Blender: interface_regions.c File Reference
interface_regions.c File Reference
interface
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "MEM_guardedalloc.h"
#include "DNA_userdef_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_dynstr.h"
#include "BLI_ghash.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm_draw.h"
#include "wm_subwindow.h"
#include "wm_window.h"
#include "RNA_access.h"
#include "BIF_gl.h"
#include "UI_interface.h"
#include "UI_interface_icons.h"
#include "UI_view2d.h"
#include "BLF_api.h"
#include "BLF_translation.h"
#include "ED_screen.h"
#include "interface_intern.h"
Classes
struct MenuEntry
struct MenuData
struct uiTooltipData
struct uiSearchItems
struct uiSearchboxData
struct uiPopupMenu
Defines
#define MENU_SEPR_HEIGHT 6
#define B_NOP -1
#define MENU_SHADOW_SIDE 8
#define MENU_SHADOW_BOTTOM 10
#define MENU_TOP 8
#define UI_TIP_LC_MAX 5
#define MAX_TOOLTIP_LINES 8
#define TIP_MARGIN_Y 2
#define TIP_BORDER_X 16.0f
#define TIP_BORDER_Y 6.0f
#define SEARCH_ITEMS 10
#define SPICK 110.0
#define FPICK 180.0
#define DPICK 6.0
#define BPICK 24.0
#define SPICK1 150.0
#define DPICK1 6.0
#define PICKER_H 150
#define PICKER_W 150
#define PICKER_SPACE 6
#define PICKER_BAR 14
#define PICKER_TOTAL_W (PICKER_W + PICKER_SPACE + PICKER_BAR)
Typedefs
typedef struct MenuEntry MenuEntry
typedef struct MenuData MenuData
typedef struct uiTooltipData uiTooltipData
typedef struct uiSearchboxData uiSearchboxData
Enumerations
enum uiTooltipLineColor {
UI_TIP_LC_MAIN, UI_TIP_LC_NORMAL, UI_TIP_LC_PYTHON, UI_TIP_LC_ALERT,
UI_TIP_LC_SUBMENU
}
Functions
static MenuData * menudata_new (const char *instr)
static void menudata_set_title (MenuData *md, const char *title, int titleicon)
static void menudata_add_item (MenuData *md, const char *str, int retval, int icon, int sepr)
static void menudata_free (MenuData *md)
static MenuData * decompose_menu_string (const char *str)
void ui_set_name_menu (uiBut *but, int value)
int ui_step_name_menu (uiBut *but, int step)
static ARegion * ui_add_temporary_region (bScreen *sc)
static void ui_remove_temporary_region (bContext *C, bScreen *sc, ARegion *ar)
static void rgb_tint (float col[3], float h, float h_strength, float v, float v_strength)
static void ui_tooltip_region_draw_cb (const bContext *UNUSED(C), ARegion *ar)
static void ui_tooltip_region_free_cb (ARegion *ar)
ARegion * ui_tooltip_create (bContext *C, ARegion *butregion, uiBut *but)
void ui_tooltip_free (bContext *C, ARegion *ar)
int uiSearchItemAdd (uiSearchItems *items, const char *name, void *poin, int iconid)
int uiSearchBoxhHeight (void)
static void ui_searchbox_select (bContext *C, ARegion *ar, uiBut *but, int step)
static void ui_searchbox_butrect (rcti *rect, uiSearchboxData *data, int itemnr)
int ui_searchbox_inside (ARegion *ar, int x, int y)
void ui_searchbox_apply (uiBut *but, ARegion *ar)
void ui_searchbox_event (bContext *C, ARegion *ar, uiBut *but, wmEvent *event)
void ui_searchbox_update (bContext *C, ARegion *ar, uiBut *but, int reset)
void ui_searchbox_autocomplete (bContext *C, ARegion *ar, uiBut *but, char *str)
static void ui_searchbox_region_draw_cb (const bContext *UNUSED(C), ARegion *ar)
static void ui_searchbox_region_free_cb (ARegion *ar)
ARegion * ui_searchbox_create (bContext *C, ARegion *butregion, uiBut *but)
void ui_searchbox_free (bContext *C, ARegion *ar)
void ui_but_search_test (uiBut *but)
static void ui_block_position (wmWindow *window, ARegion *butregion, uiBut *but, uiBlock *block)
static void ui_block_region_draw (const bContext *C, ARegion *ar)
static void ui_popup_block_clip (wmWindow *window, uiBlock *block)
void ui_popup_block_scrolltest (uiBlock *block)
uiPopupBlockHandle * ui_popup_block_create (bContext *C, ARegion *butregion, uiBut *but, uiBlockCreateFunc create_func, uiBlockHandleCreateFunc handle_create_func, void *arg)
void ui_popup_block_free (bContext *C, uiPopupBlockHandle *handle)
static void ui_block_func_MENUSTR (bContext *UNUSED(C), uiLayout *layout, void *arg_str)
void ui_block_func_ICONROW (bContext *UNUSED(C), uiLayout *layout, void *arg_but)
void ui_block_func_ICONTEXTROW (bContext *UNUSED(C), uiLayout *layout, void *arg_but)
void ui_set_but_hsv (uiBut *but)
static void ui_update_block_buts_rgb (uiBlock *block, const float rgb[3])
static void do_picker_rna_cb (bContext *UNUSED(C), void *bt1, void *UNUSED(arg))
static void do_hsv_rna_cb (bContext *UNUSED(C), void *bt1, void *UNUSED(arg))
static void do_hex_rna_cb (bContext *UNUSED(C), void *bt1, void *hexcl)
static void close_popup_cb (bContext *UNUSED(C), void *bt1, void *UNUSED(arg))
static void picker_new_hide_reveal (uiBlock *block, short colormode)
static void do_picker_new_mode_cb (bContext *UNUSED(C), void *bt1, void *UNUSED(arg))
static void circle_picker (uiBlock *block, PointerRNA *ptr, PropertyRNA *prop)
static void square_picker (uiBlock *block, PointerRNA *ptr, PropertyRNA *prop, int type)
static void uiBlockPicker (uiBlock *block, float rgba[4], PointerRNA *ptr, PropertyRNA *prop)
static int ui_picker_small_wheel_cb (const bContext *UNUSED(C), uiBlock *block, wmEvent *event)
uiBlock * ui_block_func_COL (bContext *C, uiPopupBlockHandle *handle, void *arg_but)
static int ui_popup_string_hash (char *str)
static int ui_popup_menu_hash (const char *str)
uiBut * ui_popup_menu_memory (uiBlock *block, uiBut *but)
static uiBlock * ui_block_func_POPUP (bContext *C, uiPopupBlockHandle *handle, void *arg_pup)
uiPopupBlockHandle * ui_popup_menu_create (bContext *C, ARegion *butregion, uiBut *but, uiMenuCreateFunc menu_func, void *arg, char *str)
uiPopupMenu * uiPupMenuBegin (bContext *C, const char *title, int icon)
void uiPupMenuEnd (bContext *C, uiPopupMenu *pup)
uiLayout * uiPupMenuLayout (uiPopupMenu *pup)
static void operator_name_cb (bContext *C, void *arg, int retval)
static void operator_cb (bContext *C, void *arg, int retval)
static void confirm_cancel_operator (void *opv)
static void vconfirm_opname (bContext *C, const char *opname, const char *title, const char *itemfmt, va_list ap)
static void confirm_operator (bContext *C, wmOperator *op, const char *title, const char *item)
void uiPupMenuOkee (bContext *C, const char *opname, const char *str,...)
void uiPupMenuSaveOver (bContext *C, wmOperator *op, const char *filename)
void uiPupMenuNotice (bContext *C, const char *str,...)
void uiPupMenuError (bContext *C, const char *str,...)
void uiPupMenuReports (bContext *C, ReportList *reports)
void uiPupMenuInvoke (bContext *C, const char *idname)
void uiPupBlockO (bContext *C, uiBlockCreateFunc func, void *arg, const char *opname, int opcontext)
void uiPupBlock (bContext *C, uiBlockCreateFunc func, void *arg)
void uiPupBlockEx (bContext *C, uiBlockCreateFunc func, uiBlockHandleFunc popup_func, uiBlockCancelFunc cancel_func, void *arg)
void uiPupBlockClose (bContext *C, uiBlock *block)
float * ui_block_hsv_get (uiBlock *block)
Detailed Description
Definition in file interface_regions.c.
Define Documentation
#define B_NOP -1
Definition at line 72 of file interface_regions.c.
Referenced by ui_block_func_ICONROW(), ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), and uiTemplateImage().
#define BPICK 24.0
Definition at line 1835 of file interface_regions.c.
#define DPICK 6.0
Definition at line 1834 of file interface_regions.c.
#define DPICK1 6.0
Definition at line 2015 of file interface_regions.c.
#define FPICK 180.0
Definition at line 1833 of file interface_regions.c.
#define MAX_TOOLTIP_LINES 8
Definition at line 325 of file interface_regions.c.
Referenced by ui_tooltip_create().
#define MENU_SEPR_HEIGHT 6
Definition at line 71 of file interface_regions.c.
#define MENU_SHADOW_BOTTOM 10
Definition at line 74 of file interface_regions.c.
Referenced by ui_popup_block_clip(), ui_popup_block_create(), ui_searchbox_create(), and ui_tooltip_create().
#define MENU_SHADOW_SIDE 8
Definition at line 73 of file interface_regions.c.
Referenced by ui_popup_block_clip(), ui_popup_block_create(), ui_searchbox_create(), and ui_tooltip_create().
#define MENU_TOP 8
Definition at line 75 of file interface_regions.c.
Referenced by ui_popup_block_clip(), ui_popup_block_create(), ui_searchbox_butrect(), ui_tooltip_create(), and uiSearchBoxhHeight().
#define PICKER_BAR 14
Definition at line 2020 of file interface_regions.c.
Referenced by circle_picker(), and square_picker().
#define PICKER_H 150
Definition at line 2017 of file interface_regions.c.
Referenced by circle_picker(), and square_picker().
#define PICKER_SPACE 6
Definition at line 2019 of file interface_regions.c.
Referenced by circle_picker(), and square_picker().
#define PICKER_TOTAL_W (PICKER_W + PICKER_SPACE + PICKER_BAR)
Definition at line 2022 of file interface_regions.c.
Referenced by square_picker(), and uiBlockPicker().
#define PICKER_W 150
Definition at line 2018 of file interface_regions.c.
Referenced by circle_picker().
#define SEARCH_ITEMS 10
Definition at line 716 of file interface_regions.c.
Referenced by ui_searchbox_butrect(), ui_searchbox_create(), and uiSearchBoxhHeight().
#define SPICK 110.0
Definition at line 1832 of file interface_regions.c.
#define SPICK1 150.0
Definition at line 2014 of file interface_regions.c.
#define TIP_BORDER_X 16.0f
Referenced by ui_tooltip_create().
#define TIP_BORDER_Y 6.0f
Referenced by ui_tooltip_create().
#define TIP_MARGIN_Y 2
Referenced by ui_tooltip_create().
#define UI_TIP_LC_MAX 5
Definition at line 323 of file interface_regions.c.
Referenced by ui_tooltip_region_draw_cb().
Typedef Documentation
typedef struct MenuData MenuData
typedef struct MenuEntry MenuEntry
typedef struct uiSearchboxData uiSearchboxData
typedef struct uiTooltipData uiTooltipData
Enumeration Type Documentation
enum uiTooltipLineColor
Enumerator:
UI_TIP_LC_MAIN
UI_TIP_LC_NORMAL
UI_TIP_LC_PYTHON
UI_TIP_LC_ALERT
UI_TIP_LC_SUBMENU
Definition at line 316 of file interface_regions.c.
Function Documentation
static void circle_picker (uiBlock * block, PointerRNA * ptr, PropertyRNA * prop) [static]
Definition at line 2024 of file interface_regions.c.
References do_picker_rna_cb(), HSVCIRCLE, HSVCUBE, NULL, PICKER_BAR, PICKER_H, PICKER_SPACE, PICKER_W, UI_GRAD_V_ALT, uiButSetFunc(), and uiDefButR_prop().
Referenced by uiBlockPicker().
static void close_popup_cb (bContext * UNUSEDC, void * bt1, void * UNUSEDarg) [static]
Definition at line 1966 of file interface_regions.c.
References uiBut::block, uiBlock::handle, uiPopupBlockHandle::menuretval, and UI_RETURN_OK.
Referenced by uiBlockPicker().
static void confirm_cancel_operator (void * opv) [static]
Definition at line 2525 of file interface_regions.c.
References WM_operator_free().
Referenced by confirm_operator().
static void confirm_operator (bContext * C, wmOperator * op, const char * title, const char * item) [static]
Definition at line 2546 of file interface_regions.c.
References BLI_snprintf(), uiPopupBlockHandle::cancel_func, confirm_cancel_operator(), NULL, operator_cb(), uiPopupBlockHandle::popup_arg, uiPopupBlockHandle::popup_func, and ui_popup_menu_create().
Referenced by uiPupMenuSaveOver().
static MenuData* decompose_menu_string (const char * str) [static]
Parse menu description strings, string is of the form "[sss%t|]{(sss[%xNN]|), (%l|), (sss%l|)}", sssst indicates the menu title, sss or sssxNN indicates an option, if xNN is given then NN is the return value if that option is selected otherwise the return value is the index of the option (starting with 1). l indicates a seperator, sssl indicates a label and new column.
Parameters:
str String to be parsed.
Return values:
new menudata structure, free with menudata_free()
Definition at line 160 of file interface_regions.c.
References BLI_strdup(), menudata_add_item(), menudata_new(), menudata_set_title(), MenuData::nitems, and NULL.
Referenced by ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_set_name_menu(), and ui_step_name_menu().
static void do_hex_rna_cb (bContext * UNUSEDC, void * bt1, void * hexcl) [static]
Definition at line 1945 of file interface_regions.c.
References BLI_PR_NONE, uiBut::block, uiBlock::color_profile, uiBlock::handle, hex_to_rgb(), uiPopupBlockHandle::menuretval, srgb_to_linearrgb_v3_v3(), UI_RETURN_UPDATE, and ui_update_block_buts_rgb().
Referenced by uiBlockPicker().
static void do_hsv_rna_cb (bContext * UNUSEDC, void * bt1, void * UNUSEDarg) [static]
Definition at line 1930 of file interface_regions.c.
References uiBut::block, uiBlock::handle, hsv_to_rgb(), uiPopupBlockHandle::menuretval, ui_block_hsv_get(), UI_RETURN_UPDATE, and ui_update_block_buts_rgb().
Referenced by uiBlockPicker().
static void do_picker_new_mode_cb (bContext * UNUSEDC, void * bt1, void * UNUSEDarg) [static]
Definition at line 2006 of file interface_regions.c.
References uiBut::block, picker_new_hide_reveal(), and ui_get_but_val().
Referenced by uiBlockPicker().
static void do_picker_rna_cb (bContext * UNUSEDC, void * bt1, void * UNUSEDarg) [static]
Definition at line 1913 of file interface_regions.c.
References uiBut::block, uiBlock::handle, uiPopupBlockHandle::menuretval, RNA_property_float_get_array(), uiBut::rnapoin, uiBut::rnaprop, UI_RETURN_UPDATE, and ui_update_block_buts_rgb().
Referenced by circle_picker(), square_picker(), and uiBlockPicker().
static void menudata_add_item (MenuData * md, const char * str, int retval, int icon, int sepr) [static]
Definition at line 116 of file interface_regions.c.
References MenuEntry::icon, MenuData::items, MenuData::itemssize, MEM_freeN(), MEM_mallocN(), MenuData::nitems, MenuEntry::retval, MenuEntry::sepr, MenuEntry::str, and str.
Referenced by decompose_menu_string().
static void menudata_free (MenuData * md) [static]
Definition at line 138 of file interface_regions.c.
References MenuData::instr, MenuData::items, and MEM_freeN().
Referenced by ui_block_func_ICONTEXTROW(), ui_block_func_MENUSTR(), ui_set_name_menu(), and ui_step_name_menu().
static MenuData* menudata_new (const char * instr) [static]
Definition at line 95 of file interface_regions.c.
References MenuData::instr, MenuData::items, MenuData::itemssize, MEM_mallocN(), MenuData::nitems, NULL, MenuData::title, and MenuData::titleicon.
Referenced by decompose_menu_string().
static void menudata_set_title (MenuData * md, const char * title, int titleicon) [static]
Definition at line 108 of file interface_regions.c.
References MenuData::title, and MenuData::titleicon.
Referenced by decompose_menu_string().
static void operator_cb (bContext * C, void * arg, int retval) [static]
Definition at line 2515 of file interface_regions.c.
References WM_operator_call(), and WM_operator_free().
Referenced by confirm_operator().
static void operator_name_cb (bContext * C, void * arg, int retval) [static]
Definition at line 2507 of file interface_regions.c.
References NULL, WM_OP_EXEC_DEFAULT, and WM_operator_name_call().
Referenced by vconfirm_opname().
static void picker_new_hide_reveal (uiBlock * block, short colormode) [static]
Definition at line 1975 of file interface_regions.c.
References uiBlock::buttons, ELEM3, ListBase::first, uiBut::flag, LABEL, uiBut::next, NUMSLI, uiBut::str, TEX, uiBut::type, and UI_HIDDEN.
Referenced by do_picker_new_mode_cb(), and uiBlockPicker().
static void rgb_tint (float col[3], float h, float h_strength, float v, float v_strength) [static]
Definition at line 335 of file interface_regions.c.
References hsv_to_rgb(), and rgb_to_hsv().
Referenced by ui_tooltip_region_draw_cb().
static void square_picker (uiBlock * block, PointerRNA * ptr, PropertyRNA * prop, int type) [static]
Definition at line 2038 of file interface_regions.c.
References do_picker_rna_cb(), HSVCUBE, NULL, PICKER_BAR, PICKER_H, PICKER_SPACE, PICKER_TOTAL_W, uiButSetFunc(), and uiDefButR_prop().
Referenced by uiBlockPicker().
static ARegion* ui_add_temporary_region (bScreen * sc) [static]
Definition at line 291 of file interface_regions.c.
References ARegion::alignment, BLI_addtail(), MEM_callocN(), bScreen::regionbase, ARegion::regiontype, RGN_ALIGN_FLOAT, and RGN_TYPE_TEMPORARY.
Referenced by ui_popup_block_create(), ui_searchbox_create(), and ui_tooltip_create().
uiBlock* ui_block_func_COL (bContext * C, uiPopupBlockHandle * handle, void * arg_but)
Definition at line 2195 of file interface_regions.c.
References BLI_PR_NONE, uiBlock::block_event_func, uiBlock::color_profile, copy_v3_v3(), uiBlock::direction, uiBut::editvec, uiBlock::flag, PROP_COLOR_GAMMA, uiPopupBlockHandle::region, uiPopupBlockHandle::retvec, RNA_property_subtype(), uiBut::rnapoin, uiBut::rnaprop, UI_BLOCK_KEEP_OPEN, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_OUT_1, UI_BLOCK_REDRAW, UI_EMBOSS, ui_picker_small_wheel_cb(), UI_TOP, uiBeginBlock(), uiBlockPicker(), uiBlockSetFlag(), and uiBoundsBlock().
Referenced by ui_blockopen_begin().
void ui_block_func_ICONROW (bContext * UNUSEDC, uiLayout * layout, void * arg_but)
Definition at line 1770 of file interface_regions.c.
References B_NOP, BUTM, FLO, uiBlock::handle, uiBut::hardmax, uiBut::hardmin, uiBut::icon, uiPopupBlockHandle::retvalue, UI_BLOCK_MOVEMOUSE_QUIT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetFlag(), uiDefIconButF(), and uiLayoutGetBlock().
void ui_block_func_ICONTEXTROW (bContext * UNUSEDC, uiLayout * layout, void * arg_but)
Definition at line 1784 of file interface_regions.c.
References B_NOP, BUTM, decompose_menu_string(), FLO, uiBlock::handle, uiBut::hardmin, uiBut::icon, MenuData::items, LABEL, menudata_free(), MenuData::nitems, NULL, MenuEntry::retval, uiPopupBlockHandle::retvalue, MenuEntry::sepr, MenuEntry::str, uiBut::str, MenuData::title, UI_BLOCK_MOVEMOUSE_QUIT, UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetFlag(), uiDefBut(), uiDefIconTextButF(), uiItemS(), and uiLayoutGetBlock().
static void ui_block_func_MENUSTR (bContext * UNUSEDC, uiLayout * layout, void * arg_str) [static]
Definition at line 1673 of file interface_regions.c.
References B_NOP, BUTM, uiBlock::buttons, decompose_menu_string(), uiBut::flag, uiBlock::flag, FLO, uiBlock::handle, MenuEntry::icon, MenuData::items, ListBase::last, menudata_free(), MenuData::nitems, NULL, MenuEntry::retval, uiPopupBlockHandle::retvalue, MenuEntry::sepr, split(), MenuEntry::str, MenuData::title, MenuData::titleicon, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_NO_FLIP, UI_TEXT_LEFT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetFlag(), uiDefButF(), uiDefIconTextButF(), uiItemL(), uiLayoutColumn(), uiLayoutGetBlock(), and uiLayoutSplit().
Referenced by ui_popup_menu_create().
static uiBlock* ui_block_func_POPUP (bContext * C, uiPopupBlockHandle * handle, void * arg_pup) [static]
Definition at line 2286 of file interface_regions.c.
References BLI_findindex(), uiPopupMenu::block, uiPopupMenu::but, uiBlock::buttons, CTX_wm_area(), CTX_wm_region(), uiBlock::direction, ListBase::first, uiBlock::flag, uiBlock::handle, HEADERDOWN, ScrArea::headertype, uiPopupMenu::layout, uiPopupMenu::menu_arg, uiBut::menu_create_func, uiPopupMenu::menu_func, MIN2, uiBlock::minbounds, uiBut::next, NULL, uiPopupMenu::popup, PULLDOWN, uiPopupBlockHandle::region, ARegion::regiontype, RGN_TYPE_HEADER, uiPopupMenu::slideout, uiBut::type, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_NUMSELECT, UI_BLOCK_POPUP_MEMORY, UI_BLOCK_REDRAW, UI_BLOCK_RET_1, UI_DOWN, ui_popup_menu_memory(), UI_RIGHT, UI_TOP, UI_UNIT_Y, uiBlockFlipOrder(), uiBlockLayoutResolve(), ARegion::uiblocks, uiBlockSetDirection(), uiBlockSetFlag(), uiBlockSetRegion(), uiEndBlock(), uiMenuPopupBoundsBlock(), uiTextBoundsBlock(), uiBut::x1, uiBut::x2, and uiBut::y1.
Referenced by ui_popup_menu_create(), and uiPupMenuEnd().
float* ui_block_hsv_get (uiBlock * block)
Definition at line 2739 of file interface_regions.c.
References uiBlock::_hsv.
Referenced by do_hsv_rna_cb(), ui_do_but_BLOCK(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_draw_but_HSVCIRCLE(), ui_draw_but_HSVCUBE(), ui_ndofedit_but_HSVCIRCLE(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCIRCLE(), ui_numedit_but_HSVCUBE(), ui_picker_small_wheel_cb(), ui_set_but_hsv(), ui_update_block_buts_rgb(), and uiBlockPicker().
static void ui_block_position (wmWindow * window, ARegion * butregion, uiBut * but, uiBlock * block) [static]
Definition at line 1262 of file interface_regions.c.
References uiBut::aspect, uiBlock::aspect, BLI_addhead(), BLI_duplicatelist(), BLI_freelistN(), uiBut::block, uiBlock::buttons, uiBlock::direction, ListBase::first, left(), uiBlock::maxx, uiBlock::maxy, MEM_callocN(), uiBlock::minx, uiBlock::miny, uiBut::next, uiSafetyRct::parent, uiBlock::saferct, uiBlock::safety, uiSafetyRct::safety, ui_block_to_window_fl(), UI_CENTER, ui_check_but(), UI_DIRECTION, UI_DOWN, UI_LEFT, UI_RIGHT, UI_SHIFT_FLIPPED, UI_TOP, uiBlockFlipOrder(), wm_window_get_size(), uiBut::x1, uiBut::x2, rctf::xmax, rctf::xmin, uiBlock::xofs, uiBut::y1, uiBut::y2, rctf::ymax, rctf::ymin, and uiBlock::yofs.
Referenced by ui_popup_block_create().
static void ui_block_region_draw (const bContext * C, ARegion * ar) [static]
Definition at line 1490 of file interface_regions.c.
References ListBase::first, uiBlock::next, ARegion::uiblocks, and uiDrawBlock().
Referenced by ui_popup_block_create().
void ui_but_search_test (uiBut * but)
Definition at line 1218 of file interface_regions.c.
References uiBut::block, uiBut::drawstr, uiBlock::evil_C, uiBut::hardmax, uiSearchItems::maxitem, uiSearchItems::maxstrlen, MEM_callocN(), MEM_freeN(), uiSearchItems::more, uiSearchItems::names, PROP_STRING, RNA_property_type(), uiBut::rnaprop, uiBut::search_arg, uiBut::search_func, uiSearchItems::totitem, UI_BUT_REDALERT, and uiButSetFlag().
Referenced by uiButSetSearchFunc().
static int ui_picker_small_wheel_cb (const bContext * UNUSEDC, uiBlock * block, wmEvent * event) [static]
Definition at line 2158 of file interface_regions.c.
References uiBut::active, add(), uiBlock::buttons, CLAMPIS, ListBase::first, uiBlock::handle, hsv_to_rgb(), HSVCUBE, uiPopupBlockHandle::menuretval, uiBut::next, NULL, rgb_to_hsv_compat(), wmEvent::type, uiBut::type, ui_block_hsv_get(), ui_get_but_vectorf(), UI_RETURN_UPDATE, ui_set_but_vectorf(), ui_update_block_buts_rgb(), WHEELDOWNMOUSE, and WHEELUPMOUSE.
Referenced by ui_block_func_COL().
static void ui_popup_block_clip (wmWindow * window, uiBlock * block) [static]
Definition at line 1498 of file interface_regions.c.
References uiBlock::maxx, uiBlock::maxy, MENU_SHADOW_BOTTOM, MENU_SHADOW_SIDE, MENU_TOP, uiBlock::minx, uiBlock::miny, and wm_window_get_size().
Referenced by ui_popup_block_create().
uiPopupBlockHandle* ui_popup_block_create (bContext * C, ARegion * butregion, uiBut * but, uiBlockCreateFunc create_func, uiBlockHandleCreateFunc handle_create_func, void * arg)
Definition at line 1556 of file interface_regions.c.
References uiBlock::aspect, BLI_addhead(), BLOCK, uiBut::block, uiBlock::buttons, create_func(), uiPopupBlockHandle::ctx_area, uiPopupBlockHandle::ctx_region, CTX_wm_area(), CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), ARegionType::draw, ED_region_init(), ED_region_tag_redraw(), ELEM, uiBlock::endblock, ListBase::first, uiBlock::flag, uiBlock::handle, ARegion::handlers, uiBlock::maxx, uiBlock::maxy, MEM_callocN(), MEM_freeN(), MENU_SHADOW_BOTTOM, MENU_SHADOW_SIDE, MENU_TOP, uiBlock::minx, uiBlock::miny, uiBut::next, PULLDOWN, uiPopupBlockHandle::region, ARegion::regiondata, uiBlock::saferct, uiBlock::safety, uiSafetyRct::safety, ARegion::swinid, ARegion::type, uiBut::type, UI_add_region_handlers(), ui_add_temporary_region(), UI_BLOCK_LOOP, UI_BLOCK_NUMSELECT, UI_BLOCK_POPUP, ui_block_position(), ui_block_region_draw(), ui_popup_block_clip(), ui_popup_block_scrolltest(), uiEndBlock(), uiBlock::winmat, ARegion::winrct, wm_subwindow_getmatrix(), wmSubWindowSet(), uiBut::x1, uiBut::x2, rcti::xmax, rcti::xmin, uiBlock::xofs, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by ui_blockopen_begin(), ui_popup_menu_create(), uiPupBlockEx(), uiPupBlockO(), and uiPupMenuEnd().
void ui_popup_block_free (bContext * C, uiPopupBlockHandle * handle)
Definition at line 1661 of file interface_regions.c.
References CTX_wm_manager(), CTX_wm_screen(), CTX_wm_window(), MEM_freeN(), uiPopupBlockHandle::region, uiPopupBlockHandle::scrolltimer, ui_remove_temporary_region(), and WM_event_remove_timer().
Referenced by ui_blockopen_end(), ui_handler_popup(), ui_handler_remove_popup(), and uiPupBlockClose().
void ui_popup_block_scrolltest (uiBlock * block)
Definition at line 1515 of file interface_regions.c.
References uiBlock::buttons, uiBlock::direction, ListBase::first, uiBut::flag, uiBlock::flag, ListBase::last, uiBlock::maxy, uiBlock::miny, uiBut::next, uiBut::prev, UI_BLOCK_CLIPBOTTOM, UI_BLOCK_CLIPTOP, UI_BLOCK_NO_FLIP, UI_SCROLLED, UI_TOP, uiBut::y1, and uiBut::y2.
Referenced by ui_menu_scroll(), and ui_popup_block_create().
uiPopupBlockHandle* ui_popup_menu_create (bContext * C, ARegion * butregion, uiBut * but, uiMenuCreateFunc menu_func, void * arg, char * str)
Definition at line 2385 of file interface_regions.c.
References uiPopupMenu::block, uiBut::block, uiPopupMenu::but, uiBut::context, CTX_wm_window(), wmWindow::eventstate, uiBlock::flag, uiPopupMenu::layout, MEM_callocN(), MEM_freeN(), uiPopupMenu::menu_arg, uiPopupMenu::menu_func, wmWindow::modalhandlers, uiPopupMenu::mx, uiPopupMenu::my, NULL, uiPopupMenu::popup, uiPopupBlockHandle::popup, PROP_ENUM, RNA_property_type(), uiBut::rnaprop, uiPopupMenu::slideout, str, UI_add_popup_handlers(), ui_block_func_MENUSTR(), ui_block_func_POPUP(), UI_BLOCK_LOOP, UI_BLOCK_NO_FLIP, UI_EMBOSSP, UI_GetStyle(), UI_LAYOUT_MENU, UI_LAYOUT_VERTICAL, ui_popup_block_create(), uiBeginBlock(), uiBlockLayout(), uiLayoutContextCopy(), uiLayoutSetOperatorContext(), WM_event_add_mousemove(), WM_OP_INVOKE_REGION_WIN, wmEvent::x, and wmEvent::y.
Referenced by confirm_operator(), ui_blockopen_begin(), uiPupMenuReports(), and vconfirm_opname().
static int ui_popup_menu_hash (const char * str) [static]
Definition at line 2240 of file interface_regions.c.
References BLI_ghashutil_strhash().
Referenced by uiPupMenuBegin().
uiBut* ui_popup_menu_memory (uiBlock * block, uiBut * but)
Definition at line 2246 of file interface_regions.c.
References uiBlock::buttons, ListBase::first, hash, uiBut::next, NULL, uiBlock::puphash, uiBut::str, and ui_popup_string_hash().
Referenced by button_activate_exit(), and ui_block_func_POPUP().
static int ui_popup_string_hash (char * str) [static]
Definition at line 2227 of file interface_regions.c.
References BLI_ghashutil_strhash(), and hash.
Referenced by ui_popup_menu_memory().
static void ui_remove_temporary_region (bContext * C, bScreen * sc, ARegion * ar) [static]
Definition at line 304 of file interface_regions.c.
References BKE_area_region_free(), BLI_freelinkN(), CTX_wm_window(), ED_region_exit(), NULL, bScreen::regionbase, and wm_draw_region_clear().
Referenced by ui_popup_block_free(), ui_searchbox_free(), and ui_tooltip_free().
void ui_searchbox_apply (uiBut * but, ARegion * ar)
Definition at line 838 of file interface_regions.c.
References uiSearchboxData::active, BLI_strncpy(), data, uiBut::editstr, uiBut::func_arg2, uiSearchboxData::items, uiSearchItems::maxstrlen, uiSearchItems::names, NULL, uiSearchItems::pointers, and ARegion::regiondata.
Referenced by ui_textedit_end().
void ui_searchbox_autocomplete (bContext * C, ARegion * ar, uiBut * but, char * str)
Definition at line 961 of file interface_regions.c.
References autocomplete_begin(), autocomplete_end(), uiSearchItems::autocpl, data, uiBut::editstr, uiSearchboxData::items, NULL, ARegion::regiondata, uiBut::search_arg, uiBut::search_func, and ui_get_but_string_max_length().
Referenced by ui_textedit_autocomplete().
static void ui_searchbox_butrect (rcti * rect, uiSearchboxData * data, int itemnr) [static]
Definition at line 796 of file interface_regions.c.
References uiSearchboxData::bbox, MENU_TOP, uiSearchboxData::preview, uiSearchboxData::prv_cols, uiSearchboxData::prv_rows, SEARCH_ITEMS, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_searchbox_event(), and ui_searchbox_region_draw_cb().
ARegion* ui_searchbox_create (bContext * C, ARegion * butregion, uiBut * but)
Definition at line 1060 of file interface_regions.c.
References uiBut::a1, uiBut::a2, uiFontStyle::align, uiBlock::aspect, uiSearchboxData::bbox, uiBut::block, CTX_wm_screen(), CTX_wm_window(), View2D::cur, data, ARegionType::draw, ED_region_init(), ED_region_tag_redraw(), uiBlock::flag, ARegionType::free, uiSearchboxData::fstyle, uiBut::hardmax, uiSearchItems::icons, uiSearchboxData::items, uiSearchItems::maxitem, uiSearchItems::maxstrlen, uiBlock::maxy, MEM_callocN(), MENU_SHADOW_BOTTOM, MENU_SHADOW_SIDE, uiBlock::miny, uiSearchItems::names, uiSearchboxData::noback, NULL, Panel::ofsx, Panel::ofsy, uiBlock::panel, uiSearchItems::pointers, uiFontStyle::points, uiSearchboxData::preview, uiSearchboxData::prv_cols, uiSearchboxData::prv_rows, ARegion::regiondata, SEARCH_ITEMS, uiSearchItems::totitem, ARegion::type, ui_add_temporary_region(), UI_BLOCK_LOOP, ui_fontscale(), UI_GetStyle(), ui_searchbox_region_draw_cb(), ui_searchbox_region_free_cb(), UI_STYLE_TEXT_CENTER, UI_view2d_to_region_no_clip(), uiSearchBoxhHeight(), uiStyleFontSet(), ARegion::v2d, uiStyle::widget, ARegion::winrct, wm_window_get_size(), uiBut::x1, uiBut::x2, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by ui_textedit_begin().
void ui_searchbox_event (bContext * C, ARegion * ar, uiBut * but, wmEvent * event)
Definition at line 856 of file interface_regions.c.
References uiSearchboxData::active, BLI_in_rcti(), data, DOWNARROWKEY, uiSearchboxData::items, MOUSEMOVE, ARegion::regiondata, uiSearchItems::totitem, wmEvent::type, ui_searchbox_butrect(), ui_searchbox_select(), UPARROWKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, ARegion::winrct, wmEvent::x, rcti::xmin, wmEvent::y, and rcti::ymin.
Referenced by ui_do_but_textedit().
void ui_searchbox_free (bContext * C, ARegion * ar)
Definition at line 1211 of file interface_regions.c.
References CTX_wm_screen(), and ui_remove_temporary_region().
Referenced by ui_textedit_end().
int ui_searchbox_inside (ARegion * ar, int x, int y)
Definition at line 830 of file interface_regions.c.
References uiSearchboxData::bbox, BLI_in_rcti(), data, ARegion::regiondata, ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by ui_do_but_textedit().
static void ui_searchbox_region_draw_cb (const bContext * UNUSEDC, ARegion * ar) [static]
Definition at line 975 of file interface_regions.c.
References uiSearchboxData::active, uiSearchboxData::bbox, data, uiSearchboxData::fstyle, uiSearchItems::icons, uiSearchboxData::items, uiSearchItems::maxitem, uiSearchItems::more, uiSearchItems::names, uiSearchboxData::noback, NULL, uiSearchItems::offset, uiSearchboxData::preview, ARegion::regiondata, uiSearchItems::totitem, UI_ACTIVE, ui_draw_menu_item(), ui_draw_preview_item(), ui_draw_search_back(), UI_icon_draw(), ui_searchbox_butrect(), ARegion::winx, ARegion::winy, wmOrtho2(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_searchbox_create().
static void ui_searchbox_region_free_cb (ARegion * ar) [static]
Definition at line 1043 of file interface_regions.c.
References data, uiSearchItems::icons, uiSearchboxData::items, uiSearchItems::maxitem, MEM_freeN(), uiSearchItems::names, NULL, uiSearchItems::pointers, and ARegion::regiondata.
Referenced by ui_searchbox_create().
static void ui_searchbox_select (bContext * C, ARegion * ar, uiBut * but, int step) [static]
Definition at line 765 of file interface_regions.c.
References uiSearchboxData::active, data, ED_region_tag_redraw(), uiSearchboxData::items, uiSearchItems::more, uiSearchItems::offset, ARegion::regiondata, step(), uiSearchItems::totitem, and ui_searchbox_update().
Referenced by ui_searchbox_event(), and ui_searchbox_update().
void ui_searchbox_update (bContext * C, ARegion * ar, uiBut * but, int reset)
Definition at line 890 of file interface_regions.c.
References uiSearchboxData::active, uiSearchItems::active, data, ED_region_tag_redraw(), uiBut::editstr, uiBut::func_arg2, uiSearchboxData::items, uiSearchItems::maxitem, uiSearchItems::more, uiSearchItems::names, NULL, uiSearchItems::offset, uiSearchItems::offset_i, ARegion::regiondata, uiBut::search_arg, uiBut::search_func, uiSearchItems::totitem, and ui_searchbox_select().
Referenced by ui_but_copy_paste(), ui_do_but_textedit(), ui_searchbox_select(), and ui_textedit_begin().
void ui_set_but_hsv (uiBut * but)
Definition at line 1838 of file interface_regions.c.
References uiBut::block, hsv_to_rgb(), ui_block_hsv_get(), and ui_set_but_vectorf().
Referenced by ui_do_but_HSVCIRCLE().
void ui_set_name_menu (uiBut * but, int value)
Definition at line 235 of file interface_regions.c.
References BLI_strncpy(), decompose_menu_string(), uiBut::drawstr, i, MenuData::items, menudata_free(), MenuData::nitems, MenuEntry::retval, MenuEntry::str, and uiBut::str.
Referenced by ui_check_but().
int ui_step_name_menu (uiBut * but, int step)
Definition at line 251 of file interface_regions.c.
References decompose_menu_string(), i, MenuData::items, menudata_free(), MenuData::nitems, MenuEntry::retval, uiBut::str, and ui_get_but_val().
Referenced by ui_do_but_BLOCK().
ARegion* ui_tooltip_create (bContext * C, ARegion * butregion, uiBut * but) [read]
Definition at line 414 of file interface_regions.c.
References uiFontStyle::align, uiBlock::aspect, assert, uiTooltipData::bbox, BLF_height_max(), BLF_width(), BLI_snprintf(), BLI_strncpy(), uiBut::block, uiTooltipData::color_id, CTX_wm_operator_poll_msg_get(), CTX_wm_operator_poll_msg_set(), CTX_wm_screen(), CTX_wm_window(), View2D::cur, data, PointerRNA::data, EnumPropertyItem::description, ARegionType::draw, ED_region_init(), ED_region_tag_redraw(), ELEM, ELEM3, uiBut::flag, uiBlock::flag, ARegionType::free, uiTooltipData::fstyle, uiBut::hardmax, i, PointerRNA::id, wmOperatorType::idname, MenuType::idname, IDPOIN, if(), ID::lib, uiTooltipData::lineh, uiTooltipData::lines, MAX2, MAX_TOOLTIP_LINES, MEM_callocN(), MEM_freeN(), MENU, MENU_SHADOW_BOTTOM, MENU_SHADOW_SIDE, MENU_TOP, mt, Library::name, EnumPropertyItem::name, NULL, Panel::ofsx, Panel::ofsy, uiBut::opcontext, uiBut::opptr, uiBut::optype, uiBlock::panel, PROP_ENUM, PROP_FLOAT, PROP_UNIT_ROTATION, PULLDOWN, ARegion::regiondata, RNA_property_array_check(), RNA_property_description(), RNA_property_enum_items_gettexted(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_identifier(), RNA_property_type(), RNA_struct_identifier(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, ROW, SEARCH_MENU, uiTooltipData::spaceh, str, TEX, uiBut::tip, TIP_, TIP_BORDER_X, TIP_BORDER_Y, TIP_MARGIN_Y, uiTooltipData::toth, uiTooltipData::totline, TRUE, PointerRNA::type, ARegion::type, uiBut::type, ui_add_temporary_region(), UI_BLOCK_LOOP, ui_but_anim_expression_get(), UI_BUT_DISABLED, UI_BUT_DRIVEN, UI_BUT_NO_TOOLTIP, ui_get_but_string(), ui_get_but_val(), UI_GetStyle(), UI_STYLE_TEXT_CENTER, UI_TIP_LC_ALERT, UI_TIP_LC_MAIN, UI_TIP_LC_NORMAL, UI_TIP_LC_PYTHON, UI_TIP_LC_SUBMENU, ui_tooltip_region_draw_cb(), ui_tooltip_region_free_cb(), UI_view2d_to_region_no_clip(), uiButGetMenuType(), uiButGetOperatorPtrRNA(), uiButGetUnitType(), uiFontStyle::uifont_id, uiStyleFontSet(), USER_TOOLTIPS_PYTHON, ARegion::v2d, uiStyle::widget, ARegion::winrct, WM_key_event_operator_string(), WM_operator_poll_context(), WM_operator_pystring(), wm_window_get_size(), uiBut::x1, uiBut::x2, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, uiBut::y1, rcti::ymax, and rcti::ymin.
Referenced by ui_handle_button_event().
void ui_tooltip_free (bContext * C, ARegion * ar)
Definition at line 684 of file interface_regions.c.
References CTX_wm_screen(), and ui_remove_temporary_region().
Referenced by button_timers_tooltip_remove().
static void ui_tooltip_region_draw_cb (const bContext * UNUSEDC, ARegion * ar) [static]
Definition at line 351 of file interface_regions.c.
References uiTooltipData::bbox, uiTooltipData::color_id, copy_v3_v3(), data, uiTooltipData::fstyle, i, uiWidgetColors::inner, uiTooltipData::lineh, uiTooltipData::lines, NULL, ARegion::regiondata, rgb_tint(), rgb_to_grayscale(), rgb_uchar_to_float(), uiTooltipData::spaceh, uiWidgetColors::text, uiTooltipData::toth, uiTooltipData::totline, ui_draw_tooltip_background(), UI_GetStyle(), UI_TIP_LC_ALERT, UI_TIP_LC_MAIN, UI_TIP_LC_MAX, UI_TIP_LC_NORMAL, UI_TIP_LC_PYTHON, UI_TIP_LC_SUBMENU, ui_tooltip_get_theme(), uiStyleFontDraw(), uiStyleFontSet(), rcti::ymax, and rcti::ymin.
Referenced by ui_tooltip_create().
static void ui_tooltip_region_free_cb (ARegion * ar) [static]
Definition at line 405 of file interface_regions.c.
References data, MEM_freeN(), NULL, and ARegion::regiondata.
Referenced by ui_tooltip_create().
static void ui_update_block_buts_rgb (uiBlock * block, const float rgb[3]) [static]
Definition at line 1848 of file interface_regions.c.
References BLI_PR_NONE, BLI_snprintf(), uiBlock::buttons, uiBlock::color_profile, copy_v3_v3(), ListBase::first, FTOCHAR, linearrgb_to_srgb_v3_v3(), uiBut::next, uiBut::poin, rgb_to_hsv_compat(), uiBut::rnaprop, uiBut::str, ui_block_hsv_get(), ui_check_but(), ui_set_but_val(), and ui_set_but_vectorf().
Referenced by do_hex_rna_cb(), do_hsv_rna_cb(), do_picker_rna_cb(), and ui_picker_small_wheel_cb().
static void uiBlockPicker (uiBlock * block, float rgba[4], PointerRNA * ptr, PropertyRNA * prop) [static]
Definition at line 2054 of file interface_regions.c.
References BLI_PR_NONE, BLI_snprintf(), BLI_strncpy(), BUT, circle_picker(), close_popup_cb(), uiBlock::color_profile, copy_v3_v3(), do_hex_rna_cb(), do_hsv_rna_cb(), do_picker_new_mode_cb(), do_picker_rna_cb(), FLT_MAX, FTOCHAR, IFACE_, LABEL, linearrgb_to_srgb_v3_v3(), max, min, N_, NULL, NUMSLI, picker_new_hide_reveal(), PICKER_TOTAL_W, rgb_to_hsv(), RNA_property_float_get_array(), RNA_property_float_ui_range(), ROW, square_picker(), step(), TEX, TIP_, ui_block_hsv_get(), UI_GRAD_HS, UI_GRAD_HV, UI_GRAD_SV, UI_UNIT_X, UI_UNIT_Y, uiBlockBeginAlign(), uiBlockEndAlign(), uiButSetFunc(), uiDefBut(), uiDefButF(), uiDefButR_prop(), uiDefButS(), uiDefIconButO(), USER_CP_CIRCLE, USER_CP_SQUARE_HS, USER_CP_SQUARE_HV, USER_CP_SQUARE_SV, and WM_OP_INVOKE_DEFAULT.
Referenced by ui_block_func_COL().
void uiPupBlock (bContext * C, uiBlockCreateFunc func, void * arg)
Definition at line 2683 of file interface_regions.c.
References NULL, and uiPupBlockO().
Referenced by popup_add_shortcut_func(), popup_change_shortcut_func(), wm_block_splash_refreshmenu(), WM_enum_search_invoke(), WM_operator_props_popup(), WM_operator_redo_popup(), wm_search_menu_invoke(), and wm_splash_invoke().
void uiPupBlockClose (bContext * C, uiBlock * block)
Definition at line 2726 of file interface_regions.c.
References CTX_wm_window(), uiBlock::handle, wmWindow::modalhandlers, ui_popup_block_free(), and UI_remove_popup_handlers().
Referenced by dialog_exec_cb(), wm_block_splash_close(), and wm_block_splash_refreshmenu().
void uiPupBlockEx (bContext * C, uiBlockCreateFunc func, uiBlockHandleFunc popup_func, uiBlockCancelFunc cancel_func, void * arg)
Definition at line 2688 of file interface_regions.c.
References uiPopupBlockHandle::cancel_func, CTX_wm_window(), wmWindow::modalhandlers, NULL, uiPopupBlockHandle::popup, uiPopupBlockHandle::popup_arg, uiPopupBlockHandle::popup_func, uiPopupBlockHandle::retvalue, UI_add_popup_handlers(), ui_popup_block_create(), and WM_event_add_mousemove().
Referenced by WM_operator_props_dialog_popup(), and WM_operator_ui_popup().
void uiPupBlockO (bContext * C, uiBlockCreateFunc func, void * arg, const char * opname, int opcontext)
Definition at line 2669 of file interface_regions.c.
References CTX_wm_window(), wmWindow::modalhandlers, NULL, uiPopupBlockHandle::opcontext, uiPopupBlockHandle::optype, uiPopupBlockHandle::popup, UI_add_popup_handlers(), ui_popup_block_create(), WM_event_add_mousemove(), and WM_operatortype_find().
Referenced by uiPupBlock().
uiPopupMenu* uiPupMenuBegin (bContext * C, const char * title, int icon)
Definition at line 2449 of file interface_regions.c.
References BLI_snprintf(), uiPopupMenu::block, uiBut::flag, uiBlock::flag, uiBlock::handle, LABEL, uiPopupMenu::layout, MEM_callocN(), NULL, uiBlock::puphash, UI_BLOCK_POPUP_MEMORY, UI_EMBOSSP, UI_GetStyle(), UI_LAYOUT_MENU, UI_LAYOUT_VERTICAL, ui_popup_menu_hash(), UI_TEXT_LEFT, UI_UNIT_Y, uiBeginBlock(), uiBlockLayout(), uiDefBut(), uiDefIconTextBut(), uiLayoutSetOperatorContext(), and WM_OP_EXEC_REGION_WIN.
Referenced by armature_parent_set_invoke(), delete_invoke(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), image_pack_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), make_proxy_invoke(), nla_fmodifier_add_invoke(), object_metaball_add_invoke(), parent_drop_invoke(), parent_set_invoke(), pose_groups_menu_invoke(), pose_ik_add_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), screen_area_options_invoke(), select_grouped_group(), select_orientation_invoke(), text_resolve_conflict_invoke(), toggle_cyclic_invoke(), toolbox_invoke(), ui_but_menu(), uiPupMenuInvoke(), undo_history_invoke(), unpack_all_invoke(), unpack_menu(), WM_menu_invoke(), and WM_operator_confirm_message().
void uiPupMenuEnd (bContext * C, uiPopupMenu * pup)
Definition at line 2482 of file interface_regions.c.
References CTX_wm_window(), wmWindow::eventstate, MEM_freeN(), wmWindow::modalhandlers, uiPopupMenu::mx, uiPopupMenu::my, NULL, uiPopupBlockHandle::popup, uiPopupMenu::popup, UI_add_popup_handlers(), ui_block_func_POPUP(), ui_popup_block_create(), WM_event_add_mousemove(), wmEvent::x, and wmEvent::y.
Referenced by armature_parent_set_invoke(), delete_invoke(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), image_pack_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), make_proxy_invoke(), nla_fmodifier_add_invoke(), object_metaball_add_invoke(), parent_drop_invoke(), parent_set_invoke(), pose_groups_menu_invoke(), pose_ik_add_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), screen_area_options_invoke(), select_grouped_group(), select_orientation_invoke(), text_resolve_conflict_invoke(), toggle_cyclic_invoke(), toolbox_invoke(), ui_but_menu(), uiPupMenuInvoke(), undo_history_invoke(), unpack_all_invoke(), unpack_menu(), WM_menu_invoke(), and WM_operator_confirm_message().
void uiPupMenuError (bContext * C, const char * str, ...)
Definition at line 2593 of file interface_regions.c.
References BLI_snprintf(), BLI_strncpy(), NULL, and vconfirm_opname().
void uiPupMenuInvoke (bContext * C, const char * idname)
Definition at line 2640 of file interface_regions.c.
References MenuType::draw, IFACE_, MenuType::label, Menu::layout, mt, NULL, MenuType::poll, TRUE, Menu::type, uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_menutype_find().
Referenced by wm_call_menu_exec().
uiLayout* uiPupMenuLayout (uiPopupMenu * pup) [read]
Definition at line 2500 of file interface_regions.c.
References uiPopupMenu::layout.
Referenced by armature_parent_set_invoke(), delete_invoke(), graph_fmodifier_add_invoke(), header_toolbox_invoke(), image_pack_invoke(), insert_key_menu_invoke(), keyingset_active_menu_invoke(), make_proxy_invoke(), nla_fmodifier_add_invoke(), object_metaball_add_invoke(), parent_drop_invoke(), parent_set_invoke(), pose_groups_menu_invoke(), pose_ik_add_invoke(), poselib_add_menu_invoke(), repeat_history_invoke(), screen_area_options_invoke(), select_grouped_group(), select_orientation_invoke(), text_resolve_conflict_invoke(), toggle_cyclic_invoke(), toolbox_invoke(), ui_but_menu(), uiPupMenuInvoke(), undo_history_invoke(), unpack_all_invoke(), unpack_menu(), WM_menu_invoke(), and WM_operator_confirm_message().
void uiPupMenuNotice (bContext * C, const char * str, ...)
Definition at line 2584 of file interface_regions.c.
References NULL, and vconfirm_opname().
void uiPupMenuOkee (bContext * C, const char * opname, const char * str, ...)
Definition at line 2562 of file interface_regions.c.
References BLI_snprintf(), and vconfirm_opname().
Referenced by node_group_edit_invoke(), and pack_all_invoke().
void uiPupMenuReports (bContext * C, ReportList * reports)
Definition at line 2608 of file interface_regions.c.
References BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), CTX_wm_window(), ListBase::first, ReportList::list, MEM_freeN(), Report::message, Report::next, NULL, ReportList::printlevel, RPT_ERROR, RPT_INFO, RPT_WARNING, str, Report::type, and ui_popup_menu_create().
Referenced by wm_handler_fileselect_call(), and wm_operator_reports().
void uiPupMenuSaveOver (bContext * C, wmOperator * op, const char * filename)
Definition at line 2579 of file interface_regions.c.
References confirm_operator().
Referenced by wm_handler_fileselect_call(), and wm_save_mainfile_invoke().
int uiSearchBoxhHeight (void)
Definition at line 759 of file interface_regions.c.
References MENU_TOP, SEARCH_ITEMS, and UI_UNIT_Y.
Referenced by id_search_menu(), operator_search_menu(), tool_search_menu(), ui_searchbox_create(), wm_block_search_menu(), and wm_enum_search_menu().
int uiSearchItemAdd (uiSearchItems * items, const char * name, void * poin, int iconid)
Definition at line 720 of file interface_regions.c.
References uiSearchItems::active, autocomplete_do_name(), uiSearchItems::autocpl, BLI_strncpy(), uiSearchItems::icons, uiSearchItems::maxitem, uiSearchItems::maxstrlen, uiSearchItems::more, uiSearchItems::names, uiSearchItems::offset_i, uiSearchItems::pointers, and uiSearchItems::totitem.
Referenced by id_search_cb(), operator_enum_search_cb(), operator_search_cb(), and rna_search_cb().
static void vconfirm_opname (bContext * C, const char * opname, const char * title, const char * itemfmt, va_list ap) [static]
Definition at line 2530 of file interface_regions.c.
References NULL, operator_name_cb(), and ui_popup_menu_create().
Referenced by uiPupMenuError(), uiPupMenuNotice(), and uiPupMenuOkee().