Blender: bmo_mesh_conv.c File Reference
bmo_mesh_conv.c File Reference
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_key_types.h"
#include "DNA_modifier_types.h"
#include "BKE_mesh.h"
#include "BLI_listbase.h"
#include "BKE_global.h"
#include "BKE_key.h"
#include "BKE_main.h"
#include "BKE_customdata.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
#include "intern/bmesh_operators_private.h"
Functions
void bmo_mesh_to_bmesh_exec (BMesh *bm, BMOperator *op)
void bmo_object_load_bmesh_exec (BMesh *bm, BMOperator *op)
void bmo_bmesh_to_mesh_exec (BMesh *bm, BMOperator *op)
Function Documentation
void bmo_bmesh_to_mesh_exec (BMesh * bm, BMOperator * op)
Definition at line 76 of file bmo_mesh_conv.c.
References BM_mesh_bm_to_me(), BMO_slot_bool_get(), and BMO_slot_ptr_get().
void bmo_mesh_to_bmesh_exec (BMesh * bm, BMOperator * op)
Definition at line 54 of file bmo_mesh_conv.c.
References BM_mesh_bm_from_me(), BMO_slot_bool_get(), BMO_slot_ptr_get(), Mesh::key, Object::shapenr, and Key::totkey.
void bmo_object_load_bmesh_exec (BMesh * bm, BMOperator * op)
Definition at line 67 of file bmo_mesh_conv.c.
References BMO_op_callf(), BMO_slot_ptr_get(), Object::data, and TRUE.