Blender: RAS_Deformer Class Reference
RAS_Deformer Class Reference
#include <RAS_Deformer.h>
Public Member Functions
RAS_Deformer ()
virtual ~RAS_Deformer ()
virtual void Relink (CTR_Map< class CTR_HashedPtr, void * > *map)=0
virtual bool Apply (class RAS_IPolyMaterial *polymat)=0
virtual bool Update (void)=0
virtual bool UpdateBuckets (void)=0
virtual RAS_Deformer * GetReplica ()=0
virtual void ProcessReplica ()=0
virtual bool SkipVertexTransform ()
virtual bool ShareVertexArray ()
virtual bool UseVertexArray ()
bool IsDynamic ()
virtual struct DerivedMesh * GetFinalMesh ()
virtual struct DerivedMesh * GetPhysicsMesh ()
virtual class RAS_MeshObject * GetRasMesh ()
virtual float(* GetTransVerts (int *tot))[3]
Protected Attributes
class RAS_MeshObject * m_pMesh
bool m_bDynamic
Detailed Description
Definition at line 49 of file RAS_Deformer.h.
Constructor & Destructor Documentation
RAS_Deformer::RAS_Deformer () [inline]
Definition at line 52 of file RAS_Deformer.h.
virtual RAS_Deformer::~RAS_Deformer () [inline, virtual]
Definition at line 53 of file RAS_Deformer.h.
Member Function Documentation
virtual bool RAS_Deformer::Apply (class RAS_IPolyMaterial * polymat) [pure virtual]
Implemented in BL_MeshDeformer, BL_ModifierDeformer, BL_SkinDeformer, and KX_SoftBodyDeformer.
Referenced by RAS_MaterialBucket::RenderMeshSlot().
virtual struct DerivedMesh* RAS_Deformer::GetFinalMesh () [inline, read, virtual]
Reimplemented in BL_ModifierDeformer.
Definition at line 77 of file RAS_Deformer.h.
References NULL.
virtual struct DerivedMesh* RAS_Deformer::GetPhysicsMesh () [inline, read, virtual]
Reimplemented in BL_ModifierDeformer.
Definition at line 81 of file RAS_Deformer.h.
References NULL.
Referenced by BL_CreatePhysicsObjectNew(), and CcdShapeConstructionInfo::UpdateMesh().
virtual class RAS_MeshObject* RAS_Deformer::GetRasMesh () [inline, virtual]
Reimplemented in BL_MeshDeformer.
Definition at line 85 of file RAS_Deformer.h.
References NULL.
Referenced by CcdShapeConstructionInfo::UpdateMesh().
virtual RAS_Deformer* RAS_Deformer::GetReplica () [pure virtual]
Implemented in BL_MeshDeformer, BL_ModifierDeformer, BL_ShapeDeformer, BL_SkinDeformer, and KX_SoftBodyDeformer.
Referenced by BL_DeformableGameObject::ProcessReplica().
virtual float(* RAS_Deformer::GetTransVerts (int * tot))[3] [inline, virtual]
Reimplemented in BL_MeshDeformer.
Definition at line 90 of file RAS_Deformer.h.
References NULL.
Referenced by CcdShapeConstructionInfo::UpdateMesh().
bool RAS_Deformer::IsDynamic () [inline]
Definition at line 73 of file RAS_Deformer.h.
References m_bDynamic.
Referenced by RAS_MaterialBucket::RenderMeshSlot().
virtual void RAS_Deformer::ProcessReplica () [pure virtual]
Implemented in BL_MeshDeformer, BL_ModifierDeformer, BL_ShapeDeformer, BL_SkinDeformer, and KX_SoftBodyDeformer.
virtual void RAS_Deformer::Relink (CTR_Map< class CTR_HashedPtr, void * > * map) [pure virtual]
Implemented in BL_MeshDeformer, BL_SkinDeformer, and KX_SoftBodyDeformer.
Referenced by BL_DeformableGameObject::Relink().
virtual bool RAS_Deformer::ShareVertexArray () [inline, virtual]
Reimplemented in BL_SkinDeformer.
Definition at line 64 of file RAS_Deformer.h.
Referenced by RAS_MeshSlot::SetDeformer().
virtual bool RAS_Deformer::SkipVertexTransform () [inline, virtual]
Reimplemented in KX_SoftBodyDeformer.
Definition at line 60 of file RAS_Deformer.h.
Referenced by RAS_MaterialBucket::RenderMeshSlot().
virtual bool RAS_Deformer::Update (void) [pure virtual]
Implemented in BL_MeshDeformer, BL_ModifierDeformer, BL_ShapeDeformer, BL_SkinDeformer, and KX_SoftBodyDeformer.
virtual bool RAS_Deformer::UpdateBuckets (void) [pure virtual]
Implemented in BL_MeshDeformer, BL_SkinDeformer, and KX_SoftBodyDeformer.
Referenced by BL_ConvertBlenderObjects(), and BL_CreateGraphicObjectNew().
virtual bool RAS_Deformer::UseVertexArray () [inline, virtual]
Reimplemented in BL_ModifierDeformer.
Definition at line 68 of file RAS_Deformer.h.
Referenced by RAS_MeshObject::AddMeshUser(), and RAS_MeshSlot::SetDeformer().
Member Data Documentation
bool RAS_Deformer::m_bDynamic [protected]
Definition at line 94 of file RAS_Deformer.h.
Referenced by BL_ShapeDeformer::ExecuteShapeDrivers(), IsDynamic(), BL_MeshDeformer::ProcessReplica(), KX_SoftBodyDeformer::ProcessReplica(), BL_ModifierDeformer::Update(), BL_ShapeDeformer::Update(), KX_SoftBodyDeformer::Update(), and BL_SkinDeformer::UpdateInternal().
class RAS_MeshObject* RAS_Deformer::m_pMesh [protected]
Definition at line 93 of file RAS_Deformer.h.
The documentation for this class was generated from the following file:
RAS_Deformer.h