Blender: logImageLib.c File Reference
logImageLib.c File Reference
Cineon
#include "cineonlib.h"
#include "dpxlib.h"
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <string.h>
#include "BLI_fileops.h"
Defines
#define MIN_GAMMA 0.01
#define MAX_GAMMA 99.9
#define DEFAULT_GAMMA 1.0
#define DEFAULT_BLACK_POINT 95
#define DEFAULT_WHITE_POINT 685
Functions
void logImageSetVerbose (int verbosity)
LogImageFile * logImageOpen (const char *filename, int cineon)
LogImageFile * logImageOpenFromMem (unsigned char *buffer, unsigned int size, int cineon)
LogImageFile * logImageCreate (const char *filename, int cineon, int width, int height, int depth)
int logImageGetSize (const LogImageFile *logImage, int *width, int *height, int *depth)
int logImageGetByteConversionDefaults (LogImageByteConversionParameters *params)
int logImageGetByteConversion (const LogImageFile *logImage, LogImageByteConversionParameters *params)
int logImageSetByteConversion (LogImageFile *logImage, const LogImageByteConversionParameters *params)
int logImageGetRowBytes (LogImageFile *logImage, unsigned short *row, int y)
int logImageSetRowBytes (LogImageFile *logImage, const unsigned short *row, int y)
void logImageClose (LogImageFile *logImage)
void logImageDump (const char *filename)
Detailed Description
Definition in file logImageLib.c.
Define Documentation
#define DEFAULT_BLACK_POINT 95
Definition at line 44 of file logImageLib.c.
Referenced by logImageGetByteConversionDefaults().
#define DEFAULT_GAMMA 1.0
Definition at line 43 of file logImageLib.c.
Referenced by logImageGetByteConversionDefaults().
#define DEFAULT_WHITE_POINT 685
Definition at line 45 of file logImageLib.c.
Referenced by logImageGetByteConversionDefaults().
#define MAX_GAMMA 99.9
Definition at line 42 of file logImageLib.c.
Referenced by logImageSetByteConversion().
#define MIN_GAMMA 0.01
Definition at line 41 of file logImageLib.c.
Referenced by logImageSetByteConversion().
Function Documentation
void logImageClose (LogImageFile * logImage)
Definition at line 150 of file logImageLib.c.
References _Log_Image_File_t_::close.
Referenced by imb_load_dpx_cineon(), and imb_save_dpx_cineon().
LogImageFile* logImageCreate (const char * filename, int cineon, int width, int height, int depth)
Definition at line 79 of file logImageLib.c.
References cineonCreate(), and dpxCreate().
Referenced by imb_save_dpx_cineon().
void logImageDump (const char * filename)
Definition at line 156 of file logImageLib.c.
References BLI_fopen(), CINEON_FILE_MAGIC, DPX_FILE_MAGIC, dpxDump(), and magic.
int logImageGetByteConversion (const LogImageFile * logImage, LogImageByteConversionParameters * params)
Definition at line 110 of file logImageLib.c.
References LogImageByteConversionParameters::blackPoint, LogImageByteConversionParameters::doLogarithm, LogImageByteConversionParameters::gamma, _Log_Image_File_t_::params, and LogImageByteConversionParameters::whitePoint.
int logImageGetByteConversionDefaults (LogImageByteConversionParameters * params)
Definition at line 100 of file logImageLib.c.
References LogImageByteConversionParameters::blackPoint, DEFAULT_BLACK_POINT, DEFAULT_GAMMA, DEFAULT_WHITE_POINT, LogImageByteConversionParameters::doLogarithm, LogImageByteConversionParameters::gamma, and LogImageByteConversionParameters::whitePoint.
Referenced by cineonCreate(), cineonOpen(), cineonOpenFromMem(), dpxCreate(), imb_save_dpx_cineon(), and intern_dpxOpen().
int logImageGetRowBytes (LogImageFile * logImage, unsigned short * row, int y)
Definition at line 138 of file logImageLib.c.
References _Log_Image_File_t_::getRow.
Referenced by imb_load_dpx_cineon().
int logImageGetSize (const LogImageFile * logImage, int * width, int * height, int * depth)
Definition at line 91 of file logImageLib.c.
References _Log_Image_File_t_::depth, _Log_Image_File_t_::height, and _Log_Image_File_t_::width.
Referenced by imb_load_dpx_cineon().
LogImageFile* logImageOpen (const char * filename, int cineon)
Definition at line 55 of file logImageLib.c.
References cineonOpen(), and dpxOpen().
LogImageFile* logImageOpenFromMem (unsigned char * buffer, unsigned int size, int cineon)
Definition at line 67 of file logImageLib.c.
References cineonOpenFromMem(), and dpxOpenFromMem().
Referenced by imb_load_dpx_cineon().
int logImageSetByteConversion (LogImageFile * logImage, const LogImageByteConversionParameters * params)
Definition at line 120 of file logImageLib.c.
References LogImageByteConversionParameters::blackPoint, LogImageByteConversionParameters::doLogarithm, LogImageByteConversionParameters::gamma, MAX_GAMMA, MIN_GAMMA, _Log_Image_File_t_::params, setupLut16(), and LogImageByteConversionParameters::whitePoint.
Referenced by imb_save_dpx_cineon().
int logImageSetRowBytes (LogImageFile * logImage, const unsigned short * row, int y)
Definition at line 144 of file logImageLib.c.
References _Log_Image_File_t_::setRow.
Referenced by imb_save_dpx_cineon().
void logImageSetVerbose (int verbosity)
Definition at line 48 of file logImageLib.c.
References cineonSetVerbose(), and dpxSetVerbose().
Referenced by imb_load_dpx_cineon(), and imb_save_dpx_cineon().