Blender: MOD_cloth.c File Reference
MOD_cloth.c File Reference
modifiers
#include "DNA_cloth_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BKE_cloth.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_global.h"
#include "BKE_modifier.h"
#include "BKE_pointcache.h"
#include "depsgraph_private.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int UNUSED(numVerts), int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static void updateDepgraph (ModifierData *md, DagForest *forest, Scene *scene, Object *ob, DagNode *obNode)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static int dependsOnTime (ModifierData *UNUSED(md))
static void freeData (ModifierData *md)
static void foreachIDLink (ModifierData *md, Object *ob, IDWalkFunc walk, void *userData)
Variables
ModifierTypeInfo modifierType_Cloth
Detailed Description
Definition in file MOD_cloth.c.
Function Documentation
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 137 of file MOD_cloth.c.
References BKE_ptcache_copy_list(), BKE_ptcache_free_list(), ClothModifierData::clothObject, ClothModifierData::coll_parms, ClothSimSettings::effector_weights, MEM_dupallocN(), MEM_freeN(), NULL, ClothModifierData::point_cache, ClothModifierData::ptcaches, and ClothModifierData::sim_parms.
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int UNUSEDnumVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 70 of file MOD_cloth.c.
References CDDM_apply_vert_coords(), CDDM_copy(), clothModifier_do(), ClothModifierData::coll_parms, DM_ensure_tessface(), get_dm(), DerivedMesh::getVertCos, initData(), NULL, DerivedMesh::release, ModifierData::scene, and ClothModifierData::sim_parms.
static int dependsOnTime (ModifierData * UNUSEDmd) [static]
Definition at line 162 of file MOD_cloth.c.
static void foreachIDLink (ModifierData * md, Object * ob, IDWalkFunc walk, void * userData) [static]
Definition at line 190 of file MOD_cloth.c.
References ClothModifierData::coll_parms, ClothSimSettings::effector_weights, ClothCollSettings::group, EffectorWeights::group, and ClothModifierData::sim_parms.
static void freeData (ModifierData * md) [static]
Definition at line 167 of file MOD_cloth.c.
References BKE_ptcache_free_list(), cloth_free_modifier_extern(), ClothModifierData::coll_parms, ClothSimSettings::effector_weights, G, MEM_freeN(), NULL, ClothModifierData::point_cache, ClothModifierData::ptcaches, and ClothModifierData::sim_parms.
static void initData (ModifierData * md) [static]
Definition at line 55 of file MOD_cloth.c.
References BKE_ptcache_add(), cloth_init(), ClothModifierData::coll_parms, MEM_callocN(), ClothModifierData::point_cache, ClothModifierData::ptcaches, and ClothModifierData::sim_parms.
Referenced by deformVerts().
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 123 of file MOD_cloth.c.
References CD_MASK_CLOTH_ORCO, CD_MASK_MDEFORMVERT, cloth_uses_vgroup(), ClothSimSettings::shapekey_rest, and ClothModifierData::sim_parms.
static void updateDepgraph (ModifierData * md, DagForest * forest, Scene * scene, Object * ob, DagNode * obNode) [static]
Definition at line 103 of file MOD_cloth.c.
References Scene::base, dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, eModifierType_Collision, ListBase::first, modifiers_findByType(), Base::next, and Base::object.
Variable Documentation
ModifierTypeInfo modifierType_Cloth
Initial value:
 {
                  "Cloth",
            "ClothModifierData",
            sizeof(ClothModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_UsesPointCache
                            | eModifierTypeFlag_Single,
              copyData,
           deformVerts,
        NULL,
         NULL,
      NULL,
         NULL,
       NULL,
              initData,
      requiredDataMask,
              freeData,
            NULL,
        updateDepgraph,
         dependsOnTime,
        NULL,
     NULL,
         foreachIDLink,
        NULL,
}
Definition at line 204 of file MOD_cloth.c.