Blender: bpy_rna.c File Reference
bpy_rna.c File Reference
Python RNA and Operators
#include <Python.h>
#include <stddef.h>
#include <float.h>
#include "RNA_types.h"
#include "bpy_rna.h"
#include "bpy_rna_anim.h"
#include "bpy_props.h"
#include "bpy_util.h"
#include "bpy_rna_callback.h"
#include "bpy_intern_string.h"
#include "BLI_dynstr.h"
#include "BLI_string.h"
#include "BLI_listbase.h"
#include "BLI_math_rotation.h"
#include "BLI_utildefines.h"
#include "RNA_enum_types.h"
#include "RNA_define.h"
#include "RNA_access.h"
#include "MEM_guardedalloc.h"
#include "BKE_main.h"
#include "BKE_idcode.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_report.h"
#include "BKE_idprop.h"
#include "BKE_animsys.h"
#include "BKE_fcurve.h"
#include "../generic/idprop_py_api.h"
#include "../generic/py_capi_utils.h"
#include "../mathutils/mathutils.h"
Defines
#define USE_PEDANTIC_WRITE
#define USE_MATHUTILS
#define USE_STRING_COERCE
#define BPY_DOC_ID_PROP_TYPE_NOTE
#define MATHUTILS_CB_SUBTYPE_EUL 0
#define MATHUTILS_CB_SUBTYPE_VEC 1
#define MATHUTILS_CB_SUBTYPE_QUAT 2
#define MATHUTILS_CB_SUBTYPE_COLOR 3
#define PROP_ALL_VECTOR_SUBTYPES
#define PYRNA_PROP_COLLECTION_ABS_INDEX(ret_err)
#define BPY_REPLACEMENT_STRING(rna_attr, py_attr)
Functions
static PyObject * pyrna_struct_Subtype (PointerRNA *ptr)
static PyObject * pyrna_prop_collection_values (BPy_PropertyRNA *self)
int pyrna_struct_validity_check (BPy_StructRNA *pysrna)
int pyrna_prop_validity_check (BPy_PropertyRNA *self)
void BPY_id_release (struct ID *id)
static int rna_id_write_error (PointerRNA *ptr, PyObject *key)
int pyrna_write_check (void)
void pyrna_write_set (int val)
static Py_ssize_t pyrna_prop_collection_length (BPy_PropertyRNA *self)
static Py_ssize_t pyrna_prop_array_length (BPy_PropertyArrayRNA *self)
static int pyrna_py_to_prop (PointerRNA *ptr, PropertyRNA *prop, void *data, PyObject *value, const char *error_prefix)
static int deferred_register_prop (StructRNA *srna, PyObject *key, PyObject *item)
static PyObject * pyrna_prop_array_subscript_slice (BPy_PropertyArrayRNA *self, PointerRNA *ptr, PropertyRNA *prop, Py_ssize_t start, Py_ssize_t stop, Py_ssize_t length)
static short pyrna_rotation_euler_order_get (PointerRNA *ptr, PropertyRNA **prop_eul_order, short order_fallback)
static int mathutils_rna_generic_check (BaseMathObject *bmo)
static int mathutils_rna_vector_get (BaseMathObject *bmo, int subtype)
static int mathutils_rna_vector_set (BaseMathObject *bmo, int subtype)
static int mathutils_rna_vector_get_index (BaseMathObject *bmo, int UNUSED(subtype), int index)
static int mathutils_rna_vector_set_index (BaseMathObject *bmo, int UNUSED(subtype), int index)
static int mathutils_rna_matrix_get (BaseMathObject *bmo, int UNUSED(subtype))
static int mathutils_rna_matrix_set (BaseMathObject *bmo, int UNUSED(subtype))
PyObject * pyrna_math_object_from_array (PointerRNA *ptr, PropertyRNA *prop)
int pyrna_enum_value_from_id (EnumPropertyItem *item, const char *identifier, int *value, const char *error_prefix)
static int pyrna_struct_compare (BPy_StructRNA *a, BPy_StructRNA *b)
static int pyrna_prop_compare (BPy_PropertyRNA *a, BPy_PropertyRNA *b)
static PyObject * pyrna_struct_richcmp (PyObject *a, PyObject *b, int op)
static PyObject * pyrna_prop_richcmp (PyObject *a, PyObject *b, int op)
static PyObject * pyrna_struct_str (BPy_StructRNA *self)
static PyObject * pyrna_struct_repr (BPy_StructRNA *self)
static PyObject * pyrna_prop_str (BPy_PropertyRNA *self)
static PyObject * pyrna_prop_repr (BPy_PropertyRNA *self)
static PyObject * pyrna_func_repr (BPy_FunctionRNA *self)
static Py_hash_t pyrna_struct_hash (BPy_StructRNA *self)
static long pyrna_prop_hash (BPy_PropertyRNA *self)
static void pyrna_struct_dealloc (BPy_StructRNA *self)
static void pyrna_prop_dealloc (BPy_PropertyRNA *self)
static void pyrna_prop_array_dealloc (BPy_PropertyRNA *self)
static const char * pyrna_enum_as_string (PointerRNA *ptr, PropertyRNA *prop)
static int pyrna_string_to_enum (PyObject *item, PointerRNA *ptr, PropertyRNA *prop, int *val, const char *error_prefix)
int pyrna_set_to_enum_bitfield (EnumPropertyItem *items, PyObject *value, int *r_value, const char *error_prefix)
static int pyrna_prop_to_enum_bitfield (PointerRNA *ptr, PropertyRNA *prop, PyObject *value, int *r_value, const char *error_prefix)
PyObject * pyrna_enum_bitfield_to_py (EnumPropertyItem *items, int value)
static PyObject * pyrna_enum_to_py (PointerRNA *ptr, PropertyRNA *prop, int val)
PyObject * pyrna_prop_to_py (PointerRNA *ptr, PropertyRNA *prop)
int pyrna_pydict_to_props (PointerRNA *ptr, PyObject *kw, int all_args, const char *error_prefix)
static PyObject * pyrna_func_to_py (PointerRNA *ptr, FunctionRNA *func)
static PyObject * pyrna_prop_array_to_py_index (BPy_PropertyArrayRNA *self, int index)
static int pyrna_py_to_prop_array_index (BPy_PropertyArrayRNA *self, int index, PyObject *value)
static int pyrna_prop_array_bool (BPy_PropertyRNA *self)
static int pyrna_prop_collection_bool (BPy_PropertyRNA *self)
static PyObject * pyrna_prop_collection_subscript_int (BPy_PropertyRNA *self, Py_ssize_t keynum)
static int pyrna_prop_collection_ass_subscript_int (BPy_PropertyRNA *self, Py_ssize_t keynum, PyObject *value)
static PyObject * pyrna_prop_array_subscript_int (BPy_PropertyArrayRNA *self, int keynum)
static PyObject * pyrna_prop_collection_subscript_str (BPy_PropertyRNA *self, const char *keyname)
int pyrna_prop_collection_subscript_str_lib_pair_ptr (BPy_PropertyRNA *self, PyObject *key, const char *err_prefix, const short err_not_found, PointerRNA *r_ptr)
static PyObject * pyrna_prop_collection_subscript_str_lib_pair (BPy_PropertyRNA *self, PyObject *key, const char *err_prefix, const short err_not_found)
static PyObject * pyrna_prop_collection_subscript_slice (BPy_PropertyRNA *self, Py_ssize_t start, Py_ssize_t stop)
static PyObject * pyrna_prop_collection_subscript (BPy_PropertyRNA *self, PyObject *key)
static int pyrna_prop_collection_type_check (BPy_PropertyRNA *self, PyObject *value)
static int pyrna_prop_collection_ass_subscript (BPy_PropertyRNA *self, PyObject *key, PyObject *value)
static PyObject * pyrna_prop_array_subscript (BPy_PropertyArrayRNA *self, PyObject *key)
static int prop_subscript_ass_array_slice (PointerRNA *ptr, PropertyRNA *prop, int start, int stop, int length, PyObject *value_orig)
static int prop_subscript_ass_array_int (BPy_PropertyArrayRNA *self, Py_ssize_t keynum, PyObject *value)
static int pyrna_prop_array_ass_subscript (BPy_PropertyArrayRNA *self, PyObject *key, PyObject *value)
static int pyrna_prop_array_contains (BPy_PropertyRNA *self, PyObject *value)
static int pyrna_prop_collection_contains (BPy_PropertyRNA *self, PyObject *key)
static int pyrna_struct_contains (BPy_StructRNA *self, PyObject *value)
static PyObject * pyrna_struct_subscript (BPy_StructRNA *self, PyObject *key)
static int pyrna_struct_ass_subscript (BPy_StructRNA *self, PyObject *key, PyObject *value)
PyDoc_STRVAR (pyrna_struct_keys_doc,".. method:: keys()\n""\n"" Returns the keys of this objects custom properties (matches pythons\n"" dictionary function of the same name).\n""\n"" :return: custom property keys.\n"" :rtype: list of strings\n""\n"BPY_DOC_ID_PROP_TYPE_NOTE)
static PyObject * pyrna_struct_keys (BPy_PropertyRNA *self)
PyDoc_STRVAR (pyrna_struct_items_doc,".. method:: items()\n""\n"" Returns the items of this objects custom properties (matches pythons\n"" dictionary function of the same name).\n""\n"" :return: custom property key, value pairs.\n"" :rtype: list of key, value tuples\n""\n"BPY_DOC_ID_PROP_TYPE_NOTE)
static PyObject * pyrna_struct_items (BPy_PropertyRNA *self)
PyDoc_STRVAR (pyrna_struct_values_doc,".. method:: values()\n""\n"" Returns the values of this objects custom properties (matches pythons\n"" dictionary function of the same name).\n""\n"" :return: custom property values.\n"" :rtype: list\n""\n"BPY_DOC_ID_PROP_TYPE_NOTE)
static PyObject * pyrna_struct_values (BPy_PropertyRNA *self)
PyDoc_STRVAR (pyrna_struct_is_property_set_doc,".. method:: is_property_set(property)\n""\n"" Check if a property is set, use for testing operator properties.\n""\n"" :return: True when the property has been set.\n"" :rtype: boolean\n")
static PyObject * pyrna_struct_is_property_set (BPy_StructRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_struct_is_property_hidden_doc,".. method:: is_property_hidden(property)\n""\n"" Check if a property is hidden.\n""\n"" :return: True when the property is hidden.\n"" :rtype: boolean\n")
static PyObject * pyrna_struct_is_property_hidden (BPy_StructRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_struct_path_resolve_doc,".. method:: path_resolve(path, coerce=True)\n""\n"" Returns the property from the path, raise an exception when not found.\n""\n"" :arg path: path which this property resolves.\n"" :type path: string\n"" :arg coerce: optional argument, when True, the property will be converted\n"" into its python representation.\n"" :type coerce: boolean\n")
static PyObject * pyrna_struct_path_resolve (BPy_StructRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_struct_path_from_id_doc,".. method:: path_from_id(property=\"\")\n""\n"" Returns the data path from the ID to this object (string).\n""\n"" :arg property: Optional property name which can be used if the path is\n"" to a property of this object.\n"" :type property: string\n"" :return: The path from :class:`bpy.types.bpy_struct.id_data`\n"" to this struct and property (when given).\n"" :rtype: str\n")
static PyObject * pyrna_struct_path_from_id (BPy_StructRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_prop_path_from_id_doc,".. method:: path_from_id()\n""\n"" Returns the data path from the ID to this property (string).\n""\n"" :return: The path from :class:`bpy.types.bpy_struct.id_data` to this property.\n"" :rtype: str\n")
static PyObject * pyrna_prop_path_from_id (BPy_PropertyRNA *self)
PyDoc_STRVAR (pyrna_struct_type_recast_doc,".. method:: type_recast()\n""\n"" Return a new instance, this is needed because types\n"" such as textures can be changed at runtime.\n""\n"" :return: a new instance of this object with the type initialized again.\n"" :rtype: subclass of :class:`bpy.types.bpy_struct`\n")
static PyObject * pyrna_struct_type_recast (BPy_StructRNA *self)
static void pyrna_dir_members_py__add_keys (PyObject *list, PyObject *dict)
static void pyrna_dir_members_py (PyObject *list, PyObject *self)
static void pyrna_dir_members_rna (PyObject *list, PointerRNA *ptr)
static PyObject * pyrna_struct_dir (BPy_StructRNA *self)
static PyObject * pyrna_struct_getattro (BPy_StructRNA *self, PyObject *pyname)
static int pyrna_is_deferred_prop (const PyObject *value)
static int pyrna_struct_meta_idprop_setattro (PyObject *cls, PyObject *attr, PyObject *value)
static int pyrna_struct_setattro (BPy_StructRNA *self, PyObject *pyname, PyObject *value)
static PyObject * pyrna_prop_dir (BPy_PropertyRNA *self)
static PyObject * pyrna_prop_array_getattro (BPy_PropertyRNA *self, PyObject *pyname)
static PyObject * pyrna_prop_collection_getattro (BPy_PropertyRNA *self, PyObject *pyname)
static int pyrna_prop_collection_setattro (BPy_PropertyRNA *self, PyObject *pyname, PyObject *value)
static PyObject * pyrna_prop_collection_idprop_add (BPy_PropertyRNA *self)
static PyObject * pyrna_prop_collection_idprop_remove (BPy_PropertyRNA *self, PyObject *value)
static PyObject * pyrna_prop_collection_idprop_clear (BPy_PropertyRNA *self)
static PyObject * pyrna_prop_collection_idprop_move (BPy_PropertyRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_struct_get_id_data_doc,"The :class:`bpy.types.ID` object this datablock is from or None, (not available for all data types)")
static PyObject * pyrna_struct_get_id_data (BPy_DummyPointerRNA *self)
PyDoc_STRVAR (pyrna_struct_get_data_doc,"The data this property is using, *type* :class:`bpy.types.bpy_struct`")
static PyObject * pyrna_struct_get_data (BPy_DummyPointerRNA *self)
PyDoc_STRVAR (pyrna_struct_get_rna_type_doc,"The property type for introspection")
static PyObject * pyrna_struct_get_rna_type (BPy_PropertyRNA *self)
static PyObject * pyrna_func_doc_get (BPy_FunctionRNA *self, void *closure)
PyDoc_STRVAR (pyrna_prop_collection_keys_doc,".. method:: keys()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.keys() functionality).\n""\n"" :return: the identifiers for each member of this collection.\n"" :rtype: list of strings\n")
static PyObject * pyrna_prop_collection_keys (BPy_PropertyRNA *self)
PyDoc_STRVAR (pyrna_prop_collection_items_doc,".. method:: items()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.items() functionality).\n""\n"" :return: (key, value) pairs for each member of this collection.\n"" :rtype: list of tuples\n")
static PyObject * pyrna_prop_collection_items (BPy_PropertyRNA *self)
PyDoc_STRVAR (pyrna_prop_collection_values_doc,".. method:: values()\n""\n"" Return the values of collection\n"" (matching pythons dict.values() functionality).\n""\n"" :return: the members of this collection.\n"" :rtype: list\n")
PyDoc_STRVAR (pyrna_struct_get_doc,".. method:: get(key, default=None)\n""\n"" Returns the value of the custom property assigned to key or default\n"" when not found (matches pythons dictionary function of the same name).\n""\n"" :arg key: The key associated with the custom property.\n"" :type key: string\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n""\n"BPY_DOC_ID_PROP_TYPE_NOTE)
static PyObject * pyrna_struct_get (BPy_StructRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_struct_as_pointer_doc,".. method:: as_pointer()\n""\n"" Returns the memory address which holds a pointer to blenders internal data\n""\n"" :return: int (memory address).\n"" :rtype: int\n""\n"" .. note:: This is intended only for advanced script writers who need to\n"" pass blender data to their own C/Python modules.\n")
static PyObject * pyrna_struct_as_pointer (BPy_StructRNA *self)
PyDoc_STRVAR (pyrna_prop_collection_get_doc,".. method:: get(key, default=None)\n""\n"" Returns the value of the item assigned to key or default when not found\n"" (matches pythons dictionary function of the same name).\n""\n"" :arg key: The identifier for the collection member.\n"" :type key: string\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n")
static PyObject * pyrna_prop_collection_get (BPy_PropertyRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_prop_collection_find_doc,".. method:: find(key)\n""\n"" Returns the index of a key in a collection or -1 when not found\n"" (matches pythons string find function of the same name).\n""\n"" :arg key: The identifier for the collection member.\n"" :type key: string\n"" :return: index of the key.\n"" :rtype: int\n")
static PyObject * pyrna_prop_collection_find (BPy_PropertyRNA *self, PyObject *key_ob)
static void foreach_attr_type (BPy_PropertyRNA *self, const char *attr, RawPropertyType *raw_type, int *attr_tot, int *attr_signed)
static int foreach_parse_args (BPy_PropertyRNA *self, PyObject *args, const char **attr, PyObject **seq, int *tot, int *size, RawPropertyType *raw_type, int *attr_tot, int *attr_signed)
static int foreach_compat_buffer (RawPropertyType raw_type, int attr_signed, const char *format)
static PyObject * foreach_getset (BPy_PropertyRNA *self, PyObject *args, int set)
PyDoc_STRVAR (pyrna_prop_collection_foreach_get_doc,".. method:: foreach_get(attr, seq)\n""\n"" This is a function to give fast access to attributes within a collection.\n""\n"" .. code-block:: python\n""\n"" collection.foreach_get(someseq, attr)\n""\n"" # Python equivalent\n"" for i in range(len(seq)): someseq[i] = getattr(collection, attr)\n""\n")
static PyObject * pyrna_prop_collection_foreach_get (BPy_PropertyRNA *self, PyObject *args)
PyDoc_STRVAR (pyrna_prop_collection_foreach_set_doc,".. method:: foreach_set(attr, seq)\n""\n"" This is a function to give fast access to attributes within a collection.\n""\n"" .. code-block:: python\n""\n"" collection.foreach_set(seq, attr)\n""\n"" # Python equivalent\n"" for i in range(len(seq)): setattr(collection[i], attr, seq[i])\n""\n")
static PyObject * pyrna_prop_collection_foreach_set (BPy_PropertyRNA *self, PyObject *args)
static PyObject * pyrna_prop_array_iter (BPy_PropertyArrayRNA *self)
static PyObject * pyrna_prop_collection_iter (BPy_PropertyRNA *self)
static PyObject * pyrna_struct_new (PyTypeObject *type, PyObject *args, PyObject *UNUSED(kwds))
static PyObject * pyrna_prop_new (PyTypeObject *type, PyObject *args, PyObject *UNUSED(kwds))
static PyObject * pyrna_param_to_py (PointerRNA *ptr, PropertyRNA *prop, void *data)
static PyObject * small_dict_get_item_string (PyObject *dict, const char *key_lookup)
static PyObject * pyrna_func_call (BPy_FunctionRNA *self, PyObject *args, PyObject *kw)
static PyObject * pyrna_func_doc_get (BPy_FunctionRNA *self, void *UNUSED(closure))
static void pyrna_prop_collection_iter_dealloc (BPy_PropertyCollectionIterRNA *self)
static PyObject * pyrna_prop_collection_iter_next (BPy_PropertyCollectionIterRNA *self)
PyObject * pyrna_prop_collection_iter_CreatePyObject (PointerRNA *ptr, PropertyRNA *prop)
static void pyrna_subtype_set_rna (PyObject *newclass, StructRNA *srna)
static PyObject * pyrna_srna_Subtype (StructRNA *srna)
static PyObject * pyrna_srna_PyBase (StructRNA *srna)
static PyObject * pyrna_srna_ExternalType (StructRNA *srna)
static StructRNA * srna_from_ptr (PointerRNA *ptr)
PyObject * pyrna_struct_CreatePyObject (PointerRNA *ptr)
PyObject * pyrna_prop_CreatePyObject (PointerRNA *ptr, PropertyRNA *prop)
void BPY_rna_init (void)
PyObject * BPY_rna_module (void)
void BPY_update_rna_module (void)
static PyObject * pyrna_basetype_getattro (BPy_BaseTypeRNA *self, PyObject *pyname)
static PyObject * pyrna_basetype_dir (BPy_BaseTypeRNA *self)
static PyObject * pyrna_register_class (PyObject *self, PyObject *py_class)
static PyObject * pyrna_unregister_class (PyObject *self, PyObject *py_class)
PyObject * BPY_rna_types (void)
StructRNA * pyrna_struct_as_srna (PyObject *self, int parent, const char *error_prefix)
StructRNA * srna_from_self (PyObject *self, const char *error_prefix)
static int pyrna_deferred_register_props (StructRNA *srna, PyObject *class_dict)
static int pyrna_deferred_register_class_recursive (StructRNA *srna, PyTypeObject *py_class)
int pyrna_deferred_register_class (StructRNA *srna, PyObject *py_class)
static int rna_function_arg_count (FunctionRNA *func)
static int bpy_class_validate (PointerRNA *dummyptr, void *py_data, int *have_function)
static int bpy_class_call (bContext *C, PointerRNA *ptr, FunctionRNA *func, ParameterList *parms)
static void bpy_class_free (void *pyob_ptr)
void pyrna_alloc_types (void)
void pyrna_free_types (void)
PyDoc_STRVAR (pyrna_register_class_doc,".. method:: register_class(cls)\n""\n"" Register a subclass of a blender type in (:class:`bpy.types.Panel`,\n"" :class:`bpy.types.Menu`, :class:`bpy.types.Header`, :class:`bpy.types.Operator`,\n"" :class:`bpy.types.KeyingSetInfo`, :class:`bpy.types.RenderEngine`).\n""\n"" If the class has a *register* class method it will be called\n"" before registration.\n""\n"" .. note::\n""\n"" :exc:`ValueError` exception is raised if the class is not a\n"" subclass of a registerable blender class.\n""\n")
static PyObject * pyrna_register_class (PyObject *UNUSED(self), PyObject *py_class)
static int pyrna_srna_contains_pointer_prop_srna (StructRNA *srna_props, StructRNA *srna, const char **prop_identifier)
PyDoc_STRVAR (pyrna_unregister_class_doc,".. method:: unregister_class(cls)\n""\n"" Unload the python class from blender.\n""\n"" If the class has an *unregister* class method it will be called\n"" before unregistering.\n")
static PyObject * pyrna_unregister_class (PyObject *UNUSED(self), PyObject *py_class)
Variables
static short rna_disallow_writes = FALSE
static unsigned char mathutils_rna_array_cb_index = -1
static Mathutils_Callback mathutils_rna_array_cb
static unsigned char mathutils_rna_matrix_cb_index = -1
static Mathutils_Callback mathutils_rna_matrix_cb
static PyMappingMethods pyrna_prop_array_as_mapping
static PyMappingMethods pyrna_prop_collection_as_mapping
static PyNumberMethods pyrna_prop_array_as_number
static PyNumberMethods pyrna_prop_collection_as_number
static PySequenceMethods pyrna_prop_array_as_sequence
static PySequenceMethods pyrna_prop_collection_as_sequence
static PySequenceMethods pyrna_struct_as_sequence
static PyMappingMethods pyrna_struct_as_mapping
static PyGetSetDef pyrna_prop_getseters []
static PyGetSetDef pyrna_struct_getseters []
static PyGetSetDef pyrna_func_getseters []
static struct PyMethodDef pyrna_struct_methods []
static struct PyMethodDef pyrna_prop_methods []
static struct PyMethodDef pyrna_prop_array_methods []
static struct PyMethodDef pyrna_prop_collection_methods []
static struct PyMethodDef pyrna_prop_collection_idprop_methods []
PyTypeObject pyrna_struct_meta_idprop_Type
PyTypeObject pyrna_struct_Type
PyTypeObject pyrna_prop_Type
PyTypeObject pyrna_prop_array_Type
PyTypeObject pyrna_prop_collection_Type
static PyTypeObject pyrna_prop_collection_idprop_Type
PyTypeObject pyrna_func_Type
PyTypeObject pyrna_prop_collection_iter_Type
static PyObject * bpy_types_dict = NULL
static PointerRNA * rna_module_ptr = NULL
static struct PyMethodDef pyrna_basetype_methods []
static PyTypeObject pyrna_basetype_Type = BLANK_PYTHON_TYPE
PyMethodDef meth_bpy_register_class = {"register_class", pyrna_register_class, METH_O, pyrna_register_class_doc}
PyMethodDef meth_bpy_unregister_class
Detailed Description
This file is the main interface between python and blenders data api (RNA), exposing RNA to python so blender data can be accessed in a python like way.
The two main types are 'BPy_StructRNA' and 'BPy_PropertyRNA' - the base classes for most of the data python accesses in blender.
Definition in file bpy_rna.c.
Define Documentation
#define BPY_DOC_ID_PROP_TYPE_NOTE
Value:
"   .. note::\n"                                                              \
"\n"                                                                          \
"      Only :class:`bpy.types.ID`, :class:`bpy.types.Bone` and \n"            \
"      :class:`bpy.types.PoseBone` classes support custom properties.\n"
Definition at line 91 of file bpy_rna.c.
#define BPY_REPLACEMENT_STRING (rna_attr, py_attr)
Value:
if (strcmp(identifier, rna_attr) == 0) {                                  \
        item = PyObject_GetAttrString(py_class, py_attr);                     \
        if (item && item != Py_None) {                                        \
            if (pyrna_py_to_prop(dummyptr, prop, NULL,                        \
                                 item, "validating class:") != 0)             \
            {                                                                 \
                Py_DECREF(item);                                              \
                return -1;                                                    \
            }                                                                 \
        }                                                                     \
        Py_XDECREF(item);                                                     \
    }                                                                         \
Referenced by bpy_class_validate().
#define MATHUTILS_CB_SUBTYPE_COLOR 3
Definition at line 381 of file bpy_rna.c.
Referenced by pyrna_math_object_from_array().
#define MATHUTILS_CB_SUBTYPE_EUL 0
Definition at line 378 of file bpy_rna.c.
Referenced by mathutils_rna_vector_get(), mathutils_rna_vector_set(), and pyrna_math_object_from_array().
#define MATHUTILS_CB_SUBTYPE_QUAT 2
Definition at line 380 of file bpy_rna.c.
Referenced by pyrna_math_object_from_array().
#define MATHUTILS_CB_SUBTYPE_VEC 1
Definition at line 379 of file bpy_rna.c.
Referenced by pyrna_math_object_from_array().
#define PROP_ALL_VECTOR_SUBTYPES
Value:
PROP_COORDS:                                                         \
    case PROP_TRANSLATION:                                                    \
    case PROP_DIRECTION:                                                      \
    case PROP_VELOCITY:                                                       \
    case PROP_ACCELERATION:                                                   \
    case PROP_XYZ:                                                            \
    case PROP_XYZ_LENGTH                                                      \
Definition at line 593 of file bpy_rna.c.
Referenced by pyrna_math_object_from_array(), and pyrna_param_to_py().
#define PYRNA_PROP_COLLECTION_ABS_INDEX (ret_err)
Value:
if (keynum < 0) {                                                         \
        keynum_abs += RNA_property_collection_length(&self->ptr, self->prop); \
        if (keynum_abs < 0) {                                                 \
            PyErr_Format(PyExc_IndexError,                                    \
                         "bpy_prop_collection[%d]: out of range.", keynum);   \
            return ret_err;                                                   \
        }                                                                     \
    }                                                                         \
Definition at line 2032 of file bpy_rna.c.
Referenced by pyrna_prop_collection_ass_subscript_int(), and pyrna_prop_collection_subscript_int().
#define USE_MATHUTILS
Definition at line 85 of file bpy_rna.c.
#define USE_PEDANTIC_WRITE
Definition at line 84 of file bpy_rna.c.
#define USE_STRING_COERCE
Definition at line 86 of file bpy_rna.c.
Function Documentation
static int bpy_class_call (bContext * C, PointerRNA * ptr, FunctionRNA * func, ParameterList * parms) [static]
Definition at line 6844 of file bpy_rna.c.
References bpy_context_clear(), bpy_context_set(), BPy_errors_to_report(), BPy_GetContext(), CTX_wm_manager(), CTX_wm_reports(), ParameterIterator::data, PointerRNA::data, err, FALSE, FUNC_NO_SELF, i, NULL, ParameterIterator::parm, PROP_OUTPUT, PyC_Err_Format_Prefix(), pyrna_param_to_py(), pyrna_py_to_prop(), pyrna_struct_CreatePyObject(), wmOperator::reports, rna_disallow_writes, RNA_Function, rna_function_arg_count(), RNA_function_flag(), RNA_function_identifier(), RNA_Operator, RNA_parameter_list_begin(), RNA_parameter_list_end(), RNA_parameter_list_next(), RNA_pointer_create(), RNA_property_flag(), RNA_struct_identifier(), RNA_struct_instance(), RNA_struct_is_a(), RNA_struct_py_type_get(), TRUE, PointerRNA::type, and ParameterIterator::valid.
Referenced by pyrna_register_class().
static void bpy_class_free (void * pyob_ptr) [static]
Definition at line 7152 of file bpy_rna.c.
References bpy_intern_str_bl_rna, G, G_DEBUG_PYTHON, and PyC_ObSpit().
Referenced by pyrna_free_types(), and pyrna_register_class().
static int bpy_class_validate (PointerRNA * dummyptr, void * py_data, int * have_function) [static]
Definition at line 6695 of file bpy_rna.c.
References BPY_REPLACEMENT_STRING, ListBase::first, FUNC_NO_SELF, FUNC_REGISTER, FUNC_REGISTER_OPTIONAL, i, link(), Link::next, NULL, PROP_REGISTER, PROP_REGISTER_OPTIONAL, pyrna_py_to_prop(), rna_function_arg_count(), RNA_function_flag(), RNA_function_identifier(), RNA_property_flag(), RNA_property_identifier(), RNA_struct_identifier(), RNA_struct_py_type_get(), RNA_struct_type_functions(), RNA_struct_type_properties(), and PointerRNA::type.
Referenced by pyrna_register_class().
void BPY_id_release (struct ID * id)
Definition at line 293 of file bpy_rna.c.
Referenced by free_libblock().
void BPY_rna_init (void)
Definition at line 6249 of file bpy_rna.c.
References Mathutils_RegisterCallback().
Referenced by BPy_init_modules().
PyObject* BPY_rna_module (void)
Definition at line 6294 of file bpy_rna.c.
References G, BPy_StructRNA::ptr, pyrna_struct_CreatePyObject(), and RNA_main_pointer_create().
Referenced by BPy_init_modules(), and BPY_modules_update().
PyObject* BPY_rna_types (void)
Definition at line 6427 of file bpy_rna.c.
References BPy_BaseTypeRNA, NULL, pyrna_basetype_getattro(), pyrna_basetype_methods, RNA_blender_rna_pointer_create(), and RNA_struct_find_property().
Referenced by BPy_init_modules(), and BPY_modules_update().
void BPY_update_rna_module (void)
Definition at line 6307 of file bpy_rna.c.
References PointerRNA::data, G, and RNA_main_pointer_create().
Referenced by BPY_driver_exec(), and BPY_modules_update().
static int deferred_register_prop (StructRNA * srna, PyObject * key, PyObject * item) [static]
Definition at line 6537 of file bpy_rna.c.
References bpy_intern_str_attr, PyC_ObSpit(), pyrna_is_deferred_prop(), and RNA_struct_identifier().
Referenced by pyrna_deferred_register_props(), and pyrna_struct_meta_idprop_setattro().
static void foreach_attr_type (BPy_PropertyRNA * self, const char * attr, RawPropertyType * raw_type, int * attr_tot, int * attr_signed) [static]
Definition at line 4213 of file bpy_rna.c.
References FALSE, PROP_RAW_UNSET, PROP_UNSIGNED, RNA_PROP_BEGIN, RNA_PROP_END, RNA_property_array_length(), RNA_property_raw_type(), RNA_property_subtype(), RNA_struct_find_property(), and TRUE.
Referenced by foreach_parse_args().
static int foreach_compat_buffer (RawPropertyType raw_type, int attr_signed, const char * format) [static]
Definition at line 4291 of file bpy_rna.c.
References PROP_RAW_CHAR, PROP_RAW_DOUBLE, PROP_RAW_FLOAT, PROP_RAW_INT, PROP_RAW_SHORT, and PROP_RAW_UNSET.
Referenced by foreach_getset().
static PyObject* foreach_getset (BPy_PropertyRNA * self, PyObject * args, int set) [static]
Definition at line 4316 of file bpy_rna.c.
References BLI_assert, FALSE, foreach_compat_buffer(), foreach_parse_args(), i, NULL, PROP_RAW_CHAR, PROP_RAW_DOUBLE, PROP_RAW_FLOAT, PROP_RAW_INT, PROP_RAW_SHORT, PROP_RAW_UNSET, RNA_property_collection_raw_get(), RNA_property_collection_raw_set(), and size().
Referenced by pyrna_prop_collection_foreach_get(), and pyrna_prop_collection_foreach_set().
static int foreach_parse_args (BPy_PropertyRNA * self, PyObject * args, const char ** attr, PyObject ** seq, int * tot, int * size, RawPropertyType * raw_type, int * attr_tot, int * attr_signed) [static]
Definition at line 4234 of file bpy_rna.c.
References FALSE, foreach_attr_type(), PROP_COLLECTION, PROP_RAW_UNSET, RNA_property_array_length(), RNA_property_collection_length(), RNA_property_type(), and RNA_raw_type_sizeof().
Referenced by foreach_getset().
static int mathutils_rna_generic_check (BaseMathObject * bmo) [static]
Definition at line 383 of file bpy_rna.c.
References PYRNA_PROP_CHECK_INT.
static int mathutils_rna_matrix_get (BaseMathObject * bmo, int UNUSEDsubtype) [static]
Definition at line 522 of file bpy_rna.c.
References NULL, PYRNA_PROP_CHECK_INT, and RNA_property_float_get_array().
static int mathutils_rna_matrix_set (BaseMathObject * bmo, int UNUSEDsubtype) [static]
Definition at line 535 of file bpy_rna.c.
References BPy_GetContext(), NULL, PYRNA_PROP_CHECK_INT, rna_id_write_error(), RNA_property_editable_flag(), RNA_property_float_set_array(), RNA_property_identifier(), RNA_property_update(), RNA_property_update_check(), and RNA_struct_identifier().
static int mathutils_rna_vector_get (BaseMathObject * bmo, int subtype) [static]
Definition at line 392 of file bpy_rna.c.
References MATHUTILS_CB_SUBTYPE_EUL, NULL, EulerObject::order, PYRNA_PROP_CHECK_INT, pyrna_rotation_euler_order_get(), and RNA_property_float_get_array().
static int mathutils_rna_vector_get_index (BaseMathObject * bmo, int UNUSEDsubtype, int index) [static]
Definition at line 465 of file bpy_rna.c.
References NULL, PYRNA_PROP_CHECK_INT, and RNA_property_float_get_index().
static int mathutils_rna_vector_set (BaseMathObject * bmo, int subtype) [static]
Definition at line 413 of file bpy_rna.c.
References BPy_GetContext(), CLAMP(), FLT_MAX, i, len(), MATHUTILS_CB_SUBTYPE_EUL, max, min, NULL, EulerObject::order, PYRNA_PROP_CHECK_INT, pyrna_rotation_euler_order_get(), rna_id_write_error(), RNA_property_array_length(), RNA_property_editable_flag(), RNA_property_enum_set(), RNA_property_float_range(), RNA_property_float_set_array(), RNA_property_identifier(), RNA_property_update(), RNA_property_update_check(), and RNA_struct_identifier().
static int mathutils_rna_vector_set_index (BaseMathObject * bmo, int UNUSEDsubtype, int index) [static]
Definition at line 478 of file bpy_rna.c.
References BPy_GetContext(), NULL, PYRNA_PROP_CHECK_INT, rna_id_write_error(), RNA_property_editable_flag(), RNA_property_float_clamp(), RNA_property_float_set_index(), RNA_property_identifier(), RNA_property_update(), RNA_property_update_check(), and RNA_struct_identifier().
static int prop_subscript_ass_array_int (BPy_PropertyArrayRNA * self, Py_ssize_t keynum, PyObject * value) [static]
Definition at line 2718 of file bpy_rna.c.
References len(), pyrna_prop_array_length(), PYRNA_PROP_CHECK_INT, and pyrna_py_to_prop_array_index().
Referenced by pyrna_prop_array_ass_subscript().
static int prop_subscript_ass_array_slice (PointerRNA * ptr, PropertyRNA * prop, int start, int stop, int length, PyObject * value_orig) [static]
Definition at line 2613 of file bpy_rna.c.
References CLAMP(), max, min, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PYRNA_STACK_ARRAY, RNA_property_boolean_get_array(), RNA_property_boolean_set_array(), RNA_property_float_get_array(), RNA_property_float_range(), RNA_property_float_set_array(), RNA_property_int_get_array(), RNA_property_int_range(), RNA_property_int_set_array(), and RNA_property_type().
Referenced by pyrna_prop_array_ass_subscript().
PyDoc_STRVAR (pyrna_struct_keys_doc , ".. method:: keys()\n""\n"" Returns the keys of this objects custom properties (matches pythons\n"" dictionary function of the same name).\n""\n"" :return: custom property keys.\n"" :rtype: list of strings\n""\n" BPY_DOC_ID_PROP_TYPE_NOTE)
PyDoc_STRVAR (pyrna_prop_collection_foreach_get_doc)
PyDoc_STRVAR (pyrna_prop_collection_foreach_set_doc , ".. method:: foreach_set(attr, seq)\n""\n"" This is a function to give fast access to attributes within a collection.\n""\n"" .. code-block:: python\n""\n"" collection.foreach_set(seq, attr)\n""\n"" # Python equivalent\n"" for i in range(len(seq)): setattr(collection[i], attr, seq[i])\n""\n")
PyDoc_STRVAR (pyrna_struct_items_doc , ".. method:: items()\n""\n"" Returns the items of this objects custom properties (matches pythons\n"" dictionary function of the same name).\n""\n"" :return: custom property key, value pairs.\n"":rtype:list of key, value tuples\n""\n" BPY_DOC_ID_PROP_TYPE_NOTE)
PyDoc_STRVAR (pyrna_struct_values_doc , ".. method:: values()\n""\n"" Returns the values of this objects custom properties (matches pythons\n"" dictionary function of the same name).\n""\n"" :return: custom property values.\n"" :rtype: list\n""\n" BPY_DOC_ID_PROP_TYPE_NOTE)
PyDoc_STRVAR (pyrna_struct_is_property_set_doc , ".. method:: is_property_set(property)\n""\n"" Check if a property is set, use for testing operator properties.\n""\n"":return:True when the property has been set.\n"":rtype:boolean\n")
PyDoc_STRVAR (pyrna_struct_is_property_hidden_doc , ".. method:: is_property_hidden(property)\n""\n"" Check if a property is hidden.\n""\n"" :return: True when the property is hidden.\n"" :rtype: boolean\n")
PyDoc_STRVAR (pyrna_struct_path_resolve_doc , ".. method:: path_resolve(path, coerce=True)\n""\n"" Returns the property from the path, raise an exception when not found.\n""\n"":arg path:path which this property resolves.\n"":type path:string\n"":arg coerce:optional argument, when True, the property will be converted\n""into its python representation.\n"":type coerce:boolean\n")
PyDoc_STRVAR (pyrna_struct_path_from_id_doc , ".. method:: path_from_id(property=\"\")\n""\n"" Returns the data path from the ID to this object (string).\n""\n"" :arg property: Optional property name which can be used if the path is\n"" to a property of this object.\n"" :type property: string\n"" :return: The path from :class:`bpy.types.bpy_struct.id_data`\n"" to this struct and property (when given).\n"" :rtype: str\n")
PyDoc_STRVAR (pyrna_prop_path_from_id_doc , ".. method:: path_from_id()\n""\n"" Returns the data path from the ID to this property (string).\n""\n"" :return: The path from :class:`bpy.types.bpy_struct.id_data` to this property.\n"" :rtype: str\n")
PyDoc_STRVAR (pyrna_register_class_doc , ".. method:: register_class(cls)\n""\n"" Register a subclass of a blender type in (:class:`bpy.types.Panel`,\n"" :class:`bpy.types.Menu`, :class:`bpy.types.Header`, :class:`bpy.types.Operator`,\n"" :class:`bpy.types.KeyingSetInfo`, :class:`bpy.types.RenderEngine`).\n""\n"" If the class has a *register* class method it will be called\n"" before registration.\n""\n"" .. note::\n""\n"" :exc:`ValueError` exception is raised if the class is not a\n"" subclass of a registerable blender class.\n""\n")
PyDoc_STRVAR (pyrna_struct_type_recast_doc , ".. method:: type_recast()\n""\n"" Return a new instance, this is needed because types\n""such as textures can be changed at runtime.\n""\n"":return:a new instance of this object with the type initialized again.\n"":rtype:subclass of:class:`bpy.types.bpy_struct`\n")
PyDoc_STRVAR (pyrna_unregister_class_doc , ".. method:: unregister_class(cls)\n""\n"" Unload the python class from blender.\n""\n"" If the class has an *unregister* class method it will be called\n"" before unregistering.\n")
PyDoc_STRVAR (pyrna_struct_get_id_data_doc , "The :class:`bpy.types.ID` object this datablock is from or None, (not available for all data types)")
PyDoc_STRVAR (pyrna_struct_get_data_doc , "The data this property is using, *type *:class:`bpy.types.bpy_struct`")
PyDoc_STRVAR (pyrna_struct_get_rna_type_doc , "The property type for introspection")
PyDoc_STRVAR (pyrna_prop_collection_keys_doc , ".. method:: keys()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.keys() functionality).\n""\n"" :return: the identifiers for each member of this collection.\n"" :rtype: list of strings\n")
PyDoc_STRVAR (pyrna_prop_collection_items_doc , ".. method:: items()\n""\n"" Return the identifiers of collection members\n"" (matching pythons dict.items() functionality).\n""\n"" :return: (key, value) pairs for each member of this collection.\n"" :rtype: list of tuples\n")
PyDoc_STRVAR (pyrna_prop_collection_values_doc , ".. method:: values()\n""\n"" Return the values of collection\n"" (matching pythons dict.values() functionality).\n""\n"" :return: the members of this collection.\n"" :rtype: list\n")
PyDoc_STRVAR (pyrna_struct_get_doc , ".. method:: get(key, default=None)\n""\n"" Returns the value of the custom property assigned to key or default\n"" when not found (matches pythons dictionary function of the same name).\n""\n"" :arg key: The key associated with the custom property.\n"" :type key: string\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n""\n" BPY_DOC_ID_PROP_TYPE_NOTE)
PyDoc_STRVAR (pyrna_struct_as_pointer_doc , ".. method:: as_pointer()\n""\n"" Returns the memory address which holds a pointer to blenders internal data\n""\n"" :return: int (memory address).\n"" :rtype: int\n""\n"" .. note:: This is intended only for advanced script writers who need to\n"" pass blender data to their own C/Python modules.\n")
PyDoc_STRVAR (pyrna_prop_collection_get_doc , ".. method:: get(key, default=None)\n""\n"" Returns the value of the item assigned to key or default when not found\n"" (matches pythons dictionary function of the same name).\n""\n"" :arg key: The identifier for the collection member.\n"" :type key: string\n"" :arg default: Optional argument for the value to return if\n"" *key* is not found.\n"" :type default: Undefined\n")
PyDoc_STRVAR (pyrna_prop_collection_find_doc , ".. method:: find(key)\n""\n"" Returns the index of a key in a collection or -1 when not found\n"" (matches pythons string find function of the same name).\n""\n"" :arg key: The identifier for the collection member.\n"" :type key: string\n"" :return: index of the key.\n"" :rtype: int\n")
void pyrna_alloc_types (void)
Definition at line 7179 of file bpy_rna.c.
References pyrna_struct_Subtype(), RNA_blender_rna_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, and RNA_struct_find_property().
Referenced by BPY_python_start().
static PyObject * pyrna_basetype_dir (BPy_BaseTypeRNA * self) [static]
Definition at line 6399 of file bpy_rna.c.
References RNA_Operator, RNA_PROP_BEGIN, RNA_PROP_END, RNA_struct_base(), and RNA_struct_identifier().
static PyObject* pyrna_basetype_getattro (BPy_BaseTypeRNA * self, PyObject * pyname) [static]
Definition at line 6334 of file bpy_rna.c.
References NULL, pyrna_struct_Subtype(), and RNA_property_collection_lookup_string().
Referenced by BPY_rna_types().
int pyrna_deferred_register_class (StructRNA * srna, PyObject * py_class)
Definition at line 6667 of file bpy_rna.c.
References pyrna_deferred_register_class_recursive(), and RNA_struct_idprops_register_check().
Referenced by operator_properties_init(), and pyrna_register_class().
static int pyrna_deferred_register_class_recursive (StructRNA * srna, PyTypeObject * py_class) [static]
Definition at line 6634 of file bpy_rna.c.
References i, len(), and pyrna_deferred_register_props().
Referenced by pyrna_deferred_register_class().
static int pyrna_deferred_register_props (StructRNA * srna, PyObject * class_dict) [static]
Definition at line 6599 of file bpy_rna.c.
References bpy_intern_str_order, and deferred_register_prop().
Referenced by pyrna_deferred_register_class_recursive().
static void pyrna_dir_members_py (PyObject * list, PyObject * self) [static]
Definition at line 3304 of file bpy_rna.c.
References BPy_PropertyRNA_Check, BPy_PropertyRNA::prop, PROP_COLLECTION, BPy_PropertyRNA::ptr, pyrna_dir_members_py__add_keys(), pyrna_struct_Subtype(), RNA_property_collection_type_get(), and RNA_property_type().
Referenced by pyrna_prop_dir(), and pyrna_struct_dir().
static void pyrna_dir_members_py__add_keys (PyObject * list, PyObject * dict) [static]
Definition at line 3295 of file bpy_rna.c.
Referenced by pyrna_dir_members_py().
static void pyrna_dir_members_rna (PyObject * list, PointerRNA * ptr) [static]
Definition at line 3336 of file bpy_rna.c.
References MEM_freeN(), RNA_function_identifier(), RNA_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, RNA_Struct, RNA_struct_find_property(), RNA_struct_iterator_property(), RNA_struct_name_get_alloc(), and PointerRNA::type.
Referenced by pyrna_prop_dir(), and pyrna_struct_dir().
static const char* pyrna_enum_as_string (PointerRNA * ptr, PropertyRNA * prop) [static]
Definition at line 1123 of file bpy_rna.c.
References BPy_enum_as_string(), BPy_GetContext(), FALSE, MEM_freeN(), NULL, and RNA_property_enum_items().
Referenced by pyrna_string_to_enum().
PyObject* pyrna_enum_bitfield_to_py (EnumPropertyItem * items, int value)
Definition at line 1241 of file bpy_rna.c.
References NULL, RNA_enum_bitflag_identifiers(), and RNA_ENUM_BITFLAG_SIZE.
Referenced by pyop_call().
static PyObject* pyrna_enum_to_py (PointerRNA * ptr, PropertyRNA * prop, int val) [static]
Definition at line 1259 of file bpy_rna.c.
References BLI_snprintf(), BPy_GetContext(), FALSE, EnumPropertyItem::identifier, MEM_freeN(), NULL, PROP_ENUM_FLAG, RNA_ENUM_BITFLAG_SIZE, RNA_property_enum_bitflag_identifiers(), RNA_property_enum_identifier(), RNA_property_enum_items(), RNA_property_flag(), RNA_property_identifier(), RNA_struct_identifier(), RNA_struct_name_get_alloc(), and PointerRNA::type.
Referenced by pyrna_param_to_py(), and pyrna_prop_to_py().
int pyrna_enum_value_from_id (EnumPropertyItem * item, const char * identifier, int * value, const char * error_prefix)
Definition at line 732 of file bpy_rna.c.
References BPy_enum_as_string(), MEM_freeN(), and RNA_enum_value_from_id().
Referenced by pyrna_callback_add(), and pyrna_set_to_enum_bitfield().
void pyrna_free_types (void)
Definition at line 7210 of file bpy_rna.c.
References bpy_class_free(), RNA_blender_rna_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, RNA_struct_find_property(), RNA_struct_py_type_get(), RNA_struct_py_type_set(), and srna_from_ptr().
Referenced by BPY_python_end().
static PyObject* pyrna_func_call (BPy_FunctionRNA * self, PyObject * args, PyObject * kw) [static]
Definition at line 4875 of file bpy_rna.c.
References BKE_reports_init(), BLI_assert, BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), BLI_snprintf(), BPy_GetContext(), BPy_reports_to_error(), C, ParameterIterator::data, PointerRNA::data, err, FALSE, i, PointerRNA::id, MEM_freeN(), NULL, ParameterIterator::parm, PROP_OUTPUT, PROP_REQUIRED, PyC_FileAndNum(), pyrna_param_to_py(), pyrna_py_to_prop(), RNA_Function, RNA_function_call(), RNA_function_identifier(), RNA_parameter_list_arg_count(), RNA_parameter_list_begin(), RNA_parameter_list_create(), RNA_parameter_list_end(), RNA_parameter_list_free(), RNA_parameter_list_next(), RNA_pointer_create(), RNA_property_flag(), RNA_property_identifier(), RNA_struct_identifier(), RPT_STORE, small_dict_get_item_string(), TRUE, PointerRNA::type, and ParameterIterator::valid.
static PyObject* pyrna_func_doc_get (BPy_FunctionRNA * self, void * UNUSEDclosure) [static]
Definition at line 5178 of file bpy_rna.c.
References MEM_freeN(), RNA_function_as_string_keywords(), RNA_function_identifier(), RNA_function_ui_description(), RNA_struct_identifier(), and TRUE.
static PyObject* pyrna_func_doc_get (BPy_FunctionRNA * self, void * closure) [static]
static PyObject* pyrna_func_repr (BPy_FunctionRNA * self) [static]
Definition at line 1007 of file bpy_rna.c.
References RNA_function_identifier(), and RNA_struct_identifier().
static PyObject* pyrna_func_to_py (PointerRNA * ptr, FunctionRNA * func) [static]
Definition at line 1481 of file bpy_rna.c.
References BPy_FunctionRNA::func, BPy_FunctionRNA::ptr, and pyrna_func_Type.
Referenced by pyrna_prop_collection_getattro(), and pyrna_struct_getattro().
static int pyrna_is_deferred_prop (const PyObject * value) [static]
Definition at line 3555 of file bpy_rna.c.
Referenced by deferred_register_prop(), and pyrna_struct_meta_idprop_setattro().
PyObject* pyrna_math_object_from_array (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 603 of file bpy_rna.c.
References Color_CreatePyObject(), Color_CreatePyObject_cb(), Euler_CreatePyObject(), Euler_CreatePyObject_cb(), EULER_ORDER_XYZ, FALSE, len(), MATHUTILS_CB_SUBTYPE_COLOR, MATHUTILS_CB_SUBTYPE_EUL, MATHUTILS_CB_SUBTYPE_QUAT, MATHUTILS_CB_SUBTYPE_VEC, Matrix_CreatePyObject(), Matrix_CreatePyObject_cb(), NULL, PROP_ALL_VECTOR_SUBTYPES, PROP_COLOR, PROP_COLOR_GAMMA, PROP_DYNAMIC, PROP_EULER, PROP_FLOAT, PROP_MATRIX, PROP_QUATERNION, PROP_THICK_WRAP, Py_NEW, pyrna_prop_array_subscript_slice(), pyrna_prop_CreatePyObject(), pyrna_rotation_euler_order_get(), Quaternion_CreatePyObject(), Quaternion_CreatePyObject_cb(), RNA_property_array_dimension(), RNA_property_array_length(), RNA_property_flag(), RNA_property_float_get_array(), RNA_property_subtype(), RNA_property_type(), Vector_CreatePyObject(), and Vector_CreatePyObject_cb().
Referenced by pyrna_py_from_array().
static PyObject* pyrna_param_to_py (PointerRNA * ptr, PropertyRNA * prop, void * data) [static]
Definition at line 4679 of file bpy_rna.c.
References ParameterDynAlloc::array, ParameterDynAlloc::array_tot, data, PointerRNA::data, ELEM3, ListBase::first, PointerRNA::id, len(), link(), Matrix_CreatePyObject(), CollectionPointerLink::next, NULL, PROP_ALL_VECTOR_SUBTYPES, PROP_BOOLEAN, PROP_BYTESTRING, PROP_COLLECTION, PROP_DIRPATH, PROP_DYNAMIC, PROP_ENUM, PROP_FILENAME, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_MATRIX, PROP_POINTER, PROP_RNAPTR, PROP_STRING, PROP_THICK_WRAP, CollectionPointerLink::ptr, Py_NEW, PyC_UnicodeFromByte(), pyrna_enum_to_py(), pyrna_struct_CreatePyObject(), RNA_id_pointer_create(), RNA_pointer_create(), RNA_property_array_check(), RNA_property_array_length(), RNA_property_flag(), RNA_property_pointer_type(), RNA_property_subtype(), RNA_property_type(), RNA_struct_is_ID(), and Vector_CreatePyObject().
Referenced by bpy_class_call(), and pyrna_func_call().
static int pyrna_prop_array_ass_subscript (BPy_PropertyArrayRNA * self, PyObject * key, PyObject * value) [static]
Definition at line 2736 of file bpy_rna.c.
References BPy_GetContext(), i, len(), prop_subscript_ass_array_int(), prop_subscript_ass_array_slice(), PYRNA_PROP_CHECK_INT, RNA_property_array_length(), RNA_property_editable_flag(), RNA_property_identifier(), RNA_property_update(), RNA_property_update_check(), RNA_struct_identifier(), and step().
static int pyrna_prop_array_bool (BPy_PropertyRNA * self) [static]
Definition at line 2007 of file bpy_rna.c.
References PYRNA_PROP_CHECK_INT, and RNA_property_array_length().
static int pyrna_prop_array_contains (BPy_PropertyRNA * self, PyObject * value) [static]
Definition at line 2830 of file bpy_rna.c.
References pyrna_array_contains_py().
static void pyrna_prop_array_dealloc (BPy_PropertyRNA * self) [static]
Definition at line 1112 of file bpy_rna.c.
References NULL.
static PyObject* pyrna_prop_array_getattro (BPy_PropertyRNA * self, PyObject * pyname) [static]
Definition at line 3746 of file bpy_rna.c.
static PyObject* pyrna_prop_array_iter (BPy_PropertyArrayRNA * self) [static]
Definition at line 4503 of file bpy_rna.c.
References len(), NULL, pyrna_prop_array_length(), pyrna_prop_array_subscript_slice(), and PYRNA_PROP_CHECK_OBJ.
static Py_ssize_t pyrna_prop_array_length (BPy_PropertyArrayRNA * self) [static]
Definition at line 1988 of file bpy_rna.c.
References NULL, PYRNA_PROP_CHECK_INT, RNA_property_array_dimension(), RNA_property_array_length(), and RNA_property_multi_array_length().
Referenced by prop_subscript_ass_array_int(), pyrna_prop_array_iter(), pyrna_prop_array_subscript(), pyrna_prop_array_subscript_int(), and pyrna_prop_str().
static PyObject* pyrna_prop_array_subscript (BPy_PropertyArrayRNA * self, PyObject * key) [static]
Definition at line 2558 of file bpy_rna.c.
References i, len(), NULL, pyrna_prop_array_length(), pyrna_prop_array_subscript_int(), pyrna_prop_array_subscript_slice(), PYRNA_PROP_CHECK_OBJ, and step().
static PyObject* pyrna_prop_array_subscript_int (BPy_PropertyArrayRNA * self, int keynum) [static]
Definition at line 2103 of file bpy_rna.c.
References len(), NULL, pyrna_prop_array_length(), pyrna_prop_array_to_py_index(), and PYRNA_PROP_CHECK_OBJ.
Referenced by pyrna_prop_array_subscript().
static PyObject * pyrna_prop_array_subscript_slice (BPy_PropertyArrayRNA * self, PointerRNA * ptr, PropertyRNA * prop, Py_ssize_t start, Py_ssize_t stop, Py_ssize_t length) [static]
Definition at line 2293 of file bpy_rna.c.
References BLI_assert, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, pyrna_prop_array_to_py_index(), PYRNA_PROP_CHECK_OBJ, PYRNA_STACK_ARRAY, RNA_property_array_dimension(), RNA_property_boolean_get_array(), RNA_property_float_get_array(), RNA_property_int_get_array(), and RNA_property_type().
Referenced by pyrna_math_object_from_array(), pyrna_prop_array_iter(), and pyrna_prop_array_subscript().
static PyObject* pyrna_prop_array_to_py_index (BPy_PropertyArrayRNA * self, int index) [static]
Definition at line 1909 of file bpy_rna.c.
References PYRNA_PROP_CHECK_OBJ, and pyrna_py_from_array_index().
Referenced by pyrna_prop_array_subscript_int(), and pyrna_prop_array_subscript_slice().
static int pyrna_prop_collection_ass_subscript (BPy_PropertyRNA * self, PyObject * key, PyObject * value) [static]
Definition at line 2484 of file bpy_rna.c.
References i, len(), NULL, PYRNA_PROP_CHECK_INT, pyrna_prop_collection_ass_subscript_int(), pyrna_prop_collection_subscript_slice(), pyrna_prop_collection_subscript_str(), pyrna_prop_collection_type_check(), RNA_property_collection_length(), and step().
static int pyrna_prop_collection_ass_subscript_int (BPy_PropertyRNA * self, Py_ssize_t keynum, PyObject * value) [static]
Definition at line 2075 of file bpy_rna.c.
References len(), PointerRNA_NULL, PYRNA_PROP_CHECK_INT, PYRNA_PROP_COLLECTION_ABS_INDEX, RNA_property_collection_assign_int(), and RNA_property_collection_length().
Referenced by pyrna_prop_collection_ass_subscript().
static int pyrna_prop_collection_bool (BPy_PropertyRNA * self) [static]
Definition at line 2014 of file bpy_rna.c.
References PYRNA_PROP_CHECK_INT, RNA_property_collection_begin(), RNA_property_collection_end(), and CollectionPropertyIterator::valid.
static int pyrna_prop_collection_contains (BPy_PropertyRNA * self, PyObject * key) [static]
Definition at line 2835 of file bpy_rna.c.
References FALSE, pyrna_prop_collection_subscript_str_lib_pair_ptr(), and RNA_property_collection_lookup_string().
static PyObject* pyrna_prop_collection_find (BPy_PropertyRNA * self, PyObject * key_ob) [static]
Definition at line 4179 of file bpy_rna.c.
References i, MEM_freeN(), PYRNA_PROP_CHECK_OBJ, RNA_PROP_BEGIN, RNA_PROP_END, and RNA_struct_name_get_alloc().
static PyObject* pyrna_prop_collection_foreach_get (BPy_PropertyRNA * self, PyObject * args) [static]
Definition at line 4474 of file bpy_rna.c.
References foreach_getset(), and PYRNA_PROP_CHECK_OBJ.
static PyObject* pyrna_prop_collection_foreach_set (BPy_PropertyRNA * self, PyObject * args) [static]
Definition at line 4494 of file bpy_rna.c.
References foreach_getset(), and PYRNA_PROP_CHECK_OBJ.
static PyObject* pyrna_prop_collection_get (BPy_PropertyRNA * self, PyObject * args) [static]
Definition at line 4134 of file bpy_rna.c.
References FALSE, NULL, PYRNA_PROP_CHECK_OBJ, pyrna_prop_collection_subscript_str_lib_pair(), pyrna_struct_CreatePyObject(), and RNA_property_collection_lookup_string().
static PyObject* pyrna_prop_collection_getattro (BPy_PropertyRNA * self, PyObject * pyname) [static]
Definition at line 3751 of file bpy_rna.c.
References NULL, pyrna_func_to_py(), pyrna_prop_to_py(), pyrna_struct_CreatePyObject(), pyrna_struct_Subtype(), RNA_property_collection_type_get(), RNA_struct_find_function(), and RNA_struct_find_property().
static PyObject* pyrna_prop_collection_idprop_add (BPy_PropertyRNA * self) [static]
Definition at line 3853 of file bpy_rna.c.
References PointerRNA::data, NULL, pyrna_struct_CreatePyObject(), and RNA_property_collection_add().
static PyObject* pyrna_prop_collection_idprop_clear (BPy_PropertyRNA * self) [static]
Definition at line 3884 of file bpy_rna.c.
References RNA_property_collection_clear().
static PyObject* pyrna_prop_collection_idprop_move (BPy_PropertyRNA * self, PyObject * args) [static]
Definition at line 3891 of file bpy_rna.c.
References NULL, and RNA_property_collection_move().
static PyObject* pyrna_prop_collection_idprop_remove (BPy_PropertyRNA * self, PyObject * value) [static]
Definition at line 3867 of file bpy_rna.c.
References NULL, and RNA_property_collection_remove().
static PyObject* pyrna_prop_collection_items (BPy_PropertyRNA * self) [static]
Definition at line 4012 of file bpy_rna.c.
References i, MEM_freeN(), pyrna_struct_CreatePyObject(), RNA_PROP_BEGIN, RNA_PROP_END, and RNA_struct_name_get_alloc().
static PyObject * pyrna_prop_collection_iter (BPy_PropertyRNA * self) [static]
Definition at line 5908 of file bpy_rna.c.
References pyrna_prop_collection_iter_CreatePyObject().
PyObject* pyrna_prop_collection_iter_CreatePyObject (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 5895 of file bpy_rna.c.
References NULL, and RNA_property_collection_begin().
Referenced by pyrna_prop_collection_iter().
static void pyrna_prop_collection_iter_dealloc (BPy_PropertyCollectionIterRNA * self) [static]
Definition at line 5940 of file bpy_rna.c.
References RNA_property_collection_end().
static PyObject * pyrna_prop_collection_iter_next (BPy_PropertyCollectionIterRNA * self) [static]
Definition at line 5913 of file bpy_rna.c.
References FALSE, NULL, pyrna_struct_CreatePyObject(), and RNA_property_collection_next().
static PyObject* pyrna_prop_collection_keys (BPy_PropertyRNA * self) [static]
Definition at line 3976 of file bpy_rna.c.
References MEM_freeN(), RNA_PROP_BEGIN, RNA_PROP_END, and RNA_struct_name_get_alloc().
static Py_ssize_t pyrna_prop_collection_length (BPy_PropertyRNA * self) [static]
Definition at line 1998 of file bpy_rna.c.
References PYRNA_PROP_CHECK_INT, and RNA_property_collection_length().
Referenced by pyrna_prop_str().
static int pyrna_prop_collection_setattro (BPy_PropertyRNA * self, PyObject * pyname, PyObject * value) [static]
Definition at line 3819 of file bpy_rna.c.
References pyrna_py_to_prop(), rna_id_write_error(), RNA_property_collection_type_get(), and RNA_struct_find_property().
static PyObject* pyrna_prop_collection_subscript (BPy_PropertyRNA * self, PyObject * key) [static]
Definition at line 2372 of file bpy_rna.c.
References i, len(), NULL, PYRNA_PROP_CHECK_OBJ, pyrna_prop_collection_subscript_int(), pyrna_prop_collection_subscript_slice(), pyrna_prop_collection_subscript_str(), pyrna_prop_collection_subscript_str_lib_pair(), RNA_property_collection_length(), step(), and TRUE.
static PyObject* pyrna_prop_collection_subscript_int (BPy_PropertyRNA * self, Py_ssize_t keynum) [static]
Definition at line 2044 of file bpy_rna.c.
References len(), NULL, PYRNA_PROP_CHECK_OBJ, PYRNA_PROP_COLLECTION_ABS_INDEX, pyrna_struct_CreatePyObject(), RNA_property_collection_length(), and RNA_property_collection_lookup_int().
Referenced by pyrna_prop_collection_subscript().
static PyObject* pyrna_prop_collection_subscript_slice (BPy_PropertyRNA * self, Py_ssize_t start, Py_ssize_t stop) [static]
Definition at line 2246 of file bpy_rna.c.
References CollectionPropertyIterator::ptr, PYRNA_PROP_CHECK_OBJ, pyrna_struct_CreatePyObject(), RNA_property_collection_begin(), RNA_property_collection_end(), RNA_property_collection_next(), and CollectionPropertyIterator::valid.
Referenced by pyrna_prop_collection_ass_subscript(), pyrna_prop_collection_subscript(), and pyrna_prop_collection_values().
static PyObject* pyrna_prop_collection_subscript_str (BPy_PropertyRNA * self, const char * keyname) [static]
Definition at line 2121 of file bpy_rna.c.
References NULL, PYRNA_PROP_CHECK_OBJ, pyrna_struct_CreatePyObject(), and RNA_property_collection_lookup_string().
Referenced by pyrna_prop_collection_ass_subscript(), and pyrna_prop_collection_subscript().
static PyObject* pyrna_prop_collection_subscript_str_lib_pair (BPy_PropertyRNA * self, PyObject * key, const char * err_prefix, const short err_not_found) [static]
Definition at line 2231 of file bpy_rna.c.
References NULL, pyrna_prop_collection_subscript_str_lib_pair_ptr(), and pyrna_struct_CreatePyObject().
Referenced by pyrna_prop_collection_get(), and pyrna_prop_collection_subscript().
int pyrna_prop_collection_subscript_str_lib_pair_ptr (BPy_PropertyRNA * self, PyObject * key, const char * err_prefix, const short err_not_found, PointerRNA * r_ptr)
Definition at line 2144 of file bpy_rna.c.
References BLI_findstring(), FALSE, ID::lib, Main::library, ID::name, NULL, RNA_BlendData, RNA_PROP_BEGIN, RNA_PROP_END, RNA_struct_identifier(), and TRUE.
Referenced by pyrna_prop_collection_contains(), and pyrna_prop_collection_subscript_str_lib_pair().
static int pyrna_prop_collection_type_check (BPy_PropertyRNA * self, PyObject * value) [static]
Definition at line 2438 of file bpy_rna.c.
References BPy_StructRNA_Check, PROP_NEVER_NULL, RNA_property_flag(), RNA_property_pointer_type(), RNA_struct_identifier(), and RNA_struct_is_a().
Referenced by pyrna_prop_collection_ass_subscript().
static PyObject * pyrna_prop_collection_values (BPy_PropertyRNA * self) [static]
Definition at line 4056 of file bpy_rna.c.
References pyrna_prop_collection_subscript_slice().
static int pyrna_prop_compare (BPy_PropertyRNA * a, BPy_PropertyRNA * b) [static]
Definition at line 763 of file bpy_rna.c.
References PointerRNA::data, BPy_PropertyRNA::prop, BPy_PropertyRNA::ptr, and PointerRNA::type.
Referenced by pyrna_prop_richcmp().
PyObject* pyrna_prop_CreatePyObject (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 6199 of file bpy_rna.c.
References PointerRNA::data, PointerRNA::id, NULL, BPy_PropertyRNA::prop, PROP_COLLECTION, PROP_IDPROPERTY, BPy_PropertyRNA::ptr, pyrna_prop_collection_idprop_Type, pyrna_prop_collection_Type, pyrna_prop_Type, RNA_property_array_check(), RNA_property_flag(), and RNA_property_type().
Referenced by pyrna_math_object_from_array(), pyrna_prop_to_py(), pyrna_py_from_array(), pyrna_py_from_array_index(), and pyrna_struct_path_resolve().
static void pyrna_prop_dealloc (BPy_PropertyRNA * self) [static]
Definition at line 1101 of file bpy_rna.c.
References NULL.
static PyObject* pyrna_prop_dir (BPy_PropertyRNA * self) [static]
Definition at line 3722 of file bpy_rna.c.
References BPy_PropertyRNA_CheckExact, PROP_COLLECTION, pyrna_dir_members_py(), pyrna_dir_members_rna(), RNA_property_collection_type_get(), and RNA_property_type().
static long pyrna_prop_hash (BPy_PropertyRNA * self) [static]
Definition at line 1022 of file bpy_rna.c.
References NULL.
static PyObject* pyrna_prop_new (PyTypeObject * type, PyObject * args, PyObject * UNUSEDkwds) [static]
Definition at line 4654 of file bpy_rna.c.
References NULL, BPy_PropertyRNA::prop, BPy_PropertyRNA::ptr, and pyrna_prop_Type.
static PyObject* pyrna_prop_path_from_id (BPy_PropertyRNA * self) [static]
Definition at line 3255 of file bpy_rna.c.
References MEM_freeN(), NULL, RNA_path_from_ID_to_property(), RNA_property_identifier(), and RNA_struct_identifier().
static PyObject* pyrna_prop_repr (BPy_PropertyRNA * self) [static]
Definition at line 965 of file bpy_rna.c.
References BKE_idcode_to_name_plural(), GS, ID_NT, MEM_freeN(), ID::name, NULL, PYRNA_PROP_CHECK_OBJ, pyrna_prop_str(), RNA_path_from_ID_to_property(), and RNA_property_identifier().
static PyObject* pyrna_prop_richcmp (PyObject * a, PyObject * b, int op) [static]
Definition at line 799 of file bpy_rna.c.
References BPy_PropertyRNA_Check, NULL, and pyrna_prop_compare().
static PyObject* pyrna_prop_str (BPy_PropertyRNA * self) [static]
Definition at line 900 of file bpy_rna.c.
References len(), MEM_freeN(), NULL, PROP_COLLECTION, PROP_POINTER, property_type_items, pyrna_prop_array_length(), PYRNA_PROP_CHECK_OBJ, pyrna_prop_collection_length(), RNA_enum_id_from_value(), RNA_property_array_check(), RNA_property_collection_type_get(), RNA_property_identifier(), RNA_property_pointer_get(), RNA_property_type(), RNA_struct_identifier(), RNA_struct_name_get_alloc(), and PointerRNA::type.
Referenced by pyrna_prop_repr().
static int pyrna_prop_to_enum_bitfield (PointerRNA * ptr, PropertyRNA * prop, PyObject * value, int * r_value, const char * error_prefix) [static]
Definition at line 1202 of file bpy_rna.c.
References BPy_GetContext(), FALSE, MEM_freeN(), NULL, pyrna_set_to_enum_bitfield(), RNA_property_enum_items(), RNA_property_identifier(), RNA_struct_identifier(), and PointerRNA::type.
Referenced by pyrna_py_to_prop().
PyObject* pyrna_prop_to_py (PointerRNA * ptr, PropertyRNA * prop)
Definition at line 1333 of file bpy_rna.c.
References PointerRNA::data, ELEM3, MEM_freeN(), NULL, PROP_BOOLEAN, PROP_BYTESTRING, PROP_COLLECTION, PROP_DIRPATH, PROP_ENUM, PROP_FILENAME, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_STRING, PyC_UnicodeFromByteAndSize(), pyrna_enum_to_py(), pyrna_prop_CreatePyObject(), pyrna_py_from_array(), pyrna_struct_CreatePyObject(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_enum_get(), RNA_property_float_get(), RNA_property_int_get(), RNA_property_pointer_get(), RNA_property_string_get_alloc(), RNA_property_subtype(), and RNA_property_type().
Referenced by pyrna_prop_collection_getattro(), pyrna_struct_getattro(), and pyrna_struct_path_resolve().
int pyrna_prop_validity_check (BPy_PropertyRNA * self)
Definition at line 109 of file bpy_rna.c.
References RNA_property_identifier().
static int pyrna_py_to_prop (PointerRNA * ptr, PropertyRNA * prop, void * data, PyObject * value, const char * error_prefix) [static]
Definition at line 1490 of file bpy_rna.c.
References BLI_addtail(), BPy_GetContext(), BPy_StructRNA_Check, data, PointerRNA::data, ELEM3, FALSE, i, PointerRNA::id, IFACE_, link(), MEM_callocN(), NULL, BPy_PropertyRNA::prop, PROP_BOOLEAN, PROP_BYTESTRING, PROP_COLLECTION, PROP_DIRPATH, PROP_ENUM, PROP_ENUM_FLAG, PROP_FILENAME, PROP_FILEPATH, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_NEVER_NULL, PROP_OUTPUT, PROP_POINTER, PROP_RNAPTR, PROP_STRING, PROP_TRANSLATE, BPy_StructRNA::ptr, BPy_PropertyRNA::ptr, CollectionPointerLink::ptr, PyC_Err_Format_Prefix(), PyC_ExceptionBuffer(), PyC_UnicodeAsByte(), pyrna_prop_collection_Type, pyrna_prop_to_enum_bitfield(), pyrna_py_to_array(), pyrna_pydict_to_props(), pyrna_string_to_enum(), pyrna_struct_CreatePyObject(), RNA_AnyType, RNA_Operator, RNA_OperatorProperties, RNA_pointer_create(), RNA_property_array_check(), RNA_property_boolean_set(), RNA_property_collection_add(), RNA_property_collection_type_get(), RNA_property_enum_set(), RNA_property_flag(), RNA_property_float_clamp(), RNA_property_float_set(), RNA_property_identifier(), RNA_property_int_clamp(), RNA_property_int_set(), RNA_property_pointer_get(), RNA_property_pointer_set(), RNA_property_pointer_type(), RNA_property_string_set(), RNA_property_subtype(), RNA_property_type(), RNA_property_update(), RNA_property_update_check(), RNA_struct_identifier(), RNA_struct_is_a(), STRINGIFY, TRUE, and PointerRNA::type.
Referenced by bpy_class_call(), bpy_class_validate(), pyrna_func_call(), pyrna_prop_collection_setattro(), pyrna_pydict_to_props(), and pyrna_struct_setattro().
static int pyrna_py_to_prop_array_index (BPy_PropertyArrayRNA * self, int index, PyObject * value) [static]
Definition at line 1915 of file bpy_rna.c.
References BPy_GetContext(), NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, pyrna_py_to_array_index(), RNA_property_array_dimension(), RNA_property_boolean_set_index(), RNA_property_float_clamp(), RNA_property_float_set_index(), RNA_property_int_clamp(), RNA_property_int_set_index(), RNA_property_type(), RNA_property_update(), and RNA_property_update_check().
Referenced by prop_subscript_ass_array_int().
int pyrna_pydict_to_props (PointerRNA * ptr, PyObject * kw, int all_args, const char * error_prefix)
Definition at line 1418 of file bpy_rna.c.
References NULL, pyrna_py_to_prop(), RNA_property_identifier(), RNA_STRUCT_BEGIN, RNA_STRUCT_END, and RNA_struct_find_property().
Referenced by pyop_as_string(), pyop_call(), and pyrna_py_to_prop().
static PyObject* pyrna_register_class (PyObject * self, PyObject * py_class) [static]
static PyObject* pyrna_register_class (PyObject * UNUSEDself, PyObject * py_class) [static]
Definition at line 7261 of file bpy_rna.c.
References BKE_reports_init(), bpy_class_call(), bpy_class_free(), bpy_class_validate(), BPy_GetContext(), bpy_intern_str_bl_rna, bpy_intern_str_register, BPy_reports_to_error(), C, CTX_data_main(), NULL, pyrna_deferred_register_class(), pyrna_struct_as_srna(), pyrna_subtype_set_rna(), pyrna_write_check(), RNA_struct_identifier(), RNA_struct_py_type_get(), RNA_struct_py_type_set(), RNA_struct_register(), RPT_STORE, and TRUE.
static short pyrna_rotation_euler_order_get (PointerRNA * ptr, PropertyRNA ** prop_eul_order, short order_fallback) [static]
Definition at line 574 of file bpy_rna.c.
References EULER_ORDER_XYZ, EULER_ORDER_ZYX, NULL, RNA_property_enum_get(), and RNA_struct_find_property().
Referenced by mathutils_rna_vector_get(), mathutils_rna_vector_set(), and pyrna_math_object_from_array().
int pyrna_set_to_enum_bitfield (EnumPropertyItem * items, PyObject * value, int * r_value, const char * error_prefix)
Definition at line 1169 of file bpy_rna.c.
References hash, NULL, and pyrna_enum_value_from_id().
Referenced by pyrna_prop_to_enum_bitfield().
static int pyrna_srna_contains_pointer_prop_srna (StructRNA * srna_props, StructRNA * srna, const char ** prop_identifier) [static]
Definition at line 7372 of file bpy_rna.c.
References ListBase::first, link(), LinkData::next, PROP_BUILTIN, PROP_POINTER, RNA_pointer_create(), RNA_property_flag(), RNA_property_identifier(), RNA_property_pointer_type(), RNA_property_type(), RNA_Struct, and RNA_struct_type_properties().
Referenced by pyrna_unregister_class().
static PyObject* pyrna_srna_ExternalType (StructRNA * srna) [static]
Definition at line 6015 of file bpy_rna.c.
References bpy_intern_str___slots__, G, G_DEBUG_PYTHON, NULL, PyC_ObSpit(), pyrna_srna_PyBase(), and RNA_struct_identifier().
Referenced by pyrna_srna_Subtype().
static PyObject* pyrna_srna_PyBase (StructRNA * srna) [static]
Definition at line 5988 of file bpy_rna.c.
References NULL, pyrna_srna_Subtype(), and RNA_struct_base().
Referenced by pyrna_srna_ExternalType(), and pyrna_srna_Subtype().
static PyObject * pyrna_srna_Subtype (StructRNA * srna) [static]
Definition at line 6065 of file bpy_rna.c.
References NULL, pyrna_srna_ExternalType(), pyrna_srna_PyBase(), pyrna_subtype_set_rna(), RNA_struct_identifier(), RNA_struct_idprops_check(), and RNA_struct_py_type_get().
Referenced by pyrna_srna_PyBase(), and pyrna_struct_Subtype().
static int pyrna_string_to_enum (PyObject * item, PointerRNA * ptr, PropertyRNA * prop, int * val, const char * error_prefix) [static]
Definition at line 1144 of file bpy_rna.c.
References BPy_GetContext(), MEM_freeN(), NULL, pyrna_enum_as_string(), and RNA_property_enum_value().
Referenced by pyrna_py_to_prop().
static PyObject* pyrna_struct_as_pointer (BPy_StructRNA * self) [static]
Definition at line 4117 of file bpy_rna.c.
StructRNA* pyrna_struct_as_srna (PyObject * self, int parent, const char * error_prefix)
Definition at line 6453 of file bpy_rna.c.
References bpy_intern_str_bl_rna, BPy_StructRNA_Check, PointerRNA::data, NULL, BPy_StructRNA::ptr, RNA_Struct, and PointerRNA::type.
Referenced by pyrna_register_class(), pyrna_unregister_class(), and srna_from_self().
static int pyrna_struct_ass_subscript (BPy_StructRNA * self, PyObject * key, PyObject * value) [static]
Definition at line 2961 of file bpy_rna.c.
References BPy_Wrap_SetMapItem(), PYRNA_STRUCT_CHECK_INT, rna_id_write_error(), and RNA_struct_idprops().
static int pyrna_struct_compare (BPy_StructRNA * a, BPy_StructRNA * b) [static]
Definition at line 757 of file bpy_rna.c.
References PointerRNA::data, BPy_StructRNA::ptr, and PointerRNA::type.
Referenced by pyrna_struct_richcmp().
static int pyrna_struct_contains (BPy_StructRNA * self, PyObject * value) [static]
Definition at line 2862 of file bpy_rna.c.
References IDP_GetPropertyFromGroup(), PYRNA_STRUCT_CHECK_INT, RNA_struct_idprops(), and RNA_struct_idprops_check().
PyObject* pyrna_struct_CreatePyObject (PointerRNA * ptr)
Definition at line 6151 of file bpy_rna.c.
References PointerRNA::data, FALSE, PointerRNA::id, NULL, BPy_StructRNA::ptr, pyrna_struct_Subtype(), and PointerRNA::type.
Referenced by bpy_app_generic_callback(), bpy_class_call(), BPy_init_modules(), bpy_lib_exit(), BPY_rna_module(), pyop_getinstance(), pyop_getrna(), PYOP_wrap_macro_define(), pyrna_param_to_py(), pyrna_prop_collection_get(), pyrna_prop_collection_getattro(), pyrna_prop_collection_idprop_add(), pyrna_prop_collection_items(), pyrna_prop_collection_iter_next(), pyrna_prop_collection_subscript_int(), pyrna_prop_collection_subscript_slice(), pyrna_prop_collection_subscript_str(), pyrna_prop_collection_subscript_str_lib_pair(), pyrna_prop_to_py(), pyrna_py_to_prop(), pyrna_struct_as_instance(), pyrna_struct_driver_add(), pyrna_struct_get_data(), pyrna_struct_get_id_data(), pyrna_struct_getattro(), pyrna_struct_path_resolve(), pyrna_struct_type_recast(), and pyrna_subtype_set_rna().
static void pyrna_struct_dealloc (BPy_StructRNA * self) [static]
Definition at line 1056 of file bpy_rna.c.
References IDP_FreeProperty(), MEM_freeN(), and NULL.
static PyObject* pyrna_struct_dir (BPy_StructRNA * self) [static]
Definition at line 3386 of file bpy_rna.c.
References BLI_freelistN(), BPy_StructRNA_CheckExact, CTX_data_dir_get(), LinkData::data, ListBase::first, link(), LinkData::next, pyrna_dir_members_py(), pyrna_dir_members_rna(), PYRNA_STRUCT_CHECK_OBJ, and RNA_Context.
static PyObject* pyrna_struct_get (BPy_StructRNA * self, PyObject * args) [static]
Definition at line 4076 of file bpy_rna.c.
References BPy_IDGroup_WrapData(), IDP_GetPropertyFromGroup(), NULL, PYRNA_STRUCT_CHECK_OBJ, RNA_struct_idprops(), and RNA_struct_idprops_check().
static PyObject* pyrna_struct_get_data (BPy_DummyPointerRNA * self) [static]
Definition at line 3927 of file bpy_rna.c.
References pyrna_struct_CreatePyObject().
static PyObject* pyrna_struct_get_id_data (BPy_DummyPointerRNA * self) [static]
Definition at line 3912 of file bpy_rna.c.
References pyrna_struct_CreatePyObject(), and RNA_id_pointer_create().
static PyObject* pyrna_struct_get_rna_type (BPy_PropertyRNA * self) [static]
Definition at line 3935 of file bpy_rna.c.
References pyrna_struct_Subtype(), RNA_pointer_create(), and RNA_Property.
static PyObject* pyrna_struct_getattro (BPy_StructRNA * self, PyObject * pyname) [static]
Definition at line 3431 of file bpy_rna.c.
References BLI_assert, BLI_freelistN(), C, CTX_data_get(), CTX_DATA_TYPE_COLLECTION, CTX_DATA_TYPE_POINTER, PointerRNA::data, ListBase::first, link(), CollectionPointerLink::next, NULL, CollectionPointerLink::ptr, pyrna_func_to_py(), pyrna_prop_to_py(), PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_CreatePyObject(), RNA_Context, RNA_function_defined(), RNA_struct_find_function(), RNA_struct_find_property(), and RNA_struct_idprops_check().
static Py_hash_t pyrna_struct_hash (BPy_StructRNA * self) [static]
Definition at line 1016 of file bpy_rna.c.
static PyObject* pyrna_struct_is_property_hidden (BPy_StructRNA * self, PyObject * args) [static]
Definition at line 3110 of file bpy_rna.c.
References NULL, PROP_HIDDEN, PYRNA_STRUCT_CHECK_OBJ, RNA_property_flag(), RNA_struct_find_property(), and RNA_struct_identifier().
static PyObject* pyrna_struct_is_property_set (BPy_StructRNA * self, PyObject * args) [static]
Definition at line 3082 of file bpy_rna.c.
References NULL, PYRNA_STRUCT_CHECK_OBJ, RNA_property_is_set(), RNA_struct_find_property(), and RNA_struct_identifier().
static PyObject* pyrna_struct_items (BPy_PropertyRNA * self) [static]
Definition at line 3028 of file bpy_rna.c.
References BPy_Wrap_GetItems(), NULL, RNA_struct_idprops(), and RNA_struct_idprops_check().
static PyObject* pyrna_struct_keys (BPy_PropertyRNA * self) [static]
Definition at line 3000 of file bpy_rna.c.
References BPy_Wrap_GetKeys(), NULL, RNA_struct_idprops(), and RNA_struct_idprops_check().
static int pyrna_struct_meta_idprop_setattro (PyObject * cls, PyObject * attr, PyObject * value) [static]
Definition at line 3594 of file bpy_rna.c.
References deferred_register_prop(), pyrna_is_deferred_prop(), pyrna_write_check(), RNA_def_property_free_identifier(), RNA_struct_type_find_property(), and srna_from_self().
static PyObject* pyrna_struct_new (PyTypeObject * type, PyObject * args, PyObject * UNUSEDkwds) [static]
Definition at line 4609 of file bpy_rna.c.
References NULL, BPy_StructRNA::ptr, and pyrna_struct_Type.
static PyObject* pyrna_struct_path_from_id (BPy_StructRNA * self, PyObject * args) [static]
Definition at line 3200 of file bpy_rna.c.
References MEM_freeN(), NULL, PYRNA_STRUCT_CHECK_OBJ, RNA_path_from_ID_to_property(), RNA_path_from_ID_to_struct(), RNA_struct_find_property(), and RNA_struct_identifier().
static PyObject* pyrna_struct_path_resolve (BPy_StructRNA * self, PyObject * args) [static]
Definition at line 3141 of file bpy_rna.c.
References NULL, pyrna_array_index(), pyrna_prop_CreatePyObject(), pyrna_prop_to_py(), PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_CreatePyObject(), RNA_path_resolve_full(), RNA_property_array_length(), and RNA_struct_identifier().
static PyObject* pyrna_struct_repr (BPy_StructRNA * self) [static]
Definition at line 854 of file bpy_rna.c.
References BKE_idcode_to_name_plural(), GS, ID_NT, MEM_freeN(), ID::name, NULL, PYRNA_STRUCT_IS_VALID, pyrna_struct_str(), RNA_path_from_ID_to_struct(), RNA_struct_identifier(), and RNA_struct_is_ID().
static PyObject* pyrna_struct_richcmp (PyObject * a, PyObject * b, int op) [static]
Definition at line 770 of file bpy_rna.c.
References BPy_StructRNA_Check, NULL, and pyrna_struct_compare().
static int pyrna_struct_setattro (BPy_StructRNA * self, PyObject * pyname, PyObject * value) [static]
Definition at line 3656 of file bpy_rna.c.
References BLI_freelistN(), C, CTX_data_get(), NULL, pyrna_py_to_prop(), PYRNA_STRUCT_CHECK_INT, RNA_Context, rna_id_write_error(), RNA_property_editable_flag(), RNA_property_identifier(), RNA_struct_find_property(), and RNA_struct_identifier().
static PyObject* pyrna_struct_str (BPy_StructRNA * self) [static]
Definition at line 829 of file bpy_rna.c.
References MEM_freeN(), NULL, PYRNA_STRUCT_IS_VALID, RNA_struct_identifier(), and RNA_struct_name_get_alloc().
Referenced by pyrna_struct_repr().
static PyObject* pyrna_struct_subscript (BPy_StructRNA * self, PyObject * key) [static]
Definition at line 2926 of file bpy_rna.c.
References BPy_IDGroup_WrapData(), IDP_GetPropertyFromGroup(), NULL, PYRNA_STRUCT_CHECK_OBJ, RNA_struct_idprops(), and RNA_struct_idprops_check().
static PyObject * pyrna_struct_Subtype (PointerRNA * ptr) [static]
Definition at line 6145 of file bpy_rna.c.
References pyrna_srna_Subtype(), and srna_from_ptr().
Referenced by pyrna_alloc_types(), pyrna_basetype_getattro(), pyrna_dir_members_py(), pyrna_prop_collection_getattro(), pyrna_struct_CreatePyObject(), and pyrna_struct_get_rna_type().
static PyObject* pyrna_struct_type_recast (BPy_StructRNA * self) [static]
Definition at line 3285 of file bpy_rna.c.
References PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_CreatePyObject(), and RNA_pointer_recast().
int pyrna_struct_validity_check (BPy_StructRNA * pysrna)
Definition at line 98 of file bpy_rna.c.
References BPy_StructRNA::ptr, and PointerRNA::type.
static PyObject* pyrna_struct_values (BPy_PropertyRNA * self) [static]
Definition at line 3056 of file bpy_rna.c.
References BPy_Wrap_GetValues(), NULL, RNA_struct_idprops(), and RNA_struct_idprops_check().
static void pyrna_subtype_set_rna (PyObject * newclass, StructRNA * srna) [static]
Definition at line 5957 of file bpy_rna.c.
References bpy_intern_str_bl_rna, PyC_ObSpit(), pyrna_struct_CreatePyObject(), RNA_pointer_create(), RNA_Struct, RNA_struct_py_type_get(), and RNA_struct_py_type_set().
Referenced by pyrna_register_class(), and pyrna_srna_Subtype().
static PyObject* pyrna_unregister_class (PyObject * UNUSEDself, PyObject * py_class) [static]
Definition at line 7407 of file bpy_rna.c.
References BPy_GetContext(), bpy_intern_str_bl_rna, bpy_intern_str_unregister, C, CTX_data_main(), G, G_DEBUG_PYTHON, NULL, pyrna_srna_contains_pointer_prop_srna(), pyrna_struct_as_srna(), pyrna_write_check(), RNA_blender_rna_pointer_create(), RNA_PROP_BEGIN, RNA_PROP_END, RNA_struct_find_property(), RNA_struct_identifier(), and RNA_struct_unregister().
static PyObject* pyrna_unregister_class (PyObject * self, PyObject * py_class) [static]
int pyrna_write_check (void)
Definition at line 342 of file bpy_rna.c.
References rna_disallow_writes.
Referenced by bpy_prop_update_cb(), pyop_call(), pyrna_register_class(), pyrna_struct_meta_idprop_setattro(), and pyrna_unregister_class().
void pyrna_write_set (int val)
Definition at line 347 of file bpy_rna.c.
Referenced by bpy_prop_update_cb().
static int rna_function_arg_count (FunctionRNA * func) [static]
Definition at line 6679 of file bpy_rna.c.
References ListBase::first, FUNC_NO_SELF, link(), Link::next, PROP_OUTPUT, RNA_function_defined_parameters(), RNA_function_flag(), and RNA_property_flag().
Referenced by bpy_class_call(), and bpy_class_validate().
static int rna_id_write_error (PointerRNA * ptr, PyObject * key) [static]
Definition at line 315 of file bpy_rna.c.
References BKE_idcode_to_name(), BLI_assert, PointerRNA::data, ELEM, FALSE, GS, PointerRNA::id, ID_SCR, ID_WM, ID::name, NULL, RNA_struct_identifier(), TRUE, and PointerRNA::type.
Referenced by mathutils_rna_matrix_set(), mathutils_rna_vector_set(), mathutils_rna_vector_set_index(), pyrna_prop_collection_setattro(), pyrna_struct_ass_subscript(), and pyrna_struct_setattro().
static PyObject* small_dict_get_item_string (PyObject * dict, const char * key_lookup) [static]
Definition at line 4858 of file bpy_rna.c.
References NULL.
Referenced by pyrna_func_call().
static StructRNA* srna_from_ptr (PointerRNA * ptr) [static]
Definition at line 6134 of file bpy_rna.c.
References PointerRNA::data, RNA_Struct, and PointerRNA::type.
Referenced by pyrna_free_types(), and pyrna_struct_Subtype().
StructRNA* srna_from_self (PyObject * self, const char * error_prefix)
Definition at line 6505 of file bpy_rna.c.
References NULL, and pyrna_struct_as_srna().
Referenced by BPy_RemoveProperty(), pointer_type_from_py(), PYOP_wrap_macro_define(), and pyrna_struct_meta_idprop_setattro().
Variable Documentation
PyObject* bpy_types_dict = NULL [static]
Definition at line 6013 of file bpy_rna.c.
Mathutils_Callback mathutils_rna_array_cb [static]
Initial value:
 {
    (BaseMathCheckFunc)     mathutils_rna_generic_check,
    (BaseMathGetFunc)       mathutils_rna_vector_get,
    (BaseMathSetFunc)       mathutils_rna_vector_set,
    (BaseMathGetIndexFunc)  mathutils_rna_vector_get_index,
    (BaseMathSetIndexFunc)  mathutils_rna_vector_set_index
}
Definition at line 510 of file bpy_rna.c.
unsigned char mathutils_rna_array_cb_index = -1 [static]
Definition at line 375 of file bpy_rna.c.
Mathutils_Callback mathutils_rna_matrix_cb [static]
Initial value:
 {
    mathutils_rna_generic_check,
    mathutils_rna_matrix_get,
    mathutils_rna_matrix_set,
    NULL,
    NULL
}
Definition at line 566 of file bpy_rna.c.
unsigned char mathutils_rna_matrix_cb_index = -1 [static]
Definition at line 520 of file bpy_rna.c.
PyMethodDef meth_bpy_register_class = {"register_class", pyrna_register_class, METH_O, pyrna_register_class_doc}
Definition at line 7260 of file bpy_rna.c.
Referenced by BPy_init_modules().
PyMethodDef meth_bpy_unregister_class
Initial value:
 {
    "unregister_class", pyrna_unregister_class, METH_O, pyrna_unregister_class_doc
}
Definition at line 7404 of file bpy_rna.c.
Referenced by BPy_init_modules().
struct PyMethodDef pyrna_basetype_methods[] [static]
Initial value:
 {
    {"__dir__", (PyCFunction)pyrna_basetype_dir, METH_NOARGS, ""},
    {NULL, NULL, 0, NULL}
}
Definition at line 6370 of file bpy_rna.c.
Referenced by BPY_rna_types().
PyTypeObject pyrna_basetype_Type = BLANK_PYTHON_TYPE [static]
Definition at line 6425 of file bpy_rna.c.
PyGetSetDef pyrna_func_getseters[] [static]
Initial value:
 {
    {(char *)"__doc__", (getter)pyrna_func_doc_get, (setter)NULL, NULL, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 3962 of file bpy_rna.c.
PyTypeObject pyrna_func_Type
Definition at line 5708 of file bpy_rna.c.
Referenced by pyrna_func_to_py().
PyMappingMethods pyrna_prop_array_as_mapping [static]
Initial value:
 {
    (lenfunc) pyrna_prop_array_length,
    (binaryfunc) pyrna_prop_array_subscript,
    (objobjargproc) pyrna_prop_array_ass_subscript,
}
Definition at line 2792 of file bpy_rna.c.
PyNumberMethods pyrna_prop_array_as_number [static]
Initial value:
 {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    (inquiry) pyrna_prop_array_bool,
}
Definition at line 2805 of file bpy_rna.c.
PySequenceMethods pyrna_prop_array_as_sequence [static]
Initial value:
 {
    (lenfunc)pyrna_prop_array_length,
    NULL,
    NULL,
    (ssizeargfunc)pyrna_prop_array_subscript_int,
    NULL,
    (ssizeobjargproc)prop_subscript_ass_array_int,
    NULL,
    (objobjproc)pyrna_prop_array_contains,
    (binaryfunc) NULL,
    (ssizeargfunc) NULL,
}
Definition at line 2887 of file bpy_rna.c.
struct PyMethodDef pyrna_prop_array_methods[] [static]
Initial value:
 {
    {NULL, NULL, 0, NULL}
}
Definition at line 4582 of file bpy_rna.c.
PyTypeObject pyrna_prop_array_Type
Definition at line 5455 of file bpy_rna.c.
PyMappingMethods pyrna_prop_collection_as_mapping [static]
Initial value:
 {
    (lenfunc) pyrna_prop_collection_length,
    (binaryfunc) pyrna_prop_collection_subscript,
    (objobjargproc) pyrna_prop_collection_ass_subscript,
}
Definition at line 2798 of file bpy_rna.c.
PyNumberMethods pyrna_prop_collection_as_number [static]
Initial value:
 {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    (inquiry) pyrna_prop_collection_bool,
}
Definition at line 2817 of file bpy_rna.c.
PySequenceMethods pyrna_prop_collection_as_sequence [static]
Initial value:
 {
    (lenfunc)pyrna_prop_collection_length,
    NULL,
    NULL,
    (ssizeargfunc)pyrna_prop_collection_subscript_int,
    NULL,
    (ssizeobjargproc) NULL ,
    NULL,
    (objobjproc)pyrna_prop_collection_contains,
    (binaryfunc) NULL,
    (ssizeargfunc) NULL,
}
Definition at line 2900 of file bpy_rna.c.
struct PyMethodDef pyrna_prop_collection_idprop_methods[] [static]
Initial value:
 {
    {"add", (PyCFunction)pyrna_prop_collection_idprop_add, METH_NOARGS, NULL},
    {"remove", (PyCFunction)pyrna_prop_collection_idprop_remove, METH_O, NULL},
    {"clear", (PyCFunction)pyrna_prop_collection_idprop_clear, METH_NOARGS, NULL},
    {"move", (PyCFunction)pyrna_prop_collection_idprop_move, METH_VARARGS, NULL},
    {NULL, NULL, 0, NULL}
}
Definition at line 4599 of file bpy_rna.c.
PyTypeObject pyrna_prop_collection_idprop_Type [static]
Definition at line 5623 of file bpy_rna.c.
Referenced by pyrna_prop_CreatePyObject().
PyTypeObject pyrna_prop_collection_iter_Type
Definition at line 5804 of file bpy_rna.c.
struct PyMethodDef pyrna_prop_collection_methods[] [static]
Initial value:
 {
    {"foreach_get", (PyCFunction)pyrna_prop_collection_foreach_get, METH_VARARGS, pyrna_prop_collection_foreach_get_doc},
    {"foreach_set", (PyCFunction)pyrna_prop_collection_foreach_set, METH_VARARGS, pyrna_prop_collection_foreach_set_doc},
    {"keys", (PyCFunction)pyrna_prop_collection_keys, METH_NOARGS, pyrna_prop_collection_keys_doc},
    {"items", (PyCFunction)pyrna_prop_collection_items, METH_NOARGS, pyrna_prop_collection_items_doc},
    {"values", (PyCFunction)pyrna_prop_collection_values, METH_NOARGS, pyrna_prop_collection_values_doc},
    {"get", (PyCFunction)pyrna_prop_collection_get, METH_VARARGS, pyrna_prop_collection_get_doc},
    {"find", (PyCFunction)pyrna_prop_collection_find, METH_O, pyrna_prop_collection_find_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 4586 of file bpy_rna.c.
PyTypeObject pyrna_prop_collection_Type
Definition at line 5538 of file bpy_rna.c.
Referenced by pyrna_prop_CreatePyObject(), and pyrna_py_to_prop().
PyGetSetDef pyrna_prop_getseters[] [static]
Initial value:
 {
    {(char *)"id_data", (getter)pyrna_struct_get_id_data, (setter)NULL, (char *)pyrna_struct_get_id_data_doc, NULL},
    {(char *)"data", (getter)pyrna_struct_get_data, (setter)NULL, (char *)pyrna_struct_get_data_doc, NULL},
    {(char *)"rna_type", (getter)pyrna_struct_get_rna_type, (setter)NULL, (char *)pyrna_struct_get_rna_type_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 3948 of file bpy_rna.c.
struct PyMethodDef pyrna_prop_methods[] [static]
Initial value:
 {
    {"path_from_id", (PyCFunction)pyrna_prop_path_from_id, METH_NOARGS, pyrna_prop_path_from_id_doc},
    {"__dir__", (PyCFunction)pyrna_prop_dir, METH_NOARGS, NULL},
    {NULL, NULL, 0, NULL}
}
Definition at line 4576 of file bpy_rna.c.
PyTypeObject pyrna_prop_Type
Definition at line 5371 of file bpy_rna.c.
Referenced by pyrna_prop_CreatePyObject(), and pyrna_prop_new().
PyMappingMethods pyrna_struct_as_mapping [static]
Initial value:
 {
    (lenfunc) NULL,
    (binaryfunc) pyrna_struct_subscript,
    (objobjargproc) pyrna_struct_ass_subscript,
}
Definition at line 2983 of file bpy_rna.c.
PySequenceMethods pyrna_struct_as_sequence [static]
Initial value:
 {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    (objobjproc)pyrna_struct_contains,
    (binaryfunc) NULL,
    (ssizeargfunc) NULL,
}
Definition at line 2913 of file bpy_rna.c.
PyGetSetDef pyrna_struct_getseters[] [static]
Initial value:
 {
    {(char *)"id_data", (getter)pyrna_struct_get_id_data, (setter)NULL, (char *)pyrna_struct_get_id_data_doc, NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 3955 of file bpy_rna.c.
PyTypeObject pyrna_struct_meta_idprop_Type
Definition at line 5197 of file bpy_rna.c.
Referenced by BPy_init_modules().
struct PyMethodDef pyrna_struct_methods[] [static]
Initial value:
 {
    {"keys", (PyCFunction)pyrna_struct_keys, METH_NOARGS, pyrna_struct_keys_doc},
    {"values", (PyCFunction)pyrna_struct_values, METH_NOARGS, pyrna_struct_values_doc},
    {"items", (PyCFunction)pyrna_struct_items, METH_NOARGS, pyrna_struct_items_doc},
    {"get", (PyCFunction)pyrna_struct_get, METH_VARARGS, pyrna_struct_get_doc},
    {"as_pointer", (PyCFunction)pyrna_struct_as_pointer, METH_NOARGS, pyrna_struct_as_pointer_doc},
    {"keyframe_insert", (PyCFunction)pyrna_struct_keyframe_insert, METH_VARARGS | METH_KEYWORDS, pyrna_struct_keyframe_insert_doc},
    {"keyframe_delete", (PyCFunction)pyrna_struct_keyframe_delete, METH_VARARGS | METH_KEYWORDS, pyrna_struct_keyframe_delete_doc},
    {"driver_add", (PyCFunction)pyrna_struct_driver_add, METH_VARARGS, pyrna_struct_driver_add_doc},
    {"driver_remove", (PyCFunction)pyrna_struct_driver_remove, METH_VARARGS, pyrna_struct_driver_remove_doc},
    {"is_property_set", (PyCFunction)pyrna_struct_is_property_set, METH_VARARGS, pyrna_struct_is_property_set_doc},
    {"is_property_hidden", (PyCFunction)pyrna_struct_is_property_hidden, METH_VARARGS, pyrna_struct_is_property_hidden_doc},
    {"path_resolve", (PyCFunction)pyrna_struct_path_resolve, METH_VARARGS, pyrna_struct_path_resolve_doc},
    {"path_from_id", (PyCFunction)pyrna_struct_path_from_id, METH_VARARGS, pyrna_struct_path_from_id_doc},
    {"type_recast", (PyCFunction)pyrna_struct_type_recast, METH_NOARGS, pyrna_struct_type_recast_doc},
    {"__dir__", (PyCFunction)pyrna_struct_dir, METH_NOARGS, NULL},
    {"callback_add", (PyCFunction)pyrna_callback_add, METH_VARARGS, NULL},
    {"callback_remove", (PyCFunction)pyrna_callback_remove, METH_VARARGS, NULL},
    {NULL, NULL, 0, NULL}
}
Definition at line 4546 of file bpy_rna.c.
PyTypeObject pyrna_struct_Type
Definition at line 5282 of file bpy_rna.c.
Referenced by pyrna_struct_new().
short rna_disallow_writes = FALSE [static]
Definition at line 313 of file bpy_rna.c.
Referenced by bpy_class_call(), and pyrna_write_check().
PointerRNA* rna_module_ptr = NULL [static]
Definition at line 6293 of file bpy_rna.c.