Blender: CamerasExporter Class Reference
CamerasExporter Class Reference
#include <CameraExporter.h>
Public Member Functions
CamerasExporter (COLLADASW::StreamWriter *sw, const ExportSettings *export_settings)
void exportCameras (Scene *sce)
void operator() (Object *ob, Scene *sce)
Detailed Description
Definition at line 39 of file CameraExporter.h.
Constructor & Destructor Documentation
CamerasExporter::CamerasExporter (COLLADASW::StreamWriter * sw, const ExportSettings * export_settings)
Definition at line 40 of file CameraExporter.cpp.
Member Function Documentation
void CamerasExporter::exportCameras (Scene * sce)
Definition at line 57 of file CameraExporter.cpp.
References forEachCameraObjectInScene(), and ExportSettings::selected.
Referenced by DocumentExporter::exportCurrentScene().
void CamerasExporter::operator() (Object * ob, Scene * sce)
Definition at line 65 of file CameraExporter.cpp.
References CAM_PERSP, Camera::clipend, Camera::clipsta, Object::data, focallength_to_fov(), get_camera_id(), id_name(), Camera::lens, Camera::ortho_scale, Scene::r, RAD2DEGF, Camera::sensor_x, Camera::type, RenderData::xsch, and RenderData::ysch.
The documentation for this class was generated from the following files:
CameraExporter.h
CameraExporter.cpp