Blender: node_header.c File Reference
node_header.c File Reference
node editor
#include <string.h>
#include <stdio.h>
#include "DNA_space_types.h"
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_interface_icons.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "node_intern.h"
Functions
static void do_node_add (bContext *C, bNodeTemplate *ntemp)
static void do_node_add_static (bContext *C, void *UNUSED(arg), int event)
static void do_node_add_group (bContext *C, void *UNUSED(arg), int event)
static int node_tree_has_type (int treetype, int nodetype)
static void node_add_menu (bContext *C, uiLayout *layout, void *arg_nodeclass)
static void node_menu_add_foreach_cb (void *calldata, int nclass, const char *name)
static void node_menu_add (const bContext *C, Menu *menu)
void node_menus_register (void)
Detailed Description
Definition in file node_header.c.
Function Documentation
static void do_node_add (bContext * C, bNodeTemplate * ntemp) [static]
Definition at line 68 of file node_header.c.
References CTX_data_main(), CTX_data_scene(), CTX_wm_area(), CTX_wm_space_node(), CTX_wm_window(), SpaceNode::edittree, wmWindow::eventstate, ListBase::first, bNode::flag, SpaceNode::mx, SpaceNode::my, bNode::next, ARegion::next, node_add_node(), NODE_SELECT, NODE_TEST, bNodeTree::nodes, ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_WINDOW, snode_dag_update(), snode_notify(), UI_view2d_region_to_view(), ARegion::v2d, ARegion::winrct, wmEvent::x, rcti::xmin, wmEvent::y, and rcti::ymin.
Referenced by do_node_add_group(), and do_node_add_static().
static void do_node_add_group (bContext * C, void * UNUSEDarg, int event) [static]
Definition at line 124 of file node_header.c.
References BLI_findlink(), CTX_data_main(), CTX_data_scene(), CTX_wm_space_node(), do_node_add(), G, bNodeTemplate::main, bNodeTemplate::ngroup, NODE_FORLOOP, NODE_GROUP, NODE_WHILELOOP, bNodeTree::nodetype, ntreeAddTree(), NULL, bNodeTemplate::scene, SpaceNode::treetype, and bNodeTemplate::type.
Referenced by node_add_menu().
static void do_node_add_static (bContext * C, void * UNUSEDarg, int event) [static]
Definition at line 111 of file node_header.c.
References CTX_data_main(), CTX_data_scene(), do_node_add(), bNodeTemplate::main, bNodeTemplate::scene, and bNodeTemplate::type.
Referenced by node_add_menu().
static void node_add_menu (bContext * C, uiLayout * layout, void * arg_nodeclass) [static]
Definition at line 187 of file node_header.c.
References bNodeType::compatibility, CTX_data_main(), CTX_data_scene(), CTX_wm_space_node(), do_node_add_group(), do_node_add_static(), ELEM3, ListBase::first, GET_INT_FROM_POINTER, bNodeTree::id, IFACE_, bNodeType::name, ID::name, bNodeType::nclass, bNodeType::next, ID::next, NODE_CLASS_GROUP, NODE_DYNAMIC, NODE_FORLOOP, NODE_GROUP, NODE_NEW_SHADING, NODE_OLD_SHADING, node_tree_has_type(), bNodeTreeType::node_types, NODE_WHILELOOP, Main::nodetree, SpaceNode::nodetree, bNodeTree::nodetype, NTREE_SHADER, ntreeGetType(), NULL, scene_use_new_shading_nodes(), bNodeType::type, bNodeTree::type, uiItemS(), uiItemV(), and uiLayoutSetFunc().
Referenced by node_menu_add_foreach_cb().
static void node_menu_add (const bContext * C, Menu * menu) [static]
Definition at line 253 of file node_header.c.
References CTX_data_scene(), CTX_wm_space_node(), bNodeTreeType::foreach_nodeclass, Menu::layout, node_menu_add_foreach_cb(), SpaceNode::nodetree, ntreeGetType(), SpaceNode::treetype, and uiLayoutSetActive().
Referenced by node_menus_register().
static void node_menu_add_foreach_cb (void * calldata, int nclass, const char * name) [static]
Definition at line 247 of file node_header.c.
References IFACE_, node_add_menu(), SET_INT_IN_POINTER, and uiItemMenuF().
Referenced by node_menu_add().
void node_menus_register (void)
Definition at line 267 of file node_header.c.
References MenuType::draw, MenuType::idname, MenuType::label, MEM_callocN(), mt, node_menu_add(), and WM_menutype_add().
Referenced by ED_spacetype_node().
static int node_tree_has_type (int treetype, int nodetype) [static]
Definition at line 176 of file node_header.c.
References ListBase::first, bNodeType::next, bNodeTreeType::node_types, ntreeGetType(), and bNodeType::type.
Referenced by node_add_menu().