Blender: ED_anim_api.h File Reference
ED_anim_api.h File Reference
Editors
Classes
struct bAnimContext
struct bAnimListElem
struct bAnimChannelType
Defines
#define SEL_SCEC(sce) ((sce->flag & SCE_DS_SELECTED))
#define EXPANDED_SCEC(sce) ((sce->flag & SCE_DS_COLLAPSED)==0)
#define FILTER_WOR_SCED(wo) ((wo->flag & WO_DS_EXPAND))
#define SEL_OBJC(base) ((base->flag & SELECT))
#define EXPANDED_OBJC(ob) ((ob->nlaflag & OB_ADS_COLLAPSED)==0)
#define FILTER_SKE_OBJD(key) ((key->flag & KEY_DS_EXPAND))
#define FILTER_MAT_OBJD(ma) ((ma->flag & MA_DS_EXPAND))
#define FILTER_LAM_OBJD(la) ((la->flag & LA_DS_EXPAND))
#define FILTER_CAM_OBJD(ca) ((ca->flag & CAM_DS_EXPAND))
#define FILTER_CUR_OBJD(cu) ((cu->flag & CU_DS_EXPAND))
#define FILTER_PART_OBJD(part) ((part->flag & PART_DS_EXPAND))
#define FILTER_MBALL_OBJD(mb) ((mb->flag2 & MB_DS_EXPAND))
#define FILTER_ARM_OBJD(arm) ((arm->flag & ARM_DS_EXPAND))
#define FILTER_MESH_OBJD(me) ((me->flag & ME_DS_EXPAND))
#define FILTER_LATTICE_OBJD(lt) ((lt->flag & LT_DS_EXPAND))
#define FILTER_SPK_OBJD(spk) ((spk->flag & SPK_DS_EXPAND))
#define FILTER_NTREE_DATA(ntree) ((ntree->flag & NTREE_DS_EXPAND))
#define FILTER_TEX_DATA(tex) ((tex->flag & TEX_DS_EXPAND))
#define SEL_ACTC(actc) ((actc->flag & ACT_SELECTED))
#define EXPANDED_ACTC(actc) ((actc->flag & ACT_COLLAPSED)==0)
#define EXPANDED_DRVD(adt) ((adt->flag & ADT_DRIVERS_COLLAPSED)==0)
#define EDITABLE_AGRP(agrp) ((agrp->flag & AGRP_PROTECTED)==0)
#define EXPANDED_AGRP(ac, agrp)
#define SEL_AGRP(agrp) ((agrp->flag & AGRP_SELECTED) || (agrp->flag & AGRP_ACTIVE))
#define EDITABLE_FCU(fcu) ((fcu->flag & FCURVE_PROTECTED)==0)
#define SEL_FCU(fcu) (fcu->flag & FCURVE_SELECTED)
#define EDITABLE_SHAPEKEY(kb) ((kb->flag & KEYBLOCK_LOCKED)==0)
#define SEL_SHAPEKEY(kb) (kb->flag & KEYBLOCK_SEL)
#define EXPANDED_GPD(gpd) (gpd->flag & GP_DATA_EXPAND)
#define EDITABLE_GPL(gpl) ((gpl->flag & GP_LAYER_LOCKED)==0)
#define SEL_GPL(gpl) (gpl->flag & GP_LAYER_SELECT)
#define SEL_NLT(nlt) (nlt->flag & NLATRACK_SELECTED)
#define EDITABLE_NLT(nlt) ((nlt->flag & NLATRACK_PROTECTED)==0)
#define ACHANNEL_FIRST -16
#define ACHANNEL_HEIGHT 16
#define ACHANNEL_HEIGHT_HALF 8
#define ACHANNEL_SKIP 2
#define ACHANNEL_STEP (ACHANNEL_HEIGHT + ACHANNEL_SKIP)
#define ACHANNEL_NAMEWIDTH 200
#define ACHANNEL_BUTTON_WIDTH 16
#define NLACHANNEL_FIRST -16
#define NLACHANNEL_HEIGHT(snla) ((snla && (snla->flag & SNLA_NOSTRIPCURVES)) ? 16 : 24)
#define NLACHANNEL_HEIGHT_HALF(snla) ((snla && (snla->flag & SNLA_NOSTRIPCURVES)) ? 8 : 12)
#define NLACHANNEL_SKIP 2
#define NLACHANNEL_STEP(snla) (NLACHANNEL_HEIGHT(snla) + NLACHANNEL_SKIP)
#define NLACHANNEL_NAMEWIDTH 200
#define NLACHANNEL_BUTTON_WIDTH 16
#define BEZKEYTYPE(bezt) ((bezt)->hide)
#define ACHANNEL_SET_FLAG(channel, smode, sflag)
#define ACHANNEL_SET_FLAG_NEG(channel, smode, sflag)
Typedefs
typedef struct bAnimContext bAnimContext
typedef enum eAnimCont_Types eAnimCont_Types
typedef struct bAnimListElem bAnimListElem
typedef enum eAnim_ChannelType eAnim_ChannelType
typedef enum eAnim_KeyType eAnim_KeyType
typedef enum eAnimFilter_Flags eAnimFilter_Flags
typedef enum eAnimChannels_SetFlag eAnimChannels_SetFlag
typedef enum eAnimChannel_Settings eAnimChannel_Settings
typedef struct bAnimChannelType bAnimChannelType
typedef enum eAnimUnitConv_Flags eAnimUnitConv_Flags
Enumerations
enum eAnimCont_Types {
ANIMCONT_NONE = 0, ANIMCONT_ACTION, ANIMCONT_SHAPEKEY, ANIMCONT_GPENCIL,
ANIMCONT_DOPESHEET, ANIMCONT_FCURVES, ANIMCONT_DRIVERS, ANIMCONT_NLA,
ANIMCONT_CHANNEL
}
enum eAnim_ChannelType {
ANIMTYPE_NONE = 0, ANIMTYPE_ANIMDATA, ANIMTYPE_SPECIALDATA, ANIMTYPE_SUMMARY,
ANIMTYPE_SCENE, ANIMTYPE_OBJECT, ANIMTYPE_GROUP, ANIMTYPE_FCURVE,
ANIMTYPE_FILLACTD, ANIMTYPE_FILLDRIVERS, ANIMTYPE_DSMAT, ANIMTYPE_DSLAM,
ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSSKEY, ANIMTYPE_DSWOR,
ANIMTYPE_DSNTREE, ANIMTYPE_DSPART, ANIMTYPE_DSMBALL, ANIMTYPE_DSARM,
ANIMTYPE_DSMESH, ANIMTYPE_DSTEX, ANIMTYPE_DSLAT, ANIMTYPE_DSSPK,
ANIMTYPE_SHAPEKEY, ANIMTYPE_GPDATABLOCK, ANIMTYPE_GPLAYER, ANIMTYPE_NLATRACK,
ANIMTYPE_NLAACTION, ANIMTYPE_NUM_TYPES
}
enum eAnim_KeyType {
ALE_NONE = 0, ALE_FCURVE, ALE_GPFRAME, ALE_NLASTRIP,
ALE_ALL, ALE_SCE, ALE_OB, ALE_ACT,
ALE_GROUP
}
enum eAnimFilter_Flags {
ANIMFILTER_DATA_VISIBLE = (1<<0), ANIMFILTER_LIST_VISIBLE = (1<<1), ANIMFILTER_CURVE_VISIBLE = (1<<2), ANIMFILTER_LIST_CHANNELS = (1<<3),
ANIMFILTER_ACTIVE = (1<<4), ANIMFILTER_ACTGROUPED = (1<<5), ANIMFILTER_SEL = (1<<6), ANIMFILTER_UNSEL = (1<<7),
ANIMFILTER_FOREDIT = (1<<8), ANIMFILTER_SELEDIT = (1<<9), ANIMFILTER_ANIMDATA = (1<<10), ANIMFILTER_NODUPLIS = (1<<11),
ANIMFILTER_TMP_PEEK = (1<<30)
}
enum eAnimChannels_SetFlag { ACHANNEL_SETFLAG_CLEAR = 0, ACHANNEL_SETFLAG_ADD, ACHANNEL_SETFLAG_INVERT, ACHANNEL_SETFLAG_TOGGLE }
enum eAnimChannel_Settings {
ACHANNEL_SETTING_SELECT = 0, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_EXPAND,
ACHANNEL_SETTING_VISIBLE, ACHANNEL_SETTING_SOLO
}
enum { DRAWCFRA_PLAIN = 0, DRAWCFRA_SHOW_NUMBOX = (1<<0), DRAWCFRA_UNIT_SECONDS = (1<<1), DRAWCFRA_WIDE = (1<<2) }
enum eAnimUnitConv_Flags { ANIM_UNITCONV_RESTORE = (1<<0), ANIM_UNITCONV_ONLYKEYS = (1<<1), ANIM_UNITCONV_ONLYSEL = (1<<2), ANIM_UNITCONV_SELVERTS = (1<<3) }
Functions
size_t ANIM_animdata_filter (bAnimContext *ac, ListBase *anim_data, int filter_mode, void *data, short datatype)
short ANIM_animdata_get_context (const struct bContext *C, bAnimContext *ac)
short ANIM_animdata_context_getdata (bAnimContext *ac)
bAnimChannelType * ANIM_channel_get_typeinfo (bAnimListElem *ale)
void ANIM_channel_debug_print_info (bAnimListElem *ale, short indent_level)
void ANIM_channel_draw (bAnimContext *ac, bAnimListElem *ale, float yminc, float ymaxc)
void ANIM_channel_draw_widgets (struct bContext *C, bAnimContext *ac, bAnimListElem *ale, struct uiBlock *block, float yminc, float ymaxc, size_t channel_index)
short ANIM_channel_setting_get (bAnimContext *ac, bAnimListElem *ale, int setting)
void ANIM_channel_setting_set (bAnimContext *ac, bAnimListElem *ale, int setting, short mode)
void ANIM_flush_setting_anim_channels (bAnimContext *ac, ListBase *anim_data, bAnimListElem *ale_setting, int setting, short on)
void ANIM_deselect_anim_channels (bAnimContext *ac, void *data, short datatype, short test, short sel)
void ANIM_set_active_channel (bAnimContext *ac, void *data, short datatype, int filter, void *channel_data, short channel_type)
void ANIM_fcurve_delete_from_animdata (bAnimContext *ac, struct AnimData *adt, struct FCurve *fcu)
void ANIM_timecode_string_from_frame (char *str, struct Scene *scene, int power, short timecodes, float cfra)
void ANIM_draw_cfra (const struct bContext *C, struct View2D *v2d, short flag)
void ANIM_draw_previewrange (const struct bContext *C, struct View2D *v2d)
void ANIM_uiTemplate_fmodifier_draw (struct uiLayout *layout, struct ID *id, ListBase *modifiers, struct FModifier *fcm)
void free_fmodifiers_copybuf (void)
short ANIM_fmodifiers_copy_to_buf (ListBase *modifiers, short active)
short ANIM_fmodifiers_paste_from_buf (ListBase *modifiers, short replace)
int getname_anim_fcurve (char *name, struct ID *id, struct FCurve *fcu)
void getcolor_fcurve_rainbow (int cur, int tot, float *out)
struct AnimData * ANIM_nla_mapping_get (bAnimContext *ac, bAnimListElem *ale)
void ANIM_nla_mapping_apply_fcurve (struct AnimData *adt, struct FCurve *fcu, short restore, short only_keys)
void ED_nla_postop_refresh (bAnimContext *ac)
float ANIM_unit_mapping_get_factor (struct Scene *scene, struct ID *id, struct FCurve *fcu, short restore)
void ANIM_unit_mapping_apply_fcurve (struct Scene *scene, struct ID *id, struct FCurve *fcu, short flag)
void ANIM_id_update (struct Scene *scene, struct ID *id)
void ANIM_list_elem_update (struct Scene *scene, bAnimListElem *ale)
void ANIM_sync_animchannels_to_data (const struct bContext *C)
void ED_operatortypes_animchannels (void)
void ED_keymap_animchannels (struct wmKeyConfig *keyconf)
void ED_operatortypes_anim (void)
void ED_keymap_anim (struct wmKeyConfig *keyconf)
void ED_operatormacros_graph (void)
void ED_operatormacros_action (void)
Variables
enum { ... } eAnimEditDraw_CurrentFrame
Detailed Description
Definition in file ED_anim_api.h.
Define Documentation
#define ACHANNEL_BUTTON_WIDTH 16
Definition at line 299 of file ED_anim_api.h.
Referenced by ANIM_channel_draw(), and ANIM_channel_draw_widgets().
#define ACHANNEL_FIRST -16
Definition at line 289 of file ED_anim_api.h.
Referenced by draw_channel_names(), and graph_draw_channel_names().
#define ACHANNEL_HEIGHT 16
Definition at line 290 of file ED_anim_api.h.
Referenced by borderselect_anim_channels(), draw_channel_names(), draw_channel_strips(), and graph_draw_channel_names().
#define ACHANNEL_HEIGHT_HALF 8
Definition at line 291 of file ED_anim_api.h.
Referenced by animchannels_mouseclick_invoke(), animchannels_rename_invoke(), borderselect_action(), draw_channel_names(), draw_channel_strips(), graph_draw_channel_names(), and mouse_action_keys().
#define ACHANNEL_NAMEWIDTH 200
Definition at line 296 of file ED_anim_api.h.
Referenced by animchannels_mouseclick_invoke(), and animchannels_rename_invoke().
#define ACHANNEL_SET_FLAG (channel, smode, sflag)
Value:
{ \
        if (smode == ACHANNEL_SETFLAG_INVERT)   (channel)->flag ^= (sflag); \
        else if (smode == ACHANNEL_SETFLAG_ADD) (channel)->flag |= (sflag); \
        else                                    (channel)->flag &= ~(sflag); \
    }
Definition at line 562 of file ED_anim_api.h.
Referenced by ANIM_deselect_anim_channels(), ANIM_set_active_channel(), borderselect_anim_channels(), borderselect_nla_strips(), deselect_nla_strips(), mouse_nla_strips(), and nlaedit_select_leftright().
#define ACHANNEL_SET_FLAG_NEG (channel, smode, sflag)
Value:
{ \
        if (smode == ACHANNEL_SETFLAG_INVERT)   (channel)->flag ^= (sflag); \
        else if (smode == ACHANNEL_SETFLAG_ADD) (channel)->flag &= ~(sflag); \
        else                                    (channel)->flag |= (sflag); \
    }
Definition at line 574 of file ED_anim_api.h.
#define ACHANNEL_SKIP 2
Definition at line 292 of file ED_anim_api.h.
#define ACHANNEL_STEP (ACHANNEL_HEIGHT + ACHANNEL_SKIP)
Definition at line 293 of file ED_anim_api.h.
Referenced by animchannels_mouseclick_invoke(), animchannels_rename_invoke(), borderselect_action(), borderselect_anim_channels(), draw_channel_names(), draw_channel_strips(), graph_draw_channel_names(), and mouse_action_keys().
#define BEZKEYTYPE (bezt) ((bezt)->hide)
Definition at line 555 of file ED_anim_api.h.
Referenced by nalloc_ak_bezt(), nupdate_ak_bezt(), sample_fcurve(), set_keytype_breakdown(), set_keytype_extreme(), set_keytype_jitter(), and set_keytype_keyframe().
#define EDITABLE_AGRP (agrp) ((agrp->flag & AGRP_PROTECTED)==0)
Definition at line 262 of file ED_anim_api.h.
Referenced by animfilter_act_group().
#define EDITABLE_FCU (fcu) ((fcu->flag & FCURVE_PROTECTED)==0)
Definition at line 268 of file ED_anim_api.h.
Referenced by animfilter_fcurve_next().
#define EDITABLE_GPL (gpl) ((gpl->flag & GP_LAYER_LOCKED)==0)
Definition at line 279 of file ED_anim_api.h.
Referenced by animdata_filter_gpencil_data().
#define EDITABLE_NLT (nlt) ((nlt->flag & NLATRACK_PROTECTED)==0)
Definition at line 284 of file ED_anim_api.h.
Referenced by draw_nla_channel_list_gl().
#define EDITABLE_SHAPEKEY (kb) ((kb->flag & KEYBLOCK_LOCKED)==0)
Definition at line 272 of file ED_anim_api.h.
Referenced by animdata_filter_shapekey().
#define EXPANDED_ACTC (actc) ((actc->flag & ACT_COLLAPSED)==0)
Definition at line 255 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obanim(), and animdata_filter_ds_scene().
#define EXPANDED_AGRP (ac, agrp)
Value:
(((!(ac) || ((ac)->spacetype != SPACE_IPO)) && (agrp->flag & AGRP_EXPANDED)) || \
      (( (ac) && ((ac)->spacetype == SPACE_IPO)) && (agrp->flag & AGRP_EXPANDED_G)) )
Definition at line 263 of file ED_anim_api.h.
Referenced by animfilter_act_group(), and rearrange_action_channels().
#define EXPANDED_DRVD (adt) ((adt->flag & ADT_DRIVERS_COLLAPSED)==0)
Definition at line 257 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obanim(), animdata_filter_ds_scene(), and rearrange_driver_channels().
#define EXPANDED_GPD (gpd) (gpd->flag & GP_DATA_EXPAND)
Definition at line 277 of file ED_anim_api.h.
Referenced by animdata_filter_gpencil().
#define EXPANDED_OBJC (ob) ((ob->nlaflag & OB_ADS_COLLAPSED)==0)
Definition at line 236 of file ED_anim_api.h.
Referenced by animdata_filter_dopesheet_ob().
#define EXPANDED_SCEC (sce) ((sce->flag & SCE_DS_COLLAPSED)==0)
Definition at line 231 of file ED_anim_api.h.
Referenced by animdata_filter_dopesheet_scene().
#define FILTER_ARM_OBJD (arm) ((arm->flag & ARM_DS_EXPAND))
Definition at line 245 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata(), and make_new_animlistelem().
#define FILTER_CAM_OBJD (ca) ((ca->flag & CAM_DS_EXPAND))
Definition at line 241 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata(), and make_new_animlistelem().
#define FILTER_CUR_OBJD (cu) ((cu->flag & CU_DS_EXPAND))
Definition at line 242 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata(), and make_new_animlistelem().
#define FILTER_LAM_OBJD (la) ((la->flag & LA_DS_EXPAND))
Definition at line 240 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata(), and make_new_animlistelem().
#define FILTER_LATTICE_OBJD (lt) ((lt->flag & LT_DS_EXPAND))
Definition at line 247 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata(), and make_new_animlistelem().
#define FILTER_MAT_OBJD (ma) ((ma->flag & MA_DS_EXPAND))
Definition at line 239 of file ED_anim_api.h.
Referenced by animdata_filter_ds_materials(), and make_new_animlistelem().
#define FILTER_MBALL_OBJD (mb) ((mb->flag2 & MB_DS_EXPAND))
Definition at line 244 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata().
#define FILTER_MESH_OBJD (me) ((me->flag & ME_DS_EXPAND))
Definition at line 246 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata(), and make_new_animlistelem().
#define FILTER_NTREE_DATA (ntree) ((ntree->flag & NTREE_DS_EXPAND))
Definition at line 250 of file ED_anim_api.h.
Referenced by animdata_filter_ds_nodetree(), and make_new_animlistelem().
#define FILTER_PART_OBJD (part) ((part->flag & PART_DS_EXPAND))
Definition at line 243 of file ED_anim_api.h.
Referenced by animdata_filter_ds_particles(), and make_new_animlistelem().
#define FILTER_SKE_OBJD (key) ((key->flag & KEY_DS_EXPAND))
Definition at line 238 of file ED_anim_api.h.
Referenced by animdata_filter_ds_keyanim(), and make_new_animlistelem().
#define FILTER_SPK_OBJD (spk) ((spk->flag & SPK_DS_EXPAND))
Definition at line 248 of file ED_anim_api.h.
Referenced by animdata_filter_ds_obdata(), and make_new_animlistelem().
#define FILTER_TEX_DATA (tex) ((tex->flag & TEX_DS_EXPAND))
Definition at line 251 of file ED_anim_api.h.
Referenced by animdata_filter_ds_textures(), and make_new_animlistelem().
#define FILTER_WOR_SCED (wo) ((wo->flag & WO_DS_EXPAND))
Definition at line 233 of file ED_anim_api.h.
Referenced by animdata_filter_ds_world(), and make_new_animlistelem().
#define NLACHANNEL_BUTTON_WIDTH 16
Definition at line 316 of file ED_anim_api.h.
Referenced by mouse_nla_channels().
#define NLACHANNEL_FIRST -16
Definition at line 306 of file ED_anim_api.h.
#define NLACHANNEL_HEIGHT (snla) ((snla && (snla->flag & SNLA_NOSTRIPCURVES)) ? 16 : 24)
Definition at line 307 of file ED_anim_api.h.
Referenced by borderselect_anim_channels(), draw_nla_channel_list(), and draw_nla_main_data().
#define NLACHANNEL_HEIGHT_HALF (snla) ((snla && (snla->flag & SNLA_NOSTRIPCURVES)) ? 8 : 12)
Definition at line 308 of file ED_anim_api.h.
Referenced by animchannels_rename_invoke(), draw_nla_channel_list(), draw_nla_channel_list_gl(), draw_nla_main_data(), mouse_nla_strips(), and nlachannels_mouseclick_invoke().
#define NLACHANNEL_NAMEWIDTH 200
Definition at line 313 of file ED_anim_api.h.
Referenced by animchannels_rename_invoke(), and nlachannels_mouseclick_invoke().
#define NLACHANNEL_SKIP 2
Definition at line 309 of file ED_anim_api.h.
Referenced by draw_nla_channel_list_gl(), and draw_nla_main_data().
#define NLACHANNEL_STEP (snla) (NLACHANNEL_HEIGHT(snla) + NLACHANNEL_SKIP)
Definition at line 310 of file ED_anim_api.h.
Referenced by animchannels_rename_invoke(), borderselect_anim_channels(), borderselect_nla_strips(), createTransNlaData(), draw_nla_channel_list(), draw_nla_channel_list_gl(), draw_nla_main_data(), mouse_nla_strips(), nlachannels_mouseclick_invoke(), and recalcData_nla().
#define SEL_ACTC (actc) ((actc->flag & ACT_SELECTED))
Definition at line 254 of file ED_anim_api.h.
#define SEL_AGRP (agrp) ((agrp->flag & AGRP_SELECTED) || (agrp->flag & AGRP_ACTIVE))
Definition at line 266 of file ED_anim_api.h.
Referenced by animfilter_act_group(), and rearrange_animchannel_add_to_islands().
#define SEL_FCU (fcu) (fcu->flag & FCURVE_SELECTED)
Definition at line 269 of file ED_anim_api.h.
Referenced by animfilter_fcurve_next(), and rearrange_animchannel_add_to_islands().
#define SEL_GPL (gpl) (gpl->flag & GP_LAYER_SELECT)
Definition at line 280 of file ED_anim_api.h.
Referenced by animdata_filter_gpencil_data().
#define SEL_NLT (nlt) (nlt->flag & NLATRACK_SELECTED)
Definition at line 283 of file ED_anim_api.h.
Referenced by draw_nla_channel_list_gl(), and rearrange_animchannel_add_to_islands().
#define SEL_OBJC (base) ((base->flag & SELECT))
Definition at line 235 of file ED_anim_api.h.
#define SEL_SCEC (sce) ((sce->flag & SCE_DS_SELECTED))
Definition at line 230 of file ED_anim_api.h.
#define SEL_SHAPEKEY (kb) (kb->flag & KEYBLOCK_SEL)
Definition at line 273 of file ED_anim_api.h.
Referenced by animdata_filter_shapekey().
Typedef Documentation
typedef struct bAnimChannelType bAnimChannelType
typedef struct bAnimContext bAnimContext
typedef struct bAnimListElem bAnimListElem
typedef enum eAnim_ChannelType eAnim_ChannelType
typedef enum eAnim_KeyType eAnim_KeyType
typedef enum eAnimChannel_Settings eAnimChannel_Settings
typedef enum eAnimChannels_SetFlag eAnimChannels_SetFlag
typedef enum eAnimCont_Types eAnimCont_Types
typedef enum eAnimFilter_Flags eAnimFilter_Flags
typedef enum eAnimUnitConv_Flags eAnimUnitConv_Flags
Enumeration Type Documentation
anonymous enum
Enumerator:
DRAWCFRA_PLAIN
DRAWCFRA_SHOW_NUMBOX
DRAWCFRA_UNIT_SECONDS
DRAWCFRA_WIDE
Definition at line 458 of file ED_anim_api.h.
enum eAnim_ChannelType
Enumerator:
ANIMTYPE_NONE
ANIMTYPE_ANIMDATA
ANIMTYPE_SPECIALDATA
ANIMTYPE_SUMMARY
ANIMTYPE_SCENE
ANIMTYPE_OBJECT
ANIMTYPE_GROUP
ANIMTYPE_FCURVE
ANIMTYPE_FILLACTD
ANIMTYPE_FILLDRIVERS
ANIMTYPE_DSMAT
ANIMTYPE_DSLAM
ANIMTYPE_DSCAM
ANIMTYPE_DSCUR
ANIMTYPE_DSSKEY
ANIMTYPE_DSWOR
ANIMTYPE_DSNTREE
ANIMTYPE_DSPART
ANIMTYPE_DSMBALL
ANIMTYPE_DSARM
ANIMTYPE_DSMESH
ANIMTYPE_DSTEX
ANIMTYPE_DSLAT
ANIMTYPE_DSSPK
ANIMTYPE_SHAPEKEY
ANIMTYPE_GPDATABLOCK
ANIMTYPE_GPLAYER
ANIMTYPE_NLATRACK
ANIMTYPE_NLAACTION
ANIMTYPE_NUM_TYPES
Definition at line 129 of file ED_anim_api.h.
enum eAnim_KeyType
Enumerator:
ALE_NONE
ALE_FCURVE
ALE_GPFRAME
ALE_NLASTRIP
ALE_ALL
ALE_SCE
ALE_OB
ALE_ACT
ALE_GROUP
Definition at line 172 of file ED_anim_api.h.
enum eAnimChannel_Settings
Enumerator:
ACHANNEL_SETTING_SELECT
ACHANNEL_SETTING_PROTECT
ACHANNEL_SETTING_MUTE
ACHANNEL_SETTING_EXPAND
ACHANNEL_SETTING_VISIBLE
ACHANNEL_SETTING_SOLO
Definition at line 351 of file ED_anim_api.h.
enum eAnimChannels_SetFlag
Enumerator:
ACHANNEL_SETFLAG_CLEAR
ACHANNEL_SETFLAG_ADD
ACHANNEL_SETFLAG_INVERT
ACHANNEL_SETFLAG_TOGGLE
Definition at line 343 of file ED_anim_api.h.
enum eAnimCont_Types
Enumerator:
ANIMCONT_NONE
ANIMCONT_ACTION
ANIMCONT_SHAPEKEY
ANIMCONT_GPENCIL
ANIMCONT_DOPESHEET
ANIMCONT_FCURVES
ANIMCONT_DRIVERS
ANIMCONT_NLA
ANIMCONT_CHANNEL
Definition at line 91 of file ED_anim_api.h.
enum eAnimFilter_Flags
Enumerator:
ANIMFILTER_DATA_VISIBLE
ANIMFILTER_LIST_VISIBLE
ANIMFILTER_CURVE_VISIBLE
ANIMFILTER_LIST_CHANNELS
ANIMFILTER_ACTIVE
ANIMFILTER_ACTGROUPED
ANIMFILTER_SEL
ANIMFILTER_UNSEL
ANIMFILTER_FOREDIT
ANIMFILTER_SELEDIT
ANIMFILTER_ANIMDATA
ANIMFILTER_NODUPLIS
ANIMFILTER_TMP_PEEK
Definition at line 188 of file ED_anim_api.h.
enum eAnimUnitConv_Flags
Enumerator:
ANIM_UNITCONV_RESTORE
ANIM_UNITCONV_ONLYKEYS
ANIM_UNITCONV_ONLYSEL
ANIM_UNITCONV_SELVERTS
Definition at line 533 of file ED_anim_api.h.
Function Documentation
short ANIM_animdata_context_getdata (bAnimContext * ac)
Definition at line 263 of file anim_filter.c.
References actedit_get_context(), bAnimContext::data, graphedit_get_context(), nlaedit_get_context(), bAnimContext::sl, SPACE_ACTION, SPACE_IPO, SPACE_NLA, and bAnimContext::spacetype.
Referenced by ANIM_animdata_get_context().
size_t ANIM_animdata_filter (bAnimContext * ac, ListBase * anim_data, int filter_mode, void * data, short datatype)
Definition at line 2208 of file anim_filter.c.
References bAnimContext::ads, SpaceAction::ads, ANIMCONT_ACTION, ANIMCONT_CHANNEL, ANIMCONT_DOPESHEET, ANIMCONT_DRIVERS, ANIMCONT_FCURVES, ANIMCONT_GPENCIL, ANIMCONT_NLA, ANIMCONT_SHAPEKEY, animdata_filter_animchan(), animdata_filter_dopesheet(), animdata_filter_dopesheet_summary(), animdata_filter_gpencil(), animdata_filter_remove_duplis(), animdata_filter_remove_invalid(), animdata_filter_shapekey(), animfilter_action(), ANIMFILTER_NODUPLIS, NULL, bAnimContext::obact, and bAnimContext::sl.
Referenced by achannel_setting_flush_widget_cb(), actkeys_framejump_exec(), actkeys_mselect_column(), actkeys_select_leftright(), actkeys_select_linked_exec(), ANIM_deselect_anim_channels(), ANIM_editkeyframes_refresh(), ANIM_set_active_channel(), ANIM_sync_animchannels_to_data(), animchannels_delete_exec(), animchannels_enable_exec(), animchannels_rearrange_exec(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), bake_graph_curves(), borderselect_action(), borderselect_anim_channels(), borderselect_graphkeys(), borderselect_nla_strips(), clean_action_keys(), clean_graph_keys(), columnselect_action_keys(), columnselect_graph_keys(), copy_action_keys(), copy_graph_keys(), createTransActionData(), createTransNlaData(), delete_action_keys(), delete_graph_keys(), deselect_action_keys(), deselect_nla_strips(), draw_channel_names(), draw_channel_strips(), draw_nla_channel_list(), draw_nla_main_data(), duplicate_action_keys(), duplicate_graph_keys(), ED_nla_postop_refresh(), get_active_fcurve_channel(), get_graph_keyframe_extents(), get_keyframe_extents(), get_nearest_fcurve_verts_list(), get_nlastrip_extents(), graph_draw_channel_names(), graph_draw_curves(), graph_fmodifier_add_exec(), graph_fmodifier_paste_exec(), graph_refresh(), graphkeys_euler_filter_exec(), graphkeys_framejump_exec(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), graphkeys_smooth_exec(), graphop_editable_keyframes_poll(), graphop_selected_fcurve_poll(), graphop_visible_keyframes_poll(), insert_action_keys(), insert_graph_keys(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), mouse_action_keys(), mouse_anim_channels(), mouse_nla_channels(), mouse_nla_strips(), nla_fmodifier_add_exec(), nla_fmodifier_copy_exec(), nla_fmodifier_paste_exec(), nla_panel_context(), nlaedit_add_actionclip_exec(), nlaedit_add_meta_exec(), nlaedit_add_sound_exec(), nlaedit_add_tracks_exec(), nlaedit_add_transition_exec(), nlaedit_apply_scale_exec(), nlaedit_bake_exec(), nlaedit_clear_scale_exec(), nlaedit_delete_exec(), nlaedit_delete_tracks_exec(), nlaedit_disable_tweakmode_exec(), nlaedit_duplicate_exec(), nlaedit_enable_tweakmode_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_remove_meta_exec(), nlaedit_select_leftright(), nlaedit_snap_exec(), nlaedit_split_exec(), nlaedit_swap_exec(), nlaedit_sync_actlen_exec(), nlaedit_toggle_mute_exec(), ob_keyframes_loop(), ob_to_keylist(), paste_action_keys(), paste_graph_keys(), posttrans_action_clean(), rename_anim_channels(), sample_action_keys(), sample_graph_keys(), scene_keyframes_loop(), scene_to_keylist(), select_moreless_action_keys(), select_moreless_graph_keys(), setexpo_action_keys(), setexpo_graph_keys(), setflag_anim_channels(), sethandles_action_keys(), sethandles_graph_keys(), setipo_action_keys(), setipo_graph_keys(), setkeytype_action_keys(), snap_action_keys(), snap_graph_keys(), special_aftertrans_update(), summary_keyframes_loop(), and summary_to_keylist().
short ANIM_animdata_get_context (const struct bContext * C, bAnimContext * ac)
void ANIM_channel_debug_print_info (bAnimListElem * ale, short indent_level)
Definition at line 2563 of file anim_channels_defines.c.
References ANIM_CHAN_NAME_SIZE, ANIM_channel_get_typeinfo(), BLI_strncpy(), bAnimChannelType::channel_type_name, bAnimChannelType::name, and bAnimListElem::type.
void ANIM_channel_draw (bAnimContext * ac, bAnimListElem * ale, float yminc, float ymaxc)
Definition at line 2725 of file anim_channels_defines.c.
References ACHANNEL_BUTTON_WIDTH, ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, ACHANNEL_SETTING_SELECT, ACHANNEL_SETTING_SOLO, ACHANNEL_SETTING_VISIBLE, ANIM_CHAN_NAME_SIZE, ANIM_channel_get_typeinfo(), ANIM_channel_setting_get(), ANIMTYPE_FCURVE, ANIMTYPE_SHAPEKEY, bAnimContext::ar, FCurve::color, View2D::cur, bAnimListElem::data, bAnimChannelType::draw_backdrop, ELEM, EXTRA_SCROLL_PAD, FCURVE_DISABLED, fdrawline(), SpaceIpo::flag, SpaceAction::flag, bAnimListElem::flag, bAnimChannelType::get_backdrop_color, bAnimChannelType::get_offset, bAnimChannelType::has_setting, bAnimChannelType::icon, ICON_WIDTH, View2D::mask, bAnimChannelType::name, NULL, SACTION_SLIDERS, SIPO_SLIDERS, bAnimContext::sl, SLIDER_WIDTH, SPACE_ACTION, SPACE_IPO, SPACE_NLA, bAnimContext::spacetype, TH_TEXT, TH_TEXT_HI, bAnimListElem::type, UI_DrawString(), UI_icon_draw(), UI_ThemeColor(), ARegion::v2d, rcti::xmax, rctf::xmax, and rcti::xmin.
Referenced by draw_channel_names(), draw_nla_channel_list_gl(), and graph_draw_channel_names().
void ANIM_channel_draw_widgets (struct bContext * C, bAnimContext * ac, bAnimListElem * ale, struct uiBlock * block, float yminc, float ymaxc, size_t channel_index)
Definition at line 3153 of file anim_channels_defines.c.
References ACHANNEL_BUTTON_WIDTH, ACHANNEL_SETTING_EXPAND, ACHANNEL_SETTING_MUTE, ACHANNEL_SETTING_PROTECT, achannel_setting_rename_done_cb(), achannel_setting_slider_cb(), achannel_setting_slider_shapekey_cb(), ACHANNEL_SETTING_SOLO, ACHANNEL_SETTING_VISIBLE, bAnimContext::ads, ANIM_channel_get_typeinfo(), ANIMTYPE_FCURVE, ANIMTYPE_SHAPEKEY, bAnimContext::ar, FCurve::array_index, View2D::cur, bAnimListElem::data, draw_setting_widget(), ELEM, ELEM3, SpaceIpo::flag, SpaceAction::flag, free_path(), bAnimChannelType::get_offset, bAnimChannelType::has_setting, bAnimChannelType::icon, ICON_WIDTH, bAnimListElem::id, key_get_curValue_rnaPath(), View2D::mask, MEM_freeN(), bAnimChannelType::name_prop, NULL, RENAME_TEXT_WIDTH, bDopeSheet::renameIndex, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), RNA_property_identifier(), SACTION_SLIDERS, SIPO_SLIDERS, bAnimContext::sl, SLIDER_WIDTH, SPACE_ACTION, SPACE_IPO, SPACE_NLA, bAnimContext::spacetype, TEX, bAnimListElem::type, UI_EMBOSS, UI_EMBOSSN, uiBlockSetEmboss(), uiButActiveOnly(), uiButSetFunc(), uiDefAutoButR(), uiDefButR(), ARegion::v2d, rctf::xmax, rcti::xmax, and rcti::xmin.
Referenced by draw_channel_names(), draw_nla_channel_list(), and graph_draw_channel_names().
bAnimChannelType* ANIM_channel_get_typeinfo (bAnimListElem * ale)
Definition at line 2544 of file anim_channels_defines.c.
References ANIM_init_channel_typeinfo_data(), ANIMTYPE_NUM_TYPES, NULL, and bAnimListElem::type.
Referenced by acf_generic_basic_offset(), acf_generic_channel_backdrop(), acf_generic_channel_color(), acf_generic_dataexpand_backdrop(), acf_generic_root_backdrop(), acf_group_backdrop(), acf_summary_backdrop(), ANIM_channel_debug_print_info(), ANIM_channel_draw(), ANIM_channel_draw_widgets(), ANIM_channel_setting_get(), ANIM_channel_setting_set(), ANIM_flush_setting_anim_channels(), draw_channel_strips(), rename_anim_channels(), and skip_fcurve_with_name().
short ANIM_channel_setting_get (bAnimContext * ac, bAnimListElem * ale, int setting)
Definition at line 2595 of file anim_channels_defines.c.
References ANIM_channel_get_typeinfo(), bAnimChannelType::has_setting, bAnimChannelType::setting_flag, and bAnimChannelType::setting_ptr.
Referenced by acf_generic_root_backdrop(), acf_group_backdrop(), achannel_setting_flush_widget_cb(), ANIM_channel_draw(), animchannels_visibility_toggle_exec(), draw_channel_strips(), and setflag_anim_channels().
void ANIM_channel_setting_set (bAnimContext * ac, bAnimListElem * ale, int setting, short mode)
Definition at line 2672 of file anim_channels_defines.c.
References ACF_SETTING_SET, ANIM_channel_get_typeinfo(), bAnimChannelType::has_setting, bAnimChannelType::setting_flag, and bAnimChannelType::setting_ptr.
Referenced by ANIM_flush_setting_anim_channels(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), borderselect_anim_channels(), and setflag_anim_channels().
void ANIM_deselect_anim_channels (bAnimContext * ac, void * data, short datatype, short test, short sel)
Definition at line 191 of file anim_channels_edit.c.
References ACHANNEL_SET_FLAG, ACHANNEL_SETFLAG_CLEAR, Scene::adt, bAnimListElem::adt, ADT_UI_ACTIVE, ADT_UI_SELECTED, AGRP_ACTIVE, AGRP_SELECTED, ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSMESH, ANIMTYPE_DSNTREE, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSTEX, ANIMTYPE_DSWOR, ANIMTYPE_FCURVE, ANIMTYPE_FILLACTD, ANIMTYPE_GPLAYER, ANIMTYPE_GROUP, ANIMTYPE_NLATRACK, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, ANIMTYPE_SHAPEKEY, BLI_freelistN(), bAnimListElem::data, FCURVE_ACTIVE, FCURVE_SELECTED, filter(), ListBase::first, NlaTrack::flag, FCurve::flag, bActionGroup::flag, AnimData::flag, bAnimListElem::flag, GP_LAYER_SELECT, KEYBLOCK_SEL, bAnimListElem::next, NLATRACK_ACTIVE, NLATRACK_SELECTED, NULL, Base::object, SCE_DS_SELECTED, SELECT, and bAnimListElem::type.
Referenced by animchannels_borderselect_exec(), animchannels_deselectall_exec(), mouse_action_keys(), mouse_anim_channels(), mouse_graph_keys(), mouse_nla_channels(), and mouse_nla_strips().
void ANIM_draw_cfra (const struct bContext * C, struct View2D * v2d, short flag)
void ANIM_draw_previewrange (const struct bContext * C, struct View2D * v2d)
void ANIM_fcurve_delete_from_animdata (bAnimContext * ac, struct AnimData * adt, struct FCurve * fcu)
Definition at line 507 of file anim_channels_edit.c.
References AnimData::action, action_groups_remove_channel(), ADT_NLA_EDIT_ON, ANIMCONT_DRIVERS, BLI_remlink(), bAction::curves, bAnimContext::datatype, AnimData::drivers, ELEM, ListBase::first, AnimData::flag, free_fcurve(), FCurve::grp, bAction::id, id_us_min(), and NULL.
Referenced by animchannels_delete_exec(), delete_action_keys(), delete_graph_keys(), and delete_keyframe().
void ANIM_flush_setting_anim_channels (bAnimContext * ac, ListBase * anim_data, bAnimListElem * ale_setting, int setting, short on)
Definition at line 375 of file anim_channels_edit.c.
References ACHANNEL_SETTING_VISIBLE, ANIM_channel_get_typeinfo(), ANIM_channel_setting_set(), bAnimListElem::data, ELEM, ListBase::first, bAnimChannelType::get_offset, bAnimListElem::id, bAnimListElem::next, NULL, bAnimListElem::prev, and bAnimListElem::type.
Referenced by achannel_setting_flush_widget_cb(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), and setflag_anim_channels().
short ANIM_fmodifiers_copy_to_buf (ListBase * modifiers, short active)
Definition at line 782 of file fmodifier_ui.c.
References BLI_addtail(), copy_fmodifier(), copy_fmodifiers(), ELEM, find_active_fmodifier(), ListBase::first, and NULL.
Referenced by graph_fmodifier_copy_exec(), and nla_fmodifier_copy_exec().
short ANIM_fmodifiers_paste_from_buf (ListBase * modifiers, short replace)
Definition at line 811 of file fmodifier_ui.c.
References BLI_addtail(), copy_fmodifier(), ListBase::first, FModifier::flag, FMODIFIER_FLAG_ACTIVE, free_fmodifiers(), FModifier::next, and NULL.
Referenced by graph_fmodifier_paste_exec(), and nla_fmodifier_paste_exec().
void ANIM_id_update (struct Scene * scene, struct ID * id)
void ANIM_list_elem_update (struct Scene * scene, bAnimListElem * ale)
Definition at line 64 of file anim_deps.c.
References ADT_RECALC_ANIM, ALE_FCURVE, BKE_animdata_from_id(), DAG_id_tag_update(), bAnimListElem::datatype, G, bAnimListElem::id, if(), bAnimListElem::key_data, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, AnimData::recalc, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), and RNA_property_update_main().
Referenced by animchannels_enable_exec().
void ANIM_nla_mapping_apply_fcurve (struct AnimData * adt, struct FCurve * fcu, short restore, short only_keys)
Definition at line 338 of file anim_draw.c.
References ANIM_fcurve_keyframes_loop(), bezt_nlamapping_apply(), bezt_nlamapping_restore(), KeyframeEditData::data, KeyframeEditData::i1, and NULL.
Referenced by actkeys_framejump_exec(), actkeys_select_leftright(), borderselect_graphkeys(), fcurve_to_keylist(), get_nearest_fcurve_verts_list(), graph_draw_curves(), graphkeys_framejump_exec(), graphkeys_select_leftright(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), posttrans_action_clean(), snap_action_keys(), snap_graph_keys(), and special_aftertrans_update().
struct AnimData* ANIM_nla_mapping_get (bAnimContext * ac, bAnimListElem * ale) [read]
Definition at line 279 of file anim_draw.c.
References bAnimListElem::adt, G, and NULL.
Referenced by actkeys_framejump_exec(), actkeys_mselect_column(), actkeys_select_leftright(), borderselect_action(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), createTransActionData(), draw_channel_strips(), get_graph_keyframe_extents(), get_keyframe_extents(), get_nearest_fcurve_verts_list(), graph_draw_curves(), graphkeys_click_insert_exec(), graphkeys_framejump_exec(), graphkeys_mselect_column(), graphkeys_select_leftright(), insert_action_keys(), insert_graph_keys(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), mouse_action_keys(), posttrans_action_clean(), snap_action_keys(), snap_graph_keys(), and special_aftertrans_update().
void ANIM_set_active_channel (bAnimContext * ac, void * data, short datatype, int filter, void * channel_data, short channel_type)
Definition at line 72 of file anim_channels_edit.c.
References ACHANNEL_SET_FLAG, ACHANNEL_SETFLAG_CLEAR, bAnimListElem::adt, ADT_UI_ACTIVE, AGRP_ACTIVE, ANIM_animdata_filter(), ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSLAT, ANIMTYPE_DSMAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSMESH, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSTEX, ANIMTYPE_DSWOR, ANIMTYPE_FCURVE, ANIMTYPE_FILLACTD, ANIMTYPE_GROUP, ANIMTYPE_NLATRACK, BLI_freelistN(), bAnimListElem::data, FCURVE_ACTIVE, ListBase::first, AnimData::flag, NlaTrack::flag, FCurve::flag, bActionGroup::flag, bAnimListElem::next, NLATRACK_ACTIVE, NULL, and bAnimListElem::type.
Referenced by mouse_action_keys(), mouse_anim_channels(), mouse_graph_keys(), mouse_nla_channels(), and mouse_nla_strips().
void ANIM_sync_animchannels_to_data (const struct bContext * C)
void ANIM_timecode_string_from_frame (char * str, struct Scene * scene, int power, short timecodes, float cfra)
Definition at line 66 of file anim_draw.c.
References FPS, TNT::seconds(), USER_TIMECODE_MILLISECONDS, USER_TIMECODE_MINIMAL, USER_TIMECODE_SECONDS_ONLY, USER_TIMECODE_SMPTE_FULL, and USER_TIMECODE_SMPTE_MSF.
Referenced by draw_cfra_number(), and scroll_printstr().
void ANIM_uiTemplate_fmodifier_draw (struct uiLayout * layout, struct ID * id, ListBase * modifiers, struct FModifier * fcm)
Definition at line 628 of file fmodifier_ui.c.
References B_REDR, BUT, delete_fmodifier_cb(), draw_modifier__cycles(), draw_modifier__envelope(), draw_modifier__fn_generator(), draw_modifier__generator(), draw_modifier__limits(), draw_modifier__noise(), draw_modifier__stepped(), FModifier::flag, FMODIFIER_FLAG_EXPANDED, FMODIFIER_FLAG_RANGERESTRICT, FMODIFIER_FLAG_USEINFLUENCE, fmodifier_get_typeinfo(), FMODIFIER_TYPE_CYCLES, FMODIFIER_TYPE_ENVELOPE, FMODIFIER_TYPE_FN_GENERATOR, FMODIFIER_TYPE_GENERATOR, FMODIFIER_TYPE_LIMITS, FMODIFIER_TYPE_NOISE, FMODIFIER_TYPE_STEPPED, IFACE_, FModifierTypeInfo::name, NULL, RNA_FModifier, RNA_pointer_create(), TIP_, FModifier::type, UI_EMBOSS, UI_EMBOSSN, UI_ITEM_R_ICON_ONLY, UI_LAYOUT_ALIGN_LEFT, UI_LAYOUT_ALIGN_RIGHT, UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiButSetFunc(), uiDefIconBut(), uiItemL(), uiItemR(), uiLayoutBox(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and uiLayoutSetAlignment().
Referenced by graph_panel_modifiers(), and nla_panel_modifiers().
void ANIM_unit_mapping_apply_fcurve (struct Scene * scene, struct ID * id, struct FCurve * fcu, short flag)
Definition at line 418 of file anim_draw.c.
References ANIM_editkeyframes_ok(), ANIM_fcurve_keyframes_loop(), ANIM_unit_mapping_get_factor(), ANIM_UNITCONV_ONLYSEL, ANIM_UNITCONV_RESTORE, BEZT_OK_SELECTED, bezt_unit_mapping_apply(), KeyframeEditData::f1, FCurve::fpt, G, i, KeyframeEditData::i1, NULL, and FPoint::vec.
Referenced by borderselect_graphkeys(), draw_fcurve_curve_bezts(), draw_fcurve_curve_samples(), get_nearest_fcurve_verts_list(), graph_draw_curves(), graphkeys_framejump_exec(), mirror_graph_keys(), and snap_graph_keys().
float ANIM_unit_mapping_get_factor (struct Scene * scene, struct ID * id, struct FCurve * fcu, short restore)
Definition at line 364 of file anim_draw.c.
References DEG2RADF, PROP_UNIT_ROTATION, RAD2DEGF, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), RNA_property_subtype(), RNA_SUBTYPE_UNIT, UnitSettings::system_rotation, Scene::unit, and USER_UNIT_ROT_RADIANS.
Referenced by ANIM_unit_mapping_apply_fcurve(), draw_fcurve_curve(), get_graph_keyframe_extents(), and graphkeys_click_insert_exec().
void ED_keymap_anim (struct wmKeyConfig * keyconf)
Definition at line 316 of file anim_ops.c.
References ACTIONMOUSE, KM_ALT, KM_CTRL, KM_PRESS, PKEY, wmKeyMapItem::ptr, RNA_string_set(), TKEY, WM_keymap_add_item(), WM_keymap_find(), and WM_keymap_verify_item().
Referenced by ED_spacetypes_keymap().
void ED_keymap_animchannels (struct wmKeyConfig * keyconf)
Definition at line 2400 of file anim_channels_edit.c.
References AKEY, BKEY, DELKEY, EVT_TWEAK_L, FALSE, IKEY, KM_ALT, KM_ANY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, wmKeyMapItem::ptr, REARRANGE_ANIMCHAN_BOTTOM, REARRANGE_ANIMCHAN_DOWN, REARRANGE_ANIMCHAN_TOP, REARRANGE_ANIMCHAN_UP, RNA_boolean_set(), RNA_enum_set(), TABKEY, TRUE, VKEY, WKEY, WM_keymap_add_item(), WM_keymap_find(), and XKEY.
Referenced by ED_spacetypes_keymap().
void ED_nla_postop_refresh (bAnimContext * ac)
Definition at line 79 of file nla_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_ANIMDATA, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, BKE_nla_validate_state(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::next, and NULL.
Referenced by nlaedit_add_actionclip_exec(), nlaedit_add_sound_exec(), nlaedit_add_transition_exec(), nlaedit_bake_exec(), nlaedit_clear_scale_exec(), nlaedit_delete_exec(), nlaedit_duplicate_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_snap_exec(), nlaedit_split_exec(), nlaedit_swap_exec(), and special_aftertrans_update().
void ED_operatormacros_action (void)
Definition at line 91 of file action_ops.c.
References wmOperatorType::description, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_enum_set(), TFM_TIME_DUPLICATE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatormacros_graph (void)
Definition at line 239 of file graph_ops.c.
References wmOperatorType::description, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_enum_set(), TFM_TIME_DUPLICATE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
void ED_operatortypes_anim (void)
Definition at line 282 of file anim_ops.c.
References ANIM_OT_change_frame(), ANIM_OT_copy_driver_button(), ANIM_OT_driver_button_add(), ANIM_OT_driver_button_remove(), ANIM_OT_keyframe_delete(), ANIM_OT_keyframe_delete_button(), ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert(), ANIM_OT_keyframe_insert_button(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), ANIM_OT_keying_set_add(), ANIM_OT_keying_set_path_add(), ANIM_OT_keying_set_path_remove(), ANIM_OT_keying_set_remove(), ANIM_OT_keyingset_button_add(), ANIM_OT_keyingset_button_remove(), ANIM_OT_paste_driver_button(), ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void ED_operatortypes_animchannels (void)
Definition at line 2371 of file anim_channels_edit.c.
References ANIM_OT_channels_click(), ANIM_OT_channels_collapse(), ANIM_OT_channels_delete(), ANIM_OT_channels_editable_toggle(), ANIM_OT_channels_expand(), ANIM_OT_channels_fcurves_enable(), ANIM_OT_channels_move(), ANIM_OT_channels_rename(), ANIM_OT_channels_select_all_toggle(), ANIM_OT_channels_select_border(), ANIM_OT_channels_setting_disable(), ANIM_OT_channels_setting_enable(), ANIM_OT_channels_setting_toggle(), ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
void free_fmodifiers_copybuf (void)
Definition at line 772 of file fmodifier_ui.c.
void getcolor_fcurve_rainbow (int cur, int tot, float * out)
Definition at line 194 of file anim_ipo_utils.c.
References HSV_BANDWIDTH, and hsv_to_rgb().
Referenced by graph_refresh().
int getname_anim_fcurve (char * name, struct ID * id, struct FCurve * fcu)
Definition at line 57 of file anim_ipo_utils.c.
References FCurve::array_index, BLI_getQuotedStr(), BLI_snprintf(), BLI_sprintfN(), PointerRNA::data, ELEM3, FCURVE_DISABLED, FCurve::flag, PointerRNA::id, MEM_freeN(), NULL, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), RNA_property_array_item_char(), RNA_property_array_length(), RNA_property_string_get_alloc(), RNA_property_ui_name(), RNA_struct_name_property(), RNA_struct_ui_icon(), RNA_struct_ui_name(), and PointerRNA::type.
Referenced by acf_fcurve_name(), and graph_panel_properties().
Variable Documentation
enum { ... } eAnimEditDraw_CurrentFrame