Blender: bmesh_operators.c File Reference
bmesh_operators.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "BLI_math.h"
#include "BLI_memarena.h"
#include "BLI_mempool.h"
#include "BLI_listbase.h"
#include "BLI_array.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
Classes
struct BMOpError
Defines
#define NEXT_CHAR(fmt) ((fmt)[0] != 0 ? (fmt)[1] : 0)
#define GOTO_ERROR(reason)
Typedefs
typedef struct BMOpError BMOpError
Functions
static void bmo_flag_layer_alloc (BMesh *bm)
ALLOC/FREE FLAG LAYER.
static void bmo_flag_layer_free (BMesh *bm)
static void bmo_flag_layer_clear (BMesh *bm)
static int bmo_name_to_slotcode (BMOpDefine *def, const char *name)
static int bmo_name_to_slotcode_check (BMOpDefine *def, const char *name)
static int bmo_opname_to_opcode (const char *opname)
void BMO_op_flag_enable (BMesh *UNUSED(bm), BMOperator *op, const int op_flag)
void BMO_op_flag_disable (BMesh *UNUSED(bm), BMOperator *op, const int op_flag)
void BMO_push (BMesh *bm, BMOperator *UNUSED(op))
BMESH OPSTACK PUSH.
void BMO_pop (BMesh *bm)
BMESH OPSTACK POP.
void BMO_op_init (BMesh *bm, BMOperator *op, const char *opname)
BMESH OPSTACK INIT OP.
void BMO_op_exec (BMesh *bm, BMOperator *op)
BMESH OPSTACK EXEC OP.
void BMO_op_finish (BMesh *bm, BMOperator *op)
BMESH OPSTACK FINISH OP.
int BMO_slot_exists (BMOperator *op, const char *slotname)
BMESH OPSTACK HAS SLOT.
BMOpSlot * BMO_slot_get (BMOperator *op, const char *slotname)
BMESH OPSTACK GET SLOT.
void BMO_slot_copy (BMOperator *source_op, BMOperator *dest_op, const char *src, const char *dst)
BMESH OPSTACK COPY SLOT.
void BMO_slot_float_set (BMOperator *op, const char *slotname, const float f)
void BMO_slot_int_set (BMOperator *op, const char *slotname, const int i)
void BMO_slot_bool_set (BMOperator *op, const char *slotname, const int i)
void BMO_slot_mat_set (BMOperator *op, const char *slotname, const float *mat, int size)
void BMO_slot_mat4_get (BMOperator *op, const char *slotname, float r_mat[4][4])
void BMO_slot_mat3_set (BMOperator *op, const char *slotname, float r_mat[3][3])
void BMO_slot_ptr_set (BMOperator *op, const char *slotname, void *p)
void BMO_slot_vec_set (BMOperator *op, const char *slotname, const float vec[3])
float BMO_slot_float_get (BMOperator *op, const char *slotname)
int BMO_slot_int_get (BMOperator *op, const char *slotname)
int BMO_slot_bool_get (BMOperator *op, const char *slotname)
void * BMO_slot_ptr_get (BMOperator *op, const char *slotname)
void BMO_slot_vec_get (BMOperator *op, const char *slotname, float r_vec[3])
static int bmo_mesh_flag_count (BMesh *bm, const char htype, const short oflag, const short test_for_enabled)
int BMO_mesh_enabled_flag_count (BMesh *bm, const char htype, const short oflag)
int BMO_mesh_disabled_flag_count (BMesh *bm, const char htype, const short oflag)
void BMO_mesh_flag_disable_all (BMesh *bm, BMOperator *UNUSED(op), const char htype, const short oflag)
int BMO_slot_buffer_count (BMesh *UNUSED(bm), BMOperator *op, const char *slotname)
int BMO_slot_map_count (BMesh *UNUSED(bm), BMOperator *op, const char *slotname)
void BMO_slot_map_insert (BMesh *UNUSED(bm), BMOperator *op, const char *slotname, void *element, void *data, int len)
void BMO_slot_map_to_flag (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const short oflag)
static void * bmo_slot_buffer_alloc (BMOperator *op, const char *slotname, int len)
static void BMO_slot_buffer_from_all (BMesh *bm, BMOperator *op, const char *slotname, const char htype)
BMO_ALL_TO_SLOT.
static void bmo_slot_buffer_from_hflag (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const char hflag, const short test_for_enabled)
BMO_HEADERFLAG_TO_SLOT.
void BMO_slot_buffer_from_enabled_hflag (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const char hflag)
void BMO_slot_buffer_from_disabled_hflag (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const char hflag)
void BMO_slot_buffer_append (BMOperator *output_op, const char *output_slot_name, BMOperator *other_op, const char *other_slot_name)
static void bmo_slot_buffer_from_flag (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const short oflag, const short test_for_enabled)
BMO_FLAG_TO_SLOT.
void BMO_slot_buffer_from_enabled_flag (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const short oflag)
void BMO_slot_buffer_from_disabled_flag (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const short oflag)
void BMO_slot_buffer_hflag_enable (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const char hflag, const char do_flush)
BMO_FLAG_BUFFER.
void BMO_slot_buffer_hflag_disable (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const char hflag, const char do_flush)
BMO_FLAG_BUFFER.
int BMO_vert_edge_flags_count (BMesh *bm, BMVert *v, const short oflag)
void BMO_slot_buffer_flag_enable (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const short oflag)
BMO_FLAG_BUFFER.
void BMO_slot_buffer_flag_disable (BMesh *bm, BMOperator *op, const char *slotname, const char htype, const short oflag)
BMO_FLAG_BUFFER.
void * BMO_slot_buffer_elem_first (BMOperator *op, const char *slotname)
void * BMO_iter_new (BMOIter *iter, BMesh *UNUSED(bm), BMOperator *op, const char *slotname, const char restrictmask)
New Iterator.
void * BMO_iter_step (BMOIter *iter)
void * BMO_iter_map_value (BMOIter *iter)
void * BMO_iter_map_value_p (BMOIter *iter)
float BMO_iter_map_value_f (BMOIter *iter)
void BMO_error_clear (BMesh *bm)
void BMO_error_raise (BMesh *bm, BMOperator *owner, int errcode, const char *msg)
int BMO_error_occurred (BMesh *bm)
int BMO_error_get (BMesh *bm, const char **msg, BMOperator **op)
int BMO_error_pop (BMesh *bm, const char **msg, BMOperator **op)
int BMO_op_vinitf (BMesh *bm, BMOperator *op, const char *_fmt, va_list vlist)
int BMO_op_initf (BMesh *bm, BMOperator *op, const char *fmt,...)
int BMO_op_callf (BMesh *bm, const char *fmt,...)
Variables
static const char * bmo_error_messages []
const int BMO_OPSLOT_TYPEINFO [BMO_OP_SLOT_TOTAL_TYPES]
static BMOpSlot BMOpEmptySlot = {0}
Detailed Description
BMesh operator access.
Definition in file bmesh_operators.c.
Define Documentation
#define GOTO_ERROR (reason)
Value:
{                        \
        err_reason = reason; \
        lineno = __LINE__;   \
        goto error;          \
    } (void)0
Referenced by BMO_op_vinitf().
#define NEXT_CHAR (fmt) ((fmt)[0] != 0 ? (fmt)[1] : 0)
Definition at line 1283 of file bmesh_operators.c.
Referenced by BMO_op_vinitf(), console_keymap(), console_move_exec(), ED_keymap_curve(), move_cursor(), text_keymap(), and text_move_cursor().
Typedef Documentation
typedef struct BMOpError BMOpError
Function Documentation
void BMO_error_clear (BMesh * bm)
Definition at line 1232 of file bmesh_operators.c.
References BMO_error_pop(), and NULL.
Referenced by BM_mesh_data_free(), bmo_dissolve_faces_exec(), bmo_dissolve_limit_exec(), and bmo_dissolve_verts_exec().
int BMO_error_get (BMesh * bm, const char ** msg, BMOperator ** op)
Definition at line 1255 of file bmesh_operators.c.
References err, BMOpError::errorcode, BMesh::errorstack, ListBase::first, BMOpError::msg, and BMOpError::op.
Referenced by bmo_dissolve_verts_exec(), BMO_error_pop(), and EDBM_op_finish().
int BMO_error_occurred (BMesh * bm)
Definition at line 1249 of file bmesh_operators.c.
References BMesh::errorstack, ListBase::first, and NULL.
Referenced by BM_faces_join(), bmo_dissolve_faces_exec(), and bmo_dissolve_verts_exec().
int BMO_error_pop (BMesh * bm, const char ** msg, BMOperator ** op)
Definition at line 1268 of file bmesh_operators.c.
References BLI_remlink(), BMO_error_get(), err, BMOpError::errorcode, BMesh::errorstack, ListBase::first, and MEM_freeN().
Referenced by BMO_error_clear().
void BMO_error_raise (BMesh * bm, BMOperator * owner, int errcode, const char * msg)
Definition at line 1237 of file bmesh_operators.c.
References BLI_addhead(), bmo_error_messages, err, BMOpError::errorcode, BMesh::errorstack, MEM_callocN(), BMOpError::msg, and BMOpError::op.
Referenced by BM_faces_join(), bmo_bridge_loops_exec(), bmo_connectverts_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_verts_exec(), bmo_edgerotate_exec(), bmo_extrude_face_indiv_exec(), bmo_vertex_slide_exec(), bmw_IslandboundWalker_step(), and count_flagged_radial().
static void bmo_flag_layer_alloc (BMesh * bm) [static]
ALLOC/FREE FLAG LAYER.
Used by operator stack to free/allocate private flag data. This is allocated using a mempool so the allocation/frees should be quite fast.
BMESH_TODO: Investigate not freeing flag layers until all operators have been executed. This would save a lot of realloc potentially.
Definition at line 1017 of file bmesh_operators.c.
References BLI_mempool_calloc(), BLI_mempool_create(), BLI_mempool_destroy(), BM_EDGE, BM_EDGES_OF_MESH, BM_elem_index_set, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH_INDEX, BM_VERT, BM_VERTS_OF_MESH, BMesh::elem_index_dirty, i, BMElemF::oflags, BMesh::toolflagpool, and BMesh::totflags.
Referenced by BMO_push().
static void bmo_flag_layer_clear (BMesh * bm) [static]
Definition at line 1107 of file bmesh_operators.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_elem_index_set, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH_INDEX, BM_VERT, BM_VERTS_OF_MESH, BMesh::elem_index_dirty, i, BMElemF::oflags, and BMesh::totflags.
Referenced by BMO_push().
static void bmo_flag_layer_free (BMesh * bm) [static]
Definition at line 1062 of file bmesh_operators.c.
References BLI_mempool_calloc(), BLI_mempool_create(), BLI_mempool_destroy(), BLI_MEMPOOL_SYSMALLOC, BM_EDGE, BM_EDGES_OF_MESH, BM_elem_index_set, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH_INDEX, BM_VERT, BM_VERTS_OF_MESH, BMesh::elem_index_dirty, i, BMElemF::oflags, BMesh::toolflagpool, and BMesh::totflags.
Referenced by BMO_pop().
void* BMO_iter_map_value (BMOIter * iter)
Definition at line 1209 of file bmesh_operators.c.
References BMOIter::val.
Referenced by bmo_extrude_edge_only_exec(), and bmo_extrude_face_region_exec().
float BMO_iter_map_value_f (BMOIter * iter)
Definition at line 1219 of file bmesh_operators.c.
References BMOIter::val.
void* BMO_iter_map_value_p (BMOIter * iter)
Definition at line 1214 of file bmesh_operators.c.
References BMOIter::val.
Referenced by bm_merge_dm_transform(), find_doubles_index_map(), and merge_first_last().
void* BMO_iter_new (BMOIter * iter, BMesh * UNUSEDbm, BMOperator * op, const char * slotname, const char restrictmask)
New Iterator.
Parameters:
restrictmask restricts the iteration to certain element types (e.g. combination of BM_VERT, BM_EDGE, BM_FACE), if iterating over an element buffer (not a mapping).
Definition at line 1150 of file bmesh_operators.c.
References BLI_ghashIterator_init(), BMO_iter_step(), BMO_OP_SLOT_MAPPING, BMO_slot_get(), BMOIter::cur, BMOpSlot::data, BMOpSlot::ghash, BMOIter::giter, NULL, BMOIter::restrictmask, BMOIter::slot, and BMOpSlot::slottype.
void* BMO_iter_step (BMOIter * iter)
Definition at line 1173 of file bmesh_operators.c.
References BLI_ghashIterator_getKey(), BLI_ghashIterator_getValue(), BLI_ghashIterator_step(), BMO_OP_SLOT_ELEMENT_BUF, BMO_OP_SLOT_MAPPING, BMOpSlot::buf, BMOIter::cur, BMOpSlot::data, BMOIter::giter, BMHeader::htype, BMOpSlot::len, NULL, BMOIter::restrictmask, BMOIter::slot, BMOpSlot::slottype, and BMOIter::val.
Referenced by BM_mesh_esubdivide(), bmo_extrude_edge_only_exec(), bmo_extrude_face_region_exec(), bmo_extrude_vert_indiv_exec(), BMO_iter_new(), and bmo_triangulate_exec().
int BMO_mesh_disabled_flag_count (BMesh * bm, const char htype, const short oflag)
Definition at line 492 of file bmesh_operators.c.
References bmo_mesh_flag_count(), and FALSE.
Referenced by bmo_slot_buffer_from_flag().
int BMO_mesh_enabled_flag_count (BMesh * bm, const char htype, const short oflag)
Definition at line 487 of file bmesh_operators.c.
References bmo_mesh_flag_count(), and TRUE.
Referenced by bmo_slot_buffer_from_flag().
static int bmo_mesh_flag_count (BMesh * bm, const char htype, const short oflag, const short test_for_enabled) [static]
Definition at line 458 of file bmesh_operators.c.
References BLI_assert, BM_EDGE, BM_EDGES_OF_MESH, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_test_bool, ELEM, FALSE, i, and TRUE.
Referenced by BMO_mesh_disabled_flag_count(), and BMO_mesh_enabled_flag_count().
void BMO_mesh_flag_disable_all (BMesh * bm, BMOperator * UNUSEDop, const char htype, const short oflag)
Definition at line 497 of file bmesh_operators.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_disable, and i.
static int bmo_name_to_slotcode (BMOpDefine * def, const char * name) [static]
Definition at line 1285 of file bmesh_operators.c.
References i, MAX_SLOTNAME, BMOSlotType::name, BMOpDefine::slottypes, and BMOSlotType::type.
Referenced by bmo_name_to_slotcode_check(), and BMO_slot_exists().
static int bmo_name_to_slotcode_check (BMOpDefine * def, const char * name) [static]
Definition at line 1298 of file bmesh_operators.c.
References bmo_name_to_slotcode(), and i.
Referenced by BMO_op_vinitf(), and BMO_slot_get().
int BMO_op_callf (BMesh * bm, const char * fmt, ...)
Definition at line 1571 of file bmesh_operators.c.
References BMO_op_exec(), BMO_op_finish(), BMO_op_vinitf(), FALSE, BMOpError::op, and TRUE.
Referenced by bmo_bevel_exec(), bmo_collapse_exec(), bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_grid_exec(), bmo_create_uvsphere_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_verts_exec(), bmo_extrude_face_indiv_exec(), bmo_mirror_exec(), bmo_object_load_bmesh_exec(), bmo_rotate_exec(), bmo_scale_exec(), bmo_spin_exec(), bmo_translate_exec(), bmo_weldverts_exec(), doEdgeSplit(), EDBM_automerge(), and edbm_extrude_repeat_exec().
void BMO_op_exec (BMesh * bm, BMOperator * op)
BMESH OPSTACK EXEC OP.
Executes a passed in operator.
This handles the allocation and freeing of temporary flag layers and starting/stopping the modeling loop. Can be called from other operators exec callbacks as well.
Definition at line 170 of file bmesh_operators.c.
References bmesh_edit_begin(), bmesh_edit_end(), BMO_pop(), BMO_push(), BMOperator::exec, BMOperator::flag, and BMesh::stackdepth.
Referenced by arrayModifier_doArray(), bm_merge_dm_transform(), BM_mesh_esubdivide(), bmo_automerge_exec(), bmo_collapse_exec(), bmo_contextual_create_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_uvsphere_exec(), bmo_extrude_edge_only_exec(), bmo_extrude_face_region_exec(), bmo_mirror_exec(), BMO_op_callf(), bmo_pointmerge_exec(), bmo_removedoubles_exec(), bmo_solidify_face_region_exec(), bmo_spin_exec(), bmo_split_exec(), bmo_triangle_fill_exec(), edbm_add_edge_face_exec(), edbm_bevel_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edge(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_extrude_verts_indiv(), edbm_fill_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), EDBM_op_call_and_selectf(), EDBM_op_call_silentf(), EDBM_op_callf(), edbm_remove_doubles_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_call_edgesplit(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), EDBM_select_less(), EDBM_select_more(), edbm_select_vertex_path_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), find_doubles_index_map(), merge_first_last(), similar_edge_select_exec(), similar_face_select_exec(), and similar_vert_select_exec().
void BMO_op_finish (BMesh * bm, BMOperator * op)
BMESH OPSTACK FINISH OP.
Does housekeeping chores related to finishing up an operator.
Definition at line 190 of file bmesh_operators.c.
References BMOperator::arena, BLI_ghash_free(), BLI_memarena_free(), BM_ELEM_INDEX_VALIDATE, BMO_OP_SLOT_MAPPING, BMOpSlot::data, BMOpSlot::ghash, i, BMOpDefine::name, NULL, opdefines, BMOperator::slots, BMOpSlot::slottype, BMOpDefine::slottypes, BMOSlotType::type, and BMOperator::type.
Referenced by arrayModifier_doArray(), bm_merge_dm_transform(), BM_mesh_esubdivide(), bm_rationalize_normals(), bmo_automerge_exec(), bmo_collapse_exec(), bmo_contextual_create_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_uvsphere_exec(), bmo_extrude_edge_only_exec(), bmo_extrude_face_region_exec(), bmo_mirror_exec(), BMO_op_callf(), BMO_op_vinitf(), bmo_pointmerge_exec(), bmo_removedoubles_exec(), bmo_solidify_face_region_exec(), bmo_spin_exec(), bmo_split_exec(), bmo_triangle_fill_exec(), edbm_extrude_edge(), EDBM_op_finish(), edbm_remove_doubles_exec(), EDBM_select_less(), EDBM_select_more(), find_doubles_index_map(), and merge_first_last().
void BMO_op_flag_disable (BMesh * UNUSEDbm, BMOperator * op, const int op_flag)
Definition at line 88 of file bmesh_operators.c.
References BMOperator::flag.
void BMO_op_flag_enable (BMesh * UNUSEDbm, BMOperator * op, const int op_flag)
Definition at line 83 of file bmesh_operators.c.
References BMOperator::flag.
void BMO_op_init (BMesh * bm, BMOperator * op, const char * opname)
BMESH OPSTACK INIT OP.
Initializes an operator structure to a certain type
Definition at line 129 of file bmesh_operators.c.
References BMOperator::arena, BLI_memarena_new(), BLI_MEMARENA_STD_BUFSIZE, BLI_memarena_use_calloc(), BM_ELEM_INDEX_VALIDATE, bmo_opname_to_opcode(), BMOperator::exec, BMOpDefine::exec, BMOpDefine::flag, BMOperator::flag, i, BMOpSlot::index, opdefines, BMOperator::slots, BMOpSlot::slottype, BMOpDefine::slottypes, BMOSlotType::type, and BMOperator::type.
Referenced by arrayModifier_doArray(), bmo_automerge_exec(), bmo_collapse_exec(), bmo_extrude_face_region_exec(), bmo_mirror_exec(), BMO_op_vinitf(), bmo_pointmerge_exec(), bmo_removedoubles_exec(), bmo_solidify_face_region_exec(), bmo_split_exec(), and edbm_extrude_edge().
int BMO_op_initf (BMesh * bm, BMOperator * op, const char * fmt, ...)
Definition at line 1556 of file bmesh_operators.c.
References BMO_op_vinitf(), FALSE, and TRUE.
Referenced by arrayModifier_doArray(), bm_merge_dm_transform(), BM_mesh_esubdivide(), bm_rationalize_normals(), bmo_automerge_exec(), bmo_contextual_create_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_uvsphere_exec(), bmo_extrude_edge_only_exec(), bmo_extrude_face_region_exec(), bmo_mirror_exec(), bmo_solidify_face_region_exec(), bmo_spin_exec(), bmo_triangle_fill_exec(), EDBM_select_less(), EDBM_select_more(), find_doubles_index_map(), and merge_first_last().
int BMO_op_vinitf (BMesh * bm, BMOperator * op, const char * _fmt, va_list vlist)
Definition at line 1336 of file bmesh_operators.c.
References BMOperator::arena, BLI_memarena_alloc(), BLI_strdup(), BLI_strncpy(), BM_EDGE, BM_FACE, BM_VERT, bmo_name_to_slotcode_check(), BMO_op_finish(), BMO_op_init(), bmo_opname_to_opcode(), BMO_slot_bool_set(), BMO_slot_buffer_from_all(), BMO_slot_buffer_from_disabled_flag(), BMO_slot_buffer_from_disabled_hflag(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_buffer_from_enabled_hflag(), BMO_slot_copy(), BMO_slot_float_set(), BMO_slot_get(), BMO_slot_int_set(), BMO_slot_mat_set(), BMO_slot_ptr_set(), BMO_slot_vec_set(), BMOpSlot::buf, BMOpSlot::data, error(), FALSE, GOTO_ERROR, i, BMOpSlot::len, MEM_freeN(), NEXT_CHAR, opdefines, size(), state, and TRUE.
Referenced by BMO_op_callf(), BMO_op_initf(), EDBM_op_call_and_selectf(), EDBM_op_call_silentf(), EDBM_op_callf(), and EDBM_op_init().
static int bmo_opname_to_opcode (const char * opname) [static]
Definition at line 1308 of file bmesh_operators.c.
References bmesh_total_ops, i, and opdefines.
Referenced by BMO_op_init(), and BMO_op_vinitf().
void BMO_pop (BMesh * bm)
BMESH OPSTACK POP.
Pops the opstack one level and frees a flag layer if appropriate
BMESH_TODO: investigate NOT freeing flag layers.
Definition at line 116 of file bmesh_operators.c.
References bmo_flag_layer_free(), and BMesh::stackdepth.
Referenced by arrayModifier_doArray(), bm_rationalize_normals(), BME_bevel(), BMO_op_exec(), doEdgeSplit(), and walker_deselect_nth().
void BMO_push (BMesh * bm, BMOperator * UNUSEDop)
BMESH OPSTACK PUSH.
Pushes the opstack down one level and allocates a new flag layer if appropriate.
Definition at line 98 of file bmesh_operators.c.
References bmo_flag_layer_alloc(), bmo_flag_layer_clear(), and BMesh::stackdepth.
int BMO_slot_bool_get (BMOperator * op, const char * slotname)
Definition at line 419 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_BOOL, BMO_slot_get(), BMOpSlot::data, BMOpSlot::i, and BMOpSlot::slottype.
Referenced by bmo_bevel_exec(), bmo_bmesh_to_mesh_exec(), bmo_contextual_create_exec(), bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_dissolve_edges_exec(), bmo_dissolve_faces_exec(), bmo_edgenet_fill_exec(), bmo_edgerotate_exec(), bmo_edgesplit_exec(), bmo_esubd_exec(), bmo_extrude_face_region_exec(), bmo_inset_exec(), bmo_join_triangles_exec(), bmo_mesh_to_bmesh_exec(), bmo_mirror_exec(), bmo_regionextend_exec(), bmo_righthandfaces_exec(), bmo_spin_exec(), bmo_split_exec(), bmo_triangulate_exec(), bmo_vertexsmooth_exec(), and edge_find_shortest_path().
void BMO_slot_bool_set (BMOperator * op, const char * slotname, const int i)
Definition at line 324 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_BOOL, BMO_slot_get(), BMOpSlot::data, BMOpSlot::i, i, and BMOpSlot::slottype.
Referenced by BMO_op_vinitf(), and edbm_knife_cut_exec().
static void* bmo_slot_buffer_alloc (BMOperator * op, const char * slotname, int len) [static]
Definition at line 628 of file bmesh_operators.c.
References BMOperator::arena, BLI_assert, BLI_memarena_alloc(), BMO_OP_SLOT_ELEMENT_BUF, BMO_OPSLOT_TYPEINFO, BMO_slot_get(), BMOpSlot::buf, BMOpSlot::data, len(), BMOpSlot::len, NULL, and BMOpSlot::slottype.
Referenced by BMO_slot_buffer_from_all(), bmo_slot_buffer_from_flag(), and bmo_slot_buffer_from_hflag().
void BMO_slot_buffer_append (BMOperator * output_op, const char * output_slot_name, BMOperator * other_op, const char * other_slot_name)
Copies the values from another slot to the end of the output slot.
Definition at line 769 of file bmesh_operators.c.
References BMOperator::arena, BLI_assert, BLI_memarena_alloc(), BMO_OP_SLOT_ELEMENT_BUF, BMO_OPSLOT_TYPEINFO, BMO_slot_copy(), BMO_slot_get(), BMOpSlot::buf, BMOpSlot::data, BMOpSlot::len, and BMOpSlot::slottype.
Referenced by bm_merge_dm_transform(), and merge_first_last().
int BMO_slot_buffer_count (BMesh * UNUSEDbm, BMOperator * op, const char * slotname)
Definition at line 518 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_ELEMENT_BUF, BMO_slot_get(), BMOpSlot::len, and BMOpSlot::slottype.
void* BMO_slot_buffer_elem_first (BMOperator * op, const char * slotname)
Definition at line 1134 of file bmesh_operators.c.
References BMO_OP_SLOT_ELEMENT_BUF, BMO_slot_get(), BMOpSlot::buf, BMOpSlot::data, NULL, and BMOpSlot::slottype.
void BMO_slot_buffer_flag_disable (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const short oflag)
BMO_FLAG_BUFFER.
Removes flags from elements in a slots buffer
Definition at line 986 of file bmesh_operators.c.
References BLI_assert, BMO_elem_flag_disable, BMO_OP_SLOT_ELEMENT_BUF, BMO_slot_get(), data, BMOpSlot::data, i, BMOpSlot::len, BMOpSlot::p, and BMOpSlot::slottype.
void BMO_slot_buffer_flag_enable (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const short oflag)
BMO_FLAG_BUFFER.
Flags elements in a slots buffer
Definition at line 964 of file bmesh_operators.c.
References BLI_assert, BMO_elem_flag_enable, BMO_OP_SLOT_ELEMENT_BUF, BMO_slot_get(), data, BMOpSlot::data, i, BMOpSlot::len, BMOpSlot::p, and BMOpSlot::slottype.
Referenced by bmesh_finddoubles_common(), bmo_automerge_exec(), bmo_beautify_fill_exec(), bmo_bridge_loops_exec(), bmo_collapse_exec(), bmo_collapsecon_do_layer(), bmo_connectverts_exec(), bmo_contextual_create_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_uvsphere_exec(), bmo_del_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_verts_exec(), bmo_dupe_exec(), bmo_edgenet_fill_exec(), bmo_edgenet_prepare(), bmo_edgesplit_exec(), bmo_esubd_exec(), bmo_extrude_face_region_exec(), bmo_mirror_exec(), bmo_regionextend_exec(), bmo_righthandfaces_exec(), bmo_solidify_face_region_exec(), bmo_split_exec(), and bmo_triangle_fill_exec().
static void BMO_slot_buffer_from_all (BMesh * bm, BMOperator * op, const char * slotname, const char htype) [static]
BMO_ALL_TO_SLOT.
Copies all elements of a certain type into an operator slot.
Definition at line 648 of file bmesh_operators.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, bmo_slot_buffer_alloc(), BMO_slot_get(), BMOpSlot::data, i, BMOpSlot::p, BMesh::totedge, BMesh::totface, and BMesh::totvert.
Referenced by BMO_op_vinitf().
void BMO_slot_buffer_from_disabled_flag (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const short oflag)
Definition at line 868 of file bmesh_operators.c.
References bmo_slot_buffer_from_flag(), and FALSE.
Referenced by BMO_op_vinitf().
void BMO_slot_buffer_from_disabled_hflag (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const char hflag)
Definition at line 760 of file bmesh_operators.c.
References bmo_slot_buffer_from_hflag(), and FALSE.
Referenced by BMO_op_vinitf().
void BMO_slot_buffer_from_enabled_flag (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const short oflag)
Definition at line 862 of file bmesh_operators.c.
References bmo_slot_buffer_from_flag(), and TRUE.
Referenced by bmo_beautify_fill_exec(), bmo_bevel_exec(), bmo_connectverts_exec(), bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_cube_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_monkey_exec(), bmo_create_uvsphere_exec(), bmo_dissolve_faces_exec(), bmo_dupe_exec(), bmo_edgebisect_exec(), bmo_edgenet_fill_exec(), bmo_edgenet_prepare(), bmo_edgerotate_exec(), bmo_esubd_exec(), bmo_extrude_edge_only_exec(), bmo_extrude_face_indiv_exec(), bmo_extrude_vert_indiv_exec(), bmo_inset_exec(), bmo_makevert_exec(), bmo_mirror_exec(), BMO_op_vinitf(), bmo_regionextend_exec(), bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), bmo_split_exec(), bmo_triangle_fill_exec(), bmo_triangulate_exec(), bmo_vertex_slide_exec(), bmo_vertexshortestpath_exec(), and edbm_knife_cut_exec().
void BMO_slot_buffer_from_enabled_hflag (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const char hflag)
Definition at line 754 of file bmesh_operators.c.
References bmo_slot_buffer_from_hflag(), and TRUE.
Referenced by bmo_edgesplit_exec(), BMO_op_vinitf(), and edbm_extrude_edge().
static void bmo_slot_buffer_from_flag (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const short oflag, const short test_for_enabled) [static]
BMO_FLAG_TO_SLOT.
Copies elements of a certain type, which have a certain flag set into an output slot for an operator.
Definition at line 803 of file bmesh_operators.c.
References BLI_assert, BM_EDGE, BM_EDGES_OF_MESH, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_test_bool, BMO_mesh_disabled_flag_count(), BMO_mesh_enabled_flag_count(), BMO_OP_SLOT_ELEMENT_BUF, bmo_slot_buffer_alloc(), BMO_slot_get(), BMOpSlot::data, ELEM, FALSE, i, if(), BMOpSlot::len, BMOpSlot::p, BMOpSlot::slottype, and TRUE.
Referenced by BMO_slot_buffer_from_disabled_flag(), and BMO_slot_buffer_from_enabled_flag().
static void bmo_slot_buffer_from_hflag (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const char hflag, const short test_for_enabled) [static]
BMO_HEADERFLAG_TO_SLOT.
Copies elements of a certain type, which have a certain header flag enabled/disabled into a slot for an operator.
Definition at line 694 of file bmesh_operators.c.
References BLI_assert, BM_EDGE, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_elem_flag_test_bool, BM_ELEM_HIDDEN, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_mesh_elem_hflag_count_disabled(), BM_mesh_elem_hflag_count_enabled(), BM_VERT, BM_VERTS_OF_MESH, bmo_slot_buffer_alloc(), BMO_slot_get(), BMOpSlot::data, ELEM, FALSE, i, BMOpSlot::len, BMOpSlot::p, and TRUE.
Referenced by BMO_slot_buffer_from_disabled_hflag(), and BMO_slot_buffer_from_enabled_hflag().
void BMO_slot_buffer_hflag_disable (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const char hflag, const char do_flush)
BMO_FLAG_BUFFER.
Removes flags from elements in a slots buffer, automatically using the selection API where appropriate.
Definition at line 913 of file bmesh_operators.c.
References BLI_assert, BM_elem_flag_disable, BM_ELEM_HIDDEN, BM_elem_hide_set, BM_ELEM_SELECT, BM_elem_select_set(), BMO_OP_SLOT_ELEMENT_BUF, BMO_slot_get(), data, BMOpSlot::data, FALSE, i, BMOpSlot::len, BMOpSlot::p, and BMOpSlot::slottype.
Referenced by bmo_inset_exec(), edbm_edge_rotate_selected_exec(), edbm_extrude_verts_indiv(), edbm_inset_exec(), EDBM_select_less(), edbm_solidify_exec(), and edbm_vertex_slide_exec().
void BMO_slot_buffer_hflag_enable (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const char hflag, const char do_flush)
BMO_FLAG_BUFFER.
Header Flags elements in a slots buffer, automatically using the selection API where appropriate.
Definition at line 880 of file bmesh_operators.c.
References BLI_assert, BM_elem_flag_enable, BM_ELEM_HIDDEN, BM_elem_hide_set, BM_ELEM_SELECT, BM_elem_select_set(), BMO_OP_SLOT_ELEMENT_BUF, BMO_slot_get(), data, BMOpSlot::data, FALSE, i, BMOpSlot::len, BMOpSlot::p, BMOpSlot::slottype, and TRUE.
Referenced by bmo_inset_exec(), edbm_add_edge_face_exec(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_extrude_edges_indiv(), edbm_extrude_verts_indiv(), edbm_fill_exec(), edbm_inset_exec(), EDBM_op_call_and_selectf(), edbm_screw_exec(), EDBM_select_more(), edbm_select_vertex_path_exec(), edbm_solidify_exec(), edbm_spin_exec(), edbm_split_exec(), edbm_vertex_slide_exec(), similar_edge_select_exec(), similar_face_select_exec(), and similar_vert_select_exec().
void BMO_slot_copy (BMOperator * source_op, BMOperator * dest_op, const char * src, const char * dst)
BMESH OPSTACK COPY SLOT.
Copies data from one slot to another.
Definition at line 244 of file bmesh_operators.c.
References BMOperator::arena, BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashIterator_getValue(), BLI_ghashIterator_init(), BLI_ghashIterator_step(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BLI_memarena_alloc(), BMO_OP_SLOT_ELEMENT_BUF, BMO_OP_SLOT_MAPPING, BMO_OPSLOT_TYPEINFO, BMO_slot_get(), BMOpSlot::buf, BMOpSlot::data, BMOElemMapping::element, BMOpSlot::ghash, BMOpSlot::len, BMOElemMapping::len, NULL, and BMOpSlot::slottype.
Referenced by bmo_automerge_exec(), bmo_contextual_create_exec(), bmo_dupe_exec(), bmo_extrude_face_region_exec(), BMO_op_vinitf(), BMO_slot_buffer_append(), bmo_solidify_face_region_exec(), bmo_spin_exec(), and bmo_split_exec().
int BMO_slot_exists (BMOperator * op, const char * slotname)
BMESH OPSTACK HAS SLOT.
Returns:
Success if the slot if found.
Definition at line 217 of file bmesh_operators.c.
References bmo_name_to_slotcode(), opdefines, and BMOperator::type.
Referenced by bmesh_finddoubles_common().
float BMO_slot_float_get (BMOperator * op, const char * slotname)
Definition at line 399 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_FLT, BMO_slot_get(), BMOpSlot::data, BMOpSlot::f, and BMOpSlot::slottype.
Referenced by bmesh_finddoubles_common(), bmo_bevel_exec(), bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_cube_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_uvsphere_exec(), bmo_dissolve_limit_exec(), bmo_esubd_exec(), bmo_inset_exec(), bmo_join_triangles_exec(), bmo_mirror_exec(), bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), bmo_solidify_face_region_exec(), bmo_spin_exec(), bmo_vertex_slide_exec(), and bmo_vertexsmooth_exec().
void BMO_slot_float_set (BMOperator * op, const char * slotname, const float f)
Definition at line 304 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_FLT, BMO_slot_get(), BMOpSlot::data, BMOpSlot::f, and BMOpSlot::slottype.
Referenced by BMO_op_vinitf(), and edbm_knife_cut_exec().
BMOpSlot* BMO_slot_get (BMOperator * op, const char * slotname)
BMESH OPSTACK GET SLOT.
Returns a pointer to the slot of type 'slotcode'
Definition at line 228 of file bmesh_operators.c.
References bmo_name_to_slotcode_check(), BMOpEmptySlot, opdefines, BMOperator::slots, and BMOperator::type.
Referenced by arrayModifier_doArray(), bmo_dissolve_limit_exec(), bmo_esubd_exec(), BMO_iter_new(), BMO_op_vinitf(), BMO_slot_bool_get(), BMO_slot_bool_set(), bmo_slot_buffer_alloc(), BMO_slot_buffer_append(), BMO_slot_buffer_count(), BMO_slot_buffer_elem_first(), BMO_slot_buffer_flag_disable(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_all(), bmo_slot_buffer_from_flag(), bmo_slot_buffer_from_hflag(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), BMO_slot_copy(), BMO_slot_float_get(), BMO_slot_float_set(), BMO_slot_int_get(), BMO_slot_int_set(), BMO_slot_map_contains(), BMO_slot_map_count(), BMO_slot_map_data_get(), BMO_slot_map_insert(), BMO_slot_map_to_flag(), BMO_slot_mat3_set(), BMO_slot_mat4_get(), BMO_slot_mat_set(), BMO_slot_ptr_get(), BMO_slot_ptr_set(), BMO_slot_vec_get(), BMO_slot_vec_set(), edbm_edge_split_exec(), and edbm_vert_connect().
int BMO_slot_int_get (BMOperator * op, const char * slotname)
Definition at line 409 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_INT, BMO_slot_get(), BMOpSlot::data, BMOpSlot::i, and BMOpSlot::slottype.
Referenced by bmo_bevel_exec(), bmo_contextual_create_exec(), bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_uvsphere_exec(), bmo_del_exec(), bmo_edgebisect_exec(), bmo_edgenet_fill_exec(), bmo_esubd_exec(), bmo_face_rotateuvs_exec(), bmo_mirror_exec(), bmo_rotatecolors_exec(), bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), bmo_spin_exec(), and bmo_vertexshortestpath_exec().
void BMO_slot_int_set (BMOperator * op, const char * slotname, const int i)
Definition at line 314 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_INT, BMO_slot_get(), BMOpSlot::data, BMOpSlot::i, i, and BMOpSlot::slottype.
Referenced by BMO_op_vinitf(), bmo_split_exec(), and edbm_knife_cut_exec().
int BMO_slot_map_count (BMesh * UNUSEDbm, BMOperator * op, const char * slotname)
Definition at line 530 of file bmesh_operators.c.
References BLI_assert, BLI_ghash_size(), BMO_OP_SLOT_MAPPING, BMO_slot_get(), BMOpSlot::data, BMOpSlot::ghash, and BMOpSlot::slottype.
void BMO_slot_map_insert (BMesh * UNUSEDbm, BMOperator * op, const char * slotname, void * element, void * data, int len)
Definition at line 545 of file bmesh_operators.c.
References BMOperator::arena, BLI_assert, BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BLI_memarena_alloc(), BMO_OP_SLOT_MAPPING, BMO_slot_get(), BMOpSlot::data, BMOElemMapping::element, BMOpSlot::ghash, len(), BMOElemMapping::len, and BMOpSlot::slottype.
Referenced by BMO_slot_map_float_insert(), BMO_slot_map_int_insert(), and BMO_slot_map_ptr_insert().
void BMO_slot_map_to_flag (BMesh * bm, BMOperator * op, const char * slotname, const char htype, const short oflag)
Definition at line 608 of file bmesh_operators.c.
References BLI_assert, BLI_ghashIterator_getKey(), BLI_ghashIterator_init(), BLI_ghashIterator_step(), BMO_elem_flag_enable, BMO_OP_SLOT_MAPPING, BMO_slot_get(), BMOpSlot::data, BMOpSlot::ghash, BMElemF::head, BMHeader::htype, and BMOpSlot::slottype.
Referenced by bmo_esubd_exec().
void BMO_slot_mat3_set (BMOperator * op, const char * slotname, float r_mat[3][3])
Definition at line 368 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_MAT, BMO_slot_get(), copy_m3_m4(), BMOpSlot::data, BMOpSlot::p, and BMOpSlot::slottype.
void BMO_slot_mat4_get (BMOperator * op, const char * slotname, float r_mat[4][4])
Definition at line 358 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_MAT, BMO_slot_get(), copy_m4_m4(), BMOpSlot::data, BMOpSlot::p, and BMOpSlot::slottype.
Referenced by bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_cube_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_monkey_exec(), bmo_create_uvsphere_exec(), bmo_mirror_exec(), and bmo_transform_exec().
void BMO_slot_mat_set (BMOperator * op, const char * slotname, const float * mat, int size)
Definition at line 335 of file bmesh_operators.c.
References BMOperator::arena, BLI_assert, BLI_memarena_alloc(), BMO_OP_SLOT_MAT, BMO_slot_get(), copy_m4_m3(), BMOpSlot::data, BMOpSlot::len, BMOpSlot::p, and BMOpSlot::slottype.
Referenced by BMO_op_vinitf().
void* BMO_slot_ptr_get (BMOperator * op, const char * slotname)
Definition at line 430 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_PNT, BMO_slot_get(), BMOpSlot::data, NULL, BMOpSlot::p, and BMOpSlot::slottype.
Referenced by bmo_bmesh_to_mesh_exec(), bmo_dupe_exec(), bmo_mesh_to_bmesh_exec(), and bmo_object_load_bmesh_exec().
void BMO_slot_ptr_set (BMOperator * op, const char * slotname, void * p)
Definition at line 378 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_PNT, BMO_slot_get(), BMOpSlot::data, p, BMOpSlot::p, and BMOpSlot::slottype.
Referenced by BMO_op_vinitf().
void BMO_slot_vec_get (BMOperator * op, const char * slotname, float r_vec[3])
Definition at line 440 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_VEC, BMO_slot_get(), copy_v3_v3(), BMOpSlot::data, BMOpSlot::slottype, and BMOpSlot::vec.
Referenced by bmo_makevert_exec(), bmo_pointmerge_exec(), bmo_rotate_exec(), bmo_scale_exec(), bmo_spin_exec(), and bmo_translate_exec().
void BMO_slot_vec_set (BMOperator * op, const char * slotname, const float vec[3])
Definition at line 388 of file bmesh_operators.c.
References BLI_assert, BMO_OP_SLOT_VEC, BMO_slot_get(), copy_v3_v3(), BMOpSlot::data, BMOpSlot::slottype, and BMOpSlot::vec.
Referenced by BMO_op_vinitf().
int BMO_vert_edge_flags_count (BMesh * bm, BMVert * v, const short oflag)
Definition at line 940 of file bmesh_operators.c.
References bmesh_disk_count(), bmesh_disk_edge_next(), BMO_elem_flag_test, BMVert::e, i, and len().
Referenced by bmo_edgenet_prepare().
Variable Documentation
const char* bmo_error_messages[] [static]
Initial value:
 {
    NULL,
    "Self intersection error",
    "Could not dissolve vert",
    "Could not connect vertices",
    "Could not traverse mesh",
    "Could not dissolve faces",
    "Could not dissolve vertices",
    "Tessellation error",
    "Can not deal with non-manifold geometry",
    "Invalid selection",
    "Internal mesh error",
}
Definition at line 50 of file bmesh_operators.c.
Referenced by BMO_error_raise().
const int BMO_OPSLOT_TYPEINFO[BMO_OP_SLOT_TOTAL_TYPES]
Initial value:
 {
    0,
    sizeof(int),
    sizeof(int),
    sizeof(float),
    sizeof(void *),
    sizeof(void *),
    0,
    0,
    sizeof(float) * 3,
    sizeof(void *),
    sizeof(BMOElemMapping)
}
Definition at line 66 of file bmesh_operators.c.
Referenced by bmo_slot_buffer_alloc(), BMO_slot_buffer_append(), and BMO_slot_copy().
BMOpSlot BMOpEmptySlot = {0} [static]
Definition at line 81 of file bmesh_operators.c.
Referenced by BMO_slot_get().