Blender: node_texture_valToRgb.c File Reference
node_texture_valToRgb.c File Reference
texnodes
#include "node_texture_util.h"
#include "NOD_texture.h"
Functions
static void valtorgb_colorfn (float *out, TexParams *p, bNode *node, bNodeStack **in, short thread)
static void valtorgb_exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static void valtorgb_init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_tex_valtorgb (bNodeTreeType *ttype)
static void rgbtobw_valuefn (float *out, TexParams *p, bNode *UNUSED(node), bNodeStack **in, short thread)
static void rgbtobw_exec (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_tex_rgbtobw (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate valtorgb_in []
static bNodeSocketTemplate valtorgb_out []
static bNodeSocketTemplate rgbtobw_in []
static bNodeSocketTemplate rgbtobw_out []
Detailed Description
Definition in file node_texture_valToRgb.c.
Function Documentation
void register_node_type_tex_rgbtobw (bNodeTreeType * ttype)
Definition at line 103 of file node_texture_valToRgb.c.
References NODE_CLASS_CONVERTOR, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), rgbtobw_exec(), and TEX_NODE_RGBTOBW.
Referenced by registerTextureNodes().
void register_node_type_tex_valtorgb (bNodeTreeType * ttype)
Definition at line 65 of file node_texture_valToRgb.c.
References NODE_CLASS_CONVERTOR, node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), TEX_NODE_VALTORGB, valtorgb_exec(), and valtorgb_init().
Referenced by registerTextureNodes().
static void rgbtobw_exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 98 of file node_texture_valToRgb.c.
References rgbtobw_valuefn(), and tex_output().
Referenced by register_node_type_tex_rgbtobw().
static void rgbtobw_valuefn (float * out, TexParams * p, bNode * UNUSEDnode, bNodeStack ** in, short thread) [static]
Definition at line 90 of file node_texture_valToRgb.c.
References tex_input_rgba().
Referenced by rgbtobw_exec().
static void valtorgb_colorfn (float * out, TexParams * p, bNode * node, bNodeStack ** in, short thread) [static]
Definition at line 46 of file node_texture_valToRgb.c.
References do_colorband(), bNode::storage, and tex_input_value().
Referenced by valtorgb_exec().
static void valtorgb_exec (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 55 of file node_texture_valToRgb.c.
References tex_output(), and valtorgb_colorfn().
Referenced by register_node_type_tex_valtorgb().
static void valtorgb_init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 60 of file node_texture_valToRgb.c.
References add_colorband(), and bNode::storage.
Referenced by register_node_type_tex_valtorgb().
Variable Documentation
bNodeSocketTemplate rgbtobw_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Color",          0.5f, 0.5f, 0.5f, 1.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 80 of file node_texture_valToRgb.c.
bNodeSocketTemplate rgbtobw_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Val",           0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 84 of file node_texture_valToRgb.c.
bNodeSocketTemplate valtorgb_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",           0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_texture_valToRgb.c.
bNodeSocketTemplate valtorgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_texture_valToRgb.c.