Blender: RAS_IRenderTools Class Reference
RAS_IRenderTools Class Reference
#include <RAS_IRenderTools.h>
Public Types
enum RAS_TEXT_RENDER_MODE { RAS_TEXT_RENDER_NODEF = 0, RAS_TEXT_NORMAL, RAS_TEXT_PADDED, RAS_TEXT_MAX }
Public Member Functions
RAS_IRenderTools ()
virtual ~RAS_IRenderTools ()
virtual void BeginFrame (RAS_IRasterizer *rasty)=0
virtual void EndFrame (RAS_IRasterizer *rasty)=0
virtual void applyTransform (class RAS_IRasterizer *rasty, double *oglmatrix, int drawingmode)=0
virtual void RenderText3D (int fontid, const char *text, int size, int dpi, float *color, double *mat, float aspect)=0
virtual void RenderText2D (RAS_TEXT_RENDER_MODE mode, const char *text, int xco, int yco, int width, int height)=0
virtual void RenderText (int mode, RAS_IPolyMaterial *polymat, float v1[3], float v2[3], float v3[3], float v4[3], int glattrib)=0
virtual void ProcessLighting (RAS_IRasterizer *rasty, bool uselights, const MT_Transform &trans)=0
virtual void SetClientObject (RAS_IRasterizer *rasty, void *obj)
void SetAuxilaryClientInfo (void *inf)
virtual void PushMatrix ()=0
virtual void PopMatrix ()=0
virtual void AddLight (struct RAS_LightObject *lightobject)
virtual void RemoveLight (struct RAS_LightObject *lightobject)
virtual void MotionBlur (RAS_IRasterizer *rasterizer)=0
Protected Attributes
void * m_clientobject
void * m_auxilaryClientInfo
std::vector< struct
RAS_LightObject * > m_lights
RAS_2DFilterManager m_filtermanager
Detailed Description
Definition at line 50 of file RAS_IRenderTools.h.
Member Enumeration Documentation
enum RAS_IRenderTools::RAS_TEXT_RENDER_MODE
Enumerator:
RAS_TEXT_RENDER_NODEF
RAS_TEXT_NORMAL
RAS_TEXT_PADDED
RAS_TEXT_MAX
Definition at line 62 of file RAS_IRenderTools.h.
Constructor & Destructor Documentation
RAS_IRenderTools::RAS_IRenderTools () [inline]
Definition at line 69 of file RAS_IRenderTools.h.
virtual RAS_IRenderTools::~RAS_IRenderTools () [inline, virtual]
Definition at line 76 of file RAS_IRenderTools.h.
Member Function Documentation
void RAS_IRenderTools::AddLight (struct RAS_LightObject * lightobject) [virtual]
Definition at line 46 of file RAS_IRenderTools.cpp.
References m_lights.
Referenced by KX_LightObject::GetReplica(), and KX_LightObject::KX_LightObject().
virtual void RAS_IRenderTools::applyTransform (class RAS_IRasterizer * rasty, double * oglmatrix, int drawingmode) [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by RAS_MaterialBucket::RenderMeshSlot().
virtual void RAS_IRenderTools::BeginFrame (RAS_IRasterizer * rasty) [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by KX_KetsjiEngine::BeginFrame(), ImageRender::Render(), and KX_KetsjiEngine::RenderDome().
virtual void RAS_IRenderTools::EndFrame (RAS_IRasterizer * rasty) [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by KX_KetsjiEngine::EndFrame().
virtual void RAS_IRenderTools::MotionBlur (RAS_IRasterizer * rasterizer) [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by KX_KetsjiEngine::RenderDome().
virtual void RAS_IRenderTools::PopMatrix () [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by RAS_MaterialBucket::RenderMeshSlot().
virtual void RAS_IRenderTools::ProcessLighting (RAS_IRasterizer * rasty, bool uselights, const MT_Transform & trans) [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by RAS_MaterialBucket::ActivateMaterial().
virtual void RAS_IRenderTools::PushMatrix () [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by RAS_MaterialBucket::RenderMeshSlot().
void RAS_IRenderTools::RemoveLight (struct RAS_LightObject * lightobject) [virtual]
Definition at line 51 of file RAS_IRenderTools.cpp.
References find(), and m_lights.
Referenced by KX_LightObject::~KX_LightObject().
virtual void RAS_IRenderTools::RenderText (int mode, RAS_IPolyMaterial * polymat, float v1[3], float v2[3], float v3[3], float v4[3], int glattrib) [pure virtual]
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by RAS_OpenGLRasterizer::IndexPrimitives_3DText().
virtual void RAS_IRenderTools::RenderText2D (RAS_TEXT_RENDER_MODE mode, const char * text, int xco, int yco, int width, int height) [pure virtual]
Renders 2D text string.
Parameters:
mode The type of text
text The string to render.
xco Position on the screen (origin in lower left corner).
yco Position on the screen (origin in lower left corner).
width Width of the canvas to draw to.
height Height of the canvas to draw to.
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
virtual void RAS_IRenderTools::RenderText3D (int fontid, const char * text, int size, int dpi, float * color, double * mat, float aspect) [pure virtual]
Renders 3D text string using BFL.
Parameters:
fontid The id of the font.
text The string to render.
size The size of the text.
dpi The resolution of the text.
color The color of the object.
mat The Matrix of the text object.
aspect A scaling factor to compensate for the size.
Implemented in KX_BlenderRenderTools, and GPC_RenderTools.
Referenced by KX_FontObject::DrawText().
void RAS_IRenderTools::SetAuxilaryClientInfo (void * inf)
Definition at line 41 of file RAS_IRenderTools.cpp.
References m_auxilaryClientInfo.
Referenced by KX_KetsjiEngine::Render(), ImageRender::Render(), and KX_KetsjiEngine::RenderDome().
void RAS_IRenderTools::SetClientObject (RAS_IRasterizer * rasty, void * obj) [virtual]
Reimplemented in KX_BlenderRenderTools, and GPC_RenderTools.
Definition at line 35 of file RAS_IRenderTools.cpp.
References m_clientobject.
Referenced by RAS_BucketManager::Renderbuckets().
Member Data Documentation
void* RAS_IRenderTools::m_auxilaryClientInfo [protected]
Definition at line 55 of file RAS_IRenderTools.h.
Referenced by KX_BlenderRenderTools::applyLights(), GPC_RenderTools::applyLights(), GPC_RenderTools::applyTransform(), KX_BlenderRenderTools::applyTransform(), KX_BlenderRenderTools::ProcessLighting(), GPC_RenderTools::ProcessLighting(), and SetAuxilaryClientInfo().
void* RAS_IRenderTools::m_clientobject [protected]
Definition at line 54 of file RAS_IRenderTools.h.
Referenced by GPC_RenderTools::applyTransform(), KX_BlenderRenderTools::applyTransform(), GPC_RenderTools::BeginFrame(), KX_BlenderRenderTools::BeginFrame(), KX_BlenderRenderTools::ProcessLighting(), GPC_RenderTools::ProcessLighting(), KX_BlenderRenderTools::RenderText(), GPC_RenderTools::RenderText(), GPC_RenderTools::SetClientObject(), SetClientObject(), and KX_BlenderRenderTools::SetClientObject().
RAS_2DFilterManager RAS_IRenderTools::m_filtermanager [protected]
Definition at line 59 of file RAS_IRenderTools.h.
std::vector<struct RAS_LightObject*> RAS_IRenderTools::m_lights [protected]
Definition at line 57 of file RAS_IRenderTools.h.
Referenced by AddLight(), KX_BlenderRenderTools::applyLights(), GPC_RenderTools::applyLights(), and RemoveLight().
The documentation for this class was generated from the following files:
RAS_IRenderTools.h
RAS_IRenderTools.cpp