Blender: poselib.c File Reference
poselib.c File Reference
armature
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
#include "BLI_dlrbTree.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BKE_animsys.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_depsgraph.h"
#include "BKE_idprop.h"
#include "BKE_library.h"
#include "BKE_object.h"
#include "BKE_context.h"
#include "BKE_report.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "ED_anim_api.h"
#include "ED_armature.h"
#include "ED_keyframes_draw.h"
#include "ED_keyframing.h"
#include "ED_keyframes_edit.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "armature_intern.h"
Classes
struct tPoseLib_PreviewData
struct tPoseLib_Backup
Typedefs
typedef struct tPoseLib_PreviewData tPoseLib_PreviewData
typedef struct tPoseLib_Backup tPoseLib_Backup
Enumerations
enum {
PL_PREVIEW_ERROR = -1, PL_PREVIEW_RUNNING, PL_PREVIEW_CONFIRM, PL_PREVIEW_CANCEL,
PL_PREVIEW_RUNONCE
}
enum { PL_PREVIEW_NOREDRAW = 0, PL_PREVIEW_REDRAWALL, PL_PREVIEW_REDRAWHEADER }
enum { PL_PREVIEW_FIRSTTIME = (1<<0), PL_PREVIEW_SHOWORIGINAL = (1<<1) }
Functions
static void action_set_activemarker (void *UNUSED(a), void *UNUSED(b), void *UNUSED(c))
static int poselib_get_free_index (bAction *act)
static TimeMarker * poselib_get_active_pose (bAction *act)
static Object * get_poselib_object (bContext *C)
static int has_poselib_pose_data_poll (bContext *C)
static bAction * poselib_init_new (Object *ob)
static bAction * poselib_validate (Object *ob)
static int poselib_new_exec (bContext *C, wmOperator *UNUSED(op))
void POSELIB_OT_new (wmOperatorType *ot)
static int poselib_unlink_exec (bContext *C, wmOperator *UNUSED(op))
void POSELIB_OT_unlink (wmOperatorType *ot)
static int poselib_sanitise_exec (bContext *C, wmOperator *op)
void POSELIB_OT_action_sanitise (wmOperatorType *ot)
static void poselib_add_menu_invoke__replacemenu (bContext *C, uiLayout *layout, void *UNUSED(arg))
static int poselib_add_menu_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(evt))
static int poselib_add_exec (bContext *C, wmOperator *op)
void POSELIB_OT_pose_add (wmOperatorType *ot)
static EnumPropertyItem * poselib_stored_pose_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
static int poselib_remove_exec (bContext *C, wmOperator *op)
void POSELIB_OT_pose_remove (wmOperatorType *ot)
static int poselib_rename_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int poselib_rename_exec (bContext *C, wmOperator *op)
void POSELIB_OT_pose_rename (wmOperatorType *ot)
static void poselib_backup_posecopy (tPoseLib_PreviewData *pld)
static void poselib_backup_restore (tPoseLib_PreviewData *pld)
static void poselib_backup_free_data (tPoseLib_PreviewData *pld)
static void poselib_apply_pose (tPoseLib_PreviewData *pld)
static void poselib_keytag_pose (bContext *C, Scene *scene, tPoseLib_PreviewData *pld)
static void poselib_preview_apply (bContext *C, wmOperator *op)
static void poselib_preview_get_next (tPoseLib_PreviewData *pld, int step)
static void poselib_preview_handle_search (tPoseLib_PreviewData *pld, unsigned short event, char ascii)
static int poselib_preview_handle_event (bContext *UNUSED(C), wmOperator *op, wmEvent *event)
static void poselib_preview_init_data (bContext *C, wmOperator *op)
static void poselib_preview_cleanup (bContext *C, wmOperator *op)
static int poselib_preview_exit (bContext *C, wmOperator *op)
static int poselib_preview_cancel (bContext *C, wmOperator *op)
static int poselib_preview_modal (bContext *C, wmOperator *op, wmEvent *event)
static int poselib_preview_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int poselib_preview_exec (bContext *C, wmOperator *op)
void POSELIB_OT_browse_interactive (wmOperatorType *ot)
void POSELIB_OT_apply_pose (wmOperatorType *ot)
Detailed Description
Definition in file poselib.c.
Typedef Documentation
typedef struct tPoseLib_Backup tPoseLib_Backup
typedef struct tPoseLib_PreviewData tPoseLib_PreviewData
Enumeration Type Documentation
anonymous enum
Enumerator:
PL_PREVIEW_ERROR
PL_PREVIEW_RUNNING
PL_PREVIEW_CONFIRM
PL_PREVIEW_CANCEL
PL_PREVIEW_RUNONCE
Definition at line 747 of file poselib.c.
anonymous enum
Enumerator:
PL_PREVIEW_NOREDRAW
PL_PREVIEW_REDRAWALL
PL_PREVIEW_REDRAWHEADER
Definition at line 756 of file poselib.c.
anonymous enum
Enumerator:
PL_PREVIEW_FIRSTTIME
PL_PREVIEW_SHOWORIGINAL
Definition at line 763 of file poselib.c.
Function Documentation
static void action_set_activemarker (void * UNUSEDa, void * UNUSEDb, void * UNUSEDc) [static]
Definition at line 86 of file poselib.c.
Referenced by poselib_preview_cleanup().
static Object* get_poselib_object (bContext * C) [static]
Definition at line 164 of file poselib.c.
References CTX_data_active_object(), CTX_wm_area(), ED_object_context(), NULL, object_pose_armature_get(), SPACE_BUTS, and ScrArea::spacetype.
Referenced by has_poselib_pose_data_poll(), poselib_add_exec(), poselib_add_menu_invoke(), poselib_add_menu_invoke__replacemenu(), poselib_new_exec(), poselib_preview_init_data(), poselib_remove_exec(), poselib_rename_invoke(), poselib_sanitise_exec(), poselib_stored_pose_itemf(), and poselib_unlink_exec().
static int has_poselib_pose_data_poll (bContext * C) [static]
Definition at line 181 of file poselib.c.
References get_poselib_object(), and Object::poselib.
Referenced by POSELIB_OT_action_sanitise(), POSELIB_OT_apply_pose(), POSELIB_OT_browse_interactive(), POSELIB_OT_pose_remove(), POSELIB_OT_pose_rename(), and POSELIB_OT_unlink().
static int poselib_add_exec (bContext * C, wmOperator * op) [static]
Definition at line 435 of file poselib.c.
References bAction::active_marker, ANIM_apply_keyingset(), ANIM_builtin_keyingset_get_named(), ANIM_KS_WHOLE_CHARACTER_ID, BLI_addtail(), BLI_countlist(), BLI_strncpy(), BLI_uniquename(), ELEM, ListBase::first, get_poselib_object(), bAction::markers, MEM_callocN(), MODIFYKEY_MODE_INSERT, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::pose, poselib_validate(), wmOperator::ptr, RNA_int_get(), and RNA_string_get().
Referenced by POSELIB_OT_pose_add().
static int poselib_add_menu_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevt) [static]
Definition at line 399 of file poselib.c.
References CFRA, CTX_data_scene(), ELEM, ListBase::first, get_poselib_object(), if(), IFACE_, bAction::markers, wmOperatorType::name, NULL, OPERATOR_CANCELLED, Object::pose, Object::poselib, poselib_add_menu_invoke__replacemenu(), poselib_get_free_index(), wmOperator::type, uiItemIntO(), uiItemMenuF(), uiLayoutSetOperatorContext(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_OP_EXEC_DEFAULT.
Referenced by POSELIB_OT_pose_add().
static void poselib_add_menu_invoke__replacemenu (bContext * C, uiLayout * layout, void * UNUSEDarg) [static]
Definition at line 373 of file poselib.c.
References BLI_assert, ListBase::first, TimeMarker::frame, get_poselib_object(), bAction::markers, TimeMarker::name, TimeMarker::next, NULL, Object::poselib, RNA_int_set(), RNA_string_set(), UI_ITEM_O_RETURN_PROPS, uiItemFullO_ptr(), uiLayoutSetOperatorContext(), WM_OP_EXEC_DEFAULT, and WM_operatortype_find().
Referenced by poselib_add_menu_invoke().
static void poselib_apply_pose (tPoseLib_PreviewData * pld) [static]
Definition at line 857 of file poselib.c.
References tPoseLib_PreviewData::act, ALE_GROUP, ANIM_animchanneldata_keyframes_loop(), ANIM_editkeyframes_ok(), animsys_evaluate_action_group(), tPoseLib_PreviewData::arm, BEZT_OK_FRAMERANGE, bPoseChannel::bone, BONE_HIDDEN_P, BONE_SELECTED, KeyframeEditData::f1, KeyframeEditData::f2, ListBase::first, Bone::flag, TimeMarker::frame, get_pose_channel(), bAction::groups, bArmature::layer, Bone::layer, tPoseLib_PreviewData::marker, bActionGroup::name, bActionGroup::next, NULL, tPoseLib_Backup::pchan, tPoseLib_PreviewData::pose, tPoseLib_PreviewData::rna_ptr, and tPoseLib_PreviewData::selcount.
Referenced by poselib_preview_apply().
static void poselib_backup_free_data (tPoseLib_PreviewData * pld) [static]
Definition at line 832 of file poselib.c.
References tPoseLib_PreviewData::backups, BLI_freelinkN(), ListBase::first, IDP_FreeProperty(), MEM_freeN(), tPoseLib_Backup::next, and tPoseLib_Backup::oldprops.
Referenced by poselib_preview_cleanup().
static void poselib_backup_posecopy (tPoseLib_PreviewData * pld) [static]
Definition at line 781 of file poselib.c.
References tPoseLib_PreviewData::act, tPoseLib_PreviewData::backups, BLI_addtail(), bPoseChannel::bone, BONE_SELECTED, ListBase::first, Bone::flag, get_pose_channel(), bAction::groups, IDP_CopyProperty(), MEM_callocN(), bActionGroup::name, bActionGroup::next, tPoseLib_Backup::olddata, tPoseLib_Backup::oldprops, tPoseLib_Backup::pchan, tPoseLib_PreviewData::pose, bPoseChannel::prop, tPoseLib_PreviewData::selcount, and tPoseLib_PreviewData::totcount.
Referenced by poselib_preview_init_data().
static void poselib_backup_restore (tPoseLib_PreviewData * pld) [static]
Definition at line 815 of file poselib.c.
References tPoseLib_PreviewData::backups, ListBase::first, IDP_SyncGroupValues(), tPoseLib_Backup::next, tPoseLib_Backup::olddata, tPoseLib_Backup::oldprops, tPoseLib_Backup::pchan, and bPoseChannel::prop.
Referenced by poselib_preview_apply(), and poselib_preview_cleanup().
static TimeMarker* poselib_get_active_pose (bAction * act) [static]
Definition at line 154 of file poselib.c.
References bAction::active_marker, BLI_findlink(), bAction::markers, and NULL.
Referenced by poselib_preview_init_data().
static int poselib_get_free_index (bAction * act) [static]
Definition at line 111 of file poselib.c.
References ELEM, ListBase::first, TimeMarker::frame, bAction::markers, TimeMarker::next, and NULL.
Referenced by poselib_add_menu_invoke().
static bAction* poselib_init_new (Object * ob) [static]
Definition at line 190 of file poselib.c.
References add_empty_action(), ELEM, bAction::id, id_us_min(), NULL, Object::pose, and Object::poselib.
Referenced by poselib_new_exec(), and poselib_validate().
static void poselib_keytag_pose (bContext * C, Scene * scene, tPoseLib_PreviewData * pld) [static]
Definition at line 914 of file poselib.c.
References tPoseLib_PreviewData::act, ANIM_apply_keyingset(), ANIM_get_keyingset_for_autokeying(), ANIM_KS_WHOLE_CHARACTER_ID, ANIM_relative_keyingset_add_source(), autokeyframe_cfra_can_key(), BLI_freelistN(), bPoseChannel::bone, BONE_SELECTED, BONE_UNKEYED, CFRA, ListBase::first, Bone::flag, get_pose_channel(), bAction::groups, Object::id, MODIFYKEY_MODE_INSERT, NA_EDITED, bActionGroup::name, NC_ANIMATION, ND_KEYFRAME, bActionGroup::next, NULL, tPoseLib_PreviewData::ob, tPoseLib_Backup::pchan, tPoseLib_PreviewData::pose, RNA_PoseBone, tPoseLib_PreviewData::selcount, and WM_event_add_notifier().
Referenced by poselib_preview_cleanup().
static int poselib_new_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 218 of file poselib.c.
References get_poselib_object(), NC_OBJECT, ND_POSE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, poselib_init_new(), and WM_event_add_notifier().
Referenced by POSELIB_OT_new().
void POSELIB_OT_action_sanitise (wmOperatorType * ot)
Definition at line 356 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and poselib_sanitise_exec().
Referenced by ED_operatortypes_armature().
void POSELIB_OT_apply_pose (wmOperatorType * ot)
Definition at line 1649 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_preview_exec(), wmOperatorType::prop, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_browse_interactive (wmOperatorType * ot)
Definition at line 1623 of file poselib.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_preview_cancel(), poselib_preview_exec(), poselib_preview_invoke(), poselib_preview_modal(), wmOperatorType::prop, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_new (wmOperatorType * ot)
Definition at line 235 of file poselib.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and poselib_new_exec().
Referenced by ED_operatortypes_armature().
void POSELIB_OT_pose_add (wmOperatorType * ot)
Definition at line 486 of file poselib.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_add_exec(), poselib_add_menu_invoke(), RNA_def_int(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_pose_remove (wmOperatorType * ot)
Definition at line 600 of file poselib.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_remove_exec(), poselib_stored_pose_itemf(), wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSELIB_OT_pose_rename (wmOperatorType * ot)
Definition at line 687 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_rename_exec(), poselib_rename_invoke(), poselib_stored_pose_itemf(), wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_unlink (wmOperatorType * ot)
Definition at line 270 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and poselib_unlink_exec().
Referenced by ED_operatortypes_armature().
static void poselib_preview_apply (bContext * C, wmOperator * op) [static]
Definition at line 961 of file poselib.c.
References tPoseLib_PreviewData::act, tPoseLib_PreviewData::arm, ARM_DELAYDEFORM, BLI_findindex(), BLI_snprintf(), BLI_strncpy(), wmOperator::customdata, DAG_id_tag_update(), ED_area_headerprint(), bArmature::flag, tPoseLib_PreviewData::flag, tPoseLib_PreviewData::headerstr, Object::id, if(), tPoseLib_PreviewData::marker, bAction::markers, TimeMarker::name, NC_OBJECT, ND_POSE, tPoseLib_PreviewData::ob, OB_RECALC_DATA, PL_PREVIEW_FIRSTTIME, PL_PREVIEW_NOREDRAW, PL_PREVIEW_REDRAWALL, PL_PREVIEW_RUNNING, PL_PREVIEW_SHOWORIGINAL, poselib_apply_pose(), poselib_backup_restore(), wmOperator::ptr, tPoseLib_PreviewData::redraw, RNA_int_set(), tPoseLib_PreviewData::sa, tPoseLib_PreviewData::scene, tPoseLib_PreviewData::search_cursor, tPoseLib_PreviewData::searchstr, tPoseLib_PreviewData::state, where_is_pose(), and WM_event_add_notifier().
Referenced by poselib_preview_exec(), poselib_preview_invoke(), and poselib_preview_modal().
static int poselib_preview_cancel (bContext * C, wmOperator * op) [static]
Definition at line 1543 of file poselib.c.
References OPERATOR_CANCELLED, and poselib_preview_exit().
Referenced by POSELIB_OT_browse_interactive().
static void poselib_preview_cleanup (bContext * C, wmOperator * op) [static]
Definition at line 1470 of file poselib.c.
References tPoseLib_PreviewData::act, action_set_activemarker(), tPoseLib_PreviewData::arm, ARM_DELAYDEFORM, BLI_findindex(), BLI_freelistN(), wmOperator::customdata, DAG_id_tag_update(), ED_area_headerprint(), IS_AUTOKEY_MODE, tPoseLib_PreviewData::marker, MEM_freeN(), NULL, tPoseLib_PreviewData::ob, OB_RECALC_DATA, PL_PREVIEW_CANCEL, PL_PREVIEW_CONFIRM, tPoseLib_PreviewData::pose, POSE_DO_UNLOCK, poselib_backup_free_data(), poselib_backup_restore(), poselib_keytag_pose(), tPoseLib_PreviewData::sa, tPoseLib_PreviewData::scene, tPoseLib_PreviewData::searchp, tPoseLib_PreviewData::state, and where_is_pose().
Referenced by poselib_preview_exec(), poselib_preview_exit(), and poselib_preview_invoke().
static int poselib_preview_exec (bContext * C, wmOperator * op) [static]
Definition at line 1594 of file poselib.c.
References wmOperator::customdata, if(), OPERATOR_CANCELLED, PL_PREVIEW_CONFIRM, PL_PREVIEW_ERROR, PL_PREVIEW_RUNONCE, poselib_preview_apply(), poselib_preview_cleanup(), poselib_preview_exit(), poselib_preview_init_data(), and tPoseLib_PreviewData::state.
Referenced by POSELIB_OT_apply_pose(), and POSELIB_OT_browse_interactive().
static int poselib_preview_exit (bContext * C, wmOperator * op) [static]
Definition at line 1528 of file poselib.c.
References wmOperator::customdata, ELEM, OPERATOR_CANCELLED, OPERATOR_FINISHED, PL_PREVIEW_CANCEL, PL_PREVIEW_ERROR, poselib_preview_cleanup(), and tPoseLib_PreviewData::state.
Referenced by poselib_preview_cancel(), poselib_preview_exec(), and poselib_preview_modal().
static void poselib_preview_get_next (tPoseLib_PreviewData * pld, int step) [static]
Definition at line 1045 of file poselib.c.
References tPoseLib_PreviewData::act, BLI_addtail(), BLI_freelistN(), BLI_strcasestr(), LinkData::data, ListBase::first, ListBase::last, tPoseLib_PreviewData::marker, bAction::markers, MEM_callocN(), TimeMarker::name, next, LinkData::next, TimeMarker::next, NULL, TimeMarker::prev, LinkData::prev, tPoseLib_PreviewData::searchold, tPoseLib_PreviewData::searchp, tPoseLib_PreviewData::searchstr, and step().
Referenced by poselib_preview_handle_event(), and poselib_preview_handle_search().
static int poselib_preview_handle_event (bContext * UNUSEDC, wmOperator * op, wmEvent * event) [static]
Definition at line 1196 of file poselib.c.
References tPoseLib_PreviewData::act, bAction::active_marker, wmEvent::ascii, BLI_countlist(), BLI_strncpy(), wmOperator::customdata, DOWNARROWKEY, ELEM, ENDKEY, ESCKEY, ListBase::first, tPoseLib_PreviewData::flag, HOMEKEY, KM_NOTHING, KM_PRESS, ListBase::last, LEFTARROWKEY, LEFTMOUSE, tPoseLib_PreviewData::marker, bAction::markers, MIDDLEMOUSE, MOUSEMOVE, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, PAD0, PAD1, PAD2, PAD3, PAD4, PAD5, PAD6, PAD7, PAD8, PAD9, PADENTER, PADMINUS, PADPLUSKEY, PAGEDOWNKEY, PAGEUPKEY, PL_PREVIEW_CANCEL, PL_PREVIEW_CONFIRM, PL_PREVIEW_REDRAWALL, PL_PREVIEW_REDRAWHEADER, PL_PREVIEW_SHOWORIGINAL, poselib_preview_get_next(), poselib_preview_handle_search(), tPoseLib_PreviewData::redraw, RETKEY, RIGHTARROWKEY, RIGHTMOUSE, tPoseLib_PreviewData::search_cursor, tPoseLib_PreviewData::searchold, tPoseLib_PreviewData::searchstr, SPACEKEY, tPoseLib_PreviewData::state, strlen(), TABKEY, wmEvent::type, UPARROWKEY, wmEvent::val, WHEELDOWNMOUSE, and WHEELUPMOUSE.
Referenced by poselib_preview_modal().
static void poselib_preview_handle_search (tPoseLib_PreviewData * pld, unsigned short event, char ascii) [static]
Definition at line 1135 of file poselib.c.
References BACKSPACEKEY, DELKEY, i, len(), PL_PREVIEW_REDRAWALL, poselib_preview_get_next(), tPoseLib_PreviewData::redraw, tPoseLib_PreviewData::search_cursor, tPoseLib_PreviewData::searchstr, and strlen().
Referenced by poselib_preview_handle_event().
static void poselib_preview_init_data (bContext * C, wmOperator * op) [static]
Definition at line 1397 of file poselib.c.
References tPoseLib_PreviewData::act, tPoseLib_PreviewData::arm, BKE_report(), BLI_findlink(), CTX_data_scene(), CTX_wm_area(), wmOperator::customdata, Object::data, ELEM3, ListBase::first, bPose::flag, tPoseLib_PreviewData::flag, get_poselib_object(), tPoseLib_PreviewData::headerstr, Object::id, tPoseLib_PreviewData::marker, bAction::markers, MEM_callocN(), NULL, tPoseLib_PreviewData::ob, PL_PREVIEW_ERROR, PL_PREVIEW_FIRSTTIME, PL_PREVIEW_REDRAWALL, PL_PREVIEW_RUNNING, PL_PREVIEW_SHOWORIGINAL, Object::pose, tPoseLib_PreviewData::pose, POSE_DO_UNLOCK, POSE_LOCKED, Object::poselib, poselib_backup_posecopy(), poselib_get_active_pose(), wmOperator::ptr, tPoseLib_PreviewData::redraw, wmOperator::reports, RNA_id_pointer_create(), RNA_int_get(), tPoseLib_PreviewData::rna_ptr, RPT_ERROR, RPT_WARNING, tPoseLib_PreviewData::sa, tPoseLib_PreviewData::scene, tPoseLib_PreviewData::search_cursor, tPoseLib_PreviewData::searchold, tPoseLib_PreviewData::searchstr, and tPoseLib_PreviewData::state.
Referenced by poselib_preview_exec(), and poselib_preview_invoke().
static int poselib_preview_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1570 of file poselib.c.
References wmOperator::customdata, if(), OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, PL_PREVIEW_ERROR, poselib_preview_apply(), poselib_preview_cleanup(), poselib_preview_init_data(), tPoseLib_PreviewData::state, and WM_event_add_modal_handler().
Referenced by POSELIB_OT_browse_interactive().
static int poselib_preview_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1550 of file poselib.c.
References wmOperator::customdata, PL_PREVIEW_RUNNING, poselib_preview_apply(), poselib_preview_exit(), poselib_preview_handle_event(), tPoseLib_PreviewData::redraw, and tPoseLib_PreviewData::state.
Referenced by POSELIB_OT_browse_interactive().
static int poselib_remove_exec (bContext * C, wmOperator * op) [static]
Definition at line 539 of file poselib.c.
References bAction::active_marker, BKE_report(), BKE_reportf(), BLI_findlink(), BLI_freelinkN(), bAction::curves, delete_fcurve_key(), ListBase::first, get_poselib_object(), i, if(), IS_EQ, bAction::markers, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::poselib, wmOperator::ptr, wmOperator::reports, RNA_property_enum_get(), RNA_property_is_set(), RNA_struct_find_property(), RPT_ERROR, BezTriple::vec, and WM_event_add_notifier().
Referenced by POSELIB_OT_pose_remove().
static int poselib_rename_exec (bContext * C, wmOperator * op) [static]
Definition at line 651 of file poselib.c.
References BKE_report(), BLI_findlink(), BLI_strncpy(), BLI_uniquename(), CTX_data_active_object(), if(), bAction::markers, NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, object_pose_armature_get(), OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::poselib, wmOperator::ptr, wmOperator::reports, RNA_int_get(), RNA_string_get(), RPT_ERROR, and WM_event_add_notifier().
Referenced by POSELIB_OT_pose_rename().
static int poselib_rename_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 623 of file poselib.c.
References bAction::active_marker, BKE_report(), BLI_findlink(), get_poselib_object(), if(), bAction::markers, NULL, OPERATOR_CANCELLED, Object::poselib, wmOperator::ptr, wmOperator::reports, RNA_enum_set(), RNA_string_set(), RPT_ERROR, and WM_operator_props_popup().
Referenced by POSELIB_OT_pose_rename().
static int poselib_sanitise_exec (bContext * C, wmOperator * op) [static]
Definition at line 291 of file poselib.c.
References action_to_keylist(), BKE_report(), BLI_addtail(), BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), BLI_freelinkN(), BLI_strncpy(), ListBase::first, get_poselib_object(), if(), IS_EQ, bAction::markers, MEM_callocN(), NA_EDITED, NC_ANIMATION, ND_KEYFRAME, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::poselib, wmOperator::reports, RPT_WARNING, and WM_event_add_notifier().
Referenced by POSELIB_OT_action_sanitise().
static EnumPropertyItem* poselib_stored_pose_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 509 of file poselib.c.
References get_poselib_object(), NULL, and Object::poselib.
Referenced by POSELIB_OT_pose_remove(), and POSELIB_OT_pose_rename().
static int poselib_unlink_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 252 of file poselib.c.
References ELEM, get_poselib_object(), bAction::id, id_us_min(), NC_OBJECT, ND_POSE, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::poselib, and WM_event_add_notifier().
Referenced by POSELIB_OT_unlink().
static bAction* poselib_validate (Object * ob) [static]
Definition at line 205 of file poselib.c.
References ELEM, NULL, Object::pose, Object::poselib, and poselib_init_new().
Referenced by poselib_add_exec().