Blender: interface_anim.c File Reference
interface_anim.c File Reference
interface
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_string_utf8.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_animsys.h"
#include "BKE_fcurve.h"
#include "BKE_global.h"
#include "ED_keyframing.h"
#include "UI_interface.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "interface_intern.h"
Functions
static FCurve * ui_but_get_fcurve (uiBut *but, bAction **action, int *driven)
void ui_but_anim_flag (uiBut *but, float cfra)
int ui_but_anim_expression_get (uiBut *but, char *str, size_t maxlen)
int ui_but_anim_expression_set (uiBut *but, const char *str)
int ui_but_anim_expression_create (uiBut *but, const char *str)
void ui_but_anim_autokey (bContext *C, uiBut *but, Scene *scene, float cfra)
void ui_but_anim_insert_keyframe (bContext *C)
void ui_but_anim_delete_keyframe (bContext *C)
void ui_but_anim_add_driver (bContext *C)
void ui_but_anim_remove_driver (bContext *C)
void ui_but_anim_copy_driver (bContext *C)
void ui_but_anim_paste_driver (bContext *C)
void ui_but_anim_add_keyingset (bContext *C)
void ui_but_anim_remove_keyingset (bContext *C)
Detailed Description
Definition in file interface_anim.c.
Function Documentation
void ui_but_anim_add_driver (bContext * C)
Definition at line 215 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_add_keyingset (bContext * C)
Definition at line 239 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_autokey (bContext * C, uiBut * but, Scene * scene, float cfra)
Definition at line 179 of file interface_anim.c.
References ANIM_get_keyframing_flags(), FCurve::array_index, autokeyframe_cfra_can_key(), CTX_wm_reports(), PointerRNA::data, FCURVE_SELECTED, FCurve::flag, FCurve::grp, PointerRNA::id, insert_keyframe(), NA_EDITED, bActionGroup::name, NC_ANIMATION, ND_KEYFRAME, NULL, FCurve::rna_path, uiBut::rnapoin, ui_but_get_fcurve(), and WM_event_add_notifier().
Referenced by ui_apply_autokey_undo().
void ui_but_anim_copy_driver (bContext * C)
Definition at line 227 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
void ui_but_anim_delete_keyframe (bContext * C)
Definition at line 209 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
int ui_but_anim_expression_create (uiBut * but, const char * str)
Definition at line 128 of file interface_anim.c.
References BLI_strncpy_utf8(), uiBut::block, C, PointerRNA::data, FCurve::driver, DRIVER_FLAG_RECOMPILE, DRIVER_TYPE_PYTHON, ELEM, uiBlock::evil_C, ChannelDriver::expression, ChannelDriver::flag, G, G_DEBUG, GS, PointerRNA::id, ID_MA, ID_TE, if(), MEM_freeN(), ID::name, NC_ANIMATION, ND_KEYFRAME, NULL, RNA_path_from_ID_to_property(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, ChannelDriver::type, verify_driver_fcurve(), and WM_event_add_notifier().
Referenced by ui_set_but_string().
int ui_but_anim_expression_get (uiBut * but, char * str, size_t maxlen)
Definition at line 85 of file interface_anim.c.
References BLI_strncpy(), FCurve::driver, DRIVER_TYPE_PYTHON, ChannelDriver::expression, NULL, ChannelDriver::type, and ui_but_get_fcurve().
Referenced by ui_get_but_string(), and ui_tooltip_create().
int ui_but_anim_expression_set (uiBut * but, const char * str)
Definition at line 105 of file interface_anim.c.
References BLI_strncpy_utf8(), uiBut::block, FCurve::driver, DRIVER_FLAG_RECOMPILE, DRIVER_TYPE_PYTHON, uiBlock::evil_C, ChannelDriver::expression, ChannelDriver::flag, NC_ANIMATION, ND_KEYFRAME, NULL, ChannelDriver::type, ui_but_get_fcurve(), and WM_event_add_notifier().
Referenced by ui_set_but_string().
void ui_but_anim_flag (uiBut * but, float cfra)
Definition at line 63 of file interface_anim.c.
References fcurve_frame_has_keyframe(), uiBut::flag, NULL, UI_BUT_ANIMATED, UI_BUT_ANIMATED_KEY, UI_BUT_DRIVEN, and ui_but_get_fcurve().
Referenced by uiContextAnimUpdate(), and uiEndBlock().
void ui_but_anim_insert_keyframe (bContext * C)
Definition at line 203 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_paste_driver (bContext * C)
Definition at line 233 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
void ui_but_anim_remove_driver (bContext * C)
Definition at line 221 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_remove_keyingset (bContext * C)
Definition at line 245 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
static FCurve* ui_but_get_fcurve (uiBut * but, bAction ** action, int * driven) [static]
Definition at line 58 of file interface_anim.c.
References rna_get_fcurve(), uiBut::rnaindex, uiBut::rnapoin, and uiBut::rnaprop.
Referenced by ui_but_anim_autokey(), ui_but_anim_expression_get(), ui_but_anim_expression_set(), and ui_but_anim_flag().