Blender: KX_PythonInit.cpp File Reference
KX_PythonInit.cpp File Reference
Ketsji
#include "GL/glew.h"
#include "KX_PythonInit.h"
#include <dirent.h>
#include <stdlib.h>
#include "KX_PyConstraintBinding.h"
#include "KX_KetsjiEngine.h"
#include "KX_RadarSensor.h"
#include "KX_RaySensor.h"
#include "KX_ArmatureSensor.h"
#include "KX_SceneActuator.h"
#include "KX_GameActuator.h"
#include "KX_ParentActuator.h"
#include "KX_SCA_DynamicActuator.h"
#include "KX_SteeringActuator.h"
#include "KX_NavMeshObject.h"
#include "SCA_IInputDevice.h"
#include "SCA_PropertySensor.h"
#include "SCA_RandomActuator.h"
#include "SCA_KeyboardSensor.h"
#include "SCA_PythonKeyboard.h"
#include "SCA_PythonMouse.h"
#include "KX_ConstraintActuator.h"
#include "KX_IpoActuator.h"
#include "KX_SoundActuator.h"
#include "KX_StateActuator.h"
#include "BL_ActionActuator.h"
#include "BL_ArmatureObject.h"
#include "RAS_IRasterizer.h"
#include "RAS_ICanvas.h"
#include "RAS_BucketManager.h"
#include "RAS_2DFilterManager.h"
#include "MT_Vector3.h"
#include "MT_Point3.h"
#include "ListValue.h"
#include "InputParser.h"
#include "KX_Scene.h"
#include "NG_NetworkScene.h"
#include "BL_Shader.h"
#include "BL_Action.h"
#include "KX_PyMath.h"
#include "PyObjectPlus.h"
#include "KX_PythonInitTypes.h"
#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "PHY_IPhysicsEnvironment.h"
#include "BKE_main.h"
#include "BKE_utildefines.h"
#include "BKE_global.h"
#include "BLI_blenlib.h"
#include "GPU_material.h"
#include "MEM_guardedalloc.h"
#include "KX_BlenderSceneConverter.h"
#include "KX_MeshProxy.h"
#include "BKE_idcode.h"
Functions
void KX_SetActiveScene (class KX_Scene *scene)
class KX_Scene * KX_GetActiveScene ()
class KX_KetsjiEngine * KX_GetActiveEngine ()
void KX_RasterizerDrawDebugLine (const MT_Vector3 &from, const MT_Vector3 &to, const MT_Vector3 &color)
void KX_RasterizerDrawDebugCircle (const MT_Vector3 &center, const MT_Scalar radius, const MT_Vector3 &color, const MT_Vector3 &normal, int nsector)
Variables
static KX_Scene * gp_KetsjiScene = NULL
static KX_KetsjiEngine * gp_KetsjiEngine = NULL
static RAS_IRasterizer * gp_Rasterizer = NULL
Detailed Description
Definition in file KX_PythonInit.cpp.
Function Documentation
class KX_KetsjiEngine* KX_GetActiveEngine ()
Definition at line 178 of file KX_PythonInit.cpp.
References gp_KetsjiEngine.
Referenced by ImageRender::ImageRender(), ImageViewport::ImageViewport(), BL_Action::Play(), and Texture_refresh().
class KX_Scene* KX_GetActiveScene ()
Definition at line 173 of file KX_PythonInit.cpp.
References gp_KetsjiScene.
Referenced by KX_NavMeshObject::BuildVertIndArrays(), KX_GameObject::GetActionManager(), KX_KetsjiEngine::NextFrame(), BL_Action::Play(), KX_NavMeshObject::ProcessReplica(), KX_GameObject::ProcessReplica(), KX_FontObject::ProcessReplica(), KX_SoundActuator::Update(), KX_ConstraintActuator::Update(), KX_ParentActuator::Update(), and KX_GameObject::~KX_GameObject().
void KX_RasterizerDrawDebugCircle (const MT_Vector3 & center, const MT_Scalar radius, const MT_Vector3 & color, const MT_Vector3 & normal, int nsector)
Definition at line 190 of file KX_PythonInit.cpp.
References RAS_IRasterizer::DrawDebugCircle().
Referenced by KX_ObstacleSimulation::DrawObstacles().
void KX_RasterizerDrawDebugLine (const MT_Vector3 & from, const MT_Vector3 & to, const MT_Vector3 & color)
Definition at line 184 of file KX_PythonInit.cpp.
References RAS_IRasterizer::DrawDebugLine().
Referenced by KX_NavMeshObject::DrawNavMesh(), KX_ObstacleSimulation::DrawObstacles(), KX_NavMeshObject::DrawPath(), and KX_SteeringActuator::Update().
void KX_SetActiveScene (class KX_Scene * scene)
Definition at line 168 of file KX_PythonInit.cpp.
Referenced by KX_KetsjiEngine::NextFrame().
Variable Documentation
KX_KetsjiEngine* gp_KetsjiEngine = NULL [static]
Definition at line 164 of file KX_PythonInit.cpp.
Referenced by KX_GetActiveEngine().
KX_Scene* gp_KetsjiScene = NULL [static]
Definition at line 163 of file KX_PythonInit.cpp.
Referenced by KX_GetActiveScene().
RAS_IRasterizer* gp_Rasterizer = NULL [static]
Definition at line 165 of file KX_PythonInit.cpp.