Blender: blf_py_api.c File Reference
blf_py_api.c File Reference
Python Generic
#include <Python.h>
#include "blf_py_api.h"
#include "../../blenfont/BLF_api.h"
#include "BLI_utildefines.h"
Functions
PyDoc_STRVAR (py_blf_position_doc,".. function:: position(fontid, x, y, z)\n""\n"" Set the position for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg x: X axis position to draw the text.\n"" :type x: float\n"" :arg y: Y axis position to draw the text.\n"" :type y: float\n"" :arg z: Z axis position to draw the text.\n"" :type z: float\n")
static PyObject * py_blf_position (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_size_doc,".. function:: size(fontid, size, dpi)\n""\n"" Set the size and dpi for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg size: Point size of the font.\n"" :type size: int\n"" :arg dpi: dots per inch value to use for drawing.\n"" :type dpi: int\n")
static PyObject * py_blf_size (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_aspect_doc,".. function:: aspect(fontid, aspect)\n""\n"" Set the aspect for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg aspect: The aspect ratio for text drawing to use.\n"" :type aspect: float\n")
static PyObject * py_blf_aspect (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_blur_doc,".. function:: blur(fontid, radius)\n""\n"" Set the blur radius for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg radius: The radius for blurring text (in pixels).\n"" :type radius: int\n")
static PyObject * py_blf_blur (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_draw_doc,".. function:: draw(fontid, text)\n""\n"" Draw text in the current context.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg text: the text to draw.\n"" :type text: string\n")
static PyObject * py_blf_draw (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_dimensions_doc,".. function:: dimensions(fontid, text)\n""\n"" Return the width and height of the text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg text: the text to draw.\n"" :type text: string\n"" :return: the width and height of the text.\n"" :rtype: tuple of 2 floats\n")
static PyObject * py_blf_dimensions (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_clipping_doc,".. function:: clipping(fontid, xmin, ymin, xmax, ymax)\n""\n"" Set the clipping, enable/disable using CLIPPING.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg xmin: Clip the drawing area by these bounds.\n"" :type xmin: float\n"" :arg ymin: Clip the drawing area by these bounds.\n"" :type ymin: float\n"" :arg xmax: Clip the drawing area by these bounds.\n"" :type xmax: float\n"" :arg ymax: Clip the drawing area by these bounds.\n"" :type ymax: float\n")
static PyObject * py_blf_clipping (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_disable_doc,".. function:: disable(fontid, option)\n""\n"" Disable option.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg option: One of ROTATION, CLIPPING, SHADOW or KERNING_DEFAULT.\n"" :type option: int\n")
static PyObject * py_blf_disable (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_enable_doc,".. function:: enable(fontid, option)\n""\n"" Enable option.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg option: One of ROTATION, CLIPPING, SHADOW or KERNING_DEFAULT.\n"" :type option: int\n")
static PyObject * py_blf_enable (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_rotation_doc,".. function:: rotation(fontid, angle)\n""\n"" Set the text rotation angle, enable/disable using ROTATION.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg angle: The angle for text drawing to use.\n"" :type angle: float\n")
static PyObject * py_blf_rotation (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_shadow_doc,".. function:: shadow(fontid, level, r, g, b, a)\n""\n"" Shadow options, enable/disable using SHADOW .\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg level: The blur level, can be 3, 5 or 0.\n"" :type level: int\n"" :arg r: Shadow color (red channel 0.0 - 1.0).\n"" :type r: float\n"" :arg g: Shadow color (green channel 0.0 - 1.0).\n"" :type g: float\n"" :arg b: Shadow color (blue channel 0.0 - 1.0).\n"" :type b: float\n"" :arg a: Shadow color (alpha channel 0.0 - 1.0).\n"" :type a: float\n")
static PyObject * py_blf_shadow (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_shadow_offset_doc,".. function:: shadow_offset(fontid, x, y)\n""\n"" Set the offset for shadow text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load`, for default font use 0.\n"" :type fontid: int\n"" :arg x: Vertical shadow offset value in pixels.\n"" :type x: float\n"" :arg y: Horizontal shadow offset value in pixels.\n"" :type y: float\n")
static PyObject * py_blf_shadow_offset (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_load_doc,".. function:: load(filename)\n""\n"" Load a new font.\n""\n"" :arg filename: the filename of the font.\n"" :type filename: string\n"" :return: the new font's fontid or -1 if there was an error.\n"" :rtype: integer\n")
static PyObject * py_blf_load (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (py_blf_unload_doc,".. function:: unload(filename)\n""\n"" Unload an existing font.\n""\n"" :arg filename: the filename of the font.\n"" :type filename: string\n")
static PyObject * py_blf_unload (PyObject *UNUSED(self), PyObject *args)
PyDoc_STRVAR (BLF_doc,"This module provides access to blenders text drawing functions.")
PyObject * BPyInit_blf (void)
Variables
static PyMethodDef BLF_methods []
static struct PyModuleDef BLF_module_def
Detailed Description
This file defines the 'bgl' module, used for drawing text in OpenGL.
Definition in file blf_py_api.c.
Function Documentation
PyObject* BPyInit_blf (void)
Definition at line 421 of file blf_py_api.c.
References BLF_CLIPPING, BLF_KERNING_DEFAULT, BLF_ROTATION, and BLF_SHADOW.
static PyObject* py_blf_aspect (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 100 of file blf_py_api.c.
References BLF_aspect(), and NULL.
static PyObject* py_blf_blur (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 124 of file blf_py_api.c.
References BLF_blur(), and NULL.
static PyObject* py_blf_clipping (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 207 of file blf_py_api.c.
References BLF_clipping(), and NULL.
static PyObject* py_blf_dimensions (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 173 of file blf_py_api.c.
References BLF_width_and_height(), and NULL.
static PyObject* py_blf_disable (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 230 of file blf_py_api.c.
References BLF_disable(), and NULL.
static PyObject* py_blf_draw (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 147 of file blf_py_api.c.
References BLF_draw(), and NULL.
static PyObject* py_blf_enable (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 252 of file blf_py_api.c.
References BLF_enable(), and NULL.
static PyObject* py_blf_load (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 357 of file blf_py_api.c.
References BLF_load(), and NULL.
static PyObject* py_blf_position (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 51 of file blf_py_api.c.
References BLF_position(), and NULL.
static PyObject* py_blf_rotation (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 274 of file blf_py_api.c.
References angle(), BLF_rotation(), and NULL.
static PyObject* py_blf_shadow (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 305 of file blf_py_api.c.
References BLF_shadow(), g, and NULL.
static PyObject* py_blf_shadow_offset (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 335 of file blf_py_api.c.
References BLF_shadow_offset(), and NULL.
static PyObject* py_blf_size (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 77 of file blf_py_api.c.
References BLF_size(), NULL, and size().
static PyObject* py_blf_unload (PyObject * UNUSEDself, PyObject * args) [static]
Definition at line 375 of file blf_py_api.c.
References BLF_unload(), and NULL.
PyDoc_STRVAR (py_blf_position_doc , ".. function:: position(fontid, x, y, z)\n""\n"" Set the position for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg x:X axis position to draw the text.\n"":type x:float\n"":arg y:Y axis position to draw the text.\n"":type y:float\n"":arg z:Z axis position to draw the text.\n"":type z:float\n")
PyDoc_STRVAR (py_blf_disable_doc , ".. function:: disable(fontid, option)\n""\n"" Disable option.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg option:One of ROTATION, CLIPPING , SHADOW or KERNING_DEFAULT.\n"":type option:int\n")
PyDoc_STRVAR (py_blf_blur_doc , ".. function:: blur(fontid, radius)\n""\n"" Set the blur radius for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg radius:The radius for blurring text(in pixels).\n"":type radius:int\n")
PyDoc_STRVAR (py_blf_unload_doc , ".. function:: unload(filename)\n""\n"" Unload an existing font.\n""\n"" :arg filename: the filename of the font.\n"" :type filename: string\n")
PyDoc_STRVAR (py_blf_shadow_offset_doc , ".. function:: shadow_offset(fontid, x, y)\n""\n"" Set the offset for shadow text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg x:Vertical shadow offset value in pixels.\n"":type x:float\n"":arg y:Horizontal shadow offset value in pixels.\n"":type y:float\n")
PyDoc_STRVAR (py_blf_size_doc , ".. function:: size(fontid, size, dpi)\n""\n"" Set the size and dpi for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg size:Point size of the font.\n"":type size:int\n"":arg dpi:dots per inch value to use for drawing.\n"":type dpi:int\n")
PyDoc_STRVAR (py_blf_clipping_doc , ".. function:: clipping(fontid, xmin, ymin, xmax, ymax)\n""\n"" Set the clipping, enable/disable using CLIPPING.\n""\n"":arg fontid:The id of the typeface as returned by:func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg xmin:Clip the drawing area by these bounds.\n"":type xmin:float\n"":arg ymin:Clip the drawing area by these bounds.\n"":type ymin:float\n"":arg xmax:Clip the drawing area by these bounds.\n"":type xmax:float\n"":arg ymax:Clip the drawing area by these bounds.\n"":type ymax:float\n")
PyDoc_STRVAR (BLF_doc , "This module provides access to blenders text drawing functions.")
PyDoc_STRVAR (py_blf_load_doc , ".. function:: load(filename)\n""\n"" Load a new font.\n""\n"" :arg filename: the filename of the font.\n"" :type filename: string\n"" :return: the new font's fontid or -1 if there was an error.\n"" :rtype: integer\n")
PyDoc_STRVAR (py_blf_rotation_doc , ".. function:: rotation(fontid, angle)\n""\n"" Set the text rotation angle, enable/disable using ROTATION.\n""\n"":arg fontid:The id of the typeface as returned by:func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg angle:The angle for text drawing to use.\n"":type angle:float\n")
PyDoc_STRVAR (py_blf_dimensions_doc , ".. function:: dimensions(fontid, text)\n""\n"" Return the width and height of the text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg text:the text to draw.\n"":type text:string\n"":return:the width and height of the text.\n"":rtype:tuple of 2 floats\n")
PyDoc_STRVAR (py_blf_shadow_doc , ".. function:: shadow(fontid, level, r, g, b, a)\n""\n"" Shadow options, enable/disable using SHADOW.\n""\n"":arg fontid:The id of the typeface as returned by:func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg level:The blur level, can be 3, 5 or 0.\n"":type level:int\n"":arg r:Shadow color(red channel 0.0-1.0).\n"":type r:float\n"":arg g:Shadow color(green channel 0.0-1.0).\n"":type g:float\n"":arg b:Shadow color(blue channel 0.0-1.0).\n"":type b:float\n"":arg a:Shadow color(alpha channel 0.0-1.0).\n"":type a:float\n")
PyDoc_STRVAR (py_blf_aspect_doc , ".. function:: aspect(fontid, aspect)\n""\n"" Set the aspect for drawing text.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg aspect:The aspect ratio for text drawing to use.\n"":type aspect:float\n")
PyDoc_STRVAR (py_blf_enable_doc , ".. function:: enable(fontid, option)\n""\n"" Enable option.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg option:One of ROTATION, CLIPPING , SHADOW or KERNING_DEFAULT.\n"":type option:int\n")
PyDoc_STRVAR (py_blf_draw_doc , ".. function:: draw(fontid, text)\n""\n"" Draw text in the current context.\n""\n"" :arg fontid: The id of the typeface as returned by :func:`blf.load` , for default font use 0.\n"":type fontid:int\n"":arg text:the text to draw.\n"":type text:string\n")
Variable Documentation
PyMethodDef BLF_methods[] [static]
Initial value:
 {
    {"aspect", (PyCFunction) py_blf_aspect, METH_VARARGS, py_blf_aspect_doc},
    {"blur", (PyCFunction) py_blf_blur, METH_VARARGS, py_blf_blur_doc},
    {"clipping", (PyCFunction) py_blf_clipping, METH_VARARGS, py_blf_clipping_doc},
    {"disable", (PyCFunction) py_blf_disable, METH_VARARGS, py_blf_disable_doc},
    {"dimensions", (PyCFunction) py_blf_dimensions, METH_VARARGS, py_blf_dimensions_doc},
    {"draw", (PyCFunction) py_blf_draw, METH_VARARGS, py_blf_draw_doc},
    {"enable", (PyCFunction) py_blf_enable, METH_VARARGS, py_blf_enable_doc},
    {"position", (PyCFunction) py_blf_position, METH_VARARGS, py_blf_position_doc},
    {"rotation", (PyCFunction) py_blf_rotation, METH_VARARGS, py_blf_rotation_doc},
    {"shadow", (PyCFunction) py_blf_shadow, METH_VARARGS, py_blf_shadow_doc},
    {"shadow_offset", (PyCFunction) py_blf_shadow_offset, METH_VARARGS, py_blf_shadow_offset_doc},
    {"size", (PyCFunction) py_blf_size, METH_VARARGS, py_blf_size_doc},
    {"load", (PyCFunction) py_blf_load, METH_VARARGS, py_blf_load_doc},
    {"unload", (PyCFunction) py_blf_unload, METH_VARARGS, py_blf_unload_doc},
    {NULL, NULL, 0, NULL}
}
Definition at line 388 of file blf_py_api.c.
struct PyModuleDef BLF_module_def [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "blf",
    BLF_doc,
    0,
    BLF_methods,
    NULL,
    NULL,
    NULL,
    NULL,
}
Definition at line 409 of file blf_py_api.c.