Blender: AUD_SequencerEntry Class Reference
AUD_SequencerEntry Class Reference
#include <AUD_SequencerEntry.h>
Public Member Functions
AUD_SequencerEntry (AUD_Reference< AUD_IFactory > sound, float begin, float end, float skip, int id)
virtual ~AUD_SequencerEntry ()
void lock ()
void unlock ()
void setSound (AUD_Reference< AUD_IFactory > sound)
void move (float begin, float end, float skip)
void mute (bool mute)
int getID () const
AUD_AnimateableProperty * getAnimProperty (AUD_AnimateablePropertyType type)
void updateAll (float volume_max, float volume_min, float distance_max, float distance_reference, float attenuation, float cone_angle_outer, float cone_angle_inner, float cone_volume_outer)
bool isRelative ()
void setRelative (bool relative)
float getVolumeMaximum ()
void setVolumeMaximum (float volume)
float getVolumeMinimum ()
void setVolumeMinimum (float volume)
float getDistanceMaximum ()
void setDistanceMaximum (float distance)
float getDistanceReference ()
void setDistanceReference (float distance)
float getAttenuation ()
void setAttenuation (float factor)
float getConeAngleOuter ()
void setConeAngleOuter (float angle)
float getConeAngleInner ()
void setConeAngleInner (float angle)
float getConeVolumeOuter ()
void setConeVolumeOuter (float volume)
Friends
class AUD_SequencerHandle
Detailed Description
This class represents a sequenced entry in a sequencer factory.
Definition at line 42 of file AUD_SequencerEntry.h.
Constructor & Destructor Documentation
AUD_SequencerEntry::AUD_SequencerEntry (AUD_Reference< AUD_IFactory > sound, float begin, float end, float skip, int id)
Creates a new sequenced entry.
Parameters:
sound The sound this entry should play.
begin The start time.
end The end time or a negative value if determined by the sound.
skip How much seconds should be skipped at the beginning.
id The ID of the entry.
Definition at line 36 of file AUD_SequencerEntry.cpp.
References AUD_Quaternion::get(), and AUD_AnimateableProperty::write().
AUD_SequencerEntry::~AUD_SequencerEntry () [virtual]
Definition at line 73 of file AUD_SequencerEntry.cpp.
Member Function Documentation
AUD_AnimateableProperty * AUD_SequencerEntry::getAnimProperty (AUD_AnimateablePropertyType type)
Retrieves one of the animated properties of the entry.
Parameters:
type Which animated property to retrieve.
Returns:
A pointer to the animated property, valid as long as the entry is.
Definition at line 130 of file AUD_SequencerEntry.cpp.
References AUD_AP_LOCATION, AUD_AP_ORIENTATION, AUD_AP_PANNING, AUD_AP_PITCH, AUD_AP_VOLUME, and NULL.
float AUD_SequencerEntry::getAttenuation ()
Retrieves the attenuation of a source.
Returns:
The attenuation.
Definition at line 284 of file AUD_SequencerEntry.cpp.
float AUD_SequencerEntry::getConeAngleInner ()
Retrieves the inner angle of the cone of a source.
Returns:
The inner angle of the cone.
Definition at line 314 of file AUD_SequencerEntry.cpp.
float AUD_SequencerEntry::getConeAngleOuter ()
Retrieves the outer angle of the cone of a source.
Returns:
The outer angle of the cone.
Definition at line 299 of file AUD_SequencerEntry.cpp.
float AUD_SequencerEntry::getConeVolumeOuter ()
Retrieves the outer volume of the cone of a source. The volume between inner and outer angle is interpolated between inner volume and this value.
Returns:
The outer volume of the cone.
Definition at line 329 of file AUD_SequencerEntry.cpp.
float AUD_SequencerEntry::getDistanceMaximum ()
Retrieves the maximum distance of a source. If a source is further away from the reader than this distance, the volume will automatically be set to 0.
Returns:
The maximum distance.
Definition at line 254 of file AUD_SequencerEntry.cpp.
float AUD_SequencerEntry::getDistanceReference ()
Retrieves the reference distance of a source.
Returns:
The reference distance.
Definition at line 269 of file AUD_SequencerEntry.cpp.
int AUD_SequencerEntry::getID (void) const
Retrieves the ID of the entry.
Returns:
The ID of the entry.
Definition at line 125 of file AUD_SequencerEntry.cpp.
float AUD_SequencerEntry::getVolumeMaximum ()
Retrieves the maximum volume of a source.
Returns:
The maximum volume.
Definition at line 224 of file AUD_SequencerEntry.cpp.
float AUD_SequencerEntry::getVolumeMinimum ()
Retrieves the minimum volume of a source.
Returns:
The minimum volume.
Definition at line 239 of file AUD_SequencerEntry.cpp.
bool AUD_SequencerEntry::isRelative ()
Checks whether the source location, velocity and orientation are relative to the listener.
Returns:
Whether the source is relative.
Definition at line 206 of file AUD_SequencerEntry.cpp.
void AUD_SequencerEntry::lock ()
Locks the entry.
Definition at line 78 of file AUD_SequencerEntry.cpp.
Referenced by move(), mute(), setAttenuation(), setConeAngleInner(), setConeAngleOuter(), setConeVolumeOuter(), setDistanceMaximum(), setDistanceReference(), setRelative(), setSound(), setVolumeMaximum(), setVolumeMinimum(), and updateAll().
void AUD_SequencerEntry::move (float begin, float end, float skip)
Moves the entry.
Parameters:
begin The new start time.
end The new end time or a negative value if unknown.
skip How many seconds to skip at the beginning.
Definition at line 101 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
void AUD_SequencerEntry::mute (bool mute)
Sets the muting state of the entry.
Parameters:
mute Whether the entry should be muted or not.
Definition at line 116 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
void AUD_SequencerEntry::setAttenuation (float factor)
Sets the attenuation of a source. This value is used for distance calculation.
Parameters:
factor The new attenuation.
Returns:
Whether the action succeeded.
Definition at line 289 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
void AUD_SequencerEntry::setConeAngleInner (float angle)
Sets the inner angle of the cone of a source.
Parameters:
angle The new inner angle of the cone.
Returns:
Whether the action succeeded.
Definition at line 319 of file AUD_SequencerEntry.cpp.
References angle(), lock(), and unlock().
void AUD_SequencerEntry::setConeAngleOuter (float angle)
Sets the outer angle of the cone of a source.
Parameters:
angle The new outer angle of the cone.
Returns:
Whether the action succeeded.
Definition at line 304 of file AUD_SequencerEntry.cpp.
References angle(), lock(), and unlock().
void AUD_SequencerEntry::setConeVolumeOuter (float volume)
Sets the outer volume of the cone of a source. The volume between inner and outer angle is interpolated between inner volume and this value.
Parameters:
volume The new outer volume of the cone.
Returns:
Whether the action succeeded.
Definition at line 334 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
void AUD_SequencerEntry::setDistanceMaximum (float distance)
Sets the maximum distance of a source. If a source is further away from the reader than this distance, the volume will automatically be set to 0.
Parameters:
distance The new maximum distance.
Returns:
Whether the action succeeded.
Definition at line 259 of file AUD_SequencerEntry.cpp.
References distance(), lock(), and unlock().
void AUD_SequencerEntry::setDistanceReference (float distance)
Sets the reference distance of a source.
Parameters:
distance The new reference distance.
Returns:
Whether the action succeeded.
Definition at line 274 of file AUD_SequencerEntry.cpp.
References distance(), lock(), and unlock().
void AUD_SequencerEntry::setRelative (bool relative)
Sets whether the source location, velocity and orientation are relative to the listener.
Parameters:
relative Whether the source is relative.
Returns:
Whether the action succeeded.
Definition at line 211 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
void AUD_SequencerEntry::setSound (AUD_Reference< AUD_IFactory > sound)
Sets the sound of the entry.
Parameters:
sound The new sound.
Definition at line 88 of file AUD_SequencerEntry.cpp.
References AUD_Reference< T >::get(), lock(), and unlock().
void AUD_SequencerEntry::setVolumeMaximum (float volume)
Sets the maximum volume of a source.
Parameters:
volume The new maximum volume.
Returns:
Whether the action succeeded.
Definition at line 229 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
void AUD_SequencerEntry::setVolumeMinimum (float volume)
Sets the minimum volume of a source.
Parameters:
volume The new minimum volume.
Returns:
Whether the action succeeded.
Definition at line 244 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
void AUD_SequencerEntry::unlock ()
Unlocks the previously locked entry.
Definition at line 83 of file AUD_SequencerEntry.cpp.
Referenced by move(), mute(), setAttenuation(), setConeAngleInner(), setConeAngleOuter(), setConeVolumeOuter(), setDistanceMaximum(), setDistanceReference(), setRelative(), setSound(), setVolumeMaximum(), setVolumeMinimum(), and updateAll().
void AUD_SequencerEntry::updateAll (float volume_max, float volume_min, float distance_max, float distance_reference, float attenuation, float cone_angle_outer, float cone_angle_inner, float cone_volume_outer)
Updates all non-animated parameters of the entry.
Parameters:
volume_max The maximum volume.
volume_min The minimum volume.
distance_max The maximum distance.
distance_reference The reference distance.
attenuation The attenuation.
cone_angle_outer The outer cone opening angle.
cone_angle_inner The inner cone opening angle.
cone_volume_outer The volume outside the outer cone.
Definition at line 149 of file AUD_SequencerEntry.cpp.
References lock(), and unlock().
Friends And Related Function Documentation
friend class AUD_SequencerHandle [friend]
Definition at line 44 of file AUD_SequencerEntry.h.
The documentation for this class was generated from the following files:
AUD_SequencerEntry.h
AUD_SequencerEntry.cpp