Blender: BOP_Face Class Reference
BOP_Face Class Reference
#include <BOP_Face.h>
Public Member Functions
BOP_Face (MT_Plane3 plane, BOP_Index originalFace)
virtual ~BOP_Face ()
MT_Plane3 getPlane () const
void setPlane (const MT_Plane3 plane)
BOP_TAG getTAG () const
void setTAG (const BOP_TAG t)
BOP_Index getOriginalFace () const
void setOriginalFace (const BOP_Index originalFace)
BOP_Index getVertex (unsigned int i) const
void setVertex (const BOP_Index idx, const BOP_Index i)
unsigned int getSplit () const
void setSplit (const unsigned int i)
void invert ()
void setBBox (const MT_Point3 &p1, const MT_Point3 &p2, const MT_Point3 &p3)
BOP_BBox * getBBox ()
void freeBBox ()
unsigned int size () const
virtual bool getEdgeIndex (BOP_Index v1, BOP_Index v2, unsigned int &e)=0
virtual void replaceVertexIndex (BOP_Index oldIndex, BOP_Index newIndex)=0
virtual bool containsVertex (BOP_Index v)=0
Protected Attributes
BOP_Index m_indexs [4]
unsigned int m_size
unsigned int m_split
BOP_BBox * m_bbox
Detailed Description
Definition at line 49 of file BOP_Face.h.
Constructor & Destructor Documentation
BOP_Face::BOP_Face (MT_Plane3 plane, BOP_Index originalFace)
Constructs a new face.
Parameters:
plane face plane
originalFace index of the original face
Definition at line 44 of file BOP_Face.cpp.
References m_bbox, m_split, NULL, and UNCLASSIFIED.
virtual BOP_Face::~BOP_Face () [inline, virtual]
Definition at line 64 of file BOP_Face.h.
References m_bbox.
Member Function Documentation
virtual bool BOP_Face::containsVertex (BOP_Index v) [pure virtual]
Implemented in BOP_Face3, and BOP_Face4.
void BOP_Face::freeBBox () [inline]
Definition at line 80 of file BOP_Face.h.
References m_bbox, and NULL.
Referenced by BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC_split(), BOP_triangulateD_split(), BOP_triangulateE(), and BOP_triangulateF().
BOP_BBox* BOP_Face::getBBox () [inline]
Definition at line 79 of file BOP_Face.h.
References m_bbox.
Referenced by BOP_Face2Face().
virtual bool BOP_Face::getEdgeIndex (BOP_Index v1, BOP_Index v2, unsigned int & e) [pure virtual]
Implemented in BOP_Face3, and BOP_Face4.
Referenced by triangulate().
BOP_Index BOP_Face::getOriginalFace () const [inline]
Definition at line 69 of file BOP_Face.h.
Referenced by BOP_intersectCoplanarFaces(), BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC_split(), BOP_triangulateD_split(), BOP_triangulateE(), BOP_triangulateF(), and clean_nonmanifold().
MT_Plane3 BOP_Face::getPlane () const [inline]
Definition at line 65 of file BOP_Face.h.
Referenced by BOP_BSPTree::addFace(), BOP_createXS(), BOP_Face2Face(), BOP_intersectCoplanarFaces(), BOP_intersectNonCoplanarFaces(), BOP_meshFilter(), BOP_removeOverlappedFaces(), BOP_sew(), BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC_split(), BOP_triangulateD_split(), BOP_triangulateE(), BOP_triangulateF(), clean_nonmanifold(), BOP_BSPTree::filterFace(), and invert().
unsigned int BOP_Face::getSplit () const [inline]
Definition at line 73 of file BOP_Face.h.
References m_split.
Referenced by BOP_Face2Face(), BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC_split(), BOP_triangulateD_split(), BOP_triangulateE(), and BOP_triangulateF().
BOP_TAG BOP_Face::getTAG () const [inline]
Definition at line 67 of file BOP_Face.h.
Referenced by BOP_Face2Face(), BOP_getOppositeFace(), BOP_intersectCoplanarFaces(), BOP_mergeVertexs(), BOP_removeOverlappedFaces(), BOP_sew(), BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC_split(), BOP_triangulateD_split(), BOP_triangulateE(), and BOP_triangulateF().
BOP_Index BOP_Face::getVertex (unsigned int i) const [inline]
Definition at line 71 of file BOP_Face.h.
References i, and m_indexs.
Referenced by BOP_Mesh::addFace(), BOP_BSPTree::addFace(), BOP_addFace(), BOP_Face2Face(), BOP_intersectCoplanarFaces(), BOP_mergeVertexs(), BOP_meshFilter(), BOP_removeOverlappedFaces(), BOP_sew(), BOP_simplifiedMeshFilter(), BOP_splitEdge(), BOP_splitFace(), BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC(), BOP_triangulateD(), BOP_triangulateE(), BOP_triangulateF(), clean_nonmanifold(), deleteFace(), and BOP_Mesh::getEdge().
void BOP_Face::invert ()
Inverts this face.
Definition at line 56 of file BOP_Face.cpp.
References getPlane(), MT_Plane3::Invert(), and m_indexs.
virtual void BOP_Face::replaceVertexIndex (BOP_Index oldIndex, BOP_Index newIndex) [pure virtual]
Implemented in BOP_Face3, and BOP_Face4.
void BOP_Face::setBBox (const MT_Point3 & p1, const MT_Point3 & p2, const MT_Point3 & p3) [inline]
Definition at line 77 of file BOP_Face.h.
References m_bbox.
Referenced by BOP_Face2Face().
void BOP_Face::setOriginalFace (const BOP_Index originalFace) [inline]
Definition at line 70 of file BOP_Face.h.
void BOP_Face::setPlane (const MT_Plane3 plane) [inline]
Definition at line 66 of file BOP_Face.h.
void BOP_Face::setSplit (const unsigned int i) [inline]
Definition at line 74 of file BOP_Face.h.
References i, and m_split.
Referenced by BOP_Face2Face(), BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC_split(), BOP_triangulateD_split(), BOP_triangulateE(), and BOP_triangulateF().
void BOP_Face::setTAG (const BOP_TAG t) [inline]
Definition at line 68 of file BOP_Face.h.
Referenced by BOP_Mesh::addFace(), BOP_addFace(), BOP_mergeVertexs(), BOP_meshFilter(), BOP_removeOverlappedFaces(), BOP_simplifiedMeshFilter(), BOP_triangulateA(), BOP_triangulateB(), BOP_triangulateC_split(), BOP_triangulateD_split(), BOP_triangulateE(), BOP_triangulateF(), deleteFace(), and BOP_Face3::replaceVertexIndex().
void BOP_Face::setVertex (const BOP_Index idx, const BOP_Index i) [inline]
Definition at line 72 of file BOP_Face.h.
References i, and m_indexs.
unsigned int BOP_Face::size () const [inline]
Definition at line 82 of file BOP_Face.h.
References m_size.
Referenced by BOP_Mesh::addFace(), deleteFace(), and BOP_Mesh::getEdge().
Member Data Documentation
BOP_BBox* BOP_Face::m_bbox [protected]
Definition at line 60 of file BOP_Face.h.
Referenced by BOP_Face(), freeBBox(), getBBox(), setBBox(), and ~BOP_Face().
BOP_Index BOP_Face::m_indexs[4] [protected]
Definition at line 57 of file BOP_Face.h.
Referenced by BOP_Face3::BOP_Face3(), BOP_Face4::BOP_Face4(), BOP_Face4::containsVertex(), BOP_Face3::containsVertex(), BOP_Face3::getEdgeIndex(), BOP_Face4::getEdgeIndex(), BOP_Face3::getNeighbours(), BOP_Face4::getNeighbours(), BOP_Face4::getNextVertex(), BOP_Face3::getNextVertex(), BOP_Face4::getOppositeVertex(), BOP_Face4::getPreviousVertex(), BOP_Face3::getPreviousVertex(), getVertex(), invert(), BOP_Face3::replaceVertexIndex(), BOP_Face4::replaceVertexIndex(), and setVertex().
unsigned int BOP_Face::m_size [protected]
Definition at line 58 of file BOP_Face.h.
Referenced by BOP_Face3::BOP_Face3(), BOP_Face4::BOP_Face4(), and size().
unsigned int BOP_Face::m_split [protected]
Definition at line 59 of file BOP_Face.h.
Referenced by BOP_Face(), getSplit(), and setSplit().
The documentation for this class was generated from the following files:
BOP_Face.h
BOP_Face.cpp