Blender: Device Class Reference
Device Class Reference
#include <AUD_PyAPI.h>
Public Member Functions
virtual ~Device ()
virtual const string & error_message ()
virtual void mem_alloc (device_memory &mem, MemoryType type)=0
virtual void mem_copy_to (device_memory &mem)=0
virtual void mem_copy_from (device_memory &mem, int y, int w, int h, int elem)=0
virtual void mem_zero (device_memory &mem)=0
virtual void mem_free (device_memory &mem)=0
virtual void const_copy_to (const char *name, void *host, size_t size)=0
virtual void tex_alloc (const char *name, device_memory &mem, bool interpolation=false, bool periodic=false)
virtual void tex_free (device_memory &mem)
virtual void pixels_alloc (device_memory &mem)
virtual void pixels_copy_from (device_memory &mem, int y, int w, int h)
virtual void pixels_free (device_memory &mem)
virtual void * osl_memory ()
virtual bool load_kernels (bool experimental)
virtual void task_add (DeviceTask &task)=0
virtual void task_wait ()=0
virtual void task_cancel ()=0
virtual void draw_pixels (device_memory &mem, int y, int w, int h, int dy, int width, int height, bool transparent)
Static Public Member Functions
static Device * create (DeviceInfo &info, bool background=true, int threads=0)
static DeviceType type_from_string (const char *name)
static string string_from_type (DeviceType type)
static vector< DeviceType > & available_types ()
static vector< DeviceInfo > & available_devices ()
Public Attributes
PyObject_HEAD
AUD_Reference_AUD_IDevice * device
DeviceInfo info
Protected Member Functions
Device ()
Protected Attributes
bool background
string error_msg
Detailed Description
Definition at line 58 of file AUD_PyAPI.h.
Constructor & Destructor Documentation
Device::Device () [inline, protected]
Definition at line 98 of file device.h.
virtual Device::~Device () [inline, virtual]
Definition at line 104 of file device.h.
Member Function Documentation
vector< DeviceInfo > & Device::available_devices () [static]
Definition at line 255 of file device.cpp.
References clLibraryInit(), cuLibraryInit(), device_cpu_info(), device_cuda_info(), device_multi_info(), device_network_info(), and device_opencl_info().
Referenced by available_devices_func(), BlenderSync::get_session_params(), main(), and options_parse().
vector< DeviceType > & Device::available_types () [static]
Definition at line 224 of file device.cpp.
References clLibraryInit(), cuLibraryInit(), DEVICE_CPU, DEVICE_CUDA, DEVICE_MULTI, DEVICE_NETWORK, DEVICE_OPENCL, and types.
Referenced by main(), and options_parse().
virtual void Device::const_copy_to (const char * name, void * host, size_t size) [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by MultiDevice::const_copy_to(), Scene::device_update(), and dump_background_pixels().
Device * Device::create (DeviceInfo & info, bool background = true, int threads = 0) [static]
Definition at line 148 of file device.cpp.
References clLibraryInit(), cuLibraryInit(), device, DEVICE_CPU, device_cpu_create(), DEVICE_CUDA, device_cuda_create(), DEVICE_MULTI, device_multi_create(), DEVICE_NETWORK, device_network_create(), DEVICE_OPENCL, device_opencl_create(), info, NULL, and DeviceInfo::type.
Referenced by main(), MultiDevice::MultiDevice(), and Session::Session().
void Device::draw_pixels (device_memory & mem, int y, int w, int h, int dy, int width, int height, bool transparent) [virtual]
Reimplemented in CUDADevice, and MultiDevice.
Definition at line 121 of file device.cpp.
References device_memory::data_pointer, and pixels_copy_from().
Referenced by DisplayBuffer::draw(), and MultiDevice::draw_pixels().
virtual const string& Device::error_message () [inline, virtual]
Reimplemented in MultiDevice.
Definition at line 108 of file device.h.
References error_msg.
Referenced by MultiDevice::error_message(), Session::run(), Session::run_cpu(), and Session::run_gpu().
virtual bool Device::load_kernels (bool experimental) [inline, virtual]
Reimplemented in CUDADevice, and MultiDevice.
Definition at line 135 of file device.h.
Referenced by MultiDevice::load_kernels(), and Session::run().
virtual void Device::mem_alloc (device_memory & mem, MemoryType type) [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by MeshManager::displace(), dump_background_pixels(), MultiDevice::mem_alloc(), pixels_alloc(), and RenderBuffers::reset().
virtual void Device::mem_copy_from (device_memory & mem, int y, int w, int h, int elem) [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by RenderBuffers::copy_from_device(), MeshManager::displace(), dump_background_pixels(), MultiDevice::mem_copy_from(), and pixels_copy_from().
virtual void Device::mem_copy_to (device_memory & mem) [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by MeshManager::displace(), dump_background_pixels(), MultiDevice::mem_copy_to(), and RenderBuffers::reset().
virtual void Device::mem_free (device_memory & mem) [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by RenderBuffers::device_free(), MeshManager::displace(), dump_background_pixels(), MultiDevice::mem_free(), and pixels_free().
virtual void Device::mem_zero (device_memory & mem) [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by MultiDevice::mem_zero(), and RenderBuffers::reset().
virtual void* Device::osl_memory () [inline, virtual]
Reimplemented in CPUDevice.
Definition at line 132 of file device.h.
References NULL.
Referenced by MeshManager::update_osl_attributes().
void Device::pixels_alloc (device_memory & mem) [virtual]
Reimplemented in CUDADevice, and MultiDevice.
Definition at line 106 of file device.cpp.
References mem_alloc(), and MEM_READ_WRITE.
Referenced by MultiDevice::pixels_alloc(), and DisplayBuffer::reset().
void Device::pixels_copy_from (device_memory & mem, int y, int w, int h) [virtual]
Reimplemented in CUDADevice, and MultiDevice.
Definition at line 111 of file device.cpp.
References mem_copy_from().
Referenced by draw_pixels(), MultiDevice::pixels_copy_from(), and DisplayBuffer::write().
void Device::pixels_free (device_memory & mem) [virtual]
Reimplemented in CUDADevice, and MultiDevice.
Definition at line 116 of file device.cpp.
References mem_free().
Referenced by DisplayBuffer::device_free(), and MultiDevice::pixels_free().
string Device::string_from_type (DeviceType type) [static]
Definition at line 208 of file device.cpp.
References DEVICE_CPU, DEVICE_CUDA, DEVICE_MULTI, DEVICE_NETWORK, and DEVICE_OPENCL.
Referenced by main(), and options_parse().
virtual void Device::task_add (DeviceTask & task) [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by MeshManager::displace(), dump_background_pixels(), Session::path_trace(), MultiDevice::task_add(), and Session::tonemap().
virtual void Device::task_cancel () [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by Session::reset_cpu(), and MultiDevice::task_cancel().
virtual void Device::task_wait () [pure virtual]
Implemented in CPUDevice, CUDADevice, and MultiDevice.
Referenced by MeshManager::displace(), dump_background_pixels(), Session::run_cpu(), Session::run_gpu(), MultiDevice::task_wait(), and Session::tonemap().
virtual void Device::tex_alloc (const char * name, device_memory & mem, bool interpolation = false, bool periodic = false) [inline, virtual]
Reimplemented in CPUDevice, CUDADevice, and MultiDevice.
Definition at line 122 of file device.h.
Referenced by SVMShaderManager::device_update(), Filter::device_update(), Integrator::device_update(), MeshManager::device_update_attributes(), LightManager::device_update_background(), MeshManager::device_update_bvh(), ShaderManager::device_update_common(), LightManager::device_update_distribution(), MeshManager::device_update_mesh(), LightManager::device_update_points(), ObjectManager::device_update_transforms(), MultiDevice::tex_alloc(), and MeshManager::update_svm_attributes().
virtual void Device::tex_free (device_memory & mem) [inline, virtual]
Reimplemented in CPUDevice, CUDADevice, and MultiDevice.
Definition at line 124 of file device.h.
Referenced by MeshManager::device_free(), Integrator::device_free(), ObjectManager::device_free(), SVMShaderManager::device_free(), Filter::device_free(), LightManager::device_free(), ShaderManager::device_free_common(), and MultiDevice::tex_free().
DeviceType Device::type_from_string (const char * name) [static]
Definition at line 192 of file device.cpp.
References DEVICE_CPU, DEVICE_CUDA, DEVICE_MULTI, DEVICE_NETWORK, DEVICE_NONE, and DEVICE_OPENCL.
Referenced by main(), and options_parse().
Member Data Documentation
bool Device::background [protected]
Definition at line 100 of file device.h.
Referenced by CUDADevice::CUDADevice(), CUDADevice::draw_pixels(), CUDADevice::map_pixels(), MultiDevice::MultiDevice(), CUDADevice::pixels_alloc(), CUDADevice::pixels_copy_from(), CUDADevice::pixels_free(), and CUDADevice::unmap_pixels().
PyObject_HEAD AUD_Reference_AUD_IDevice* Device::device
Definition at line 60 of file AUD_PyAPI.h.
Referenced by create(), and MultiDevice::MultiDevice().
string Device::error_msg [protected]
Definition at line 101 of file device.h.
Referenced by CUDADevice::cuda_error(), MultiDevice::error_message(), and error_message().
DeviceInfo Device::info
Definition at line 107 of file device.h.
Referenced by create(), device_cuda_info(), SVMShaderManager::device_update(), and LightManager::device_update_points().
The documentation for this class was generated from the following files:
AUD_PyAPI.h
device.h
device.cpp