Blender: writeavi.c File Reference
writeavi.c File Reference
blenkernel
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "BKE_writeavi.h"
#include "AVI_avi.h"
#include "BKE_writeframeserver.h"
Functions
static int start_avi (Scene *scene, RenderData *rd, int rectx, int recty, ReportList *reports)
static void end_avi (void)
static int append_avi (RenderData *rd, int start_frame, int frame, int *pixels, int rectx, int recty, ReportList *reports)
static void filepath_avi (char *string, RenderData *rd)
bMovieHandle * BKE_get_movie_handle (const char imtype)
static int append_avi (RenderData *UNUSED(rd), int start_frame, int frame, int *pixels, int rectx, int recty, ReportList *UNUSED(reports))
void BKE_makeanimstring (char *string, RenderData *rd)
Variables
static AviMovie * avi = NULL
Detailed Description
Definition in file writeavi.c.
Function Documentation
static int append_avi (RenderData * rd, int start_frame, int frame, int * pixels, int rectx, int recty, ReportList * reports) [static]
Referenced by BKE_get_movie_handle().
static int append_avi (RenderData * UNUSEDrd, int start_frame, int frame, int * pixels, int rectx, int recty, ReportList * UNUSEDreports) [static]
Definition at line 185 of file writeavi.c.
References AVI_FORMAT_RGB32, AVI_write_frame(), MEM_mallocN(), and NULL.
bMovieHandle* BKE_get_movie_handle (const char imtype)
Definition at line 71 of file writeavi.c.
References append_avi(), append_frameserver(), bMovieHandle::append_movie, ELEM4, end_avi(), end_frameserver(), bMovieHandle::end_movie, filepath_avi(), frameserver_loop(), bMovieHandle::get_movie_path, bMovieHandle::get_next_frame, NULL, R_IMF_IMTYPE_AVICODEC, R_IMF_IMTYPE_FFMPEG, R_IMF_IMTYPE_FRAMESERVER, R_IMF_IMTYPE_H264, R_IMF_IMTYPE_QUICKTIME, R_IMF_IMTYPE_THEORA, R_IMF_IMTYPE_XVID, start_avi(), start_frameserver(), and bMovieHandle::start_movie.
Referenced by BKE_makeanimstring(), RE_BlenderAnim(), screen_opengl_render_anim_initialize(), and screenshot_startjob().
void BKE_makeanimstring (char * string, RenderData * rd)
Definition at line 231 of file writeavi.c.
References BKE_get_movie_handle(), bMovieHandle::get_movie_path, RenderData::im_format, and ImageFormatData::imtype.
static void end_avi (void) [static]
Definition at line 221 of file writeavi.c.
References AVI_close_compress(), MEM_freeN(), and NULL.
Referenced by BKE_get_movie_handle().
static void filepath_avi (char * string, RenderData * rd) [static]
Definition at line 126 of file writeavi.c.
References BLI_make_existing_file(), BLI_path_abs(), BLI_path_frame_range(), BLI_testextensie(), RenderData::efra, G, NULL, RenderData::pic, and RenderData::sfra.
Referenced by BKE_get_movie_handle(), and start_avi().
static int start_avi (Scene * scene, RenderData * rd, int rectx, int recty, ReportList * reports) [static]
Definition at line 141 of file writeavi.c.
References AVI_ERROR_NONE, AVI_FORMAT_AVI_RGB, AVI_FORMAT_MJPEG, AVI_open_compress(), AVI_OPTION_FRAMERATE, AVI_OPTION_HEIGHT, AVI_OPTION_QUALITY, AVI_OPTION_TYPE_MAIN, AVI_OPTION_WIDTH, AVI_set_compress_option(), BKE_report(), filepath_avi(), RenderData::frs_sec, RenderData::frs_sec_base, RenderData::im_format, ImageFormatData::imtype, _AviMovie::interlace, MEM_freeN(), MEM_mallocN(), NULL, _AviMovie::odd_fields, ImageFormatData::quality, R_IMF_IMTYPE_AVIJPEG, and RPT_ERROR.
Referenced by BKE_get_movie_handle().
Variable Documentation
AviMovie* avi = NULL [static]
Definition at line 124 of file writeavi.c.
Referenced by alloc_proxy_output_avi().