Blender: dds_api.h File Reference
dds_api.h File Reference
DDS
Functions
int imb_save_dds (struct ImBuf *ibuf, const char *name, int flags)
int imb_is_a_dds (unsigned char *mem)
struct ImBuf * imb_load_dds (unsigned char *mem, size_t size, int flags)
Detailed Description
Definition in file dds_api.h.
Function Documentation
int imb_is_a_dds (unsigned char * mem)
Definition at line 61 of file dds_api.cpp.
Referenced by imb_load_dds().
struct ImBuf* imb_load_dds (unsigned char * mem, size_t size, int flags) [read]
Definition at line 71 of file dds_api.cpp.
References Color32::a, Color32::b, Image::format(), Image::Format_ARGB, ImBuf::ftype, Color32::g, DirectDrawSurface::height(), i, IB_PROFILE_SRGB, IB_test, imb_addrectImBuf(), IMB_allocImBuf(), IMB_flipy(), imb_is_a_dds(), DirectDrawSurface::isSupported(), DirectDrawSurface::isValid(), DirectDrawSurface::mipmap(), Image::pixels(), DirectDrawSurface::printInfo(), ImBuf::profile, Color32::r, ImBuf::rect, and DirectDrawSurface::width().
int imb_save_dds (struct ImBuf * ibuf, const char * name, int flags)
Definition at line 43 of file dds_api.cpp.
References ImBuf::rect.