Blender: NM_Scalar< T > Class Template Reference
NM_Scalar< T > Class Template Reference
#include <NM_Scalar.h>
Public Member Functions
NM_Scalar ()
NM_Scalar (T value, T error=0.0)
T getValue () const
T getError () const
operator T () const
NM_Scalar operator- () const
NM_Scalar & operator= (T value)
NM_Scalar & operator+= (const NM_Scalar &x)
NM_Scalar & operator-= (const NM_Scalar &x)
NM_Scalar & operator*= (const NM_Scalar &x)
NM_Scalar & operator/= (const NM_Scalar &x)
Detailed Description
template<class T>
class NM_Scalar< T >
Definition at line 37 of file NM_Scalar.h.
Constructor & Destructor Documentation
template<class T> NM_Scalar< T >::NM_Scalar () [inline]
Definition at line 39 of file NM_Scalar.h.
template<class T> NM_Scalar< T >::NM_Scalar (T value, T error = 0.0) [inline, explicit]
Definition at line 40 of file NM_Scalar.h.
Member Function Documentation
template<class T> T NM_Scalar< T >::getError () const [inline]
Definition at line 44 of file NM_Scalar.h.
Referenced by acos(), cos(), fabs(), operator*(), operator+(), operator-(), operator/(), pow(), sin(), and sqrt().
template<class T> void Frame::getValue () const [inline]
Definition at line 43 of file NM_Scalar.h.
Referenced by acos(), cos(), fabs(), operator*(), operator+(), operator-(), operator/(), pow(), sin(), and sqrt().
template<class T> NM_Scalar< T >::operator T () const [inline]
Definition at line 46 of file NM_Scalar.h.
template<class T> NM_Scalar& NM_Scalar< T >::operator*= (const NM_Scalar< T > & x) [inline]
Definition at line 74 of file NM_Scalar.h.
template<class T> NM_Scalar& NM_Scalar< T >::operator+= (const NM_Scalar< T > & x) [inline]
Definition at line 58 of file NM_Scalar.h.
References fabs().
template<class T> NM_Scalar NM_Scalar< T >::operator- () const [inline]
Definition at line 48 of file NM_Scalar.h.
template<class T> NM_Scalar& NM_Scalar< T >::operator-= (const NM_Scalar< T > & x) [inline]
Definition at line 66 of file NM_Scalar.h.
References fabs().
template<class T> NM_Scalar& NM_Scalar< T >::operator/= (const NM_Scalar< T > & x) [inline]
Definition at line 80 of file NM_Scalar.h.
template<class T> NM_Scalar& NM_Scalar< T >::operator= (T value) [inline]
Definition at line 52 of file NM_Scalar.h.
The documentation for this class was generated from the following files:
NM_Scalar.h
frames.inl