Blender: clip_editor.c File Reference
clip_editor.c File Reference
#include <stddef.h>
#include "BKE_main.h"
#include "BKE_movieclip.h"
#include "BKE_context.h"
#include "BKE_tracking.h"
#include "DNA_object_types.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "ED_screen.h"
#include "ED_clip.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "clip_intern.h"
Functions
int ED_space_clip_poll (bContext *C)
void ED_space_clip_set (bContext *C, SpaceClip *sc, MovieClip *clip)
MovieClip * ED_space_clip (SpaceClip *sc)
ImBuf * ED_space_clip_get_buffer (SpaceClip *sc)
ImBuf * ED_space_clip_get_stable_buffer (SpaceClip *sc, float loc[2], float *scale, float *angle)
void ED_space_clip_size (SpaceClip *sc, int *width, int *height)
void ED_space_clip_zoom (SpaceClip *sc, ARegion *ar, float *zoomx, float *zoomy)
void ED_space_clip_aspect (SpaceClip *sc, float *aspx, float *aspy)
void ED_clip_update_frame (const Main *mainp, int cfra)
static int selected_boundbox (SpaceClip *sc, float min[2], float max[2])
int ED_clip_view_selection (SpaceClip *sc, ARegion *ar, int fit)
void ED_clip_point_undistorted_pos (SpaceClip *sc, float co[2], float nco[2])
void ED_clip_point_stable_pos (bContext *C, float x, float y, float *xr, float *yr)
void ED_clip_mouse_pos (bContext *C, wmEvent *event, float co[2])
Detailed Description
Definition in file clip_editor.c.
Function Documentation
void ED_clip_mouse_pos (bContext * C, wmEvent * event, float co[2])
Definition at line 313 of file clip_editor.c.
References ED_clip_point_stable_pos(), and wmEvent::mval.
Referenced by add_marker_invoke(), sclip_zoom_set_factor_exec(), select_invoke(), slide_marker_customdata(), view_zoom_in_invoke(), view_zoom_init(), and view_zoom_out_invoke().
void ED_clip_point_stable_pos (bContext * C, float x, float y, float * xr, float * yr)
Definition at line 279 of file clip_editor.c.
References BKE_tracking_apply_intrinsics(), MovieTracking::camera, CTX_wm_region(), CTX_wm_space_clip(), ED_space_clip(), ED_space_clip_size(), ED_space_clip_zoom(), invert_m4_m4(), MCLIP_PROXY_RENDER_UNDISTORT, mul_v3_m4v3(), MovieTrackingCamera::pixel_aspect, MovieClipUser::render_flag, SpaceClip::stabmat, MovieClip::tracking, UI_view2d_to_region_no_clip(), SpaceClip::user, and ARegion::v2d.
Referenced by border_select_exec(), circle_select_exec(), and ED_clip_mouse_pos().
void ED_clip_point_undistorted_pos (SpaceClip * sc, float co[2], float nco[2])
Definition at line 258 of file clip_editor.c.
References BKE_tracking_invert_intrinsics(), MovieTracking::camera, copy_v2_v2(), ED_space_clip(), ED_space_clip_size(), MCLIP_PROXY_RENDER_UNDISTORT, MovieTrackingCamera::pixel_aspect, MovieClipUser::render_flag, MovieClip::tracking, and SpaceClip::user.
Referenced by draw_marker_areas(), draw_marker_outline(), draw_track_path(), draw_tracking_tracks(), and selected_boundbox().
void ED_clip_update_frame (const Main * mainp, int cfra)
Definition at line 148 of file clip_editor.c.
References bScreen::areabase, BKE_movieclip_user_set_frame(), FALSE, ListBase::first, wmWindowManager::id, ScrArea::next, wmWindow::next, ID::next, MovieClipScopes::ok, SpaceClip::scopes, wmWindow::screen, SPACE_CLIP, ScrArea::spacedata, ScrArea::spacetype, SpaceClip::user, wmWindowManager::windows, and Main::wm.
int ED_clip_view_selection (SpaceClip * sc, ARegion * ar, int fit)
Definition at line 217 of file clip_editor.c.
References clip_view_center_to_point(), ED_space_clip_aspect(), ED_space_clip_size(), FALSE, max, min, MIN2, power_of_2(), selected_boundbox(), TRUE, ARegion::winrct, rcti::xmax, rcti::xmin, rcti::ymax, rcti::ymin, and SpaceClip::zoom.
Referenced by clip_main_area_draw(), and view_selected_exec().
MovieClip* ED_space_clip (SpaceClip * sc) [read]
Definition at line 79 of file clip_editor.c.
References SpaceClip::clip.
Referenced by add_marker(), add_marker_exec(), border_select_exec(), border_select_graph_exec(), cancelTransTracking(), circle_select_exec(), clean_tracks_exec(), clean_tracks_invoke(), clear_solution_exec(), clear_track_path_exec(), clip_draw_graph(), clip_draw_grease_pencil(), clip_draw_main(), clip_graph_tracking_iterate(), clip_graph_tracking_values_iterate(), clip_graph_tracking_values_iterate_track(), clip_main_area_draw(), clip_rebuild_proxy_exec(), clip_stabilization_tag_refresh(), copy_tracks_exec(), count_selected_bundles(), createTransTrackingCurvesData(), createTransTrackingData(), createTransTrackingTracksData(), delete_curve_exec(), delete_knot_exec(), delete_marker_exec(), delete_track_exec(), detect_features_exec(), disable_markers_exec(), do_set_scale(), draw_frame_curves(), draw_movieclip_buffer(), draw_movieclip_notes(), draw_tracks_curves(), ED_clip_point_stable_pos(), ED_clip_point_undistorted_pos(), ED_space_clip_aspect(), frame_jump_exec(), get_orientation_object(), gpencil_data_get_pointers(), graph_disable_markers_exec(), graph_select_all_markers_exec(), hide_tracks_clear_exec(), hide_tracks_exec(), join_tracks_exec(), lock_tracks_exec(), mouse_select(), mouse_select_curve(), mouse_select_knot(), movieclip_main_area_set_view2d(), open_invoke(), paste_tracks_exec(), recalcData_clip(), select_all_exec(), select_groped_exec(), select_invoke(), selected_boundbox(), set_axis_exec(), set_center_principal_exec(), set_orientation_poll(), set_origin_exec(), set_plane_exec(), set_scale_invoke(), set_solution_scale_invoke(), set_solution_scale_poll(), slide_marker_customdata(), slide_marker_invoke(), solve_camera_initjob(), solve_camera_invoke(), space_clip_frame_poll(), special_aftertrans_update(), stabilize_2d_add_exec(), stabilize_2d_remove_exec(), stabilize_2d_select_exec(), stabilize_2d_set_rotation_exec(), track_copy_color_exec(), track_markers_exec(), track_markers_initjob(), track_markers_invoke(), tracking_object_new_exec(), tracking_object_remove_exec(), and viewRedrawForce().
void ED_space_clip_aspect (SpaceClip * sc, float * aspx, float * aspy)
Definition at line 138 of file clip_editor.c.
References BKE_movieclip_aspect(), and ED_space_clip().
Referenced by clip_view_center_to_point(), ED_clip_view_selection(), and view_all_exec().
ImBuf* ED_space_clip_get_buffer (SpaceClip * sc) [read]
Definition at line 84 of file clip_editor.c.
References BKE_movieclip_get_postprocessed_ibuf(), SpaceClip::clip, IMB_freeImBuf(), NULL, SpaceClip::postproc_flag, ImBuf::rect, ImBuf::rect_float, and SpaceClip::user.
Referenced by clip_draw_grease_pencil(), and clip_draw_main().
ImBuf* ED_space_clip_get_stable_buffer (SpaceClip * sc, float loc[2], float * scale, float * angle) [read]
Definition at line 101 of file clip_editor.c.
References BKE_movieclip_get_stable_ibuf(), SpaceClip::clip, IMB_freeImBuf(), NULL, SpaceClip::postproc_flag, ImBuf::rect, ImBuf::rect_float, and SpaceClip::user.
Referenced by clip_draw_main(), and clip_main_area_draw().
int ED_space_clip_poll (bContext * C)
Definition at line 58 of file clip_editor.c.
References SpaceClip::clip, CTX_wm_space_clip(), FALSE, and TRUE.
Referenced by change_frame_poll(), CLIP_OT_clean_tracks(), CLIP_OT_clear_solution(), CLIP_OT_clear_track_path(), CLIP_OT_copy_tracks(), CLIP_OT_delete_marker(), CLIP_OT_delete_track(), CLIP_OT_disable_markers(), CLIP_OT_graph_delete_curve(), CLIP_OT_hide_tracks(), CLIP_OT_hide_tracks_clear(), CLIP_OT_lock_tracks(), CLIP_OT_mode_set(), CLIP_OT_rebuild_proxy(), CLIP_OT_select(), CLIP_OT_select_all(), CLIP_OT_select_border(), CLIP_OT_select_circle(), CLIP_OT_set_center_principal(), CLIP_OT_solve_camera(), CLIP_OT_stabilize_2d_add(), CLIP_OT_stabilize_2d_remove(), CLIP_OT_stabilize_2d_select(), CLIP_OT_stabilize_2d_set_rotation(), CLIP_OT_track_copy_color(), CLIP_OT_tracking_object_new(), CLIP_OT_tracking_object_remove(), CLIP_OT_view_all(), CLIP_OT_view_pan(), CLIP_OT_view_selected(), CLIP_OT_view_zoom(), CLIP_OT_view_zoom_in(), CLIP_OT_view_zoom_out(), CLIP_OT_view_zoom_ratio(), and paste_tracks_poll().
void ED_space_clip_set (bContext * C, SpaceClip * sc, MovieClip * clip)
Definition at line 68 of file clip_editor.c.
References SpaceClip::clip, MovieClip::id, NA_SELECTED, NC_MOVIECLIP, ID::us, and WM_event_add_notifier().
Referenced by open_exec().
void ED_space_clip_size (SpaceClip * sc, int * width, int * height)
Definition at line 118 of file clip_editor.c.
References BKE_movieclip_get_size(), SpaceClip::clip, and SpaceClip::user.
Referenced by add_marker(), add_marker_exec(), circle_select_exec(), clip_draw_main(), clip_view_center_to_point(), ED_clip_point_stable_pos(), ED_clip_point_undistorted_pos(), ED_clip_view_selection(), ED_space_clip_zoom(), movieclip_main_area_set_view2d(), sclip_zoom_set(), selected_boundbox(), slide_marker_customdata(), track_mouse_area(), and view_all_exec().
void ED_space_clip_zoom (SpaceClip * sc, ARegion * ar, float * zoomx, float * zoomy)
Definition at line 128 of file clip_editor.c.
References View2D::cur, ED_space_clip_size(), ARegion::v2d, ARegion::winrct, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by circle_select_exec(), clip_draw_main(), and ED_clip_point_stable_pos().
static int selected_boundbox (SpaceClip * sc, float min[2], float max[2]) [static]
Definition at line 171 of file clip_editor.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), DO_MINMAX2, ED_clip_point_undistorted_pos(), ED_space_clip(), ED_space_clip_size(), FALSE, ListBase::first, MovieClipUser::framenr, INIT_MINMAX2, MCLIP_PROXY_RENDER_UNDISTORT, mul_v3_m4v3(), MovieTrackingTrack::next, MovieTrackingTrack::offset, MovieTrackingMarker::pos, MovieClipUser::render_flag, SpaceClip::stabmat, TRACK_VIEW_SELECTED, MovieClip::tracking, TRUE, and SpaceClip::user.
Referenced by ED_clip_view_selection().