Blender: SCA_JoystickManager Class Reference
SCA_JoystickManager Class Reference
#include <SCA_JoystickManager.h>
Public Member Functions
SCA_JoystickManager (class SCA_LogicManager *logicmgr)
virtual ~SCA_JoystickManager ()
virtual void NextFrame (double curtime, double deltatime)
SCA_Joystick * GetJoystickDevice (short int joyindex)
Detailed Description
Definition at line 40 of file SCA_JoystickManager.h.
Constructor & Destructor Documentation
SCA_JoystickManager::SCA_JoystickManager (class SCA_LogicManager * logicmgr)
Definition at line 41 of file SCA_JoystickManager.cpp.
References SCA_Joystick::GetInstance(), i, and JOYINDEX_MAX.
SCA_JoystickManager::~SCA_JoystickManager () [virtual]
Definition at line 51 of file SCA_JoystickManager.cpp.
References i, JOYINDEX_MAX, and SCA_Joystick::ReleaseInstance().
Member Function Documentation
SCA_Joystick * SCA_JoystickManager::GetJoystickDevice (short int joyindex)
Definition at line 84 of file SCA_JoystickManager.cpp.
void SCA_JoystickManager::NextFrame (double curtime, double deltatime) [virtual]
Reimplemented from SCA_EventManager.
Definition at line 61 of file SCA_JoystickManager.cpp.
References SCA_ISensor::Activate(), SG_DList::iterator< T >::begin(), SG_DList::Empty(), SG_DList::iterator< T >::end(), SCA_Joystick::HandleEvents(), SCA_ISensor::IsSuspended(), SCA_EventManager::m_logicmgr, and SCA_EventManager::m_sensors.
The documentation for this class was generated from the following files:
SCA_JoystickManager.h
SCA_JoystickManager.cpp