Blender: node_state.c File Reference
node_state.c File Reference
node editor
#include <stdio.h>
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "BLI_rect.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_node.h"
#include "ED_screen.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "node_intern.h"
Functions
static void snode_home (ScrArea *UNUSED(sa), ARegion *ar, SpaceNode *snode)
static int node_view_all_exec (bContext *C, wmOperator *UNUSED(op))
void NODE_OT_view_all (wmOperatorType *ot)
Detailed Description
Definition in file node_state.c.
Function Documentation
void NODE_OT_view_all (wmOperatorType * ot)
Definition at line 120 of file node_state.c.
References wmOperatorType::description, ED_operator_node_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, node_view_all_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by node_operatortypes().
static int node_view_all_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 108 of file node_state.c.
References CTX_wm_area(), CTX_wm_region(), CTX_wm_space_node(), ED_region_tag_redraw(), OPERATOR_FINISHED, and snode_home().
Referenced by NODE_OT_view_all().
static void snode_home (ScrArea * UNUSEDsa, ARegion * ar, SpaceNode * snode) [static]
Definition at line 58 of file node_state.c.
References BLI_union_rctf(), View2D::cur, SpaceNode::edittree, ListBase::first, bNode::next, bNodeTree::nodes, View2D::tot, bNode::totr, UI_view2d_curRect_validate(), ARegion::v2d, ARegion::winx, ARegion::winy, rctf::xmax, rctf::xmin, SpaceNode::xof, rctf::ymax, rctf::ymin, and SpaceNode::yof.
Referenced by node_view_all_exec().