Blender: space_nla.c File Reference
space_nla.c File Reference
NLA editor
#include <string.h>
#include <stdio.h>
#include "DNA_anim_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "nla_intern.h"
Functions
ARegion * nla_has_buttons_region (ScrArea *sa)
static SpaceLink * nla_new (const bContext *C)
static void nla_free (SpaceLink *sl)
static void nla_init (struct wmWindowManager *UNUSED(wm), ScrArea *sa)
static SpaceLink * nla_duplicate (SpaceLink *sl)
static void nla_channel_area_init (wmWindowManager *wm, ARegion *ar)
static void nla_channel_area_draw (const bContext *C, ARegion *ar)
static void nla_main_area_init (wmWindowManager *wm, ARegion *ar)
static void nla_main_area_draw (const bContext *C, ARegion *ar)
static void nla_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void nla_header_area_draw (const bContext *C, ARegion *ar)
static void nla_buttons_area_init (wmWindowManager *wm, ARegion *ar)
static void nla_buttons_area_draw (const bContext *C, ARegion *ar)
static void nla_region_listener (ARegion *ar, wmNotifier *wmn)
static void nla_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void nla_channel_area_listener (ARegion *ar, wmNotifier *wmn)
static void nla_listener (ScrArea *sa, wmNotifier *wmn)
void ED_spacetype_nla (void)
Detailed Description
Definition in file space_nla.c.
Function Documentation
void ED_spacetype_nla (void)
Definition at line 497 of file space_nla.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, nla_buttons_area_draw(), nla_buttons_area_init(), nla_buttons_register(), nla_channel_area_draw(), nla_channel_area_init(), nla_channel_area_listener(), nla_duplicate(), nla_free(), nla_header_area_draw(), nla_header_area_init(), nla_init(), nla_keymap(), nla_listener(), nla_main_area_draw(), nla_main_area_init(), nla_main_area_listener(), nla_new(), nla_operatortypes(), nla_region_listener(), SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_NLA, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static void nla_buttons_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 343 of file space_nla.c.
References ED_region_panels(), and NULL.
Referenced by ED_spacetype_nla().
static void nla_buttons_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 333 of file space_nla.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, View2D::mask, SPACE_NLA, ARegion::v2d, ARegion::winrct, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_nla().
static void nla_channel_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 224 of file space_nla.c.
References ANIM_animdata_get_context(), draw_nla_channel_list(), TH_BACK, UI_ThemeClearColor(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, and V2D_ARG_DUMMY.
Referenced by ED_spacetype_nla().
static void nla_channel_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 205 of file space_nla.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_NLA, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_LIST, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_nla().
static void nla_channel_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 425 of file space_nla.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_RENAME, NC_ANIMATION, NC_ID, NC_OBJECT, NC_SCENE, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_KEYS, and ND_OB_ACTIVE.
Referenced by ED_spacetype_nla().
static SpaceLink* nla_duplicate (SpaceLink * sl) [static]
Definition at line 194 of file space_nla.c.
References SpaceNla::ads, and MEM_dupallocN().
Referenced by ED_spacetype_nla().
static void nla_free (SpaceLink * sl) [static]
Definition at line 169 of file space_nla.c.
References SpaceNla::ads, BLI_freelistN(), bDopeSheet::chanbase, and MEM_freeN().
Referenced by ED_spacetype_nla().
ARegion* nla_has_buttons_region (ScrArea * sa)
Definition at line 67 of file space_nla.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_UI, and RGN_TYPE_WINDOW.
Referenced by nla_properties().
static void nla_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 327 of file space_nla.c.
References ED_region_header().
Referenced by ED_spacetype_nla().
static void nla_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 322 of file space_nla.c.
References ED_region_header_init().
Referenced by ED_spacetype_nla().
static void nla_init (struct wmWindowManager * UNUSEDwm, ScrArea * sa) [static]
Definition at line 181 of file space_nla.c.
References SpaceNla::ads, ED_area_tag_refresh(), ListBase::first, G, if(), MEM_callocN(), NULL, bDopeSheet::source, and ScrArea::spacedata.
Referenced by ED_spacetype_nla().
static void nla_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 460 of file space_nla.c.
References wmNotifier::category, wmNotifier::data, ED_area_tag_redraw(), ED_area_tag_refresh(), NC_ANIMATION, NC_OBJECT, NC_SCENE, NC_SPACE, ND_OB_ACTIVE, ND_OB_SELECT, ND_SPACE_NLA, and ND_TRANSFORM.
Referenced by ED_spacetype_nla().
static void nla_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 265 of file space_nla.c.
References ANIM_animdata_get_context(), ANIM_draw_cfra(), ANIM_draw_previewrange(), CTX_data_scene(), CTX_wm_space_nla(), draw_markers_time(), draw_nla_main_data(), DRAWCFRA_SHOW_NUMBOX, DRAWCFRA_UNIT_SECONDS, SpaceNla::flag, SNLA_DRAWTIME, SNLA_NODRAWCFRANUM, TH_BACK, UI_ThemeClearColor(), UI_view2d_grid_calc(), UI_view2d_grid_draw(), UI_view2d_grid_free(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_text_cache_draw(), UI_view2d_view_ortho(), UI_view2d_view_orthoSpecial(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_GRID_CLAMP, V2D_GRIDLINES_ALL, V2D_UNIT_FRAMES, V2D_UNIT_SECONDS, ARegion::winx, and ARegion::winy.
Referenced by ED_spacetype_nla().
static void nla_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 252 of file space_nla.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_NLA, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler(), WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_nla().
static void nla_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 381 of file space_nla.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_EDITED, NA_RENAME, NC_ANIMATION, NC_ID, NC_NODE, NC_OBJECT, NC_SCENE, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_FRAME, ND_KEYS, ND_MARKERS, ND_OB_ACTIVE, ND_RENDER_OPTIONS, and ND_TRANSFORM.
Referenced by ED_spacetype_nla().
static SpaceLink* nla_new (const bContext * C) [static]
Definition at line 95 of file space_nla.c.
References SpaceNla::ads, View2D::align, ARegion::alignment, SpaceNla::autosnap, BLI_addtail(), CTX_data_scene(), CTX_wm_area(), View2D::cur, EFRA, ARegion::flag, View2D::flag, View2D::keepofs, View2D::keepzoom, View2D::max, MAXFRAMEF, View2D::maxzoom, MEM_callocN(), View2D::min, View2D::minzoom, SpaceNla::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SACTSNAP_FRAME, View2D::scroll, SFRA, bDopeSheet::source, SPACE_NLA, SpaceNla::spacetype, View2D::tot, ARegion::v2d, V2D_ALIGN_NO_POS_Y, V2D_KEEPOFS_Y, V2D_LOCKZOOM_Y, V2D_SCROLL_BOTTOM, V2D_SCROLL_RIGHT, V2D_SCROLL_SCALE_HORIZONTAL, V2D_VIEWSYNC_AREA_VERTICAL, ScrArea::winy, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_nla().
static void nla_region_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 348 of file space_nla.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NC_ANIMATION, NC_OBJECT, NC_SCENE, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_FRAME, ND_KEYS, ND_MARKERS, and ND_OB_ACTIVE.
Referenced by ED_spacetype_nla().