Blender: LOD_NdQuadric Class Reference
LOD_NdQuadric Class Reference
#include <LOD_NdQuadric.h>
Public Member Functions
LOD_NdQuadric (const MT_Vector3 &vec, const MT_Scalar &offset)
LOD_NdQuadric (const MT_Vector3 &vec, const MT_Scalar &offset, int pos)
LOD_NdQuadric ()
~LOD_NdQuadric ()
void Tensor (TNT::Matrix< MT_Scalar > &) const
void Vector (TNT::Vector< MT_Scalar > &) const
void Clear (MT_Scalar val=0.0)
LOD_NdQuadric & operator= (const LOD_NdQuadric &Q)
LOD_NdQuadric & operator+= (const LOD_NdQuadric &Q)
LOD_NdQuadric & operator*= (const MT_Scalar &s)
MT_Scalar Evaluate (const TNT::Vector< MT_Scalar > &vec) const
bool Optimize (TNT::Vector< MT_Scalar > &vec) const
Detailed Description
Definition at line 45 of file LOD_NdQuadric.h.
Constructor & Destructor Documentation
LOD_NdQuadric::LOD_NdQuadric (const MT_Vector3 & vec, const MT_Scalar & offset)
Definition at line 44 of file LOD_NdQuadric.cpp.
LOD_NdQuadric::LOD_NdQuadric (const MT_Vector3 & vec, const MT_Scalar & offset, int pos)
Definition at line 62 of file LOD_NdQuadric.cpp.
LOD_NdQuadric::LOD_NdQuadric ()
Definition at line 84 of file LOD_NdQuadric.cpp.
LOD_NdQuadric::~LOD_NdQuadric () [inline]
Definition at line 104 of file LOD_NdQuadric.h.
Member Function Documentation
void LOD_NdQuadric::Clear (MT_Scalar val = 0.0)
Definition at line 162 of file LOD_NdQuadric.cpp.
References LOD_Quadric::Clear().
MT_Scalar LOD_NdQuadric::Evaluate (const TNT::Vector< MT_Scalar > & vec) const
Definition at line 223 of file LOD_NdQuadric.cpp.
References TNT::dot_prod(), MAT_SIZE, TNT::matmult(), Tensor(), and Vector().
Referenced by LOD_QuadricEditor::ComputeEdgeCosts(), and LOD_NdQuadricEditor::InitializeHeapKeys().
LOD_NdQuadric & LOD_NdQuadric::operator*= (const MT_Scalar & s)
Definition at line 206 of file LOD_NdQuadric.cpp.
References TNT::vectorscale().
LOD_NdQuadric & LOD_NdQuadric::operator+= (const LOD_NdQuadric & Q)
Definition at line 191 of file LOD_NdQuadric.cpp.
References TNT::vectoradd().
LOD_NdQuadric & LOD_NdQuadric::operator= (const LOD_NdQuadric & Q)
Definition at line 175 of file LOD_NdQuadric.cpp.
bool LOD_NdQuadric::Optimize (TNT::Vector< MT_Scalar > & vec) const
Definition at line 247 of file LOD_NdQuadric.cpp.
References TNT::Vector< T >::begin(), TNT::Vector< T >::end(), TNT::LU_factor(), TNT::LU_solve(), MAT_SIZE, Tensor(), and Vector().
Referenced by LOD_NdQuadricEditor::TargetVertex().
void LOD_NdQuadric::Tensor (TNT::Matrix< MT_Scalar > & tensor) const
Definition at line 102 of file LOD_NdQuadric.cpp.
References i, MAT_SIZE, and LOD_Quadric::Tensor().
Referenced by Evaluate(), and Optimize().
void LOD_NdQuadric::Vector (TNT::Vector< MT_Scalar > & vector) const
Definition at line 144 of file LOD_NdQuadric.cpp.
References i, MAT_SIZE, and LOD_Quadric::Vector().
Referenced by Evaluate(), and Optimize().
The documentation for this class was generated from the following files:
LOD_NdQuadric.h
LOD_NdQuadric.cpp