Blender: bmo_utils.c File Reference
bmo_utils.c File Reference
#include "MEM_guardedalloc.h"
#include "DNA_meshdata_types.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BLI_heap.h"
#include "BKE_customdata.h"
#include "bmesh.h"
#include "intern/bmesh_operators_private.h"
Classes
struct SimSel_FaceExt
struct SimSel_EdgeExt
struct SimSel_VertExt
struct ElemNode
Defines
#define EDGE_OUT 1
#define FACE_TAINT 1
#define SEL_FLAG 1
#define SEL_ORIG 2
#define FACE_VIS 1
#define FACE_FLAG 2
#define FACE_MARK 4
#define FACE_FLIP 8
#define EDGE_MARK 1
#define VERT_MARK 1
Typedefs
typedef struct SimSel_FaceExt SimSel_FaceExt
typedef struct SimSel_EdgeExt SimSel_EdgeExt
typedef struct SimSel_VertExt SimSel_VertExt
typedef struct ElemNode ElemNode
Functions
void bmo_makevert_exec (BMesh *bm, BMOperator *op)
void bmo_transform_exec (BMesh *bm, BMOperator *op)
void bmo_translate_exec (BMesh *bm, BMOperator *op)
void bmo_scale_exec (BMesh *bm, BMOperator *op)
void bmo_rotate_exec (BMesh *bm, BMOperator *op)
void bmo_reversefaces_exec (BMesh *bm, BMOperator *op)
void bmo_edgerotate_exec (BMesh *bm, BMOperator *op)
static void bmo_regionextend_extend (BMesh *bm, BMOperator *op, int usefaces)
static void bmo_regionextend_constrict (BMesh *bm, BMOperator *op, int usefaces)
void bmo_regionextend_exec (BMesh *bm, BMOperator *op)
void bmo_righthandfaces_exec (BMesh *bm, BMOperator *op)
void bmo_vertexsmooth_exec (BMesh *bm, BMOperator *op)
static float ngon_fake_area (BMFace *f)
void bmo_similarfaces_exec (BMesh *bm, BMOperator *op)
void bmo_similaredges_exec (BMesh *bm, BMOperator *op)
void bmo_similarverts_exec (BMesh *bm, BMOperator *op)
void bmo_face_rotateuvs_exec (BMesh *bm, BMOperator *op)
void bmo_face_reverseuvs_exec (BMesh *bm, BMOperator *op)
void bmo_rotatecolors_exec (BMesh *bm, BMOperator *op)
void bmo_face_reversecolors_exec (BMesh *bm, BMOperator *op)
void bmo_vertexshortestpath_exec (BMesh *bm, BMOperator *op)
Define Documentation
#define EDGE_MARK 1
Definition at line 664 of file bmo_utils.c.
Referenced by bmo_similaredges_exec().
#define EDGE_OUT 1
#define FACE_FLAG 2
Definition at line 274 of file bmo_utils.c.
Referenced by bmo_righthandfaces_exec().
#define FACE_FLIP 8
Definition at line 276 of file bmo_utils.c.
Referenced by bmo_righthandfaces_exec().
#define FACE_MARK 4
Definition at line 275 of file bmo_utils.c.
Referenced by bmo_similarfaces_exec().
#define FACE_TAINT 1
Referenced by bmo_edgerotate_exec().
#define FACE_VIS 1
Definition at line 273 of file bmo_utils.c.
Referenced by bmo_righthandfaces_exec().
#define SEL_FLAG 1
Definition at line 172 of file bmo_utils.c.
Referenced by bmo_regionextend_constrict(), bmo_regionextend_exec(), and bmo_regionextend_extend().
#define SEL_ORIG 2
Definition at line 173 of file bmo_utils.c.
Referenced by bmo_regionextend_constrict(), bmo_regionextend_exec(), and bmo_regionextend_extend().
#define VERT_MARK 1
Definition at line 840 of file bmo_utils.c.
Referenced by bmo_similarverts_exec(), and bmo_vertexshortestpath_exec().
Typedef Documentation
typedef struct ElemNode ElemNode
typedef struct SimSel_EdgeExt SimSel_EdgeExt
typedef struct SimSel_FaceExt SimSel_FaceExt
typedef struct SimSel_VertExt SimSel_VertExt
Function Documentation
void bmo_edgerotate_exec (BMesh * bm, BMOperator * op)
this ends up being called twice, could add option to not to call check in BM_edge_rotate to get some extra speed
Definition at line 121 of file bmo_utils.c.
References BM_EDGE, BM_edge_face_pair(), BM_edge_rotate(), BM_edge_rotate_check(), BM_EDGEROT_CHECK_DEGENERATE, BM_EDGEROT_CHECK_EXISTS, BMERR_INVALID_SELECTION, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_count(), BMO_slot_buffer_from_enabled_flag(), EDGE_OUT, FACE_TAINT, FALSE, and fb().
void bmo_face_reversecolors_exec (BMesh * bm, BMOperator * op)
Definition at line 1130 of file bmo_utils.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_FACE, BM_ITER_ELEM_INDEX, BM_LOOPS_OF_FACE, BMO_ITER, CD_MLOOPCOL, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, BMLoop::head, i, BMesh::ldata, BMFace::len, and NULL.
void bmo_face_reverseuvs_exec (BMesh * bm, BMOperator * op)
Definition at line 1024 of file bmo_utils.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_FACE, BM_ITER_ELEM_INDEX, BM_LOOPS_OF_FACE, BMO_ITER, CD_MLOOPUV, copy_v2_v2(), CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, BMLoop::head, i, BMesh::ldata, BMFace::len, NULL, and MLoopUV::uv.
void bmo_face_rotateuvs_exec (BMesh * bm, BMOperator * op)
Definition at line 957 of file bmo_utils.c.
References BM_FACE, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMO_ITER, BMO_slot_int_get(), CD_MLOOPUV, copy_v2_v2(), CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, DIRECTION_CCW, DIRECTION_CW, BMLoop::head, BMesh::ldata, and MLoopUV::uv.
void bmo_makevert_exec (BMesh * bm, BMOperator * op)
Definition at line 44 of file bmo_utils.c.
References BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_slot_buffer_from_enabled_flag(), BMO_slot_vec_get(), and NULL.
static void bmo_regionextend_constrict (BMesh * bm, BMOperator * op, int usefaces) [static]
Definition at line 214 of file bmo_utils.c.
References BM_EDGES_OF_VERT, BM_FACE, BM_FACES_OF_EDGE, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_VERT, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMLoop::e, SEL_FLAG, and SEL_ORIG.
Referenced by bmo_regionextend_exec().
void bmo_regionextend_exec (BMesh * bm, BMOperator * op)
Definition at line 256 of file bmo_utils.c.
References BM_ALL, bmo_regionextend_constrict(), bmo_regionextend_extend(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), SEL_FLAG, and SEL_ORIG.
static void bmo_regionextend_extend (BMesh * bm, BMOperator * op, int usefaces) [static]
Definition at line 175 of file bmo_utils.c.
References BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_FACE, BM_FACES_OF_EDGE, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_VERT, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMLoop::e, SEL_FLAG, and SEL_ORIG.
Referenced by bmo_regionextend_exec().
void bmo_reversefaces_exec (BMesh * bm, BMOperator * op)
Definition at line 111 of file bmo_utils.c.
References BM_FACE, BM_face_normal_flip(), and BMO_ITER.
void bmo_righthandfaces_exec (BMesh * bm, BMOperator * op)
Definition at line 299 of file bmo_utils.c.
References BLI_array_declare, BLI_array_free, BLI_array_growone, BM_elem_flag_disable, BM_elem_flag_test, BM_elem_flag_toggle, BM_ELEM_TAG, BM_FACE, BM_face_calc_center_bounds(), BM_face_normal_flip(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_LOOPS_OF_LOOP, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_elem_flag_toggle, BMO_ITER, bmo_righthandfaces_exec(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), dot_v3v3(), BMLoop::f, FACE_FLAG, FACE_FLIP, FACE_VIS, i, BMFace::no, NULL, and BMLoop::v.
Referenced by bm_rationalize_normals(), and bmo_righthandfaces_exec().
void bmo_rotate_exec (BMesh * bm, BMOperator * op)
Definition at line 93 of file bmo_utils.c.
References BMO_op_callf(), BMO_slot_vec_get(), and mul_v3_fl().
void bmo_rotatecolors_exec (BMesh * bm, BMOperator * op)
Definition at line 1064 of file bmo_utils.c.
References BM_FACE, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMO_ITER, BMO_slot_int_get(), CD_MLOOPCOL, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, DIRECTION_CCW, DIRECTION_CW, BMLoop::head, and BMesh::ldata.
void bmo_scale_exec (BMesh * bm, BMOperator * op)
Definition at line 79 of file bmo_utils.c.
References BMO_op_callf(), BMO_slot_vec_get(), and unit_m3().
void bmo_similaredges_exec (BMesh * bm, BMOperator * op)
Definition at line 686 of file bmo_utils.c.
References angle(), SimSel_EdgeExt::angle, angle_v3v3(), BM_EDGE, BM_edge_calc_face_angle(), BM_edge_face_count(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SEAM, BM_ELEM_SMOOTH, BM_ITER_MESH, BM_mesh_elem_count(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), CD_CREASE, BMVert::co, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, SimSel_EdgeExt::e, BMesh::edata, EDGE_MARK, fabsf, SimSel_EdgeExt::faces, FALSE, BMEdge::head, i, indices, len_v3v3(), SimSel_EdgeExt::length, length(), MEM_callocN(), MEM_freeN(), NULL, RAD2DEGF, SIMEDGE_CREASE, SIMEDGE_DIR, SIMEDGE_FACE, SIMEDGE_FACE_ANGLE, SIMEDGE_LENGTH, SIMEDGE_SEAM, SIMEDGE_SHARP, sub_v3_v3v3(), thresh, TRUE, BMEdge::v1, and BMEdge::v2.
void bmo_similarfaces_exec (BMesh * bm, BMOperator * op)
Definition at line 514 of file bmo_utils.c.
References angle(), angle_v3v3(), SimSel_FaceExt::area, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_FACE, BM_face_calc_center_mean(), BM_face_calc_perimeter(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_mesh_elem_count(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), CD_MTEXPOLY, copy_v3_v3(), CustomData_bmesh_get(), CustomData_has_layer(), SimSel_FaceExt::d, BMHeader::data, dot_v3v3(), SimSel_FaceExt::f, fabsf, FACE_MARK, FALSE, BMFace::head, i, indices, BMFace::mat_nr, MEM_callocN(), MEM_freeN(), ngon_fake_area(), BMFace::no, normalize_v3(), NULL, BMesh::pdata, SimSel_FaceExt::perim, RAD2DEGF, SIMFACE_AREA, SIMFACE_COPLANAR, SIMFACE_IMAGE, SIMFACE_MATERIAL, SIMFACE_NORMAL, SIMFACE_PERIMETER, SimSel_FaceExt::t, thresh, MTexPoly::tpage, TRUE, and Image::type.
void bmo_similarverts_exec (BMesh * bm, BMOperator * op)
Definition at line 854 of file bmo_utils.c.
References angle_v3v3(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ITER_MESH, BM_mesh_elem_count(), BM_VERT, BM_vert_face_count(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), CD_MDEFORMVERT, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, MDeformWeight::def_nr, SimSel_VertExt::dvert, MDeformVert::dw, FALSE, BMVert::head, i, indices, MEM_freeN(), MEM_mallocN(), BMVert::no, NULL, SimSel_VertExt::num_faces, RAD2DEGF, SIMVERT_FACE, SIMVERT_NORMAL, SIMVERT_VGROUP, thresh, MDeformVert::totweight, TRUE, SimSel_VertExt::v, BMesh::vdata, and VERT_MARK.
void bmo_transform_exec (BMesh * bm, BMOperator * op)
Definition at line 54 of file bmo_utils.c.
References BM_VERT, BMO_ITER, BMO_slot_mat4_get(), BMVert::co, and mul_m4_v3().
void bmo_translate_exec (BMesh * bm, BMOperator * op)
Definition at line 67 of file bmo_utils.c.
References BMO_op_callf(), BMO_slot_vec_get(), copy_v3_v3(), and unit_m4().
void bmo_vertexshortestpath_exec (BMesh * bm, BMOperator * op)
Definition at line 1174 of file bmo_utils.c.
References BLI_heap_empty(), BLI_heap_free(), BLI_heap_insert(), BLI_heap_new(), BLI_heap_popmin(), BLI_heap_remove(), BM_EDGES_OF_VERT, BM_elem_index_get, BM_elem_index_set, BM_ITER_ELEM, BM_ITER_MESH, BM_mesh_elem_count(), BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_int_get(), BMVert::co, BMesh::elem_index_dirty, FLT_MAX, ElemNode::hn, i, if(), len_v3v3(), MEM_freeN(), MEM_mallocN(), NULL, ElemNode::parent, ElemNode::v, BMEdge::v1, BMEdge::v2, VERT_MARK, VPATH_SELECT_EDGE_LENGTH, and ElemNode::weight.
void bmo_vertexsmooth_exec (BMesh * bm, BMOperator * op)
Definition at line 406 of file bmo_utils.c.
References add_v3_v3v3(), BLI_array_declare, BLI_array_free, BLI_array_growone, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_ITER_ELEM, BM_VERT, BMO_ITER, BMO_slot_bool_get(), BMO_slot_float_get(), co, BMVert::co, copy_v3_v3(), cos(), fabsf, i, mid_v3_v3v3(), mul_v3_fl(), and NULL.
static float ngon_fake_area (BMFace * f) [static]
Definition at line 468 of file bmo_utils.c.
References area_tri_v3(), BM_face_calc_center_mean(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMVert::co, copy_v3_v3(), BMLoop::f, and BMLoop::v.
Referenced by bmo_similarfaces_exec().