Blender: sound.c File Reference
sound.c File Reference
blenkernel
#include <string.h>
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
#include "DNA_packedFile_types.h"
#include "DNA_screen_types.h"
#include "DNA_sound_types.h"
#include "DNA_speaker_types.h"
#include "BKE_utildefines.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_sound.h"
#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_packedFile.h"
#include "BKE_animsys.h"
#include "BKE_sequencer.h"
#include "BKE_scene.h"
#include "BLI_utildefines.h"
Defines
#define NAN_FLT *((float*)(&NAN_INT))
Functions
struct bSound * sound_new_file (struct Main *bmain, const char *filename)
void sound_free (struct bSound *sound)
int sound_define_from_str (const char *UNUSED(str))
void sound_force_device (int UNUSED(device))
void sound_init_once (void)
void sound_init (struct Main *UNUSED(bmain))
void sound_exit (void)
void sound_cache (struct bSound *UNUSED(sound))
void sound_delete_cache (struct bSound *UNUSED(sound))
void sound_load (struct Main *UNUSED(bmain), struct bSound *UNUSED(sound))
void sound_create_scene (struct Scene *UNUSED(scene))
void sound_destroy_scene (struct Scene *UNUSED(scene))
void sound_mute_scene (struct Scene *UNUSED(scene), int UNUSED(muted))
void * sound_scene_add_scene_sound (struct Scene *UNUSED(scene), struct Sequence *UNUSED(sequence), int UNUSED(startframe), int UNUSED(endframe), int UNUSED(frameskip))
void * sound_scene_add_scene_sound_defaults (struct Scene *UNUSED(scene), struct Sequence *UNUSED(sequence))
void * sound_add_scene_sound (struct Scene *UNUSED(scene), struct Sequence *UNUSED(sequence), int UNUSED(startframe), int UNUSED(endframe), int UNUSED(frameskip))
void * sound_add_scene_sound_defaults (struct Scene *UNUSED(scene), struct Sequence *UNUSED(sequence))
void sound_remove_scene_sound (struct Scene *UNUSED(scene), void *UNUSED(handle))
void sound_mute_scene_sound (void *UNUSED(handle), char UNUSED(mute))
void sound_move_scene_sound (struct Scene *UNUSED(scene), void *UNUSED(handle), int UNUSED(startframe), int UNUSED(endframe), int UNUSED(frameskip))
void sound_move_scene_sound_defaults (struct Scene *UNUSED(scene), struct Sequence *UNUSED(sequence))
void sound_play_scene (struct Scene *UNUSED(scene))
void sound_stop_scene (struct Scene *UNUSED(scene))
void sound_seek_scene (struct Main *UNUSED(bmain), struct Scene *UNUSED(scene))
float sound_sync_scene (struct Scene *UNUSED(scene))
int sound_scene_playing (struct Scene *UNUSED(scene))
int sound_read_sound_buffer (struct bSound *UNUSED(sound), float *UNUSED(buffer), int UNUSED(length), float UNUSED(start), float UNUSED(end))
void sound_read_waveform (struct bSound *sound)
void sound_init_main (struct Main *bmain)
void sound_set_cfra (int cfra)
void sound_update_sequencer (struct Main *main, struct bSound *sound)
void sound_update_scene (struct Scene *scene)
void sound_update_scene_sound (void *handle, struct bSound *sound)
void sound_update_scene_listener (struct Scene *scene)
void sound_update_fps (struct Scene *scene)
void sound_set_scene_sound_volume (void *handle, float volume, char animated)
void sound_set_scene_sound_pan (void *handle, float pan, char animated)
void sound_set_scene_volume (struct Scene *scene, float volume)
void sound_set_scene_sound_pitch (void *handle, float pitch, char animated)
Variables
static const int NAN_INT = 0x7FC00000
Detailed Description
Definition in file sound.c.
Define Documentation
#define NAN_FLT *((float*)(&NAN_INT))
Definition at line 66 of file sound.c.
Referenced by sound_sync_scene().
Function Documentation
void* sound_add_scene_sound (struct Scene * UNUSEDscene, struct Sequence * UNUSEDsequence, int UNUSEDstartframe, int UNUSEDendframe, int UNUSEDframeskip)
Definition at line 806 of file sound.c.
References NULL.
void* sound_add_scene_sound_defaults (struct Scene * UNUSEDscene, struct Sequence * UNUSEDsequence)
Definition at line 807 of file sound.c.
References NULL.
void sound_cache (struct bSound * UNUSEDsound)
Definition at line 798 of file sound.c.
void sound_create_scene (struct Scene * UNUSEDscene)
Definition at line 801 of file sound.c.
int sound_define_from_str (const char * UNUSEDstr)
Definition at line 793 of file sound.c.
void sound_delete_cache (struct bSound * UNUSEDsound)
Definition at line 799 of file sound.c.
void sound_destroy_scene (struct Scene * UNUSEDscene)
Definition at line 802 of file sound.c.
void sound_exit (void)
Definition at line 797 of file sound.c.
Referenced by GPG_Application::exitEngine(), GPG_Application::initEngine(), WM_exit_ext(), and WM_init_game().
void sound_force_device (int UNUSEDdevice)
Definition at line 794 of file sound.c.
void sound_free (struct bSound * sound)
Definition at line 107 of file sound.c.
References AUD_unload(), bSound::cache, freePackedFile(), bSound::handle, NULL, bSound::packedfile, bSound::playback_handle, and sound_free_waveform().
Referenced by free_libblock().
void sound_init (struct Main * UNUSEDbmain)
Definition at line 796 of file sound.c.
void sound_init_main (struct Main * bmain)
Definition at line 819 of file sound.c.
Referenced by setup_app_data().
void sound_init_once (void)
Definition at line 795 of file sound.c.
Referenced by main().
void sound_load (struct Main * UNUSEDbmain, struct bSound * UNUSEDsound)
Definition at line 800 of file sound.c.
void sound_move_scene_sound (struct Scene * UNUSEDscene, void * UNUSEDhandle, int UNUSEDstartframe, int UNUSEDendframe, int UNUSEDframeskip)
Definition at line 810 of file sound.c.
void sound_move_scene_sound_defaults (struct Scene * UNUSEDscene, struct Sequence * UNUSEDsequence)
Definition at line 811 of file sound.c.
void sound_mute_scene (struct Scene * UNUSEDscene, int UNUSEDmuted)
Definition at line 803 of file sound.c.
void sound_mute_scene_sound (void * UNUSEDhandle, char UNUSEDmute)
Definition at line 809 of file sound.c.
struct bSound* sound_new_file (struct Main * bmain, const char * filename) [read]
Definition at line 73 of file sound.c.
References alloc_libblock(), BLI_path_abs(), BLI_strncpy(), FILE_MAX, free_libblock(), G, ID_SO, len(), bSound::name, NULL, bSound::playback_handle, Main::sound, sound_load(), str, and strlen().
Referenced by do_versions().
void sound_play_scene (struct Scene * UNUSEDscene)
Definition at line 812 of file sound.c.
int sound_read_sound_buffer (struct bSound * UNUSEDsound, float * UNUSEDbuffer, int UNUSEDlength, float UNUSEDstart, float UNUSEDend)
Definition at line 817 of file sound.c.
void sound_read_waveform (struct bSound * sound)
Definition at line 818 of file sound.c.
Referenced by drawseqwave().
void sound_remove_scene_sound (struct Scene * UNUSEDscene, void * UNUSEDhandle)
Definition at line 808 of file sound.c.
void* sound_scene_add_scene_sound (struct Scene * UNUSEDscene, struct Sequence * UNUSEDsequence, int UNUSEDstartframe, int UNUSEDendframe, int UNUSEDframeskip)
Definition at line 804 of file sound.c.
References NULL.
void* sound_scene_add_scene_sound_defaults (struct Scene * UNUSEDscene, struct Sequence * UNUSEDsequence)
Definition at line 805 of file sound.c.
References NULL.
int sound_scene_playing (struct Scene * UNUSEDscene)
Definition at line 816 of file sound.c.
void sound_seek_scene (struct Main * UNUSEDbmain, struct Scene * UNUSEDscene)
Definition at line 814 of file sound.c.
void sound_set_cfra (int cfra)
Definition at line 820 of file sound.c.
Referenced by scene_update_for_newframe().
void sound_set_scene_sound_pan (void * handle, float pan, char animated)
Definition at line 827 of file sound.c.
void sound_set_scene_sound_pitch (void * handle, float pitch, char animated)
Definition at line 829 of file sound.c.
void sound_set_scene_sound_volume (void * handle, float volume, char animated)
Definition at line 826 of file sound.c.
void sound_set_scene_volume (struct Scene * scene, float volume)
Definition at line 828 of file sound.c.
void sound_stop_scene (struct Scene * UNUSEDscene)
Definition at line 813 of file sound.c.
float sound_sync_scene (struct Scene * UNUSEDscene)
Definition at line 815 of file sound.c.
References NAN_FLT.
void sound_update_fps (struct Scene * scene)
Definition at line 825 of file sound.c.
void sound_update_scene (struct Scene * scene)
Definition at line 822 of file sound.c.
Referenced by scene_update_tagged_recursive().
void sound_update_scene_listener (struct Scene * scene)
Definition at line 824 of file sound.c.
void sound_update_scene_sound (void * handle, struct bSound * sound)
Definition at line 823 of file sound.c.
Referenced by seq_update_sound_recursive().
void sound_update_sequencer (struct Main * main, struct bSound * sound)
Definition at line 821 of file sound.c.
Variable Documentation
const int NAN_INT = 0x7FC00000 [static]
Definition at line 65 of file sound.c.