Blender: BLI_math_vector.h File Reference
BLI_math_vector.h File Reference
blenlib
#include "BLI_math_inline.h"
#include "intern/math_vector_inline.c"
Functions
MINLINE void zero_v2 (float r[2])
MINLINE void zero_v3 (float r[3])
MINLINE void zero_v4 (float r[4])
MINLINE void copy_v2_v2 (float r[2], const float a[2])
MINLINE void copy_v3_v3 (float r[3], const float a[3])
MINLINE void copy_v4_v4 (float r[4], const float a[4])
MINLINE void copy_v2_fl (float r[2], float f)
MINLINE void copy_v3_fl (float r[3], float f)
MINLINE void copy_v4_fl (float r[4], float f)
MINLINE void swap_v2_v2 (float a[2], float b[2])
MINLINE void swap_v3_v3 (float a[3], float b[3])
MINLINE void swap_v4_v4 (float a[4], float b[4])
MINLINE void copy_v2_v2_char (char r[2], const char a[2])
MINLINE void copy_v3_v3_char (char r[3], const char a[3])
MINLINE void copy_v4_v4_char (char r[4], const char a[4])
MINLINE void copy_v2_v2_short (short r[2], const short a[2])
MINLINE void copy_v3_v3_short (short r[3], const short a[3])
MINLINE void copy_v4_v4_short (short r[4], const short a[4])
MINLINE void copy_v2_v2_int (int r[2], const int a[2])
MINLINE void copy_v3_v3_int (int r[3], const int a[3])
MINLINE void copy_v4_v4_int (int r[4], const int a[4])
MINLINE void copy_v2fl_v2db (float r[2], const double a[2])
MINLINE void copy_v3fl_v3db (float r[3], const double a[3])
MINLINE void copy_v4fl_v4db (float r[4], const double a[4])
MINLINE void copy_v2db_v2fl (double r[2], const float a[2])
MINLINE void copy_v3db_v3fl (double r[3], const float a[3])
MINLINE void copy_v4db_v4fl (double r[4], const float a[4])
MINLINE void add_v3_fl (float r[3], float f)
MINLINE void add_v4_fl (float r[4], float f)
MINLINE void add_v2_v2 (float r[2], const float a[2])
MINLINE void add_v2_v2v2 (float r[2], const float a[2], const float b[2])
MINLINE void add_v3_v3 (float r[3], const float a[3])
MINLINE void add_v3_v3v3 (float r[3], const float a[3], const float b[3])
MINLINE void sub_v2_v2 (float r[2], const float a[2])
MINLINE void sub_v2_v2v2 (float r[2], const float a[2], const float b[2])
MINLINE void sub_v3_v3 (float r[3], const float a[3])
MINLINE void sub_v3_v3v3 (float r[3], const float a[3], const float b[3])
MINLINE void sub_v4_v4 (float r[4], const float a[4])
MINLINE void sub_v4_v4v4 (float r[4], const float a[4], const float b[4])
MINLINE void mul_v2_fl (float r[2], float f)
MINLINE void mul_v2_v2fl (float r[2], const float a[2], float f)
MINLINE void mul_v3_fl (float r[3], float f)
MINLINE void mul_v3_v3fl (float r[3], const float a[3], float f)
MINLINE void mul_v2_v2 (float r[2], const float a[2])
MINLINE void mul_v3_v3 (float r[3], const float a[3])
MINLINE void mul_v3_v3v3 (float r[3], const float a[3], const float b[3])
MINLINE void mul_v4_fl (float r[4], float f)
MINLINE void madd_v3_v3fl (float r[3], const float a[3], float f)
MINLINE void madd_v3_v3v3 (float r[3], const float a[3], const float b[3])
MINLINE void madd_v2_v2v2fl (float r[2], const float a[2], const float b[2], float f)
MINLINE void madd_v3_v3v3fl (float r[3], const float a[3], const float b[3], float f)
MINLINE void madd_v3_v3v3v3 (float r[3], const float a[3], const float b[3], const float c[3])
MINLINE void madd_v4_v4fl (float r[4], const float a[4], float f)
MINLINE void negate_v2 (float r[2])
MINLINE void negate_v2_v2 (float r[2], const float a[2])
MINLINE void negate_v3 (float r[3])
MINLINE void negate_v3_v3 (float r[3], const float a[3])
MINLINE void negate_v4 (float r[4])
MINLINE void negate_v4_v4 (float r[4], const float a[3])
MINLINE float dot_v2v2 (const float a[2], const float b[2])
MINLINE float dot_v3v3 (const float a[3], const float b[3])
MINLINE float cross_v2v2 (const float a[2], const float b[2])
MINLINE void cross_v3_v3v3 (float r[3], const float a[3], const float b[3])
MINLINE void add_newell_cross_v3_v3v3 (float n[3], const float v_prev[3], const float v_curr[3])
MINLINE void star_m3_v3 (float rmat[3][3], float a[3])
MINLINE float len_squared_v2 (const float v[2])
MINLINE float len_squared_v3 (const float v[3])
MINLINE float len_v2 (const float a[2])
MINLINE float len_v2v2 (const float a[2], const float b[2])
MINLINE float len_squared_v2v2 (const float a[2], const float b[2])
MINLINE float len_v3 (const float a[3])
MINLINE float len_v3v3 (const float a[3], const float b[3])
MINLINE float len_squared_v3v3 (const float a[3], const float b[3])
MINLINE float normalize_v2 (float r[2])
MINLINE float normalize_v2_v2 (float r[2], const float a[2])
MINLINE float normalize_v3 (float r[3])
MINLINE float normalize_v3_v3 (float r[3], const float a[3])
void interp_v2_v2v2 (float r[2], const float a[2], const float b[2], const float t)
void interp_v2_v2v2v2 (float r[2], const float a[2], const float b[2], const float c[3], const float t[3])
void interp_v3_v3v3 (float r[3], const float a[3], const float b[3], const float t)
void interp_v3_v3v3v3 (float p[3], const float v1[3], const float v2[3], const float v3[3], const float w[3])
void interp_v3_v3v3v3v3 (float p[3], const float v1[3], const float v2[3], const float v3[3], const float v4[3], const float w[4])
void interp_v4_v4v4 (float r[4], const float a[4], const float b[4], const float t)
void interp_v4_v4v4v4 (float p[4], const float v1[4], const float v2[4], const float v3[4], const float w[3])
void interp_v4_v4v4v4v4 (float p[4], const float v1[4], const float v2[4], const float v3[4], const float v4[4], const float w[4])
void mid_v3_v3v3 (float r[3], const float a[3], const float b[3])
void mid_v2_v2v2 (float r[2], const float a[2], const float b[2])
MINLINE int is_zero_v3 (const float a[3])
MINLINE int is_zero_v4 (const float a[4])
MINLINE int is_one_v3 (const float a[3])
MINLINE int equals_v2v2 (const float v1[2], const float v2[2])
MINLINE int equals_v3v3 (const float a[3], const float b[3])
MINLINE int compare_v3v3 (const float a[3], const float b[3], const float limit)
MINLINE int compare_len_v3v3 (const float a[3], const float b[3], const float limit)
MINLINE int compare_v4v4 (const float a[4], const float b[4], const float limit)
MINLINE int equals_v4v4 (const float a[4], const float b[4])
MINLINE float line_point_side_v2 (const float l1[2], const float l2[2], const float pt[2])
float angle_v2v2 (const float a[2], const float b[2])
float angle_signed_v2v2 (const float v1[2], const float v2[2])
float angle_v2v2v2 (const float a[2], const float b[2], const float c[2])
float angle_normalized_v2v2 (const float a[2], const float b[2])
float angle_v3v3 (const float a[3], const float b[3])
float angle_v3v3v3 (const float a[3], const float b[3], const float c[3])
float angle_normalized_v3v3 (const float v1[3], const float v2[3])
void angle_tri_v3 (float angles[3], const float v1[3], const float v2[3], const float v3[3])
void angle_quad_v3 (float angles[4], const float v1[3], const float v2[3], const float v3[3], const float v4[3])
void angle_poly_v3 (float *angles, const float *verts[3], int len)
void project_v2_v2v2 (float c[2], const float v1[2], const float v2[2])
void project_v3_v3v3 (float r[3], const float p[3], const float n[3])
void project_v3_plane (float v[3], const float n[3], const float p[3])
void reflect_v3_v3v3 (float r[3], const float v[3], const float n[3])
void ortho_basis_v3v3_v3 (float r1[3], float r2[3], const float a[3])
void bisect_v3_v3v3v3 (float r[3], const float a[3], const float b[3], const float c[3])
void rotate_v3_v3v3fl (float v[3], const float p[3], const float axis[3], const float angle)
void rotate_normalized_v3_v3v3fl (float v[3], const float p[3], const float axis[3], const float angle)
void print_v2 (const char *str, const float a[2])
void print_v3 (const char *str, const float a[3])
void print_v4 (const char *str, const float a[4])
MINLINE void normal_short_to_float_v3 (float r[3], const short n[3])
MINLINE void normal_float_to_short_v3 (short r[3], const float n[3])
void minmax_v3v3_v3 (float min[3], float max[3], const float vec[3])
double dot_vn_vn (const float *array_src_a, const float *array_src_b, const int size)
float normalize_vn_vn (float *array_tar, const float *array_src, const int size)
float normalize_vn (float *array_tar, const int size)
void range_vn_i (int *array_tar, const int size, const int start)
void range_vn_fl (float *array_tar, const int size, const float start, const float step)
void negate_vn (float *array_tar, const int size)
void negate_vn_vn (float *array_tar, const float *array_src, const int size)
void mul_vn_fl (float *array_tar, const int size, const float f)
void mul_vn_vn_fl (float *array_tar, const float *array_src, const int size, const float f)
void add_vn_vn (float *array_tar, const float *array_src, const int size)
void add_vn_vnvn (float *array_tar, const float *array_src_a, const float *array_src_b, const int size)
void sub_vn_vn (float *array_tar, const float *array_src, const int size)
void sub_vn_vnvn (float *array_tar, const float *array_src_a, const float *array_src_b, const int size)
void fill_vn_i (int *array_tar, const int size, const int val)
void fill_vn_ushort (unsigned short *array_tar, const int size, const unsigned short val)
void fill_vn_fl (float *array_tar, const int size, const float val)
Detailed Description
Definition in file BLI_math_vector.h.
Function Documentation
MINLINE void add_newell_cross_v3_v3v3 (float n[3], const float v_prev[3], const float v_curr[3])
Definition at line 487 of file math_vector_inline.c.
Referenced by BLI_edgefill_ex(), bm_face_calc_poly_normal(), bm_face_calc_poly_normal_vertex_cos(), BME_bevel_poly(), and calc_poly_normal().
MINLINE void add_v2_v2 (float r[2], const float a[2])
Definition at line 249 of file math_vector_inline.c.
Referenced by BKE_tracking_stabdata_to_mat4(), draw_distortion(), dynamicPaint_findNeighbourPixel(), ED_uvedit_median(), find_nearest_uv_face(), get_area_imbuf(), grab_clone_apply(), HC_relaxation_iteration_uv(), laplacian_relaxation_iteration_uv(), layerAdd_mloop_origspace(), layerAdd_mloopuv(), node_composit_transform(), paint_space_stroke(), poly_uv_center(), snap_uvs_to_adjacent_unselected(), stitch_calculate_island_snapping(), stitch_init(), stitch_process_data(), uvedit_center(), and uvedit_translate().
MINLINE void add_v2_v2v2 (float r[2], const float a[2], const float b[2])
Definition at line 255 of file math_vector_inline.c.
Referenced by boid_brain(), draw_marker_areas(), draw_marker_outline(), draw_track_path(), flushTransTracking(), followtrack_evaluate(), marker_block_handler(), mouse_on_offset(), p_chart_stretch_minimize(), paint_brush_stroke_add_step(), slide_marker_modal(), uiTemplateMarker(), and uv_image_outset().
MINLINE void add_v3_fl (float r[3], float f)
Definition at line 234 of file math_vector_inline.c.
Referenced by dynamicPaint_paintMesh().
MINLINE void add_v3_v3 (float r[3], const float a[3])
Definition at line 261 of file math_vector_inline.c.
Referenced by _scan_for_ext_spring_forces(), _softbody_calc_forces_slice_in_a_thread(), add_norm_if(), add_normal_aligned(), addnormalsDispList(), alter_co(), apply_tangmat_callback(), applyModifier(), applyProject(), armature_deform_verts(), BKE_metaball_center_median(), BKE_metaball_translate(), BLI_mirrorAlongAxis(), BM_face_calc_center_mean(), BM_loop_interp_from_face(), bm_loop_interp_mdisps(), BM_mesh_bm_to_me(), BM_vert_interp_from_face(), BME_bevel_poly(), bmo_bevel_exec(), bmo_inset_exec(), boid_body(), boid_brain(), boid_find_ground(), bone_connect_to_new_parent(), bone_matrix_translate_y(), brush_add(), brush_comb(), brush_puff(), brush_smooth_do(), brush_smooth_get(), calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), calc_poly_plane(), calc_shapeKeys(), calc_solidify_normals(), calc_tangent_vector(), calc_tw_center(), calculateCenterMedian(), closest_point_on_surface(), cloth_calc_helper_forces(), cloth_collision(), collision_response(), connect_hair(), contarget_get_lattice_mat(), contarget_get_mesh_mat(), createFacepa(), cuboid_do(), curve_center_median(), curve_translate(), cutEdges(), dl_surf_to_renderdata(), dm_calc_normal(), do_clay_brush(), do_clay_strips_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_guides(), do_kink(), do_layer_brush(), do_mesh_smooth_brush(), do_multires_smooth_brush(), do_path_effectors(), do_physical_effector(), do_scrape_brush(), do_snake_hook_brush(), do_texture_effector(), docenter_armature(), draw_em_measure_stats(), draw_particle(), draw_rotation_guide(), draw_xyz_wire(), drawConstraint(), drawnurb(), drawRBpivot(), DS_energy(), dynamicPaint_paintMesh(), edbm_noise_exec(), edbm_rip_invoke__vert(), edbm_sort_faces_exec(), ElementResize(), ElementRotation(), emDM__calcFaceCent(), envmaptex(), explodeMesh(), face_duplilist(), fix_connected_bone(), flyApply(), flyEnd(), get_effector_data(), get_matrix_editbone(), get_next_loop(), getEditDerivedBMesh(), getSingleCoordinate(), getSnapPoint(), getTransformOrientation(), give_parvert(), heat_calc_vnormals(), init_render_curve(), init_rotsys(), integrate_particle(), interp_barycentric_tri_data(), interp_bilinear_quad_data(), isect_plane_plane_v3(), isect_sweeping_sphere_tri_v3(), knife_edge_tri_isect(), layerInterp_shapekey(), make_occ_tree(), make_selection_list_nurb(), make_trans_verts(), markdownSecondarySymmetry(), mdisp_in_mdispquad(), merge_target(), mesh_center_median(), mesh_translate(), meshdeformModifier_do(), minmax_object(), minmax_verts(), multires_set_space(), multiresModifier_base_apply(), multiresModifier_disp_run(), neighbor_average(), nextLengthSubdivision(), ob_draw_RE_motion(), ob_parbone(), ob_parvert3(), object_handle_update(), object_origin_set_exec(), occ_compute_bounces(), offset_child(), offset_to_key(), p_face_stretch(), particle_billboard(), pe_deflect_emitter(), pe_iterate_lengths(), peelDerivedMesh(), project_paint_begin(), psys_make_billboard(), psys_particle_on_dm(), psys_render_simplify_distribution(), psys_thread_create_path(), raycallback(), REEB_AxialSymmetry(), reference_to_scratch(), return_editcurve_indexar(), return_editlattice_indexar(), return_editmesh_indexar(), return_editmesh_vgroup(), rotateflagNurb(), rule_average_speed(), rule_flock(), rule_goal_avoid(), rule_separate(), sb_detect_vertex_collisionCached(), scale_point(), scale_quad(), scale_tri(), sculpt_combine_proxies(), sculpt_stroke_get_location(), sculpt_update_brush_delta(), set_origin_exec(), setNearestAxis3d(), shade_lamp_loop(), Shear(), sk_drawStroke(), sk_flattenStroke(), sk_getSelfIntersections(), sk_interpolateDepth(), sk_straightenStroke(), smoothModifier_do(), snap_curs_to_sel(), snap_sel_to_grid(), softbody_apply_forces(), softbody_calc_forces(), special_transvert_update(), sph_particle_courant(), sphere_do(), static_particle_strand(), subsurf_calculate_limit_positions(), sum_or_add_vertex_tangent(), TargetSnapMedian(), testAxialSymmetry(), trace_reflect(), trace_refract(), translateflagNurb(), v3d_editvertex_buts(), vcloud_estimate_transform(), vertex_dupli__mapFunc(), viewmove_apply(), viewpan_exec(), viewrotate_apply(), vol_get_scattering(), vol_get_transmittance(), volumeintegrate(), voxeldatatex(), where_is_pose_bone(), where_on_path_deform(), and zbufshade_sss_tile().
MINLINE void add_v3_v3v3 (float r[3], const float a[3], const float b[3])
Definition at line 268 of file math_vector_inline.c.
Referenced by _scan_for_ext_spring_forces(), _softbody_calc_forces_slice_in_a_thread(), add_primitive_bone(), alter_co(), applyTranslation(), area_lamp_energy_multisample(), armature_bone_primitive_add_exec(), armature_deform_verts(), arrayModifier_doArray(), axisProjection(), bisect_v3_v3v3v3(), BM_editselection_center(), BM_editselection_normal(), BM_face_multires_bounds_smooth(), BM_loop_calc_face_tangent(), bm_loop_flip_disp(), BMBVH_EdgeVisible(), bmo_collapse_exec(), bmo_inset_exec(), bmo_vertexsmooth_exec(), boid_climb(), boid_find_ground(), bone_align_to_bone(), brush_add(), brush_length(), calc_corner_co(), calc_curve_deform(), calc_solidify_normals(), calchandleNurb_intern(), CalcSnapGeometry(), calculateCenterBound(), camera_view_frame_fit_to_scene(), cdDM_foreachMappedFaceCenter(), check_path_length(), collision_response(), compute_mdisp_quad(), compute_radiance(), createFacepa(), createSlideVerts(), createTransEdge(), curvemap_make_table(), dist_to_plane_normalized_v3(), dist_to_plane_v3(), distribute_threads_exec(), dl_surf_to_renderdata(), dm_calc_normal(), do_crease_brush(), do_hair_dynamics(), do_kink(), do_material_tex(), do_multires_smooth_brush(), do_physical_effector(), do_version_bone_head_tail_237(), doEdgeSlide(), draw_new_particle_system(), draw_particle(), draw_rotation_guide(), draw_sphere_bone_wire(), draw_volume(), draw_xyz_wire(), drawLine(), ED_view3d_win_to_3d(), edbm_blend_from_shape_exec(), edbm_rip_invoke__vert(), ElementResize(), ElementRotation(), get_effector_data(), get_next_loop(), ImageRender::ImageRender(), InputVector(), integrate_particle(), is_quad_convex_v3(), isect_line_line_strict_v3(), isect_line_line_v3(), isect_line_plane_v3(), knife_find_closest_face(), knife_start_cut(), knife_update_active(), M_Geometry_intersect_ray_tri(), meshdeform_intersect(), meshdeform_ray_tree_intersect(), multires_set_space(), multiresModifier_disp_run(), nearest_point_in_tri_surface(), new_particle_duplilist(), ob_parvert3(), object_to_mat4(), old_mdisps_bilinear(), paintface_minmax(), particle_billboard(), pdDoEffectors(), PE_apply_lengths(), pe_iterate_lengths(), pivotcon_evaluate(), planeProjection(), project_brush_radius(), PushPull(), ray_trace(), recalc_emitter_field(), REEB_RadialSymmetry(), render_new_particle_system(), repositionControl(), rule_avoid_collision(), sculpt_flush_pbvhvert_deform(), Shear(), shrink_edgef(), ShrinkFatten(), sk_getStrokeSnapPoint(), snapEdge(), softbody_calc_forces(), special_transvert_update(), strand_eval_point(), subsurf_calculate_limit_positions(), testRadialSymmetry(), testshadowbuf(), ToSphere(), trace_reflect(), trace_refract(), transform_evaluate(), view_zoom_mouseloc(), viewselected_exec(), Warp(), where_is_ik_bone(), and where_is_pose_bone_tail().
MINLINE void add_v4_fl (float r[4], float f)
Definition at line 241 of file math_vector_inline.c.
void add_vn_vn (float * array_tar, const float * array_src, const int size)
Definition at line 513 of file math_vector.c.
References i, and size().
Referenced by Color_iadd(), screen_opengl_render_apply(), and Vector_iadd().
void add_vn_vnvn (float * array_tar, const float * array_src_a, const float * array_src_b, const int size)
Definition at line 523 of file math_vector.c.
References i, and size().
Referenced by Color_add(), Matrix_add(), and Vector_add().
float angle_normalized_v2v2 (const float a[2], const float b[2])
Definition at line 205 of file math_vector.c.
References dot_v2v2(), len_v2v2(), M_PI, and saasin().
Referenced by angle_v2v2(), angle_v2v2v2(), draw_uvs_stretch(), and uv_image_outset().
float angle_normalized_v3v3 (const float v1[3], const float v2[3])
Definition at line 189 of file math_vector.c.
References dot_v3v3(), len_v3v3(), M_PI, and saasin().
Referenced by angle_poly_v3(), angle_quad_v3(), angle_tri_v3(), angle_v3v3(), angle_v3v3v3(), applyModifier(), bevel_list_smooth(), BM_edge_calc_face_angle(), BM_vert_calc_shell_factor(), BME_bevel_get_angle_vert(), bmo_inset_exec(), calc_corner_co(), calc_solidify_normals(), dm_calc_normal(), draw_uvs_stretch(), edbm_dupli_extrude_cursor_invoke(), edbm_select_linked_flat_faces_exec(), edbm_select_sharp_edges_exec(), make_bevel_list_3D_minimum_twist(), project_paint_begin(), project_paint_uvpixel_mask(), RIG_calculateEdgeAngles(), rollBoneByQuatAligned(), rotation_between_vecs_to_quat(), sk_drawEdge(), sk_drawNormal(), solidify_add_thickness(), vec_roll_to_mat3(), and viewrotate_apply().
void angle_poly_v3 (float * angles, const float * verts[3], int len)
Definition at line 258 of file math_vector.c.
References angle_normalized_v3v3(), i, len(), M_PI, normalize_v3(), and sub_v3_v3v3().
Referenced by solidify_add_thickness().
void angle_quad_v3 (float angles[4], const float v1[3], const float v2[3], const float v3[3], const float v4[3])
Definition at line 238 of file math_vector.c.
References angle_normalized_v3v3(), M_PI, normalize_v3(), and sub_v3_v3v3().
float angle_signed_v2v2 (const float v1[2], const float v2[2])
Definition at line 183 of file math_vector.c.
References atan2f, and dot_v2v2().
Referenced by Vector_angle_signed().
void angle_tri_v3 (float angles[3], const float v1[3], const float v2[3], const float v3[3])
Definition at line 220 of file math_vector.c.
References angle_normalized_v3v3(), M_PI, normalize_v3(), and sub_v3_v3v3().
float angle_v2v2 (const float a[2], const float b[2])
Definition at line 167 of file math_vector.c.
References angle_normalized_v2v2(), and normalize_v2().
Referenced by bevel_list_flip_tangents(), sk_detectDeleteGesture(), sk_detectReverseGesture(), and sk_detectTrimGesture().
float angle_v2v2v2 (const float a[2], const float b[2], const float c[2])
Definition at line 150 of file math_vector.c.
References angle_normalized_v2v2(), and normalize_v2().
Referenced by draw_uvs_stretch().
float angle_v3v3 (const float a[3], const float b[3])
Definition at line 140 of file math_vector.c.
References angle_normalized_v3v3(), and normalize_v3_v3().
Referenced by applyModifier(), axisProjection(), BM_face_create_ngon_vcloud(), bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), ED_rollBoneToVector(), measure_facepair(), smooth_view(), test_manipulator_axis(), and viewrotate_apply().
float angle_v3v3v3 (const float a[3], const float b[3], const float c[3])
Definition at line 127 of file math_vector.c.
References angle_normalized_v3v3(), normalize_v3(), and sub_v3_v3v3().
Referenced by BM_loop_calc_face_angle(), BM_vert_calc_edge_angle(), bmo_bevel_exec(), draw_em_measure_stats(), draw_uvs_stretch(), find_ear(), and laplacian_triangle_area().
void bisect_v3_v3v3v3 (float r[3], const float a[3], const float b[3], const float c[3])
Definition at line 310 of file math_vector.c.
References add_v3_v3v3(), normalize_v3(), and sub_v3_v3v3().
Referenced by bevel_list_calc_bisect(), make_bevel_list_3D_zup(), and makeBevelList().
MINLINE int compare_len_v3v3 (const float a[3], const float b[3], const float limit)
Definition at line 690 of file math_vector_inline.c.
Referenced by apply_boid_rule(), and bmesh_finddoubles_common().
MINLINE int compare_v3v3 (const float a[3], const float b[3], const float limit)
Definition at line 680 of file math_vector_inline.c.
References fabsf.
Referenced by BLI_edgefill_ex(), BM_loop_calc_face_tangent(), BME_bevel_get_vec(), bmo_inset_exec(), flushTransParticles(), mesh_octree_find_index(), select_grouped_color(), testvertexnearedge(), and unwrap_exec().
MINLINE int compare_v4v4 (const float a[4], const float b[4], const float limit)
Definition at line 701 of file math_vector_inline.c.
References fabsf.
MINLINE void copy_v2_fl (float r[2], float f)
Definition at line 80 of file math_vector_inline.c.
MINLINE void copy_v2_v2 (float r[2], const float a[2])
Definition at line 59 of file math_vector_inline.c.
Referenced by ActionFCurveToTransData(), applySeqSlide(), bezt_to_transdata(), BKE_movieclip_get_stable_ibuf(), BKE_tracking_add_track(), BKE_tracking_next(), BKE_tracking_stabilize(), bm_corners_to_loops(), bmo_face_reverseuvs_exec(), bmo_face_rotateuvs_exec(), boid_body(), bpy_bmloopuv_uv_set(), brush_jitter_pos(), cancel_mouse_slide(), ccg_loops_to_corners(), cdDM_drawMappedFacesGLSL(), clip_draw_main(), closest_to_line_segment_v2(), create_slide_marker_data(), DM_calc_auto_bump_scale(), DM_init_origspace(), do_rough_end(), draw_distortion(), draw_mesh_text(), draw_tracking_tracks(), draw_uvs_stretch(), dynamicPaint_createUVSurface(), dynamicPaint_findNeighbourPixel(), dynamicPaint_setInitialColor(), ED_clip_point_undistorted_pos(), emDM_getTessFaceDataArray(), find_nearest_tracking_knot_cb(), find_nearest_tracking_segment_cb(), flushTransTracking(), get_area_imbuf(), gp_draw_stroke(), GPU_buffer_copy_uv(), GPU_buffer_copy_uvedge(), grab_clone_invoke(), grab_clone_modal(), HC_relaxation_iteration_uv(), imagewraposa_aniso(), init_render_mesh(), isect_point_face_uv_v2(), isect_seg_seg_v2_point(), laplacian_relaxation_iteration_uv(), layerCopyValue_mloop_origspace(), layerCopyValue_mloopuv(), layerInterp_msticky(), layerSwap_origspace_face(), layerSwap_tface(), line_clip_rect2f(), loops_to_customdata_corners(), M_Geometry_intersect_point_line(), marker_block_handler(), markerToTransDataInit(), mesh_loops_to_mface_corners(), mouse_on_corner(), mouse_select_init_data(), p_chart_stretch_minimize(), paint_brush_stroke_add_step(), paint_space_stroke(), project_bucket_clip_face(), project_paint_face_init(), project_paint_op(), project_paint_uvpixel_init(), put_postprocessed_frame_to_cache(), put_stabilized_frame_to_cache(), raycallback(), remap_uvs_15(), remap_uvs_19_21_22(), remap_uvs_23(), remap_uvs_3_6_9_12(), remap_uvs_5_10(), remap_uvs_7_11_13_14(), sculpt_update_brush_delta(), sculpt_update_cache_invariants(), sculpt_update_cache_variants(), set_subsurf_uv(), snap_uvs_to_cursor(), ss_sync_from_uv(), stitch_process_data(), to_pixel_space(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uvedit_vertex_buttons(), uvprojectModifier_do(), view3d_boxview_clip(), view_pan_exit(), view_pan_init(), view_pan_modal(), and widget_verts_to_quad_strip().
MINLINE void copy_v2_v2_char (char r[2], const char a[2])
Definition at line 102 of file math_vector_inline.c.
MINLINE void copy_v2_v2_int (int r[2], const int a[2])
Definition at line 146 of file math_vector_inline.c.
Referenced by console_draw_string(), ED_view3d_autodist_depth_seg(), edbm_vertex_slide_modal(), flyEvent(), gp_stroke_addpoint(), gp_stroke_newfrombuffer(), gp_stroke_smooth(), handleMouseInput(), initFlyInfo(), initTransInfo(), transformEvent(), and vtx_slide_find_edge().
MINLINE void copy_v2_v2_short (short r[2], const short a[2])
Definition at line 124 of file math_vector_inline.c.
MINLINE void copy_v2db_v2fl (double r[2], const float a[2])
Definition at line 190 of file math_vector_inline.c.
MINLINE void copy_v2fl_v2db (float r[2], const double a[2])
Definition at line 168 of file math_vector_inline.c.
MINLINE void copy_v3_fl (float r[3], float f)
Definition at line 86 of file math_vector_inline.c.
Referenced by add_curve(), barycentric_weights(), and barycentric_weights_v2().
MINLINE void copy_v3_v3 (float r[3], const float a[3])
Definition at line 65 of file math_vector_inline.c.
Referenced by _softbody_calc_forces_slice_in_a_thread(), actcon_get_tarmat(), AnimationImporter::add_bone_animation_sampled(), add_hook_object(), add_in_range(), add_metaball_primitive(), add_nearest(), add_points_bone(), add_pose_transdata(), add_primitive_bone(), add_render_lamp(), add_tface_color_layer(), add_vertex_invoke(), add_verts_to_dgroups(), add_vgroups__mapFunc(), addDepthPeel(), addSnapPoint(), Align(), alter_co(), ambient_occlusion_apply(), apply_armature_pose2bones_exec(), AnimationImporter::apply_matrix_curves(), apply_objects_internal(), apply_project_float(), apply_targetless_ik(), applyAxisConstraintRot(), applyAxisConstraintVec(), applyModifier(), applyObjectConstraintRot(), applyObjectConstraintVec(), applyProject(), applyTranslation(), applyTransObjects(), armature_bone_primitive_add_exec(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_click_extrude_invoke(), armature_deform_verts(), armature_extrude_exec(), armature_fill_bones_exec(), armature_loc_pose_to_bone(), armature_loc_world_to_pose(), armature_subdivide_exec(), atm_tile(), AtmospherePixleShader(), axis_angle_to_gimbal_axis(), axisProjection(), b_bone_spline_setup(), bake_shade(), barycentric_transform(), base_callback(), basic_integrate(), bevel_list_cyclic_fix_3D(), bevelinside(), bevels_to_filledpoly(), bezt_to_transdata(), BIF_draw_manipulator(), blendColors(), BlenderWorldInfo::BlenderWorldInfo(), BLI_addfillvert(), BLI_bvhtree_bb_raycast(), BLI_bvhtree_ray_cast(), BLI_edgefill_ex(), BLI_kdtree_find_nearest(), BLI_kdtree_insert(), BLI_pbvh_apply_vertCos(), BLI_pbvh_get_vertCos(), BLI_pbvh_node_get_BB(), BLI_pbvh_node_get_original_BB(), BLI_pbvh_raycast(), BLI_pbvh_redraw_BB(), BM_editselection_center(), BM_editselection_normal(), bm_face_attrs_copy(), BM_face_calc_area(), bm_face_goodline(), BM_face_interp_from_face(), BM_face_legal_splits(), BM_face_multires_bounds_smooth(), BM_face_split(), BM_face_split_n(), BM_face_triangulate(), BM_loop_calc_face_normal(), BM_loop_interp_from_face(), bm_loop_interp_mdisps(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), BM_mesh_copy(), bm_vert_attrs_copy(), BM_vert_create(), BM_vert_interp_from_face(), BMBVH_EdgeVisible(), BMBVH_FindClosestVert(), BMBVH_NewBVH(), BMBVH_RayCast(), BME_assign_transdata(), BME_bevel_poly(), bmo_collapse_exec(), bmo_esubd_exec(), bmo_inset_exec(), bmo_pointmerge_exec(), bmo_similarfaces_exec(), BMO_slot_vec_get(), BMO_slot_vec_set(), bmo_translate_exec(), bmo_vertexsmooth_exec(), bmvert_to_mvert(), boid_body(), boid_brain(), boid_climb(), boid_find_ground(), boids_precalc_rules(), bone_connect_to_existing_parent(), bone_connect_to_new_parent(), bone_matrix_translate_y(), bones_merge(), boundInsert(), box_minmax_bounds_m4(), BPy_BMLayerItem_SetItem(), brush_comb(), brush_imbuf_new(), brush_length(), brush_painter_do_partial(), brush_puff(), brush_smooth_do(), bspface_init_strand(), KX_NavMeshObject::BuildVertIndArrays(), bvhselftree_build_from_cloth(), bvhselftree_update_from_cloth(), bvhtree_build_from_cloth(), bvhtree_build_from_mvert(), bvhtree_from_mesh_edges(), bvhtree_from_mesh_faces(), bvhtree_update_from_cloth(), bvhtree_update_from_mvert(), cache_key_incremental_rotation(), cache_occ_samples(), cache_strand_surface(), cage_mapped_verts_callback(), calc_area_normal(), calc_area_normal_and_flatten_center(), calc_corner_co(), calc_curve_deform(), calc_latt_deform(), calc_nearest_point(), calc_ocval_face(), calc_sculpt_normal(), calc_sculpt_plane(), calc_shapeKeys(), calc_solidify_normals(), calc_vertexnormals(), CalcSnapGeometry(), calculateCenter(), calculateCenter2D(), calculateCenterBound(), calculateCenterCursor(), calculateCenterMedian(), calculateTransformCenter(), camera_view_frame_fit_to_scene(), ccd_mesh_make(), ccd_mesh_update(), ccgDM_copyFinalVertArray(), ccgDM_getFinalVert(), ccgDM_getFinalVertCo(), ccgdm_getVertCos(), CDDM_apply_vert_coords(), cdDM_drawMappedFacesGLSL(), CDDM_from_BMEditMesh(), cdDM_getVertCo(), cdDM_getVertCos(), childof_evaluate(), choose_winner(), clampto_evaluate(), clip_line_plane(), clipMirrorModifier(), cloneArc(), cloneControl(), closest_point_on_surface(), closest_to_line_segment_v3(), cloth_bvh_objcollisions_resolve(), cloth_calc_force(), cloth_calc_helper_forces(), cloth_calc_spring_force(), cloth_collision_response_static(), cloth_from_object(), cloth_to_object(), collision_check(), collision_fail(), collision_newton_rhapson(), collision_point_velocity(), collision_response(), Color_CreatePyObject(), colorfn(), column_vectors_to_mat3(), compatible_bump_compute(), compute_mdisp_quad(), compute_radiance(), connect_hair(), constraint_mat_convertspace(), constraint_target_to_mat4(), constraintTransLim(), contarget_get_lattice_mat(), contarget_get_mesh_mat(), convert_tree(), convertspline(), copy_attr(), copy_object_transform(), copy_pose_channel_data(), copy_pose_result(), copyData(), cp_fmatrix(), createRepresentation(), createSlideVerts(), createSpaceNormal(), createSpaceNormalTangent(), createTransArmatureVerts(), createTransCurveVerts(), createTransLatticeVerts(), createTransMBallVerts(), createTransNlaData(), createTransParticleVerts(), createTransTexspace(), createVertsTrisData(), cubemap_glob(), cubemap_ob(), cuboid_do(), curve_applyVertexCos(), curve_deform_vector(), curve_deform_verts(), curve_getKeyVertexCos(), curve_getVertexCos(), curve_to_displist(), curve_to_key(), curvemap_make_table(), curvemapping_set_black_white(), damptrack_evaluate(), database_init_objects(), TransformBase::decompose(), deformVerts(), direct_link_object(), displace_render_vert(), dist_bone_deform(), distlimit_evaluate(), distribute_grid(), distribute_threads_init_data(), dl_surf_to_renderdata(), DM_to_bmesh_ex(), DM_to_meshkey(), do_bake_shade(), do_clay_strips_brush(), do_color_key(), do_copy_a_rgba(), do_copy_rgb(), do_curves_fac(), do_diff_matte(), do_distance_matte(), do_filter3(), do_grab_brush(), do_guides(), do_hair_dynamics(), do_inflate_brush(), do_invert(), do_kink(), do_lamp_tex(), do_material_tex(), do_mix_rgb(), do_nudge_brush(), do_path_effectors(), do_physical_effector(), do_projectpaint_draw_f(), do_rotate_brush(), do_rough(), do_scanconvert_strand(), do_sky_tex(), do_snake_hook_brush(), do_step_cloth(), do_texture_effector(), do_thumb_brush(), do_version_bone_head_tail_237(), do_versions(), do_versions_socket_default_value(), do_volume_tex(), docenter_armature(), doEdgeSlide(), draw_em_measure_stats(), draw_forcefield(), draw_new_particle_system(), draw_object(), draw_particle(), draw_pose_dofs(), draw_ptcache_edit(), draw_sphere_bone_wire(), draw_tface__set_draw_legacy(), draw_volume(), draw_xyz_wire(), drawcone(), drawHelpline(), drawlamp(), drawLine(), drawPropCircle(), drawRBpivot(), drawspiral(), drawSubdividedStrokeBy(), drawtexspace(), drawtube(), duplicate_pose_channel_data(), dvar_eval_locDiff(), dvar_eval_transChan(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_generateBakeData(), dynamicPaint_mixPaintColors(), dynamicPaint_paintMesh(), dynamicPaint_paintParticles(), dynamicPaint_paintSinglePoint(), dynamicPaint_prepareEffectStep(), dynamicPaint_setInitialColor(), dynamicPaint_surfacePreStep(), ED_armature_from_edit(), ED_curve_actSelection(), ED_image_draw_info(), ED_node_shader_default(), ED_object_base_init_transform(), ED_object_location_from_view(), ED_object_modifier_convert(), ED_object_new_primitive_matrix(), ED_view3d_boundbox_clip(), ED_view3d_draw_offscreen(), ED_view3d_global_to_vector(), ED_view3d_project_float_v2(), ED_view3d_project_float_v3(), ED_view3d_win_to_3d(), ED_view3d_win_to_segment_clip(), ED_view3d_win_to_vector(), edbm_blend_from_shape_exec(), edbm_dupli_extrude_cursor_invoke(), edbm_extrude_edge(), edbm_extrude_face_indiv(), edbm_knife_cut_exec(), edbm_sort_faces_exec(), EDBM_verts_mirror_apply(), edgering_sel(), edit_to_particle(), editbmesh_get_vertex_cos(), ElementResize(), ElementRotation(), emDM_copyVertArray(), emDM_getVert(), emDM_getVertCos(), envmaptex(), Euler_CreatePyObject(), eulO_to_gimbal_axis(), AnimationImporter::evaluate_animation(), exec_strandsurface_sample(), execute_posetree(), execute_scene(), face_duplilist(), fcurves_to_pchan_links_get(), ff_visible_quad(), fill_add_joint(), filldisplist(), finalize_render_object(), finalizeControl(), flushTransParticles(), flyApply(), flyEnd(), followpath_get_tarmat(), followtrack_evaluate(), font_duplilist(), get_angular_velocity_vector(), get_cpa_texture(), get_editbmesh_orco_verts(), get_effector_data(), get_mesh_orco_verts(), get_new_constraint_target(), get_next_loop(), get_offset_bone_mat(), get_strand_normal(), get_texture_coords(), get_vert2geom_distance(), getEditBoneRollUpAxis(), getEditDerivedBMesh(), GetNormal(), GetPosition(), GetSkyXYZRadiancef(), getSnapPoint(), getTransformOrientation(), getViewVector(), give_base_to_groups(), give_parvert(), global_bounds_obi(), globallen(), gp_get_3d_reference(), gp_paint_initstroke(), gp_stroke_to_bezier(), gp_stroke_to_path(), gp_strokepoint_convertcoords(), GPU_buffer_copy_normal(), GPU_buffer_copy_vertex(), GPU_lamp_update(), GPU_material_bind(), GPU_material_bind_uniforms(), gpu_material_to_fixed(), GPU_scene_object_lights(), GPU_update_grid_buffers(), GPU_update_mesh_buffers(), hair_to_particle(), harmonic_coordinates_bind(), headerTranslation(), heat_ray_source_visible(), heat_source_distance(), ibuf_get_color(), ibuftoimage(), image_sample_line_exec(), ImageRender::ImageRender(), imagewraposa(), imapaint_project(), imapaint_tri_weights(), IMB_buffer_float_from_float(), imb_savetiff(), implicit_init(), implicit_set_positions(), implicit_solver(), init_lfvector(), init_render_curve(), init_render_dm(), init_render_mball(), init_render_mesh(), init_render_world(), init_rotsys(), init_tex_mapping(), initElbeemMesh(), initFlyInfo(), initRotation(), initstar(), initTransform(), initWarp(), integrate_particle(), interp_barycentric_tri_data(), interp_bilinear_grid(), interp_bilinear_quad_data(), InterpCSGFace(), intersect_dm_quad_weights(), isb_make_buffer_transp(), isec_tri_quad(), isec_tri_quad_neighbour(), isect_line_line_v3(), isect_sweeping_sphere_tri_v3(), join_mesh_exec(), key_block_get_data(), key_to_curve(), key_to_latt(), key_to_mesh(), key_to_vertcos(), kinematic_get_tarmat(), knife_add_cut(), knife_edge_tri_isect(), knife_find_closest_edge(), knife_find_closest_vert(), knife_find_line_hits(), knife_make_chain_cut(), knife_sample_screen_density(), knife_split_edge(), knife_start_cut(), knifetool_draw(), lamp_get_visibility(), latt_to_key(), lattice_applyVertexCos(), lattice_getVertexCos(), lib_link_screen_restore(), limit_dist_v3(), load_editLatt(), loclike_evaluate(), M_Geometry_intersect_line_line(), M_Geometry_intersect_point_line(), M_Geometry_intersect_ray_tri(), make_bevel_list_3D_tangent(), make_bevel_list_segment_3D(), make_boneList(), make_occ_tree(), make_orco_curve(), make_render_halos(), make_snap(), make_trans_verts(), make_vertexcos__mapFunc(), make_vertexcosnos__mapFunc(), makeBevelList(), markerToTransCurveDataInit(), markerToTransDataInit(), mat3_to_compatible_eul(), mat3_to_compatible_eulO(), mat3_to_eul(), mat3_to_eul2(), mat3_to_eulO(), mat3_to_eulo2(), mat3_to_vec_roll(), mat4_to_dquat(), mat4_to_loc_rot_size(), matrix_as_3x3(), Matrix_to_euler(), Matrix_translation_set(), mball_to_mesh(), merge_target(), mesh_calc_normals_mapping_ex(), mesh_calc_poly_area(), mesh_deform_bind(), mesh_edges_nearest_point(), mesh_faces_nearest_point(), mesh_faces_nearest_point_dp(), mesh_get_texspace(), mesh_getVertexCos(), mesh_octree_table(), mesh_recalcTessellation(), mesh_to_curve(), mesh_to_key(), meshdeform_dynamic_bind(), meshdeform_inside_cage(), meshdeform_intersect(), meshdeform_matrix_solve(), meshdeform_ray_tree_intersect(), meshdeformModifier_do(), minmax_evaluate(), minmax_object(), minmax_verts(), mixColors(), motionpaths_calc_bake_targets(), moveCloserToDistanceFromPlane(), mul_m3_v3(), multires_copy_dm_grid(), multires_copy_grid(), multires_load_old_dm(), multires_mvert_to_ss(), multires_set_space(), multiresbake_get_normal(), multiresModifier_base_apply(), multitex(), multitex_nodes(), mvert_to_particle(), my_tex_space_mesh(), ndof_orbit_invoke(), nearest_point_in_tri_surface(), neighbor_average(), new_knife_vert(), new_particle_duplilist(), new_primitive_matrix(), newRigNode(), newRigNodeHead(), nextAdaptativeSubdivision(), nextFixedSubdivision(), nextLengthSubdivision(), ngon_fake_area(), node_buts_curvecol(), node_composit_exec_normal(), node_composit_exec_texture(), node_shader_exec_camera(), node_shader_exec_geom(), node_shader_exec_invert(), node_shader_exec_material(), node_shader_exec_mix_rgb(), node_shader_exec_normal(), node_shader_exec_rgb(), node_shader_exec_texture(), node_socket_convert_default_value(), nodeShaderSynchronizeID(), nodestack_get_vec(), NodeToTransData(), normal_projection_project_vertex(), ntap_bump_compute(), nurbs_to_mdata_customdb(), ob_parbone(), ob_parcurve(), ob_parvert3(), object_clear_rot(), object_hook_assign_exec(), object_make_proxy(), object_origin_set_exec(), object_shape_key_mirror(), object_tfm_backup(), object_tfm_restore(), ObjectToTransData(), obmat_to_viewmat(), occ_build_dco(), occ_face(), occ_form_factor(), occ_lookup(), occ_shade(), occ_sum_occlusion(), occ_visible_quad(), octree_fill_rayface(), offset_child(), p_face_stretch(), p_vert_add(), p_vert_copy(), paintface_minmax(), particle_billboard(), particle_intersect_dm(), particle_normal_ren(), pbvh_update_normals(), pchan_bone_deform(), pchan_clear_rot(), pchan_to_mat4(), pchan_to_pose_mat(), pdDoEffectors(), pe_deflect_emitter(), PE_lasso_select(), PE_minmax(), PE_mirror_particle(), PE_update_mirror_cache(), peelDerivedMesh(), pivotcon_evaluate(), planeProjection(), plugintex(), point_inside_obi(), pointdensity_cache_object(), pointdensity_cache_psys(), pointdensitytex(), pose_bone_do_paste(), pose_grab_with_ik_add(), poseAnim_mapping_reset(), precache_init_parts(), precalc_guides(), precalculate_effector(), project_float_noclip(), project_from_camera(), project_from_view(), project_int(), project_int_noclip(), project_paint_begin(), project_paint_begin_clone(), project_paint_face_init(), project_paint_PickFace(), project_renderdata(), project_short(), project_short_noclip(), psys_cache_edit_paths(), psys_face_mat(), psys_get_birth_coordinates(), psys_get_dupli_path_transform(), psys_get_from_key(), psys_get_particle_on_path(), psys_get_texture(), psys_interpolate_face(), psys_make_billboard(), psys_mat_hair_to_object(), psys_mat_hair_to_orco(), psys_particle_on_dm(), psys_particle_on_emitter(), psys_particle_on_shape(), psys_render_projected_area(), psys_render_simplify_distribution(), psys_thread_create_path(), ptcache_cloth_interpolate(), ptcache_softbody_interpolate(), put_postprocessed_frame_to_cache(), quad_co(), Quaternion_mul(), ray_ao_qmc(), ray_ao_spheresamp(), ray_fadeout_endcolor(), ray_shadow(), ray_shadow_jitter(), ray_shadow_jittered_coords(), ray_shadow_qmc(), ray_trace(), ray_trace_shadow_rad(), ray_trace_shadow_tra(), raycallback(), rayface_from_coords(), RE_Database_Baking(), RE_Database_FromScene(), RE_inithalo(), RE_inithalo_particle(), RE_make_sticky(), RE_rayobject_blibvh_intersect(), RE_rayobject_instance_intersect(), RE_rayobject_octree_intersect(), RE_sample_material_color(), RE_vlakren_copy(), RE_vlakren_get_normal(), recalc_emitter_field(), recalcData_view3d(), REEB_AxialSymmetry(), REEB_RadialSymmetry(), reference_to_scratch(), reflect_v3_v3v3(), refraction(), rekey_particle(), rekey_particle_to_time(), remove_doubles_exec(), remove_tagged_keys(), render_lighting_halo(), render_new_particle_system(), repositionBone(), repositionControl(), Resize(), ResizeBetween(), resizelattice(), restore_localviewdata(), restoreElement(), RIG_addControlBone(), RIG_addEdgeToArc(), RIG_appendEdgeToArc(), RIG_parentControl(), RIG_removeUneededOffsets(), rollBoneByQuat(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), Rotation(), RotationBetween(), rotlike_evaluate(), rotlimit_evaluate(), rtbuild_add(), rtbuild_heuristic_object_split(), rule_average_speed(), rule_avoid_collision(), rule_fight(), rule_follow_leader(), rule_goal_avoid(), AnimationExporter::sample_animation(), sample_occ(), sample_occ_cache(), sample_occ_tree(), save_hair(), sb_deflect_face(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), SB_estimate_transform(), scatter_tree_new(), scatter_tree_sample(), scopes_update(), sculpt_brush_test_init(), sculpt_combine_proxies(), sculpt_flush_pbvhvert_deform(), sculpt_flush_stroke_deform(), sculpt_restore_mesh(), sculpt_stroke_get_location(), sculpt_undo_restore_deformed(), sculpt_undo_store_coords(), sculpt_update_brush_delta(), sculpt_update_cache_invariants(), sculpt_update_cache_variants(), sculpt_vertcos_to_key(), SeqSlide(), SeqToTransData(), set_3dcursor_invoke(), set_axis(), set_mapped_co(), set_origin_exec(), set_plane_exec(), setBoneRollFromNormal(), setNearestAxis3d(), SetTSpace(), setup_stack(), setviewmatrixview3d(), shade_input_calc_viewco(), shade_input_do_shade(), shade_input_set_normals(), shade_input_set_shade_texco(), shade_input_set_strand(), shade_input_set_strand_texco(), shade_input_set_triangle_i(), shade_input_set_uv(), shade_input_set_vertex_normals(), shade_intersection(), shade_lamp_loop(), shade_one_light(), shade_ray(), shade_sample_sss(), shade_volume_shadow(), shadeSkyPixel(), shadeSkyView(), shadowbuf_autoclip(), shadowbuf_project_co(), shape_propagate(), shapekey_layers_to_keyblocks(), ShrinkFatten(), shrinkwrap_calc_nearest_surface_point(), shrinkwrap_calc_nearest_vertex(), shrinkwrap_calc_normal_projection(), shrinkwrap_evaluate(), shrinkwrap_get_tarmat(), SimpleDeformModifier_do(), sk_addStrokeSnapPoint(), sk_applyCutGesture(), sk_applyTrimGesture(), sk_convertStroke(), sk_drawStroke(), sk_flattenStroke(), sk_getStrokePoint(), sk_getStrokeSnapPoint(), sk_pointToNode(), sk_projectDrawPoint(), sk_straightenStroke(), sk_strokeToArc(), smooth_view(), snap_curs_to_active(), snap_curs_to_sel(), snap_sel_to_curs(), snap_sel_to_grid(), snapArmature(), snapDerivedMesh(), snapEdge(), snapVertex(), softbody_apply_forces(), softbody_apply_goalsnap(), softbody_calc_forces(), softbody_reset(), softbody_restore_prev_step(), softbody_to_object(), softbody_update_positions(), solve_parenting(), special_transvert_update(), speedvector_project(), sph_force_cb(), sph_particle_courant(), sphere_do(), spin_invoke(), splineik_evaluate_bone(), spotvolume(), springs_from_mesh(), stabilization_auto_scale_factor(), static_particle_strand(), static_particle_wire(), strand_eval_point(), strand_minmax(), stretchto_evaluate(), stucci(), subdivide_particle(), subdivideArcBy(), subdividenurb(), sum_or_add_vertex_tangent(), surfaceGenerateGrid(), target_callback(), TargetSnapActive(), TargetSnapCenter(), TargetSnapClosest(), testAxialSymmetry(), testRadialSymmetry(), tex_space_mesh(), texture_procedural(), texture_rgb_blend(), trace_reflect(), trace_refract(), traceray(), track_colors(), track_copy_color_exec(), Trackball(), tracking_segment_start_cb(), transform_armature_mirror_update(), transform_evaluate(), AnimationImporter::translate_animation_OLD(), Translation(), TransMat3ToSize(), typecheck_compbuf(), ui_apply_button(), ui_block_func_COL(), ui_blockopen_begin(), ui_draw_but_HSVCIRCLE(), ui_draw_gradient(), ui_get_but_vectorf(), ui_handle_button_return_submenu(), ui_ndofedit_but_HSVCUBE(), ui_numedit_begin(), ui_numedit_but_HSVCIRCLE(), ui_numedit_but_HSVCUBE(), ui_set_but_vectorf(), ui_tooltip_region_draw_cb(), ui_update_block_buts_rgb(), uiBlockPicker(), update_world_cos(), BL_SkinDeformer::UpdateInternal(), uvprojectModifier_do(), UVsToTransData(), vcloud_estimate_transform(), vec_apply_track(), vectomat(), Vector_mul(), vertcos_to_key(), vertex_dupli__mapFunc(), vertsearchcallback(), VertsToTransData(), view3d_align_axis_to_vector(), view3d_boxview_copy(), view3d_cached_text_draw_add(), view3d_camera_to_view_selected_exec(), view3d_clipping_test(), view3d_main_area_draw_objects(), view3d_project_short_clip(), view3d_project_short_clip_persmat(), view3d_project_short_noclip(), view3d_smoothview_invoke(), view3d_split_250(), view3d_zoom_border_exec(), view_zoom_mouseloc(), viewdolly_exec(), viewops_data_create(), vieworbit_exec(), viewpixel_to_lampbuf(), viewrotate_apply(), vol_get_bounds(), vol_get_emission(), vol_get_reflection_color(), vol_get_shadow(), vol_precache_part(), vol_shade_one_lamp(), vol_trace_behind(), volume_trace(), voxeldatatex(), vtx_slide_set_frame(), vtx_slide_update(), Warp(), warpModifier_do(), where_is_armature_bone(), where_is_ik_bone(), where_is_pose(), where_is_pose_bone(), where_is_pose_bone_tail(), write_node_socket(), zbuf_part_project(), zbuf_render_project(), zbuffer_abuf(), zbufline(), zbufline_onlyZ(), and zbuflineAc().
MINLINE void copy_v3_v3_char (char r[3], const char a[3])
Definition at line 108 of file math_vector_inline.c.
Referenced by acf_generic_channel_color(), GPU_buffer_copy_color3(), set_pchan_glColor(), widget_box(), widget_numslider(), widget_state(), widget_state_menu_item(), widget_state_option_menu(), and widget_state_pulldown().
MINLINE void copy_v3_v3_int (int r[3], const int a[3])
Definition at line 152 of file math_vector_inline.c.
Referenced by init_frame_smoke(), and precache_init_parts().
MINLINE void copy_v3_v3_short (short r[3], const short a[3])
Definition at line 130 of file math_vector_inline.c.
Referenced by CDDM_apply_vert_normals(), sculpt_restore_mesh(), and sculpt_undo_store_coords().
MINLINE void copy_v3db_v3fl (double r[3], const float a[3])
Definition at line 196 of file math_vector_inline.c.
Referenced by draw_manipulator_rotate(), mesh_calc_ngon_normal(), mesh_calc_ngon_normal_coords(), and spothalo().
MINLINE void copy_v3fl_v3db (float r[3], const double a[3])
Definition at line 174 of file math_vector_inline.c.
Referenced by ED_view3d_calc_clipping().
MINLINE void copy_v4_fl (float r[4], float f)
Definition at line 93 of file math_vector_inline.c.
MINLINE void copy_v4_v4 (float r[4], const float a[4])
Definition at line 72 of file math_vector_inline.c.
Referenced by add_passes(), add_transp_speed(), addtosamp_shr(), BKE_image_buf_fill_color(), blur_with_reference(), cache_key_incremental_rotation(), cdDM_drawMappedFacesGLSL(), colorfn(), copy_attr(), copy_stack(), do_alphaover_key(), do_alphaover_mixed(), do_alphaover_premul(), do_bake_shade(), do_copy_rgba(), do_copy_split_rgba(), do_filter3(), do_filter_edge(), do_hue_sat_fac(), do_invert_fac(), do_proc(), do_projectpaint_thread(), do_versions_socket_default_value(), do_zcombine(), draw_tracking_tracks(), ED_image_draw_info(), ED_preview_shader_job(), gp_draw_data(), GPU_material_bind_uniforms(), ibuf_get_color(), init_render_mesh(), initTransform(), KX_FontObject::KX_FontObject(), lamp_get_shadow(), move_stack(), node_composit_exec_normalize(), node_composit_exec_rgb(), node_composit_exec_scale(), node_gpu_stack_from_data(), node_shader_exec_material(), node_shader_exec_output(), node_socket_convert_default_value(), nodestack_get_vec(), preview_prepare_scene(), project_paint_end(), project_paint_PickColor(), psys_map_index_on_dm(), ray_shadow(), setup_stack(), shade_input_do_shade(), shade_input_set_strand_texco(), shade_lamp_loop(), sky_tile(), volume_trace(), write_node_socket(), zbuf_part_project(), zbuf_shadow_project(), zbufclipwire(), and zbufsinglewire().
MINLINE void copy_v4_v4_char (char r[4], const char a[4])
Definition at line 115 of file math_vector_inline.c.
Referenced by cdDM_drawMappedFacesGLSL(), DM_update_weight_mcol(), uiWidgetScrollDraw(), widget_state(), widget_state_menu_item(), and widget_state_pulldown().
MINLINE void copy_v4_v4_int (int r[4], const int a[4])
Definition at line 159 of file math_vector_inline.c.
MINLINE void copy_v4_v4_short (short r[4], const short a[4])
Definition at line 137 of file math_vector_inline.c.
MINLINE void copy_v4db_v4fl (double r[4], const float a[4])
Definition at line 203 of file math_vector_inline.c.
Referenced by ED_view3d_clipping_set().
MINLINE void copy_v4fl_v4db (float r[4], const double a[4])
Definition at line 181 of file math_vector_inline.c.
MINLINE float cross_v2v2 (const float a[2], const float b[2])
Definition at line 471 of file math_vector_inline.c.
Referenced by stabilization_auto_scale_factor(), and stitch_island_calculate_vert_rotation().
MINLINE void cross_v3_v3v3 (float r[3], const float a[3], const float b[3])
Definition at line 476 of file math_vector_inline.c.
Referenced by applyModifier(), applyTranslation(), area_quad_v3(), area_tri_v3(), axis_angle_to_gimbal_axis(), axisProjection(), bake_shade(), basic_rotate(), bevel_list_smooth(), BM_edge_calc_face_tangent(), BM_edge_rotate_check_degenerate(), BM_editselection_normal(), BM_editselection_plane(), BM_face_create_ngon_vcloud(), BM_loop_calc_face_tangent(), bm_loop_flip_disp(), BME_bevel_get_angle(), BME_bevel_poly(), BME_bevel_project_vec(), BME_bevel_split_edge(), bmo_edgenet_prepare(), bmo_inset_exec(), boid_body(), brush_puff(), cache_key_incremental_rotation(), calc_corner_co(), collision_point_on_surface(), collision_response(), compatible_bump_compute(), contarget_get_mesh_mat(), convex(), costDistance(), cotan_weight(), createSpaceNormal(), createSpaceNormalTangent(), damptrack_evaluate(), DM_calc_auto_bump_scale(), do_clay_strips_brush(), do_guides(), do_material_tex(), do_nudge_brush(), do_physical_effector(), do_thumb_brush(), draw_rotation_guide(), draw_sphere_bone_dist(), draw_sphere_bone_wire(), ED_rollBoneToVector(), edbm_dupli_extrude_cursor_invoke(), ff_quad_form_factor(), flush_pixel(), get_angular_velocity_vector(), get_next_loop(), get_strand_normal(), getTransformOrientation(), ImageRender::ImageRender(), init_rotsys(), interp_weights_face_v3(), is_negative_m3(), is_negative_m4(), isec_tri_quad(), isec_tri_quad_neighbour(), isect_line_line_strict_v3(), isect_line_line_v3(), isect_line_tri_v3(), isect_plane_plane_v3(), isect_ray_plane_v3(), isect_ray_tri_epsilon_v3(), isect_ray_tri_threshold_v3(), isect_ray_tri_v3(), isect_sweeping_sphere_tri_v3(), locktrack_evaluate(), M_Geometry_intersect_ray_tri(), make_bevel_list_3D_minimum_twist(), make_bevel_list_3D_tangent(), mean_value_half_tan(), meshdeform_tri_intersect(), nr_distance_to_edge(), nr_signed_distance_to_plane(), ntap_bump_compute(), occ_quad_form_factor(), orthogonalize_m3(), orthogonalize_m4(), poly_rotate_plane(), project_brush_radius(), psys_get_birth_coordinates(), psys_get_dupli_path_transform(), psys_make_billboard(), REEB_RadialSymmetry(), RIG_calculateEdgeAngles(), RIG_parentControl(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), rotate(), rotation_between_vecs_to_quat(), RotationBetween(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), set_axis(), set_plane_exec(), shade_input_set_strand(), shade_one_light(), sk_drawEdge(), sk_drawNormal(), splineik_evaluate_bone(), spotvolume(), static_particle_strand(), strand_eval_point(), stretchto_evaluate(), surface_determineForceTargetPoints(), tangent_from_uv(), testAxialSymmetry(), testRadialSymmetry(), trace_reflect(), triatomat(), vec_roll_to_mat3(), vectomat(), Vector_cross(), view3d_align_axis_to_vector(), and viewrotate_apply().
MINLINE float dot_v2v2 (const float a[2], const float b[2])
Definition at line 461 of file math_vector_inline.c.
Referenced by angle_normalized_v2v2(), angle_signed_v2v2(), boid_body(), boid_brain(), calc_vp_strength_dl(), closest_to_line_v2(), DM_calc_auto_bump_scale(), HC_relaxation_iteration_uv(), isect_line_sphere_v2(), isect_seg_seg_v2_point(), laplacian_relaxation_iteration_uv(), len_squared_v2v2(), line_point_factor_v2(), normalize_v2_v2(), project_v2_v2v2(), rule_average_speed(), stitch_island_calculate_vert_rotation(), texpaint_break_stroke(), uv_sculpt_stroke_apply(), and uv_sculpt_stroke_init().
MINLINE float dot_v3v3 (const float a[3], const float b[3])
Definition at line 466 of file math_vector_inline.c.
Referenced by _scan_for_ext_spring_forces(), accumulate_vertex_normals(), accumulate_vertex_normals_poly(), add_norm_if(), add_normal_aligned(), alter_co(), angle_normalized_v3v3(), apply_heights_callback(), applyAxisConstraintRot(), applyObjectConstraintRot(), applyTranslation(), area_lamp_energy_multisample(), arrayModifier_doArray(), as_findvertex(), as_testvertex(), AtmospherePixleShader(), axisProjection(), basic_rotate(), BLI_bvhtree_find_nearest(), BLI_bvhtree_ray_cast(), BLI_edgefill_ex(), BM_edge_rotate_check_degenerate(), BM_face_create_ngon_vcloud(), BM_face_point_inside_test(), BM_mesh_normals_update(), BM_vert_normal_update(), BME_bevel_get_angle(), BME_bevel_poly(), BME_bevel_project_vec(), bmesh_quick_edgedraw_flag(), bmo_edgenet_prepare(), bmo_esubd_exec(), bmo_inset_exec(), bmo_righthandfaces_exec(), bmo_similarfaces_exec(), boid_body(), boid_goal_signed_dist(), bvh_callback(), cache_key_incremental_rotation(), cache_occ_samples(), calc_corner_co(), calc_nearest_point(), calc_poly_plane(), calc_vertexnormals(), calc_vp_alpha_dl(), calcArcCorrelation(), calchandleNurb_intern(), CalcSnapGeometry(), calculateVertexWindForce(), camera_view_frame_fit_to_scene(), check_non_flat_quads(), choose_winner(), clip_line_plane(), closest_to_line_v3(), closest_to_plane_v3(), cloth_calc_spring_force(), cloth_collision_response_static(), collision_point_distance_with_normal(), collision_point_on_surface(), collision_response(), collision_sphere_to_edges(), collision_sphere_to_tri(), convex(), costAngle(), costDistance(), cotan_weight(), create_kdop_hull(), createSpaceNormal(), damptrack_evaluate(), dfdx_damp(), displace_render_vert(), distfactor_to_bone(), DM_calc_auto_bump_scale(), do_guides(), do_kink(), do_material_tex(), do_normal(), do_texture_effector(), doEdgeSplit(), dot_lfvector(), draw_rotation_guide(), draw_volume(), DS_energy(), ED_rollBoneToVector(), edbm_screw_exec(), edgetag_cut_cost(), effector_falloff(), ff_normalize(), ff_quad_form_factor(), ff_visible_quad(), flagAxialSymmetry(), frontface(), get_strand_normal(), getVerticalAndHorizontalChange(), heat_source_distance(), ImageRender::ImageRender(), init_rotsys(), InputHorizontalAbsolute(), InputVerticalAbsolute(), is_negative_m3(), is_negative_m4(), is_orthogonal_m3(), is_orthonormal_m3(), is_quad_convex_v3(), isec_tri_quad(), isec_tri_quad_neighbour(), isect_line_line_strict_v3(), isect_line_line_v3(), isect_line_plane_v3(), isect_line_sphere_v3(), isect_line_tri_v3(), isect_ray_plane_v3(), isect_ray_tri_epsilon_v3(), isect_ray_tri_threshold_v3(), isect_ray_tri_v3(), isect_sweeping_sphere_tri_v3(), lamp_get_visibility(), len_squared_v3v3(), len_v3(), line_point_factor_v3(), load_fluidsimspeedvectors(), M_Geometry_intersect_ray_tri(), make_render_halos(), makeraytree(), mean_value_half_tan(), meshdeform_intersect(), meshdeform_tri_intersect(), moveCloserToDistanceFromPlane(), mul_fmatrix_fvector(), muladd_fmatrix_fvector(), mulsub_fmatrix_fvector(), nearest_point_in_tri_surface(), nextLengthSubdivision(), node_composit_exec_normal(), node_shader_exec_normal(), normal_projection_project_vertex(), normalize_v3_v3(), normalizef(), nr_signed_distance_to_plane(), ntap_bump_compute(), occ_build_dco(), occ_lookup(), occ_quad_form_factor(), occ_solid_angle(), occ_visible_quad(), orthogonalize_m3(), orthogonalize_m4(), p_face_stretch(), particle_billboard(), pe_deflect_emitter(), plane_point_side(), plane_point_side_flip(), plane_trim(), planeProjection(), planes_contain_v3(), point_in_slice(), point_plane_project(), poly_rotate_plane(), project_v3_plane(), project_v3_v3v3(), psys_get_birth_coordinates(), psys_get_dupli_path_transform(), psys_make_billboard(), psys_thread_create_path(), quad_co(), ray_ao_qmc(), ray_ao_spheresamp(), ray_trace_shadow_rad(), reflect_v3_v3v3(), reflection(), reflection_simple(), refraction(), render_lighting_halo(), RIG_parentControl(), rollBoneByQuatAligned(), rotate(), RotationBetween(), rotsys_make_consistent(), rule_avoid_collision(), rule_fight(), rule_follow_leader(), sample_occ(), sample_occ_cache(), sample_occ_tree(), sb_detect_edge_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), sb_spring_force(), sculpt_search_sphere_cb(), set_phong_threshold(), shade_input_calc_viewco(), shade_input_set_normals(), shade_input_set_strand(), shade_lamp_loop_only_shadow(), shade_one_light(), shadeSkyView(), shrinkwrap_calc_normal_projection(), shrinkwrap_get_tarmat(), sk_applyTrimGesture(), sk_distanceDepth(), snapEdge(), snapVertex(), sph_force_cb(), splineik_evaluate_bone(), squared_distance(), static_particle_strand(), surface_determineForceTargetPoints(), tangent_from_uv(), test_planes_aabb(), testRadialSymmetry(), traverse_octree(), uvprojectModifier_do(), v3_dist_from_plane(), validSnappingNormal(), vec_roll_to_mat3(), vgroup_fix(), view3d_align_axis_to_vector(), view3d_boxview_clip(), view3d_clipping_test(), viewAxisCorrectCenter(), viewpixel_to_lampbuf(), viewrotate_apply(), and vol_get_phasefunc().
double dot_vn_vn (const float * array_src_a, const float * array_src_b, const int size)
Definition at line 424 of file math_vector.c.
References i, and size().
Referenced by is_orthogonal_m4(), is_orthonormal_m4(), normalize_vn_vn(), vec_magnitude_nosqrt(), Vector_dot(), Vector_length_get(), Vector_length_set(), Vector_length_squared_get(), and Vector_mul().
MINLINE int equals_v2v2 (const float v1[2], const float v2[2])
Definition at line 665 of file math_vector_inline.c.
Referenced by check_undistortion_cache_flags(), DM_calc_auto_bump_scale(), get_stable_cached_frame(), isect_seg_seg_v2_point(), and scanfill().
MINLINE int equals_v3v3 (const float a[3], const float b[3])
Definition at line 670 of file math_vector_inline.c.
Referenced by check_undistortion_cache_flags(), DM_calc_auto_bump_scale(), draw_motion_path_instance(), fill_add_joint(), fix_connected_bone(), interp_weights_face_v3(), knife_make_chain_cut(), same_snap(), select_groped_exec(), and smooth_view().
MINLINE int equals_v4v4 (const float a[4], const float b[4])
Definition at line 675 of file math_vector_inline.c.
Referenced by smooth_view().
void fill_vn_fl (float * array_tar, const int size, const float val)
Definition at line 573 of file math_vector.c.
References i, and size().
Referenced by C_Vector_Fill(), do_versions(), editmesh_set_connectivity_distance(), imb_read_tiff_pixels(), Matrix_zero(), normalize_vn_vn(), Vector_CreatePyObject(), Vector_length_set(), Vector_new(), Vector_resize(), Vector_resized(), and Vector_zero().
void fill_vn_i (int * array_tar, const int size, const int val)
Definition at line 555 of file math_vector.c.
References i, and size().
Referenced by applyModifier(), calc_weightpaint_vert_array(), and mouse_select().
void fill_vn_ushort (unsigned short * array_tar, const int size, const unsigned short val)
Definition at line 564 of file math_vector.c.
References i, and size().
Referenced by imb_read_tiff_pixels().
void interp_v2_v2v2 (float r[2], const float a[2], const float b[2], const float t)
Definition at line 36 of file math_vector.c.
Referenced by BKE_tracking_join_tracks(), isect_seg_seg_v2_point(), and project_paint_face_init().
void interp_v2_v2v2v2 (float r[2], const float a[2], const float b[2], const float c[3], const float t[3])
Referenced by project_bucket_clip_face(), project_face_pixel(), project_paint_PickColor(), rect_to_uvspace_ortho(), and rect_to_uvspace_persp().
void interp_v3_v3v3 (float r[3], const float a[3], const float b[3], const float t)
Definition at line 52 of file math_vector.c.
Referenced by ambient_occlusion_apply(), blend_m3_m3m3(), blend_m4_m4m4(), bm_subdivide_edge_addvert(), bmo_vertex_slide_exec(), boid_find_ground(), calc_curvepath(), calc_latt_deform(), collision_newton_rhapson(), collision_response(), constraint_target_to_mat4(), curve_deform_verts(), deformVerts_do(), distlimit_evaluate(), do_clump(), do_guides(), do_kink(), draw_em_measure_stats(), draw_mesh_fancy(), drawlamp(), dynamicPaint_Modifier_apply(), edbm_blend_from_shape_exec(), flyApply(), get_strand_normal(), gp_stroke_to_bezier(), interpolate_pathcache(), knife_edge_tri_isect(), knife_find_closest_edge(), knife_split_edge(), limit_dist_v3(), mixColors(), node_shader_exec_curve_rgb(), project_paint_face_init(), psys_cache_edit_paths(), psys_get_particle_state(), REEB_AxialSymmetry(), REEB_RadialSymmetry(), shade_one_light(), shrinkwrap_calc_nearest_surface_point(), shrinkwrap_calc_nearest_vertex(), shrinkwrap_calc_normal_projection(), shrinkwrap_get_tarmat(), SimpleDeformModifier_do(), snapEdge(), splineik_evaluate_bone(), subdividenurb(), update_reports_display_invoke(), viewrotate_apply(), vtx_slide_update(), and warpModifier_do().
void interp_v3_v3v3v3 (float p[3], const float v1[3], const float v2[3], const float v3[3], const float w[3])
Definition at line 73 of file math_vector.c.
Referenced by barycentric_transform(), dynamicPaint_generateBakeData(), dynamicPaint_paintMesh(), dynamicPaint_setInitialColor(), project_paint_face_init(), project_paint_occlude_ptv_clip(), psys_interpolate_face(), screen_px_from_ortho(), and screen_px_from_persp().
void interp_v3_v3v3v3v3 (float p[3], const float v1[3], const float v2[3], const float v3[3], const float v4[3], const float w[4])
Definition at line 82 of file math_vector.c.
Referenced by psys_interpolate_face(), psys_interpolate_particle(), psys_thread_create_path(), and where_on_path().
void interp_v4_v4v4 (float r[4], const float a[4], const float b[4], const float t)
Definition at line 61 of file math_vector.c.
Referenced by psys_thread_create_path(), and subdividenurb().
void interp_v4_v4v4v4 (float p[4], const float v1[4], const float v2[4], const float v3[4], const float w[3])
Definition at line 89 of file math_vector.c.
Referenced by dynamicPaint_setInitialColor().
void interp_v4_v4v4v4v4 (float p[4], const float v1[4], const float v2[4], const float v3[4], const float v4[4], const float w[4])
Definition at line 97 of file math_vector.c.
MINLINE int is_one_v3 (const float a[3])
Definition at line 660 of file math_vector_inline.c.
Referenced by init_tex_mapping().
MINLINE int is_zero_v3 (const float a[3])
Definition at line 650 of file math_vector_inline.c.
Referenced by bmo_spin_exec(), calc_area_normal(), calc_area_normal_and_flatten_center(), calc_corner_co(), calc_vertexnormals(), costAngle(), do_versions(), ED_rollBoneToVector(), edbm_extrude_edge(), flyApply_ndof(), group_duplilist(), init_tex_mapping(), knife_start_cut(), ndof_orbit_invoke(), new_particle_duplilist(), quat__axis_angle_sanitize(), repositionBone(), setBoneRollFromNormal(), sk_drawEdge(), and sk_drawNormal().
MINLINE int is_zero_v4 (const float a[4])
Definition at line 655 of file math_vector_inline.c.
Referenced by do_versions().
MINLINE float len_squared_v2 (const float v[2])
Definition at line 507 of file math_vector_inline.c.
MINLINE float len_squared_v2v2 (const float a[2], const float b[2])
Definition at line 536 of file math_vector_inline.c.
References dot_v2v2(), and sub_v2_v2v2().
Referenced by do_projectpaint_thread(), find_hole_chains(), freetypechar_to_vchar(), layerEqual_mloop_origspace(), layerEqual_mloopuv(), and weight_sample_invoke().
MINLINE float len_squared_v3 (const float v[3])
Definition at line 512 of file math_vector_inline.c.
Referenced by bmo_inset_exec(), and project_v3_plane().
MINLINE float len_squared_v3v3 (const float a[3], const float b[3])
Definition at line 552 of file math_vector_inline.c.
References dot_v3v3(), and sub_v3_v3v3().
Referenced by BM_edge_rotate_check_beauty(), BM_face_create_ngon_vcloud(), bmo_bridge_loops_exec(), calc_nearest_point(), calc_overlap(), distfactor_to_bone(), do_bake_shade(), doMirrorOnAxis(), find_ear(), get_vert2geom_distance(), hook_falloff(), knife_edge_tri_isect(), mesh_edges_nearest_point(), sculpt_brush_test(), sculpt_brush_test_fast(), sculpt_brush_test_sq(), shrinkwrap_calc_nearest_surface_point(), shrinkwrap_calc_nearest_vertex(), and viewrotate_apply().
MINLINE float len_v2 (const float a[2])
Definition at line 517 of file math_vector_inline.c.
References sqrtf.
Referenced by boid_brain(), brush_imbuf_new(), brush_jitter_pos(), calchandle_curvemap(), draw_sphere_bone_dist(), draw_tracking_tracks(), gp_draw_stroke(), imagewraposa_aniso(), isect_point_quad_uv_v2(), ntap_bump_compute(), paint_space_stroke(), project_from_camera(), set_axis(), ui_ndofedit_but_HSVCIRCLE(), and ui_numedit_but_CURVE().
MINLINE float len_v2v2 (const float a[2], const float b[2])
Definition at line 522 of file math_vector_inline.c.
References sqrtf.
Referenced by angle_normalized_v2v2(), bspface_init_strand(), customdata_compare(), draw_distortion(), draw_fcurve_curve_bezts(), edbm_rip_edge_side_measure(), isect_seg_seg_v2_point(), knife_find_closest_vert(), knife_find_line_hits(), knife_sample_screen_density(), knifetool_draw(), p_chart_minimum_area_angle(), p_rectangle_area(), project_brush_radius(), project_paint_face_init(), texpaint_break_stroke(), and ui_mouse_motion_towards_check().
MINLINE float len_v3 (const float a[3])
Definition at line 531 of file math_vector_inline.c.
References dot_v3v3(), and sqrtf.
Referenced by accum_density(), apply_boid_rule(), applyModifier(), armature_fill_bones_exec(), b_bone_spline_setup(), basic_force_cb(), basic_rotate(), BM_face_create_ngon_vcloud(), BMBVH_FindClosestVert(), BME_bevel_get_vec(), BME_bevel_poly(), boid_body(), boid_find_ground(), bone_align_to_bone(), brush_puff(), calc_curvepath(), calc_vp_alpha_dl(), calcArcCorrelation(), calchandleNurb_intern(), camera_view_frame_fit_to_scene(), collision_detect(), contarget_get_mesh_mat(), convert_pose(), convert_tree(), cotan_weight(), curvemap_make_table(), distribute_simple_children(), DM_calc_auto_bump_scale(), do_grab_brush(), do_guides(), do_path_effectors(), do_set_scale(), do_snake_hook_brush(), do_versions(), draw_ebones(), draw_manipulator_rotate(), draw_new_particle_system(), draw_particle(), draw_pose_bones(), drawcamera(), dynamicPaint_generateBakeData(), dynamicPaint_paintMesh(), dynamicPaint_paintParticles(), dynamicPaint_paintSinglePoint(), dynamicPaint_prepareAdjacencyData(), dynamicPaint_prepareEffectStep(), ED_view3d_update_viewmat(), edgetag_cut_cost(), editmesh_set_connectivity_distance(), effector_falloff(), execute_posetree(), finalizeControl(), followtrack_evaluate(), get_effector_data(), headerTranslation(), init_rotsys(), len_v3v3(), mat3_to_scale(), mat3_to_size(), mat4_to_dquat(), mat4_to_size(), mdisp_in_mdispquad(), mean_value_half_tan(), nr_distance_to_edge(), ntap_bump_compute(), paint_calc_object_space_radius(), particle_normal_ren(), pointdensitytex(), precalc_guides(), psys_get_particle_on_path(), psys_thread_create_path(), ray_shadow_qmc(), RE_rayobject_instance_intersect(), render_lighting_halo(), render_new_particle_system(), ResizeBetween(), rest_pose(), rule_avoid_collision(), rule_flock(), rule_follow_leader(), rule_goal_avoid(), screen_aligned(), setNearestAxis3d(), shade_input_do_shade(), shade_sample_sss(), sk_distanceDepth(), snapDerivedMesh(), speedvector_project(), sph_particle_courant(), sphere_do(), splineik_evaluate_bone(), static_particle_strand(), strand_eval_point(), uiTemplateColorWheel(), update_courant_num(), v3d_editvertex_buts(), vcloud_estimate_transform(), vertsearchcallback(), view3d_zoom_border_exec(), viewAxisCorrectCenter(), viewrotate_apply(), and window_translate_m4().
MINLINE float len_v3v3 (const float a[3], const float b[3])
Definition at line 544 of file math_vector_inline.c.
References len_v3(), and sub_v3_v3v3().
Referenced by alter_co(), angle_normalized_v3v3(), apply_spring_memory(), applyModifier(), armature_click_extrude_exec(), autocalchandlesNurb(), BLI_FindNodeByPosition(), BLI_removeDoubleNodes(), BM_edge_calc_length(), BM_face_calc_perimeter(), bmo_beautify_fill_exec(), bmo_bridge_loops_exec(), bmo_create_uvsphere_exec(), bmo_similaredges_exec(), bmo_vertexshortestpath_exec(), bpy_bmedge_calc_length(), brush_puff(), calc_distanceCurveVerts(), calc_edge_stress_add(), calchandleNurb_intern(), CalcSnapGeometry(), cloth_build_springs(), cloth_calc_helper_forces(), convert_pose(), curvemap_make_table(), customdata_compare(), dist_to_line_segment_v3(), distlimit_evaluate(), draw_em_measure_stats(), draw_new_particle_system(), draw_sphere_bone_dist(), draw_sphere_bone_wire(), dvar_eval_locDiff(), dynamicPaint_paintSinglePoint(), ED_armature_from_edit(), edbm_bevel_exec(), edbm_sort_faces_exec(), equalize_bezier(), finalizeControl(), frac_along(), get_ob2ob_distance(), get_vert2ob_distance(), getVerticalAndHorizontalChange(), globallen(), init_rotsys(), initToSphere(), interp_weights_poly_v3(), knife_add_cut(), knife_edge_tri_isect(), knife_find_closest_edge(), knife_split_edge(), laplacian_triangle_area(), len_v3_tri_side_max(), limit_dist_v3(), make_selection_list_nurb(), merge_2_nurb(), meshdeform_intersect(), meshdeform_ray_tree_intersect(), nextFixedSubdivision(), nextLengthSubdivision(), normal_projection_project_vertex(), nr_distance_to_vert(), p_quad_split_direction(), pe_deflect_emitter(), peelDerivedMesh(), psys_thread_create_path(), ray_fadeout(), RE_inithalo(), RE_inithalo_particle(), recalc_lengths(), recalcData_view3d(), render_new_particle_system(), retargetArctoArcLength(), RIG_appendEdgeToArc(), RIG_reconnectControlBones(), RIG_removeUneededOffsets(), sb_detect_edge_collisionCached(), shade_input_set_strand_texco(), shade_input_set_uv(), shrinkwrap_get_tarmat(), sk_addStrokeSnapPoint(), sk_getStrokeSnapPoint(), sk_interpolateDepth(), snapEdge(), snapVertex(), sphere_do(), spothalo(), springs_from_mesh(), stretchto_evaluate(), testAxialSymmetry(), testRadialSymmetry(), TranslationBetween(), valuefn(), viewops_data_create(), vol_shade_one_lamp(), vtx_slide_confirm(), vtx_slide_update(), warpModifier_do(), and where_is_armature_bone().
MINLINE float line_point_side_v2 (const float l1[2], const float l2[2], const float pt[2])
Definition at line 712 of file math_vector_inline.c.
Referenced by edbm_dupli_extrude_cursor_invoke(), isect_point_quad_v2(), isect_point_tri_v2(), IsectPoly2Df(), IsectPoly2Df_twoside(), project_bucket_clip_face(), and project_paint_begin().
MINLINE void madd_v2_v2v2fl (float r[2], const float a[2], const float b[2], float f)
Definition at line 384 of file math_vector_inline.c.
Referenced by calchandle_curvemap(), and isect_line_sphere_v2().
MINLINE void madd_v3_v3fl (float r[3], const float a[3], float f)
Definition at line 370 of file math_vector_inline.c.
Referenced by accumulate_vertex_normals(), accumulate_vertex_normals_poly(), alter_co(), applyModifier(), basic_force_cb(), basic_integrate(), BM_face_create_ngon_vcloud(), BM_mesh_normals_update(), BM_vert_normal_update(), BME_bevel_get_angle_vert(), bmo_inset_exec(), boid_body(), boid_climb(), brush_puff(), calc_latt_deform(), calc_nearest_point(), calc_poly_plane(), camera_view_frame_fit_to_scene(), collision_point_on_surface(), collision_point_velocity(), collision_response(), dist_bone_deform(), do_guides(), do_kink(), do_material_tex(), do_physical_effector(), do_rough(), do_rough_end(), do_texture_effector(), drawnurb(), dynamicPaint_generateBakeData(), dynamicPaint_Modifier_apply(), dynamicPaint_prepareEffectStep(), face_duplilist(), integrate_particle(), layerInterp_shapekey(), mesh_calc_ngon_center(), meshdeformModifier_do(), occ_build_recursive(), occ_compute_bounces(), occ_compute_passes(), occ_lookup(), occ_shade(), occ_sum_occlusion(), psys_get_birth_coordinates(), psys_make_billboard(), psys_thread_create_path(), rule_avoid_collision(), rule_follow_leader(), sample_occ_cache(), sample_occ_surface(), softbody_calc_forces(), solidify_add_thickness(), sph_force_cb(), and update_velocities().
MINLINE void madd_v3_v3v3 (float r[3], const float a[3], const float b[3])
Definition at line 377 of file math_vector_inline.c.
MINLINE void madd_v3_v3v3fl (float r[3], const float a[3], const float b[3], float f)
Definition at line 390 of file math_vector_inline.c.
Referenced by bake_intersect_tree(), barycentric_transform(), Bevel(), BLI_bvhtree_bb_raycast(), BM_edge_split(), BME_bevel(), BME_bevel_split_edge(), bmo_inset_exec(), boid_body(), brush_add(), brush_puff(), calchandleNurb_intern(), clip_line_plane(), collision_interpolate_element(), collision_point_distance_with_normal(), collision_point_on_surface(), collision_response(), collision_sphere_to_edges(), dfs_raycast(), do_path_effectors(), draw_particle(), draw_sphere_bone_dist(), drawshadbuflimits(), dynamicPaint_paintMesh(), ED_view3d_win_to_segment_clip(), effector_falloff(), heat_ray_source_visible(), integrate_particle(), isect_line_sphere_v3(), mesh_faces_spherecast(), particle_normal_ren(), psys_get_particle_state(), psys_make_billboard(), RE_rayobject_octree_intersect(), reflection_simple(), shrinkwrap_calc_nearest_surface_point(), shrinkwrap_calc_normal_projection(), sph_force_cb(), sphereray_tri_intersection(), surface_determineForceTargetPoints(), view_dolly_mouseloc(), and view_zoom_mouseloc().
MINLINE void madd_v3_v3v3v3 (float r[3], const float a[3], const float b[3], const float c[3])
Definition at line 397 of file math_vector_inline.c.
Referenced by transform_mesh_orco_verts().
MINLINE void madd_v4_v4fl (float r[4], const float a[4], float f)
Definition at line 404 of file math_vector_inline.c.
Referenced by calculate_speedvectors().
void mid_v2_v2v2 (float r[2], const float a[2], const float b[2])
Definition at line 112 of file math_vector.c.
Referenced by uvedit_center().
void mid_v3_v3v3 (float r[3], const float a[3], const float b[3])
Definition at line 105 of file math_vector.c.
Referenced by _scan_for_ext_spring_forces(), _softbody_calc_forces_slice_in_a_thread(), BKE_metaball_center_bounds(), BM_face_calc_center_bounds(), BM_face_legal_splits(), bmo_inset_exec(), bmo_vertexsmooth_exec(), boundbox_armature(), boundbox_mesh(), bspface_init_strand(), bundle_midpoint(), curve_center_bounds(), docenter_armature(), draw_ebones(), draw_em_indices(), draw_em_measure_stats(), draw_pose_bones(), edbm_dupli_extrude_cursor_invoke(), edbm_rip_edge_side_measure(), exec_strandsurface_sample(), get_edge_center(), initWarp(), knife_edge_in_face(), knife_find_closest_edge(), make_trans_verts(), mesh_center_bounds(), object_origin_set_exec(), occ_face(), shrink_edgef(), smoothModifier_do(), snap_curs_to_sel(), softbody_calc_forces(), tex_space_curve(), and uv_map_transform_center().
void minmax_v3v3_v3 (float min[3], float max[3], const float vec[3])
Definition at line 411 of file math_vector.c.
Referenced by calculateCenterBound(), and initWarp().
MINLINE void mul_v2_fl (float r[2], float f)
Definition at line 317 of file math_vector_inline.c.
Referenced by applySeqSlide(), BM_face_point_inside_test(), boid_body(), calculate_stabdata(), do_rough_end(), draw_distortion(), dynamicPaint_findNeighbourPixel(), ED_uvedit_median(), edbm_rip_edge_side_measure(), HC_relaxation_iteration_uv(), imagewraposa_aniso(), laplacian_relaxation_iteration_uv(), layerMultiply_mloop_origspace(), layerMultiply_mloopuv(), marker_block_handler(), paint_brush_stroke_add_step(), paint_space_stroke(), poly_uv_center(), uiTemplateMarker(), and uv_image_outset().
MINLINE void mul_v2_v2 (float r[2], const float a[2])
Definition at line 343 of file math_vector_inline.c.
Referenced by uv_image_outset().
MINLINE void mul_v2_v2fl (float r[2], const float a[2], float f)
Definition at line 323 of file math_vector_inline.c.
Referenced by clip_draw_main(), normalize_v2_v2(), and snap_uvs_to_adjacent_unselected().
MINLINE void mul_v3_fl (float r[3], float f)
Definition at line 329 of file math_vector_inline.c.
Referenced by _scan_for_ext_spring_forces(), _softbody_calc_forces_slice_in_a_thread(), actcon_get_tarmat(), alter_co(), apply_tangmat_callback(), applyModifier(), applyTranslation(), armature_deform_verts(), atm_tile(), axisProjection(), b_bone_spline_setup(), bake_shade(), barycentric_weights(), barycentric_weights_v2(), basic_force_cb(), basic_integrate(), basic_rotate(), BKE_metaball_center_median(), BKE_text_to_curve(), BLI_mirrorAlongAxis(), BM_editselection_center(), BM_face_calc_center_mean(), BM_face_multires_bounds_smooth(), BM_loop_interp_from_face(), bm_loop_interp_mdisps(), BM_vert_interp_from_face(), BMBVH_EdgeVisible(), BME_bevel_poly(), bmo_bevel_exec(), bmo_collapse_exec(), bmo_inset_exec(), bmo_rotate_exec(), bmo_vertexsmooth_exec(), boid_body(), boid_brain(), boid_climb(), bone_align_to_bone(), bone_matrix_translate_y(), brush_add(), brush_comb(), brush_edit_apply(), brush_length(), brush_puff(), brush_smooth_do(), calc_area_normal_and_flatten_center(), calc_brushdata_symm(), calc_corner_co(), calc_curve_deform(), calc_flatten_center(), calc_manipulator_stats(), calc_solidify_normals(), calchandleNurb_intern(), CalcSnapGeometry(), calculateCenterBound(), calculateCenterMedian(), camera_view_frame_fit_to_scene(), cdDM_foreachMappedFaceCenter(), check_path_length(), closest_point_on_surface(), cloth_bvh_objcollision(), cloth_calc_force(), cloth_calc_helper_forces(), cloth_collision(), cloth_collision_response_static(), cloth_from_object(), collision_check(), collision_fail(), collision_response(), compute_mdisp_quad(), compute_radiance(), contarget_get_lattice_mat(), contarget_get_mesh_mat(), createFacepa(), createSlideVerts(), createTransEdge(), curve_center_median(), curvemap_make_table(), cutEdges(), distribute_threads_exec(), dm_calc_normal(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_guides(), do_inflate_brush(), do_kink(), do_lamp_tex(), do_material_tex(), do_mesh_smooth_brush(), do_multires_smooth_brush(), do_particle_interpolation(), do_path_effectors(), do_physical_effector(), do_rotate_brush(), do_rough(), do_scrape_brush(), do_set_scale(), do_snake_hook_brush(), do_version_bone_head_tail_237(), do_versions(), docenter_armature(), doEdgeSlide(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), draw_particle(), draw_sphere_bone_wire(), draw_volume(), draw_xyz_wire(), drawlamp(), drawLine(), DS_energy(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_brushObjectCalculateVelocity(), dynamicPaint_generateBakeData(), dynamicPaint_paintMesh(), dynamicPaint_paintParticles(), dynamicPaint_paintSinglePoint(), dynamicPaint_prepareAdjacencyData(), dynamicPaint_prepareEffectStep(), ED_view3d_global_to_vector(), edbm_blend_from_shape_exec(), edbm_extrude_repeat_exec(), edbm_rip_invoke__vert(), edbm_screw_exec(), edbm_sort_faces_exec(), ElementResize(), emDM__calcFaceCent(), execute_posetree(), execute_scene(), explodeMesh(), flush_pixel(), flyApply(), flyApply_ndof(), followpath_evaluate(), get_effector_data(), get_next_loop(), getSingleCoordinate(), getSnapPoint(), give_parvert(), heat_ray_source_visible(), ImageRender::ImageRender(), imapaint_tri_weights(), implicit_solver(), init_rotsys(), InputVector(), integrate_particle(), interp_barycentric_tri_data(), interp_bilinear_quad_data(), isect_line_line_strict_v3(), isect_line_line_v3(), isect_line_plane_v3(), isect_ray_tri_threshold_v3(), isect_sweeping_sphere_tri_v3(), knife_edge_tri_isect(), lamp_get_visibility(), M_Geometry_intersect_ray_tri(), make_occ_tree(), make_selection_list_nurb(), make_trans_verts(), mdisp_in_mdispquad(), merge_target(), mesh_center_median(), mesh_octree_table(), meshdeformModifier_do(), mul_fac_qt_fl(), multiresModifier_base_apply(), multitex(), ndof_orbit_invoke(), ndof_pan_invoke(), nearest_point_in_tri_surface(), neighbor_average(), new_particle_duplilist(), nextLengthSubdivision(), ob_parbone(), ob_parvert3(), object_origin_set_exec(), occ_build_recursive(), occ_sum_occlusion(), offset_child(), old_mdisps_bilinear(), orthogonalize_m3(), orthogonalize_m4(), outside_lattice(), p_face_stretch(), particle_normal_ren(), PE_apply_lengths(), pe_deflect_emitter(), pe_iterate_lengths(), peelDerivedMesh(), planeProjection(), pointdensitytex(), postInputShear(), postInputWarp(), project_brush_radius(), psys_get_birth_coordinates(), psys_get_particle_on_path(), psys_get_particle_state(), psys_make_billboard(), psys_particle_on_dm(), psys_render_simplify_distribution(), psys_thread_create_path(), ptcache_cloth_interpolate(), ptcache_particle_interpolate(), ptcache_particle_read(), ptcache_softbody_interpolate(), PushPull(), ray_ao_qmc(), ray_ao_spheresamp(), raycallback(), recalc_emitter_field(), REEB_AxialSymmetry(), reference_to_scratch(), repositionControl(), return_editcurve_indexar(), return_editlattice_indexar(), return_editmesh_indexar(), return_editmesh_vgroup(), rotate(), rotsys_make_consistent(), rule_average_speed(), rule_avoid_collision(), rule_flock(), rule_follow_leader(), rule_goal_avoid(), rule_separate(), samevolume_evaluate(), sample_occ_cache(), sample_occ_tree(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), scale_point(), scale_quad(), scale_tri(), scatter_tree_new(), scatter_tree_sample(), sculpt_stroke_get_location(), set_origin_exec(), setNearestAxis3d(), shade_input_do_shade(), shade_input_set_shade_texco(), shade_lamp_loop(), Shear(), shrink_edgef(), ShrinkFatten(), sizelike_evaluate(), sizelimit_evaluate(), sk_drawStroke(), sk_flattenStroke(), sk_getSelfIntersections(), sk_getStrokeSnapPoint(), sk_interpolateDepth(), snap_curs_to_sel(), snapEdge(), softbody_apply_forces(), softbody_calc_forces(), sph_integrate(), splineik_evaluate_bone(), static_particle_strand(), strand_eval_point(), subsurf_calculate_limit_positions(), TargetSnapMedian(), ToSphere(), trace_reflect(), trace_refract(), transform_evaluate(), ui_ndofedit_but_HSVCIRCLE(), ui_numedit_but_HSVCIRCLE(), update_velocities(), KX_GameObject::UpdateBlenderObjectMatrix(), vcloud_estimate_transform(), viewAxisCorrectCenter(), vieworbit_exec(), viewrotate_apply(), viewselected_exec(), vol_get_transmittance(), vol_shade_one_lamp(), volumeintegrate(), voxeldatatex(), Warp(), where_is_ik_bone(), where_is_pose_bone_tail(), and where_on_path_deform().
MINLINE void mul_v3_v3 (float r[3], const float a[3])
Definition at line 349 of file math_vector_inline.c.
Referenced by alter_co(), brush_imbuf_new(), do_crease_brush(), do_draw_brush(), do_projectpaint_draw_f(), dynamicPaint_generateBakeData(), and gpu_material_to_fixed().
MINLINE void mul_v3_v3fl (float r[3], const float a[3], float f)
Definition at line 336 of file math_vector_inline.c.
Referenced by alter_co(), bake_intersect_tree(), bm_loop_flip_disp(), bvh_callback(), camera_view_frame_fit_to_scene(), circball_array_fill(), collision_response(), dm_calc_normal(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_draw_brush(), do_fill_brush(), do_flatten_brush(), do_grab_brush(), do_kink(), do_layer_brush(), do_nudge_brush(), do_pinch_brush(), do_scrape_brush(), do_snake_hook_brush(), do_thumb_brush(), draw_new_particle_system(), draw_rotation_guide(), drawlamp(), drawspiral(), dynamicPaint_paintParticles(), GPU_enable_material(), gpu_material_to_fixed(), GPU_scene_object_lights(), integrate_particle(), ndof_orbit_invoke(), normalize_v3_v3(), old_mdisps_bilinear(), point_plane_project(), project_v3_plane(), psys_get_birth_coordinates(), RE_rayobject_instance_intersect(), rotate(), sk_straightenStroke(), sph_particle_courant(), and track_colors().
MINLINE void mul_v3_v3v3 (float r[3], const float a[3], const float b[3])
Definition at line 412 of file math_vector_inline.c.
Referenced by ambient_occlusion_apply(), brush_imbuf_new(), colorfn(), do_clay_brush(), do_clay_strips_brush(), do_displacement(), do_fill_brush(), do_flatten_brush(), do_inflate_brush(), do_layer_brush(), do_scrape_brush(), object_scale_to_mat3(), vol_shade_one_lamp(), and volumeintegrate().
MINLINE void mul_v4_fl (float r[4], float f)
Definition at line 356 of file math_vector_inline.c.
void mul_vn_fl (float * array_tar, const int size, const float f)
Definition at line 494 of file math_vector.c.
References i, and size().
Referenced by Color_idiv(), Color_imul(), edbm_bevel_exec(), Vector_idiv(), Vector_imul(), and Vector_length_set().
void mul_vn_vn_fl (float * array_tar, const float * array_src, const int size, const float f)
Definition at line 503 of file math_vector.c.
References i, and size().
Referenced by color_mul_float(), matrix_mul_float(), normalize_vn_vn(), screen_opengl_render_apply(), Vector_div(), and vector_mul_float().
MINLINE void negate_v2 (float r[2])
MINLINE void negate_v2_v2 (float r[2], const float a[2])
Definition at line 425 of file math_vector_inline.c.
Referenced by BKE_tracking_add_track(), flushTransTracking(), and stitch_island_calculate_vert_rotation().
MINLINE void negate_v3 (float r[3])
Definition at line 431 of file math_vector_inline.c.
Referenced by applyModifier(), armature_calc_roll_exec(), bevel_list_flip_tangents(), BM_face_normal_flip(), bmo_inset_exec(), boid_body(), calc_corner_co(), collision_point_on_surface(), do_kink(), do_snake_hook_brush(), dynamicPaint_generateBakeData(), dynamicPaint_paintMesh(), ED_rollBoneToVector(), ED_view3d_calc_clipping(), edbm_screw_exec(), exec_strandsurface_sample(), flyApply(), getTransformOrientation(), GPU_material_bind_uniforms(), init_render_mesh(), is_quad_convex_v3(), isect_line_plane_v3(), isect_sweeping_sphere_tri_v3(), locktrack_evaluate(), mat3_to_rot_size(), node_shader_exec_material(), nr_signed_distance_to_plane(), occ_compute_passes(), occ_shade(), postInputWarp(), psys_get_birth_coordinates(), rollBoneByQuatAligned(), rule_fight(), shade_input_set_normals(), shade_input_set_strand(), shade_material_loop(), shade_sample_sss(), strand_eval_point(), tangent_from_uv(), testAxialSymmetry(), vectomat(), view_zoom_mouseloc(), viewAxisCorrectCenter(), viewops_data_create(), viewrotate_apply(), vol_shade_one_lamp(), and where_on_path().
MINLINE void negate_v3_v3 (float r[3], const float a[3])
Definition at line 438 of file math_vector_inline.c.
Referenced by applyModifier(), BM_edge_rotate_check_degenerate(), boid_body(), collision_response(), compatible_bump_compute(), draw_rotation_guide(), drawshadbuflimits(), ED_view3d_from_m4(), eff_calc_visibility(), getTransformOrientation(), GPU_scene_object_lights(), ImageRender::ImageRender(), initFlyInfo(), initRotation(), isec_tri_quad_neighbour(), knife_input_ray_cast(), object_origin_clear_exec(), object_origin_set_exec(), psys_get_birth_coordinates(), rule_goal_avoid(), sample_occ_tree(), set_3dcursor_invoke(), shade_material_loop(), shrinkwrap_calc_normal_projection(), stretchto_evaluate(), Vector_to_track_quat(), view3d_get_view_aligned_coordinate(), view_zoom_mouseloc(), viewcenter_cursor_exec(), viewdolly_exec(), viewdolly_invoke(), viewops_data_create(), and warpModifier_do().
MINLINE void negate_v4 (float r[4])
Definition at line 445 of file math_vector_inline.c.
Referenced by pose_flip_quats_exec().
MINLINE void negate_v4_v4 (float r[4], const float a[3])
Referenced by Quaternion_neg().
void negate_vn (float * array_tar, const int size)
Definition at line 475 of file math_vector.c.
References i, and size().
Referenced by Vector_negate().
void negate_vn_vn (float * array_tar, const float * array_src, const int size)
Definition at line 484 of file math_vector.c.
References i, and size().
Referenced by Color_neg(), and Vector_neg().
MINLINE void normal_float_to_short_v3 (short r[3], const float n[3])
Definition at line 635 of file math_vector_inline.c.
Referenced by applyModifier(), BM_mesh_bm_to_me(), bmvert_to_mvert(), ccgDM_copyFinalVertArray(), ccgDM_getFinalVert(), CDDM_from_BMEditMesh(), emDM_copyVertArray(), mball_to_mesh(), mesh_calc_normals(), mesh_calc_normals_tessface(), and sculpt_undo_store_coords().
MINLINE void normal_short_to_float_v3 (float r[3], const short n[3])
Definition at line 628 of file math_vector_inline.c.
Referenced by applyModifier(), BL_ConvertMesh(), BM_mesh_bm_from_me(), calc_area_normal(), calc_area_normal_and_flatten_center(), ccgDM_getFinalVertNo(), cdDM_getVertNo(), dm_calc_normal(), DM_to_bmesh_ex(), do_inflate_brush(), dynamicPaint_applySurfaceDisplace(), dynamicPaint_generateBakeData(), dynamicPaint_Modifier_apply(), dynamicPaint_paintMesh(), frontface(), GetNormal(), GPU_buffer_copy_normal(), init_render_mesh(), make_vertexcosnos__mapFunc(), multiresbake_get_normal(), project_paint_begin(), psys_interpolate_face(), sculpt_restore_mesh(), shrinkwrap_calc_normal_projection(), snapEdge(), snapVertex(), and BL_SkinDeformer::UpdateInternal().
MINLINE float normalize_v2 (float r[2])
Definition at line 576 of file math_vector_inline.c.
References normalize_v2_v2().
Referenced by angle_v2v2(), angle_v2v2v2(), boid_body(), boid_brain(), brush_painter_paint(), draw_uvs_stretch(), edbm_rip_edge_side_measure(), gp_draw_stroke(), stitch_calculate_edge_normal(), stitch_init(), stitch_island_calculate_edge_rotation(), uv_image_outset(), and uv_sculpt_stroke_apply().
MINLINE float normalize_v2_v2 (float r[2], const float a[2])
Definition at line 560 of file math_vector_inline.c.
References dot_v2v2(), mul_v2_v2fl(), sqrtf, and zero_v2().
Referenced by normalize_v2().
MINLINE float normalize_v3 (float r[3])
Definition at line 623 of file math_vector_inline.c.
References normalize_v3_v3().
Referenced by _scan_for_ext_spring_forces(), _softbody_calc_forces_slice_in_a_thread(), accumulate_vertex_normals(), accumulate_vertex_normals_poly(), add_render_lamp(), addnormalsDispList(), alter_co(), angle_poly_v3(), angle_quad_v3(), angle_tri_v3(), angle_v3v3v3(), apply_tangmat_callback(), applyModifier(), area_quad_v3(), area_tri_v3(), axis_angle_to_gimbal_axis(), axisProjection(), b_bone_spline_setup(), bake_shade(), basic_rotate(), bisect_v3_v3v3v3(), BKE_text_to_curve(), BLI_bvhtree_bb_raycast(), BLI_bvhtree_ray_cast(), BLI_edgefill_ex(), Blinn_Spec(), BM_edge_calc_face_tangent(), BM_edge_rotate_check_degenerate(), BM_editselection_normal(), bm_face_calc_poly_normal_vertex_cos(), BM_face_create_ngon_vcloud(), BM_loop_calc_face_tangent(), BM_mesh_normals_update(), bm_subdivide_edge_addvert(), BM_vert_normal_update(), BMBVH_EdgeVisible(), BME_assign_transdata(), BME_bevel_get_angle(), BME_bevel_get_angle_vert(), BME_bevel_poly(), BME_bevel_project_vec(), BME_bevel_split_edge(), bmo_bevel_exec(), bmo_esubd_exec(), bmo_inset_exec(), bmo_similarfaces_exec(), bmo_spin_exec(), boid_body(), boid_brain(), boid_climb(), bone_align_to_bone(), brush_puff(), cache_key_incremental_rotation(), calc_area_normal(), calc_area_normal_and_flatten_center(), calc_corner_co(), calc_curve_deform(), calc_poly_plane(), calc_solidify_normals(), calc_vertexnormals(), calcCostAngleLengthDistance(), calchandleNurb_intern(), calculateCenter(), camera_view_frame_fit_to_scene(), cloth_bvh_objcollision(), cloth_calc_helper_forces(), cloth_collision_response_static(), collision_point_distance_with_normal(), collision_point_on_surface(), collision_sphere_to_edges(), collision_sphere_to_verts(), compatible_bump_compute(), contarget_get_mesh_mat(), CookTorr_Spec(), createSpaceNormal(), createSpaceNormalTangent(), damptrack_evaluate(), distfactor_to_bone(), distribute_threads_exec(), dl_surf_to_renderdata(), dm_calc_normal(), do_guides(), do_kink(), do_material_tex(), do_path_effectors(), do_physical_effector(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), draw_new_particle_system(), draw_particle(), draw_sphere_bone_dist(), draw_sphere_bone_wire(), draw_uvs_stretch(), draw_volume(), drawlamp(), drawmball(), drawshadbuflimits(), DS_energy(), dynamicPaint_applySurfaceDisplace(), dynamicPaint_generateBakeData(), dynamicPaint_paintMesh(), ED_view3d_global_to_vector(), ED_view3d_win_to_ray(), ED_view3d_win_to_vector(), edbm_dupli_extrude_cursor_invoke(), edbm_extrude_edge(), edbm_rip_invoke__vert(), eff_calc_visibility(), followpath_get_tarmat(), forward_diff_bezier_cotangent(), get_effector_data(), get_strand_normal(), getEditDerivedBMesh(), GetSkyXYZRadiancef(), getTransformOrientation(), getViewVector(), GPU_lamp_shadow_buffer_bind(), GPU_material_bind_uniforms(), handleRadialSymmetry(), heat_calc_vnormals(), heat_ray_source_visible(), heat_source_distance(), ImageRender::ImageRender(), init_render_curve(), init_render_mball(), init_render_mesh(), init_render_world(), init_rotsys(), initRotation(), initSnapping(), initTransform(), interpolate_shade_result(), isect_line_plane_v3(), isect_sweeping_sphere_tri_v3(), knife_edge_tri_isect(), knife_input_ray_cast(), locktrack_evaluate(), M_Geometry_intersect_plane_plane(), M_Geometry_intersect_ray_tri(), make_bevel_list_3D_minimum_twist(), make_bevel_list_3D_tangent(), make_bevel_list_segment_3D(), make_render_halos(), markdownSecondarySymmetry(), mat3_to_quat_is_ok(), mdisp_axis_from_quad(), mesh_calc_normals(), mesh_calc_normals_tessface(), mesh_edges_nearest_point(), meshdeform_inside_cage(), mul_fac_qt_fl(), multires_apply_smat(), multires_set_space(), multiresbake_get_normal(), multiresModifier_base_apply(), multiresModifier_disp_run(), nextLengthSubdivision(), node_shader_exec_camera(), node_shader_exec_material(), node_shader_exec_vect_math(), normal_quad_v3(), normal_tri_v3(), normalize_m3(), normalize_m4(), nr_signed_distance_to_plane(), ntap_bump_compute(), ob_parcurve(), occ_lookup(), occ_shade(), OrenNayar_Diff(), orthogonalize_m3(), orthogonalize_m4(), p_vec_angle_cos(), particle_billboard(), particle_normal_ren(), pbvh_update_normals(), PE_apply_lengths(), pe_deflect_emitter(), pe_iterate_lengths(), peelDerivedMesh(), Phong_Spec(), project_brush_radius(), project_paint_begin(), project_paint_uvpixel_mask(), psys_get_birth_coordinates(), psys_get_dupli_path_transform(), psys_get_particle_on_path(), psys_make_billboard(), psys_particle_on_dm(), psys_thread_create_path(), PushPull(), ray_ao_qmc(), ray_ao_spheresamp(), ray_fadeout_endcolor(), ray_shadow(), ray_shadow_qmc(), raycallback(), RE_inithalo(), RE_inithalo_particle(), RE_rayobject_instance_intersect(), RE_vlakren_get_normal(), recalc_emitter_field(), recalcData_view3d(), BL_MeshDeformer::RecalcNormals(), repositionBone(), RIG_calculateEdgeAngles(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), RotationBetween(), rule_average_speed(), rule_avoid_collision(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), sb_spring_force(), sculpt_stroke_get_location(), set_axis(), set_plane_exec(), set_prop_dist(), setNearestAxis3d(), shade_input_calc_viewco(), shade_input_set_normals(), shade_input_set_shade_texco(), shade_input_set_strand(), shade_input_set_triangle_i(), shade_input_set_vertex_normals(), shade_one_light(), shade_ray(), shade_sample_sss(), shadeAtmPixel(), shadeSkyPixel(), shadeSunView(), shadowbuf_autoclip(), shrinkwrap_calc_normal_projection(), shrinkwrap_get_tarmat(), sk_drawEdge(), sk_flattenStroke(), snapDerivedMesh(), snapEdge(), snapVertex(), softbody_calc_forces(), space_transform_apply_normal(), space_transform_invert_normal(), sph_force_cb(), sph_springs_modify(), sphere_do(), splineik_evaluate_bone(), spotvolume(), static_particle_strand(), static_particle_wire(), stretchto_evaluate(), surface_determineForceTargetPoints(), Toon_Spec(), ToSphere(), trace_reflect(), trace_refract(), Trackball(), TransMat3ToSize(), tri_to_quat(), triatomat(), ui_get_but_vectorf(), ui_ndofedit_but_HSVCIRCLE(), ui_numedit_but_HSVCIRCLE(), ui_numedit_but_NORMAL(), vec_roll_to_mat3(), vec_rot_to_quat(), vec_to_quat(), vectomat(), Vector_reflect(), Vector_rotation_difference(), vgroup_fix(), viewdolly_exec(), viewdolly_invoke(), vieworbit_exec(), viewrotate_apply(), vol_get_shadow(), vol_get_transmittance(), vol_precache_part(), vol_shade_one_lamp(), volumeintegrate(), and WardIso_Spec().
MINLINE float normalize_v3_v3 (float r[3], const float a[3])
Definition at line 581 of file math_vector_inline.c.
References dot_v3v3(), mul_v3_v3fl(), sqrtf, and zero_v3().
Referenced by angle_v3v3(), applyModifier(), axis_angle_to_mat3(), axis_angle_to_quat(), bm_face_calc_poly_normal(), BM_mesh_normals_update(), boid_body(), boid_find_ground(), calc_poly_normal(), cloth_calc_force(), cloth_collision(), dist_to_plane_v3(), DM_add_tangent_layer(), do_kink(), edbm_dupli_extrude_cursor_invoke(), edbm_extrude_repeat_exec(), flyApply(), get_effector_data(), GPU_default_lights(), isect_line_line_strict_v3(), isect_line_line_v3(), isect_line_plane_v3(), locktrack_evaluate(), mesh_calc_normals(), mesh_calc_normals_tessface(), ndof_to_axis_angle(), normalize_m3_m3(), normalize_m4_m4(), normalize_v3(), ocean_texture(), psys_get_birth_coordinates(), psys_make_billboard(), psys_render_projected_area(), rotate_v3_v3v3fl(), rule_fight(), sb_detect_vertex_collisionCached(), shadeSunView(), sk_initPoint(), spin_nurb(), strand_eval_point(), stretchto_evaluate(), vec_roll_to_mat3(), vectomat(), Vector_rotation_difference(), view3d_align_axis_to_vector(), viewAxisCorrectCenter(), and viewdolly_exec().
float normalize_vn (float * array_tar, const int size)
Definition at line 451 of file math_vector.c.
References normalize_vn_vn().
Referenced by M_Noise_random_unit_vector(), and Vector_normalize().
float normalize_vn_vn (float * array_tar, const float * array_src, const int size)
Definition at line 436 of file math_vector.c.
References dot_vn_vn(), fill_vn_fl(), mul_vn_vn_fl(), and sqrt().
Referenced by normalize_vn().
void ortho_basis_v3v3_v3 (float r1[3], float r2[3], const float a[3])
Definition at line 342 of file math_vector.c.
References sqrt().
Referenced by compatible_bump_compute(), compatible_bump_uv_derivs(), psys_render_projected_area(), ray_ao_qmc(), ray_shadow_qmc(), trace_reflect(), and trace_refract().
void print_v2 (const char * str, const float a[2])
Definition at line 396 of file math_vector.c.
void print_v3 (const char * str, const float a[3])
Definition at line 401 of file math_vector.c.
Referenced by RIG_printCtrl(), and RIG_printNode().
void print_v4 (const char * str, const float a[4])
Definition at line 406 of file math_vector.c.
void project_v2_v2v2 (float c[2], const float v1[2], const float v2[2])
Definition at line 275 of file math_vector.c.
References dot_v2v2(), and mul().
void project_v3_plane (float v[3], const float n[3], const float p[3])
Definition at line 296 of file math_vector.c.
References dot_v3v3(), len_squared_v3(), mul(), mul_v3_v3fl(), sub_v3_v3(), and sub_v3_v3v3().
void project_v3_v3v3 (float r[3], const float p[3], const float n[3])
Definition at line 285 of file math_vector.c.
References dot_v3v3(), and mul().
Referenced by _scan_for_ext_spring_forces(), axisProjection(), BLI_mirrorAlongAxis(), BM_face_create_ngon_vcloud(), bm_loop_flip_disp(), BME_bevel_poly(), boid_body(), boid_climb(), calcArcCorrelation(), cloth_calc_force(), do_kink(), ED_rollBoneToVector(), followtrack_evaluate(), get_effector_data(), handleRadialSymmetry(), InputHorizontalAbsolute(), InputVerticalAbsolute(), isect_line_line_v3(), locktrack_evaluate(), pivotcon_evaluate(), psys_get_birth_coordinates(), psys_thread_create_path(), PushPull(), RotationBetween(), rule_average_speed(), setNearestAxis3d(), sk_distanceDepth(), sk_flattenStroke(), static_particle_strand(), update_velocities(), vectomat(), and viewAxisCorrectCenter().
void range_vn_fl (float * array_tar, const int size, const float start, const float step)
Definition at line 466 of file math_vector.c.
References i, and size().
Referenced by C_Vector_Linspace(), and C_Vector_Range().
void range_vn_i (int * array_tar, const int size, const int start)
Definition at line 456 of file math_vector.c.
References i, and size().
Referenced by mesh_calc_modifiers().
void reflect_v3_v3v3 (float r[3], const float v[3], const float n[3])
Definition at line 324 of file math_vector.c.
References copy_v3_v3(), dot_v3v3(), and reflect().
Referenced by Vector_reflect().
void rotate_normalized_v3_v3v3fl (float v[3], const float p[3], const float axis[3], const float angle)
Definition at line 367 of file math_vector.c.
References cos(), and sin().
Referenced by rotate_v3_v3v3fl().
void rotate_v3_v3v3fl (float v[3], const float p[3], const float axis[3], const float angle)
Definition at line 385 of file math_vector.c.
References normalize_v3_v3(), and rotate_normalized_v3_v3v3fl().
MINLINE void star_m3_v3 (float rmat[3][3], float a[3])
MINLINE void sub_v2_v2 (float r[2], const float a[2])
Definition at line 275 of file math_vector_inline.c.
Referenced by draw_tracking_tracks(), flushTransTracking(), and marker_block_handler().
MINLINE void sub_v2_v2v2 (float r[2], const float a[2], const float b[2])
Definition at line 281 of file math_vector_inline.c.
Referenced by BKE_tracking_clamp_track(), BKE_tracking_next(), brush_painter_paint(), calc_vp_strength_dl(), calchandle_curvemap(), calculate_stabdata(), closest_to_line_v2(), DM_calc_auto_bump_scale(), do_projectpaint_thread(), draw_distortion(), draw_uvs_stretch(), dynamicPaint_createUVSurface(), dynamicPaint_findNeighbourPixel(), edbm_rip_edge_side_measure(), EDBM_uv_element_map_create(), EDBM_uv_vert_map_create(), flushTransTracking(), HC_relaxation_iteration_uv(), isect_seg_seg_v2_point(), laplacian_relaxation_iteration_uv(), len_squared_v2v2(), line_point_factor_v2(), make_uv_vert_map(), marker_block_handler(), paint_brush_stroke_add_step(), paint_space_stroke(), project_paint_uvpixel_init(), slide_marker_modal(), stitch_calculate_edge_normal(), texpaint_break_stroke(), uiTemplateMarker(), uv_image_outset(), uv_sculpt_stroke_apply(), and uv_sculpt_stroke_init().
MINLINE void sub_v3_v3 (float r[3], const float a[3])
Definition at line 287 of file math_vector_inline.c.
Referenced by _scan_for_ext_spring_forces(), add_normal_aligned(), alter_co(), applyModifier(), armature_deform_verts(), BM_face_create_ngon_vcloud(), boid_find_ground(), calcArcCorrelation(), cuboid_do(), curvemap_make_table(), dist_bone_deform(), do_kink(), do_rotate_brush(), do_set_scale(), docenter_armature(), draw_xyz_wire(), dynamicPaint_paintParticles(), dynamicPaint_prepareEffectStep(), ED_view3d_from_m4(), ED_view3d_win_to_vector(), edbm_dupli_extrude_cursor_invoke(), edbm_screw_exec(), edbm_spin_exec(), ElementResize(), ElementRotation(), envmaptex(), explodeMesh(), flyApply_ndof(), followtrack_evaluate(), initFlyInfo(), initWarp(), knife_edge_tri_isect(), mdisp_in_mdispquad(), minmax_object(), multires_set_space(), ndof_orbit_invoke(), ndof_pan_invoke(), new_primitive_matrix(), node_shader_exec_material(), object_apply_mat4(), object_make_proxy(), object_mat3_to_rot(), object_origin_set_exec(), particle_billboard(), pivotcon_evaluate(), pointdensity_cache_object(), pointdensity_cache_psys(), project_v3_plane(), psys_get_birth_coordinates(), PushPull(), quad_co(), rotateflagNurb(), rule_average_speed(), rule_flock(), save_hair(), sb_detect_face_pointCached(), scale_point(), set_3dcursor_invoke(), set_axis(), set_origin_exec(), set_plane_exec(), Shear(), sk_drawStroke(), sk_flattenStroke(), snap_sel_to_grid(), sphere_do(), vertex_dupli__mapFunc(), view3d_get_view_aligned_coordinate(), view3d_zoom_border_exec(), viewAxisCorrectCenter(), viewrotate_apply(), and Warp().
MINLINE void sub_v3_v3v3 (float r[3], const float a[3], const float b[3])
Definition at line 294 of file math_vector_inline.c.
Referenced by _scan_for_ext_spring_forces(), _softbody_calc_forces_slice_in_a_thread(), accumulate_vertex_normals(), accumulate_vertex_normals_poly(), alter_co(), angle_poly_v3(), angle_quad_v3(), angle_tri_v3(), angle_v3v3v3(), apply_armature_pose2bones_exec(), apply_heights_callback(), applyModifier(), applyProject(), ApplySnapTranslation(), area_lamp_energy_multisample(), area_quad_v3(), area_tri_v3(), armature_calc_roll_exec(), armature_click_extrude_exec(), armature_fill_bones_exec(), axisProjection(), b_bone_spline_setup(), basic_integrate(), bisect_v3_v3v3v3(), BLI_edgefill_ex(), BLI_mirrorAlongAxis(), BM_edge_calc_face_tangent(), BM_edge_rotate_check_degenerate(), BM_edge_split(), BM_editselection_normal(), BM_editselection_plane(), BM_face_create_ngon_vcloud(), BM_loop_calc_face_tangent(), bm_loop_flip_disp(), BM_loop_interp_from_face(), bm_loop_interp_mdisps(), BM_mesh_bm_to_me(), BM_mesh_normals_update(), BM_vert_interp_from_face(), BM_vert_normal_update(), BMBVH_EdgeVisible(), BMBVH_FindClosestVert(), BME_bevel_get_angle(), BME_bevel_get_vec(), BME_bevel_split_edge(), bmo_bevel_exec(), bmo_edgenet_prepare(), bmo_esubd_exec(), bmo_inset_exec(), bmo_similaredges_exec(), boid_body(), boid_climb(), boid_find_ground(), boid_goal_signed_dist(), bone_align_to_bone(), bone_connect_to_new_parent(), brush_add(), brush_length(), brush_puff(), brush_smooth_do(), brush_smooth_get(), cache_key_incremental_rotation(), calc_corner_co(), calc_curvepath(), calc_shapeKeys(), calcArcCorrelation(), calcCostAngleLengthDistance(), calchandleNurb_intern(), CalcSnapGeometry(), calculateCenterCursor(), camera_view_frame_fit_to_scene(), check_non_flat_quads(), clampto_evaluate(), clip_line_plane(), closest_to_line_v3(), closest_to_plane_v3(), cloth_apply_spring_force(), cloth_bvh_objcollision(), cloth_calc_force(), cloth_calc_helper_forces(), cloth_calc_spring_force(), cloth_collision_response_static(), collision_check(), collision_detect(), collision_move_object(), collision_point_distance_with_normal(), collision_point_on_surface(), collision_point_velocity(), collision_response(), collision_sphere_to_edges(), collision_sphere_to_tri(), collision_sphere_to_verts(), compute_mdisp_quad(), connect_hair(), convex(), costDistance(), cotan_weight(), createSlideVerts(), createTransArmatureVerts(), cuboid_do(), curvemap_make_table(), damptrack_evaluate(), deformVerts(), distfactor_to_bone(), distPointToSegmentSq(), distribute_grid(), DM_calc_auto_bump_scale(), do_clay_brush(), do_clay_strips_brush(), do_crease_brush(), do_fill_brush(), do_flatten_brush(), do_hair_dynamics(), do_kink(), do_mesh_smooth_brush(), do_multires_smooth_brush(), do_path_effectors(), do_pinch_brush(), do_scrape_brush(), draw_particle(), draw_rotation_guide(), draw_sphere_bone_dist(), draw_sphere_bone_wire(), draw_uvs_stretch(), draw_volume(), draw_xyz_wire(), drawLine(), DS_energy(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_brushObjectCalculateVelocity(), dynamicPaint_generateBakeData(), dynamicPaint_paintMesh(), dynamicPaint_paintSinglePoint(), dynamicPaint_prepareAdjacencyData(), ED_armature_apply_transform(), ED_armature_from_edit(), ED_object_new_primitive_matrix(), ED_object_parent_set(), ED_rollBoneToVector(), ED_view3d_global_to_vector(), ED_view3d_to_m4(), ED_view3d_win_to_ray(), edbm_extrude_mesh(), edbm_rip_invoke__vert(), edbm_screw_exec(), edgetag_cut_cost(), editmesh_set_connectivity_distance(), ElementResize(), ElementRotation(), execute_posetree(), execute_scene(), face_duplilist(), ff_quad_form_factor(), finalizeControl(), fix_bonelist_roll(), fix_connected_bone(), flagAxialSymmetry(), followtrack_evaluate(), get_effector_data(), get_matrix_editbone(), get_next_loop(), getEditBoneRollUpAxis(), getTransformOrientation(), getViewVector(), gp_get_3d_reference(), gp_stroke_convertcoords(), grid_tangent(), group_duplilist(), hair_velocity_smoothing(), handleRadialSymmetry(), heat_ray_source_visible(), heat_source_distance(), ImageRender::ImageRender(), implicit_solver(), init_rotsys(), integrate_particle(), interp_weights_face_v3(), isec_tri_quad(), isec_tri_quad_neighbour(), isect_axial_line_tri_v3(), isect_line_line_strict_v3(), isect_line_line_v3(), isect_line_plane_v3(), isect_line_tri_v3(), isect_ray_plane_v3(), isect_ray_tri_epsilon_v3(), isect_ray_tri_threshold_v3(), isect_ray_tri_v3(), isect_sweeping_sphere_tri_v3(), join_armature_exec(), knife_input_ray_cast(), lamp_get_visibility(), len_squared_v3v3(), len_v3v3(), line_point_factor_v3(), locktrack_evaluate(), M_Geometry_intersect_ray_tri(), make_bevel_list_segment_3D(), markdownSecondarySymmetry(), mdisp_axis_from_quad(), mean_value_half_tan(), measure_facepair(), mesh_edges_nearest_point(), mesh_octree_table(), meshdeform_inside_cage(), meshdeform_ray_tree_intersect(), meshdeform_tri_intersect(), meshdeformModifier_do(), multires_apply_smat(), multires_modifier_update_mdisps(), multiresModifier_disp_run(), nearest_point_in_tri_surface(), nearest_uv_between(), new_particle_duplilist(), nextAdaptativeSubdivision(), nextLengthSubdivision(), nr_distance_to_edge(), nr_signed_distance_to_plane(), object_hook_recenter_exec(), occ_build_dco(), occ_lookup(), occ_quad_form_factor(), p_chart_pin_positions(), particle_billboard(), pdDoEffectors(), PE_apply_lengths(), pe_deflect_emitter(), pe_iterate_lengths(), pivotcon_evaluate(), plane_point_side(), plane_point_side_flip(), planeProjection(), point_in_slice(), point_plane_project(), precache_init_parts(), precache_resolution(), precalc_guides(), precalculate_effector(), project_paint_begin(), project_v3_plane(), psys_cache_edit_paths(), psys_get_birth_coordinates(), psys_get_dupli_path_transform(), psys_get_particle_on_path(), psys_interpolate_face(), psys_interpolate_particle(), psys_make_billboard(), psys_thread_create_path(), ptcache_particle_interpolate(), ptcache_particle_read(), PushPull(), ray_shadow(), ray_shadow_qmc(), ray_trace(), RE_inithalo(), RE_inithalo_particle(), recalcData_view3d(), render_new_particle_system(), repositionBone(), repositionControl(), ResizeBetween(), RIG_calculateEdgeAngles(), RIG_parentControl(), rollBoneByQuatAligned(), rollBoneByQuatJoint(), RotationBetween(), rule_avoid_collision(), rule_fight(), rule_follow_leader(), rule_goal_avoid(), rule_separate(), sample_occ_cache(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), sb_spring_force(), scale_quad(), scale_tri(), sculpt_flush_pbvhvert_deform(), sculpt_search_sphere_cb(), sculpt_stroke_get_location(), sculpt_update_brush_delta(), sculpt_vertcos_to_key(), set_prop_dist(), setNearestAxis3d(), shade_lamp_loop(), shade_ray(), Shear(), shrink_edgef(), sk_applyTrimGesture(), sk_detectDeleteGesture(), sk_detectReverseGesture(), sk_detectTrimGesture(), sk_distanceDepth(), sk_drawEdge(), sk_flattenStroke(), sk_getSegments(), sk_getSelfIntersections(), sk_projectDrawPoint(), sk_straightenStroke(), snap_sel_to_curs(), snapEdge(), snapVertex(), softbody_calc_forces(), special_transvert_update(), sph_force_cb(), sph_integrate(), sph_particle_courant(), sph_springs_modify(), splineik_evaluate_bone(), stabilization_auto_scale_factor(), static_particle_strand(), static_particle_wire(), strand_eval_point(), stretchto_evaluate(), sub_fmatrix_fmatrix(), sub_lfvector_lfvector(), surfaceGenerateGrid(), tangent_from_uv(), testAxialSymmetry(), ToSphere(), trackto_evaluate(), traverse_octree(), tri_to_quat(), triatomat(), update_courant_num(), update_velocities(), uv_cylinder_project(), uv_sphere_project(), v3_dist_from_plane(), v3d_editvertex_buts(), vcloud_estimate_transform(), vectomat(), vertsearchcallback(), vgroup_fix(), view3d_all_exec(), viewAxisCorrectCenter(), viewops_data_create(), viewrotate_apply(), viewselected_exec(), vol_get_precached_scattering(), vol_get_shadow(), where_is_armature_bone(), and where_on_path_deform().
MINLINE void sub_v4_v4 (float r[4], const float a[4])
Definition at line 301 of file math_vector_inline.c.
MINLINE void sub_v4_v4v4 (float r[4], const float a[4], const float b[4])
Definition at line 309 of file math_vector_inline.c.
void sub_vn_vn (float * array_tar, const float * array_src, const int size)
Definition at line 534 of file math_vector.c.
References i, and size().
Referenced by Color_isub(), and Vector_isub().
void sub_vn_vnvn (float * array_tar, const float * array_src_a, const float * array_src_b, const int size)
Definition at line 544 of file math_vector.c.
References i, and size().
Referenced by Color_sub(), Matrix_sub(), and Vector_sub().
MINLINE void swap_v2_v2 (float a[2], float b[2])
Definition at line 211 of file math_vector_inline.c.
References SWAP.
MINLINE void swap_v3_v3 (float a[3], float b[3])
Definition at line 217 of file math_vector_inline.c.
References SWAP.
Referenced by bm_loop_reverse_loop(), sculpt_undo_restore_coords(), sculpt_undo_restore_deformed(), and switch_keys_direction().
MINLINE void swap_v4_v4 (float a[4], float b[4])
Definition at line 224 of file math_vector_inline.c.
References SWAP.
MINLINE void zero_v2 (float r[2])
Definition at line 38 of file math_vector_inline.c.
Referenced by BKE_movieclip_get_stable_ibuf(), BKE_tracking_stabilization_data(), BKE_tracking_stabilize(), clip_draw_main(), draw_distortion(), ED_uvedit_median(), get_area_imbuf(), layerInterp_mloop_origspace(), layerInterp_mloopuv(), normalize_v2_v2(), poly_uv_center(), projectFloatView(), resolve_quad_uv(), resolve_tri_uv(), and uvedit_center().
MINLINE void zero_v3 (float r[3])
Definition at line 44 of file math_vector_inline.c.
Referenced by ambient_occlusion(), apply_armature_pose2bones_exec(), apply_objects_internal(), applyModifier(), bake_shade(), basic_integrate(), BKE_mesh_validate_arrays(), BKE_metaball_center_median(), BlenderWorldInfo::BlenderWorldInfo(), BLI_edgefill_ex(), BM_face_calc_center_mean(), bm_face_calc_poly_normal_vertex_cos(), BM_face_create_ngon_vcloud(), BM_face_normal_update(), BM_face_normal_update_vcos(), BM_mesh_normals_update(), BM_vert_normal_update(), BME_bevel_get_vec(), BME_bevel_poly(), bmo_inset_exec(), boundbox_displist(), calc_area_normal(), calc_area_normal_and_flatten_center(), calc_flatten_center(), calc_manipulator_stats(), calc_poly_plane(), calc_solidify_normals(), cdDM_getMinMax(), clip_line_plane(), collision_interpolateOnTriangle(), Color_CreatePyObject(), constraint_mat_convertspace(), convertViewVec(), createRepresentation(), createSlideVerts(), curve_center_median(), docenter_armature(), draw_bgpic(), draw_em_measure_stats(), draw_sphere_bone_dist(), drawcamera(), drawfloor(), drawlamp(), ED_image_draw_info(), ED_object_rotation_from_view(), ED_view3d_project_float_v3(), ED_view3d_win_to_3d(), edbm_extrude_edge(), edbm_extrude_mesh(), edbm_sort_faces_exec(), emDM__calcFaceCent(), emDM_getMinMax(), Euler_CreatePyObject(), Euler_zero(), flyApply(), followtrack_evaluate(), getSingleCoordinate(), getTransformOrientation(), gp_layer_to_curve(), init_render_curve(), init_rotsys(), initData(), initFlyInfo(), integrate_particle(), knife_pos_data_clear(), layerInterp_shapekey(), make_trans_verts(), mesh_calc_ngon_center(), mesh_center_median(), meshdeform_dynamic_bind(), meshdeformModifier_do(), minmax_new_data(), multitex_nodes(), neighbor_average(), normalize_v3_v3(), object_clear_rot(), object_get_dimensions(), object_origin_set_exec(), occ_lookup(), occ_sum_occlusion(), paint_brush_stroke_add_step(), pchan_clear_rot(), psys_get_birth_coordinates(), psys_make_billboard(), psys_thread_create_path(), ray_ao_qmc(), ray_ao_spheresamp(), rest_pose(), return_editcurve_indexar(), return_editlattice_indexar(), return_editmesh_indexar(), return_editmesh_vgroup(), RVBlurBitmap2_byte(), RVBlurBitmap2_float(), sample_occ_cache(), sample_occ_surface(), sample_occ_tree(), sculpt_update_brush_delta(), set_origin_exec(), shrinkwrap_get_tarmat(), snap_curs_to_center(), snap_curs_to_sel(), softbody_reset(), tex_space_curve(), tex_space_mesh(), vcloud_estimate_transform(), view3d_all_exec(), and vol_get_scattering().
MINLINE void zero_v4 (float r[4])
Definition at line 51 of file math_vector_inline.c.
Referenced by calculate_speedvectors(), ED_image_draw_info(), gpu_material_to_fixed(), move_stack(), and svd_m4().