Blender: TransformWriter Class Reference
TransformWriter Class Reference
#include <TransformWriter.h>
Protected Member Functions
void add_node_transform (COLLADASW::Node &node, float mat[][4], float parent_mat[][4])
void add_node_transform_ob (COLLADASW::Node &node, Object *ob)
void add_node_transform_identity (COLLADASW::Node &node)
Detailed Description
Definition at line 37 of file TransformWriter.h.
Member Function Documentation
void TransformWriter::add_node_transform (COLLADASW::Node & node, float mat[][4], float parent_mat[][4]) [protected]
Definition at line 35 of file TransformWriter.cpp.
References copy_m4_m4(), TransformBase::decompose(), invert_m4_m4(), UnitConverter::mat4_to_dae_double(), mult_m4_m4m4(), NULL, and rot.
void TransformWriter::add_node_transform_identity (COLLADASW::Node & node) [protected]
Definition at line 121 of file TransformWriter.cpp.
References rot.
void TransformWriter::add_node_transform_ob (COLLADASW::Node & node, Object * ob) [protected]
Definition at line 60 of file TransformWriter.cpp.
References i, Object::loc, UnitConverter::mat4_to_dae_double(), Object::parent, Object::parentinv, Object::rot, and Object::size.
The documentation for this class was generated from the following files:
TransformWriter.h
TransformWriter.cpp