Blender: rna_main_api.c File Reference
rna_main_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include "RNA_define.h"
#include "RNA_access.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "BKE_utildefines.h"
Functions
void RNA_api_main (StructRNA *srna)
void RNA_def_main_cameras (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_scenes (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_objects (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_materials (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_node_groups (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_meshes (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_lamps (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_libraries (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_screens (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_window_managers (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_images (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_lattices (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_curves (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_metaballs (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_fonts (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_textures (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_brushes (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_worlds (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_groups (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_speakers (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_texts (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_sounds (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_armatures (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_actions (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_particles (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_gpencil (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_movieclips (BlenderRNA *brna, PropertyRNA *cprop)
Detailed Description
Definition in file rna_main_api.c.
Function Documentation
void RNA_api_main (StructRNA * srna)
Definition at line 602 of file rna_main_api.c.
References PROP_REQUIRED, RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string_file_path().
Referenced by RNA_def_main().
void RNA_def_main_actions (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1401 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_armatures (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1367 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_brushes (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1161 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_cameras (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 618 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_curves (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1020 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, object_type_curve_items, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_fonts (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1090 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_gpencil (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1470 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_groups (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1231 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_images (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 936 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_lamps (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 837 of file rna_main_api.c.
References FUNC_USE_REPORTS, lamp_type_items, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_lattices (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 986 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_libraries (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 874 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_materials (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 727 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_meshes (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 803 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_metaballs (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1056 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_movieclips (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1491 of file rna_main_api.c.
References FILE_MAX, FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_node_groups (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 761 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_objects (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 688 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_particles (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1435 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_scenes (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 653 of file rna_main_api.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_screens (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 895 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_sounds (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1344 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_speakers (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1265 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_texts (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1300 of file rna_main_api.c.
References FILE_MAX, FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_textures (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1125 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and texture_type_items.
Referenced by RNA_def_main().
void RNA_def_main_window_managers (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 916 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_worlds (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1196 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().