Blender: BLI_rect.h File Reference
BLI_rect.h File Reference
blenlib
Functions
int BLI_rcti_is_empty (struct rcti *rect)
int BLI_rctf_is_empty (struct rctf *rect)
void BLI_init_rctf (struct rctf *rect, float xmin, float xmax, float ymin, float ymax)
void BLI_init_rcti (struct rcti *rect, int xmin, int xmax, int ymin, int ymax)
void BLI_translate_rctf (struct rctf *rect, float x, float y)
void BLI_translate_rcti (struct rcti *rect, int x, int y)
void BLI_resize_rcti (struct rcti *rect, int x, int y)
void BLI_resize_rctf (struct rctf *rect, float x, float y)
int BLI_in_rcti (struct rcti *rect, int x, int y)
int BLI_in_rctf (struct rctf *rect, float x, float y)
int BLI_segment_in_rcti (struct rcti *rect, int s1[2], int s2[2])
int BLI_isect_rctf (struct rctf *src1, struct rctf *src2, struct rctf *dest)
int BLI_isect_rcti (struct rcti *src1, struct rcti *src2, struct rcti *dest)
void BLI_union_rctf (struct rctf *rcta, struct rctf *rctb)
void BLI_union_rcti (struct rcti *rcti1, struct rcti *rcti2)
void BLI_copy_rcti_rctf (struct rcti *tar, const struct rctf *src)
void print_rctf (const char *str, struct rctf *rect)
void print_rcti (const char *str, struct rcti *rect)
Detailed Description
Definition in file BLI_rect.h.
Function Documentation
void BLI_copy_rcti_rctf (struct rcti * tar, const struct rctf * src)
Referenced by draw_gpencil_view3d().
int BLI_in_rctf (struct rctf * rect, float x, float y)
Definition at line 60 of file rct.c.
References rctf::xmax, and rctf::ymax.
Referenced by blf_glyph_render(), border_select_cb(), border_select_exec(), draw_marker_areas(), draw_marker_outline(), isb_bsp_face_inside(), line_clip_rect2f(), node_find_indicated_socket(), node_mouse_groupheader(), node_resize_area_default(), node_under_mouse(), project_bucket_clip_face(), project_bucket_face_isect(), project_bucket_isect_circle(), and ui_handle_menu_event().
int BLI_in_rcti (struct rcti * rect, int x, int y)
Definition at line 51 of file rct.c.
References rcti::xmax, and rcti::ymax.
Referenced by actionzone_area_poll(), area_event_inside(), BLI_segment_in_rcti(), do_lasso_select_mesh__doSelectFace(), do_lasso_select_mesh__doSelectVert(), do_lattice_box_select__doSelect(), do_mesh_box_select__doSelectFace(), do_mesh_box_select__doSelectVert(), do_nurbs_box_select__doSelect(), ED_area_overdraw_flush(), ED_screen_set_subwinactive(), edge_fully_inside_rect(), file_hilight_set(), file_select_invoke(), gp_stroke_eraser_dostroke(), handler_boundbox_test(), is_in_area_actionzone(), region_event_inside(), screen_areahascursor(), ui_but_mouse_inside_icon(), ui_do_drag(), ui_mouse_inside_region(), ui_searchbox_event(), ui_searchbox_inside(), wm_event_do_handlers(), wm_event_inside_i(), wm_operator_invoke(), and wm_paintcursor_test().
void BLI_init_rctf (struct rctf * rect, float xmin, float xmax, float ymin, float ymax)
Definition at line 134 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by add_scene(), curvemapping_add(), draw_marker_areas(), and draw_marker_outline().
void BLI_init_rcti (struct rcti * rect, int xmin, int xmax, int ymin, int ymax)
Definition at line 154 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by area_azone_initialize(), find_file_mouse_rect(), mixed_bones_object_selectbuffer(), region_azone_edge(), region_azone_icon(), region_azone_tab(), region_azone_tab_plus(), region_azone_tria(), and region_rect_recursive().
int BLI_isect_rctf (struct rctf * src1, struct rctf * src2, struct rctf * dest)
Definition at line 210 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by isb_bsp_face_inside(), node_borderselect_exec(), sequencer_borderselect_exec(), and visible_node().
int BLI_isect_rcti (struct rcti * src1, struct rcti * src2, struct rcti * dest)
Definition at line 240 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by file_border_select_exec(), file_border_select_modal(), game_engine_exec(), region_scissor_winrct(), ui_draw_but_CURVE(), view3d_update_depths_rect(), wm_flush_regions_down(), and wm_flush_regions_up().
int BLI_rctf_is_empty (struct rctf * rect)
Definition at line 46 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_draw_basis().
int BLI_rcti_is_empty (struct rcti * rect)
Determine if a rect is empty. An empty rect is one with a zero (or negative) width or height.
Returns:
True if rect is empty.
Definition at line 41 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by sculpt_get_redraw_rect().
void BLI_resize_rctf (struct rctf * rect, float x, float y)
Definition at line 200 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by sequencer_view_zoom_ratio_exec().
void BLI_resize_rcti (struct rcti * rect, int x, int y)
Definition at line 190 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
int BLI_segment_in_rcti (struct rcti * rect, int s1[2], int s2[2])
Definition at line 83 of file rct.c.
References BLI_in_rcti(), isect_segments(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by mesh_foreachScreenEdge__mapFunc().
void BLI_translate_rctf (struct rctf * rect, float x, float y)
Definition at line 181 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void BLI_translate_rcti (struct rcti * rect, int x, int y)
Definition at line 174 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by area_dupli_invoke(), and handler_boundbox_test().
void BLI_union_rctf (struct rctf * rcta, struct rctf * rctb)
Definition at line 118 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_update_group(), and snode_home().
void BLI_union_rcti (struct rcti * rcti1, struct rcti * rcti2)
Definition at line 126 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by sculpt_get_redraw_rect().
void print_rctf (const char * str, struct rctf * rect)
Definition at line 278 of file rct.c.
References rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
void print_rcti (const char * str, struct rcti * rect)
Definition at line 284 of file rct.c.
References rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.