Blender: BLI_string_cursor_utf8.h File Reference
BLI_string_cursor_utf8.h File Reference
Typedefs
typedef enum strCursorJumpType strCursorJumpType
typedef enum strCursorJumpDirection strCursorJumpDirection
Enumerations
enum strCursorJumpType { STRCUR_JUMP_NONE, STRCUR_JUMP_DELIM, STRCUR_JUMP_ALL }
enum strCursorJumpDirection { STRCUR_DIR_PREV, STRCUR_DIR_NEXT }
Functions
int BLI_str_cursor_step_next_utf8 (const char *str, size_t maxlen, int *pos)
int BLI_str_cursor_step_prev_utf8 (const char *str, size_t maxlen, int *pos)
void BLI_str_cursor_step_utf8 (const char *str, size_t maxlen, int *pos, strCursorJumpDirection direction, strCursorJumpType jump)
Typedef Documentation
typedef enum strCursorJumpDirection strCursorJumpDirection
typedef enum strCursorJumpType strCursorJumpType
Enumeration Type Documentation
enum strCursorJumpDirection
Enumerator:
STRCUR_DIR_PREV
STRCUR_DIR_NEXT
Definition at line 39 of file BLI_string_cursor_utf8.h.
enum strCursorJumpType
Enumerator:
STRCUR_JUMP_NONE
STRCUR_JUMP_DELIM
STRCUR_JUMP_ALL
Definition at line 33 of file BLI_string_cursor_utf8.h.
Function Documentation
int BLI_str_cursor_step_next_utf8 (const char * str, size_t maxlen, int * pos)
Definition at line 115 of file string_cursor_utf8.c.
References BLI_str_find_next_char_utf8(), FALSE, and TRUE.
Referenced by BLI_str_cursor_step_utf8().
int BLI_str_cursor_step_prev_utf8 (const char * str, size_t maxlen, int * pos)
Referenced by BLI_str_cursor_step_utf8(), and ui_textedit_set_cursor_pos().
void BLI_str_cursor_step_utf8 (const char * str, size_t maxlen, int * pos, strCursorJumpDirection direction, strCursorJumpType jump)
Definition at line 145 of file string_cursor_utf8.c.
References ABS, BLI_assert, BLI_str_cursor_step_next_utf8(), BLI_str_cursor_step_prev_utf8(), STRCUR_DELIM_NONE, STRCUR_DIR_NEXT, STRCUR_DIR_PREV, STRCUR_JUMP_ALL, STRCUR_JUMP_NONE, and test_special_char().
Referenced by console_delete_exec(), console_move_exec(), txt_jump_left(), txt_jump_right(), ui_textedit_delete(), and ui_textedit_move().