Blender: BL_Texture.cpp File Reference
BL_Texture.cpp File Reference
Ketsji
#include "GL/glew.h"
#include <iostream>
#include <map>
#include <stdlib.h>
#include "BL_Material.h"
#include "BL_Texture.h"
#include "MT_assert.h"
#include "DNA_texture_types.h"
#include "DNA_image_types.h"
#include "IMB_imbuf_types.h"
#include "BKE_image.h"
#include "BLI_blenlib.h"
#include "RAS_OpenGLRasterizer/RAS_GLExtensionManager.h"
#include "RAS_ICanvas.h"
#include "RAS_Rect.h"
#include "KX_GameObject.h"
#include "MEM_guardedalloc.h"
#include "GPU_draw.h"
#include "IMB_imbuf.h"
Classes
class BL_TextureObject
Defines
#define spit(x) std::cout << x << std::endl;
#define SetCubeMapFace(face, num)
Typedefs
typedef std::map< char
*, BL_TextureObject > BL_TextureMap
Functions
void my_envmap_split_ima (EnvMap *env, ImBuf *ibuf)
void my_free_envmapdata (EnvMap *env)
static int is_power_of_2_i (int num)
static int power_of_2_min_i (int num)
Variables
static BL_TextureMap g_textureManager
Detailed Description
Definition in file BL_Texture.cpp.
Define Documentation
#define SetCubeMapFace (face, num)
Value:
glTexImage2D(face, 0,GL_RGBA,   \
    cubemap->cube[num]->x,          \
    cubemap->cube[num]->y,          \
    0, GL_RGBA, GL_UNSIGNED_BYTE,   \
    cubemap->cube[num]->rect)
Referenced by BL_Texture::InitCubeMap().
#define spit (x) std::cout << x << std::endl;
Definition at line 28 of file BL_Texture.cpp.
Referenced by BL_Texture::InitCubeMap().
Typedef Documentation
typedef std::map<char*, BL_TextureObject> BL_TextureMap
Definition at line 60 of file BL_Texture.cpp.
Function Documentation
static int is_power_of_2_i (int num) [static]
Definition at line 41 of file BL_Texture.cpp.
void my_envmap_split_ima (EnvMap * env, ImBuf * ibuf)
Definition at line 633 of file BL_Texture.cpp.
References EnvMap::cube, IB_rect, EnvMap::ima, IMB_allocImBuf(), IMB_rectcpy(), my_free_envmapdata(), Image::ok, EnvMap::ok, ImBuf::x, and ImBuf::y.
Referenced by BL_Texture::InitCubeMap(), and BL_Texture::SplitEnvMap().
void my_free_envmapdata (EnvMap * env)
Definition at line 668 of file BL_Texture.cpp.
References EnvMap::cube, IMB_freeImBuf(), NULL, and EnvMap::ok.
Referenced by BL_Texture::InitCubeMap(), and my_envmap_split_ima().
static int power_of_2_min_i (int num) [static]
Definition at line 45 of file BL_Texture.cpp.
References is_power_of_2_i().
Variable Documentation
BL_TextureMap g_textureManager [static]
Definition at line 61 of file BL_Texture.cpp.
Referenced by BL_Texture::DeleteTex(), BL_Texture::InitCubeMap(), and BL_Texture::InitFromImage().