Blender: MT_Point3.inl File Reference
MT_Point3.inl File Reference
#include "MT_Optimize.h"
Functions
GEN_INLINE MT_Point3 operator+ (const MT_Point3 &p, const MT_Vector3 &v)
GEN_INLINE MT_Point3 operator- (const MT_Point3 &p, const MT_Vector3 &v)
GEN_INLINE MT_Vector3 operator- (const MT_Point3 &p1, const MT_Point3 &p2)
GEN_INLINE MT_Scalar MT_distance (const MT_Point3 &p1, const MT_Point3 &p2)
GEN_INLINE MT_Scalar MT_distance2 (const MT_Point3 &p1, const MT_Point3 &p2)
GEN_INLINE MT_Point3 MT_lerp (const MT_Point3 &p1, const MT_Point3 &p2, MT_Scalar t)
Function Documentation
GEN_INLINE MT_Scalar MT_distance (const MT_Point3 & p1, const MT_Point3 & p2)
Definition at line 49 of file MT_Point3.inl.
References MT_Point3::distance().
GEN_INLINE MT_Scalar MT_distance2 (const MT_Point3 & p1, const MT_Point3 & p2)
Definition at line 53 of file MT_Point3.inl.
References MT_Point3::distance2().
GEN_INLINE MT_Point3 MT_lerp (const MT_Point3 & p1, const MT_Point3 & p2, MT_Scalar t)
Definition at line 57 of file MT_Point3.inl.
References MT_Point3::lerp().
GEN_INLINE MT_Point3 operator+ (const MT_Point3 & p, const MT_Vector3 & v)
Definition at line 37 of file MT_Point3.inl.
GEN_INLINE MT_Vector3 operator- (const MT_Point3 & p1, const MT_Point3 & p2)
Definition at line 45 of file MT_Point3.inl.
GEN_INLINE MT_Point3 operator- (const MT_Point3 & p, const MT_Vector3 & v)
Definition at line 41 of file MT_Point3.inl.