Blender: targa.c File Reference
targa.c File Reference
IMage Buffer
#include "BLI_blenlib.h"
#include "MEM_guardedalloc.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_allocimbuf.h"
#include "IMB_filetype.h"
Classes
struct TARGA
Defines
#define GSS(x) (((uchar *)(x))[1] << 8 | ((uchar *)(x))[0])
Typedefs
typedef struct TARGA TARGA
Functions
static int tga_out1 (unsigned int data, FILE *file)
static int tga_out2 (unsigned int data, FILE *file)
static int tga_out3 (unsigned int data, FILE *file)
static int tga_out4 (unsigned int data, FILE *file)
static short makebody_tga (ImBuf *ibuf, FILE *file, int(*out)(unsigned int, FILE *))
static int dumptarga (struct ImBuf *ibuf, FILE *file)
int imb_savetarga (struct ImBuf *ibuf, const char *name, int flags)
static int checktarga (TARGA *tga, unsigned char *mem)
int imb_is_a_targa (unsigned char *buf)
static void complete_partial_load (struct ImBuf *ibuf, unsigned int *rect)
static void decodetarga (struct ImBuf *ibuf, unsigned char *mem, size_t mem_size, int psize)
static void ldtarga (struct ImBuf *ibuf, unsigned char *mem, size_t mem_size, int psize)
struct ImBuf * imb_loadtarga (unsigned char *mem, size_t mem_size, int flags)
Detailed Description
Definition in file targa.c.
Define Documentation
#define GSS (x) (((uchar *)(x))[1] << 8 | ((uchar *)(x))[0])
Definition at line 49 of file targa.c.
Referenced by checktarga().
Typedef Documentation
typedef struct TARGA TARGA
Function Documentation
static int checktarga (TARGA * tga, unsigned char * mem) [static]
Definition at line 312 of file targa.c.
References GSS, TARGA::imgdes, TARGA::imgtyp, TARGA::mapbits, TARGA::maporig, TARGA::mapsize, TARGA::maptyp, TARGA::numid, TARGA::pixsize, TARGA::xorig, TARGA::xsize, TARGA::yorig, and TARGA::ysize.
Referenced by imb_is_a_targa(), and imb_loadtarga().
static void complete_partial_load (struct ImBuf * ibuf, unsigned int * rect) [static]
Definition at line 355 of file targa.c.
References ImBuf::rect, size(), ImBuf::x, and ImBuf::y.
Referenced by decodetarga(), and ldtarga().
static void decodetarga (struct ImBuf * ibuf, unsigned char * mem, size_t mem_size, int psize) [static]
Definition at line 370 of file targa.c.
References complete_partial_load(), NULL, ImBuf::rect, size(), ImBuf::x, and ImBuf::y.
Referenced by imb_loadtarga().
static int dumptarga (struct ImBuf * ibuf, FILE * file) [static]
Definition at line 195 of file targa.c.
References if(), NULL, ImBuf::planes, ImBuf::rect, size(), ImBuf::x, and ImBuf::y.
Referenced by imb_savetarga().
int imb_is_a_targa (unsigned char * buf)
Definition at line 348 of file targa.c.
References checktarga().
struct ImBuf* imb_loadtarga (unsigned char * mem, size_t mem_size, int flags) [read]
Definition at line 548 of file targa.c.
References BIG_LONG, checktarga(), ImBuf::crect, decodetarga(), ImBuf::ftype, IB_PROFILE_SRGB, IB_rect, IB_test, IMB_allocImBuf(), IMB_convert_rgba_to_abgr(), IMB_flipy(), TARGA::imgdes, TARGA::imgtyp, ldtarga(), TARGA::mapbits, TARGA::mapsize, MEM_callocN(), MEM_freeN(), NULL, TARGA::numid, TARGA::pixsize, ImBuf::planes, ImBuf::profile, ImBuf::rect, size(), TGA, ImBuf::x, TARGA::xsize, ImBuf::y, and TARGA::ysize.
int imb_savetarga (struct ImBuf * ibuf, const char * name, int flags)
Definition at line 246 of file targa.c.
References BLI_fopen(), dumptarga(), ImBuf::ftype, makebody_tga(), ImBuf::planes, RAWTGA, tga_out1(), tga_out2(), tga_out3(), tga_out4(), ImBuf::x, and ImBuf::y.
static void ldtarga (struct ImBuf * ibuf, unsigned char * mem, size_t mem_size, int psize) [static]
Definition at line 488 of file targa.c.
References complete_partial_load(), NULL, ImBuf::rect, size(), ImBuf::x, and ImBuf::y.
Referenced by imb_loadtarga().
static short makebody_tga (ImBuf * ibuf, FILE * file, int(*)(unsigned int, FILE *) out) [static]
Definition at line 116 of file targa.c.
References copy(), FALSE, ImBuf::rect, TRUE, ImBuf::x, and ImBuf::y.
Referenced by imb_savetarga().
static int tga_out1 (unsigned int data, FILE * file) [static]
Definition at line 71 of file targa.c.
References p.
Referenced by imb_savetarga().
static int tga_out2 (unsigned int data, FILE * file) [static]
Definition at line 80 of file targa.c.
References p.
Referenced by imb_savetarga().
static int tga_out3 (unsigned int data, FILE * file) [static]
Definition at line 91 of file targa.c.
References p.
Referenced by imb_savetarga().
static int tga_out4 (unsigned int data, FILE * file) [static]
Definition at line 103 of file targa.c.
References p.
Referenced by imb_savetarga().