Blender: rna_rna.c File Reference
rna_rna.c File Reference
RNA
#include <stdlib.h>
#include "DNA_ID.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "rna_internal.h"
Functions
static void rna_def_struct (BlenderRNA *brna)
static void rna_def_property (BlenderRNA *brna)
static void rna_def_function (BlenderRNA *brna)
static void rna_def_number_property (StructRNA *srna, PropertyType type)
static void rna_def_string_property (StructRNA *srna)
static void rna_def_enum_property (BlenderRNA *brna, StructRNA *srna)
static void rna_def_pointer_property (StructRNA *srna, PropertyType type)
void RNA_def_rna (BlenderRNA *brna)
Variables
EnumPropertyItem property_type_items []
EnumPropertyItem property_subtype_items []
EnumPropertyItem property_unit_items []
Detailed Description
Definition in file rna_rna.c.
Function Documentation
static void rna_def_enum_property (BlenderRNA * brna, StructRNA * srna) [static]
Definition at line 1327 of file rna_rna.c.
References NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_ENUM_FLAG, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_rna().
static void rna_def_function (BlenderRNA * brna) [static]
Definition at line 1175 of file rna_rna.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_rna().
static void rna_def_number_property (StructRNA * srna, PropertyType type) [static]
Definition at line 1221 of file rna_rna.c.
References NULL, PROP_BOOLEAN, PROP_DYNAMIC, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), and RNA_def_property_ui_text().
Referenced by RNA_def_rna().
static void rna_def_pointer_property (StructRNA * srna, PropertyType type) [static]
Definition at line 1385 of file rna_rna.c.
References NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), and RNA_def_property_ui_text().
Referenced by RNA_def_rna().
static void rna_def_property (BlenderRNA * brna) [static]
Definition at line 1040 of file rna_rna.c.
References NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_COLOR, PROP_COLOR_GAMMA, PROP_COORDS, PROP_DIRECTION, PROP_DIRPATH, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_EULER, PROP_FACTOR, PROP_FILEPATH, PROP_LAYER, PROP_LAYER_MEMBER, PROP_MATRIX, PROP_NONE, PROP_PERCENTAGE, PROP_POINTER, PROP_QUATERNION, PROP_STRING, PROP_TIME, PROP_TRANSLATION, PROP_UNSIGNED, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_rna().
void RNA_def_rna (BlenderRNA * brna)
Definition at line 1399 of file rna_rna.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, rna_def_enum_property(), rna_def_function(), rna_def_number_property(), rna_def_pointer_property(), rna_def_property(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), rna_def_string_property(), RNA_def_struct(), rna_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
static void rna_def_string_property (StructRNA * srna) [static]
Definition at line 1312 of file rna_rna.c.
References NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_int_funcs(), RNA_def_property_string_funcs(), and RNA_def_property_ui_text().
Referenced by RNA_def_rna().
static void rna_def_struct (BlenderRNA * brna) [static]
Definition at line 973 of file rna_rna.c.
References NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_rna().
Variable Documentation
EnumPropertyItem property_subtype_items[]
Definition at line 47 of file rna_rna.c.
EnumPropertyItem property_type_items[]
Initial value:
 {
    {PROP_BOOLEAN, "BOOLEAN", 0, "Boolean", ""},
    {PROP_INT, "INT", 0, "Integer", ""},
    {PROP_FLOAT, "FLOAT", 0, "Float", ""},
    {PROP_STRING, "STRING", 0, "String", ""},
    {PROP_ENUM, "ENUM", 0, "Enumeration", ""},
    {PROP_POINTER, "POINTER", 0, "Pointer", ""},
    {PROP_COLLECTION, "COLLECTION", 0, "Collection", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 37 of file rna_rna.c.
Referenced by pyrna_prop_str().
EnumPropertyItem property_unit_items[]
Initial value:
 {
    {PROP_UNIT_NONE, "NONE", 0, "None", ""},
    {PROP_UNIT_LENGTH, "LENGTH", 0, "Length", ""},
    {PROP_UNIT_AREA, "AREA", 0, "Area", ""},
    {PROP_UNIT_VOLUME, "VOLUME", 0, "Volume", ""},
    {PROP_UNIT_ROTATION, "ROTATION", 0, "Rotation", ""},
    {PROP_UNIT_TIME, "TIME", 0, "Time", ""},
    {PROP_UNIT_VELOCITY, "VELOCITY", 0, "Velocity", ""},
    {PROP_UNIT_ACCELERATION, "ACCELERATION", 0, "Acceleration", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 84 of file rna_rna.c.
Referenced by BPy_FloatProperty(), and BPy_FloatVectorProperty().