Blender: RAS_ListSlot Class Reference
RAS_ListSlot Class Reference
#include <RAS_ListRasterizer.h>
Public Member Functions
RAS_ListSlot (RAS_ListRasterizer *rasty)
virtual ~RAS_ListSlot ()
virtual void SetModified (bool mod)
virtual int Release ()
void RemoveList ()
void DrawList ()
void EndList ()
bool End ()
Friends
class RAS_ListRasterizer
Detailed Description
Definition at line 15 of file RAS_ListRasterizer.h.
Constructor & Destructor Documentation
RAS_ListSlot::RAS_ListSlot (RAS_ListRasterizer * rasty)
Definition at line 27 of file RAS_ListRasterizer.cpp.
RAS_ListSlot::~RAS_ListSlot () [virtual]
Definition at line 45 of file RAS_ListRasterizer.cpp.
References RemoveList().
Member Function Documentation
void RAS_ListSlot::DrawList ()
Definition at line 60 of file RAS_ListRasterizer.cpp.
References LIST_BEGIN, LIST_CREATE, LIST_MODIFY, LIST_NOCREATE, LIST_STREAM, RemoveList(), and spit.
Referenced by RAS_ListRasterizer::IndexPrimitives(), and RAS_ListRasterizer::IndexPrimitivesMulti().
bool RAS_ListSlot::End ()
Definition at line 102 of file RAS_ListRasterizer.cpp.
References LIST_END.
Referenced by RAS_ListRasterizer::IndexPrimitives(), and RAS_ListRasterizer::IndexPrimitivesMulti().
void RAS_ListSlot::EndList ()
Definition at line 83 of file RAS_ListRasterizer.cpp.
References LIST_BEGIN, LIST_END, and LIST_MODIFY.
Referenced by RAS_ListRasterizer::IndexPrimitives(), and RAS_ListRasterizer::IndexPrimitivesMulti().
int RAS_ListSlot::Release () [virtual]
Reimplemented from KX_ListSlot.
Definition at line 36 of file RAS_ListRasterizer.cpp.
References KX_ListSlot::m_refcount, and RAS_ListRasterizer::RemoveListSlot().
void RAS_ListSlot::RemoveList ()
Definition at line 51 of file RAS_ListRasterizer.cpp.
References spit.
Referenced by DrawList(), and ~RAS_ListSlot().
void RAS_ListSlot::SetModified (bool mod) [virtual]
Implements KX_ListSlot.
Definition at line 93 of file RAS_ListRasterizer.cpp.
References LIST_END, LIST_MODIFY, LIST_STREAM, and spit.
Friends And Related Function Documentation
friend class RAS_ListRasterizer [friend]
Definition at line 17 of file RAS_ListRasterizer.h.
The documentation for this class was generated from the following files:
RAS_ListRasterizer.h
RAS_ListRasterizer.cpp