Blender: string_cursor_utf8.c File Reference
string_cursor_utf8.c File Reference
blenlib
#include <stdio.h>
#include <stdlib.h>
#include "BLI_utildefines.h"
#include "BLI_string_utf8.h"
#include "BLI_string_cursor_utf8.h"
Typedefs
typedef enum strCursorDelimType strCursorDelimType
Enumerations
enum strCursorDelimType {
STRCUR_DELIM_NONE, STRCUR_DELIM_ALPHA, STRCUR_DELIM_PUNCT, STRCUR_DELIM_BRACE,
STRCUR_DELIM_OPERATOR, STRCUR_DELIM_QUOTE, STRCUR_DELIM_WHITESPACE, STRCUR_DELIM_OTHER
}
Functions
static strCursorDelimType test_special_char (const char *ch_utf8)
int BLI_str_cursor_step_next_utf8 (const char *str, size_t maxlen, int *pos)
int BLI_str_cursor_step_prev_utf8 (const char *str, size_t UNUSED(maxlen), int *pos)
void BLI_str_cursor_step_utf8 (const char *str, size_t maxlen, int *pos, strCursorJumpDirection direction, strCursorJumpType jump)
Detailed Description
Definition in file string_cursor_utf8.c.
Typedef Documentation
typedef enum strCursorDelimType strCursorDelimType
Enumeration Type Documentation
enum strCursorDelimType
Enumerator:
STRCUR_DELIM_NONE
STRCUR_DELIM_ALPHA
STRCUR_DELIM_PUNCT
STRCUR_DELIM_BRACE
STRCUR_DELIM_OPERATOR
STRCUR_DELIM_QUOTE
STRCUR_DELIM_WHITESPACE
STRCUR_DELIM_OTHER
Definition at line 39 of file string_cursor_utf8.c.
Function Documentation
int BLI_str_cursor_step_next_utf8 (const char * str, size_t maxlen, int * pos)
Definition at line 115 of file string_cursor_utf8.c.
References BLI_str_find_next_char_utf8(), FALSE, and TRUE.
Referenced by BLI_str_cursor_step_utf8().
int BLI_str_cursor_step_prev_utf8 (const char * str, size_t UNUSEDmaxlen, int * pos)
Definition at line 131 of file string_cursor_utf8.c.
References BLI_str_find_prev_char_utf8(), FALSE, and TRUE.
void BLI_str_cursor_step_utf8 (const char * str, size_t maxlen, int * pos, strCursorJumpDirection direction, strCursorJumpType jump)
Definition at line 145 of file string_cursor_utf8.c.
References ABS, BLI_assert, BLI_str_cursor_step_next_utf8(), BLI_str_cursor_step_prev_utf8(), STRCUR_DELIM_NONE, STRCUR_DIR_NEXT, STRCUR_DIR_PREV, STRCUR_JUMP_ALL, STRCUR_JUMP_NONE, and test_special_char().
Referenced by console_delete_exec(), console_move_exec(), txt_jump_left(), txt_jump_right(), ui_textedit_delete(), and ui_textedit_move().
static strCursorDelimType test_special_char (const char * ch_utf8) [static]
Definition at line 51 of file string_cursor_utf8.c.
References BLI_str_utf8_as_unicode(), STRCUR_DELIM_ALPHA, STRCUR_DELIM_BRACE, STRCUR_DELIM_NONE, STRCUR_DELIM_OPERATOR, STRCUR_DELIM_OTHER, STRCUR_DELIM_PUNCT, STRCUR_DELIM_QUOTE, and STRCUR_DELIM_WHITESPACE.
Referenced by BLI_str_cursor_step_utf8().