Blender: ScrollBar.h File Reference
ScrollBar.h File Reference
Typedefs
typedef struct _ScrollBar ScrollBar
Functions
ScrollBar * scrollbar_new (int inset, int minthumb)
int scrollbar_is_scrolling (ScrollBar *sb)
int scrollbar_contains_pt (ScrollBar *sb, int pt[2])
void scrollbar_start_scrolling (ScrollBar *sb, int yco)
void scrollbar_keep_scrolling (ScrollBar *sb, int yco)
void scrollbar_stop_scrolling (ScrollBar *sb)
void scrollbar_set_thumbpct (ScrollBar *sb, float pct)
void scrollbar_set_thumbpos (ScrollBar *sb, float pos)
void scrollbar_set_rect (ScrollBar *sb, int rect[2][2])
float scrollbar_get_thumbpct (ScrollBar *sb)
float scrollbar_get_thumbpos (ScrollBar *sb)
void scrollbar_get_rect (ScrollBar *sb, int rect_r[2][2])
void scrollbar_get_thumb (ScrollBar *sb, int thumb_r[2][2])
void scrollbar_free (ScrollBar *sb)
Typedef Documentation
typedef struct _ScrollBar ScrollBar
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 28 of file ScrollBar.h.
Function Documentation
int scrollbar_contains_pt (ScrollBar * sb, int pt[2])
Definition at line 92 of file ScrollBar.c.
References _ScrollBar::rect, and rect_contains_pt().
Referenced by loggerwindow_do_button().
void scrollbar_free (ScrollBar * sb)
Definition at line 139 of file ScrollBar.c.
References MEM_freeN().
void scrollbar_get_rect (ScrollBar * sb, int rect_r[2][2])
Definition at line 135 of file ScrollBar.c.
References _ScrollBar::rect, and rect_copy().
Referenced by loggerwindow_do_draw().
void scrollbar_get_thumb (ScrollBar * sb, int thumb_r[2][2])
Definition at line 78 of file ScrollBar.c.
References _ScrollBar::inset, _ScrollBar::rect, scrollbar_get_thumbableH(), scrollbar_get_thumbH(), and _ScrollBar::thumbpos.
Referenced by loggerwindow_do_draw().
float scrollbar_get_thumbpct (ScrollBar * sb)
Definition at line 129 of file ScrollBar.c.
References _ScrollBar::thumbpct.
float scrollbar_get_thumbpos (ScrollBar * sb)
Definition at line 132 of file ScrollBar.c.
References _ScrollBar::thumbpos.
Referenced by loggerwindow_do_draw().
int scrollbar_is_scrolling (ScrollBar * sb)
Definition at line 89 of file ScrollBar.c.
References _ScrollBar::scrolling.
Referenced by loggerwindow_do_button(), loggerwindow_do_draw(), and loggerwindow_do_move().
void scrollbar_keep_scrolling (ScrollBar * sb, int yco)
Definition at line 109 of file ScrollBar.c.
References clamp_f(), scrollbar_co_to_pos(), _ScrollBar::scrolloffs, and _ScrollBar::thumbpos.
Referenced by loggerwindow_do_move().
ScrollBar* scrollbar_new (int inset, int minthumb)
Definition at line 70 of file ScrollBar.c.
References _ScrollBar::inset, MEM_callocN(), and _ScrollBar::minthumb.
Referenced by loggerwindow_new().
void scrollbar_set_rect (ScrollBar * sb, int rect[2][2])
Definition at line 125 of file ScrollBar.c.
References _ScrollBar::rect, and rect_copy().
Referenced by loggerwindow_recalc_regions().
void scrollbar_set_thumbpct (ScrollBar * sb, float pct)
Definition at line 119 of file ScrollBar.c.
References _ScrollBar::thumbpct.
Referenced by loggerwindow_log(), and loggerwindow_recalc_regions().
void scrollbar_set_thumbpos (ScrollBar * sb, float pos)
Definition at line 122 of file ScrollBar.c.
References clamp_f(), and _ScrollBar::thumbpos.
void scrollbar_start_scrolling (ScrollBar * sb, int yco)
Definition at line 96 of file ScrollBar.c.
References clamp_f(), fabs(), scrollbar_co_to_pos(), scrollbar_get_thumbableH(), scrollbar_get_thumbH(), _ScrollBar::scrolling, _ScrollBar::scrolloffs, and _ScrollBar::thumbpos.
Referenced by loggerwindow_do_button().
void scrollbar_stop_scrolling (ScrollBar * sb)
Definition at line 114 of file ScrollBar.c.
References _ScrollBar::scrolling, and _ScrollBar::scrolloffs.
Referenced by loggerwindow_do_button().