Blender: AUD_PyAPI.cpp File Reference
AUD_PyAPI.cpp File Reference
Audaspace Python
#include "AUD_PyAPI.h"
#include "structmember.h"
#include "AUD_I3DDevice.h"
#include "AUD_I3DHandle.h"
#include "AUD_NULLDevice.h"
#include "AUD_DelayFactory.h"
#include "AUD_DoubleFactory.h"
#include "AUD_FaderFactory.h"
#include "AUD_HighpassFactory.h"
#include "AUD_LimiterFactory.h"
#include "AUD_LoopFactory.h"
#include "AUD_LowpassFactory.h"
#include "AUD_PingPongFactory.h"
#include "AUD_PitchFactory.h"
#include "AUD_ReverseFactory.h"
#include "AUD_SinusFactory.h"
#include "AUD_FileFactory.h"
#include "AUD_SquareFactory.h"
#include "AUD_StreamBufferFactory.h"
#include "AUD_SuperposeFactory.h"
#include "AUD_VolumeFactory.h"
#include "AUD_IIRFilterFactory.h"
Defines
#define PY_MODULE_ADD_CONSTANT(module, name) PyModule_AddIntConstant(module, #name, name)
Enumerations
enum AUD_DeviceTypes {
AUD_DEVICE_NULL = 0, AUD_DEVICE_OPENAL, AUD_DEVICE_SDL, AUD_DEVICE_JACK,
AUD_DEVICE_READ
}
Functions
static void Factory_dealloc (Factory *self)
static PyObject * Factory_new (PyTypeObject *type, PyObject *args, PyObject *kwds)
PyDoc_STRVAR (M_aud_Factory_sine_doc,"sine(frequency, rate=44100)\n\n""Creates a sine factory which plays a sine wave.\n\n"":arg frequency: The frequency of the sine wave in Hz.\n"":type frequency: float\n"":arg rate: The sampling rate in Hz. It's recommended to set this ""value to the playback device's samling rate to avoid resamping.\n"":type rate: int\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_sine (PyTypeObject *type, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_file_doc,"file(filename)\n\n""Creates a factory object of a sound file.\n\n"":arg filename: Path of the file.\n"":type filename: string\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. warning:: If the file doesn't exist or can't be read you will ""not get an exception immediately, but when you try to start ""playback of that factory.")
static PyObject * Factory_file (PyTypeObject *type, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_lowpass_doc,"lowpass(frequency, Q=0.5)\n\n""Creates a second order lowpass filter based on the transfer ""function H(s) = 1 / (s^2 + s/Q + 1)\n\n"":arg frequency: The cut off trequency of the lowpass.\n"":type frequency: float\n"":arg Q: Q factor of the lowpass.\n"":type Q: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_lowpass (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_delay_doc,"delay(time)\n\n""Delays by playing adding silence in front of the other factory's ""data.\n\n"":arg time: How many seconds of silence should be added before ""the factory.\n"":type time: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_delay (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_join_doc,"join(factory)\n\n""Plays two factories in sequence.\n\n"":arg factory: The factory to play second.\n"":type factory: :class:`Factory`\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: The two factories have to have the same specifications ""(channels and samplerate).")
static PyObject * Factory_join (Factory *self, PyObject *object)
PyDoc_STRVAR (M_aud_Factory_highpass_doc,"highpass(frequency, Q=0.5)\n\n""Creates a second order highpass filter based on the transfer ""function H(s) = s^2 / (s^2 + s/Q + 1)\n\n"":arg frequency: The cut off trequency of the highpass.\n"":type frequency: float\n"":arg Q: Q factor of the lowpass.\n"":type Q: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_highpass (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_limit_doc,"limit(start, end)\n\n""Limits a factory within a specific start and end time.\n\n"":arg start: Start time in seconds.\n"":type start: float\n"":arg end: End time in seconds.\n"":type end: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_limit (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_pitch_doc,"pitch(factor)\n\n""Changes the pitch of a factory with a specific factor.\n\n"":arg factor: The factor to change the pitch with.\n"":type factor: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: This is done by changing the sample rate of the ""underlying factory, which has to be an integer, so the factor ""value rounded and the factor may not be 100 % accurate.\n\n"".. note:: This is a filter function, you might consider using "":attr:`Handle.pitch` instead.")
static PyObject * Factory_pitch (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_volume_doc,"volume(volume)\n\n""Changes the volume of a factory.\n\n"":arg volume: The new volume..\n"":type volume: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: Should be in the range [0, 1] to avoid clipping.\n\n"".. note:: This is a filter function, you might consider using "":attr:`Handle.volume` instead.")
static PyObject * Factory_volume (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_fadein_doc,"fadein(start, length)\n\n""Fades a factory in by raising the volume linearly in the given ""time interval.\n\n"":arg start: Time in seconds when the fading should start.\n"":type start: float\n"":arg length: Time in seconds how long the fading should last.\n"":type length: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: Before the fade starts it plays silence.")
static PyObject * Factory_fadein (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_fadeout_doc,"fadeout(start, length)\n\n""Fades a factory in by lowering the volume linearly in the given ""time interval.\n\n"":arg start: Time in seconds when the fading should start.\n"":type start: float\n"":arg length: Time in seconds how long the fading should last.\n"":type length: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: After the fade this factory plays silence, so that ""the length of the factory is not altered.")
static PyObject * Factory_fadeout (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_loop_doc,"loop(count)\n\n""Loops a factory.\n\n"":arg count: How often the factory should be looped. ""Negative values mean endlessly.\n"":type count: integer\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: This is a filter function, you might consider using "":attr:`Handle.loop_count` instead.")
static PyObject * Factory_loop (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_mix_doc,"mix(factory)\n\n""Mixes two factories.\n\n"":arg factory: The factory to mix over the other.\n"":type factory: :class:`Factory`\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: The two factories have to have the same specifications ""(channels and samplerate).")
static PyObject * Factory_mix (Factory *self, PyObject *object)
PyDoc_STRVAR (M_aud_Factory_pingpong_doc,"pingpong()\n\n""Plays a factory forward and then backward.\n""This is like joining a factory with its reverse.\n\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_pingpong (Factory *self)
PyDoc_STRVAR (M_aud_Factory_reverse_doc,"reverse()\n\n""Plays a factory reversed.\n\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: The factory has to have a finite length and has to be ""seekable. It's recommended to use this only with factories with ""fast and accurate seeking, which is not true for encoded audio ""files, such ones should be buffered using :meth:`buffer` before ""being played reversed.\n\n"".. warning:: If seeking is not accurate in the underlying factory ""you'll likely hear skips/jumps/cracks.")
static PyObject * Factory_reverse (Factory *self)
PyDoc_STRVAR (M_aud_Factory_buffer_doc,"buffer()\n\n""Buffers a factory into RAM.\n""This saves CPU usage needed for decoding and file access if the ""underlying factory reads from a file on the harddisk, but it ""consumes a lot of memory.\n\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: Only known-length factories can be buffered.\n\n"".. warning:: Raw PCM data needs a lot of space, only buffer ""short factories.")
static PyObject * Factory_buffer (Factory *self)
PyDoc_STRVAR (M_aud_Factory_square_doc,"square(threshold = 0)\n\n""Makes a square wave out of an audio wave by setting all samples ""with a amplitude >= threshold to 1, all <= -threshold to -1 and ""all between to 0.\n\n"":arg threshold: Threshold value over which an amplitude counts ""non-zero.\n"":type threshold: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_square (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_filter_doc,"filter(b, a = (1))\n\n""Filters a factory with the supplied IIR filter coefficients.\n""Without the second parameter you'll get a FIR filter.\n""If the first value of the a sequence is 0 it will be set to 1 ""automatically.\n""If the first value of the a sequence is neither 0 nor 1, all ""filter coefficients will be scaled by this value so that it is 1 ""in the end, you don't have to scale yourself.\n\n"":arg b: The nominator filter coefficients.\n"":type b: sequence of float\n"":arg a: The denominator filter coefficients.\n"":type a: sequence of float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
static PyObject * Factory_filter (Factory *self, PyObject *args)
PyDoc_STRVAR (M_aud_Factory_doc,"Factory objects are immutable and represent a sound that can be ""played simultaneously multiple times. They are called factories ""because they create reader objects internally that are used for ""playback.")
static void Handle_dealloc (Handle *self)
PyDoc_STRVAR (M_aud_Handle_pause_doc,"pause()\n\n""Pauses playback.\n\n"":return: Whether the action succeeded.\n"":rtype: bool")
static PyObject * Handle_pause (Handle *self)
PyDoc_STRVAR (M_aud_Handle_resume_doc,"resume()\n\n""Resumes playback.\n\n"":return: Whether the action succeeded.\n"":rtype: bool")
static PyObject * Handle_resume (Handle *self)
PyDoc_STRVAR (M_aud_Handle_stop_doc,"stop()\n\n""Stops playback.\n\n"":return: Whether the action succeeded.\n"":rtype: bool\n\n"".. note:: This makes the handle invalid.")
static PyObject * Handle_stop (Handle *self)
PyDoc_STRVAR (M_aud_Handle_position_doc,"The playback position of the sound in seconds.")
static PyObject * Handle_get_position (Handle *self, void *nothing)
static int Handle_set_position (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_keep_doc,"Whether the sound should be kept paused in the device when its ""end is reached.\n""This can be used to seek the sound to some position and start ""playback again.\n\n"".. warning:: If this is set to true and you forget stopping this ""equals a memory leak as the handle exists until the device is ""destroyed.")
static PyObject * Handle_get_keep (Handle *self, void *nothing)
static int Handle_set_keep (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_status_doc,"Whether the sound is playing, paused or stopped (=invalid).")
static PyObject * Handle_get_status (Handle *self, void *nothing)
PyDoc_STRVAR (M_aud_Handle_volume_doc,"The volume of the sound.")
static PyObject * Handle_get_volume (Handle *self, void *nothing)
static int Handle_set_volume (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_pitch_doc,"The pitch of the sound.")
static PyObject * Handle_get_pitch (Handle *self, void *nothing)
static int Handle_set_pitch (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_loop_count_doc,"The (remaining) loop count of the sound. A negative value indicates infinity.")
static PyObject * Handle_get_loop_count (Handle *self, void *nothing)
static int Handle_set_loop_count (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_location_doc,"The source's location in 3D space, a 3D tuple of floats.")
static PyObject * Handle_get_location (Handle *self, void *nothing)
static int Handle_set_location (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_velocity_doc,"The source's velocity in 3D space, a 3D tuple of floats.")
static PyObject * Handle_get_velocity (Handle *self, void *nothing)
static int Handle_set_velocity (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_orientation_doc,"The source's orientation in 3D space as quaternion, a 4 float tuple.")
static PyObject * Handle_get_orientation (Handle *self, void *nothing)
static int Handle_set_orientation (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_relative_doc,"Whether the source's location, velocity and orientation is relative or absolute to the listener.")
static PyObject * Handle_get_relative (Handle *self, void *nothing)
static int Handle_set_relative (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_volume_minimum_doc,"The minimum volume of the source.\n\n"".. seealso:: :attr:`Device.distance_model`")
static PyObject * Handle_get_volume_minimum (Handle *self, void *nothing)
static int Handle_set_volume_minimum (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_volume_maximum_doc,"The maximum volume of the source.\n\n"".. seealso:: :attr:`Device.distance_model`")
static PyObject * Handle_get_volume_maximum (Handle *self, void *nothing)
static int Handle_set_volume_maximum (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_distance_reference_doc,"The reference distance of the source.\n""At this distance the volume will be exactly :attr:`volume`.\n\n"".. seealso:: :attr:`Device.distance_model`")
static PyObject * Handle_get_distance_reference (Handle *self, void *nothing)
static int Handle_set_distance_reference (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_distance_maximum_doc,"The maximum distance of the source.\n""If the listener is further away the source volume will be 0.\n\n"".. seealso:: :attr:`Device.distance_model`")
static PyObject * Handle_get_distance_maximum (Handle *self, void *nothing)
static int Handle_set_distance_maximum (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_attenuation_doc,"This factor is used for distance based attenuation of the ""source.\n\n"".. seealso:: :attr:`Device.distance_model`")
static PyObject * Handle_get_attenuation (Handle *self, void *nothing)
static int Handle_set_attenuation (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_cone_angle_inner_doc,"The opening angle of the inner cone of the source. If the cone ""values of a source are set there are two (audible) cones with ""the apex at the :attr:`location` of the source and with infinite ""height, heading in the direction of the source's "":attr:`orientation`.\n""In the inner cone the volume is normal. Outside the outer cone ""the volume will be :attr:`cone_volume_outer` and in the area ""between the volume will be interpolated linearly.")
static PyObject * Handle_get_cone_angle_inner (Handle *self, void *nothing)
static int Handle_set_cone_angle_inner (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_cone_angle_outer_doc,"The opening angle of the outer cone of the source.\n\n"".. seealso:: :attr:`cone_angle_inner`")
static PyObject * Handle_get_cone_angle_outer (Handle *self, void *nothing)
static int Handle_set_cone_angle_outer (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_cone_volume_outer_doc,"The volume outside the outer cone of the source.\n\n"".. seealso:: :attr:`cone_angle_inner`")
static PyObject * Handle_get_cone_volume_outer (Handle *self, void *nothing)
static int Handle_set_cone_volume_outer (Handle *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Handle_doc,"Handle objects are playback handles that can be used to control ""playback of a sound. If a sound is played back multiple times ""then there are as many handles.")
static void Device_dealloc (Device *self)
static PyObject * Device_new (PyTypeObject *type, PyObject *args, PyObject *kwds)
PyDoc_STRVAR (M_aud_Device_play_doc,"play(factory, keep=False)\n\n""Plays a factory.\n\n"":arg factory: The factory to play.\n"":type factory: :class:`Factory`\n"":arg keep: See :attr:`Handle.keep`.\n"":type keep: bool\n"":return: The playback handle with which playback can be ""controlled with.\n"":rtype: :class:`Handle`")
static PyObject * Device_play (Device *self, PyObject *args, PyObject *kwds)
PyDoc_STRVAR (M_aud_Device_stopAll_doc,"stopAll()\n\n""Stops all playing and paused sounds.")
static PyObject * Device_stopAll (Device *self)
PyDoc_STRVAR (M_aud_Device_lock_doc,"lock()\n\n""Locks the device so that it's guaranteed, that no samples are ""read from the streams until :meth:`unlock` is called.\n""This is useful if you want to do start/stop/pause/resume some ""sounds at the same time.\n\n"".. note:: The device has to be unlocked as often as locked to be ""able to continue playback.\n\n"".. warning:: Make sure the time between locking and unlocking is ""as short as possible to avoid clicks.")
static PyObject * Device_lock (Device *self)
PyDoc_STRVAR (M_aud_Device_unlock_doc,"unlock()\n\n""Unlocks the device after a lock call, see :meth:`lock` for ""details.")
static PyObject * Device_unlock (Device *self)
PyDoc_STRVAR (M_aud_Device_rate_doc,"The sampling rate of the device in Hz.")
static PyObject * Device_get_rate (Device *self, void *nothing)
PyDoc_STRVAR (M_aud_Device_format_doc,"The native sample format of the device.")
static PyObject * Device_get_format (Device *self, void *nothing)
PyDoc_STRVAR (M_aud_Device_channels_doc,"The channel count of the device.")
static PyObject * Device_get_channels (Device *self, void *nothing)
PyDoc_STRVAR (M_aud_Device_volume_doc,"The overall volume of the device.")
static PyObject * Device_get_volume (Device *self, void *nothing)
static int Device_set_volume (Device *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Device_listener_location_doc,"The listeners's location in 3D space, a 3D tuple of floats.")
static PyObject * Device_get_listener_location (Device *self, void *nothing)
static int Device_set_listener_location (Device *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Device_listener_velocity_doc,"The listener's velocity in 3D space, a 3D tuple of floats.")
static PyObject * Device_get_listener_velocity (Device *self, void *nothing)
static int Device_set_listener_velocity (Device *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Device_listener_orientation_doc,"The listener's orientation in 3D space as quaternion, a 4 float tuple.")
static PyObject * Device_get_listener_orientation (Device *self, void *nothing)
static int Device_set_listener_orientation (Device *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Device_speed_of_sound_doc,"The speed of sound of the device.\n""The speed of sound in air is typically 343 m/s.")
static PyObject * Device_get_speed_of_sound (Device *self, void *nothing)
static int Device_set_speed_of_sound (Device *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Device_doppler_factor_doc,"The doppler factor of the device.\n""This factor is a scaling factor for the velocity vectors in ""doppler calculation. So a value bigger than 1 will exaggerate ""the effect as it raises the velocity.")
static PyObject * Device_get_doppler_factor (Device *self, void *nothing)
static int Device_set_doppler_factor (Device *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Device_distance_model_doc,"The distance model of the device.\n\n"".. seealso:: http://connect.creativelabs.com/openal/Documentation/OpenAL%201.1%20Specification.htm#_Toc199835864")
static PyObject * Device_get_distance_model (Device *self, void *nothing)
static int Device_set_distance_model (Device *self, PyObject *args, void *nothing)
PyDoc_STRVAR (M_aud_Device_doc,"Device objects represent an audio output backend like OpenAL or ""SDL, but might also represent a file output or RAM buffer ""output.")
PyObject * Device_empty ()
PyObject * Factory_empty ()
Factory * checkFactory (PyObject *factory)
PyDoc_STRVAR (M_aud_doc,"This module provides access to the audaspace audio library.")
PyMODINIT_FUNC PyInit_aud (void)
Variables
static PyObject * AUDError
static const char * device_not_3d_error = "Device is not a 3D device!"
static PyMethodDef Factory_methods []
static PyTypeObject FactoryType
static PyMethodDef Handle_methods []
static PyGetSetDef Handle_properties []
static PyTypeObject HandleType
static PyMethodDef Device_methods []
static PyGetSetDef Device_properties []
static PyTypeObject DeviceType
static struct PyModuleDef audmodule
Detailed Description
Definition in file AUD_PyAPI.cpp.
Define Documentation
#define PY_MODULE_ADD_CONSTANT (module, name) PyModule_AddIntConstant(module, #name, name)
Definition at line 79 of file AUD_PyAPI.cpp.
Referenced by PyInit_aud().
Enumeration Type Documentation
enum AUD_DeviceTypes
Enumerator:
AUD_DEVICE_NULL
AUD_DEVICE_OPENAL
AUD_DEVICE_SDL
AUD_DEVICE_JACK
AUD_DEVICE_READ
Definition at line 68 of file AUD_PyAPI.cpp.
Function Documentation
Factory* checkFactory (PyObject * factory)
Definition at line 2836 of file AUD_PyAPI.cpp.
References NULL.
static void Device_dealloc (Device * self) [static]
Definition at line 2104 of file AUD_PyAPI.cpp.
PyObject* Device_empty ()
Definition at line 2824 of file AUD_PyAPI.cpp.
static PyObject* Device_get_channels (Device * self, void * nothing) [static]
Definition at line 2373 of file AUD_PyAPI.cpp.
References AUDError, AUD_DeviceSpecs::channels, NULL, and AUD_Exception::str.
static PyObject* Device_get_distance_model (Device * self, void * nothing) [static]
Definition at line 2704 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::getDistanceModel(), NULL, and AUD_Exception::str.
static PyObject* Device_get_doppler_factor (Device * self, void * nothing) [static]
Definition at line 2650 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::getDopplerFactor(), NULL, and AUD_Exception::str.
static PyObject* Device_get_format (Device * self, void * nothing) [static]
Definition at line 2355 of file AUD_PyAPI.cpp.
References AUDError, AUD_DeviceSpecs::format, NULL, and AUD_Exception::str.
static PyObject* Device_get_listener_location (Device * self, void * nothing) [static]
Definition at line 2428 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::getListenerLocation(), NULL, AUD_Exception::str, AUD_Vector3::x(), AUD_Vector3::y(), and AUD_Vector3::z().
static PyObject* Device_get_listener_orientation (Device * self, void * nothing) [static]
Definition at line 2538 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::getListenerOrientation(), NULL, AUD_Exception::str, AUD_Quaternion::w(), AUD_Quaternion::x(), AUD_Quaternion::y(), and AUD_Quaternion::z().
static PyObject* Device_get_listener_velocity (Device * self, void * nothing) [static]
Definition at line 2483 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::getListenerVelocity(), NULL, AUD_Exception::str, AUD_Vector3::x(), AUD_Vector3::y(), and AUD_Vector3::z().
static PyObject* Device_get_rate (Device * self, void * nothing) [static]
Definition at line 2337 of file AUD_PyAPI.cpp.
References AUDError, NULL, AUD_DeviceSpecs::rate, and AUD_Exception::str.
static PyObject* Device_get_speed_of_sound (Device * self, void * nothing) [static]
Definition at line 2594 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::getSpeedOfSound(), NULL, and AUD_Exception::str.
static PyObject* Device_get_volume (Device * self, void * nothing) [static]
Definition at line 2391 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Device_lock (Device * self) [static]
Definition at line 2283 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Device_new (PyTypeObject * type, PyObject * args, PyObject * kwds) [static]
Definition at line 2112 of file AUD_PyAPI.cpp.
References AUD_CHANNELS_STEREO, AUD_DEFAULT_BUFFER_SIZE, AUD_DEVICE_JACK, AUD_DEVICE_NULL, AUD_DEVICE_OPENAL, AUD_DEVICE_READ, AUD_DEVICE_SDL, AUD_FORMAT_FLOAT32, AUD_RATE_44100, AUDError, AUD_DeviceSpecs::channels, AUD_DeviceSpecs::format, NULL, AUD_DeviceSpecs::rate, and AUD_Exception::str.
static PyObject* Device_play (Device * self, PyObject * args, PyObject * kwds) [static]
Definition at line 2202 of file AUD_PyAPI.cpp.
References AUDError, Factory::factory, Handle::handle, NULL, and AUD_Exception::str.
static int Device_set_distance_model (Device * self, PyObject * args, void * nothing) [static]
Definition at line 2727 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::setDistanceModel(), and AUD_Exception::str.
static int Device_set_doppler_factor (Device * self, PyObject * args, void * nothing) [static]
Definition at line 2673 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::setDopplerFactor(), and AUD_Exception::str.
static int Device_set_listener_location (Device * self, PyObject * args, void * nothing) [static]
Definition at line 2452 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::setListenerLocation(), and AUD_Exception::str.
static int Device_set_listener_orientation (Device * self, PyObject * args, void * nothing) [static]
Definition at line 2562 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::setListenerOrientation(), and AUD_Exception::str.
static int Device_set_listener_velocity (Device * self, PyObject * args, void * nothing) [static]
Definition at line 2507 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::setListenerVelocity(), and AUD_Exception::str.
static int Device_set_speed_of_sound (Device * self, PyObject * args, void * nothing) [static]
Definition at line 2617 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DDevice::setSpeedOfSound(), and AUD_Exception::str.
static int Device_set_volume (Device * self, PyObject * args, void * nothing) [static]
Definition at line 2405 of file AUD_PyAPI.cpp.
References AUDError, and AUD_Exception::str.
static PyObject* Device_stopAll (Device * self) [static]
Definition at line 2257 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Device_unlock (Device * self) [static]
Definition at line 2303 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Factory_buffer (Factory * self) [static]
Definition at line 764 of file AUD_PyAPI.cpp.
References AUDError, Factory::factory, NULL, and AUD_Exception::str.
static void Factory_dealloc (Factory * self) [static]
Definition at line 90 of file AUD_PyAPI.cpp.
static PyObject* Factory_delay (Factory * self, PyObject * args) [static]
Definition at line 263 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
PyObject* Factory_empty ()
Definition at line 2830 of file AUD_PyAPI.cpp.
static PyObject* Factory_fadein (Factory * self, PyObject * args) [static]
Definition at line 520 of file AUD_PyAPI.cpp.
References AUD_FADE_IN, AUDError, Factory::child_list, Factory::factory, length(), NULL, and AUD_Exception::str.
static PyObject* Factory_fadeout (Factory * self, PyObject * args) [static]
Definition at line 564 of file AUD_PyAPI.cpp.
References AUD_FADE_OUT, AUDError, Factory::child_list, Factory::factory, length(), NULL, and AUD_Exception::str.
static PyObject* Factory_file (PyTypeObject * type, PyObject * args) [static]
Definition at line 182 of file AUD_PyAPI.cpp.
References AUDError, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_filter (Factory * self, PyObject * args) [static]
Definition at line 845 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, i, NULL, and AUD_Exception::str.
static PyObject* Factory_highpass (Factory * self, PyObject * args) [static]
Definition at line 349 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_join (Factory * self, PyObject * object) [static]
Definition at line 304 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_limit (Factory * self, PyObject * args) [static]
Definition at line 391 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_loop (Factory * self, PyObject * args) [static]
Definition at line 606 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_lowpass (Factory * self, PyObject * args) [static]
Definition at line 221 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_mix (Factory * self, PyObject * object) [static]
Definition at line 647 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_new (PyTypeObject * type, PyObject * args, PyObject * kwds) [static]
Definition at line 99 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Factory_pingpong (Factory * self) [static]
Definition at line 687 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_pitch (Factory * self, PyObject * args) [static]
Definition at line 435 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_reverse (Factory * self) [static]
Definition at line 726 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_sine (PyTypeObject * type, PyObject * args) [static]
Definition at line 142 of file AUD_PyAPI.cpp.
References AUDError, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_square (Factory * self, PyObject * args) [static]
Definition at line 798 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static PyObject* Factory_volume (Factory * self, PyObject * args) [static]
Definition at line 477 of file AUD_PyAPI.cpp.
References AUDError, Factory::child_list, Factory::factory, NULL, and AUD_Exception::str.
static void Handle_dealloc (Handle * self) [static]
Definition at line 1039 of file AUD_PyAPI.cpp.
static PyObject* Handle_get_attenuation (Handle * self, void * nothing) [static]
Definition at line 1794 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getAttenuation(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_cone_angle_inner (Handle * self, void * nothing) [static]
Definition at line 1855 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getConeAngleInner(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_cone_angle_outer (Handle * self, void * nothing) [static]
Definition at line 1910 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getConeAngleOuter(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_cone_volume_outer (Handle * self, void * nothing) [static]
Definition at line 1965 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getConeVolumeOuter(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_distance_maximum (Handle * self, void * nothing) [static]
Definition at line 1738 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getDistanceMaximum(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_distance_reference (Handle * self, void * nothing) [static]
Definition at line 1682 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getDistanceReference(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_keep (Handle * self, void * nothing) [static]
Definition at line 1169 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Handle_get_location (Handle * self, void * nothing) [static]
Definition at line 1345 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getSourceLocation(), NULL, AUD_Exception::str, AUD_Vector3::x(), AUD_Vector3::y(), and AUD_Vector3::z().
static PyObject* Handle_get_loop_count (Handle * self, void * nothing) [static]
Definition at line 1306 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Handle_get_orientation (Handle * self, void * nothing) [static]
Definition at line 1457 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getSourceOrientation(), NULL, AUD_Exception::str, AUD_Quaternion::w(), AUD_Quaternion::x(), AUD_Quaternion::y(), and AUD_Quaternion::z().
static PyObject* Handle_get_pitch (Handle * self, void * nothing) [static]
Definition at line 1267 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Handle_get_position (Handle * self, void * nothing) [static]
Definition at line 1124 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Handle_get_relative (Handle * self, void * nothing) [static]
Definition at line 1513 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::isRelative(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_status (Handle * self, void * nothing) [static]
Definition at line 1211 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Handle_get_velocity (Handle * self, void * nothing) [static]
Definition at line 1401 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getSourceVelocity(), NULL, AUD_Exception::str, AUD_Vector3::x(), AUD_Vector3::y(), and AUD_Vector3::z().
static PyObject* Handle_get_volume (Handle * self, void * nothing) [static]
Definition at line 1228 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Handle_get_volume_maximum (Handle * self, void * nothing) [static]
Definition at line 1626 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getVolumeMaximum(), NULL, and AUD_Exception::str.
static PyObject* Handle_get_volume_minimum (Handle * self, void * nothing) [static]
Definition at line 1571 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::getVolumeMinimum(), NULL, and AUD_Exception::str.
static PyObject* Handle_pause (Handle * self) [static]
Definition at line 1053 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static PyObject* Handle_resume (Handle * self) [static]
Definition at line 1073 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
static int Handle_set_attenuation (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1817 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setAttenuation(), and AUD_Exception::str.
static int Handle_set_cone_angle_inner (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1878 of file AUD_PyAPI.cpp.
References angle(), AUDError, device_not_3d_error, AUD_I3DHandle::setConeAngleInner(), and AUD_Exception::str.
static int Handle_set_cone_angle_outer (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1933 of file AUD_PyAPI.cpp.
References angle(), AUDError, device_not_3d_error, AUD_I3DHandle::setConeAngleOuter(), and AUD_Exception::str.
static int Handle_set_cone_volume_outer (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1988 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setConeVolumeOuter(), and AUD_Exception::str.
static int Handle_set_distance_maximum (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1761 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, distance(), AUD_I3DHandle::setDistanceMaximum(), and AUD_Exception::str.
static int Handle_set_distance_reference (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1705 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, distance(), AUD_I3DHandle::setDistanceReference(), and AUD_Exception::str.
static int Handle_set_keep (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1183 of file AUD_PyAPI.cpp.
References AUDError, and AUD_Exception::str.
static int Handle_set_location (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1369 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setSourceLocation(), and AUD_Exception::str.
static int Handle_set_loop_count (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1320 of file AUD_PyAPI.cpp.
References AUDError, and AUD_Exception::str.
static int Handle_set_orientation (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1481 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setSourceOrientation(), and AUD_Exception::str.
static int Handle_set_pitch (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1281 of file AUD_PyAPI.cpp.
References AUDError, and AUD_Exception::str.
static int Handle_set_position (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1138 of file AUD_PyAPI.cpp.
References AUDError, and AUD_Exception::str.
static int Handle_set_relative (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1536 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setRelative(), and AUD_Exception::str.
static int Handle_set_velocity (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1425 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setSourceVelocity(), and AUD_Exception::str.
static int Handle_set_volume (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1242 of file AUD_PyAPI.cpp.
References AUDError, and AUD_Exception::str.
static int Handle_set_volume_maximum (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1649 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setVolumeMaximum(), and AUD_Exception::str.
static int Handle_set_volume_minimum (Handle * self, PyObject * args, void * nothing) [static]
Definition at line 1594 of file AUD_PyAPI.cpp.
References AUDError, device_not_3d_error, AUD_I3DHandle::setVolumeMinimum(), and AUD_Exception::str.
static PyObject* Handle_stop (Handle * self) [static]
Definition at line 1094 of file AUD_PyAPI.cpp.
References AUDError, NULL, and AUD_Exception::str.
PyDoc_STRVAR (M_aud_Device_distance_model_doc , "The distance model of the device.\n\n"".. seealso:: http://connect.creativelabs.com/openal/Documentation/OpenAL%201.1%20Specification.htm#_Toc199835864")
PyDoc_STRVAR (M_aud_Handle_velocity_doc , "The source's velocity in 3D space, a 3D tuple of floats.")
PyDoc_STRVAR (M_aud_Handle_stop_doc , "stop()\n\n""Stops playback.\n\n"":return: Whether the action succeeded.\n"":rtype: bool\n\n"".. note:: This makes the handle invalid.")
PyDoc_STRVAR (M_aud_Factory_reverse_doc , "reverse()\n\n""Plays a factory reversed.\n\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: The factory has to have a finite length and has to be ""seekable. It's recommended to use this only with factories with ""fast and accurate seeking, which is not true for encoded audio"" files, such ones should be buffered using:meth:`buffer`before""being played reversed.\n\n""..warning::If seeking is not accurate in the underlying factory""you'll likely hear skips/jumps/cracks.")
PyDoc_STRVAR (M_aud_Device_rate_doc , "The sampling rate of the device in Hz.")
PyDoc_STRVAR (M_aud_Handle_volume_doc , "The volume of the sound.")
PyDoc_STRVAR (M_aud_Handle_loop_count_doc , "The (remaining) loop count of the sound. A negative value indicates infinity.")
PyDoc_STRVAR (M_aud_Factory_limit_doc , "limit(start, end)\n\n""Limits a factory within a specific start and end time.\n\n"":arg start: Start time in seconds.\n"":type start: float\n"":arg end: End time in seconds.\n"":type end: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
PyDoc_STRVAR (M_aud_Device_listener_location_doc , "The listeners's location in 3D space, a 3D tuple of floats.")
PyDoc_STRVAR (M_aud_Factory_pitch_doc , "pitch(factor)\n\n""Changes the pitch of a factory with a specific factor.\n\n"":arg factor: The factor to change the pitch with.\n"":type factor: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: This is done by changing the sample rate of the ""underlying factory, which has to be an integer, so the factor""value rounded and the factor may not be 100%accurate.\n\n""..note::This is a filter function, you might consider using"":attr:`Handle.pitch`instead.")
PyDoc_STRVAR (M_aud_Handle_cone_angle_inner_doc , "The opening angle of the inner cone of the source. If the cone ""values of a source are set there are two (audible) cones with ""the apex at the :attr:`location` of the source and with infinite "" height, heading in the direction of the source's"":attr:`orientation`.\n""In the inner cone the volume is normal.Outside the outer cone""the volume will be:attr:`cone_volume_outer`and in the area""between the volume will be interpolated linearly.")
PyDoc_STRVAR (M_aud_Factory_loop_doc , "loop(count)\n\n""Loops a factory.\n\n"":arg count: How often the factory should be looped. ""Negative values mean endlessly.\n"":type count: integer\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: This is a filter function, you might consider using"":attr:`Handle.loop_count`instead.")
PyDoc_STRVAR (M_aud_Device_listener_orientation_doc , "The listener's orientation in 3D space as quaternion, a 4 float tuple.")
PyDoc_STRVAR (M_aud_Handle_volume_maximum_doc , "The maximum volume of the source.\n\n"".. seealso:: :attr:`Device.distance_model`")
PyDoc_STRVAR (M_aud_Handle_cone_volume_outer_doc , "The volume outside the outer cone of the source.\n\n"".. seealso:: :attr:`cone_angle_inner`")
PyDoc_STRVAR (M_aud_Handle_pitch_doc , "The pitch of the sound.")
PyDoc_STRVAR (M_aud_Factory_volume_doc , "volume(volume)\n\n""Changes the volume of a factory.\n\n"":arg volume: The new volume..\n"":type volume: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: Should be in the range to avoid clipping.\n\n"".. note:: This is a filter function[0, 1], you might consider using"":attr:`Handle.volume`instead.")
PyDoc_STRVAR (M_aud_Handle_pause_doc , "pause()\n\n""Pauses playback.\n\n"":return: Whether the action succeeded.\n"":rtype: bool")
PyDoc_STRVAR (M_aud_Device_unlock_doc , "unlock()\n\n""Unlocks the device after a lock call, see:meth:`lock`for""details.")
PyDoc_STRVAR (M_aud_Handle_position_doc , "The playback position of the sound in seconds.")
PyDoc_STRVAR (M_aud_Factory_fadeout_doc , "fadeout(start, length)\n\n""Fades a factory in by lowering the volume linearly in the given ""time interval.\n\n"":arg start: Time in seconds when the fading should start.\n"":type start: float\n"":arg length: Time in seconds how long the fading should last.\n"":type length: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: After the fade this factory plays silence, so that""the length of the factory is not altered.")
PyDoc_STRVAR (M_aud_Device_volume_doc , "The overall volume of the device.")
PyDoc_STRVAR (M_aud_Handle_distance_maximum_doc , "The maximum distance of the source.\n""If the listener is further away the source volume will be 0.\n\n"".. seealso:: :attr:`Device.distance_model`")
PyDoc_STRVAR (M_aud_Device_speed_of_sound_doc , "The speed of sound of the device.\n""The speed of sound in air is typically 343 m/s.")
PyDoc_STRVAR (M_aud_Device_channels_doc , "The channel count of the device.")
PyDoc_STRVAR (M_aud_Handle_keep_doc , "Whether the sound should be kept paused in the device when its ""end is reached.\n""This can be used to seek the sound to some position and start ""playback again.\n\n"".. warning:: If this is set to true and you forget stopping this ""equals a memory leak as the handle exists until the device is ""destroyed.")
PyDoc_STRVAR (M_aud_Factory_lowpass_doc)
PyDoc_STRVAR (M_aud_Device_doppler_factor_doc , "The doppler factor of the device.\n""This factor is a scaling factor for the velocity vectors in ""doppler calculation. So a value bigger than 1 will exaggerate ""the effect as it raises the velocity.")
PyDoc_STRVAR (M_aud_Handle_status_doc , "Whether the sound is playing, paused or stopped(=invalid).")
PyDoc_STRVAR (M_aud_Factory_fadein_doc , "fadein(start, length)\n\n""Fades a factory in by raising the volume linearly in the given ""time interval.\n\n"":arg start: Time in seconds when the fading should start.\n"":type start: float\n"":arg length: Time in seconds how long the fading should last.\n"":type length: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: Before the fade starts it plays silence.")
PyDoc_STRVAR (M_aud_Device_format_doc , "The native sample format of the device.")
PyDoc_STRVAR (M_aud_Factory_join_doc , "join(factory)\n\n""Plays two factories in sequence.\n\n"":arg factory: The factory to play second.\n"":type factory: :class:`Factory`\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: The two factories have to have the same specifications ""(channels and samplerate).")
PyDoc_STRVAR (M_aud_Handle_cone_angle_outer_doc , "The opening angle of the outer cone of the source.\n\n"".. seealso:: :attr:`cone_angle_inner`")
PyDoc_STRVAR (M_aud_Handle_doc , "Handle objects are playback handles that can be used to control ""playback of a sound. If a sound is played back multiple times ""then there are as many handles.")
PyDoc_STRVAR (M_aud_Factory_highpass_doc)
PyDoc_STRVAR (M_aud_Handle_resume_doc , "resume()\n\n""Resumes playback.\n\n"":return: Whether the action succeeded.\n"":rtype: bool")
PyDoc_STRVAR (M_aud_Factory_doc , "Factory objects are immutable and represent a sound that can be ""played simultaneously multiple times. They are called factories ""because they create reader objects internally that are used for ""playback.")
PyDoc_STRVAR (M_aud_Factory_file_doc , "file(filename)\n\n""Creates a factory object of a sound file.\n\n"":arg filename: Path of the file.\n"":type filename: string\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. warning:: If the file doesn't exist or can't be read you will ""not get an exception immediately, but when you try to start""playback of that factory.")
PyDoc_STRVAR (M_aud_Device_listener_velocity_doc , "The listener's velocity in 3D space, a 3D tuple of floats.")
PyDoc_STRVAR (M_aud_Handle_volume_minimum_doc , "The minimum volume of the source.\n\n"".. seealso:: :attr:`Device.distance_model`")
PyDoc_STRVAR (M_aud_doc , "This module provides access to the audaspace audio library.")
PyDoc_STRVAR (M_aud_Device_play_doc , "play(factory, keep=False)\n\n""Plays a factory.\n\n"":arg factory: The factory to play.\n"":type factory: :class:`Factory`\n"":arg keep: See :attr:`Handle.keep`.\n"":type keep: bool\n"":return: The playback handle with which playback can be ""controlled with.\n"":rtype: :class:`Handle`")
PyDoc_STRVAR (M_aud_Factory_sine_doc , "sine(frequency, rate=44100)\n\n""Creates a sine factory which plays a sine wave.\n\n"":arg frequency: The frequency of the sine wave in Hz.\n"":type frequency: float\n"":arg rate: The sampling rate in Hz. It's recommended to set this ""value to the playback device's samling rate to avoid resamping.\n"":type rate: int\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
PyDoc_STRVAR (M_aud_Handle_location_doc , "The source's location in 3D space, a 3D tuple of floats.")
PyDoc_STRVAR (M_aud_Factory_square_doc , "square(threshold = 0)\n\n""Makes a square wave out of an audio wave by setting all samples ""with a amplitude >= threshold to 1, all<=-threshold to-1 and""all between to 0.\n\n"":arg threshold:Threshold value over which an amplitude counts""non-zero.\n"":type threshold:float\n"":return:The created:class:`Factory`object.\n"":rtype::class:`Factory`")
PyDoc_STRVAR (M_aud_Device_stopAll_doc , "stopAll()\n\n""Stops all playing and paused sounds.")
PyDoc_STRVAR (M_aud_Device_lock_doc , "lock()\n\n""Locks the device so that it's guaranteed, that no samples are""read from the streams until:meth:`unlock`is called.\n""This is useful if you want to do start/stop/pause/resume some""sounds at the same time.\n\n""..note::The device has to be unlocked as often as locked to be""able to continue playback.\n\n""..warning::Make sure the time between locking and unlocking is""as short as possible to avoid clicks.")
PyDoc_STRVAR (M_aud_Handle_distance_reference_doc , "The reference distance of the source.\n""At this distance the volume will be exactly :attr:`volume`.\n\n"".. seealso:: :attr:`Device.distance_model`")
PyDoc_STRVAR (M_aud_Handle_relative_doc , "Whether the source's location, velocity and orientation is relative or absolute to the listener.")
PyDoc_STRVAR (M_aud_Device_doc , "Device objects represent an audio output backend like OpenAL or "" SDL, but might also represent a file output or RAM buffer""output.")
PyDoc_STRVAR (M_aud_Factory_delay_doc , "delay(time)\n\n""Delays by playing adding silence in front of the other factory's ""data.\n\n"":arg time: How many seconds of silence should be added before ""the factory.\n"":type time: float\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
PyDoc_STRVAR (M_aud_Handle_attenuation_doc , "This factor is used for distance based attenuation of the ""source.\n\n"".. seealso:: :attr:`Device.distance_model`")
PyDoc_STRVAR (M_aud_Factory_buffer_doc , "buffer()\n\n""Buffers a factory into RAM.\n""This saves CPU usage needed for decoding and file access if the ""underlying factory reads from a file on the harddisk, but it""consumes a lot of memory.\n\n"":return:The created:class:`Factory`object.\n"":rtype::class:`Factory`\n\n""..note::Only known-length factories can be buffered.\n\n""..warning::Raw PCM data needs a lot of space, only buffer""short factories.")
PyDoc_STRVAR (M_aud_Factory_filter_doc , "filter(b, a = (1))\n\n""Filters a factory with the supplied IIR filter coefficients.\n""Without the second parameter you'll get a FIR filter.\n""If the first value of the a sequence is 0 it will be set to 1 ""automatically.\n""If the first value of the a sequence is neither 0 nor 1, all""filter coefficients will be scaled by this value so that it is 1""in the end, you don't have to scale yourself.\n\n"":arg b:The nominator filter coefficients.\n"":type b:sequence of float\n"":arg a:The denominator filter coefficients.\n"":type a:sequence of float\n"":return:The created:class:`Factory`object.\n"":rtype::class:`Factory`")
PyDoc_STRVAR (M_aud_Handle_orientation_doc , "The source's orientation in 3D space as quaternion, a 4 float tuple.")
PyDoc_STRVAR (M_aud_Factory_pingpong_doc , "pingpong()\n\n""Plays a factory forward and then backward.\n""This is like joining a factory with its reverse.\n\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`")
PyDoc_STRVAR (M_aud_Factory_mix_doc , "mix(factory)\n\n""Mixes two factories.\n\n"":arg factory: The factory to mix over the other.\n"":type factory: :class:`Factory`\n"":return: The created :class:`Factory` object.\n"":rtype: :class:`Factory`\n\n"".. note:: The two factories have to have the same specifications ""(channels and samplerate).")
PyMODINIT_FUNC PyInit_aud (void)
Definition at line 2863 of file AUD_PyAPI.cpp.
References AUD_DEVICE_JACK, AUD_DEVICE_NULL, AUD_DEVICE_OPENAL, AUD_DEVICE_SDL, AUD_DISTANCE_MODEL_EXPONENT, AUD_DISTANCE_MODEL_EXPONENT_CLAMPED, AUD_DISTANCE_MODEL_INVALID, AUD_DISTANCE_MODEL_INVERSE, AUD_DISTANCE_MODEL_INVERSE_CLAMPED, AUD_DISTANCE_MODEL_LINEAR, AUD_DISTANCE_MODEL_LINEAR_CLAMPED, AUD_FORMAT_FLOAT32, AUD_FORMAT_FLOAT64, AUD_FORMAT_INVALID, AUD_FORMAT_S16, AUD_FORMAT_S24, AUD_FORMAT_S32, AUD_FORMAT_U8, AUD_STATUS_INVALID, AUD_STATUS_PAUSED, AUD_STATUS_PLAYING, AUDError, NULL, and PY_MODULE_ADD_CONSTANT.
Variable Documentation
PyObject* AUDError [static]
Definition at line 83 of file AUD_PyAPI.cpp.
Referenced by Device_get_channels(), Device_get_distance_model(), Device_get_doppler_factor(), Device_get_format(), Device_get_listener_location(), Device_get_listener_orientation(), Device_get_listener_velocity(), Device_get_rate(), Device_get_speed_of_sound(), Device_get_volume(), Device_lock(), Device_new(), Device_play(), Device_set_distance_model(), Device_set_doppler_factor(), Device_set_listener_location(), Device_set_listener_orientation(), Device_set_listener_velocity(), Device_set_speed_of_sound(), Device_set_volume(), Device_stopAll(), Device_unlock(), Factory_buffer(), Factory_delay(), Factory_fadein(), Factory_fadeout(), Factory_file(), Factory_filter(), Factory_highpass(), Factory_join(), Factory_limit(), Factory_loop(), Factory_lowpass(), Factory_mix(), Factory_new(), Factory_pingpong(), Factory_pitch(), Factory_reverse(), Factory_sine(), Factory_square(), Factory_volume(), Handle_get_attenuation(), Handle_get_cone_angle_inner(), Handle_get_cone_angle_outer(), Handle_get_cone_volume_outer(), Handle_get_distance_maximum(), Handle_get_distance_reference(), Handle_get_keep(), Handle_get_location(), Handle_get_loop_count(), Handle_get_orientation(), Handle_get_pitch(), Handle_get_position(), Handle_get_relative(), Handle_get_status(), Handle_get_velocity(), Handle_get_volume(), Handle_get_volume_maximum(), Handle_get_volume_minimum(), Handle_pause(), Handle_resume(), Handle_set_attenuation(), Handle_set_cone_angle_inner(), Handle_set_cone_angle_outer(), Handle_set_cone_volume_outer(), Handle_set_distance_maximum(), Handle_set_distance_reference(), Handle_set_keep(), Handle_set_location(), Handle_set_loop_count(), Handle_set_orientation(), Handle_set_pitch(), Handle_set_position(), Handle_set_relative(), Handle_set_velocity(), Handle_set_volume(), Handle_set_volume_maximum(), Handle_set_volume_minimum(), Handle_stop(), and PyInit_aud().
struct PyModuleDef audmodule [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "aud",
    M_aud_doc,
    -1,
   NULL, NULL, NULL, NULL, NULL
}
Definition at line 2853 of file AUD_PyAPI.cpp.
PyMethodDef Device_methods[] [static]
Initial value:
 {
    {"play", (PyCFunction)Device_play, METH_VARARGS | METH_KEYWORDS,
     M_aud_Device_play_doc
    },
    {"stopAll", (PyCFunction)Device_stopAll, METH_NOARGS,
     M_aud_Device_stopAll_doc
    },
    {"lock", (PyCFunction)Device_lock, METH_NOARGS,
     M_aud_Device_lock_doc
    },
    {"unlock", (PyCFunction)Device_unlock, METH_NOARGS,
     M_aud_Device_unlock_doc
    },
    {NULL}
}
Definition at line 2317 of file AUD_PyAPI.cpp.
const char* device_not_3d_error = "Device is not a 3D device!" [static]
Definition at line 85 of file AUD_PyAPI.cpp.
Referenced by Device_get_distance_model(), Device_get_doppler_factor(), Device_get_listener_location(), Device_get_listener_orientation(), Device_get_listener_velocity(), Device_get_speed_of_sound(), Device_set_distance_model(), Device_set_doppler_factor(), Device_set_listener_location(), Device_set_listener_orientation(), Device_set_listener_velocity(), Device_set_speed_of_sound(), Handle_get_attenuation(), Handle_get_cone_angle_inner(), Handle_get_cone_angle_outer(), Handle_get_cone_volume_outer(), Handle_get_distance_maximum(), Handle_get_distance_reference(), Handle_get_location(), Handle_get_orientation(), Handle_get_relative(), Handle_get_velocity(), Handle_get_volume_maximum(), Handle_get_volume_minimum(), Handle_set_attenuation(), Handle_set_cone_angle_inner(), Handle_set_cone_angle_outer(), Handle_set_cone_volume_outer(), Handle_set_distance_maximum(), Handle_set_distance_reference(), Handle_set_location(), Handle_set_orientation(), Handle_set_relative(), Handle_set_velocity(), Handle_set_volume_maximum(), and Handle_set_volume_minimum().
PyGetSetDef Device_properties[] [static]
Initial value:
 {
    {(char*)"rate", (getter)Device_get_rate, NULL,
     M_aud_Device_rate_doc, NULL },
    {(char*)"format", (getter)Device_get_format, NULL,
     M_aud_Device_format_doc, NULL },
    {(char*)"channels", (getter)Device_get_channels, NULL,
     M_aud_Device_channels_doc, NULL },
    {(char*)"volume", (getter)Device_get_volume, (setter)Device_set_volume,
     M_aud_Device_volume_doc, NULL },
    {(char*)"listener_location", (getter)Device_get_listener_location, (setter)Device_set_listener_location,
     M_aud_Device_listener_location_doc, NULL },
    {(char*)"listener_velocity", (getter)Device_get_listener_velocity, (setter)Device_set_listener_velocity,
     M_aud_Device_listener_velocity_doc, NULL },
    {(char*)"listener_orientation", (getter)Device_get_listener_orientation, (setter)Device_set_listener_orientation,
     M_aud_Device_listener_orientation_doc, NULL },
    {(char*)"speed_of_sound", (getter)Device_get_speed_of_sound, (setter)Device_set_speed_of_sound,
     M_aud_Device_speed_of_sound_doc, NULL },
    {(char*)"doppler_factor", (getter)Device_get_doppler_factor, (setter)Device_set_doppler_factor,
     M_aud_Device_doppler_factor_doc, NULL },
    {(char*)"distance_model", (getter)Device_get_distance_model, (setter)Device_set_distance_model,
     M_aud_Device_distance_model_doc, NULL },
    {NULL}
}
Definition at line 2753 of file AUD_PyAPI.cpp.
PyTypeObject DeviceType [static]
Definition at line 2782 of file AUD_PyAPI.cpp.
PyMethodDef Factory_methods[] [static]
Definition at line 931 of file AUD_PyAPI.cpp.
PyTypeObject FactoryType [static]
Definition at line 995 of file AUD_PyAPI.cpp.
PyMethodDef Handle_methods[] [static]
Initial value:
 {
    {"pause", (PyCFunction)Handle_pause, METH_NOARGS,
     M_aud_Handle_pause_doc
    },
    {"resume", (PyCFunction)Handle_resume, METH_NOARGS,
     M_aud_Handle_resume_doc
    },
    {"stop", (PyCFunction)Handle_stop, METH_NOARGS,
     M_aud_Handle_stop_doc
    },
    {NULL}
}
Definition at line 1107 of file AUD_PyAPI.cpp.
PyGetSetDef Handle_properties[] [static]
Definition at line 2015 of file AUD_PyAPI.cpp.
PyTypeObject HandleType [static]
Definition at line 2060 of file AUD_PyAPI.cpp.