Blender: npunix.c File Reference
npunix.c File Reference
#include <stdio.h>
#include "npapi.h"
#include "npupp.h"
Defines
#define PLUGINDEBUGSTR(msg)
Functions
void NPN_Version (int *plugin_major, int *plugin_minor, int *netscape_major, int *netscape_minor)
NPError NPN_GetValue (NPP instance, NPNVariable variable, void *r_value)
NPError NPN_GetURL (NPP instance, const char *url, const char *window)
NPError NPN_PostURL (NPP instance, const char *url, const char *window, uint32 len, const char *buf, NPBool file)
NPError NPN_RequestRead (NPStream *stream, NPByteRange *rangeList)
NPError NPN_NewStream (NPP instance, NPMIMEType type, const char *window, NPStream **stream_ptr)
int32 NPN_Write (NPP instance, NPStream *stream, int32 len, void *buffer)
NPError NPN_DestroyStream (NPP instance, NPStream *stream, NPError reason)
void NPN_Status (NPP instance, const char *message)
const char * NPN_UserAgent (NPP instance)
void * NPN_MemAlloc (uint32 size)
void NPN_MemFree (void *ptr)
uint32 NPN_MemFlush (uint32 size)
void NPN_ReloadPlugins (NPBool reloadPages)
JRIEnv * NPN_GetJavaEnv ()
jref NPN_GetJavaPeer (NPP instance)
void NPN_ForceRedraw (NPP instance)
void NPN_InvalidateRect (NPP instance, NPRect *invalidRect)
NPError Private_New (NPMIMEType pluginType, NPP instance, uint16 mode, int16 argc, char *argn[], char *argv[], NPSavedData *saved)
NPError Private_Destroy (NPP instance, NPSavedData **save)
NPError Private_SetWindow (NPP instance, NPWindow *window)
NPError Private_NewStream (NPP instance, NPMIMEType type, NPStream *stream, NPBool seekable, uint16 *stype)
int32 Private_WriteReady (NPP instance, NPStream *stream)
int32 Private_Write (NPP instance, NPStream *stream, int32 offset, int32 len, void *buffer)
void Private_StreamAsFile (NPP instance, NPStream *stream, const char *fname)
NPError Private_DestroyStream (NPP instance, NPStream *stream, NPError reason)
void Private_Print (NPP instance, NPPrint *platformPrint)
char * NP_GetMIMEDescription (void)
NPError NP_GetValue (void *future, NPPVariable variable, void *value)
NPError NP_Initialize (NPNetscapeFuncs *nsTable, NPPluginFuncs *pluginFuncs)
NPError NP_Shutdown (void)
Variables
static NPNetscapeFuncs gNetscapeFuncs
Define Documentation
#define PLUGINDEBUGSTR (msg)
Adapted to new API. Used by the Blender Web Plugin
Definition at line 33 of file npunix.c.
Referenced by NP_Initialize(), NP_Shutdown(), Private_Destroy(), Private_DestroyStream(), Private_New(), Private_NewStream(), Private_Print(), Private_SetWindow(), Private_StreamAsFile(), Private_Write(), and Private_WriteReady().
Function Documentation
char* NP_GetMIMEDescription (void)
Definition at line 292 of file npunix.c.
References NPP_GetMIMEDescription().
NPError NP_GetValue (void * future, NPPVariable variable, void * value)
Definition at line 304 of file npunix.c.
References NPP_GetValue().
NPError NP_Initialize (NPNetscapeFuncs * nsTable, NPPluginFuncs * pluginFuncs)
Definition at line 327 of file npunix.c.
References err, gNetscapeFuncs, NPP_Initialize(), NULL, PLUGINDEBUGSTR, Private_Destroy(), Private_DestroyStream(), Private_New(), Private_NewStream(), Private_Print(), Private_SetWindow(), Private_StreamAsFile(), Private_Write(), and Private_WriteReady().
NPError NP_Shutdown (void)
Definition at line 447 of file npunix.c.
References NPP_Shutdown(), and PLUGINDEBUGSTR.
NPError NPN_DestroyStream (NPP instance, NPStream * stream, NPError reason)
Definition at line 122 of file npunix.c.
References gNetscapeFuncs.
void NPN_ForceRedraw (NPP instance)
Definition at line 173 of file npunix.c.
References gNetscapeFuncs.
JRIEnv* NPN_GetJavaEnv ()
Definition at line 161 of file npunix.c.
References gNetscapeFuncs.
jref NPN_GetJavaPeer (NPP instance)
Definition at line 166 of file npunix.c.
References gNetscapeFuncs.
NPError NPN_GetURL (NPP instance, const char * url, const char * window)
Definition at line 77 of file npunix.c.
References gNetscapeFuncs.
NPError NPN_GetValue (NPP instance, NPNVariable variable, void * r_value)
Definition at line 70 of file npunix.c.
References gNetscapeFuncs.
void NPN_InvalidateRect (NPP instance, NPRect * invalidRect)
Definition at line 180 of file npunix.c.
References gNetscapeFuncs.
void* NPN_MemAlloc (uint32 size)
Definition at line 141 of file npunix.c.
References gNetscapeFuncs.
Referenced by execute_blenderplayer(), NPP_New(), and NPP_NewStream().
uint32 NPN_MemFlush (uint32 size)
Definition at line 151 of file npunix.c.
References gNetscapeFuncs.
void NPN_MemFree (void * ptr)
Definition at line 146 of file npunix.c.
References gNetscapeFuncs.
Referenced by NPP_Destroy().
NPError NPN_NewStream (NPP instance, NPMIMEType type, const char * window, NPStream ** stream_ptr)
Definition at line 107 of file npunix.c.
References gNetscapeFuncs.
NPError NPN_PostURL (NPP instance, const char * url, const char * window, uint32 len, const char * buf, NPBool file)
Definition at line 92 of file npunix.c.
References gNetscapeFuncs.
void NPN_ReloadPlugins (NPBool reloadPages)
Definition at line 156 of file npunix.c.
References gNetscapeFuncs.
NPError NPN_RequestRead (NPStream * stream, NPByteRange * rangeList)
Definition at line 100 of file npunix.c.
References gNetscapeFuncs.
void NPN_Status (NPP instance, const char * message)
Definition at line 129 of file npunix.c.
References gNetscapeFuncs.
Referenced by NPP_DestroyStream().
const char* NPN_UserAgent (NPP instance)
Definition at line 135 of file npunix.c.
References gNetscapeFuncs.
void NPN_Version (int * plugin_major, int * plugin_minor, int * netscape_major, int * netscape_minor)
Definition at line 57 of file npunix.c.
References gNetscapeFuncs.
int32 NPN_Write (NPP instance, NPStream * stream, int32 len, void * buffer)
Definition at line 115 of file npunix.c.
References gNetscapeFuncs.
NPError Private_Destroy (NPP instance, NPSavedData ** save)
Definition at line 210 of file npunix.c.
References NPP_Destroy(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
NPError Private_DestroyStream (NPP instance, NPStream * stream, NPError reason)
Definition at line 263 of file npunix.c.
References err, NPP_DestroyStream(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
NPError Private_New (NPMIMEType pluginType, NPP instance, uint16 mode, int16 argc, char * argn[], char * argv[], NPSavedData * saved)
Definition at line 200 of file npunix.c.
References NPP_New(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
NPError Private_NewStream (NPP instance, NPMIMEType type, NPStream * stream, NPBool seekable, uint16 * stype)
Definition at line 226 of file npunix.c.
References err, NPP_NewStream(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
void Private_Print (NPP instance, NPPrint * platformPrint)
Definition at line 273 of file npunix.c.
References NPP_Print(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
NPError Private_SetWindow (NPP instance, NPWindow * window)
Definition at line 217 of file npunix.c.
References err, NPP_SetWindow(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
void Private_StreamAsFile (NPP instance, NPStream * stream, const char * fname)
Definition at line 255 of file npunix.c.
References NPP_StreamAsFile(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
int32 Private_Write (NPP instance, NPStream * stream, int32 offset, int32 len, void * buffer)
Definition at line 245 of file npunix.c.
References NPP_Write(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
int32 Private_WriteReady (NPP instance, NPStream * stream)
Definition at line 236 of file npunix.c.
References NPP_WriteReady(), and PLUGINDEBUGSTR.
Referenced by NP_Initialize().
Variable Documentation
NPNetscapeFuncs gNetscapeFuncs [static]
Definition at line 43 of file npunix.c.
Referenced by NP_Initialize(), NPN_DestroyStream(), NPN_ForceRedraw(), NPN_GetJavaEnv(), NPN_GetJavaPeer(), NPN_GetURL(), NPN_GetValue(), NPN_InvalidateRect(), NPN_MemAlloc(), NPN_MemFlush(), NPN_MemFree(), NPN_NewStream(), NPN_PostURL(), NPN_ReloadPlugins(), NPN_RequestRead(), NPN_Status(), NPN_UserAgent(), NPN_Version(), and NPN_Write().