Blender: render_view.c File Reference
render_view.c File Reference
render
#include <string.h>
#include <stddef.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_scene_types.h"
#include "BKE_blender.h"
#include "BKE_context.h"
#include "BKE_image.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_report.h"
#include "BKE_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "wm_window.h"
#include "render_intern.h"
Functions
static ScrArea * biggest_non_image_area (bContext *C)
static ScrArea * find_area_showing_r_result (bContext *C, wmWindow **win)
static ScrArea * find_area_image_empty (bContext *C)
void render_view_open (bContext *C, int mx, int my)
static int render_view_cancel_exec (bContext *C, wmOperator *UNUSED(op))
void RENDER_OT_view_cancel (struct wmOperatorType *ot)
static int render_view_show_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
void RENDER_OT_view_show (struct wmOperatorType *ot)
Detailed Description
Definition in file render_view.c.
Function Documentation
static ScrArea* biggest_non_image_area (bContext * C) [static]
Definition at line 62 of file render_view.c.
References bScreen::areabase, CTX_wm_screen(), ListBase::first, ScrArea::next, NULL, size(), SPACE_BUTS, SPACE_IMAGE, ScrArea::spacetype, ScrArea::winx, and ScrArea::winy.
Referenced by render_view_open().
static ScrArea* find_area_image_empty (bContext * C) [static]
Definition at line 111 of file render_view.c.
References bScreen::areabase, CTX_wm_screen(), ListBase::first, SpaceImage::image, ScrArea::next, SPACE_IMAGE, ScrArea::spacedata, and ScrArea::spacetype.
Referenced by render_view_open().
static ScrArea* find_area_showing_r_result (bContext * C, wmWindow ** win) [static]
Definition at line 89 of file render_view.c.
References CTX_wm_manager(), ListBase::first, IMA_TYPE_R_RESULT, SpaceImage::image, ScrArea::next, wmWindow::next, NULL, SPACE_IMAGE, ScrArea::spacedata, ScrArea::spacetype, Image::type, and wmWindowManager::windows.
Referenced by render_view_open(), and render_view_show_invoke().
void RENDER_OT_view_cancel (struct wmOperatorType * ot)
Definition at line 263 of file render_view.c.
References wmOperatorType::description, ED_operator_image_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and render_view_cancel_exec().
Referenced by ED_operatortypes_render().
void RENDER_OT_view_show (struct wmOperatorType * ot)
Definition at line 330 of file render_view.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and render_view_show_invoke().
Referenced by ED_operatortypes_render().
static int render_view_cancel_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 230 of file render_view.c.
References CTX_wm_area(), CTX_wm_window(), ED_area_prevspace(), ED_screen_full_prevspace(), ED_screen_full_toggle(), ListBase::first, SpaceImage::flag, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, SI_FULLWINDOW, SI_PREVSPACE, ScrArea::spacedata, and wm_window_lower().
Referenced by RENDER_OT_view_cancel().
void render_view_open (bContext * C, int mx, int my)
Definition at line 132 of file render_view.c.
References biggest_non_image_area(), BKE_image_verify_viewer(), BKE_screen_find_big_area(), CTX_data_scene(), CTX_wm_area(), CTX_wm_screen(), CTX_wm_window(), RenderData::displaymode, ED_area_newspace(), ED_screen_full_newspace(), find_area_image_empty(), find_area_showing_r_result(), ListBase::first, SpaceImage::flag, ScrArea::full, IMA_TYPE_R_RESULT, SpaceImage::image, NULL, wmWindow::posx, wmWindow::posy, Scene::r, R_OUTPUT_NONE, R_OUTPUT_SCREEN, R_OUTPUT_WINDOW, SI_FULLWINDOW, SI_PREVSPACE, RenderData::size, SPACE_IMAGE, ScrArea::spacedata, ScrArea::spacetype, WM_window_open_temp(), wm_window_raise(), WM_WINDOW_RENDER, rcti::xmax, rcti::xmin, RenderData::xsch, rcti::ymax, rcti::ymin, and RenderData::ysch.
Referenced by render_view_show_invoke(), screen_opengl_render_invoke(), and screen_render_invoke().
static int render_view_show_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 277 of file render_view.c.
References CTX_wm_manager(), CTX_wm_window(), ED_area_newspace(), ED_area_tag_redraw(), ED_screen_full_prevspace(), find_area_showing_r_result(), ListBase::first, SpaceImage::flag, G, SpaceLink::next, SpaceImage::next, wmWindow::next, OPERATOR_FINISHED, render_view_open(), wmWindow::screen, SI_FULLWINDOW, SI_PREVSPACE, SPACE_FILE, ScrArea::spacedata, SpaceLink::spacetype, bScreen::temp, wm_window_lower(), wm_window_raise(), wmEvent::x, and wmEvent::y.
Referenced by RENDER_OT_view_show().