Blender: btCompoundLeafCallback Struct Reference
btCompoundLeafCallback Struct Reference
Public Member Functions
btCompoundLeafCallback (btCollisionObject *compoundObj, btCollisionObject *otherObj, btDispatcher *dispatcher, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut, btCollisionAlgorithm **childCollisionAlgorithms, btPersistentManifold *sharedManifold)
void ProcessChildShape (btCollisionShape *childShape, int index)
void Process (const btDbvtNode *leaf)
Public Attributes
btCollisionObject * m_compoundColObj
btCollisionObject * m_otherObj
btDispatcher * m_dispatcher
const btDispatcherInfo & m_dispatchInfo
btManifoldResult * m_resultOut
btCollisionAlgorithm ** m_childCollisionAlgorithms
btPersistentManifold * m_sharedManifold
Detailed Description
Definition at line 90 of file btCompoundCollisionAlgorithm.cpp.
Constructor & Destructor Documentation
btCompoundLeafCallback::btCompoundLeafCallback (btCollisionObject * compoundObj, btCollisionObject * otherObj, btDispatcher * dispatcher, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut, btCollisionAlgorithm ** childCollisionAlgorithms, btPersistentManifold * sharedManifold) [inline]
Definition at line 106 of file btCompoundCollisionAlgorithm.cpp.
Member Function Documentation
void btCompoundLeafCallback::Process (const btDbvtNode * leaf) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 169 of file btCompoundCollisionAlgorithm.cpp.
References btTransformAabb(), btDbvtNode::dataAsInt, btIDebugDraw::DBG_DrawAabb, btIDebugDraw::drawAabb(), btIDebugDraw::getDebugMode(), m_compoundColObj, btDispatcherInfo::m_debugDraw, m_dispatchInfo, btDbvtAabbMm::Maxs(), btDbvtAabbMm::Mins(), ProcessChildShape(), and btDbvtNode::volume.
void btCompoundLeafCallback::ProcessChildShape (btCollisionShape * childShape, int index) [inline]
detect swapping case
Definition at line 115 of file btCompoundCollisionAlgorithm.cpp.
References btAssert, btIDebugDraw::DBG_DrawAabb, btIDebugDraw::drawAabb(), btDispatcher::findAlgorithm(), btCollisionShape::getAabb(), btManifoldResult::getBody0Internal(), btIDebugDraw::getDebugMode(), m_childCollisionAlgorithms, m_compoundColObj, btDispatcherInfo::m_debugDraw, m_dispatcher, m_dispatchInfo, m_otherObj, m_resultOut, m_sharedManifold, btCollisionAlgorithm::processCollision(), btManifoldResult::setShapeIdentifiersA(), btManifoldResult::setShapeIdentifiersB(), and TestAabbAgainstAabb2().
Referenced by Process(), and btCompoundCollisionAlgorithm::processCollision().
Member Data Documentation
btCollisionAlgorithm** btCompoundLeafCallback::m_childCollisionAlgorithms
Definition at line 100 of file btCompoundCollisionAlgorithm.cpp.
Referenced by ProcessChildShape().
btCollisionObject* btCompoundLeafCallback::m_compoundColObj
Definition at line 95 of file btCompoundCollisionAlgorithm.cpp.
Referenced by Process(), and ProcessChildShape().
btDispatcher* btCompoundLeafCallback::m_dispatcher
Definition at line 97 of file btCompoundCollisionAlgorithm.cpp.
Referenced by ProcessChildShape().
const btDispatcherInfo& btCompoundLeafCallback::m_dispatchInfo
Definition at line 98 of file btCompoundCollisionAlgorithm.cpp.
Referenced by Process(), and ProcessChildShape().
btCollisionObject* btCompoundLeafCallback::m_otherObj
Definition at line 96 of file btCompoundCollisionAlgorithm.cpp.
Referenced by ProcessChildShape().
btManifoldResult* btCompoundLeafCallback::m_resultOut
Definition at line 99 of file btCompoundCollisionAlgorithm.cpp.
Referenced by ProcessChildShape().
btPersistentManifold* btCompoundLeafCallback::m_sharedManifold
Definition at line 101 of file btCompoundCollisionAlgorithm.cpp.
Referenced by ProcessChildShape().
The documentation for this struct was generated from the following file:
btCompoundCollisionAlgorithm.cpp