Blender: TNT::Stopwatch Class Reference
TNT::Stopwatch Class Reference
#include <tnt_stopwatch.h>
Public Member Functions
Stopwatch ()
void start ()
double stop ()
double read ()
void resume ()
int running ()
Detailed Description
Definition at line 39 of file tnt_stopwatch.h.
Constructor & Destructor Documentation
TNT::Stopwatch::Stopwatch () [inline]
Definition at line 54 of file tnt_stopwatch.h.
Member Function Documentation
double TNT::Stopwatch::read () [inline]
Definition at line 83 of file tnt_stopwatch.h.
References resume(), and stop().
void TNT::Stopwatch::resume () [inline]
Definition at line 73 of file tnt_stopwatch.h.
References TNT::seconds().
Referenced by read().
int TNT::Stopwatch::running () [inline]
void TNT::Stopwatch::start () [inline]
Definition at line 56 of file tnt_stopwatch.h.
References TNT::seconds().
double TNT::Stopwatch::stop (void) [inline]
Definition at line 63 of file tnt_stopwatch.h.
References TNT::seconds().
Referenced by read().
The documentation for this class was generated from the following file:
tnt_stopwatch.h