Blender: wm_subwindow.h File Reference
wm_subwindow.h File Reference
windowmanager
Defines
#define WM_MAXSUBWIN 256
Functions
void wm_subwindows_free (wmWindow *win)
int wm_subwindow_open (wmWindow *win, rcti *winrct)
void wm_subwindow_close (wmWindow *win, int swinid)
int wm_subwindow_get (wmWindow *win)
void wm_subwindow_position (wmWindow *win, int swinid, rcti *winrct)
void wm_subwindow_getsize (wmWindow *win, int swinid, int *x, int *y)
void wm_subwindow_getorigin (wmWindow *win, int swinid, int *x, int *y)
void wm_subwindow_getmatrix (wmWindow *win, int swinid, float mat[][4])
unsigned int index_to_framebuffer (int index)
Detailed Description
Definition in file wm_subwindow.h.
Define Documentation
#define WM_MAXSUBWIN 256
Definition at line 37 of file wm_subwindow.h.
Function Documentation
unsigned int index_to_framebuffer (int index)
Definition at line 348 of file wm_subwindow.c.
References GPU_color_depth(), and i.
Referenced by WM_set_framebuffer_index_color().
void wm_subwindow_close (wmWindow * win, int swinid)
Definition at line 185 of file wm_subwindow.c.
References BLI_remlink(), wmWindow::curswin, MEM_freeN(), NULL, wmWindow::subwindows, swin_from_swinid(), and wm_subwindow_free().
Referenced by ED_region_exit(), ED_screen_exit(), and region_subwindow().
int wm_subwindow_get (wmWindow * win)
Definition at line 97 of file wm_subwindow.c.
References wmWindow::curswin, and wmSubWindow::swinid.
void wm_subwindow_getmatrix (wmWindow * win, int swinid, float mat[][4])
Definition at line 134 of file wm_subwindow.c.
References bScreen::mainwin, orthographic_m4(), wmWindow::screen, swin_from_swinid(), wmSubWindow::swinid, and wm_subwindow_getsize().
Referenced by ui_popup_block_create(), and uiBeginBlock().
void wm_subwindow_getorigin (wmWindow * win, int swinid, int * x, int * y)
Definition at line 124 of file wm_subwindow.c.
References swin_from_swinid(), wmSubWindow::winrct, rcti::xmin, and rcti::ymin.
Referenced by tweak_gesture_modal(), WM_border_select_modal(), WM_gesture_circle_modal(), WM_gesture_lasso_modal(), WM_gesture_new(), and WM_gesture_straightline_modal().
void wm_subwindow_getsize (wmWindow * win, int swinid, int * x, int * y)
Definition at line 114 of file wm_subwindow.c.
References swin_from_swinid(), wmSubWindow::winrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by uiBeginBlock(), wm_subwindow_getmatrix(), wm_subwindow_open(), and wm_subwindow_position().
int wm_subwindow_open (wmWindow * win, rcti * winrct)
Definition at line 153 of file wm_subwindow.c.
References BLI_addtail(), wmWindow::curswin, ListBase::first, G, G_DEBUG_EVENTS, MEM_callocN(), wmSubWindow::next, wmWindow::subwindows, wmSubWindow::swinid, wmSubWindow::winrct, wm_subwindow_getsize(), wmOrtho2(), and wmSubWindowSet().
Referenced by ED_screen_refresh(), and region_subwindow().
void wm_subwindow_position (wmWindow * win, int swinid, rcti * winrct)
Definition at line 203 of file wm_subwindow.c.
References wmWindow::sizex, wmWindow::sizey, swin_from_swinid(), wmSubWindow::winrct, wm_subwindow_getsize(), wmOrtho2(), wmSubWindowSet(), rcti::xmax, and rcti::ymax.
Referenced by ED_screen_refresh(), and region_subwindow().
void wm_subwindows_free (wmWindow * win)
Definition at line 86 of file wm_subwindow.c.
References BLI_freelistN(), ListBase::first, wmSubWindow::next, wmWindow::subwindows, and wm_subwindow_free().
Referenced by wm_window_free().