Blender: UnixShell.c File Reference
UnixShell.c File Reference
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include "npapi.h"
#include "prthread.h"
#include "prlock.h"
#include "blender_plugin_types.h"
#include <signal.h>
Defines
#define MOZ_X11 1
Functions
static void log_entry (char *msg)
void execute_blenderplayer (BlenderPluginInstance *)
char * NPP_GetMIMEDescription (void)
NPError NPP_GetValue (NPP instance, NPPVariable variable, void *value)
NPError NPP_Initialize (void)
void NPP_Shutdown (void)
NPError NPP_New (NPMIMEType pluginType, NPP instance, uint16 mode, int16 argc, char *argn[], char *argv[], NPSavedData *saved)
NPError NPP_Destroy (NPP instance, NPSavedData **save)
NPError NPP_SetWindow (NPP instance, NPWindow *window)
NPError NPP_NewStream (NPP instance, NPMIMEType type, NPStream *stream, NPBool seekable, uint16 *stype)
int32 NPP_WriteReady (NPP instance, NPStream *stream)
int32 NPP_Write (NPP instance, NPStream *stream, int32 offset, int32 len, void *buffer)
NPError NPP_DestroyStream (NPP instance, NPStream *stream, NPError reason)
void NPP_StreamAsFile (NPP instance, NPStream *stream, const char *fname)
void NPP_Print (NPP instance, NPPrint *printInfo)
Variables
int32 STREAMBUFSIZE = 0X0FFFFFFF
Define Documentation
#define MOZ_X11 1
Definition at line 29 of file UnixShell.c.
Function Documentation
void execute_blenderplayer (BlenderPluginInstance * instance)
Definition at line 485 of file UnixShell.c.
References _BlenderPluginInstance::main_file_store, NPN_MemAlloc(), NULL, _BlenderPluginInstance::pID, _BlenderPluginInstance::stream_retrieved, strlen(), _BlenderPluginInstance::temp_mail_file_name, and _BlenderPluginInstance::window.
Referenced by NPP_Write().
static void log_entry (char * msg) [static]
Generate a log file.
Definition at line 543 of file UnixShell.c.
Referenced by NPP_Destroy(), NPP_DestroyStream(), NPP_GetMIMEDescription(), NPP_GetValue(), NPP_Initialize(), NPP_New(), NPP_NewStream(), NPP_Print(), NPP_SetWindow(), NPP_Shutdown(), NPP_Write(), and NPP_WriteReady().
NPError NPP_Destroy (NPP instance, NPSavedData ** save)
Definition at line 216 of file UnixShell.c.
References _BlenderPluginInstance::blend_file, log_entry(), _BlenderPluginInstance::main_file_store, NPN_MemFree(), NULL, _BlenderPluginInstance::pID, _BlenderPluginInstance::temp_mail_file_name, and _BlenderPluginInstance::window.
Referenced by Private_Destroy().
NPError NPP_DestroyStream (NPP instance, NPStream * stream, NPError reason)
Definition at line 426 of file UnixShell.c.
References if(), log_entry(), _BlenderPluginInstance::main_file_stream, NPN_Status(), and NULL.
Referenced by Private_DestroyStream().
char* NPP_GetMIMEDescription (void)
Definition at line 79 of file UnixShell.c.
References log_entry().
Referenced by NP_GetMIMEDescription().
NPError NPP_GetValue (NPP instance, NPPVariable variable, void * value)
Definition at line 86 of file UnixShell.c.
References err, and log_entry().
Referenced by NP_GetValue().
NPError NPP_Initialize (void)
Definition at line 127 of file UnixShell.c.
References log_entry().
Referenced by NP_Initialize().
NPError NPP_New (NPMIMEType pluginType, NPP instance, uint16 mode, int16 argc, char * argn[], char * argv[], NPSavedData * saved)
Definition at line 143 of file UnixShell.c.
References _BlenderPluginInstance::blend_file, _BlenderPluginInstance::browser_instance, _BlenderPluginInstance::display, i, if(), log_entry(), _BlenderPluginInstance::main_file_store, NPN_MemAlloc(), NULL, _BlenderPluginInstance::pID, _BlenderPluginInstance::temp_mail_file_name, and _BlenderPluginInstance::window.
Referenced by Private_New().
NPError NPP_NewStream (NPP instance, NPMIMEType type, NPStream * stream, NPBool seekable, uint16 * stype)
Definition at line 293 of file UnixShell.c.
References if(), log_entry(), _BlenderPluginInstance::main_file_store, _BlenderPluginInstance::main_file_stream, NPN_MemAlloc(), NULL, _BlenderPluginInstance::stream_retrieved, and _BlenderPluginInstance::stream_total.
Referenced by Private_NewStream().
void NPP_Print (NPP instance, NPPrint * printInfo)
Definition at line 468 of file UnixShell.c.
References FALSE, log_entry(), and NULL.
Referenced by Private_Print().
NPError NPP_SetWindow (NPP instance, NPWindow * window)
Definition at line 258 of file UnixShell.c.
References _BlenderPluginInstance::display, if(), log_entry(), NULL, and _BlenderPluginInstance::window.
Referenced by Private_SetWindow().
void NPP_Shutdown (void)
Definition at line 136 of file UnixShell.c.
References log_entry().
Referenced by NP_Shutdown().
void NPP_StreamAsFile (NPP instance, NPStream * stream, const char * fname)
Definition at line 461 of file UnixShell.c.
Referenced by Private_StreamAsFile().
int32 NPP_Write (NPP instance, NPStream * stream, int32 offset, int32 len, void * buffer)
Definition at line 380 of file UnixShell.c.
References execute_blenderplayer(), if(), len(), log_entry(), _BlenderPluginInstance::main_file_store, _BlenderPluginInstance::main_file_stream, NULL, _BlenderPluginInstance::stream_retrieved, and _BlenderPluginInstance::stream_total.
Referenced by Private_Write().
int32 NPP_WriteReady (NPP instance, NPStream * stream)
Definition at line 350 of file UnixShell.c.
References acceptable, if(), log_entry(), _BlenderPluginInstance::main_file_store, _BlenderPluginInstance::main_file_stream, NULL, and STREAMBUFSIZE.
Referenced by Private_WriteReady().
Variable Documentation
int32 STREAMBUFSIZE = 0X0FFFFFFF
If defined: write to the plugin log file
Definition at line 62 of file UnixShell.c.
Referenced by NPP_WriteReady().