Blender: AUD_FileWriter Class Reference
AUD_FileWriter Class Reference
#include <AUD_FileWriter.h>
Static Public Member Functions
static AUD_Reference< AUD_IWriter > createWriter (std::string filename, AUD_DeviceSpecs specs, AUD_Container format, AUD_Codec codec, unsigned int bitrate)
static void writeReader (AUD_Reference< AUD_IReader > reader, AUD_Reference< AUD_IWriter > writer, unsigned int length, unsigned int buffersize)
Detailed Description
This class is able to create IWriter classes as well as write reads to them.
Definition at line 43 of file AUD_FileWriter.h.
Member Function Documentation
AUD_Reference< AUD_IWriter > AUD_FileWriter::createWriter (std::string filename, AUD_DeviceSpecs specs, AUD_Container format, AUD_Codec codec, unsigned int bitrate) [static]
Creates a new IWriter.
Parameters:
filename The file to write to.
specs The file's audio specification.
format The file's container format.
codec The codec used for encoding the audio data.
bitrate The bitrate for encoding.
Returns:
The writer to write data to.
Definition at line 46 of file AUD_FileWriter.cpp.
References AUD_ERROR_SPECS, AUD_THROW, and write_error.
Referenced by AUD_mixdown().
void AUD_FileWriter::writeReader (AUD_Reference< AUD_IReader > reader, AUD_Reference< AUD_IWriter > writer, unsigned int length, unsigned int buffersize) [static]
Writes a reader to a writer.
Parameters:
reader The reader to read from.
writer The writer to write to.
length How many samples should be transfered.
buffersize How many samples should be transfered at once.
Definition at line 68 of file AUD_FileWriter.cpp.
References AUD_SAMPLE_SIZE, AUD_Buffer::getBuffer(), i, len(), and length().
Referenced by AUD_mixdown().
The documentation for this class was generated from the following files:
AUD_FileWriter.h
AUD_FileWriter.cpp