Blender: btConstraintSolver Class Reference
btConstraintSolver Class Reference
btConstraintSolver provides solver interface
#include <btConstraintSolver.h>
Public Member Functions
virtual ~btConstraintSolver ()
virtual void prepareSolve (int, int)
virtual btScalar solveGroup (btCollisionObject **bodies, int numBodies, btPersistentManifold **manifold, int numManifolds, btTypedConstraint **constraints, int numConstraints, const btContactSolverInfo &info, class btIDebugDraw *debugDrawer, btStackAlloc *stackAlloc, btDispatcher *dispatcher)=0
solve a group of constraints
virtual void allSolved (const btContactSolverInfo &, class btIDebugDraw *, btStackAlloc *)
virtual void reset ()=0
clear internal cached data and reset random seed
Detailed Description
btConstraintSolver provides solver interface
Definition at line 31 of file btConstraintSolver.h.
Constructor & Destructor Documentation
virtual btConstraintSolver::~btConstraintSolver () [inline, virtual]
Definition at line 36 of file btConstraintSolver.h.
Referenced by btDiscreteDynamicsWorld::~btDiscreteDynamicsWorld().
Member Function Documentation
virtual void btConstraintSolver::allSolved (const btContactSolverInfo & , class btIDebugDraw * , btStackAlloc *) [inline, virtual]
Definition at line 43 of file btConstraintSolver.h.
Referenced by btDiscreteDynamicsWorld::solveConstraints(), and btSimpleDynamicsWorld::stepSimulation().
virtual void btConstraintSolver::prepareSolve (int , int) [inline, virtual]
Definition at line 38 of file btConstraintSolver.h.
Referenced by btDiscreteDynamicsWorld::solveConstraints(), and btSimpleDynamicsWorld::stepSimulation().
virtual void btConstraintSolver::reset () [pure virtual]
clear internal cached data and reset random seed
Implemented in btSequentialImpulseConstraintSolver.
virtual btScalar btConstraintSolver::solveGroup (btCollisionObject ** bodies, int numBodies, btPersistentManifold ** manifold, int numManifolds, btTypedConstraint ** constraints, int numConstraints, const btContactSolverInfo & info, class btIDebugDraw * debugDrawer, btStackAlloc * stackAlloc, btDispatcher * dispatcher) [pure virtual]
solve a group of constraints
Implemented in btSequentialImpulseConstraintSolver.
Referenced by btSimpleDynamicsWorld::stepSimulation().
The documentation for this class was generated from the following file:
btConstraintSolver.h