Blender: bmesh_error.h File Reference
bmesh_error.h File Reference
Defines
#define BM_ELEM_INDEX_VALIDATE(_bm, _msg_a, _msg_b) BM_mesh_elem_index_validate(_bm, __FILE__ ":" STRINGIFY(__LINE__), __func__, _msg_a, _msg_b)
#define BMERR_SELF_INTERSECTING 1
#define BMERR_DISSOLVEDISK_FAILED 2
#define BMERR_CONNECTVERT_FAILED 3
#define BMERR_WALKER_FAILED 4
#define BMERR_DISSOLVEFACES_FAILED 5
#define BMERR_DISSOLVEVERTS_FAILED 6
#define BMERR_TESSELLATION 7
#define BMERR_NONMANIFOLD 8
#define BMERR_INVALID_SELECTION 9
#define BMERR_MESH_ERROR 10
#define _BMESH_DUMMY_ABORT() (void)0
#define BMESH_ASSERT(a)
Functions
void BMO_error_raise (BMesh *bm, BMOperator *owner, int errcode, const char *msg)
int BMO_error_get (BMesh *bm, const char **msg, BMOperator **op)
int BMO_error_occurred (BMesh *bm)
int BMO_error_pop (BMesh *bm, const char **msg, BMOperator **op)
void BMO_error_clear (BMesh *bm)
Define Documentation
#define _BMESH_DUMMY_ABORT () (void)0
Definition at line 77 of file bmesh_error.h.
#define BM_ELEM_INDEX_VALIDATE (_bm, _msg_a, _msg_b) BM_mesh_elem_index_validate(_bm, __FILE__ ":" STRINGIFY(__LINE__), __func__, _msg_a, _msg_b)
Definition at line 56 of file bmesh_error.h.
Referenced by BM_mesh_elem_index_ensure(), BMO_op_finish(), and BMO_op_init().
#define BMERR_CONNECTVERT_FAILED 3
Definition at line 64 of file bmesh_error.h.
Referenced by bmo_connectverts_exec().
#define BMERR_DISSOLVEDISK_FAILED 2
Definition at line 63 of file bmesh_error.h.
#define BMERR_DISSOLVEFACES_FAILED 5
Definition at line 66 of file bmesh_error.h.
Referenced by BM_faces_join(), and bmo_dissolve_faces_exec().
#define BMERR_DISSOLVEVERTS_FAILED 6
Definition at line 67 of file bmesh_error.h.
Referenced by bmo_dissolve_verts_exec().
#define BMERR_INVALID_SELECTION 9
Definition at line 70 of file bmesh_error.h.
Referenced by bmo_bridge_loops_exec(), bmo_edgerotate_exec(), and bmo_vertex_slide_exec().
#define BMERR_MESH_ERROR 10
Definition at line 71 of file bmesh_error.h.
Referenced by bmo_extrude_face_indiv_exec(), and count_flagged_radial().
#define BMERR_NONMANIFOLD 8
Definition at line 69 of file bmesh_error.h.
#define BMERR_SELF_INTERSECTING 1
Definition at line 62 of file bmesh_error.h.
#define BMERR_TESSELLATION 7
Definition at line 68 of file bmesh_error.h.
#define BMERR_WALKER_FAILED 4
Definition at line 65 of file bmesh_error.h.
Referenced by bmw_IslandboundWalker_step().
#define BMESH_ASSERT (a)
Value:
(void)((!(a)) ?  (\
        (                                                                     \
        fprintf(stderr,                                                       \
            "BMESH_ASSERT failed: %s, %s(), %d at \'%s\'\n",                  \
            __FILE__, __func__, __LINE__, STRINGIFY(a)),                      \
        _BMESH_DUMMY_ABORT(),                                                 \
        NULL)) : NULL)
Definition at line 82 of file bmesh_error.h.
Referenced by _bm_elem_hide_set(), BM_edge_split(), BM_face_exists_multi_edge(), BM_faces_join(), BM_faces_join_pair(), bmesh_elem_check(), bmesh_jekv(), bmesh_jfke(), bmesh_radial_append(), bmesh_radial_length(), bmesh_radial_loop_remove(), bmesh_radial_validate(), bmesh_semv(), BMW_init(), count_flagged_radial(), and quad_4edge_subdivide().
Function Documentation
void BMO_error_clear (BMesh * bm)
Definition at line 1232 of file bmesh_operators.c.
References BMO_error_pop(), and NULL.
Referenced by BM_mesh_data_free(), bmo_dissolve_faces_exec(), bmo_dissolve_limit_exec(), and bmo_dissolve_verts_exec().
int BMO_error_get (BMesh * bm, const char ** msg, BMOperator ** op)
Definition at line 1255 of file bmesh_operators.c.
References err, BMOpError::errorcode, BMesh::errorstack, ListBase::first, BMOpError::msg, and BMOpError::op.
Referenced by bmo_dissolve_verts_exec(), BMO_error_pop(), and EDBM_op_finish().
int BMO_error_occurred (BMesh * bm)
Definition at line 1249 of file bmesh_operators.c.
References BMesh::errorstack, ListBase::first, and NULL.
Referenced by BM_faces_join(), bmo_dissolve_faces_exec(), and bmo_dissolve_verts_exec().
int BMO_error_pop (BMesh * bm, const char ** msg, BMOperator ** op)
Definition at line 1268 of file bmesh_operators.c.
References BLI_remlink(), BMO_error_get(), err, BMOpError::errorcode, BMesh::errorstack, ListBase::first, and MEM_freeN().
Referenced by BMO_error_clear().
void BMO_error_raise (BMesh * bm, BMOperator * owner, int errcode, const char * msg)
Definition at line 1237 of file bmesh_operators.c.
References BLI_addhead(), bmo_error_messages, err, BMOpError::errorcode, BMesh::errorstack, MEM_callocN(), BMOpError::msg, and BMOpError::op.
Referenced by BM_faces_join(), bmo_bridge_loops_exec(), bmo_connectverts_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_verts_exec(), bmo_edgerotate_exec(), bmo_extrude_face_indiv_exec(), bmo_vertex_slide_exec(), bmw_IslandboundWalker_step(), and count_flagged_radial().