Blender: object_edit.c File Reference
object_edit.c File Reference
object
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <float.h>
#include <ctype.h>
#include <stddef.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_ghash.h"
#include "BLI_rand.h"
#include "DNA_armature_types.h"
#include "DNA_curve_types.h"
#include "DNA_group_types.h"
#include "DNA_lattice_types.h"
#include "DNA_material_types.h"
#include "DNA_meta_types.h"
#include "DNA_property_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "DNA_object_force.h"
#include "DNA_meshdata_types.h"
#include "DNA_vfont_types.h"
#include "DNA_mesh_types.h"
#include "IMB_imbuf_types.h"
#include "BKE_anim.h"
#include "BKE_constraint.h"
#include "BKE_context.h"
#include "BKE_curve.h"
#include "BKE_effect.h"
#include "BKE_depsgraph.h"
#include "BKE_font.h"
#include "BKE_image.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_mball.h"
#include "BKE_mesh.h"
#include "BKE_object.h"
#include "BKE_paint.h"
#include "BKE_pointcache.h"
#include "BKE_property.h"
#include "BKE_sca.h"
#include "BKE_softbody.h"
#include "BKE_modifier.h"
#include "BKE_tessmesh.h"
#include "ED_armature.h"
#include "ED_curve.h"
#include "ED_mesh.h"
#include "ED_mball.h"
#include "ED_lattice.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "ED_image.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "UI_interface.h"
#include "WM_api.h"
#include "WM_types.h"
#include "object_intern.h"
Defines
#define COPY_PROPERTIES_REPLACE 1
#define COPY_PROPERTIES_MERGE 2
#define COPY_PROPERTIES_COPY 3
Functions
static void error (const char *UNUSED(arg))
static void waitcursor (int UNUSED(val))
static int pupmenu (const char *UNUSED(msg))
static void error_libdata (void)
Object * ED_object_context (bContext *C)
Object * ED_object_active_context (bContext *C)
static int object_hide_view_clear_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_hide_view_clear (wmOperatorType *ot)
static int object_hide_view_set_exec (bContext *C, wmOperator *op)
void OBJECT_OT_hide_view_set (wmOperatorType *ot)
static int object_hide_render_clear_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_hide_render_clear (wmOperatorType *ot)
static int object_hide_render_set_exec (bContext *C, wmOperator *op)
void OBJECT_OT_hide_render_set (wmOperatorType *ot)
void ED_object_exit_editmode (bContext *C, int flag)
void ED_object_enter_editmode (bContext *C, int flag)
static int editmode_toggle_exec (bContext *C, wmOperator *UNUSED(op))
static int editmode_toggle_poll (bContext *C)
void OBJECT_OT_editmode_toggle (wmOperatorType *ot)
static int posemode_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_posemode_toggle (wmOperatorType *ot)
static void copymenu_properties (Scene *scene, View3D *v3d, Object *ob)
static void copymenu_logicbricks (Scene *scene, View3D *v3d, Object *ob)
static void copy_texture_space (Object *to, Object *ob)
static void copy_attr (Main *bmain, Scene *scene, View3D *v3d, short event)
static void UNUSED_FUNCTION() copy_attr_menu (Main *bmain, Scene *scene, View3D *v3d)
static int forcefield_toggle_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_forcefield_toggle (wmOperatorType *ot)
void ED_objects_recalculate_paths (bContext *C, Scene *scene)
static int object_calculate_paths_exec (bContext *C, wmOperator *op)
void OBJECT_OT_paths_calculate (wmOperatorType *ot)
void ED_objects_clear_paths (bContext *C)
static int object_clear_paths_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_paths_clear (wmOperatorType *ot)
static int shade_smooth_exec (bContext *C, wmOperator *op)
static int shade_poll (bContext *C)
void OBJECT_OT_shade_flat (wmOperatorType *ot)
void OBJECT_OT_shade_smooth (wmOperatorType *ot)
static void UNUSED_FUNCTION() image_aspect (Scene *scene, View3D *v3d)
static EnumPropertyItem * object_mode_set_itemsf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
static const char * object_mode_op_string (int mode)
static int object_mode_set_compat (bContext *UNUSED(C), wmOperator *op, Object *ob)
static int object_mode_set_exec (bContext *C, wmOperator *op)
void OBJECT_OT_mode_set (wmOperatorType *ot)
void ED_object_toggle_modes (bContext *C, int mode)
static int game_property_new (bContext *C, wmOperator *op)
void OBJECT_OT_game_property_new (wmOperatorType *ot)
static int game_property_remove (bContext *C, wmOperator *op)
void OBJECT_OT_game_property_remove (wmOperatorType *ot)
static EnumPropertyItem * gameprops_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
static int game_property_copy_exec (bContext *C, wmOperator *op)
void OBJECT_OT_game_property_copy (wmOperatorType *ot)
static int game_property_clear_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_game_property_clear (wmOperatorType *ot)
static int logicbricks_copy_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_logic_bricks_copy (wmOperatorType *ot)
static int game_physics_copy_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_game_physics_copy (struct wmOperatorType *ot)
Variables
static EnumPropertyItem game_properties_copy_operations []
static EnumPropertyItem gameprops_items []
Detailed Description
Definition in file object_edit.c.
Define Documentation
#define COPY_PROPERTIES_COPY 3
Definition at line 1587 of file object_edit.c.
#define COPY_PROPERTIES_MERGE 2
Definition at line 1586 of file object_edit.c.
#define COPY_PROPERTIES_REPLACE 1
Definition at line 1585 of file object_edit.c.
Referenced by game_property_copy_exec().
Function Documentation
static void copy_attr (Main * bmain, Scene * scene, View3D * v3d, short event) [static]
Definition at line 757 of file object_edit.c.
References BASACT, Curve::bevobj, Curve::bevresol, BKE_text_to_curve(), BLI_addhead(), BLI_addtail(), BLI_strncpy(), Object::bsoft, Object::col, Object::collision_boundtype, Object::constraints, copy_bulletsoftbody(), copy_constraints(), copy_qt_qt(), copy_softbody(), copy_texture_space(), copy_v3_v3(), copy_v4_v4(), copymenu_logicbricks(), copymenu_properties(), CU_UV_ORCO, DAG_ids_flush_update(), DAG_scene_sort(), Object::damping, Object::data, Object::dloc, Object::dquat, Object::drot, Object::dscale, Object::dt, Object::dtx, Object::dup_group, Object::dupend, Object::dupoff, Object::dupon, Object::dupsta, ELEM, eModifierType_Softbody, eModifierType_Subsurf, Object::empty_drawsize, Object::empty_drawtype, Curve::ext1, Curve::ext2, Curve::family, ListBase::first, FIRSTBASE, Curve::flag, Mesh::flag, Object::formfactor, Curve::fsize, Object::gameflag, VFont::id, Group::id, Scene::id, id_lib_extern(), id_us_plus(), Object::index, Object::inertia, ID::lib, Curve::linedist, Object::loc, Object::margin, Object::mass, Object::max_vel, ME_AUTOSMOOTH, Object::min_vel, modifier_copyData(), modifier_new(), Object::modifiers, modifiers_findByType(), Nurb::next, Base::next, Curve::nurb, OB_BOUNDS, OB_CURVE, OB_DUPLI, OB_FONT, OB_MESH, OB_RECALC_DATA, OB_RECALC_OB, OB_SURF, OBACT, Scene::obedit, Base::object, Object::protectflag, Object::quat, Object::rdamping, Object::recalc, Nurb::resolu, Curve::resolu, Curve::resolu_ren, Object::rot, sbFree(), Object::sf, Curve::shear, Object::size, Mesh::smoothresh, Object::soft, Object::softflag, Curve::spacemode, Curve::spacing, Curve::taperobj, TESTBASELIB, Curve::textoncurve, Object::transflag, TRUE, Object::type, Curve::ulheight, Curve::ulpos, ID::us, Curve::vfont, Curve::vfontb, Curve::vfontbi, Curve::vfonti, Curve::width, Curve::wordspace, Curve::xof, and Curve::yof.
Referenced by copy_attr_menu().
static void UNUSED_FUNCTION() copy_attr_menu (Main * bmain, Scene * scene, View3D * v3d) [static]
Definition at line 1006 of file object_edit.c.
References copy_attr(), OB_CURVE, OB_FONT, OB_LATTICE, OB_MESH, OB_SURF, OBACT, pupmenu(), Object::soft, str, and Object::type.
static void copy_texture_space (Object * to, Object * ob) [static]
Definition at line 707 of file object_edit.c.
References Object::data, ELEM3, NULL, OB_CURVE, OB_FONT, OB_MBALL, OB_MESH, OB_SURF, tex_space_curve(), tex_space_mball(), and Object::type.
Referenced by copy_attr().
static void copymenu_logicbricks (Scene * scene, View3D * v3d, Object * ob) [static]
Definition at line 671 of file object_edit.c.
References Object::actuators, clear_sca_new_poins_ob(), Object::controllers, copy_actuators(), copy_controllers(), copy_sensors(), FIRSTBASE, free_actuators(), free_controllers(), free_sensors(), Object::init_state, Base::next, Base::object, Object::scaflag, Object::scavisflag, Object::sensors, set_sca_new_poins_ob(), Object::state, TESTBASELIB, unlink_actuators(), and unlink_controllers().
Referenced by copy_attr().
static void copymenu_properties (Scene * scene, View3D * v3d, Object * ob) [static]
Definition at line 610 of file object_edit.c.
References BASACT, BLI_findlink(), copy_properties(), ListBase::first, FIRSTBASE, MEM_callocN(), MEM_freeN(), bProperty::name, Base::next, bProperty::next, Base::object, Object::prop, pupmenu(), set_ob_property(), str, and TESTBASELIB.
Referenced by copy_attr().
Object* ED_object_active_context (bContext * C) [read]
Definition at line 121 of file object_edit.c.
References CTX_data_active_object(), ED_object_context(), and NULL.
Referenced by childof_clear_inverse_exec(), childof_set_inverse_exec(), constraint_move_down_exec(), constraint_move_up_exec(), ED_operator_object_active(), ED_operator_object_active_editable(), ED_operator_object_active_editable_font(), ED_operator_object_active_editable_mesh(), ED_operator_outliner_active_no_editobject(), edit_constraint_invoke_properties(), edit_constraint_poll_generic(), edit_modifier_poll_generic(), edit_object_property_get(), explode_refresh_exec(), game_physics_copy_exec(), game_property_copy_exec(), gameprops_itemf(), get_new_constraint_target(), limitdistance_reset_exec(), logicbricks_copy_exec(), make_links_data_exec(), make_proxy_exec(), make_proxy_invoke(), meshdeform_bind_exec(), modifier_add_exec(), modifier_add_itemf(), modifier_apply_exec(), modifier_convert_exec(), modifier_copy_exec(), modifier_move_down_exec(), modifier_move_up_exec(), modifier_remove_exec(), multires_base_apply_exec(), multires_external_pack_exec(), multires_external_save_exec(), multires_external_save_invoke(), multires_higher_levels_delete_exec(), multires_reshape_exec(), multires_subdivide_exec(), navmesh_clear_exec(), navmesh_obmode_data_poll(), navmesh_obmode_poll(), navmesh_reset_exec(), object_constraint_add_exec(), object_constraint_copy_exec(), objectsolver_clear_inverse_exec(), objectsolver_set_inverse_exec(), ocean_bake_exec(), parent_noinv_set_exec(), parent_set_exec(), parent_set_invoke(), pose_constraint_add_exec(), proxy_group_object_itemf(), stretchto_reset_exec(), and track_set_exec().
Object* ED_object_context (bContext * C) [read]
Definition at line 114 of file object_edit.c.
References CTX_data_pointer_get_type(), PointerRNA::data, and RNA_Object.
Referenced by connect_hair_exec(), disconnect_hair_exec(), dynamicPaint_initBake(), ED_object_active_context(), get_poselib_object(), group_add_exec(), group_link_exec(), group_move_exec(), group_remove_exec(), group_sort_exec(), layers_poll(), material_slot_add_exec(), material_slot_assign_exec(), material_slot_copy_exec(), material_slot_de_select(), material_slot_remove_exec(), mesh_sticky_add_exec(), mesh_sticky_remove_exec(), mesh_uv_texture_add_exec(), mesh_uv_texture_remove_exec(), mesh_vertex_color_add_exec(), mesh_vertex_color_remove_exec(), output_toggle_exec(), particle_system_add_exec(), particle_system_remove_exec(), pose_calculate_paths_exec(), pose_clear_paths_exec(), pose_de_select_all_exec(), pose_group_add_exec(), pose_group_assign_exec(), pose_group_deselect_exec(), pose_group_remove_exec(), pose_group_select_exec(), pose_group_unassign_exec(), pose_groups_menu_invoke(), set_active_group_exec(), shape_key_add_exec(), shape_key_clear_exec(), shape_key_mirror_exec(), shape_key_mode_poll(), shape_key_move_exec(), shape_key_poll(), shape_key_remove_exec(), shape_key_retime_exec(), surface_slot_add_exec(), surface_slot_remove_exec(), type_toggle_exec(), vertex_group_add_exec(), vertex_group_assign_exec(), vertex_group_blend_exec(), vertex_group_blend_poll(), vertex_group_clean_exec(), vertex_group_copy_exec(), vertex_group_copy_to_linked_exec(), vertex_group_copy_to_selected_exec(), vertex_group_deselect_exec(), vertex_group_invert_exec(), vertex_group_levels_exec(), vertex_group_mirror_exec(), vertex_group_normalize_all_exec(), vertex_group_normalize_exec(), vertex_group_poll(), vertex_group_poll_edit(), vertex_group_poll_edit_or_wpaint_vert_select(), vertex_group_remove_exec(), vertex_group_remove_from_exec(), vertex_group_select_exec(), vertex_group_sort_exec(), vgroup_itemf(), and vgroup_move_exec().
void ED_object_enter_editmode (bContext * C, int flag)
Definition at line 397 of file object_edit.c.
References Scene::basact, BMEditMesh::bm, BM_mesh_select_mode_flush(), BMEdit_FromObject(), BMEdit_RecalcTessellation(), CTX_data_active_base(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_area(), DAG_id_tag_update(), Object::data, ED_armature_to_edit(), ED_object_toggle_modes(), ED_undo_push(), EDBM_mesh_make(), EDBM_mesh_normals_update(), ELEM3, EM_DO_UNDO, EM_IGNORE_LAYER, EM_WAITCURSOR, error_libdata(), ListBase::first, Object::id, bArmature::id, Scene::id, Scene::lay, View3D::lay, Base::lay, ID::lib, LIKELY, make_editLatt(), make_editMball(), make_editNurb(), make_editText(), Object::mode, NC_SCENE, ND_MODE, NS_EDITMODE_ARMATURE, NS_EDITMODE_CURVE, NS_EDITMODE_LATTICE, NS_EDITMODE_MBALL, NS_EDITMODE_MESH, NS_EDITMODE_TEXT, NS_MODE_OBJECT, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, OB_SURF, Scene::obedit, Base::object, object_data_is_libdata(), Object::restore_mode, SPACE_VIEW3D, ScrArea::spacedata, ScrArea::spacetype, Object::type, waitcursor(), and WM_event_add_notifier().
Referenced by createRepresentation(), ED_object_add_type(), edbm_sort_faces_exec(), editmode_toggle_exec(), effector_add_type(), join_curve_exec(), join_mesh_exec(), make_prim_init(), and object_armature_add_exec().
void ED_object_exit_editmode (bContext * C, int flag)
Definition at line 309 of file object_edit.c.
References BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), BLI_freelistN(), BMEditMesh::bm, PTCacheID::cache, CTX_data_edit_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, ED_armature_edit_free(), ED_armature_from_edit(), ED_undo_push(), EDBM_mesh_free(), EDBM_mesh_load(), Mesh::edit_btmesh, ELEM, EM_DO_UNDO, EM_FREEDATA, EM_WAITCURSOR, error(), ListBase::first, PointCache::flag, free_editLatt(), free_editMball(), free_editNurb(), free_editText(), Object::id, load_editLatt(), load_editMball(), load_editNurb(), load_editText(), MEM_freeN(), MESH_MAX_VERTS, mesh_mirrtopo_table(), mesh_octree_table(), Object::mode, NC_SCENE, ND_MODE, PTCacheID::next, NS_MODE_OBJECT, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_MODE_WEIGHT_PAINT, OB_RECALC_DATA, OB_RECALC_OB, OB_SURF, Scene::obedit, PTCACHE_OUTDATED, PTCACHE_RESET_OUTDATED, PTCACHE_TYPE_PARTICLES, Object::restore_mode, BMesh::totvert, PTCacheID::type, Object::type, waitcursor(), and WM_event_add_notifier().
Referenced by createRepresentation(), curvesurf_prim_add(), ED_object_add_type(), ED_screen_set_scene(), edbm_sort_faces_exec(), editmode_toggle_exec(), effector_add_type(), init_bake_internal(), join_curve_exec(), join_mesh_exec(), make_prim_finish(), object_armature_add_exec(), object_delete_cb(), object_metaball_add_exec(), posemode_exec(), screen_render_invoke(), tree_element_active_pose(), and WM_write_file().
void ED_object_toggle_modes (bContext * C, int mode)
Definition at line 1485 of file object_edit.c.
References NULL, OB_MODE_EDIT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, WM_OP_EXEC_REGION_WIN, and WM_operator_name_call().
Referenced by delete_customdata_layer(), ED_editors_init(), and ED_object_enter_editmode().
void ED_objects_clear_paths (bContext * C)
Definition at line 1167 of file object_edit.c.
References animviz_free_motionpath(), CTX_DATA_BEGIN, CTX_DATA_END, MOTIONPATH_BAKE_HAS_PATHS, and NULL.
Referenced by object_clear_paths_exec().
void ED_objects_recalculate_paths (bContext * C, Scene * scene)
Definition at line 1106 of file object_edit.c.
References animviz_calc_motionpaths(), animviz_get_object_motionpaths(), ANIMVIZ_RECALC_PATHS, BLI_freelistN(), CTX_DATA_BEGIN, CTX_DATA_END, and NULL.
Referenced by object_calculate_paths_exec(), and special_aftertrans_update().
static int editmode_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 525 of file object_edit.c.
References CTX_data_edit_object(), CTX_data_tool_settings(), CTX_wm_manager(), ED_object_enter_editmode(), ED_object_exit_editmode(), ED_space_image_uv_sculpt_update(), EM_FREEDATA, EM_FREEUNDO, EM_WAITCURSOR, and OPERATOR_FINISHED.
Referenced by OBJECT_OT_editmode_toggle().
static int editmode_toggle_poll (bContext * C) [static]
Definition at line 539 of file object_edit.c.
References CTX_data_active_object(), Object::data, ELEM, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_RESTRICT_VIEW, OB_SURF, Object::restrictflag, and Object::type.
Referenced by OBJECT_OT_editmode_toggle().
static void error (const char * UNUSEDarg) [static]
Definition at line 107 of file object_edit.c.
Referenced by ED_object_exit_editmode().
static void error_libdata (void) [static]
Definition at line 112 of file object_edit.c.
Referenced by ED_object_enter_editmode().
static int forcefield_toggle_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1065 of file object_edit.c.
References CTX_data_active_object(), PartDeflect::forcefield, NC_OBJECT, ND_DRAW, NULL, object_add_collision_fields(), OPERATOR_FINISHED, Object::pd, PFIELD_FORCE, and WM_event_add_notifier().
Referenced by OBJECT_OT_forcefield_toggle().
static int game_physics_copy_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1760 of file object_edit.c.
References Object::anisotropicFriction, Object::bsoft, Object::collision_boundtype, copy_bulletsoftbody(), CTX_DATA_BEGIN, CTX_DATA_END, Object::damping, ED_object_active_context(), Object::formfactor, Object::gameflag, Object::gameflag2, Object::inertia, Object::margin, Object::mass, Object::max_vel, Object::min_vel, OB_RESTRICT_RENDER, Object::obstacleRad, OPERATOR_FINISHED, Object::rdamping, and Object::restrictflag.
Referenced by OBJECT_OT_game_physics_copy().
static int game_property_clear_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1678 of file object_edit.c.
References CTX_DATA_BEGIN, CTX_DATA_END, free_properties(), NC_LOGIC, NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by OBJECT_OT_game_property_clear().
static int game_property_copy_exec (bContext * C, wmOperator * op) [static]
Definition at line 1622 of file object_edit.c.
References BLI_findlink(), copy_properties(), COPY_PROPERTIES_REPLACE, CTX_DATA_BEGIN, CTX_DATA_END, ED_object_active_context(), ListBase::first, bProperty::next, OPERATOR_FINISHED, Object::prop, wmOperator::ptr, RNA_enum_get(), set_ob_property(), and Object::type.
Referenced by OBJECT_OT_game_property_copy().
static int game_property_new (bContext * C, wmOperator * op) [static]
Definition at line 1505 of file object_edit.c.
References BLI_addtail(), BLI_strncpy(), CTX_data_active_object(), MAX_NAME, bProperty::name, Object::name, NC_LOGIC, new_property(), NULL, OPERATOR_FINISHED, Object::prop, wmOperator::ptr, RNA_enum_get(), RNA_string_get(), Object::type, unique_property(), and WM_event_add_notifier().
Referenced by OBJECT_OT_game_property_new().
static int game_property_remove (bContext * C, wmOperator * op) [static]
Definition at line 1545 of file object_edit.c.
References BLI_findlink(), BLI_remlink(), CTX_data_active_object(), free_property(), Object::index, NC_LOGIC, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::prop, wmOperator::ptr, RNA_int_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_game_property_remove().
static EnumPropertyItem* gameprops_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 1598 of file object_edit.c.
References ED_object_active_context(), ListBase::first, gameprops_items, EnumPropertyItem::identifier, bProperty::name, EnumPropertyItem::name, bProperty::next, NULL, Object::prop, RNA_enum_item_add(), RNA_enum_item_end(), and EnumPropertyItem::value.
Referenced by OBJECT_OT_game_property_copy().
static void UNUSED_FUNCTION() image_aspect (Scene * scene, View3D * v3d) [static]
Definition at line 1284 of file object_edit.c.
References BKE_image_get_ibuf(), DAG_id_tag_update(), Object::data, ELEM3, FIRSTBASE, give_current_material(), Object::id, Tex::ima, MAX_MTEX, mesh_get_texspace(), Material::mtex, Base::next, NULL, OB_CURVE, OB_FONT, OB_MESH, OB_RECALC_OB, OB_SURF, Base::object, Object::size, Curve::size, size(), TESTBASELIB, MTex::tex, TEX_IMAGE, Object::totcol, Object::type, Tex::type, ImBuf::x, and ImBuf::y.
static int logicbricks_copy_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1704 of file object_edit.c.
References Object::actcol, Object::actuators, clear_sca_new_poins_ob(), Object::controllers, copy_actuators(), copy_controllers(), copy_sensors(), CTX_DATA_BEGIN, CTX_DATA_END, ED_object_active_context(), free_actuators(), free_controllers(), free_sensors(), Object::init_state, NC_LOGIC, NC_OBJECT, ND_DRAW, NULL, OPERATOR_FINISHED, Object::scaflag, Object::scavisflag, Object::sensors, set_sca_new_poins_ob(), Object::state, Object::totcol, unlink_actuators(), unlink_controllers(), and WM_event_add_notifier().
Referenced by OBJECT_OT_logic_bricks_copy().
static int object_calculate_paths_exec (bContext * C, wmOperator * op) [static]
Definition at line 1127 of file object_edit.c.
References animviz_verify_motionpaths(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_scene(), ED_objects_recalculate_paths(), NC_OBJECT, ND_POSE, NULL, OPERATOR_FINISHED, wmOperator::reports, and WM_event_add_notifier().
Referenced by OBJECT_OT_paths_calculate().
static int object_clear_paths_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1182 of file object_edit.c.
References ED_objects_clear_paths(), NC_OBJECT, ND_POSE, NULL, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by OBJECT_OT_paths_clear().
static int object_hide_render_clear_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 234 of file object_edit.c.
References CTX_DATA_BEGIN, CTX_DATA_END, NC_SPACE, ND_SPACE_OUTLINER, NULL, OB_RESTRICT_RENDER, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by OBJECT_OT_hide_render_clear().
static int object_hide_render_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 269 of file object_edit.c.
References CTX_DATA_BEGIN, CTX_DATA_END, NC_SPACE, ND_SPACE_OUTLINER, NULL, OB_RESTRICT_RENDER, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SELECT, and WM_event_add_notifier().
Referenced by OBJECT_OT_hide_render_set().
static int object_hide_view_clear_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 133 of file object_edit.c.
References CTX_data_main(), CTX_data_scene(), CTX_wm_area(), DAG_id_type_tag(), DAG_scene_sort(), ListBase::first, FIRSTBASE, Object::flag, Base::flag, ID_OB, View3D::lay, Base::lay, NC_SCENE, ND_OB_SELECT, Base::next, OB_RESTRICT_VIEW, Base::object, OPERATOR_FINISHED, Object::restrictflag, SELECT, ScrArea::spacedata, and WM_event_add_notifier().
Referenced by OBJECT_OT_hide_view_clear().
static int object_hide_view_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 176 of file object_edit.c.
References BASACT, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_id_type_tag(), DAG_scene_sort(), ED_base_object_activate(), ID_OB, NC_SCENE, ND_OB_SELECT, NULL, OB_RESTRICT_VIEW, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SELECT, and WM_event_add_notifier().
Referenced by OBJECT_OT_hide_view_set().
static const char* object_mode_op_string (int mode) [static]
Definition at line 1375 of file object_edit.c.
References NULL, OB_MODE_EDIT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, and OB_MODE_WEIGHT_PAINT.
Referenced by object_mode_set_exec().
static int object_mode_set_compat (bContext * UNUSEDC, wmOperator * op, Object * ob) [static]
Definition at line 1396 of file object_edit.c.
References Object::mode, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_MODE_OBJECT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_SURF, wmOperator::ptr, RNA_enum_get(), and Object::type.
Referenced by object_mode_set_exec().
static int object_mode_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 1428 of file object_edit.c.
References CTX_data_active_object(), Object::mode, NULL, OB_MODE_OBJECT, object_mode_op_string(), object_mode_set_compat(), OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, Object::restore_mode, RNA_boolean_get(), RNA_enum_get(), WM_OP_EXEC_REGION_WIN, and WM_operator_name_call().
Referenced by OBJECT_OT_mode_set().
static EnumPropertyItem* object_mode_set_itemsf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 1344 of file object_edit.c.
References CTX_data_active_object(), ListBase::first, EnumPropertyItem::identifier, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_EDIT, OB_MODE_OBJECT, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_SURF, object_mode_items, Object::particlesystem, RNA_enum_item_add(), RNA_enum_item_end(), Object::type, and EnumPropertyItem::value.
Referenced by OBJECT_OT_mode_set().
void OBJECT_OT_editmode_toggle (wmOperatorType * ot)
Definition at line 556 of file object_edit.c.
References wmOperatorType::description, editmode_toggle_exec(), editmode_toggle_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_forcefield_toggle (wmOperatorType * ot)
Definition at line 1082 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, forcefield_toggle_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_physics_copy (struct wmOperatorType * ot)
Definition at line 1793 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_physics_copy_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_clear (wmOperatorType * ot)
Definition at line 1688 of file object_edit.c.
References ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_clear_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_copy (wmOperatorType * ot)
Definition at line 1658 of file object_edit.c.
References ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_copy_exec(), gameprops_itemf(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, Object::prop, RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_new (wmOperatorType * ot)
Definition at line 1527 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_new(), gameproperty_type_items, GPROP_FLOAT, wmOperatorType::idname, MAX_NAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_game_property_remove (wmOperatorType * ot)
Definition at line 1568 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, game_property_remove(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_render_clear (wmOperatorType * ot)
Definition at line 253 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_render_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_render_set (wmOperatorType * ot)
Definition at line 290 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_render_set_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_view_clear (wmOperatorType * ot)
Definition at line 160 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_view_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_hide_view_set (wmOperatorType * ot)
Definition at line 215 of file object_edit.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_hide_view_set_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_logic_bricks_copy (wmOperatorType * ot)
Definition at line 1745 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, logicbricks_copy_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_mode_set (wmOperatorType * ot)
Definition at line 1460 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OB_MODE_OBJECT, object_mode_items, object_mode_set_exec(), object_mode_set_itemsf(), wmOperatorType::poll, Object::prop, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_paths_calculate (wmOperatorType * ot)
Definition at line 1149 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_calculate_paths_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_paths_clear (wmOperatorType * ot)
Definition at line 1193 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, object_clear_paths_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_object().
void OBJECT_OT_posemode_toggle (wmOperatorType * ot)
Definition at line 595 of file object_edit.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and posemode_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_shade_flat (wmOperatorType * ot)
Definition at line 1252 of file object_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shade_poll(), and shade_smooth_exec().
Referenced by ED_operatortypes_object().
void OBJECT_OT_shade_smooth (wmOperatorType * ot)
Definition at line 1267 of file object_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, shade_poll(), and shade_smooth_exec().
Referenced by ED_operatortypes_object().
static int posemode_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 575 of file object_edit.c.
References CTX_data_active_base(), CTX_data_edit_object(), ED_armature_enter_posemode(), ED_armature_exit_posemode(), ED_object_exit_editmode(), EM_DO_UNDO, EM_FREEDATA, Object::mode, OB_ARMATURE, OB_MODE_POSE, Base::object, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, and Object::type.
Referenced by OBJECT_OT_posemode_toggle().
static int pupmenu (const char * UNUSEDmsg) [static]
Definition at line 109 of file object_edit.c.
Referenced by BIF_selectOrientation(), copy_attr_menu(), and copymenu_properties().
static int shade_poll (bContext * C) [static]
Definition at line 1247 of file object_edit.c.
References ED_operator_editmesh(), and ED_operator_object_active_editable().
Referenced by OBJECT_OT_shade_flat(), and OBJECT_OT_shade_smooth().
static int shade_smooth_exec (bContext * C, wmOperator * op) [static]
Definition at line 1211 of file object_edit.c.
References clear(), CTX_DATA_BEGIN, CTX_DATA_END, DAG_id_tag_update(), ELEM, ListBase::first, Nurb::flag, wmOperator::idname, ME_SMOOTH, mesh_set_smooth_flag(), NC_OBJECT, ND_DRAW, Nurb::next, Curve::nurb, OB_CURVE, OB_MESH, OB_RECALC_DATA, OB_SURF, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by OBJECT_OT_shade_flat(), and OBJECT_OT_shade_smooth().
static void waitcursor (int UNUSEDval) [static]
Definition at line 108 of file object_edit.c.
Referenced by ED_object_enter_editmode(), and ED_object_exit_editmode().
Variable Documentation
EnumPropertyItem game_properties_copy_operations[] [static]
Initial value:
{
    {COPY_PROPERTIES_REPLACE, "REPLACE", 0, "Replace Properties", ""},
    {COPY_PROPERTIES_MERGE, "MERGE", 0, "Merge Properties", ""},
    {COPY_PROPERTIES_COPY, "COPY", 0, "Copy a Property", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 1589 of file object_edit.c.
EnumPropertyItem gameprops_items[] [static]
Initial value:
 {
    {0, NULL, 0, NULL, NULL}}
Definition at line 1595 of file object_edit.c.
Referenced by gameprops_itemf().