Blender: KX_ArmatureSensor Class Reference
KX_ArmatureSensor Class Reference
#include <KX_ArmatureSensor.h>
Public Member Functions
KX_ArmatureSensor (class SCA_EventManager *eventmgr, SCA_IObject *gameobj, const char *posechannel, const char *constraintname, int type, float value)
virtual ~KX_ArmatureSensor ()
virtual CValue * GetReplica ()
virtual void ReParent (SCA_IObject *parent)
virtual void Init ()
virtual bool Evaluate ()
virtual bool IsPositiveTrigger ()
void FindConstraint ()
Detailed Description
Definition at line 41 of file KX_ArmatureSensor.h.
Constructor & Destructor Documentation
KX_ArmatureSensor::KX_ArmatureSensor (class SCA_EventManager * eventmgr, SCA_IObject * gameobj, const char * posechannel, const char * constraintname, int type, float value)
Definition at line 46 of file KX_ArmatureSensor.cpp.
References FindConstraint().
Referenced by GetReplica().
KX_ArmatureSensor::~KX_ArmatureSensor () [virtual]
For property sensor, it is used to release the pre-calculated expression so that self references are removed before the sensor itself is released
Definition at line 120 of file KX_ArmatureSensor.cpp.
Member Function Documentation
bool KX_ArmatureSensor::Evaluate () [virtual]
Implements SCA_ISensor.
Definition at line 124 of file KX_ArmatureSensor.cpp.
References CONSTRAINT_OFF, bConstraint::flag, bConstraint::lin_error, SCA_ISensor::m_level, SCA_ISensor::m_reset, bConstraint::rot_error, SENS_ARM_LIN_ERROR_ABOVE, SENS_ARM_LIN_ERROR_BELOW, SENS_ARM_ROT_ERROR_ABOVE, SENS_ARM_ROT_ERROR_BELOW, and SENS_ARM_STATE_CHANGED.
void KX_ArmatureSensor::FindConstraint ()
Definition at line 69 of file KX_ArmatureSensor.cpp.
References bPose::chanbase, CONSTRAINT_DISABLE, bPoseChannel::constraints, ListBase::first, bConstraint::flag, SCA_IObject::GetGameObjectType(), BL_ArmatureObject::GetOrigPose(), SCA_ILogicBrick::m_gameobj, bPoseChannel::name, bConstraint::name, bPoseChannel::next, bConstraint::next, NULL, and SCA_IObject::OBJ_ARMATURE.
Referenced by KX_ArmatureSensor(), and ReParent().
CValue * KX_ArmatureSensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Definition at line 99 of file KX_ArmatureSensor.cpp.
References KX_ArmatureSensor(), and SCA_ISensor::ProcessReplica().
void KX_ArmatureSensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 62 of file KX_ArmatureSensor.cpp.
References SCA_ISensor::m_invert, and SCA_ISensor::m_reset.
bool KX_ArmatureSensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Definition at line 114 of file KX_ArmatureSensor.cpp.
References SCA_ISensor::m_invert.
void KX_ArmatureSensor::ReParent (SCA_IObject * parent) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 107 of file KX_ArmatureSensor.cpp.
References FindConstraint().
The documentation for this class was generated from the following files:
KX_ArmatureSensor.h
KX_ArmatureSensor.cpp