Blender: ntlTriangle Class Reference
ntlTriangle Class Reference
#include <ntl_ray.h>
Public Member Functions
ntlTriangle (void)
ntlTriangle (int *p, bool smooth, int obj, ntlVec3Gfx norm, int setflags)
ntlTriangle (const ntlTriangle &tri)
~ntlTriangle ()
int * getPoints (void)
bool getSmoothNormals (void) const
void setSmoothNormals (bool set)
int getObjectId (void) const
void setObjectId (int set)
ntlVec3Gfx getNormal (void) const
void setNormal (ntlVec3Gfx set)
int getFlags (void) const
void setFlags (int set)
int getLastRay (void) const
void setLastRay (int set)
int getBBoxId (void) const
void setBBoxId (int set)
gfxReal getAverage (int axis) const
Friends
bool operator< (const ntlTriangle &lhs, const ntlTriangle &rhs)
bool operator> (const ntlTriangle &lhs, const ntlTriangle &rhs)
Detailed Description
Definition at line 158 of file ntl_ray.h.
Constructor & Destructor Documentation
ntlTriangle::ntlTriangle (void) [inline]
Default constructor
Definition at line 236 of file ntl_ray.h.
ntlTriangle::ntlTriangle (int * p, bool smooth, int obj, ntlVec3Gfx norm, int setflags) [inline]
Constructor with parameters
Definition at line 251 of file ntl_ray.h.
References norm(), and smooth().
ntlTriangle::ntlTriangle (const ntlTriangle & tri) [inline]
Copy - Constructor
Definition at line 268 of file ntl_ray.h.
ntlTriangle::~ntlTriangle () [inline]
Destructor
Definition at line 169 of file ntl_ray.h.
Member Function Documentation
gfxReal ntlTriangle::getAverage (int axis) const [inline]
Get average of the three points for this axis
Definition at line 295 of file ntl_ray.h.
References globalSortingPoints.
Referenced by lessTriangleAverage(), operator<(), and operator>().
int ntlTriangle::getBBoxId (void) const [inline]
Acces bbox id
Definition at line 191 of file ntl_ray.h.
Referenced by ntlTree::checkAABBTriangle().
int ntlTriangle::getFlags (void) const [inline]
Acces flags
Definition at line 185 of file ntl_ray.h.
int ntlTriangle::getLastRay (void) const [inline]
Access last intersection ray ID
Definition at line 188 of file ntl_ray.h.
ntlVec3Gfx ntlTriangle::getNormal (void) const [inline]
Acces normal index
Definition at line 182 of file ntl_ray.h.
Referenced by ntlRay::shade().
int ntlTriangle::getObjectId (void) const [inline]
Access object
Definition at line 179 of file ntl_ray.h.
Referenced by ControlParticles::checkPointInside(), LbmSolverInterface::geoInitCheckPointInside(), and ntlRay::shade().
int* ntlTriangle::getPoints (void) [inline]
Acces to points of triangle
Definition at line 174 of file ntl_ray.h.
Referenced by IsoSurface::getTriangles(), ntlTree::intersect(), ntlRay::intersectTriangle(), ntlRay::intersectTriangleBack(), ntlRay::intersectTriangleFront(), ntlRay::intersectTriangleX(), ntlTree::intersectX(), ntlGeometryObject::sceneAddTriangle(), and ntlGeometryObject::sceneAddTriangleNoVert().
bool ntlTriangle::getSmoothNormals (void) const [inline]
Acces normal smoothing
Definition at line 176 of file ntl_ray.h.
void ntlTriangle::setBBoxId (int set) [inline]
Definition at line 192 of file ntl_ray.h.
void ntlTriangle::setFlags (int set) [inline]
Definition at line 186 of file ntl_ray.h.
Referenced by IsoSurface::getTriangles(), ntlGeometryObject::sceneAddTriangle(), and ntlGeometryObject::sceneAddTriangleNoVert().
void ntlTriangle::setLastRay (int set) [inline]
Definition at line 189 of file ntl_ray.h.
void ntlTriangle::setNormal (ntlVec3Gfx set) [inline]
Definition at line 183 of file ntl_ray.h.
Referenced by IsoSurface::getTriangles(), ntlGeometryObject::sceneAddTriangle(), and ntlGeometryObject::sceneAddTriangleNoVert().
void ntlTriangle::setObjectId (int set) [inline]
Definition at line 180 of file ntl_ray.h.
Referenced by IsoSurface::getTriangles(), ntlGeometryObject::sceneAddTriangle(), and ntlGeometryObject::sceneAddTriangleNoVert().
void ntlTriangle::setSmoothNormals (bool set) [inline]
Definition at line 177 of file ntl_ray.h.
Referenced by IsoSurface::getTriangles(), ntlGeometryObject::sceneAddTriangle(), and ntlGeometryObject::sceneAddTriangleNoVert().
Friends And Related Function Documentation
bool operator< (const ntlTriangle & lhs, const ntlTriangle & rhs) [friend]
operator < for sorting, uses global sorting axis
Definition at line 302 of file ntl_ray.h.
bool operator> (const ntlTriangle & lhs, const ntlTriangle & rhs) [friend]
operator > for sorting, uses global sorting axis
Definition at line 308 of file ntl_ray.h.
The documentation for this class was generated from the following file:
ntl_ray.h