Blender: KX_GameObject.cpp File Reference
KX_GameObject.cpp File Reference
Ketsji
#include "RAS_IPolygonMaterial.h"
#include "KX_BlenderMaterial.h"
#include "KX_GameObject.h"
#include "KX_Camera.h"
#include "KX_Light.h"
#include "KX_FontObject.h"
#include "RAS_MeshObject.h"
#include "KX_MeshProxy.h"
#include "KX_PolyProxy.h"
#include <stdio.h>
#include "SG_Controller.h"
#include "KX_IPhysicsController.h"
#include "PHY_IGraphicController.h"
#include "SG_Node.h"
#include "KX_ClientObjectInfo.h"
#include "RAS_BucketManager.h"
#include "KX_RayCast.h"
#include "KX_PythonInit.h"
#include "KX_PyMath.h"
#include "KX_PythonSeq.h"
#include "KX_ConvertPhysicsObject.h"
#include "SCA_IActuator.h"
#include "SCA_ISensor.h"
#include "SCA_IController.h"
#include "NG_NetworkScene.h"
#include "KX_ObstacleSimulation.h"
#include "BL_ActionManager.h"
#include "PyObjectPlus.h"
#include "KX_SG_NodeRelationships.h"
#include "BLI_math.h"
Defines
#define KX_INERTIA_INFINITE 10000
Typedefs
typedef unsigned long uint_ptr
Functions
static void setGraphicController_recursive (SG_Node *node)
static void UpdateBuckets_recursive (SG_Node *node)
static void setVisible_recursive (SG_Node *node, bool v)
static void setOccluder_recursive (SG_Node *node, bool v)
static void walk_children (SG_Node *node, CListValue *list, bool recursive)
Variables
static MT_Point3 dummy_point = MT_Point3(0.0, 0.0, 0.0)
static MT_Vector3 dummy_scaling = MT_Vector3(1.0, 1.0, 1.0)
static MT_Matrix3x3 dummy_orientation
Detailed Description
Definition in file KX_GameObject.cpp.
Define Documentation
#define KX_INERTIA_INFINITE 10000
Definition at line 47 of file KX_GameObject.cpp.
Typedef Documentation
typedef unsigned long uint_ptr
Definition at line 37 of file KX_GameObject.cpp.
Function Documentation
static void setGraphicController_recursive (SG_Node * node) [static]
Definition at line 454 of file KX_GameObject.cpp.
References KX_GameObject::ActivateGraphicController(), SG_Node::GetSGChildren(), and NULL.
Referenced by KX_GameObject::ActivateGraphicController().
static void setOccluder_recursive (SG_Node * node, bool v) [static]
Definition at line 816 of file KX_GameObject.cpp.
References SG_Node::GetSGChildren(), NULL, and KX_GameObject::SetOccluder().
Referenced by KX_GameObject::SetOccluder().
static void setVisible_recursive (SG_Node * node, bool v) [static]
Definition at line 783 of file KX_GameObject.cpp.
References SG_Node::GetSGChildren(), NULL, and KX_GameObject::SetVisible().
Referenced by KX_GameObject::SetVisible().
static void UpdateBuckets_recursive (SG_Node * node) [static]
Definition at line 598 of file KX_GameObject.cpp.
References SG_Node::GetSGChildren(), NULL, and KX_GameObject::UpdateBuckets().
Referenced by KX_GameObject::UpdateBuckets().
static void walk_children (SG_Node * node, CListValue * list, bool recursive) [static]
Definition at line 1303 of file KX_GameObject.cpp.
References CListValue::Add(), CValue::AddRef(), SG_Node::GetSGChildren(), SG_IObject::GetSGClientObject(), and NULL.
Referenced by KX_GameObject::GetChildren(), and KX_GameObject::GetChildrenRecursive().
Variable Documentation
MT_Matrix3x3 dummy_orientation [static]
Initial value:
 MT_Matrix3x3(1.0, 0.0, 0.0,
                                                     0.0, 1.0, 0.0,
                                                     0.0, 0.0, 1.0)
Definition at line 89 of file KX_GameObject.cpp.
Referenced by KX_GameObject::NodeGetLocalOrientation(), and KX_GameObject::NodeGetWorldOrientation().
MT_Point3 dummy_point = MT_Point3(0.0, 0.0, 0.0) [static]
Definition at line 87 of file KX_GameObject.cpp.
Referenced by KX_GameObject::NodeGetLocalPosition(), and KX_GameObject::NodeGetWorldPosition().
MT_Vector3 dummy_scaling = MT_Vector3(1.0, 1.0, 1.0) [static]
Definition at line 88 of file KX_GameObject.cpp.
Referenced by KX_GameObject::NodeGetLocalScaling(), and KX_GameObject::NodeGetWorldScaling().