Blender: noise.c File Reference
noise.c File Reference
blenlib
#include <math.h>
#include "BLI_noise.h"
Defines
#define HASHVEC(x, y, z) hashvectf+3*hash[ (hash[ (hash[(z) & 255]+(y)) & 255]+(x)) & 255]
#define HASHPNT(x, y, z) hashpntf+3*hash[ (hash[ (hash[(z) & 255]+(y)) & 255]+(x)) & 255]
#define SETUP(val, b0, b1, r0, r1)
#define VALUE_AT(rx, ry, rz) (rx * q[0] + ry * q[1] + rz * q[2])
#define SURVE(t) (t * t * (3.0f - 2.0f * t))
Functions
static float noise3_perlin (float vec[3])
static float lerp (float t, float a, float b)
static float npfade (float t)
static float grad (int hash, float x, float y, float z)
static float newPerlin (float x, float y, float z)
static float newPerlinU (float x, float y, float z)
static float orgBlenderNoise (float x, float y, float z)
static float orgBlenderNoiseS (float x, float y, float z)
float BLI_hnoise (float noisesize, float x, float y, float z)
float BLI_turbulence (float noisesize, float x, float y, float z, int nr)
float BLI_turbulence1 (float noisesize, float x, float y, float z, int nr)
static float orgPerlinNoise (float x, float y, float z)
static float orgPerlinNoiseU (float x, float y, float z)
float BLI_hnoisep (float noisesize, float x, float y, float z)
static float dist_Squared (float x, float y, float z, float e)
static float dist_Real (float x, float y, float z, float e)
static float dist_Manhattan (float x, float y, float z, float e)
static float dist_Chebychev (float x, float y, float z, float e)
static float dist_MinkovskyH (float x, float y, float z, float e)
static float dist_Minkovsky4 (float x, float y, float z, float e)
static float dist_Minkovsky (float x, float y, float z, float e)
void voronoi (float x, float y, float z, float *da, float *pa, float me, int dtype)
static float voronoi_F1 (float x, float y, float z)
static float voronoi_F2 (float x, float y, float z)
static float voronoi_F3 (float x, float y, float z)
static float voronoi_F4 (float x, float y, float z)
static float voronoi_F1F2 (float x, float y, float z)
static float voronoi_Cr (float x, float y, float z)
static float voronoi_F1S (float x, float y, float z)
static float voronoi_F2S (float x, float y, float z)
static float voronoi_F3S (float x, float y, float z)
static float voronoi_F4S (float x, float y, float z)
static float voronoi_F1F2S (float x, float y, float z)
static float voronoi_CrS (float x, float y, float z)
static float cellNoiseU (float x, float y, float z)
float cellNoise (float x, float y, float z)
void cellNoiseV (float x, float y, float z, float *ca)
float BLI_gNoise (float noisesize, float x, float y, float z, int hard, int noisebasis)
float BLI_gTurbulence (float noisesize, float x, float y, float z, int oct, int hard, int noisebasis)
float mg_fBm (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
float mg_MultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
float mg_HeteroTerrain (float x, float y, float z, float H, float lacunarity, float octaves, float offset, int noisebasis)
float mg_HybridMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
float mg_RidgedMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
float mg_VLNoise (float x, float y, float z, float distortion, int nbas1, int nbas2)
Variables
static float hashpntf [768]
unsigned char hash [512]
float hashvectf [768]
static char p [512+2]
static float g [512+2][3]
Detailed Description
Definition in file noise.c.
Define Documentation
#define HASHPNT (x, y, z) hashpntf+3*hash[ (hash[ (hash[(z) & 255]+(y)) & 255]+(x)) & 255]
Definition at line 53 of file noise.c.
Referenced by cellNoiseV(), and voronoi().
#define HASHVEC (x, y, z) hashvectf+3*hash[ (hash[ (hash[(z) & 255]+(y)) & 255]+(x)) & 255]
Definition at line 50 of file noise.c.
#define SETUP (val, b0, b1, r0, r1)
Value:
{                                                                         \
        t = val + 10000.0f;                                                   \
        b0 = ((int)t) & 255;                                                  \
        b1 = (b0 + 1) & 255;                                                  \
        r0 = t - floorf(t);                                                   \
        r1 = r0 - 1.0f;                                                       \
    }
Definition at line 922 of file noise.c.
Referenced by noise3_perlin().
#define SURVE (t) (t * t * (3.0f - 2.0f * t))
Referenced by noise3_perlin().
#define VALUE_AT (rx, ry, rz) (rx * q[0] + ry * q[1] + rz * q[2])
Referenced by noise3_perlin().
Function Documentation
float BLI_gNoise (float noisesize, float x, float y, float z, int hard, int noisebasis)
Definition at line 1319 of file noise.c.
References cellNoiseU(), fabsf, newPerlinU(), orgBlenderNoise(), orgPerlinNoiseU(), voronoi_Cr(), voronoi_F1(), voronoi_F1F2(), voronoi_F2(), voronoi_F3(), and voronoi_F4().
Referenced by M_Noise_noise(), noise_vector(), stucci(), turb(), and wood_int().
float BLI_gTurbulence (float noisesize, float x, float y, float z, int oct, int hard, int noisebasis)
Definition at line 1373 of file noise.c.
References cellNoiseU(), fabsf, i, newPerlinU(), orgBlenderNoise(), orgPerlinNoiseU(), sum(), voronoi_Cr(), voronoi_F1(), voronoi_F1F2(), voronoi_F2(), voronoi_F3(), and voronoi_F4().
Referenced by alter_co(), clouds(), do_physical_effector(), do_rough(), marble_int(), and pointdensitytex().
float BLI_hnoise (float noisesize, float x, float y, float z)
Definition at line 346 of file noise.c.
References orgBlenderNoise().
Referenced by BLI_turbulence(), BLI_turbulence1(), edbm_noise_exec(), and hnoise().
float BLI_hnoisep (float noisesize, float x, float y, float z)
Definition at line 1039 of file noise.c.
References noise3_perlin().
Referenced by hnoisep().
float BLI_turbulence (float noisesize, float x, float y, float z, int nr)
Definition at line 357 of file noise.c.
References BLI_hnoise(), and div.
Referenced by fcm_noise_evaluate(), and turbulence().
float BLI_turbulence1 (float noisesize, float x, float y, float z, int nr)
Definition at line 374 of file noise.c.
References BLI_hnoise(), div, and fabsf.
Referenced by turbulence1().
float cellNoise (float x, float y, float z)
Definition at line 1296 of file noise.c.
References cellNoiseU().
Referenced by M_Noise_cell(), mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), and mg_VLNoise().
static float cellNoiseU (float x, float y, float z) [static]
Definition at line 1285 of file noise.c.
Referenced by BLI_gNoise(), BLI_gTurbulence(), and cellNoise().
void cellNoiseV (float x, float y, float z, float * ca)
Definition at line 1302 of file noise.c.
References HASHPNT.
Referenced by M_Noise_cell_vector(), and voronoiTex().
static float dist_Chebychev (float x, float y, float z, float e) [static]
Definition at line 1077 of file noise.c.
References fabsf.
Referenced by voronoi().
static float dist_Manhattan (float x, float y, float z, float e) [static]
Definition at line 1075 of file noise.c.
References fabsf.
Referenced by voronoi().
static float dist_Minkovsky (float x, float y, float z, float e) [static]
Definition at line 1108 of file noise.c.
References fabsf, and powf.
Referenced by voronoi().
static float dist_Minkovsky4 (float x, float y, float z, float e) [static]
Definition at line 1098 of file noise.c.
References sqrtf.
Referenced by voronoi().
static float dist_MinkovskyH (float x, float y, float z, float e) [static]
Definition at line 1090 of file noise.c.
References fabsf, and sqrtf.
Referenced by voronoi().
static float dist_Real (float x, float y, float z, float e) [static]
Definition at line 1073 of file noise.c.
References sqrtf.
Referenced by voronoi().
static float dist_Squared (float x, float y, float z, float e) [static]
Definition at line 1071 of file noise.c.
Referenced by voronoi().
static float grad (int hash, float x, float y, float z) [static]
Definition at line 218 of file noise.c.
Referenced by newPerlin().
static float lerp (float t, float a, float b) [static]
Definition at line 208 of file noise.c.
Referenced by ATTRIBUTE_ALIGNED16(), BVHBuild::build_node(), btSoftBodyHelpers::CreatePatch(), btSoftBodyHelpers::CreatePatchUV(), btSoftBodyHelpers::CreateRope(), interpolateToi(), newPerlin(), noise3_perlin(), and BVHBuild::split_reference().
float mg_fBm (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
Definition at line 1449 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_fractal(), and mg_mFractalOrfBmTex().
float mg_HeteroTerrain (float x, float y, float z, float H, float lacunarity, float octaves, float offset, int noisebasis)
Definition at line 1583 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_hetero_terrain(), and mg_HTerrainTex().
float mg_HybridMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
Definition at line 1656 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_hybrid_multi_fractal(), and mg_ridgedOrHybridMFTex().
float mg_MultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, int noisebasis)
Definition at line 1519 of file noise.c.
References cellNoise(), floorf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_multi_fractal(), and mg_mFractalOrfBmTex().
float mg_RidgedMultiFractal (float x, float y, float z, float H, float lacunarity, float octaves, float offset, float gain, int noisebasis)
Definition at line 1731 of file noise.c.
References cellNoise(), fabsf, i, newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), powf, voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_ridged_multi_fractal(), and mg_ridgedOrHybridMFTex().
float mg_VLNoise (float x, float y, float z, float distortion, int nbas1, int nbas2)
Definition at line 1797 of file noise.c.
References cellNoise(), newPerlin(), orgBlenderNoiseS(), orgPerlinNoise(), voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
Referenced by M_Noise_variable_lacunarity(), and mg_distNoiseTex().
static float newPerlin (float x, float y, float z) [static]
Definition at line 227 of file noise.c.
References A, B, grad(), hash, lerp(), npfade(), and X.
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), mg_VLNoise(), and newPerlinU().
static float newPerlinU (float x, float y, float z) [static]
Definition at line 251 of file noise.c.
References newPerlin().
Referenced by BLI_gNoise(), and BLI_gTurbulence().
static float noise3_perlin (float vec[3]) [static]
Definition at line 932 of file noise.c.
References g, i, lerp(), p, SETUP, SURVE, and VALUE_AT.
Referenced by BLI_hnoisep(), orgPerlinNoise(), and orgPerlinNoiseU().
static float npfade (float t) [static]
Definition at line 213 of file noise.c.
Referenced by newPerlin().
static float orgBlenderNoise (float x, float y, float z) [static]
Definition at line 262 of file noise.c.
References hash, hashvectf, and i.
Referenced by BLI_gNoise(), BLI_gTurbulence(), BLI_hnoise(), and orgBlenderNoiseS().
static float orgBlenderNoiseS (float x, float y, float z) [static]
Definition at line 340 of file noise.c.
References orgBlenderNoise().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), and mg_VLNoise().
static float orgPerlinNoise (float x, float y, float z) [static]
Definition at line 1016 of file noise.c.
References noise3_perlin().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), and mg_VLNoise().
static float orgPerlinNoiseU (float x, float y, float z) [static]
Definition at line 1027 of file noise.c.
References noise3_perlin().
Referenced by BLI_gNoise(), and BLI_gTurbulence().
void voronoi (float x, float y, float z, float * da, float * pa, float me, int dtype)
Definition at line 1116 of file noise.c.
References dist_Chebychev(), dist_Manhattan(), dist_Minkovsky(), dist_Minkovsky4(), dist_MinkovskyH(), dist_Real(), dist_Squared(), HASHPNT, and p.
Referenced by add_node(), M_Noise_voronoi(), svm_voronoi(), voronoi_F1(), voronoi_F1F2(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2(), voronoi_F2S(), voronoi_F3(), voronoi_F3S(), voronoi_F4(), voronoi_F4S(), voronoi_Fn(), voronoi_FnFn(), voronoiTex(), and xml_read_shader_graph().
static float voronoi_Cr (float x, float y, float z) [static]
Definition at line 1222 of file noise.c.
References voronoi_F1F2().
Referenced by BLI_gNoise(), BLI_gTurbulence(), and voronoi_CrS().
static float voronoi_CrS (float x, float y, float z) [static]
Definition at line 1268 of file noise.c.
References voronoi_F1F2().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), mg_VLNoise(), and noise_basis().
static float voronoi_F1 (float x, float y, float z) [static]
Definition at line 1186 of file noise.c.
References voronoi().
Referenced by BLI_gNoise(), BLI_gTurbulence(), and voronoi_F1S().
static float voronoi_F1F2 (float x, float y, float z) [static]
Definition at line 1214 of file noise.c.
References voronoi().
Referenced by BLI_gNoise(), BLI_gTurbulence(), voronoi_Cr(), voronoi_CrS(), and voronoi_F1F2S().
static float voronoi_F1F2S (float x, float y, float z) [static]
Definition at line 1260 of file noise.c.
References voronoi().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), mg_VLNoise(), and noise_basis().
static float voronoi_F1S (float x, float y, float z) [static]
Definition at line 1232 of file noise.c.
References voronoi().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), mg_VLNoise(), and noise_basis().
static float voronoi_F2 (float x, float y, float z) [static]
Definition at line 1193 of file noise.c.
References voronoi().
Referenced by BLI_gNoise(), BLI_gTurbulence(), and voronoi_F2S().
static float voronoi_F2S (float x, float y, float z) [static]
Definition at line 1239 of file noise.c.
References voronoi().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), mg_VLNoise(), and noise_basis().
static float voronoi_F3 (float x, float y, float z) [static]
Definition at line 1200 of file noise.c.
References voronoi().
Referenced by BLI_gNoise(), BLI_gTurbulence(), and voronoi_F3S().
static float voronoi_F3S (float x, float y, float z) [static]
Definition at line 1246 of file noise.c.
References voronoi().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), mg_VLNoise(), and noise_basis().
static float voronoi_F4 (float x, float y, float z) [static]
Definition at line 1207 of file noise.c.
References voronoi().
Referenced by BLI_gNoise(), BLI_gTurbulence(), and voronoi_F4S().
static float voronoi_F4S (float x, float y, float z) [static]
Definition at line 1253 of file noise.c.
References voronoi().
Referenced by mg_fBm(), mg_HeteroTerrain(), mg_HybridMultiFractal(), mg_MultiFractal(), mg_RidgedMultiFractal(), mg_VLNoise(), and noise_basis().
Variable Documentation
float g[512+2][3] [static]
Definition at line 405 of file noise.c.
Referenced by add_filt_fmask(), add_filt_fmask_coord(), BKE_image_buf_fill_checker(), BKE_tracking_disable_imbuf_channels(), BLF_buffer_col(), blf_font_boundbox(), blf_font_buffer(), blf_font_draw(), blf_font_draw_ascii(), blf_font_ensure_ascii_table(), blf_font_fixed_width(), blf_glyph_add(), blf_glyph_cache_clear(), blf_glyph_cache_free(), BLF_shadow(), Blinn_Spec(), cellnoise_color(), checker_board_color_fill(), GPC_Canvas::ClearColor(), constrain_rgb(), cp_shade_color3ub(), do_comb_hsva(), do_comb_ycca_601(), do_comb_ycca_709(), do_comb_ycca_jfif(), do_comb_yuva(), draw_zebra_byte(), draw_zebra_float(), dynamicPaint_setInitialColor(), Eigenorthes(), Eigentql2(), Eigentred2(), fresnel(), fresnel_dielectric(), fresnel_dielectric_cos(), GenerateTSpaces(), gpu_draw_buffers_legacy_grids(), GPU_extensions_init(), hsv_to_cpack(), BasicVector::hsvToRgb(), hsvToRgb(), ibJpegImageFromCinfo(), image_invert_exec(), IMB_half_x(), IMB_half_y(), imb_save_openexr_half(), integrate_overlap(), layerEqual_mloopcol(), layerInterp_mcol(), layerInterp_mloopcol(), make_transform(), multires_output_hidden_to_ccgdm(), node_socket_set_default_value_rgba(), noise3_perlin(), partialvis_update_grids(), py_blf_shadow(), KX_BlenderSceneConverter::ResetPhysicsObjectsAnimationIpo(), rgb_to_hsv(), rgb_to_ycc(), rgba_char_args_set(), rgba_char_args_test_set(), BlenderWorldInfo::setBackColor(), RAS_OpenGLRasterizer::SetFog(), RAS_OpenGLRasterizer::SetFogColor(), KX_KetsjiEngine::SetOverrideFrameColor(), TNT::SVD(), KDL::svd_eigen_HH(), svd_m4(), svm_node_convert(), svm_node_rgb_curves(), KX_BlenderSceneConverter::TestHandlesPhysicsObjectToAnimationIpo(), transformc(), UI_ColorPtrBlendShade3ubv(), UI_GetColorPtrBlendShade3ubv(), UI_GetColorPtrShade3ubv(), UI_GetThemeColorShade3fv(), UI_ThemeColorBlend(), UI_ThemeColorBlendShade(), UI_ThemeColorBlendShadeAlpha(), UI_ThemeColorShade(), UI_ThemeColorShadeAlpha(), vectorscope_put_cross(), vol_get_phasefunc(), KX_BlenderSceneConverter::WritePhysicsObjectToAnimationIpo(), ycc_to_rgb(), and yuv_to_rgb().
unsigned char hash[512]
Initial value:
 {
0xA2,0xA0,0x19,0x3B,0xF8,0xEB,0xAA,0xEE,0xF3,0x1C,0x67,0x28,0x1D,0xED,0x0,0xDE,0x95,0x2E,0xDC,0x3F,0x3A,0x82,0x35,0x4D,0x6C,0xBA,0x36,0xD0,0xF6,0xC,0x79,0x32,0xD1,0x59,0xF4,0x8,0x8B,0x63,0x89,0x2F,0xB8,0xB4,0x97,0x83,0xF2,0x8F,0x18,0xC7,0x51,0x14,0x65,0x87,0x48,0x20,0x42,0xA8,0x80,0xB5,0x40,0x13,0xB2,0x22,0x7E,0x57,
0xBC,0x7F,0x6B,0x9D,0x86,0x4C,0xC8,0xDB,0x7C,0xD5,0x25,0x4E,0x5A,0x55,0x74,0x50,0xCD,0xB3,0x7A,0xBB,0xC3,0xCB,0xB6,0xE2,0xE4,0xEC,0xFD,0x98,0xB,0x96,0xD3,0x9E,0x5C,0xA1,0x64,0xF1,0x81,0x61,0xE1,0xC4,0x24,0x72,0x49,0x8C,0x90,0x4B,0x84,0x34,0x38,0xAB,0x78,0xCA,0x1F,0x1,0xD7,0x93,0x11,0xC1,0x58,0xA9,0x31,0xF9,0x44,0x6D,
0xBF,0x33,0x9C,0x5F,0x9,0x94,0xA3,0x85,0x6,0xC6,0x9A,0x1E,0x7B,0x46,0x15,0x30,0x27,0x2B,0x1B,0x71,0x3C,0x5B,0xD6,0x6F,0x62,0xAC,0x4F,0xC2,0xC0,0xE,0xB1,0x23,0xA7,0xDF,0x47,0xB0,0x77,0x69,0x5,0xE9,0xE6,0xE7,0x76,0x73,0xF,0xFE,0x6E,0x9B,0x56,0xEF,0x12,0xA5,0x37,0xFC,0xAE,0xD9,0x3,0x8E,0xDD,0x10,0xB9,0xCE,0xC9,0x8D,
0xDA,0x2A,0xBD,0x68,0x17,0x9F,0xBE,0xD4,0xA,0xCC,0xD2,0xE8,0x43,0x3D,0x70,0xB7,0x2,0x7D,0x99,0xD8,0xD,0x60,0x8A,0x4,0x2C,0x3E,0x92,0xE5,0xAF,0x53,0x7,0xE0,0x29,0xA6,0xC5,0xE3,0xF5,0xF7,0x4A,0x41,0x26,0x6A,0x16,0x5E,0x52,0x2D,0x21,0xAD,0xF0,0x91,0xFF,0xEA,0x54,0xFA,0x66,0x1A,0x45,0x39,0xCF,0x75,0xA4,0x88,0xFB,0x5D,
0xA2,0xA0,0x19,0x3B,0xF8,0xEB,0xAA,0xEE,0xF3,0x1C,0x67,0x28,0x1D,0xED,0x0,0xDE,0x95,0x2E,0xDC,0x3F,0x3A,0x82,0x35,0x4D,0x6C,0xBA,0x36,0xD0,0xF6,0xC,0x79,0x32,0xD1,0x59,0xF4,0x8,0x8B,0x63,0x89,0x2F,0xB8,0xB4,0x97,0x83,0xF2,0x8F,0x18,0xC7,0x51,0x14,0x65,0x87,0x48,0x20,0x42,0xA8,0x80,0xB5,0x40,0x13,0xB2,0x22,0x7E,0x57,
0xBC,0x7F,0x6B,0x9D,0x86,0x4C,0xC8,0xDB,0x7C,0xD5,0x25,0x4E,0x5A,0x55,0x74,0x50,0xCD,0xB3,0x7A,0xBB,0xC3,0xCB,0xB6,0xE2,0xE4,0xEC,0xFD,0x98,0xB,0x96,0xD3,0x9E,0x5C,0xA1,0x64,0xF1,0x81,0x61,0xE1,0xC4,0x24,0x72,0x49,0x8C,0x90,0x4B,0x84,0x34,0x38,0xAB,0x78,0xCA,0x1F,0x1,0xD7,0x93,0x11,0xC1,0x58,0xA9,0x31,0xF9,0x44,0x6D,
0xBF,0x33,0x9C,0x5F,0x9,0x94,0xA3,0x85,0x6,0xC6,0x9A,0x1E,0x7B,0x46,0x15,0x30,0x27,0x2B,0x1B,0x71,0x3C,0x5B,0xD6,0x6F,0x62,0xAC,0x4F,0xC2,0xC0,0xE,0xB1,0x23,0xA7,0xDF,0x47,0xB0,0x77,0x69,0x5,0xE9,0xE6,0xE7,0x76,0x73,0xF,0xFE,0x6E,0x9B,0x56,0xEF,0x12,0xA5,0x37,0xFC,0xAE,0xD9,0x3,0x8E,0xDD,0x10,0xB9,0xCE,0xC9,0x8D,
0xDA,0x2A,0xBD,0x68,0x17,0x9F,0xBE,0xD4,0xA,0xCC,0xD2,0xE8,0x43,0x3D,0x70,0xB7,0x2,0x7D,0x99,0xD8,0xD,0x60,0x8A,0x4,0x2C,0x3E,0x92,0xE5,0xAF,0x53,0x7,0xE0,0x29,0xA6,0xC5,0xE3,0xF5,0xF7,0x4A,0x41,0x26,0x6A,0x16,0x5E,0x52,0x2D,0x21,0xAD,0xF0,0x91,0xFF,0xEA,0x54,0xFA,0x66,0x1A,0x45,0x39,0xCF,0x75,0xA4,0x88,0xFB,0x5D,
}
Definition at line 165 of file noise.c.
Referenced by _ehash_insert(), _ehash_lookup(), _ehash_lookupWithPrev(), BLI_edgehash_insert(), BLI_edgehash_lookup_p(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_remove(), BLI_ghashutil_pairhash(), BLI_smallhash_iternew(), BLI_thread_srandom(), BM_edge_split(), bmo_bevel_exec(), bmo_triangle_fill_exec(), btAdjustInternalEdgeContacts(), btGetHash(), btHashString::btHashString(), cage_mapped_verts_callback(), cellnoise(), ED_mesh_mirrtopo_init(), btHashMap< btHashPtr, btPointerUid >::findIndex(), btHashedOverlappingPairCache::findPair(), CacheData::get_filename(), HsiehHash(), btHashMap< btHashPtr, btPointerUid >::insert(), knife_find_line_hits(), make_edges_mdata(), mirrtopo_vert_sort(), newPerlin(), orgBlenderNoise(), path_files_md5_hash(), perlin(), phash(), phash_insert(), phash_lookup(), phash_next(), btConnectivityProcessor::processTriangle(), PyC_FlagSet_ToBitfield(), pyrna_set_to_enum_bitfield(), RE_make_stars(), btHashMap< btHashPtr, btPointerUid >::remove(), btHashedOverlappingPairCache::removeOverlappingPair(), rng_srandom(), rotsys_fill_faces(), sb_detect_aabb_collisionCached(), sb_detect_edge_collisionCached(), sb_detect_face_collisionCached(), sb_detect_face_pointCached(), sb_detect_vertex_collisionCached(), ui_popup_menu_memory(), and ui_popup_string_hash().
float hashpntf[768] [static]
Definition at line 54 of file noise.c.
float hashvectf[768]
Initial value:
 {
0.33783,0.715698,-0.611206,-0.944031,-0.326599,-0.045624,-0.101074,-0.416443,-0.903503,0.799286,0.49411,-0.341949,-0.854645,0.518036,0.033936,0.42514,-0.437866,-0.792114,-0.358948,0.597046,0.717377,-0.985413,0.144714,0.089294,-0.601776,-0.33728,-0.723907,-0.449921,0.594513,0.666382,0.208313,-0.10791,
0.972076,0.575317,0.060425,0.815643,0.293365,-0.875702,-0.383453,0.293762,0.465759,0.834686,-0.846008,-0.233398,-0.47934,-0.115814,0.143036,-0.98291,0.204681,-0.949036,-0.239532,0.946716,-0.263947,0.184326,-0.235596,0.573822,0.784332,0.203705,-0.372253,-0.905487,0.756989,-0.651031,0.055298,0.497803,
0.814697,-0.297363,-0.16214,0.063995,-0.98468,-0.329254,0.834381,0.441925,0.703827,-0.527039,-0.476227,0.956421,0.266113,0.119781,0.480133,0.482849,0.7323,-0.18631,0.961212,-0.203125,-0.748474,-0.656921,-0.090393,-0.085052,-0.165253,0.982544,-0.76947,0.628174,-0.115234,0.383148,0.537659,0.751068,
0.616486,-0.668488,-0.415924,-0.259979,-0.630005,0.73175,0.570953,-0.087952,0.816223,-0.458008,0.023254,0.888611,-0.196167,0.976563,-0.088287,-0.263885,-0.69812,-0.665527,0.437134,-0.892273,-0.112793,-0.621674,-0.230438,0.748566,0.232422,0.900574,-0.367249,0.22229,-0.796143,0.562744,-0.665497,-0.73764,
0.11377,0.670135,0.704803,0.232605,0.895599,0.429749,-0.114655,-0.11557,-0.474243,0.872742,0.621826,0.604004,-0.498444,-0.832214,0.012756,0.55426,-0.702484,0.705994,-0.089661,-0.692017,0.649292,0.315399,-0.175995,-0.977997,0.111877,0.096954,-0.04953,0.994019,0.635284,-0.606689,-0.477783,-0.261261,
-0.607422,-0.750153,0.983276,0.165436,0.075958,-0.29837,0.404083,-0.864655,-0.638672,0.507721,0.578156,0.388214,0.412079,0.824249,0.556183,-0.208832,0.804352,0.778442,0.562012,0.27951,-0.616577,0.781921,-0.091522,0.196289,0.051056,0.979187,-0.121216,0.207153,-0.970734,-0.173401,-0.384735,0.906555,
0.161499,-0.723236,-0.671387,0.178497,-0.006226,-0.983887,-0.126038,0.15799,0.97934,0.830475,-0.024811,0.556458,-0.510132,-0.76944,0.384247,0.81424,0.200104,-0.544891,-0.112549,-0.393311,-0.912445,0.56189,0.152222,-0.813049,0.198914,-0.254517,-0.946381,-0.41217,0.690979,-0.593811,-0.407257,0.324524,
0.853668,-0.690186,0.366119,-0.624115,-0.428345,0.844147,-0.322296,-0.21228,-0.297546,-0.930756,-0.273071,0.516113,0.811798,0.928314,0.371643,0.007233,0.785828,-0.479218,-0.390778,-0.704895,0.058929,0.706818,0.173248,0.203583,0.963562,0.422211,-0.904297,-0.062469,-0.363312,-0.182465,0.913605,0.254028,
-0.552307,-0.793945,-0.28891,-0.765747,-0.574554,0.058319,0.291382,0.954803,0.946136,-0.303925,0.111267,-0.078156,0.443695,-0.892731,0.182098,0.89389,0.409515,-0.680298,-0.213318,0.701141,0.062469,0.848389,-0.525635,-0.72879,-0.641846,0.238342,-0.88089,0.427673,0.202637,-0.532501,-0.21405,0.818878,
0.948975,-0.305084,0.07962,0.925446,0.374664,0.055817,0.820923,0.565491,0.079102,0.25882,0.099792,-0.960724,-0.294617,0.910522,0.289978,0.137115,0.320038,-0.937408,-0.908386,0.345276,-0.235718,-0.936218,0.138763,0.322754,0.366577,0.925934,-0.090637,0.309296,-0.686829,-0.657684,0.66983,0.024445,
0.742065,-0.917999,-0.059113,-0.392059,0.365509,0.462158,-0.807922,0.083374,0.996399,-0.014801,0.593842,0.253143,-0.763672,0.974976,-0.165466,0.148285,0.918976,0.137299,0.369537,0.294952,0.694977,0.655731,0.943085,0.152618,-0.295319,0.58783,-0.598236,0.544495,0.203796,0.678223,0.705994,-0.478821,
-0.661011,0.577667,0.719055,-0.1698,-0.673828,-0.132172,-0.965332,0.225006,-0.981873,-0.14502,0.121979,0.763458,0.579742,0.284546,-0.893188,0.079681,0.442474,-0.795776,-0.523804,0.303802,0.734955,0.67804,-0.007446,0.15506,0.986267,-0.056183,0.258026,0.571503,-0.778931,-0.681549,-0.702087,-0.206116,
-0.96286,-0.177185,0.203613,-0.470978,-0.515106,0.716095,-0.740326,0.57135,0.354095,-0.56012,-0.824982,-0.074982,-0.507874,0.753204,0.417969,-0.503113,0.038147,0.863342,0.594025,0.673553,-0.439758,-0.119873,-0.005524,-0.992737,0.098267,-0.213776,0.971893,-0.615631,0.643951,0.454163,0.896851,-0.441071,
0.032166,-0.555023,0.750763,-0.358093,0.398773,0.304688,0.864929,-0.722961,0.303589,0.620544,-0.63559,-0.621948,-0.457306,-0.293243,0.072327,0.953278,-0.491638,0.661041,-0.566772,-0.304199,-0.572083,-0.761688,0.908081,-0.398956,0.127014,-0.523621,-0.549683,-0.650848,-0.932922,-0.19986,0.299408,0.099426,
0.140869,0.984985,-0.020325,-0.999756,-0.002319,0.952667,0.280853,-0.11615,-0.971893,0.082581,0.220337,0.65921,0.705292,-0.260651,0.733063,-0.175537,0.657043,-0.555206,0.429504,-0.712189,0.400421,-0.89859,0.179352,0.750885,-0.19696,0.630341,0.785675,-0.569336,0.241821,-0.058899,-0.464111,0.883789,
0.129608,-0.94519,0.299622,-0.357819,0.907654,0.219238,-0.842133,-0.439117,-0.312927,-0.313477,0.84433,0.434479,-0.241211,0.053253,0.968994,0.063873,0.823273,0.563965,0.476288,0.862152,-0.172516,0.620941,-0.298126,0.724915,0.25238,-0.749359,-0.612122,-0.577545,0.386566,0.718994,-0.406342,-0.737976,
0.538696,0.04718,0.556305,0.82959,-0.802856,0.587463,0.101166,-0.707733,-0.705963,0.026428,0.374908,0.68457,0.625092,0.472137,0.208405,-0.856506,-0.703064,-0.581085,-0.409821,-0.417206,-0.736328,0.532623,-0.447876,-0.20285,-0.870728,0.086945,-0.990417,0.107086,0.183685,0.018341,-0.982788,0.560638,
-0.428864,0.708282,0.296722,-0.952576,-0.0672,0.135773,0.990265,0.030243,-0.068787,0.654724,0.752686,0.762604,-0.551758,0.337585,-0.819611,-0.407684,0.402466,-0.727844,-0.55072,-0.408539,-0.855774,-0.480011,0.19281,0.693176,-0.079285,0.716339,0.226013,0.650116,-0.725433,0.246704,0.953369,-0.173553,
-0.970398,-0.239227,-0.03244,0.136383,-0.394318,0.908752,0.813232,0.558167,0.164368,0.40451,0.549042,-0.731323,-0.380249,-0.566711,0.730865,0.022156,0.932739,0.359741,0.00824,0.996552,-0.082306,0.956635,-0.065338,-0.283722,-0.743561,0.008209,0.668579,-0.859589,-0.509674,0.035767,-0.852234,0.363678,
-0.375977,-0.201965,-0.970795,-0.12915,0.313477,0.947327,0.06546,-0.254028,-0.528259,0.81015,0.628052,0.601105,0.49411,-0.494385,0.868378,0.037933,0.275635,-0.086426,0.957336,-0.197937,0.468903,-0.860748,0.895599,0.399384,0.195801,0.560791,0.825012,-0.069214,0.304199,-0.849487,0.43103,0.096375,
0.93576,0.339111,-0.051422,0.408966,-0.911072,0.330444,0.942841,-0.042389,-0.452362,-0.786407,0.420563,0.134308,-0.933472,-0.332489,0.80191,-0.566711,-0.188934,-0.987946,-0.105988,0.112518,-0.24408,0.892242,-0.379791,-0.920502,0.229095,-0.316376,0.7789,0.325958,0.535706,-0.912872,0.185211,-0.36377,
-0.184784,0.565369,-0.803833,-0.018463,0.119537,0.992615,-0.259247,-0.935608,0.239532,-0.82373,-0.449127,-0.345947,-0.433105,0.659515,0.614349,-0.822754,0.378845,-0.423676,0.687195,-0.674835,-0.26889,-0.246582,-0.800842,0.545715,-0.729187,-0.207794,0.651978,0.653534,-0.610443,-0.447388,0.492584,-0.023346,
0.869934,0.609039,0.009094,-0.79306,0.962494,-0.271088,-0.00885,0.2659,-0.004913,0.963959,0.651245,0.553619,-0.518951,0.280548,-0.84314,0.458618,-0.175293,-0.983215,0.049805,0.035339,-0.979919,0.196045,-0.982941,0.164307,-0.082245,0.233734,-0.97226,-0.005005,-0.747253,-0.611328,0.260437,0.645599,
0.592773,0.481384,0.117706,-0.949524,-0.29068,-0.535004,-0.791901,-0.294312,-0.627167,-0.214447,0.748718,-0.047974,-0.813477,-0.57959,-0.175537,0.477264,-0.860992,0.738556,-0.414246,-0.53183,0.562561,-0.704071,0.433289,-0.754944,0.64801,-0.100586,0.114716,0.044525,-0.992371,0.966003,0.244873,-0.082764,
}
Definition at line 177 of file noise.c.
Referenced by orgBlenderNoise(), ray_trace_shadow_rad(), renderflare(), and shadeHaloFloat().
char p[512+2] [static]
Initial value:
 {
0xA2,0xA0,0x19,0x3B,0xF8,0xEB,0xAA,0xEE,0xF3,0x1C,0x67,0x28,0x1D,0xED,0x0,0xDE,0x95,0x2E,0xDC,0x3F,0x3A,0x82,0x35,0x4D,0x6C,0xBA,0x36,0xD0,0xF6,0xC,0x79,0x32,0xD1,0x59,0xF4,0x8,0x8B,0x63,0x89,0x2F,0xB8,0xB4,0x97,0x83,0xF2,0x8F,0x18,0xC7,0x51,0x14,0x65,0x87,0x48,0x20,0x42,0xA8,0x80,0xB5,0x40,0x13,0xB2,0x22,0x7E,0x57,
0xBC,0x7F,0x6B,0x9D,0x86,0x4C,0xC8,0xDB,0x7C,0xD5,0x25,0x4E,0x5A,0x55,0x74,0x50,0xCD,0xB3,0x7A,0xBB,0xC3,0xCB,0xB6,0xE2,0xE4,0xEC,0xFD,0x98,0xB,0x96,0xD3,0x9E,0x5C,0xA1,0x64,0xF1,0x81,0x61,0xE1,0xC4,0x24,0x72,0x49,0x8C,0x90,0x4B,0x84,0x34,0x38,0xAB,0x78,0xCA,0x1F,0x1,0xD7,0x93,0x11,0xC1,0x58,0xA9,0x31,0xF9,0x44,0x6D,
0xBF,0x33,0x9C,0x5F,0x9,0x94,0xA3,0x85,0x6,0xC6,0x9A,0x1E,0x7B,0x46,0x15,0x30,0x27,0x2B,0x1B,0x71,0x3C,0x5B,0xD6,0x6F,0x62,0xAC,0x4F,0xC2,0xC0,0xE,0xB1,0x23,0xA7,0xDF,0x47,0xB0,0x77,0x69,0x5,0xE9,0xE6,0xE7,0x76,0x73,0xF,0xFE,0x6E,0x9B,0x56,0xEF,0x12,0xA5,0x37,0xFC,0xAE,0xD9,0x3,0x8E,0xDD,0x10,0xB9,0xCE,0xC9,0x8D,
0xDA,0x2A,0xBD,0x68,0x17,0x9F,0xBE,0xD4,0xA,0xCC,0xD2,0xE8,0x43,0x3D,0x70,0xB7,0x2,0x7D,0x99,0xD8,0xD,0x60,0x8A,0x4,0x2C,0x3E,0x92,0xE5,0xAF,0x53,0x7,0xE0,0x29,0xA6,0xC5,0xE3,0xF5,0xF7,0x4A,0x41,0x26,0x6A,0x16,0x5E,0x52,0x2D,0x21,0xAD,0xF0,0x91,0xFF,0xEA,0x54,0xFA,0x66,0x1A,0x45,0x39,0xCF,0x75,0xA4,0x88,0xFB,0x5D,
0xA2,0xA0,0x19,0x3B,0xF8,0xEB,0xAA,0xEE,0xF3,0x1C,0x67,0x28,0x1D,0xED,0x0,0xDE,0x95,0x2E,0xDC,0x3F,0x3A,0x82,0x35,0x4D,0x6C,0xBA,0x36,0xD0,0xF6,0xC,0x79,0x32,0xD1,0x59,0xF4,0x8,0x8B,0x63,0x89,0x2F,0xB8,0xB4,0x97,0x83,0xF2,0x8F,0x18,0xC7,0x51,0x14,0x65,0x87,0x48,0x20,0x42,0xA8,0x80,0xB5,0x40,0x13,0xB2,0x22,0x7E,0x57,
0xBC,0x7F,0x6B,0x9D,0x86,0x4C,0xC8,0xDB,0x7C,0xD5,0x25,0x4E,0x5A,0x55,0x74,0x50,0xCD,0xB3,0x7A,0xBB,0xC3,0xCB,0xB6,0xE2,0xE4,0xEC,0xFD,0x98,0xB,0x96,0xD3,0x9E,0x5C,0xA1,0x64,0xF1,0x81,0x61,0xE1,0xC4,0x24,0x72,0x49,0x8C,0x90,0x4B,0x84,0x34,0x38,0xAB,0x78,0xCA,0x1F,0x1,0xD7,0x93,0x11,0xC1,0x58,0xA9,0x31,0xF9,0x44,0x6D,
0xBF,0x33,0x9C,0x5F,0x9,0x94,0xA3,0x85,0x6,0xC6,0x9A,0x1E,0x7B,0x46,0x15,0x30,0x27,0x2B,0x1B,0x71,0x3C,0x5B,0xD6,0x6F,0x62,0xAC,0x4F,0xC2,0xC0,0xE,0xB1,0x23,0xA7,0xDF,0x47,0xB0,0x77,0x69,0x5,0xE9,0xE6,0xE7,0x76,0x73,0xF,0xFE,0x6E,0x9B,0x56,0xEF,0x12,0xA5,0x37,0xFC,0xAE,0xD9,0x3,0x8E,0xDD,0x10,0xB9,0xCE,0xC9,0x8D,
0xDA,0x2A,0xBD,0x68,0x17,0x9F,0xBE,0xD4,0xA,0xCC,0xD2,0xE8,0x43,0x3D,0x70,0xB7,0x2,0x7D,0x99,0xD8,0xD,0x60,0x8A,0x4,0x2C,0x3E,0x92,0xE5,0xAF,0x53,0x7,0xE0,0x29,0xA6,0xC5,0xE3,0xF5,0xF7,0x4A,0x41,0x26,0x6A,0x16,0x5E,0x52,0x2D,0x21,0xAD,0xF0,0x91,0xFF,0xEA,0x54,0xFA,0x66,0x1A,0x45,0x39,0xCF,0x75,0xA4,0x88,0xFB,0x5D,
0xA2,0xA0}
Definition at line 393 of file noise.c.
Referenced by addImage(), ParticleTracer::addParticle(), addSnapPoint(), btVoronoiSimplexSolver::addVertex(), LbmFsgrSolver::advanceParticles(), MD5Hash::append(), OcclusionBuffer::appendOccluderM(), applyModifier(), TNT::Array2D< T >::Array2D(), TNT::Array3D< T >::Array3D(), avgLogLum(), avi_fetchibuf(), basic_integrate(), BIF_listTemplates(), BIF_menustringTransformOrientation(), blf_dir_find(), BLF_dir_get(), blf_glyph_cache_find(), blf_glyph_search(), BLI_fillrand(), BLI_ghash_remove(), BLI_heap_remove(), BLI_heap_up(), BLI_insert_work(), BLI_path_abs(), BLI_path_rel(), BLI_pbvh_node_free_proxies(), BLI_str_find_next_char_utf8(), BLI_str_find_prev_char_utf8(), BLI_str_prev_char_utf8(), BLI_str_utf8_as_unicode_step(), BLI_utf8_invalid_byte(), Blinn_Spec(), BMO_slot_ptr_set(), BOP_Vertex::BOP_Vertex(), bottomup(), KX_Camera::BoxInsideFrustum(), brush_curve_strength_clamp(), btMachineIsLittleEndian(), btPoolAllocator::btPoolAllocator(), KX_NavMeshObject::BuildNavMesh(), KX_NavMeshObject::BuildVertIndArrays(), CalcSnapGeometry(), btSubsimplexConvexCast::calcTimeOfImpact(), ParticleTracer::checkDumpTextPositions(), ParticleTracer::cleanup(), ImageBuff::clear(), OcclusionBuffer::clipDraw(), cliptest(), cliptestf(), btVoronoiSimplexSolver::closestPtPointTetrahedron(), btDbvtBroadphase::collide(), btDbvt::collideTT(), btDbvt::collideTTpersistentStack(), collision_check(), color_balance_byte_byte(), color_balance_byte_float(), color_balance_float_float(), colorfn(), compute_mdisp_quad(), SubdAccBuilder::computeBoundaryTangentStencils(), IK_QPositionTask::ComputeJacobian(), computeLU(), convexHullSupport(), copy_particlesystem(), count_particles_mod(), create_vert_poly_map(), btSoftBodyHelpers::CreateEllipsoid(), createFacepa(), createRepresentation(), CcdPhysicsController::CreateSoftbody(), dblur(), dBoxBox2(), defocus_blur(), btMatrix3x3::diagonalize(), dist_to_rect(), btGjkEpaSolver2::Distance(), distribute_grid(), distribute_invalid(), distribute_simple_children(), distribute_threads_exec(), distribute_threads_exec_cb(), distribute_threads_init_data(), dLineClosestApproach(), btSoftBodyHelpers::Draw(), draw_documentation(), draw_histogram_bar(), draw_histogram_marker(), draw_mesh_fancy(), draw_rotation_guide(), draw_zebra_byte(), draw_zebra_float(), KX_NavMeshObject::DrawNavMesh(), drawSnapping(), dynamicPaint_paintParticles(), KDL::Eat(), KDL::EatWord(), ED_view3d_autodist(), ED_view3d_autodist_simple(), ED_view3d_calc_clipping(), Eigenhqr2(), Eigentql2(), gjkepa2_impl::GJK::EncloseOrigin(), escape_uri_string(), SubdFaceRing::evaluate_stencils(), exec_retargetArctoArc(), exec_work_fnct(), filelist_new(), filterObstacle(), find(), findzero(), folderlist_new(), for_mouse_hit_keys(), foreach_mouse_hit_key(), foreach_mouse_hit_point(), foreach_point(), foreach_selected_key(), foreach_selected_point(), TNT::Fortran_Array3D< T >::Fortran_Array3D(), forward_diff_bezier(), KDL::Frame::Frame(), get_colamd(), get_effector_tot(), get_property__internal(), get_PTCacheUndo(), KDL::FrameVel::GetFrame(), btSliderConstraint::getInfo2NonVirtual(), btConeTwistConstraint::getInfo2NonVirtual(), getNavmeshNormal(), GHOST_EventManager::getNumEvents(), getSnapPoint(), ParticleTracer::getTriangles(), KDL::TwistVel::GetTwist(), ghosts(), gp_session_cleanup(), gp_session_initpaint(), gpencil_draw_apply_event(), gpencil_draw_exec(), gpencil_draw_exit(), gpencil_draw_init(), gpencil_draw_invoke(), gpencil_draw_modal(), gpencil_stroke_begin(), gpencil_stroke_end(), GPU_texture_convert_pixels(), hammersley_create(), RAS_MeshObject::HasColliderPolygon(), MTRand::hash(), btSparseSdf< 3 >::Hash(), HC_relaxation_iteration_uv(), hsv_to_rgb(), BasicVector::hsvToRgb(), hsvToRgb(), imapaint_pick_uv(), IMB_metadata_change_field(), IMB_metadata_del_field(), ControlParticles::initBlenderTest(), ControlParticles::initFromBinaryFile(), ControlParticles::initFromMVCMesh(), ControlParticles::initFromObject(), TNT::Fortran_Matrix< T >::initialize(), TNT::Matrix< MT_Scalar >::initialize(), initialize_all_particles(), ntlGeometryObjModel::initModel(), ntlGeometryObject::initMovingPoints(), ControlParticles::initTime(), ControlParticles::initTimeArray(), TNT::Fortran_Array3D< T >::inject(), insert_lorem_exec(), intersectRectQuad2(), ntlRay::intersectTriangle(), ntlRay::intersectTriangleBack(), ntlRay::intersectTriangleFront(), ntlRay::intersectTriangleX(), isect_axial_line_tri_v3(), isect_line_tri_v3(), isect_point_tri_v2_int(), isect_ray_plane_v3(), isect_ray_tri_epsilon_v3(), isect_ray_tri_threshold_v3(), isect_ray_tri_v3(), knife_edge_tri_isect(), laplacian_increase_edge_count(), laplacian_relaxation_iteration_uv(), JAMA::LU< Real >::LU(), main(), make_sep_waveform_view_from_ibuf_byte(), make_sep_waveform_view_from_ibuf_float(), make_transform(), make_vectorscope_view_from_ibuf_byte(), make_vectorscope_view_from_ibuf_float(), make_waveform_view_from_ibuf_byte(), make_waveform_view_from_ibuf_float(), mesh_flush_hidden_from_verts(), mesh_strip_loose_polysloops(), morpho_dilate(), morpho_erode(), multiresModifier_base_apply(), need_add_seq_dup(), neighbor_average(), next_state(), node_select_same_type(), node_select_same_type_np(), noise3_perlin(), KDL::VectorVel::Norm(), normalfn(), KX_Camera::NormalizeClipPlanes(), ParticleTracer::notifyOfDump(), btCollisionWorld::objectQuerySingle(), TNT::operator*(), MT_Transform::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), ntlVector3Dim< gfxReal >::operator+=(), TNT::operator-(), TNT::operator-=(), ntlVector3Dim< gfxReal >::operator-=(), TNT::operator/(), TNT::operator/=(), KDL::operator<<(), TNT::Fortran_Array3D< T >::operator=(), outliner_add_element(), outliner_add_seq_dup(), GIM_AABB::overlapping_trans_cache(), p_chart_convex_hull(), Mesh::pack_verts(), paint_cursor_start(), paint_poll(), parse_bcd(), particles_fluid_step(), pdDoEffectors(), PE_apply_mirror(), PE_create_particle_edit(), pe_deflect_emitter(), PE_lasso_select(), PE_minmax(), PE_mirror_x(), PE_update_mirror_cache(), PE_update_selection(), perlin_periodic(), precalc_guides(), btSoftColliders::CollideVF_SS::Process(), processSamples(), btDbvtAabbMm::ProjectMinimum(), ProjectOrigin(), gjkepa2_impl::GJK::projectorigin(), btSoftBody::PSolve_SContacts(), psys_apply_hair_lattice(), psys_find_parents(), psys_get_birth_coordinates(), psys_get_particle_on_path(), psys_get_particle_state(), psys_update_particle_bvhtree(), psys_update_particle_tree(), ptcache_particle_totwrite(), OcclusionBuffer::queryOccluderW(), btCollisionWorld::rayTestSingle(), realloc_particles(), btKinematicCharacterController::recoverFromPenetration(), regular_polygon_sample(), MTRand::reload(), remove_doubles_exec(), remove_tagged_keys(), remove_tagged_particles(), reset_all_particles(), reset_particle(), retargetArctoArc(), KDL::TwistVel::ReverseSign(), rna_path_token(), rule_follow_leader(), sculpt_brush_test_cube(), sculpt_combine_proxies(), sculpt_stroke_done(), sculpt_update_cache_invariants(), Stream::seek(), set_keyed_keys(), ntlGeometryObject::setMaterial(), OcclusionBuffer::setup(), shade_by_transmission(), btGjkEpaSolver2::SignedDistance(), sk_drawSketch(), sk_flattenStroke(), sk_getStrokeSnapPoint(), sk_straightenStroke(), sort(), sp_coletree(), sp_symetree(), KX_Camera::SphereInsideFrustum(), sss_add_points(), sss_create_tree_mat(), star4(), strand_eval_point(), strand_segment_recursive(), strand_shade_get(), TNT::Array3D< T >::subarray(), TNT::Array2D< T >::subarray(), sum_leaf_radiance(), TNT::SVD(), svd_m4(), svm_node_value_v(), btEigen::system(), testAxialSymmetry(), testRadialSymmetry(), tga_out1(), tga_out2(), tga_out3(), tga_out4(), to_hex_char(), transformc(), BoundBox::transformed(), traverse_octree(), tree_element_active_sequence_dup(), IsoSurface::triangulate(), KDL::Segment::twist(), ui_but_copy_paste(), ui_textedit_copypaste(), unique_property(), unlink_object(), unref_strand_samples(), KX_SoundActuator::Update(), update_world_cos(), btVoronoiSimplexSolver::updateClosestVectorAndPoints(), CcdShapeConstructionInfo::UpdateMesh(), updateSelectedSnapPoint(), upsampleX(), upsampleY(), upsampleZ(), vectorscope_put_cross(), VertexIt_Fill(), vgroup_fix(), view3d_zoom_border_exec(), viewops_data_free(), vol_get_transmittance(), vol_shade_one_lamp(), volumeintegrate(), voronoi(), weight_set_exec(), wform_put_border(), WM_clipboard_text_get(), WM_clipboard_text_set(), and btDbvt::write().