Blender: btTriangleShapeEx Class Reference
btTriangleShapeEx Class Reference
Helper class for colliding Bullet Triangle Shapes.
#include <btTriangleShapeEx.h>
Public Member Functions
btTriangleShapeEx ()
btTriangleShapeEx (const btVector3 &p0, const btVector3 &p1, const btVector3 &p2)
btTriangleShapeEx (const btTriangleShapeEx &other)
virtual void getAabb (const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
void applyTransform (const btTransform &t)
SIMD_FORCE_INLINE void buildTriPlane (btVector4 &plane) const
bool overlap_test_conservative (const btTriangleShapeEx &other)
class btTriangleShapeEx: public btTriangleShape
Detailed Description
Helper class for colliding Bullet Triangle Shapes.
This class implements a better getAabb method than the previous btTriangleShape class
Definition at line 135 of file btTriangleShapeEx.h.
Constructor & Destructor Documentation
btTriangleShapeEx::btTriangleShapeEx () [inline]
Definition at line 139 of file btTriangleShapeEx.h.
btTriangleShapeEx::btTriangleShapeEx (const btVector3 & p0, const btVector3 & p1, const btVector3 & p2) [inline]
Definition at line 143 of file btTriangleShapeEx.h.
btTriangleShapeEx::btTriangleShapeEx (const btTriangleShapeEx & other) [inline]
Definition at line 147 of file btTriangleShapeEx.h.
Member Function Documentation
void btTriangleShapeEx::applyTransform (const btTransform & t) [inline]
Definition at line 162 of file btTriangleShapeEx.h.
SIMD_FORCE_INLINE void btTriangleShapeEx::buildTriPlane (btVector4 & plane) const [inline]
Definition at line 169 of file btTriangleShapeEx.h.
References cross(), dot(), and btVector4::setValue().
Referenced by overlap_test_conservative().
virtual void btTriangleShapeEx::getAabb (const btTransform & t, btVector3 & aabbMin, btVector3 & aabbMax) const [inline, virtual]
Definition at line 151 of file btTriangleShapeEx.h.
bool btTriangleShapeEx::overlap_test_conservative (const btTriangleShapeEx & other)
class btTriangleShapeEx: public btTriangleShape
Definition at line 188 of file btTriangleShapeEx.cpp.
References bt_distance_point_plane(), and buildTriPlane().
Referenced by btGImpactCollisionAlgorithm::collide_gjk_triangles().
The documentation for this class was generated from the following files:
btTriangleShapeEx.h
btTriangleShapeEx.cpp