Blender: SG_QList Class Reference
SG_QList Class Reference
#include <SG_QList.h>
Classes
class iterator
Public Member Functions
SG_QList ()
SG_QList (const SG_QList &other)
virtual ~SG_QList ()
bool QEmpty ()
bool QAddBack (SG_QList *item)
bool QAddFront (SG_QList *item)
SG_QList * QRemove ()
bool QDelink ()
SG_QList * QPeek ()
SG_QList * QBack ()
Protected Attributes
SG_QList * m_fqlink
SG_QList * m_bqlink
Detailed Description
Double-Double circular linked list For storing an object is two lists simultaneously
Definition at line 41 of file SG_QList.h.
Constructor & Destructor Documentation
SG_QList::SG_QList () [inline]
Definition at line 91 of file SG_QList.h.
References m_bqlink, and m_fqlink.
SG_QList::SG_QList (const SG_QList & other) [inline]
Definition at line 95 of file SG_QList.h.
References m_bqlink, and m_fqlink.
virtual SG_QList::~SG_QList () [inline, virtual]
Definition at line 99 of file SG_QList.h.
References QDelink().
Member Function Documentation
bool SG_QList::QAddBack (SG_QList * item) [inline]
Definition at line 108 of file SG_QList.h.
References m_bqlink, m_fqlink, and QEmpty().
Referenced by SCA_IController::Activate(), RAS_MeshObject::AddMeshUser(), SCA_ILogicBrick::InsertSelfActiveQList(), and SG_Node::Reschedule().
bool SG_QList::QAddFront (SG_QList * item) [inline]
Definition at line 118 of file SG_QList.h.
References SG_DList::Empty(), m_bqlink, and m_fqlink.
SG_QList* SG_QList::QBack () [inline]
Definition at line 153 of file SG_QList.h.
References m_bqlink.
Referenced by SG_QList::iterator< T >::back().
bool SG_QList::QDelink () [inline]
Definition at line 140 of file SG_QList.h.
References m_bqlink, m_fqlink, and QEmpty().
Referenced by KX_StateActuator::Deactivate(), SCA_IActuator::Deactivate(), SCA_LogicManager::UpdateFrame(), and ~SG_QList().
bool SG_QList::QEmpty () [inline]
Definition at line 104 of file SG_QList.h.
References m_fqlink.
Referenced by SCA_IActuator::Activate(), SCA_IController::Activate(), KX_StateActuator::Activate(), KX_StateActuator::Deactivate(), SCA_IActuator::Deactivate(), QAddBack(), QDelink(), QRemove(), and SCA_LogicManager::UpdateFrame().
SG_QList* SG_QList::QPeek () [inline]
Definition at line 149 of file SG_QList.h.
References m_fqlink.
Referenced by SG_QList::iterator< T >::begin().
SG_QList* SG_QList::QRemove () [inline]
Definition at line 128 of file SG_QList.h.
References m_bqlink, m_fqlink, NULL, and QEmpty().
Referenced by SCA_LogicManager::BeginFrame(), and SG_Node::GetNextRescheduled().
Member Data Documentation
SG_QList* SG_QList::m_bqlink [protected]
Definition at line 45 of file SG_QList.h.
Referenced by QAddBack(), QAddFront(), QBack(), QDelink(), QRemove(), and SG_QList().
SG_QList* SG_QList::m_fqlink [protected]
Definition at line 44 of file SG_QList.h.
Referenced by QAddBack(), QAddFront(), QDelink(), QEmpty(), QPeek(), QRemove(), and SG_QList().
The documentation for this class was generated from the following file:
SG_QList.h