Blender: rna_test.c File Reference
rna_test.c File Reference
RNA
#include <stdlib.h>
#include <string.h>
#include "RNA_define.h"
#include "rna_internal.h"
Defines
#define ARRAY_SIZE 3
#define DYNAMIC_ARRAY_SIZE 64
#define MARRAY_DIM [3][4][5]
#define MARRAY_TOTDIM 3
#define MARRAY_DIMSIZE 4, 5
#define MARRAY_SIZE(type) (sizeof(type MARRAY_DIM) / sizeof(type))
#define DYNAMIC_MARRAY_DIM [3][4][5]
#define DYNAMIC_MARRAY_SIZE(type) (sizeof(type DYNAMIC_MARRAY_DIM) / sizeof(type))
Functions
void RNA_def_test (BlenderRNA *brna)
Detailed Description
Definition in file rna_test.c.
Define Documentation
#define ARRAY_SIZE 3
Definition at line 37 of file rna_test.c.
Referenced by RNA_def_test().
#define DYNAMIC_ARRAY_SIZE 64
Definition at line 38 of file rna_test.c.
Referenced by RNA_def_test().
#define DYNAMIC_MARRAY_DIM [3][4][5]
Definition at line 43 of file rna_test.c.
#define DYNAMIC_MARRAY_SIZE (type) (sizeof(type DYNAMIC_MARRAY_DIM) / sizeof(type))
Definition at line 44 of file rna_test.c.
Referenced by RNA_def_test().
#define MARRAY_DIM [3][4][5]
Definition at line 39 of file rna_test.c.
#define MARRAY_DIMSIZE 4, 5
Definition at line 41 of file rna_test.c.
Referenced by RNA_def_test().
#define MARRAY_SIZE (type) (sizeof(type MARRAY_DIM) / sizeof(type))
Definition at line 42 of file rna_test.c.
Referenced by RNA_def_test().
#define MARRAY_TOTDIM 3
Definition at line 40 of file rna_test.c.
Referenced by RNA_def_test().
Function Documentation
void RNA_def_test (BlenderRNA * brna)
Definition at line 118 of file rna_test.c.
References ARRAY_SIZE, DYNAMIC_ARRAY_SIZE, DYNAMIC_MARRAY_SIZE, MARRAY_DIMSIZE, MARRAY_SIZE, MARRAY_TOTDIM, NULL, PROP_BOOLEAN, PROP_DYNAMIC, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_boolean_array(), RNA_def_float_array(), RNA_def_int_array(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), RNA_def_struct(), and RNA_def_struct_sdna().