Blender: btTriangleMeshShape Class Reference
btTriangleMeshShape Class Reference
The btTriangleMeshShape is an internal concave triangle mesh interface. Don't use this class directly, use btBvhTriangleMeshShape instead.
#include <btTriangleMeshShape.h>
Public Member Functions
virtual ~btTriangleMeshShape ()
virtual btVector3 localGetSupportingVertex (const btVector3 &vec) const
virtual btVector3 localGetSupportingVertexWithoutMargin (const btVector3 &vec) const
void recalcLocalAabb ()
virtual void getAabb (const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
getAabb returns the axis aligned bounding box in the coordinate frame of the given transform t.
virtual void processAllTriangles (btTriangleCallback *callback, const btVector3 &aabbMin, const btVector3 &aabbMax) const
virtual void calculateLocalInertia (btScalar mass, btVector3 &inertia) const
virtual void setLocalScaling (const btVector3 &scaling)
virtual const btVector3 & getLocalScaling () const
btStridingMeshInterface * getMeshInterface ()
const btStridingMeshInterface * getMeshInterface () const
const btVector3 & getLocalAabbMin () const
const btVector3 & getLocalAabbMax () const
virtual const char * getName () const
Protected Member Functions
btTriangleMeshShape (btStridingMeshInterface *meshInterface)
Protected Attributes
btVector3 m_localAabbMin
btVector3 m_localAabbMax
btStridingMeshInterface * m_meshInterface
Detailed Description
The btTriangleMeshShape is an internal concave triangle mesh interface. Don't use this class directly, use btBvhTriangleMeshShape instead.
Definition at line 24 of file btTriangleMeshShape.h.
Constructor & Destructor Documentation
btTriangleMeshShape::btTriangleMeshShape (btStridingMeshInterface * meshInterface) [protected]
btTriangleMeshShape constructor has been disabled/protected, so that users will not mistakenly use this class. Don't use btTriangleMeshShape but use btBvhTriangleMeshShape instead!
Definition at line 24 of file btTriangleMeshShape.cpp.
References btStridingMeshInterface::getPremadeAabb(), btStridingMeshInterface::hasPremadeAabb(), m_localAabbMax, m_localAabbMin, btCollisionShape::m_shapeType, recalcLocalAabb(), and TRIANGLE_MESH_SHAPE_PROXYTYPE.
btTriangleMeshShape::~btTriangleMeshShape () [virtual]
Definition at line 39 of file btTriangleMeshShape.cpp.
Member Function Documentation
void btTriangleMeshShape::calculateLocalInertia (btScalar mass, btVector3 & inertia) const [virtual]
Implements btCollisionShape.
Definition at line 184 of file btTriangleMeshShape.cpp.
References btAssert.
void btTriangleMeshShape::getAabb (const btTransform & t, btVector3 & aabbMin, btVector3 & aabbMax) const [virtual]
getAabb returns the axis aligned bounding box in the coordinate frame of the given transform t.
Implements btCollisionShape.
Definition at line 47 of file btTriangleMeshShape.cpp.
References btMatrix3x3::absolute(), dot(), btTransform::getBasis(), btConcaveShape::getMargin(), m_localAabbMax, and m_localAabbMin.
const btVector3& btTriangleMeshShape::getLocalAabbMax () const [inline]
Definition at line 72 of file btTriangleMeshShape.h.
References m_localAabbMax.
const btVector3& btTriangleMeshShape::getLocalAabbMin () const [inline]
Definition at line 68 of file btTriangleMeshShape.h.
References m_localAabbMin.
const btVector3 & btTriangleMeshShape::getLocalScaling () const [virtual]
Implements btCollisionShape.
Definition at line 134 of file btTriangleMeshShape.cpp.
References btStridingMeshInterface::getScaling(), and m_meshInterface.
btStridingMeshInterface* btTriangleMeshShape::getMeshInterface () [inline]
Definition at line 58 of file btTriangleMeshShape.h.
References m_meshInterface.
Referenced by DeleteBulletShape(), and GetHitTriangle().
const btStridingMeshInterface* btTriangleMeshShape::getMeshInterface () const [inline]
Definition at line 63 of file btTriangleMeshShape.h.
References m_meshInterface.
virtual const char* btTriangleMeshShape::getName (void) const [inline, virtual]
Implements btCollisionShape.
Definition at line 80 of file btTriangleMeshShape.h.
btVector3 btTriangleMeshShape::localGetSupportingVertex (const btVector3 & vec) const [virtual]
Definition at line 193 of file btTriangleMeshShape.cpp.
References BT_LARGE_FLOAT, SupportVertexCallback::GetSupportVertexLocal(), processAllTriangles(), and btTransform::setIdentity().
Referenced by localGetSupportingVertexWithoutMargin(), and recalcLocalAabb().
virtual btVector3 btTriangleMeshShape::localGetSupportingVertexWithoutMargin (const btVector3 & vec) const [inline, virtual]
Definition at line 41 of file btTriangleMeshShape.h.
References btAssert, and localGetSupportingVertex().
void btTriangleMeshShape::processAllTriangles (btTriangleCallback * callback, const btVector3 & aabbMin, const btVector3 & aabbMax) const [virtual]
Implements btConcaveShape.
Definition at line 148 of file btTriangleMeshShape.cpp.
References btStridingMeshInterface::InternalProcessAllTriangles(), m_meshInterface, and TestTriangleAgainstAabb2().
Referenced by localGetSupportingVertex().
void btTriangleMeshShape::recalcLocalAabb ()
Definition at line 67 of file btTriangleMeshShape.cpp.
References i, localGetSupportingVertex(), btConcaveShape::m_collisionMargin, m_localAabbMax, and m_localAabbMin.
Referenced by btTriangleMeshShape(), and setLocalScaling().
void btTriangleMeshShape::setLocalScaling (const btVector3 & scaling) [virtual]
Implements btCollisionShape.
Definition at line 128 of file btTriangleMeshShape.cpp.
References m_meshInterface, recalcLocalAabb(), and btStridingMeshInterface::setScaling().
Member Data Documentation
btVector3 btTriangleMeshShape::m_localAabbMax [protected]
Definition at line 28 of file btTriangleMeshShape.h.
Referenced by btTriangleMeshShape(), getAabb(), getLocalAabbMax(), and recalcLocalAabb().
btVector3 btTriangleMeshShape::m_localAabbMin [protected]
Definition at line 27 of file btTriangleMeshShape.h.
Referenced by btTriangleMeshShape(), getAabb(), getLocalAabbMin(), and recalcLocalAabb().
btStridingMeshInterface* btTriangleMeshShape::m_meshInterface [protected]
Definition at line 29 of file btTriangleMeshShape.h.
Referenced by getLocalScaling(), getMeshInterface(), processAllTriangles(), and setLocalScaling().
The documentation for this class was generated from the following files:
btTriangleMeshShape.h
btTriangleMeshShape.cpp