Blender: movieclip.c File Reference
movieclip.c File Reference
blenkernel
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include "MEM_guardedalloc.h"
#include "DNA_constraint_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_movieclip_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_view3d_types.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_ghash.h"
#include "BLI_math.h"
#include "BLI_mempool.h"
#include "BLI_threads.h"
#include "BKE_animsys.h"
#include "BKE_constraint.h"
#include "BKE_library.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_utildefines.h"
#include "BKE_movieclip.h"
#include "BKE_image.h"
#include "BKE_tracking.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_moviecache.h"
Classes
struct MovieClipCache
struct MovieClipImBufCacheKey
Typedefs
typedef struct MovieClipCache MovieClipCache
typedef struct
MovieClipImBufCacheKey MovieClipImBufCacheKey
Functions
static int sequence_guess_offset (const char *full_name, int head_len, unsigned short numlen)
static int rendersize_to_proxy (MovieClipUser *user, int flag)
static int rendersize_to_number (int render_size)
static int get_timecode (MovieClip *clip, int flag)
static void get_sequence_fname (MovieClip *clip, int framenr, char *name)
static void get_proxy_fname (MovieClip *clip, int proxy_render_size, int undistorted, int framenr, char *name)
static ImBuf * movieclip_load_sequence_file (MovieClip *clip, MovieClipUser *user, int framenr, int flag)
static void movieclip_open_anim_file (MovieClip *clip)
static ImBuf * movieclip_load_movie_file (MovieClip *clip, MovieClipUser *user, int framenr, int flag)
static void movieclip_calc_length (MovieClip *clip)
static void moviecache_keydata (void *userkey, int *framenr, int *proxy, int *render_flags)
static unsigned int moviecache_hashhash (const void *keyv)
static int moviecache_hashcmp (const void *av, const void *bv)
static ImBuf * get_imbuf_cache (MovieClip *clip, MovieClipUser *user, int flag)
static void put_imbuf_cache (MovieClip *clip, MovieClipUser *user, ImBuf *ibuf, int flag)
static MovieClip * movieclip_alloc (const char *name)
MovieClip * BKE_add_movieclip_file (const char *name)
static void real_ibuf_size (MovieClip *clip, MovieClipUser *user, ImBuf *ibuf, int *width, int *height)
static ImBuf * get_undistorted_ibuf (MovieClip *clip, struct MovieDistortion *distortion, ImBuf *ibuf)
static int need_undistortion_postprocess (MovieClipUser *user, int flag)
static int need_postprocessed_frame (MovieClipUser *user, int flag, int postprocess_flag)
static int check_undistortion_cache_flags (MovieClip *clip)
static ImBuf * get_postprocessed_cached_frame (MovieClip *clip, MovieClipUser *user, int flag, int postprocess_flag)
static ImBuf * put_postprocessed_frame_to_cache (MovieClip *clip, MovieClipUser *user, ImBuf *ibuf, int flag, int postprocess_flag)
static ImBuf * movieclip_get_postprocessed_ibuf (MovieClip *clip, MovieClipUser *user, int flag, int postprocess_flag, int cache_flag)
ImBuf * BKE_movieclip_get_ibuf (MovieClip *clip, MovieClipUser *user)
ImBuf * BKE_movieclip_get_ibuf_flag (MovieClip *clip, MovieClipUser *user, int flag, int cache_flag)
ImBuf * BKE_movieclip_get_postprocessed_ibuf (MovieClip *clip, MovieClipUser *user, int postprocess_flag)
static ImBuf * get_stable_cached_frame (MovieClip *clip, MovieClipUser *user, int framenr, int postprocess_flag)
static ImBuf * put_stabilized_frame_to_cache (MovieClip *clip, MovieClipUser *user, ImBuf *ibuf, int framenr, int postprocess_flag)
ImBuf * BKE_movieclip_get_stable_ibuf (MovieClip *clip, MovieClipUser *user, float loc[2], float *scale, float *angle, int postprocess_flag)
int BKE_movieclip_has_frame (MovieClip *clip, MovieClipUser *user)
void BKE_movieclip_get_size (MovieClip *clip, MovieClipUser *user, int *width, int *height)
int BKE_movieclip_get_duration (MovieClip *clip)
void BKE_movieclip_aspect (MovieClip *clip, float *aspx, float *aspy)
void BKE_movieclip_get_cache_segments (MovieClip *clip, MovieClipUser *user, int *totseg_r, int **points_r)
void BKE_movieclip_user_set_frame (MovieClipUser *iuser, int framenr)
static void free_buffers (MovieClip *clip)
void BKE_movieclip_reload (MovieClip *clip)
void BKE_movieclip_update_scopes (MovieClip *clip, MovieClipUser *user, MovieClipScopes *scopes)
static void movieclip_build_proxy_ibuf (MovieClip *clip, ImBuf *ibuf, int cfra, int proxy_render_size, int undistorted)
void BKE_movieclip_build_proxy_frame (MovieClip *clip, int clip_flag, struct MovieDistortion *distortion, int cfra, int *build_sizes, int build_count, int undistorted)
void free_movieclip (MovieClip *clip)
void unlink_movieclip (Main *bmain, MovieClip *clip)
Detailed Description
Definition in file movieclip.c.
Typedef Documentation
typedef struct MovieClipCache MovieClipCache
typedef struct MovieClipImBufCacheKey MovieClipImBufCacheKey
Function Documentation
MovieClip* BKE_add_movieclip_file (const char * name) [read]
Definition at line 453 of file movieclip.c.
References BKE_movieclip_get_size(), BLI_open(), BLI_path_abs(), BLI_strncpy(), BLI_testextensie_array(), MovieTracking::camera, FILE_MAX, MovieTrackingCamera::focal, MovieClipUser::framenr, G, MovieClip::id, imb_ext_movie, len(), MCLIP_SRC_MOVIE, MCLIP_SRC_SEQUENCE, movieclip_alloc(), movieclip_calc_length(), MovieClip::name, ID::next, NULL, O_BINARY, MovieTrackingCamera::principal, MovieTrackingCamera::sensor_width, MovieClip::source, str, strlen(), MovieClip::tracking, and ID::us.
Referenced by open_exec().
void BKE_movieclip_aspect (MovieClip * clip, float * aspx, float * aspy)
Definition at line 946 of file movieclip.c.
References MovieClip::aspx, MovieClip::aspy, MovieTracking::camera, MovieTrackingCamera::pixel_aspect, and MovieClip::tracking.
Referenced by ED_space_clip_aspect().
void BKE_movieclip_build_proxy_frame (MovieClip * clip, int clip_flag, struct MovieDistortion * distortion, int cfra, int * build_sizes, int build_count, int undistorted)
Definition at line 1123 of file movieclip.c.
References BKE_movieclip_get_ibuf_flag(), MovieClipUser::framenr, get_undistorted_ibuf(), i, IMB_freeImBuf(), MCLIP_PROXY_RENDER_SIZE_FULL, movieclip_build_proxy_ibuf(), MOVIECLIP_CACHE_SKIP, MovieClipUser::render_flag, and MovieClipUser::render_size.
Referenced by proxy_startjob().
void BKE_movieclip_get_cache_segments (MovieClip * clip, MovieClipUser * user, int * totseg_r, int ** points_r)
Definition at line 955 of file movieclip.c.
References MovieClip::cache, MovieClip::flag, IMB_moviecache_get_cache_segments(), MovieClipCache::moviecache, NULL, MovieClipUser::render_flag, and rendersize_to_proxy().
Referenced by draw_movieclip_cache().
int BKE_movieclip_get_duration (MovieClip * clip)
Definition at line 937 of file movieclip.c.
References MovieClip::len, and movieclip_calc_length().
Referenced by reload_sequence_new_file(), and sequencer_add_movieclip_strip_exec().
ImBuf* BKE_movieclip_get_ibuf (MovieClip * clip, MovieClipUser * user) [read]
Definition at line 751 of file movieclip.c.
References BKE_movieclip_get_ibuf_flag(), and MovieClip::flag.
Referenced by BKE_movieclip_get_size(), BKE_movieclip_has_frame(), BKE_movieclip_update_scopes(), draw_bgpic(), ED_view3d_draw_offscreen(), and node_composit_get_movieclip().
ImBuf* BKE_movieclip_get_ibuf_flag (MovieClip * clip, MovieClipUser * user, int flag, int cache_flag) [read]
Definition at line 756 of file movieclip.c.
References movieclip_get_postprocessed_ibuf().
Referenced by BKE_movieclip_build_proxy_frame(), BKE_movieclip_get_ibuf(), BKE_tracking_next(), detect_features_exec(), and seq_render_movieclip_strip().
ImBuf* BKE_movieclip_get_postprocessed_ibuf (MovieClip * clip, MovieClipUser * user, int postprocess_flag) [read]
Definition at line 761 of file movieclip.c.
References MovieClip::flag, and movieclip_get_postprocessed_ibuf().
Referenced by BKE_movieclip_get_stable_ibuf(), and ED_space_clip_get_buffer().
void BKE_movieclip_get_size (MovieClip * clip, MovieClipUser * user, int * width, int * height)
Definition at line 915 of file movieclip.c.
References BKE_movieclip_get_ibuf(), MovieClipUser::framenr, IMB_freeImBuf(), MovieClip::lastframe, MovieClip::lastsize, real_ibuf_size(), ImBuf::x, and ImBuf::y.
Referenced by BKE_add_movieclip_file(), BKE_movieclip_update_scopes(), BKE_tracking_context_new(), clip_graph_tracking_values_iterate_track(), createTransTrackingCurvesData(), draw_tracks_curves(), ED_space_clip_size(), exec(), marker_block_handler(), set_center_principal_exec(), solve_camera_freejob(), solve_camera_initjob(), and uiTemplateMarker().
ImBuf* BKE_movieclip_get_stable_ibuf (MovieClip * clip, MovieClipUser * user, float loc[2], float * scale, float * angle, int postprocess_flag) [read]
Definition at line 854 of file movieclip.c.
References MovieClipCache::angle, BKE_movieclip_get_postprocessed_ibuf(), MovieClip::cache, copy_v2_v2(), MovieTrackingStabilization::flag, MovieClipUser::framenr, get_stable_cached_frame(), IMB_freeImBuf(), MovieClipCache::loc, NULL, put_stabilized_frame_to_cache(), MovieClipCache::scale, MovieTracking::stabilization, MovieClipCache::stabilized, MovieClip::tracking, TRACKING_2D_STABILIZATION, and zero_v2().
Referenced by ED_space_clip_get_stable_buffer(), and seq_render_movieclip_strip().
int BKE_movieclip_has_frame (MovieClip * clip, MovieClipUser * user)
Definition at line 903 of file movieclip.c.
References BKE_movieclip_get_ibuf(), FALSE, IMB_freeImBuf(), and TRUE.
Referenced by createTransTrackingData(), and space_clip_frame_poll().
void BKE_movieclip_reload (MovieClip * clip)
Definition at line 997 of file movieclip.c.
References BLI_testextensie_array(), FALSE, free_buffers(), imb_ext_movie, MCLIP_SRC_MOVIE, MCLIP_SRC_SEQUENCE, movieclip_calc_length(), MovieClip::name, MovieTrackingStabilization::ok, MovieClip::source, MovieTracking::stabilization, and MovieClip::tracking.
Referenced by proxy_endjob(), and reload_exec().
void BKE_movieclip_update_scopes (MovieClip * clip, MovieClipUser * user, MovieClipScopes * scopes)
Definition at line 1013 of file movieclip.c.
References BKE_movieclip_get_ibuf(), BKE_movieclip_get_size(), BKE_tracking_active_track(), BKE_tracking_get_marker(), BKE_tracking_get_pattern_imbuf(), BKE_tracking_invert_intrinsics(), MovieTracking::camera, FALSE, MovieTrackingTrack::flag, MovieTrackingMarker::flag, MovieClipScopes::framenr, MovieClipUser::framenr, IMB_freeImBuf(), IMB_rect_from_float(), MovieClipScopes::marker, MARKER_DISABLED, MCLIP_PROXY_RENDER_UNDISTORT, NULL, MovieClipScopes::ok, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingCamera::pixel_aspect, MovieTrackingMarker::pos, ImBuf::rect, ImBuf::rect_float, MovieClipUser::render_flag, MovieClipScopes::slide_scale, MovieClipScopes::track, MovieClipScopes::track_disabled, TRACK_LOCKED, MovieClipScopes::track_pos, MovieClipScopes::track_preview, MovieClip::tracking, and TRUE.
Referenced by clip_properties_area_draw().
void BKE_movieclip_user_set_frame (MovieClipUser * iuser, int framenr)
Definition at line 967 of file movieclip.c.
References MovieClipUser::framenr.
Referenced by clip_refresh(), draw_bgpic(), ED_clip_update_frame(), ED_view3d_draw_offscreen(), exec(), node_composit_exec_movieclip(), and seq_render_movieclip_strip().
static int check_undistortion_cache_flags (MovieClip * clip) [static]
Definition at line 584 of file movieclip.c.
References MovieClip::cache, MovieTracking::camera, equals_v2v2(), equals_v3v3(), FALSE, MovieClipCache::k1, MovieTrackingCamera::k1, MovieClipCache::postprocessed, MovieTrackingCamera::principal, MovieClipCache::principal, MovieClip::tracking, and TRUE.
Referenced by get_postprocessed_cached_frame().
static void free_buffers (MovieClip * clip) [static]
Definition at line 974 of file movieclip.c.
References MovieClip::anim, BKE_free_animdata(), MovieClip::cache, MovieClipCache::ibuf, IMB_free_anim(), IMB_freeImBuf(), IMB_moviecache_free(), MEM_freeN(), MovieClipCache::moviecache, NULL, MovieClipCache::postprocessed, and MovieClipCache::stabilized.
Referenced by BKE_movieclip_reload(), and free_movieclip().
void free_movieclip (MovieClip * clip)
Definition at line 1152 of file movieclip.c.
References BKE_tracking_free(), free_buffers(), and MovieClip::tracking.
Referenced by free_libblock().
static ImBuf* get_imbuf_cache (MovieClip * clip, MovieClipUser * user, int flag) [static]
Definition at line 379 of file movieclip.c.
References MovieClip::cache, MovieClipUser::framenr, MovieClipImBufCacheKey::framenr, IMB_moviecache_get(), IMB_PROXY_NONE, MCLIP_USE_PROXY, MovieClipCache::moviecache, NULL, MovieClipImBufCacheKey::proxy, MovieClipImBufCacheKey::render_flag, MovieClipUser::render_flag, and rendersize_to_proxy().
Referenced by movieclip_get_postprocessed_ibuf().
static ImBuf* get_postprocessed_cached_frame (MovieClip * clip, MovieClipUser * user, int flag, int postprocess_flag) [static]
Definition at line 599 of file movieclip.c.
References MovieClip::cache, check_undistortion_cache_flags(), MovieClipCache::flag, MovieClipCache::framenr, MovieClipUser::framenr, MovieClipCache::ibuf, IMB_PROXY_NONE, IMB_refImBuf(), MCLIP_USE_PROXY, need_undistortion_postprocess(), NULL, MovieClipCache::postprocessed, MovieClipCache::proxy, MovieClipCache::render_flag, MovieClipUser::render_flag, rendersize_to_proxy(), and MovieClipCache::undistoriton_used.
Referenced by movieclip_get_postprocessed_ibuf().
static void get_proxy_fname (MovieClip * clip, int proxy_render_size, int undistorted, int framenr, char * name) [static]
Definition at line 169 of file movieclip.c.
References BLI_path_abs(), BLI_path_frame(), BLI_snprintf(), BLI_split_dirfile(), BLI_strncpy(), MovieClipProxy::dir, FILE_MAX, MovieClip::flag, G, MCLIP_USE_PROXY_CUSTOM_DIR, MovieClip::name, MovieClip::proxy, rendersize_to_number(), and size().
Referenced by movieclip_build_proxy_ibuf(), and movieclip_load_sequence_file().
static void get_sequence_fname (MovieClip * clip, int framenr, char * name) [static]
Definition at line 147 of file movieclip.c.
References BLI_path_abs(), BLI_stringdec(), BLI_stringenc(), BLI_strncpy(), FILE_MAX, G, MovieClip::id, ID_BLEND_PATH, MovieClip::name, sequence_guess_offset(), and strlen().
Referenced by movieclip_calc_length(), and movieclip_load_sequence_file().
static ImBuf* get_stable_cached_frame (MovieClip * clip, MovieClipUser * user, int framenr, int postprocess_flag) [static]
Definition at line 766 of file movieclip.c.
References MovieClipCache::angle, MovieClipCache::aspect, BKE_tracking_stabilization_data(), MovieClip::cache, MovieTracking::camera, equals_v2v2(), MovieTrackingStabilization::filter, MovieClipCache::filter, MovieClip::flag, MovieClipCache::framenr, MovieClipCache::ibuf, IMB_PROXY_NONE, IMB_refImBuf(), MovieClipCache::loc, MCLIP_USE_PROXY, NULL, MovieTrackingCamera::pixel_aspect, MovieClipCache::postprocess_flag, MovieClipCache::proxy, MovieClipCache::render_flag, MovieClipUser::render_flag, rendersize_to_proxy(), MovieClipCache::scale, MovieTracking::stabilization, MovieClipCache::stabilized, MovieClip::tracking, ImBuf::x, and ImBuf::y.
Referenced by BKE_movieclip_get_stable_ibuf().
static int get_timecode (MovieClip * clip, int flag) [static]
Definition at line 139 of file movieclip.c.
References IMB_TC_NONE, MCLIP_USE_PROXY, MovieClip::proxy, and MovieClipProxy::tc.
Referenced by movieclip_load_movie_file().
static ImBuf* get_undistorted_ibuf (MovieClip * clip, struct MovieDistortion * distortion, ImBuf * ibuf) [static]
Definition at line 539 of file movieclip.c.
References BKE_tracking_distortion_exec(), BKE_tracking_undistort(), IB_RECT_INVALID, imb_freerectfloatImBuf(), IMB_rect_from_float(), IMB_scaleImBuf(), MovieClip::tracking, ImBuf::userflags, ImBuf::x, and ImBuf::y.
Referenced by BKE_movieclip_build_proxy_frame(), and put_postprocessed_frame_to_cache().
static int moviecache_hashcmp (const void * av, const void * bv) [static]
Definition at line 356 of file movieclip.c.
References MovieClipImBufCacheKey::framenr, MovieClipImBufCacheKey::proxy, and MovieClipImBufCacheKey::render_flag.
Referenced by put_imbuf_cache().
static unsigned int moviecache_hashhash (const void * keyv) [static]
Definition at line 348 of file movieclip.c.
References MovieClipImBufCacheKey::framenr.
Referenced by put_imbuf_cache().
static void moviecache_keydata (void * userkey, int * framenr, int * proxy, int * render_flags) [static]
Definition at line 339 of file movieclip.c.
References MovieClipImBufCacheKey::framenr, MovieClipImBufCacheKey::proxy, and MovieClipImBufCacheKey::render_flag.
Referenced by put_imbuf_cache().
static MovieClip* movieclip_alloc (const char * name) [static]
Definition at line 429 of file movieclip.c.
References alloc_libblock(), MovieClip::aspx, MovieClip::aspy, BKE_tracking_init_settings(), MovieClipProxy::build_size_flag, MovieClipProxy::build_tc_flag, G, ID_MC, IMB_PROXY_25, IMB_TC_FREE_RUN, IMB_TC_INTERPOLATED_REC_DATE_FREE_RUN, IMB_TC_RECORD_RUN, IMB_TC_RECORD_RUN_NO_GAPS, MovieClip::proxy, MovieClipProxy::quality, and MovieClip::tracking.
Referenced by BKE_add_movieclip_file().
static void movieclip_build_proxy_ibuf (MovieClip * clip, ImBuf * ibuf, int cfra, int proxy_render_size, int undistorted) [static]
Definition at line 1089 of file movieclip.c.
References BLI_lock_thread(), BLI_make_existing_file(), BLI_unlock_thread(), FILE_MAX, ImBuf::ftype, get_proxy_fname(), IB_rect, IMB_dupImBuf(), IMB_freeImBuf(), IMB_saveiff(), IMB_scaleImBuf(), JPG, LOCK_MOVIECLIP, ImBuf::planes, MovieClip::proxy, MovieClipProxy::quality, rendersize_to_number(), size(), ImBuf::x, and ImBuf::y.
Referenced by BKE_movieclip_build_proxy_frame().
static void movieclip_calc_length (MovieClip * clip) [static]
Definition at line 265 of file movieclip.c.
References MovieClip::anim, BLI_exists(), BLI_stringdec(), FILE_MAX, get_sequence_fname(), IMB_anim_get_duration(), MovieClip::len, MCLIP_SRC_MOVIE, MCLIP_SRC_SEQUENCE, movieclip_open_anim_file(), MovieClip::name, ImBuf::name, MovieClip::proxy, MovieClip::source, and MovieClipProxy::tc.
Referenced by BKE_add_movieclip_file(), BKE_movieclip_get_duration(), and BKE_movieclip_reload().
static ImBuf* movieclip_get_postprocessed_ibuf (MovieClip * clip, MovieClipUser * user, int flag, int postprocess_flag, int cache_flag) [static]
Definition at line 695 of file movieclip.c.
References BLI_lock_thread(), BLI_unlock_thread(), FALSE, MovieClipUser::framenr, get_imbuf_cache(), get_postprocessed_cached_frame(), IMB_freeImBuf(), MovieClip::lastframe, MovieClip::lastsize, LOCK_MOVIECLIP, MCLIP_PROXY_RENDER_SIZE_FULL, MCLIP_PROXY_RENDER_UNDISTORT, MCLIP_SRC_SEQUENCE, MOVIECLIP_CACHE_SKIP, movieclip_load_movie_file(), movieclip_load_sequence_file(), need_postprocessed_frame(), NULL, put_imbuf_cache(), put_postprocessed_frame_to_cache(), real_ibuf_size(), MovieClipUser::render_flag, MovieClipUser::render_size, MovieClip::source, and TRUE.
Referenced by BKE_movieclip_get_ibuf_flag(), and BKE_movieclip_get_postprocessed_ibuf().
static ImBuf* movieclip_load_movie_file (MovieClip * clip, MovieClipUser * user, int framenr, int flag) [static]
Definition at line 238 of file movieclip.c.
References MovieClip::anim, get_timecode(), IMB_anim_absolute(), IMB_anim_get_duration(), movieclip_open_anim_file(), NULL, and rendersize_to_proxy().
Referenced by movieclip_get_postprocessed_ibuf().
static ImBuf* movieclip_load_sequence_file (MovieClip * clip, MovieClipUser * user, int framenr, int flag) [static]
Definition at line 194 of file movieclip.c.
References FILE_MAX, get_proxy_fname(), get_sequence_fname(), IB_multilayer, IB_rect, if(), IMB_loadiffname(), MCLIP_PROXY_RENDER_SIZE_FULL, MCLIP_PROXY_RENDER_UNDISTORT, MCLIP_USE_PROXY, ImBuf::name, MovieClipUser::render_flag, and MovieClipUser::render_size.
Referenced by movieclip_get_postprocessed_ibuf().
static void movieclip_open_anim_file (MovieClip * clip) [static]
Definition at line 216 of file movieclip.c.
References MovieClip::anim, BLI_path_abs(), BLI_strncpy(), MovieClipProxy::dir, FILE_MAX, MovieClip::flag, G, IB_rect, MovieClip::id, ID_BLEND_PATH, IMB_anim_set_index_dir(), MCLIP_USE_PROXY_CUSTOM_DIR, MovieClip::name, openanim(), MovieClip::proxy, and str.
Referenced by movieclip_calc_length(), and movieclip_load_movie_file().
static int need_postprocessed_frame (MovieClipUser * user, int flag, int postprocess_flag) [static]
Definition at line 575 of file movieclip.c.
References need_undistortion_postprocess().
Referenced by movieclip_get_postprocessed_ibuf().
static int need_undistortion_postprocess (MovieClipUser * user, int flag) [static]
Definition at line 562 of file movieclip.c.
References MCLIP_PROXY_RENDER_SIZE_FULL, MCLIP_PROXY_RENDER_UNDISTORT, MCLIP_USE_PROXY, MovieClipUser::render_flag, and MovieClipUser::render_size.
Referenced by get_postprocessed_cached_frame(), need_postprocessed_frame(), and put_postprocessed_frame_to_cache().
static void put_imbuf_cache (MovieClip * clip, MovieClipUser * user, ImBuf * ibuf, int flag) [static]
Definition at line 401 of file movieclip.c.
References MovieClip::cache, MovieClipUser::framenr, MovieClipImBufCacheKey::framenr, IMB_moviecache_create(), IMB_moviecache_put(), IMB_PROXY_NONE, MCLIP_USE_PROXY, MEM_callocN(), MovieClipCache::moviecache, moviecache_hashcmp(), moviecache_hashhash(), moviecache_keydata(), MovieClipImBufCacheKey::proxy, MovieClipImBufCacheKey::render_flag, MovieClipUser::render_flag, and rendersize_to_proxy().
Referenced by movieclip_get_postprocessed_ibuf().
static ImBuf* put_postprocessed_frame_to_cache (MovieClip * clip, MovieClipUser * user, ImBuf * ibuf, int flag, int postprocess_flag) [static]
Definition at line 638 of file movieclip.c.
References BKE_tracking_disable_imbuf_channels(), MovieClip::cache, MovieTracking::camera, copy_v2_v2(), copy_v3_v3(), FALSE, MovieClipCache::flag, MovieClipUser::framenr, MovieClipCache::framenr, get_undistorted_ibuf(), MovieClipCache::ibuf, IMB_dupImBuf(), IMB_freeImBuf(), IMB_PROXY_NONE, IMB_refImBuf(), MovieTrackingCamera::k1, MovieClipCache::k1, MCLIP_USE_PROXY, MOVIECLIP_DISABLE_BLUE, MOVIECLIP_DISABLE_GREEN, MOVIECLIP_DISABLE_RED, MOVIECLIP_PREVIEW_GRAYSCALE, need_undistortion_postprocess(), NULL, MovieClipCache::postprocessed, MovieTrackingCamera::principal, MovieClipCache::principal, MovieClipCache::proxy, MovieClipUser::render_flag, MovieClipCache::render_flag, rendersize_to_proxy(), MovieClipCache::stabilized, MovieClip::tracking, TRUE, and MovieClipCache::undistoriton_used.
Referenced by movieclip_get_postprocessed_ibuf().
static ImBuf* put_stabilized_frame_to_cache (MovieClip * clip, MovieClipUser * user, ImBuf * ibuf, int framenr, int postprocess_flag) [static]
Definition at line 815 of file movieclip.c.
References MovieClipCache::angle, MovieClipCache::aspect, BKE_tracking_stabilize(), MovieClip::cache, MovieTracking::camera, copy_v2_v2(), MovieTrackingStabilization::filter, MovieClipCache::filter, MovieClip::flag, MovieClipCache::framenr, MovieClipCache::ibuf, IMB_freeImBuf(), IMB_PROXY_NONE, IMB_refImBuf(), MovieClipCache::loc, MCLIP_USE_PROXY, MovieTrackingCamera::pixel_aspect, MovieClipCache::postprocess_flag, MovieClipCache::proxy, MovieClipUser::render_flag, MovieClipCache::render_flag, rendersize_to_proxy(), MovieClipCache::scale, MovieTracking::stabilization, MovieClipCache::stabilized, and MovieClip::tracking.
Referenced by BKE_movieclip_get_stable_ibuf().
static void real_ibuf_size (MovieClip * clip, MovieClipUser * user, ImBuf * ibuf, int * width, int * height) [static]
Definition at line 514 of file movieclip.c.
References MovieClip::flag, MCLIP_PROXY_RENDER_SIZE_25, MCLIP_PROXY_RENDER_SIZE_50, MCLIP_PROXY_RENDER_SIZE_75, MCLIP_USE_PROXY, MovieClipUser::render_size, ImBuf::x, and ImBuf::y.
Referenced by BKE_movieclip_get_size(), and movieclip_get_postprocessed_ibuf().
static int rendersize_to_number (int render_size) [static]
Definition at line 117 of file movieclip.c.
References MCLIP_PROXY_RENDER_SIZE_100, MCLIP_PROXY_RENDER_SIZE_25, MCLIP_PROXY_RENDER_SIZE_50, MCLIP_PROXY_RENDER_SIZE_75, and MCLIP_PROXY_RENDER_SIZE_FULL.
Referenced by get_proxy_fname(), and movieclip_build_proxy_ibuf().
static int rendersize_to_proxy (MovieClipUser * user, int flag) [static]
Definition at line 92 of file movieclip.c.
References IMB_PROXY_100, IMB_PROXY_25, IMB_PROXY_50, IMB_PROXY_75, IMB_PROXY_NONE, MCLIP_PROXY_RENDER_SIZE_100, MCLIP_PROXY_RENDER_SIZE_25, MCLIP_PROXY_RENDER_SIZE_50, MCLIP_PROXY_RENDER_SIZE_75, MCLIP_PROXY_RENDER_SIZE_FULL, MCLIP_USE_PROXY, and MovieClipUser::render_size.
Referenced by BKE_movieclip_get_cache_segments(), get_imbuf_cache(), get_postprocessed_cached_frame(), get_stable_cached_frame(), movieclip_load_movie_file(), put_imbuf_cache(), put_postprocessed_frame_to_cache(), and put_stabilized_frame_to_cache().
static int sequence_guess_offset (const char * full_name, int head_len, unsigned short numlen) [static]
Definition at line 83 of file movieclip.c.
References BLI_strncpy(), and FILE_MAX.
Referenced by get_sequence_fname().
void unlink_movieclip (Main * bmain, MovieClip * clip)
Definition at line 1159 of file movieclip.c.
References bScreen::areabase, View3D::bgpicbase, bObjectSolverConstraint::clip, bCameraSolverConstraint::clip, bFollowTrackConstraint::clip, Scene::clip, BGpic::clip, SpaceClip::clip, constraint_get_typeinfo(), CONSTRAINT_TYPE_CAMERASOLVER, CONSTRAINT_TYPE_FOLLOWTRACK, CONSTRAINT_TYPE_OBJECTSOLVER, Object::constraints, bConstraint::data, data, ListBase::first, MovieClip::id, Object::id, Scene::id, bScreen::id, if(), bConstraint::next, BGpic::next, SpaceLink::next, ScrArea::next, ID::next, NULL, Main::object, Main::scene, Main::screen, SPACE_CLIP, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, bConstraintTypeInfo::type, and ID::us.