Blender: rna_gpencil.c File Reference
rna_gpencil.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_gpencil_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "WM_types.h"
Functions
static void rna_def_gpencil_stroke_point (BlenderRNA *brna)
static void rna_def_gpencil_stroke (BlenderRNA *brna)
static void rna_def_gpencil_frame (BlenderRNA *brna)
static void rna_def_gpencil_layer (BlenderRNA *brna)
static void rna_def_gpencil_layers (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_gpencil_data (BlenderRNA *brna)
void RNA_def_gpencil (BlenderRNA *brna)
Detailed Description
Definition in file rna_gpencil.c.
Function Documentation
void RNA_def_gpencil (BlenderRNA * brna)
Definition at line 356 of file rna_gpencil.c.
References rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_stroke(), and rna_def_gpencil_stroke_point().
static void rna_def_gpencil_data (BlenderRNA * brna) [static]
Definition at line 317 of file rna_gpencil.c.
References GP_DATA_DEPTH_STROKE, GP_DATA_DEPTH_STROKE_ENDPOINTS, GP_DATA_DEPTH_VIEW, GP_DATA_VIEWALIGN, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_NONE, rna_def_gpencil_layers(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_gpencil().
static void rna_def_gpencil_frame (BlenderRNA * brna) [static]
Definition at line 147 of file rna_gpencil.c.
References GP_FRAME_PAINT, GP_FRAME_SELECT, MAXFRAME, MINFRAME, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_gpencil().
static void rna_def_gpencil_layer (BlenderRNA * brna) [static]
Definition at line 178 of file rna_gpencil.c.
References GP_LAYER_ACTIVE, GP_LAYER_DRAWDEBUG, GP_LAYER_FRAMELOCK, GP_LAYER_HIDE, GP_LAYER_LOCKED, GP_LAYER_NO_XRAY, GP_LAYER_ONIONSKIN, GP_LAYER_SELECT, NC_SCREEN, ND_GPENCIL, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_sdna(), RNA_def_property_editable_func(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_gpencil().
static void rna_def_gpencil_layers (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 282 of file rna_gpencil.c.
References CU_POLY, curve_type_items, FUNC_USE_REPORTS, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by rna_def_gpencil_data().
static void rna_def_gpencil_stroke (BlenderRNA * brna) [static]
Definition at line 128 of file rna_gpencil.c.
References NULL, PROP_COLLECTION, PROP_NONE, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_gpencil().
static void rna_def_gpencil_stroke_point (BlenderRNA * brna) [static]
Definition at line 106 of file rna_gpencil.c.
References NC_SCREEN, ND_GPENCIL, NULL, PROP_FLOAT, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_gpencil().