Blender: svm_image.h File Reference
svm_image.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float4 svm_image_texture (KernelGlobals *kg, int id, float x, float y)
__device void svm_node_tex_image (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node)
__device void svm_node_tex_environment (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node)
Function Documentation
CCL_NAMESPACE_BEGIN __device float4 svm_image_texture (KernelGlobals * kg, int id, float x, float y)
Definition at line 21 of file svm_image.h.
References kernel_assert, kernel_tex_image_interp, and make_float4().
Referenced by svm_node_tex_environment(), and svm_node_tex_image().
__device void svm_node_tex_environment (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node)
Definition at line 170 of file svm_image.h.
References co, color_srgb_to_scene_linear(), decode_node_uchar4(), direction_to_equirectangular(), direction_to_mirrorball(), make_float3(), normalize(), stack_load_float3(), stack_store_float(), stack_store_float3(), stack_valid(), svm_image_texture(), float4::w, uint4::w, float3::x, float4::x, float2::x, float3::y, float4::y, float2::y, uint4::y, float3::z, float4::z, and uint4::z.
Referenced by svm_eval_nodes().
__device void svm_node_tex_image (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node)
Definition at line 147 of file svm_image.h.
References co, color_srgb_to_scene_linear(), decode_node_uchar4(), make_float3(), stack_load_float3(), stack_store_float(), stack_store_float3(), stack_valid(), svm_image_texture(), float4::w, float4::x, float3::x, float4::y, float3::y, uint4::y, float3::z, float4::z, and uint4::z.
Referenced by svm_eval_nodes().