Blender: AUD_I3DHandle Class Reference
AUD_I3DHandle Class Reference
#include <AUD_I3DHandle.h>
Public Member Functions
virtual ~AUD_I3DHandle ()
virtual AUD_Vector3 getSourceLocation ()=0
virtual bool setSourceLocation (const AUD_Vector3 &location)=0
virtual AUD_Vector3 getSourceVelocity ()=0
virtual bool setSourceVelocity (const AUD_Vector3 &velocity)=0
virtual AUD_Quaternion getSourceOrientation ()=0
virtual bool setSourceOrientation (const AUD_Quaternion &orientation)=0
virtual bool isRelative ()=0
virtual bool setRelative (bool relative)=0
virtual float getVolumeMaximum ()=0
virtual bool setVolumeMaximum (float volume)=0
virtual float getVolumeMinimum ()=0
virtual bool setVolumeMinimum (float volume)=0
virtual float getDistanceMaximum ()=0
virtual bool setDistanceMaximum (float distance)=0
virtual float getDistanceReference ()=0
virtual bool setDistanceReference (float distance)=0
virtual float getAttenuation ()=0
virtual bool setAttenuation (float factor)=0
virtual float getConeAngleOuter ()=0
virtual bool setConeAngleOuter (float angle)=0
virtual float getConeAngleInner ()=0
virtual bool setConeAngleInner (float angle)=0
virtual float getConeVolumeOuter ()=0
virtual bool setConeVolumeOuter (float volume)=0
Detailed Description
This class represents a playback handle for 3D sources.
Definition at line 39 of file AUD_I3DHandle.h.
Constructor & Destructor Documentation
virtual AUD_I3DHandle::~AUD_I3DHandle () [inline, virtual]
Destroys the handle.
Definition at line 45 of file AUD_I3DHandle.h.
Member Function Documentation
virtual float AUD_I3DHandle::getAttenuation () [pure virtual]
Retrieves the attenuation of a source.
Returns:
The attenuation.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_attenuation().
virtual float AUD_I3DHandle::getConeAngleInner () [pure virtual]
Retrieves the inner angle of the cone of a source.
Returns:
The inner angle of the cone.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_cone_angle_inner().
virtual float AUD_I3DHandle::getConeAngleOuter () [pure virtual]
Retrieves the outer angle of the cone of a source.
Returns:
The outer angle of the cone.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_cone_angle_outer().
virtual float AUD_I3DHandle::getConeVolumeOuter () [pure virtual]
Retrieves the outer volume of the cone of a source. The volume between inner and outer angle is interpolated between inner volume and this value.
Returns:
The outer volume of the cone.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_cone_volume_outer().
virtual float AUD_I3DHandle::getDistanceMaximum () [pure virtual]
Retrieves the maximum distance of a source. If a source is further away from the reader than this distance, the volume will automatically be set to 0.
Returns:
The maximum distance.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_distance_maximum().
virtual float AUD_I3DHandle::getDistanceReference () [pure virtual]
Retrieves the reference distance of a source.
Returns:
The reference distance.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_distance_reference().
virtual AUD_Vector3 AUD_I3DHandle::getSourceLocation () [pure virtual]
Retrieves the location of a source.
Returns:
The location.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_location().
virtual AUD_Quaternion AUD_I3DHandle::getSourceOrientation () [pure virtual]
Retrieves the orientation of a source.
Returns:
The orientation as quaternion.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_orientation().
virtual AUD_Vector3 AUD_I3DHandle::getSourceVelocity () [pure virtual]
Retrieves the velocity of a source.
Returns:
The velocity.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_velocity().
virtual float AUD_I3DHandle::getVolumeMaximum () [pure virtual]
Retrieves the maximum volume of a source.
Returns:
The maximum volume.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_volume_maximum().
virtual float AUD_I3DHandle::getVolumeMinimum () [pure virtual]
Retrieves the minimum volume of a source.
Returns:
The minimum volume.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_volume_minimum().
virtual bool AUD_I3DHandle::isRelative () [pure virtual]
Checks whether the source location, velocity and orientation are relative to the listener.
Returns:
Whether the source is relative.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_get_relative().
virtual bool AUD_I3DHandle::setAttenuation (float factor) [pure virtual]
Sets the attenuation of a source. This value is used for distance calculation.
Parameters:
factor The new attenuation.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_attenuation().
virtual bool AUD_I3DHandle::setConeAngleInner (float angle) [pure virtual]
Sets the inner angle of the cone of a source.
Parameters:
angle The new inner angle of the cone.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_cone_angle_inner().
virtual bool AUD_I3DHandle::setConeAngleOuter (float angle) [pure virtual]
Sets the outer angle of the cone of a source.
Parameters:
angle The new outer angle of the cone.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_cone_angle_outer().
virtual bool AUD_I3DHandle::setConeVolumeOuter (float volume) [pure virtual]
Sets the outer volume of the cone of a source. The volume between inner and outer angle is interpolated between inner volume and this value.
Parameters:
volume The new outer volume of the cone.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_cone_volume_outer().
virtual bool AUD_I3DHandle::setDistanceMaximum (float distance) [pure virtual]
Sets the maximum distance of a source. If a source is further away from the reader than this distance, the volume will automatically be set to 0.
Parameters:
distance The new maximum distance.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_distance_maximum().
virtual bool AUD_I3DHandle::setDistanceReference (float distance) [pure virtual]
Sets the reference distance of a source.
Parameters:
distance The new reference distance.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_distance_reference().
virtual bool AUD_I3DHandle::setRelative (bool relative) [pure virtual]
Sets whether the source location, velocity and orientation are relative to the listener.
Parameters:
relative Whether the source is relative.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_relative().
virtual bool AUD_I3DHandle::setSourceLocation (const AUD_Vector3 & location) [pure virtual]
Sets the location of a source.
Parameters:
location The new location.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_location().
virtual bool AUD_I3DHandle::setSourceOrientation (const AUD_Quaternion & orientation) [pure virtual]
Sets the orientation of a source.
Parameters:
orientation The new orientation as quaternion.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_orientation().
virtual bool AUD_I3DHandle::setSourceVelocity (const AUD_Vector3 & velocity) [pure virtual]
Sets the velocity of a source.
Parameters:
velocity The new velocity.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_velocity().
virtual bool AUD_I3DHandle::setVolumeMaximum (float volume) [pure virtual]
Sets the maximum volume of a source.
Parameters:
volume The new maximum volume.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_volume_maximum().
virtual bool AUD_I3DHandle::setVolumeMinimum (float volume) [pure virtual]
Sets the minimum volume of a source.
Parameters:
volume The new minimum volume.
Returns:
Whether the action succeeded.
Implemented in AUD_SoftwareDevice::AUD_SoftwareHandle.
Referenced by Handle_set_volume_minimum().
The documentation for this class was generated from the following file:
AUD_I3DHandle.h