Blender: bsdf_ashikhmin_velvet.h File Reference
bsdf_ashikhmin_velvet.h File Reference
Classes
struct BsdfAshikhminVelvetClosure
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct
BsdfAshikhminVelvetClosure BsdfAshikhminVelvetClosure
Functions
__device void bsdf_ashikhmin_velvet_setup (ShaderData *sd, ShaderClosure *sc, float sigma)
__device void bsdf_ashikhmin_velvet_blur (ShaderClosure *sc, float roughness)
__device float3 bsdf_ashikhmin_velvet_eval_reflect (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float3 bsdf_ashikhmin_velvet_eval_transmit (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float bsdf_ashikhmin_velvet_albedo (const ShaderData *sd, const ShaderClosure *sc, const float3 I)
__device int bsdf_ashikhmin_velvet_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, float3 *domega_in_dx, float3 *domega_in_dy, float *pdf)
Typedef Documentation
typedef CCL_NAMESPACE_BEGIN struct BsdfAshikhminVelvetClosure BsdfAshikhminVelvetClosure
Function Documentation
__device float bsdf_ashikhmin_velvet_albedo (const ShaderData * sd, const ShaderClosure * sc, const float3 I)
Definition at line 101 of file bsdf_ashikhmin_velvet.h.
__device void bsdf_ashikhmin_velvet_blur (ShaderClosure * sc, float roughness)
Definition at line 54 of file bsdf_ashikhmin_velvet.h.
Referenced by svm_bsdf_blur().
__device float3 bsdf_ashikhmin_velvet_eval_reflect (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 58 of file bsdf_ashikhmin_velvet.h.
References D(), ShaderClosure::data0, dot(), expf, fabsf, fmaxf, G, H, M_1_PI_F, make_float3(), min, ShaderData::N, and normalize().
Referenced by svm_bsdf_eval().
__device float3 bsdf_ashikhmin_velvet_eval_transmit (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 96 of file bsdf_ashikhmin_velvet.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device int bsdf_ashikhmin_velvet_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, float3 * domega_in_dx, float3 * domega_in_dy, float * pdf)
Definition at line 106 of file bsdf_ashikhmin_velvet.h.
References D(), ShaderClosure::data0, ShaderData::dI, dot(), differential3::dx, differential3::dy, expf, fabsf, fmaxf, G, H, ShaderData::I, LABEL_DIFFUSE, LABEL_REFLECT, M_1_PI_F, make_float3(), min, ShaderData::N, ShaderData::Ng, normalize(), and sample_uniform_hemisphere().
Referenced by svm_bsdf_sample().
__device void bsdf_ashikhmin_velvet_setup (ShaderData * sd, ShaderClosure * sc, float sigma)
Definition at line 43 of file bsdf_ashikhmin_velvet.h.
References CLOSURE_BSDF_ASHIKHMIN_VELVET_ID, ShaderClosure::data0, ShaderData::flag, fmaxf, SD_BSDF, SD_BSDF_HAS_EVAL, and ShaderClosure::type.
Referenced by svm_node_closure_bsdf().