Blender: clip_graph_draw.c File Reference
clip_graph_draw.c File Reference
#include "DNA_movieclip_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
#include "BKE_context.h"
#include "BKE_movieclip.h"
#include "BKE_tracking.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_string.h"
#include "ED_screen.h"
#include "ED_clip.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "BLF_api.h"
#include "clip_intern.h"
Functions
static void draw_curve_knot (float x, float y, float xscale, float yscale, float hsize)
static void draw_graph_cfra (SpaceClip *sc, ARegion *ar, Scene *scene)
static void draw_graph_sfra_efra (Scene *scene, View2D *v2d)
static void tracking_segment_point_cb (void *UNUSED(userdata), MovieTrackingTrack *UNUSED(track), MovieTrackingMarker *marker, int UNUSED(coord), float val)
void tracking_segment_start_cb (void *userdata, MovieTrackingTrack *track, int coord)
void tracking_segment_end_cb (void *UNUSED(userdata))
static void tracking_segment_knot_cb (void *userdata, MovieTrackingTrack *track, MovieTrackingMarker *marker, int coord, float val)
static void draw_tracks_curves (View2D *v2d, SpaceClip *sc)
static void draw_frame_curves (SpaceClip *sc)
void clip_draw_graph (SpaceClip *sc, ARegion *ar, Scene *scene)
Detailed Description
Definition in file clip_graph_draw.c.
Function Documentation
void clip_draw_graph (SpaceClip * sc, ARegion * ar, Scene * scene)
Definition at line 262 of file clip_graph_draw.c.
References draw_frame_curves(), draw_graph_cfra(), draw_graph_sfra_efra(), draw_tracks_curves(), ED_space_clip(), SpaceClip::flag, SC_SHOW_GRAPH_FRAMES, SC_SHOW_GRAPH_TRACKS, UI_view2d_grid_calc(), UI_view2d_grid_draw(), UI_view2d_grid_free(), ARegion::v2d, V2D_GRID_NOCLAMP, V2D_GRIDLINES_ALL, V2D_UNIT_FRAMESCALE, V2D_UNIT_VALUES, ARegion::winx, and ARegion::winy.
Referenced by clip_preview_area_draw().
static void draw_curve_knot (float x, float y, float xscale, float yscale, float hsize) [static]
Definition at line 62 of file clip_graph_draw.c.
Referenced by tracking_segment_knot_cb().
static void draw_frame_curves (SpaceClip * sc) [static]
Definition at line 231 of file clip_graph_draw.c.
References BKE_tracking_get_reconstruction(), MovieTrackingReconstruction::cameras, MovieTrackingReconstruction::camnr, ED_space_clip(), MovieReconstructedCamera::error, MovieReconstructedCamera::framenr, i, and MovieClip::tracking.
Referenced by clip_draw_graph().
static void draw_graph_cfra (SpaceClip * sc, ARegion * ar, Scene * scene) [static]
Definition at line 90 of file clip_graph_draw.c.
References clip_draw_curfra_label(), View2D::cur, RenderData::framelen, MovieClipUser::framenr, Scene::r, TH_CFRAME, UI_ThemeColor(), UI_view2d_getscale(), UI_view2d_view_orthoSpecial(), SpaceClip::user, ARegion::v2d, rctf::ymax, and rctf::ymin.
Referenced by clip_draw_graph().
static void draw_graph_sfra_efra (Scene * scene, View2D * v2d) [static]
Definition at line 124 of file clip_graph_draw.c.
References View2D::cur, EFRA, fdrawline(), SFRA, TH_BACK, UI_ThemeColorShade(), UI_view2d_view_ortho(), rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by clip_draw_graph().
static void draw_tracks_curves (View2D * v2d, SpaceClip * sc) [static]
Definition at line 201 of file clip_graph_draw.c.
References BKE_movieclip_get_size(), BKE_tracking_active_track(), clip_graph_tracking_values_iterate(), ED_space_clip(), FALSE, NULL, TH_HANDLE_VERTEX_SIZE, MovieClip::tracking, tracking_segment_end_cb(), tracking_segment_knot_cb(), tracking_segment_point_cb(), tracking_segment_start_cb(), TRUE, UI_GetThemeValuef(), UI_view2d_getscale(), and SpaceClip::user.
Referenced by clip_draw_graph().
void tracking_segment_end_cb (void * UNUSEDuserdata)
Definition at line 172 of file clip_graph_draw.c.
Referenced by draw_tracks_curves().
static void tracking_segment_knot_cb (void * userdata, MovieTrackingTrack * track, MovieTrackingMarker * marker, int coord, float val) [static]
Definition at line 179 of file clip_graph_draw.c.
References data, draw_curve_knot(), MovieTrackingMarker::flag, MovieTrackingMarker::framenr, MARKER_GRAPH_SEL_X, MARKER_GRAPH_SEL_Y, TH_HANDLE_VERTEX, TH_HANDLE_VERTEX_SELECT, and UI_ThemeColor().
Referenced by draw_tracks_curves().
static void tracking_segment_point_cb (void * UNUSEDuserdata, MovieTrackingTrack * UNUSEDtrack, MovieTrackingMarker * marker, int UNUSEDcoord, float val) [static]
Definition at line 144 of file clip_graph_draw.c.
References MovieTrackingMarker::framenr.
Referenced by draw_tracks_curves().
void tracking_segment_start_cb (void * userdata, MovieTrackingTrack * track, int coord)
Definition at line 150 of file clip_graph_draw.c.
References copy_v3_v3().
Referenced by draw_tracks_curves().