Blender: RAS_texmatrix.cpp File Reference
RAS_texmatrix.cpp File Reference
Rasterizer
#include "RAS_TexMatrix.h"
Functions
void RAS_CalcTexMatrix (RAS_TexVert p[3], MT_Point3 &origin, MT_Vector3 &udir, MT_Vector3 &vdir)
Detailed Description
Definition in file RAS_texmatrix.cpp.
Function Documentation
void RAS_CalcTexMatrix (RAS_TexVert p[3], MT_Point3 & origin, MT_Vector3 & udir, MT_Vector3 & vdir)
Definition at line 35 of file RAS_texmatrix.cpp.
References MT_Vector3::closestAxis(), MT_Vector3::cross(), MT_Vector3::dot(), MT_Matrix3x3::inverse(), MT_Vector3::normalize(), MT_Tuple3::x(), RAS_TexVert::xyz(), MT_Tuple3::y(), and MT_Tuple3::z().