Blender: AUD_BandPassReader Class Reference
AUD_BandPassReader Class Reference
#include <AUD_BandPassReader.h>
Public Member Functions
AUD_BandPassReader (AUD_IReader *reader, float low, float high)
virtual ~AUD_BandPassReader ()
virtual AUD_ReaderType getType ()
virtual void read (int &length, sample_t *&buffer)
Detailed Description
This class only passes a specific frequency band of another reader.
Definition at line 41 of file AUD_BandPassReader.h.
Constructor & Destructor Documentation
AUD_BandPassReader::AUD_BandPassReader (AUD_IReader * reader, float low, float high)
Creates a new band pass reader.
Parameters:
reader The reader to read from.
low The lowest passed frequency.
high The highest passed frequency.
Definition at line 36 of file AUD_BandPassReader.cpp.
AUD_BandPassReader::~AUD_BandPassReader () [virtual]
Destroys the reader.
Definition at line 46 of file AUD_BandPassReader.cpp.
Member Function Documentation
AUD_ReaderType AUD_BandPassReader::getType (void) [virtual]
Definition at line 59 of file AUD_BandPassReader.cpp.
References AUD_EffectReader::m_reader.
void AUD_BandPassReader::read (int & length, sample_t *& buffer) [virtual]
Definition at line 64 of file AUD_BandPassReader.cpp.
References AUD_Buffer::assureSize(), AUD_SAMPLE_SIZE, AUD_Specs::channels, AUD_Buffer::getBuffer(), AUD_Buffer::getSize(), i, length(), AUD_EffectReader::m_reader, AUD_Specs::rate, and AUD_Buffer::resize().
The documentation for this class was generated from the following files:
AUD_BandPassReader.h
AUD_BandPassReader.cpp