Blender: rna_key.c File Reference
rna_key.c File Reference
RNA
#include <stdlib.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "DNA_curve_types.h"
#include "DNA_key_types.h"
#include "DNA_lattice_types.h"
#include "DNA_mesh_types.h"
Functions
static void rna_def_keydata (BlenderRNA *brna)
static void rna_def_keyblock (BlenderRNA *brna)
static void rna_def_key (BlenderRNA *brna)
void RNA_def_key (BlenderRNA *brna)
Detailed Description
Definition in file rna_key.c.
Function Documentation
static void rna_def_key (BlenderRNA * brna) [static]
Definition at line 597 of file rna_key.c.
References KEY_RELATIVE, MAXFRAME, MINFRAME, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, rna_def_animdata_common(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_key().
void RNA_def_key (BlenderRNA * brna)
Definition at line 645 of file rna_key.c.
References rna_def_key(), rna_def_keyblock(), and rna_def_keydata().
static void rna_def_keyblock (BlenderRNA * brna) [static]
Definition at line 513 of file rna_key.c.
References KEY_BSPLINE, KEY_CARDINAL, KEY_LINEAR, KEYBLOCK_MUTE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_key().
static void rna_def_keydata (BlenderRNA * brna) [static]
Definition at line 448 of file rna_key.c.
References NULL, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_array(), RNA_def_property_float_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), and RNA_def_struct_ui_text().
Referenced by RNA_def_key().