Blender: editarmature_sketch.c File Reference
editarmature_sketch.c File Reference
armature
#include <string.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_armature_types.h"
#include "RNA_define.h"
#include "RNA_access.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_graph.h"
#include "BLI_ghash.h"
#include "BKE_context.h"
#include "BKE_sketch.h"
#include "ED_view3d.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "ED_armature.h"
#include "armature_intern.h"
#include "BIF_retarget.h"
#include "BIF_generate.h"
#include "ED_transform.h"
#include "WM_api.h"
#include "WM_types.h"
#include "reeb.h"
Classes
struct SK_GestureAction
struct SK_StrokeIterator
Typedefs
typedef int(* GestureDetectFct)(bContext *, SK_Gesture *, SK_Sketch *)
typedef void(* GestureApplyFct)(bContext *, SK_Gesture *, SK_Sketch *)
typedef struct SK_GestureAction SK_GestureAction
typedef struct SK_StrokeIterator SK_StrokeIterator
Functions
void initStrokeIterator (BArcIterator *iter, SK_Stroke *stk, int start, int end)
int sk_detectCutGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
void sk_applyCutGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
int sk_detectTrimGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
void sk_applyTrimGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
int sk_detectCommandGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
void sk_applyCommandGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
int sk_detectDeleteGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
void sk_applyDeleteGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
int sk_detectMergeGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
void sk_applyMergeGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
int sk_detectReverseGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
void sk_applyReverseGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
int sk_detectConvertGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
void sk_applyConvertGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
SK_Sketch * contextSketch (const bContext *c, int create)
SK_Sketch * viewcontextSketch (ViewContext *vc, int create)
void sk_resetOverdraw (SK_Sketch *sketch)
int sk_hasOverdraw (SK_Sketch *sketch, SK_Stroke *stk)
void BIF_makeListTemplates (const bContext *C)
const char * BIF_listTemplates (const bContext *UNUSED(C))
int BIF_currentTemplate (const bContext *C)
static RigGraph * sk_makeTemplateGraph (const bContext *C, Object *ob)
int BIF_nbJointsTemplate (const bContext *C)
const char * BIF_nameBoneTemplate (const bContext *C)
void BIF_freeTemplates (bContext *UNUSED(C))
void BIF_setTemplate (bContext *C, int index)
static void sk_autoname (bContext *C, ReebArc *arc)
static ReebNode * sk_pointToNode (SK_Point *pt, float imat[][4], float tmat[][3])
static ReebArc * sk_strokeToArc (SK_Stroke *stk, float imat[][4], float tmat[][3])
static void sk_retargetStroke (bContext *C, SK_Stroke *stk)
static void sk_cancelStroke (SK_Sketch *sketch)
static float sk_clampPointSize (SK_Point *pt, float size)
static void sk_drawPoint (GLUquadric *quad, SK_Point *pt, float size)
static void sk_drawEdge (GLUquadric *quad, SK_Point *pt0, SK_Point *pt1, float size)
static void sk_drawNormal (GLUquadric *quad, SK_Point *pt, float size, float height)
static void sk_drawStroke (SK_Stroke *stk, int id, float color[3], int start, int end)
static void drawSubdividedStrokeBy (ToolSettings *toolsettings, BArcIterator *iter, NextSubdivisionFunc next_subdividion)
static void sk_drawStrokeSubdivision (ToolSettings *toolsettings, SK_Stroke *stk)
static SK_Point * sk_snapPointStroke (bContext *C, SK_Stroke *stk, int mval[2], int *dist, int *index, int all_pts)
static void sk_updateOverdraw (bContext *C, SK_Sketch *sketch, SK_Stroke *stk, SK_DrawData *dd)
static int sk_adjustIndexes (SK_Sketch *sketch, int *start, int *end)
static void sk_endOverdraw (SK_Sketch *sketch)
static void sk_startStroke (SK_Sketch *sketch)
static void sk_endStroke (bContext *C, SK_Sketch *sketch)
static void sk_updateDrawData (SK_DrawData *dd)
static float sk_distanceDepth (bContext *C, float p1[3], float p2[3])
static void sk_interpolateDepth (bContext *C, SK_Stroke *stk, int start, int end, float length, float distance)
static void sk_projectDrawPoint (bContext *C, float vec[3], SK_Stroke *stk, SK_DrawData *dd)
static int sk_getStrokeDrawPoint (bContext *C, SK_Point *pt, SK_Sketch *UNUSED(sketch), SK_Stroke *stk, SK_DrawData *dd)
static int sk_addStrokeDrawPoint (bContext *C, SK_Sketch *sketch, SK_Stroke *stk, SK_DrawData *dd)
static int sk_getStrokeSnapPoint (bContext *C, SK_Point *pt, SK_Sketch *sketch, SK_Stroke *stk, SK_DrawData *dd)
static int sk_addStrokeSnapPoint (bContext *C, SK_Sketch *sketch, SK_Stroke *stk, SK_DrawData *dd)
static void sk_addStrokePoint (bContext *C, SK_Sketch *sketch, SK_Stroke *stk, SK_DrawData *dd, short snap)
static void sk_getStrokePoint (bContext *C, SK_Point *pt, SK_Sketch *sketch, SK_Stroke *stk, SK_DrawData *dd, short snap)
static void * headPoint (void *arg)
static void * tailPoint (void *arg)
static void * nextPoint (void *arg)
static void * nextNPoint (void *arg, int n)
static void * peekPoint (void *arg, int n)
static void * previousPoint (void *arg)
static int iteratorStopped (void *arg)
static void initIteratorFct (SK_StrokeIterator *iter)
static SK_Point * setIteratorValues (SK_StrokeIterator *iter, int index)
static void sk_convertStroke (bContext *C, SK_Stroke *stk)
static void sk_convert (bContext *C, SK_Sketch *sketch)
static int sk_getSelfIntersections (bContext *C, ListBase *list, SK_Stroke *gesture)
static int cmpIntersections (void *i1, void *i2)
static int sk_getIntersections (bContext *C, ListBase *list, SK_Sketch *sketch, SK_Stroke *gesture)
static int sk_getSegments (SK_Stroke *segments, SK_Stroke *gesture)
int sk_detectCutGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
void sk_applyCutGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
int sk_detectTrimGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
void sk_applyTrimGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
int sk_detectCommandGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
void sk_applyCommandGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
int sk_detectDeleteGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
void sk_applyDeleteGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *sketch)
int sk_detectMergeGesture (bContext *C, SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
void sk_applyMergeGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
int sk_detectReverseGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
void sk_applyReverseGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
int sk_detectConvertGesture (bContext *UNUSED(C), SK_Gesture *gest, SK_Sketch *UNUSED(sketch))
void sk_applyConvertGesture (bContext *C, SK_Gesture *UNUSED(gest), SK_Sketch *sketch)
static void sk_initGesture (bContext *C, SK_Gesture *gest, SK_Sketch *sketch)
static void sk_freeGesture (SK_Gesture *gest)
static void sk_applyGesture (bContext *C, SK_Sketch *sketch)
static int sk_selectStroke (bContext *C, SK_Sketch *sketch, const int mval[2], int extend)
static void sk_drawSketch (Scene *scene, View3D *UNUSED(v3d), SK_Sketch *sketch, int with_names)
static int sk_finish_stroke (bContext *C, SK_Sketch *sketch)
static void sk_start_draw_stroke (SK_Sketch *sketch)
static void sk_start_draw_gesture (SK_Sketch *sketch)
static int sk_draw_stroke (bContext *C, SK_Sketch *sketch, SK_Stroke *stk, SK_DrawData *dd, short snap)
static int ValidSketchViewContext (ViewContext *vc)
int BDR_drawSketchNames (ViewContext *vc)
void BDR_drawSketch (const bContext *C)
static int sketch_delete (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
void BIF_sk_selectStroke (bContext *C, const int mval[2], short extend)
void BIF_convertSketch (bContext *C)
void BIF_deleteSketch (bContext *C)
static int sketch_convert (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static int sketch_cancel (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static int sketch_finish (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static int sketch_select (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
static int sketch_draw_stroke_cancel (bContext *C, wmOperator *op)
static int sketch_draw_stroke (bContext *C, wmOperator *op, wmEvent *event)
static int sketch_draw_gesture_cancel (bContext *C, wmOperator *op)
static int sketch_draw_gesture (bContext *C, wmOperator *op, wmEvent *event)
static int sketch_draw_modal (bContext *C, wmOperator *op, wmEvent *event, short gesture, SK_Stroke *stk)
static int sketch_draw_stroke_modal (bContext *C, wmOperator *op, wmEvent *event)
static int sketch_draw_gesture_modal (bContext *C, wmOperator *op, wmEvent *event)
static int sketch_draw_preview (bContext *C, wmOperator *op, wmEvent *event)
int ED_operator_sketch_mode_active_stroke (bContext *C)
static int ED_operator_sketch_mode_gesture (bContext *C)
int ED_operator_sketch_full_mode (bContext *C)
int ED_operator_sketch_mode (const bContext *C)
void SKETCH_OT_delete (wmOperatorType *ot)
void SKETCH_OT_select (wmOperatorType *ot)
void SKETCH_OT_cancel_stroke (wmOperatorType *ot)
void SKETCH_OT_convert (wmOperatorType *ot)
void SKETCH_OT_finish_stroke (wmOperatorType *ot)
void SKETCH_OT_draw_preview (wmOperatorType *ot)
void SKETCH_OT_draw_stroke (wmOperatorType *ot)
void SKETCH_OT_gesture (wmOperatorType *ot)
Variables
static int LAST_SNAP_POINT_VALID = 0
static float LAST_SNAP_POINT [3]
static SK_GestureAction GESTURE_ACTIONS []
static char * TEMPLATES_MENU = NULL
static int TEMPLATES_CURRENT = 0
static GHash * TEMPLATES_HASH = NULL
static RigGraph * TEMPLATE_RIGG = NULL
Detailed Description
Definition in file editarmature_sketch.c.
Typedef Documentation
typedef void(* GestureApplyFct)(bContext *, SK_Gesture *, SK_Sketch *)
Definition at line 74 of file editarmature_sketch.c.
typedef int(* GestureDetectFct)(bContext *, SK_Gesture *, SK_Sketch *)
Definition at line 73 of file editarmature_sketch.c.
typedef struct SK_GestureAction SK_GestureAction
typedef struct SK_StrokeIterator SK_StrokeIterator
Function Documentation
void BDR_drawSketch (const bContext * C)
Definition at line 2452 of file editarmature_sketch.c.
References contextSketch(), CTX_data_scene(), CTX_wm_view3d(), ED_operator_sketch_mode(), and sk_drawSketch().
Referenced by view3d_main_area_draw_objects().
int BDR_drawSketchNames (ViewContext * vc)
Definition at line 2437 of file editarmature_sketch.c.
References ViewContext::scene, sk_drawSketch(), ViewContext::v3d, ValidSketchViewContext(), and viewcontextSketch().
Referenced by view3d_opengl_select().
void BIF_convertSketch (bContext * C)
Definition at line 2488 of file editarmature_sketch.c.
References contextSketch(), ED_operator_sketch_full_mode(), and sk_convert().
int BIF_currentTemplate (const bContext * C)
Definition at line 222 of file editarmature_sketch.c.
References BLI_ghashIterator_getKey(), BLI_ghashIterator_getValue(), BLI_ghashIterator_init(), BLI_ghashIterator_isDone(), BLI_ghashIterator_step(), CTX_data_tool_settings(), GET_INT_FROM_POINTER, NULL, ToolSettings::skgen_template, and TEMPLATES_CURRENT.
void BIF_deleteSketch (bContext * C)
Definition at line 2503 of file editarmature_sketch.c.
References contextSketch(), ED_operator_sketch_full_mode(), and sk_deleteSelectedStrokes().
void BIF_freeTemplates (bContext * UNUSEDC)
Definition at line 315 of file editarmature_sketch.c.
References BLI_ghash_free(), MEM_freeN(), NULL, RIG_freeRigGraph(), and TEMPLATES_MENU.
Referenced by WM_exit_ext().
const char* BIF_listTemplates (const bContext * UNUSEDC)
Definition at line 190 of file editarmature_sketch.c.
References BLI_ghash_size(), BLI_ghashIterator_getKey(), BLI_ghashIterator_getValue(), BLI_ghashIterator_init(), BLI_ghashIterator_isDone(), BLI_ghashIterator_step(), GET_INT_FROM_POINTER, Object::id, MEM_callocN(), MEM_freeN(), ID::name, NULL, p, and TEMPLATES_MENU.
void BIF_makeListTemplates (const bContext * C)
Definition at line 157 of file editarmature_sketch.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_intcmp(), BLI_ghashutil_inthash(), CTX_data_edit_object(), CTX_data_scene(), CTX_data_tool_settings(), FIRSTBASE, Base::next, NULL, OB_ARMATURE, Base::object, SET_INT_IN_POINTER, ToolSettings::skgen_template, TEMPLATES_CURRENT, and Object::type.
const char* BIF_nameBoneTemplate (const bContext * C)
Definition at line 293 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, contextSketch(), CTX_data_tool_settings(), SK_Stroke::nb_points, NULL, RIG_nameBone(), sk_makeTemplateGraph(), and ToolSettings::skgen_template.
int BIF_nbJointsTemplate (const bContext * C)
Definition at line 278 of file editarmature_sketch.c.
References CTX_data_tool_settings(), RIG_nbJoints(), sk_makeTemplateGraph(), and ToolSettings::skgen_template.
void BIF_setTemplate (bContext * C, int index)
Definition at line 336 of file editarmature_sketch.c.
References BLI_ghash_lookup(), CTX_data_tool_settings(), NULL, RIG_freeRigGraph(), SET_INT_IN_POINTER, and ToolSettings::skgen_template.
void BIF_sk_selectStroke (bContext * C, const int mval[2], short extend)
Definition at line 2476 of file editarmature_sketch.c.
References ToolSettings::bone_sketching, BONE_SKETCHING, contextSketch(), CTX_data_tool_settings(), CTX_wm_area(), ED_area_tag_redraw(), NULL, and sk_selectStroke().
Referenced by mouse_armature().
static int cmpIntersections (void * i1, void * i2) [static]
Definition at line 1646 of file editarmature_sketch.c.
References SK_Intersection::before, SK_Intersection::lambda, and SK_Intersection::stroke.
Referenced by sk_getIntersections().
SK_Sketch * contextSketch (const bContext * c, int create)
Definition at line 2533 of file editarmature_sketch.c.
References createSketch(), CTX_data_edit_object(), Object::data, NULL, OB_ARMATURE, bArmature::sketch, and Object::type.
Referenced by BDR_drawSketch(), BIF_convertSketch(), BIF_deleteSketch(), BIF_nameBoneTemplate(), BIF_sk_selectStroke(), ED_operator_sketch_mode_active_stroke(), ED_operator_sketch_mode_gesture(), sketch_cancel(), sketch_convert(), sketch_delete(), sketch_draw_gesture(), sketch_draw_gesture_cancel(), sketch_draw_gesture_modal(), sketch_draw_modal(), sketch_draw_preview(), sketch_draw_stroke(), sketch_draw_stroke_cancel(), sketch_draw_stroke_modal(), sketch_finish(), and sketch_select().
static void drawSubdividedStrokeBy (ToolSettings * toolsettings, BArcIterator * iter, NextSubdivisionFunc next_subdividion) [static]
Definition at line 616 of file editarmature_sketch.c.
References copy_v3_v3(), BArcIterator::head, BArcIterator::length, BArcIterator::p, SK_Stroke::points, sk_drawNormal(), and sk_drawPoint().
Referenced by sk_drawStrokeSubdivision().
int ED_operator_sketch_full_mode (bContext * C)
Definition at line 2802 of file editarmature_sketch.c.
References ToolSettings::bone_sketching, BONE_SKETCHING, BONE_SKETCHING_QUICK, CTX_data_edit_object(), CTX_data_tool_settings(), OB_ARMATURE, and Object::type.
Referenced by BIF_convertSketch(), BIF_deleteSketch(), SKETCH_OT_convert(), SKETCH_OT_delete(), and SKETCH_OT_select().
int ED_operator_sketch_mode (const bContext * C)
Definition at line 2820 of file editarmature_sketch.c.
References ToolSettings::bone_sketching, BONE_SKETCHING, CTX_data_edit_object(), CTX_data_tool_settings(), OB_ARMATURE, and Object::type.
Referenced by BDR_drawSketch(), and SKETCH_OT_draw_stroke().
int ED_operator_sketch_mode_active_stroke (bContext * C)
Definition at line 2767 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, ToolSettings::bone_sketching, BONE_SKETCHING, contextSketch(), CTX_data_tool_settings(), and NULL.
Referenced by SKETCH_OT_cancel_stroke(), SKETCH_OT_draw_preview(), and SKETCH_OT_finish_stroke().
static int ED_operator_sketch_mode_gesture (bContext * C) [static]
Definition at line 2784 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, ToolSettings::bone_sketching, BONE_SKETCHING, BONE_SKETCHING_QUICK, contextSketch(), CTX_data_tool_settings(), and NULL.
Referenced by SKETCH_OT_gesture().
static void * headPoint (void * arg) [static]
Definition at line 1380 of file editarmature_sketch.c.
References SK_Point::no, SK_StrokeIterator::no, NULL, SK_Point::p, SK_StrokeIterator::p, SK_Stroke::points, SK_Point::size, SK_StrokeIterator::size, SK_StrokeIterator::start, SK_StrokeIterator::stride, and SK_StrokeIterator::stroke.
Referenced by initIteratorFct().
static void initIteratorFct (SK_StrokeIterator * iter) [static]
Definition at line 1322 of file editarmature_sketch.c.
References SK_StrokeIterator::head, headPoint(), iteratorStopped(), SK_StrokeIterator::next, SK_StrokeIterator::nextN, nextNPoint(), nextPoint(), SK_StrokeIterator::peek, peekPoint(), SK_StrokeIterator::previous, previousPoint(), SK_StrokeIterator::stopped, SK_StrokeIterator::tail, and tailPoint().
Referenced by initStrokeIterator().
void initStrokeIterator (BArcIterator * iter, SK_Stroke * stk, int start, int end)
Definition at line 1354 of file editarmature_sketch.c.
References SK_StrokeIterator::end, SK_StrokeIterator::index, initIteratorFct(), SK_StrokeIterator::length, SK_StrokeIterator::start, SK_StrokeIterator::stride, and SK_StrokeIterator::stroke.
Referenced by sk_convertStroke(), sk_drawStrokeSubdivision(), and sk_getSegments().
static int iteratorStopped (void * arg) [static]
Definition at line 1465 of file editarmature_sketch.c.
References SK_StrokeIterator::index, and SK_StrokeIterator::length.
Referenced by initIteratorFct().
static void * nextNPoint (void * arg, int n) [static]
Definition at line 1420 of file editarmature_sketch.c.
References SK_StrokeIterator::index, SK_StrokeIterator::length, NULL, and setIteratorValues().
Referenced by initIteratorFct().
static void * nextPoint (void * arg) [static]
Definition at line 1406 of file editarmature_sketch.c.
References SK_StrokeIterator::index, SK_StrokeIterator::length, NULL, and setIteratorValues().
Referenced by initIteratorFct().
static void * peekPoint (void * arg, int n) [static]
Definition at line 1436 of file editarmature_sketch.c.
References SK_StrokeIterator::index, length(), NULL, and setIteratorValues().
Referenced by initIteratorFct().
static void * previousPoint (void * arg) [static]
Definition at line 1451 of file editarmature_sketch.c.
References SK_StrokeIterator::index, NULL, and setIteratorValues().
Referenced by initIteratorFct().
static SK_Point* setIteratorValues (SK_StrokeIterator * iter, int index) [static]
Definition at line 1333 of file editarmature_sketch.c.
References length(), SK_Point::no, SK_StrokeIterator::no, NULL, SK_Point::p, SK_StrokeIterator::p, SK_Stroke::points, SK_Point::size, SK_StrokeIterator::size, SK_StrokeIterator::start, SK_StrokeIterator::stride, and SK_StrokeIterator::stroke.
Referenced by nextNPoint(), nextPoint(), peekPoint(), and previousPoint().
static int sk_addStrokeDrawPoint (bContext * C, SK_Sketch * sketch, SK_Stroke * stk, SK_DrawData * dd) [static]
Definition at line 1048 of file editarmature_sketch.c.
References CTX_wm_region(), ARegion::regiondata, sk_appendStrokePoint(), sk_getStrokeDrawPoint(), sk_initPoint(), and RegionView3D::viewinv.
Referenced by sk_addStrokePoint().
static void sk_addStrokePoint (bContext * C, SK_Sketch * sketch, SK_Stroke * stk, SK_DrawData * dd, short snap) [static]
Definition at line 1270 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, ToolSettings::bone_sketching, BONE_SKETCHING_ADJUST, CTX_data_tool_settings(), sk_addStrokeDrawPoint(), sk_addStrokeSnapPoint(), and sk_updateOverdraw().
Referenced by sk_draw_stroke().
static int sk_addStrokeSnapPoint (bContext * C, SK_Sketch * sketch, SK_Stroke * stk, SK_DrawData * dd) [static]
Definition at line 1219 of file editarmature_sketch.c.
References copy_v3_v3(), CTX_wm_region(), distance(), i, len_v3v3(), length(), SK_Point::mode, SK_Stroke::nb_points, SK_Point::p, SK_Stroke::points, PT_EXACT, PT_SNAP, ARegion::regiondata, sk_appendStrokePoint(), sk_distanceDepth(), sk_getStrokeSnapPoint(), sk_initPoint(), sk_interpolateDepth(), sk_projectDrawPoint(), SK_Point::type, and RegionView3D::viewinv.
Referenced by sk_addStrokePoint().
static int sk_adjustIndexes (SK_Sketch * sketch, int * start, int * end) [static]
Definition at line 879 of file editarmature_sketch.c.
References SK_Overdraw::end, SK_Stroke::nb_points, SK_Sketch::over, SK_Overdraw::start, and SK_Overdraw::target.
Referenced by sk_drawSketch(), and sk_endOverdraw().
void sk_applyCommandGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1893 of file editarmature_sketch.c.
References SK_Intersection::after, SK_Intersection::before, ListBase::first, SK_Gesture::intersections, SK_Intersection::next, SK_Intersection::p, sk_flattenStroke(), sk_polygonizeStroke(), sk_straightenStroke(), and SK_Intersection::stroke.
void sk_applyCommandGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
void sk_applyConvertGesture (bContext * C, SK_Gesture * UNUSEDgest, SK_Sketch * sketch)
Definition at line 2112 of file editarmature_sketch.c.
References sk_convert().
void sk_applyConvertGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
void sk_applyCutGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1793 of file editarmature_sketch.c.
References SK_Intersection::after, SK_Intersection::before, copy_v3_v3(), ListBase::first, SK_Gesture::intersections, SK_Point::mode, SK_Intersection::next, SK_Point::no, SK_Point::p, SK_Intersection::p, SK_Stroke::points, PT_EXACT, PT_PROJECT, sk_insertStrokePoint(), SK_Intersection::stroke, and SK_Point::type.
void sk_applyCutGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
void sk_applyDeleteGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
void sk_applyDeleteGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * sketch)
Definition at line 1949 of file editarmature_sketch.c.
References ListBase::first, SK_Gesture::intersections, SK_Intersection::next, sk_removeStroke(), and SK_Intersection::stroke.
static void sk_applyGesture (bContext * C, SK_Sketch * sketch) [static]
Definition at line 2137 of file editarmature_sketch.c.
References SK_GestureAction::apply, SK_GestureAction::detect, NULL, sk_freeGesture(), and sk_initGesture().
Referenced by sketch_draw_modal().
void sk_applyMergeGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 2013 of file editarmature_sketch.c.
References SK_Intersection::after, SK_Intersection::before, ListBase::first, i, SK_Gesture::intersections, MAX2, MIN2, SK_Intersection::next, SK_Stroke::points, PT_CONTINUOUS, PT_EXACT, SK_Intersection::stroke, and SK_Point::type.
void sk_applyMergeGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
void sk_applyReverseGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 2086 of file editarmature_sketch.c.
References ListBase::first, SK_Gesture::intersections, SK_Intersection::next, sk_reverseStroke(), and SK_Intersection::stroke.
void sk_applyReverseGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
void sk_applyTrimGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
void sk_applyTrimGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1831 of file editarmature_sketch.c.
References SK_Intersection::after, SK_Intersection::before, copy_v3_v3(), dot_v3v3(), ListBase::first, SK_Gesture::intersections, SK_Point::mode, SK_Stroke::nb_points, SK_Intersection::next, SK_Point::no, SK_Point::p, SK_Intersection::p, SK_Stroke::points, PT_EXACT, PT_PROJECT, SK_Gesture::segments, sk_replaceStrokePoint(), sk_trimStroke(), SK_Intersection::stroke, sub_v3_v3v3(), and SK_Point::type.
static void sk_autoname (bContext * C, ReebArc * arc) [static]
Definition at line 357 of file editarmature_sketch.c.
References BLI_snprintf(), CTX_data_tool_settings(), ReebArc::head, i, NULL, ReebNode::p, SK_RETARGET_AUTONAME, ToolSettings::skgen_num_string, ToolSettings::skgen_retarget_options, and ToolSettings::skgen_side_string.
Referenced by sk_retargetStroke().
static void sk_cancelStroke (SK_Sketch * sketch) [static]
Definition at line 474 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, NULL, sk_removeStroke(), and sk_resetOverdraw().
Referenced by sketch_cancel(), sketch_draw_gesture(), sketch_draw_gesture_cancel(), and sketch_draw_stroke_cancel().
static float sk_clampPointSize (SK_Point * pt, float size) [static]
Definition at line 484 of file editarmature_sketch.c.
References MAX2, and SK_Point::size.
Referenced by sk_drawEdge(), sk_drawNormal(), and sk_drawPoint().
static void sk_convert (bContext * C, SK_Sketch * sketch) [static]
Definition at line 1571 of file editarmature_sketch.c.
References ToolSettings::bone_sketching_convert, CTX_data_tool_settings(), ListBase::first, SK_Stroke::next, SK_Stroke::selected, SK_CONVERT_RETARGET, sk_convertStroke(), sk_retargetStroke(), and SK_Sketch::strokes.
Referenced by BIF_convertSketch(), sk_applyConvertGesture(), and sketch_convert().
static void sk_convertStroke (bContext * C, SK_Stroke * stk) [static]
Definition at line 1479 of file editarmature_sketch.c.
References BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, ToolSettings::bone_sketching_convert, BONE_TIPSEL, copy_m3_m4(), copy_v3_v3(), CTX_data_edit_object(), CTX_data_tool_settings(), Object::data, ED_armature_edit_bone_add(), bArmature::edbo, EditBone::flag, EditBone::head, i, initStrokeIterator(), invert_m4_m4(), mul_m4_v3(), SK_Stroke::nb_points, nextAdaptativeSubdivision(), nextFixedSubdivision(), nextLengthSubdivision(), SK_Point::no, NULL, Object::obmat, SK_Point::p, EditBone::parent, SK_Stroke::points, PT_EXACT, setBoneRollFromNormal(), SK_CONVERT_CUT_ADAPTATIVE, SK_CONVERT_CUT_FIXED, SK_CONVERT_CUT_LENGTH, subdivideArcBy(), EditBone::tail, transpose_m3(), and SK_Point::type.
Referenced by sk_convert(), and sk_finish_stroke().
int sk_detectCommandGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1866 of file editarmature_sketch.c.
References ListBase::first, SK_Intersection::gesture_index, SK_Gesture::intersections, SK_Gesture::nb_intersections, SK_Gesture::nb_segments, SK_Gesture::nb_self_intersections, SK_Intersection::next, SK_Gesture::self_intersections, and SK_Intersection::stroke.
int sk_detectCommandGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
int sk_detectConvertGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 2103 of file editarmature_sketch.c.
References SK_Gesture::nb_segments, and SK_Gesture::nb_self_intersections.
int sk_detectConvertGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
int sk_detectCutGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1783 of file editarmature_sketch.c.
References SK_Gesture::nb_intersections, and SK_Gesture::nb_segments.
int sk_detectCutGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
int sk_detectDeleteGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
int sk_detectDeleteGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1928 of file editarmature_sketch.c.
References angle(), angle_v2v2(), SK_Gesture::nb_intersections, SK_Gesture::nb_segments, SK_Point::p, SK_Stroke::points, RAD2DEGF, SK_Gesture::segments, and sub_v3_v3v3().
int sk_detectMergeGesture (bContext * C, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1965 of file editarmature_sketch.c.
References ABS, SK_Intersection::after, SK_Intersection::before, CTX_wm_region(), ListBase::first, i, SK_Gesture::intersections, MAX2, MIN2, SK_Gesture::nb_intersections, SK_Gesture::nb_segments, SK_Intersection::next, SK_Point::p, SK_Stroke::points, project_short_noclip(), PT_EXACT, sk_lastStrokePoint(), SK_Gesture::stk, SK_Intersection::stroke, and SK_Point::type.
int sk_detectMergeGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
int sk_detectReverseGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 2044 of file editarmature_sketch.c.
References angle(), angle_v2v2(), ListBase::first, SK_Intersection::gesture_index, SK_Gesture::intersections, SK_Gesture::nb_intersections, SK_Gesture::nb_segments, SK_Gesture::nb_self_intersections, SK_Intersection::next, SK_Intersection::p, SK_Point::p, SK_Stroke::points, RAD2DEGF, sk_lastStrokePoint(), SK_Gesture::stk, SK_Intersection::stroke, and sub_v3_v3v3().
int sk_detectReverseGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
int sk_detectTrimGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch)
int sk_detectTrimGesture (bContext * UNUSEDC, SK_Gesture * gest, SK_Sketch * UNUSEDsketch)
Definition at line 1810 of file editarmature_sketch.c.
References angle(), angle_v2v2(), SK_Gesture::nb_intersections, SK_Gesture::nb_segments, SK_Gesture::nb_self_intersections, SK_Point::p, SK_Stroke::points, RAD2DEGF, SK_Gesture::segments, and sub_v3_v3v3().
static float sk_distanceDepth (bContext * C, float p1[3], float p2[3]) [static]
Definition at line 967 of file editarmature_sketch.c.
References CTX_wm_region(), distance(), dot_v3v3(), len_v3(), project_v3_v3v3(), ARegion::regiondata, sub_v3_v3v3(), and RegionView3D::viewinv.
Referenced by sk_addStrokeSnapPoint().
static int sk_draw_stroke (bContext * C, SK_Sketch * sketch, SK_Stroke * stk, SK_DrawData * dd, short snap) [static]
Definition at line 2406 of file editarmature_sketch.c.
References sk_addStrokePoint(), sk_stroke_filtermval(), sk_updateDrawData(), and sk_updateNextPoint().
Referenced by sketch_draw_gesture(), sketch_draw_modal(), and sketch_draw_stroke().
static void sk_drawEdge (GLUquadric * quad, SK_Point * pt0, SK_Point * pt1, float size) [static]
Definition at line 495 of file editarmature_sketch.c.
References angle(), angle_normalized_v3v3(), cross_v3_v3v3(), is_zero_v3(), length(), M_PI, normalize_v3(), SK_Point::p, sk_clampPointSize(), and sub_v3_v3v3().
Referenced by sk_drawSketch(), and sk_drawStroke().
static void sk_drawNormal (GLUquadric * quad, SK_Point * pt, float size, float height) [static]
Definition at line 516 of file editarmature_sketch.c.
References angle(), angle_normalized_v3v3(), cross_v3_v3v3(), is_zero_v3(), M_PI, SK_Point::no, and sk_clampPointSize().
Referenced by drawSubdividedStrokeBy(), and sk_drawStroke().
static void sk_drawPoint (GLUquadric * quad, SK_Point * pt, float size) [static]
Definition at line 489 of file editarmature_sketch.c.
References SK_Point::p, and sk_clampPointSize().
Referenced by drawSubdividedStrokeBy(), sk_drawSketch(), and sk_drawStroke().
static void sk_drawSketch (Scene * scene, View3D * UNUSEDv3d, SK_Sketch * sketch, int with_names) [static]
Definition at line 2227 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, ToolSettings::bone_sketching, BONE_SKETCHING_QUICK, SK_Sketch::depth_peels, ListBase::first, SK_Sketch::gesture, GET_INT_FROM_POINTER, SK_Point::mode, SK_Stroke::next, DepthPeel::next, SK_Sketch::next_point, NULL, DepthPeel::ob, DepthPeel::p, p, PT_PROJECT, PT_SNAP, SK_Stroke::selected, sk_adjustIndexes(), sk_drawEdge(), sk_drawPoint(), sk_drawStroke(), sk_drawStrokeSubdivision(), sk_hasOverdraw(), sk_lastStrokePoint(), SK_Sketch::strokes, and Scene::toolsettings.
Referenced by BDR_drawSketch(), and BDR_drawSketchNames().
static void sk_drawStroke (SK_Stroke * stk, int id, float color[3], int start, int end) [static]
Definition at line 540 of file editarmature_sketch.c.
References add_v3_v3(), copy_v3_v3(), i, mul_v3_fl(), SK_Stroke::nb_points, SK_Stroke::points, PT_EXACT, sk_drawEdge(), sk_drawNormal(), sk_drawPoint(), sub_v3_v3(), and SK_Point::type.
Referenced by sk_drawSketch().
static void sk_drawStrokeSubdivision (ToolSettings * toolsettings, SK_Stroke * stk) [static]
Definition at line 652 of file editarmature_sketch.c.
References ToolSettings::bone_sketching_convert, drawSubdividedStrokeBy(), i, initStrokeIterator(), SK_Stroke::nb_points, nextAdaptativeSubdivision(), nextFixedSubdivision(), nextLengthSubdivision(), SK_Stroke::points, PT_EXACT, SK_CONVERT_CUT_ADAPTATIVE, SK_CONVERT_CUT_FIXED, SK_CONVERT_CUT_LENGTH, SK_CONVERT_RETARGET, and SK_Point::type.
Referenced by sk_drawSketch().
static void sk_endOverdraw (SK_Sketch * sketch) [static]
Definition at line 907 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, SK_Stroke::nb_points, NULL, SK_Sketch::over, SK_Stroke::points, sk_adjustIndexes(), sk_hasOverdraw(), sk_insertStrokePoints(), sk_lastStrokePoint(), sk_removeStroke(), sk_resetOverdraw(), sk_reverseStroke(), SK_Overdraw::target, and SK_Point::type.
Referenced by sk_endStroke().
static void sk_endStroke (bContext * C, SK_Sketch * sketch) [static]
Definition at line 946 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, ToolSettings::bone_sketching, BONE_SKETCHING_ADJUST, CTX_data_tool_settings(), NULL, sk_endOverdraw(), and sk_shrinkStrokeBuffer().
Referenced by sk_finish_stroke().
static int sk_finish_stroke (bContext * C, SK_Sketch * sketch) [static]
Definition at line 2355 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, ToolSettings::bone_sketching, ToolSettings::bone_sketching_convert, BONE_SKETCHING_QUICK, CTX_data_tool_settings(), NULL, SK_CONVERT_RETARGET, sk_convertStroke(), sk_endStroke(), sk_removeStroke(), and sk_retargetStroke().
Referenced by sketch_finish().
static void sk_freeGesture (SK_Gesture * gest) [static]
Definition at line 2130 of file editarmature_sketch.c.
References BLI_freelistN(), SK_Gesture::intersections, SK_Gesture::segments, SK_Gesture::self_intersections, and sk_freeStroke().
Referenced by sk_applyGesture().
static int sk_getIntersections (bContext * C, ListBase * list, SK_Sketch * sketch, SK_Stroke * gesture) [static]
Definition at line 1678 of file editarmature_sketch.c.
References SK_Intersection::after, SK_Intersection::before, BLI_addtail(), BLI_sortlist(), cmpIntersections(), CTX_wm_area(), CTX_wm_region(), ED_view3d_win_to_segment_clip(), ListBase::first, SK_Intersection::gesture_index, isect_line_line_strict_v3(), isect_line_line_v3(), SK_Intersection::lambda, MAX2, MEM_callocN(), SK_Stroke::nb_points, SK_Stroke::next, SK_Point::p, SK_Intersection::p, SK_Stroke::points, project_float(), ScrArea::spacedata, SK_Intersection::stroke, and SK_Sketch::strokes.
Referenced by sk_initGesture().
static int sk_getSegments (SK_Stroke * segments, SK_Stroke * gesture) [static]
Definition at line 1748 of file editarmature_sketch.c.
References calcArcCorrelation(), i, initStrokeIterator(), SK_Stroke::nb_points, SK_Point::p, SK_Stroke::points, PT_EXACT, sk_appendStrokePoint(), sub_v3_v3v3(), and SK_Point::type.
Referenced by sk_initGesture().
static int sk_getSelfIntersections (bContext * C, ListBase * list, SK_Stroke * gesture) [static]
Definition at line 1597 of file editarmature_sketch.c.
References add_v3_v3(), SK_Intersection::after, SK_Intersection::before, BLI_addtail(), CTX_wm_region(), SK_Intersection::gesture_index, isect_line_line_strict_v3(), MEM_callocN(), mul_v3_fl(), SK_Stroke::nb_points, SK_Point::p, SK_Intersection::p, SK_Stroke::points, project_float(), SK_Intersection::stroke, and sub_v3_v3v3().
Referenced by sk_initGesture().
static int sk_getStrokeDrawPoint (bContext * C, SK_Point * pt, SK_Sketch * UNUSEDsketch, SK_Stroke * stk, SK_DrawData * dd) [static]
Definition at line 1039 of file editarmature_sketch.c.
References SK_Point::mode, SK_Point::p, PT_PROJECT, sk_projectDrawPoint(), SK_Point::type, and SK_DrawData::type.
Referenced by sk_addStrokeDrawPoint(), and sk_getStrokePoint().
static void sk_getStrokePoint (bContext * C, SK_Point * pt, SK_Sketch * sketch, SK_Stroke * stk, SK_DrawData * dd, short snap) [static]
Definition at line 1291 of file editarmature_sketch.c.
References copy_v3_v3(), LAST_SNAP_POINT, LAST_SNAP_POINT_VALID, SK_Point::p, sk_getStrokeDrawPoint(), and sk_getStrokeSnapPoint().
Referenced by sketch_draw_preview().
static int sk_getStrokeSnapPoint (bContext * C, SK_Point * pt, SK_Sketch * sketch, SK_Stroke * stk, SK_DrawData * dd) [static]
Definition at line 1063 of file editarmature_sketch.c.
References add_v3_v3v3(), BLI_freelistN(), copy_v3_v3(), CTX_data_tool_settings(), SK_Sketch::depth_peels, ListBase::first, DepthPeel::flag, FLT_MAX, ListBase::last, LAST_SNAP_POINT, LAST_SNAP_POINT_VALID, len_v3v3(), SK_Point::mode, mul_v3_fl(), SK_DrawData::mval, SK_Stroke::nb_points, SK_Stroke::next, DepthPeel::next, NULL, DepthPeel::ob, DepthPeel::p, p, SK_Point::p, peelObjectsContext(), SK_Stroke::points, PT_CONTINUOUS, PT_SNAP, SCE_SNAP_MODE_VOLUME, SCE_SNAP_PEEL_OBJECT, SK_Point::size, size(), sk_snapPointStroke(), SNAP_ALL, ToolSettings::snap_flag, SNAP_MIN_DISTANCE, ToolSettings::snap_mode, SNAP_NOT_SELECTED, snapObjectsContext(), SK_Sketch::strokes, SK_Point::type, and SK_DrawData::type.
Referenced by sk_addStrokeSnapPoint(), and sk_getStrokePoint().
int sk_hasOverdraw (SK_Sketch * sketch, SK_Stroke * stk)
Definition at line 794 of file editarmature_sketch.c.
References SK_Overdraw::count, SK_Overdraw::end, NULL, SK_Sketch::over, SK_OVERDRAW_LIMIT, SK_Overdraw::start, and SK_Overdraw::target.
Referenced by sk_drawSketch(), and sk_endOverdraw().
static void sk_initGesture (bContext * C, SK_Gesture * gest, SK_Sketch * sketch) [static]
Definition at line 2117 of file editarmature_sketch.c.
References ListBase::first, SK_Sketch::gesture, SK_Gesture::intersections, ListBase::last, SK_Gesture::nb_intersections, SK_Gesture::nb_segments, SK_Gesture::nb_self_intersections, NULL, SK_Gesture::segments, SK_Gesture::self_intersections, sk_createStroke(), sk_getIntersections(), sk_getSegments(), sk_getSelfIntersections(), and SK_Gesture::stk.
Referenced by sk_applyGesture().
static void sk_interpolateDepth (bContext * C, SK_Stroke * stk, int start, int end, float length, float distance) [static]
Definition at line 988 of file editarmature_sketch.c.
References add_v3_v3(), CTX_wm_area(), CTX_wm_region(), ED_view3d_win_to_ray(), ListBase::first, i, len_v3v3(), mul_v3_fl(), SK_Point::p, SK_Stroke::points, project_float(), and ScrArea::spacedata.
Referenced by sk_addStrokeSnapPoint().
static RigGraph* sk_makeTemplateGraph (const bContext * C, Object * ob) [static]
Definition at line 249 of file editarmature_sketch.c.
References CTX_data_edit_object(), Object::data, NULL, RigGraph::ob, RIG_freeRigGraph(), RIG_graphFromArmature(), and TEMPLATE_RIGG.
Referenced by BIF_nameBoneTemplate(), BIF_nbJointsTemplate(), and sk_retargetStroke().
static ReebNode* sk_pointToNode (SK_Point * pt, float imat[][4], float tmat[][3]) [static]
Definition at line 405 of file editarmature_sketch.c.
References copy_v3_v3(), MEM_callocN(), mul_m3_v3(), mul_m4_v3(), ReebNode::no, SK_Point::no, ReebNode::p, and SK_Point::p.
Referenced by sk_strokeToArc().
static void sk_projectDrawPoint (bContext * C, float vec[3], SK_Stroke * stk, SK_DrawData * dd) [static]
Definition at line 1015 of file editarmature_sketch.c.
References copy_v3_v3(), CTX_wm_region(), ED_view3d_win_to_delta(), initgrabz(), SK_DrawData::mval, NULL, SK_Point::p, project_short_noclip(), ARegion::regiondata, sk_lastStrokePoint(), sub_v3_v3v3(), and VECSUB2D.
Referenced by sk_addStrokeSnapPoint(), and sk_getStrokeDrawPoint().
void sk_resetOverdraw (SK_Sketch * sketch)
Definition at line 786 of file editarmature_sketch.c.
References SK_Overdraw::count, SK_Overdraw::end, NULL, SK_Sketch::over, SK_Overdraw::start, and SK_Overdraw::target.
Referenced by sk_cancelStroke(), sk_endOverdraw(), and sk_startStroke().
static void sk_retargetStroke (bContext * C, SK_Stroke * stk) [static]
Definition at line 443 of file editarmature_sketch.c.
References BIF_retargetArc(), copy_m3_m4(), CTX_data_edit_object(), CTX_data_tool_settings(), ReebArc::head, invert_m4_m4(), MEM_freeN(), NULL, Object::obmat, REEB_freeArc(), sk_autoname(), sk_makeTemplateGraph(), sk_strokeToArc(), ToolSettings::skgen_template, ReebArc::tail, and transpose_m3().
Referenced by sk_convert(), and sk_finish_stroke().
static int sk_selectStroke (bContext * C, SK_Sketch * sketch, const int mval[2], int extend) [static]
Definition at line 2160 of file editarmature_sketch.c.
References BLI_findlink(), MAXPICKBUF, SK_Stroke::selected, sk_selectAllSketch(), SK_Sketch::strokes, view3d_opengl_select(), view3d_set_viewcontext(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by BIF_sk_selectStroke(), and sketch_select().
static SK_Point* sk_snapPointStroke (bContext * C, SK_Stroke * stk, int mval[2], int * dist, int * index, int all_pts) [static]
Definition at line 703 of file editarmature_sketch.c.
References ABS, CTX_wm_region(), i, SK_Stroke::nb_points, NULL, SK_Point::p, SK_Stroke::points, project_short_noclip(), PT_EXACT, and SK_Point::type.
Referenced by sk_getStrokeSnapPoint(), and sk_updateOverdraw().
static void sk_start_draw_gesture (SK_Sketch * sketch) [static]
Definition at line 2401 of file editarmature_sketch.c.
References SK_Sketch::gesture, and sk_createStroke().
Referenced by sketch_draw_gesture().
static void sk_start_draw_stroke (SK_Sketch * sketch) [static]
Definition at line 2390 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, NULL, SK_Stroke::selected, sk_selectAllSketch(), and sk_startStroke().
Referenced by sketch_draw_stroke().
static void sk_startStroke (SK_Sketch * sketch) [static]
Definition at line 936 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, BLI_addtail(), sk_createStroke(), sk_resetOverdraw(), and SK_Sketch::strokes.
Referenced by sk_start_draw_stroke().
static ReebArc* sk_strokeToArc (SK_Stroke * stk, float imat[][4], float tmat[][3]) [static]
Definition at line 419 of file editarmature_sketch.c.
References ReebArc::bcount, ReebArc::buckets, copy_v3_v3(), ReebArc::head, i, MEM_callocN(), mul_m3_v3(), mul_m4_v3(), SK_Stroke::nb_points, SK_Point::no, EmbedBucket::no, EmbedBucket::p, SK_Point::p, SK_Stroke::points, sk_lastStrokePoint(), sk_pointToNode(), and ReebArc::tail.
Referenced by sk_retargetStroke().
static void sk_updateDrawData (SK_DrawData * dd) [static]
Definition at line 959 of file editarmature_sketch.c.
References SK_DrawData::mval, SK_DrawData::previous_mval, PT_CONTINUOUS, and SK_DrawData::type.
Referenced by sk_draw_stroke().
static void sk_updateOverdraw (bContext * C, SK_Sketch * sketch, SK_Stroke * stk, SK_DrawData * dd) [static]
Definition at line 802 of file editarmature_sketch.c.
References SK_Overdraw::count, SK_Overdraw::end, ListBase::first, SK_DrawData::mval, SK_Stroke::nb_points, SK_Stroke::next, NULL, SK_Sketch::over, PT_EXACT, sk_lastStrokePoint(), SK_OVERDRAW_LIMIT, sk_snapPointStroke(), SNAP_MIN_DISTANCE, SK_Overdraw::start, SK_Sketch::strokes, and SK_Overdraw::target.
Referenced by sk_addStrokePoint().
static int sketch_cancel (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 2582 of file editarmature_sketch.c.
References contextSketch(), CTX_wm_area(), ED_area_tag_redraw(), NULL, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, and sk_cancelStroke().
Referenced by SKETCH_OT_cancel_stroke().
static int sketch_convert (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 2571 of file editarmature_sketch.c.
References contextSketch(), CTX_wm_area(), ED_area_tag_redraw(), NULL, OPERATOR_FINISHED, and sk_convert().
Referenced by SKETCH_OT_convert().
static int sketch_delete (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 2464 of file editarmature_sketch.c.
References contextSketch(), NA_REMOVED, NC_SCREEN, ND_SKETCH, NULL, OPERATOR_FINISHED, sk_deleteSelectedStrokes(), and WM_event_add_notifier().
Referenced by SKETCH_OT_delete().
static int sketch_draw_gesture (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2655 of file editarmature_sketch.c.
References contextSketch(), wmOperator::customdata, SK_Sketch::gesture, MEM_callocN(), wmEvent::mval, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_get(), sk_cancelStroke(), sk_draw_stroke(), sk_initDrawData(), sk_start_draw_gesture(), and WM_event_add_modal_handler().
Referenced by SKETCH_OT_gesture().
static int sketch_draw_gesture_cancel (bContext * C, wmOperator * op) [static]
Definition at line 2647 of file editarmature_sketch.c.
References contextSketch(), wmOperator::customdata, MEM_freeN(), OPERATOR_CANCELLED, and sk_cancelStroke().
Referenced by SKETCH_OT_gesture().
static int sketch_draw_gesture_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2742 of file editarmature_sketch.c.
References contextSketch(), SK_Sketch::gesture, and sketch_draw_modal().
Referenced by SKETCH_OT_gesture().
static int sketch_draw_modal (bContext * C, wmOperator * op, wmEvent * event, short gesture, SK_Stroke * stk) [static]
Definition at line 2673 of file editarmature_sketch.c.
References wmOperatorType::cancel, contextSketch(), CTX_wm_area(), wmOperator::customdata, ED_area_tag_redraw(), ESCKEY, SK_Sketch::gesture, INBETWEEN_MOUSEMOVE, KM_RELEASE, LEFTCTRLKEY, LEFTMOUSE, MEM_freeN(), MOUSEMOVE, SK_DrawData::mval, SK_Stroke::nb_points, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RIGHTCTRLKEY, RNA_boolean_get(), RNA_boolean_set(), sk_applyGesture(), sk_draw_stroke(), sk_endContinuousStroke(), sk_filterLastContinuousStroke(), sk_freeStroke(), sk_updateNextPoint(), wmEvent::type, wmOperator::type, and wmEvent::val.
Referenced by sketch_draw_gesture_modal(), and sketch_draw_stroke_modal().
static int sketch_draw_preview (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2748 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, contextSketch(), CTX_wm_area(), ED_area_tag_redraw(), wmEvent::mval, SK_Sketch::next_point, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmOperator::ptr, RNA_boolean_get(), sk_getStrokePoint(), and sk_initDrawData().
Referenced by SKETCH_OT_draw_preview().
static int sketch_draw_stroke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2629 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, contextSketch(), wmOperator::customdata, MEM_callocN(), wmEvent::mval, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_get(), sk_draw_stroke(), sk_initDrawData(), sk_start_draw_stroke(), and WM_event_add_modal_handler().
Referenced by SKETCH_OT_draw_stroke().
static int sketch_draw_stroke_cancel (bContext * C, wmOperator * op) [static]
Definition at line 2621 of file editarmature_sketch.c.
References contextSketch(), wmOperator::customdata, MEM_freeN(), OPERATOR_CANCELLED, and sk_cancelStroke().
Referenced by SKETCH_OT_draw_stroke().
static int sketch_draw_stroke_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2736 of file editarmature_sketch.c.
References SK_Sketch::active_stroke, contextSketch(), and sketch_draw_modal().
Referenced by SKETCH_OT_draw_stroke().
static int sketch_finish (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 2594 of file editarmature_sketch.c.
References contextSketch(), CTX_wm_area(), ED_area_tag_redraw(), NULL, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, and sk_finish_stroke().
Referenced by SKETCH_OT_finish_stroke().
void SKETCH_OT_cancel_stroke (wmOperatorType * ot)
Definition at line 2869 of file editarmature_sketch.c.
References ED_operator_sketch_mode_active_stroke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_cancel().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_convert (wmOperatorType * ot)
Definition at line 2884 of file editarmature_sketch.c.
References ED_operator_sketch_full_mode(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, and sketch_convert().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_delete (wmOperatorType * ot)
Definition at line 2839 of file editarmature_sketch.c.
References ED_operator_sketch_full_mode(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_delete().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_draw_preview (wmOperatorType * ot)
Definition at line 2914 of file editarmature_sketch.c.
References ED_operator_sketch_mode_active_stroke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), sketch_draw_preview(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void SKETCH_OT_draw_stroke (wmOperatorType * ot)
Definition at line 2931 of file editarmature_sketch.c.
References wmOperatorType::cancel, ED_operator_sketch_mode(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_boolean(), sketch_draw_stroke(), sketch_draw_stroke_cancel(), sketch_draw_stroke_modal(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void SKETCH_OT_finish_stroke (wmOperatorType * ot)
Definition at line 2899 of file editarmature_sketch.c.
References ED_operator_sketch_mode_active_stroke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_finish().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_gesture (wmOperatorType * ot)
Definition at line 2950 of file editarmature_sketch.c.
References wmOperatorType::cancel, ED_operator_sketch_mode_gesture(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_boolean(), sketch_draw_gesture(), sketch_draw_gesture_cancel(), sketch_draw_gesture_modal(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void SKETCH_OT_select (wmOperatorType * ot)
Definition at line 2854 of file editarmature_sketch.c.
References ED_operator_sketch_full_mode(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_select().
Referenced by ED_operatortypes_armature().
static int sketch_select (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 2608 of file editarmature_sketch.c.
References contextSketch(), CTX_wm_area(), ED_area_tag_redraw(), wmEvent::mval, OPERATOR_FINISHED, and sk_selectStroke().
Referenced by SKETCH_OT_select().
static void * tailPoint (void * arg) [static]
Definition at line 1393 of file editarmature_sketch.c.
References SK_StrokeIterator::end, SK_Point::no, SK_StrokeIterator::no, NULL, SK_Point::p, SK_StrokeIterator::p, SK_Stroke::points, SK_Point::size, SK_StrokeIterator::size, SK_StrokeIterator::stride, and SK_StrokeIterator::stroke.
Referenced by initIteratorFct().
static int ValidSketchViewContext (ViewContext * vc) [static]
Definition at line 2420 of file editarmature_sketch.c.
References ToolSettings::bone_sketching, BONE_SKETCHING, OB_ARMATURE, ViewContext::obedit, ViewContext::scene, Scene::toolsettings, and Object::type.
Referenced by BDR_drawSketchNames().
SK_Sketch * viewcontextSketch (ViewContext * vc, int create)
Definition at line 2552 of file editarmature_sketch.c.
References createSketch(), Object::data, NULL, OB_ARMATURE, ViewContext::obedit, bArmature::sketch, and Object::type.
Referenced by BDR_drawSketchNames().
Variable Documentation
SK_GestureAction GESTURE_ACTIONS[] [static]
Initial value:
    {
        {"Cut", sk_detectCutGesture, sk_applyCutGesture},
        {"Trim", sk_detectTrimGesture, sk_applyTrimGesture},
        {"Command", sk_detectCommandGesture, sk_applyCommandGesture},
        {"Delete", sk_detectDeleteGesture, sk_applyDeleteGesture},
        {"Merge", sk_detectMergeGesture, sk_applyMergeGesture},
        {"Reverse", sk_detectReverseGesture, sk_applyReverseGesture},
        {"Convert", sk_detectConvertGesture, sk_applyConvertGesture},
        {"", NULL, NULL}
    }
Definition at line 138 of file editarmature_sketch.c.
float LAST_SNAP_POINT[3] [static]
Definition at line 87 of file editarmature_sketch.c.
Referenced by sk_getStrokePoint(), and sk_getStrokeSnapPoint().
int LAST_SNAP_POINT_VALID = 0 [static]
Definition at line 86 of file editarmature_sketch.c.
Referenced by sk_getStrokePoint(), and sk_getStrokeSnapPoint().
RigGraph* TEMPLATE_RIGG = NULL [static]
Definition at line 155 of file editarmature_sketch.c.
Referenced by sk_makeTemplateGraph().
int TEMPLATES_CURRENT = 0 [static]
Definition at line 153 of file editarmature_sketch.c.
Referenced by BIF_currentTemplate(), and BIF_makeListTemplates().
GHash* TEMPLATES_HASH = NULL [static]
Definition at line 154 of file editarmature_sketch.c.
char* TEMPLATES_MENU = NULL [static]
Definition at line 152 of file editarmature_sketch.c.
Referenced by BIF_freeTemplates(), and BIF_listTemplates().