Blender: KX_ObstacleSimulationTOI_rays Class Reference
KX_ObstacleSimulationTOI_rays Class Reference
#include <KX_ObstacleSimulation.h>
Public Member Functions
KX_ObstacleSimulationTOI_rays (MT_Scalar levelHeight, bool enableVisualization)
Protected Member Functions
virtual void sampleRVO (KX_Obstacle *activeObst, KX_NavMeshObject *activeNavMeshObj, const float maxDeltaAngle)
Detailed Description
Definition at line 113 of file KX_ObstacleSimulation.h.
Constructor & Destructor Documentation
KX_ObstacleSimulationTOI_rays::KX_ObstacleSimulationTOI_rays (MT_Scalar levelHeight, bool enableVisualization)
Definition at line 463 of file KX_ObstacleSimulation.cpp.
References KX_ObstacleSimulationTOI::m_collisionWeight, KX_ObstacleSimulationTOI::m_maxSamples, KX_ObstacleSimulationTOI::m_maxToi, KX_ObstacleSimulationTOI::m_minToi, KX_ObstacleSimulationTOI::m_toiWeight, and KX_ObstacleSimulationTOI::m_velWeight.
Member Function Documentation
void KX_ObstacleSimulationTOI_rays::sampleRVO (KX_Obstacle * activeObst, KX_NavMeshObject * activeNavMeshObj, const float maxDeltaAngle) [protected, virtual]
Implements KX_ObstacleSimulationTOI.
Definition at line 475 of file KX_ObstacleSimulation.cpp.
References KDL::atan2(), cosf, TOICircle::dir, KX_Obstacle::dvel, fabsf, filterObstacle(), FLT_MAX, i, interpolateToi(), KX_OBSTACLE_CIRCLE, KX_OBSTACLE_NAV_MESH, KX_OBSTACLE_SEGMENT, MT_Vector2::length(), KX_ObstacleSimulationTOI::m_collisionWeight, KX_Obstacle::m_gameObj, KX_ObstacleSimulation::m_levelHeight, KX_ObstacleSimulationTOI::m_maxSamples, KX_ObstacleSimulationTOI::m_maxToi, KX_ObstacleSimulationTOI::m_minToi, KX_ObstacleSimulation::m_obstacles, M_PI, KX_Obstacle::m_pos, KX_Obstacle::m_pos2, KX_Obstacle::m_rad, KX_Obstacle::m_shape, KX_ObstacleSimulationTOI::m_toiWeight, KX_Obstacle::m_type, KX_ObstacleSimulationTOI::m_velWeight, TOICircle::maxToi, min, TOICircle::minToi, TOICircle::n, MT_Vector2::normalize(), KX_Obstacle::nvel, sinf, sweepCircleCircle(), sweepCircleSegment(), TOICircle::toi, TOICircle::toie, KX_NavMeshObject::TransformToWorldCoords(), KX_Obstacle::vel, MT_Tuple2::x(), and MT_Tuple2::y().
The documentation for this class was generated from the following files:
KX_ObstacleSimulation.h
KX_ObstacleSimulation.cpp