Blender: readfile.c File Reference
readfile.c File Reference
.blend read and write functions
#include "zlib.h"
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <fcntl.h>
#include <string.h>
#include <math.h>
#include <stdarg.h>
#include <unistd.h>
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_actuator_types.h"
#include "DNA_brush_types.h"
#include "DNA_camera_types.h"
#include "DNA_cloth_types.h"
#include "DNA_controller_types.h"
#include "DNA_constraint_types.h"
#include "DNA_dynamicpaint_types.h"
#include "DNA_effect_types.h"
#include "DNA_fileglobal_types.h"
#include "DNA_genfile.h"
#include "DNA_group_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_ipo_types.h"
#include "DNA_key_types.h"
#include "DNA_lattice_types.h"
#include "DNA_lamp_types.h"
#include "DNA_meta_types.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_nla_types.h"
#include "DNA_node_types.h"
#include "DNA_object_fluidsim.h"
#include "DNA_packedFile_types.h"
#include "DNA_particle_types.h"
#include "DNA_property_types.h"
#include "DNA_text_types.h"
#include "DNA_view3d_types.h"
#include "DNA_screen_types.h"
#include "DNA_sensor_types.h"
#include "DNA_sdna_types.h"
#include "DNA_scene_types.h"
#include "DNA_sequence_types.h"
#include "DNA_smoke_types.h"
#include "DNA_speaker_types.h"
#include "DNA_sound_types.h"
#include "DNA_space_types.h"
#include "DNA_vfont_types.h"
#include "DNA_world_types.h"
#include "DNA_movieclip_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BKE_anim.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_brush.h"
#include "BKE_colortools.h"
#include "BKE_constraint.h"
#include "BKE_context.h"
#include "BKE_curve.h"
#include "BKE_deform.h"
#include "BKE_effect.h"
#include "BKE_fcurve.h"
#include "BKE_global.h"
#include "BKE_group.h"
#include "BKE_image.h"
#include "BKE_lattice.h"
#include "BKE_library.h"
#include "BKE_idcode.h"
#include "BKE_material.h"
#include "BKE_main.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_multires.h"
#include "BKE_node.h"
#include "BKE_ocean.h"
#include "BKE_object.h"
#include "BKE_paint.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_property.h"
#include "BKE_report.h"
#include "BKE_sca.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "BKE_sequencer.h"
#include "BKE_text.h"
#include "BKE_texture.h"
#include "BKE_tracking.h"
#include "BKE_utildefines.h"
#include "BKE_sound.h"
#include "IMB_imbuf.h"
#include "NOD_socket.h"
#include "BLO_readfile.h"
#include "BLO_undofile.h"
#include "RE_engine.h"
#include "readfile.h"
#include "PIL_time.h"
#include <errno.h>
Classes
struct OldNew
struct OldNewMap
struct tConstraintLinkData
struct bheadsort
struct tConstraintExpandData
Defines
#define DNA_DEPRECATED_ALLOW
#define GS(a) (*((short *)(a)))
#define SWITCH_LONGINT(a)
Typedefs
typedef struct OldNew OldNew
typedef struct OldNewMap OldNewMap
typedef struct tConstraintLinkData tConstraintLinkData
typedef struct
tConstraintExpandData tConstraintExpandData
Functions
static void * read_struct (FileData *fd, BHead *bh, const char *blockname)
static void direct_link_modifiers (FileData *fd, ListBase *lb)
static void convert_tface_mt (FileData *fd, Main *main)
static void BKE_reportf_wrap (ReportList *reports, ReportType type, const char *format,...)
static OldNewMap * oldnewmap_new (void)
static int verg_oldnewmap (const void *v1, const void *v2)
static void oldnewmap_sort (FileData *fd)
static void oldnewmap_insert (OldNewMap *onm, void *oldaddr, void *newaddr, int nr)
static void * oldnewmap_lookup_and_inc (OldNewMap *onm, void *addr)
static void * oldnewmap_liblookup (OldNewMap *onm, void *addr, void *lib)
static void oldnewmap_free_unused (OldNewMap *onm)
static void oldnewmap_clear (OldNewMap *onm)
static void oldnewmap_free (OldNewMap *onm)
static void read_libraries (FileData *basefd, ListBase *mainlist)
static void add_main_to_main (Main *mainvar, Main *from)
void blo_join_main (ListBase *mainlist)
static void split_libdata (ListBase *lb, Main *first)
void blo_split_main (ListBase *mainlist, Main *main)
static void cleanup_path (const char *relabase, char *name)
static void read_file_version (FileData *fd, Main *main)
static Main * blo_find_main (FileData *fd, ListBase *mainlist, const char *filepath, const char *relabase)
static void switch_endian_bh4 (BHead4 *bhead)
static void switch_endian_bh8 (BHead8 *bhead)
static void bh4_from_bh8 (BHead *bhead, BHead8 *bhead8, int do_endian_swap)
static void bh8_from_bh4 (BHead *bhead, BHead4 *bhead4)
static BHeadN * get_bhead (FileData *fd)
BHead * blo_firstbhead (FileData *fd)
BHead * blo_prevbhead (FileData *UNUSED(fd), BHead *thisblock)
BHead * blo_nextbhead (FileData *fd, BHead *thisblock)
static void decode_blender_header (FileData *fd)
static int read_file_dna (FileData *fd)
static int fd_read_from_file (FileData *filedata, void *buffer, unsigned int size)
static int fd_read_gzip_from_file (FileData *filedata, void *buffer, unsigned int size)
static int fd_read_from_memory (FileData *filedata, void *buffer, unsigned int size)
static int fd_read_from_memfile (FileData *filedata, void *buffer, unsigned int size)
static FileData * filedata_new (void)
static FileData * blo_decode_and_check (FileData *fd, ReportList *reports)
FileData * blo_openblenderfile (const char *filepath, ReportList *reports)
FileData * blo_openblendermemory (void *mem, int memsize, ReportList *reports)
FileData * blo_openblendermemfile (MemFile *memfile, ReportList *reports)
void blo_freefiledata (FileData *fd)
int BLO_has_bfile_extension (const char *str)
int BLO_is_a_library (const char *path, char *dir, char *group)
static void * newdataadr (FileData *fd, void *adr)
static void * newglobadr (FileData *fd, void *adr)
static void * newimaadr (FileData *fd, void *adr)
static void * newmclipadr (FileData *fd, void *adr)
static void * newlibadr (FileData *fd, void *lib, void *adr)
static void * newlibadr_us (FileData *fd, void *lib, void *adr)
static void change_idid_adr_fd (FileData *fd, void *old, void *new)
static void change_idid_adr (ListBase *mainlist, FileData *basefd, void *old, void *new)
void blo_clear_proxy_pointers_from_lib (Main *oldmain)
void blo_make_image_pointer_map (FileData *fd, Main *oldmain)
void blo_end_image_pointer_map (FileData *fd, Main *oldmain)
void blo_make_movieclip_pointer_map (FileData *fd, Main *oldmain)
void blo_end_movieclip_pointer_map (FileData *fd, Main *oldmain)
void blo_add_library_pointer_map (ListBase *mainlist, FileData *fd)
static void switch_endian_structs (struct SDNA *filesdna, BHead *bhead)
static void link_list (FileData *fd, ListBase *lb)
static void link_glob_list (FileData *fd, ListBase *lb)
static void test_pointer_array (FileData *fd, void **mat)
static void IDP_DirectLinkProperty (IDProperty *prop, int switch_endian, FileData *fd)
static void IDP_LibLinkProperty (IDProperty *prop, int switch_endian, FileData *fd)
static void IDP_DirectLinkIDPArray (IDProperty *prop, int switch_endian, FileData *fd)
static void IDP_DirectLinkArray (IDProperty *prop, int switch_endian, FileData *fd)
static void IDP_DirectLinkString (IDProperty *prop, FileData *fd)
static void IDP_DirectLinkGroup (IDProperty *prop, int switch_endian, FileData *fd)
static void IDP_LibLinkProperty (IDProperty *UNUSED(prop), int UNUSED(switch_endian), FileData *UNUSED(fd))
static void direct_link_curvemapping (FileData *fd, CurveMapping *cumap)
static void lib_link_brush (FileData *fd, Main *main)
static void direct_link_brush (FileData *fd, Brush *brush)
static void direct_link_script (FileData *UNUSED(fd), Script *script)
static PackedFile * direct_link_packedfile (FileData *fd, PackedFile *oldpf)
static PreviewImage * direct_link_preview_image (FileData *fd, PreviewImage *old_prv)
static void lib_link_ipo (FileData *fd, Main *main)
static void direct_link_ipo (FileData *fd, Ipo *ipo)
static void lib_link_nlastrips (FileData *fd, ID *id, ListBase *striplist)
static void direct_link_nlastrips (FileData *fd, ListBase *strips)
static void lib_link_constraint_channels (FileData *fd, ID *id, ListBase *chanbase)
static void lib_link_fmodifiers (FileData *fd, ID *id, ListBase *list)
static void lib_link_fcurves (FileData *fd, ID *id, ListBase *list)
static void direct_link_fmodifiers (FileData *fd, ListBase *list)
static void direct_link_fcurves (FileData *fd, ListBase *list)
static void lib_link_action (FileData *fd, Main *main)
static void direct_link_action (FileData *fd, bAction *act)
static void lib_link_nladata_strips (FileData *fd, ID *id, ListBase *list)
static void lib_link_nladata (FileData *fd, ID *id, ListBase *list)
static void direct_link_nladata_strips (FileData *fd, ListBase *list)
static void direct_link_nladata (FileData *fd, ListBase *list)
static void lib_link_keyingsets (FileData *fd, ID *id, ListBase *list)
static void direct_link_keyingsets (FileData *fd, ListBase *list)
static void lib_link_animdata (FileData *fd, ID *id, AnimData *adt)
static void direct_link_animdata (FileData *fd, AnimData *adt)
static void direct_link_motionpath (FileData *fd, bMotionPath *mpath)
static void lib_link_ntree (FileData *fd, ID *id, bNodeTree *ntree)
static void lib_link_nodetree (FileData *fd, Main *main)
static void do_versions_socket_default_value (bNodeSocket *sock)
static void do_versions_nodetree_default_value (bNodeTree *ntree)
static void lib_nodetree_init_types_cb (void *UNUSED(data), ID *UNUSED(id), bNodeTree *ntree)
static void lib_node_do_versions_group_indices (bNode *gnode)
static void lib_nodetree_do_versions_group_indices_cb (void *UNUSED(data), ID *UNUSED(id), bNodeTree *ntree)
static void lib_nodetree_do_versions_update_cb (void *UNUSED(data), ID *UNUSED(id), bNodeTree *ntree)
static void lib_verify_nodetree (Main *main, int UNUSED(open))
static void direct_link_node_socket (FileData *fd, bNodeSocket *sock)
static void direct_link_nodetree (FileData *fd, bNodeTree *ntree)
static void lib_link_constraint_cb (bConstraint *UNUSED(con), ID **idpoin, void *userdata)
static void lib_link_constraints (FileData *fd, ID *id, ListBase *conlist)
static void direct_link_constraints (FileData *fd, ListBase *lb)
static void lib_link_pose (FileData *fd, Object *ob, bPose *pose)
static void lib_link_armature (FileData *fd, Main *main)
static void direct_link_bones (FileData *fd, Bone *bone)
static void direct_link_armature (FileData *fd, bArmature *arm)
static void lib_link_camera (FileData *fd, Main *main)
static void direct_link_camera (FileData *fd, Camera *ca)
static void lib_link_lamp (FileData *fd, Main *main)
static void direct_link_lamp (FileData *fd, Lamp *la)
static void lib_link_key (FileData *fd, Main *main)
static void switch_endian_keyblock (Key *key, KeyBlock *kb)
static void direct_link_key (FileData *fd, Key *key)
static void lib_link_mball (FileData *fd, Main *main)
static void direct_link_mball (FileData *fd, MetaBall *mb)
static void lib_link_world (FileData *fd, Main *main)
static void direct_link_world (FileData *fd, World *wrld)
static void lib_link_vfont (FileData *UNUSED(fd), Main *main)
static void direct_link_vfont (FileData *fd, VFont *vf)
static void lib_link_text (FileData *UNUSED(fd), Main *main)
static void direct_link_text (FileData *fd, Text *text)
static void lib_link_image (FileData *fd, Main *main)
static void link_ibuf_list (FileData *fd, ListBase *lb)
static void direct_link_image (FileData *fd, Image *ima)
static void lib_link_curve (FileData *fd, Main *main)
static void switch_endian_knots (Nurb *nu)
static void direct_link_curve (FileData *fd, Curve *cu)
static void lib_link_texture (FileData *fd, Main *main)
static void direct_link_texture (FileData *fd, Tex *tex)
static void lib_link_material (FileData *fd, Main *main)
static void direct_link_material (FileData *fd, Material *ma)
static void direct_link_pointcache (FileData *fd, PointCache *cache)
static void direct_link_pointcache_list (FileData *fd, ListBase *ptcaches, PointCache **ocache, int force_disk)
static void lib_link_partdeflect (FileData *fd, ID *id, PartDeflect *pd)
static void lib_link_particlesettings (FileData *fd, Main *main)
static void direct_link_partdeflect (PartDeflect *pd)
static void direct_link_particlesettings (FileData *fd, ParticleSettings *part)
static void lib_link_particlesystems (FileData *fd, Object *ob, ID *id, ListBase *particles)
static void direct_link_particlesystems (FileData *fd, ListBase *particles)
static void lib_link_mtface (FileData *fd, Mesh *me, MTFace *mtface, int totface)
static void lib_link_customdata_mtface (FileData *fd, Mesh *me, CustomData *fdata, int totface)
static void lib_link_customdata_mtpoly (FileData *fd, Mesh *me, CustomData *pdata, int totface)
static void lib_link_mesh (FileData *fd, Main *main)
static void direct_link_dverts (FileData *fd, int count, MDeformVert *mdverts)
static void direct_link_mdisps (FileData *fd, int count, MDisps *mdisps, int external)
static void direct_link_customdata (FileData *fd, CustomData *data, int count)
static void direct_link_mesh (FileData *fd, Mesh *mesh)
static void lib_link_latt (FileData *fd, Main *main)
static void direct_link_latt (FileData *fd, Lattice *lt)
static void lib_link_modifiers__linkModifiers (void *userData, Object *ob, ID **idpoin)
static void lib_link_modifiers (FileData *fd, Object *ob)
static void lib_link_object (FileData *fd, Main *main)
static void direct_link_pose (FileData *fd, bPose *pose)
static void direct_link_object (FileData *fd, Object *ob)
static void composite_patch (bNodeTree *ntree, Scene *scene)
static void link_paint (FileData *fd, Scene *sce, Paint *p)
static void lib_link_scene (FileData *fd, Main *main)
static void link_recurs_seq (FileData *fd, ListBase *lb)
static void direct_link_paint (FileData *fd, Paint **paint)
static void direct_link_scene (FileData *fd, Scene *sce)
static void direct_link_windowmanager (FileData *fd, wmWindowManager *wm)
static void lib_link_windowmanager (FileData *fd, Main *main)
static void direct_link_gpencil (FileData *fd, bGPdata *gpd)
static void butspace_version_132 (SpaceButs *buts)
static void lib_link_screen (FileData *fd, Main *main)
static void * restore_pointer_by_name (Main *mainp, ID *id, int user)
static int lib_link_seq_clipboard_cb (Sequence *seq, void *arg_pt)
static void lib_link_clipboard_restore (Main *newmain)
void lib_link_screen_restore (Main *newmain, bScreen *curscreen, Scene *curscene)
static void direct_link_region (FileData *fd, ARegion *ar, int spacetype)
static void view3d_split_250 (View3D *v3d, ListBase *regions)
static void direct_link_screen (FileData *fd, bScreen *sc)
static void direct_link_library (FileData *fd, Library *lib, Main *main)
static void lib_link_library (FileData *UNUSED(fd), Main *main)
static void fix_relpaths_library (const char *basepath, Main *main)
static void lib_link_speaker (FileData *fd, Main *main)
static void direct_link_speaker (FileData *fd, Speaker *spk)
static void direct_link_sound (FileData *fd, bSound *sound)
static void lib_link_sound (FileData *fd, Main *main)
static void direct_link_group (FileData *fd, Group *group)
static void lib_link_group (FileData *fd, Main *main)
static void direct_link_movieReconstruction (FileData *fd, MovieTrackingReconstruction *reconstruction)
static void direct_link_movieTracks (FileData *fd, ListBase *tracksbase)
static void direct_link_movieclip (FileData *fd, MovieClip *clip)
static void lib_link_movieclip (FileData *fd, Main *main)
static const char * dataname (short id_code)
static BHead * read_data_into_oldnewmap (FileData *fd, BHead *bhead, const char *allocname)
static BHead * read_libblock (FileData *fd, Main *main, BHead *bhead, int flag, ID **id_r)
static BHead * read_global (BlendFileData *bfd, FileData *fd, BHead *bhead)
static void link_global (FileData *fd, BlendFileData *bfd)
static void vcol_to_fcol (Mesh *me)
static int map_223_keybd_code_to_224_keybd_code (int code)
static void do_version_bone_head_tail_237 (Bone *bone)
static void bone_version_238 (ListBase *lb)
static void bone_version_239 (ListBase *lb)
static void ntree_version_241 (bNodeTree *ntree)
static void ntree_version_242 (bNodeTree *ntree)
static void customdata_version_242 (Mesh *me)
static void customdata_version_243 (Mesh *me)
static void do_version_ntree_242_2 (bNodeTree *ntree)
static void ntree_version_245 (FileData *fd, Library *lib, bNodeTree *ntree)
static void idproperties_fix_groups_lengths_recurse (IDProperty *prop)
static void idproperties_fix_group_lengths (ListBase idlist)
static void alphasort_version_246 (FileData *fd, Library *lib, Mesh *me)
static void area_add_header_region (ScrArea *sa, ListBase *lb)
static void sequencer_init_preview_region (ARegion *ar)
static void area_add_window_regions (ScrArea *sa, SpaceLink *sl, ListBase *lb)
static void do_versions_windowmanager_2_50 (bScreen *screen)
static void versions_gpencil_add_main (ListBase *lb, ID *id, const char *name)
static void do_versions_gpencil_2_50 (Main *main, bScreen *screen)
static PartEff * do_version_give_parteff_245 (Object *ob)
static void do_version_free_effect_245 (Effect *eff)
static void do_version_free_effects_245 (ListBase *lb)
static void do_version_mtex_factor_2_50 (MTex **mtex_array, short idtype)
static void do_version_mdef_250 (Main *main)
static void do_version_constraints_radians_degrees_250 (ListBase *lb)
static void do_version_old_trackto_to_constraints (Object *ob)
static void do_versions_seq_unique_name_all_strips (Scene *sce, ListBase *seqbasep)
static void do_version_bone_roll_256 (Bone *bone)
static void do_versions_nodetree_dynamic_sockets (bNodeTree *ntree)
static void do_versions_nodetree_image_default_alpha_output (bNodeTree *ntree)
static void do_version_ntree_tex_mapping_260 (void *UNUSED(data), ID *UNUSED(id), bNodeTree *ntree)
static void do_versions_nodetree_convert_angle (bNodeTree *ntree)
void do_versions_image_settings_2_60 (Scene *sce)
static void do_versions_nodetree_socket_use_flags_2_62 (bNodeTree *ntree)
static void do_versions_nodetree_multi_file_output_format_2_62_1 (Scene *sce, bNodeTree *ntree)
static void do_versions_mesh_mloopcol_swap_2_62_1 (Mesh *me)
static void do_versions (FileData *fd, Library *lib, Main *main)
static void lib_link_all (FileData *fd, Main *main)
static void direct_link_keymapitem (FileData *fd, wmKeyMapItem *kmi)
static BHead * read_userdef (BlendFileData *bfd, FileData *fd, BHead *bhead)
BlendFileData * blo_read_file_internal (FileData *fd, const char *filepath)
static int verg_bheadsort (const void *v1, const void *v2)
static void sort_bhead_old_map (FileData *fd)
static BHead * find_previous_lib (FileData *fd, BHead *bhead)
static BHead * find_bhead (FileData *fd, void *old)
char * bhead_id_name (FileData *fd, BHead *bhead)
static ID * is_yet_read (FileData *fd, Main *mainvar, BHead *bhead)
static void expand_doit (FileData *fd, Main *mainvar, void *old)
static void expand_ipo (FileData *fd, Main *mainvar, Ipo *ipo)
static void expand_constraint_channels (FileData *fd, Main *mainvar, ListBase *chanbase)
static void expand_fmodifiers (FileData *fd, Main *mainvar, ListBase *list)
static void expand_fcurves (FileData *fd, Main *mainvar, ListBase *list)
static void expand_action (FileData *fd, Main *mainvar, bAction *act)
static void expand_keyingsets (FileData *fd, Main *mainvar, ListBase *list)
static void expand_animdata_nlastrips (FileData *fd, Main *mainvar, ListBase *list)
static void expand_animdata (FileData *fd, Main *mainvar, AnimData *adt)
static void expand_particlesettings (FileData *fd, Main *mainvar, ParticleSettings *part)
static void expand_group (FileData *fd, Main *mainvar, Group *group)
static void expand_key (FileData *fd, Main *mainvar, Key *key)
static void expand_nodetree (FileData *fd, Main *mainvar, bNodeTree *ntree)
static void expand_texture (FileData *fd, Main *mainvar, Tex *tex)
static void expand_brush (FileData *fd, Main *mainvar, Brush *brush)
static void expand_material (FileData *fd, Main *mainvar, Material *ma)
static void expand_lamp (FileData *fd, Main *mainvar, Lamp *la)
static void expand_lattice (FileData *fd, Main *mainvar, Lattice *lt)
static void expand_world (FileData *fd, Main *mainvar, World *wrld)
static void expand_mball (FileData *fd, Main *mainvar, MetaBall *mb)
static void expand_curve (FileData *fd, Main *mainvar, Curve *cu)
static void expand_mesh (FileData *fd, Main *mainvar, Mesh *me)
static void expand_constraint_cb (bConstraint *UNUSED(con), ID **idpoin, void *userdata)
static void expand_constraints (FileData *fd, Main *mainvar, ListBase *lb)
static void expand_bones (FileData *fd, Main *mainvar, Bone *bone)
static void expand_pose (FileData *fd, Main *mainvar, bPose *pose)
static void expand_armature (FileData *fd, Main *mainvar, bArmature *arm)
static void expand_object_expandModifiers (void *userData, Object *UNUSED(ob), ID **idpoin)
static void expand_object (FileData *fd, Main *mainvar, Object *ob)
static void expand_scene (FileData *fd, Main *mainvar, Scene *sce)
static void expand_camera (FileData *fd, Main *mainvar, Camera *ca)
static void expand_speaker (FileData *fd, Main *mainvar, Speaker *spk)
static void expand_sound (FileData *fd, Main *mainvar, bSound *snd)
static void expand_movieclip (FileData *fd, Main *mainvar, MovieClip *clip)
static void expand_main (FileData *fd, Main *mainvar)
static int object_in_any_scene (Main *mainvar, Object *ob)
static void give_base_to_objects (Main *mainvar, Scene *sce, Library *lib, const short idcode, const short is_link)
static void give_base_to_groups (Main *mainvar, Scene *scene)
static ID * append_named_part (Main *mainl, FileData *fd, const char *idname, const short idcode)
static ID * append_named_part_ex (const bContext *C, Main *mainl, FileData *fd, const char *idname, const int idcode, const int flag)
ID * BLO_library_append_named_part (Main *mainl, BlendHandle **bh, const char *idname, const int idcode)
ID * BLO_library_append_named_part_ex (const bContext *C, Main *mainl, BlendHandle **bh, const char *idname, const int idcode, const short flag)
static void append_id_part (FileData *fd, Main *mainvar, ID *id, ID **id_r)
static Main * library_append_begin (Main *mainvar, FileData **fd, const char *filepath)
Main * BLO_library_append_begin (Main *mainvar, BlendHandle **bh, const char *filepath)
static void library_append_end (const bContext *C, Main *mainl, FileData **fd, int idcode, short flag)
void BLO_library_append_end (const bContext *C, struct Main *mainl, BlendHandle **bh, int idcode, short flag)
void * BLO_library_read_struct (FileData *fd, BHead *bh, const char *blockname)
static int mainvar_count_libread_blocks (Main *mainvar)
BlendFileData * blo_read_blendafterruntime (int file, const char *name, int actualsize, ReportList *reports)
Variables
static const char * ptcache_data_struct []
Detailed Description
Definition in file readfile.c.
Define Documentation
#define DNA_DEPRECATED_ALLOW
Definition at line 53 of file readfile.c.
#define GS (a) (*((short *)(a)))
Definition at line 221 of file readfile.c.
Referenced by append_id_part(), append_named_part_ex(), blo_add_library_pointer_map(), change_idid_adr_fd(), expand_main(), is_yet_read(), lib_link_animdata(), lib_link_modifiers__linkModifiers(), lib_link_nladata_strips(), lib_link_screen(), lib_link_screen_restore(), ntree_version_245(), read_libblock(), read_libraries(), restore_pointer_by_name(), and split_libdata().
#define SWITCH_LONGINT (a)
Value:
{ \
    char s_i, *p_i; \
    p_i= (char *)&(a);  \
    s_i=p_i[0]; p_i[0]=p_i[7]; p_i[7]=s_i; \
    s_i=p_i[1]; p_i[1]=p_i[6]; p_i[6]=s_i; \
    s_i=p_i[2]; p_i[2]=p_i[5]; p_i[5]=s_i; \
    s_i=p_i[3]; p_i[3]=p_i[4]; p_i[4]=s_i; }
Definition at line 227 of file readfile.c.
Referenced by bh4_from_bh8(), IDP_DirectLinkArray(), IDP_DirectLinkProperty(), and test_pointer_array().
Typedef Documentation
typedef struct OldNew OldNew
typedef struct OldNewMap OldNewMap
typedef struct tConstraintExpandData tConstraintExpandData
typedef struct tConstraintLinkData tConstraintLinkData
Function Documentation
static void add_main_to_main (Main * mainvar, Main * from) [static]
Definition at line 428 of file readfile.c.
References BLI_movelisttolist(), MAX_LIBARRAY, and set_listbasepointers().
Referenced by blo_join_main().
static void alphasort_version_246 (FileData * fd, Library * lib, Mesh * me) [static]
Definition at line 6824 of file readfile.c.
References CD_MTFACE, CustomDataLayer::data, ELEM, Mesh::fdata, Material::id, CustomData::layers, ID::lib, MA_ZTRANSP, MAP_ALPHA, MTex::mapto, Mesh::mat, MFace::mat_nr, MAX_MTEX, Mesh::mface, Material::mode, MTFace::mode, Material::mtex, newlibadr(), NULL, TF_ADD, TF_ALPHA, TF_ALPHASORT, TF_CLIP, Mesh::totcol, CustomData::totlayer, MTFace::transp, and CustomDataLayer::type.
Referenced by do_versions().
static void append_id_part (FileData * fd, Main * mainvar, ID * id, ID ** id_r) [static]
Definition at line 14619 of file readfile.c.
References bhead_id_name(), blo_firstbhead(), blo_nextbhead(), BHead::code, ENDB, ID::flag, GS, LIB_READ, LIB_TEST, ID::name, and read_libblock().
Referenced by read_libraries().
static ID* append_named_part (Main * mainl, FileData * fd, const char * idname, const short idcode) [static]
Definition at line 14523 of file readfile.c.
References bhead_id_name(), BLI_assert, blo_firstbhead(), blo_nextbhead(), BHead::code, ENDB, ID::flag, id_sort_by_name(), is_yet_read(), LIB_EXTERN, LIB_INDIRECT, LIB_TESTEXT, FileData::libmap, NULL, BHead::old, oldnewmap_insert(), read_libblock(), and which_libbase().
Referenced by append_named_part_ex(), and BLO_library_append_named_part().
static ID* append_named_part_ex (const bContext * C, Main * mainl, FileData * fd, const char * idname, const int idcode, const int flag) [static]
Definition at line 14570 of file readfile.c.
References append_named_part(), Scene::base, BLI_addtail(), CTX_data_scene(), CTX_wm_view3d(), FILE_ACTIVELAY, FILE_AUTOSELECT, Object::flag, Base::flag, GS, Object::id, ID_OB, Base::lay, Scene::lay, Object::lay, View3D::layact, MEM_callocN(), Object::mode, ID::name, Base::object, SELECT, and ID::us.
Referenced by BLO_library_append_named_part_ex().
static void area_add_header_region (ScrArea * sa, ListBase * lb) [static]
Definition at line 6874 of file readfile.c.
References View2D::align, ARegion::alignment, BLI_addtail(), View2D::flag, HEADERDOWN, ScrArea::headertype, View2D::keepofs, View2D::keeptot, View2D::keepzoom, MEM_callocN(), ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_TOP, RGN_TYPE_HEADER, ARegion::v2d, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_KEEPASPECT, V2D_KEEPTOT_STRICT, V2D_LIMITZOOM, V2D_LOCKOFS_Y, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, V2D_PIXELOFS_X, and V2D_PIXELOFS_Y.
Referenced by do_versions_windowmanager_2_50().
static void area_add_window_regions (ScrArea * sa, SpaceLink * sl, ListBase * lb) [static]
Definition at line 6918 of file readfile.c.
References SpaceAction::action, View2D::align, ARegion::alignment, BLI_addtail(), BLI_insertlinkbefore(), View2D::cur, ListBase::first, ARegion::flag, View2D::flag, SpaceText::flags, FLT_MAX, View2D::keepofs, View2D::keeptot, View2D::keepzoom, View2D::max, MAXFRAMEF, View2D::maxzoom, MEM_callocN(), View2D::min, View2D::minzoom, SpaceAction::mode, ARegion::next, NULL, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_ALIGN_TOP, RGN_FLAG_HIDDEN, RGN_SPLIT_PREV, RGN_TYPE_CHANNELS, RGN_TYPE_TOOL_PROPS, RGN_TYPE_TOOLS, RGN_TYPE_UI, RGN_TYPE_WINDOW, SACTCONT_SHAPEKEY, View2D::scroll, sequencer_init_preview_region(), SPACE_ACTION, SPACE_BUTS, SPACE_FILE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_OUTLINER, SPACE_SEQ, SPACE_TEXT, SPACE_TIME, SPACE_VIEW3D, SpaceLink::spacetype, ST_FIND_WRAP, View2D::tot, ScrArea::totrct, ARegion::v2d, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_ALIGN_NO_POS_Y, V2D_IS_INITIALISED, V2D_KEEPASPECT, V2D_KEEPTOT_STRICT, V2D_LIMITZOOM, V2D_LOCKOFS_Y, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, V2D_SCROLL_BOTTOM, V2D_SCROLL_BOTTOM_O, V2D_SCROLL_LEFT, V2D_SCROLL_RIGHT, V2D_SCROLL_SCALE_HORIZONTAL, V2D_SCROLL_SCALE_VERTICAL, V2D_VIEWSYNC_AREA_VERTICAL, view3d_split_250(), ARegion::winrct, ARegion::winx, ScrArea::winx, ARegion::winy, ScrArea::winy, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by do_versions_windowmanager_2_50().
static void bh4_from_bh8 (BHead * bhead, BHead8 * bhead8, int do_endian_swap) [static]
Definition at line 594 of file readfile.c.
References BHead8::code, BHead4::code, ENDB, BHead8::len, BHead4::len, BHead8::nr, BHead4::nr, BHead4::old, BHead8::old, OldNew::old, BHead8::SDNAnr, BHead4::SDNAnr, and SWITCH_LONGINT.
Referenced by get_bhead().
static void bh8_from_bh4 (BHead * bhead, BHead4 * bhead4) [static]
Definition at line 624 of file readfile.c.
References BHead4::code, BHead8::code, ENDB, BHead4::len, BHead8::len, BHead4::nr, BHead8::nr, BHead4::old, BHead8::old, BHead4::SDNAnr, and BHead8::SDNAnr.
Referenced by get_bhead().
char* bhead_id_name (FileData * fd, BHead * bhead)
Definition at line 13589 of file readfile.c.
References FileData::id_name_offs.
Referenced by append_id_part(), append_named_part(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_previews(), and is_yet_read().
static void BKE_reportf_wrap (ReportList * reports, ReportType type, const char * format, ...) [static]
Definition at line 261 of file readfile.c.
References BKE_report(), and G.
Referenced by direct_link_library(), do_versions(), lib_link_scene(), and read_libraries().
void blo_add_library_pointer_map (ListBase * mainlist, FileData * fd)
Definition at line 1359 of file readfile.c.
References ListBase::first, GS, i, FileData::libmap, MAX_LIBARRAY, ID::name, ID::next, Main::next, oldnewmap_insert(), and set_listbasepointers().
Referenced by BLO_read_from_memfile().
void blo_clear_proxy_pointers_from_lib (Main * oldmain)
Definition at line 1225 of file readfile.c.
References ListBase::first, Object::id, ID::lib, ID::next, NULL, Main::object, and Object::proxy_from.
Referenced by BLO_read_from_memfile().
static FileData* blo_decode_and_check (FileData * fd, ReportList * reports) [static]
Definition at line 977 of file readfile.c.
References BKE_reportf(), blo_freefiledata(), decode_blender_header(), FD_FLAGS_FILE_OK, FileData::flags, NULL, read_file_dna(), FileData::relabase, and RPT_ERROR.
Referenced by blo_openblenderfile(), blo_openblendermemfile(), blo_openblendermemory(), and blo_read_blendafterruntime().
void blo_end_image_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1263 of file readfile.c.
References Image::bindcode, BLI_remlink(), OldNewMap::entries, ListBase::first, Image::gputexture, i, Image::ibufs, Scene::id, Image::id, IMA_MAX_RENDER_SLOT, Main::image, FileData::imamap, OldNewMap::nentries, newimaadr(), OldNew::newp, bNode::next, Link::next, next, ID::next, bNodeTree::nodes, Scene::nodetree, OldNew::nr, NULL, bNode::preview, Image::renders, and Main::scene.
Referenced by BLO_read_from_memfile().
void blo_end_movieclip_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1329 of file readfile.c.
References MovieClip::cache, MovieTracking::camera, CMP_NODE_MOVIEDISTORTION, OldNewMap::entries, ListBase::first, i, Scene::id, MovieClip::id, MovieTrackingCamera::intrinsics, Main::movieclip, FileData::movieclipmap, OldNewMap::nentries, newmclipadr(), OldNew::newp, bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, OldNew::nr, NULL, Main::scene, bNode::storage, MovieClip::tracking, and bNode::type.
Referenced by BLO_read_from_memfile().
static Main* blo_find_main (FileData * fd, ListBase * mainlist, const char * filepath, const char * relabase) [static]
Definition at line 532 of file readfile.c.
References alloc_libblock(), BLI_addtail(), BLI_path_cmp, BLI_strncpy(), cleanup_path(), Main::curlib, FILE_MAX, Library::filepath, ListBase::first, G, G_DEBUG, ID_LI, if(), Main::library, MEM_callocN(), Library::name, Main::name, Main::next, and read_file_version().
Referenced by expand_doit(), and library_append_begin().
BHead* blo_firstbhead (FileData * fd)
Definition at line 738 of file readfile.c.
References BHeadN::bhead, ListBase::first, get_bhead(), FileData::listbase, and NULL.
Referenced by append_id_part(), append_named_part(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_linkable_groups(), BLO_blendhandle_get_previews(), BLO_blendhandle_print_sizes(), blo_read_file_internal(), find_bhead(), read_file_dna(), read_file_version(), and sort_bhead_old_map().
void blo_freefiledata (FileData * fd)
Definition at line 1056 of file readfile.c.
References FileData::bheadmap, BLI_freelistN(), FileData::buffer, FileData::compflags, FileData::datamap, DNA_sdna_free(), FD_FLAGS_NOT_MY_BUFFER, FD_FLAGS_NOT_MY_LIBMAP, FileData::filedes, FileData::filesdna, FileData::flags, FileData::globmap, FileData::gzfiledes, FileData::imamap, FileData::libmap, FileData::listbase, MEM_freeN(), FileData::memsdna, FileData::movieclipmap, NULL, and oldnewmap_free().
Referenced by BLO_blendhandle_close(), blo_decode_and_check(), blo_read_blendafterruntime(), BLO_read_from_file(), BLO_read_from_memfile(), BLO_read_from_memory(), library_append_end(), and read_libraries().
int BLO_has_bfile_extension (const char * str)
Definition at line 1103 of file readfile.c.
References BLI_testextensie().
Referenced by blend_save_check(), BLO_is_a_library(), file_extension_type(), and filelist_read_library().
int BLO_is_a_library (const char * path, char * dir, char * group)
Definition at line 1108 of file readfile.c.
References BLI_last_slash(), BLI_strncpy(), BLO_has_bfile_extension(), GROUP_MAX, len(), NULL, and strlen().
Referenced by filelist_islibrary(), is_filtered_lib(), and wm_link_append_exec().
void blo_join_main (ListBase * mainlist)
Definition at line 440 of file readfile.c.
References add_main_to_main(), BLI_remlink(), ListBase::first, MEM_freeN(), and Main::next.
Referenced by blo_read_file_internal(), BLO_read_from_memfile(), library_append_end(), and write_file_handle().
Main* BLO_library_append_begin (struct Main * mainvar, BlendHandle ** bh, const char * filepath) [read]
Initialize the BlendHandle for appending or linking library data.
Parameters:
mainvar The current main database eg G.main or CTX_data_main(C).
bh A blender file handle as returned by BLO_blendhandle_from_file or BLO_blendhandle_from_memory.
filepath Used for relative linking, copied to the lib->name
Returns:
the library Main, to be passed to BLO_library_append_named_part as mainl.
Definition at line 14659 of file readfile.c.
References library_append_begin().
Referenced by bpy_lib_exit(), KX_BlenderSceneConverter::LinkBlendFile(), and wm_link_append_exec().
void BLO_library_append_end (const bContext * C, struct Main * mainl, BlendHandle ** bh, int idcode, short flag)
Definition at line 14730 of file readfile.c.
References library_append_end().
ID* BLO_library_append_named_part (struct Main * mainl, BlendHandle ** bh, const char * idname, const int idcode) [read]
Link/Append a named datablock from an external blend file.
Parameters:
mainl The main database to link from (not the active one).
bh The blender file handle.
idname The name of the datablock (without the 2 char ID prefix)
idcode The kind of datablock to link.
Returns:
the appended ID when found.
Definition at line 14607 of file readfile.c.
References append_named_part().
Referenced by bpy_lib_exit(), and KX_BlenderSceneConverter::LinkBlendFile().
ID* BLO_library_append_named_part_ex (const bContext * C, Main * mainl, BlendHandle ** bh, const char * idname, const int idcode, const short flag)
Definition at line 14613 of file readfile.c.
References append_named_part_ex().
void* BLO_library_read_struct (FileData * fd, BHead * bh, const char * blockname)
Definition at line 14737 of file readfile.c.
References read_struct().
Referenced by BLO_blendhandle_get_previews().
void blo_make_image_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1234 of file readfile.c.
References ListBase::first, Image::gputexture, Image::ibufs, Scene::id, Image::id, IMA_MAX_RENDER_SLOT, Main::image, FileData::imamap, bNode::next, Link::next, ID::next, bNodeTree::nodes, Scene::nodetree, oldnewmap_insert(), oldnewmap_new(), bNode::preview, Image::renders, and Main::scene.
Referenced by BLO_read_from_memfile().
void blo_make_movieclip_pointer_map (FileData * fd, Main * oldmain)
Definition at line 1302 of file readfile.c.
References MovieClip::cache, MovieTracking::camera, CMP_NODE_MOVIEDISTORTION, ListBase::first, Scene::id, MovieClip::id, MovieTrackingCamera::intrinsics, Main::movieclip, FileData::movieclipmap, bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, oldnewmap_insert(), oldnewmap_new(), Main::scene, bNode::storage, MovieClip::tracking, and bNode::type.
Referenced by BLO_read_from_memfile().
BHead* blo_nextbhead (FileData * fd, BHead * thisblock)
Definition at line 766 of file readfile.c.
References BHeadN::bhead, get_bhead(), GET_INT_FROM_POINTER, BHeadN::next, and NULL.
Referenced by append_id_part(), append_named_part(), BLO_blendhandle_get_datablock_names(), BLO_blendhandle_get_linkable_groups(), BLO_blendhandle_get_previews(), BLO_blendhandle_print_sizes(), blo_read_file_internal(), find_bhead(), read_data_into_oldnewmap(), read_file_dna(), read_file_version(), read_global(), read_libblock(), and sort_bhead_old_map().
FileData* blo_openblenderfile (const char * filepath, ReportList * reports)
Definition at line 999 of file readfile.c.
References BKE_reportf(), BLI_gzopen(), BLI_strncpy(), blo_decode_and_check(), fd_read_gzip_from_file(), filedata_new(), FileData::gzfiledes, NULL, FileData::read, FileData::relabase, and RPT_ERROR.
Referenced by BLO_blendhandle_from_file(), BLO_read_from_file(), and read_libraries().
FileData* blo_openblendermemfile (MemFile * memfile, ReportList * reports)
Definition at line 1038 of file readfile.c.
References BKE_report(), blo_decode_and_check(), FD_FLAGS_NOT_MY_BUFFER, fd_read_from_memfile(), filedata_new(), FileData::flags, FileData::memfile, NULL, FileData::read, and RPT_ERROR.
Referenced by BLO_read_from_memfile().
FileData* blo_openblendermemory (void * mem, int memsize, ReportList * reports)
Definition at line 1021 of file readfile.c.
References BKE_report(), blo_decode_and_check(), FileData::buffer, FileData::buffersize, FD_FLAGS_NOT_MY_BUFFER, fd_read_from_memory(), filedata_new(), FileData::flags, NULL, FileData::read, RPT_ERROR, and SIZEOFBLENDERHEADER.
Referenced by BLO_blendhandle_from_memory(), and BLO_read_from_memory().
BHead* blo_prevbhead (FileData * UNUSEDfd, BHead * thisblock)
Definition at line 758 of file readfile.c.
References BHeadN::bhead, GET_INT_FROM_POINTER, NULL, and BHeadN::prev.
Referenced by find_previous_lib().
BlendFileData* blo_read_blendafterruntime (int file, const char * name, int actualsize, ReportList * reports)
Definition at line 14921 of file readfile.c.
References BLI_strncpy(), blo_decode_and_check(), blo_freefiledata(), blo_read_file_internal(), FileData::buffersize, fd_read_from_file(), filedata_new(), FileData::filedes, NULL, FileData::read, FileData::relabase, and FileData::reports.
Referenced by BLO_read_runtime().
BlendFileData* blo_read_file_internal (FileData * fd, const char * filepath)
Definition at line 13428 of file readfile.c.
References BLENFILETYPE_BLEND, BLI_addtail(), BLI_strncpy(), blo_firstbhead(), blo_join_main(), blo_nextbhead(), BHead::code, DATA, DNA1, do_versions(), ENDB, FileData::fileversion, fix_relpaths_library(), GLOB, ID_ID, ID_LI, ID_SCR, ID_SCRN, ListBase::last, LIB_EXTERN, lib_link_all(), LIB_LOCAL, LIB_READ, lib_verify_nodetree(), link_global(), BlendFileData::main, FileData::mainlist, MEM_callocN(), FileData::memfile, Main::name, NULL, read_global(), read_libblock(), read_libraries(), read_userdef(), FileData::relabase, REND, TEST, TRUE, BlendFileData::type, USER, and Main::versionfile.
Referenced by blo_read_blendafterruntime(), BLO_read_from_file(), BLO_read_from_memfile(), and BLO_read_from_memory().
void blo_split_main (ListBase * mainlist, Main * main)
Definition at line 479 of file readfile.c.
References BLI_addtail(), Main::curlib, ListBase::first, i, Library::id, ListBase::last, Main::library, main(), MAX_LIBARRAY, MEM_callocN(), ID::next, Main::next, NULL, set_listbasepointers(), and split_libdata().
Referenced by BLO_read_from_memfile(), library_append_begin(), and write_file_handle().
static void bone_version_238 (ListBase * lb) [static]
Definition at line 6557 of file readfile.c.
References Bone::childbase, Bone::dist, ListBase::first, Bone::length, Bone::next, Bone::rad_head, and Bone::rad_tail.
Referenced by do_versions().
static void bone_version_239 (ListBase * lb) [static]
Definition at line 6573 of file readfile.c.
References Bone::childbase, ListBase::first, Bone::layer, and Bone::next.
Referenced by do_versions().
static void butspace_version_132 (SpaceButs * buts) [static]
Definition at line 5213 of file readfile.c.
Referenced by lib_link_screen().
static void change_idid_adr (ListBase * mainlist, FileData * basefd, void * old, void * new) [static]
Definition at line 1205 of file readfile.c.
References change_idid_adr_fd(), Main::curlib, Library::filedata, ListBase::first, and Main::next.
Referenced by direct_link_library(), and read_libraries().
static void change_idid_adr_fd (FileData * fd, void * old, void * new) [static]
Definition at line 1190 of file readfile.c.
References OldNewMap::entries, GS, i, ID_ID, FileData::libmap, OldNewMap::nentries, OldNew::newp, and OldNew::nr.
Referenced by change_idid_adr(), and expand_doit().
static void cleanup_path (const char * relabase, char * name) [static]
Definition at line 503 of file readfile.c.
References BLI_cleanup_dir(), BLI_splitdirstring(), and FILE_MAXFILE.
Referenced by blo_find_main(), direct_link_library(), and read_libraries().
static void composite_patch (bNodeTree * ntree, Scene * scene) [static]
Definition at line 4787 of file readfile.c.
References CMP_NODE_COMPOSITE, CMP_NODE_DEFOCUS, CMP_NODE_OUTPUT_FILE, CMP_NODE_R_LAYERS, ELEM4, ListBase::first, Scene::id, bNode::id, bNode::next, bNodeTree::nodes, NULL, and bNode::type.
Referenced by lib_link_scene().
void convert_tface_mt (FileData * fd, Main * main) [static]
Definition at line 7505 of file readfile.c.
References BKE_report(), do_version_tface(), G, main(), FileData::reports, RPT_WARNING, Main::subversionfile, and Main::versionfile.
Referenced by lib_link_mesh().
static void customdata_version_242 (Mesh * me) [static]
Definition at line 6634 of file readfile.c.
References BLI_snprintf(), CD_ASSIGN, CD_CALLOC, CD_MCOL, CD_MDEFORMVERT, CD_MEDGE, CD_MFACE, CD_MSTICKY, CD_MTFACE, CD_MVERT, CustomData_add_layer(), Mesh::dvert, Mesh::fdata, CustomData::layers, Mesh::mcol, Mesh::medge, MEM_freeN(), mesh_update_customdata_pointers(), Mesh::mface, Mesh::msticky, Mesh::mtface, Mesh::mvert, CustomDataLayer::name, NULL, Mesh::tface, Mesh::totedge, Mesh::totface, CustomData::totlayer, Mesh::totvert, TRUE, and CustomDataLayer::type.
Referenced by do_versions().
static void customdata_version_243 (Mesh * me) [static]
Definition at line 6716 of file readfile.c.
References CustomDataLayer::active, CustomDataLayer::active_rnd, Mesh::fdata, CustomData::layers, and CustomData::totlayer.
Referenced by do_versions().
static const char* dataname (short id_code) [static]
Definition at line 6234 of file readfile.c.
References ID_AC, ID_AR, ID_BR, ID_CA, ID_CU, ID_GD, ID_GR, ID_IM, ID_IP, ID_KE, ID_LA, ID_LI, ID_LT, ID_MA, ID_MB, ID_MC, ID_ME, ID_NT, ID_OB, ID_PA, ID_SCE, ID_SCR, ID_SO, ID_SPK, ID_TE, ID_TXT, ID_VF, and ID_WO.
Referenced by read_libblock().
static void decode_blender_header (FileData * fd) [static]
Definition at line 792 of file readfile.c.
References B_ENDIAN, FD_FLAGS_FILE_OK, FD_FLAGS_FILE_POINTSIZE_IS_4, FD_FLAGS_POINTSIZE_DIFFERS, FD_FLAGS_SWITCH_ENDIAN, FileData::fileversion, FileData::flags, L_ENDIAN, FileData::read, and SIZEOFBLENDERHEADER.
Referenced by blo_decode_and_check().
static void direct_link_action (FileData * fd, bAction * act) [static]
Definition at line 1955 of file readfile.c.
References bAction::chanbase, bActionGroup::channels, bActionChannel::constraintChannels, bAction::curves, direct_link_fcurves(), ListBase::first, bAction::groups, bActionChannel::grp, ListBase::last, link_list(), bAction::markers, newdataadr(), bActionChannel::next, and bActionGroup::next.
Referenced by read_libblock().
static void direct_link_animdata (FileData * fd, AnimData * adt) [static]
Definition at line 2106 of file readfile.c.
References AnimData::actstrip, direct_link_fcurves(), direct_link_nladata(), AnimData::drivers, link_list(), newdataadr(), AnimData::nla_tracks, and NULL.
Referenced by direct_link_armature(), direct_link_camera(), direct_link_curve(), direct_link_key(), direct_link_lamp(), direct_link_latt(), direct_link_material(), direct_link_mball(), direct_link_mesh(), direct_link_nodetree(), direct_link_object(), direct_link_particlesettings(), direct_link_scene(), direct_link_speaker(), direct_link_texture(), and direct_link_world().
static void direct_link_armature (FileData * fd, bArmature * arm) [static]
Definition at line 2613 of file readfile.c.
References bArmature::act_bone, bArmature::act_edbone, bArmature::adt, bArmature::bonebase, direct_link_animdata(), direct_link_bones(), bArmature::edbo, ListBase::first, link_list(), newdataadr(), Bone::next, NULL, and bArmature::sketch.
Referenced by read_libblock().
static void direct_link_bones (FileData * fd, Bone * bone) [static]
Definition at line 2596 of file readfile.c.
References BONE_DRAW_ACTIVE, Bone::childbase, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, Bone::flag, FileData::flags, IDP_DirectLinkProperty(), link_list(), newdataadr(), Bone::next, Bone::parent, and Bone::prop.
Referenced by direct_link_armature().
static void direct_link_brush (FileData * fd, Brush * brush) [static]
Definition at line 1664 of file readfile.c.
References brush_curve_preset(), Brush::curve, CURVE_PRESET_SHARP, direct_link_curvemapping(), Brush::icon_imbuf, newdataadr(), NULL, and Brush::preview.
Referenced by read_libblock().
static void direct_link_camera (FileData * fd, Camera * ca) [static]
Definition at line 2655 of file readfile.c.
References Camera::adt, direct_link_animdata(), and newdataadr().
Referenced by read_libblock().
static void direct_link_constraints (FileData * fd, ListBase * lb) [static]
Definition at line 2490 of file readfile.c.
References CONSTRAINT_SPACE_POSE, CONSTRAINT_SPACEONCE, CONSTRAINT_TYPE_CHILDOF, CONSTRAINT_TYPE_KINEMATIC, CONSTRAINT_TYPE_PYTHON, CONSTRAINT_TYPE_SPLINEIK, bConstraint::data, data, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, bConstraint::flag, FileData::flags, IDP_DirectLinkProperty(), bConstraint::lin_error, link_list(), newdataadr(), bConstraint::next, bConstraint::ownspace, bSplineIKConstraint::points, bPythonConstraint::prop, bConstraint::rot_error, bPythonConstraint::targets, and bConstraint::type.
Referenced by direct_link_object(), and direct_link_pose().
static void direct_link_curve (FileData * fd, Curve * cu) [static]
Definition at line 3093 of file readfile.c.
References Curve::actbox, Curve::adt, Curve::bb, Curve::bev, Nurb::bezt, Nurb::bp, Nurb::charidx, direct_link_animdata(), Curve::disp, Curve::editfont, Curve::editnurb, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, FileData::flags, Nurb::knotsu, Nurb::knotsv, ListBase::last, Curve::lastsel, Curve::linewidth, link_list(), Curve::mat, Nurb::mat_nr, MAXTEXTBOX, MEM_callocN(), MEM_freeN(), newdataadr(), Nurb::next, NULL, Curve::nurb, Curve::path, Curve::str, Curve::strinfo, switch_endian_knots(), Curve::tb, test_pointer_array(), Curve::totbox, Curve::vfont, TextBox::w, and Curve::wordspace.
Referenced by read_libblock().
static void direct_link_curvemapping (FileData * fd, CurveMapping * cumap) [static]
Definition at line 1633 of file readfile.c.
References CurveMapping::cm, CM_TOT, CUMA_PREMULLED, CurveMap::curve, CurveMapping::flag, newdataadr(), NULL, CurveMap::premultable, and CurveMap::table.
Referenced by direct_link_brush(), direct_link_lamp(), direct_link_modifiers(), direct_link_nodetree(), direct_link_screen(), and direct_link_texture().
static void direct_link_customdata (FileData * fd, CustomData * data, int count) [static]
Definition at line 3808 of file readfile.c.
References CD_FLAG_EXTERNAL, CD_FLAG_IN_MEMORY, CD_MDISPS, CustomData_update_typemap(), CustomData_verify_versions(), CustomDataLayer::data, direct_link_mdisps(), CustomData::external, CustomDataLayer::flag, i, CustomData::layers, newdataadr(), NULL, CustomData::totlayer, CustomDataLayer::type, and UNLIKELY.
Referenced by direct_link_mesh().
static void direct_link_dverts (FileData * fd, int count, MDeformVert * mdverts) [static]
Definition at line 3748 of file readfile.c.
References MDeformVert::dw, i, MEM_freeN(), MEM_mallocN(), newdataadr(), NULL, and MDeformVert::totweight.
Referenced by direct_link_latt(), and direct_link_mesh().
static void direct_link_fcurves (FileData * fd, ListBase * list) [static]
Definition at line 1888 of file readfile.c.
References FCurve::bezt, direct_link_fmodifiers(), FCurve::driver, DRIVER_TARGETS_LOOPER, DRIVER_TARGETS_LOOPER_END, ChannelDriver::expr_comp, ListBase::first, FCurve::fpt, FCurve::grp, link_list(), FCurve::modifiers, newdataadr(), FCurve::next, DriverVar::next, NULL, FCurve::rna_path, and ChannelDriver::variables.
Referenced by direct_link_action(), direct_link_animdata(), and direct_link_nladata_strips().
static void direct_link_fmodifiers (FileData * fd, ListBase * list) [static]
Definition at line 1844 of file readfile.c.
References FMod_Generator::arraysize, FMod_Generator::coefficients, FMod_Envelope::data, data, FModifier::data, FModifier::edata, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, FileData::flags, FMODIFIER_TYPE_ENVELOPE, FMODIFIER_TYPE_GENERATOR, FMODIFIER_TYPE_PYTHON, IDP_DirectLinkProperty(), newdataadr(), FModifier::next, NULL, FMod_Python::prop, SWITCH_INT, and FModifier::type.
Referenced by direct_link_fcurves(), and direct_link_nladata_strips().
static void direct_link_gpencil (FileData * fd, bGPdata * gpd) [static]
Definition at line 5182 of file readfile.c.
References bGPDlayer::actframe, ListBase::first, bGPDlayer::frames, bGPdata::layers, link_list(), newdataadr(), bGPDlayer::next, bGPDstroke::next, bGPDframe::next, NULL, bGPDstroke::points, and bGPDframe::strokes.
Referenced by direct_link_screen(), and read_libblock().
static void direct_link_group (FileData * fd, Group * group) [static]
Definition at line 6119 of file readfile.c.
References Group::gobject, and link_list().
Referenced by read_libblock().
static void direct_link_image (FileData * fd, Image * ima) [static]
Definition at line 3007 of file readfile.c.
References Image::anim, Image::bindcode, direct_link_packedfile(), direct_link_preview_image(), ListBase::first, Image::gputexture, Image::ibufs, IMA_MAX_RENDER_SLOT, FileData::imamap, ListBase::last, Image::last_render_slot, link_ibuf_list(), newimaadr(), NULL, Image::ok, Image::packedfile, Image::preview, Image::render_slot, Image::renders, Image::repbind, and Image::rr.
Referenced by read_libblock().
static void direct_link_ipo (FileData * fd, Ipo * ipo) [static]
Definition at line 1741 of file readfile.c.
References IpoCurve::bezt, IpoCurve::bp, Ipo::curve, IpoCurve::driver, ListBase::first, link_list(), newdataadr(), and IpoCurve::next.
Referenced by read_libblock().
static void direct_link_key (FileData * fd, Key * key) [static]
Definition at line 2780 of file readfile.c.
References Key::adt, Key::block, KeyBlock::data, direct_link_animdata(), FD_FLAGS_SWITCH_ENDIAN, ListBase::first, FileData::flags, link_list(), newdataadr(), KeyBlock::next, Key::refkey, and switch_endian_keyblock().
Referenced by read_libblock().
static void direct_link_keyingsets (FileData * fd, ListBase * list) [static]
Definition at line 2063 of file readfile.c.
References ListBase::first, link_list(), newdataadr(), KeyingSet::next, KS_Path::next, KeyingSet::paths, and KS_Path::rna_path.
Referenced by direct_link_scene().
static void direct_link_keymapitem (FileData * fd, wmKeyMapItem * kmi) [static]
Definition at line 13363 of file readfile.c.
References FD_FLAGS_SWITCH_ENDIAN, wmKeyMapItem::flag, FileData::flags, IDP_DirectLinkProperty(), KMI_UPDATE, newdataadr(), NULL, wmKeyMapItem::properties, and wmKeyMapItem::ptr.
Referenced by read_userdef().
static void direct_link_lamp (FileData * fd, Lamp * la) [static]
Definition at line 2694 of file readfile.c.
References Lamp::adt, Lamp::curfalloff, direct_link_animdata(), direct_link_curvemapping(), direct_link_nodetree(), direct_link_preview_image(), MAX_MTEX, Lamp::mtex, newdataadr(), Lamp::nodetree, and Lamp::preview.
Referenced by read_libblock().
static void direct_link_latt (FileData * fd, Lattice * lt) [static]
Definition at line 3984 of file readfile.c.
References Lattice::adt, Lattice::def, direct_link_animdata(), direct_link_dverts(), Lattice::dvert, Lattice::editlatt, newdataadr(), NULL, Lattice::pntsu, Lattice::pntsv, and Lattice::pntsw.
Referenced by read_libblock().
static void direct_link_library (FileData * fd, Library * lib, Main * main) [static]
Definition at line 5976 of file readfile.c.
References BKE_reportf_wrap(), BLI_addtail(), BLI_path_cmp, BLI_remlink(), BLI_strncpy(), change_idid_adr(), cleanup_path(), Main::curlib, Library::filepath, ListBase::first, Main::library, FileData::mainlist, MEM_callocN(), MEM_freeN(), Library::name, Main::next, NULL, Library::parent, FileData::relabase, FileData::reports, and RPT_WARNING.
Referenced by read_libblock().
static void direct_link_material (FileData * fd, Material * ma) [static]
Definition at line 3271 of file readfile.c.
References Material::adt, direct_link_animdata(), direct_link_nodetree(), direct_link_preview_image(), ListBase::first, Material::gpumaterial, ListBase::last, MAX_MTEX, Material::mtex, newdataadr(), Material::nodetree, NULL, Material::preview, Material::ramp_col, and Material::ramp_spec.
Referenced by read_libblock().
static void direct_link_mball (FileData * fd, MetaBall * mb) [static]
Definition at line 2825 of file readfile.c.
References MetaBall::adt, MetaBall::bb, direct_link_animdata(), MetaBall::disp, MetaBall::editelems, MetaBall::elems, ListBase::first, ListBase::last, MetaBall::lastelem, link_list(), MetaBall::mat, newdataadr(), NULL, and test_pointer_array().
Referenced by read_libblock().
static void direct_link_mdisps (FileData * fd, int count, MDisps * mdisps, int external) [static]
Definition at line 3773 of file readfile.c.
References MDisps::disps, FD_FLAGS_SWITCH_ENDIAN, FileData::flags, MDisps::hidden, i, MDisps::level, logf, M_LN2, newdataadr(), sqrtf, SWITCH_INT, and MDisps::totdisp.
Referenced by direct_link_customdata().
static void direct_link_mesh (FileData * fd, Mesh * mesh) [static]
Definition at line 3840 of file readfile.c.
References Mesh::adt, Mesh::bb, CD_MDEFORMVERT, TFace::col, MultiresLevel::colfaces, CustomData_free(), CustomData_get(), direct_link_animdata(), direct_link_customdata(), direct_link_dverts(), Mesh::dvert, MultiresLevel::edges, Mesh::edit_btmesh, MultiresLevel::faces, FD_FLAGS_SWITCH_ENDIAN, Mesh::fdata, FileData::flags, i, Mesh::ldata, link_list(), Mesh::mat, Mesh::mcol, Mesh::medge, MEM_dupallocN(), MEM_freeN(), mesh_mpoly_to_mface(), mesh_update_customdata_pointers(), Mesh::mface, Mesh::mloop, Mesh::mloopcol, Mesh::mloopuv, Mesh::mpoly, Mesh::mselect, Mesh::msticky, Mesh::mtface, Mesh::mtpoly, multires_free(), Mesh::mvert, newdataadr(), MultiresLevel::next, NULL, SWITCH_INT, test_pointer_array(), Mesh::tface, Mesh::totedge, MultiresLevel::totface, Mesh::totface, Mesh::totloop, Mesh::totpoly, MultiresLevel::totvert, Mesh::totvert, MultiresLevel::verts, and Mesh::verts.
Referenced by read_libblock().
static void direct_link_modifiers (FileData * fd, ListBase * lb) [static]
Definition at line 4303 of file readfile.c.
References MeshDeformModifierData::bindcagecos, MeshDeformModifierData::bindcos, MeshDeformModifierData::bindinfluences, MeshDeformModifierData::bindoffsets, MeshDeformModifierData::bindweights, BKE_add_effector_weights(), BKE_ptcache_free(), DynamicPaintModifierData::brush, SurfaceModifierData::bvhtree, CollisionModifierData::bvhtree, DynamicPaintSurface::canvas, DynamicPaintModifierData::canvas, ClothModifierData::clothObject, WeightVGEditModifierData::cmap_curve, SmokeModifierData::coll, ClothModifierData::coll_parms, WarpModifierData::curfalloff, CollisionModifierData::current_v, CollisionModifierData::current_x, CollisionModifierData::current_xnew, DynamicPaintSurface::data, direct_link_curvemapping(), direct_link_pointcache_list(), ParticleSystemModifierData::dm, SurfaceModifierData::dm, DynamicPaintBrushSettings::dm, DynamicPaintCanvasSettings::dm, SmokeModifierData::domain, MeshDeformModifierData::dyngrid, MeshDeformModifierData::dyninfluences, MeshDeformModifierData::dynverts, DynamicPaintSurface::effector_weights, SmokeDomainSettings::effector_weights, ClothSimSettings::effector_weights, SubsurfModifierData::emCache, eModifierType_Armature, eModifierType_Cloth, eModifierType_Collision, eModifierType_DynamicPaint, eModifierType_Explode, eModifierType_Fluidsim, eModifierType_Hook, eModifierType_MeshDeform, eModifierType_None, eModifierType_Ocean, eModifierType_ParticleSystem, eModifierType_Smoke, eModifierType_Subsurf, eModifierType_Surface, eModifierType_Warp, eModifierType_WeightVGEdit, eParticleSystemFlag_file_loaded, eParticleSystemFlag_psys_updated, ModifierData::error, ExplodeModifierData::facepa, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, ParticleSystemModifierData::flag, PointCache::flag, FileData::flags, DynamicPaintCanvasSettings::flags, SmokeModifierData::flow, SmokeDomainSettings::fluid, FluidsimSettings::fmd, FluidsimModifierData::fss, HookModifierData::indexar, ListBase::last, link_list(), SubsurfModifierData::mCache, FluidsimSettings::meshVelocities, CollisionModifierData::mfaces, MOD_DPAINT_BAKING, MOD_OCEAN_REFRESH_ADD, MOD_OCEAN_REFRESH_RESET, MOD_OCEAN_REFRESH_SIM, MOD_SMOKE_TYPE_COLL, MOD_SMOKE_TYPE_DOMAIN, MOD_SMOKE_TYPE_FLOW, modifierType_getInfo(), newdataadr(), DynamicPaintSurface::next, ModifierData::next, NULL, SmokeCollSettings::numpoints, SurfaceModifierData::numverts, CollisionModifierData::numverts, OceanModifierData::ocean, OceanModifierData::oceancache, DynamicPaintBrushSettings::paint_ramp, DynamicPaintBrushSettings::pmd, DynamicPaintCanvasSettings::pmd, SmokeDomainSettings::point_cache, ClothModifierData::point_cache, DynamicPaintSurface::pointcache, SmokeCollSettings::points, ClothSimSettings::presets, ArmatureModifierData::prevCos, ParticleSystemModifierData::psys, DynamicPaintBrushSettings::psys, SmokeFlowSettings::psys, PTCACHE_FAKE_SMOKE, DynamicPaintSurface::ptcaches, SmokeDomainSettings::ptcaches, ClothModifierData::ptcaches, OceanModifierData::refresh, ClothSimSettings::reset, ModifierData::scene, SmokeDomainSettings::shadow, ClothModifierData::sim_parms, SmokeFlowSettings::smd, SmokeDomainSettings::smd, DynamicPaintCanvasSettings::surfaces, SWITCH_INT, SmokeDomainSettings::tex, SmokeDomainSettings::tex_shadow, SmokeDomainSettings::tex_wt, CollisionModifierData::time_x, CollisionModifierData::time_xnew, MeshDeformModifierData::totcagevert, HookModifierData::totindex, MeshDeformModifierData::totvert, SmokeModifierData::type, ModifierData::type, SurfaceModifierData::v, DynamicPaintBrushSettings::vel_ramp, SmokeDomainSettings::wt, SurfaceModifierData::x, CollisionModifierData::x, and CollisionModifierData::xnew.
Referenced by direct_link_object().
static void direct_link_motionpath (FileData * fd, bMotionPath * mpath) [static]
Definition at line 2135 of file readfile.c.
References newdataadr(), NULL, and bMotionPath::points.
Referenced by direct_link_object(), and direct_link_pose().
static void direct_link_movieclip (FileData * fd, MovieClip * clip) [static]
Definition at line 6176 of file readfile.c.
References MovieTracking::act_track, MovieClip::adt, MovieClip::anim, MovieClip::cache, MovieTracking::camera, direct_link_movieReconstruction(), direct_link_movieTracks(), ListBase::first, MovieTrackingCamera::intrinsics, link_list(), FileData::movieclipmap, newdataadr(), newmclipadr(), NULL, MovieTracking::objects, MovieTrackingStabilization::ok, MovieTrackingObject::reconstruction, MovieTracking::reconstruction, MovieTrackingStabilization::rot_track, MovieTrackingStabilization::scaleibuf, MovieTracking::stabilization, MovieTracking::stats, MovieClip::tracking, MovieClip::tracking_context, MovieTrackingObject::tracks, and MovieTracking::tracks.
Referenced by read_libblock().
static void direct_link_movieReconstruction (FileData * fd, MovieTrackingReconstruction * reconstruction) [static]
Definition at line 6157 of file readfile.c.
References MovieTrackingReconstruction::cameras, and newdataadr().
Referenced by direct_link_movieclip().
static void direct_link_movieTracks (FileData * fd, ListBase * tracksbase) [static]
Definition at line 6162 of file readfile.c.
References ListBase::first, link_list(), MovieTrackingTrack::markers, newdataadr(), and MovieTrackingTrack::next.
Referenced by direct_link_movieclip().
static void direct_link_nladata (FileData * fd, ListBase * list) [static]
Definition at line 2034 of file readfile.c.
References direct_link_nladata_strips(), ListBase::first, link_list(), NlaTrack::next, and NlaTrack::strips.
Referenced by direct_link_animdata().
static void direct_link_nladata_strips (FileData * fd, ListBase * list) [static]
Definition at line 2014 of file readfile.c.
References direct_link_fcurves(), direct_link_fmodifiers(), NlaStrip::fcurves, ListBase::first, link_list(), NlaStrip::modifiers, NlaStrip::next, and NlaStrip::strips.
Referenced by direct_link_nladata().
static void direct_link_nlastrips (FileData * fd, ListBase * strips) [static]
Definition at line 1771 of file readfile.c.
References ListBase::first, link_list(), bActionStrip::modifiers, and bActionStrip::next.
Referenced by direct_link_object().
static void direct_link_node_socket (FileData * fd, bNodeSocket * sock) [static]
Definition at line 2362 of file readfile.c.
References bNodeSocket::cache, bNodeSocket::default_value, bNodeSocket::link, newdataadr(), NULL, and bNodeSocket::storage.
Referenced by direct_link_nodetree().
static void direct_link_nodetree (FileData * fd, bNodeTree * ntree) [static]
Definition at line 2371 of file readfile.c.
References bNodeTree::adt, BSET, CMP_NODE_CURVE_RGB, CMP_NODE_CURVE_VEC, CMP_NODE_HUECORRECT, CMP_NODE_IMAGE, CMP_NODE_MOVIEDISTORTION, CMP_NODE_SPLITVIEWER, CMP_NODE_TIME, CMP_NODE_VIEWER, bNode::custom1, direct_link_animdata(), direct_link_curvemapping(), direct_link_node_socket(), ELEM3, ELEM4, bNodeTree::execdata, ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNodeTree::init, bNodeTree::inputs, bNode::inputs, bNode::lasty, link(), link_list(), bNodeTree::links, newdataadr(), newimaadr(), newmclipadr(), bNodeLink::next, bNodeSocket::next, bNode::next, NODE_DYNAMIC, NODE_DYNAMIC_LOADED, bNodeTree::nodes, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, bNodeTree::outputs, bNode::outputs, bNode::parent, bNode::preview, bNodeTree::progress, SH_NODE_CURVE_RGB, SH_NODE_CURVE_VEC, bNode::storage, TEX_NODE_CURVE_RGB, TEX_NODE_CURVE_TIME, TEX_NODE_IMAGE, bNodeLink::tonode, bNodeLink::tosock, bNodeTree::type, bNode::type, and bNode::typeinfo.
Referenced by direct_link_lamp(), direct_link_material(), direct_link_scene(), direct_link_texture(), direct_link_world(), and read_libblock().
static void direct_link_object (FileData * fd, Object * ob) [static]
Definition at line 4568 of file readfile.c.
References Object::actuators, Object::adt, Object::bb, BKE_add_effector_weights(), BLI_addhead(), BLI_addtail(), BLI_remlink(), SoftBody::bpoint, Object::bsoft, SoftBody::bspring, ObHook::cent, HookModifierData::cent, CLAMP(), Object::constraints, Object::controllers, copy_v3_v3(), Object::customdata_mask, WaveEff::damp, WaveModifierData::damp, bActuator::data, bController::data, bSensor::data, bProperty::data, Object::defbase, Object::derivedDeform, Object::derivedFinal, direct_link_animdata(), direct_link_constraints(), direct_link_modifiers(), direct_link_motionpath(), direct_link_nlastrips(), direct_link_partdeflect(), direct_link_particlesystems(), direct_link_pointcache_list(), direct_link_pose(), Object::disp, EFF_BUILD, EFF_PARTICLE, EFF_WAVE, SoftBody::effector_weights, eModifierType_Build, eModifierType_Hook, eModifierType_Wave, ObHook::falloff, HookModifierData::falloff, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, WaveEff::flag, WaveModifierData::flag, Object::flag, FileData::flags, Object::fluidsimSettings, ObHook::force, HookModifierData::force, Object::gpulamp, WaveEff::height, WaveModifierData::height, HookModifierData::indexar, ObHook::indexar, Object::init_state, SoftBody::keys, PartEff::keys, ListBase::last, BuildEff::len, BuildModifierData::length, WaveEff::lifetime, WaveModifierData::lifetime, link_glob_list(), link_list(), bController::links, bSensor::links, Object::mat, Object::matbits, MEM_callocN(), MEM_freeN(), FileData::memfile, Object::mode, modifier_new(), modifier_unique_name(), Object::modifiers, Object::mpath, WaveEff::narrow, WaveModifierData::narrow, newdataadr(), bActuator::next, bController::next, bSensor::next, bProperty::next, PartEff::next, next, NULL, OB_FROMGROUP, OB_MODE_EDIT, OB_MODE_PARTICLE_EDIT, HookModifierData::object, ObHook::parent, ObHook::parentinv, HookModifierData::parentinv, Object::particlesystem, Object::pc_ids, Object::pd, bProperty::poin, SoftBody::pointcache, Object::pose, Object::prop, SoftBody::ptcaches, BuildModifierData::randomize, ROT_MODE_MAX, ROT_MODE_MIN, Object::rotmode, SoftBody::scratch, Object::sculpt, BuildModifierData::seed, Object::sensors, BuildEff::sfra, Object::soft, WaveEff::speed, WaveModifierData::speed, BuildModifierData::start, WaveEff::startx, WaveModifierData::startx, WaveModifierData::starty, Object::state, bController::state_mask, SWITCH_INT, test_pointer_array(), WaveEff::timeoffs, WaveModifierData::timeoffs, HookModifierData::totindex, ObHook::totindex, SoftBody::totkey, PartEff::type, WaveEff::width, and WaveModifierData::width.
Referenced by read_libblock().
static PackedFile* direct_link_packedfile (FileData * fd, PackedFile * oldpf) [static]
Definition at line 1688 of file readfile.c.
References PackedFile::data, newdataadr(), and pf.
Referenced by direct_link_image(), direct_link_sound(), and direct_link_vfont().
static void direct_link_paint (FileData * fd, Paint ** paint) [static]
Definition at line 4925 of file readfile.c.
References newdataadr().
Referenced by direct_link_scene().
static void direct_link_partdeflect (PartDeflect * pd) [static]
Definition at line 3477 of file readfile.c.
References NULL, and PartDeflect::rng.
Referenced by direct_link_object(), and direct_link_particlesettings().
static void direct_link_particlesettings (FileData * fd, ParticleSettings * part) [static]
Definition at line 3482 of file readfile.c.
References BoidState::actions, ParticleSettings::adt, BKE_add_effector_weights(), ParticleSettings::boids, BoidState::conditions, direct_link_animdata(), direct_link_partdeflect(), ParticleSettings::dupliweights, ParticleSettings::effector_weights, ListBase::first, ParticleSettings::fluid, link_list(), MAX_MTEX, ParticleSettings::mtex, newdataadr(), BoidState::next, ParticleSettings::pd, ParticleSettings::pd2, BoidState::rules, state, and BoidSettings::states.
Referenced by read_libblock().
static void direct_link_particlesystems (FileData * fd, ListBase * particles) [static]
Definition at line 3553 of file readfile.c.
References ParticleData::boid, ParticleSystem::bvhtree, ParticleSystem::child, ParticleSystem::childcache, ParticleSystem::childcachebufs, ParticleSystem::clmd, ClothModifierData::clothObject, ClothModifierData::coll_parms, direct_link_pointcache_list(), ParticleSystem::edit, ClothSimSettings::effector_weights, ParticleSystem::effectors, ListBase::first, ParticleSystem::flag, ParticleSystem::fluid_springs, ParticleSystem::frand, ParticleSystem::free_edit, ParticleData::hair, ParticleSystem::hair_in_dm, ParticleSystem::hair_out_dm, ParticleData::keys, ListBase::last, link_list(), newdataadr(), ParticleSystem::next, NULL, ParticleSystem::particles, ParticleSystem::pathcache, ParticleSystem::pathcachebufs, ParticleSystem::pdd, ClothModifierData::point_cache, ParticleSystem::pointcache, ClothSimSettings::presets, PSYS_KEYED, ParticleSystem::ptcaches, ParticleSystem::renderdata, ClothModifierData::sim_parms, ParticleSystem::targets, ParticleData::totkey, ParticleSystem::totpart, and ParticleSystem::tree.
Referenced by direct_link_object().
static void direct_link_pointcache (FileData * fd, PointCache * cache) [static]
Definition at line 3305 of file readfile.c.
References BKE_ptcache_data_size(), BPHYS_TOT_DATA, PointCache::cached_frames, PTCacheExtra::data, PTCacheMem::data, PointCache::edit, PTCacheMem::extradata, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, PointCache::flag, FileData::flags, PointCache::free_edit, i, ListBase::last, link_list(), PointCache::mem_cache, newdataadr(), PTCacheExtra::next, PTCacheMem::next, NULL, PTCACHE_DISK_CACHE, PTCACHE_SIMULATION_VALID, PointCache::simframe, SWITCH_INT, and PTCacheMem::totpoint.
Referenced by direct_link_pointcache_list().
static void direct_link_pointcache_list (FileData * fd, ListBase * ptcaches, PointCache ** ocache, int force_disk) [static]
Definition at line 3346 of file readfile.c.
References direct_link_pointcache(), ListBase::first, PointCache::flag, ListBase::last, link_list(), newdataadr(), PointCache::next, NULL, PTCACHE_DISK_CACHE, and PointCache::step.
Referenced by direct_link_modifiers(), direct_link_object(), and direct_link_particlesystems().
static void direct_link_pose (FileData * fd, bPose * pose) [static]
Definition at line 4263 of file readfile.c.
References bPose::agroups, bPoseChannel::bone, bPose::chanbase, bPose::chanhash, bPoseChannel::child, CLAMP(), bPoseChannel::constraints, bPoseChannel::custom_tx, direct_link_constraints(), direct_link_motionpath(), FD_FLAGS_SWITCH_ENDIAN, ListBase::first, FileData::flags, IDP_DirectLinkProperty(), bPose::ikdata, bPose::ikparam, bPoseChannel::iktree, ListBase::last, link_list(), bPoseChannel::mpath, newdataadr(), bPoseChannel::next, NULL, bPoseChannel::parent, bPoseChannel::prop, ROT_MODE_MAX, ROT_MODE_MIN, bPoseChannel::rotmode, and bPoseChannel::siktree.
Referenced by direct_link_object().
static PreviewImage* direct_link_preview_image (FileData * fd, PreviewImage * old_prv) [static]
Definition at line 1701 of file readfile.c.
References i, newdataadr(), NUM_ICON_SIZES, and PreviewImage::rect.
Referenced by direct_link_image(), direct_link_lamp(), direct_link_material(), direct_link_texture(), and direct_link_world().
static void direct_link_region (FileData * fd, ARegion * ar, int spacetype) [static]
Definition at line 5674 of file readfile.c.
References Panel::activedata, RegionView3D::clipbb, RegionView3D::depths, ARegion::do_draw, ARegion::drawrct, ListBase::first, ARegion::handlers, ARegion::headerstr, ListBase::last, link_list(), RegionView3D::localvd, newdataadr(), Panel::next, NULL, ARegion::panels, Panel::paneltab, ARegion::regiondata, RegionView3D::render_engine, RegionView3D::ri, Panel::runtime_flag, RegionView3D::smooth_timer, RegionView3D::sms, SPACE_VIEW3D, ARegion::swap, ARegion::swinid, View2D::tab_cur, View2D::tab_num, View2D::tab_offset, ARegion::type, Panel::type, ARegion::uiblocks, and ARegion::v2d.
Referenced by direct_link_screen().
static void direct_link_scene (FileData * fd, Scene * sce) [static]
Definition at line 4931 of file readfile.c.
References Editing::act_seq, Scene::adt, StripProxy::anim, RenderData::avicodecdata, Scene::basact, Scene::base, QuicktimeCodecData::cdParms, Strip::color_balance, Strip::crop, Scene::customdata_mask_modal, Scene::dagisvalid, direct_link_animdata(), direct_link_keyingsets(), direct_link_nodetree(), direct_link_paint(), Strip::done, Scene::ed, Sequence::effectdata, FD_FLAGS_SWITCH_ENDIAN, RenderData::ffcodecdata, ListBase::first, Sequence::flag, FileData::flags, Scene::fps_info, SpeedControlVars::frameMap, Scene::id, IDP_DirectLinkProperty(), ToolSettings::imapaint, Scene::keyingsets, Scene::lay_updated, RenderData::layers, link_list(), link_recurs_seq(), AviCodecData::lpFormat, AviCodecData::lpParms, Scene::markers, Editing::metastack, newdataadr(), MetaStack::next, Scene::nodetree, NULL, Scene::obedit, MetaStack::oldbasep, ParticleEditSettings::paintcursor, ImagePaintSettings::paintcursor, MetaStack::parseq, ToolSettings::particle, Sequence::plugin, FFMpegCodecData::properties, Strip::proxy, RenderData::qtcodecdata, Scene::r, ToolSettings::sculpt, Sequence::seq1, Sequence::seq2, Sequence::seq3, SEQ_BEGIN, SEQ_EFFECT, SEQ_EFFECT_NOT_LOADED, SEQ_END, SEQ_HD_SOUND, SEQ_IMAGE, SEQ_MOVIE, SEQ_RAM_SOUND, SEQ_SPEED, SEQ_USE_COLOR_BALANCE, SEQ_USE_CROP, SEQ_USE_PROXY, SEQ_USE_TRANSFORM, Sequence::seqbase, Editing::seqbase, Editing::seqbasep, sound_create_scene(), Scene::stats, Sequence::strip, Strip::stripdata, Scene::theDag, Scene::toolsettings, Strip::transform, Scene::transform_spaces, Sequence::type, ID::us, ToolSettings::uvsculpt, ToolSettings::vpaint, and ToolSettings::wpaint.
Referenced by read_libblock().
static void direct_link_screen (FileData * fd, bScreen * sc) [static]
Definition at line 5740 of file readfile.c.
References ScrArea::actionzones, SpaceNla::ads, SpaceIpo::ads, View3D::afterdraw_transp, View3D::afterdraw_xray, View3D::afterdraw_xraytransp, bScreen::areabase, View3D::bgpicbase, BLI_addtail(), BLI_remlink(), SpaceTime::caches, bScreen::context, SpaceImage::cumap, TreeStore::data, direct_link_curvemapping(), direct_link_gpencil(), direct_link_region(), View3D::drawtype, bScreen::edgebase, SpaceFile::files, ListBase::first, View3D::flag, SpaceFile::folders_next, SpaceFile::folders_prev, SpaceIpo::ghostCurves, SpaceSeq::gpd, SpaceLogic::gpd, SpaceNode::gpd, SpaceImage::gpd, bScreen::handler, ScrArea::handlers, SpaceConsole::history, SpaceImage::iuser, BGpic::iuser, ListBase::last, SpaceFile::layout, ConsoleLine::len, ConsoleLine::len_alloc, ConsoleLine::line, link_list(), View3D::localvd, bScreen::mainwin, MEM_callocN(), MEM_freeN(), newdataadr(), ConsoleLine::next, BGpic::next, SpaceLink::next, ARegion::next, ScrArea::next, ScrEdge::next, NULL, OB_RENDER, OB_WIRE, Scopes::ok, ImageUser::ok, SpaceFile::op, SpaceFile::params, SpaceButs::path, View3D::properties_storage, SpaceLink::regionbase, ScrArea::regionbase, bScreen::regionbase, ImageUser::scene, SpaceImage::scopes, SCREEN_HANDLER_VERSE, SCREEN_MAXHANDLER, SpaceConsole::scrollback, SO_TREESTORE_CLEANUP, SPACE_BUTS, SPACE_CONSOLE, SPACE_FILE, SPACE_IMAGE, SPACE_INFO, SPACE_IPO, SPACE_LOGIC, SPACE_NLA, SPACE_NODE, SPACE_OUTLINER, SPACE_SEQ, SPACE_TIME, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, SpaceInfo::spacetype, ScrArea::spacetype, SpaceOops::storeflag, bScreen::subwinactive, bScreen::swap, SpaceButs::texuser, TreeStore::totelem, SpaceOops::treestore, ScrArea::type, TreeStore::usedelem, ScrArea::v1, ScrEdge::v1, ScrArea::v2, ScrEdge::v2, ScrArea::v3, V3D_INVALID_BACKBUF, ScrArea::v4, Scopes::vecscope, bScreen::vertbase, view3d_split_250(), Scopes::waveform_1, Scopes::waveform_2, and Scopes::waveform_3.
Referenced by read_libblock().
static void direct_link_script (FileData * UNUSEDfd, Script * script) [static]
Definition at line 1679 of file readfile.c.
References Script::id, SCRIPT_SET_NULL, and ID::us.
Referenced by read_libblock().
static void direct_link_sound (FileData * fd, bSound * sound) [static]
Definition at line 6085 of file readfile.c.
References bSound::cache, direct_link_packedfile(), bSound::flags, bSound::handle, bSound::newpackedfile, NULL, bSound::packedfile, bSound::playback_handle, SOUND_FLAGS_CACHING, and bSound::waveform.
Referenced by direct_link_speaker(), and read_libblock().
static void direct_link_speaker (FileData * fd, Speaker * spk) [static]
Definition at line 6072 of file readfile.c.
References Speaker::adt, direct_link_animdata(), direct_link_sound(), newdataadr(), and Speaker::sound.
Referenced by read_libblock().
static void direct_link_text (FileData * fd, Text * text) [static]
Definition at line 2929 of file readfile.c.
References Text::compiled, Text::curl, ListBase::first, Text::flags, TextLine::format, Text::id, TextLine::len, TextLine::line, Text::lines, link_list(), Text::markers, MEM_mallocN(), Text::name, newdataadr(), TextLine::next, NULL, reopen_text(), Text::sell, strlen(), TXT_INIT_UNDO, TXT_ISEXT, Text::undo_buf, Text::undo_len, Text::undo_pos, and ID::us.
Referenced by read_libblock().
static void direct_link_texture (FileData * fd, Tex * tex) [static]
Definition at line 3179 of file readfile.c.
References Tex::adt, PointDensity::coba, Tex::coba, EnvMap::cube, PluginTex::data, VoxelData::dataset, direct_link_animdata(), direct_link_curvemapping(), direct_link_nodetree(), direct_link_preview_image(), Tex::env, PointDensity::falloff_curve, PluginTex::handle, EnvMap::ima, PluginTex::instance_init, Tex::iuser, MEM_callocN(), newdataadr(), Tex::nodetree, NULL, ImageUser::ok, VoxelData::ok, EnvMap::ok, open_plugin_tex(), Tex::ot, Tex::pd, Tex::plugin, PointDensity::point_tree, Tex::preview, TEX_VOXELDATA, Tex::type, and Tex::vd.
Referenced by read_libblock().
static void direct_link_vfont (FileData * fd, VFont * vf) [static]
Definition at line 2908 of file readfile.c.
References VFont::data, direct_link_packedfile(), NULL, and VFont::packedfile.
Referenced by read_libblock().
static void direct_link_windowmanager (FileData * fd, wmWindowManager * wm) [static]
Definition at line 5120 of file readfile.c.
References wmWindowManager::addonconf, BKE_reports_init(), wmWindow::curswin, wmWindowManager::defaultconf, wmWindowManager::drags, wmWindow::drawdata, wmWindow::drawfail, wmWindow::drawmethod, wmWindow::eventstate, ListBase::first, wmWindow::gesture, wmWindow::ghostwin, wmWindow::handlers, wmWindowManager::id, wmWindowManager::initialized, wmWindowManager::jobs, wmWindowManager::keyconfigs, ListBase::last, link_list(), wmWindow::modalhandlers, wmWindow::next, NULL, wmWindowManager::op_undo_depth, wmWindowManager::operators, wmWindowManager::paintcursors, wmWindow::queue, wmWindowManager::queue, wmWindowManager::reports, RPT_STORE, wmWindow::subwindows, wmWindowManager::timers, wmWindow::tweak, ID::us, wmWindowManager::userconf, wmWindowManager::winactive, wmWindowManager::windows, and wmWindowManager::windrawable.
Referenced by read_libblock().
static void direct_link_world (FileData * fd, World * wrld) [static]
Definition at line 2874 of file readfile.c.
References World::adt, direct_link_animdata(), direct_link_nodetree(), direct_link_preview_image(), MAX_MTEX, World::mtex, newdataadr(), World::nodetree, and World::preview.
Referenced by read_libblock().
static void do_version_bone_head_tail_237 (Bone * bone) [static]
Definition at line 6540 of file readfile.c.
References add_v3_v3v3(), Bone::arm_head, Bone::arm_mat, Bone::arm_tail, Bone::childbase, copy_v3_v3(), ListBase::first, Bone::length, mul_v3_fl(), and Bone::next.
Referenced by do_versions().
static void do_version_bone_roll_256 (Bone * bone) [static]
Definition at line 7484 of file readfile.c.
References Bone::arm_mat, Bone::arm_roll, Bone::childbase, copy_m3_m4(), ListBase::first, mat3_to_vec_roll(), Bone::next, and NULL.
Referenced by do_versions().
static void do_version_constraints_radians_degrees_250 (ListBase * lb) [static]
Definition at line 7421 of file readfile.c.
References bRigidBodyJointConstraint::axX, bRigidBodyJointConstraint::axY, bRigidBodyJointConstraint::axZ, CONSTRAINT_TYPE_KINEMATIC, CONSTRAINT_TYPE_RIGIDBODYJOINT, CONSTRAINT_TYPE_ROTLIMIT, bConstraint::data, data, ListBase::first, M_PI, bConstraint::next, bKinematicConstraint::poleangle, bConstraint::type, bRotLimitConstraint::xmax, bRotLimitConstraint::xmin, bRotLimitConstraint::ymax, bRotLimitConstraint::ymin, bRotLimitConstraint::zmax, and bRotLimitConstraint::zmin.
Referenced by do_versions().
static void do_version_free_effect_245 (Effect * eff) [static]
Definition at line 7311 of file readfile.c.
References EFF_PARTICLE, PartEff::keys, MEM_freeN(), and Effect::type.
Referenced by do_version_free_effects_245().
static void do_version_free_effects_245 (ListBase * lb) [static]
Definition at line 7321 of file readfile.c.
References BLI_remlink(), do_version_free_effect_245(), and ListBase::first.
Referenced by do_versions().
static PartEff* do_version_give_parteff_245 (Object * ob) [static]
Definition at line 7300 of file readfile.c.
References EFF_PARTICLE, PartEff::next, NULL, and PartEff::type.
Referenced by do_versions(), and expand_object().
static void do_version_mdef_250 (Main * main) [static]
Definition at line 7397 of file readfile.c.
References MeshDeformModifierData::bindcagecos, MeshDeformModifierData::bindcos, eModifierType_MeshDeform, ListBase::first, Object::id, modifier_mdef_compact_influences(), Object::modifiers, ModifierData::next, ID::next, NULL, Main::object, and ModifierData::type.
Referenced by do_versions().
static void do_version_mtex_factor_2_50 (MTex ** mtex_array, short idtype) [static]
Definition at line 7333 of file readfile.c.
References MTex::alphafac, MTex::ambfac, MTex::blendfac, MTex::clumpfac, MTex::colemitfac, MTex::colfac, MTex::colreflfac, MTex::colspecfac, MTex::coltransfac, MTex::densfac, MTex::difffac, MTex::dispfac, MTex::emitfac, MTex::hardfac, ID_LA, ID_MA, ID_WO, MTex::ivelfac, MTex::kinkfac, LAMAP_COL, LAMAP_SHAD, MTex::lengthfac, MTex::lifefac, MAP_ALPHA, MAP_AMB, MAP_COL, MAP_COLMIR, MAP_COLSPEC, MAP_DENSITY, MAP_DISP, MAP_EMISSION_COL, MAP_EMIT, MAP_HAR, MAP_NORM, MAP_PA_CLUMP, MAP_PA_DENS, MAP_PA_IVEL, MAP_PA_KINK, MAP_PA_LENGTH, MAP_PA_LIFE, MAP_PA_ROUGH, MAP_PA_SIZE, MAP_PA_TIME, MAP_RAYMIRR, MAP_REF, MAP_REFLECTION, MAP_REFLECTION_COL, MAP_SCATTERING, MAP_SPEC, MAP_TRANSLU, MAP_TRANSMISSION_COL, MAP_WARP, MTex::maptoneg, MAX_MTEX, MTex::mirrfac, MTex::norfac, MTex::padensfac, MTex::raymirrfac, MTex::reflfac, MTex::roughfac, MTex::scatterfac, MTex::shadowfac, MTex::sizefac, MTex::specfac, MTex::timefac, MTex::translfac, MTex::varfac, MTex::warpfac, WOMAP_BLEND, WOMAP_HORIZ, WOMAP_ZENDOWN, WOMAP_ZENUP, MTex::zendownfac, and MTex::zenupfac.
Referenced by do_versions().
static void do_version_ntree_242_2 (bNodeTree * ntree) [static]
Definition at line 6728 of file readfile.c.
References CMP_NODE_IMAGE, CMP_NODE_SPLITVIEWER, CMP_NODE_VIEWER, ImageUser::cycl, NodeImageAnim::cyclic, ELEM3, ImageUser::fie_ima, ListBase::first, NodeImageAnim::frames, ImageUser::frames, MEM_callocN(), MEM_freeN(), bNode::next, bNodeTree::nodes, NodeImageAnim::nr, NTREE_COMPOSIT, ImageUser::offset, ImageUser::ok, NodeImageAnim::sfra, ImageUser::sfra, bNode::storage, bNode::type, and bNodeTree::type.
Referenced by do_versions().
static void do_version_ntree_tex_mapping_260 (void * UNUSEDdata, ID * UNUSEDid, bNodeTree * ntree) [static]
Definition at line 7539 of file readfile.c.
References ListBase::first, bNode::next, bNodeTree::nodes, PROJ_X, PROJ_Y, PROJ_Z, TexMapping::projx, TexMapping::projy, TexMapping::projz, SH_NODE_MAPPING, bNode::storage, and bNode::type.
Referenced by do_versions().
static void do_version_old_trackto_to_constraints (Object * ob) [static]
Definition at line 7450 of file readfile.c.
References add_ob_constraint(), CONSTRAINT_TYPE_TRACKTO, bConstraint::data, data, NULL, bTrackToConstraint::reserved1, bTrackToConstraint::reserved2, bTrackToConstraint::tar, Object::track, Object::trackflag, and Object::upflag.
Referenced by do_versions().
static void do_versions (FileData * fd, Library * lib, Main * main) [static]
Definition at line 7778 of file readfile.c.
References MCol::a, ParticleSettings::acc, bActionActuator::act, ACT_ACTION, ACT_ADD_OBJECT, ACT_CAMERA, ACT_CONST_LOCAL, ACT_CONST_TYPE_DIST, ACT_CONSTRAINT, ACT_DROT_LOCAL, ACT_EDIT_OBJECT, ACT_EDOB_ADD_OBJECT, ACT_EDOB_END_OBJECT, ACT_END_OBJECT, ACT_IPO, ACT_IPO_FROM_PROP, ACT_MESSAGE, ACT_OBJECT, ACT_SHAPEACTION, ACT_SND_3D_SOUND, ACT_SOUND, ACT_STEERING, ACT_TORQUE_LOCAL, bActionStrip::actend, AnimData::action, Main::action, bActionStrip::actstart, ACTSTRIP_USESTRIDE, Object::actuators, Lamp::adapt_thresh, Material::adapt_thresh_mir, Material::adapt_thresh_tra, Material::add, Brush::add_col, Object::adt, Tex::afmax, RecastData::agentheight, RecastData::agentmaxclimb, RecastData::agentmaxslope, RecastData::agentradius, BPoint::alfa, BezTriple::alfa, View2D::align, SpaceButs::align, UnifiedPaintSettings::alpha, Material::alpha, Brush::alpha, alphasort_version_246(), Material::amb, World::ambr, Material::ang, GameDome::angle, bObjectActuator::angularvelocity, FluidsimSettings::animRate, Image::animspeed, animviz_settings_init(), Material::aniso_gloss_mir, Object::anisotropicFriction, World::ao_adapt_thresh, World::ao_approx_error, World::ao_env_energy, World::ao_indirect_bounces, World::ao_samp_method, World::aobias, World::aocolor, World::aodist, World::aoenergy, World::aomix, World::aomode, World::aosamp, Lamp::area_size, Lamp::area_sizey, Lamp::area_sizez, bScreen::areabase, ARM_DEF_B_BONE_REST, ARM_DEF_VGROUP, ARM_DRAWXRAY, ARM_PATH_ACFRA, ARM_PATH_FNUMS, ARM_PATH_HEADS, ARM_PATH_KFNOS, ARM_PATH_KFRAS, Main::armature, MovieClip::aspx, Image::aspx, MovieClip::aspy, Image::aspy, Lamp::atm_distance_factor, Lamp::atm_extinction_factor, Lamp::atm_inscattering_factor, Lamp::atm_turbidity, bSound::attenuation, GameData::attrib, Scene::audio, FFMpegCodecData::audio_channels, FFMpegCodecData::audio_codec, FFMpegCodecData::audio_mixrate, AUDIO_SCRUB, FFMpegCodecData::audio_volume, ToolSettings::autokey_mode, SpaceNla::autosnap, SpaceIpo::autosnap, SpaceAction::autosnap, bPose::avs, Object::avs, bCameraActuator::axis, Material::b, Lamp::backscattered_light, RenderData::bake_filter, RenderData::bake_flag, RenderData::bake_mode, RenderData::bake_osa, Scene::base, ParticleSettings::bb_size, FCurve::bezt, Nurb::bezt, Tex::bfac, RenderData::bg_stamp, View3D::bgpicbase, BKE_area_region_free(), BKE_ptcache_add(), BKE_reportf_wrap(), BKE_spacetype_from_id(), BKE_tracking_new_object(), Sequence::blend_mode, Sequence::blend_opacity, BLI_addhead(), BLI_addtail(), BLI_countlist(), BLI_findindex(), BLI_freelinkN(), BLI_insertlinkbefore(), BLI_join_dirfile(), BLI_path_abs(), BLI_snprintf(), BLI_strncpy(), BLI_strnlen(), Key::block, RenderData::blurfac, ParticleSettings::boids, ToolSettings::bone_sketching, bone_version_238(), bone_version_239(), bArmature::bonebase, RenderData::border, Object::boundtype, Nurb::bp, Main::brush, ParticleEditSettings::brush, BRUSH_SPACE_ATTEN, ParticleEditSettings::brushtype, Lamp::buffers, MovieClipProxy::build_size_flag, MovieClipProxy::build_tc_flag, View3D::bundle_drawtype, View3D::bundle_size, BUTS_ANIM, BUTS_CONSTRAINT, BUTS_EDIT, BUTS_FPAINT, BUTS_GAME, BUTS_LAMP, BUTS_MAT, BUTS_RADIO, BUTS_RENDER, BUTS_SCRIPT, BUTS_TEX, BUTS_WORLD, SpaceTime::cache_display, calc_lat_fudu(), CAM_ORTHO, CAM_PANORAMA, CAM_SHOWPASSEPARTOUT, CAM_SHOWTITLESAFE, MovieTracking::camera, Scene::camera, Main::camera, DynamicPaintModifierData::canvas, RecastData::cellheight, RecastData::cellsize, bPose::chanbase, ParticleSettings::child_nbr, ToolSettings::clean_thresh, ParticleSettings::clength, CurveMapping::clipr, CurveMapping::cm, CMP_NODE_BLUR, CMP_NODE_COLORBALANCE, MVert::co, Tex::coba, Object::col, TFace::col, Object::collision_boundtype, DynamicPaintSurface::color_dry_threshold, RenderData::color_mgt_flag, Lamp::compressthresh, Sound3D::cone_inner_angle, Sound3D::cone_outer_angle, bPoseChannel::constinv, Object::constinv, constraint_get_typeinfo(), CONSTRAINT_IK_POS, CONSTRAINT_IK_ROT, CONSTRAINT_IK_STRETCH, CONSTRAINT_SPACE_LOCAL, CONSTRAINT_TYPE_ACTION, CONSTRAINT_TYPE_FOLLOWPATH, CONSTRAINT_TYPE_KINEMATIC, CONSTRAINT_TYPE_LOCLIKE, CONSTRAINT_TYPE_LOCLIMIT, CONSTRAINT_TYPE_MINMAX, CONSTRAINT_TYPE_OBJECTSOLVER, CONSTRAINT_TYPE_PYTHON, CONSTRAINT_TYPE_ROTLIKE, CONSTRAINT_TYPE_TRACKTO, bPoseChannel::constraints, Object::constraints, CONTEXT_EDITING, CONTEXT_LOGIC, CONTEXT_OBJECT, CONTEXT_SCENE, CONTEXT_SHADING, PixelFormat::convert(), copy_v3_v3(), ToolSettings::cornertype, ParticleSettings::courant_target, Brush::crease_pinch_factor, CU_2D, CU_PATH, CU_TYPE, CUMA_EXTEND_EXTRAPOLATE, View2D::cur, Text::curc, Lamp::curfalloff, Text::curl, Brush::curve, Main::curve, CURVE_PRESET_LINE, CURVE_PRESET_SMOOTH, curvemap_reset(), CURVEMAP_SLOPE_POSITIVE, curvemapping_add(), curvemapping_changed(), curvemapping_initialize(), bAction::curves, bNode::custom1, customdata_version_242(), customdata_version_243(), ImageUser::cycl, PartEff::damp, ParticleSettings::dampfac, bCameraActuator::damping, Object::damping, Material::darkness, ColorBand::data, KeyBlock::data, Object::data, bConstraint::data, data, bProperty::data, bSensor::data, bActuator::data, Lattice::def, MovieTrackingSettings::default_minimum_correlation, default_mtex(), MovieTrackingSettings::default_pattern_size, MovieTrackingSettings::default_pyramid_levels, MovieTrackingSettings::default_search_size, DEFAULT_SENSOR_HEIGHT, DEFAULT_SENSOR_WIDTH, MovieTrackingSettings::default_tracker, CurveModifierData::defaxis, Object::defbase, SoftBody::defgoal, defgroup_find_name(), defgroup_unique_name(), ArmatureModifierData::deformflag, bArmature::deformflag, ToolSettings::degr, VolumeSettings::density, VolumeSettings::density_scale, GameData::depth, VolumeSettings::depth_cutoff, RecastData::detailsampledist, RecastData::detailsamplemaxerror, StripProxy::dir, Strip::dir, ParticleSettings::disp, PartEff::disp, Tex::dist_amount, Material::dist_mir, bSound::distance, AudioData::distance_model, do_version_bone_head_tail_237(), do_version_bone_roll_256(), do_version_constraints_radians_degrees_250(), do_version_free_effects_245(), do_version_give_parteff_245(), do_version_mdef_250(), do_version_mtex_factor_2_50(), do_version_ntree_242_2(), do_version_ntree_tex_mapping_260(), do_version_old_trackto_to_constraints(), do_versions_gpencil_2_50(), do_versions_image_settings_2_60(), do_versions_mesh_mloopcol_swap_2_62_1(), do_versions_nodetree_convert_angle(), do_versions_nodetree_default_value(), do_versions_nodetree_dynamic_sockets(), do_versions_nodetree_image_default_alpha_output(), do_versions_nodetree_multi_file_output_format_2_62_1(), do_versions_nodetree_socket_use_flags_2_62(), do_versions_seq_unique_name_all_strips(), do_versions_windowmanager_2_50(), SmokeModifierData::domain, GameData::dome, AudioData::doppler_factor, ToolSettings::doublimit, Object::dquat, ParticleSettings::draw, ParticleSettings::draw_as, ParticleSettings::draw_col, ParticleSettings::draw_line, ParticleSettings::draw_step, Mesh::drawflag, View3D::drawtype, bObjectActuator::drot, Object::drotAngle, Object::drotAxis, Object::dscale, Object::dt, Object::dtx, Lattice::du, ParticleSettings::dup_ob, Object::dupend, Object::dupfacesca, Object::dupoff, Object::dupon, Object::dupsta, Lattice::dv, Lattice::dw, Scene::ed, RecastData::edgemaxerror, RecastData::edgemaxlen, SoftBody::effector_weights, ClothSimSettings::effector_weights, ParticleSettings::effector_weights, SoftBody::efra, ELEM, VolumeSettings::emission, VolumeSettings::emission_col, ParticleEditSettings::emitterdist, eModifierType_Armature, eModifierType_Cloth, eModifierType_Curve, eModifierType_DynamicPaint, eModifierType_Fluidsim, eModifierType_Lattice, eModifierType_Mirror, eModifierType_Multires, eModifierType_Ocean, eModifierType_ParticleSystem, eModifierType_Smoke, eModifierType_Softbody, eModifierType_Solidify, eModifierType_Subsurf, eModifierTypeType_OnlyDeform, Object::empty_drawsize, Object::empty_drawtype, bIpoActuator::end, bActionActuator::end, bActionStrip::end, PartEff::end, ParticleSettings::end, Tex::env, eSubsurfModifierFlag_ControlEdges, eSubsurfModifierFlag_DebugIncr, eSubsurfModifierFlag_Incremental, GameData::exitkey, World::exposure, VoxelData::extend, Tex::extend, ToolSettings::extr_offs, GameData::eyeseparation, PartDeflect::f_noise, fabsf, bSteeringActuator::facingaxis, Material::fadeto_mir, PointDensity::falloff_curve, PointDensity::falloff_speed_scale, Lamp::falloff_type, FCURVE_AUTO_HANDLES, RenderData::ffcodecdata, FFMPEG_MULTIPLEX_AUDIO, RenderData::fg_stamp, Tex::fie_ima, ImageUser::fie_ima, FILE_MAX, FILE_MAXDIR, FileData::fileflags, fill_vn_fl(), Tex::filtersize, RenderData::filtertype, ListBase::first, UnifiedPaintSettings::flag, bIpoActuator::flag, bActionActuator::flag, FCurve::flag, CurveMap::flag, SolidifyModifierData::flag, bNodeTree::flag, Brush::flag, FluidsimSettings::flag, PartDeflect::flag, PhysicsSettings::flag, Object::flag, GameData::flag, Nurb::flag, bSoundActuator::flag, bConstraintActuator::flag, bActionStrip::flag, ParticleEditSettings::flag, ParticleSettings::flag, PartEff::flag, ParticleSystem::flag, bLocateLikeConstraint::flag, ImageUser::flag, PointCache::flag, bConstraint::flag, MirrorModifierData::flag, Image::flag, bRotateLikeConstraint::flag, bMinMaxConstraint::flag, Camera::flag, bKinematicConstraint::flag, Lattice::flag, Curve::flag, bArmature::flag, bPose::flag, Sequence::flag, View3D::flag, Tex::flag, AudioData::flag, Mesh::flag, bObjectActuator::flag, ID::flag, View3D::flag2, bLocLimitConstraint::flag2, DynamicPaintSurface::flags, Text::flags, SmokeFlowSettings::flags, SmokeDomainSettings::flags, FFMpegCodecData::flags, SubsurfModifierData::flags, bSound::flags, Material::flareboost, Material::flaresize, SmokeModifierData::flow, FLT_MAX, Object::fluidsimSettings, FluidsimSettings::fmd, FO_BUILTIN_NAME, PartEff::force, PartDeflect::forcefield, bObjectActuator::forceloc, bObjectActuator::forcerot, bNodeTreeType::foreach_nodetree, Object::formfactor, RenderData::framapto, RenderData::frame_step, RenderData::framelen, bIpoActuator::frameProp, bActionActuator::frameProp, Tex::frames, ImageUser::frames, GameData::framing, bSensor::freq, GameData::freqplay, Material::fresnel_mir, Material::fresnel_mir_i, Material::fresnel_tra, Material::fresnel_tra_i, ParticleSettings::from, RenderData::frs_sec, RenderData::frs_sec_base, FluidsimModifierData::fss, Lattice::fu, Lattice::fv, Lattice::fw, Material::g, G, G_DEBUG, G_FILE_ENABLE_ALL_FRAMES, G_FILE_GAME_MAT, G_FILE_GAME_MAT_GLSL, G_FILE_GLSL_NO_EXTRA_TEX, G_FILE_GLSL_NO_NODES, G_FILE_GLSL_NO_RAMPS, G_FILE_GLSL_NO_SHADERS, G_FILE_GLSL_NO_SHADOWS, G_FILE_IGNORE_DEPRECATION_WARNINGS, G_FILE_SHOW_DEBUG_PROPS, G_FILE_SHOW_FRAMERATE, G_FILE_SHOW_PHYSICS, GAME_DISPLAY_LISTS, GAME_ENABLE_ALL_FRAMES, GAME_GLSL_NO_EXTRA_TEX, GAME_GLSL_NO_NODES, GAME_GLSL_NO_RAMPS, GAME_GLSL_NO_SHADERS, GAME_GLSL_NO_SHADOWS, GAME_IGNORE_DEPRECATION_WARNINGS, GAME_MAT_GLSL, GAME_MAT_MULTITEX, GAME_MAT_TEXFACE, GAME_PLAYER_FULLSCREEN, GAME_SHOW_DEBUG_PROPS, GAME_SHOW_FRAMERATE, GAME_SHOW_PHYSICS, Object::gameflag, RenderData::gauss, Image::gen_type, Image::gen_x, Image::gen_y, get_ob_property(), Tex::gfac, bAnimVizSettings::ghost_ac, bAnimVizSettings::ghost_bc, bAnimVizSettings::ghost_ef, bAnimVizSettings::ghost_sf, bAnimVizSettings::ghost_step, bAnimVizSettings::ghost_type, GHOST_TYPE_NONE, bArmature::ghostef, bArmature::ghostep, bArmature::ghostsf, bArmature::ghostsize, bArmature::ghosttype, EffectorWeights::global_gravity, Material::gloss_mir, Material::gloss_tra, Scene::gm, GPROP_TIME, SoftBody::grav, ClothSimSettings::gravity, PhysicsSettings::gravity, GameData::gravity, View3D::gridflag, View3D::gridlines, View3D::gridsubdiv, PartEff::group, Main::group, BezTriple::h1, BezTriple::h2, ParticleSettings::hair_step, HD_AUTO, HD_AUTO_ANIM, bConstraint::headtail, Brush::height, Histogram::height, Lamp::horizon_brightness, World::horr, i, Text::id, MovieClip::id, bAction::id, Brush::id, ParticleSettings::id, Group::id, Curve::id, bNodeTree::id, Key::id, Lattice::id, bArmature::id, Camera::id, Lamp::id, World::id, Image::id, VFont::id, bSound::id, bScreen::id, Mesh::id, Object::id, Material::id, Scene::id, Tex::id, ID_LA, ID_MA, ID_OB, ID_WO, KeyingSet::idname, idproperties_fix_group_lengths(), if(), Tex::ima, IMA_DO_PREMUL, IMA_FIELDS, IMA_OLD_PREMUL, IMA_SRC_FILE, IMA_SRC_MOVIE, IMA_SRC_VIEWER, IMA_STD_FIELD, IMA_TYPE_COMPOSITE, IMA_TYPE_IMAGE, IMA_TYPE_R_RESULT, Tex::imaflag, Main::image, RenderData::images, ToolSettings::imapaint, IMB_PROXY_25, IMB_TC_FREE_RUN, IMB_TC_INTERPOLATED_REC_DATE_FREE_RUN, IMB_TC_RECORD_RUN, IMB_TC_RECORD_RUN_NO_GAPS, Object::inertia, DynamicPaintSurface::influence_scale, INFO_RPT_OP, SoftBody::inpush, SoftBody::inspring, SoftBody::interval, bSensor::invert, bObjectSolverConstraint::invmat, FluidsimSettings::ipo, Main::ipo, IS_EQ, IS_EQF, is_zero_v3(), is_zero_v4(), BGpic::iuser, Tex::iuser, ToolSettings::jointrilimit, Lamp::k, View2D::keepofs, View2D::keeptot, View2D::keepzoom, Curve::key, Lattice::key, Mesh::key, Main::key, bKeyboardSensor::key, Scene::keyingsets, SoftBody::keys, ParticleSettings::kink_amp_clump, LA_AREA, LA_FALLOFF_INVLINEAR, LA_FALLOFF_SLIDERS, LA_QUAD, LA_SAMP_CONSTANT, LA_SAMP_HALTON, Main::lamp, Main::latt, Scene::lay, Scene::layact, Group::layer, bArmature::layer, RenderData::layers, SceneRenderLayer::layflag, TextLine::len, len_v3(), length(), Camera::lens, GameData::levelHeight, SubsurfModifierData::levels, SpaceText::lheight, ID::lib, LIB_NEEDLINK, FileData::libmap, Main::library, PartEff::lifetime, ParticleSettings::lifetime, NodeColorBalance::lift, bPoseChannel::limitmax, bPoseChannel::limitmin, TextLine::line, bObjectActuator::linearvelocity, Text::lines, bEditObjectActuator::linVelocity, bActionConstraint::local, bEditObjectActuator::localflag, LOCLIKE_TIP, MultiresModifierData::lvl, Object::m_contactProcessingThreshold, M_PI, MA_APPROX_OCCLUSION, MA_HALO, MA_NORMAP_TANG, MA_RAMP_ADD, MA_RAYMIR_FADETOSKY, MA_RAYTRANSP, MA_SHADBUF, MA_TANGENT_STR, MA_TRACEBLE, MA_TRANSP, MA_TYPE_HALO, MA_TYPE_VOLUME, MA_TYPE_WIRE, MA_VOL_PRECACHESHADING, MA_VOL_SHADE_SHADED, MA_VOL_STEP_RANDOMIZED, MA_WIRE, MA_ZTRANSP, AudioData::main, SpaceSeq::mainb, SpaceButs::mainb, make_edges(), map_223_keybd_code_to_224_keybd_code(), MAP_ALPHA, MAP_COL, MAP_REF, MAP_SPEC, MTex::mapto, Object::margin, Object::mass, PartEff::mat, Object::mat, Main::mat, SolidifyModifierData::mat_ofs_rim, Object::matbits, Material::material_type, GameData::matmode, MAX2, Sound3D::max_distance, Sound3D::max_gain, bSound::max_gain, MAX_MTEX, GameData::maxlogicstep, World::maxlogicstep, GameData::maxphystep, World::maxphystep, View2D::maxzoom, Main::mball, RenderData::mblur_samples, Mesh::mcol, ME_DRAWCREASES, ME_DRAWEDGES, ME_DRAWFACES, ME_OPT_EDGES, ME_SMESH, ME_SUBSURF, Mesh::medge, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), Main::mesh, mesh_calc_normals_tessface(), mesh_strip_loose_faces(), Mesh::mface, Tex::mg_gain, Tex::mg_H, Tex::mg_lacunarity, Tex::mg_octaves, Tex::mg_offset, View2D::min, MIN2, Sound3D::min_gain, bSound::min_gain, MovieTrackingTrack::minimum_correlation, MINMAX_STICKY, View2D::minzoom, Material::mirr, AudioData::mixrate, MOD_DPAINT_USE_DRYING, MOD_MIR_AXIS_X, MOD_MIR_AXIS_Y, MOD_MIR_AXIS_Z, MOD_SMOKE_FLOW_INITVELOCITY, MOD_SMOKE_TYPE_DOMAIN, MOD_SMOKE_TYPE_FLOW, MOD_SOLIDIFY_RIM_MATERIAL, Object::mode, GameData::mode, GameDome::mode, SpaceAction::mode, Lamp::mode, World::mode, ModifierData::mode, bRaySensor::mode, bCollisionSensor::mode, TFace::mode, Material::mode, RenderData::mode, SubsurfModifierData::modifier, modifier_new(), modifier_unique_name(), Object::modifiers, modifiers_findByType(), modifierType_getInfo(), MOTIONPATH_BAKE_HEADS, MOTIONPATH_TYPE_ACFRA, MOTIONPATH_VIEW_FNUMS, MOTIONPATH_VIEW_KFNOS, MOTIONPATH_VIEW_KFRAS, Main::movieclip, VolumeSettings::ms_diff, VolumeSettings::ms_intensity, VolumeSettings::ms_spread, Brush::mtex, World::mtex, Lamp::mtex, Material::mtex, MTEX_3TAP_BUMP, MTEX_BUMP_OBJECTSPACE, MTEX_NSPACE_TANGENT, mul_v3_fl(), multires_load_old(), multires_load_old_250(), Mesh::mvert, Tex::nabla, KeyingSet::name, bActionActuator::name, Main::name, StripElem::name, ModifierData::name, bDeformGroup::name, ID::name, Image::name, KeyBlock::name, VFont::name, bIpoActuator::name, newlibadr(), newlibadr_us(), bSound::newpackedfile, KeyingSet::next, DynamicPaintSurface::next, TextLine::next, MovieTrackingObject::next, MovieTrackingTrack::next, FCurve::next, ARegion::next, bNode::next, Base::next, bActionStrip::next, ParticleSystem::next, bDeformGroup::next, BGpic::next, Nurb::next, SceneRenderLayer::next, KeyBlock::next, ModifierData::next, Bone::next, bPoseChannel::next, bConstraint::next, bProperty::next, bSensor::next, bActuator::next, ScrArea::next, SpaceLink::next, ID::next, NODE_GROUP, bNodeTree::nodes, World::nodetree, Lamp::nodetree, Tex::nodetree, Material::nodetree, Main::nodetree, Scene::nodetree, bNodeTree::nodetype, nodeUniqueName(), ImagePaintSettings::normal_angle, ToolSettings::normalsize, MTex::normapspace, PartEff::normfac, ParticleSettings::normfac, Tex::ns_outscale, NTREE_DO_VERSIONS_GROUP_EXPOSE, NTREE_SHADER, NTREE_UPDATE, ntree_version_241(), ntree_version_242(), ntree_version_245(), ntreeGetType(), NULL, Curve::nurb, bAddObjectActuator::ob, bEditObjectActuator::ob, OB_ACTOR, OB_ANISOTROPIC_FRICTION, OB_ARMATURE, OB_ARROWS, OB_BOUNDS, OB_CAMERA, OB_CHILD, OB_COLLISION, OB_COLLISION_RESPONSE, OB_CURVE, OB_DO_FH, OB_DRAWXRAY, OB_DUPLIPARTS, OB_DUPLIVERTS, OB_DYNAMIC, OB_FLUIDSIM_ACTIVE, OB_FLUIDSIM_OVERRIDE_TIME, OB_FLUIDSIM_PARTICLE, OB_FONT, OB_GHOST, OB_LATTICE, OB_MATERIAL, OB_MESH, Brush::ob_mode, OB_MODE_ALL_PAINT, OB_MODE_POSE, OB_PLAINAXES, OB_POSX, OB_POSY, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, OB_RIGID_BODY, OB_ROT_FH, OB_SB_ENABLE, OB_SB_POSTDEF, OB_SOFT_BODY, OB_SOLID, OB_TEXTURE, PartEff::obfac, ParticleSettings::obfac, CurveModifierData::object, LatticeModifierData::object, Base::object, ArmatureModifierData::object, Main::object, MovieTrackingSettings::object_distance, MovieTracking::objects, GameData::occlusionRes, World::occlusionRes, OceanModifierData::oceancache, RenderData::ocres, Tex::offset, ImageUser::offset, oldnewmap_insert(), ParticleSettings::omat, PartEff::omat, bKinematicConstraint::orientweight, Camera::ortho_scale, RenderData::osa, bActuator::otype, bConstraint::ownspace, bSound::packedfile, PAF_BSPLINE, PAF_DIED, PAF_EDISTR, PAF_FACE, PAF_SHOWE, PAF_STATIC, PAF_TRAND, PAF_UNBORN, PAF_VECT, Material::param, PARCURVE, Object::parent, PAROBJECT, PARSKEL, ParticleSystem::part, PART_DIED, PART_DRAW_AXIS, PART_DRAW_COL_MAT, PART_DRAW_DOT, PART_DRAW_EMITTER, PART_DRAW_GR, PART_DRAW_HALO, PART_DRAW_LINE, PART_DRAW_MAT_COL, PART_DRAW_OB, PART_DRAW_PATH, PART_DRAW_REND, PART_DRAW_ROTATE_OB, PART_DRAW_VEL_LENGTH, PART_EDISTR, PART_FLUID, PART_FROM_FACE, PART_HAIR, PART_HAIR_BSPLINE, PART_HAIR_REGROW, PART_ROT_VEL, PART_ROTATIONS, PART_TIME_AUTOSF, PART_TRAND, PART_UNBORN, ToolSettings::particle, Main::particle, Object::particlesystem, Object::partype, Camera::passepartalpha, SceneRenderLayer::passflag, bAnimVizSettings::path_ac, bAnimVizSettings::path_bakeflag, bAnimVizSettings::path_bc, bAnimVizSettings::path_ef, ParticleSettings::path_end, bAnimVizSettings::path_sf, bAnimVizSettings::path_step, bAnimVizSettings::path_type, bAnimVizSettings::path_viewflag, bArmature::pathac, bArmature::pathbc, bArmature::pathef, bArmature::pathflag, bArmature::pathsf, bArmature::pathsize, Tex::pd, Object::pd, PE_BRUSH_CUT, PE_BRUSH_NONE, PE_DEFLECT_EMITTER, PE_KEEP_LENGTHS, PE_LOCK_FIRST, PE_TOT_BRUSH, NodeBlurData::percentx, NodeBlurData::percenty, PFIELD_DO_LOCATION, PFIELD_PLANAR, PFIELD_SHAPE_PLANE, PFIELD_SHAPE_SURFACE, PFIELD_SURFACE, PFIELD_WIND, PHYS_GLOBAL_GRAVITY, Scene::physics_settings, SoftBody::physics_speed, GameData::physicsEngine, World::physicsEngine, GameData::physubstep, World::physubstep, PIL_check_seconds_timer(), Sequence::pitch, BoidSettings::pitch, bSound::pitch, bSoundActuator::pitch, MovieTrackingCamera::pixel_aspect, Brush::plane_trim, GameData::playerflag, Nurb::pntsu, Lattice::pntsu, Nurb::pntsv, Lattice::pntsv, Lattice::pntsw, ClothModifierData::point_cache, ParticleSystem::pointcache, SoftBody::pointcache, Object::pose, POSE_RECALC, Material::pr_lamp, VolumeSettings::precache_resolution, CurveMapping::preset, MultiresLevel::prev, Image::preview, Object::prop, MovieClip::proxy, Strip::proxy, ParticleSystemModifierData::psys, PSYS_CURRENT, PSYS_ENABLED, psys_new_settings(), PSYS_RECALC_REDO, PSYS_VG_DENSITY, PSYS_VG_LENGTH, PSYS_VG_VEL, PTCACHE_BAKED, PTCACHE_DISK_CACHE, ClothModifierData::ptcaches, ParticleSystem::ptcaches, SoftBody::ptcaches, bSensor::pulse, MovieTrackingTrack::pyramid_levels, bKeyboardSensor::qual, bKeyboardSensor::qual2, MovieClipProxy::quality, StripProxy::quality, Object::quat, CBData::r, Material::r, Scene::r, R_BAKE_CLEAR, R_COLOR_MANAGEMENT, R_ENVMAP, R_FILTER_GAUSS, R_GAMMA, R_GAUSS, R_PANORAMA, R_PASSEPARTOUT, R_SSS, R_THREADS, BPoint::radius, BezTriple::radius, Nurb::radius_interp, DynamicPaintSurface::radius_scale, Material::ramp_col, Material::ramp_spec, Material::rampfac_col, Material::rampfac_spec, PartEff::randfac, ParticleSettings::randfac, PartEff::randlife, ParticleSettings::randlife, World::range, bRadarSensor::range, Brush::rate, Material::ray_depth, Material::ray_depth_tra, Lamp::ray_samp, Lamp::ray_samp_method, Lamp::ray_sampy, Lamp::ray_sampz, Object::rdamping, ParticleSystem::recalc, Object::recalc, GameData::recastData, bScreen::redraws_flag, Sound3D::reference_distance, Key::refkey, VolumeSettings::reflection, VolumeSettings::reflection_col, Material::refrac, SpaceLink::regionbase, ScrArea::regionbase, RecastData::regionmergesize, RecastData::regionminsize, ARegion::regiontype, FileData::relabase, ParticleSettings::ren_as, ParticleSettings::ren_child_nbr, ParticleSettings::ren_step, SubsurfModifierData::renderLevels, MultiresModifierData::renderlvl, bActionStrip::repeat, FileData::reports, GameDome::res, GameDome::resbuf, bTrackToConstraint::reserved1, bTrackToConstraint::reserved2, Nurb::resolu, OceanModifierData::resolution, Nurb::resolv, Main::revision, Tex::rfac, RGN_TYPE_PREVIEW, RGN_TYPE_WINDOW, ToolSettings::rings, Material::rms, Sound3D::rolloff_factor, bKinematicConstraint::rootbone, ROT_MODE_EUL, bPoseChannel::rotAxis, Object::rotAxis, ROTLIKE_X, ROTLIKE_Y, ROTLIKE_Z, Object::rotmode, ParticleSettings::rotmode, Material::roughness, SpaceInfo::rpt_mask, RPT_WARNING, SACTCONT_DOPESHEET, SACTSNAP_FRAME, Material::samp_gloss_mir, Material::samp_gloss_tra, SpaceImage::sample_line_hist, Sequence::sat, Tex::saturation, Object::scaflag, MovieTrackingObject::scale, bActionStrip::scale, UnitSettings::scale_length, VolumeSettings::scattering, SCE_LAY_SKY, SCE_LAY_SOLID, SCE_PASS_COMBINED, SCE_PASS_NORMAL, SCE_PASS_VECTOR, SCE_PASS_Z, SCE_SELECT_PATH, SCE_SELECT_VERTEX, RenderData::scemode, Main::scene, scene_add_render_layer(), SpaceClip::scopes, SpaceImage::scopes, scopes_new(), Main::screen, Main::script, View2D::scroll, Brush::sculpt_tool, SCULPT_TOOL_ROTATE, MultiresModifierData::sculptlvl, ImagePaintSettings::seam_bleed, PartDeflect::seed, PartEff::seed, ParticleSystem::seed, ToolSettings::segments, ToolSettings::select_thresh, ParticleEditSettings::selectmode, ToolSettings::selectmode, SENS_ALWAYS, SENS_COLLISION, SENS_KEYBOARD, SENS_RADAR, SENS_RAY, Camera::sensor_x, Camera::sensor_y, Object::sensors, SEQ_BEGIN, SEQ_DRAW_IMG_IMBUF, SEQ_END, SEQ_HD_SOUND, SEQ_IMAGE, SEQ_MAKE_PREMUL, SEQ_MOVIE, SEQ_USE_PROXY_CUSTOM_DIR, SEQ_USE_PROXY_CUSTOM_FILE, SEQ_VIEW_SEQUENCE, Editing::seqbase, Editing::seqbasep, SEQP_BEGIN, sequencer_init_preview_region(), MovieTracking::settings, Tex::sfra, ImageUser::sfra, SoftBody::sfra, Material::shad_alpha, Material::shade_flag, VolumeSettings::shade_type, VolumeSettings::shadeflag, PartDeflect::shape, SoftBody::shearstiff, ClothModifierData::sim_parms, RenderData::simplify_aosss, RenderData::simplify_particles, ParticleSettings::simplify_rate, ParticleSettings::simplify_refsize, RenderData::simplify_shadowsamples, RenderData::simplify_subsurf, ParticleSettings::simplify_transition, ParticleSettings::simplify_viewport, UnifiedPaintSettings::size, Object::size, Brush::size, ParticleBrushData::size, SK_RETARGET_ROLL_VIEW, ToolSettings::skgen_angle_limit, ToolSettings::skgen_correlation_limit, SKGEN_FILTER_EXTERNAL, SKGEN_FILTER_INTERNAL, SKGEN_FILTER_SMART, SKGEN_HARMONIC, ToolSettings::skgen_length_limit, ToolSettings::skgen_length_ratio, ToolSettings::skgen_options, ToolSettings::skgen_postpro, ToolSettings::skgen_postpro_passes, ToolSettings::skgen_resolution, ToolSettings::skgen_retarget_angle_weight, ToolSettings::skgen_retarget_distance_weight, ToolSettings::skgen_retarget_length_weight, ToolSettings::skgen_retarget_roll, SKGEN_SMOOTH, SKGEN_SUB_ANGLE, SKGEN_SUB_CORRELATION, SKGEN_SUB_LENGTH, ToolSettings::skgen_subdivisions, ToolSettings::skgen_symmetry_limit, ToolSettings::skgen_threshold_external, ToolSettings::skgen_threshold_internal, Lamp::sky_exposure, Lamp::skyblendfac, Lamp::skyblendtype, KeyBlock::slidermax, KeyBlock::slidermin, Curve::smallcaps_scale, Brush::smooth_stroke_factor, Brush::smooth_stroke_radius, Mesh::smoothresh, Object::soft, Object::softflag, Sequence::sound, bSoundActuator::sound, Main::sound, bSoundActuator::sound3D, SOUND_FLAGS_3D, sound_new_file(), Image::source, bConstraintTarget::space, SPACE_ACTION, SPACE_BUTS, SPACE_CLIP, SPACE_IMAGE, SPACE_INFO, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_TEXT, SPACE_TIME, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, Brush::spacing, Material::specr, AudioData::speed_of_sound, PartEff::speedtex, Lamp::spread, srgb_to_linearrgb_v3_v3(), Material::sss_back, Material::sss_col, Material::sss_colfac, Material::sss_error, Material::sss_front, Material::sss_ior, Material::sss_radius, Material::sss_scale, Material::sss_texfac, bIpoActuator::sta, bActionActuator::sta, PartEff::sta, ParticleSettings::sta, bActionStrip::start, PartEff::staticstep, ParticleBrushData::step, ToolSettings::step, VolumeSettings::stepsize, VolumeSettings::stepsize_type, STEREO_ANAGLYPH, STEREO_DOME, STEREO_ENABLED, STEREO_NOSTEREO, GameData::stereoflag, GameData::stereomode, bMinMaxConstraint::sticky, bNode::storage, str, Material::strand_end, Material::strand_min, Material::strand_sta, LatticeModifierData::strength, ParticleBrushData::strength, Sequence::strip, Strip::stripdata, strlen(), PartEff::stype, Brush::sub_col, SubsurfModifierData::subdivType, Material::subsize, bPythonConstraint::subtarget, bConstraintTarget::subtarget, Main::subversionfile, Lamp::sun_brightness, Lamp::sun_effect_type, Lamp::sun_intensity, Lamp::sun_size, DynamicPaintCanvasSettings::surfaces, SpaceText::tabnumber, bConstraintTarget::tar, bPythonConstraint::tar, bFollowPathConstraint::tar, bPythonConstraint::targets, bPythonConstraint::tarnum, bConstraint::tarspace, MTex::tex, Main::tex, TEX_ANIM5_, TEX_ANIMCYCLIC_, TEX_CHECKER_EVEN, TEX_CHECKER_ODD, TEX_CLIP, TEX_EXTEND, TEX_FIELDS_, TEX_IMAGE, TEX_NODE_OUTPUT, TEX_REPEAT, TEX_STD_FIELD_, TEX_STUCCI, MTex::texflag, Main::text, Brush::texture_overlay_alpha, TF_DYNAMIC, TF_INVISIBLE, Mesh::tface, RenderData::threads, GameData::ticrate, World::ticrate, GameDome::tilt, bAddObjectActuator::time, bEditObjectActuator::time, TIME_ALL_3D_WIN, TIME_ALL_ANIM_WIN, TIME_CACHE_CLOTH, TIME_CACHE_DISPLAY, TIME_CACHE_DYNAMICPAINT, TIME_CACHE_PARTICLES, TIME_CACHE_SMOKE, TIME_CACHE_SOFTBODY, ParticleSettings::time_flag, SmokeDomainSettings::time_scale, Scene::toolsettings, bMessageActuator::toPropName, View2D::tot, ColorBand::tot, ParticleEditSettings::totaddkey, Object::totcol, KeyBlock::totelem, Mesh::totface, PartEff::totkey, SoftBody::totkey, MultiresModifierData::totlvl, PartEff::totpart, ParticleSettings::totpart, ParticleSystem::totpart, ParticleEditSettings::totrekey, FCurve::totvert, Mesh::totvert, MovieClipScopes::track_preview_height, TRACKER_KLT, Object::trackflag, MovieClip::tracking, MovieTracking::tracks, Object::transflag, VolumeSettings::transmission_col, ToolSettings::turn, View3D::twtype, Material::tx_falloff, txt_extended_ascii_as_utf8(), TXT_ISEXT, bConstraintTypeInfo::type, bActionActuator::type, SmokeModifierData::type, Nurb::type, bNode::type, bConstraintActuator::type, FluidsimSettings::type, ParticleSettings::type, Lamp::type, Image::type, Tex::type, ModifierTypeInfo::type, ModifierData::type, Camera::type, Sequence::type, Object::type, bConstraint::type, bProperty::type, bSensor::type, bEditObjectActuator::type, bIpoActuator::type, bActuator::type, ToolSettings::unified_paint_settings, Scene::unit, unit_axis_angle(), unit_m4(), unit_qt(), UnifiedPaintSettings::unprojected_radius, Brush::unprojected_radius, ToolSettings::unwrapper, bNodeTree::update, Object::upflag, ID::us, Tex::use_nodes, TFace::uv, UV_SELECT_VERTEX, ToolSettings::uv_selectmode, ToolSettings::uvcalc_cubesize, UVCALC_FILLHOLES, ToolSettings::uvcalc_flag, ToolSettings::uvcalc_mapalign, ToolSettings::uvcalc_mapdir, ToolSettings::uvcalc_radius, ARegion::v2d, V2D_ALIGN_NO_NEG_X, V2D_ALIGN_NO_NEG_Y, V2D_KEEPASPECT, V2D_KEEPTOT_BOUNDS, V2D_LIMITZOOM, V2D_LOCKOFS_X, V2D_LOCKZOOM_X, V2D_LOCKZOOM_Y, V2D_SCROLL_RIGHT, V3D_MANIP_TRANSLATE, V3D_RENDER_OVERRIDE, V3D_RENDER_SHADOW, V3D_SELECT_OUTLINE, V3D_SHOW_FLOOR, V3D_SHOW_RECONSTRUCTION, V3D_SHOW_X, V3D_SHOW_Y, V3D_SHOW_Z, V3D_ZBUF_SELECT, vcol_to_fcol(), Tex::vd, BezTriple::vec, BPoint::vec, ClothSimSettings::vel_damping, SmokeFlowSettings::vel_multi, ClothSimSettings::velocity_smooth, Main::versionfile, PartEff::vertgroup, SoftBody::vertgroup, PartEff::vertgroup_v, ToolSettings::vertices, MultiresLevel::verts, Mesh::verts, RecastData::vertsperpoly, Main::vfont, ParticleSystem::vgroup, ToolSettings::vgroup_weight, SpaceSeq::view, EnvMap::viewscale, FluidsimSettings::viscosityExponent, FluidsimSettings::viscosityValue, Tex::vn_mexp, Tex::vn_w1, Material::vol, AudioData::volume, Sequence::volume, bSoundActuator::volume, bSound::volume, SmokeDomainSettings::vorticity, GameDome::warptext, bKinematicConstraint::weight, where_is_armature(), MTex::which_output, ScrArea::winy, WO_AMB_OCC, WO_AOADDSUB, WO_AODIST, WO_AOMUL, WO_AOPLAIN, WO_AOSAMP_CONSTANT, WO_AOSAMP_HAMMERSLEY, WO_AOSUB, WO_DBVT_CULLING, WO_INDIRECT_LIGHT, WOPHY_BULLET, Main::world, rctf::xmax, rctf::xmin, RenderData::xparts, GameData::xplay, Tex::xrepeat, RenderData::xsch, rctf::ymax, rctf::ymin, RenderData::yparts, GameData::yplay, Tex::yrepeat, RenderData::ysch, and World::zenr.
Referenced by blo_read_file_internal(), and read_libraries().
static void do_versions_gpencil_2_50 (Main * main, bScreen * screen) [static]
Definition at line 7255 of file readfile.c.
References bScreen::areabase, ListBase::first, SpaceNode::gpd, SpaceImage::gpd, SpaceSeq::gpd, Main::gpencil, SpaceLink::next, ScrArea::next, NULL, SPACE_IMAGE, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, and versions_gpencil_add_main().
Referenced by do_versions().
void do_versions_image_settings_2_60 (Scene * sce)
Definition at line 7601 of file readfile.c.
References ImageFormatData::cineon_flag, ImageFormatData::compress, ImageFormatData::depth, ImageFormatData::exr_codec, ImageFormatData::flag, RenderData::im_format, ImageFormatData::imtype, ImageFormatData::jp2_flag, ImageFormatData::planes, ImageFormatData::quality, Scene::r, R_CINEON_LOG, R_IMF_CHAN_DEPTH_12, R_IMF_CHAN_DEPTH_16, R_IMF_CHAN_DEPTH_32, R_IMF_CHAN_DEPTH_8, R_IMF_CINEON_FLAG_LOG, R_IMF_FLAG_PREVIEW_JPG, R_IMF_FLAG_ZBUF, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_DPX, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_TIFF, R_IMF_JP2_FLAG_CINE_48, R_IMF_JP2_FLAG_CINE_PRESET, R_IMF_JP2_FLAG_YCC, R_JPEG2K_12BIT, R_JPEG2K_16BIT, R_JPEG2K_CINE_48FPS, R_JPEG2K_CINE_PRESET, R_JPEG2K_YCC, R_OPENEXR_HALF, R_OPENEXR_ZBUF, R_PREVIEW_JPG, and R_TIFF_16BIT.
Referenced by do_versions().
static void do_versions_mesh_mloopcol_swap_2_62_1 (Mesh * me) [static]
Definition at line 7759 of file readfile.c.
References MLoopCol::b, CD_MLOOPCOL, CustomDataLayer::data, i, CustomData::layers, Mesh::ldata, MLoopCol::r, SWAP, CustomData::totlayer, Mesh::totloop, and CustomDataLayer::type.
Referenced by do_versions().
static void do_versions_nodetree_convert_angle (bNodeTree * ntree) [static]
Definition at line 7555 of file readfile.c.
References NodeDBlurData::angle, NodeGlare::angle_ofs, CMP_NODE_CHROMA_MATTE, CMP_NODE_DBLUR, CMP_NODE_DEFOCUS, CMP_NODE_GLARE, CMP_NODE_ROTATE, bNodeSocket::default_value, DEG2RADF, ListBase::first, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, TexMapping::rot, NodeDefocus::rotation, SH_NODE_MAPPING, NodeDBlurData::spin, bNode::storage, NodeChroma::t1, NodeChroma::t2, and bNode::type.
Referenced by do_versions().
static void do_versions_nodetree_default_value (bNodeTree * ntree) [static]
Definition at line 2205 of file readfile.c.
References do_versions_socket_default_value(), ListBase::first, bNodeTree::inputs, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, bNode::outputs, and bNodeTree::outputs.
Referenced by do_versions(), and lib_nodetree_init_types_cb().
static void do_versions_nodetree_dynamic_sockets (bNodeTree * ntree) [static]
Definition at line 7496 of file readfile.c.
References ListBase::first, bNodeSocket::flag, bNodeTree::inputs, bNodeSocket::next, bNodeTree::outputs, and SOCK_DYNAMIC.
Referenced by do_versions().
static void do_versions_nodetree_image_default_alpha_output (bNodeTree * ntree) [static]
Definition at line 7526 of file readfile.c.
References CMP_NODE_IMAGE, CMP_NODE_R_LAYERS, bNodeSocket::default_value, ELEM, ListBase::first, bNode::next, bNodeTree::nodes, bNode::outputs, and bNode::type.
Referenced by do_versions().
static void do_versions_nodetree_multi_file_output_format_2_62_1 (Scene * sce, bNodeTree * ntree) [static]
Definition at line 7687 of file readfile.c.
References NodeImageMultiFile::base_path, BLI_findlink(), BLI_strncpy(), CMP_NODE_OUTPUT_FILE, CMP_NODE_OUTPUT_MULTI_FILE__DEPRECATED, ELEM, ListBase::first, bNode::flag, NodeImageMultiFile::format, RenderData::im_format, NodeImageFile::im_format, ImageFormatData::imtype, bNode::inputs, bNodeSocket::link, MEM_callocN(), MEM_freeN(), bNodeSocket::name, NodeImageFile::name, bNodeSocket::next, bNode::next, NODE_PREVIEW, nodeRemoveSocket(), bNodeTree::nodes, ntreeCompositOutputFileAddSocket(), Scene::r, R_IMF_IMTYPE_IRIZ, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, bNodeSocket::storage, bNode::storage, bNodeLink::tosock, bNode::type, and NodeImageMultiFileSocket::use_node_format.
Referenced by do_versions().
static void do_versions_nodetree_socket_use_flags_2_62 (bNodeTree * ntree) [static]
Definition at line 7664 of file readfile.c.
References ListBase::first, bNodeSocket::flag, bNodeLink::fromsock, bNodeTree::inputs, bNode::inputs, link(), bNodeTree::links, bNodeSocket::next, bNode::next, bNodeLink::next, bNodeTree::nodes, bNode::outputs, bNodeTree::outputs, SOCK_IN_USE, and bNodeLink::tosock.
Referenced by do_versions().
static void do_versions_seq_unique_name_all_strips (Scene * sce, ListBase * seqbasep) [static]
Definition at line 7468 of file readfile.c.
References Scene::ed, ListBase::first, Sequence::next, Sequence::seqbase, Editing::seqbase, and seqbase_unique_name_recursive().
Referenced by do_versions().
static void do_versions_socket_default_value (bNodeSocket * sock) [static]
Definition at line 2174 of file readfile.c.
References copy_v3_v3(), copy_v4_v4(), bNodeSocket::default_value, bNodeSocketValueVector::max, bNodeSocketValueFloat::max, MEM_callocN(), bNodeSocketValueVector::min, bNodeSocketValueFloat::min, PROP_NONE, SOCK_FLOAT, SOCK_RGBA, SOCK_VECTOR, bNodeSocketValueVector::subtype, bNodeSocketValueFloat::subtype, bNodeSocket::type, bNodeSocketValueRGBA::value, bNodeSocketValueVector::value, and bNodeSocketValueFloat::value.
Referenced by do_versions_nodetree_default_value().
static void do_versions_windowmanager_2_50 (bScreen * screen) [static]
Definition at line 7199 of file readfile.c.
References area_add_header_region(), area_add_window_regions(), bScreen::areabase, ScrArea::butspacetype, ListBase::first, ScrArea::headertype, SpaceLink::next, ScrArea::next, ScrArea::regionbase, SpaceLink::regionbase, SPACE_EMPTY, SPACE_IMASEL, SPACE_SOUND, ScrArea::spacedata, ScrArea::spacetype, and SpaceLink::spacetype.
Referenced by do_versions().
static void expand_action (FileData * fd, Main * mainvar, bAction * act) [static]
Definition at line 13727 of file readfile.c.
References bAction::chanbase, bActionChannel::constraintChannels, bAction::curves, expand_constraint_channels(), expand_doit(), expand_fcurves(), ListBase::first, bActionChannel::ipo, and bActionChannel::next.
Referenced by expand_main().
static void expand_animdata (FileData * fd, Main * mainvar, AnimData * adt) [static]
Definition at line 13774 of file readfile.c.
References AnimData::action, AnimData::drivers, expand_animdata_nlastrips(), expand_doit(), expand_fcurves(), ListBase::first, NlaTrack::next, AnimData::nla_tracks, NlaTrack::strips, and AnimData::tmpact.
Referenced by expand_armature(), expand_camera(), expand_curve(), expand_key(), expand_lamp(), expand_lattice(), expand_material(), expand_mball(), expand_mesh(), expand_movieclip(), expand_nodetree(), expand_object(), expand_particlesettings(), expand_scene(), expand_speaker(), expand_texture(), and expand_world().
static void expand_animdata_nlastrips (FileData * fd, Main * mainvar, ListBase * list) [static]
Definition at line 13755 of file readfile.c.
References NlaStrip::act, expand_doit(), expand_fcurves(), expand_fmodifiers(), NlaStrip::fcurves, ListBase::first, NlaStrip::modifiers, NlaStrip::next, and NlaStrip::strips.
Referenced by expand_animdata().
static void expand_armature (FileData * fd, Main * mainvar, bArmature * arm) [static]
Definition at line 14058 of file readfile.c.
References bArmature::adt, bArmature::bonebase, expand_animdata(), expand_bones(), ListBase::first, and Bone::next.
Referenced by expand_main().
static void expand_bones (FileData * fd, Main * mainvar, Bone * bone) [static]
Definition at line 14035 of file readfile.c.
References Bone::childbase, ListBase::first, and Bone::next.
Referenced by expand_armature().
static void expand_brush (FileData * fd, Main * mainvar, Brush * brush) [static]
Definition at line 13855 of file readfile.c.
References Brush::clone, expand_doit(), BrushClone::image, Brush::mtex, and MTex::tex.
Referenced by expand_main().
static void expand_camera (FileData * fd, Main * mainvar, Camera * ca) [static]
Definition at line 14294 of file readfile.c.
References Camera::adt, expand_animdata(), and expand_doit().
Referenced by expand_main().
static void expand_constraint_cb (bConstraint * UNUSEDcon, ID ** idpoin, void * userdata) [static]
Definition at line 14011 of file readfile.c.
References expand_doit(), tConstraintExpandData::fd, and tConstraintExpandData::mainvar.
Referenced by expand_constraints().
static void expand_constraint_channels (FileData * fd, Main * mainvar, ListBase * chanbase) [static]
Definition at line 13676 of file readfile.c.
References expand_doit(), ListBase::first, bConstraintChannel::ipo, and bConstraintChannel::next.
Referenced by expand_action(), and expand_object().
static void expand_constraints (FileData * fd, Main * mainvar, ListBase * lb) [static]
Definition at line 14017 of file readfile.c.
References expand_constraint_cb(), expand_doit(), tConstraintExpandData::fd, ListBase::first, id_loop_constraints(), tConstraintExpandData::mainvar, and bConstraint::next.
Referenced by expand_object(), and expand_pose().
static void expand_curve (FileData * fd, Main * mainvar, Curve * cu) [static]
Definition at line 13947 of file readfile.c.
References Curve::adt, Curve::bevobj, expand_animdata(), expand_doit(), Curve::key, Curve::mat, Curve::taperobj, Curve::textoncurve, Curve::totcol, Curve::vfont, Curve::vfontb, Curve::vfontbi, and Curve::vfonti.
Referenced by expand_main().
static void expand_doit (FileData * fd, Main * mainvar, void * old) [static]
Definition at line 13601 of file readfile.c.
References bheadsort::bhead, blo_find_main(), change_idid_adr_fd(), BHead::code, Main::curlib, find_bhead(), find_previous_lib(), ID::flag, ID_ID, is_yet_read(), LIB_INDIRECT, LIB_PRE_EXISTING, LIB_READ, LIB_TESTIND, FileData::libmap, FileData::mainlist, MEM_freeN(), Library::name, NULL, BHead::old, oldnewmap_insert(), Library::parent, read_libblock(), read_struct(), and FileData::relabase.
Referenced by expand_action(), expand_animdata(), expand_animdata_nlastrips(), expand_brush(), expand_camera(), expand_constraint_cb(), expand_constraint_channels(), expand_constraints(), expand_curve(), expand_fcurves(), expand_fmodifiers(), expand_group(), expand_ipo(), expand_key(), expand_keyingsets(), expand_lamp(), expand_lattice(), expand_material(), expand_mball(), expand_mesh(), expand_nodetree(), expand_object(), expand_object_expandModifiers(), expand_particlesettings(), expand_pose(), expand_scene(), expand_sound(), expand_speaker(), expand_texture(), and expand_world().
static void expand_fcurves (FileData * fd, Main * mainvar, ListBase * list) [static]
Definition at line 13702 of file readfile.c.
References FCurve::driver, DRIVER_TARGETS_LOOPER, DRIVER_TARGETS_LOOPER_END, expand_doit(), expand_fmodifiers(), ListBase::first, FCurve::modifiers, FCurve::next, DriverVar::next, and ChannelDriver::variables.
Referenced by expand_action(), expand_animdata(), and expand_animdata_nlastrips().
static void expand_fmodifiers (FileData * fd, Main * mainvar, ListBase * list) [static]
Definition at line 13684 of file readfile.c.
References FModifier::data, data, expand_doit(), ListBase::first, FMODIFIER_TYPE_PYTHON, FModifier::next, FMod_Python::script, and FModifier::type.
Referenced by expand_animdata_nlastrips(), and expand_fcurves().
static void expand_group (FileData * fd, Main * mainvar, Group * group) [static]
Definition at line 13810 of file readfile.c.
References expand_doit(), ListBase::first, Group::gobject, GroupObject::next, and GroupObject::ob.
Referenced by expand_main().
static void expand_ipo (FileData * fd, Main * mainvar, Ipo * ipo) [static]
Definition at line 13666 of file readfile.c.
References Ipo::curve, IpoCurve::driver, expand_doit(), ListBase::first, IpoCurve::next, and IpoDriver::ob.
Referenced by expand_main().
static void expand_key (FileData * fd, Main * mainvar, Key * key) [static]
Definition at line 13819 of file readfile.c.
References Key::adt, expand_animdata(), and expand_doit().
Referenced by expand_main().
static void expand_keyingsets (FileData * fd, Main * mainvar, ListBase * list) [static]
Definition at line 13742 of file readfile.c.
References expand_doit(), ListBase::first, KS_Path::id, KeyingSet::next, KS_Path::next, and KeyingSet::paths.
Referenced by expand_scene().
static void expand_lamp (FileData * fd, Main * mainvar, Lamp * la) [static]
Definition at line 13884 of file readfile.c.
References Lamp::adt, expand_animdata(), expand_doit(), expand_nodetree(), MAX_MTEX, Lamp::mtex, Lamp::nodetree, MTex::object, and MTex::tex.
Referenced by expand_main().
static void expand_lattice (FileData * fd, Main * mainvar, Lattice * lt) [static]
Definition at line 13904 of file readfile.c.
References Lattice::adt, expand_animdata(), expand_doit(), and Lattice::key.
Referenced by expand_main().
static void expand_main (FileData * fd, Main * mainvar) [static]
Definition at line 14321 of file readfile.c.
References expand_action(), expand_armature(), expand_brush(), expand_camera(), expand_curve(), expand_group(), expand_ipo(), expand_key(), expand_lamp(), expand_lattice(), expand_material(), expand_mball(), expand_mesh(), expand_movieclip(), expand_nodetree(), expand_object(), expand_particlesettings(), expand_scene(), expand_sound(), expand_speaker(), expand_texture(), expand_world(), ListBase::first, ID::flag, GS, ID_AC, ID_AR, ID_BR, ID_CA, ID_CU, ID_GR, ID_IP, ID_KE, ID_LA, ID_LT, ID_MA, ID_MB, ID_MC, ID_ME, ID_NT, ID_OB, ID_PA, ID_SCE, ID_SO, ID_SPK, ID_TE, ID_WO, LIB_TEST, MAX_LIBARRAY, ID::name, NULL, and set_listbasepointers().
Referenced by library_append_end(), and read_libraries().
static void expand_material (FileData * fd, Main * mainvar, Material * ma) [static]
Definition at line 13861 of file readfile.c.
References Material::adt, expand_animdata(), expand_doit(), expand_nodetree(), Material::group, MAX_MTEX, Material::mtex, Material::nodetree, MTex::object, and MTex::tex.
Referenced by expand_main().
static void expand_mball (FileData * fd, Main * mainvar, MetaBall * mb) [static]
Definition at line 13935 of file readfile.c.
References MetaBall::adt, expand_animdata(), expand_doit(), MetaBall::mat, and MetaBall::totcol.
Referenced by expand_main().
static void expand_mesh (FileData * fd, Main * mainvar, Mesh * me) [static]
Definition at line 13969 of file readfile.c.
References Mesh::adt, CD_MTFACE, CustomDataLayer::data, expand_animdata(), expand_doit(), Mesh::fdata, i, Mesh::key, CustomData::layers, Mesh::mat, Mesh::texcomesh, Mesh::tface, Mesh::totcol, Mesh::totface, CustomData::totlayer, MTFace::tpage, TFace::tpage, and CustomDataLayer::type.
Referenced by expand_main().
static void expand_movieclip (FileData * fd, Main * mainvar, MovieClip * clip) [static]
Definition at line 14315 of file readfile.c.
References MovieClip::adt, and expand_animdata().
Referenced by expand_main().
static void expand_nodetree (FileData * fd, Main * mainvar, bNodeTree * ntree) [static]
Definition at line 13827 of file readfile.c.
References bNodeTree::adt, CMP_NODE_R_LAYERS, expand_animdata(), expand_doit(), ListBase::first, bNodeTree::gpd, bNode::id, bNode::next, bNodeTree::nodes, and bNode::type.
Referenced by expand_lamp(), expand_main(), expand_material(), expand_scene(), expand_texture(), and expand_world().
static void expand_object (FileData * fd, Main * mainvar, Object * ob) [static]
Definition at line 14081 of file readfile.c.
References bActionActuator::act, bActionStrip::act, ACT_2DFILTER, ACT_ACTION, ACT_ADD_OBJECT, ACT_ARMATURE, ACT_CAMERA, ACT_EDIT_OBJECT, ACT_MESSAGE, ACT_OBJECT, ACT_PARENT, ACT_PROPERTY, ACT_SCENE, ACT_SHAPEACTION, ACT_SOUND, ACT_STEERING, Object::actuators, Object::adt, bSceneActuator::camera, Object::constraints, CONT_PYTHON, Object::controllers, bActuator::data, bController::data, bSensor::data, data, Object::data, do_version_give_parteff_245(), Object::dup_group, expand_animdata(), expand_constraint_channels(), expand_constraints(), expand_doit(), expand_object_expandModifiers(), expand_pose(), ListBase::first, bMessageSensor::fromObject, Object::gpd, PartEff::group, bActionStrip::ipo, bTouchSensor::ma, Object::mat, bEditObjectActuator::me, Object::modifiers, modifiers_foreachIDLink(), bSteeringActuator::navmesh, bActuator::next, bController::next, bSensor::next, ParticleSystem::next, bActionStrip::next, bParentActuator::ob, bPropertyActuator::ob, bAddObjectActuator::ob, bEditObjectActuator::ob, bCameraActuator::ob, bActionStrip::object, ParticleSystem::part, Object::particlesystem, Object::pd, Object::pose, Object::poselib, Object::proxy, Object::proxy_group, bObjectActuator::reference, bSceneActuator::scene, SENS_MESSAGE, SENS_TOUCH, Object::sensors, bSoundActuator::sound, bSteeringActuator::target, bArmatureActuator::target, PartDeflect::tex, bTwoDFilterActuator::text, bPythonCont::text, bMessageActuator::toObject, Object::totcol, bActuator::type, bController::type, and bSensor::type.
Referenced by expand_main().
static void expand_object_expandModifiers (void * userData, Object * UNUSEDob, ID ** idpoin) [static]
Definition at line 14070 of file readfile.c.
References data, and expand_doit().
Referenced by expand_object().
static void expand_particlesettings (FileData * fd, Main * mainvar, ParticleSettings * part) [static]
Definition at line 13790 of file readfile.c.
References ParticleSettings::adt, ParticleSettings::bb_ob, ParticleSettings::dup_group, ParticleSettings::dup_ob, expand_animdata(), expand_doit(), MAX_MTEX, ParticleSettings::mtex, MTex::object, and MTex::tex.
Referenced by expand_main().
static void expand_pose (FileData * fd, Main * mainvar, bPose * pose) [static]
Definition at line 14045 of file readfile.c.
References bPose::chanbase, bPoseChannel::constraints, bPoseChannel::custom, expand_constraints(), expand_doit(), ListBase::first, and bPoseChannel::next.
Referenced by expand_object().
static void expand_scene (FileData * fd, Main * mainvar, Scene * sce) [static]
Definition at line 14236 of file readfile.c.
References Scene::adt, Scene::base, TimeMarker::camera, Scene::camera, Scene::clip, GameData::dome, Scene::ed, expand_animdata(), expand_doit(), expand_keyingsets(), expand_nodetree(), ListBase::first, Scene::gm, Scene::gpd, Scene::keyingsets, RenderData::layers, SceneRenderLayer::light_override, Scene::markers, SceneRenderLayer::mat_override, TimeMarker::next, SceneRenderLayer::next, Base::next, Scene::nodetree, Base::object, Scene::r, Sequence::scene, Sequence::scene_camera, SEQ_BEGIN, SEQ_END, Scene::set, Sequence::sound, GameDome::warptext, and Scene::world.
Referenced by expand_main().
static void expand_sound (FileData * fd, Main * mainvar, bSound * snd) [static]
Definition at line 14310 of file readfile.c.
References expand_doit(), and bSound::ipo.
Referenced by expand_main().
static void expand_speaker (FileData * fd, Main * mainvar, Speaker * spk) [static]
Definition at line 14302 of file readfile.c.
References Speaker::adt, expand_animdata(), expand_doit(), and Speaker::sound.
Referenced by expand_main().
static void expand_texture (FileData * fd, Main * mainvar, Tex * tex) [static]
Definition at line 13843 of file readfile.c.
References Tex::adt, expand_animdata(), expand_doit(), expand_nodetree(), Tex::ima, and Tex::nodetree.
Referenced by expand_main().
static void expand_world (FileData * fd, Main * mainvar, World * wrld) [static]
Definition at line 13914 of file readfile.c.
References World::adt, expand_animdata(), expand_doit(), expand_nodetree(), MAX_MTEX, World::mtex, World::nodetree, MTex::object, and MTex::tex.
Referenced by expand_main().
static int fd_read_from_file (FileData * filedata, void * buffer, unsigned int size) [static]
Definition at line 859 of file readfile.c.
References FileData::filedes, and FileData::seek.
Referenced by blo_read_blendafterruntime().
static int fd_read_from_memfile (FileData * filedata, void * buffer, unsigned int size) [static]
Definition at line 898 of file readfile.c.
References MemFileChunk::buf, MemFile::chunks, ListBase::first, FileData::memfile, MemFileChunk::next, NULL, FileData::seek, and MemFileChunk::size.
Referenced by blo_openblendermemfile().
static int fd_read_from_memory (FileData * filedata, void * buffer, unsigned int size) [static]
Definition at line 887 of file readfile.c.
References FileData::buffer, FileData::buffersize, MIN2, and FileData::seek.
Referenced by blo_openblendermemory().
static int fd_read_gzip_from_file (FileData * filedata, void * buffer, unsigned int size) [static]
Definition at line 873 of file readfile.c.
References FileData::gzfiledes, and FileData::seek.
Referenced by blo_openblenderfile().
static FileData* filedata_new (void) [static]
Definition at line 957 of file readfile.c.
References FileData::datamap, DNA_sdna_from_data(), DNAlen, DNAstr, FileData::filedes, FileData::globmap, FileData::gzfiledes, FileData::libmap, MEM_callocN(), FileData::memsdna, NULL, and oldnewmap_new().
Referenced by blo_openblenderfile(), blo_openblendermemfile(), blo_openblendermemory(), and blo_read_blendafterruntime().
static BHead* find_bhead (FileData * fd, void * old) [static]
Definition at line 13561 of file readfile.c.
References bheadsort::bhead, FileData::bheadmap, blo_firstbhead(), blo_nextbhead(), NULL, BHead::old, bheadsort::old, sort_bhead_old_map(), FileData::tot_bheadmap, and verg_bheadsort().
Referenced by expand_doit().
static BHead* find_previous_lib (FileData * fd, BHead * bhead) [static]
Definition at line 13548 of file readfile.c.
References bheadsort::bhead, blo_prevbhead(), BHead::code, ID_LI, FileData::memfile, and NULL.
Referenced by expand_doit().
static void fix_relpaths_library (const char * basepath, Main * main) [static]
Definition at line 6022 of file readfile.c.
References BLI_path_rel(), BLI_strncpy(), Library::filepath, ListBase::first, Library::id, Main::library, Library::name, ID::next, and NULL.
Referenced by blo_read_file_internal(), and library_append_end().
static BHeadN* get_bhead (FileData * fd) [static]
Definition at line 638 of file readfile.c.
References bh4_from_bh8(), bh8_from_bh4(), BHeadN::bhead, BLI_addtail(), BHead8::code, BHead4::code, DATA, ENDB, FileData::eof, FD_FLAGS_FILE_POINTSIZE_IS_4, FD_FLAGS_POINTSIZE_DIFFERS, FD_FLAGS_SWITCH_ENDIAN, FileData::flags, BHead::len, FileData::listbase, MEM_freeN(), MEM_mallocN(), BHeadN::next, NULL, BHeadN::prev, FileData::read, switch_endian_bh4(), and switch_endian_bh8().
Referenced by blo_firstbhead(), and blo_nextbhead().
static void give_base_to_groups (Main * mainvar, Scene * scene) [static]
Definition at line 14491 of file readfile.c.
References add_only_object(), Scene::basact, copy_v3_v3(), Scene::cursor, Object::dup_group, ListBase::first, Object::flag, Base::flag, ID::flag, Main::group, Object::id, Group::id, Scene::lay, Object::lay, LIB_INDIRECT, LIB_PRE_EXISTING, Object::loc, ID::name, ID::next, OB_DUPLIGROUP, OB_EMPTY, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, Base::object, Object::recalc, rename_id(), scene_add_base(), SELECT, Object::transflag, and Object::type.
Referenced by library_append_end().
static void give_base_to_objects (Main * mainvar, Scene * sce, Library * lib, const short idcode, const short is_link) [static]
Definition at line 14429 of file readfile.c.
References Scene::base, BLI_addtail(), FALSE, ListBase::first, Base::flag, Object::flag, ID::flag, Object::id, ID_GR, Object::lay, Base::lay, ID::lib, LIB_EXTERN, LIB_INDIRECT, LIB_PRE_EXISTING, MEM_callocN(), ID::next, OB_FROMGROUP, Base::object, Main::object, object_in_any_scene(), and ID::us.
Referenced by library_append_end().
static void IDP_DirectLinkArray (IDProperty * prop, int switch_endian, FileData * fd) [static]
Definition at line 1537 of file readfile.c.
References IDProperty::data, i, IDP_DirectLinkProperty(), IDP_DOUBLE, IDP_GROUP, IDProperty::len, newdataadr(), IDPropertyData::pointer, IDProperty::subtype, SWITCH_INT, SWITCH_LONGINT, test_pointer_array(), and IDProperty::totallen.
Referenced by IDP_DirectLinkProperty().
static void IDP_DirectLinkGroup (IDProperty * prop, int switch_endian, FileData * fd) [static]
Definition at line 1576 of file readfile.c.
References IDProperty::data, ListBase::first, IDPropertyData::group, IDP_DirectLinkProperty(), link_list(), and IDProperty::next.
Referenced by IDP_DirectLinkProperty().
static void IDP_DirectLinkIDPArray (IDProperty * prop, int switch_endian, FileData * fd) [static]
Definition at line 1514 of file readfile.c.
References IDProperty::data, i, IDP_DirectLinkProperty(), if(), IDProperty::len, newdataadr(), NULL, IDPropertyData::pointer, and IDProperty::totallen.
Referenced by IDP_DirectLinkProperty().
static void IDP_DirectLinkProperty (IDProperty * prop, int switch_endian, FileData * fd) [static]
Definition at line 1589 of file readfile.c.
References IDProperty::data, IDP_ARRAY, IDP_DirectLinkArray(), IDP_DirectLinkGroup(), IDP_DirectLinkIDPArray(), IDP_DirectLinkString(), IDP_DOUBLE, IDP_GROUP, IDP_IDPARRAY, IDP_STRING, SWITCH_INT, SWITCH_LONGINT, IDProperty::type, IDPropertyData::val, and IDPropertyData::val2.
Referenced by direct_link_bones(), direct_link_constraints(), direct_link_fmodifiers(), direct_link_keymapitem(), direct_link_pose(), direct_link_scene(), IDP_DirectLinkArray(), IDP_DirectLinkGroup(), IDP_DirectLinkIDPArray(), and read_libblock().
static void IDP_DirectLinkString (IDProperty * prop, FileData * fd) [static]
Definition at line 1569 of file readfile.c.
References IDProperty::data, IDProperty::len, newdataadr(), IDPropertyData::pointer, and IDProperty::totallen.
Referenced by IDP_DirectLinkProperty().
static void IDP_LibLinkProperty (IDProperty * UNUSEDprop, int UNUSEDswitch_endian, FileData * UNUSEDfd) [static]
Definition at line 1626 of file readfile.c.
static void IDP_LibLinkProperty (IDProperty * prop, int switch_endian, FileData * fd) [static]
Referenced by lib_link_image(), lib_link_material(), lib_link_mesh(), lib_link_object(), and lib_link_scene().
static void idproperties_fix_group_lengths (ListBase idlist) [static]
Definition at line 6813 of file readfile.c.
References ListBase::first, idproperties_fix_groups_lengths_recurse(), ID::next, and ID::properties.
Referenced by do_versions().
static void idproperties_fix_groups_lengths_recurse (IDProperty * prop) [static]
Definition at line 6798 of file readfile.c.
References IDProperty::data, ListBase::first, IDPropertyData::group, i, IDP_GROUP, IDProperty::len, IDProperty::next, and IDProperty::type.
Referenced by idproperties_fix_group_lengths().
static ID* is_yet_read (FileData * fd, Main * mainvar, BHead * bhead) [static]
Definition at line 13594 of file readfile.c.
References bhead_id_name(), BLI_findstring(), GS, and which_libbase().
Referenced by append_named_part(), and expand_doit().
static void lib_link_action (FileData * fd, Main * main) [static]
Definition at line 1934 of file readfile.c.
References Main::action, bAction::chanbase, bActionChannel::constraintChannels, bAction::curves, ListBase::first, ID::flag, bAction::id, bActionChannel::ipo, ID::lib, lib_link_constraint_channels(), lib_link_fcurves(), LIB_NEEDLINK, newlibadr_us(), bActionChannel::next, and ID::next.
Referenced by lib_link_all().
static void lib_link_all (FileData * fd, Main * main) [static]
Definition at line 13327 of file readfile.c.
References lib_link_action(), lib_link_armature(), lib_link_brush(), lib_link_camera(), lib_link_curve(), lib_link_group(), lib_link_image(), lib_link_ipo(), lib_link_key(), lib_link_lamp(), lib_link_latt(), lib_link_library(), lib_link_material(), lib_link_mball(), lib_link_mesh(), lib_link_movieclip(), lib_link_nodetree(), lib_link_object(), lib_link_particlesettings(), lib_link_scene(), lib_link_screen(), lib_link_sound(), lib_link_speaker(), lib_link_text(), lib_link_texture(), lib_link_vfont(), lib_link_windowmanager(), lib_link_world(), and oldnewmap_sort().
Referenced by blo_read_file_internal(), library_append_end(), and read_libraries().
static void lib_link_animdata (FileData * fd, ID * id, AnimData * adt) [static]
Definition at line 2082 of file readfile.c.
References AnimData::action, AnimData::drivers, GS, bAction::idroot, ID::lib, lib_link_fcurves(), lib_link_nladata(), ID::name, newlibadr_us(), AnimData::nla_tracks, NULL, and AnimData::tmpact.
Referenced by lib_link_armature(), lib_link_camera(), lib_link_curve(), lib_link_key(), lib_link_lamp(), lib_link_latt(), lib_link_material(), lib_link_mball(), lib_link_mesh(), lib_link_movieclip(), lib_link_ntree(), lib_link_object(), lib_link_particlesettings(), lib_link_scene(), lib_link_speaker(), lib_link_texture(), and lib_link_world().
static void lib_link_armature (FileData * fd, Main * main) [static]
Definition at line 2581 of file readfile.c.
References bArmature::adt, Main::armature, ListBase::first, ID::flag, bArmature::id, lib_link_animdata(), LIB_NEEDLINK, and ID::next.
Referenced by lib_link_all().
static void lib_link_brush (FileData * fd, Main * main) [static]
Definition at line 1649 of file readfile.c.
References Main::brush, Brush::clone, ListBase::first, ID::flag, Brush::id, BrushClone::image, ID::lib, LIB_NEEDLINK, Brush::mtex, newlibadr_us(), ID::next, and MTex::tex.
Referenced by lib_link_all().
static void lib_link_camera (FileData * fd, Main * main) [static]
Definition at line 2636 of file readfile.c.
References Camera::adt, Main::camera, Camera::dof_ob, ListBase::first, ID::flag, Camera::id, ID::lib, lib_link_animdata(), LIB_NEEDLINK, newlibadr_us(), and ID::next.
Referenced by lib_link_all().
static void lib_link_clipboard_restore (Main * newmain) [static]
Definition at line 5452 of file readfile.c.
References lib_link_seq_clipboard_cb(), seqbase_clipboard, and seqbase_recursive_apply().
Referenced by lib_link_screen_restore().
static void lib_link_constraint_cb (bConstraint * UNUSEDcon, ID ** idpoin, void * userdata) [static]
Definition at line 2461 of file readfile.c.
References tConstraintLinkData::fd, tConstraintLinkData::id, ID::lib, and newlibadr().
Referenced by lib_link_constraints().
static void lib_link_constraint_channels (FileData * fd, ID * id, ListBase * chanbase) [static]
Definition at line 1782 of file readfile.c.
References ListBase::first, bConstraintChannel::ipo, ID::lib, newlibadr_us(), and bConstraintChannel::next.
Referenced by lib_link_action(), and lib_link_object().
static void lib_link_constraints (FileData * fd, ID * id, ListBase * conlist) [static]
Definition at line 2467 of file readfile.c.
References CONSTRAINT_TYPE_NULL, bConstraint::data, tConstraintLinkData::fd, ListBase::first, tConstraintLinkData::id, id_loop_constraints(), ID::lib, lib_link_constraint_cb(), newlibadr_us(), bConstraint::next, NULL, and bConstraint::type.
Referenced by lib_link_object(), and lib_link_pose().
static void lib_link_curve (FileData * fd, Main * main) [static]
Definition at line 3045 of file readfile.c.
References Curve::adt, Curve::bevobj, Main::curve, ListBase::first, ID::flag, Curve::id, Curve::key, ID::lib, lib_link_animdata(), LIB_NEEDLINK, Curve::mat, newlibadr(), newlibadr_us(), ID::next, Curve::taperobj, Curve::textoncurve, Curve::totcol, Curve::vfont, Curve::vfontb, Curve::vfontbi, and Curve::vfonti.
Referenced by lib_link_all().
static void lib_link_customdata_mtface (FileData * fd, Mesh * me, CustomData * fdata, int totface) [static]
Definition at line 3647 of file readfile.c.
References CD_MTFACE, CustomDataLayer::data, i, CustomData::layers, lib_link_mtface(), CustomData::totlayer, and CustomDataLayer::type.
Referenced by lib_link_mesh().
static void lib_link_customdata_mtpoly (FileData * fd, Mesh * me, CustomData * pdata, int totface) [static]
Definition at line 3659 of file readfile.c.
References CD_MTEXPOLY, CustomDataLayer::data, i, Mesh::id, Image::id, CustomData::layers, ID::lib, newlibadr(), CustomData::totlayer, MTexPoly::tpage, CustomDataLayer::type, and ID::us.
Referenced by lib_link_mesh().
static void lib_link_fcurves (FileData * fd, ID * id, ListBase * list) [static]
Definition at line 1810 of file readfile.c.
References FCurve::driver, DRIVER_TARGETS_LOOPER, DRIVER_TARGETS_LOOPER_END, ListBase::first, Library::id, ID::lib, lib_link_fmodifiers(), FCurve::modifiers, newlibadr(), FCurve::next, DriverVar::next, NULL, and ChannelDriver::variables.
Referenced by lib_link_action(), lib_link_animdata(), and lib_link_nladata_strips().
static void lib_link_fmodifiers (FileData * fd, ID * id, ListBase * list) [static]
Definition at line 1793 of file readfile.c.
References FModifier::data, data, ListBase::first, FMODIFIER_TYPE_PYTHON, ID::lib, newlibadr(), FModifier::next, FMod_Python::script, and FModifier::type.
Referenced by lib_link_fcurves().
static void lib_link_group (FileData * fd, Main * main) [static]
Definition at line 6124 of file readfile.c.
References ListBase::first, Object::flag, ID::flag, Group::gobject, Main::group, Object::id, Group::id, ID::lib, LIB_NEEDLINK, newlibadr(), ID::next, GroupObject::next, NULL, GroupObject::ob, OB_FROMGROUP, rem_from_group(), and ID::us.
Referenced by lib_link_all().
static void lib_link_image (FileData * fd, Main * main) [static]
Definition at line 2974 of file readfile.c.
References FD_FLAGS_SWITCH_ENDIAN, ListBase::first, ID::flag, FileData::flags, Image::id, IDP_LibLinkProperty(), Main::image, LIB_NEEDLINK, ID::next, and ID::properties.
Referenced by lib_link_all().
static void lib_link_ipo (FileData * fd, Main * main) [static]
Definition at line 1722 of file readfile.c.
References Ipo::curve, IpoCurve::driver, ListBase::first, ID::flag, Ipo::id, Main::ipo, ID::lib, LIB_NEEDLINK, newlibadr(), IpoCurve::next, ID::next, and IpoDriver::ob.
Referenced by lib_link_all().
static void lib_link_key (FileData * fd, Main * main) [static]
Definition at line 2718 of file readfile.c.
References Key::adt, Key::block, ListBase::first, ID::flag, Key::from, Key::id, Main::key, ID::lib, lib_link_animdata(), LIB_NEEDLINK, newlibadr(), newlibadr_us(), KeyBlock::next, ID::next, KeyBlock::uid, and Key::uidgen.
Referenced by lib_link_all().
static void lib_link_keyingsets (FileData * fd, ID * id, ListBase * list) [static]
Definition at line 2049 of file readfile.c.
References ListBase::first, KS_Path::id, ID::lib, newlibadr(), KeyingSet::next, KS_Path::next, and KeyingSet::paths.
Referenced by lib_link_scene().
static void lib_link_lamp (FileData * fd, Main * main) [static]
Definition at line 2664 of file readfile.c.
References Lamp::adt, ListBase::first, ID::flag, Lamp::id, Main::lamp, ID::lib, lib_link_animdata(), lib_link_ntree(), LIB_NEEDLINK, MAX_MTEX, Lamp::mtex, newlibadr(), newlibadr_us(), ID::next, Lamp::nodetree, MTex::object, and MTex::tex.
Referenced by lib_link_all().
static void lib_link_latt (FileData * fd, Main * main) [static]
Definition at line 3966 of file readfile.c.
References Lattice::adt, ListBase::first, ID::flag, Lattice::id, Lattice::key, Main::latt, ID::lib, lib_link_animdata(), LIB_NEEDLINK, newlibadr_us(), and ID::next.
Referenced by lib_link_all().
static void lib_link_library (FileData * UNUSEDfd, Main * main) [static]
Definition at line 6013 of file readfile.c.
References ListBase::first, Library::id, Main::library, ID::next, and ID::us.
Referenced by lib_link_all().
static void lib_link_material (FileData * fd, Main * main) [static]
Definition at line 3236 of file readfile.c.
References Material::adt, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, ID::flag, FileData::flags, Material::group, Material::id, IDP_LibLinkProperty(), ID::lib, lib_link_animdata(), lib_link_ntree(), LIB_NEEDLINK, Main::mat, MAX_MTEX, Material::mtex, newlibadr(), newlibadr_us(), ID::next, Material::nodetree, MTex::object, ID::properties, and MTex::tex.
Referenced by lib_link_all().
static void lib_link_mball (FileData * fd, Main * main) [static]
Definition at line 2805 of file readfile.c.
References MetaBall::adt, ListBase::first, ID::flag, MetaBall::id, ID::lib, lib_link_animdata(), LIB_NEEDLINK, MetaBall::mat, Main::mball, newlibadr_us(), ID::next, and MetaBall::totcol.
Referenced by lib_link_all().
static void lib_link_mesh (FileData * fd, Main * main) [static]
Definition at line 3679 of file readfile.c.
References Mesh::adt, BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_tessface_calc(), BKE_mesh_tessface_clear(), convert_tface_mt(), FD_FLAGS_SWITCH_ENDIAN, Mesh::fdata, ListBase::first, ID::flag, FileData::flags, G, i, Mesh::id, IDP_LibLinkProperty(), Mesh::key, ID::lib, lib_link_animdata(), lib_link_customdata_mtface(), lib_link_customdata_mtpoly(), LIB_NEEDLINK, main(), Mesh::mat, Main::mesh, newlibadr_us(), ID::next, ID::properties, Mesh::texcomesh, Mesh::totcol, Mesh::totface, and Mesh::totpoly.
Referenced by lib_link_all().
static void lib_link_modifiers (FileData * fd, Object * ob) [static]
Definition at line 4010 of file readfile.c.
References lib_link_modifiers__linkModifiers(), and modifiers_foreachIDLink().
Referenced by lib_link_object().
static void lib_link_modifiers__linkModifiers (void * userData, Object * ob, ID ** idpoin) [static]
Definition at line 4000 of file readfile.c.
References GS, Object::id, ID_OB, ID::lib, and newlibadr().
Referenced by lib_link_modifiers().
static void lib_link_movieclip (FileData * fd, Main * main) [static]
Definition at line 6213 of file readfile.c.
References MovieClip::adt, ListBase::first, ID::flag, MovieClip::gpd, MovieClip::id, ID::lib, lib_link_animdata(), LIB_NEEDLINK, Main::movieclip, newlibadr_us(), and ID::next.
Referenced by lib_link_all().
static void lib_link_mtface (FileData * fd, Mesh * me, MTFace * mtface, int totface) [static]
Definition at line 3632 of file readfile.c.
References i, Mesh::id, Image::id, ID::lib, newlibadr(), MTFace::tpage, and ID::us.
Referenced by lib_link_customdata_mtface().
static void lib_link_nladata (FileData * fd, ID * id, ListBase * list) [static]
Definition at line 2001 of file readfile.c.
References ListBase::first, lib_link_nladata_strips(), NlaTrack::next, and NlaTrack::strips.
Referenced by lib_link_animdata().
static void lib_link_nladata_strips (FileData * fd, ID * id, ListBase * list) [static]
Definition at line 1981 of file readfile.c.
References NlaStrip::act, NlaStrip::fcurves, ListBase::first, GS, bAction::idroot, ID::lib, lib_link_fcurves(), ID::name, newlibadr_us(), NlaStrip::next, and NlaStrip::strips.
Referenced by lib_link_nladata().
static void lib_link_nlastrips (FileData * fd, ID * id, ListBase * striplist) [static]
Definition at line 1756 of file readfile.c.
References bActionStrip::act, ListBase::first, bActionStrip::ipo, ID::lib, bActionStrip::modifiers, newlibadr(), newlibadr_us(), bActionModifier::next, bActionStrip::next, bActionModifier::ob, and bActionStrip::object.
Referenced by lib_link_object().
static void lib_link_nodetree (FileData * fd, Main * main) [static]
Definition at line 2161 of file readfile.c.
References ListBase::first, ID::flag, bNodeTree::id, lib_link_ntree(), LIB_NEEDLINK, ID::next, and Main::nodetree.
Referenced by lib_link_all().
static void lib_link_ntree (FileData * fd, ID * id, bNodeTree * ntree) [static]
Definition at line 2148 of file readfile.c.
References bNodeTree::adt, ListBase::first, bNodeTree::gpd, bNode::id, bNodeTree::id, ID::lib, lib_link_animdata(), newlibadr_us(), bNode::next, and bNodeTree::nodes.
Referenced by lib_link_lamp(), lib_link_material(), lib_link_nodetree(), lib_link_scene(), lib_link_texture(), and lib_link_world().
static void lib_link_object (FileData * fd, Main * main) [static]
Definition at line 4015 of file readfile.c.
References bActionActuator::act, ACT_2DFILTER, ACT_ACTION, ACT_ADD_OBJECT, ACT_ARMATURE, ACT_CAMERA, ACT_EDIT_OBJECT, ACT_GAME, ACT_MESSAGE, ACT_OBJECT, ACT_PARENT, ACT_PROPERTY, ACT_SCENE, ACT_SHAPEACTION, ACT_SOUND, ACT_STATE, ACT_STEERING, Object::actuators, Object::adt, BKE_report(), bSceneActuator::camera, Object::constraints, CONT_PYTHON, Object::controllers, bActuator::data, bController::data, bSensor::data, Object::data, SmokeModifierData::domain, Object::dup_group, Object::duplilist, EFF_PARTICLE, SoftBody::effector_weights, eModifierType_Fluidsim, eModifierType_Smoke, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, ID::flag, SmokeDomainSettings::flags, FileData::flags, free_pose(), bMessageSensor::fromObject, FluidsimModifierData::fss, give_totcolp(), Object::gpd, EffectorWeights::group, PartEff::group, Object::id, IDP_LibLinkProperty(), init_actuator(), FluidsimSettings::ipo, ID::lib, lib_link_animdata(), lib_link_constraint_channels(), lib_link_constraints(), lib_link_modifiers(), lib_link_nlastrips(), lib_link_partdeflect(), lib_link_particlesystems(), lib_link_pose(), LIB_NEEDLINK, bController::links, bSensor::links, bTouchSensor::ma, Object::mat, bEditObjectActuator::me, MOD_SMOKE_FILE_LOAD, MOD_SMOKE_TYPE_DOMAIN, Object::mode, modifiers_findByType(), Library::name, ID::name, bSteeringActuator::navmesh, newglobadr(), newlibadr(), newlibadr_us(), ID::next, bActuator::next, bController::next, bSensor::next, PartEff::next, NULL, bParentActuator::ob, bPropertyActuator::ob, bEditObjectActuator::ob, bAddObjectActuator::ob, bCameraActuator::ob, OB_EMPTY, OB_MODE_POSE, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, Main::object, Object::parent, Object::particlesystem, Object::pd, Object::pose, Object::poselib, ID::properties, Object::proxy, Object::proxy_from, Object::proxy_group, Object::recalc, bObjectActuator::reference, FileData::reports, resize_object_material(), RPT_WARNING, bSceneActuator::scene, SENS_MESSAGE, SENS_TOUCH, Object::sensors, bController::slinks, Object::soft, bSoundActuator::sound, bArmatureActuator::subtarget, bSteeringActuator::target, bArmatureActuator::target, bTwoDFilterActuator::text, bPythonCont::text, bMessageActuator::toObject, Object::totcol, bController::totlinks, bSensor::totlinks, bController::totslinks, Object::track, SmokeModifierData::type, bActuator::type, bController::type, bSensor::type, PartEff::type, and Object::type.
Referenced by lib_link_all().
static void lib_link_partdeflect (FileData * fd, ID * id, PartDeflect * pd) [static]
Definition at line 3374 of file readfile.c.
References ID::lib, newlibadr_us(), and PartDeflect::tex.
Referenced by lib_link_object(), and lib_link_particlesettings().
static void lib_link_particlesettings (FileData * fd, Main * main) [static]
Definition at line 3380 of file readfile.c.
References ParticleSettings::adt, ParticleSettings::bb_ob, BLI_findlink(), ParticleSettings::boids, ParticleSettings::dup_group, ParticleSettings::dup_ob, ParticleSettings::dupliweights, eBoidRuleType_Avoid, eBoidRuleType_FollowLeader, eBoidRuleType_Goal, ParticleSettings::effector_weights, ListBase::first, ID::flag, Group::gobject, EffectorWeights::group, ParticleSettings::id, ParticleDupliWeight::index, ListBase::last, ID::lib, lib_link_animdata(), lib_link_partdeflect(), LIB_NEEDLINK, MAX_MTEX, ParticleSettings::mtex, newlibadr(), newlibadr_us(), ID::next, BoidRule::next, BoidState::next, ParticleDupliWeight::next, NULL, BoidRuleFollowLeader::ob, BoidRuleGoalAvoid::ob, GroupObject::ob, ParticleDupliWeight::ob, MTex::object, Main::particle, ParticleSettings::pd, ParticleSettings::pd2, BoidState::rules, state, BoidSettings::states, MTex::tex, and BoidRule::type.
Referenced by lib_link_all().
static void lib_link_particlesystems (FileData * fd, Object * ob, ID * id, ListBase * particles) [static]
Definition at line 3517 of file readfile.c.
References BLI_remlink(), ParticleSystem::clmd, ClothModifierData::coll_parms, ListBase::first, ClothCollSettings::group, ListBase::last, ID::lib, MEM_freeN(), modifier_free(), Object::modifiers, newlibadr(), newlibadr_us(), ParticleTarget::next, ParticleSystem::next, NULL, ParticleTarget::ob, ParticleSystem::parent, ParticleSystem::part, ClothModifierData::point_cache, ParticleSystem::pointcache, psys_get_modifier(), ClothModifierData::ptcaches, ParticleSystem::target_ob, and ParticleSystem::targets.
Referenced by lib_link_object().
static void lib_link_pose (FileData * fd, Object * ob, bPose * pose) [static]
Definition at line 2533 of file readfile.c.
References bArmature::act_bone, bPoseChannel::bone, BONE_SELECTED, bPose::chanbase, bPoseChannel::constraints, bPoseChannel::custom, Object::data, ListBase::first, bPose::flag, Bone::flag, get_named_bone(), bArmature::id, Object::id, bArmature::layer, ID::lib, lib_link_constraints(), bPoseChannel::name, newlibadr_us(), bPoseChannel::next, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, POSE_RECALC, Object::proxy, bPose::proxy_act_bone, bPose::proxy_layer, Object::recalc, and bPoseChannel::selectflag.
Referenced by lib_link_object().
static void lib_link_scene (FileData * fd, Main * main) [static]
Definition at line 4804 of file readfile.c.
References Scene::adt, Sequence::anim, Scene::basact, Scene::base, BKE_reportf_wrap(), BLI_remlink(), TimeMarker::camera, Scene::camera, Scene::clip, Sequence::clip, composite_patch(), GameData::dome, Scene::ed, FD_FLAGS_SWITCH_ENDIAN, ListBase::first, ID::flag, FileData::flags, Scene::gm, Scene::gpd, bSound::id, MovieClip::id, Scene::id, IDP_LibLinkProperty(), ToolSettings::imapaint, Scene::keyingsets, RenderData::layers, ID::lib, lib_link_animdata(), lib_link_keyingsets(), lib_link_ntree(), LIB_NEEDLINK, SceneRenderLayer::light_override, link_paint(), Scene::markers, SceneRenderLayer::mat_override, MEM_freeN(), ID::name, newlibadr(), newlibadr_us(), ID::next, SceneRenderLayer::next, TimeMarker::next, Base::next, next, Scene::nodetree, NULL, Base::object, UvSculpt::paint, ImagePaintSettings::paint, VPaint::paint, Sculpt::paint, ID::properties, Scene::r, FileData::reports, RPT_ERROR, Sequence::scene, Main::scene, Sequence::scene_camera, Sequence::scene_sound, ToolSettings::sculpt, SEQ_BEGIN, SEQ_END, SEQ_HD_SOUND, SEQ_SOUND, seq_update_muting(), seq_update_sound_bounds_all(), Scene::set, ToolSettings::skgen_template, Sequence::sound, sound_add_scene_sound_defaults(), sound_scene_add_scene_sound_defaults(), Scene::toolsettings, Sequence::type, ID::us, ToolSettings::uvsculpt, ToolSettings::vpaint, GameDome::warptext, Scene::world, and ToolSettings::wpaint.
Referenced by lib_link_all().
static void lib_link_screen (FileData * fd, Main * main) [static]
Definition at line 5236 of file readfile.c.
References SpaceAction::action, SpaceNla::ads, SpaceAction::ads, SpaceIpo::ads, bScreen::animtimer, bScreen::areabase, View3D::bgpicbase, BLI_addtail(), butspace_version_132(), View3D::camera, SpaceClip::clip, BGpic::clip, TreeStore::data, SpaceText::drawcache, SpaceNode::edittree, ELEM3, SpaceFile::files, bDopeSheet::filter_grp, ListBase::first, ID::flag, SpaceFile::folders_next, SpaceFile::folders_prev, ScrArea::full, SpaceImage::gpd, GS, SpaceNode::id, TreeStoreElem::id, bScreen::id, ID_LA, ID_MA, ID_SCE, ID_TE, ID_WO, BGpic::ima, SpaceImage::image, ListBase::last, SpaceFile::layout, ID::lib, LIB_NEEDLINK, SpaceNode::linkdrag, View3D::localvd, SpaceButs::mainb, SpaceButs::mainbo, SpaceButs::mainbuser, ID::name, newlibadr(), newlibadr_us(), ScrArea::next, BGpic::next, SpaceLink::next, ID::next, SpaceNode::nodetree, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, View3D::ob_centre, MovieClipScopes::ok, SpaceFile::op, SpaceButs::pinid, bScreen::scene, SpaceClip::scopes, Main::screen, SpaceScript::script, SCRIPT_SET_NULL, SpaceOops::search_tse, bDopeSheet::source, SPACE_ACTION, SPACE_BUTS, SPACE_CLIP, SPACE_FILE, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_OUTLINER, SPACE_SCRIPT, SPACE_TEXT, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, SpaceText::text, MovieClipScopes::track_preview, SpaceOops::tree, SpaceOops::treestore, SpaceNode::treetype, ID::us, TreeStore::usedelem, and Main::versionfile.
Referenced by lib_link_all().
void lib_link_screen_restore (Main * newmain, bScreen * curscreen, Scene * curscene)
Definition at line 5461 of file readfile.c.
References SpaceAction::action, SpaceNla::ads, SpaceAction::ads, SpaceIpo::ads, bScreen::areabase, View3D::bgpicbase, Scene::camera, View3D::camera, SpaceClip::clip, BGpic::clip, copy_v3_v3(), Scene::cursor, TreeStore::data, SpaceNode::edittree, ELEM3, bDopeSheet::filter_grp, ListBase::first, SpaceImage::gpd, GS, bNodeTree::id, SpaceNode::id, TreeStoreElem::id, bScreen::id, wmWindowManager::id, ID_MA, ID_SCE, ID_TE, BGpic::ima, SpaceImage::image, SpaceImage::iuser, Scene::lay, View3D::lay, View3D::layact, lib_link_clipboard_restore(), View3D::localvd, ID::name, ScrArea::next, ARegion::next, BGpic::next, SpaceLink::next, wmWindow::next, ID::next, SpaceNode::nodetree, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, NULL, View3D::ob_centre, MovieClipScopes::ok, Scopes::ok, SpaceFile::op, SpaceButs::pinid, RE_engine_free(), ScrArea::regionbase, ARegion::regiondata, RegionView3D::render_engine, restore_pointer_by_name(), ImageUser::scene, bScreen::scene, View3D::scenelock, SpaceClip::scopes, SpaceImage::scopes, Main::screen, wmWindow::screen, SpaceScript::script, SCRIPT_SET_NULL, SpaceOops::search_tse, bDopeSheet::source, SPACE_ACTION, SPACE_BUTS, SPACE_CLIP, SPACE_FILE, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_OUTLINER, SPACE_SCRIPT, SPACE_TEXT, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, Main::text, SpaceText::text, SpaceOops::treestore, SpaceNode::treetype, TreeStore::usedelem, Scopes::vecscope, Scopes::waveform_1, Scopes::waveform_2, Scopes::waveform_3, wmWindowManager::windows, wmWindow::winid, bScreen::winid, and Main::wm.
Referenced by setup_app_data().
static int lib_link_seq_clipboard_cb (Sequence * seq, void * arg_pt) [static]
Definition at line 5434 of file readfile.c.
References bSound::id, restore_pointer_by_name(), Sequence::scene, Sequence::scene_camera, Sequence::sound, and ID::us.
Referenced by lib_link_clipboard_restore().
static void lib_link_sound (FileData * fd, Main * main) [static]
Definition at line 6102 of file readfile.c.
References ListBase::first, ID::flag, bSound::id, bSound::ipo, ID::lib, LIB_NEEDLINK, newlibadr_us(), ID::next, Main::sound, and sound_load().
Referenced by lib_link_all().
static void lib_link_speaker (FileData * fd, Main * main) [static]
Definition at line 6052 of file readfile.c.
References Speaker::adt, ListBase::first, ID::flag, Speaker::id, bSound::id, ID::lib, lib_link_animdata(), LIB_NEEDLINK, newlibadr(), ID::next, Speaker::sound, Main::speaker, and ID::us.
Referenced by lib_link_all().
static void lib_link_text (FileData * UNUSEDfd, Main * main) [static]
Definition at line 2916 of file readfile.c.
References ListBase::first, ID::flag, Text::id, LIB_NEEDLINK, ID::next, and Main::text.
Referenced by lib_link_all().
static void lib_link_texture (FileData * fd, Main * main) [static]
Definition at line 3152 of file readfile.c.
References Tex::adt, Tex::env, ListBase::first, ID::flag, Tex::id, Tex::ima, ID::lib, lib_link_animdata(), lib_link_ntree(), LIB_NEEDLINK, newlibadr(), newlibadr_us(), ID::next, Tex::nodetree, VoxelData::object, EnvMap::object, OceanTex::object, PointDensity::object, Tex::ot, Tex::pd, Main::tex, and Tex::vd.
Referenced by lib_link_all().
static void lib_link_vfont (FileData * UNUSEDfd, Main * main) [static]
Definition at line 2895 of file readfile.c.
References ListBase::first, ID::flag, VFont::id, LIB_NEEDLINK, ID::next, and Main::vfont.
Referenced by lib_link_all().
static void lib_link_windowmanager (FileData * fd, Main * main) [static]
Definition at line 5164 of file readfile.c.
References ListBase::first, ID::flag, wmWindowManager::id, LIB_NEEDLINK, newlibadr(), wmWindow::next, ID::next, NULL, wmWindow::screen, wmWindowManager::windows, and Main::wm.
Referenced by lib_link_all().
static void lib_link_world (FileData * fd, Main * main) [static]
Definition at line 2844 of file readfile.c.
References World::adt, ListBase::first, ID::flag, World::id, ID::lib, lib_link_animdata(), lib_link_ntree(), LIB_NEEDLINK, MAX_MTEX, World::mtex, newlibadr(), newlibadr_us(), ID::next, World::nodetree, MTex::object, MTex::tex, and Main::world.
Referenced by lib_link_all().
static void lib_node_do_versions_group_indices (bNode * gnode) [static]
Definition at line 2238 of file readfile.c.
References ListBase::first, bNode::id, bNode::inputs, bNodeTree::nodes, bNode::outputs, bNodeTree::outputs, and bNodeSocket::own_index.
Referenced by lib_nodetree_do_versions_group_indices_cb().
static void lib_nodetree_do_versions_group_indices_cb (void * UNUSEDdata, ID * UNUSEDid, bNodeTree * ntree) [static]
Definition at line 2271 of file readfile.c.
References ListBase::first, bNodeTree::flag, bNode::id, if(), lib_node_do_versions_group_indices(), bNode::next, NODE_GROUP, bNodeTree::nodes, NTREE_DO_VERSIONS_GROUP_EXPOSE, and bNode::type.
Referenced by lib_verify_nodetree().
static void lib_nodetree_do_versions_update_cb (void * UNUSEDdata, ID * UNUSEDid, bNodeTree * ntree) [static]
Definition at line 2285 of file readfile.c.
References ntreeUpdateTree(), and bNodeTree::update.
Referenced by lib_verify_nodetree().
static void lib_nodetree_init_types_cb (void * UNUSEDdata, ID * UNUSEDid, bNodeTree * ntree) [static]
Definition at line 2221 of file readfile.c.
References do_versions_nodetree_default_value(), ListBase::first, bNode::next, node_verify_socket_templates(), bNodeTree::nodes, and ntreeInitTypes().
Referenced by lib_verify_nodetree().
static void lib_verify_nodetree (Main * main, int UNUSEDopen) [static]
Definition at line 2294 of file readfile.c.
References ListBase::first, bNodeTree::flag, bNodeTreeType::foreach_nodetree, i, bNodeTree::id, lib_nodetree_do_versions_group_indices_cb(), lib_nodetree_do_versions_update_cb(), lib_nodetree_init_types_cb(), ID::next, node_group_expose_all_sockets(), Main::nodetree, NTREE_DO_VERSIONS_GROUP_EXPOSE, ntreeGetType(), ntreeUpdateTree(), ntreeVerifyNodes(), NULL, NUM_NTREE_TYPES, and bNodeTree::update.
Referenced by blo_read_file_internal(), and library_append_end().
static Main* library_append_begin (Main * mainvar, FileData ** fd, const char * filepath) [static]
Definition at line 14642 of file readfile.c.
References blo_find_main(), blo_split_main(), G, FileData::mainlist, read_file_version(), and Main::versionfile.
Referenced by BLO_library_append_begin().
static void library_append_end (const bContext * C, Main * mainl, FileData ** fd, int idcode, short flag) [static]
Definition at line 14667 of file readfile.c.
References BLI_path_rel(), BLI_strncpy(), blo_freefiledata(), blo_join_main(), CTX_data_scene(), Main::curlib, expand_main(), FALSE, FD_FLAGS_SWITCH_ENDIAN, FILE_GROUP_INSTANCE, FILE_LINK, FILE_RELPATH, Library::filepath, fix_relpaths_library(), G, give_base_to_groups(), give_base_to_objects(), ID_SCE, lib_link_all(), lib_verify_nodetree(), FileData::mainlist, Library::name, NULL, and read_libraries().
Referenced by BLO_library_append_end().
static void link_glob_list (FileData * fd, ListBase * lb) [static]
Definition at line 1435 of file readfile.c.
References ListBase::first, FileData::globmap, ListBase::last, newdataadr(), Link::next, NULL, oldnewmap_insert(), and Link::prev.
Referenced by direct_link_object().
static void link_global (FileData * fd, BlendFileData * bfd) [static]
Definition at line 6487 of file readfile.c.
References BlendFileData::curscene, BlendFileData::curscreen, newlibadr(), NULL, and bScreen::scene.
Referenced by blo_read_file_internal().
static void link_ibuf_list (FileData * fd, ListBase * lb) [static]
Definition at line 2989 of file readfile.c.
References ListBase::first, ListBase::last, newimaadr(), Link::next, NULL, and Link::prev.
Referenced by direct_link_image().
static void link_list (FileData * fd, ListBase * lb) [static]
Definition at line 1417 of file readfile.c.
References ListBase::first, ListBase::last, newdataadr(), Link::next, NULL, and Link::prev.
Referenced by direct_link_action(), direct_link_animdata(), direct_link_armature(), direct_link_bones(), direct_link_constraints(), direct_link_curve(), direct_link_fcurves(), direct_link_gpencil(), direct_link_group(), direct_link_ipo(), direct_link_key(), direct_link_keyingsets(), direct_link_mball(), direct_link_mesh(), direct_link_modifiers(), direct_link_movieclip(), direct_link_movieTracks(), direct_link_nladata(), direct_link_nladata_strips(), direct_link_nlastrips(), direct_link_nodetree(), direct_link_object(), direct_link_particlesettings(), direct_link_particlesystems(), direct_link_pointcache(), direct_link_pointcache_list(), direct_link_pose(), direct_link_region(), direct_link_scene(), direct_link_screen(), direct_link_text(), direct_link_windowmanager(), IDP_DirectLinkGroup(), link_recurs_seq(), and read_userdef().
static void link_paint (FileData * fd, Scene * sce, Paint * p) [static]
Definition at line 4796 of file readfile.c.
References Paint::brush, Scene::id, ID::lib, newlibadr_us(), NULL, and Paint::paint_cursor.
Referenced by lib_link_scene().
static void link_recurs_seq (FileData * fd, ListBase * lb) [static]
Definition at line 4914 of file readfile.c.
References ListBase::first, link_list(), Sequence::next, and Sequence::seqbase.
Referenced by direct_link_scene().
static int mainvar_count_libread_blocks (Main * mainvar) [static]
Definition at line 14744 of file readfile.c.
References ID::flag, LIB_READ, MAX_LIBARRAY, ID::next, and set_listbasepointers().
Referenced by read_libraries().
static int map_223_keybd_code_to_224_keybd_code (int code) [static]
Definition at line 6521 of file readfile.c.
Referenced by do_versions().
static void* newdataadr (FileData * fd, void * adr) [static]
Definition at line 1150 of file readfile.c.
References FileData::datamap, and oldnewmap_lookup_and_inc().
Referenced by direct_link_action(), direct_link_animdata(), direct_link_armature(), direct_link_bones(), direct_link_brush(), direct_link_camera(), direct_link_constraints(), direct_link_curve(), direct_link_curvemapping(), direct_link_customdata(), direct_link_dverts(), direct_link_fcurves(), direct_link_fmodifiers(), direct_link_gpencil(), direct_link_ipo(), direct_link_key(), direct_link_keyingsets(), direct_link_keymapitem(), direct_link_lamp(), direct_link_latt(), direct_link_material(), direct_link_mball(), direct_link_mdisps(), direct_link_mesh(), direct_link_modifiers(), direct_link_motionpath(), direct_link_movieclip(), direct_link_movieReconstruction(), direct_link_movieTracks(), direct_link_node_socket(), direct_link_nodetree(), direct_link_object(), direct_link_packedfile(), direct_link_paint(), direct_link_particlesettings(), direct_link_particlesystems(), direct_link_pointcache(), direct_link_pointcache_list(), direct_link_pose(), direct_link_preview_image(), direct_link_region(), direct_link_scene(), direct_link_screen(), direct_link_speaker(), direct_link_text(), direct_link_texture(), direct_link_world(), IDP_DirectLinkArray(), IDP_DirectLinkIDPArray(), IDP_DirectLinkString(), link_glob_list(), link_list(), read_libblock(), and read_userdef().
static void* newglobadr (FileData * fd, void * adr) [static]
Definition at line 1155 of file readfile.c.
References FileData::globmap, and oldnewmap_lookup_and_inc().
Referenced by lib_link_object().
static void* newimaadr (FileData * fd, void * adr) [static]
Definition at line 1160 of file readfile.c.
References FileData::imamap, NULL, and oldnewmap_lookup_and_inc().
Referenced by blo_end_image_pointer_map(), direct_link_image(), direct_link_nodetree(), and link_ibuf_list().
static void* newlibadr (FileData * fd, void * lib, void * adr) [static]
Definition at line 1175 of file readfile.c.
References FileData::libmap, and oldnewmap_liblookup().
Referenced by alphasort_version_246(), do_versions(), lib_link_constraint_cb(), lib_link_curve(), lib_link_customdata_mtpoly(), lib_link_fcurves(), lib_link_fmodifiers(), lib_link_group(), lib_link_ipo(), lib_link_key(), lib_link_keyingsets(), lib_link_lamp(), lib_link_material(), lib_link_modifiers__linkModifiers(), lib_link_mtface(), lib_link_nlastrips(), lib_link_object(), lib_link_particlesettings(), lib_link_particlesystems(), lib_link_scene(), lib_link_screen(), lib_link_speaker(), lib_link_texture(), lib_link_windowmanager(), lib_link_world(), link_global(), newlibadr_us(), and ntree_version_245().
static void* newlibadr_us (FileData * fd, void * lib, void * adr) [static]
Definition at line 1180 of file readfile.c.
References newlibadr().
Referenced by do_versions(), lib_link_action(), lib_link_animdata(), lib_link_brush(), lib_link_camera(), lib_link_constraint_channels(), lib_link_constraints(), lib_link_curve(), lib_link_key(), lib_link_lamp(), lib_link_latt(), lib_link_material(), lib_link_mball(), lib_link_mesh(), lib_link_movieclip(), lib_link_nladata_strips(), lib_link_nlastrips(), lib_link_ntree(), lib_link_object(), lib_link_partdeflect(), lib_link_particlesettings(), lib_link_particlesystems(), lib_link_pose(), lib_link_scene(), lib_link_screen(), lib_link_sound(), lib_link_texture(), lib_link_world(), and link_paint().
static void* newmclipadr (FileData * fd, void * adr) [static]
Definition at line 1167 of file readfile.c.
References FileData::movieclipmap, NULL, and oldnewmap_lookup_and_inc().
Referenced by blo_end_movieclip_pointer_map(), direct_link_movieclip(), and direct_link_nodetree().
static void ntree_version_241 (bNodeTree * ntree) [static]
Definition at line 6584 of file readfile.c.
References CMP_NODE_BLUR, CMP_NODE_VECBLUR, bNode::custom1, bNode::custom2, NodeBlurData::fac, NodeBlurData::filtertype, ListBase::first, NodeBlurData::maxspeed, MEM_callocN(), bNode::next, bNodeTree::nodes, NTREE_COMPOSIT, NULL, R_FILTER_QUAD, NodeBlurData::samples, NodeBlurData::sizex, NodeBlurData::sizey, bNode::storage, bNode::type, and bNodeTree::type.
Referenced by do_versions().
static void ntree_version_242 (bNodeTree * ntree) [static]
Definition at line 6612 of file readfile.c.
References CMP_NODE_HUE_SAT, ListBase::first, MEM_callocN(), bNode::next, bNodeTree::nodes, NTREE_COMPOSIT, NTREE_SHADER, NULL, SH_NODE_GEOMETRY, bNode::storage, bNode::type, bNodeTree::type, and NodeHueSat::val.
Referenced by do_versions().
static void ntree_version_245 (FileData * fd, Library * lib, bNodeTree * ntree) [static]
Definition at line 6761 of file readfile.c.
References CMP_NODE_ALPHAOVER, bNode::custom1, ListBase::first, ImageUser::flag, Image::flag, GS, bNode::id, ID_IM, IMA_DO_PREMUL, IMA_OLD_PREMUL, MEM_callocN(), ID::name, newlibadr(), bNode::next, bNodeTree::nodes, NTREE_COMPOSIT, bNode::storage, bNodeTree::type, bNode::type, and NodeTwoFloats::x.
Referenced by do_versions().
static int object_in_any_scene (Main * mainvar, Object * ob) [static]
Definition at line 14419 of file readfile.c.
References ListBase::first, Scene::id, ID::next, object_in_scene(), and Main::scene.
Referenced by give_base_to_objects().
static void oldnewmap_clear (OldNewMap * onm) [static]
Definition at line 410 of file readfile.c.
References OldNewMap::lasthit, and OldNewMap::nentries.
Referenced by read_libblock(), and read_userdef().
static void oldnewmap_free (OldNewMap * onm) [static]
Definition at line 416 of file readfile.c.
References OldNewMap::entries, and MEM_freeN().
Referenced by blo_freefiledata(), and read_libraries().
static void oldnewmap_free_unused (OldNewMap * onm) [static]
Definition at line 397 of file readfile.c.
References OldNewMap::entries, i, MEM_freeN(), OldNewMap::nentries, OldNew::newp, OldNew::nr, and NULL.
Referenced by read_libblock(), and read_userdef().
static void oldnewmap_insert (OldNewMap * onm, void * oldaddr, void * newaddr, int nr) [static]
Definition at line 307 of file readfile.c.
References OldNewMap::entries, OldNewMap::entriessize, MEM_freeN(), MEM_mallocN(), OldNewMap::nentries, OldNew::newp, OldNew::nr, NULL, and OldNew::old.
Referenced by append_named_part(), blo_add_library_pointer_map(), blo_make_image_pointer_map(), blo_make_movieclip_pointer_map(), do_versions(), expand_doit(), link_glob_list(), read_data_into_oldnewmap(), and read_libblock().
static void* oldnewmap_liblookup (OldNewMap * onm, void * addr, void * lib) [static]
Definition at line 360 of file readfile.c.
References OldNewMap::entries, i, ID::lib, OldNewMap::nentries, OldNew::newp, NULL, OldNew::old, OldNewMap::sorted, and verg_oldnewmap().
Referenced by newlibadr().
static void* oldnewmap_lookup_and_inc (OldNewMap * onm, void * addr) [static]
Definition at line 330 of file readfile.c.
References OldNewMap::entries, i, OldNewMap::lasthit, OldNewMap::nentries, OldNew::newp, OldNew::nr, NULL, and OldNew::old.
Referenced by newdataadr(), newglobadr(), newimaadr(), and newmclipadr().
static OldNewMap* oldnewmap_new (void) [static]
Definition at line 280 of file readfile.c.
References OldNewMap::entries, OldNewMap::entriessize, MEM_callocN(), and MEM_mallocN().
Referenced by blo_make_image_pointer_map(), blo_make_movieclip_pointer_map(), filedata_new(), and read_libraries().
static void oldnewmap_sort (FileData * fd) [static]
Definition at line 300 of file readfile.c.
References OldNewMap::entries, FileData::libmap, OldNewMap::nentries, OldNewMap::sorted, and verg_oldnewmap().
Referenced by lib_link_all().
static BHead* read_data_into_oldnewmap (FileData * fd, BHead * bhead, const char * allocname) [static]
Definition at line 6271 of file readfile.c.
References blo_nextbhead(), BHead::code, DATA, data, FileData::datamap, FileData::filesdna, BHead::old, oldnewmap_insert(), read_struct(), BHead::SDNAnr, SDNA::structs, and SDNA::types.
Referenced by read_libblock(), and read_userdef().
static int read_file_dna (FileData * fd) [static]
Definition at line 834 of file readfile.c.
References blo_firstbhead(), blo_nextbhead(), BHead::code, FileData::compflags, DNA1, DNA_elem_offset(), DNA_sdna_from_data(), DNA_struct_get_compareflags(), ENDB, FD_FLAGS_SWITCH_ENDIAN, FileData::filesdna, FileData::flags, FileData::id_name_offs, BHead::len, and FileData::memsdna.
Referenced by blo_decode_and_check().
static void read_file_version (FileData * fd, Main * main) [static]
Definition at line 512 of file readfile.c.
References blo_firstbhead(), blo_nextbhead(), BHead::code, ENDB, GLOB, MEM_freeN(), FileGlobal::minsubversion, Main::minsubversionfile, FileGlobal::minversion, Main::minversionfile, read_struct(), FileGlobal::subversion, and Main::subversionfile.
Referenced by blo_find_main(), library_append_begin(), and read_libraries().
static BHead* read_global (BlendFileData * bfd, FileData * fd, BHead * bhead) [static]
Definition at line 6456 of file readfile.c.
References BLI_strncpy(), blo_nextbhead(), FileGlobal::curscene, BlendFileData::curscene, FileGlobal::curscreen, BlendFileData::curscreen, FileGlobal::displaymode, BlendFileData::displaymode, FileData::fileflags, FileGlobal::fileflags, BlendFileData::fileflags, FileGlobal::filename, BlendFileData::filename, G, G_FILE_RECOVER, FileData::globalf, FileGlobal::globalf, BlendFileData::globalf, BlendFileData::main, MEM_freeN(), FileGlobal::minsubversion, Main::minsubversionfile, FileGlobal::minversion, Main::minversionfile, read_struct(), FileData::relabase, FileGlobal::revision, Main::revision, FileGlobal::subversion, Main::subversionfile, FileGlobal::winpos, and BlendFileData::winpos.
Referenced by blo_read_file_internal().
static BHead* read_libblock (FileData * fd, Main * main, BHead * bhead, int flag, ID ** id_r) [static]
Definition at line 6298 of file readfile.c.
References BLI_addtail(), blo_nextbhead(), BHead::code, Main::curlib, FileData::datamap, dataname(), direct_link_action(), direct_link_armature(), direct_link_brush(), direct_link_camera(), direct_link_curve(), direct_link_gpencil(), direct_link_group(), direct_link_image(), direct_link_ipo(), direct_link_key(), direct_link_lamp(), direct_link_latt(), direct_link_library(), direct_link_material(), direct_link_mball(), direct_link_mesh(), direct_link_movieclip(), direct_link_nodetree(), direct_link_object(), direct_link_particlesettings(), direct_link_scene(), direct_link_screen(), direct_link_script(), direct_link_sound(), direct_link_speaker(), direct_link_text(), direct_link_texture(), direct_link_vfont(), direct_link_windowmanager(), direct_link_world(), FD_FLAGS_SWITCH_ENDIAN, ID::flag, FileData::flags, GS, ID_AC, ID_AR, ID_BR, ID_CA, ID_CU, ID_GD, ID_GR, ID_ID, ID_IM, ID_IP, ID_KE, ID_LA, ID_LI, ID_LT, ID_MA, ID_MB, ID_MC, ID_ME, ID_NT, ID_OB, ID_PA, ID_SCE, ID_SCR, ID_SCRIPT, ID_SO, ID_SPK, ID_TE, ID_TXT, ID_VF, ID_WM, ID_WO, IDP_DirectLinkProperty(), LIB_FAKEUSER, LIB_ID_RECALC, LIB_ID_RECALC_DATA, LIB_NEEDLINK, FileData::libmap, ID::name, newdataadr(), BHead::old, oldnewmap_clear(), oldnewmap_free_unused(), oldnewmap_insert(), ID::properties, read_data_into_oldnewmap(), read_struct(), and which_libbase().
Referenced by append_id_part(), append_named_part(), blo_read_file_internal(), and expand_doit().
static void read_libraries (FileData * basefd, ListBase * mainlist) [static]
Definition at line 14760 of file readfile.c.
References append_id_part(), BKE_idcode_to_name(), BKE_reportf_wrap(), BLI_addtail(), BLI_remlink(), BLI_strncpy(), blo_freefiledata(), blo_openblenderfile(), change_idid_adr(), cleanup_path(), Main::curlib, do_versions(), expand_main(), FILE_MAX, Library::filedata, Library::filepath, FileData::fileversion, ListBase::first, ID::flag, G, GS, lib_link_all(), LIB_READ, FileData::libmap, FileData::mainlist, mainvar_count_libread_blocks(), MAX_LIBARRAY, MEM_freeN(), ID::name, Library::name, ID::next, Main::next, NULL, oldnewmap_free(), oldnewmap_new(), read_file_version(), FileData::reports, RPT_ERROR, RPT_INFO, set_listbasepointers(), and Main::versionfile.
Referenced by blo_read_file_internal(), and library_append_end().
static void * read_struct (FileData * fd, BHead * bh, const char * blockname) [static]
Definition at line 1394 of file readfile.c.
References FileData::compflags, DNA_struct_reconstruct(), FD_FLAGS_SWITCH_ENDIAN, FileData::filesdna, FileData::flags, BHead::len, MEM_mallocN(), FileData::memsdna, BHead::nr, NULL, BHead::SDNAnr, and switch_endian_structs().
Referenced by BLO_library_read_struct(), expand_doit(), read_data_into_oldnewmap(), read_file_version(), read_global(), read_libblock(), and read_userdef().
static BHead* read_userdef (BlendFileData * bfd, FileData * fd, BHead * bhead) [static]
Definition at line 13372 of file readfile.c.
References wmKeyMapDiffItem::add_item, UserDef::addons, FileData::datamap, wmKeyMap::diff_items, direct_link_keymapitem(), ListBase::first, wmKeyMap::flag, wmKeyMap::items, KEYMAP_UPDATE, ListBase::last, link_list(), wmKeyMap::modal_items, newdataadr(), wmKeyMap::next, wmKeyMapDiffItem::next, wmKeyMapItem::next, NULL, oldnewmap_clear(), oldnewmap_free_unused(), wmKeyMap::poll, read_data_into_oldnewmap(), read_struct(), wmKeyMapDiffItem::remove_item, UserDef::themes, UserDef::uifonts, UserDef::uistyles, BlendFileData::user, and UserDef::user_keymaps.
Referenced by blo_read_file_internal().
static void* restore_pointer_by_name (Main * mainp, ID * id, int user) [static]
Definition at line 5409 of file readfile.c.
References ListBase::first, GS, ID::lib, ID::name, ID::next, NULL, ID::us, and which_libbase().
Referenced by lib_link_screen_restore(), and lib_link_seq_clipboard_cb().
static void sequencer_init_preview_region (ARegion * ar) [static]
Definition at line 6894 of file readfile.c.
References View2D::align, ARegion::alignment, View2D::cur, ARegion::flag, View2D::keeptot, View2D::keepzoom, View2D::max, View2D::maxzoom, View2D::min, View2D::minzoom, ARegion::regiontype, RGN_ALIGN_TOP, RGN_FLAG_HIDDEN, RGN_TYPE_PREVIEW, View2D::tot, ARegion::v2d, V2D_ALIGN_FREE, V2D_KEEPASPECT, V2D_KEEPTOT_FREE, V2D_KEEPZOOM, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by area_add_window_regions(), and do_versions().
static void sort_bhead_old_map (FileData * fd) [static]
Definition at line 13525 of file readfile.c.
References bheadsort::bhead, FileData::bheadmap, blo_firstbhead(), blo_nextbhead(), MEM_mallocN(), BHead::old, bheadsort::old, FileData::tot_bheadmap, and verg_bheadsort().
Referenced by find_bhead().
static void split_libdata (ListBase * lb, Main * first) [static]
Definition at line 453 of file readfile.c.
References BLI_addtail(), BLI_remlink(), Main::curlib, ListBase::first, GS, ID::lib, ID::name, Main::next, ID::next, NULL, and which_libbase().
Referenced by blo_split_main().
static void switch_endian_bh4 (BHead4 * bhead) [static]
Definition at line 570 of file readfile.c.
References BHead4::code, ENDB, BHead4::len, BHead4::nr, BHead4::SDNAnr, and SWITCH_INT.
Referenced by get_bhead().
static void switch_endian_bh8 (BHead8 * bhead) [static]
Definition at line 582 of file readfile.c.
References BHead8::code, ENDB, BHead8::len, BHead8::nr, BHead8::SDNAnr, and SWITCH_INT.
Referenced by get_bhead().
static void switch_endian_keyblock (Key * key, KeyBlock * kb) [static]
Definition at line 2746 of file readfile.c.
References KeyBlock::data, data, Key::elemsize, Key::elemstr, IPO_BEZTRIPLE, IPO_BPOINT, IPO_FLOAT, SWITCH_INT, and KeyBlock::totelem.
Referenced by direct_link_key().
static void switch_endian_knots (Nurb * nu) [static]
Definition at line 3075 of file readfile.c.
References KNOTSU, Nurb::knotsu, KNOTSV, Nurb::knotsv, len(), and SWITCH_INT.
Referenced by direct_link_curve().
static void switch_endian_structs (struct SDNA * filesdna, BHead * bhead) [static]
Definition at line 1378 of file readfile.c.
References data, DNA_struct_switch_endian(), BHead::nr, BHead::SDNAnr, SDNA::structs, and SDNA::typelens.
Referenced by read_struct().
static void test_pointer_array (FileData * fd, void ** mat) [static]
Definition at line 1462 of file readfile.c.
References FD_FLAGS_SWITCH_ENDIAN, FileData::filesdna, FileData::flags, len(), MEM_allocN_len(), MEM_freeN(), MEM_mallocN(), FileData::memsdna, SDNA::pointerlen, and SWITCH_LONGINT.
Referenced by direct_link_curve(), direct_link_mball(), direct_link_mesh(), direct_link_object(), and IDP_DirectLinkArray().
static void vcol_to_fcol (Mesh * me) [static]
Definition at line 6498 of file readfile.c.
References Mesh::mcol, MEM_freeN(), MEM_mallocN(), Mesh::mface, NULL, Mesh::totface, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by do_versions().
static int verg_bheadsort (const void * v1, const void * v2) [static]
Definition at line 13516 of file readfile.c.
References bheadsort::old.
Referenced by find_bhead(), and sort_bhead_old_map().
static int verg_oldnewmap (const void * v1, const void * v2) [static]
Definition at line 290 of file readfile.c.
References OldNew::old.
Referenced by oldnewmap_liblookup(), and oldnewmap_sort().
static void versions_gpencil_add_main (ListBase * lb, ID * id, const char * name) [static]
Definition at line 7240 of file readfile.c.
References BLI_addtail(), G, G_DEBUG, ID_GD, LIB_FAKEUSER, ID::name, and new_id().
Referenced by do_versions_gpencil_2_50().
static void view3d_split_250 (View3D * v3d, ListBase * regions) [static]
Definition at line 5718 of file readfile.c.
References copy_qt_qt(), copy_v3_v3(), RegionView3D::dist, ListBase::first, MEM_callocN(), ARegion::next, NULL, RegionView3D::ofs, RegionView3D::persp, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, View3D::twtype, V3D_MANIP_TRANSLATE, RegionView3D::view, and RegionView3D::viewquat.
Referenced by area_add_window_regions(), and direct_link_screen().
Variable Documentation
const char* ptcache_data_struct[] [static]
Initial value:
 {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "BoidData"
}
Definition at line 3295 of file readfile.c.