Blender: NG_NetworkMessage Class Reference
NG_NetworkMessage Class Reference
#include <NG_NetworkMessage.h>
Public Member Functions
NG_NetworkMessage (const STR_String &to, const STR_String &from, const STR_String &subject, const STR_String &body)
void AddRef ()
void Release ()
void SetMessageText (const STR_String &msgtext)
const STR_String & GetDestinationName ()
const STR_String & GetSenderName ()
const STR_String & GetSubject ()
const STR_String & GetMessageText ()
const STR_String & GetMessageText () const
void SetSender (unsigned int ClientId)
unsigned int GetSender (void)
int GetMessageID ()
Protected Member Functions
~NG_NetworkMessage ()
Detailed Description
Definition at line 41 of file NG_NetworkMessage.h.
Constructor & Destructor Documentation
NG_NetworkMessage::~NG_NetworkMessage () [protected]
Definition at line 52 of file NG_NetworkMessage.cpp.
References assert.
NG_NetworkMessage::NG_NetworkMessage (const STR_String & to, const STR_String & from, const STR_String & subject, const STR_String & body)
Definition at line 38 of file NG_NetworkMessage.cpp.
Member Function Documentation
void NG_NetworkMessage::AddRef () [inline]
Definition at line 63 of file NG_NetworkMessage.h.
Referenced by NG_NetworkScene::FindMessages(), NG_NetworkScene::proceed(), and NG_LoopBackNetworkDeviceInterface::SendNetworkMessage().
const STR_String& NG_NetworkMessage::GetDestinationName () [inline]
get the (read-only) To part of this message
Definition at line 87 of file NG_NetworkMessage.h.
Referenced by NG_NetworkScene::proceed(), and NG_LoopBackNetworkDeviceInterface::SendNetworkMessage().
int NG_NetworkMessage::GetMessageID () [inline]
get the unique Network Message ID
Definition at line 128 of file NG_NetworkMessage.h.
const STR_String& NG_NetworkMessage::GetMessageText () const [inline]
Definition at line 106 of file NG_NetworkMessage.h.
const STR_String& NG_NetworkMessage::GetMessageText () [inline]
get the (read-only) Body part of this message
Definition at line 102 of file NG_NetworkMessage.h.
Referenced by NG_LoopBackNetworkDeviceInterface::SendNetworkMessage().
unsigned int NG_NetworkMessage::GetSender (void) [inline]
Get the NetworkMessage sender identifier
Definition at line 121 of file NG_NetworkMessage.h.
const STR_String& NG_NetworkMessage::GetSenderName () [inline]
get the (read-only) From part of this message
Definition at line 92 of file NG_NetworkMessage.h.
Referenced by NG_NetworkScene::proceed(), and NG_LoopBackNetworkDeviceInterface::SendNetworkMessage().
const STR_String& NG_NetworkMessage::GetSubject () [inline]
get the (read-only) Subject part of this message
Definition at line 97 of file NG_NetworkMessage.h.
Referenced by NG_NetworkScene::proceed(), and NG_LoopBackNetworkDeviceInterface::SendNetworkMessage().
void NG_NetworkMessage::Release () [inline]
Definition at line 69 of file NG_NetworkMessage.h.
Referenced by NG_NetworkScene::SendMessage(), and GPC_Engine::UpdateLoadingAnimation().
void NG_NetworkMessage::SetMessageText (const STR_String & msgtext) [inline]
set the content of this message
Definition at line 80 of file NG_NetworkMessage.h.
void NG_NetworkMessage::SetSender (unsigned int ClientId) [inline]
Set the NetworkMessage sender identifier
Definition at line 114 of file NG_NetworkMessage.h.
The documentation for this class was generated from the following files:
NG_NetworkMessage.h
NG_NetworkMessage.cpp