Blender: ImageBase.cpp File Reference
ImageBase.cpp File Reference
BGE Video Texture
#include "ImageBase.h"
#include "bgl.h"
#include "GL/glew.h"
#include <vector>
#include <string.h>
#include <PyObjectPlus.h>
#include <structmember.h>
#include "FilterBase.h"
#include "Exception.h"
Functions
ExpDesc ImageHasExportsDesc (ImageHasExports,"Image has exported buffers, cannot resize")
ExpDesc InvalidColorChannelDesc (InvalidColorChannel,"Invalid or too many color channels specified. At most 4 values within R, G, B, A, 0, 1")
PyObject * Image_allocNew (PyTypeObject *type, PyObject *args, PyObject *kwds)
void Image_dealloc (PyImage *self)
PyObject * Image_getImage (PyImage *self, char *mode)
PyObject * Image_getSize (PyImage *self, void *closure)
PyObject * Image_refresh (PyImage *self)
PyObject * Image_getScale (PyImage *self, void *closure)
int Image_setScale (PyImage *self, PyObject *value, void *closure)
PyObject * Image_getFlip (PyImage *self, void *closure)
int Image_setFlip (PyImage *self, PyObject *value, void *closure)
PyObject * Image_getSource (PyImage *self, PyObject *args)
PyObject * Image_setSource (PyImage *self, PyObject *args)
PyObject * Image_getFilter (PyImage *self, void *closure)
int Image_setFilter (PyImage *self, PyObject *value, void *closure)
PyObject * Image_valid (PyImage *self, void *closure)
int Image_getbuffer (PyImage *self, Py_buffer *view, int flags)
void Image_releaseBuffer (PyImage *self, Py_buffer *buffer)
Variables
ExceptionID ImageHasExports
ExceptionID InvalidColorChannel
PyTypeList pyImageTypes
PyBufferProcs imageBufferProcs
Detailed Description
Definition in file ImageBase.cpp.
Function Documentation
PyObject* Image_allocNew (PyTypeObject * type, PyObject * args, PyObject * kwds)
Definition at line 360 of file ImageBase.cpp.
References PyImage::m_image, and NULL.
void Image_dealloc (PyImage * self)
Definition at line 371 of file ImageBase.cpp.
References NULL.
int Image_getbuffer (PyImage * self, Py_buffer * view, int flags)
Definition at line 646 of file ImageBase.cpp.
References error(), KDL::exp(), NULL, and Exception::report().
PyObject* Image_getFilter (PyImage * self, void * closure)
Definition at line 595 of file ImageBase.cpp.
References NULL.
PyObject* Image_getFlip (PyImage * self, void * closure)
Definition at line 513 of file ImageBase.cpp.
References NULL.
PyObject* Image_getImage (PyImage * self, char * mode)
Definition at line 390 of file ImageBase.cpp.
References _Buffer::asbyte, BGL_MakeBuffer(), _Buffer::buf, KDL::exp(), i, NULL, Exception::report(), S_OK, and THRWEXCP.
Referenced by imageToArray().
PyObject* Image_getScale (PyImage * self, void * closure)
Definition at line 491 of file ImageBase.cpp.
References NULL.
PyObject* Image_getSize (PyImage * self, void * closure)
Definition at line 477 of file ImageBase.cpp.
PyObject* Image_getSource (PyImage * self, PyObject * args)
Definition at line 536 of file ImageBase.cpp.
References NULL.
PyObject* Image_refresh (PyImage * self)
Definition at line 484 of file ImageBase.cpp.
void Image_releaseBuffer (PyImage * self, Py_buffer * buffer)
Definition at line 693 of file ImageBase.cpp.
int Image_setFilter (PyImage * self, PyObject * value, void * closure)
Definition at line 616 of file ImageBase.cpp.
References PyTypeList::in(), NULL, and pyFilterTypes.
int Image_setFlip (PyImage * self, PyObject * value, void * closure)
Definition at line 520 of file ImageBase.cpp.
References NULL.
int Image_setScale (PyImage * self, PyObject * value, void * closure)
Definition at line 498 of file ImageBase.cpp.
References NULL.
PyObject* Image_setSource (PyImage * self, PyObject * args)
Definition at line 560 of file ImageBase.cpp.
References PyTypeList::in(), and NULL.
PyObject* Image_valid (PyImage * self, void * closure)
Definition at line 634 of file ImageBase.cpp.
ExpDesc ImageHasExportsDesc (ImageHasExports , "Image has exported buffers, cannot resize")
ExpDesc InvalidColorChannelDesc (InvalidColorChannel , "Invalid or too many color channels specified. At most 4 values within R, G , B , A , 0 , 1")
Variable Documentation
PyBufferProcs imageBufferProcs
Initial value:
{
    (getbufferproc)Image_getbuffer,
    (releasebufferproc)Image_releaseBuffer
}
Definition at line 698 of file ImageBase.cpp.
ExceptionID ImageHasExports
Definition at line 176 of file ImageBase.cpp.
ExceptionID InvalidColorChannel
Definition at line 177 of file ImageBase.cpp.
PyTypeList pyImageTypes
Definition at line 353 of file ImageBase.cpp.
Referenced by imageToArray(), initVideoTexture(), registerAllTypes(), and Texture_setSource().