Blender: RAS_2DFilterManager Class Reference
RAS_2DFilterManager Class Reference
#include <RAS_2DFilterManager.h>
Public Types
enum RAS_2DFILTER_MODE {
RAS_2DFILTER_ENABLED = -2, RAS_2DFILTER_DISABLED = -1, RAS_2DFILTER_NOFILTER = 0, RAS_2DFILTER_MOTIONBLUR,
RAS_2DFILTER_BLUR, RAS_2DFILTER_SHARPEN, RAS_2DFILTER_DILATION, RAS_2DFILTER_EROSION,
RAS_2DFILTER_LAPLACIAN, RAS_2DFILTER_SOBEL, RAS_2DFILTER_PREWITT, RAS_2DFILTER_GRAYSCALE,
RAS_2DFILTER_SEPIA, RAS_2DFILTER_INVERT, RAS_2DFILTER_CUSTOMFILTER, RAS_2DFILTER_NUMBER_OF_FILTERS
}
Public Member Functions
RAS_2DFilterManager ()
~RAS_2DFilterManager ()
void RenderFilters (RAS_ICanvas *canvas)
void EnableFilter (std::vector< STR_String > &propNames, void *gameObj, RAS_2DFILTER_MODE mode, int pass, STR_String &text)
Detailed Description
Definition at line 42 of file RAS_2DFilterManager.h.
Member Enumeration Documentation
enum RAS_2DFilterManager::RAS_2DFILTER_MODE
Enumerator:
RAS_2DFILTER_ENABLED
RAS_2DFILTER_DISABLED
RAS_2DFILTER_NOFILTER
RAS_2DFILTER_MOTIONBLUR
RAS_2DFILTER_BLUR
RAS_2DFILTER_SHARPEN
RAS_2DFILTER_DILATION
RAS_2DFILTER_EROSION
RAS_2DFILTER_LAPLACIAN
RAS_2DFILTER_SOBEL
RAS_2DFILTER_PREWITT
RAS_2DFILTER_GRAYSCALE
RAS_2DFILTER_SEPIA
RAS_2DFILTER_INVERT
RAS_2DFILTER_CUSTOMFILTER
RAS_2DFILTER_NUMBER_OF_FILTERS
Definition at line 83 of file RAS_2DFilterManager.h.
Constructor & Destructor Documentation
RAS_2DFilterManager::RAS_2DFilterManager ()
Definition at line 53 of file RAS_2DFilterManager.cpp.
References MAX_RENDER_PASS, and NULL.
RAS_2DFilterManager::~RAS_2DFilterManager ()
Definition at line 77 of file RAS_2DFilterManager.cpp.
Member Function Documentation
void RAS_2DFilterManager::EnableFilter (std::vector< STR_String > & propNames, void * gameObj, RAS_2DFILTER_MODE mode, int pass, STR_String & text)
Definition at line 476 of file RAS_2DFilterManager.cpp.
References MAX_RENDER_PASS, NULL, STR_String::Ptr(), RAS_2DFILTER_CUSTOMFILTER, RAS_2DFILTER_DISABLED, RAS_2DFILTER_ENABLED, and RAS_2DFILTER_NOFILTER.
Referenced by KX_Scene::Update2DFilter().
void RAS_2DFilterManager::RenderFilters (RAS_ICanvas * canvas)
Definition at line 374 of file RAS_2DFilterManager.cpp.
References RAS_ICanvas::GetHeight(), RAS_ICanvas::GetWidth(), and MAX_RENDER_PASS.
Referenced by KX_Scene::Render2DFilters().
The documentation for this class was generated from the following files:
RAS_2DFilterManager.h
RAS_2DFilterManager.cpp