Blender: svm_texture.h File Reference
svm_texture.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float voronoi_distance (NodeDistanceMetric distance_metric, float3 d, float e)
__device_noinline void voronoi (float3 p, NodeDistanceMetric distance_metric, float e, float da[4], float3 pa[4])
__device float voronoi_Fn (float3 p, int n)
__device float voronoi_FnFn (float3 p, int n1, int n2)
__device float voronoi_F1 (float3 p)
__device float voronoi_F2 (float3 p)
__device float voronoi_F3 (float3 p)
__device float voronoi_F4 (float3 p)
__device float voronoi_F1F2 (float3 p)
__device float voronoi_Cr (float3 p)
__device float voronoi_F1S (float3 p)
__device float voronoi_F2S (float3 p)
__device float voronoi_F3S (float3 p)
__device float voronoi_F4S (float3 p)
__device float voronoi_F1F2S (float3 p)
__device float voronoi_CrS (float3 p)
__device float noise_basis (float3 p, NodeNoiseBasis basis)
__device float noise_basis_hard (float3 p, NodeNoiseBasis basis, int hard)
__device float noise_wave (NodeWaveType wave, float a)
__device_noinline float noise_turbulence (float3 p, NodeNoiseBasis basis, float octaves, int hard)
Function Documentation
__device float noise_basis (float3 p, NodeNoiseBasis basis)
Definition at line 152 of file svm_texture.h.
References cellnoise(), NODE_NOISE_CELL_NOISE, NODE_NOISE_PERLIN, NODE_NOISE_VORONOI_CRACKLE, NODE_NOISE_VORONOI_F1, NODE_NOISE_VORONOI_F2, NODE_NOISE_VORONOI_F2_F1, NODE_NOISE_VORONOI_F3, NODE_NOISE_VORONOI_F4, noise(), voronoi_CrS(), voronoi_F1F2S(), voronoi_F1S(), voronoi_F2S(), voronoi_F3S(), and voronoi_F4S().
__device float noise_basis_hard (float3 p, NodeNoiseBasis basis, int hard)
Definition at line 183 of file svm_texture.h.
References fabsf, and noise_basis().
__device_noinline float noise_turbulence (float3 p, NodeNoiseBasis basis, float octaves, int hard)
Definition at line 216 of file svm_texture.h.
References clamp, fabsf, i, noise_basis(), and sum().
__device float noise_wave (NodeWaveType wave, float a)
Definition at line 191 of file svm_texture.h.
References fabsf, floorf, M_PI_F, NODE_WAVE_SAW, NODE_WAVE_SINE, NODE_WAVE_TRI, and sin().
__device_noinline void voronoi (float3 p, NodeDistanceMetric distance_metric, float e, float da[4], float3 pa[4])
Definition at line 45 of file svm_texture.h.
References cellnoise_color(), floorf, make_float3(), voronoi_distance(), float3::x, float3::y, and float3::z.
__device float voronoi_Cr (float3 p)
Definition at line 136 of file svm_texture.h.
References voronoi_F1F2().
__device float voronoi_CrS (float3 p)
Definition at line 148 of file svm_texture.h.
References voronoi_Cr().
CCL_NAMESPACE_BEGIN __device float voronoi_distance (NodeDistanceMetric distance_metric, float3 d, float e)
Definition at line 23 of file svm_texture.h.
References dot(), fabsf, fmaxf, len(), NODE_VORONOI_ACTUAL_DISTANCE, NODE_VORONOI_CHEBYCHEV, NODE_VORONOI_DISTANCE_SQUARED, NODE_VORONOI_MANHATTAN, NODE_VORONOI_MINKOVSKY, NODE_VORONOI_MINKOVSKY_4, NODE_VORONOI_MINKOVSKY_H, powf, sqrtf, float3::x, float3::y, and float3::z.
__device float voronoi_F1 (float3 p)
Definition at line 130 of file svm_texture.h.
References voronoi_Fn().
__device float voronoi_F1F2 (float3 p)
Definition at line 134 of file svm_texture.h.
References voronoi_FnFn().
__device float voronoi_F1F2S (float3 p)
Definition at line 147 of file svm_texture.h.
References voronoi_F1F2().
__device float voronoi_F1S (float3 p)
Definition at line 143 of file svm_texture.h.
References voronoi_F1().
__device float voronoi_F2 (float3 p)
Definition at line 131 of file svm_texture.h.
References voronoi_Fn().
__device float voronoi_F2S (float3 p)
Definition at line 144 of file svm_texture.h.
References voronoi_F2().
__device float voronoi_F3 (float3 p)
Definition at line 132 of file svm_texture.h.
References voronoi_Fn().
__device float voronoi_F3S (float3 p)
Definition at line 145 of file svm_texture.h.
References voronoi_F3().
__device float voronoi_F4 (float3 p)
Definition at line 133 of file svm_texture.h.
References voronoi_Fn().
__device float voronoi_F4S (float3 p)
Definition at line 146 of file svm_texture.h.
References voronoi_F4().
__device float voronoi_Fn (float3 p, int n)
Definition at line 110 of file svm_texture.h.
References NODE_VORONOI_DISTANCE_SQUARED, and voronoi().
__device float voronoi_FnFn (float3 p, int n1, int n2)
Definition at line 120 of file svm_texture.h.
References NODE_VORONOI_DISTANCE_SQUARED, and voronoi().