Blender: ImageManager Class Reference
ImageManager Class Reference
#include <image.h>
Classes
struct Image
Public Member Functions
ImageManager ()
~ImageManager ()
int add_image (const string &filename, bool &is_float)
void remove_image (const string &filename)
void device_update (Device *device, DeviceScene *dscene, Progress &progress)
void device_free (Device *device, DeviceScene *dscene)
void set_osl_texture_system (void *texture_system)
Public Attributes
bool need_update
Detailed Description
Definition at line 38 of file image.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN ImageManager::ImageManager ()
Definition at line 34 of file image.cpp.
References need_update, and NULL.
ImageManager::~ImageManager ()
Definition at line 40 of file image.cpp.
References assert.
Member Function Documentation
int ImageManager::add_image (const string & filename, bool & is_float)
Definition at line 87 of file image.cpp.
References is_float_image(), need_update, TEX_IMAGE_FLOAT_START, TEX_NUM_FLOAT_IMAGES, and TEX_NUM_IMAGES.
void ImageManager::device_free (Device * device, DeviceScene * dscene)
Definition at line 470 of file image.cpp.
References TEX_IMAGE_FLOAT_START.
Referenced by Scene::~Scene().
void ImageManager::device_update (Device * device, DeviceScene * dscene, Progress & progress)
Definition at line 430 of file image.cpp.
References Progress::get_cancel(), need_update, path_filename(), Progress::set_status(), and TEX_IMAGE_FLOAT_START.
Referenced by Scene::device_update().
void ImageManager::remove_image (const string & filename)
Definition at line 163 of file image.cpp.
References assert, and need_update.
Referenced by EnvironmentTextureNode::~EnvironmentTextureNode(), and ImageTextureNode::~ImageTextureNode().
void ImageManager::set_osl_texture_system (void * texture_system)
Definition at line 48 of file image.cpp.
Member Data Documentation
bool ImageManager::need_update
Definition at line 51 of file image.h.
Referenced by add_image(), device_update(), ImageManager(), Scene::need_reset(), and remove_image().
The documentation for this class was generated from the following files:
image.h
image.cpp