Blender: editderivedmesh.c File Reference
editderivedmesh.c File Reference
blenkernel
#include <string.h>
#include <limits.h>
#include <math.h>
#include "GL/glew.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_edgehash.h"
#include "BLI_math.h"
#include "BLI_pbvh.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_global.h"
#include "BKE_mesh.h"
#include "BKE_paint.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
#include "GPU_buffers.h"
#include "GPU_draw.h"
#include "GPU_extensions.h"
#include "GPU_material.h"
#include "BKE_tessmesh.h"
#include "BLI_array.h"
#include "BLI_scanfill.h"
#include "bmesh.h"
Classes
struct EditDerivedBMesh
Defines
#define USE_TESSFACE_SPEEDUP
#define PASSATTRIB(loop, eve, vert)
#define PASSATTRIB(loop, eve, vert)
Typedefs
typedef struct EditDerivedBMesh EditDerivedBMesh
Functions
BMEditMesh * BMEdit_Create (BMesh *bm, int do_tessellate)
BMEditMesh * BMEdit_Copy (BMEditMesh *tm)
static void BMEdit_RecalcTessellation_intern (BMEditMesh *tm)
void BMEdit_RecalcTessellation (BMEditMesh *em)
void BMEdit_UpdateLinkedCustomData (BMEditMesh *em)
void BMEdit_Free (BMEditMesh *em)
static void emDM_calcNormals (DerivedMesh *UNUSED(dm))
static void emDM_recalcTessellation (DerivedMesh *UNUSED(dm))
static void emDM_foreachMappedVert (DerivedMesh *dm, void(*func)(void *userData, int index, const float co[3], const float no_f[3], const short no_s[3]), void *userData)
static void emDM_foreachMappedEdge (DerivedMesh *dm, void(*func)(void *userData, int index, const float v0co[3], const float v1co[3]), void *userData)
static void emDM_drawMappedEdges (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, void *userData)
static void emDM_drawEdges (DerivedMesh *dm, int UNUSED(drawLooseEdges), int UNUSED(drawAllEdges))
static void emDM_drawMappedEdgesInterp (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetDrawInterpOptions setDrawInterpOptions, void *userData)
static void emDM_drawUVEdges (DerivedMesh *dm)
static void emDM__calcFaceCent (BMesh *bm, BMFace *efa, float cent[3], float(*vertexCos)[3])
static void emDM_foreachMappedFaceCenter (DerivedMesh *dm, void(*func)(void *userData, int index, const float co[3], const float no[3]), void *userData)
static void emDM_drawMappedFaces (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void *userData, DMDrawFlag flag)
static void bmdm_get_tri_tex (BMesh *bm, BMLoop **ls, MLoopUV *luv[3], MLoopCol *lcol[3], int has_uv, int has_col)
static void emDM_drawFacesTex_common (DerivedMesh *dm, DMSetDrawOptionsTex drawParams, DMSetDrawOptions drawParamsMapped, DMCompareDrawOptions compareDrawOptions, void *userData)
static void emDM_drawFacesTex (DerivedMesh *dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
static void emDM_drawMappedFacesTex (DerivedMesh *dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void *userData)
static void emDM_drawMappedFacesGLSL (DerivedMesh *dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void *userData)
static void emDM_drawFacesGLSL (DerivedMesh *dm, int(*setMaterial)(int, void *attribs))
static void emDM_drawMappedFacesMat (DerivedMesh *dm, void(*setMaterial)(void *userData, int, void *attribs), int(*setFace)(void *userData, int index), void *userData)
static void emDM_getMinMax (DerivedMesh *dm, float min_r[3], float max_r[3])
static int emDM_getNumVerts (DerivedMesh *dm)
static int emDM_getNumEdges (DerivedMesh *dm)
static int emDM_getNumTessFaces (DerivedMesh *dm)
static int emDM_getNumLoops (DerivedMesh *dm)
static int emDM_getNumPolys (DerivedMesh *dm)
static int bmvert_to_mvert (BMesh *bm, BMVert *ev, MVert *vert_r)
static void emDM_getVert (DerivedMesh *dm, int index, MVert *vert_r)
static void emDM_getEdge (DerivedMesh *dm, int index, MEdge *edge_r)
static void emDM_getTessFace (DerivedMesh *dm, int index, MFace *face_r)
static void emDM_copyVertArray (DerivedMesh *dm, MVert *vert_r)
static void emDM_copyEdgeArray (DerivedMesh *dm, MEdge *edge_r)
static void emDM_copyTessFaceArray (DerivedMesh *dm, MFace *face_r)
static void emDM_copyLoopArray (DerivedMesh *dm, MLoop *loop_r)
static void emDM_copyPolyArray (DerivedMesh *dm, MPoly *poly_r)
static void * emDM_getTessFaceDataArray (DerivedMesh *dm, int type)
static void emDM_getVertCos (DerivedMesh *dm, float(*cos_r)[3])
static void emDM_release (DerivedMesh *dm)
static CustomData * bmDm_getVertDataLayout (DerivedMesh *dm)
static CustomData * bmDm_getEdgeDataLayout (DerivedMesh *dm)
static CustomData * bmDm_getTessFaceDataLayout (DerivedMesh *dm)
static CustomData * bmDm_getLoopDataLayout (DerivedMesh *dm)
static CustomData * bmDm_getPolyDataLayout (DerivedMesh *dm)
DerivedMesh * getEditDerivedBMesh (BMEditMesh *em, Object *UNUSED(ob), float(*vertexCos)[3])
BMEditMesh * BMEdit_FromObject (Object *ob)
Return the BMEditMesh for a given object.
Variables
GLubyte stipple_quarttone [128]
Detailed Description
Definition in file editderivedmesh.c.
Define Documentation
#define PASSATTRIB (loop, eve, vert)
Value:
{                                           \
    if (attribs.totorco) {                                                      \
        float *orco = attribs.orco.array[BM_elem_index_get(eve)];                       \
        glVertexAttrib3fvARB(attribs.orco.glIndex, orco);                       \
    }                                                                           \
    for (b = 0; b < attribs.tottface; b++) {                                    \
        MLoopUV *_luv = CustomData_bmesh_get_n(&bm->ldata, loop->head.data, CD_MLOOPUV, b);\
        glVertexAttrib2fvARB(attribs.tface[b].glIndex, _luv->uv);               \
    }                                                                           \
    for (b = 0; b < attribs.totmcol; b++) {                                     \
        MLoopCol *_cp = CustomData_bmesh_get_n(&bm->ldata, loop->head.data, CD_MLOOPCOL, b);\
        GLubyte _col[4];                                                        \
        _col[0]= _cp->b; _col[1]= _cp->g; _col[2]= _cp->r; _col[3]= _cp->a;     \
        glVertexAttrib4ubvARB(attribs.mcol[b].glIndex, _col);                   \
    }                                                                           \
    if (attribs.tottang) {                                                      \
        float *tang = attribs.tang.array[i*4 + vert];                           \
        glVertexAttrib3fvARB(attribs.tang.glIndex, tang);                       \
    }                                                                           \
    }
Referenced by ccgDM_drawMappedFacesGLSL(), ccgDM_drawMappedFacesMat(), emDM_drawMappedFacesGLSL(), and emDM_drawMappedFacesMat().
#define PASSATTRIB (loop, eve, vert)
Value:
{                                           \
    if (attribs.totorco) {                                                      \
        float *orco = attribs.orco.array[BM_elem_index_get(eve)];               \
        if (attribs.orco.glTexco)                                               \
            glTexCoord3fv(orco);                                                \
        else                                                                    \
            glVertexAttrib3fvARB(attribs.orco.glIndex, orco);                   \
    }                                                                           \
    for (b = 0; b < attribs.tottface; b++) {                                    \
        MLoopUV *_luv = CustomData_bmesh_get_n(&bm->ldata, loop->head.data, CD_MLOOPUV, b);\
        if (attribs.tface[b].glTexco)                                           \
            glTexCoord2fv(_luv->uv);                                            \
        else                                                                    \
            glVertexAttrib2fvARB(attribs.tface[b].glIndex, _luv->uv);           \
    }                                                                           \
    for (b = 0; b < attribs.totmcol; b++) {                                     \
        MLoopCol *_cp = CustomData_bmesh_get_n(&bm->ldata, loop->head.data, CD_MLOOPCOL, b);\
        GLubyte _col[4];                                                        \
        _col[0]= _cp->b; _col[1]= _cp->g; _col[2]= _cp->r; _col[3]= _cp->a;     \
        glVertexAttrib4ubvARB(attribs.mcol[b].glIndex, _col);                   \
    }                                                                           \
    if (attribs.tottang) {                                                      \
        float *tang = attribs.tang.array[i*4 + vert];                           \
        glVertexAttrib4fvARB(attribs.tang.glIndex, tang);                       \
    }                                                                           \
}
#define USE_TESSFACE_SPEEDUP
Typedef Documentation
typedef struct EditDerivedBMesh EditDerivedBMesh
Function Documentation
static void bmdm_get_tri_tex (BMesh * bm, BMLoop ** ls, MLoopUV * luv[3], MLoopCol * lcol[3], int has_uv, int has_col) [static]
Definition at line 768 of file editderivedmesh.c.
References CD_MLOOPCOL, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, and BMesh::ldata.
Referenced by emDM_drawFacesTex_common().
static CustomData* bmDm_getEdgeDataLayout (DerivedMesh * dm) [static]
Definition at line 1596 of file editderivedmesh.c.
References BMEditMesh::bm, BMesh::edata, and EditDerivedBMesh::tc.
Referenced by getEditDerivedBMesh().
static CustomData* bmDm_getLoopDataLayout (DerivedMesh * dm) [static]
Definition at line 1610 of file editderivedmesh.c.
References BMEditMesh::bm, BMesh::ldata, and EditDerivedBMesh::tc.
Referenced by getEditDerivedBMesh().
static CustomData* bmDm_getPolyDataLayout (DerivedMesh * dm) [static]
Definition at line 1617 of file editderivedmesh.c.
References BMEditMesh::bm, BMesh::pdata, and EditDerivedBMesh::tc.
Referenced by getEditDerivedBMesh().
static CustomData* bmDm_getTessFaceDataLayout (DerivedMesh * dm) [static]
Definition at line 1603 of file editderivedmesh.c.
References EditDerivedBMesh::dm, and DerivedMesh::faceData.
Referenced by getEditDerivedBMesh().
static CustomData* bmDm_getVertDataLayout (DerivedMesh * dm) [static]
Definition at line 1589 of file editderivedmesh.c.
References BMEditMesh::bm, EditDerivedBMesh::tc, and BMesh::vdata.
Referenced by getEditDerivedBMesh().
BMEditMesh* BMEdit_Copy (BMEditMesh * tm)
Definition at line 84 of file editderivedmesh.c.
References BMEditMesh::bm, BM_mesh_copy(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, BMEditMesh::edge_index, BMEditMesh::face_index, BMEditMesh::looptris, MEM_callocN(), NULL, and BMEditMesh::vert_index.
Referenced by EDBM_op_call_and_selectf(), EDBM_op_call_silentf(), EDBM_op_callf(), and EDBM_op_init().
BMEditMesh* BMEdit_Create (BMesh * bm, int do_tessellate)
Definition at line 72 of file editderivedmesh.c.
References BMEditMesh::bm, BMEdit_RecalcTessellation(), and MEM_callocN().
Referenced by bm_mdisps_space_set(), DM_to_editbmesh(), EDBM_mesh_make(), and undoMesh_to_editbtMesh().
void BMEdit_Free (BMEditMesh * em)
Definition at line 290 of file editderivedmesh.c.
References BMEditMesh::bm, BM_mesh_free(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, BMEditMesh::edge_index, BMEditMesh::face_index, BMEditMesh::looptris, MEM_freeN(), DerivedMesh::needsFree, NULL, DerivedMesh::release, and BMEditMesh::vert_index.
Referenced by applyModifier(), arrayModifier_doArray(), bm_mdisps_space_set(), doEdgeSplit(), EDBM_mesh_free(), and EDBM_op_finish().
BMEditMesh* BMEdit_FromObject (Object * ob)
Return the BMEditMesh for a given object.
Note:
this function assumes this is a mesh object, don't add NULL data check here. caller must do that
Definition at line 1744 of file editderivedmesh.c.
References BLI_assert, Object::data, OB_MESH, and Object::type.
Referenced by average_islands_scale_exec(), border_select_exec(), calc_manipulator_stats(), calculateCenter(), circle_select_exec(), createRepresentation(), createTransEdge(), createTransEditVerts(), createTransUVs(), cube_project_exec(), cylinder_project_exec(), do_lasso_select_mesh(), do_uvedit_vertex(), do_view3d_header_buttons(), draw_uvs_shadow(), ED_object_enter_editmode(), ED_operator_editmesh(), ED_operator_uvmap(), ED_space_image_show_uvedit(), ED_space_image_show_uvshadow(), ED_unwrap_lscm(), ED_uvedit_assign_image(), ED_uvedit_ensure_uvs(), ED_uvedit_live_unwrap(), ED_uvedit_live_unwrap_begin(), ED_uvedit_median(), ED_uvedit_minmax(), ED_uvedit_nearest_uv(), ED_uvedit_test(), ED_vgroup_object_is_edit_mode(), edbm_add_edge_face_exec(), EDBM_automerge(), edbm_beautify_fill_exec(), edbm_bevel_exec(), edbm_bridge_edge_loops_exec(), edbm_collapse_edge_exec(), edbm_collapse_edge_loop_exec(), edbm_delete_exec(), edbm_dissolve_exec(), edbm_dissolve_limited_exec(), edbm_do_smooth_vertex_exec(), edbm_duplicate_exec(), edbm_edge_rotate_selected_exec(), edbm_edge_split_exec(), edbm_extrude_edges_exec(), edbm_extrude_faces_exec(), edbm_extrude_region_exec(), edbm_extrude_repeat_exec(), edbm_extrude_verts_exec(), edbm_faces_select_interior_exec(), edbm_faces_shade_flat_exec(), edbm_faces_shade_smooth_exec(), edbm_fill_exec(), edbm_flip_normals_exec(), edbm_hide_exec(), edbm_inset_exec(), edbm_knife_cut_exec(), edbm_loop_multiselect_exec(), edbm_loop_to_region_exec(), edbm_mark_seam(), edbm_mark_sharp(), edbm_merge_exec(), edbm_noise_exec(), edbm_normals_make_consistent_exec(), edbm_quads_convert_to_tris_exec(), edbm_region_to_loop_exec(), edbm_remove_doubles_exec(), edbm_reveal_exec(), edbm_reverse_colors_exec(), edbm_reverse_uvs_exec(), edbm_rip_invoke(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), edbm_rotate_colors_exec(), edbm_rotate_uvs_exec(), edbm_screw_exec(), edbm_select_all_exec(), edbm_select_axis_exec(), edbm_select_by_number_vertices_exec(), edbm_select_less_exec(), edbm_select_linked_exec(), edbm_select_linked_flat_faces_exec(), edbm_select_loose_verts_exec(), edbm_select_mirror_exec(), edbm_select_more_exec(), edbm_select_next_loop_exec(), edbm_select_non_manifold_exec(), edbm_select_nth_exec(), edbm_select_random_exec(), edbm_select_sharp_edges_exec(), edbm_select_vertex_path_exec(), EDBM_selectmode_to_scene(), edbm_separate_exec(), edbm_shortest_path_select_poll(), edbm_spin_exec(), edbm_split_exec(), edbm_subdivide_exec(), edbm_tris_convert_to_quads_exec(), edbm_vert_connect(), edbm_vertex_slide_exec(), edbm_vertices_randomize_exec(), hide_exec(), knifetool_init(), knifetool_modal(), linked_limit_default(), make_prim_finish(), material_slot_assign_exec(), material_slot_de_select(), merge_type_itemf(), mesh_circle_select(), mesh_separate_loose(), mesh_separate_material(), minimize_stretch_init(), mouse_select(), navmesh_face_add_exec(), navmesh_face_copy_exec(), object_handle_update(), pack_islands_exec(), peelObjects(), pin_exec(), recalcData_view3d(), reveal_exec(), ringsel_init(), select_all_exec(), select_linked_internal(), select_pinned_exec(), select_similar_type_itemf(), shape_itemf(), similar_edge_select_exec(), similar_face_select_exec(), similar_vert_select_exec(), snap_uvs_to_adjacent_unselected(), snap_uvs_to_cursor(), snap_uvs_to_pixels(), snapObject(), special_aftertrans_update(), sphere_project_exec(), stats_object_edit(), stitch_init(), uiTemplateEditModeSelection(), undo_push_mesh(), unlink_selection_exec(), unwrap_exec(), uv_faces_do_sticky(), uv_from_view_exec(), uv_map_transform(), uv_sculpt_brush_poll(), uv_sculpt_stroke_apply(), uv_sculpt_stroke_init(), uvedit_set_tile(), uvedit_vertex_buttons(), vgroup_blend(), vgroup_do_remap(), vgroup_object_in_edit_mode(), view3d_borderselect_exec(), vtx_slide_confirm(), vtx_slide_init(), and weld_align_uv().
void BMEdit_RecalcTessellation (BMEditMesh * em)
Definition at line 250 of file editderivedmesh.c.
References BMEdit_RecalcTessellation_intern(), BMEditMesh::derivedCage, BMEditMesh::derivedFinal, and DerivedMesh::recalcTessellation.
Referenced by BMBVH_NewBVH(), BME_bevel(), BMEdit_Create(), DM_to_editbmesh(), ED_mesh_calc_tessface(), ED_object_enter_editmode(), EDBM_automerge(), EDBM_op_finish(), EDBM_update_generic(), and recalcData_view3d().
static void BMEdit_RecalcTessellation_intern (BMEditMesh * tm) [static]
Definition at line 109 of file editderivedmesh.c.
References BLI_addfilledge(), BLI_addfillvert(), BLI_array_declare, BLI_array_growitems, BLI_array_growone, BLI_array_reserve, BLI_begin_edgefill(), BLI_edgefill_ex(), BLI_end_edgefill(), BMEditMesh::bm, BM_elem_index_get, BM_elem_index_set, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BMVert::co, FALSE, ScanFillContext::fillfacebase, ListBase::first, i, BMFace::len, BMEditMesh::looptris, MEM_freeN(), ScanFillFace::next, BMFace::no, NULL, ScanFillVert::p, SWAP, ScanFillVert::tmp, BMesh::totface, BMEditMesh::tottri, BMLoop::v, ScanFillFace::v1, ScanFillFace::v2, and ScanFillFace::v3.
Referenced by BMEdit_RecalcTessellation().
void BMEdit_UpdateLinkedCustomData (BMEditMesh * em)
Definition at line 269 of file editderivedmesh.c.
References BMEditMesh::bm, CD_MLOOPUV, CD_MTEXPOLY, CustomData_get_active_layer(), CustomData_get_clone_layer(), CustomData_get_render_layer(), CustomData_get_stencil_layer(), CustomData_has_layer(), CustomData_set_layer_active(), CustomData_set_layer_clone(), CustomData_set_layer_render(), CustomData_set_layer_stencil(), BMesh::ldata, and BMesh::pdata.
Referenced by mesh_update_linked_customdata().
static int bmvert_to_mvert (BMesh * bm, BMVert * ev, MVert * vert_r) [static]
Definition at line 1294 of file editderivedmesh.c.
References BM_elem_float_data_get(), BM_vert_flag_to_mflag(), MVert::bweight, CD_BWEIGHT, MVert::co, BMVert::co, copy_v3_v3(), CustomData_has_layer(), MVert::flag, MVert::no, BMVert::no, normal_float_to_short_v3(), and BMesh::vdata.
Referenced by emDM_getVert().
static void emDM__calcFaceCent (BMesh * bm, BMFace * efa, float cent[3], float(*) vertexCos[3]) [static]
Definition at line 526 of file editderivedmesh.c.
References add_v3_v3(), BM_elem_index_get, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BMVert::co, mul_v3_fl(), BMLoop::v, and zero_v3().
Referenced by emDM_foreachMappedFaceCenter().
static void emDM_calcNormals (DerivedMesh * UNUSEDdm) [static]
Definition at line 344 of file editderivedmesh.c.
Referenced by getEditDerivedBMesh().
static void emDM_copyEdgeArray (DerivedMesh * dm, MEdge * edge_r) [static]
Definition at line 1406 of file editderivedmesh.c.
References BM_edge_flag_to_mflag(), BM_EDGES_OF_MESH, BM_elem_float_data_get(), BM_elem_index_get, BM_iter_new(), BM_iter_step(), BM_mesh_elem_index_ensure(), BM_VERT, MEdge::bweight, CD_BWEIGHT, CD_CREASE, MEdge::crease, CustomData_has_layer(), BMesh::edata, MEdge::flag, NULL, BMEdge::v1, MEdge::v1, BMEdge::v2, and MEdge::v2.
Referenced by getEditDerivedBMesh().
static void emDM_copyLoopArray (DerivedMesh * dm, MLoop * loop_r) [static]
Definition at line 1461 of file editderivedmesh.c.
References BMEditMesh::bm, BM_EDGE, BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, MLoop::e, BMLoop::e, BMLoop::f, EditDerivedBMesh::tc, MLoop::v, and BMLoop::v.
Referenced by getEditDerivedBMesh().
static void emDM_copyPolyArray (DerivedMesh * dm, MPoly * poly_r) [static]
Definition at line 1480 of file editderivedmesh.c.
References BMEditMesh::bm, BM_face_flag_to_mflag(), BM_FACES_OF_MESH, BM_ITER_MESH, BMLoop::f, MPoly::flag, i, BMFace::len, MPoly::loopstart, BMFace::mat_nr, MPoly::mat_nr, EditDerivedBMesh::tc, and MPoly::totloop.
Referenced by getEditDerivedBMesh().
static void emDM_copyTessFaceArray (DerivedMesh * dm, MFace * face_r) [static]
Definition at line 1433 of file editderivedmesh.c.
References BMEditMesh::bm, BM_elem_index_get, BM_face_flag_to_mflag(), BM_mesh_elem_index_ensure(), BM_VERT, BMLoop::f, MFace::flag, i, BMEditMesh::looptris, BMFace::mat_nr, MFace::mat_nr, NULL, EditDerivedBMesh::tc, test_index_face(), BMEditMesh::tottri, BMLoop::v, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by getEditDerivedBMesh().
static void emDM_copyVertArray (DerivedMesh * dm, MVert * vert_r) [static]
Definition at line 1381 of file editderivedmesh.c.
References BMEditMesh::bm, BM_elem_float_data_get(), BM_iter_new(), BM_iter_step(), BM_vert_flag_to_mflag(), BM_VERTS_OF_MESH, MVert::bweight, CD_BWEIGHT, MVert::co, BMVert::co, copy_v3_v3(), CustomData_has_layer(), MVert::flag, i, MVert::no, BMVert::no, normal_float_to_short_v3(), NULL, EditDerivedBMesh::tc, BMesh::vdata, and EditDerivedBMesh::vertexCos.
Referenced by getEditDerivedBMesh().
static void emDM_drawEdges (DerivedMesh * dm, int UNUSEDdrawLooseEdges, int UNUSEDdrawAllEdges) [static]
Definition at line 438 of file editderivedmesh.c.
References emDM_drawMappedEdges(), and NULL.
Referenced by getEditDerivedBMesh().
static void emDM_drawFacesGLSL (DerivedMesh * dm, int(*)(int, void *attribs) setMaterial) [static]
Definition at line 1107 of file editderivedmesh.c.
References DerivedMesh::drawMappedFacesGLSL, and NULL.
Referenced by getEditDerivedBMesh().
static void emDM_drawFacesTex (DerivedMesh * dm, DMSetDrawOptionsTex setDrawOptions, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 969 of file editderivedmesh.c.
References emDM_drawFacesTex_common(), and NULL.
Referenced by getEditDerivedBMesh().
static void emDM_drawFacesTex_common (DerivedMesh * dm, DMSetDrawOptionsTex drawParams, DMSetDrawOptions drawParamsMapped, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 786 of file editderivedmesh.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_elem_index_get, BM_ELEM_SMOOTH, BM_FACE, BM_mesh_elem_index_ensure(), BM_VERT, bmdm_get_tri_tex(), CD_MLOOPCOL, CD_MTEXPOLY, BMVert::co, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, BMLoop::f, BMFace::head, i, BMesh::ldata, BMEditMesh::looptris, BMFace::mat_nr, ME_MTEXFACE_CPY, BMFace::no, BMVert::no, NULL, BMesh::pdata, EditDerivedBMesh::polyNos, EditDerivedBMesh::tc, BMEditMesh::tottri, BMLoop::v, EditDerivedBMesh::vertexCos, and EditDerivedBMesh::vertexNos.
Referenced by emDM_drawFacesTex(), and emDM_drawMappedFacesTex().
static void emDM_drawMappedEdges (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, void * userData) [static]
Definition at line 402 of file editderivedmesh.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_index_get, BM_iter_new(), BM_iter_step(), BM_mesh_elem_index_ensure(), BM_VERT, DM_DRAW_OPTION_SKIP, i, NULL, EditDerivedBMesh::tc, and EditDerivedBMesh::vertexCos.
Referenced by emDM_drawEdges(), and getEditDerivedBMesh().
static void emDM_drawMappedEdgesInterp (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMSetDrawInterpOptions setDrawInterpOptions, void * userData) [static]
Definition at line 446 of file editderivedmesh.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_index_get, BM_iter_new(), BM_iter_step(), BM_mesh_elem_index_ensure(), BM_VERT, DM_DRAW_OPTION_SKIP, i, NULL, EditDerivedBMesh::tc, and EditDerivedBMesh::vertexCos.
Referenced by getEditDerivedBMesh().
static void emDM_drawMappedFaces (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMSetMaterial setMaterial, DMCompareDrawOptions compareDrawOptions, void * userData, DMDrawFlag flag) [static]
Definition at line 582 of file editderivedmesh.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_elem_index_get, BM_ELEM_SMOOTH, BM_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BMVert::co, DM_DRAW_ALWAYS_SMOOTH, DM_DRAW_OPTION_NORMAL, DM_DRAW_OPTION_SKIP, DM_DRAW_OPTION_STIPPLE, BMLoop::f, i, if(), BMEditMesh::looptris, BMFace::mat_nr, BMFace::no, BMVert::no, EditDerivedBMesh::polyNos, stipple_quarttone, EditDerivedBMesh::tc, BMEditMesh::tottri, BMLoop::v, EditDerivedBMesh::vertexCos, and EditDerivedBMesh::vertexNos.
Referenced by getEditDerivedBMesh().
static void emDM_drawMappedFacesGLSL (DerivedMesh * dm, DMSetMaterial setMaterial, DMSetDrawOptions setDrawOptions, void * userData) [static]
Definition at line 987 of file editderivedmesh.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_elem_index_get, BM_ELEM_SMOOTH, BM_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BMVert::co, DM_DRAW_OPTION_SKIP, DM_vertex_attributes_from_gpu(), BMLoop::f, i, BMEditMesh::looptris, BMFace::mat_nr, BMFace::no, BMVert::no, PASSATTRIB, EditDerivedBMesh::polyNos, EditDerivedBMesh::tc, BMLoop::v, EditDerivedBMesh::vertexCos, and EditDerivedBMesh::vertexNos.
Referenced by getEditDerivedBMesh().
static void emDM_drawMappedFacesMat (DerivedMesh * dm, void(*)(void *userData, int, void *attribs) setMaterial, int(*)(void *userData, int index) setFace, void * userData) [static]
Definition at line 1114 of file editderivedmesh.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_elem_index_get, BM_ELEM_SMOOTH, BM_FACE, BM_mesh_elem_index_ensure(), BM_VERT, BMVert::co, DM_vertex_attributes_from_gpu(), BMLoop::f, i, BMEditMesh::looptris, BMFace::mat_nr, BMFace::no, BMVert::no, PASSATTRIB, EditDerivedBMesh::polyNos, EditDerivedBMesh::tc, BMLoop::v, EditDerivedBMesh::vertexCos, and EditDerivedBMesh::vertexNos.
Referenced by getEditDerivedBMesh().
static void emDM_drawMappedFacesTex (DerivedMesh * dm, DMSetDrawOptions setDrawOptions, DMCompareDrawOptions compareDrawOptions, void * userData) [static]
Definition at line 978 of file editderivedmesh.c.
References emDM_drawFacesTex_common(), and NULL.
Referenced by getEditDerivedBMesh().
static void emDM_drawUVEdges (DerivedMesh * dm) [static]
Definition at line 488 of file editderivedmesh.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, NULL, EditDerivedBMesh::tc, and MLoopUV::uv.
Referenced by getEditDerivedBMesh().
static void emDM_foreachMappedEdge (DerivedMesh * dm, void(*)(void *userData, int index, const float v0co[3], const float v1co[3]) func, void * userData) [static]
Definition at line 375 of file editderivedmesh.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_index_get, BM_iter_new(), BM_iter_step(), BM_mesh_elem_index_ensure(), BM_VERT, i, NULL, EditDerivedBMesh::tc, and EditDerivedBMesh::vertexCos.
Referenced by getEditDerivedBMesh().
static void emDM_foreachMappedFaceCenter (DerivedMesh * dm, void(*)(void *userData, int index, const float co[3], const float no[3]) func, void * userData) [static]
Definition at line 555 of file editderivedmesh.c.
References BLI_assert, BMEditMesh::bm, BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_mesh_elem_index_ensure(), BM_VERT, emDM__calcFaceCent(), i, BMFace::no, NULL, EditDerivedBMesh::polyNos, EditDerivedBMesh::tc, and EditDerivedBMesh::vertexCos.
Referenced by getEditDerivedBMesh().
static void emDM_foreachMappedVert (DerivedMesh * dm, void(*)(void *userData, int index, const float co[3], const float no_f[3], const short no_s[3]) func, void * userData) [static]
Definition at line 355 of file editderivedmesh.c.
References BMEditMesh::bm, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, i, NULL, EditDerivedBMesh::tc, EditDerivedBMesh::vertexCos, and EditDerivedBMesh::vertexNos.
Referenced by getEditDerivedBMesh().
static void emDM_getEdge (DerivedMesh * dm, int index, MEdge * edge_r) [static]
Definition at line 1327 of file editderivedmesh.c.
References BMEditMesh::bm, BM_edge_at_index(), BM_edge_flag_to_mflag(), BM_elem_float_data_get(), BM_elem_index_get, MEdge::bweight, CD_BWEIGHT, CD_CREASE, MEdge::crease, CustomData_has_layer(), BMLoop::e, BMesh::edata, MEdge::flag, EditDerivedBMesh::tc, EditDerivedBMesh::te, BMEdge::v1, MEdge::v1, BMEdge::v2, and MEdge::v2.
Referenced by getEditDerivedBMesh().
static void emDM_getMinMax (DerivedMesh * dm, float min_r[3], float max_r[3]) [static]
Definition at line 1236 of file editderivedmesh.c.
References BMEditMesh::bm, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMVert::co, DO_MINMAX, i, NULL, EditDerivedBMesh::tc, BMesh::totvert, EditDerivedBMesh::vertexCos, and zero_v3().
Referenced by getEditDerivedBMesh().
static int emDM_getNumEdges (DerivedMesh * dm) [static]
Definition at line 1266 of file editderivedmesh.c.
References BMEditMesh::bm, EditDerivedBMesh::tc, and BMesh::totedge.
Referenced by getEditDerivedBMesh().
static int emDM_getNumLoops (DerivedMesh * dm) [static]
Definition at line 1280 of file editderivedmesh.c.
References BMEditMesh::bm, EditDerivedBMesh::tc, and BMesh::totloop.
Referenced by getEditDerivedBMesh().
static int emDM_getNumPolys (DerivedMesh * dm) [static]
Definition at line 1287 of file editderivedmesh.c.
References BMEditMesh::bm, EditDerivedBMesh::tc, and BMesh::totface.
Referenced by getEditDerivedBMesh().
static int emDM_getNumTessFaces (DerivedMesh * dm) [static]
Definition at line 1273 of file editderivedmesh.c.
References EditDerivedBMesh::tc, and BMEditMesh::tottri.
Referenced by getEditDerivedBMesh().
static int emDM_getNumVerts (DerivedMesh * dm) [static]
Definition at line 1259 of file editderivedmesh.c.
References BMEditMesh::bm, EditDerivedBMesh::tc, and BMesh::totvert.
Referenced by getEditDerivedBMesh().
static void emDM_getTessFace (DerivedMesh * dm, int index, MFace * face_r) [static]
Definition at line 1355 of file editderivedmesh.c.
References BM_elem_index_get, BM_face_flag_to_mflag(), BMLoop::f, MFace::flag, BMEditMesh::looptris, BMFace::mat_nr, MFace::mat_nr, NULL, EditDerivedBMesh::tc, test_index_face(), EditDerivedBMesh::tf, BMLoop::v, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by getEditDerivedBMesh().
static void* emDM_getTessFaceDataArray (DerivedMesh * dm, int type) [static]
Definition at line 1500 of file editderivedmesh.c.
References BMEditMesh::bm, CD_CALLOC, CD_FLAG_TEMPORARY, CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, copy_v2_v2(), CustomData_bmesh_get(), CustomData_get_layer_index(), CustomData_sizeof(), data, BMHeader::data, DM_add_tessface_layer(), DM_get_tessface_data_layer(), BMLoop::f, DerivedMesh::faceData, CustomDataLayer::flag, BMFace::head, BMLoop::head, i, CustomData::layers, BMesh::ldata, BMEditMesh::looptris, ME_MTEXFACE_CPY, MESH_MLOOPCOL_TO_MCOL, NULL, BMesh::pdata, size(), EditDerivedBMesh::tc, and BMEditMesh::tottri.
Referenced by getEditDerivedBMesh().
static void emDM_getVert (DerivedMesh * dm, int index, MVert * vert_r) [static]
Definition at line 1309 of file editderivedmesh.c.
References BMEditMesh::bm, BM_vert_at_index(), bmvert_to_mvert(), MVert::co, copy_v3_v3(), EditDerivedBMesh::tc, EditDerivedBMesh::tv, and EditDerivedBMesh::vertexCos.
Referenced by getEditDerivedBMesh().
static void emDM_getVertCos (DerivedMesh * dm, float(*) cos_r[3]) [static]
Definition at line 1554 of file editderivedmesh.c.
References BMEditMesh::bm, BM_ITER_MESH, BM_VERTS_OF_MESH, BMVert::co, copy_v3_v3(), i, EditDerivedBMesh::tc, and EditDerivedBMesh::vertexCos.
Referenced by getEditDerivedBMesh().
static void emDM_recalcTessellation (DerivedMesh * UNUSEDdm) [static]
Definition at line 350 of file editderivedmesh.c.
Referenced by getEditDerivedBMesh().
static void emDM_release (DerivedMesh * dm) [static]
Definition at line 1574 of file editderivedmesh.c.
References DM_release(), MEM_freeN(), EditDerivedBMesh::polyNos, EditDerivedBMesh::vertexCos, and EditDerivedBMesh::vertexNos.
Referenced by getEditDerivedBMesh().
DerivedMesh* getEditDerivedBMesh (BMEditMesh * em, Object * UNUSEDob, float(*) vertexCos[3])
Definition at line 1625 of file editderivedmesh.c.
References add_v3_v3(), BMEditMesh::bm, BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_normal_update_vcos(), BM_FACES_OF_MESH, BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_iter_new(), BM_iter_step(), BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, bmDm_getEdgeDataLayout(), bmDm_getLoopDataLayout(), bmDm_getPolyDataLayout(), bmDm_getTessFaceDataLayout(), bmDm_getVertDataLayout(), DerivedMesh::calcNormals, CD_CALLOC, CD_MDEFORMVERT, copy_v3_v3(), DerivedMesh::copyEdgeArray, DerivedMesh::copyLoopArray, DerivedMesh::copyPolyArray, DerivedMesh::copyTessFaceArray, DerivedMesh::copyVertArray, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, DM_add_vert_layer(), DM_init(), DM_set_vert_data(), DM_TYPE_EDITBMESH, DerivedMesh::drawEdges, DerivedMesh::drawFacesGLSL, DerivedMesh::drawFacesTex, DerivedMesh::drawMappedEdges, DerivedMesh::drawMappedEdgesInterp, DerivedMesh::drawMappedFaces, DerivedMesh::drawMappedFacesGLSL, DerivedMesh::drawMappedFacesMat, DerivedMesh::drawMappedFacesTex, DerivedMesh::drawUVEdges, BMesh::elem_index_dirty, emDM_calcNormals(), emDM_copyEdgeArray(), emDM_copyLoopArray(), emDM_copyPolyArray(), emDM_copyTessFaceArray(), emDM_copyVertArray(), emDM_drawEdges(), emDM_drawFacesGLSL(), emDM_drawFacesTex(), emDM_drawMappedEdges(), emDM_drawMappedEdgesInterp(), emDM_drawMappedFaces(), emDM_drawMappedFacesGLSL(), emDM_drawMappedFacesMat(), emDM_drawMappedFacesTex(), emDM_drawUVEdges(), emDM_foreachMappedEdge(), emDM_foreachMappedFaceCenter(), emDM_foreachMappedVert(), emDM_getEdge(), emDM_getMinMax(), emDM_getNumEdges(), emDM_getNumLoops(), emDM_getNumPolys(), emDM_getNumTessFaces(), emDM_getNumVerts(), emDM_getTessFace(), emDM_getTessFaceDataArray(), emDM_getVert(), emDM_getVertCos(), emDM_recalcTessellation(), emDM_release(), DerivedMesh::foreachMappedEdge, DerivedMesh::foreachMappedFaceCenter, DerivedMesh::foreachMappedVert, DerivedMesh::getEdge, DerivedMesh::getEdgeDataLayout, DerivedMesh::getLoopDataLayout, DerivedMesh::getMinMax, DerivedMesh::getNumEdges, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, DerivedMesh::getPolyDataLayout, DerivedMesh::getTessFace, DerivedMesh::getTessFaceDataArray, DerivedMesh::getTessFaceDataLayout, DerivedMesh::getVert, DerivedMesh::getVertCos, DerivedMesh::getVertDataLayout, BMVert::head, i, MEM_callocN(), MEM_mallocN(), normalize_v3(), NULL, DerivedMesh::recalcTessellation, DerivedMesh::release, EditDerivedBMesh::tc, BMesh::totedge, BMesh::totface, BMesh::totloop, BMEditMesh::tottri, BMesh::totvert, and BMesh::vdata.
Variable Documentation
GLubyte stipple_quarttone[128]
Definition at line 83 of file glutil.c.
Referenced by ccgDM_drawMappedFaces(), draw_uvs(), and emDM_drawMappedFaces().