Blender: VideoBase.cpp File Reference
VideoBase.cpp File Reference
BGE Video Texture
#include "VideoBase.h"
#include "FilterSource.h"
Functions
void Video_open (VideoBase *self, char *file, short captureID)
PyObject * Video_play (PyImage *self)
PyObject * Video_pause (PyImage *self)
PyObject * Video_stop (PyImage *self)
PyObject * Video_getStatus (PyImage *self, void *closure)
PyObject * Video_refresh (PyImage *self)
PyObject * Video_getRange (PyImage *self, void *closure)
int Video_setRange (PyImage *self, PyObject *value, void *closure)
PyObject * Video_getRepeat (PyImage *self, void *closure)
int Video_setRepeat (PyImage *self, PyObject *value, void *closure)
PyObject * Video_getFrameRate (PyImage *self, void *closure)
int Video_setFrameRate (PyImage *self, PyObject *value, void *closure)
Variables
ExceptionID SourceVideoEmpty
ExceptionID SourceVideoCreation
ExpDesc SourceVideoEmptyDesc (SourceVideoEmpty,"Source Video is empty")
ExpDesc SourceVideoCreationDesc (SourceVideoCreation,"SourceVideo object was not created")
Detailed Description
Definition in file VideoBase.cpp.
Function Documentation
PyObject* Video_getFrameRate (PyImage * self, void * closure)
Definition at line 188 of file VideoBase.cpp.
References getVideo().
PyObject* Video_getRange (PyImage * self, void * closure)
Definition at line 144 of file VideoBase.cpp.
References getVideo().
PyObject* Video_getRepeat (PyImage * self, void * closure)
Definition at line 169 of file VideoBase.cpp.
References getVideo().
PyObject* Video_getStatus (PyImage * self, void * closure)
Definition at line 130 of file VideoBase.cpp.
References getVideo().
Referenced by Video_refresh().
void Video_open (VideoBase * self, char * file, short captureID)
Definition at line 105 of file VideoBase.cpp.
References NULL, S_OK, and THRWEXCP.
PyObject* Video_pause (PyImage * self)
Definition at line 123 of file VideoBase.cpp.
References getVideo().
PyObject* Video_play (PyImage * self)
Definition at line 119 of file VideoBase.cpp.
References getVideo().
PyObject* Video_refresh (PyImage * self)
Definition at line 136 of file VideoBase.cpp.
References getVideo(), NULL, ImageBase::refresh(), and Video_getStatus().
int Video_setFrameRate (PyImage * self, PyObject * value, void * closure)
Definition at line 192 of file VideoBase.cpp.
References getVideo(), NULL, and VideoBase::setFrameRate().
int Video_setRange (PyImage * self, PyObject * value, void * closure)
Definition at line 151 of file VideoBase.cpp.
References getVideo(), NULL, and VideoBase::setRange().
int Video_setRepeat (PyImage * self, PyObject * value, void * closure)
Definition at line 173 of file VideoBase.cpp.
References getVideo(), NULL, and VideoBase::setRepeat().
PyObject* Video_stop (PyImage * self)
Definition at line 126 of file VideoBase.cpp.
References getVideo().
Variable Documentation
ExceptionID SourceVideoCreation
Definition at line 100 of file VideoBase.cpp.
ExpDesc SourceVideoCreationDesc(SourceVideoCreation,"SourceVideo object was not created")
Referenced by registerAllExceptions().
ExceptionID SourceVideoEmpty
Definition at line 100 of file VideoBase.cpp.
ExpDesc SourceVideoEmptyDesc(SourceVideoEmpty,"Source Video is empty")
Referenced by registerAllExceptions().