Blender: BKE_node.h File Reference
BKE_node.h File Reference
blenkernel
#include "DNA_listBase.h"
#include "RNA_types.h"
Classes
struct bNodeSocketTemplate
struct bNodeSocketType
struct bNodeTemplate
struct bNodeType
struct bNodeTreeType
Defines
#define MAX_SOCKET 64
#define NODE_PROCESSING 1
#define NODE_READY 2
#define NODE_BREAK 2
#define NODE_FINISHED 4
#define NODE_FREEBUFS 8
#define NODE_SKIPPED 16
#define NODE_EXEC_FINISHED 0
#define NODE_EXEC_SUSPEND 1
#define NODE_CLASS_INPUT 0
#define NODE_CLASS_OUTPUT 1
#define NODE_CLASS_OP_COLOR 3
#define NODE_CLASS_OP_VECTOR 4
#define NODE_CLASS_OP_FILTER 5
#define NODE_CLASS_GROUP 6
#define NODE_CLASS_FILE 7
#define NODE_CLASS_CONVERTOR 8
#define NODE_CLASS_MATTE 9
#define NODE_CLASS_DISTORT 10
#define NODE_CLASS_OP_DYNAMIC 11
#define NODE_CLASS_PATTERN 12
#define NODE_CLASS_TEXTURE 13
#define NODE_CLASS_EXECUTION 14
#define NODE_CLASS_GETDATA 15
#define NODE_CLASS_SETDATA 16
#define NODE_CLASS_MATH 17
#define NODE_CLASS_MATH_VECTOR 18
#define NODE_CLASS_MATH_ROTATION 19
#define NODE_CLASS_PARTICLES 25
#define NODE_CLASS_TRANSFORM 30
#define NODE_CLASS_COMBINE 31
#define NODE_CLASS_SHADER 40
#define NODE_CLASS_LAYOUT 100
#define NODE_OLD_SHADING 1
#define NODE_NEW_SHADING 2
#define SOCK_IN 1
#define SOCK_OUT 2
#define NODE_GROUP 2
#define NODE_FORLOOP 3
#define NODE_WHILELOOP 4
#define NODE_FRAME 5
#define NODE_GROUP_MENU 10000
#define NODE_DYNAMIC_MENU 20000
#define SH_NODE_OUTPUT 1
#define SH_NODE_MATERIAL 100
#define SH_NODE_RGB 101
#define SH_NODE_VALUE 102
#define SH_NODE_MIX_RGB 103
#define SH_NODE_VALTORGB 104
#define SH_NODE_RGBTOBW 105
#define SH_NODE_TEXTURE 106
#define SH_NODE_NORMAL 107
#define SH_NODE_GEOMETRY 108
#define SH_NODE_MAPPING 109
#define SH_NODE_CURVE_VEC 110
#define SH_NODE_CURVE_RGB 111
#define SH_NODE_CAMERA 114
#define SH_NODE_MATH 115
#define SH_NODE_VECT_MATH 116
#define SH_NODE_SQUEEZE 117
#define SH_NODE_MATERIAL_EXT 118
#define SH_NODE_INVERT 119
#define SH_NODE_SEPRGB 120
#define SH_NODE_COMBRGB 121
#define SH_NODE_HUE_SAT 122
#define NODE_DYNAMIC 123
#define SH_NODE_OUTPUT_MATERIAL 124
#define SH_NODE_OUTPUT_WORLD 125
#define SH_NODE_OUTPUT_LAMP 126
#define SH_NODE_FRESNEL 127
#define SH_NODE_MIX_SHADER 128
#define SH_NODE_ATTRIBUTE 129
#define SH_NODE_BACKGROUND 130
#define SH_NODE_BSDF_ANISOTROPIC 131
#define SH_NODE_BSDF_DIFFUSE 132
#define SH_NODE_BSDF_GLOSSY 133
#define SH_NODE_BSDF_GLASS 134
#define SH_NODE_BSDF_TRANSLUCENT 137
#define SH_NODE_BSDF_TRANSPARENT 138
#define SH_NODE_BSDF_VELVET 139
#define SH_NODE_EMISSION 140
#define SH_NODE_NEW_GEOMETRY 141
#define SH_NODE_LIGHT_PATH 142
#define SH_NODE_TEX_IMAGE 143
#define SH_NODE_TEX_SKY 145
#define SH_NODE_TEX_GRADIENT 146
#define SH_NODE_TEX_VORONOI 147
#define SH_NODE_TEX_MAGIC 148
#define SH_NODE_TEX_WAVE 149
#define SH_NODE_TEX_NOISE 150
#define SH_NODE_TEX_MUSGRAVE 152
#define SH_NODE_TEX_COORD 155
#define SH_NODE_ADD_SHADER 156
#define SH_NODE_TEX_ENVIRONMENT 157
#define SH_NODE_OUTPUT_TEXTURE 158
#define SH_NODE_HOLDOUT 159
#define SH_NODE_LAYER_WEIGHT 160
#define SH_NODE_VOLUME_TRANSPARENT 161
#define SH_NODE_VOLUME_ISOTROPIC 162
#define SH_NODE_GAMMA 163
#define SH_NODE_TEX_CHECKER 164
#define SH_NODE_BRIGHTCONTRAST 165
#define SH_NODE_MAT_DIFF 1
#define SH_NODE_MAT_SPEC 2
#define SH_NODE_MAT_NEG 4
#define NODE_DYNAMIC_READY 0
#define NODE_DYNAMIC_LOADED 1
#define NODE_DYNAMIC_NEW 2
#define NODE_DYNAMIC_UPDATED 3
#define NODE_DYNAMIC_ADDEXIST 4
#define NODE_DYNAMIC_ERROR 5
#define NODE_DYNAMIC_REPARSE 6
#define NODE_DYNAMIC_SET 15
#define RRES_OUT_IMAGE 0
#define RRES_OUT_ALPHA 1
#define RRES_OUT_Z 2
#define RRES_OUT_NORMAL 3
#define RRES_OUT_UV 4
#define RRES_OUT_VEC 5
#define RRES_OUT_RGBA 6
#define RRES_OUT_DIFF 7
#define RRES_OUT_SPEC 8
#define RRES_OUT_SHADOW 9
#define RRES_OUT_AO 10
#define RRES_OUT_REFLECT 11
#define RRES_OUT_REFRACT 12
#define RRES_OUT_INDIRECT 13
#define RRES_OUT_INDEXOB 14
#define RRES_OUT_INDEXMA 15
#define RRES_OUT_MIST 16
#define RRES_OUT_EMIT 17
#define RRES_OUT_ENV 18
#define RRES_OUT_DIFF_DIRECT 19
#define RRES_OUT_DIFF_INDIRECT 20
#define RRES_OUT_DIFF_COLOR 21
#define RRES_OUT_GLOSSY_DIRECT 22
#define RRES_OUT_GLOSSY_INDIRECT 23
#define RRES_OUT_GLOSSY_COLOR 24
#define RRES_OUT_TRANSM_DIRECT 25
#define RRES_OUT_TRANSM_INDIRECT 26
#define RRES_OUT_TRANSM_COLOR 27
#define CMP_NODE_VIEWER 201
#define CMP_NODE_RGB 202
#define CMP_NODE_VALUE 203
#define CMP_NODE_MIX_RGB 204
#define CMP_NODE_VALTORGB 205
#define CMP_NODE_RGBTOBW 206
#define CMP_NODE_NORMAL 207
#define CMP_NODE_CURVE_VEC 208
#define CMP_NODE_CURVE_RGB 209
#define CMP_NODE_ALPHAOVER 210
#define CMP_NODE_BLUR 211
#define CMP_NODE_FILTER 212
#define CMP_NODE_MAP_VALUE 213
#define CMP_NODE_TIME 214
#define CMP_NODE_VECBLUR 215
#define CMP_NODE_SEPRGBA 216
#define CMP_NODE_SEPHSVA 217
#define CMP_NODE_SETALPHA 218
#define CMP_NODE_HUE_SAT 219
#define CMP_NODE_IMAGE 220
#define CMP_NODE_R_LAYERS 221
#define CMP_NODE_COMPOSITE 222
#define CMP_NODE_OUTPUT_FILE 223
#define CMP_NODE_TEXTURE 224
#define CMP_NODE_TRANSLATE 225
#define CMP_NODE_ZCOMBINE 226
#define CMP_NODE_COMBRGBA 227
#define CMP_NODE_DILATEERODE 228
#define CMP_NODE_ROTATE 229
#define CMP_NODE_SCALE 230
#define CMP_NODE_SEPYCCA 231
#define CMP_NODE_COMBYCCA 232
#define CMP_NODE_SEPYUVA 233
#define CMP_NODE_COMBYUVA 234
#define CMP_NODE_DIFF_MATTE 235
#define CMP_NODE_COLOR_SPILL 236
#define CMP_NODE_CHROMA_MATTE 237
#define CMP_NODE_CHANNEL_MATTE 238
#define CMP_NODE_FLIP 239
#define CMP_NODE_SPLITVIEWER 240
#define CMP_NODE_INDEX_MASK 241
#define CMP_NODE_MAP_UV 242
#define CMP_NODE_ID_MASK 243
#define CMP_NODE_DEFOCUS 244
#define CMP_NODE_DISPLACE 245
#define CMP_NODE_COMBHSVA 246
#define CMP_NODE_MATH 247
#define CMP_NODE_LUMA_MATTE 248
#define CMP_NODE_BRIGHTCONTRAST 249
#define CMP_NODE_GAMMA 250
#define CMP_NODE_INVERT 251
#define CMP_NODE_NORMALIZE 252
#define CMP_NODE_CROP 253
#define CMP_NODE_DBLUR 254
#define CMP_NODE_BILATERALBLUR 255
#define CMP_NODE_PREMULKEY 256
#define CMP_NODE_DIST_MATTE 257
#define CMP_NODE_VIEW_LEVELS 258
#define CMP_NODE_COLOR_MATTE 259
#define CMP_NODE_COLORBALANCE 260
#define CMP_NODE_HUECORRECT 261
#define CMP_NODE_MOVIECLIP 262
#define CMP_NODE_STABILIZE2D 263
#define CMP_NODE_TRANSFORM 264
#define CMP_NODE_MOVIEDISTORTION 265
#define CMP_NODE_DOUBLEEDGEMASK 266
#define CMP_NODE_OUTPUT_MULTI_FILE__DEPRECATED 267
#define CMP_NODE_GLARE 301
#define CMP_NODE_TONEMAP 302
#define CMP_NODE_LENSDIST 303
#define CMP_CHAN_RGB 1
#define CMP_CHAN_A 2
#define CMP_CHAN_R 4
#define CMP_CHAN_G 8
#define CMP_CHAN_B 16
#define CMP_FILT_SOFT 0
#define CMP_FILT_SHARP 1
#define CMP_FILT_LAPLACE 2
#define CMP_FILT_SOBEL 3
#define CMP_FILT_PREWITT 4
#define CMP_FILT_KIRSCH 5
#define CMP_FILT_SHADOW 6
#define CMP_SCALE_RELATIVE 0
#define CMP_SCALE_ABSOLUTE 1
#define CMP_SCALE_SCENEPERCENT 2
#define CMP_SCALE_RENDERPERCENT 3
#define TEX_NODE_OUTPUT 401
#define TEX_NODE_CHECKER 402
#define TEX_NODE_TEXTURE 403
#define TEX_NODE_BRICKS 404
#define TEX_NODE_MATH 405
#define TEX_NODE_MIX_RGB 406
#define TEX_NODE_RGBTOBW 407
#define TEX_NODE_VALTORGB 408
#define TEX_NODE_IMAGE 409
#define TEX_NODE_CURVE_RGB 410
#define TEX_NODE_INVERT 411
#define TEX_NODE_HUE_SAT 412
#define TEX_NODE_CURVE_TIME 413
#define TEX_NODE_ROTATE 414
#define TEX_NODE_VIEWER 415
#define TEX_NODE_TRANSLATE 416
#define TEX_NODE_COORD 417
#define TEX_NODE_DISTANCE 418
#define TEX_NODE_COMPOSE 419
#define TEX_NODE_DECOMPOSE 420
#define TEX_NODE_VALTONOR 421
#define TEX_NODE_SCALE 422
#define TEX_NODE_AT 423
#define TEX_NODE_PROC 500
#define TEX_NODE_PROC_MAX 600
Typedefs
typedef struct bNodeSocketTemplate bNodeSocketTemplate
typedef void(* NodeSocketButtonFunction)(const struct bContext *C, struct uiBlock *block, struct bNodeTree *ntree, struct bNode *node, struct bNodeSocket *sock, const char *name, int x, int y, int width)
typedef struct bNodeSocketType bNodeSocketType
typedef struct bNodeTemplate bNodeTemplate
typedef struct bNodeType bNodeType
typedef void(* bNodeTreeCallback)(void *calldata, struct ID *owner_id, struct bNodeTree *ntree)
typedef void(* bNodeClassCallback)(void *calldata, int nclass, const char *name)
typedef struct bNodeTreeType bNodeTreeType
Functions
struct bNodeTreeType * ntreeGetType (int type)
struct bNodeType * ntreeGetNodeType (struct bNodeTree *ntree)
struct bNodeSocketType * ntreeGetSocketType (int type)
struct bNodeTree * ntreeAddTree (const char *name, int type, int nodetype)
void ntreeInitTypes (struct bNodeTree *ntree)
void ntreeFreeTree (struct bNodeTree *ntree)
struct bNodeTree * ntreeCopyTree (struct bNodeTree *ntree)
void ntreeSwitchID (struct bNodeTree *ntree, struct ID *sce_from, struct ID *sce_to)
void ntreeMakeLocal (struct bNodeTree *ntree)
int ntreeHasType (struct bNodeTree *ntree, int type)
void ntreeUpdateTree (struct bNodeTree *ntree)
void ntreeVerifyNodes (struct Main *main, struct ID *id)
void ntreeGetDependencyList (struct bNodeTree *ntree, struct bNode ***deplist, int *totnodes)
void ntreeSetOutput (struct bNodeTree *ntree)
void ntreeInitPreview (struct bNodeTree *, int xsize, int ysize)
void ntreeClearPreview (struct bNodeTree *ntree)
void ntreeFreeCache (struct bNodeTree *ntree)
int ntreeNodeExists (struct bNodeTree *ntree, struct bNode *testnode)
int ntreeOutputExists (struct bNode *node, struct bNodeSocket *testsock)
struct bNodeTree * ntreeLocalize (struct bNodeTree *ntree)
void ntreeLocalSync (struct bNodeTree *localtree, struct bNodeTree *ntree)
void ntreeLocalMerge (struct bNodeTree *localtree, struct bNodeTree *ntree)
struct bNodeSocket * nodeAddSocket (struct bNodeTree *ntree, struct bNode *node, int in_out, const char *name, int type)
struct bNodeSocket * nodeInsertSocket (struct bNodeTree *ntree, struct bNode *node, int in_out, struct bNodeSocket *next_sock, const char *name, int type)
void nodeRemoveSocket (struct bNodeTree *ntree, struct bNode *node, struct bNodeSocket *sock)
void nodeRemoveAllSockets (struct bNodeTree *ntree, struct bNode *node)
void nodeAddToPreview (struct bNode *, float *, int, int, int)
struct bNode * nodeAddNode (struct bNodeTree *ntree, struct bNodeTemplate *ntemp)
void nodeUnlinkNode (struct bNodeTree *ntree, struct bNode *node)
void nodeUniqueName (struct bNodeTree *ntree, struct bNode *node)
void nodeRegisterType (struct bNodeTreeType *ttype, struct bNodeType *ntype)
void nodeMakeDynamicType (struct bNode *node)
int nodeDynamicUnlinkText (struct ID *txtid)
void nodeFreeNode (struct bNodeTree *ntree, struct bNode *node)
struct bNode * nodeCopyNode (struct bNodeTree *ntree, struct bNode *node)
struct bNodeLink * nodeAddLink (struct bNodeTree *ntree, struct bNode *fromnode, struct bNodeSocket *fromsock, struct bNode *tonode, struct bNodeSocket *tosock)
void nodeRemLink (struct bNodeTree *ntree, struct bNodeLink *link)
void nodeRemSocketLinks (struct bNodeTree *ntree, struct bNodeSocket *sock)
void nodeInternalRelink (struct bNodeTree *ntree, struct bNode *node)
void nodeSpaceCoords (struct bNode *node, float *locx, float *locy)
void nodeAttachNode (struct bNode *node, struct bNode *parent)
void nodeDetachNode (struct bNode *node)
struct bNode * nodeFindNodebyName (struct bNodeTree *ntree, const char *name)
int nodeFindNode (struct bNodeTree *ntree, struct bNodeSocket *sock, struct bNode **nodep, int *sockindex, int *in_out)
struct bNodeLink * nodeFindLink (struct bNodeTree *ntree, struct bNodeSocket *from, struct bNodeSocket *to)
int nodeCountSocketLinks (struct bNodeTree *ntree, struct bNodeSocket *sock)
void nodeSetActive (struct bNodeTree *ntree, struct bNode *node)
struct bNode * nodeGetActive (struct bNodeTree *ntree)
struct bNode * nodeGetActiveID (struct bNodeTree *ntree, short idtype)
int nodeSetActiveID (struct bNodeTree *ntree, short idtype, struct ID *id)
void nodeClearActiveID (struct bNodeTree *ntree, short idtype)
struct bNode * nodeGetActiveTexture (struct bNodeTree *ntree)
void nodeUpdate (struct bNodeTree *ntree, struct bNode *node)
int nodeUpdateID (struct bNodeTree *ntree, struct ID *id)
void nodeFreePreview (struct bNode *node)
int nodeSocketIsHidden (struct bNodeSocket *sock)
void nodeSocketSetType (struct bNodeSocket *sock, int type)
struct bNodeTemplate nodeMakeTemplate (struct bNode *node)
int nodeValid (struct bNodeTree *ntree, struct bNodeTemplate *ntemp)
const char * nodeLabel (struct bNode *node)
struct bNodeTree * nodeGroupEditGet (struct bNode *node)
struct bNodeTree * nodeGroupEditSet (struct bNode *node, int edit)
void nodeGroupEditClear (struct bNode *node)
void node_type_base (struct bNodeTreeType *ttype, struct bNodeType *ntype, int type, const char *name, short nclass, short flag)
void node_type_socket_templates (struct bNodeType *ntype, struct bNodeSocketTemplate *inputs, struct bNodeSocketTemplate *outputs)
void node_type_size (struct bNodeType *ntype, int width, int minwidth, int maxwidth)
void node_type_init (struct bNodeType *ntype, void(*initfunc)(struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp))
void node_type_valid (struct bNodeType *ntype, int(*validfunc)(struct bNodeTree *ntree, struct bNodeTemplate *ntemp))
void node_type_storage (struct bNodeType *ntype, const char *storagename, void(*freestoragefunc)(struct bNode *), void(*copystoragefunc)(struct bNode *, struct bNode *))
void node_type_label (struct bNodeType *ntype, const char *(*labelfunc)(struct bNode *))
void node_type_template (struct bNodeType *ntype, struct bNodeTemplate(*templatefunc)(struct bNode *))
void node_type_update (struct bNodeType *ntype, void(*updatefunc)(struct bNodeTree *ntree, struct bNode *node), void(*verifyfunc)(struct bNodeTree *ntree, struct bNode *node, struct ID *id))
void node_type_tree (struct bNodeType *ntype, void(*inittreefunc)(struct bNodeTree *), void(*updatetreefunc)(struct bNodeTree *))
void node_type_group_edit (struct bNodeType *ntype, struct bNodeTree *(*group_edit_get)(struct bNode *node), struct bNodeTree *(*group_edit_set)(struct bNode *node, int edit), void(*group_edit_clear)(struct bNode *node))
void node_type_exec (struct bNodeType *ntype, void(*execfunc)(void *data, struct bNode *, struct bNodeStack **, struct bNodeStack **))
void node_type_exec_new (struct bNodeType *ntype, void *(*initexecfunc)(struct bNode *node), void(*freeexecfunc)(struct bNode *node, void *nodedata), void(*newexecfunc)(void *data, int thread, struct bNode *, void *nodedata, struct bNodeStack **, struct bNodeStack **))
void node_type_internal_connect (struct bNodeType *ntype, ListBase(*internal_connect)(struct bNodeTree *, struct bNode *))
void node_type_gpu (struct bNodeType *ntype, int(*gpufunc)(struct GPUMaterial *mat, struct bNode *node, struct GPUNodeStack *in, struct GPUNodeStack *out))
void node_type_gpu_ext (struct bNodeType *ntype, int(*gpuextfunc)(struct GPUMaterial *mat, struct bNode *node, void *nodedata, struct GPUNodeStack *in, struct GPUNodeStack *out))
void node_type_compatibility (struct bNodeType *ntype, short compatibility)
struct bNodeSocket * node_group_find_input (struct bNode *gnode, struct bNodeSocket *gsock)
struct bNodeSocket * node_group_find_output (struct bNode *gnode, struct bNodeSocket *gsock)
struct bNodeSocket * node_group_add_socket (struct bNodeTree *ngroup, const char *name, int type, int in_out)
struct bNodeSocket * node_group_expose_socket (struct bNodeTree *ngroup, struct bNodeSocket *sock, int in_out)
void node_group_expose_all_sockets (struct bNodeTree *ngroup)
void node_group_remove_socket (struct bNodeTree *ngroup, struct bNodeSocket *gsock, int in_out)
struct bNode * node_group_make_from_selected (struct bNodeTree *ntree)
int node_group_ungroup (struct bNodeTree *ntree, struct bNode *gnode)
void register_node_type_frame (struct bNodeTreeType *ttype)
struct bNodeTreeExec * ntreeShaderBeginExecTree (struct bNodeTree *ntree, int use_tree_data)
void ntreeShaderEndExecTree (struct bNodeTreeExec *exec, int use_tree_data)
void ntreeShaderExecTree (struct bNodeTree *ntree, struct ShadeInput *shi, struct ShadeResult *shr)
void ntreeShaderGetTexcoMode (struct bNodeTree *ntree, int osa, short *texco, int *mode)
void nodeShaderSynchronizeID (struct bNode *node, int copyto)
void set_node_shader_lamp_loop (void(*lamp_loop_func)(struct ShadeInput *, struct ShadeResult *))
void ntreeGPUMaterialNodes (struct bNodeTree *ntree, struct GPUMaterial *mat)
struct bNodeTreeExec * ntreeCompositBeginExecTree (struct bNodeTree *ntree, int use_tree_data)
void ntreeCompositEndExecTree (struct bNodeTreeExec *exec, int use_tree_data)
void ntreeCompositExecTree (struct bNodeTree *ntree, struct RenderData *rd, int do_previews)
void ntreeCompositTagRender (struct Scene *sce)
int ntreeCompositTagAnimated (struct bNodeTree *ntree)
void ntreeCompositTagGenerators (struct bNodeTree *ntree)
void ntreeCompositForceHidden (struct bNodeTree *ntree, struct Scene *scene)
void ntreeCompositClearTags (struct bNodeTree *ntree)
struct bNodeSocket * ntreeCompositOutputFileAddSocket (struct bNodeTree *ntree, struct bNode *node, const char *name, struct ImageFormatData *im_format)
int ntreeCompositOutputFileRemoveActiveSocket (struct bNodeTree *ntree, struct bNode *node)
int ntreeTexTagAnimated (struct bNodeTree *ntree)
void ntreeTexCheckCyclics (struct bNodeTree *ntree)
struct bNodeTreeExec * ntreeTexBeginExecTree (struct bNodeTree *ntree, int use_tree_data)
void ntreeTexEndExecTree (struct bNodeTreeExec *exec, int use_tree_data)
int ntreeTexExecTree (struct bNodeTree *ntree, struct TexResult *target, float *coord, float *dxt, float *dyt, int osatex, short thread, struct Tex *tex, short which_output, int cfra, int preview, struct ShadeInput *shi, struct MTex *mtex)
void init_nodesystem (void)
void free_nodesystem (void)
void clear_scene_in_nodes (struct Main *bmain, struct Scene *sce)
Variables
void(* node_shader_lamp_loop)(struct ShadeInput *, struct ShadeResult *)
Detailed Description
Definition in file BKE_node.h.
Define Documentation
#define CMP_CHAN_A 2
Definition at line 648 of file BKE_node.h.
Referenced by def_cmp_invert(), do_invert(), and do_invert_fac().
#define CMP_CHAN_B 16
Definition at line 651 of file BKE_node.h.
#define CMP_CHAN_G 8
Definition at line 650 of file BKE_node.h.
#define CMP_CHAN_R 4
Definition at line 649 of file BKE_node.h.
#define CMP_CHAN_RGB 1
Definition at line 647 of file BKE_node.h.
Referenced by def_cmp_invert(), do_invert(), do_invert_fac(), and node_composit_init_invert().
#define CMP_FILT_KIRSCH 5
Definition at line 659 of file BKE_node.h.
Referenced by node_composit_exec_filter().
#define CMP_FILT_LAPLACE 2
Definition at line 656 of file BKE_node.h.
Referenced by node_composit_exec_filter().
#define CMP_FILT_PREWITT 4
Definition at line 658 of file BKE_node.h.
Referenced by node_composit_exec_filter().
#define CMP_FILT_SHADOW 6
Definition at line 660 of file BKE_node.h.
Referenced by node_composit_exec_filter().
#define CMP_FILT_SHARP 1
Definition at line 655 of file BKE_node.h.
Referenced by node_composit_exec_filter().
#define CMP_FILT_SOBEL 3
Definition at line 657 of file BKE_node.h.
Referenced by node_composit_exec_filter().
#define CMP_FILT_SOFT 0
Definition at line 654 of file BKE_node.h.
Referenced by node_composit_exec_filter().
#define CMP_NODE_ALPHAOVER 210
Definition at line 583 of file BKE_node.h.
#define CMP_NODE_BILATERALBLUR 255
Definition at line 628 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_bilateralblur().
#define CMP_NODE_BLUR 211
Definition at line 584 of file BKE_node.h.
Referenced by do_versions(), node_composit_set_butfunc(), ntree_version_241(), and register_node_type_cmp_blur().
#define CMP_NODE_BRIGHTCONTRAST 249
Definition at line 622 of file BKE_node.h.
Referenced by register_node_type_cmp_brightcontrast().
#define CMP_NODE_CHANNEL_MATTE 238
Definition at line 611 of file BKE_node.h.
#define CMP_NODE_CHROMA_MATTE 237
Definition at line 610 of file BKE_node.h.
Referenced by do_versions_nodetree_convert_angle(), node_composit_set_butfunc(), and register_node_type_cmp_chroma_matte().
#define CMP_NODE_COLOR_MATTE 259
Definition at line 632 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_color_matte().
#define CMP_NODE_COLOR_SPILL 236
Definition at line 609 of file BKE_node.h.
#define CMP_NODE_COLORBALANCE 260
Definition at line 633 of file BKE_node.h.
Referenced by do_versions(), node_composit_set_butfunc(), and register_node_type_cmp_colorbalance().
#define CMP_NODE_COMBHSVA 246
Definition at line 619 of file BKE_node.h.
#define CMP_NODE_COMBRGBA 227
Definition at line 600 of file BKE_node.h.
Referenced by register_node_type_cmp_combrgba().
#define CMP_NODE_COMBYCCA 232
Definition at line 605 of file BKE_node.h.
#define CMP_NODE_COMBYUVA 234
Definition at line 607 of file BKE_node.h.
#define CMP_NODE_COMPOSITE 222
Definition at line 595 of file BKE_node.h.
#define CMP_NODE_CROP 253
Definition at line 626 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_crop().
#define CMP_NODE_CURVE_RGB 209
Definition at line 582 of file BKE_node.h.
Referenced by direct_link_nodetree(), node_composit_set_butfunc(), ntreeCompositBeginExecTree(), ntreeCompositEndExecTree(), register_node_type_cmp_curve_rgb(), and write_nodetree().
#define CMP_NODE_CURVE_VEC 208
Definition at line 581 of file BKE_node.h.
#define CMP_NODE_DBLUR 254
Definition at line 627 of file BKE_node.h.
#define CMP_NODE_DEFOCUS 244
Definition at line 617 of file BKE_node.h.
#define CMP_NODE_DIFF_MATTE 235
Definition at line 608 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_diff_matte().
#define CMP_NODE_DILATEERODE 228
Definition at line 601 of file BKE_node.h.
#define CMP_NODE_DISPLACE 245
Definition at line 618 of file BKE_node.h.
Referenced by register_node_type_cmp_displace().
#define CMP_NODE_DIST_MATTE 257
Definition at line 630 of file BKE_node.h.
#define CMP_NODE_DOUBLEEDGEMASK 266
Definition at line 639 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_doubleedgemask().
#define CMP_NODE_FILTER 212
Definition at line 585 of file BKE_node.h.
#define CMP_NODE_FLIP 239
Definition at line 612 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_flip().
#define CMP_NODE_GAMMA 250
Definition at line 623 of file BKE_node.h.
#define CMP_NODE_GLARE 301
Definition at line 642 of file BKE_node.h.
Referenced by do_versions_nodetree_convert_angle(), node_composit_set_butfunc(), and register_node_type_cmp_glare().
#define CMP_NODE_HUE_SAT 219
Definition at line 592 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), ntree_version_242(), and register_node_type_cmp_hue_sat().
#define CMP_NODE_HUECORRECT 261
Definition at line 634 of file BKE_node.h.
#define CMP_NODE_ID_MASK 243
Definition at line 616 of file BKE_node.h.
#define CMP_NODE_IMAGE 220
Definition at line 593 of file BKE_node.h.
#define CMP_NODE_INDEX_MASK 241
Definition at line 614 of file BKE_node.h.
#define CMP_NODE_INVERT 251
Definition at line 624 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_invert().
#define CMP_NODE_LENSDIST 303
Definition at line 644 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_lensdist().
#define CMP_NODE_LUMA_MATTE 248
Definition at line 621 of file BKE_node.h.
#define CMP_NODE_MAP_UV 242
Definition at line 615 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_mapuv().
#define CMP_NODE_MAP_VALUE 213
Definition at line 586 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), node_only_value(), and register_node_type_cmp_map_value().
#define CMP_NODE_MATH 247
Definition at line 620 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_math().
#define CMP_NODE_MIX_RGB 204
Definition at line 577 of file BKE_node.h.
#define CMP_NODE_MOVIECLIP 262
Definition at line 635 of file BKE_node.h.
Referenced by node_add_node(), node_composit_set_butfunc(), ntreeCompositTagAnimated(), and register_node_type_cmp_movieclip().
#define CMP_NODE_MOVIEDISTORTION 265
Definition at line 638 of file BKE_node.h.
#define CMP_NODE_NORMAL 207
Definition at line 580 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_normal().
#define CMP_NODE_NORMALIZE 252
Definition at line 625 of file BKE_node.h.
#define CMP_NODE_OUTPUT_FILE 223
Definition at line 596 of file BKE_node.h.
Referenced by composite_patch(), do_versions_nodetree_multi_file_output_format_2_62_1(), node_add_node(), node_composit_set_butfunc(), ntreeSetOutput(), register_node_type_cmp_output_file(), and write_nodetree().
#define CMP_NODE_OUTPUT_MULTI_FILE__DEPRECATED 267
Definition at line 640 of file BKE_node.h.
Referenced by do_versions_nodetree_multi_file_output_format_2_62_1().
#define CMP_NODE_PREMULKEY 256
Definition at line 629 of file BKE_node.h.
#define CMP_NODE_R_LAYERS 221
Definition at line 594 of file BKE_node.h.
Referenced by check_valid_camera(), clear_scene_in_nodes(), composite_needs_render(), composite_patch(), do_versions_nodetree_image_default_alpha_output(), ED_node_composit_default(), ED_node_set_active(), expand_nodetree(), freeExecutableNode(), node_add_node(), node_composit_set_butfunc(), node_group_make_exec(), node_read_renderlayers_exec(), ntree_render_scenes(), ntreeCompositForceHidden(), ntreeCompositTagGenerators(), RE_MergeFullSample(), register_node_type_cmp_rlayers(), scene_remove_render_layer(), and tag_scenes_for_render().
#define CMP_NODE_RGB 202
Definition at line 575 of file BKE_node.h.
#define CMP_NODE_RGBTOBW 206
Definition at line 579 of file BKE_node.h.
#define CMP_NODE_ROTATE 229
Definition at line 602 of file BKE_node.h.
Referenced by do_versions_nodetree_convert_angle(), node_composit_set_butfunc(), and register_node_type_cmp_rotate().
#define CMP_NODE_SCALE 230
Definition at line 603 of file BKE_node.h.
#define CMP_NODE_SEPHSVA 217
Definition at line 590 of file BKE_node.h.
Referenced by register_node_type_cmp_sephsva().
#define CMP_NODE_SEPRGBA 216
Definition at line 589 of file BKE_node.h.
#define CMP_NODE_SEPYCCA 231
Definition at line 604 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_sepycca().
#define CMP_NODE_SEPYUVA 233
Definition at line 606 of file BKE_node.h.
Referenced by register_node_type_cmp_sepyuva().
#define CMP_NODE_SETALPHA 218
Definition at line 591 of file BKE_node.h.
#define CMP_NODE_SPLITVIEWER 240
Definition at line 613 of file BKE_node.h.
#define CMP_NODE_STABILIZE2D 263
Definition at line 636 of file BKE_node.h.
Referenced by node_add_node(), node_composit_set_butfunc(), and register_node_type_cmp_stabilize2d().
#define CMP_NODE_TEXTURE 224
Definition at line 597 of file BKE_node.h.
#define CMP_NODE_TIME 214
Definition at line 587 of file BKE_node.h.
#define CMP_NODE_TONEMAP 302
Definition at line 643 of file BKE_node.h.
#define CMP_NODE_TRANSFORM 264
Definition at line 637 of file BKE_node.h.
#define CMP_NODE_TRANSLATE 225
Definition at line 598 of file BKE_node.h.
Referenced by register_node_type_cmp_translate().
#define CMP_NODE_VALTORGB 205
Definition at line 578 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), and register_node_type_cmp_valtorgb().
#define CMP_NODE_VALUE 203
Definition at line 576 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), node_only_value(), and register_node_type_cmp_value().
#define CMP_NODE_VECBLUR 215
Definition at line 588 of file BKE_node.h.
Referenced by node_composit_set_butfunc(), ntree_version_241(), and register_node_type_cmp_vecblur().
#define CMP_NODE_VIEW_LEVELS 258
Definition at line 631 of file BKE_node.h.
#define CMP_NODE_VIEWER 201
Definition at line 574 of file BKE_node.h.
Referenced by direct_link_nodetree(), do_version_ntree_242_2(), ED_node_set_active(), local_merge(), localize(), node_link_viewer(), ntree_get_active_iuser(), ntreeSetOutput(), register_node_type_cmp_viewer(), and setExecutableNodes().
#define CMP_NODE_ZCOMBINE 226
Definition at line 599 of file BKE_node.h.
#define CMP_SCALE_ABSOLUTE 1
Definition at line 664 of file BKE_node.h.
Referenced by node_composit_exec_scale().
#define CMP_SCALE_RELATIVE 0
Definition at line 663 of file BKE_node.h.
Referenced by node_composit_exec_scale().
#define CMP_SCALE_RENDERPERCENT 3
Definition at line 666 of file BKE_node.h.
Referenced by node_composit_exec_scale().
#define CMP_SCALE_SCENEPERCENT 2
Definition at line 665 of file BKE_node.h.
Referenced by node_composit_exec_scale().
#define MAX_SOCKET 64
Definition at line 40 of file BKE_node.h.
Referenced by exec_composite_node(), ntreeExecGPUNodes(), ntreeExecNodes(), ntreeExecThreadNodes(), setExecutableNodes(), and tex_output().
#define NODE_BREAK 2
Definition at line 205 of file BKE_node.h.
Referenced by blur_single_image(), blur_with_reference(), bokeh_single_image(), dblur(), defocus_blur(), do_displace(), node_composit_exec_bilateralblur(), node_composit_exec_blur(), and node_composit_exec_defocus().
#define NODE_CLASS_COMBINE 31
Definition at line 236 of file BKE_node.h.
#define NODE_CLASS_CONVERTOR 8
Definition at line 222 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_get_colorid(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_idmask(), register_node_type_cmp_math(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_valtorgb(), register_node_type_sh_combrgb(), register_node_type_sh_math(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_valtorgb(), register_node_type_sh_vect_math(), register_node_type_tex_distance(), register_node_type_tex_math(), register_node_type_tex_rgbtobw(), register_node_type_tex_valtonor(), and register_node_type_tex_valtorgb().
#define NODE_CLASS_DISTORT 10
Definition at line 224 of file BKE_node.h.
Referenced by foreach_nodeclass(), register_node_type_cmp_crop(), register_node_type_cmp_displace(), register_node_type_cmp_flip(), register_node_type_cmp_lensdist(), register_node_type_cmp_mapuv(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_tex_at(), register_node_type_tex_rotate(), register_node_type_tex_scale(), and register_node_type_tex_translate().
#define NODE_CLASS_EXECUTION 14
Definition at line 228 of file BKE_node.h.
#define NODE_CLASS_FILE 7
Definition at line 221 of file BKE_node.h.
#define NODE_CLASS_GETDATA 15
Definition at line 229 of file BKE_node.h.
#define NODE_CLASS_GROUP 6
Definition at line 220 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_add_menu(), node_get_colorid(), node_menu_column_foreach_cb(), register_node_type_cmp_group(), register_node_type_sh_group(), register_node_type_tex_group(), ui_node_menu_column(), and ui_template_node_link_menu().
#define NODE_CLASS_INPUT 0
Definition at line 215 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_get_colorid(), register_node_type_cmp_curve_time(), register_node_type_cmp_image(), register_node_type_cmp_movieclip(), register_node_type_cmp_rgb(), register_node_type_cmp_rlayers(), register_node_type_cmp_texture(), register_node_type_cmp_value(), register_node_type_sh_attribute(), register_node_type_sh_camera(), register_node_type_sh_fresnel(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_rgb(), register_node_type_sh_tex_coord(), register_node_type_sh_texture(), register_node_type_sh_value(), register_node_type_tex_coord(), register_node_type_tex_curve_time(), register_node_type_tex_image(), and register_node_type_tex_texture().
#define NODE_CLASS_LAYOUT 100
Definition at line 238 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_menu_column_foreach_cb(), and register_node_type_frame().
#define NODE_CLASS_MATH 17
Definition at line 231 of file BKE_node.h.
#define NODE_CLASS_MATH_ROTATION 19
Definition at line 233 of file BKE_node.h.
#define NODE_CLASS_MATH_VECTOR 18
Definition at line 232 of file BKE_node.h.
#define NODE_CLASS_MATTE 9
Definition at line 223 of file BKE_node.h.
Referenced by foreach_nodeclass(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_diff_matte(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), and register_node_type_cmp_luma_matte().
#define NODE_CLASS_OP_COLOR 3
Definition at line 217 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_get_colorid(), register_node_type_cmp_alphaover(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_colorbalance(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_gamma(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_invert(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_tonemap(), register_node_type_cmp_zcombine(), register_node_type_sh_brightcontrast(), register_node_type_sh_curve_rgb(), register_node_type_sh_gamma(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_mix_rgb(), register_node_type_tex_compose(), register_node_type_tex_curve_rgb(), register_node_type_tex_decompose(), register_node_type_tex_hue_sat(), register_node_type_tex_invert(), and register_node_type_tex_mix_rgb().
#define NODE_CLASS_OP_DYNAMIC 11
Definition at line 225 of file BKE_node.h.
Referenced by register_node_type_sh_dynamic().
#define NODE_CLASS_OP_FILTER 5
Definition at line 219 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_get_colorid(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_dilateerode(), register_node_type_cmp_filter(), register_node_type_cmp_glare(), and register_node_type_cmp_vecblur().
#define NODE_CLASS_OP_VECTOR 4
Definition at line 218 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_get_colorid(), register_node_type_cmp_curve_vec(), register_node_type_cmp_map_value(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_sh_curve_vec(), register_node_type_sh_mapping(), and register_node_type_sh_normal().
#define NODE_CLASS_OUTPUT 1
Definition at line 216 of file BKE_node.h.
Referenced by foreach_nodeclass(), node_get_colorid(), ntreeExecGPUNodes(), ntreeSetOutput(), register_node_type_cmp_composite(), register_node_type_cmp_output_file(), register_node_type_cmp_splitviewer(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_tex_output(), and register_node_type_tex_viewer().
#define NODE_CLASS_PARTICLES 25
Definition at line 234 of file BKE_node.h.
#define NODE_CLASS_PATTERN 12
Definition at line 226 of file BKE_node.h.
Referenced by foreach_nodeclass(), register_node_type_tex_bricks(), and register_node_type_tex_checker().
#define NODE_CLASS_SETDATA 16
Definition at line 230 of file BKE_node.h.
#define NODE_CLASS_SHADER 40
Definition at line 237 of file BKE_node.h.
Referenced by foreach_nodeclass(), register_node_type_sh_add_shader(), register_node_type_sh_background(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_emission(), register_node_type_sh_holdout(), register_node_type_sh_mix_shader(), register_node_type_sh_volume_isotropic(), and register_node_type_sh_volume_transparent().
#define NODE_CLASS_TEXTURE 13
Definition at line 227 of file BKE_node.h.
Referenced by buttons_texture_users_find_nodetree(), foreach_nodeclass(), node_socket_add_replace(), nodeSetActive(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), and register_node_type_sh_tex_wave().
#define NODE_CLASS_TRANSFORM 30
Definition at line 235 of file BKE_node.h.
#define NODE_DYNAMIC 123
Definition at line 473 of file BKE_node.h.
Referenced by alloc_node_type_items(), direct_link_nodetree(), free_dynamic_typeinfo(), free_typeinfos(), node_add_menu(), node_dynamic_update_cb(), node_shader_set_butfunc(), nodeMakeDynamicType(), ntreeInitTypes(), register_node_type_sh_dynamic(), and write_nodetree().
#define NODE_DYNAMIC_ADDEXIST 4
Definition at line 521 of file BKE_node.h.
Referenced by ntreeInitTypes().
#define NODE_DYNAMIC_ERROR 5
Definition at line 522 of file BKE_node.h.
Referenced by node_dynamic_update_cb(), and node_shader_buts_dynamic().
#define NODE_DYNAMIC_LOADED 1
Definition at line 518 of file BKE_node.h.
Referenced by direct_link_nodetree().
#define NODE_DYNAMIC_MENU 20000
Definition at line 424 of file BKE_node.h.
#define NODE_DYNAMIC_NEW 2
Definition at line 519 of file BKE_node.h.
Referenced by node_browse_text_cb().
#define NODE_DYNAMIC_READY 0
Definition at line 517 of file BKE_node.h.
#define NODE_DYNAMIC_REPARSE 6
Definition at line 523 of file BKE_node.h.
Referenced by node_dynamic_update_cb().
#define NODE_DYNAMIC_SET 15
Definition at line 524 of file BKE_node.h.
#define NODE_DYNAMIC_UPDATED 3
Definition at line 520 of file BKE_node.h.
#define NODE_EXEC_FINISHED 0
Definition at line 211 of file BKE_node.h.
#define NODE_EXEC_SUSPEND 1
Definition at line 212 of file BKE_node.h.
#define NODE_FINISHED 4
Definition at line 206 of file BKE_node.h.
Referenced by freeExecutableNode(), ntreeCompositExecTree(), and setExecutableNodes().
#define NODE_FORLOOP 3
Definition at line 420 of file BKE_node.h.
Referenced by do_node_add_group(), node_add_menu(), node_common_set_butfunc(), and node_forloop_template().
#define NODE_FRAME 5
Definition at line 422 of file BKE_node.h.
Referenced by ED_node_update_hierarchy(), node_common_set_butfunc(), and register_node_type_frame().
#define NODE_FREEBUFS 8
Definition at line 207 of file BKE_node.h.
Referenced by freeExecutableNode().
#define NODE_GROUP 2
Definition at line 419 of file BKE_node.h.
Referenced by alloc_node_type_items(), buttons_texture_users_find_nodetree(), do_node_add_group(), do_versions(), ED_node_set_active(), flag_render_node_material(), has_nodetree(), init_render_nodetree(), lib_nodetree_do_versions_group_indices_cb(), material_in_nodetree(), node_add_menu(), node_common_set_butfunc(), node_draw_basis(), node_group_make_from_selected(), node_group_template(), node_group_ungroup_exec(), node_socket_add_replace(), nodes_use_material(), nodes_use_tex(), ntreeClearPreview(), ntreeCompositClearTags(), ntreeCompositTagAnimated(), ntreeInitPreview(), ntreeTexTagAnimated(), preview_mat_has_sss(), register_node_type_cmp_group(), register_node_type_sh_group(), register_node_type_tex_group(), setExecutableNodes(), ui_node_draw_input(), ui_node_draw_node(), ui_node_menu_column(), and ui_node_sock_name().
#define NODE_GROUP_MENU 10000
Definition at line 423 of file BKE_node.h.
#define NODE_NEW_SHADING 2
Definition at line 242 of file BKE_node.h.
Referenced by node_add_menu(), register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), and ui_node_menu_column().
#define NODE_OLD_SHADING 1
Definition at line 241 of file BKE_node.h.
Referenced by node_add_menu(), register_node_type_frame(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_dynamic(), register_node_type_sh_geom(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), and ui_node_menu_column().
#define NODE_PROCESSING 1
Definition at line 203 of file BKE_node.h.
Referenced by ntreeCompositExecTree().
#define NODE_READY 2
Definition at line 204 of file BKE_node.h.
Referenced by exec_composite_node(), getExecutableNode(), local_sync(), ntreeCompositExecTree(), and setExecutableNodes().
#define NODE_SKIPPED 16
Definition at line 208 of file BKE_node.h.
Referenced by local_sync(), and setExecutableNodes().
#define NODE_WHILELOOP 4
Definition at line 421 of file BKE_node.h.
Referenced by do_node_add_group(), node_add_menu(), node_common_set_butfunc(), and node_whileloop_template().
#define RRES_OUT_ALPHA 1
Definition at line 545 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), cmp_node_image_create_outputs(), force_hidden_passes(), and node_composit_exec_rlayers().
#define RRES_OUT_AO 10
Definition at line 554 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_DIFF 7
Definition at line 551 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_DIFF_COLOR 21
Definition at line 565 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_DIFF_DIRECT 19
Definition at line 563 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_DIFF_INDIRECT 20
Definition at line 564 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_EMIT 17
Definition at line 561 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_ENV 18
Definition at line 562 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_GLOSSY_COLOR 24
Definition at line 568 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_GLOSSY_DIRECT 22
Definition at line 566 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_GLOSSY_INDIRECT 23
Definition at line 567 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_IMAGE 0
Definition at line 544 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), cmp_node_image_create_outputs(), force_hidden_passes(), and node_composit_exec_rlayers().
#define RRES_OUT_INDEXMA 15
Definition at line 559 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_INDEXOB 14
Definition at line 558 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_INDIRECT 13
Definition at line 557 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_MIST 16
Definition at line 560 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_NORMAL 3
Definition at line 547 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_REFLECT 11
Definition at line 555 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_REFRACT 12
Definition at line 556 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_RGBA 6
Definition at line 550 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_SHADOW 9
Definition at line 553 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_SPEC 8
Definition at line 552 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_TRANSM_COLOR 27
Definition at line 571 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_TRANSM_DIRECT 25
Definition at line 569 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_TRANSM_INDIRECT 26
Definition at line 570 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_UV 4
Definition at line 548 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_VEC 5
Definition at line 549 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define RRES_OUT_Z 2
Definition at line 546 of file BKE_node.h.
Referenced by cmp_node_image_add_render_pass_outputs(), cmp_node_image_create_outputs(), force_hidden_passes(), and node_composit_rlayers_out().
#define SH_NODE_ADD_SHADER 156
Definition at line 501 of file BKE_node.h.
Referenced by register_node_type_sh_add_shader().
#define SH_NODE_ATTRIBUTE 129
Definition at line 480 of file BKE_node.h.
#define SH_NODE_BACKGROUND 130
Definition at line 481 of file BKE_node.h.
Referenced by ED_node_shader_default(), and register_node_type_sh_background().
#define SH_NODE_BRIGHTCONTRAST 165
Definition at line 510 of file BKE_node.h.
Referenced by register_node_type_sh_brightcontrast().
#define SH_NODE_BSDF_ANISOTROPIC 131
Definition at line 482 of file BKE_node.h.
Referenced by register_node_type_sh_bsdf_anisotropic().
#define SH_NODE_BSDF_DIFFUSE 132
Definition at line 483 of file BKE_node.h.
Referenced by ED_node_shader_default(), and register_node_type_sh_bsdf_diffuse().
#define SH_NODE_BSDF_GLASS 134
Definition at line 485 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_bsdf_glass().
#define SH_NODE_BSDF_GLOSSY 133
Definition at line 484 of file BKE_node.h.
#define SH_NODE_BSDF_TRANSLUCENT 137
Definition at line 486 of file BKE_node.h.
#define SH_NODE_BSDF_TRANSPARENT 138
Definition at line 487 of file BKE_node.h.
Referenced by register_node_type_sh_bsdf_transparent().
#define SH_NODE_BSDF_VELVET 139
Definition at line 488 of file BKE_node.h.
#define SH_NODE_CAMERA 114
Definition at line 464 of file BKE_node.h.
#define SH_NODE_COMBRGB 121
Definition at line 471 of file BKE_node.h.
Referenced by register_node_type_sh_combrgb().
#define SH_NODE_CURVE_RGB 111
Definition at line 463 of file BKE_node.h.
Referenced by direct_link_nodetree(), node_shader_set_butfunc(), register_node_type_sh_curve_rgb(), and write_nodetree().
#define SH_NODE_CURVE_VEC 110
Definition at line 462 of file BKE_node.h.
#define SH_NODE_EMISSION 140
Definition at line 489 of file BKE_node.h.
Referenced by ED_node_shader_default(), and register_node_type_sh_emission().
#define SH_NODE_FRESNEL 127
Definition at line 478 of file BKE_node.h.
#define SH_NODE_GAMMA 163
Definition at line 508 of file BKE_node.h.
#define SH_NODE_GEOMETRY 108
Definition at line 460 of file BKE_node.h.
#define SH_NODE_HOLDOUT 159
Definition at line 504 of file BKE_node.h.
#define SH_NODE_HUE_SAT 122
Definition at line 472 of file BKE_node.h.
#define SH_NODE_INVERT 119
Definition at line 469 of file BKE_node.h.
Referenced by register_node_type_sh_invert().
#define SH_NODE_LAYER_WEIGHT 160
Definition at line 505 of file BKE_node.h.
Referenced by register_node_type_sh_layer_weight().
#define SH_NODE_LIGHT_PATH 142
Definition at line 491 of file BKE_node.h.
Referenced by register_node_type_sh_light_path().
#define SH_NODE_MAPPING 109
Definition at line 461 of file BKE_node.h.
Referenced by do_version_ntree_tex_mapping_260(), do_versions_nodetree_convert_angle(), node_shader_set_butfunc(), and register_node_type_sh_mapping().
#define SH_NODE_MAT_DIFF 1
Definition at line 513 of file BKE_node.h.
Referenced by def_sh_material(), gpu_shader_material(), node_shader_exec_material(), and node_shader_init_material().
#define SH_NODE_MAT_NEG 4
Definition at line 515 of file BKE_node.h.
Referenced by def_sh_material(), gpu_shader_material(), and node_shader_exec_material().
#define SH_NODE_MAT_SPEC 2
Definition at line 514 of file BKE_node.h.
Referenced by def_sh_material(), gpu_shader_material(), node_shader_exec_material(), and node_shader_init_material().
#define SH_NODE_MATERIAL 100
Definition at line 452 of file BKE_node.h.
#define SH_NODE_MATERIAL_EXT 118
Definition at line 468 of file BKE_node.h.
#define SH_NODE_MATH 115
Definition at line 465 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_math().
#define SH_NODE_MIX_RGB 103
Definition at line 455 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_mix_rgb().
#define SH_NODE_MIX_SHADER 128
Definition at line 479 of file BKE_node.h.
#define SH_NODE_NEW_GEOMETRY 141
Definition at line 490 of file BKE_node.h.
#define SH_NODE_NORMAL 107
Definition at line 459 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_normal().
#define SH_NODE_OUTPUT 1
Definition at line 450 of file BKE_node.h.
Referenced by ED_node_set_active(), ED_node_shader_default(), and register_node_type_sh_output().
#define SH_NODE_OUTPUT_LAMP 126
Definition at line 477 of file BKE_node.h.
#define SH_NODE_OUTPUT_MATERIAL 124
Definition at line 475 of file BKE_node.h.
Referenced by ED_node_shader_default(), and register_node_type_sh_output_material().
#define SH_NODE_OUTPUT_TEXTURE 158
Definition at line 503 of file BKE_node.h.
#define SH_NODE_OUTPUT_WORLD 125
Definition at line 476 of file BKE_node.h.
Referenced by ED_node_shader_default(), and register_node_type_sh_output_world().
#define SH_NODE_RGB 101
Definition at line 453 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_rgb().
#define SH_NODE_RGBTOBW 105
Definition at line 457 of file BKE_node.h.
Referenced by register_node_type_sh_rgbtobw().
#define SH_NODE_SEPRGB 120
Definition at line 470 of file BKE_node.h.
#define SH_NODE_SQUEEZE 117
Definition at line 467 of file BKE_node.h.
Referenced by register_node_type_sh_squeeze().
#define SH_NODE_TEX_CHECKER 164
Definition at line 509 of file BKE_node.h.
Referenced by register_node_type_sh_tex_checker().
#define SH_NODE_TEX_COORD 155
Definition at line 500 of file BKE_node.h.
#define SH_NODE_TEX_ENVIRONMENT 157
Definition at line 502 of file BKE_node.h.
Referenced by is_image_texture_node(), node_shader_set_butfunc(), and register_node_type_sh_tex_environment().
#define SH_NODE_TEX_GRADIENT 146
Definition at line 494 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_tex_gradient().
#define SH_NODE_TEX_IMAGE 143
Definition at line 492 of file BKE_node.h.
#define SH_NODE_TEX_MAGIC 148
Definition at line 496 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_tex_magic().
#define SH_NODE_TEX_MUSGRAVE 152
Definition at line 499 of file BKE_node.h.
Referenced by node_shader_set_butfunc(), and register_node_type_sh_tex_musgrave().
#define SH_NODE_TEX_NOISE 150
Definition at line 498 of file BKE_node.h.
#define SH_NODE_TEX_SKY 145
Definition at line 493 of file BKE_node.h.
#define SH_NODE_TEX_VORONOI 147
Definition at line 495 of file BKE_node.h.
#define SH_NODE_TEX_WAVE 149
Definition at line 497 of file BKE_node.h.
#define SH_NODE_TEXTURE 106
Definition at line 458 of file BKE_node.h.
#define SH_NODE_VALTORGB 104
Definition at line 456 of file BKE_node.h.
#define SH_NODE_VALUE 102
Definition at line 454 of file BKE_node.h.
#define SH_NODE_VECT_MATH 116
Definition at line 466 of file BKE_node.h.
#define SH_NODE_VOLUME_ISOTROPIC 162
Definition at line 507 of file BKE_node.h.
#define SH_NODE_VOLUME_TRANSPARENT 161
Definition at line 506 of file BKE_node.h.
Referenced by register_node_type_sh_volume_transparent().
#define SOCK_IN 1
Definition at line 245 of file BKE_node.h.
Referenced by draw_group_socket(), draw_group_socket_name(), group_verify_socket(), loop_sync(), make_socket(), node_add_input_from_template(), node_draw_group(), node_find_indicated_socket(), node_forloop_init(), node_forloop_init_tree(), node_group_add_extern_socket(), node_group_add_socket(), node_group_expose_all_sockets(), node_group_init(), node_group_make_from_selected(), node_group_remove_socket(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_group_verify(), node_link_init(), node_link_modal(), node_loop_update_tree(), node_mouse_select(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), node_verify_socket_templates(), node_whileloop_init(), nodeAddSocket(), nodeFindNode(), nodeInsertSocket(), ntreeCompositOutputFileAddSocket(), rna_def_group_sockets_api(), rna_def_nodetree(), and verify_socket_template().
#define SOCK_OUT 2
Definition at line 246 of file BKE_node.h.
Referenced by cmp_node_image_add_multilayer_outputs(), draw_group_socket(), node_add_output_from_template(), node_draw_group(), node_find_indicated_socket(), node_forloop_init(), node_group_expose_all_sockets(), node_group_init(), node_group_make_from_selected(), node_group_remove_socket(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_verify(), node_link_init(), node_link_invoke(), node_link_modal(), node_loop_update_tree(), node_mouse_select(), node_verify_socket_templates(), node_whileloop_init(), node_whileloop_init_tree(), nodeAddSocket(), nodeFindNode(), nodeInsertSocket(), and rna_def_nodetree().
#define TEX_NODE_AT 423
Definition at line 710 of file BKE_node.h.
Referenced by register_node_type_tex_at().
#define TEX_NODE_BRICKS 404
Definition at line 691 of file BKE_node.h.
#define TEX_NODE_CHECKER 402
Definition at line 689 of file BKE_node.h.
#define TEX_NODE_COMPOSE 419
Definition at line 706 of file BKE_node.h.
Referenced by register_node_type_tex_compose().
#define TEX_NODE_COORD 417
Definition at line 704 of file BKE_node.h.
Referenced by register_node_type_tex_coord().
#define TEX_NODE_CURVE_RGB 410
Definition at line 697 of file BKE_node.h.
#define TEX_NODE_CURVE_TIME 413
Definition at line 700 of file BKE_node.h.
Referenced by direct_link_nodetree(), node_texture_set_butfunc(), ntreeTexTagAnimated(), register_node_type_tex_curve_time(), and write_nodetree().
#define TEX_NODE_DECOMPOSE 420
Definition at line 707 of file BKE_node.h.
#define TEX_NODE_DISTANCE 418
Definition at line 705 of file BKE_node.h.
#define TEX_NODE_HUE_SAT 412
Definition at line 699 of file BKE_node.h.
#define TEX_NODE_IMAGE 409
Definition at line 696 of file BKE_node.h.
Referenced by direct_link_nodetree(), node_add_file_exec(), node_texture_set_butfunc(), and register_node_type_tex_image().
#define TEX_NODE_INVERT 411
Definition at line 698 of file BKE_node.h.
Referenced by register_node_type_tex_invert().
#define TEX_NODE_MATH 405
Definition at line 692 of file BKE_node.h.
Referenced by node_texture_set_butfunc(), and register_node_type_tex_math().
#define TEX_NODE_MIX_RGB 406
Definition at line 693 of file BKE_node.h.
#define TEX_NODE_OUTPUT 401
Definition at line 688 of file BKE_node.h.
Referenced by assign_index(), do_versions(), ED_node_texture_default(), node_texture_set_butfunc(), register_node_type_tex_output(), and unique_name().
#define TEX_NODE_PROC 500
Definition at line 713 of file BKE_node.h.
Referenced by node_texture_set_butfunc(), and ProcDef().
#define TEX_NODE_PROC_MAX 600
Definition at line 714 of file BKE_node.h.
Referenced by node_texture_set_butfunc().
#define TEX_NODE_RGBTOBW 407
Definition at line 694 of file BKE_node.h.
Referenced by register_node_type_tex_rgbtobw().
#define TEX_NODE_ROTATE 414
Definition at line 701 of file BKE_node.h.
#define TEX_NODE_SCALE 422
Definition at line 709 of file BKE_node.h.
#define TEX_NODE_TEXTURE 403
Definition at line 690 of file BKE_node.h.
Referenced by node_buts_texture(), node_texture_set_butfunc(), ntreeTexCheckCyclics(), and register_node_type_tex_texture().
#define TEX_NODE_TRANSLATE 416
Definition at line 703 of file BKE_node.h.
#define TEX_NODE_VALTONOR 421
Definition at line 708 of file BKE_node.h.
Referenced by register_node_type_tex_valtonor().
#define TEX_NODE_VALTORGB 408
Definition at line 695 of file BKE_node.h.
#define TEX_NODE_VIEWER 415
Definition at line 702 of file BKE_node.h.
Referenced by register_node_type_tex_viewer().
Typedef Documentation
typedef void(* bNodeClassCallback)(void *calldata, int nclass, const char *name)
Definition at line 251 of file BKE_node.h.
typedef struct bNodeSocketTemplate bNodeSocketTemplate
Compact definition of a node socket. Can be used to quickly define a list of static sockets for a node, which are added to each new node of that type.
Deprecated:
New nodes should add default sockets in the initialization function instead. This struct is mostly kept for old nodes and should be removed some time.
typedef struct bNodeSocketType bNodeSocketType
Defines a socket type. Defines the appearance and behavior of a socket in the UI.
typedef struct bNodeTemplate bNodeTemplate
Template for creating a node. Stored required parameters to make a new node of a specific type.
typedef void(* bNodeTreeCallback)(void *calldata, struct ID *owner_id, struct bNodeTree *ntree)
Definition at line 250 of file BKE_node.h.
typedef struct bNodeTreeType bNodeTreeType
typedef struct bNodeType bNodeType
Defines a node type. Initial attributes and constants for a node as well as callback functions implementing the node behavior.
typedef void(* NodeSocketButtonFunction)(const struct bContext *C, struct uiBlock *block, struct bNodeTree *ntree, struct bNode *node, struct bNodeSocket *sock, const char *name, int x, int y, int width)
Definition at line 90 of file BKE_node.h.
Function Documentation
void clear_scene_in_nodes (struct Main * bmain, struct Scene * sce)
Definition at line 2101 of file node.c.
References CMP_NODE_R_LAYERS, ListBase::first, bNode::id, Scene::id, if(), bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, NULL, Main::scene, and bNode::type.
Referenced by unlink_scene().
void free_nodesystem (void)
Definition at line 2089 of file node.c.
References free_typeinfos(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, and ntreeGetType().
Referenced by free_blender(), and main().
void init_nodesystem (void)
Definition at line 2082 of file node.c.
References NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeGetType(), registerCompositNodes(), registerShaderNodes(), and registerTextureNodes().
Referenced by main().
struct bNodeSocket* node_group_add_socket (struct bNodeTree * ngroup, const char * name, int type, int in_out) [read]
Definition at line 402 of file node_common.c.
References BLI_addtail(), BLI_strncpy(), bNodeTree::cur_index, bNodeSocket::default_value, bNodeSocket::flag, bNodeTree::inputs, bNodeSocket::limit, bNodeSocket::link, MEM_callocN(), bNodeSocket::name, bNodeSocket::new_sock, bNodeSocket::next, NTREE_UPDATE_GROUP_IN, NTREE_UPDATE_GROUP_OUT, ntreeGetSocketType(), NULL, bNodeTree::outputs, bNodeSocket::own_index, bNodeSocket::prev, SOCK_DYNAMIC, SOCK_IN, bNodeTemplate::type, bNodeSocket::type, bNodeTree::update, and bNodeSocketType::value_structsize.
Referenced by node_forloop_init_tree(), node_group_expose_all_sockets(), node_group_expose_socket(), node_group_socket_add_exec(), and node_whileloop_init_tree().
void node_group_expose_all_sockets (struct bNodeTree * ngroup)
Definition at line 439 of file node_common.c.
References bNodeSocket::default_value, ListBase::first, bNode::inputs, bNodeSocket::link, bNodeSocket::name, bNodeSocket::next, bNode::next, node_group_add_socket(), node_socket_copy_default_value(), nodeAddLink(), nodeCountSocketLinks(), bNodeTree::nodes, nodeSocketIsHidden(), NULL, bNode::outputs, SOCK_IN, SOCK_OUT, and bNodeSocket::type.
Referenced by lib_verify_nodetree().
struct bNodeSocket* node_group_expose_socket (struct bNodeTree * ngroup, struct bNodeSocket * sock, int in_out) [read]
Definition at line 429 of file node_common.c.
References bNodeSocket::default_value, bNodeSocket::name, node_group_add_socket(), node_socket_copy_default_value(), and bNodeSocket::type.
Referenced by loop_sync(), node_group_link(), node_group_make_from_selected(), and node_link_modal().
struct bNodeSocket* node_group_find_input (struct bNode * gnode, struct bNodeSocket * gsock) [read]
Definition at line 65 of file node_common.c.
References ListBase::first, bNodeSocket::groupsock, bNode::inputs, bNodeSocket::next, and NULL.
Referenced by node_group_ungroup().
struct bNodeSocket* node_group_find_output (struct bNode * gnode, struct bNodeSocket * gsock) [read]
Definition at line 74 of file node_common.c.
References ListBase::first, bNodeSocket::groupsock, bNodeSocket::next, NULL, and bNode::outputs.
Referenced by node_group_make_from_selected().
struct bNode* node_group_make_from_selected (struct bNodeTree * ntree) [read]
Definition at line 114 of file node_common.c.
References bNodeTree::adt, BKE_animdata_separate_by_basepath(), BLI_addtail(), BLI_freelinkN(), BLI_genericNodeN(), BLI_remlink(), LinkData::data, DO_MINMAX2, bNode::done, ListBase::first, bNode::flag, bNodeLink::fromnode, bNodeLink::fromsock, bNodeTree::id, INIT_MINMAX2, bNode::inputs, link(), bNodeSocket::link, bNodeTree::links, bNode::locx, bNode::locy, max, MEM_freeN(), min, LinkData::next, bNodeSocket::next, bNode::next, bNodeLink::next, bNodeTemplate::ngroup, NODE_GROUP, node_group_add_extern_socket(), node_group_expose_socket(), node_group_find_output(), NODE_SELECT, nodeAddLink(), nodeAddNode(), bNodeTree::nodes, NTREE_UPDATE, NTREE_UPDATE_LINKS, NTREE_UPDATE_NODES, ntreeAddTree(), ntreeFreeCache(), ntreeUpdateTree(), NULL, bNode::outputs, bNodeTree::outputs, RNA_Node, RNA_path_from_ID_to_struct(), RNA_pointer_create(), SOCK_IN, SOCK_OUT, bNodeLink::tonode, bNodeLink::tosock, bNodeTree::type, bNode::type, bNodeTemplate::type, and bNodeTree::update.
Referenced by node_group_make_exec().
void node_group_remove_socket (struct bNodeTree * ngroup, struct bNodeSocket * gsock, int in_out)
Definition at line 468 of file node_common.c.
References BLI_remlink(), bNodeSocket::default_value, bNodeTree::inputs, MEM_freeN(), nodeRemSocketLinks(), NTREE_UPDATE_GROUP_IN, NTREE_UPDATE_GROUP_OUT, bNodeTree::outputs, SOCK_IN, SOCK_OUT, and bNodeTree::update.
Referenced by loop_sync(), and node_group_socket_remove_exec().
int node_group_ungroup (struct bNodeTree * ntree, struct bNode * gnode)
Definition at line 253 of file node_common.c.
References AnimData::action, bNodeTree::adt, BKE_animdata_separate_by_basepath(), BLI_addtail(), BLI_freelinkN(), BLI_genericNodeN(), BLI_remlink(), copy_action(), LinkData::data, bNodeSocket::default_value, ListBase::first, bNode::flag, free_libblock(), bNodeLink::fromnode, bNodeLink::fromsock, G, bNodeSocket::groupsock, bNode::id, bNodeTree::id, if(), bNode::inputs, link(), bNodeSocket::link, bNodeTree::links, bNode::locx, bNode::locy, MEM_freeN(), bNode::new_node, bNodeSocket::new_sock, bNodeSocket::next, LinkData::next, bNode::next, bNodeLink::next, bNodeTemplate::ngroup, node_group_find_input(), NODE_SELECT, node_socket_convert_default_value(), nodeFreeNode(), nodeRemLink(), bNodeTree::nodes, NTREE_UPDATE_LINKS, NTREE_UPDATE_NODES, ntreeCopyTree(), ntreeUpdateTree(), NULL, RNA_Node, RNA_path_from_ID_to_struct(), RNA_pointer_create(), bNodeLink::tonode, bNodeLink::tosock, bNodeSocket::type, and bNodeTree::update.
Referenced by node_group_ungroup_exec().
void node_type_base (struct bNodeTreeType * ttype, struct bNodeType * ntype, int type, const char * name, short nclass, short flag)
Definition at line 1703 of file node.c.
References BLI_strncpy(), bNodeType::flag, FLT_MAX, bNodeType::height, bNodeTreeType::internal_connect, bNodeType::internal_connect, bNodeType::maxheight, bNodeType::maxwidth, bNodeType::minheight, bNodeType::minwidth, bNodeType::name, bNodeType::nclass, bNodeTemplate::type, bNodeType::type, and bNodeType::width.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_dynamic(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_compatibility (struct bNodeType * ntype, short compatibility)
Definition at line 1825 of file node.c.
References bNodeType::compatibility.
Referenced by register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_dynamic(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), and register_node_type_sh_volume_transparent().
void node_type_exec (struct bNodeType * ntype, void(*)(void *data, struct bNode *, struct bNodeStack **, struct bNodeStack **) execfunc)
Definition at line 1795 of file node.c.
References bNodeType::execfunc.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_exec_new (struct bNodeType * ntype, void *(*)(struct bNode *node) initexecfunc, void(*)(struct bNode *node, void *nodedata) freeexecfunc, void(*)(void *data, int thread, struct bNode *, void *nodedata, struct bNodeStack **, struct bNodeStack **) newexecfunc)
Definition at line 1800 of file node.c.
References bNodeType::freeexecfunc, bNodeType::initexecfunc, and bNodeType::newexecfunc.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_gpu (struct bNodeType * ntype, int(*)(struct GPUMaterial *mat, struct bNode *node, struct GPUNodeStack *in, struct GPUNodeStack *out) gpufunc)
Definition at line 1815 of file node.c.
References bNodeType::gpufunc.
Referenced by register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), and register_node_type_sh_volume_transparent().
void node_type_gpu_ext (struct bNodeType * ntype, int(*)(struct GPUMaterial *mat, struct bNode *node, void *nodedata, struct GPUNodeStack *in, struct GPUNodeStack *out) gpuextfunc)
Definition at line 1820 of file node.c.
References bNodeType::gpuextfunc.
Referenced by register_node_type_sh_group().
void node_type_group_edit (struct bNodeType * ntype, struct bNodeTree *(*)(struct bNode *node) group_edit_get, struct bNodeTree *(*)(struct bNode *node, int edit) group_edit_set, void(*)(struct bNode *node) group_edit_clear)
Definition at line 1785 of file node.c.
References bNodeType::group_edit_clear, bNodeType::group_edit_get, and bNodeType::group_edit_set.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_init (struct bNodeType * ntype, void(*)(struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp) initfunc)
Definition at line 1731 of file node.c.
References bNodeType::initfunc.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_distance_matte(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_movieclip(), register_node_type_cmp_normal(), register_node_type_cmp_output_file(), register_node_type_cmp_rgb(), register_node_type_cmp_rotate(), register_node_type_cmp_splitviewer(), register_node_type_cmp_tonemap(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_bricks(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_group(), register_node_type_tex_image(), register_node_type_tex_output(), and register_node_type_tex_valtorgb().
void node_type_internal_connect (struct bNodeType * ntype, ListBase(*)(struct bNodeTree *, struct bNode *) internal_connect)
Referenced by register_node_type_cmp_composite(), register_node_type_cmp_splitviewer(), register_node_type_cmp_viewer(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_tex_output(), and register_node_type_tex_viewer().
void node_type_label (struct bNodeType * ntype, const char *(*)(struct bNode *) labelfunc)
Definition at line 1761 of file node.c.
References bNodeType::labelfunc.
Referenced by register_node_type_cmp_filter(), register_node_type_cmp_group(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_moviedistortion(), register_node_type_sh_group(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_vect_math(), register_node_type_tex_group(), register_node_type_tex_math(), and register_node_type_tex_mix_rgb().
void node_type_size (struct bNodeType * ntype, int width, int minwidth, int maxwidth)
Definition at line 1741 of file node.c.
References FLT_MAX, bNodeType::maxwidth, bNodeType::minwidth, and bNodeType::width.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_socket_templates (struct bNodeType * ntype, struct bNodeSocketTemplate * inputs, struct bNodeSocketTemplate * outputs)
Definition at line 1725 of file node.c.
References inputs, bNodeType::inputs, outputs, and bNodeType::outputs.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_storage (struct bNodeType * ntype, const char * storagename, void(*)(struct bNode *) freestoragefunc, void(*)(struct bNode *, struct bNode *) copystoragefunc)
Definition at line 1751 of file node.c.
References BLI_strncpy(), bNodeType::copystoragefunc, bNodeType::freestoragefunc, and bNodeType::storagename.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_distance_matte(), register_node_type_cmp_glare(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_image(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_output_file(), register_node_type_cmp_splitviewer(), register_node_type_cmp_tonemap(), register_node_type_cmp_valtorgb(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_math(), register_node_type_sh_mix_shader(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_valtorgb(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_distance(), register_node_type_tex_image(), register_node_type_tex_math(), register_node_type_tex_output(), and register_node_type_tex_valtorgb().
void node_type_template (struct bNodeType * ntype, struct bNodeTemplate(*)(struct bNode *) templatefunc)
Definition at line 1766 of file node.c.
References bNodeType::templatefunc.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_tree (struct bNodeType * ntype, void(*)(struct bNodeTree *) inittreefunc, void(*)(struct bNodeTree *) updatetreefunc)
Definition at line 1779 of file node.c.
References bNodeType::inittreefunc, and bNodeType::updatetreefunc.
void node_type_update (struct bNodeType * ntype, void(*)(struct bNodeTree *ntree, struct bNode *node) updatefunc, void(*)(struct bNodeTree *ntree, struct bNode *node, struct ID *id) verifyfunc)
Definition at line 1771 of file node.c.
References bNodeType::updatefunc, and bNodeType::verifyfunc.
Referenced by register_node_type_cmp_group(), register_node_type_cmp_image(), register_node_type_cmp_output_file(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_valid (struct bNodeType * ntype, int(*)(struct bNodeTree *ntree, struct bNodeTemplate *ntemp) validfunc)
Definition at line 1736 of file node.c.
References bNodeType::validfunc.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
struct bNodeLink* nodeAddLink (struct bNodeTree * ntree, struct bNode * fromnode, struct bNodeSocket * fromsock, struct bNode * tonode, struct bNodeSocket * tosock) [read]
Definition at line 433 of file node.c.
References BLI_addtail(), ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNodeTree::inputs, bNode::inputs, link(), bNodeTree::links, MEM_callocN(), bNodeSocket::next, NTREE_UPDATE_LINKS, NULL, bNodeTree::outputs, bNode::outputs, bNodeLink::tonode, bNodeLink::tosock, and bNodeTree::update.
Referenced by ED_node_composit_default(), ED_node_link_insert(), ED_node_shader_default(), ED_node_texture_default(), node_group_expose_all_sockets(), node_group_make_from_selected(), node_link_viewer(), node_socket_add_replace(), and snode_autoconnect_input().
struct bNode* nodeAddNode (struct bNodeTree * ntree, struct bNodeTemplate * ntemp) [read]
Definition at line 318 of file node.c.
References BLI_addtail(), BLI_strncpy(), bNodeType::flag, bNode::flag, bNodeType::height, bNode::height, bNodeType::initfunc, MEM_callocN(), bNode::miniwidth, bNode::name, node_add_sockets_from_type(), node_get_type(), NODE_MAXSTR, NODE_SELECT, nodeLabel(), bNodeTree::nodes, nodeUniqueName(), nodeValid(), NTREE_UPDATE_NODES, NULL, bNodeType::type, bNode::type, bNodeTemplate::type, bNode::typeinfo, bNodeTree::update, bNodeType::width, and bNode::width.
Referenced by ED_node_composit_default(), ED_node_shader_default(), ED_node_texture_default(), node_add_node(), node_group_make_from_selected(), and node_socket_add_replace().
struct bNodeSocket* nodeAddSocket (struct bNodeTree * ntree, struct bNode * node, int in_out, const char * name, int type) [read]
Definition at line 177 of file node.c.
References BLI_addtail(), bNode::inputs, make_socket(), NODE_UPDATE, bNode::outputs, SOCK_IN, SOCK_OUT, and bNode::update.
Referenced by cmp_node_image_add_multilayer_outputs(), node_add_input_from_template(), node_add_output_from_template(), node_forloop_init(), node_whileloop_init(), and ntreeCompositOutputFileAddSocket().
void nodeAddToPreview (struct bNode * , float * , int , int , int)
Definition at line 833 of file node.c.
References linearrgb_to_srgb_uchar4(), bNode::preview, bNodePreview::rect, rgba_float_to_uchar(), and bNodePreview::xsize.
Referenced by node_shader_exec_material(), node_shader_exec_output(), node_shader_exec_texture(), and tex_do_preview().
void nodeAttachNode (struct bNode * node, struct bNode * parent)
Definition at line 608 of file node.c.
References bNode::locx, bNode::locy, nodeSpaceCoords(), and bNode::parent.
Referenced by node_frame_attach_nodes().
void nodeClearActiveID (struct bNodeTree * ntree, short idtype)
Definition at line 1333 of file node.c.
References ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNode::next, NODE_ACTIVE_ID, bNodeTree::nodes, and NULL.
Referenced by ED_node_set_active().
struct bNode* nodeCopyNode (struct bNodeTree * ntree, struct bNode * node) [read]
Definition at line 378 of file node.c.
References BLI_addtail(), BLI_duplicatelist(), bNodeSocket::cache, bNodeType::copystoragefunc, bNodeSocket::default_value, ListBase::first, bNode::inputs, MEM_callocN(), bNode::new_node, bNodeSocket::new_sock, bNodeSocket::next, node_socket_copy_default_value(), node_socket_make_default_value(), bNodeTree::nodes, nodeUniqueName(), NTREE_UPDATE_NODES, NULL, bNode::outputs, bNode::preview, bNodeSocket::stack_index, bNodeSocket::type, bNode::typeinfo, and bNodeTree::update.
Referenced by node_duplicate_exec(), and ntreeCopyTree().
int nodeCountSocketLinks (struct bNodeTree * ntree, struct bNodeSocket * sock)
Definition at line 1252 of file node.c.
References ListBase::first, bNodeLink::fromsock, link(), bNodeTree::links, bNodeLink::next, and bNodeLink::tosock.
Referenced by node_group_expose_all_sockets(), node_link_init(), node_link_modal(), node_remove_extra_links(), node_set_hidden_sockets(), and node_socket_add_replace().
void nodeDetachNode (struct bNode * node)
Definition at line 619 of file node.c.
References bNode::locx, bNode::locy, nodeSpaceCoords(), NULL, and bNode::parent.
Referenced by ED_node_update_hierarchy(), node_frame_attach_nodes(), and node_unlink_attached().
int nodeDynamicUnlinkText (struct ID * txtid)
struct bNodeLink* nodeFindLink (struct bNodeTree * ntree, struct bNodeSocket * from, struct bNodeSocket * to) [read]
Definition at line 1239 of file node.c.
References ListBase::first, bNodeLink::fromsock, link(), bNodeTree::links, bNodeLink::next, NULL, and bNodeLink::tosock.
Referenced by node_link_modal().
int nodeFindNode (struct bNodeTree * ntree, struct bNodeSocket * sock, struct bNode ** nodep, int * sockindex, int * in_out)
Definition at line 253 of file node.c.
References ListBase::first, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, NULL, bNode::outputs, SOCK_IN, and SOCK_OUT.
struct bNode* nodeFindNodebyName (struct bNodeTree * ntree, const char * name) [read]
Definition at line 247 of file node.c.
References BLI_findstring(), and bNodeTree::nodes.
Referenced by animchan_sync_fcurve(), and skip_fcurve_selected_data().
void nodeFreeNode (struct bNodeTree * ntree, struct bNode * node)
Definition at line 897 of file node.c.
References BLI_remlink(), bNodeSocket::default_value, ListBase::first, bNodeTreeType::free_node_cache, bNodeType::freestoragefunc, bNode::inputs, MEM_freeN(), bNodeSocket::next, node_socket_free_default_value(), node_unlink_attached(), nodeFreePreview(), bNodeTree::nodes, nodeUnlinkNode(), NTREE_UPDATE_NODES, ntreeGetType(), bNode::outputs, bNodeSocket::type, bNodeTree::type, bNode::typeinfo, and bNodeTree::update.
Referenced by localize(), node_delete_exec(), node_delete_reconnect_exec(), node_group_ungroup(), node_remove_linked(), ntreeFreeTree(), and ntreeInitTypes().
void nodeFreePreview (struct bNode * node)
Definition at line 755 of file node.c.
References MEM_freeN(), NULL, bNode::preview, and bNodePreview::rect.
Referenced by local_sync(), nodeFreeNode(), and ntreeLocalMerge().
struct bNode* nodeGetActive (struct bNodeTree * ntree) [read]
Definition at line 1264 of file node.c.
References ListBase::first, bNode::flag, bNode::next, NODE_ACTIVE, bNodeTree::nodes, and NULL.
Referenced by active_node_panel(), active_node_poll(), editnode_get_active(), node_group_edit_exec(), node_group_edit_invoke(), node_group_ungroup_exec(), node_output_file_add_socket_exec(), node_output_file_remove_active_socket_exec(), node_sockets_panel(), and snode_make_group_editable().
struct bNode* nodeGetActiveID (struct bNodeTree * ntree, short idtype) [read]
Definition at line 1277 of file node.c.
References ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNode::next, NODE_ACTIVE_ID, NODE_GROUP_EDIT, bNodeTree::nodes, and NULL.
Referenced by give_current_material_texture(), give_current_material_texture_node(), give_node_material(), gpu_active_node_material(), has_current_material_texture(), and set_current_material_texture().
struct bNode* nodeGetActiveTexture (struct bNodeTree * ntree) [read]
Definition at line 248 of file node_shader_util.c.
References ListBase::first, bNode::flag, bNode::id, bNode::next, NODE_ACTIVE_TEXTURE, NODE_GROUP_EDIT, bNodeTree::nodes, and NULL.
Referenced by ED_object_assign_active_image(), and ED_object_get_active_image().
void nodeGroupEditClear (struct bNode * node)
Definition at line 1686 of file node.c.
References bNodeType::group_edit_clear, and bNode::typeinfo.
Referenced by node_group_edit_clear(), and snode_make_group_editable().
struct bNodeTree* nodeGroupEditGet (struct bNode * node) [read]
Definition at line 1668 of file node.c.
References bNodeType::group_edit_get, NULL, and bNode::typeinfo.
Referenced by editnode_get_active(), node_tree_from_ID(), and node_tree_get_editgroup().
struct bNodeTree* nodeGroupEditSet (struct bNode * node, int edit) [read]
Definition at line 1676 of file node.c.
References bNodeType::group_edit_get, bNodeType::group_edit_set, NULL, and bNode::typeinfo.
Referenced by snode_make_group_editable().
struct bNodeSocket* nodeInsertSocket (struct bNodeTree * ntree, struct bNode * node, int in_out, struct bNodeSocket * next_sock, const char * name, int type) [read]
Definition at line 190 of file node.c.
References BLI_insertlinkbefore(), bNode::inputs, make_socket(), NODE_UPDATE, bNode::outputs, SOCK_IN, SOCK_OUT, and bNode::update.
void nodeInternalRelink (struct bNodeTree * ntree, struct bNode * node)
Definition at line 545 of file node.c.
References BLI_freelistN(), ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNodeType::internal_connect, bNodeSocket::link, link(), bNodeTree::links, bNodeLink::next, nodeRemLink(), NTREE_UPDATE_LINKS, bNodeLink::tonode, bNodeLink::tosock, bNode::typeinfo, and bNodeTree::update.
Referenced by detach_links_exec(), localize(), and node_delete_reconnect_exec().
const char* nodeLabel (struct bNode * node)
Definition at line 1658 of file node.c.
References IFACE_, bNode::label, bNodeType::labelfunc, bNodeType::name, and bNode::typeinfo.
Referenced by node_draw_basis(), node_draw_hidden(), and nodeAddNode().
void nodeMakeDynamicType (struct bNode * node)
Definition at line 356 of file node.c.
References BLI_strncpy(), ListBase::first, MEM_callocN(), bNodeType::name, bNodeType::next, NODE_DYNAMIC, bNodeTreeType::node_types, NTREE_SHADER, ntreeGetType(), bNodeType::type, and bNode::typeinfo.
struct bNodeTemplate nodeMakeTemplate (struct bNode * node) [read]
Definition at line 1692 of file node.c.
References bNodeTemplate::type.
Referenced by node_group_valid().
void nodeRegisterType (struct bNodeTreeType * ttype, struct bNodeType * ntype)
Definition at line 1841 of file node.c.
References BLI_addtail(), is_nodetype_registered(), bNodeTreeType::node_types, NULL, and bNodeType::type.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_dynamic(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void nodeRemLink (struct bNodeTree * ntree, struct bNodeLink * link)
Definition at line 521 of file node.c.
References BLI_remlink(), bNodeSocket::link, bNodeTree::links, MEM_freeN(), NTREE_UPDATE_LINKS, NULL, bNodeLink::tosock, and bNodeTree::update.
Referenced by cut_links_exec(), node_group_ungroup(), node_link_cancel(), node_link_init(), node_link_modal(), node_link_viewer(), node_remove_extra_links(), node_socket_add_replace(), node_socket_disconnect(), nodeInternalRelink(), nodeRemoveAllSockets(), nodeRemoveSocket(), nodeRemSocketLinks(), nodeUnlinkNode(), and snode_autoconnect_input().
void nodeRemoveAllSockets (struct bNodeTree * ntree, struct bNode * node)
Definition at line 224 of file node.c.
References BLI_freelistN(), bNodeSocket::default_value, ListBase::first, bNodeLink::fromnode, bNode::inputs, link(), bNodeTree::links, bNodeSocket::next, bNodeLink::next, next, node_socket_free_default_value(), NODE_UPDATE, nodeRemLink(), bNode::outputs, bNodeLink::tonode, bNodeSocket::type, and bNode::update.
void nodeRemoveSocket (struct bNodeTree * ntree, struct bNode * node, struct bNodeSocket * sock)
Definition at line 203 of file node.c.
References BLI_remlink(), bNodeSocket::default_value, ListBase::first, bNodeLink::fromsock, bNode::inputs, link(), bNodeTree::links, MEM_freeN(), bNodeLink::next, next, node_socket_free_default_value(), NODE_UPDATE, nodeRemLink(), bNode::outputs, bNodeLink::tosock, bNodeSocket::type, and bNode::update.
Referenced by cmp_node_image_verify_outputs(), do_versions_nodetree_multi_file_output_format_2_62_1(), group_verify_socket_list(), ntreeCompositOutputFileRemoveActiveSocket(), and verify_socket_template_list().
void nodeRemSocketLinks (struct bNodeTree * ntree, struct bNodeSocket * sock)
Definition at line 531 of file node.c.
References ListBase::first, bNodeLink::fromsock, link(), bNodeTree::links, bNodeLink::next, next, nodeRemLink(), NTREE_UPDATE_LINKS, bNodeLink::tosock, and bNodeTree::update.
Referenced by node_group_remove_socket(), and snode_autoconnect_input().
void nodeSetActive (struct bNodeTree * ntree, struct bNode * node)
Definition at line 1345 of file node.c.
References ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNodeType::nclass, bNode::next, NODE_ACTIVE, NODE_ACTIVE_ID, NODE_ACTIVE_TEXTURE, NODE_CLASS_TEXTURE, bNodeTree::nodes, and bNode::typeinfo.
Referenced by ED_node_composit_default(), ED_node_set_active(), ED_node_shader_default(), ED_node_texture_default(), node_browse_text_cb(), node_group_make_exec(), and node_socket_add_replace().
int nodeSetActiveID (struct bNodeTree * ntree, short idtype, struct ID * id)
Definition at line 1300 of file node.c.
References FALSE, ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNode::next, NODE_ACTIVE_ID, NODE_GROUP_EDIT, bNodeTree::nodes, NULL, and TRUE.
Referenced by node_area_listener().
void nodeShaderSynchronizeID (struct bNode * node, int copyto)
Definition at line 127 of file node_shader_util.c.
References Material::alpha, Material::amb, copy_v3_v3(), bNodeSocket::default_value, ELEM, Material::emit, ListBase::first, bNode::id, bNode::inputs, MAT_IN_ALPHA, MAT_IN_AMB, MAT_IN_COLOR, MAT_IN_EMIT, MAT_IN_MIR, MAT_IN_RAY_MIRROR, MAT_IN_REFL, MAT_IN_SPEC, MAT_IN_SPECTRA, MAT_IN_TRANSLUCENCY, Material::mirr, bNodeSocket::next, nodeSocketIsHidden(), NULL, Material::r, Material::ray_mirror, Material::ref, SH_NODE_MATERIAL, SH_NODE_MATERIAL_EXT, Material::specr, Material::spectra, Material::translucency, and bNode::type.
Referenced by node_draw_basis(), and node_sync_cb().
int nodeSocketIsHidden (struct bNodeSocket * sock)
Definition at line 1368 of file node.c.
References bNodeSocket::flag, SOCK_HIDDEN, and SOCK_UNAVAIL.
Referenced by node_draw_basis(), node_draw_hidden(), node_find_indicated_socket(), node_group_expose_all_sockets(), node_link_viewer(), node_update_basis(), node_update_hidden(), nodeShaderSynchronizeID(), socket_best_match(), and socket_is_available().
void nodeSocketSetType (struct bNodeSocket * sock, int type)
Definition at line 1373 of file node.c.
References bNodeSocket::default_value, node_socket_convert_default_value(), node_socket_free_default_value(), node_socket_init_default_value(), node_socket_make_default_value(), and bNodeSocket::type.
Referenced by update_output_file().
void nodeSpaceCoords (struct bNode * node, float * locx, float * locy)
Definition at line 595 of file node.c.
References bNode::locx, bNode::locy, nodeSpaceCoords(), and bNode::parent.
Referenced by node_update_basis(), node_update_frame(), node_update_group(), node_update_hidden(), nodeAttachNode(), nodeDetachNode(), and nodeSpaceCoords().
void nodeUniqueName (struct bNodeTree * ntree, struct bNode * node)
Definition at line 313 of file node.c.
References BLI_uniquename(), bNode::name, bNodeSocket::name, and bNodeTree::nodes.
Referenced by do_versions(), nodeAddNode(), and nodeCopyNode().
void nodeUnlinkNode (struct bNodeTree * ntree, struct bNode * node)
Definition at line 857 of file node.c.
References ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNode::inputs, link(), bNodeTree::links, bNodeSocket::next, bNodeLink::next, next, NODE_UPDATE, nodeRemLink(), NULL, bNode::outputs, bNodeLink::tonode, bNodeLink::tosock, and bNode::update.
Referenced by nodeFreeNode().
void nodeUpdate (struct bNodeTree * ntree, struct bNode * node)
Definition at line 1592 of file node.c.
References ntreeGetType(), bNodeTree::type, bNode::typeinfo, bNode::update, bNodeTreeType::update_node, and bNodeType::updatefunc.
Referenced by dag_id_flush_update(), dag_tag_renderlayers(), ED_node_changed_update(), node_animation_properties(), node_socket_add_replace(), node_socket_disconnect(), node_socket_remove(), ntree_render_scenes(), ntreeCompositForceHidden(), ntreeCompositTagAnimated(), ntreeCompositTagGenerators(), ntreeCompositTagRender(), ntreeTexTagAnimated(), and snode_update().
int nodeUpdateID (struct bNodeTree * ntree, struct ID * id)
Definition at line 1604 of file node.c.
References ELEM, FALSE, ListBase::first, bNode::id, bNode::next, NODE_UPDATE_ID, bNodeTree::nodes, ntreeGetType(), NULL, TRUE, bNodeTree::type, bNode::typeinfo, bNode::update, bNodeTreeType::update_node, and bNodeType::updatefunc.
Referenced by BKE_image_signal(), ED_node_changed_update(), node_area_listener(), render_endjob(), snode_update(), and special_aftertrans_update().
int nodeValid (struct bNodeTree * ntree, struct bNodeTemplate * ntemp)
Definition at line 1645 of file node.c.
References node_get_type(), bNodeTemplate::type, and bNodeType::validfunc.
Referenced by node_group_valid(), and nodeAddNode().
struct bNodeTree* ntreeAddTree (const char * name, int type, int nodetype) [read]
Definition at line 632 of file node.c.
References alloc_libblock(), BLI_strncpy(), ELEM3, G, bNodeTree::id, ID_NT, bNodeType::inittreefunc, MEM_callocN(), ID::name, node_get_type(), bNodeTree::nodetype, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeInitTypes(), bNodeSocket::type, and bNodeTree::type.
Referenced by do_node_add_group(), ED_node_composit_default(), ED_node_shader_default(), ED_node_texture_default(), new_node_tree_exec(), and node_group_make_from_selected().
void ntreeClearPreview (struct bNodeTree * ntree)
Definition at line 815 of file node.c.
References ListBase::first, bNode::flag, bNodeType::flag, bNode::id, bNode::next, NODE_GROUP, NODE_GROUP_EDIT, NODE_PREVIEW, nodeClearPreview(), bNodeTree::nodes, ntreeClearPreview(), NULL, bNode::type, and bNode::typeinfo.
Referenced by ntreeClearPreview().
struct bNodeTreeExec* ntreeCompositBeginExecTree (struct bNodeTree * ntree, int use_tree_data) [read]
Definition at line 260 of file node_composite_tree.c.
References bNodeSocket::cache, CMP_NODE_CURVE_RGB, CMP_NODE_CURVE_VEC, CMP_NODE_HUECORRECT, CMP_NODE_TIME, curvemapping_initialize(), curvemapping_premultiply(), bNodeStack::data, ELEM4, bNode::exec, exec(), bNodeTree::execdata, ListBase::first, bNodeSocket::next, bNode::next, node_get_socket_stack(), bNodeTree::nodes, bNodeTreeExec::nodetree, ntree_exec_begin(), ntreeSetOutput(), NULL, bNode::outputs, bNodeTreeExec::stack, bNode::storage, and bNode::type.
Referenced by group_initexec(), and ntreeCompositExecTree().
void ntreeCompositClearTags (struct bNodeTree * ntree)
Definition at line 895 of file node_composite_tree.c.
References ListBase::first, bNode::id, bNode::need_exec, bNode::next, NODE_GROUP, bNodeTree::nodes, ntreeCompositClearTags(), NULL, and bNode::type.
Referenced by ntreeCompositClearTags(), and render_endjob().
void ntreeCompositEndExecTree (struct bNodeTreeExec * exec, int use_tree_data)
Definition at line 311 of file node_composite_tree.c.
References bNodeSocket::cache, CMP_NODE_CURVE_RGB, curvemapping_premultiply(), bNodeStack::data, bNodeTree::execdata, ListBase::first, bNode::need_exec, bNodeSocket::next, bNode::next, node_get_socket_stack(), bNodeTree::nodes, bNodeTreeExec::nodetree, ntree_exec_end(), NULL, bNode::outputs, bNodeTreeExec::stack, bNode::storage, and bNode::type.
Referenced by group_freeexec(), ntreeCompositExecTree(), and ntreeFreeTree().
void ntreeCompositExecTree (struct bNodeTree * ntree, struct RenderData * rd, int do_previews)
Definition at line 578 of file node_composite_tree.c.
References BLI_available_threads(), BLI_end_threads(), BLI_init_threads(), BLI_insert_thread(), BLI_remove_thread(), BLI_snprintf(), BLI_srandom(), RenderData::cfra, bNode::exec, exec(), exec_composite_node(), bNodeTree::execdata, ListBase::first, freeExecutableNode(), G, getExecutableNode(), bNode::name, bNode::next, bNodeExec::node, NODE_FINISHED, NODE_PROCESSING, NODE_READY, bNodeTreeExec::nodeexec, bNodeTree::nodes, ntree_composite_texnode(), ntreeCompositBeginExecTree(), ntreeCompositEndExecTree(), ntreeInitPreview(), NULL, PIL_sleep_ms(), bNodeTree::prh, bNodeTree::progress, R_COMP_CROP, R_COMP_FREE, ThreadData::rd, RenderData::scemode, bNodeTree::sdh, setExecutableNodes(), bNodeTreeExec::stack, ThreadData::stack, bNodeTree::stats_draw, str, bNodeTree::tbh, bNodeTree::test_break, bNode::threaddata, RenderData::threads, and threads.
Referenced by compo_startjob(), do_merge_fullsample(), do_render_composite_fields_blur_3d(), and image_record_composite_apply().
void ntreeCompositForceHidden (struct bNodeTree * ntree, struct Scene * scene)
Definition at line 747 of file node_composite_tree.c.
References BLI_findlink(), CMP_NODE_IMAGE, CMP_NODE_R_LAYERS, bNode::custom1, ListBase::first, force_hidden_passes(), bNode::id, RenderData::layers, bNode::next, bNodeTree::nodes, nodeUpdate(), NULL, Scene::r, and bNode::type.
Referenced by node_add_node(), and snode_set_context().
struct bNodeSocket* ntreeCompositOutputFileAddSocket (struct bNodeTree * ntree, struct bNode * node, const char * name, struct ImageFormatData * im_format) [read]
Definition at line 48 of file node_composite_outputFile.c.
References NodeImageMultiFile::active_input, BKE_imtype_is_movie(), BLI_findindex(), NodeImageMultiFileSocket::format, ImageFormatData::imtype, bNode::inputs, MEM_callocN(), nodeAddSocket(), R_IMF_IMTYPE_OPENEXR, SOCK_IN, SOCK_RGBA, SOCK_STRUCT_OUTPUT_FILE, bNodeSocket::storage, bNode::storage, bNodeSocket::struct_type, and NodeImageMultiFileSocket::use_node_format.
Referenced by do_versions_nodetree_multi_file_output_format_2_62_1(), init_output_file(), and node_output_file_add_socket_exec().
int ntreeCompositOutputFileRemoveActiveSocket (struct bNodeTree * ntree, struct bNode * node)
Definition at line 72 of file node_composite_outputFile.c.
References NodeImageMultiFile::active_input, BLI_countlist(), BLI_findlink(), bNode::inputs, MEM_freeN(), nodeRemoveSocket(), bNodeSocket::storage, and bNode::storage.
Referenced by node_output_file_remove_active_socket_exec().
int ntreeCompositTagAnimated (struct bNodeTree * ntree)
Definition at line 842 of file node_composite_tree.c.
References CMP_NODE_IMAGE, CMP_NODE_MOVIECLIP, CMP_NODE_TIME, CMP_NODE_TRANSFORM, ELEM, ListBase::first, bNode::id, if(), IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, bNode::next, node_animation_properties(), NODE_GROUP, bNodeTree::nodes, nodeUpdate(), ntreeCompositTagAnimated(), NULL, Image::source, and bNode::type.
Referenced by do_merge_fullsample(), do_render_composite_fields_blur_3d(), ED_update_for_newframe(), image_record_composite_apply(), and ntreeCompositTagAnimated().
void ntreeCompositTagGenerators (struct bNodeTree * ntree)
Definition at line 882 of file node_composite_tree.c.
References CMP_NODE_IMAGE, CMP_NODE_R_LAYERS, ELEM, ListBase::first, bNode::next, bNodeTree::nodes, nodeUpdate(), NULL, and bNode::type.
void ntreeCompositTagRender (struct Scene * sce)
Definition at line 774 of file node_composite_tree.c.
References CMP_NODE_COMPOSITE, CMP_NODE_TEXTURE, ListBase::first, G, bNode::id, Scene::id, bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, nodeUpdate(), and bNode::type.
Referenced by do_merge_fullsample(), do_render_composite_fields_blur_3d(), node_read_renderlayers_exec(), and render_initialize_from_main().
struct bNodeTree* ntreeCopyTree (struct bNodeTree * ntree) [read]
Definition at line 665 of file node.c.
References BLI_duplicatelist(), copy_libblock(), copy_libblock_data(), bNodeSocket::default_value, bNodeTree::execdata, ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, G, bNodeTree::gpd, bNodeSocket::groupsock, bNodeTree::id, id_us_plus(), bNodeTree::inputs, ListBase::last, bNodeSocket::link, link(), bNodeTree::links, MEM_dupallocN(), bNode::new_node, bNodeSocket::new_sock, bNodeLink::next, bNodeSocket::next, bNode::next, ID::next, node_socket_copy_default_value(), node_socket_make_default_value(), nodeCopyNode(), bNodeTree::nodes, NULL, bNodeTree::outputs, bNode::parent, bNodeLink::tonode, bNodeLink::tosock, TRUE, and bNodeSocket::type.
Referenced by copy_lamp(), copy_matcopybuf(), copy_material(), copy_scene(), copy_texture(), copy_world(), id_copy(), node_group_ungroup(), ntreeLocalize(), ntreeMakeLocal(), and paste_matcopybuf().
void ntreeFreeCache (struct bNodeTree * ntree)
Definition at line 980 of file node.c.
References bNodeTreeType::free_cache, ntreeGetType(), NULL, and bNodeTree::type.
Referenced by do_render_composite_fields_blur_3d(), and node_group_make_from_selected().
void ntreeFreeTree (struct bNodeTree * ntree)
Definition at line 935 of file node.c.
References BKE_free_animdata(), BLI_freelistN(), bNodeSocket::default_value, bNodeTree::execdata, id_us_min(), bNodeSocket::next, bNode::next, next, node_socket_free_default_value(), nodeFreeNode(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeCompositEndExecTree(), ntreeShaderEndExecTree(), ntreeTexEndExecTree(), NULL, bNodeSocket::type, and bNodeTree::type.
Referenced by free_lamp(), free_libblock(), free_matcopybuf(), free_material(), free_scene(), free_texture(), free_world(), ntreeLocalMerge(), and paste_matcopybuf().
void ntreeGetDependencyList (struct bNodeTree * ntree, struct bNode *** deplist, int * totnodes)
Definition at line 1426 of file node.c.
References bNode::done, ListBase::first, bNode::level, MEM_callocN(), bNode::next, node_get_deplist_recurs(), bNodeTree::nodes, and NULL.
Referenced by ntree_exec_begin().
struct bNodeType* ntreeGetNodeType (struct bNodeTree * ntree) [read]
Definition at line 108 of file node.c.
References node_get_type(), and bNodeTree::nodetype.
struct bNodeSocketType* ntreeGetSocketType (int type) [read]
Definition at line 113 of file node.c.
References node_socket_type_init(), NULL, NUM_SOCKET_TYPES, bNodeSocket::type, and types.
Referenced by draw_group_socket(), ED_init_node_butfuncs(), node_draw_basis(), node_group_add_socket(), node_socket_circle_draw(), node_socket_make_default_value(), and write_node_socket().
struct bNodeTreeType* ntreeGetType (int type) [read]
Definition at line 79 of file node.c.
References NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeType_Composite, ntreeType_Shader, ntreeType_Texture, NULL, NUM_NTREE_TYPES, bNodeSocket::type, and types.
Referenced by do_versions(), ED_init_node_butfuncs(), ED_node_generic_update(), free_nodesystem(), init_nodesystem(), lib_verify_nodetree(), node_add_menu(), node_get_type(), node_menu_add(), node_tree_has_type(), nodeFreeNode(), nodeMakeDynamicType(), nodeUpdate(), nodeUpdateID(), ntree_validate_links(), ntreeFreeCache(), ntreeLocalize(), ntreeLocalMerge(), ntreeLocalSync(), ntreeMakeLocal(), ntreeUpdateTree(), ntreeVerifyNodes(), ui_node_menu_column(), and ui_template_node_link_menu().
void ntreeGPUMaterialNodes (struct bNodeTree * ntree, struct GPUMaterial * mat)
Definition at line 159 of file node_shader_tree.c.
References exec(), ntreeExecGPUNodes(), ntreeShaderBeginExecTree(), and ntreeShaderEndExecTree().
Referenced by GPU_material_from_blender().
int ntreeHasType (struct bNodeTree * ntree, int type)
Definition at line 1228 of file node.c.
References ListBase::first, bNode::next, bNodeTree::nodes, and bNode::type.
Referenced by setExecutableNodes().
void ntreeInitPreview (struct bNodeTree * , int xsize, int ysize)
Definition at line 793 of file node.c.
References ListBase::first, bNode::flag, bNodeType::flag, bNode::id, bNode::next, NODE_GROUP, NODE_GROUP_EDIT, node_init_preview(), NODE_PREVIEW, bNodeTree::nodes, ntreeInitPreview(), NULL, bNode::type, and bNode::typeinfo.
Referenced by ntreeCompositExecTree(), ntreeInitPreview(), and preview_prepare_scene().
void ntreeInitTypes (struct bNodeTree * ntree)
Definition at line 131 of file node.c.
References BSET, bNode::custom1, ListBase::first, bNode::id, bNodeTree::init, bNode::name, bNode::next, next, NODE_DYNAMIC, NODE_DYNAMIC_ADDEXIST, node_get_type(), nodeFreeNode(), bNodeTree::nodes, NTREE_TYPE_INIT, NULL, bNode::storage, bNode::type, and bNode::typeinfo.
Referenced by lib_nodetree_init_types_cb(), ntree_exec_begin(), and ntreeAddTree().
struct bNodeTree* ntreeLocalize (struct bNodeTree * ntree) [read]
Definition at line 1140 of file node.c.
References AnimData::action, BKE_animdata_from_id(), ListBase::first, bAction::id, bNodeTree::id, bNodeTreeType::localize, bNode::new_node, bNode::next, bNodeTree::nodes, ntreeCopyTree(), ntreeGetType(), ntreeSetOutput(), NULL, AnimData::tmpact, bNodeTree::type, and ID::us.
Referenced by compo_initjob(), localize_lamp(), localize_material(), localize_texture(), and localize_world().
void ntreeLocalMerge (struct bNodeTree * localtree, struct bNodeTree * ntree)
Definition at line 1203 of file node.c.
References ListBase::first, bNodeTreeType::local_merge, MEM_freeN(), bNode::new_node, bNode::next, nodeFreePreview(), bNodeTree::nodes, ntreeFreeTree(), ntreeGetType(), ntreeNodeExists(), NULL, bNode::preview, bNodePreview::rect, and bNodeTree::type.
Referenced by compo_freejob().
void ntreeLocalSync (struct bNodeTree * localtree, struct bNodeTree * ntree)
Definition at line 1193 of file node.c.
References bNodeTreeType::local_sync, ntreeGetType(), and bNodeTree::type.
Referenced by compo_updatejob(), and shader_preview_updatejob().
void ntreeMakeLocal (struct bNodeTree * ntree)
Definition at line 1080 of file node.c.
References bNodeTreeType::foreach_nodetree, G, MakeLocalCallData::group_id, bNodeTree::id, id_clear_lib_data(), MakeLocalCallData::lib, ID::lib, MakeLocalCallData::local, MakeLocalCallData::new_id, ntreeCopyTree(), ntreeGetType(), ntreeMakeLocal_CheckLocal(), ntreeMakeLocal_LinkNew(), NULL, bNodeTree::type, and ID::us.
Referenced by node_group_edit_set().
int ntreeNodeExists (struct bNodeTree * ntree, struct bNode * testnode)
Definition at line 1121 of file node.c.
References ListBase::first, bNode::next, and bNodeTree::nodes.
Referenced by local_merge(), local_sync(), and ntreeLocalMerge().
int ntreeOutputExists (struct bNode * node, struct bNodeSocket * testsock)
Definition at line 1130 of file node.c.
References ListBase::first, bNodeSocket::next, and bNode::outputs.
Referenced by local_merge().
void ntreeSetOutput (struct bNodeTree * ntree)
Definition at line 991 of file node.c.
References CMP_NODE_OUTPUT_FILE, CMP_NODE_SPLITVIEWER, CMP_NODE_VIEWER, ELEM, ListBase::first, bNode::flag, bNodeType::nclass, bNode::next, NODE_CLASS_OUTPUT, NODE_DO_OUTPUT, bNodeTree::nodes, NTREE_COMPOSIT, bNodeTree::type, bNode::type, and bNode::typeinfo.
Referenced by ntreeCompositBeginExecTree(), ntreeLocalize(), ntreeShaderBeginExecTree(), and update().
struct bNodeTreeExec* ntreeShaderBeginExecTree (struct bNodeTree * ntree, int use_tree_data) [read]
Definition at line 183 of file node_shader_tree.c.
References BLENDER_MAX_THREADS, exec(), bNodeTree::execdata, ListBase::first, MEM_callocN(), bNode::need_exec, bNode::next, bNodeTree::nodes, bNodeTreeExec::nodetree, ntree_exec_begin(), ntreeSetOutput(), and bNodeTreeExec::threadstack.
Referenced by group_initexec(), init_render_material(), ntreeGPUMaterialNodes(), and ntreeShaderExecTree().
void ntreeShaderEndExecTree (struct bNodeTreeExec * exec, int use_tree_data)
Definition at line 221 of file node_shader_tree.c.
References BLENDER_MAX_THREADS, BLI_freelistN(), bNodeTree::execdata, ListBase::first, MEM_freeN(), bNodeThreadStack::next, bNodeTreeExec::nodetree, ntree_exec_end(), NULL, bNodeThreadStack::stack, and bNodeTreeExec::threadstack.
Referenced by end_render_material(), group_freeexec(), ntreeFreeTree(), and ntreeGPUMaterialNodes().
void ntreeShaderExecTree (struct bNodeTree * ntree, struct ShadeInput * shi, struct ShadeResult * shr)
Note:
: preserve material from ShadeInput for material id, nodetree execs change it fix for bug "[#28012] Mat ID messy with shader nodes"
Definition at line 248 of file node_shader_tree.c.
References BLI_lock_thread(), BLI_unlock_thread(), ShadeResult::combined, exec(), bNodeTree::execdata, LOCK_NODES, ShadeInput::mat, ntreeExecThreadNodes(), ntreeGetThreadStack(), ntreeReleaseThreadStack(), ntreeShaderBeginExecTree(), NULL, ShaderCallData::shi, ShaderCallData::shr, and ShadeInput::thread.
Referenced by bake_shade(), shade_input_do_shade(), and shade_ray().
void ntreeShaderGetTexcoMode (struct bNodeTree * ntree, int osa, short * texco, int * mode)
Definition at line 81 of file node_shader_util.c.
References ELEM3, ListBase::first, bNodeSocket::flag, GEOM_OUT_GLOB, GEOM_OUT_NORMAL, GEOM_OUT_ORCO, GEOM_OUT_UV, GEOM_OUT_VCOL, GEOM_OUT_VCOL_ALPHA, GEOM_OUT_VIEW, bNode::id, if(), bNode::inputs, bNodeSocket::link, MA_VERTEXCOL, NEED_UV, bNodeSocket::next, bNode::next, bNodeTree::nodes, NULL, bNode::outputs, R_OSA, SH_NODE_GEOMETRY, SH_NODE_TEXTURE, SOCK_IN_USE, TEX_ENVMAP, TEX_IMAGE, TEX_PLUGIN, TEXCO_GLOB, TEXCO_NORM, TEXCO_ORCO, TEXCO_OSA, TEXCO_UV, TEXCO_VIEW, Tex::type, and bNode::type.
Referenced by do_init_render_material().
void ntreeSwitchID (struct bNodeTree * ntree, struct ID * sce_from, struct ID * sce_to)
Definition at line 741 of file node.c.
References ListBase::first, bNode::id, bNode::next, and bNodeTree::nodes.
Referenced by copy_scene().
struct bNodeTreeExec* ntreeTexBeginExecTree (struct bNodeTree * ntree, int use_tree_data) [read]
Definition at line 158 of file node_texture_tree.c.
References BLENDER_MAX_THREADS, exec(), bNodeTree::execdata, ListBase::first, MEM_callocN(), bNode::need_exec, bNode::next, bNodeTree::nodes, bNodeTreeExec::nodetree, ntree_exec_begin(), and bNodeTreeExec::threadstack.
Referenced by group_initexec(), init_render_texture(), ntree_composite_texnode(), ntreeTexExecTree(), paint_brush_init_tex(), and sculpt_brush_init_tex().
void ntreeTexCheckCyclics (struct bNodeTree * ntree)
Definition at line 145 of file node_texture_util.c.
References bNode::custom1, bNode::custom2, ListBase::first, bNode::id, if(), bNode::next, bNodeTree::nodes, Tex::nodetree, ntreeTexCheckCyclics(), TEX_NODE_TEXTURE, bNode::type, and Tex::use_nodes.
Referenced by ED_node_generic_update(), node_add_node(), and ntreeTexCheckCyclics().
void ntreeTexEndExecTree (struct bNodeTreeExec * exec, int use_tree_data)
Definition at line 207 of file node_texture_tree.c.
References BLENDER_MAX_THREADS, BLI_freelistN(), bNodeTree::execdata, ListBase::first, MEM_freeN(), bNodeThreadStack::next, bNodeTreeExec::nodetree, ntree_exec_end(), NULL, bNodeThreadStack::stack, tex_free_delegates(), and bNodeTreeExec::threadstack.
Referenced by copy_texture(), end_render_texture(), group_freeexec(), ntree_composite_texnode(), ntreeFreeTree(), paint_brush_exit_tex(), and sculpt_brush_exit_tex().
int ntreeTexExecTree (struct bNodeTree * ntree, struct TexResult * target, float * coord, float * dxt, float * dyt, int osatex, short thread, struct Tex * tex, short which_output, int cfra, int preview, struct ShadeInput * shi, struct MTex * mtex)
Referenced by multitex(), and multitex_mtex().
int ntreeTexTagAnimated (struct bNodeTree * ntree)
Definition at line 134 of file node_texture_tree.c.
References ListBase::first, bNode::id, bNode::next, NODE_GROUP, bNodeTree::nodes, nodeUpdate(), ntreeTexTagAnimated(), NULL, TEX_NODE_CURVE_TIME, and bNode::type.
Referenced by ED_update_for_newframe(), and ntreeTexTagAnimated().
void ntreeUpdateTree (struct bNodeTree * ntree)
Definition at line 1543 of file node.c.
References ListBase::first, G, bNodeTree::id, bNode::next, node_get_type(), NODE_UPDATE, bNodeTree::nodes, bNodeTree::nodetype, NTREE_UPDATE, ntree_update_link_pointers(), NTREE_UPDATE_LINKS, ntree_update_node_level(), NTREE_UPDATE_NODES, ntree_validate_links(), ntreeGetType(), ntreeVerifyNodes(), bNodeTree::type, bNode::typeinfo, bNodeTreeType::update, bNode::update, bNodeTree::update, bNodeTreeType::update_node, bNodeType::updatefunc, and bNodeType::updatetreefunc.
Referenced by cut_links_exec(), detach_links_exec(), ED_node_composit_default(), ED_node_link_insert(), ED_node_shader_default(), ED_node_texture_default(), lib_nodetree_do_versions_update_cb(), lib_verify_nodetree(), node_add_node(), node_delete_exec(), node_delete_reconnect_exec(), node_duplicate_exec(), node_group_make_exec(), node_group_make_from_selected(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_group_ungroup(), node_link_modal(), node_link_viewer(), node_make_link_exec(), node_show_cycles_exec(), node_socket_add_replace(), node_socket_disconnect(), node_socket_remove(), node_socket_toggle_exec(), snode_autoconnect(), snode_autoconnect_input(), update_group_input_cb(), and update_group_output_cb().
void ntreeVerifyNodes (struct Main * main, struct ID * id)
Definition at line 1528 of file node.c.
References ListBase::first, bNodeTreeType::foreach_nodetree, bNodeTree::id, ID::next, Main::nodetree, ntree_verify_nodes_cb(), ntreeGetType(), NULL, and NUM_NTREE_TYPES.
Referenced by lib_verify_nodetree(), and ntreeUpdateTree().
void register_node_type_frame (struct bNodeTreeType * ttype)
Definition at line 812 of file node_common.c.
References MEM_callocN(), bNodeType::needs_free, NODE_BACKGROUND, NODE_CLASS_LAYOUT, NODE_FRAME, NODE_NEW_SHADING, NODE_OLD_SHADING, node_type_base(), node_type_compatibility(), node_type_size(), and nodeRegisterType().
Referenced by registerCompositNodes(), registerShaderNodes(), and registerTextureNodes().
void set_node_shader_lamp_loop (void(*)(struct ShadeInput *, struct ShadeResult *) lamp_loop_func)
Referenced by RE_Database_Baking(), and RE_Database_FromScene().
Variable Documentation
void(* node_shader_lamp_loop)(struct ShadeInput *, struct ShadeResult *)
Definition at line 172 of file node_shader_tree.c.
Referenced by node_shader_exec_material(), and set_node_shader_lamp_loop().