Blender: bpy_driver.h File Reference
bpy_driver.h File Reference
Python RNA and Operators
Functions
int bpy_pydriver_create_dict (void)
float BPY_driver_exec (struct ChannelDriver *driver, const float evaltime)
void BPY_driver_reset (void)
Variables
PyObject * bpy_pydriver_Dict
Detailed Description
Definition in file bpy_driver.h.
Function Documentation
float BPY_driver_exec (struct ChannelDriver * driver, const float evaltime)
Definition at line 171 of file bpy_driver.c.
References BLI_countlist(), bpy_pydriver_create_dict(), bpy_pydriver_Dict, bpy_pydriver_update_dict(), BPY_update_rna_module(), DRIVER_FLAG_INVALID, DRIVER_FLAG_RECOMPILE, DRIVER_FLAG_RENAMEVAR, driver_get_variable_value(), ChannelDriver::expr_comp, ChannelDriver::expression, ListBase::first, ChannelDriver::flag, G, G_SCRIPT_AUTOEXEC, i, DriverVar::name, DriverVar::next, NULL, pydriver_error(), tval(), and ChannelDriver::variables.
void BPY_driver_reset (void)
Definition at line 122 of file bpy_driver.c.
References bpy_pydriver_Dict, bpy_pydriver_evaltime_prev, bpy_pydriver_InternStr__frame, FLT_MAX, and NULL.
int bpy_pydriver_create_dict (void)
Definition at line 55 of file bpy_driver.c.
References bpy_pydriver_Dict, mod(), and NULL.
Referenced by bpy_app_driver_dict_get(), and BPY_driver_exec().
Variable Documentation
PyObject* bpy_pydriver_Dict
Definition at line 50 of file bpy_driver.c.
Referenced by bpy_app_driver_dict_get(), BPY_driver_exec(), BPY_driver_reset(), bpy_pydriver_create_dict(), and bpy_pydriver_update_dict().