Blender: btConeTwistConstraint.cpp File Reference
btConeTwistConstraint.cpp File Reference
#include "btConeTwistConstraint.h"
#include "BulletDynamics/Dynamics/btRigidBody.h"
#include "LinearMath/btTransformUtil.h"
#include "LinearMath/btMinMax.h"
#include <new>
Defines
#define CONETWIST_USE_OBSOLETE_SOLVER false
#define CONETWIST_DEF_FIX_THRESH btScalar(.05f)
Functions
SIMD_FORCE_INLINE btScalar computeAngularImpulseDenominator (const btVector3 &axis, const btMatrix3x3 &invInertiaWorld)
static btVector3 vTwist (1, 0, 0)
Define Documentation
#define CONETWIST_DEF_FIX_THRESH btScalar(.05f)
Definition at line 29 of file btConeTwistConstraint.cpp.
Referenced by btConeTwistConstraint::init().
#define CONETWIST_USE_OBSOLETE_SOLVER false
Definition at line 28 of file btConeTwistConstraint.cpp.
Function Documentation
SIMD_FORCE_INLINE btScalar computeAngularImpulseDenominator (const btVector3 & axis, const btMatrix3x3 & invInertiaWorld)
Definition at line 32 of file btConeTwistConstraint.cpp.
Referenced by btConeTwistConstraint::calcAngleInfo2().
static btVector3 vTwist (1 , 0 , 0) [static]
Referenced by btConeTwistConstraint::calcAngleInfo2(), and btConeTwistConstraint::setMotorTargetInConstraintSpace().