Blender: ModifierTypeInfo Struct Reference
ModifierTypeInfo Struct Reference
#include <BKE_modifier.h>
Public Attributes
char name [32]
char structName [32]
int structSize
ModifierTypeType type
ModifierTypeFlag flags
void(* copyData)(struct ModifierData *md, struct ModifierData *target)
void(* deformVerts)(struct ModifierData *md, struct Object *ob, struct DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts, int useRenderParams, int isFinalCalc)
void(* deformMatrices)(struct ModifierData *md, struct Object *ob, struct DerivedMesh *derivedData, float(*vertexCos)[3], float(*defMats)[3][3], int numVerts)
void(* deformVertsEM)(struct ModifierData *md, struct Object *ob, struct BMEditMesh *editData, struct DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts)
void(* deformMatricesEM)(struct ModifierData *md, struct Object *ob, struct BMEditMesh *editData, struct DerivedMesh *derivedData, float(*vertexCos)[3], float(*defMats)[3][3], int numVerts)
struct DerivedMesh *(* applyModifier)(struct ModifierData *md, struct Object *ob, struct DerivedMesh *derivedData, int useRenderParams, int isFinalCalc)
struct DerivedMesh *(* applyModifierEM)(struct ModifierData *md, struct Object *ob, struct BMEditMesh *editData, struct DerivedMesh *derivedData)
void(* initData)(struct ModifierData *md)
CustomDataMask(* requiredDataMask)(struct Object *ob, struct ModifierData *md)
void(* freeData)(struct ModifierData *md)
int(* isDisabled)(struct ModifierData *md, int userRenderParams)
void(* updateDepgraph)(struct ModifierData *md, struct DagForest *forest, struct Scene *scene, struct Object *ob, struct DagNode *obNode)
int(* dependsOnTime)(struct ModifierData *md)
int(* dependsOnNormals)(struct ModifierData *md)
void(* foreachObjectLink)(struct ModifierData *md, struct Object *ob, ObjectWalkFunc walk, void *userData)
void(* foreachIDLink)(struct ModifierData *md, struct Object *ob, IDWalkFunc walk, void *userData)
void(* foreachTexLink)(struct ModifierData *md, struct Object *ob, TexWalkFunc walk, void *userData)
Detailed Description
Definition at line 112 of file BKE_modifier.h.
Member Data Documentation
struct DerivedMesh*(* ModifierTypeInfo::applyModifier)(struct ModifierData *md, struct Object *ob, struct DerivedMesh *derivedData, int useRenderParams, int isFinalCalc) [read]
Definition at line 187 of file BKE_modifier.h.
Referenced by curve_calc_modifiers_post(), curve_calc_orcodm(), editbmesh_calc_modifiers(), get_multires_dm(), mesh_calc_modifiers(), and mesh_create_derived_for_modifier().
struct DerivedMesh*(* ModifierTypeInfo::applyModifierEM)(struct ModifierData *md, struct Object *ob, struct BMEditMesh *editData, struct DerivedMesh *derivedData) [read]
Definition at line 199 of file BKE_modifier.h.
Referenced by editbmesh_calc_modifiers().
void(* ModifierTypeInfo::copyData)(struct ModifierData *md, struct ModifierData *target)
Definition at line 133 of file BKE_modifier.h.
Referenced by modifier_copyData().
void(* ModifierTypeInfo::deformMatrices)(struct ModifierData *md, struct Object *ob, struct DerivedMesh *derivedData, float(*vertexCos)[3], float(*defMats)[3][3], int numVerts)
Definition at line 148 of file BKE_modifier.h.
Referenced by crazyspace_build_sculpt(), and sculpt_get_first_deform_matrices().
void(* ModifierTypeInfo::deformMatricesEM)(struct ModifierData *md, struct Object *ob, struct BMEditMesh *editData, struct DerivedMesh *derivedData, float(*vertexCos)[3], float(*defMats)[3][3], int numVerts)
Definition at line 161 of file BKE_modifier.h.
Referenced by editbmesh_get_first_deform_matrices().
void(* ModifierTypeInfo::deformVerts)(struct ModifierData *md, struct Object *ob, struct DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts, int useRenderParams, int isFinalCalc)
Definition at line 142 of file BKE_modifier.h.
Referenced by crazyspace_build_sculpt(), curve_calc_modifiers_post(), curve_calc_modifiers_pre(), editbmesh_calc_modifiers(), lattice_calc_modifiers(), mesh_calc_modifiers(), mesh_create_derived_for_modifier(), modifier_apply_obdata(), and multiresModifier_reshapeFromDeformMod().
void(* ModifierTypeInfo::deformVertsEM)(struct ModifierData *md, struct Object *ob, struct BMEditMesh *editData, struct DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts)
Definition at line 155 of file BKE_modifier.h.
Referenced by editbmesh_calc_modifiers().
int(* ModifierTypeInfo::dependsOnNormals)(struct ModifierData *md)
Definition at line 272 of file BKE_modifier.h.
Referenced by mesh_calc_modifiers().
int(* ModifierTypeInfo::dependsOnTime)(struct ModifierData *md)
Definition at line 262 of file BKE_modifier.h.
Referenced by mesh_calc_modifiers(), and modifier_dependsOnTime().
ModifierTypeFlag ModifierTypeInfo::flags
Definition at line 125 of file BKE_modifier.h.
Referenced by draw_modifier(), ED_object_modifier_add(), ED_object_modifier_move_down(), ED_object_modifier_move_up(), editbmesh_modifier_is_enabled(), mesh_calc_modifiers(), modifier_add_itemf(), modifier_isEnabled(), modifier_isPreview(), modifier_new(), modifier_supportsMapping(), modifiers_getCageIndex(), and object_support_modifier_type().
void(* ModifierTypeInfo::foreachIDLink)(struct ModifierData *md, struct Object *ob, IDWalkFunc walk, void *userData)
Definition at line 292 of file BKE_modifier.h.
Referenced by modifiers_foreachIDLink().
void(* ModifierTypeInfo::foreachObjectLink)(struct ModifierData *md, struct Object *ob, ObjectWalkFunc walk, void *userData)
Definition at line 281 of file BKE_modifier.h.
Referenced by modifiers_foreachIDLink(), and modifiers_foreachObjectLink().
void(* ModifierTypeInfo::foreachTexLink)(struct ModifierData *md, struct Object *ob, TexWalkFunc walk, void *userData)
Definition at line 302 of file BKE_modifier.h.
Referenced by modifiers_foreachTexLink().
void(* ModifierTypeInfo::freeData)(struct ModifierData *md)
Definition at line 237 of file BKE_modifier.h.
Referenced by modifier_free().
void(* ModifierTypeInfo::initData)(struct ModifierData *md)
Definition at line 212 of file BKE_modifier.h.
Referenced by modifier_new().
int(* ModifierTypeInfo::isDisabled)(struct ModifierData *md, int userRenderParams)
Definition at line 247 of file BKE_modifier.h.
Referenced by curve_calc_modifiers_post(), curve_calc_modifiers_pre(), curve_calc_orcodm(), lattice_calc_modifiers(), mesh_create_derived_for_modifier(), modifier_apply_obdata(), modifier_apply_shape(), modifier_couldBeCage(), modifier_isEnabled(), and modifiers_getCageIndex().
char ModifierTypeInfo::name[32]
Definition at line 114 of file BKE_modifier.h.
Referenced by modifier_new(), and modifier_unique_name().
CustomDataMask(* ModifierTypeInfo::requiredDataMask)(struct Object *ob, struct ModifierData *md)
Definition at line 230 of file BKE_modifier.h.
Referenced by editbmesh_calc_modifiers(), mesh_calc_modifiers(), and modifiers_calcDataMasks().
char ModifierTypeInfo::structName[32]
Definition at line 119 of file BKE_modifier.h.
Referenced by modifier_new(), and write_modifiers().
int ModifierTypeInfo::structSize
Definition at line 122 of file BKE_modifier.h.
Referenced by modifier_new().
ModifierTypeType ModifierTypeInfo::type
Definition at line 124 of file BKE_modifier.h.
Referenced by add_hook_object(), crazyspace_build_sculpt(), curve_calc_modifiers_post(), curve_calc_modifiers_pre(), curve_calc_orcodm(), curve_get_tessellate_point(), do_versions(), draw_modifier(), ED_object_modifier_add(), ED_object_modifier_move_down(), ED_object_modifier_move_up(), editbmesh_calc_modifiers(), editbmesh_get_first_deform_matrices(), lattice_calc_modifiers(), mesh_calc_modifiers(), mesh_create_derived_for_modifier(), modifier_apply_obdata(), modifier_apply_shape(), modifier_nonGeometrical(), modifier_sameTopology(), modifier_supportsMapping(), multires_load_old(), sculpt_get_first_deform_matrices(), and sculpt_modifiers_active().
void(* ModifierTypeInfo::updateDepgraph)(struct ModifierData *md, struct DagForest *forest, struct Scene *scene, struct Object *ob, struct DagNode *obNode)
Definition at line 254 of file BKE_modifier.h.
Referenced by build_dag_object().
The documentation for this struct was generated from the following file:
BKE_modifier.h