Blender: interface_icons.c File Reference
interface_icons.c File Reference
interface
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "MEM_guardedalloc.h"
#include "GPU_extensions.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_brush_types.h"
#include "DNA_object_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "RNA_access.h"
#include "RNA_enum_types.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_icons.h"
#include "BKE_utildefines.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "ED_datafiles.h"
#include "ED_render.h"
#include "UI_interface.h"
#include "UI_interface_icons.h"
#include "interface_intern.h"
Classes
struct IconImage
struct DrawInfo
struct IconTexture
Defines
#define ICON_IMAGE_W 600
#define ICON_IMAGE_H 640
#define ICON_GRID_COLS 26
#define ICON_GRID_ROWS 30
#define ICON_GRID_MARGIN 5
#define ICON_GRID_W 16
#define ICON_GRID_H 16
#define ICON_TYPE_PREVIEW 0
#define ICON_TYPE_TEXTURE 1
#define ICON_TYPE_BUFFER 2
#define ICON_TYPE_VECTOR 3
#define INIT_BRUSH_ICON(icon_id, name)
Typedefs
typedef struct IconImage IconImage
typedef void(* VectorDrawFunc)(int x, int y, int w, int h, float alpha)
typedef struct DrawInfo DrawInfo
typedef struct IconTexture IconTexture
Functions
static void def_internal_icon (ImBuf *bbuf, int icon_id, int xofs, int yofs, int size, int type)
static void def_internal_vicon (int icon_id, VectorDrawFunc drawFunc)
static void viconutil_set_point (GLint pt[2], int x, int y)
static void viconutil_draw_tri (GLint(*pts)[2])
static void viconutil_draw_lineloop (GLint(*pts)[2], int numPoints)
static void viconutil_draw_lineloop_smooth (GLint(*pts)[2], int numPoints)
static void viconutil_draw_points (GLint(*pts)[2], int numPoints, int pointSize)
static void vicon_x_draw (int x, int y, int w, int h, float alpha)
static void vicon_view3d_draw (int x, int y, int w, int h, float alpha)
static void vicon_edit_draw (int x, int y, int w, int h, float alpha)
static void vicon_editmode_hlt_draw (int x, int y, int w, int h, float alpha)
static void vicon_editmode_dehlt_draw (int x, int y, int w, int h, float UNUSED(alpha))
static void vicon_disclosure_tri_right_draw (int x, int y, int w, int UNUSED(h), float alpha)
static void vicon_small_tri_right_draw (int x, int y, int w, int UNUSED(h), float alpha)
static void vicon_disclosure_tri_down_draw (int x, int y, int w, int UNUSED(h), float alpha)
static void vicon_move_up_draw (int x, int y, int w, int h, float UNUSED(alpha))
static void vicon_move_down_draw (int x, int y, int w, int h, float UNUSED(alpha))
static void init_brush_icons (void)
static void init_internal_icons (void)
static void init_iconfile_list (struct ListBase *list)
static void free_iconfile_list (struct ListBase *list)
int UI_iconfile_get_index (const char *filename)
ListBase * UI_iconfile_list (void)
void UI_icons_free (void)
void UI_icons_free_drawinfo (void *drawinfo)
static DrawInfo * icon_create_drawinfo (void)
int UI_icon_get_width (int icon_id)
int UI_icon_get_height (int icon_id)
void UI_icons_init (int first_dyn_id)
static int preview_render_size (enum eIconSizes size)
static void icon_create_rect (struct PreviewImage *prv_img, enum eIconSizes size)
static void icon_set_image (bContext *C, ID *id, PreviewImage *prv_img, enum eIconSizes size)
static void icon_draw_rect (float x, float y, int w, int h, float UNUSED(aspect), int rw, int rh, unsigned int *rect, float alpha, const float rgb[3], short is_preview)
static void icon_draw_texture (float x, float y, float w, float h, int ix, int iy, int UNUSED(iw), int ih, float alpha, const float rgb[3])
static int get_draw_size (enum eIconSizes size)
static void icon_draw_size (float x, float y, int icon_id, float aspect, float alpha, const float rgb[3], enum eIconSizes size, int draw_size, int UNUSED(nocreate), short is_preview)
static void ui_id_preview_image_render_size (bContext *C, ID *id, PreviewImage *pi, int size)
static void ui_id_icon_render (bContext *C, ID *id, int big)
static void ui_id_brush_render (bContext *C, ID *id)
static int ui_id_brush_get_icon (bContext *C, ID *id)
int ui_id_icon_get (bContext *C, ID *id, int big)
static void icon_draw_at_size (float x, float y, int icon_id, float aspect, float alpha, enum eIconSizes size, int nocreate)
void UI_icon_draw_aspect (float x, float y, int icon_id, float aspect, float alpha)
void UI_icon_draw_aspect_color (float x, float y, int icon_id, float aspect, const float rgb[3])
void UI_icon_draw (float x, float y, int icon_id)
void UI_icon_draw_size (float x, float y, int size, int icon_id, float alpha)
void UI_icon_draw_preview (float x, float y, int icon_id)
void UI_icon_draw_preview_aspect (float x, float y, int icon_id, float aspect)
void UI_icon_draw_preview_aspect_size (float x, float y, int icon_id, float aspect, int size)
Variables
static struct ListBase iconfilelist = {NULL, NULL}
static IconTexture icongltex = {0, 0, 0, 0.0f, 0.0f}
Detailed Description
Definition in file interface_icons.c.
Define Documentation
#define ICON_GRID_COLS 26
Definition at line 82 of file interface_icons.c.
Referenced by init_internal_icons().
#define ICON_GRID_H 16
Definition at line 87 of file interface_icons.c.
Referenced by init_internal_icons().
#define ICON_GRID_MARGIN 5
Definition at line 85 of file interface_icons.c.
Referenced by init_internal_icons().
#define ICON_GRID_ROWS 30
Definition at line 83 of file interface_icons.c.
Referenced by init_internal_icons().
#define ICON_GRID_W 16
Definition at line 86 of file interface_icons.c.
Referenced by init_internal_icons().
#define ICON_IMAGE_H 640
Definition at line 80 of file interface_icons.c.
Referenced by init_iconfile_list(), and init_internal_icons().
#define ICON_IMAGE_W 600
Definition at line 79 of file interface_icons.c.
Referenced by init_iconfile_list(), and init_internal_icons().
#define ICON_TYPE_BUFFER 2
Definition at line 99 of file interface_icons.c.
Referenced by def_internal_icon(), icon_draw_size(), init_internal_icons(), and UI_icons_free_drawinfo().
#define ICON_TYPE_PREVIEW 0
Definition at line 97 of file interface_icons.c.
Referenced by icon_create_drawinfo(), and icon_draw_size().
#define ICON_TYPE_TEXTURE 1
Definition at line 98 of file interface_icons.c.
Referenced by def_internal_icon(), icon_draw_size(), and init_internal_icons().
#define ICON_TYPE_VECTOR 3
Definition at line 100 of file interface_icons.c.
Referenced by def_internal_vicon(), and icon_draw_size().
#define INIT_BRUSH_ICON (icon_id, name)
Value:
{                                                                         \
        bbuf = IMB_ibImageFromMemory((unsigned char *)datatoc_ ##name## _png, \
                                     datatoc_ ##name## _png_size,             \
                                     IB_rect, "<brush icon>");                \
        def_internal_icon(bbuf, icon_id, 0, 0, w, ICON_TYPE_BUFFER);          \
        IMB_freeImBuf(bbuf);                                                  \
    } (void)0
Referenced by init_brush_icons().
Typedef Documentation
typedef struct DrawInfo DrawInfo
typedef struct IconImage IconImage
typedef struct IconTexture IconTexture
typedef void(* VectorDrawFunc)(int x, int y, int w, int h, float alpha)
Definition at line 95 of file interface_icons.c.
Function Documentation
static void def_internal_icon (ImBuf * bbuf, int icon_id, int xofs, int yofs, int size, int type) [static]
Definition at line 135 of file interface_icons.c.
References BKE_icon_set(), DrawInfo::buffer, DrawInfo::data, Icon::drawinfo, Icon::drawinfo_free, IconImage::h, ICON_TYPE_BUFFER, ICON_TYPE_TEXTURE, MEM_callocN(), MEM_mallocN(), NULL, Icon::obj, ImBuf::rect, IconImage::rect, size(), DrawInfo::texture, DrawInfo::type, Icon::type, UI_icons_free_drawinfo(), IconImage::w, and ImBuf::x.
Referenced by init_internal_icons().
static void def_internal_vicon (int icon_id, VectorDrawFunc drawFunc) [static]
Definition at line 178 of file interface_icons.c.
References BKE_icon_set(), DrawInfo::data, Icon::drawinfo, Icon::drawinfo_free, ICON_TYPE_VECTOR, MEM_callocN(), NULL, Icon::obj, DrawInfo::type, Icon::type, and DrawInfo::vector.
Referenced by init_internal_icons().
static void free_iconfile_list (struct ListBase * list) [static]
Definition at line 681 of file interface_icons.c.
References BLI_freelinkN(), ListBase::first, IconFile::next, and NULL.
Referenced by UI_icons_free().
static int get_draw_size (enum eIconSizes size) [static]
Definition at line 949 of file interface_icons.c.
References ICON_DEFAULT_HEIGHT, ICON_SIZE_ICON, ICON_SIZE_PREVIEW, and PREVIEW_DEFAULT_HEIGHT.
Referenced by icon_draw_at_size(), and UI_icon_draw_aspect_color().
static DrawInfo* icon_create_drawinfo (void) [static]
Definition at line 742 of file interface_icons.c.
References ICON_TYPE_PREVIEW, MEM_callocN(), NULL, and DrawInfo::type.
Referenced by icon_draw_size(), UI_icon_get_height(), and UI_icon_get_width().
static void icon_create_rect (struct PreviewImage * prv_img, enum eIconSizes size) [static]
Definition at line 829 of file interface_icons.c.
References PreviewImage::changed, PreviewImage::changed_timestamp, G, G_DEBUG, PreviewImage::h, MEM_callocN(), preview_render_size(), PreviewImage::rect, size(), and PreviewImage::w.
Referenced by icon_set_image().
static void icon_draw_at_size (float x, float y, int icon_id, float aspect, float alpha, enum eIconSizes size, int nocreate) [static]
Definition at line 1140 of file interface_icons.c.
References FALSE, get_draw_size(), icon_draw_size(), and NULL.
Referenced by UI_icon_draw_aspect(), UI_icon_draw_preview(), and UI_icon_draw_preview_aspect().
static void icon_draw_rect (float x, float y, int w, int h, float UNUSEDaspect, int rw, int rh, unsigned int * rect, float alpha, const float rgb[3], short is_preview) [static]
Definition at line 862 of file interface_icons.c.
References BLI_assert, glaDrawPixelsSafe(), IB_rect, IMB_allocImBuf(), IMB_freeImBuf(), IMB_scaleImBuf(), NULL, and ImBuf::rect.
Referenced by icon_draw_size().
static void icon_draw_size (float x, float y, int icon_id, float aspect, float alpha, const float rgb[3], enum eIconSizes size, int draw_size, int UNUSEDnocreate, short is_preview) [static]
Definition at line 958 of file interface_icons.c.
References BKE_icon_get(), BKE_previewimg_get(), DrawInfo::buffer, DrawInfo::data, Icon::drawinfo, Icon::drawinfo_free, G, G_DEBUG, IconImage::h, PreviewImage::h, ThemeUI::icon_alpha, icon_create_drawinfo(), ICON_DEFAULT_HEIGHT, icon_draw_rect(), icon_draw_texture(), ICON_TYPE_BUFFER, ICON_TYPE_PREVIEW, ICON_TYPE_TEXTURE, ICON_TYPE_VECTOR, if(), NULL, Icon::obj, PreviewImage::rect, IconImage::rect, DrawInfo::texture, bTheme::tui, DrawInfo::type, UI_DPI_ICON_FAC, UI_GetTheme(), UI_icons_free_drawinfo(), DrawInfo::vector, IconImage::w, and PreviewImage::w.
Referenced by icon_draw_at_size(), UI_icon_draw_aspect_color(), UI_icon_draw_preview_aspect_size(), and UI_icon_draw_size().
static void icon_draw_texture (float x, float y, float w, float h, int ix, int iy, int UNUSEDiw, int ih, float alpha, const float rgb[3]) [static]
Definition at line 915 of file interface_icons.c.
References IconTexture::id, IconTexture::invh, and IconTexture::invw.
Referenced by icon_draw_size().
static void icon_set_image (bContext * C, ID * id, PreviewImage * prv_img, enum eIconSizes size) [static]
Definition at line 848 of file interface_icons.c.
References ED_preview_icon_job(), G, G_DEBUG, PreviewImage::h, icon_create_rect(), ID::name, PreviewImage::rect, and PreviewImage::w.
Referenced by ui_id_brush_render(), and ui_id_preview_image_render_size().
static void init_brush_icons (void) [static]
Definition at line 463 of file interface_icons.c.
References add(), INIT_BRUSH_ICON, mix(), and smooth().
Referenced by UI_icons_init().
static void init_iconfile_list (struct ListBase * list) [static]
Definition at line 599 of file interface_icons.c.
References BLENDER_DATAFILES, BLI_addtail(), BLI_current_working_dir(), BLI_dir_contents(), BLI_get_folder(), BLI_join_dirfile(), BLI_strncpy(), BLI_testextensie(), FILE_MAX, IconFile::filename, ListBase::first, i, IB_rect, ICON_IMAGE_H, ICON_IMAGE_W, IMB_freeImBuf(), IMB_loadiffname(), IconFile::index, ListBase::last, MEM_callocN(), MEM_freeN(), NULL, direntry::path, direntry::relname, direntry::type, ImBuf::x, and ImBuf::y.
Referenced by UI_icons_init().
static void init_internal_icons (void) [static]
Definition at line 512 of file interface_icons.c.
References BIFICONID_FIRST, BLENDER_DATAFILES, BLI_get_folder(), BLI_join_dirfile(), datatoc_blender_icons_png, datatoc_blender_icons_png_size, def_internal_icon(), def_internal_vicon(), FILE_MAX, GPU_non_power_of_two_support(), IconTexture::h, IB_rect, ICON_GRID_COLS, ICON_GRID_H, ICON_GRID_MARGIN, ICON_GRID_ROWS, ICON_GRID_W, ICON_IMAGE_H, ICON_IMAGE_W, ICON_TYPE_BUFFER, ICON_TYPE_TEXTURE, ThemeUI::iconfile, IconTexture::id, IMB_freeImBuf(), IMB_ibImageFromMemory(), IMB_loadiffname(), IconTexture::invh, IconTexture::invw, NULL, ImBuf::rect, bTheme::tui, UI_GetTheme(), vicon_disclosure_tri_down_draw(), vicon_disclosure_tri_right_draw(), vicon_edit_draw(), vicon_editmode_dehlt_draw(), vicon_editmode_hlt_draw(), vicon_move_down_draw(), vicon_move_up_draw(), vicon_small_tri_right_draw(), vicon_view3d_draw(), vicon_x_draw(), IconTexture::w, ImBuf::x, and ImBuf::y.
Referenced by UI_icons_init().
static int preview_render_size (enum eIconSizes size) [static]
Definition at line 818 of file interface_icons.c.
References ICON_SIZE_ICON, ICON_SIZE_PREVIEW, and PREVIEW_DEFAULT_HEIGHT.
Referenced by icon_create_rect(), and seq_new_render_data().
void UI_icon_draw (float x, float y, int icon_id)
Definition at line 1157 of file interface_icons.c.
References UI_icon_draw_aspect().
Referenced by ANIM_channel_draw(), draw_marker(), draw_nla_channel_list_gl(), draw_view_icon(), outliner_draw_tree_element(), tselem_draw_icon(), and ui_searchbox_region_draw_cb().
void UI_icon_draw_aspect (float x, float y, int icon_id, float aspect, float alpha)
Definition at line 1146 of file interface_icons.c.
References icon_draw_at_size(), and ICON_SIZE_ICON.
Referenced by tselem_draw_icon_uibut(), ui_draw_menu_item(), UI_icon_draw(), widget_draw_icon(), and wm_drags_draw().
void UI_icon_draw_aspect_color (float x, float y, int icon_id, float aspect, const float rgb[3])
Definition at line 1151 of file interface_icons.c.
References FALSE, get_draw_size(), icon_draw_size(), and ICON_SIZE_ICON.
Referenced by widget_draw_icon().
void UI_icon_draw_preview (float x, float y, int icon_id)
Definition at line 1167 of file interface_icons.c.
References icon_draw_at_size(), and ICON_SIZE_PREVIEW.
void UI_icon_draw_preview_aspect (float x, float y, int icon_id, float aspect)
Definition at line 1172 of file interface_icons.c.
References icon_draw_at_size(), and ICON_SIZE_PREVIEW.
void UI_icon_draw_preview_aspect_size (float x, float y, int icon_id, float aspect, int size)
Definition at line 1177 of file interface_icons.c.
References FALSE, icon_draw_size(), ICON_SIZE_PREVIEW, NULL, and TRUE.
Referenced by widget_draw_preview().
void UI_icon_draw_size (float x, float y, int size, int icon_id, float alpha)
Definition at line 1162 of file interface_icons.c.
References FALSE, icon_draw_size(), ICON_SIZE_ICON, NULL, and TRUE.
int UI_icon_get_height (int icon_id)
Definition at line 778 of file interface_icons.c.
References BKE_icon_get(), Icon::drawinfo, G, G_DEBUG, icon_create_drawinfo(), ICON_DEFAULT_HEIGHT, if(), and NULL.
int UI_icon_get_width (int icon_id)
Definition at line 753 of file interface_icons.c.
References BKE_icon_get(), Icon::drawinfo, G, G_DEBUG, icon_create_drawinfo(), ICON_DEFAULT_WIDTH, if(), and NULL.
Referenced by widget_draw_text_icon().
int UI_iconfile_get_index (const char * filename)
Definition at line 691 of file interface_icons.c.
References BLI_path_cmp, IconFile::filename, ListBase::first, iconfilelist, IconFile::index, and IconFile::next.
ListBase* UI_iconfile_list (void) [read]
Definition at line 705 of file interface_icons.c.
References iconfilelist.
void UI_icons_free (void)
Definition at line 713 of file interface_icons.c.
References BKE_icons_free(), free_iconfile_list(), and IconTexture::id.
Referenced by ui_resources_free().
void UI_icons_free_drawinfo (void * drawinfo)
Definition at line 726 of file interface_icons.c.
References DrawInfo::buffer, DrawInfo::data, ICON_TYPE_BUFFER, MEM_freeN(), and DrawInfo::type.
Referenced by def_internal_icon(), and icon_draw_size().
void UI_icons_init (int first_dyn_id)
Definition at line 804 of file interface_icons.c.
References BKE_icons_init(), init_brush_icons(), init_iconfile_list(), and init_internal_icons().
Referenced by ui_resources_init().
static int ui_id_brush_get_icon (bContext * C, ID * id) [static]
Definition at line 1062 of file interface_icons.c.
References BKE_icon_getid(), BRUSH_CUSTOM_ICON, brush_image_tool_items, brush_sculpt_tool_items, brush_vertex_tool_items, CTX_data_active_object(), CTX_wm_space_image(), CTX_wm_view3d(), SpaceImage::flag, Brush::flag, ID::icon_id, Brush::imagepaint_tool, Object::mode, NULL, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, RNA_enum_icon_from_value(), Brush::sculpt_tool, SI_DRAWTOOL, ui_id_brush_render(), and Brush::vertexpaint_tool.
Referenced by ui_id_icon_get().
static void ui_id_brush_render (bContext * C, ID * id) [static]
Definition at line 1043 of file interface_icons.c.
References BKE_previewimg_get(), PreviewImage::changed, i, icon_set_image(), NUM_ICON_SIZES, and PreviewImage::rect.
Referenced by ui_id_brush_get_icon().
int ui_id_icon_get (bContext * C, ID * id, int big)
Definition at line 1115 of file interface_icons.c.
References BKE_icon_getid(), GS, ID_BR, ID_IM, ID_LA, ID_MA, ID_TE, ID_WO, ID::name, ui_id_brush_get_icon(), and ui_id_icon_render().
Referenced by id_search_cb(), list_item_icon_get(), list_item_row(), rna_search_cb(), and template_ID().
static void ui_id_icon_render (bContext * C, ID * id, int big) [static]
Definition at line 1031 of file interface_icons.c.
References BKE_previewimg_get(), ICON_SIZE_ICON, ICON_SIZE_PREVIEW, and ui_id_preview_image_render_size().
Referenced by ui_id_icon_get().
static void ui_id_preview_image_render_size (bContext * C, ID * id, PreviewImage * pi, int size) [static]
Definition at line 1021 of file interface_icons.c.
References PreviewImage::changed, icon_set_image(), PreviewImage::rect, and size().
Referenced by ui_id_icon_render().
static void vicon_disclosure_tri_down_draw (int x, int y, int w, int UNUSEDh, float alpha) [static]
Definition at line 401 of file interface_icons.c.
References viconutil_draw_lineloop_smooth(), and viconutil_set_point().
Referenced by init_internal_icons().
static void vicon_disclosure_tri_right_draw (int x, int y, int w, int UNUSEDh, float alpha) [static]
Definition at line 354 of file interface_icons.c.
References viconutil_draw_lineloop_smooth(), and viconutil_set_point().
Referenced by init_internal_icons().
static void vicon_edit_draw (int x, int y, int w, int h, float alpha) [static]
Definition at line 305 of file interface_icons.c.
References viconutil_draw_lineloop(), viconutil_draw_points(), and viconutil_set_point().
Referenced by init_internal_icons().
static void vicon_editmode_dehlt_draw (int x, int y, int w, int h, float UNUSEDalpha) [static]
Definition at line 339 of file interface_icons.c.
References viconutil_draw_lineloop_smooth(), viconutil_draw_points(), and viconutil_set_point().
Referenced by init_internal_icons().
static void vicon_editmode_hlt_draw (int x, int y, int w, int h, float alpha) [static]
Definition at line 321 of file interface_icons.c.
References viconutil_draw_lineloop_smooth(), viconutil_draw_points(), viconutil_draw_tri(), and viconutil_set_point().
Referenced by init_internal_icons().
static void vicon_move_down_draw (int x, int y, int w, int h, float UNUSEDalpha) [static]
Definition at line 444 of file interface_icons.c.
Referenced by init_internal_icons().
static void vicon_move_up_draw (int x, int y, int w, int h, float UNUSEDalpha) [static]
Definition at line 426 of file interface_icons.c.
Referenced by init_internal_icons().
static void vicon_small_tri_right_draw (int x, int y, int w, int UNUSEDh, float alpha) [static]
Definition at line 379 of file interface_icons.c.
References viconutil_set_point().
Referenced by init_internal_icons().
static void vicon_view3d_draw (int x, int y, int w, int h, float alpha) [static]
Definition at line 277 of file interface_icons.c.
References MAX2.
Referenced by init_internal_icons().
static void vicon_x_draw (int x, int y, int w, int h, float alpha) [static]
Definition at line 253 of file interface_icons.c.
Referenced by init_internal_icons().
static void viconutil_draw_lineloop (GLint(*) pts[2], int numPoints) [static]
Definition at line 217 of file interface_icons.c.
References i.
Referenced by vicon_edit_draw(), and viconutil_draw_lineloop_smooth().
static void viconutil_draw_lineloop_smooth (GLint(*) pts[2], int numPoints) [static]
Definition at line 228 of file interface_icons.c.
References viconutil_draw_lineloop().
Referenced by vicon_disclosure_tri_down_draw(), vicon_disclosure_tri_right_draw(), vicon_editmode_dehlt_draw(), and vicon_editmode_hlt_draw().
static void viconutil_draw_points (GLint(*) pts[2], int numPoints, int pointSize) [static]
Definition at line 235 of file interface_icons.c.
References i.
Referenced by vicon_edit_draw(), vicon_editmode_dehlt_draw(), and vicon_editmode_hlt_draw().
static void viconutil_draw_tri (GLint(*) pts[2]) [static]
Definition at line 208 of file interface_icons.c.
Referenced by vicon_editmode_hlt_draw().
static void viconutil_set_point (GLint pt[2], int x, int y) [static]
Definition at line 202 of file interface_icons.c.
Referenced by vicon_disclosure_tri_down_draw(), vicon_disclosure_tri_right_draw(), vicon_edit_draw(), vicon_editmode_dehlt_draw(), vicon_editmode_hlt_draw(), and vicon_small_tri_right_draw().
Variable Documentation
struct ListBase iconfilelist = {NULL, NULL} [static]
Definition at line 130 of file interface_icons.c.
Referenced by UI_iconfile_get_index(), and UI_iconfile_list().
IconTexture icongltex = {0, 0, 0, 0.0f, 0.0f} [static]
Definition at line 131 of file interface_icons.c.