Blender: heap_relax_snode.c File Reference
heap_relax_snode.c File Reference
opennl
#include "ssp_defs.h"
Functions
void heap_relax_snode (const int n, int *et, const int relax_columns, int *descendants, int *relax_end)
Detailed Description
Definition in file heap_relax_snode.c.
Function Documentation
void heap_relax_snode (const int n, int * et, const int relax_columns, int * descendants, int * relax_end)
Definition at line 27 of file heap_relax_snode.c.
References ABORT, EMPTY, i, ifill(), intMalloc(), post, SUPERLU_FREE, SUPERLU_MIN, and TreePostorder().
Referenced by sgstrf().