Blender: BL_ShapeDeformer Class Reference
BL_ShapeDeformer Class Reference
#include <BL_ShapeDeformer.h>
Public Member Functions
BL_ShapeDeformer (BL_DeformableGameObject *gameobj, Object *bmeshobj, RAS_MeshObject *mesh)
BL_ShapeDeformer (BL_DeformableGameObject *gameobj, struct Object *bmeshobj_old, struct Object *bmeshobj_new, class RAS_MeshObject *mesh, bool release_object, bool recalc_normal, BL_ArmatureObject *arma=NULL)
virtual RAS_Deformer * GetReplica ()
virtual void ProcessReplica ()
virtual ~BL_ShapeDeformer ()
bool Update (void)
bool LoadShapeDrivers (Object *arma)
bool ExecuteShapeDrivers (void)
struct Key * GetKey ()
void SetKey (struct Key *key)
void ForceUpdate ()
Protected Attributes
bool m_useShapeDrivers
double m_lastShapeUpdate
struct Key * m_key
Detailed Description
Definition at line 43 of file BL_ShapeDeformer.h.
Constructor & Destructor Documentation
BL_ShapeDeformer::BL_ShapeDeformer (BL_DeformableGameObject * gameobj, Object * bmeshobj, RAS_MeshObject * mesh)
Definition at line 71 of file BL_ShapeDeformer.cpp.
References copy_key(), Mesh::key, BL_MeshDeformer::m_bmesh, and m_key.
Referenced by GetReplica().
BL_ShapeDeformer::BL_ShapeDeformer (BL_DeformableGameObject * gameobj, struct Object * bmeshobj_old, struct Object * bmeshobj_new, class RAS_MeshObject * mesh, bool release_object, bool recalc_normal, BL_ArmatureObject * arma = NULL)
Definition at line 84 of file BL_ShapeDeformer.cpp.
References copy_key(), Mesh::key, BL_MeshDeformer::m_bmesh, and m_key.
BL_ShapeDeformer::~BL_ShapeDeformer () [virtual]
Definition at line 100 of file BL_ShapeDeformer.cpp.
References BLI_remlink_safe(), free_key(), G, Mesh::key, BL_MeshDeformer::m_bmesh, m_key, MEM_freeN(), and NULL.
Member Function Documentation
bool BL_ShapeDeformer::ExecuteShapeDrivers (void)
Definition at line 137 of file BL_ShapeDeformer.cpp.
References ADT_RECALC_DRIVERS, BL_ArmatureObject::ApplyPose(), BKE_animsys_evaluate_animdata(), ForceUpdate(), GetKey(), BL_SkinDeformer::m_armobj, RAS_Deformer::m_bDynamic, m_useShapeDrivers, NULL, BL_SkinDeformer::PoseUpdated(), and BL_ArmatureObject::RestorePose().
Referenced by Update().
void BL_ShapeDeformer::ForceUpdate () [inline]
Reimplemented from BL_SkinDeformer.
Reimplemented in BL_ModifierDeformer.
Definition at line 70 of file BL_ShapeDeformer.h.
References m_lastShapeUpdate.
Referenced by ExecuteShapeDrivers(), and Update().
Key * BL_ShapeDeformer::GetKey () [read]
Definition at line 208 of file BL_ShapeDeformer.cpp.
References Mesh::key, and BL_MeshDeformer::m_bmesh.
Referenced by BL_Action::BL_Action(), BL_ShapeActionActuator::BL_ShapeActionActuator(), ExecuteShapeDrivers(), BL_DeformableGameObject::GetShape(), BL_Action::Play(), BL_Action::Update(), and BL_ShapeActionActuator::Update().
RAS_Deformer * BL_ShapeDeformer::GetReplica (void) [virtual]
Reimplemented from BL_SkinDeformer.
Reimplemented in BL_ModifierDeformer.
Definition at line 112 of file BL_ShapeDeformer.cpp.
References BL_ShapeDeformer(), and ProcessReplica().
bool BL_ShapeDeformer::LoadShapeDrivers (Object * arma)
Definition at line 127 of file BL_ShapeDeformer.cpp.
References m_useShapeDrivers.
Referenced by gameobject_from_blenderobject(), and KX_Scene::ReplaceMesh().
void BL_ShapeDeformer::ProcessReplica () [virtual]
Reimplemented from BL_SkinDeformer.
Reimplemented in BL_ModifierDeformer.
Definition at line 121 of file BL_ShapeDeformer.cpp.
References m_lastShapeUpdate.
Referenced by GetReplica().
void BL_ShapeDeformer::SetKey (struct Key * key)
Definition at line 213 of file BL_ShapeDeformer.cpp.
References Mesh::key, and BL_MeshDeformer::m_bmesh.
bool BL_ShapeDeformer::Update (void) [virtual]
Reimplemented from BL_SkinDeformer.
Reimplemented in BL_ModifierDeformer.
Definition at line 155 of file BL_ShapeDeformer.cpp.
References RAS_MeshObject::CheckWeightCache(), do_rel_key(), ExecuteShapeDrivers(), ForceUpdate(), BL_DeformableGameObject::GetBlendObject(), BL_DeformableGameObject::GetLastFrame(), Mesh::key, RAS_Deformer::m_bDynamic, BL_MeshDeformer::m_bmesh, BL_MeshDeformer::m_gameobj, m_lastShapeUpdate, BL_MeshDeformer::m_pMeshObject, BL_SkinDeformer::m_recalcNormal, BL_MeshDeformer::m_transverts, NULL, BL_MeshDeformer::RecalcNormals(), Mesh::totvert, BL_SkinDeformer::UpdateInternal(), and BL_MeshDeformer::VerifyStorage().
Member Data Documentation
struct Key* BL_ShapeDeformer::m_key [protected]
Definition at line 78 of file BL_ShapeDeformer.h.
Referenced by BL_ShapeDeformer(), and ~BL_ShapeDeformer().
double BL_ShapeDeformer::m_lastShapeUpdate [protected]
Definition at line 77 of file BL_ShapeDeformer.h.
Referenced by ForceUpdate(), ProcessReplica(), and Update().
bool BL_ShapeDeformer::m_useShapeDrivers [protected]
Definition at line 73 of file BL_ShapeDeformer.h.
Referenced by ExecuteShapeDrivers(), and LoadShapeDrivers().
The documentation for this class was generated from the following files:
BL_ShapeDeformer.h
BL_ShapeDeformer.cpp