Blender: bmesh_operators.h File Reference
bmesh_operators.h File Reference
BMesh
#include "intern/bmesh_operator_api_inline.h"
Enumerations
enum { SUBD_INNERVERT, SUBD_PATH, SUBD_FAN, SUBD_STRAIGHT_CUT }
enum { SUBDIV_SELECT_ORIG, SUBDIV_SELECT_INNER, SUBDIV_SELECT_INNER_SEL, SUBDIV_SELECT_LOOPCUT }
enum {
SIMFACE_MATERIAL = 201, SIMFACE_IMAGE, SIMFACE_AREA, SIMFACE_PERIMETER,
SIMFACE_NORMAL, SIMFACE_COPLANAR
}
enum {
SIMEDGE_LENGTH = 101, SIMEDGE_DIR, SIMEDGE_FACE, SIMEDGE_FACE_ANGLE,
SIMEDGE_CREASE, SIMEDGE_SEAM, SIMEDGE_SHARP
}
enum { SIMVERT_NORMAL = 0, SIMVERT_FACE, SIMVERT_VGROUP }
enum { OPUVC_AXIS_X = 1, OPUVC_AXIS_Y }
enum { DIRECTION_CW = 1, DIRECTION_CCW }
enum { VPATH_SELECT_EDGE_LENGTH = 0, VPATH_SELECT_TOPOLOGICAL }
Functions
void BM_mesh_esubdivide (BMesh *bm, const char edge_hflag, float smooth, float fractal, int numcuts, int seltype, int cornertype, const short use_singleedge, const short use_gridfill, int seed)
Variables
BMOpDefine * opdefines []
int bmesh_total_ops
Detailed Description
Definition in file bmesh_operators.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
SUBD_INNERVERT
SUBD_PATH
SUBD_FAN
SUBD_STRAIGHT_CUT
Definition at line 35 of file bmesh_operators.h.
anonymous enum
Enumerator:
SUBDIV_SELECT_ORIG
SUBDIV_SELECT_INNER
SUBDIV_SELECT_INNER_SEL
SUBDIV_SELECT_LOOPCUT
Definition at line 42 of file bmesh_operators.h.
anonymous enum
Enumerator:
SIMFACE_MATERIAL
SIMFACE_IMAGE
SIMFACE_AREA
SIMFACE_PERIMETER
SIMFACE_NORMAL
SIMFACE_COPLANAR
Definition at line 50 of file bmesh_operators.h.
anonymous enum
Enumerator:
SIMEDGE_LENGTH
SIMEDGE_DIR
SIMEDGE_FACE
SIMEDGE_FACE_ANGLE
SIMEDGE_CREASE
SIMEDGE_SEAM
SIMEDGE_SHARP
Definition at line 60 of file bmesh_operators.h.
anonymous enum
Enumerator:
SIMVERT_NORMAL
SIMVERT_FACE
SIMVERT_VGROUP
Definition at line 71 of file bmesh_operators.h.
anonymous enum
Enumerator:
OPUVC_AXIS_X
OPUVC_AXIS_Y
Definition at line 77 of file bmesh_operators.h.
anonymous enum
Enumerator:
DIRECTION_CW
DIRECTION_CCW
Definition at line 82 of file bmesh_operators.h.
anonymous enum
Enumerator:
VPATH_SELECT_EDGE_LENGTH
VPATH_SELECT_TOPOLOGICAL
Definition at line 88 of file bmesh_operators.h.
Function Documentation
void BM_mesh_esubdivide (BMesh * bm, const char edge_hflag, float smooth, float fractal, int numcuts, int seltype, int cornertype, const short use_singleedge, const short use_gridfill, int seed)
Definition at line 1027 of file bmo_subdivide.c.
References BM_EDGE, BM_edge_select_set(), BM_EDGES_OF_VERT, BM_elem_flag_test, BM_ELEM_SELECT, BM_elem_select_set(), BM_FACE, BM_ITER_ELEM, BM_mesh_elem_hflag_disable_all(), BM_VERT, BMO_iter_new(), BMO_iter_step(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), FALSE, BMElem::head, BMHeader::htype, SUBDIV_SELECT_INNER, SUBDIV_SELECT_LOOPCUT, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by edbm_subdivide_exec(), and ringsel_finish().
Variable Documentation
int bmesh_total_ops
Definition at line 1198 of file bmesh_opdefines.c.
Referenced by bmo_opname_to_opcode().
BMOpDefine* opdefines[]
Definition at line 1128 of file bmesh_opdefines.c.
Referenced by BMO_op_finish(), BMO_op_init(), BMO_op_vinitf(), bmo_opname_to_opcode(), BMO_slot_exists(), and BMO_slot_get().