Blender: btGeometryUtil Class Reference
btGeometryUtil Class Reference
The btGeometryUtil helper class provides a few methods to convert between plane equations and vertices.
#include <btGeometryUtil.h>
Static Public Member Functions
static void getPlaneEquationsFromVertices (btAlignedObjectArray< btVector3 > &vertices, btAlignedObjectArray< btVector3 > &planeEquationsOut)
static void getVerticesFromPlaneEquations (const btAlignedObjectArray< btVector3 > &planeEquations, btAlignedObjectArray< btVector3 > &verticesOut)
static bool isInside (const btAlignedObjectArray< btVector3 > &vertices, const btVector3 &planeNormal, btScalar margin)
static bool isPointInsidePlanes (const btAlignedObjectArray< btVector3 > &planeEquations, const btVector3 &point, btScalar margin)
static bool areVerticesBehindPlane (const btVector3 &planeNormal, const btAlignedObjectArray< btVector3 > &vertices, btScalar margin)
Detailed Description
The btGeometryUtil helper class provides a few methods to convert between plane equations and vertices.
Definition at line 23 of file btGeometryUtil.h.
Member Function Documentation
bool btGeometryUtil::areVerticesBehindPlane (const btVector3 & planeNormal, const btAlignedObjectArray< btVector3 > & vertices, btScalar margin) [static]
Definition at line 50 of file btGeometryUtil.cpp.
References i, and btAlignedObjectArray< T >::size().
Referenced by getPlaneEquationsFromVertices().
void btGeometryUtil::getPlaneEquationsFromVertices (btAlignedObjectArray< btVector3 > & vertices, btAlignedObjectArray< btVector3 > & planeEquationsOut) [static]
Definition at line 81 of file btGeometryUtil.cpp.
References areVerticesBehindPlane(), i, notExist(), btAlignedObjectArray< T >::push_back(), and btAlignedObjectArray< T >::size().
void btGeometryUtil::getVerticesFromPlaneEquations (const btAlignedObjectArray< btVector3 > & planeEquations, btAlignedObjectArray< btVector3 > & verticesOut) [static]
Definition at line 129 of file btGeometryUtil.cpp.
References btFabs(), i, isPointInsidePlanes(), btAlignedObjectArray< T >::push_back(), and btAlignedObjectArray< T >::size().
static bool btGeometryUtil::isInside (const btAlignedObjectArray< btVector3 > & vertices, const btVector3 & planeNormal, btScalar margin) [static]
bool btGeometryUtil::isPointInsidePlanes (const btAlignedObjectArray< btVector3 > & planeEquations, const btVector3 & point, btScalar margin) [static]
Definition at line 33 of file btGeometryUtil.cpp.
References i, and btAlignedObjectArray< T >::size().
Referenced by getVerticesFromPlaneEquations().
The documentation for this class was generated from the following files:
btGeometryUtil.h
btGeometryUtil.cpp