Blender: text_intern.h File Reference
text_intern.h File Reference
text editor
Classes
struct FlattenString
Defines
#define TXT_OFFSET 15
#define TXT_SCROLL_WIDTH 20
#define TXT_SCROLL_SPACE 2
#define TEXTXLOC (st->cwidth * st->linenrs_tot)
#define SUGG_LIST_SIZE 7
#define SUGG_LIST_WIDTH 20
#define DOC_WIDTH 40
#define DOC_HEIGHT 10
#define TOOL_SUGG_LIST 0x01
#define TOOL_DOCUMENT 0x02
#define TMARK_GRP_CUSTOM 0x00010000
#define TMARK_GRP_FINDALL 0x00020000
Typedefs
typedef struct FlattenString FlattenString
Enumerations
enum {
LINE_BEGIN, LINE_END, FILE_TOP, FILE_BOTTOM,
PREV_CHAR, NEXT_CHAR, PREV_WORD, NEXT_WORD,
PREV_LINE, NEXT_LINE, PREV_PAGE, NEXT_PAGE
}
enum { DEL_NEXT_CHAR, DEL_PREV_CHAR, DEL_NEXT_WORD, DEL_PREV_WORD }
Functions
void draw_text_main (struct SpaceText *st, struct ARegion *ar)
void text_update_line_edited (struct TextLine *line)
void text_update_edited (struct Text *text)
void text_update_character_width (struct SpaceText *st)
void text_scroll_to_cursor (struct SpaceText *st, struct ScrArea *sa)
void text_update_cursor_moved (struct bContext *C)
int flatten_string (struct SpaceText *st, FlattenString *fs, const char *in)
void flatten_string_free (FlattenString *fs)
int wrap_width (struct SpaceText *st, struct ARegion *ar)
void wrap_offset (struct SpaceText *st, struct ARegion *ar, struct TextLine *linein, int cursin, int *offl, int *offc)
void wrap_offset_in_line (struct SpaceText *st, struct ARegion *ar, struct TextLine *linep, int cursin, int *offl, int *offc)
int text_get_char_pos (struct SpaceText *st, const char *line, int cur)
void text_drawcache_tag_update (struct SpaceText *st, int full)
void text_free_caches (struct SpaceText *st)
int text_file_modified (struct Text *text)
int text_do_suggest_select (struct SpaceText *st, struct ARegion *ar)
void text_pop_suggest_list (void)
int text_get_visible_lines (struct SpaceText *st, struct ARegion *ar, const char *str)
int text_get_span_wrap (struct SpaceText *st, struct ARegion *ar, struct TextLine *from, struct TextLine *to)
int text_get_total_lines (struct SpaceText *st, struct ARegion *ar)
void TEXT_OT_new (struct wmOperatorType *ot)
void TEXT_OT_open (struct wmOperatorType *ot)
void TEXT_OT_reload (struct wmOperatorType *ot)
void TEXT_OT_unlink (struct wmOperatorType *ot)
void TEXT_OT_save (struct wmOperatorType *ot)
void TEXT_OT_save_as (struct wmOperatorType *ot)
void TEXT_OT_make_internal (struct wmOperatorType *ot)
void TEXT_OT_run_script (struct wmOperatorType *ot)
void TEXT_OT_refresh_pyconstraints (struct wmOperatorType *ot)
void TEXT_OT_paste (struct wmOperatorType *ot)
void TEXT_OT_copy (struct wmOperatorType *ot)
void TEXT_OT_cut (struct wmOperatorType *ot)
void TEXT_OT_convert_whitespace (struct wmOperatorType *ot)
void TEXT_OT_uncomment (struct wmOperatorType *ot)
void TEXT_OT_comment (struct wmOperatorType *ot)
void TEXT_OT_unindent (struct wmOperatorType *ot)
void TEXT_OT_indent (struct wmOperatorType *ot)
void TEXT_OT_line_break (struct wmOperatorType *ot)
void TEXT_OT_insert (struct wmOperatorType *ot)
void TEXT_OT_markers_clear (struct wmOperatorType *ot)
void TEXT_OT_next_marker (struct wmOperatorType *ot)
void TEXT_OT_previous_marker (struct wmOperatorType *ot)
void TEXT_OT_select_line (struct wmOperatorType *ot)
void TEXT_OT_select_all (struct wmOperatorType *ot)
void TEXT_OT_select_word (struct wmOperatorType *ot)
void TEXT_OT_jump (struct wmOperatorType *ot)
void TEXT_OT_move (struct wmOperatorType *ot)
void TEXT_OT_move_select (struct wmOperatorType *ot)
void TEXT_OT_delete (struct wmOperatorType *ot)
void TEXT_OT_overwrite_toggle (struct wmOperatorType *ot)
void TEXT_OT_scroll (struct wmOperatorType *ot)
void TEXT_OT_scroll_bar (struct wmOperatorType *ot)
void TEXT_OT_selection_set (struct wmOperatorType *ot)
void TEXT_OT_cursor_set (struct wmOperatorType *ot)
void TEXT_OT_line_number (struct wmOperatorType *ot)
void TEXT_OT_properties (struct wmOperatorType *ot)
void TEXT_OT_find (struct wmOperatorType *ot)
void TEXT_OT_find_set_selected (struct wmOperatorType *ot)
void TEXT_OT_replace (struct wmOperatorType *ot)
void TEXT_OT_replace_set_selected (struct wmOperatorType *ot)
void TEXT_OT_mark_all (struct wmOperatorType *ot)
void TEXT_OT_to_3d_object (struct wmOperatorType *ot)
void TEXT_OT_resolve_conflict (struct wmOperatorType *ot)
Variables
const char * text_context_dir []
Detailed Description
Definition in file text_intern.h.
Define Documentation
#define DOC_HEIGHT 10
Definition at line 66 of file text_intern.h.
Referenced by draw_documentation().
#define DOC_WIDTH 40
Definition at line 65 of file text_intern.h.
Referenced by draw_documentation().
#define SUGG_LIST_SIZE 7
Definition at line 63 of file text_intern.h.
Referenced by do_texttools(), draw_suggestion_list(), text_do_suggest_select(), and text_pop_suggest_list().
#define SUGG_LIST_WIDTH 20
Definition at line 64 of file text_intern.h.
Referenced by draw_documentation(), draw_suggestion_list(), and text_do_suggest_select().
#define TEXTXLOC (st->cwidth * st->linenrs_tot)
Definition at line 61 of file text_intern.h.
Referenced by draw_brackets(), draw_cursor(), draw_documentation(), draw_markers(), draw_suggestion_list(), draw_text_main(), text_cursor_set_to_pos(), text_do_suggest_select(), text_draw(), text_line_number_invoke(), and wrap_width().
#define TMARK_GRP_CUSTOM 0x00010000
Definition at line 71 of file text_intern.h.
#define TMARK_GRP_FINDALL 0x00020000
Definition at line 72 of file text_intern.h.
Referenced by text_find_and_replace().
#define TOOL_DOCUMENT 0x02
Definition at line 69 of file text_intern.h.
Referenced by do_texttools().
#define TOOL_SUGG_LIST 0x01
Definition at line 68 of file text_intern.h.
Referenced by do_texttools().
#define TXT_OFFSET 15
Definition at line 57 of file text_intern.h.
Referenced by draw_brackets(), draw_cursor(), draw_documentation(), draw_markers(), draw_suggestion_list(), draw_text_main(), text_cursor_set_to_pos(), text_do_suggest_select(), text_draw(), text_line_number_invoke(), and wrap_width().
#define TXT_SCROLL_SPACE 2
Definition at line 59 of file text_intern.h.
Referenced by text_scroll_bar_invoke().
#define TXT_SCROLL_WIDTH 20
Definition at line 58 of file text_intern.h.
Referenced by draw_text_main(), text_scroll_to_cursor(), and wrap_width().
Typedef Documentation
typedef struct FlattenString FlattenString
Enumeration Type Documentation
anonymous enum
Enumerator:
LINE_BEGIN
LINE_END
FILE_TOP
FILE_BOTTOM
PREV_CHAR
NEXT_CHAR
PREV_WORD
NEXT_WORD
PREV_LINE
NEXT_LINE
PREV_PAGE
NEXT_PAGE
Definition at line 104 of file text_intern.h.
anonymous enum
Enumerator:
DEL_NEXT_CHAR
DEL_PREV_CHAR
DEL_NEXT_WORD
DEL_PREV_WORD
Definition at line 106 of file text_intern.h.
Function Documentation
void draw_text_main (struct SpaceText * st, struct ARegion * ar)
Definition at line 1737 of file text_draw.c.
References BLF_fixed_width(), BLI_snprintf(), calc_text_rcts(), Text::curl, SpaceText::cwidth, draw_brackets(), draw_cursor(), draw_documentation(), draw_markers(), draw_suggestion_list(), draw_textscroll(), ListBase::first, SpaceText::flags, TextLine::format, i, if(), ListBase::last, SpaceText::left, SpaceText::lheight, SpaceText::linenrs_tot, Text::lines, SpaceText::margin_column, MAX2, mono, TextLine::next, Text::sell, SpaceText::showlinenrs, SpaceText::showsyntax, ST_SHOW_MARGIN, SpaceText::text, text_draw(), text_draw_wrapped(), text_font_begin(), text_font_draw(), text_font_end(), text_get_visible_lines_no(), text_update_drawcache(), TEXTXLOC, TH_GRID, TH_HILITE, TH_TEXT, SpaceText::top, txt_clean_text(), txt_format_line(), TXT_OFFSET, TXT_SCROLL_WIDTH, UI_ThemeColor(), SpaceText::viewlines, ARegion::winx, ARegion::winy, and SpaceText::wordwrap.
Referenced by text_main_area_draw().
int flatten_string (struct SpaceText * st, FlattenString * fs, const char * in)
Definition at line 142 of file text_draw.c.
References FlattenString::accum, BLI_str_utf8_size(), FlattenString::buf, FlattenString::fixedaccum, FlattenString::fixedbuf, flatten_string_append(), i, len(), FlattenString::len, and SpaceText::tabnumber.
Referenced by text_convert_whitespace_exec(), text_draw(), text_draw_wrapped(), and txt_format_line().
void flatten_string_free (FlattenString * fs)
Definition at line 174 of file text_draw.c.
References FlattenString::accum, FlattenString::buf, FlattenString::fixedaccum, FlattenString::fixedbuf, and MEM_freeN().
Referenced by text_convert_whitespace_exec(), text_draw(), text_draw_wrapped(), and txt_format_line().
int text_do_suggest_select (struct SpaceText * st, struct ARegion * ar)
Definition at line 50 of file text_python.c.
References Text::curc, Text::curl, SpaceText::cwidth, i, if(), SpaceText::left, SpaceText::lheight, SuggItem::next, TextLine::prev, SpaceText::showlinenrs, SUGG_LIST_SIZE, SUGG_LIST_WIDTH, SpaceText::text, text_update_character_width(), texttool_suggest_first(), texttool_suggest_last(), texttool_suggest_select(), texttool_suggest_top(), texttool_text_is_active(), TEXTXLOC, SpaceText::top, TXT_OFFSET, and ARegion::winy.
Referenced by do_texttools().
void text_drawcache_tag_update (struct SpaceText * st, int full)
Definition at line 945 of file text_draw.c.
References BLI_findindex(), SpaceText::drawcache, if(), DrawCache::nlines, NULL, SpaceText::text, DrawCache::update_flag, DrawCache::valid_head, and DrawCache::valid_tail.
Referenced by ED_text_undo_step(), text_comment_exec(), text_convert_whitespace_exec(), text_cut_exec(), text_delete_exec(), text_find_and_replace(), text_indent_exec(), text_insert_exec(), text_line_break_exec(), text_listener(), text_new_exec(), text_open_exec(), text_paste_exec(), text_reload_exec(), text_uncomment_exec(), text_unindent_exec(), and text_unlink_exec().
int text_file_modified (struct Text * text)
Definition at line 3136 of file text_ops.c.
References BLI_exists(), BLI_path_abs(), BLI_strncpy(), FILE_MAX, G, Text::mtime, and Text::name.
Referenced by text_resolve_conflict_invoke().
void text_free_caches (struct SpaceText * st)
Definition at line 989 of file text_draw.c.
References SpaceText::drawcache, if(), DrawCache::line_height, and MEM_freeN().
Referenced by text_free().
int text_get_char_pos (struct SpaceText * st, const char * line, int cur)
Definition at line 685 of file text_draw.c.
References BLI_str_utf8_size(), i, and SpaceText::tabnumber.
Referenced by cursor_skip_find_line(), draw_brackets(), draw_cursor(), draw_markers(), txt_wrap_move_down(), and txt_wrap_move_up().
int text_get_span_wrap (struct SpaceText * st, struct ARegion * ar, struct TextLine * from, struct TextLine * to)
Definition at line 1046 of file text_draw.c.
References TextLine::line, TextLine::next, text_get_visible_lines(), txt_get_span(), and SpaceText::wordwrap.
Referenced by calc_text_rcts().
int text_get_total_lines (struct SpaceText * st, struct ARegion * ar)
Definition at line 1064 of file text_draw.c.
References SpaceText::drawcache, text_update_drawcache(), and DrawCache::total_lines.
Referenced by calc_text_rcts(), text_scroll_modal(), and txt_screen_skip().
int text_get_visible_lines (struct SpaceText * st, struct ARegion * ar, const char * str)
Definition at line 1011 of file text_draw.c.
References BLI_str_utf8_size(), i, max, SpaceText::tabnumber, and wrap_width().
Referenced by cursor_skip_find_line(), draw_cursor(), get_first_visible_line(), text_get_span_wrap(), text_update_drawcache(), txt_wrap_move_down(), txt_wrap_move_up(), and wrap_offset().
void TEXT_OT_comment (struct wmOperatorType * ot)
Definition at line 1036 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_comment_exec(), and text_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_convert_whitespace (struct wmOperatorType * ot)
Definition at line 1210 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, text_convert_whitespace_exec(), text_edit_poll(), and TO_SPACES.
Referenced by text_operatortypes().
void TEXT_OT_copy (struct wmOperatorType * ot)
Definition at line 852 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_copy_exec(), and text_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_cursor_set (struct wmOperatorType * ot)
Definition at line 2746 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, text_cursor_set_exec(), text_cursor_set_invoke(), and text_region_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_cut (struct wmOperatorType * ot)
Definition at line 885 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_cut_exec(), and text_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_delete (struct wmOperatorType * ot)
Definition at line 2033 of file text_ops.c.
References DEL_NEXT_CHAR, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, text_delete_exec(), and text_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_find (struct wmOperatorType * ot)
Definition at line 3013 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_find_exec(), and text_space_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_find_set_selected (struct wmOperatorType * ot)
Definition at line 3081 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_find_set_selected_exec(), and text_space_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_indent (struct wmOperatorType * ot)
Definition at line 920 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_indent_exec().
Referenced by text_operatortypes().
void TEXT_OT_insert (struct wmOperatorType * ot)
Definition at line 2891 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_property_flag(), RNA_def_string(), wmOperatorType::srna, text_edit_poll(), text_insert_exec(), and text_insert_invoke().
Referenced by text_operatortypes().
void TEXT_OT_jump (struct wmOperatorType * ot)
Definition at line 1980 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, text_edit_poll(), text_jump_exec(), and text_jump_invoke().
Referenced by text_operatortypes().
void TEXT_OT_line_break (struct wmOperatorType * ot)
Definition at line 1003 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_line_break_exec().
Referenced by text_operatortypes().
void TEXT_OT_line_number (struct wmOperatorType * ot)
Definition at line 2802 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, text_line_number_invoke(), and text_region_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_make_internal (struct wmOperatorType * ot)
Definition at line 426 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, text_edit_poll(), and text_make_internal_exec().
Referenced by text_operatortypes().
void TEXT_OT_mark_all (struct wmOperatorType * ot)
Definition at line 3051 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_mark_all_exec(), and text_space_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_markers_clear (struct wmOperatorType * ot)
Definition at line 1390 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_clear_all_markers_exec(), and text_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_move (struct wmOperatorType * ot)
Definition at line 1914 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, LINE_BEGIN, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, text_edit_poll(), and text_move_exec().
Referenced by text_operatortypes().
void TEXT_OT_move_select (struct wmOperatorType * ot)
Definition at line 1938 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, LINE_BEGIN, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, text_move_select_exec(), and text_space_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_new (struct wmOperatorType * ot)
Definition at line 197 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, text_new_exec(), and text_new_poll().
Referenced by text_operatortypes().
void TEXT_OT_next_marker (struct wmOperatorType * ot)
Definition at line 1364 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_next_marker_exec().
Referenced by text_operatortypes().
void TEXT_OT_open (struct wmOperatorType * ot)
Definition at line 296 of file text_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, PYSCRIPTFILE, RNA_def_boolean(), wmOperatorType::srna, text_new_poll(), text_open_cancel(), text_open_exec(), text_open_invoke(), TEXTFILE, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by text_operatortypes().
void TEXT_OT_overwrite_toggle (struct wmOperatorType * ot)
Definition at line 2061 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_space_edit_poll(), and text_toggle_overwrite_exec().
Referenced by text_operatortypes().
void TEXT_OT_paste (struct wmOperatorType * ot)
Definition at line 814 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, text_edit_poll(), and text_paste_exec().
Referenced by text_operatortypes().
void TEXT_OT_previous_marker (struct wmOperatorType * ot)
Definition at line 1328 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_previous_marker_exec().
Referenced by text_operatortypes().
void TEXT_OT_properties (struct wmOperatorType * ot)
Definition at line 117 of file text_header.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_properties_exec(), and text_properties_poll().
Referenced by text_operatortypes().
void TEXT_OT_refresh_pyconstraints (struct wmOperatorType * ot)
Definition at line 690 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_refresh_pyconstraints_exec().
Referenced by text_operatortypes().
void TEXT_OT_reload (struct wmOperatorType * ot)
Definition at line 341 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), text_reload_exec(), and WM_operator_confirm().
Referenced by text_operatortypes().
void TEXT_OT_replace (struct wmOperatorType * ot)
Definition at line 3032 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_replace_exec(), and text_space_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_replace_set_selected (struct wmOperatorType * ot)
Definition at line 3108 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_replace_set_selected_exec(), and text_space_edit_poll().
Referenced by text_operatortypes().
void TEXT_OT_resolve_conflict (struct wmOperatorType * ot)
Definition at line 3244 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RESOLVE_IGNORE, RNA_def_enum(), wmOperatorType::srna, text_resolve_conflict_exec(), text_resolve_conflict_invoke(), and text_save_poll().
Referenced by text_operatortypes().
void TEXT_OT_run_script (struct wmOperatorType * ot)
Definition at line 630 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, text_run_script_exec(), and text_run_script_poll().
Referenced by text_operatortypes().
void TEXT_OT_save (struct wmOperatorType * ot)
Definition at line 503 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_save_exec(), and text_save_poll().
Referenced by text_operatortypes().
void TEXT_OT_save_as (struct wmOperatorType * ot)
Definition at line 560 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, FOLDERFILE, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, PYSCRIPTFILE, text_edit_poll(), text_save_as_exec(), text_save_as_invoke(), TEXTFILE, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by text_operatortypes().
void TEXT_OT_scroll (struct wmOperatorType * ot)
Definition at line 2261 of file text_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, text_scroll_cancel(), text_scroll_exec(), text_scroll_invoke(), text_scroll_modal(), and text_scroll_poll().
Referenced by text_operatortypes().
void TEXT_OT_scroll_bar (struct wmOperatorType * ot)
Definition at line 2355 of file text_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, text_region_scroll_poll(), text_scroll_bar_invoke(), text_scroll_cancel(), and text_scroll_modal().
Referenced by text_operatortypes().
void TEXT_OT_select_all (struct wmOperatorType * ot)
Definition at line 1239 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_select_all_exec().
Referenced by text_operatortypes().
void TEXT_OT_select_line (struct wmOperatorType * ot)
Definition at line 1265 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_select_line_exec().
Referenced by text_operatortypes().
void TEXT_OT_select_word (struct wmOperatorType * ot)
Definition at line 1292 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_select_word_exec().
Referenced by text_operatortypes().
void TEXT_OT_selection_set (struct wmOperatorType * ot)
Definition at line 2692 of file text_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, text_region_edit_poll(), text_set_selection_cancel(), text_set_selection_invoke(), and text_set_selection_modal().
Referenced by text_operatortypes().
void TEXT_OT_to_3d_object (struct wmOperatorType * ot)
Definition at line 3272 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, text_edit_poll(), and text_to_3d_object_exec().
Referenced by text_operatortypes().
void TEXT_OT_uncomment (struct wmOperatorType * ot)
Definition at line 1070 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_uncomment_exec().
Referenced by text_operatortypes().
void TEXT_OT_unindent (struct wmOperatorType * ot)
Definition at line 955 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, text_edit_poll(), and text_unindent_exec().
Referenced by text_operatortypes().
void TEXT_OT_unlink (struct wmOperatorType * ot)
Definition at line 391 of file text_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, text_unlink_exec(), text_unlink_poll(), and WM_operator_confirm().
Referenced by text_operatortypes().
void text_pop_suggest_list (void)
Definition at line 105 of file text_python.c.
References i, SuggItem::next, SUGG_LIST_SIZE, texttool_suggest_first(), texttool_suggest_selected(), and texttool_suggest_top().
Referenced by do_texttools(), and draw_suggestion_list().
void text_scroll_to_cursor (struct SpaceText * st, struct ScrArea * sa)
Definition at line 1878 of file text_draw.c.
References Text::curc, Text::curl, SpaceText::cwidth, ELEM3, ListBase::first, i, SpaceText::left, TextLine::line, Text::lines, ARegion::next, NULL, ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_WINDOW, Text::selc, Text::sell, SpaceText::text, text_draw(), text_update_character_width(), SpaceText::top, txt_get_span(), TXT_SCROLL_WIDTH, SpaceText::viewlines, ARegion::winx, SpaceText::wordwrap, and wrap_offset().
Referenced by text_listener(), and text_update_cursor_moved().
void text_update_character_width (struct SpaceText * st)
Definition at line 1868 of file text_draw.c.
References BLF_fixed_width(), SpaceText::cwidth, MAX2, mono, text_font_begin(), and text_font_end().
Referenced by text_cursor_set_to_pos(), text_do_suggest_select(), text_line_number_invoke(), text_scroll_apply(), text_scroll_invoke(), text_scroll_to_cursor(), text_update_drawcache(), txt_wrap_move_bol(), txt_wrap_move_down(), txt_wrap_move_eol(), and txt_wrap_move_up().
void text_update_cursor_moved (struct bContext * C)
Definition at line 1922 of file text_draw.c.
References CTX_wm_area(), CTX_wm_space_text(), and text_scroll_to_cursor().
Referenced by ED_text_undo_step(), text_clear_all_markers_exec(), text_comment_exec(), text_convert_whitespace_exec(), text_cursor_set_apply(), text_cursor_set_exec(), text_cursor_set_exit(), text_cut_exec(), text_delete_exec(), text_find_and_replace(), text_indent_exec(), text_insert_exec(), text_jump_exec(), text_line_break_exec(), text_line_number_invoke(), text_make_internal_exec(), text_move_cursor(), text_next_marker_exec(), text_paste_exec(), text_previous_marker_exec(), text_reload_exec(), text_run_script(), text_save_as_exec(), text_save_exec(), text_select_all_exec(), text_select_line_exec(), text_select_word_exec(), text_uncomment_exec(), text_unindent_exec(), and text_unlink_exec().
void text_update_edited (struct Text * text)
Definition at line 153 of file text_ops.c.
References ListBase::first, Text::lines, TextLine::next, and text_update_line_edited().
void text_update_line_edited (struct TextLine * line)
Definition at line 141 of file text_ops.c.
References TextLine::format, MEM_freeN(), and NULL.
Referenced by do_textmarkers(), do_texttools(), text_delete_exec(), text_insert_exec(), text_line_break_exec(), and text_update_edited().
void wrap_offset (struct SpaceText * st, struct ARegion * ar, struct TextLine * linein, int cursin, int * offl, int * offc)
Definition at line 534 of file text_draw.c.
References BLI_str_utf8_size(), ListBase::first, i, TextLine::line, Text::lines, max, TextLine::next, SpaceText::tabnumber, SpaceText::text, text_get_visible_lines(), SpaceText::top, txt_utf8_offset_to_index(), SpaceText::wordwrap, and wrap_width().
Referenced by draw_brackets(), draw_cursor(), draw_markers(), and text_scroll_to_cursor().
void wrap_offset_in_line (struct SpaceText * st, struct ARegion * ar, struct TextLine * linep, int cursin, int * offl, int * offc)
Definition at line 626 of file text_draw.c.
References BLI_str_utf8_size(), i, TextLine::line, max, SpaceText::tabnumber, SpaceText::text, txt_utf8_offset_to_index(), SpaceText::wordwrap, and wrap_width().
Referenced by cursor_skip_find_line(), draw_cursor(), txt_wrap_move_down(), and txt_wrap_move_up().
int wrap_width (struct SpaceText * st, struct ARegion * ar)
Definition at line 523 of file text_draw.c.
References SpaceText::cwidth, max, SpaceText::showlinenrs, TEXTXLOC, TXT_OFFSET, TXT_SCROLL_WIDTH, and ARegion::winx.
Referenced by text_cursor_set_to_pos_wrapped(), text_get_cursor_rel(), text_get_visible_lines(), txt_wrap_move_bol(), txt_wrap_move_eol(), wrap_offset(), and wrap_offset_in_line().
Variable Documentation
const char* text_context_dir[]
Definition at line 385 of file space_text.c.