Blender: LOD_Vertex Class Reference
LOD_Vertex Class Reference
#include <LOD_MeshPrimitives.h>
Public Member Functions
LOD_Vertex ()
bool RemoveEdge (LOD_EdgeInd e)
void AddEdge (LOD_EdgeInd e)
void SwapEdge (LOD_EdgeInd e_old, LOD_EdgeInd e_new)
bool SelectTag () const
void SetSelectTag (bool tag)
bool Degenerate ()
void CopyPosition (float *float_ptr)
Public Attributes
MT_Vector3 pos
std::vector< LOD_EdgeInd > m_edges
bool m_select_tag
Detailed Description
Definition at line 46 of file LOD_MeshPrimitives.h.
Constructor & Destructor Documentation
LOD_Vertex::LOD_Vertex ()
Definition at line 45 of file LOD_MeshPrimitives.cpp.
Member Function Documentation
void LOD_Vertex::AddEdge (LOD_EdgeInd e)
Definition at line 70 of file LOD_MeshPrimitives.cpp.
References m_edges.
void LOD_Vertex::CopyPosition (float * float_ptr)
Definition at line 118 of file LOD_MeshPrimitives.cpp.
References MT_Tuple3::getValue(), and pos.
bool LOD_Vertex::Degenerate ()
Definition at line 111 of file LOD_MeshPrimitives.cpp.
References m_edges.
bool LOD_Vertex::RemoveEdge (LOD_EdgeInd e)
Definition at line 54 of file LOD_MeshPrimitives.cpp.
References find(), m_edges, and swap().
bool LOD_Vertex::SelectTag () const
Definition at line 96 of file LOD_MeshPrimitives.cpp.
References m_select_tag.
void LOD_Vertex::SetSelectTag (bool tag)
Definition at line 103 of file LOD_MeshPrimitives.cpp.
References m_select_tag.
void LOD_Vertex::SwapEdge (LOD_EdgeInd e_old, LOD_EdgeInd e_new)
Definition at line 78 of file LOD_MeshPrimitives.cpp.
References LOD_MeshException::e_search_error, find(), m_edges, and MT_assert.
Member Data Documentation
std::vector<LOD_EdgeInd> LOD_Vertex::m_edges
Definition at line 49 of file LOD_MeshPrimitives.h.
Referenced by AddEdge(), Degenerate(), RemoveEdge(), and SwapEdge().
bool LOD_Vertex::m_select_tag
Definition at line 50 of file LOD_MeshPrimitives.h.
Referenced by SelectTag(), and SetSelectTag().
MT_Vector3 LOD_Vertex::pos
Definition at line 48 of file LOD_MeshPrimitives.h.
Referenced by CopyPosition().
The documentation for this class was generated from the following files:
LOD_MeshPrimitives.h
LOD_MeshPrimitives.cpp