Blender: utf_winfunc.c File Reference
utf_winfunc.c File Reference
#include "utf_winfunc.h"
#include <io.h>
#include <Windows.h>
#include <wchar.h>
Defines
#define _WIN32_IE 0x0501
Functions
FILE * ufopen (const char *filename, const char *mode)
int uopen (const char *filename, int oflag, int pmode)
int urename (const char *oldname, const char *newname)
int umkdir (const char *pathname)
char * u_alloc_getenv (const char *varname)
void u_free_getenv (char *val)
int uput_getenv (const char *varname, char *value, size_t buffsize)
int uputenv (const char *name, const char *value)
Define Documentation
#define _WIN32_IE 0x0501
Definition at line 27 of file utf_winfunc.c.
Function Documentation
char* u_alloc_getenv (const char * varname)
Definition at line 104 of file utf_winfunc.c.
References alloc_utf_8_from_16(), str, UTF16_ENCODE, and UTF16_UN_ENCODE.
void u_free_getenv (char * val)
Definition at line 117 of file utf_winfunc.c.
FILE* ufopen (const char * filename, const char * mode)
Definition at line 36 of file utf_winfunc.c.
References NULL, UTF16_ENCODE, and UTF16_UN_ENCODE.
int umkdir (const char * pathname)
Definition at line 91 of file utf_winfunc.c.
References BOOL, NULL, UTF16_ENCODE, and UTF16_UN_ENCODE.
int uopen (const char * filename, int oflag, int pmode)
Definition at line 58 of file utf_winfunc.c.
References UTF16_ENCODE, and UTF16_UN_ENCODE.
int uput_getenv (const char * varname, char * value, size_t buffsize)
Definition at line 122 of file utf_winfunc.c.
References conv_utf_16_to_8(), str, UTF16_ENCODE, and UTF16_UN_ENCODE.
Referenced by BLI_getDefaultDocumentFolder().
int uputenv (const char * name, const char * value)
Definition at line 141 of file utf_winfunc.c.
References UTF16_ENCODE, and UTF16_UN_ENCODE.
Referenced by BLI_setenv().
int urename (const char * oldname, const char * newname)
Definition at line 78 of file utf_winfunc.c.
References UTF16_ENCODE, and UTF16_UN_ENCODE.