Blender: KX_IpoSGController Class Reference
KX_IpoSGController Class Reference
#include <KX_IPO_SGController.h>
Public Member Functions
KX_IpoSGController ()
virtual ~KX_IpoSGController ()
virtual SG_Controller * GetReplica (class SG_Node *destnode)
void SetOption (int option, int value)
void UpdateSumoReference ()
void SetGameObject (class KX_GameObject *)
void SetIPOChannelActive (int index, bool value)
KX_IPOTransform & GetIPOTransform ()
void AddInterpolator (KX_IInterpolator *interp)
virtual bool Update (double time)
virtual void SetSimulatedTime (double time)
Detailed Description
Definition at line 43 of file KX_IPO_SGController.h.
Constructor & Destructor Documentation
KX_IpoSGController::KX_IpoSGController ()
Definition at line 55 of file KX_IPO_SGController.cpp.
References i, KX_MAX_IPO_CHANNELS, and NULL.
Referenced by GetReplica().
KX_IpoSGController::~KX_IpoSGController () [virtual]
Definition at line 379 of file KX_IPO_SGController.cpp.
References i.
Member Function Documentation
void KX_IpoSGController::AddInterpolator (KX_IInterpolator * interp)
Definition at line 343 of file KX_IPO_SGController.cpp.
Referenced by BL_CreateIPO(), and GetReplica().
KX_IPOTransform& KX_IpoSGController::GetIPOTransform () [inline]
Definition at line 111 of file KX_IPO_SGController.h.
Referenced by BL_CreateIPO().
SG_Controller * KX_IpoSGController::GetReplica (class SG_Node * destnode) [virtual]
Implements SG_Controller.
Definition at line 348 of file KX_IPO_SGController.cpp.
References AddInterpolator(), SG_Controller::ClearObject(), SG_IObject::GetSGClientObject(), i, KX_IpoSGController(), SetGameObject(), and KX_ScalarInterpolator::SetNewTarget().
void KX_IpoSGController::SetGameObject (class KX_GameObject * go)
Set reference to the corresponding game object.
Definition at line 114 of file KX_IPO_SGController.cpp.
Referenced by BL_CreateIPO(), and GetReplica().
void KX_IpoSGController::SetIPOChannelActive (int index, bool value) [inline]
Definition at line 105 of file KX_IPO_SGController.h.
Referenced by BL_CreateIPO().
void KX_IpoSGController::SetOption (int option, int value) [virtual]
Hacky way of passing options to specific controllers
Parameters:
option An integer identifying the option.
value The value of this option.
Attention:
This has been placed here to give sca-elements
some control over the controllers. This is
necessary because the identity of the controller
is lost on the way here.
Implements SG_Controller.
Definition at line 71 of file KX_IPO_SGController.cpp.
References SG_Controller::SG_CONTR_IPO_IPO_ADD, SG_Controller::SG_CONTR_IPO_IPO_AS_FORCE, SG_Controller::SG_CONTR_IPO_LOCAL, and SG_Controller::SG_CONTR_IPO_RESET.
virtual void KX_IpoSGController::SetSimulatedTime (double time) [inline, virtual]
Implements SG_Controller.
Definition at line 117 of file KX_IPO_SGController.h.
bool KX_IpoSGController::Update (double time) [virtual]
Implements SG_Controller.
Definition at line 123 of file KX_IPO_SGController.cpp.
References KX_IPhysicsController::ApplyForce(), KX_GameObject::ApplyTorque(), KX_IPOTransform::GetDeltaEulerAngles(), KX_IPOTransform::GetDeltaPosition(), KX_IPOTransform::GetDeltaScaling(), MT_Matrix3x3::getEuler(), KX_IPOTransform::GetEulerAngles(), SG_Spatial::GetLocalOrientation(), SG_Spatial::GetLocalPosition(), SG_Spatial::GetLocalScale(), KX_GameObject::GetPhysicsController(), KX_IPOTransform::GetPosition(), KX_IPOTransform::GetScaling(), SG_Spatial::GetWorldOrientation(), i, SG_Controller::m_pObject, KX_GameObject::NodeSetLocalOrientation(), KX_GameObject::NodeSetLocalPosition(), KX_GameObject::NodeSetLocalScale(), OB_DLOC_X, OB_DLOC_Y, OB_DLOC_Z, OB_DROT_X, OB_DROT_Y, OB_DROT_Z, OB_DSIZE_X, OB_DSIZE_Y, OB_DSIZE_Z, OB_LOC_X, OB_LOC_Y, OB_LOC_Z, OB_ROT_X, OB_ROT_Y, OB_ROT_Z, OB_SIZE_X, OB_SIZE_Y, and OB_SIZE_Z.
void KX_IpoSGController::UpdateSumoReference ()
Set sumo data.
Definition at line 105 of file KX_IPO_SGController.cpp.
The documentation for this class was generated from the following files:
KX_IPO_SGController.h
KX_IPO_SGController.cpp