Blender: AUD_DelayReader Class Reference
AUD_DelayReader Class Reference
#include <AUD_DelayReader.h>
Public Member Functions
AUD_DelayReader (AUD_Reference< AUD_IReader > reader, float delay)
virtual void seek (int position)
virtual int getLength () const
virtual int getPosition () const
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This class reads another reader and delays it.
Definition at line 39 of file AUD_DelayReader.h.
Constructor & Destructor Documentation
AUD_DelayReader::AUD_DelayReader (AUD_Reference< AUD_IReader > reader, float delay)
Creates a new delay reader.
Parameters:
reader The reader to read from.
delay The delay in seconds.
Definition at line 34 of file AUD_DelayReader.cpp.
Member Function Documentation
int AUD_DelayReader::getLength () const [virtual]
Returns an approximated length of the source in samples.
Returns:
The length as sample count. May be negative if unknown.
Reimplemented from AUD_EffectReader.
Definition at line 55 of file AUD_DelayReader.cpp.
References len(), and AUD_EffectReader::m_reader.
int AUD_DelayReader::getPosition () const [virtual]
Returns the position of the source as a sample count value.
Returns:
The current position in the source. A negative value indicates that the position is unknown.
Warning:
The value returned doesn't always have to be correct for readers, especially after seeking.
Reimplemented from AUD_EffectReader.
Definition at line 63 of file AUD_DelayReader.cpp.
References AUD_EffectReader::m_reader.
void AUD_DelayReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Reimplemented from AUD_EffectReader.
Definition at line 70 of file AUD_DelayReader.cpp.
References AUD_SAMPLE_SIZE, AUD_Specs::channels, len(), length(), and AUD_EffectReader::m_reader.
void AUD_DelayReader::seek (int position) [virtual]
Seeks to a specific position in the source.
Parameters:
position The position to seek for measured in samples. To get from a given time to the samples you simply have to multiply the time value in seconds with the sample rate of the reader.
Warning:
This may work or not, depending on the actual reader.
Reimplemented from AUD_EffectReader.
Definition at line 41 of file AUD_DelayReader.cpp.
References AUD_EffectReader::m_reader.
The documentation for this class was generated from the following files:
AUD_DelayReader.h
AUD_DelayReader.cpp