Blender: particle_boids.c File Reference
particle_boids.c File Reference
physics
#include <stdlib.h>
#include "MEM_guardedalloc.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "BLI_listbase.h"
#include "BLI_utildefines.h"
#include "BKE_boids.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_main.h"
#include "BKE_particle.h"
#include "RNA_access.h"
#include "RNA_enum_types.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "physics_intern.h"
Functions
static int rule_add_exec (bContext *C, wmOperator *op)
void BOID_OT_rule_add (wmOperatorType *ot)
static int rule_del_exec (bContext *C, wmOperator *UNUSED(op))
void BOID_OT_rule_del (wmOperatorType *ot)
static int rule_move_up_exec (bContext *C, wmOperator *UNUSED(op))
void BOID_OT_rule_move_up (wmOperatorType *ot)
static int rule_move_down_exec (bContext *C, wmOperator *UNUSED(op))
void BOID_OT_rule_move_down (wmOperatorType *ot)
static int state_add_exec (bContext *C, wmOperator *UNUSED(op))
void BOID_OT_state_add (wmOperatorType *ot)
static int state_del_exec (bContext *C, wmOperator *UNUSED(op))
void BOID_OT_state_del (wmOperatorType *ot)
static int state_move_up_exec (bContext *C, wmOperator *UNUSED(op))
void BOID_OT_state_move_up (wmOperatorType *ot)
static int state_move_down_exec (bContext *C, wmOperator *UNUSED(op))
void BOID_OT_state_move_down (wmOperatorType *ot)
Detailed Description
Definition in file particle_boids.c.
Function Documentation
void BOID_OT_rule_add (wmOperatorType * ot)
Definition at line 90 of file particle_boids.c.
References boidrule_type_items, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, RNA_def_enum(), rule_add_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by operatortypes_boids().
void BOID_OT_rule_del (wmOperatorType * ot)
Definition at line 143 of file particle_boids.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and rule_del_exec().
Referenced by operatortypes_boids().
void BOID_OT_rule_move_down (wmOperatorType * ot)
Definition at line 221 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and rule_move_down_exec().
Referenced by operatortypes_boids().
void BOID_OT_rule_move_up (wmOperatorType * ot)
Definition at line 183 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and rule_move_up_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_add (wmOperatorType * ot)
Definition at line 261 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_add_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_del (wmOperatorType * ot)
Definition at line 316 of file particle_boids.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_del_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_move_down (wmOperatorType * ot)
Definition at line 391 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_move_down_exec().
Referenced by operatortypes_boids().
void BOID_OT_state_move_up (wmOperatorType * ot)
Definition at line 355 of file particle_boids.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and state_move_up_exec().
Referenced by operatortypes_boids().
static int rule_add_exec (bContext * C, wmOperator * op) [static]
Definition at line 57 of file particle_boids.c.
References BLI_addtail(), boid_get_current_state(), boid_new_rule(), BOIDRULE_CURRENT, ParticleSettings::boids, CTX_data_pointer_get_type(), DAG_id_tag_update(), PointerRNA::data, ListBase::first, BoidRule::flag, ParticleSettings::id, PointerRNA::id, NC_OBJECT, ND_DRAW, BoidRule::next, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, PSYS_RECALC_RESET, wmOperator::ptr, RNA_enum_get(), RNA_ParticleSystem, BoidState::rules, state, and WM_event_add_notifier().
Referenced by BOID_OT_rule_add().
static int rule_del_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 106 of file particle_boids.c.
References BLI_remlink(), boid_get_current_state(), BOIDRULE_CURRENT, ParticleSettings::boids, CTX_data_main(), CTX_data_pointer_get_type(), CTX_data_scene(), DAG_id_tag_update(), DAG_scene_sort(), PointerRNA::data, ListBase::first, BoidRule::flag, ParticleSettings::id, PointerRNA::id, MEM_freeN(), NC_OBJECT, ND_DRAW, BoidRule::next, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, PSYS_RECALC_RESET, RNA_ParticleSystem, BoidState::rules, state, and WM_event_add_notifier().
Referenced by BOID_OT_rule_del().
static int rule_move_down_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 195 of file particle_boids.c.
References BLI_insertlink(), BLI_remlink(), boid_get_current_state(), BOIDRULE_CURRENT, ParticleSettings::boids, CTX_data_pointer_get_type(), DAG_id_tag_update(), PointerRNA::data, ListBase::first, BoidRule::flag, ParticleSettings::id, PointerRNA::id, NC_OBJECT, ND_DRAW, BoidRule::next, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, PSYS_RECALC_RESET, RNA_ParticleSystem, BoidState::rules, state, and WM_event_add_notifier().
Referenced by BOID_OT_rule_move_down().
static int rule_move_up_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 157 of file particle_boids.c.
References BLI_insertlink(), BLI_remlink(), boid_get_current_state(), BOIDRULE_CURRENT, ParticleSettings::boids, CTX_data_pointer_get_type(), DAG_id_tag_update(), PointerRNA::data, ListBase::first, BoidRule::flag, ParticleSettings::id, PointerRNA::id, NC_OBJECT, ND_DRAW, BoidRule::next, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, BoidRule::prev, PSYS_RECALC_RESET, RNA_ParticleSystem, BoidState::rules, state, and WM_event_add_notifier().
Referenced by BOID_OT_rule_move_up().
static int state_add_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 235 of file particle_boids.c.
References BLI_addtail(), boid_new_state(), ParticleSettings::boids, BOIDSTATE_CURRENT, CTX_data_pointer_get_type(), PointerRNA::data, ListBase::first, BoidState::flag, PointerRNA::id, NC_OBJECT, ND_DRAW, BoidState::next, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, RNA_ParticleSystem, state, BoidSettings::states, and WM_event_add_notifier().
Referenced by BOID_OT_state_add().
static int state_del_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 274 of file particle_boids.c.
References BLI_addtail(), BLI_remlink(), boid_new_state(), ParticleSettings::boids, BOIDSTATE_CURRENT, CTX_data_main(), CTX_data_pointer_get_type(), CTX_data_scene(), DAG_id_tag_update(), DAG_scene_sort(), PointerRNA::data, ListBase::first, BoidState::flag, ParticleSettings::id, PointerRNA::id, MEM_freeN(), NC_OBJECT, ND_DRAW, BoidState::next, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, PSYS_RECALC_RESET, RNA_ParticleSystem, state, BoidSettings::states, and WM_event_add_notifier().
Referenced by BOID_OT_state_del().
static int state_move_down_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 367 of file particle_boids.c.
References BLI_insertlink(), BLI_remlink(), ParticleSettings::boids, BOIDSTATE_CURRENT, CTX_data_pointer_get_type(), DAG_id_tag_update(), PointerRNA::data, ListBase::first, BoidState::flag, ParticleSettings::id, BoidState::next, OB_RECALC_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, PSYS_RECALC_RESET, RNA_ParticleSystem, state, and BoidSettings::states.
Referenced by BOID_OT_state_move_down().
static int state_move_up_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 330 of file particle_boids.c.
References BLI_insertlink(), BLI_remlink(), ParticleSettings::boids, BOIDSTATE_CURRENT, CTX_data_pointer_get_type(), PointerRNA::data, ListBase::first, BoidState::flag, PointerRNA::id, NC_OBJECT, ND_DRAW, BoidState::next, OPERATOR_CANCELLED, OPERATOR_FINISHED, ParticleSystem::part, PART_PHYS_BOIDS, ParticleSettings::phystype, BoidState::prev, RNA_ParticleSystem, state, BoidSettings::states, and WM_event_add_notifier().
Referenced by BOID_OT_state_move_up().