Blender: node_shader_texture.c File Reference
node_shader_texture.c File Reference
shdnodes
#include "DNA_texture_types.h"
#include "node_shader_util.h"
Functions
static void node_shader_exec_texture (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
static int gpu_shader_texture (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_texture (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_texture_in []
static bNodeSocketTemplate sh_node_texture_out []
Detailed Description
Definition in file node_shader_texture.c.
Function Documentation
static int gpu_shader_texture (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 124 of file node_shader_texture.c.
References GPU_image(), GPU_stack_link(), bNode::id, if(), Tex::ima, NULL, TEX_IMAGE, and Tex::type.
Referenced by register_node_type_sh_texture().
static void node_shader_exec_texture (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 49 of file node_shader_texture.c.
References CLAMP(), copy_v3_v3(), bNode::custom1, bNodeStack::data, ShadeInput::do_manage, ShadeInput::do_preview, ListBase::first, bNode::id, bNode::inputs, bNodeSocket::link, ShadeInput::lo, multitex_nodes(), nodeAddToPreview(), nodestack_get_vec(), TexResult::nor, NS_OSA_VALUES, NS_OSA_VECTORS, NULL, ShadeInput::osatex, SOCK_VECTOR, TexResult::ta, TexResult::talpha, TexResult::tb, TEX_RGB, TEX_STUCCI, TexResult::tg, ShadeInput::thread, TexResult::tin, TexResult::tr, bNodeStack::vec, ShadeInput::xs, and ShadeInput::ys.
Referenced by register_node_type_sh_texture().
void register_node_type_sh_texture (bNodeTreeType * ttype)
Definition at line 136 of file node_shader_texture.c.
References gpu_shader_texture(), NODE_CLASS_INPUT, NODE_OLD_SHADING, NODE_OPTIONS, NODE_PREVIEW, node_shader_exec_texture(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and SH_NODE_TEXTURE.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_texture_in[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 1, "Vector",   0.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_NONE, SOCK_HIDE_VALUE},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_shader_texture.c.
bNodeSocketTemplate sh_node_texture_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Value"},
    {   SOCK_RGBA , 0, "Color"},
    {   SOCK_VECTOR, 0, "Normal"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_shader_texture.c.