Blender: BOP_Mesh.cpp File Reference
BOP_Mesh.cpp File Reference
#include "BOP_Mesh.h"
#include "BOP_MathUtils.h"
#include <iostream>
#include <fstream>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
Functions
static void removeBrokenFaces (BOP_Edge *edge, BOP_Mesh *mesh)
Detailed Description
Definition in file BOP_Mesh.cpp.
Function Documentation
static void removeBrokenFaces (BOP_Edge * edge, BOP_Mesh * mesh) [static]
Marks faces which bad edges as BROKEN (invalid face, no further processing).
Parameters:
edge edge which is being replaced
mesh mesh containing faces
Definition at line 697 of file BOP_Mesh.cpp.
References BROKEN, BOP_Edge::getFaces(), and BOP_Mesh::getFaces().
Referenced by BOP_Mesh::replaceVertexIndex().