Blender: DebugDrawcallback Class Reference
DebugDrawcallback Class Reference
Public Member Functions
DebugDrawcallback (btIDebugDraw *debugDrawer, const btTransform &worldTrans, const btVector3 &color)
virtual void internalProcessTriangleIndex (btVector3 *triangle, int partId, int triangleIndex)
virtual void processTriangle (btVector3 *triangle, int partId, int triangleIndex)
Detailed Description
Definition at line 1135 of file btCollisionWorld.cpp.
Constructor & Destructor Documentation
DebugDrawcallback::DebugDrawcallback (btIDebugDraw * debugDrawer, const btTransform & worldTrans, const btVector3 & color) [inline]
Definition at line 1143 of file btCollisionWorld.cpp.
Member Function Documentation
virtual void DebugDrawcallback::internalProcessTriangleIndex (btVector3 * triangle, int partId, int triangleIndex) [inline, virtual]
Implements btInternalTriangleIndexCallback.
Definition at line 1150 of file btCollisionWorld.cpp.
References processTriangle().
virtual void DebugDrawcallback::processTriangle (btVector3 * triangle, int partId, int triangleIndex) [inline, virtual]
Implements btTriangleCallback.
Definition at line 1155 of file btCollisionWorld.cpp.
References cross(), and btIDebugDraw::drawLine().
Referenced by internalProcessTriangleIndex().
The documentation for this class was generated from the following file:
btCollisionWorld.cpp