Blender: blender_python.cpp File Reference
blender_python.cpp File Reference
#include <Python.h>
#include "CCL_api.h"
#include "blender_sync.h"
#include "blender_session.h"
#include "util_foreach.h"
#include "util_opengl.h"
#include "util_path.h"
Functions
static CCL_NAMESPACE_BEGIN
PyObject * init_func (PyObject *self, PyObject *args)
static PyObject * create_func (PyObject *self, PyObject *args)
static PyObject * free_func (PyObject *self, PyObject *value)
static PyObject * render_func (PyObject *self, PyObject *value)
static PyObject * draw_func (PyObject *self, PyObject *args)
static PyObject * sync_func (PyObject *self, PyObject *value)
static PyObject * available_devices_func (PyObject *self, PyObject *args)
CCLDeviceInfo * compute_device_list (DeviceType type)
CCL_NAMESPACE_END void * CCL_python_module_init ()
CCLDeviceInfo * CCL_compute_device_list (int opencl)
Variables
static PyMethodDef methods []
static struct PyModuleDef module
Function Documentation
static PyObject* available_devices_func (PyObject * self, PyObject * args) [static]
Definition at line 145 of file blender_python.cpp.
References Device::available_devices(), DeviceInfo::description, and i.
CCLDeviceInfo* CCL_compute_device_list (int opencl)
Definition at line 230 of file blender_python.cpp.
References compute_device_list(), DEVICE_CUDA, and DEVICE_OPENCL.
CCL_NAMESPACE_END void* CCL_python_module_init (void)
Definition at line 215 of file blender_python.cpp.
References mod(), and module.
CCLDeviceInfo* compute_device_list (DeviceType type)
Definition at line 178 of file blender_python.cpp.
References DeviceInfo::description, DEVICE_MULTI, DEVICE_NONE, i, DeviceInfo::id, DeviceInfo::multi_devices, NULL, and DeviceInfo::type.
Referenced by CCL_compute_device_list().
static PyObject* create_func (PyObject * self, PyObject * args) [static]
Definition at line 44 of file blender_python.cpp.
References data, NULL, RNA_id_pointer_create(), RNA_pointer_create(), RNA_RenderEngine, and BlenderSession::width.
Referenced by ui_popup_block_create().
static PyObject* draw_func (PyObject * self, PyObject * args) [static]
Definition at line 117 of file blender_python.cpp.
References BlenderSession::draw(), and NULL.
static PyObject* free_func (PyObject * self, PyObject * value) [static]
Definition at line 98 of file blender_python.cpp.
static CCL_NAMESPACE_BEGIN PyObject* init_func (PyObject * self, PyObject * args) [static]
Definition at line 32 of file blender_python.cpp.
References NULL, and path_init().
static PyObject* render_func (PyObject * self, PyObject * value) [static]
Definition at line 105 of file blender_python.cpp.
References BlenderSession::render().
static PyObject* sync_func (PyObject * self, PyObject * value) [static]
Definition at line 137 of file blender_python.cpp.
References BlenderSession::synchronize().
Variable Documentation
PyMethodDef methods[] [static]
Initial value:
 {
    {"init", init_func, METH_VARARGS, ""},
    {"create", create_func, METH_VARARGS, ""},
    {"free", free_func, METH_O, ""},
    {"render", render_func, METH_O, ""},
    {"draw", draw_func, METH_VARARGS, ""},
    {"sync", sync_func, METH_O, ""},
    {"available_devices", available_devices_func, METH_NOARGS, ""},
    {NULL, NULL, 0, NULL},
}
Definition at line 158 of file blender_python.cpp.
struct PyModuleDef module [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "_cycles",
    "Blender cycles render integration",
    -1,
    methods,
    NULL, NULL, NULL, NULL
}
Definition at line 169 of file blender_python.cpp.
Referenced by btGenericMemoryPool::allocate(), BPY_modules_load_user(), CCL_python_module_init(), dynamic_library_open(), GPU_initPython(), and init_userdef_do_versions().