Blender: AUD_MixerFactory Class Reference
AUD_MixerFactory Class Reference
#include <AUD_MixerFactory.h>
Public Member Functions
AUD_MixerFactory (AUD_Reference< AUD_IFactory > factory, AUD_DeviceSpecs specs)
AUD_DeviceSpecs getSpecs () const
AUD_Reference< AUD_IFactory > getFactory () const
Protected Member Functions
AUD_Reference< AUD_IReader > getReader () const
Protected Attributes
const AUD_DeviceSpecs m_specs
AUD_Reference< AUD_IFactory > m_factory
Detailed Description
This factory is a base class for all mixer factories.
Definition at line 38 of file AUD_MixerFactory.h.
Constructor & Destructor Documentation
AUD_MixerFactory::AUD_MixerFactory (AUD_Reference< AUD_IFactory > factory, AUD_DeviceSpecs specs)
Creates a new factory.
Parameters:
factory The factory to create the readers to mix out of.
specs The target specification.
Definition at line 38 of file AUD_MixerFactory.cpp.
Member Function Documentation
AUD_Reference< AUD_IFactory > AUD_MixerFactory::getFactory () const
Returns the saved factory.
Returns:
The factory.
Definition at line 49 of file AUD_MixerFactory.cpp.
References m_factory.
AUD_Reference< AUD_IReader > AUD_MixerFactory::getReader () const [protected]
Returns the reader created out of the factory. This method can be used for the createReader function of the implementing classes.
Returns:
The reader to mix.
Definition at line 33 of file AUD_MixerFactory.cpp.
References m_factory.
Referenced by AUD_SRCResampleFactory::createReader(), AUD_ConverterFactory::createReader(), AUD_LinearResampleFactory::createReader(), AUD_ChannelMapperFactory::createReader(), and AUD_JOSResampleFactory::createReader().
AUD_DeviceSpecs AUD_MixerFactory::getSpecs () const
Returns the target specification for resampling.
Definition at line 44 of file AUD_MixerFactory.cpp.
References m_specs.
Member Data Documentation
AUD_Reference<AUD_IFactory> AUD_MixerFactory::m_factory [protected]
If there is no reader it is created out of this factory.
Definition at line 49 of file AUD_MixerFactory.h.
Referenced by getFactory(), and getReader().
const AUD_DeviceSpecs AUD_MixerFactory::m_specs [protected]
The target specification for resampling.
Definition at line 44 of file AUD_MixerFactory.h.
Referenced by AUD_SRCResampleFactory::createReader(), AUD_ConverterFactory::createReader(), AUD_LinearResampleFactory::createReader(), AUD_ChannelMapperFactory::createReader(), AUD_JOSResampleFactory::createReader(), and getSpecs().
The documentation for this class was generated from the following files:
AUD_MixerFactory.h
AUD_MixerFactory.cpp