Blender: sculpt_uv.c File Reference
sculpt_uv.c File Reference
sculpt and paint
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_ghash.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_brush_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "BKE_brush.h"
#include "BKE_paint.h"
#include "BKE_context.h"
#include "BKE_main.h"
#include "BKE_depsgraph.h"
#include "BKE_mesh.h"
#include "BKE_customdata.h"
#include "BKE_tessmesh.h"
#include "ED_screen.h"
#include "ED_image.h"
#include "ED_mesh.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "paint_intern.h"
#include "uvedit_intern.h"
#include "UI_view2d.h"
Classes
struct UvAdjacencyElement
struct UvEdge
struct UVInitialStrokeElement
struct UVInitialStroke
struct UvSculptData
struct Temp_UvData
Defines
#define MARK_BOUNDARY 1
Typedefs
typedef struct UvAdjacencyElement UvAdjacencyElement
typedef struct UvEdge UvEdge
typedef struct
UVInitialStrokeElement UVInitialStrokeElement
typedef struct UVInitialStroke UVInitialStroke
typedef struct UvSculptData UvSculptData
typedef struct Temp_UvData Temp_UVData
Functions
void HC_relaxation_iteration_uv (BMEditMesh *em, UvSculptData *sculptdata, float mouse_coord[2], float alpha, float radius, float aspectRatio)
static void laplacian_relaxation_iteration_uv (BMEditMesh *em, UvSculptData *sculptdata, float mouse_coord[2], float alpha, float radius, float aspectRatio)
static void uv_sculpt_stroke_apply (bContext *C, wmOperator *op, wmEvent *event, Object *obedit)
static void uv_sculpt_stroke_exit (bContext *C, wmOperator *op)
static int uv_element_offset_from_face_get (UvElementMap *map, BMFace *efa, BMLoop *l, int island_index, int doIslands)
static unsigned int uv_edge_hash (const void *key)
static int uv_edge_compare (const void *a, const void *b)
static UvSculptData * uv_sculpt_stroke_init (bContext *C, wmOperator *op, wmEvent *event)
static int uv_sculpt_stroke_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int uv_sculpt_stroke_modal (bContext *C, wmOperator *op, wmEvent *event)
void SCULPT_OT_uv_sculpt_stroke (wmOperatorType *ot)
Detailed Description
Definition in file sculpt_uv.c.
Define Documentation
#define MARK_BOUNDARY 1
Definition at line 71 of file sculpt_uv.c.
Referenced by HC_relaxation_iteration_uv(), laplacian_relaxation_iteration_uv(), uv_sculpt_stroke_apply(), and uv_sculpt_stroke_init().
Typedef Documentation
typedef struct Temp_UvData Temp_UVData
typedef struct UvAdjacencyElement UvAdjacencyElement
typedef struct UvEdge UvEdge
typedef struct UVInitialStroke UVInitialStroke
typedef struct UVInitialStrokeElement UVInitialStrokeElement
typedef struct UvSculptData UvSculptData
Function Documentation
void HC_relaxation_iteration_uv (BMEditMesh * em, UvSculptData * sculptdata, float mouse_coord[2], float alpha, float radius, float aspectRatio)
Definition at line 159 of file sculpt_uv.c.
References add_v2_v2(), Temp_UvData::b, BMEditMesh::bm, brush_curve_strength(), CD_MLOOPUV, copy_v2_v2(), CustomData_bmesh_get(), BMHeader::data, KDL::diff(), dot_v2v2(), UvAdjacencyElement::element, UvAdjacencyElement::flag, BMLoop::head, i, UvElement::l, BMesh::ldata, MARK_BOUNDARY, MEM_callocN(), MEM_freeN(), mul_v2_fl(), Temp_UvData::ncounter, UvElement::next, Temp_UvData::p, p, paint_brush(), UvElement::separate, sqrt(), sub_v2_v2v2(), Temp_UvData::sum_b, Temp_UvData::sum_co, UvSculptData::totalUniqueUvs, UvSculptData::totalUvEdges, MLoopUV::uv, UvAdjacencyElement::uv, UvSculptData::uv, UvEdge::uv1, UvEdge::uv2, UvSculptData::uvedges, and UvSculptData::uvsculpt.
Referenced by uv_sculpt_stroke_apply().
static void laplacian_relaxation_iteration_uv (BMEditMesh * em, UvSculptData * sculptdata, float mouse_coord[2], float alpha, float radius, float aspectRatio) [static]
Definition at line 232 of file sculpt_uv.c.
References add_v2_v2(), BMEditMesh::bm, brush_curve_strength(), CD_MLOOPUV, copy_v2_v2(), CustomData_bmesh_get(), BMHeader::data, KDL::diff(), dot_v2v2(), UvAdjacencyElement::element, UvAdjacencyElement::flag, BMLoop::head, i, UvElement::l, BMesh::ldata, MARK_BOUNDARY, MEM_callocN(), MEM_freeN(), mul_v2_fl(), Temp_UvData::ncounter, UvElement::next, Temp_UvData::p, p, paint_brush(), UvElement::separate, sqrt(), sub_v2_v2v2(), Temp_UvData::sum_co, UvSculptData::totalUniqueUvs, UvSculptData::totalUvEdges, MLoopUV::uv, UvAdjacencyElement::uv, UvSculptData::uv, UvEdge::uv1, UvEdge::uv2, UvSculptData::uvedges, and UvSculptData::uvsculpt.
Referenced by uv_sculpt_stroke_apply().
void SCULPT_OT_uv_sculpt_stroke (wmOperatorType * ot)
Definition at line 787 of file sculpt_uv.c.
References BRUSH_STROKE_INVERT, BRUSH_STROKE_NORMAL, BRUSH_STROKE_SMOOTH, wmOperatorType::description, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, uv_sculpt_poll(), uv_sculpt_stroke_invoke(), and uv_sculpt_stroke_modal().
Referenced by ED_operatortypes_paint().
static int uv_edge_compare (const void * a, const void * b) [static]
Definition at line 455 of file sculpt_uv.c.
References UvEdge::uv1, and UvEdge::uv2.
Referenced by uv_sculpt_stroke_init().
static unsigned int uv_edge_hash (const void * key) [static]
Definition at line 448 of file sculpt_uv.c.
References BLI_ghashutil_inthash(), SET_INT_IN_POINTER, UvEdge::uv1, and UvEdge::uv2.
Referenced by uv_sculpt_stroke_init().
static int uv_element_offset_from_face_get (UvElementMap * map, BMFace * efa, BMLoop * l, int island_index, int doIslands) [static]
Definition at line 438 of file sculpt_uv.c.
References UvElementMap::buf, ED_uv_element_get(), and UvElement::island.
Referenced by uv_sculpt_stroke_init().
static void uv_sculpt_stroke_apply (bContext * C, wmOperator * op, wmEvent * event, Object * obedit) [static]
Definition at line 297 of file sculpt_uv.c.
References BMEditMesh::bm, BMEdit_FromObject(), brush_alpha(), brush_curve_strength(), brush_size(), CD_MLOOPUV, co, copy_v2_v2(), CTX_data_scene(), CTX_data_tool_settings(), CTX_wm_region(), CTX_wm_space_image(), wmOperator::customdata, CustomData_bmesh_get(), BMHeader::data, KDL::diff(), dot_v2v2(), ED_space_image_size(), ED_space_image_zoom(), UvAdjacencyElement::element, UvAdjacencyElement::flag, HC_relaxation_iteration_uv(), BMLoop::head, i, UVInitialStroke::init_coord, UvSculptData::initial_stroke, UVInitialStrokeElement::initial_uv, UVInitialStroke::initialSelection, UvSculptData::invert, invert(), UvElement::l, laplacian_relaxation_iteration_uv(), BMesh::ldata, MARK_BOUNDARY, wmEvent::mval, UvElement::next, normalize_v2(), paint_brush(), UvElement::separate, sqrt(), UVInitialStrokeElement::strength, sub_v2_v2v2(), UvSculptData::tool, UVInitialStroke::totalInitialSelected, UvSculptData::totalUniqueUvs, UI_view2d_region_to_view(), UVInitialStrokeElement::uv, MLoopUV::uv, UvAdjacencyElement::uv, UvSculptData::uv, ToolSettings::uv_relax_method, UV_SCULPT_TOOL_GRAB, UV_SCULPT_TOOL_PINCH, UV_SCULPT_TOOL_RELAX, UV_SCULPT_TOOL_RELAX_HC, UvSculptData::uvsculpt, and ARegion::v2d.
Referenced by uv_sculpt_stroke_invoke(), and uv_sculpt_stroke_modal().
static void uv_sculpt_stroke_exit (bContext * C, wmOperator * op) [static]
Definition at line 412 of file sculpt_uv.c.
References CTX_wm_manager(), CTX_wm_window(), wmOperator::customdata, data, EDBM_uv_element_map_free(), UvSculptData::elementMap, UvSculptData::initial_stroke, UVInitialStroke::initialSelection, MEM_freeN(), NULL, UvSculptData::timer, UvSculptData::uv, UvSculptData::uvedges, and WM_event_remove_timer().
Referenced by uv_sculpt_stroke_init(), uv_sculpt_stroke_invoke(), and uv_sculpt_stroke_modal().
static UvSculptData* uv_sculpt_stroke_init (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 467 of file sculpt_uv.c.
References BLI_ghash_free(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), BLI_ghash_size(), BLI_ghashIterator_free(), BLI_ghashIterator_getKey(), BLI_ghashIterator_isDone(), BLI_ghashIterator_new(), BLI_ghashIterator_step(), BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), brush_alpha(), brush_curve_strength(), brush_size(), BRUSH_STROKE_INVERT, BRUSH_STROKE_SMOOTH, UvElementMap::buf, CD_MLOOPUV, co, copy_v2_v2(), CTX_data_edit_image(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region(), CTX_wm_space_image(), wmOperator::customdata, CustomData_bmesh_get(), BMHeader::data, data, KDL::diff(), dot_v2v2(), ED_space_image_size(), ED_space_image_zoom(), ED_uv_element_get(), EDBM_uv_element_map_create(), NearestHit::efa, UvAdjacencyElement::element, UvSculptData::elementMap, UvEdge::flag, UvAdjacencyElement::flag, BMLoop::head, i, UVInitialStroke::init_coord, UvSculptData::initial_stroke, UVInitialStrokeElement::initial_uv, UVInitialStroke::initialSelection, UvSculptData::invert, UvElement::island, UvElement::l, NearestHit::l, BMesh::ldata, MARK_BOUNDARY, MEM_callocN(), MEM_freeN(), MEM_mallocN(), wmEvent::mval, BMLoop::next, UvElement::next, NULL, UvSculpt::paint, paint_brush(), wmOperator::ptr, RNA_enum_get(), UvElement::separate, sqrt(), UVInitialStrokeElement::strength, sub_v2_v2v2(), UvSculptData::tool, Scene::toolsettings, UVInitialStroke::totalInitialSelected, UvSculptData::totalUniqueUvs, UvSculptData::totalUvEdges, UvElementMap::totalUVs, BMesh::totvert, UI_view2d_region_to_view(), UVInitialStrokeElement::uv, MLoopUV::uv, UvAdjacencyElement::uv, UvSculptData::uv, UvEdge::uv1, UvEdge::uv2, uv_edge_compare(), uv_edge_hash(), uv_element_offset_from_face_get(), uv_find_nearest_vert(), ToolSettings::uv_flag, UV_SCULPT_ALL_ISLANDS, UV_SCULPT_LOCK_BORDERS, ToolSettings::uv_sculpt_settings, uv_sculpt_stroke_exit(), ToolSettings::uv_sculpt_tool, UV_SCULPT_TOOL_GRAB, UV_SCULPT_TOOL_RELAX, UV_SYNC_SELECTION, UvSculptData::uvedges, ToolSettings::uvsculpt, UvSculptData::uvsculpt, ARegion::v2d, and UvElementMap::vert.
Referenced by uv_sculpt_stroke_invoke().
static int uv_sculpt_stroke_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 734 of file sculpt_uv.c.
References CTX_data_edit_object(), CTX_wm_manager(), CTX_wm_window(), data, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, TIMER, UvSculptData::timer, uv_sculpt_stroke_apply(), uv_sculpt_stroke_exit(), uv_sculpt_stroke_init(), WM_event_add_modal_handler(), and WM_event_add_timer().
Referenced by SCULPT_OT_uv_sculpt_stroke().
static int uv_sculpt_stroke_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 757 of file sculpt_uv.c.
References CTX_data_edit_object(), CTX_wm_region(), wmEvent::customdata, wmOperator::customdata, DAG_id_tag_update(), data, ED_region_tag_redraw(), INBETWEEN_MOUSEMOVE, LEFTMOUSE, MIDDLEMOUSE, MOUSEMOVE, NC_GEOM, ND_DATA, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, UvSculptData::timer, TIMER, wmEvent::type, uv_sculpt_stroke_apply(), uv_sculpt_stroke_exit(), and WM_event_add_notifier().
Referenced by SCULPT_OT_uv_sculpt_stroke().