Blender: btCollisionAlgorithmCreateFunc Struct Reference
btCollisionAlgorithmCreateFunc Struct Reference
Used by the btCollisionDispatcher to register and create instances for btCollisionAlgorithm.
#include <btCollisionCreateFunc.h>
Public Member Functions
btCollisionAlgorithmCreateFunc ()
virtual ~btCollisionAlgorithmCreateFunc ()
virtual btCollisionAlgorithm * CreateCollisionAlgorithm (btCollisionAlgorithmConstructionInfo &, btCollisionObject *body0, btCollisionObject *body1)
Public Attributes
bool m_swapped
Detailed Description
Used by the btCollisionDispatcher to register and create instances for btCollisionAlgorithm.
Definition at line 26 of file btCollisionCreateFunc.h.
Constructor & Destructor Documentation
btCollisionAlgorithmCreateFunc::btCollisionAlgorithmCreateFunc () [inline]
Definition at line 30 of file btCollisionCreateFunc.h.
virtual btCollisionAlgorithmCreateFunc::~btCollisionAlgorithmCreateFunc () [inline, virtual]
Definition at line 34 of file btCollisionCreateFunc.h.
Referenced by btDefaultCollisionConfiguration::~btDefaultCollisionConfiguration(), and btSoftBodyRigidBodyCollisionConfiguration::~btSoftBodyRigidBodyCollisionConfiguration().
Member Function Documentation
virtual btCollisionAlgorithm* btCollisionAlgorithmCreateFunc::CreateCollisionAlgorithm (btCollisionAlgorithmConstructionInfo & , btCollisionObject * body0, btCollisionObject * body1) [inline, virtual]
Reimplemented in btBox2dBox2dCollisionAlgorithm::CreateFunc, btBoxBoxCollisionAlgorithm::CreateFunc, btCompoundCollisionAlgorithm::CreateFunc, btCompoundCollisionAlgorithm::SwappedCreateFunc, btConvex2dConvex2dAlgorithm::CreateFunc, btConvexConcaveCollisionAlgorithm::CreateFunc, btConvexConcaveCollisionAlgorithm::SwappedCreateFunc, btConvexConvexAlgorithm::CreateFunc, btConvexPlaneCollisionAlgorithm::CreateFunc, btEmptyAlgorithm::CreateFunc, CreateFunc, btSphereBoxCollisionAlgorithm::CreateFunc, btSphereSphereCollisionAlgorithm::CreateFunc, btSphereTriangleCollisionAlgorithm::CreateFunc, btGImpactCollisionAlgorithm::CreateFunc, btSoftBodyConcaveCollisionAlgorithm::CreateFunc, btSoftBodyConcaveCollisionAlgorithm::SwappedCreateFunc, btSoftRigidCollisionAlgorithm::CreateFunc, and btSoftSoftCollisionAlgorithm::CreateFunc.
Definition at line 36 of file btCollisionCreateFunc.h.
Referenced by btCollisionDispatcher::findAlgorithm().
Member Data Documentation
bool btCollisionAlgorithmCreateFunc::m_swapped
Definition at line 28 of file btCollisionCreateFunc.h.
Referenced by btDefaultCollisionConfiguration::btDefaultCollisionConfiguration(), btSoftBodyRigidBodyCollisionConfiguration::btSoftBodyRigidBodyCollisionConfiguration(), btConvexPlaneCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm(), btSphereBoxCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm(), btSphereTriangleCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm(), and btSoftRigidCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
The documentation for this struct was generated from the following file:
btCollisionCreateFunc.h