Blender: BL_BlenderDataConversion.cpp File Reference
BL_BlenderDataConversion.cpp File Reference
Converter
#include <math.h>
#include "BL_BlenderDataConversion.h"
#include "KX_BlenderGL.h"
#include "KX_BlenderScalarInterpolator.h"
#include "RAS_IPolygonMaterial.h"
#include "KX_PolygonMaterial.h"
#include "ListValue.h"
#include "IntValue.h"
#include "PHY_Pro.h"
#include "KX_Scene.h"
#include "KX_GameObject.h"
#include "RAS_FramingManager.h"
#include "RAS_MeshObject.h"
#include "KX_ConvertActuators.h"
#include "KX_ConvertControllers.h"
#include "KX_ConvertSensors.h"
#include "SCA_LogicManager.h"
#include "SCA_EventManager.h"
#include "SCA_TimeEventManager.h"
#include "KX_Light.h"
#include "KX_Camera.h"
#include "KX_EmptyObject.h"
#include "KX_FontObject.h"
#include "MT_Point3.h"
#include "MT_Transform.h"
#include "MT_MinMax.h"
#include "SCA_IInputDevice.h"
#include "RAS_TexMatrix.h"
#include "RAS_ICanvas.h"
#include "RAS_MaterialBucket.h"
#include "RAS_Polygon.h"
#include "RAS_TexVert.h"
#include "RAS_BucketManager.h"
#include "RAS_IRenderTools.h"
#include "BL_Material.h"
#include "KX_BlenderMaterial.h"
#include "BL_Texture.h"
#include "DNA_action_types.h"
#include "BKE_main.h"
#include "BKE_global.h"
#include "BKE_object.h"
#include "BL_ModifierDeformer.h"
#include "BL_ShapeDeformer.h"
#include "BL_SkinDeformer.h"
#include "BL_MeshDeformer.h"
#include "KX_SoftBodyDeformer.h"
#include "BLI_utildefines.h"
#include "BlenderWorldInfo.h"
#include "KX_KetsjiEngine.h"
#include "KX_BlenderSceneConverter.h"
#include "DNA_object_types.h"
#include "DNA_material_types.h"
#include "DNA_texture_types.h"
#include "DNA_image_types.h"
#include "DNA_lamp_types.h"
#include "DNA_group_types.h"
#include "DNA_scene_types.h"
#include "DNA_camera_types.h"
#include "DNA_property_types.h"
#include "DNA_text_types.h"
#include "DNA_sensor_types.h"
#include "DNA_controller_types.h"
#include "DNA_actuator_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_view3d_types.h"
#include "DNA_world_types.h"
#include "DNA_sound_types.h"
#include "DNA_key_types.h"
#include "DNA_armature_types.h"
#include "DNA_object_force.h"
#include "MEM_guardedalloc.h"
#include "BKE_key.h"
#include "BKE_mesh.h"
#include "BLI_math.h"
#include "BKE_scene.h"
#include "BKE_customdata.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_DerivedMesh.h"
#include "BKE_material.h"
#include "BKE_image.h"
#include "IMB_imbuf_types.h"
#include "KX_BlenderInputDevice.h"
#include "KX_ConvertProperties.h"
#include "KX_HashedPtr.h"
#include "KX_ScalarInterpolator.h"
#include "KX_IpoConvert.h"
#include "BL_System.h"
#include "SG_Node.h"
#include "SG_BBox.h"
#include "SG_Tree.h"
#include "KX_ConvertPhysicsObject.h"
#include "KX_MotionState.h"
#include "KX_SG_NodeRelationships.h"
#include "KX_SG_BoneParentNodeRelationship.h"
#include "BL_ArmatureObject.h"
#include "BL_DeformableGameObject.h"
#include "KX_NavMeshObject.h"
#include "KX_ObstacleSimulation.h"
#include "DNA_constraint_types.h"
#include "PHY_IPhysicsEnvironment.h"
#include "KX_IPhysicsController.h"
#include "PHY_DynamicTypes.h"
Classes
struct MTF_localLayer
struct parentChildLink
Defines
#define BL_CONVERTBLENDEROBJECT_SINGLE
#define CONVERT_LOGIC
Typedefs
typedef struct MTF_localLayer MTF_localLayer
Functions
static std::map< int,
SCA_IInputDevice::KX_EnumInputs > create_translate_table ()
static unsigned int KX_rgbaint2uint_new (unsigned int icol)
static unsigned int KX_Mcol2uint_new (MCol col)
static void SetDefaultLightMode (Scene *scene)
static void GetRGB (short type, MFace *mface, MCol *mmcol, Material *mat, unsigned int &c0, unsigned int &c1, unsigned int &c2, unsigned int &c3)
bool ConvertMaterial (BL_Material *material, Material *mat, MTFace *tface, const char *tfaceName, MFace *mface, MCol *mmcol, MTF_localLayer *layers, bool glslmat)
RAS_MeshObject * BL_ConvertMesh (Mesh *mesh, Object *blenderobj, KX_Scene *scene, KX_BlenderSceneConverter *converter)
static PHY_MaterialProps * CreateMaterialFromBlenderObject (struct Object *blenderobject)
static PHY_ShapeProps * CreateShapePropsFromBlenderObject (struct Object *blenderobject)
static float my_boundbox_mesh (Mesh *me, float *loc, float *size)
static void my_tex_space_mesh (Mesh *me)
static void my_get_local_bounds (Object *ob, DerivedMesh *dm, float *center, float *size)
void BL_CreateGraphicObjectNew (KX_GameObject *gameobj, const MT_Point3 &localAabbMin, const MT_Point3 &localAabbMax, KX_Scene *kxscene, bool isActive, e_PhysicsEngine physics_engine)
void BL_CreatePhysicsObjectNew (KX_GameObject *gameobj, struct Object *blenderobject, RAS_MeshObject *meshobj, KX_Scene *kxscene, int activeLayerBitInfo, e_PhysicsEngine physics_engine, KX_BlenderSceneConverter *converter, bool processCompoundChildren)
static KX_LightObject * gamelight_from_blamp (Object *ob, Lamp *la, unsigned int layerflag, KX_Scene *kxscene, RAS_IRenderTools *rendertools, KX_BlenderSceneConverter *converter)
static KX_Camera * gamecamera_from_bcamera (Object *ob, KX_Scene *kxscene, KX_BlenderSceneConverter *converter)
static KX_GameObject * gameobject_from_blenderobject (Object *ob, KX_Scene *kxscene, RAS_IRenderTools *rendertools, KX_BlenderSceneConverter *converter)
bPoseChannel * get_active_posechannel2 (Object *ob)
ListBase * get_active_constraints2 (Object *ob)
void RBJconstraints (Object *ob)
KX_IPhysicsController * getPhId (CListValue *sumolist, STR_String busc)
KX_GameObject * getGameOb (STR_String busc, CListValue *sumolist)
static void bl_ConvertBlenderObject_Single (KX_BlenderSceneConverter *converter, Scene *blenderscene, Object *blenderobject, vector< MT_Vector3 > &inivel, vector< MT_Vector3 > &iniang, vector< parentChildLink > &vec_parent_child, CListValue *logicbrick_conversionlist, CListValue *objectlist, CListValue *inactivelist, CListValue *sumolist, KX_Scene *kxscene, KX_GameObject *gameobj, SCA_LogicManager *logicmgr, SCA_TimeEventManager *timemgr, bool isInActiveLayer)
void BL_ConvertBlenderObjects (struct Main *maggie, KX_Scene *kxscene, KX_KetsjiEngine *ketsjiEngine, e_PhysicsEngine physics_engine, RAS_IRenderTools *rendertools, RAS_ICanvas *canvas, KX_BlenderSceneConverter *converter, bool alwaysUseExpandFraming)
SCA_IInputDevice::KX_EnumInputs ConvertKeyCode (int key_code)
Variables
Material defmaterial
static bool default_light_mode = 0
static std::map< int,
SCA_IInputDevice::KX_EnumInputs > gReverseKeyTranslateTable = create_translate_table()
Detailed Description
Definition in file BL_BlenderDataConversion.cpp.
Define Documentation
#define BL_CONVERTBLENDEROBJECT_SINGLE
Value:
bl_ConvertBlenderObject_Single(converter,                          \
                                   blenderscene, blenderobject,        \
                                   inivel, iniang,                     \
                                   vec_parent_child,                   \
                                   logicbrick_conversionlist,          \
                                   objectlist, inactivelist, sumolist, \
                                   kxscene, gameobj,                   \
                                   logicmgr, timemgr,                  \
                                   isInActiveLayer                     \
                                   )
Referenced by BL_ConvertBlenderObjects().
#define CONVERT_LOGIC
Typedef Documentation
typedef struct MTF_localLayer MTF_localLayer
Function Documentation
static void bl_ConvertBlenderObject_Single (KX_BlenderSceneConverter * converter, Scene * blenderscene, Object * blenderobject, vector< MT_Vector3 > & inivel, vector< MT_Vector3 > & iniang, vector< parentChildLink > & vec_parent_child, CListValue * logicbrick_conversionlist, CListValue * objectlist, CListValue * inactivelist, CListValue * sumolist, KX_Scene * kxscene, KX_GameObject * gameobj, SCA_LogicManager * logicmgr, SCA_TimeEventManager * timemgr, bool isInActiveLayer) [static]
Definition at line 2165 of file BL_BlenderDataConversion.cpp.
References CListValue::Add(), SG_Node::AddChild(), KX_ISceneConverter::addInitFromFrame, KX_GameObject::AddMeshUser(), CValue::AddRef(), BL_ConvertMaterialIpos(), BL_ConvertProperties(), RenderData::cfra, Object::dloc, RenderData::frs_sec, RenderData::frs_sec_base, KX_GameObject::GetMesh(), KX_GameObject::GetMeshCount(), KX_GameObject::GetName(), RAS_MeshObject::GetName(), KX_GameObject::GetSGNode(), i, Object::id, KX_Scene::KX_ScenegraphRescheduleFunc(), KX_Scene::KX_ScenegraphUpdateFunc(), Object::loc, parentChildLink::m_blenderchild, parentChildLink::m_gamechildnode, MT_fuzzyZero(), ID::name, KX_NormalParentRelation::New(), KX_GameObject::NodeGetWorldOrientation(), KX_GameObject::NodeGetWorldPosition(), KX_GameObject::NodeSetLocalOrientation(), KX_GameObject::NodeSetLocalPosition(), KX_GameObject::NodeSetLocalScale(), KX_GameObject::NodeUpdateGS(), NULL, Object::parent, Object::parentinv, Scene::r, SCA_LogicManager::RegisterGameMeshName(), SCA_LogicManager::RegisterGameObj(), KX_BlenderSceneConverter::RegisterGameObject(), SCA_LogicManager::RegisterGameObjectName(), Object::rot, MT_Vector3::scale(), SG_Spatial::SetLocalOrientation(), SG_Spatial::SetLocalPosition(), SG_Spatial::SetLocalScale(), KX_GameObject::SetName(), SG_Spatial::SetParentRelation(), RenderData::sfra, and Object::size.
void BL_ConvertBlenderObjects (struct Main * maggie, KX_Scene * kxscene, KX_KetsjiEngine * ketsjiEngine, e_PhysicsEngine physics_engine, RAS_IRenderTools * rendertools, RAS_ICanvas * canvas, KX_BlenderSceneConverter * converter, bool alwaysUseExpandFraming)
Definition at line 2313 of file BL_BlenderDataConversion.cpp.
References Main::action, GameData::activityBoxRadius, CListValue::Add(), KX_ISceneConverter::addInitFromFrame, KX_ObstacleSimulation::AddObstacleForObj(), KX_ObstacleSimulation::AddObstaclesForNavMesh(), CValue::AddRef(), assert, bRigidBodyJointConstraint::axX, bRigidBodyJointConstraint::axY, bRigidBodyJointConstraint::axZ, SG_Spatial::BBox(), BL_ConvertActuators(), BL_CONVERTBLENDEROBJECT_SINGLE, BL_ConvertControllers(), BL_ConvertSensors(), BL_CreateGraphicObjectNew(), BL_CreatePhysicsObjectNew(), KX_NavMeshObject::BuildNavMesh(), Scene::camera, bRigidBodyJointConstraint::child, GameFraming::col, CONSTRAINT_OFF, CONSTRAINT_TYPE_RIGIDBODYJOINT, PHY_IPhysicsEnvironment::createConstraint(), Object::data, bConstraint::data, SG_Node::DisconnectFromParent(), distance(), Object::dup_group, KX_Scene::DupliGroupRecurse(), Mesh::dvert, RAS_FrameSettings::e_frame_bars, RAS_FrameSettings::e_frame_extend, RAS_FrameSettings::e_frame_scale, KX_BlenderSceneConverter::FindGameObject(), ListBase::first, bConstraint::flag, bRigidBodyJointConstraint::flag, GameData::framing, Object::gameflag, gameobject_from_blenderobject(), get_active_constraints2(), get_named_bone(), KX_Scene::GetActiveCamera(), KX_GameObject::GetBlenderObject(), KX_Scene::GetBlenderScene(), KX_Scene::GetBucketManager(), KX_Camera::GetCameraFar(), KX_Camera::GetCameraNear(), KX_GameObject::GetChildrenRecursive(), MT_Matrix3x3::getColumn(), CListValue::GetCount(), KX_Scene::GetDbvtCulling(), KX_GameObject::GetDeformer(), BL_DeformableGameObject::GetDeformer(), getGameOb(), SCA_IObject::GetGameObjectType(), RAS_ICanvas::GetHeight(), KX_Scene::GetInactiveList(), KX_GameObject::GetLayer(), KX_Scene::GetLogicManager(), KX_GameObject::GetMesh(), KX_GameObject::GetMeshCount(), SG_BBox::getmm(), KX_Scene::GetObjectList(), KX_Scene::GetObstacleSimulation(), KX_GameObject::GetOccluder(), KX_GameObject::GetPhysicsController(), KX_Scene::GetPhysicsEnvironment(), KX_Scene::GetRootParentList(), KX_GameObject::GetSGNode(), SG_Node::GetSGParent(), KX_Scene::GetTimeEventManager(), KX_IPhysicsController::GetUserData(), CListValue::GetValue(), RAS_ICanvas::GetWidth(), Scene::gm, Group::gobject, GameData::gravity, BL_ModifierDeformer::HasArmatureDeformer(), i, Object::id, bAction::id, MT_Transform::Identity(), if(), Object::init_state, KX_GameObject::IsDupliGroup(), KX_GameObject::IsDynamic(), Object::lay, Scene::lay, bRigidBodyJointConstraint::maxLimit, bRigidBodyJointConstraint::minLimit, GameData::mode, Main::name, ID::name, KX_BoneParentRelation::New(), KX_SlowParentRelation::New(), KX_VertexParentRelation::New(), GroupObject::next, bConstraint::next, ID::next, KX_GameObject::NodeUpdateGS(), NULL, GroupObject::ob, OB_ARMATURE, OB_CAMERA, OB_HASOBSTACLE, OB_MESH, OB_NAVMESH, SCA_IObject::OBJ_ARMATURE, Base::object, GameData::occlusionRes, RAS_BucketManager::OptimizeBuckets(), PARBONE, PARCURVE, Object::parent, PARKEY, PAROBJECT, PARSKEL, PARSLOW, Object::parsubstr, Object::partype, PARVERT1, PARVERT3, PHY_CONE_TWIST_CONSTRAINT, PHY_GENERIC_6DOF_CONSTRAINT, PHY_LINEHINGE_CONSTRAINT, GameData::physubstep, bRigidBodyJointConstraint::pivX, bRigidBodyJointConstraint::pivY, bRigidBodyJointConstraint::pivZ, Scene::r, SCA_LogicManager::RegisterActionName(), KX_BlenderSceneConverter::RegisterWorldInfo(), CValue::Release(), KX_Scene::RemoveObject(), CListValue::RemoveValue(), SCA_IObject::ResetState(), SCE_GAMEFRAMING_BARS, SCE_GAMEFRAMING_EXTEND, CListValue::SearchValue(), KX_Scene::SetActiveCamera(), KX_Scene::SetActivityCulling(), KX_Scene::SetActivityCullingRadius(), KX_GameObject::setAngularVelocity(), PHY_IPhysicsEnvironment::setConstraintParam(), KX_Scene::SetDbvtCulling(), KX_Scene::SetDbvtOcclusionRes(), SetDefaultLightMode(), KX_Scene::SetFramingType(), KX_Scene::SetGravity(), SCA_IObject::SetInitState(), KX_GameObject::setLinearVelocity(), SETLOOPER, PHY_IPhysicsEnvironment::setNumTimeSubSteps(), KX_GameObject::SetVisible(), KX_Scene::SetWorldInfo(), Object::sf, Object::state, bRigidBodyJointConstraint::tar, bConstraint::type, Object::type, bRigidBodyJointConstraint::type, GameFraming::type, KX_BlenderSceneConverter::UnregisterGameObject(), RAS_Deformer::UpdateBuckets(), WO_ACTIVITY_CULLING, WO_DBVT_CULLING, Scene::world, MT_Tuple3::x(), RenderData::xasp, RenderData::xsch, MT_Tuple3::y(), RenderData::yasp, RenderData::ysch, and MT_Tuple3::z().
Referenced by KX_BlenderSceneConverter::ConvertScene().
RAS_MeshObject* BL_ConvertMesh (Mesh * mesh, Object * blenderobj, KX_Scene * scene, KX_BlenderSceneConverter * converter)
Definition at line 906 of file BL_BlenderDataConversion.cpp.
References RAS_MeshObject::AddPolygon(), RAS_MeshObject::AddVertex(), Material::alpha, GameSettings::alpha_blend, assert, Material::b, BKE_image_has_alpha(), CD_MCOL, CD_MTFACE, CD_TANGENT, CDDM_from_mesh(), MVert::co, ConvertMaterial(), CustomDataLayer::data, default_light_mode, defmaterial, DM_add_tangent_layer(), DM_ensure_tessface(), ELEM3, Material::emit, RAS_MeshObject::EndConversion(), MTF_localLayer::face, DerivedMesh::faceData, KX_Scene::FindBucket(), KX_BlenderSceneConverter::FindGameMesh(), MFace::flag, GameSettings::flag, Material::g, Material::game, GEMAT_ADD, GEMAT_ALPHA, GEMAT_ALPHA_SORT, GEMAT_BACKCULL, GEMAT_INVISIBLE, GEMAT_NOPHYSICS, GEMAT_SOLID, GEMAT_TEXT, BL_Material::GetConversionRGB(), BL_Material::GetConversionUV(), BL_Material::GetConversionUV2(), RAS_MeshObject::GetFirstMaterial(), KX_BlenderSceneConverter::GetGLSLMaterials(), RAS_MeshObject::GetLastMaterial(), KX_BlenderSceneConverter::GetMaterials(), DerivedMesh::getNumTessFaces, DerivedMesh::getNumVerts, RAS_MaterialBucket::GetPolyMaterial(), DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertArray, give_current_material(), Material::har, i, Mesh::id, Image::id, KX_BlenderMaterial::Initialize(), KX_PolygonMaterial::Initialize(), KX_Mcol2uint_new(), KX_rgbaint2uint_new(), L, Object::lay, CustomData::layers, RAS_IPolyMaterial::m_diffuse, RAS_MeshObject::m_sharedvertex_map, RAS_IPolyMaterial::m_shininess, RAS_IPolyMaterial::m_specular, MA_FACETEXTURE, MA_SHLESS, Mesh::mat, MFace::mat_nr, MAX_MTFACE, ME_SMOOTH, Material::mode, MTF_localLayer::name, ID::name, CustomDataLayer::name, MVert::no, normal_quad_v3(), normal_short_to_float_v3(), normal_tri_v3(), NULL, Material::r, Material::ref, KX_BlenderSceneConverter::RegisterBlenderMaterial(), KX_BlenderSceneConverter::RegisterGameMesh(), KX_BlenderSceneConverter::RegisterPolyMaterial(), DerivedMesh::release, RAS_Polygon::SetCollider(), RAS_MeshObject::SetName(), RAS_Polygon::SetTwoside(), MT_Tuple3::setValue(), MT_Tuple2::setValue(), RAS_Polygon::SetVisible(), Material::spec, Material::specb, Material::specg, Material::specr, MTFace::tile, CustomData::totlayer, MTFace::tpage, CustomDataLayer::type, MTFace::uv, MFace::v1, MFace::v2, MFace::v3, MFace::v4, Image::xrep, and Image::yrep.
Referenced by BL_ConvertActuators(), KX_BlenderSceneConverter::ConvertMeshSpecial(), gameobject_from_blenderobject(), and KX_BlenderSceneConverter::LinkBlendFile().
void BL_CreateGraphicObjectNew (KX_GameObject * gameobj, const MT_Point3 & localAabbMin, const MT_Point3 & localAabbMax, KX_Scene * kxscene, bool isActive, e_PhysicsEngine physics_engine)
Definition at line 1536 of file BL_BlenderDataConversion.cpp.
References CcdPhysicsEnvironment::addCcdGraphicController(), assert, KX_GameObject::getClientInfo(), KX_GameObject::GetDeformer(), KX_GameObject::GetMeshCount(), KX_Scene::GetPhysicsEnvironment(), KX_GameObject::GetSGNode(), KX_GameObject::GetVisible(), KX_GameObject::SetGraphicController(), RAS_Deformer::UpdateBuckets(), and UseBullet.
Referenced by BL_ConvertBlenderObjects().
void BL_CreatePhysicsObjectNew (KX_GameObject * gameobj, struct Object * blenderobject, RAS_MeshObject * meshobj, KX_Scene * kxscene, int activeLayerBitInfo, e_PhysicsEngine physics_engine, KX_BlenderSceneConverter * converter, bool processCompoundChildren)
contact processing threshold is only for rigid bodies and static geometry, not 'dynamic'
for game soft bodies
Definition at line 1575 of file BL_BlenderDataConversion.cpp.
References BulletSoftBody::angStiff, Object::bb, KX_ObjectProperties::box, Object::bsoft, KX_ObjectProperties::c, BulletSoftBody::citerations, Object::collision_boundtype, BulletSoftBody::collisionflags, CreateMaterialFromBlenderObject(), CreateShapePropsFromBlenderObject(), BulletSoftBody::diterations, KX_BlenderSceneConverter::FindGameObject(), BulletSoftBody::flag, Object::gameflag, Object::gameflag2, KX_GameObject::GetDeformer(), RAS_Deformer::GetPhysicsMesh(), Object::inertia, BulletSoftBody::kAHR, BulletSoftBody::kCHR, BulletSoftBody::kDF, BulletSoftBody::kDG, BulletSoftBody::kDP, BulletSoftBody::kKHR, BulletSoftBody::kLF, BulletSoftBody::kMT, BulletSoftBody::kPR, BulletSoftBody::kSHR, BulletSoftBody::kSK_SPLT_CL, BulletSoftBody::kSKHR_CL, BulletSoftBody::kSR_SPLT_CL, BulletSoftBody::kSRHR_CL, BulletSoftBody::kSS_SPLT_CL, BulletSoftBody::kSSHR_CL, BulletSoftBody::kVC, BulletSoftBody::kVCF, KX_BOUNDBOX, KX_BOUNDCAPSULE, KX_BOUNDCONE, KX_BOUNDCYLINDER, KX_BOUNDMESH, KX_BOUNDPOLYTOPE, KX_BOUNDSPHERE, Object::lay, BulletSoftBody::linStiff, KX_ObjectProperties::m_angular_rigidbody, KX_ObjectProperties::m_boundclass, KX_ObjectProperties::m_boundobject, KX_BoxBounds::m_center, KX_ObjectProperties::m_concave, KX_ObjectProperties::m_contactProcessingThreshold, Object::m_contactProcessingThreshold, KX_ObjectProperties::m_disableSleeping, KX_ObjectProperties::m_dyna, KX_ObjectProperties::m_dynamic_parent, KX_BoxBounds::m_extends, KX_ObjectProperties::m_gamesoftFlag, KX_ObjectProperties::m_ghost, KX_ObjectProperties::m_hasCompoundChildren, KX_CBounds::m_height, KX_ObjectProperties::m_in_active_layer, KX_ObjectProperties::m_isactor, KX_ObjectProperties::m_isCompoundChild, KX_ObjectProperties::m_isdeformable, KX_ObjectProperties::m_lockXaxis, KX_ObjectProperties::m_lockXRotaxis, KX_ObjectProperties::m_lockYaxis, KX_ObjectProperties::m_lockYRotaxis, KX_ObjectProperties::m_lockZaxis, KX_ObjectProperties::m_lockZRotaxis, KX_ObjectProperties::m_margin, PHY_ShapeProps::m_mass, KX_CBounds::m_radius, KX_ObjectProperties::m_radius, KX_ObjectProperties::m_sensor, KX_ObjectProperties::m_soft_angStiff, KX_ObjectProperties::m_soft_citerations, KX_ObjectProperties::m_soft_collisionflags, KX_ObjectProperties::m_soft_diterations, KX_ObjectProperties::m_soft_kAHR, KX_ObjectProperties::m_soft_kCHR, KX_ObjectProperties::m_soft_kDF, KX_ObjectProperties::m_soft_kDG, KX_ObjectProperties::m_soft_kDP, KX_ObjectProperties::m_soft_kKHR, KX_ObjectProperties::m_soft_kLF, KX_ObjectProperties::m_soft_kMT, KX_ObjectProperties::m_soft_kPR, KX_ObjectProperties::m_soft_kSHR, KX_ObjectProperties::m_soft_kSK_SPLT_CL, KX_ObjectProperties::m_soft_kSKHR_CL, KX_ObjectProperties::m_soft_kSR_SPLT_CL, KX_ObjectProperties::m_soft_kSRHR_CL, KX_ObjectProperties::m_soft_kSS_SPLT_CL, KX_ObjectProperties::m_soft_kSSHR_CL, KX_ObjectProperties::m_soft_kVC, KX_ObjectProperties::m_soft_kVCF, KX_ObjectProperties::m_soft_linStiff, KX_ObjectProperties::m_soft_numclusteriterations, KX_ObjectProperties::m_soft_piterations, KX_ObjectProperties::m_soft_viterations, KX_ObjectProperties::m_soft_volume, KX_ObjectProperties::m_soft_welding, KX_ObjectProperties::m_softbody, Object::margin, BulletSoftBody::margin, MT_max(), my_get_local_bounds(), DerivedMesh::needsFree, NULL, BulletSoftBody::numclusteriterations, OB_ACTOR, OB_BOUND_BOX, OB_BOUND_CAPSULE, OB_BOUND_CONE, OB_BOUND_CONVEX_HULL, OB_BOUND_CYLINDER, OB_BOUND_SPHERE, OB_BOUND_TRIANGLE_MESH, OB_BOUNDS, OB_BSB_AERO_VPOINT, OB_BSB_BENDING_CONSTRAINTS, OB_BSB_COL_SDF_RS, OB_BSB_COL_VF_SS, OB_BSB_SHAPE_MATCHING, OB_CHILD, OB_COLLISION, OB_COLLISION_RESPONSE, OB_DYNAMIC, OB_GHOST, OB_LOCK_RIGID_BODY_X_AXIS, OB_LOCK_RIGID_BODY_X_ROT_AXIS, OB_LOCK_RIGID_BODY_Y_AXIS, OB_LOCK_RIGID_BODY_Y_ROT_AXIS, OB_LOCK_RIGID_BODY_Z_AXIS, OB_LOCK_RIGID_BODY_Z_ROT_AXIS, OB_MESH, OB_RIGID_BODY, OB_SENSOR, OB_SOFT_BODY, Object::parent, BulletSoftBody::piterations, DerivedMesh::release, Object::type, UseBullet, UseNone, BulletSoftBody::viterations, and BulletSoftBody::volume.
Referenced by BL_ConvertBlenderObjects().
SCA_IInputDevice::KX_EnumInputs ConvertKeyCode (int key_code)
Definition at line 2956 of file BL_BlenderDataConversion.cpp.
References gReverseKeyTranslateTable.
Referenced by BL_ConvertSensors(), GPG_Application::initEngine(), StartKetsjiShell(), and BL_BlenderInputDevice::ToNative().
bool ConvertMaterial (BL_Material * material, Material * mat, MTFace * tface, const char * tfaceName, MFace * mface, MCol * mmcol, MTF_localLayer * layers, bool glslmat)
--------------------------------
--------------------------------
Definition at line 498 of file BL_BlenderDataConversion.cpp.
References Material::alpha, ALPHA, BL_Material::alpha, GameSettings::alpha_blend, BL_Material::alphablend, BL_Material::amb, Material::amb, Material::b, BKE_animdata_from_id(), BKE_image_has_alpha(), BLEND_ADD, BLEND_MIX, BL_Material::blend_mode, BLEND_MUL, BLEND_SCR, BLEND_SUB, MTex::blendtype, CALCALPHA, CAST_SHADOW, MTex::colfac, BL_Material::color_blend, EnvMap::cube, BL_Material::cubemap, DEFAULT_BLENDER, DISABLE, ELEM3, BL_Material::emit, Material::emit, Tex::env, ENV_LOAD, MTF_localLayer::face, Tex::flag, GameSettings::flag, BL_Material::flag, Image::flag, Material::g, Material::game, GEMAT_ADD, GEMAT_ALPHA, GEMAT_ALPHA_SORT, GEMAT_BACKCULL, GEMAT_CLIP, GEMAT_SOLID, GEMAT_TEXT, getImageFromMaterial(), getNumTexChannels(), GetRGB(), BL_Material::glslmat, GREATERTHAN2, Material::har, BL_Material::hard, i, Material::id, Object::id, Tex::id, Image::id, BL_Material::IdMode, if(), EnvMap::ima, Tex::ima, IMA_REFLECT, Tex::imaflag, BL_Material::img, BL_Material::Initialize(), STR_String::IsEmpty(), KX_rgbaint2uint_new(), MA_FACETEXTURE, MA_SHADBUF, MA_SHLESS, MA_TRANSP, MA_TYPE_WIRE, MA_VERTEXCOLP, MA_ZTRANSP, MAP_ALPHA, BL_Mapping::mapping, BL_Material::mapping, MTex::mapto, MFace::mat_nr, BL_Material::matcolor, BL_Material::material, Material::material_type, BL_Material::materialindex, BL_Material::matname, MAX_MTFACE, MAXTEX, MIPMAP, Material::mode, MTEX_ADD, MTEX_BLEND, MTEX_MUL, MTEX_NEGATIVE, MTEX_SCREEN, MTEX_SUB, BL_Material::mtexname, MTF_localLayer::name, ID::name, NULL, BL_Material::num_enabled, BL_Mapping::objconame, MTex::object, BL_Mapping::offsets, MTex::ofs, ONETEX, BL_Mapping::projplane, MTex::projx, MTex::projy, MTex::projz, Material::r, BL_Material::ras_mode, STR_String::ReadPtr(), BL_Material::ref, Material::ref, BL_Mapping::scale, BL_Material::SetConversionRGB(), BL_Material::SetConversionUV(), BL_Material::SetConversionUV2(), BL_Material::SetUsers(), MT_Tuple2::setValue(), MTex::size, Material::spec, BL_Material::spec_f, Material::specb, BL_Material::speccolor, Material::specg, Material::specr, BL_Texture::SplitEnvMap(), EnvMap::stype, MTex::tex, TEX_CALCALPHA, TEX_ENVMAP, TEX_IMAGE, TEX_MIPMAP, TEX_NEGALPHA, TEX_USEALPHA, TEXALPHA, MTex::texco, TEXCO_GLOB, TEXCO_NORM, TEXCO_OBJECT, TEXCO_ORCO, TEXCO_REFL, TEXCO_TANGENT, TEXCO_UV, TEXFACE, MTex::texflag, BL_Material::texname, TEXNEG, BL_Material::tface, MTFace::tile, BL_Material::tile, MTFace::tpage, TWOSIDED, Tex::type, ID::us, USE_LIGHT, USEALPHA, USECUSTOMUV, USEENV, USENEGALPHA, USENORM, USEOBJ, USEORCO, USEREFL, USETANG, USEUV, MTFace::uv, BL_Mapping::uvCoName, MTex::uvname, MFace::v4, WIRE, and ZSORT.
Referenced by BL_ConvertMesh().
static std::map<int, SCA_IInputDevice::KX_EnumInputs> create_translate_table () [static]
Definition at line 200 of file BL_BlenderDataConversion.cpp.
References ACCENTGRAVEKEY, AKEY, BACKSLASHKEY, BACKSPACEKEY, BKEY, CAPSLOCKKEY, CKEY, COMMAKEY, DELKEY, DKEY, DOWNARROWKEY, EIGHTKEY, EKEY, ENDKEY, EQUALKEY, ESCKEY, F10KEY, F11KEY, F12KEY, F13KEY, F14KEY, F15KEY, F16KEY, F17KEY, F18KEY, F19KEY, F1KEY, F2KEY, F3KEY, F4KEY, F5KEY, F6KEY, F7KEY, F8KEY, F9KEY, FIVEKEY, FKEY, FOURKEY, GKEY, HKEY, HOMEKEY, IKEY, INPUTCHANGE, INSERTKEY, JKEY, KKEY, SCA_IInputDevice::KX_ACCENTGRAVEKEY, SCA_IInputDevice::KX_AKEY, SCA_IInputDevice::KX_BACKSLASHKEY, SCA_IInputDevice::KX_BACKSPACEKEY, SCA_IInputDevice::KX_BKEY, SCA_IInputDevice::KX_CAPSLOCKKEY, SCA_IInputDevice::KX_CKEY, SCA_IInputDevice::KX_COMMAKEY, SCA_IInputDevice::KX_DELKEY, SCA_IInputDevice::KX_DKEY, SCA_IInputDevice::KX_DOWNARROWKEY, SCA_IInputDevice::KX_EIGHTKEY, SCA_IInputDevice::KX_EKEY, SCA_IInputDevice::KX_ENDKEY, SCA_IInputDevice::KX_EQUALKEY, SCA_IInputDevice::KX_ESCKEY, SCA_IInputDevice::KX_F10KEY, SCA_IInputDevice::KX_F11KEY, SCA_IInputDevice::KX_F12KEY, SCA_IInputDevice::KX_F13KEY, SCA_IInputDevice::KX_F14KEY, SCA_IInputDevice::KX_F15KEY, SCA_IInputDevice::KX_F16KEY, SCA_IInputDevice::KX_F17KEY, SCA_IInputDevice::KX_F18KEY, SCA_IInputDevice::KX_F19KEY, SCA_IInputDevice::KX_F1KEY, SCA_IInputDevice::KX_F2KEY, SCA_IInputDevice::KX_F3KEY, SCA_IInputDevice::KX_F4KEY, SCA_IInputDevice::KX_F5KEY, SCA_IInputDevice::KX_F6KEY, SCA_IInputDevice::KX_F7KEY, SCA_IInputDevice::KX_F8KEY, SCA_IInputDevice::KX_F9KEY, SCA_IInputDevice::KX_FIVEKEY, SCA_IInputDevice::KX_FKEY, SCA_IInputDevice::KX_FOURKEY, SCA_IInputDevice::KX_GKEY, SCA_IInputDevice::KX_HKEY, SCA_IInputDevice::KX_HOMEKEY, SCA_IInputDevice::KX_IKEY, SCA_IInputDevice::KX_INPUTCHANGE, SCA_IInputDevice::KX_INSERTKEY, SCA_IInputDevice::KX_JKEY, SCA_IInputDevice::KX_KEYBD, SCA_IInputDevice::KX_KKEY, SCA_IInputDevice::KX_LEFTALTKEY, SCA_IInputDevice::KX_LEFTARROWKEY, SCA_IInputDevice::KX_LEFTBRACKETKEY, SCA_IInputDevice::KX_LEFTCTRLKEY, SCA_IInputDevice::KX_LEFTMOUSE, SCA_IInputDevice::KX_LEFTSHIFTKEY, SCA_IInputDevice::KX_LINEFEEDKEY, SCA_IInputDevice::KX_LKEY, SCA_IInputDevice::KX_MIDDLEMOUSE, SCA_IInputDevice::KX_MINUSKEY, SCA_IInputDevice::KX_MKEY, SCA_IInputDevice::KX_MOUSEX, SCA_IInputDevice::KX_MOUSEY, SCA_IInputDevice::KX_NINEKEY, SCA_IInputDevice::KX_NKEY, SCA_IInputDevice::KX_OKEY, SCA_IInputDevice::KX_ONEKEY, SCA_IInputDevice::KX_PAD0, SCA_IInputDevice::KX_PAD1, SCA_IInputDevice::KX_PAD2, SCA_IInputDevice::KX_PAD3, SCA_IInputDevice::KX_PAD4, SCA_IInputDevice::KX_PAD5, SCA_IInputDevice::KX_PAD6, SCA_IInputDevice::KX_PAD7, SCA_IInputDevice::KX_PAD8, SCA_IInputDevice::KX_PAD9, SCA_IInputDevice::KX_PADASTERKEY, SCA_IInputDevice::KX_PADENTER, SCA_IInputDevice::KX_PADMINUS, SCA_IInputDevice::KX_PADPERIOD, SCA_IInputDevice::KX_PADPLUSKEY, SCA_IInputDevice::KX_PADSLASHKEY, SCA_IInputDevice::KX_PAGEDOWNKEY, SCA_IInputDevice::KX_PAGEUPKEY, SCA_IInputDevice::KX_PAUSEKEY, SCA_IInputDevice::KX_PERIODKEY, SCA_IInputDevice::KX_PKEY, SCA_IInputDevice::KX_Q_FIRSTTIME, SCA_IInputDevice::KX_QFULL, SCA_IInputDevice::KX_QKEY, SCA_IInputDevice::KX_QUOTEKEY, SCA_IInputDevice::KX_RAWKEYBD, SCA_IInputDevice::KX_REDRAW, SCA_IInputDevice::KX_RETKEY, SCA_IInputDevice::KX_RIGHTALTKEY, SCA_IInputDevice::KX_RIGHTARROWKEY, SCA_IInputDevice::KX_RIGHTBRACKETKEY, SCA_IInputDevice::KX_RIGHTCTRLKEY, SCA_IInputDevice::KX_RIGHTMOUSE, SCA_IInputDevice::KX_RIGHTSHIFTKEY, SCA_IInputDevice::KX_RKEY, SCA_IInputDevice::KX_SEMICOLONKEY, SCA_IInputDevice::KX_SEVENKEY, SCA_IInputDevice::KX_SIXKEY, SCA_IInputDevice::KX_SKEY, SCA_IInputDevice::KX_SLASHKEY, SCA_IInputDevice::KX_SPACEKEY, SCA_IInputDevice::KX_TABKEY, SCA_IInputDevice::KX_THREEKEY, SCA_IInputDevice::KX_TIMER0, SCA_IInputDevice::KX_TIMER1, SCA_IInputDevice::KX_TIMER2, SCA_IInputDevice::KX_TKEY, SCA_IInputDevice::KX_TWOKEY, SCA_IInputDevice::KX_UKEY, SCA_IInputDevice::KX_UPARROWKEY, SCA_IInputDevice::KX_VKEY, SCA_IInputDevice::KX_WHEELDOWNMOUSE, SCA_IInputDevice::KX_WHEELUPMOUSE, SCA_IInputDevice::KX_WINCLOSE, SCA_IInputDevice::KX_WINFREEZE, SCA_IInputDevice::KX_WINQUIT, SCA_IInputDevice::KX_WINTHAW, SCA_IInputDevice::KX_WKEY, SCA_IInputDevice::KX_XKEY, SCA_IInputDevice::KX_YKEY, SCA_IInputDevice::KX_ZEROKEY, SCA_IInputDevice::KX_ZKEY, LEFTALTKEY, LEFTARROWKEY, LEFTBRACKETKEY, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, LINEFEEDKEY, LKEY, MIDDLEMOUSE, MINUSKEY, MKEY, MOUSEX, MOUSEY, NINEKEY, NKEY, OKEY, ONEKEY, PAD0, PAD1, PAD2, PAD3, PAD4, PAD5, PAD6, PAD7, PAD8, PAD9, PADASTERKEY, PADENTER, PADMINUS, PADPERIOD, PADPLUSKEY, PADSLASHKEY, PAGEDOWNKEY, PAGEUPKEY, PAUSEKEY, PERIODKEY, PKEY, QKEY, QUOTEKEY, RETKEY, RIGHTALTKEY, RIGHTARROWKEY, RIGHTBRACKETKEY, RIGHTCTRLKEY, RIGHTMOUSE, RIGHTSHIFTKEY, RKEY, SEMICOLONKEY, SEVENKEY, SIXKEY, SKEY, SLASHKEY, SPACEKEY, TABKEY, THREEKEY, TIMER0, TIMER1, TIMER2, TKEY, TWOKEY, UKEY, UPARROWKEY, VKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, WKEY, XKEY, YKEY, ZEROKEY, and ZKEY.
static PHY_MaterialProps* CreateMaterialFromBlenderObject (struct Object * blenderobject) [static]
Definition at line 1284 of file BL_BlenderDataConversion.cpp.
References Material::dynamode, Material::fh, Material::fhdist, Material::friction, give_current_material(), PHY_MaterialProps::m_fh_damping, PHY_MaterialProps::m_fh_distance, PHY_MaterialProps::m_fh_normal, PHY_MaterialProps::m_fh_spring, PHY_MaterialProps::m_friction, PHY_MaterialProps::m_restitution, MA_FH_NOR, MT_assert, reflect(), Material::reflect, and Material::xyfrict.
Referenced by BL_CreatePhysicsObjectNew().
static PHY_ShapeProps* CreateShapePropsFromBlenderObject (struct Object * blenderobject) [static]
Definition at line 1317 of file BL_BlenderDataConversion.cpp.
References Object::anisotropicFriction, Object::damping, Object::formfactor, Object::gameflag, PHY_ShapeProps::m_ang_drag, PHY_ShapeProps::m_clamp_vel_max, PHY_ShapeProps::m_clamp_vel_min, PHY_ShapeProps::m_do_anisotropic, PHY_ShapeProps::m_do_fh, PHY_ShapeProps::m_do_rot_fh, PHY_ShapeProps::m_friction_scaling, PHY_ShapeProps::m_inertia, PHY_ShapeProps::m_lin_drag, PHY_ShapeProps::m_mass, Object::mass, Object::max_vel, Object::min_vel, MT_assert, OB_ANISOTROPIC_FRICTION, OB_DO_FH, OB_ROT_FH, and Object::rdamping.
Referenced by BL_CreatePhysicsObjectNew().
static KX_Camera* gamecamera_from_bcamera (Object * ob, KX_Scene * kxscene, KX_BlenderSceneConverter * converter) [static]
Definition at line 1903 of file BL_BlenderDataConversion.cpp.
References CAM_PERSP, Camera::clipend, Camera::clipsta, Object::data, Camera::id, Camera::lens, KX_Scene::m_callbacks, ID::name, Camera::ortho_scale, Camera::sensor_fit, Camera::sensor_x, Camera::sensor_y, KX_GameObject::SetName(), Camera::type, and Camera::YF_dofdist.
Referenced by gameobject_from_blenderobject().
static KX_LightObject* gamelight_from_blamp (Object * ob, Lamp * la, unsigned int layerflag, KX_Scene * kxscene, RAS_IRenderTools * rendertools, KX_BlenderSceneConverter * converter) [static]
Definition at line 1858 of file BL_BlenderDataConversion.cpp.
References Lamp::att1, Lamp::att2, Lamp::b, Lamp::dist, Lamp::energy, Lamp::g, KX_BlenderSceneConverter::GetGLSLMaterials(), LA_NEG, LA_NO_DIFF, LA_NO_SPEC, LA_QUAD, LA_SPOT, LA_SUN, RAS_LightObject::LIGHT_NORMAL, RAS_LightObject::LIGHT_SPOT, RAS_LightObject::LIGHT_SUN, RAS_LightObject::m_att1, RAS_LightObject::m_att2, RAS_LightObject::m_blue, KX_Scene::m_callbacks, RAS_LightObject::m_distance, RAS_LightObject::m_energy, RAS_LightObject::m_green, RAS_LightObject::m_layer, RAS_LightObject::m_nodiffuse, RAS_LightObject::m_nospecular, RAS_LightObject::m_red, RAS_LightObject::m_spotblend, RAS_LightObject::m_spotsize, RAS_LightObject::m_type, Lamp::mode, Lamp::r, Lamp::spotblend, Lamp::spotsize, and Lamp::type.
Referenced by gameobject_from_blenderobject().
static KX_GameObject* gameobject_from_blenderobject (Object * ob, KX_Scene * kxscene, RAS_IRenderTools * rendertools, KX_BlenderSceneConverter * converter) [static]
Definition at line 1915 of file BL_BlenderDataConversion.cpp.
References CListValue::Add(), KX_Scene::AddCamera(), KX_Scene::AddFont(), KX_GameObject::AddMesh(), CValue::AddRef(), BL_ConvertMesh(), Object::data, Object::defbase, Mesh::dvert, ListBase::first, gamecamera_from_bcamera(), Object::gameflag, Object::gameflag2, gamelight_from_blamp(), KX_Scene::GetBlenderScene(), KX_Scene::GetLightList(), KX_Scene::GetLogicManager(), RAS_MeshObject::GetName(), KX_GameObject::GetSGNode(), bArmature::gevertdeformer, BL_ModifierDeformer::HasArmatureDeformer(), BL_ModifierDeformer::HasCompatibleDeformer(), Mesh::key, KEY_RELATIVE, Object::lay, Scene::lay, BL_ShapeDeformer::LoadShapeDrivers(), KX_Scene::m_callbacks, max, Object::mesh, min, my_boundbox_mesh(), NULL, OB_ARMATURE, OB_CAMERA, OB_EMPTY, OB_FONT, OB_LAMP, OB_MESH, OB_NAVMESH, OB_NEVER_DO_ACTIVITY_CULLING, OB_OCCLUDER, OB_RESTRICT_RENDER, OB_SOFT_BODY, Object::parent, SCA_LogicManager::RegisterMeshName(), Object::restrictflag, SG_Spatial::SetBBox(), KX_GameObject::SetBlenderObject(), SCA_IObject::SetIgnoreActivityCulling(), KX_GameObject::SetLayer(), KX_GameObject::SetOccluder(), SG_Spatial::SetRadius(), KX_GameObject::SetVisible(), Key::type, and Object::type.
Referenced by BL_ConvertBlenderObjects().
ListBase* get_active_constraints2 (Object * ob)
Definition at line 2095 of file BL_BlenderDataConversion.cpp.
References bPoseChannel::constraints, Object::constraints, get_active_posechannel2(), Object::mode, NULL, and OB_MODE_POSE.
Referenced by BL_ConvertBlenderObjects(), and RBJconstraints().
bPoseChannel* get_active_posechannel2 (Object * ob)
Definition at line 2081 of file BL_BlenderDataConversion.cpp.
References bArmature::act_bone, bPose::chanbase, Object::data, ListBase::first, bArmature::layer, NULL, and Object::pose.
Referenced by get_active_constraints2().
KX_GameObject* getGameOb (STR_String busc, CListValue * sumolist)
Definition at line 2149 of file BL_BlenderDataConversion.cpp.
References CListValue::GetCount(), KX_GameObject::GetName(), and CListValue::GetValue().
Referenced by BL_ConvertBlenderObjects().
KX_IPhysicsController* getPhId (CListValue * sumolist, STR_String busc)
Definition at line 2136 of file BL_BlenderDataConversion.cpp.
References CListValue::GetCount(), KX_GameObject::GetName(), KX_GameObject::GetPhysicsController(), and CListValue::GetValue().
static void GetRGB (short type, MFace * mface, MCol * mmcol, Material * mat, unsigned int & c0, unsigned int & c1, unsigned int & c2, unsigned int & c3) [static]
Definition at line 429 of file BL_BlenderDataConversion.cpp.
References Material::alpha, Material::b, Material::g, KX_Mcol2uint_new(), KX_rgbaint2uint_new(), L, Material::r, and MFace::v4.
Referenced by ConvertMaterial().
static unsigned int KX_Mcol2uint_new (MCol col) [static]
Definition at line 392 of file BL_BlenderDataConversion.cpp.
Referenced by BL_ConvertMesh(), and GetRGB().
static unsigned int KX_rgbaint2uint_new (unsigned int icol) [static]
Definition at line 374 of file BL_BlenderDataConversion.cpp.
Referenced by BL_ConvertMesh(), ConvertMaterial(), and GetRGB().
static float my_boundbox_mesh (Mesh * me, float * loc, float * size) [static]
Definition at line 1360 of file BL_BlenderDataConversion.cpp.
References Mesh::bb, MVert::co, co, DO_MINMAX, INIT_MINMAX, max, MEM_callocN(), min, Mesh::mvert, sqrt(), Mesh::totvert, and BoundBox::vec.
Referenced by gameobject_from_blenderobject(), and my_tex_space_mesh().
static void my_get_local_bounds (Object * ob, DerivedMesh * dm, float * center, float * size) [static]
Definition at line 1469 of file BL_BlenderDataConversion.cpp.
References Object::bb, Object::data, fabs(), fabsf, DerivedMesh::getMinMax, INIT_MINMAX, my_tex_space_mesh(), NULL, OB_CURVE, OB_FONT, OB_MBALL, OB_MESH, OB_SURF, Object::type, and BoundBox::vec.
Referenced by BL_CreatePhysicsObjectNew().
static void my_tex_space_mesh (Mesh * me) [static]
Definition at line 1419 of file BL_BlenderDataConversion.cpp.
References copy_v3_v3(), KeyBlock::data, DO_MINMAX, INIT_MINMAX, Mesh::key, Mesh::loc, max, ME_AUTOSPACE, min, my_boundbox_mesh(), Key::refkey, Mesh::rot, Mesh::size, size(), Mesh::texflag, and KeyBlock::totelem.
Referenced by my_get_local_bounds().
void RBJconstraints (Object * ob)
Definition at line 2115 of file BL_BlenderDataConversion.cpp.
References ListBase::first, get_active_constraints2(), bConstraint::next, and bConstraint::type.
static void SetDefaultLightMode (Scene * scene) [static]
Definition at line 411 of file BL_BlenderDataConversion.cpp.
References default_light_mode, OB_LAMP, Base::object, SETLOOPER, and Object::type.
Referenced by BL_ConvertBlenderObjects().
Variable Documentation
bool default_light_mode = 0 [static]
Definition at line 198 of file BL_BlenderDataConversion.cpp.
Referenced by BL_ConvertMesh(), and SetDefaultLightMode().
Material defmaterial
Definition at line 71 of file material.c.
Referenced by BL_ConvertMesh(), give_current_material_or_def(), give_render_material(), GPU_begin_object_materials(), GPU_codegen_exit(), and GPU_materials_free().
std::map<int, SCA_IInputDevice::KX_EnumInputs> gReverseKeyTranslateTable = create_translate_table() [static]
Definition at line 372 of file BL_BlenderDataConversion.cpp.
Referenced by ConvertKeyCode().