Blender: smallhash.c File Reference
smallhash.c File Reference
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_smallhash.h"
Defines
#define SMHASH_CELL_UNUSED ((void *)0x7FFFFFFF)
#define SMHASH_CELL_FREE ((void *)0x7FFFFFFD)
#define SMHASH_NONZERO(n) ((n) + !(n))
#define SMHASH_NEXT(h, hoff) ABS(((h) + ((hoff = SMHASH_NONZERO(hoff * 2) + 1), hoff)))
Functions
void BLI_smallhash_init (SmallHash *hash)
void BLI_smallhash_release (SmallHash *hash)
void BLI_smallhash_insert (SmallHash *hash, uintptr_t key, void *item)
void BLI_smallhash_remove (SmallHash *hash, uintptr_t key)
void * BLI_smallhash_lookup (SmallHash *hash, uintptr_t key)
int BLI_smallhash_haskey (SmallHash *hash, uintptr_t key)
int BLI_smallhash_count (SmallHash *hash)
void * BLI_smallhash_iternext (SmallHashIter *iter, uintptr_t *key)
void * BLI_smallhash_iternew (SmallHash *hash, SmallHashIter *iter, uintptr_t *key)
Variables
unsigned int hashsizes []
Define Documentation
#define SMHASH_CELL_FREE ((void *)0x7FFFFFFD)
Definition at line 44 of file smallhash.c.
Referenced by BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_iternext(), BLI_smallhash_lookup(), and BLI_smallhash_remove().
#define SMHASH_CELL_UNUSED ((void *)0x7FFFFFFF)
Definition at line 43 of file smallhash.c.
Referenced by BLI_smallhash_haskey(), BLI_smallhash_insert(), BLI_smallhash_iternext(), BLI_smallhash_lookup(), and BLI_smallhash_remove().
#define SMHASH_NEXT (h, hoff) ABS(((h) + ((hoff = SMHASH_NONZERO(hoff * 2) + 1), hoff)))
Definition at line 47 of file smallhash.c.
Referenced by BLI_smallhash_haskey(), BLI_smallhash_insert(), BLI_smallhash_lookup(), and BLI_smallhash_remove().
#define SMHASH_NONZERO (n) ((n) + !(n))
Definition at line 46 of file smallhash.c.
Function Documentation
int BLI_smallhash_count (SmallHash * hash)
Definition at line 215 of file smallhash.c.
References SmallHash::used.
int BLI_smallhash_haskey (SmallHash * hash, uintptr_t key)
Definition at line 193 of file smallhash.c.
References ABS, ELEM, SmallHashEntry::key, NULL, SmallHash::size, SMHASH_CELL_FREE, SMHASH_CELL_UNUSED, SMHASH_NEXT, SmallHash::table, and SmallHashEntry::val.
Referenced by BM_edge_split(), bmo_bevel_exec(), bmo_triangle_fill_exec(), cage_mapped_verts_callback(), createSlideVerts(), edgetag_add_adjacent(), edgetag_shortest_path(), editmesh_set_connectivity_distance(), find_chain_search(), find_hole_search(), knife_edge_tri_isect(), loop_find_region(), loop_find_regions(), projectSVData(), and rotsys_fill_faces().
void BLI_smallhash_init (SmallHash * hash)
Definition at line 51 of file smallhash.c.
References SmallHash::_copytable, SmallHash::_stacktable, SmallHash::copytable, SmallHash::curhash, hashsizes, i, SmallHash::size, SMHASH_CELL_FREE, SmallHash::stacktable, SmallHash::table, and SmallHashEntry::val.
Referenced by BM_edge_split(), BMBVH_NewBVH(), bmo_bevel_exec(), bmo_triangle_fill_exec(), createSlideVerts(), edgetag_shortest_path(), editmesh_set_connectivity_distance(), find_chain_from_vertex(), find_hole(), knife_find_line_hits(), knife_make_cuts(), knifetool_init(), loop_find_regions(), projectSVData(), and rotsys_fill_faces().
void BLI_smallhash_insert (SmallHash * hash, uintptr_t key, void * item)
Definition at line 81 of file smallhash.c.
References ABS, SmallHash::copytable, SmallHash::curhash, ELEM, hashsizes, i, SmallHashEntry::key, MEM_callocN(), MEM_freeN(), SmallHash::size, SMHASH_CELL_FREE, SMHASH_CELL_UNUSED, SMHASH_NEXT, SMSTACKSIZE, SmallHash::stacktable, SWAP, SmallHash::table, SmallHash::used, and SmallHashEntry::val.
Referenced by BM_edge_split(), bmo_bevel_exec(), bmo_triangle_fill_exec(), cage_mapped_verts_callback(), createSlideVerts(), edgetag_shortest_path(), editmesh_set_connectivity_distance(), find_chain_from_vertex(), find_chain_search(), find_hole_search(), knife_edge_tri_isect(), knife_make_cuts(), loop_find_region(), projectSVData(), and rotsys_fill_faces().
void* BLI_smallhash_iternew (SmallHash * hash, SmallHashIter * iter, uintptr_t * key)
Definition at line 241 of file smallhash.c.
References BLI_smallhash_iternext(), hash, SmallHashIter::hash, and SmallHashIter::i.
Referenced by freeSlideTempFaces(), and knife_make_cuts().
void* BLI_smallhash_iternext (SmallHashIter * iter, uintptr_t * key)
Definition at line 220 of file smallhash.c.
References SmallHashIter::hash, SmallHashIter::i, SmallHashEntry::key, NULL, SmallHash::size, SMHASH_CELL_FREE, SMHASH_CELL_UNUSED, SmallHash::table, and SmallHashEntry::val.
Referenced by BLI_smallhash_iternew(), freeSlideTempFaces(), and knife_make_cuts().
void* BLI_smallhash_lookup (SmallHash * hash, uintptr_t key)
Definition at line 163 of file smallhash.c.
References ABS, ELEM, SmallHashEntry::key, NULL, SmallHash::size, SMHASH_CELL_FREE, SMHASH_CELL_UNUSED, SMHASH_NEXT, SmallHash::table, and SmallHashEntry::val.
Referenced by bmo_bevel_exec(), bmo_triangle_fill_exec(), createSlideVerts(), knife_make_cuts(), and projectSVData().
void BLI_smallhash_release (SmallHash * hash)
Definition at line 70 of file smallhash.c.
References MEM_freeN(), NULL, SmallHash::stacktable, and SmallHash::table.
Referenced by BM_edge_split(), BMBVH_NewBVH(), bmo_bevel_exec(), bmo_triangle_fill_exec(), createSlideVerts(), edgetag_shortest_path(), editmesh_set_connectivity_distance(), find_chain_from_vertex(), find_hole(), freeSlideTempFaces(), freeSlideVerts(), knife_find_line_hits(), knife_make_cuts(), knifetool_init(), loop_find_regions(), projectSVData(), and rotsys_fill_faces().
void BLI_smallhash_remove (SmallHash * hash, uintptr_t key)
Definition at line 142 of file smallhash.c.
References ABS, SmallHashEntry::key, SmallHash::size, SMHASH_CELL_FREE, SMHASH_CELL_UNUSED, SMHASH_NEXT, SmallHash::table, and SmallHashEntry::val.
Referenced by bmo_bevel_exec().
Variable Documentation
unsigned int hashsizes[]
Definition at line 47 of file BLI_ghash.c.
Referenced by BLI_ghash_insert(), BLI_ghash_new(), BLI_smallhash_init(), and BLI_smallhash_insert().