Blender: clip_ops.c File Reference
clip_ops.c File Reference
#include <errno.h>
#include "MEM_guardedalloc.h"
#include "DNA_userdef_types.h"
#include "DNA_scene_types.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_report.h"
#include "BKE_main.h"
#include "BKE_library.h"
#include "BKE_movieclip.h"
#include "BKE_sound.h"
#include "BKE_tracking.h"
#include "WM_api.h"
#include "WM_types.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "ED_screen.h"
#include "ED_clip.h"
#include "UI_interface.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "UI_view2d.h"
#include "clip_intern.h"
Classes
struct ViewPanData
struct ViewZoomData
struct ProxyBuildJob
Typedefs
typedef struct ViewPanData ViewPanData
typedef struct ViewZoomData ViewZoomData
typedef struct ProxyBuildJob ProxyJob
Functions
static void sclip_zoom_set (SpaceClip *sc, ARegion *ar, float zoom, float location[2])
static void sclip_zoom_set_factor (SpaceClip *sc, ARegion *ar, float zoomfac, float location[2])
static void sclip_zoom_set_factor_exec (bContext *C, wmEvent *event, float factor)
static void clip_filesel (bContext *C, wmOperator *op, const char *path)
static void open_init (bContext *C, wmOperator *op)
static int open_cancel (bContext *UNUSED(C), wmOperator *op)
static int open_exec (bContext *C, wmOperator *op)
static int open_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void CLIP_OT_open (wmOperatorType *ot)
static int reload_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_reload (wmOperatorType *ot)
static void view_pan_init (bContext *C, wmOperator *op, wmEvent *event)
static void view_pan_exit (bContext *C, wmOperator *op, int cancel)
static int view_pan_exec (bContext *C, wmOperator *op)
static int view_pan_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int view_pan_modal (bContext *C, wmOperator *op, wmEvent *event)
static int view_pan_cancel (bContext *C, wmOperator *op)
void CLIP_OT_view_pan (wmOperatorType *ot)
static void view_zoom_init (bContext *C, wmOperator *op, wmEvent *event)
static void view_zoom_exit (bContext *C, wmOperator *op, int cancel)
static int view_zoom_exec (bContext *C, wmOperator *op)
static int view_zoom_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int view_zoom_modal (bContext *C, wmOperator *op, wmEvent *event)
static int view_zoom_cancel (bContext *C, wmOperator *op)
void CLIP_OT_view_zoom (wmOperatorType *ot)
static int view_zoom_in_exec (bContext *C, wmOperator *op)
static int view_zoom_in_invoke (bContext *C, wmOperator *op, wmEvent *event)
void CLIP_OT_view_zoom_in (wmOperatorType *ot)
static int view_zoom_out_exec (bContext *C, wmOperator *op)
static int view_zoom_out_invoke (bContext *C, wmOperator *op, wmEvent *event)
void CLIP_OT_view_zoom_out (wmOperatorType *ot)
static int view_zoom_ratio_exec (bContext *C, wmOperator *op)
void CLIP_OT_view_zoom_ratio (wmOperatorType *ot)
static int view_all_exec (bContext *C, wmOperator *op)
void CLIP_OT_view_all (wmOperatorType *ot)
static int view_selected_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_view_selected (wmOperatorType *ot)
static int change_frame_poll (bContext *C)
static void change_frame_apply (bContext *C, wmOperator *op)
static int change_frame_exec (bContext *C, wmOperator *op)
static int frame_from_event (bContext *C, wmEvent *event)
static int change_frame_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int change_frame_modal (bContext *C, wmOperator *op, wmEvent *event)
void CLIP_OT_change_frame (wmOperatorType *ot)
static void proxy_freejob (void *pjv)
static int proxy_bitflag_to_array (int size_flag, int build_sizes[4], int undistort)
static void proxy_startjob (void *pjv, short *stop, short *do_update, float *progress)
static void proxy_endjob (void *pjv)
static int clip_rebuild_proxy_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_rebuild_proxy (wmOperatorType *ot)
static int mode_set_exec (bContext *C, wmOperator *op)
void CLIP_OT_mode_set (wmOperatorType *ot)
void ED_operatormacros_clip (void)
Detailed Description
Definition in file clip_ops.c.
Typedef Documentation
typedef struct ProxyBuildJob ProxyJob
typedef struct ViewPanData ViewPanData
typedef struct ViewZoomData ViewZoomData
Function Documentation
static void change_frame_apply (bContext * C, wmOperator * op) [static]
Definition at line 765 of file clip_ops.c.
References CFRA, CTX_data_main(), CTX_data_scene(), FRAMENUMBER_MIN_CLAMP, NC_SCENE, ND_FRAME, wmOperator::ptr, RNA_int_get(), sound_seek_scene(), SUBFRA, and WM_event_add_notifier().
Referenced by change_frame_exec(), change_frame_invoke(), and change_frame_modal().
static int change_frame_exec (bContext * C, wmOperator * op) [static]
Definition at line 779 of file clip_ops.c.
References change_frame_apply(), and OPERATOR_FINISHED.
Referenced by CLIP_OT_change_frame().
static int change_frame_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 808 of file clip_ops.c.
References change_frame_apply(), CTX_wm_region(), frame_from_event(), wmEvent::mval, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, wmOperator::ptr, ARegion::regiontype, RGN_TYPE_WINDOW, RNA_int_set(), and WM_event_add_modal_handler().
Referenced by CLIP_OT_change_frame().
static int change_frame_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 827 of file clip_ops.c.
References change_frame_apply(), ESCKEY, frame_from_event(), KM_RELEASE, LEFTMOUSE, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RIGHTMOUSE, RNA_int_set(), wmEvent::type, and wmEvent::val.
Referenced by CLIP_OT_change_frame().
static int change_frame_poll (bContext * C) [static]
Definition at line 756 of file clip_ops.c.
References ED_space_clip_poll(), and G.
Referenced by CLIP_OT_change_frame().
static void clip_filesel (bContext * C, wmOperator * op, const char * path) [static]
Definition at line 124 of file clip_ops.c.
References wmOperator::ptr, RNA_string_set(), and WM_event_add_fileselect().
Referenced by open_invoke().
void CLIP_OT_change_frame (wmOperatorType * ot)
Definition at line 848 of file clip_ops.c.
References change_frame_exec(), change_frame_invoke(), change_frame_modal(), change_frame_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAXFRAME, MINAFRAME, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_mode_set (wmOperatorType * ot)
Definition at line 1057 of file clip_ops.c.
References wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::idname, mode_set_exec(), wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), SC_MODE_DISTORTION, SC_MODE_RECONSTRUCTION, SC_MODE_TRACKING, and wmOperatorType::srna.
Referenced by clip_operatortypes().
void CLIP_OT_open (wmOperatorType * ot)
Definition at line 222 of file clip_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, MOVIEFILE, wmOperatorType::name, open_cancel(), open_exec(), open_invoke(), OPTYPE_REGISTER, OPTYPE_UNDO, WM_FILESEL_FILEPATH, WM_FILESEL_RELPATH, and WM_operator_properties_filesel().
Referenced by clip_operatortypes().
void CLIP_OT_rebuild_proxy (wmOperatorType * ot)
Definition at line 1021 of file clip_ops.c.
References clip_rebuild_proxy_exec(), wmOperatorType::description, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by clip_operatortypes().
void CLIP_OT_reload (wmOperatorType * ot)
Definition at line 257 of file clip_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and reload_exec().
Referenced by clip_operatortypes().
void CLIP_OT_view_all (wmOperatorType * ot)
Definition at line 713 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and view_all_exec().
Referenced by clip_operatortypes().
void CLIP_OT_view_pan (wmOperatorType * ot)
Definition at line 399 of file clip_ops.c.
References wmOperatorType::cancel, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, view_pan_cancel(), view_pan_exec(), view_pan_invoke(), and view_pan_modal().
Referenced by clip_operatortypes().
void CLIP_OT_view_selected (wmOperatorType * ot)
Definition at line 743 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and view_selected_exec().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom (wmOperatorType * ot)
Definition at line 525 of file clip_ops.c.
References wmOperatorType::cancel, ED_space_clip_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, view_zoom_cancel(), view_zoom_exec(), view_zoom_invoke(), and view_zoom_modal().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom_in (wmOperatorType * ot)
Definition at line 573 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, view_zoom_in_exec(), and view_zoom_in_invoke().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom_out (wmOperatorType * ot)
Definition at line 613 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_float_vector(), wmOperatorType::srna, view_zoom_out_exec(), and view_zoom_out_invoke().
Referenced by clip_operatortypes().
void CLIP_OT_view_zoom_ratio (wmOperatorType * ot)
Definition at line 646 of file clip_ops.c.
References ED_space_clip_poll(), wmOperatorType::exec, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, and view_zoom_ratio_exec().
Referenced by clip_operatortypes().
static int clip_rebuild_proxy_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 984 of file clip_ops.c.
References MovieClip::anim, MovieClipProxy::build_size_flag, MovieClipProxy::build_tc_flag, ProxyBuildJob::clip, ProxyBuildJob::clip_flag, CTX_data_main(), CTX_data_scene(), CTX_wm_area(), CTX_wm_manager(), CTX_wm_space_clip(), CTX_wm_window(), ED_area_tag_redraw(), ED_space_clip(), MovieClip::flag, G, IMB_anim_index_rebuild_context(), ProxyBuildJob::index_context, ProxyBuildJob::main, MCLIP_TIMECODE_FLAGS, MCLIP_USE_PROXY, MEM_callocN(), NC_MOVIECLIP, ND_DISPLAY, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, MovieClip::proxy, proxy_endjob(), proxy_freejob(), proxy_startjob(), MovieClipProxy::quality, ProxyBuildJob::scene, WM_JOB_PROGRESS, WM_jobs_callbacks(), WM_jobs_customdata(), WM_jobs_get(), WM_jobs_start(), and WM_jobs_timer().
Referenced by CLIP_OT_rebuild_proxy().
void ED_operatormacros_clip (void)
Definition at line 1083 of file clip_ops.c.
References wmOperatorType::description, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorTypeMacro::ptr, RNA_boolean_set(), RNA_struct_idprops_unset(), TRUE, WM_operatortype_append_macro(), and WM_operatortype_macro_define().
Referenced by ED_spacetypes_init().
static int frame_from_event (bContext * C, wmEvent * event) [static]
Definition at line 786 of file clip_ops.c.
References CTX_data_scene(), CTX_wm_region(), EFRA, wmEvent::mval, ARegion::regiontype, RGN_TYPE_WINDOW, SFRA, UI_view2d_region_to_view(), ARegion::v2d, and ARegion::winx.
Referenced by change_frame_invoke(), and change_frame_modal().
static int mode_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 1038 of file clip_ops.c.
References CTX_wm_space_clip(), SpaceClip::mode, NC_SPACE, ND_SPACE_CLIP, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), SC_MODE_TRACKING, and WM_event_add_notifier().
Referenced by CLIP_OT_mode_set().
static int open_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 139 of file clip_ops.c.
References wmOperator::customdata, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by CLIP_OT_open().
static int open_exec (bContext * C, wmOperator * op) [static]
Definition at line 147 of file clip_ops.c.
References BKE_add_movieclip_file(), BKE_reportf(), CTX_wm_space_clip(), wmOperator::customdata, ED_space_clip_set(), FILE_MAX, MovieClip::id, MEM_freeN(), NA_ADDED, NC_MOVIECLIP, NULL, open_init(), OPERATOR_CANCELLED, OPERATOR_FINISHED, PropertyPointerRNA::prop, wmOperator::ptr, PropertyPointerRNA::ptr, wmOperator::reports, RNA_id_pointer_create(), RNA_property_pointer_set(), RNA_property_update(), RNA_string_get(), RPT_ERROR, str, ID::us, and WM_event_add_notifier().
Referenced by CLIP_OT_open(), and open_invoke().
static void open_init (bContext * C, wmOperator * op) [static]
Definition at line 131 of file clip_ops.c.
References wmOperator::customdata, MEM_callocN(), PropertyPointerRNA::prop, PropertyPointerRNA::ptr, and uiIDContextProperty().
Referenced by open_exec(), and open_invoke().
static int open_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 197 of file clip_ops.c.
References clip_filesel(), CTX_wm_space_clip(), ED_space_clip(), MovieClip::name, NULL, open_exec(), open_init(), OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_boolean_set(), RNA_struct_property_is_set(), and USER_RELPATHS.
Referenced by CLIP_OT_open().
static int proxy_bitflag_to_array (int size_flag, int build_sizes[4], int undistort) [static]
Definition at line 885 of file clip_ops.c.
References MCLIP_PROXY_RENDER_SIZE_100, MCLIP_PROXY_RENDER_SIZE_25, MCLIP_PROXY_RENDER_SIZE_50, MCLIP_PROXY_RENDER_SIZE_75, MCLIP_PROXY_SIZE_100, MCLIP_PROXY_SIZE_25, MCLIP_PROXY_SIZE_50, MCLIP_PROXY_SIZE_75, MCLIP_PROXY_UNDISTORTED_SIZE_100, MCLIP_PROXY_UNDISTORTED_SIZE_25, MCLIP_PROXY_UNDISTORTED_SIZE_50, and MCLIP_PROXY_UNDISTORTED_SIZE_75.
Referenced by proxy_startjob().
static void proxy_endjob (void * pjv) [static]
Definition at line 969 of file clip_ops.c.
References MovieClip::anim, BKE_movieclip_reload(), ProxyBuildJob::clip, IMB_anim_index_rebuild_finish(), IMB_close_anim_proxies(), ProxyBuildJob::index_context, NC_MOVIECLIP, ND_DISPLAY, ProxyBuildJob::stop, and WM_main_add_notifier().
Referenced by clip_rebuild_proxy_exec().
static void proxy_freejob (void * pjv) [static]
Definition at line 878 of file clip_ops.c.
References MEM_freeN().
Referenced by clip_rebuild_proxy_exec().
static void proxy_startjob (void * pjv, short * stop, short * do_update, float * progress) [static]
Definition at line 914 of file clip_ops.c.
References MovieClip::anim, BKE_movieclip_build_proxy_frame(), BKE_tracking_distortion_create(), BKE_tracking_distortion_destroy(), MovieClipProxy::build_size_flag, ProxyBuildJob::clip, ProxyBuildJob::clip_flag, EFRA, G, IMB_anim_get_duration(), IMB_anim_index_rebuild(), IMB_TC_NONE, ProxyBuildJob::index_context, MCLIP_SRC_MOVIE, NULL, MovieClip::proxy, proxy_bitflag_to_array(), ProxyBuildJob::scene, SFRA, MovieClip::source, ProxyBuildJob::stop, and TRUE.
Referenced by clip_rebuild_proxy_exec().
static int reload_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 243 of file clip_ops.c.
References BKE_movieclip_reload(), CTX_data_edit_movieclip(), NA_EDITED, NC_MOVIECLIP, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by CLIP_OT_reload().
static void sclip_zoom_set (SpaceClip * sc, ARegion * ar, float zoom, float location[2]) [static]
Definition at line 71 of file clip_ops.c.
References ED_space_clip_size(), USER_ZOOM_TO_MOUSEPOS, ARegion::winrct, rcti::xmax, rcti::xmin, SpaceClip::xof, rcti::ymax, rcti::ymin, SpaceClip::yof, and SpaceClip::zoom.
Referenced by sclip_zoom_set_factor(), view_all_exec(), view_zoom_modal(), and view_zoom_ratio_exec().
static void sclip_zoom_set_factor (SpaceClip * sc, ARegion * ar, float zoomfac, float location[2]) [static]
Definition at line 101 of file clip_ops.c.
References sclip_zoom_set(), and SpaceClip::zoom.
Referenced by sclip_zoom_set_factor_exec(), view_zoom_exec(), view_zoom_in_exec(), and view_zoom_out_exec().
static void sclip_zoom_set_factor_exec (bContext * C, wmEvent * event, float factor) [static]
Definition at line 106 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_clip_mouse_pos(), ED_region_tag_redraw(), NULL, and sclip_zoom_set_factor().
Referenced by view_zoom_invoke().
static int view_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 663 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_region_tag_redraw(), ED_space_clip_aspect(), ED_space_clip_size(), MIN2, NULL, OPERATOR_FINISHED, power_of_2(), wmOperator::ptr, RNA_boolean_get(), sclip_zoom_set(), ARegion::winrct, rcti::xmax, rcti::xmin, SpaceClip::xof, rcti::ymax, rcti::ymin, and SpaceClip::yof.
Referenced by CLIP_OT_view_all().
static int view_pan_cancel (bContext * C, wmOperator * op) [static]
Definition at line 392 of file clip_ops.c.
References OPERATOR_CANCELLED, and view_pan_exit().
Referenced by CLIP_OT_view_pan().
static int view_pan_exec (bContext * C, wmOperator * op) [static]
Definition at line 315 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_region_tag_redraw(), SpaceClip::flag, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), SC_LOCK_SELECTION, SpaceClip::xlockof, SpaceClip::xof, SpaceClip::ylockof, and SpaceClip::yof.
Referenced by CLIP_OT_view_pan(), view_pan_invoke(), and view_pan_modal().
static void view_pan_exit (bContext * C, wmOperator * op, int cancel) [static]
Definition at line 301 of file clip_ops.c.
References copy_v2_v2(), CTX_wm_region(), CTX_wm_window(), wmOperator::customdata, ED_region_tag_redraw(), MEM_freeN(), ViewPanData::vec, WM_cursor_restore(), and ViewPanData::xorig.
Referenced by view_pan_cancel(), and view_pan_modal().
static void view_pan_init (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 277 of file clip_ops.c.
References BC_NSEW_SCROLLCURSOR, copy_v2_v2(), CTX_wm_space_clip(), CTX_wm_window(), wmOperator::customdata, ViewPanData::event_type, SpaceClip::flag, MEM_callocN(), SC_LOCK_SELECTION, ViewPanData::vec, WM_cursor_modal(), WM_event_add_modal_handler(), ViewPanData::x, SpaceClip::xlockof, SpaceClip::xof, ViewPanData::xof, ViewPanData::xorig, and ViewPanData::y.
Referenced by view_pan_invoke().
static int view_pan_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 336 of file clip_ops.c.
References CTX_wm_space_clip(), MOUSEPAN, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmEvent::prevy, wmOperator::ptr, RNA_float_set_array(), wmEvent::type, view_pan_exec(), view_pan_init(), wmEvent::y, and SpaceClip::zoom.
Referenced by CLIP_OT_view_pan().
static int view_pan_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 358 of file clip_ops.c.
References copy_v2_v2(), CTX_wm_space_clip(), wmOperator::customdata, ESCKEY, ViewPanData::event_type, KM_RELEASE, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_float_set_array(), SPACEKEY, wmEvent::type, wmEvent::val, ViewPanData::vec, view_pan_exec(), view_pan_exit(), ViewPanData::x, ViewPanData::xorig, ViewPanData::y, wmEvent::y, and SpaceClip::zoom.
Referenced by CLIP_OT_view_pan().
static int view_selected_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 729 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_clip_view_selection(), ED_region_tag_redraw(), OPERATOR_FINISHED, SpaceClip::xlockof, and SpaceClip::ylockof.
Referenced by CLIP_OT_view_selected().
static int view_zoom_cancel (bContext * C, wmOperator * op) [static]
Definition at line 518 of file clip_ops.c.
References OPERATOR_CANCELLED, and view_zoom_exit().
Referenced by CLIP_OT_view_zoom().
static int view_zoom_exec (bContext * C, wmOperator * op) [static]
Definition at line 461 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_region_tag_redraw(), NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), and sclip_zoom_set_factor().
Referenced by CLIP_OT_view_zoom().
static void view_zoom_exit (bContext * C, wmOperator * op, int cancel) [static]
Definition at line 447 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), CTX_wm_window(), wmOperator::customdata, ED_region_tag_redraw(), MEM_freeN(), WM_cursor_restore(), ViewZoomData::zoom, and SpaceClip::zoom.
Referenced by view_zoom_cancel(), and view_zoom_modal().
static int view_zoom_in_exec (bContext * C, wmOperator * op) [static]
Definition at line 548 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_region_tag_redraw(), OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), and sclip_zoom_set_factor().
Referenced by CLIP_OT_view_zoom_in(), and view_zoom_in_invoke().
static int view_zoom_in_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 563 of file clip_ops.c.
References ED_clip_mouse_pos(), wmOperator::ptr, RNA_float_set_array(), and view_zoom_in_exec().
Referenced by CLIP_OT_view_zoom_in().
static void view_zoom_init (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 429 of file clip_ops.c.
References BC_NSEW_SCROLLCURSOR, CTX_wm_space_clip(), CTX_wm_window(), wmOperator::customdata, ED_clip_mouse_pos(), ViewZoomData::event_type, ViewZoomData::location, MEM_callocN(), WM_cursor_modal(), WM_event_add_modal_handler(), ViewZoomData::x, ViewZoomData::y, ViewZoomData::zoom, and SpaceClip::zoom.
Referenced by view_zoom_invoke().
static int view_zoom_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 473 of file clip_ops.c.
References MOUSEZOOM, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_float_set(), sclip_zoom_set_factor_exec(), wmEvent::type, and view_zoom_init().
Referenced by CLIP_OT_view_zoom().
static int view_zoom_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 492 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), wmOperator::customdata, ED_region_tag_redraw(), ViewZoomData::event_type, KM_RELEASE, ViewZoomData::location, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_float_set(), sclip_zoom_set(), wmEvent::type, wmEvent::val, view_zoom_exit(), ViewZoomData::x, ViewZoomData::y, and ViewZoomData::zoom.
Referenced by CLIP_OT_view_zoom().
static int view_zoom_out_exec (bContext * C, wmOperator * op) [static]
Definition at line 588 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_region_tag_redraw(), OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get_array(), and sclip_zoom_set_factor().
Referenced by CLIP_OT_view_zoom_out(), and view_zoom_out_invoke().
static int view_zoom_out_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 603 of file clip_ops.c.
References ED_clip_mouse_pos(), wmOperator::ptr, RNA_float_set_array(), and view_zoom_out_exec().
Referenced by CLIP_OT_view_zoom_out().
static int view_zoom_ratio_exec (bContext * C, wmOperator * op) [static]
Definition at line 630 of file clip_ops.c.
References CTX_wm_region(), CTX_wm_space_clip(), ED_region_tag_redraw(), NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), sclip_zoom_set(), SpaceClip::xof, and SpaceClip::yof.
Referenced by CLIP_OT_view_zoom_ratio().