Blender: rna_constraint.c File Reference
rna_constraint.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "BLI_math.h"
#include "BLF_translation.h"
#include "DNA_action_types.h"
#include "DNA_constraint_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "ED_object.h"
#include "WM_types.h"
Functions
static void rna_def_constrainttarget (BlenderRNA *brna)
static void rna_def_constraint_childof (BlenderRNA *brna)
static void rna_def_constraint_python (BlenderRNA *brna)
static void rna_def_constraint_kinematic (BlenderRNA *brna)
static void rna_def_constraint_track_to (BlenderRNA *brna)
static void rna_def_constraint_locate_like (BlenderRNA *brna)
static void rna_def_constraint_rotate_like (BlenderRNA *brna)
static void rna_def_constraint_size_like (BlenderRNA *brna)
static void rna_def_constraint_same_volume (BlenderRNA *brna)
static void rna_def_constraint_transform_like (BlenderRNA *brna)
static void rna_def_constraint_minmax (BlenderRNA *brna)
static void rna_def_constraint_action (BlenderRNA *brna)
static void rna_def_constraint_locked_track (BlenderRNA *brna)
static void rna_def_constraint_follow_path (BlenderRNA *brna)
static void rna_def_constraint_stretch_to (BlenderRNA *brna)
static void rna_def_constraint_rigid_body_joint (BlenderRNA *brna)
static void rna_def_constraint_clamp_to (BlenderRNA *brna)
static void rna_def_constraint_transform (BlenderRNA *brna)
static void rna_def_constraint_location_limit (BlenderRNA *brna)
static void rna_def_constraint_rotation_limit (BlenderRNA *brna)
static void rna_def_constraint_size_limit (BlenderRNA *brna)
static void rna_def_constraint_distance_limit (BlenderRNA *brna)
static void rna_def_constraint_shrinkwrap (BlenderRNA *brna)
static void rna_def_constraint_damped_track (BlenderRNA *brna)
static void rna_def_constraint_spline_ik (BlenderRNA *brna)
static void rna_def_constraint_pivot (BlenderRNA *brna)
static void rna_def_constraint_follow_track (BlenderRNA *brna)
static void rna_def_constraint_camera_solver (BlenderRNA *brna)
static void rna_def_constraint_object_solver (BlenderRNA *brna)
void RNA_def_constraint (BlenderRNA *brna)
Variables
EnumPropertyItem constraint_type_items []
static EnumPropertyItem target_space_pchan_items []
static EnumPropertyItem owner_space_pchan_items []
EnumPropertyItem constraint_distance_items []
Detailed Description
Definition in file rna_constraint.c.
Function Documentation
void RNA_def_constraint (BlenderRNA * brna)
Definition at line 2297 of file rna_constraint.c.
References CONSTRAINT_ACTIVE, CONSTRAINT_DISABLE, CONSTRAINT_EXPAND, CONSTRAINT_OFF, CONSTRAINT_PROXY_LOCAL, NA_RENAME, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_STRING, rna_def_constraint_action(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
static void rna_def_constraint_action (BlenderRNA * brna) [static]
Definition at line 1058 of file rna_constraint.c.
References MAXFRAME, MINAFRAME, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_camera_solver (BlenderRNA * brna) [static]
Definition at line 2234 of file rna_constraint.c.
References CAMERASOLVER_ACTIVECLIP, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_childof (BlenderRNA * brna) [static]
Definition at line 470 of file rna_constraint.c.
References CHILDOF_LOCX, CHILDOF_LOCY, CHILDOF_LOCZ, CHILDOF_ROTX, CHILDOF_ROTY, CHILDOF_ROTZ, CHILDOF_SIZEX, CHILDOF_SIZEY, CHILDOF_SIZEZ, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_FLOAT, PROP_MATRIX, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), and rna_matrix_dimsize_4x4.
Referenced by RNA_def_constraint().
static void rna_def_constraint_clamp_to (BlenderRNA * brna) [static]
Definition at line 1490 of file rna_constraint.c.
References CLAMPTO_AUTO, CLAMPTO_CYCLIC, CLAMPTO_X, CLAMPTO_Y, CLAMPTO_Z, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_damped_track (BlenderRNA * brna) [static]
Definition at line 1991 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), TRACK_nX, TRACK_nY, TRACK_nZ, TRACK_X, TRACK_Y, and TRACK_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_distance_limit (BlenderRNA * brna) [static]
Definition at line 1894 of file rna_constraint.c.
References LIMITDIST_TRANSFORM, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_follow_path (BlenderRNA * brna) [static]
Definition at line 1185 of file rna_constraint.c.
References FOLLOWPATH_FOLLOW, FOLLOWPATH_RADIUS, FOLLOWPATH_STATIC, MAXFRAME, MINAFRAME, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), TRACK_nX, TRACK_nY, TRACK_nZ, TRACK_X, TRACK_Y, and TRACK_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_follow_track (BlenderRNA * brna) [static]
Definition at line 2173 of file rna_constraint.c.
References FOLLOWTRACK_ACTIVECLIP, FOLLOWTRACK_USE_3D_POSITION, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_kinematic (BlenderRNA * brna) [static]
Definition at line 579 of file rna_constraint.c.
References CONSTRAINT_IK_AUTO, CONSTRAINT_IK_COPYPOSE, CONSTRAINT_IK_DISTANCE, CONSTRAINT_IK_NO_POS_X, CONSTRAINT_IK_NO_POS_Y, CONSTRAINT_IK_NO_POS_Z, CONSTRAINT_IK_NO_ROT_X, CONSTRAINT_IK_NO_ROT_Y, CONSTRAINT_IK_NO_ROT_Z, CONSTRAINT_IK_POS, CONSTRAINT_IK_ROT, CONSTRAINT_IK_STRETCH, CONSTRAINT_IK_TARGETAXIS, CONSTRAINT_IK_TIP, M_PI, NC_OBJECT, ND_CONSTRAINT, ND_POSE, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_locate_like (BlenderRNA * brna) [static]
Definition at line 790 of file rna_constraint.c.
References LOCLIKE_OFFSET, LOCLIKE_X, LOCLIKE_X_INVERT, LOCLIKE_Y, LOCLIKE_Y_INVERT, LOCLIKE_Z, LOCLIKE_Z_INVERT, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_location_limit (BlenderRNA * brna) [static]
Definition at line 1666 of file rna_constraint.c.
References LIMIT_TRANSFORM, LIMIT_XMAX, LIMIT_XMIN, LIMIT_YMAX, LIMIT_YMIN, LIMIT_ZMAX, LIMIT_ZMIN, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_locked_track (BlenderRNA * brna) [static]
Definition at line 1130 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), TRACK_nX, TRACK_nY, TRACK_nZ, TRACK_X, TRACK_Y, and TRACK_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_minmax (BlenderRNA * brna) [static]
Definition at line 1007 of file rna_constraint.c.
References MINMAX_STICKY, MINMAX_USEROT, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), TRACK_nX, TRACK_nY, TRACK_nZ, TRACK_X, TRACK_Y, and TRACK_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_object_solver (BlenderRNA * brna) [static]
Definition at line 2257 of file rna_constraint.c.
References CAMERASOLVER_ACTIVECLIP, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_pivot (BlenderRNA * brna) [static]
Definition at line 2111 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PIVOTCON_AXIS_NONE, PIVOTCON_AXIS_X, PIVOTCON_AXIS_X_NEG, PIVOTCON_AXIS_Y, PIVOTCON_AXIS_Y_NEG, PIVOTCON_AXIS_Z, PIVOTCON_AXIS_Z_NEG, PIVOTCON_FLAG_OFFSET_ABS, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_python (BlenderRNA * brna) [static]
Definition at line 544 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, PYCON_SCRIPTERROR, PYCON_USETARGETS, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_rigid_body_joint (BlenderRNA * brna) [static]
Definition at line 1319 of file rna_constraint.c.
References CONSTRAINT_DISABLE_LINKED_COLLISION, CONSTRAINT_DRAW_PIVOT, CONSTRAINT_RB_BALL, CONSTRAINT_RB_CONETWIST, CONSTRAINT_RB_GENERIC6DOF, CONSTRAINT_RB_HINGE, M_PI, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_rotate_like (BlenderRNA * brna) [static]
Definition at line 853 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), ROTLIKE_OFFSET, ROTLIKE_X, ROTLIKE_X_INVERT, ROTLIKE_Y, ROTLIKE_Y_INVERT, ROTLIKE_Z, and ROTLIKE_Z_INVERT.
Referenced by RNA_def_constraint().
static void rna_def_constraint_rotation_limit (BlenderRNA * brna) [static]
Definition at line 1747 of file rna_constraint.c.
References LIMIT_TRANSFORM, LIMIT_XROT, LIMIT_YROT, LIMIT_ZROT, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_same_volume (BlenderRNA * brna) [static]
Definition at line 951 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SAMEVOL_X, SAMEVOL_Y, and SAMEVOL_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_shrinkwrap (BlenderRNA * brna) [static]
Definition at line 1938 of file rna_constraint.c.
References MOD_SHRINKWRAP_NEAREST_SURFACE, MOD_SHRINKWRAP_NEAREST_VERTEX, MOD_SHRINKWRAP_PROJECT, MOD_SHRINKWRAP_PROJECT_OVER_X_AXIS, MOD_SHRINKWRAP_PROJECT_OVER_Y_AXIS, MOD_SHRINKWRAP_PROJECT_OVER_Z_AXIS, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_size_like (BlenderRNA * brna) [static]
Definition at line 909 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), SIZELIKE_OFFSET, SIZELIKE_X, SIZELIKE_Y, and SIZELIKE_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_size_limit (BlenderRNA * brna) [static]
Definition at line 1813 of file rna_constraint.c.
References LIMIT_TRANSFORM, LIMIT_XMAX, LIMIT_XMIN, LIMIT_YMAX, LIMIT_YMIN, LIMIT_ZMAX, LIMIT_ZMIN, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_spline_ik (BlenderRNA * brna) [static]
Definition at line 2034 of file rna_constraint.c.
References CONSTRAINT_SPLINEIK_EVENSPLITS, CONSTRAINT_SPLINEIK_NO_CURVERAD, CONSTRAINT_SPLINEIK_NO_ROOT, CONSTRAINT_SPLINEIK_SCALE_LIMITED, CONSTRAINT_SPLINEIK_XZS_NONE, CONSTRAINT_SPLINEIK_XZS_ORIGINAL, CONSTRAINT_SPLINEIK_XZS_VOLUMETRIC, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_DYNAMIC, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_stretch_to (BlenderRNA * brna) [static]
Definition at line 1257 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NO_VOLUME, NULL, PLANE_X, PLANE_Z, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), VOLUME_X, VOLUME_XZ, and VOLUME_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_track_to (BlenderRNA * brna) [static]
Definition at line 731 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), RNA_def_struct_ui_text(), TARGET_Z_UP, TRACK_nX, TRACK_nY, TRACK_nZ, TRACK_X, TRACK_Y, and TRACK_Z.
Referenced by RNA_def_constraint().
static void rna_def_constraint_transform (BlenderRNA * brna) [static]
Definition at line 1526 of file rna_constraint.c.
References CLAMPTO_CYCLIC, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constraint_transform_like (BlenderRNA * brna) [static]
Definition at line 980 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_EDITABLE, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
static void rna_def_constrainttarget (BlenderRNA * brna) [static]
Definition at line 447 of file rna_constraint.c.
References NC_OBJECT, ND_CONSTRAINT, NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_constraint().
Variable Documentation
EnumPropertyItem constraint_distance_items[]
Initial value:
 {
    {LIMITDIST_INSIDE, "LIMITDIST_INSIDE", 0, "Inside",
                       "The object is constrained inside a virtual sphere around the target object, "
                       "with a radius defined by the limit distance"},
    {LIMITDIST_OUTSIDE, "LIMITDIST_OUTSIDE", 0, "Outside",
                        "The object is constrained outside a virtual sphere around the target object, "
                        "with a radius defined by the limit distance"},
    {LIMITDIST_ONSURFACE, "LIMITDIST_ONSURFACE", 0, "On Surface",
                          "The object is constrained on the surface of a virtual sphere around the target object, "
                          "with a radius defined by the limit distance"},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 433 of file rna_constraint.c.
EnumPropertyItem constraint_type_items[]
Definition at line 47 of file rna_constraint.c.
Referenced by OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), rna_def_object_constraints(), and rna_def_pose_channel_constraints().
EnumPropertyItem owner_space_pchan_items[] [static]
Initial value:
 {
    {CONSTRAINT_SPACE_WORLD,    "WORLD", 0, "World Space",
                                "The constraint is applied relative to the world coordinate system"},
    {CONSTRAINT_SPACE_POSE,     "POSE", 0, "Pose Space",
                                "The constraint is applied in Pose Space, the object transformation is ignored"},
    {CONSTRAINT_SPACE_PARLOCAL, "LOCAL_WITH_PARENT", 0, "Local With Parent",
                                "The constraint is applied relative to the local coordinate system of the object, "
                                "with the parent transformation added"},
    {CONSTRAINT_SPACE_LOCAL,    "LOCAL", 0, "Local Space",
                                "The constraint is applied relative to the local coordinate sytem of the object"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 100 of file rna_constraint.c.
EnumPropertyItem target_space_pchan_items[] [static]
Initial value:
 {
    {CONSTRAINT_SPACE_WORLD,    "WORLD", 0, "World Space",
                                "The transformation of the target is evaluated relative to the world "
                                "coordinate system"},
    {CONSTRAINT_SPACE_POSE,     "POSE", 0, "Pose Space",
                                "The transformation of the target is only evaluated in the Pose Space, "
                                "the target armature object transformation is ignored"},
    {CONSTRAINT_SPACE_PARLOCAL, "LOCAL_WITH_PARENT", 0, "Local With Parent",
                                "The transformation of the target bone is evaluated relative its local "
                                "coordinate system, with the parent transformation added"},
    {CONSTRAINT_SPACE_LOCAL,    "LOCAL", 0, "Local Space",
                                "The transformation of the target is evaluated relative to its local "
                                "coordinate system"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 85 of file rna_constraint.c.