Blender: wm_apple.c File Reference
wm_apple.c File Reference
windowmanager
#include "BKE_context.h"
#include "BKE_global.h"
#include "WM_api.h"
#include <OpenGL/OpenGL.h>
#include <Carbon/Carbon.h>
Defines
#define __CARBONSOUND__
#define ID ID_
Functions
static int checkAppleVideoCard (void)
static void getMacAvailableBounds (short *top, short *left, short *bottom, short *right)
void wm_set_apple_prefsize (int scr_x, int scr_y)
Variables
int macPrefState = 0
Detailed Description
Definition in file wm_apple.c.
Define Documentation
#define __CARBONSOUND__
Definition at line 38 of file wm_apple.c.
#define ID ID_
Definition at line 40 of file wm_apple.c.
Function Documentation
static int checkAppleVideoCard (void) [static]
Definition at line 55 of file wm_apple.c.
References macPrefState, and NULL.
Referenced by wm_set_apple_prefsize().
static void getMacAvailableBounds (short * top, short * left, short * bottom, short * right) [static]
Definition at line 105 of file wm_apple.c.
Referenced by wm_set_apple_prefsize().
void wm_set_apple_prefsize (int scr_x, int scr_y)
Definition at line 118 of file wm_apple.c.
References checkAppleVideoCard(), G, getMacAvailableBounds(), left(), and WM_setprefsize().
Referenced by wm_window_add_ghostwindows().
Variable Documentation
int macPrefState = 0
Definition at line 53 of file wm_apple.c.
Referenced by checkAppleVideoCard(), and wm_window_add_ghostwindow().