Blender: INTERPOLATE Namespace Reference
INTERPOLATE Namespace Reference
Functions
static float lerp (float t, float a, float b)
static float lerp (float *field, float x, float y, int res)
static float lerp3d (float *field, float x, float y, float z, int xres, int yres, int zres)
template<class T >
static float lerp3dToFloat (T *field1, float x, float y, float z, int xres, int yres, int zres)
static Vec3 lerp3dVec (float *field1, float *field2, float *field3, float x, float y, float z, int xres, int yres, int zres)
Function Documentation
static float INTERPOLATE::lerp (float t, float a, float b) [inline, static]
Definition at line 34 of file INTERPOLATE.h.
Referenced by lerp().
static float INTERPOLATE::lerp (float * field, float x, float y, int res) [inline, static]
Definition at line 38 of file INTERPOLATE.h.
References lerp().
static float INTERPOLATE::lerp3d (float * field, float x, float y, float z, int xres, int yres, int zres) [inline, static]
Definition at line 63 of file INTERPOLATE.h.
Referenced by WTURBULENCE::stepTurbulenceFull().
template<class T > static float INTERPOLATE::lerp3dToFloat (T * field1, float x, float y, float z, int xres, int yres, int zres) [inline, static]
Definition at line 113 of file INTERPOLATE.h.
Referenced by WTURBULENCE::stepTurbulenceFull().
static Vec3 INTERPOLATE::lerp3dVec (float * field1, float * field2, float * field3, float x, float y, float z, int xres, int yres, int zres) [inline, static]
Definition at line 164 of file INTERPOLATE.h.
Referenced by WTURBULENCE::stepTurbulenceFull().