Blender: interface_utils.c File Reference
interface_utils.c File Reference
interface
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "DNA_object_types.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "RNA_access.h"
#include "UI_interface.h"
#include "UI_resources.h"
Functions
uiBut * uiDefAutoButR (uiBlock *block, PointerRNA *ptr, PropertyRNA *prop, int index, const char *name, int icon, int x1, int y1, int x2, int y2)
int uiDefAutoButsRNA (uiLayout *layout, PointerRNA *ptr, int(*check_prop)(PointerRNA *, PropertyRNA *), const char label_align)
int uiIconFromID (ID *id)
Detailed Description
Definition in file interface_utils.c.
Function Documentation
uiBut* uiDefAutoButR (uiBlock * block, PointerRNA * ptr, PropertyRNA * prop, int index, const char * name, int icon, int x1, int y1, int x2, int y2)
Definition at line 54 of file interface_utils.c.
References BLI_snprintf(), COL, ELEM, ICONTOG, IDPOIN, IFACE_, LABEL, MENU, NULL, NUM, NUMSLI, OPTION, PROP_BOOLEAN, PROP_COLLECTION, PROP_COLOR, PROP_COLOR_GAMMA, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_PERCENTAGE, PROP_POINTER, PROP_STRING, RNA_property_array_length(), RNA_property_collection_length(), RNA_property_pointer_get(), RNA_property_pointer_type(), RNA_property_subtype(), RNA_property_type(), RNA_struct_ui_icon(), TEX, PointerRNA::type, UI_BUT_DISABLED, uiButSetFlag(), uiDefBut(), uiDefButR_prop(), uiDefIconButR_prop(), and uiDefIconTextButR_prop().
Referenced by ANIM_channel_draw_widgets(), outliner_draw_rnabuts(), ui_item_array(), ui_item_with_label(), uiItemFullR(), and uiTemplateLayers().
int uiDefAutoButsRNA (uiLayout * layout, PointerRNA * ptr, int(*)(PointerRNA *, PropertyRNA *) check_prop, const char label_align)
Definition at line 133 of file interface_utils.c.
References assert, ELEM3, FALSE, NULL, PROP_BOOLEAN, PROP_ENUM_FLAG, PROP_HIDDEN, RNA_property_array_check(), RNA_property_flag(), RNA_property_type(), RNA_property_ui_name(), RNA_STRUCT_BEGIN, RNA_STRUCT_END, split(), uiItemFullR(), uiItemL(), uiLayoutColumn(), and uiLayoutSplit().
int uiIconFromID (ID * id)
Definition at line 191 of file interface_utils.c.
References Object::data, GS, ID_OB, ID::name, NULL, OB_EMPTY, RNA_id_pointer_create(), RNA_struct_ui_icon(), PointerRNA::type, Object::type, and uiIconFromID().
Referenced by object_mouse_select_menu(), and uiIconFromID().