Blender: btDbvtTreeCollider Struct Reference
btDbvtTreeCollider Struct Reference
Public Member Functions
btDbvtTreeCollider (btDbvtBroadphase *p)
void Process (const btDbvtNode *na, const btDbvtNode *nb)
void Process (const btDbvtNode *n)
Public Attributes
btDbvtBroadphase * pbp
btDbvtProxy * proxy
Detailed Description
Definition at line 92 of file btDbvtBroadphase.cpp.
Constructor & Destructor Documentation
btDbvtTreeCollider::btDbvtTreeCollider (btDbvtBroadphase * p) [inline]
Definition at line 96 of file btDbvtBroadphase.cpp.
Member Function Documentation
void btDbvtTreeCollider::Process (const btDbvtNode * na, const btDbvtNode * nb) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 97 of file btDbvtBroadphase.cpp.
References btOverlappingPairCallback::addOverlappingPair(), btSwap(), btDbvtNode::data, btDbvtBroadphase::m_newpairs, btDbvtBroadphase::m_paircache, and pbp.
Referenced by Process().
void btDbvtTreeCollider::Process (const btDbvtNode * n) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 111 of file btDbvtBroadphase.cpp.
References btDbvtProxy::leaf, Process(), and proxy.
Member Data Documentation
btDbvtBroadphase* btDbvtTreeCollider::pbp
Definition at line 94 of file btDbvtBroadphase.cpp.
Referenced by Process().
btDbvtProxy* btDbvtTreeCollider::proxy
Definition at line 95 of file btDbvtBroadphase.cpp.
Referenced by btDbvtBroadphase::collide(), btDbvtBroadphase::createProxy(), and Process().
The documentation for this struct was generated from the following file:
btDbvtBroadphase.cpp