Blender: cineonlib.h File Reference
cineonlib.h File Reference
Cineon
#include "logImageCore.h"
Typedefs
typedef struct _Log_Image_File_t_ CineonFile
Functions
void cineonSetVerbose (int)
CineonFile * cineonOpenFromMem (unsigned char *mem, unsigned int size)
CineonFile * cineonOpen (const char *filename)
int cineonGetSize (const CineonFile *cineon, int *xsize, int *ysize, int *channels)
CineonFile * cineonCreate (const char *filename, int xsize, int ysize, int channels)
int cineonIsMemFileCineon (unsigned char *mem)
int cineonGetRowBytes (CineonFile *cineon, unsigned short *row, int y)
int cineonSetRowBytes (CineonFile *cineon, const unsigned short *row, int y)
int cineonGetRow (CineonFile *cineon, unsigned short *row, int y)
int cineonSetRow (CineonFile *cineon, const unsigned short *row, int y)
void cineonClose (CineonFile *cineon)
Detailed Description
Definition in file cineonlib.h.
Typedef Documentation
typedef struct _Log_Image_File_t_ CineonFile
Definition at line 39 of file cineonlib.h.
Function Documentation
void cineonClose (CineonFile * cineon)
Definition at line 799 of file cineonlib.c.
References _Log_Image_File_t_::file, _Log_Image_File_t_::lineBuffer, and _Log_Image_File_t_::pixelBuffer.
Referenced by cineonCreate(), cineonOpen(), and cineonOpenFromMem().
CineonFile* cineonCreate (const char * filename, int xsize, int ysize, int channels)
Definition at line 715 of file cineonlib.c.
References _Log_Image_File_t_::bitsPerPixel, BLI_fopen(), cineonClose(), cineonSetRowBytes(), _Log_Image_File_t_::close, d_printf, _Log_Image_File_t_::depth, _Log_Image_File_t_::file, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::getRow, _Log_Image_File_t_::height, _Log_Image_File_t_::imageOffset, initCineonGenericHeader(), _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, logImageGetByteConversionDefaults(), _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, _Log_Image_File_t_::pixelBufferUsed, pixelsToLongs(), _Log_Image_File_t_::reading, _Log_Image_File_t_::setRow, setupLut(), verbose, and _Log_Image_File_t_::width.
Referenced by logImageCreate().
int cineonGetRow (CineonFile * cineon, unsigned short * row, int y)
Definition at line 428 of file cineonlib.c.
References d_printf, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, logimage_fread(), logimage_fseek(), and verbose.
int cineonGetRowBytes (CineonFile * cineon, unsigned short * row, int y)
Definition at line 322 of file cineonlib.c.
References d_printf, _Log_Image_File_t_::depth, LogImageByteConversionParameters::doLogarithm, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, logimage_fread(), logimage_fseek(), _Log_Image_File_t_::lut10_16, _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, verbose, and _Log_Image_File_t_::width.
Referenced by cineonOpen(), and cineonOpenFromMem().
int cineonGetSize (const CineonFile * cineon, int * xsize, int * ysize, int * channels)
Definition at line 707 of file cineonlib.c.
References _Log_Image_File_t_::depth, _Log_Image_File_t_::height, and _Log_Image_File_t_::width.
int cineonIsMemFileCineon (unsigned char * mem)
Definition at line 604 of file cineonlib.c.
References CINEON_FILE_MAGIC.
Referenced by imb_is_cineon().
CineonFile* cineonOpen (const char * filename)
Definition at line 513 of file cineonlib.c.
References CineonChannelInformation::bits_per_pixel, _Log_Image_File_t_::bitsPerPixel, BLI_fopen(), CineonImageInformation::channel, CineonImageInformation::channels_per_image, CINEON_FILE_MAGIC, cineonClose(), cineonGetRowBytes(), _Log_Image_File_t_::close, d_printf, _Log_Image_File_t_::depth, _Log_Image_File_t_::file, CineonGenericHeader::fileInfo, _Log_Image_File_t_::fileYPos, CineonGenericHeader::formatInfo, _Log_Image_File_t_::getRow, _Log_Image_File_t_::height, CineonFileInformation::image_offset, CineonGenericHeader::imageInfo, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, CineonChannelInformation::lines_per_image, logimage_fread(), logimage_fseek(), logImageGetByteConversionDefaults(), CineonFileInformation::magic_num, _Log_Image_File_t_::membuffer, _Log_Image_File_t_::membuffersize, _Log_Image_File_t_::memcursor, CineonFormatInformation::packing, _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, _Log_Image_File_t_::pixelBufferUsed, CineonChannelInformation::pixels_per_line, pixelsToLongs(), _Log_Image_File_t_::reading, _Log_Image_File_t_::setRow, setupLut(), verbose, verboseMe(), and _Log_Image_File_t_::width.
Referenced by logImageOpen().
CineonFile* cineonOpenFromMem (unsigned char * mem, unsigned int size)
Definition at line 616 of file cineonlib.c.
References CineonChannelInformation::bits_per_pixel, _Log_Image_File_t_::bitsPerPixel, CineonImageInformation::channel, CineonImageInformation::channels_per_image, CINEON_FILE_MAGIC, cineonClose(), cineonGetRowBytes(), _Log_Image_File_t_::close, d_printf, _Log_Image_File_t_::depth, _Log_Image_File_t_::file, CineonGenericHeader::fileInfo, _Log_Image_File_t_::fileYPos, CineonGenericHeader::formatInfo, _Log_Image_File_t_::getRow, _Log_Image_File_t_::height, CineonFileInformation::image_offset, CineonGenericHeader::imageInfo, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, CineonChannelInformation::lines_per_image, logimage_fread(), logimage_fseek(), logImageGetByteConversionDefaults(), CineonFileInformation::magic_num, _Log_Image_File_t_::membuffer, _Log_Image_File_t_::membuffersize, _Log_Image_File_t_::memcursor, CineonFormatInformation::packing, _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, _Log_Image_File_t_::pixelBufferUsed, CineonChannelInformation::pixels_per_line, pixelsToLongs(), _Log_Image_File_t_::reading, _Log_Image_File_t_::setRow, setupLut(), size(), verbose, verboseMe(), and _Log_Image_File_t_::width.
Referenced by logImageOpenFromMem().
int cineonSetRow (CineonFile * cineon, const unsigned short * row, int y)
Definition at line 472 of file cineonlib.c.
References d_printf, _Log_Image_File_t_::file, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, logimage_fseek(), and verbose.
int cineonSetRowBytes (CineonFile * cineon, const unsigned short * row, int y)
Definition at line 379 of file cineonlib.c.
References d_printf, _Log_Image_File_t_::depth, LogImageByteConversionParameters::doLogarithm, _Log_Image_File_t_::file, _Log_Image_File_t_::fileYPos, _Log_Image_File_t_::imageOffset, _Log_Image_File_t_::lineBuffer, _Log_Image_File_t_::lineBufferLength, logimage_fseek(), _Log_Image_File_t_::lut16_16, _Log_Image_File_t_::params, _Log_Image_File_t_::pixelBuffer, verbose, and _Log_Image_File_t_::width.
Referenced by cineonCreate().
void cineonSetVerbose (int)
Definition at line 308 of file cineonlib.c.
References verbose.
Referenced by logImageSetVerbose().