Blender: sp_ienv.c File Reference
sp_ienv.c File Reference
opennl
#include "ssp_defs.h"
#include "util.h"
Functions
int sp_ienv (int ispec)
Detailed Description
Definition in file sp_ienv.c.
Function Documentation
int sp_ienv (int ispec)
Definition at line 13 of file sp_ienv.c.
References i, and xerbla_().
Referenced by __nlFactorize_SUPERLU(), scolumn_dfs(), sgssv(), sLUMemInit(), sLUWorkInit(), spanel_bmod(), sQuerySpace(), sSetRWork(), and StatInit().