Blender: UI_interface_icons.h File Reference
UI_interface_icons.h File Reference
Interface and Widgets
Classes
struct IconFile
Defines
#define ICON_DEFAULT_HEIGHT 16
#define ICON_DEFAULT_WIDTH 16
#define ICON_DEFAULT_HEIGHT_SCALE ((int)(UI_UNIT_Y * 0.8f))
#define ICON_DEFAULT_WIDTH_SCALE ((int)(UI_UNIT_X * 0.8f))
#define PREVIEW_DEFAULT_HEIGHT 96
Typedefs
typedef struct IconFile IconFile
Functions
void UI_icons_init (int first_dyn_id)
int UI_icon_get_width (int icon_id)
int UI_icon_get_height (int icon_id)
void UI_icon_draw (float x, float y, int icon_id)
void UI_icon_draw_preview (float x, float y, int icon_id)
void UI_icon_draw_preview_aspect (float x, float y, int icon_id, float aspect)
void UI_icon_draw_preview_aspect_size (float x, float y, int icon_id, float aspect, int size)
void UI_icon_draw_aspect (float x, float y, int icon_id, float aspect, float alpha)
void UI_icon_draw_aspect_color (float x, float y, int icon_id, float aspect, const float rgb[3])
void UI_icon_draw_size (float x, float y, int size, int icon_id, float alpha)
void UI_icons_free (void)
void UI_icons_free_drawinfo (void *drawinfo)
struct ListBase * UI_iconfile_list (void)
int UI_iconfile_get_index (const char *filename)
Detailed Description
Definition in file UI_interface_icons.h.
Define Documentation
#define ICON_DEFAULT_HEIGHT 16
Definition at line 48 of file UI_interface_icons.h.
Referenced by get_draw_size(), icon_draw_size(), and UI_icon_get_height().
#define ICON_DEFAULT_HEIGHT_SCALE ((int)(UI_UNIT_Y * 0.8f))
Definition at line 51 of file UI_interface_icons.h.
Referenced by file_draw_list().
#define ICON_DEFAULT_WIDTH 16
Definition at line 49 of file UI_interface_icons.h.
Referenced by UI_icon_get_width().
#define ICON_DEFAULT_WIDTH_SCALE ((int)(UI_UNIT_X * 0.8f))
Definition at line 52 of file UI_interface_icons.h.
Referenced by ED_fileselect_init_layout(), and file_draw_list().
#define PREVIEW_DEFAULT_HEIGHT 96
Definition at line 54 of file UI_interface_icons.h.
Referenced by get_draw_size(), and preview_render_size().
Typedef Documentation
typedef struct IconFile IconFile
Function Documentation
void UI_icon_draw (float x, float y, int icon_id)
Definition at line 1157 of file interface_icons.c.
References UI_icon_draw_aspect().
Referenced by ANIM_channel_draw(), draw_marker(), draw_nla_channel_list_gl(), draw_view_icon(), outliner_draw_tree_element(), tselem_draw_icon(), and ui_searchbox_region_draw_cb().
void UI_icon_draw_aspect (float x, float y, int icon_id, float aspect, float alpha)
Definition at line 1146 of file interface_icons.c.
References icon_draw_at_size(), and ICON_SIZE_ICON.
Referenced by tselem_draw_icon_uibut(), ui_draw_menu_item(), UI_icon_draw(), widget_draw_icon(), and wm_drags_draw().
void UI_icon_draw_aspect_color (float x, float y, int icon_id, float aspect, const float rgb[3])
Definition at line 1151 of file interface_icons.c.
References FALSE, get_draw_size(), icon_draw_size(), and ICON_SIZE_ICON.
Referenced by widget_draw_icon().
void UI_icon_draw_preview (float x, float y, int icon_id)
Definition at line 1167 of file interface_icons.c.
References icon_draw_at_size(), and ICON_SIZE_PREVIEW.
void UI_icon_draw_preview_aspect (float x, float y, int icon_id, float aspect)
Definition at line 1172 of file interface_icons.c.
References icon_draw_at_size(), and ICON_SIZE_PREVIEW.
void UI_icon_draw_preview_aspect_size (float x, float y, int icon_id, float aspect, int size)
Definition at line 1177 of file interface_icons.c.
References FALSE, icon_draw_size(), ICON_SIZE_PREVIEW, NULL, and TRUE.
Referenced by widget_draw_preview().
void UI_icon_draw_size (float x, float y, int size, int icon_id, float alpha)
Definition at line 1162 of file interface_icons.c.
References FALSE, icon_draw_size(), ICON_SIZE_ICON, NULL, and TRUE.
int UI_icon_get_height (int icon_id)
Definition at line 778 of file interface_icons.c.
References BKE_icon_get(), Icon::drawinfo, G, G_DEBUG, icon_create_drawinfo(), ICON_DEFAULT_HEIGHT, if(), and NULL.
int UI_icon_get_width (int icon_id)
Definition at line 753 of file interface_icons.c.
References BKE_icon_get(), Icon::drawinfo, G, G_DEBUG, icon_create_drawinfo(), ICON_DEFAULT_WIDTH, if(), and NULL.
Referenced by widget_draw_text_icon().
int UI_iconfile_get_index (const char * filename)
Definition at line 691 of file interface_icons.c.
References BLI_path_cmp, IconFile::filename, ListBase::first, iconfilelist, IconFile::index, and IconFile::next.
struct ListBase* UI_iconfile_list (void) [read]
Definition at line 705 of file interface_icons.c.
References iconfilelist.
void UI_icons_free (void)
Definition at line 713 of file interface_icons.c.
References BKE_icons_free(), free_iconfile_list(), and IconTexture::id.
Referenced by ui_resources_free().
void UI_icons_free_drawinfo (void * drawinfo)
Definition at line 726 of file interface_icons.c.
References DrawInfo::buffer, DrawInfo::data, ICON_TYPE_BUFFER, MEM_freeN(), and DrawInfo::type.
Referenced by def_internal_icon(), and icon_draw_size().
void UI_icons_init (int first_dyn_id)
Definition at line 804 of file interface_icons.c.
References BKE_icons_init(), init_brush_icons(), init_iconfile_list(), and init_internal_icons().
Referenced by ui_resources_init().