Blender: AUD_EnvelopeFactory Class Reference
AUD_EnvelopeFactory Class Reference
#include <AUD_EnvelopeFactory.h>
Public Member Functions
AUD_EnvelopeFactory (AUD_Reference< AUD_IFactory > factory, float attack, float release, float threshold, float arthreshold)
virtual AUD_Reference
< AUD_IReader > createReader ()
Static Public Member Functions
static sample_t envelopeFilter (AUD_CallbackIIRFilterReader *reader, EnvelopeParameters *param)
static void endEnvelopeFilter (EnvelopeParameters *param)
Detailed Description
This factory creates an envelope follower reader.
Definition at line 40 of file AUD_EnvelopeFactory.h.
Constructor & Destructor Documentation
AUD_EnvelopeFactory::AUD_EnvelopeFactory (AUD_Reference< AUD_IFactory > factory, float attack, float release, float threshold, float arthreshold)
Creates a new envelope factory.
Parameters:
factory The input factory.
attack The attack value in seconds.
release The release value in seconds.
threshold The threshold value.
arthreshold The attack/release threshold value.
Definition at line 57 of file AUD_EnvelopeFactory.cpp.
Member Function Documentation
AUD_Reference< AUD_IReader > AUD_EnvelopeFactory::createReader () [virtual]
Creates a reader for playback of the sound source.
Returns:
A pointer to an AUD_IReader object or NULL if there has been an error.
Exceptions:
AUD_Exception An exception may be thrown if there has been a more unexpected error during reader creation.
Implements AUD_IFactory.
Definition at line 68 of file AUD_EnvelopeFactory.cpp.
References EnvelopeParameters::arthreshold, EnvelopeParameters::attack, endEnvelopeFilter(), envelopeFilter(), AUD_EffectFactory::getReader(), pow(), EnvelopeParameters::release, and EnvelopeParameters::threshold.
void AUD_EnvelopeFactory::endEnvelopeFilter (EnvelopeParameters * param) [static]
Definition at line 52 of file AUD_EnvelopeFactory.cpp.
Referenced by createReader().
sample_t AUD_EnvelopeFactory::envelopeFilter (AUD_CallbackIIRFilterReader * reader, EnvelopeParameters * param) [static]
Definition at line 43 of file AUD_EnvelopeFactory.cpp.
References EnvelopeParameters::attack, fabs(), EnvelopeParameters::release, AUD_BaseIIRFilterReader::x(), and AUD_BaseIIRFilterReader::y().
Referenced by createReader().
The documentation for this class was generated from the following files:
AUD_EnvelopeFactory.h
AUD_EnvelopeFactory.cpp