Blender: kernel_emission.h File Reference
kernel_emission.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device float3 direct_emissive_eval (KernelGlobals *kg, float rando, LightSample *ls, float u, float v, float3 I)
__device bool direct_emission (KernelGlobals *kg, ShaderData *sd, int lindex, float randt, float rando, float randu, float randv, Ray *ray, BsdfEval *eval, bool *is_lamp)
__device float3 indirect_emission (KernelGlobals *kg, ShaderData *sd, float t, int path_flag, float bsdf_pdf)
__device float3 indirect_background (KernelGlobals *kg, Ray *ray, int path_flag, float bsdf_pdf)
Function Documentation
__device bool direct_emission (KernelGlobals * kg, ShaderData * sd, int lindex, float randt, float rando, float randu, float randv, Ray * ray, BsdfEval * eval, bool * is_lamp)
Definition at line 62 of file kernel_emission.h.
References bsdf_eval_is_zero(), bsdf_eval_mul(), Ray::D, LightSample::D, direct_emissive_eval(), dot(), FLT_MAX, is_zero(), LIGHT_BACKGROUND, light_sample(), light_sample_pdf(), light_select(), M_1_PI_F, ShaderData::Ng, LightSample::Ng, normalize_len(), Ray::P, LightSample::P, ShaderData::P, power_heuristic(), LightSample::prim, ray_offset(), LightSample::shader, SHADER_AREA_LIGHT, shader_bsdf_eval(), SHADER_CAST_SHADOW, LightSample::t, Ray::t, and LightSample::type.
Referenced by kernel_path_integrate().
CCL_NAMESPACE_BEGIN __device float3 direct_emissive_eval (KernelGlobals * kg, float rando, LightSample * ls, float u, float v, float3 I)
Definition at line 23 of file kernel_emission.h.
References Ray::D, LightSample::D, Ray::dP, differential3::dx, differential3::dy, ShaderData::flag, LIGHT_BACKGROUND, make_float3(), ShaderData::Ng, LightSample::Ng, LightSample::object, Ray::P, LightSample::P, LightSample::prim, SD_EMISSION, LightSample::shader, shader_emissive_eval(), shader_eval_background(), shader_eval_surface(), shader_release(), shader_setup_from_background(), shader_setup_from_sample(), and LightSample::type.
Referenced by direct_emission().
__device float3 indirect_background (KernelGlobals * kg, Ray * ray, int path_flag, float bsdf_pdf)
Definition at line 165 of file kernel_emission.h.
References background_light_pdf(), Ray::D, kernel_data, L, make_float3(), PATH_RAY_MIS_SKIP, power_heuristic(), shader_eval_background(), shader_release(), and shader_setup_from_background().
Referenced by kernel_path_integrate().
__device float3 indirect_emission (KernelGlobals * kg, ShaderData * sd, float t, int path_flag, float bsdf_pdf)
Definition at line 146 of file kernel_emission.h.
References ShaderData::flag, ShaderData::I, L, ShaderData::Ng, PATH_RAY_MIS_SKIP, power_heuristic(), SD_SAMPLE_AS_LIGHT, shader_emissive_eval(), and triangle_light_pdf().
Referenced by kernel_path_integrate().