Blender: node_shader_curves.c File Reference
node_shader_curves.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_exec_curve_vec (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_shader_init_curve_vec (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int gpu_shader_curve_vec (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_curve_vec (bNodeTreeType *ttype)
static void node_shader_exec_curve_rgb (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_shader_init_curve_rgb (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static int gpu_shader_curve_rgb (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_curve_rgb (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_curve_vec_in []
static bNodeSocketTemplate sh_node_curve_vec_out []
static bNodeSocketTemplate sh_node_curve_rgb_in []
static bNodeSocketTemplate sh_node_curve_rgb_out []
Detailed Description
Definition in file node_shader_curves.c.
Function Documentation
static int gpu_shader_curve_rgb (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 119 of file node_shader_curves.c.
References curvemapping_table_RGBA(), GPU_stack_link(), GPU_texture(), size(), and bNode::storage.
Referenced by register_node_type_sh_curve_rgb().
static int gpu_shader_curve_vec (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 63 of file node_shader_curves.c.
References curvemapping_table_RGBA(), GPU_stack_link(), GPU_texture(), size(), and bNode::storage.
Referenced by register_node_type_sh_curve_vec().
static void node_shader_exec_curve_rgb (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 101 of file node_shader_curves.c.
References curvemapping_evaluateRGBF(), interp_v3_v3v3(), nodestack_get_vec(), SOCK_VECTOR, bNode::storage, and bNodeStack::vec.
Referenced by register_node_type_sh_curve_rgb().
static void node_shader_exec_curve_vec (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 48 of file node_shader_curves.c.
References curvemapping_evaluate3F(), nodestack_get_vec(), SOCK_VECTOR, bNode::storage, and bNodeStack::vec.
Referenced by register_node_type_sh_curve_vec().
static void node_shader_init_curve_rgb (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 114 of file node_shader_curves.c.
References curvemapping_add(), and bNode::storage.
Referenced by register_node_type_sh_curve_rgb().
static void node_shader_init_curve_vec (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 58 of file node_shader_curves.c.
References curvemapping_add(), and bNode::storage.
Referenced by register_node_type_sh_curve_vec().
void register_node_type_sh_curve_rgb (bNodeTreeType * ttype)
Definition at line 127 of file node_shader_curves.c.
References gpu_shader_curve_rgb(), NODE_CLASS_OP_COLOR, node_copy_curves(), node_free_curves(), NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_curve_rgb(), node_shader_init_curve_rgb(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_CURVE_RGB.
Referenced by registerShaderNodes().
void register_node_type_sh_curve_vec (bNodeTreeType * ttype)
Definition at line 72 of file node_shader_curves.c.
References gpu_shader_curve_vec(), NODE_CLASS_OP_VECTOR, node_copy_curves(), node_free_curves(), NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_curve_vec(), node_shader_init_curve_vec(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), and SH_NODE_CURVE_VEC.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_curve_rgb_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",   1.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_FACTOR},
    {   SOCK_RGBA, 1, "Color",  0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 90 of file node_shader_curves.c.
bNodeSocketTemplate sh_node_curve_rgb_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 96 of file node_shader_curves.c.
bNodeSocketTemplate sh_node_curve_vec_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Fac",   1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   SOCK_VECTOR, 1, "Vector",   0.0f, 0.0f, 0.0f, 1.0f, -1.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_shader_curves.c.
bNodeSocketTemplate sh_node_curve_vec_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Vector"},
    {   -1, 0, ""   }
}
Definition at line 43 of file node_shader_curves.c.