Blender: CCGAllocatorIFC Struct Reference
CCGAllocatorIFC Struct Reference
#include <CCGSubSurf.h>
Public Attributes
void *(* alloc)(CCGAllocatorHDL a, int numBytes)
void *(* realloc)(CCGAllocatorHDL a, void *ptr, int newSize, int oldSize)
void(* free)(CCGAllocatorHDL a, void *ptr)
void(* release)(CCGAllocatorHDL a)
Detailed Description
Definition at line 26 of file CCGSubSurf.h.
Member Data Documentation
void*(* CCGAllocatorIFC::alloc)(CCGAllocatorHDL a, int numBytes)
Definition at line 27 of file CCGSubSurf.h.
Referenced by _ehash_new(), _getStandardAllocatorIFC(), _getSubSurf(), and ccgSubSurf_new().
void(* CCGAllocatorIFC::free)(CCGAllocatorHDL a, void *ptr)
Definition at line 29 of file CCGSubSurf.h.
Referenced by _getStandardAllocatorIFC(), and _getSubSurf().
void*(* CCGAllocatorIFC::realloc)(CCGAllocatorHDL a, void *ptr, int newSize, int oldSize)
Definition at line 28 of file CCGSubSurf.h.
Referenced by _getStandardAllocatorIFC(), and _getSubSurf().
void(* CCGAllocatorIFC::release)(CCGAllocatorHDL a)
Definition at line 30 of file CCGSubSurf.h.
Referenced by _getStandardAllocatorIFC(), _getSubSurf(), and ccgSubSurf_free().
The documentation for this struct was generated from the following file:
CCGSubSurf.h