Blender: btSoftColliders::CollideCL_SS Struct Reference
btSoftColliders::CollideCL_SS Struct Reference
#include <btSoftBodyInternals.h>
Public Member Functions
void Process (const btDbvtNode *la, const btDbvtNode *lb)
void Process (btSoftBody *psa, btSoftBody *psb)
Public Attributes
btSoftBody * bodies [2]
Detailed Description
Definition at line 777 of file btSoftBodyInternals.h.
Member Function Documentation
void btSoftColliders::CollideCL_SS::Process (const btDbvtNode * la, const btDbvtNode * lb) [inline]
Reimplemented from btDbvt::ICollide.
Definition at line 780 of file btSoftBodyInternals.h.
References btAlignedAlloc, btMax(), btDbvtNode::data, btTransform::getIdentity(), btSoftBody::Cluster::m_clusterIndex, btSoftBody::Cluster::m_com, btSoftBody::Joint::m_erp, btSoftBody::Joint::m_split, and btGjkEpaSolver2::SignedDistance().
Referenced by btSoftBody::defaultCollisionHandler().
void btSoftColliders::CollideCL_SS::Process (btSoftBody * psa, btSoftBody * psb) [inline]
Definition at line 818 of file btSoftBodyInternals.h.
References btMin(), btDbvt::collideTT(), btSoftBody::m_cdbvt, btSoftBody::m_cfg, btDbvt::m_root, and btSoftBody::m_sst.
Member Data Documentation
btSoftBody* btSoftColliders::CollideCL_SS::bodies[2]
Definition at line 779 of file btSoftBodyInternals.h.
The documentation for this struct was generated from the following file:
btSoftBodyInternals.h