Blender: EdgeDice Class Reference
EdgeDice Class Reference
#include <subd_dice.h>
Public Member Functions
EdgeDice (Mesh *mesh, int shader, bool smooth, float dicing_rate)
void reserve (int num_verts, int num_tris)
int add_vert (Patch *patch, float2 uv)
void add_triangle (int v0, int v1, int v2)
void stitch_triangles (vector< int > &outer, vector< int > &inner)
Public Attributes
Camera * camera
Mesh * mesh
float3 * mesh_P
float3 * mesh_N
float dicing_rate
size_t vert_offset
size_t tri_offset
int shader
bool smooth
Detailed Description
Definition at line 38 of file subd_dice.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN EdgeDice::EdgeDice (Mesh * mesh, int shader, bool smooth, float dicing_rate)
Definition at line 31 of file subd_dice.cpp.
References AttributeSet::add(), Mesh::attributes, camera, dicing_rate, mesh, mesh_N, mesh_P, NULL, shader, smooth, Attribute::STD_VERTEX_NORMAL, and vert_offset.
Member Function Documentation
void EdgeDice::add_triangle (int v0, int v1, int v2)
Definition at line 73 of file subd_dice.cpp.
References Mesh::add_triangle(), mesh, shader, and smooth.
Referenced by QuadDice::add_grid(), TriangleDice::add_grid(), and stitch_triangles().
int EdgeDice::add_vert (Patch * patch, float2 uv)
Definition at line 58 of file subd_dice.cpp.
References assert, cross(), Patch::eval(), mesh_N, mesh_P, N, normalize(), P(), vert_offset, float2::x, and float2::y.
void EdgeDice::reserve (int num_verts, int num_tris)
Definition at line 45 of file subd_dice.cpp.
References AttributeSet::add(), Mesh::attributes, Attribute::data_float3(), mesh, mesh_N, mesh_P, Mesh::reserve(), Attribute::STD_VERTEX_NORMAL, tri_offset, Mesh::triangles, vert_offset, and Mesh::verts.
void EdgeDice::stitch_triangles (vector< int > & outer, vector< int > & inner)
Definition at line 78 of file subd_dice.cpp.
References add_triangle(), i, len(), and mesh_P.
Referenced by TriangleDice::add_grid(), and QuadDice::dice().
Member Data Documentation
Camera* EdgeDice::camera
Definition at line 40 of file subd_dice.h.
Referenced by EdgeDice(), QuadDice::eval_projected(), DiagSplit::split_quad(), and DiagSplit::split_triangle().
float EdgeDice::dicing_rate
Definition at line 44 of file subd_dice.h.
Referenced by EdgeDice(), and QuadDice::scale_factor().
Mesh* EdgeDice::mesh
Definition at line 41 of file subd_dice.h.
Referenced by add_triangle(), TriangleDice::dice(), QuadDice::dice(), EdgeDice(), and reserve().
float3* EdgeDice::mesh_N
Definition at line 43 of file subd_dice.h.
Referenced by add_vert(), EdgeDice(), and reserve().
float3* EdgeDice::mesh_P
Definition at line 42 of file subd_dice.h.
Referenced by add_vert(), EdgeDice(), reserve(), and stitch_triangles().
int EdgeDice::shader
Definition at line 47 of file subd_dice.h.
Referenced by add_triangle(), and EdgeDice().
bool EdgeDice::smooth
Definition at line 48 of file subd_dice.h.
Referenced by add_triangle(), and EdgeDice().
size_t EdgeDice::tri_offset
Definition at line 46 of file subd_dice.h.
Referenced by reserve().
size_t EdgeDice::vert_offset
Definition at line 45 of file subd_dice.h.
Referenced by add_vert(), TriangleDice::dice(), QuadDice::dice(), EdgeDice(), and reserve().
The documentation for this class was generated from the following files:
subd_dice.h
subd_dice.cpp