Blender: bmesh_mods.h File Reference
bmesh_mods.h File Reference
BMesh
#include <stdio.h>
Enumerations
enum { BM_EDGEROT_CHECK_EXISTS = (1 << 0), BM_EDGEROT_CHECK_SPLICE = (1 << 1), BM_EDGEROT_CHECK_DEGENERATE = (1 << 2), BM_EDGEROT_CHECK_BEAUTY = (1 << 3) }
Functions
int BM_vert_dissolve (BMesh *bm, BMVert *v)
Dissolve Vert.
int BM_disk_dissolve (BMesh *bm, BMVert *v)
BMFace * BM_faces_join_pair (BMesh *bm, BMFace *f1, BMFace *f2, BMEdge *e, const short do_del)
Faces Join Pair.
BMEdge * BM_verts_connect (BMesh *bm, BMVert *v1, BMVert *v2, BMFace **r_f)
Connect Verts, Split Face.
BMFace * BM_face_split (BMesh *bm, BMFace *f, BMVert *v1, BMVert *v2, BMLoop **r_l, BMEdge *example, const short nodouble)
Face Split.
BMFace * BM_face_split_n (BMesh *bm, BMFace *f, BMVert *v1, BMVert *v2, float cos[][3], int n, BMLoop **r_l, BMEdge *example)
Face Split with intermediate points.
BMEdge * BM_vert_collapse_faces (BMesh *bm, BMEdge *ke, BMVert *kv, float fac, const short join_faces, const short kill_degenerate_faces)
Vert Collapse Faces.
BMEdge * BM_vert_collapse_edge (BMesh *bm, BMEdge *ke, BMVert *kv, const short kill_degenerate_faces)
Vert Collapse Faces.
BMVert * BM_edge_split (BMesh *bm, BMEdge *e, BMVert *v, BMEdge **r_e, float percent)
Edge Split.
BMVert * BM_edge_split_n (BMesh *bm, BMEdge *e, int numcuts)
Split an edge multiple times evenly.
int BM_face_validate (BMFace *face, FILE *err)
void BM_edge_calc_rotate (BMEdge *e, int ccw, BMLoop **r_l1, BMLoop **r_l2)
int BM_edge_rotate_check (BMEdge *e)
Check if Rotate Edge is OK.
int BM_edge_rotate_check_degenerate (BMEdge *e, BMLoop *l1, BMLoop *l2)
Check if Edge Rotate Gives Degenerate Faces.
int BM_edge_rotate_check_beauty (BMEdge *e, BMLoop *l1, BMLoop *l2)
BMEdge * BM_edge_rotate (BMesh *bm, BMEdge *e, const short ccw, const short check_flag)
Rotate Edge.
BMVert * BM_face_vert_separate (BMesh *bm, BMFace *sf, BMVert *sv)
Rip a single face from a vertex fan.
BMVert * BM_face_loop_separate (BMesh *bm, BMLoop *sl)
Rip a single face from a vertex fan.
Detailed Description
Definition in file bmesh_mods.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
BM_EDGEROT_CHECK_EXISTS
BM_EDGEROT_CHECK_SPLICE
BM_EDGEROT_CHECK_DEGENERATE
BM_EDGEROT_CHECK_BEAUTY
Definition at line 72 of file bmesh_mods.h.
Function Documentation
int BM_disk_dissolve (BMesh * bm, BMVert * v)
dissolves all faces around a vert, and removes it.
disabled for testing why bad things happen
Definition at line 105 of file bmesh_mods.c.
References BM_disk_dissolve(), BM_edge_share_face_count(), BM_face_split(), BM_faces_join_pair(), BM_vert_collapse_faces(), BM_vert_is_manifold(), bmesh_disk_edge_next(), bmesh_radial_length(), BMVert::e, BMLoop::f, FALSE, BMEdge::l, len(), BMLoop::next, NULL, BMLoop::radial_next, TRUE, and BMLoop::v.
Referenced by BM_disk_dissolve(), and BM_vert_dissolve().
void BM_edge_calc_rotate (BMEdge * e, int ccw, BMLoop ** r_l1, BMLoop ** r_l2)
Calculate the 2 loops which _would_ make up the newly rotated Edge but don't actually change anything.
Use this to further inspect if the loops to be connected have issues:
Examples:
the newly formed edge already exists
the new face would be degenerate (zero area / concave / bow-tie)
may want to measure if the new edge gives improved results topology. over the old one, as with beauty fill.
Note:
BM_edge_rotate_check must have already run.
Definition at line 819 of file bmesh_mods.c.
References BLI_assert, BM_edge_face_pair(), BM_edge_ordered_verts(), BM_edge_rotate_check(), BM_face_other_vert_loop(), fb(), SWAP, and TRUE.
Referenced by BM_edge_rotate().
BMEdge* BM_edge_rotate (BMesh * bm, BMEdge * e, const short ccw, const short check_flag)
Rotate Edge.
Spins an edge topologically, either counter-clockwise or clockwise depending on ccw.
Returns:
The spun edge, NULL on error (e.g., if the edge isn't surrounded by exactly two faces).
Note:
This works by dissolving the edge then re-creating it, so the returned edge won't have the same pointer address as the original one.
See also:
header definition for check_flag enum.
Definition at line 1005 of file bmesh_mods.c.
References BM_edge_calc_rotate(), BM_edge_create(), BM_edge_exists(), BM_edge_face_pair(), BM_edge_rotate_check(), BM_edge_rotate_check_beauty(), BM_edge_rotate_check_degenerate(), BM_EDGEROT_CHECK_BEAUTY, BM_EDGEROT_CHECK_DEGENERATE, BM_EDGEROT_CHECK_EXISTS, BM_EDGEROT_CHECK_SPLICE, BM_face_split(), BM_faces_join_pair(), BMLoop::f, fb(), BMFace::head, BMHeader::hflag, NULL, TRUE, and BMLoop::v.
Referenced by bmo_beautify_fill_exec(), bmo_edgerotate_exec(), and bpy_bm_utils_edge_rotate().
int BM_edge_rotate_check (BMEdge * e)
Check if Rotate Edge is OK.
Quick check to see if we could rotate the edge, use this to avoid calling exceptions on common cases.
Definition at line 852 of file bmesh_mods.c.
References BM_edge_face_pair(), BM_face_other_vert_loop(), FALSE, fb(), TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by BM_edge_calc_rotate(), BM_edge_rotate(), BM_edge_rotate_check_degenerate(), and bmo_edgerotate_exec().
int BM_edge_rotate_check_beauty (BMEdge * e, BMLoop * l1, BMLoop * l2)
Definition at line 981 of file bmesh_mods.c.
References BMVert::co, len_squared_v3v3(), BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by BM_edge_rotate().
int BM_edge_rotate_check_degenerate (BMEdge * e, BMLoop * l1, BMLoop * l2)
Check if Edge Rotate Gives Degenerate Faces.
Check 2 cases 1) does the newly forms edge form a flipped face (compare with previous cross product) 2) does the newly formed edge cause a zero area corner (or close enough to be almost zero)
Parameters:
l1,l2 are the loops of the proposed verts to rotate too and should be the result of calling BM_edge_calc_rotate
Definition at line 893 of file bmesh_mods.c.
References BLI_assert, BM_edge_exists(), BM_edge_ordered_verts(), BM_edge_rotate_check(), BM_face_other_vert_loop(), BMVert::co, cross_v3_v3v3(), dot_v3v3(), BMLoop::f, FALSE, negate_v3_v3(), normalize_v3(), sub_v3_v3v3(), TRUE, and BMLoop::v.
Referenced by BM_edge_rotate().
BMVert* BM_edge_split (BMesh * bm, BMEdge * e, BMVert * v, BMEdge ** r_e, float percent)
Edge Split.
Splits an edge. v should be one of the vertices in e and defines the "from" end of the splitting operation: the new vertex will be percent of the way from v to the other end. The newly created edge is attached to v and is returned in r_e. The original edge e will be the other half of the split.
Returns:
The new vert
Definition at line 630 of file bmesh_mods.c.
References BLI_array_append, BLI_array_count, BLI_array_free, BLI_array_staticdeclare, BLI_assert, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_release(), BM_data_interp_face_vert_edge(), BM_data_interp_from_verts(), BM_elem_attrs_copy(), BM_face_copy(), BM_FACE_FIRST_LOOP, BM_face_multires_bounds_smooth(), BM_face_verts_kill(), BM_loop_interp_multires(), BMESH_ASSERT, bmesh_edge_other_vert_get(), bmesh_semv(), CD_MDISPS, BMVert::co, CustomData_has_layer(), BMLoop::f, hash, BMEdge::head, BMHeader::hflag, i, BMEdge::l, BMesh::ldata, madd_v3_v3v3fl(), BMLoop::next, NULL, BMLoop::radial_next, sub_v3_v3v3(), TRUE, and UNLIKELY.
Referenced by BM_edge_split_n(), bm_subdivide_edge_addvert(), BME_bevel_split_edge(), bpy_bm_utils_edge_split(), and knife_make_cuts().
BMVert* BM_edge_split_n (BMesh * bm, BMEdge * e, int numcuts)
Split an edge multiple times evenly.
Definition at line 745 of file bmesh_mods.c.
References BM_edge_split(), i, NULL, and BMEdge::v2.
BMVert* BM_face_loop_separate (BMesh * bm, BMLoop * sl)
Rip a single face from a vertex fan.
Note:
same as BM_face_vert_separate but faster (avoids a loop lookup)
Definition at line 1101 of file bmesh_mods.c.
References bmesh_urmv_loop().
Referenced by bpy_bm_utils_face_vert_separate(), and bpy_bm_utils_loop_separate().
BMFace* BM_face_split (BMesh * bm, BMFace * f, BMVert * v1, BMVert * v2, BMLoop ** r_l, BMEdge * example, const short nodouble)
Face Split.
Split a face along two vertices. returns the newly made face, and sets the r_l member to a loop in the newly created edge.
Parameters:
bm The bmesh
f the original face
v1,v2 vertices which define the split edge, must be different
r_l pointer which will receive the BMLoop for the split edge in the new face
example Edge used for attributes of splitting edge, if non-NULL
nodouble Use an existing edge if found
Returns:
Pointer to the newly created face representing one side of the split if the split is successful (and the original original face will be the other side). NULL if the split fails.
Definition at line 327 of file bmesh_mods.c.
References BLI_assert, BM_elem_attrs_copy(), BM_face_copy(), BM_FACE_FIRST_LOOP, BM_face_kill(), BM_face_multires_bounds_smooth(), BM_loop_interp_from_face(), bmesh_sfme(), CD_MDISPS, copy_v3_v3(), CustomData_has_layer(), FALSE, BMesh::ldata, BMLoop::next, BMFace::no, NULL, and TRUE.
Referenced by BM_disk_dissolve(), BM_edge_rotate(), BM_face_triangulate(), BM_vert_collapse_faces(), BM_verts_connect(), BME_bevel_edge(), BME_bevel_mesh(), BME_bevel_vert(), bmo_connectverts_exec(), bmo_esubd_exec(), bpy_bm_utils_face_split(), connect_smallest_face(), knife_make_chain_cut(), and remdoubles_splitface().
BMFace* BM_face_split_n (BMesh * bm, BMFace * f, BMVert * v1, BMVert * v2, float cos[][3], int n, BMLoop ** r_l, BMEdge * example)
Face Split with intermediate points.
Like BM_face_split, but with an edge split by n intermediate points with given coordinates.
Parameters:
bm The bmesh
f the original face
v1,v2 vertices which define the split edge, must be different
co Array of coordinates for intermediate points
n Length of cos (must be > 0)
r_l pointer which will receive the BMLoop for the first split edge (from v1) in the new face
example Edge used for attributes of splitting edge, if non-NULL
Returns:
Pointer to the newly created face representing one side of the split if the split is successful (and the original original face will be the other side). NULL if the split fails.
Definition at line 395 of file bmesh_mods.c.
References BLI_assert, BM_elem_attrs_copy(), BM_face_copy(), BM_face_verts_kill(), BM_loop_interp_from_face(), bmesh_semv(), bmesh_sfme(), BMVert::co, copy_v3_v3(), FALSE, i, BMEdge::l, BMFace::no, NULL, BMLoop::radial_next, TRUE, and BMLoop::v.
Referenced by bpy_bm_utils_face_split(), and knife_make_chain_cut().
int BM_face_validate (BMFace * face, FILE * err)
Checks if a face is valid in the data structure
Definition at line 761 of file bmesh_mods.c.
References BLI_array_declare, BLI_array_free, BLI_array_growitems, BM_ITER_ELEM_INDEX, BM_LOOPS_OF_FACE, BMLoop::e, i, BMFace::len, NULL, BMLoop::v, BMEdge::v1, BMEdge::v2, and Mesh::verts.
BMVert* BM_face_vert_separate (BMesh * bm, BMFace * sf, BMVert * sv)
Rip a single face from a vertex fan.
Definition at line 1091 of file bmesh_mods.c.
References bmesh_urmv().
Referenced by edbm_rip_invoke__vert().
BMFace* BM_faces_join_pair (BMesh * bm, BMFace * f1, BMFace * f2, BMEdge * e, const short do_del)
Faces Join Pair.
Joins two adjacent faces together.
Because this method calls to BM_faces_join to do its work, if a pair of faces share multiple edges, the pair of faces will be joined at every edge (not just edge e). This part of the functionality might need to be reconsidered.
If the windings do not match the winding of the new face will follow f1's winding (i.e. f2 will be reversed before the join).
Returns:
pointer to the combined face
Definition at line 227 of file bmesh_mods.c.
References BM_FACE_FIRST_LOOP, BM_faces_join(), BMESH_ASSERT, bmesh_loop_reverse(), BMLoop::e, BMLoop::f, BMEdge::l, BMLoop::next, NULL, BMLoop::radial_next, UNLIKELY, and BMLoop::v.
Referenced by BM_disk_dissolve(), BM_edge_rotate(), BME_bevel_mesh(), bmo_dissolve_edgeloop_exec(), bmo_dissolve_edges_exec(), bmo_dissolve_limit_exec(), and bmo_join_triangles_exec().
BMEdge* BM_vert_collapse_edge (BMesh * bm, BMEdge * ke, BMVert * kv, const short kill_degenerate_faces)
Vert Collapse Faces.
Collapses a vertex onto another vertex it shares an edge with.
Returns:
The New Edge
Definition at line 583 of file bmesh_mods.c.
References BM_edge_other_vert(), BM_vert_collapse_faces(), bmesh_disk_edge_next(), bmesh_edge_other_vert_get(), bmesh_jekv(), FALSE, and NULL.
Referenced by BM_vert_dissolve(), BME_Bevel_Dissolve_Disk(), BME_bevel_edge(), bmo_dissolve_edgeloop_exec(), bmo_dissolve_edges_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_limit_exec(), bmo_dissolve_verts_exec(), and bpy_bm_utils_vert_collapse_edge().
BMEdge* BM_vert_collapse_faces (BMesh * bm, BMEdge * ke, BMVert * kv, float fac, const short join_faces, const short kill_degenerate_faces)
Vert Collapse Faces.
Collapses vertex kv that has only two manifold edges onto a vertex it shares an edge with. fac defines the amount of interpolation for Custom Data.
Note:
that this is not a general edge collapse function.
this function is very close to BM_vert_collapse_edge, both collapse a vertex and return a new edge. Except this takes a factor and merges custom data.
BMESH_TODO: Insert error checking for KV valance.
Parameters:
bm The bmesh
ke The edge to collapse
kv The vertex to collapse into the edge
fac The factor along the edge
join_faces When true the faces around the vertex will be joined otherwise collapse the vertex by merging the 2 edges this vert touches into one.
kill_degenerate_faces Removes faces with less than 3 verts after collapsing.
Returns:
The New Edge
Definition at line 476 of file bmesh_mods.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_pop, BLI_array_staticdeclare, BLI_assert, BM_data_interp_from_verts(), BM_edge_other_vert(), BM_face_kill(), BM_face_split(), BM_faces_join(), BM_FACES_OF_VERT, BM_ITER_ELEM, bmesh_disk_count(), bmesh_disk_edge_next(), bmesh_edge_other_vert_get(), bmesh_jekv(), CustomData_bmesh_interp(), BMHeader::data, BMLoop::e, FALSE, BMLoop::head, i, BMEdge::l, BMesh::ldata, BMFace::len, BMLoop::next, NULL, BMLoop::radial_next, TRUE, BMLoop::v, BMEdge::v1, BMEdge::v2, and Mesh::verts.
Referenced by BM_disk_dissolve(), BM_vert_collapse_edge(), bmo_dissolve_verts_exec(), and bpy_bm_utils_vert_collapse_faces().
int BM_vert_dissolve (BMesh * bm, BMVert * v)
Dissolve Vert.
Turns the face region surrounding a manifold vertex into a single polygon.
Example:
+---------+ +---------+ | \ / | | | Before: | v | After: | | | / \ | | | +---------+ +---------+
This function can also collapse edges too in cases when it cant merge into faces.
Example:
Before: +----v----+ After: +---------+
Note:
dissolves vert, in more situations then BM_disk_dissolve (e.g. if the vert is part of a wire edge, etc).
Definition at line 66 of file bmesh_mods.c.
References BM_disk_dissolve(), BM_vert_collapse_edge(), BM_vert_edge_count(), BM_vert_face_count(), BM_vert_is_manifold(), BM_vert_kill(), BMVert::e, FALSE, BMEdge::l, len(), NULL, and TRUE.
Referenced by bmo_dissolve_verts_exec(), and bpy_bm_utils_vert_dissolve().
BMEdge* BM_verts_connect (BMesh * bm, BMVert * v1, BMVert * v2, BMFace ** r_f)
Connect Verts, Split Face.
connects two verts together, automatically (if very naively) finding the face they both share (if there is one) and splitting it. Use this at your own risk, as it doesn't handle the many complex cases it should (like zero-area faces, multiple faces, etc).
this is really only meant for cases where you don't know before hand the face the two verts belong to for splitting (e.g. the subdivision operator).
Returns:
The newly created edge.
Definition at line 281 of file bmesh_mods.c.
References BM_face_split(), BM_FACES_OF_VERT, BM_ITER_ELEM, BMLoop::e, FALSE, and NULL.