Blender: SVMShaderManager Class Reference
SVMShaderManager Class Reference
#include <svm.h>
Public Member Functions
SVMShaderManager ()
~SVMShaderManager ()
void device_update (Device *device, DeviceScene *dscene, Scene *scene, Progress &progress)
void device_free (Device *device, DeviceScene *dscene)
Detailed Description
Definition at line 43 of file render/svm.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN SVMShaderManager::SVMShaderManager ()
Definition at line 35 of file svm.cpp.
SVMShaderManager::~SVMShaderManager ()
Definition at line 39 of file svm.cpp.
Member Function Documentation
void SVMShaderManager::device_free (Device * device, DeviceScene * dscene) [virtual]
Implements ShaderManager.
Definition at line 95 of file svm.cpp.
References device_vector< T >::clear(), ShaderManager::device_free_common(), DeviceScene::svm_nodes, and Device::tex_free().
Referenced by device_update().
void SVMShaderManager::device_update (Device * device, DeviceScene * dscene, Scene * scene, Progress & progress) [virtual]
Implements ShaderManager.
Definition at line 43 of file svm.cpp.
References DeviceInfo::advanced_shading, assert, SVMCompiler::background, SVMCompiler::compile(), device_vector< T >::copy(), DeviceScene::data, Scene::default_background, device_free(), ShaderManager::device_update_common(), Progress::get_cancel(), Shader::graph, Shader::has_surface_emission, i, Scene::image_manager, Device::info, Scene::light_manager, make_int4(), Shader::need_update, LightManager::need_update, ShaderManager::need_update, NODE_SHADER_JUMP, NULL, Shader::sample_as_light, Scene::shader_manager, Scene::shaders, KernelData::sunsky, SVMCompiler::sunsky, DeviceScene::svm_nodes, and Device::tex_alloc().
The documentation for this class was generated from the following files:
render/svm.h
svm.cpp