Blender: AshikhminVelvetClosure Class Reference
AshikhminVelvetClosure Class Reference
Public Member Functions
AshikhminVelvetClosure ()
void setup ()
bool mergeable (const ClosurePrimitive *other) const
size_t memsize () const
const char * name () const
void print_on (std::ostream &out) const
float albedo (const Vec3 &omega_out) const
Color3 eval_reflect (const Vec3 &omega_out, const Vec3 &omega_in, float &pdf) const
Color3 eval_transmit (const Vec3 &omega_out, const Vec3 &omega_in, float &pdf) const
ustring sample (const Vec3 &Ng, const Vec3 &omega_out, const Vec3 &domega_out_dx, const Vec3 &domega_out_dy, float randu, float randv, Vec3 &omega_in, Vec3 &domega_in_dx, Vec3 &domega_in_dy, float &pdf, Color3 &eval) const
Public Attributes
Vec3 m_N
float m_sigma
float m_invsigma2
Detailed Description
Definition at line 43 of file bsdf_ashikhmin_velvet.cpp.
Constructor & Destructor Documentation
AshikhminVelvetClosure::AshikhminVelvetClosure () [inline]
Definition at line 49 of file bsdf_ashikhmin_velvet.cpp.
Member Function Documentation
float AshikhminVelvetClosure::albedo (const Vec3 & omega_out) const [inline]
Definition at line 75 of file bsdf_ashikhmin_velvet.cpp.
Color3 AshikhminVelvetClosure::eval_reflect (const Vec3 & omega_out, const Vec3 & omega_in, float & pdf) const [inline]
Definition at line 80 of file bsdf_ashikhmin_velvet.cpp.
References D(), expf, fabsf, G, H, M_1_PI, max, and min.
Color3 AshikhminVelvetClosure::eval_transmit (const Vec3 & omega_out, const Vec3 & omega_in, float & pdf) const [inline]
Definition at line 112 of file bsdf_ashikhmin_velvet.cpp.
size_t AshikhminVelvetClosure::memsize () const [inline]
Definition at line 63 of file bsdf_ashikhmin_velvet.cpp.
bool AshikhminVelvetClosure::mergeable (const ClosurePrimitive * other) const [inline]
Definition at line 57 of file bsdf_ashikhmin_velvet.cpp.
References m_N, and m_sigma.
const char* AshikhminVelvetClosure::name () const [inline]
Definition at line 65 of file bsdf_ashikhmin_velvet.cpp.
void AshikhminVelvetClosure::print_on (std::ostream & out) const [inline]
Definition at line 67 of file bsdf_ashikhmin_velvet.cpp.
ustring AshikhminVelvetClosure::sample (const Vec3 & Ng, const Vec3 & omega_out, const Vec3 & domega_out_dx, const Vec3 & domega_out_dy, float randu, float randv, Vec3 & omega_in, Vec3 & domega_in_dx, Vec3 & domega_in_dy, float & pdf, Color3 & eval) const [inline]
Definition at line 117 of file bsdf_ashikhmin_velvet.cpp.
References D(), expf, fabsf, G, H, M_1_PI, max, min, and sample_uniform_hemisphere().
void AshikhminVelvetClosure::setup () [inline]
Definition at line 51 of file bsdf_ashikhmin_velvet.cpp.
References max.
Member Data Documentation
float AshikhminVelvetClosure::m_invsigma2
Definition at line 47 of file bsdf_ashikhmin_velvet.cpp.
Vec3 AshikhminVelvetClosure::m_N
Definition at line 45 of file bsdf_ashikhmin_velvet.cpp.
Referenced by mergeable().
float AshikhminVelvetClosure::m_sigma
Definition at line 46 of file bsdf_ashikhmin_velvet.cpp.
Referenced by mergeable().
The documentation for this class was generated from the following file:
bsdf_ashikhmin_velvet.cpp