Blender: node_shader_output_world.c File Reference
node_shader_output_world.c File Reference
#include "../node_shader_util.h"
Functions
void register_node_type_sh_output_world (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_output_world_in []
Function Documentation
void register_node_type_sh_output_world (bNodeTreeType * ttype)
Definition at line 39 of file node_shader_output_world.c.
References NODE_CLASS_OUTPUT, NODE_NEW_SHADING, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_OUTPUT_WORLD.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_output_world_in[] [static]
Initial value:
 {
    {   SOCK_SHADER, 1, "Surface",      0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_SHADER, 1, "Volume",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_output_world.c.