Blender: node_shader_dynamic.c File Reference
node_shader_dynamic.c File Reference
shdnodes
#include "DNA_text_types.h"
#include "BKE_text.h"
#include "node_shader_util.h"
Functions
void register_node_type_sh_dynamic (bNodeTreeType *ttype)
Detailed Description
Definition in file node_shader_dynamic.c.
Function Documentation
void register_node_type_sh_dynamic (bNodeTreeType * ttype)
Definition at line 788 of file node_shader_dynamic.c.
References NODE_CLASS_OP_DYNAMIC, NODE_DYNAMIC, NODE_OLD_SHADING, node_type_base(), node_type_compatibility(), and nodeRegisterType().