Blender: BLI_md5.h File Reference
BLI_md5.h File Reference
blenlib
#include <stdio.h>
#include <stdlib.h>
Functions
void * md5_buffer (const char *buffer, size_t len, void *resblock)
int md5_stream (FILE *stream, void *resblock)
Detailed Description
Definition in file BLI_md5.h.
Function Documentation
void* md5_buffer (const char * buffer, size_t len, void * resblock)
Definition at line 220 of file md5.c.
References fillbuf, md5_init_ctx(), md5_process_block(), md5_read_ctx(), and SWAP.
Referenced by thumbname_from_uri().
int md5_stream (FILE * stream, void * resblock)
Definition at line 140 of file md5.c.
References BLOCKSIZE, fillbuf, len(), md5_init_ctx(), md5_process_block(), md5_read_ctx(), sum(), and SWAP.