Blender: mesh.c File Reference
mesh.c File Reference
blenkernel
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "DNA_key_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_ipo_types.h"
#include "DNA_customdata_types.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_bpath.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BLI_scanfill.h"
#include "BKE_animsys.h"
#include "BKE_main.h"
#include "BKE_customdata.h"
#include "BKE_DerivedMesh.h"
#include "BKE_global.h"
#include "BKE_mesh.h"
#include "BKE_displist.h"
#include "BKE_library.h"
#include "BKE_material.h"
#include "BKE_modifier.h"
#include "BKE_multires.h"
#include "BKE_key.h"
#include "BKE_curve.h"
#include "BKE_object.h"
#include "BKE_tessmesh.h"
#include "BLI_array.h"
#include "bmesh.h"
Classes
struct edgesort
struct EdgeLink
struct VertLink
Defines
#define ML(v1, v2) {ml->v = mf->v1; ml->e = GET_INT_FROM_POINTER(BLI_edgehash_lookup(eh, mf->v1, mf->v2)); ml++; j++;}
#define USE_TESSFACE_SPEEDUP
#define USE_TESSFACE_QUADS
#define TESSFACE_SCANFILL (1<<0)
#define TESSFACE_IS_QUAD (1<<1)
#define ML_TO_MF(i1, i2, i3)
#define ML_TO_MF_QUAD()
Typedefs
typedef struct EdgeLink EdgeLink
typedef struct VertLink VertLink
Enumerations
enum {
MESHCMP_DVERT_WEIGHTMISMATCH = 1, MESHCMP_DVERT_GROUPMISMATCH, MESHCMP_DVERT_TOTGROUPMISMATCH, MESHCMP_LOOPCOLMISMATCH,
MESHCMP_LOOPUVMISMATCH, MESHCMP_LOOPMISMATCH, MESHCMP_POLYVERTMISMATCH, MESHCMP_POLYMISMATCH,
MESHCMP_EDGEUNKNOWN, MESHCMP_VERTCOMISMATCH, MESHCMP_CDLAYERS_MISMATCH
}
Functions
static const char * cmpcode_to_str (int code)
static int customdata_compare (CustomData *c1, CustomData *c2, Mesh *m1, Mesh *m2, float thresh)
const char * mesh_cmp (Mesh *me1, Mesh *me2, float thresh)
static void mesh_ensure_tessellation_customdata (Mesh *me)
static void mesh_update_linked_customdata (Mesh *me, const short do_ensure_tess_cd)
void mesh_update_customdata_pointers (Mesh *me, const short do_ensure_tess_cd)
void unlink_mesh (Mesh *me)
void free_mesh (Mesh *me, int unlink)
void copy_dverts (MDeformVert *dst, MDeformVert *src, int copycount)
void free_dverts (MDeformVert *dvert, int totvert)
static void mesh_tessface_clear_intern (Mesh *mesh, int free_customdata)
Mesh * add_mesh (const char *name)
Mesh * copy_mesh (Mesh *me)
BMesh * BKE_mesh_to_bmesh (Mesh *me, Object *ob)
static void expand_local_mesh (Mesh *me)
void make_local_mesh (Mesh *me)
void boundbox_mesh (Mesh *me, float *loc, float *size)
void tex_space_mesh (Mesh *me)
BoundBox * mesh_get_bb (Object *ob)
void mesh_get_texspace (Mesh *me, float r_loc[3], float r_rot[3], float r_size[3])
float * get_mesh_orco_verts (Object *ob)
void transform_mesh_orco_verts (Mesh *me, float(*orco)[3], int totvert, int invert)
int test_index_face (MFace *mface, CustomData *fdata, int mfindex, int nr)
Mesh * get_mesh (Object *ob)
void set_mesh (Object *ob, Mesh *me)
static void to_edgesort (struct edgesort *ed, unsigned int v1, unsigned int v2, short is_loose, short is_draw)
static int vergedgesort (const void *v1, const void *v2)
static void make_edges_mdata (MVert *UNUSED(allvert), MFace *allface, MLoop *allloop, MPoly *allpoly, int UNUSED(totvert), int totface, int UNUSED(totloop), int totpoly, int old, MEdge **alledge, int *_totedge)
void make_edges (Mesh *me, int old)
void mesh_strip_loose_faces (Mesh *me)
void mesh_strip_loose_polysloops (Mesh *me)
void mesh_strip_loose_edges (Mesh *me)
void mball_to_mesh (ListBase *lb, Mesh *me)
int nurbs_to_mdata (Object *ob, MVert **allvert, int *totvert, MEdge **alledge, int *totedge, MLoop **allloop, MPoly **allpoly, int *totloop, int *totpoly)
int nurbs_to_mdata_customdb (Object *ob, ListBase *dispbase, MVert **allvert, int *_totvert, MEdge **alledge, int *_totedge, MLoop **allloop, MPoly **allpoly, int *_totloop, int *_totpoly)
void nurbs_to_mesh (Object *ob)
static void prependPolyLineVert (ListBase *lb, unsigned int index)
static void appendPolyLineVert (ListBase *lb, unsigned int index)
void mesh_to_curve (Scene *scene, Object *ob)
void mesh_delete_material_index (Mesh *me, short index)
void mesh_set_smooth_flag (Object *meshOb, int enableSmooth)
void mesh_calc_normals_mapping (MVert *mverts, int numVerts, MLoop *mloop, MPoly *mpolys, int numLoops, int numPolys, float(*polyNors_r)[3], MFace *mfaces, int numFaces, int *origIndexFace, float(*faceNors_r)[3])
void mesh_calc_normals_mapping_ex (MVert *mverts, int numVerts, MLoop *mloop, MPoly *mpolys, int numLoops, int numPolys, float(*polyNors_r)[3], MFace *mfaces, int numFaces, int *origIndexFace, float(*faceNors_r)[3], const short only_face_normals)
void mesh_calc_normals (MVert *mverts, int numVerts, MLoop *mloop, MPoly *mpolys, int UNUSED(numLoops), int numPolys, float(*polyNors_r)[3])
void mesh_calc_normals_tessface (MVert *mverts, int numVerts, MFace *mfaces, int numFaces, float(*faceNors_r)[3])
static void bm_corners_to_loops (Mesh *me, int findex, int loopstart, int numTex, int numCol)
void BKE_mesh_convert_mfaces_to_mpolys (Mesh *mesh)
float(* mesh_getVertexCos (Mesh *me, int *numVerts_r))[3]
UvVertMap * make_uv_vert_map (struct MPoly *mpoly, struct MLoop *mloop, struct MLoopUV *mloopuv, unsigned int totpoly, unsigned int totvert, int selected, float *limit)
UvMapVert * get_uv_map_vert (UvVertMap *vmap, unsigned int v)
void free_uv_vert_map (UvVertMap *vmap)
void create_vert_poly_map (MeshElemMap **map, int **mem, const MPoly *mpoly, const MLoop *mloop, int totvert, int totpoly, int totloop)
void create_vert_edge_map (ListBase **map, IndexNode **mem, const MEdge *medge, const int totvert, const int totedge)
void mesh_loops_to_mface_corners (CustomData *fdata, CustomData *ldata, CustomData *pdata, int lindex[4], int findex, const int polyindex, const int mf_len, const int numTex, const int numCol, const int hasPCol, const int hasOrigSpace)
int mesh_recalcTessellation (CustomData *fdata, CustomData *ldata, CustomData *pdata, MVert *mvert, int totface, int UNUSED(totloop), int totpoly, const int do_face_nor_cpy)
static void mesh_calc_ngon_normal (MPoly *mpoly, MLoop *loopstart, MVert *mvert, float normal[3])
void mesh_calc_poly_normal (MPoly *mpoly, MLoop *loopstart, MVert *mvarray, float no[3])
static void mesh_calc_ngon_normal_coords (MPoly *mpoly, MLoop *loopstart, const float(*vertex_coords)[3], float normal[3])
void mesh_calc_poly_normal_coords (MPoly *mpoly, MLoop *loopstart, const float(*vertex_coords)[3], float no[3])
static void mesh_calc_ngon_center (MPoly *mpoly, MLoop *loopstart, MVert *mvert, float cent[3])
void mesh_calc_poly_center (MPoly *mpoly, MLoop *loopstart, MVert *mvarray, float cent[3])
float mesh_calc_poly_area (MPoly *mpoly, MLoop *loopstart, MVert *mvarray, float polynormal[3])
int poly_find_loop_from_vert (const MPoly *poly, const MLoop *loopstart, unsigned vert)
int poly_get_adj_loops_from_vert (unsigned adj_r[3], const MPoly *poly, const MLoop *mloop, unsigned vert)
void mesh_flush_hidden_from_verts (const MVert *mvert, const MLoop *mloop, MEdge *medge, int totedge, MPoly *mpoly, int totpoly)
int minmax_mesh (Mesh *me, float min[3], float max[3])
int mesh_center_median (Mesh *me, float cent[3])
int mesh_center_bounds (Mesh *me, float cent[3])
void mesh_translate (Mesh *me, float offset[3], int do_keys)
void BKE_mesh_ensure_navmesh (Mesh *me)
void BKE_mesh_tessface_calc (Mesh *mesh)
void BKE_mesh_tessface_ensure (Mesh *mesh)
void BKE_mesh_tessface_clear (Mesh *mesh)
Detailed Description
Definition in file mesh.c.
Define Documentation
#define ML (v1, v2) {ml->v = mf->v1; ml->e = GET_INT_FROM_POINTER(BLI_edgehash_lookup(eh, mf->v1, mf->v2)); ml++; j++;}
Referenced by BKE_mesh_convert_mfaces_to_mpolys().
#define ML_TO_MF (i1, i2, i3)
Value:
BLI_array_growone(mface_to_poly_map);                                 \
        BLI_array_growone(mface);                                             \
        mface_to_poly_map[mface_index] = poly_index;                          \
        mf= &mface[mface_index];                                              \
        /* set loop indices, transformed to vert indices later */             \
        mf->v1 = mp->loopstart + i1;                                          \
        mf->v2 = mp->loopstart + i2;                                          \
        mf->v3 = mp->loopstart + i3;                                          \
        mf->v4 = 0;                                                           \
        mf->mat_nr = mp->mat_nr;                                              \
        mf->flag = mp->flag;                                                  \
        if (poly_orig_index) {                                                \
            BLI_array_append(mface_orig_index,                                \
                             poly_orig_index[poly_index]);                    \
        }                                                                     \
        (void)0
Referenced by mesh_recalcTessellation().
#define ML_TO_MF_QUAD ()
Value:
BLI_array_growone(mface_to_poly_map);                                 \
        BLI_array_growone(mface);                                             \
        mface_to_poly_map[mface_index] = poly_index;                          \
        mf= &mface[mface_index];                                              \
        /* set loop indices, transformed to vert indices later */             \
        mf->v1 = mp->loopstart + 0; /* EXCEPTION */                           \
        mf->v2 = mp->loopstart + 1; /* EXCEPTION */                           \
        mf->v3 = mp->loopstart + 2; /* EXCEPTION */                           \
        mf->v4 = mp->loopstart + 3; /* EXCEPTION */                           \
        mf->mat_nr = mp->mat_nr;                                              \
        mf->flag = mp->flag;                                                  \
        if (poly_orig_index) {                                                \
            BLI_array_append(mface_orig_index,                                \
                             poly_orig_index[poly_index]);                    \
        }                                                                     \
        mf->edcode |= TESSFACE_IS_QUAD; /* EXCEPTION */                       \
        (void)0
Referenced by mesh_recalcTessellation().
#define TESSFACE_IS_QUAD (1<<1)
Referenced by mesh_recalcTessellation().
#define TESSFACE_SCANFILL (1<<0)
Referenced by mesh_recalcTessellation().
#define USE_TESSFACE_QUADS
Referenced by mesh_recalcTessellation().
#define USE_TESSFACE_SPEEDUP
Typedef Documentation
typedef struct EdgeLink EdgeLink
typedef struct VertLink VertLink
Enumeration Type Documentation
anonymous enum
Enumerator:
MESHCMP_DVERT_WEIGHTMISMATCH
MESHCMP_DVERT_GROUPMISMATCH
MESHCMP_DVERT_TOTGROUPMISMATCH
MESHCMP_LOOPCOLMISMATCH
MESHCMP_LOOPUVMISMATCH
MESHCMP_LOOPMISMATCH
MESHCMP_POLYVERTMISMATCH
MESHCMP_POLYMISMATCH
MESHCMP_EDGEUNKNOWN
MESHCMP_VERTCOMISMATCH
MESHCMP_CDLAYERS_MISMATCH
Definition at line 80 of file mesh.c.
Function Documentation
Mesh* add_mesh (const char * name) [read]
Definition at line 479 of file mesh.c.
References alloc_libblock(), Mesh::bb, Mesh::drawflag, Mesh::flag, G, ID_ME, ME_AUTOSPACE, ME_DRAWCREASES, ME_DRAWEDGES, ME_DRAWFACES, ME_TWOSIDED, Mesh::size, Mesh::smoothresh, Mesh::texflag, and unit_boundbox().
Referenced by add_obdata_from_type(), AddNewBlenderMesh(), convert_exec(), nurbs_to_mesh(), and MeshImporter::write_geometry().
static void appendPolyLineVert (ListBase * lb, unsigned int index) [static]
Definition at line 1548 of file mesh.c.
References BLI_addtail(), VertLink::index, and MEM_callocN().
Referenced by mesh_to_curve().
void BKE_mesh_convert_mfaces_to_mpolys (Mesh * mesh)
Definition at line 2023 of file mesh.c.
References BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_new(), bm_corners_to_loops(), CD_ASSIGN, CD_MASK_MDISPS, CD_MCOL, CD_MLOOP, CD_MPOLY, CD_MTFACE, CustomData_add_layer(), CustomData_external_read(), CustomData_free(), CustomData_number_of_layers(), CustomData_to_bmeshpoly(), Mesh::fdata, MPoly::flag, MEdge::flag, i, Mesh::id, Mesh::ldata, MPoly::loopstart, MPoly::mat_nr, ME_FGON, Mesh::medge, MEM_callocN(), mesh_update_customdata_pointers(), Mesh::mface, ML, Mesh::mloop, Mesh::mpoly, NULL, SET_INT_IN_POINTER, Mesh::totedge, Mesh::totface, MPoly::totloop, Mesh::totloop, Mesh::totpoly, TRUE, MEdge::v1, MEdge::v2, and MFace::v4.
Referenced by ED_mesh_update(), EDBM_mesh_make(), lib_link_mesh(), and MeshImporter::write_geometry().
void BKE_mesh_ensure_navmesh (Mesh * me)
Definition at line 3132 of file mesh.c.
References CD_CALLOC, CD_RECAST, CD_REFERENCE, CustomData_add_layer_named(), CustomData_get_layer(), CustomData_has_layer(), i, NULL, and Mesh::totpoly.
Referenced by createRepresentation(), and navmesh_reset_exec().
void BKE_mesh_tessface_calc (Mesh * mesh)
Definition at line 3147 of file mesh.c.
References FALSE, Mesh::fdata, Mesh::ldata, mesh_recalcTessellation(), mesh_update_customdata_pointers(), Mesh::mvert, Mesh::totface, Mesh::totloop, Mesh::totpoly, and TRUE.
Referenced by BKE_mesh_tessface_ensure(), BM_mesh_bm_to_me(), DM_to_mesh(), ED_mesh_calc_tessface(), ED_mesh_update(), EDBM_mesh_load(), lib_link_mesh(), and make_vertexcol().
void BKE_mesh_tessface_clear (Mesh * mesh)
Definition at line 3165 of file mesh.c.
References mesh_tessface_clear_intern(), and TRUE.
Referenced by ED_mesh_update(), lib_link_mesh(), make_vertexcol(), mesh_ensure_tessellation_customdata(), and vpaint_fill().
void BKE_mesh_tessface_ensure (Mesh * mesh)
Definition at line 3158 of file mesh.c.
References BKE_mesh_tessface_calc(), Mesh::totface, and Mesh::totpoly.
Referenced by cdDM_getPBVH(), heat_bone_weighting(), GeometryExporter::operator()(), PE_mirror_x(), and sculpt_update_mesh_elements().
BMesh* BKE_mesh_to_bmesh (Mesh * me, Object * ob) [read]
Definition at line 556 of file mesh.c.
References bm_mesh_allocsize_default, BM_mesh_bm_from_me(), BM_mesh_create(), Object::shapenr, and TRUE.
Referenced by EDBM_mesh_make().
static void bm_corners_to_loops (Mesh * me, int findex, int loopstart, int numTex, int numCol) [static]
Definition at line 1944 of file mesh.c.
References BLI_assert, CD_MCOL, CD_MDISPS, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, copy_v2_v2(), CustomData_external_add(), CustomData_external_test(), CustomData_get(), CustomData_get_n(), CustomData_has_layer(), MDisps::disps, CustomData::external, Mesh::fdata, CustomDataExternal::filename, i, Mesh::id, Mesh::ldata, MDisps::level, logf, M_LN2, ME_MTEXFACE_CPY, MEM_callocN(), MEM_freeN(), MESH_MLOOPCOL_FROM_MCOL, Mesh::mface, multires_mdisp_corners(), sqrt(), MDisps::totdisp, Mesh::totloop, MTFace::uv, MLoopUV::uv, and MFace::v4.
Referenced by BKE_mesh_convert_mfaces_to_mpolys().
void boundbox_mesh (Mesh * me, float * loc, float * size)
Definition at line 653 of file mesh.c.
References Mesh::bb, boundbox_set_from_min_max(), INIT_MINMAX, max, MEM_callocN(), mid_v3_v3v3(), min, minmax_mesh(), and NULL.
Referenced by tex_space_mesh().
static const char* cmpcode_to_str (int code) [static]
Definition at line 94 of file mesh.c.
References MESHCMP_CDLAYERS_MISMATCH, MESHCMP_DVERT_GROUPMISMATCH, MESHCMP_DVERT_TOTGROUPMISMATCH, MESHCMP_DVERT_WEIGHTMISMATCH, MESHCMP_EDGEUNKNOWN, MESHCMP_LOOPCOLMISMATCH, MESHCMP_LOOPMISMATCH, MESHCMP_LOOPUVMISMATCH, MESHCMP_POLYMISMATCH, MESHCMP_POLYVERTMISMATCH, and MESHCMP_VERTCOMISMATCH.
Referenced by mesh_cmp().
void copy_dverts (MDeformVert * dst, MDeformVert * src, int copycount)
Definition at line 430 of file mesh.c.
References MDeformVert::dw, i, and MEM_callocN().
Referenced by copy_lattice(), copy_wpaint_prev(), load_editLatt(), and make_editLatt().
Mesh* copy_mesh (Mesh * me) [read]
Definition at line 495 of file mesh.c.
References Mesh::bb, CD_DUPLICATE, CD_MASK_MESH, CD_MTEXPOLY, CD_MTFACE, copy_key(), copy_libblock(), CustomData_copy(), CustomDataLayer::data, Mesh::edit_btmesh, FALSE, Mesh::fdata, Key::from, i, Mesh::id, id_lib_extern(), id_us_plus(), Mesh::key, CustomData::layers, Mesh::ldata, Mesh::mat, MEM_dupallocN(), mesh_tessface_clear_intern(), mesh_update_customdata_pointers(), Mesh::mselect, NULL, Mesh::texcomesh, Mesh::totcol, Mesh::totedge, Mesh::totface, CustomData::totlayer, Mesh::totloop, Mesh::totpoly, Mesh::totvert, MTexPoly::tpage, MTFace::tpage, and CustomDataLayer::type.
Referenced by bmo_dupe_exec(), convert_exec(), KX_BlenderSceneConverter::ConvertMeshSpecial(), id_copy(), make_local_mesh(), object_add_duplicate_internal(), and single_obdata_users().
void create_vert_edge_map (ListBase ** map, IndexNode ** mem, const MEdge * medge, const int totvert, const int totedge)
Definition at line 2279 of file mesh.c.
References BLI_addtail(), i, IndexNode::index, MEM_callocN(), and NULL.
void create_vert_poly_map (MeshElemMap ** map, int ** mem, const MPoly * mpoly, const MLoop * mloop, int totvert, int totpoly, int totloop)
Definition at line 2235 of file mesh.c.
References i, indices, MPoly::loopstart, MEM_callocN(), MEM_mallocN(), p, MPoly::totloop, and MLoop::v.
static int customdata_compare (CustomData * c1, CustomData * c2, Mesh * m1, Mesh * m2, float thresh) [static]
Definition at line 126 of file mesh.c.
References MLoopCol::a, ABS, MLoopCol::b, BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), CD_MDEFORMVERT, CD_MEDGE, CD_MLOOP, CD_MLOOPCOL, CD_MLOOPUV, CD_MPOLY, CD_MTEXPOLY, CD_MVERT, MVert::co, MDeformVert::dw, ELEM7, MLoopCol::g, i, CustomData::layers, len_v2v2(), len_v3v3(), MPoly::loopstart, MESHCMP_CDLAYERS_MISMATCH, MESHCMP_DVERT_GROUPMISMATCH, MESHCMP_DVERT_TOTGROUPMISMATCH, MESHCMP_DVERT_WEIGHTMISMATCH, MESHCMP_EDGEUNKNOWN, MESHCMP_LOOPCOLMISMATCH, MESHCMP_LOOPMISMATCH, MESHCMP_LOOPUVMISMATCH, MESHCMP_POLYMISMATCH, MESHCMP_POLYVERTMISMATCH, MESHCMP_VERTCOMISMATCH, Mesh::mloop, NULL, MLoopCol::r, Mesh::totedge, CustomData::totlayer, Mesh::totloop, MPoly::totloop, Mesh::totpoly, Mesh::totvert, MDeformVert::totweight, CustomDataLayer::type, MLoopUV::uv, MLoop::v, MEdge::v1, and MEdge::v2.
Referenced by mesh_cmp().
static void expand_local_mesh (Mesh * me) [static]
Definition at line 567 of file mesh.c.
References CD_MTEXPOLY, CD_MTFACE, CustomDataLayer::data, extern_local_matarar(), Mesh::fdata, i, id_lib_extern(), CustomData::layers, Mesh::mat, Mesh::mtface, Mesh::mtpoly, Mesh::texcomesh, Mesh::totcol, Mesh::totface, CustomData::totlayer, Mesh::totpoly, MTFace::tpage, MTexPoly::tpage, and CustomDataLayer::type.
Referenced by make_local_mesh().
void free_dverts (MDeformVert * dvert, int totvert)
Definition at line 449 of file mesh.c.
References i, and MEM_freeN().
Referenced by copy_wpaint_prev(), free_editLatt(), free_lattice(), load_editLatt(), and resizelattice().
void free_mesh (Mesh * me, int unlink)
Definition at line 407 of file mesh.c.
References Mesh::adt, Mesh::bb, BKE_free_animdata(), CustomData_free(), Mesh::edit_btmesh, Mesh::fdata, Mesh::id, Mesh::ldata, Mesh::mat, MEM_freeN(), Mesh::mselect, NULL, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totvert, and unlink_mesh().
Referenced by free_libblock(), and free_undo().
void free_uv_vert_map (UvVertMap * vmap)
Definition at line 2223 of file mesh.c.
References UvVertMap::buf, MEM_freeN(), and UvVertMap::vert.
Referenced by EDBM_uv_vert_map_create(), make_uv_vert_map(), and ss_sync_from_uv().
Mesh* get_mesh (Object * ob) [read]
Definition at line 841 of file mesh.c.
References Object::data, NULL, OB_MESH, and Object::type.
Referenced by do_paintface_box_select(), image_paint_sample_color_poll(), make_vertexcol(), minmax_object(), multires_force_external_reload(), multiresModifier_base_apply(), multiresModifier_del_levels(), paintface_deselect_all_visible(), paintface_flush_flags(), paintface_hide(), paintface_minmax(), paintface_mouse_select(), paintface_reveal(), paintface_select_linked(), paintvert_deselect_all_visible(), paintvert_flush_flags(), sculpt_update_mesh_elements(), set_vpaint(), set_wpaint(), texture_paint_init(), texture_paint_toggle_exec(), vertex_paint_use_fast_update_check(), vertex_paint_use_tessface_check(), vpaint_fill(), vpaint_paint_poly(), vpaint_stroke_test_start(), weight_paint_sample_enum_itemf(), weight_sample_invoke(), and wpaint_stroke_test_start().
float* get_mesh_orco_verts (Object * ob)
Definition at line 724 of file mesh.c.
References MVert::co, copy_v3_v3(), Object::data, MEM_callocN(), MIN2, Mesh::mvert, NULL, Mesh::texcomesh, and Mesh::totvert.
Referenced by distribute_threads_init_data(), face_duplilist(), get_dm(), get_orco_coords_dm(), and vertex_duplilist().
UvMapVert* get_uv_map_vert (UvVertMap * vmap, unsigned int v)
Definition at line 2218 of file mesh.c.
References UvVertMap::vert.
Referenced by get_face_uv_map_vert(), and ss_sync_from_uv().
void make_edges (Mesh * me, int old)
Definition at line 1010 of file mesh.c.
References CD_ASSIGN, CD_MEDGE, CustomData_add_layer(), make_edges_mdata(), Mesh::medge, mesh_strip_loose_faces(), Mesh::mface, Mesh::mloop, Mesh::mpoly, Mesh::mvert, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, and Mesh::totvert.
Referenced by do_versions(), and MeshImporter::write_geometry().
static void make_edges_mdata (MVert * UNUSEDallvert, MFace * allface, MLoop * allloop, MPoly * allpoly, int UNUSEDtotvert, int totface, int UNUSEDtotloop, int totpoly, int old, MEdge ** alledge, int * _totedge) [static]
Definition at line 906 of file mesh.c.
References BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), MLoop::e, MFace::edcode, MEdge::flag, GET_INT_FROM_POINTER, hash, edgesort::is_draw, edgesort::is_loose, MPoly::loopstart, ME_EDGEDRAW, ME_EDGERENDER, ME_LOOSEEDGE, ME_POLY_LOOP_NEXT, ME_V1V2, ME_V2V3, ME_V3V1, ME_V3V4, ME_V4V1, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, SET_INT_IN_POINTER, SWAP, to_edgesort(), MPoly::totloop, MLoop::v, MEdge::v1, MFace::v1, edgesort::v1, MEdge::v2, MFace::v2, edgesort::v2, MFace::v3, MFace::v4, and vergedgesort().
Referenced by make_edges(), and nurbs_to_mdata_customdb().
void make_local_mesh (Mesh * me)
Definition at line 606 of file mesh.c.
References BKE_id_lib_local_paths(), copy_mesh(), Object::data, ELEM, expand_local_mesh(), FALSE, ListBase::first, G, Mesh::id, Object::id, id_clear_lib_data(), ID::lib, ID::next, NULL, Main::object, set_mesh(), TRUE, and ID::us.
Referenced by id_make_local().
UvVertMap* make_uv_vert_map (struct MPoly * mpoly, struct MLoop * mloop, struct MLoopUV * mloopuv, unsigned int totpoly, unsigned int totvert, int selected, float * limit)
Definition at line 2127 of file mesh.c.
References UvVertMap::buf, UvMapVert::f, fabsf, MPoly::flag, free_uv_vert_map(), i, MPoly::loopstart, ME_FACE_SEL, ME_HIDE, MEM_callocN(), next, UvMapVert::next, NULL, UvMapVert::separate, sub_v2_v2v2(), UvMapVert::tfindex, MPoly::totloop, MLoopUV::uv, MLoop::v, and UvVertMap::vert.
Referenced by ss_sync_from_uv().
void mball_to_mesh (ListBase * lb, Mesh * me)
Definition at line 1161 of file mesh.c.
References BKE_mesh_calc_edges(), CD_CALLOC, CD_MLOOP, CD_MPOLY, CD_MVERT, MVert::co, copy_v3_v3(), CustomData_add_layer(), DL_INDEX4, ListBase::first, MPoly::flag, DispList::index, Mesh::ldata, MPoly::loopstart, ME_SMOOTH, mesh_calc_normals(), mesh_update_customdata_pointers(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, MVert::no, normal_float_to_short_v3(), DispList::nors, DispList::nr, NULL, DispList::parts, Mesh::totloop, MPoly::totloop, Mesh::totpoly, Mesh::totvert, TRUE, DispList::type, MLoop::v, and DispList::verts.
Referenced by convert_exec().
static void mesh_calc_ngon_center (MPoly * mpoly, MLoop * loopstart, MVert * mvert, float cent[3]) [static]
Definition at line 2930 of file mesh.c.
References co, madd_v3_v3fl(), MPoly::totloop, and zero_v3().
Referenced by mesh_calc_poly_center().
static void mesh_calc_ngon_normal (MPoly * mpoly, MLoop * loopstart, MVert * mvert, float normal[3]) [static]
Definition at line 2758 of file mesh.c.
References MVert::co, copy_v3db_v3fl(), i, sqrt(), MPoly::totloop, and MLoop::v.
Referenced by mesh_calc_poly_normal().
static void mesh_calc_ngon_normal_coords (MPoly * mpoly, MLoop * loopstart, const float(*) vertex_coords[3], float normal[3]) [static]
Definition at line 2849 of file mesh.c.
References copy_v3db_v3fl(), i, sqrt(), MPoly::totloop, and MLoop::v.
Referenced by mesh_calc_poly_normal_coords().
void mesh_calc_normals (MVert * mverts, int numVerts, MLoop * mloop, MPoly * mpolys, int UNUSEDnumLoops, int numPolys, float(*) polyNors_r[3])
Definition at line 1843 of file mesh.c.
References accumulate_vertex_normals_poly(), BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, MVert::co, i, MPoly::loopstart, MEM_callocN(), MEM_freeN(), mesh_calc_poly_normal(), MVert::no, normal_float_to_short_v3(), normalize_v3(), normalize_v3_v3(), NULL, MPoly::totloop, and MLoop::v.
void mesh_calc_normals_mapping (MVert * mverts, int numVerts, MLoop * mloop, MPoly * mpolys, int numLoops, int numPolys, float(*) polyNors_r[3], MFace * mfaces, int numFaces, int * origIndexFace, float(*) faceNors_r[3])
Definition at line 1772 of file mesh.c.
References mesh_calc_normals_mapping_ex(), and TRUE.
Referenced by apply_objects_internal(), sculpt_vertcos_to_key(), and MeshImporter::write_geometry().
void mesh_calc_normals_mapping_ex (MVert * mverts, int numVerts, MLoop * mloop, MPoly * mpolys, int numLoops, int numPolys, float(*) polyNors_r[3], MFace * mfaces, int numFaces, int * origIndexFace, float(*) faceNors_r[3], const short only_face_normals)
Definition at line 1781 of file mesh.c.
References copy_v3_v3(), FALSE, i, MPoly::loopstart, MEM_callocN(), MEM_freeN(), mesh_calc_normals(), mesh_calc_poly_normal(), NULL, and TRUE.
Referenced by CDDM_calc_normals_mapping_ex(), ED_mesh_calc_normals(), ED_mesh_update(), and mesh_calc_normals_mapping().
void mesh_calc_normals_tessface (MVert * mverts, int numVerts, MFace * mfaces, int numFaces, float(*) faceNors_r[3])
Definition at line 1905 of file mesh.c.
References accumulate_vertex_normals(), MVert::co, i, MEM_callocN(), MEM_freeN(), MVert::no, normal_float_to_short_v3(), normal_quad_v3(), normal_tri_v3(), normalize_v3(), normalize_v3_v3(), NULL, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by BLI_pbvh_apply_vertCos(), CDDM_calc_normals_tessface(), do_versions(), and sculpt_undo_restore().
float mesh_calc_poly_area (MPoly * mpoly, MLoop * loopstart, MVert * mvarray, float polynormal[3])
Definition at line 2967 of file mesh.c.
References area_poly_v3(), area_quad_v3(), area_tri_v3(), BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_NGON_STACK_SIZE, MVert::co, co, copy_v3_v3(), i, mesh_calc_poly_normal(), NULL, MPoly::totloop, and MLoop::v.
Referenced by face_duplilist().
void mesh_calc_poly_center (MPoly * mpoly, MLoop * loopstart, MVert * mvarray, float cent[3])
Definition at line 2943 of file mesh.c.
References cent_quad_v3(), cent_tri_v3(), co, mesh_calc_ngon_center(), and MPoly::totloop.
Referenced by face_duplilist().
void mesh_calc_poly_normal (MPoly * mpoly, MLoop * loopstart, MVert * mvarray, float no[3])
Definition at line 2821 of file mesh.c.
References co, mesh_calc_ngon_normal(), normal_quad_v3(), normal_tri_v3(), and MPoly::totloop.
Referenced by applyModifier(), dm_calc_normal(), mesh_calc_normals(), mesh_calc_normals_mapping_ex(), and mesh_calc_poly_area().
void mesh_calc_poly_normal_coords (MPoly * mpoly, MLoop * loopstart, const float(*) vertex_coords[3], float no[3])
Definition at line 2902 of file mesh.c.
References mesh_calc_ngon_normal_coords(), normal_quad_v3(), normal_tri_v3(), and MPoly::totloop.
Referenced by multiresModifier_base_apply(), and uvprojectModifier_do().
int mesh_center_bounds (Mesh * me, float cent[3])
Definition at line 3100 of file mesh.c.
References INIT_MINMAX, max, mid_v3_v3v3(), min, and minmax_mesh().
Referenced by object_origin_set_exec().
int mesh_center_median (Mesh * me, float cent[3])
Definition at line 3084 of file mesh.c.
References add_v3_v3(), MVert::co, mul_v3_fl(), Mesh::mvert, Mesh::totvert, and zero_v3().
Referenced by object_origin_set_exec().
const char* mesh_cmp (Mesh * me1, Mesh * me2, float thresh)
Definition at line 272 of file mesh.c.
References cmpcode_to_str(), customdata_compare(), Mesh::ldata, NULL, Mesh::totedge, Mesh::totloop, Mesh::totpoly, and Mesh::totvert.
void mesh_delete_material_index (Mesh * me, short index)
Definition at line 1727 of file mesh.c.
References i, MFace::mat_nr, MPoly::mat_nr, Mesh::mface, Mesh::mpoly, Mesh::totface, and Mesh::totpoly.
Referenced by data_delete_material_index_id().
static void mesh_ensure_tessellation_customdata (Mesh * me) [static]
Definition at line 306 of file mesh.c.
References BKE_mesh_tessface_clear(), CD_MCOL, CD_MLOOPCOL, CD_MTEXPOLY, CD_MTFACE, CustomData_from_bmeshpoly(), CustomData_number_of_layers(), Mesh::fdata, G, G_DEBUG, Mesh::ldata, Mesh::totface, Mesh::totpoly, and UNLIKELY.
Referenced by mesh_update_linked_customdata().
void mesh_flush_hidden_from_verts (const MVert * mvert, const MLoop * mloop, MEdge * medge, int totedge, MPoly * mpoly, int totpoly)
Definition at line 3047 of file mesh.c.
References MPoly::flag, MEdge::flag, MVert::flag, i, MPoly::loopstart, ME_HIDE, p, MPoly::totloop, MLoop::v, MEdge::v1, and MEdge::v2.
BoundBox* mesh_get_bb (Object * ob) [read]
Definition at line 700 of file mesh.c.
References Mesh::bb, Object::bb, Object::data, and tex_space_mesh().
Referenced by draw_bounding_volume(), minmax_object(), and object_get_boundbox().
void mesh_get_texspace (Mesh * me, float r_loc[3], float r_rot[3], float r_size[3])
Definition at line 713 of file mesh.c.
References Mesh::bb, copy_v3_v3(), Mesh::loc, Mesh::rot, Mesh::size, and tex_space_mesh().
Referenced by calc_edge_stress(), drawtexspace(), image_aspect(), psys_render_simplify_distribution(), and transform_mesh_orco_verts().
float(* mesh_getVertexCos (Mesh * me, int * numVerts_r))[3]
Definition at line 2110 of file mesh.c.
References MVert::co, copy_v3_v3(), cos(), i, MEM_mallocN(), Mesh::mvert, and Mesh::totvert.
Referenced by crazyspace_build_sculpt(), mesh_calc_modifiers(), mesh_create_derived_for_modifier(), sculpt_get_first_deform_matrices(), and sculpt_update_mesh_elements().
void mesh_loops_to_mface_corners (CustomData * fdata, CustomData * ldata, CustomData * pdata, int lindex[4], int findex, const int polyindex, const int mf_len, const int numTex, const int numCol, const int hasPCol, const int hasOrigSpace)
Definition at line 2297 of file mesh.c.
References CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CD_ORIGSPACE, CD_ORIGSPACE_MLOOP, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, copy_v2_v2(), CustomData_get(), CustomData_get_n(), i, ME_MTEXFACE_CPY, MESH_MLOOPCOL_TO_MCOL, MTFace::uv, MLoopUV::uv, OrigSpaceLoop::uv, and OrigSpaceFace::uv.
Referenced by DM_update_tessface_data(), and mesh_recalcTessellation().
int mesh_recalcTessellation (CustomData * fdata, CustomData * ldata, CustomData * pdata, MVert * mvert, int totface, int UNUSEDtotloop, int totpoly, const int do_face_nor_cpy)
Definition at line 2361 of file mesh.c.
References BLI_addfilledge(), BLI_addfillvert(), BLI_array_declare, BLI_array_growitems, BLI_array_reserve, BLI_begin_edgefill(), BLI_edgefill(), BLI_end_edgefill(), CD_ASSIGN, CD_CALLOC, CD_MFACE, CD_MLOOP, CD_MLOOPCOL, CD_MPOLY, CD_MTEXPOLY, CD_NORMAL, CD_ORIGINDEX, CD_ORIGSPACE_MLOOP, CD_POLYINDEX, CD_PREVIEW_MLOOPCOL, MVert::co, copy_v3_v3(), CustomData_add_layer(), CustomData_free(), CustomData_from_bmeshpoly(), CustomData_get_layer(), CustomData_has_layer(), CustomData_number_of_layers(), MFace::edcode, FALSE, ScanFillContext::fillfacebase, ListBase::first, MPoly::flag, ScanFillVert::keyindex, LIKELY, MPoly::loopstart, MPoly::mat_nr, MEM_allocN_len(), MEM_reallocN(), mesh_loops_to_mface_corners(), ML_TO_MF, ML_TO_MF_QUAD, ScanFillFace::next, NULL, SWAP, TESSFACE_IS_QUAD, TESSFACE_SCANFILL, test_index_face(), MPoly::totloop, UNLIKELY, USE_TESSFACE_QUADS, MLoop::v, ScanFillFace::v1, MFace::v1, ScanFillFace::v2, and ScanFillFace::v3.
void mesh_set_smooth_flag (Object * meshOb, int enableSmooth)
Definition at line 1744 of file mesh.c.
References Object::data, MFace::flag, MPoly::flag, i, ME_SMOOTH, Mesh::mface, Mesh::mpoly, Mesh::totface, and Mesh::totpoly.
Referenced by shade_smooth_exec().
void mesh_strip_loose_edges (Mesh * me)
Definition at line 1126 of file mesh.c.
References CustomData_copy_data(), CustomData_free_elem(), MLoop::e, INVALID_LOOP_EDGE_MARKER, Mesh::medge, MEM_freeN(), MEM_mallocN(), Mesh::mloop, Mesh::totedge, MEdge::v1, and MEdge::v2.
Referenced by BKE_mesh_validate_arrays().
void mesh_strip_loose_faces (Mesh * me)
Definition at line 1031 of file mesh.c.
References CustomData_copy_data(), CustomData_free_elem(), edgesort::f, Mesh::fdata, Mesh::mface, Mesh::totface, and MFace::v3.
Referenced by do_versions(), and make_edges().
void mesh_strip_loose_polysloops (Mesh * me)
Definition at line 1055 of file mesh.c.
References CustomData_copy_data(), CustomData_free_elem(), MLoop::e, FALSE, i, INVALID_LOOP_EDGE_MARKER, Mesh::ldata, MPoly::loopstart, MEM_freeN(), MEM_mallocN(), Mesh::mloop, Mesh::mpoly, p, Mesh::totloop, MPoly::totloop, Mesh::totpoly, and TRUE.
Referenced by BKE_mesh_validate_arrays().
static void mesh_tessface_clear_intern (Mesh * mesh, int free_customdata) [static]
Definition at line 466 of file mesh.c.
References CustomData_free(), Mesh::fdata, Mesh::mcol, Mesh::mface, Mesh::mtface, NULL, and Mesh::totface.
Referenced by BKE_mesh_tessface_clear(), and copy_mesh().
void mesh_to_curve (Scene * scene, Object * ob)
Definition at line 1555 of file mesh.c.
References add_curve(), appendPolyLineVert(), Object::bb, BLI_addtail(), BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_new(), BLI_findlink(), BLI_freelinkN(), BLI_freelistN(), Nurb::bp, CD_MASK_MESH, MVert::co, copy_v3_v3(), CU_3D, CU_NURB_CYCLIC, CU_NURB_ENDPOINT, Object::data, Object::derivedFinal, EdgeLink::edge, BPoint::f1, FALSE, ListBase::first, Curve::flag, Nurb::flagu, DerivedMesh::getEdgeArray, DerivedMesh::getNumEdges, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceArray, DerivedMesh::getVertArray, i, Object::id, VertLink::index, ListBase::last, MEM_callocN(), MEM_freeN(), mesh_get_derived_final(), ID::name, DerivedMesh::needsFree, VertLink::next, NULL, Curve::nurb, OB_CURVE, Nurb::orderu, Nurb::pntsu, Nurb::pntsv, prependPolyLineVert(), BPoint::radius, DerivedMesh::release, Nurb::resolu, SELECT, TRUE, Object::type, MEdge::v1, MFace::v1, MEdge::v2, MFace::v2, MFace::v3, MFace::v4, BPoint::vec, and BPoint::weight.
Referenced by convert_exec().
void mesh_translate (Mesh * me, float offset[3], int do_keys)
Definition at line 3112 of file mesh.c.
References add_v3_v3(), Key::block, MVert::co, KeyBlock::data, ListBase::first, Mesh::key, Mesh::mvert, KeyBlock::next, KeyBlock::totelem, and Mesh::totvert.
Referenced by object_origin_set_exec().
void mesh_update_customdata_pointers (Mesh * me, const short do_ensure_tess_cd)
Definition at line 360 of file mesh.c.
References CD_MCOL, CD_MDEFORMVERT, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MLOOPCOL, CD_MLOOPUV, CD_MPOLY, CD_MSTICKY, CD_MTEXPOLY, CD_MTFACE, CD_MVERT, CustomData_get_layer(), Mesh::dvert, Mesh::fdata, Mesh::ldata, Mesh::mcol, Mesh::medge, mesh_update_linked_customdata(), Mesh::mface, Mesh::mloop, Mesh::mloopcol, Mesh::mloopuv, Mesh::mpoly, Mesh::msticky, Mesh::mtface, Mesh::mtpoly, and Mesh::mvert.
Referenced by BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_tessface_calc(), BM_mesh_bm_to_me(), copy_mesh(), customdata_version_242(), delete_customdata_layer(), direct_link_mesh(), DM_to_mesh(), ED_mesh_color_add(), ED_mesh_uv_texture_add(), join_mesh_exec(), make_vertexcol(), mball_to_mesh(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), and write_meshs().
static void mesh_update_linked_customdata (Mesh * me, const short do_ensure_tess_cd) [static]
Definition at line 348 of file mesh.c.
References BMEdit_UpdateLinkedCustomData(), CustomData_bmesh_update_active_layers(), Mesh::edit_btmesh, Mesh::fdata, Mesh::ldata, and mesh_ensure_tessellation_customdata().
Referenced by mesh_update_customdata_pointers().
int minmax_mesh (Mesh * me, float min[3], float max[3])
Definition at line 3073 of file mesh.c.
References MVert::co, DO_MINMAX, Mesh::mvert, and Mesh::totvert.
Referenced by boundbox_mesh(), and mesh_center_bounds().
int nurbs_to_mdata (Object * ob, MVert ** allvert, int * totvert, MEdge ** alledge, int * totedge, MLoop ** allloop, MPoly ** allpoly, int * totloop, int * totpoly)
Definition at line 1226 of file mesh.c.
References Object::disp, and nurbs_to_mdata_customdb().
Referenced by nurbs_to_mesh().
int nurbs_to_mdata_customdb (Object * ob, ListBase * dispbase, MVert ** allvert, int * _totvert, MEdge ** alledge, int * _totedge, MLoop ** allloop, MPoly ** allpoly, int * _totloop, int * _totpoly)
Definition at line 1242 of file mesh.c.
References MVert::co, DispList::col, copy_v3_v3(), CU_3D, CU_SMOOTH, Object::data, data, DL_CYCL_U, DL_CYCL_V, DL_INDEX3, DL_POLY, DL_SEGM, DL_SURF, ListBase::first, Curve::flag, MEdge::flag, DispList::flag, MPoly::flag, DispList::index, MPoly::loopstart, make_edges_mdata(), MPoly::mat_nr, ME_EDGEDRAW, ME_EDGERENDER, ME_LOOSEEDGE, ME_SMOOTH, MEM_callocN(), DispList::next, DispList::nr, OB_SURF, DispList::parts, DispList::rt, smooth(), MPoly::totloop, DispList::type, Object::type, MLoop::v, MEdge::v1, MEdge::v2, and DispList::verts.
Referenced by CDDM_from_curve_customDB(), and nurbs_to_mdata().
void nurbs_to_mesh (Object * ob)
Definition at line 1462 of file mesh.c.
References add_mesh(), BKE_mesh_calc_edges(), CD_ASSIGN, CD_MEDGE, CD_MLOOP, CD_MPOLY, CD_MVERT, Main::curve, CustomData_add_layer(), Object::data, Object::derivedFinal, DM_to_mesh(), ListBase::first, free_libblock(), G, Object::id, id_us_plus(), Mesh::ldata, Curve::mat, Mesh::mat, Mesh::medge, mesh_calc_normals(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, ID::next, NULL, nurbs_to_mdata(), OB_MESH, Main::object, tex_space_mesh(), Curve::totcol, Mesh::totcol, Mesh::totedge, Mesh::totloop, Mesh::totpoly, Mesh::totvert, TRUE, and Object::type.
Referenced by curvetomesh().
int poly_find_loop_from_vert (const MPoly * poly, const MLoop * loopstart, unsigned vert)
Definition at line 3011 of file mesh.c.
References MPoly::totloop, and MLoop::v.
int poly_get_adj_loops_from_vert (unsigned adj_r[3], const MPoly * poly, const MLoop * mloop, unsigned vert)
Definition at line 3026 of file mesh.c.
References MPoly::loopstart, ME_POLY_LOOP_NEXT, ME_POLY_LOOP_PREV, poly_find_loop_from_vert(), and MLoop::v.
static void prependPolyLineVert (ListBase * lb, unsigned int index) [static]
Definition at line 1541 of file mesh.c.
References BLI_addhead(), VertLink::index, and MEM_callocN().
Referenced by mesh_to_curve().
void set_mesh (Object * ob, Mesh * me)
Definition at line 849 of file mesh.c.
References Object::data, Mesh::id, id_us_plus(), multires_force_update(), NULL, OB_MESH, test_object_materials(), test_object_modifiers(), Object::type, and ID::us.
Referenced by MeshImporter::create_mesh_object(), and make_local_mesh().
int test_index_face (MFace * mface, CustomData * fdata, int mfindex, int nr)
Definition at line 769 of file mesh.c.
References CustomData_swap(), SWAP, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by CDDM_from_BMEditMesh(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), emDM_copyTessFaceArray(), emDM_getTessFace(), explodeMesh(), and mesh_recalcTessellation().
void tex_space_mesh (Mesh * me)
Definition at line 680 of file mesh.c.
References boundbox_mesh(), copy_v3_v3(), Mesh::loc, ME_AUTOSPACE, Mesh::rot, Mesh::size, size(), Mesh::texflag, and zero_v3().
Referenced by mesh_get_bb(), mesh_get_texspace(), and nurbs_to_mesh().
static void to_edgesort (struct edgesort * ed, unsigned int v1, unsigned int v2, short is_loose, short is_draw) [static]
Definition at line 878 of file mesh.c.
References edgesort::is_draw, edgesort::is_loose, edgesort::v1, and edgesort::v2.
Referenced by make_edges_mdata().
void transform_mesh_orco_verts (Mesh * me, float(*) orco[3], int totvert, int invert)
Definition at line 744 of file mesh.c.
References co, madd_v3_v3v3v3(), mesh_get_texspace(), NULL, size(), and Mesh::texcomesh.
Referenced by add_orco_dm(), distribute_threads_exec(), distribute_threads_init_data(), face_duplilist(), psys_face_mat(), psys_mat_hair_to_orco(), and vertex_duplilist().
void unlink_mesh (Mesh * me)
Definition at line 387 of file mesh.c.
References Key::id, Material::id, Mesh::key, Mesh::mat, NULL, Mesh::texcomesh, Mesh::totcol, and ID::us.
Referenced by free_mesh(), and free_object().
static int vergedgesort (const void * v1, const void * v2) [static]
Definition at line 892 of file mesh.c.
References edgesort::v1, and edgesort::v2.
Referenced by make_edges_mdata().