Blender: FilterColor Class Reference
FilterColor Class Reference
pixel filter for color calculation
#include <FilterColor.h>
Public Member Functions
FilterColor (void)
constructor
virtual ~FilterColor (void)
destructor
ColorMatrix & getMatrix (void)
get color matrix
void setMatrix (ColorMatrix &mat)
set color matrix
Protected Member Functions
unsigned char calcColor (unsigned int val, short idx)
calculate one color component
template<class SRC >
unsigned int tFilter (SRC src, short x, short y, short *size, unsigned int pixSize, unsigned int val)
filter pixel template, source int buffer
virtual unsigned int filter (unsigned char *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for byte source
virtual unsigned int filter (unsigned int *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for unsigned int source
Protected Attributes
ColorMatrix m_matrix
color calculation matrix
Detailed Description
pixel filter for color calculation
Definition at line 74 of file FilterColor.h.
Constructor & Destructor Documentation
FilterColor::FilterColor (void)
constructor
Definition at line 91 of file FilterColor.cpp.
References m_matrix.
virtual FilterColor::~FilterColor (void) [inline, virtual]
destructor
Definition at line 80 of file FilterColor.h.
Member Function Documentation
unsigned char FilterColor::calcColor (unsigned int val, short idx) [inline, protected]
calculate one color component
Definition at line 92 of file FilterColor.h.
References m_matrix, VT_A, VT_B, VT_G, and VT_R.
Referenced by tFilter().
virtual unsigned int FilterColor::filter (unsigned char * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for byte source
Reimplemented from FilterBase.
Definition at line 110 of file FilterColor.h.
References tFilter().
virtual unsigned int FilterColor::filter (unsigned int * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for unsigned int source
Reimplemented from FilterBase.
Definition at line 114 of file FilterColor.h.
References tFilter().
ColorMatrix& FilterColor::getMatrix (void) [inline]
get color matrix
Definition at line 83 of file FilterColor.h.
References m_matrix.
Referenced by getMatrix().
void FilterColor::setMatrix (ColorMatrix & mat)
set color matrix
Definition at line 100 of file FilterColor.cpp.
References m_matrix.
Referenced by setMatrix().
template<class SRC > unsigned int FilterColor::tFilter (SRC src, short x, short y, short * size, unsigned int pixSize, unsigned int val) [inline, protected]
filter pixel template, source int buffer
Definition at line 100 of file FilterColor.h.
References calcColor(), and VT_RGBA.
Referenced by filter().
Member Data Documentation
ColorMatrix FilterColor::m_matrix [protected]
color calculation matrix
Definition at line 89 of file FilterColor.h.
Referenced by calcColor(), FilterColor(), getMatrix(), and setMatrix().
The documentation for this class was generated from the following files:
FilterColor.h
FilterColor.cpp