Blender: object_relations.c File Reference
object_relations.c File Reference
object
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_anim_types.h"
#include "DNA_mesh_types.h"
#include "DNA_constraint_types.h"
#include "DNA_group_types.h"
#include "DNA_lamp_types.h"
#include "DNA_lattice_types.h"
#include "DNA_material_types.h"
#include "DNA_meta_types.h"
#include "DNA_particle_types.h"
#include "DNA_scene_types.h"
#include "DNA_speaker_types.h"
#include "DNA_world_types.h"
#include "DNA_object_types.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "BKE_action.h"
#include "BKE_animsys.h"
#include "BKE_armature.h"
#include "BKE_camera.h"
#include "BKE_context.h"
#include "BKE_constraint.h"
#include "BKE_curve.h"
#include "BKE_depsgraph.h"
#include "BKE_DerivedMesh.h"
#include "BKE_displist.h"
#include "BKE_global.h"
#include "BKE_fcurve.h"
#include "BKE_lamp.h"
#include "BKE_lattice.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_material.h"
#include "BKE_mball.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_object.h"
#include "BKE_report.h"
#include "BKE_sca.h"
#include "BKE_scene.h"
#include "BKE_speaker.h"
#include "BKE_texture.h"
#include "BKE_tessmesh.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "ED_armature.h"
#include "ED_curve.h"
#include "ED_keyframing.h"
#include "ED_object.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "object_intern.h"
Enumerations
enum {
MAKE_LINKS_OBDATA = 1, MAKE_LINKS_MATERIALS, MAKE_LINKS_ANIMDATA, MAKE_LINKS_DUPLIGROUP,
MAKE_LINKS_MODIFIERS
}
Functions
static int vertex_parent_set_poll (bContext *C)
static int vertex_parent_set_exec (bContext *C, wmOperator *op)
void OBJECT_OT_vertex_parent_set (wmOperatorType *ot)
static int make_proxy_invoke (bContext *C, wmOperator *op, wmEvent *evt)
static int make_proxy_exec (bContext *C, wmOperator *op)
static EnumPropertyItem * proxy_group_object_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
void OBJECT_OT_proxy_make (wmOperatorType *ot)
void ED_object_parent_clear (bContext *C, int type)
static int parent_clear_exec (bContext *C, wmOperator *op)
void OBJECT_OT_parent_clear (wmOperatorType *ot)
void ED_object_parent (Object *ob, Object *par, int type, const char *substr)
int ED_object_parent_set (ReportList *reports, Main *bmain, Scene *scene, Object *ob, Object *par, int partype)
static int parent_set_exec (bContext *C, wmOperator *op)
static int parent_set_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
void OBJECT_OT_parent_set (wmOperatorType *ot)
static int parent_noinv_set_exec (bContext *C, wmOperator *op)
void OBJECT_OT_parent_no_inverse_set (wmOperatorType *ot)
static int object_slow_parent_clear_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_slow_parent_clear (wmOperatorType *ot)
static int object_slow_parent_set_exec (bContext *C, wmOperator *UNUSED(op))
void OBJECT_OT_slow_parent_set (wmOperatorType *ot)
static int object_track_clear_exec (bContext *C, wmOperator *op)
void OBJECT_OT_track_clear (wmOperatorType *ot)
static int track_set_exec (bContext *C, wmOperator *op)
void OBJECT_OT_track_set (wmOperatorType *ot)
static unsigned int move_to_layer_init (bContext *C, wmOperator *op)
static int move_to_layer_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int move_to_layer_exec (bContext *C, wmOperator *op)
void OBJECT_OT_move_to_layer (wmOperatorType *ot)
static int make_links_scene_exec (bContext *C, wmOperator *op)
static int allow_make_links_data (int ev, Object *ob, Object *obt)
static int make_links_data_exec (bContext *C, wmOperator *op)
void OBJECT_OT_make_links_scene (wmOperatorType *ot)
void OBJECT_OT_make_links_data (wmOperatorType *ot)
static void single_object_users (Scene *scene, View3D *v3d, int flag)
void ED_object_single_user (Scene *scene, Object *ob)
static void new_id_matar (Material **matar, int totcol)
static void single_obdata_users (Main *bmain, Scene *scene, int flag)
static void single_object_action_users (Scene *scene, int flag)
static void single_mat_users (Scene *scene, int flag, int do_textures)
static void do_single_tex_user (Tex **from)
static void single_tex_users_expand (Main *bmain)
static void single_mat_users_expand (Main *bmain)
void ED_object_single_users (Main *bmain, Scene *scene, int full)
static void make_local_makelocalmaterial (Material *ma)
static int make_local_exec (bContext *C, wmOperator *op)
void OBJECT_OT_make_local (wmOperatorType *ot)
static int make_single_user_exec (bContext *C, wmOperator *op)
void OBJECT_OT_make_single_user (wmOperatorType *ot)
static int drop_named_material_invoke (bContext *C, wmOperator *op, wmEvent *event)
void OBJECT_OT_drop_named_material (wmOperatorType *ot)
Variables
EnumPropertyItem prop_clear_parent_types []
EnumPropertyItem prop_make_parent_types []
static EnumPropertyItem prop_clear_track_types []
static EnumPropertyItem prop_make_track_types []
Detailed Description
Definition in file object_relations.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
MAKE_LINKS_OBDATA
MAKE_LINKS_MATERIALS
MAKE_LINKS_ANIMDATA
MAKE_LINKS_DUPLIGROUP
MAKE_LINKS_MODIFIERS
Definition at line 1224 of file object_relations.c.
Function Documentation
static int allow_make_links_data (int ev, Object * ob, Object * obt) [static]
Definition at line 1233 of file object_relations.c.
References MAKE_LINKS_ANIMDATA, MAKE_LINKS_DUPLIGROUP, MAKE_LINKS_MATERIALS, MAKE_LINKS_MODIFIERS, MAKE_LINKS_OBDATA, OB_EMPTY, OB_TYPE_SUPPORT_MATERIAL, and Object::type.
Referenced by make_links_data_exec().
static void do_single_tex_user (Tex ** from) [static]
Definition at line 1584 of file object_relations.c.
References BKE_copy_animdata_id_action(), copy_texture(), Tex::id, id_us_plus(), ID::newid, NULL, and ID::us.
Referenced by single_tex_users_expand().
static int drop_named_material_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1890 of file object_relations.c.
References assign_material(), CTX_data_main(), CTX_wm_view3d(), DAG_ids_flush_update(), ED_view3d_give_base_under_cursor(), find_id(), MAX_ID_NAME, wmEvent::mval, NC_SPACE, ND_SPACE_VIEW3D, NULL, Base::object, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_string_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_drop_named_material().
void ED_object_parent (Object * ob, Object * par, int type, const char * substr)
Definition at line 485 of file object_relations.c.
References BKE_object_parent_loop_check(), BLI_strncpy(), NULL, Object::parent, PAROBJECT, Object::parsubstr, PARTYPE, and Object::partype.
void ED_object_parent_clear (bContext * C, int type)
Definition at line 426 of file object_relations.c.
References CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), FALSE, NC_OBJECT, ND_PARENT, ND_TRANSFORM, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, object_apply_mat4(), TRUE, unit_m4(), and WM_event_add_notifier().
Referenced by parent_clear_exec(), and parent_clear_invoke().
int ED_object_parent_set (ReportList * reports, Main * bmain, Scene * scene, Object * ob, Object * par, int partype)
Definition at line 519 of file object_relations.c.
References add_fmodifier(), add_ob_constraint(), ARM_GROUPS_AUTO, ARM_GROUPS_ENVELOPE, ARM_GROUPS_NAME, FCurve::bezt, BKE_object_parent_loop_check(), BKE_report(), BLI_strncpy(), RenderData::cfra, CONSTRAINT_OBTYPE_OBJECT, CONSTRAINT_TYPE_FOLLOWPATH, create_vgroups_from_armature(), CU_FOLLOW, CU_PATH, bConstraint::data, data, Object::data, ED_object_modifier_add(), ELEM, ELEM4, ELEM5, eModifierType_Armature, eModifierType_Curve, eModifierType_Lattice, ListBase::first, Curve::flag, FMODIFIER_TYPE_GENERATOR, FCurve::fpt, get_active_posechannel(), get_constraint_target_matrix(), Curve::id, invert_m4_m4(), Object::loc, makeDispListCurveTypes(), FCurve::modifiers, bPoseChannel::name, NULL, OB_ARMATURE, OB_CURVE, OB_FONT, OB_LATTICE, OB_MESH, OB_RECALC_DATA, OB_RECALC_OB, OB_SURF, Object::obmat, PAR_ARMATURE, PAR_ARMATURE_AUTO, PAR_ARMATURE_ENVELOPE, PAR_ARMATURE_NAME, PAR_BONE, PAR_CURVE, PAR_FOLLOW, PAR_LATTICE, PAR_OBJECT, PAR_PATH_CONST, PARBONE, Object::parent, Object::parentinv, PAROBJECT, Object::parsubstr, Object::partype, Scene::r, Object::recalc, RPT_ERROR, sub_v3_v3v3(), bFollowPathConstraint::tar, Object::type, verify_adt_action(), verify_fcurve(), what_does_parent(), and WM_cursor_wait().
Referenced by parent_drop_exec(), parent_drop_invoke(), and parent_set_exec().
void ED_object_single_user (Scene * scene, Object * ob)
Definition at line 1412 of file object_relations.c.
References FIRSTBASE, Base::flag, Base::next, NULL, OB_DONE, Base::object, and single_object_users().
Referenced by template_id_cb().
void ED_object_single_users (Main * bmain, Scene * scene, int full)
Definition at line 1679 of file object_relations.c.
References clear_id_newpoins(), NULL, single_mat_users_expand(), single_obdata_users(), single_object_action_users(), single_object_users(), and single_tex_users_expand().
Referenced by scene_new_exec().
static int make_links_data_exec (bContext * C, wmOperator * op) [static]
Definition at line 1258 of file object_relations.c.
References allow_make_links_data(), assign_material(), BKE_copy_animdata_id(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), CTX_wm_view3d(), DAG_ids_flush_update(), DAG_scene_sort(), Object::data, ED_object_active_context(), FALSE, give_current_material(), id_lib_extern(), id_us_plus(), MAKE_LINKS_ANIMDATA, MAKE_LINKS_DUPLIGROUP, MAKE_LINKS_MATERIALS, MAKE_LINKS_MODIFIERS, MAKE_LINKS_OBDATA, NC_SPACE, ND_SPACE_VIEW3D, OB_DUPLIGROUP, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, object_link_modifiers(), OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), test_object_materials(), Object::totcol, and WM_event_add_notifier().
Referenced by OBJECT_OT_make_links_data().
static int make_links_scene_exec (bContext * C, wmOperator * op) [static]
Definition at line 1187 of file object_relations.c.
References Scene::base, BKE_report(), BLI_addhead(), BLI_findlink(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), Scene::id, id_us_plus(), ID::lib, MEM_mallocN(), NULL, Base::object, object_in_scene(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), and RPT_ERROR.
Referenced by OBJECT_OT_make_links_scene().
static int make_local_exec (bContext * C, wmOperator * op) [static]
Definition at line 1713 of file object_relations.c.
References BKE_animdata_from_id(), BKE_animdata_make_local(), BKE_library_make_local(), clear_id_newpoins(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), give_matarar(), Tex::id, ParticleSettings::id, Material::id, id_lib_extern(), id_make_local(), ID_NEW, make_local_makelocalmaterial(), MAX_MTEX, Lamp::mtex, NC_WINDOW, ParticleSystem::next, NULL, OB_LAMP, OPERATOR_FINISHED, ParticleSystem::part, wmOperator::ptr, RNA_enum_get(), MTex::tex, and WM_event_add_notifier().
Referenced by OBJECT_OT_make_local().
static void make_local_makelocalmaterial (Material * ma) [static]
Definition at line 1696 of file object_relations.c.
References BKE_animdata_from_id(), BKE_animdata_make_local(), Tex::id, Material::id, id_make_local(), MAX_MTEX, Material::mtex, and MTex::tex.
Referenced by make_local_exec().
static int make_proxy_exec (bContext * C, wmOperator * op) [static]
Definition at line 315 of file object_relations.c.
References add_object(), BASACT, Scene::base, BKE_report(), BLI_findlink(), BLI_remlink(), BLI_snprintf(), CTX_data_main(), CTX_data_scene(), DAG_id_tag_update(), DAG_scene_sort(), Object::dup_group, ED_object_active_context(), Group::gobject, Object::id, Object::lay, Base::lay, MAX_ID_NAME, MEM_freeN(), NC_OBJECT, ND_DRAW, NULL, GroupObject::ob, OB_EMPTY, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, object_make_proxy(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, rename_id(), wmOperator::reports, RNA_enum_get(), RPT_ERROR, and WM_event_add_notifier().
Referenced by OBJECT_OT_proxy_make().
static int make_proxy_invoke (bContext * C, wmOperator * op, wmEvent * evt) [static]
Definition at line 279 of file object_relations.c.
References BKE_report(), CTX_data_scene(), Object::dup_group, ED_object_active_context(), Object::id, Group::id, Scene::id, ID::lib, wmOperatorType::name, NULL, OPERATOR_CANCELLED, wmOperator::reports, RPT_ERROR, wmOperator::type, UI_ITEM_O_RETURN_PROPS, uiItemFullO_ptr(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), WM_enum_search_invoke(), and WM_OP_EXEC_REGION_WIN.
Referenced by OBJECT_OT_proxy_make().
static int make_single_user_exec (bContext * C, wmOperator * op) [static]
Definition at line 1831 of file object_relations.c.
References clear_id_newpoins(), CTX_data_main(), CTX_data_scene(), CTX_wm_view3d(), NC_WINDOW, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), single_mat_users(), single_obdata_users(), single_object_action_users(), single_object_users(), TRUE, and WM_event_add_notifier().
Referenced by OBJECT_OT_make_single_user().
static int move_to_layer_exec (bContext * C, wmOperator * op) [static]
Definition at line 1096 of file object_relations.c.
References CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), CTX_wm_view3d(), DAG_scene_sort(), View3D::lay, View3D::localvd, move_to_layer_init(), NC_OBJECT, NC_SCENE, ND_DRAW, ND_LAYER_CONTENT, OPERATOR_CANCELLED, OPERATOR_FINISHED, SELECT, and WM_event_add_notifier().
Referenced by OBJECT_OT_move_to_layer().
static unsigned int move_to_layer_init (bContext * C, wmOperator * op) [static]
Definition at line 1056 of file object_relations.c.
References CTX_DATA_BEGIN, CTX_DATA_END, wmOperator::ptr, RNA_boolean_get_array(), RNA_boolean_set_array(), and RNA_struct_property_is_set().
Referenced by move_to_layer_exec(), and move_to_layer_invoke().
static int move_to_layer_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1084 of file object_relations.c.
References CTX_wm_view3d(), View3D::localvd, move_to_layer_init(), WM_operator_confirm_message(), and WM_operator_props_popup().
Referenced by OBJECT_OT_move_to_layer().
static void new_id_matar (Material ** matar, int totcol) [static]
Definition at line 1424 of file object_relations.c.
References copy_material(), id_us_plus(), ID::lib, ID::newid, NULL, and ID::us.
Referenced by single_mat_users_expand().
void OBJECT_OT_drop_named_material (wmOperatorType * ot)
Definition at line 1912 of file object_relations.c.
References wmOperatorType::description, drop_named_material_invoke(), ED_operator_objectmode(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, MAX_ID_NAME, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_links_data (wmOperatorType * ot)
Definition at line 1344 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAKE_LINKS_ANIMDATA, make_links_data_exec(), MAKE_LINKS_DUPLIGROUP, MAKE_LINKS_MATERIALS, MAKE_LINKS_MODIFIERS, MAKE_LINKS_OBDATA, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_links_scene (wmOperatorType * ot)
Definition at line 1321 of file object_relations.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_links_scene_exec(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_scene_local_itemf(), wmOperatorType::srna, and WM_enum_search_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_local (wmOperatorType * ot)
Definition at line 1806 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_local_exec(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_make_single_user (wmOperatorType * ot)
Definition at line 1860 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_single_user_exec(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), SELECT, wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_move_to_layer (wmOperatorType * ot)
Definition at line 1145 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, move_to_layer_exec(), move_to_layer_invoke(), wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_parent_clear (wmOperatorType * ot)
Definition at line 464 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_clear_exec(), wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_parent_no_inverse_set (wmOperatorType * ot)
Definition at line 787 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active_editable(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_noinv_set_exec(), wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_parent_set (wmOperatorType * ot)
Definition at line 730 of file object_relations.c.
References wmOperatorType::description, ED_operator_object_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, parent_set_exec(), parent_set_invoke(), wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_proxy_make (wmOperatorType * ot)
Definition at line 394 of file object_relations.c.
References wmOperatorType::description, DummyRNA_DEFAULT_items, ED_operator_object_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, make_proxy_exec(), make_proxy_invoke(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, proxy_group_object_itemf(), RNA_def_enum(), RNA_def_enum_funcs(), and wmOperatorType::srna.
Referenced by ED_operatortypes_object().
void OBJECT_OT_slow_parent_clear (wmOperatorType * ot)
Definition at line 828 of file object_relations.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_slow_parent_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_slow_parent_set (wmOperatorType * ot)
Definition at line 867 of file object_relations.c.
References wmOperatorType::description, ED_operator_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_slow_parent_set_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_object().
void OBJECT_OT_track_clear (wmOperatorType * ot)
Definition at line 929 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, object_track_clear_exec(), OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_track_set (wmOperatorType * ot)
Definition at line 1034 of file object_relations.c.
References wmOperatorType::description, ED_operator_objectmode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, track_set_exec(), and WM_menu_invoke().
Referenced by ED_operatortypes_object().
void OBJECT_OT_vertex_parent_set (wmOperatorType * ot)
Definition at line 260 of file object_relations.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, vertex_parent_set_exec(), vertex_parent_set_poll(), and WM_operator_confirm().
Referenced by ED_operatortypes_object().
static int object_slow_parent_clear_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 805 of file object_relations.c.
References CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), NC_SCENE, OB_RECALC_OB, OPERATOR_FINISHED, PARSLOW, where_is_object(), and WM_event_add_notifier().
Referenced by OBJECT_OT_slow_parent_clear().
static int object_slow_parent_set_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 847 of file object_relations.c.
References CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), NC_SCENE, OB_RECALC_OB, OPERATOR_FINISHED, PARSLOW, and WM_event_add_notifier().
Referenced by OBJECT_OT_slow_parent_set().
static int object_track_clear_exec (bContext * C, wmOperator * op) [static]
Definition at line 893 of file object_relations.c.
References BKE_report(), CONSTRAINT_TYPE_DAMPTRACK, CONSTRAINT_TYPE_LOCKTRACK, CONSTRAINT_TYPE_TRACKTO, CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), ELEM3, NC_OBJECT, ND_TRANSFORM, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, object_apply_mat4(), OPERATOR_CANCELLED, OPERATOR_FINISHED, bConstraint::prev, wmOperator::ptr, remove_constraint(), wmOperator::reports, RNA_enum_get(), RPT_ERROR, TRUE, bConstraint::type, and WM_event_add_notifier().
Referenced by OBJECT_OT_track_clear().
static int parent_clear_exec (bContext * C, wmOperator * op) [static]
Definition at line 457 of file object_relations.c.
References ED_object_parent_clear(), OPERATOR_FINISHED, wmOperator::ptr, and RNA_enum_get().
Referenced by OBJECT_OT_parent_clear().
static int parent_noinv_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 751 of file object_relations.c.
References BKE_object_parent_loop_check(), BKE_report(), CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), ED_object_active_context(), NC_OBJECT, ND_TRANSFORM, NULL, OB_RECALC_DATA, OB_RECALC_OB, OPERATOR_FINISHED, PAROBJECT, Object::partype, Object::recalc, wmOperator::reports, RPT_ERROR, unit_m4(), and WM_event_add_notifier().
Referenced by OBJECT_OT_parent_no_inverse_set().
static int parent_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 669 of file object_relations.c.
References CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), ED_object_active_context(), ED_object_parent_set(), NC_OBJECT, ND_PARENT, ND_TRANSFORM, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), and WM_event_add_notifier().
Referenced by OBJECT_OT_parent_set().
static int parent_set_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 698 of file object_relations.c.
References ED_object_active_context(), NULL, OB_ARMATURE, OB_CURVE, OB_LATTICE, OPERATOR_CANCELLED, PAR_ARMATURE, PAR_ARMATURE_AUTO, PAR_ARMATURE_ENVELOPE, PAR_ARMATURE_NAME, PAR_BONE, PAR_CURVE, PAR_FOLLOW, PAR_LATTICE, PAR_OBJECT, PAR_PATH_CONST, Object::type, uiItemEnumO(), uiLayoutSetOperatorContext(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), and WM_OP_EXEC_DEFAULT.
Referenced by OBJECT_OT_parent_set().
static EnumPropertyItem* proxy_group_object_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 370 of file object_relations.c.
References DummyRNA_DEFAULT_items, Object::dup_group, ED_object_active_context(), ListBase::first, Group::gobject, i, Object::id, EnumPropertyItem::identifier, EnumPropertyItem::name, ID::name, GroupObject::next, NULL, GroupObject::ob, RNA_enum_item_add(), RNA_enum_item_end(), and EnumPropertyItem::value.
Referenced by OBJECT_OT_proxy_make().
static void single_mat_users (Scene * scene, int flag, int do_textures) [static]
Definition at line 1541 of file object_relations.c.
References assign_material(), BKE_copy_animdata_id_action(), copy_material(), copy_texture(), FIRSTBASE, Base::flag, give_current_material(), Tex::id, Material::id, Object::id, ID::lib, MAX_MTEX, Material::mtex, Base::next, NULL, Base::object, SELECT, MTex::tex, Object::totcol, and ID::us.
Referenced by make_single_user_exec().
static void single_mat_users_expand (Main * bmain) [static]
Definition at line 1644 of file object_relations.c.
References Main::curve, ListBase::first, ID::flag, Material::id, MetaBall::id, Curve::id, Mesh::id, Object::id, ID_NEW, LIB_NEW, Main::mat, MetaBall::mat, Curve::mat, Mesh::mat, Object::mat, MAX_MTEX, Main::mball, Main::mesh, Material::mtex, new_id_matar(), ID::next, MTex::object, Main::object, MetaBall::totcol, Curve::totcol, Mesh::totcol, and Object::totcol.
Referenced by ED_object_single_users().
static void single_obdata_users (Main * bmain, Scene * scene, int flag) [static]
Definition at line 1446 of file object_relations.c.
References armature_rebuild_pose(), Curve::bevobj, BKE_copy_animdata_id_action(), copy_armature(), copy_camera(), copy_curve(), copy_lamp(), copy_lattice(), copy_mball(), copy_mesh(), copy_speaker(), Object::data, ListBase::first, FIRSTBASE, Base::flag, G, G_DEBUG, Mesh::id, Object::id, ID_NEW, ID::lib, MAX_MTEX, Main::mesh, Lamp::mtex, ID::name, ID::next, Base::next, NULL, OB_ARMATURE, OB_CAMERA, OB_CURVE, OB_FONT, OB_LAMP, OB_LATTICE, OB_MBALL, OB_MESH, OB_RECALC_DATA, OB_SPEAKER, OB_SURF, MTex::object, Base::object, Object::recalc, Curve::taperobj, Mesh::texcomesh, Object::type, and ID::us.
Referenced by ED_object_single_users(), and make_single_user_exec().
static void single_object_action_users (Scene * scene, int flag) [static]
Definition at line 1527 of file object_relations.c.
References BKE_copy_animdata_id_action(), FIRSTBASE, Base::flag, Object::id, ID::lib, Base::next, NULL, OB_RECALC_DATA, Base::object, Object::recalc, and SELECT.
Referenced by ED_object_single_users(), and make_single_user_exec().
static void single_object_users (Scene * scene, View3D * v3d, int flag) [static]
Definition at line 1373 of file object_relations.c.
References View3D::camera, Scene::camera, clear_sca_new_poins(), copy_object(), FIRSTBASE, Base::flag, Object::id, ID_NEW, ID::lib, ID::newid, Base::next, NULL, Base::object, object_relink(), set_sca_new_poins(), and ID::us.
Referenced by ED_object_single_user(), ED_object_single_users(), and make_single_user_exec().
static void single_tex_users_expand (Main * bmain) [static]
Definition at line 1605 of file object_relations.c.
References do_single_tex_user(), ListBase::first, ID::flag, Material::id, World::id, Lamp::id, Main::lamp, LIB_NEW, Main::mat, MAX_MTEX, Lamp::mtex, World::mtex, Material::mtex, ID::next, MTex::tex, and Main::world.
Referenced by ED_object_single_users().
static int track_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 957 of file object_relations.c.
References add_ob_constraint(), CONSTRAINT_TYPE_DAMPTRACK, CONSTRAINT_TYPE_LOCKTRACK, CONSTRAINT_TYPE_TRACKTO, CTX_DATA_BEGIN, CTX_DATA_END, CTX_data_main(), CTX_data_scene(), DAG_ids_flush_update(), DAG_scene_sort(), bConstraint::data, data, ED_object_active_context(), LOCK_Y, bLockTrackConstraint::lockflag, NC_OBJECT, ND_TRANSFORM, NULL, OB_CAMERA, OB_LAMP, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, OB_SPEAKER, OPERATOR_FINISHED, wmOperator::ptr, Object::recalc, bTrackToConstraint::reserved1, bTrackToConstraint::reserved2, RNA_enum_get(), bLockTrackConstraint::tar, bTrackToConstraint::tar, bDampTrackConstraint::tar, TRACK_nZ, bLockTrackConstraint::trackflag, bDampTrackConstraint::trackflag, UP_Y, and WM_event_add_notifier().
Referenced by OBJECT_OT_track_set().
static int vertex_parent_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 111 of file object_relations.c.
References BASACT, BEZSELECTED_HIDDENHANDLES, Nurb::bezt, BKE_report(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, Nurb::bp, CD_MASK_BAREMESH, CTX_DATA_BEGIN, CTX_data_edit_object(), CTX_DATA_END, CTX_data_main(), CTX_data_scene(), CU_BEZIER, DAG_scene_sort(), Object::data, Lattice::def, EDBM_mesh_load(), EDBM_mesh_make(), Mesh::edit_btmesh, Lattice::editlatt, ELEM, BPoint::f1, ListBase::first, invert_m4_m4(), EditLatt::latt, makeDerivedMesh(), NC_OBJECT, Nurb::next, NULL, OB_CURVE, OB_LATTICE, OB_MESH, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, OB_SURF, object_editcurve_get(), Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, Object::parent, PARVERT1, PARVERT3, Lattice::pntsu, Nurb::pntsu, Lattice::pntsv, Nurb::pntsv, Lattice::pntsw, wmOperator::reports, RPT_ERROR, SELECT, Scene::toolsettings, Nurb::type, Object::type, what_does_parent(), and WM_event_add_notifier().
Referenced by OBJECT_OT_vertex_parent_set().
static int vertex_parent_set_poll (bContext * C) [static]
Definition at line 106 of file object_relations.c.
References ED_operator_editlattice(), ED_operator_editmesh(), and ED_operator_editsurfcurve().
Referenced by OBJECT_OT_vertex_parent_set().
Variable Documentation
EnumPropertyItem prop_clear_parent_types[]
Initial value:
 {
    {0, "CLEAR", 0, "Clear Parent", ""},
    {1, "CLEAR_KEEP_TRANSFORM", 0, "Clear and Keep Transformation", ""},
    {2, "CLEAR_INVERSE", 0, "Clear Parent Inverse", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 419 of file object_relations.c.
Referenced by OUTLINER_OT_parent_clear().
EnumPropertyItem prop_clear_track_types[] [static]
Initial value:
 {
    {0, "CLEAR", 0, "Clear Track", ""},
    {1, "CLEAR_KEEP_TRANSFORM", 0, "Clear and Keep Transformation (Clear Track)", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 886 of file object_relations.c.
EnumPropertyItem prop_make_parent_types[]
Initial value:
 {
    {PAR_OBJECT, "OBJECT", 0, "Object", ""},
    {PAR_ARMATURE, "ARMATURE", 0, "Armature Deform", ""},
    {PAR_ARMATURE_NAME, "ARMATURE_NAME", 0, "   With Empty Groups", ""},
    {PAR_ARMATURE_AUTO, "ARMATURE_AUTO", 0, "   With Automatic Weights", ""},
    {PAR_ARMATURE_ENVELOPE, "ARMATURE_ENVELOPE", 0, "   With Envelope Weights", ""},
    {PAR_BONE, "BONE", 0, "Bone", ""},
    {PAR_CURVE, "CURVE", 0, "Curve Deform", ""},
    {PAR_FOLLOW, "FOLLOW", 0, "Follow Path", ""},
    {PAR_PATH_CONST, "PATH_CONST", 0, "Path Constraint", ""},
    {PAR_LATTICE, "LATTICE", 0, "Lattice Deform", ""},
    {PAR_VERTEX, "VERTEX", 0, "Vertex", ""},
    {PAR_TRIA, "TRIA", 0, "Triangle", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 503 of file object_relations.c.
Referenced by OUTLINER_OT_parent_drop().
EnumPropertyItem prop_make_track_types[] [static]
Initial value:
 {
    {1, "DAMPTRACK", 0, "Damped Track Constraint", ""},
    {2, "TRACKTO", 0, "Track To Constraint", ""},
    {3, "LOCKTRACK", 0, "Lock Track Constraint", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 950 of file object_relations.c.