Blender: blender_camera.cpp File Reference
blender_camera.cpp File Reference
#include "camera.h"
#include "scene.h"
#include "blender_sync.h"
#include "blender_util.h"
Classes
struct BlenderCamera
Functions
static void blender_camera_init (BlenderCamera *bcam)
static float blender_camera_focal_distance (BL::Object b_ob, BL::Camera b_camera)
static void blender_camera_from_object (BlenderCamera *bcam, BL::Object b_ob)
static void blender_camera_sync (Camera *cam, BlenderCamera *bcam, int width, int height)
Function Documentation
static float blender_camera_focal_distance (BL::Object b_ob, BL::Camera b_camera) [static]
Definition at line 69 of file blender_camera.cpp.
References fabsf, get_transform(), transform_clear_scale(), transform_get_column(), and transform_inverse().
Referenced by blender_camera_from_object().
static void blender_camera_from_object (BlenderCamera * bcam, BL::Object b_ob) [static]
Definition at line 84 of file blender_camera.cpp.
References BlenderCamera::apertureblades, BlenderCamera::aperturerotation, BlenderCamera::aperturesize, BlenderCamera::AUTO, blender_camera_focal_distance(), CAMERA_ENVIRONMENT, CAMERA_ORTHOGRAPHIC, CAMERA_PERSPECTIVE, BlenderCamera::farclip, BlenderCamera::focaldistance, BlenderCamera::HORIZONTAL, BlenderCamera::lens, max, BlenderCamera::nearclip, BlenderCamera::ortho_scale, RNA_Camera, RNA_enum_get(), RNA_float_get(), RNA_int_get(), RNA_pointer_get(), BlenderCamera::sensor_fit, BlenderCamera::sensor_height, BlenderCamera::sensor_width, BlenderCamera::shift, BlenderCamera::type, BlenderCamera::VERTICAL, float2::x, and float2::y.
Referenced by BlenderSync::sync_camera(), and BlenderSync::sync_view().
static void blender_camera_init (BlenderCamera * bcam) [static]
Definition at line 57 of file blender_camera.cpp.
References BlenderCamera::AUTO, CAMERA_PERSPECTIVE, make_float2(), BlenderCamera::pixelaspect, BlenderCamera::sensor_fit, BlenderCamera::sensor_height, BlenderCamera::sensor_width, BlenderCamera::type, and BlenderCamera::zoom.
Referenced by BlenderSync::sync_camera(), and BlenderSync::sync_view().
static void blender_camera_sync (Camera * cam, BlenderCamera * bcam, int width, int height) [static]
Definition at line 135 of file blender_camera.cpp.
References BlenderCamera::apertureblades, BlenderCamera::aperturerotation, BlenderCamera::aperturesize, Camera::aperturesize, KDL::atan(), BlenderCamera::AUTO, Camera::blades, Camera::bladesrotation, Camera::bottom, CAMERA_ENVIRONMENT, CAMERA_ORTHOGRAPHIC, BlenderCamera::farclip, Camera::farclip, Camera::focaldistance, BlenderCamera::focaldistance, Camera::fov, BlenderCamera::HORIZONTAL, Camera::left, BlenderCamera::lens, make_transform(), Camera::matrix, BlenderCamera::matrix, Camera::modified(), Camera::nearclip, BlenderCamera::nearclip, BlenderCamera::offset, BlenderCamera::ortho_scale, BlenderCamera::pixelaspect, Camera::right, BlenderCamera::sensor_fit, BlenderCamera::sensor_height, BlenderCamera::sensor_width, BlenderCamera::shift, Camera::tag_update(), Camera::top, transform_clear_scale(), transform_scale(), Camera::type, BlenderCamera::type, float2::x, float2::y, and BlenderCamera::zoom.
Referenced by BlenderSync::sync_camera(), and BlenderSync::sync_view().