Blender: frames.inl File Reference
frames.inl File Reference
Functions
IMETHOD Vector operator+ (const Vector &lhs, const Vector &rhs)
IMETHOD Vector operator- (const Vector &lhs, const Vector &rhs)
Vector operator* (const Vector &lhs, double rhs)
Vector operator* (double lhs, const Vector &rhs)
Vector operator/ (const Vector &lhs, double rhs)
Vector operator* (const Vector &lhs, const Vector &rhs)
IMETHOD Vector Normalize (const Vector &a, double eps)
Wrench operator* (const Wrench &lhs, double rhs)
Wrench operator* (double lhs, const Wrench &rhs)
Wrench operator/ (const Wrench &lhs, double rhs)
Wrench operator+ (const Wrench &lhs, const Wrench &rhs)
Wrench operator- (const Wrench &lhs, const Wrench &rhs)
Wrench operator- (const Wrench &arg)
Twist operator* (const Twist &lhs, double rhs)
Twist operator* (double lhs, const Twist &rhs)
Twist operator/ (const Twist &lhs, double rhs)
Twist operator+ (const Twist &lhs, const Twist &rhs)
Twist operator- (const Twist &lhs, const Twist &rhs)
Twist operator- (const Twist &arg)
Frame operator* (const Frame &lhs, const Frame &rhs)
Vector operator- (const Vector &arg)
IMETHOD Vector2 operator+ (const Vector2 &lhs, const Vector2 &rhs)
IMETHOD Vector2 operator- (const Vector2 &lhs, const Vector2 &rhs)
IMETHOD Vector2 operator* (const Vector2 &lhs, double rhs)
IMETHOD Vector2 operator* (double lhs, const Vector2 &rhs)
IMETHOD Vector2 operator/ (const Vector2 &lhs, double rhs)
IMETHOD Vector2 operator- (const Vector2 &arg)
IMETHOD Rotation2 operator* (const Rotation2 &lhs, const Rotation2 &rhs)
IMETHOD Frame2 operator* (const Frame2 &lhs, const Frame2 &rhs)
IMETHOD double dot (const Vector &lhs, const Vector &rhs)
IMETHOD double dot (const Twist &lhs, const Wrench &rhs)
IMETHOD double dot (const Wrench &rhs, const Twist &lhs)
IMETHOD bool Equal (const Vector &a, const Vector &b, double eps)
IMETHOD bool Equal (const Frame &a, const Frame &b, double eps)
IMETHOD bool Equal (const Wrench &a, const Wrench &b, double eps)
IMETHOD bool Equal (const Twist &a, const Twist &b, double eps)
IMETHOD bool Equal (const Vector2 &a, const Vector2 &b, double eps)
IMETHOD bool Equal (const Rotation2 &a, const Rotation2 &b, double eps)
IMETHOD bool Equal (const Frame2 &a, const Frame2 &b, double eps)
IMETHOD void SetToZero (Vector &v)
IMETHOD void SetToZero (Twist &v)
IMETHOD void SetToZero (Wrench &v)
IMETHOD void SetToZero (Vector2 &v)
IMETHOD Rotation Rot (const Vector &axis_a_b)
IMETHOD Vector diff (const Vector &a, const Vector &b, double dt)
IMETHOD Vector diff (const Rotation &R_a_b1, const Rotation &R_a_b2, double dt)
diff operator for displacement rotational velocity.
IMETHOD Twist diff (const Frame &F_a_b1, const Frame &F_a_b2, double dt)
IMETHOD Twist diff (const Twist &a, const Twist &b, double dt)
IMETHOD Wrench diff (const Wrench &a, const Wrench &b, double dt)
IMETHOD Vector addDelta (const Vector &a, const Vector &da, double dt)
IMETHOD Rotation addDelta (const Rotation &a, const Vector &da, double dt)
IMETHOD Frame addDelta (const Frame &a, const Twist &da, double dt)
IMETHOD Twist addDelta (const Twist &a, const Twist &da, double dt)
IMETHOD Wrench addDelta (const Wrench &a, const Wrench &da, double dt)
IMETHOD void random (Vector &a)
addDelta operator for displacement rotational velocity.
IMETHOD void random (Twist &a)
IMETHOD void random (Wrench &a)
IMETHOD void random (Rotation &R)
IMETHOD void random (Frame &F)
IMETHOD void posrandom (Vector &a)
IMETHOD void posrandom (Twist &a)
IMETHOD void posrandom (Wrench &a)
IMETHOD void posrandom (Rotation &R)
IMETHOD void posrandom (Frame &F)
IMETHOD bool operator== (const Frame &a, const Frame &b)
IMETHOD bool operator!= (const Frame &a, const Frame &b)
IMETHOD bool operator== (const Vector &a, const Vector &b)
IMETHOD bool operator!= (const Vector &a, const Vector &b)
IMETHOD bool operator== (const Twist &a, const Twist &b)
IMETHOD bool operator!= (const Twist &a, const Twist &b)
IMETHOD bool operator== (const Wrench &a, const Wrench &b)
IMETHOD bool operator!= (const Wrench &a, const Wrench &b)
IMETHOD bool operator!= (const Rotation &a, const Rotation &b)
Function Documentation
IMETHOD Vector addDelta (const Vector & a, const Vector & da, double dt)
Definition at line 1216 of file frames.inl.
IMETHOD Rotation addDelta (const Rotation & a, const Vector & da, double dt)
Definition at line 1220 of file frames.inl.
References Rot().
IMETHOD Frame addDelta (const Frame & a, const Twist & da, double dt)
Definition at line 1223 of file frames.inl.
References KDL::addDelta().
IMETHOD Twist addDelta (const Twist & a, const Twist & da, double dt)
Definition at line 1229 of file frames.inl.
References KDL::addDelta().
IMETHOD Wrench addDelta (const Wrench & a, const Wrench & da, double dt)
Definition at line 1232 of file frames.inl.
References KDL::addDelta().
IMETHOD Vector diff (const Rotation & R_a_b1, const Rotation & R_a_b2, double dt)
diff operator for displacement rotational velocity.
The Vector arguments here represent a displacement rotational velocity. i.e. a rotation around a fixed axis for a certain angle. For this representation you cannot use diff() but have to use diff_displ().
represent a displacement twist and displacement rotational velocity with another class, instead of Vector and Twist.
Warning:
do not confuse displacement rotational velocities and velocities
do not confuse displacement twist and twist.
IMETHOD Vector diff_displ(const Vector& a,const Vector& b,double dt) { return diff(Rot(a),Rot(b),dt); } diff operator for displacement twist.
The Twist arguments here represent a displacement twist. i.e. a rotation around a fixed axis for a certain angle. For this representation you cannot use diff() but have to use diff_displ().
Warning:
do not confuse displacement rotational velocities and velocities
do not confuse displacement twist and twist.
IMETHOD Twist diff_displ(const Twist& a,const Twist& b,double dt) { return Twist(diff(a.vel,b.vel,dt),diff(Rot(a.rot),Rot(b.rot),dt)); }
Definition at line 1194 of file frames.inl.
References Rotation().
IMETHOD Twist diff (const Frame & F_a_b1, const Frame & F_a_b2, double dt)
Definition at line 1198 of file frames.inl.
References KDL::diff().
IMETHOD Twist diff (const Twist & a, const Twist & b, double dt)
Definition at line 1204 of file frames.inl.
References KDL::diff().
IMETHOD Wrench diff (const Wrench & a, const Wrench & b, double dt)
Definition at line 1208 of file frames.inl.
References KDL::diff().
IMETHOD Vector diff (const Vector & a, const Vector & b, double dt)
Definition at line 1158 of file frames.inl.
IMETHOD double dot (const Vector & lhs, const Vector & rhs)
Definition at line 1040 of file frames.inl.
IMETHOD double dot (const Wrench & rhs, const Twist & lhs)
Definition at line 1048 of file frames.inl.
References KDL::dot().
IMETHOD double dot (const Twist & lhs, const Wrench & rhs)
Definition at line 1044 of file frames.inl.
References KDL::dot().
IMETHOD bool Equal (const Vector & a, const Vector & b, double eps)
Definition at line 1060 of file frames.inl.
References KDL::Equal().
IMETHOD bool Equal (const Frame & a, const Frame & b, double eps)
Definition at line 1067 of file frames.inl.
References KDL::Equal().
IMETHOD bool Equal (const Wrench & a, const Wrench & b, double eps)
Definition at line 1072 of file frames.inl.
References KDL::Equal().
IMETHOD bool Equal (const Twist & a, const Twist & b, double eps)
Definition at line 1077 of file frames.inl.
References KDL::Equal().
IMETHOD bool Equal (const Vector2 & a, const Vector2 & b, double eps)
Definition at line 1082 of file frames.inl.
References KDL::Equal().
IMETHOD bool Equal (const Rotation2 & a, const Rotation2 & b, double eps)
Definition at line 1087 of file frames.inl.
References KDL::Equal().
IMETHOD bool Equal (const Frame2 & a, const Frame2 & b, double eps)
Definition at line 1091 of file frames.inl.
References KDL::Equal().
IMETHOD Vector Normalize (const Vector & a, double eps)
Definition at line 162 of file frames.inl.
IMETHOD bool operator!= (const Frame & a, const Frame & b)
Definition at line 1344 of file frames.inl.
References KDL::operator==().
IMETHOD bool operator!= (const Vector & a, const Vector & b)
Definition at line 1358 of file frames.inl.
References KDL::operator==().
IMETHOD bool operator!= (const Twist & a, const Twist & b)
Definition at line 1371 of file frames.inl.
References KDL::operator==().
IMETHOD bool operator!= (const Wrench & a, const Wrench & b)
Definition at line 1384 of file frames.inl.
References KDL::operator==().
IMETHOD bool operator!= (const Rotation & a, const Rotation & b)
Definition at line 1387 of file frames.inl.
References KDL::operator==().
Wrench operator* (const Wrench & lhs, double rhs)
Definition at line 254 of file frames.inl.
Wrench operator* (double lhs, const Wrench & rhs)
Definition at line 259 of file frames.inl.
Frame operator* (const Frame & lhs, const Frame & rhs)
Definition at line 407 of file frames.inl.
IMETHOD Vector2 operator* (const Vector2 & lhs, double rhs)
Definition at line 793 of file frames.inl.
IMETHOD Vector2 operator* (double lhs, const Vector2 & rhs)
Definition at line 798 of file frames.inl.
Vector operator* (double lhs, const Vector & rhs)
Definition at line 100 of file frames.inl.
Twist operator* (const Twist & lhs, double rhs)
Definition at line 357 of file frames.inl.
IMETHOD Rotation2 operator* (const Rotation2 & lhs, const Rotation2 & rhs)
Definition at line 898 of file frames.inl.
IMETHOD Frame2 operator* (const Frame2 & lhs, const Frame2 & rhs)
Definition at line 958 of file frames.inl.
Vector operator* (const Vector & lhs, double rhs)
Definition at line 91 of file frames.inl.
Twist operator* (double lhs, const Twist & rhs)
Definition at line 362 of file frames.inl.
Vector operator* (const Vector & lhs, const Vector & rhs)
Definition at line 118 of file frames.inl.
IMETHOD Vector operator+ (const Vector & lhs, const Vector & rhs)
Definition at line 65 of file frames.inl.
Wrench operator+ (const Wrench & lhs, const Wrench & rhs)
Definition at line 270 of file frames.inl.
IMETHOD Vector2 operator+ (const Vector2 & lhs, const Vector2 & rhs)
Definition at line 783 of file frames.inl.
Twist operator+ (const Twist & lhs, const Twist & rhs)
Definition at line 373 of file frames.inl.
IMETHOD Vector2 operator- (const Vector2 & lhs, const Vector2 & rhs)
Definition at line 788 of file frames.inl.
Wrench operator- (const Wrench & lhs, const Wrench & rhs)
Definition at line 275 of file frames.inl.
Twist operator- (const Twist & arg)
Definition at line 384 of file frames.inl.
Vector operator- (const Vector & arg)
Definition at line 450 of file frames.inl.
IMETHOD Vector operator- (const Vector & lhs, const Vector & rhs)
Definition at line 74 of file frames.inl.
Twist operator- (const Twist & lhs, const Twist & rhs)
Definition at line 378 of file frames.inl.
Wrench operator- (const Wrench & arg)
Definition at line 281 of file frames.inl.
IMETHOD Vector2 operator- (const Vector2 & arg)
Definition at line 843 of file frames.inl.
Twist operator/ (const Twist & lhs, double rhs)
Definition at line 367 of file frames.inl.
IMETHOD Vector2 operator/ (const Vector2 & lhs, double rhs)
Definition at line 803 of file frames.inl.
Wrench operator/ (const Wrench & lhs, double rhs)
Definition at line 264 of file frames.inl.
Vector operator/ (const Vector & lhs, double rhs)
Definition at line 109 of file frames.inl.
IMETHOD bool operator== (const Wrench & a, const Wrench & b)
Definition at line 1375 of file frames.inl.
References KDL::Equal().
IMETHOD bool operator== (const Frame & a, const Frame & b)
Definition at line 1335 of file frames.inl.
References KDL::Equal().
IMETHOD bool operator== (const Twist & a, const Twist & b)
Definition at line 1362 of file frames.inl.
References KDL::Equal().
IMETHOD bool operator== (const Vector & a, const Vector & b)
Definition at line 1348 of file frames.inl.
References KDL::Equal().
IMETHOD void posrandom (Rotation & R)
Definition at line 1317 of file frames.inl.
References KDL::Rotation::EulerZYX(), and KDL::posrandom().
IMETHOD void posrandom (Vector & a)
Definition at line 1303 of file frames.inl.
References KDL::posrandom().
IMETHOD void posrandom (Frame & F)
Definition at line 1327 of file frames.inl.
References KDL::random().
IMETHOD void posrandom (Twist & a)
Definition at line 1308 of file frames.inl.
References KDL::posrandom().
IMETHOD void posrandom (Wrench & a)
Definition at line 1312 of file frames.inl.
References KDL::posrandom().
IMETHOD void random (Frame & F)
Definition at line 1298 of file frames.inl.
References KDL::random().
IMETHOD void random (Vector & a)
addDelta operator for displacement rotational velocity.
The Vector arguments here represent a displacement rotational velocity. i.e. a rotation around a fixed axis for a certain angle. For this representation you cannot use diff() but have to use diff_displ().
Parameters:
a : displacement rotational velocity
da : rotational velocity
Returns:
displacement rotational velocity
Warning:
do not confuse displacement rotational velocities and velocities
do not confuse displacement twist and twist.
IMETHOD Vector addDelta_displ(const Vector& a,const Vector&da,double dt) { return getRot(addDelta(Rot(a),da,dt)); } addDelta operator for displacement twist.
The Vector arguments here represent a displacement rotational velocity. i.e. a rotation around a fixed axis for a certain angle. For this representation you cannot use diff() but have to use diff_displ().
Parameters:
a : displacement twist
da : twist
Returns:
displacement twist
Warning:
do not confuse displacement rotational velocities and velocities
do not confuse displacement twist and twist.
IMETHOD Twist addDelta_displ(const Twist& a,const Twist&da,double dt) { return Twist(addDelta(a.vel,da.vel,dt),addDelta_displ(a.rot,da.rot,dt)); }
Definition at line 1274 of file frames.inl.
References KDL::random().
Referenced by render_new_particle_system(), and wind_func().
IMETHOD void random (Twist & a)
Definition at line 1279 of file frames.inl.
References KDL::random().
IMETHOD void random (Wrench & a)
Definition at line 1283 of file frames.inl.
References KDL::random().
IMETHOD void random (Rotation & R)
Definition at line 1288 of file frames.inl.
References KDL::Rotation::EulerZYX(), and KDL::random().
IMETHOD Rotation Rot (const Vector & axis_a_b)
axis_a_b is a rotation vector, its norm is a rotation angle axis_a_b rotates the a frame towards the b frame. This routine returns the rotation matrix R_a_b
Definition at line 1135 of file frames.inl.
References angle(), KDL::cos(), Rotation(), and KDL::sin().
Referenced by addDelta(), KDL::Joint::pose(), and iTaSC::Armature::updateJoint().
IMETHOD void SetToZero (Vector & v)
Definition at line 1096 of file frames.inl.
References KDL::Vector::Zero().
Referenced by rest_pose(), and SetToZero().
IMETHOD void SetToZero (Wrench & v)
Definition at line 1103 of file frames.inl.
References KDL::SetToZero().
IMETHOD void SetToZero (Twist & v)
Definition at line 1099 of file frames.inl.
References KDL::SetToZero().
IMETHOD void SetToZero (Vector2 & v)
Definition at line 1108 of file frames.inl.
References KDL::Vector2::Zero().