Blender: osl_closures.cpp File Reference
osl_closures.cpp File Reference
#include <OSL/genclosure.h>
#include <OSL/oslclosure.h>
#include "osl_closures.h"
#include "osl_shader.h"
#include "util_debug.h"
#include "util_param.h"
Functions
static CCL_NAMESPACE_BEGIN void generic_closure_setup (OSL::RendererServices *, int id, void *data)
static bool generic_closure_mergeable (int id, const void *dataA, const void *dataB)
static void register_closure (OSL::ShadingSystem *ss, const char *name, int id, OSL::ClosureParam *params, OSL::PrepareClosureFunc prepare)
Function Documentation
static bool generic_closure_mergeable (int id, const void * dataA, const void * dataB) [static]
Definition at line 51 of file osl_closures.cpp.
References assert.
Referenced by register_closure().
static CCL_NAMESPACE_BEGIN void generic_closure_setup (OSL::RendererServices * , int id, void * data) [static]
Definition at line 44 of file osl_closures.cpp.
References assert.
Referenced by register_closure().
static void register_closure (OSL::ShadingSystem * ss, const char * name, int id, OSL::ClosureParam * params, OSL::PrepareClosureFunc prepare) [static]
Definition at line 60 of file osl_closures.cpp.
References generic_closure_mergeable(), generic_closure_setup(), and size().