Blender: rna_controller.c File Reference
rna_controller.c File Reference
RNA
#include <stdlib.h>
#include "WM_types.h"
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_object_types.h"
#include "DNA_controller_types.h"
Functions
void RNA_def_controller (BlenderRNA *brna)
Variables
EnumPropertyItem controller_type_items []
Detailed Description
Definition in file rna_controller.c.
Function Documentation
void RNA_def_controller (BlenderRNA * brna)
Definition at line 184 of file rna_controller.c.
References CONT_PRIO, CONT_PY_DEBUG, CONT_PY_MODULE, CONT_PY_SCRIPT, CONT_SHOW, NC_LOGIC, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, RNA_api_controller(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Variable Documentation
EnumPropertyItem controller_type_items[]
Initial value:
 {
    {CONT_LOGIC_AND, "LOGIC_AND", 0, "And", "Logic And"},
    {CONT_LOGIC_OR, "LOGIC_OR", 0, "Or", "Logic Or"},
    {CONT_LOGIC_NAND, "LOGIC_NAND", 0, "Nand", "Logic Nand"},
    {CONT_LOGIC_NOR, "LOGIC_NOR", 0, "Nor", "Logic Nor"},
    {CONT_LOGIC_XOR, "LOGIC_XOR", 0, "Xor", "Logic Xor"},
    {CONT_LOGIC_XNOR, "LOGIC_XNOR", 0, "Xnor", "Logic Xnor"},
    {CONT_EXPRESSION, "EXPRESSION", 0, "Expression", ""},
    {CONT_PYTHON, "PYTHON", 0, "Python", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 37 of file rna_controller.c.
Referenced by LOGIC_OT_controller_add().