Blender: wm_files.h File Reference
wm_files.h File Reference
windowmanager
Functions
void WM_read_history (void)
Detailed Description
Definition in file wm_files.h.
Function Documentation
void WM_read_history (void)
Definition at line 583 of file wm_files.c.
References BLENDER_HISTORY_FILE, BLENDER_USER_CONFIG, BLI_addtail(), BLI_exists(), BLI_file_free_lines(), BLI_file_read_as_lines(), BLI_get_folder(), BLI_make_file_string(), BLI_strdup(), FILE_MAX, RecentFile::filepath, G, MEM_mallocN(), LinkNode::next, and NULL.
Referenced by WM_init().