Blender: node_composite_sepcombYCCA.c File Reference
node_composite_sepcombYCCA.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_sepycca_601 (bNode *UNUSED(node), float *out, float *in)
static void do_sepycca_709 (bNode *UNUSED(node), float *out, float *in)
static void do_sepycca_jfif (bNode *UNUSED(node), float *out, float *in)
static void node_composit_exec_sepycca (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_sepycca (bNodeTreeType *ttype)
static void do_comb_ycca_601 (bNode *UNUSED(node), float *out, float *in1, float *in2, float *in3, float *in4)
static void do_comb_ycca_709 (bNode *UNUSED(node), float *out, float *in1, float *in2, float *in3, float *in4)
static void do_comb_ycca_jfif (bNode *UNUSED(node), float *out, float *in1, float *in2, float *in3, float *in4)
static void node_composit_exec_combycca (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_combycca (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_sepycca_in []
static bNodeSocketTemplate cmp_node_sepycca_out []
static bNodeSocketTemplate cmp_node_combycca_in []
static bNodeSocketTemplate cmp_node_combycca_out []
Detailed Description
Definition in file node_composite_sepcombYCCA.c.
Function Documentation
static void do_comb_ycca_601 (bNode * UNUSEDnode, float * out, float * in1, float * in2, float * in3, float * in4) [static]
Definition at line 178 of file node_composite_sepcombYCCA.c.
References BLI_YCC_ITU_BT601, g, and ycc_to_rgb().
Referenced by node_composit_exec_combycca().
static void do_comb_ycca_709 (bNode * UNUSEDnode, float * out, float * in1, float * in2, float * in3, float * in4) [static]
Definition at line 196 of file node_composite_sepcombYCCA.c.
References BLI_YCC_ITU_BT709, g, and ycc_to_rgb().
Referenced by node_composit_exec_combycca().
static void do_comb_ycca_jfif (bNode * UNUSEDnode, float * out, float * in1, float * in2, float * in3, float * in4) [static]
Definition at line 214 of file node_composite_sepcombYCCA.c.
References BLI_YCC_JFIF_0_255, g, and ycc_to_rgb().
Referenced by node_composit_exec_combycca().
static void do_sepycca_601 (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 49 of file node_composite_sepcombYCCA.c.
References BLI_YCC_ITU_BT601, and rgb_to_ycc().
Referenced by node_composit_exec_sepycca().
static void do_sepycca_709 (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 62 of file node_composite_sepcombYCCA.c.
References BLI_YCC_ITU_BT709, and rgb_to_ycc().
Referenced by node_composit_exec_sepycca().
static void do_sepycca_jfif (bNode * UNUSEDnode, float * out, float * in) [static]
Definition at line 75 of file node_composite_sepcombYCCA.c.
References BLI_YCC_JFIF_0_255, and rgb_to_ycc().
Referenced by node_composit_exec_sepycca().
static void node_composit_exec_combycca (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 232 of file node_composite_sepcombYCCA.c.
References alloc_compbuf(), BLI_YCC_ITU_BT601, BLI_YCC_ITU_BT709, BLI_YCC_JFIF_0_255, CB_RGBA, CB_VAL, composit4_pixel_processor(), bNode::custom1, bNodeStack::data, data, do_comb_ycca_601(), do_comb_ycca_709(), do_comb_ycca_jfif(), NULL, bNodeStack::vec, CompBuf::x, CompBuf::y, and ycc_to_rgb().
Referenced by register_node_type_cmp_combycca().
static void node_composit_exec_sepycca (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 88 of file node_composite_sepcombYCCA.c.
References BLI_YCC_ITU_BT601, BLI_YCC_ITU_BT709, BLI_YCC_JFIF_0_255, CB_RGBA, CHAN_A, CHAN_B, CHAN_G, CHAN_R, composit1_pixel_processor(), bNode::custom1, bNodeStack::data, data, do_sepycca_601(), do_sepycca_709(), do_sepycca_jfif(), dupalloc_compbuf(), free_compbuf(), NULL, rgb_to_ycc(), typecheck_compbuf(), valbuf_from_rgbabuf(), and bNodeStack::vec.
Referenced by register_node_type_cmp_sepycca().
void register_node_type_cmp_combycca (bNodeTreeType * ttype)
Definition at line 298 of file node_composite_sepcombYCCA.c.
References CMP_NODE_COMBYCCA, NODE_CLASS_CONVERTOR, node_composit_exec_combycca(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
void register_node_type_cmp_sepycca (bNodeTreeType * ttype)
Definition at line 151 of file node_composite_sepcombYCCA.c.
References CMP_NODE_SEPYCCA, NODE_CLASS_CONVERTOR, node_composit_exec_sepycca(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_combycca_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Y",         0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "Cb",            0.5f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "Cr",            0.5f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "A",         1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 166 of file node_composite_sepcombYCCA.c.
bNodeSocketTemplate cmp_node_combycca_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 173 of file node_composite_sepcombYCCA.c.
bNodeSocketTemplate cmp_node_sepycca_in[] [static]
Initial value:
 {
    {  SOCK_RGBA, 1, "Image",        1.0f, 1.0f, 1.0f, 1.0f},
    {  -1, 0, ""   }
}
Definition at line 37 of file node_composite_sepcombYCCA.c.
bNodeSocketTemplate cmp_node_sepycca_out[] [static]
Initial value:
 {
    {  SOCK_FLOAT, 0, "Y"},
    {  SOCK_FLOAT, 0, "Cb"},
    {  SOCK_FLOAT, 0, "Cr"},
    {  SOCK_FLOAT, 0, "A"},
    {  -1, 0, ""   }
}
Definition at line 41 of file node_composite_sepcombYCCA.c.