Blender: BLI_listbase.h File Reference
BLI_listbase.h File Reference
blenlib
#include "DNA_listBase.h"
Functions
void BLI_insertlink (struct ListBase *listbase, void *vprevlink, void *vnewlink)
int BLI_findindex (const struct ListBase *listbase, void *vlink)
int BLI_findstringindex (const struct ListBase *listbase, const char *id, const int offset)
void * BLI_findlink (const struct ListBase *listbase, int number)
void * BLI_findstring (const struct ListBase *listbase, const char *id, const int offset)
void * BLI_findstring_ptr (const struct ListBase *listbase, const char *id, const int offset)
void * BLI_rfindlink (const struct ListBase *listbase, int number)
void * BLI_rfindstring (const struct ListBase *listbase, const char *id, const int offset)
void * BLI_rfindstring_ptr (const struct ListBase *listbase, const char *id, const int offset)
void BLI_freelistN (struct ListBase *listbase)
void BLI_addtail (struct ListBase *listbase, void *vlink)
void BLI_remlink (struct ListBase *listbase, void *vlink)
int BLI_remlink_safe (struct ListBase *listbase, void *vlink)
void BLI_addhead (struct ListBase *listbase, void *vlink)
void BLI_insertlinkbefore (struct ListBase *listbase, void *vnextlink, void *vnewlink)
void BLI_insertlinkafter (struct ListBase *listbase, void *vprevlink, void *vnewlink)
void BLI_sortlist (struct ListBase *listbase, int(*cmp)(void *, void *))
void BLI_freelist (struct ListBase *listbase)
int BLI_countlist (const struct ListBase *listbase)
void BLI_freelinkN (struct ListBase *listbase, void *vlink)
void BLI_movelisttolist (struct ListBase *dst, struct ListBase *src)
void BLI_duplicatelist (struct ListBase *dst, const struct ListBase *src)
struct LinkData * BLI_genericNodeN (void *data)
Detailed Description
Definition in file BLI_listbase.h.
Function Documentation
void BLI_addhead (struct ListBase * listbase, void * vlink)
Definition at line 69 of file listbase.c.
References ListBase::first, ListBase::last, link(), Link::next, NULL, and Link::prev.
Referenced by add_empty_text(), AddNewBlenderMesh(), BKE_nlameta_add_strip(), BKE_nlastrips_sort_strips(), BLF_dir_add(), blf_glyph_add(), blf_glyph_cache_new(), bli_builddir(), BLO_read_from_memfile(), BMO_error_raise(), BMW_state_add(), console_history_cycle_exec(), copy_attr(), copy_particle_dupliob_exec(), DAG_pose_sort(), DAG_scene_sort(), direct_link_object(), do_versions(), duplibase_for_convert(), ED_area_newspace(), ed_marker_duplicate_apply(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), filldisplist(), group_linkobs2scene_cb(), imb_exr_get_pass(), imb_global_cache_get_tile(), imb_thread_cache_get_tile(), make_links_scene_exec(), make_object_duplilist_real(), make_selection_list_nurb(), modifiers_convertToReal(), motionpaths_calc_optimise_depsgraph(), object_add_duplicate_internal(), posttrans_gpd_clean(), prependPolyLineVert(), scene_add_base(), tree_element_to_path(), txt_add_marker(), ui_block_position(), ui_item_align(), ui_popup_block_create(), uiBlockSetRegion(), WM_event_add_dropbox_handler(), WM_event_add_fileselect(), WM_event_add_keymap_handler_priority(), WM_event_add_modal_handler(), WM_event_add_ui_handler(), wm_keymap_addon_add(), and write_history().
void BLI_addtail (struct ListBase * listbase, void * vlink)
Definition at line 85 of file listbase.c.
References ListBase::first, ListBase::last, link(), Link::next, NULL, and Link::prev.
Referenced by _bm_select_history_store_notest(), act_markers_make_local_exec(), action_get_item_transforms(), action_groups_add_new(), action_move_fcurves_by_basepath(), action_new(), actuator_add_exec(), AnimationImporter::add_bone_fcurve(), add_collider_cache_object(), add_empty_ks_path_exec(), add_fmodifier(), add_keyblock(), add_marker_to_cfra_elem(), add_memfilechunk(), add_metaball_element(), add_new_constraint(), add_nlatrack(), add_object_to_effectors(), add_particles_to_effectors(), add_render_lamp(), add_text(), add_to_group_internal(), add_user_list(), add_view3d_after(), add_volume(), addDepthPeel(), addedgetoscanvert(), addfillface(), addMatrixSpace(), addpsmain(), addpsmainA(), addpsmainAstrand(), addSnapPoint(), adduplicateflagNurb(), alloc_libblock(), alloc_sequence(), ANIM_fmodifiers_copy_to_buf(), ANIM_fmodifiers_paste_from_buf(), ANIM_keyingset_info_register(), ANIM_relative_keyingset_add_source(), animdata_filter_dopesheet_summary(), animviz_get_object_motionpaths(), append_named_part_ex(), appendPolyLineVert(), AnimationImporter::apply_matrix_curves(), area_add_header_region(), area_add_window_regions(), area_azone_initialize(), area_copy_data(), armature_extrude_exec(), armature_subdivide_exec(), as_addvert(), AnimationImporter::Assign_color_animations(), AnimationImporter::Assign_float_animations(), bevels_to_filledpoly(), bezt_add_to_cfra_elem(), bezt_to_cfraelem(), BKE_animdata_separate_by_basepath(), BKE_keyingset_add(), BKE_keyingset_add_path(), BKE_library_make_local(), BKE_nlameta_add_strip(), BKE_nlastrip_validate_fcurves(), BKE_nlastrips_add_strip(), BKE_nlastrips_make_metas(), BKE_ptcache_add(), BKE_ptcache_copy_list(), BKE_ptcache_disk_to_mem(), BKE_ptcache_ids_from_object(), BKE_report(), BKE_reportf(), BKE_spacedata_copylist(), BKE_spacetype_register(), BKE_tracking_add_track(), BKE_tracking_clipboard_copy_tracks(), BKE_tracking_clipboard_paste_tracks(), BKE_tracking_new_object(), BKE_write_undo(), BLI_add_cb(), BLI_addfilledge(), BLI_addfillvert(), BLI_duplicatelist(), BLI_init_threads(), BLI_mempool_alloc(), BLI_mempool_create(), BLI_mempool_free(), blo_find_main(), blo_read_file_internal(), blo_split_main(), bm_face_boundary_add(), bm_face_create__sfme(), BM_faces_join(), BMW_state_add(), BPY_context_member_get(), build_underline(), buildchar(), buttons_context_register(), buttons_new(), buttons_texture_user_node_add(), buttons_texture_user_property_add(), cache_strand_surface(), chains_find_tips(), clip_new(), cloneArc(), columnselect_action_keys(), columnselect_graph_keys(), compress_deepshadowbuf(), compress_shadowbuf(), console_history_cycle_exec(), console_lb_add__internal(), console_lb_add_str__internal(), console_new(), console_scrollback_prompt_begin(), controller_add_exec(), KX_BlenderSceneConverter::ConvertMeshSpecial(), copy_action(), copy_actuators(), copy_animedit_keys(), copy_attr(), copy_controllers(), copy_dbase_object_vectors(), copy_displist(), copy_fcurves(), copy_nladata(), copy_nlastrip(), copy_nlatrack(), copy_object(), copy_object_particlesystems(), copy_properties(), copy_sensors(), copy_text(), count_images(), create_old_vert_edge_map(), create_old_vert_face_map(), create_vert_edge_map(), CTX_data_id_list_add(), CTX_data_list_add(), CTX_store_add(), CTX_store_add_all(), curve_rename_fcurves(), curve_to_displist(), curvesurf_prim_add(), cut_seq_list(), data_dir_add(), defgroup_copy_list(), delete_exec(), direct_link_library(), direct_link_object(), direct_link_screen(), do_logic_buts(), do_makeDispListCurveTypes(), do_versions(), draw_triangulated(), driver_add_new_variable(), duplicate_metaelems_exec(), duplicateEditBoneObjects(), duplicateNurblist(), dynamicPaint_createNewSurface(), ED_armature_edit_bone_add(), ED_armature_from_edit(), ED_clip_buttons_register(), ED_clip_tool_props_register(), ed_marker_add(), ed_marker_make_links_scene_exec(), ED_object_modifier_add(), ED_region_draw_cb_activate(), ED_undo_gpencil_step(), ED_uvedit_buttons_register(), ED_vgroup_add_name(), ED_view3D_background_image_new(), edge_copy_add_path(), edge_path_new(), editBones_to_undoBones(), editCurve_to_undoCurve(), editMball_to_undoMball(), effector_add_type(), extract_proxylocal_constraints(), fcurve_add_to_list(), fcurve_path_rename(), fcurves_to_pchan_links_get(), file_new(), file_panels_register(), fill_add_joint(), fill_metaball_octal_node(), fillBevelCap(), find_displist_create(), folderlist_pushdir(), freetypechar_to_vchar(), game_property_new(), get_bhead(), get_thread_qmcsampler(), give_base_to_objects(), give_ibuf_prefetch_request(), gp_stroke_newfrombuffer(), gp_stroke_to_bezier(), gp_stroke_to_path(), gpencil_data_duplicate(), gpencil_frame_addnew(), gpencil_frame_duplicate(), gpencil_layer_addnew(), gpencil_layer_duplicate(), gpencil_undo_push(), gplayer_make_cfra_list(), GPU_lamp_from_blender(), gpu_material_add_node(), GPU_material_from_blender(), gpu_node_input_link(), GPU_node_output(), GPU_nodes_extract_dynamic_inputs(), gpu_queue_image_for_free(), gpu_render_lamp_update(), GPU_shader_export(), graph_buttons_register(), graph_new(), graphkeys_euler_filter_exec(), group_sort_exec(), group_verify_socket_list(), icon_preview_add_size(), id_sort_by_name(), IDP_AddToGroup(), IDP_CopyGroup(), IDP_ReplaceGroupInGroup(), IDP_ReplaceInGroup(), image_buttons_register(), image_new(), image_undo_push_tile(), IMB_exr_add_channel(), IMB_exr_get_handle(), imb_exr_get_layer(), imb_exr_get_pass(), imb_thread_cache_init(), imb_tile_cache_tile_free(), info_new(), init_camera_inside_volumes(), init_iconfile_list(), init_metaball_octal_tree(), init_multiresbake_job(), init_userdef_do_versions(), initialize_chain(), initialize_posetree(), initparts(), internalDocs(), join_armature_exec(), join_curve_exec(), join_mesh_exec(), knife_append_list(), knife_split_edge(), lattice_calc_modifiers(), lib_link_screen(), linkedlist_sync_add_node(), list_find_data_fcurves(), load_editNurb(), load_vfont(), logic_new(), loop_sync(), M_Geometry_tessellate_polygon(), make_boneList(), make_editNurb(), make_selection_list_nurb(), makebevelcurve(), makeBevelList(), makeDispListSurf(), mem_element_new(), mem_element_reset(), mesh_to_curve(), metaball_polygonize(), ml_addlayer_cb(), ml_addpass_cb(), nearest_fcurve_vert_store(), new_dupli_object(), new_particle_target_exec(), new_pgn_element(), newRigArc(), newRigControl(), newRigNode(), newRigNodeHead(), nla_buttons_register(), nla_new(), nlaedit_snap_exec(), nlaevalchan_buffers_accumulate(), nlaevalchan_verify(), nlastrips_ctime_get_strip(), node_buttons_register(), node_duplicate_exec(), node_group_add_extern_socket(), node_group_add_socket(), node_group_make_from_selected(), node_group_ungroup(), node_internal_connect_default(), node_link_invoke(), node_link_modal(), node_new(), nodeAddLink(), nodeAddNode(), nodeAddSocket(), nodeCopyNode(), nodeRegisterType(), ntreeGetThreadStack(), object_add_particle_system(), object_insert_ptcache(), object_link_modifiers(), operator_call_cb(), outliner_add_element(), outliner_add_id_contents(), outliner_add_object_contents(), outliner_build_tree(), outliner_make_hierarchy(), outliner_new(), outliner_sort(), PE_undo_push(), pose_add_group(), poselib_add_exec(), poselib_backup_posecopy(), poselib_preview_get_next(), poselib_sanitise_exec(), posttrans_gpd_clean(), precache_init_parts(), preview_prepare_scene(), psys_alloc_path_cache_buffers(), psys_check_group_weights(), psys_prepare_physics(), ptcache_disk_frame_to_mem(), ptcache_particle_extra_write(), ptcache_write(), pyrna_py_to_prop(), RE_addRenderInstance(), RE_addRenderObject(), RE_engine_begin_result(), RE_engines_init(), RE_makeRenderInstances(), RE_NewRender(), read_libblock(), read_libraries(), rearrange_animchannel_add_to_islands(), rearrange_island_bottom(), recalcData_nla(), region_azone_initialize(), region_copylist(), region_quadview_exec(), BOP_Mesh::rehashVertex(), render_layer_add_pass(), render_result_new(), render_result_new_full_sample(), render_result_single_layer_end(), reopen_text(), repeat_history_exec(), RIG_appendEdgeToArc(), rna_function_parameter_parse(), RNA_property_update_cache_add(), rna_search_cb(), rule_add_exec(), scanfill(), scene_add_render_layer(), scene_sort_groups(), screen_addarea(), screen_addedge(), screen_addvert(), script_new(), sculpt_undo_alloc_node(), sensor_add_exec(), separate_exec(), seq_dupe_animdata(), seq_dupli_recursive(), seq_proxy_build_job(), seqbase_dupli_recursive(), sequencer_meta_make_exec(), sequencer_meta_toggle_exec(), sequencer_new(), sequencer_separate_images_exec(), set_ob_property(), sk_getIntersections(), sk_getSelfIntersections(), sk_startStroke(), snode_autoconnect(), sort_seq(), spacedata_cleanup(), splineik_init_tree_from_pchan(), split_groups_action_temp(), split_libdata(), splitlist(), sss_add_points(), state_add_exec(), state_del_exec(), text_new(), thumbnails_start(), time_draw_cache(), time_new(), tracks_map_merge(), AnimationImporter::translate_animation_OLD(), AnimationImporter::translate_Animations(), ui_add_link_line(), ui_add_temporary_region(), ui_apply_autokey_undo(), ui_apply_but_func(), ui_def_but(), ui_layout_add_but(), ui_layout_box(), ui_style_new(), ui_theme_init_default(), UI_view2d_text_cache_add(), UI_view2d_text_cache_rectf(), uiBeginPanel(), uiBlockFlipOrder(), uiBlockLayout(), uiLayoutAbsolute(), uiLayoutColumn(), uiLayoutColumnFlow(), uiLayoutOverlap(), uiLayoutRow(), uiLayoutSplit(), uiStyleInit(), undo_editmode_push(), undo_stack_push_begin(), undoBones_to_editBones(), undoCurve_to_editCurve(), undoMball_to_editMball(), userpref_new(), verify_driver_fcurve(), verify_fcurve(), verify_pose_channel(), verify_socket_template_list(), versions_gpencil_add_main(), vfont_get_data(), vgroup_duplicate(), view3d_buttons_register(), view3d_cached_text_draw_add(), view3d_new(), view3d_tool_props_register(), view3d_toolshelf_register(), vpaint_build_poly_facemap(), WM_dropbox_add(), WM_dropboxmap_find(), wm_event_add(), WM_event_add_keymap_handler(), WM_event_add_notifier(), WM_event_add_timer(), WM_event_start_drag(), WM_gesture_new(), WM_jobs_get(), WM_keyconfig_new(), WM_keymap_add_item(), wm_keymap_copy(), wm_keymap_diff(), wm_keymap_diff_update(), WM_keymap_find(), wm_keymap_patch(), wm_keymap_patch_update(), WM_keymap_verify_item(), WM_main_add_notifier(), WM_modalkeymap_add_item(), WM_modalkeymap_add_item_str(), wm_operator_create(), wm_operator_register(), WM_operatortype_macro_define(), WM_paint_cursor_activate(), WM_read_history(), wm_subwindow_open(), and wm_window_new().
int BLI_countlist (const struct ListBase * listbase)
Referenced by add_default_keyingset_exec(), add_empty_ks_path_exec(), add_keyblock(), add_keyingset_button_exec(), add_nlatrack(), applyModifier(), armature_deform_verts(), armature_fill_bones_exec(), BL_SkinDeformer::BGEDeformVerts(), BKE_tracking_new_object(), BKE_tracking_reconstruction_context_new(), BLF_dir_get(), BM_mesh_bm_to_me(), boid_brain(), bpy_bmeditselseq_length(), BPY_driver_exec(), buttons_texture_context_compute(), buttons_texture_user_node_add(), buttons_texture_user_property_add(), calc_weightpaint_vert_array(), console_scrollback_limit(), ctx_data_list_count(), curve_surf_to_softbody(), defgroup_flip_map(), defgroup_flip_map_single(), do_outliner_keyingset_editop(), do_versions(), ED_markers_get_minmax(), ED_text_to_object(), ED_vgroup_add_name(), ED_vgroup_copy_array(), exec_retargetArctoArc(), find_chain(), find_hole_chains(), give_ibuf_seq(), GPU_export_shader(), group_sort_exec(), IDnames_to_dyn_pupstring(), IDP_EqualsProperties(), image_multi_inclay_cb(), image_multi_incpass_cb(), ipo_to_animdata(), knife_make_chain_cut(), knife_make_face_cuts(), layer_menu(), make_trans_verts(), make_unique_prop_names(), multiresbake_startjob(), nlaedit_swap_exec(), node_composit_exec_image(), node_sort(), node_update_group(), ntreeCompositOutputFileRemoveActiveSocket(), object_add_particle_system(), pass_menu(), pose_add_group(), pose_select_same_group(), poselib_add_exec(), poselib_preview_handle_event(), RE_makeRenderInstances(), render_layer_add_exec(), repeat_history_invoke(), retargetArctoArcAggresive(), RIG_findHead(), RIG_nameBone(), RIG_nbJoints(), screen_set_exec(), set_constraint_nth_target(), snode_autoconnect(), spacedata_cleanup(), text_drawcache_init(), text_update_drawcache(), ui_litem_layout_split(), verify_active_keyingset(), vgroup_delete_update_users(), vgroup_do_remap(), vgroup_duplicate(), vgroup_init_remap(), weight_paint_sample_enum_itemf(), wm_operator_register(), and wpaint_stroke_test_start().
void BLI_duplicatelist (struct ListBase * dst, const struct ListBase * src)
Referenced by BKE_area_region_copy(), BKE_keyingsets_copy(), boid_copy_settings(), boid_duplicate_state(), copy_action(), copy_armature(), copy_bonechildren(), copy_constraints(), copy_fmodifiers(), copy_group(), copy_key(), copy_key_nolib(), copy_mball(), copy_particlesystem(), copy_pose(), copy_scene(), CTX_store_add(), CTX_store_add_all(), CTX_store_copy(), ED_vgroup_copy_array(), fcurve_copy_driver(), folderlist_duplicate(), game_copy_pose(), get_PTCacheUndo(), graph_duplicate(), make_PTCacheUndo(), nodeCopyNode(), ntreeCopyTree(), pose_proxy_synchronize(), psys_copy_settings(), pycon_copy(), screen_copy(), ui_block_position(), vertex_group_copy_to_linked_exec(), and view3d_duplicate().
int BLI_findindex (const struct ListBase * listbase, void * vlink)
Referenced by ANIM_scene_get_keyingset_index(), armature_deform_verts(), BKE_tracking_active_track(), BKE_tracking_remove_object(), BLI_remlink_safe(), buttons_texture_context_compute(), ccgDM_release(), createTransNlaData(), do_versions(), draw_markers(), ED_object_shape_key_add(), ED_vgroup_vert_add(), ED_vgroup_vert_remove(), ED_vgroup_vert_weight(), game_engine_exec(), get_constraint_lb(), get_sample_layers(), make_new_animlistelem(), ntreeCompositOutputFileAddSocket(), pastebuf_match_path_property(), poselib_preview_apply(), poselib_preview_cleanup(), RE_InitState(), scene_remove_render_layer(), sculpt_undo_restore_coords(), select_report_pick_invoke(), set_actNurb(), text_drawcache_tag_update(), txt_wrap_move_down(), txt_wrap_move_up(), ui_block_func_POPUP(), ui_handler_remove_region(), vgroup_active_remove_verts(), vgroup_delete_edit_mode(), vgroup_delete_object_mode(), view3d_recalc_used_layers(), wm_handlers_do(), WM_keymap_remove_item(), and wpaint_stroke_test_start().
void* BLI_findlink (const struct ListBase * listbase, int number)
Referenced by add_empty_ks_path_exec(), add_keyingset_button_exec(), ANIM_scene_get_active_keyingset(), applyModifier(), background_image_remove_exec(), BIF_removeTransformOrientationIndex(), BKE_tracking_active_object(), BKE_undo_get_name(), BKE_undo_number(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), boid_brain(), bpy_bmeditselseq_subscript_int(), brush_clone_image_set_nr(), brush_texture_set_nr(), build_dag_object(), buttons_texture_context_compute(), cache_pointdensity(), calc_shapeKeys(), cmp_node_image_create_outputs(), cmp_node_image_output_relink(), compbuf_multilayer_get(), copymenu_properties(), dag_tag_renderlayers(), defgroup_flip_index(), defgroup_flip_map_single(), delete_key_exec(), DM_to_mesh(), do_armature_box_select(), do_node_add_group(), do_ob_key(), do_rel_key(), do_versions_nodetree_multi_file_output_format_2_62_1(), draw_markers(), draw_selected_name(), dynamics_step(), ed_marker_make_links_scene_exec(), ED_object_shape_key_remove(), ED_vgroup_mirror(), force_hidden_passes(), game_property_copy_exec(), game_property_remove(), get_actNurb(), get_bone_from_selectbuffer(), get_indexed_bone(), get_nearest_editbonepoint(), get_sample_layers(), give_ibuf_seq(), group_instance_add_exec(), group_link_exec(), group_move_exec(), image_get_render_result(), image_multi_incpass_cb(), insert_key_exec(), join_mesh_exec(), keyingset_poll_activePath_edit(), lib_link_particlesettings(), SkinInfo::link_armature(), load_editLatt(), make_links_scene_exec(), make_proxy_exec(), mesh_create_derived_for_modifier(), mesh_to_curve(), mouse_action_keys(), mouse_anim_channels(), mouse_nla_channels(), mouse_nla_strips(), nlaedit_add_actionclip_exec(), node_browse_text_cb(), node_composit_exec_image(), node_composit_exec_rlayers(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_render_changed_exec(), node_socket_add_replace(), ntreeCompositForceHidden(), ntreeCompositOutputFileRemoveActiveSocket(), ob_get_keyblock(), object_hook_assign_exec(), object_hook_recenter_exec(), object_hook_remove_exec(), object_hook_reset_exec(), object_hook_select_exec(), object_shape_key_mirror(), outliner_action_set_exec(), PE_undo_get_name(), pose_remove_group(), poselib_get_active_pose(), poselib_preview_init_data(), poselib_remove_exec(), poselib_rename_exec(), poselib_rename_invoke(), psys_get_target_system(), RE_is_rendering_allowed(), remove_active_keyingset_exec(), remove_active_ks_path_exec(), remove_keyingset_button_exec(), rename_anim_channels(), render_get_active_layer(), render_layer_remove_exec(), repeat_history_exec(), return_editmesh_vgroup(), RIG_nameBone(), RNA_function_get_parameter(), rna_listbase_lookup_int(), select_report_pick_exec(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), set_keyed_keys(), set_pchan_colorset(), shape_key_move_exec(), sk_selectStroke(), texture_paint_camera_project_exec(), tselem_draw_icon(), uiblock_layer_pass_buttons(), undo_editmode_get_name(), v3d_editvertex_buts(), verify_active_keyingset(), vertex_group_remove_from_exec(), vgroup_assign_verts(), vgroup_blend(), vgroup_clean(), vgroup_delete(), vgroup_duplicate(), vgroup_invert(), vgroup_levels(), vgroup_move_exec(), vgroup_normalize(), vgroup_normalize_all(), vgroup_select_verts(), view3d_panel_vgroup(), wpaint_mirror_vgroup_ensure(), and wpaint_stroke_test_start().
void* BLI_findstring (const struct ListBase * listbase, const char * id, const int offset)
Referenced by action_groups_find_named(), ANIM_keyingset_info_find_named(), bpy_text_import_name(), bpy_text_reimport(), constraints_findByName(), convert_tfacematerial(), convert_tfacenomaterial(), KX_BlenderSceneConverter::ConvertMeshSpecial(), data_dir_add(), edit_actuator_property_get(), edit_controller_property_get(), edit_object_property_get(), edit_sensor_property_get(), editbone_name_exists(), find_id(), get_armature_bone_constraint(), get_ob_property(), get_pose_channel(), KX_BlenderSceneConverter::GetBlenderSceneForName(), IDP_GetPropertyFromGroup(), IDP_SyncGroupValues(), image_undo_restore(), image_unpack_exec(), imb_exr_get_layer(), imb_exr_get_pass(), IMB_exr_set_channel(), init_userdef_do_versions(), is_yet_read(), key_get_named_keyblock(), modifiers_findByName(), nodeFindNodebyName(), preview_prepare_scene(), pyrna_prop_collection_subscript_str_lib_pair_ptr(), RE_engines_find(), RNA_function_find_parameter(), screen_render_scene_layer_set(), separated_armature_fix_links(), set_engine(), sound_unpack_exec(), StartKetsjiShell(), test_actionpoin_but(), test_idbutton(), test_matpoin_but(), test_meshpoin_but(), test_obpoin_but(), test_scenepoin_but(), test_scriptpoin_but(), uiBlockSetRegion(), uiGetBlock(), verify_pose_channel(), wm_link_append_exec(), and WM_read_file().
void* BLI_findstring_ptr (const struct ListBase * listbase, const char * id, const int offset)
Referenced by RNA_struct_find_function(), and RNA_struct_type_find_property().
int BLI_findstringindex (const struct ListBase * listbase, const char * id, const int offset)
Referenced by vgroup_do_remap().
void BLI_freelinkN (struct ListBase * listbase, void * vlink)
Definition at line 127 of file listbase.c.
References BLI_remlink(), link(), MEM_freeN(), and NULL.
Referenced by _bm_select_history_remove(), action_move_fcurves_by_basepath(), action_to_animato(), ANIM_keyingset_info_unregister(), ANIM_keyingset_infos_exit(), animchannels_delete_exec(), animdata_filter_remove_duplis(), animdata_filter_remove_invalid(), armature_delete_selected_exec(), armature_rebuild_pose(), BIF_removeTransformOrientation(), BIF_removeTransformOrientationIndex(), BKE_keyingset_free_path(), BKE_keyingsets_free(), BKE_ptcache_id_clear(), BKE_tracking_remove_object(), BLI_removeArc(), BLI_removeNode(), BLI_replaceNode(), BLI_replaceNodeInArc(), BM_select_history_validate(), bone_free(), clean_tracks_exec(), clip_delete_track(), do_textmarkers(), do_versions(), do_versions_ipos_to_animato(), draw_ghost_poses_keys(), draw_markers(), driver_free_variable(), ED_area_newspace(), ed_marker_delete_exec(), edbm_strip_selections(), folderlist_popdir(), free_anim_copybuf(), free_gpencil_frames(), free_gpencil_layers(), free_gpencil_strokes(), free_iconfile_list(), free_ipo(), free_nlastrip(), free_nlatrack(), free_vfont(), gp_stroke_eraser_dostroke(), gp_stroke_eraser_splitdel(), gpencil_frame_delete_laststroke(), gpencil_layer_delactive(), gpencil_layer_delframe(), gpencil_undo_push(), GPU_lamp_free(), GPU_material_free(), ipo_to_animato(), join_tracks_exec(), mesh_to_curve(), nlastrips_to_animdata(), node_group_make_from_selected(), node_group_ungroup(), pose_remove_group(), poseAnim_mapping_free(), poselib_backup_free_data(), poselib_remove_exec(), poselib_sanitise_exec(), psys_check_group_weights(), rearrange_animchannel_flatten_islands(), remove_active_keyingset_exec(), remove_constraint(), remove_fmodifier(), removeSnapPoint(), RNA_property_update_cache_free(), separate_armature_bones(), splineik_execute_tree(), tracks_map_merge(), txt_backspace_char(), txt_clear_marker_region(), txt_clear_markers(), txt_delete_char(), txt_delete_line(), txt_replace_char(), ui_apply_but_funcs_after(), ui_remove_temporary_region(), undo_clean_stack(), undo_editmode_push(), undo_stack_push_begin(), undo_stack_push_end(), vgroup_delete_edit_mode(), vgroup_delete_object_mode(), WM_keyconfig_free(), wm_keymap_diff_update(), wm_keymap_patch(), wm_keymap_patch_update(), WM_keymap_remove_item(), WM_keymap_restore_to_default(), and write_history().
void BLI_freelist (struct ListBase * listbase)
Definition at line 273 of file listbase.c.
References ListBase::first, ListBase::last, link(), Link::next, next, and NULL.
Referenced by bli_builddir(), BLI_mempool_destroy(), and BLI_mempool_free().
void BLI_freelistN (struct ListBase * listbase)
Definition at line 291 of file listbase.c.
References ListBase::first, ListBase::last, link(), MEM_freeN(), Link::next, next, and NULL.
Referenced by achannel_setting_flush_widget_cb(), action_to_animato(), actkeys_framejump_exec(), actkeys_mselect_column(), actkeys_select_leftright(), actkeys_select_linked_exec(), ANIM_deselect_anim_channels(), ANIM_editkeyframes_refresh(), ANIM_set_active_channel(), ANIM_sync_animchannels_to_data(), animchannels_delete_exec(), animchannels_enable_exec(), animchannels_rearrange_exec(), animchannels_visibility_set_exec(), animchannels_visibility_toggle_exec(), animsys_calculate_nla(), animsys_evaluate_nla(), area_azone_initialize(), area_copy_data(), armature_fill_bones_exec(), armature_merge_exec(), autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), autosmooth(), bake_graph_curves(), BIF_clearTransformOrientation(), BKE_area_region_free(), BKE_ptcache_bake(), BKE_ptcache_free_mem(), BKE_ptcache_id_clear(), BKE_reset_undo(), BKE_screen_area_free(), BKE_spacedata_freelist(), BKE_spacetypes_free(), BKE_userdef_free(), BLI_argsFree(), BLI_destroy_worker(), BLI_dlrbTree_free(), BLI_end_threads(), BLI_mempool_destroy(), BLI_mempool_free(), blo_freefiledata(), BM_mesh_data_free(), BM_select_history_clear(), boid_free_settings(), borderselect_action(), borderselect_anim_channels(), borderselect_graphkeys(), borderselect_nla_strips(), buttons_free(), buttons_texture_context_compute(), CalcSnapGeometry(), clean_action_keys(), clean_graph_keys(), columnselect_action_keys(), columnselect_graph_keys(), constraintTransLim(), copy_action_keys(), copy_graph_keys(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), create_scene(), createTransActionData(), createTransNlaData(), ctx_data_list_count(), CTX_store_free(), delete_action_keys(), delete_graph_keys(), deselect_action_keys(), deselect_nla_strips(), do_makeDispListCurveTypes(), draw_channel_names(), draw_channel_strips(), draw_nla_channel_list(), draw_nla_main_data(), duplicate_action_keys(), duplicate_graph_keys(), ED_armature_edit_free(), ED_autokeyframe_object(), ED_autokeyframe_pchan(), ED_nla_postop_refresh(), ED_object_exit_editmode(), ED_objects_recalculate_paths(), ED_pose_recalculate_paths(), ED_vgroup_copy_array(), find_nearest_fcurve_vert(), folderlist_free(), free_action(), free_armature(), free_bonelist(), free_camera_inside_volumes(), free_collider_cache(), free_constraints(), free_curve(), free_dbase_object_vectors(), free_mball(), free_metaball_octal_node(), free_object(), free_object_duplilist(), free_openrecent(), free_pose(), free_pose_channels(), free_posebuf(), free_posetree(), free_renderdata_tables(), free_scene(), free_screen(), free_strand_surface(), free_text(), free_ttfont(), free_undoBones(), free_volume_precache(), freeparts(), freeshadowbuf(), freeSketch(), get_active_fcurve_channel(), get_graph_keyframe_extents(), get_keyframe_extents(), get_nearest_fcurve_verts_list(), get_nlastrip_extents(), gpencil_undo_finish(), GPU_free_shader_export(), GPU_free_unused_buffers(), GPU_inputs_free(), GPU_lamp_free(), GPU_material_free(), GPU_node_free(), gpu_update_lamps_shadows(), graph_draw_channel_names(), graph_draw_curves(), graph_fmodifier_add_exec(), graph_fmodifier_paste_exec(), graph_free(), graph_refresh(), graphkeys_euler_filter_exec(), graphkeys_framejump_exec(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), graphkeys_smooth_exec(), graphop_editable_keyframes_poll(), graphop_selected_fcurve_poll(), graphop_visible_keyframes_poll(), icon_preview_free(), IDP_FreeGroup(), IMB_exr_close(), IMB_exrtile_clear_channels(), insert_action_keys(), insert_graph_keys(), makeBevelList(), markers_selectkeys_between(), mem_element_reset(), merge_nurb(), mesh_to_curve(), mirror_action_keys(), mirror_graph_keys(), mouse_action_keys(), mouse_anim_channels(), mouse_nla_channels(), mouse_nla_strips(), move_camera(), multires_free(), multiresbake_image_exec_locked(), multiresbake_startjob(), new_pgn_element(), nla_fmodifier_add_exec(), nla_fmodifier_paste_exec(), nla_free(), nla_panel_context(), nlaedit_add_actionclip_exec(), nlaedit_add_meta_exec(), nlaedit_add_sound_exec(), nlaedit_add_tracks_exec(), nlaedit_add_transition_exec(), nlaedit_apply_scale_exec(), nlaedit_bake_exec(), nlaedit_clear_scale_exec(), nlaedit_delete_exec(), nlaedit_delete_tracks_exec(), nlaedit_disable_tweakmode_exec(), nlaedit_duplicate_exec(), nlaedit_enable_tweakmode_exec(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_remove_meta_exec(), nlaedit_select_leftright(), nlaedit_snap_exec(), nlaedit_split_exec(), nlaedit_swap_exec(), nlaedit_sync_actlen_exec(), nlaedit_toggle_mute_exec(), nlaevalchan_buffers_accumulate(), nlastrips_to_animdata(), node_draw_mute_line(), nodeInternalRelink(), nodeRemoveAllSockets(), ntreeFreeTree(), ntreeShaderEndExecTree(), ntreeTexEndExecTree(), ob_keyframes_loop(), ob_to_keylist(), object_cacheIgnoreClear(), object_handle_update(), paste_action_keys(), paste_graph_keys(), pdEndEffectors(), pe_get_current(), pose_clear_user_transforms_exec(), pose_proxy_synchronize(), poseAnim_mapping_autoKeyframe(), poseAnim_mapping_free(), poselib_keytag_pose(), poselib_preview_cleanup(), poselib_preview_get_next(), postTrans(), posttrans_action_clean(), precache_init_parts(), proxy_freejob(), psys_check_group_weights(), psys_free(), psys_free_path_cache_buffers(), psys_free_settings(), ptcache_add_new_exec(), ptcache_bake_exec(), ptcache_extra_free(), ptcache_free_bake_all_exec(), ptcache_remove_exec(), PTCacheUndo_clear(), pycon_free(), pyrna_struct_dir(), pyrna_struct_getattro(), pyrna_struct_setattro(), RE_Database_Free(), RE_makeRenderInstances(), REEB_freeArc(), REEB_freeGraph(), rename_anim_channels(), reopen_text(), RIG_freeRigArc(), RIG_freeRigGraph(), RNA_parameter_list_free(), RNA_property_update_cache_free(), rna_search_cb(), sample_action_keys(), sample_graph_keys(), scene_keyframes_loop(), scene_to_keylist(), select_moreless_action_keys(), select_moreless_graph_keys(), setexpo_action_keys(), setexpo_graph_keys(), setflag_anim_channels(), sethandles_action_keys(), sethandles_graph_keys(), setipo_action_keys(), setipo_graph_keys(), setkeytype_action_keys(), sk_freeGesture(), sk_getStrokeSnapPoint(), snap_action_keys(), snap_graph_keys(), snode_autoconnect(), spacetype_free(), special_aftertrans_update(), sss_create_tree_mat(), subdivide_metaball_octal_node(), summary_keyframes_loop(), summary_to_keylist(), thumbnail_joblist_free(), time_cache_free(), time_draw_cache(), tracking_objects_free(), tracking_tracks_free(), tree_element_to_path(), ui_block_position(), ui_free_link(), UI_view2d_text_cache_draw(), uiBlockLayoutResolve(), uiFreeBlock(), undo_editmode_clear(), undo_elem_free(), undo_stack_free(), undoBones_to_editBones(), BL_ShapeActionActuator::Update(), vertex_group_copy_to_linked_exec(), vgroup_delete_all(), view3d_cached_text_draw_end(), view3d_free(), vol_precache_objectinstance_threads(), wm_close_and_free(), wm_dropbox_free(), wm_event_drag_test(), wm_event_free(), wm_handlers_do(), WM_keymap_free(), wm_operatortype_free_macro(), wm_subwindows_free(), and BOP_Mesh::~BOP_Mesh().
struct LinkData* BLI_genericNodeN (void * data) [read]
Definition at line 486 of file listbase.c.
References data, LinkData::data, MEM_callocN(), and NULL.
Referenced by action_get_item_transforms(), count_images(), node_group_make_from_selected(), node_group_ungroup(), RNA_property_update_cache_add(), and seq_proxy_build_job().
void BLI_insertlink (struct ListBase * listbase, void * vprevlink, void * vnewlink)
Definition at line 139 of file listbase.c.
References ListBase::first, ListBase::last, Link::next, NULL, and Link::prev.
Referenced by dupliob_move_down_exec(), dupliob_move_up_exec(), ED_object_modifier_copy(), ED_object_modifier_move_down(), ED_object_modifier_move_up(), IDP_InsertToGroup(), IDP_ReplaceGroupInGroup(), IDP_ReplaceInGroup(), old_sca_move_actuator(), old_sca_move_controller(), old_sca_move_sensor(), rule_move_down_exec(), rule_move_up_exec(), sca_move_actuator(), sca_move_controller(), sca_move_sensor(), sort_keys(), state_move_down_exec(), state_move_up_exec(), target_move_down_exec(), target_move_up_exec(), and ui_but_update_from_old_block().
void BLI_insertlinkafter (struct ListBase * listbase, void * vprevlink, void * vnewlink)
Definition at line 202 of file listbase.c.
References ListBase::first, ListBase::last, Link::next, NULL, and Link::prev.
Referenced by action_groups_add_channel(), add_nlatrack(), BKE_nlastrips_sort_strips(), BLI_sortlist(), clip_has_properties_region(), clip_has_tools_region(), constraint_move_down_exec(), duplicate_gplayer_frames(), file_buttons_region(), gp_stroke_eraser_splitdel(), graph_has_buttons_region(), group_move_exec(), IDP_SyncGroupValues(), image_has_buttons_region(), image_has_scope_region(), logic_has_buttons_region(), nla_has_buttons_region(), nlaedit_add_transition_exec(), nlaedit_split_strip_actclip(), node_group_socket_move_down_exec(), node_has_buttons_region(), posttrans_gpd_clean(), rearrange_island_down(), sequencer_has_buttons_region(), shape_key_move_exec(), sort_by_frac_along(), text_has_properties_region(), txt_add_marker(), vgroup_move_exec(), view3d_has_buttons_region(), and view3d_has_tools_region().
void BLI_insertlinkbefore (struct ListBase * listbase, void * vnextlink, void * vnewlink)
Definition at line 237 of file listbase.c.
References ListBase::first, ListBase::last, Link::next, NULL, and Link::prev.
Referenced by action_groups_add_channel(), add_hook_object(), add_marker_to_cfra_elem(), addedgetoscanvert(), area_add_window_regions(), armature_merge_exec(), bezt_add_to_cfra_elem(), BKE_nlastrips_add_strip(), BKE_nlastrips_clear_metastrip(), BKE_nlastrips_make_metas(), clip_has_preview_region(), constraint_move_up_exec(), do_versions(), ED_object_modifier_add(), gpencil_frame_addnew(), group_move_exec(), id_sort_by_name(), image_assign_ibuf(), loop_sync(), makeBevelList(), multires_load_old(), node_group_socket_move_up_exec(), node_sort(), nodeInsertSocket(), old_sca_move_actuator(), old_sca_move_controller(), old_sca_move_sensor(), posttrans_gpd_clean(), rearrange_island_bottom(), rearrange_island_top(), rearrange_island_up(), sca_move_actuator(), sca_move_controller(), sca_move_sensor(), scanfill(), shape_key_move_exec(), sort_seq(), txt_insert_buf(), txt_split_curline(), verify_socket_template_list(), vgroup_move_exec(), and wm_keymap_patch().
void BLI_movelisttolist (struct ListBase * dst, struct ListBase * src)
Definition at line 53 of file listbase.c.
References ListBase::first, ListBase::last, and NULL.
Referenced by add_main_to_main(), animdata_filter_dopesheet_ob(), animdata_filter_dopesheet_scene(), animdata_filter_ds_keyanim(), animdata_filter_ds_materials(), animdata_filter_ds_nodetree(), animdata_filter_ds_obanim(), animdata_filter_ds_obdata(), animdata_filter_ds_particles(), animdata_filter_ds_scene(), animdata_filter_ds_textures(), animdata_filter_ds_world(), animdata_filter_gpencil(), animfilter_act_group(), BKE_ptcache_ids_from_object(), BLI_edgefill_ex(), BM_faces_join(), bmesh_sfme(), ED_preview_icon_job(), ipo_to_animdata(), join_curve_exec(), join_groups_action_temp(), pose_proxy_synchronize(), rearrange_animchannel_flatten_islands(), seq_dupe_animdata(), sequencer_add_duplicate_exec(), sequencer_copy_exec(), sequencer_cut_exec(), sequencer_meta_separate_exec(), sequencer_paste_exec(), sort_seq(), splitlist(), wm_handler_fileselect_call(), wm_macro_invoke_internal(), and wm_operator_reports().
void BLI_remlink (struct ListBase * listbase, void * vlink)
Definition at line 101 of file listbase.c.
References ListBase::first, ListBase::last, link(), Link::next, NULL, and Link::prev.
Referenced by act_markers_make_local_exec(), action_groups_remove_channel(), actuator_remove_exec(), add_lightgroup(), ANIM_fcurve_delete_from_animdata(), ANIM_keyingset_info_unregister(), ANIM_remove_driver(), armature_merge_exec(), BKE_animdata_separate_by_basepath(), BKE_image_free_anim_ibufs(), BKE_image_merge(), BKE_library_make_local(), BKE_nlastrips_clear_metastrip(), BKE_nlastrips_make_metas(), BKE_nlastrips_sort_strips(), BKE_ptcache_free_list(), BKE_write_undo(), BLF_dir_rem(), blf_font_free(), blf_glyph_cache_clear(), blf_glyph_cache_free(), BLI_cb_finalize(), BLI_edgefill_ex(), BLI_freelinkN(), BLI_mempool_free(), BLI_remlink_safe(), BLI_sortlist(), blo_end_image_pointer_map(), BLO_free_memfile(), blo_join_main(), BLO_read_from_memfile(), BM_faces_join(), BMO_error_pop(), BMW_state_remove(), console_history_cycle_exec(), console_history_free(), console_scrollback_free(), console_scrollback_prompt_end(), constraint_move_down_exec(), constraint_move_up_exec(), controller_remove_exec(), KX_BlenderSceneConverter::ConvertMeshSpecial(), create_scene(), CTX_store_free_list(), cut_seq_list(), DAG_pose_sort(), DAG_scene_sort(), delete_exec(), delete_metaelems_exec(), deleteflagNurb(), direct_link_library(), direct_link_object(), direct_link_screen(), do_logic_buts(), do_version_free_effects_245(), draw_depth(), dupliob_move_down_exec(), dupliob_move_up_exec(), dynamicPaint_freeSurface(), ED_area_newspace(), ED_base_object_free_and_unlink(), ED_object_modifier_apply(), ED_object_modifier_move_down(), ED_object_modifier_move_up(), ED_object_shape_key_remove(), ED_region_draw_cb_exit(), ED_view3D_background_image_remove(), extract_proxylocal_constraints(), fcurve_path_rename(), fcurve_remove(), find_chain(), find_chain_search(), find_hole(), find_hole_search(), DocumentImporter::finish(), free_actuators(), free_controllers(), free_group_objects(), free_key(), free_key_nolib(), free_libblock(), free_properties(), free_sensors(), freedisplist(), freeMetaElemlist(), game_property_remove(), get_active_fcurve_channel(), get_best_nearest_fcurve_vert(), GPU_nodes_extract_dynamic_inputs(), GPU_nodes_free(), gpu_nodes_prune(), group_move_exec(), group_verify_socket(), id_sort_by_name(), IDP_RemFromGroup(), IDP_ReplaceGroupInGroup(), IDP_ReplaceInGroup(), IDP_SyncGroupValues(), iksolver_execute_tree(), image_free_buffers(), image_remove_ibuf(), IMB_exr_close(), imb_global_cache_get_tile(), imb_thread_cache_get_tile(), imb_tile_cache_tile_free(), initialize_posetree(), join_armature_exec(), join_groups_action_temp(), join_mesh_exec(), knife_make_face_cuts(), knife_split_edge(), lib_link_particlesystems(), lib_link_scene(), localize_lamp(), localize_material(), localize_texture(), localize_world(), loop_sync(), make_proxy_exec(), make_segment_exec(), make_selection_list_nurb(), makeBevelList(), mem_element_reset(), merge_2_nurb(), motionpaths_calc_optimise_depsgraph(), mouse_action_keys(), mouse_nla_strips(), nlaedit_move_down_exec(), nlaedit_move_up_exec(), nlaedit_snap_exec(), nlaedit_swap_exec(), nlaevalchan_buffers_accumulate(), node_group_make_from_selected(), node_group_remove_socket(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_ungroup(), node_link_cancel(), node_link_modal(), node_sort(), nodeFreeNode(), nodeRemLink(), nodeRemoveSocket(), object_free_modifiers(), object_free_particlesystems(), object_handle_update(), object_hook_remove_exec(), object_modifier_remove(), object_remove_particle_system(), old_sca_move_actuator(), old_sca_move_controller(), old_sca_move_sensor(), outliner_add_id_contents(), outliner_add_object_contents(), outliner_build_tree(), outliner_filter_tree(), outliner_free_tree(), outliner_make_hierarchy(), PE_undo_push(), pose_grab_with_ik_clear(), posttrans_gpd_clean(), ptcache_remove_exec(), RE_engines_exit(), RE_FreeRender(), read_libraries(), rearrange_animchannel_add_to_islands(), rearrange_island_bottom(), rearrange_island_down(), rearrange_island_top(), rearrange_island_up(), recalcData_nla(), recurs_del_seq_flag(), region_quadview_exec(), BOP_Mesh::rehashVertex(), rem_from_group_internal(), remove_particle_dupliob_exec(), remove_particle_target_exec(), removedouble_scredges(), removedouble_scrverts(), removenotused_scredges(), removenotused_scrverts(), render_result_free(), render_result_free_list(), render_result_single_layer_end(), repeat_history_exec(), report_delete_exec(), KX_BlenderSceneConverter::ResetPhysicsObjectsAnimationIpo(), RIG_removeUneededOffsets(), rule_del_exec(), rule_move_down_exec(), rule_move_up_exec(), sca_move_actuator(), sca_move_controller(), sca_move_sensor(), scanfill(), scene_remove_render_layer(), scene_sort_groups(), screen_delarea(), sensor_remove_exec(), separate_exec(), seq_free_animdata(), seq_free_editing(), sequencer_add_effect_strip_exec(), sequencer_meta_make_exec(), sequencer_meta_separate_exec(), sequencer_meta_toggle_exec(), sequencer_separate_images_exec(), set_ob_property(), shader_preview_free(), shape_key_move_exec(), sk_removeStroke(), sort_by_frac_along(), sort_keys(), sort_seq(), spacedata_cleanup(), split_libdata(), splitlist(), StartKetsjiShell(), state_del_exec(), state_move_down_exec(), state_move_up_exec(), target_move_down_exec(), target_move_up_exec(), time_draw_cache(), tracks_map_merge(), txt_delete_line(), ui_but_update_from_old_block(), ui_delete_active_linkline(), ui_delete_linkline(), ui_item_align(), uiBlockFlipOrder(), uiButActiveOnly(), uiFreeBlock(), uiFreeBlocks(), uiFreeInactiveBlocks(), verify_socket_template(), vgroup_move_exec(), view3d_draw_transp(), view3d_draw_xray(), view3d_draw_xraytransp(), wm_close_and_free(), wm_close_and_free_all(), WM_event_add_fileselect(), wm_event_do_handlers(), wm_event_free_all(), WM_event_remove_area_handler(), WM_event_remove_handlers(), WM_event_remove_keymap_handler(), WM_event_remove_timer(), WM_event_remove_ui_handler(), WM_gesture_end(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_handlers_do(), wm_jobs_kill_job(), wm_jobs_timer(), WM_keyconfig_remove(), wm_macro_modal(), wm_notifier_next(), wm_operator_register(), WM_operator_stack_clear(), WM_paint_cursor_end(), wm_subwindow_close(), wm_window_close(), and wm_window_match_init().
int BLI_remlink_safe (struct ListBase * listbase, void * vlink)
Definition at line 115 of file listbase.c.
References BLI_findindex(), and BLI_remlink().
Referenced by ANIM_keyingset_info_unregister(), and BL_ShapeDeformer::~BL_ShapeDeformer().
void* BLI_rfindlink (const struct ListBase * listbase, int number)
Referenced by bpy_bmeditselseq_subscript_int().
void* BLI_rfindstring (const struct ListBase * listbase, const char * id, const int offset)
Referenced by BKE_undo_name(), BKE_undo_valid(), and ctx_data_get().
void* BLI_rfindstring_ptr (const struct ListBase * listbase, const char * id, const int offset)
void BLI_sortlist (struct ListBase * listbase, int(*)(void *, void *) cmp)
Definition at line 176 of file listbase.c.
References BLI_insertlinkafter(), BLI_remlink(), ListBase::first, ListBase::last, Link::next, next, NULL, and Link::prev.
Referenced by object_insert_ptcache(), peelObjects(), rna_search_cb(), sk_getIntersections(), snode_autoconnect(), and vertex_group_sort_exec().