Blender: KX_TouchEventManager Class Reference
KX_TouchEventManager Class Reference
#include <KX_TouchEventManager.h>
Public Member Functions
KX_TouchEventManager (class SCA_LogicManager *logicmgr, PHY_IPhysicsEnvironment *physEnv)
virtual void NextFrame ()
virtual void EndFrame ()
virtual void RegisterSensor (SCA_ISensor *sensor)
virtual void RemoveSensor (SCA_ISensor *sensor)
SCA_LogicManager * GetLogicManager ()
PHY_IPhysicsEnvironment * GetPhysicsEnvironment ()
virtual void Replace_PhysicsScene (PHY_IPhysicsEnvironment *env)
Detailed Description
Definition at line 46 of file KX_TouchEventManager.h.
Constructor & Destructor Documentation
KX_TouchEventManager::KX_TouchEventManager (class SCA_LogicManager * logicmgr, PHY_IPhysicsEnvironment * physEnv)
Definition at line 41 of file KX_TouchEventManager.cpp.
References PHY_IPhysicsEnvironment::addTouchCallback(), PHY_BROADPH_RESPONSE, PHY_OBJECT_RESPONSE, and PHY_SENSOR_RESPONSE.
Member Function Documentation
void KX_TouchEventManager::EndFrame () [virtual]
Reimplemented from SCA_EventManager.
Definition at line 145 of file KX_TouchEventManager.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::iterator< T >::end(), and SCA_EventManager::m_sensors.
SCA_LogicManager* KX_TouchEventManager::GetLogicManager () [inline]
Definition at line 78 of file KX_TouchEventManager.h.
References SCA_EventManager::m_logicmgr.
PHY_IPhysicsEnvironment* KX_TouchEventManager::GetPhysicsEnvironment () [inline]
Definition at line 79 of file KX_TouchEventManager.h.
Referenced by KX_TouchSensor::RegisterSumo(), and KX_TouchSensor::UnregisterSumo().
void KX_TouchEventManager::NextFrame () [virtual]
Reimplemented from SCA_EventManager.
Definition at line 156 of file KX_TouchEventManager.cpp.
References SG_DList::iterator< T >::begin(), SG_DList::Empty(), SG_DList::iterator< T >::end(), PHY_IController::getNewClientInfo(), SCA_EventManager::m_logicmgr, KX_ClientObjectInfo::m_sensors, SCA_EventManager::m_sensors, KX_TouchSensor::NewHandleCollision(), and NULL.
void KX_TouchEventManager::RegisterSensor (SCA_ISensor * sensor) [virtual]
Reimplemented from SCA_EventManager.
Definition at line 127 of file KX_TouchEventManager.cpp.
References SG_DList::AddBack(), SCA_EventManager::m_sensors, and KX_TouchSensor::RegisterSumo().
void KX_TouchEventManager::RemoveSensor (SCA_ISensor * sensor) [virtual]
Reimplemented from SCA_EventManager.
Definition at line 135 of file KX_TouchEventManager.cpp.
References SG_DList::Delink(), and KX_TouchSensor::UnregisterSumo().
virtual void KX_TouchEventManager::Replace_PhysicsScene (PHY_IPhysicsEnvironment * env) [inline, virtual]
Reimplemented from SCA_EventManager.
Definition at line 80 of file KX_TouchEventManager.h.
The documentation for this class was generated from the following files:
KX_TouchEventManager.h
KX_TouchEventManager.cpp