Blender: btSoftBodyConcaveCollisionAlgorithm Class Reference
btSoftBodyConcaveCollisionAlgorithm Class Reference
btSoftBodyConcaveCollisionAlgorithm supports collision between soft body shapes and (concave) trianges meshes.
#include <btSoftBodyConcaveCollisionAlgorithm.h>
Classes
struct CreateFunc
struct SwappedCreateFunc
Public Member Functions
btSoftBodyConcaveCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *body0, btCollisionObject *body1, bool isSwapped)
virtual ~btSoftBodyConcaveCollisionAlgorithm ()
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
void clearCache ()
Detailed Description
btSoftBodyConcaveCollisionAlgorithm supports collision between soft body shapes and (concave) trianges meshes.
Definition at line 111 of file btSoftBodyConcaveCollisionAlgorithm.h.
Constructor & Destructor Documentation
btSoftBodyConcaveCollisionAlgorithm::btSoftBodyConcaveCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * body0, btCollisionObject * body1, bool isSwapped)
Definition at line 37 of file btSoftBodyConcaveCollisionAlgorithm.cpp.
Referenced by btSoftBodyConcaveCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm(), and btSoftBodyConcaveCollisionAlgorithm::SwappedCreateFunc::CreateCollisionAlgorithm().
btSoftBodyConcaveCollisionAlgorithm::~btSoftBodyConcaveCollisionAlgorithm () [virtual]
Definition at line 46 of file btSoftBodyConcaveCollisionAlgorithm.cpp.
Member Function Documentation
btScalar btSoftBodyConcaveCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 255 of file btSoftBodyConcaveCollisionAlgorithm.cpp.
References btSubsimplexConvexCast::calcTimeOfImpact(), btTransform::getOrigin(), btTransform::inverse(), btConvexCast::CastResult::m_fraction, btConcaveShape::processAllTriangles(), and btTransform::setIdentity().
void btSoftBodyConcaveCollisionAlgorithm::clearCache ()
Definition at line 211 of file btSoftBodyConcaveCollisionAlgorithm.cpp.
References btSoftBodyTriangleCallback::clearCache().
virtual void btSoftBodyConcaveCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Implements btCollisionAlgorithm.
Definition at line 128 of file btSoftBodyConcaveCollisionAlgorithm.h.
void btSoftBodyConcaveCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 217 of file btSoftBodyConcaveCollisionAlgorithm.cpp.
References btSoftBodyTriangleCallback::getAabbMax(), btSoftBodyTriangleCallback::getAabbMin(), btConcaveShape::getMargin(), btConcaveShape::processAllTriangles(), and btSoftBodyTriangleCallback::setTimeStepAndCounters().
The documentation for this class was generated from the following files:
btSoftBodyConcaveCollisionAlgorithm.h
btSoftBodyConcaveCollisionAlgorithm.cpp