Blender: MOD_build.c File Reference
MOD_build.c File Reference
modifiers
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_rand.h"
#include "BLI_ghash.h"
#include "DNA_scene_types.h"
#include "DNA_meshdata_types.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_object.h"
#include "BKE_particle.h"
#include "BKE_scene.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static int dependsOnTime (ModifierData *UNUSED(md))
static DerivedMesh * applyModifier (ModifierData *md, Object *UNUSED(ob), DerivedMesh *derivedData, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
Variables
ModifierTypeInfo modifierType_Build
Detailed Description
Definition in file MOD_build.c.
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * UNUSEDob, DerivedMesh * derivedData, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 78 of file MOD_build.c.
References BKE_curframe(), BLI_array_randomize(), BLI_ghash_free(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), BLI_ghash_size(), BLI_ghashIterator_free(), BLI_ghashIterator_getKey(), BLI_ghashIterator_getValue(), BLI_ghashIterator_isDone(), BLI_ghashIterator_new(), BLI_ghashIterator_step(), BLI_ghashutil_intcmp(), BLI_ghashutil_inthash(), CDDM_from_template(), CDDM_get_edge(), CDDM_get_loops(), CDDM_get_polys(), CDDM_get_vert(), CLAMP(), DM_copy_edge_data(), DM_copy_loop_data(), DM_copy_poly_data(), DM_copy_vert_data(), MLoop::e, faceMap, GET_INT_FROM_POINTER, DerivedMesh::getEdgeArray, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, i, BuildModifierData::length, MPoly::loopstart, MEM_callocN(), MEM_freeN(), NULL, BuildModifierData::randomize, ModifierData::scene, BuildModifierData::seed, SET_INT_IN_POINTER, BuildModifierData::start, MPoly::totloop, MLoop::v, MEdge::v1, and MEdge::v2.
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 62 of file MOD_build.c.
References BuildModifierData::length, BuildModifierData::randomize, BuildModifierData::seed, and BuildModifierData::start.
static int dependsOnTime (ModifierData * UNUSEDmd) [static]
Definition at line 73 of file MOD_build.c.
Referenced by mesh_calc_modifiers().
static void initData (ModifierData * md) [static]
Definition at line 54 of file MOD_build.c.
References BuildModifierData::length, and BuildModifierData::start.
Variable Documentation
ModifierTypeInfo modifierType_Build
Initial value:
 {
                  "Build",
            "BuildModifierData",
            sizeof(BuildModifierData),
                  eModifierTypeType_Nonconstructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_AcceptsCVs,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       NULL,
              initData,
      NULL,
              NULL,
            NULL,
        NULL,
         dependsOnTime,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 299 of file MOD_build.c.