Blender: MT_Point3.h File Reference
MT_Point3.h File Reference
moto
#include "MT_Vector3.h"
Classes
class MT_Point3
Functions
MT_Point3 operator+ (const MT_Point3 &p, const MT_Vector3 &v)
MT_Point3 operator- (const MT_Point3 &p, const MT_Vector3 &v)
MT_Vector3 operator- (const MT_Point3 &p1, const MT_Point3 &p2)
MT_Scalar MT_distance (const MT_Point3 &p1, const MT_Point3 &p2)
MT_Scalar MT_distance2 (const MT_Point3 &p1, const MT_Point3 &p2)
MT_Point3 MT_lerp (const MT_Point3 &p1, const MT_Point3 &p2, MT_Scalar t)
Detailed Description
Definition in file MT_Point3.h.
Function Documentation
MT_Scalar MT_distance (const MT_Point3 & p1, const MT_Point3 & p2)
Definition at line 49 of file MT_Point3.inl.
References MT_Point3::distance().
MT_Scalar MT_distance2 (const MT_Point3 & p1, const MT_Point3 & p2)
Definition at line 53 of file MT_Point3.inl.
References MT_Point3::distance2().
MT_Point3 MT_lerp (const MT_Point3 & p1, const MT_Point3 & p2, MT_Scalar t)
Definition at line 57 of file MT_Point3.inl.
References MT_Point3::lerp().
MT_Point3 operator+ (const MT_Point3 & p, const MT_Vector3 & v)
Definition at line 37 of file MT_Point3.inl.
MT_Vector3 operator- (const MT_Point3 & p1, const MT_Point3 & p2)
Definition at line 45 of file MT_Point3.inl.
MT_Point3 operator- (const MT_Point3 & p, const MT_Vector3 & v)
Definition at line 41 of file MT_Point3.inl.