Blender: btPairCachingGhostObject Class Reference
btPairCachingGhostObject Class Reference
#include <btGhostObject.h>
Public Member Functions
btPairCachingGhostObject ()
virtual ~btPairCachingGhostObject ()
virtual void addOverlappingObjectInternal (btBroadphaseProxy *otherProxy, btBroadphaseProxy *thisProxy=0)
this method is mainly for expert/internal use only.
virtual void removeOverlappingObjectInternal (btBroadphaseProxy *otherProxy, btDispatcher *dispatcher, btBroadphaseProxy *thisProxy=0)
btHashedOverlappingPairCache * getOverlappingPairCache ()
Detailed Description
Definition at line 99 of file btGhostObject.h.
Constructor & Destructor Documentation
btPairCachingGhostObject::btPairCachingGhostObject ()
Definition at line 59 of file btGhostObject.cpp.
References btAlignedAlloc.
btPairCachingGhostObject::~btPairCachingGhostObject () [virtual]
Definition at line 64 of file btGhostObject.cpp.
References btAlignedFree, and btHashedOverlappingPairCache::~btHashedOverlappingPairCache().
Member Function Documentation
void btPairCachingGhostObject::addOverlappingObjectInternal (btBroadphaseProxy * otherProxy, btBroadphaseProxy * thisProxy = 0) [virtual]
this method is mainly for expert/internal use only.
Definition at line 70 of file btGhostObject.cpp.
References btHashedOverlappingPairCache::addOverlappingPair(), and btAssert.
btHashedOverlappingPairCache* btPairCachingGhostObject::getOverlappingPairCache () [inline]
Definition at line 114 of file btGhostObject.h.
Referenced by btKinematicCharacterController::recoverFromPenetration().
void btPairCachingGhostObject::removeOverlappingObjectInternal (btBroadphaseProxy * otherProxy, btDispatcher * dispatcher, btBroadphaseProxy * thisProxy = 0) [virtual]
Definition at line 85 of file btGhostObject.cpp.
References btAssert, and btHashedOverlappingPairCache::removeOverlappingPair().
The documentation for this class was generated from the following files:
btGhostObject.h
btGhostObject.cpp