Blender: util_time.cpp File Reference
util_time.cpp File Reference
#include <stdlib.h>
#include "util_time.h"
#include <sys/time.h>
#include <unistd.h>
Functions
CCL_NAMESPACE_BEGIN double time_dt ()
void time_sleep (double t)
Function Documentation
CCL_NAMESPACE_BEGIN double time_dt ()
Definition at line 53 of file util_time.cpp.
References NULL.
Referenced by CUDADevice::compile_kernel(), display_info(), Session::draw_cpu(), Session::draw_gpu(), Progress::Progress(), BVHBuild::progress_update(), Session::ready_to_reset(), Session::reset_(), Session::reset_cpu(), Session::reset_gpu(), BVHBuild::run(), Session::run_cpu(), Session::run_gpu(), Progress::set_sample(), Progress::set_status(), Progress::set_substatus(), BlenderSession::tag_redraw(), and Session::update_status_time().
void time_sleep (double t)
Definition at line 61 of file util_time.cpp.
Referenced by MultiDevice::MultiDevice(), and view_idle().