Blender: sgstrf.c File Reference
sgstrf.c File Reference
opennl
#include "ssp_defs.h"
Functions
void sgstrf (superlu_options_t *options, SuperMatrix *A, int relax, int panel_size, int *etree, void *work, int lwork, int *perm_c, int *perm_r, SuperMatrix *L, SuperMatrix *U, SuperLUStat_t *stat, int *info)
Detailed Description
Definition in file sgstrf.c.
Function Documentation
void sgstrf (superlu_options_t * options, SuperMatrix * A, int relax, int panel_size, int * etree, void * work, int lwork, int * perm_c, int * perm_r, SuperMatrix * L, SuperMatrix * U, SuperLUStat_t * stat, int * info)
Definition at line 28 of file sgstrf.c.
References NCPformat::colbeg, NCPformat::colend, countnz(), superlu_options_t::DiagPivotThresh, EMPTY, FACT, superlu_options_t::Fact, fixupL(), GEMV, heap_relax_snode(), i, ifill(), intMalloc(), GlobalLU_t::lsub, GlobalLU_t::lusup, LUSUP, SuperMatrix::ncol, NCPformat::nnz, NO_MARKER, SuperMatrix::nrow, NULL, GlobalLU_t::nzlumax, NCPformat::nzval, SuperLUStat_t::ops, SuperLUStat_t::panel_histo, relax_snode(), resetrep_col(), NCPformat::rowind, SamePattern_SameRowPerm, scolumn_bmod(), scolumn_dfs(), scopy_to_ucol(), sCreate_CompCol_Matrix(), sCreate_SuperNode_Matrix(), SetIWork(), SLU_NC, SLU_S, SLU_SC, SLU_TRLU, SLU_TRU, sLUMemInit(), sLUMemXpand(), sLUWorkFree(), spanel_bmod(), spanel_dfs(), spivotL(), sprint_lu_col(), spruneL(), sSetRWork(), ssnode_bmod(), ssnode_dfs(), SuperMatrix::Store, SUPERLU_FREE, SUPERLU_MIN, GlobalLU_t::supno, superlu_options_t::SymmetricMode, TRSV, GlobalLU_t::ucol, GlobalLU_t::usub, GlobalLU_t::xlsub, GlobalLU_t::xlusup, GlobalLU_t::xsup, GlobalLU_t::xusub, and YES.
Referenced by __nlFactorize_SUPERLU(), and sgssv().