Blender: file_intern.h File Reference
file_intern.h File Reference
fileselector
Defines
#define TILE_BORDER_X (UI_UNIT_X/4)
#define TILE_BORDER_Y (UI_UNIT_Y/4)
#define IMASEL_BUTTONS_HEIGHT (UI_UNIT_Y*2)
#define IMASEL_BUTTONS_MARGIN (UI_UNIT_Y/6)
Functions
struct ARegion * file_buttons_region (struct ScrArea *sa)
void file_draw_buttons (const bContext *C, ARegion *ar)
void file_calc_previews (const bContext *C, ARegion *ar)
void file_draw_list (const bContext *C, ARegion *ar)
void file_draw_check_cb (bContext *C, void *arg1, void *arg2)
int file_draw_check_exists (SpaceFile *sfile)
void FILE_OT_highlight (struct wmOperatorType *ot)
void FILE_OT_select (struct wmOperatorType *ot)
void FILE_OT_select_all_toggle (struct wmOperatorType *ot)
void FILE_OT_select_border (struct wmOperatorType *ot)
void FILE_OT_select_bookmark (struct wmOperatorType *ot)
void FILE_OT_bookmark_add (struct wmOperatorType *ot)
void FILE_OT_delete_bookmark (struct wmOperatorType *ot)
void FILE_OT_hidedot (struct wmOperatorType *ot)
void FILE_OT_execute (struct wmOperatorType *ot)
void FILE_OT_cancel (struct wmOperatorType *ot)
void FILE_OT_parent (struct wmOperatorType *ot)
void FILE_OT_directory_new (struct wmOperatorType *ot)
void FILE_OT_directory (struct wmOperatorType *ot)
void FILE_OT_previous (struct wmOperatorType *ot)
void FILE_OT_next (struct wmOperatorType *ot)
void FILE_OT_refresh (struct wmOperatorType *ot)
void FILE_OT_bookmark_toggle (struct wmOperatorType *ot)
void FILE_OT_filenum (struct wmOperatorType *ot)
void FILE_OT_delete (struct wmOperatorType *ot)
void FILE_OT_rename (struct wmOperatorType *ot)
void FILE_OT_smoothscroll (struct wmOperatorType *ot)
int file_exec (bContext *C, struct wmOperator *exec_op)
int file_cancel_exec (bContext *C, struct wmOperator *unused)
int file_parent_exec (bContext *C, struct wmOperator *unused)
int file_previous_exec (bContext *C, struct wmOperator *unused)
int file_next_exec (bContext *C, struct wmOperator *unused)
int file_filename_exec (bContext *C, struct wmOperator *unused)
int file_directory_exec (bContext *C, struct wmOperator *unused)
int file_directory_new_exec (bContext *C, struct wmOperator *unused)
int file_delete_exec (bContext *C, struct wmOperator *unused)
int file_hilight_set (struct SpaceFile *sfile, struct ARegion *ar, int mx, int my)
void file_sfile_to_operator (struct wmOperator *op, struct SpaceFile *sfile, char *filepath)
void file_operator_to_sfile (struct SpaceFile *sfile, struct wmOperator *op)
float file_shorten_string (char *string, float w, int front)
float file_string_width (const char *str)
float file_font_pointsize (void)
void file_change_dir (bContext *C, int checkdir)
int file_select_match (struct SpaceFile *sfile, const char *pattern)
void autocomplete_directory (struct bContext *C, char *str, void *arg_v)
void autocomplete_file (struct bContext *C, char *str, void *arg_v)
void file_panels_register (struct ARegionType *art)
Detailed Description
Definition in file file_intern.h.
Define Documentation
#define IMASEL_BUTTONS_HEIGHT (UI_UNIT_Y*2)
Definition at line 48 of file file_intern.h.
Referenced by file_draw_buttons().
#define IMASEL_BUTTONS_MARGIN (UI_UNIT_Y/6)
Definition at line 49 of file file_intern.h.
Referenced by file_draw_buttons().
#define TILE_BORDER_X (UI_UNIT_X/4)
Definition at line 44 of file file_intern.h.
#define TILE_BORDER_Y (UI_UNIT_Y/4)
Definition at line 45 of file file_intern.h.
Function Documentation
void autocomplete_directory (struct bContext * C, char * str, void * arg_v)
Referenced by file_draw_buttons().
void autocomplete_file (struct bContext * C, char * str, void * arg_v)
Referenced by file_draw_buttons().
struct ARegion* file_buttons_region (struct ScrArea * sa) [read]
Definition at line 1254 of file file_ops.c.
References ARegion::alignment, BLI_insertlinkafter(), ListBase::first, ARegion::flag, MEM_callocN(), ARegion::next, NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_TYPE_CHANNELS, and RGN_TYPE_HEADER.
Referenced by file_bookmark_toggle_exec().
void file_calc_previews (const bContext * C, ARegion * ar)
Definition at line 316 of file file_draw.c.
References CTX_wm_space_file(), ED_fileselect_init_layout(), FileLayout::height, SpaceFile::layout, UI_view2d_totRect_set(), ARegion::v2d, V2D_SCROLL_HEIGHT, and FileLayout::width.
Referenced by file_main_area_draw().
int file_cancel_exec (bContext * C, struct wmOperator * unused)
Referenced by FILE_OT_cancel().
void file_change_dir (bContext * C, int checkdir)
Definition at line 570 of file filesel.c.
References BLI_is_dir(), BLI_strncpy(), CTX_wm_space_file(), FileSelectParams::dir, ED_fileselect_clear(), filelist_dir(), filelist_setdir(), SpaceFile::files, folderlist_clear_next(), folderlist_free(), folderlist_pushdir(), SpaceFile::folders_next, SpaceFile::folders_prev, and SpaceFile::params.
Referenced by bookmark_select_exec(), file_directory_exec(), file_next_exec(), file_parent_exec(), file_previous_exec(), and file_select_do().
int file_delete_exec (bContext * C, struct wmOperator * unused)
Referenced by FILE_OT_delete().
int file_directory_exec (bContext * C, struct wmOperator * unused)
Referenced by do_file_buttons(), file_directory_invoke(), and FILE_OT_directory().
int file_directory_new_exec (bContext * C, struct wmOperator * unused)
Definition at line 1030 of file file_ops.c.
References BKE_report(), BLI_dir_create_recursive(), BLI_exists(), BLI_strncpy(), CTX_wm_manager(), CTX_wm_space_file(), CTX_wm_window(), FileSelectParams::dir, ED_fileselect_clear(), FILE_MAX, FILE_MAXFILE, NC_SPACE, ND_SPACE_FILE_LIST, new_folder_path(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, SpaceFile::params, direntry::path, wmOperator::ptr, FileSelectParams::renamefile, wmOperator::reports, RNA_string_get(), RNA_struct_find_property(), RPT_ERROR, RPT_WARNING, SpaceFile::scroll_offset, SpaceFile::smoothscroll_timer, TIMER1, WM_event_add_notifier(), and WM_event_add_timer().
Referenced by FILE_OT_directory_new().
void file_draw_buttons (const bContext * C, ARegion * ar)
Definition at line 108 of file file_draw.c.
References autocomplete_directory(), autocomplete_file(), B_FS_FILENAME, BLI_snprintf(), BUT, CTX_wm_area(), CTX_wm_space_file(), FileSelectParams::dir, do_file_buttons(), ED_fileselect_get_params(), FileSelectParams::file, FILE_DIRSEL_ONLY, file_draw_check_cb(), file_draw_check_exists(), FILE_MAX, FILE_MAXFILE, ARegion::flag, FileSelectParams::flag, IFACE_, IMASEL_BUTTONS_HEIGHT, IMASEL_BUTTONS_MARGIN, MAX2, N_, ARegion::next, NULL, SpaceFile::params, ARegion::regiontype, RGN_FLAG_HIDDEN, RGN_TYPE_CHANNELS, RNA_int_set(), TEX, TIP_, FileSelectParams::title, UI_BUT_NO_UTF8, UI_BUT_REDALERT, UI_BUT_UNDO, UI_EMBOSS, UI_GetStringWidth(), UI_UNIT_X, UI_UNIT_Y, uiBeginBlock(), uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetFunc(), uiBlockSetHandleFunc(), uiButClearFlag(), uiButGetOperatorPtrRNA(), uiButSetCompleteFunc(), uiButSetFlag(), uiDefBut(), uiDefButO(), uiDefButTextO(), uiDefIconButO(), uiDrawBlock(), uiEndBlock(), ARegion::winx, ARegion::winy, and WM_OP_EXEC_REGION_WIN.
Referenced by file_ui_area_draw().
void file_draw_check_cb (bContext * C, void * arg1, void * arg2)
Referenced by file_draw_buttons(), file_filenum_exec(), file_panel_operator(), and file_select().
int file_draw_check_exists (SpaceFile * sfile)
Definition at line 713 of file file_ops.c.
References BLI_is_file(), BLI_join_dirfile(), FileSelectParams::dir, FALSE, FileSelectParams::file, FILE_MAX, SpaceFile::op, SpaceFile::params, wmOperator::ptr, RNA_boolean_get(), RNA_struct_find_property(), and TRUE.
Referenced by file_draw_buttons().
void file_draw_list (const bContext * C, ARegion * ar)
Definition at line 446 of file file_draw.c.
References FileSelectParams::active_file, COLUMN_DATE, COLUMN_MODE1, COLUMN_MODE2, COLUMN_MODE3, COLUMN_NAME, COLUMN_OWNER, COLUMN_SIZE, COLUMN_TIME, FileLayout::column_widths, FileLayout::columns, CTX_wm_space_file(), View2D::cur, direntry::date, FileSelectParams::display, draw_background(), draw_dividers(), draw_tile(), ED_fileselect_get_layout(), ED_fileselect_get_params(), ED_fileselect_layout_numfiles(), ED_fileselect_layout_offset(), ED_fileselect_layout_tilepos(), EDITING_FILE, file_draw_icon(), file_draw_preview(), file_draw_string(), FILE_IMGDISPLAY, FILE_LAYOUT_HOR, FILE_LONGDISPLAY, FILE_SHORTDISPLAY, filelist_file(), filelist_geticon(), filelist_getimage(), filelist_numfiles(), SpaceFile::files, files, FileLayout::flag, direntry::flags, get_file_icon(), HILITED_FILE, i, ICON_DEFAULT_HEIGHT_SCALE, ICON_DEFAULT_WIDTH_SCALE, if(), IMAGEFILE, SpaceFile::layout, direntry::mode1, direntry::mode2, direntry::mode3, direntry::owner, SpaceFile::params, direntry::path, direntry::relname, renamebutton_cb(), FileSelectParams::renameedit, FileLayout::rows, SELECTED_FILE, direntry::selflag, direntry::size, TEX, FileLayout::textheight, TH_BACK, TH_HILITE, TH_TEXT, FileLayout::tile_border_y, FileLayout::tile_h, FileLayout::tile_w, direntry::time, View2D::tot, direntry::type, UI_BUT_NO_UTF8, UI_BUT_UNDO, UI_CNR_NONE, UI_EMBOSS, UI_STYLE_TEXT_CENTER, UI_STYLE_TEXT_LEFT, UI_ThemeColor4(), UI_UNIT_Y, uiBeginBlock(), uiButActiveOnly(), uiButClearFlag(), uiButSetFlag(), uiButSetRenameFunc(), uiDefBut(), uiDrawBlock(), uiEndBlock(), uiSetRoundBox(), ARegion::v2d, rctf::xmin, and rctf::ymax.
Referenced by file_main_area_draw().
int file_exec (bContext * C, struct wmOperator * exec_op)
Definition at line 731 of file file_ops.c.
References BLENDER_BOOKMARK_FILE, BLENDER_USER_CONFIG, BLI_exists(), BLI_get_folder_create(), BLI_make_file_string(), CHECK_ALL, CTX_wm_space_file(), FileSelectParams::dir, EVT_FILESELECT_EXEC, FILE_MAX, file_sfile_to_operator(), filelist_is_selected(), filelist_numfiles(), SpaceFile::files, FS_CATEGORY_RECENT, fsmenu_get(), fsmenu_insert_entry(), fsmenu_write_file(), G, i, NULL, SpaceFile::op, OPERATOR_CANCELLED, OPERATOR_FINISHED, SpaceFile::params, wmOperator::ptr, RNA_boolean_get(), and WM_event_fileselect_event().
Referenced by FILE_OT_execute().
int file_filename_exec (bContext * C, struct wmOperator * unused)
Referenced by do_file_buttons().
float file_font_pointsize (void)
Definition at line 425 of file filesel.c.
References BLF_height(), uiFontStyle::points, UI_DPI_FAC, UI_GetStyle(), uiFontStyle::uifont_id, uiStyleFontSet(), and uiStyle::widget.
Referenced by ED_fileselect_init_layout().
int file_hilight_set (struct SpaceFile * sfile, struct ARegion * ar, int mx, int my)
Definition at line 518 of file file_ops.c.
References FileSelectParams::active_file, BLI_in_rcti(), ED_fileselect_get_params(), ED_fileselect_layout_offset(), filelist_numfiles(), SpaceFile::files, SpaceFile::layout, View2D::mask, NULL, View2D::tot, UI_view2d_region_to_view(), ARegion::v2d, ARegion::winrct, rcti::xmin, rctf::xmin, rctf::ymax, and rcti::ymin.
Referenced by file_highlight_invoke(), and file_main_area_draw().
int file_next_exec (bContext * C, struct wmOperator * unused)
Referenced by FILE_OT_next().
void file_operator_to_sfile (struct SpaceFile * sfile, struct wmOperator * op)
Definition at line 667 of file file_ops.c.
References BLI_path_abs(), BLI_split_dirfile(), FileSelectParams::dir, FileSelectParams::file, FILE_MAX, G, SpaceFile::params, wmOperator::ptr, RNA_property_string_get(), and RNA_struct_find_property().
Referenced by file_draw_check_cb().
void FILE_OT_bookmark_add (struct wmOperatorType * ot)
Definition at line 471 of file file_ops.c.
References bookmark_add_exec(), wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_bookmark_toggle (struct wmOperatorType * ot)
Definition at line 1292 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_bookmark_toggle_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_cancel (struct wmOperatorType * ot)
Definition at line 600 of file file_ops.c.
References wmOperatorType::description, wmOperatorType::exec, file_cancel_exec(), file_operator_poll(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_delete (struct wmOperatorType * ot)
Definition at line 1430 of file file_ops.c.
References wmOperatorType::description, wmOperatorType::exec, file_delete_exec(), file_delete_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and WM_operator_confirm().
Referenced by file_operatortypes().
void FILE_OT_delete_bookmark (struct wmOperatorType * ot)
Definition at line 504 of file file_ops.c.
References bookmark_delete_exec(), wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by file_operatortypes().
void FILE_OT_directory (struct wmOperatorType * ot)
Definition at line 1203 of file file_ops.c.
References wmOperatorType::description, wmOperatorType::exec, file_directory_exec(), file_directory_invoke(), file_directory_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_directory_new (struct wmOperatorType * ot)
Definition at line 1081 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_directory_new_exec(), FILE_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_string_dir_path(), wmOperatorType::srna, and WM_operator_confirm().
Referenced by file_operatortypes().
void FILE_OT_execute (struct wmOperatorType * ot)
Definition at line 770 of file file_ops.c.
References wmOperatorType::description, wmOperatorType::exec, file_exec(), file_operator_poll(), wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by file_operatortypes().
void FILE_OT_filenum (struct wmOperatorType * ot)
Definition at line 1322 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_filenum_exec(), wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by file_operatortypes().
void FILE_OT_hidedot (struct wmOperatorType * ot)
Definition at line 1242 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_hidedot_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_highlight (struct wmOperatorType * ot)
Definition at line 566 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), file_highlight_invoke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_next (struct wmOperatorType * ot)
Definition at line 863 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_next_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_parent (struct wmOperatorType * ot)
Definition at line 807 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_parent_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_previous (struct wmOperatorType * ot)
Definition at line 832 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_previous_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_refresh (struct wmOperatorType * ot)
Definition at line 1216 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_refresh_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_rename (struct wmOperatorType * ot)
Definition at line 1377 of file file_ops.c.
References wmOperatorType::description, wmOperatorType::exec, file_rename_exec(), file_rename_poll(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_select (struct wmOperatorType * ot)
Definition at line 354 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), file_select_invoke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by file_operatortypes().
void FILE_OT_select_all_toggle (struct wmOperatorType * ot)
Definition at line 401 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_select_all_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void FILE_OT_select_bookmark (struct wmOperatorType * ot)
Definition at line 438 of file file_ops.c.
References bookmark_select_exec(), wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by file_operatortypes().
void FILE_OT_select_border (struct wmOperatorType * ot)
Definition at line 303 of file file_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_file_active(), wmOperatorType::exec, file_border_select_exec(), file_border_select_modal(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, WM_border_select_cancel(), WM_border_select_invoke(), and WM_operator_properties_gesture_border().
Referenced by file_operatortypes().
void FILE_OT_smoothscroll (struct wmOperatorType * ot)
Definition at line 993 of file file_ops.c.
References wmOperatorType::description, ED_operator_file_active(), file_smoothscroll_invoke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, and wmOperatorType::poll.
Referenced by file_operatortypes().
void file_panels_register (struct ARegionType * art)
Definition at line 202 of file file_panels.c.
References BLI_addtail(), PanelType::draw, PanelType::draw_header, file_panel_bookmarks(), file_panel_operator(), file_panel_operator_header(), file_panel_operator_poll(), file_panel_recent(), file_panel_system(), PanelType::idname, PanelType::label, MEM_callocN(), N_, ARegionType::paneltypes, and PanelType::poll.
Referenced by ED_spacetype_file().
int file_parent_exec (bContext * C, struct wmOperator * unused)
Referenced by FILE_OT_parent().
int file_previous_exec (bContext * C, struct wmOperator * unused)
Referenced by FILE_OT_previous().
int file_select_match (struct SpaceFile * sfile, const char * pattern)
Definition at line 592 of file filesel.c.
References filelist_file(), filelist_numfiles(), SpaceFile::files, i, direntry::relname, SELECTED_FILE, and direntry::selflag.
Referenced by file_filename_exec().
void file_sfile_to_operator (struct wmOperator * op, struct SpaceFile * sfile, char * filepath)
Definition at line 613 of file file_ops.c.
References BLI_join_dirfile(), BLI_path_rel(), CHECK_DIRS, CHECK_FILES, FileSelectParams::dir, FileSelectParams::file, FILE_MAX, filelist_file(), filelist_is_selected(), filelist_numfiles(), SpaceFile::files, G, i, SpaceFile::params, wmOperator::ptr, direntry::relname, RNA_boolean_get(), RNA_property_collection_add(), RNA_property_collection_clear(), RNA_string_set(), and RNA_struct_find_property().
Referenced by file_draw_check_cb(), and file_exec().
float file_shorten_string (char * string, float w, int front)
Definition at line 369 of file filesel.c.
References BLI_strncpy(), FILE_MAX, file_string_width(), and strlen().
Referenced by file_draw_string().
float file_string_width (const char * str)
Definition at line 418 of file filesel.c.
References BLF_width(), UI_GetStyle(), uiFontStyle::uifont_id, uiStyleFontSet(), and uiStyle::widget.
Referenced by column_widths(), and file_shorten_string().