Blender: IMB_thumbs.h File Reference
IMB_thumbs.h File Reference
IMage Buffer
Defines
#define THUMB_SIZE_MAX (100 * 1024*1024)
Typedefs
typedef enum ThumbSize ThumbSize
typedef enum ThumbSource ThumbSource
Enumerations
enum ThumbSize { THB_NORMAL, THB_LARGE, THB_FAIL }
enum ThumbSource { THB_SOURCE_IMAGE, THB_SOURCE_MOVIE, THB_SOURCE_BLEND }
Functions
ImBuf * IMB_thumb_create (const char *path, ThumbSize size, ThumbSource source, ImBuf *ibuf)
ImBuf * IMB_thumb_read (const char *path, ThumbSize size)
void IMB_thumb_delete (const char *path, ThumbSize size)
ImBuf * IMB_thumb_manage (const char *path, ThumbSize size, ThumbSource source)
void IMB_thumb_makedirs (void)
ImBuf * IMB_loadblend_thumb (const char *path)
void IMB_overlayblend_thumb (unsigned int *thumb, int width, int height, float aspect)
Detailed Description
Definition in file IMB_thumbs.h.
Define Documentation
#define THUMB_SIZE_MAX (100 * 1024*1024)
Definition at line 61 of file IMB_thumbs.h.
Referenced by IMB_thumb_create().
Typedef Documentation
typedef enum ThumbSize ThumbSize
Thumbnail creation and retrieval according to the 'Thumbnail Management Standard' supported by Gimp, Gnome (Nautilus), KDE etc. Reference: http://jens.triq.net/thumbnail-spec/index.html
typedef enum ThumbSource ThumbSource
Enumeration Type Documentation
enum ThumbSize
Thumbnail creation and retrieval according to the 'Thumbnail Management Standard' supported by Gimp, Gnome (Nautilus), KDE etc. Reference: http://jens.triq.net/thumbnail-spec/index.html
Enumerator:
THB_NORMAL
THB_LARGE
THB_FAIL
Definition at line 48 of file IMB_thumbs.h.
enum ThumbSource
Enumerator:
THB_SOURCE_IMAGE
THB_SOURCE_MOVIE
THB_SOURCE_BLEND
Definition at line 54 of file IMB_thumbs.h.
Function Documentation
ImBuf* IMB_loadblend_thumb (const char * path)
Definition at line 124 of file thumbs_blend.c.
References BLI_gzopen(), loadblend_thumb(), and NULL.
Referenced by IMB_thumb_create().
void IMB_overlayblend_thumb (unsigned int * thumb, int width, int height, float aspect)
Definition at line 146 of file thumbs_blend.c.
References CLAMP(), and MARGIN.
Referenced by blend_file_thumb().
ImBuf* IMB_thumb_create (const char * path, ThumbSize size, ThumbSource source, ImBuf * ibuf)
Definition at line 256 of file thumbs.c.
References abs(), BLI_file_size(), BLI_path_ncmp, BLI_rename(), BLI_snprintf(), FILE_MAX, ImBuf::ftype, get_thumb_dir(), IB_metadata, IB_rect, IMB_allocImBuf(), IMB_anim_absolute(), IMB_anim_previewframe(), IMB_free_anim(), IMB_freeImBuf(), imb_freerectfloatImBuf(), IMB_loadblend_thumb(), IMB_loadiffname(), IMB_metadata_change_field(), IMB_open_anim(), IMB_PROXY_NONE, IMB_rect_from_float(), IMB_saveiff(), IMB_scaleImBuf(), IMB_TC_NONE, NULL, ImBuf::planes, PNG, ImBuf::rect, ImBuf::rect_float, THB_FAIL, THB_LARGE, THB_NORMAL, THB_SOURCE_BLEND, THB_SOURCE_IMAGE, THB_SOURCE_MOVIE, THUMB_SIZE_MAX, thumbname_from_uri(), uri_from_filename(), URI_MAX, ImBuf::x, and ImBuf::y.
Referenced by IMB_thumb_manage(), and WM_write_file().
void IMB_thumb_delete (const char * path, ThumbSize size)
Definition at line 412 of file thumbs.c.
References BLI_delete(), BLI_exists(), BLI_path_ncmp, FILE_MAX, thumbpath_from_uri(), and uri_from_filename().
Referenced by IMB_thumb_manage(), and WM_write_file().
void IMB_thumb_makedirs (void)
Definition at line 244 of file thumbs.c.
References BLI_dir_create_recursive(), FILE_MAX, get_thumb_dir(), THB_FAIL, and THB_NORMAL.
Referenced by ED_file_init().
ImBuf* IMB_thumb_manage (const char * path, ThumbSize size, ThumbSource source)
Definition at line 432 of file thumbs.c.
References BLI_delete(), BLI_exists(), BLI_file_older(), BLI_path_ncmp, FILE_MAX, IB_metadata, IB_rect, IMB_freeImBuf(), IMB_loadiffname(), IMB_metadata_get_field(), IMB_thumb_create(), IMB_thumb_delete(), NULL, THB_FAIL, THB_LARGE, THB_NORMAL, thumbpath_from_uri(), and uri_from_filename().
Referenced by thumbnails_startjob().
ImBuf* IMB_thumb_read (const char * path, ThumbSize size)
Definition at line 395 of file thumbs.c.
References FILE_MAX, IB_metadata, IB_rect, IMB_loadiffname(), NULL, thumbpath_from_uri(), and uri_from_filename().