Blender: btSoftColliders::ClusterBase Struct Reference
btSoftColliders::ClusterBase Struct Reference
#include <btSoftBodyInternals.h>
Public Member Functions
ClusterBase ()
bool SolveContact (const btGjkEpaSolver2::sResults &res, btSoftBody::Body ba, btSoftBody::Body bb, btSoftBody::CJoint &joint)
Public Attributes
btScalar erp
btScalar idt
btScalar m_margin
btScalar friction
btScalar threshold
Detailed Description
Definition at line 653 of file btSoftBodyInternals.h.
Constructor & Destructor Documentation
btSoftColliders::ClusterBase::ClusterBase () [inline]
Definition at line 660 of file btSoftBodyInternals.h.
Member Function Documentation
bool btSoftColliders::ClusterBase::SolveContact (const btGjkEpaSolver2::sResults & res, btSoftBody::Body ba, btSoftBody::Body bb, btSoftBody::CJoint & joint) [inline]
Definition at line 668 of file btSoftBodyInternals.h.
References btDot(), btGjkEpaSolver2::sResults::distance, btTransform::getBasis(), btTransform::getOrigin(), ImpulseMatrix(), btSoftBody::Body::invMass(), btSoftBody::Body::invWorldInertia(), btSoftBody::Joint::m_bodies, btSoftBody::Joint::m_cfm, btSoftBody::Joint::m_delete, btSoftBody::Joint::m_drift, btSoftBody::Joint::m_erp, btSoftBody::CJoint::m_friction, btSoftBody::CJoint::m_life, btSoftBody::Joint::m_massmatrix, btSoftBody::CJoint::m_maxlife, btSoftBody::CJoint::m_normal, btSoftBody::Joint::m_refs, btSoftBody::CJoint::m_rpos, btSoftBody::Joint::m_split, norm(), btGjkEpaSolver2::sResults::normal, btSoftBody::Body::velocity(), btGjkEpaSolver2::sResults::witnesses, and btSoftBody::Body::xform().
Member Data Documentation
btScalar btSoftColliders::ClusterBase::erp
Definition at line 655 of file btSoftBodyInternals.h.
btScalar btSoftColliders::ClusterBase::friction
Definition at line 658 of file btSoftBodyInternals.h.
btScalar btSoftColliders::ClusterBase::idt
Definition at line 656 of file btSoftBodyInternals.h.
btScalar btSoftColliders::ClusterBase::m_margin
Definition at line 657 of file btSoftBodyInternals.h.
btScalar btSoftColliders::ClusterBase::threshold
Definition at line 659 of file btSoftBodyInternals.h.
The documentation for this struct was generated from the following file:
btSoftBodyInternals.h