Blender: BOP_Splitter.cpp File Reference
BOP_Splitter.cpp File Reference
#include "BOP_Splitter.h"
#include "BOP_Tag.h"
#include <iostream>
Functions
MT_Point3 BOP_splitEdge (MT_Plane3 plane, BOP_Mesh *m, BOP_Face *f, unsigned int e)
BOP_Segment BOP_splitFace (MT_Plane3 plane, BOP_Mesh *m, BOP_Face *f)
Detailed Description
Definition in file BOP_Splitter.cpp.
Function Documentation
MT_Point3 BOP_splitEdge (MT_Plane3 plane, BOP_Mesh * m, BOP_Face * f, unsigned int e)
Returns the split point resulting from intersect a plane and a mesh face according to its specified relative edge.
Parameters:
plane split plane
m mesh
f face
e relative edge index
Returns:
intersection point
Definition at line 47 of file BOP_Splitter.cpp.
References BOP_intersectPlane(), BOP_Vertex::getPoint(), BOP_Face::getVertex(), and BOP_Mesh::getVertex().
Referenced by BOP_getPoints().
BOP_Segment BOP_splitFace (MT_Plane3 plane, BOP_Mesh * m, BOP_Face * f)
Returns the segment resulting from intersect a plane and a mesh face.
Parameters:
plane split plane
m mesh
f face
Returns:
segment if there is intersection, NULL otherwise
Definition at line 81 of file BOP_Splitter.cpp.
References BOP_classify(), BOP_createTAG(), BOP_Segment::createEdgeCfg(), BOP_Segment::createUndefinedCfg(), BOP_Segment::createVertexCfg(), BOP_Vertex::getPoint(), BOP_Face::getVertex(), BOP_Mesh::getVertex(), IN_IN_IN, IN_IN_ON, IN_IN_OUT, IN_ON_IN, IN_ON_ON, IN_ON_OUT, IN_OUT_IN, IN_OUT_ON, IN_OUT_OUT, BOP_Segment::m_cfg1, BOP_Segment::m_cfg2, BOP_Segment::m_v1, BOP_Segment::m_v2, ON_IN_IN, ON_IN_ON, ON_IN_OUT, ON_ON_IN, ON_ON_ON, ON_ON_OUT, ON_OUT_IN, ON_OUT_ON, ON_OUT_OUT, OUT_IN_IN, OUT_IN_ON, OUT_IN_OUT, OUT_ON_IN, OUT_ON_ON, OUT_ON_OUT, OUT_OUT_IN, OUT_OUT_ON, and OUT_OUT_OUT.
Referenced by BOP_intersectCoplanarFaces(), and BOP_intersectNonCoplanarFaces().