Blender: bpy_rna_callback.c File Reference
bpy_rna_callback.c File Reference
Python RNA and Operators
#include <Python.h>
#include "RNA_types.h"
#include "bpy_rna.h"
#include "bpy_rna_callback.h"
#include "bpy_util.h"
#include "BLI_utildefines.h"
#include "DNA_screen_types.h"
#include "RNA_access.h"
#include "BKE_context.h"
#include "ED_space_api.h"
Defines
#define RNA_CAPSULE_ID "RNA_HANDLE"
#define RNA_CAPSULE_ID_INVALID "RNA_HANDLE_REMOVED"
Functions
static void cb_region_draw (const bContext *C, ARegion *UNUSED(ar), void *customdata)
PyObject * pyrna_callback_add (BPy_StructRNA *self, PyObject *args)
PyObject * pyrna_callback_remove (BPy_StructRNA *self, PyObject *args)
Detailed Description
This file currently exposes callbacks for interface regions but may be extended later.
Definition in file bpy_rna_callback.c.
Define Documentation
#define RNA_CAPSULE_ID "RNA_HANDLE"
Definition at line 49 of file bpy_rna_callback.c.
Referenced by pyrna_callback_add(), and pyrna_callback_remove().
#define RNA_CAPSULE_ID_INVALID "RNA_HANDLE_REMOVED"
Definition at line 50 of file bpy_rna_callback.c.
Referenced by pyrna_callback_remove().
Function Documentation
static void cb_region_draw (const bContext * C, ARegion * UNUSEDar, void * customdata) [static]
Definition at line 52 of file bpy_rna_callback.c.
References bpy_context_clear(), and bpy_context_set().
Referenced by pyrna_callback_add().
PyObject* pyrna_callback_add (BPy_StructRNA * self, PyObject * args)
Definition at line 74 of file bpy_rna_callback.c.
References cb_region_draw(), ED_region_draw_cb_activate(), NULL, pyrna_enum_value_from_id(), REGION_DRAW_POST_PIXEL, REGION_DRAW_POST_VIEW, REGION_DRAW_PRE_VIEW, RNA_CAPSULE_ID, RNA_Region, and RNA_struct_is_a().
PyObject* pyrna_callback_remove (BPy_StructRNA * self, PyObject * args)
Definition at line 117 of file bpy_rna_callback.c.
References ED_region_draw_cb_customdata(), ED_region_draw_cb_exit(), NULL, RNA_CAPSULE_ID, RNA_CAPSULE_ID_INVALID, RNA_Region, and RNA_struct_is_a().