Blender: SG_QList::iterator< T > Class Template Reference
SG_QList::iterator< T > Class Template Reference
#include <SG_QList.h>
Public Types
typedef iterator< T > _myT
Public Member Functions
iterator (SG_QList &head, SG_QList *current=NULL)
~iterator ()
void begin ()
void back ()
bool end ()
bool add_back (T *item)
T * operator* ()
_myT & operator++ ()
_myT & operator-- ()
Detailed Description
template<typename T>
class SG_QList::iterator< T >
Definition at line 48 of file SG_QList.h.
Member Typedef Documentation
template<typename T> typedef iterator<T> SG_QList::iterator< T >::_myT
Definition at line 54 of file SG_QList.h.
Constructor & Destructor Documentation
template<typename T> SG_QList::iterator< T >::iterator (SG_QList & head, SG_QList * current = NULL) [inline]
Definition at line 55 of file SG_QList.h.
References T.
template<typename T> SG_QList::iterator< T >::~iterator () [inline]
Definition at line 56 of file SG_QList.h.
Member Function Documentation
template<typename T> bool SG_QList::iterator< T >::add_back (T * item) [inline]
Definition at line 70 of file SG_QList.h.
Referenced by SCA_ILogicBrick::InsertActiveQList(), and SCA_ILogicBrick::InsertSelfActiveQList().
template<typename T> void SG_QList::iterator< T >::back () [inline]
Definition at line 62 of file SG_QList.h.
References SG_QList::QBack(), and T.
template<typename T> void SG_QList::iterator< T >::begin () [inline]
Definition at line 58 of file SG_QList.h.
References SG_QList::QPeek(), and T.
Referenced by KX_GameObject::AddMeshUser(), SCA_ILogicBrick::InsertActiveQList(), BL_DeformableGameObject::SetDeformer(), KX_GameObject::UpdateBuckets(), and SCA_LogicManager::UpdateFrame().
template<typename T> bool SG_QList::iterator< T >::end () [inline]
Definition at line 66 of file SG_QList.h.
References SG_DList::Self(), and T.
Referenced by KX_GameObject::AddMeshUser(), SCA_ILogicBrick::InsertActiveQList(), SCA_ILogicBrick::InsertSelfActiveQList(), BL_DeformableGameObject::SetDeformer(), KX_GameObject::UpdateBuckets(), and SCA_LogicManager::UpdateFrame().
template<typename T> T* SG_QList::iterator< T >::operator* () [inline]
Definition at line 74 of file SG_QList.h.
template<typename T> _myT& SG_QList::iterator< T >::operator++ () [inline]
Definition at line 78 of file SG_QList.h.
References T.
template<typename T> _myT& SG_QList::iterator< T >::operator-- () [inline]
Definition at line 83 of file SG_QList.h.
References T.
The documentation for this class was generated from the following file:
SG_QList.h