Blender: rna_lattice.c File Reference
rna_lattice.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_curve_types.h"
#include "DNA_key_types.h"
#include "DNA_lattice_types.h"
#include "DNA_meshdata_types.h"
Functions
static void rna_def_latticepoint (BlenderRNA *brna)
static void rna_def_lattice (BlenderRNA *brna)
void RNA_def_lattice (BlenderRNA *brna)
Detailed Description
Definition in file rna_lattice.c.
Function Documentation
static void rna_def_lattice (BlenderRNA * brna) [static]
Definition at line 246 of file rna_lattice.c.
References KEY_BSPLINE, KEY_CARDINAL, KEY_LINEAR, LT_OUTSIDE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_ENUM, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, rna_def_animdata_common(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_editable_func(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lattice().
void RNA_def_lattice (BlenderRNA * brna)
Definition at line 329 of file rna_lattice.c.
References rna_def_lattice(), and rna_def_latticepoint().
static void rna_def_latticepoint (BlenderRNA * brna) [static]
Definition at line 216 of file rna_lattice.c.
References NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_array(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_lattice().