Blender: area.c File Reference
area.c File Reference
screen
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "DNA_userdef_types.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm_subwindow.h"
#include "ED_screen.h"
#include "ED_screen_types.h"
#include "ED_space_api.h"
#include "ED_types.h"
#include "ED_fileselect.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "BLF_api.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "screen_intern.h"
Defines
#define AZONEPAD_EDGE 4
#define AZONEPAD_ICON 9
#define AZONEPAD_TAB_PLUSW 14
#define AZONEPAD_TAB_PLUSH 14
#define AZONEPAD_TABW 18
#define AZONEPAD_TABH 7
#define AZONEPAD_TRIAW 16
#define AZONEPAD_TRIAH 9
Functions
static void region_draw_emboss (ARegion *ar, rcti *scirct)
void ED_region_pixelspace (ARegion *ar)
void ED_region_do_listen (ARegion *ar, wmNotifier *note)
void ED_area_do_listen (ScrArea *sa, wmNotifier *note)
void ED_area_do_refresh (bContext *C, ScrArea *sa)
void ED_area_overdraw_flush (ScrArea *sa, ARegion *ar)
static void area_draw_azone (short x1, short y1, short x2, short y2)
static void region_draw_azone_icon (AZone *az)
static void draw_azone_plus (float x1, float y1, float x2, float y2)
static void region_draw_azone_tab_plus (AZone *az)
static void region_draw_azone_tab (AZone *az)
static void region_draw_azone_tria (AZone *az)
void ED_area_overdraw (bContext *C)
void region_scissor_winrct (ARegion *ar, rcti *winrct)
void ED_region_set (const bContext *C, ARegion *ar)
void ED_region_do_draw (bContext *C, ARegion *ar)
void ED_region_tag_redraw (ARegion *ar)
void ED_region_tag_redraw_overlay (ARegion *ar)
void ED_region_tag_redraw_partial (ARegion *ar, rcti *rct)
void ED_area_tag_redraw (ScrArea *sa)
void ED_area_tag_redraw_regiontype (ScrArea *sa, int regiontype)
void ED_area_tag_refresh (ScrArea *sa)
void ED_area_headerprint (ScrArea *sa, const char *str)
static void area_azone_initialize (ScrArea *sa)
static void region_azone_edge (AZone *az, ARegion *ar)
static void region_azone_icon (ScrArea *sa, AZone *az, ARegion *ar)
static void region_azone_tab_plus (ScrArea *sa, AZone *az, ARegion *ar)
static void region_azone_tab (ScrArea *sa, AZone *az, ARegion *ar)
static void region_azone_tria (ScrArea *sa, AZone *az, ARegion *ar)
static void region_azone_initialize (ScrArea *sa, ARegion *ar, AZEdge edge)
static void region_azone_add (ScrArea *sa, ARegion *ar, int alignment)
static int rct_fits (rcti *rect, char dir, int size)
static void region_rect_recursive (ScrArea *sa, ARegion *ar, rcti *remainder, int quad)
static void area_calc_totrct (ScrArea *sa, int sizex, int sizey)
static void region_subwindow (wmWindow *win, ARegion *ar)
static void ed_default_handlers (wmWindowManager *wm, ScrArea *sa, ListBase *handlers, int flag)
void ED_area_initialize (wmWindowManager *wm, wmWindow *win, ScrArea *sa)
void ED_region_init (bContext *C, ARegion *ar)
void ED_region_toggle_hidden (bContext *C, ARegion *ar)
void area_copy_data (ScrArea *sa1, ScrArea *sa2, int swap_space)
void ED_area_swapspace (bContext *C, ScrArea *sa1, ScrArea *sa2)
void ED_area_newspace (bContext *C, ScrArea *sa, int type)
void ED_area_prevspace (bContext *C, ScrArea *sa)
static const char * editortype_pup (void)
static void spacefunc (struct bContext *C, void *UNUSED(arg1), void *UNUSED(arg2))
int ED_area_header_switchbutton (const bContext *C, uiBlock *block, int yco)
int ED_area_header_standardbuttons (const bContext *C, uiBlock *block, int yco)
void ED_region_panels (const bContext *C, ARegion *ar, int vertical, const char *context, int contextnr)
void ED_region_panels_init (wmWindowManager *wm, ARegion *ar)
void ED_region_header (const bContext *C, ARegion *ar)
void ED_region_header_init (ARegion *ar)
int ED_area_headersize (void)
void ED_region_info_draw (ARegion *ar, const char *text, int block, float alpha)
Detailed Description
Definition in file area.c.
Define Documentation
#define AZONEPAD_EDGE 4
Definition at line 622 of file area.c.
Referenced by region_azone_edge().
#define AZONEPAD_ICON 9
Definition at line 623 of file area.c.
Referenced by region_azone_icon().
#define AZONEPAD_TAB_PLUSH 14
Definition at line 716 of file area.c.
Referenced by region_azone_tab_plus().
#define AZONEPAD_TAB_PLUSW 14
Definition at line 715 of file area.c.
Referenced by region_azone_tab_plus().
#define AZONEPAD_TABH 7
Definition at line 761 of file area.c.
Referenced by region_azone_tab().
#define AZONEPAD_TABW 18
Definition at line 760 of file area.c.
Referenced by region_azone_tab().
#define AZONEPAD_TRIAH 9
Definition at line 805 of file area.c.
Referenced by region_azone_tria().
#define AZONEPAD_TRIAW 16
Definition at line 804 of file area.c.
Referenced by region_azone_tria().
Function Documentation
static void area_azone_initialize (ScrArea * sa) [static]
Definition at line 595 of file area.c.
References ScrArea::actionzones, AZONE_AREA, AZONESPOT, BLI_addtail(), BLI_freelistN(), BLI_init_rcti(), MEM_callocN(), AZone::rect, ScrArea::totrct, AZone::type, AZone::x1, AZone::x2, rcti::xmax, rcti::xmin, AZone::y1, AZone::y2, rcti::ymax, and rcti::ymin.
Referenced by ED_area_initialize().
static void area_calc_totrct (ScrArea * sa, int sizex, int sizey) [static]
Definition at line 1114 of file area.c.
References ScrArea::totrct, ScrArea::v1, ScrArea::v2, ScrArea::v4, ScrVert::vec, ScrArea::winx, ScrArea::winy, vec2s::x, rcti::xmax, rcti::xmin, vec2s::y, rcti::ymax, and rcti::ymin.
Referenced by ED_area_initialize().
void area_copy_data (ScrArea * sa1, ScrArea * sa2, int swap_space)
Definition at line 1287 of file area.c.
References BKE_area_region_copy(), BKE_area_region_free(), BKE_spacedata_copylist(), BKE_spacedata_freelist(), BKE_spacetype_from_id(), BLI_addtail(), BLI_freelistN(), ScrArea::butspacetype, ListBase::first, ScrArea::headertype, ARegion::next, ScrArea::regionbase, ScrArea::spacedata, ScrArea::spacetype, and SWAP.
Referenced by area_dupli_invoke(), area_split(), ED_area_swapspace(), ED_screen_full_toggle(), and screen_copy().
static void area_draw_azone (short x1, short y1, short x2, short y2) [static]
Definition at line 170 of file area.c.
References fabs(), and fdrawline().
Referenced by ED_area_overdraw().
static void draw_azone_plus (float x1, float y1, float x2, float y2) [static]
Definition at line 233 of file area.c.
Referenced by region_draw_azone_tab_plus().
void ED_area_do_listen (ScrArea * sa, wmNotifier * note)
Definition at line 133 of file area.c.
References SpaceType::listener, and ScrArea::type.
Referenced by wm_event_do_notifiers().
void ED_area_do_refresh (bContext * C, ScrArea * sa)
Definition at line 142 of file area.c.
References ScrArea::do_refresh, SpaceType::refresh, and ScrArea::type.
Referenced by wm_event_do_notifiers().
int ED_area_header_standardbuttons (const bContext * C, uiBlock * block, int yco)
Definition at line 1520 of file area.c.
References CTX_wm_area(), ED_area_header_switchbutton(), ScrArea::flag, ScrArea::full, HEADER_NO_PULLDOWN, TOG, UI_BUT_UNDO, UI_EMBOSS, UI_EMBOSSN, UI_UNIT_X, UI_UNIT_Y, uiBlockSetEmboss(), uiButClearFlag(), and uiDefIconButBitS().
int ED_area_header_switchbutton (const bContext * C, uiBlock * block, int yco)
Definition at line 1504 of file area.c.
References ScrArea::butspacetype, CTX_wm_area(), editortype_pup(), ICONTEXTROW, NULL, spacefunc(), SPACEICONMAX, TIP_, UI_BUT_UNDO, UI_UNIT_X, UI_UNIT_Y, uiButClearFlag(), uiButSetFunc(), and uiDefIconTextButC().
void ED_area_headerprint (ScrArea * sa, const char * str)
Definition at line 568 of file area.c.
References BLI_strncpy(), ED_region_tag_redraw(), ListBase::first, ARegion::headerstr, MEM_freeN(), MEM_mallocN(), ARegion::next, NULL, ScrArea::regionbase, ARegion::regiontype, and RGN_TYPE_HEADER.
Referenced by Align(), BakeTime(), Bevel(), BevelWeight(), BoneEnvelope(), BoneRoll(), BoneSize(), Crease(), CurveShrinkFatten(), ed_marker_move_exit(), ed_marker_move_modal(), ED_screen_full_toggle(), edbm_vertex_slide_modal(), EdgeSlide(), gpencil_draw_status_indicators(), knife_update_header(), knifetool_modal(), loopcut_modal(), minimize_stretch_exit(), minimize_stretch_iteration(), Mirror(), pose_slide_draw_status(), pose_slide_modal(), poselib_preview_apply(), poselib_preview_cleanup(), PushPull(), Resize(), ringcut_invoke(), Rotation(), SeqSlide(), Shear(), ShrinkFatten(), stitch_exit(), stitch_update_header(), Tilt(), TimeScale(), TimeSlide(), TimeTranslate(), ToSphere(), Trackball(), Translation(), viewRedrawPost(), vtx_slide_exit(), vtx_slide_init(), and Warp().
int ED_area_headersize (void)
Definition at line 1777 of file area.c.
References UI_UNIT_Y.
Referenced by area_move_apply_do(), area_move_set_limits(), area_split_init(), ED_region_header(), screen_refresh_headersizes(), and screen_test_scale().
void ED_area_initialize (wmWindowManager * wm, wmWindow * win, ScrArea * sa)
Definition at line 1202 of file area.c.
References area_azone_initialize(), area_calc_totrct(), BKE_regiontype_from_id(), BKE_spacetype_from_id(), ScrArea::butspacetype, ed_default_handlers(), ListBase::first, View2D::flag, ARegion::handlers, ScrArea::handlers, ARegionType::init, SpaceType::init, SpaceType::keymapflag, ARegionType::keymapflag, ARegion::next, NULL, region_rect_recursive(), region_subwindow(), ScrArea::regionbase, ARegion::regiontype, RGN_TYPE_HEADER, wmWindow::sizex, wmWindow::sizey, SPACE_VIEW3D, ScrArea::spacetype, ARegion::swinid, ScrArea::totrct, ScrArea::type, ARegion::type, ARegion::uiblocks, uiFreeBlocks(), ARegion::v2d, and V2D_IS_INITIALISED.
Referenced by clip_refresh(), ED_area_newspace(), ED_area_swapspace(), ED_region_toggle_hidden(), ED_screen_refresh(), and sequencer_refresh().
void ED_area_newspace (bContext * C, ScrArea * sa, int type)
Definition at line 1360 of file area.c.
References BKE_spacetype_from_id(), BLI_addhead(), BLI_freelinkN(), BLI_remlink(), ScrArea::butspacetype, CTX_wm_manager(), CTX_wm_window(), ED_area_exit(), ED_area_initialize(), ED_area_tag_redraw(), ED_area_tag_refresh(), ListBase::first, SpaceType::free, ListBase::last, NC_SPACE, ND_SPACE_CHANGED, SpaceType::new, SpaceLink::next, NULL, ScrArea::regionbase, SpaceLink::regionbase, ScrArea::spacedata, SpaceLink::spacetype, ScrArea::spacetype, ScrArea::type, WM_event_add_mousemove(), and WM_event_add_notifier().
Referenced by ED_area_prevspace(), ED_screen_full_newspace(), ED_screen_full_toggle(), render_view_open(), render_view_show_invoke(), spacefunc(), wm_handler_fileselect_call(), and WM_window_open_temp().
void ED_area_overdraw (bContext * C)
Definition at line 351 of file area.c.
References ScrArea::actionzones, AZone::ar, area_draw_azone(), bScreen::areabase, AZONE_AREA, AZONE_REGION, CTX_wm_screen(), CTX_wm_window(), AZone::do_draw, ListBase::first, ARegion::flag, G, bScreen::mainwin, ScrArea::next, AZone::next, region_draw_azone_icon(), region_draw_azone_tab(), region_draw_azone_tab_plus(), region_draw_azone_tria(), RGN_FLAG_HIDDEN, RGN_FLAG_TOO_SMALL, AZone::type, wmSubWindowSet(), AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
void ED_area_overdraw_flush (ScrArea * sa, ARegion * ar)
Definition at line 153 of file area.c.
References ScrArea::actionzones, BLI_in_rcti(), AZone::do_draw, ListBase::first, AZone::next, ARegion::winrct, AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
void ED_area_prevspace (bContext * C, ScrArea * sa)
Definition at line 1431 of file area.c.
References CTX_wm_space_data(), ED_area_newspace(), ED_area_tag_redraw(), ListBase::first, NC_SPACE, ND_SPACE_CHANGED, SpaceLink::next, SPACE_FILE, SPACE_INFO, ScrArea::spacedata, SpaceLink::spacetype, and WM_event_add_notifier().
Referenced by ED_screen_full_prevspace(), render_view_cancel_exec(), and wm_handler_fileselect_call().
void ED_area_swapspace (bContext * C, ScrArea * sa1, ScrArea * sa2)
Definition at line 1335 of file area.c.
References area_copy_data(), BKE_screen_area_free(), CTX_wm_manager(), CTX_wm_window(), ED_area_exit(), ED_area_initialize(), ED_area_tag_redraw(), ED_area_tag_refresh(), MEM_callocN(), MEM_freeN(), and WM_event_add_mousemove().
Referenced by area_swap_modal().
void ED_area_tag_redraw (ScrArea * sa)
Definition at line 537 of file area.c.
References ED_region_tag_redraw(), ListBase::first, ARegion::next, and ScrArea::regionbase.
Referenced by action_listener(), action_refresh(), actkeys_viewall(), area_dupli_invoke(), area_join_modal(), area_move_apply_do(), area_split_apply(), area_split_exit(), area_split_modal(), area_swap_modal(), BIF_sk_selectStroke(), bookmark_add_exec(), bookmark_delete_exec(), borderselect_exec(), buttons_area_listener(), buttons_area_redraw(), clip_listener(), clip_rebuild_proxy_exec(), clip_refresh(), console_clear_exec(), console_delete_exec(), console_history_append_exec(), console_history_cycle_exec(), console_insert_exec(), console_modal_select_apply(), console_move_exec(), console_paste_exec(), console_scrollback_append_exec(), do_buttons_buttons(), do_view3d_header_buttons(), do_view3d_region_buttons(), ED_area_newspace(), ED_area_prevspace(), ED_area_swapspace(), ED_region_toggle_hidden(), ED_view3d_quadview_update(), file_draw_check_cb(), file_filenum_exec(), file_highlight_invoke(), file_listener(), file_rename_exec(), file_select_all_exec(), game_engine_exec(), graph_listener(), graphkeys_clear_ghostcurves_exec(), graphkeys_create_ghostcurves_exec(), graphkeys_viewall(), header_flip_exec(), image_listener(), image_record_composite_apply(), image_sample_apply(), image_sample_exit(), image_sample_line_exec(), localview_exec(), nla_listener(), nlaedit_viewall(), node_area_listener(), pin_cb(), previewrange_clear_exec(), redraw_timer_window_swap(), region_flip_exec(), region_quadview_exec(), region_scale_modal(), render_view_show_invoke(), report_delete_exec(), report_replay_exec(), report_select_all_toggle_exec(), sample_apply(), sample_exit(), select_report_pick_exec(), seq_proxy_build_job(), sequencer_refresh(), sequencer_view_all_exec(), sequencer_view_all_preview_exec(), sequencer_view_selected_exec(), set_clone_cursor_exec(), sketch_cancel(), sketch_convert(), sketch_draw_modal(), sketch_draw_preview(), sketch_finish(), sketch_select(), spacefunc(), template_texture_show(), text_listener(), text_scroll_apply(), text_scroll_exec(), text_scroll_modal(), time_listener(), view3d_layers_exec(), viewRedrawForce(), and wm_gesture_end().
void ED_area_tag_redraw_regiontype (ScrArea * sa, int regiontype)
Definition at line 546 of file area.c.
References ED_region_tag_redraw(), ListBase::first, ARegion::next, ScrArea::regionbase, and ARegion::regiontype.
Referenced by space_view3d_listener().
void ED_area_tag_refresh (ScrArea * sa)
Definition at line 559 of file area.c.
References ScrArea::do_refresh.
Referenced by action_listener(), ED_area_newspace(), ED_area_swapspace(), file_listener(), graph_init(), graph_listener(), image_listener(), nla_init(), nla_listener(), node_area_listener(), screen_animation_step(), sequencer_view_toggle_exec(), and time_listener().
static void ed_default_handlers (wmWindowManager * wm, ScrArea * sa, ListBase * handlers, int flag) [static]
Definition at line 1148 of file area.c.
References BKE_area_find_region_type(), wmWindowManager::defaultconf, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_GPENCIL, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, RGN_TYPE_WINDOW, SPACE_TIME, ScrArea::spacetype, UI_add_region_handlers(), ARegion::winrct, WM_event_add_keymap_handler(), WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_area_initialize().
void ED_region_do_draw (bContext * C, ARegion * ar)
Definition at line 443 of file area.c.
References BLF_draw_default(), BLF_DRAW_STR_DUMMY_MAX, CTX_wm_area(), CTX_wm_window(), ARegion::do_draw, ARegionType::do_lock, ARegionType::draw, ARegion::drawrct, ED_region_draw_cb_draw(), ED_region_pixelspace(), ARegion::headerstr, MAX2, MIN2, region_draw_emboss(), REGION_DRAW_POST_PIXEL, region_scissor_winrct(), ARegionType::regionid, ScrArea::spacetype, ARegion::swinid, TH_HEADER, TH_TEXT, ARegion::type, UI_SetTheme(), UI_ThemeClearColor(), UI_ThemeColor(), ARegion::uiblocks, uiFreeInactiveBlocks(), wmSubWindowScissorSet(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by redraw_timer_exec(), wm_method_draw_full(), wm_method_draw_overlap_all(), and wm_method_draw_triple().
void ED_region_do_listen (ARegion * ar, wmNotifier * note)
Definition at line 115 of file area.c.
References wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), ARegionType::listener, NC_WINDOW, NC_WM, ND_FILEREAD, and ARegion::type.
Referenced by wm_event_do_notifiers().
void ED_region_header (const bContext * C, ARegion * ar)
Definition at line 1718 of file area.c.
References HeaderType::draw, ED_area_headersize(), ED_screen_area_active(), ListBase::first, ARegionType::headertypes, HeaderType::idname, Header::layout, HeaderType::next, NULL, TH_HEADER, TH_HEADERDESEL, View2D::tot, Header::type, ARegion::type, UI_EMBOSS, UI_GetStyle(), UI_LAYOUT_HEADER, UI_LAYOUT_HORIZONTAL, UI_ThemeClearColor(), UI_UNIT_X, UI_UNIT_Y, UI_view2d_totRect_set(), UI_view2d_view_ortho(), UI_view2d_view_restore(), uiBeginBlock(), uiBlockLayout(), uiBlockLayoutResolve(), uiDrawBlock(), uiEndBlock(), uiLayoutGetWidth(), ARegion::v2d, rctf::ymax, and rctf::ymin.
void ED_region_header_init (ARegion * ar)
Definition at line 1771 of file area.c.
References UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_HEADER, ARegion::winx, and ARegion::winy.
Referenced by action_header_area_init(), clip_header_area_init(), console_header_area_init(), file_header_area_init(), graph_header_area_init(), image_header_area_init(), info_header_area_init(), logic_header_area_init(), nla_header_area_init(), node_header_area_init(), outliner_header_area_init(), script_header_area_init(), sequencer_header_area_init(), text_header_area_init(), time_header_area_init(), userpref_header_area_init(), and view3d_header_area_init().
void ED_region_info_draw (ARegion * ar, const char * text, int block, float alpha)
Definition at line 1782 of file area.c.
References BLF_draw(), BLF_DRAW_STR_DUMMY_MAX, BLF_position(), BLF_size(), BLF_width(), TH_TEXT_HI, UI_GetStyle(), UI_ThemeColor(), uiFontStyle::uifont_id, uiStyle::widget, ARegion::winrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_movieclip_notes(), draw_render_info(), and view3d_main_area_draw_engine_info().
void ED_region_init (bContext * C, ARegion * ar)
Definition at line 1257 of file area.c.
References CTX_wm_window(), region_subwindow(), ARegion::winrct, ARegion::winx, ARegion::winy, wmOrtho2(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_popup_block_create(), ui_searchbox_create(), and ui_tooltip_create().
void ED_region_panels (const bContext * C, ARegion * ar, int vertical, const char * context, int contextnr)
Definition at line 1555 of file area.c.
References PanelType::context, CTX_wm_area(), View2D::cur, PanelType::draw, PanelType::draw_header, ListBase::first, PanelType::flag, PanelType::idname, View2D::keepofs, Panel::labelofs, Panel::layout, MAX2, PanelType::next, NULL, uiStyle::panelspace, ARegionType::paneltypes, PNL_NO_HEADER, PanelType::poll, ARegionType::prefsizex, ARegionType::regionid, ARegion::regiontype, RGN_TYPE_PREVIEW, RGN_TYPE_TOOLS, View2D::scroll, TH_BACK, TH_PREVIEW_BACK, ARegion::type, UI_EMBOSS, UI_GetStyle(), UI_LAYOUT_HEADER, UI_LAYOUT_HORIZONTAL, UI_LAYOUT_PANEL, UI_LAYOUT_TOOLBAR, UI_LAYOUT_VERTICAL, UI_PANEL_WIDTH, UI_ThemeClearColor(), UI_UNIT_Y, UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_tab_set(), UI_view2d_totRect_set(), UI_view2d_view_ortho(), UI_view2d_view_restore(), uiBeginBlock(), uiBeginPanel(), uiBeginPanels(), uiBlockLayout(), uiBlockLayoutResolve(), uiDrawPanels(), uiEndBlock(), uiEndPanel(), uiEndPanels(), ARegion::v2d, V2D_ARG_DUMMY, V2D_KEEPOFS_X, V2D_KEEPOFS_Y, V2D_LOCKOFS_X, V2D_LOCKOFS_Y, V2D_SCROLL_HEIGHT, V2D_SCROLL_HORIZONTAL_HIDE, V2D_SCROLL_VERTICAL_HIDE, V2D_SCROLL_WIDTH, rctf::xmax, rctf::xmin, and rctf::ymin.
void ED_region_panels_init (wmWindowManager * wm, ARegion * ar)
Definition at line 1697 of file area.c.
References View2D::align, wmWindowManager::defaultconf, View2D::flag, ARegion::handlers, View2D::keepzoom, View2D::scroll, UI_view2d_region_reinit(), ARegion::v2d, V2D_ALIGN_NO_POS_Y, V2D_COMMONVIEW_PANELS_UI, V2D_IS_INITIALISED, V2D_KEEPZOOM, V2D_SCROLL_BOTTOM, V2D_SCROLL_HORIZONTAL_HIDE, V2D_SCROLL_RIGHT, V2D_SCROLL_VERTICAL_HIDE, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by buttons_main_area_init(), clip_properties_area_init(), clip_tools_area_init(), file_channel_area_init(), graph_buttons_area_init(), image_buttons_area_init(), image_scope_area_init(), logic_buttons_area_init(), nla_buttons_area_init(), node_buttons_area_init(), sequencer_buttons_area_init(), text_properties_area_init(), userpref_main_area_init(), view3d_buttons_area_init(), and view3d_tools_area_init().
void ED_region_pixelspace (ARegion * ar)
Definition at line 105 of file area.c.
References ARegion::winrct, wmOrtho2(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by draw_bgpic(), ED_region_do_draw(), ED_region_set(), ED_view3d_draw_offscreen(), EDBM_backbuf_border_mask_init(), UI_view2d_text_cache_draw(), view3d_cached_text_draw_end(), view3d_main_area_draw(), view3d_main_area_draw_engine(), and view3d_main_area_draw_objects().
void ED_region_set (const bContext * C, ARegion * ar)
Definition at line 422 of file area.c.
References CTX_wm_area(), CTX_wm_window(), ARegion::drawrct, ED_region_pixelspace(), region_scissor_winrct(), ARegionType::regionid, ScrArea::spacetype, ARegion::swinid, ARegion::type, UI_SetTheme(), and wmSubWindowScissorSet().
void ED_region_tag_redraw (ARegion * ar)
Definition at line 504 of file area.c.
References ARegion::do_draw, ARegion::drawrct, and RGN_DRAW.
Referenced by action_channel_area_listener(), action_header_area_listener(), action_main_area_listener(), axis_set_view(), backimage_zoom(), button_activate_exit(), button_activate_state(), center_current_frame_exec(), clip_main_area_listener(), clip_properties_area_listener(), clip_props_area_listener(), console_main_area_listener(), curvemap_buttons_redraw(), curvemap_buttons_zoom_in(), curvemap_buttons_zoom_out(), curvemap_tools_dofunc(), do_item_rename(), do_outliner_operation_event(), ED_area_headerprint(), ED_area_tag_redraw(), ED_area_tag_redraw_regiontype(), ED_region_do_listen(), ED_screen_set_subwinactive(), edbm_vertex_slide_modal(), face_select_all_exec(), face_select_hide_exec(), face_select_inverse_exec(), face_select_reveal_exec(), file_main_area_listener(), file_smoothscroll_invoke(), file_ui_area_listener(), fly_modal(), gpencil_draw_apply_event(), grab_clone_apply(), graph_region_listener(), hide_show_exec(), image_buttons_area_listener(), image_header_area_listener(), image_main_area_listener(), image_scope_area_listener(), image_view_all_exec(), image_view_ndof_invoke(), image_view_pan_exec(), image_view_pan_exit(), image_view_selected_exec(), image_view_zoom_exec(), image_view_zoom_exit(), image_view_zoom_in_exec(), image_view_zoom_invoke(), image_view_zoom_modal(), image_view_zoom_out_exec(), image_view_zoom_ratio_exec(), info_header_listener(), info_main_area_listener(), keymap_type_cb(), knifetool_exit(), knifetool_init(), knifetool_modal(), knifetool_update_mval(), logic_listener(), loopcut_modal(), ndof_orbit_invoke(), ndof_pan_invoke(), nla_channel_area_listener(), nla_main_area_listener(), nla_region_listener(), node_link_modal(), node_region_listener(), node_resize_modal(), node_view_all_exec(), outliner_border_select_exec(), outliner_header_area_listener(), outliner_item_activate(), outliner_item_openclose(), outliner_main_area_listener(), outliner_one_level_exec(), outliner_scroll_page_exec(), outliner_show_active_exec(), outliner_show_hierarchy_exec(), outliner_toggle_expanded_exec(), outliner_toggle_selectability_exec(), outliner_toggle_selected_exec(), outliner_toggle_visibility_exec(), paint_redraw(), paint_select_linked_exec(), paint_select_linked_pick_invoke(), paintface_mouse_select(), panel_activate_state(), radial_control_modal(), redraw_timer_exec(), rename_anim_channels(), renamebutton_cb(), reset_exec(), ringsel_exit(), ringsel_init(), run_pyfile_exec(), sclip_zoom_set_factor_exec(), screen_animation_step(), scroller_activate_apply(), scroller_activate_exit(), scroller_activate_init(), sculpt_flush_update(), sequencer_buttons_area_listener(), sequencer_main_area_listener(), sequencer_preview_area_listener(), sequencer_view_zoom_ratio_exec(), smooth_view(), snode_bg_viewmove_modal(), stitch_modal(), time_header_area_listener(), time_main_area_listener(), time_view_all_exec(), ui_do_animate(), ui_do_but_HOTKEYEVT(), ui_do_but_textedit(), ui_do_but_textedit_select(), ui_do_button(), ui_do_drag(), ui_handle_button_event(), ui_handle_list_event(), ui_handle_panel_header(), ui_handler_panel_region(), ui_menu_scroll(), ui_numedit_apply(), ui_popup_block_create(), ui_searchbox_create(), ui_searchbox_select(), ui_searchbox_update(), ui_tooltip_create(), UI_view2d_sync(), uiContextAnimUpdate(), uiEndPanels(), uv_sculpt_stroke_modal(), vert_select_all_exec(), vert_select_inverse_exec(), vertex_color_set_exec(), view3d_all_exec(), view3d_boxview_copy(), view3d_boxview_sync(), view3d_buttons_area_listener(), view3d_clipping_invoke(), view3d_header_area_listener(), view3d_main_area_draw_objects(), view3d_main_area_listener(), view3d_props_area_listener(), view_all_exec(), view_borderzoom_exec(), view_pan_apply(), view_pan_exec(), view_pan_exit(), view_selected_exec(), view_zoom_exec(), view_zoom_exit(), view_zoom_in_exec(), view_zoom_modal(), view_zoom_out_exec(), view_zoom_ratio_exec(), view_zoomdrag_apply(), view_zoomstep_apply(), viewdolly_apply(), viewdolly_exec(), viewmove_apply(), viewops_data_free(), viewpan_exec(), viewpersportho_exec(), viewrotate_apply(), viewrotate_invoke(), viewzoom_apply(), viewzoom_exec(), vpaint_stroke_update_step(), vtx_slide_confirm(), vtx_slide_init(), weight_paint_set_exec(), wm_method_draw_overlap_all(), wm_tag_redraw_overlay(), and wpaint_stroke_update_step().
void ED_region_tag_redraw_overlay (ARegion * ar)
Definition at line 513 of file area.c.
References ARegion::do_draw_overlay, and RGN_DRAW.
Referenced by view3d_main_area_listener().
void ED_region_tag_redraw_partial (ARegion * ar, rcti * rct)
Definition at line 519 of file area.c.
References ARegion::do_draw, ARegion::drawrct, MAX2, MIN2, RGN_DRAW_PARTIAL, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by sculpt_flush_update().
void ED_region_toggle_hidden (bContext * C, ARegion * ar)
Definition at line 1272 of file area.c.
References CTX_wm_area(), CTX_wm_manager(), CTX_wm_window(), ED_area_initialize(), ED_area_tag_redraw(), ARegion::flag, ARegion::handlers, RGN_FLAG_HIDDEN, and WM_event_remove_handlers().
Referenced by file_bookmark_toggle_exec(), graph_properties(), image_properties(), image_scopes(), logic_properties(), nla_properties(), node_properties(), properties_exec(), region_scale_toggle_hidden(), sequencer_properties(), text_properties_exec(), tools_exec(), view3d_properties(), view3d_toolshelf(), and WM_init_game().
static const char* editortype_pup (void) [static]
Definition at line 1452 of file area.c.
References IFACE_, N_, and types.
Referenced by ED_area_header_switchbutton().
static int rct_fits (rcti * rect, char dir, int size) [static]
Definition at line 894 of file area.c.
References size(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by region_rect_recursive().
static void region_azone_add (ScrArea * sa, ARegion * ar, int alignment) [static]
Definition at line 879 of file area.c.
References AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, ELEM, region_azone_initialize(), RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_ALIGN_TOP, RGN_OVERLAP_LEFT, and RGN_OVERLAP_RIGHT.
Referenced by region_rect_recursive().
static void region_azone_edge (AZone * az, ARegion * ar) [static]
Definition at line 624 of file area.c.
References AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, AZONEPAD_EDGE, BLI_init_rcti(), AZone::edge, AZone::rect, ARegion::winrct, AZone::x1, AZone::x2, rcti::xmax, rcti::xmin, AZone::y1, AZone::y2, rcti::ymax, and rcti::ymin.
Referenced by region_azone_initialize().
static void region_azone_icon (ScrArea * sa, AZone * az, ARegion * ar) [static]
Definition at line 656 of file area.c.
References ABS, ScrArea::actionzones, AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, AZONEPAD_ICON, AZONESPOT, BLI_init_rcti(), AZone::edge, ListBase::first, AZone::next, AZone::rect, ARegion::winrct, AZone::x1, AZone::x2, rcti::xmax, rcti::xmin, AZone::y1, AZone::y2, rcti::ymax, and rcti::ymin.
Referenced by region_azone_initialize().
static void region_azone_initialize (ScrArea * sa, ARegion * ar, AZEdge edge) [static]
Definition at line 850 of file area.c.
References ScrArea::actionzones, AZone::ar, AZONE_REGION, BLI_addtail(), AZone::edge, ARegion::flag, G, MEM_callocN(), region_azone_edge(), region_azone_icon(), region_azone_tab(), region_azone_tab_plus(), region_azone_tria(), RGN_FLAG_HIDDEN, RGN_FLAG_TOO_SMALL, and AZone::type.
Referenced by region_azone_add().
static void region_azone_tab (ScrArea * sa, AZone * az, ARegion * ar) [static]
Definition at line 764 of file area.c.
References ScrArea::actionzones, add(), AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, AZONEPAD_TABH, AZONEPAD_TABW, BLI_init_rcti(), AZone::edge, ListBase::first, AZone::next, AZone::rect, ScrArea::totrct, ARegion::winrct, AZone::x1, AZone::x2, rcti::xmax, rcti::xmin, AZone::y1, AZone::y2, rcti::ymax, and rcti::ymin.
Referenced by region_azone_initialize().
static void region_azone_tab_plus (ScrArea * sa, AZone * az, ARegion * ar) [static]
Definition at line 719 of file area.c.
References ScrArea::actionzones, add(), AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, AZONEPAD_TAB_PLUSH, AZONEPAD_TAB_PLUSW, BLI_init_rcti(), AZone::edge, ListBase::first, AZone::next, AZone::rect, ScrArea::totrct, ARegion::winrct, AZone::x1, AZone::x2, rcti::xmax, rcti::xmin, AZone::y1, AZone::y2, rcti::ymax, and rcti::ymin.
Referenced by region_azone_initialize().
static void region_azone_tria (ScrArea * sa, AZone * az, ARegion * ar) [static]
Definition at line 809 of file area.c.
References ScrArea::actionzones, add(), AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, AZONEPAD_TRIAH, AZONEPAD_TRIAW, BLI_init_rcti(), AZone::edge, ListBase::first, AZone::next, AZone::rect, ScrArea::totrct, ARegion::winrct, AZone::x1, AZone::x2, rcti::xmax, rcti::xmin, AZone::y1, AZone::y2, rcti::ymax, and rcti::ymin.
Referenced by region_azone_initialize().
static void region_draw_azone_icon (AZone * az) [static]
Definition at line 199 of file area.c.
References NULL, sdrawline(), AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by ED_area_overdraw().
static void region_draw_azone_tab (AZone * az) [static]
Definition at line 276 of file area.c.
References AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, AZone::edge, TH_HEADER, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, UI_GetThemeColor3fv(), UI_RB_ALPHA, uiDrawBoxShade(), uiRoundRect(), uiSetRoundBox(), AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by ED_area_overdraw().
static void region_draw_azone_tab_plus (AZone * az) [static]
Definition at line 243 of file area.c.
References AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, draw_azone_plus(), AZone::edge, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, ui_draw_anti_tria(), uiRoundBox(), uiSetRoundBox(), AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by ED_area_overdraw().
static void region_draw_azone_tria (AZone * az) [static]
Definition at line 319 of file area.c.
References AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, AZone::edge, ui_draw_anti_tria(), AZone::x1, AZone::x2, AZone::y1, and AZone::y2.
Referenced by ED_area_overdraw().
static void region_draw_emboss (ARegion * ar, rcti * scirct) [static]
Definition at line 72 of file area.c.
References sdrawline(), ARegion::winrct, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ED_region_do_draw().
static void region_rect_recursive (ScrArea * sa, ARegion * ar, rcti * remainder, int quad) [static]
Definition at line 904 of file area.c.
References ARegion::alignment, BLI_init_rcti(), ELEM, ELEM4, ARegion::flag, G, G_DEBUG, ARegion::next, NULL, ARegionType::prefsizex, ARegionType::prefsizey, ARegion::prev, rct_fits(), region_azone_add(), ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_FLOAT, RGN_ALIGN_HSPLIT, RGN_ALIGN_LEFT, RGN_ALIGN_NONE, RGN_ALIGN_QSPLIT, RGN_ALIGN_RIGHT, RGN_ALIGN_TOP, RGN_ALIGN_VSPLIT, RGN_FLAG_HIDDEN, RGN_FLAG_TOO_SMALL, RGN_OVERLAP_LEFT, RGN_OVERLAP_RIGHT, RGN_SPLIT_PREV, RGN_TYPE_HEADER, RGN_TYPE_UI, ARegion::sizex, ARegion::sizey, SPACE_FILE, ScrArea::spacetype, ARegion::type, UI_UNIT_Y, ARegion::winrct, ARegion::winx, ScrArea::winy, ARegion::winy, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ED_area_initialize().
void region_scissor_winrct (ARegion * ar, rcti * winrct)
Definition at line 396 of file area.c.
References ARegion::alignment, BLI_isect_rcti(), ELEM, ARegion::flag, NULL, ARegion::prev, RGN_FLAG_HIDDEN, RGN_OVERLAP_LEFT, RGN_OVERLAP_RIGHT, RGN_SPLIT_PREV, ARegion::winrct, rcti::xmax, and rcti::xmin.
Referenced by backdrawview3d(), ED_region_do_draw(), and ED_region_set().
static void region_subwindow (wmWindow * win, ARegion * ar) [static]
Definition at line 1135 of file area.c.
References ARegion::flag, RGN_FLAG_HIDDEN, RGN_FLAG_TOO_SMALL, ARegion::swinid, ARegion::winrct, wm_subwindow_close(), wm_subwindow_open(), and wm_subwindow_position().
Referenced by ED_area_initialize(), and ED_region_init().
static void spacefunc (struct bContext * C, void * UNUSEDarg1, void * UNUSEDarg2) [static]
Definition at line 1494 of file area.c.
References CTX_wm_area(), ED_area_newspace(), ED_area_tag_redraw(), NC_SPACE, ND_SPACE_CHANGED, and WM_event_add_notifier().
Referenced by ED_area_header_switchbutton().