Blender: node_util.h File Reference
node_util.h File Reference
nodes
#include "DNA_listBase.h"
#include "BKE_node.h"
#include "MEM_guardedalloc.h"
#include "NOD_socket.h"
#include "GPU_material.h"
Defines
#define DO_INLINE static inline
Functions
void node_free_curves (struct bNode *node)
void node_free_standard_storage (struct bNode *node)
void node_copy_curves (struct bNode *orig_node, struct bNode *new_node)
void node_copy_standard_storage (struct bNode *orig_node, struct bNode *new_node)
const char * node_blend_label (struct bNode *node)
const char * node_math_label (struct bNode *node)
const char * node_vect_math_label (struct bNode *node)
const char * node_filter_label (struct bNode *node)
ListBase node_internal_connect_default (struct bNodeTree *ntree, struct bNode *node)
Detailed Description
Definition in file node_util.h.
Define Documentation
#define DO_INLINE static inline
Definition at line 74 of file node_util.h.
Function Documentation
const char* node_blend_label (struct bNode * node)
Definition at line 75 of file node_util.c.
References bNode::custom1, IFACE_, ramp_blend_items, and RNA_enum_name().
Referenced by register_node_type_cmp_mix_rgb(), register_node_type_sh_mix_rgb(), and register_node_type_tex_mix_rgb().
void node_copy_curves (struct bNode * orig_node, struct bNode * new_node)
Definition at line 63 of file node_util.c.
References curvemapping_copy(), and bNode::storage.
Referenced by register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_huecorrect(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_tex_curve_rgb(), and register_node_type_tex_curve_time().
void node_copy_standard_storage (struct bNode * orig_node, struct bNode * new_node)
Definition at line 68 of file node_util.c.
References MEM_dupallocN(), and bNode::storage.
Referenced by copy(), register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_crop(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_distance_matte(), register_node_type_cmp_glare(), register_node_type_cmp_hue_sat(), register_node_type_cmp_image(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_movieclip(), register_node_type_cmp_splitviewer(), register_node_type_cmp_tonemap(), register_node_type_cmp_valtorgb(), register_node_type_cmp_vecblur(), register_node_type_cmp_viewer(), register_node_type_sh_attribute(), register_node_type_sh_geom(), register_node_type_sh_mapping(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_valtorgb(), register_node_type_tex_image(), and register_node_type_tex_valtorgb().
const char* node_filter_label (struct bNode * node)
Definition at line 96 of file node_util.c.
References bNode::custom1, IFACE_, node_filter_items, and RNA_enum_name().
Referenced by register_node_type_cmp_filter().
void node_free_curves (struct bNode * node)
Definition at line 53 of file node_util.c.
References curvemapping_free(), and bNode::storage.
Referenced by register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_huecorrect(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_tex_curve_rgb(), and register_node_type_tex_curve_time().
void node_free_standard_storage (struct bNode * node)
Definition at line 58 of file node_util.c.
References MEM_freeN(), and bNode::storage.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_crop(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_distance_matte(), register_node_type_cmp_glare(), register_node_type_cmp_hue_sat(), register_node_type_cmp_image(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_movieclip(), register_node_type_cmp_splitviewer(), register_node_type_cmp_tonemap(), register_node_type_cmp_valtorgb(), register_node_type_cmp_vecblur(), register_node_type_cmp_viewer(), register_node_type_sh_attribute(), register_node_type_sh_geom(), register_node_type_sh_mapping(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_valtorgb(), register_node_type_tex_image(), register_node_type_tex_output(), and register_node_type_tex_valtorgb().
ListBase node_internal_connect_default (struct bNodeTree * ntree, struct bNode * node)
Definition at line 103 of file node_util.c.
References BLI_addtail(), ListBase::first, bNodeLink::flag, bNodeLink::fromnode, bNodeLink::fromsock, ListBase::last, link(), bNodeTree::links, MEM_callocN(), bNodeLink::next, NODE_LINK_VALID, NULL, NUM_SOCKET_TYPES, bNodeLink::tonode, bNodeLink::tosock, and bNodeSocket::type.
const char* node_math_label (struct bNode * node)
Definition at line 82 of file node_util.c.
References bNode::custom1, IFACE_, node_math_items, and RNA_enum_name().
Referenced by register_node_type_cmp_math(), register_node_type_sh_math(), and register_node_type_tex_math().
const char* node_vect_math_label (struct bNode * node)
Definition at line 89 of file node_util.c.
References bNode::custom1, IFACE_, node_vec_math_items, and RNA_enum_name().
Referenced by register_node_type_sh_vect_math().