Blender: kernel_differential.h File Reference
kernel_differential.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void differential_transfer (differential3 *dP_, const differential3 dP, float3 D, const differential3 dD, float3 Ng, float t)
__device void differential_incoming (differential3 *dI, const differential3 dD)
__device void differential_dudv (differential *du, differential *dv, float3 dPdu, float3 dPdv, differential3 dP, float3 Ng)
Function Documentation
__device void differential_dudv (differential * du, differential * dv, float3 dPdu, float3 dPdv, differential3 dP, float3 Ng)
Definition at line 45 of file kernel_differential.h.
References differential::dx, differential3::dx, differential3::dy, differential::dy, fabsf, float3::x, float3::y, and float3::z.
Referenced by shader_setup_from_ray().
__device void differential_incoming (differential3 * dI, const differential3 dD)
Definition at line 36 of file kernel_differential.h.
References differential3::dx, and differential3::dy.
Referenced by shader_setup_from_background(), and shader_setup_from_ray().
CCL_NAMESPACE_BEGIN __device void differential_transfer (differential3 * dP_, const differential3 dP, float3 D, const differential3 dD, float3 Ng, float t)
Definition at line 23 of file kernel_differential.h.
References dot(), differential3::dx, and differential3::dy.
Referenced by shader_setup_from_ray().