Blender: SubdAccBuilder Class Reference
SubdAccBuilder Class Reference
#include <subd_build.h>
Public Member Functions
SubdAccBuilder ()
~SubdAccBuilder ()
Patch * run (SubdFace *face)
Protected Member Functions
void computeCornerStencil (SubdFaceRing *ring, GregoryAccStencil *stencil)
void computeEdgeStencil (SubdFaceRing *ring, GregoryAccStencil *stencil)
void computeInteriorStencil (SubdFaceRing *ring, GregoryAccStencil *stencil)
void computeBoundaryTangentStencils (SubdFaceRing *ring, SubdVert *vert, StencilMask &r0, StencilMask &r1)
Detailed Description
Definition at line 43 of file subd_build.h.
Constructor & Destructor Documentation
SubdAccBuilder::SubdAccBuilder ()
Definition at line 95 of file subd_build.cpp.
SubdAccBuilder::~SubdAccBuilder ()
Definition at line 99 of file subd_build.cpp.
Member Function Documentation
void SubdAccBuilder::computeBoundaryTangentStencils (SubdFaceRing * ring, SubdVert * vert, StencilMask & r0, StencilMask & r1) [protected]
Definition at line 552 of file subd_build.cpp.
References assert, cosf, SubdVert::edge, SubdVert::edges(), SubdEdge::from(), SubdVert::is_boundary(), SubdVert::EdgeIterator::isDone(), M_PI_F, NULL, SubdFaceRing::num_verts(), p, SubdEdge::pair, SubdEdge::prev, sinf, StencilMask::size(), sqrtf, SubdEdge::to(), SubdVert::valence(), and SubdFaceRing::vert_index().
Referenced by computeEdgeStencil().
void SubdAccBuilder::computeCornerStencil (SubdFaceRing * ring, GregoryAccStencil * stencil) [protected]
Definition at line 132 of file subd_build.cpp.
References assert, SubdVert::co, SubdVert::edge, SubdEdge::face, SubdFaceRing::firstEdge(), SubdEdge::from(), GregoryAccStencil::get(), SubdVert::is_boundary(), StencilMask::is_normalized(), SubdFaceRing::is_quad(), SubdFaceRing::is_triangle(), SubdFace::EdgeIterator::isDone(), SubdVert::EdgeIterator::isDone(), SubdEdge::next, StencilMask::normalize(), NULL, SubdEdge::prev, SubdEdge::to(), and SubdVert::valence().
Referenced by run().
void SubdAccBuilder::computeEdgeStencil (SubdFaceRing * ring, GregoryAccStencil * stencil) [protected]
Definition at line 188 of file subd_build.cpp.
References assert, SubdVert::co, computeBoundaryTangentStencils(), cosf, SubdVert::edge, SubdVert::edges(), SubdEdge::face, SubdFaceRing::firstEdge(), SubdEdge::from(), GregoryAccStencil::get(), i, SubdVert::is_boundary(), StencilMask::is_normalized(), SubdFaceRing::is_quad(), SubdFaceRing::is_triangle(), SubdVert::EdgeIterator::isDone(), SubdFace::EdgeIterator::isDone(), M_PI_F, min, SubdEdge::next, SubdFaceRing::num_verts(), SubdEdge::pair, SubdEdge::prev, sinf, sqrtf, SubdEdge::to(), and SubdVert::valence().
Referenced by run().
void SubdAccBuilder::computeInteriorStencil (SubdFaceRing * ring, GregoryAccStencil * stencil) [protected]
Definition at line 353 of file subd_build.cpp.
References assert, cosf, SubdFace::edges(), SubdEdge::face, SubdFaceRing::face(), SubdFaceRing::firstEdge(), SubdEdge::from(), GregoryAccStencil::get(), i, SubdEdge::is_boundary(), SubdFaceRing::is_quad(), SubdFaceRing::is_triangle(), SubdFace::EdgeIterator::isDone(), M_PI_F, SubdEdge::next, StencilMask::normalize(), SubdFaceRing::num_verts(), SubdEdge::pair, SubdEdge::prev, pseudoValence(), SubdEdge::to(), and SubdFaceRing::vert_index().
Referenced by run().
Patch * SubdAccBuilder::run (SubdFace * face) [virtual]
Implements SubdBuilder.
Definition at line 103 of file subd_build.cpp.
References assert, computeCornerStencil(), computeEdgeStencil(), computeInteriorStencil(), SubdFace::edge, SubdFaceRing::evaluate_stencils(), GregoryTrianglePatch::hull, GregoryQuadPatch::hull, NULL, SubdFace::num_edges(), and GregoryAccStencil::stencil.
The documentation for this class was generated from the following files:
subd_build.h
subd_build.cpp