Blender: meshlaplacian.h File Reference
meshlaplacian.h File Reference
armature
Typedefs
typedef struct LaplacianSystem LaplacianSystem
Functions
void laplacian_add_vertex (LaplacianSystem *sys, float *co, int pinned)
void laplacian_add_triangle (LaplacianSystem *sys, int v1, int v2, int v3)
void laplacian_begin_solve (LaplacianSystem *sys, int index)
void laplacian_add_right_hand_side (LaplacianSystem *sys, int v, float value)
int laplacian_system_solve (LaplacianSystem *sys)
float laplacian_system_get_solution (int v)
void heat_bone_weighting (struct Object *ob, struct Mesh *me, float(*verts)[3], int numbones, struct bDeformGroup **dgrouplist, struct bDeformGroup **dgroupflip, float(*root)[3], float(*tip)[3], int *selected, const char **error)
Detailed Description
Definition in file meshlaplacian.h.
Typedef Documentation
typedef struct LaplacianSystem LaplacianSystem
Definition at line 52 of file meshlaplacian.h.
Function Documentation
void heat_bone_weighting (struct Object * ob, struct Mesh * me, float(*) verts[3], int numbones, struct bDeformGroup ** dgrouplist, struct bDeformGroup ** dgroupflip, float(*) root[3], float(*) tip[3], int * selected, const char ** error)
Definition at line 653 of file meshlaplacian.c.
References BKE_mesh_tessface_ensure(), ED_vgroup_vert_add(), ED_vgroup_vert_remove(), ED_vgroup_vert_weight(), Mesh::editflag, FALSE, MVert::flag, MPoly::flag, LaplacianSystem::HeatWeighting::H, LaplacianSystem::heat, heat_laplacian_create(), heat_limit_weight(), heat_ray_tree_create(), heat_source_closest(), heat_system_free(), laplacian_add_right_hand_side(), laplacian_begin_solve(), laplacian_system_construct_begin(), laplacian_system_construct_end(), laplacian_system_delete(), laplacian_system_get_solution(), laplacian_system_solve(), MPoly::loopstart, ME_EDIT_PAINT_MASK, ME_EDIT_VERT_SEL, ME_FACE_SEL, MEM_callocN(), MEM_freeN(), mesh_get_x_mirror_vert(), LaplacianSystem::HeatWeighting::mface, Mesh::mface, Mesh::mloop, Mesh::mpoly, Mesh::mvert, NULL, LaplacianSystem::HeatWeighting::numsource, LaplacianSystem::HeatWeighting::p, LaplacianSystem::HeatWeighting::root, SELECT, BVHCallbackUserData::sys, LaplacianSystem::HeatWeighting::tip, LaplacianSystem::HeatWeighting::totface, Mesh::totface, Mesh::totvert, LaplacianSystem::HeatWeighting::totvert, MLoop::v, MFace::v4, LaplacianSystem::HeatWeighting::verts, WEIGHT_ADD, and WEIGHT_REPLACE.
Referenced by add_verts_to_dgroups().
void laplacian_add_right_hand_side (LaplacianSystem * sys, int v, float value)
void laplacian_add_triangle (LaplacianSystem * sys, int v1, int v2, int v3)
Definition at line 281 of file meshlaplacian.c.
References LaplacianSystem::faces, and LaplacianSystem::totface.
Referenced by heat_laplacian_create().
void laplacian_add_vertex (LaplacianSystem * sys, float * co, int pinned)
Definition at line 274 of file meshlaplacian.c.
References co, LaplacianSystem::totvert, LaplacianSystem::verts, and LaplacianSystem::vpinned.
Referenced by heat_laplacian_create().
void laplacian_begin_solve (LaplacianSystem * sys, int index)
Definition at line 352 of file meshlaplacian.c.
References NL_MATRIX, NL_SYSTEM, nlBegin(), LaplacianSystem::nlbegun, nlLockVariable(), nlSetVariable(), LaplacianSystem::totvert, LaplacianSystem::verts, and LaplacianSystem::vpinned.
Referenced by heat_bone_weighting(), and laplacian_system_construct_end().
float laplacian_system_get_solution (int v)
Definition at line 389 of file meshlaplacian.c.
References nlGetVariable().
Referenced by heat_bone_weighting().
int laplacian_system_solve (LaplacianSystem * sys)
Definition at line 378 of file meshlaplacian.c.
References NL_MATRIX, NL_SYSTEM, NL_TRUE, LaplacianSystem::nlbegun, nlEnd(), nlSolveAdvanced(), and NULL.
Referenced by heat_bone_weighting().