Blender: MT_Tuple4 Class Reference
MT_Tuple4 Class Reference
#include <MT_Tuple4.h>
Public Member Functions
MT_Tuple4 ()
MT_Tuple4 (const float *v)
MT_Tuple4 (const double *v)
MT_Tuple4 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww)
MT_Scalar & operator[] (int i)
const MT_Scalar & operator[] (int i) const
MT_Scalar & x ()
const MT_Scalar & x () const
MT_Scalar & y ()
const MT_Scalar & y () const
MT_Scalar & z ()
const MT_Scalar & z () const
MT_Scalar & w ()
const MT_Scalar & w () const
MT_Scalar * getValue ()
const MT_Scalar * getValue () const
void getValue (float *v) const
void getValue (double *v) const
void setValue (const float *v)
void setValue (const double *v)
void setValue (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww)
Protected Attributes
MT_Scalar m_co [4]
Detailed Description
Definition at line 53 of file MT_Tuple4.h.
Constructor & Destructor Documentation
MT_Tuple4::MT_Tuple4 () [inline]
Definition at line 55 of file MT_Tuple4.h.
MT_Tuple4::MT_Tuple4 (const float * v) [inline]
Definition at line 56 of file MT_Tuple4.h.
References setValue().
MT_Tuple4::MT_Tuple4 (const double * v) [inline]
Definition at line 57 of file MT_Tuple4.h.
References setValue().
MT_Tuple4::MT_Tuple4 (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww) [inline]
Definition at line 58 of file MT_Tuple4.h.
References setValue().
Member Function Documentation
MT_Scalar* MT_Tuple4::getValue () [inline]
Definition at line 77 of file MT_Tuple4.h.
References m_co.
Referenced by KX_FontObject::DrawText(), RAS_TexVert::RAS_TexVert(), BL_Shader::SetUniform(), and LOD_QuadricEditor::Update().
const MT_Scalar* MT_Tuple4::getValue () const [inline]
Definition at line 78 of file MT_Tuple4.h.
References m_co.
void MT_Tuple4::getValue (float * v) const [inline]
Definition at line 81 of file MT_Tuple4.h.
References m_co.
void MT_Tuple4::getValue (double * v) const [inline]
Definition at line 88 of file MT_Tuple4.h.
References m_co.
MT_Scalar& MT_Tuple4::operator[] (int i) [inline]
Definition at line 62 of file MT_Tuple4.h.
References i, and m_co.
const MT_Scalar& MT_Tuple4::operator[] (int i) const [inline]
Definition at line 63 of file MT_Tuple4.h.
References i, and m_co.
void MT_Tuple4::setValue (const double * v) [inline]
Definition at line 102 of file MT_Tuple4.h.
References m_co.
void MT_Tuple4::setValue (MT_Scalar xx, MT_Scalar yy, MT_Scalar zz, MT_Scalar ww) [inline]
Definition at line 109 of file MT_Tuple4.h.
References m_co.
void MT_Tuple4::setValue (const float * v) [inline]
Definition at line 95 of file MT_Tuple4.h.
References m_co.
Referenced by Carve_exportMesh(), KX_Camera::ExtractFrustumSphere(), MT_Tuple4(), MT_Quaternion::operator*=(), MT_Quaternion::setEuler(), and MT_Quaternion::setRotation().
const MT_Scalar& MT_Tuple4::w () const [inline]
Definition at line 75 of file MT_Tuple4.h.
References m_co.
MT_Scalar& MT_Tuple4::w () [inline]
Definition at line 74 of file MT_Tuple4.h.
References m_co.
Referenced by BOP_intersectPlane(), and MT_ExpMap::setRotation().
const MT_Scalar& MT_Tuple4::x () const [inline]
Definition at line 66 of file MT_Tuple4.h.
References m_co.
MT_Scalar& MT_Tuple4::x () [inline]
Definition at line 65 of file MT_Tuple4.h.
References m_co.
Referenced by BOP_intersectCoplanarFaces(), BOP_intersectPlane(), BOP_orientation(), BOP_removeOverlappedFaces(), and MT_ExpMap::setRotation().
MT_Scalar& MT_Tuple4::y () [inline]
Definition at line 68 of file MT_Tuple4.h.
References m_co.
Referenced by BOP_intersectCoplanarFaces(), BOP_intersectPlane(), BOP_orientation(), BOP_removeOverlappedFaces(), and MT_ExpMap::setRotation().
const MT_Scalar& MT_Tuple4::y () const [inline]
Definition at line 69 of file MT_Tuple4.h.
References m_co.
const MT_Scalar& MT_Tuple4::z () const [inline]
Definition at line 72 of file MT_Tuple4.h.
References m_co.
MT_Scalar& MT_Tuple4::z () [inline]
Definition at line 71 of file MT_Tuple4.h.
References m_co.
Referenced by BOP_intersectCoplanarFaces(), BOP_intersectPlane(), BOP_orientation(), BOP_removeOverlappedFaces(), and MT_ExpMap::setRotation().
Member Data Documentation
MT_Scalar MT_Tuple4::m_co[4] [protected]
Definition at line 114 of file MT_Tuple4.h.
Referenced by MT_Vector4::absolute(), MT_Quaternion::conjugate(), MT_Vector4::dot(), getValue(), MT_Plane3::Invert(), MT_Plane3::MT_Plane3(), MT_Plane3::Normal(), MT_Vector4::operator*=(), MT_Quaternion::operator*=(), MT_Vector4::operator+=(), MT_Vector4::operator-=(), MT_Plane3::operator=(), operator[](), MT_Plane3::Scalar(), MT_Vector4::scale(), MT_Vector4::scaled(), setValue(), MT_Plane3::signedDistance(), w(), x(), y(), and z().
The documentation for this class was generated from the following file:
MT_Tuple4.h