Blender: bmesh_operators_private.h File Reference
bmesh_operators_private.h File Reference
BMesh
Functions
void BMO_push (BMesh *bm, BMOperator *op)
void BMO_pop (BMesh *bm)
BMESH OPSTACK POP.
void bmo_split_exec (BMesh *bm, BMOperator *op)
void bmo_spin_exec (BMesh *bm, BMOperator *op)
void bmo_dupe_exec (BMesh *bm, BMOperator *op)
void bmo_del_exec (BMesh *bm, BMOperator *op)
void bmo_esubd_exec (BMesh *bm, BMOperator *op)
void bmo_triangulate_exec (BMesh *bm, BMOperator *op)
void bmo_dissolve_faces_exec (BMesh *bm, BMOperator *op)
void bmo_dissolve_verts_exec (BMesh *bm, BMOperator *op)
void bmo_dissolve_limit_exec (BMesh *bm, BMOperator *op)
void bmo_extrude_face_region_exec (BMesh *bm, BMOperator *op)
void bmo_vertex_slide_exec (BMesh *bm, BMOperator *op)
void bmo_connectverts_exec (BMesh *bm, BMOperator *op)
void bmo_extrude_vert_indiv_exec (BMesh *bm, BMOperator *op)
void bmo_mesh_to_bmesh_exec (BMesh *bm, BMOperator *op)
void bmo_bmesh_to_mesh_exec (BMesh *bm, BMOperator *op)
void bmo_translate_exec (BMesh *bm, BMOperator *op)
void bmo_transform_exec (BMesh *bm, BMOperator *op)
void bmo_contextual_create_exec (BMesh *bm, BMOperator *op)
void bmo_edgenet_fill_exec (BMesh *bm, BMOperator *op)
void bmo_rotate_exec (BMesh *bm, BMOperator *op)
void bmo_makevert_exec (BMesh *bm, BMOperator *op)
void bmo_dissolve_edges_exec (BMesh *bm, BMOperator *op)
void bmo_dissolve_edgeloop_exec (BMesh *bm, BMOperator *op)
void bmo_weldverts_exec (BMesh *bm, BMOperator *op)
void bmo_removedoubles_exec (BMesh *bm, BMOperator *op)
void bmo_finddoubles_exec (BMesh *bm, BMOperator *op)
void bmo_mirror_exec (BMesh *bm, BMOperator *op)
void bmo_edgebisect_exec (BMesh *bm, BMOperator *op)
void bmo_reversefaces_exec (BMesh *bm, BMOperator *op)
void bmo_edgerotate_exec (BMesh *bm, BMOperator *op)
void bmo_regionextend_exec (BMesh *bm, BMOperator *op)
void bmo_righthandfaces_exec (BMesh *bm, BMOperator *op)
void bmo_vertexsmooth_exec (BMesh *bm, BMOperator *op)
void bmo_extrude_edge_only_exec (BMesh *bm, BMOperator *op)
void bmo_extrude_face_indiv_exec (BMesh *bm, BMOperator *op)
void bmo_collapse_uvs_exec (BMesh *bm, BMOperator *op)
void bmo_pointmerge_exec (BMesh *bm, BMOperator *op)
void bmo_collapse_exec (BMesh *bm, BMOperator *op)
void bmo_similarfaces_exec (BMesh *bm, BMOperator *op)
void bmo_similaredges_exec (BMesh *bm, BMOperator *op)
void bmo_similarverts_exec (BMesh *bm, BMOperator *op)
void bmo_pointmerge_facedata_exec (BMesh *bm, BMOperator *op)
void bmo_vert_average_facedata_exec (BMesh *bm, BMOperator *op)
void bmo_face_rotateuvs_exec (BMesh *bm, BMOperator *op)
void bmo_object_load_bmesh_exec (BMesh *bm, BMOperator *op)
void bmo_face_reverseuvs_exec (BMesh *bm, BMOperator *op)
void bmo_edgenet_prepare (BMesh *bm, BMOperator *op)
void bmo_rotatecolors_exec (BMesh *bm, BMOperator *op)
void bmo_face_reversecolors_exec (BMesh *bm, BMOperator *op)
void bmo_vertexshortestpath_exec (BMesh *bm, BMOperator *op)
void bmo_scale_exec (BMesh *bm, BMOperator *op)
void bmo_edgesplit_exec (BMesh *bm, BMOperator *op)
void bmo_automerge_exec (BMesh *bm, BMOperator *op)
void bmo_create_cone_exec (BMesh *bm, BMOperator *op)
void bmo_create_monkey_exec (BMesh *bm, BMOperator *op)
void bmo_create_icosphere_exec (BMesh *bm, BMOperator *op)
void bmo_create_uvsphere_exec (BMesh *bm, BMOperator *op)
void bmo_create_grid_exec (BMesh *bm, BMOperator *op)
void bmo_create_cube_exec (BMesh *bm, BMOperator *op)
void bmo_join_triangles_exec (BMesh *bm, BMOperator *op)
void bmo_bevel_exec (BMesh *bm, BMOperator *op)
void bmo_beautify_fill_exec (BMesh *bm, BMOperator *op)
void bmo_triangle_fill_exec (BMesh *bm, BMOperator *op)
void bmo_create_circle_exec (BMesh *bm, BMOperator *op)
void bmo_bridge_loops_exec (BMesh *bm, BMOperator *op)
void bmo_solidify_face_region_exec (BMesh *bm, BMOperator *op)
void bmo_inset_exec (BMesh *bm, BMOperator *op)
Detailed Description
Definition in file bmesh_operators_private.h.
Function Documentation
void bmo_automerge_exec (BMesh * bm, BMOperator * op)
Definition at line 576 of file bmo_removedoubles.c.
References BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), VERT_IN, and VERT_KEEP.
void bmo_beautify_fill_exec (BMesh * bm, BMOperator * op)
Definition at line 82 of file bmo_triangulate.c.
References area_tri_v3(), BM_EDGE, BM_edge_is_manifold(), BM_edge_rotate(), BM_EDGEROT_CHECK_EXISTS, BM_EDGES_OF_MESH, BM_FACE, BM_ITER_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, EDGE_MARK, ELE_NEW, BMLoop::f, FACE_MARK, FALSE, is_quad_convex_v3(), BMEdge::l, BMFace::len, len_v3v3(), BMLoop::next, BMLoop::prev, BMLoop::radial_next, and BMLoop::v.
void bmo_bevel_exec (BMesh * bm, BMOperator * op)
Definition at line 181 of file bmo_bevel.c.
References add_v3_v3(), angle_v3v3v3(), BEVEL_DEL, BEVEL_FLAG, BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_lookup(), BLI_smallhash_release(), BLI_smallhash_remove(), BM_EDGE, BM_edge_create(), BM_edge_exists(), BM_edge_face_count(), BM_edge_other_vert(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_elem_attrs_copy(), BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_create(), BM_face_create_ngon(), BM_face_create_quad_tri(), BM_face_exists(), BM_FACE_FIRST_LOOP, BM_face_kill(), BM_faces_join(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_loop_interp_from_face(), BM_loop_interp_multires(), BM_LOOPS_OF_EDGE, BM_LOOPS_OF_FACE, BM_LOOPS_OF_VERT, BM_vert_create(), BM_vert_in_edge(), BM_VERTS_OF_MESH, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), calc_corner_co(), CD_MDISPS, CD_PROP_FLT, co, BMVert::co, CustomData_bmesh_get_n(), CustomData_has_layer(), BMHeader::data, DEL_EDGES, DEL_FACES, DEL_VERTS, BMLoop::e, BMesh::edata, EDGE_OLD, BMesh::elem_index_dirty, err, ETAG_GET, ETAG_SET, BMLoop::f, FACE_HOLE, FACE_NEW, FACE_OLD, FACE_SPAN, FALSE, hash, BMEdge::head, i, BMEdge::l, BMesh::ldata, mul_v3_fl(), LoopTag::newv, BMLoop::next, normalize_v3(), NULL, BMLoop::prev, BMLoop::radial_next, sub_v3_v3v3(), TRUE, BMLoop::v, BMEdge::v1, BMEdge::v2, and VERT_OLD.
void bmo_bmesh_to_mesh_exec (BMesh * bm, BMOperator * op)
Definition at line 76 of file bmo_mesh_conv.c.
References BM_mesh_bm_to_me(), BMO_slot_bool_get(), and BMO_slot_ptr_get().
void bmo_bridge_loops_exec (BMesh * bm, BMOperator * op)
Definition at line 213 of file bmo_connect.c.
References ARRAY_SWAP, BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_assert, BM_EDGE, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_elem_attrs_copy(), BM_face_create_quad_tri(), BM_FACE_FIRST_LOOP, BM_ITER_ELEM, bm_vert_loop_pair(), BMERR_INVALID_SELECTION, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_ITER, BMO_slot_buffer_flag_enable(), clamp_index(), co, BMVert::co, EDGE_DONE, EDGE_MARK, BMLoop::f, get_outer_vert(), i, BMFace::len, len_squared_v3v3(), len_v3v3(), min, BMLoop::next, NULL, SWAP, TRUE, and BMEdge::v1.
void bmo_collapse_exec (BMesh * bm, BMOperator * op)
Definition at line 367 of file bmo_removedoubles.c.
References add_v3_v3v3(), BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_EDGE, BM_EDGES_OF_MESH, BM_ITER_MESH, BMO_elem_flag_test, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_slot_buffer_flag_enable(), BMO_slot_map_ptr_insert(), BMW_begin(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_MASK_NOP, BMW_NIL_LAY, BMW_SHELL, BMW_step(), copy_v3_v3(), DO_MINMAX, EDGE_MARK, i, INIT_MINMAX, max, min, mul_v3_fl(), NULL, and BMEdge::v1.
void bmo_collapse_uvs_exec (BMesh * bm, BMOperator * op)
Definition at line 480 of file bmo_removedoubles.c.
References bmo_collapsecon_do_layer(), CustomData_layer_has_math(), i, BMesh::ldata, and CustomData::totlayer.
void bmo_connectverts_exec (BMesh * bm, BMOperator * op)
Definition at line 43 of file bmo_connect.c.
References BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_EDGE, BM_face_legal_splits(), BM_face_split(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_VERT, BMERR_CONNECTVERT_FAILED, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMLoop::e, EDGE_OUT, FACE_NEW, FALSE, i, BMLoop::next, NULL, BMLoop::prev, BMLoop::v, and VERT_INPUT.
void bmo_contextual_create_exec (BMesh * bm, BMOperator * op)
Definition at line 1274 of file bmo_create.c.
References BM_EDGE, BM_edge_create(), BM_EDGES_OF_VERT, BM_elem_flag_enable, BM_ELEM_SMOOTH, BM_FACE, BM_face_create_ngon_vcloud(), BM_ITER_ELEM, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_buffer_count(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), BMO_slot_int_get(), BMEditSelection::ele, ELE_NEW, ELE_OUT, FALSE, ListBase::first, BMHeader::htype, BMEditSelection::htype, i, if(), BMFace::mat_nr, MEM_freeN(), MEM_mallocN(), BMEditSelection::next, NULL, BMesh::selected, and TRUE.
void bmo_create_circle_exec (BMesh * bm, BMOperator * op)
Definition at line 500 of file bmo_primitive.c.
References BM_edge_create(), BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), cosf, FACE_NEW, FALSE, M_PI, mul_m4_v3(), NULL, sinf, and VERT_MARK.
void bmo_create_cone_exec (BMesh * bm, BMOperator * op)
Definition at line 571 of file bmo_primitive.c.
References BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), cosf, FACE_NEW, FALSE, M_PI, mul_m4_v3(), NULL, sinf, and VERT_MARK.
void bmo_create_cube_exec (BMesh * bm, BMOperator * op)
Definition at line 667 of file bmo_primitive.c.
References BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_mat4_get(), FALSE, mul_m4_v3(), NULL, and VERT_MARK.
void bmo_create_grid_exec (BMesh * bm, BMOperator * op)
Definition at line 228 of file bmo_primitive.c.
References BM_edge_create(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), EDGE_ORIG, mul_m4_v3(), mul_mat3_m4_v3(), NULL, TRUE, and VERT_MARK.
void bmo_create_icosphere_exec (BMesh * bm, BMOperator * op)
Definition at line 380 of file bmo_primitive.c.
References BM_EDGE, BM_face_create_quad_tri(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_VERT, BM_vert_create(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), BMVert::co, BMLoop::e, EDGE_MARK, FACE_MARK, FALSE, icoface, icovert, mul_m4_v3(), NULL, TRUE, and VERT_MARK.
void bmo_create_monkey_exec (BMesh * bm, BMOperator * op)
Definition at line 452 of file bmo_primitive.c.
References BM_face_create_quad_tri(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_slot_buffer_from_enabled_flag(), BMO_slot_mat4_get(), co, BMVert::co, fabsf, FALSE, i, MEM_freeN(), MEM_mallocN(), monkeyf, monkeynf, monkeynv, monkeyo, monkeyv, mul_m4_v3(), NULL, and VERT_MARK.
void bmo_create_uvsphere_exec (BMesh * bm, BMOperator * op)
Definition at line 291 of file bmo_primitive.c.
References BM_edge_create(), BM_ITER_MESH, BM_VERT, BM_vert_create(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_mat4_get(), BMVert::co, cosf, EDGE_ORIG, FALSE, len(), len_v3v3(), M_PI, MIN2, mul_m4_v3(), mul_v3_m3v3(), NULL, quat_to_mat3(), sinf, and VERT_MARK.
void bmo_del_exec (BMesh * bm, BMOperator * op)
Definition at line 446 of file bmo_dupe.c.
References BM_ALL, BMO_remove_tagged_context(), BMO_slot_buffer_flag_enable(), BMO_slot_int_get(), and DEL_INPUT.
void bmo_dissolve_edgeloop_exec (BMesh * bm, BMOperator * op)
Definition at line 199 of file bmo_dissolve.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BM_EDGE, BM_edge_face_pair(), BM_faces_join_pair(), BM_ITER_MESH, BM_vert_collapse_edge(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, fb(), i, NULL, TRUE, BMEdge::v1, BMEdge::v2, and VERT_MARK.
void bmo_dissolve_edges_exec (BMesh * bm, BMOperator * op)
Definition at line 246 of file bmo_dissolve.c.
References BM_EDGE, BM_edge_face_pair(), BM_faces_join_pair(), BM_ITER_MESH, BM_vert_collapse_edge(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMO_elem_flag_set, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMVert::e, fb(), TRUE, and VERT_MARK.
void bmo_dissolve_faces_exec (BMesh * bm, BMOperator * op)
Definition at line 77 of file bmo_dissolve.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BM_FACE, BM_faces_join(), BM_ITER_MESH, BM_vert_collapse_edge(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMERR_DISSOLVEFACES_FAILED, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_set, BMO_elem_flag_test, BMO_error_clear(), BMO_error_occurred(), BMO_error_raise(), BMO_ITER, BMO_op_callf(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMW_begin(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_ISLAND, BMW_MASK_NOP, BMW_NIL_LAY, BMW_step(), DEL_FACES, BMVert::e, FACE_MARK, FACE_NEW, FACE_ORIG, i, MEM_freeN(), NULL, TRUE, and VERT_MARK.
void bmo_dissolve_limit_exec (BMesh * bm, BMOperator * op)
Definition at line 516 of file bmo_dissolve.c.
References angle(), BM_edge_calc_face_angle(), BM_edge_is_manifold(), BM_edge_is_wire(), BM_edge_kill(), BM_edge_normals_update(), BM_face_normal_update(), BM_faces_join_pair(), BM_vert_collapse_edge(), BM_vert_edge_count(), bm_vert_edge_face_angle(), BM_vert_kill(), BMO_error_clear(), BMO_slot_float_get(), BMO_slot_get(), BMOpSlot::data, dissolve_elem_cmp(), BMVert::e, DissolveElemWeight::ele, BMLoop::f, FALSE, i, BMEdge::l, BMOpSlot::len, M_PI, MAX2, MEM_freeN(), MEM_mallocN(), minf(), NULL, BMOpSlot::p, BMLoop::radial_next, TRUE, BMEdge::v1, BMEdge::v2, and DissolveElemWeight::weight.
void bmo_dissolve_verts_exec (BMesh * bm, BMOperator * op)
Definition at line 334 of file bmo_dissolve.c.
References BM_FACES_OF_VERT, BM_iter_new(), BM_iter_step(), BM_VERT, BM_vert_collapse_edge(), BM_vert_collapse_faces(), BM_vert_dissolve(), BM_vert_edge_count(), BM_VERTS_OF_MESH, BMERR_DISSOLVEVERTS_FAILED, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_clear(), BMO_error_get(), BMO_error_occurred(), BMO_error_raise(), BMO_op_callf(), BMO_slot_buffer_flag_enable(), BMVert::e, FACE_MARK, FACE_ORIG, NULL, test_extra_verts(), TRUE, and VERT_MARK.
void bmo_dupe_exec (BMesh * bm, BMOperator * op)
Duplicate Operator
Duplicates verts, edges and faces of a mesh.
INPUT SLOTS:
BMOP_DUPE_VINPUT: Buffer containing pointers to mesh vertices to be duplicated BMOP_DUPE_EINPUT: Buffer containing pointers to mesh edges to be duplicated BMOP_DUPE_FINPUT: Buffer containing pointers to mesh faces to be duplicated
OUTPUT SLOTS:
BMOP_DUPE_VORIGINAL: Buffer containing pointers to the original mesh vertices BMOP_DUPE_EORIGINAL: Buffer containing pointers to the original mesh edges BMOP_DUPE_FORIGINAL: Buffer containing pointers to the original mesh faces BMOP_DUPE_VNEW: Buffer containing pointers to the new mesh vertices BMOP_DUPE_ENEW: Buffer containing pointers to the new mesh edges BMOP_DUPE_FNEW: Buffer containing pointers to the new mesh faces
Definition at line 317 of file bmo_dupe.c.
References BM_ALL, BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_copy(), BMO_slot_ptr_get(), copy_mesh(), DUPE_INPUT, and DUPE_NEW.
void bmo_edgebisect_exec (BMesh * bm, BMOperator * op)
Definition at line 1096 of file bmo_subdivide.c.
References BM_ALL, BM_data_layer_add(), BM_data_layer_free_n(), BM_EDGE, bm_subdivide_multicut(), BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_int_get(), CD_SHAPEKEY, CustomData_number_of_layers(), ELE_SPLIT, SubDParams::numcuts, SubDParams::op, SubDParams::origkey, BMEdge::v1, BMEdge::v2, and BMesh::vdata.
void bmo_edgenet_fill_exec (BMesh * bm, BMOperator * op)
Definition at line 884 of file bmo_create.c.
References BLI_array_append, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_EDGE, BM_edge_exists(), BM_EDGES_OF_MESH, BM_elem_flag_enable, BM_elem_index_get, BM_elem_index_set, BM_ELEM_SMOOTH, BM_FACE, BM_face_create_ngon(), BM_face_exists_multi_edge(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_VERT, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_int_get(), BMO_slot_map_contains(), BMO_slot_map_int_get(), BMO_slot_map_int_insert(), count_edge_faces(), edge_find_shortest_path(), edge_free_path(), EDGE_MARK, edge_pathbase_free(), edge_pathbase_new(), ELE_ORIG, BMesh::elem_index_dirty, FACE_IGNORE, FACE_NEW, FALSE, ListBase::first, EdgeData::ftag, EPath::group, i, init_rotsys(), BMEdge::l, ListBase::last, BMFace::mat_nr, MEM_callocN(), MEM_freeN(), EPathNode::next, EPath::nodes, NULL, EdgeData::tag, BMesh::totedge, BMesh::totvert, TRUE, EPathNode::v, and vote_on_winding().
void bmo_edgenet_prepare (BMesh * bm, BMOperator * op)
Definition at line 1096 of file bmo_create.c.
References BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BLI_array_set_length, BM_EDGE, BM_edge_create(), BM_edge_share_vert_count(), BM_vert_in_edge(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_vert_edge_flags_count(), BMVert::co, cross_v3_v3v3(), dot_v3v3(), EDGE_MARK, edge_next(), EDGE_VIS, ELE_NEW, i, normal_tri_v3(), NULL, sub_v3_v3v3(), SWAP, TRUE, BMEdge::v1, and BMEdge::v2.
void bmo_edgerotate_exec (BMesh * bm, BMOperator * op)
this ends up being called twice, could add option to not to call check in BM_edge_rotate to get some extra speed
Definition at line 121 of file bmo_utils.c.
References BM_EDGE, BM_edge_face_pair(), BM_edge_rotate(), BM_edge_rotate_check(), BM_EDGEROT_CHECK_DEGENERATE, BM_EDGEROT_CHECK_EXISTS, BMERR_INVALID_SELECTION, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_count(), BMO_slot_buffer_from_enabled_flag(), EDGE_OUT, FACE_TAINT, FALSE, and fb().
void bmo_edgesplit_exec (BMesh * bm, BMOperator * op)
Definition at line 103 of file bmo_edgesplit.c.
References BM_EDGE, BM_edge_is_boundary(), bm_edgesplit_validate_seams(), BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_INTERNAL_TAG, BM_ELEM_TAG, BM_VERT, bmesh_edge_separate(), bmesh_vert_separate(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_hflag(), EDGE_SEAM, FALSE, BMEdge::l, NULL, UNLIKELY, BMEdge::v1, BMEdge::v2, and VERT_SEAM.
void bmo_esubd_exec (BMesh * bm, BMOperator * op)
Definition at line 674 of file bmo_subdivide.c.
References angle(), BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BLI_array_growone, BLI_drand(), BLI_srandom(), BM_ALL, BM_CHECK_ELEMENT, BM_data_layer_add(), BM_data_layer_free_n(), BM_EDGE, BM_edge_share_vert_count(), BM_FACE, BM_face_split(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, bm_subdivide_multicut(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_get(), BMO_slot_int_get(), BMO_slot_map_data_get(), BMO_slot_map_to_flag(), CD_SHAPEKEY, co, BMVert::co, SubDPattern::connectexec, copy_v3_v3(), CustomData_bmesh_get_n(), CustomData_number_of_layers(), BMHeader::data, BMOpSlot::data, dot_v3v3(), BMLoop::e, EDGE_PERCENT, ELE_INNER, ELE_SPLIT, fabsf, SubDFaceData::face, FACE_CUSTOMFILL, FALSE, SubDParams::fractal, BMVert::head, i, if(), BMOpSlot::len, SubDPattern::len, BMFace::len, normalize_v3(), NULL, SubDParams::numcuts, SubDParams::off, SubDParams::op, SubDParams::origkey, BMOpSlot::p, SubDFaceData::pat, PLEN, quad_1edge, quad_2edge_fan, quad_2edge_innervert, quad_2edge_path, quad_4edge, SubDParams::seed, SubDPattern::seledges, smooth(), SubDParams::smooth, SubDFaceData::start, sub_v3_v3v3(), SUBD_FAN, SUBD_INNERVERT, SUBD_PATH, SUBD_SPLIT, SubDFaceData::totedgesel, tri_1edge, tri_3edge, SubDParams::use_fractal, SubDParams::use_smooth, SubDParams::use_sphere, BMLoop::v, BMEdge::v1, BMEdge::v2, and BMesh::vdata.
void bmo_extrude_edge_only_exec (BMesh * bm, BMOperator * op)
Definition at line 170 of file bmo_extrude.c.
References BM_ALL, BM_EDGE, bm_extrude_copy_face_loop_attributes(), BM_face_create_quad_tri(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_iter_map_value(), BMO_iter_new(), BMO_iter_step(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_from_enabled_flag(), EXT_INPUT, EXT_KEEP, FALSE, BMEdge::l, NULL, BMLoop::v, BMEdge::v1, and BMEdge::v2.
void bmo_extrude_face_indiv_exec (BMesh * bm, BMOperator * op)
Definition at line 48 of file bmo_extrude.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_edge_create(), BM_edge_other_vert(), BM_elem_attrs_copy(), BM_FACE, BM_face_create_ngon(), BM_face_create_quad_tri(), BM_FACE_FIRST_LOOP, BM_ITER_ELEM, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_vert_create(), BMERR_MESH_ERROR, BMO_elem_flag_enable, BMO_error_raise(), BMO_ITER, BMO_op_callf(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, DEL_ONLYFACES, BMLoop::e, EXT_DEL, EXT_KEEP, FALSE, i, BMFace::len, BMLoop::next, NULL, and BMLoop::v.
void bmo_extrude_face_region_exec (BMesh * bm, BMOperator * op)
Definition at line 241 of file bmo_extrude.c.
References BMesh::act_face, BM_EDGE, BM_edge_create(), BM_edge_is_wire(), BM_edge_kill(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, bm_extrude_copy_face_loop_attributes(), BM_FACE, BM_face_create_quad_tri_v(), BM_face_normal_flip(), BM_FACES_OF_EDGE, BM_FACES_OF_MESH, BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_iter_map_value(), BMO_iter_new(), BMO_iter_step(), BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), BMO_slot_map_contains(), BMO_slot_map_ptr_get(), DEL_ONLYTAGGED, BMVert::e, EXT_DEL, EXT_INPUT, FALSE, BMEdge::l, NULL, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
void bmo_extrude_vert_indiv_exec (BMesh * bm, BMOperator * op)
Definition at line 222 of file bmo_extrude.c.
References BM_EDGE, BM_edge_create(), BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_iter_new(), BMO_iter_step(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, EXT_KEEP, FALSE, and NULL.
void bmo_face_reversecolors_exec (BMesh * bm, BMOperator * op)
Definition at line 1130 of file bmo_utils.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_FACE, BM_ITER_ELEM_INDEX, BM_LOOPS_OF_FACE, BMO_ITER, CD_MLOOPCOL, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, BMLoop::head, i, BMesh::ldata, BMFace::len, and NULL.
void bmo_face_reverseuvs_exec (BMesh * bm, BMOperator * op)
Definition at line 1024 of file bmo_utils.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_FACE, BM_ITER_ELEM_INDEX, BM_LOOPS_OF_FACE, BMO_ITER, CD_MLOOPUV, copy_v2_v2(), CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, BMLoop::head, i, BMesh::ldata, BMFace::len, NULL, and MLoopUV::uv.
void bmo_face_rotateuvs_exec (BMesh * bm, BMOperator * op)
Definition at line 957 of file bmo_utils.c.
References BM_FACE, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMO_ITER, BMO_slot_int_get(), CD_MLOOPUV, copy_v2_v2(), CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, DIRECTION_CCW, DIRECTION_CW, BMLoop::head, BMesh::ldata, and MLoopUV::uv.
void bmo_finddoubles_exec (BMesh * bm, BMOperator * op)
Definition at line 571 of file bmo_removedoubles.c.
References bmesh_finddoubles_common().
void bmo_inset_exec (BMesh * bm, BMOperator * op)
implementation is as follows...
set all faces as tagged/untagged based on selection.
find all edges that have 1 tagged, 1 untagged face.
separate these edges and tag vertices, set their index to point to the original edge.
build faces between old/new edges.
inset the new edges into their faces.
Definition at line 110 of file bmo_inset.c.
References add_v3_v3(), add_v3_v3v3(), angle_normalized_v3v3(), BLI_assert, BM_EDGE, BM_edge_calc_face_tangent(), BM_edge_calc_length(), BM_edge_create(), BM_edge_is_boundary(), bm_edge_is_mixed_face_tag(), BM_edge_ordered_verts_ex(), BM_edge_other_vert(), BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_elem_index_get, BM_elem_index_set, BM_ELEM_TAG, BM_FACE, BM_face_copy_shared(), BM_face_create_quad_tri_v(), BM_FACES_OF_VERT, BM_ITER_ELEM, BM_ITER_MESH, BM_ITER_MESH_INDEX, BM_loop_other_vert_loop(), BM_mesh_elem_hflag_disable_all(), BM_mesh_elem_hflag_enable_all(), BM_VERT, bm_vert_avg_tag_dist(), BM_vert_calc_shell_factor(), BM_vert_create(), BM_vert_splice(), BM_VERTS_OF_FACE, BM_VERTS_OF_MESH, bmesh_edge_separate(), bmesh_vert_separate(), BMO_elem_flag_enable, BMO_ITER, BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), BMO_slot_float_get(), BMVert::co, compare_v3v3(), copy_v3_v3(), cross_v3_v3v3(), dot_v3v3(), BMLoop::e, BMVert::e, SplitEdgeInfo::e_new, SplitEdgeInfo::e_old, ELE_NEW, BMesh::elem_index_dirty, BMLoop::f, FALSE, i, if(), SplitEdgeInfo::l, BMEdge::l, len_squared_v3(), SplitEdgeInfo::length, length(), madd_v3_v3fl(), madd_v3_v3v3fl(), MEM_callocN(), MEM_freeN(), MEM_mallocN(), mid_v3_v3v3(), mul_v3_fl(), negate_v3(), BMLoop::next, SplitEdgeInfo::no, BMFace::no, BMVert::no, normalize_v3(), NULL, BMLoop::prev, shell_angle_to_dist(), sub_v3_v3v3(), BMesh::totvert, TRUE, BMLoop::v, BMEdge::v1, BMEdge::v2, and zero_v3().
void bmo_join_triangles_exec (BMesh * bm, BMOperator * op)
Definition at line 223 of file bmo_join_triangles.c.
References BLI_array_count, BLI_array_declare, BLI_array_free, BLI_array_growone, BM_edge_face_pair(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SMOOTH, BM_FACE, BM_faces_join_pair(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_bool_get(), BMO_slot_float_get(), compareFaceAttribs(), JoinEdge::e, BMLoop::e, EDGE_CHOSEN, EDGE_MARK, BMLoop::f, FACE_INPUT, FACE_MARK, fplcmp(), i, BMEdge::l, BMFace::len, BMFace::mat_nr, measure_facepair(), BMLoop::next, NULL, BMLoop::prev, BMLoop::radial_next, TRUE, BMLoop::v, and JoinEdge::weight.
void bmo_makevert_exec (BMesh * bm, BMOperator * op)
Definition at line 44 of file bmo_utils.c.
References BM_VERT, BM_vert_create(), BMO_elem_flag_enable, BMO_slot_buffer_from_enabled_flag(), BMO_slot_vec_get(), and NULL.
void bmo_mesh_to_bmesh_exec (BMesh * bm, BMOperator * op)
Definition at line 54 of file bmo_mesh_conv.c.
References BM_mesh_bm_from_me(), BMO_slot_bool_get(), BMO_slot_ptr_get(), Mesh::key, Object::shapenr, and Key::totkey.
void bmo_mirror_exec (BMesh * bm, BMOperator * op)
Definition at line 41 of file bmo_mirror.c.
References ABS, BLI_array_declare, BLI_array_free, BLI_array_growone, BM_ALL, BM_FACE, BM_ITER_ELEM, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_VERT, BM_VERTS_OF_MESH, BMO_ITER, BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_map_ptr_insert(), BMO_slot_mat4_get(), CD_MLOOPUV, BMVert::co, CustomData_bmesh_get_n(), CustomData_number_of_layers(), BMHeader::data, ELE_NEW, BMesh::elem_index_dirty, BMLoop::head, i, invert_m4_m4(), BMesh::ldata, NULL, BMesh::totvert, and MLoopUV::uv.
void bmo_object_load_bmesh_exec (BMesh * bm, BMOperator * op)
Definition at line 67 of file bmo_mesh_conv.c.
References BMO_op_callf(), BMO_slot_ptr_get(), Object::data, and TRUE.
void bmo_pointmerge_exec (BMesh * bm, BMOperator * op)
Definition at line 341 of file bmo_removedoubles.c.
References BM_VERT, BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_slot_map_ptr_insert(), BMO_slot_vec_get(), BMVert::co, copy_v3_v3(), and NULL.
void bmo_pointmerge_facedata_exec (BMesh * bm, BMOperator * op)
Definition at line 256 of file bmo_removedoubles.c.
References BM_ITER_ELEM, BM_LOOPS_OF_VERT, BM_VERT, BM_vert_face_count(), BMO_ITER, BMO_iter_new(), CustomData_bmesh_copy_data(), CustomData_bmesh_get_layer_n(), CustomData_data_add(), CustomData_data_multiply(), CustomData_layer_has_math(), BMHeader::data, BMLoop::head, i, CustomData::layers, BMesh::ldata, NULL, CustomData::totlayer, and CustomDataLayer::type.
void BMO_pop (BMesh * bm)
BMESH OPSTACK POP.
Pops the opstack one level and frees a flag layer if appropriate
BMESH_TODO: investigate NOT freeing flag layers.
Definition at line 116 of file bmesh_operators.c.
References bmo_flag_layer_free(), and BMesh::stackdepth.
void BMO_push (BMesh * bm, BMOperator * op)
void bmo_regionextend_exec (BMesh * bm, BMOperator * op)
Definition at line 256 of file bmo_utils.c.
References BM_ALL, bmo_regionextend_constrict(), bmo_regionextend_extend(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), SEL_FLAG, and SEL_ORIG.
void bmo_removedoubles_exec (BMesh * bm, BMOperator * op)
Definition at line 560 of file bmo_removedoubles.c.
References bmesh_finddoubles_common(), BMO_op_exec(), BMO_op_finish(), and BMO_op_init().
void bmo_reversefaces_exec (BMesh * bm, BMOperator * op)
Definition at line 111 of file bmo_utils.c.
References BM_FACE, BM_face_normal_flip(), and BMO_ITER.
void bmo_righthandfaces_exec (BMesh * bm, BMOperator * op)
Definition at line 299 of file bmo_utils.c.
References BLI_array_declare, BLI_array_free, BLI_array_growone, BM_elem_flag_disable, BM_elem_flag_test, BM_elem_flag_toggle, BM_ELEM_TAG, BM_FACE, BM_face_calc_center_bounds(), BM_face_normal_flip(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_LOOPS_OF_LOOP, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_elem_flag_toggle, BMO_ITER, bmo_righthandfaces_exec(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), dot_v3v3(), BMLoop::f, FACE_FLAG, FACE_FLIP, FACE_VIS, i, BMFace::no, NULL, and BMLoop::v.
Referenced by bm_rationalize_normals(), and bmo_righthandfaces_exec().
void bmo_rotate_exec (BMesh * bm, BMOperator * op)
Definition at line 93 of file bmo_utils.c.
References BMO_op_callf(), BMO_slot_vec_get(), and mul_v3_fl().
void bmo_rotatecolors_exec (BMesh * bm, BMOperator * op)
Definition at line 1064 of file bmo_utils.c.
References BM_FACE, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMO_ITER, BMO_slot_int_get(), CD_MLOOPCOL, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, DIRECTION_CCW, DIRECTION_CW, BMLoop::head, and BMesh::ldata.
void bmo_scale_exec (BMesh * bm, BMOperator * op)
Definition at line 79 of file bmo_utils.c.
References BMO_op_callf(), BMO_slot_vec_get(), and unit_m3().
void bmo_similaredges_exec (BMesh * bm, BMOperator * op)
Definition at line 686 of file bmo_utils.c.
References angle(), SimSel_EdgeExt::angle, angle_v3v3(), BM_EDGE, BM_edge_calc_face_angle(), BM_edge_face_count(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SEAM, BM_ELEM_SMOOTH, BM_ITER_MESH, BM_mesh_elem_count(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), CD_CREASE, BMVert::co, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, SimSel_EdgeExt::e, BMesh::edata, EDGE_MARK, fabsf, SimSel_EdgeExt::faces, FALSE, BMEdge::head, i, indices, len_v3v3(), SimSel_EdgeExt::length, length(), MEM_callocN(), MEM_freeN(), NULL, RAD2DEGF, SIMEDGE_CREASE, SIMEDGE_DIR, SIMEDGE_FACE, SIMEDGE_FACE_ANGLE, SIMEDGE_LENGTH, SIMEDGE_SEAM, SIMEDGE_SHARP, sub_v3_v3v3(), thresh, TRUE, BMEdge::v1, and BMEdge::v2.
void bmo_similarfaces_exec (BMesh * bm, BMOperator * op)
Definition at line 514 of file bmo_utils.c.
References angle(), angle_v3v3(), SimSel_FaceExt::area, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_FACE, BM_face_calc_center_mean(), BM_face_calc_perimeter(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_mesh_elem_count(), BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), CD_MTEXPOLY, copy_v3_v3(), CustomData_bmesh_get(), CustomData_has_layer(), SimSel_FaceExt::d, BMHeader::data, dot_v3v3(), SimSel_FaceExt::f, fabsf, FACE_MARK, FALSE, BMFace::head, i, indices, BMFace::mat_nr, MEM_callocN(), MEM_freeN(), ngon_fake_area(), BMFace::no, normalize_v3(), NULL, BMesh::pdata, SimSel_FaceExt::perim, RAD2DEGF, SIMFACE_AREA, SIMFACE_COPLANAR, SIMFACE_IMAGE, SIMFACE_MATERIAL, SIMFACE_NORMAL, SIMFACE_PERIMETER, SimSel_FaceExt::t, thresh, MTexPoly::tpage, TRUE, and Image::type.
void bmo_similarverts_exec (BMesh * bm, BMOperator * op)
Definition at line 854 of file bmo_utils.c.
References angle_v3v3(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ITER_MESH, BM_mesh_elem_count(), BM_VERT, BM_vert_face_count(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMO_slot_int_get(), CD_MDEFORMVERT, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, MDeformWeight::def_nr, SimSel_VertExt::dvert, MDeformVert::dw, FALSE, BMVert::head, i, indices, MEM_freeN(), MEM_mallocN(), BMVert::no, NULL, SimSel_VertExt::num_faces, RAD2DEGF, SIMVERT_FACE, SIMVERT_NORMAL, SIMVERT_VGROUP, thresh, MDeformVert::totweight, TRUE, SimSel_VertExt::v, BMesh::vdata, and VERT_MARK.
void bmo_solidify_face_region_exec (BMesh * bm, BMOperator * op)
Definition at line 610 of file bmo_extrude.c.
References BM_FACE, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_copy(), BMO_slot_float_get(), calc_solidify_normals(), FACE_MARK, solidify_add_thickness(), and TRUE.
void bmo_spin_exec (BMesh * bm, BMOperator * op)
Spin Operator
Extrude or duplicate geometry a number of times, rotating and possibly translating after each step
Definition at line 467 of file bmo_dupe.c.
References axis_angle_to_mat3(), BMO_op_callf(), BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_bool_get(), BMO_slot_copy(), BMO_slot_float_get(), BMO_slot_int_get(), BMO_slot_vec_get(), DEG2RADF, is_zero_v3(), and normalize_v3().
void bmo_split_exec (BMesh * bm, BMOperator * op)
Definition at line 376 of file bmo_dupe.c.
References BM_ALL, BM_EDGES_OF_MESH, BM_EDGES_OF_VERT, BM_FACES_OF_EDGE, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_slot_bool_get(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_copy(), BMO_slot_int_set(), DEL_FACES, NULL, and SPLIT_INPUT.
void bmo_transform_exec (BMesh * bm, BMOperator * op)
Definition at line 54 of file bmo_utils.c.
References BM_VERT, BMO_ITER, BMO_slot_mat4_get(), BMVert::co, and mul_m4_v3().
void bmo_translate_exec (BMesh * bm, BMOperator * op)
Definition at line 67 of file bmo_utils.c.
References BMO_op_callf(), BMO_slot_vec_get(), copy_v3_v3(), and unit_m4().
void bmo_triangle_fill_exec (BMesh * bm, BMOperator * op)
Definition at line 158 of file bmo_triangulate.c.
References BLI_addfilledge(), BLI_addfillvert(), BLI_begin_edgefill(), BLI_edgefill(), BLI_end_edgefill(), BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_lookup(), BLI_smallhash_release(), BM_EDGE, BM_FACE, BM_face_create_quad_tri(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_initf(), BMO_slot_buffer_flag_enable(), BMO_slot_buffer_from_enabled_flag(), BMVert::co, BMLoop::e, EDGE_MARK, ELE_NEW, FALSE, ScanFillContext::fillfacebase, ListBase::first, hash, ScanFillFace::next, NULL, ScanFillVert::p, ScanFillVert::tmp, TRUE, BMEdge::v1, ScanFillFace::v1, BMEdge::v2, ScanFillFace::v2, and ScanFillFace::v3.
void bmo_triangulate_exec (BMesh * bm, BMOperator * op)
Definition at line 47 of file bmo_triangulate.c.
References BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BM_EDGE, BM_FACE, BM_face_triangulate(), BMO_iter_new(), BMO_iter_step(), BMO_slot_bool_get(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_map_ptr_insert(), EDGE_NEW, FACE_NEW, i, BMFace::len, and NULL.
void bmo_vert_average_facedata_exec (BMesh * bm, BMOperator * op)
Definition at line 304 of file bmo_removedoubles.c.
References BM_ITER_ELEM, BM_LOOPS_OF_VERT, BM_VERT, BMO_ITER, CustomData_bmesh_get_layer_n(), CustomData_data_add(), CustomData_data_copy_value(), CustomData_data_dominmax(), CustomData_data_initminmax(), CustomData_data_multiply(), CustomData_layer_has_math(), BMHeader::data, BMLoop::head, i, CustomData::layers, BMesh::ldata, max, min, CustomData::totlayer, and CustomDataLayer::type.
void bmo_vertex_slide_exec (BMesh * bm, BMOperator * op)
Definition at line 43 of file bmo_slide.c.
References BM_EDGE, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_ITER_ELEM, BM_VERT, BM_vert_in_edge(), BMERR_INVALID_SELECTION, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_error_raise(), BMO_ITER, BMO_iter_new(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_get(), BMVert::co, EDGE_MARK, G, G_DEBUG, BMHeader::htype, interp_v3_v3v3(), and VERT_MARK.
void bmo_vertexshortestpath_exec (BMesh * bm, BMOperator * op)
Definition at line 1174 of file bmo_utils.c.
References BLI_heap_empty(), BLI_heap_free(), BLI_heap_insert(), BLI_heap_new(), BLI_heap_popmin(), BLI_heap_remove(), BM_EDGES_OF_VERT, BM_elem_index_get, BM_elem_index_set, BM_ITER_ELEM, BM_ITER_MESH, BM_mesh_elem_count(), BM_VERT, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_ITER, BMO_slot_buffer_from_enabled_flag(), BMO_slot_int_get(), BMVert::co, BMesh::elem_index_dirty, FLT_MAX, ElemNode::hn, i, if(), len_v3v3(), MEM_freeN(), MEM_mallocN(), NULL, ElemNode::parent, ElemNode::v, BMEdge::v1, BMEdge::v2, VERT_MARK, VPATH_SELECT_EDGE_LENGTH, and ElemNode::weight.
void bmo_vertexsmooth_exec (BMesh * bm, BMOperator * op)
Definition at line 406 of file bmo_utils.c.
References add_v3_v3v3(), BLI_array_declare, BLI_array_free, BLI_array_growone, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_ITER_ELEM, BM_VERT, BMO_ITER, BMO_slot_bool_get(), BMO_slot_float_get(), co, BMVert::co, copy_v3_v3(), cos(), fabsf, i, mid_v3_v3v3(), mul_v3_fl(), and NULL.
void bmo_weldverts_exec (BMesh * bm, BMOperator * op)
Definition at line 99 of file bmo_removedoubles.c.
References BLI_array_count, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growone, BM_edge_create(), BM_edge_exists(), BM_EDGES_OF_MESH, BM_elem_attrs_copy(), BM_elem_flag_merge, BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_create_ngon(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_VERTS_OF_MESH, BMO_elem_flag_enable, BMO_elem_flag_test, BMO_op_callf(), BMO_slot_map_ptr_get(), DEL_ONLYTAGGED, BMLoop::e, EDGE_COL, ELE_DEL, BMesh::elem_index_dirty, FACE_MARK, BMFace::len, BMLoop::next, NULL, remdoubles_splitface(), TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.