Blender: node_shader_layer_weight.c File Reference
node_shader_layer_weight.c File Reference
#include "../node_shader_util.h"
Functions
static int node_shader_gpu_layer_weight (GPUMaterial *UNUSED(mat), bNode *UNUSED(node), GPUNodeStack *UNUSED(in), GPUNodeStack *UNUSED(out))
void register_node_type_sh_layer_weight (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_layer_weight_in []
static bNodeSocketTemplate sh_node_layer_weight_out []
Function Documentation
static int node_shader_gpu_layer_weight (GPUMaterial * UNUSEDmat, bNode * UNUSEDnode, GPUNodeStack * UNUSEDin, GPUNodeStack * UNUSEDout) [static]
Definition at line 43 of file node_shader_layer_weight.c.
Referenced by register_node_type_sh_layer_weight().
void register_node_type_sh_layer_weight (bNodeTreeType * ttype)
Definition at line 49 of file node_shader_layer_weight.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_layer_weight(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_LAYER_WEIGHT.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_layer_weight_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Blend",     0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 32 of file node_shader_layer_weight.c.
bNodeSocketTemplate sh_node_layer_weight_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Fresnel",   0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 0, "Facing",    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 37 of file node_shader_layer_weight.c.