Blender: TriangleDice Class Reference
TriangleDice Class Reference
#include <subd_dice.h>
Classes
struct EdgeFactors
struct SubPatch
Public Member Functions
TriangleDice (Mesh *mesh, int shader, bool smooth, float dicing_rate)
void reserve (EdgeFactors &ef, int M)
float2 map_uv (SubPatch &sub, float2 uv)
int add_vert (SubPatch &sub, float2 uv)
void add_grid (SubPatch &sub, EdgeFactors &ef, int M)
void dice (SubPatch &sub, EdgeFactors &ef)
Detailed Description
Definition at line 129 of file subd_dice.h.
Constructor & Destructor Documentation
TriangleDice::TriangleDice (Mesh * mesh, int shader, bool smooth, float dicing_rate)
Definition at line 323 of file subd_dice.cpp.
Member Function Documentation
void TriangleDice::add_grid (SubPatch & sub, EdgeFactors & ef, int M)
Definition at line 352 of file subd_dice.cpp.
References EdgeDice::add_triangle(), add_vert(), i, interp(), make_float2(), EdgeDice::stitch_triangles(), TriangleDice::EdgeFactors::tu, TriangleDice::EdgeFactors::tv, and TriangleDice::EdgeFactors::tw.
Referenced by dice().
int TriangleDice::add_vert (SubPatch & sub, float2 uv)
Definition at line 347 of file subd_dice.cpp.
References map_uv(), and TriangleDice::SubPatch::patch.
Referenced by add_grid().
void TriangleDice::dice (SubPatch & sub, EdgeFactors & ef)
Definition at line 449 of file subd_dice.cpp.
References add_grid(), assert, M, max, EdgeDice::mesh, reserve(), TriangleDice::EdgeFactors::tu, TriangleDice::EdgeFactors::tv, TriangleDice::EdgeFactors::tw, EdgeDice::vert_offset, and Mesh::verts.
Referenced by DiagSplit::split_triangle().
float2 TriangleDice::map_uv (SubPatch & sub, float2 uv)
Definition at line 341 of file subd_dice.cpp.
References TriangleDice::SubPatch::Pu, TriangleDice::SubPatch::Pv, TriangleDice::SubPatch::Pw, float2::x, and float2::y.
Referenced by add_vert().
void TriangleDice::reserve (EdgeFactors & ef, int M)
Definition at line 328 of file subd_dice.cpp.
References TriangleDice::EdgeFactors::tu, TriangleDice::EdgeFactors::tv, and TriangleDice::EdgeFactors::tw.
Referenced by dice().
The documentation for this class was generated from the following files:
subd_dice.h
subd_dice.cpp