Blender: IMB_indexer.h File Reference
IMB_indexer.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include "BKE_utildefines.h"
#include "IMB_anim.h"
Classes
struct anim_index_entry
struct anim_index
struct anim_index_builder
Typedefs
typedef struct anim_index_entry anim_index_entry
typedef struct anim_index_builder anim_index_builder
Functions
anim_index_builder * IMB_index_builder_create (const char *name)
void IMB_index_builder_add_entry (anim_index_builder *fp, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
void IMB_index_builder_proc_frame (anim_index_builder *fp, unsigned char *buffer, int data_size, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
void IMB_index_builder_finish (anim_index_builder *fp, int rollback)
struct anim_index * IMB_indexer_open (const char *name)
unsigned long long IMB_indexer_get_seek_pos (struct anim_index *idx, int frameno_index)
unsigned long long IMB_indexer_get_seek_pos_dts (struct anim_index *idx, int frameno_index)
int IMB_indexer_get_frame_index (struct anim_index *idx, int frameno)
unsigned long long IMB_indexer_get_pts (struct anim_index *idx, int frame_index)
int IMB_indexer_get_duration (struct anim_index *idx)
int IMB_indexer_can_scan (struct anim_index *idx, int old_frame_index, int new_frame_index)
void IMB_indexer_close (struct anim_index *idx)
void IMB_free_indices (struct anim *anim)
int IMB_anim_index_get_frame_index (struct anim *anim, IMB_Timecode_Type tc, int position)
struct anim * IMB_anim_open_proxy (struct anim *anim, IMB_Proxy_Size preview_size)
struct anim_index * IMB_anim_open_index (struct anim *anim, IMB_Timecode_Type tc)
int IMB_proxy_size_to_array_index (IMB_Proxy_Size pr_size)
int IMB_timecode_to_array_index (IMB_Timecode_Type tc)
Typedef Documentation
typedef struct anim_index_builder anim_index_builder
typedef struct anim_index_entry anim_index_entry
Function Documentation
int IMB_anim_index_get_frame_index (struct anim * anim, IMB_Timecode_Type tc, int position)
Definition at line 1253 of file indexer.c.
References IMB_anim_open_index(), and IMB_indexer_get_frame_index().
struct anim_index* IMB_anim_open_index (struct anim * anim, IMB_Timecode_Type tc) [read]
Definition at line 1230 of file indexer.c.
References anim::curr_idx, FILE_MAX, get_tc_filename(), i, IMB_indexer_open(), IMB_timecode_to_array_index(), anim::indices_tried, and NULL.
Referenced by avi_fetchibuf(), IMB_anim_get_duration(), and IMB_anim_index_get_frame_index().
struct anim* IMB_anim_open_proxy (struct anim * anim, IMB_Proxy_Size preview_size) [read]
Definition at line 1207 of file indexer.c.
References FALSE, FILE_MAX, get_proxy_filename(), i, IMB_open_anim(), IMB_proxy_size_to_array_index(), NULL, anim::proxies_tried, and anim::proxy_anim.
Referenced by IMB_anim_absolute().
void IMB_free_indices (struct anim * anim)
Definition at line 1174 of file indexer.c.
References anim::curr_idx, i, IMB_close_anim(), IMB_indexer_close(), IMB_PROXY_MAX_SLOT, IMB_TC_MAX_SLOT, anim::indices_tried, NULL, anim::proxies_tried, and anim::proxy_anim.
Referenced by IMB_anim_set_index_dir(), IMB_close_anim_proxies(), and IMB_free_anim().
void IMB_index_builder_add_entry (anim_index_builder * fp, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
Definition at line 99 of file indexer.c.
References anim_index_builder::fp.
Referenced by IMB_index_builder_proc_frame(), and write_index().
anim_index_builder* IMB_index_builder_create (const char * name)
Definition at line 68 of file indexer.c.
References B_ENDIAN, BLI_fopen(), BLI_make_existing_file(), BLI_strncpy(), ENDIAN_ORDER, anim_index_builder::fp, INDEX_FILE_VERSION, magic, MEM_callocN(), MEM_freeN(), anim_index_builder::name, NULL, temp_ext, and anim_index_builder::temp_name.
void IMB_index_builder_finish (anim_index_builder * fp, int rollback)
Definition at line 132 of file indexer.c.
References BLI_rename(), anim_index_builder::delete_priv_data, anim_index_builder::fp, MEM_freeN(), anim_index_builder::name, and anim_index_builder::temp_name.
void IMB_index_builder_proc_frame (anim_index_builder * fp, unsigned char * buffer, int data_size, int frameno, unsigned long long seek_pos, unsigned long long seek_pos_dts, unsigned long long pts)
Definition at line 110 of file indexer.c.
References anim_index_entry::frameno, IMB_index_builder_add_entry(), anim_index_builder::proc_frame, anim_index_entry::pts, anim_index_entry::seek_pos, and anim_index_entry::seek_pos_dts.
int IMB_indexer_can_scan (struct anim_index * idx, int old_frame_index, int new_frame_index)
Definition at line 299 of file indexer.c.
References IMB_indexer_get_seek_pos().
Referenced by avi_fetchibuf().
void IMB_indexer_close (struct anim_index * idx)
Definition at line 309 of file indexer.c.
References anim_index::entries, and MEM_freeN().
Referenced by IMB_free_indices().
int IMB_indexer_get_duration (struct anim_index * idx)
Definition at line 291 of file indexer.c.
References anim_index::entries, anim_index_entry::frameno, and anim_index::num_entries.
Referenced by IMB_anim_get_duration().
int IMB_indexer_get_frame_index (struct anim_index * idx, int frameno)
Definition at line 246 of file indexer.c.
References anim_index::entries, anim_index_entry::frameno, len(), and anim_index::num_entries.
Referenced by avi_fetchibuf(), and IMB_anim_index_get_frame_index().
unsigned long long IMB_indexer_get_pts (struct anim_index * idx, int frame_index)
Definition at line 279 of file indexer.c.
References anim_index::entries, anim_index::num_entries, and anim_index_entry::pts.
Referenced by avi_fetchibuf().
unsigned long long IMB_indexer_get_seek_pos (struct anim_index * idx, int frameno_index)
Definition at line 222 of file indexer.c.
References anim_index::entries, anim_index::num_entries, and anim_index_entry::seek_pos.
Referenced by avi_fetchibuf(), and IMB_indexer_can_scan().
unsigned long long IMB_indexer_get_seek_pos_dts (struct anim_index * idx, int frameno_index)
Definition at line 234 of file indexer.c.
References anim_index::entries, anim_index::num_entries, and anim_index_entry::seek_pos_dts.
Referenced by avi_fetchibuf().
struct anim_index* IMB_indexer_open (const char * name) [read]
Definition at line 151 of file indexer.c.
References B_ENDIAN, BLI_fopen(), BLI_strncpy(), ENDIAN_ORDER, anim_index::entries, anim_index_entry::frameno, fseek, ftell, i, INDEX_FILE_VERSION, magic, MEM_callocN(), anim_index::name, NULL, anim_index::num_entries, anim_index_entry::pts, anim_index_entry::seek_pos, anim_index_entry::seek_pos_dts, SWITCH_INT, and SWITCH_INT64.
Referenced by IMB_anim_open_index().
int IMB_proxy_size_to_array_index (IMB_Proxy_Size pr_size)
Definition at line 315 of file indexer.c.
References IMB_PROXY_100, IMB_PROXY_25, IMB_PROXY_50, IMB_PROXY_75, and IMB_PROXY_NONE.
Referenced by get_proxy_filename(), and IMB_anim_open_proxy().
int IMB_timecode_to_array_index (IMB_Timecode_Type tc)
Definition at line 335 of file indexer.c.
References IMB_TC_FREE_RUN, IMB_TC_INTERPOLATED_REC_DATE_FREE_RUN, IMB_TC_NONE, IMB_TC_RECORD_RUN, and IMB_TC_RECORD_RUN_NO_GAPS.
Referenced by get_tc_filename(), and IMB_anim_open_index().