Blender: interface_intern.h File Reference
interface_intern.h File Reference
interface
#include "UI_resources.h"
#include "RNA_types.h"
Classes
struct uiLinkLine
struct uiLink
struct uiBut
struct uiBlock
struct uiSafetyRct
struct uiPopupBlockHandle
Defines
#define UI_PANEL_MINX 100
#define UI_PANEL_MINY 70
#define UI_SELECT 1
#define UI_SCROLLED 2
#define UI_ACTIVE 4
#define UI_HAS_ICON 8
#define UI_TEXTINPUT 16
#define UI_HIDDEN 32
#define PNL_GRID (UI_UNIT_Y / 5)
#define PNL_HEADER (UI_UNIT_Y + 4)
#define PNL_SELECT 1
#define PNL_CLOSEDX 2
#define PNL_CLOSEDY 4
#define PNL_CLOSED 6
#define PNL_OVERLAP 16
#define EXTEND_LEFT 1
#define EXTEND_RIGHT 2
#define SCOPE_RESIZE_PAD 9
#define UI_TRANSP_DARK 100
#define UI_TRANSP_LIGHT 160
Typedefs
typedef struct uiLinkLine uiLinkLine
typedef struct uiSafetyRct uiSafetyRct
typedef uiBlock *(* uiBlockHandleCreateFunc)(struct bContext *C, struct uiPopupBlockHandle *handle, void *arg1)
Enumerations
enum uiWidgetTypeEnum {
UI_WTYPE_REGULAR, UI_WTYPE_LABEL, UI_WTYPE_TOGGLE, UI_WTYPE_OPTION,
UI_WTYPE_RADIO, UI_WTYPE_NUMBER, UI_WTYPE_SLIDER, UI_WTYPE_EXEC,
UI_WTYPE_TOOLTIP, UI_WTYPE_NAME, UI_WTYPE_NAME_LINK, UI_WTYPE_POINTER_LINK,
UI_WTYPE_FILENAME, UI_WTYPE_MENU_RADIO, UI_WTYPE_MENU_ICON_RADIO, UI_WTYPE_MENU_POINTER_LINK,
UI_WTYPE_MENU_NODE_LINK, UI_WTYPE_PULLDOWN, UI_WTYPE_MENU_ITEM, UI_WTYPE_MENU_BACK,
UI_WTYPE_ICON, UI_WTYPE_SWATCH, UI_WTYPE_RGB_PICKER, UI_WTYPE_NORMAL,
UI_WTYPE_BOX, UI_WTYPE_SCROLL, UI_WTYPE_LISTITEM, UI_WTYPE_PROGRESSBAR
}
Functions
void ui_delete_linkline (uiLinkLine *line, uiBut *but)
void ui_fontscale (short *points, float aspect)
void ui_block_to_window_fl (const struct ARegion *ar, uiBlock *block, float *x, float *y)
void ui_block_to_window (const struct ARegion *ar, uiBlock *block, int *x, int *y)
void ui_block_to_window_rct (const struct ARegion *ar, uiBlock *block, rctf *graph, rcti *winr)
void ui_window_to_block_fl (const struct ARegion *ar, uiBlock *block, float *x, float *y)
void ui_window_to_block (const struct ARegion *ar, uiBlock *block, int *x, int *y)
void ui_window_to_region (const ARegion *ar, int *x, int *y)
double ui_get_but_val (uiBut *but)
void ui_set_but_val (uiBut *but, double value)
void ui_set_but_hsv (uiBut *but)
void ui_get_but_vectorf (uiBut *but, float vec[3])
void ui_set_but_vectorf (uiBut *but, const float vec[3])
void ui_hsvcircle_vals_from_pos (float *valrad, float *valdist, rcti *rect, float mx, float my)
void ui_get_but_string (uiBut *but, char *str, size_t maxlen)
void ui_convert_to_unit_alt_name (uiBut *but, char *str, size_t maxlen)
int ui_set_but_string (struct bContext *C, uiBut *but, const char *str)
int ui_get_but_string_max_length (uiBut *but)
int ui_set_but_string_eval_num (struct bContext *C, uiBut *but, const char *str, double *value)
void ui_set_but_default (struct bContext *C, short all)
void ui_set_but_soft_range (uiBut *but, double value)
void ui_check_but (uiBut *but)
int ui_is_but_float (uiBut *but)
int ui_is_but_unit (uiBut *but)
int ui_is_but_rna_valid (uiBut *but)
int ui_is_but_utf8 (uiBut *but)
void ui_bounds_block (uiBlock *block)
void ui_block_translate (uiBlock *block, int x, int y)
void ui_block_do_align (uiBlock *block)
uiBlock * ui_block_func_COL (struct bContext *C, uiPopupBlockHandle *handle, void *arg_but)
void ui_block_func_ICONROW (struct bContext *C, uiLayout *layout, void *arg_but)
void ui_block_func_ICONTEXTROW (struct bContext *C, uiLayout *layout, void *arg_but)
struct ARegion * ui_tooltip_create (struct bContext *C, struct ARegion *butregion, uiBut *but)
void ui_tooltip_free (struct bContext *C, struct ARegion *ar)
uiBut * ui_popup_menu_memory (struct uiBlock *block, struct uiBut *but)
float * ui_block_hsv_get (struct uiBlock *block)
void ui_popup_block_scrolltest (struct uiBlock *block)
ARegion * ui_searchbox_create (struct bContext *C, struct ARegion *butregion, uiBut *but)
int ui_searchbox_inside (struct ARegion *ar, int x, int y)
void ui_searchbox_update (struct bContext *C, struct ARegion *ar, uiBut *but, int reset)
void ui_searchbox_autocomplete (struct bContext *C, struct ARegion *ar, uiBut *but, char *str)
void ui_searchbox_event (struct bContext *C, struct ARegion *ar, uiBut *but, struct wmEvent *event)
void ui_searchbox_apply (uiBut *but, struct ARegion *ar)
void ui_searchbox_free (struct bContext *C, struct ARegion *ar)
void ui_but_search_test (uiBut *but)
uiPopupBlockHandle * ui_popup_block_create (struct bContext *C, struct ARegion *butregion, uiBut *but, uiBlockCreateFunc create_func, uiBlockHandleCreateFunc handle_create_func, void *arg)
uiPopupBlockHandle * ui_popup_menu_create (struct bContext *C, struct ARegion *butregion, uiBut *but, uiMenuCreateFunc create_func, void *arg, char *str)
void ui_popup_block_free (struct bContext *C, uiPopupBlockHandle *handle)
void ui_set_name_menu (uiBut *but, int value)
int ui_step_name_menu (uiBut *but, int step)
int ui_handler_panel_region (struct bContext *C, struct wmEvent *event)
void ui_draw_aligned_panel (struct uiStyle *style, uiBlock *block, rcti *rect)
void ui_dropshadow (rctf *rct, float radius, float aspect, int select)
void ui_draw_gradient (rcti *rect, const float hsv[3], int type, float alpha)
void ui_draw_but_HISTOGRAM (ARegion *ar, uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_draw_but_WAVEFORM (ARegion *ar, uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_draw_but_VECTORSCOPE (ARegion *ar, uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_draw_but_COLORBAND (uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_draw_but_NORMAL (uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_draw_but_CURVE (ARegion *ar, uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_draw_but_IMAGE (ARegion *ar, uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_draw_but_TRACKPREVIEW (ARegion *ar, uiBut *but, struct uiWidgetColors *wcol, rcti *rect)
void ui_button_activate_do (struct bContext *C, struct ARegion *ar, uiBut *but)
void ui_button_active_free (const struct bContext *C, uiBut *but)
int ui_button_is_active (struct ARegion *ar)
void ui_draw_anti_tria (float x1, float y1, float x2, float y2, float x3, float y3)
void ui_draw_anti_roundbox (int mode, float minx, float miny, float maxx, float maxy, float rad)
void ui_draw_menu_back (struct uiStyle *style, uiBlock *block, rcti *rect)
uiWidgetColors * ui_tooltip_get_theme (void)
void ui_draw_tooltip_background (uiStyle *UNUSED(style), uiBlock *block, rcti *rect)
void ui_draw_search_back (struct uiStyle *style, uiBlock *block, rcti *rect)
int ui_link_bezier_points (rcti *rect, float coord_array[][2], int resol)
void ui_draw_link_bezier (rcti *rect)
void ui_draw_but (const struct bContext *C, ARegion *ar, struct uiStyle *style, uiBut *but, rcti *rect)
void ui_widget_color_init (struct ThemeUI *tui)
void ui_draw_menu_item (struct uiFontStyle *fstyle, rcti *rect, const char *name, int iconid, int state)
void ui_draw_preview_item (struct uiFontStyle *fstyle, rcti *rect, const char *name, int iconid, int state)
void uiStyleInit (void)
int ui_id_icon_get (struct bContext *C, struct ID *id, int preview)
void init_userdef_do_versions (void)
void ui_theme_init_default (void)
void ui_resources_init (void)
void ui_resources_free (void)
void ui_layout_add_but (uiLayout *layout, uiBut *but)
int ui_but_can_align (uiBut *but)
void ui_but_add_search (uiBut *but, PointerRNA *ptr, PropertyRNA *prop, PointerRNA *searchptr, PropertyRNA *searchprop)
void ui_but_add_shortcut (uiBut *but, const char *key_str, const short do_strip)
void ui_but_anim_flag (uiBut *but, float cfra)
void ui_but_anim_insert_keyframe (struct bContext *C)
void ui_but_anim_delete_keyframe (struct bContext *C)
void ui_but_anim_add_driver (struct bContext *C)
void ui_but_anim_remove_driver (struct bContext *C)
void ui_but_anim_copy_driver (struct bContext *C)
void ui_but_anim_paste_driver (struct bContext *C)
void ui_but_anim_add_keyingset (struct bContext *C)
void ui_but_anim_remove_keyingset (struct bContext *C)
int ui_but_anim_expression_get (uiBut *but, char *str, size_t maxlen)
int ui_but_anim_expression_set (uiBut *but, const char *str)
int ui_but_anim_expression_create (uiBut *but, const char *str)
void ui_but_anim_autokey (struct bContext *C, uiBut *but, struct Scene *scene, float cfra)
Variables
unsigned char checker_stipple_sml []
Detailed Description
Definition in file interface_intern.h.
Define Documentation
#define EXTEND_LEFT 1
Definition at line 128 of file interface_intern.h.
Referenced by ui_textedit_move(), and ui_textedit_set_cursor_select().
#define EXTEND_RIGHT 2
Definition at line 129 of file interface_intern.h.
Referenced by ui_textedit_move(), and ui_textedit_set_cursor_select().
#define PNL_CLOSED 6
Definition at line 122 of file interface_intern.h.
Referenced by ui_handle_panel_header(), ui_handler_panel_region(), uiAlignPanelStep(), and uiBeginPanel().
#define PNL_CLOSEDX 2
Definition at line 120 of file interface_intern.h.
Referenced by check_panel_overlap(), get_panel_real_ofsx(), ui_draw_aligned_panel(), ui_handle_panel_header(), ui_handler_panel_region(), uiAlignPanelStep(), and uiBeginPanel().
#define PNL_CLOSEDY 4
Definition at line 121 of file interface_intern.h.
Referenced by check_panel_overlap(), get_panel_real_ofsy(), ui_draw_aligned_panel(), ui_handle_panel_header(), ui_handler_panel_region(), uiAlignPanelStep(), and uiBeginPanel().
#define PNL_GRID (UI_UNIT_Y / 5)
Definition at line 115 of file interface_intern.h.
Referenced by ui_do_drag().
#define PNL_HEADER (UI_UNIT_Y + 4)
Definition at line 116 of file interface_intern.h.
Referenced by get_panel_header(), get_panel_size_y(), ui_draw_aligned_panel(), ui_draw_panel_scalewidget(), and ui_handler_panel_region().
#define PNL_OVERLAP 16
Definition at line 124 of file interface_intern.h.
Referenced by check_panel_overlap().
#define PNL_SELECT 1
Definition at line 119 of file interface_intern.h.
Referenced by panel_activate_state(), ui_draw_aligned_panel(), uiAlignPanelStep(), and uiDrawPanels().
#define SCOPE_RESIZE_PAD 9
Definition at line 132 of file interface_intern.h.
Referenced by draw_scope_end(), in_scope_resize_zone(), ui_draw_but_HISTOGRAM(), and ui_draw_but_TRACKPREVIEW().
#define UI_ACTIVE 4
Definition at line 108 of file interface_intern.h.
Referenced by button_activate_exit(), button_activate_init(), ui_draw_preview_item(), ui_handle_button_event(), ui_searchbox_region_draw_cb(), uiIDContextProperty(), widget_draw_icon(), widget_pulldownbut(), widget_state(), widget_state_menu_item(), and widget_state_pulldown().
#define UI_HAS_ICON 8
Definition at line 109 of file interface_intern.h.
Referenced by template_ID(), ui_check_but_and_iconize(), ui_def_but_rna(), ui_draw_but(), ui_text_leftclip(), ui_textedit_set_cursor_pos(), uiDefIconBlockBut(), uiDefIconMenuBut(), uiDefIconTextBlockBut(), uiDefIconTextMenuBut(), uiDefSearchBut(), and widget_draw_text_icon().
#define UI_HIDDEN 32
Definition at line 111 of file interface_intern.h.
Referenced by picker_new_hide_reveal(), ui_but_find_mouse_over(), ui_menu_block_set_keyaccels(), and uiDrawBlock().
#define UI_PANEL_MINX 100
Definition at line 102 of file interface_intern.h.
Referenced by ui_do_drag().
#define UI_PANEL_MINY 70
Definition at line 103 of file interface_intern.h.
Referenced by ui_do_drag().
#define UI_SCROLLED 2
Definition at line 107 of file interface_intern.h.
Referenced by ui_but_find_mouse_over(), ui_menu_scroll(), ui_popup_block_scrolltest(), and uiDrawBlock().
#define UI_SELECT 1
Definition at line 106 of file interface_intern.h.
Referenced by button_activate_exit(), button_activate_state(), ui_add_link(), ui_check_but(), ui_delete_active_linkline(), ui_do_but_BUT(), ui_do_but_LINK(), ui_draw_linkline(), ui_handle_button_event(), ui_is_but_sel(), widget_draw_icon(), widget_link(), widget_numbut(), widget_numslider(), widget_optionbut(), widget_scroll(), widget_state(), widget_state_label(), widget_state_numslider(), widget_state_option_menu(), and widget_textbut().
#define UI_TEXTINPUT 16
Definition at line 110 of file interface_intern.h.
Referenced by ui_draw_but(), widget_numbut(), and widget_numslider().
#define UI_TRANSP_DARK 100
Definition at line 485 of file interface_intern.h.
Referenced by ui_draw_but_COLORBAND(), and widgetbase_draw().
#define UI_TRANSP_LIGHT 160
Definition at line 486 of file interface_intern.h.
Referenced by ui_draw_but_COLORBAND(), and widgetbase_draw().
Typedef Documentation
typedef uiBlock*(* uiBlockHandleCreateFunc)(struct bContext *C, struct uiPopupBlockHandle *handle, void *arg1)
Definition at line 428 of file interface_intern.h.
typedef struct uiLinkLine uiLinkLine
typedef struct uiSafetyRct uiSafetyRct
Enumeration Type Documentation
enum uiWidgetTypeEnum
Enumerator:
UI_WTYPE_REGULAR
UI_WTYPE_LABEL
UI_WTYPE_TOGGLE
UI_WTYPE_OPTION
UI_WTYPE_RADIO
UI_WTYPE_NUMBER
UI_WTYPE_SLIDER
UI_WTYPE_EXEC
UI_WTYPE_TOOLTIP
UI_WTYPE_NAME
UI_WTYPE_NAME_LINK
UI_WTYPE_POINTER_LINK
UI_WTYPE_FILENAME
UI_WTYPE_MENU_RADIO
UI_WTYPE_MENU_ICON_RADIO
UI_WTYPE_MENU_POINTER_LINK
UI_WTYPE_MENU_NODE_LINK
UI_WTYPE_PULLDOWN
UI_WTYPE_MENU_ITEM
UI_WTYPE_MENU_BACK
UI_WTYPE_ICON
UI_WTYPE_SWATCH
UI_WTYPE_RGB_PICKER
UI_WTYPE_NORMAL
UI_WTYPE_BOX
UI_WTYPE_SCROLL
UI_WTYPE_LISTITEM
UI_WTYPE_PROGRESSBAR
Definition at line 59 of file interface_intern.h.
Function Documentation
void init_userdef_do_versions (void)
Definition at line 1179 of file resources.c.
References ThemeSpace::act_marker, ThemeSpace::act_spline, ThemeSpace::audio, AUTOKEY_FLAG_ONLYKEYINGSET, ThemeSpace::back, BEZT_IPO_BEZ, BLI_addtail(), BLI_findstring(), BLI_strncpy(), BLI_system_temporary_dir(), ThemeSpace::bone_pose, ThemeSpace::bone_solid, ThemeSpace::bundle_solid, ThemeSpace::camera_path, ThemeSpace::cframe, ThemeSpace::dis_marker, ThemeSpace::ds_channel, ThemeSpace::ds_subchannel, ThemeSpace::edge_crease, ThemeSpace::edge_seam, ThemeSpace::edge_select, ThemeSpace::edge_sharp, ThemeSpace::editmesh_active, ThemeSpace::effect, ThemeSpace::extra_edge_len, ThemeSpace::extra_face_angle, ThemeSpace::extra_face_area, ThemeSpace::face_dot, ThemeSpace::facedot_size, G, ThemeSpace::grid, ThemeSpace::group, ThemeSpace::group_active, ThemeSpace::handle_align, ThemeSpace::handle_auto, ThemeSpace::handle_auto_clamped, ThemeSpace::handle_free, ThemeSpace::handle_sel_align, ThemeSpace::handle_sel_auto, ThemeSpace::handle_sel_auto_clamped, ThemeSpace::handle_sel_free, ThemeSpace::handle_sel_vect, ThemeSpace::handle_vect, ThemeSpace::handle_vertex, ThemeSpace::handle_vertex_select, ThemeSpace::handle_vertex_size, HD_AUTO, HD_AUTO_ANIM, uiPanelColors::header, ThemeUI::icon_alpha, wmKeyMap::idname, ThemeSpace::image, init_colorband(), uiWidgetColors::inner, uiWidgetColors::item, ThemeSpace::lamp, ThemeSpace::lastsel_point, ThemeSpace::lock_marker, ThemeSpace::marker, ThemeSpace::marker_outline, ThemeSpace::match, MEM_callocN(), ThemeSpace::meta, module, bAddon::module, ThemeSpace::movie, ThemeSpace::movieclip, NDOF_LOCK_HORIZON, NDOF_SHOULD_PAN, NDOF_SHOULD_ROTATE, NDOF_SHOULD_ZOOM, bTheme::next, wmKeyMap::next, ThemeSpace::noodle_curving, ThemeSpace::normal, NULL, uiWidgetColors::outline, ThemeSpace::outline_width, ThemeUI::panel, ThemeSpace::path_after, ThemeSpace::path_before, ThemeSpace::plugin, ThemeSpace::preview_stitch_active, ThemeSpace::preview_stitch_edge, ThemeSpace::preview_stitch_face, ThemeSpace::preview_stitch_stitchable, ThemeSpace::preview_stitch_unstitchable, ThemeSpace::preview_stitch_vert, rgba_char_args_set(), rgba_char_args_set_fl, ThemeSpace::scene, ThemeSpace::sel_marker, ThemeSpace::selected_highlight, ThemeSpace::shade1, ThemeWireColor::solid, ThemeSpace::speaker, ThemeSpace::strip, ThemeSpace::strip_select, Main::subversionfile, ThemeSpace::syntaxb, ThemeSpace::syntaxc, ThemeSpace::syntaxl, ThemeSpace::syntaxn, ThemeSpace::syntaxv, bTheme::tact, bTheme::tarm, bTheme::tclip, bTheme::text, uiWidgetColors::text, bTheme::tima, bTheme::tinfo, bTheme::tipo, bTheme::tlogic, bTheme::tnla, bTheme::tnode, bTheme::toops, ThemeSpace::transition, bTheme::tseq, bTheme::ttime, bTheme::tui, bTheme::tuserpref, bTheme::tv3d, ui_theme_init_boneColorSets(), ui_theme_init_new(), ui_widget_color_init(), USER_ADD_EDITMODE, USER_ADD_VIEWALIGNED, USER_CUSTOM_RANGE, USER_DISABLE_VBO, USER_DRAW_AUTOMATIC, USER_DRAW_TRIPLE, USER_DUP_ARM, USER_GLOBALUNDO, USER_LMOUSESELECT, USER_PLAINMENUS, USER_SHOW_ROTVIEWICON, USER_TWOBUTTONMOUSE, vDM_ColorBand_store(), Main::versionfile, ThemeSpace::vertex, ThemeSpace::vertex_normal, ThemeSpace::vertex_select, ThemeSpace::vertex_size, ThemeUI::wcol_menu_back, ThemeUI::wcol_menu_item, ThemeUI::wcol_num, ThemeUI::wcol_progress, wcol_progress, and ThemeUI::wcol_tooltip.
Referenced by UI_init_userdef().
void ui_block_do_align (uiBlock * block)
Definition at line 2502 of file interface.c.
References uiBut::alignnr, uiBlock::buttons, ListBase::first, uiBut::next, and ui_block_do_align_but().
Referenced by uiEndBlock().
uiBlock* ui_block_func_COL (struct bContext * C, uiPopupBlockHandle * handle, void * arg_but)
Definition at line 2195 of file interface_regions.c.
References BLI_PR_NONE, uiBlock::block_event_func, uiBlock::color_profile, copy_v3_v3(), uiBlock::direction, uiBut::editvec, uiBlock::flag, PROP_COLOR_GAMMA, uiPopupBlockHandle::region, uiPopupBlockHandle::retvec, RNA_property_subtype(), uiBut::rnapoin, uiBut::rnaprop, UI_BLOCK_KEEP_OPEN, UI_BLOCK_LOOP, UI_BLOCK_MOVEMOUSE_QUIT, UI_BLOCK_OUT_1, UI_BLOCK_REDRAW, UI_EMBOSS, ui_picker_small_wheel_cb(), UI_TOP, uiBeginBlock(), uiBlockPicker(), uiBlockSetFlag(), and uiBoundsBlock().
Referenced by ui_blockopen_begin().
void ui_block_func_ICONROW (struct bContext * C, uiLayout * layout, void * arg_but)
Referenced by ui_blockopen_begin().
void ui_block_func_ICONTEXTROW (struct bContext * C, uiLayout * layout, void * arg_but)
Referenced by ui_blockopen_begin().
float* ui_block_hsv_get (struct uiBlock * block)
Definition at line 2739 of file interface_regions.c.
References uiBlock::_hsv.
Referenced by do_hsv_rna_cb(), ui_do_but_BLOCK(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_draw_but_HSVCIRCLE(), ui_draw_but_HSVCUBE(), ui_ndofedit_but_HSVCIRCLE(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCIRCLE(), ui_numedit_but_HSVCUBE(), ui_picker_small_wheel_cb(), ui_set_but_hsv(), ui_update_block_buts_rgb(), and uiBlockPicker().
void ui_block_to_window (const struct ARegion * ar, uiBlock * block, int * x, int * y)
void ui_block_to_window_fl (const struct ARegion * ar, uiBlock * block, float * x, float * y)
void ui_block_to_window_rct (const struct ARegion * ar, uiBlock * block, rctf * graph, rcti * winr)
void ui_block_translate (uiBlock * block, int x, int y)
Definition at line 197 of file interface.c.
References uiBlock::buttons, ListBase::first, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, uiBut::next, uiBut::x1, uiBut::x2, uiBut::y1, and uiBut::y2.
Referenced by ui_centered_bounds_block(), and ui_popup_bounds_block().
void ui_bounds_block (uiBlock * block)
Definition at line 258 of file interface.c.
References uiBlock::bounds, uiBlock::buttons, ListBase::first, MAX2, uiBlock::maxx, uiBlock::maxy, uiBlock::minbounds, uiBlock::minx, uiBlock::miny, uiBut::next, NULL, uiBlock::panel, uiBlock::safety, Panel::sizex, Panel::sizey, uiBut::str, uiBut::x1, uiBut::x2, rctf::xmax, rctf::xmin, uiBut::y1, uiBut::y2, rctf::ymax, and rctf::ymin.
Referenced by ui_centered_bounds_block(), ui_offset_panel_block(), ui_popup_bounds_block(), and uiEndBlock().
void ui_but_add_search (uiBut * but, PointerRNA * ptr, PropertyRNA * prop, PointerRNA * searchptr, PropertyRNA * searchprop)
Definition at line 1350 of file interface_layout.c.
References uiBut::flag, uiBut::hardmax, MAX2, NULL, PROP_POINTER, RNA_property_pointer_type(), RNA_property_type(), rna_search_cb(), uiBut::rnasearchpoin, uiBut::rnasearchprop, search_id_collection(), SEARCH_MENU, uiBut::type, UI_ICON_LEFT, UI_TEXT_LEFT, and uiButSetSearchFunc().
Referenced by uiItemFullR(), and uiItemPointerR().
void ui_but_add_shortcut (uiBut * but, const char * key_str, const short do_strip)
Definition at line 806 of file interface.c.
References BLI_snprintf(), BLI_strdup(), MEM_freeN(), uiBut::str, uiBut::strdata, and ui_check_but().
Referenced by but_shortcut_name_func(), and ui_menu_block_set_keymaps().
void ui_but_anim_add_driver (struct bContext * C)
Definition at line 215 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_add_keyingset (struct bContext * C)
Definition at line 239 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_autokey (struct bContext * C, uiBut * but, struct Scene * scene, float cfra)
Definition at line 179 of file interface_anim.c.
References ANIM_get_keyframing_flags(), FCurve::array_index, autokeyframe_cfra_can_key(), CTX_wm_reports(), PointerRNA::data, FCURVE_SELECTED, FCurve::flag, FCurve::grp, PointerRNA::id, insert_keyframe(), NA_EDITED, bActionGroup::name, NC_ANIMATION, ND_KEYFRAME, NULL, FCurve::rna_path, uiBut::rnapoin, ui_but_get_fcurve(), and WM_event_add_notifier().
Referenced by ui_apply_autokey_undo().
void ui_but_anim_copy_driver (struct bContext * C)
Definition at line 227 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
void ui_but_anim_delete_keyframe (struct bContext * C)
Definition at line 209 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
int ui_but_anim_expression_create (uiBut * but, const char * str)
Definition at line 128 of file interface_anim.c.
References BLI_strncpy_utf8(), uiBut::block, C, PointerRNA::data, FCurve::driver, DRIVER_FLAG_RECOMPILE, DRIVER_TYPE_PYTHON, ELEM, uiBlock::evil_C, ChannelDriver::expression, ChannelDriver::flag, G, G_DEBUG, GS, PointerRNA::id, ID_MA, ID_TE, if(), MEM_freeN(), ID::name, NC_ANIMATION, ND_KEYFRAME, NULL, RNA_path_from_ID_to_property(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, ChannelDriver::type, verify_driver_fcurve(), and WM_event_add_notifier().
Referenced by ui_set_but_string().
int ui_but_anim_expression_get (uiBut * but, char * str, size_t maxlen)
Definition at line 85 of file interface_anim.c.
References BLI_strncpy(), FCurve::driver, DRIVER_TYPE_PYTHON, ChannelDriver::expression, NULL, ChannelDriver::type, and ui_but_get_fcurve().
Referenced by ui_get_but_string(), and ui_tooltip_create().
int ui_but_anim_expression_set (uiBut * but, const char * str)
Definition at line 105 of file interface_anim.c.
References BLI_strncpy_utf8(), uiBut::block, FCurve::driver, DRIVER_FLAG_RECOMPILE, DRIVER_TYPE_PYTHON, uiBlock::evil_C, ChannelDriver::expression, ChannelDriver::flag, NC_ANIMATION, ND_KEYFRAME, NULL, ChannelDriver::type, ui_but_get_fcurve(), and WM_event_add_notifier().
Referenced by ui_set_but_string().
void ui_but_anim_flag (uiBut * but, float cfra)
Definition at line 63 of file interface_anim.c.
References fcurve_frame_has_keyframe(), uiBut::flag, NULL, UI_BUT_ANIMATED, UI_BUT_ANIMATED_KEY, UI_BUT_DRIVEN, and ui_but_get_fcurve().
Referenced by uiContextAnimUpdate(), and uiEndBlock().
void ui_but_anim_insert_keyframe (struct bContext * C)
Definition at line 203 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_paste_driver (struct bContext * C)
Definition at line 233 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
void ui_but_anim_remove_driver (struct bContext * C)
Definition at line 221 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
void ui_but_anim_remove_keyingset (struct bContext * C)
Definition at line 245 of file interface_anim.c.
References NULL, WM_OP_INVOKE_DEFAULT, and WM_operator_name_call().
Referenced by ui_do_button().
int ui_but_can_align (uiBut * but)
Definition at line 2363 of file interface.c.
References ELEM3, LABEL, OPTION, OPTIONN, and uiBut::type.
Referenced by ui_def_but(), and ui_item_align().
void ui_but_search_test (uiBut * but)
Definition at line 1218 of file interface_regions.c.
References uiBut::block, uiBut::drawstr, uiBlock::evil_C, uiBut::hardmax, uiSearchItems::maxitem, uiSearchItems::maxstrlen, MEM_callocN(), MEM_freeN(), uiSearchItems::more, uiSearchItems::names, PROP_STRING, RNA_property_type(), uiBut::rnaprop, uiBut::search_arg, uiBut::search_func, uiSearchItems::totitem, UI_BUT_REDALERT, and uiButSetFlag().
Referenced by uiButSetSearchFunc().
void ui_button_activate_do (struct bContext * C, struct ARegion * ar, uiBut * but)
Definition at line 5502 of file interface_handlers.c.
References uiBut::block, button_activate_init(), BUTTON_ACTIVATE_OVER, CTX_wm_window(), wmWindow::eventstate, EVT_BUT_OPEN, FALSE, KM_PRESS, and ui_do_button().
Referenced by uiButActiveOnly().
void ui_button_active_free (const struct bContext * C, uiBut * but)
int ui_button_is_active (struct ARegion * ar)
Definition at line 4816 of file interface_handlers.c.
References NULL, and ui_but_find_activated().
Referenced by ui_handler_panel_region().
void ui_check_but (uiBut * but)
Definition at line 2143 of file interface.c.
References BLI_snprintf(), BLI_strncpy(), BUT_TOGDUAL, uiBut::drawstr, uiBut::editstr, uiBut::editval, uiBut::editvec, fabs(), uiBut::flag, FLT_MAX, uiBut::hardmax, uiBut::hardmin, HOTKEYEVT, HSVCIRCLE, HSVCUBE, HSVSLI, uiBut::iconadd, ICONROW, ICONTEXTROW, ICONTOG, ICONTOGN, IDPOIN, KEYEVT, KM_ALT, KM_CTRL, KM_OSKEY, KM_SHIFT, LABEL, MENU, uiBut::modifier_key, NUM, NUMABS, NUMSLI, PROP_ICONS_CONSECUTIVE, PROP_PERCENTAGE, RNA_property_flag(), RNA_property_subtype(), uiBut::rnaprop, SCROLL, SEARCH_MENU, SLI, uiBut::str, strlen(), TEX, TRUE, uiBut::type, ui_but_float_precision(), UI_BUT_VALUE_UNSET, ui_get_but_string(), ui_get_but_string_unit(), UI_GET_BUT_VALUE_INIT, ui_is_but_float(), ui_is_but_sel(), ui_is_but_unit(), UI_MAX_DRAW_STR, UI_SELECT, ui_set_but_soft_range(), ui_set_but_val(), ui_set_name_menu(), WM_key_event_string(), uiBut::x1, and uiBut::x2.
Referenced by button_activate_exit(), button_activate_state(), ui_apply_but_BLOCK(), ui_apply_but_IDPOIN(), ui_apply_but_NUM(), ui_apply_but_ROW(), ui_apply_but_TEX(), ui_apply_but_TOG(), ui_apply_but_TOG3(), ui_apply_but_VEC(), ui_block_position(), ui_but_add_shortcut(), ui_check_but_and_iconize(), ui_do_but_HOTKEYEVT(), ui_do_but_textedit(), ui_do_but_textedit_select(), ui_handle_button_return_submenu(), ui_item_position(), ui_layer_but_cb(), ui_numedit_apply(), ui_text_bounds_block(), ui_textedit_begin(), ui_textedit_move(), ui_textedit_set_cursor_select(), ui_update_block_buts_rgb(), uiDefBlockBut(), uiDefBlockButN(), uiDefBut(), uiDefButO_ptr(), uiDefButR(), uiDefButR_prop(), uiDefButTextO(), uiDefHotKeyevtButS(), uiDefIconBlockBut(), uiDefIconMenuBut(), uiDefIconTextBlockBut(), uiDefIconTextMenuBut(), uiDefIDPoinBut(), uiDefKeyevtButS(), uiDefMenuBut(), uiDefPulldownBut(), uiDefSearchBut(), and uiEndBlock().
void ui_convert_to_unit_alt_name (uiBut * but, char * str, size_t maxlen)
Definition at line 1581 of file interface.c.
References uiBut::block, bUnit_ToUnitAltName(), MEM_callocN(), MEM_freeN(), RNA_SUBTYPE_UNIT_VALUE, UnitSettings::system, ui_is_but_unit(), uiButGetUnitType(), and uiBlock::unit.
Referenced by ui_textedit_begin().
void ui_delete_linkline (uiLinkLine * line, uiBut * but)
Definition at line 1210 of file interface.c.
References BLI_remlink(), uiLinkLine::from, uiLink::lines, link(), uiBut::link, MEM_freeN(), NULL, uiLink::poin, uiBut::poin, uiLink::ppoin, uiLinkLine::to, and uiLink::totlink.
Referenced by cut_links_exec().
void ui_draw_aligned_panel (struct uiStyle * style, uiBlock * block, rcti * rect)
Definition at line 483 of file interface_panel.c.
References uiBlock::aspect, Panel::control, fdrawline(), PanelType::flag, Panel::flag, uiPanelColors::header, ThemeUI::panel, uiBlock::panel, Panel::paneltab, PNL_CLOSEDX, PNL_CLOSEDY, PNL_FIRST, PNL_HEADER, PNL_NO_HEADER, PNL_SELECT, rectf_scale(), Panel::runtime_flag, uiPanelColors::show_header, TH_BACK, TH_TEXT, bTheme::tui, Panel::type, UI_CNR_ALL, UI_CNR_NONE, ui_draw_aligned_panel_header(), ui_draw_panel_dragwidget(), ui_draw_panel_scalewidget(), ui_draw_tria_rect(), ui_draw_x_icon(), UI_GetTheme(), UI_PNL_CLOSE, UI_PNL_SCALE, UI_PNL_SOLID, UI_ThemeColor(), UI_ThemeColorShade(), uiRoundRect(), uiSetRoundBox(), rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by uiDrawBlock().
void ui_draw_anti_roundbox (int mode, float minx, float miny, float maxx, float maxy, float rad)
Definition at line 216 of file interface_widgets.c.
References jit, uiDrawBox(), and WIDGET_AA_JITTER.
Referenced by uiRoundBox().
void ui_draw_anti_tria (float x1, float y1, float x2, float y2, float x3, float y3)
Definition at line 191 of file interface_widgets.c.
References jit, and WIDGET_AA_JITTER.
Referenced by region_draw_azone_tab_plus(), region_draw_azone_tria(), ui_draw_tria_rect(), and UI_DrawTriIcon().
void ui_draw_but (const struct bContext * C, ARegion * ar, struct uiStyle * style, uiBut * but, rcti * rect)
Referenced by uiDrawBlock().
void ui_draw_but_COLORBAND (uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
void ui_draw_but_CURVE (ARegion * ar, uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
Definition at line 1291 of file interface_draw.c.
References uiBut::a1, uiBut::aspect, bglBegin(), bglEnd(), bglVertex2fv(), BLI_isect_rcti(), CurveMapping::clipr, CurveMapping::cm, CM_TABLE, CUMA_DO_CLIP, CUMA_DRAW_CFRA, CUMA_DRAW_SAMPLE, CUMA_EXTEND_EXTRAPOLATE, CurveMapping::cur, CurveMapping::curr, CurveMap::curve, curvemapping_changed(), uiBut::editcumap, CurveMap::ext_in, CurveMap::ext_out, fdrawbox(), CurveMapping::flag, CurveMap::flag, glColor3ubvShade(), uiWidgetColors::inner, uiWidgetColors::item, NULL, uiWidgetColors::outline, uiBut::poin, CurveMapping::sample, SELECT, CurveMap::table, TH_TEXT, TH_TEXT_HI, CurveMap::totpoint, ui_draw_but_curve_grid(), ui_draw_gradient(), UI_GRAD_H, UI_ThemeColor(), ARegion::winrct, CurveMapPoint::x, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, CurveMapPoint::y, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by ui_draw_but().
void ui_draw_but_HISTOGRAM (ARegion * ar, uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
void ui_draw_but_IMAGE (ARegion * ar, uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
void ui_draw_but_NORMAL (uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
Definition at line 1167 of file interface_draw.c.
References KDL::diff(), glutil_draw_lined_arc(), uiWidgetColors::inner, M_PI, size(), UI_CNR_ALL, ui_get_but_vectorf(), uiDrawBox(), uiSetRoundBox(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but().
void ui_draw_but_TRACKPREVIEW (ARegion * ar, uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
void ui_draw_but_VECTORSCOPE (ARegion * ar, uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
void ui_draw_but_WAVEFORM (ARegion * ar, uiBut * but, struct uiWidgetColors * wcol, rcti * rect)
void ui_draw_gradient (rcti * rect, const float hsv[3], int type, float alpha)
Definition at line 1943 of file interface_widgets.c.
References assert, copy_v3_v3(), hsv_to_rgb(), UI_GRAD_H, UI_GRAD_HS, UI_GRAD_HV, UI_GRAD_S, UI_GRAD_SV, UI_GRAD_V, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but_CURVE(), and ui_draw_but_HSVCUBE().
void ui_draw_link_bezier (rcti * rect)
Definition at line 2243 of file interface_widgets.c.
References LINK_RESOL, and ui_link_bezier_points().
Referenced by ui_draw_linkline(), and widget_link().
void ui_draw_menu_back (struct uiStyle * style, uiBlock * block, rcti * rect)
Referenced by uiDrawBlock().
void ui_draw_menu_item (struct uiFontStyle * fstyle, rcti * rect, const char * name, int iconid, int state)
Definition at line 3300 of file interface_widgets.c.
References uiFontStyle::align, BLF_width(), uiWidgetType::draw, uiWidgetType::state, uiWidgetColors::text, UI_DPI_ICON_SIZE, UI_icon_draw_aspect(), UI_STYLE_TEXT_LEFT, UI_STYLE_TEXT_RIGHT, UI_WTYPE_MENU_ITEM, uiFontStyle::uifont_id, uiStyleFontDraw(), uiStyleFontSet(), uiWidgetType::wcol, widget_type(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_searchbox_region_draw_cb().
void ui_draw_preview_item (struct uiFontStyle * fstyle, rcti * rect, const char * name, int iconid, int state)
Definition at line 3346 of file interface_widgets.c.
References BLF_width_and_height(), uiWidgetType::draw, uiWidgetColors::item, PREVIEW_PAD, uiWidgetType::state, uiWidgetColors::text, uiWidgetColors::text_sel, TH_BUTBACK, UI_ACTIVE, UI_GetThemeColor3ubv(), UI_WTYPE_MENU_ITEM, uiFontStyle::uifont_id, uiStyleFontDraw(), uiWidgetType::wcol, widget_draw_preview(), widget_type(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_searchbox_region_draw_cb().
void ui_draw_search_back (struct uiStyle * style, uiBlock * block, rcti * rect)
Referenced by ui_searchbox_region_draw_cb().
void ui_draw_tooltip_background (uiStyle * UNUSEDstyle, uiBlock * block, rcti * rect)
Referenced by ui_tooltip_region_draw_cb().
void ui_dropshadow (rctf * rct, float radius, float aspect, int select)
void ui_fontscale (short * points, float aspect)
Definition at line 950 of file interface.c.
References ceilf, floorf, and sqrt().
Referenced by ui_searchbox_create(), and uiDrawBlock().
void ui_get_but_string (uiBut * but, char * str, size_t maxlen)
Definition at line 1630 of file interface.c.
References BLI_snprintf(), BLI_strncpy(), ELEM3, IDPOIN, uiBut::idpoin_idpp, MEM_freeN(), MIN2, ID::name, NULL, uiBut::poin, PROP_POINTER, PROP_STRING, RNA_property_pointer_get(), RNA_property_string_get_alloc(), RNA_property_type(), RNA_struct_name_get_alloc(), uiBut::rnapoin, uiBut::rnaprop, SEARCH_MENU, TEX, uiBut::type, ui_but_anim_expression_get(), ui_but_float_precision(), ui_get_but_string_unit(), ui_get_but_val(), ui_is_but_float(), and ui_is_but_unit().
Referenced by ui_but_copy_paste(), ui_check_but(), ui_textedit_begin(), and ui_tooltip_create().
int ui_get_but_string_max_length (uiBut * but)
Definition at line 1547 of file interface.c.
References ELEM, uiBut::hardmax, IDPOIN, MAX_ID_NAME, SEARCH_MENU, TEX, uiBut::type, and UI_MAX_DRAW_STR.
Referenced by ui_searchbox_autocomplete(), and ui_textedit_begin().
double ui_get_but_val (uiBut * but)
Definition at line 1380 of file interface.c.
References CHA, PointerRNA::data, uiBut::editval, uiBut::editvec, FLO, HSVSLI, INT, NULL, uiBut::poin, uiBut::pointype, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, rgb_to_hsv(), RNA_property_array_check(), RNA_property_boolean_get(), RNA_property_boolean_get_index(), RNA_property_enum_get(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_int_get(), RNA_property_int_get_index(), RNA_property_type(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, SHO, uiBut::str, and uiBut::type.
Referenced by do_picker_new_mode_cb(), ui_apply_but_NUM(), ui_apply_but_TOG(), ui_blockopen_begin(), ui_but_start_drag(), ui_get_but_string(), ui_numedit_begin(), ui_step_name_menu(), ui_tooltip_create(), widget_numslider(), and widget_scroll().
void ui_get_but_vectorf (uiBut * but, float vec[3])
Definition at line 1252 of file interface.c.
References BUT_NORMAL, CHA, copy_v3_v3(), uiBut::editvec, FLO, MIN2, normalize_v3(), NULL, uiBut::poin, uiBut::pointype, PROP_FLOAT, RNA_property_array_length(), RNA_property_float_get_index(), RNA_property_type(), uiBut::rnapoin, uiBut::rnaprop, and uiBut::type.
Referenced by ui_blockopen_begin(), ui_but_copy_paste(), ui_do_but_BLOCK(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_draw_but_HSV_v(), ui_draw_but_HSVCIRCLE(), ui_draw_but_HSVCUBE(), ui_draw_but_NORMAL(), ui_ndofedit_but_HSVCIRCLE(), ui_ndofedit_but_HSVCUBE(), ui_numedit_begin(), ui_numedit_but_HSVCIRCLE(), ui_numedit_but_HSVCUBE(), ui_picker_small_wheel_cb(), and widget_swatch().
int ui_handler_panel_region (struct bContext * C, struct wmEvent * event)
Definition at line 1075 of file interface_panel.c.
References AKEY, wmEvent::alt, CLAMP(), Panel::control, wmEvent::ctrl, CTX_wm_area(), CTX_wm_region(), ED_region_tag_redraw(), ELEM, ELEM4, ESCKEY, ListBase::first, PanelType::flag, Panel::flag, KM_MOD_FIRST, KM_PRESS, ListBase::last, LEFTMOUSE, uiBlock::maxx, uiBlock::maxy, uiBlock::minx, uiBlock::miny, NULL, wmEvent::oskey, PADENTER, PADMINUS, PADPLUSKEY, uiBlock::panel, panel_activate_state(), PANEL_STATE_DRAG_SCALE, Panel::paneltab, PNL_CLOSED, PNL_CLOSEDX, PNL_CLOSEDY, PNL_HEADER, PNL_NO_HEADER, uiBlock::prev, RETKEY, wmEvent::shift, SPACE_BUTS, ScrArea::spacedata, ScrArea::spacetype, wmEvent::type, Panel::type, ui_button_is_active(), ui_handle_panel_header(), UI_PNL_SCALE, ui_window_to_block(), ARegion::uiblocks, wmEvent::val, WM_UI_HANDLER_BREAK, and WM_UI_HANDLER_CONTINUE.
Referenced by ui_handler_region().
void ui_hsvcircle_vals_from_pos (float * valrad, float * valdist, rcti * rect, float mx, float my)
Definition at line 1836 of file interface_widgets.c.
References atan2f, M_PI, sqrt(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by ui_draw_but_HSVCIRCLE(), and ui_numedit_but_HSVCIRCLE().
int ui_id_icon_get (struct bContext * C, struct ID * id, int preview)
Definition at line 1115 of file interface_icons.c.
References BKE_icon_getid(), GS, ID_BR, ID_IM, ID_LA, ID_MA, ID_TE, ID_WO, ID::name, ui_id_brush_get_icon(), and ui_id_icon_render().
Referenced by id_search_cb(), list_item_icon_get(), list_item_row(), rna_search_cb(), and template_ID().
int ui_is_but_float (uiBut * but)
Definition at line 1332 of file interface.c.
References FLO, uiBut::poin, uiBut::pointype, PROP_FLOAT, RNA_property_type(), and uiBut::rnaprop.
Referenced by ui_check_but(), ui_do_but_NUM(), ui_do_but_SLI(), ui_get_but_string(), ui_numedit_but_NUM(), ui_numedit_but_SLI(), and ui_set_but_string().
int ui_is_but_rna_valid (uiBut * but)
Definition at line 1369 of file interface.c.
References uiBut::drawstr, FALSE, NULL, RNA_struct_contains_property(), uiBut::rnapoin, uiBut::rnaprop, and TRUE.
int ui_is_but_unit (uiBut * but)
Definition at line 1343 of file interface.c.
References uiBut::block, PROP_UNIT_NONE, PROP_UNIT_ROTATION, PROP_UNIT_TIME, UnitSettings::system, UnitSettings::system_rotation, uiButGetUnitType(), uiBlock::unit, USER_UNIT_NONE, and USER_UNIT_ROT_RADIANS.
Referenced by ui_check_but(), ui_convert_to_unit_alt_name(), ui_def_but_rna(), ui_get_but_string(), ui_numedit_apply_snapf(), and ui_set_but_string_eval_num().
int ui_is_but_utf8 (uiBut * but)
Definition at line 265 of file interface_handlers.c.
References ELEM4, uiBut::flag, PROP_BYTESTRING, PROP_DIRPATH, PROP_FILENAME, PROP_FILEPATH, RNA_property_subtype(), uiBut::rnaprop, and UI_BUT_NO_UTF8.
Referenced by ui_but_copy_paste(), ui_set_but_string(), ui_textedit_end(), and ui_textedit_type_ascii().
void ui_layout_add_but (uiLayout * layout, uiBut * but)
Definition at line 2669 of file interface_layout.c.
References BLI_addtail(), uiButtonItem::but, uiBut::context, uiLayout::context, uiButtonItem::item, ITEM_BUTTON, uiLayout::items, MEM_callocN(), uiItem::type, and bContextStore::used.
Referenced by ui_def_but().
int ui_link_bezier_points (rcti * rect, float coord_array[][2], int resol)
Definition at line 2219 of file interface_widgets.c.
References ABS, forward_diff_bezier(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by cut_links_intersect(), and ui_draw_link_bezier().
uiPopupBlockHandle* ui_popup_block_create (struct bContext * C, struct ARegion * butregion, uiBut * but, uiBlockCreateFunc create_func, uiBlockHandleCreateFunc handle_create_func, void * arg)
Definition at line 1556 of file interface_regions.c.
References uiBlock::aspect, BLI_addhead(), BLOCK, uiBut::block, uiBlock::buttons, create_func(), uiPopupBlockHandle::ctx_area, uiPopupBlockHandle::ctx_region, CTX_wm_area(), CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), ARegionType::draw, ED_region_init(), ED_region_tag_redraw(), ELEM, uiBlock::endblock, ListBase::first, uiBlock::flag, uiBlock::handle, ARegion::handlers, uiBlock::maxx, uiBlock::maxy, MEM_callocN(), MEM_freeN(), MENU_SHADOW_BOTTOM, MENU_SHADOW_SIDE, MENU_TOP, uiBlock::minx, uiBlock::miny, uiBut::next, PULLDOWN, uiPopupBlockHandle::region, ARegion::regiondata, uiBlock::saferct, uiBlock::safety, uiSafetyRct::safety, ARegion::swinid, ARegion::type, uiBut::type, UI_add_region_handlers(), ui_add_temporary_region(), UI_BLOCK_LOOP, UI_BLOCK_NUMSELECT, UI_BLOCK_POPUP, ui_block_position(), ui_block_region_draw(), ui_popup_block_clip(), ui_popup_block_scrolltest(), uiEndBlock(), uiBlock::winmat, ARegion::winrct, wm_subwindow_getmatrix(), wmSubWindowSet(), uiBut::x1, uiBut::x2, rcti::xmax, rcti::xmin, uiBlock::xofs, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by ui_blockopen_begin(), ui_popup_menu_create(), uiPupBlockEx(), uiPupBlockO(), and uiPupMenuEnd().
void ui_popup_block_free (struct bContext * C, uiPopupBlockHandle * handle)
Definition at line 1661 of file interface_regions.c.
References CTX_wm_manager(), CTX_wm_screen(), CTX_wm_window(), MEM_freeN(), uiPopupBlockHandle::region, uiPopupBlockHandle::scrolltimer, ui_remove_temporary_region(), and WM_event_remove_timer().
Referenced by ui_blockopen_end(), ui_handler_popup(), ui_handler_remove_popup(), and uiPupBlockClose().
void ui_popup_block_scrolltest (struct uiBlock * block)
Definition at line 1515 of file interface_regions.c.
References uiBlock::buttons, uiBlock::direction, ListBase::first, uiBut::flag, uiBlock::flag, ListBase::last, uiBlock::maxy, uiBlock::miny, uiBut::next, uiBut::prev, UI_BLOCK_CLIPBOTTOM, UI_BLOCK_CLIPTOP, UI_BLOCK_NO_FLIP, UI_SCROLLED, UI_TOP, uiBut::y1, and uiBut::y2.
Referenced by ui_menu_scroll(), and ui_popup_block_create().
uiPopupBlockHandle* ui_popup_menu_create (struct bContext * C, struct ARegion * butregion, uiBut * but, uiMenuCreateFunc create_func, void * arg, char * str)
Definition at line 2385 of file interface_regions.c.
References uiPopupMenu::block, uiBut::block, uiPopupMenu::but, uiBut::context, CTX_wm_window(), wmWindow::eventstate, uiBlock::flag, uiPopupMenu::layout, MEM_callocN(), MEM_freeN(), uiPopupMenu::menu_arg, uiPopupMenu::menu_func, wmWindow::modalhandlers, uiPopupMenu::mx, uiPopupMenu::my, NULL, uiPopupMenu::popup, uiPopupBlockHandle::popup, PROP_ENUM, RNA_property_type(), uiBut::rnaprop, uiPopupMenu::slideout, str, UI_add_popup_handlers(), ui_block_func_MENUSTR(), ui_block_func_POPUP(), UI_BLOCK_LOOP, UI_BLOCK_NO_FLIP, UI_EMBOSSP, UI_GetStyle(), UI_LAYOUT_MENU, UI_LAYOUT_VERTICAL, ui_popup_block_create(), uiBeginBlock(), uiBlockLayout(), uiLayoutContextCopy(), uiLayoutSetOperatorContext(), WM_event_add_mousemove(), WM_OP_INVOKE_REGION_WIN, wmEvent::x, and wmEvent::y.
Referenced by confirm_operator(), ui_blockopen_begin(), uiPupMenuReports(), and vconfirm_opname().
uiBut* ui_popup_menu_memory (struct uiBlock * block, struct uiBut * but)
Definition at line 2246 of file interface_regions.c.
References uiBlock::buttons, ListBase::first, hash, uiBut::next, NULL, uiBlock::puphash, uiBut::str, and ui_popup_string_hash().
Referenced by button_activate_exit(), and ui_block_func_POPUP().
void ui_resources_free (void)
Definition at line 73 of file resources.c.
References UI_icons_free().
Referenced by UI_exit().
void ui_resources_init (void)
Definition at line 68 of file resources.c.
References UI_icons_init().
Referenced by UI_init().
void ui_searchbox_apply (uiBut * but, struct ARegion * ar)
Definition at line 838 of file interface_regions.c.
References uiSearchboxData::active, BLI_strncpy(), data, uiBut::editstr, uiBut::func_arg2, uiSearchboxData::items, uiSearchItems::maxstrlen, uiSearchItems::names, NULL, uiSearchItems::pointers, and ARegion::regiondata.
Referenced by ui_textedit_end().
void ui_searchbox_autocomplete (struct bContext * C, struct ARegion * ar, uiBut * but, char * str)
Definition at line 961 of file interface_regions.c.
References autocomplete_begin(), autocomplete_end(), uiSearchItems::autocpl, data, uiBut::editstr, uiSearchboxData::items, NULL, ARegion::regiondata, uiBut::search_arg, uiBut::search_func, and ui_get_but_string_max_length().
Referenced by ui_textedit_autocomplete().
ARegion* ui_searchbox_create (struct bContext * C, struct ARegion * butregion, uiBut * but)
Definition at line 1060 of file interface_regions.c.
References uiBut::a1, uiBut::a2, uiFontStyle::align, uiBlock::aspect, uiSearchboxData::bbox, uiBut::block, CTX_wm_screen(), CTX_wm_window(), View2D::cur, data, ARegionType::draw, ED_region_init(), ED_region_tag_redraw(), uiBlock::flag, ARegionType::free, uiSearchboxData::fstyle, uiBut::hardmax, uiSearchItems::icons, uiSearchboxData::items, uiSearchItems::maxitem, uiSearchItems::maxstrlen, uiBlock::maxy, MEM_callocN(), MENU_SHADOW_BOTTOM, MENU_SHADOW_SIDE, uiBlock::miny, uiSearchItems::names, uiSearchboxData::noback, NULL, Panel::ofsx, Panel::ofsy, uiBlock::panel, uiSearchItems::pointers, uiFontStyle::points, uiSearchboxData::preview, uiSearchboxData::prv_cols, uiSearchboxData::prv_rows, ARegion::regiondata, SEARCH_ITEMS, uiSearchItems::totitem, ARegion::type, ui_add_temporary_region(), UI_BLOCK_LOOP, ui_fontscale(), UI_GetStyle(), ui_searchbox_region_draw_cb(), ui_searchbox_region_free_cb(), UI_STYLE_TEXT_CENTER, UI_view2d_to_region_no_clip(), uiSearchBoxhHeight(), uiStyleFontSet(), ARegion::v2d, uiStyle::widget, ARegion::winrct, wm_window_get_size(), uiBut::x1, uiBut::x2, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, uiBut::y1, uiBut::y2, rcti::ymax, and rcti::ymin.
Referenced by ui_textedit_begin().
void ui_searchbox_event (struct bContext * C, struct ARegion * ar, uiBut * but, struct wmEvent * event)
Definition at line 856 of file interface_regions.c.
References uiSearchboxData::active, BLI_in_rcti(), data, DOWNARROWKEY, uiSearchboxData::items, MOUSEMOVE, ARegion::regiondata, uiSearchItems::totitem, wmEvent::type, ui_searchbox_butrect(), ui_searchbox_select(), UPARROWKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, ARegion::winrct, wmEvent::x, rcti::xmin, wmEvent::y, and rcti::ymin.
Referenced by ui_do_but_textedit().
void ui_searchbox_free (struct bContext * C, struct ARegion * ar)
Definition at line 1211 of file interface_regions.c.
References CTX_wm_screen(), and ui_remove_temporary_region().
Referenced by ui_textedit_end().
int ui_searchbox_inside (struct ARegion * ar, int x, int y)
Definition at line 830 of file interface_regions.c.
References uiSearchboxData::bbox, BLI_in_rcti(), data, ARegion::regiondata, ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by ui_do_but_textedit().
void ui_searchbox_update (struct bContext * C, struct ARegion * ar, uiBut * but, int reset)
Definition at line 890 of file interface_regions.c.
References uiSearchboxData::active, uiSearchItems::active, data, ED_region_tag_redraw(), uiBut::editstr, uiBut::func_arg2, uiSearchboxData::items, uiSearchItems::maxitem, uiSearchItems::more, uiSearchItems::names, NULL, uiSearchItems::offset, uiSearchItems::offset_i, ARegion::regiondata, uiBut::search_arg, uiBut::search_func, uiSearchItems::totitem, and ui_searchbox_select().
Referenced by ui_but_copy_paste(), ui_do_but_textedit(), ui_searchbox_select(), and ui_textedit_begin().
void ui_set_but_default (struct bContext * C, short all)
Definition at line 1846 of file interface.c.
References RNA_boolean_set(), WM_OP_EXEC_DEFAULT, WM_operator_name_call(), WM_operator_properties_create(), and WM_operator_properties_free().
Referenced by ui_do_button().
void ui_set_but_hsv (uiBut * but)
Definition at line 1838 of file interface_regions.c.
References uiBut::block, hsv_to_rgb(), ui_block_hsv_get(), and ui_set_but_vectorf().
Referenced by ui_do_but_HSVCIRCLE().
void ui_set_but_soft_range (uiBut * but, double value)
Definition at line 1882 of file interface.c.
References FLT_MAX, uiBut::hardmax, uiBut::hardmin, PROP_FLOAT, PROP_INT, RNA_property_array_length(), RNA_property_float_get_array_range(), RNA_property_float_ui_range(), RNA_property_int_get_array_range(), RNA_property_int_ui_range(), RNA_property_type(), uiBut::rnapoin, uiBut::rnaprop, soft_range_round_down(), soft_range_round_up(), uiBut::softmax, and uiBut::softmin.
Referenced by ui_check_but().
int ui_set_but_string (struct bContext * C, uiBut * but, const char * str)
Definition at line 1763 of file interface.c.
References BLI_strncpy(), BLI_strncpy_utf8(), ELEM3, fabs(), FALSE, uiBut::hardmax, uiBut::hardmin, IDPOIN, uiBut::idpoin_func, uiBut::idpoin_idpp, NULL, NUMABS, uiBut::poin, PointerRNA_NULL, PROP_POINTER, PROP_STRING, RNA_property_collection_lookup_string(), RNA_property_editable(), RNA_property_pointer_set(), RNA_property_string_set(), RNA_property_type(), uiBut::rnapoin, uiBut::rnaprop, uiBut::rnasearchpoin, uiBut::rnasearchprop, SEARCH_MENU, TEX, uiBut::type, ui_but_anim_expression_create(), ui_but_anim_expression_set(), ui_is_but_float(), ui_is_but_utf8(), ui_set_but_string_eval_num(), and ui_set_but_val().
Referenced by ui_apply_but_IDPOIN(), ui_apply_but_NUM(), ui_apply_but_TEX(), and ui_but_copy_paste().
int ui_set_but_string_eval_num (struct bContext * C, uiBut * but, const char * str, double * value)
Definition at line 1722 of file interface.c.
References BLI_snprintf(), BPY_button_exec(), FALSE, TRUE, and ui_is_but_unit().
Referenced by ui_but_copy_paste(), and ui_set_but_string().
void ui_set_but_val (uiBut * but, double value)
Definition at line 1446 of file interface.c.
References CHA, uiBut::editval, uiBut::editvec, FLO, hsv_to_rgb(), HSVSLI, INT, uiBut::poin, uiBut::pointype, PROP_BOOLEAN, PROP_ENUM, PROP_ENUM_FLAG, PROP_FLOAT, PROP_INT, rgb_to_hsv(), RNA_property_array_length(), RNA_property_boolean_set(), RNA_property_boolean_set_index(), RNA_property_editable(), RNA_property_enum_get(), RNA_property_enum_set(), RNA_property_flag(), RNA_property_float_set(), RNA_property_float_set_index(), RNA_property_int_set(), RNA_property_int_set_index(), RNA_property_type(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, SHO, uiBut::str, uiBut::type, UI_BUT_VALUE_UNSET, and ui_is_but_sel().
Referenced by ui_apply_but_BLOCK(), ui_apply_but_BUTM(), ui_apply_but_NUM(), ui_apply_but_ROW(), ui_apply_but_TOG(), ui_check_but(), ui_do_but_HOTKEYEVT(), ui_do_but_KEYEVT(), ui_set_but_string(), and ui_update_block_buts_rgb().
void ui_set_but_vectorf (uiBut * but, const float vec[3])
Definition at line 1297 of file interface.c.
References CHA, copy_v3_v3(), uiBut::editvec, FLO, MIN2, uiBut::poin, uiBut::pointype, PROP_FLOAT, RNA_property_array_length(), RNA_property_float_set_index(), RNA_property_type(), uiBut::rnapoin, and uiBut::rnaprop.
Referenced by ui_apply_but_VEC(), ui_but_copy_paste(), ui_do_but_BLOCK(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_ndofedit_but_HSVCIRCLE(), ui_ndofedit_but_HSVCUBE(), ui_numedit_but_HSVCIRCLE(), ui_picker_small_wheel_cb(), ui_set_but_hsv(), and ui_update_block_buts_rgb().
void ui_set_name_menu (uiBut * but, int value)
Definition at line 235 of file interface_regions.c.
References BLI_strncpy(), decompose_menu_string(), uiBut::drawstr, i, MenuData::items, menudata_free(), MenuData::nitems, MenuEntry::retval, MenuEntry::str, and uiBut::str.
Referenced by ui_check_but().
int ui_step_name_menu (uiBut * but, int step)
Definition at line 251 of file interface_regions.c.
References decompose_menu_string(), i, MenuData::items, menudata_free(), MenuData::nitems, MenuEntry::retval, uiBut::str, and ui_get_but_val().
Referenced by ui_do_but_BLOCK().
void ui_theme_init_default (void)
Definition at line 600 of file resources.c.
References ThemeSpace::act_marker, ThemeSpace::act_spline, ThemeSpace::active, ThemeSpace::audio, ThemeSpace::back, BLI_addtail(), ThemeSpace::bone_pose, ThemeSpace::bone_solid, ThemeSpace::bundle_solid, ThemeSpace::button, ThemeSpace::button_text, ThemeSpace::button_text_hi, ThemeSpace::button_title, ThemeSpace::camera, ThemeSpace::camera_path, ThemeSpace::cframe, ThemeSpace::console_cursor, ThemeSpace::console_error, ThemeSpace::console_info, ThemeSpace::console_input, ThemeSpace::console_output, ThemeSpace::dis_marker, ThemeSpace::ds_channel, ThemeSpace::ds_subchannel, ThemeSpace::edge, ThemeSpace::edge_crease, ThemeSpace::edge_facesel, ThemeSpace::edge_seam, ThemeSpace::edge_select, ThemeSpace::edge_sharp, ThemeSpace::editmesh_active, ThemeSpace::effect, ThemeSpace::empty, ThemeSpace::extra_edge_len, ThemeSpace::extra_face_angle, ThemeSpace::extra_face_area, ThemeSpace::face, ThemeSpace::face_dot, ThemeSpace::face_select, ThemeSpace::facedot_size, FALSE, ThemeSpace::grid, ThemeSpace::group, ThemeSpace::group_active, ThemeSpace::handle_align, ThemeSpace::handle_auto, ThemeSpace::handle_auto_clamped, ThemeSpace::handle_free, ThemeSpace::handle_sel_align, ThemeSpace::handle_sel_auto, ThemeSpace::handle_sel_auto_clamped, ThemeSpace::handle_sel_free, ThemeSpace::handle_sel_vect, ThemeSpace::handle_vect, ThemeSpace::handle_vertex, ThemeSpace::handle_vertex_select, ThemeSpace::handle_vertex_size, ThemeSpace::header, uiPanelColors::header, ThemeSpace::header_text, ThemeSpace::header_text_hi, ThemeSpace::hilite, ThemeUI::iconfile, ThemeSpace::image, ThemeSpace::lamp, ThemeSpace::lastsel_point, ThemeSpace::list, ThemeSpace::lock_marker, ThemeSpace::marker, ThemeSpace::marker_outline, ThemeSpace::match, MEM_callocN(), ThemeSpace::meta, ThemeSpace::movie, ThemeSpace::movieclip, bTheme::name, bTheme::next, ThemeSpace::noodle_curving, ThemeSpace::normal, NULL, ThemeSpace::nurb_sel_uline, ThemeSpace::nurb_sel_vline, ThemeSpace::nurb_uline, ThemeSpace::nurb_vline, ThemeSpace::outline_width, ThemeUI::panel, ThemeSpace::panel, ThemeSpace::path_after, ThemeSpace::path_before, ThemeSpace::plugin, ThemeSpace::preview_back, ThemeSpace::preview_stitch_edge, ThemeSpace::preview_stitch_face, ThemeSpace::preview_stitch_stitchable, ThemeSpace::preview_stitch_unstitchable, ThemeSpace::preview_stitch_vert, rgba_char_args_set(), rgba_char_args_set_fl, ThemeSpace::scene, ThemeSpace::sel_marker, ThemeSpace::select, ThemeSpace::selected_highlight, ThemeSpace::shade1, ThemeSpace::shade2, uiPanelColors::show_header, ThemeSpace::speaker, ThemeSpace::strip, ThemeSpace::strip_select, ThemeSpace::syntaxb, ThemeSpace::syntaxc, ThemeSpace::syntaxl, ThemeSpace::syntaxn, ThemeSpace::syntaxv, bTheme::tact, bTheme::tbuts, bTheme::tclip, bTheme::tconsole, ThemeSpace::text, bTheme::text, ThemeSpace::text_hi, bTheme::tfile, bTheme::tima, bTheme::tinfo, bTheme::tipo, ThemeSpace::title, bTheme::tlogic, bTheme::tnla, bTheme::tnode, bTheme::toops, ThemeSpace::transform, ThemeSpace::transition, bTheme::tseq, bTheme::ttime, bTheme::tui, bTheme::tuserpref, bTheme::tv3d, UI_SetTheme(), ui_theme_init_boneColorSets(), ui_theme_init_new(), ui_widget_color_init(), ThemeSpace::vertex, ThemeSpace::vertex_normal, ThemeSpace::vertex_select, ThemeSpace::vertex_size, and ThemeSpace::wire.
Referenced by reset_default_theme_exec().
struct ARegion* ui_tooltip_create (struct bContext * C, struct ARegion * butregion, uiBut * but) [read]
Definition at line 414 of file interface_regions.c.
References uiFontStyle::align, uiBlock::aspect, assert, uiTooltipData::bbox, BLF_height_max(), BLF_width(), BLI_snprintf(), BLI_strncpy(), uiBut::block, uiTooltipData::color_id, CTX_wm_operator_poll_msg_get(), CTX_wm_operator_poll_msg_set(), CTX_wm_screen(), CTX_wm_window(), View2D::cur, data, PointerRNA::data, EnumPropertyItem::description, ARegionType::draw, ED_region_init(), ED_region_tag_redraw(), ELEM, ELEM3, uiBut::flag, uiBlock::flag, ARegionType::free, uiTooltipData::fstyle, uiBut::hardmax, i, PointerRNA::id, wmOperatorType::idname, MenuType::idname, IDPOIN, if(), ID::lib, uiTooltipData::lineh, uiTooltipData::lines, MAX2, MAX_TOOLTIP_LINES, MEM_callocN(), MEM_freeN(), MENU, MENU_SHADOW_BOTTOM, MENU_SHADOW_SIDE, MENU_TOP, mt, Library::name, EnumPropertyItem::name, NULL, Panel::ofsx, Panel::ofsy, uiBut::opcontext, uiBut::opptr, uiBut::optype, uiBlock::panel, PROP_ENUM, PROP_FLOAT, PROP_UNIT_ROTATION, PULLDOWN, ARegion::regiondata, RNA_property_array_check(), RNA_property_description(), RNA_property_enum_items_gettexted(), RNA_property_float_get(), RNA_property_float_get_index(), RNA_property_identifier(), RNA_property_type(), RNA_struct_identifier(), uiBut::rnaindex, uiBut::rnapoin, uiBut::rnaprop, ROW, SEARCH_MENU, uiTooltipData::spaceh, str, TEX, uiBut::tip, TIP_, TIP_BORDER_X, TIP_BORDER_Y, TIP_MARGIN_Y, uiTooltipData::toth, uiTooltipData::totline, TRUE, PointerRNA::type, ARegion::type, uiBut::type, ui_add_temporary_region(), UI_BLOCK_LOOP, ui_but_anim_expression_get(), UI_BUT_DISABLED, UI_BUT_DRIVEN, UI_BUT_NO_TOOLTIP, ui_get_but_string(), ui_get_but_val(), UI_GetStyle(), UI_STYLE_TEXT_CENTER, UI_TIP_LC_ALERT, UI_TIP_LC_MAIN, UI_TIP_LC_NORMAL, UI_TIP_LC_PYTHON, UI_TIP_LC_SUBMENU, ui_tooltip_region_draw_cb(), ui_tooltip_region_free_cb(), UI_view2d_to_region_no_clip(), uiButGetMenuType(), uiButGetOperatorPtrRNA(), uiButGetUnitType(), uiFontStyle::uifont_id, uiStyleFontSet(), USER_TOOLTIPS_PYTHON, ARegion::v2d, uiStyle::widget, ARegion::winrct, WM_key_event_operator_string(), WM_operator_poll_context(), WM_operator_pystring(), wm_window_get_size(), uiBut::x1, uiBut::x2, rcti::xmax, rctf::xmax, rcti::xmin, rctf::xmin, uiBut::y1, rcti::ymax, and rcti::ymin.
Referenced by ui_handle_button_event().
void ui_tooltip_free (struct bContext * C, struct ARegion * ar)
Definition at line 684 of file interface_regions.c.
References CTX_wm_screen(), and ui_remove_temporary_region().
Referenced by button_timers_tooltip_remove().
uiWidgetColors* ui_tooltip_get_theme (void)
Definition at line 3267 of file interface_widgets.c.
References UI_WTYPE_TOOLTIP, uiWidgetType::wcol_theme, and widget_type().
Referenced by ui_tooltip_region_draw_cb().
void ui_widget_color_init (struct ThemeUI * tui)
Definition at line 1565 of file interface_widgets.c.
References wcol_box, ThemeUI::wcol_box, ThemeUI::wcol_list_item, wcol_list_item, wcol_menu, ThemeUI::wcol_menu, wcol_menu_back, ThemeUI::wcol_menu_back, ThemeUI::wcol_menu_item, wcol_menu_item, ThemeUI::wcol_num, wcol_num, wcol_numslider, ThemeUI::wcol_numslider, wcol_option, ThemeUI::wcol_option, ThemeUI::wcol_progress, wcol_progress, ThemeUI::wcol_pulldown, wcol_pulldown, ThemeUI::wcol_radio, wcol_radio, ThemeUI::wcol_regular, wcol_regular, wcol_scroll, ThemeUI::wcol_scroll, ThemeUI::wcol_state, wcol_state_colors, wcol_text, ThemeUI::wcol_text, ThemeUI::wcol_toggle, wcol_toggle, ThemeUI::wcol_tool, wcol_tool, ThemeUI::wcol_tooltip, and wcol_tooltip.
Referenced by init_userdef_do_versions(), and ui_theme_init_default().
void ui_window_to_block (const struct ARegion * ar, uiBlock * block, int * x, int * y)
void ui_window_to_block_fl (const struct ARegion * ar, uiBlock * block, float * x, float * y)
void ui_window_to_region (const ARegion * ar, int * x, int * y)
Definition at line 189 of file interface.c.
References ARegion::winrct, rcti::xmin, and rcti::ymin.
Referenced by ui_mouse_inside_region().
void uiStyleInit (void)
Definition at line 303 of file interface_style.c.
References uiFont::blf_id, BLF_load(), BLF_load_mem(), BLF_load_mem_unique(), blf_mono_font, blf_mono_font_render, BLF_size(), BLF_unload(), BLI_addtail(), BLI_strncpy(), CLAMP(), datatoc_bfont_ttf, datatoc_bfont_ttf_size, datatoc_bmonofont_ttf, datatoc_bmonofont_ttf_size, uiFont::filename, G, G_DEBUG, MEM_callocN(), uiFont::next, NULL, ui_style_new(), UIFONT_DEFAULT, uiFont::uifont_id, and USER_DOTRANSLATE.
Referenced by UI_init_userdef(), and UI_reinit_font().
Variable Documentation
unsigned char checker_stipple_sml[]
Definition at line 177 of file interface_widgets.c.
Referenced by ui_draw_but_COLORBAND(), and widgetbase_draw().