Blender: node_composite_alphaOver.c File Reference
node_composite_alphaOver.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_alphaover_premul (bNode *UNUSED(node), float *out, float *src, float *over, float *fac)
static void do_alphaover_key (bNode *UNUSED(node), float *out, float *src, float *over, float *fac)
static void do_alphaover_mixed (bNode *node, float *out, float *src, float *over, float *fac)
static void node_composit_exec_alphaover (void *UNUSED(data), bNode *node, bNodeStack **in, bNodeStack **out)
static void node_alphaover_init (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
void register_node_type_cmp_alphaover (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_alphaover_in []
static bNodeSocketTemplate cmp_node_alphaover_out []
Detailed Description
Definition in file node_composite_alphaOver.c.
Function Documentation
static void do_alphaover_key (bNode * UNUSEDnode, float * out, float * src, float * over, float * fac) [static]
Definition at line 68 of file node_composite_alphaOver.c.
References copy_v4_v4(), and mul().
Referenced by node_composit_exec_alphaover().
static void do_alphaover_mixed (bNode * node, float * out, float * src, float * over, float * fac) [static]
Definition at line 89 of file node_composite_alphaOver.c.
References copy_v4_v4(), mul(), bNode::storage, and NodeTwoFloats::x.
Referenced by node_composit_exec_alphaover().
static void do_alphaover_premul (bNode * UNUSEDnode, float * out, float * src, float * over, float * fac) [static]
Definition at line 47 of file node_composite_alphaOver.c.
References copy_v4_v4(), and mul().
Referenced by node_composit_exec_alphaover().
static void node_alphaover_init (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 142 of file node_composite_alphaOver.c.
References MEM_callocN(), and bNode::storage.
Referenced by register_node_type_cmp_alphaover().
static void node_composit_exec_alphaover (void * UNUSEDdata, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 114 of file node_composite_alphaOver.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, composit3_pixel_processor(), bNode::custom1, bNodeStack::data, data, do_alphaover_key(), do_alphaover_mixed(), do_alphaover_premul(), NULL, bNode::storage, NodeTwoFloats::x, CompBuf::x, and CompBuf::y.
Referenced by register_node_type_cmp_alphaover().
void register_node_type_cmp_alphaover (bNodeTreeType * ttype)
Definition at line 147 of file node_composite_alphaOver.c.
References CMP_NODE_ALPHAOVER, node_alphaover_init(), NODE_CLASS_OP_COLOR, node_composit_exec_alphaover(), node_copy_standard_storage(), node_free_standard_storage(), NODE_OPTIONS, node_type_base(), node_type_exec(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_alphaover_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",           1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_composite_alphaOver.c.
bNodeSocketTemplate cmp_node_alphaover_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 42 of file node_composite_alphaOver.c.