Blender: mathutils_Vector.h File Reference
mathutils_Vector.h File Reference
Python Mathutils
Classes
struct VectorObject
Defines
#define VectorObject_Check(_v) PyObject_TypeCheck((_v), &vector_Type)
Functions
PyObject * Vector_CreatePyObject (float *vec, const int size, const int type, PyTypeObject *base_type)
PyObject * Vector_CreatePyObject_cb (PyObject *user, int size, unsigned char cb_type, unsigned char subtype)
PyObject * Vector_CreatePyObject_alloc (float *vec, const int size, PyTypeObject *base_type)
Variables
PyTypeObject vector_Type
Detailed Description
Definition in file mathutils_Vector.h.
Define Documentation
#define VectorObject_Check (_v) PyObject_TypeCheck((_v), &vector_Type)
Definition at line 39 of file mathutils_Vector.h.
Referenced by M_Geometry_tessellate_polygon(), mathutils_array_parse(), mathutils_array_parse_alloc(), Matrix_mul(), Quaternion_mul(), Vector_add(), Vector_div(), Vector_iadd(), Vector_isub(), Vector_mul(), Vector_richcmpr(), and Vector_sub().
Function Documentation
PyObject* Vector_CreatePyObject (float * vec, const int size, const int type, PyTypeObject * base_type)
Definition at line 2878 of file mathutils_Vector.c.
References fill_vn_fl(), NULL, Py_NEW, Py_WRAP, and size().
Referenced by bpy_bmedge_calc_tangent(), bpy_bmface_calc_center_bounds(), bpy_bmface_calc_center_mean(), bpy_bmface_normal_get(), BPy_BMLayerItem_GetItem(), bpy_bmloop_calc_normal(), bpy_bmloop_calc_tangent(), bpy_bmloopuv_uv_get(), bpy_bmvert_co_get(), bpy_bmvert_normal_get(), M_Geometry_barycentric_transform(), M_Geometry_interpolate_bezier(), M_Geometry_intersect_line_line(), M_Geometry_intersect_line_line_2d(), M_Geometry_intersect_line_plane(), M_Geometry_intersect_line_sphere(), M_Geometry_intersect_line_sphere_2d(), M_Geometry_intersect_plane_plane(), M_Geometry_intersect_point_line(), M_Geometry_intersect_ray_tri(), M_Geometry_normal(), M_Noise_cell_vector(), M_Noise_noise_vector(), M_Noise_random_unit_vector(), M_Noise_turbulence_vector(), M_Noise_voronoi(), Matrix_decompose(), Matrix_mul(), Matrix_to_scale(), Matrix_to_translation(), pyrna_math_object_from_array(), pyrna_param_to_py(), Quaternion_axis_vector_get(), Quaternion_mul(), Quaternion_to_axis_angle(), Vector_copy(), Vector_CreatePyObject_alloc(), Vector_CreatePyObject_cb(), Vector_cross(), Vector_mul(), Vector_new(), Vector_project(), Vector_reflect(), Vector_swizzle_get(), Vector_to_2d(), Vector_to_3d(), and Vector_to_4d().
PyObject* Vector_CreatePyObject_alloc (float * vec, const int size, PyTypeObject * base_type)
Definition at line 2937 of file mathutils_Vector.c.
References Py_NEW, Py_WRAP, and Vector_CreatePyObject().
Referenced by C_Vector_Fill(), C_Vector_Linspace(), C_Vector_Range(), C_Vector_Repeat(), Vector_add(), Vector_div(), Vector_lerp(), vector_mul_float(), Vector_neg(), Vector_resized(), and Vector_sub().
PyObject* Vector_CreatePyObject_cb (PyObject * user, int size, unsigned char cb_type, unsigned char subtype)
Definition at line 2922 of file mathutils_Vector.c.
References Py_NEW, and Vector_CreatePyObject().
Referenced by Matrix_item_col(), Matrix_item_row(), Matrix_slice(), Matrix_translation_get(), and pyrna_math_object_from_array().
Variable Documentation
PyTypeObject vector_Type
Definition at line 2791 of file mathutils_Vector.c.
Referenced by M_Geometry_area_tri(), M_Geometry_barycentric_transform(), M_Geometry_distance_point_to_plane(), M_Geometry_interpolate_bezier(), M_Geometry_intersect_line_line(), M_Geometry_intersect_line_line_2d(), M_Geometry_intersect_line_plane(), M_Geometry_intersect_line_sphere(), M_Geometry_intersect_line_sphere_2d(), M_Geometry_intersect_plane_plane(), M_Geometry_intersect_point_line(), M_Geometry_intersect_point_quad_2d(), M_Geometry_intersect_point_tri_2d(), M_Geometry_intersect_ray_tri(), M_Geometry_normal(), M_Geometry_tessellate_polygon(), and PyInit_mathutils().