Blender: EnvironmentTextureNode Class Reference
EnvironmentTextureNode Class Reference
#include <nodes.h>
Public Member Functions
~EnvironmentTextureNode ()
ShaderNode * clone () const
Public Attributes
ImageManager * image_manager
int slot
bool is_float
string filename
ustring color_space
ustring projection
Static Public Attributes
static ShaderEnum color_space_enum = color_space_init()
static ShaderEnum projection_enum = projection_init()
Detailed Description
Definition at line 74 of file nodes.h.
Constructor & Destructor Documentation
EnvironmentTextureNode::~EnvironmentTextureNode ()
Definition at line 221 of file nodes.cpp.
References filename, image_manager, and ImageManager::remove_image().
Member Function Documentation
ShaderNode * EnvironmentTextureNode::clone () const [virtual]
Implements ShaderNode.
Definition at line 227 of file nodes.cpp.
References image_manager, is_float, NULL, and slot.
Member Data Documentation
ustring EnvironmentTextureNode::color_space
Definition at line 84 of file nodes.h.
ShaderEnum EnvironmentTextureNode::color_space_enum = color_space_init() [static]
Definition at line 87 of file nodes.h.
Referenced by add_node().
string EnvironmentTextureNode::filename
Definition at line 83 of file nodes.h.
Referenced by xml_read_shader_graph(), and ~EnvironmentTextureNode().
ImageManager* EnvironmentTextureNode::image_manager
Definition at line 80 of file nodes.h.
Referenced by clone(), and ~EnvironmentTextureNode().
bool EnvironmentTextureNode::is_float
Definition at line 82 of file nodes.h.
Referenced by clone().
ustring EnvironmentTextureNode::projection
Definition at line 85 of file nodes.h.
ShaderEnum EnvironmentTextureNode::projection_enum = projection_init() [static]
Definition at line 88 of file nodes.h.
Referenced by add_node().
int EnvironmentTextureNode::slot
Definition at line 81 of file nodes.h.
Referenced by clone().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp