Blender: ED_keyframes_edit.h File Reference
ED_keyframes_edit.h File Reference
Editors
Classes
struct KeyframeEditData
struct KeyframeEditCD_Remap
Defines
#define BEZ_SEL(bezt) { (bezt)->f1 |= SELECT; (bezt)->f2 |= SELECT; (bezt)->f3 |= SELECT; }
#define BEZ_DESEL(bezt) { (bezt)->f1 &= ~SELECT; (bezt)->f2 &= ~SELECT; (bezt)->f3 &= ~SELECT; }
#define BEZ_INVSEL(bezt) { (bezt)->f1 ^= SELECT; (bezt)->f2 ^= SELECT; (bezt)->f3 ^= SELECT; }
Typedefs
typedef enum
eEditKeyframes_Validate eEditKeyframes_Validate
typedef enum eEditKeyframes_Select eEditKeyframes_Select
typedef enum eEditKeyframes_SelMap eEditKeyframes_SelMap
typedef enum eEditKeyframes_Snap eEditKeyframes_Snap
typedef enum eEditKeyframes_Mirror eEditKeyframes_Mirror
typedef struct KeyframeEditData KeyframeEditData
typedef void(* FcuEditFunc)(struct FCurve *fcu)
typedef short(* KeyframeEditFunc)(KeyframeEditData *ked, struct BezTriple *bezt)
typedef enum eKeyframeVertOk eKeyframeVertOk
typedef enum eKeyframeIterFlags eKeyframeIterFlags
typedef struct KeyframeEditCD_Remap KeyframeEditCD_Remap
typedef enum eKeyPasteOffset eKeyPasteOffset
typedef enum eKeyMergeMode eKeyMergeMode
Enumerations
enum eEditKeyframes_Validate {
BEZT_OK_FRAME = 1, BEZT_OK_FRAMERANGE, BEZT_OK_SELECTED, BEZT_OK_VALUE,
BEZT_OK_VALUERANGE, BEZT_OK_REGION
}
enum eEditKeyframes_Select { SELECT_REPLACE = (1<<0), SELECT_ADD = (1<<1), SELECT_SUBTRACT = (1<<2), SELECT_INVERT = (1<<3) }
enum eEditKeyframes_SelMap { SELMAP_MORE = 0, SELMAP_LESS }
enum eEditKeyframes_Snap {
SNAP_KEYS_CURFRAME = 1, SNAP_KEYS_NEARFRAME, SNAP_KEYS_NEARSEC, SNAP_KEYS_NEARMARKER,
SNAP_KEYS_HORIZONTAL, SNAP_KEYS_VALUE
}
enum eEditKeyframes_Mirror {
MIRROR_KEYS_CURFRAME = 1, MIRROR_KEYS_YAXIS, MIRROR_KEYS_XAXIS, MIRROR_KEYS_MARKER,
MIRROR_KEYS_VALUE
}
enum eKeyframeVertOk { KEYFRAME_OK_KEY = (1<<0), KEYFRAME_OK_H1 = (1<<1), KEYFRAME_OK_H2 = (1<<2), KEYFRAME_OK_ALL = (KEYFRAME_OK_KEY|KEYFRAME_OK_H1|KEYFRAME_OK_H2) }
enum eKeyframeIterFlags { KEYFRAME_ITER_INCL_HANDLES = (1<<0) }
enum eKeyPasteOffset { KEYFRAME_PASTE_OFFSET_CFRA_START, KEYFRAME_PASTE_OFFSET_CFRA_END, KEYFRAME_PASTE_OFFSET_CFRA_RELATIVE, KEYFRAME_PASTE_OFFSET_NONE }
enum eKeyMergeMode { KEYFRAME_PASTE_MERGE_MIX, KEYFRAME_PASTE_MERGE_OVER, KEYFRAME_PASTE_MERGE_OVER_RANGE, KEYFRAME_PASTE_MERGE_OVER_RANGE_ALL }
Functions
short ANIM_fcurve_keyframes_loop (KeyframeEditData *ked, struct FCurve *fcu, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
short ANIM_animchannel_keyframes_loop (KeyframeEditData *ked, struct bDopeSheet *ads, struct bAnimListElem *ale, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
short ANIM_animchanneldata_keyframes_loop (KeyframeEditData *ked, struct bDopeSheet *ads, void *data, int keytype, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
void ANIM_editkeyframes_refresh (struct bAnimContext *ac)
KeyframeEditFunc ANIM_editkeyframes_ok (short mode)
KeyframeEditFunc ANIM_editkeyframes_snap (short mode)
KeyframeEditFunc ANIM_editkeyframes_mirror (short mode)
KeyframeEditFunc ANIM_editkeyframes_select (short mode)
KeyframeEditFunc ANIM_editkeyframes_handles (short mode)
KeyframeEditFunc ANIM_editkeyframes_ipo (short mode)
KeyframeEditFunc ANIM_editkeyframes_keytype (short mode)
KeyframeEditFunc ANIM_editkeyframes_buildselmap (short mode)
short bezt_selmap_flush (KeyframeEditData *ked, struct BezTriple *bezt)
short bezt_calc_average (KeyframeEditData *ked, struct BezTriple *bezt)
short bezt_to_cfraelem (KeyframeEditData *ked, struct BezTriple *bezt)
void bezt_remap_times (KeyframeEditData *ked, struct BezTriple *bezt)
void delete_fcurve_key (struct FCurve *fcu, int index, short do_recalc)
void delete_fcurve_keys (struct FCurve *fcu)
void clear_fcurve_keys (struct FCurve *fcu)
void duplicate_fcurve_keys (struct FCurve *fcu)
void clean_fcurve (struct FCurve *fcu, float thresh)
void smooth_fcurve (struct FCurve *fcu)
void sample_fcurve (struct FCurve *fcu)
void free_anim_copybuf (void)
short copy_animedit_keys (struct bAnimContext *ac, ListBase *anim_data)
short paste_animedit_keys (struct bAnimContext *ac, ListBase *anim_data, const eKeyPasteOffset offset_mode, const eKeyMergeMode merge_mode)
Detailed Description
Definition in file ED_keyframes_edit.h.
Define Documentation
#define BEZ_DESEL (bezt) { (bezt)->f1 &= ~SELECT; (bezt)->f2 &= ~SELECT; (bezt)->f3 &= ~SELECT; }
Definition at line 47 of file ED_keyframes_edit.h.
Referenced by bezt_selmap_flush(), duplicate_fcurve_keys(), mouse_graph_keys(), and select_bezier_subtract().
#define BEZ_INVSEL (bezt) { (bezt)->f1 ^= SELECT; (bezt)->f2 ^= SELECT; (bezt)->f3 ^= SELECT; }
Definition at line 48 of file ED_keyframes_edit.h.
#define BEZ_SEL (bezt) { (bezt)->f1 |= SELECT; (bezt)->f2 |= SELECT; (bezt)->f3 |= SELECT; }
Definition at line 46 of file ED_keyframes_edit.h.
Referenced by bezt_selmap_flush(), copy_animedit_keys(), duplicate_fcurve_keys(), mouse_graph_keys(), and select_bezier_add().
Typedef Documentation
typedef enum eEditKeyframes_Mirror eEditKeyframes_Mirror
typedef enum eEditKeyframes_Select eEditKeyframes_Select
typedef enum eEditKeyframes_SelMap eEditKeyframes_SelMap
typedef enum eEditKeyframes_Snap eEditKeyframes_Snap
typedef enum eEditKeyframes_Validate eEditKeyframes_Validate
typedef enum eKeyframeIterFlags eKeyframeIterFlags
typedef enum eKeyframeVertOk eKeyframeVertOk
typedef enum eKeyMergeMode eKeyMergeMode
typedef enum eKeyPasteOffset eKeyPasteOffset
typedef void(* FcuEditFunc)(struct FCurve *fcu)
Definition at line 126 of file ED_keyframes_edit.h.
typedef struct KeyframeEditCD_Remap KeyframeEditCD_Remap
typedef struct KeyframeEditData KeyframeEditData
typedef short(* KeyframeEditFunc)(KeyframeEditData *ked, struct BezTriple *bezt)
Definition at line 128 of file ED_keyframes_edit.h.
Enumeration Type Documentation
enum eEditKeyframes_Mirror
Enumerator:
MIRROR_KEYS_CURFRAME
MIRROR_KEYS_YAXIS
MIRROR_KEYS_XAXIS
MIRROR_KEYS_MARKER
MIRROR_KEYS_VALUE
Definition at line 93 of file ED_keyframes_edit.h.
enum eEditKeyframes_Select
Enumerator:
SELECT_REPLACE
SELECT_ADD
SELECT_SUBTRACT
SELECT_INVERT
Definition at line 65 of file ED_keyframes_edit.h.
enum eEditKeyframes_SelMap
Enumerator:
SELMAP_MORE
SELMAP_LESS
Definition at line 77 of file ED_keyframes_edit.h.
enum eEditKeyframes_Snap
Enumerator:
SNAP_KEYS_CURFRAME
SNAP_KEYS_NEARFRAME
SNAP_KEYS_NEARSEC
SNAP_KEYS_NEARMARKER
SNAP_KEYS_HORIZONTAL
SNAP_KEYS_VALUE
Definition at line 83 of file ED_keyframes_edit.h.
enum eEditKeyframes_Validate
Enumerator:
BEZT_OK_FRAME
BEZT_OK_FRAMERANGE
BEZT_OK_SELECTED
BEZT_OK_VALUE
BEZT_OK_VALUERANGE
BEZT_OK_REGION
Definition at line 53 of file ED_keyframes_edit.h.
enum eKeyframeIterFlags
Enumerator:
KEYFRAME_ITER_INCL_HANDLES
Definition at line 145 of file ED_keyframes_edit.h.
enum eKeyframeVertOk
Enumerator:
KEYFRAME_OK_KEY
KEYFRAME_OK_H1
KEYFRAME_OK_H2
KEYFRAME_OK_ALL
Definition at line 133 of file ED_keyframes_edit.h.
enum eKeyMergeMode
Enumerator:
KEYFRAME_PASTE_MERGE_MIX
KEYFRAME_PASTE_MERGE_OVER
KEYFRAME_PASTE_MERGE_OVER_RANGE
KEYFRAME_PASTE_MERGE_OVER_RANGE_ALL
Definition at line 170 of file ED_keyframes_edit.h.
enum eKeyPasteOffset
Enumerator:
KEYFRAME_PASTE_OFFSET_CFRA_START
KEYFRAME_PASTE_OFFSET_CFRA_END
KEYFRAME_PASTE_OFFSET_CFRA_RELATIVE
KEYFRAME_PASTE_OFFSET_NONE
Definition at line 159 of file ED_keyframes_edit.h.
Function Documentation
short ANIM_animchannel_keyframes_loop (KeyframeEditData * ked, struct bDopeSheet * ads, struct bAnimListElem * ale, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
Definition at line 317 of file keyframes_edit.c.
References act_keyframes_loop(), agrp_keyframes_loop(), ALE_ACT, ALE_ALL, ALE_FCURVE, ALE_GROUP, ALE_OB, ALE_SCE, ANIM_fcurve_keyframes_loop(), bAnimListElem::data, bAnimListElem::datatype, bAnimListElem::key_data, NULL, ob_keyframes_loop(), scene_keyframes_loop(), and summary_keyframes_loop().
Referenced by actkeys_mselect_single(), and borderselect_action().
short ANIM_animchanneldata_keyframes_loop (KeyframeEditData * ked, struct bDopeSheet * ads, void * data, int keytype, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
Definition at line 349 of file keyframes_edit.c.
References act_keyframes_loop(), agrp_keyframes_loop(), ALE_ACT, ALE_ALL, ALE_FCURVE, ALE_GROUP, ALE_OB, ALE_SCE, ANIM_fcurve_keyframes_loop(), NULL, ob_keyframes_loop(), scene_keyframes_loop(), and summary_keyframes_loop().
Referenced by nlaedit_apply_scale_exec(), and poselib_apply_pose().
KeyframeEditFunc ANIM_editkeyframes_buildselmap (short mode)
Definition at line 1095 of file keyframes_edit.c.
References selmap_build_bezier_less(), selmap_build_bezier_more(), SELMAP_LESS, and SELMAP_MORE.
Referenced by select_moreless_action_keys(), and select_moreless_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_handles (short mode)
Definition at line 833 of file keyframes_edit.c.
References bezier_isfree(), HD_ALIGN, HD_AUTO, HD_AUTO_ANIM, HD_FREE, HD_VECT, set_bezier_align(), set_bezier_auto(), set_bezier_auto_clamped(), set_bezier_free(), and set_bezier_vector().
Referenced by sethandles_action_keys(), and sethandles_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_ipo (short mode)
Definition at line 878 of file keyframes_edit.c.
References BEZT_IPO_CONST, BEZT_IPO_LIN, set_bezt_bezier(), set_bezt_constant(), and set_bezt_linear().
Referenced by setipo_action_keys(), and setipo_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_keytype (short mode)
Definition at line 921 of file keyframes_edit.c.
References BEZT_KEYTYPE_BREAKDOWN, BEZT_KEYTYPE_EXTREME, BEZT_KEYTYPE_JITTER, BEZT_KEYTYPE_KEYFRAME, set_keytype_breakdown(), set_keytype_extreme(), set_keytype_jitter(), and set_keytype_keyframe().
Referenced by setkeytype_action_keys().
KeyframeEditFunc ANIM_editkeyframes_mirror (short mode)
Definition at line 739 of file keyframes_edit.c.
References mirror_bezier_cframe(), mirror_bezier_marker(), mirror_bezier_value(), mirror_bezier_xaxis(), mirror_bezier_yaxis(), MIRROR_KEYS_CURFRAME, MIRROR_KEYS_MARKER, MIRROR_KEYS_VALUE, MIRROR_KEYS_XAXIS, and MIRROR_KEYS_YAXIS.
Referenced by mirror_action_keys(), and mirror_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_ok (short mode)
Definition at line 520 of file keyframes_edit.c.
References BEZT_OK_FRAME, BEZT_OK_FRAMERANGE, BEZT_OK_REGION, BEZT_OK_SELECTED, BEZT_OK_VALUE, BEZT_OK_VALUERANGE, NULL, ok_bezier_frame(), ok_bezier_framerange(), ok_bezier_region(), ok_bezier_selected(), ok_bezier_value(), and ok_bezier_valuerange().
Referenced by actkeys_mselect_column(), actkeys_mselect_single(), actkeys_select_leftright(), actkeys_select_linked_exec(), ANIM_unit_mapping_apply_fcurve(), borderselect_action(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), copy_animedit_keys(), deselect_action_keys(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), markers_selectkeys_between(), poselib_apply_pose(), sethandles_action_keys(), and sethandles_graph_keys().
void ANIM_editkeyframes_refresh (struct bAnimContext * ac)
Definition at line 385 of file keyframes_edit.c.
References ANIM_animdata_filter(), ANIMFILTER_DATA_VISIBLE, BLI_freelistN(), bAnimContext::data, bAnimContext::datatype, FALSE, filter(), ListBase::first, SpaceIpo::flag, bAnimListElem::key_data, bAnimListElem::next, NULL, SIPO_NOHANDLES, bAnimContext::sl, sort_time_fcurve(), SPACE_IPO, bAnimContext::spacetype, and testhandles_fcurve().
Referenced by actkeys_clean_exec(), actkeys_delete_exec(), actkeys_duplicate_exec(), actkeys_expo_exec(), actkeys_handletype_exec(), actkeys_insertkey_exec(), actkeys_ipo_exec(), actkeys_keytype_exec(), actkeys_mirror_exec(), actkeys_paste_exec(), actkeys_sample_exec(), actkeys_snap_exec(), graph_fmodifier_add_exec(), graph_fmodifier_paste_exec(), graphkeys_bake_exec(), graphkeys_clean_exec(), graphkeys_delete_exec(), graphkeys_duplicate_exec(), graphkeys_euler_filter_exec(), graphkeys_expo_exec(), graphkeys_handletype_exec(), graphkeys_insertkey_exec(), graphkeys_ipo_exec(), graphkeys_mirror_exec(), graphkeys_paste_exec(), graphkeys_sample_exec(), graphkeys_smooth_exec(), graphkeys_snap_exec(), and special_aftertrans_update().
KeyframeEditFunc ANIM_editkeyframes_select (short mode)
Definition at line 993 of file keyframes_edit.c.
References SELECT_ADD, select_bezier_add(), select_bezier_invert(), select_bezier_subtract(), SELECT_INVERT, and SELECT_SUBTRACT.
Referenced by actkeys_mselect_column(), actkeys_mselect_single(), actkeys_select_leftright(), actkeys_select_linked_exec(), borderselect_action(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), deselect_action_keys(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), markers_selectkeys_between(), and mouse_graph_keys().
KeyframeEditFunc ANIM_editkeyframes_snap (short mode)
Definition at line 653 of file keyframes_edit.c.
References snap_bezier_cframe(), snap_bezier_horizontal(), snap_bezier_nearest(), snap_bezier_nearestsec(), snap_bezier_nearmarker(), snap_bezier_value(), SNAP_KEYS_CURFRAME, SNAP_KEYS_HORIZONTAL, SNAP_KEYS_NEARFRAME, SNAP_KEYS_NEARMARKER, SNAP_KEYS_NEARSEC, and SNAP_KEYS_VALUE.
Referenced by snap_action_keys(), and snap_graph_keys().
short ANIM_fcurve_keyframes_loop (KeyframeEditData * ked, struct FCurve * fcu, KeyframeEditFunc key_ok, KeyframeEditFunc key_cb, FcuEditFunc fcu_cb)
Definition at line 93 of file keyframes_edit.c.
References FCurve::bezt, KeyframeEditData::curflags, KeyframeEditData::curIndex, ELEM, KeyframeEditData::fcu, i, and NULL.
Referenced by act_keyframes_loop(), actkeys_framejump_exec(), actkeys_mselect_column(), actkeys_select_leftright(), actkeys_select_linked_exec(), agrp_keyframes_loop(), ANIM_animchannel_keyframes_loop(), ANIM_animchanneldata_keyframes_loop(), ANIM_nla_mapping_apply_fcurve(), ANIM_unit_mapping_apply_fcurve(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), copy_animedit_keys(), deselect_action_keys(), graphkeys_framejump_exec(), graphkeys_mselect_column(), graphkeys_select_leftright(), graphkeys_select_linked_exec(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), mouse_graph_keys(), ob_keyframes_loop(), scene_keyframes_loop(), select_moreless_action_keys(), select_moreless_graph_keys(), sethandles_action_keys(), sethandles_graph_keys(), setipo_action_keys(), setipo_graph_keys(), setkeytype_action_keys(), snap_action_keys(), snap_graph_keys(), and summary_keyframes_loop().
short bezt_calc_average (KeyframeEditData * ked, struct BezTriple * bezt)
Definition at line 545 of file keyframes_edit.c.
References KeyframeEditData::f1, BezTriple::f2, KeyframeEditData::f2, KeyframeEditData::i1, SELECT, and BezTriple::vec.
Referenced by actkeys_framejump_exec(), and graphkeys_framejump_exec().
void bezt_remap_times (KeyframeEditData * ked, struct BezTriple * bezt)
Definition at line 581 of file keyframes_edit.c.
References KeyframeEditData::data, KeyframeEditCD_Remap::newMax, KeyframeEditCD_Remap::newMin, KeyframeEditCD_Remap::oldMax, KeyframeEditCD_Remap::oldMin, and BezTriple::vec.
short bezt_selmap_flush (KeyframeEditData * ked, struct BezTriple * bezt)
Definition at line 1110 of file keyframes_edit.c.
References BEZ_DESEL, BEZ_SEL, KeyframeEditData::curIndex, and KeyframeEditData::data.
Referenced by select_moreless_action_keys(), and select_moreless_graph_keys().
short bezt_to_cfraelem (KeyframeEditData * ked, struct BezTriple * bezt)
Definition at line 565 of file keyframes_edit.c.
References BLI_addtail(), CfraElem::cfra, BezTriple::f2, KeyframeEditData::list, MEM_callocN(), SELECT, and BezTriple::vec.
Referenced by columnselect_action_keys(), and columnselect_graph_keys().
void clean_fcurve (struct FCurve * fcu, float thresh)
Definition at line 180 of file keyframes_general.c.
References FCurve::bezt, i, insert_vert_fcurve(), IS_EQT, MEM_freeN(), next, NULL, ActBeztColumn::prev, FCurve::totvert, and BezTriple::vec.
Referenced by clean_action_keys(), and clean_graph_keys().
void clear_fcurve_keys (struct FCurve * fcu)
Definition at line 130 of file keyframes_general.c.
References FCurve::bezt, MEM_freeN(), NULL, and FCurve::totvert.
Referenced by delete_fcurve_keys(), and paste_animedit_keys_fcurve().
short copy_animedit_keys (struct bAnimContext * ac, ListBase * anim_data)
Definition at line 509 of file keyframes_general.c.
References ANIM_editkeyframes_ok(), ANIM_fcurve_keyframes_loop(), animcopy_cfra, animcopy_firstframe, animcopy_lastframe, FCurve::array_index, BEZ_SEL, BEZSELECTED, tAnimCopybufItem::bezt, FCurve::bezt, BEZT_OK_SELECTED, BLI_addtail(), CFRA, ELEM, ListBase::first, free_anim_copybuf(), FCurve::grp, GS, i, bAnimListElem::id, if(), bAnimListElem::key_data, ListBase::last, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), ID::name, bAnimListElem::next, NULL, FCurve::rna_path, bAnimContext::scene, and tAnimCopybufItem::totvert.
Referenced by copy_action_keys(), and copy_graph_keys().
void delete_fcurve_key (struct FCurve * fcu, int index, short do_recalc)
Definition at line 77 of file keyframes_general.c.
References abs(), FCurve::bezt, calchandles_fcurve(), MEM_freeN(), NULL, and FCurve::totvert.
Referenced by delete_keyframe(), insert_keyframe_direct(), poselib_remove_exec(), and posttrans_fcurve_clean().
void delete_fcurve_keys (struct FCurve * fcu)
Definition at line 108 of file keyframes_general.c.
References FCurve::bezt, clear_fcurve_keys(), BezTriple::f2, i, NULL, SELECT, and FCurve::totvert.
Referenced by delete_action_keys(), delete_graph_keys(), and paste_animedit_keys_fcurve().
void duplicate_fcurve_keys (struct FCurve * fcu)
Definition at line 142 of file keyframes_general.c.
References BEZ_DESEL, BEZ_SEL, FCurve::bezt, ELEM, BezTriple::f2, i, MEM_callocN(), MEM_freeN(), NULL, SELECT, and FCurve::totvert.
Referenced by duplicate_action_keys(), and duplicate_graph_keys().
void free_anim_copybuf (void)
Definition at line 480 of file keyframes_general.c.
short paste_animedit_keys (struct bAnimContext * ac, ListBase * anim_data, const eKeyPasteOffset offset_mode, const eKeyMergeMode merge_mode)
Definition at line 763 of file keyframes_general.c.
References animcopy_cfra, animcopy_firstframe, animcopy_lastframe, BKE_report(), CFRA, bAnimListElem::data, ListBase::first, KEYFRAME_PASTE_OFFSET_CFRA_END, KEYFRAME_PASTE_OFFSET_CFRA_RELATIVE, KEYFRAME_PASTE_OFFSET_CFRA_START, KEYFRAME_PASTE_OFFSET_NONE, ListBase::last, bAnimListElem::next, NULL, paste_animedit_keys_fcurve(), pastebuf_match_index_only(), pastebuf_match_path_full(), pastebuf_match_path_property(), bAnimContext::reports, RPT_ERROR, and bAnimContext::scene.
Referenced by paste_action_keys(), and paste_graph_keys().
void sample_fcurve (struct FCurve * fcu)
Definition at line 383 of file keyframes_general.c.
References BEZKEYTYPE, BEZSELECTED, FCurve::bezt, BEZT_KEYTYPE_BREAKDOWN, calchandles_fcurve(), evaluate_fcurve(), i, insert_vert_fcurve(), MEM_callocN(), MEM_freeN(), NULL, and BezTriple::vec.
Referenced by sample_action_keys(), and sample_graph_keys().
void smooth_fcurve (struct FCurve * fcu)
Definition at line 285 of file keyframes_general.c.
References BEZSELECTED, FCurve::bezt, calchandles_fcurve(), ELEM, tSmooth_Bezt::h1, tSmooth_Bezt::h2, tSmooth_Bezt::h3, i, MEM_callocN(), MEM_freeN(), NULL, FCurve::totvert, BezTriple::vec, tSmooth_Bezt::y1, tSmooth_Bezt::y2, and tSmooth_Bezt::y3.
Referenced by graphkeys_smooth_exec().