Blender: graph_utils.c File Reference
graph_utils.c File Reference
graph editor
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include "DNA_anim_types.h"
#include "DNA_space_types.h"
#include "DNA_screen_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_rand.h"
#include "BKE_context.h"
#include "BKE_fcurve.h"
#include "WM_api.h"
#include "ED_anim_api.h"
#include "graph_intern.h"
Functions
bAnimListElem * get_active_fcurve_channel (bAnimContext *ac)
int graphop_visible_keyframes_poll (bContext *C)
int graphop_editable_keyframes_poll (bContext *C)
int graphop_active_fcurve_poll (bContext *C)
int graphop_selected_fcurve_poll (bContext *C)
Detailed Description
Definition in file graph_utils.c.
Function Documentation
bAnimListElem* get_active_fcurve_channel (bAnimContext * ac) [read]
Definition at line 68 of file graph_utils.c.
References ANIM_animdata_filter(), ANIMFILTER_ACTIVE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, BLI_freelistN(), BLI_remlink(), bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, and NULL.
Referenced by graph_fmodifier_copy_exec(), graph_panel_context(), graphkeys_click_insert_exec(), and graphop_active_fcurve_poll().
int graphop_active_fcurve_poll (bContext * C)
Definition at line 194 of file graph_utils.c.
References ANIM_animdata_get_context(), ANIMTYPE_FCURVE, CTX_wm_area(), bAnimListElem::data, tNearestVertInfo::fcu, FCURVE_VISIBLE, FCurve::flag, get_active_fcurve_channel(), MEM_freeN(), NULL, SPACE_IPO, ScrArea::spacetype, and bAnimListElem::type.
Referenced by GRAPH_OT_click_insert(), GRAPH_OT_fmodifier_copy(), and GRAPH_OT_fmodifier_paste().
int graphop_editable_keyframes_poll (bContext * C)
Definition at line 144 of file graph_utils.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, FCurve::bezt, BLI_freelistN(), CTX_wm_area(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, tNearestVertInfo::fcu, fcurve_is_keyframable(), filter(), ListBase::first, if(), bAnimListElem::next, NULL, SPACE_IPO, and ScrArea::spacetype.
Referenced by GRAPH_OT_clean(), GRAPH_OT_copy(), GRAPH_OT_delete(), GRAPH_OT_duplicate(), GRAPH_OT_euler_filter(), GRAPH_OT_extrapolation_type(), GRAPH_OT_handle_type(), GRAPH_OT_interpolation_type(), GRAPH_OT_keyframe_insert(), GRAPH_OT_mirror(), GRAPH_OT_paste(), GRAPH_OT_sample(), GRAPH_OT_smooth(), and GRAPH_OT_snap().
int graphop_selected_fcurve_poll (bContext * C)
Definition at line 229 of file graph_utils.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_SEL, BLI_freelistN(), CTX_wm_area(), bAnimContext::data, bAnimContext::datatype, filter(), NULL, SPACE_IPO, and ScrArea::spacetype.
Referenced by GRAPH_OT_bake(), GRAPH_OT_fmodifier_add(), and GRAPH_OT_sound_bake().
int graphop_visible_keyframes_poll (bContext * C)
Definition at line 95 of file graph_utils.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, FCurve::bezt, BLI_freelistN(), CTX_wm_area(), bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, tNearestVertInfo::fcu, fcurve_are_keyframes_usable(), filter(), ListBase::first, if(), bAnimListElem::next, NULL, SPACE_IPO, and ScrArea::spacetype.
Referenced by GRAPH_OT_clickselect(), GRAPH_OT_frame_jump(), GRAPH_OT_ghost_curves_create(), GRAPH_OT_select_all_toggle(), GRAPH_OT_select_border(), GRAPH_OT_select_column(), GRAPH_OT_select_leftright(), GRAPH_OT_select_less(), GRAPH_OT_select_linked(), and GRAPH_OT_select_more().