Blender: editmesh_rip.c File Reference
editmesh_rip.c File Reference
mesh
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "RNA_define.h"
#include "RNA_access.h"
#include "BLI_math.h"
#include "BLI_array.h"
#include "BKE_context.h"
#include "BKE_object.h"
#include "BKE_report.h"
#include "BKE_tessmesh.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "ED_view3d.h"
#include "mesh_intern.h"
Classes
struct EdgeLoopPair
Defines
#define IS_VISIT_POSSIBLE(e) (BM_edge_is_manifold(e) && BM_elem_flag_test(e, BM_ELEM_TAG))
#define IS_VISIT_DONE(e) ((e)->l && (BM_elem_index_get((e)->l) != INVALID_UID))
#define INVALID_UID INT_MIN
Typedefs
typedef struct EdgeLoopPair EdgeLoopPair
Functions
static float edbm_rip_rip_edgedist (ARegion *ar, float mat[][4], float *co1, float *co2, const float mvalf[2])
static float edbm_rip_edge_side_measure (BMEdge *e, BMLoop *e_l, ARegion *ar, float projectMat[4][4], const float fmval[2])
static BMEdge * edbm_ripsel_edge_mark_step (BMVert *v, const int uid)
static EdgeLoopPair * edbm_ripsel_looptag_helper (BMesh *bm)
static BMEdge * edbm_ripsel_edge_uid_step (BMEdge *e_orig, BMVert **v_prev)
static BMVert * edbm_ripsel_edloop_pair_start_vert (BMEdge *e)
static void edbm_ripsel_deselect_helper (BMesh *bm, EdgeLoopPair *eloop_pairs, ARegion *ar, float projectMat[4][4], float fmval[2])
static int edbm_rip_call_edgesplit (BMEditMesh *em, wmOperator *op)
static int edbm_rip_invoke__vert (bContext *C, wmOperator *op, wmEvent *event)
static int edbm_rip_invoke__edge (bContext *C, wmOperator *op, wmEvent *event)
static int edbm_rip_invoke (bContext *C, wmOperator *op, wmEvent *event)
void MESH_OT_rip (wmOperatorType *ot)
Detailed Description
Definition in file editmesh_rip.c.
Define Documentation
#define INVALID_UID INT_MIN
Definition at line 158 of file editmesh_rip.c.
Referenced by edbm_ripsel_looptag_helper().
#define IS_VISIT_DONE (e) ((e)->l && (BM_elem_index_get((e)->l) != INVALID_UID))
Definition at line 157 of file editmesh_rip.c.
Referenced by edbm_ripsel_edge_mark_step(), and edbm_ripsel_looptag_helper().
#define IS_VISIT_POSSIBLE (e) (BM_edge_is_manifold(e) && BM_elem_flag_test(e, BM_ELEM_TAG))
How rip selection works
Firstly - rip is basically edge split with side-selection & grab. Things would be much more simple if we didn't have to worry about side selection
The method used for checking the side of selection is as follows...
First tag all rip-able edges.
Build a contiguous edge list by looping over tagged edges and following each ones tagged siblings in both directions.
The loops are not stored in an array, Instead both loops on either side of each edge has its index values set to count down from the last edge, this way, once we have the 'last' edge its very easy to walk down the connected edge loops. The reason for using loops like this is because when the edges are split we don't which face user gets the newly created edge (its as good as random so we cant assume new edges will be on once side). After splittingm, its very simple to walk along boundary loops since each only has one edge from a single side.
The end loop pairs are stored in an array however to support multiple edge-selection-islands, so you can rip multiple selections at once.
* Execute the split *
For each EdgeLoopPair walk down both sides of the split using the loops and measure which is facing the mouse.
Deselect the edge loop facing away.
Limitation! This currently works very poorly with intersecting edge islands (verts with more then 2 tagged edges) This is nice to but for now not essential.
campbell.
Definition at line 156 of file editmesh_rip.c.
Referenced by edbm_ripsel_edge_mark_step(), and edbm_ripsel_looptag_helper().
Typedef Documentation
typedef struct EdgeLoopPair EdgeLoopPair
Function Documentation
static int edbm_rip_call_edgesplit (BMEditMesh * em, wmOperator * op) [static]
Definition at line 345 of file editmesh_rip.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_ELEM_TAG, BMO_op_exec(), EDBM_op_finish(), EDBM_op_init(), FALSE, and TRUE.
Referenced by edbm_rip_invoke__edge(), and edbm_rip_invoke__vert().
static float edbm_rip_edge_side_measure (BMEdge * e, BMLoop * e_l, ARegion * ar, float projectMat[4][4], const float fmval[2]) [static]
Definition at line 69 of file editmesh_rip.c.
References BLI_assert, BM_face_other_vert_loop(), BM_vert_in_edge(), BMVert::co, dist_to_line_segment_v2(), ED_view3d_project_float_v2(), BMLoop::f, len_v2v2(), mid_v3_v3v3(), mul_v2_fl(), normalize_v2(), sub_v2_v2v2(), BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by edbm_rip_invoke__edge(), and edbm_ripsel_deselect_helper().
static int edbm_rip_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 700 of file editmesh_rip.c.
References BKE_report(), BLI_assert, BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_SELECT, BM_ELEM_TAG, BM_ITER_MESH, BMEdit_FromObject(), CTX_data_edit_object(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, RPT_ERROR, BMesh::totedgesel, BMesh::totfacesel, BMesh::totvertsel, and TRUE.
Referenced by MESH_OT_rip().
static int edbm_rip_invoke__edge (bContext * C, wmOperator * op, wmEvent * event) [static]
This is the main edge ripping function
BM_vert_other_disk_edge has no hidden checks so don't check hidden here
Definition at line 592 of file editmesh_rip.c.
References BKE_report(), BMEditMesh::bm, BM_edge_is_manifold(), BM_edge_is_wire(), BM_EDGES_OF_VERT, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_face_other_edge_loop(), BM_ITER_ELEM, BM_ITER_MESH, BM_vert_other_disk_edge(), BM_VERTS_OF_MESH, BMEdit_FromObject(), CTX_data_edit_object(), CTX_wm_region(), CTX_wm_region_view3d(), BMLoop::e, ED_view3d_ob_project_mat_get(), edbm_rip_call_edgesplit(), edbm_rip_edge_side_measure(), edbm_ripsel_deselect_helper(), edbm_ripsel_looptag_helper(), EDBM_selectmode_flush(), BMLoop::f, FALSE, i, BMEdge::l, MEM_freeN(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, BMLoop::radial_next, wmOperator::reports, RPT_ERROR, BMesh::totedge, and TRUE.
Referenced by edbm_rip_invoke().
static int edbm_rip_invoke__vert (bContext * C, wmOperator * op, wmEvent * event) [static]
This is the main vert ripping function (rip when one vertex is selected)
Definition at line 364 of file editmesh_rip.c.
References add_v3_v3(), add_v3_v3v3(), BKE_report(), BLI_assert, BMEditMesh::bm, BM_edge_calc_length(), BM_edge_is_boundary(), BM_edge_is_manifold(), BM_edge_is_wire(), BM_EDGES_OF_VERT, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_face_other_edge_loop(), BM_face_vert_separate(), BM_ITER_ELEM, BM_ITER_MESH, BM_loop_calc_face_tangent(), BM_LOOPS_OF_VERT, BM_select_history_active_get(), BM_select_history_remove, BM_select_history_store, BM_VERT, BM_vert_face_count(), BM_vert_select_set(), BM_vert_splice(), BM_VERTS_OF_MESH, BMEdit_FromObject(), bmesh_vert_separate(), BMVert::co, CTX_data_edit_object(), CTX_wm_region(), CTX_wm_region_view3d(), BMLoop::e, BMVert::e, ED_view3d_ob_project_mat_get(), edbm_rip_call_edgesplit(), edbm_rip_rip_edgedist(), BMEditSelection::ele, BMLoop::f, FALSE, FLT_MAX, BMEditSelection::htype, i, BMEdge::l, MEM_freeN(), mul_v3_fl(), BMLoop::next, normalize_v3(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, BMLoop::prev, BMLoop::radial_next, wmOperator::reports, RPT_ERROR, sub_v3_v3v3(), SWAP, BMesh::totvert, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by edbm_rip_invoke().
static float edbm_rip_rip_edgedist (ARegion * ar, float mat[][4], float * co1, float * co2, const float mvalf[2]) [static]
Definition at line 59 of file editmesh_rip.c.
References dist_to_line_segment_v2(), and ED_view3d_project_float_v2().
Referenced by edbm_rip_invoke__vert().
static void edbm_ripsel_deselect_helper (BMesh * bm, EdgeLoopPair * eloop_pairs, ARegion * ar, float projectMat[4][4], float fmval[2]) [static]
Definition at line 313 of file editmesh_rip.c.
References BM_edge_select_set(), BMLoop::e, edbm_rip_edge_side_measure(), edbm_ripsel_edge_uid_step(), edbm_ripsel_edloop_pair_start_vert(), FALSE, BMEdge::l, EdgeLoopPair::l_a, and EdgeLoopPair::l_b.
Referenced by edbm_rip_invoke__edge().
static BMEdge* edbm_ripsel_edge_mark_step (BMVert * v, const int uid) [static]
Definition at line 161 of file editmesh_rip.c.
References BM_edge_loop_pair(), BM_EDGES_OF_VERT, BM_elem_index_set, BM_ITER_ELEM, IS_VISIT_DONE, IS_VISIT_POSSIBLE, and NULL.
Referenced by edbm_ripsel_looptag_helper().
static BMEdge* edbm_ripsel_edge_uid_step (BMEdge * e_orig, BMVert ** v_prev) [static]
Definition at line 290 of file editmesh_rip.c.
References BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_elem_index_get, BM_ITER_ELEM, BMEdge::l, and NULL.
Referenced by edbm_ripsel_deselect_helper(), and edbm_ripsel_edloop_pair_start_vert().
static BMVert* edbm_ripsel_edloop_pair_start_vert (BMEdge * e) [static]
Definition at line 306 of file editmesh_rip.c.
References edbm_ripsel_edge_uid_step(), BMEdge::v1, and BMEdge::v2.
Referenced by edbm_ripsel_deselect_helper().
static EdgeLoopPair* edbm_ripsel_looptag_helper (BMesh * bm) [static]
Definition at line 186 of file editmesh_rip.c.
References BLI_array_count, BLI_array_declare, BLI_array_growone, BLI_assert, BM_edge_loop_pair(), BM_edge_other_vert(), BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_index_set, BM_ELEM_SMOOTH, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, edbm_ripsel_edge_mark_step(), INVALID_UID, IS_VISIT_DONE, IS_VISIT_POSSIBLE, EdgeLoopPair::l_a, EdgeLoopPair::l_b, NULL, BMesh::totedge, TRUE, and BMEdge::v1.
Referenced by edbm_rip_invoke__edge().
void MESH_OT_rip (wmOperatorType * ot)
Definition at line 759 of file editmesh_rip.c.
References wmOperatorType::description, edbm_rip_invoke(), EM_view3d_poll(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, P_PROPORTIONAL, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, and Transform_Properties().
Referenced by ED_operatortypes_mesh().