Blender: transform_conversions.c File Reference
transform_conversions.c File Reference
transform
#include <unistd.h>
#include <string.h>
#include <math.h>
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_lattice_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meta_types.h"
#include "DNA_node_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_sequence_types.h"
#include "DNA_view3d_types.h"
#include "DNA_constraint_types.h"
#include "DNA_scene_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_movieclip_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_array.h"
#include "BLI_utildefines.h"
#include "BLI_smallhash.h"
#include "BKE_DerivedMesh.h"
#include "BKE_action.h"
#include "BKE_armature.h"
#include "BKE_bmesh.h"
#include "BKE_constraint.h"
#include "BKE_context.h"
#include "BKE_curve.h"
#include "BKE_depsgraph.h"
#include "BKE_fcurve.h"
#include "BKE_global.h"
#include "BKE_gpencil.h"
#include "BKE_key.h"
#include "BKE_main.h"
#include "BKE_modifier.h"
#include "BKE_movieclip.h"
#include "BKE_nla.h"
#include "BKE_node.h"
#include "BKE_object.h"
#include "BKE_particle.h"
#include "BKE_pointcache.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_sequencer.h"
#include "BKE_tessmesh.h"
#include "BKE_tracking.h"
#include "ED_anim_api.h"
#include "ED_armature.h"
#include "ED_particle.h"
#include "ED_image.h"
#include "ED_keyframing.h"
#include "ED_keyframes_edit.h"
#include "ED_object.h"
#include "ED_markers.h"
#include "ED_mesh.h"
#include "ED_node.h"
#include "ED_types.h"
#include "ED_uvedit.h"
#include "ED_clip.h"
#include "ED_util.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "RNA_access.h"
#include "transform.h"
#include "bmesh.h"
#include "BLO_sys_types.h"
Classes
struct tGPFtransdata
struct BeztMap
struct TransDataTracking
Defines
#define THRESHOLDFACTOR (1.0f-0.0001f)
#define SEQ_TX_NESTED_METAS
#define XXX_DURIAN_ANIM_TX_HACK
Typedefs
typedef struct tGPFtransdata tGPFtransdata
typedef struct BeztMap BeztMap
typedef struct TransDataTracking TransDataTracking
Enumerations
enum { transDataTracking_ModeTracks = 0, transDataTracking_ModeCurves = 1 }
Functions
static short constraints_list_needinv (TransInfo *t, ListBase *list)
static void qsort_trans_data (TransInfo *t, TransData *head, TransData *tail, TransData *temp)
void sort_trans_data_dist (TransInfo *t)
static void sort_trans_data (TransInfo *t)
static void set_prop_dist (TransInfo *t, short with_dist)
static void createTransTexspace (TransInfo *t)
static void createTransEdge (TransInfo *t)
static bKinematicConstraint * has_targetless_ik (bPoseChannel *pchan)
static short apply_targetless_ik (Object *ob)
static void add_pose_transdata (TransInfo *t, bPoseChannel *pchan, Object *ob, TransData *td)
static void bone_children_clear_transflag (int mode, short around, ListBase *lb)
int count_set_pose_transflags (int *out_mode, short around, Object *ob)
static void pchan_autoik_adjust (bPoseChannel *pchan, short chainlen)
void transform_autoik_update (TransInfo *t, short mode)
static void pose_grab_with_ik_clear (Object *ob)
static short pose_grab_with_ik_add (bPoseChannel *pchan)
static short pose_grab_with_ik_children (bPose *pose, Bone *bone)
static short pose_grab_with_ik (Object *ob)
static void createTransPose (TransInfo *t, Object *ob)
static void createTransArmatureVerts (TransInfo *t)
static void createTransMBallVerts (TransInfo *t)
static void calc_distanceCurveVerts (TransData *head, TransData *tail)
static TransDataCurveHandleFlags * initTransDataCurveHandles (TransData *td, struct BezTriple *bezt)
static void createTransCurveVerts (bContext *C, TransInfo *t)
static void createTransLatticeVerts (TransInfo *t)
static void createTransParticleVerts (bContext *C, TransInfo *t)
void flushTransParticles (TransInfo *t)
static void editmesh_set_connectivity_distance (BMEditMesh *em, float mtx[][3], float *dists)
static void get_face_center (float cent_r[3], BMVert *eve)
static void get_edge_center (float cent_r[3], BMVert *eve)
static void VertsToTransData (TransInfo *t, TransData *td, BMEditMesh *em, BMVert *eve, float *bweight)
static void createTransEditVerts (bContext *C, TransInfo *t)
void flushTransNodes (TransInfo *t)
void flushTransSeq (TransInfo *t)
static void UVsToTransData (SpaceImage *sima, TransData *td, TransData2D *td2d, float *uv, int selected)
static void createTransUVs (bContext *C, TransInfo *t)
void flushTransUVs (TransInfo *t)
int clipUVTransform (TransInfo *t, float *vec, int resize)
static short FrameOnMouseSide (char side, float frame, float cframe)
static void createTransNlaData (bContext *C, TransInfo *t)
static void posttrans_gpd_clean (bGPdata *gpd)
static void posttrans_fcurve_clean (FCurve *fcu, const short use_handle)
static void posttrans_action_clean (bAnimContext *ac, bAction *act)
static int count_fcurve_keys (FCurve *fcu, char side, float cfra)
static int count_gplayer_frames (bGPDlayer *gpl, char side, float cfra)
static void TimeToTransData (TransData *td, float *time, AnimData *adt)
static TransData * ActionFCurveToTransData (TransData *td, TransData2D **td2dv, FCurve *fcu, AnimData *adt, char side, float cfra)
void flushTransGPactionData (TransInfo *t)
static int GPLayerToTransData (TransData *td, tGPFtransdata *tfd, bGPDlayer *gpl, char side, float cfra)
static void createTransActionData (bContext *C, TransInfo *t)
static void bezt_to_transdata (TransData *td, TransData2D *td2d, AnimData *adt, BezTriple *bezt, int bi, short selected, short ishandle, short intvals, float mtx[3][3], float smtx[3][3])
static void createTransGraphEditData (bContext *C, TransInfo *t)
static BeztMap * bezt_to_beztmaps (BezTriple *bezts, int totvert, const short UNUSED(use_handle))
static void sort_time_beztmaps (BeztMap *bezms, int totvert, const short UNUSED(use_handle))
static void beztmap_to_data (TransInfo *t, FCurve *fcu, BeztMap *bezms, int totvert, const short UNUSED(use_handle))
void remake_graph_transdata (TransInfo *t, ListBase *anim_data)
void flushTransGraphData (TransInfo *t)
static void SeqTransInfo (TransInfo *t, Sequence *seq, int *recursive, int *count, int *flag)
static int SeqTransCount (TransInfo *t, Sequence *parent, ListBase *seqbase, int depth)
static TransData * SeqToTransData (TransData *td, TransData2D *td2d, TransDataSeq *tdsq, Sequence *seq, int flag, int sel_flag)
static int SeqToTransData_Recursive (TransInfo *t, ListBase *seqbase, TransData *td, TransData2D *td2d, TransDataSeq *tdsq)
static void freeSeqData (TransInfo *t)
static void createTransSeqData (bContext *C, TransInfo *t)
static void ObjectToTransData (TransInfo *t, TransData *td, Object *ob)
static void set_trans_object_base_flags (TransInfo *t)
static int mark_children (Object *ob)
static int count_proportional_objects (TransInfo *t)
static void clear_trans_object_base_flags (TransInfo *t)
void autokeyframe_ob_cb_func (bContext *C, Scene *scene, View3D *v3d, Object *ob, int tmode)
void autokeyframe_pose_cb_func (bContext *C, Scene *scene, View3D *v3d, Object *ob, int tmode, short targetless_ik)
void special_aftertrans_update (bContext *C, TransInfo *t)
static void createTransObject (bContext *C, TransInfo *t)
static void NodeToTransData (TransData *td, TransData2D *td2d, bNode *node)
static void createTransNodeData (bContext *C, TransInfo *t)
static void markerToTransDataInit (TransData *td, TransData2D *td2d, TransDataTracking *tdt, MovieTrackingTrack *track, int area, float *loc, float *rel, float *off)
static void trackToTransData (SpaceClip *sc, TransData *td, TransData2D *td2d, TransDataTracking *tdt, MovieTrackingTrack *track)
static void transDataTrackingFree (TransInfo *t)
static void createTransTrackingTracksData (bContext *C, TransInfo *t)
static void markerToTransCurveDataInit (TransData *td, TransData2D *td2d, TransDataTracking *tdt, MovieTrackingMarker *marker, MovieTrackingMarker *prev_marker, short coord, float size)
static void createTransTrackingCurvesData (bContext *C, TransInfo *t)
static void createTransTrackingData (bContext *C, TransInfo *t)
static void cancelTransTracking (TransInfo *t)
void flushTransTracking (TransInfo *t)
void createTransData (bContext *C, TransInfo *t)
Variables
enum { ... } transDataTracking_Mode
Detailed Description
Definition in file transform_conversions.c.
Define Documentation
#define SEQ_TX_NESTED_METAS
Definition at line 2292 of file transform_conversions.c.
#define THRESHOLDFACTOR (1.0f-0.0001f)
Definition at line 1867 of file transform_conversions.c.
#define XXX_DURIAN_ANIM_TX_HACK
Typedef Documentation
typedef struct BeztMap BeztMap
typedef struct tGPFtransdata tGPFtransdata
typedef struct TransDataTracking TransDataTracking
Enumeration Type Documentation
anonymous enum
Enumerator:
transDataTracking_ModeTracks
transDataTracking_ModeCurves
Definition at line 5424 of file transform_conversions.c.
Function Documentation
static TransData* ActionFCurveToTransData (TransData * td, TransData2D ** td2dv, FCurve * fcu, AnimData * adt, char side, float cfra) [static]
Definition at line 3042 of file transform_conversions.c.
References FCurve::bezt, copy_v2_v2(), ELEM, BezTriple::f2, TransData::flag, FrameOnMouseSide(), TransData2D::h1, TransData2D::h2, i, TransData2D::ih1, TransData2D::ih2, NULL, SELECT, TD_MOVEHANDLE1, TD_MOVEHANDLE2, TimeToTransData(), and BezTriple::vec.
Referenced by createTransActionData().
static void add_pose_transdata (TransInfo * t, bPoseChannel * pchan, Object * ob, TransData * td) [static]
Definition at line 526 of file transform_conversions.c.
References ARM_ENVELOPE, Bone::arm_mat, TransData::axismtx, bPoseChannel::bone, BONE_HINGE, BONE_HINGE_CHILD_TRANSFORM, Bone::bone_mat, BONE_NO_LOCAL_LOCATION, BONE_NO_SCALE, BONE_TRANSFORM_CHILD, TransData::center, TransData::con, bPoseChannel::constinv, CONSTRAINT_IK_AUTO, CONSTRAINT_IK_TIP, bPoseChannel::constraints, constraints_list_needinv(), copy_m3_m3(), copy_m3_m4(), copy_qt_qt(), copy_v3_v3(), data, Object::data, Bone::dist, bArmature::drawtype, ELEM, bPoseChannel::eul, TransData::ext, ListBase::first, bKinematicConstraint::flag, Bone::flag, TransData::flag, bKinematicConstraint::grabtarget, has_targetless_ik(), TransData::iloc, invert_m3_m3(), TransDataExtension::iquat, TransDataExtension::irot, TransDataExtension::irotAngle, TransDataExtension::irotAxis, TransDataExtension::isize, TransData::ival, TransDataExtension::l_smtx, bPoseChannel::loc, TransData::loc, mat4_to_size(), TransInfo::mode, TransData::mtx, mul_m3_m3m3(), mul_serie_m3(), normalize_m3(), NULL, TransData::ob, Object::obmat, bPoseChannel::parent, pchan_to_pose_mat(), bPoseChannel::pose_head, bPoseChannel::pose_mat, bPoseChannel::pose_tail, TransInfo::poseobj, bPoseChannel::protectflag, TransData::protectflag, bPoseChannel::quat, TransDataExtension::quat, TransDataExtension::rot, ROT_MODE_AXISANGLE, bPoseChannel::rotAngle, TransDataExtension::rotAngle, bPoseChannel::rotAxis, TransDataExtension::rotAxis, bPoseChannel::rotmode, TransDataExtension::rotOrder, bPoseChannel::size, TransDataExtension::size, size_to_mat3(), TransData::smtx, TD_NO_LOC, TD_NOCENTER, TD_PBONE_LOCAL_MTX_C, TD_PBONE_LOCAL_MTX_P, TD_SELECTED, TFM_BONESIZE, TFM_RESIZE, TFM_TRANSLATION, unit_m3(), TransData::val, and Bone::xwidth.
Referenced by createTransPose().
static short apply_targetless_ik (Object * ob) [static]
Definition at line 387 of file transform_conversions.c.
References Bone::arm_mat, armature_mat_pose_to_bone(), axis_angle_to_mat3(), bPoseChannel::bone, BONE_HINGE, Bone::bone_mat, BONE_NO_SCALE, BONE_TRANSFORM, bPose::chanbase, CONSTRAINT_IK_AUTO, CONSTRAINT_IK_STRETCH, CONSTRAINT_IK_TIP, copy_m3_m4(), copy_m4_m3(), copy_m4_m4(), copy_v3_v3(), data, bPoseChannel::eul, eulO_to_mat3(), ListBase::first, Bone::flag, bKinematicConstraint::flag, has_targetless_ik(), Bone::head, invert_m3_m3(), invert_m4_m4(), Bone::length, mat3_to_axis_angle(), mat3_to_eulO(), mat3_to_quat(), mat3_to_size(), mul_m3_m3m3(), mul_m4_v3(), mult_m4_m4m4(), bPoseChannel::next, normalize_m4(), bPoseChannel::parent, Object::pose, bPoseChannel::pose_mat, bPoseChannel::quat, quat_to_mat3(), bKinematicConstraint::rootbone, ROT_MODE_AXISANGLE, bPoseChannel::rotAngle, bPoseChannel::rotAxis, bPoseChannel::rotmode, and bPoseChannel::size.
Referenced by special_aftertrans_update().
void autokeyframe_ob_cb_func (bContext * C, Scene * scene, View3D * v3d, Object * ob, int tmode)
Definition at line 4632 of file transform_conversions.c.
References AnimData::action, Object::adt, ANIM_apply_keyingset(), ANIM_builtin_keyingset_get_named(), ANIM_get_keyframing_flags(), ANIM_KS_LOC_ROT_SCALE_ID, ANIM_KS_LOCATION_ID, ANIM_KS_ROTATION_ID, ANIM_KS_SCALING_ID, ANIM_relative_keyingset_add_source(), ANIM_scene_get_active_keyingset(), View3D::around, FCurve::array_index, autokeyframe_cfra_can_key(), BLI_freelistN(), CFRA, CTX_wm_reports(), bAction::curves, FCURVE_SELECTED, ListBase::first, View3D::flag, FCurve::flag, FCurve::grp, Object::id, insert_keyframe(), IS_AUTOKEY_FLAG, MODIFYKEY_MODE_INSERT, bActionGroup::name, FCurve::next, NULL, OBACT, FCurve::rna_path, TFM_RESIZE, TFM_ROTATION, TFM_TRANSLATION, V3D_ACTIVE, V3D_ALIGN, and V3D_CURSOR.
Referenced by recalcData_view3d(), and special_aftertrans_update().
void autokeyframe_pose_cb_func (bContext * C, Scene * scene, View3D * v3d, Object * ob, int tmode, short targetless_ik)
Definition at line 4730 of file transform_conversions.c.
References AnimData::action, Object::adt, ANIM_apply_keyingset(), ANIM_builtin_keyingset_get_named(), ANIM_get_keyframing_flags(), ANIM_KS_LOC_ROT_SCALE_ID, ANIM_KS_LOCATION_ID, ANIM_KS_ROTATION_ID, ANIM_KS_SCALING_ID, ANIM_relative_keyingset_add_source(), ANIM_scene_get_active_keyingset(), View3D::around, FCurve::array_index, autokeyframe_cfra_can_key(), bPose::avs, BLI_freelistN(), BLI_getQuotedStr(), BONE_TRANSFORM, BONE_UNKEYED, CFRA, CTX_wm_reports(), bAction::curves, ED_pose_recalculate_paths(), ELEM, ListBase::first, View3D::flag, FCurve::grp, Object::id, if(), insert_keyframe(), INSERTKEY_MATRIX, IS_AUTOKEY_FLAG, MEM_freeN(), MODIFYKEY_MODE_INSERT, MOTIONPATH_BAKE_HAS_PATHS, bActionGroup::name, FCurve::next, NULL, bAnimVizSettings::path_bakeflag, Object::pose, FCurve::rna_path, RNA_PoseBone, TFM_RESIZE, TFM_ROTATION, TFM_TRANSLATION, V3D_ACTIVE, V3D_ALIGN, and V3D_CURSOR.
Referenced by recalcData_view3d(), and special_aftertrans_update().
static BeztMap* bezt_to_beztmaps (BezTriple * bezts, int totvert, const short UNUSEDuse_handle) [static]
Definition at line 3601 of file transform_conversions.c.
References i, BezTriple::ipo, MEM_callocN(), and NULL.
Referenced by remake_graph_transdata().
static void bezt_to_transdata (TransData * td, TransData2D * td2d, AnimData * adt, BezTriple * bezt, int bi, short selected, short ishandle, short intvals, float mtx[3][3], float smtx[3][3]) [static]
Definition at line 3280 of file transform_conversions.c.
References TransData::axismtx, BKE_nla_tweakedit_remap(), TransData::center, copy_m3_m3(), copy_v2_v2(), copy_v3_v3(), TransData::dist, TransData::ext, TransData::extra, TransData::flag, TransData2D::h1, TransData2D::h2, TransData2D::ih1, TransData2D::ih2, TransData::iloc, TransData::loc, TransData2D::loc, TransData2D::loc2d, MAXFLOAT, TransData::mtx, NLATIME_CONVERT_MAP, NULL, TransData::smtx, TD_INTVALUES, TD_MOVEHANDLE1, TD_MOVEHANDLE2, TD_NOTIMESNAP, TD_SELECTED, TransData::val, and BezTriple::vec.
static void beztmap_to_data (TransInfo * t, FCurve * fcu, BeztMap * bezms, int totvert, const short UNUSEDuse_handle) [static]
Definition at line 3674 of file transform_conversions.c.
References FCurve::bezt, BeztMap::bezt, TransInfo::data, TransInfo::data2d, TransData::flag, TransDataCurveHandleFlags::h1, TransDataCurveHandleFlags::h2, TransData::hdata, i, MEM_callocN(), MEM_freeN(), BeztMap::newIndex, BeztMap::swapHs, TD_BEZTRIPLE, TransInfo::total, and BezTriple::vec.
Referenced by remake_graph_transdata().
static void bone_children_clear_transflag (int mode, short around, ListBase * lb) [static]
Definition at line 709 of file transform_conversions.c.
References BONE_CONNECTED, BONE_HINGE, BONE_HINGE_CHILD_TRANSFORM, BONE_TRANSFORM, BONE_TRANSFORM_CHILD, Bone::childbase, ListBase::first, Bone::flag, Bone::next, TFM_ROTATION, TFM_TRACKBALL, and V3D_LOCAL.
Referenced by count_set_pose_transflags().
static void calc_distanceCurveVerts (TransData * head, TransData * tail) [static]
Definition at line 1369 of file transform_conversions.c.
References TransData::center, TransData::dist, TransData::flag, len_v3v3(), MAXFLOAT, NULL, TD_NOTCONNECTED, and TD_SELECTED.
Referenced by createTransCurveVerts(), and createTransParticleVerts().
static void cancelTransTracking (TransInfo * t) [static]
Definition at line 5770 of file transform_conversions.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), TransInfo::customData, ED_space_clip(), ListBase::first, TransDataTracking::flag, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MovieClipUser::framenr, MARKER_DISABLED, MARKER_GRAPH_SEL_X, MARKER_GRAPH_SEL_Y, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, TransDataTracking::mode, MovieTrackingTrack::next, MovieTrackingTrack::pat_flag, TransInfo::sa, MovieTrackingTrack::search_flag, SELECT, ScrArea::spacedata, TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, transDataTracking_ModeCurves, transDataTracking_ModeTracks, and SpaceClip::user.
Referenced by flushTransTracking().
static void clear_trans_object_base_flags (TransInfo * t) [static]
Definition at line 4614 of file transform_conversions.c.
References BA_HAS_RECALC_DATA, BA_HAS_RECALC_OB, BA_TEMP_TAG, BA_TRANSFORM_CHILD, BA_TRANSFORM_PARENT, BA_WAS_SEL, Scene::base, ListBase::first, Base::flag, Base::next, TransInfo::scene, and SELECT.
Referenced by createTransObject(), and special_aftertrans_update().
int clipUVTransform (TransInfo * t, float * vec, int resize)
Definition at line 2529 of file transform_conversions.c.
References TransInfo::center, TransInfo::data, DO_MINMAX2, ED_space_image_uv_aspect(), ListBase::first, TransData::loc, max, min, TransInfo::sa, and ScrArea::spacedata.
Referenced by Resize(), and Translation().
static short constraints_list_needinv (TransInfo * t, ListBase * list) [static]
Definition at line 4314 of file transform_conversions.c.
References CONSTRAINT_DISABLE, CONSTRAINT_TYPE_CHILDOF, CONSTRAINT_TYPE_CLAMPTO, CONSTRAINT_TYPE_FOLLOWPATH, CONSTRAINT_TYPE_OBJECTSOLVER, CONSTRAINT_TYPE_ROTLIKE, data, bConstraint::data, bConstraint::enforce, ListBase::first, bConstraint::flag, bRotateLikeConstraint::flag, if(), TransInfo::mode, bConstraint::next, ROTLIKE_OFFSET, TFM_ROTATION, and bConstraint::type.
Referenced by add_pose_transdata(), and ObjectToTransData().
static int count_fcurve_keys (FCurve * fcu, char side, float cfra) [static]
Definition at line 2980 of file transform_conversions.c.
References FCurve::bezt, ELEM, BezTriple::f2, FrameOnMouseSide(), i, NULL, SELECT, and BezTriple::vec.
Referenced by createTransActionData().
static int count_gplayer_frames (bGPDlayer * gpl, char side, float cfra) [static]
Definition at line 3003 of file transform_conversions.c.
References ListBase::first, bGPDframe::flag, bGPDframe::framenum, FrameOnMouseSide(), bGPDlayer::frames, GP_FRAME_SELECT, bGPDframe::next, and NULL.
Referenced by createTransActionData().
static int count_proportional_objects (TransInfo * t) [static]
Definition at line 4549 of file transform_conversions.c.
References TransInfo::around, BA_HAS_RECALC_DATA, BA_HAS_RECALC_OB, BA_TRANSFORM_CHILD, BA_TRANSFORM_PARENT, Scene::base, BASE_EDITABLE_BGMODE, DAG_scene_flush_update(), ListBase::first, Base::flag, Object::flag, G, mark_children(), TransInfo::mode, Base::next, OB_RECALC_DATA, OB_RECALC_OB, Base::object, Object::parent, Object::recalc, TransInfo::scene, SELECT, TESTBASELIB_BGMODE, TFM_ROTATION, TFM_TRACKBALL, V3D_LOCAL, and TransInfo::view.
Referenced by createTransObject().
int count_set_pose_transflags (int * out_mode, short around, Object * ob)
Definition at line 734 of file transform_conversions.c.
References bPoseChannel::bone, bone_children_clear_transflag(), BONE_CONNECTED, BONE_HINGE_CHILD_TRANSFORM, BONE_SELECTED, BONE_TRANSFORM, BONE_TRANSFORM_CHILD, bPose::chanbase, Bone::childbase, Object::data, ListBase::first, Bone::flag, has_targetless_ik(), bPoseChannel::next, NULL, OB_LOCK_LOC, bPoseChannel::parent, PBONE_VISIBLE, Object::pose, bPoseChannel::protectflag, TFM_BONESIZE, TFM_ROTATION, and TFM_TRANSLATION.
Referenced by calc_manipulator_stats(), createTransPose(), and special_aftertrans_update().
static void createTransActionData (bContext * C, TransInfo * t) [static]
Definition at line 3135 of file transform_conversions.c.
References ActionFCurveToTransData(), ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_nla_mapping_get(), ANIMCONT_GPENCIL, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMTYPE_FCURVE, ANIMTYPE_GPLAYER, bAnimContext::ar, BKE_nla_tweakedit_remap(), BLI_freelistN(), CFRA, count_fcurve_keys(), count_gplayer_frames(), TransInfo::customData, TransInfo::data, bAnimListElem::data, bAnimContext::data, TransInfo::data2d, bAnimContext::datatype, filter(), ListBase::first, TransInfo::frame_side, GPLayerToTransData(), i, if(), TransInfo::imval, bAnimListElem::key_data, max, MEM_callocN(), min, TransInfo::mode, bAnimListElem::next, NLATIME_CONVERT_UNMAP, NULL, PEFRA, PSFRA, TransInfo::scene, TFM_TIME_EXTEND, TFM_TIME_SLIDE, TransInfo::total, bAnimListElem::type, UI_view2d_region_to_view(), ARegion::v2d, and TransData::val.
Referenced by createTransData().
static void createTransArmatureVerts (TransInfo * t) [static]
Definition at line 1103 of file transform_conversions.c.
References ARM_ENVELOPE, TransInfo::around, TransData::axismtx, BONE_EDITMODE_LOCKED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, TransData::center, copy_m3_m3(), copy_m3_m4(), copy_v3_v3(), TransInfo::data, Object::data, EditBone::dist, bArmature::drawtype, EBONE_VISIBLE, bArmature::edbo, TransData::ext, TransData::extra, ListBase::first, TransData::flag, EditBone::flag, EditBone::head, TransData::iloc, invert_m3_m3(), TransData::ival, EditBone::length, TransData::loc, MEM_callocN(), TransInfo::mode, TransData::mtx, mul_m3_m3m3(), EditBone::next, normalize_m3(), NULL, TransData::ob, OB_LOCK_LOC, OB_LOCK_ROT, OB_LOCK_SCALE, TransInfo::obedit, Object::obmat, EditBone::oldlength, TransData::protectflag, EditBone::rad_head, EditBone::rad_tail, EditBone::roll, TransData::smtx, sub_v3_v3v3(), EditBone::tail, TD_SELECTED, TFM_BONE_ENVELOPE, TFM_BONE_ROLL, TFM_BONESIZE, TFM_RESIZE, TransInfo::total, V3D_LOCAL, TransData::val, vec_roll_to_mat3(), and EditBone::xwidth.
Referenced by createTransData().
static void createTransCurveVerts (bContext * C, TransInfo * t) [static]
Definition at line 1427 of file transform_conversions.c.
References BPoint::alfa, BezTriple::alfa, Nurb::bezt, Nurb::bp, calc_distanceCurveVerts(), TransData::center, copy_m3_m3(), copy_m3_m4(), copy_v3_v3(), CTX_data_edit_object(), CU_BEZIER, CU_HIDE_HANDLES, curve_editnurbs(), TransInfo::data, Object::data, Curve::drawflag, Curve::editnurb, ELEM, TransData::ext, BPoint::f1, BezTriple::f1, BezTriple::f2, BezTriple::f3, ListBase::first, TransData::flag, TransInfo::flag, BPoint::hide, BezTriple::hide, TransData::iloc, initTransDataCurveHandles(), invert_m3_m3(), TransData::ival, TransData::loc, MEM_callocN(), TransInfo::mode, TransData::mtx, Nurb::next, NULL, TransInfo::obedit, Object::obmat, Nurb::pntsu, Nurb::pntsv, BPoint::radius, BezTriple::radius, SELECT, TransData::smtx, T_PROP_EDIT, TD_SELECTED, testhandlesNurb(), TFM_CURVE_SHRINKFATTEN, TFM_RESIZE, TFM_TILT, TransInfo::total, Nurb::type, TransData::val, BPoint::vec, and BezTriple::vec.
Referenced by createTransData().
void createTransData (bContext * C, TransInfo * t)
Definition at line 5875 of file transform_conversions.c.
References TransInfo::ar, BASE_VISIBLE, View3D::camera, createTransActionData(), createTransArmatureVerts(), createTransCurveVerts(), createTransEdge(), createTransEditVerts(), createTransGraphEditData(), createTransLatticeVerts(), createTransMBallVerts(), createTransNlaData(), createTransNodeData(), createTransObject(), createTransParticleVerts(), createTransPose(), createTransSeqData(), createTransTexspace(), createTransTrackingData(), createTransUVs(), CTX_BMESH, CTX_EDGE, CTX_TEXTURE, CTX_wm_region_view3d(), TransInfo::data, ELEM, TransInfo::ext, NumInput::flag, TransInfo::flag, Object::mode, TransInfo::mode, modifiers_isDeformedByArmature(), NULL, TransInfo::num, NUM_NO_FRACTION, OB_ARMATURE, OB_CURVE, OB_LATTICE, OB_MBALL, OB_MESH, OB_MODE_PARTICLE_EDIT, OB_MODE_POSE, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_WEIGHT_PAINT, OB_SURF, OBACT, TransInfo::obedit, object_in_scene(), TransInfo::options, PE_get_current(), PE_start_edit(), RegionView3D::persp, TransInfo::poseobj, ARegion::regiontype, RGN_TYPE_WINDOW, RV3D_CAMOB, TransInfo::scene, set_prop_dist(), sort_trans_data(), sort_trans_data_dist(), SPACE_ACTION, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, TransInfo::spacetype, T_2D_EDIT, T_CAMERA, T_EDIT, T_OBJECT, T_POINTS, T_POSE, T_PROP_EDIT, T_TEXTURE, TFM_BONESIZE, Object::type, and TransInfo::view.
Referenced by calculateTransformCenter(), and initTransform().
static void createTransEdge (TransInfo * t) [static]
Definition at line 302 of file transform_conversions.c.
References add_v3_v3v3(), BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ITER_MESH, BMEdit_FromObject(), CD_BWEIGHT, CD_CREASE, TransData::center, BMVert::co, copy_m3_m3(), copy_m3_m4(), CustomData_bmesh_get(), BMHeader::data, TransInfo::data, BMesh::edata, TransData::ext, TransData::flag, TransInfo::flag, BMEdge::head, invert_m3_m3(), TransData::ival, TransData::loc, MEM_callocN(), TransInfo::mode, TransData::mtx, mul_v3_fl(), NULL, TransInfo::obedit, Object::obmat, TransData::smtx, T_PROP_EDIT, TD_SELECTED, TFM_BWEIGHT, TransInfo::total, BMEdge::v1, BMEdge::v2, and TransData::val.
Referenced by createTransData().
static void createTransEditVerts (bContext * C, TransInfo * t) [static]
Definition at line 2020 of file transform_conversions.c.
References ABS, BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_ELEM_SELECT, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_MESH, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, BM_VERT, BM_VERTS_OF_MESH, BMEdit_FromObject(), CD_BWEIGHT, BMVert::co, copy_m3_m3(), copy_m3_m4(), crazyspace_get_mapped_editverts(), crazyspace_set_quats_editmesh(), CTX_data_tool_settings(), CustomData_bmesh_get(), BMHeader::data, TransInfo::data, TransData::dist, EDBM_verts_mirror_cache_begin(), EDBM_verts_mirror_cache_end(), EDBM_verts_mirror_get(), editbmesh_get_first_deform_matrices(), editmesh_set_connectivity_distance(), BMEditSelection::ele, TransData::extra, TransData::flag, TransInfo::flag, BMVert::head, BMEditSelection::htype, TransData::iloc, invert_m3_m3(), ListBase::last, TransData::loc, TransformOrientation::mat, MAXFLOAT, MEM_callocN(), MEM_freeN(), MEM_mallocN(), TransInfo::mirror, TransInfo::mode, modifiers_getCageIndex(), modifiers_isCorrectableDeformed(), TransData::mtx, mul_m3_m3m3(), mul_serie_m3(), NULL, TransInfo::obedit, Object::obmat, quat_to_mat3(), SCE_SELECT_EDGE, SCE_SELECT_VERTEX, TransInfo::scene, BMesh::selected, ToolSettings::selectmode, TransData::smtx, T_MIRROR, T_PROP_CONNECTED, T_PROP_EDIT, TD_ACTIVE, TD_MIRROR_EDGE, TD_NOTCONNECTED, TD_SELECTED, TFM_EDGE_SLIDE, TransInfo::total, BMesh::totvert, TRUE, BMLoop::v, BMEdge::v1, BMEdge::v2, BMesh::vdata, and VertsToTransData().
Referenced by createTransData().
static void createTransGraphEditData (bContext * C, TransInfo * t) [static]
Definition at line 3357 of file transform_conversions.c.
References TransInfo::ar, ListBase::first, NULL, TransInfo::sa, TransInfo::scene, and ScrArea::spacedata.
Referenced by createTransData().
static void createTransLatticeVerts (TransInfo * t) [static]
Definition at line 1642 of file transform_conversions.c.
References TransData::center, copy_m3_m3(), copy_m3_m4(), copy_v3_v3(), TransInfo::data, Object::data, Lattice::def, Lattice::editlatt, TransData::ext, BPoint::f1, TransData::flag, TransInfo::flag, BPoint::hide, TransData::iloc, invert_m3_m3(), EditLatt::latt, TransData::loc, MEM_callocN(), TransData::mtx, NULL, TransInfo::obedit, Object::obmat, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, SELECT, TransData::smtx, T_PROP_EDIT, TD_SELECTED, TransInfo::total, TransData::val, and BPoint::vec.
Referenced by createTransData().
static void createTransMBallVerts (TransInfo * t) [static]
Definition at line 1297 of file transform_conversions.c.
References copy_m3_m3(), copy_m3_m4(), copy_qt_qt(), copy_v3_v3(), TransInfo::data, Object::data, MetaBall::editelems, TransInfo::ext, ListBase::first, TransInfo::flag, invert_m3_m3(), MB_SCALE_RAD, MEM_callocN(), NULL, TransInfo::obedit, Object::obmat, SELECT, T_PROP_EDIT, TD_SELECTED, TD_SINGLESIZE, TD_USEQUAT, and TransInfo::total.
Referenced by createTransData().
static void createTransNlaData (bContext * C, TransInfo * t) [static]
Definition at line 2594 of file transform_conversions.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_NLATRACK, bAnimContext::ar, TransData::axismtx, BKE_nlastrips_make_metas(), BLI_findindex(), BLI_freelistN(), TransData::center, CFRA, copy_v3_v3(), TransInfo::customData, TransInfo::data, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, TransData::dist, ELEM, TransData::ext, TransData::extra, filter(), ListBase::first, TransData::flag, TransInfo::flag, TransInfo::frame_side, FrameOnMouseSide(), TransDataNla::h1, TransDataNla::h2, TransDataNla::handle, bAnimListElem::id, TransDataNla::id, TransData::iloc, TransInfo::imval, TransData::ival, TransData::loc, MEM_callocN(), TransInfo::mode, TransData::mtx, bAnimListElem::next, AnimData::nla_tracks, NLACHANNEL_STEP, NLASTRIP_FLAG_SELECT, NLASTRIP_TYPE_TRANSITION, TransDataNla::nlt, NULL, TransDataNla::oldTrack, TransInfo::scene, bAnimContext::sl, TransData::smtx, TransDataNla::strip, NlaTrack::strips, T_FREE_CUSTOMDATA, TD_SELECTED, TFM_TIME_EXTEND, TFM_TRANSLATION, TransInfo::total, TransDataNla::trackIndex, bAnimListElem::type, UI_view2d_region_to_view(), unit_m3(), ARegion::v2d, and TransData::val.
Referenced by createTransData().
static void createTransNodeData (bContext * C, TransInfo * t) [static]
Definition at line 5392 of file transform_conversions.c.
References CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_DATA_END, TransInfo::data, TransInfo::data2d, SpaceNode::edittree, ListBase::first, bNode::flag, MEM_callocN(), bNode::next, NODE_SELECT, NODE_TRANSFORM, bNodeTree::nodes, NodeToTransData(), bNode::parent, TransInfo::sa, ScrArea::spacedata, and TransInfo::total.
Referenced by createTransData().
static void createTransObject (bContext * C, TransInfo * t) [static]
Definition at line 5284 of file transform_conversions.c.
References BA_TRANSFORM_CHILD, BA_TRANSFORM_PARENT, Scene::base, BASE_EDITABLE_BGMODE, clear_trans_object_base_flags(), count_proportional_objects(), CTX_DATA_BEGIN, CTX_DATA_COUNT, CTX_DATA_END, TransInfo::data, TransData::ext, TransInfo::ext, ListBase::first, Object::flag, TransData::flag, TransInfo::flag, Object::id, ID::lib, MEM_callocN(), Base::next, NULL, Base::object, ObjectToTransData(), Object::protectflag, TransData::protectflag, Object::rotmode, TransDataExtension::rotOrder, TransInfo::scene, SELECT, set_trans_object_base_flags(), T_PROP_EDIT, TD_NO_LOC, TD_NOCENTER, TD_SELECTED, TD_SKIP, TransInfo::total, TransData::val, and TransInfo::view.
Referenced by createTransData().
static void createTransParticleVerts (bContext * C, TransInfo * t) [static]
Definition at line 1698 of file transform_conversions.c.
References BA_HAS_RECALC_DATA, calc_distanceCurveVerts(), TransData::center, PTCacheEditKey::co, copy_v3_v3(), CTX_data_active_base(), CTX_data_active_object(), TransInfo::data, ParticleSystemModifierData::dm, TransData::ext, TransInfo::ext, ParticleEditSettings::flag, TransData::flag, ParticleSystem::flag, PTCacheEditKey::flag, PTCacheEditPoint::flag, Base::flag, TransInfo::flag, ParticleSettings::from, i, TransData::iloc, Object::imat, invert_m4_m4(), TransData::ival, PTCacheEditPoint::keys, TransData::loc, TransformOrientation::mat, MEM_callocN(), TransInfo::mode, TransData::mtx, mul_m4_v3(), NULL, TransData::ob, OB_LOCK_LOC, Object::obmat, ParticleSystem::part, ToolSettings::particle, ParticleSystem::particles, PE_get_current(), PE_LOCK_FIRST, PE_settings(), PEK_HIDE, PEK_SELECT, PEK_USE_WCO, PEP_HIDE, PEP_TRANSFORM, PTCacheEdit::points, TransData::protectflag, PTCacheEdit::psys, psys_get_modifier(), PSYS_GLOBAL_HAIR, psys_mat_hair_to_global(), TransDataExtension::quat, SCE_SELECT_PATH, TransInfo::scene, ParticleEditSettings::selectmode, TransInfo::settings, TransDataExtension::size, TransData::smtx, T_PROP_EDIT, TD_NO_EXT, TD_SELECTED, TD_SKIP, TFM_BAKE_TIME, PTCacheEditKey::time, TransInfo::total, PTCacheEditPoint::totkey, unit_m3(), unit_m4(), TransData::val, and PTCacheEditKey::world_co.
Referenced by createTransData().
static void createTransPose (TransInfo * t, Object * ob) [static]
Definition at line 1038 of file transform_conversions.c.
References add_pose_transdata(), ARM_AUTO_IK, ARM_RESTPOS, TransInfo::around, bPoseChannel::bone, BONE_TRANSFORM, bPose::chanbase, count_set_pose_transflags(), TransInfo::data, ELEM, TransInfo::ext, ListBase::first, Bone::flag, TransInfo::flag, bArmature::flag, get_armature(), i, MEM_callocN(), TransInfo::mode, bPoseChannel::next, NULL, Object::pose, pose_grab_with_ik(), TransInfo::poseobj, T_AUTOIK, T_POSE, TFM_BONESIZE, TFM_DUMMY, TFM_TRANSLATION, TransInfo::total, and transform_autoik_update().
Referenced by createTransData().
static void createTransSeqData (bContext * C, TransInfo * t) [static]
Definition at line 4227 of file transform_conversions.c.
References CFRA, TransInfo::customData, TransInfo::customFree, TransInfo::data, TransInfo::data2d, FALSE, ListBase::first, TransInfo::flag, Sequence::flag, TransInfo::frame_side, freeSeqData(), i, TransInfo::imval, MEM_callocN(), TransInfo::mode, Sequence::next, NULL, TransInfo::scene, SELECT, Sequence::seq1, SEQ_EFFECT, seq_give_editing(), SEQ_LEFTSEL, SEQ_LOCK, SEQ_RIGHTSEL, Editing::seqbasep, SeqToTransData_Recursive(), SeqTransCount(), T_FREE_CUSTOMDATA, TFM_TIME_EXTEND, TransInfo::total, Sequence::type, UI_view2d_fromcontext(), and UI_view2d_region_to_view().
Referenced by createTransData().
static void createTransTexspace (TransInfo * t) [static]
Definition at line 256 of file transform_conversions.c.
References TransData::axismtx, TransData::center, copy_m3_m4(), copy_v3_v3(), TransInfo::data, Object::data, Object::dtx, ELEM3, TransInfo::ext, TransData::ext, TransData::flag, give_obdata_texspace(), GS, ID_CU, ID_MB, ID_ME, TransData::iloc, invert_m3_m3(), TransDataExtension::irot, TransDataExtension::isize, TransData::loc, ME_AUTOSPACE, MEM_callocN(), TransData::mtx, ID::name, normalize_m3(), NULL, TransData::ob, OB_TEXSPACE, OBACT, Object::obmat, TransDataExtension::rot, TransInfo::scene, TransDataExtension::size, TransData::smtx, TD_SELECTED, and TransInfo::total.
Referenced by createTransData().
static void createTransTrackingCurvesData (bContext * C, TransInfo * t) [static]
Definition at line 5668 of file transform_conversions.c.
References BKE_movieclip_get_size(), BKE_tracking_get_tracks(), CTX_wm_space_clip(), TransInfo::customData, TransInfo::customFree, TransInfo::data, TransInfo::data2d, ED_space_clip(), ListBase::first, MovieTrackingMarker::flag, MovieTrackingTrack::flag, i, MARKER_DISABLED, MARKER_GRAPH_SEL_X, MARKER_GRAPH_SEL_Y, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, markerToTransCurveDataInit(), MEM_callocN(), MovieTrackingTrack::next, TransInfo::total, TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, transDataTrackingFree(), and SpaceClip::user.
Referenced by createTransTrackingData().
static void createTransTrackingData (bContext * C, TransInfo * t) [static]
Definition at line 5747 of file transform_conversions.c.
References BKE_movieclip_has_frame(), createTransTrackingCurvesData(), createTransTrackingTracksData(), CTX_wm_region(), CTX_wm_space_clip(), ED_space_clip(), ELEM, TransInfo::mode, ARegion::regiontype, RGN_TYPE_PREVIEW, TFM_RESIZE, TFM_TRANSLATION, TransInfo::total, and SpaceClip::user.
Referenced by createTransData().
static void createTransTrackingTracksData (bContext * C, TransInfo * t) [static]
Definition at line 5541 of file transform_conversions.c.
References BKE_tracking_get_marker(), BKE_tracking_get_tracks(), CTX_wm_space_clip(), TransInfo::customData, TransInfo::customFree, TransInfo::data, TransInfo::data2d, ED_space_clip(), ListBase::first, MovieTrackingMarker::flag, MovieTrackingTrack::flag, MovieClipUser::framenr, MARKER_DISABLED, MEM_callocN(), MovieTrackingTrack::next, MovieTrackingTrack::pat_flag, MovieTrackingTrack::search_flag, SELECT, TransInfo::total, TRACK_LOCKED, TRACK_VIEW_SELECTED, MovieClip::tracking, trackToTransData(), transDataTrackingFree(), and SpaceClip::user.
Referenced by createTransTrackingData().
static void createTransUVs (bContext * C, TransInfo * t) [static]
Definition at line 2436 of file transform_conversions.c.
References BMEditMesh::bm, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_TAG, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CTX_data_edit_image(), CTX_wm_space_image(), CustomData_bmesh_get(), TransInfo::data, BMHeader::data, TransInfo::data2d, ED_space_image_show_uvedit(), ED_uvedit_live_unwrap_begin(), SpaceImage::flag, TransInfo::flag, BMLoop::head, BMFace::head, BMesh::ldata, MEM_callocN(), NULL, TransInfo::obedit, BMesh::pdata, TransInfo::scene, SI_CLIP_UV, SI_LIVE_UNWRAP, T_CLIP_UV, T_PROP_EDIT, TransInfo::total, MLoopUV::uv, uvedit_face_visible_test(), uvedit_uv_select_test(), and UVsToTransData().
Referenced by createTransData().
static void editmesh_set_connectivity_distance (BMEditMesh * em, float mtx[][3], float * dists) [static]
Definition at line 1873 of file transform_conversions.c.
References BLI_array_append, BLI_array_count, BLI_array_declare, BLI_array_free, BLI_smallhash_haskey(), BLI_smallhash_init(), BLI_smallhash_insert(), BLI_smallhash_release(), BMEditMesh::bm, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_ELEM_SELECT, BM_ITER_ELEM, BM_ITER_MESH, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, BMVert::co, fill_vn_fl(), FLT_MAX, i, len_v3(), MEM_callocN(), MEM_freeN(), MIN2, mul_m3_v3(), NULL, sub_v3_v3v3(), and BMesh::totvert.
Referenced by createTransEditVerts().
void flushTransGPactionData (TransInfo * t)
Definition at line 3084 of file transform_conversions.c.
References TransInfo::customData, i, TransInfo::mode, tGPFtransdata::sdata, TFM_TIME_SLIDE, TransInfo::total, and tGPFtransdata::val.
void flushTransGraphData (TransInfo * t)
Definition at line 3790 of file transform_conversions.c.
References SpaceIpo::autosnap, BKE_nla_tweakedit_remap(), TransInfo::data, TransInfo::data2d, ED_markers_find_nearest_marker_time(), ListBase::first, SpaceIpo::flag, floorf, FPS, if(), Scene::markers, NLATIME_CONVERT_UNMAP, TransInfo::sa, SACTSNAP_FRAME, SACTSNAP_MARKER, TransInfo::scene, SIPO_DRAWTIME, ScrArea::spacedata, TD_INTVALUES, TD_MOVEHANDLE1, TD_MOVEHANDLE2, and TD_NOTIMESNAP.
void flushTransNodes (TransInfo * t)
Definition at line 2269 of file transform_conversions.c.
References TransInfo::data2d, ED_node_link_intersect_test(), TransData2D::loc, TransData2D::loc2d, TransInfo::sa, and TransInfo::total.
Referenced by recalcData().
void flushTransParticles (TransInfo * t)
Definition at line 1819 of file transform_conversions.c.
References PTCacheEditKey::co, co, compare_v3v3(), copy_v3_v3(), TransInfo::data, ParticleSystemModifierData::dm, ParticleSystem::flag, PTCacheEditPoint::flag, TransInfo::flag, ParticleSettings::from, i, invert_m4_m4(), PTCacheEditPoint::keys, TransformOrientation::mat, mul_m4_v3(), NULL, OBACT, ParticleSystem::part, ParticleSystem::particles, PE_get_current(), PE_update_object(), PEP_EDIT_RECALC, PEP_TRANSFORM, PTCacheEdit::points, PTCacheEdit::psys, psys_get_modifier(), PSYS_GLOBAL_HAIR, psys_mat_hair_to_global(), TransInfo::scene, T_PROP_EDIT, and PTCacheEditKey::world_co.
Referenced by recalcData_view3d().
void flushTransSeq (TransInfo * t)
Definition at line 2294 of file transform_conversions.c.
References calc_sequence(), calc_sequence_disp(), CLAMP(), TransInfo::data, TransInfo::data2d, Sequence::depth, ELEM, TransData::extra, FALSE, ListBase::first, Sequence::flag, TransDataSeq::flag, if(), TransData2D::loc, Sequence::machine, MAXSEQ, TransInfo::mode, Sequence::next, NULL, TransInfo::scene, TransDataSeq::sel_flag, SELECT, TransDataSeq::seq, Sequence::seq1, Sequence::seq2, Sequence::seq3, seq_give_editing(), SEQ_LEFTSEL, SEQ_META, seq_offset_animdata(), SEQ_OVERLAP, SEQ_RIGHTSEL, seq_single_fix(), seq_test_overlap(), seq_tx_handle_xlimits(), seq_tx_set_final_left(), seq_tx_set_final_right(), seq_tx_test(), Editing::seqbasep, Sequence::start, TransDataSeq::start_offset, TFM_SEQ_SLIDE, TFM_TIME_TRANSLATE, and Sequence::type.
Referenced by recalcData().
void flushTransTracking (TransInfo * t)
Definition at line 5826 of file transform_conversions.c.
References add_v2_v2v2(), TransDataTracking::area, cancelTransTracking(), TransDataTracking::coord, copy_v2_v2(), TransInfo::customData, TransInfo::data, TransInfo::data2d, TransInfo::flag, TransData2D::loc, TransData2D::loc2d, TransDataTracking::markers, TransDataTracking::markersnr, MEM_callocN(), TransDataTracking::mode, negate_v2_v2(), MovieTrackingMarker::pos, TransDataTracking::prev_pos, TransDataTracking::relative, TransDataTracking::scale, TransDataTracking::smarkers, TransDataTracking::soffset, TransDataTracking::srelative, TransInfo::state, sub_v2_v2(), sub_v2_v2v2(), T_ALT_TRANSFORM, TRACK_AREA_POINT, TRANS_CANCEL, transDataTracking_ModeCurves, and transDataTracking_ModeTracks.
Referenced by recalcData_clip().
void flushTransUVs (TransInfo * t)
Definition at line 2505 of file transform_conversions.c.
References TransInfo::data2d, ED_space_image_size(), ED_space_image_uv_aspect(), ListBase::first, SpaceImage::flag, TransData2D::loc, TransData2D::loc2d, TransInfo::sa, SI_PIXELSNAP, ScrArea::spacedata, TransInfo::state, and TRANS_CANCEL.
Referenced by recalcData_image().
static short FrameOnMouseSide (char side, float frame, float cframe) [static]
Definition at line 2580 of file transform_conversions.c.
Referenced by ActionFCurveToTransData(), count_fcurve_keys(), count_gplayer_frames(), createTransNlaData(), and GPLayerToTransData().
static void freeSeqData (TransInfo * t) [static]
Definition at line 4095 of file transform_conversions.c.
References calc_sequence(), calc_sequence_disp(), TransInfo::customData, TransInfo::data, Sequence::depth, TransData::extra, FALSE, ListBase::first, TransInfo::flag, Sequence::flag, MEM_freeN(), Sequence::next, NULL, TransInfo::scene, SELECT, Sequence::seq1, Sequence::seq2, Sequence::seq3, SEQ_EFFECT, seq_give_editing(), SEQ_OVERLAP, seq_test_overlap(), Editing::seqbasep, shuffle_seq(), shuffle_seq_time(), sort_seq(), TransInfo::state, T_FREE_CUSTOMDATA, Sequence::tmp, TransInfo::total, TRANS_CANCEL, TRUE, and Sequence::type.
Referenced by createTransSeqData().
static void get_edge_center (float cent_r[3], BMVert * eve) [static]
Definition at line 1970 of file transform_conversions.c.
References BM_EDGES_OF_VERT, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_ELEM, BMVert::co, mid_v3_v3v3(), BMEdge::v1, and BMEdge::v2.
Referenced by VertsToTransData().
static void get_face_center (float cent_r[3], BMVert * eve) [static]
Definition at line 1956 of file transform_conversions.c.
References BM_elem_flag_test, BM_ELEM_SELECT, BM_face_calc_center_mean(), BM_FACES_OF_VERT, and BM_ITER_ELEM.
Referenced by VertsToTransData().
static int GPLayerToTransData (TransData * td, tGPFtransdata * tfd, bGPDlayer * gpl, char side, float cfra) [static]
Definition at line 3108 of file transform_conversions.c.
References ListBase::first, bGPDframe::flag, bGPDframe::framenum, FrameOnMouseSide(), bGPDlayer::frames, GP_FRAME_SELECT, TransData::ival, bGPDframe::next, tGPFtransdata::sdata, tGPFtransdata::val, and TransData::val.
Referenced by createTransActionData().
static bKinematicConstraint* has_targetless_ik (bPoseChannel * pchan) [static]
Definition at line 370 of file transform_conversions.c.
References CONSTRAINT_TYPE_KINEMATIC, bPoseChannel::constraints, bConstraint::data, data, bConstraint::enforce, ListBase::first, bConstraint::next, NULL, OB_ARMATURE, bKinematicConstraint::subtarget, bKinematicConstraint::tar, Object::type, and bConstraint::type.
Referenced by add_pose_transdata(), apply_targetless_ik(), count_set_pose_transflags(), and special_aftertrans_update().
static TransDataCurveHandleFlags* initTransDataCurveHandles (TransData * td, struct BezTriple * bezt) [static]
Definition at line 1415 of file transform_conversions.c.
References TransData::flag, BezTriple::h1, TransDataCurveHandleFlags::h1, BezTriple::h2, TransDataCurveHandleFlags::h2, TransData::hdata, TransDataCurveHandleFlags::ih1, TransDataCurveHandleFlags::ih2, MEM_mallocN(), and TD_BEZTRIPLE.
Referenced by createTransCurveVerts().
static int mark_children (Object * ob) [static]
Definition at line 4532 of file transform_conversions.c.
References BA_TRANSFORM_CHILD, Object::flag, Object::parent, and SELECT.
Referenced by count_proportional_objects().
static void markerToTransCurveDataInit (TransData * td, TransData2D * td2d, TransDataTracking * tdt, MovieTrackingMarker * marker, MovieTrackingMarker * prev_marker, short coord, float size) [static]
Definition at line 5629 of file transform_conversions.c.
References TransData::axismtx, TransData::center, TransDataTracking::coord, copy_v3_v3(), TransData::dist, TransData::ext, TransData::flag, MovieTrackingMarker::flag, TransDataTracking::flag, MovieTrackingMarker::framenr, TransData::iloc, TransData::loc, TransData2D::loc, TransData2D::loc2d, MARKER_TRACKED, TransDataTracking::mode, TransData::mtx, NULL, MovieTrackingMarker::pos, TransDataTracking::prev_pos, TransDataTracking::scale, TransData::smtx, TD_SELECTED, transDataTracking_ModeCurves, unit_m3(), and TransData::val.
Referenced by createTransTrackingCurvesData().
static void markerToTransDataInit (TransData * td, TransData2D * td2d, TransDataTracking * tdt, MovieTrackingTrack * track, int area, float * loc, float * rel, float * off) [static]
Definition at line 5447 of file transform_conversions.c.
References TransDataTracking::area, TransData::axismtx, TransData::center, copy_v2_v2(), copy_v3_v3(), TransData::dist, TransData::ext, TransData::flag, TransData::iloc, TransData::loc, TransDataTracking::loc, TransData2D::loc, TransData2D::loc2d, MovieTrackingTrack::markers, TransDataTracking::markers, MovieTrackingTrack::markersnr, TransDataTracking::markersnr, TransDataTracking::mode, TransData::mtx, NULL, TransDataTracking::relative, TransData::smtx, TransDataTracking::soffset, TransDataTracking::srelative, TD_SELECTED, TRACK_AREA_POINT, transDataTracking_ModeTracks, unit_m3(), and TransData::val.
Referenced by trackToTransData().
static void NodeToTransData (TransData * td, TransData2D * td2d, bNode * node) [static]
Definition at line 5362 of file transform_conversions.c.
References TransData::axismtx, TransData::center, copy_v3_v3(), TransData::dist, TransData::ext, bNode::flag, TransData::flag, TransData::iloc, TransData::loc, TransData2D::loc, TransData2D::loc2d, bNode::locx, bNode::locy, TransData::mtx, NODE_TRANSFORM, NULL, bNode::parent, TransData::smtx, TD_SELECTED, TD_SKIP, unit_m3(), and TransData::val.
Referenced by createTransNodeData().
static void ObjectToTransData (TransInfo * t, TransData * td, Object * ob) [static]
Definition at line 4349 of file transform_conversions.c.
References TransData::axismtx, TransData::center, TransData::con, Object::constraints, constraints_list_needinv(), copy_m3_m4(), copy_m4_m4(), copy_qt_qt(), copy_v3_v3(), Object::dquat, TransDataExtension::dquat, Object::drot, TransDataExtension::drot, Object::dscale, TransDataExtension::dscale, TransData::ext, ListBase::first, TransData::flag, TransData::iloc, invert_m3_m3(), TransDataExtension::iquat, TransDataExtension::irot, TransDataExtension::irotAngle, TransDataExtension::irotAxis, TransDataExtension::isize, Object::loc, TransData::loc, TransInfo::mode, TransData::mtx, mul_m3_m3m3(), normalize_m3(), NULL, TransData::ob, OB_NO_CONSTRAINTS, OBACT, object_to_mat3(), TransDataExtension::obmat, Object::obmat, Object::parent, Object::quat, TransDataExtension::quat, Object::rot, TransDataExtension::rot, ROT_MODE_AXISANGLE, Object::rotAngle, TransDataExtension::rotAngle, Object::rotAxis, TransDataExtension::rotAxis, Object::rotmode, TransDataExtension::rotOrder, TransInfo::scene, Object::size, TransDataExtension::size, TransData::smtx, TD_ACTIVE, TFM_DUMMY, Object::transflag, unit_m3(), and where_is_object().
Referenced by createTransObject().
static void pchan_autoik_adjust (bPoseChannel * pchan, short chainlen) [static]
Definition at line 803 of file transform_conversions.c.
References bPoseChannel::constflag, CONSTRAINT_IK_TEMP, CONSTRAINT_TYPE_KINEMATIC, bPoseChannel::constraints, data, bConstraint::data, bConstraint::enforce, ListBase::first, bKinematicConstraint::flag, bKinematicConstraint::max_rootbone, bConstraint::next, PCHAN_HAS_IK, PCHAN_HAS_TARGET, bKinematicConstraint::rootbone, and bConstraint::type.
Referenced by transform_autoik_update().
static short pose_grab_with_ik (Object * ob) [static]
Definition at line 990 of file transform_conversions.c.
References bPoseChannel::bone, BONE_CONNECTED, BONE_SELECTED, bPose::chanbase, Bone::childbase, Object::data, ListBase::first, Bone::flag, Bone::layer, bArmature::layer, Object::mode, bPoseChannel::next, Bone::next, NULL, OB_MODE_POSE, bPoseChannel::parent, Object::pose, pose_grab_with_ik_add(), and pose_grab_with_ik_children().
Referenced by createTransPose().
static short pose_grab_with_ik_add (bPoseChannel * pchan) [static]
Definition at line 887 of file transform_conversions.c.
References add_pose_constraint(), bPoseChannel::bone, BONE_CONNECTED, BONE_IK_NO_XDOF_TEMP, BONE_IK_NO_YDOF_TEMP, BONE_IK_NO_ZDOF_TEMP, bPoseChannel::constflag, CONSTRAINT_DISABLE, CONSTRAINT_IK_AUTO, CONSTRAINT_IK_TEMP, CONSTRAINT_IK_TIP, CONSTRAINT_TYPE_KINEMATIC, bPoseChannel::constraints, copy_v3_v3(), bConstraint::data, data, bConstraint::enforce, ListBase::first, Bone::flag, bConstraint::flag, bKinematicConstraint::flag, bKinematicConstraint::grabtarget, if(), bPoseChannel::ikflag, bKinematicConstraint::max_rootbone, bConstraint::next, NULL, OB_ARMATURE, OB_LOCK_ROTX, OB_LOCK_ROTY, OB_LOCK_ROTZ, bPoseChannel::parent, PCHAN_HAS_IK, PCHAN_HAS_TARGET, bPoseChannel::pose_tail, bPoseChannel::protectflag, bKinematicConstraint::rootbone, bKinematicConstraint::subtarget, bKinematicConstraint::tar, Object::type, and bConstraint::type.
Referenced by pose_grab_with_ik(), and pose_grab_with_ik_children().
static short pose_grab_with_ik_children (bPose * pose, Bone * bone) [static]
Definition at line 968 of file transform_conversions.c.
References BONE_CONNECTED, Bone::childbase, ListBase::first, Bone::flag, get_pose_channel(), Bone::name, Bone::next, and pose_grab_with_ik_add().
Referenced by pose_grab_with_ik().
static void pose_grab_with_ik_clear (Object * ob) [static]
Definition at line 855 of file transform_conversions.c.
References BLI_remlink(), BONE_IK_NO_XDOF_TEMP, BONE_IK_NO_YDOF_TEMP, BONE_IK_NO_ZDOF_TEMP, bPose::chanbase, bPoseChannel::constflag, CONSTRAINT_IK_TEMP, CONSTRAINT_TYPE_KINEMATIC, bPoseChannel::constraints, bConstraint::data, data, ListBase::first, bKinematicConstraint::flag, bPoseChannel::ikflag, MEM_freeN(), bConstraint::next, bPoseChannel::next, next, NULL, OB_ARMATURE, PCHAN_HAS_IK, PCHAN_HAS_TARGET, Object::pose, bKinematicConstraint::subtarget, bKinematicConstraint::tar, Object::type, and bConstraint::type.
Referenced by special_aftertrans_update().
static void posttrans_action_clean (bAnimContext * ac, bAction * act) [static]
Definition at line 2948 of file transform_conversions.c.
References ANIM_animdata_filter(), ANIM_nla_mapping_apply_fcurve(), ANIM_nla_mapping_get(), ANIMCONT_ACTION, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, BLI_freelistN(), FALSE, filter(), ListBase::first, bAnimListElem::key_data, bAnimListElem::next, NULL, and posttrans_fcurve_clean().
Referenced by special_aftertrans_update().
static void posttrans_fcurve_clean (FCurve * fcu, const short use_handle) [static]
Definition at line 2886 of file transform_conversions.c.
References BEZSELECTED, FCurve::bezt, delete_fcurve_key(), i, IS_EQF, len(), MEM_callocN(), MEM_freeN(), NULL, testhandles_fcurve(), FCurve::totvert, and BezTriple::vec.
Referenced by posttrans_action_clean(), and special_aftertrans_update().
static void posttrans_gpd_clean (bGPdata * gpd) [static]
Definition at line 2799 of file transform_conversions.c.
References BLI_addhead(), BLI_addtail(), BLI_insertlinkafter(), BLI_insertlinkbefore(), BLI_remlink(), ListBase::first, bGPDframe::flag, bGPDframe::framenum, bGPDlayer::frames, GP_FRAME_SELECT, gpencil_layer_delframe(), ListBase::last, bGPdata::layers, bGPDframe::next, bGPDlayer::next, NULL, and bGPDframe::prev.
Referenced by special_aftertrans_update().
static void qsort_trans_data (TransInfo * t, TransData * head, TransData * tail, TransData * temp) [static]
Definition at line 124 of file transform_conversions.c.
References TransData::dist, TransInfo::flag, TransData::rdist, and T_PROP_CONNECTED.
Referenced by sort_trans_data_dist().
void remake_graph_transdata (TransInfo * t, ListBase * anim_data)
Definition at line 3756 of file transform_conversions.c.
References FCurve::bezt, bezt_to_beztmaps(), beztmap_to_data(), ListBase::first, SpaceIpo::flag, if(), bAnimListElem::key_data, MEM_freeN(), bAnimListElem::next, TransInfo::sa, SIPO_NOHANDLES, sort_time_beztmaps(), sort_time_fcurve(), ScrArea::spacedata, testhandles_fcurve(), and FCurve::totvert.
static TransData* SeqToTransData (TransData * td, TransData2D * td2d, TransDataSeq * tdsq, Sequence * seq, int flag, int sel_flag) [static]
Definition at line 3992 of file transform_conversions.c.
References TransData::axismtx, TransData::center, copy_v3_v3(), TransData::dist, TransData::ext, TransData::extra, TransData::flag, TransDataSeq::flag, TransData::iloc, TransData::ival, TransData::loc, TransData2D::loc, TransData2D::loc2d, Sequence::machine, TransData::mtx, NULL, TransDataSeq::sel_flag, SELECT, TransDataSeq::seq, SEQ_LEFTSEL, SEQ_RIGHTSEL, seq_tx_get_final_left(), seq_tx_get_final_right(), TransData::smtx, Sequence::start, TransDataSeq::start_offset, TD_SELECTED, unit_m3(), and TransData::val.
Referenced by SeqToTransData_Recursive().
static int SeqToTransData_Recursive (TransInfo * t, ListBase * seqbase, TransData * td, TransData2D * td2d, TransDataSeq * tdsq) [static]
Definition at line 4052 of file transform_conversions.c.
References ListBase::first, Sequence::next, SELECT, SEQ_LEFTSEL, SEQ_RIGHTSEL, Sequence::seqbase, SeqToTransData(), and SeqTransInfo().
Referenced by createTransSeqData().
static int SeqTransCount (TransInfo * t, Sequence * parent, ListBase * seqbase, int depth) [static]
Definition at line 3968 of file transform_conversions.c.
References Sequence::depth, ListBase::first, Sequence::next, Sequence::seqbase, SeqTransInfo(), and Sequence::tmp.
Referenced by createTransSeqData().
static void SeqTransInfo (TransInfo * t, Sequence * seq, int * recursive, int * count, int * flag) [static]
Definition at line 3856 of file transform_conversions.c.
References CFRA, Sequence::depth, Sequence::flag, TransInfo::frame_side, left(), TransInfo::mode, TransInfo::scene, SELECT, SEQ_LEFTSEL, SEQ_LOCK, SEQ_META, SEQ_RIGHTSEL, seq_tx_get_final_left(), seq_tx_get_final_right(), TFM_TIME_EXTEND, and Sequence::type.
Referenced by SeqToTransData_Recursive(), and SeqTransCount().
static void set_prop_dist (TransInfo * t, short with_dist) [static]
Definition at line 215 of file transform_conversions.c.
References TransData::center, TransInfo::data, TransData::dist, TransData::flag, i, TransData::mtx, mul_m3_v3(), normalize_v3(), TransData::rdist, sub_v3_v3v3(), and TD_SELECTED.
Referenced by createTransData().
static void set_trans_object_base_flags (TransInfo * t) [static]
Definition at line 4459 of file transform_conversions.c.
References TransInfo::around, BA_HAS_RECALC_DATA, BA_HAS_RECALC_OB, BA_TRANSFORM_CHILD, BA_WAS_SEL, Scene::base, copy_baseflags(), DAG_scene_flush_update(), ListBase::first, Object::flag, Base::flag, G, TransInfo::mode, Base::next, OB_RECALC_DATA, OB_RECALC_OB, Base::object, object_handle_update(), object_in_scene(), Object::parent, Object::recalc, TransInfo::scene, SELECT, TESTBASELIB_BGMODE, TFM_DUMMY, TFM_ROTATION, TFM_TRACKBALL, V3D_LOCAL, and TransInfo::view.
Referenced by createTransObject().
static void sort_time_beztmaps (BeztMap * bezms, int totvert, const short UNUSEDuse_handle) [static]
Definition at line 3628 of file transform_conversions.c.
References BeztMap::bezt, i, BeztMap::newIndex, SWAP, BeztMap::swapHs, and BezTriple::vec.
Referenced by remake_graph_transdata().
static void sort_trans_data (TransInfo * t) [static]
Definition at line 185 of file transform_conversions.c.
References TransInfo::data, TransData::flag, TD_SELECTED, and TransInfo::total.
Referenced by createTransData().
void sort_trans_data_dist (TransInfo * t)
Definition at line 172 of file transform_conversions.c.
References TransInfo::data, TransData::flag, i, qsort_trans_data(), TD_SELECTED, and TransInfo::total.
Referenced by createTransData(), and transformEvent().
void special_aftertrans_update (bContext * C, TransInfo * t)
Definition at line 4867 of file transform_conversions.c.
References ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIM_editkeyframes_refresh(), ANIM_nla_mapping_apply_fcurve(), ANIM_nla_mapping_get(), ANIMCONT_ACTION, ANIMCONT_DOPESHEET, ANIMCONT_GPENCIL, ANIMCONT_SHAPEKEY, ANIMFILTER_CURVE_VISIBLE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_FOREDIT, apply_targetless_ik(), ARM_DELAYDEFORM, TransInfo::around, autokeyframe_ob_cb_func(), autokeyframe_pose_cb_func(), Object::avs, Scene::basact, BKE_nlastrips_clear_metas(), BKE_nlatrack_sort_strips(), BKE_ptcache_ids_from_object(), BKE_ptcache_object_reset(), BLI_freelistN(), BMEdit_FromObject(), PTCacheID::cache, bPose::chanbase, clear_trans_object_base_flags(), CONSTRAINT_IK_AUTO, count_set_pose_transflags(), CTX_AUTOCONFIRM, TransInfo::customData, DAG_id_tag_update(), TransInfo::data, data, Object::data, bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, ED_context_get_markers(), ED_markers_post_apply_transform(), ED_nla_postop_refresh(), ED_node_link_insert(), ED_node_link_intersect_test(), ED_node_update_hierarchy(), ED_objects_recalculate_paths(), ED_space_clip(), EDBM_automerge(), SpaceNode::edittree, ELEM, FALSE, filter(), ListBase::first, PointCache::flag, TransData::flag, bArmature::flag, bKinematicConstraint::flag, TransInfo::flag, SpaceIpo::flag, SpaceAction::flag, SpaceSeq::flag, TransInfo::frame_side, freeSlideTempFaces(), G, has_targetless_ik(), i, bGPdata::id, Object::id, MovieClip::id, ID_REAL_USERS, if(), bAnimListElem::key_data, Scene::markers, MAX_DUPLI_RECUR, mesh_octree_table(), Object::mode, TransInfo::mode, MOTIONPATH_BAKE_HAS_PATHS, NC_SCENE, ND_NODES, PTCacheID::next, bPoseChannel::next, ID::next, bAnimListElem::next, Scene::nodetree, nodeUpdateID(), NULL, TransData::ob, ob_get_key(), OB_MESH, OB_MODE_PARTICLE_EDIT, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, TransInfo::obedit, Base::object, TransInfo::options, bAnimVizSettings::path_bakeflag, PE_get_current(), SlideData::perc, Object::pose, pose_grab_with_ik_clear(), TransInfo::poseobj, posttrans_action_clean(), posttrans_fcurve_clean(), posttrans_gpd_clean(), projectSVData(), PTCACHE_OUTDATED, PTCACHE_RESET_OUTDATED, PTCACHE_TYPE_PARTICLES, Object::recalc, TransInfo::redraw, TransInfo::sa, SACTION_MARKERS_MOVE, SACTION_MOVING, SACTION_NOTRANSKEYCULL, TransInfo::scene, SEQ_MARKER_TRANS, SIPO_NOHANDLES, SIPO_NOTRANSKEYCULL, SPACE_ACTION, SPACE_CLIP, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, TransInfo::spacetype, TransInfo::state, NlaTrack::strips, T_AUTOIK, T_POSE, TD_NOACTION, TD_SKIP, TFM_DUMMY, TFM_EDGE_SLIDE, TFM_SEQ_SLIDE, TFM_TIME_DUPLICATE, TFM_TIME_EXTEND, TFM_TIME_SCALE, TFM_TIME_TRANSLATE, TFM_TRANSLATION, TransInfo::total, TRANS_CANCEL, transformApply(), TREDRAW_HARD, TRUE, PTCacheID::type, Object::type, TransInfo::values, TransInfo::view, where_is_pose(), and WM_event_add_notifier().
Referenced by calculateTransformCenter(), and transformEnd().
static void TimeToTransData (TransData * td, float * time, AnimData * adt) [static]
Definition at line 3023 of file transform_conversions.c.
References TransData::extra, TransData::ival, and TransData::val.
Referenced by ActionFCurveToTransData().
static void trackToTransData (SpaceClip * sc, TransData * td, TransData2D * td2d, TransDataTracking * tdt, MovieTrackingTrack * track) [static]
Definition at line 5505 of file transform_conversions.c.
References BKE_tracking_ensure_marker(), MovieTrackingTrack::flag, MovieTrackingMarker::flag, TransDataTracking::flag, MovieClipUser::framenr, MARKER_DISABLED, MARKER_TRACKED, markerToTransDataInit(), NULL, MovieTrackingTrack::offset, MovieTrackingTrack::pat_flag, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingMarker::pos, MovieTrackingTrack::search_flag, MovieTrackingTrack::search_max, MovieTrackingTrack::search_min, SELECT, TRACK_AREA_PAT, TRACK_AREA_POINT, TRACK_AREA_SEARCH, and SpaceClip::user.
Referenced by createTransTrackingTracksData().
static void transDataTrackingFree (TransInfo * t) [static]
Definition at line 5529 of file transform_conversions.c.
References TransInfo::customData, MEM_freeN(), and TransDataTracking::smarkers.
Referenced by createTransTrackingCurvesData(), and createTransTrackingTracksData().
void transform_autoik_update (TransInfo * t, short mode)
Definition at line 829 of file transform_conversions.c.
References ToolSettings::autoik_chainlen, bPose::chanbase, ELEM, ListBase::first, bPoseChannel::next, NULL, pchan_autoik_adjust(), Object::pose, TransInfo::poseobj, and TransInfo::settings.
Referenced by createTransPose(), and transformEvent().
static void UVsToTransData (SpaceImage * sima, TransData * td, TransData2D * td2d, float * uv, int selected) [static]
Definition at line 2400 of file transform_conversions.c.
References TransData::axismtx, TransData::center, copy_v3_v3(), TransData::dist, ED_space_image_uv_aspect(), TransData::ext, TransData::flag, TransData::iloc, TransData::loc, TransData2D::loc, TransData2D::loc2d, MAXFLOAT, TransData::mtx, NULL, TransData::smtx, TD_SELECTED, unit_m3(), and TransData::val.
Referenced by createTransUVs().
static void VertsToTransData (TransInfo * t, TransData * td, BMEditMesh * em, BMVert * eve, float * bweight) [static]
Definition at line 1984 of file transform_conversions.c.
References TransInfo::around, TransData::axismtx, TransData::center, BMVert::co, copy_v3_v3(), TransData::ext, TransData::extra, TransData::flag, get_edge_center(), get_face_center(), TransData::iloc, TransData::ival, TransData::loc, TransInfo::mode, BMVert::no, NULL, SCE_SELECT_EDGE, SCE_SELECT_FACE, BMEditMesh::selectmode, TFM_BWEIGHT, V3D_LOCAL, and TransData::val.
Referenced by createTransEditVerts().
Variable Documentation
enum { ... } transDataTracking_Mode