Blender: BL_InterpolatorList Class Reference
BL_InterpolatorList Class Reference
#include <KX_BlenderScalarInterpolator.h>
Public Member Functions
BL_InterpolatorList (struct bAction *action)
~BL_InterpolatorList ()
KX_IScalarInterpolator * GetScalarInterpolator (const char *rna_path, int array_index)
Detailed Description
Definition at line 65 of file KX_BlenderScalarInterpolator.h.
Constructor & Destructor Documentation
BL_InterpolatorList::BL_InterpolatorList (struct bAction * action)
Definition at line 50 of file KX_BlenderScalarInterpolator.cpp.
References bAction::curves, ListBase::first, and NULL.
BL_InterpolatorList::~BL_InterpolatorList ()
Definition at line 64 of file KX_BlenderScalarInterpolator.cpp.
References i.
Member Function Documentation
KX_IScalarInterpolator * BL_InterpolatorList::GetScalarInterpolator (const char * rna_path, int array_index)
Definition at line 72 of file KX_BlenderScalarInterpolator.cpp.
References FCurve::array_index, i, NULL, and FCurve::rna_path.
Referenced by BL_ConvertWorldIpos(), BL_CreateCameraIPO(), BL_CreateIPO(), BL_CreateLampIPO(), and ConvertMaterialIpos().
The documentation for this class was generated from the following files:
KX_BlenderScalarInterpolator.h
KX_BlenderScalarInterpolator.cpp