Blender: space_logic.c File Reference
space_logic.c File Reference
game logic editor
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "logic_intern.h"
Functions
ARegion * logic_has_buttons_region (ScrArea *sa)
static SpaceLink * logic_new (const bContext *UNUSED(C))
static void logic_free (SpaceLink *UNUSED(sl))
static void logic_init (struct wmWindowManager *UNUSED(wm), ScrArea *UNUSED(sa))
static SpaceLink * logic_duplicate (SpaceLink *sl)
static void logic_operatortypes (void)
static void logic_keymap (struct wmKeyConfig *keyconf)
static void logic_refresh (const bContext *UNUSED(C), ScrArea *UNUSED(sa))
static void logic_listener (ARegion *ar, wmNotifier *wmn)
static int logic_context (const bContext *UNUSED(C), const char *UNUSED(member), bContextDataResult *UNUSED(result))
static void logic_main_area_init (wmWindowManager *wm, ARegion *ar)
static void logic_main_area_draw (const bContext *C, ARegion *ar)
static void logic_buttons_area_init (wmWindowManager *wm, ARegion *ar)
static void logic_buttons_area_draw (const bContext *C, ARegion *ar)
static void logic_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void logic_header_area_draw (const bContext *C, ARegion *ar)
void ED_spacetype_logic (void)
Detailed Description
Definition in file space_logic.c.
Function Documentation
void ED_spacetype_logic (void)
Definition at line 303 of file space_logic.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), SpaceType::context, ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, logic_buttons_area_draw(), logic_buttons_area_init(), logic_context(), logic_duplicate(), logic_free(), logic_header_area_draw(), logic_header_area_init(), logic_init(), logic_keymap(), logic_listener(), logic_main_area_draw(), logic_main_area_init(), logic_new(), logic_operatortypes(), logic_refresh(), MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_LOGIC, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().
static void logic_buttons_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 282 of file space_logic.c.
References ED_region_panels(), and NULL.
Referenced by ED_spacetype_logic().
static void logic_buttons_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 272 of file space_logic.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, SPACE_LOGIC, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by ED_spacetype_logic().
static int logic_context (const bContext * UNUSEDC, const char * UNUSEDmember, bContextDataResult * UNUSEDresult) [static]
Definition at line 222 of file space_logic.c.
Referenced by ED_spacetype_logic().
static SpaceLink* logic_duplicate (SpaceLink * sl) [static]
Definition at line 166 of file space_logic.c.
References MEM_dupallocN().
Referenced by ED_spacetype_logic().
static void logic_free (SpaceLink * UNUSEDsl) [static]
Definition at line 150 of file space_logic.c.
Referenced by ED_spacetype_logic().
ARegion* logic_has_buttons_region (ScrArea * sa) [read]
Definition at line 61 of file space_logic.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by logic_properties().
static void logic_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 295 of file space_logic.c.
References ED_region_header().
Referenced by ED_spacetype_logic().
static void logic_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 290 of file space_logic.c.
References ED_region_header_init().
Referenced by ED_spacetype_logic().
static void logic_init (struct wmWindowManager * UNUSEDwm, ScrArea * UNUSEDsa) [static]
Definition at line 161 of file space_logic.c.
Referenced by ED_spacetype_logic().
static void logic_keymap (struct wmKeyConfig * keyconf) [static]
Definition at line 179 of file space_logic.c.
References AKEY, KM_CTRL, KM_PRESS, KM_SHIFT, LEFTMOUSE, NKEY, SPACE_LOGIC, WM_keymap_add_item(), WM_keymap_add_menu(), and WM_keymap_find().
Referenced by ED_spacetype_logic().
static void logic_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 195 of file space_logic.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_RENAME, NC_ID, NC_LOGIC, NC_OBJECT, NC_SCENE, ND_FRAME, and ND_OB_ACTIVE.
Referenced by ED_spacetype_logic().
static void logic_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 243 of file space_logic.c.
References logic_buttons(), TH_BACK, UI_ThemeClearColor(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, and V2D_GRID_CLAMP.
Referenced by ED_spacetype_logic().
static void logic_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 232 of file space_logic.c.
References wmWindowManager::defaultconf, ARegion::handlers, SPACE_LOGIC, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by ED_spacetype_logic().
static SpaceLink* logic_new (const bContext * UNUSEDC) [static]
Definition at line 87 of file space_logic.c.
References ARegion::alignment, BLI_addtail(), BUTS_ACT_ACT, BUTS_ACT_LINK, BUTS_ACT_SEL, BUTS_ACT_STATE, BUTS_CONT_ACT, BUTS_CONT_LINK, BUTS_CONT_SEL, BUTS_SENS_ACT, BUTS_SENS_LINK, BUTS_SENS_SEL, BUTS_SENS_STATE, View2D::cur, View2D::keeptot, View2D::keepzoom, View2D::max, View2D::maxzoom, MEM_callocN(), View2D::min, View2D::minzoom, SpaceLogic::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_TYPE_HEADER, RGN_TYPE_UI, RGN_TYPE_WINDOW, SpaceLogic::scaflag, View2D::scroll, SPACE_LOGIC, SpaceLogic::spacetype, View2D::tot, ARegion::v2d, V2D_KEEPASPECT, V2D_LIMITZOOM, V2D_SCROLL_BOTTOM, V2D_SCROLL_RIGHT, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_logic().
static void logic_operatortypes (void) [static]
Definition at line 173 of file space_logic.c.
References LOGIC_OT_links_cut(), LOGIC_OT_properties(), and WM_operatortype_append().
Referenced by ED_spacetype_logic().
static void logic_refresh (const bContext * UNUSEDC, ScrArea * UNUSEDsa) [static]
Definition at line 188 of file space_logic.c.
Referenced by ED_spacetype_logic().