Blender: AlphaBlockDXT5 Struct Reference
AlphaBlockDXT5 Struct Reference
DXT5 alpha block.
#include <BlockDXT.h>
Public Member Functions
uint8 alpha0 () const
uint8 alpha1 () const
uint8 bits0 () const
uint8 bits1 () const
uint8 bits2 () const
uint8 bits3 () const
uint8 bits4 () const
uint8 bits5 () const
uint8 bits6 () const
uint8 bits7 () const
uint8 bits8 () const
uint8 bits9 () const
uint8 bitsA () const
uint8 bitsB () const
uint8 bitsC () const
uint8 bitsD () const
uint8 bitsE () const
uint8 bitsF () const
void evaluatePalette (uint8 alpha[8]) const
void evaluatePalette8 (uint8 alpha[8]) const
void evaluatePalette6 (uint8 alpha[8]) const
void indices (uint8 index_array[16]) const
uint index (uint index) const
void setIndex (uint index, uint value)
void decodeBlock (ColorBlock *block) const
void flip4 ()
void flip2 ()
Public Attributes
uint64 u
Detailed Description
DXT5 alpha block.
Definition at line 147 of file BlockDXT.h.
Member Function Documentation
uint8 AlphaBlockDXT5::alpha0 () const [inline]
Definition at line 176 of file BlockDXT.h.
References u.
Referenced by evaluatePalette(), evaluatePalette6(), and evaluatePalette8().
uint8 AlphaBlockDXT5::alpha1 () const [inline]
Definition at line 177 of file BlockDXT.h.
References u.
Referenced by evaluatePalette(), evaluatePalette6(), and evaluatePalette8().
uint8 AlphaBlockDXT5::bits0 () const [inline]
Definition at line 178 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits1 () const [inline]
Definition at line 179 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits2 () const [inline]
Definition at line 180 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits3 () const [inline]
Definition at line 181 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits4 () const [inline]
Definition at line 182 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits5 () const [inline]
Definition at line 183 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits6 () const [inline]
Definition at line 184 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits7 () const [inline]
Definition at line 185 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits8 () const [inline]
Definition at line 186 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bits9 () const [inline]
Definition at line 187 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bitsA () const [inline]
Definition at line 188 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bitsB () const [inline]
Definition at line 189 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bitsC () const [inline]
Definition at line 190 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bitsD () const [inline]
Definition at line 191 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bitsE () const [inline]
Definition at line 192 of file BlockDXT.h.
References u.
Referenced by indices().
uint8 AlphaBlockDXT5::bitsF () const [inline]
Definition at line 193 of file BlockDXT.h.
References u.
Referenced by indices().
void AlphaBlockDXT5::decodeBlock (ColorBlock * block) const
Definition at line 418 of file BlockDXT.cpp.
References Color32::a, ColorBlock::color(), evaluatePalette(), i, and indices().
Referenced by BlockDXT5::decodeBlock(), and BlockDXT5::decodeBlockNV5x().
void AlphaBlockDXT5::evaluatePalette (uint8 alpha[8]) const
Definition at line 347 of file BlockDXT.cpp.
References alpha0(), alpha1(), evaluatePalette6(), and evaluatePalette8().
Referenced by BlockATI2::decodeBlock(), decodeBlock(), and BlockATI1::decodeBlock().
void AlphaBlockDXT5::evaluatePalette6 (uint8 alpha[8]) const
Definition at line 371 of file BlockDXT.cpp.
References alpha0(), and alpha1().
Referenced by evaluatePalette().
void AlphaBlockDXT5::evaluatePalette8 (uint8 alpha[8]) const
Definition at line 357 of file BlockDXT.cpp.
References alpha0(), and alpha1().
Referenced by evaluatePalette().
void AlphaBlockDXT5::flip2 ()
Definition at line 445 of file BlockDXT.cpp.
Referenced by BlockATI1::flip2(), BlockATI2::flip2(), and BlockDXT5::flip2().
void AlphaBlockDXT5::flip4 ()
Definition at line 431 of file BlockDXT.cpp.
Referenced by BlockDXT5::flip4(), BlockATI1::flip4(), and BlockATI2::flip4().
uint AlphaBlockDXT5::index (uint index) const
Definition at line 405 of file BlockDXT.cpp.
References u, and uint.
void AlphaBlockDXT5::indices (uint8 index_array[16]) const
Definition at line 385 of file BlockDXT.cpp.
References bits0(), bits1(), bits2(), bits3(), bits4(), bits5(), bits6(), bits7(), bits8(), bits9(), bitsA(), bitsB(), bitsC(), bitsD(), bitsE(), and bitsF().
Referenced by BlockATI2::decodeBlock(), BlockATI1::decodeBlock(), and decodeBlock().
void AlphaBlockDXT5::setIndex (uint index, uint value)
Definition at line 411 of file BlockDXT.cpp.
References u.
Member Data Documentation
uint64 AlphaBlockDXT5::u
Definition at line 175 of file BlockDXT.h.
Referenced by alpha0(), alpha1(), bits0(), bits1(), bits2(), bits3(), bits4(), bits5(), bits6(), bits7(), bits8(), bits9(), bitsA(), bitsB(), bitsC(), bitsD(), bitsE(), bitsF(), index(), mem_read(), and setIndex().
The documentation for this struct was generated from the following files:
BlockDXT.h
BlockDXT.cpp