Blender: bmesh_py_types_customdata.h File Reference
bmesh_py_types_customdata.h File Reference
Classes
struct BPy_BMLayerAccess
struct BPy_BMLayerCollection
struct BPy_BMLayerItem
Defines
#define BPy_BMLayerAccess_Check(v) (Py_TYPE(v) == &BPy_BMLayerAccess_Type)
#define BPy_BMLayerCollection_Check(v) (Py_TYPE(v) == &BPy_BMLayerCollection_Type)
#define BPy_BMLayerItem_Check(v) (Py_TYPE(v) == &BPy_BMLayerItem_Type)
Typedefs
typedef struct BPy_BMLayerAccess BPy_BMLayerAccess
typedef struct
BPy_BMLayerCollection BPy_BMLayerCollection
typedef struct BPy_BMLayerItem BPy_BMLayerItem
Functions
PyObject * BPy_BMLayerAccess_CreatePyObject (BMesh *bm, const char htype)
PyObject * BPy_BMLayerCollection_CreatePyObject (BMesh *bm, const char htype, int type)
PyObject * BPy_BMLayerItem_CreatePyObject (BMesh *bm, const char htype, int type, int index)
void BPy_BM_init_types_customdata (void)
PyObject * BPy_BMLayerItem_GetItem (BPy_BMElem *py_ele, BPy_BMLayerItem *py_layer)
BMElem.__getitem__()
int BPy_BMLayerItem_SetItem (BPy_BMElem *py_ele, BPy_BMLayerItem *py_layer, PyObject *value)
Variables
PyTypeObject BPy_BMLayerAccessVert_Type
PyTypeObject BPy_BMLayerAccessEdge_Type
PyTypeObject BPy_BMLayerAccessFace_Type
PyTypeObject BPy_BMLayerAccessLoop_Type
PyTypeObject BPy_BMLayerCollection_Type
PyTypeObject BPy_BMLayerItem_Type
Detailed Description
Definition in file bmesh_py_types_customdata.h.
Define Documentation
#define BPy_BMLayerAccess_Check (v) (Py_TYPE(v) == &BPy_BMLayerAccess_Type)
Definition at line 42 of file bmesh_py_types_customdata.h.
#define BPy_BMLayerCollection_Check (v) (Py_TYPE(v) == &BPy_BMLayerCollection_Type)
Definition at line 43 of file bmesh_py_types_customdata.h.
#define BPy_BMLayerItem_Check (v) (Py_TYPE(v) == &BPy_BMLayerItem_Type)
Definition at line 44 of file bmesh_py_types_customdata.h.
Referenced by bpy_bmlayercollection_remove(), and bpy_bmlayeritem_ptr_get().
Typedef Documentation
typedef struct BPy_BMLayerAccess BPy_BMLayerAccess
typedef struct BPy_BMLayerCollection BPy_BMLayerCollection
typedef struct BPy_BMLayerItem BPy_BMLayerItem
Function Documentation
void BPy_BM_init_types_customdata (void)
Definition at line 725 of file bmesh_py_types_customdata.c.
References bpy_bmelemseq_methods, bpy_bmlayeraccess_edge_getseters, bpy_bmlayeraccess_face_getseters, bpy_bmlayeraccess_loop_getseters, bpy_bmlayeraccess_vert_getseters, bpy_bmlayercollection_as_mapping, bpy_bmlayercollection_as_sequence, bpy_bmlayercollection_getseters, bpy_bmlayercollection_iter(), bpy_bmlayeritem_getseters, and NULL.
Referenced by BPyInit_bmesh().
PyObject* BPy_BMLayerAccess_CreatePyObject (BMesh * bm, const char htype)
Definition at line 681 of file bmesh_py_types_customdata.c.
References BLI_assert, BM_EDGE, BM_FACE, BM_LOOP, BM_VERT, BPy_BMLayerAccessEdge_Type, BPy_BMLayerAccessFace_Type, BPy_BMLayerAccessLoop_Type, BPy_BMLayerAccessVert_Type, and NULL.
Referenced by bpy_bmelemseq_layers_get().
PyObject* BPy_BMLayerCollection_CreatePyObject (BMesh * bm, const char htype, int type)
Definition at line 705 of file bmesh_py_types_customdata.c.
Referenced by bpy_bmlayeraccess_collection_get().
PyObject* BPy_BMLayerItem_CreatePyObject (BMesh * bm, const char htype, int type, int index)
Definition at line 714 of file bmesh_py_types_customdata.c.
Referenced by bpy_bmlayercollection_active_get(), bpy_bmlayercollection_get(), bpy_bmlayercollection_items(), bpy_bmlayercollection_new(), bpy_bmlayercollection_subscript_int(), bpy_bmlayercollection_subscript_slice(), bpy_bmlayercollection_subscript_str(), and bpy_bmlayercollection_values().
PyObject* BPy_BMLayerItem_GetItem (BPy_BMElem * py_ele, BPy_BMLayerItem * py_layer)
BMElem.__getitem__()
assume all error checks are done, eg:
uv = vert[uv_layer]
Definition at line 853 of file bmesh_py_types_customdata.c.
References BLI_strnlen(), BPy_BMDeformVert_CreatePyObject(), bpy_bmlayeritem_ptr_get(), BPy_BMLoopColor_CreatePyObject(), BPy_BMLoopUV_CreatePyObject(), CD_BWEIGHT, CD_CREASE, CD_MDEFORMVERT, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_PROP_FLT, CD_PROP_INT, CD_PROP_STR, CD_SHAPEKEY, NULL, Py_WRAP, MStringProperty::s, BPy_BMLayerItem::type, UNLIKELY, and Vector_CreatePyObject().
Referenced by bpy_bmelem_subscript().
int BPy_BMLayerItem_SetItem (BPy_BMElem * py_ele, BPy_BMLayerItem * py_layer, PyObject * value)
Definition at line 926 of file bmesh_py_types_customdata.c.
References BLI_strncpy(), BPy_BMDeformVert_AssignPyObject(), bpy_bmlayeritem_ptr_get(), BPy_BMLoopColor_AssignPyObject(), BPy_BMLoopUV_AssignPyObject(), CD_BWEIGHT, CD_CREASE, CD_MDEFORMVERT, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_PROP_FLT, CD_PROP_INT, CD_PROP_STR, CD_SHAPEKEY, CLAMPIS, copy_v3_v3(), mathutils_array_parse(), NULL, MStringProperty::s, BPy_BMLayerItem::type, and UNLIKELY.
Referenced by bpy_bmelem_ass_subscript().
Variable Documentation
PyTypeObject BPy_BMLayerAccessEdge_Type
Definition at line 674 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerAccessFace_Type
Definition at line 675 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerAccessLoop_Type
Definition at line 676 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerAccessVert_Type
Definition at line 673 of file bmesh_py_types_customdata.c.
Referenced by BPy_BMLayerAccess_CreatePyObject(), and BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerCollection_Type
Definition at line 677 of file bmesh_py_types_customdata.c.
Referenced by BPyInit_bmesh_types().
PyTypeObject BPy_BMLayerItem_Type
Definition at line 678 of file bmesh_py_types_customdata.c.
Referenced by BPyInit_bmesh_types().