Blender: bmesh_core.h File Reference
bmesh_core.h File Reference
BMesh
Functions
BMFace * BM_face_copy (BMesh *bm, BMFace *f, const short copyverts, const short copyedges)
BMVert * BM_vert_create (BMesh *bm, const float co[3], const BMVert *example)
Main function for creating a new vertex.
BMEdge * BM_edge_create (BMesh *bm, BMVert *v1, BMVert *v2, const BMEdge *example, int nodouble)
Main function for creating a new edge.
BMFace * BM_face_create (BMesh *bm, BMVert **verts, BMEdge **edges, const int len, int nodouble)
Main face creation function.
void BM_face_edges_kill (BMesh *bm, BMFace *f)
void BM_face_verts_kill (BMesh *bm, BMFace *f)
void BM_face_kill (BMesh *bm, BMFace *f)
void BM_edge_kill (BMesh *bm, BMEdge *e)
void BM_vert_kill (BMesh *bm, BMVert *v)
int bmesh_edge_separate (BMesh *bm, BMEdge *e, BMLoop *l_sep)
Separate Edge.
int BM_edge_splice (BMesh *bm, BMEdge *e, BMEdge *etarget)
Splice Edge.
int BM_vert_splice (BMesh *bm, BMVert *v, BMVert *vtarget)
Splice Vert.
int bmesh_vert_separate (BMesh *bm, BMVert *v, BMVert ***r_vout, int *r_vout_len)
Separate Vert.
int bmesh_loop_reverse (BMesh *bm, BMFace *f)
Flip the faces direction.
BMFace * BM_faces_join (BMesh *bm, BMFace **faces, int totface, const short do_del)
Join Connected Faces.
int BM_vert_separate (BMesh *bm, BMVert *v, BMVert ***r_vout, int *r_vout_len, BMEdge **e_in, int e_in_len)
BMFace * bmesh_sfme (BMesh *bm, BMFace *f, BMVert *v1, BMVert *v2, BMLoop **r_l, BMEdge *example, const short nodouble)
Split Face Make Edge (SFME)
BMVert * bmesh_semv (BMesh *bm, BMVert *tv, BMEdge *e, BMEdge **r_e)
Split Edge Make Vert (SEMV)
BMEdge * bmesh_jekv (BMesh *bm, BMEdge *ke, BMVert *kv, const short check_edge_splice)
Join Edge Kill Vert (JEKV)
BMFace * bmesh_jfke (BMesh *bm, BMFace *f1, BMFace *f2, BMEdge *e)
Join Face Kill Edge (JFKE)
BMVert * bmesh_urmv (BMesh *bm, BMFace *sf, BMVert *sv)
Unglue Region Make Vert (URMV)
BMVert * bmesh_urmv_loop (BMesh *bm, BMLoop *sl)
Unglue Region Make Vert (URMV)
Detailed Description
Definition in file bmesh_core.h.
Function Documentation
BMEdge* BM_edge_create (BMesh * bm, BMVert * v1, BMVert * v2, const BMEdge * example, int nodouble)
Main function for creating a new edge.
Note:
Duplicate edges are supported by the API however users should _never_ see them. so unless you need a unique edge or know the edge won't exist, you should call wih nodouble=TRUE
Definition at line 97 of file bmesh_core.c.
References BLI_mempool_calloc(), BM_CHECK_ELEMENT, BM_EDGE, BM_edge_exists(), BM_elem_attrs_copy(), BM_elem_flag_enable, BM_elem_index_set, BM_ELEM_SMOOTH, bmesh_disk_edge_append(), CustomData_bmesh_set_default(), BMHeader::data, BMesh::edata, BMesh::elem_index_dirty, BMesh::epool, BMEdge::head, BMHeader::htype, BMEdge::oflags, BMesh::toolflagpool, BMesh::totedge, BMEdge::v1, and BMEdge::v2.
Referenced by BM_edge_rotate(), BM_face_copy(), BM_face_create_ngon_vcloud(), BM_face_create_quad_tri_v(), BM_mesh_bm_from_me(), BM_mesh_copy(), bmesh_edge_separate(), bmesh_semv(), bmesh_sfme(), bmo_bevel_exec(), bmo_contextual_create_exec(), bmo_create_circle_exec(), bmo_create_grid_exec(), bmo_create_uvsphere_exec(), bmo_edgenet_prepare(), bmo_extrude_face_indiv_exec(), bmo_extrude_face_region_exec(), bmo_extrude_vert_indiv_exec(), bmo_inset_exec(), bmo_weldverts_exec(), bpy_bmedgeseq_new(), bpy_bmfaceseq_new(), copy_edge(), DM_to_bmesh_ex(), and init_rotsys().
void BM_edge_kill (BMesh * bm, BMEdge * e)
kills e and all faces that use it.
Definition at line 627 of file bmesh_core.c.
References BM_face_kill(), bm_kill_only_edge(), bmesh_disk_edge_remove(), BMLoop::f, BMEdge::l, BMLoop::radial_next, BMEdge::v1, and BMEdge::v2.
Referenced by BM_edge_splice(), BM_face_edges_kill(), BM_faces_join(), BM_vert_kill(), bmo_dissolve_limit_exec(), bmo_extrude_face_region_exec(), BMO_remove_tagged_edges(), and bpy_bmedgeseq_remove().
int BM_edge_splice (BMesh * bm, BMEdge * e, BMEdge * etarget)
Splice Edge.
Splice two unique edges which share the same two vertices into one edge.
Returns:
Success
Note:
Edges must already have the same vertices.
Definition at line 1968 of file bmesh_core.c.
References BLI_assert, BM_CHECK_ELEMENT, BM_edge_kill(), BM_vert_in_edge(), bmesh_radial_append(), bmesh_radial_length(), bmesh_radial_loop_remove(), FALSE, BMEdge::l, BMLoop::next, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by bmesh_jekv().
BMFace* BM_face_copy (BMesh * bm, BMFace * f, const short copyverts, const short copyedges)
Definition at line 185 of file bmesh_core.c.
References BLI_array_append, BLI_array_staticdeclare, BM_edge_create(), BM_elem_attrs_copy(), BM_face_create(), BM_FACE_FIRST_LOOP, BM_NGON_STACK_SIZE, BM_vert_create(), BMVert::co, BMLoop::e, FALSE, i, BMFace::len, BMLoop::next, NULL, BMLoop::v, and BMEdge::v1.
Referenced by BM_edge_split(), BM_face_split(), BM_face_split_n(), bpy_bmface_copy(), and createSlideVerts().
BMFace* BM_face_create (BMesh * bm, BMVert ** verts, BMEdge ** edges, const int len, int nodouble)
Main face creation function.
Definition at line 287 of file bmesh_core.c.
References BLI_assert, BM_CHECK_ELEMENT, bm_face_boundary_add(), bm_face_create__internal(), BM_face_exists(), bm_loop_create(), bmesh_radial_append(), BMLoop::e, BMLoop::f, i, len(), BMFace::len, BMLoop::next, NULL, BMLoop::prev, and BMLoop::v.
Referenced by BM_face_copy(), BM_face_create_ngon(), BM_face_create_quad_tri_v(), BM_mesh_bm_from_me(), bmo_bevel_exec(), bpy_bmfaceseq_new(), and copy_face().
void BM_face_edges_kill (BMesh * bm, BMFace * f)
kills all edges associated with f, along with any other faces containing those edges
Definition at line 542 of file bmesh_core.c.
References BLI_array_append, BLI_array_count, BLI_array_free, BLI_array_staticdeclare, BM_edge_kill(), BM_FACE_FIRST_LOOP, BM_NGON_STACK_SIZE, BMLoop::e, i, BMLoop::next, and NULL.
void BM_face_kill (BMesh * bm, BMFace * f)
Definition at line 586 of file bmesh_core.c.
References BLI_mempool_free(), BM_CHECK_ELEMENT, bm_kill_only_face(), bm_kill_only_loop(), bmesh_radial_loop_remove(), BMLoop::e, BMFace::l_first, and BMLoop::next.
Referenced by BM_edge_kill(), BM_face_split(), BM_faces_join(), BM_vert_collapse_faces(), bmo_bevel_exec(), BMO_remove_tagged_faces(), bpy_bmfaceseq_remove(), and knife_make_face_cuts().
void BM_face_verts_kill (BMesh * bm, BMFace * f)
kills all verts associated with f, along with any other faces containing those vertices
Definition at line 566 of file bmesh_core.c.
References BLI_array_append, BLI_array_count, BLI_array_free, BLI_array_staticdeclare, BM_FACE_FIRST_LOOP, BM_NGON_STACK_SIZE, BM_vert_kill(), i, BMLoop::next, NULL, and BMLoop::v.
Referenced by BM_edge_split(), BM_face_split_n(), and freeSlideTempFaces().
BMFace* BM_faces_join (BMesh * bm, BMFace ** faces, int totface, const short do_del)
Join Connected Faces.
Joins a collected group of faces into one. Only restriction on the input data is that the faces must be connected to each other.
Returns:
The newly created combine BMFace.
Note:
If a pair of faces share multiple edges, the pair of faces will be joined at every edge.
this is a generic, flexible join faces function, almost everything uses this, including BM_faces_join_pair
Definition at line 910 of file bmesh_core.c.
References _FLAG_JF, BLI_addtail(), BLI_array_append, BLI_array_count, BLI_array_free, BLI_array_staticdeclare, BLI_movelisttolist(), BLI_remlink(), BM_CHECK_ELEMENT, BM_edge_face_count(), BM_edge_kill(), BM_edge_other_vert(), BM_ELEM_API_FLAG_DISABLE, BM_ELEM_API_FLAG_ENABLE, BM_ELEM_API_FLAG_TEST, BM_elem_attrs_copy(), bm_elements_systag_disable(), bm_elements_systag_enable(), BM_face_create_ngon(), BM_FACE_FIRST_LOOP, BM_face_kill(), BM_loop_interp_multires(), BM_NGON_STACK_SIZE, BM_vert_kill(), BMERR_DISSOLVEFACES_FAILED, BMESH_ASSERT, BMO_error_occurred(), BMO_error_raise(), CD_MDISPS, count_flagged_radial(), BMesh::currentop, CustomData_has_layer(), disk_is_flagged(), BMLoop::e, err, error(), BMLoop::f, FALSE, i, BMesh::ldata, BMLoop::next, NULL, BMLoop::radial_next, UNLIKELY, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by BM_faces_join_pair(), BM_vert_collapse_faces(), bmo_bevel_exec(), bmo_dissolve_faces_exec(), and bpy_bm_utils_face_join().
BMVert* BM_vert_create (BMesh * bm, const float co[3], const BMVert * example)
Main function for creating a new vertex.
Definition at line 56 of file bmesh_core.c.
References BLI_mempool_calloc(), BM_CHECK_ELEMENT, BM_elem_attrs_copy(), BM_elem_index_set, BM_VERT, BMVert::co, copy_v3_v3(), CustomData_bmesh_set_default(), BMHeader::data, BMesh::elem_index_dirty, BMVert::head, BMHeader::htype, BMVert::oflags, BMesh::toolflagpool, BMesh::totvert, BMesh::vdata, and BMesh::vpool.
Referenced by BM_face_copy(), BM_mesh_bm_from_me(), BM_mesh_copy(), bmesh_semv(), bmesh_vert_separate(), bmo_bevel_exec(), bmo_create_circle_exec(), bmo_create_cone_exec(), bmo_create_cube_exec(), bmo_create_grid_exec(), bmo_create_icosphere_exec(), bmo_create_monkey_exec(), bmo_create_uvsphere_exec(), bmo_extrude_face_indiv_exec(), bmo_extrude_vert_indiv_exec(), bmo_inset_exec(), bmo_makevert_exec(), bpy_bmvertseq_new(), copy_vertex(), createRepresentation(), DM_to_bmesh_ex(), and init_rotsys().
void BM_vert_kill (BMesh * bm, BMVert * v)
kills v and all edges that use it.
Definition at line 657 of file bmesh_core.c.
References BM_edge_kill(), bm_kill_only_vert(), bmesh_disk_edge_next(), and BMVert::e.
Referenced by BM_face_verts_kill(), BM_faces_join(), BM_vert_dissolve(), BM_vert_splice(), bmo_dissolve_limit_exec(), BMO_remove_tagged_verts(), and bpy_bmvertseq_remove().
int BM_vert_separate (BMesh * bm, BMVert * v, BMVert *** r_vout, int * r_vout_len, BMEdge ** e_in, int e_in_len)
High level function which wraps both #bm_vert_separate and #bm_edge_separate
Definition at line 1944 of file bmesh_core.c.
References BM_vert_in_edge(), bmesh_edge_separate(), bmesh_vert_separate(), i, and BMEdge::l.
Referenced by bpy_bm_utils_vert_separate().
int BM_vert_splice (BMesh * bm, BMVert * v, BMVert * vtarget)
Splice Vert.
Merges two verts into one (v into vtarget).
Returns:
Success
Definition at line 1778 of file bmesh_core.c.
References BM_CHECK_ELEMENT, BM_ITER_ELEM, BM_LOOPS_OF_VERT, BM_vert_kill(), bmesh_disk_edge_append(), bmesh_disk_edge_remove(), bmesh_edge_swapverts(), BMVert::e, FALSE, TRUE, and BMLoop::v.
Referenced by bmesh_urmv_loop(), bmo_inset_exec(), and edbm_rip_invoke__vert().
int bmesh_edge_separate (BMesh * bm, BMEdge * e, BMLoop * l_sep)
Separate Edge.
Separates a single edge into two edge: the original edge and a new edge that has only l_sep in its radial.
Returns:
Success
Note:
Does nothing if l_sep is already the only loop in the edge radial.
Definition at line 2007 of file bmesh_core.c.
References BLI_assert, BM_CHECK_ELEMENT, BM_edge_create(), bmesh_radial_append(), bmesh_radial_length(), bmesh_radial_loop_remove(), BMLoop::e, FALSE, BMEdge::l, BMLoop::radial_next, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by BM_vert_separate(), bmesh_urmv_loop(), bmo_edgesplit_exec(), and bmo_inset_exec().
BMEdge* bmesh_jekv (BMesh * bm, BMEdge * ke, BMVert * kv, const short check_edge_double)
Join Edge Kill Vert (JEKV)
Takes an edge ke and pointer to one of its vertices kv and collapses the edge on that vertex.
Examples:
Before: OE KE ------- ------- | || | OV KV TV
After: OE --------------- | | OV TV
Restrictions:
KV is a vertex that must have a valance of exactly two. Furthermore both edges in KV's disk cycle (OE and KE) must be unique (no double edges).
Returns:
The resulting edge, NULL for failure.
Note:
This euler has the possibility of creating faces with just 2 edges. It is up to the caller to decide what to do with these faces.
Definition at line 1496 of file bmesh_core.c.
References BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BLI_mempool_free(), BM_CHECK_ELEMENT, BM_edge_exists(), BM_edge_splice(), BM_FACE_FIRST_LOOP, bm_kill_only_edge(), bm_kill_only_vert(), BM_NGON_STACK_SIZE, BMESH_ASSERT, bmesh_disk_count(), bmesh_disk_edge_append(), bmesh_disk_edge_next(), bmesh_disk_edge_remove(), bmesh_disk_validate(), bmesh_edge_other_vert_get(), bmesh_edge_swapverts(), bmesh_loop_validate(), bmesh_radial_length(), bmesh_radial_validate(), bmesh_vert_in_edge(), bmesh_verts_in_edge(), BMLoop::e, BMVert::e, BMLoop::f, FALSE, i, BMEdge::l, len(), BMFace::len, LIKELY, BMesh::lpool, BMLoop::next, NULL, BMLoop::prev, BMLoop::radial_next, BMesh::totloop, and BMLoop::v.
Referenced by BM_vert_collapse_edge(), and BM_vert_collapse_faces().
BMFace* bmesh_jfke (BMesh * bm, BMFace * f1, BMFace * f2, BMEdge * e)
Join Face Kill Edge (JFKE)
Takes two faces joined by a single 2-manifold edge and fuses them together. The edge shared by the faces must not be connected to any other edges which have Both faces in its radial cycle
Examples:
A B +--------+ +--------+ | | | | | f1 | | f1 | v1========v2 = Ok! v1==V2==v3 == Wrong! | f2 | | f2 | | | | | +--------+ +--------+
In the example A, faces f1 and f2 are joined by a single edge, and the euler can safely be used. In example B however, f1 and f2 are joined by multiple edges and will produce an error. The caller in this case should call bmesh_jekv on the extra edges before attempting to fuse f1 and f2.
Note:
The order of arguments decides whether or not certain per-face attributes are present in the resultant face. For instance vertex winding, material index, smooth flags, etc are inherited from f1, not f2.
Returns:
A BMFace pointer
Definition at line 1658 of file bmesh_core.c.
References BLI_mempool_free(), BM_CHECK_ELEMENT, BM_EDGE, BM_edge_is_manifold(), BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_INTERNAL_TAG, BM_FACE, BM_face_edge_share_loop(), BM_FACE_FIRST_LOOP, BM_face_share_edge_count(), BMESH_ASSERT, bmesh_disk_edge_remove(), bmesh_loop_validate(), bmesh_radial_face_find(), BMLoop::e, BMesh::elem_index_dirty, BMesh::epool, FALSE, BMesh::fpool, i, BMFace::len, BMesh::lpool, BMLoop::next, NULL, BMEdge::oflags, BMFace::oflags, BMLoop::prev, BMesh::toolflagpool, BMesh::totedge, BMesh::totface, BMesh::totloop, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by BME_Bevel_Dissolve_Disk(), and BME_bevel_edge().
int bmesh_loop_reverse (BMesh * bm, BMFace * f)
Flip the faces direction.
Definition at line 791 of file bmesh_core.c.
References bm_loop_reverse_loop().
Referenced by BM_face_normal_flip(), and BM_faces_join_pair().
BMVert* bmesh_semv (BMesh * bm, BMVert * tv, BMEdge * e, BMEdge ** r_e)
Split Edge Make Vert (SEMV)
Takes e edge and splits it into two, creating a new vert. tv should be one end of e : the newly created edge will be attached to that end and is returned in r_e.
Examples:
E Before: OV-------------TV
E RE After: OV------NV-----TV
Returns:
The newly created BMVert pointer.
Definition at line 1311 of file bmesh_core.c.
References BLI_assert, BM_CHECK_ELEMENT, BM_edge_create(), bm_loop_create(), BM_vert_create(), BMESH_ASSERT, bmesh_disk_count(), bmesh_disk_edge_append(), bmesh_disk_edge_remove(), bmesh_disk_validate(), bmesh_edge_other_vert_get(), bmesh_edge_swapverts(), bmesh_radial_append(), bmesh_radial_length(), bmesh_radial_loop_remove(), bmesh_radial_validate(), bmesh_vert_in_edge(), bmesh_verts_in_edge(), BMVert::co, BMLoop::e, BMVert::e, BMLoop::f, FALSE, i, BMEdge::l, BMFace::len, BMLoop::next, NULL, BMLoop::prev, BMLoop::radial_next, BMLoop::radial_prev, and BMLoop::v.
Referenced by BM_edge_split(), and BM_face_split_n().
BMFace* bmesh_sfme (BMesh * bm, BMFace * f, BMVert * v1, BMVert * v2, BMLoop ** r_l, BMEdge * example, const short nodouble)
Split Face Make Edge (SFME)
Takes as input two vertices in a single face. An edge is created which divides the original face into two distinct regions. One of the regions is assigned to the original face and it is closed off. The second region has a new face assigned to it.
Examples:
Before: After: +--------+ +--------+ | | | | | | | f1 | v1 f1 v2 v1======v2 | | | f2 | | | | | +--------+ +--------+
Note:
the input vertices can be part of the same edge. This will result in a two edged face. This is desirable for advanced construction tools and particularly essential for edge bevel. Because of this it is up to the caller to decide what to do with the extra edge.
If holes is NULL, then both faces will lose all holes from the original face. Also, you cannot split between a hole vert and a boundary vert; that case is handled by higher- level wrapping functions (when holes are fully implemented, anyway).
that holes represents which holes goes to the new face, and of course this requires removing them from the existing face first, since you cannot have linked list links inside multiple lists.
Returns:
A BMFace pointer
Definition at line 1160 of file bmesh_core.c.
References BLI_mempool_free(), BLI_movelisttolist(), BM_CHECK_ELEMENT, BM_edge_create(), bm_face_create__sfme(), BM_FACE_FIRST_LOOP, bm_loop_create(), bmesh_radial_append(), i, BMFace::l_first, len(), BMFace::len, BMLoop::next, NULL, and BMLoop::prev.
Referenced by BM_face_split(), and BM_face_split_n().
BMVert* bmesh_urmv (BMesh * bm, BMFace * sf, BMVert * sv)
Unglue Region Make Vert (URMV)
Disconnects sf from the vertex fan at sv
Returns:
The newly created BMVert
Definition at line 2121 of file bmesh_core.c.
References BM_face_vert_share_loop(), and bmesh_urmv_loop().
Referenced by BM_face_vert_separate().
BMVert* bmesh_urmv_loop (BMesh * bm, BMLoop * sl)
Unglue Region Make Vert (URMV)
Disconnects a face from its vertex fan at loop sl
Returns:
The newly created BMVert
Definition at line 2046 of file bmesh_core.c.
References BLI_assert, BM_vert_splice(), bmesh_disk_count(), bmesh_disk_edge_next(), bmesh_edge_separate(), bmesh_vert_separate(), BMLoop::e, BMVert::e, i, len(), MEM_freeN(), NULL, BMLoop::prev, SWAP, and BMLoop::v.
Referenced by BM_face_loop_separate(), and bmesh_urmv().
int bmesh_vert_separate (BMesh * bm, BMVert * v, BMVert *** r_vout, int * r_vout_len)
Separate Vert.
Separates all disjoint fans that meet at a vertex, making a unique vertex for each region. returns an array of all resulting vertices.
Note:
this is a low level function, bm_edge_separate needs to run on edges first or, the faces sharing verts must not be sharing edges for them to split at least.
Returns:
Success
Definition at line 1821 of file bmesh_core.c.
References BLI_array_append, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_pop, BLI_assert, BLI_ghash_free(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BM_CHECK_ELEMENT, BM_EDGES_OF_VERT, BM_ITER_ELEM, BM_LOOPS_OF_EDGE, BM_LOOPS_OF_VERT, BM_vert_create(), bmesh_disk_edge_append(), bmesh_disk_edge_remove(), bmesh_edge_swapverts(), BMVert::co, BMLoop::e, GET_INT_FROM_POINTER, i, if(), MEM_callocN(), MEM_freeN(), BMLoop::next, NULL, BMLoop::prev, SET_INT_IN_POINTER, stack, TRUE, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by BM_vert_separate(), bmesh_urmv_loop(), bmo_edgesplit_exec(), bmo_inset_exec(), and edbm_rip_invoke__vert().