Blender: rna_nla.c File Reference
rna_nla.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_anim_types.h"
#include "DNA_action_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_nlastrip (BlenderRNA *brna)
static void rna_api_nlatrack_strips (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_nlatrack (BlenderRNA *brna)
void RNA_def_nla (BlenderRNA *brna)
Variables
EnumPropertyItem nla_mode_blend_items []
EnumPropertyItem nla_mode_extend_items []
Detailed Description
Definition in file rna_nla.c.
Function Documentation
static void rna_api_nlatrack_strips (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 574 of file rna_nla.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_nlatrack().
void RNA_def_nla (BlenderRNA * brna)
Definition at line 663 of file rna_nla.c.
References rna_def_nlastrip(), and rna_def_nlatrack().
static void rna_def_nlastrip (BlenderRNA * brna) [static]
Definition at line 379 of file rna_nla.c.
References NC_ANIMATION, ND_NLA, NLASTRIP_FLAG_ACTIVE, NLASTRIP_FLAG_AUTO_BLENDS, NLASTRIP_FLAG_MUTED, NLASTRIP_FLAG_REVERSE, NLASTRIP_FLAG_SELECT, NLASTRIP_FLAG_USR_INFLUENCE, NLASTRIP_FLAG_USR_TIME, NLASTRIP_FLAG_USR_TIME_CYCLIC, NLASTRIP_TYPE_CLIP, NLASTRIP_TYPE_META, NLASTRIP_TYPE_SOUND, NLASTRIP_TYPE_TRANSITION, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_editable_func(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_nla().
static void rna_def_nlatrack (BlenderRNA * brna) [static]
Definition at line 606 of file rna_nla.c.
References NC_ANIMATION, ND_NLA, NLATRACK_ACTIVE, NLATRACK_MUTED, NLATRACK_PROTECTED, NLATRACK_SELECTED, NLATRACK_SOLO, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_NONE, PROP_STRING, rna_api_nlatrack_strips(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_nla().
Variable Documentation
EnumPropertyItem nla_mode_blend_items[]
Initial value:
 {
    {NLASTRIP_MODE_REPLACE, "REPLACE", 0, "Replace",
                            "Result strip replaces the accumulated results by amount specified by influence"},
    {NLASTRIP_MODE_ADD, "ADD", 0, "Add", "Weighted result of strip is added to the accumulated results"},
    {NLASTRIP_MODE_SUBTRACT, "SUBTRACT", 0, "Subtract",
                             "Weighted result of strip is removed from the accumulated results"},
    {NLASTRIP_MODE_MULTIPLY, "MULITPLY", 0, "Multiply",
                             "Weighted result of strip is multiplied with the accumulated results"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 363 of file rna_nla.c.
Referenced by rna_def_animdata().
EnumPropertyItem nla_mode_extend_items[]
Initial value:
 {
    {NLASTRIP_EXTEND_NOTHING, "NOTHING", 0, "Nothing", "Strip has no influence past its extents"},
    {NLASTRIP_EXTEND_HOLD, "HOLD", 0, "Hold",
                           "Hold the first frame if no previous strips in track, and always hold last frame"},
    {NLASTRIP_EXTEND_HOLD_FORWARD, "HOLD_FORWARD", 0, "Hold Forward", "Only hold last frame"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 372 of file rna_nla.c.
Referenced by rna_def_animdata().