Blender: btConcaveShape Class Reference
btConcaveShape Class Reference
#include <btConcaveShape.h>
Public Member Functions
btConcaveShape ()
virtual ~btConcaveShape ()
virtual void processAllTriangles (btTriangleCallback *callback, const btVector3 &aabbMin, const btVector3 &aabbMax) const =0
virtual btScalar getMargin () const
virtual void setMargin (btScalar collisionMargin)
Protected Attributes
btScalar m_collisionMargin
Detailed Description
The btConcaveShape class provides an interface for non-moving (static) concave shapes. It has been implemented by the btStaticPlaneShape, btBvhTriangleMeshShape and btHeightfieldTerrainShape.
Definition at line 36 of file btConcaveShape.h.
Constructor & Destructor Documentation
btConcaveShape::btConcaveShape ()
Definition at line 19 of file btConcaveShape.cpp.
btConcaveShape::~btConcaveShape () [virtual]
Definition at line 24 of file btConcaveShape.cpp.
Member Function Documentation
virtual btScalar btConcaveShape::getMargin () const [inline, virtual]
Implements btCollisionShape.
Reimplemented in btGImpactMeshShapePart.
Definition at line 48 of file btConcaveShape.h.
References m_collisionMargin.
Referenced by btHeightfieldTerrainShape::getAabb(), btTriangleMeshShape::getAabb(), btEmptyShape::getAabb(), btSoftClusterCollisionShape::getMargin(), btGImpactCollisionAlgorithm::gimpact_vs_concave(), btCollisionWorld::objectQuerySingle(), btConvexConcaveCollisionAlgorithm::processCollision(), and btSoftBodyConcaveCollisionAlgorithm::processCollision().
virtual void btConcaveShape::processAllTriangles (btTriangleCallback * callback, const btVector3 & aabbMin, const btVector3 & aabbMax) const [pure virtual]
Implemented in btEmptyShape, btHeightfieldTerrainShape, btTriangleMeshShape, btGImpactShapeInterface, btGImpactMeshShapePart, btGImpactMeshShape, and btSoftBodyCollisionShape.
Referenced by btConvexConcaveCollisionAlgorithm::calculateTimeOfImpact(), btSoftBodyConcaveCollisionAlgorithm::calculateTimeOfImpact(), btCollisionWorld::debugDrawObject(), btGImpactCollisionAlgorithm::gimpact_vs_concave(), btCollisionWorld::objectQuerySingle(), btConvexConcaveCollisionAlgorithm::processCollision(), btSoftBodyConcaveCollisionAlgorithm::processCollision(), and btCollisionWorld::rayTestSingle().
virtual void btConcaveShape::setMargin (btScalar collisionMargin) [inline, virtual]
Implements btCollisionShape.
Reimplemented in btGImpactShapeInterface, btGImpactMeshShapePart, and btGImpactMeshShape.
Definition at line 51 of file btConcaveShape.h.
References m_collisionMargin.
Referenced by btSoftClusterCollisionShape::btSoftClusterCollisionShape(), and btSoftClusterCollisionShape::setMargin().
Member Data Documentation
btScalar btConcaveShape::m_collisionMargin [protected]
Definition at line 39 of file btConcaveShape.h.
Referenced by getMargin(), btTriangleMeshShape::recalcLocalAabb(), btGImpactMeshShape::serialize(), btGImpactShapeInterface::setMargin(), btGImpactMeshShape::setMargin(), and setMargin().
The documentation for this class was generated from the following files:
btConcaveShape.h
btConcaveShape.cpp