Blender: svm_gamma.h File Reference
svm_gamma.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_gamma (ShaderData *sd, float *stack, uint in_gamma, uint in_color, uint out_color)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_gamma (ShaderData * sd, float * stack, uint in_gamma, uint in_color, uint out_color)
Definition at line 21 of file svm_gamma.h.
References powf, stack_load_float(), stack_load_float3(), stack_store_float3(), stack_valid(), float3::x, float3::y, and float3::z.
Referenced by svm_eval_nodes().