Blender: FModifierTypeInfo Struct Reference
FModifierTypeInfo Struct Reference
#include <BKE_fcurve.h>
Public Attributes
short type
short size
short acttype
short requires
char name [64]
char structName [64]
void(* free_data)(struct FModifier *fcm)
void(* copy_data)(struct FModifier *fcm, struct FModifier *src)
void(* new_data)(void *mdata)
void(* verify_data)(struct FModifier *fcm)
float(* evaluate_modifier_time)(struct FCurve *fcu, struct FModifier *fcm, float cvalue, float evaltime)
void(* evaluate_modifier)(struct FCurve *fcu, struct FModifier *fcm, float *cvalue, float evaltime)
Detailed Description
Definition at line 112 of file BKE_fcurve.h.
Member Data Documentation
short FModifierTypeInfo::acttype
Definition at line 116 of file BKE_fcurve.h.
Referenced by list_has_suitable_fmodifier().
void(* FModifierTypeInfo::copy_data)(struct FModifier *fcm, struct FModifier *src)
Definition at line 125 of file BKE_fcurve.h.
Referenced by copy_fmodifier(), and copy_fmodifiers().
void(* FModifierTypeInfo::evaluate_modifier)(struct FCurve *fcu, struct FModifier *fcm, float *cvalue, float evaltime)
Definition at line 135 of file BKE_fcurve.h.
Referenced by evaluate_value_fmodifiers().
float(* FModifierTypeInfo::evaluate_modifier_time)(struct FCurve *fcu, struct FModifier *fcm, float cvalue, float evaltime)
Definition at line 133 of file BKE_fcurve.h.
Referenced by evaluate_time_fmodifiers().
void(* FModifierTypeInfo::free_data)(struct FModifier *fcm)
Definition at line 123 of file BKE_fcurve.h.
Referenced by remove_fmodifier().
char FModifierTypeInfo::name[64]
Definition at line 118 of file BKE_fcurve.h.
Referenced by ANIM_uiTemplate_fmodifier_draw(), graph_fmodifier_add_invoke(), and nla_fmodifier_add_invoke().
void(* FModifierTypeInfo::new_data)(void *mdata)
Definition at line 127 of file BKE_fcurve.h.
Referenced by add_fmodifier().
short FModifierTypeInfo::requires
Definition at line 117 of file BKE_fcurve.h.
short FModifierTypeInfo::size
Definition at line 115 of file BKE_fcurve.h.
Referenced by add_fmodifier().
char FModifierTypeInfo::structName[64]
Definition at line 119 of file BKE_fcurve.h.
Referenced by add_fmodifier(), and write_fmodifiers().
short FModifierTypeInfo::type
Definition at line 114 of file BKE_fcurve.h.
void(* FModifierTypeInfo::verify_data)(struct FModifier *fcm)
Definition at line 129 of file BKE_fcurve.h.
Referenced by validate_fmodifier_cb().
The documentation for this struct was generated from the following file:
BKE_fcurve.h