Blender: AUD_LimiterReader Class Reference
AUD_LimiterReader Class Reference
#include <AUD_LimiterReader.h>
Public Member Functions
AUD_LimiterReader (AUD_Reference< AUD_IReader > reader, float start=0, float end=-1)
virtual void seek (int position)
virtual int getLength () const
virtual int getPosition () const
virtual void read (int &length, bool &eos, sample_t *buffer)
Detailed Description
This reader limits another reader in start and end times.
Definition at line 38 of file AUD_LimiterReader.h.
Constructor & Destructor Documentation
AUD_LimiterReader::AUD_LimiterReader (AUD_Reference< AUD_IReader > reader, float start = 0, float end = -1)
Creates a new limiter reader.
Parameters:
reader The reader to read from.
start The desired start time (inclusive).
end The desired end time (sample exklusive), a negative value signals that it should play to the end.
Definition at line 33 of file AUD_LimiterReader.cpp.
References AUD_Buffer::assureSize(), AUD_DEFAULT_BUFFER_SIZE, AUD_SAMPLE_SIZE, AUD_Specs::channels, AUD_Buffer::getBuffer(), len(), length(), AUD_EffectReader::m_reader, and AUD_Specs::rate.
Member Function Documentation
int AUD_LimiterReader::getLength () const [virtual]
Returns an approximated length of the source in samples.
Returns:
The length as sample count. May be negative if unknown.
Reimplemented from AUD_EffectReader.
Definition at line 83 of file AUD_LimiterReader.cpp.
References len(), and AUD_EffectReader::m_reader.
int AUD_LimiterReader::getPosition () const [virtual]
Returns the position of the source as a sample count value.
Returns:
The current position in the source. A negative value indicates that the position is unknown.
Warning:
The value returned doesn't always have to be correct for readers, especially after seeking.
Reimplemented from AUD_EffectReader.
Definition at line 92 of file AUD_LimiterReader.cpp.
References AUD_MIN, and AUD_EffectReader::m_reader.
void AUD_LimiterReader::read (int & length, bool & eos, sample_t * buffer) [virtual]
Request to read the next length samples out of the source. The buffer supplied has the needed size.
Parameters:
[in,out] length The count of samples that should be read. Shall contain the real count of samples after reading, in case there were only fewer samples available. A smaller value also indicates the end of the reader.
[out] eos End of stream, whether the end is reached or not.
[in] buffer The pointer to the buffer to read into.
Reimplemented from AUD_EffectReader.
Definition at line 99 of file AUD_LimiterReader.cpp.
References len(), length(), and AUD_EffectReader::m_reader.
void AUD_LimiterReader::seek (int position) [virtual]
Seeks to a specific position in the source.
Parameters:
position The position to seek for measured in samples. To get from a given time to the samples you simply have to multiply the time value in seconds with the sample rate of the reader.
Warning:
This may work or not, depending on the actual reader.
Reimplemented from AUD_EffectReader.
Definition at line 78 of file AUD_LimiterReader.cpp.
References AUD_EffectReader::m_reader.
The documentation for this class was generated from the following files:
AUD_LimiterReader.h
AUD_LimiterReader.cpp