Blender: drawnode.c File Reference
drawnode.c File Reference
node editor
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "DNA_node_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_space_types.h"
#include "DNA_screen_types.h"
#include "BKE_context.h"
#include "BKE_curve.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "NOD_composite.h"
#include "NOD_shader.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "BLF_api.h"
#include "MEM_guardedalloc.h"
#include "RNA_access.h"
#include "ED_node.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "IMB_imbuf.h"
#include "IMB_imbuf_types.h"
#include "node_intern.h"
Classes
struct SocketComponentMenuArgs
Defines
#define NODE_GROUP_FRAME 120
#define LINK_RESOL 24
Typedefs
typedef struct
SocketComponentMenuArgs SocketComponentMenuArgs
Functions
static void node_sync_cb (bContext *UNUSED(C), void *snode_v, void *node_v)
static void node_socket_button_label (const bContext *UNUSED(C), uiBlock *block, bNodeTree *UNUSED(ntree), bNode *UNUSED(node), bNodeSocket *sock, const char *UNUSED(name), int x, int y, int width)
static void node_socket_button_output_file (const bContext *C, uiBlock *block, bNodeTree *ntree, bNode *node, bNodeSocket *sock, const char *UNUSED(name), int x, int y, int width)
static void node_socket_button_default (const bContext *C, uiBlock *block, bNodeTree *ntree, bNode *node, bNodeSocket *sock, const char *name, int x, int y, int width)
static uiBlock * socket_component_menu (bContext *C, ARegion *ar, void *args_v)
static void node_socket_button_components (const bContext *C, uiBlock *block, bNodeTree *ntree, bNode *node, bNodeSocket *sock, const char *name, int x, int y, int width)
static void node_socket_button_color (const bContext *C, uiBlock *block, bNodeTree *ntree, bNode *node, bNodeSocket *sock, const char *name, int x, int y, int width)
static void node_buts_value (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_buts_rgb (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_buts_mix_rgb (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_buts_time (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_buts_colorramp (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_buts_curvevec (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_buts_curvecol (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_normal_cb (bContext *C, void *ntree_v, void *node_v)
static void node_buts_normal (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_dynamic_update_cb (bContext *C, void *UNUSED(ntree_v), void *node_v)
static void node_buts_texture (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_buts_math (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static int node_resize_area_default (bNode *node, int x, int y)
static void node_update_group (const bContext *C, bNodeTree *ntree, bNode *gnode)
static void update_group_input_cb (bContext *UNUSED(C), void *UNUSED(snode_v), void *ngroup_v)
static void update_group_output_cb (bContext *UNUSED(C), void *UNUSED(snode_v), void *ngroup_v)
static void draw_group_socket_name (SpaceNode *snode, bNode *gnode, bNodeSocket *sock, int in_out, float xoffset, float yoffset)
static void draw_group_socket (const bContext *C, SpaceNode *snode, bNodeTree *ntree, bNode *gnode, bNodeSocket *sock, bNodeSocket *gsock, int index, int in_out)
static void node_draw_group (const bContext *C, ARegion *ar, SpaceNode *snode, bNodeTree *ntree, bNode *gnode)
void node_uifunc_group (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_common_buts_whileloop (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_update_frame (const bContext *UNUSED(C), bNodeTree *UNUSED(ntree), bNode *node)
static void node_common_set_butfunc (bNodeType *ntype)
static void node_browse_text_cb (bContext *C, void *ntree_v, void *node_v)
static void node_shader_buts_material (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_shader_buts_mapping (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_vect_math (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_geometry (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_shader_buts_attribute (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_tex_image (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_shader_buts_tex_environment (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_shader_buts_tex_sky (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_tex_gradient (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_tex_magic (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_tex_wave (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_tex_musgrave (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_tex_voronoi (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_glossy (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_shader_buts_dynamic (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_shader_set_butfunc (bNodeType *ntype)
static void node_composit_buts_image (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_composit_buts_renderlayers (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_composit_buts_blur (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_dblur (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_bilateralblur (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_defocus (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_glare (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_tonemap (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_lensdist (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_vecblur (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_filter (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_flip (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_crop (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_splitviewer (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_double_edge_mask (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_map_value (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_alphaover (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_zcombine (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_hue_sat (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_dilateerode (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_diff_matte (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_distance_matte (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_color_spill (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_chroma_matte (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_color_matte (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_channel_matte (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_luma_matte (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_map_uv (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_id_mask (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_file_output (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_file_output_details (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_composit_buts_scale (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_rotate (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_invert (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_premulkey (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_view_levels (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_colorbalance (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_colorbalance_but (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_huecorrect (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_ycc (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_movieclip (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_composit_buts_stabilize2d (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_composit_buts_transform (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_composit_buts_moviedistortion (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_composit_set_butfunc (bNodeType *ntype)
static void node_texture_buts_bricks (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_texture_buts_proc (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_texture_buts_image (uiLayout *layout, bContext *C, PointerRNA *ptr)
static void node_texture_buts_output (uiLayout *layout, bContext *UNUSED(C), PointerRNA *ptr)
static void node_texture_set_butfunc (bNodeType *ntype)
void ED_init_node_butfuncs (void)
void draw_nodespace_back_pix (ARegion *ar, SpaceNode *snode, int color_manage)
int node_link_bezier_points (View2D *v2d, SpaceNode *snode, bNodeLink *link, float coord_array[][2], int resol)
void node_draw_link_bezier (View2D *v2d, SpaceNode *snode, bNodeLink *link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
static void node_link_straight_points (View2D *UNUSED(v2d), SpaceNode *snode, bNodeLink *link, float coord_array[][2])
void node_draw_link_straight (View2D *v2d, SpaceNode *snode, bNodeLink *link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
void node_draw_link (View2D *v2d, SpaceNode *snode, bNodeLink *link)
Variables
static float * _sample_col = NULL
Detailed Description
Definition in file drawnode.c.
Define Documentation
#define LINK_RESOL 24
Definition at line 2505 of file drawnode.c.
Referenced by node_draw_link_bezier(), and node_draw_link_straight().
#define NODE_GROUP_FRAME 120
Definition at line 531 of file drawnode.c.
Referenced by draw_group_socket(), node_draw_group(), and node_update_group().
Typedef Documentation
typedef struct SocketComponentMenuArgs SocketComponentMenuArgs
Function Documentation
static void draw_group_socket (const bContext * C, SpaceNode * snode, bNodeTree * ntree, bNode * gnode, bNodeSocket * sock, bNodeSocket * gsock, int index, int in_out) [static]
Definition at line 721 of file drawnode.c.
References bNode::block, BUT, draw_group_socket_name(), bNodeSocket::flag, bNodeType::flag, bNode::id, bNodeSocket::link, bNodeSocket::locx, bNodeSocket::locy, bNodeSocket::next, NODE_CONST_OUTPUT, NODE_DY, NODE_DYS, NODE_GROUP_FRAME, node_socket_circle_draw(), NODE_SOCKSIZE, ntreeGetSocketType(), NULL, bNodeSocket::prev, RNA_enum_set(), RNA_int_set(), SOCK_DYNAMIC, SOCK_IN, SOCK_INTERNAL, SOCK_OUT, bNodeSocket::type, bNode::typeinfo, UI_BUT_DISABLED, UI_EMBOSS, UI_EMBOSSN, UI_TOP, UI_UNIT_X, uiBlockBeginAlign(), uiBlockEndAlign(), uiBlockSetDirection(), uiBlockSetEmboss(), uiButGetOperatorPtrRNA(), uiButSetFlag(), and uiDefIconButO().
Referenced by node_draw_group().
static void draw_group_socket_name (SpaceNode * snode, bNode * gnode, bNodeSocket * sock, int in_out, float xoffset, float yoffset) [static]
Definition at line 700 of file drawnode.c.
References bNode::block, bNodeSocket::flag, bNode::id, if(), LABEL, bNodeSocket::locx, bNodeSocket::locy, bNodeSocket::name, NODE_DY, NULL, SOCK_DYNAMIC, SOCK_IN, TEX, uiButSetFunc(), uiDefBut(), update_group_input_cb(), and update_group_output_cb().
Referenced by draw_group_socket().
void draw_nodespace_back_pix (ARegion * ar, SpaceNode * snode, int color_manage)
Definition at line 2332 of file drawnode.c.
References B_ENDIAN, BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), BKE_image_verify_viewer(), ENDIAN_ORDER, SpaceNode::flag, glaDefine2DArea(), glaDrawPixelsSafe(), IB_PROFILE_LINEAR_RGB, IB_PROFILE_NONE, IMA_TYPE_COMPOSITE, IMB_rect_from_float(), NTREE_COMPOSIT, NULL, ImBuf::profile, ImBuf::rect, SNODE_BACKDRAW, SNODE_SHOW_ALPHA, SNODE_USE_ALPHA, SpaceNode::treetype, ARegion::winrct, ARegion::winx, ARegion::winy, wmOrtho2(), ImBuf::x, SpaceNode::xof, ImBuf::y, SpaceNode::yof, and SpaceNode::zoom.
Referenced by drawnodespace().
void ED_init_node_butfuncs (void)
Definition at line 2268 of file drawnode.c.
References bNodeSocketType::buttonfunc, bNodeType::drawfunc, bNodeType::drawupdatefunc, ListBase::first, i, bNodeType::next, node_common_set_butfunc(), node_composit_set_butfunc(), node_draw_default(), node_resize_area_default(), node_shader_set_butfunc(), node_socket_button_color(), node_socket_button_components(), node_socket_button_default(), node_socket_button_label(), node_texture_set_butfunc(), bNodeTreeType::node_types, node_update_default(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeGetSocketType(), ntreeGetType(), NULL, NUM_NTREE_TYPES, NUM_SOCKET_TYPES, bNodeType::resize_area_func, SOCK_BOOLEAN, SOCK_FLOAT, SOCK_INT, SOCK_RGBA, SOCK_SHADER, SOCK_VECTOR, bNodeSocketType::type, bNodeType::uifunc, and bNodeType::uifuncbut.
Referenced by WM_init().
static void node_browse_text_cb (bContext * C, void * ntree_v, void * node_v) [static]
Definition at line 990 of file drawnode.c.
References BLI_findlink(), BLI_strncpy(), BSET, CTX_data_main(), bNode::custom1, bNode::id, id_us_plus(), bNode::menunr, bNode::name, ID::name, NODE_DYNAMIC_NEW, nodeSetActive(), Main::text, and ID::us.
Referenced by node_shader_buts_dynamic().
static void node_buts_colorramp (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 365 of file drawnode.c.
References uiTemplateColorRamp().
Referenced by node_composit_set_butfunc(), node_shader_set_butfunc(), and node_texture_set_butfunc().
static void node_buts_curvecol (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 383 of file drawnode.c.
References copy_v3_v3(), CUMA_DRAW_SAMPLE, PointerRNA::data, CurveMapping::flag, CurveMapping::sample, bNode::storage, and uiTemplateCurveMapping().
Referenced by node_composit_set_butfunc(), node_shader_set_butfunc(), and node_texture_set_butfunc().
static void node_buts_curvevec (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 370 of file drawnode.c.
References uiTemplateCurveMapping().
Referenced by node_composit_set_butfunc(), and node_shader_set_butfunc().
static void node_buts_math (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 505 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc(), node_shader_set_butfunc(), and node_texture_set_butfunc().
static void node_buts_mix_rgb (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 331 of file drawnode.c.
References PointerRNA::data, PointerRNA::id, NTREE_COMPOSIT, bNodeTree::type, uiItemR(), and uiLayoutRow().
Referenced by node_composit_set_butfunc(), node_shader_set_butfunc(), and node_texture_set_butfunc().
static void node_buts_normal (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 406 of file drawnode.c.
References B_NODE_EXEC, BUT_NORMAL, bNode::butr, PointerRNA::data, bNodeSocket::default_value, ListBase::first, PointerRNA::id, node_normal_cb(), bNode::outputs, uiButSetFunc(), uiDefButF(), uiLayoutAbsoluteBlock(), rctf::xmax, and rctf::xmin.
Referenced by node_composit_set_butfunc(), and node_shader_set_butfunc().
static void node_buts_rgb (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 316 of file drawnode.c.
References RNA_property_collection_lookup_int(), RNA_struct_find_property(), uiItemR(), uiLayoutColumn(), and uiTemplateColorWheel().
Referenced by node_composit_set_butfunc(), and node_shader_set_butfunc().
static void node_buts_texture (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 486 of file drawnode.c.
References CMP_NODE_TEXTURE, PointerRNA::data, bNode::id, TEX_NODE_TEXTURE, bNode::type, and uiItemR().
Referenced by node_composit_set_butfunc(), node_shader_set_butfunc(), and node_texture_set_butfunc().
static void node_buts_time (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 343 of file drawnode.c.
References CFRA, CUMA_DRAW_CFRA, bNode::custom1, bNode::custom2, PointerRNA::data, CurveMapping::flag, CurveMapping::sample, bNode::storage, uiItemR(), uiLayoutRow(), and uiTemplateCurveMapping().
Referenced by node_composit_set_butfunc(), and node_texture_set_butfunc().
static void node_buts_value (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 304 of file drawnode.c.
References RNA_property_collection_lookup_int(), RNA_struct_find_property(), and uiItemR().
Referenced by node_composit_set_butfunc(), and node_shader_set_butfunc().
static void node_common_buts_whileloop (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 943 of file drawnode.c.
References NULL, and uiItemR().
Referenced by node_common_set_butfunc().
static void node_common_set_butfunc (bNodeType * ntype) [static]
Definition at line 964 of file drawnode.c.
References bNodeType::drawfunc, bNodeType::drawupdatefunc, node_common_buts_whileloop(), node_draw_group(), NODE_FORLOOP, NODE_FRAME, NODE_GROUP, node_uifunc_group(), node_update_frame(), node_update_group(), NODE_WHILELOOP, bNodeType::type, and bNodeType::uifunc.
Referenced by ED_init_node_butfuncs().
static void node_composit_buts_alphaover (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1594 of file drawnode.c.
References NULL, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_bilateralblur (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1399 of file drawnode.c.
References NULL, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_blur (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1345 of file drawnode.c.
References NULL, R_FILTER_FAST_GAUSS, RNA_boolean_get(), RNA_enum_get(), UI_ITEM_R_EXPAND, uiItemL(), uiItemR(), uiLayoutColumn(), and uiLayoutRow().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_channel_matte (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1695 of file drawnode.c.
References NULL, RNA_enum_get(), UI_ITEM_R_EXPAND, UI_ITEM_R_SLIDER, uiItemL(), uiItemR(), uiLayoutColumn(), and uiLayoutRow().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_chroma_matte (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1671 of file drawnode.c.
References NULL, UI_ITEM_R_SLIDER, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_color_matte (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1685 of file drawnode.c.
References NULL, UI_ITEM_R_SLIDER, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_color_spill (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1645 of file drawnode.c.
References NULL, RNA_boolean_get(), RNA_enum_get(), UI_ITEM_R_EXPAND, UI_ITEM_R_SLIDER, uiItemL(), uiItemR(), uiLayoutColumn(), and uiLayoutRow().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_colorbalance (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1823 of file drawnode.c.
References NULL, RNA_enum_get(), split(), uiItemR(), uiLayoutColumn(), uiLayoutRow(), uiLayoutSplit(), and uiTemplateColorWheel().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_colorbalance_but (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1868 of file drawnode.c.
References NULL, RNA_enum_get(), uiItemR(), and uiTemplateColorWheel().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_crop (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1529 of file drawnode.c.
References NULL, RNA_boolean_get(), uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_dblur (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1375 of file drawnode.c.
References NULL, uiItemL(), uiItemR(), uiItemS(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_defocus (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1409 of file drawnode.c.
References NULL, RNA_boolean_get(), uiItemL(), uiItemR(), uiLayoutColumn(), and uiLayoutSetActive().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_diff_matte (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1627 of file drawnode.c.
References NULL, UI_ITEM_R_SLIDER, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_dilateerode (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1622 of file drawnode.c.
References NULL, and uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_distance_matte (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1636 of file drawnode.c.
References NULL, UI_ITEM_R_SLIDER, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_double_edge_mask (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1561 of file drawnode.c.
References uiItemL(), uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_file_output (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1741 of file drawnode.c.
References R_IMF_IMTYPE_MULTILAYER, RNA_enum_get(), RNA_pointer_get(), uiItemL(), and uiItemR().
Referenced by node_composit_buts_file_output_details(), and node_composit_set_butfunc().
static void node_composit_buts_file_output_details (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1752 of file drawnode.c.
References PointerRNA::data, node_composit_buts_file_output(), NULL, R_IMF_IMTYPE_MULTILAYER, RNA_boolean_get(), RNA_enum_get(), RNA_pointer_get(), UI_ITEM_R_ICON_ONLY, uiItemFullO(), uiItemL(), uiItemO(), uiItemR(), uiItemS(), uiLayoutColumn(), uiLayoutRow(), uiLayoutSetActive(), uiTemplateImageSettings(), uiTemplateList(), and WM_OP_EXEC_DEFAULT.
Referenced by node_composit_set_butfunc().
static void node_composit_buts_filter (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1519 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_flip (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1524 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_glare (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1441 of file drawnode.c.
References NULL, RNA_enum_get(), UI_ITEM_R_SLIDER, and uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_hue_sat (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1612 of file drawnode.c.
References NULL, UI_ITEM_R_SLIDER, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_huecorrect (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1896 of file drawnode.c.
References uiTemplateCurveMapping().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_id_mask (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1735 of file drawnode.c.
References NULL, and uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_image (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1262 of file drawnode.c.
References BKE_image_user_get_frame(), BLI_snprintf(), CFRA, CTX_data_scene(), PointerRNA::data, ELEM, bNode::id, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, IMA_TYPE_MULTILAYER, NULL, PROP_POINTER, RNA_enum_get(), RNA_property_pointer_get(), RNA_property_type(), RNA_struct_find_property(), bNode::storage, UI_ITEM_R_ICON_ONLY, uiItemL(), uiItemR(), uiLayoutColumn(), and uiTemplateID().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_invert (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1804 of file drawnode.c.
References NULL, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_lensdist (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1490 of file drawnode.c.
References NULL, RNA_boolean_get(), uiItemR(), uiLayoutColumn(), and uiLayoutSetActive().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_luma_matte (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1721 of file drawnode.c.
References NULL, UI_ITEM_R_SLIDER, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_map_uv (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1730 of file drawnode.c.
References NULL, and uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_map_value (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1573 of file drawnode.c.
References NULL, RNA_boolean_get(), uiItemR(), uiLayoutColumn(), and uiLayoutSetActive().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_movieclip (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1906 of file drawnode.c.
References NULL, and uiTemplateID().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_moviedistortion (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1928 of file drawnode.c.
References PointerRNA::data, bNode::id, NULL, uiItemR(), and uiTemplateID().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_premulkey (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1813 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_renderlayers (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1309 of file drawnode.c.
References BLI_assert, PointerRNA::data, bNode::id, MAX_ID_NAME, NULL, RNA_pointer_get(), RNA_property_enum_get(), RNA_property_enum_identifier(), RNA_string_get(), RNA_string_set(), RNA_struct_find_property(), uiItemFullO_ptr(), uiItemR(), uiLayoutColumn(), uiLayoutRow(), uiTemplateID(), WM_OP_INVOKE_DEFAULT, WM_operator_properties_create_ptr(), and WM_operatortype_find().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_rotate (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1799 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_scale (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1794 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_splitviewer (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1551 of file drawnode.c.
References NULL, UI_ITEM_R_EXPAND, uiItemR(), uiLayoutColumn(), and uiLayoutRow().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_stabilize2d (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1911 of file drawnode.c.
References PointerRNA::data, bNode::id, NULL, uiItemR(), and uiTemplateID().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_tonemap (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1471 of file drawnode.c.
References NULL, RNA_enum_get(), UI_ITEM_R_SLIDER, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_transform (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1923 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_vecblur (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1503 of file drawnode.c.
References NULL, uiItemL(), uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_view_levels (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1818 of file drawnode.c.
References NULL, UI_ITEM_R_EXPAND, and uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_ycc (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1901 of file drawnode.c.
References uiItemR().
Referenced by node_composit_set_butfunc().
static void node_composit_buts_zcombine (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1603 of file drawnode.c.
References NULL, uiItemR(), and uiLayoutColumn().
Referenced by node_composit_set_butfunc().
static void node_composit_set_butfunc (bNodeType * ntype) [static]
Definition at line 1941 of file drawnode.c.
References CMP_NODE_ALPHAOVER, CMP_NODE_BILATERALBLUR, CMP_NODE_BLUR, CMP_NODE_CHANNEL_MATTE, CMP_NODE_CHROMA_MATTE, CMP_NODE_COLOR_MATTE, CMP_NODE_COLOR_SPILL, CMP_NODE_COLORBALANCE, CMP_NODE_COMBYCCA, CMP_NODE_CROP, CMP_NODE_CURVE_RGB, CMP_NODE_CURVE_VEC, CMP_NODE_DBLUR, CMP_NODE_DEFOCUS, CMP_NODE_DIFF_MATTE, CMP_NODE_DILATEERODE, CMP_NODE_DIST_MATTE, CMP_NODE_DOUBLEEDGEMASK, CMP_NODE_FILTER, CMP_NODE_FLIP, CMP_NODE_GLARE, CMP_NODE_HUE_SAT, CMP_NODE_HUECORRECT, CMP_NODE_ID_MASK, CMP_NODE_IMAGE, CMP_NODE_INVERT, CMP_NODE_LENSDIST, CMP_NODE_LUMA_MATTE, CMP_NODE_MAP_UV, CMP_NODE_MAP_VALUE, CMP_NODE_MATH, CMP_NODE_MIX_RGB, CMP_NODE_MOVIECLIP, CMP_NODE_MOVIEDISTORTION, CMP_NODE_NORMAL, CMP_NODE_OUTPUT_FILE, CMP_NODE_PREMULKEY, CMP_NODE_R_LAYERS, CMP_NODE_RGB, CMP_NODE_ROTATE, CMP_NODE_SCALE, CMP_NODE_SEPYCCA, CMP_NODE_SPLITVIEWER, CMP_NODE_STABILIZE2D, CMP_NODE_TEXTURE, CMP_NODE_TIME, CMP_NODE_TONEMAP, CMP_NODE_TRANSFORM, CMP_NODE_VALTORGB, CMP_NODE_VALUE, CMP_NODE_VECBLUR, CMP_NODE_VIEW_LEVELS, CMP_NODE_ZCOMBINE, node_buts_colorramp(), node_buts_curvecol(), node_buts_curvevec(), node_buts_math(), node_buts_mix_rgb(), node_buts_normal(), node_buts_rgb(), node_buts_texture(), node_buts_time(), node_buts_value(), node_composit_buts_alphaover(), node_composit_buts_bilateralblur(), node_composit_buts_blur(), node_composit_buts_channel_matte(), node_composit_buts_chroma_matte(), node_composit_buts_color_matte(), node_composit_buts_color_spill(), node_composit_buts_colorbalance(), node_composit_buts_colorbalance_but(), node_composit_buts_crop(), node_composit_buts_dblur(), node_composit_buts_defocus(), node_composit_buts_diff_matte(), node_composit_buts_dilateerode(), node_composit_buts_distance_matte(), node_composit_buts_double_edge_mask(), node_composit_buts_file_output(), node_composit_buts_file_output_details(), node_composit_buts_filter(), node_composit_buts_flip(), node_composit_buts_glare(), node_composit_buts_hue_sat(), node_composit_buts_huecorrect(), node_composit_buts_id_mask(), node_composit_buts_image(), node_composit_buts_invert(), node_composit_buts_lensdist(), node_composit_buts_luma_matte(), node_composit_buts_map_uv(), node_composit_buts_map_value(), node_composit_buts_movieclip(), node_composit_buts_moviedistortion(), node_composit_buts_premulkey(), node_composit_buts_renderlayers(), node_composit_buts_rotate(), node_composit_buts_scale(), node_composit_buts_splitviewer(), node_composit_buts_stabilize2d(), node_composit_buts_tonemap(), node_composit_buts_transform(), node_composit_buts_vecblur(), node_composit_buts_view_levels(), node_composit_buts_ycc(), node_composit_buts_zcombine(), NULL, bNodeType::type, bNodeType::uifunc, and bNodeType::uifuncbut.
Referenced by ED_init_node_butfuncs().
static void node_draw_group (const bContext * C, ARegion * ar, SpaceNode * snode, bNodeTree * ntree, bNode * gnode) [static]
Definition at line 819 of file drawnode.c.
References BASIS_RAD, bNode::block, draw_group_socket(), ListBase::first, bNode::flag, bNodeSocket::groupsock, bNode::id, bNodeTree::id, bNodeTree::inputs, bNode::inputs, MIN2, bNodeSocket::next, node_draw_default(), node_draw_nodetree(), NODE_GROUP_EDIT, NODE_GROUP_FRAME, NULL, bNode::outputs, bNodeTree::outputs, RNA_Node, RNA_pointer_create(), SOCK_IN, SOCK_OUT, TH_BACK, TH_NODE_GROUP, TH_TEXT_HI, bNode::totr, UI_CNR_ALL, UI_CNR_BOTTOM_LEFT, UI_CNR_BOTTOM_RIGHT, UI_CNR_NONE, UI_CNR_TOP_LEFT, UI_CNR_TOP_RIGHT, UI_GetStyle(), UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, UI_ThemeColor(), UI_ThemeColorShadeAlpha(), uiBlockLayout(), uiBlockLayoutResolve(), uiDrawBlock(), uiDrawBox(), uiEndBlock(), uiSetRoundBox(), and uiTemplateIDBrowse().
Referenced by drawnodespace(), and node_common_set_butfunc().
void node_draw_link (View2D * v2d, SpaceNode * snode, bNodeLink * link)
Definition at line 2649 of file drawnode.c.
References bNodeLink::flag, bNode::flag, bNodeSocket::flag, bNodeLink::fromnode, bNodeLink::fromsock, bNode::level, node_draw_link_bezier(), NODE_LINK_VALID, NODE_LINKFLAG_HILITE, NULL, SELECT, SOCK_UNAVAIL, TH_ACTIVE, TH_BACK, TH_EDGE_SELECT, TH_HEADER, TH_REDALERT, TH_WIRE, bNodeLink::tonode, bNodeLink::tosock, and UI_ThemeColorBlend().
Referenced by drawnodespace(), and node_draw_nodetree().
void node_draw_link_bezier (View2D * v2d, SpaceNode * snode, bNodeLink * link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
Definition at line 2506 of file drawnode.c.
References i, LINK_RESOL, node_link_bezier_points(), UI_ThemeColor(), UI_ThemeColorBlend(), and UI_ThemeColorShadeAlpha().
Referenced by node_draw_link(), and node_draw_mute_line().
void node_draw_link_straight (View2D * v2d, SpaceNode * snode, bNodeLink * link, int th_col1, int do_shaded, int th_col2, int do_triple, int th_col3)
Definition at line 2590 of file drawnode.c.
References i, LINK_RESOL, node_link_straight_points(), UI_ThemeColor(), UI_ThemeColorBlend(), and UI_ThemeColorShadeAlpha().
static void node_dynamic_update_cb (bContext * C, void * UNUSEDntree_v, void * node_v) [static]
Definition at line 454 of file drawnode.c.
References BSET, BTST, CTX_data_main(), bNode::custom1, error(), ListBase::first, Material::id, bNode::id, Main::mat, bNode::menunr, bNode::next, ID::next, NODE_DYNAMIC, NODE_DYNAMIC_ERROR, NODE_DYNAMIC_REPARSE, bNodeTree::nodes, Material::nodetree, and bNode::type.
Referenced by node_shader_buts_dynamic().
int node_link_bezier_points (View2D * v2d, SpaceNode * snode, bNodeLink * link, float coord_array[][2], int resol)
Definition at line 2459 of file drawnode.c.
References ABS, View2D::cur, forward_diff_bezier(), bNodeLink::fromsock, bNodeSocket::locx, bNodeSocket::locy, MAX4, MIN4, SpaceNode::mx, SpaceNode::my, NULL, TH_NODE_CURVING, bNodeLink::tosock, UI_GetThemeValue(), rctf::xmax, and rctf::xmin.
Referenced by cut_links_intersect(), and node_draw_link_bezier().
static void node_link_straight_points (View2D * UNUSEDv2d, SpaceNode * snode, bNodeLink * link, float coord_array[][2]) [static]
Definition at line 2568 of file drawnode.c.
References bNodeLink::fromsock, bNodeSocket::locx, bNodeSocket::locy, SpaceNode::mx, SpaceNode::my, NULL, and bNodeLink::tosock.
Referenced by node_draw_link_straight().
static void node_normal_cb (bContext * C, void * ntree_v, void * node_v) [static]
Definition at line 398 of file drawnode.c.
References CTX_data_main(), ED_node_generic_update(), NA_EDITED, NC_NODE, and WM_event_add_notifier().
Referenced by node_buts_normal().
static int node_resize_area_default (bNode * node, int x, int y) [static]
Definition at line 510 of file drawnode.c.
References BLI_in_rctf(), bNode::flag, NODE_HIDDEN, bNode::totr, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_init_node_butfuncs().
static void node_shader_buts_attribute (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1081 of file drawnode.c.
References uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_dynamic (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1136 of file drawnode.c.
References B_NODE_EXEC, B_NOP, BTST, BUT, bNode::butr, CTX_data_main(), bNode::custom1, PointerRNA::data, bNode::id, PointerRNA::id, IDnames_to_pupstring(), if(), MEM_freeN(), MENU, bNode::menunr, node_browse_text_cb(), NODE_DYNAMIC_ERROR, node_dynamic_update_cb(), NULL, Main::text, uiButSetFunc(), uiDefBut(), uiDefButS(), uiLayoutAbsoluteBlock(), rctf::xmin, and rctf::ymin.
Referenced by node_shader_set_butfunc().
static void node_shader_buts_geometry (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1062 of file drawnode.c.
References CTX_data_pointer_get(), PointerRNA::data, OB_MESH, RNA_enum_get(), RNA_pointer_get(), uiItemPointerR(), uiItemR(), and uiLayoutColumn().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_glossy (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1131 of file drawnode.c.
References uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_mapping (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1032 of file drawnode.c.
References uiItemL(), uiItemR(), and uiLayoutRow().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_material (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1017 of file drawnode.c.
References PointerRNA::data, bNode::id, NULL, uiItemR(), uiLayoutColumn(), and uiTemplateID().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_environment (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1093 of file drawnode.c.
References NULL, uiItemR(), and uiTemplateID().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_gradient (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1106 of file drawnode.c.
References uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_image (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 1086 of file drawnode.c.
References NULL, uiItemR(), and uiTemplateID().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_magic (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1111 of file drawnode.c.
References NULL, and uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_musgrave (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1121 of file drawnode.c.
References uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_sky (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1100 of file drawnode.c.
References NULL, and uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_voronoi (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1126 of file drawnode.c.
References uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_tex_wave (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1116 of file drawnode.c.
References uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_buts_vect_math (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 1057 of file drawnode.c.
References uiItemR().
Referenced by node_shader_set_butfunc().
static void node_shader_set_butfunc (bNodeType * ntype) [static]
Definition at line 1176 of file drawnode.c.
References node_buts_colorramp(), node_buts_curvecol(), node_buts_curvevec(), node_buts_math(), node_buts_mix_rgb(), node_buts_normal(), node_buts_rgb(), node_buts_texture(), node_buts_value(), NODE_DYNAMIC, node_shader_buts_attribute(), node_shader_buts_dynamic(), node_shader_buts_geometry(), node_shader_buts_glossy(), node_shader_buts_mapping(), node_shader_buts_material(), node_shader_buts_tex_environment(), node_shader_buts_tex_gradient(), node_shader_buts_tex_image(), node_shader_buts_tex_magic(), node_shader_buts_tex_musgrave(), node_shader_buts_tex_sky(), node_shader_buts_tex_voronoi(), node_shader_buts_tex_wave(), node_shader_buts_vect_math(), NULL, SH_NODE_ATTRIBUTE, SH_NODE_BSDF_GLASS, SH_NODE_BSDF_GLOSSY, SH_NODE_CURVE_RGB, SH_NODE_CURVE_VEC, SH_NODE_GEOMETRY, SH_NODE_MAPPING, SH_NODE_MATERIAL, SH_NODE_MATERIAL_EXT, SH_NODE_MATH, SH_NODE_MIX_RGB, SH_NODE_NORMAL, SH_NODE_RGB, SH_NODE_TEX_ENVIRONMENT, SH_NODE_TEX_GRADIENT, SH_NODE_TEX_IMAGE, SH_NODE_TEX_MAGIC, SH_NODE_TEX_MUSGRAVE, SH_NODE_TEX_SKY, SH_NODE_TEX_VORONOI, SH_NODE_TEX_WAVE, SH_NODE_TEXTURE, SH_NODE_VALTORGB, SH_NODE_VALUE, SH_NODE_VECT_MATH, bNodeType::type, bNodeType::uifunc, and bNodeType::uifuncbut.
Referenced by ED_init_node_butfuncs().
static void node_socket_button_color (const bContext * C, uiBlock * block, bNodeTree * ntree, bNode * node, bNodeSocket * sock, const char * name, int x, int y, int width) [static]
Definition at line 225 of file drawnode.c.
References B_NODE_EXEC, COL, CTX_wm_space_node(), bNodeSocket::flag, bNodeTree::id, LABEL, bNodeSocket::link, NODE_DY, node_socket_button_label(), node_socket_button_output_file(), node_sync_cb(), NULL, RNA_NodeSocket, RNA_pointer_create(), SOCK_HIDE_VALUE, SOCK_STRUCT_NONE, SOCK_STRUCT_OUTPUT_FILE, bNodeSocket::struct_type, uiButSetFunc(), uiDefBut(), and uiDefButR().
Referenced by ED_init_node_butfuncs().
static void node_socket_button_components (const bContext * C, uiBlock * block, bNodeTree * ntree, bNode * node, bNodeSocket * sock, const char * name, int x, int y, int width) [static]
Definition at line 191 of file drawnode.c.
References SocketComponentMenuArgs::arg1, SocketComponentMenuArgs::arg2, SocketComponentMenuArgs::cb, CTX_wm_space_node(), bNodeSocket::flag, bNodeTree::id, bNodeSocket::link, MEM_callocN(), NODE_DY, node_socket_button_label(), node_socket_button_output_file(), node_sync_cb(), SocketComponentMenuArgs::ptr, RNA_NodeSocket, RNA_pointer_create(), SOCK_HIDE_VALUE, SOCK_STRUCT_NONE, SOCK_STRUCT_OUTPUT_FILE, socket_component_menu(), bNodeSocket::struct_type, uiDefBlockButN(), SocketComponentMenuArgs::width, SocketComponentMenuArgs::x, and SocketComponentMenuArgs::y.
Referenced by ED_init_node_butfuncs().
static void node_socket_button_default (const bContext * C, uiBlock * block, bNodeTree * ntree, bNode * node, bNodeSocket * sock, const char * name, int x, int y, int width) [static]
Definition at line 141 of file drawnode.c.
References B_NODE_EXEC, CTX_wm_space_node(), bNodeSocket::flag, bNodeTree::id, bNodeSocket::link, NODE_DY, node_socket_button_label(), node_socket_button_output_file(), node_sync_cb(), NULL, NUM, RNA_NodeSocket, RNA_pointer_create(), SOCK_HIDE_VALUE, SOCK_STRUCT_NONE, SOCK_STRUCT_OUTPUT_FILE, bNodeSocket::struct_type, uiButSetFunc(), and uiDefButR().
Referenced by ED_init_node_butfuncs().
static void node_socket_button_label (const bContext * UNUSEDC, uiBlock * block, bNodeTree * UNUSEDntree, bNode * UNUSEDnode, bNodeSocket * sock, const char * UNUSEDname, int x, int y, int width) [static]
Definition at line 94 of file drawnode.c.
References LABEL, bNodeSocket::name, NODE_DY, NULL, and uiDefBut().
Referenced by ED_init_node_butfuncs(), node_socket_button_color(), node_socket_button_components(), and node_socket_button_default().
static void node_socket_button_output_file (const bContext * C, uiBlock * block, bNodeTree * ntree, bNode * node, bNodeSocket * sock, const char * UNUSEDname, int x, int y, int width) [static]
Definition at line 105 of file drawnode.c.
References bNodeTree::id, bNodeSocket::name, NODE_DY, R_IMF_IMTYPE_MULTILAYER, RNA_boolean_get(), RNA_enum_get(), RNA_Node, RNA_NodeSocket, RNA_pointer_create(), RNA_pointer_get(), RNA_property_enum_get(), RNA_property_enum_name(), RNA_struct_find_property(), UI_EMBOSSN, UI_EMBOSSP, UI_GetStyle(), UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, uiBlockLayout(), uiBlockLayoutResolve(), uiBlockSetEmboss(), uiItemL(), and uiLayoutRow().
Referenced by node_socket_button_color(), node_socket_button_components(), and node_socket_button_default().
static void node_sync_cb (bContext * UNUSEDC, void * snode_v, void * node_v) [static]
Definition at line 84 of file drawnode.c.
References nodeShaderSynchronizeID(), NTREE_SHADER, and SpaceNode::treetype.
Referenced by node_socket_button_color(), node_socket_button_components(), and node_socket_button_default().
static void node_texture_buts_bricks (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 2115 of file drawnode.c.
References uiItemR(), and uiLayoutColumn().
Referenced by node_texture_set_butfunc().
static void node_texture_buts_image (uiLayout * layout, bContext * C, PointerRNA * ptr) [static]
Definition at line 2208 of file drawnode.c.
References NULL, and uiTemplateID().
Referenced by node_texture_set_butfunc().
static void node_texture_buts_output (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 2213 of file drawnode.c.
References uiItemR().
Referenced by node_texture_set_butfunc().
static void node_texture_buts_proc (uiLayout * layout, bContext * UNUSEDC, PointerRNA * ptr) [static]
Definition at line 2128 of file drawnode.c.
References PointerRNA::data, PointerRNA::id, NULL, RNA_enum_get(), RNA_pointer_create(), RNA_Texture, bNode::storage, TEX_BAND, TEX_BLEND, TEX_CLOUDS, TEX_DISTNOISE, TEX_MAGIC, TEX_MARBLE, TEX_MINKOVSKY, TEX_MUSGRAVE, TEX_RING, TEX_STUCCI, TEX_VORONOI, TEX_WOOD, Tex::type, UI_ITEM_R_EXPAND, uiItemR(), uiLayoutColumn(), uiLayoutRow(), uiLayoutSetActive(), and Tex::vn_distm.
Referenced by node_texture_set_butfunc().
static void node_texture_set_butfunc (bNodeType * ntype) [static]
Definition at line 2219 of file drawnode.c.
References node_buts_colorramp(), node_buts_curvecol(), node_buts_math(), node_buts_mix_rgb(), node_buts_texture(), node_buts_time(), node_texture_buts_bricks(), node_texture_buts_image(), node_texture_buts_output(), node_texture_buts_proc(), NULL, TEX_NODE_BRICKS, TEX_NODE_CURVE_RGB, TEX_NODE_CURVE_TIME, TEX_NODE_IMAGE, TEX_NODE_MATH, TEX_NODE_MIX_RGB, TEX_NODE_OUTPUT, TEX_NODE_PROC, TEX_NODE_PROC_MAX, TEX_NODE_TEXTURE, TEX_NODE_VALTORGB, bNodeType::type, bNodeType::uifunc, and bNodeType::uifuncbut.
Referenced by ED_init_node_butfuncs().
void node_uifunc_group (uiLayout * layout, bContext * C, PointerRNA * ptr)
Definition at line 938 of file drawnode.c.
References NULL, and uiTemplateIDBrowse().
Referenced by node_common_set_butfunc().
static void node_update_frame (const bContext * UNUSEDC, bNodeTree * UNUSEDntree, bNode * node) [static]
Definition at line 948 of file drawnode.c.
References bNode::height, NODE_DYS, nodeSpaceCoords(), bNode::prvr, bNode::totr, bNode::width, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by node_common_set_butfunc().
static void node_update_group (const bContext * C, bNodeTree * ntree, bNode * gnode) [static]
Definition at line 536 of file drawnode.c.
References BLI_countlist(), BLI_union_rctf(), bNode::block, ListBase::first, bNode::flag, bNode::id, bNodeTree::inputs, bNode::inputs, bNode::next, NODE_DY, NODE_DYS, NODE_GROUP_EDIT, NODE_GROUP_FRAME, node_update_default(), node_update_nodetree(), bNodeTree::nodes, nodeSpaceCoords(), bNode::outputs, bNodeTree::outputs, bNode::totr, and uiExplicitBoundsBlock().
Referenced by node_common_set_butfunc().
static uiBlock* socket_component_menu (bContext * C, ARegion * ar, void * args_v) [static]
Definition at line 176 of file drawnode.c.
References NODE_DY, SocketComponentMenuArgs::ptr, UI_BLOCK_KEEP_OPEN, UI_EMBOSS, UI_GetStyle(), UI_ITEM_R_EXPAND, UI_LAYOUT_PANEL, UI_LAYOUT_VERTICAL, uiBeginBlock(), uiBlockLayout(), uiBlockSetFlag(), uiItemR(), uiLayoutColumn(), SocketComponentMenuArgs::width, SocketComponentMenuArgs::x, and SocketComponentMenuArgs::y.
Referenced by node_socket_button_components().
static void update_group_input_cb (bContext * UNUSEDC, void * UNUSEDsnode_v, void * ngroup_v) [static]
Definition at line 684 of file drawnode.c.
References NTREE_UPDATE_GROUP_IN, ntreeUpdateTree(), and bNodeTree::update.
Referenced by draw_group_socket_name().
static void update_group_output_cb (bContext * UNUSEDC, void * UNUSEDsnode_v, void * ngroup_v) [static]
Definition at line 692 of file drawnode.c.
References NTREE_UPDATE_GROUP_OUT, ntreeUpdateTree(), and bNodeTree::update.
Referenced by draw_group_socket_name().
Variable Documentation
float* _sample_col = NULL [static]
Definition at line 375 of file drawnode.c.