Blender: node_shader_value.c File Reference
node_shader_value.c File Reference
shdnodes
#include "node_shader_util.h"
Functions
static void node_shader_init_value (bNodeTree *UNUSED(ntree), bNode *node, bNodeTemplate *UNUSED(ntemp))
static void node_shader_exec_value (void *UNUSED(data), bNode *node, bNodeStack **UNUSED(in), bNodeStack **out)
static int gpu_shader_value (GPUMaterial *mat, bNode *node, GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_value (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_value_out []
Detailed Description
Definition in file node_shader_value.c.
Function Documentation
static int gpu_shader_value (GPUMaterial * mat, bNode * node, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 60 of file node_shader_value.c.
References bNodeSocket::default_value, ListBase::first, GPU_stack_link(), GPU_uniform(), and bNode::outputs.
Referenced by register_node_type_sh_value().
static void node_shader_exec_value (void * UNUSEDdata, bNode * node, bNodeStack ** UNUSEDin, bNodeStack ** out) [static]
Definition at line 52 of file node_shader_value.c.
References bNodeSocket::default_value, ListBase::first, bNode::outputs, and bNodeStack::vec.
Referenced by register_node_type_sh_value().
static void node_shader_init_value (bNodeTree * UNUSEDntree, bNode * node, bNodeTemplate * UNUSEDntemp) [static]
Definition at line 42 of file node_shader_value.c.
References bNodeSocket::default_value, ListBase::first, FLT_MAX, bNodeSocketValueFloat::max, bNodeSocketValueFloat::min, bNode::outputs, and bNodeSocketValueFloat::value.
Referenced by register_node_type_sh_value().
void register_node_type_sh_value (bNodeTreeType * ttype)
Definition at line 69 of file node_shader_value.c.
References gpu_shader_value(), NODE_CLASS_INPUT, NODE_NEW_SHADING, NODE_OLD_SHADING, NODE_OPTIONS, node_shader_exec_value(), node_shader_init_value(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), NULL, and SH_NODE_VALUE.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_value_out[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 0, "Value", 0.0f, 0.0f, 0.0f, 0.0f, -FLT_MAX, FLT_MAX},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_shader_value.c.