Blender: node_shader_brightness.c File Reference
node_shader_brightness.c File Reference
#include "node_shader_util.h"
Functions
void register_node_type_sh_brightcontrast (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_brightcontrast_in []
static bNodeSocketTemplate sh_node_brightcontrast_out []
Function Documentation
void register_node_type_sh_brightcontrast (bNodeTreeType * ttype)
Definition at line 46 of file node_shader_brightness.c.
References NODE_CLASS_OP_COLOR, NODE_NEW_SHADING, NODE_OPTIONS, node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_BRIGHTCONTRAST.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_brightcontrast_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Color",          1.0f, 1.0f, 1.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Bright",        0.0f, 0.0f, 0.0f, 0.0f, -100.0f, 100.0f, PROP_NONE},
    {   SOCK_FLOAT, 1, "Contrast",      0.0f, 0.0f, 0.0f, 0.0f, -100.0f, 100.0f, PROP_NONE},
    {   -1, 0, ""   }
}
Definition at line 34 of file node_shader_brightness.c.
bNodeSocketTemplate sh_node_brightcontrast_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Color"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_shader_brightness.c.