Blender: ntlMatrix4x4< Scalar > Class Template Reference
ntlMatrix4x4< Scalar > Class Template Reference
#include <ntl_matrices.h>
Public Member Functions
ntlMatrix4x4 (void)
ntlMatrix4x4 (const ntlMatrix4x4< Scalar > &v)
ntlMatrix4x4 (Scalar)
ntlMatrix4x4 (Scalar, Scalar, Scalar)
const ntlMatrix4x4< Scalar > & operator= (const ntlMatrix4x4< Scalar > &v)
const ntlMatrix4x4< Scalar > & operator= (Scalar s)
const ntlMatrix4x4< Scalar > & operator+= (const ntlMatrix4x4< Scalar > &v)
const ntlMatrix4x4< Scalar > & operator+= (Scalar s)
const ntlMatrix4x4< Scalar > & operator-= (const ntlMatrix4x4< Scalar > &v)
const ntlMatrix4x4< Scalar > & operator-= (Scalar s)
const ntlMatrix4x4< Scalar > & operator*= (const ntlMatrix4x4< Scalar > &v)
const ntlMatrix4x4< Scalar > & operator*= (Scalar s)
const ntlMatrix4x4< Scalar > & operator/= (const ntlMatrix4x4< Scalar > &v)
const ntlMatrix4x4< Scalar > & operator/= (Scalar s)
ntlMatrix4x4< Scalar > operator- () const
ntlMatrix4x4< Scalar > operator+ (const ntlMatrix4x4< Scalar > &) const
ntlMatrix4x4< Scalar > operator+ (Scalar) const
ntlMatrix4x4< Scalar > operator- (const ntlMatrix4x4< Scalar > &) const
ntlMatrix4x4< Scalar > operator- (Scalar) const
ntlMatrix4x4< Scalar > operator* (const ntlMatrix4x4< Scalar > &) const
ntlVector3Dim< Scalar > operator* (const ntlVector3Dim< Scalar > &) const
ntlMatrix4x4< Scalar > operator* (Scalar) const
ntlMatrix4x4< Scalar > operator/ (Scalar) const
void initId ()
init identity matrix
void initTranslation (Scalar x, Scalar y, Scalar z)
init rotation matrix
void initRotationX (Scalar rot)
init rotation matrix
void initRotationY (Scalar rot)
void initRotationZ (Scalar rot)
void initRotationXYZ (Scalar rotx, Scalar roty, Scalar rotz)
void initScaling (Scalar scale)
init scaling matrix
void initScaling (Scalar x, Scalar y, Scalar z)
init scaling matrix
void initArrayCheck (Scalar *array)
from 16 value array (init id if all 0)
void decompose (ntlVector3Dim< Scalar > &trans, ntlVector3Dim< Scalar > &scale, ntlVector3Dim< Scalar > &rot, ntlVector3Dim< Scalar > &shear)
decompose matrix
Public Attributes
Scalar value [4][4]
public to avoid [][] operators
Detailed Description
template<class Scalar>
class ntlMatrix4x4< Scalar >
Definition at line 20 of file ntl_matrices.h.
Constructor & Destructor Documentation
template<class Scalar > ntlMatrix4x4< Scalar >::ntlMatrix4x4 (void) [inline]
Definition at line 176 of file ntl_matrices.h.
References i.
template<class Scalar> ntlMatrix4x4< Scalar >::ntlMatrix4x4 (const ntlMatrix4x4< Scalar > & v) [inline]
Definition at line 193 of file ntl_matrices.h.
References ntlMatrix4x4< Scalar >::value.
template<class Scalar> ntlMatrix4x4< Scalar >::ntlMatrix4x4 (Scalar s) [inline]
Definition at line 210 of file ntl_matrices.h.
References i.
template<class Scalar> ntlMatrix4x4< Scalar >::ntlMatrix4x4 (Scalar , Scalar , Scalar) [inline]
Member Function Documentation
template<class Scalar> void ntlMatrix4x4< Scalar >::decompose (ntlVector3Dim< Scalar > & trans, ntlVector3Dim< Scalar > & scale, ntlVector3Dim< Scalar > & rot, ntlVector3Dim< Scalar > & shear)
decompose matrix
Definition at line 707 of file ntl_matrices.h.
References KDL::asin(), KDL::atan2(), cos(), cross(), dot(), fabs(), i, M_PI, norm(), normalize(), and VECTOR_EPSILON.
Referenced by ntlBlenderDumper::renderScene().
template<class Scalar> void ntlMatrix4x4< Scalar >::initArrayCheck (Scalar * array) [inline]
from 16 value array (init id if all 0)
Definition at line 692 of file ntl_matrices.h.
References i.
Referenced by LbmSolverInterface::initDomainTrafo().
template<class Scalar > void ntlMatrix4x4< Scalar >::initId () [inline]
init identity matrix
Definition at line 580 of file ntl_matrices.h.
Referenced by ParticleTracer::getTriangles(), ParticleTracer::initTrafoMatrix(), LbmSolverInterface::LbmSolverInterface(), and ntlBlenderDumper::renderScene().
template<class Scalar> void ntlMatrix4x4< Scalar >::initRotationX (Scalar rot) [inline]
init rotation matrix
Definition at line 603 of file ntl_matrices.h.
References cos(), M_PI, and sin().
Referenced by ntlMatrix4x4< Scalar >::initRotationXYZ().
template<class Scalar> void ntlMatrix4x4< Scalar >::initRotationXYZ (Scalar rotx, Scalar roty, Scalar rotz) [inline]
Definition at line 642 of file ntl_matrices.h.
References ntlMatrix4x4< Scalar >::initRotationX(), ntlMatrix4x4< Scalar >::initRotationY(), ntlMatrix4x4< Scalar >::initRotationZ(), and rot.
Referenced by ntlGeometryObject::applyTransformation(), ntlGeometryObject::getInitialVelocity(), and ntlBlenderDumper::renderScene().
template<class Scalar> void ntlMatrix4x4< Scalar >::initRotationY (Scalar rot) [inline]
Definition at line 616 of file ntl_matrices.h.
References cos(), M_PI, and sin().
Referenced by ntlMatrix4x4< Scalar >::initRotationXYZ().
template<class Scalar> void ntlMatrix4x4< Scalar >::initRotationZ (Scalar rot) [inline]
Definition at line 629 of file ntl_matrices.h.
References cos(), M_PI, and sin().
Referenced by ntlMatrix4x4< Scalar >::initRotationXYZ().
template<class Scalar> void ntlMatrix4x4< Scalar >::initScaling (Scalar x, Scalar y, Scalar z) [inline]
init scaling matrix
Definition at line 680 of file ntl_matrices.h.
template<class Scalar> void ntlMatrix4x4< Scalar >::initScaling (Scalar scale) [inline]
init scaling matrix
Definition at line 670 of file ntl_matrices.h.
template<class Scalar> void ntlMatrix4x4< Scalar >::initTranslation (Scalar x, Scalar y, Scalar z) [inline]
init rotation matrix
Definition at line 591 of file ntl_matrices.h.
template<class Scalar> ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator* (Scalar s) const [inline]
Definition at line 498 of file ntl_matrices.h.
References i.
template<class Scalar> ntlVector3Dim< Scalar > ntlMatrix4x4< Scalar >::operator* (const ntlVector3Dim< Scalar > & v) const [inline]
Definition at line 557 of file ntl_matrices.h.
References i.
template<class Scalar> ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator* (const ntlMatrix4x4< Scalar > & v) const [inline]
Definition at line 541 of file ntl_matrices.h.
References i, and ntlMatrix4x4< Scalar >::value.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator*= (Scalar s) [inline]
Definition at line 355 of file ntl_matrices.h.
References i.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator*= (const ntlMatrix4x4< Scalar > & v) [inline]
Definition at line 333 of file ntl_matrices.h.
References i, and ntlMatrix4x4< Scalar >::value.
template<class Scalar> ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator+ (Scalar s) const [inline]
Definition at line 440 of file ntl_matrices.h.
References i.
template<class Scalar> ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator+ (const ntlMatrix4x4< Scalar > & v) const [inline]
Definition at line 421 of file ntl_matrices.h.
References i, and ntlMatrix4x4< Scalar >::value.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator+= (Scalar s) [inline]
Definition at line 280 of file ntl_matrices.h.
References i.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator+= (const ntlMatrix4x4< Scalar > & v) [inline]
Definition at line 263 of file ntl_matrices.h.
References ntlMatrix4x4< Scalar >::value.
template<class Scalar> ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator- (Scalar s) const [inline]
Definition at line 478 of file ntl_matrices.h.
References i.
template<class Scalar > ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator- () const [inline]
Definition at line 396 of file ntl_matrices.h.
References i.
template<class Scalar> ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator- (const ntlMatrix4x4< Scalar > & v) const [inline]
Definition at line 459 of file ntl_matrices.h.
References i, and ntlMatrix4x4< Scalar >::value.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator-= (const ntlMatrix4x4< Scalar > & v) [inline]
Definition at line 298 of file ntl_matrices.h.
References ntlMatrix4x4< Scalar >::value.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator-= (Scalar s) [inline]
Definition at line 315 of file ntl_matrices.h.
References i.
template<class Scalar> ntlMatrix4x4< Scalar > ntlMatrix4x4< Scalar >::operator/ (Scalar s) const [inline]
Definition at line 519 of file ntl_matrices.h.
References i.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator/= (Scalar s) [inline]
Definition at line 374 of file ntl_matrices.h.
References i.
template<class Scalar> const ntlMatrix4x4<Scalar>& ntlMatrix4x4< Scalar >::operator/= (const ntlMatrix4x4< Scalar > & v) [inline]
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator= (const ntlMatrix4x4< Scalar > & v) [inline]
Definition at line 228 of file ntl_matrices.h.
References ntlMatrix4x4< Scalar >::value.
template<class Scalar> const ntlMatrix4x4< Scalar > & ntlMatrix4x4< Scalar >::operator= (Scalar s) [inline]
Definition at line 245 of file ntl_matrices.h.
References i.
Member Data Documentation
template<class Scalar> Scalar ntlMatrix4x4< Scalar >::value[4][4]
public to avoid [][] operators
Definition at line 94 of file ntl_matrices.h.
Referenced by ParticleTracer::checkDumpTextPositions(), ParticleTracer::initTrafoMatrix(), ParticleTracer::notifyOfDump(), ntlMatrix4x4< Scalar >::ntlMatrix4x4(), ntlMatrix4x4< Scalar >::operator*(), ntlMatrix4x4< Scalar >::operator*=(), ntlMatrix4x4< Scalar >::operator+(), ntlMatrix4x4< Scalar >::operator+=(), ntlMatrix4x4< Scalar >::operator-(), ntlMatrix4x4< Scalar >::operator-=(), ntlMatrix4x4< Scalar >::operator=(), and operator>>().
The documentation for this class was generated from the following file:
ntl_matrices.h