Blender: device_cpu.cpp File Reference
device_cpu.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include "device.h"
#include "device_intern.h"
#include "kernel.h"
#include "kernel_types.h"
#include "osl_shader.h"
#include "util_debug.h"
#include "util_foreach.h"
#include "util_function.h"
#include "util_opengl.h"
#include "util_progress.h"
#include "util_system.h"
#include "util_thread.h"
Classes
class CPUDevice
Functions
Device * device_cpu_create (DeviceInfo &info, int threads)
void device_cpu_info (vector< DeviceInfo > &devices)
Function Documentation
Device* device_cpu_create (DeviceInfo & info, int threads)
Definition at line 256 of file device_cpu.cpp.
Referenced by Device::create().
void device_cpu_info (vector< DeviceInfo > & devices)
Definition at line 261 of file device_cpu.cpp.
References DeviceInfo::advanced_shading, DeviceInfo::description, DEVICE_CPU, DeviceInfo::id, DeviceInfo::num, system_cpu_brand_string(), and DeviceInfo::type.
Referenced by Device::available_devices().