Blender: speaker.c File Reference
speaker.c File Reference
blenkernel
#include "DNA_object_types.h"
#include "DNA_sound_types.h"
#include "DNA_speaker_types.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BLI_bpath.h"
#include "BKE_animsys.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_speaker.h"
Functions
void * add_speaker (const char *name)
Speaker * copy_speaker (Speaker *spk)
void make_local_speaker (Speaker *spk)
void free_speaker (Speaker *spk)
Detailed Description
Definition in file speaker.c.
Function Documentation
void* add_speaker (const char * name)
Definition at line 46 of file speaker.c.
References alloc_libblock(), Speaker::attenuation, Speaker::cone_angle_inner, Speaker::cone_angle_outer, Speaker::cone_volume_outer, Speaker::distance_max, Speaker::distance_reference, Speaker::flag, FLT_MAX, G, ID_SPK, NULL, Speaker::pitch, Speaker::sound, Speaker::volume, Speaker::volume_max, and Speaker::volume_min.
Referenced by add_obdata_from_type().
Speaker* copy_speaker (Speaker * spk) [read]
Definition at line 68 of file speaker.c.
References copy_libblock(), bSound::id, Speaker::id, Speaker::sound, and ID::us.
Referenced by id_copy(), make_local_speaker(), object_add_duplicate_internal(), and single_obdata_users().
void free_speaker (Speaker * spk)
Definition at line 130 of file speaker.c.
References BKE_free_animdata(), bSound::id, Speaker::sound, and ID::us.
Referenced by free_libblock().
void make_local_speaker (Speaker * spk)
Definition at line 79 of file speaker.c.
References BKE_id_lib_local_paths(), copy_speaker(), Object::data, FALSE, ListBase::first, G, Object::id, Speaker::id, id_clear_lib_data(), ID::lib, ID::next, NULL, Main::object, TRUE, and ID::us.
Referenced by id_make_local().