Blender: AUD_SDLDevice Class Reference
AUD_SDLDevice Class Reference
#include <AUD_SDLDevice.h>
Public Member Functions
AUD_SDLDevice (AUD_DeviceSpecs specs, int buffersize=AUD_DEFAULT_BUFFER_SIZE)
virtual ~AUD_SDLDevice ()
Protected Member Functions
virtual void playing (bool playing)
Detailed Description
This device plays back through SDL, the simple direct media layer.
Definition at line 40 of file AUD_SDLDevice.h.
Constructor & Destructor Documentation
AUD_SDLDevice::AUD_SDLDevice (AUD_DeviceSpecs specs, int buffersize = AUD_DEFAULT_BUFFER_SIZE)
Opens the SDL audio device for playback.
Parameters:
specs The wanted audio specification.
buffersize The size of the internal buffer.
Note:
The specification really used for opening the device may differ.
Exceptions:
AUD_Exception Thrown if the audio device cannot be opened.
Definition at line 44 of file AUD_SDLDevice.cpp.
References AUD_CHANNELS_INVALID, AUD_CHANNELS_STEREO, AUD_ERROR_SDL, AUD_FORMAT_INVALID, AUD_FORMAT_S16, AUD_FORMAT_U8, AUD_RATE_44100, AUD_RATE_INVALID, AUD_THROW, AUD_DeviceSpecs::channels, AUD_SoftwareDevice::create(), AUD_DeviceSpecs::format, AUD_SoftwareDevice::m_specs, and AUD_DeviceSpecs::rate.
AUD_SDLDevice::~AUD_SDLDevice () [virtual]
Closes the SDL audio device.
Definition at line 85 of file AUD_SDLDevice.cpp.
References AUD_SoftwareDevice::destroy(), AUD_SoftwareDevice::lock(), and AUD_SoftwareDevice::unlock().
Member Function Documentation
void AUD_SDLDevice::playing (bool playing) [protected, virtual]
This function tells the device, to start or pause playback.
Parameters:
playing True if device should playback.
Implements AUD_SoftwareDevice.
Definition at line 94 of file AUD_SDLDevice.cpp.
The documentation for this class was generated from the following files:
AUD_SDLDevice.h
AUD_SDLDevice.cpp