Blender: screen_ops.c File Reference
screen_ops.c File Reference
screen
#include <math.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_dlrbTree.h"
#include "BLI_utildefines.h"
#include "DNA_armature_types.h"
#include "DNA_lattice_types.h"
#include "DNA_object_types.h"
#include "DNA_curve_types.h"
#include "DNA_scene_types.h"
#include "DNA_meta_types.h"
#include "DNA_mesh_types.h"
#include "DNA_userdef_types.h"
#include "BKE_context.h"
#include "BKE_customdata.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_mesh.h"
#include "BKE_object.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "BKE_tessmesh.h"
#include "BKE_sound.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_util.h"
#include "ED_image.h"
#include "ED_screen.h"
#include "ED_object.h"
#include "ED_armature.h"
#include "ED_screen_types.h"
#include "ED_keyframes_draw.h"
#include "ED_view3d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "wm_window.h"
#include "screen_intern.h"
Classes
struct sActionzoneData
struct sAreaSwapData
struct sAreaMoveData
struct sAreaSplitData
struct RegionMoveData
struct sAreaJoinData
Defines
#define KM_MODAL_CANCEL 1
#define KM_MODAL_APPLY 2
#define KM_MODAL_STEP10 3
#define KM_MODAL_STEP10_OFF 4
#define SPLIT_STARTED 1
#define SPLIT_PROGRESS 2
Typedefs
typedef struct sActionzoneData sActionzoneData
typedef struct sAreaSwapData sAreaSwapData
typedef struct sAreaMoveData sAreaMoveData
typedef struct sAreaSplitData sAreaSplitData
typedef struct RegionMoveData RegionMoveData
typedef struct sAreaJoinData sAreaJoinData
Functions
int ED_operator_regionactive (bContext *C)
int ED_operator_areaactive (bContext *C)
int ED_operator_screenactive (bContext *C)
static int ED_operator_screenactive_norender (bContext *C)
static int screen_active_editable (bContext *C)
int ED_operator_screen_mainwinactive (bContext *C)
int ED_operator_scene_editable (bContext *C)
int ED_operator_objectmode (bContext *C)
static int ed_spacetype_test (bContext *C, int type)
int ED_operator_view3d_active (bContext *C)
int ED_operator_region_view3d_active (bContext *C)
int ED_operator_animview_active (bContext *C)
int ED_operator_timeline_active (bContext *C)
int ED_operator_outliner_active (bContext *C)
int ED_operator_outliner_active_no_editobject (bContext *C)
int ED_operator_file_active (bContext *C)
int ED_operator_action_active (bContext *C)
int ED_operator_buttons_active (bContext *C)
int ED_operator_node_active (bContext *C)
int ED_operator_graphedit_active (bContext *C)
int ED_operator_sequencer_active (bContext *C)
int ED_operator_image_active (bContext *C)
int ED_operator_nla_active (bContext *C)
int ED_operator_logic_active (bContext *C)
int ED_operator_info_active (bContext *C)
int ED_operator_console_active (bContext *C)
int ED_operator_object_active (bContext *C)
int ED_operator_object_active_editable (bContext *C)
int ED_operator_object_active_editable_mesh (bContext *C)
int ED_operator_object_active_editable_font (bContext *C)
int ED_operator_editmesh (bContext *C)
int ED_operator_editmesh_view3d (bContext *C)
int ED_operator_editmesh_region_view3d (bContext *C)
int ED_operator_editarmature (bContext *C)
int ED_operator_posemode (bContext *C)
int ED_operator_uvedit (bContext *C)
int ED_operator_uvmap (bContext *C)
int ED_operator_editsurfcurve (bContext *C)
int ED_operator_editsurfcurve_region_view3d (bContext *C)
int ED_operator_editcurve (bContext *C)
int ED_operator_editcurve_3d (bContext *C)
int ED_operator_editsurf (bContext *C)
int ED_operator_editfont (bContext *C)
int ED_operator_editlattice (bContext *C)
int ED_operator_editmball (bContext *C)
static ScrArea * screen_areahascursor (bScreen *scr, int x, int y)
static int actionzone_area_poll (bContext *C)
AZone * is_in_area_actionzone (ScrArea *sa, int x, int y)
static void actionzone_exit (wmOperator *op)
static void actionzone_apply (bContext *C, wmOperator *op, int type)
static int actionzone_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int actionzone_modal (bContext *C, wmOperator *op, wmEvent *event)
static int actionzone_cancel (bContext *UNUSED(C), wmOperator *op)
static void SCREEN_OT_actionzone (wmOperatorType *ot)
static int area_swap_init (wmOperator *op, wmEvent *event)
static void area_swap_exit (bContext *C, wmOperator *op)
static int area_swap_cancel (bContext *C, wmOperator *op)
static int area_swap_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int area_swap_modal (bContext *C, wmOperator *op, wmEvent *event)
static void SCREEN_OT_area_swap (wmOperatorType *ot)
static int area_dupli_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void SCREEN_OT_area_dupli (wmOperatorType *ot)
static void area_move_set_limits (bScreen *sc, int dir, int *bigger, int *smaller)
static int area_move_init (bContext *C, wmOperator *op)
static void area_move_apply_do (bContext *C, int origval, int delta, int dir, int bigger, int smaller)
static void area_move_apply (bContext *C, wmOperator *op)
static void area_move_exit (bContext *C, wmOperator *op)
static int area_move_exec (bContext *C, wmOperator *op)
static int area_move_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int area_move_cancel (bContext *C, wmOperator *op)
static int area_move_modal (bContext *C, wmOperator *op, wmEvent *event)
static void SCREEN_OT_area_move (wmOperatorType *ot)
static int area_split_menu_init (bContext *C, wmOperator *op)
static int area_split_init (bContext *C, wmOperator *op)
static ScrEdge * area_findsharededge (bScreen *screen, ScrArea *sa, ScrArea *sb)
static int area_split_apply (bContext *C, wmOperator *op)
static void area_split_exit (bContext *C, wmOperator *op)
static int area_split_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int area_split_exec (bContext *C, wmOperator *op)
static int area_split_cancel (bContext *C, wmOperator *op)
static int area_split_modal (bContext *C, wmOperator *op, wmEvent *event)
static void SCREEN_OT_area_split (wmOperatorType *ot)
static int area_max_regionsize (ScrArea *sa, ARegion *scalear, AZEdge edge)
static int region_scale_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int region_scale_get_maxsize (RegionMoveData *rmd)
static void region_scale_validate_size (RegionMoveData *rmd)
static void region_scale_toggle_hidden (bContext *C, RegionMoveData *rmd)
static int region_scale_modal (bContext *C, wmOperator *op, wmEvent *event)
static int region_scale_cancel (bContext *UNUSED(C), wmOperator *op)
static void SCREEN_OT_region_scale (wmOperatorType *ot)
static int frame_offset_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_frame_offset (wmOperatorType *ot)
static int frame_jump_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_frame_jump (wmOperatorType *ot)
static int keyframe_jump_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_keyframe_jump (wmOperatorType *ot)
static int screen_set_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_screen_set (wmOperatorType *ot)
static int screen_full_area_exec (bContext *C, wmOperator *UNUSED(op))
static void SCREEN_OT_screen_full_area (wmOperatorType *ot)
static int area_join_init (bContext *C, wmOperator *op)
static int area_join_apply (bContext *C, wmOperator *op)
static void area_join_exit (bContext *C, wmOperator *op)
static int area_join_exec (bContext *C, wmOperator *op)
static int area_join_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int area_join_cancel (bContext *C, wmOperator *op)
static int area_join_modal (bContext *C, wmOperator *op, wmEvent *event)
static void SCREEN_OT_area_join (wmOperatorType *ot)
static int screen_area_options_invoke (bContext *C, wmOperator *op, wmEvent *event)
static void SCREEN_OT_area_options (wmOperatorType *ot)
static int spacedata_cleanup (bContext *C, wmOperator *op)
static void SCREEN_OT_spacedata_cleanup (wmOperatorType *ot)
static int repeat_last_exec (bContext *C, wmOperator *UNUSED(op))
static void SCREEN_OT_repeat_last (wmOperatorType *ot)
static int repeat_history_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int repeat_history_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_repeat_history (wmOperatorType *ot)
static int redo_last_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static void SCREEN_OT_redo_last (wmOperatorType *ot)
static int region_quadview_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_region_quadview (wmOperatorType *ot)
static int region_flip_exec (bContext *C, wmOperator *UNUSED(op))
static void SCREEN_OT_region_flip (wmOperatorType *ot)
static int header_flip_exec (bContext *C, wmOperator *UNUSED(op))
static void SCREEN_OT_header_flip (wmOperatorType *ot)
static int header_toolbox_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *UNUSED(event))
static void SCREEN_OT_header_toolbox (wmOperatorType *ot)
static int match_area_with_refresh (int spacetype, int refresh)
static int match_region_with_redraws (int spacetype, int regiontype, int redraws)
static int screen_animation_step (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
static void SCREEN_OT_animation_step (wmOperatorType *ot)
int ED_screen_animation_play (bContext *C, int sync, int mode)
static int screen_animation_play_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_animation_play (wmOperatorType *ot)
static int screen_animation_cancel_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_animation_cancel (wmOperatorType *ot)
static int fullscreen_back_exec (bContext *C, wmOperator *op)
static void SCREEN_OT_back_to_previous (struct wmOperatorType *ot)
static int userpref_show_invoke (bContext *C, wmOperator *UNUSED(op), wmEvent *event)
static void SCREEN_OT_userpref_show (struct wmOperatorType *ot)
static int screen_new_exec (bContext *C, wmOperator *UNUSED(op))
static void SCREEN_OT_new (wmOperatorType *ot)
static int screen_delete_exec (bContext *C, wmOperator *UNUSED(op))
static void SCREEN_OT_delete (wmOperatorType *ot)
static int scene_new_exec (bContext *C, wmOperator *op)
static void SCENE_OT_new (wmOperatorType *ot)
static int scene_delete_exec (bContext *C, wmOperator *UNUSED(op))
static void SCENE_OT_delete (wmOperatorType *ot)
void ED_operatortypes_screen (void)
static void keymap_modal_set (wmKeyConfig *keyconf)
static int open_file_drop_poll (bContext *UNUSED(C), wmDrag *drag, wmEvent *UNUSED(event))
static void open_file_drop_copy (wmDrag *drag, wmDropBox *drop)
void ED_keymap_screen (wmKeyConfig *keyconf)
Variables
static EnumPropertyItem prop_direction_items []
Detailed Description
Definition in file screen_ops.c.
Define Documentation
#define KM_MODAL_APPLY 2
Definition at line 84 of file screen_ops.c.
Referenced by area_move_modal(), and keymap_modal_set().
#define KM_MODAL_CANCEL 1
Definition at line 83 of file screen_ops.c.
Referenced by area_move_modal(), and keymap_modal_set().
#define KM_MODAL_STEP10 3
Definition at line 85 of file screen_ops.c.
Referenced by area_move_modal(), and keymap_modal_set().
#define KM_MODAL_STEP10_OFF 4
Definition at line 86 of file screen_ops.c.
Referenced by area_move_modal(), and keymap_modal_set().
#define SPLIT_PROGRESS 2
Definition at line 1141 of file screen_ops.c.
#define SPLIT_STARTED 1
Definition at line 1140 of file screen_ops.c.
Typedef Documentation
typedef struct RegionMoveData RegionMoveData
typedef struct sActionzoneData sActionzoneData
typedef struct sAreaJoinData sAreaJoinData
typedef struct sAreaMoveData sAreaMoveData
typedef struct sAreaSplitData sAreaSplitData
typedef struct sAreaSwapData sAreaSwapData
Function Documentation
static void actionzone_apply (bContext * C, wmOperator * op, int type) [static]
Definition at line 544 of file screen_ops.c.
References AZONE_AREA, CTX_wm_window(), wmOperator::customdata, wmWindow::eventstate, EVT_ACTIONZONE_AREA, EVT_ACTIONZONE_REGION, sActionzoneData::modifier, NULL, wmOperator::ptr, RNA_int_get(), TRUE, and wm_event_add().
Referenced by actionzone_invoke(), and actionzone_modal().
static int actionzone_area_poll (bContext * C) [static]
Definition at line 496 of file screen_ops.c.
References ScrArea::actionzones, BLI_in_rcti(), CTX_wm_area(), CTX_wm_window(), wmWindow::eventstate, ListBase::first, AZone::next, AZone::rect, wmEvent::x, and wmEvent::y.
Referenced by SCREEN_OT_actionzone().
static int actionzone_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 639 of file screen_ops.c.
References actionzone_exit(), and OPERATOR_CANCELLED.
Referenced by SCREEN_OT_actionzone().
static void actionzone_exit (wmOperator * op) [static]
Definition at line 536 of file screen_ops.c.
References wmOperator::customdata, MEM_freeN(), and NULL.
Referenced by actionzone_cancel(), actionzone_invoke(), actionzone_modal(), and area_dupli_invoke().
static int actionzone_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 564 of file screen_ops.c.
References actionzone_apply(), actionzone_exit(), sActionzoneData::az, AZONE_REGION, CTX_wm_area(), wmOperator::customdata, is_in_area_actionzone(), MEM_callocN(), NULL, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, sActionzoneData::sa1, AZone::type, WM_event_add_modal_handler(), sActionzoneData::x, wmEvent::x, sActionzoneData::y, and wmEvent::y.
Referenced by SCREEN_OT_actionzone().
static int actionzone_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 594 of file screen_ops.c.
References ABS, actionzone_apply(), actionzone_exit(), sActionzoneData::az, AZONE_REGION, CTX_wm_screen(), wmOperator::customdata, ESCKEY, sActionzoneData::gesture_dir, if(), LEFTMOUSE, MOUSEMOVE, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, sActionzoneData::sa2, screen_areahascursor(), wmEvent::type, AZone::type, wmEvent::x, sActionzoneData::x, wmEvent::y, and sActionzoneData::y.
Referenced by SCREEN_OT_actionzone().
static int area_dupli_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 786 of file screen_ops.c.
References actionzone_exit(), area_copy_data(), bScreen::areabase, BLI_translate_rcti(), CTX_data_scene(), CTX_wm_area(), CTX_wm_screen(), CTX_wm_window(), ED_area_tag_redraw(), ED_screen_add(), EVT_ACTIONZONE_AREA, ListBase::first, bScreen::full, bScreen::id, NA_EDITED, ID::name, NC_SCREEN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, wmWindow::posx, wmWindow::posy, sActionzoneData::sa1, wmWindow::screen, SCREENNORMAL, ScrArea::totrct, wmEvent::type, WM_event_add_notifier(), and WM_window_open().
Referenced by SCREEN_OT_area_dupli().
static ScrEdge* area_findsharededge (bScreen * screen, ScrArea * sa, ScrArea * sb) [static]
Definition at line 1211 of file screen_ops.c.
References NULL, screen_findedge(), ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_split_apply().
static int area_join_apply (bContext * C, wmOperator * op) [static]
Definition at line 2161 of file screen_ops.c.
References CTX_wm_area(), CTX_wm_area_set(), CTX_wm_region_set(), CTX_wm_screen(), wmOperator::customdata, if(), NULL, sAreaJoinData::sa1, sAreaJoinData::sa2, and screen_area_join().
Referenced by area_join_exec(), and area_join_modal().
static int area_join_cancel (bContext * C, wmOperator * op) [static]
Definition at line 2238 of file screen_ops.c.
References AREA_FLAG_DRAWJOINFROM, AREA_FLAG_DRAWJOINTO, area_join_exit(), wmOperator::customdata, ScrArea::flag, if(), NC_WINDOW, NULL, OPERATOR_CANCELLED, sAreaJoinData::sa1, sAreaJoinData::sa2, and WM_event_add_notifier().
Referenced by area_join_modal(), and SCREEN_OT_area_join().
static int area_join_exec (bContext * C, wmOperator * op) [static]
Definition at line 2191 of file screen_ops.c.
References area_join_apply(), area_join_exit(), area_join_init(), OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by SCREEN_OT_area_join().
static void area_join_exit (bContext * C, wmOperator * op) [static]
Definition at line 2178 of file screen_ops.c.
References CTX_wm_screen(), wmOperator::customdata, MEM_freeN(), NULL, removedouble_scredges(), removenotused_scredges(), and removenotused_scrverts().
Referenced by area_join_cancel(), area_join_exec(), and area_join_modal().
static int area_join_init (bContext * C, wmOperator * op) [static]
Definition at line 2119 of file screen_ops.c.
References AREA_FLAG_DRAWJOINFROM, AREA_FLAG_DRAWJOINTO, CTX_wm_screen(), wmOperator::customdata, ScrArea::flag, MEM_callocN(), NULL, wmOperator::ptr, RNA_int_get(), sAreaJoinData::sa1, sAreaJoinData::sa2, screen_areahascursor(), ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_join_exec(), and area_join_invoke().
static int area_join_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2203 of file screen_ops.c.
References area_join_init(), EVT_ACTIONZONE_AREA, sActionzoneData::modifier, NULL, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_set(), sActionzoneData::sa1, sActionzoneData::sa2, wmEvent::type, WM_event_add_modal_handler(), wmEvent::x, sActionzoneData::x, wmEvent::y, and sActionzoneData::y.
Referenced by SCREEN_OT_area_join().
static int area_join_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2259 of file screen_ops.c.
References AREA_FLAG_DRAWJOINFROM, AREA_FLAG_DRAWJOINTO, area_getorientation(), area_join_apply(), area_join_cancel(), area_join_exit(), CTX_wm_screen(), wmOperator::customdata, ED_area_tag_redraw(), ESCKEY, ScrArea::flag, KM_RELEASE, LEFTMOUSE, MOUSEMOVE, NA_EDITED, NC_SCREEN, NC_WINDOW, NULL, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, sAreaJoinData::sa1, sAreaJoinData::sa2, screen_areahascursor(), wmEvent::type, wmEvent::val, WM_event_add_notifier(), wmEvent::x, and wmEvent::y.
Referenced by SCREEN_OT_area_join().
static int area_max_regionsize (ScrArea * sa, ARegion * scalear, AZEdge edge) [static]
Definition at line 1572 of file screen_ops.c.
References AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, AE_TOP_TO_BOTTOMRIGHT, ARegion::alignment, ListBase::first, ARegion::next, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_ALIGN_TOP, RGN_TYPE_HEADER, ScrArea::totrct, ARegion::winx, ARegion::winy, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by region_scale_invoke().
static void area_move_apply (bContext * C, wmOperator * op) [static]
Definition at line 985 of file screen_ops.c.
References area_move_apply_do(), sAreaMoveData::bigger, wmOperator::customdata, sAreaMoveData::dir, sAreaMoveData::origval, wmOperator::ptr, RNA_int_get(), and sAreaMoveData::smaller.
Referenced by area_move_cancel(), area_move_exec(), and area_move_modal().
static void area_move_apply_do (bContext * C, int origval, int delta, int dir, int bigger, int smaller) [static]
Definition at line 947 of file screen_ops.c.
References bScreen::areabase, AREAGRID, CLAMPIS, CTX_wm_screen(), CTX_wm_window(), ED_area_headersize(), ED_area_tag_redraw(), ListBase::first, ScrVert::flag, NA_EDITED, NC_SCREEN, ScrArea::next, ScrVert::next, NULL, wmWindow::sizex, wmWindow::sizey, ScrArea::v1, ScrArea::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, bScreen::vertbase, WM_event_add_notifier(), vec2s::x, and vec2s::y.
Referenced by area_move_apply(), and area_split_modal().
static int area_move_cancel (bContext * C, wmOperator * op) [static]
Definition at line 1031 of file screen_ops.c.
References area_move_apply(), area_move_exit(), OPERATOR_CANCELLED, wmOperator::ptr, and RNA_int_set().
Referenced by area_move_modal(), and SCREEN_OT_area_move().
static int area_move_exec (bContext * C, wmOperator * op) [static]
Definition at line 1005 of file screen_ops.c.
References area_move_apply(), area_move_exit(), area_move_init(), OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by SCREEN_OT_area_move().
static void area_move_exit (bContext * C, wmOperator * op) [static]
Definition at line 994 of file screen_ops.c.
References CTX_wm_screen(), wmOperator::customdata, MEM_freeN(), NULL, removedouble_scredges(), and removedouble_scrverts().
Referenced by area_move_cancel(), area_move_exec(), and area_move_modal().
static int area_move_init (bContext * C, wmOperator * op) [static]
Definition at line 916 of file screen_ops.c.
References area_move_set_limits(), sAreaMoveData::bigger, CTX_wm_screen(), wmOperator::customdata, sAreaMoveData::dir, MEM_callocN(), NULL, sAreaMoveData::origval, wmOperator::ptr, RNA_int_get(), scredge_is_horizontal(), screen_find_active_scredge(), select_connected_scredge(), sAreaMoveData::smaller, ScrEdge::v1, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by area_move_exec(), and area_move_invoke().
static int area_move_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1017 of file screen_ops.c.
References area_move_init(), OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_set(), WM_event_add_modal_handler(), wmEvent::x, and wmEvent::y.
Referenced by SCREEN_OT_area_move().
static int area_move_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1042 of file screen_ops.c.
References area_move_apply(), area_move_cancel(), area_move_exit(), wmOperator::customdata, sAreaMoveData::dir, EVT_MODAL_MAP, if(), KM_MODAL_APPLY, KM_MODAL_CANCEL, KM_MODAL_STEP10, KM_MODAL_STEP10_OFF, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, wmOperator::ptr, RNA_int_get(), RNA_int_set(), sAreaMoveData::step, wmEvent::type, wmEvent::val, wmEvent::x, and wmEvent::y.
Referenced by SCREEN_OT_area_move().
static void area_move_set_limits (bScreen * sc, int dir, int * bigger, int * smaller) [static]
Definition at line 884 of file screen_ops.c.
References bScreen::areabase, AREAMINX, ED_area_headersize(), ListBase::first, ScrVert::flag, MIN2, ScrArea::next, ScrArea::v1, ScrArea::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by area_move_init(), and area_split_invoke().
static int area_split_apply (bContext * C, wmOperator * op) [static]
Definition at line 1240 of file screen_ops.c.
References area_findsharededge(), area_split(), CTX_wm_screen(), wmOperator::customdata, ED_area_tag_redraw(), ListBase::first, ScrVert::flag, NA_EDITED, sAreaSplitData::narea, NC_SCREEN, sAreaSplitData::nedge, ScrVert::next, NULL, sAreaSplitData::origval, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), sAreaSplitData::sarea, ScrEdge::v1, ScrEdge::v2, ScrVert::vec, bScreen::vertbase, WM_event_add_notifier(), vec2s::x, and vec2s::y.
Referenced by area_split_exec(), area_split_invoke(), and area_split_modal().
static int area_split_cancel (bContext * C, wmOperator * op) [static]
Definition at line 1414 of file screen_ops.c.
References area_split_exit(), CTX_wm_area(), CTX_wm_area_set(), CTX_wm_region_set(), CTX_wm_screen(), wmOperator::customdata, if(), sAreaSplitData::narea, NULL, OPERATOR_CANCELLED, sAreaSplitData::previewmode, sAreaSplitData::sarea, and screen_area_join().
Referenced by area_split_modal(), and SCREEN_OT_area_split().
static int area_split_exec (bContext * C, wmOperator * op) [static]
Definition at line 1401 of file screen_ops.c.
References area_split_apply(), area_split_exit(), area_split_init(), OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by SCREEN_OT_area_split().
static void area_split_exit (bContext * C, wmOperator * op) [static]
Definition at line 1278 of file screen_ops.c.
References AREA_FLAG_DRAWSPLIT_H, AREA_FLAG_DRAWSPLIT_V, CTX_wm_screen(), CTX_wm_window(), wmOperator::customdata, ED_area_tag_redraw(), ScrArea::flag, if(), MEM_freeN(), NA_EDITED, sAreaSplitData::narea, NC_SCREEN, NULL, removedouble_scredges(), removedouble_scrverts(), sAreaSplitData::sarea, WM_cursor_restore(), and WM_event_add_notifier().
Referenced by area_split_cancel(), area_split_exec(), and area_split_modal().
static int area_split_init (bContext * C, wmOperator * op) [static]
Definition at line 1181 of file screen_ops.c.
References AREAMINX, CTX_wm_area(), wmOperator::customdata, ED_area_headersize(), MEM_callocN(), NULL, sAreaSplitData::origmin, sAreaSplitData::origsize, wmOperator::ptr, RNA_enum_get(), sAreaSplitData::sarea, ScrArea::totrct, ScrArea::winx, ScrArea::winy, rcti::xmin, and rcti::ymin.
Referenced by area_split_exec(), and area_split_invoke().
static int area_split_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1302 of file screen_ops.c.
References area_move_set_limits(), area_split_apply(), area_split_init(), area_split_menu_init(), sActionzoneData::az, sAreaSplitData::bigger, CTX_wm_area(), CTX_wm_screen(), wmOperator::customdata, EVT_ACTIONZONE_AREA, sActionzoneData::gesture_dir, if(), sActionzoneData::modifier, NULL, OPERATOR_CANCELLED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, sAreaSplitData::previewmode, wmOperator::ptr, RNA_enum_set(), RNA_float_set(), RNA_int_get(), RNA_struct_property_is_set(), sActionzoneData::sa1, sActionzoneData::sa2, scredge_is_horizontal(), screen_find_active_scredge(), SCREENNORMAL, sAreaSplitData::smaller, wmEvent::type, ScrArea::v1, ScrVert::vec, ScrArea::winx, ScrArea::winy, WM_event_add_modal_handler(), sAreaSplitData::x, vec2s::x, wmEvent::x, sAreaSplitData::y, vec2s::y, and wmEvent::y.
Referenced by SCREEN_OT_area_split().
static int area_split_menu_init (bContext * C, wmOperator * op) [static]
Definition at line 1159 of file screen_ops.c.
References AREA_FLAG_DRAWSPLIT_H, AREA_FLAG_DRAWSPLIT_V, CTX_wm_area(), wmOperator::customdata, ScrArea::flag, MEM_callocN(), wmOperator::ptr, RNA_enum_get(), and sAreaSplitData::sarea.
Referenced by area_split_invoke().
static int area_split_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1434 of file screen_ops.c.
References AREA_FLAG_DRAWSPLIT_H, AREA_FLAG_DRAWSPLIT_V, area_move_apply_do(), area_split_apply(), area_split_cancel(), area_split_exit(), sAreaSplitData::bigger, CTX_wm_screen(), CTX_wm_window(), CURSOR_X_MOVE, CURSOR_Y_MOVE, wmOperator::customdata, sAreaSplitData::delta, bScreen::do_draw, ED_area_tag_redraw(), ESCKEY, ScrArea::flag, if(), KM_PRESS, KM_RELEASE, LEFTMOUSE, MIDDLEMOUSE, MOUSEMOVE, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, sAreaSplitData::origmin, sAreaSplitData::origsize, sAreaSplitData::origval, sAreaSplitData::previewmode, wmOperator::ptr, RIGHTMOUSE, RNA_enum_get(), RNA_enum_set(), RNA_float_set(), sAreaSplitData::sarea, wmWindow::screen, screen_areahascursor(), sAreaSplitData::smaller, TABKEY, ScrArea::totrct, wmEvent::type, wmEvent::val, ScrArea::winx, ScrArea::winy, WM_cursor_set(), wmEvent::x, rcti::xmin, wmEvent::y, and rcti::ymin.
Referenced by SCREEN_OT_area_split().
static int area_swap_cancel (bContext * C, wmOperator * op) [static]
Definition at line 714 of file screen_ops.c.
References area_swap_exit(), and OPERATOR_CANCELLED.
Referenced by area_swap_modal(), and SCREEN_OT_area_swap().
static void area_swap_exit (bContext * C, wmOperator * op) [static]
Definition at line 706 of file screen_ops.c.
References CTX_wm_window(), wmOperator::customdata, MEM_freeN(), NULL, and WM_cursor_restore().
Referenced by area_swap_cancel(), and area_swap_modal().
static int area_swap_init (wmOperator * op, wmEvent * event) [static]
Definition at line 689 of file screen_ops.c.
References wmOperator::customdata, MEM_callocN(), NULL, sActionzoneData::sa1, sAreaSwapData::sa1, sActionzoneData::sa2, and sAreaSwapData::sa2.
Referenced by area_swap_invoke().
static int area_swap_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 720 of file screen_ops.c.
References area_swap_init(), BC_SWAPAREA_CURSOR, CTX_wm_window(), OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, WM_cursor_modal(), and WM_event_add_modal_handler().
Referenced by SCREEN_OT_area_swap().
static int area_swap_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 734 of file screen_ops.c.
References area_swap_cancel(), area_swap_exit(), CTX_wm_screen(), wmOperator::customdata, ED_area_swapspace(), ED_area_tag_redraw(), ESCKEY, KM_RELEASE, LEFTMOUSE, MOUSEMOVE, NA_EDITED, NC_SCREEN, NULL, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, sActionzoneData::sa1, sActionzoneData::sa2, screen_areahascursor(), wmEvent::type, wmEvent::val, WM_event_add_notifier(), wmEvent::x, and wmEvent::y.
Referenced by SCREEN_OT_area_swap().
void ED_keymap_screen (wmKeyConfig * keyconf)
Definition at line 3497 of file screen_ops.c.
References AKEY, COMMAKEY, DOWNARROWKEY, ESCKEY, EVT_ACTIONZONE_AREA, EVT_ACTIONZONE_REGION, F11KEY, F12KEY, F3KEY, F5KEY, F6KEY, F8KEY, FALSE, keymap_modal_set(), KM_ALT, KM_ANY, KM_CTRL, KM_OSKEY, KM_PRESS, KM_SHIFT, LEFTARROWKEY, LEFTMOUSE, MEDIAFIRST, MEDIALAST, MEDIAPLAY, MEDIASTOP, open_file_drop_copy(), open_file_drop_poll(), PADENTER, wmKeyMapItem::ptr, QKEY, RETKEY, RIGHTARROWKEY, RIGHTMOUSE, RKEY, RNA_boolean_set(), RNA_int_set(), SPACEKEY, TIMER0, TRUE, UKEY, UPARROWKEY, WHEELDOWNMOUSE, WHEELUPMOUSE, WM_dropbox_add(), WM_dropboxmap_find(), WM_keymap_add_item(), WM_keymap_find(), WM_keymap_verify_item(), and ZKEY.
Referenced by ED_spacetypes_keymap().
int ED_operator_action_active (bContext * C)
Definition at line 233 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_ACTION.
Referenced by ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_mirror(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), and ACTION_OT_view_selected().
int ED_operator_animview_active (bContext * C)
Definition at line 193 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_space_data(), ED_operator_areaactive(), ELEM5, SPACE_ACTION, SPACE_IPO, SPACE_NLA, SPACE_SEQ, SPACE_TIME, SpaceLink::spacetype, and TRUE.
Referenced by ANIM_OT_previewrange_clear(), ANIM_OT_previewrange_set(), ed_markers_poll_markers_exist(), ed_markers_poll_selected_markers(), and MARKER_OT_add().
int ED_operator_areaactive (bContext * C)
Definition at line 98 of file screen_ops.c.
References CTX_wm_area(), CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by ANIM_OT_keyframe_delete_v3d(), ANIM_OT_keyframe_insert_menu(), ANIM_OT_keying_set_active_set(), delete_orientation_poll(), ED_operator_animview_active(), ed_spacetype_test(), SCREEN_OT_area_dupli(), SCREEN_OT_area_swap(), SCREEN_OT_header_flip(), SCREEN_OT_region_flip(), SCREEN_OT_region_scale(), SCREEN_OT_screen_full_area(), SCRIPT_OT_python_file_run(), TRANSFORM_OT_create_orientation(), and TRANSFORM_OT_snap_type().
int ED_operator_buttons_active (bContext * C)
Definition at line 238 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_BUTS.
Referenced by BUTTONS_OT_toolbox().
int ED_operator_console_active (bContext * C)
Definition at line 285 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_CONSOLE.
Referenced by CONSOLE_OT_clear(), CONSOLE_OT_copy(), CONSOLE_OT_delete(), CONSOLE_OT_history_append(), CONSOLE_OT_history_cycle(), CONSOLE_OT_insert(), CONSOLE_OT_move(), CONSOLE_OT_paste(), CONSOLE_OT_scrollback_append(), and CONSOLE_OT_select_set().
int ED_operator_editarmature (bContext * C)
Definition at line 336 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_ARMATURE, and Object::type.
Referenced by ARMATURE_OT_align(), ARMATURE_OT_armature_layers(), ARMATURE_OT_autoside_names(), ARMATURE_OT_bone_layers(), ARMATURE_OT_bone_primitive_add(), ARMATURE_OT_calculate_roll(), ARMATURE_OT_click_extrude(), ARMATURE_OT_delete(), ARMATURE_OT_duplicate(), ARMATURE_OT_extrude(), ARMATURE_OT_fill(), ARMATURE_OT_flip_names(), ARMATURE_OT_hide(), ARMATURE_OT_merge(), ARMATURE_OT_parent_clear(), ARMATURE_OT_parent_set(), ARMATURE_OT_reveal(), ARMATURE_OT_select_all(), ARMATURE_OT_select_hierarchy(), ARMATURE_OT_select_inverse(), ARMATURE_OT_separate(), ARMATURE_OT_subdivide(), ARMATURE_OT_switch_direction(), armature_select_linked_poll(), ED_keymap_armature(), and pose_armature_layers_showall_poll().
int ED_operator_editcurve (bContext * C)
Definition at line 401 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_CURVE, and Object::type.
Referenced by CURVE_OT_de_select_first(), CURVE_OT_de_select_last(), CURVE_OT_handle_type_set(), CURVE_OT_select_next(), CURVE_OT_select_previous(), CURVE_OT_spline_type_set(), CURVE_OT_tilt_clear(), and CURVE_OT_vertex_add().
int ED_operator_editcurve_3d (bContext * C)
Definition at line 409 of file screen_ops.c.
References CTX_data_edit_object(), CU_3D, Object::data, Curve::editnurb, Curve::flag, NULL, OB_CURVE, and Object::type.
Referenced by TRANSFORM_OT_tilt().
int ED_operator_editfont (bContext * C)
Definition at line 428 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_FONT, and Object::type.
Referenced by ED_keymap_curve(), FONT_OT_case_set(), FONT_OT_case_toggle(), FONT_OT_change_character(), FONT_OT_change_spacing(), FONT_OT_delete(), FONT_OT_file_paste(), FONT_OT_insert_lorem(), FONT_OT_line_break(), FONT_OT_move(), FONT_OT_move_select(), FONT_OT_style_set(), FONT_OT_style_toggle(), FONT_OT_text_copy(), FONT_OT_text_cut(), FONT_OT_text_insert(), and FONT_OT_text_paste().
int ED_operator_editlattice (bContext * C)
Definition at line 436 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_LATTICE, and Object::type.
Referenced by ED_keymap_object(), hook_op_edit_poll(), LATTICE_OT_select_all(), make_regular_poll(), and vertex_parent_set_poll().
int ED_operator_editmball (bContext * C)
Definition at line 444 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_MBALL, and Object::type.
Referenced by ED_keymap_metaball(), MBALL_OT_delete_metaelems(), MBALL_OT_duplicate_metaelems(), MBALL_OT_hide_metaelems(), MBALL_OT_reveal_metaelems(), MBALL_OT_select_all(), and MBALL_OT_select_random_metaelems().
int ED_operator_editmesh (bContext * C)
Definition at line 314 of file screen_ops.c.
References BMEdit_FromObject(), CTX_data_edit_object(), NULL, OB_MESH, and Object::type.
Referenced by ED_keymap_mesh(), ED_operator_editmesh_region_view3d(), ED_operator_editmesh_view3d(), EM_view3d_poll(), hook_op_edit_poll(), MESH_OT_beautify_fill(), MESH_OT_bevel(), MESH_OT_blend_from_shape(), MESH_OT_bridge_edge_loops(), MESH_OT_colors_reverse(), MESH_OT_colors_rotate(), MESH_OT_delete(), MESH_OT_dissolve(), MESH_OT_dissolve_limited(), MESH_OT_dupli_extrude_cursor(), MESH_OT_duplicate(), MESH_OT_edge_collapse(), MESH_OT_edge_collapse_loop(), MESH_OT_edge_face_add(), MESH_OT_edge_rotate(), MESH_OT_edge_split(), MESH_OT_edges_select_sharp(), MESH_OT_extrude_edges_indiv(), MESH_OT_extrude_faces_indiv(), MESH_OT_extrude_region(), MESH_OT_extrude_verts_indiv(), MESH_OT_faces_select_linked_flat(), MESH_OT_faces_shade_flat(), MESH_OT_faces_shade_smooth(), MESH_OT_fill(), MESH_OT_flip_normals(), MESH_OT_hide(), MESH_OT_inset(), MESH_OT_loop_multi_select(), MESH_OT_loop_to_region(), MESH_OT_mark_seam(), MESH_OT_mark_sharp(), MESH_OT_merge(), MESH_OT_navmesh_face_add(), MESH_OT_navmesh_face_copy(), MESH_OT_noise(), MESH_OT_normals_make_consistent(), MESH_OT_quads_convert_to_tris(), MESH_OT_region_to_loop(), MESH_OT_remove_doubles(), MESH_OT_reveal(), MESH_OT_select_all(), MESH_OT_select_axis(), MESH_OT_select_by_number_vertices(), MESH_OT_select_interior_faces(), MESH_OT_select_less(), MESH_OT_select_linked(), MESH_OT_select_linked_pick(), MESH_OT_select_loose_verts(), MESH_OT_select_mirror(), MESH_OT_select_more(), MESH_OT_select_next_loop(), MESH_OT_select_non_manifold(), MESH_OT_select_nth(), MESH_OT_select_random(), MESH_OT_select_similar(), MESH_OT_select_vertex_path(), MESH_OT_separate(), MESH_OT_shape_propagate_to_all(), MESH_OT_solidify(), MESH_OT_sort_faces(), MESH_OT_split(), MESH_OT_subdivide(), MESH_OT_tris_convert_to_quads(), MESH_OT_uvs_reverse(), MESH_OT_uvs_rotate(), MESH_OT_vert_connect(), MESH_OT_vertices_randomize(), MESH_OT_vertices_smooth(), shade_poll(), TRANSFORM_OT_edge_crease(), TRANSFORM_OT_edge_slide(), TRANSFORM_OT_shrink_fatten(), and vertex_parent_set_poll().
int ED_operator_editmesh_region_view3d (bContext * C)
Definition at line 327 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_region_view3d(), and ED_operator_editmesh().
Referenced by edbm_shortest_path_select_poll(), MESH_OT_edgering_select(), MESH_OT_loop_select(), MESH_OT_loopcut(), and MESH_OT_vert_slide().
int ED_operator_editmesh_view3d (bContext * C)
Definition at line 322 of file screen_ops.c.
References ED_operator_editmesh(), and ED_operator_view3d_active().
Referenced by MESH_OT_extrude_repeat(), and MESH_OT_knife_tool().
int ED_operator_editsurf (bContext * C)
Definition at line 420 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, NULL, OB_SURF, and Object::type.
Referenced by CURVE_OT_select_row(), and CURVE_OT_spin().
int ED_operator_editsurfcurve (bContext * C)
Definition at line 384 of file screen_ops.c.
References CTX_data_edit_object(), Object::data, ELEM, NULL, OB_CURVE, OB_SURF, and Object::type.
Referenced by CURVE_OT_cyclic_toggle(), CURVE_OT_delete(), CURVE_OT_duplicate(), CURVE_OT_extrude(), CURVE_OT_hide(), CURVE_OT_make_segment(), CURVE_OT_radius_set(), CURVE_OT_reveal(), CURVE_OT_select_all(), CURVE_OT_select_less(), CURVE_OT_select_linked(), CURVE_OT_select_more(), CURVE_OT_select_nth(), CURVE_OT_select_random(), CURVE_OT_separate(), CURVE_OT_shade_flat(), CURVE_OT_shade_smooth(), CURVE_OT_smooth(), CURVE_OT_smooth_radius(), CURVE_OT_spline_weight_set(), CURVE_OT_subdivide(), CURVE_OT_switch_direction(), ED_keymap_curve(), ED_operator_editsurfcurve_region_view3d(), hook_op_edit_poll(), and vertex_parent_set_poll().
int ED_operator_editsurfcurve_region_view3d (bContext * C)
Definition at line 392 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_region_view3d(), and ED_operator_editsurfcurve().
Referenced by CURVE_OT_select_linked_pick().
int ED_operator_file_active (bContext * C)
Definition at line 228 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_FILE.
Referenced by file_delete_poll(), file_directory_poll(), file_operator_poll(), FILE_OT_bookmark_add(), FILE_OT_bookmark_toggle(), FILE_OT_delete_bookmark(), FILE_OT_directory_new(), FILE_OT_filenum(), FILE_OT_hidedot(), FILE_OT_highlight(), FILE_OT_next(), FILE_OT_parent(), FILE_OT_previous(), FILE_OT_refresh(), FILE_OT_select(), FILE_OT_select_all_toggle(), FILE_OT_select_bookmark(), FILE_OT_select_border(), FILE_OT_smoothscroll(), and file_rename_poll().
int ED_operator_graphedit_active (bContext * C)
Definition at line 254 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_IPO.
Referenced by ANIM_OT_channels_visibility_set(), ANIM_OT_channels_visibility_toggle(), GRAPH_OT_cursor_set(), GRAPH_OT_ghost_curves_clear(), GRAPH_OT_previewrange_set(), GRAPH_OT_properties(), GRAPH_OT_view_all(), and GRAPH_OT_view_selected().
int ED_operator_image_active (bContext * C)
Definition at line 264 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_IMAGE.
Referenced by IMAGE_OT_properties(), IMAGE_OT_scopes(), RENDER_OT_view_cancel(), UV_OT_align(), UV_OT_circle_select(), UV_OT_cursor_set(), UV_OT_select(), UV_OT_select_border(), UV_OT_select_linked(), UV_OT_select_linked_pick(), UV_OT_select_loop(), UV_OT_snap_cursor(), UV_OT_snap_selected(), and UV_OT_tile_set().
int ED_operator_info_active (bContext * C)
Definition at line 279 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_INFO.
Referenced by INFO_OT_report_copy(), INFO_OT_report_delete(), INFO_OT_report_replay(), INFO_OT_select_all_toggle(), INFO_OT_select_border(), and INFO_OT_select_pick().
int ED_operator_logic_active (bContext * C)
Definition at line 274 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_LOGIC.
Referenced by LOGIC_OT_links_cut(), and LOGIC_OT_properties().
int ED_operator_nla_active (bContext * C)
Definition at line 269 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_NLA.
Referenced by NLA_OT_action_sync_length(), NLA_OT_channels_click(), NLA_OT_click_select(), NLA_OT_properties(), NLA_OT_select_leftright(), NLA_OT_view_all(), NLA_OT_view_selected(), nlaop_poll_tweakmode_off(), and nlaop_poll_tweakmode_on().
int ED_operator_node_active (bContext * C)
Definition at line 243 of file screen_ops.c.
References CTX_wm_space_node(), and SpaceNode::edittree.
Referenced by composite_node_active(), NODE_OT_add_file(), NODE_OT_backimage_sample(), NODE_OT_delete(), NODE_OT_delete_reconnect(), NODE_OT_duplicate(), NODE_OT_group_edit(), NODE_OT_group_make(), NODE_OT_group_socket_add(), NODE_OT_group_socket_move_down(), NODE_OT_group_socket_move_up(), NODE_OT_group_socket_remove(), NODE_OT_group_ungroup(), NODE_OT_hide_socket_toggle(), NODE_OT_hide_toggle(), NODE_OT_link(), NODE_OT_link_make(), NODE_OT_links_cut(), NODE_OT_links_detach(), NODE_OT_mute_toggle(), NODE_OT_new_node_tree(), NODE_OT_options_toggle(), NODE_OT_preview_toggle(), NODE_OT_resize(), NODE_OT_select(), NODE_OT_select_all(), NODE_OT_select_border(), NODE_OT_select_linked_from(), NODE_OT_select_linked_to(), NODE_OT_select_same_type(), NODE_OT_select_same_type_next(), NODE_OT_select_same_type_prev(), NODE_OT_show_cyclic_dependencies(), and NODE_OT_view_all().
int ED_operator_object_active (bContext * C)
Definition at line 290 of file screen_ops.c.
References ED_object_active_context(), NULL, OB_RESTRICT_VIEW, and Object::restrictflag.
Referenced by OBJECT_OT_make_links_data(), OBJECT_OT_parent_set(), and OBJECT_OT_proxy_make().
int ED_operator_object_active_editable (bContext * C)
Definition at line 296 of file screen_ops.c.
References ED_object_active_context(), Object::id, ID::lib, NULL, OB_RESTRICT_VIEW, and Object::restrictflag.
Referenced by DPAINT_OT_bake(), DPAINT_OT_output_toggle(), DPAINT_OT_surface_slot_add(), DPAINT_OT_surface_slot_remove(), DPAINT_OT_type_toggle(), LOGIC_OT_actuator_add(), LOGIC_OT_controller_add(), LOGIC_OT_sensor_add(), OBJECT_OT_constraint_add(), OBJECT_OT_constraint_add_with_targets(), OBJECT_OT_constraints_clear(), OBJECT_OT_constraints_copy(), OBJECT_OT_forcefield_toggle(), OBJECT_OT_game_physics_copy(), OBJECT_OT_game_property_clear(), OBJECT_OT_game_property_copy(), OBJECT_OT_game_property_new(), OBJECT_OT_game_property_remove(), OBJECT_OT_logic_bricks_copy(), OBJECT_OT_material_slot_add(), OBJECT_OT_material_slot_assign(), OBJECT_OT_material_slot_remove(), OBJECT_OT_mode_set(), OBJECT_OT_modifier_add(), OBJECT_OT_parent_clear(), OBJECT_OT_parent_no_inverse_set(), OBJECT_OT_particle_system_add(), OBJECT_OT_particle_system_remove(), OBJECT_OT_paths_calculate(), OBJECT_OT_paths_clear(), OBJECT_OT_posemode_toggle(), and shade_poll().
int ED_operator_object_active_editable_font (bContext * C)
Definition at line 308 of file screen_ops.c.
References ED_object_active_context(), Object::id, ID::lib, NULL, OB_FONT, OB_RESTRICT_VIEW, Object::restrictflag, and Object::type.
Referenced by FONT_OT_textbox_add(), and FONT_OT_textbox_remove().
int ED_operator_object_active_editable_mesh (bContext * C)
Definition at line 302 of file screen_ops.c.
References Object::data, ED_object_active_context(), Object::id, ID::lib, NULL, OB_MESH, OB_RESTRICT_VIEW, Object::restrictflag, and Object::type.
Referenced by SCULPT_OT_sculptmode_toggle().
int ED_operator_objectmode (bContext * C)
Definition at line 151 of file screen_ops.c.
References CTX_data_active_object(), CTX_data_edit_object(), CTX_data_scene(), Scene::id, ID::lib, Object::mode, and NULL.
Referenced by GROUP_OT_create(), GROUP_OT_objects_add_active(), GROUP_OT_objects_remove(), GROUP_OT_objects_remove_active(), OBJECT_OT_add(), OBJECT_OT_add_named(), OBJECT_OT_armature_add(), OBJECT_OT_camera_add(), OBJECT_OT_delete(), OBJECT_OT_drop_named_material(), OBJECT_OT_duplicate(), OBJECT_OT_duplicates_make_real(), OBJECT_OT_effector_add(), OBJECT_OT_group_instance_add(), OBJECT_OT_lamp_add(), OBJECT_OT_make_local(), OBJECT_OT_make_single_user(), OBJECT_OT_move_to_layer(), OBJECT_OT_speaker_add(), OBJECT_OT_text_add(), OBJECT_OT_track_clear(), OBJECT_OT_track_set(), and OBJECT_OT_transform_apply().
int ED_operator_outliner_active (bContext * C)
Definition at line 210 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_OUTLINER.
Referenced by OUTLINER_OT_action_set(), OUTLINER_OT_animdata_operation(), OUTLINER_OT_data_operation(), OUTLINER_OT_expanded_toggle(), OUTLINER_OT_group_operation(), OUTLINER_OT_id_operation(), OUTLINER_OT_item_activate(), OUTLINER_OT_item_openclose(), OUTLINER_OT_item_rename(), OUTLINER_OT_object_operation(), OUTLINER_OT_operation(), OUTLINER_OT_parent_clear(), OUTLINER_OT_parent_drop(), OUTLINER_OT_renderability_toggle(), OUTLINER_OT_scroll_page(), OUTLINER_OT_select_border(), OUTLINER_OT_selected_toggle(), OUTLINER_OT_show_active(), OUTLINER_OT_show_hierarchy(), and OUTLINER_OT_show_one_level().
int ED_operator_outliner_active_no_editobject (bContext * C)
Definition at line 215 of file screen_ops.c.
References CTX_data_edit_object(), ED_object_active_context(), ed_spacetype_test(), and SPACE_OUTLINER.
Referenced by OUTLINER_OT_selectability_toggle(), and OUTLINER_OT_visibility_toggle().
int ED_operator_posemode (bContext * C)
Definition at line 344 of file screen_ops.c.
References CTX_data_active_object(), Object::mode, OB_MODE_EDIT, OB_MODE_WEIGHT_PAINT, and object_pose_armature_get().
Referenced by ED_keymap_armature(), pose_armature_layers_showall_poll(), POSE_OT_armature_apply(), POSE_OT_armature_layers(), POSE_OT_autoside_names(), POSE_OT_bone_layers(), POSE_OT_breakdown(), POSE_OT_constraint_add(), POSE_OT_constraint_add_with_targets(), POSE_OT_constraints_clear(), POSE_OT_constraints_copy(), POSE_OT_copy(), POSE_OT_flip_names(), POSE_OT_group_add(), POSE_OT_group_assign(), POSE_OT_group_deselect(), POSE_OT_group_move(), POSE_OT_group_remove(), POSE_OT_group_select(), POSE_OT_group_sort(), POSE_OT_group_unassign(), POSE_OT_hide(), POSE_OT_ik_add(), POSE_OT_ik_clear(), POSE_OT_loc_clear(), POSE_OT_paste(), POSE_OT_paths_calculate(), POSE_OT_paths_clear(), POSE_OT_propagate(), POSE_OT_push(), POSE_OT_quaternions_flip(), POSE_OT_relax(), POSE_OT_reveal(), POSE_OT_rot_clear(), POSE_OT_rotation_mode_set(), POSE_OT_scale_clear(), POSE_OT_select_all(), POSE_OT_select_constraint_target(), POSE_OT_select_flip_active(), POSE_OT_select_grouped(), POSE_OT_select_hierarchy(), POSE_OT_select_parent(), POSE_OT_transforms_clear(), POSE_OT_user_transforms_clear(), POSE_OT_visual_transform_apply(), pose_select_linked_poll(), POSELIB_OT_new(), and POSELIB_OT_pose_add().
int ED_operator_region_view3d_active (bContext * C)
Definition at line 183 of file screen_ops.c.
References CTX_wm_operator_poll_msg_set(), CTX_wm_region_view3d(), FALSE, and TRUE.
Referenced by PAINT_OT_image_from_view(), SCREEN_OT_region_quadview(), VIEW3D_OT_clip_border(), VIEW3D_OT_rotate(), VIEW3D_OT_snap_cursor_to_grid(), VIEW3D_OT_snap_selected_to_grid(), VIEW3D_OT_view_all(), VIEW3D_OT_view_pan(), VIEW3D_OT_view_selected(), VIEW3D_OT_zoom(), VIEW3D_OT_zoom_border(), and view3d_selectable_data().
int ED_operator_regionactive (bContext * C)
Definition at line 90 of file screen_ops.c.
References CTX_wm_region(), CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by gpencil_draw_poll().
int ED_operator_scene_editable (bContext * C)
Definition at line 143 of file screen_ops.c.
References CTX_data_scene(), Scene::id, ID::lib, and NULL.
Referenced by CURVE_OT_primitive_bezier_circle_add(), CURVE_OT_primitive_bezier_curve_add(), CURVE_OT_primitive_nurbs_circle_add(), CURVE_OT_primitive_nurbs_curve_add(), CURVE_OT_primitive_nurbs_path_add(), MESH_OT_primitive_circle_add(), MESH_OT_primitive_cone_add(), MESH_OT_primitive_cube_add(), MESH_OT_primitive_cylinder_add(), MESH_OT_primitive_grid_add(), MESH_OT_primitive_ico_sphere_add(), MESH_OT_primitive_monkey_add(), MESH_OT_primitive_plane_add(), MESH_OT_primitive_uv_sphere_add(), OBJECT_OT_location_clear(), OBJECT_OT_metaball_add(), OBJECT_OT_origin_clear(), OBJECT_OT_origin_set(), OBJECT_OT_rotation_clear(), OBJECT_OT_scale_clear(), OBJECT_OT_visual_transform_apply(), SEQUENCER_OT_effect_strip_add(), SEQUENCER_OT_image_strip_add(), SEQUENCER_OT_movie_strip_add(), SEQUENCER_OT_movieclip_strip_add(), SEQUENCER_OT_scene_strip_add(), SEQUENCER_OT_sound_strip_add(), SURFACE_OT_primitive_nurbs_surface_circle_add(), SURFACE_OT_primitive_nurbs_surface_curve_add(), SURFACE_OT_primitive_nurbs_surface_cylinder_add(), SURFACE_OT_primitive_nurbs_surface_sphere_add(), SURFACE_OT_primitive_nurbs_surface_surface_add(), and SURFACE_OT_primitive_nurbs_surface_torus_add().
int ED_operator_screen_mainwinactive (bContext * C)
Definition at line 135 of file screen_ops.c.
References CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by SCREEN_OT_area_move(), and SCREEN_OT_area_options().
int ED_operator_screenactive (bContext * C)
Definition at line 106 of file screen_ops.c.
References CTX_wm_screen(), CTX_wm_window(), and NULL.
Referenced by ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), join_poll(), join_shapes_poll(), RENDER_OT_opengl(), RENDER_OT_view_show(), screen_active_editable(), SCREEN_OT_animation_cancel(), SCREEN_OT_back_to_previous(), SCREEN_OT_redo_last(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_set(), SCREEN_OT_userpref_show(), TRANSFORM_OT_mirror(), TRANSFORM_OT_push_pull(), TRANSFORM_OT_resize(), TRANSFORM_OT_rotate(), TRANSFORM_OT_shear(), TRANSFORM_OT_tosphere(), TRANSFORM_OT_trackball(), TRANSFORM_OT_transform(), TRANSFORM_OT_translate(), and TRANSFORM_OT_warp().
static int ED_operator_screenactive_norender (bContext * C) [static]
Definition at line 114 of file screen_ops.c.
References CTX_wm_screen(), CTX_wm_window(), G, and NULL.
Referenced by SCREEN_OT_animation_play(), SCREEN_OT_animation_step(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), and SCREEN_OT_keyframe_jump().
int ED_operator_sequencer_active (bContext * C)
Definition at line 259 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_SEQ.
Referenced by sequencer_add_effect_strip_invoke(), sequencer_add_image_strip_invoke(), sequencer_add_movie_strip_invoke(), sequencer_add_movieclip_strip_invoke(), sequencer_add_scene_strip_invoke(), sequencer_add_sound_strip_invoke(), sequencer_cut_invoke(), SEQUENCER_OT_duplicate(), SEQUENCER_OT_paste(), SEQUENCER_OT_properties(), SEQUENCER_OT_rebuild_proxy(), SEQUENCER_OT_select(), SEQUENCER_OT_select_border(), SEQUENCER_OT_select_linked_pick(), SEQUENCER_OT_swap_data(), SEQUENCER_OT_view_all(), SEQUENCER_OT_view_all_preview(), SEQUENCER_OT_view_selected(), SEQUENCER_OT_view_toggle(), SEQUENCER_OT_view_zoom_ratio(), and TRANSFORM_OT_seq_slide().
int ED_operator_timeline_active (bContext * C)
Definition at line 205 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_TIME.
Referenced by TIME_OT_end_frame_set(), TIME_OT_start_frame_set(), and TIME_OT_view_all().
int ED_operator_uvedit (bContext * C)
Definition at line 361 of file screen_ops.c.
References CTX_data_edit_object(), CTX_wm_space_image(), and ED_space_image_show_uvedit().
Referenced by image_view_selected_poll(), UV_OT_average_islands_scale(), UV_OT_hide(), UV_OT_mark_seam(), UV_OT_minimize_stretch(), UV_OT_pack_islands(), UV_OT_pin(), UV_OT_reveal(), UV_OT_seams_from_islands(), UV_OT_select_all(), UV_OT_select_pinned(), UV_OT_stitch(), UV_OT_unlink_selected(), and UV_OT_weld().
int ED_operator_uvmap (bContext * C)
Definition at line 368 of file screen_ops.c.
References BMEditMesh::bm, BMEdit_FromObject(), CTX_data_edit_object(), FALSE, NULL, OB_MESH, BMesh::totface, TRUE, and Object::type.
Referenced by uv_from_view_poll(), UV_OT_cube_project(), UV_OT_cylinder_project(), UV_OT_reset(), UV_OT_sphere_project(), and UV_OT_unwrap().
int ED_operator_view3d_active (bContext * C)
Definition at line 178 of file screen_ops.c.
References ed_spacetype_test(), and SPACE_VIEW3D.
Referenced by armature_select_linked_poll(), ED_operator_editmesh_view3d(), EM_view3d_poll(), OBJECT_OT_hide_render_clear(), OBJECT_OT_hide_render_set(), OBJECT_OT_hide_view_clear(), OBJECT_OT_hide_view_set(), OBJECT_OT_slow_parent_clear(), OBJECT_OT_slow_parent_set(), pose_select_linked_poll(), TRANSFORM_OT_select_orientation(), view3d_camera_active_poll(), view3d_layers_poll(), VIEW3D_OT_background_image_add(), VIEW3D_OT_background_image_remove(), VIEW3D_OT_cursor3d(), VIEW3D_OT_enable_manipulator(), VIEW3D_OT_fly(), VIEW3D_OT_localview(), VIEW3D_OT_manipulator(), VIEW3D_OT_move(), VIEW3D_OT_ndof_orbit(), VIEW3D_OT_ndof_pan(), VIEW3D_OT_properties(), VIEW3D_OT_select(), VIEW3D_OT_smoothview(), VIEW3D_OT_snap_cursor_to_active(), VIEW3D_OT_snap_cursor_to_center(), VIEW3D_OT_snap_cursor_to_selected(), VIEW3D_OT_snap_selected_to_cursor(), VIEW3D_OT_toolshelf(), and VIEW3D_OT_view_center_cursor().
void ED_operatortypes_screen (void)
Definition at line 3403 of file screen_ops.c.
References ED_OT_redo(), ED_OT_undo(), ED_OT_undo_history(), ED_OT_undo_push(), SCENE_OT_delete(), SCENE_OT_new(), SCREEN_OT_actionzone(), SCREEN_OT_animation_cancel(), SCREEN_OT_animation_play(), SCREEN_OT_animation_step(), SCREEN_OT_area_dupli(), SCREEN_OT_area_join(), SCREEN_OT_area_move(), SCREEN_OT_area_options(), SCREEN_OT_area_split(), SCREEN_OT_area_swap(), SCREEN_OT_back_to_previous(), SCREEN_OT_delete(), SCREEN_OT_frame_jump(), SCREEN_OT_frame_offset(), SCREEN_OT_header_flip(), SCREEN_OT_header_toolbox(), SCREEN_OT_keyframe_jump(), SCREEN_OT_new(), SCREEN_OT_redo_last(), SCREEN_OT_region_flip(), SCREEN_OT_region_quadview(), SCREEN_OT_region_scale(), SCREEN_OT_repeat_history(), SCREEN_OT_repeat_last(), SCREEN_OT_screen_full_area(), SCREEN_OT_screen_set(), SCREEN_OT_screencast(), SCREEN_OT_screenshot(), SCREEN_OT_spacedata_cleanup(), SCREEN_OT_userpref_show(), and WM_operatortype_append().
Referenced by ED_spacetypes_init().
int ED_screen_animation_play (bContext * C, int sync, int mode)
Definition at line 3033 of file screen_ops.c.
References bScreen::animtimer, ScreenAnimData::ar, CTX_data_scene(), CTX_wm_region(), CTX_wm_screen(), wmTimer::customdata, ED_screen_animation_timer(), OPERATOR_FINISHED, bScreen::redraws_flag, sound_play_scene(), sound_stop_scene(), and SPACE_TIME.
Referenced by screen_animation_cancel_exec(), screen_animation_play_exec(), screen_render_invoke(), and wm_event_do_handlers().
static int ed_spacetype_test (bContext * C, int type) [static]
Definition at line 169 of file screen_ops.c.
References CTX_wm_space_data(), ED_operator_areaactive(), SpaceLink::spacetype, and AZone::type.
Referenced by ED_operator_action_active(), ED_operator_buttons_active(), ED_operator_console_active(), ED_operator_file_active(), ED_operator_graphedit_active(), ED_operator_image_active(), ED_operator_info_active(), ED_operator_logic_active(), ED_operator_nla_active(), ED_operator_outliner_active(), ED_operator_outliner_active_no_editobject(), ED_operator_sequencer_active(), ED_operator_timeline_active(), and ED_operator_view3d_active().
static int frame_jump_exec (bContext * C, wmOperator * op) [static]
Definition at line 1849 of file screen_ops.c.
References ANIMPLAY_FLAG_USE_NEXT_FRAME, bScreen::animtimer, CFRA, CTX_data_main(), CTX_data_scene(), CTX_wm_screen(), wmTimer::customdata, ScreenAnimData::flag, NC_SCENE, ND_FRAME, ScreenAnimData::nextfra, OPERATOR_FINISHED, PEFRA, PSFRA, wmOperator::ptr, RNA_boolean_get(), sound_seek_scene(), and WM_event_add_notifier().
Referenced by SCREEN_OT_frame_jump().
static int frame_offset_exec (bContext * C, wmOperator * op) [static]
Definition at line 1814 of file screen_ops.c.
References CFRA, CTX_data_main(), CTX_data_scene(), FRAMENUMBER_MIN_CLAMP, NC_SCENE, ND_FRAME, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), sound_seek_scene(), SUBFRA, and WM_event_add_notifier().
Referenced by SCREEN_OT_frame_offset().
static int fullscreen_back_exec (bContext * C, wmOperator * op) [static]
Definition at line 3194 of file screen_ops.c.
References bScreen::areabase, BKE_report(), CTX_wm_screen(), ED_screen_full_restore(), ListBase::first, ScrArea::full, ScrArea::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::reports, and RPT_ERROR.
Referenced by SCREEN_OT_back_to_previous().
static int header_flip_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2716 of file screen_ops.c.
References ARegion::alignment, BKE_area_find_region_type(), CTX_wm_area(), CTX_wm_region(), ED_area_tag_redraw(), NA_EDITED, NC_SCREEN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_ALIGN_TOP, RGN_TYPE_HEADER, and WM_event_add_notifier().
Referenced by SCREEN_OT_header_flip().
static int header_toolbox_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 2765 of file screen_ops.c.
References ARegion::alignment, CTX_wm_area(), CTX_wm_region(), ScrArea::full, OPERATOR_CANCELLED, RGN_ALIGN_TOP, SPACE_FILE, ScrArea::spacetype, uiItemO(), uiItemS(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by SCREEN_OT_header_toolbox().
AZone* is_in_area_actionzone (ScrArea * sa, int x, int y) [read]
Definition at line 513 of file screen_ops.c.
References ScrArea::actionzones, AZONE_AREA, AZONE_REGION, AZONESPOT, BLI_in_rcti(), ListBase::first, AZone::next, NULL, AZone::rect, AZone::type, AZone::x1, and AZone::y1.
Referenced by actionzone_invoke(), ED_screen_area_active(), ED_screen_set_subwinactive(), and screen_cursor_set().
static int keyframe_jump_exec (bContext * C, wmOperator * op) [static]
Definition at line 1902 of file screen_ops.c.
References BKE_report(), BLI_dlrbTree_free(), BLI_dlrbTree_init(), BLI_dlrbTree_linkedlist_sync(), BLI_dlrbTree_search_next(), BLI_dlrbTree_search_prev(), ActKeyColumn::cfra, CFRA, compare_ak_cfraPtr(), CTX_data_active_object(), CTX_data_main(), CTX_data_scene(), NC_SCENE, ND_FRAME, next, NULL, ob_to_keylist(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RPT_INFO, scene_to_keylist(), sound_seek_scene(), and WM_event_add_notifier().
Referenced by SCREEN_OT_keyframe_jump().
static void keymap_modal_set (wmKeyConfig * keyconf) [static]
Definition at line 3454 of file screen_ops.c.
References ESCKEY, KM_ANY, KM_MODAL_APPLY, KM_MODAL_CANCEL, KM_MODAL_STEP10, KM_MODAL_STEP10_OFF, KM_PRESS, KM_RELEASE, LEFTCTRLKEY, LEFTMOUSE, NULL, PADENTER, RETKEY, WM_modalkeymap_add(), WM_modalkeymap_add_item(), and WM_modalkeymap_assign().
Referenced by ED_keymap_screen().
static int match_area_with_refresh (int spacetype, int refresh) [static]
Definition at line 2809 of file screen_ops.c.
References SPACE_TIME.
Referenced by screen_animation_step().
static int match_region_with_redraws (int spacetype, int regiontype, int redraws) [static]
Definition at line 2821 of file screen_ops.c.
References RGN_TYPE_HEADER, RGN_TYPE_PREVIEW, RGN_TYPE_UI, RGN_TYPE_WINDOW, SPACE_ACTION, SPACE_BUTS, SPACE_CLIP, SPACE_IMAGE, SPACE_IPO, SPACE_NLA, SPACE_NODE, SPACE_SEQ, SPACE_TIME, SPACE_VIEW3D, TIME_ALL_3D_WIN, TIME_ALL_ANIM_WIN, TIME_ALL_BUTS_WIN, TIME_ALL_IMAGE_WIN, TIME_CLIPS, TIME_NODES, TIME_REGION, and TIME_SEQ.
Referenced by screen_animation_step().
static void open_file_drop_copy (wmDrag * drag, wmDropBox * drop) [static]
Definition at line 3488 of file screen_ops.c.
References wmDropBox::opcontext, wmDrag::path, wmDropBox::ptr, RNA_string_set(), and WM_OP_EXEC_DEFAULT.
Referenced by ED_keymap_screen().
static int open_file_drop_poll (bContext * UNUSEDC, wmDrag * drag, wmEvent * UNUSEDevent) [static]
Definition at line 3479 of file screen_ops.c.
References wmDrag::icon, wmDrag::type, and WM_DRAG_PATH.
Referenced by ED_keymap_screen().
static int redo_last_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * UNUSEDevent) [static]
Definition at line 2546 of file screen_ops.c.
References OPERATOR_CANCELLED, WM_operator_last_redo(), and WM_operator_redo_popup().
Referenced by SCREEN_OT_redo_last().
static int region_flip_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2678 of file screen_ops.c.
References ARegion::alignment, CTX_wm_area(), CTX_wm_region(), ED_area_tag_redraw(), NA_EDITED, NC_SCREEN, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT, RGN_ALIGN_TOP, and WM_event_add_notifier().
Referenced by SCREEN_OT_region_flip().
static int region_quadview_exec (bContext * C, wmOperator * op) [static]
Definition at line 2572 of file screen_ops.c.
References ARegion::alignment, BKE_area_region_copy(), BKE_area_region_free(), BKE_report(), BLI_addtail(), BLI_remlink(), copy_qt_qt(), CTX_wm_area(), CTX_wm_region(), ED_area_tag_redraw(), ED_region_exit(), ED_view3d_lock(), ListBase::first, RegionView3D::localvd, MEM_freeN(), NA_EDITED, NC_SCREEN, ARegion::next, NULL, OPERATOR_FINISHED, RegionView3D::persp, ScrArea::regionbase, ARegion::regiondata, ARegion::regiontype, wmOperator::reports, RegionView3D::rflag, RGN_ALIGN_QSPLIT, RGN_TYPE_WINDOW, RPT_ERROR, RV3D_CAMOB, RV3D_CLIPPING, RV3D_LOCKED, RV3D_ORTHO, RV3D_VIEW_CAMERA, RV3D_VIEW_FRONT, RV3D_VIEW_RIGHT, RV3D_VIEW_TOP, SPACE_VIEW3D, ScrArea::spacetype, ScrArea::type, RegionView3D::view, RegionView3D::viewlock, RegionView3D::viewquat, and WM_event_add_notifier().
Referenced by SCREEN_OT_region_quadview().
static int region_scale_cancel (bContext * UNUSEDC, wmOperator * op) [static]
Definition at line 1786 of file screen_ops.c.
References wmOperator::customdata, MEM_freeN(), NULL, and OPERATOR_CANCELLED.
Referenced by SCREEN_OT_region_scale().
static int region_scale_get_maxsize (RegionMoveData * rmd) [static]
Definition at line 1667 of file screen_ops.c.
References AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, RegionMoveData::ar, RegionMoveData::edge, HEADERTOP, ScrArea::headertype, RegionMoveData::maxsize, ARegion::regiontype, RGN_TYPE_TOOL_PROPS, RegionMoveData::sa, UI_UNIT_X, UI_UNIT_Y, and ScrArea::winx.
Referenced by region_scale_modal(), and region_scale_validate_size().
static int region_scale_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1610 of file screen_ops.c.
References AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, RegionMoveData::ar, AZone::ar, area_max_regionsize(), RegionMoveData::az, sActionzoneData::az, BKE_report(), CLAMP(), wmOperator::customdata, AZone::edge, RegionMoveData::edge, EVT_ACTIONZONE_REGION, RegionMoveData::maxsize, MEM_callocN(), OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RegionMoveData::origval, RegionMoveData::origx, RegionMoveData::origy, ARegionType::prefsizex, ARegionType::prefsizey, ARegion::regiontype, wmOperator::reports, RGN_TYPE_HEADER, RPT_ERROR, RegionMoveData::sa, sActionzoneData::sa1, ARegion::sizex, ARegion::sizey, ARegion::type, wmEvent::type, and WM_event_add_modal_handler().
Referenced by SCREEN_OT_region_scale().
static int region_scale_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1708 of file screen_ops.c.
References ABS, AE_BOTTOM_TO_TOPLEFT, AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, RegionMoveData::ar, CLAMP(), wmOperator::customdata, ED_area_tag_redraw(), RegionMoveData::edge, ESCKEY, ARegion::flag, KM_RELEASE, LEFTMOUSE, RegionMoveData::maxsize, MEM_freeN(), MOUSEMOVE, NA_EDITED, NC_SCREEN, NULL, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RegionMoveData::origval, RegionMoveData::origx, RegionMoveData::origy, region_scale_get_maxsize(), region_scale_toggle_hidden(), region_scale_validate_size(), RGN_FLAG_HIDDEN, RGN_FLAG_TOO_SMALL, RegionMoveData::sa, ARegion::sizex, ARegion::sizey, wmEvent::type, UI_UNIT_X, UI_UNIT_Y, wmEvent::val, WM_event_add_notifier(), wmEvent::x, and wmEvent::y.
Referenced by SCREEN_OT_region_scale().
static void region_scale_toggle_hidden (bContext * C, RegionMoveData * rmd) [static]
Definition at line 1702 of file screen_ops.c.
References RegionMoveData::ar, ED_region_toggle_hidden(), and region_scale_validate_size().
Referenced by region_scale_modal().
static void region_scale_validate_size (RegionMoveData * rmd) [static]
Definition at line 1684 of file screen_ops.c.
References AE_LEFT_TO_TOPRIGHT, AE_RIGHT_TO_TOPLEFT, RegionMoveData::ar, RegionMoveData::edge, ARegion::flag, region_scale_get_maxsize(), RGN_FLAG_HIDDEN, size(), ARegion::sizex, and ARegion::sizey.
Referenced by region_scale_modal(), and region_scale_toggle_hidden().
static int repeat_history_exec (bContext * C, wmOperator * op) [static]
Definition at line 2512 of file screen_ops.c.
References BLI_addtail(), BLI_findlink(), BLI_remlink(), CTX_wm_manager(), OPERATOR_FINISHED, wmWindowManager::operators, wmOperator::ptr, RNA_int_get(), and WM_operator_repeat().
Referenced by SCREEN_OT_repeat_history().
static int repeat_history_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 2489 of file screen_ops.c.
References BLI_countlist(), CTX_wm_manager(), i, wmOperatorType::idname, ListBase::last, wmOperatorType::name, OPERATOR_CANCELLED, wmWindowManager::operators, wmOperator::prev, wmOperator::type, uiItemIntO(), uiPupMenuBegin(), uiPupMenuEnd(), and uiPupMenuLayout().
Referenced by SCREEN_OT_repeat_history().
static int repeat_last_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2465 of file screen_ops.c.
References CTX_wm_manager(), ListBase::last, OPERATOR_CANCELLED, wmWindowManager::operators, and WM_operator_repeat().
Referenced by SCREEN_OT_repeat_last().
static int scene_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3371 of file screen_ops.c.
References CTX_data_scene(), ED_screen_delete_scene(), G, G_DEBUG, NA_REMOVED, NC_SCENE, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by SCENE_OT_delete().
static int scene_new_exec (bContext * C, wmOperator * op) [static]
Definition at line 3315 of file screen_ops.c.
References add_scene(), copy_scene(), CTX_data_main(), CTX_data_scene(), CTX_wm_screen(), ED_object_single_users(), ED_screen_set_scene(), NC_SCENE, ND_SCENEBROWSE, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SCE_COPY_FULL, SCE_COPY_LINK_DATA, SCE_COPY_NEW, and WM_event_add_notifier().
Referenced by SCENE_OT_new().
static void SCENE_OT_delete (wmOperatorType * ot) [static]
Definition at line 3385 of file screen_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and scene_delete_exec().
Referenced by ED_operatortypes_screen().
static void SCENE_OT_new (wmOperatorType * ot) [static]
Definition at line 3343 of file screen_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::prop, RNA_def_enum(), SCE_COPY_EMPTY, SCE_COPY_FULL, SCE_COPY_LINK_DATA, SCE_COPY_LINK_OB, SCE_COPY_NEW, scene_new_exec(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_screen().
static int screen_active_editable (bContext * C) [static]
Definition at line 123 of file screen_ops.c.
References CTX_wm_screen(), ED_operator_screenactive(), and SCREENNORMAL.
Referenced by SCREEN_OT_area_join(), and SCREEN_OT_area_split().
static int screen_animation_cancel_exec (bContext * C, wmOperator * op) [static]
Definition at line 3093 of file screen_ops.c.
References bScreen::animtimer, RenderData::cfra, CTX_data_scene(), CTX_wm_screen(), wmTimer::customdata, ED_screen_animation_play(), NC_SCENE, ND_FRAME, OPERATOR_PASS_THROUGH, wmOperator::ptr, Scene::r, RNA_boolean_get(), ScreenAnimData::sfra, and WM_event_add_notifier().
Referenced by SCREEN_OT_animation_cancel().
static int screen_animation_play_exec (bContext * C, wmOperator * op) [static]
Definition at line 3062 of file screen_ops.c.
References ED_screen_animation_play(), wmOperator::ptr, RNA_boolean_get(), and RNA_struct_property_is_set().
Referenced by SCREEN_OT_animation_play().
static int screen_animation_step (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 2894 of file screen_ops.c.
References ANIMPLAY_FLAG_JUMPED, ANIMPLAY_FLAG_NO_SYNC, ANIMPLAY_FLAG_REVERSE, ANIMPLAY_FLAG_SYNC, ANIMPLAY_FLAG_USE_NEXT_FRAME, bScreen::animtimer, ScreenAnimData::ar, bScreen::areabase, Scene::audio, AUDIO_SYNC, RenderData::cfra, CTX_data_main(), CTX_data_scene(), CTX_wm_screen(), wmTimer::customdata, wmEvent::customdata, wmTimer::duration, ED_area_tag_refresh(), ED_refresh_viewport_fps(), ED_region_tag_redraw(), ED_update_for_newframe(), RenderData::efra, FALSE, ListBase::first, AudioData::flag, Scene::flag, ScreenAnimData::flag, FPS, ScreenAnimData::last_duration, match_area_with_refresh(), match_region_with_redraws(), ARegion::next, ScrArea::next, ScreenAnimData::nextfra, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, RenderData::pefra, PRVRANGEON, RenderData::psfra, Scene::r, ScreenAnimData::redraws, ScreenAnimData::refresh, ScrArea::regionbase, ARegion::regiontype, SCE_FRAME_DROP, RenderData::sfra, sound_seek_scene(), sound_sync_scene(), ScrArea::spacetype, step(), and wmTimer::timestep.
Referenced by SCREEN_OT_animation_step().
static int screen_area_options_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 2375 of file screen_ops.c.
References CTX_wm_screen(), PointerRNA::data, wmOperatorType::name, NULL, OPERATOR_CANCELLED, RNA_int_set(), screen_find_active_scredge(), wmOperator::type, uiItemFullO(), uiPupMenuBegin(), uiPupMenuEnd(), uiPupMenuLayout(), WM_OP_INVOKE_DEFAULT, WM_operator_properties_create(), wmEvent::x, and wmEvent::y.
Referenced by SCREEN_OT_area_options().
static ScrArea* screen_areahascursor (bScreen * scr, int x, int y) [static]
Definition at line 483 of file screen_ops.c.
References bScreen::areabase, BLI_in_rcti(), ListBase::first, ScrArea::next, NULL, and ScrArea::totrct.
Referenced by actionzone_modal(), area_join_init(), area_join_modal(), area_split_modal(), and area_swap_modal().
static int screen_delete_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3290 of file screen_ops.c.
References CTX_wm_screen(), NC_SCREEN, ND_SCREENDELETE, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by SCREEN_OT_delete().
static int screen_full_area_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 2047 of file screen_ops.c.
References bScreen::areabase, CTX_wm_area(), CTX_wm_screen(), CTX_wm_window(), ED_screen_full_toggle(), ListBase::first, ScrArea::full, ScrArea::next, NULL, and OPERATOR_FINISHED.
Referenced by SCREEN_OT_screen_full_area().
static int screen_new_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3262 of file screen_ops.c.
References CTX_wm_screen(), CTX_wm_window(), ED_screen_duplicate(), NC_SCREEN, ND_SCREENBROWSE, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by SCREEN_OT_new().
static void SCREEN_OT_actionzone (wmOperatorType * ot) [static]
Definition at line 646 of file screen_ops.c.
References actionzone_area_poll(), actionzone_cancel(), actionzone_invoke(), actionzone_modal(), wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_animation_cancel (wmOperatorType * ot) [static]
Definition at line 3117 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), screen_animation_cancel_exec(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_animation_play (wmOperatorType * ot) [static]
Definition at line 3073 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive_norender(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), screen_animation_play_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_animation_step (wmOperatorType * ot) [static]
Definition at line 3016 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive_norender(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and screen_animation_step().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_area_dupli (wmOperatorType * ot) [static]
Definition at line 837 of file screen_ops.c.
References area_dupli_invoke(), wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_area_join (wmOperatorType * ot) [static]
Definition at line 2350 of file screen_ops.c.
References area_join_cancel(), area_join_exec(), area_join_invoke(), area_join_modal(), wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_INTERNAL, wmOperatorType::poll, RNA_def_int(), screen_active_editable(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_area_move (wmOperatorType * ot) [static]
Definition at line 1083 of file screen_ops.c.
References area_move_cancel(), area_move_exec(), area_move_invoke(), area_move_modal(), wmOperatorType::cancel, wmOperatorType::description, ED_operator_screen_mainwinactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_area_options (wmOperatorType * ot) [static]
Definition at line 2409 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screen_mainwinactive(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and screen_area_options_invoke().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_area_split (wmOperatorType * ot) [static]
Definition at line 1535 of file screen_ops.c.
References area_split_cancel(), area_split_exec(), area_split_invoke(), area_split_modal(), wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_enum(), RNA_def_float(), RNA_def_int(), screen_active_editable(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_area_swap (wmOperatorType * ot) [static]
Definition at line 769 of file screen_ops.c.
References area_swap_cancel(), area_swap_invoke(), area_swap_modal(), wmOperatorType::cancel, wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_back_to_previous (struct wmOperatorType * ot) [static]
Definition at line 3213 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, fullscreen_back_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_delete (wmOperatorType * ot) [static]
Definition at line 3299 of file screen_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and screen_delete_exec().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_frame_jump (wmOperatorType * ot) [static]
Definition at line 1883 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive_norender(), wmOperatorType::exec, wmOperatorType::flag, frame_jump_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_frame_offset (wmOperatorType * ot) [static]
Definition at line 1833 of file screen_ops.c.
References ED_operator_screenactive_norender(), wmOperatorType::exec, wmOperatorType::flag, frame_offset_exec(), wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_header_flip (wmOperatorType * ot) [static]
Definition at line 2750 of file screen_ops.c.
References ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, header_flip_exec(), wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_header_toolbox (wmOperatorType * ot) [static]
Definition at line 2796 of file screen_ops.c.
References wmOperatorType::description, header_toolbox_invoke(), wmOperatorType::idname, wmOperatorType::invoke, and wmOperatorType::name.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_keyframe_jump (wmOperatorType * ot) [static]
Definition at line 1966 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive_norender(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, keyframe_jump_exec(), wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_new (wmOperatorType * ot) [static]
Definition at line 3273 of file screen_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, screen_new_exec(), and WM_operator_winactive().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_redo_last (wmOperatorType * ot) [static]
Definition at line 2556 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and redo_last_invoke().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_region_flip (wmOperatorType * ot) [static]
Definition at line 2701 of file screen_ops.c.
References ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and region_flip_exec().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_region_quadview (wmOperatorType * ot) [static]
Definition at line 2659 of file screen_ops.c.
References wmOperatorType::description, ED_operator_region_view3d_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and region_quadview_exec().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_region_scale (wmOperatorType * ot) [static]
Definition at line 1794 of file screen_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, region_scale_cancel(), region_scale_invoke(), and region_scale_modal().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_repeat_history (wmOperatorType * ot) [static]
Definition at line 2528 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, repeat_history_exec(), repeat_history_invoke(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_repeat_last (wmOperatorType * ot) [static]
Definition at line 2475 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and repeat_last_exec().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_screen_full_area (wmOperatorType * ot) [static]
Definition at line 2064 of file screen_ops.c.
References wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and screen_full_area_exec().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_screen_set (wmOperatorType * ot) [static]
Definition at line 2030 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), screen_set_exec(), and wmOperatorType::srna.
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_spacedata_cleanup (wmOperatorType * ot) [static]
Definition at line 2450 of file screen_ops.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, spacedata_cleanup(), and WM_operator_winactive().
Referenced by ED_operatortypes_screen().
static void SCREEN_OT_userpref_show (struct wmOperatorType * ot) [static]
Definition at line 3248 of file screen_ops.c.
References wmOperatorType::description, ED_operator_screenactive(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and userpref_show_invoke().
Referenced by ED_operatortypes_screen().
static int screen_set_exec (bContext * C, wmOperator * op) [static]
Definition at line 1985 of file screen_ops.c.
References BLI_countlist(), CTX_data_main(), CTX_wm_area(), CTX_wm_screen(), ED_screen_full_restore(), ED_screen_set(), ListBase::first, ScrArea::full, bScreen::full, bScreen::id, ListBase::last, ID::next, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, ID::prev, wmOperator::ptr, RNA_int_get(), Main::screen, bScreen::temp, and bScreen::winid.
Referenced by SCREEN_OT_screen_set().
static int spacedata_cleanup (bContext * C, wmOperator * op) [static]
Definition at line 2426 of file screen_ops.c.
References bScreen::areabase, BKE_reportf(), BKE_spacedata_freelist(), BLI_addtail(), BLI_countlist(), BLI_remlink(), CTX_data_main(), ListBase::first, bScreen::id, ListBase::last, ScrArea::next, ID::next, OPERATOR_FINISHED, wmOperator::reports, RPT_INFO, Main::screen, and ScrArea::spacedata.
Referenced by SCREEN_OT_spacedata_cleanup().
static int userpref_show_invoke (bContext * C, wmOperator * UNUSEDop, wmEvent * event) [static]
Definition at line 3227 of file screen_ops.c.
References CTX_wm_window(), OPERATOR_FINISHED, wmWindow::posx, wmWindow::posy, WM_window_open_temp(), WM_WINDOW_USERPREFS, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by SCREEN_OT_userpref_show().
Variable Documentation
EnumPropertyItem prop_direction_items[] [static]
Initial value:
 {
{'h', "HORIZONTAL", 0, "Horizontal", ""},
{'v', "VERTICAL", 0, "Vertical", ""},
{0, NULL, 0, NULL, NULL}}
Definition at line 1530 of file screen_ops.c.
Referenced by rna_def_constraint_actuator(), and rna_def_modifier_displace().