Blender: callbacks.c File Reference
callbacks.c File Reference
#include "BLI_utildefines.h"
#include "BLI_listbase.h"
#include "BLI_callbacks.h"
#include "MEM_guardedalloc.h"
Functions
void BLI_exec_cb (struct Main *main, struct ID *self, eCbEvent evt)
void BLI_add_cb (bCallbackFuncStore *funcstore, eCbEvent evt)
void BLI_cb_init (void)
void BLI_cb_finalize (void)
Variables
static ListBase callback_slots [BLI_CB_EVT_TOT] = {{NULL}}
Function Documentation
void BLI_add_cb (bCallbackFuncStore * funcstore, eCbEvent evt)
Definition at line 41 of file callbacks.c.
References BLI_addtail().
Referenced by BPY_app_handlers_struct().
void BLI_cb_finalize (void)
Definition at line 53 of file callbacks.c.
References bCallbackFuncStore::alloc, BLI_CB_EVT_TOT, BLI_remlink(), ListBase::first, MEM_freeN(), and bCallbackFuncStore::next.
Referenced by free_blender().
void BLI_cb_init (void)
Definition at line 47 of file callbacks.c.
Referenced by main().
void BLI_exec_cb (struct Main * main, struct ID * self, eCbEvent evt)
Definition at line 31 of file callbacks.c.
References bCallbackFuncStore::arg, ListBase::first, bCallbackFuncStore::func, and bCallbackFuncStore::next.
Referenced by do_write_image_or_movie(), RE_BlenderAnim(), RE_BlenderFrame(), scene_update_for_newframe(), scene_update_tagged(), stats_background(), WM_read_file(), and WM_write_file().
Variable Documentation
ListBase callback_slots[BLI_CB_EVT_TOT] = {{NULL}} [static]
Definition at line 29 of file callbacks.c.