Blender: KX_CameraIpoSGController Class Reference
KX_CameraIpoSGController Class Reference
#include <KX_CameraIpoSGController.h>
Public Member Functions
KX_CameraIpoSGController ()
~KX_CameraIpoSGController ()
SG_Controller * GetReplica (class SG_Node *destnode)
bool Update (double time)
void SetOption (int option, int value)
void SetSimulatedTime (double time)
void SetModifyLens (bool modify)
void SetModifyClipEnd (bool modify)
void SetModifyClipStart (bool modify)
void AddInterpolator (KX_IInterpolator *interp)
Public Attributes
MT_Scalar m_lens
MT_Scalar m_clipstart
MT_Scalar m_clipend
Detailed Description
Definition at line 42 of file KX_CameraIpoSGController.h.
Constructor & Destructor Documentation
KX_CameraIpoSGController::KX_CameraIpoSGController () [inline]
Definition at line 58 of file KX_CameraIpoSGController.h.
Referenced by GetReplica().
KX_CameraIpoSGController::~KX_CameraIpoSGController ()
Definition at line 109 of file KX_CameraIpoSGController.cpp.
References i.
Member Function Documentation
void KX_CameraIpoSGController::AddInterpolator (KX_IInterpolator * interp)
Definition at line 75 of file KX_CameraIpoSGController.cpp.
Referenced by BL_CreateCameraIPO(), and GetReplica().
SG_Controller * KX_CameraIpoSGController::GetReplica (class SG_Node * destnode) [virtual]
Implements SG_Controller.
Definition at line 80 of file KX_CameraIpoSGController.cpp.
References AddInterpolator(), SG_Controller::ClearObject(), i, KX_CameraIpoSGController(), and KX_ScalarInterpolator::SetNewTarget().
void KX_CameraIpoSGController::SetModifyClipEnd (bool modify) [inline]
Definition at line 83 of file KX_CameraIpoSGController.h.
Referenced by BL_CreateCameraIPO().
void KX_CameraIpoSGController::SetModifyClipStart (bool modify) [inline]
Definition at line 86 of file KX_CameraIpoSGController.h.
Referenced by BL_CreateCameraIPO().
void KX_CameraIpoSGController::SetModifyLens (bool modify) [inline]
Definition at line 80 of file KX_CameraIpoSGController.h.
Referenced by BL_CreateCameraIPO().
void KX_CameraIpoSGController::SetOption (int option, int value) [virtual]
Hacky way of passing options to specific controllers
Parameters:
option An integer identifying the option.
value The value of this option.
Attention:
This has been placed here to give sca-elements
some control over the controllers. This is
necessary because the identity of the controller
is lost on the way here.
Implements SG_Controller.
Definition at line 120 of file KX_CameraIpoSGController.cpp.
void KX_CameraIpoSGController::SetSimulatedTime (double time) [inline, virtual]
Implements SG_Controller.
Definition at line 76 of file KX_CameraIpoSGController.h.
bool KX_CameraIpoSGController::Update (double time) [virtual]
Implements SG_Controller.
Definition at line 44 of file KX_CameraIpoSGController.cpp.
References KX_Camera::GetCameraData(), SG_IObject::GetSGClientObject(), i, KX_Camera::InvalidateProjectionMatrix(), m_clipend, RAS_CameraData::m_clipend, RAS_CameraData::m_clipstart, m_clipstart, RAS_CameraData::m_lens, m_lens, and SG_Controller::m_pObject.
Member Data Documentation
MT_Scalar KX_CameraIpoSGController::m_clipend
Definition at line 47 of file KX_CameraIpoSGController.h.
Referenced by BL_CreateCameraIPO(), and Update().
MT_Scalar KX_CameraIpoSGController::m_clipstart
Definition at line 46 of file KX_CameraIpoSGController.h.
Referenced by BL_CreateCameraIPO(), and Update().
MT_Scalar KX_CameraIpoSGController::m_lens
Definition at line 45 of file KX_CameraIpoSGController.h.
Referenced by BL_CreateCameraIPO(), and Update().
The documentation for this class was generated from the following files:
KX_CameraIpoSGController.h
KX_CameraIpoSGController.cpp