Blender: node_shader_tex_coord.c File Reference
node_shader_tex_coord.c File Reference
#include "../node_shader_util.h"
#include "DNA_customdata_types.h"
Functions
static int node_shader_gpu_tex_coord (GPUMaterial *mat, bNode *UNUSED(node), GPUNodeStack *in, GPUNodeStack *out)
void register_node_type_sh_tex_coord (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate sh_node_tex_coord_out []
Function Documentation
static int node_shader_gpu_tex_coord (GPUMaterial * mat, bNode * UNUSEDnode, GPUNodeStack * in, GPUNodeStack * out) [static]
Definition at line 44 of file node_shader_tex_coord.c.
References CD_MTFACE, CD_ORCO, GPU_attribute(), GPU_builtin(), GPU_INVERSE_VIEW_MATRIX, GPU_stack_link(), GPU_VIEW_NORMAL, and GPU_VIEW_POSITION.
Referenced by register_node_type_sh_tex_coord().
void register_node_type_sh_tex_coord (bNodeTreeType * ttype)
Definition at line 55 of file node_shader_tex_coord.c.
References NODE_CLASS_INPUT, NODE_NEW_SHADING, node_shader_gpu_tex_coord(), node_type_base(), node_type_compatibility(), node_type_exec(), node_type_gpu(), node_type_init(), node_type_size(), node_type_socket_templates(), node_type_storage(), nodeRegisterType(), NULL, and SH_NODE_TEX_COORD.
Referenced by registerShaderNodes().
Variable Documentation
bNodeSocketTemplate sh_node_tex_coord_out[] [static]
Initial value:
 {
    {   SOCK_VECTOR, 0, "Generated",        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "UV",               0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Object",           0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Camera",           0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Window",           0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_VECTOR, 0, "Reflection",       0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 34 of file node_shader_tex_coord.c.