Blender: BOP_Edge Class Reference
BOP_Edge Class Reference
#include <BOP_Edge.h>
Public Member Functions
BOP_Edge (BOP_Index v1, BOP_Index v2)
BOP_Index getVertex1 ()
BOP_Index getVertex2 ()
void replaceVertexIndex (BOP_Index oldIndex, BOP_Index newIndex)
BOP_Index getFace (unsigned int i)
unsigned int getNumFaces ()
BOP_Indexs & getFaces ()
void addFace (BOP_Index face)
bool removeFace (BOP_Index i)
bool getUsed ()
void setUsed (bool setting)
Detailed Description
Definition at line 39 of file BOP_Edge.h.
Constructor & Destructor Documentation
BOP_Edge::BOP_Edge (BOP_Index v1, BOP_Index v2)
Constructs a new edge.
Parameters:
v1 vertex index
v2 vertex index
Definition at line 40 of file BOP_Edge.cpp.
Member Function Documentation
void BOP_Edge::addFace (BOP_Index i)
Adds a new face index to this edge.
Parameters:
i face index
Definition at line 50 of file BOP_Edge.cpp.
Referenced by BOP_Mesh::addFace(), and BOP_Mesh::replaceVertexIndex().
BOP_Index BOP_Edge::getFace (unsigned int i) [inline]
Definition at line 55 of file BOP_Edge.h.
References i.
BOP_Indexs& BOP_Edge::getFaces () [inline]
Definition at line 57 of file BOP_Edge.h.
Referenced by BOP_getOppositeFace(), clean_nonmanifold(), deleteFace(), BOP_Mesh::isClosedMesh(), removeBrokenFaces(), and BOP_Mesh::replaceVertexIndex().
unsigned int BOP_Edge::getNumFaces () [inline]
Definition at line 56 of file BOP_Edge.h.
bool BOP_Edge::getUsed () [inline]
Definition at line 61 of file BOP_Edge.h.
BOP_Index BOP_Edge::getVertex1 () [inline]
Definition at line 52 of file BOP_Edge.h.
Referenced by clean_nonmanifold(), deleteFace(), BOP_Mesh::replaceVertexIndex(), and triangulate().
BOP_Index BOP_Edge::getVertex2 () [inline]
Definition at line 53 of file BOP_Edge.h.
Referenced by clean_nonmanifold(), deleteFace(), BOP_Mesh::replaceVertexIndex(), and triangulate().
bool BOP_Edge::removeFace (BOP_Index i)
Returns if this edge contains the specified face index.
Parameters:
i face index
Returns:
true if this edge contains the specified face index, false otherwise
Definition at line 90 of file BOP_Edge.cpp.
References i.
Referenced by deleteFace().
void BOP_Edge::replaceVertexIndex (BOP_Index oldIndex, BOP_Index newIndex)
Replaces an edge vertex index.
Parameters:
oldIndex old vertex index
newIndex new vertex index
Definition at line 77 of file BOP_Edge.cpp.
Referenced by BOP_Mesh::replaceVertexIndex().
void BOP_Edge::setUsed (bool setting) [inline]
Definition at line 62 of file BOP_Edge.h.
The documentation for this class was generated from the following files:
BOP_Edge.h
BOP_Edge.cpp