Blender: action_intern.h File Reference
action_intern.h File Reference
action space
Enumerations
enum { ACTKEYS_LRSEL_TEST = 0, ACTKEYS_LRSEL_LEFT, ACTKEYS_LRSEL_RIGHT }
enum { ACTKEYS_COLUMNSEL_KEYS = 0, ACTKEYS_COLUMNSEL_CFRA, ACTKEYS_COLUMNSEL_MARKERS_COLUMN, ACTKEYS_COLUMNSEL_MARKERS_BETWEEN }
enum { ACTKEYS_SNAP_CFRA = 1, ACTKEYS_SNAP_NEAREST_FRAME, ACTKEYS_SNAP_NEAREST_SECOND, ACTKEYS_SNAP_NEAREST_MARKER }
enum { ACTKEYS_MIRROR_CFRA = 1, ACTKEYS_MIRROR_YAXIS, ACTKEYS_MIRROR_XAXIS, ACTKEYS_MIRROR_MARKER }
Functions
void draw_channel_names (struct bContext *C, struct bAnimContext *ac, struct ARegion *ar)
void draw_channel_strips (struct bAnimContext *ac, struct SpaceAction *saction, struct ARegion *ar)
void ACTION_OT_select_all_toggle (struct wmOperatorType *ot)
void ACTION_OT_select_border (struct wmOperatorType *ot)
void ACTION_OT_select_column (struct wmOperatorType *ot)
void ACTION_OT_select_linked (struct wmOperatorType *ot)
void ACTION_OT_select_more (struct wmOperatorType *ot)
void ACTION_OT_select_less (struct wmOperatorType *ot)
void ACTION_OT_select_leftright (struct wmOperatorType *ot)
void ACTION_OT_clickselect (struct wmOperatorType *ot)
void ACTION_OT_previewrange_set (struct wmOperatorType *ot)
void ACTION_OT_view_all (struct wmOperatorType *ot)
void ACTION_OT_view_selected (struct wmOperatorType *ot)
void ACTION_OT_copy (struct wmOperatorType *ot)
void ACTION_OT_paste (struct wmOperatorType *ot)
void ACTION_OT_keyframe_insert (struct wmOperatorType *ot)
void ACTION_OT_duplicate (struct wmOperatorType *ot)
void ACTION_OT_delete (struct wmOperatorType *ot)
void ACTION_OT_clean (struct wmOperatorType *ot)
void ACTION_OT_sample (struct wmOperatorType *ot)
void ACTION_OT_keyframe_type (struct wmOperatorType *ot)
void ACTION_OT_handle_type (struct wmOperatorType *ot)
void ACTION_OT_interpolation_type (struct wmOperatorType *ot)
void ACTION_OT_extrapolation_type (struct wmOperatorType *ot)
void ACTION_OT_frame_jump (struct wmOperatorType *ot)
void ACTION_OT_snap (struct wmOperatorType *ot)
void ACTION_OT_mirror (struct wmOperatorType *ot)
void ACTION_OT_new (struct wmOperatorType *ot)
void ACTION_OT_markers_make_local (struct wmOperatorType *ot)
void action_operatortypes (void)
void action_keymap (struct wmKeyConfig *keyconf)
Variables
enum { ... } eActKeys_LeftRightSelect_Mode
enum { ... } eActKeys_ColumnSelect_Mode
enum { ... } eActKeys_Snap_Mode
enum { ... } eActKeys_Mirror_Mode
Detailed Description
Definition in file action_intern.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
ACTKEYS_LRSEL_TEST
ACTKEYS_LRSEL_LEFT
ACTKEYS_LRSEL_RIGHT
Definition at line 63 of file action_intern.h.
anonymous enum
Enumerator:
ACTKEYS_COLUMNSEL_KEYS
ACTKEYS_COLUMNSEL_CFRA
ACTKEYS_COLUMNSEL_MARKERS_COLUMN
ACTKEYS_COLUMNSEL_MARKERS_BETWEEN
Definition at line 70 of file action_intern.h.
anonymous enum
Enumerator:
ACTKEYS_SNAP_CFRA
ACTKEYS_SNAP_NEAREST_FRAME
ACTKEYS_SNAP_NEAREST_SECOND
ACTKEYS_SNAP_NEAREST_MARKER
Definition at line 110 of file action_intern.h.
anonymous enum
Enumerator:
ACTKEYS_MIRROR_CFRA
ACTKEYS_MIRROR_YAXIS
ACTKEYS_MIRROR_XAXIS
ACTKEYS_MIRROR_MARKER
Definition at line 120 of file action_intern.h.
Function Documentation
void action_keymap (struct wmKeyConfig * keyconf)
Definition at line 217 of file action_ops.c.
References action_keymap_keyframes(), SPACE_ACTION, and WM_keymap_find().
Referenced by ED_spacetype_action().
void action_operatortypes (void)
Definition at line 54 of file action_ops.c.
References ACTION_OT_clean(), ACTION_OT_clickselect(), ACTION_OT_copy(), ACTION_OT_delete(), ACTION_OT_duplicate(), ACTION_OT_extrapolation_type(), ACTION_OT_frame_jump(), ACTION_OT_handle_type(), ACTION_OT_interpolation_type(), ACTION_OT_keyframe_insert(), ACTION_OT_keyframe_type(), ACTION_OT_markers_make_local(), ACTION_OT_mirror(), ACTION_OT_new(), ACTION_OT_paste(), ACTION_OT_previewrange_set(), ACTION_OT_sample(), ACTION_OT_select_all_toggle(), ACTION_OT_select_border(), ACTION_OT_select_column(), ACTION_OT_select_leftright(), ACTION_OT_select_less(), ACTION_OT_select_linked(), ACTION_OT_select_more(), ACTION_OT_snap(), ACTION_OT_view_all(), ACTION_OT_view_selected(), and WM_operatortype_append().
Referenced by ED_spacetype_action().
void ACTION_OT_clean (struct wmOperatorType * ot)
Definition at line 854 of file action_edit.c.
References actkeys_clean_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_float(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_clickselect (struct wmOperatorType * ot)
Definition at line 1177 of file action_select.c.
References actkeys_clickselect_invoke(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_copy (struct wmOperatorType * ot)
Definition at line 487 of file action_edit.c.
References actkeys_copy_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_delete (struct wmOperatorType * ot)
Definition at line 790 of file action_edit.c.
References actkeys_delete_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by action_operatortypes().
void ACTION_OT_duplicate (struct wmOperatorType * ot)
Definition at line 715 of file action_edit.c.
References actkeys_duplicate_exec(), actkeys_duplicate_invoke(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_extrapolation_type (struct wmOperatorType * ot)
Definition at line 1028 of file action_edit.c.
References actkeys_expo_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_frame_jump (struct wmOperatorType * ot)
Definition at line 1318 of file action_edit.c.
References actkeys_framejump_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_handle_type (struct wmOperatorType * ot)
Definition at line 1179 of file action_edit.c.
References actkeys_handletype_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, keyframe_handle_type_items, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_interpolation_type (struct wmOperatorType * ot)
Definition at line 1099 of file action_edit.c.
References actkeys_ipo_exec(), beztriple_interpolation_mode_items, wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_keyframe_insert (struct wmOperatorType * ot)
Definition at line 639 of file action_edit.c.
References actkeys_insertkey_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_keyframe_type (struct wmOperatorType * ot)
Definition at line 1250 of file action_edit.c.
References actkeys_keytype_exec(), beztriple_keyframe_type_items, wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_markers_make_local (struct wmOperatorType * ot)
Definition at line 207 of file action_edit.c.
References act_markers_make_local_exec(), act_markers_make_local_poll(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_mirror (struct wmOperatorType * ot)
Definition at line 1532 of file action_edit.c.
References actkeys_mirror_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_new (struct wmOperatorType * ot)
Definition at line 124 of file action_edit.c.
References act_new_exec(), wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by action_operatortypes().
void ACTION_OT_paste (struct wmOperatorType * ot)
Definition at line 538 of file action_edit.c.
References actkeys_paste_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, keyframe_paste_merge_items, KEYFRAME_PASTE_MERGE_MIX, KEYFRAME_PASTE_OFFSET_CFRA_START, keyframe_paste_offset_items, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_previewrange_set (struct wmOperatorType * ot)
Definition at line 322 of file action_edit.c.
References actkeys_previewrange_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_sample (struct wmOperatorType * ot)
Definition at line 918 of file action_edit.c.
References actkeys_sample_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_select_all_toggle (struct wmOperatorType * ot)
Definition at line 161 of file action_select.c.
References actkeys_deselectall_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_select_border (struct wmOperatorType * ot)
Definition at line 319 of file action_select.c.
References actkeys_borderselect_exec(), wmOperatorType::cancel, wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), wmOperatorType::srna, TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by action_operatortypes().
void ACTION_OT_select_column (struct wmOperatorType * ot)
Definition at line 527 of file action_select.c.
References actkeys_columnselect_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_select_leftright (struct wmOperatorType * ot)
Definition at line 863 of file action_select.c.
References ACTKEYS_LRSEL_TEST, actkeys_select_leftright_exec(), actkeys_select_leftright_invoke(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by action_operatortypes().
void ACTION_OT_select_less (struct wmOperatorType * ot)
Definition at line 696 of file action_select.c.
References actkeys_select_less_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_select_linked (struct wmOperatorType * ot)
Definition at line 585 of file action_select.c.
References actkeys_select_linked_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_select_more (struct wmOperatorType * ot)
Definition at line 662 of file action_select.c.
References actkeys_select_more_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_snap (struct wmOperatorType * ot)
Definition at line 1418 of file action_edit.c.
References actkeys_snap_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by action_operatortypes().
void ACTION_OT_view_all (struct wmOperatorType * ot)
Definition at line 384 of file action_edit.c.
References actkeys_viewall_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void ACTION_OT_view_selected (struct wmOperatorType * ot)
Definition at line 399 of file action_edit.c.
References actkeys_viewsel_exec(), wmOperatorType::description, ED_operator_action_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by action_operatortypes().
void draw_channel_names (struct bContext * C, struct bAnimContext * ac, struct ARegion * ar)
Definition at line 70 of file action_draw.c.
References ACHANNEL_FIRST, ACHANNEL_HEIGHT, ACHANNEL_HEIGHT_HALF, ACHANNEL_STEP, ANIM_animdata_filter(), ANIM_channel_draw(), ANIM_channel_draw_widgets(), ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, BLI_freelistN(), View2D::cur, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, IN_RANGE, View2D::mask, bAnimListElem::next, NULL, bAnimContext::sa, View2D::tot, UI_EMBOSS, UI_view2d_sync(), uiBeginBlock(), uiDrawBlock(), uiEndBlock(), ARegion::v2d, V2D_LOCK_COPY, rcti::ymax, rctf::ymax, rcti::ymin, and rctf::ymin.
Referenced by action_channel_area_draw().
void draw_channel_strips (struct bAnimContext * ac, struct SpaceAction * saction, struct ARegion * ar)
Definition at line 159 of file action_draw.c.
References ACHANNEL_HEIGHT, ACHANNEL_HEIGHT_HALF, ACHANNEL_SETTING_SELECT, ACHANNEL_STEP, SpaceAction::ads, ALE_ACT, ALE_ALL, ALE_FCURVE, ALE_GPFRAME, ALE_GROUP, ALE_NONE, ALE_OB, ALE_SCE, ANIM_animdata_filter(), ANIM_channel_get_typeinfo(), ANIM_channel_setting_get(), ANIM_nla_mapping_get(), ANIMCONT_ACTION, ANIMCONT_DOPESHEET, ANIMCONT_GPENCIL, ANIMCONT_SHAPEKEY, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_DSSKEY, ANIMTYPE_DSWOR, ANIMTYPE_FILLACTD, ANIMTYPE_GROUP, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, ANIMTYPE_SUMMARY, BLI_freelistN(), calc_action_range(), View2D::cur, bAnimContext::data, bAnimListElem::data, bAnimContext::datatype, bAnimListElem::datatype, draw_action_channel(), draw_agroup_channel(), draw_fcurve_channel(), draw_gpl_channel(), draw_object_channel(), draw_scene_channel(), draw_summary_channel(), ELEM3, EXTRA_SCROLL_PAD, filter(), ListBase::first, SpaceAction::flag, bAnimChannelType::has_setting, IN_RANGE, bAnimListElem::key_data, bAnimListElem::next, NULL, SACTION_MOVING, TH_BACK, TH_DOPESHEET_CHANNELOB, TH_DOPESHEET_CHANNELSUBOB, TH_GROUP, TH_GROUP_ACTIVE, TH_HILITE, SpaceAction::timeslide, View2D::tot, bAnimListElem::type, UI_GetThemeColor3ubv(), ARegion::v2d, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by action_main_area_draw().
Variable Documentation
enum { ... } eActKeys_ColumnSelect_Mode
enum { ... } eActKeys_LeftRightSelect_Mode
enum { ... } eActKeys_Mirror_Mode
enum { ... } eActKeys_Snap_Mode