Blender: wm.c File Reference
wm.c File Reference
windowmanager
#include <string.h>
#include <stddef.h>
#include "BLO_sys_types.h"
#include "DNA_windowmanager_types.h"
#include "GHOST_C-api.h"
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_blenlib.h"
#include "BLI_ghash.h"
#include "BKE_blender.h"
#include "BKE_context.h"
#include "BKE_idprop.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_screen.h"
#include "BKE_report.h"
#include "BKE_global.h"
#include "WM_api.h"
#include "WM_types.h"
#include "wm_window.h"
#include "wm_event_system.h"
#include "wm_event_types.h"
#include "wm_draw.h"
#include "wm.h"
#include "ED_screen.h"
Defines
#define MAX_OP_REGISTERED 32
Functions
void WM_operator_free (wmOperator *op)
static void wm_reports_free (wmWindowManager *wm)
void wm_operator_register (bContext *C, wmOperator *op)
void WM_operator_stack_clear (wmWindowManager *wm)
MenuType * WM_menutype_find (const char *idname, int quiet)
int WM_menutype_add (MenuType *mt)
void WM_menutype_freelink (MenuType *mt)
void WM_menutype_init (void)
void WM_menutype_free (void)
void WM_keymap_init (bContext *C)
void WM_check (bContext *C)
void wm_clear_default_size (bContext *C)
void wm_add_default (bContext *C)
void wm_close_and_free (bContext *C, wmWindowManager *wm)
void wm_close_and_free_all (bContext *C, ListBase *wmlist)
void WM_main (bContext *C)
Variables
static GHash * menutypes_hash = NULL
Detailed Description
Definition in file wm.c.
Define Documentation
#define MAX_OP_REGISTERED 32
Definition at line 72 of file wm.c.
Referenced by wm_operator_register().
Function Documentation
void wm_add_default (bContext * C)
Definition at line 292 of file wm.c.
References alloc_libblock(), BLI_strncpy(), CTX_data_main(), CTX_wm_manager_set(), CTX_wm_screen(), wmWindowManager::file_saved, bScreen::id, ID_WM, ID::name, wmWindow::screen, wmWindow::screenname, wmWindowManager::winactive, bScreen::winid, wmWindow::winid, wm_window_make_drawable(), and wm_window_new().
Referenced by load_file(), and wm_window_match_do().
void WM_check (bContext * C)
Definition at line 238 of file wm.c.
References CTX_data_main(), CTX_wm_manager(), CTX_wm_manager_set(), ED_screens_initialize(), ListBase::first, G, wmWindowManager::initialized, NULL, wmWindowManager::windows, Main::wm, WM_autosave_init(), WM_INIT_WINDOW, WM_keymap_init(), and wm_window_add_ghostwindows().
Referenced by load_file(), WM_read_file(), WM_read_homefile(), wm_window_duplicate_exec(), WM_window_open(), and WM_window_open_temp().
void wm_clear_default_size (bContext * C)
Definition at line 269 of file wm.c.
References CTX_data_main(), CTX_wm_manager(), CTX_wm_manager_set(), ListBase::first, wmWindow::next, NULL, wmWindow::posx, wmWindow::posy, wmWindow::sizex, wmWindow::sizey, wmWindowManager::windows, and Main::wm.
Referenced by WM_read_homefile().
void wm_close_and_free (bContext * C, wmWindowManager * wm)
Definition at line 311 of file wm.c.
References wmWindowManager::autosavetimer, BLI_freelistN(), BLI_remlink(), CTX_wm_manager(), CTX_wm_manager_set(), wmWindowManager::drags, ListBase::first, wmWindowManager::keyconfigs, NULL, wmWindowManager::operators, wmWindowManager::paintcursors, wmWindowManager::queue, wmWindow::screen, wmWindowManager::windows, wm_autosave_timer_ended(), wm_draw_window_clear(), WM_keyconfig_free(), WM_operator_free(), wm_reports_free(), and wm_window_free().
Referenced by wm_close_and_free_all(), and WM_init().
void wm_close_and_free_all (bContext * C, ListBase * wmlist)
Definition at line 347 of file wm.c.
References BLI_remlink(), ListBase::first, MEM_freeN(), and wm_close_and_free().
Referenced by wm_window_match_do().
void WM_keymap_init (bContext * C)
Definition at line 207 of file wm.c.
References wmWindowManager::addonconf, CTX_py_init_get(), CTX_wm_manager(), wmWindowManager::defaultconf, ED_spacetypes_keymap(), wmKeyConfig::flag, wmWindowManager::initialized, KEYCONF_INIT_DEFAULT, NULL, wmWindowManager::userconf, WM_INIT_KEYMAP, WM_keyconfig_new(), WM_keyconfig_update(), WM_keyconfig_update_tag(), and wm_window_keymap().
Referenced by main(), and WM_check().
void WM_main (bContext * C)
Definition at line 358 of file wm.c.
References wm_draw_update(), wm_event_do_handlers(), wm_event_do_notifiers(), and wm_window_process_events().
Referenced by main().
int WM_menutype_add (MenuType * mt)
Definition at line 172 of file wm.c.
References BLI_ghash_insert(), and MenuType::idname.
Referenced by node_menus_register(), and recent_files_menu_register().
MenuType* WM_menutype_find (const char * idname, int quiet) [read]
Definition at line 156 of file wm.c.
References BLI_ghash_lookup(), mt, and NULL.
Referenced by uiItemM(), uiPupMenuInvoke(), and wm_block_create_splash().
void WM_menutype_free (void)
Definition at line 189 of file wm.c.
References BLI_ghash_free(), BLI_ghashIterator_free(), BLI_ghashIterator_getValue(), BLI_ghashIterator_isDone(), BLI_ghashIterator_new(), BLI_ghashIterator_step(), ExtensionRNA::data, MenuType::ext, ExtensionRNA::free, MEM_freeN(), mt, and NULL.
Referenced by WM_exit_ext().
void WM_menutype_freelink (MenuType * mt)
Definition at line 178 of file wm.c.
References BLI_ghash_remove(), MenuType::idname, MEM_freeN(), and NULL.
void WM_menutype_init (void)
Definition at line 184 of file wm.c.
References BLI_ghash_new(), BLI_ghashutil_strcmp(), and BLI_ghashutil_strhash().
Referenced by WM_init().
void WM_operator_free (wmOperator * op)
Definition at line 74 of file wm.c.
References BKE_reports_clear(), BPY_DECREF(), PointerRNA::data, ListBase::first, ReportList::flag, IDP_FreeProperty(), wmOperator::macro, MEM_freeN(), wmOperator::next, wmOperator::properties, wmOperator::ptr, wmOperator::py_instance, wmOperator::reports, RPT_FREE, and WM_operator_free().
Referenced by confirm_cancel_operator(), operator_cb(), wm_close_and_free(), WM_event_add_fileselect(), WM_event_remove_handlers(), wm_exit_blender_op(), wm_handler_fileselect_call(), wm_handler_operator_call(), wm_operator_exec(), wm_operator_finished(), WM_operator_free(), wm_operator_invoke(), wm_operator_register(), WM_operator_stack_clear(), and wm_operator_ui_popup_cancel().
void wm_operator_register (bContext * C, wmOperator * op)
Definition at line 119 of file wm.c.
References BLI_addtail(), BLI_countlist(), BLI_remlink(), CTX_wm_manager(), ListBase::first, MAX_OP_REGISTERED, NC_SPACE, NC_WM, ND_HISTORY, ND_SPACE_INFO_REPORT, NULL, wmWindowManager::operators, WM_event_add_notifier(), and WM_operator_free().
Referenced by wm_operator_finished(), and WM_operator_props_popup().
void WM_operator_stack_clear (wmWindowManager * wm)
Definition at line 140 of file wm.c.
References BLI_remlink(), ListBase::first, NC_WM, ND_HISTORY, NULL, wmWindowManager::operators, WM_main_add_notifier(), and WM_operator_free().
Referenced by ed_undo_exec().
static void wm_reports_free (wmWindowManager * wm) [static]
Definition at line 111 of file wm.c.
References BKE_reports_clear(), NULL, wmWindowManager::reports, ReportList::reporttimer, and WM_event_remove_timer().
Referenced by wm_close_and_free().
Variable Documentation
GHash* menutypes_hash = NULL [static]
Definition at line 154 of file wm.c.