Blender: resources.c File Reference
resources.c File Reference
interface
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "DNA_curve_types.h"
#include "DNA_userdef_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_windowmanager_types.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BKE_DerivedMesh.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_texture.h"
#include "BIF_gl.h"
#include "UI_interface.h"
#include "UI_interface_icons.h"
#include "interface_intern.h"
Typedefs
typedef void(* VectorDrawFunc)(int x, int y, int w, int h, float alpha)
Functions
void ui_resources_init (void)
void ui_resources_free (void)
const unsigned char * UI_ThemeGetColorPtr (bTheme *btheme, int spacetype, int colorid)
static void ui_theme_init_boneColorSets (bTheme *btheme)
static void ui_theme_init_new_do (ThemeSpace *ts)
static void ui_theme_init_new (bTheme *btheme)
void ui_theme_init_default (void)
void UI_SetTheme (int spacetype, int regionid)
bTheme * UI_GetTheme ()
void UI_ThemeColor (int colorid)
void UI_ThemeColor4 (int colorid)
void UI_ThemeColorShade (int colorid, int offset)
void UI_ThemeColorShadeAlpha (int colorid, int coloffset, int alphaoffset)
void UI_ThemeColorBlend (int colorid1, int colorid2, float fac)
void UI_ThemeColorBlendShade (int colorid1, int colorid2, float fac, int offset)
void UI_ThemeColorBlendShadeAlpha (int colorid1, int colorid2, float fac, int offset, int alphaoffset)
float UI_GetThemeValuef (int colorid)
int UI_GetThemeValue (int colorid)
void UI_GetThemeColor3fv (int colorid, float *col)
void UI_GetThemeColorShade3fv (int colorid, int offset, float *col)
void UI_GetThemeColor3ubv (int colorid, unsigned char col[3])
void UI_GetThemeColor4ubv (int colorid, unsigned char col[4])
void UI_GetThemeColorType4ubv (int colorid, int spacetype, char col[4])
void UI_ColorPtrBlendShade3ubv (const unsigned char cp1[3], const unsigned char cp2[3], float fac, int offset)
void UI_GetColorPtrShade3ubv (const unsigned char cp[3], unsigned char col[3], int offset)
void UI_GetColorPtrBlendShade3ubv (const unsigned char cp1[3], const unsigned char cp2[3], unsigned char col[3], float fac, int offset)
void UI_ThemeClearColor (int colorid)
void UI_make_axis_color (const unsigned char src_col[3], unsigned char dst_col[3], const char axis)
void init_userdef_do_versions (void)
Variables
static bTheme * theme_active = NULL
static int theme_spacetype = SPACE_VIEW3D
static int theme_regionid = RGN_TYPE_WINDOW
Detailed Description
Definition in file resources.c.
Typedef Documentation
typedef void(* VectorDrawFunc)(int x, int y, int w, int h, float alpha)
Definition at line 62 of file resources.c.
Function Documentation
void init_userdef_do_versions (void)
Definition at line 1179 of file resources.c.
References ThemeSpace::act_marker, ThemeSpace::act_spline, ThemeSpace::audio, AUTOKEY_FLAG_ONLYKEYINGSET, ThemeSpace::back, BEZT_IPO_BEZ, BLI_addtail(), BLI_findstring(), BLI_strncpy(), BLI_system_temporary_dir(), ThemeSpace::bone_pose, ThemeSpace::bone_solid, ThemeSpace::bundle_solid, ThemeSpace::camera_path, ThemeSpace::cframe, ThemeSpace::dis_marker, ThemeSpace::ds_channel, ThemeSpace::ds_subchannel, ThemeSpace::edge_crease, ThemeSpace::edge_seam, ThemeSpace::edge_select, ThemeSpace::edge_sharp, ThemeSpace::editmesh_active, ThemeSpace::effect, ThemeSpace::extra_edge_len, ThemeSpace::extra_face_angle, ThemeSpace::extra_face_area, ThemeSpace::face_dot, ThemeSpace::facedot_size, G, ThemeSpace::grid, ThemeSpace::group, ThemeSpace::group_active, ThemeSpace::handle_align, ThemeSpace::handle_auto, ThemeSpace::handle_auto_clamped, ThemeSpace::handle_free, ThemeSpace::handle_sel_align, ThemeSpace::handle_sel_auto, ThemeSpace::handle_sel_auto_clamped, ThemeSpace::handle_sel_free, ThemeSpace::handle_sel_vect, ThemeSpace::handle_vect, ThemeSpace::handle_vertex, ThemeSpace::handle_vertex_select, ThemeSpace::handle_vertex_size, HD_AUTO, HD_AUTO_ANIM, uiPanelColors::header, ThemeUI::icon_alpha, wmKeyMap::idname, ThemeSpace::image, init_colorband(), uiWidgetColors::inner, uiWidgetColors::item, ThemeSpace::lamp, ThemeSpace::lastsel_point, ThemeSpace::lock_marker, ThemeSpace::marker, ThemeSpace::marker_outline, ThemeSpace::match, MEM_callocN(), ThemeSpace::meta, bAddon::module, module, ThemeSpace::movie, ThemeSpace::movieclip, NDOF_LOCK_HORIZON, NDOF_SHOULD_PAN, NDOF_SHOULD_ROTATE, NDOF_SHOULD_ZOOM, wmKeyMap::next, bTheme::next, ThemeSpace::noodle_curving, ThemeSpace::normal, NULL, uiWidgetColors::outline, ThemeSpace::outline_width, ThemeUI::panel, ThemeSpace::path_after, ThemeSpace::path_before, ThemeSpace::plugin, ThemeSpace::preview_stitch_active, ThemeSpace::preview_stitch_edge, ThemeSpace::preview_stitch_face, ThemeSpace::preview_stitch_stitchable, ThemeSpace::preview_stitch_unstitchable, ThemeSpace::preview_stitch_vert, rgba_char_args_set(), rgba_char_args_set_fl, ThemeSpace::scene, ThemeSpace::sel_marker, ThemeSpace::selected_highlight, ThemeSpace::shade1, ThemeWireColor::solid, ThemeSpace::speaker, ThemeSpace::strip, ThemeSpace::strip_select, Main::subversionfile, ThemeSpace::syntaxb, ThemeSpace::syntaxc, ThemeSpace::syntaxl, ThemeSpace::syntaxn, ThemeSpace::syntaxv, bTheme::tact, bTheme::tarm, bTheme::tclip, uiWidgetColors::text, bTheme::text, bTheme::tima, bTheme::tinfo, bTheme::tipo, bTheme::tlogic, bTheme::tnla, bTheme::tnode, bTheme::toops, ThemeSpace::transition, bTheme::tseq, bTheme::ttime, bTheme::tui, bTheme::tuserpref, bTheme::tv3d, ui_theme_init_boneColorSets(), ui_theme_init_new(), ui_widget_color_init(), USER_ADD_EDITMODE, USER_ADD_VIEWALIGNED, USER_CUSTOM_RANGE, USER_DISABLE_VBO, USER_DRAW_AUTOMATIC, USER_DRAW_TRIPLE, USER_DUP_ARM, USER_GLOBALUNDO, USER_LMOUSESELECT, USER_PLAINMENUS, USER_SHOW_ROTVIEWICON, USER_TWOBUTTONMOUSE, vDM_ColorBand_store(), Main::versionfile, ThemeSpace::vertex, ThemeSpace::vertex_normal, ThemeSpace::vertex_select, ThemeSpace::vertex_size, ThemeUI::wcol_menu_back, ThemeUI::wcol_menu_item, ThemeUI::wcol_num, wcol_progress, ThemeUI::wcol_progress, and ThemeUI::wcol_tooltip.
Referenced by UI_init_userdef().
void UI_ColorPtrBlendShade3ubv (const unsigned char cp1[3], const unsigned char cp2[3], float fac, int offset)
Definition at line 1093 of file resources.c.
References CLAMP(), floorf, and g.
void UI_GetColorPtrBlendShade3ubv (const unsigned char cp1[3], const unsigned char cp2[3], unsigned char col[3], float fac, int offset)
Definition at line 1126 of file resources.c.
References CLAMP(), and g.
Referenced by draw_seq_extensions(), draw_shadedstrip(), and get_seq_color3ubv().
void UI_GetColorPtrShade3ubv (const unsigned char cp[3], unsigned char col[3], int offset)
Definition at line 1108 of file resources.c.
References CLAMP(), and g.
Referenced by draw_seq_extensions(), draw_seq_strip(), draw_shadedstrip(), drawfloor(), drawmeta_contents(), and get_seq_color3ubv().
bTheme* UI_GetTheme (void) [read]
Definition at line 886 of file resources.c.
Referenced by draw_textscroll(), icon_draw_size(), init_internal_icons(), set_pchan_colorset(), ui_draw_aligned_panel(), ui_draw_but(), UI_view2d_scrollers_draw(), widget_state_option_menu(), and widget_type().
void UI_GetThemeColor3fv (int colorid, float * col)
Definition at line 1028 of file resources.c.
References theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by acf_generic_dataexpand_color(), acf_generic_root_color(), draw_image_seq(), draw_mesh_fancy(), draw_ptcache_edit(), draw_timeline_seq(), file_main_area_draw(), file_ui_area_draw(), graph_channel_area_draw(), graph_main_area_draw(), image_main_area_draw(), nla_strip_get_color_inside(), outliner_draw_tree(), region_draw_azone_tab(), track_colors(), and UI_ThemeClearColor().
void UI_GetThemeColor3ubv (int colorid, unsigned char col[3])
Definition at line 1059 of file resources.c.
References theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by console_line_color(), console_textview_line_color(), draw_channel_strips(), draw_ebones(), draw_em_fancy_verts(), draw_em_indices(), draw_em_measure_stats(), draw_fcurve_handles(), draw_motion_path_instance(), draw_object(), draw_pose_bones(), draw_textscroll(), drawfloor(), drawgrid(), drawHelpline(), drawLine(), drawSnapping(), get_seq_color3ubv(), knife_init_colors(), manipulator_setcolor(), PE_create_particle_edit(), tekenhandlesN(), ui_draw_preview_item(), and widget_draw_extra_mask().
void UI_GetThemeColor4ubv (int colorid, unsigned char col[4])
Definition at line 1070 of file resources.c.
References theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by draw_em_fancy(), draw_em_fancy_edges(), draw_uvs(), draw_viewport_object_reconstruction(), drawlamp(), text_find_and_replace(), widget_state_label(), and widget_state_option_menu().
void UI_GetThemeColorShade3fv (int colorid, int offset, float * col)
Definition at line 1039 of file resources.c.
References CLAMP(), g, theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by acf_generic_channel_color(), acf_gpd_color(), and acf_group_color().
void UI_GetThemeColorType4ubv (int colorid, int spacetype, char col[4])
Definition at line 1081 of file resources.c.
References UI_ThemeGetColorPtr().
Referenced by outliner_draw_tree_element().
int UI_GetThemeValue (int colorid)
Definition at line 1017 of file resources.c.
References theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by node_link_bezier_points().
float UI_GetThemeValuef (int colorid)
Definition at line 1007 of file resources.c.
References theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by bbs_mesh_solid_EM(), bbs_mesh_verts(), bbs_obmode_mesh_verts(), draw_dm_bweights(), draw_dm_verts__mapFunc(), draw_em_fancy_verts(), draw_fcurve_samples(), draw_fcurve_vertices(), draw_fcurve_vertices_handles(), draw_mesh_fancy(), draw_mesh_object_outline(), draw_ptcache_edit(), draw_tracks_curves(), draw_uvs(), drawSnapping(), lattice_draw_verts(), tekenvertsN(), and vtx_slide_draw().
void UI_make_axis_color (const unsigned char src_col[3], unsigned char dst_col[3], const char axis)
Definition at line 1152 of file resources.c.
References BLI_assert.
void ui_resources_free (void)
Definition at line 73 of file resources.c.
References UI_icons_free().
Referenced by UI_exit().
void ui_resources_init (void)
Definition at line 68 of file resources.c.
References UI_icons_init().
Referenced by UI_init().
void UI_SetTheme (int spacetype, int regionid)
Definition at line 871 of file resources.c.
References RGN_TYPE_WINDOW, SPACE_VIEW3D, theme_regionid, and theme_spacetype.
Referenced by ED_region_do_draw(), ED_region_set(), and ui_theme_init_default().
static void ui_theme_init_boneColorSets (bTheme * btheme) [static]
Definition at line 480 of file resources.c.
References ThemeWireColor::active, ThemeWireColor::flag, i, rgba_char_args_set(), ThemeWireColor::select, ThemeWireColor::solid, and bTheme::tarm.
Referenced by init_userdef_do_versions(), and ui_theme_init_default().
void ui_theme_init_default (void)
Definition at line 600 of file resources.c.
References ThemeSpace::act_marker, ThemeSpace::act_spline, ThemeSpace::active, ThemeSpace::audio, ThemeSpace::back, BLI_addtail(), ThemeSpace::bone_pose, ThemeSpace::bone_solid, ThemeSpace::bundle_solid, ThemeSpace::button, ThemeSpace::button_text, ThemeSpace::button_text_hi, ThemeSpace::button_title, ThemeSpace::camera, ThemeSpace::camera_path, ThemeSpace::cframe, ThemeSpace::console_cursor, ThemeSpace::console_error, ThemeSpace::console_info, ThemeSpace::console_input, ThemeSpace::console_output, ThemeSpace::dis_marker, ThemeSpace::ds_channel, ThemeSpace::ds_subchannel, ThemeSpace::edge, ThemeSpace::edge_crease, ThemeSpace::edge_facesel, ThemeSpace::edge_seam, ThemeSpace::edge_select, ThemeSpace::edge_sharp, ThemeSpace::editmesh_active, ThemeSpace::effect, ThemeSpace::empty, ThemeSpace::extra_edge_len, ThemeSpace::extra_face_angle, ThemeSpace::extra_face_area, ThemeSpace::face, ThemeSpace::face_dot, ThemeSpace::face_select, ThemeSpace::facedot_size, FALSE, ThemeSpace::grid, ThemeSpace::group, ThemeSpace::group_active, ThemeSpace::handle_align, ThemeSpace::handle_auto, ThemeSpace::handle_auto_clamped, ThemeSpace::handle_free, ThemeSpace::handle_sel_align, ThemeSpace::handle_sel_auto, ThemeSpace::handle_sel_auto_clamped, ThemeSpace::handle_sel_free, ThemeSpace::handle_sel_vect, ThemeSpace::handle_vect, ThemeSpace::handle_vertex, ThemeSpace::handle_vertex_select, ThemeSpace::handle_vertex_size, ThemeSpace::header, uiPanelColors::header, ThemeSpace::header_text, ThemeSpace::header_text_hi, ThemeSpace::hilite, ThemeUI::iconfile, ThemeSpace::image, ThemeSpace::lamp, ThemeSpace::lastsel_point, ThemeSpace::list, ThemeSpace::lock_marker, ThemeSpace::marker, ThemeSpace::marker_outline, ThemeSpace::match, MEM_callocN(), ThemeSpace::meta, ThemeSpace::movie, ThemeSpace::movieclip, bTheme::name, bTheme::next, ThemeSpace::noodle_curving, ThemeSpace::normal, NULL, ThemeSpace::nurb_sel_uline, ThemeSpace::nurb_sel_vline, ThemeSpace::nurb_uline, ThemeSpace::nurb_vline, ThemeSpace::outline_width, ThemeSpace::panel, ThemeUI::panel, ThemeSpace::path_after, ThemeSpace::path_before, ThemeSpace::plugin, ThemeSpace::preview_back, ThemeSpace::preview_stitch_edge, ThemeSpace::preview_stitch_face, ThemeSpace::preview_stitch_stitchable, ThemeSpace::preview_stitch_unstitchable, ThemeSpace::preview_stitch_vert, rgba_char_args_set(), rgba_char_args_set_fl, ThemeSpace::scene, ThemeSpace::sel_marker, ThemeSpace::select, ThemeSpace::selected_highlight, ThemeSpace::shade1, ThemeSpace::shade2, uiPanelColors::show_header, ThemeSpace::speaker, ThemeSpace::strip, ThemeSpace::strip_select, ThemeSpace::syntaxb, ThemeSpace::syntaxc, ThemeSpace::syntaxl, ThemeSpace::syntaxn, ThemeSpace::syntaxv, bTheme::tact, bTheme::tbuts, bTheme::tclip, bTheme::tconsole, bTheme::text, ThemeSpace::text, ThemeSpace::text_hi, bTheme::tfile, bTheme::tima, bTheme::tinfo, bTheme::tipo, ThemeSpace::title, bTheme::tlogic, bTheme::tnla, bTheme::tnode, bTheme::toops, ThemeSpace::transform, ThemeSpace::transition, bTheme::tseq, bTheme::ttime, bTheme::tui, bTheme::tuserpref, bTheme::tv3d, UI_SetTheme(), ui_theme_init_boneColorSets(), ui_theme_init_new(), ui_widget_color_init(), ThemeSpace::vertex, ThemeSpace::vertex_normal, ThemeSpace::vertex_select, ThemeSpace::vertex_size, and ThemeSpace::wire.
Referenced by reset_default_theme_exec().
static void ui_theme_init_new (bTheme * btheme) [static]
Definition at line 573 of file resources.c.
References bTheme::tact, bTheme::tbuts, bTheme::tclip, bTheme::tconsole, bTheme::text, bTheme::tfile, bTheme::tima, bTheme::tinfo, bTheme::tipo, bTheme::tlogic, bTheme::tnla, bTheme::tnode, bTheme::toops, bTheme::tseq, bTheme::ttime, bTheme::tuserpref, bTheme::tv3d, and ui_theme_init_new_do().
Referenced by init_userdef_do_versions(), and ui_theme_init_default().
static void ui_theme_init_new_do (ThemeSpace * ts) [static]
Definition at line 552 of file resources.c.
References ThemeSpace::button, ThemeSpace::button_text, ThemeSpace::button_text_hi, ThemeSpace::button_title, ThemeSpace::header_text, ThemeSpace::header_text_hi, ThemeSpace::header_title, ThemeSpace::list, ThemeSpace::list_text, ThemeSpace::list_text_hi, ThemeSpace::list_title, ThemeSpace::panel_text, ThemeSpace::panel_text_hi, ThemeSpace::panel_title, and rgba_char_args_test_set().
Referenced by ui_theme_init_new().
void UI_ThemeClearColor (int colorid)
Definition at line 1144 of file resources.c.
References UI_GetThemeColor3fv().
Referenced by action_channel_area_draw(), action_main_area_draw(), buttons_header_area_draw(), clip_main_area_draw(), clip_preview_area_draw(), console_main_area_draw(), drawnodespace(), ED_region_do_draw(), ED_region_header(), ED_region_panels(), ED_view3d_draw_offscreen(), info_main_area_draw(), logic_main_area_draw(), nla_channel_area_draw(), nla_main_area_draw(), node_draw_basis(), outliner_main_area_draw(), script_main_area_draw(), text_main_area_draw(), time_main_area_draw(), uiDrawPanels(), and view3d_main_area_draw_objects().
void UI_ThemeColor (int colorid)
Definition at line 892 of file resources.c.
References theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by ANIM_channel_draw(), ANIM_draw_cfra(), clip_draw_curfra_label(), draw_armature(), draw_b_bone(), draw_bone(), draw_bone_points(), draw_brackets(), draw_cfra_number(), draw_controllerbuttons(), draw_cursor(), draw_documentation(), draw_ebones(), draw_editnurb(), draw_em_fancy(), draw_empty_image(), draw_fcurve_samples(), draw_fcurve_vertices_handles(), draw_graph_cfra(), draw_image_grid(), draw_line_bone(), draw_manipulator_rotate(), draw_manipulator_rotate_cyl(), draw_marker(), draw_marker_areas(), draw_marker_outline(), draw_marker_slide_zones(), draw_marker_texts(), draw_mesh_face_select(), draw_mesh_fancy(), draw_motion_path_instance(), draw_movieclip_cache(), draw_new_particle_system(), draw_nla_channel_list_gl(), draw_object(), draw_object_mesh_instance(), draw_pose_bones(), draw_selected_name(), draw_seq_backdrop(), draw_sphere_bone(), draw_sphere_bone_wire(), draw_suggestion_list(), draw_text_main(), draw_textscroll(), draw_track_path(), draw_uvs(), draw_viewport_fps(), draw_viewport_name(), draw_viewport_object_reconstruction(), drawgrid(), drawHelpline(), drawmball(), drawnurb(), drawPropCircle(), drawviewborder(), drawWireExtra(), ED_region_do_draw(), ED_region_info_draw(), editnurb_draw_active_nurbs(), editnurb_draw_active_poly(), format_draw_color(), knifetool_draw_angle_snapping(), lattice_draw_verts(), node_circle_draw(), node_draw_basis(), node_draw_group(), node_draw_hidden(), node_draw_link_bezier(), node_draw_link_straight(), outliner_draw_restrictcols(), outliner_draw_tree_element(), set_ebone_glColor(), set_pchan_glColor(), tekenhandlesN_active(), tekenvertsN(), tracking_segment_knot_cb(), ui_draw_aligned_panel(), ui_draw_aligned_panel_header(), ui_draw_but_CURVE(), ui_draw_but_TRACKPREVIEW(), UI_view2d_grid_draw(), UI_view2d_scrollers_draw(), view3d_main_area_draw_info(), and widget_link().
void UI_ThemeColor4 (int colorid)
Definition at line 902 of file resources.c.
References theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by draw_dm_verts__mapFunc(), draw_keylist(), draw_uvs(), file_draw_list(), and node_draw_basis().
void UI_ThemeColorBlend (int colorid1, int colorid2, float fac)
Definition at line 945 of file resources.c.
References CLAMP(), floorf, g, theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by draw_dm_bweights__mapFunc(), draw_dm_bweights__setDrawOptions(), draw_dm_creases__setDrawOptions(), draw_dupli_objects_color(), draw_em_fancy(), draw_forcefield(), draw_motion_path_instance(), drawgrid(), ED_view3d_draw_offscreen(), fdrawbezier(), format_draw_color(), node_draw_basis(), node_draw_hidden(), node_draw_link(), node_draw_link_bezier(), node_draw_link_straight(), outliner_draw_tree(), outliner_draw_tree_element(), set_ebone_glColor(), set_pchan_glColor(), and view3d_main_area_draw_objects().
void UI_ThemeColorBlendShade (int colorid1, int colorid2, float fac, int offset)
Definition at line 962 of file resources.c.
References CLAMP(), floorf, g, theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by draw_image_seq(), draw_motion_path_instance(), drawviewborder(), node_draw_basis(), and node_draw_hidden().
void UI_ThemeColorBlendShadeAlpha (int colorid1, int colorid2, float fac, int offset, int alphaoffset)
Definition at line 983 of file resources.c.
References CLAMP(), floorf, g, theme_spacetype, and UI_ThemeGetColorPtr().
void UI_ThemeColorShade (int colorid, int offset)
Definition at line 912 of file resources.c.
References CLAMP(), g, theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by draw_background(), draw_cfra_number(), draw_dividers(), draw_graph_sfra_efra(), draw_image_grid(), draw_line_bone(), draw_manipulator_rotate(), draw_marker_areas(), draw_marker_texts(), draw_mesh_fancy(), draw_nla_channel_list_gl(), draw_object(), draw_seq_backdrop(), draw_sphere_bone(), draw_tile(), drawviewborder(), drawWireExtra(), graph_draw_curves(), node_draw_basis(), node_draw_hidden(), node_scaling_widget(), outliner_back(), outliner_draw_restrictcols(), outliner_draw_tree_element(), seq_draw_sfra_efra(), set_col_actuator(), set_col_sensor(), set_ebone_glColor(), set_pchan_glColor(), time_draw_sfra_efra(), ui_draw_aligned_panel(), UI_view2d_constant_grid_draw(), UI_view2d_grid_draw(), and view3d_draw_clipping().
void UI_ThemeColorShadeAlpha (int colorid, int coloffset, int alphaoffset)
Definition at line 927 of file resources.c.
References CLAMP(), g, theme_spacetype, and UI_ThemeGetColorPtr().
Referenced by draw_ghost_poses(), draw_ghost_poses_keys(), draw_ghost_poses_range(), draw_keyframe_shape(), drawcentercircle(), graph_main_area_draw(), node_draw_basis(), node_draw_group(), node_draw_hidden(), node_draw_link_bezier(), node_draw_link_straight(), node_draw_preview(), outliner_draw_restrictcols(), outliner_draw_rnacols(), outliner_draw_tree(), seq_draw_sfra_efra(), set_fcurve_vertex_color(), and vtx_slide_draw().
const unsigned char* UI_ThemeGetColorPtr (bTheme * btheme, int spacetype, int colorid)
Definition at line 83 of file resources.c.
References ThemeSpace::act_marker, ThemeSpace::act_spline, ThemeSpace::active, ThemeSpace::audio, ThemeSpace::back, ThemeSpace::bone_pose, ThemeSpace::bone_solid, ThemeSpace::bundle_solid, ThemeSpace::button, ThemeSpace::button_text, ThemeSpace::button_text_hi, ThemeSpace::button_title, ThemeSpace::camera, ThemeSpace::camera_path, ThemeSpace::cframe, ThemeSpace::console_cursor, ThemeSpace::console_error, ThemeSpace::console_info, ThemeSpace::console_input, ThemeSpace::console_output, ThemeSpace::dis_marker, ThemeSpace::ds_channel, ThemeSpace::ds_subchannel, ThemeSpace::edge, ThemeSpace::edge_crease, ThemeSpace::edge_facesel, ThemeSpace::edge_seam, ThemeSpace::edge_select, ThemeSpace::edge_sharp, ThemeSpace::editmesh_active, ThemeSpace::effect, ThemeSpace::empty, error(), ThemeSpace::extra_edge_len, ThemeSpace::extra_face_angle, ThemeSpace::extra_face_area, ThemeSpace::face, ThemeSpace::face_dot, ThemeSpace::face_select, ThemeSpace::facedot_size, ThemeSpace::grid, ThemeSpace::group, ThemeSpace::group_active, ThemeSpace::handle_align, ThemeSpace::handle_auto, ThemeSpace::handle_auto_clamped, ThemeSpace::handle_free, ThemeSpace::handle_sel_align, ThemeSpace::handle_sel_auto, ThemeSpace::handle_sel_auto_clamped, ThemeSpace::handle_sel_free, ThemeSpace::handle_sel_vect, ThemeSpace::handle_vect, ThemeSpace::handle_vertex, ThemeSpace::handle_vertex_select, ThemeSpace::handle_vertex_size, ThemeSpace::header, ThemeSpace::header_text, ThemeSpace::header_text_hi, ThemeSpace::header_title, ThemeSpace::hilite, ThemeSpace::image, ThemeSpace::lamp, ThemeSpace::lastsel_point, ThemeSpace::list, ThemeSpace::list_text, ThemeSpace::list_text_hi, ThemeSpace::list_title, ThemeSpace::lock_marker, ThemeSpace::marker, ThemeSpace::marker_outline, ThemeSpace::match, ThemeSpace::meta, ThemeSpace::movie, ThemeSpace::movieclip, ThemeSpace::noodle_curving, ThemeSpace::normal, NULL, ThemeSpace::nurb_sel_uline, ThemeSpace::nurb_sel_vline, ThemeSpace::nurb_uline, ThemeSpace::nurb_vline, ThemeSpace::outline_width, ThemeSpace::panel, ThemeSpace::panel_text, ThemeSpace::panel_text_hi, ThemeSpace::path_after, ThemeSpace::path_before, ThemeSpace::plugin, ThemeSpace::preview_back, ThemeSpace::preview_stitch_active, ThemeSpace::preview_stitch_edge, ThemeSpace::preview_stitch_face, ThemeSpace::preview_stitch_stitchable, ThemeSpace::preview_stitch_unstitchable, ThemeSpace::preview_stitch_vert, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, ThemeSpace::scene, ThemeSpace::sel_marker, ThemeSpace::select, ThemeSpace::selected_highlight, ThemeSpace::shade1, ThemeSpace::shade2, SPACE_ACTION, SPACE_BUTS, SPACE_CLIP, SPACE_CONSOLE, SPACE_FILE, SPACE_IMAGE, SPACE_INFO, SPACE_IPO, SPACE_LOGIC, SPACE_NLA, SPACE_NODE, SPACE_OUTLINER, SPACE_SEQ, SPACE_TEXT, SPACE_TIME, SPACE_USERPREF, SPACE_VIEW3D, ThemeSpace::speaker, ThemeSpace::strip, ThemeSpace::strip_select, ThemeSpace::syntaxb, ThemeSpace::syntaxc, ThemeSpace::syntaxl, ThemeSpace::syntaxn, ThemeSpace::syntaxv, bTheme::tact, bTheme::tbuts, bTheme::tclip, bTheme::tconsole, ThemeSpace::text, bTheme::text, ThemeSpace::text_hi, bTheme::tfile, TH_ACT_MARKER, TH_ACTIVE, TH_ACTIVE_SPLINE, TH_BACK, TH_BONE_POSE, TH_BONE_SOLID, TH_BUNDLE_SOLID, TH_BUTBACK, TH_BUTBACK_TEXT, TH_BUTBACK_TEXT_HI, TH_CAMERA, TH_CAMERA_PATH, TH_CFRAME, TH_CONSOLE_CURSOR, TH_CONSOLE_ERROR, TH_CONSOLE_INFO, TH_CONSOLE_INPUT, TH_CONSOLE_OUTPUT, TH_DIS_MARKER, TH_DOPESHEET_CHANNELOB, TH_DOPESHEET_CHANNELSUBOB, TH_DRAWEXTRA_EDGELEN, TH_DRAWEXTRA_FACEANG, TH_DRAWEXTRA_FACEAREA, TH_EDGE, TH_EDGE_CREASE, TH_EDGE_FACESEL, TH_EDGE_SEAM, TH_EDGE_SELECT, TH_EDGE_SHARP, TH_EDITMESH_ACTIVE, TH_EMPTY, TH_FACE, TH_FACE_DOT, TH_FACE_SELECT, TH_FACEDOT_SIZE, TH_GRID, TH_GROUP, TH_GROUP_ACTIVE, TH_HANDLE_ALIGN, TH_HANDLE_AUTO, TH_HANDLE_AUTOCLAMP, TH_HANDLE_FREE, TH_HANDLE_SEL_ALIGN, TH_HANDLE_SEL_AUTO, TH_HANDLE_SEL_AUTOCLAMP, TH_HANDLE_SEL_FREE, TH_HANDLE_SEL_VECT, TH_HANDLE_VECT, TH_HANDLE_VERTEX, TH_HANDLE_VERTEX_SELECT, TH_HANDLE_VERTEX_SIZE, TH_HEADER, TH_HEADER_TEXT, TH_HEADER_TEXT_HI, TH_HEADERDESEL, TH_HILITE, TH_LAMP, TH_LASTSEL_POINT, TH_LOCK_MARKER, TH_MARKER, TH_MARKER_OUTLINE, TH_MATCH, TH_NODE, TH_NODE_CONVERTOR, TH_NODE_CURVING, TH_NODE_GROUP, TH_NODE_IN_OUT, TH_NODE_OPERATOR, TH_NORMAL, TH_NURB_SEL_ULINE, TH_NURB_SEL_VLINE, TH_NURB_ULINE, TH_NURB_VLINE, TH_OUTLINE_WIDTH, TH_PANEL, TH_PANEL_TEXT, TH_PANEL_TEXT_HI, TH_PATH_AFTER, TH_PATH_BEFORE, TH_PREVIEW_BACK, TH_REDALERT, TH_SEL_MARKER, TH_SELECT, TH_SELECT_HIGHLIGHT, TH_SEQ_AUDIO, TH_SEQ_EFFECT, TH_SEQ_IMAGE, TH_SEQ_META, TH_SEQ_MOVIE, TH_SEQ_MOVIECLIP, TH_SEQ_PLUGIN, TH_SEQ_PREVIEW, TH_SEQ_SCENE, TH_SEQ_TRANSITION, TH_SHADE1, TH_SHADE2, TH_SPEAKER, TH_STITCH_PREVIEW_ACTIVE, TH_STITCH_PREVIEW_EDGE, TH_STITCH_PREVIEW_FACE, TH_STITCH_PREVIEW_STITCHABLE, TH_STITCH_PREVIEW_UNSTITCHABLE, TH_STITCH_PREVIEW_VERT, TH_STRIP, TH_STRIP_SELECT, TH_SYNTAX_B, TH_SYNTAX_C, TH_SYNTAX_L, TH_SYNTAX_N, TH_SYNTAX_V, TH_TEXT, TH_TEXT_HI, TH_THEMEUI, TH_TITLE, TH_TRANSFORM, TH_VERTEX, TH_VERTEX_SELECT, TH_VERTEX_SIZE, TH_VNORMAL, TH_WIRE, theme_regionid, bTheme::tima, bTheme::tinfo, bTheme::tipo, ThemeSpace::title, bTheme::tlogic, bTheme::tnla, bTheme::tnode, bTheme::toops, ThemeSpace::transform, ThemeSpace::transition, bTheme::tseq, bTheme::ttime, bTheme::tuserpref, bTheme::tv3d, ThemeSpace::vertex, ThemeSpace::vertex_normal, ThemeSpace::vertex_select, ThemeSpace::vertex_size, and ThemeSpace::wire.
Referenced by UI_GetThemeColor3fv(), UI_GetThemeColor3ubv(), UI_GetThemeColor4ubv(), UI_GetThemeColorShade3fv(), UI_GetThemeColorType4ubv(), UI_GetThemeValue(), UI_GetThemeValuef(), UI_ThemeColor(), UI_ThemeColor4(), UI_ThemeColorBlend(), UI_ThemeColorBlendShade(), UI_ThemeColorBlendShadeAlpha(), UI_ThemeColorShade(), and UI_ThemeColorShadeAlpha().
Variable Documentation
bTheme* theme_active = NULL [static]
Definition at line 64 of file resources.c.
int theme_regionid = RGN_TYPE_WINDOW [static]
Definition at line 66 of file resources.c.
Referenced by UI_SetTheme(), and UI_ThemeGetColorPtr().
int theme_spacetype = SPACE_VIEW3D [static]
Definition at line 65 of file resources.c.
Referenced by UI_GetThemeColor3fv(), UI_GetThemeColor3ubv(), UI_GetThemeColor4ubv(), UI_GetThemeColorShade3fv(), UI_GetThemeValue(), UI_GetThemeValuef(), UI_SetTheme(), UI_ThemeColor(), UI_ThemeColor4(), UI_ThemeColorBlend(), UI_ThemeColorBlendShade(), UI_ThemeColorBlendShadeAlpha(), UI_ThemeColorShade(), and UI_ThemeColorShadeAlpha().