Blender: btConvexInternalAabbCachingShape Class Reference
btConvexInternalAabbCachingShape Class Reference
btConvexInternalAabbCachingShape adds local aabb caching for convex shapes, to avoid expensive bounding box calculations
#include <btConvexInternalShape.h>
Public Member Functions
virtual void setLocalScaling (const btVector3 &scaling)
virtual void getAabb (const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
void recalcLocalAabb ()
Protected Member Functions
btConvexInternalAabbCachingShape ()
void setCachedLocalAabb (const btVector3 &aabbMin, const btVector3 &aabbMax)
void getCachedLocalAabb (btVector3 &aabbMin, btVector3 &aabbMax) const
void getNonvirtualAabb (const btTransform &trans, btVector3 &aabbMin, btVector3 &aabbMax, btScalar margin) const
Detailed Description
btConvexInternalAabbCachingShape adds local aabb caching for convex shapes, to avoid expensive bounding box calculations
Definition at line 160 of file btConvexInternalShape.h.
Constructor & Destructor Documentation
btConvexInternalAabbCachingShape::btConvexInternalAabbCachingShape () [protected]
Definition at line 84 of file btConvexInternalShape.cpp.
Member Function Documentation
void btConvexInternalAabbCachingShape::getAabb (const btTransform & t, btVector3 & aabbMin, btVector3 & aabbMax) const [virtual]
getAabb's default implementation is brute force, expected derived classes to implement a fast dedicated version
Reimplemented from btConvexInternalShape.
Definition at line 93 of file btConvexInternalShape.cpp.
References btConvexInternalShape::getMargin(), and getNonvirtualAabb().
void btConvexInternalAabbCachingShape::getCachedLocalAabb (btVector3 & aabbMin, btVector3 & aabbMax) const [inline, protected]
Definition at line 177 of file btConvexInternalShape.h.
References btAssert.
Referenced by btMultiSphereShape::calculateLocalInertia().
void btConvexInternalAabbCachingShape::getNonvirtualAabb (const btTransform & trans, btVector3 & aabbMin, btVector3 & aabbMax, btScalar margin) const [inline, protected]
Definition at line 184 of file btConvexInternalShape.h.
References btAssert, and btTransformAabb().
Referenced by getAabb().
void btConvexInternalAabbCachingShape::recalcLocalAabb ()
Definition at line 105 of file btConvexInternalShape.cpp.
References i, btConvexInternalShape::localGetSupportingVertex(), and btConvexInternalShape::m_collisionMargin.
Referenced by btMultiSphereShape::btMultiSphereShape(), and setLocalScaling().
void btConvexInternalAabbCachingShape::setCachedLocalAabb (const btVector3 & aabbMin, const btVector3 & aabbMax) [inline, protected]
Definition at line 170 of file btConvexInternalShape.h.
void btConvexInternalAabbCachingShape::setLocalScaling (const btVector3 & scaling) [virtual]
Reimplemented from btConvexInternalShape.
Definition at line 98 of file btConvexInternalShape.cpp.
References recalcLocalAabb().
The documentation for this class was generated from the following files:
btConvexInternalShape.h
btConvexInternalShape.cpp