Blender: bsdf_refraction.h File Reference
bsdf_refraction.h File Reference
Classes
struct BsdfRefractionClosure
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct BsdfRefractionClosure BsdfRefractionClosure
Functions
__device void bsdf_refraction_setup (ShaderData *sd, ShaderClosure *sc, float eta)
__device void bsdf_refraction_blur (ShaderClosure *sc, float roughness)
__device float3 bsdf_refraction_eval_reflect (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float3 bsdf_refraction_eval_transmit (const ShaderData *sd, const ShaderClosure *sc, const float3 I, const float3 omega_in, float *pdf)
__device float bsdf_refraction_albedo (const ShaderData *sd, const ShaderClosure *sc, const float3 I)
__device int bsdf_refraction_sample (const ShaderData *sd, const ShaderClosure *sc, float randu, float randv, float3 *eval, float3 *omega_in, float3 *domega_in_dx, float3 *domega_in_dy, float *pdf)
Typedef Documentation
typedef CCL_NAMESPACE_BEGIN struct BsdfRefractionClosure BsdfRefractionClosure
Function Documentation
__device float bsdf_refraction_albedo (const ShaderData * sd, const ShaderClosure * sc, const float3 I)
Definition at line 66 of file bsdf_refraction.h.
__device void bsdf_refraction_blur (ShaderClosure * sc, float roughness)
Definition at line 52 of file bsdf_refraction.h.
Referenced by svm_bsdf_blur().
__device float3 bsdf_refraction_eval_reflect (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 56 of file bsdf_refraction.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device float3 bsdf_refraction_eval_transmit (const ShaderData * sd, const ShaderClosure * sc, const float3 I, const float3 omega_in, float * pdf)
Definition at line 61 of file bsdf_refraction.h.
References make_float3().
Referenced by svm_bsdf_eval().
__device int bsdf_refraction_sample (const ShaderData * sd, const ShaderClosure * sc, float randu, float randv, float3 * eval, float3 * omega_in, float3 * domega_in_dx, float3 * domega_in_dy, float * pdf)
Definition at line 71 of file bsdf_refraction.h.
References __RAY_DIFFERENTIALS__, ShaderClosure::data0, ShaderData::dI, differential3::dx, differential3::dy, fresnel_dielectric(), ShaderData::I, LABEL_SINGULAR, LABEL_TRANSMIT, make_float3(), ShaderData::N, R, and T.
Referenced by svm_bsdf_sample().
__device void bsdf_refraction_setup (ShaderData * sd, ShaderClosure * sc, float eta)
Definition at line 44 of file bsdf_refraction.h.
References CLOSURE_BSDF_REFRACTION_ID, ShaderClosure::data0, ShaderData::flag, SD_BSDF, and ShaderClosure::type.
Referenced by svm_node_glossy_setup().