Blender: btSolve2LinearConstraint Class Reference
btSolve2LinearConstraint Class Reference
constraint class used for lateral tyre friction.
#include <btSolve2LinearConstraint.h>
Public Member Functions
btSolve2LinearConstraint (btScalar tau, btScalar damping)
void resolveUnilateralPairConstraint (btRigidBody *body0, btRigidBody *body1, const btMatrix3x3 &world2A, const btMatrix3x3 &world2B, const btVector3 &invInertiaADiag, const btScalar invMassA, const btVector3 &linvelA, const btVector3 &angvelA, const btVector3 &rel_posA1, const btVector3 &invInertiaBDiag, const btScalar invMassB, const btVector3 &linvelB, const btVector3 &angvelB, const btVector3 &rel_posA2, btScalar depthA, const btVector3 &normalA, const btVector3 &rel_posB1, const btVector3 &rel_posB2, btScalar depthB, const btVector3 &normalB, btScalar &imp0, btScalar &imp1)
void resolveBilateralPairConstraint (btRigidBody *body0, btRigidBody *body1, const btMatrix3x3 &world2A, const btMatrix3x3 &world2B, const btVector3 &invInertiaADiag, const btScalar invMassA, const btVector3 &linvelA, const btVector3 &angvelA, const btVector3 &rel_posA1, const btVector3 &invInertiaBDiag, const btScalar invMassB, const btVector3 &linvelB, const btVector3 &angvelB, const btVector3 &rel_posA2, btScalar depthA, const btVector3 &normalA, const btVector3 &rel_posB1, const btVector3 &rel_posB2, btScalar depthB, const btVector3 &normalB, btScalar &imp0, btScalar &imp1)
Detailed Description
constraint class used for lateral tyre friction.
Definition at line 28 of file btSolve2LinearConstraint.h.
Constructor & Destructor Documentation
btSolve2LinearConstraint::btSolve2LinearConstraint (btScalar tau, btScalar damping) [inline]
Definition at line 35 of file btSolve2LinearConstraint.h.
Member Function Documentation
void btSolve2LinearConstraint::resolveBilateralPairConstraint (btRigidBody * body0, btRigidBody * body1, const btMatrix3x3 & world2A, const btMatrix3x3 & world2B, const btVector3 & invInertiaADiag, const btScalar invMassA, const btVector3 & linvelA, const btVector3 & angvelA, const btVector3 & rel_posA1, const btVector3 & invInertiaBDiag, const btScalar invMassB, const btVector3 & linvelB, const btVector3 & angvelB, const btVector3 & rel_posA2, btScalar depthA, const btVector3 & normalA, const btVector3 & rel_posB1, const btVector3 & rel_posB2, btScalar depthB, const btVector3 & normalB, btScalar & imp0, btScalar & imp1)
Definition at line 114 of file btSolve2LinearConstraint.cpp.
References btAssert, btFabs(), btRigidBody::getVelocityInLocalPoint(), len(), and SIMD_EPSILON.
void btSolve2LinearConstraint::resolveUnilateralPairConstraint (btRigidBody * body0, btRigidBody * body1, const btMatrix3x3 & world2A, const btMatrix3x3 & world2B, const btVector3 & invInertiaADiag, const btScalar invMassA, const btVector3 & linvelA, const btVector3 & angvelA, const btVector3 & rel_posA1, const btVector3 & invInertiaBDiag, const btScalar invMassB, const btVector3 & linvelB, const btVector3 & angvelB, const btVector3 & rel_posA2, btScalar depthA, const btVector3 & normalA, const btVector3 & rel_posB1, const btVector3 & rel_posB2, btScalar depthB, const btVector3 & normalB, btScalar & imp0, btScalar & imp1)
Definition at line 25 of file btSolve2LinearConstraint.cpp.
References btAssert, btFabs(), btRigidBody::getVelocityInLocalPoint(), len(), and SIMD_EPSILON.
The documentation for this class was generated from the following files:
btSolve2LinearConstraint.h
btSolve2LinearConstraint.cpp