Blender: kernel_montecarlo.h File Reference
kernel_montecarlo.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void to_unit_disk (float *x, float *y)
__device void make_orthonormals_tangent (const float3 N, const float3 T, float3 *a, float3 *b)
__device_inline void sample_cos_hemisphere (const float3 N, float randu, float randv, float3 *omega_in, float *pdf)
__device_inline void sample_uniform_hemisphere (const float3 N, float randu, float randv, float3 *omega_in, float *pdf)
__device float3 sample_uniform_sphere (float u1, float u2)
__device float power_heuristic (float a, float b)
__device float2 concentric_sample_disk (float u1, float u2)
__device float2 regular_polygon_sample (float corners, float rotation, float u, float v)
__device float2 direction_to_spherical (float3 dir)
__device float3 spherical_to_direction (float theta, float phi)
__device float2 direction_to_equirectangular (float3 dir)
__device float3 equirectangular_to_direction (float u, float v)
__device float3 mirrorball_to_direction (float u, float v)
__device float2 direction_to_mirrorball (float3 dir)
Function Documentation
__device float2 concentric_sample_disk (float u1, float u2)
Definition at line 121 of file kernel_montecarlo.h.
References cosf, M_PI_4_F, make_float2(), and sinf.
Referenced by camera_sample_aperture().
__device float2 direction_to_equirectangular (float3 dir)
Definition at line 208 of file kernel_montecarlo.h.
References atan2f, hypotf, M_PI_F, make_float2(), float3::x, float3::y, and float3::z.
Referenced by background_light_pdf(), and svm_node_tex_environment().
__device float2 direction_to_mirrorball (float3 dir)
Definition at line 244 of file kernel_montecarlo.h.
References div, make_float2(), max, sqrt(), float3::x, float3::y, and float3::z.
Referenced by svm_node_tex_environment().
__device float2 direction_to_spherical (float3 dir)
Definition at line 190 of file kernel_montecarlo.h.
References acosf, atan2f, make_float2(), float3::x, float3::y, and float3::z.
Referenced by sky_radiance().
__device float3 equirectangular_to_direction (float u, float v)
Definition at line 216 of file kernel_montecarlo.h.
References cos(), M_PI_F, make_float3(), and sin().
Referenced by background_light_sample(), camera_sample_environment(), and kernel_shader_evaluate().
__device void make_orthonormals_tangent (const float3 N, const float3 T, float3 * a, float3 * b)
Definition at line 70 of file kernel_montecarlo.h.
References cross().
Referenced by bsdf_ward_eval_reflect(), and bsdf_ward_sample().
__device float3 mirrorball_to_direction (float u, float v)
Definition at line 229 of file kernel_montecarlo.h.
References dot(), I, make_float3(), max, sqrt(), float3::x, float3::y, and float3::z.
__device float power_heuristic (float a, float b)
Definition at line 116 of file kernel_montecarlo.h.
Referenced by direct_emission(), indirect_background(), and indirect_emission().
__device float2 regular_polygon_sample (float corners, float rotation, float u, float v)
Definition at line 164 of file kernel_montecarlo.h.
References angle(), cosf, floorf, M_PI_F, make_float2(), p, sinf, sqrtf, float2::x, and float2::y.
Referenced by camera_sample_aperture().
__device_inline void sample_cos_hemisphere (const float3 N, float randu, float randv, float3 * omega_in, float * pdf)
Definition at line 76 of file kernel_montecarlo.h.
References B, M_1_PI_F, make_orthonormals(), max, N, sqrtf, T, and to_unit_disk().
Referenced by bsdf_diffuse_sample(), bsdf_translucent_sample(), bsdf_westin_sheen_sample(), kernel_path_integrate(), WestinSheenClosure::sample(), TranslucentClosure::sample(), and DiffuseClosure::sample().
__device_inline void sample_uniform_hemisphere (const float3 N, float randu, float randv, float3 * omega_in, float * pdf)
Definition at line 89 of file kernel_montecarlo.h.
References B, cosf, M_1_PI_F, M_PI_F, make_orthonormals(), max, N, sinf, sqrtf, and T.
Referenced by bsdf_ashikhmin_velvet_sample(), bsdf_oren_nayar_sample(), AshikhminVelvetClosure::sample(), and OrenNayarClosure::sample().
__device float3 sample_uniform_sphere (float u1, float u2)
Definition at line 105 of file kernel_montecarlo.h.
References cosf, fmaxf, M_PI_F, make_float3(), sinf, and sqrtf.
__device float3 spherical_to_direction (float theta, float phi)
Definition at line 198 of file kernel_montecarlo.h.
References cosf, make_float3(), and sinf.
CCL_NAMESPACE_BEGIN __device void to_unit_disk (float * x, float * y)
Given values x and y on [0,1], convert them in place to values on [-1,1] uniformly distributed over a unit sphere. This code is derived from Peter Shirley, "Realistic Ray Tracing", p. 103.
Definition at line 41 of file kernel_montecarlo.h.
References cosf, M_PI_4_F, and sinf.
Referenced by disk_light_sample(), and sample_cos_hemisphere().