Blender: node.c File Reference
node.c File Reference
blenkernel
#include "MEM_guardedalloc.h"
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <limits.h>
#include "DNA_action_types.h"
#include "DNA_anim_types.h"
#include "DNA_node_types.h"
#include "DNA_scene_types.h"
#include "BLI_string.h"
#include "BLI_math.h"
#include "BLI_listbase.h"
#include "BLI_path_util.h"
#include "BLI_utildefines.h"
#include "BLF_translation.h"
#include "BKE_animsys.h"
#include "BKE_action.h"
#include "BKE_fcurve.h"
#include "BKE_global.h"
#include "BKE_image.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_utildefines.h"
#include "RNA_access.h"
#include "NOD_socket.h"
#include "NOD_composite.h"
#include "NOD_shader.h"
#include "NOD_texture.h"
Classes
struct MakeLocalCallData
Typedefs
typedef struct MakeLocalCallData MakeLocalCallData
Functions
bNodeTreeType * ntreeGetType (int type)
static bNodeType * node_get_type (bNodeTree *ntree, int type)
bNodeType * ntreeGetNodeType (bNodeTree *ntree)
bNodeSocketType * ntreeGetSocketType (int type)
void ntreeInitTypes (bNodeTree *ntree)
static bNodeSocket * make_socket (bNodeTree *UNUSED(ntree), int in_out, const char *name, int type)
bNodeSocket * nodeAddSocket (bNodeTree *ntree, bNode *node, int in_out, const char *name, int type)
bNodeSocket * nodeInsertSocket (bNodeTree *ntree, bNode *node, int in_out, bNodeSocket *next_sock, const char *name, int type)
void nodeRemoveSocket (bNodeTree *ntree, bNode *node, bNodeSocket *sock)
void nodeRemoveAllSockets (bNodeTree *ntree, bNode *node)
bNode * nodeFindNodebyName (bNodeTree *ntree, const char *name)
int nodeFindNode (bNodeTree *ntree, bNodeSocket *sock, bNode **nodep, int *sockindex, int *in_out)
static void node_add_sockets_from_type (bNodeTree *ntree, bNode *node, bNodeType *ntype)
void nodeUniqueName (bNodeTree *ntree, bNode *node)
bNode * nodeAddNode (bNodeTree *ntree, struct bNodeTemplate *ntemp)
void nodeMakeDynamicType (bNode *node)
bNode * nodeCopyNode (struct bNodeTree *ntree, struct bNode *node)
bNodeLink * nodeAddLink (bNodeTree *ntree, bNode *fromnode, bNodeSocket *fromsock, bNode *tonode, bNodeSocket *tosock)
void nodeRemLink (bNodeTree *ntree, bNodeLink *link)
void nodeRemSocketLinks (bNodeTree *ntree, bNodeSocket *sock)
void nodeInternalRelink (bNodeTree *ntree, bNode *node)
void nodeSpaceCoords (bNode *node, float *locx, float *locy)
void nodeAttachNode (bNode *node, bNode *parent)
void nodeDetachNode (struct bNode *node)
bNodeTree * ntreeAddTree (const char *name, int type, int nodetype)
bNodeTree * ntreeCopyTree (bNodeTree *ntree)
void ntreeSwitchID (bNodeTree *ntree, ID *id_from, ID *id_to)
void nodeFreePreview (bNode *node)
static void node_init_preview (bNode *node, int xsize, int ysize)
void ntreeInitPreview (bNodeTree *ntree, int xsize, int ysize)
static void nodeClearPreview (bNode *node)
void ntreeClearPreview (bNodeTree *ntree)
void nodeAddToPreview (bNode *node, float *col, int x, int y, int do_manage)
void nodeUnlinkNode (bNodeTree *ntree, bNode *node)
static void node_unlink_attached (bNodeTree *ntree, bNode *parent)
void nodeFreeNode (bNodeTree *ntree, bNode *node)
void ntreeFreeTree (bNodeTree *ntree)
void ntreeFreeCache (bNodeTree *ntree)
void ntreeSetOutput (bNodeTree *ntree)
static void ntreeMakeLocal_CheckLocal (void *calldata, ID *owner_id, bNodeTree *ntree)
static void ntreeMakeLocal_LinkNew (void *calldata, ID *owner_id, bNodeTree *ntree)
void ntreeMakeLocal (bNodeTree *ntree)
int ntreeNodeExists (bNodeTree *ntree, bNode *testnode)
int ntreeOutputExists (bNode *node, bNodeSocket *testsock)
bNodeTree * ntreeLocalize (bNodeTree *ntree)
void ntreeLocalSync (bNodeTree *localtree, bNodeTree *ntree)
void ntreeLocalMerge (bNodeTree *localtree, bNodeTree *ntree)
int ntreeHasType (bNodeTree *ntree, int type)
bNodeLink * nodeFindLink (bNodeTree *ntree, bNodeSocket *from, bNodeSocket *to)
int nodeCountSocketLinks (bNodeTree *ntree, bNodeSocket *sock)
bNode * nodeGetActive (bNodeTree *ntree)
bNode * nodeGetActiveID (bNodeTree *ntree, short idtype)
int nodeSetActiveID (bNodeTree *ntree, short idtype, ID *id)
void nodeClearActiveID (bNodeTree *ntree, short idtype)
void nodeSetActive (bNodeTree *ntree, bNode *node)
int nodeSocketIsHidden (bNodeSocket *sock)
void nodeSocketSetType (bNodeSocket *sock, int type)
static int node_get_deplist_recurs (bNode *node, bNode ***nsort)
void ntreeGetDependencyList (struct bNodeTree *ntree, struct bNode ***deplist, int *totnodes)
static void ntree_update_node_level (bNodeTree *ntree)
static void ntree_update_link_pointers (bNodeTree *ntree)
static void ntree_validate_links (bNodeTree *ntree)
static void ntree_verify_nodes_cb (void *calldata, struct ID *UNUSED(owner_id), struct bNodeTree *ntree)
void ntreeVerifyNodes (struct Main *main, struct ID *id)
void ntreeUpdateTree (bNodeTree *ntree)
void nodeUpdate (bNodeTree *ntree, bNode *node)
int nodeUpdateID (bNodeTree *ntree, ID *id)
int nodeValid (bNodeTree *ntree, bNodeTemplate *ntemp)
const char * nodeLabel (bNode *node)
struct bNodeTree * nodeGroupEditGet (struct bNode *node)
struct bNodeTree * nodeGroupEditSet (struct bNode *node, int edit)
void nodeGroupEditClear (struct bNode *node)
struct bNodeTemplate nodeMakeTemplate (struct bNode *node)
void node_type_base (bNodeTreeType *ttype, bNodeType *ntype, int type, const char *name, short nclass, short flag)
void node_type_socket_templates (struct bNodeType *ntype, struct bNodeSocketTemplate *inputs, struct bNodeSocketTemplate *outputs)
void node_type_init (struct bNodeType *ntype, void(*initfunc)(struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp))
void node_type_valid (struct bNodeType *ntype, int(*validfunc)(struct bNodeTree *ntree, struct bNodeTemplate *ntemp))
void node_type_size (struct bNodeType *ntype, int width, int minwidth, int maxwidth)
void node_type_storage (bNodeType *ntype, const char *storagename, void(*freestoragefunc)(struct bNode *), void(*copystoragefunc)(struct bNode *, struct bNode *))
void node_type_label (struct bNodeType *ntype, const char *(*labelfunc)(struct bNode *))
void node_type_template (struct bNodeType *ntype, struct bNodeTemplate(*templatefunc)(struct bNode *))
void node_type_update (struct bNodeType *ntype, void(*updatefunc)(struct bNodeTree *ntree, struct bNode *node), void(*verifyfunc)(struct bNodeTree *ntree, struct bNode *node, struct ID *id))
void node_type_tree (struct bNodeType *ntype, void(*inittreefunc)(struct bNodeTree *), void(*updatetreefunc)(struct bNodeTree *))
void node_type_group_edit (struct bNodeType *ntype, struct bNodeTree *(*group_edit_get)(struct bNode *node), struct bNodeTree *(*group_edit_set)(struct bNode *node, int edit), void(*group_edit_clear)(struct bNode *node))
void node_type_exec (struct bNodeType *ntype, void(*execfunc)(void *data, struct bNode *, struct bNodeStack **, struct bNodeStack **))
void node_type_exec_new (struct bNodeType *ntype, void *(*initexecfunc)(struct bNode *node), void(*freeexecfunc)(struct bNode *node, void *nodedata), void(*newexecfunc)(void *data, int thread, struct bNode *, void *nodedata, struct bNodeStack **, struct bNodeStack **))
void node_type_internal_connect (bNodeType *ntype, ListBase(*internal_connect)(bNodeTree *, bNode *))
void node_type_gpu (struct bNodeType *ntype, int(*gpufunc)(struct GPUMaterial *mat, struct bNode *node, struct GPUNodeStack *in, struct GPUNodeStack *out))
void node_type_gpu_ext (struct bNodeType *ntype, int(*gpuextfunc)(struct GPUMaterial *mat, struct bNode *node, void *nodedata, struct GPUNodeStack *in, struct GPUNodeStack *out))
void node_type_compatibility (struct bNodeType *ntype, short compatibility)
static bNodeType * is_nodetype_registered (ListBase *typelist, int type)
void nodeRegisterType (bNodeTreeType *ttype, bNodeType *ntype)
static void registerCompositNodes (bNodeTreeType *ttype)
static void registerShaderNodes (bNodeTreeType *ttype)
static void registerTextureNodes (bNodeTreeType *ttype)
static void free_dynamic_typeinfo (bNodeType *ntype)
static void free_typeinfos (ListBase *list)
void init_nodesystem (void)
void free_nodesystem (void)
void clear_scene_in_nodes (Main *bmain, Scene *sce)
Detailed Description
Definition in file node.c.
Typedef Documentation
typedef struct MakeLocalCallData MakeLocalCallData
Function Documentation
void clear_scene_in_nodes (Main * bmain, Scene * sce)
Definition at line 2101 of file node.c.
References CMP_NODE_R_LAYERS, ListBase::first, bNode::id, Scene::id, if(), bNode::next, ID::next, bNodeTree::nodes, Scene::nodetree, NULL, Main::scene, and bNode::type.
Referenced by unlink_scene().
static void free_dynamic_typeinfo (bNodeType * ntype) [static]
Definition at line 2053 of file node.c.
References bNodeType::inputs, MEM_freeN(), bNodeType::name, NODE_DYNAMIC, bNodeType::outputs, and bNodeType::type.
Referenced by free_typeinfos().
void free_nodesystem (void)
Definition at line 2089 of file node.c.
References free_typeinfos(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, and ntreeGetType().
Referenced by free_blender(), and main().
static void free_typeinfos (ListBase * list) [static]
Definition at line 2068 of file node.c.
References ListBase::first, free_dynamic_typeinfo(), MEM_freeN(), bNodeType::needs_free, bNodeType::next, next, NODE_DYNAMIC, and bNodeType::type.
Referenced by free_nodesystem().
void init_nodesystem (void)
Definition at line 2082 of file node.c.
References NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeGetType(), registerCompositNodes(), registerShaderNodes(), and registerTextureNodes().
Referenced by main().
static bNodeType* is_nodetype_registered (ListBase * typelist, int type) [static]
Definition at line 1830 of file node.c.
References ListBase::first, bNodeType::next, NULL, and bNodeType::type.
Referenced by nodeRegisterType().
static bNodeSocket* make_socket (bNodeTree * UNUSEDntree, int in_out, const char * name, int type) [static]
Definition at line 160 of file node.c.
References BLI_strncpy(), bNodeSocket::default_value, bNodeSocket::limit, MEM_callocN(), bNodeSocket::name, NODE_MAXSTR, node_socket_init_default_value(), node_socket_make_default_value(), NULL, SOCK_IN, bNodeSocket::storage, and bNodeSocket::type.
Referenced by nodeAddSocket(), and nodeInsertSocket().
static void node_add_sockets_from_type (bNodeTree * ntree, bNode * node, bNodeType * ntype) [static]
Definition at line 289 of file node.c.
References bNodeType::inputs, node_add_input_from_template(), node_add_output_from_template(), bNodeType::outputs, and bNodeSocketTemplate::type.
Referenced by nodeAddNode().
static int node_get_deplist_recurs (bNode * node, bNode *** nsort) [static]
Definition at line 1389 of file node.c.
References bNode::done, ListBase::first, bNodeLink::fromnode, bNode::inputs, bNode::level, bNodeSocket::link, bNodeSocket::next, and bNode::parent.
Referenced by ntree_update_node_level(), and ntreeGetDependencyList().
static bNodeType* node_get_type (bNodeTree * ntree, int type) [static]
Definition at line 98 of file node.c.
References ListBase::first, bNodeType::next, bNodeTreeType::node_types, ntreeGetType(), NULL, bNodeTree::type, and bNodeType::type.
Referenced by nodeAddNode(), nodeValid(), ntreeAddTree(), ntreeGetNodeType(), ntreeInitTypes(), and ntreeUpdateTree().
static void node_init_preview (bNode * node, int xsize, int ysize) [static]
Definition at line 765 of file node.c.
References MEM_callocN(), MEM_freeN(), NULL, bNode::preview, bNodePreview::rect, bNodePreview::xsize, and bNodePreview::ysize.
Referenced by ntreeInitPreview().
void node_type_base (bNodeTreeType * ttype, bNodeType * ntype, int type, const char * name, short nclass, short flag)
Definition at line 1703 of file node.c.
References BLI_strncpy(), bNodeType::flag, FLT_MAX, bNodeType::height, bNodeType::internal_connect, bNodeTreeType::internal_connect, bNodeType::maxheight, bNodeType::maxwidth, bNodeType::minheight, bNodeType::minwidth, bNodeType::name, bNodeType::nclass, bNodeType::type, bNodeTemplate::type, and bNodeType::width.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_dynamic(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_compatibility (struct bNodeType * ntype, short compatibility)
Definition at line 1825 of file node.c.
References bNodeType::compatibility.
Referenced by register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_dynamic(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), and register_node_type_sh_volume_transparent().
void node_type_exec (struct bNodeType * ntype, void(*)(void *data, struct bNode *, struct bNodeStack **, struct bNodeStack **) execfunc)
Definition at line 1795 of file node.c.
References bNodeType::execfunc.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_exec_new (struct bNodeType * ntype, void *(*)(struct bNode *node) initexecfunc, void(*)(struct bNode *node, void *nodedata) freeexecfunc, void(*)(void *data, int thread, struct bNode *, void *nodedata, struct bNodeStack **, struct bNodeStack **) newexecfunc)
Definition at line 1800 of file node.c.
References bNodeType::freeexecfunc, bNodeType::initexecfunc, and bNodeType::newexecfunc.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_gpu (struct bNodeType * ntype, int(*)(struct GPUMaterial *mat, struct bNode *node, struct GPUNodeStack *in, struct GPUNodeStack *out) gpufunc)
Definition at line 1815 of file node.c.
References bNodeType::gpufunc.
Referenced by register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), and register_node_type_sh_volume_transparent().
void node_type_gpu_ext (struct bNodeType * ntype, int(*)(struct GPUMaterial *mat, struct bNode *node, void *nodedata, struct GPUNodeStack *in, struct GPUNodeStack *out) gpuextfunc)
Definition at line 1820 of file node.c.
References bNodeType::gpuextfunc.
Referenced by register_node_type_sh_group().
void node_type_group_edit (struct bNodeType * ntype, struct bNodeTree *(*)(struct bNode *node) group_edit_get, struct bNodeTree *(*)(struct bNode *node, int edit) group_edit_set, void(*)(struct bNode *node) group_edit_clear)
Definition at line 1785 of file node.c.
References bNodeType::group_edit_clear, bNodeType::group_edit_get, and bNodeType::group_edit_set.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_init (struct bNodeType * ntype, void(*)(struct bNodeTree *ntree, struct bNode *node, struct bNodeTemplate *ntemp) initfunc)
Definition at line 1731 of file node.c.
References bNodeType::initfunc.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_distance_matte(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_movieclip(), register_node_type_cmp_normal(), register_node_type_cmp_output_file(), register_node_type_cmp_rgb(), register_node_type_cmp_rotate(), register_node_type_cmp_splitviewer(), register_node_type_cmp_tonemap(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_bricks(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_group(), register_node_type_tex_image(), register_node_type_tex_output(), and register_node_type_tex_valtorgb().
void node_type_internal_connect (bNodeType * ntype, ListBase(*)(bNodeTree *, bNode *) internal_connect)
Definition at line 1810 of file node.c.
References bNodeType::internal_connect.
void node_type_label (struct bNodeType * ntype, const char *(*)(struct bNode *) labelfunc)
Definition at line 1761 of file node.c.
References bNodeType::labelfunc.
Referenced by register_node_type_cmp_filter(), register_node_type_cmp_group(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_moviedistortion(), register_node_type_sh_group(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_vect_math(), register_node_type_tex_group(), register_node_type_tex_math(), and register_node_type_tex_mix_rgb().
void node_type_size (struct bNodeType * ntype, int width, int minwidth, int maxwidth)
Definition at line 1741 of file node.c.
References FLT_MAX, bNodeType::maxwidth, bNodeType::minwidth, and bNodeType::width.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_socket_templates (struct bNodeType * ntype, struct bNodeSocketTemplate * inputs, struct bNodeSocketTemplate * outputs)
Definition at line 1725 of file node.c.
References inputs, bNodeType::inputs, bNodeType::outputs, and outputs.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void node_type_storage (bNodeType * ntype, const char * storagename, void(*)(struct bNode *) freestoragefunc, void(*)(struct bNode *, struct bNode *) copystoragefunc)
Definition at line 1751 of file node.c.
References BLI_strncpy(), bNodeType::copystoragefunc, bNodeType::freestoragefunc, and bNodeType::storagename.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_distance_matte(), register_node_type_cmp_glare(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_image(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_output_file(), register_node_type_cmp_splitviewer(), register_node_type_cmp_tonemap(), register_node_type_cmp_valtorgb(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_holdout(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_math(), register_node_type_sh_mix_shader(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_valtorgb(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_distance(), register_node_type_tex_image(), register_node_type_tex_math(), register_node_type_tex_output(), and register_node_type_tex_valtorgb().
void node_type_template (struct bNodeType * ntype, struct bNodeTemplate(*)(struct bNode *) templatefunc)
Definition at line 1766 of file node.c.
References bNodeType::templatefunc.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_tree (struct bNodeType * ntype, void(*)(struct bNodeTree *) inittreefunc, void(*)(struct bNodeTree *) updatetreefunc)
Definition at line 1779 of file node.c.
References bNodeType::inittreefunc, and bNodeType::updatetreefunc.
void node_type_update (struct bNodeType * ntype, void(*)(struct bNodeTree *ntree, struct bNode *node) updatefunc, void(*)(struct bNodeTree *ntree, struct bNode *node, struct ID *id) verifyfunc)
Definition at line 1771 of file node.c.
References bNodeType::updatefunc, and bNodeType::verifyfunc.
Referenced by register_node_type_cmp_group(), register_node_type_cmp_image(), register_node_type_cmp_output_file(), register_node_type_sh_group(), and register_node_type_tex_group().
void node_type_valid (struct bNodeType * ntype, int(*)(struct bNodeTree *ntree, struct bNodeTemplate *ntemp) validfunc)
Definition at line 1736 of file node.c.
References bNodeType::validfunc.
Referenced by register_node_type_cmp_group(), register_node_type_sh_group(), and register_node_type_tex_group().
static void node_unlink_attached (bNodeTree * ntree, bNode * parent) [static]
Definition at line 888 of file node.c.
References ListBase::first, bNode::next, nodeDetachNode(), bNodeTree::nodes, and bNode::parent.
Referenced by nodeFreeNode().
bNodeLink* nodeAddLink (bNodeTree * ntree, bNode * fromnode, bNodeSocket * fromsock, bNode * tonode, bNodeSocket * tosock) [read]
Definition at line 433 of file node.c.
References BLI_addtail(), ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNodeTree::inputs, bNode::inputs, link(), bNodeTree::links, MEM_callocN(), bNodeSocket::next, NTREE_UPDATE_LINKS, NULL, bNodeTree::outputs, bNode::outputs, bNodeLink::tonode, bNodeLink::tosock, and bNodeTree::update.
Referenced by ED_node_composit_default(), ED_node_link_insert(), ED_node_shader_default(), ED_node_texture_default(), node_group_expose_all_sockets(), node_group_make_from_selected(), node_link_viewer(), node_socket_add_replace(), and snode_autoconnect_input().
bNode* nodeAddNode (bNodeTree * ntree, struct bNodeTemplate * ntemp) [read]
Definition at line 318 of file node.c.
References BLI_addtail(), BLI_strncpy(), bNodeType::flag, bNode::flag, bNodeType::height, bNode::height, bNodeType::initfunc, MEM_callocN(), bNode::miniwidth, bNode::name, node_add_sockets_from_type(), node_get_type(), NODE_MAXSTR, NODE_SELECT, nodeLabel(), bNodeTree::nodes, nodeUniqueName(), nodeValid(), NTREE_UPDATE_NODES, NULL, bNodeType::type, bNode::type, bNodeTemplate::type, bNode::typeinfo, bNodeTree::update, bNodeType::width, and bNode::width.
Referenced by ED_node_composit_default(), ED_node_shader_default(), ED_node_texture_default(), node_add_node(), node_group_make_from_selected(), and node_socket_add_replace().
bNodeSocket* nodeAddSocket (bNodeTree * ntree, bNode * node, int in_out, const char * name, int type) [read]
Definition at line 177 of file node.c.
References BLI_addtail(), bNode::inputs, make_socket(), NODE_UPDATE, bNode::outputs, SOCK_IN, SOCK_OUT, and bNode::update.
Referenced by cmp_node_image_add_multilayer_outputs(), node_add_input_from_template(), node_add_output_from_template(), node_forloop_init(), node_whileloop_init(), and ntreeCompositOutputFileAddSocket().
void nodeAddToPreview (bNode * node, float * col, int x, int y, int do_manage)
Definition at line 833 of file node.c.
References linearrgb_to_srgb_uchar4(), bNode::preview, bNodePreview::rect, rgba_float_to_uchar(), and bNodePreview::xsize.
Referenced by node_shader_exec_material(), node_shader_exec_output(), node_shader_exec_texture(), and tex_do_preview().
void nodeAttachNode (bNode * node, bNode * parent)
Definition at line 608 of file node.c.
References bNode::locx, bNode::locy, nodeSpaceCoords(), and bNode::parent.
Referenced by node_frame_attach_nodes().
void nodeClearActiveID (bNodeTree * ntree, short idtype)
Definition at line 1333 of file node.c.
References ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNode::next, NODE_ACTIVE_ID, bNodeTree::nodes, and NULL.
Referenced by ED_node_set_active().
static void nodeClearPreview (bNode * node) [static]
Definition at line 808 of file node.c.
References MEM_allocN_len(), bNode::preview, and bNodePreview::rect.
Referenced by ntreeClearPreview().
bNode* nodeCopyNode (struct bNodeTree * ntree, struct bNode * node) [read]
Definition at line 378 of file node.c.
References BLI_addtail(), BLI_duplicatelist(), bNodeSocket::cache, bNodeType::copystoragefunc, bNodeSocket::default_value, ListBase::first, bNode::inputs, MEM_callocN(), bNode::new_node, bNodeSocket::new_sock, bNodeSocket::next, node_socket_copy_default_value(), node_socket_make_default_value(), bNodeTree::nodes, nodeUniqueName(), NTREE_UPDATE_NODES, NULL, bNode::outputs, bNode::preview, bNodeSocket::stack_index, bNodeSocket::type, bNode::typeinfo, and bNodeTree::update.
Referenced by node_duplicate_exec(), and ntreeCopyTree().
int nodeCountSocketLinks (bNodeTree * ntree, bNodeSocket * sock)
Definition at line 1252 of file node.c.
References ListBase::first, bNodeLink::fromsock, link(), bNodeTree::links, bNodeLink::next, and bNodeLink::tosock.
Referenced by node_group_expose_all_sockets(), node_link_init(), node_link_modal(), node_remove_extra_links(), node_set_hidden_sockets(), and node_socket_add_replace().
void nodeDetachNode (struct bNode * node)
Definition at line 619 of file node.c.
References bNode::locx, bNode::locy, nodeSpaceCoords(), NULL, and bNode::parent.
Referenced by ED_node_update_hierarchy(), node_frame_attach_nodes(), and node_unlink_attached().
bNodeLink* nodeFindLink (bNodeTree * ntree, bNodeSocket * from, bNodeSocket * to) [read]
Definition at line 1239 of file node.c.
References ListBase::first, bNodeLink::fromsock, link(), bNodeTree::links, bNodeLink::next, NULL, and bNodeLink::tosock.
Referenced by node_link_modal().
int nodeFindNode (bNodeTree * ntree, bNodeSocket * sock, bNode ** nodep, int * sockindex, int * in_out)
Definition at line 253 of file node.c.
References ListBase::first, bNode::inputs, bNodeSocket::next, bNode::next, bNodeTree::nodes, NULL, bNode::outputs, SOCK_IN, and SOCK_OUT.
bNode* nodeFindNodebyName (bNodeTree * ntree, const char * name) [read]
Definition at line 247 of file node.c.
References BLI_findstring(), and bNodeTree::nodes.
Referenced by animchan_sync_fcurve(), and skip_fcurve_selected_data().
void nodeFreeNode (bNodeTree * ntree, bNode * node)
Definition at line 897 of file node.c.
References BLI_remlink(), bNodeSocket::default_value, ListBase::first, bNodeTreeType::free_node_cache, bNodeType::freestoragefunc, bNode::inputs, MEM_freeN(), bNodeSocket::next, node_socket_free_default_value(), node_unlink_attached(), nodeFreePreview(), bNodeTree::nodes, nodeUnlinkNode(), NTREE_UPDATE_NODES, ntreeGetType(), bNode::outputs, bNodeSocket::type, bNodeTree::type, bNode::typeinfo, and bNodeTree::update.
Referenced by localize(), node_delete_exec(), node_delete_reconnect_exec(), node_group_ungroup(), node_remove_linked(), ntreeFreeTree(), and ntreeInitTypes().
void nodeFreePreview (bNode * node)
Definition at line 755 of file node.c.
References MEM_freeN(), NULL, bNode::preview, and bNodePreview::rect.
Referenced by local_sync(), nodeFreeNode(), and ntreeLocalMerge().
bNode* nodeGetActive (bNodeTree * ntree) [read]
Definition at line 1264 of file node.c.
References ListBase::first, bNode::flag, bNode::next, NODE_ACTIVE, bNodeTree::nodes, and NULL.
Referenced by active_node_panel(), active_node_poll(), editnode_get_active(), node_group_edit_exec(), node_group_edit_invoke(), node_group_ungroup_exec(), node_output_file_add_socket_exec(), node_output_file_remove_active_socket_exec(), node_sockets_panel(), and snode_make_group_editable().
bNode* nodeGetActiveID (bNodeTree * ntree, short idtype) [read]
Definition at line 1277 of file node.c.
References ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNode::next, NODE_ACTIVE_ID, NODE_GROUP_EDIT, bNodeTree::nodes, and NULL.
Referenced by give_current_material_texture(), give_current_material_texture_node(), give_node_material(), gpu_active_node_material(), has_current_material_texture(), and set_current_material_texture().
void nodeGroupEditClear (struct bNode * node)
Definition at line 1686 of file node.c.
References bNodeType::group_edit_clear, and bNode::typeinfo.
Referenced by node_group_edit_clear(), and snode_make_group_editable().
struct bNodeTree* nodeGroupEditGet (struct bNode * node) [read]
Definition at line 1668 of file node.c.
References bNodeType::group_edit_get, NULL, and bNode::typeinfo.
Referenced by editnode_get_active(), node_tree_from_ID(), and node_tree_get_editgroup().
struct bNodeTree* nodeGroupEditSet (struct bNode * node, int edit) [read]
Definition at line 1676 of file node.c.
References bNodeType::group_edit_get, bNodeType::group_edit_set, NULL, and bNode::typeinfo.
Referenced by snode_make_group_editable().
bNodeSocket* nodeInsertSocket (bNodeTree * ntree, bNode * node, int in_out, bNodeSocket * next_sock, const char * name, int type) [read]
Definition at line 190 of file node.c.
References BLI_insertlinkbefore(), bNode::inputs, make_socket(), NODE_UPDATE, bNode::outputs, SOCK_IN, SOCK_OUT, and bNode::update.
void nodeInternalRelink (bNodeTree * ntree, bNode * node)
Definition at line 545 of file node.c.
References BLI_freelistN(), ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNodeType::internal_connect, link(), bNodeSocket::link, bNodeTree::links, bNodeLink::next, nodeRemLink(), NTREE_UPDATE_LINKS, bNodeLink::tonode, bNodeLink::tosock, bNode::typeinfo, and bNodeTree::update.
Referenced by detach_links_exec(), localize(), and node_delete_reconnect_exec().
const char* nodeLabel (bNode * node)
Definition at line 1658 of file node.c.
References IFACE_, bNode::label, bNodeType::labelfunc, bNodeType::name, and bNode::typeinfo.
Referenced by node_draw_basis(), node_draw_hidden(), and nodeAddNode().
void nodeMakeDynamicType (bNode * node)
Definition at line 356 of file node.c.
References BLI_strncpy(), ListBase::first, MEM_callocN(), bNodeType::name, bNodeType::next, NODE_DYNAMIC, bNodeTreeType::node_types, NTREE_SHADER, ntreeGetType(), bNodeType::type, and bNode::typeinfo.
struct bNodeTemplate nodeMakeTemplate (struct bNode * node) [read]
Definition at line 1692 of file node.c.
References bNodeTemplate::type.
Referenced by node_group_valid().
void nodeRegisterType (bNodeTreeType * ttype, bNodeType * ntype)
Definition at line 1841 of file node.c.
References BLI_addtail(), is_nodetype_registered(), bNodeTreeType::node_types, NULL, and bNodeType::type.
Referenced by register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_anisotropic(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_dynamic(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), register_node_type_sh_vect_math(), register_node_type_sh_volume_isotropic(), register_node_type_sh_volume_transparent(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
void nodeRemLink (bNodeTree * ntree, bNodeLink * link)
Definition at line 521 of file node.c.
References BLI_remlink(), bNodeSocket::link, bNodeTree::links, MEM_freeN(), NTREE_UPDATE_LINKS, NULL, bNodeLink::tosock, and bNodeTree::update.
Referenced by cut_links_exec(), node_group_ungroup(), node_link_cancel(), node_link_init(), node_link_modal(), node_link_viewer(), node_remove_extra_links(), node_socket_add_replace(), node_socket_disconnect(), nodeInternalRelink(), nodeRemoveAllSockets(), nodeRemoveSocket(), nodeRemSocketLinks(), nodeUnlinkNode(), and snode_autoconnect_input().
void nodeRemoveAllSockets (bNodeTree * ntree, bNode * node)
Definition at line 224 of file node.c.
References BLI_freelistN(), bNodeSocket::default_value, ListBase::first, bNodeLink::fromnode, bNode::inputs, link(), bNodeTree::links, bNodeSocket::next, bNodeLink::next, next, node_socket_free_default_value(), NODE_UPDATE, nodeRemLink(), bNode::outputs, bNodeLink::tonode, bNodeSocket::type, and bNode::update.
void nodeRemoveSocket (bNodeTree * ntree, bNode * node, bNodeSocket * sock)
Definition at line 203 of file node.c.
References BLI_remlink(), bNodeSocket::default_value, ListBase::first, bNodeLink::fromsock, bNode::inputs, link(), bNodeTree::links, MEM_freeN(), bNodeLink::next, next, node_socket_free_default_value(), NODE_UPDATE, nodeRemLink(), bNode::outputs, bNodeLink::tosock, bNodeSocket::type, and bNode::update.
Referenced by cmp_node_image_verify_outputs(), do_versions_nodetree_multi_file_output_format_2_62_1(), group_verify_socket_list(), ntreeCompositOutputFileRemoveActiveSocket(), and verify_socket_template_list().
void nodeRemSocketLinks (bNodeTree * ntree, bNodeSocket * sock)
Definition at line 531 of file node.c.
References ListBase::first, bNodeLink::fromsock, link(), bNodeTree::links, bNodeLink::next, next, nodeRemLink(), NTREE_UPDATE_LINKS, bNodeLink::tosock, and bNodeTree::update.
Referenced by node_group_remove_socket(), and snode_autoconnect_input().
void nodeSetActive (bNodeTree * ntree, bNode * node)
Definition at line 1345 of file node.c.
References ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNodeType::nclass, bNode::next, NODE_ACTIVE, NODE_ACTIVE_ID, NODE_ACTIVE_TEXTURE, NODE_CLASS_TEXTURE, bNodeTree::nodes, and bNode::typeinfo.
Referenced by ED_node_composit_default(), ED_node_set_active(), ED_node_shader_default(), ED_node_texture_default(), node_browse_text_cb(), node_group_make_exec(), and node_socket_add_replace().
int nodeSetActiveID (bNodeTree * ntree, short idtype, ID * id)
Definition at line 1300 of file node.c.
References FALSE, ListBase::first, bNode::flag, GS, bNode::id, ID::name, bNode::next, NODE_ACTIVE_ID, NODE_GROUP_EDIT, bNodeTree::nodes, NULL, and TRUE.
Referenced by node_area_listener().
int nodeSocketIsHidden (bNodeSocket * sock)
Definition at line 1368 of file node.c.
References bNodeSocket::flag, SOCK_HIDDEN, and SOCK_UNAVAIL.
Referenced by node_draw_basis(), node_draw_hidden(), node_find_indicated_socket(), node_group_expose_all_sockets(), node_link_viewer(), node_update_basis(), node_update_hidden(), nodeShaderSynchronizeID(), socket_best_match(), and socket_is_available().
void nodeSocketSetType (bNodeSocket * sock, int type)
Definition at line 1373 of file node.c.
References bNodeSocket::default_value, node_socket_convert_default_value(), node_socket_free_default_value(), node_socket_init_default_value(), node_socket_make_default_value(), and bNodeSocket::type.
Referenced by update_output_file().
void nodeSpaceCoords (bNode * node, float * locx, float * locy)
Definition at line 595 of file node.c.
References bNode::locx, bNode::locy, nodeSpaceCoords(), and bNode::parent.
Referenced by node_update_basis(), node_update_frame(), node_update_group(), node_update_hidden(), nodeAttachNode(), nodeDetachNode(), and nodeSpaceCoords().
void nodeUniqueName (bNodeTree * ntree, bNode * node)
Definition at line 313 of file node.c.
References BLI_uniquename(), bNode::name, bNodeSocket::name, and bNodeTree::nodes.
Referenced by do_versions(), nodeAddNode(), and nodeCopyNode().
void nodeUnlinkNode (bNodeTree * ntree, bNode * node)
Definition at line 857 of file node.c.
References ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, bNode::inputs, link(), bNodeTree::links, bNodeSocket::next, bNodeLink::next, next, NODE_UPDATE, nodeRemLink(), NULL, bNode::outputs, bNodeLink::tonode, bNodeLink::tosock, and bNode::update.
Referenced by nodeFreeNode().
void nodeUpdate (bNodeTree * ntree, bNode * node)
Definition at line 1592 of file node.c.
References ntreeGetType(), bNodeTree::type, bNode::typeinfo, bNode::update, bNodeTreeType::update_node, and bNodeType::updatefunc.
Referenced by dag_id_flush_update(), dag_tag_renderlayers(), ED_node_changed_update(), node_animation_properties(), node_socket_add_replace(), node_socket_disconnect(), node_socket_remove(), ntree_render_scenes(), ntreeCompositForceHidden(), ntreeCompositTagAnimated(), ntreeCompositTagGenerators(), ntreeCompositTagRender(), ntreeTexTagAnimated(), and snode_update().
int nodeUpdateID (bNodeTree * ntree, ID * id)
Definition at line 1604 of file node.c.
References ELEM, FALSE, ListBase::first, bNode::id, bNode::next, NODE_UPDATE_ID, bNodeTree::nodes, ntreeGetType(), NULL, TRUE, bNodeTree::type, bNode::typeinfo, bNode::update, bNodeTreeType::update_node, and bNodeType::updatefunc.
Referenced by BKE_image_signal(), ED_node_changed_update(), node_area_listener(), render_endjob(), snode_update(), and special_aftertrans_update().
int nodeValid (bNodeTree * ntree, bNodeTemplate * ntemp)
Definition at line 1645 of file node.c.
References node_get_type(), bNodeTemplate::type, and bNodeType::validfunc.
Referenced by node_group_valid(), and nodeAddNode().
static void ntree_update_link_pointers (bNodeTree * ntree) [static]
Definition at line 1470 of file node.c.
References ListBase::first, bNodeSocket::flag, bNodeLink::fromsock, bNodeTree::inputs, bNode::inputs, link(), bNodeSocket::link, bNodeTree::links, bNodeSocket::next, bNode::next, bNodeLink::next, bNodeTree::nodes, NULL, bNode::outputs, bNodeTree::outputs, SOCK_IN_USE, and bNodeLink::tosock.
Referenced by ntreeUpdateTree().
static void ntree_update_node_level (bNodeTree * ntree) [static]
Definition at line 1453 of file node.c.
References bNode::done, ListBase::first, bNode::level, bNode::next, node_get_deplist_recurs(), bNodeTree::nodes, and NULL.
Referenced by ntreeUpdateTree().
static void ntree_validate_links (bNodeTree * ntree) [static]
Definition at line 1502 of file node.c.
References ListBase::first, bNodeLink::flag, bNodeLink::fromnode, bNode::level, link(), bNodeTree::links, bNodeLink::next, NODE_LINK_VALID, ntreeGetType(), bNodeLink::tonode, bNodeTree::type, and bNodeTreeType::validate_link.
Referenced by ntreeUpdateTree().
static void ntree_verify_nodes_cb (void * calldata, struct ID * UNUSEDowner_id, struct bNodeTree * ntree) [static]
Definition at line 1518 of file node.c.
References ListBase::first, bNode::next, bNodeTree::nodes, bNode::typeinfo, and bNodeType::verifyfunc.
Referenced by ntreeVerifyNodes().
bNodeTree* ntreeAddTree (const char * name, int type, int nodetype) [read]
Definition at line 632 of file node.c.
References alloc_libblock(), BLI_strncpy(), ELEM3, G, bNodeTree::id, ID_NT, bNodeType::inittreefunc, MEM_callocN(), ID::name, node_get_type(), bNodeTree::nodetype, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeInitTypes(), bNodeSocket::type, and bNodeTree::type.
Referenced by do_node_add_group(), ED_node_composit_default(), ED_node_shader_default(), ED_node_texture_default(), new_node_tree_exec(), and node_group_make_from_selected().
void ntreeClearPreview (bNodeTree * ntree)
Definition at line 815 of file node.c.
References ListBase::first, bNode::flag, bNodeType::flag, bNode::id, bNode::next, NODE_GROUP, NODE_GROUP_EDIT, NODE_PREVIEW, nodeClearPreview(), bNodeTree::nodes, ntreeClearPreview(), NULL, bNode::type, and bNode::typeinfo.
Referenced by ntreeClearPreview().
bNodeTree* ntreeCopyTree (bNodeTree * ntree) [read]
Definition at line 665 of file node.c.
References BLI_duplicatelist(), copy_libblock(), copy_libblock_data(), bNodeSocket::default_value, bNodeTree::execdata, ListBase::first, bNodeLink::fromnode, bNodeLink::fromsock, G, bNodeTree::gpd, bNodeSocket::groupsock, bNodeTree::id, id_us_plus(), bNodeTree::inputs, ListBase::last, bNodeSocket::link, link(), bNodeTree::links, MEM_dupallocN(), bNode::new_node, bNodeSocket::new_sock, bNodeLink::next, bNodeSocket::next, bNode::next, ID::next, node_socket_copy_default_value(), node_socket_make_default_value(), nodeCopyNode(), bNodeTree::nodes, NULL, bNodeTree::outputs, bNode::parent, bNodeLink::tonode, bNodeLink::tosock, TRUE, and bNodeSocket::type.
Referenced by copy_lamp(), copy_matcopybuf(), copy_material(), copy_scene(), copy_texture(), copy_world(), id_copy(), node_group_ungroup(), ntreeLocalize(), ntreeMakeLocal(), and paste_matcopybuf().
void ntreeFreeCache (bNodeTree * ntree)
Definition at line 980 of file node.c.
References bNodeTreeType::free_cache, ntreeGetType(), NULL, and bNodeTree::type.
Referenced by do_render_composite_fields_blur_3d(), and node_group_make_from_selected().
void ntreeFreeTree (bNodeTree * ntree)
Definition at line 935 of file node.c.
References BKE_free_animdata(), BLI_freelistN(), bNodeSocket::default_value, bNodeTree::execdata, id_us_min(), bNodeSocket::next, bNode::next, next, node_socket_free_default_value(), nodeFreeNode(), NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeCompositEndExecTree(), ntreeShaderEndExecTree(), ntreeTexEndExecTree(), NULL, bNodeSocket::type, and bNodeTree::type.
Referenced by free_lamp(), free_libblock(), free_matcopybuf(), free_material(), free_scene(), free_texture(), free_world(), ntreeLocalMerge(), and paste_matcopybuf().
void ntreeGetDependencyList (struct bNodeTree * ntree, struct bNode *** deplist, int * totnodes)
Definition at line 1426 of file node.c.
References bNode::done, ListBase::first, bNode::level, MEM_callocN(), bNode::next, node_get_deplist_recurs(), bNodeTree::nodes, and NULL.
Referenced by ntree_exec_begin().
bNodeType* ntreeGetNodeType (bNodeTree * ntree) [read]
Definition at line 108 of file node.c.
References node_get_type(), and bNodeTree::nodetype.
bNodeSocketType* ntreeGetSocketType (int type) [read]
Definition at line 113 of file node.c.
References node_socket_type_init(), NULL, NUM_SOCKET_TYPES, bNodeSocket::type, and types.
Referenced by draw_group_socket(), ED_init_node_butfuncs(), node_draw_basis(), node_group_add_socket(), node_socket_circle_draw(), node_socket_make_default_value(), and write_node_socket().
bNodeTreeType* ntreeGetType (int type) [read]
Definition at line 79 of file node.c.
References NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, ntreeType_Composite, ntreeType_Shader, ntreeType_Texture, NULL, NUM_NTREE_TYPES, bNodeSocket::type, and types.
Referenced by do_versions(), ED_init_node_butfuncs(), ED_node_generic_update(), free_nodesystem(), init_nodesystem(), lib_verify_nodetree(), node_add_menu(), node_get_type(), node_menu_add(), node_tree_has_type(), nodeFreeNode(), nodeMakeDynamicType(), nodeUpdate(), nodeUpdateID(), ntree_validate_links(), ntreeFreeCache(), ntreeLocalize(), ntreeLocalMerge(), ntreeLocalSync(), ntreeMakeLocal(), ntreeUpdateTree(), ntreeVerifyNodes(), ui_node_menu_column(), and ui_template_node_link_menu().
int ntreeHasType (bNodeTree * ntree, int type)
Definition at line 1228 of file node.c.
References ListBase::first, bNode::next, bNodeTree::nodes, and bNode::type.
Referenced by setExecutableNodes().
void ntreeInitPreview (bNodeTree * ntree, int xsize, int ysize)
Definition at line 793 of file node.c.
References ListBase::first, bNode::flag, bNodeType::flag, bNode::id, bNode::next, NODE_GROUP, NODE_GROUP_EDIT, node_init_preview(), NODE_PREVIEW, bNodeTree::nodes, ntreeInitPreview(), NULL, bNode::type, and bNode::typeinfo.
Referenced by ntreeCompositExecTree(), ntreeInitPreview(), and preview_prepare_scene().
void ntreeInitTypes (bNodeTree * ntree)
Definition at line 131 of file node.c.
References BSET, bNode::custom1, ListBase::first, bNode::id, bNodeTree::init, bNode::name, bNode::next, next, NODE_DYNAMIC, NODE_DYNAMIC_ADDEXIST, node_get_type(), nodeFreeNode(), bNodeTree::nodes, NTREE_TYPE_INIT, NULL, bNode::storage, bNode::type, and bNode::typeinfo.
Referenced by lib_nodetree_init_types_cb(), ntree_exec_begin(), and ntreeAddTree().
bNodeTree* ntreeLocalize (bNodeTree * ntree) [read]
Definition at line 1140 of file node.c.
References AnimData::action, BKE_animdata_from_id(), ListBase::first, bAction::id, bNodeTree::id, bNodeTreeType::localize, bNode::new_node, bNode::next, bNodeTree::nodes, ntreeCopyTree(), ntreeGetType(), ntreeSetOutput(), NULL, AnimData::tmpact, bNodeTree::type, and ID::us.
Referenced by compo_initjob(), localize_lamp(), localize_material(), localize_texture(), and localize_world().
void ntreeLocalMerge (bNodeTree * localtree, bNodeTree * ntree)
Definition at line 1203 of file node.c.
References ListBase::first, bNodeTreeType::local_merge, MEM_freeN(), bNode::new_node, bNode::next, nodeFreePreview(), bNodeTree::nodes, ntreeFreeTree(), ntreeGetType(), ntreeNodeExists(), NULL, bNode::preview, bNodePreview::rect, and bNodeTree::type.
Referenced by compo_freejob().
void ntreeLocalSync (bNodeTree * localtree, bNodeTree * ntree)
Definition at line 1193 of file node.c.
References bNodeTreeType::local_sync, ntreeGetType(), and bNodeTree::type.
Referenced by compo_updatejob(), and shader_preview_updatejob().
void ntreeMakeLocal (bNodeTree * ntree)
Definition at line 1080 of file node.c.
References bNodeTreeType::foreach_nodetree, G, MakeLocalCallData::group_id, bNodeTree::id, id_clear_lib_data(), MakeLocalCallData::lib, ID::lib, MakeLocalCallData::local, MakeLocalCallData::new_id, ntreeCopyTree(), ntreeGetType(), ntreeMakeLocal_CheckLocal(), ntreeMakeLocal_LinkNew(), NULL, bNodeTree::type, and ID::us.
Referenced by node_group_edit_set().
static void ntreeMakeLocal_CheckLocal (void * calldata, ID * owner_id, bNodeTree * ntree) [static]
Definition at line 1049 of file node.c.
References ListBase::first, MakeLocalCallData::group_id, bNode::id, MakeLocalCallData::lib, ID::lib, MakeLocalCallData::local, bNode::next, and bNodeTree::nodes.
Referenced by ntreeMakeLocal().
static void ntreeMakeLocal_LinkNew (void * calldata, ID * owner_id, bNodeTree * ntree) [static]
Definition at line 1063 of file node.c.
References ListBase::first, MakeLocalCallData::group_id, bNode::id, ID::lib, MakeLocalCallData::new_id, bNode::next, bNodeTree::nodes, NULL, and ID::us.
Referenced by ntreeMakeLocal().
int ntreeNodeExists (bNodeTree * ntree, bNode * testnode)
Definition at line 1121 of file node.c.
References ListBase::first, bNode::next, and bNodeTree::nodes.
Referenced by local_merge(), local_sync(), and ntreeLocalMerge().
int ntreeOutputExists (bNode * node, bNodeSocket * testsock)
Definition at line 1130 of file node.c.
References ListBase::first, bNodeSocket::next, and bNode::outputs.
Referenced by local_merge().
void ntreeSetOutput (bNodeTree * ntree)
Definition at line 991 of file node.c.
References CMP_NODE_OUTPUT_FILE, CMP_NODE_SPLITVIEWER, CMP_NODE_VIEWER, ELEM, ListBase::first, bNode::flag, bNodeType::nclass, bNode::next, NODE_CLASS_OUTPUT, NODE_DO_OUTPUT, bNodeTree::nodes, NTREE_COMPOSIT, bNodeTree::type, bNode::type, and bNode::typeinfo.
Referenced by ntreeCompositBeginExecTree(), ntreeLocalize(), ntreeShaderBeginExecTree(), and update().
void ntreeSwitchID (bNodeTree * ntree, ID * id_from, ID * id_to)
Definition at line 741 of file node.c.
References ListBase::first, bNode::id, bNode::next, and bNodeTree::nodes.
Referenced by copy_scene().
void ntreeUpdateTree (bNodeTree * ntree)
Definition at line 1543 of file node.c.
References ListBase::first, G, bNodeTree::id, bNode::next, node_get_type(), NODE_UPDATE, bNodeTree::nodes, bNodeTree::nodetype, NTREE_UPDATE, ntree_update_link_pointers(), NTREE_UPDATE_LINKS, ntree_update_node_level(), NTREE_UPDATE_NODES, ntree_validate_links(), ntreeGetType(), ntreeVerifyNodes(), bNodeTree::type, bNode::typeinfo, bNodeTreeType::update, bNode::update, bNodeTree::update, bNodeTreeType::update_node, bNodeType::updatefunc, and bNodeType::updatetreefunc.
Referenced by cut_links_exec(), detach_links_exec(), ED_node_composit_default(), ED_node_link_insert(), ED_node_shader_default(), ED_node_texture_default(), lib_nodetree_do_versions_update_cb(), lib_verify_nodetree(), node_add_node(), node_delete_exec(), node_delete_reconnect_exec(), node_duplicate_exec(), node_group_make_exec(), node_group_make_from_selected(), node_group_socket_add_exec(), node_group_socket_move_down_exec(), node_group_socket_move_up_exec(), node_group_socket_remove_exec(), node_group_ungroup(), node_link_modal(), node_link_viewer(), node_make_link_exec(), node_show_cycles_exec(), node_socket_add_replace(), node_socket_disconnect(), node_socket_remove(), node_socket_toggle_exec(), snode_autoconnect(), snode_autoconnect_input(), update_group_input_cb(), and update_group_output_cb().
void ntreeVerifyNodes (struct Main * main, struct ID * id)
Definition at line 1528 of file node.c.
References ListBase::first, bNodeTreeType::foreach_nodetree, bNodeTree::id, ID::next, Main::nodetree, ntree_verify_nodes_cb(), ntreeGetType(), NULL, and NUM_NTREE_TYPES.
Referenced by lib_verify_nodetree(), and ntreeUpdateTree().
static void registerCompositNodes (bNodeTreeType * ttype) [static]
Definition at line 1850 of file node.c.
References register_node_type_cmp_alphaover(), register_node_type_cmp_bilateralblur(), register_node_type_cmp_blur(), register_node_type_cmp_brightcontrast(), register_node_type_cmp_channel_matte(), register_node_type_cmp_chroma_matte(), register_node_type_cmp_color_matte(), register_node_type_cmp_color_spill(), register_node_type_cmp_colorbalance(), register_node_type_cmp_combhsva(), register_node_type_cmp_combrgba(), register_node_type_cmp_combycca(), register_node_type_cmp_combyuva(), register_node_type_cmp_composite(), register_node_type_cmp_crop(), register_node_type_cmp_curve_rgb(), register_node_type_cmp_curve_time(), register_node_type_cmp_curve_vec(), register_node_type_cmp_dblur(), register_node_type_cmp_defocus(), register_node_type_cmp_diff_matte(), register_node_type_cmp_dilateerode(), register_node_type_cmp_displace(), register_node_type_cmp_distance_matte(), register_node_type_cmp_doubleedgemask(), register_node_type_cmp_filter(), register_node_type_cmp_flip(), register_node_type_cmp_gamma(), register_node_type_cmp_glare(), register_node_type_cmp_group(), register_node_type_cmp_hue_sat(), register_node_type_cmp_huecorrect(), register_node_type_cmp_idmask(), register_node_type_cmp_image(), register_node_type_cmp_invert(), register_node_type_cmp_lensdist(), register_node_type_cmp_luma_matte(), register_node_type_cmp_map_value(), register_node_type_cmp_mapuv(), register_node_type_cmp_math(), register_node_type_cmp_mix_rgb(), register_node_type_cmp_movieclip(), register_node_type_cmp_moviedistortion(), register_node_type_cmp_normal(), register_node_type_cmp_normalize(), register_node_type_cmp_output_file(), register_node_type_cmp_premulkey(), register_node_type_cmp_rgb(), register_node_type_cmp_rgbtobw(), register_node_type_cmp_rlayers(), register_node_type_cmp_rotate(), register_node_type_cmp_scale(), register_node_type_cmp_sephsva(), register_node_type_cmp_seprgba(), register_node_type_cmp_sepycca(), register_node_type_cmp_sepyuva(), register_node_type_cmp_setalpha(), register_node_type_cmp_splitviewer(), register_node_type_cmp_stabilize2d(), register_node_type_cmp_texture(), register_node_type_cmp_tonemap(), register_node_type_cmp_transform(), register_node_type_cmp_translate(), register_node_type_cmp_valtorgb(), register_node_type_cmp_value(), register_node_type_cmp_vecblur(), register_node_type_cmp_view_levels(), register_node_type_cmp_viewer(), register_node_type_cmp_zcombine(), and register_node_type_frame().
Referenced by init_nodesystem().
static void registerShaderNodes (bNodeTreeType * ttype) [static]
Definition at line 1935 of file node.c.
References register_node_type_frame(), register_node_type_sh_add_shader(), register_node_type_sh_attribute(), register_node_type_sh_background(), register_node_type_sh_brightcontrast(), register_node_type_sh_bsdf_diffuse(), register_node_type_sh_bsdf_glass(), register_node_type_sh_bsdf_glossy(), register_node_type_sh_bsdf_translucent(), register_node_type_sh_bsdf_transparent(), register_node_type_sh_bsdf_velvet(), register_node_type_sh_camera(), register_node_type_sh_combrgb(), register_node_type_sh_curve_rgb(), register_node_type_sh_curve_vec(), register_node_type_sh_emission(), register_node_type_sh_fresnel(), register_node_type_sh_gamma(), register_node_type_sh_geom(), register_node_type_sh_geometry(), register_node_type_sh_group(), register_node_type_sh_holdout(), register_node_type_sh_hue_sat(), register_node_type_sh_invert(), register_node_type_sh_layer_weight(), register_node_type_sh_light_path(), register_node_type_sh_mapping(), register_node_type_sh_material(), register_node_type_sh_material_ext(), register_node_type_sh_math(), register_node_type_sh_mix_rgb(), register_node_type_sh_mix_shader(), register_node_type_sh_normal(), register_node_type_sh_output(), register_node_type_sh_output_lamp(), register_node_type_sh_output_material(), register_node_type_sh_output_world(), register_node_type_sh_rgb(), register_node_type_sh_rgbtobw(), register_node_type_sh_seprgb(), register_node_type_sh_squeeze(), register_node_type_sh_tex_checker(), register_node_type_sh_tex_coord(), register_node_type_sh_tex_environment(), register_node_type_sh_tex_gradient(), register_node_type_sh_tex_image(), register_node_type_sh_tex_magic(), register_node_type_sh_tex_musgrave(), register_node_type_sh_tex_noise(), register_node_type_sh_tex_sky(), register_node_type_sh_tex_voronoi(), register_node_type_sh_tex_wave(), register_node_type_sh_texture(), register_node_type_sh_valtorgb(), register_node_type_sh_value(), and register_node_type_sh_vect_math().
Referenced by init_nodesystem().
static void registerTextureNodes (bNodeTreeType * ttype) [static]
Definition at line 2006 of file node.c.
References register_node_type_frame(), register_node_type_tex_at(), register_node_type_tex_bricks(), register_node_type_tex_checker(), register_node_type_tex_compose(), register_node_type_tex_coord(), register_node_type_tex_curve_rgb(), register_node_type_tex_curve_time(), register_node_type_tex_decompose(), register_node_type_tex_distance(), register_node_type_tex_group(), register_node_type_tex_hue_sat(), register_node_type_tex_image(), register_node_type_tex_invert(), register_node_type_tex_math(), register_node_type_tex_mix_rgb(), register_node_type_tex_output(), register_node_type_tex_proc_blend(), register_node_type_tex_proc_clouds(), register_node_type_tex_proc_distnoise(), register_node_type_tex_proc_magic(), register_node_type_tex_proc_marble(), register_node_type_tex_proc_musgrave(), register_node_type_tex_proc_noise(), register_node_type_tex_proc_stucci(), register_node_type_tex_proc_voronoi(), register_node_type_tex_proc_wood(), register_node_type_tex_rgbtobw(), register_node_type_tex_rotate(), register_node_type_tex_scale(), register_node_type_tex_texture(), register_node_type_tex_translate(), register_node_type_tex_valtonor(), register_node_type_tex_valtorgb(), and register_node_type_tex_viewer().
Referenced by init_nodesystem().