Blender: sutil.c File Reference
sutil.c File Reference
opennl
#include <math.h>
#include "ssp_defs.h"
Functions
void sprint_lu_col (char *msg, int jcol, int pivrow, int *xprune, GlobalLU_t *Glu)
void scheck_tempv (int n, float *tempv)
void sPrintPerf (SuperMatrix *, SuperMatrix *, mem_usage_t *, float, float, float *, float *, char *, SuperLUStat_t *)
int print_float_vec (char *what, int n, float *vec)
void sCreate_CompCol_Matrix (SuperMatrix *A, int m, int n, int nnz, float *nzval, int *rowind, int *colptr, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
void sCreate_CompRow_Matrix (SuperMatrix *A, int m, int n, int nnz, float *nzval, int *colind, int *rowptr, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
void sCopy_CompCol_Matrix (SuperMatrix *A, SuperMatrix *B)
void sCreate_Dense_Matrix (SuperMatrix *X, int m, int n, float *x, int ldx, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
void sCopy_Dense_Matrix (int M, int N, float *X, int ldx, float *Y, int ldy)
void sCreate_SuperNode_Matrix (SuperMatrix *L, int m, int n, int nnz, float *nzval, int *nzval_colptr, int *rowind, int *rowind_colptr, int *col_to_sup, int *sup_to_col, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
void sCompRow_to_CompCol (int m, int n, int nnz, float *a, int *colind, int *rowptr, float **at, int **rowind, int **colptr)
void sPrint_CompCol_Matrix (char *what, SuperMatrix *A)
void sPrint_SuperNode_Matrix (char *what, SuperMatrix *A)
void sPrint_Dense_Matrix (char *what, SuperMatrix *A)
void sGenXtrue (int n, int nrhs, float *x, int ldx)
void sFillRHS (trans_t trans, int nrhs, float *x, int ldx, SuperMatrix *A, SuperMatrix *B)
void sfill (float *a, int alen, float dval)
void sinf_norm_error (int nrhs, SuperMatrix *X, float *xtrue)
Detailed Description
Definition in file sutil.c.
Function Documentation
int print_float_vec (char * what, int n, float * vec)
Definition at line 478 of file sutil.c.
References i.
void scheck_tempv (int n, float * tempv)
Definition at line 342 of file sutil.c.
References ABORT, and i.
void sCompRow_to_CompCol (int m, int n, int nnz, float * a, int * colind, int * rowptr, float ** at, int ** rowind, int ** colptr)
Definition at line 168 of file sutil.c.
References floatMalloc(), i, intCalloc(), intMalloc(), and SUPERLU_FREE.
void sCopy_CompCol_Matrix (SuperMatrix * A, SuperMatrix * B)
Definition at line 80 of file sutil.c.
References NCformat::colptr, SuperMatrix::Dtype, i, SuperMatrix::Mtype, SuperMatrix::ncol, NCformat::nnz, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, and SuperMatrix::Stype.
void sCopy_Dense_Matrix (int M, int N, float * X, int ldx, float * Y, int ldy)
Definition at line 119 of file sutil.c.
References i, M, and N.
void sCreate_CompCol_Matrix (SuperMatrix * A, int m, int n, int nnz, float * nzval, int * rowind, int * colptr, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
Definition at line 37 of file sutil.c.
References ABORT, NCformat::colptr, SuperMatrix::Dtype, SuperMatrix::Mtype, SuperMatrix::ncol, NCformat::nnz, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, SuperMatrix::Stype, and SUPERLU_MALLOC.
Referenced by __nlFactorize_SUPERLU(), sgssv(), and sgstrf().
void sCreate_CompRow_Matrix (SuperMatrix * A, int m, int n, int nnz, float * nzval, int * colind, int * rowptr, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
Definition at line 58 of file sutil.c.
References ABORT, NRformat::colind, SuperMatrix::Dtype, SuperMatrix::Mtype, SuperMatrix::ncol, NRformat::nnz, SuperMatrix::nrow, NRformat::nzval, NRformat::rowptr, SuperMatrix::Store, SuperMatrix::Stype, and SUPERLU_MALLOC.
void sCreate_Dense_Matrix (SuperMatrix * X, int m, int n, float * x, int ldx, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
Definition at line 101 of file sutil.c.
References ABORT, SuperMatrix::Dtype, DNformat::lda, SuperMatrix::Mtype, SuperMatrix::ncol, SuperMatrix::nrow, DNformat::nzval, SuperMatrix::Store, SuperMatrix::Stype, and SUPERLU_MALLOC.
Referenced by __nlInvert_SUPERLU().
void sCreate_SuperNode_Matrix (SuperMatrix * L, int m, int n, int nnz, float * nzval, int * nzval_colptr, int * rowind, int * rowind_colptr, int * col_to_sup, int * sup_to_col, Stype_t stype, Dtype_t dtype, Mtype_t mtype)
Definition at line 137 of file sutil.c.
References ABORT, SCformat::col_to_sup, SuperMatrix::Dtype, SuperMatrix::Mtype, SuperMatrix::ncol, SCformat::nnz, SuperMatrix::nrow, SCformat::nsuper, SCformat::nzval, SCformat::nzval_colptr, SCformat::rowind, SCformat::rowind_colptr, SuperMatrix::Store, SuperMatrix::Stype, SCformat::sup_to_col, and SUPERLU_MALLOC.
Referenced by sgstrf().
void sfill (float * a, int alen, float dval)
Definition at line 396 of file sutil.c.
References i.
Referenced by sSetRWork().
void sFillRHS (trans_t trans, int nrhs, float * x, int ldx, SuperMatrix * A, SuperMatrix * B)
Definition at line 370 of file sutil.c.
References DNformat::lda, NOTRANS, DNformat::nzval, sp_sgemm(), and SuperMatrix::Store.
void sGenXtrue (int n, int nrhs, float * x, int ldx)
Definition at line 357 of file sutil.c.
References i.
void sinf_norm_error (int nrhs, SuperMatrix * X, float * xtrue)
Definition at line 407 of file sutil.c.
References err, fabs(), i, DNformat::lda, SuperMatrix::nrow, DNformat::nzval, SuperMatrix::Store, and SUPERLU_MAX.
void sPrint_CompCol_Matrix (char * what, SuperMatrix * A)
Definition at line 206 of file sutil.c.
References NCformat::colptr, SuperMatrix::Dtype, i, SuperMatrix::Mtype, SuperMatrix::ncol, NCformat::nnz, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, and SuperMatrix::Stype.
void sPrint_Dense_Matrix (char * what, SuperMatrix * A)
Definition at line 278 of file sutil.c.
References SuperMatrix::Dtype, i, DNformat::lda, SuperMatrix::Mtype, SuperMatrix::ncol, SuperMatrix::nrow, DNformat::nzval, SuperMatrix::Store, and SuperMatrix::Stype.
void sprint_lu_col (char * msg, int jcol, int pivrow, int * xprune, GlobalLU_t * Glu)
Definition at line 299 of file sutil.c.
References i, GlobalLU_t::lsub, GlobalLU_t::lusup, GlobalLU_t::supno, GlobalLU_t::ucol, GlobalLU_t::usub, GlobalLU_t::xlsub, GlobalLU_t::xlusup, GlobalLU_t::xsup, and GlobalLU_t::xusub.
Referenced by sgstrf().
void sPrint_SuperNode_Matrix (char * what, SuperMatrix * A)
Definition at line 229 of file sutil.c.
References SCformat::col_to_sup, SuperMatrix::Dtype, i, SuperMatrix::Mtype, SuperMatrix::ncol, SCformat::nnz, SuperMatrix::nrow, SCformat::nsuper, SCformat::nzval, SCformat::nzval_colptr, SCformat::rowind, SCformat::rowind_colptr, SuperMatrix::Store, SuperMatrix::Stype, and SCformat::sup_to_col.
void sPrintPerf (SuperMatrix * L, SuperMatrix * U, mem_usage_t * mem_usage, float rpg, float rcond, float * ferr, float * berr, char * equed, SuperLUStat_t * stat)
Definition at line 433 of file sutil.c.
References EQUIL, ETREE, mem_usage_t::expansions, FACT, mem_usage_t::for_lu, SCformat::nnz, NCformat::nnz, SuperLUStat_t::ops, RCOND, REFINE, RELAX, SOLVE, SuperMatrix::Store, mem_usage_t::total_needed, and SuperLUStat_t::utime.