Blender: KX_SoftBodyDeformer Class Reference
KX_SoftBodyDeformer Class Reference
#include <KX_SoftBodyDeformer.h>
Public Member Functions
KX_SoftBodyDeformer (RAS_MeshObject *pMeshObject, BL_DeformableGameObject *gameobj)
virtual ~KX_SoftBodyDeformer ()
virtual void Relink (CTR_Map< class CTR_HashedPtr, void * > *map)
virtual bool Apply (class RAS_IPolyMaterial *polymat)
virtual bool Update (void)
virtual bool UpdateBuckets (void)
virtual RAS_Deformer * GetReplica ()
virtual void ProcessReplica ()
virtual bool SkipVertexTransform ()
Detailed Description
Definition at line 44 of file KX_SoftBodyDeformer.h.
Constructor & Destructor Documentation
KX_SoftBodyDeformer::KX_SoftBodyDeformer (RAS_MeshObject * pMeshObject, BL_DeformableGameObject * gameobj) [inline]
Definition at line 50 of file KX_SoftBodyDeformer.h.
Referenced by GetReplica().
virtual KX_SoftBodyDeformer::~KX_SoftBodyDeformer () [inline, virtual]
Definition at line 57 of file KX_SoftBodyDeformer.h.
Member Function Documentation
virtual bool KX_SoftBodyDeformer::Apply (class RAS_IPolyMaterial * polymat) [virtual]
Implements RAS_Deformer.
virtual RAS_Deformer* KX_SoftBodyDeformer::GetReplica (void) [inline, virtual]
Implements RAS_Deformer.
Definition at line 76 of file KX_SoftBodyDeformer.h.
References KX_SoftBodyDeformer(), and ProcessReplica().
virtual void KX_SoftBodyDeformer::ProcessReplica () [inline, virtual]
Implements RAS_Deformer.
Definition at line 82 of file KX_SoftBodyDeformer.h.
References RAS_Deformer::m_bDynamic.
Referenced by GetReplica().
virtual void KX_SoftBodyDeformer::Relink (CTR_Map< class CTR_HashedPtr, void * > * map) [virtual]
Implements RAS_Deformer.
virtual bool KX_SoftBodyDeformer::SkipVertexTransform () [inline, virtual]
Reimplemented from RAS_Deformer.
Definition at line 87 of file KX_SoftBodyDeformer.h.
virtual bool KX_SoftBodyDeformer::Update (void) [inline, virtual]
Implements RAS_Deformer.
Definition at line 63 of file KX_SoftBodyDeformer.h.
References RAS_Deformer::m_bDynamic.
virtual bool KX_SoftBodyDeformer::UpdateBuckets (void) [inline, virtual]
Implements RAS_Deformer.
Definition at line 69 of file KX_SoftBodyDeformer.h.
The documentation for this class was generated from the following file:
KX_SoftBodyDeformer.h