Blender: MOD_fluidsim_util.c File Reference
MOD_fluidsim_util.c File Reference
modifiers
#include <stddef.h>
#include <zlib.h>
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_fluidsim.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_main.h"
#include "BKE_fluidsim.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_mesh.h"
#include "BKE_utildefines.h"
#include "BKE_global.h"
#include "MOD_fluidsim_util.h"
#include "MOD_modifiertypes.h"
#include "MEM_guardedalloc.h"
#include "LBM_fluidsim.h"
Functions
void fluidsim_init (FluidsimModifierData *fluidmd)
void fluidsim_free (FluidsimModifierData *fluidmd)
DerivedMesh * fluidsimModifier_do (FluidsimModifierData *fluidmd, Scene *scene, Object *ob, DerivedMesh *dm, int useRenderParams, int UNUSED(isFinalCalc))
Detailed Description
Definition in file MOD_fluidsim_util.c.
Function Documentation
void fluidsim_free (FluidsimModifierData * fluidmd)
Definition at line 152 of file MOD_fluidsim_util.c.
References FluidsimModifierData::fss, MEM_freeN(), FluidsimSettings::meshVelocities, and NULL.
Referenced by freeData().
void fluidsim_init (FluidsimModifierData * fluidmd)
Definition at line 66 of file MOD_fluidsim_util.c.
References FluidsimSettings::animEnd, FluidsimSettings::animRate, FluidsimSettings::animStart, FluidsimSettings::attractforceRadius, FluidsimSettings::attractforceStrength, FluidsimSettings::cpsQuality, FluidsimSettings::cpsTimeEnd, FluidsimSettings::cpsTimeStart, FluidsimSettings::domainNovecgen, FluidsimSettings::flag, FluidsimSettings::fmd, FluidsimModifierData::fss, FluidsimSettings::generateParticles, FluidsimSettings::generateTracers, FluidsimSettings::grav, FluidsimSettings::gstar, FluidsimSettings::guiDisplayMode, FluidsimSettings::lastgoodframe, FluidsimSettings::maxRefine, MEM_callocN(), FluidsimSettings::meshVelocities, modifier_path_init(), NULL, OB_FLUIDSIM_ACTIVE, OB_FLUIDSIM_ENABLE, OB_FSBND_PARTSLIP, OB_FSSG_NOOBS, FluidsimSettings::particleInfAlpha, FluidsimSettings::particleInfSize, FluidsimSettings::partSlipValue, FluidsimSettings::previewresxyz, FluidsimSettings::realsize, FluidsimSettings::renderDisplayMode, FluidsimSettings::resolutionxyz, FluidsimSettings::show_advancedoptions, FluidsimSettings::surfaceSmoothing, FluidsimSettings::surfaceSubdivs, FluidsimSettings::surfdataPath, FluidsimSettings::type, FluidsimSettings::typeFlags, FluidsimSettings::velocityforceRadius, FluidsimSettings::velocityforceStrength, FluidsimSettings::viscosityExponent, FluidsimSettings::viscosityValue, and FluidsimSettings::volumeInitType.
Referenced by initData().
DerivedMesh* fluidsimModifier_do (FluidsimModifierData * fluidmd, Scene * scene, Object * ob, DerivedMesh * dm, int useRenderParams, int UNUSEDisFinalCalc)
Definition at line 522 of file MOD_fluidsim_util.c.
References RenderData::cfra, CLAMP(), FluidsimSettings::flag, FluidsimModifierData::fss, if(), FluidsimSettings::lastgoodframe, NULL, OB_FLUIDSIM_DOMAIN, OB_FLUIDSIM_REVERSE, Scene::r, and FluidsimSettings::type.
Referenced by applyModifier().