Blender: btRaycastVehicle.cpp File Reference
btRaycastVehicle.cpp File Reference
#include "LinearMath/btVector3.h"
#include "btRaycastVehicle.h"
#include "BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h"
#include "BulletDynamics/ConstraintSolver/btJacobianEntry.h"
#include "LinearMath/btQuaternion.h"
#include "BulletDynamics/Dynamics/btDynamicsWorld.h"
#include "btVehicleRaycaster.h"
#include "btWheelInfo.h"
#include "LinearMath/btMinMax.h"
#include "LinearMath/btIDebugDraw.h"
#include "BulletDynamics/ConstraintSolver/btContactConstraint.h"
Classes
struct btWheelContactPoint
Defines
#define ROLLING_INFLUENCE_FIX
Functions
btScalar calcRollingFriction (btWheelContactPoint &contactPoint)
Variables
btScalar sideFrictionStiffness2 = btScalar(1.0)
Define Documentation
#define ROLLING_INFLUENCE_FIX
Definition at line 25 of file btRaycastVehicle.cpp.
Function Documentation
btScalar calcRollingFriction (btWheelContactPoint & contactPoint)
Definition at line 496 of file btRaycastVehicle.cpp.
References btSetMax(), btSetMin(), btRigidBody::getCenterOfMassPosition(), btRigidBody::getVelocityInLocalPoint(), btWheelContactPoint::m_body0, btWheelContactPoint::m_body1, btWheelContactPoint::m_frictionDirectionWorld, btWheelContactPoint::m_frictionPositionWorld, btWheelContactPoint::m_jacDiagABInv, and btWheelContactPoint::m_maxImpulse.
Referenced by btRaycastVehicle::updateFriction().
Variable Documentation
btScalar sideFrictionStiffness2 = btScalar(1.0)
Definition at line 525 of file btRaycastVehicle.cpp.
Referenced by btRaycastVehicle::updateFriction().