Blender: GHOST_DisplayManagerX11 Class Reference
GHOST_DisplayManagerX11 Class Reference
#include <GHOST_DisplayManagerX11.h>
Public Member Functions
GHOST_DisplayManagerX11 (GHOST_SystemX11 *system)
GHOST_TSuccess getNumDisplays (GHOST_TUns8 &numDisplays) const
GHOST_TSuccess getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 &numSettings) const
GHOST_TSuccess getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting &setting) const
GHOST_TSuccess getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting &setting) const
GHOST_TSuccess setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting &setting)
Detailed Description
Manages system displays (X11 implementation).
Author:
Laurence Bourn
Date:
October 26, 2001
Definition at line 46 of file GHOST_DisplayManagerX11.h.
Constructor & Destructor Documentation
GHOST_DisplayManagerX11::GHOST_DisplayManagerX11 (GHOST_SystemX11 * system)
Constructor.
Definition at line 45 of file GHOST_DisplayManagerX11.cpp.
Member Function Documentation
GHOST_TSuccess GHOST_DisplayManagerX11::getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 157 of file GHOST_DisplayManagerX11.cpp.
References getDisplaySetting().
GHOST_TSuccess GHOST_DisplayManagerX11::getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
index The setting index to be returned.
setting The setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 101 of file GHOST_DisplayManagerX11.cpp.
References GHOST_DisplaySetting::bpp, GHOST_DisplaySetting::frequency, GHOST_SystemX11::getXDisplay(), GHOST_ASSERT, GHOST_kFailure, GHOST_kSuccess, NULL, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
Referenced by getCurrentDisplaySetting().
GHOST_TSuccess GHOST_DisplayManagerX11::getNumDisplays (GHOST_TUns8 & numDisplays) const [virtual]
Returns the number of display devices on this system.
Parameters:
numDisplays The number of displays on this system.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 56 of file GHOST_DisplayManagerX11.cpp.
References GHOST_SystemX11::getNumDisplays(), and GHOST_kSuccess.
GHOST_TSuccess GHOST_DisplayManagerX11::getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 & numSettings) const [virtual]
Returns the number of display settings for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The number of settings of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 66 of file GHOST_DisplayManagerX11.cpp.
References GHOST_SystemX11::getXDisplay(), GHOST_ASSERT, GHOST_kFailure, GHOST_kSuccess, and NULL.
GHOST_TSuccess GHOST_DisplayManagerX11::setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting & setting) [virtual]
Changes the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented from GHOST_DisplayManager.
Definition at line 170 of file GHOST_DisplayManagerX11.cpp.
References GHOST_SystemX11::getXDisplay(), GHOST_kFailure, GHOST_kSuccess, i, NULL, GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
The documentation for this class was generated from the following files:
GHOST_DisplayManagerX11.h
GHOST_DisplayManagerX11.cpp