Blender: idprop_py_api.c File Reference
idprop_py_api.c File Reference
Python Generic
#include <Python.h>
#include "idprop_py_api.h"
#include "MEM_guardedalloc.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "BKE_idprop.h"
#include "py_capi_utils.h"
Defines
#define USE_STRING_COERCE
#define MODULE_TYPE_ADD(s, t) PyModule_AddObject(s, t.tp_name, (PyObject *)&t); Py_INCREF((PyObject *)&t)
Functions
static PyObject * idprop_py_from_idp_string (IDProperty *prop)
static PyObject * idprop_py_from_idp_int (IDProperty *prop)
static PyObject * idprop_py_from_idp_float (IDProperty *prop)
static PyObject * idprop_py_from_idp_double (IDProperty *prop)
static PyObject * idprop_py_from_idp_group (ID *id, IDProperty *prop, IDProperty *parent)
static PyObject * idprop_py_from_idp_array (ID *id, IDProperty *prop)
static PyObject * idprop_py_from_idp_idparray (ID *id, IDProperty *prop)
static Py_hash_t BPy_IDGroup_hash (BPy_IDProperty *self)
static PyObject * BPy_IDGroup_repr (BPy_IDProperty *self)
PyObject * BPy_IDGroup_WrapData (ID *id, IDProperty *prop, IDProperty *parent)
static PyObject * BPy_IDGroup_GetName (BPy_IDProperty *self, void *UNUSED(closure))
static int BPy_IDGroup_SetName (BPy_IDProperty *self, PyObject *value, void *UNUSED(closure))
static Py_ssize_t BPy_IDGroup_Map_Len (BPy_IDProperty *self)
static PyObject * BPy_IDGroup_Map_GetItem (BPy_IDProperty *self, PyObject *item)
static int idp_sequence_type (PyObject *seq)
const char * BPy_IDProperty_Map_ValidateAndCreate (PyObject *name_obj, IDProperty *group, PyObject *ob)
int BPy_Wrap_SetMapItem (IDProperty *prop, PyObject *key, PyObject *val)
static int BPy_IDGroup_Map_SetItem (BPy_IDProperty *self, PyObject *key, PyObject *val)
static PyObject * BPy_IDGroup_iter (BPy_IDProperty *self)
static PyObject * BPy_IDGroup_MapDataToPy (IDProperty *prop)
static PyObject * BPy_IDGroup_Pop (BPy_IDProperty *self, PyObject *value)
static PyObject * BPy_IDGroup_IterItems (BPy_IDProperty *self)
static void BPy_IDGroup_CorrectListLen (IDProperty *prop, PyObject *seq, int len, const char *func)
PyObject * BPy_Wrap_GetKeys (IDProperty *prop)
PyObject * BPy_Wrap_GetValues (ID *id, IDProperty *prop)
PyObject * BPy_Wrap_GetItems (ID *id, IDProperty *prop)
static PyObject * BPy_IDGroup_GetKeys (BPy_IDProperty *self)
static PyObject * BPy_IDGroup_GetValues (BPy_IDProperty *self)
static PyObject * BPy_IDGroup_GetItems (BPy_IDProperty *self)
static int BPy_IDGroup_Contains (BPy_IDProperty *self, PyObject *value)
static PyObject * BPy_IDGroup_Update (BPy_IDProperty *self, PyObject *value)
static PyObject * BPy_IDGroup_to_dict (BPy_IDProperty *self)
static PyObject * BPy_IDGroup_Get (BPy_IDProperty *self, PyObject *args)
static PyTypeObject * idp_array_py_type (BPy_IDArray *self, short *is_double)
static PyObject * BPy_IDArray_repr (BPy_IDArray *self)
static PyObject * BPy_IDArray_GetType (BPy_IDArray *self)
static PyObject * BPy_IDArray_to_list (BPy_IDArray *self)
static int BPy_IDArray_Len (BPy_IDArray *self)
static PyObject * BPy_IDArray_GetItem (BPy_IDArray *self, int index)
static int BPy_IDArray_SetItem (BPy_IDArray *self, int index, PyObject *value)
static PyObject * BPy_IDArray_slice (BPy_IDArray *self, int begin, int end)
static int BPy_IDArray_ass_slice (BPy_IDArray *self, int begin, int end, PyObject *seq)
static PyObject * BPy_IDArray_subscript (BPy_IDArray *self, PyObject *item)
static int BPy_IDArray_ass_subscript (BPy_IDArray *self, PyObject *item, PyObject *value)
static PyObject * IDGroup_Iter_repr (BPy_IDGroup_Iter *self)
static PyObject * BPy_Group_Iter_Next (BPy_IDGroup_Iter *self)
void IDProp_Init_Types (void)
static PyObject * BPyInit_idprop_types (void)
PyDoc_STRVAR (IDProp_module_doc,"This module provides access id property types (currently mainly for docs).")
PyObject * BPyInit_idprop (void)
Variables
PyTypeObject BPy_IDArray_Type
PyTypeObject BPy_IDGroup_Iter_Type
PyTypeObject BPy_IDGroup_Type
static PyGetSetDef BPy_IDGroup_getseters []
static struct PyMethodDef BPy_IDGroup_methods []
static PySequenceMethods BPy_IDGroup_Seq
static PyMappingMethods BPy_IDGroup_Mapping
static PyGetSetDef BPy_IDArray_getseters []
static PyMethodDef BPy_IDArray_methods []
static PySequenceMethods BPy_IDArray_Seq
static PyMappingMethods BPy_IDArray_AsMapping
static struct PyModuleDef IDProp_types_module_def
static PyMethodDef IDProp_methods []
static struct PyModuleDef IDProp_module_def
Detailed Description
Definition in file idprop_py_api.c.
Define Documentation
#define MODULE_TYPE_ADD (s, t) PyModule_AddObject(s, t.tp_name, (PyObject *)&t); Py_INCREF((PyObject *)&t)
#define USE_STRING_COERCE
Definition at line 40 of file idprop_py_api.c.
Function Documentation
static PyObject* BPy_Group_Iter_Next (BPy_IDGroup_Iter * self) [static]
Definition at line 1324 of file idprop_py_api.c.
References BPy_IDGroup_WrapData(), IDPROP_ITER_ITEMS, IDProperty::name, IDProperty::next, and NULL.
static int BPy_IDArray_ass_slice (BPy_IDArray * self, int begin, int end, PyObject * seq) [static]
Definition at line 1133 of file idprop_py_api.c.
References CLAMP(), IDP_Array, idp_array_py_type(), IDProperty::len, MEM_freeN(), MEM_mallocN(), MIN2, PyC_AsArray(), and size().
Referenced by BPy_IDArray_ass_subscript().
static int BPy_IDArray_ass_subscript (BPy_IDArray * self, PyObject * item, PyObject * value) [static]
Definition at line 1198 of file idprop_py_api.c.
References BPy_IDArray_ass_slice(), BPy_IDArray_SetItem(), i, and step().
static PyObject* BPy_IDArray_GetItem (BPy_IDArray * self, int index) [static]
Definition at line 1009 of file idprop_py_api.c.
References IDP_Array, IDP_DOUBLE, IDP_FLOAT, IDP_INT, and NULL.
Referenced by BPy_IDArray_subscript().
static PyObject* BPy_IDArray_GetType (BPy_IDArray * self) [static]
Definition at line 972 of file idprop_py_api.c.
References IDP_DOUBLE, IDP_FLOAT, IDP_INT, and NULL.
static int BPy_IDArray_Len (BPy_IDArray * self) [static]
Definition at line 1004 of file idprop_py_api.c.
static PyObject* BPy_IDArray_repr (BPy_IDArray * self) [static]
Definition at line 967 of file idprop_py_api.c.
static int BPy_IDArray_SetItem (BPy_IDArray * self, int index, PyObject * value) [static]
Definition at line 1032 of file idprop_py_api.c.
References i, IDP_Array, IDP_DOUBLE, IDP_FLOAT, and IDP_INT.
Referenced by BPy_IDArray_ass_subscript().
static PyObject* BPy_IDArray_slice (BPy_IDArray * self, int begin, int end) [static]
Definition at line 1090 of file idprop_py_api.c.
References CLAMP(), IDP_Array, IDP_DOUBLE, IDP_FLOAT, IDP_INT, IDProperty::len, MIN2, and IDProperty::subtype.
Referenced by BPy_IDArray_subscript().
static PyObject* BPy_IDArray_subscript (BPy_IDArray * self, PyObject * item) [static]
Definition at line 1162 of file idprop_py_api.c.
References BPy_IDArray_GetItem(), BPy_IDArray_slice(), i, NULL, and step().
static PyObject* BPy_IDArray_to_list (BPy_IDArray * self) [static]
Definition at line 993 of file idprop_py_api.c.
References BPy_IDGroup_MapDataToPy().
static int BPy_IDGroup_Contains (BPy_IDProperty * self, PyObject * value) [static]
Definition at line 786 of file idprop_py_api.c.
References IDP_GetPropertyFromGroup().
static void BPy_IDGroup_CorrectListLen (IDProperty * prop, PyObject * seq, int len, const char * func) [static]
Definition at line 687 of file idprop_py_api.c.
References len(), and IDProperty::len.
Referenced by BPy_Wrap_GetItems(), BPy_Wrap_GetKeys(), and BPy_Wrap_GetValues().
static PyObject* BPy_IDGroup_Get (BPy_IDProperty * self, PyObject * args) [static]
Definition at line 827 of file idprop_py_api.c.
References BPy_IDGroup_WrapData(), IDP_GetPropertyFromGroup(), and NULL.
static PyObject* BPy_IDGroup_GetItems (BPy_IDProperty * self) [static]
Definition at line 781 of file idprop_py_api.c.
References BPy_Wrap_GetItems().
static PyObject* BPy_IDGroup_GetKeys (BPy_IDProperty * self) [static]
Definition at line 771 of file idprop_py_api.c.
References BPy_Wrap_GetKeys().
static PyObject* BPy_IDGroup_GetName (BPy_IDProperty * self, void * UNUSEDclosure) [static]
Definition at line 227 of file idprop_py_api.c.
static PyObject* BPy_IDGroup_GetValues (BPy_IDProperty * self) [static]
Definition at line 776 of file idprop_py_api.c.
References BPy_Wrap_GetValues().
static Py_hash_t BPy_IDGroup_hash (BPy_IDProperty * self) [static]
Definition at line 130 of file idprop_py_api.c.
static PyObject* BPy_IDGroup_iter (BPy_IDProperty * self) [static]
Definition at line 527 of file idprop_py_api.c.
References BPy_IDGroup_Iter_Type, BPy_IDGroup_Iter::cur, IDProperty::data, ListBase::first, BPy_IDGroup_Iter::group, IDPropertyData::group, IDPROP_ITER_KEYS, and BPy_IDGroup_Iter::mode.
static PyObject* BPy_IDGroup_IterItems (BPy_IDProperty * self) [static]
Definition at line 676 of file idprop_py_api.c.
References BPy_IDGroup_Iter_Type, BPy_IDGroup_Iter::cur, IDProperty::data, ListBase::first, BPy_IDGroup_Iter::group, IDPropertyData::group, IDPROP_ITER_ITEMS, and BPy_IDGroup_Iter::mode.
static PyObject* BPy_IDGroup_Map_GetItem (BPy_IDProperty * self, PyObject * item) [static]
Definition at line 275 of file idprop_py_api.c.
References BPy_IDGroup_WrapData(), IDP_GetPropertyFromGroup(), IDP_GROUP, and NULL.
static Py_ssize_t BPy_IDGroup_Map_Len (BPy_IDProperty * self) [static]
Definition at line 265 of file idprop_py_api.c.
References IDP_GROUP.
static int BPy_IDGroup_Map_SetItem (BPy_IDProperty * self, PyObject * key, PyObject * val) [static]
Definition at line 522 of file idprop_py_api.c.
References BPy_Wrap_SetMapItem().
Referenced by BPy_IDGroup_Update().
static PyObject* BPy_IDGroup_MapDataToPy (IDProperty * prop) [static]
Definition at line 538 of file idprop_py_api.c.
References IDProperty::data, ListBase::first, IDPropertyData::group, i, IDP_ARRAY, IDP_Array, IDP_DOUBLE, IDP_FLOAT, IDP_GROUP, IDP_IDPArray, IDP_IDPARRAY, IDP_INT, IDP_STRING, idprop_py_from_idp_double(), idprop_py_from_idp_float(), idprop_py_from_idp_int(), idprop_py_from_idp_string(), IDProperty::len, IDProperty::name, IDProperty::next, NULL, IDProperty::subtype, and IDProperty::type.
Referenced by BPy_IDArray_to_list(), BPy_IDGroup_Pop(), and BPy_IDGroup_to_dict().
static PyObject* BPy_IDGroup_Pop (BPy_IDProperty * self, PyObject * value) [static]
Definition at line 643 of file idprop_py_api.c.
References BPy_IDGroup_MapDataToPy(), IDP_GetPropertyFromGroup(), IDP_RemFromGroup(), and NULL.
static PyObject* BPy_IDGroup_repr (BPy_IDProperty * self) [static]
Definition at line 135 of file idprop_py_api.c.
static int BPy_IDGroup_SetName (BPy_IDProperty * self, PyObject * value, void * UNUSEDclosure) [static]
Definition at line 232 of file idprop_py_api.c.
References MAX_IDPROP_NAME.
static PyObject* BPy_IDGroup_to_dict (BPy_IDProperty * self) [static]
Definition at line 820 of file idprop_py_api.c.
References BPy_IDGroup_MapDataToPy().
static PyObject* BPy_IDGroup_Update (BPy_IDProperty * self, PyObject * value) [static]
Definition at line 800 of file idprop_py_api.c.
References BPy_IDGroup_Map_SetItem(), i, and NULL.
PyObject* BPy_IDGroup_WrapData (ID * id, IDProperty * prop, IDProperty * parent)
Definition at line 141 of file idprop_py_api.c.
References IDP_ARRAY, IDP_DOUBLE, IDP_FLOAT, IDP_GROUP, IDP_IDPARRAY, IDP_INT, IDP_STRING, idprop_py_from_idp_array(), idprop_py_from_idp_double(), idprop_py_from_idp_float(), idprop_py_from_idp_group(), idprop_py_from_idp_idparray(), idprop_py_from_idp_int(), idprop_py_from_idp_string(), and IDProperty::type.
Referenced by BPy_Group_Iter_Next(), BPy_IDGroup_Get(), BPy_IDGroup_Map_GetItem(), BPy_Wrap_GetItems(), BPy_Wrap_GetValues(), idprop_py_from_idp_idparray(), pyrna_struct_get(), and pyrna_struct_subscript().
const char* BPy_IDProperty_Map_ValidateAndCreate (PyObject * name_obj, IDProperty * group, PyObject * ob)
Definition at line 344 of file idprop_py_api.c.
References IDPropertyTemplate::array, BPy_IDProperty_Map_ValidateAndCreate(), IDPropertyTemplate::d, error(), IDPropertyTemplate::i, i, IDP_AppendArray(), IDP_ARRAY, IDP_Array, IDP_DOUBLE, IDP_FreeProperty(), IDP_GROUP, IDP_IDPARRAY, IDP_INT, IDP_New(), IDP_NewIDPArray(), IDP_ReplaceInGroup(), idp_sequence_type(), IDP_STRING, IDP_STRING_SUB_BYTE, IDP_STRING_SUB_UTF8, len(), IDPropertyTemplate::len, MAX_IDPROP_NAME, MEM_freeN(), NULL, PyC_UnicodeAsByte(), IDPropertyTemplate::str, IDPropertyTemplate::string, IDPropertyTemplate::subtype, IDProperty::type, and IDPropertyTemplate::type.
Referenced by BPy_IDProperty_Map_ValidateAndCreate(), and BPy_Wrap_SetMapItem().
PyObject* BPy_Wrap_GetItems (ID * id, IDProperty * prop)
Definition at line 747 of file idprop_py_api.c.
References BPy_IDGroup_CorrectListLen(), BPy_IDGroup_WrapData(), BPy_Wrap_GetItems(), IDProperty::data, ListBase::first, IDPropertyData::group, i, IDProperty::len, IDProperty::name, and IDProperty::next.
Referenced by BPy_IDGroup_GetItems(), BPy_Wrap_GetItems(), and pyrna_struct_items().
PyObject* BPy_Wrap_GetKeys (IDProperty * prop)
Definition at line 703 of file idprop_py_api.c.
References BPy_IDGroup_CorrectListLen(), BPy_Wrap_GetKeys(), IDProperty::data, ListBase::first, IDPropertyData::group, i, len(), IDProperty::len, IDProperty::name, and IDProperty::next.
Referenced by BPy_IDGroup_GetKeys(), BPy_Wrap_GetKeys(), and pyrna_struct_keys().
PyObject* BPy_Wrap_GetValues (ID * id, IDProperty * prop)
Definition at line 727 of file idprop_py_api.c.
References BPy_IDGroup_CorrectListLen(), BPy_IDGroup_WrapData(), BPy_Wrap_GetValues(), IDProperty::data, ListBase::first, IDPropertyData::group, i, IDProperty::len, and IDProperty::next.
Referenced by BPy_IDGroup_GetValues(), BPy_Wrap_GetValues(), and pyrna_struct_values().
int BPy_Wrap_SetMapItem (IDProperty * prop, PyObject * key, PyObject * val)
Definition at line 484 of file idprop_py_api.c.
References BPy_IDProperty_Map_ValidateAndCreate(), err, IDP_FreeProperty(), IDP_GetPropertyFromGroup(), IDP_GROUP, IDP_RemFromGroup(), MEM_freeN(), NULL, and IDProperty::type.
Referenced by BPy_IDGroup_Map_SetItem(), and pyrna_struct_ass_subscript().
PyObject* BPyInit_idprop (void)
Definition at line 1471 of file idprop_py_api.c.
References BPyInit_idprop_types(), and mod().
static PyObject* BPyInit_idprop_types (void) [static]
Definition at line 1430 of file idprop_py_api.c.
References MODULE_TYPE_ADD.
Referenced by BPyInit_idprop().
static PyObject* IDGroup_Iter_repr (BPy_IDGroup_Iter * self) [static]
Definition at line 1319 of file idprop_py_api.c.
static PyTypeObject* idp_array_py_type (BPy_IDArray * self, short * is_double) [static]
Definition at line 949 of file idprop_py_api.c.
References IDP_DOUBLE, IDP_FLOAT, IDP_INT, and NULL.
Referenced by BPy_IDArray_ass_slice().
static int idp_sequence_type (PyObject * seq) [static]
Definition at line 303 of file idprop_py_api.c.
References i, IDP_DOUBLE, IDP_IDPARRAY, IDP_INT, and len().
Referenced by BPy_IDProperty_Map_ValidateAndCreate().
void IDProp_Init_Types (void)
Definition at line 1407 of file idprop_py_api.c.
Referenced by BPy_init_modules().
static PyObject* idprop_py_from_idp_array (ID * id, IDProperty * prop) [static]
Definition at line 94 of file idprop_py_api.c.
References BPy_IDArray_Type, BPy_IDProperty::id, and BPy_IDProperty::prop.
Referenced by BPy_IDGroup_WrapData().
static PyObject* idprop_py_from_idp_double (IDProperty * prop) [static]
Definition at line 80 of file idprop_py_api.c.
References IDProperty::data, and IDPropertyData::val.
Referenced by BPy_IDGroup_MapDataToPy(), and BPy_IDGroup_WrapData().
static PyObject* idprop_py_from_idp_float (IDProperty * prop) [static]
Definition at line 75 of file idprop_py_api.c.
References IDProperty::data, and IDPropertyData::val.
Referenced by BPy_IDGroup_MapDataToPy(), and BPy_IDGroup_WrapData().
static PyObject* idprop_py_from_idp_group (ID * id, IDProperty * prop, IDProperty * parent) [static]
Definition at line 85 of file idprop_py_api.c.
References BPy_IDGroup_Type, BPy_IDProperty::id, BPy_IDProperty::parent, and BPy_IDProperty::prop.
Referenced by BPy_IDGroup_WrapData().
static PyObject* idprop_py_from_idp_idparray (ID * id, IDProperty * prop) [static]
Definition at line 102 of file idprop_py_api.c.
References BPy_IDGroup_WrapData(), i, IDP_IDPArray, IDProperty::len, and NULL.
Referenced by BPy_IDGroup_WrapData().
static PyObject* idprop_py_from_idp_int (IDProperty * prop) [static]
Definition at line 70 of file idprop_py_api.c.
References IDProperty::data, and IDPropertyData::val.
Referenced by BPy_IDGroup_MapDataToPy(), and BPy_IDGroup_WrapData().
static PyObject* idprop_py_from_idp_string (IDProperty * prop) [static]
Definition at line 56 of file idprop_py_api.c.
References IDP_Array, IDP_STRING_SUB_BYTE, IDProperty::len, PyC_UnicodeFromByteAndSize(), and IDProperty::subtype.
Referenced by BPy_IDGroup_MapDataToPy(), and BPy_IDGroup_WrapData().
PyDoc_STRVAR (IDProp_module_doc , "This module provides access id property types (currently mainly for docs).")
Variable Documentation
PyMappingMethods BPy_IDArray_AsMapping [static]
Initial value:
 {
    (lenfunc)BPy_IDArray_Len,
    (binaryfunc)BPy_IDArray_subscript,
    (objobjargproc)BPy_IDArray_ass_subscript
}
Definition at line 1229 of file idprop_py_api.c.
PyGetSetDef BPy_IDArray_getseters[] [static]
Initial value:
 {
    {(char *)"typecode", (getter)BPy_IDArray_GetType, (setter)NULL, (char *)"The type of the data in the array, is an int.", NULL},
    {NULL, NULL, NULL, NULL, NULL},
}
Definition at line 987 of file idprop_py_api.c.
PyMethodDef BPy_IDArray_methods[] [static]
Initial value:
 {
    {"to_list", (PyCFunction)BPy_IDArray_to_list, METH_NOARGS,
     "return the array as a list"},
    {NULL, NULL, 0, NULL}
}
Definition at line 998 of file idprop_py_api.c.
PySequenceMethods BPy_IDArray_Seq [static]
Initial value:
 {
    (lenfunc) BPy_IDArray_Len,
    NULL,
    NULL,
    (ssizeargfunc)BPy_IDArray_GetItem,
    NULL,
    (ssizeobjargproc)BPy_IDArray_SetItem,
    NULL,
    NULL,
    NULL,
    NULL,
}
Definition at line 1073 of file idprop_py_api.c.
PyTypeObject BPy_IDArray_Type
Definition at line 1236 of file idprop_py_api.c.
Referenced by idprop_py_from_idp_array().
PyGetSetDef BPy_IDGroup_getseters[] [static]
Initial value:
 {
    {(char *)"name", (getter)BPy_IDGroup_GetName, (setter)BPy_IDGroup_SetName, (char *)"The name of this Group.", NULL},
    {NULL, NULL, NULL, NULL, NULL}
}
Definition at line 260 of file idprop_py_api.c.
PyTypeObject BPy_IDGroup_Iter_Type
Definition at line 1350 of file idprop_py_api.c.
Referenced by BPy_IDGroup_iter(), and BPy_IDGroup_IterItems().
PyMappingMethods BPy_IDGroup_Mapping [static]
Initial value:
 {
    (lenfunc)BPy_IDGroup_Map_Len,
    (binaryfunc)BPy_IDGroup_Map_GetItem,
    (objobjargproc)BPy_IDGroup_Map_SetItem,
}
Definition at line 880 of file idprop_py_api.c.
struct PyMethodDef BPy_IDGroup_methods[] [static]
Initial value:
 {
    {"pop", (PyCFunction)BPy_IDGroup_Pop, METH_O,
     "pop an item from the group; raises KeyError if the item doesn't exist"},
    {"iteritems", (PyCFunction)BPy_IDGroup_IterItems, METH_NOARGS,
     "iterate through the items in the dict; behaves like dictionary method iteritems"},
    {"keys", (PyCFunction)BPy_IDGroup_GetKeys, METH_NOARGS,
     "get the keys associated with this group as a list of strings"},
    {"values", (PyCFunction)BPy_IDGroup_GetValues, METH_NOARGS,
     "get the values associated with this group"},
    {"items", (PyCFunction)BPy_IDGroup_GetItems, METH_NOARGS,
     "get the items associated with this group"},
    {"update", (PyCFunction)BPy_IDGroup_Update, METH_O,
     "updates the values in the group with the values of another or a dict"},
    {"get", (PyCFunction)BPy_IDGroup_Get, METH_VARARGS,
     "idprop.get(k[,d]) -> idprop[k] if k in idprop, else d.  d defaults to None"},
    {"to_dict", (PyCFunction)BPy_IDGroup_to_dict, METH_NOARGS,
     "return a purely python version of the group"},
    {NULL, NULL, 0, NULL}
}
Definition at line 847 of file idprop_py_api.c.
PySequenceMethods BPy_IDGroup_Seq [static]
Initial value:
 {
    (lenfunc) BPy_IDGroup_Map_Len,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    (objobjproc) BPy_IDGroup_Contains,
    NULL,
    NULL,
}
Definition at line 867 of file idprop_py_api.c.
PyTypeObject BPy_IDGroup_Type
Definition at line 886 of file idprop_py_api.c.
Referenced by idprop_py_from_idp_group().
PyMethodDef IDProp_methods[] [static]
Initial value:
 {
    {NULL, NULL, 0, NULL}
}
Definition at line 1451 of file idprop_py_api.c.
struct PyModuleDef IDProp_module_def [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "idprop",
    IDProp_module_doc,
    0,
    IDProp_methods,
    NULL,
    NULL,
    NULL,
    NULL,
}
Definition at line 1459 of file idprop_py_api.c.
struct PyModuleDef IDProp_types_module_def [static]
Initial value:
 {
    PyModuleDef_HEAD_INIT,
    "idprop.types",
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
}
Definition at line 1418 of file idprop_py_api.c.