Blender: rna_controller_api.c File Reference
rna_controller_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "WM_types.h"
#include "RNA_define.h"
Functions
void RNA_api_controller (StructRNA *srna)
Detailed Description
Definition in file rna_controller_api.c.
Function Documentation
void RNA_api_controller (StructRNA * srna)
Definition at line 63 of file rna_controller_api.c.
References NC_LOGIC, NULL, RNA_def_function(), RNA_def_function_ui_description(), RNA_def_pointer(), and RNA_def_property_update().
Referenced by RNA_def_controller().