Blender: VBVH_optimalPackSIMD< Node, TestCost > Struct Template Reference
VBVH_optimalPackSIMD< Node, TestCost > Struct Template Reference
#include <reorganize.h>
Classes
struct calc_best
Public Member Functions
VBVH_optimalPackSIMD (TestCost testcost)
void calc_costs (Node *node)
Node * transform (Node *node)
Public Attributes
TestCost testcost
Detailed Description
template<class Node, class TestCost>
struct VBVH_optimalPackSIMD< Node, TestCost >
Definition at line 395 of file reorganize.h.
Constructor & Destructor Documentation
template<class Node , class TestCost > VBVH_optimalPackSIMD< Node, TestCost >::VBVH_optimalPackSIMD (TestCost testcost) [inline]
Definition at line 399 of file reorganize.h.
References VBVH_optimalPackSIMD< Node, TestCost >::testcost.
Member Function Documentation
template<class Node , class TestCost > void VBVH_optimalPackSIMD< Node, TestCost >::calc_costs (Node * node) [inline]
Definition at line 468 of file reorganize.h.
References assert, bb_area(), i, MAX_CUT_SIZE, RE_rayobject_isAligned, and VBVH_optimalPackSIMD< Node, TestCost >::testcost.
Referenced by VBVH_optimalPackSIMD< Node, TestCost >::transform().
template<class Node , class TestCost > Node* VBVH_optimalPackSIMD< Node, TestCost >::transform (Node * node) [inline]
Definition at line 523 of file reorganize.h.
References VBVH_optimalPackSIMD< Node, TestCost >::calc_costs(), G, G_DEBUG, and RE_rayobject_isAligned.
Member Data Documentation
template<class Node , class TestCost > TestCost VBVH_optimalPackSIMD< Node, TestCost >::testcost
Definition at line 397 of file reorganize.h.
Referenced by VBVH_optimalPackSIMD< Node, TestCost >::calc_costs(), and VBVH_optimalPackSIMD< Node, TestCost >::VBVH_optimalPackSIMD().
The documentation for this struct was generated from the following file:
reorganize.h