Blender: TNT::Matrix< T > Class Template Reference
TNT::Matrix< T > Class Template Reference
#include <cmat.h>
Public Types
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Subscript lbound () const
operator T ** ()
operator T ** () const
Subscript size () const
Matrix ()
Matrix (const Matrix< T > &A)
Matrix (Subscript M, Subscript N, const T &value=T())
Matrix (Subscript M, Subscript N, const T *v)
~Matrix ()
Matrix< T > & newsize (Subscript M, Subscript N)
void diagonal (Vector< T > &diag)
Matrix< T > & operator= (const Matrix< T > &A)
Matrix< T > & operator= (const T &scalar)
Subscript dim (Subscript d) const
Subscript num_rows () const
Subscript num_cols () const
T * operator[] (Subscript i)
const T * operator[] (Subscript i) const
reference operator() (Subscript i)
const_reference operator() (Subscript i) const
reference operator() (Subscript i, Subscript j)
const_reference operator() (Subscript i, Subscript j) const
Subscript lbound () const
operator T ** ()
operator T ** () const
Subscript size () const
Matrix ()
Matrix (const Matrix< T > &A)
Matrix (Subscript M, Subscript N, const T &value=T())
Matrix (Subscript M, Subscript N, const T *v)
Matrix (Subscript M, Subscript N, const char *s)
~Matrix ()
Matrix< T > & newsize (Subscript M, Subscript N)
Matrix< T > & operator= (const Matrix< T > &A)
Matrix< T > & operator= (const T &scalar)
Subscript dim (Subscript d) const
Subscript num_rows () const
Subscript num_cols () const
T * operator[] (Subscript i)
const T * operator[] (Subscript i) const
reference operator() (Subscript i)
const_reference operator() (Subscript i) const
reference operator() (Subscript i, Subscript j)
const_reference operator() (Subscript i, Subscript j) const
Protected Member Functions
void initialize (Subscript M, Subscript N)
void copy (const T *v)
void set (const T &val)
void destroy ()
void initialize (Subscript M, Subscript N)
void copy (const T *v)
void set (const T &val)
void destroy ()
Protected Attributes
Subscript m_
Subscript n_
Subscript mn_
T * v_
T ** row_
T * vm1_
T ** rowm1_
Detailed Description
template<class T>
class TNT::Matrix< T >
Definition at line 49 of file cmat.h.
Member Typedef Documentation
template<class T> typedef const T* TNT::Matrix< T >::const_iterator
Definition at line 61 of file cmat.h.
template<class T> typedef const T* TNT::Matrix< T >::const_iterator
Definition at line 54 of file tnt_cmat.h.
template<class T> typedef const T& TNT::Matrix< T >::const_reference
Definition at line 62 of file cmat.h.
template<class T> typedef const T& TNT::Matrix< T >::const_reference
Definition at line 55 of file tnt_cmat.h.
template<class T> typedef T TNT::Matrix< T >::element_type
Definition at line 50 of file tnt_cmat.h.
template<class T> typedef T TNT::Matrix< T >::element_type
Definition at line 57 of file cmat.h.
template<class T> typedef T* TNT::Matrix< T >::iterator
Definition at line 59 of file cmat.h.
template<class T> typedef T* TNT::Matrix< T >::iterator
Definition at line 52 of file tnt_cmat.h.
template<class T> typedef T* TNT::Matrix< T >::pointer
Definition at line 51 of file tnt_cmat.h.
template<class T> typedef T* TNT::Matrix< T >::pointer
Definition at line 58 of file cmat.h.
template<class T> typedef T& TNT::Matrix< T >::reference
Definition at line 60 of file cmat.h.
template<class T> typedef T& TNT::Matrix< T >::reference
Definition at line 53 of file tnt_cmat.h.
template<class T> typedef Subscript TNT::Matrix< T >::size_type
Definition at line 48 of file tnt_cmat.h.
template<class T> typedef Subscript TNT::Matrix< T >::size_type
Definition at line 55 of file cmat.h.
template<class T> typedef T TNT::Matrix< T >::value_type
Definition at line 56 of file cmat.h.
template<class T> typedef T TNT::Matrix< T >::value_type
Definition at line 49 of file tnt_cmat.h.
Constructor & Destructor Documentation
template<class T> TNT::Matrix< T >::Matrix () [inline]
Definition at line 185 of file cmat.h.
template<class T> TNT::Matrix< T >::Matrix (const Matrix< T > & A) [inline]
Definition at line 187 of file cmat.h.
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const T & value = T()) [inline]
Definition at line 193 of file cmat.h.
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const T * v) [inline]
Definition at line 199 of file cmat.h.
template<class T> TNT::Matrix< T >::~Matrix () [inline]
Definition at line 208 of file cmat.h.
template<class T> TNT::Matrix< T >::Matrix () [inline]
Definition at line 178 of file tnt_cmat.h.
template<class T> TNT::Matrix< T >::Matrix (const Matrix< T > & A) [inline]
Definition at line 180 of file tnt_cmat.h.
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const T & value = T()) [inline]
Definition at line 186 of file tnt_cmat.h.
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const T * v) [inline]
Definition at line 192 of file tnt_cmat.h.
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const char * s) [inline]
Definition at line 198 of file tnt_cmat.h.
template<class T> TNT::Matrix< T >::~Matrix () [inline]
Definition at line 213 of file tnt_cmat.h.
Member Function Documentation
template<class T> void TNT::Matrix< T >::copy (const T * v) [inline, protected]
Definition at line 105 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::Matrix(), and TNT::Matrix< MT_Scalar >::operator=().
template<class T> void TNT::Matrix< T >::copy (const T * v) [inline, protected]
Definition at line 98 of file tnt_cmat.h.
template<class T> void TNT::Matrix< T >::destroy () [inline, protected]
Definition at line 160 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::newsize(), TNT::Matrix< MT_Scalar >::operator=(), and TNT::Matrix< MT_Scalar >::~Matrix().
template<class T> void TNT::Matrix< T >::destroy () [inline, protected]
Definition at line 153 of file tnt_cmat.h.
template<class T> void TNT::Matrix< T >::diagonal (Vector< T > & diag) [inline]
Definition at line 228 of file cmat.h.
template<class T> Subscript TNT::Matrix< T >::dim (Subscript d) const [inline]
Definition at line 262 of file tnt_cmat.h.
template<class T> Subscript TNT::Matrix< T >::dim (Subscript d) const [inline]
Definition at line 269 of file cmat.h.
template<class T> void TNT::Matrix< T >::initialize (Subscript M, Subscript N) [inline, protected]
Definition at line 71 of file tnt_cmat.h.
template<class T> void TNT::Matrix< T >::initialize (Subscript M, Subscript N) [inline, protected]
Definition at line 78 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::Matrix(), TNT::Matrix< MT_Scalar >::newsize(), and TNT::Matrix< MT_Scalar >::operator=().
template<class T> Subscript TNT::Matrix< T >::lbound () const [inline]
Definition at line 64 of file cmat.h.
template<class T> Subscript TNT::Matrix< T >::lbound () const [inline]
Definition at line 57 of file tnt_cmat.h.
template<class T> Matrix<T>& TNT::Matrix< T >::newsize (Subscript M, Subscript N) [inline]
Definition at line 216 of file cmat.h.
Referenced by IK_QJacobian::ArmMatrices(), TNT::Matrix< MT_Scalar >::diagonal(), TNT::matmult(), TNT::matmultdiag(), and TNT::operator>>().
template<class T> Matrix<T>& TNT::Matrix< T >::newsize (Subscript M, Subscript N) [inline]
Definition at line 221 of file tnt_cmat.h.
template<class T> Subscript TNT::Matrix< T >::num_cols () const [inline]
Definition at line 272 of file tnt_cmat.h.
template<class T> Subscript TNT::Matrix< T >::num_cols () const [inline]
Definition at line 279 of file cmat.h.
Referenced by IK_QJacobian::ComputeNullProjection(), TNT::matmult(), TNT::matmultdiag(), TNT::mult_element(), TNT::Matrix< MT_Scalar >::newsize(), TNT::operator+(), TNT::operator-(), TNT::operator>>(), and TNT::transpose().
template<class T> Subscript TNT::Matrix< T >::num_rows () const [inline]
Definition at line 271 of file tnt_cmat.h.
template<class T> Subscript TNT::Matrix< T >::num_rows () const [inline]
Definition at line 278 of file cmat.h.
Referenced by IK_QJacobian::ComputeNullProjection(), TNT::matmult(), TNT::matmultdiag(), TNT::mult_element(), TNT::Matrix< MT_Scalar >::newsize(), TNT::operator+(), TNT::operator-(), TNT::operator>>(), and TNT::transpose().
template<class T> TNT::Matrix< T >::operator T ** () [inline]
Definition at line 177 of file cmat.h.
References TNT::Matrix< T >::row_.
template<class T> TNT::Matrix< T >::operator T ** () [inline]
Definition at line 170 of file tnt_cmat.h.
References TNT::Matrix< T >::row_.
template<class T> TNT::Matrix< T >::operator T ** () const [inline]
Definition at line 171 of file tnt_cmat.h.
References TNT::Matrix< T >::row_.
template<class T> TNT::Matrix< T >::operator T ** () const [inline]
Definition at line 178 of file cmat.h.
References TNT::Matrix< T >::row_.
template<class T> reference TNT::Matrix< T >::operator() (Subscript i) [inline]
Definition at line 302 of file cmat.h.
template<class T> const_reference TNT::Matrix< T >::operator() (Subscript i) const [inline]
Definition at line 311 of file cmat.h.
template<class T> reference TNT::Matrix< T >::operator() (Subscript i, Subscript j) [inline]
Definition at line 322 of file cmat.h.
template<class T> const_reference TNT::Matrix< T >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 335 of file cmat.h.
template<class T> reference TNT::Matrix< T >::operator() (Subscript i) [inline]
Definition at line 295 of file tnt_cmat.h.
template<class T> const_reference TNT::Matrix< T >::operator() (Subscript i) const [inline]
Definition at line 304 of file tnt_cmat.h.
template<class T> const_reference TNT::Matrix< T >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 328 of file tnt_cmat.h.
template<class T> reference TNT::Matrix< T >::operator() (Subscript i, Subscript j) [inline]
Definition at line 315 of file tnt_cmat.h.
template<class T> Matrix<T>& TNT::Matrix< T >::operator= (const Matrix< T > & A) [inline]
Definition at line 237 of file tnt_cmat.h.
template<class T> Matrix<T>& TNT::Matrix< T >::operator= (const T & scalar) [inline]
Definition at line 255 of file tnt_cmat.h.
template<class T> Matrix<T>& TNT::Matrix< T >::operator= (const T & scalar) [inline]
Definition at line 262 of file cmat.h.
template<class T> Matrix<T>& TNT::Matrix< T >::operator= (const Matrix< T > & A) [inline]
Definition at line 244 of file cmat.h.
template<class T> T* TNT::Matrix< T >::operator[] (Subscript i) [inline]
Definition at line 284 of file cmat.h.
template<class T> T* TNT::Matrix< T >::operator[] (Subscript i) [inline]
Definition at line 277 of file tnt_cmat.h.
template<class T> const T* TNT::Matrix< T >::operator[] (Subscript i) const [inline]
Definition at line 286 of file tnt_cmat.h.
template<class T> const T* TNT::Matrix< T >::operator[] (Subscript i) const [inline]
Definition at line 293 of file cmat.h.
template<class T> void TNT::Matrix< T >::set (const T & val) [inline, protected]
Definition at line 131 of file cmat.h.
template<class T> void TNT::Matrix< T >::set (const T & val) [inline, protected]
Definition at line 124 of file tnt_cmat.h.
template<class T> Subscript TNT::Matrix< T >::size () const [inline]
Definition at line 174 of file tnt_cmat.h.
template<class T> Subscript TNT::Matrix< T >::size () const [inline]
Definition at line 181 of file cmat.h.
Member Data Documentation
template<class T> Subscript TNT::Matrix< T >::m_ [protected]
Definition at line 67 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::copy(), TNT::Matrix< MT_Scalar >::dim(), TNT::Matrix< MT_Scalar >::initialize(), TNT::Matrix< MT_Scalar >::Matrix(), TNT::Matrix< MT_Scalar >::num_rows(), TNT::Matrix< MT_Scalar >::operator()(), TNT::Matrix< MT_Scalar >::operator=(), TNT::Matrix< MT_Scalar >::operator[](), and TNT::Matrix< MT_Scalar >::set().
template<class T> Subscript TNT::Matrix< T >::mn_ [protected]
Definition at line 69 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::initialize(), TNT::Matrix< MT_Scalar >::operator()(), and TNT::Matrix< MT_Scalar >::size().
template<class T> Subscript TNT::Matrix< T >::n_ [protected]
Definition at line 68 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::copy(), TNT::Matrix< MT_Scalar >::dim(), TNT::Matrix< MT_Scalar >::initialize(), TNT::Matrix< MT_Scalar >::Matrix(), TNT::Matrix< MT_Scalar >::num_cols(), TNT::Matrix< MT_Scalar >::operator()(), TNT::Matrix< MT_Scalar >::operator=(), and TNT::Matrix< MT_Scalar >::set().
template<class T> T ** TNT::Matrix< T >::row_ [protected]
Definition at line 71 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::destroy(), TNT::Matrix< MT_Scalar >::diagonal(), TNT::Matrix< MT_Scalar >::initialize(), TNT::Matrix< MT_Scalar >::Matrix(), TNT::Matrix< T >::operator T **(), and TNT::Matrix< MT_Scalar >::operator[]().
template<class T> T ** TNT::Matrix< T >::rowm1_ [protected]
Definition at line 73 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::destroy(), TNT::Matrix< MT_Scalar >::initialize(), and TNT::Matrix< MT_Scalar >::operator()().
template<class T> T * TNT::Matrix< T >::v_ [protected]
Definition at line 70 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::copy(), TNT::Matrix< MT_Scalar >::destroy(), TNT::Matrix< MT_Scalar >::initialize(), TNT::Matrix< MT_Scalar >::Matrix(), TNT::Matrix< MT_Scalar >::operator=(), and TNT::Matrix< MT_Scalar >::set().
template<class T> T * TNT::Matrix< T >::vm1_ [protected]
Definition at line 72 of file cmat.h.
Referenced by TNT::Matrix< MT_Scalar >::initialize(), and TNT::Matrix< MT_Scalar >::operator()().
The documentation for this class was generated from the following files:
cmat.h
tnt_cmat.h