Blender: png.c File Reference
png.c File Reference
IMage Buffer
#include "png.h"
#include "BLI_blenlib.h"
#include "MEM_guardedalloc.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_allocimbuf.h"
#include "IMB_metadata.h"
#include "IMB_filetype.h"
Classes
struct PNGReadStruct
Typedefs
typedef struct PNGReadStruct PNGReadStruct
Functions
static void ReadData (png_structp png_ptr, png_bytep data, png_size_t length)
static void WriteData (png_structp png_ptr, png_bytep data, png_size_t length)
static void Flush (png_structp png_ptr)
int imb_is_a_png (unsigned char *mem)
int imb_savepng (struct ImBuf *ibuf, const char *name, int flags)
struct ImBuf * imb_loadpng (unsigned char *mem, size_t size, int flags)
Detailed Description
Definition in file png.c.
Typedef Documentation
typedef struct PNGReadStruct PNGReadStruct
Function Documentation
static void Flush (png_structp png_ptr) [static]
Definition at line 66 of file png.c.
Referenced by imb_savepng().
int imb_is_a_png (unsigned char * mem)
Definition at line 58 of file png.c.
Referenced by imb_loadpng().
struct ImBuf* imb_loadpng (unsigned char * mem, size_t size, int flags) [read]
Definition at line 303 of file png.c.
References PNGReadStruct::data, ImBuf::flags, ImBuf::ftype, i, IB_metadata, IB_PROFILE_SRGB, IB_test, imb_addrectImBuf(), IMB_allocImBuf(), IMB_freeImBuf(), imb_is_a_png(), IMB_metadata_add_field(), MEM_freeN(), MEM_mallocN(), NULL, PNG, ImBuf::ppm, ImBuf::profile, ReadData(), ImBuf::rect, PNGReadStruct::seek, size(), PNGReadStruct::size, ImBuf::x, and ImBuf::y.
int imb_savepng (struct ImBuf * ibuf, const char * name, int flags)
Definition at line 100 of file png.c.
References BLI_fopen(), ImBuf::encodedsize, Flush(), ImBuf::ftype, i, IB_mem, imb_addencodedbufferImBuf(), ImMetaData::key, MEM_callocN(), MEM_freeN(), MEM_mallocN(), ImBuf::metadata, ImMetaData::next, NULL, ImBuf::planes, ImBuf::ppm, ImBuf::rect, ImMetaData::value, ImBuf::x, and ImBuf::y.
static void ReadData (png_structp png_ptr, png_bytep data, png_size_t length) [static]
Definition at line 84 of file png.c.
References PNGReadStruct::data, length(), PNGReadStruct::seek, and size().
Referenced by imb_loadpng().
static void WriteData (png_structp png_ptr, png_bytep data, png_size_t length) [static]
Definition at line 71 of file png.c.
References ImBuf::encodedbuffer, ImBuf::encodedbuffersize, ImBuf::encodedsize, imb_enlargeencodedbufferImBuf(), and length().