Blender: BKE_movieclip.h File Reference
BKE_movieclip.h File Reference
blenkernel
Defines
#define MOVIECLIP_CACHE_SKIP (1<<0)
#define MOVIECLIP_DISABLE_RED (1<<0)
#define MOVIECLIP_DISABLE_GREEN (1<<1)
#define MOVIECLIP_DISABLE_BLUE (1<<2)
#define MOVIECLIP_PREVIEW_GRAYSCALE (1<<3)
Functions
void free_movieclip (struct MovieClip *clip)
void unlink_movieclip (struct Main *bmain, struct MovieClip *clip)
struct MovieClip * BKE_add_movieclip_file (const char *name)
void BKE_movieclip_reload (struct MovieClip *clip)
struct ImBuf * BKE_movieclip_get_ibuf (struct MovieClip *clip, struct MovieClipUser *user)
struct ImBuf * BKE_movieclip_get_postprocessed_ibuf (struct MovieClip *clip, struct MovieClipUser *user, int postprocess_flag)
struct ImBuf * BKE_movieclip_get_stable_ibuf (struct MovieClip *clip, struct MovieClipUser *user, float loc[2], float *scale, float *angle, int postprocess_flag)
struct ImBuf * BKE_movieclip_get_ibuf_flag (struct MovieClip *clip, struct MovieClipUser *user, int flag, int cache_flag)
void BKE_movieclip_get_size (struct MovieClip *clip, struct MovieClipUser *user, int *width, int *height)
int BKE_movieclip_get_duration (struct MovieClip *clip)
void BKE_movieclip_aspect (struct MovieClip *clip, float *aspx, float *aspy)
int BKE_movieclip_has_frame (struct MovieClip *clip, struct MovieClipUser *user)
void BKE_movieclip_user_set_frame (struct MovieClipUser *user, int framenr)
void BKE_movieclip_update_scopes (struct MovieClip *clip, struct MovieClipUser *user, struct MovieClipScopes *scopes)
void BKE_movieclip_get_cache_segments (struct MovieClip *clip, struct MovieClipUser *user, int *totseg_r, int **points_r)
void BKE_movieclip_build_proxy_frame (struct MovieClip *clip, int clip_flag, struct MovieDistortion *distortion, int cfra, int *build_sizes, int build_count, int undistorted)
Detailed Description
Author:
Sergey Sharybin
Definition in file BKE_movieclip.h.
Define Documentation
#define MOVIECLIP_CACHE_SKIP (1<<0)
Definition at line 67 of file BKE_movieclip.h.
Referenced by BKE_movieclip_build_proxy_frame(), BKE_tracking_next(), detect_features_exec(), movieclip_get_postprocessed_ibuf(), and seq_render_movieclip_strip().
#define MOVIECLIP_DISABLE_BLUE (1<<2)
Definition at line 72 of file BKE_movieclip.h.
Referenced by put_postprocessed_frame_to_cache(), and rna_def_space_clip().
#define MOVIECLIP_DISABLE_GREEN (1<<1)
Definition at line 71 of file BKE_movieclip.h.
Referenced by put_postprocessed_frame_to_cache(), and rna_def_space_clip().
#define MOVIECLIP_DISABLE_RED (1<<0)
Definition at line 70 of file BKE_movieclip.h.
Referenced by put_postprocessed_frame_to_cache(), and rna_def_space_clip().
#define MOVIECLIP_PREVIEW_GRAYSCALE (1<<3)
Definition at line 73 of file BKE_movieclip.h.
Referenced by put_postprocessed_frame_to_cache(), and rna_def_space_clip().
Function Documentation
struct MovieClip* BKE_add_movieclip_file (const char * name) [read]
Definition at line 453 of file movieclip.c.
References BKE_movieclip_get_size(), BLI_open(), BLI_path_abs(), BLI_strncpy(), BLI_testextensie_array(), MovieTracking::camera, FILE_MAX, MovieTrackingCamera::focal, MovieClipUser::framenr, G, MovieClip::id, imb_ext_movie, len(), MCLIP_SRC_MOVIE, MCLIP_SRC_SEQUENCE, movieclip_alloc(), movieclip_calc_length(), MovieClip::name, ID::next, NULL, O_BINARY, MovieTrackingCamera::principal, MovieTrackingCamera::sensor_width, MovieClip::source, str, strlen(), MovieClip::tracking, and ID::us.
Referenced by open_exec().
void BKE_movieclip_aspect (struct MovieClip * clip, float * aspx, float * aspy)
Definition at line 946 of file movieclip.c.
References MovieClip::aspx, MovieClip::aspy, MovieTracking::camera, MovieTrackingCamera::pixel_aspect, and MovieClip::tracking.
Referenced by ED_space_clip_aspect().
void BKE_movieclip_build_proxy_frame (struct MovieClip * clip, int clip_flag, struct MovieDistortion * distortion, int cfra, int * build_sizes, int build_count, int undistorted)
Definition at line 1123 of file movieclip.c.
References BKE_movieclip_get_ibuf_flag(), MovieClipUser::framenr, get_undistorted_ibuf(), i, IMB_freeImBuf(), MCLIP_PROXY_RENDER_SIZE_FULL, movieclip_build_proxy_ibuf(), MOVIECLIP_CACHE_SKIP, MovieClipUser::render_flag, and MovieClipUser::render_size.
Referenced by proxy_startjob().
void BKE_movieclip_get_cache_segments (struct MovieClip * clip, struct MovieClipUser * user, int * totseg_r, int ** points_r)
Definition at line 955 of file movieclip.c.
References MovieClip::cache, MovieClip::flag, IMB_moviecache_get_cache_segments(), MovieClipCache::moviecache, NULL, MovieClipUser::render_flag, and rendersize_to_proxy().
Referenced by draw_movieclip_cache().
int BKE_movieclip_get_duration (struct MovieClip * clip)
Definition at line 937 of file movieclip.c.
References MovieClip::len, and movieclip_calc_length().
Referenced by reload_sequence_new_file(), and sequencer_add_movieclip_strip_exec().
struct ImBuf* BKE_movieclip_get_ibuf (struct MovieClip * clip, struct MovieClipUser * user) [read]
Definition at line 751 of file movieclip.c.
References BKE_movieclip_get_ibuf_flag(), and MovieClip::flag.
Referenced by BKE_movieclip_get_size(), BKE_movieclip_has_frame(), BKE_movieclip_update_scopes(), draw_bgpic(), ED_view3d_draw_offscreen(), and node_composit_get_movieclip().
struct ImBuf* BKE_movieclip_get_ibuf_flag (struct MovieClip * clip, struct MovieClipUser * user, int flag, int cache_flag) [read]
Definition at line 756 of file movieclip.c.
References movieclip_get_postprocessed_ibuf().
Referenced by BKE_movieclip_build_proxy_frame(), BKE_movieclip_get_ibuf(), BKE_tracking_next(), detect_features_exec(), and seq_render_movieclip_strip().
struct ImBuf* BKE_movieclip_get_postprocessed_ibuf (struct MovieClip * clip, struct MovieClipUser * user, int postprocess_flag) [read]
Definition at line 761 of file movieclip.c.
References MovieClip::flag, and movieclip_get_postprocessed_ibuf().
Referenced by BKE_movieclip_get_stable_ibuf(), and ED_space_clip_get_buffer().
void BKE_movieclip_get_size (struct MovieClip * clip, struct MovieClipUser * user, int * width, int * height)
Definition at line 915 of file movieclip.c.
References BKE_movieclip_get_ibuf(), MovieClipUser::framenr, IMB_freeImBuf(), MovieClip::lastframe, MovieClip::lastsize, real_ibuf_size(), ImBuf::x, and ImBuf::y.
Referenced by BKE_add_movieclip_file(), BKE_movieclip_update_scopes(), BKE_tracking_context_new(), clip_graph_tracking_values_iterate_track(), createTransTrackingCurvesData(), draw_tracks_curves(), ED_space_clip_size(), exec(), marker_block_handler(), set_center_principal_exec(), solve_camera_freejob(), solve_camera_initjob(), and uiTemplateMarker().
struct ImBuf* BKE_movieclip_get_stable_ibuf (struct MovieClip * clip, struct MovieClipUser * user, float loc[2], float * scale, float * angle, int postprocess_flag) [read]
Definition at line 854 of file movieclip.c.
References MovieClipCache::angle, BKE_movieclip_get_postprocessed_ibuf(), MovieClip::cache, copy_v2_v2(), MovieTrackingStabilization::flag, MovieClipUser::framenr, get_stable_cached_frame(), IMB_freeImBuf(), MovieClipCache::loc, NULL, put_stabilized_frame_to_cache(), MovieClipCache::scale, MovieTracking::stabilization, MovieClipCache::stabilized, MovieClip::tracking, TRACKING_2D_STABILIZATION, and zero_v2().
Referenced by ED_space_clip_get_stable_buffer(), and seq_render_movieclip_strip().
int BKE_movieclip_has_frame (struct MovieClip * clip, struct MovieClipUser * user)
Definition at line 903 of file movieclip.c.
References BKE_movieclip_get_ibuf(), FALSE, IMB_freeImBuf(), and TRUE.
Referenced by createTransTrackingData(), and space_clip_frame_poll().
void BKE_movieclip_reload (struct MovieClip * clip)
Definition at line 997 of file movieclip.c.
References BLI_testextensie_array(), FALSE, free_buffers(), imb_ext_movie, MCLIP_SRC_MOVIE, MCLIP_SRC_SEQUENCE, movieclip_calc_length(), MovieClip::name, MovieTrackingStabilization::ok, MovieClip::source, MovieTracking::stabilization, and MovieClip::tracking.
Referenced by proxy_endjob(), and reload_exec().
void BKE_movieclip_update_scopes (struct MovieClip * clip, struct MovieClipUser * user, struct MovieClipScopes * scopes)
Definition at line 1013 of file movieclip.c.
References BKE_movieclip_get_ibuf(), BKE_movieclip_get_size(), BKE_tracking_active_track(), BKE_tracking_get_marker(), BKE_tracking_get_pattern_imbuf(), BKE_tracking_invert_intrinsics(), MovieTracking::camera, FALSE, MovieTrackingTrack::flag, MovieTrackingMarker::flag, MovieClipScopes::framenr, MovieClipUser::framenr, IMB_freeImBuf(), IMB_rect_from_float(), MovieClipScopes::marker, MARKER_DISABLED, MCLIP_PROXY_RENDER_UNDISTORT, NULL, MovieClipScopes::ok, MovieTrackingTrack::pat_max, MovieTrackingTrack::pat_min, MovieTrackingCamera::pixel_aspect, MovieTrackingMarker::pos, ImBuf::rect, ImBuf::rect_float, MovieClipUser::render_flag, MovieClipScopes::slide_scale, MovieClipScopes::track, MovieClipScopes::track_disabled, TRACK_LOCKED, MovieClipScopes::track_pos, MovieClipScopes::track_preview, MovieClip::tracking, and TRUE.
Referenced by clip_properties_area_draw().
void BKE_movieclip_user_set_frame (struct MovieClipUser * user, int framenr)
Definition at line 967 of file movieclip.c.
References MovieClipUser::framenr.
Referenced by clip_refresh(), draw_bgpic(), ED_clip_update_frame(), ED_view3d_draw_offscreen(), exec(), node_composit_exec_movieclip(), and seq_render_movieclip_strip().
void free_movieclip (struct MovieClip * clip)
Definition at line 1152 of file movieclip.c.
References BKE_tracking_free(), free_buffers(), and MovieClip::tracking.
Referenced by free_libblock().
void unlink_movieclip (struct Main * bmain, struct MovieClip * clip)
Definition at line 1159 of file movieclip.c.
References bScreen::areabase, View3D::bgpicbase, bObjectSolverConstraint::clip, bCameraSolverConstraint::clip, bFollowTrackConstraint::clip, Scene::clip, BGpic::clip, SpaceClip::clip, constraint_get_typeinfo(), CONSTRAINT_TYPE_CAMERASOLVER, CONSTRAINT_TYPE_FOLLOWTRACK, CONSTRAINT_TYPE_OBJECTSOLVER, Object::constraints, bConstraint::data, data, ListBase::first, MovieClip::id, Object::id, Scene::id, bScreen::id, if(), bConstraint::next, BGpic::next, SpaceLink::next, ScrArea::next, ID::next, NULL, Main::object, Main::scene, Main::screen, SPACE_CLIP, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, bConstraintTypeInfo::type, and ID::us.