Blender: uvedit_smart_stitch.c File Reference
uvedit_smart_stitch.c File Reference
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_object_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_scene_types.h"
#include "BLI_ghash.h"
#include "BLI_math.h"
#include "BLI_math_vector.h"
#include "BLI_string.h"
#include "BKE_context.h"
#include "BKE_customdata.h"
#include "BKE_depsgraph.h"
#include "BKE_mesh.h"
#include "BKE_tessmesh.h"
#include "ED_mesh.h"
#include "ED_uvedit.h"
#include "ED_screen.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_view2d.h"
#include "uvedit_intern.h"
Classes
struct IslandStitchData
struct UVVertAverage
struct UvEdge
struct StitchState
struct PreviewPosition
Defines
#define STITCH_SELECTED 1
#define STITCH_STITCHABLE 2
#define STITCH_PROCESSED 4
#define STITCH_BOUNDARY 8
#define STITCH_STITCHABLE_CANDIDATE 16
#define STITCH_NO_PREVIEW -1
#define HEADER_LENGTH 256
Typedefs
typedef struct IslandStitchData IslandStitchData
typedef struct UVVertAverage UVVertAverage
typedef struct UvEdge UvEdge
typedef struct StitchState StitchState
typedef struct PreviewPosition PreviewPosition
Functions
static StitchPreviewer * stitch_preview_init (void)
static void stitch_preview_delete (void)
StitchPreviewer * uv_get_stitch_previewer (void)
static void stitch_update_header (StitchState *stitch_state, bContext *C)
static int getNumOfIslandUvs (UvElementMap *elementMap, int island)
static void stitch_uv_rotate (float rotation, float medianPoint[2], float uv[2])
static int stitch_check_uvs_stitchable (UvElement *element, UvElement *element_iter, StitchState *state)
static int stitch_check_uvs_state_stitchable (UvElement *element, UvElement *element_iter, StitchState *state)
static void stitch_calculate_island_snapping (StitchState *state, PreviewPosition *preview_position, StitchPreviewer *preview, IslandStitchData *island_stitch_data, int final)
static void stitch_island_calculate_edge_rotation (UvEdge *edge, StitchState *state, UVVertAverage *uv_average, unsigned int *uvfinal_map, IslandStitchData *island_stitch_data)
static void stitch_island_calculate_vert_rotation (UvElement *element, StitchState *state, IslandStitchData *island_stitch_data)
static void stitch_state_delete (StitchState *stitch_state)
static void determine_uv_stitchability (UvElement *element, StitchState *state, IslandStitchData *island_stitch_data)
static void stitch_set_face_preview_buffer_position (BMFace *efa, StitchPreviewer *preview, PreviewPosition *preview_position)
static void stitch_setup_face_preview_for_uv_group (UvElement *element, StitchState *state, IslandStitchData *island_stitch_data, PreviewPosition *preview_position)
static void stitch_validate_stichability (UvElement *element, StitchState *state, IslandStitchData *island_stitch_data, PreviewPosition *preview_position)
static int stitch_process_data (StitchState *state, Scene *scene, int final)
static unsigned int uv_edge_hash (const void *key)
static int uv_edge_compare (const void *a, const void *b)
static void stitch_select_uv (UvElement *element, StitchState *state, int always_select)
static void stitch_calculate_edge_normal (BMEditMesh *em, UvEdge *edge, float *normal)
static int stitch_init (bContext *C, wmOperator *op)
static int stitch_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static void stitch_exit (bContext *C, wmOperator *op, int finished)
static int stitch_cancel (bContext *C, wmOperator *op)
static int stitch_exec (bContext *C, wmOperator *op)
static void stitch_select (bContext *C, Scene *scene, wmEvent *event, StitchState *stitch_state)
static int stitch_modal (bContext *C, wmOperator *op, wmEvent *event)
void UV_OT_stitch (wmOperatorType *ot)
Variables
static StitchPreviewer * _stitch_preview
Detailed Description
Definition in file uvedit_smart_stitch.c.
Define Documentation
#define HEADER_LENGTH 256
Definition at line 222 of file uvedit_smart_stitch.c.
Referenced by stitch_update_header().
#define STITCH_BOUNDARY 8
Definition at line 156 of file uvedit_smart_stitch.c.
Referenced by stitch_init().
#define STITCH_NO_PREVIEW -1
Definition at line 159 of file uvedit_smart_stitch.c.
Referenced by stitch_process_data(), and stitch_set_face_preview_buffer_position().
#define STITCH_PROCESSED 4
Definition at line 155 of file uvedit_smart_stitch.c.
Referenced by stitch_calculate_island_snapping(), and stitch_process_data().
#define STITCH_SELECTED 1
Definition at line 153 of file uvedit_smart_stitch.c.
Referenced by stitch_calculate_island_snapping(), stitch_process_data(), and stitch_select_uv().
#define STITCH_STITCHABLE 2
Definition at line 154 of file uvedit_smart_stitch.c.
Referenced by stitch_process_data(), and stitch_validate_stichability().
#define STITCH_STITCHABLE_CANDIDATE 16
Definition at line 157 of file uvedit_smart_stitch.c.
Referenced by determine_uv_stitchability(), and stitch_process_data().
Typedef Documentation
typedef struct IslandStitchData IslandStitchData
typedef struct PreviewPosition PreviewPosition
typedef struct StitchState StitchState
typedef struct UvEdge UvEdge
typedef struct UVVertAverage UVVertAverage
Function Documentation
static void determine_uv_stitchability (UvElement * element, StitchState * state, IslandStitchData * island_stitch_data) [static]
Definition at line 486 of file uvedit_smart_stitch.c.
References BM_elem_index_get, StitchState::element_map, UvElement::flag, UvElement::island, UvElement::l, UvElement::next, UvElement::separate, stitch_check_uvs_stitchable(), STITCH_STITCHABLE_CANDIDATE, IslandStitchData::stitchableCandidate, BMLoop::v, and UvElementMap::vert.
Referenced by stitch_process_data().
static int getNumOfIslandUvs (UvElementMap * elementMap, int island) [static]
Definition at line 243 of file uvedit_smart_stitch.c.
References UvElementMap::islandIndices, UvElementMap::totalIslands, and UvElementMap::totalUVs.
Referenced by stitch_calculate_island_snapping(), and stitch_process_data().
static void stitch_calculate_edge_normal (BMEditMesh * em, UvEdge * edge, float * normal) [static]
Definition at line 953 of file uvedit_smart_stitch.c.
References BMEditMesh::bm, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, UvEdge::element, BMLoop::head, UvElement::l, BMesh::ldata, BMLoop::next, normalize_v2(), sub_v2_v2v2(), and MLoopUV::uv.
Referenced by stitch_init().
static void stitch_calculate_island_snapping (StitchState * state, PreviewPosition * preview_position, StitchPreviewer * preview, IslandStitchData * island_stitch_data, int final) [static]
Definition at line 317 of file uvedit_smart_stitch.c.
References add_v2_v2(), BMEditMesh::bm, BM_elem_index_get, UvElementMap::buf, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, PreviewPosition::data_position, StitchState::element_map, StitchState::em, UvElement::face, UvElement::flag, getNumOfIslandUvs(), BMLoop::head, i, UvElementMap::islandIndices, UvElement::l, BMesh::ldata, IslandStitchData::medianPoint, IslandStitchData::num_rot_elements, IslandStitchData::numOfElements, StitchPreviewer::preview_polys, IslandStitchData::rotation, STITCH_PROCESSED, STITCH_SELECTED, stitch_uv_rotate(), UvElement::tfindex, UvElementMap::totalIslands, IslandStitchData::translation, and MLoopUV::uv.
Referenced by stitch_process_data().
static int stitch_cancel (bContext * C, wmOperator * op) [static]
Definition at line 1280 of file uvedit_smart_stitch.c.
References OPERATOR_CANCELLED, and stitch_exit().
Referenced by stitch_exec(), stitch_modal(), and UV_OT_stitch().
static int stitch_check_uvs_state_stitchable (UvElement * element, UvElement * element_iter, StitchState * state) [static]
Definition at line 304 of file uvedit_smart_stitch.c.
References UvElement::island, StitchState::midpoints, StitchState::snap_islands, and stitch_check_uvs_stitchable().
Referenced by stitch_island_calculate_vert_rotation(), stitch_process_data(), and stitch_validate_stichability().
static int stitch_check_uvs_stitchable (UvElement * element, UvElement * element_iter, StitchState * state) [static]
Definition at line 267 of file uvedit_smart_stitch.c.
References BMEditMesh::bm, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, StitchState::em, fabs(), BMLoop::head, UvElement::l, BMesh::ldata, StitchState::limit_dist, StitchState::use_limit, and MLoopUV::uv.
Referenced by determine_uv_stitchability(), and stitch_check_uvs_state_stitchable().
static int stitch_exec (bContext * C, wmOperator * op) [static]
Definition at line 1287 of file uvedit_smart_stitch.c.
References CTX_data_scene(), wmOperator::customdata, OPERATOR_CANCELLED, OPERATOR_FINISHED, stitch_cancel(), stitch_exit(), stitch_init(), and stitch_process_data().
Referenced by UV_OT_stitch().
static void stitch_exit (bContext * C, wmOperator * op, int finished) [static]
Definition at line 1228 of file uvedit_smart_stitch.c.
References BM_elem_index_get, CTX_data_edit_object(), CTX_data_scene(), CTX_wm_area(), CTX_wm_space_image(), wmOperator::customdata, DAG_id_tag_update(), Object::data, ED_area_headerprint(), UvElement::face, i, if(), StitchState::limit_dist, StitchState::midpoints, NC_GEOM, ND_DATA, NULL, wmOperator::ptr, RNA_boolean_set(), RNA_collection_add(), RNA_float_set(), RNA_int_set(), StitchState::selection_size, StitchState::selection_stack, StitchState::snap_islands, StitchState::static_island, stitch_preview_delete(), stitch_state_delete(), UvElement::tfindex, StitchState::use_limit, uvedit_live_unwrap_update(), and WM_event_add_notifier().
Referenced by stitch_cancel(), stitch_exec(), and stitch_modal().
static int stitch_init (bContext * C, wmOperator * op) [static]
Definition at line 971 of file uvedit_smart_stitch.c.
References add_v2_v2(), BLI_ghash_free(), BLI_ghash_haskey(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), BLI_ghashIterator_free(), BLI_ghashIterator_getKey(), BLI_ghashIterator_init(), BLI_ghashIterator_isDone(), BLI_ghashIterator_new(), BLI_ghashIterator_step(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACE_FIRST_LOOP, BM_FACES_OF_MESH, BM_iter_at_index(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), UvElementMap::buf, CTX_data_edit_object(), CTX_data_scene(), wmOperator::customdata, ED_uv_element_get(), EDBM_face_at_index(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), EDBM_uv_element_map_create(), StitchState::edges, UvEdge::element, StitchState::element_map, StitchState::em, UvEdge::flag, i, UvElement::island, BMFace::len, StitchState::limit_dist, StitchState::map, MEM_callocN(), MEM_freeN(), MEM_mallocN(), StitchState::midpoints, BMLoop::next, UvElement::next, normalize_v2(), StitchState::normals, NULL, wmOperator::ptr, RNA_BEGIN, RNA_boolean_get(), RNA_collection_clear(), RNA_END, RNA_float_get(), RNA_int_get(), RNA_struct_property_is_set(), StitchState::selection_size, StitchState::selection_stack, UvElement::separate, StitchState::snap_islands, state, StitchState::static_island, STITCH_BOUNDARY, stitch_calculate_edge_normal(), stitch_process_data(), stitch_select_uv(), stitch_state_delete(), stitch_update_header(), Scene::toolsettings, StitchState::total_boundary_edges, StitchState::total_separate_uvs, UvElementMap::totalIslands, UvElementMap::totalUVs, BMesh::totvert, StitchState::tris_per_island, StitchState::use_limit, UvEdge::uv1, UvEdge::uv2, uv_edge_compare(), uv_edge_hash(), ToolSettings::uv_flag, UV_SYNC_SELECTION, uvedit_uv_select_test(), StitchState::uvs, and UvElementMap::vert.
Referenced by stitch_exec(), and stitch_invoke().
static int stitch_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1217 of file uvedit_smart_stitch.c.
References CTX_data_edit_object(), Object::data, NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, stitch_init(), WM_event_add_modal_handler(), and WM_event_add_notifier().
Referenced by UV_OT_stitch().
static void stitch_island_calculate_edge_rotation (UvEdge * edge, StitchState * state, UVVertAverage * uv_average, unsigned int * uvfinal_map, IslandStitchData * island_stitch_data) [static]
Definition at line 371 of file uvedit_smart_stitch.c.
References acos(), BMEditMesh::bm, UvElementMap::buf, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, StitchState::element_map, StitchState::em, BMLoop::head, UvElement::island, UvElement::l, BMesh::ldata, MAX2, MIN2, normalize_v2(), IslandStitchData::num_rot_elements, IslandStitchData::rotation, UVVertAverage::uv, MLoopUV::uv, UvEdge::uv1, UvEdge::uv2, and StitchState::uvs.
Referenced by stitch_process_data().
static void stitch_island_calculate_vert_rotation (UvElement * element, StitchState * state, IslandStitchData * island_stitch_data) [static]
Definition at line 413 of file uvedit_smart_stitch.c.
References acos(), BM_elem_index_get, UvElementMap::buf, cross_v2v2(), dot_v2v2(), StitchState::element_map, UvElement::island, UvElement::l, StitchState::map, StitchState::midpoints, negate_v2_v2(), UvElement::next, StitchState::normals, IslandStitchData::num_rot_elements, IslandStitchData::rotation, UvElement::separate, StitchState::static_island, stitch_check_uvs_state_stitchable(), BMLoop::v, and UvElementMap::vert.
Referenced by stitch_process_data().
static int stitch_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1325 of file uvedit_smart_stitch.c.
References wmEvent::alt, CTX_data_scene(), CTX_wm_region(), wmOperator::customdata, ED_region_tag_redraw(), StitchState::element_map, ESCKEY, IKEY, KM_PRESS, KM_RELEASE, LEFTMOUSE, StitchState::limit_dist, LKEY, MAX2, MIDDLEMOUSE, StitchState::midpoints, MKEY, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, PADENTER, PADMINUS, PADPLUSKEY, RETKEY, RIGHTMOUSE, wmEvent::shift, SKEY, StitchState::snap_islands, StitchState::static_island, stitch_cancel(), stitch_exit(), stitch_process_data(), stitch_select(), stitch_update_header(), UvElementMap::totalIslands, wmEvent::type, StitchState::use_limit, USER_LMOUSESELECT, wmEvent::val, WHEELDOWNMOUSE, and WHEELUPMOUSE.
Referenced by UV_OT_stitch().
static void stitch_preview_delete (void) [static]
Definition at line 186 of file uvedit_smart_stitch.c.
References MEM_freeN(), NULL, StitchPreviewer::preview_polys, StitchPreviewer::preview_stitchable, StitchPreviewer::preview_unstitchable, StitchPreviewer::static_tris, and StitchPreviewer::uvs_per_polygon.
Referenced by stitch_exit(), and stitch_process_data().
static StitchPreviewer* stitch_preview_init (void) [static]
Definition at line 165 of file uvedit_smart_stitch.c.
References _stitch_preview, MEM_mallocN(), NULL, StitchPreviewer::num_polys, StitchPreviewer::num_static_tris, StitchPreviewer::num_stitchable, StitchPreviewer::num_unstitchable, StitchPreviewer::preview_polys, StitchPreviewer::preview_stitchable, StitchPreviewer::preview_unstitchable, StitchPreviewer::preview_uvs, StitchPreviewer::static_tris, and StitchPreviewer::uvs_per_polygon.
Referenced by stitch_process_data().
static int stitch_process_data (StitchState * state, Scene * scene, int final) [static]
Definition at line 582 of file uvedit_smart_stitch.c.
References add_v2_v2(), BMEditMesh::bm, BM_elem_index_get, BM_FACE, BM_FACE_FIRST_LOOP, BM_FACES_OF_MESH, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, UvElementMap::buf, CD_MLOOPUV, copy_v2_v2(), UVVertAverage::count, CustomData_bmesh_get(), BMHeader::data, PreviewPosition::data_position, determine_uv_stitchability(), ED_uv_element_get(), StitchState::edges, StitchState::element_map, StitchState::em, UvElement::face, FALSE, UvElement::flag, getNumOfIslandUvs(), BMLoop::head, i, if(), UvElement::island, UvElementMap::islandIndices, UvElement::l, BMesh::ldata, BMFace::len, IslandStitchData::medianPoint, MEM_callocN(), MEM_freeN(), MEM_mallocN(), StitchState::midpoints, UvElement::next, BMLoop::next, NULL, StitchPreviewer::num_polys, StitchPreviewer::num_static_tris, StitchPreviewer::num_stitchable, StitchPreviewer::num_unstitchable, IslandStitchData::numOfElements, PreviewPosition::polycount_position, StitchPreviewer::preview_polys, StitchPreviewer::preview_stitchable, StitchPreviewer::preview_unstitchable, StitchPreviewer::preview_uvs, StitchState::selection_size, StitchState::selection_stack, UvElement::separate, StitchState::snap_islands, StitchState::static_island, StitchPreviewer::static_tris, stitch_calculate_island_snapping(), stitch_check_uvs_state_stitchable(), stitch_island_calculate_edge_rotation(), stitch_island_calculate_vert_rotation(), STITCH_NO_PREVIEW, stitch_preview_delete(), stitch_preview_init(), STITCH_PROCESSED, STITCH_SELECTED, stitch_set_face_preview_buffer_position(), STITCH_STITCHABLE, STITCH_STITCHABLE_CANDIDATE, stitch_validate_stichability(), IslandStitchData::stitchableCandidate, UvElement::tfindex, StitchState::total_boundary_edges, StitchState::total_separate_uvs, UvElementMap::totalIslands, UvElementMap::totalUVs, BMesh::totface, IslandStitchData::translation, StitchState::tris_per_island, IslandStitchData::use_edge_rotation, UVVertAverage::uv, MLoopUV::uv, UvEdge::uv1, UvEdge::uv2, uvedit_uv_select_enable(), StitchState::uvs, StitchPreviewer::uvs_per_polygon, BMLoop::v, and UvElementMap::vert.
Referenced by stitch_exec(), stitch_init(), and stitch_modal().
static void stitch_select (bContext * C, Scene * scene, wmEvent * event, StitchState * stitch_state) [static]
Definition at line 1302 of file uvedit_smart_stitch.c.
References co, CTX_data_edit_image(), CTX_wm_region(), ED_uv_element_get(), NearestHit::efa, StitchState::element_map, StitchState::em, NearestHit::l, wmEvent::mval, NULL, stitch_select_uv(), UI_view2d_region_to_view(), uv_find_nearest_vert(), and ARegion::v2d.
Referenced by stitch_modal().
static void stitch_select_uv (UvElement * element, StitchState * state, int always_select) [static]
Definition at line 918 of file uvedit_smart_stitch.c.
References BM_elem_index_get, StitchState::element_map, UvElement::flag, i, UvElement::l, UvElement::next, StitchState::selection_size, StitchState::selection_stack, UvElement::separate, STITCH_SELECTED, BMLoop::v, and UvElementMap::vert.
Referenced by stitch_init(), and stitch_select().
static void stitch_set_face_preview_buffer_position (BMFace * efa, StitchPreviewer * preview, PreviewPosition * preview_position) [static]
Definition at line 513 of file uvedit_smart_stitch.c.
References BM_elem_index_get, PreviewPosition::data_position, BMFace::len, StitchPreviewer::num_polys, PreviewPosition::polycount_position, StitchPreviewer::preview_uvs, and STITCH_NO_PREVIEW.
Referenced by stitch_process_data(), and stitch_setup_face_preview_for_uv_group().
static void stitch_setup_face_preview_for_uv_group (UvElement * element, StitchState * state, IslandStitchData * island_stitch_data, PreviewPosition * preview_position) [static]
Definition at line 526 of file uvedit_smart_stitch.c.
References IslandStitchData::addedForPreview, UvElement::face, UvElement::island, StitchState::midpoints, UvElement::next, UvElement::separate, StitchState::snap_islands, StitchState::static_island, stitch_set_face_preview_buffer_position(), and uv_get_stitch_previewer().
Referenced by stitch_validate_stichability().
static void stitch_state_delete (StitchState * stitch_state) [static]
Definition at line 455 of file uvedit_smart_stitch.c.
References EDBM_uv_element_map_free(), StitchState::edges, StitchState::element_map, StitchState::map, MEM_freeN(), StitchState::normals, StitchState::selection_stack, StitchState::tris_per_island, and StitchState::uvs.
Referenced by stitch_exit(), and stitch_init().
static void stitch_update_header (StitchState * stitch_state, bContext * C) [static]
Definition at line 225 of file uvedit_smart_stitch.c.
References BLI_snprintf(), CTX_wm_area(), ED_area_headerprint(), HEADER_LENGTH, StitchState::limit_dist, StitchState::midpoints, StitchState::snap_islands, str, and StitchState::use_limit.
Referenced by stitch_init(), and stitch_modal().
static void stitch_uv_rotate (float rotation, float medianPoint[2], float uv[2]) [static]
Definition at line 253 of file uvedit_smart_stitch.c.
References cos(), and sin().
Referenced by stitch_calculate_island_snapping().
static void stitch_validate_stichability (UvElement * element, StitchState * state, IslandStitchData * island_stitch_data, PreviewPosition * preview_position) [static]
Definition at line 546 of file uvedit_smart_stitch.c.
References BM_elem_index_get, StitchState::element_map, UvElement::flag, UvElement::island, UvElement::l, UvElement::next, StitchPreviewer::num_stitchable, StitchPreviewer::num_unstitchable, UvElement::separate, StitchState::static_island, stitch_check_uvs_state_stitchable(), stitch_setup_face_preview_for_uv_group(), STITCH_STITCHABLE, uv_get_stitch_previewer(), BMLoop::v, and UvElementMap::vert.
Referenced by stitch_process_data().
static int uv_edge_compare (const void * a, const void * b) [static]
Definition at line 905 of file uvedit_smart_stitch.c.
References UvEdge::uv1, and UvEdge::uv2.
Referenced by stitch_init().
static unsigned int uv_edge_hash (const void * key) [static]
Definition at line 897 of file uvedit_smart_stitch.c.
References BLI_ghashutil_inthash(), SET_INT_IN_POINTER, UvEdge::uv1, and UvEdge::uv2.
Referenced by stitch_init().
StitchPreviewer* uv_get_stitch_previewer (void)
Definition at line 217 of file uvedit_smart_stitch.c.
References _stitch_preview.
Referenced by draw_uvs(), stitch_setup_face_preview_for_uv_group(), and stitch_validate_stichability().
void UV_OT_stitch (wmOperatorType * ot)
Definition at line 1460 of file uvedit_smart_stitch.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_HIDDEN, RNA_def_boolean(), RNA_def_collection_runtime(), RNA_def_float(), RNA_def_int(), RNA_def_property_flag(), RNA_SelectedUvElement, wmOperatorType::srna, stitch_cancel(), stitch_exec(), stitch_invoke(), and stitch_modal().
Referenced by ED_operatortypes_uvedit().
Variable Documentation
StitchPreviewer* _stitch_preview [static]
Definition at line 162 of file uvedit_smart_stitch.c.
Referenced by stitch_preview_init(), and uv_get_stitch_previewer().