Blender: node_composite_util.c File Reference
node_composite_util.c File Reference
nodes
#include "node_composite_util.h"
Defines
#define PRED(k) (((k & Nym) << Mx) + (k >> My))
#define YVV(L)
Typedefs
typedef float fREAL
Functions
CompBuf * alloc_compbuf (int sizex, int sizey, int type, int alloc)
CompBuf * dupalloc_compbuf (CompBuf *cbuf)
CompBuf * pass_on_compbuf (CompBuf *cbuf)
void free_compbuf (CompBuf *cbuf)
void print_compbuf (char *str, CompBuf *cbuf)
void compbuf_set_node (CompBuf *cbuf, bNode *node)
CompBuf * get_cropped_compbuf (rcti *drect, float *rectf, int rectx, int recty, int type)
CompBuf * scalefast_compbuf (CompBuf *inbuf, int newx, int newy)
void typecheck_compbuf_color (float *out, float *in, int outtype, int intype)
CompBuf * typecheck_compbuf (CompBuf *inbuf, int type)
float * compbuf_get_pixel (CompBuf *cbuf, float *defcol, float *use, int x, int y, int xrad, int yrad)
static CompBuf * composit_check_compbuf (CompBuf *cbuf, int type, CompBuf *outbuf)
void composit1_pixel_processor (bNode *node, CompBuf *out, CompBuf *src_buf, float *src_col, void(*func)(bNode *, float *, float *), int src_type)
void composit2_pixel_processor (bNode *node, CompBuf *out, CompBuf *src_buf, float *src_col, CompBuf *fac_buf, float *fac, void(*func)(bNode *, float *, float *, float *), int src_type, int fac_type)
void composit3_pixel_processor (bNode *node, CompBuf *out, CompBuf *src1_buf, float *src1_col, CompBuf *src2_buf, float *src2_col, CompBuf *fac_buf, float *fac, void(*func)(bNode *, float *, float *, float *, float *), int src1_type, int src2_type, int fac_type)
void composit4_pixel_processor (bNode *node, CompBuf *out, CompBuf *src1_buf, float *src1_col, CompBuf *fac1_buf, float *fac1, CompBuf *src2_buf, float *src2_col, CompBuf *fac2_buf, float *fac2, void(*func)(bNode *, float *, float *, float *, float *, float *), int src1_type, int fac1_type, int src2_type, int fac2_type)
CompBuf * valbuf_from_rgbabuf (CompBuf *cbuf, int channel)
static CompBuf * generate_procedural_preview (CompBuf *cbuf, int newx, int newy)
void generate_preview (void *data, bNode *node, CompBuf *stackbuf)
void do_rgba_to_yuva (bNode *UNUSED(node), float *out, float *in)
void do_rgba_to_hsva (bNode *UNUSED(node), float *out, float *in)
void do_rgba_to_ycca (bNode *UNUSED(node), float *out, float *in)
void do_yuva_to_rgba (bNode *UNUSED(node), float *out, float *in)
void do_hsva_to_rgba (bNode *UNUSED(node), float *out, float *in)
void do_ycca_to_rgba (bNode *UNUSED(node), float *out, float *in)
void do_copy_rgba (bNode *UNUSED(node), float *out, float *in)
void do_copy_rgb (bNode *UNUSED(node), float *out, float *in)
void do_copy_value (bNode *UNUSED(node), float *out, float *in)
void do_copy_a_rgba (bNode *UNUSED(node), float *out, float *in, float *fac)
void gamma_correct_compbuf (CompBuf *img, int inversed)
void premul_compbuf (CompBuf *img, int inversed)
static unsigned int nextPow2 (unsigned int x, unsigned int *L2)
static unsigned int revbin_upd (unsigned int r, unsigned int h)
static void FHT (fREAL *data, unsigned int M, unsigned int inverse)
static void FHT2D (fREAL *data, unsigned int Mx, unsigned int My, unsigned int nzp, unsigned int inverse)
static void fht_convolve (fREAL *d1, fREAL *d2, unsigned int M, unsigned int N)
void convolve (CompBuf *dst, CompBuf *in1, CompBuf *in2)
void qd_getPixel (CompBuf *src, int x, int y, float *col)
void qd_setPixel (CompBuf *src, int x, int y, float *col)
void qd_addPixel (CompBuf *src, int x, int y, float *col)
void qd_multPixel (CompBuf *src, int x, int y, float f)
void qd_getPixelLerpWrap (CompBuf *src, float u, float v, float *col)
void qd_getPixelLerp (CompBuf *src, float u, float v, float *col)
void qd_getPixelLerpChan (CompBuf *src, float u, float v, int chan, float *out)
CompBuf * qd_downScaledCopy (CompBuf *src, int scale)
void IIR_gauss (CompBuf *src, float sigma, int chan, int xy)
Detailed Description
Definition in file node_composite_util.c.
Define Documentation
#define PRED (k) (((k & Nym) << Mx) + (k >> My))
Referenced by FHT2D().
#define YVV (L)
Value:
{                                                                             \
    W[0] = cf[0]*X[0] + cf[1]*X[0] + cf[2]*X[0] + cf[3]*X[0];                 \
    W[1] = cf[0]*X[1] + cf[1]*W[0] + cf[2]*X[0] + cf[3]*X[0];                 \
    W[2] = cf[0]*X[2] + cf[1]*W[1] + cf[2]*W[0] + cf[3]*X[0];                 \
    for (i=3; i<L; i++)                                                       \
        W[i] = cf[0]*X[i] + cf[1]*W[i-1] + cf[2]*W[i-2] + cf[3]*W[i-3];       \
    tsu[0] = W[L-1] - X[L-1];                                                 \
    tsu[1] = W[L-2] - X[L-1];                                                 \
    tsu[2] = W[L-3] - X[L-1];                                                 \
    tsv[0] = tsM[0]*tsu[0] + tsM[1]*tsu[1] + tsM[2]*tsu[2] + X[L-1];          \
    tsv[1] = tsM[3]*tsu[0] + tsM[4]*tsu[1] + tsM[5]*tsu[2] + X[L-1];          \
    tsv[2] = tsM[6]*tsu[0] + tsM[7]*tsu[1] + tsM[8]*tsu[2] + X[L-1];          \
    Y[L-1] = cf[0]*W[L-1] + cf[1]*tsv[0] + cf[2]*tsv[1] + cf[3]*tsv[2];       \
    Y[L-2] = cf[0]*W[L-2] + cf[1]*Y[L-1] + cf[2]*tsv[0] + cf[3]*tsv[1];       \
    Y[L-3] = cf[0]*W[L-3] + cf[1]*Y[L-2] + cf[2]*Y[L-1] + cf[3]*tsv[0];       \
    for (i=L-4; i>=0; i--)                                                    \
        Y[i] = cf[0]*W[i] + cf[1]*Y[i+1] + cf[2]*Y[i+2] + cf[3]*Y[i+3];       \
}
Referenced by IIR_gauss(), and IIR_gauss_single().
Typedef Documentation
typedef float fREAL
Definition at line 764 of file node_composite_util.c.
Function Documentation
CompBuf* alloc_compbuf (int sizex, int sizey, int type, int alloc)
Definition at line 35 of file node_composite_util.c.
References CB_RGBA, CB_VEC2, CB_VEC3, CompBuf::disprect, CompBuf::malloc, MEM_callocN(), MEM_mapallocN(), CompBuf::rect, CompBuf::type, CompBuf::x, rcti::xmax, rcti::xmin, CompBuf::xrad, CompBuf::y, rcti::ymax, rcti::ymin, and CompBuf::yrad.
Referenced by bloom_with_reference(), blur_single_image(), blur_with_reference(), compbuf_from_pass(), convolve(), defocus_blur(), dupalloc_compbuf(), exec(), fglow(), generate_procedural_preview(), get_cropped_compbuf(), node_composit_exec_alphaover(), node_composit_exec_bilateralblur(), node_composit_exec_blur(), node_composit_exec_color_spill(), node_composit_exec_colorbalance(), node_composit_exec_combhsva(), node_composit_exec_combrgba(), node_composit_exec_combycca(), node_composit_exec_combyuva(), node_composit_exec_composite(), node_composit_exec_crop(), node_composit_exec_curve_rgb(), node_composit_exec_defocus(), node_composit_exec_displace(), node_composit_exec_doubleedgemask(), node_composit_exec_filter(), node_composit_exec_flip(), node_composit_exec_gamma(), node_composit_exec_huecorrect(), node_composit_exec_idmask(), node_composit_exec_invert(), node_composit_exec_lensdist(), node_composit_exec_map_value(), node_composit_exec_mapuv(), node_composit_exec_math(), node_composit_exec_mix_rgb(), node_composit_exec_normal(), node_composit_exec_normalize(), node_composit_exec_rgbtobw(), node_composit_exec_rlayers(), node_composit_exec_rotate(), node_composit_exec_scale(), node_composit_exec_setalpha(), node_composit_exec_splitviewer(), node_composit_exec_texture(), node_composit_exec_valtorgb(), node_composit_exec_view_levels(), node_composit_exec_viewer(), node_composit_exec_zcombine(), node_composit_get_image(), node_composit_get_movieclip(), node_composit_get_zimage(), node_composit_transform(), pass_on_compbuf(), qd_downScaledCopy(), scalefast_compbuf(), streaks(), typecheck_compbuf(), and valbuf_from_rgbabuf().
float* compbuf_get_pixel (CompBuf * cbuf, float * defcol, float * use, int x, int y, int xrad, int yrad)
Definition at line 379 of file node_composite_util.c.
References CompBuf::rect, CompBuf::rect_procedural, CompBuf::type, CompBuf::x, CompBuf::xof, CompBuf::xrad, CompBuf::y, CompBuf::yof, and CompBuf::yrad.
Referenced by blur_with_reference(), composit1_pixel_processor(), composit2_pixel_processor(), composit3_pixel_processor(), and composit4_pixel_processor().
void compbuf_set_node (CompBuf * cbuf, bNode * node)
Definition at line 128 of file node_composite_util.c.
References CompBuf::node.
Referenced by local_merge(), and localize().
void composit1_pixel_processor (bNode * node, CompBuf * out, CompBuf * src_buf, float * src_col, void(*)(bNode *, float *, float *) func, int src_type)
Definition at line 417 of file node_composite_util.c.
References compbuf_get_pixel(), composit_check_compbuf(), free_compbuf(), CompBuf::rect, CompBuf::type, CompBuf::x, CompBuf::xrad, CompBuf::y, and CompBuf::yrad.
Referenced by node_composit_exec_channel_matte(), node_composit_exec_chroma_matte(), node_composit_exec_color_matte(), node_composit_exec_color_spill(), node_composit_exec_colorbalance(), node_composit_exec_composite(), node_composit_exec_curve_rgb(), node_composit_exec_distance_matte(), node_composit_exec_huecorrect(), node_composit_exec_invert(), node_composit_exec_luma_matte(), node_composit_exec_map_value(), node_composit_exec_normal(), node_composit_exec_rgbtobw(), node_composit_exec_sephsva(), node_composit_exec_sepycca(), node_composit_exec_sepyuva(), node_composit_exec_setalpha(), node_composit_exec_texture(), node_composit_exec_valtorgb(), and node_composit_exec_viewer().
void composit2_pixel_processor (bNode * node, CompBuf * out, CompBuf * src_buf, float * src_col, CompBuf * fac_buf, float * fac, void(*)(bNode *, float *, float *, float *) func, int src_type, int fac_type)
Definition at line 443 of file node_composite_util.c.
References compbuf_get_pixel(), composit_check_compbuf(), free_compbuf(), CompBuf::rect, CompBuf::type, CompBuf::x, CompBuf::xrad, CompBuf::y, and CompBuf::yrad.
Referenced by node_composit_exec_color_spill(), node_composit_exec_colorbalance(), node_composit_exec_composite(), node_composit_exec_curve_rgb(), node_composit_exec_diff_matte(), node_composit_exec_gamma(), node_composit_exec_hue_sat(), node_composit_exec_huecorrect(), node_composit_exec_invert(), node_composit_exec_math(), node_composit_exec_setalpha(), node_composit_exec_viewer(), and node_composit_exec_zcombine().
void composit3_pixel_processor (bNode * node, CompBuf * out, CompBuf * src1_buf, float * src1_col, CompBuf * src2_buf, float * src2_col, CompBuf * fac_buf, float * fac, void(*)(bNode *, float *, float *, float *, float *) func, int src1_type, int src2_type, int fac_type)
Definition at line 473 of file node_composite_util.c.
References compbuf_get_pixel(), composit_check_compbuf(), free_compbuf(), CompBuf::rect, CompBuf::type, CompBuf::x, CompBuf::xrad, CompBuf::y, and CompBuf::yrad.
Referenced by node_composit_exec_alphaover(), node_composit_exec_brightcontrast(), node_composit_exec_mix_rgb(), node_composit_exec_normalize(), node_composit_exec_splitviewer(), and node_composit_exec_zcombine().
void composit4_pixel_processor (bNode * node, CompBuf * out, CompBuf * src1_buf, float * src1_col, CompBuf * fac1_buf, float * fac1, CompBuf * src2_buf, float * src2_col, CompBuf * fac2_buf, float * fac2, void(*)(bNode *, float *, float *, float *, float *, float *) func, int src1_type, int fac1_type, int src2_type, int fac2_type)
Definition at line 508 of file node_composite_util.c.
References compbuf_get_pixel(), composit_check_compbuf(), free_compbuf(), CompBuf::rect, CompBuf::type, CompBuf::x, CompBuf::xrad, CompBuf::y, and CompBuf::yrad.
Referenced by node_composit_exec_combhsva(), node_composit_exec_combrgba(), node_composit_exec_combycca(), node_composit_exec_combyuva(), and node_composit_exec_zcombine().
static CompBuf* composit_check_compbuf (CompBuf * cbuf, int type, CompBuf * outbuf) [static]
Definition at line 404 of file node_composite_util.c.
References dupalloc_compbuf(), CompBuf::rect_procedural, typecheck_compbuf(), CompBuf::xof, and CompBuf::yof.
Referenced by composit1_pixel_processor(), composit2_pixel_processor(), composit3_pixel_processor(), and composit4_pixel_processor().
void convolve (CompBuf * dst, CompBuf * in1, CompBuf * in2)
Definition at line 981 of file node_composite_util.c.
References alloc_compbuf(), FHT2D(), fht_convolve(), free_compbuf(), fRGB_add, fRGB_colormult, MEM_callocN(), MEM_freeN(), nextPow2(), CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by fglow().
void do_copy_a_rgba (bNode * UNUSEDnode, float * out, float * in, float * fac)
Definition at line 696 of file node_composite_util.c.
References copy_v3_v3().
Referenced by node_composit_exec_composite(), node_composit_exec_setalpha(), and node_composit_exec_viewer().
void do_copy_rgb (bNode * UNUSEDnode, float * out, float * in)
Definition at line 685 of file node_composite_util.c.
References copy_v3_v3().
Referenced by node_composit_exec_setalpha().
void do_copy_rgba (bNode * UNUSEDnode, float * out, float * in)
Definition at line 680 of file node_composite_util.c.
References copy_v4_v4().
Referenced by node_composit_exec_composite(), node_composit_exec_texture(), and node_composit_exec_viewer().
void do_copy_value (bNode * UNUSEDnode, float * out, float * in)
Definition at line 691 of file node_composite_util.c.
Referenced by node_composit_exec_composite(), node_composit_exec_texture(), and node_composit_exec_viewer().
void do_hsva_to_rgba (bNode * UNUSEDnode, float * out, float * in)
Definition at line 668 of file node_composite_util.c.
References hsv_to_rgb().
Referenced by node_composit_exec_channel_matte(), and node_composit_exec_color_matte().
void do_rgba_to_hsva (bNode * UNUSEDnode, float * out, float * in)
Definition at line 650 of file node_composite_util.c.
References rgb_to_hsv().
Referenced by node_composit_exec_channel_matte(), and node_composit_exec_color_matte().
void do_rgba_to_ycca (bNode * UNUSEDnode, float * out, float * in)
Definition at line 656 of file node_composite_util.c.
References BLI_YCC_ITU_BT601, and rgb_to_ycc().
void do_rgba_to_yuva (bNode * UNUSEDnode, float * out, float * in)
Definition at line 644 of file node_composite_util.c.
References rgb_to_yuv().
Referenced by node_composit_exec_channel_matte(), and node_composit_exec_luma_matte().
void do_ycca_to_rgba (bNode * UNUSEDnode, float * out, float * in)
Definition at line 674 of file node_composite_util.c.
References BLI_YCC_ITU_BT601, and ycc_to_rgb().
void do_yuva_to_rgba (bNode * UNUSEDnode, float * out, float * in)
Definition at line 662 of file node_composite_util.c.
References yuv_to_rgb().
Referenced by node_composit_exec_channel_matte(), and node_composit_exec_luma_matte().
CompBuf* dupalloc_compbuf (CompBuf * cbuf)
Definition at line 64 of file node_composite_util.c.
References alloc_compbuf(), CompBuf::rect, CompBuf::type, CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by composit_check_compbuf(), dblur(), ghosts(), lensDistort(), node_composit_exec_bilateralblur(), node_composit_exec_blur(), node_composit_exec_brightcontrast(), node_composit_exec_channel_matte(), node_composit_exec_chroma_matte(), node_composit_exec_color_matte(), node_composit_exec_color_spill(), node_composit_exec_dblur(), node_composit_exec_defocus(), node_composit_exec_diff_matte(), node_composit_exec_dilateerode(), node_composit_exec_distance_matte(), node_composit_exec_glare(), node_composit_exec_hue_sat(), node_composit_exec_luma_matte(), node_composit_exec_premulkey(), node_composit_exec_scale(), node_composit_exec_sephsva(), node_composit_exec_sepycca(), node_composit_exec_sepyuva(), node_composit_exec_tonemap(), node_composit_exec_vecblur(), node_composit_exec_zcombine(), qd_downScaledCopy(), scalefast_compbuf(), star4(), and streaks().
static void FHT (fREAL * data, unsigned int M, unsigned int inverse) [static]
Definition at line 787 of file node_composite_util.c.
References cos(), i, len(), M, M_PI, revbin_upd(), and sqrt().
Referenced by FHT2D().
static void FHT2D (fREAL * data, unsigned int Mx, unsigned int My, unsigned int nzp, unsigned int inverse) [static]
Definition at line 859 of file node_composite_util.c.
References A, B, C, D(), FHT(), i, and PRED.
Referenced by convolve().
static void fht_convolve (fREAL * d1, fREAL * d2, unsigned int M, unsigned int N) [static]
Definition at line 925 of file node_composite_util.c.
References i, L, M, and N.
Referenced by convolve().
void free_compbuf (CompBuf * cbuf)
Definition at line 99 of file node_composite_util.c.
References CompBuf::malloc, MEM_freeN(), CompBuf::next, CompBuf::prev, and CompBuf::rect.
Referenced by bloom_with_reference(), blur_single_image(), blur_with_reference(), composit1_pixel_processor(), composit2_pixel_processor(), composit3_pixel_processor(), composit4_pixel_processor(), convolve(), dblur(), defocus_blur(), exec(), exec_output_file_singlelayer(), fglow(), free_node_cache(), freeExecutableNode(), generate_preview(), ghosts(), group_free_internal(), lensDistort(), node_composit_exec_bilateralblur(), node_composit_exec_blur(), node_composit_exec_brightcontrast(), node_composit_exec_channel_matte(), node_composit_exec_chroma_matte(), node_composit_exec_color_matte(), node_composit_exec_color_spill(), node_composit_exec_composite(), node_composit_exec_defocus(), node_composit_exec_diff_matte(), node_composit_exec_dilateerode(), node_composit_exec_displace(), node_composit_exec_distance_matte(), node_composit_exec_glare(), node_composit_exec_hue_sat(), node_composit_exec_luma_matte(), node_composit_exec_mapuv(), node_composit_exec_premulkey(), node_composit_exec_rotate(), node_composit_exec_scale(), node_composit_exec_sephsva(), node_composit_exec_seprgba(), node_composit_exec_sepycca(), node_composit_exec_sepyuva(), node_composit_exec_splitviewer(), node_composit_exec_stabilize2d(), node_composit_exec_texture(), node_composit_exec_tonemap(), node_composit_exec_transform(), node_composit_exec_vecblur(), node_composit_exec_view_levels(), node_composit_exec_viewer(), node_composit_exec_zcombine(), setExecutableNodes(), star4(), and streaks().
void gamma_correct_compbuf (CompBuf * img, int inversed)
Definition at line 703 of file node_composite_util.c.
References CB_RGBA, CompBuf::rect, sqrt(), CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_blur(), and node_composit_exec_defocus().
void generate_preview (void * data, bNode * node, CompBuf * stackbuf)
Definition at line 590 of file node_composite_util.c.
References BLI_lock_thread(), BLI_unlock_thread(), CB_RGBA, RenderData::color_mgt_flag, data, free_compbuf(), generate_procedural_preview(), IB_PROFILE_LINEAR_RGB, IB_PROFILE_SRGB, IMB_buffer_byte_from_float(), LOCK_PREVIEW, MEM_callocN(), MEM_freeN(), NULL, bNode::preview, R_COLOR_MANAGEMENT, R_COLOR_MANAGEMENT_PREDIVIDE, bNodePreview::rect, CompBuf::rect, CompBuf::rect_procedural, scalefast_compbuf(), typecheck_compbuf(), CompBuf::x, bNodePreview::xsize, CompBuf::y, and bNodePreview::ysize.
Referenced by exec_output_file_multilayer(), exec_output_file_singlelayer(), node_composit_exec_blur(), node_composit_exec_channel_matte(), node_composit_exec_chroma_matte(), node_composit_exec_color_matte(), node_composit_exec_composite(), node_composit_exec_diff_matte(), node_composit_exec_distance_matte(), node_composit_exec_filter(), node_composit_exec_image(), node_composit_exec_luma_matte(), node_composit_exec_mix_rgb(), node_composit_exec_movieclip(), node_composit_exec_rlayers(), node_composit_exec_splitviewer(), node_composit_exec_texture(), node_composit_exec_view_levels(), and node_composit_exec_viewer().
static CompBuf* generate_procedural_preview (CompBuf * cbuf, int newx, int newy) [static]
Definition at line 571 of file node_composite_util.c.
References alloc_compbuf(), CB_RGBA, CompBuf::rect, CompBuf::rect_procedural, CompBuf::type, CompBuf::x, CompBuf::xrad, CompBuf::y, and CompBuf::yrad.
Referenced by generate_preview().
CompBuf* get_cropped_compbuf (rcti * drect, float * rectf, int rectx, int recty, int type)
Definition at line 134 of file node_composite_util.c.
References alloc_compbuf(), NULL, CompBuf::rect, CompBuf::x, rcti::xmax, rcti::xmin, CompBuf::y, rcti::ymax, and rcti::ymin.
Referenced by compbuf_from_pass(), node_composit_exec_crop(), node_composit_exec_rlayers(), node_composit_get_image(), node_composit_get_movieclip(), and node_composit_get_zimage().
void IIR_gauss (CompBuf * src, float sigma, int chan, int xy)
Definition at line 1282 of file node_composite_util.c.
References i, MAX2, MEM_callocN(), MEM_freeN(), CompBuf::rect, CompBuf::type, CompBuf::x, X, CompBuf::y, and YVV.
Referenced by ghosts(), lensDistort(), and node_composit_exec_blur().
static unsigned int nextPow2 (unsigned int x, unsigned int * L2) [static]
Definition at line 767 of file node_composite_util.c.
Referenced by convolve().
CompBuf* pass_on_compbuf (CompBuf * cbuf)
Definition at line 77 of file node_composite_util.c.
References alloc_compbuf(), CompBuf::malloc, CompBuf::next, NULL, CompBuf::prev, CompBuf::rect, CompBuf::type, CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by exec(), node_composit_exec_blur(), node_composit_exec_colorbalance(), node_composit_exec_defocus(), node_composit_exec_huecorrect(), node_composit_exec_invert(), node_composit_exec_scale(), and node_composit_exec_translate().
void premul_compbuf (CompBuf * img, int inversed)
Definition at line 727 of file node_composite_util.c.
References CB_RGBA, fabsf, CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_defocus(), and node_composit_exec_premulkey().
void print_compbuf (char * str, CompBuf * cbuf)
Definition at line 122 of file node_composite_util.c.
References CompBuf::rect, CompBuf::x, and CompBuf::y.
void qd_addPixel (CompBuf * src, int x, int y, float * col)
Definition at line 1156 of file node_composite_util.c.
References CompBuf::rect, CompBuf::type, and CompBuf::x.
CompBuf* qd_downScaledCopy (CompBuf * src, int scale)
Definition at line 1242 of file node_composite_util.c.
References alloc_compbuf(), dupalloc_compbuf(), fRGB_add, fRGB_copy, fRGB_mult, if(), CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by BTP().
void qd_getPixel (CompBuf * src, int x, int y, float * col)
Definition at line 1105 of file node_composite_util.c.
References CB_RGBA, CB_VAL, CB_VEC2, CB_VEC3, CompBuf::rect, CompBuf::rect_procedural, CompBuf::type, CompBuf::x, CompBuf::xrad, and CompBuf::yrad.
Referenced by brightness_mean(), brightness_standard_deviation(), do_displace(), fill_bins(), star4(), and streaks().
void qd_getPixelLerp (CompBuf * src, float u, float v, float * col)
Definition at line 1196 of file node_composite_util.c.
References B, CB_VAL, CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by dblur(), ghosts(), lensDistort(), mixImages(), star4(), and streaks().
void qd_getPixelLerpChan (CompBuf * src, float u, float v, int chan, float * out)
Definition at line 1221 of file node_composite_util.c.
References B, CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by lensDistort().
void qd_getPixelLerpWrap (CompBuf * src, float u, float v, float * col)
Definition at line 1174 of file node_composite_util.c.
References CB_VAL, CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by dblur().
void qd_multPixel (CompBuf * src, int x, int y, float f)
Definition at line 1165 of file node_composite_util.c.
References CompBuf::rect, CompBuf::type, and CompBuf::x.
void qd_setPixel (CompBuf * src, int x, int y, float * col)
Definition at line 1141 of file node_composite_util.c.
References CB_RGBA, CB_VAL, CB_VEC2, CB_VEC3, CompBuf::rect, CompBuf::type, and CompBuf::x.
Referenced by do_displace(), draw_histogram(), fglow(), ghosts(), and star4().
static unsigned int revbin_upd (unsigned int r, unsigned int h) [static]
Definition at line 781 of file node_composite_util.c.
Referenced by FHT().
CompBuf* scalefast_compbuf (CompBuf * inbuf, int newx, int newy)
Definition at line 156 of file node_composite_util.c.
References alloc_compbuf(), dupalloc_compbuf(), CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by generate_preview().
CompBuf* typecheck_compbuf (CompBuf * inbuf, int type)
Definition at line 264 of file node_composite_util.c.
References alloc_compbuf(), CB_RGBA, CB_VAL, CB_VEC2, CB_VEC3, copy_v3_v3(), CompBuf::node, CompBuf::procedural_offset, CompBuf::procedural_size, CompBuf::procedural_type, CompBuf::rect, CompBuf::rect_procedural, CompBuf::type, CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by blur_with_reference(), composit_check_compbuf(), exec(), exec_output_file_singlelayer(), generate_preview(), node_composit_exec_bilateralblur(), node_composit_exec_blur(), node_composit_exec_brightcontrast(), node_composit_exec_channel_matte(), node_composit_exec_chroma_matte(), node_composit_exec_color_matte(), node_composit_exec_color_spill(), node_composit_exec_dblur(), node_composit_exec_defocus(), node_composit_exec_diff_matte(), node_composit_exec_dilateerode(), node_composit_exec_displace(), node_composit_exec_distance_matte(), node_composit_exec_glare(), node_composit_exec_hue_sat(), node_composit_exec_luma_matte(), node_composit_exec_mapuv(), node_composit_exec_premulkey(), node_composit_exec_rotate(), node_composit_exec_scale(), node_composit_exec_sephsva(), node_composit_exec_seprgba(), node_composit_exec_sepycca(), node_composit_exec_sepyuva(), node_composit_exec_splitviewer(), node_composit_exec_stabilize2d(), node_composit_exec_tonemap(), node_composit_exec_transform(), node_composit_exec_vecblur(), and node_composit_exec_view_levels().
void typecheck_compbuf_color (float * out, float * in, int outtype, int intype)
Definition at line 195 of file node_composite_util.c.
References CB_RGBA, CB_VAL, CB_VEC2, and CB_VEC3.
Referenced by texture_procedural().
CompBuf* valbuf_from_rgbabuf (CompBuf * cbuf, int channel)
Definition at line 548 of file node_composite_util.c.
References alloc_compbuf(), CB_VAL, CHAN_A, CHAN_R, CompBuf::rect, CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by node_composit_exec_channel_matte(), node_composit_exec_chroma_matte(), node_composit_exec_color_matte(), node_composit_exec_diff_matte(), node_composit_exec_distance_matte(), node_composit_exec_image(), node_composit_exec_luma_matte(), node_composit_exec_rlayers(), node_composit_exec_sephsva(), node_composit_exec_seprgba(), node_composit_exec_sepycca(), node_composit_exec_sepyuva(), and node_composit_exec_valtorgb().