Blender: CcdPhysicsEnvironment.cpp File Reference
CcdPhysicsEnvironment.cpp File Reference
Bullet Physics
#include "CcdPhysicsEnvironment.h"
#include "CcdPhysicsController.h"
#include "CcdGraphicController.h"
#include <algorithm>
#include "btBulletDynamicsCommon.h"
#include "LinearMath/btIDebugDraw.h"
#include "BulletCollision/CollisionDispatch/btSimulationIslandManager.h"
#include "BulletSoftBody/btSoftRigidDynamicsWorld.h"
#include "BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h"
#include "BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h"
#include "LinearMath/btQuickprof.h"
#include "PHY_IMotionState.h"
#include "KX_GameObject.h"
#include "RAS_MeshObject.h"
#include "RAS_Polygon.h"
#include "RAS_TexVert.h"
#include "BulletDynamics/Vehicle/btRaycastVehicle.h"
#include "BulletDynamics/Vehicle/btVehicleRaycaster.h"
#include "BulletDynamics/Vehicle/btWheelInfo.h"
#include "PHY_IVehicle.h"
#include "LinearMath/btAabbUtil2.h"
#include "MT_Matrix4x4.h"
#include "MT_Vector3.h"
#include "GL/glew.h"
#include "BulletDynamics/ConstraintSolver/btContactConstraint.h"
#include <stdio.h>
#include <string.h>
Classes
class WrapperVehicle
class CcdOverlapFilterCallBack
class ClosestRayResultCallbackNotMe
struct FilterClosestRayResultCallback
struct OcclusionBuffer
struct OcclusionBuffer::WriteOCL
struct OcclusionBuffer::QueryOCL
struct DbvtCullingCallback
Defines
#define CCD_CONSTRAINT_DISABLE_LINKED_COLLISION 0x80
Functions
static bool GetHitTriangle (btCollisionShape *shape, CcdShapeConstructionInfo *shapeInfo, int hitTriangleIndex, btVector3 triangle[])
int findClosestNode (btSoftBody *sb, const btVector3 &worldPoint)
Variables
bool useIslands = true
btRaycastVehicle::btVehicleTuning gTuning
static int gConstraintUid = 1
static OcclusionBuffer gOcb
int currentController = 0
int numController = 0
Detailed Description
Definition in file CcdPhysicsEnvironment.cpp.
Define Documentation
#define CCD_CONSTRAINT_DISABLE_LINKED_COLLISION 0x80
Definition at line 44 of file CcdPhysicsEnvironment.cpp.
Referenced by CcdPhysicsEnvironment::createConstraint(), and CcdPhysicsEnvironment::createUniversalD6Constraint().
Function Documentation
int findClosestNode (btSoftBody * sb, const btVector3 & worldPoint)
Definition at line 2293 of file CcdPhysicsEnvironment.cpp.
References btSoftBody::m_nodes, nodes, and btAlignedObjectArray< T >::size().
Referenced by CcdPhysicsEnvironment::createConstraint().
static bool GetHitTriangle (btCollisionShape * shape, CcdShapeConstructionInfo * shapeInfo, int hitTriangleIndex, btVector3 triangle[]) [static]
Definition at line 1030 of file CcdPhysicsEnvironment.cpp.
References btCollisionShape::getLocalScaling(), btStridingMeshInterface::getLockedReadOnlyVertexIndexBase(), btTriangleMeshShape::getMeshInterface(), CcdShapeConstructionInfo::GetMeshShape(), btCollisionShape::getShapeType(), GIMPACT_SHAPE_PROXYTYPE, NULL, PHY_SHORT, and btStridingMeshInterface::unLockReadOnlyVertexBase().
Referenced by CcdPhysicsEnvironment::rayTest().
Variable Documentation
int currentController = 0
Definition at line 2260 of file CcdPhysicsEnvironment.cpp.
int gConstraintUid = 1 [static]
Definition at line 900 of file CcdPhysicsEnvironment.cpp.
OcclusionBuffer gOcb [static]
Definition at line 1785 of file CcdPhysicsEnvironment.cpp.
Referenced by CcdPhysicsEnvironment::cullingTest().
btRaycastVehicle::btVehicleTuning gTuning
Definition at line 53 of file CcdPhysicsEnvironment.cpp.
int numController = 0
Definition at line 2261 of file CcdPhysicsEnvironment.cpp.
bool useIslands = true
Definition at line 46 of file CcdPhysicsEnvironment.cpp.