Blender: KX_StateActuator Class Reference
KX_StateActuator Class Reference
#include <KX_StateActuator.h>
Public Member Functions
KX_StateActuator (SCA_IObject *gameobj, int operation, unsigned int mask)
virtual ~KX_StateActuator (void)
virtual CValue * GetReplica (void)
virtual bool Update ()
virtual void Deactivate ()
virtual void Activate (SG_DList &head)
Detailed Description
Definition at line 45 of file KX_StateActuator.h.
Constructor & Destructor Documentation
KX_StateActuator::KX_StateActuator (SCA_IObject * gameobj, int operation, unsigned int mask)
Definition at line 37 of file KX_StateActuator.cpp.
Referenced by GetReplica().
KX_StateActuator::~KX_StateActuator (void) [virtual]
Definition at line 49 of file KX_StateActuator.cpp.
Member Function Documentation
void KX_StateActuator::Activate (SG_DList & head) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 119 of file KX_StateActuator.cpp.
References SG_DList::AddFront(), SCA_ILogicBrick::InsertSelfActiveQList(), SCA_IObject::m_firstState, SCA_ILogicBrick::m_gameobj, and SG_QList::QEmpty().
void KX_StateActuator::Deactivate () [virtual]
remove this actuator from the list of active actuators
Reimplemented from SCA_IActuator.
Definition at line 108 of file KX_StateActuator.cpp.
References SG_DList::Delink(), SG_QList::QDelink(), and SG_QList::QEmpty().
CValue * KX_StateActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 60 of file KX_StateActuator.cpp.
References KX_StateActuator(), and SCA_IActuator::ProcessReplica().
bool KX_StateActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 70 of file KX_StateActuator.cpp.
References SCA_ILogicBrick::GetParent(), SCA_IObject::GetState(), SCA_IActuator::IsNegativeEvent(), SCA_IObject::m_firstState, SCA_ILogicBrick::m_gameobj, NULL, SCA_IActuator::RemoveAllEvents(), and SCA_IObject::SetState().
The documentation for this class was generated from the following files:
KX_StateActuator.h
KX_StateActuator.cpp