Blender: ParticleObject Class Reference
ParticleObject Class Reference
A single particle.
#include <particletracer.h>
Public Member Functions
ParticleObject (ntlVec3Gfx mp)
Standard constructor.
ParticleObject (const ParticleObject &a)
Copy constructor.
~ParticleObject ()
Destructor.
void advance (float vx, float vy, float vz)
add vector to position
void advanceVec (ntlVec3Gfx v)
void advanceVel ()
advance with own velocity
void addToVel (ntlVec3Gfx acc)
add acceleration to velocity
ntlVec3Gfx getPos ()
get/set vector to position
void setPos (ntlVec3Gfx set)
void setVel (ntlVec3Gfx set)
set velocity
void setVel (gfxReal x, gfxReal y, gfxReal z)
set velocity
ntlVec3Gfx getVel ()
get velocity
gfxReal getSize ()
get/set size value
void setSize (gfxReal set)
ParticleObject * getNext ()
get/set next pointer
void setNext (ParticleObject *set)
int getFlags () const
get whole flags
int getStatus () const
get status (higher byte)
void setStatus (int set)
set status (higher byte)
int getType () const
get type (lower byte)
void setType (int set)
set type (lower byte)
bool getActive () const
get active flag
void setActive (bool set)
set active flag
bool getInFluid () const
get influid flag
void setInFluid (bool set)
set influid flag
float getLifeTime () const
get/set lifetime
void setLifeTime (float set)
set type (lower byte)
int getId () const
Static Public Member Functions
static float getMass (float size)
Protected Attributes
int mId
ntlVec3Gfx mPos
ntlVec3Gfx mVel
gfxReal mSize
int mStatus
float mLifeTime
ParticleObject * mpNext
Detailed Description
A single particle.
Definition at line 38 of file particletracer.h.
Constructor & Destructor Documentation
ParticleObject::ParticleObject (ntlVec3Gfx mp) [inline]
Standard constructor.
Definition at line 42 of file particletracer.h.
References mId, and ParticleObjectIdCnt.
ParticleObject::ParticleObject (const ParticleObject & a) [inline]
Copy constructor.
Definition at line 46 of file particletracer.h.
References mId, and ParticleObjectIdCnt.
ParticleObject::~ParticleObject () [inline]
Destructor.
Definition at line 52 of file particletracer.h.
Member Function Documentation
void ParticleObject::addToVel (ntlVec3Gfx acc) [inline]
add acceleration to velocity
Definition at line 62 of file particletracer.h.
References mVel.
Referenced by LbmFsgrSolver::advanceParticles().
void ParticleObject::advance (float vx, float vy, float vz) [inline]
add vector to position
Definition at line 55 of file particletracer.h.
References mPos.
Referenced by LbmFsgrSolver::advanceParticles().
void ParticleObject::advanceVec (ntlVec3Gfx v) [inline]
Definition at line 57 of file particletracer.h.
References mPos.
Referenced by LbmFsgrSolver::advanceParticles(), and LbmFsgrSolver::handleObstacleParticle().
void ParticleObject::advanceVel () [inline]
advance with own velocity
Definition at line 60 of file particletracer.h.
References mPos, and mVel.
Referenced by LbmFsgrSolver::advanceParticles(), and LbmFsgrSolver::handleObstacleParticle().
bool ParticleObject::getActive () const [inline]
get active flag
Definition at line 93 of file particletracer.h.
References mStatus, and PART_INACTIVE.
Referenced by ParticleTracer::getTriangles().
int ParticleObject::getFlags (void) const [inline]
get whole flags
Definition at line 83 of file particletracer.h.
References mStatus.
Referenced by ParticleTracer::notifyOfDump().
int ParticleObject::getId () const [inline]
Definition at line 111 of file particletracer.h.
References mId.
bool ParticleObject::getInFluid () const [inline]
get influid flag
Definition at line 100 of file particletracer.h.
References mStatus, and PART_OUTFLUID.
float ParticleObject::getLifeTime () const [inline]
get/set lifetime
Definition at line 107 of file particletracer.h.
References mLifeTime.
Referenced by LbmFsgrSolver::advanceParticles().
static float ParticleObject::getMass (float size) [inline, static]
Definition at line 113 of file particletracer.h.
References M_PI, and size().
Referenced by LbmFsgrSolver::advanceParticles(), and LbmFsgrSolver::mainLoop().
ParticleObject* ParticleObject::getNext () [inline]
get/set next pointer
Definition at line 79 of file particletracer.h.
References mpNext.
Referenced by IsoSurface::triangulate().
ntlVec3Gfx ParticleObject::getPos () [inline]
get/set vector to position
Definition at line 65 of file particletracer.h.
References mPos.
Referenced by LbmFsgrSolver::advanceParticles(), ParticleTracer::checkDumpTextPositions(), ParticleTracer::getTriangles(), LbmFsgrSolver::handleObstacleParticle(), LbmFsgrSolver::initParticles(), ParticleTracer::notifyOfDump(), and IsoSurface::triangulate().
gfxReal ParticleObject::getSize (void) [inline]
get/set size value
Definition at line 75 of file particletracer.h.
References mSize.
Referenced by LbmFsgrSolver::advanceParticles(), ParticleTracer::checkDumpTextPositions(), ParticleTracer::getTriangles(), LbmFsgrSolver::initParticles(), ParticleTracer::notifyOfDump(), and IsoSurface::triangulate().
int ParticleObject::getStatus (void) const [inline]
get status (higher byte)
Definition at line 85 of file particletracer.h.
References mStatus.
Referenced by LbmFsgrSolver::advanceParticles(), and ParticleTracer::getTriangles().
int ParticleObject::getType (void) const [inline]
get type (lower byte)
Definition at line 89 of file particletracer.h.
References mStatus.
Referenced by LbmFsgrSolver::advanceParticles(), and ParticleTracer::getTriangles().
ntlVec3Gfx ParticleObject::getVel () [inline]
get velocity
Definition at line 72 of file particletracer.h.
References mVel.
Referenced by LbmFsgrSolver::advanceParticles(), ParticleTracer::checkDumpTextPositions(), ParticleTracer::getTriangles(), LbmFsgrSolver::handleObstacleParticle(), and ParticleTracer::notifyOfDump().
void ParticleObject::setActive (bool set) [inline]
set active flag
Definition at line 95 of file particletracer.h.
References mStatus, and PART_INACTIVE.
Referenced by LbmFsgrSolver::handleObstacleParticle().
void ParticleObject::setInFluid (bool set) [inline]
set influid flag
Definition at line 102 of file particletracer.h.
References mStatus, and PART_OUTFLUID.
Referenced by LbmFsgrSolver::advanceParticles().
void ParticleObject::setLifeTime (float set) [inline]
set type (lower byte)
Definition at line 109 of file particletracer.h.
References mLifeTime.
Referenced by LbmFsgrSolver::advanceParticles(), and LbmFsgrSolver::initParticles().
void ParticleObject::setNext (ParticleObject * set) [inline]
Definition at line 80 of file particletracer.h.
References mpNext.
Referenced by IsoSurface::triangulate().
void ParticleObject::setPos (ntlVec3Gfx set) [inline]
Definition at line 66 of file particletracer.h.
References mPos.
Referenced by LbmFsgrSolver::advanceParticles().
void ParticleObject::setSize (gfxReal set) [inline]
Definition at line 76 of file particletracer.h.
References mSize.
Referenced by LbmFsgrSolver::initParticles(), and LbmFsgrSolver::mainLoop().
void ParticleObject::setStatus (int set) [inline]
set status (higher byte)
Definition at line 87 of file particletracer.h.
References mStatus.
Referenced by LbmFsgrSolver::advanceParticles(), LbmFsgrSolver::initParticles(), and LbmFsgrSolver::mainLoop().
void ParticleObject::setType (int set) [inline]
set type (lower byte)
Definition at line 91 of file particletracer.h.
References mStatus.
Referenced by LbmFsgrSolver::initParticles(), and LbmFsgrSolver::mainLoop().
void ParticleObject::setVel (ntlVec3Gfx set) [inline]
set velocity
Definition at line 68 of file particletracer.h.
References mVel.
Referenced by LbmFsgrSolver::advanceParticles(), LbmFsgrSolver::handleObstacleParticle(), and LbmFsgrSolver::mainLoop().
void ParticleObject::setVel (gfxReal x, gfxReal y, gfxReal z) [inline]
set velocity
Definition at line 70 of file particletracer.h.
References mVel.
Member Data Documentation
int ParticleObject::mId [protected]
only for debugging
Definition at line 120 of file particletracer.h.
Referenced by getId(), and ParticleObject().
float ParticleObject::mLifeTime [protected]
count survived time steps
Definition at line 130 of file particletracer.h.
Referenced by getLifeTime(), and setLifeTime().
ParticleObject* ParticleObject::mpNext [protected]
Definition at line 133 of file particletracer.h.
Referenced by getNext(), and setNext().
ntlVec3Gfx ParticleObject::mPos [protected]
the particle position
Definition at line 122 of file particletracer.h.
Referenced by advance(), advanceVec(), advanceVel(), getPos(), and setPos().
gfxReal ParticleObject::mSize [protected]
size / mass of particle
Definition at line 126 of file particletracer.h.
Referenced by getSize(), and setSize().
int ParticleObject::mStatus [protected]
particle status
Definition at line 128 of file particletracer.h.
Referenced by getActive(), getFlags(), getInFluid(), getStatus(), getType(), setActive(), setInFluid(), setStatus(), and setType().
ntlVec3Gfx ParticleObject::mVel [protected]
the particle velocity
Definition at line 124 of file particletracer.h.
Referenced by addToVel(), advanceVel(), getVel(), and setVel().
The documentation for this class was generated from the following file:
particletracer.h