Blender: KDL::Joint Class Reference
KDL::Joint Class Reference
This class encapsulates a simple joint, that is with one parameterized degree of freedom and with scalar dynamic properties.
#include <joint.hpp>
Public Types
enum JointType {
RotX, RotY, RotZ, TransX,
TransY, TransZ, Sphere, Swing,
None
}
Public Member Functions
Joint (const JointType &type=None, const double &scale=1, const double &offset=0, const double &inertia=0, const double &damping=0, const double &stiffness=0)
Joint (const Joint &in)
Joint & operator= (const Joint &arg)
Frame pose (const double &q) const
Twist twist (const double &qdot, int dof=0) const
const JointType & getType () const
const std::string getTypeName () const
unsigned int getNDof () const
virtual ~Joint ()
Detailed Description
This class encapsulates a simple joint, that is with one parameterized degree of freedom and with scalar dynamic properties.
A simple joint is described by the following properties :
scale: ratio between motion input and motion output
offset: between the "physical" and the "logical" zero position.
type: revolute or translational, along one of the basic frame axes
inertia, stiffness and damping: scalars representing the physical effects along/about the joint axis only.
Definition at line 43 of file joint.hpp.
Member Enumeration Documentation
enum KDL::Joint::JointType
Enumerator:
RotX
RotY
RotZ
TransX
TransY
TransZ
Sphere
Swing
None
Definition at line 45 of file joint.hpp.
Constructor & Destructor Documentation
KDL::Joint::Joint (const JointType & type = None, const double & scale = 1, const double & offset = 0, const double & inertia = 0, const double & damping = 0, const double & stiffness = 0)
Constructor of a joint.
Parameters:
type type of the joint, default: Joint::None
scale scale between joint input and actual geometric movement, default: 1
offset offset between joint input and actual geometric input, default: 0
inertia 1D inertia along the joint axis, default: 0
damping 1D damping along the joint axis, default: 0
stiffness 1D stiffness along the joint axis, default: 0
Definition at line 29 of file joint.cpp.
KDL::Joint::Joint (const Joint & in)
Definition at line 36 of file joint.cpp.
KDL::Joint::~Joint () [virtual]
Definition at line 54 of file joint.cpp.
Member Function Documentation
unsigned int KDL::Joint::getNDof () const
Definition at line 141 of file joint.cpp.
References None, Sphere, and Swing.
Referenced by iTaSC::Armature::addLimitConstraint(), KDL::Chain::addSegment(), KDL::Tree::addSegment(), iTaSC::Armature::addSegment(), iTaSC::Armature::getSegment(), KDL::ChainFkSolverPos_recursive::JntToCart(), and KDL::ChainJntToJacSolver::JntToJac().
const JointType& KDL::Joint::getType (void) const [inline]
Request the type of the joint.
Returns:
const reference to the type
Definition at line 88 of file joint.hpp.
Referenced by iTaSC::Armature::addLimitConstraint(), iTaSC::Armature::addSegment(), base_callback(), and execute_scene().
const std::string KDL::Joint::getTypeName () const [inline]
Request the stringified type of the joint.
Returns:
const string
Definition at line 98 of file joint.hpp.
References None, RotX, RotY, RotZ, Sphere, Swing, TransX, TransY, and TransZ.
Referenced by KDL::operator<<().
Joint & KDL::Joint::operator= (const Joint & arg)
Definition at line 42 of file joint.cpp.
Frame KDL::Joint::pose (const double & q) const
Request the 6D-pose between the beginning and the end of the joint at joint position q
Parameters:
q the 1D joint position
Returns:
the resulting 6D-pose
Definition at line 58 of file joint.cpp.
References KDL::Frame::Identity(), Rot(), KDL::Rotation::RotX(), RotX, KDL::Rotation::RotY(), RotY, KDL::Rotation::RotZ(), RotZ, Sphere, Swing, TransX, TransY, and TransZ.
Referenced by KDL::ChainJntToJacSolver::JntToJac(), and KDL::Segment::pose().
Twist KDL::Joint::twist (const double & qdot, int dof = 0) const
Request the resulting 6D-velocity with a joint velocity qdot
Parameters:
qdot the 1D joint velocity
Returns:
the resulting 6D-velocity
Definition at line 96 of file joint.cpp.
References RotX, RotY, RotZ, Sphere, Swing, TransX, TransY, TransZ, and KDL::Twist::Zero().
Referenced by KDL::Segment::twist().
The documentation for this class was generated from the following files:
joint.hpp
joint.cpp