Blender: btContactConstraint.h File Reference
btContactConstraint.h File Reference
#include "LinearMath/btVector3.h"
#include "btJacobianEntry.h"
#include "btTypedConstraint.h"
#include "BulletCollision/NarrowPhaseCollision/btPersistentManifold.h"
Functions
ATTRIBUTE_ALIGNED16 (class) btContactConstraint
btContactConstraint can be automatically created to solve contact constraints using the unified btTypedConstraint interface
void resolveSingleBilateral (btRigidBody &body1, const btVector3 &pos1, btRigidBody &body2, const btVector3 &pos2, btScalar distance, const btVector3 &normal, btScalar &impulse, btScalar timeStep)
resolveSingleBilateral is an obsolete methods used for vehicle friction between two dynamic objects
Function Documentation
ATTRIBUTE_ALIGNED16 (class)
btContactConstraint can be automatically created to solve contact constraints using the unified btTypedConstraint interface
obsolete methods
Definition at line 25 of file btContactConstraint.h.
void resolveSingleBilateral (btRigidBody & body1, const btVector3 & pos1, btRigidBody & body2, const btVector3 & pos2, btScalar distance, const btVector3 & normal, btScalar & impulse, btScalar timeStep)
resolveSingleBilateral is an obsolete methods used for vehicle friction between two dynamic objects
Definition at line 77 of file btContactConstraint.cpp.
References ASSERT2, btFabs(), btRigidBody::getAngularVelocity(), btTransform::getBasis(), btRigidBody::getCenterOfMassPosition(), btRigidBody::getCenterOfMassTransform(), btRigidBody::getInvInertiaDiagLocal(), btRigidBody::getInvMass(), btRigidBody::getLinearVelocity(), btRigidBody::getVelocityInLocalPoint(), and btMatrix3x3::transpose().
Referenced by btRaycastVehicle::updateFriction().