Blender: rna_wm.c File Reference
rna_wm.c File Reference
RNA
#include <stdlib.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_userdef_types.h"
#include "DNA_windowmanager_types.h"
#include "WM_types.h"
Defines
#define KMI_TYPE_KEYBOARD 0
#define KMI_TYPE_MOUSE 1
#define KMI_TYPE_TWEAK 2
#define KMI_TYPE_TEXTINPUT 3
#define KMI_TYPE_TIMER 4
#define KMI_TYPE_NDOF 5
Functions
static void rna_def_operator (BlenderRNA *brna)
static void rna_def_macro_operator (BlenderRNA *brna)
static void rna_def_operator_type_macro (BlenderRNA *brna)
static void rna_def_operator_utils (BlenderRNA *brna)
static void rna_def_operator_filelist_element (BlenderRNA *brna)
static void rna_def_event (BlenderRNA *brna)
static void rna_def_timer (BlenderRNA *brna)
static void rna_def_window (BlenderRNA *brna)
static void rna_def_wm_keyconfigs (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_windowmanager (BlenderRNA *brna)
static void rna_def_keymap_items (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_wm_keymaps (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_keyconfig (BlenderRNA *brna)
void RNA_def_wm (BlenderRNA *brna)
Variables
EnumPropertyItem event_keymouse_value_items []
EnumPropertyItem event_tweak_value_items []
EnumPropertyItem event_value_items []
EnumPropertyItem event_tweak_type_items []
EnumPropertyItem event_mouse_type_items []
EnumPropertyItem event_timer_type_items []
EnumPropertyItem event_ndof_type_items []
EnumPropertyItem event_type_items []
EnumPropertyItem keymap_propvalue_items []
EnumPropertyItem operator_flag_items []
EnumPropertyItem operator_return_items []
EnumPropertyItem wm_report_items []
Detailed Description
Definition in file rna_wm.c.
Define Documentation
#define KMI_TYPE_KEYBOARD 0
Definition at line 407 of file rna_wm.c.
Referenced by rna_def_keyconfig().
#define KMI_TYPE_MOUSE 1
Definition at line 408 of file rna_wm.c.
Referenced by rna_def_keyconfig().
#define KMI_TYPE_NDOF 5
Definition at line 412 of file rna_wm.c.
Referenced by rna_def_keyconfig().
#define KMI_TYPE_TEXTINPUT 3
Definition at line 410 of file rna_wm.c.
Referenced by rna_def_keyconfig().
#define KMI_TYPE_TIMER 4
Definition at line 411 of file rna_wm.c.
Referenced by rna_def_keyconfig().
#define KMI_TYPE_TWEAK 2
Definition at line 409 of file rna_wm.c.
Referenced by rna_def_keyconfig().
Function Documentation
static void rna_def_event (BlenderRNA * brna) [static]
Definition at line 1431 of file rna_wm.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_string_funcs(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and RNA_define_verify_sdna().
Referenced by RNA_def_wm().
static void rna_def_keyconfig (BlenderRNA * brna) [static]
Definition at line 1669 of file rna_wm.c.
References KEYCONF_USER, KEYMAP_CHILDREN_EXPANDED, KEYMAP_EXPANDED, KEYMAP_MODAL, KEYMAP_USER_MODIFIED, KMI_EXPANDED, KMI_INACTIVE, KMI_TYPE_KEYBOARD, KMI_TYPE_MOUSE, KMI_TYPE_NDOF, KMI_TYPE_TEXTINPUT, KMI_TYPE_TIMER, KMI_TYPE_TWEAK, KMI_USER_MODIFIED, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, region_type_items, RNA_api_keyconfig(), RNA_api_keymap(), RNA_api_keymapitem(), rna_def_keymap_items(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_wm_keymaps(), and space_type_items.
Referenced by RNA_def_wm().
static void rna_def_keymap_items (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1645 of file rna_wm.c.
References NULL, RNA_api_keymapitems(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_keyconfig().
static void rna_def_macro_operator (BlenderRNA * brna) [static]
Definition at line 1315 of file rna_wm.c.
References NULL, OP_MAX_TYPENAME, PROP_EDITABLE, PROP_ENUM, PROP_ENUM_FLAG, PROP_NEVER_CLAMP, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REGISTER, PROP_REGISTER_OPTIONAL, PROP_STRING, PROP_TRANSLATE, RNA_api_macro(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and RNA_DYN_DESCR_MAX.
Referenced by RNA_def_wm().
static void rna_def_operator (BlenderRNA * brna) [static]
Definition at line 1240 of file rna_wm.c.
References NULL, OP_MAX_TYPENAME, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_ENUM_FLAG, PROP_NEVER_CLAMP, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REGISTER, PROP_REGISTER_OPTIONAL, PROP_STRING, PROP_TRANSLATE, RNA_api_operator(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_idprops_func(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and RNA_DYN_DESCR_MAX.
Referenced by RNA_def_wm().
static void rna_def_operator_filelist_element (BlenderRNA * brna) [static]
Definition at line 1417 of file rna_wm.c.
References PROP_FILENAME, PROP_IDPROPERTY, PROP_STRING, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_wm().
static void rna_def_operator_type_macro (BlenderRNA * brna) [static]
Definition at line 1377 of file rna_wm.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_wm().
static void rna_def_operator_utils (BlenderRNA * brna) [static]
Definition at line 1399 of file rna_wm.c.
References PROP_FLOAT, PROP_IDPROPERTY, PROP_NONE, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_flag(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_wm().
static void rna_def_timer (BlenderRNA * brna) [static]
Definition at line 1524 of file rna_wm.c.
References NULL, PROP_EDITABLE, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and RNA_define_verify_sdna().
Referenced by RNA_def_wm().
static void rna_def_window (BlenderRNA * brna) [static]
Definition at line 1554 of file rna_wm.c.
References NULL, PROP_CONTEXT_UPDATE, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_wm().
static void rna_def_windowmanager (BlenderRNA * brna) [static]
Definition at line 1613 of file rna_wm.c.
References PROP_COLLECTION, PROP_NONE, PROP_STRING, RNA_api_wm(), RNA_def_property(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_wm_keyconfigs(), and STRUCT_ID_REFCOUNT.
Referenced by RNA_def_wm().
void RNA_def_wm (BlenderRNA * brna)
Definition at line 1882 of file rna_wm.c.
References rna_def_event(), rna_def_keyconfig(), rna_def_macro_operator(), rna_def_operator(), rna_def_operator_filelist_element(), rna_def_operator_type_macro(), rna_def_operator_utils(), rna_def_timer(), rna_def_window(), and rna_def_windowmanager().
static void rna_def_wm_keyconfigs (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1574 of file rna_wm.c.
References NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_api_keyconfigs(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_windowmanager().
static void rna_def_wm_keymaps (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1657 of file rna_wm.c.
References NULL, RNA_api_keymaps(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_keyconfig().
Variable Documentation
EnumPropertyItem event_keymouse_value_items[]
Initial value:
 {
    {KM_ANY, "ANY", 0, "Any", ""},
    {KM_PRESS, "PRESS", 0, "Press", ""},
    {KM_RELEASE, "RELEASE", 0, "Release", ""},
    {KM_CLICK, "CLICK", 0, "Click", ""},
    {KM_DBL_CLICK, "DOUBLE_CLICK", 0, "Double Click", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 43 of file rna_wm.c.
EnumPropertyItem event_mouse_type_items[]
Initial value:
 {
    {LEFTMOUSE, "LEFTMOUSE", 0, "Left", ""},
    {MIDDLEMOUSE, "MIDDLEMOUSE", 0, "Middle", ""},
    {RIGHTMOUSE, "RIGHTMOUSE", 0, "Right", ""},
    {BUTTON4MOUSE, "BUTTON4MOUSE", 0, "Button4", ""},
    {BUTTON5MOUSE, "BUTTON5MOUSE", 0, "Button5", ""},
    {ACTIONMOUSE, "ACTIONMOUSE", 0, "Action", ""},
    {SELECTMOUSE, "SELECTMOUSE", 0, "Select", ""},
    {0, "", 0, NULL, NULL},
    {MOUSEMOVE, "MOUSEMOVE", 0, "Move", ""},
    {MOUSEPAN, "TRACKPADPAN", 0, "Mouse/Trackpad Pan", ""},
    {MOUSEZOOM, "TRACKPADZOOM", 0, "Mouse/Trackpad Zoom", ""},
    {MOUSEROTATE, "MOUSEROTATE", 0, "Mouse/Trackpad Rotate", ""},
    {0, "", 0, NULL, NULL},
    {WHEELUPMOUSE, "WHEELUPMOUSE", 0, "Wheel Up", ""},
    {WHEELDOWNMOUSE, "WHEELDOWNMOUSE", 0, "Wheel Down", ""},
    {WHEELINMOUSE, "WHEELINMOUSE", 0, "Wheel In", ""},
    {WHEELOUTMOUSE, "WHEELOUTMOUSE", 0, "Wheel Out", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 88 of file rna_wm.c.
EnumPropertyItem event_ndof_type_items[]
Definition at line 115 of file rna_wm.c.
EnumPropertyItem event_timer_type_items[]
Initial value:
 {
    {TIMER, "TIMER", 0, "Timer", ""},
    {TIMER0, "TIMER0", 0, "Timer 0", ""},
    {TIMER1, "TIMER1", 0, "Timer 1", ""},
    {TIMER2, "TIMER2", 0, "Timer 2", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 108 of file rna_wm.c.
EnumPropertyItem event_tweak_type_items[]
Initial value:
 {
    {EVT_TWEAK_L, "EVT_TWEAK_L", 0, "Left", ""},
    {EVT_TWEAK_M, "EVT_TWEAK_M", 0, "Middle", ""},
    {EVT_TWEAK_R, "EVT_TWEAK_R", 0, "Right", ""},
    {EVT_TWEAK_A, "EVT_TWEAK_A", 0, "Action", ""},
    {EVT_TWEAK_S, "EVT_TWEAK_S", 0, "Select", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 80 of file rna_wm.c.
EnumPropertyItem event_tweak_value_items[]
Initial value:
 {
    {KM_ANY, "ANY", 0, "Any", ""},
    {EVT_GESTURE_N, "NORTH", 0, "North", ""},
    {EVT_GESTURE_NE, "NORTH_EAST", 0, "North-East", ""},
    {EVT_GESTURE_E, "EAST", 0, "East", ""},
    {EVT_GESTURE_SE, "SOUTH_EAST", 0, "South-East", ""},
    {EVT_GESTURE_S, "SOUTH", 0, "South", ""},
    {EVT_GESTURE_SW, "SOUTH_WEST", 0, "South-West", ""},
    {EVT_GESTURE_W, "WEST", 0, "West", ""},
    {EVT_GESTURE_NW, "NORTH_WEST", 0, "North-West", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 51 of file rna_wm.c.
EnumPropertyItem event_type_items[]
Definition at line 164 of file rna_wm.c.
Referenced by RNA_api_keymapitems(), rna_def_joystick_sensor(), rna_def_keyboard_sensor(), rna_def_scene_game_data(), WM_event_print(), and WM_key_event_string().
EnumPropertyItem event_value_items[]
Initial value:
 {
    {KM_ANY, "ANY", 0, "Any", ""},
    {KM_NOTHING, "NOTHING", 0, "Nothing", ""},
    {KM_PRESS, "PRESS", 0, "Press", ""},
    {KM_RELEASE, "RELEASE", 0, "Release", ""},
    {KM_CLICK, "CLICK", 0, "Click", ""},
    {KM_DBL_CLICK, "DOUBLE_CLICK", 0, "Double Click", ""},
    {EVT_GESTURE_N, "NORTH", 0, "North", ""},
    {EVT_GESTURE_NE, "NORTH_EAST", 0, "North-East", ""},
    {EVT_GESTURE_E, "EAST", 0, "East", ""},
    {EVT_GESTURE_SE, "SOUTH_EAST", 0, "South-East", ""},
    {EVT_GESTURE_S, "SOUTH", 0, "South", ""},
    {EVT_GESTURE_SW, "SOUTH_WEST", 0, "South-West", ""},
    {EVT_GESTURE_W, "WEST", 0, "West", ""},
    {EVT_GESTURE_NW, "NORTH_WEST", 0, "North-West", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 63 of file rna_wm.c.
Referenced by RNA_api_keymapitems(), and WM_event_print().
EnumPropertyItem keymap_propvalue_items[]
Initial value:
 {
        {0, "NONE", 0, "", ""},
        {0, NULL, 0, NULL, NULL}}
Definition at line 362 of file rna_wm.c.
EnumPropertyItem operator_flag_items[]
Initial value:
 {
    {OPTYPE_REGISTER, "REGISTER", 0, "Register", "Display in the info window and support the redo toolbar panel"},
    {OPTYPE_UNDO, "UNDO", 0, "Undo", "Push an undo event (needed for operator redo)"},
    {OPTYPE_BLOCKING, "BLOCKING", 0, "Blocking", "Block anything else from using the cursor"},
    {OPTYPE_MACRO, "MACRO", 0, "Macro", "Use to check if an operator is a macro"},
    {OPTYPE_GRAB_POINTER, "GRAB_POINTER", 0, "Grab Pointer",
                          "Use so the operator grabs the mouse focus, enables wrapping when continuous grab "
                          "is enabled"},
    {OPTYPE_PRESET, "PRESET", 0, "Preset", "Display a preset button with the operators settings"},
    {OPTYPE_INTERNAL, "INTERNAL", 0, "Internal", "Removes the operator from search results"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 375 of file rna_wm.c.
EnumPropertyItem operator_return_items[]
Initial value:
 {
    {OPERATOR_RUNNING_MODAL, "RUNNING_MODAL", 0, "Running Modal", "Keep the operator running with blender"},
    {OPERATOR_CANCELLED, "CANCELLED", 0, "Cancelled", "When no action has been taken, operator exits"},
    {OPERATOR_FINISHED, "FINISHED", 0, "Finished", "When the operator is complete, operator exits"},
    {OPERATOR_PASS_THROUGH, "PASS_THROUGH", 0, "Pass Through", "Do nothing and pass the event on"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 387 of file rna_wm.c.
Referenced by pyop_call(), RNA_api_operator(), and rna_generic_op_invoke().
EnumPropertyItem wm_report_items[]
Initial value:
 {
    {RPT_DEBUG, "DEBUG", 0, "Debug", ""},
    {RPT_INFO, "INFO", 0, "Info", ""},
    {RPT_OPERATOR, "OPERATOR", 0, "Operator", ""},
    {RPT_WARNING, "WARNING", 0, "Warning", ""},
    {RPT_ERROR, "ERROR", 0, "Error", ""},
    {RPT_ERROR_INVALID_INPUT, "ERROR_INVALID_INPUT", 0, "Invalid Input", ""},
    {RPT_ERROR_INVALID_CONTEXT, "ERROR_INVALID_CONTEXT", 0, "Invalid Context", ""},
    {RPT_ERROR_OUT_OF_MEMORY, "ERROR_OUT_OF_MEMORY", 0, "Out of Memory", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 396 of file rna_wm.c.
Referenced by RNA_api_macro(), RNA_api_operator(), and rna_def_render_engine().