Blender: btSerializer Class Reference
btSerializer Class Reference
#include <btSerializer.h>
Public Member Functions
virtual ~btSerializer ()
virtual const unsigned char * getBufferPointer () const =0
virtual int getCurrentBufferSize () const =0
virtual btChunk * allocate (size_t size, int numElements)=0
virtual void finalizeChunk (btChunk *chunk, const char *structType, int chunkCode, void *oldPtr)=0
virtual void * findPointer (void *oldPtr)=0
virtual void * getUniquePointer (void *oldPtr)=0
virtual void startSerialization ()=0
virtual void finishSerialization ()=0
virtual const char * findNameForPointer (const void *ptr) const =0
virtual void registerNameForPointer (const void *ptr, const char *name)=0
virtual void serializeName (const char *ptr)=0
virtual int getSerializationFlags () const =0
virtual void setSerializationFlags (int flags)=0
Detailed Description
Definition at line 69 of file btSerializer.h.
Constructor & Destructor Documentation
virtual btSerializer::~btSerializer () [inline, virtual]
Definition at line 74 of file btSerializer.h.
Member Function Documentation
virtual btChunk* btSerializer::allocate (size_t size, int numElements) [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btSoftBody::serialize(), btTriangleInfoMap::serialize(), btStridingMeshInterface::serialize(), btMultiSphereShape::serialize(), btDiscreteDynamicsWorld::serializeRigidBodies(), btRigidBody::serializeSingleObject(), btCollisionShape::serializeSingleShape(), and btSoftRigidDynamicsWorld::serializeSoftBodies().
virtual void btSerializer::finalizeChunk (btChunk * chunk, const char * structType, int chunkCode, void * oldPtr) [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btSoftBody::serialize(), btTriangleInfoMap::serialize(), btStridingMeshInterface::serialize(), btMultiSphereShape::serialize(), btDiscreteDynamicsWorld::serializeRigidBodies(), btRigidBody::serializeSingleObject(), btCollisionShape::serializeSingleShape(), and btSoftRigidDynamicsWorld::serializeSoftBodies().
virtual const char* btSerializer::findNameForPointer (const void * ptr) const [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btTypedConstraint::serialize(), and btCollisionShape::serialize().
virtual void* btSerializer::findPointer (void * oldPtr) [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btSoftBody::serialize().
virtual void btSerializer::finishSerialization () [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btSoftRigidDynamicsWorld::serialize(), btCollisionWorld::serialize(), and btDiscreteDynamicsWorld::serialize().
virtual const unsigned char* btSerializer::getBufferPointer () const [pure virtual]
Implemented in btDefaultSerializer.
virtual int btSerializer::getCurrentBufferSize () const [pure virtual]
Implemented in btDefaultSerializer.
virtual int btSerializer::getSerializationFlags () const [pure virtual]
Implemented in btDefaultSerializer.
virtual void* btSerializer::getUniquePointer (void * oldPtr) [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btTypedConstraint::serialize(), btCollisionShape::serialize(), btSoftBody::serialize(), btTriangleInfoMap::serialize(), btStridingMeshInterface::serialize(), and btMultiSphereShape::serialize().
virtual void btSerializer::registerNameForPointer (const void * ptr, const char * name) [pure virtual]
Implemented in btDefaultSerializer.
virtual void btSerializer::serializeName (const char * ptr) [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btTypedConstraint::serialize(), and btCollisionShape::serialize().
virtual void btSerializer::setSerializationFlags (int flags) [pure virtual]
Implemented in btDefaultSerializer.
virtual void btSerializer::startSerialization () [pure virtual]
Implemented in btDefaultSerializer.
Referenced by btSoftRigidDynamicsWorld::serialize(), btCollisionWorld::serialize(), and btDiscreteDynamicsWorld::serialize().
The documentation for this class was generated from the following file:
btSerializer.h