Blender: paint_hide.c File Reference
paint_hide.c File Reference
sculpt and paint
#include "MEM_guardedalloc.h"
#include "BLI_bitmap.h"
#include "BLI_listbase.h"
#include "BLI_math_vector.h"
#include "BLI_pbvh.h"
#include "BLI_utildefines.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BKE_context.h"
#include "BKE_DerivedMesh.h"
#include "BKE_mesh.h"
#include "BKE_multires.h"
#include "BKE_paint.h"
#include "BKE_subsurf.h"
#include "BIF_glutil.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "paint_intern.h"
#include "sculpt_intern.h"
#include <assert.h>
Functions
static int planes_contain_v3 (float(*planes)[4], int totplane, const float p[3])
static int is_effected (PartialVisArea area, float planes[4][4], const float co[3])
static void partialvis_update_mesh (Object *ob, PBVH *pbvh, PBVHNode *node, PartialVisAction action, PartialVisArea area, float planes[4][4])
static void partialvis_update_grids (Object *ob, PBVH *pbvh, PBVHNode *node, PartialVisAction action, PartialVisArea area, float planes[4][4])
static void rect_from_props (rcti *rect, PointerRNA *ptr)
static void clip_planes_from_rect (bContext *C, float clip_planes[4][4], const rcti *rect)
static void get_pbvh_nodes (PBVH *pbvh, PBVHNode ***nodes, int *totnode, float clip_planes[4][4], PartialVisArea mode)
static int hide_show_exec (bContext *C, wmOperator *op)
static int hide_show_invoke (bContext *C, wmOperator *op, wmEvent *event)
void PAINT_OT_hide_show (struct wmOperatorType *ot)
Detailed Description
Definition in file paint_hide.c.
Function Documentation
static void clip_planes_from_rect (bContext * C, float clip_planes[4][4], const rcti * rect) [static]
Definition at line 232 of file paint_hide.c.
References ViewContext::ar, ED_view3d_calc_clipping(), mul_m4_fl(), ViewContext::obact, ViewContext::rv3d, view3d_get_transformation(), view3d_operator_needs_opengl(), and view3d_set_viewcontext().
Referenced by hide_show_exec().
static void get_pbvh_nodes (PBVH * pbvh, PBVHNode *** nodes, int * totnode, float clip_planes[4][4], PartialVisArea mode) [static]
Definition at line 251 of file paint_hide.c.
References BLI_pbvh_node_planes_contain_AABB(), BLI_pbvh_node_planes_exclude_AABB(), BLI_pbvh_search_gather(), NULL, PARTIALVIS_ALL, PARTIALVIS_INSIDE, and PARTIALVIS_OUTSIDE.
Referenced by hide_show_exec().
static int hide_show_exec (bContext * C, wmOperator * op) [static]
Definition at line 274 of file paint_hide.c.
References BLI_pbvh_type(), CD_MASK_BAREMESH, clip_planes_from_rect(), CTX_data_active_object(), CTX_data_scene(), CTX_wm_region(), Object::data, ED_region_tag_redraw(), get_pbvh_nodes(), DerivedMesh::getPBVH, i, Mesh::medge, MEM_freeN(), mesh_flush_hidden_from_verts(), mesh_get_derived_final(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, nodes, OPERATOR_FINISHED, PARTIALVIS_HIDE, PARTIALVIS_SHOW, partialvis_update_grids(), partialvis_update_mesh(), SculptSession::pbvh, PBVH_FACES, PBVH_GRIDS, wmOperator::ptr, rect_from_props(), RNA_enum_get(), Object::sculpt, sculpt_undo_push_begin(), sculpt_undo_push_end(), Mesh::totedge, and Mesh::totpoly.
Referenced by PAINT_OT_hide_show().
static int hide_show_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 343 of file paint_hide.c.
References wmOperatorType::exec, PARTIALVIS_ALL, wmOperator::ptr, RNA_enum_get(), wmOperator::type, and WM_border_select_invoke().
Referenced by PAINT_OT_hide_show().
static int is_effected (PartialVisArea area, float planes[4][4], const float co[3]) [static]
Definition at line 86 of file paint_hide.c.
References PARTIALVIS_ALL, PARTIALVIS_INSIDE, PARTIALVIS_OUTSIDE, and planes_contain_v3().
Referenced by partialvis_update_grids(), and partialvis_update_mesh().
void PAINT_OT_hide_show (struct wmOperatorType * ot)
Definition at line 353 of file paint_hide.c.
References wmOperatorType::exec, wmOperatorType::flag, hide_show_exec(), hide_show_invoke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, NULL, OPTYPE_REGISTER, PARTIALVIS_ALL, PARTIALVIS_HIDE, PARTIALVIS_INSIDE, PARTIALVIS_OUTSIDE, PARTIALVIS_SHOW, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), sculpt_mode_poll(), wmOperatorType::srna, and WM_border_select_modal().
Referenced by ED_operatortypes_paint().
static void partialvis_update_grids (Object * ob, PBVH * pbvh, PBVHNode * node, PartialVisAction action, PartialVisArea area, float planes[4][4]) [static]
Definition at line 139 of file paint_hide.c.
References BLI_BITMAP_GET, BLI_BITMAP_MODIFY, BLI_BITMAP_NEW, BLI_pbvh_grid_hidden(), BLI_pbvh_node_fully_hidden_set(), BLI_pbvh_node_get_grids(), BLI_pbvh_node_mark_rebuild_draw(), DMGridData::co, co, g, i, is_effected(), MEM_freeN(), MULTIRES_HIDDEN_MODIFIED, multires_mark_as_modified(), NULL, PARTIALVIS_ALL, PARTIALVIS_HIDE, PARTIALVIS_SHOW, SCULPT_UNDO_HIDDEN, and sculpt_undo_push_node().
Referenced by hide_show_exec().
static void partialvis_update_mesh (Object * ob, PBVH * pbvh, PBVHNode * node, PartialVisAction action, PartialVisArea area, float planes[4][4]) [static]
Definition at line 99 of file paint_hide.c.
References BLI_pbvh_node_fully_hidden_set(), BLI_pbvh_node_get_verts(), BLI_pbvh_node_mark_rebuild_draw(), BLI_pbvh_node_num_verts(), MVert::co, MVert::flag, i, is_effected(), ME_HIDE, NULL, PARTIALVIS_HIDE, SCULPT_UNDO_HIDDEN, and sculpt_undo_push_node().
Referenced by hide_show_exec().
static int planes_contain_v3 (float(*) planes[4], int totplane, const float p[3]) [static]
Definition at line 73 of file paint_hide.c.
References dot_v3v3(), and i.
Referenced by is_effected().
static void rect_from_props (rcti * rect, PointerRNA * ptr) [static]
Definition at line 224 of file paint_hide.c.
References RNA_int_get(), rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by hide_show_exec().