Blender: modifier.c File Reference
modifier.c File Reference
blenkernel
#include <stddef.h>
#include <string.h>
#include <stdarg.h>
#include <math.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "DNA_armature_types.h"
#include "DNA_object_types.h"
#include "DNA_meshdata_types.h"
#include "BLI_utildefines.h"
#include "BLI_path_util.h"
#include "BLI_listbase.h"
#include "BLI_linklist.h"
#include "BLI_string.h"
#include "BKE_cloth.h"
#include "BKE_key.h"
#include "BKE_multires.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "MOD_modifiertypes.h"
Functions
ModifierTypeInfo * modifierType_getInfo (ModifierType type)
ModifierData * modifier_new (int type)
void modifier_free (ModifierData *md)
void modifier_unique_name (ListBase *modifiers, ModifierData *md)
int modifier_dependsOnTime (ModifierData *md)
int modifier_supportsMapping (ModifierData *md)
int modifier_isPreview (ModifierData *md)
ModifierData * modifiers_findByType (Object *ob, ModifierType type)
ModifierData * modifiers_findByName (Object *ob, const char *name)
void modifiers_clearErrors (Object *ob)
void modifiers_foreachObjectLink (Object *ob, ObjectWalkFunc walk, void *userData)
void modifiers_foreachIDLink (Object *ob, IDWalkFunc walk, void *userData)
void modifiers_foreachTexLink (Object *ob, TexWalkFunc walk, void *userData)
void modifier_copyData (ModifierData *md, ModifierData *target)
int modifier_couldBeCage (struct Scene *scene, ModifierData *md)
int modifier_sameTopology (ModifierData *md)
int modifier_nonGeometrical (ModifierData *md)
void modifier_setError (ModifierData *md, const char *format,...)
int modifiers_getCageIndex (struct Scene *scene, Object *ob, int *lastPossibleCageIndex_r, int virtual_)
int modifiers_isSoftbodyEnabled (Object *ob)
int modifiers_isClothEnabled (Object *ob)
int modifiers_isParticleEnabled (Object *ob)
int modifier_isEnabled (struct Scene *scene, ModifierData *md, int required_mode)
CDMaskLink * modifiers_calcDataMasks (struct Scene *scene, Object *ob, ModifierData *md, CustomDataMask dataMask, int required_mode)
ModifierData * modifiers_getLastPreview (struct Scene *scene, ModifierData *md, int required_mode)
ModifierData * modifiers_getVirtualModifierList (Object *ob)
Object * modifiers_isDeformedByArmature (Object *ob)
Object * modifiers_isDeformedByLattice (Object *ob)
int modifiers_usesArmature (Object *ob, bArmature *arm)
int modifier_isCorrectableDeformed (ModifierData *md)
int modifiers_isCorrectableDeformed (Object *ob)
int modifiers_isPreview (Object *ob)
int modifiers_indexInObject (Object *ob, ModifierData *md_seek)
void modifier_freeTemporaryData (ModifierData *md)
void test_object_modifiers (Object *ob)
const char * modifier_path_relbase (Object *ob)
void modifier_path_init (char *path, int path_maxlen, const char *name)
Detailed Description
Definition in file modifier.c.
Function Documentation
void modifier_copyData (ModifierData * md, ModifierData * target)
Definition at line 229 of file modifier.c.
References ModifierTypeInfo::copyData, ModifierData::mode, modifierType_getInfo(), mti, and ModifierData::type.
Referenced by copy_attr(), copy_object(), copy_particlesystem(), ED_object_modifier_copy(), modifiers_convertToReal(), and object_link_modifiers().
int modifier_couldBeCage (struct Scene * scene, ModifierData * md)
Definition at line 239 of file modifier.c.
References eModifierMode_Editmode, eModifierMode_Realtime, ModifierTypeInfo::isDisabled, ModifierData::mode, modifier_supportsMapping(), modifierType_getInfo(), mti, ModifierData::scene, and ModifierData::type.
Referenced by draw_modifier().
int modifier_dependsOnTime (ModifierData * md)
Definition at line 129 of file modifier.c.
References ModifierTypeInfo::dependsOnTime, modifierType_getInfo(), mti, and ModifierData::type.
Referenced by BL_ModifierDeformer::HasCompatibleDeformer(), and object_modifiers_use_time().
void modifier_free (ModifierData * md)
Definition at line 110 of file modifier.c.
References ModifierData::error, ModifierTypeInfo::freeData, MEM_freeN(), modifierType_getInfo(), mti, and ModifierData::type.
Referenced by ED_object_modifier_apply(), free_hair(), lib_link_particlesystems(), modifiers_getVirtualModifierList(), object_free_modifiers(), object_hook_remove_exec(), object_modifier_remove(), and object_remove_particle_system().
void modifier_freeTemporaryData (ModifierData * md)
Definition at line 603 of file modifier.c.
References eModifierType_Armature, MEM_freeN(), NULL, ArmatureModifierData::prevCos, and ModifierData::type.
Referenced by mesh_calc_modifiers().
int modifier_isCorrectableDeformed (ModifierData * md)
Definition at line 556 of file modifier.c.
References eModifierType_Armature, eModifierType_ShapeKey, and ModifierData::type.
Referenced by editbmesh_get_first_deform_matrices(), and modifiers_isCorrectableDeformed().
int modifier_isEnabled (struct Scene * scene, ModifierData * md, int required_mode)
Definition at line 343 of file modifier.c.
References eModifierMode_DisableTemporary, eModifierMode_Editmode, eModifierMode_Render, eModifierTypeFlag_SupportsEditmode, ModifierTypeInfo::flags, ModifierTypeInfo::isDisabled, ModifierData::mode, modifierType_getInfo(), mti, ModifierData::scene, and ModifierData::type.
Referenced by crazyspace_build_sculpt(), curve_get_tessellate_point(), editbmesh_modifier_is_enabled(), find_multires_modifier_before(), get_multires_modifier(), mesh_calc_modifiers(), modifiers_calcDataMasks(), modifiers_getLastPreview(), multiresbake_check(), object_is_modified(), sculpt_get_first_deform_matrices(), sculpt_has_active_modifiers(), sculpt_modifiers_active(), and sculpt_multires_active().
int modifier_isPreview (ModifierData * md)
Definition at line 144 of file modifier.c.
References eModifierMode_Realtime, eModifierTypeFlag_UsesPreview, FALSE, ModifierTypeInfo::flags, ModifierData::mode, modifierType_getInfo(), mti, TRUE, and ModifierData::type.
Referenced by modifiers_getLastPreview(), and modifiers_isPreview().
ModifierData* modifier_new (int type) [read]
Definition at line 90 of file modifier.c.
References BLI_strncpy(), eModifierMode_Editmode, eModifierMode_Expanded, eModifierMode_Realtime, eModifierMode_Render, eModifierTypeFlag_EnableInEditmode, ModifierTypeInfo::flags, ModifierTypeInfo::initData, MEM_callocN(), ModifierData::mode, modifierType_getInfo(), mti, ModifierTypeInfo::name, ModifierData::name, ModifierTypeInfo::structName, ModifierTypeInfo::structSize, and ModifierData::type.
Referenced by add_hook_object(), copy_attr(), copy_object(), copy_particlesystem(), direct_link_object(), do_hair_dynamics(), do_versions(), ED_object_modifier_add(), ED_object_modifier_copy(), modifiers_convertToReal(), modifiers_getVirtualModifierList(), multires_load_old(), object_add_particle_system(), and object_link_modifiers().
int modifier_nonGeometrical (ModifierData * md)
Definition at line 258 of file modifier.c.
References eModifierTypeType_NonGeometrical, modifierType_getInfo(), mti, ModifierData::type, and ModifierTypeInfo::type.
Referenced by draw_modifier().
void modifier_path_init (char * path, int path_maxlen, const char * name)
Definition at line 658 of file modifier.c.
References BLI_join_dirfile(), BLI_temporary_dir(), and G.
Referenced by dynamicPaint_createNewSurface(), fluidsim_init(), and initData().
const char* modifier_path_relbase (Object * ob)
Definition at line 645 of file modifier.c.
References BLI_temporary_dir(), G, Object::id, ID_BLEND_PATH, and ID::lib.
Referenced by ocean_bake_exec(), and particles_fluid_step().
int modifier_sameTopology (ModifierData * md)
Definition at line 251 of file modifier.c.
References ELEM3, eModifierTypeType_Nonconstructive, eModifierTypeType_NonGeometrical, eModifierTypeType_OnlyDeform, modifierType_getInfo(), mti, ModifierTypeInfo::type, and ModifierData::type.
Referenced by draw_modifier(), and modifier_apply_shape().
void modifier_setError (ModifierData * md, const char * format, ...)
Definition at line 264 of file modifier.c.
References BLI_strdup(), ModifierData::error, and MEM_freeN().
Referenced by cloth_from_mesh(), cloth_from_object(), editbmesh_modifier_is_enabled(), mesh_calc_modifiers(), meshdeform_matrix_solve(), and meshdeformModifier_do().
int modifier_supportsMapping (ModifierData * md)
Definition at line 136 of file modifier.c.
References eModifierTypeFlag_SupportsMapping, eModifierTypeType_OnlyDeform, ModifierTypeInfo::flags, modifierType_getInfo(), mti, ModifierData::type, and ModifierTypeInfo::type.
Referenced by mesh_calc_modifiers(), modifier_couldBeCage(), and modifiers_getCageIndex().
void modifier_unique_name (ListBase * modifiers, ModifierData * md)
Definition at line 120 of file modifier.c.
References BLI_uniquename(), modifierType_getInfo(), mti, ModifierData::name, ModifierTypeInfo::name, and ModifierData::type.
Referenced by add_hook_object(), direct_link_object(), do_versions(), ED_object_modifier_add(), ED_object_modifier_copy(), modifiers_convertToReal(), and object_add_particle_system().
CDMaskLink* modifiers_calcDataMasks (struct Scene * scene, Object * ob, ModifierData * md, CustomDataMask dataMask, int required_mode) [read]
Definition at line 358 of file modifier.c.
References BLI_linklist_reverse(), CDMaskLink::mask, MEM_callocN(), modifier_isEnabled(), modifierType_getInfo(), mti, ModifierData::next, CDMaskLink::next, NULL, ModifierTypeInfo::requiredDataMask, and ModifierData::type.
Referenced by editbmesh_calc_modifiers(), and mesh_calc_modifiers().
void modifiers_clearErrors (Object * ob)
Definition at line 173 of file modifier.c.
References ModifierData::error, ListBase::first, MEM_freeN(), Object::modifiers, ModifierData::next, and NULL.
Referenced by editbmesh_calc_modifiers(), editbmesh_get_first_deform_matrices(), and mesh_calc_modifiers().
ModifierData* modifiers_findByName (Object * ob, const char * name) [read]
Definition at line 168 of file modifier.c.
References BLI_findstring(), and Object::modifiers.
Referenced by edit_modifier_property_get().
ModifierData* modifiers_findByType (Object * ob, ModifierType type) [read]
Definition at line 157 of file modifier.c.
References ListBase::first, Object::modifiers, ModifierData::next, and ModifierData::type.
Referenced by add_collider_cache_object(), add_collision_object(), add_verts_to_dgroups(), boid_find_ground(), buttons_context(), ccd_mesh_make(), ccd_mesh_update(), cloth_bvh_objcollision(), copy_attr(), do_versions(), draw_object(), dynamicPaint_doStep(), dynamicPaint_initBake(), ED_object_modifier_add(), get_orco_coords_dm(), init_frame_smoke(), lib_link_object(), load_fluidsimspeedvectors(), modifiers_isClothEnabled(), modifiers_isParticleEnabled(), modifiers_isSoftbodyEnabled(), multires_force_render_update(), object_remove_particle_system(), ocean_texture(), output_toggle_exec(), particle_edit_toggle_poll(), particles_fluid_step(), precalculate_effector(), psys_update_path_cache(), RE_Database_FromScene_Vectors(), subframe_updateObject(), surface_getBrushFlags(), surface_slot_add_exec(), surface_slot_remove_exec(), type_toggle_exec(), updateDepgraph(), and view3d_modeselect_pup().
void modifiers_foreachIDLink (Object * ob, IDWalkFunc walk, void * userData)
Definition at line 201 of file modifier.c.
References ListBase::first, ModifierTypeInfo::foreachIDLink, ModifierTypeInfo::foreachObjectLink, Object::modifiers, modifierType_getInfo(), mti, ModifierData::next, and ModifierData::type.
Referenced by dag_id_flush_update(), expand_object(), lib_link_modifiers(), and object_relink().
void modifiers_foreachObjectLink (Object * ob, ObjectWalkFunc walk, void * userData)
Definition at line 188 of file modifier.c.
References ListBase::first, ModifierTypeInfo::foreachObjectLink, Object::modifiers, modifierType_getInfo(), mti, ModifierData::next, and ModifierData::type.
Referenced by unlink_object().
void modifiers_foreachTexLink (Object * ob, TexWalkFunc walk, void * userData)
Definition at line 217 of file modifier.c.
References ListBase::first, ModifierTypeInfo::foreachTexLink, Object::modifiers, modifierType_getInfo(), mti, ModifierData::next, and ModifierData::type.
Referenced by buttons_texture_users_from_context().
int modifiers_getCageIndex (struct Scene * scene, Object * ob, int * lastPossibleCageIndex_r, int virtual_)
Definition at line 288 of file modifier.c.
References eModifierMode_DisableTemporary, eModifierMode_Editmode, eModifierMode_OnCage, eModifierMode_Realtime, eModifierTypeFlag_SupportsEditmode, ListBase::first, ModifierTypeInfo::flags, i, ModifierTypeInfo::isDisabled, modifier_supportsMapping(), Object::modifiers, modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, and ModifierData::next.
Referenced by createTransEditVerts(), editbmesh_calc_modifiers(), editbmesh_get_first_deform_matrices(), modifiers_setOnCage(), and uiTemplateModifier().
ModifierData* modifiers_getLastPreview (struct Scene * scene, ModifierData * md, int required_mode) [read]
Definition at line 404 of file modifier.c.
References eModifierMode_Realtime, modifier_isEnabled(), modifier_isPreview(), ModifierData::next, and NULL.
Referenced by mesh_calc_modifiers().
ModifierData* modifiers_getVirtualModifierList (Object * ob) [read]
Definition at line 419 of file modifier.c.
References Object::data, CurveModifierData::defaxis, ArmatureModifierData::deformflag, ELEM, eModifierMode_Editmode, eModifierMode_OnCage, eModifierMode_Virtual, eModifierType_Armature, eModifierType_Curve, eModifierType_Lattice, eModifierType_ShapeKey, ListBase::first, init(), ModifierData::mode, ShapeKeyModifierData::modifier, LatticeModifierData::modifier, CurveModifierData::modifier, ArmatureModifierData::modifier, modifier_free(), modifier_new(), Object::modifiers, ModifierData::next, OB_ARMATURE, OB_CURVE, ob_get_key(), OB_LATTICE, OB_MESH, OB_SHAPE_EDIT_MODE, LatticeModifierData::object, CurveModifierData::object, ArmatureModifierData::object, Object::parent, PARSKEL, Object::partype, Object::shapeflag, Object::trackflag, and Object::type.
Referenced by crazyspace_build_sculpt(), curve_calc_modifiers_post(), curve_calc_modifiers_pre(), curve_calc_orcodm(), curve_get_tessellate_point(), editbmesh_calc_modifiers(), editbmesh_get_first_deform_matrices(), lattice_calc_modifiers(), mesh_calc_modifiers(), modifiers_getCageIndex(), modifiers_isCorrectableDeformed(), modifiers_isDeformedByArmature(), modifiers_isDeformedByLattice(), modifiers_usesArmature(), object_is_modified(), sculpt_get_first_deform_matrices(), sculpt_has_active_modifiers(), sculpt_modifiers_active(), sculpt_multires_active(), uiTemplateModifier(), and wpaint_make_validmap().
int modifiers_indexInObject (Object * ob, ModifierData * md_seek)
Definition at line 593 of file modifier.c.
References ListBase::first, i, Object::modifiers, and ModifierData::next.
Referenced by mesh_calc_modifiers().
int modifiers_isClothEnabled (Object * ob)
Definition at line 329 of file modifier.c.
References eModifierMode_Realtime, eModifierMode_Render, eModifierType_Cloth, ModifierData::mode, and modifiers_findByType().
Referenced by build_dag_object().
int modifiers_isCorrectableDeformed (Object * ob)
Definition at line 566 of file modifier.c.
References eModifierMode_Editmode, ModifierData::mode, Object::mode, modifier_isCorrectableDeformed(), modifiers_getVirtualModifierList(), ModifierData::next, and OB_MODE_EDIT.
Referenced by createTransEditVerts().
Object* modifiers_isDeformedByArmature (Object * ob) [read]
Definition at line 495 of file modifier.c.
References eModifierType_Armature, Object::flag, modifiers_getVirtualModifierList(), ModifierData::next, NULL, ArmatureModifierData::object, SELECT, and ModifierData::type.
Referenced by createTransData(), draw_armature(), object_pose_armature_get(), ringcut_invoke(), set_wpaint(), weight_from_bones_exec(), weight_from_bones_poll(), and wpaint_stroke_test_start().
Object* modifiers_isDeformedByLattice (Object * ob) [read]
Definition at line 519 of file modifier.c.
References eModifierType_Lattice, Object::flag, modifiers_getVirtualModifierList(), ModifierData::next, NULL, LatticeModifierData::object, SELECT, and ModifierData::type.
Referenced by ringcut_invoke().
int modifiers_isParticleEnabled (Object * ob)
Definition at line 336 of file modifier.c.
References eModifierMode_Realtime, eModifierMode_Render, eModifierType_ParticleSystem, ModifierData::mode, and modifiers_findByType().
int modifiers_isPreview (Object * ob)
Definition at line 581 of file modifier.c.
References FALSE, ListBase::first, modifier_isPreview(), Object::modifiers, ModifierData::next, and TRUE.
Referenced by draw_mesh_fancy().
int modifiers_isSoftbodyEnabled (Object * ob)
Definition at line 322 of file modifier.c.
References eModifierMode_Realtime, eModifierMode_Render, eModifierType_Softbody, ModifierData::mode, and modifiers_findByType().
Referenced by build_dag_object().
int modifiers_usesArmature (Object * ob, bArmature * arm)
Definition at line 541 of file modifier.c.
References Object::data, eModifierType_Armature, modifiers_getVirtualModifierList(), ModifierData::next, ArmatureModifierData::object, and ModifierData::type.
Referenced by ED_armature_bone_rename().
ModifierTypeInfo* modifierType_getInfo (ModifierType type)
Definition at line 69 of file modifier.c.
References modifier_type_init(), NULL, NUM_MODIFIER_TYPES, and types.
Referenced by add_hook_object(), build_dag_object(), crazyspace_build_sculpt(), curve_calc_modifiers_post(), curve_calc_modifiers_pre(), curve_calc_orcodm(), curve_get_tessellate_point(), direct_link_modifiers(), do_versions(), draw_modifier(), ED_object_modifier_add(), ED_object_modifier_move_down(), ED_object_modifier_move_up(), editbmesh_calc_modifiers(), editbmesh_get_first_deform_matrices(), editbmesh_modifier_is_enabled(), get_multires_dm(), lattice_calc_modifiers(), mesh_calc_modifiers(), mesh_create_derived_for_modifier(), modifier_add_itemf(), modifier_apply_obdata(), modifier_apply_shape(), modifier_copyData(), modifier_couldBeCage(), modifier_dependsOnTime(), modifier_free(), modifier_isEnabled(), modifier_isPreview(), modifier_new(), modifier_nonGeometrical(), modifier_sameTopology(), modifier_supportsMapping(), modifier_unique_name(), modifiers_calcDataMasks(), modifiers_foreachIDLink(), modifiers_foreachObjectLink(), modifiers_foreachTexLink(), modifiers_getCageIndex(), multires_load_old(), multiresModifier_reshapeFromDeformMod(), object_support_modifier_type(), sculpt_get_first_deform_matrices(), sculpt_modifiers_active(), and write_modifiers().
void test_object_modifiers (Object * ob)
Definition at line 616 of file modifier.c.
References eModifierType_Multires, ListBase::first, Object::modifiers, multiresModifier_set_levels_from_disps(), ModifierData::next, OB_MESH, Object::type, and ModifierData::type.
Referenced by set_mesh().