Blender: space_buttons.c File Reference
space_buttons.c File Reference
buttons space
#include <string.h>
#include <stdio.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_space_api.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "ED_render.h"
#include "buttons_intern.h"
Functions
static SpaceLink * buttons_new (const bContext *UNUSED(C))
static void buttons_free (SpaceLink *sl)
static void buttons_init (struct wmWindowManager *UNUSED(wm), ScrArea *sa)
static SpaceLink * buttons_duplicate (SpaceLink *sl)
static void buttons_main_area_init (wmWindowManager *wm, ARegion *ar)
static void buttons_main_area_draw (const bContext *C, ARegion *ar)
static void buttons_operatortypes (void)
static void buttons_keymap (struct wmKeyConfig *keyconf)
static void buttons_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void buttons_header_area_draw (const bContext *C, ARegion *ar)
static void buttons_area_redraw (ScrArea *sa, short buttons)
static void buttons_area_listener (ScrArea *sa, wmNotifier *wmn)
void ED_spacetype_buttons (void)
Detailed Description
Definition in file space_buttons.c.
Function Documentation
static void buttons_area_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 232 of file space_buttons.c.
References wmNotifier::action, BCONTEXT_BONE, BCONTEXT_BONE_CONSTRAINT, BCONTEXT_CONSTRAINT, BCONTEXT_DATA, BCONTEXT_MODIFIER, BCONTEXT_OBJECT, BCONTEXT_PARTICLE, BCONTEXT_PHYSICS, BCONTEXT_RENDER, BCONTEXT_SCENE, BCONTEXT_TEXTURE, BCONTEXT_WORLD, buttons_area_redraw(), wmNotifier::category, wmNotifier::data, ED_area_tag_redraw(), ListBase::first, SpaceButs::mainb, NA_EDITED, NA_RENAME, NA_SELECTED, NC_ANIMATION, NC_BRUSH, NC_GEOM, NC_ID, NC_IMAGE, NC_LAMP, NC_MATERIAL, NC_NODE, NC_OBJECT, NC_SCENE, NC_SPACE, NC_TEXTURE, NC_WINDOW, NC_WORLD, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_CONSTRAINT, ND_DATA, ND_DRAW, ND_FRAME, ND_KEYFRAME, ND_KEYINGSET, ND_KEYS, ND_LAYER, ND_MODE, ND_MODIFIER, ND_NODES, ND_OB_ACTIVE, ND_PARTICLE, ND_POSE, ND_RENDER_OPTIONS, ND_RENDER_RESULT, ND_SELECT, ND_SHADING, ND_SHADING_DRAW, ND_SPACE_PROPERTIES, ND_TRANSFORM, SpaceButs::preview, and ScrArea::spacedata.
Referenced by ED_spacetype_buttons().
static void buttons_area_redraw (ScrArea * sa, short buttons) [static]
Definition at line 222 of file space_buttons.c.
References ED_area_tag_redraw(), ListBase::first, SpaceButs::mainb, and ScrArea::spacedata.
Referenced by buttons_area_listener().
static SpaceLink* buttons_duplicate (SpaceLink * sl) [static]
Definition at line 124 of file space_buttons.c.
References MEM_dupallocN(), NULL, SpaceButs::path, and SpaceButs::texuser.
Referenced by ED_spacetype_buttons().
static void buttons_free (SpaceLink * sl) [static]
Definition at line 96 of file space_buttons.c.
References BLI_freelistN(), MEM_freeN(), SpaceButs::path, SpaceButs::texuser, and ButsContextTexture::users.
Referenced by ED_spacetype_buttons().
static void buttons_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 205 of file space_buttons.c.
References buttons_header_buttons(), ED_screen_area_active(), TH_HEADER, TH_HEADERDESEL, UI_ThemeClearColor(), UI_view2d_view_ortho(), UI_view2d_view_restore(), and ARegion::v2d.
Referenced by ED_spacetype_buttons().
static void buttons_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 200 of file space_buttons.c.
References UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_HEADER, ARegion::winx, and ARegion::winy.
Referenced by ED_spacetype_buttons().
static void buttons_init (struct wmWindowManager * UNUSEDwm, ScrArea * sa) [static]
Definition at line 111 of file space_buttons.c.
References SpaceButs::align, BUT_AUTO, BUT_HORIZONTAL, BUT_VERTICAL, ListBase::first, ScrArea::spacedata, ScrArea::winx, and ScrArea::winy.
Referenced by ED_spacetype_buttons().
static void buttons_keymap (struct wmKeyConfig * keyconf) [static]
Definition at line 192 of file space_buttons.c.
References KM_PRESS, RIGHTMOUSE, SPACE_BUTS, WM_keymap_add_item(), and WM_keymap_find().
Referenced by ED_spacetype_buttons().
static void buttons_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 146 of file space_buttons.c.
References SpaceButs::align, BCONTEXT_BONE, BCONTEXT_BONE_CONSTRAINT, BCONTEXT_CONSTRAINT, BCONTEXT_DATA, BCONTEXT_MATERIAL, BCONTEXT_MODIFIER, BCONTEXT_OBJECT, BCONTEXT_PARTICLE, BCONTEXT_PHYSICS, BCONTEXT_RENDER, BCONTEXT_SCENE, BCONTEXT_TEXTURE, BCONTEXT_WORLD, BUT_VERTICAL, buttons_context_compute(), CTX_wm_space_buts(), ED_region_panels(), SpaceButs::mainb, SpaceButs::mainbo, and SpaceButs::re_align.
Referenced by ED_spacetype_buttons().
static void buttons_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 136 of file space_buttons.c.
References wmWindowManager::defaultconf, ED_region_panels_init(), ARegion::handlers, SPACE_BUTS, WM_event_add_keymap_handler(), and WM_keymap_find().
Referenced by ED_spacetype_buttons().
static SpaceLink* buttons_new (const bContext * UNUSEDC) [static]
Definition at line 62 of file space_buttons.c.
References SpaceButs::align, ARegion::alignment, BLI_addtail(), BUT_VERTICAL, MEM_callocN(), SpaceButs::regionbase, ARegion::regiontype, RGN_ALIGN_TOP, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_BUTS, and SpaceButs::spacetype.
Referenced by ED_spacetype_buttons().
static void buttons_operatortypes (void) [static]
Definition at line 185 of file space_buttons.c.
References BUTTONS_OT_directory_browse(), BUTTONS_OT_file_browse(), BUTTONS_OT_toolbox(), and WM_operatortype_append().
Referenced by ED_spacetype_buttons().
void ED_spacetype_buttons (void)
Definition at line 380 of file space_buttons.c.
References BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), buttons_area_listener(), buttons_context(), buttons_context_register(), buttons_duplicate(), buttons_free(), buttons_header_area_draw(), buttons_header_area_init(), buttons_init(), buttons_keymap(), buttons_main_area_draw(), buttons_main_area_init(), buttons_new(), buttons_operatortypes(), SpaceType::context, ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizey, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_BUTS, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().