Blender: BOP_Interface.h File Reference
BOP_Interface.h File Reference
boolop
#include "../../bsp/intern/BSP_CSGMesh.h"
Typedefs
typedef enum EnumBoolOpState BoolOpState
typedef enum EnumBoolOpType BoolOpType
Enumerations
enum EnumBoolOpState { BOP_OK, BOP_NO_SOLID, BOP_ERROR }
enum EnumBoolOpType { BOP_INTERSECTION = e_csg_intersection, BOP_UNION = e_csg_union, BOP_DIFFERENCE = e_csg_difference }
Functions
BoolOpState BOP_performBooleanOperation (BoolOpType opType, BSP_CSGMesh **outputMesh, CSG_FaceIteratorDescriptor obAFaces, CSG_VertexIteratorDescriptor obAVertices, CSG_FaceIteratorDescriptor obBFaces, CSG_VertexIteratorDescriptor obBVertices)
Detailed Description
Definition in file BOP_Interface.h.
Typedef Documentation
typedef enum EnumBoolOpState BoolOpState
typedef enum EnumBoolOpType BoolOpType
Enumeration Type Documentation
enum EnumBoolOpState
Enumerator:
BOP_OK
BOP_NO_SOLID
BOP_ERROR
Definition at line 37 of file BOP_Interface.h.
enum EnumBoolOpType
Enumerator:
BOP_INTERSECTION
BOP_UNION
BOP_DIFFERENCE
Definition at line 38 of file BOP_Interface.h.
Function Documentation
BoolOpState BOP_performBooleanOperation (BoolOpType opType, BSP_CSGMesh ** outputMesh, CSG_FaceIteratorDescriptor obAFaces, CSG_VertexIteratorDescriptor obAVertices, CSG_FaceIteratorDescriptor obBFaces, CSG_VertexIteratorDescriptor obBVertices)
Performs a generic booleam operation, the entry point for external modules.
Parameters:
opType Boolean operation type BOP_INTERSECTION, BOP_UNION, BOP_DIFFERENCE
outputMesh Output mesh, the final result (the object C)
obAFaces Object A faces list
obAVertices Object A vertices list
obBFaces Object B faces list
obBVertices Object B vertices list
interpFunc Interpolating function
Returns:
operation state: BOP_OK, BOP_NO_SOLID, BOP_ERROR
Definition at line 714 of file BOP_CarveInterface.cpp.
References BOP_addMesh(), BOP_DIFFERENCE, BOP_ERROR, BOP_exportMesh(), BOP_INTERSECTION, BOP_intersectionBoolOp(), BOP_NO_SOLID, BOP_OK, BOP_UNION, Carve_addMesh(), Carve_exportMesh(), Carve_unionIntersections(), i, BOP_Mesh::isClosedMesh(), left(), MAX, max, MIN, min, and NULL.
Referenced by CSG_PerformBooleanOperation().