Blender: bmesh_private.h File Reference
bmesh_private.h File Reference
BMesh
#include "bmesh_structure.h"
#include "bmesh_operators_private.h"
Defines
#define BM_CHECK_ELEMENT(el)
#define BM_DISK_EDGE_LINK_GET(e, v)
#define _FLAG_JF 1
#define _FLAG_MF 2
#define BM_ELEM_API_FLAG_ENABLE(element, f) ((element)->oflags[0].pflag |= (f))
#define BM_ELEM_API_FLAG_DISABLE(element, f) ((element)->oflags[0].pflag &= ~(f))
#define BM_ELEM_API_FLAG_TEST(element, f) ((element)->oflags[0].pflag & (f))
Functions
int bmesh_elem_check (void *element, const char htype)
int bmesh_radial_length (BMLoop *l)
int bmesh_disk_count (BMVert *v)
void calc_poly_plane (float(*verts)[3], const int nverts)
void poly_rotate_plane (const float normal[3], float(*verts)[3], const int nverts)
POLY ROTATE PLANE.
Detailed Description
Private function prototypes for bmesh public API. This file is a grab-bag of functions from various parts of the bmesh internals.
Definition in file bmesh_private.h.
Define Documentation
#define _FLAG_JF 1
Definition at line 61 of file bmesh_private.h.
Referenced by BM_faces_join().
#define _FLAG_MF 2
Definition at line 62 of file bmesh_private.h.
Referenced by BM_face_create_ngon().
#define BM_CHECK_ELEMENT (el)
Value:
if (bmesh_elem_check(el, ((BMHeader *)el)->htype)) {                      \
        printf("check_element failure, with code %i on line %i in file\n"     \
        "    \"%s\"\n\n",                                                     \
        bmesh_elem_check(el, ((BMHeader *)el)->htype),                    \
        __LINE__, __FILE__);                                                  \
    }
Definition at line 42 of file bmesh_private.h.
Referenced by BM_edge_create(), BM_edge_splice(), BM_face_create(), BM_face_kill(), BM_faces_join(), bm_loop_reverse_loop(), BM_mesh_bm_to_me(), bm_subdivide_multicut(), BM_vert_create(), BM_vert_splice(), bmesh_edge_separate(), bmesh_jekv(), bmesh_jfke(), bmesh_semv(), bmesh_sfme(), bmesh_vert_separate(), and bmo_esubd_exec().
#define BM_DISK_EDGE_LINK_GET (e, v)
Value:
(\
    ((v) == ((BMEdge *)(e))->v1) ?                                            \
        &((e)->v1_disk_link) :                                                \
        &((e)->v2_disk_link)                                                  \
    )
Definition at line 50 of file bmesh_private.h.
Referenced by bmesh_disk_edge_append(), and bmesh_disk_edge_remove().
#define BM_ELEM_API_FLAG_DISABLE (element, f) ((element)->oflags[0].pflag &= ~(f))
Definition at line 65 of file bmesh_private.h.
Referenced by bm_elements_systag_disable(), BM_face_create_ngon(), and BM_faces_join().
#define BM_ELEM_API_FLAG_ENABLE (element, f) ((element)->oflags[0].pflag |= (f))
Definition at line 64 of file bmesh_private.h.
Referenced by bm_elements_systag_enable(), BM_face_create_ngon(), and BM_faces_join().
#define BM_ELEM_API_FLAG_TEST (element, f) ((element)->oflags[0].pflag & (f))
Definition at line 66 of file bmesh_private.h.
Referenced by BM_face_create_ngon(), BM_faces_join(), count_flagged_disk(), count_flagged_radial(), and disk_is_flagged().
Function Documentation
int bmesh_disk_count (BMVert * v)
Definition at line 245 of file bmesh_structure.c.
References bmesh_disk_edge_next(), and BMVert::e.
Referenced by BM_vert_collapse_faces(), BM_vert_edge_count(), bmesh_disk_validate(), bmesh_elem_check(), bmesh_jekv(), bmesh_semv(), bmesh_urmv_loop(), and BMO_vert_edge_flags_count().
int bmesh_elem_check (void * element, const char htype)
Check the element is valid.
BMESH_TODO, when this raises an error the output is incredible confusing. need to have some nice way to print/debug what the hecks going on.
Definition at line 342 of file bmesh_core.c.
References BM_EDGE, BM_FACE, BM_FACE_FIRST_LOOP, BM_LOOP, BM_NGON_MAX, BM_VERT, BM_vert_in_edge(), BMESH_ASSERT, bmesh_disk_count(), bmesh_radial_length(), bmesh_radial_validate(), BMLoop::e, BMVert::e, err, BMLoop::f, BMEdge::head, BMVert::head, BMFace::head, BMLoop::head, BMHeader::htype, i, BMEdge::l, BMFace::l_first, len(), BMFace::len, BMLoop::next, BMDiskLink::next, NULL, BMDiskLink::prev, BMLoop::radial_next, BMLoop::radial_prev, BMLoop::v, BMEdge::v1_disk_link, and BMEdge::v2_disk_link.
int bmesh_radial_length (BMLoop * l)
Definition at line 453 of file bmesh_structure.c.
References BM_LOOP_RADIAL_MAX, BMESH_ASSERT, i, BMLoop::radial_next, and UNLIKELY.
Referenced by BM_disk_dissolve(), BM_edge_splice(), BM_vert_is_manifold(), bmesh_edge_separate(), bmesh_elem_check(), bmesh_jekv(), bmesh_radial_face_find(), bmesh_radial_validate(), bmesh_semv(), and disk_is_flagged().
void calc_poly_plane (float(*) verts[3], const int nverts)
COMPUTE POLY PLANE
Projects a set polygon's vertices to a plane defined by the average of its edges cross products
Definition at line 248 of file bmesh_polygon.c.
References add_v3_v3(), dot_v3v3(), i, madd_v3_v3fl(), norm(), normal_tri_v3(), normalize_v3(), UNLIKELY, and zero_v3().
void poly_rotate_plane (const float normal[3], float(*) verts[3], const int nverts)
POLY ROTATE PLANE.
Rotates a polygon so that it's normal is pointing towards the mesh Z axis
Definition at line 311 of file bmesh_polygon.c.
References angle(), axis_angle_to_quat(), cross_v3_v3v3(), dot_v3v3(), i, mul_m3_v3(), quat_to_mat3(), and saacos().
Referenced by BM_face_legal_splits(), BM_face_triangulate(), and quad_co().