Blender: rna_pose.c File Reference
rna_pose.c File Reference
RNA
#include <stdlib.h>
#include <string.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_action_types.h"
#include "DNA_armature_types.h"
#include "DNA_constraint_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "WM_types.h"
Functions
static void rna_def_bone_group (BlenderRNA *brna)
static void rna_def_pose_channel_constraints (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_pose_channel (BlenderRNA *brna)
static void rna_def_pose_itasc (BlenderRNA *brna)
static void rna_def_pose_ikparam (BlenderRNA *brna)
static void rna_def_bone_groups (BlenderRNA *brna, PropertyRNA *cprop)
static void rna_def_pose (BlenderRNA *brna)
void RNA_def_pose (BlenderRNA *brna)
Variables
EnumPropertyItem posebone_rotmode_items []
static EnumPropertyItem prop_iksolver_items []
static EnumPropertyItem prop_solver_items []
Detailed Description
Definition in file rna_pose.c.
Function Documentation
static void rna_def_bone_group (BlenderRNA * brna) [static]
Definition at line 624 of file rna_pose.c.
References NC_OBJECT, ND_POSE, NULL, PROP_ENUM, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_pose().
static void rna_def_bone_groups (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 1242 of file rna_pose.c.
References NC_OBJECT, ND_POSE, NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_pose().
void RNA_def_pose (BlenderRNA * brna)
Definition at line 1317 of file rna_pose.c.
References rna_def_bone_group(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_ikparam(), and rna_def_pose_itasc().
static void rna_def_pose (BlenderRNA * brna) [static]
Definition at line 1271 of file rna_pose.c.
References NC_OBJECT, ND_POSE, NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, rna_def_animviz_common(), rna_def_bone_groups(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_pose().
static void rna_def_pose_channel (BlenderRNA * brna) [static]
Definition at line 737 of file rna_pose.c.
References BONE_IK_LINCTL, BONE_IK_NO_XDOF, BONE_IK_NO_YDOF, BONE_IK_NO_ZDOF, BONE_IK_ROTCTL, BONE_IK_XLIMIT, BONE_IK_YLIMIT, BONE_IK_ZLIMIT, FLT_MAX, M_PI, NC_OBJECT, ND_POSE, NULL, OB_LOCK_LOCX, OB_LOCK_ROT4D, OB_LOCK_ROTW, OB_LOCK_ROTX, OB_LOCK_SCALEX, PROP_ANGLE, PROP_ANIMATABLE, PROP_AXISANGLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_EULER, PROP_FLOAT, PROP_INT, PROP_MATRIX, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_QUATERNION, PROP_STRING, PROP_TRANSLATION, PROP_XYZ, RNA_api_pose_channel(), rna_def_motionpath_common(), rna_def_pose_channel_constraints(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_editable_array_func(), RNA_def_property_editable_func(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_array_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_multi_array(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_idprops_func(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by RNA_def_pose().
static void rna_def_pose_channel_constraints (BlenderRNA * brna, PropertyRNA * cprop) [static]
Definition at line 697 of file rna_pose.c.
References constraint_type_items, FUNC_USE_REPORTS, FUNC_USE_SELF_ID, NULL, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_REQUIRED, RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by rna_def_pose_channel().
static void rna_def_pose_ikparam (BlenderRNA * brna) [static]
Definition at line 1223 of file rna_pose.c.
References NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_pose().
static void rna_def_pose_itasc (BlenderRNA * brna) [static]
Definition at line 1109 of file rna_pose.c.
References ITASC_AUTO_STEP, ITASC_INITIAL_REITERATION, ITASC_REITERATION, ITASC_SIMULATION, NC_OBJECT, ND_POSE, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_pose().
Variable Documentation
EnumPropertyItem posebone_rotmode_items[]
Initial value:
 {
    {ROT_MODE_QUAT, "QUATERNION", 0, "Quaternion (WXYZ)", "No Gimbal Lock (default)"},
    {ROT_MODE_XYZ, "XYZ", 0, "XYZ Euler", "XYZ Rotation Order (prone to Gimbal Lock)"},
    {ROT_MODE_XZY, "XZY", 0, "XZY Euler", "XZY Rotation Order (prone to Gimbal Lock)"},
    {ROT_MODE_YXZ, "YXZ", 0, "YXZ Euler", "YXZ Rotation Order (prone to Gimbal Lock)"},
    {ROT_MODE_YZX, "YZX", 0, "YZX Euler", "YZX Rotation Order (prone to Gimbal Lock)"},
    {ROT_MODE_ZXY, "ZXY", 0, "ZXY Euler", "ZXY Rotation Order (prone to Gimbal Lock)"},
    {ROT_MODE_ZYX, "ZYX", 0, "ZYX Euler", "ZYX Rotation Order (prone to Gimbal Lock)"},
    {ROT_MODE_AXISANGLE, "AXIS_ANGLE", 0, "Axis Angle",
                         "Axis Angle (W+XYZ), defines a rotation around some axis defined by 3D-Vector"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 50 of file rna_pose.c.
Referenced by POSE_OT_rotation_mode_set().
EnumPropertyItem prop_iksolver_items[] [static]
Initial value:
 {
    {IKSOLVER_LEGACY, "LEGACY", 0, "Legacy", "Original IK solver"},
    {IKSOLVER_ITASC, "ITASC", 0, "iTaSC", "Multi constraint, stateful IK solver"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 686 of file rna_pose.c.
EnumPropertyItem prop_solver_items[] [static]
Initial value:
 {
    {ITASC_SOLVER_SDLS, "SDLS", 0, "SDLS", "Selective Damped Least Square"},
    {ITASC_SOLVER_DLS, "DLS", 0, "DLS", "Damped Least Square with Numerical Filtering"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 691 of file rna_pose.c.