Blender: uvedit_parametrizer.h File Reference
uvedit_parametrizer.h File Reference
#include "BLO_sys_types.h"
Typedefs
typedef void ParamHandle
typedef intptr_t ParamKey
typedef enum ParamBool ParamBool
Enumerations
enum ParamBool { PARAM_TRUE = 1, PARAM_FALSE = 0 }
Functions
ParamHandle * param_construct_begin (void)
void param_aspect_ratio (ParamHandle *handle, float aspx, float aspy)
void param_face_add (ParamHandle *handle, ParamKey key, int nverts, ParamKey *vkeys, float **co, float **uv, ParamBool *pin, ParamBool *select)
void param_edge_set_seam (ParamHandle *handle, ParamKey *vkeys)
void param_construct_end (ParamHandle *handle, ParamBool fill, ParamBool impl)
void param_delete (ParamHandle *chart)
void param_lscm_begin (ParamHandle *handle, ParamBool live, ParamBool abf)
void param_lscm_solve (ParamHandle *handle)
void param_lscm_end (ParamHandle *handle)
void param_stretch_begin (ParamHandle *handle)
void param_stretch_blend (ParamHandle *handle, float blend)
void param_stretch_iter (ParamHandle *handle)
void param_stretch_end (ParamHandle *handle)
void param_smooth_area (ParamHandle *handle)
void param_pack (ParamHandle *handle, float margin)
void param_average (ParamHandle *handle)
void param_scale (ParamHandle *handle, float x, float y)
void param_flush (ParamHandle *handle)
void param_flush_restore (ParamHandle *handle)
Detailed Description
Definition in file uvedit_parametrizer.h.
Typedef Documentation
typedef enum ParamBool ParamBool
typedef void ParamHandle
Definition at line 14 of file uvedit_parametrizer.h.
typedef intptr_t ParamKey
Definition at line 15 of file uvedit_parametrizer.h.
Enumeration Type Documentation
enum ParamBool
Enumerator:
PARAM_TRUE
PARAM_FALSE
Definition at line 16 of file uvedit_parametrizer.h.
Function Documentation
void param_aspect_ratio (ParamHandle * handle, float aspx, float aspy)
Definition at line 4080 of file uvedit_parametrizer.c.
References PHandle::aspx, and PHandle::aspy.
Referenced by construct_param_handle(), and construct_param_handle_subsurfed().
void param_average (ParamHandle * handle)
Definition at line 4427 of file uvedit_parametrizer.c.
References PHandle::charts, fabsf, PChart::faces, i, PHandle::ncharts, PFace::nextlink, p_chart_uv_bbox(), p_chart_uv_scale(), p_chart_uv_translate(), p_face_area(), p_face_uv_area_signed(), PChart::PChartUnion::pack, sqrt(), and PChart::u.
Referenced by average_islands_scale_exec().
ParamHandle* param_construct_begin (void)
Definition at line 4064 of file uvedit_parametrizer.c.
References PHandle::arena, PHandle::aspx, PHandle::aspy, BLI_memarena_new(), PHandle::construction_chart, PChart::edges, PChart::faces, PHandle::hash_edges, PHandle::hash_faces, PHandle::hash_verts, MEM_callocN(), p_chart_new(), PHANDLE_STATE_ALLOCATED, phash_new(), PHandle::state, and PChart::verts.
Referenced by construct_param_handle(), and construct_param_handle_subsurfed().
void param_construct_end (ParamHandle * handle, ParamBool fill, ParamBool impl)
Definition at line 4151 of file uvedit_parametrizer.c.
References PHandle::charts, PHandle::construction_chart, PHandle::hash_edges, PHandle::hash_faces, PHandle::hash_verts, i, PHandle::ncharts, PVert::nextlink, NULL, p_chart_boundaries(), p_chart_delete(), p_chart_fill_boundaries(), p_connect_pairs(), p_split_charts(), p_vert_load_pin_select_uvs(), param_assert, PHANDLE_STATE_ALLOCATED, PHANDLE_STATE_CONSTRUCTED, phash_delete(), PHandle::state, and PChart::verts.
Referenced by construct_param_handle(), and construct_param_handle_subsurfed().
void param_delete (ParamHandle * chart)
Definition at line 4088 of file uvedit_parametrizer.c.
References PHandle::arena, BLI_memarena_free(), PHandle::charts, PHandle::construction_chart, PHandle::hash_edges, PHandle::hash_faces, PHandle::hash_verts, i, MEM_freeN(), PHandle::ncharts, p_chart_delete(), param_assert, PHANDLE_STATE_ALLOCATED, PHANDLE_STATE_CONSTRUCTED, phash_delete(), and PHandle::state.
Referenced by average_islands_scale_exec(), ED_unwrap_lscm(), ED_uvedit_live_unwrap_end(), minimize_stretch_exit(), and pack_islands_exec().
void param_edge_set_seam (ParamHandle * handle, ParamKey * vkeys)
Definition at line 4139 of file uvedit_parametrizer.c.
References PEdge::flag, p_edge_lookup(), param_assert, PEDGE_SEAM, PHANDLE_STATE_ALLOCATED, and PHandle::state.
Referenced by construct_param_handle(), and construct_param_handle_subsurfed().
void param_face_add (ParamHandle * handle, ParamKey key, int nverts, ParamKey * vkeys, float ** co, float ** uv, ParamBool * pin, ParamBool * select)
Definition at line 4114 of file uvedit_parametrizer.c.
References PHandle::hash_faces, NULL, p_face_add_construct(), p_face_exists(), p_quad_split_direction(), param_assert, PHANDLE_STATE_ALLOCATED, phash_lookup(), and PHandle::state.
Referenced by construct_param_handle(), and construct_param_handle_subsurfed().
void param_flush (ParamHandle * handle)
Definition at line 4496 of file uvedit_parametrizer.c.
References PHandle::blend, PHandle::charts, i, PChart::PChartUnion::lscm, PHandle::ncharts, p_flush_uvs(), p_flush_uvs_blend(), PHANDLE_STATE_LSCM, PHandle::state, and PChart::u.
Referenced by average_islands_scale_exec(), ED_unwrap_lscm(), ED_uvedit_live_unwrap_re_solve(), minimize_stretch_exit(), minimize_stretch_iteration(), and pack_islands_exec().
void param_flush_restore (ParamHandle * handle)
Definition at line 4515 of file uvedit_parametrizer.c.
References PHandle::charts, PChart::faces, i, PHandle::ncharts, PFace::nextlink, and p_face_restore_uvs().
Referenced by ED_uvedit_live_unwrap_end(), and minimize_stretch_exit().
void param_lscm_begin (ParamHandle * handle, ParamBool live, ParamBool abf)
Definition at line 4197 of file uvedit_parametrizer.c.
References PHandle::charts, PChart::faces, i, PHandle::ncharts, PFace::nextlink, p_chart_lscm_begin(), p_face_backup_uvs(), param_assert, PHANDLE_STATE_CONSTRUCTED, PHANDLE_STATE_LSCM, and PHandle::state.
Referenced by ED_unwrap_lscm(), and ED_uvedit_live_unwrap_begin().
void param_lscm_end (ParamHandle * handle)
Definition at line 4237 of file uvedit_parametrizer.c.
References PHandle::charts, i, PHandle::ncharts, p_chart_lscm_end(), param_assert, PHANDLE_STATE_CONSTRUCTED, PHANDLE_STATE_LSCM, and PHandle::state.
Referenced by ED_unwrap_lscm(), and ED_uvedit_live_unwrap_end().
void param_lscm_solve (ParamHandle * handle)
Definition at line 4213 of file uvedit_parametrizer.c.
References PHandle::charts, PChart::flag, i, PChart::PChartUnion::lscm, PHandle::ncharts, p_chart_lscm_end(), p_chart_lscm_solve(), p_chart_rotate_minimum_area(), param_assert, PCHART_NOPACK, PHANDLE_STATE_LSCM, PHandle::state, and PChart::u.
Referenced by ED_unwrap_lscm(), and ED_uvedit_live_unwrap_re_solve().
void param_pack (ParamHandle * handle, float margin)
Definition at line 4334 of file uvedit_parametrizer.c.
References PHandle::aspx, PHandle::aspy, boxPack2D(), PHandle::charts, PChart::flag, boxPack::h, i, boxPack::index, MEM_freeN(), MEM_mallocN(), PHandle::ncharts, p_chart_uv_bbox(), p_chart_uv_scale(), p_chart_uv_translate(), PChart::PChartUnion::pack, param_scale(), PCHART_NOPACK, sqrt(), PChart::u, boxPack::w, boxPack::x, and boxPack::y.
Referenced by ED_unwrap_lscm(), and pack_islands_exec().
void param_scale (ParamHandle * handle, float x, float y)
Definition at line 4484 of file uvedit_parametrizer.c.
References PHandle::charts, i, PHandle::ncharts, and p_chart_uv_scale_xy().
Referenced by param_pack().
void param_smooth_area (ParamHandle * handle)
Definition at line 4316 of file uvedit_parametrizer.c.
References PHandle::charts, PVert::flag, i, PHandle::ncharts, PVert::nextlink, p_smooth(), param_assert, PHANDLE_STATE_CONSTRUCTED, PVERT_PIN, PHandle::state, and PChart::verts.
void param_stretch_begin (ParamHandle * handle)
Definition at line 4254 of file uvedit_parametrizer.c.
References PFace::PFaceUnion::area3d, PHandle::blend, PHandle::charts, PChart::faces, PVert::flag, i, PHandle::ncharts, PFace::nextlink, PVert::nextlink, p_face_area(), p_face_backup_uvs(), p_stretch_pin_boundary(), param_assert, PHANDLE_STATE_CONSTRUCTED, PHANDLE_STATE_STRETCH, PVERT_PIN, PHandle::rng, rng_new(), PHandle::state, PFace::u, and PChart::verts.
Referenced by minimize_stretch_init().
void param_stretch_blend (ParamHandle * handle, float blend)
Definition at line 4283 of file uvedit_parametrizer.c.
References blend(), PHandle::blend, param_assert, PHANDLE_STATE_STRETCH, and PHandle::state.
Referenced by minimize_stretch_init(), and minimize_stretch_iteration().
void param_stretch_end (ParamHandle * handle)
Definition at line 4305 of file uvedit_parametrizer.c.
References NULL, param_assert, PHANDLE_STATE_CONSTRUCTED, PHANDLE_STATE_STRETCH, PHandle::rng, rng_free(), and PHandle::state.
Referenced by minimize_stretch_exit().
void param_stretch_iter (ParamHandle * handle)
Definition at line 4291 of file uvedit_parametrizer.c.
References PHandle::charts, i, PHandle::ncharts, p_chart_stretch_minimize(), param_assert, PHANDLE_STATE_STRETCH, PHandle::rng, and PHandle::state.
Referenced by minimize_stretch_iteration().