Blender: BL_BlenderInputDevice Class Reference
BL_BlenderInputDevice Class Reference
#include <KX_BlenderInputDevice.h>
Public Member Functions
BL_BlenderInputDevice ()
virtual ~BL_BlenderInputDevice ()
KX_EnumInputs ToNative (unsigned short incode)
virtual bool IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode)=0
virtual bool ConvertBlenderEvent (unsigned short incode, short val)=0
Detailed Description
Base Class for Blender specific inputdevices. Blender specific inputdevices are used when the gameengine is running in embedded mode instead of standalone mode.
Definition at line 53 of file KX_BlenderInputDevice.h.
Constructor & Destructor Documentation
BL_BlenderInputDevice::BL_BlenderInputDevice () [inline]
Definition at line 56 of file KX_BlenderInputDevice.h.
virtual BL_BlenderInputDevice::~BL_BlenderInputDevice () [inline, virtual]
Definition at line 60 of file KX_BlenderInputDevice.h.
Member Function Documentation
virtual bool BL_BlenderInputDevice::ConvertBlenderEvent (unsigned short incode, short val) [pure virtual]
Implemented in KX_BlenderKeyboardDevice, and KX_BlenderMouseDevice.
virtual bool BL_BlenderInputDevice::IsPressed (SCA_IInputDevice::KX_EnumInputs inputcode) [pure virtual]
Implements SCA_IInputDevice.
Implemented in KX_BlenderKeyboardDevice, and KX_BlenderMouseDevice.
KX_EnumInputs BL_BlenderInputDevice::ToNative (unsigned short incode) [inline]
Definition at line 65 of file KX_BlenderInputDevice.h.
References ConvertKeyCode().
Referenced by KX_BlenderMouseDevice::ConvertBlenderEvent(), and KX_BlenderKeyboardDevice::ConvertBlenderEvent().
The documentation for this class was generated from the following file:
KX_BlenderInputDevice.h