Blender: BME_bevel.c File Reference
BME_bevel.c File Reference
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_listBase.h"
#include "DNA_meshdata_types.h"
#include "DNA_mesh_types.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_ghash.h"
#include "BLI_memarena.h"
#include "BKE_utildefines.h"
#include "BKE_tessmesh.h"
#include "BKE_bmesh.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
Defines
#define BMESH_263_VERT_BEVEL_WORKAROUND
Functions
BME_TransData_Head * BME_init_transdata (int bufsize)
void BME_free_transdata (BME_TransData_Head *td)
BME_TransData * BME_assign_transdata (BME_TransData_Head *td, BMesh *bm, BMVert *v, float *co, float *org, float *vec, float *loc, float factor, float weight, float maxfactor, float *max)
BME_TransData * BME_get_transdata (BME_TransData_Head *td, BMVert *v)
float * BME_new_transdata_float (BME_TransData_Head *td)
static void BME_Bevel_Dissolve_Disk (BMesh *bm, BMVert *v)
static int BME_bevel_is_split_vert (BMesh *bm, BMLoop *l)
static int BME_bevel_get_vec (float *vec, BMVert *v1, BMVert *v2, BME_TransData_Head *td)
static float BME_bevel_project_vec (float *vec1, float *vec2, float *up_vec, int is_forward, BME_TransData_Head *UNUSED(td))
static BMVert * BME_bevel_split_edge (BMesh *bm, BMVert *v, BMVert *v1, BMLoop *l, float *up_vec, float value, BME_TransData_Head *td)
static BMLoop * BME_bevel_edge (BMesh *bm, BMLoop *l, float value, int UNUSED(options), float *up_vec, BME_TransData_Head *td)
static BMLoop * BME_bevel_vert (BMesh *bm, BMLoop *l, float value, int UNUSED(options), float *up_vec, BME_TransData_Head *td)
static BMFace * BME_bevel_poly (BMesh *bm, BMFace *f, float value, int options, BME_TransData_Head *td)
static float BME_bevel_get_angle (BMEdge *e, BMVert *v)
static float BME_bevel_get_angle_vert (BMVert *v)
static void BME_bevel_add_vweight (BME_TransData_Head *td, BMesh *bm, BMVert *v, float weight, float factor, int options)
static void bevel_init_verts (BMesh *bm, int options, float angle, BME_TransData_Head *td)
static void bevel_init_edges (BMesh *bm, int options, float angle, BME_TransData_Head *td)
static BMesh * BME_bevel_initialize (BMesh *bm, int options, int UNUSED(defgrp_index), float angle, BME_TransData_Head *td)
static BMesh * BME_bevel_mesh (BMesh *bm, float value, int UNUSED(res), int options, int UNUSED(defgrp_index), BME_TransData_Head *td)
BMesh * BME_bevel (BMEditMesh *em, float value, int res, int options, int defgrp_index, float angle, BME_TransData_Head **rtd, int do_tessface)
Define Documentation
#define BMESH_263_VERT_BEVEL_WORKAROUND
Definition at line 66 of file BME_bevel.c.
Function Documentation
static void bevel_init_edges (BMesh * bm, int options, float angle, BME_TransData_Head * td) [static]
Definition at line 891 of file BME_bevel.c.
References BM_EDGES_OF_MESH, BM_elem_flag_test, BM_elem_float_data_get(), BM_ELEM_SELECT, BM_face_share_edge_count(), BM_ITER_MESH, BME_bevel_add_vweight(), BME_BEVEL_ANGLE, BME_BEVEL_BEVEL, BME_bevel_get_angle(), BME_BEVEL_NONMAN, BME_BEVEL_SELECT, BME_BEVEL_WEIGHT, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, CD_BWEIGHT, cosf, BMesh::edata, BMLoop::f, BMEdge::l, BMLoop::radial_next, BMEdge::v1, and BMEdge::v2.
Referenced by BME_bevel_initialize().
static void bevel_init_verts (BMesh * bm, int options, float angle, BME_TransData_Head * td) [static]
Definition at line 853 of file BME_bevel.c.
References BM_elem_flag_test, BM_elem_float_data_get(), BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, BME_assign_transdata(), BME_BEVEL_ANGLE, BME_BEVEL_BEVEL, BME_bevel_get_angle_vert(), BME_BEVEL_NONMAN, BME_BEVEL_SELECT, BME_BEVEL_WEIGHT, BMO_elem_flag_enable, BMO_elem_flag_test, CD_BWEIGHT, BMVert::co, NULL, and BMesh::vdata.
Referenced by BME_bevel_initialize().
BME_TransData* BME_assign_transdata (BME_TransData_Head * td, BMesh * bm, BMVert * v, float * co, float * org, float * vec, float * loc, float factor, float weight, float maxfactor, float * max)
Definition at line 89 of file BME_bevel.c.
References BLI_ghash_insert(), BLI_ghash_lookup(), BLI_memarena_alloc(), BME_TransData::bm, BME_TransData::co, BMVert::co, copy_v3_v3(), BME_TransData::factor, BME_TransData_Head::gh, BME_TransData_Head::len, BME_TransData::loc, BME_TransData_Head::ma, max, BME_TransData::max, BME_TransData::maxfactor, normalize_v3(), NULL, BME_TransData::org, BME_TransData::v, BME_TransData::vec, and BME_TransData::weight.
Referenced by bevel_init_verts(), BME_bevel_add_vweight(), BME_bevel_initialize(), and BME_bevel_split_edge().
BMesh* BME_bevel (BMEditMesh * em, float value, int res, int options, int defgrp_index, float angle, BME_TransData_Head ** rtd, int do_tessface) [read]
Definition at line 1095 of file BME_bevel.c.
References BLI_MEMARENA_STD_BUFSIZE, BMEditMesh::bm, BM_ITER_MESH, BM_VERTS_OF_MESH, BME_bevel_initialize(), BME_bevel_mesh(), BME_free_transdata(), BME_get_transdata(), BME_init_transdata(), BMEdit_RecalcTessellation(), bmesh_edit_begin(), bmesh_edit_end(), BMO_pop(), BMO_push(), BMVert::co, BME_TransData::factor, i, madd_v3_v3v3fl(), BME_TransData::max, NULL, BME_TransData::org, and BME_TransData::vec.
Referenced by applyModifier().
static void BME_bevel_add_vweight (BME_TransData_Head * td, BMesh * bm, BMVert * v, float weight, float factor, int options) [static]
Definition at line 816 of file BME_bevel.c.
References BME_assign_transdata(), BME_BEVEL_BEVEL, BME_BEVEL_EMAX, BME_BEVEL_EMIN, BME_BEVEL_NONMAN, BME_get_transdata(), BMO_elem_flag_enable, BMO_elem_flag_test, BMVert::co, BME_TransData::factor, NULL, and BME_TransData::weight.
Referenced by bevel_init_edges().
static void BME_Bevel_Dissolve_Disk (BMesh * bm, BMVert * v) [static]
Definition at line 151 of file BME_bevel.c.
References BM_edge_is_manifold(), BM_vert_collapse_edge(), bmesh_disk_edge_next(), bmesh_jfke(), BMVert::e, BMLoop::f, BMEdge::l, NULL, BMLoop::radial_next, and TRUE.
Referenced by BME_bevel_mesh().
static BMLoop* BME_bevel_edge (BMesh * bm, BMLoop * l, float value, int UNUSEDoptions, float * up_vec, BME_TransData_Head * td) [static]
Definition at line 499 of file BME_bevel.c.
References BLI_assert, BM_face_split(), BM_vert_collapse_edge(), BME_BEVEL_BEVEL, BME_BEVEL_NONMAN, BME_BEVEL_ORIG, BME_bevel_split_edge(), bmesh_jfke(), BMO_elem_flag_enable, BMO_elem_flag_test, BMLoop::e, BMLoop::f, FALSE, BMEdge::l, BMLoop::next, NULL, BMLoop::prev, BMLoop::radial_next, TRUE, and BMLoop::v.
Referenced by BME_bevel_poly().
static float BME_bevel_get_angle (BMEdge * e, BMVert * v) [static]
Definition at line 749 of file BME_bevel.c.
References BMVert::co, cross_v3_v3v3(), dot_v3v3(), BMEdge::l, BMLoop::next, normalize_v3(), BMLoop::prev, BMLoop::radial_next, sub_v3_v3v3(), and BMLoop::v.
Referenced by bevel_init_edges().
static float BME_bevel_get_angle_vert (BMVert * v) [static]
Definition at line 788 of file BME_bevel.c.
References angle(), angle_normalized_v3v3(), BM_ITER_ELEM, BM_loop_calc_face_angle(), BM_loop_calc_face_normal(), BM_LOOPS_OF_VERT, BMLoop::f, M_PI, madd_v3_v3fl(), and normalize_v3().
Referenced by bevel_init_verts().
static int BME_bevel_get_vec (float * vec, BMVert * v1, BMVert * v2, BME_TransData_Head * td) [static]
Definition at line 198 of file BME_bevel.c.
References BME_get_transdata(), BMVert::co, compare_v3v3(), len_v3(), BME_TransData::org, sub_v3_v3v3(), and zero_v3().
Referenced by BME_bevel_poly(), and BME_bevel_split_edge().
static BMesh* BME_bevel_initialize (BMesh * bm, int options, int UNUSEDdefgrp_index, float angle, BME_TransData_Head * td) [static]
Definition at line 948 of file BME_bevel.c.
References bevel_init_edges(), bevel_init_verts(), BM_edge_is_boundary(), BM_edge_is_manifold(), BM_EDGES_OF_MESH, BM_FACES_OF_MESH, BM_ITER_MESH, BM_vert_edge_count(), BM_vert_is_manifold(), BM_vert_is_wire(), BM_VERTS_OF_MESH, BME_assign_transdata(), BME_BEVEL_NONMAN, BME_BEVEL_ORIG, BME_BEVEL_VERT, BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_elem_flag_test, BMVert::co, BMVert::e, len(), NULL, BMEdge::v1, and BMEdge::v2.
Referenced by BME_bevel().
static int BME_bevel_is_split_vert (BMesh * bm, BMLoop * l) [static]
Definition at line 179 of file BME_bevel.c.
References BME_BEVEL_ORIG, BMO_elem_flag_test, BMLoop::e, BMLoop::prev, and BMLoop::v.
Referenced by BME_bevel_split_edge().
static BMesh* BME_bevel_mesh (BMesh * bm, float value, int UNUSEDres, int options, int UNUSEDdefgrp_index, BME_TransData_Head * td) [static]
BME_bevel_mesh
Mesh beveling tool:
Bevels an entire mesh. It currently uses the flags of its vertices and edges to track topological changes. The parameter "value" is the distance to inset (should be negative). The parameter "options" is not currently used.
Returns - A BMesh pointer to the BM passed as a parameter.
Definition at line 1040 of file BME_bevel.c.
References BM_EDGES_OF_MESH, BM_face_split(), BM_faces_join_pair(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERTS_OF_MESH, BME_BEVEL_BEVEL, BME_Bevel_Dissolve_Disk(), BME_BEVEL_ORIG, BME_bevel_poly(), bmesh_disk_edge_next(), BMO_elem_flag_test, BMLoop::e, BMVert::e, BMLoop::f, BMEdge::l, BMFace::len, BMLoop::next, BMLoop::prev, BMLoop::radial_next, TRUE, and BMLoop::v.
Referenced by BME_bevel().
static BMFace* BME_bevel_poly (BMesh * bm, BMFace * f, float value, int options, BME_TransData_Head * td) [static]
Definition at line 654 of file BME_bevel.c.
References add_newell_cross_v3_v3v3(), add_v3_v3(), BM_FACE_FIRST_LOOP, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BME_BEVEL_BEVEL, BME_bevel_edge(), BME_bevel_get_vec(), BME_BEVEL_ORIG, BME_bevel_vert(), BME_get_transdata(), BMO_elem_flag_test, BMVert::co, copy_v3_v3(), cross_v3_v3v3(), dot_v3v3(), BMLoop::e, BMLoop::f, BME_TransData::factor, i, len(), BMFace::len, len_v3(), BME_TransData::loc, max, BME_TransData::max, mul_v3_fl(), BMLoop::next, next, normalize_v3(), NULL, BMLoop::prev, project_v3_v3v3(), BMLoop::v, BME_TransData::vec, and zero_v3().
Referenced by BME_bevel_mesh().
static float BME_bevel_project_vec (float * vec1, float * vec2, float * up_vec, int is_forward, BME_TransData_Head * UNUSEDtd) [static]
Definition at line 237 of file BME_bevel.c.
References cross_v3_v3v3(), dot_v3v3(), fabsf, and normalize_v3().
Referenced by BME_bevel_split_edge().
static BMVert* BME_bevel_split_edge (BMesh * bm, BMVert * v, BMVert * v1, BMLoop * l, float * up_vec, float value, BME_TransData_Head * td) [static]
Definition at line 267 of file BME_bevel.c.
References BM_edge_other_vert(), BM_edge_split(), BME_assign_transdata(), BME_BEVEL_BEVEL, BME_bevel_get_vec(), BME_bevel_is_split_vert(), BME_BEVEL_ORIG, BME_bevel_project_vec(), BME_get_transdata(), BME_new_transdata_float(), bmesh_disk_edge_next(), BMO_elem_flag_enable, BMO_elem_flag_test, BMVert::co, cross_v3_v3v3(), BMLoop::e, BMVert::e, BME_TransData::factor, len(), BME_TransData::loc, madd_v3_v3v3fl(), BME_TransData::max, BME_TransData::maxfactor, BMLoop::next, normalize_v3(), NULL, BME_TransData::org, BMLoop::prev, sub_v3_v3v3(), BMLoop::v, and BME_TransData::weight.
Referenced by BME_bevel_edge(), and BME_bevel_vert().
static BMLoop* BME_bevel_vert (BMesh * bm, BMLoop * l, float value, int UNUSEDoptions, float * up_vec, BME_TransData_Head * td) [static]
Definition at line 620 of file BME_bevel.c.
References BM_face_split(), BME_bevel_split_edge(), BMLoop::e, BMLoop::f, BMLoop::next, NULL, BMLoop::prev, TRUE, and BMLoop::v.
Referenced by BME_bevel_poly().
void BME_free_transdata (BME_TransData_Head * td)
Definition at line 82 of file BME_bevel.c.
References BLI_ghash_free(), BLI_memarena_free(), BME_TransData_Head::gh, BME_TransData_Head::ma, MEM_freeN(), and NULL.
Referenced by BME_bevel().
BME_TransData* BME_get_transdata (BME_TransData_Head * td, BMVert * v) [read]
Definition at line 136 of file BME_bevel.c.
References BLI_ghash_lookup(), and BME_TransData_Head::gh.
Referenced by BME_bevel(), BME_bevel_add_vweight(), BME_bevel_get_vec(), BME_bevel_poly(), and BME_bevel_split_edge().
BME_TransData_Head* BME_init_transdata (int bufsize)
Definition at line 70 of file BME_bevel.c.
References BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BLI_memarena_new(), BLI_memarena_use_calloc(), BME_TransData_Head::gh, BME_TransData_Head::ma, and MEM_callocN().
Referenced by BME_bevel().
float* BME_new_transdata_float (BME_TransData_Head * td)
Definition at line 144 of file BME_bevel.c.
References BLI_memarena_alloc(), and BME_TransData_Head::ma.
Referenced by BME_bevel_split_edge().