Blender: SCA_MouseSensor Class Reference
SCA_MouseSensor Class Reference
#include <SCA_MouseSensor.h>
Public Types
enum KX_MOUSESENSORMODE {
KX_MOUSESENSORMODE_NODEF = 0, KX_MOUSESENSORMODE_LEFTBUTTON, KX_MOUSESENSORMODE_MIDDLEBUTTON, KX_MOUSESENSORMODE_RIGHTBUTTON,
KX_MOUSESENSORMODE_WHEELUP, KX_MOUSESENSORMODE_WHEELDOWN, KX_MOUSESENSORMODE_POSITION, KX_MOUSESENSORMODE_POSITIONX,
KX_MOUSESENSORMODE_POSITIONY, KX_MOUSESENSORMODE_MOVEMENT, KX_MOUSESENSORMODE_MAX
}
Public Member Functions
bool isValid (KX_MOUSESENSORMODE)
SCA_MouseSensor (class SCA_MouseManager *keybdmgr, int startx, int starty, short int mousemode, SCA_IObject *gameobj)
virtual ~SCA_MouseSensor ()
virtual CValue * GetReplica ()
virtual bool Evaluate ()
virtual void Init ()
virtual bool IsPositiveTrigger ()
short int GetModeKey ()
SCA_IInputDevice::KX_EnumInputs GetHotKey ()
void setX (short x)
void setY (short y)
Static Public Member Functions
static void UpdateHotkey (void *self)
Detailed Description
Definition at line 40 of file SCA_MouseSensor.h.
Member Enumeration Documentation
enum SCA_MouseSensor::KX_MOUSESENSORMODE
Allowable modes for the trigger status of the mouse sensor.
Enumerator:
KX_MOUSESENSORMODE_NODEF
KX_MOUSESENSORMODE_LEFTBUTTON
KX_MOUSESENSORMODE_MIDDLEBUTTON
KX_MOUSESENSORMODE_RIGHTBUTTON
KX_MOUSESENSORMODE_WHEELUP
KX_MOUSESENSORMODE_WHEELDOWN
KX_MOUSESENSORMODE_POSITION
KX_MOUSESENSORMODE_POSITIONX
KX_MOUSESENSORMODE_POSITIONY
KX_MOUSESENSORMODE_MOVEMENT
KX_MOUSESENSORMODE_MAX
Definition at line 74 of file SCA_MouseSensor.h.
Constructor & Destructor Documentation
SCA_MouseSensor::SCA_MouseSensor (class SCA_MouseManager * keybdmgr, int startx, int starty, short int mousemode, SCA_IObject * gameobj)
Definition at line 51 of file SCA_MouseSensor.cpp.
References Init(), and UpdateHotkey().
Referenced by GetReplica().
SCA_MouseSensor::~SCA_MouseSensor () [virtual]
Definition at line 72 of file SCA_MouseSensor.cpp.
Member Function Documentation
bool SCA_MouseSensor::Evaluate () [virtual]
Implements SCA_ISensor.
Reimplemented in KX_MouseFocusSensor.
Definition at line 144 of file SCA_MouseSensor.cpp.
References SCA_IInputDevice::GetEventValue(), SCA_InputEvent::KX_ACTIVE, SCA_InputEvent::KX_JUSTACTIVATED, SCA_InputEvent::KX_JUSTRELEASED, KX_MOUSESENSORMODE_LEFTBUTTON, KX_MOUSESENSORMODE_MIDDLEBUTTON, KX_MOUSESENSORMODE_MOVEMENT, KX_MOUSESENSORMODE_RIGHTBUTTON, KX_MOUSESENSORMODE_WHEELDOWN, KX_MOUSESENSORMODE_WHEELUP, SCA_IInputDevice::KX_MOUSEX, SCA_IInputDevice::KX_MOUSEY, SCA_ISensor::m_eventmgr, SCA_ISensor::m_level, SCA_ISensor::m_reset, and SCA_InputEvent::m_status.
SCA_IInputDevice::KX_EnumInputs SCA_MouseSensor::GetHotKey ()
Definition at line 137 of file SCA_MouseSensor.cpp.
short int SCA_MouseSensor::GetModeKey ()
Definition at line 130 of file SCA_MouseSensor.cpp.
CValue * SCA_MouseSensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Reimplemented in KX_MouseFocusSensor.
Definition at line 107 of file SCA_MouseSensor.cpp.
References Init(), SCA_ISensor::ProcessReplica(), and SCA_MouseSensor().
void SCA_MouseSensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Reimplemented in KX_MouseFocusSensor.
Definition at line 66 of file SCA_MouseSensor.cpp.
References SCA_ISensor::m_invert, and SCA_ISensor::m_reset.
Referenced by GetReplica(), and SCA_MouseSensor().
bool SCA_MouseSensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Reimplemented in KX_MouseFocusSensor.
Definition at line 119 of file SCA_MouseSensor.cpp.
References SCA_ISensor::m_invert.
bool SCA_MouseSensor::isValid (SCA_MouseSensor::KX_MOUSESENSORMODE m)
Definition at line 236 of file SCA_MouseSensor.cpp.
References KX_MOUSESENSORMODE_MAX, and KX_MOUSESENSORMODE_NODEF.
void SCA_MouseSensor::setX (short x)
Definition at line 226 of file SCA_MouseSensor.cpp.
Referenced by SCA_MouseManager::NextFrame().
void SCA_MouseSensor::setY (short y)
Definition at line 231 of file SCA_MouseSensor.cpp.
Referenced by SCA_MouseManager::NextFrame().
void SCA_MouseSensor::UpdateHotkey (void * self) [static]
Definition at line 77 of file SCA_MouseSensor.cpp.
References SCA_IInputDevice::KX_LEFTMOUSE, SCA_IInputDevice::KX_MIDDLEMOUSE, KX_MOUSESENSORMODE_LEFTBUTTON, KX_MOUSESENSORMODE_MIDDLEBUTTON, KX_MOUSESENSORMODE_RIGHTBUTTON, KX_MOUSESENSORMODE_WHEELDOWN, KX_MOUSESENSORMODE_WHEELUP, SCA_IInputDevice::KX_RIGHTMOUSE, SCA_IInputDevice::KX_WHEELDOWNMOUSE, and SCA_IInputDevice::KX_WHEELUPMOUSE.
Referenced by SCA_MouseSensor().
The documentation for this class was generated from the following files:
SCA_MouseSensor.h
SCA_MouseSensor.cpp