Blender: SG_DList::iterator< T > Class Template Reference
SG_DList::iterator< T > Class Template Reference
#include <SG_DList.h>
Public Types
typedef iterator< T > _myT
Public Member Functions
iterator (SG_DList &head)
~iterator ()
void begin ()
void back ()
bool end ()
bool add_back (T *item)
T * operator* ()
_myT & operator++ ()
_myT & operator-- ()
Detailed Description
template<typename T>
class SG_DList::iterator< T >
Definition at line 51 of file SG_DList.h.
Member Typedef Documentation
template<typename T> typedef iterator<T> SG_DList::iterator< T >::_myT
Definition at line 57 of file SG_DList.h.
Constructor & Destructor Documentation
template<typename T> SG_DList::iterator< T >::iterator (SG_DList & head) [inline]
Definition at line 58 of file SG_DList.h.
template<typename T> SG_DList::iterator< T >::~iterator () [inline]
Definition at line 59 of file SG_DList.h.
Member Function Documentation
template<typename T> bool SG_DList::iterator< T >::add_back (T * item) [inline]
Definition at line 73 of file SG_DList.h.
template<typename T> void SG_DList::iterator< T >::back () [inline]
Definition at line 65 of file SG_DList.h.
References SG_DList::Back(), and T.
template<typename T> void SG_DList::iterator< T >::begin () [inline]
Definition at line 61 of file SG_DList.h.
References SG_DList::Peek(), and T.
Referenced by BL_ArmatureObject::ApplyPose(), KX_TouchEventManager::EndFrame(), BL_ArmatureObject::GetChannel(), BL_ArmatureObject::GetConstraint(), SCA_RandomEventManager::NextFrame(), SCA_PropertyEventManager::NextFrame(), SCA_MouseManager::NextFrame(), SCA_KeyboardManager::NextFrame(), SCA_JoystickManager::NextFrame(), SCA_BasicEventManager::NextFrame(), SCA_AlwaysEventManager::NextFrame(), SCA_ActuatorEventManager::NextFrame(), KX_TouchEventManager::NextFrame(), KX_RayEventManager::NextFrame(), KX_NetworkEventManager::NextFrame(), BL_ArmatureObject::Relink(), BL_ArmatureObject::ReParentLogic(), BL_ArmatureObject::UnlinkObject(), SCA_LogicManager::UpdateFrame(), and SCA_ActuatorEventManager::UpdateFrame().
template<typename T> bool SG_DList::iterator< T >::end () [inline]
Definition at line 69 of file SG_DList.h.
References SG_DList::Self(), and T.
Referenced by BL_ArmatureObject::ApplyPose(), KX_TouchEventManager::EndFrame(), BL_ArmatureObject::GetChannel(), BL_ArmatureObject::GetConstraint(), SCA_RandomEventManager::NextFrame(), SCA_PropertyEventManager::NextFrame(), SCA_MouseManager::NextFrame(), SCA_KeyboardManager::NextFrame(), SCA_JoystickManager::NextFrame(), SCA_BasicEventManager::NextFrame(), SCA_AlwaysEventManager::NextFrame(), SCA_ActuatorEventManager::NextFrame(), KX_TouchEventManager::NextFrame(), KX_RayEventManager::NextFrame(), KX_NetworkEventManager::NextFrame(), BL_ArmatureObject::Relink(), BL_ArmatureObject::ReParentLogic(), BL_ArmatureObject::UnlinkObject(), SCA_LogicManager::UpdateFrame(), and SCA_ActuatorEventManager::UpdateFrame().
template<typename T> T* SG_DList::iterator< T >::operator* () [inline]
Definition at line 77 of file SG_DList.h.
template<typename T> _myT& SG_DList::iterator< T >::operator++ () [inline]
Definition at line 81 of file SG_DList.h.
References T.
template<typename T> _myT& SG_DList::iterator< T >::operator-- () [inline]
Definition at line 87 of file SG_DList.h.
References T.
The documentation for this class was generated from the following file:
SG_DList.h