Blender: memory.c File Reference
memory.c File Reference
opennl
#include "ssp_defs.h"
Functions
void copy_mem_int (int, void *, void *)
void user_bcopy (char *, char *, int)
void * superlu_malloc (size_t size)
void superlu_free (void *addr)
void SetIWork (int m, int n, int panel_size, int *iworkptr, int **segrep, int **parent, int **xplore, int **repfnz, int **panel_lsub, int **xprune, int **marker)
int * intMalloc (int n)
int * intCalloc (int n)
Detailed Description
Definition in file memory.c.
Function Documentation
void copy_mem_int (int howmany, void * old, void * new)
Precision-independent memory-related routines. (Shared by [sdcz]memory.c)
Definition at line 116 of file memory.c.
References i.
Referenced by sexpand(), and sStackCompress().
int* intCalloc (int n)
Definition at line 147 of file memory.c.
References ABORT, i, and SUPERLU_MALLOC.
Referenced by sCompRow_to_CompCol(), sLUWorkInit(), and StatInit().
int* intMalloc (int n)
Definition at line 137 of file memory.c.
References ABORT, and SUPERLU_MALLOC.
Referenced by heap_relax_snode(), sallocateA(), sCompRow_to_CompCol(), sgssv(), sgstrf(), and sLUMemInit().
void SetIWork (int m, int n, int panel_size, int * iworkptr, int ** segrep, int ** parent, int ** xplore, int ** repfnz, int ** panel_lsub, int ** xprune, int ** marker)
Definition at line 99 of file memory.c.
References EMPTY, and ifill().
Referenced by sgstrf().
void superlu_free (void * addr)
Definition at line 87 of file memory.c.
void* superlu_malloc (size_t size)
Definition at line 80 of file memory.c.
void user_bcopy (char * src, char * dest, int bytes)
Definition at line 126 of file memory.c.
Referenced by sexpand().