Blender: uvproject.c File Reference
uvproject.c File Reference
blenlib
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_camera_types.h"
#include "DNA_object_types.h"
#include "BLI_math.h"
#include "BLI_uvproject.h"
Classes
struct UvCameraInfo
Typedefs
typedef struct UvCameraInfo UvCameraInfo
Functions
void project_from_camera (float target[2], float source[3], UvCameraInfo *uci)
void project_from_view (float target[2], float source[3], float persmat[4][4], float rotmat[4][4], float winx, float winy)
UvCameraInfo * project_camera_info (Object *ob, float(*rotmat)[4], float winx, float winy)
void project_from_view_ortho (float target[2], float source[3], float rotmat[4][4])
void project_camera_info_scale (UvCameraInfo *uci, float scale_x, float scale_y)
Detailed Description
Definition in file uvproject.c.
Typedef Documentation
typedef struct UvCameraInfo UvCameraInfo
Function Documentation
UvCameraInfo* project_camera_info (Object * ob, float(*) rotmat[4], float winx, float winy)
Definition at line 136 of file uvproject.c.
References CAM_PANORAMA, CAM_PERSP, UvCameraInfo::camangle, UvCameraInfo::caminv, UvCameraInfo::camsize, copy_m4_m4(), Object::data, UvCameraInfo::do_pano, UvCameraInfo::do_persp, UvCameraInfo::do_rotmat, Camera::flag, focallength_to_fov(), invert_m4(), Camera::lens, MEM_mallocN(), normalize_m4(), NULL, Object::obmat, Camera::ortho_scale, UvCameraInfo::rotmat, Camera::sensor_x, Camera::shiftx, UvCameraInfo::shiftx, Camera::shifty, UvCameraInfo::shifty, tanf, Camera::type, UvCameraInfo::xasp, and UvCameraInfo::yasp.
void project_camera_info_scale (UvCameraInfo * uci, float scale_x, float scale_y)
Definition at line 196 of file uvproject.c.
References UvCameraInfo::xasp, and UvCameraInfo::yasp.
Referenced by uvprojectModifier_do().
void project_from_camera (float target[2], float source[3], UvCameraInfo * uci)
Definition at line 45 of file uvproject.c.
References angle(), atan2f, UvCameraInfo::camangle, UvCameraInfo::caminv, UvCameraInfo::camsize, copy_v3_v3(), UvCameraInfo::do_pano, UvCameraInfo::do_persp, UvCameraInfo::do_rotmat, len_v2(), M_PI, mul_m4_v4(), UvCameraInfo::rotmat, UvCameraInfo::shiftx, UvCameraInfo::shifty, UvCameraInfo::xasp, and UvCameraInfo::yasp.
Referenced by uv_from_view_exec(), and uvprojectModifier_do().
void project_from_view (float target[2], float source[3], float persmat[4][4], float rotmat[4][4], float winx, float winy)
Definition at line 96 of file uvproject.c.
References copy_v3_v3(), fabsf, mul_m4_v4(), and mul_v3_m4v3().
Referenced by uv_from_view_exec().
void project_from_view_ortho (float target[2], float source[3], float rotmat[4][4])
Definition at line 185 of file uvproject.c.
References mul_v3_m4v3().
Referenced by uv_from_view_exec().