Blender: multires.c File Reference
multires.c File Reference
blenkernel
#include "MEM_guardedalloc.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_bitmap.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_pbvh.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_mesh.h"
#include "BKE_modifier.h"
#include "BKE_multires.h"
#include "BKE_paint.h"
#include "BKE_scene.h"
#include "BKE_subsurf.h"
#include "BKE_tessmesh.h"
#include "BKE_object.h"
#include "CCGSubSurf.h"
#include <math.h>
#include <string.h>
Defines
#define DNA_DEPRECATED_ALLOW
Enumerations
enum DispOp { APPLY_DISPLACEMENTS, CALC_DISPLACEMENTS, ADD_DISPLACEMENTS }
Functions
static void multires_mvert_to_ss (DerivedMesh *dm, MVert *mvert)
static void multiresModifier_disp_run (DerivedMesh *dm, Mesh *me, DerivedMesh *dm2, DispOp op, DMGridData **oldGridData, int totlvl)
void multires_customdata_delete (Mesh *me)
static BLI_bitmap multires_mdisps_upsample_hidden (BLI_bitmap lo_hidden, int lo_level, int hi_level, BLI_bitmap prev_hidden)
static BLI_bitmap multires_mdisps_downsample_hidden (BLI_bitmap old_hidden, int old_level, int new_level)
static void multires_output_hidden_to_ccgdm (CCGDerivedMesh *ccgdm, Mesh *me, int level)
static void multires_mdisps_subdivide_hidden (MDisps *md, int new_level)
static MDisps * multires_mdisps_initialize_hidden (Mesh *me, int level)
DerivedMesh * get_multires_dm (Scene *scene, MultiresModifierData *mmd, Object *ob)
MultiresModifierData * find_multires_modifier_before (Scene *scene, ModifierData *lastmd)
MultiresModifierData * get_multires_modifier (Scene *scene, Object *ob, int use_first)
static int multires_get_level (Object *ob, MultiresModifierData *mmd, int render)
static void multires_set_tot_level (Object *ob, MultiresModifierData *mmd, int lvl)
static void multires_dm_mark_as_modified (DerivedMesh *dm, MultiresModifiedFlags flags)
void multires_mark_as_modified (Object *ob, MultiresModifiedFlags flags)
void multires_force_update (Object *ob)
void multires_force_external_reload (Object *ob)
void multires_force_render_update (Object *ob)
int multiresModifier_reshapeFromDM (Scene *scene, MultiresModifierData *mmd, Object *ob, DerivedMesh *srcdm)
int multiresModifier_reshape (Scene *scene, MultiresModifierData *mmd, Object *dst, Object *src)
int multiresModifier_reshapeFromDeformMod (Scene *scene, MultiresModifierData *mmd, Object *ob, ModifierData *md)
static int get_levels_from_disps (Object *ob)
void multiresModifier_set_levels_from_disps (MultiresModifierData *mmd, Object *ob)
static void multires_set_tot_mdisps (Mesh *me, int lvl)
static void multires_reallocate_mdisps (int totloop, MDisps *mdisps, int lvl)
static void column_vectors_to_mat3 (float mat[][3], float v1[3], float v2[3], float v3[3])
static void multires_copy_grid (float(*gridA)[3], float(*gridB)[3], int sizeA, int sizeB)
static void multires_copy_dm_grid (DMGridData *gridA, DMGridData *gridB, int sizeA, int sizeB)
static void multires_del_higher (MultiresModifierData *mmd, Object *ob, int lvl)
void multiresModifier_del_levels (MultiresModifierData *mmd, Object *ob, int direction)
static DerivedMesh * multires_dm_create_local (Object *ob, DerivedMesh *dm, int lvl, int totlvl, int simple)
static DerivedMesh * subsurf_dm_create_local (Object *ob, DerivedMesh *dm, int lvl, int simple, int optimal, int plain_uv)
static float v3_dist_from_plane (float v[3], float center[3], float no[3])
void multiresModifier_base_apply (MultiresModifierData *mmd, Object *ob)
static void multires_subdivide (MultiresModifierData *mmd, Object *ob, int totlvl, int updateblock, int simple)
void multiresModifier_subdivide (MultiresModifierData *mmd, Object *ob, int updateblock, int simple)
void grid_tangent (int gridSize, int index, int x, int y, int axis, DMGridData **gridData, float t[3])
void multires_modifier_update_mdisps (struct DerivedMesh *dm)
void multires_modifier_update_hidden (DerivedMesh *dm)
void multires_set_space (DerivedMesh *dm, Object *ob, int from, int to)
void multires_stitch_grids (Object *ob)
DerivedMesh * multires_dm_create_from_derived (MultiresModifierData *mmd, int local_mmd, DerivedMesh *dm, Object *ob, int useRenderParams)
void old_mdisps_bilinear (float out[3], float(*disps)[3], const int st, float u, float v)
static void old_mdisps_rotate (int S, int UNUSED(newside), int oldside, int x, int y, float *u, float *v)
static void old_mdisps_convert (MFace *mface, MDisps *mdisp)
void multires_load_old_250 (Mesh *me)
static void multires_free_level (MultiresLevel *lvl)
void multires_free (Multires *mr)
static void create_old_vert_face_map (ListBase **map, IndexNode **mem, const MultiresFace *mface, const int totvert, const int totface)
static void create_old_vert_edge_map (ListBase **map, IndexNode **mem, const MultiresEdge *medge, const int totvert, const int totedge)
static MultiresFace * find_old_face (ListBase *map, MultiresFace *faces, int v1, int v2, int v3, int v4)
static MultiresEdge * find_old_edge (ListBase *map, MultiresEdge *edges, int v1, int v2)
static void multires_load_old_edges (ListBase **emap, MultiresLevel *lvl, int *vvmap, int dst, int v1, int v2, int mov)
static void multires_load_old_faces (ListBase **fmap, ListBase **emap, MultiresLevel *lvl, int *vvmap, int dst, int v1, int v2, int v3, int v4, int st2, int st3)
static void multires_load_old_dm (DerivedMesh *dm, Mesh *me, int totlvl)
static void multires_load_old_vcols (Mesh *me)
static void multires_load_old_face_flags (Mesh *me)
void multires_load_old (Object *ob, Mesh *me)
static void multires_sync_levels (Scene *scene, Object *ob, Object *to_ob)
static void multires_apply_smat (Scene *scene, Object *ob, float smat[3][3])
int multires_mdisp_corners (MDisps *s)
void multiresModifier_scale_disp (Scene *scene, Object *ob)
void multiresModifier_prepare_join (Scene *scene, Object *ob, Object *to_ob)
void multires_topology_changed (Mesh *me)
int mdisp_rot_face_to_crn (const int corners, const int face_side, const float u, const float v, float *x, float *y)
Variables
static const int multires_max_levels = 13
static const int multires_grid_tot [] = {0, 4, 9, 25, 81, 289, 1089, 4225, 16641, 66049, 263169, 1050625, 4198401, 16785409}
static const int multires_side_tot [] = {0, 2, 3, 5, 9, 17, 33, 65, 129, 257, 513, 1025, 2049, 4097}
Detailed Description
Definition in file multires.c.
Define Documentation
#define DNA_DEPRECATED_ALLOW
Definition at line 36 of file multires.c.
Enumeration Type Documentation
enum DispOp
Enumerator:
APPLY_DISPLACEMENTS
CALC_DISPLACEMENTS
ADD_DISPLACEMENTS
Definition at line 71 of file multires.c.
Function Documentation
static void column_vectors_to_mat3 (float mat[][3], float v1[3], float v2[3], float v3[3]) [static]
Definition at line 545 of file multires.c.
References copy_v3_v3().
Referenced by multires_apply_smat(), multires_set_space(), and multiresModifier_disp_run().
static void create_old_vert_edge_map (ListBase ** map, IndexNode ** mem, const MultiresEdge * medge, const int totvert, const int totedge) [static]
Definition at line 1566 of file multires.c.
References BLI_addtail(), i, IndexNode::index, MEM_callocN(), and NULL.
Referenced by multires_load_old_dm().
static void create_old_vert_face_map (ListBase ** map, IndexNode ** mem, const MultiresFace * mface, const int totvert, const int totface) [static]
Definition at line 1547 of file multires.c.
References BLI_addtail(), i, IndexNode::index, MEM_callocN(), NULL, and MultiresFace::v.
Referenced by multires_load_old_dm().
MultiresModifierData* find_multires_modifier_before (Scene * scene, ModifierData * lastmd) [read]
Definition at line 290 of file multires.c.
References eModifierMode_Realtime, eModifierType_Multires, modifier_isEnabled(), NULL, ModifierData::prev, and ModifierData::type.
Referenced by modifier_apply_obdata().
static MultiresEdge* find_old_edge (ListBase * map, MultiresEdge * edges, int v1, int v2) [static]
Definition at line 1612 of file multires.c.
References IndexNode::index, IndexNode::next, and NULL.
Referenced by multires_load_old_dm(), multires_load_old_edges(), and multires_load_old_faces().
static MultiresFace* find_old_face (ListBase * map, MultiresFace * faces, int v1, int v2, int v3, int v4) [static]
Definition at line 1585 of file multires.c.
References i, IndexNode::index, IndexNode::next, NULL, and MultiresFace::v.
Referenced by multires_load_old_faces().
static int get_levels_from_disps (Object * ob) [static]
Definition at line 459 of file multires.c.
References CD_MDISPS, CustomData_get_layer(), Object::data, i, Mesh::ldata, MPoly::loopstart, Mesh::mpoly, MDisps::totdisp, MPoly::totloop, and Mesh::totpoly.
Referenced by multiresModifier_set_levels_from_disps().
DerivedMesh* get_multires_dm (Scene * scene, MultiresModifierData * mmd, Object * ob) [read]
Definition at line 275 of file multires.c.
References ModifierTypeInfo::applyModifier, CD_MASK_BAREMESH, CDDM_copy(), mesh_get_derived_deform(), modifierType_getInfo(), mti, and ModifierData::type.
Referenced by multires_apply_smat(), multiresModifier_reshapeFromDeformMod(), and multiresModifier_reshapeFromDM().
MultiresModifierData* get_multires_modifier (Scene * scene, Object * ob, int use_first) [read]
Definition at line 307 of file multires.c.
References eModifierMode_Realtime, eModifierType_Multires, ListBase::first, modifier_isEnabled(), Object::modifiers, ModifierData::next, NULL, and ModifierData::type.
Referenced by mesh_calc_modifiers(), multires_apply_smat(), multires_set_space(), multires_sync_levels(), multiresbake_check(), multiresbake_create_hiresdm(), multiresbake_create_loresdm(), and sculpt_get_first_deform_matrices().
void grid_tangent (int gridSize, int index, int x, int y, int axis, DMGridData ** gridData, float t[3])
Definition at line 914 of file multires.c.
References co, and sub_v3_v3v3().
Referenced by multires_apply_smat(), multires_set_space(), and multiresModifier_disp_run().
int mdisp_rot_face_to_crn (const int corners, const int face_side, const float u, const float v, float * x, float * y)
Definition at line 2205 of file multires.c.
Referenced by get_ccgdm_data().
static void multires_apply_smat (Scene * scene, Object * ob, float smat[3][3]) [static]
Definition at line 2037 of file multires.c.
References CD_MASK_BAREMESH, CD_MASK_MDISPS, CD_MDISPS, CDDM_apply_vert_coords(), DMGridData::co, co, column_vectors_to_mat3(), CustomData_external_read(), CustomData_get_layer(), data, Object::data, MDisps::disps, eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, get_multires_dm(), get_multires_modifier(), DerivedMesh::getGridData, DerivedMesh::getGridOffset, DerivedMesh::getGridSize, grid_tangent(), i, Mesh::id, invert_m3(), Mesh::ldata, MultiresModifierData::lvl, MEM_freeN(), MEM_mallocN(), mesh_get_derived_deform(), Mesh::mpoly, mul_m3_v3(), mul_v3_m3v3(), multires_side_tot, DMGridData::no, normalize_v3(), NULL, DerivedMesh::release, MultiresModifierData::simple, sub_v3_v3v3(), subsurf_dm_create_local(), Mesh::totloop, MultiresModifierData::totlvl, and Mesh::totpoly.
Referenced by multiresModifier_prepare_join(), and multiresModifier_scale_disp().
static void multires_copy_dm_grid (DMGridData * gridA, DMGridData * gridB, int sizeA, int sizeB) [static]
Definition at line 572 of file multires.c.
References co, and copy_v3_v3().
Referenced by multires_modifier_update_mdisps(), and multires_subdivide().
static void multires_copy_grid (float(*) gridA[3], float(*) gridB[3], int sizeA, int sizeB) [static]
Definition at line 552 of file multires.c.
References copy_v3_v3().
Referenced by multires_del_higher().
void multires_customdata_delete (Mesh * me)
Customdata
Definition at line 82 of file multires.c.
References BMEditMesh::bm, BM_data_layer_free(), CD_MDISPS, CustomData_external_remove(), CustomData_free_layer_active(), Mesh::edit_btmesh, Mesh::id, Mesh::ldata, BMesh::ldata, and Mesh::totloop.
Referenced by modifier_apply_obdata(), multires_del_higher(), multires_sync_levels(), and object_modifier_remove().
static void multires_del_higher (MultiresModifierData * mmd, Object * ob, int lvl) [static]
Definition at line 592 of file multires.c.
References CD_MASK_MDISPS, CD_MDISPS, CustomData_external_read(), CustomData_get_layer(), Object::data, MDisps::disps, MDisps::hidden, i, Mesh::id, Mesh::ldata, MDisps::level, MPoly::loopstart, MEM_callocN(), MEM_freeN(), Mesh::mpoly, multires_copy_grid(), multires_customdata_delete(), multires_force_update(), multires_grid_tot, multires_mdisps_downsample_hidden(), multires_set_tot_level(), multires_set_tot_mdisps(), multires_side_tot, MDisps::totdisp, Mesh::totloop, MPoly::totloop, MultiresModifierData::totlvl, and Mesh::totpoly.
Referenced by multires_sync_levels(), and multiresModifier_del_levels().
DerivedMesh* multires_dm_create_from_derived (MultiresModifierData * mmd, int local_mmd, DerivedMesh * dm, Object * ob, int useRenderParams) [read]
Definition at line 1326 of file multires.c.
References APPLY_DISPLACEMENTS, CD_MASK_MDISPS, CustomData_external_read(), Object::data, eMultiresModifierFlag_ControlEdges, eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, DerivedMesh::getGridData, DerivedMesh::getGridSize, DerivedMesh::getNumGrids, i, Mesh::id, Mesh::ldata, CCGDerivedMesh::local_mmd, CCGDerivedMesh::lvl, MEM_callocN(), MEM_freeN(), CCGDerivedMesh::mmd, CCGDerivedMesh::modified_flags, CCGDerivedMesh::multires, multires_get_level(), multires_output_hidden_to_ccgdm(), multires_set_tot_mdisps(), multiresModifier_disp_run(), NULL, CCGDerivedMesh::ob, MultiresModifierData::simple, subsurf_dm_create_local(), Mesh::totloop, MultiresModifierData::totlvl, and CCGDerivedMesh::totlvl.
Referenced by applyModifier(), multires_dm_create_local(), multires_load_old(), multiresbake_create_hiresdm(), and multiresbake_create_loresdm().
static DerivedMesh* multires_dm_create_local (Object * ob, DerivedMesh * dm, int lvl, int totlvl, int simple) [static]
Definition at line 671 of file multires.c.
References MultiresModifierData::lvl, multires_dm_create_from_derived(), NULL, MultiresModifierData::renderlvl, MultiresModifierData::sculptlvl, MultiresModifierData::simple, and MultiresModifierData::totlvl.
Referenced by multires_modifier_update_mdisps(), multires_set_space(), multires_subdivide(), and multiresModifier_base_apply().
static void multires_dm_mark_as_modified (DerivedMesh * dm, MultiresModifiedFlags flags) [static]
Definition at line 355 of file multires.c.
References CCGDerivedMesh::modified_flags, and CCGDerivedMesh::multires.
Referenced by multires_load_old(), multires_mark_as_modified(), and multiresModifier_reshapeFromDM().
void multires_force_external_reload (Object * ob)
Definition at line 382 of file multires.c.
References CD_MASK_MDISPS, CustomData_external_reload(), get_mesh(), Mesh::id, Mesh::ldata, multires_force_update(), and Mesh::totloop.
void multires_force_render_update (Object * ob)
Definition at line 390 of file multires.c.
References eModifierType_Multires, Object::mode, modifiers_findByType(), multires_force_update(), and OB_MODE_SCULPT.
Referenced by screen_render_invoke().
void multires_force_update (Object * ob)
Definition at line 367 of file multires.c.
References BLI_pbvh_free(), Object::derivedFinal, DerivedMesh::needsFree, NULL, SculptSession::pbvh, DerivedMesh::release, and Object::sculpt.
Referenced by ED_sculpt_force_update(), init_multiresbake_job(), modifier_apply_obdata(), multires_del_higher(), multires_force_external_reload(), multires_force_render_update(), multires_subdivide(), multiresbake_image_exec_locked(), multiresModifier_base_apply(), multiresModifier_del_levels(), multiresModifier_reshapeFromDM(), sculpt_toggle_mode(), and set_mesh().
void multires_free (Multires * mr)
Definition at line 1519 of file multires.c.
References BLI_freelistN(), CustomData_free(), Multires::edge_creases, Multires::edge_flags, Multires::fdata, ListBase::first, Multires::levels, MEM_freeN(), multires_free_level(), MultiresLevel::next, MultiresLevel::totface, MultiresLevel::totvert, Multires::vdata, and Multires::verts.
Referenced by direct_link_mesh(), and multires_load_old().
static void multires_free_level (MultiresLevel * lvl) [static]
Definition at line 1510 of file multires.c.
References MultiresLevel::colfaces, MultiresLevel::edges, MultiresLevel::faces, and MEM_freeN().
Referenced by multires_free().
static int multires_get_level (Object * ob, MultiresModifierData * mmd, int render) [static]
Definition at line 334 of file multires.c.
References get_render_subsurf_level(), MultiresModifierData::lvl, Object::mode, MultiresModifierData::modifier, OB_MODE_SCULPT, Scene::r, MultiresModifierData::renderlvl, ModifierData::scene, and MultiresModifierData::sculptlvl.
Referenced by multires_dm_create_from_derived(), multiresModifier_del_levels(), and multiresModifier_reshapeFromDeformMod().
void multires_load_old (Object * ob, Mesh * me)
Definition at line 1948 of file multires.c.
References BLI_insertlinkbefore(), CD_CALLOC, CD_MEDGE, CD_MFACE, CD_MVERT, CD_REFERENCE, CDDM_from_mesh(), CustomData_add_layer(), CustomData_free_layers(), CustomDataLayer::data, MultiresLevel::edges, eModifierType_Multires, eModifierTypeType_OnlyDeform, MultiresLevel::faces, Mesh::fdata, ListBase::first, i, CustomData::layers, MultiresModifierData::lvl, MultiresFace::mat_nr, MFace::mat_nr, Mesh::medge, Mesh::mface, modifier_new(), Object::modifiers, modifierType_getInfo(), MULTIRES_COORDS_MODIFIED, multires_dm_create_from_derived(), multires_dm_mark_as_modified(), multires_free(), multires_load_old_dm(), multires_load_old_face_flags(), multires_load_old_vcols(), multiresModifier_subdivide(), Mesh::mvert, ModifierData::next, NULL, DerivedMesh::release, Mesh::totedge, MultiresLevel::totedge, Mesh::totface, MultiresLevel::totface, MultiresModifierData::totlvl, Mesh::totvert, MultiresLevel::totvert, CustomDataLayer::type, ModifierTypeInfo::type, ModifierData::type, MultiresFace::v, MultiresEdge::v, MFace::v1, MEdge::v1, MFace::v2, MEdge::v2, MFace::v3, MFace::v4, and Mesh::verts.
Referenced by do_versions().
void multires_load_old_250 (Mesh * me)
Definition at line 1476 of file multires.c.
References CD_CALLOC, CD_MDISPS, CustomData_add_layer(), CustomData_get_layer(), MDisps::disps, Mesh::fdata, i, Mesh::ldata, MDisps::level, MEM_callocN(), Mesh::mface, NULL, old_mdisps_convert(), MDisps::totdisp, Mesh::totface, Mesh::totloop, and MFace::v4.
Referenced by do_versions().
static void multires_load_old_dm (DerivedMesh * dm, Mesh * me, int totlvl) [static]
Definition at line 1735 of file multires.c.
References co, copy_v3_v3(), create_old_vert_edge_map(), create_old_vert_face_map(), MultiresLevel::edges, MultiresLevel::faces, find_old_edge(), ListBase::first, DerivedMesh::getNumVerts, DerivedMesh::getVertArray, i, Multires::level_count, Multires::levels, MEM_callocN(), MEM_freeN(), MultiresEdge::mid, multires_load_old_faces(), multires_mvert_to_ss(), multires_side_tot, MultiresLevel::next, pow(), MultiresLevel::prev, MultiresLevel::totedge, MultiresLevel::totface, MultiresLevel::totvert, MultiresFace::v, and Multires::verts.
Referenced by multires_load_old().
static void multires_load_old_edges (ListBase ** emap, MultiresLevel * lvl, int * vvmap, int dst, int v1, int v2, int mov) [static]
Definition at line 1626 of file multires.c.
References MultiresLevel::edges, find_old_edge(), MultiresEdge::mid, and MultiresLevel::next.
Referenced by multires_load_old_faces().
static void multires_load_old_face_flags (Mesh * me) [static]
Definition at line 1932 of file multires.c.
References MultiresLevel::faces, MFace::flag, MultiresFace::flag, i, Mesh::mface, and Mesh::totface.
Referenced by multires_load_old().
static void multires_load_old_faces (ListBase ** fmap, ListBase ** emap, MultiresLevel * lvl, int * vvmap, int dst, int v1, int v2, int v3, int v4, int st2, int st3) [static]
Definition at line 1637 of file multires.c.
References MultiresLevel::edges, MultiresLevel::faces, find_old_edge(), find_old_face(), MultiresFace::mid, MultiresEdge::mid, multires_load_old_edges(), and MultiresLevel::next.
Referenced by multires_load_old_dm().
static void multires_load_old_vcols (Mesh * me) [static]
Definition at line 1903 of file multires.c.
References MultiresCol::a, MCol::a, MultiresCol::b, MCol::b, CD_MCOL, MultiresColFace::col, MultiresLevel::colfaces, CustomData_get_layer(), Mesh::fdata, MultiresCol::g, MCol::g, i, MCol::r, MultiresCol::r, and Mesh::totface.
Referenced by multires_load_old().
void multires_mark_as_modified (Object * ob, MultiresModifiedFlags flags)
Definition at line 361 of file multires.c.
References Object::derivedFinal, and multires_dm_mark_as_modified().
Referenced by partialvis_update_grids(), sculpt_flush_update(), and sculpt_undo_restore().
int multires_mdisp_corners (MDisps * s)
Definition at line 2131 of file multires.c.
References MDisps::totdisp.
Referenced by bm_corners_to_loops(), and layerSwap_mdisps().
static BLI_bitmap multires_mdisps_downsample_hidden (BLI_bitmap old_hidden, int old_level, int new_level) [static]
Definition at line 165 of file multires.c.
References BLI_assert, BLI_BITMAP_GET, BLI_BITMAP_MODIFY, BLI_BITMAP_NEW, ccg_factor(), and ccg_gridsize().
Referenced by multires_del_higher(), and multires_output_hidden_to_ccgdm().
static MDisps* multires_mdisps_initialize_hidden (Mesh * me, int level) [static]
Definition at line 239 of file multires.c.
References BLI_assert, BLI_BITMAP_NEW, BLI_BITMAP_SET, ccg_gridsize(), CD_CALLOC, CD_MDISPS, CustomData_add_layer(), MVert::flag, MDisps::hidden, i, Mesh::ldata, MPoly::loopstart, ME_HIDE, Mesh::mloop, Mesh::mpoly, Mesh::mvert, Mesh::totloop, MPoly::totloop, Mesh::totpoly, and MLoop::v.
Referenced by multires_subdivide().
static void multires_mdisps_subdivide_hidden (MDisps * md, int new_level) [static]
Definition at line 219 of file multires.c.
References BLI_assert, MDisps::hidden, MDisps::level, MEM_freeN(), multires_mdisps_upsample_hidden(), and NULL.
Referenced by multires_reallocate_mdisps().
static BLI_bitmap multires_mdisps_upsample_hidden (BLI_bitmap lo_hidden, int lo_level, int hi_level, BLI_bitmap prev_hidden) [static]
Grid hiding
Definition at line 102 of file multires.c.
References BLI_assert, BLI_BITMAP_GET, BLI_BITMAP_MODIFY, BLI_BITMAP_NEW, ccg_factor(), ccg_gridsize(), and MEM_dupallocN().
Referenced by multires_mdisps_subdivide_hidden(), and multires_modifier_update_hidden().
void multires_modifier_update_hidden (DerivedMesh * dm)
Definition at line 1148 of file multires.c.
References CD_MDISPS, CustomData_get_layer(), Object::data, CCGDerivedMesh::gridHidden, MDisps::hidden, i, Mesh::ldata, CCGDerivedMesh::lvl, MEM_freeN(), CCGDerivedMesh::multires, multires_mdisps_upsample_hidden(), NULL, CCGDerivedMesh::ob, Mesh::totloop, and CCGDerivedMesh::totlvl.
Referenced by ccgDM_release().
void multires_modifier_update_mdisps (struct DerivedMesh * dm)
Definition at line 1053 of file multires.c.
References ADD_DISPLACEMENTS, CALC_DISPLACEMENTS, ccgSubSurf_updateFromFaces(), ccgSubSurf_updateLevels(), CD_MASK_BAREMESH, CD_MASK_MDISPS, CD_MDISPS, CDDM_copy(), CDDM_from_mesh(), co, CustomData_external_read(), CustomData_get_layer(), Object::data, Object::derivedDeform, DM_set_only_copy(), eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, DerivedMesh::getGridData, DerivedMesh::getGridSize, DerivedMesh::getNumGrids, i, Mesh::id, Mesh::ldata, CCGDerivedMesh::lvl, MEM_callocN(), MEM_freeN(), CCGDerivedMesh::mmd, CCGDerivedMesh::multires, multires_copy_dm_grid(), multires_dm_create_local(), multires_set_tot_mdisps(), multiresModifier_disp_run(), NULL, CCGDerivedMesh::ob, DerivedMesh::release, MultiresModifierData::simple, sub_v3_v3v3(), subsurf_dm_create_local(), Mesh::totloop, CCGDerivedMesh::totlvl, and MultiresModifierData::totlvl.
Referenced by ccgDM_release().
static void multires_mvert_to_ss (DerivedMesh * dm, MVert * mvert) [static]
Definition at line 1674 of file multires.c.
References ccgSubSurf_getEdgeData(), ccgSubSurf_getEdgeSize(), ccgSubSurf_getFaceCenterData(), ccgSubSurf_getFaceGridData(), ccgSubSurf_getFaceGridEdgeData(), ccgSubSurf_getFaceNumVerts(), ccgSubSurf_getGridSize(), ccgSubSurf_getNumEdges(), ccgSubSurf_getNumFaces(), ccgSubSurf_getNumVerts(), ccgSubSurf_getVertData(), ccgSubSurf_updateToFaces(), DMGridData::co, MVert::co, copy_v3_v3(), CCGDerivedMesh::edge, CCGDerivedMesh::edgeMap, CCGDerivedMesh::face, CCGDerivedMesh::faceMap, i, NULL, CCGDerivedMesh::ss, CCGDerivedMesh::vert, and CCGDerivedMesh::vertMap.
Referenced by multires_load_old_dm(), and multiresModifier_reshapeFromDM().
static void multires_output_hidden_to_ccgdm (CCGDerivedMesh * ccgdm, Mesh * me, int level) [static]
Definition at line 193 of file multires.c.
References CD_MDISPS, CustomData_get_layer(), CCGDerivedMesh::dm, g, DerivedMesh::getGridOffset, CCGDerivedMesh::gridHidden, MDisps::hidden, i, Mesh::ldata, MDisps::level, Mesh::mpoly, multires_mdisps_downsample_hidden(), MPoly::totloop, and Mesh::totpoly.
Referenced by multires_dm_create_from_derived().
static void multires_reallocate_mdisps (int totloop, MDisps * mdisps, int lvl) [static]
Definition at line 524 of file multires.c.
References MDisps::disps, i, MDisps::level, MEM_callocN(), MEM_freeN(), multires_grid_tot, multires_mdisps_subdivide_hidden(), and MDisps::totdisp.
Referenced by multires_subdivide(), and multiresModifier_disp_run().
void multires_set_space (DerivedMesh * dm, Object * ob, int from, int to)
Definition at line 1180 of file multires.c.
References add_v3_v3(), add_v3_v3v3(), CD_MDISPS, CD_MPOLY, DMGridData::co, co, column_vectors_to_mat3(), copy_v3_v3(), CustomData_get_layer(), data, MDisps::disps, eMultiresModifierFlag_ControlEdges, eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, get_multires_modifier(), DerivedMesh::getGridData, DerivedMesh::getGridOffset, DerivedMesh::getGridSize, grid_tangent(), i, invert_m3(), MDisps::level, DerivedMesh::loopData, MPoly::loopstart, MEM_callocN(), mul_v3_m3v3(), multires_dm_create_local(), multires_side_tot, MULTIRES_SPACE_ABSOLUTE, MULTIRES_SPACE_OBJECT, MULTIRES_SPACE_TANGENT, DerivedMesh::needsFree, DMGridData::no, normalize_v3(), NULL, DerivedMesh::numPolyData, DerivedMesh::polyData, DerivedMesh::release, MultiresModifierData::simple, sub_v3_v3(), subsurf_dm_create_local(), MDisps::totdisp, MPoly::totloop, and MultiresModifierData::totlvl.
Referenced by bm_mdisps_space_set().
static void multires_set_tot_level (Object * ob, MultiresModifierData * mmd, int lvl) [static]
Definition at line 344 of file multires.c.
References CLAMPIS, MultiresModifierData::lvl, MAX2, Object::mode, OB_MODE_SCULPT, MultiresModifierData::renderlvl, MultiresModifierData::sculptlvl, and MultiresModifierData::totlvl.
Referenced by multires_del_higher(), multires_subdivide(), and multiresModifier_del_levels().
static void multires_set_tot_mdisps (Mesh * me, int lvl) [static]
Definition at line 511 of file multires.c.
References CD_MDISPS, CustomData_get_layer(), i, Mesh::ldata, MDisps::level, multires_grid_tot, MDisps::totdisp, and Mesh::totloop.
Referenced by multires_del_higher(), multires_dm_create_from_derived(), multires_modifier_update_mdisps(), and multiresModifier_del_levels().
void multires_stitch_grids (Object * ob)
Definition at line 1307 of file multires.c.
References BLI_pbvh_get_grid_updates(), ccgSubSurf_stitchFaces(), Object::derivedFinal, if(), MEM_freeN(), CCGDerivedMesh::pbvh, and CCGDerivedMesh::ss.
Referenced by sculpt_fix_noise_tear(), and smooth().
static void multires_subdivide (MultiresModifierData * mmd, Object * ob, int totlvl, int updateblock, int simple) [static]
Definition at line 832 of file multires.c.
References CALC_DISPLACEMENTS, ccgSubSurf_updateFromFaces(), ccgSubSurf_updateLevels(), CD_MASK_BAREMESH, CD_MDISPS, CDDM_from_mesh(), CustomData_get_layer(), Object::data, MDisps::disps, DM_set_only_copy(), eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, DerivedMesh::getGridData, DerivedMesh::getGridSize, DerivedMesh::getNumGrids, i, Mesh::ldata, MEM_callocN(), MEM_freeN(), multires_copy_dm_grid(), multires_dm_create_local(), multires_force_update(), multires_max_levels, multires_mdisps_initialize_hidden(), multires_reallocate_mdisps(), multires_set_tot_level(), multiresModifier_disp_run(), NULL, DerivedMesh::release, subsurf_dm_create_local(), Mesh::totloop, and MultiresModifierData::totlvl.
Referenced by multires_sync_levels(), and multiresModifier_subdivide().
static void multires_sync_levels (Scene * scene, Object * ob, Object * to_ob) [static]
Definition at line 2017 of file multires.c.
References Object::data, get_multires_modifier(), multires_customdata_delete(), multires_del_higher(), multires_subdivide(), MultiresModifierData::simple, and MultiresModifierData::totlvl.
Referenced by multiresModifier_prepare_join().
void multires_topology_changed (Mesh * me)
Definition at line 2169 of file multires.c.
References CD_MASK_MDISPS, CD_MDISPS, CustomData_external_read(), CustomData_get_layer(), MDisps::disps, i, Mesh::id, Mesh::ldata, MEM_callocN(), NULL, MDisps::totdisp, Mesh::totface, and Mesh::totloop.
Referenced by BM_mesh_bm_to_me().
void multiresModifier_base_apply (MultiresModifierData * mmd, Object * ob)
Definition at line 710 of file multires.c.
References add_v3_v3(), CALC_DISPLACEMENTS, CD_MASK_BAREMESH, CDDM_from_mesh(), MVert::co, copy_v3_v3(), MeshElemMap::count, DM_set_only_copy(), eMultiresModifierFlag_PlainUv, MultiresModifierData::flags, get_mesh(), DerivedMesh::getGridData, DerivedMesh::getNumVerts, DerivedMesh::getPolyMap, DerivedMesh::getVertCo, i, MeshElemMap::indices, MPoly::loopstart, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mesh_calc_poly_normal_coords(), Mesh::mloop, Mesh::mpoly, mul_v3_fl(), multires_dm_create_local(), multires_force_update(), multiresModifier_disp_run(), Mesh::mvert, normalize_v3(), NULL, p, DerivedMesh::release, subsurf_dm_create_local(), MPoly::totloop, MultiresModifierData::totlvl, Mesh::totvert, MLoop::v, and v3_dist_from_plane().
Referenced by multires_base_apply_exec().
void multiresModifier_del_levels (MultiresModifierData * mmd, Object * ob, int direction)
Definition at line 651 of file multires.c.
References CD_MASK_MDISPS, CD_MDISPS, CustomData_external_read(), CustomData_get_layer(), get_mesh(), Mesh::id, Mesh::ldata, multires_del_higher(), multires_force_update(), multires_get_level(), multires_set_tot_level(), multires_set_tot_mdisps(), Mesh::totloop, and MultiresModifierData::totlvl.
Referenced by multires_higher_levels_delete_exec().
static void multiresModifier_disp_run (DerivedMesh * dm, Mesh * me, DerivedMesh * dm2, DispOp op, DMGridData ** oldGridData, int totlvl) [static]
Definition at line 938 of file multires.c.
References ADD_DISPLACEMENTS, add_v3_v3(), add_v3_v3v3(), APPLY_DISPLACEMENTS, CALC_DISPLACEMENTS, ccgSubSurf_stitchFaces(), ccgSubSurf_updateNormals(), CD_DEFAULT, CD_MDISPS, CD_MPOLY, DMGridData::co, co, column_vectors_to_mat3(), CustomData_add_layer(), CustomData_get_layer(), CustomData_has_layer(), data, MDisps::disps, DerivedMesh::getGridData, DerivedMesh::getGridOffset, DerivedMesh::getGridSize, grid_tangent(), i, invert_m3(), Mesh::ldata, DerivedMesh::loopData, MPoly::loopstart, Mesh::mpoly, mul_v3_m3v3(), multires_reallocate_mdisps(), multires_side_tot, DMGridData::no, normalize_v3(), NULL, DerivedMesh::numLoopData, DerivedMesh::numPolyData, DerivedMesh::polyData, CCGDerivedMesh::ss, sub_v3_v3v3(), MPoly::totloop, Mesh::totloop, and Mesh::totpoly.
Referenced by multires_dm_create_from_derived(), multires_modifier_update_mdisps(), multires_subdivide(), and multiresModifier_base_apply().
void multiresModifier_prepare_join (Scene * scene, Object * ob, Object * to_ob)
Definition at line 2154 of file multires.c.
References invert_m3(), mul_m3_m3m3(), multires_apply_smat(), multires_sync_levels(), and object_scale_to_mat3().
Referenced by join_mesh_exec().
int multiresModifier_reshape (Scene * scene, MultiresModifierData * mmd, Object * dst, Object * src)
Definition at line 418 of file multires.c.
References CD_MASK_BAREMESH, mesh_get_derived_final(), and multiresModifier_reshapeFromDM().
Referenced by multires_reshape_exec().
int multiresModifier_reshapeFromDeformMod (Scene * scene, MultiresModifierData * mmd, Object * ob, ModifierData * md)
Definition at line 424 of file multires.c.
References CDDM_apply_vert_coords(), CDDM_copy(), ModifierTypeInfo::deformVerts, get_multires_dm(), DerivedMesh::getNumVerts, DerivedMesh::getVertCos, MEM_callocN(), MEM_freeN(), modifierType_getInfo(), mti, multires_get_level(), multiresModifier_reshapeFromDM(), DerivedMesh::release, and ModifierData::type.
Referenced by modifier_apply_obdata().
int multiresModifier_reshapeFromDM (Scene * scene, MultiresModifierData * mmd, Object * ob, DerivedMesh * srcdm)
Definition at line 396 of file multires.c.
References get_multires_dm(), DerivedMesh::getNumVerts, DerivedMesh::getVertArray, MULTIRES_COORDS_MODIFIED, multires_dm_mark_as_modified(), multires_force_update(), multires_mvert_to_ss(), and DerivedMesh::release.
Referenced by multiresModifier_reshape(), and multiresModifier_reshapeFromDeformMod().
void multiresModifier_scale_disp (Scene * scene, Object * ob)
Definition at line 2144 of file multires.c.
References multires_apply_smat(), and object_scale_to_mat3().
Referenced by apply_objects_internal().
void multiresModifier_set_levels_from_disps (MultiresModifierData * mmd, Object * ob)
Definition at line 493 of file multires.c.
References BMEditMesh::bm, CD_MDISPS, CustomData_get_layer(), Object::data, Mesh::edit_btmesh, get_levels_from_disps(), Mesh::ldata, BMesh::ldata, MultiresModifierData::lvl, MIN2, MultiresModifierData::renderlvl, MultiresModifierData::sculptlvl, and MultiresModifierData::totlvl.
Referenced by ED_object_modifier_add(), and test_object_modifiers().
void multiresModifier_subdivide (MultiresModifierData * mmd, Object * ob, int updateblock, int simple)
Definition at line 909 of file multires.c.
References multires_subdivide(), and MultiresModifierData::totlvl.
Referenced by multires_load_old(), and multires_subdivide_exec().
void old_mdisps_bilinear (float out[3], float(*) disps[3], const int st, float u, float v)
Definition at line 1387 of file multires.c.
References add_v3_v3v3(), isnan(), mul_v3_fl(), and mul_v3_v3fl().
Referenced by bm_loop_interp_mdisps(), and old_mdisps_convert().
static void old_mdisps_convert (MFace * mface, MDisps * mdisp) [static]
Definition at line 1441 of file multires.c.
References MDisps::disps, MDisps::level, log(), M_LN2, MEM_callocN(), MEM_freeN(), multires_grid_tot, multires_side_tot, old_mdisps_bilinear(), old_mdisps_rotate(), sqrt(), SWAP, MDisps::totdisp, and MFace::v4.
Referenced by multires_load_old_250().
static void old_mdisps_rotate (int S, int UNUSEDnewside, int oldside, int x, int y, float * u, float * v) [static]
Definition at line 1431 of file multires.c.
Referenced by old_mdisps_convert().
static DerivedMesh* subsurf_dm_create_local (Object * ob, DerivedMesh * dm, int lvl, int simple, int optimal, int plain_uv) [static]
Definition at line 684 of file multires.c.
References eSubsurfModifierFlag_ControlEdges, eSubsurfModifierFlag_SubsurfUv, SubsurfModifierData::flags, SubsurfModifierData::levels, ME_SIMPLE_SUBSURF, Object::mode, NULL, OB_MODE_EDIT, SubsurfModifierData::renderLevels, SubsurfModifierData::subdivType, and subsurf_make_derived_from_derived().
Referenced by multires_apply_smat(), multires_dm_create_from_derived(), multires_modifier_update_mdisps(), multires_set_space(), multires_subdivide(), and multiresModifier_base_apply().
static float v3_dist_from_plane (float v[3], float center[3], float no[3]) [static]
Definition at line 703 of file multires.c.
References dot_v3v3(), and sub_v3_v3v3().
Referenced by multiresModifier_base_apply().
Variable Documentation
const int multires_grid_tot[] = {0, 4, 9, 25, 81, 289, 1089, 4225, 16641, 66049, 263169, 1050625, 4198401, 16785409} [static]
Definition at line 67 of file multires.c.
Referenced by multires_del_higher(), multires_reallocate_mdisps(), multires_set_tot_mdisps(), and old_mdisps_convert().
const int multires_max_levels = 13 [static]
Definition at line 66 of file multires.c.
Referenced by multires_subdivide().
const int multires_side_tot[] = {0, 2, 3, 5, 9, 17, 33, 65, 129, 257, 513, 1025, 2049, 4097} [static]
Definition at line 68 of file multires.c.
Referenced by multires_apply_smat(), multires_del_higher(), multires_load_old_dm(), multires_set_space(), multiresModifier_disp_run(), and old_mdisps_convert().