Blender: textview.h File Reference
textview.h File Reference
info space
Classes
struct TextViewContext
Defines
#define TVC_LINE_FG (1<<0)
#define TVC_LINE_BG (1<<1)
Typedefs
typedef struct TextViewContext TextViewContext
Functions
int textview_draw (struct TextViewContext *tvc, int draw, int mval[2], void **mouse_pick, int *pos_pick)
Detailed Description
Definition in file textview.h.
Define Documentation
#define TVC_LINE_BG (1<<1)
Definition at line 60 of file textview.h.
Referenced by report_textview_line_color(), and textview_draw().
#define TVC_LINE_FG (1<<0)
Definition at line 59 of file textview.h.
Referenced by console_textview_line_color(), report_textview_line_color(), and textview_draw().
Typedef Documentation
typedef struct TextViewContext TextViewContext
Function Documentation
int textview_draw (struct TextViewContext * tvc, int draw, int mval[2], void ** mouse_pick, int * pos_pick)
Definition at line 222 of file textview.c.
References assert, TextViewContext::begin, BLF_fixed_width(), blf_mono_font, CLAMP(), CONSOLE_DRAW_MARGIN, CONSOLE_DRAW_SCROLL, console_draw_string(), console_font_begin(), TextViewContext::console_width, ConsoleDrawContext::console_width, TextViewContext::cwidth, ConsoleDrawContext::cwidth, ConsoleDrawContext::draw, TextViewContext::end, TextViewContext::iter, TextViewContext::iter_index, ConsoleDrawContext::lheight, TextViewContext::lheight, TextViewContext::line_color, TextViewContext::line_get, mono, ConsoleDrawContext::mval, NULL, ConsoleDrawContext::pos_pick, ConsoleDrawContext::sel, TextViewContext::sel_end, TextViewContext::sel_start, TextViewContext::step, TVC_LINE_BG, TVC_LINE_FG, ConsoleDrawContext::winx, TextViewContext::winx, ConsoleDrawContext::xy, TextViewContext::ymax, ConsoleDrawContext::ymax, ConsoleDrawContext::ymin, and TextViewContext::ymin.
Referenced by console_textview_main__internal(), and info_textview_main__internal().