Blender: btSoftBodyHelpers Struct Reference
btSoftBodyHelpers Struct Reference
#include <btSoftBodyHelpers.h>
Static Public Member Functions
static void Draw (btSoftBody *psb, btIDebugDraw *idraw, int drawflags=fDrawFlags::Std)
static void DrawInfos (btSoftBody *psb, btIDebugDraw *idraw, bool masses, bool areas, bool stress)
static void DrawNodeTree (btSoftBody *psb, btIDebugDraw *idraw, int mindepth=0, int maxdepth=-1)
static void DrawFaceTree (btSoftBody *psb, btIDebugDraw *idraw, int mindepth=0, int maxdepth=-1)
static void DrawClusterTree (btSoftBody *psb, btIDebugDraw *idraw, int mindepth=0, int maxdepth=-1)
static void DrawFrame (btSoftBody *psb, btIDebugDraw *idraw)
static btSoftBody * CreateRope (btSoftBodyWorldInfo &worldInfo, const btVector3 &from, const btVector3 &to, int res, int fixeds)
static btSoftBody * CreatePatch (btSoftBodyWorldInfo &worldInfo, const btVector3 &corner00, const btVector3 &corner10, const btVector3 &corner01, const btVector3 &corner11, int resx, int resy, int fixeds, bool gendiags)
static btSoftBody * CreatePatchUV (btSoftBodyWorldInfo &worldInfo, const btVector3 &corner00, const btVector3 &corner10, const btVector3 &corner01, const btVector3 &corner11, int resx, int resy, int fixeds, bool gendiags, float *tex_coords=0)
static float CalculateUV (int resx, int resy, int ix, int iy, int id)
static btSoftBody * CreateEllipsoid (btSoftBodyWorldInfo &worldInfo, const btVector3 &center, const btVector3 &radius, int res)
static btSoftBody * CreateFromTriMesh (btSoftBodyWorldInfo &worldInfo, const btScalar *vertices, const int *triangles, int ntriangles, bool randomizeConstraints=true)
static btSoftBody * CreateFromConvexHull (btSoftBodyWorldInfo &worldInfo, const btVector3 *vertices, int nvertices, bool randomizeConstraints=true)
static btSoftBody * CreateFromTetGenData (btSoftBodyWorldInfo &worldInfo, const char *ele, const char *face, const char *node, bool bfacelinks, bool btetralinks, bool bfacesfromtetras)
Detailed Description
Definition at line 45 of file btSoftBodyHelpers.h.
Member Function Documentation
float btSoftBodyHelpers::CalculateUV (int resx, int resy, int ix, int iy, int id) [static]
Definition at line 746 of file btSoftBodyHelpers.cpp.
Referenced by CreatePatchUV().
btSoftBody * btSoftBodyHelpers::CreateEllipsoid (btSoftBodyWorldInfo & worldInfo, const btVector3 & center, const btVector3 & radius, int res) [static]
Definition at line 790 of file btSoftBodyHelpers.cpp.
References btCos(), btSin(), btSqrt(), CreateFromConvexHull(), i, p, btAlignedObjectArray< T >::resize(), SIMD_PI, and btAlignedObjectArray< T >::size().
btSoftBody * btSoftBodyHelpers::CreateFromConvexHull (btSoftBodyWorldInfo & worldInfo, const btVector3 * vertices, int nvertices, bool randomizeConstraints = true) [static]
Definition at line 869 of file btSoftBodyHelpers.cpp.
References btSoftBody::appendFace(), btSoftBody::appendLink(), HullLibrary::CreateConvexHull(), i, HullResult::m_Indices, HullResult::m_OutputVertices, HullDesc::mMaxVertices, HullResult::mNumFaces, HullResult::mNumOutputVertices, QF_TRIANGLES, btSoftBody::randomizeConstraints(), and HullLibrary::ReleaseResult().
Referenced by CreateEllipsoid().
btSoftBody * btSoftBodyHelpers::CreateFromTetGenData (btSoftBodyWorldInfo & worldInfo, const char * ele, const char * face, const char * node, bool bfacelinks, bool btetralinks, bool bfacesfromtetras) [static]
Definition at line 920 of file btSoftBodyHelpers.cpp.
References btSoftBody::appendFace(), btSoftBody::appendLink(), btSoftBody::appendTetra(), i, btSoftBody::m_faces, btSoftBody::m_links, btSoftBody::m_nodes, btSoftBody::m_tetras, nextLine(), btAlignedObjectArray< T >::resize(), and btAlignedObjectArray< T >::size().
btSoftBody * btSoftBodyHelpers::CreateFromTriMesh (btSoftBodyWorldInfo & worldInfo, const btScalar * vertices, const int * triangles, int ntriangles, bool randomizeConstraints = true) [static]
Definition at line 822 of file btSoftBodyHelpers.cpp.
References btSoftBody::appendFace(), btSoftBody::appendLink(), btMax(), i, IDX, btSoftBody::randomizeConstraints(), btAlignedObjectArray< T >::resize(), and btAlignedObjectArray< T >::size().
btSoftBody * btSoftBodyHelpers::CreatePatch (btSoftBodyWorldInfo & worldInfo, const btVector3 & corner00, const btVector3 & corner10, const btVector3 & corner01, const btVector3 & corner11, int resx, int resy, int fixeds, bool gendiags) [static]
Definition at line 507 of file btSoftBodyHelpers.cpp.
References btSoftBody::appendFace(), btSoftBody::appendLink(), IDX, lerp(), and btSoftBody::setMass().
btSoftBody * btSoftBodyHelpers::CreatePatchUV (btSoftBodyWorldInfo & worldInfo, const btVector3 & corner00, const btVector3 & corner10, const btVector3 & corner01, const btVector3 & corner11, int resx, int resy, int fixeds, bool gendiags, float * tex_coords = 0) [static]
Definition at line 584 of file btSoftBodyHelpers.cpp.
References btSoftBody::appendFace(), btSoftBody::appendLink(), CalculateUV(), IDX, lerp(), and btSoftBody::setMass().
btSoftBody * btSoftBodyHelpers::CreateRope (btSoftBodyWorldInfo & worldInfo, const btVector3 & from, const btVector3 & to, int res, int fixeds) [static]
Definition at line 475 of file btSoftBodyHelpers.cpp.
References btSoftBody::appendLink(), i, lerp(), and btSoftBody::setMass().
void btSoftBodyHelpers::Draw (btSoftBody * psb, btIDebugDraw * idraw, int drawflags = fDrawFlags::Std) [static]
Definition at line 157 of file btSoftBodyHelpers.cpp.
References add(), fDrawFlags::Anchors, btSoftBody::Joint::eType::Angular, average(), btCross(), btDot(), fDrawFlags::Clusters, fDrawFlags::ClusterTree, fDrawFlags::Contacts, HullLibrary::CreateConvexHull(), btSoftBody::fMaterial::DebugDraw, btIDebugDraw::draw3dText(), DrawClusterTree(), DrawFaceTree(), btIDebugDraw::drawLine(), DrawNodeTree(), btIDebugDraw::drawTriangle(), drawVertex(), fDrawFlags::Faces, fDrawFlags::FaceTree, i, fDrawFlags::Joints, btSoftBody::Joint::eType::Linear, fDrawFlags::Links, btSoftBody::m_anchors, btSoftBody::Cluster::m_av, btSoftBody::Joint::m_bodies, btSoftBody::Anchor::m_body, btSoftBody::m_clusters, btSoftBody::Cluster::m_com, btSoftBody::Note::m_coords, btSoftBody::RContact::m_cti, btSoftBody::m_faces, btSoftBody::Node::m_im, btSoftBody::m_joints, btSoftBody::m_links, btSoftBody::Anchor::m_local, btSoftBody::Cluster::m_lv, btSoftBody::Feature::m_material, btSoftBody::Tetra::m_n, btSoftBody::Face::m_n, btSoftBody::Node::m_n, btSoftBody::Link::m_n, btSoftBody::Anchor::m_node, btSoftBody::RContact::m_node, btSoftBody::Note::m_nodes, btSoftBody::m_nodes, btSoftBody::Cluster::m_nodes, btSoftBody::m_notes, btSoftBody::Note::m_offset, btSoftBody::Note::m_rank, btSoftBody::m_rcontacts, btSoftBody::Joint::m_refs, btSoftBody::m_tetras, btSoftBody::Note::m_text, btSoftBody::Node::m_x, mul(), fDrawFlags::Nodes, fDrawFlags::NodeTree, fDrawFlags::Normals, fDrawFlags::Notes, p, QF_TRIANGLES, HullLibrary::ReleaseResult(), btAlignedObjectArray< T >::resize(), btAlignedObjectArray< T >::size(), fDrawFlags::Tetras, and btSoftBody::Joint::Type().
Referenced by btSoftRigidDynamicsWorld::debugDrawWorld().
void btSoftBodyHelpers::DrawClusterTree (btSoftBody * psb, btIDebugDraw * idraw, int mindepth = 0, int maxdepth = -1) [static]
Definition at line 442 of file btSoftBodyHelpers.cpp.
References drawTree(), btSoftBody::m_cdbvt, and btDbvt::m_root.
Referenced by btSoftRigidDynamicsWorld::debugDrawWorld(), and Draw().
void btSoftBodyHelpers::DrawFaceTree (btSoftBody * psb, btIDebugDraw * idraw, int mindepth = 0, int maxdepth = -1) [static]
Definition at line 433 of file btSoftBodyHelpers.cpp.
References drawTree(), btSoftBody::m_fdbvt, and btDbvt::m_root.
Referenced by btSoftRigidDynamicsWorld::debugDrawWorld(), and Draw().
void btSoftBodyHelpers::DrawFrame (btSoftBody * psb, btIDebugDraw * idraw) [static]
Definition at line 451 of file btSoftBodyHelpers.cpp.
References btIDebugDraw::drawLine(), drawVertex(), i, and btSoftBody::m_pose.
Referenced by btSoftRigidDynamicsWorld::debugDrawWorld().
void btSoftBodyHelpers::DrawInfos (btSoftBody * psb, btIDebugDraw * idraw, bool masses, bool areas, bool stress) [static]
Definition at line 398 of file btSoftBodyHelpers.cpp.
References btIDebugDraw::draw3dText(), i, btSoftBody::Node::m_area, btSoftBody::Node::m_im, btSoftBody::m_nodes, btSoftBody::Node::m_x, and btAlignedObjectArray< T >::size().
void btSoftBodyHelpers::DrawNodeTree (btSoftBody * psb, btIDebugDraw * idraw, int mindepth = 0, int maxdepth = -1) [static]
Definition at line 424 of file btSoftBodyHelpers.cpp.
References drawTree(), btSoftBody::m_ndbvt, and btDbvt::m_root.
Referenced by btSoftRigidDynamicsWorld::debugDrawWorld(), and Draw().
The documentation for this struct was generated from the following files:
btSoftBodyHelpers.h
btSoftBodyHelpers.cpp