Blender: KX_GameActuator Class Reference
KX_GameActuator Class Reference
#include <KX_GameActuator.h>
Public Types
enum KX_GameActuatorMode {
KX_GAME_NODEF = 0, KX_GAME_LOAD, KX_GAME_START, KX_GAME_RESTART,
KX_GAME_QUIT, KX_GAME_SAVECFG, KX_GAME_LOADCFG, KX_GAME_MAX
}
Public Member Functions
KX_GameActuator (SCA_IObject *gameobj, int mode, const STR_String &filename, const STR_String &loadinganimationname, SCA_IScene *scene, KX_KetsjiEngine *ketsjiEngine)
virtual ~KX_GameActuator ()
virtual CValue * GetReplica ()
virtual bool Update ()
virtual void Replace_IScene (SCA_IScene *val)
Protected Attributes
int m_mode
bool m_restart
STR_String m_filename
STR_String m_loadinganimationname
class SCA_IScene * m_scene
class KX_KetsjiEngine * m_ketsjiengine
Detailed Description
Definition at line 41 of file KX_GameActuator.h.
Member Enumeration Documentation
enum KX_GameActuator::KX_GameActuatorMode
Enumerator:
KX_GAME_NODEF
KX_GAME_LOAD
KX_GAME_START
KX_GAME_RESTART
KX_GAME_QUIT
KX_GAME_SAVECFG
KX_GAME_LOADCFG
KX_GAME_MAX
Definition at line 53 of file KX_GameActuator.h.
Constructor & Destructor Documentation
KX_GameActuator::KX_GameActuator (SCA_IObject * gameobj, int mode, const STR_String & filename, const STR_String & loadinganimationname, SCA_IScene * scene, KX_KetsjiEngine * ketsjiEngine)
Definition at line 52 of file KX_GameActuator.cpp.
References m_filename, m_ketsjiengine, m_loadinganimationname, m_mode, and m_scene.
Referenced by GetReplica().
KX_GameActuator::~KX_GameActuator () [virtual]
Definition at line 69 of file KX_GameActuator.cpp.
Member Function Documentation
CValue * KX_GameActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 76 of file KX_GameActuator.cpp.
References KX_GameActuator(), and SCA_IActuator::ProcessReplica().
virtual void KX_GameActuator::Replace_IScene (SCA_IScene * val) [inline, virtual]
Reimplemented from SCA_ILogicBrick.
Definition at line 78 of file KX_GameActuator.h.
References m_scene.
bool KX_GameActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 86 of file KX_GameActuator.cpp.
References SCA_IScene::AddDebugProperty(), fseek, ftell, SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), KX_EXIT_REQUEST_QUIT_GAME, KX_EXIT_REQUEST_RESTART_GAME, KX_EXIT_REQUEST_START_OTHER_GAME, KX_GAME_LOAD, KX_GAME_LOADCFG, KX_GAME_QUIT, KX_GAME_RESTART, KX_GAME_SAVECFG, KX_GAME_START, m_filename, m_ketsjiengine, m_mode, m_scene, NULL, SCA_IActuator::RemoveAllEvents(), KX_KetsjiEngine::RequestExit(), and KX_KetsjiEngine::SetNameNextGame().
Member Data Documentation
STR_String KX_GameActuator::m_filename [protected]
Definition at line 47 of file KX_GameActuator.h.
Referenced by KX_GameActuator(), and Update().
class KX_KetsjiEngine* KX_GameActuator::m_ketsjiengine [protected]
Definition at line 50 of file KX_GameActuator.h.
Referenced by KX_GameActuator(), and Update().
STR_String KX_GameActuator::m_loadinganimationname [protected]
Definition at line 48 of file KX_GameActuator.h.
Referenced by KX_GameActuator().
int KX_GameActuator::m_mode [protected]
Definition at line 45 of file KX_GameActuator.h.
Referenced by KX_GameActuator(), and Update().
bool KX_GameActuator::m_restart [protected]
Definition at line 46 of file KX_GameActuator.h.
class SCA_IScene* KX_GameActuator::m_scene [protected]
Definition at line 49 of file KX_GameActuator.h.
Referenced by KX_GameActuator(), Replace_IScene(), and Update().
The documentation for this class was generated from the following files:
KX_GameActuator.h
KX_GameActuator.cpp