Blender: uvedit_intern.h File Reference
uvedit_intern.h File Reference
Classes
struct NearestHit
struct StitchPreviewer
Defines
#define TF_PIN_MASK(id) (TF_PIN1 << id)
#define TF_SEL_MASK(id) (TF_SEL1 << id)
Typedefs
typedef struct NearestHit NearestHit
typedef struct StitchPreviewer StitchPreviewer
Functions
int uvedit_face_visible_nolocal (struct Scene *scene, struct BMFace *efa)
void uv_center (float uv[][2], float cent[2], int quad)
float uv_area (float uv[][2], int quad)
void uv_copy_aspect (float uv_orig[][2], float uv[][2], float aspx, float aspy)
float poly_uv_area (float uv[][2], int len)
void poly_copy_aspect (float uv_orig[][2], float uv[][2], float aspx, float aspy, int len)
void poly_uv_center (struct BMEditMesh *em, struct BMFace *f, float cent[2])
void uv_find_nearest_vert (struct Scene *scene, struct Image *ima, struct BMEditMesh *em, float co[2], float penalty[2], struct NearestHit *hit)
void uv_find_nearest_edge (struct Scene *scene, struct Image *ima, struct BMEditMesh *em, float co[2], struct NearestHit *hit)
struct UvElement * ED_uv_element_get (struct UvElementMap *map, struct BMFace *efa, struct BMLoop *l)
void uvedit_live_unwrap_update (struct SpaceImage *sima, struct Scene *scene, struct Object *obedit)
StitchPreviewer * uv_get_stitch_previewer (void)
void UV_OT_average_islands_scale (struct wmOperatorType *ot)
void UV_OT_cube_project (struct wmOperatorType *ot)
void UV_OT_cylinder_project (struct wmOperatorType *ot)
void UV_OT_from_view (struct wmOperatorType *ot)
void UV_OT_minimize_stretch (struct wmOperatorType *ot)
void UV_OT_pack_islands (struct wmOperatorType *ot)
void UV_OT_reset (struct wmOperatorType *ot)
void UV_OT_sphere_project (struct wmOperatorType *ot)
void UV_OT_unwrap (struct wmOperatorType *ot)
void UV_OT_stitch (struct wmOperatorType *ot)
Detailed Description
Definition in file uvedit_intern.h.
Define Documentation
#define TF_PIN_MASK (id) (TF_PIN1 << id)
Definition at line 50 of file uvedit_intern.h.
#define TF_SEL_MASK (id) (TF_SEL1 << id)
Definition at line 51 of file uvedit_intern.h.
Typedef Documentation
typedef struct NearestHit NearestHit
typedef struct StitchPreviewer StitchPreviewer
Function Documentation
struct UvElement* ED_uv_element_get (struct UvElementMap * map, struct BMFace * efa, struct BMLoop * l) [read]
Definition at line 896 of file uvedit_ops.c.
References BM_elem_index_get, UvElement::face, UvElement::next, NULL, BMLoop::v, and UvElementMap::vert.
Referenced by stitch_init(), stitch_process_data(), stitch_select(), uv_element_offset_from_face_get(), and uv_sculpt_stroke_init().
void poly_copy_aspect (float uv_orig[][2], float uv[][2], float aspx, float aspy, int len)
Definition at line 575 of file uvedit_ops.c.
References i, and len().
Referenced by draw_uvs_stretch().
float poly_uv_area (float uv[][2], int len)
Definition at line 562 of file uvedit_ops.c.
References area_tri_v2().
Referenced by draw_uvs_stretch().
void poly_uv_center (struct BMEditMesh * em, struct BMFace * f, float cent[2])
Definition at line 525 of file uvedit_ops.c.
References add_v2_v2(), BMEditMesh::bm, BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, BMFace::len, mul_v2_fl(), MLoopUV::uv, and zero_v2().
Referenced by border_select_exec(), and draw_uvs().
float uv_area (float uv[][2], int quad)
Definition at line 554 of file uvedit_ops.c.
References area_tri_v2().
void uv_center (float uv[][2], float cent[2], int quad)
Definition at line 542 of file uvedit_ops.c.
void uv_copy_aspect (float uv_orig[][2], float uv[][2], float aspx, float aspy)
void uv_find_nearest_edge (struct Scene * scene, struct Image * ima, struct BMEditMesh * em, float co[2], struct NearestHit * hit)
Definition at line 666 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, dist_to_line_segment_v2(), NearestHit::efa, BMFace::head, BMLoop::head, i, NearestHit::l, BMesh::ldata, NearestHit::lindex, NearestHit::luv, BMLoop::next, NearestHit::nextl, NearestHit::nextluv, BMesh::pdata, NearestHit::tf, MLoopUV::uv, uvedit_face_visible_test(), BMLoop::v, NearestHit::vert1, and NearestHit::vert2.
Referenced by find_nearest_uv_face(), mouse_select(), and uv_find_nearest_vert().
void uv_find_nearest_vert (struct Scene * scene, struct Image * ima, struct BMEditMesh * em, float co[2], float penalty[2], struct NearestHit * hit)
Definition at line 800 of file uvedit_ops.c.
References BMEditMesh::bm, BM_elem_index_get, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, NearestHit::efa, fabs(), BMFace::head, BMLoop::head, i, NearestHit::l, BMesh::ldata, BMFace::len, NearestHit::lindex, NearestHit::luv, nearest_uv_between(), BMLoop::next, NearestHit::nextl, NearestHit::nextluv, NULL, BMesh::pdata, NearestHit::tf, MLoopUV::uv, uv_find_nearest_edge(), uvedit_face_visible_test(), uvedit_uv_select_test(), BMLoop::v, and NearestHit::vert1.
Referenced by mouse_select(), select_linked_internal(), stitch_select(), and uv_sculpt_stroke_init().
StitchPreviewer* uv_get_stitch_previewer (void)
Definition at line 217 of file uvedit_smart_stitch.c.
References _stitch_preview.
Referenced by draw_uvs(), stitch_setup_face_preview_for_uv_group(), and stitch_validate_stichability().
void UV_OT_average_islands_scale (struct wmOperatorType * ot)
Definition at line 782 of file uvedit_unwrap_ops.c.
References average_islands_scale_exec(), ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_uvedit().
void UV_OT_cube_project (struct wmOperatorType * ot)
Definition at line 1610 of file uvedit_unwrap_ops.c.
References cube_project_exec(), ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, and uv_map_clip_correct_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_cylinder_project (struct wmOperatorType * ot)
Definition at line 1532 of file uvedit_unwrap_ops.c.
References cylinder_project_exec(), ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, uv_map_clip_correct_properties(), and uv_transform_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_from_view (struct wmOperatorType * ot)
Definition at line 1319 of file uvedit_unwrap_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, uv_from_view_exec(), uv_from_view_poll(), and uv_map_clip_correct_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_minimize_stretch (struct wmOperatorType * ot)
Definition at line 689 of file uvedit_unwrap_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, minimize_stretch_cancel(), minimize_stretch_exec(), minimize_stretch_invoke(), minimize_stretch_modal(), wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_factor(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
void UV_OT_pack_islands (struct wmOperatorType * ot)
Definition at line 742 of file uvedit_unwrap_ops.c.
References ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, pack_islands_exec(), wmOperatorType::poll, RNA_def_float_factor(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
void UV_OT_reset (struct wmOperatorType * ot)
Definition at line 1358 of file uvedit_unwrap_ops.c.
References ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and reset_exec().
Referenced by ED_operatortypes_uvedit().
void UV_OT_sphere_project (struct wmOperatorType * ot)
Definition at line 1459 of file uvedit_unwrap_ops.c.
References ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sphere_project_exec(), uv_map_clip_correct_properties(), and uv_transform_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_stitch (struct wmOperatorType * ot)
Definition at line 1460 of file uvedit_smart_stitch.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_HIDDEN, RNA_def_boolean(), RNA_def_collection_runtime(), RNA_def_float(), RNA_def_int(), RNA_def_property_flag(), RNA_SelectedUvElement, wmOperatorType::srna, stitch_cancel(), stitch_exec(), stitch_invoke(), and stitch_modal().
Referenced by ED_operatortypes_uvedit().
void UV_OT_unwrap (struct wmOperatorType * ot)
Definition at line 1201 of file uvedit_unwrap_ops.c.
References wmOperatorType::description, ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), RNA_def_int(), wmOperatorType::srna, and unwrap_exec().
Referenced by ED_operatortypes_uvedit().
int uvedit_face_visible_nolocal (struct Scene * scene, struct BMFace * efa)
Definition at line 286 of file uvedit_ops.c.
References BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, Scene::toolsettings, ToolSettings::uv_flag, and UV_SYNC_SELECTION.
Referenced by uvedit_face_visible_test().
void uvedit_live_unwrap_update (struct SpaceImage * sima, struct Scene * scene, struct Object * obedit)
Definition at line 515 of file uvedit_ops.c.
References ED_uvedit_live_unwrap_begin(), ED_uvedit_live_unwrap_end(), ED_uvedit_live_unwrap_re_solve(), SpaceImage::flag, and SI_LIVE_UNWRAP.
Referenced by snap_selection_exec(), stitch_exit(), and weld_align_uv().