Blender: info_intern.h File Reference
info_intern.h File Reference
info space
Functions
void FILE_OT_pack_all (struct wmOperatorType *ot)
void FILE_OT_unpack_all (struct wmOperatorType *ot)
void FILE_OT_make_paths_relative (struct wmOperatorType *ot)
void FILE_OT_make_paths_absolute (struct wmOperatorType *ot)
void FILE_OT_report_missing_files (struct wmOperatorType *ot)
void FILE_OT_find_missing_files (struct wmOperatorType *ot)
void INFO_OT_reports_display_update (struct wmOperatorType *ot)
void * info_text_pick (struct SpaceInfo *sinfo, struct ARegion *ar, ReportList *reports, int mouse_y)
int info_textview_height (struct SpaceInfo *sinfo, struct ARegion *ar, struct ReportList *reports)
void info_textview_main (struct SpaceInfo *sinfo, struct ARegion *ar, struct ReportList *reports)
int info_report_mask (struct SpaceInfo *sinfo)
void INFO_OT_select_pick (struct wmOperatorType *ot)
void INFO_OT_select_all_toggle (struct wmOperatorType *ot)
void INFO_OT_select_border (struct wmOperatorType *ot)
void INFO_OT_report_replay (struct wmOperatorType *ot)
void INFO_OT_report_delete (struct wmOperatorType *ot)
void INFO_OT_report_copy (struct wmOperatorType *ot)
Detailed Description
Definition in file info_intern.h.
Function Documentation
void FILE_OT_find_missing_files (struct wmOperatorType * ot)
Definition at line 298 of file info_ops.c.
References wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_OPENFILE, FILE_SPECIAL, find_missing_files_exec(), find_missing_files_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, WM_FILESEL_FILEPATH, and WM_operator_properties_filesel().
Referenced by info_operatortypes().
void FILE_OT_make_paths_absolute (struct wmOperatorType * ot)
Definition at line 241 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, make_paths_absolute_exec(), wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by info_operatortypes().
void FILE_OT_make_paths_relative (struct wmOperatorType * ot)
Definition at line 209 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, make_paths_relative_exec(), wmOperatorType::name, OPTYPE_REGISTER, and OPTYPE_UNDO.
Referenced by info_operatortypes().
void FILE_OT_pack_all (struct wmOperatorType * ot)
Definition at line 105 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, pack_all_exec(), and pack_all_invoke().
Referenced by info_operatortypes().
void FILE_OT_report_missing_files (struct wmOperatorType * ot)
Definition at line 266 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, and report_missing_files_exec().
Referenced by info_operatortypes().
void FILE_OT_unpack_all (struct wmOperatorType * ot)
Definition at line 173 of file info_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, PF_USE_LOCAL, RNA_def_enum(), wmOperatorType::srna, unpack_all_exec(), and unpack_all_invoke().
Referenced by info_operatortypes().
void INFO_OT_report_copy (struct wmOperatorType * ot)
Definition at line 399 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_copy_exec().
Referenced by info_operatortypes().
void INFO_OT_report_delete (struct wmOperatorType * ot)
Definition at line 354 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_delete_exec().
Referenced by info_operatortypes().
void INFO_OT_report_replay (struct wmOperatorType * ot)
Definition at line 95 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_replay_exec().
Referenced by info_operatortypes().
void INFO_OT_reports_display_update (struct wmOperatorType * ot)
Definition at line 412 of file info_ops.c.
References wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, and update_reports_display_invoke().
Referenced by info_operatortypes().
void INFO_OT_select_all_toggle (struct wmOperatorType * ot)
Definition at line 199 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, and report_select_all_toggle_exec().
Referenced by info_operatortypes().
void INFO_OT_select_border (struct wmOperatorType * ot)
Definition at line 303 of file info_report.c.
References borderselect_exec(), wmOperatorType::cancel, wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, wmOperatorType::poll, TRUE, WM_border_select_cancel(), WM_border_select_invoke(), WM_border_select_modal(), and WM_operator_properties_gesture_border().
Referenced by info_operatortypes().
void INFO_OT_select_pick (struct wmOperatorType * ot)
Definition at line 145 of file info_report.c.
References wmOperatorType::description, ED_operator_info_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), select_report_pick_exec(), select_report_pick_invoke(), and wmOperatorType::srna.
Referenced by info_operatortypes().
int info_report_mask (struct SpaceInfo * sinfo)
Referenced by borderselect_exec(), report_copy_exec(), report_delete_exec(), report_select_all_toggle_exec(), and report_textview_skip__internal().
void* info_text_pick (struct SpaceInfo * sinfo, struct ARegion * ar, ReportList * reports, int mouse_y)
Definition at line 282 of file info_draw.c.
References info_textview_main__internal(), and NULL.
Referenced by borderselect_exec(), and select_report_pick_invoke().
int info_textview_height (struct SpaceInfo * sinfo, struct ARegion * ar, struct ReportList * reports)
Definition at line 295 of file info_draw.c.
References info_textview_main__internal(), and NULL.
Referenced by info_textview_update_rect().
void info_textview_main (struct SpaceInfo * sinfo, struct ARegion * ar, struct ReportList * reports)
Definition at line 301 of file info_draw.c.
References info_textview_main__internal(), and NULL.
Referenced by info_main_area_draw().