Blender: MEM_guardedalloc.h File Reference
MEM_guardedalloc.h File Reference
Guarded memory (de)allocation
Read Guarded memory(de)allocation.
#include <stdio.h>
#include "MEM_sys_types.h"
Defines
#define WARN_UNUSED
Functions
size_t MEM_allocN_len (void *vmemh) WARN_UNUSED
short MEM_freeN (void *vmemh)
short MEM_testN (void *vmemh)
void * MEM_dupallocN (void *vmemh) WARN_UNUSED
void * MEM_reallocN (void *vmemh, size_t len) WARN_UNUSED
void * MEM_callocN (size_t len, const char *str) WARN_UNUSED
void * MEM_mallocN (size_t len, const char *str) WARN_UNUSED
void * MEM_mapallocN (size_t len, const char *str) WARN_UNUSED
void MEM_printmemlist_pydict (void)
void MEM_printmemlist (void)
void MEM_callbackmemlist (void(*func)(void *))
void MEM_printmemlist_stats (void)
void MEM_set_error_callback (void(*func)(const char *))
int MEM_check_memory_integrity (void)
void MEM_set_lock_callback (void(*lock)(void), void(*unlock)(void))
void MEM_set_memory_debug (void)
uintptr_t MEM_get_memory_in_use (void)
uintptr_t MEM_get_mapped_memory_in_use (void)
int MEM_get_memory_blocks_in_use (void)
void MEM_reset_peak_memory (void)
uintptr_t MEM_get_peak_memory (void) WARN_UNUSED
const char * MEM_name_ptr (void *vmemh)
Detailed Description
Read Guarded memory(de)allocation.
Author:
Copyright (C) 2001 NaN Technologies B.V.
Definition in file MEM_guardedalloc.h.
Define Documentation
#define WARN_UNUSED
Definition at line 70 of file MEM_guardedalloc.h.
Function Documentation
size_t MEM_allocN_len (void * vmemh)
Returns the length of the allocated memory segment pointed at by vmemh. If the pointer was not previously allocated by this module, the result is undefined.
Definition at line 227 of file mallocn.c.
References MemHead::len.
Referenced by applyModifier(), BKE_ptcache_id_clear(), BKE_ptcache_id_time(), BKE_ptcache_update_info(), BLI_bvhtree_insert(), bpath_traverse_id(), copy_libblock(), dm_debug_info_layers(), IDP_WriteArray(), image_mem_size(), mesh_recalcTessellation(), nodeClearPreview(), reload_sequence_new_file(), test_pointer_array(), time_draw_cache(), write_pointcaches(), write_properties(), and write_scenes().
void MEM_callbackmemlist (void(*)(void *) func)
calls the function on all allocated memory blocks.
Definition at line 531 of file mallocn.c.
References localListBase::first, mem_lock_thread(), mem_unlock_thread(), MEMNEXT, and MemHead::next.
void* MEM_callocN (size_t len, const char * str)
Allocate a block of memory of size len, with tag name str. The memory is cleared. The name must be static, because only a pointer to it is stored !
Definition at line 332 of file mallocn.c.
References make_memhead_header(), mem_in_use, mem_lock_thread(), mem_unlock_thread(), NULL, print_error(), SIZET_ARG, and SIZET_FORMAT.
Referenced by _bm_select_history_store_notest(), actcon_get_tarmat(), action_groups_add_new(), action_new(), actionzone_invoke(), add_2nd_order_springs(), AnimationImporter::add_bone_fcurve(), add_bp_springlist(), add_collider_cache_object(), add_color_mapping(), add_colorband(), add_curve(), add_empty_ks_path_exec(), add_fmodifier(), add_in_range(), add_keyblock(), add_lattice(), add_marker_to_cfra_elem(), add_mesh_quad_diag_springs(), add_metaball_element(), add_mtex(), add_named_exec(), add_new_constraint_internal(), add_nla_soundstrip(), add_nlastrip(), add_nlatrack(), add_object_to_effectors(), add_orco_dm(), add_particles_to_effectors(), add_plugin_seq(), add_plugin_tex(), add_render_lamp(), add_scene(), add_shapekey_layers(), add_tex_mapping(), add_to_group_internal(), add_user_list(), add_verts_to_dgroups(), add_view3d_after(), addbranch(), addDepthPeel(), addMatrixSpace(), addnode(), addnormalsDispList(), addpsmainA(), addpsmainAstrand(), addSnapPoint(), addtovertices(), adduplicateflagNurb(), alloc_child_particles(), alloc_compbuf(), alloc_libblock_notest(), alloc_sequence(), ANIM_relative_keyingset_add_source(), animviz_get_object_motionpaths(), animviz_verify_motionpaths(), append_named_part_ex(), appendPolyLineVert(), applyModifier(), area_add_header_region(), area_add_window_regions(), area_azone_initialize(), area_join_init(), area_move_init(), area_split_init(), area_split_menu_init(), area_swap_init(), armature_deform_verts(), armature_extrude_exec(), armature_rebuild_pose(), armatureSelectedToGraph(), as_addvert(), assign_material(), assign_material_id(), autocomplete_begin(), autosmooth(), avi_fetchibuf(), AVI_is_avi(), AVI_open_movie(), bake_images(), bevels_to_filledpoly(), bezt_add_to_cfra_elem(), bezt_to_beztmaps(), bezt_to_cfraelem(), beztmap_to_data(), bezts_to_new_actkeyblock(), BIF_listTemplates(), BIF_menustringTransformOrientation(), BKE_add_effector_weights(), BKE_add_envmap(), BKE_add_ocean(), BKE_add_oceantex(), BKE_add_pointdensity(), BKE_add_voxeldata(), BKE_icon_getid(), BKE_id_add_animdata(), BKE_image_memorypack(), BKE_init_ocean_cache(), BKE_keyingset_add(), BKE_keyingset_add_path(), BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_validate_arrays(), BKE_nlastrip_validate_fcurves(), BKE_nlastrips_make_metas(), BKE_previewimg_create(), BKE_ptcache_add(), BKE_ptcache_id_time(), BKE_ptcache_ids_from_object(), BKE_report(), BKE_reportf(), BKE_text_to_curve(), BKE_tracking_add_track(), BKE_tracking_context_new(), BKE_tracking_distortion_copy(), BKE_tracking_distortion_create(), BKE_tracking_insert_marker(), BKE_tracking_join_tracks(), BKE_tracking_new_object(), BKE_tracking_reconstruction_context_new(), BKE_write_undo(), BLF_dir_add(), BLF_dir_get(), blf_font_new(), blf_font_new_from_mem(), blf_glyph_add(), blf_glyph_cache_new(), BLI_argsInit(), BLI_buildAdjacencyList(), BLI_bvhtree_new(), BLI_bvhtree_overlap(), BLI_create_worker(), BLI_dir_create_recursive(), BLI_dlrbTree_new(), BLI_dynlib_open(), BLI_dynstr_appendf(), BLI_dynstr_vappendf(), BLI_edgefill_ex(), BLI_edgehash_new(), BLI_file_ungzip_to_mem(), BLI_genericNodeN(), BLI_heap_new(), BLI_init_threads(), BLI_insert_work(), BLI_kdtree_find_n_nearest(), BLI_kdtree_find_nearest(), BLI_kdtree_new(), BLI_kdtree_range_search(), BLI_memarena_alloc(), BLI_memarena_new(), BLI_pbvh_gather_proxies(), BLI_pbvh_get_grid_updates(), BLI_pbvh_get_vertCos(), BLI_pbvh_new(), BLI_pbvh_node_add_proxy(), BLI_pbvh_search_gather(), BLI_rebuildAdjacencyListForNode(), BLI_smallhash_insert(), BLI_thread_queue_init(), BLO_blendhandle_get_previews(), blo_find_main(), blo_read_file_internal(), blo_split_main(), bm_corners_to_loops(), bm_edgesplit_validate_seams(), bm_loop_interp_mdisps(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), BM_mesh_create(), BM_mesh_normals_update(), BM_mesh_remap(), bm_to_mesh_vertex_map(), BMBVH_NewBVH(), BME_init_transdata(), BMEdit_Copy(), BMEdit_Create(), bmesh_vert_separate(), bmo_edgenet_fill_exec(), BMO_error_raise(), bmo_inset_exec(), bmo_similaredges_exec(), bmo_similarfaces_exec(), boid_new_rule(), boid_new_state(), boundbox_armature(), boundbox_displist(), boundbox_mesh(), BPY_context_member_get(), bpy_prop_callback_assign(), brush_add(), brush_edit_init(), brush_gen_radial_control_imbuf(), brush_gen_texture_cache(), brush_painter_new(), bsbNew(), build_mesh_leaf_node(), build_underline(), buildNavMesh(), buildNavMeshData(), buildPolygonsByDetailedMeshes(), buildRawVertIndicesData(), KX_NavMeshObject::BuildVertIndArrays(), button_activate_init(), buttons_context_compute(), buttons_context_register(), buttons_new(), buttons_texture_context_compute(), buttons_texture_user_node_add(), buttons_texture_user_property_add(), bvh_create_tree(), cache_occ_samples(), cache_strand_surface(), calc_curvepath(), calc_edge_stress(), calc_shapeKeys(), calc_solidify_normals(), calc_vertexnormals(), calculate_strandsurface_speedvectors(), calculateTransformCenter(), callocN(), callocT(), ccgdm_create_grids(), cdDM_create(), cdDM_getPBVH(), CDDM_merge_verts(), CDDM_tessfaces_to_faces(), cdf_create(), cdf_layer_add(), cdf_read_header(), chains_find_tips(), check_destination(), check_persistent(), clip_has_preview_region(), clip_has_properties_region(), clip_has_tools_region(), clip_new(), clip_rebuild_proxy_exec(), cloneArc(), cloth_add_spring(), cloth_build_springs(), cloth_bvh_objcollision(), cloth_calc_helper_forces(), cloth_from_mesh(), cloth_from_object(), colorband_table_RGBA(), columnselect_action_keys(), columnselect_graph_keys(), compress_deepshadowbuf(), compress_shadowbuf(), console_lb_add__internal(), console_lb_add_str__internal(), console_line_verify_length(), console_modal_select_invoke(), console_new(), constraints_make_evalob(), convertspline(), convolve(), copy_animedit_keys(), copy_dverts(), copy_pose(), copy_scene(), copy_single_file(), copymenu_properties(), crazyspace_build_sculpt(), crazyspace_get_mapped_editverts(), crazyspace_set_quats_editmesh(), create_bfmatrix(), create_dither_context(), create_lfvector(), create_old_vert_edge_map(), create_old_vert_face_map(), create_slide_marker_data(), create_vert_edge_map(), create_vert_poly_map(), createFacepa(), createSketch(), createSlideVerts(), createTransActionData(), createTransArmatureVerts(), createTransCurveVerts(), createTransEdge(), createTransEditVerts(), createTransLatticeVerts(), createTransMBallVerts(), createTransNlaData(), createTransNodeData(), createTransObject(), createTransParticleVerts(), createTransPose(), createTransSeqData(), createTransTexspace(), createTransTrackingCurvesData(), createTransTrackingTracksData(), createTransUVs(), CTX_create(), CTX_data_id_list_add(), CTX_data_list_add(), CTX_store_add(), CTX_store_add_all(), curve_to_displist(), curve_to_key(), curvemap_insert(), curvemap_make_table(), curvemap_reset(), curvemapping_add(), curvemapping_table_RGBA(), customData_add_layer__internal(), CustomData_bmesh_interp(), CustomData_external_add(), CustomData_interp(), customData_resize(), cutEdges(), AnimationExporter::dae_animation(), dag_add_node(), dag_init(), data_dir_add(), def_internal_icon(), def_internal_vicon(), defgroup_duplicate(), deformVerts(), defvert_add_index_notest(), defvert_verify_index(), direct_link_curve(), direct_link_library(), direct_link_object(), direct_link_screen(), direct_link_texture(), displaceModifier_do(), distribute_threads_init_data(), DM_add_tangent_layer(), dm_calc_normal(), dm_dupEdgeArray(), dm_dupFaceArray(), dm_dupLoopArray(), dm_dupPolyArray(), dm_dupVertArray(), DM_set_object_boundbox(), DM_to_bmesh_ex(), DM_to_meshkey(), DM_update_weight_mcol(), DNA_struct_get_compareflags(), DNA_struct_reconstruct(), do_hair_dynamics(), do_layer_brush(), do_makeDispListCurveTypes(), do_ob_key(), do_paintface_box_select(), do_paintvert_box_select(), do_shared_vertex_tesscol(), do_shared_vertexcol(), do_version_ntree_242_2(), do_versions(), do_versions_nodetree_multi_file_output_format_2_62_1(), do_versions_socket_default_value(), draw_new_particle_system(), draw_ptcache_edit(), draw_tracking_tracks(), draw_triangulated(), draw_volume(), driver_add_new_variable(), dupli_keyIndexHash(), duplicate_fcurve_keys(), duplicate_track(), dynamicPaint_allocateSurfaceType(), dynamicPaint_createNewSurface(), dynamicPaint_createType(), dynamicPaint_createUVSurface(), dynamicPaint_doStep(), dynamicPaint_generateBakeData(), dynamicPaint_initAdjacencyData(), dynamicPaint_Modifier_apply(), dynamicPaint_resetSurface(), dynamicPaint_updateBrushMaterials(), ED_area_swapspace(), ED_armature_edit_bone_add(), ED_armature_from_edit(), ED_armature_to_edit(), ED_clip_buttons_register(), ED_clip_tool_props_register(), ED_fileselect_init_layout(), ED_fileselect_set_params(), ed_marker_add(), ed_marker_duplicate_apply(), ed_marker_move_init(), ED_mesh_mirrtopo_init(), ED_preview_icon_job(), ED_preview_shader_job(), ED_refresh_viewport_fps(), ED_region_draw_cb_activate(), ED_screen_animation_timer(), ED_space_image_uv_sculpt_update(), ED_spacetype_action(), ED_spacetype_buttons(), ED_spacetype_clip(), ED_spacetype_console(), ED_spacetype_file(), ED_spacetype_image(), ED_spacetype_info(), ED_spacetype_ipo(), ED_spacetype_logic(), ED_spacetype_nla(), ED_spacetype_node(), ED_spacetype_outliner(), ED_spacetype_script(), ED_spacetype_sequencer(), ED_spacetype_text(), ED_spacetype_time(), ED_spacetype_userpref(), ED_spacetype_view3d(), ED_uvedit_buttons_register(), ED_vgroup_add_name(), ED_vgroup_data_create(), ED_view3D_background_image_new(), ED_view3d_depth_update(), ED_view3d_draw_offscreen(), EDBM_backbuf_border_init(), EDBM_backbuf_border_mask_init(), EDBM_backbuf_circle_init(), EDBM_uv_element_map_create(), EDBM_uv_vert_map_create(), edge_pathbase_new(), edgetag_shortest_path(), editbmesh_get_first_deform_matrices(), editBones_to_undoBones(), editbtMesh_to_undoMesh(), editCurve_to_undoCurve(), editFont_to_undoFont(), editLatt_to_undoLatt(), editMball_to_undoMball(), editmesh_set_connectivity_distance(), enforce_locks(), enum_items_from_py(), extrawindow_new(), eyedropper_init(), fcm_cycles_time(), fcm_generator_evaluate(), fcm_generator_new_data(), fcm_generator_verify(), fcm_python_new_data(), fcurve_add_to_list(), fcurve_store_samples(), fcurves_to_pchan_links_get(), file_browse_invoke(), file_buttons_region(), file_new(), file_panels_register(), filedata_new(), filelist_filter(), filelist_new(), fill_add_joint(), fillBevelCap(), filldisplist(), find_displist_create(), find_doubles_index_map(), findFreeNavPolyIndex(), flatten_string_append(), fluidsim_init(), flushTransTracking(), fly_invoke(), fmod_envelope_addpoint_cb(), fmod_envelope_deletepoint_cb(), folderlist_duplicate(), folderlist_new(), font_ui_template_init(), freetypechar_to_vchar(), fsmenu_get(), generate_preview(), get_cached_work_texture(), get_collisionobjects(), get_constraint_target_matrix(), AnimationExporter::get_eul_source_for_quat(), get_ikdata(), get_mesh_orco_verts(), get_selected_and_linked_obs(), get_ss_weights(), get_texture_coords(), get_weights_array(), getCCGDerivedMesh(), getEditDerivedBMesh(), give_base_to_objects(), give_ibuf_prefetch_request(), global_bounds_obi(), gp_session_initpaint(), gp_session_validatebuffer(), gp_stroke_eraser_splitdel(), gp_stroke_newfrombuffer(), gp_stroke_smooth(), gp_stroke_to_bezier(), gp_stroke_to_path(), gpencil_frame_addnew(), gpencil_layer_addnew(), gpencil_undo_push(), gplayer_make_cfra_list(), GPU_begin_object_materials(), GPU_buffer_alloc(), gpu_buffer_pool_new(), GPU_build_grid_buffers(), GPU_build_mesh_buffers(), gpu_drawobject_init_vert_points(), GPU_drawobject_new(), GPU_framebuffer_create(), GPU_generate_pass(), GPU_glTexSubImageEmpty(), GPU_lamp_from_blender(), gpu_make_repbind(), GPU_material_construct_begin(), GPU_material_from_blender(), GPU_node_begin(), gpu_node_input_link(), GPU_node_link_create(), GPU_node_output(), GPU_offscreen_create(), gpu_parse_functions_string(), gpu_render_lamp_update(), GPU_shader_create(), GPU_shader_export(), GPU_texture_convert_pixels(), GPU_texture_create_3D(), GPU_texture_create_nD(), GPU_texture_from_blender(), grab_clone_invoke(), graph_buttons_register(), graph_has_buttons_region(), graph_init(), graph_new(), graphedit_get_context(), graphkeys_euler_filter_exec(), group_linkobs2scene_cb(), grow_nodes(), handleRadialSymmetry(), harmonic_coordinates_bind(), hashvert_flag(), HC_relaxation_iteration_uv(), heat_bone_weighting(), heat_calc_vnormals(), heat_laplacian_create(), heat_ray_tree_create(), icon_create_drawinfo(), icon_create_rect(), icon_preview_add_size(), icon_preview_startjob_all_sizes(), icu_to_fcurves(), idp_generic_copy(), IDP_GetGroupIterator(), IDP_GetProperties(), IDP_New(), IDP_NewIDPArray(), IDP_NewString(), IDP_ResizeArray(), IDP_ResizeIDPArray(), idriver_to_cdriver(), IIR_gauss(), IIR_gauss_single(), image_buttons_register(), image_has_buttons_region(), image_has_scope_region(), image_new(), image_open_init(), image_record_composite_init(), image_renderinfo_cb(), image_sample_invoke(), image_undo_push_tile(), image_view_pan_init(), image_view_zoom_init(), imb_addtilesImBuf(), IMB_allocImBuf(), IMB_exr_add_channel(), IMB_exr_get_handle(), imb_exr_get_layer(), imb_exr_get_pass(), imb_global_cache_tile_load(), IMB_index_builder_create(), IMB_indexer_dv_new(), IMB_indexer_open(), imb_loadtarga(), IMB_metadata_add_field(), IMB_moviecache_create(), IMB_moviecache_get_cache_segments(), IMB_open_anim(), imb_savepng(), implicit_init(), implicit_solver(), index_fallback_create_context(), info_new(), init(), init_actuator(), init_controller(), init_cvKeyIndex(), init_glow_effect(), init_heights_data(), init_iconfile_list(), init_jitter_plane(), init_multiresbake_job(), init_normal_data(), init_output_file(), init_pose_ikparam(), init_property(), init_render_curve(), init_render_qmcsampler(), init_render_surf(), init_sensor(), init_solid_color(), init_speed_effect(), init_structDNA(), init_transform_effect(), init_userdef_do_versions(), init_wipe_effect(), initData(), initElbeemMesh(), initglobals(), initialize_all_particles(), initialize_chain(), initialize_posetree(), initMouseInputMode(), initparts(), initshadowbuf(), insert_bezt_fcurve(), insert_text_exec(), internalAdd(), internalDocs(), interp_sparse_array(), is_track_clean(), ISB_create(), isb_make_buffer(), isb_make_buffer_transp(), join_dirfile_alloc(), join_mesh_exec(), key_block_get_data(), key_to_vertcos(), knife_cut_through(), knifetool_init(), laplacian_relaxation_iteration_uv(), laplacian_system_construct_begin(), laplacian_system_construct_end(), latt_to_key(), lattice_calc_modifiers(), layer_menu(), layerCopy_mdeformvert(), layerInterp_mdeformvert(), layerRead_mdisps(), layerSwap_mdisps(), link_logicbricks(), KX_BlenderSceneConverter::LinkBlendFile(), list_find_data_fcurves(), load_editLatt(), load_editText(), load_vfont(), loggerwindow_new(), logic_has_buttons_region(), logic_new(), M_Geometry_interpolate_bezier(), M_Geometry_tessellate_polygon(), main(), mainwindow_new(), make_boneList(), make_edges_mdata(), make_editLatt(), make_editNurb(), make_editText(), make_mesh_edge_lookup(), make_new_animlistelem(), make_occ_tree(), make_orco_surf(), make_sample_tables(), make_selection_list_nurb(), make_socket(), make_structDNA(), make_trans_verts(), make_unique_prop_names(), make_uv_vert_map(), makebevelcurve(), makeBevelList(), makecubetable(), makedeepshadowbuf(), makeDispListSurf(), makeknots(), makeNurbcurve(), makeNurbfaces(), makeraytree_object(), makeraytree_single(), material_append_id(), material_pop_id(), max_undo_test(), mem_element_new(), MEM_mapallocN(), mesh_calc_normals(), mesh_calc_normals_mapping_ex(), mesh_calc_normals_tessface(), mesh_deform_bind(), mesh_get_mapped_verts_nors(), mesh_get_x_mirror_faces(), mesh_octree_add_node(), mesh_octree_table(), mesh_to_curve(), mesh_to_key(), meshdeform_bind_floodfill(), meshdeform_matrix_solve(), meshdeformModifier_do(), metaball_polygonize(), minimize_stretch_init(), ml_addlayer_cb(), ml_addpass_cb(), modifier_mdef_compact_influences(), modifier_new(), modifiers_calcDataMasks(), moveCloserToDistanceFromPlane(), multiple_scattering_diffusion(), multires_del_higher(), multires_dm_create_from_derived(), multires_load_old_250(), multires_load_old_dm(), multires_modifier_update_mdisps(), multires_reallocate_mdisps(), multires_set_space(), multires_subdivide(), multires_topology_changed(), multiresbake_image_exec(), multiresModifier_base_apply(), multiresModifier_reshapeFromDeformMod(), my_boundbox_mesh(), nalloc_abk_bezt(), nalloc_ak_bezt(), nalloc_ak_gpframe(), nearest_fcurve_vert_store(), new_actuator(), new_controller(), new_dupli_object(), new_effector_cache(), new_particle_duplilist(), new_particle_target_exec(), new_pgn_element(), new_property(), new_sensor(), new_vpaint(), newPackedFileMemory(), newReebGraph(), newRigArc(), newRigControl(), newRigGraph(), newRigNode(), newRigNodeHead(), nla_buttons_register(), nla_has_buttons_region(), nla_init(), nla_new(), nlaedit_add_transition_exec(), nlaedit_get_context(), nlaevalchan_verify(), nlastrips_ctime_get_strip(), nlastrips_to_animdata(), node_alphaover_init(), node_buttons_register(), node_composit_init_bilateralblur(), node_composit_init_blur(), node_composit_init_channel_matte(), node_composit_init_chroma_matte(), node_composit_init_color_matte(), node_composit_init_color_spill(), node_composit_init_colorbalance(), node_composit_init_crop(), node_composit_init_dblur(), node_composit_init_defocus(), node_composit_init_diff_matte(), node_composit_init_distance_matte(), node_composit_init_glare(), node_composit_init_hue_sat(), node_composit_init_image(), node_composit_init_lensdist(), node_composit_init_luma_matte(), node_composit_init_splitviewer(), node_composit_init_tonemap(), node_composit_init_vecblur(), node_composit_init_viewer(), node_duplicate_exec(), node_group_add_extern_socket(), node_group_add_socket(), node_has_buttons_region(), node_init_preview(), node_internal_connect_default(), node_link_invoke(), node_menus_register(), node_new(), node_resize_invoke(), node_shader_init_attribute(), node_shader_init_geometry(), node_shader_init_tex_checker(), node_shader_init_tex_environment(), node_shader_init_tex_gradient(), node_shader_init_tex_image(), node_shader_init_tex_magic(), node_shader_init_tex_musgrave(), node_shader_init_tex_noise(), node_shader_init_tex_sky(), node_shader_init_tex_voronoi(), node_shader_init_tex_wave(), node_socket_button_components(), node_socket_make_default_value(), nodeAddLink(), nodeAddNode(), nodeCopyNode(), nodeMakeDynamicType(), ntree_exec_begin(), ntree_version_241(), ntree_version_242(), ntree_version_245(), ntreeAddTree(), ntreeCompositOutputFileAddSocket(), ntreeGetDependencyList(), ntreeGetThreadStack(), ntreeShaderBeginExecTree(), ntreeTexBeginExecTree(), nurbs_to_mdata_customdb(), object_add_collision_fields(), object_add_particle_system(), object_insert_ptcache(), object_shape_key_mirror(), objects_bake_render_invoke(), objfnt_to_ftvfontdata(), occ_compute_bounces(), occ_compute_passes(), occ_tree_build(), ocean_bake_exec(), old_mdisps_convert(), oldnewmap_new(), open_init(), operator_call_cb(), outliner_add_element(), outliner_new(), p_abf_setup_system(), p_chart_new(), paint_stroke_new(), panel_activate_state(), param_construct_begin(), pass_menu(), paste_file(), pbvh_build(), pbvh_stack_push(), pbvh_update_normals(), PE_create_particle_edit(), PE_mirror_x(), PE_undo_push(), PE_update_mirror_cache(), phash_insert(), phash_new(), polygonize(), pose_add_group(), pose_select_same_group(), pose_slide_init(), poselib_add_exec(), poselib_backup_posecopy(), poselib_preview_get_next(), poselib_preview_init_data(), poselib_sanitise_exec(), posttrans_fcurve_clean(), precache_init_parts(), precalc_guides(), prependPolyLineVert(), ProcDef(), project_paint_begin(), psys_alloc_path_cache_buffers(), psys_cache_vgroup(), psys_calc_dmcache(), psys_check_boid_data(), psys_check_group_weights(), psys_create_frand(), psys_prepare_physics(), psys_render_set(), psys_render_simplify_distribution(), psys_threads_create(), ptcache_data_alloc(), ptcache_disk_frame_to_mem(), ptcache_dynamicpaint_write(), ptcache_file_compressed_read(), ptcache_file_compressed_write(), ptcache_mem_frame_to_disk(), ptcache_particle_extra_write(), ptcache_write(), put_imbuf_cache(), py_to_array(), pycon_new_data(), pyop_getinstance(), pyrna_py_to_prop(), QMC_initSampler(), quad_4edge_subdivide(), radial_control_invoke(), RE_addRenderInstance(), RE_addRenderObject(), RE_addStrandBuffer(), RE_bake_shade_all_selected(), RE_engine_create(), RE_findOrAddHalo(), RE_findOrAddStrand(), RE_findOrAddVert(), RE_findOrAddVlak(), RE_InitState(), RE_makeRenderInstances(), RE_NewRender(), RE_rayobject_blibvh_create(), RE_rayobject_instance_create(), RE_rayobject_octree_create(), RE_rayobject_octree_done(), RE_set_customdata_names(), RE_strandren_get_face(), RE_strandren_get_mcol(), RE_strandren_get_simplify(), RE_strandren_get_surfnor(), RE_strandren_get_uv(), RE_strandren_get_winspeed(), RE_vertren_get_rad(), RE_vertren_get_tangent(), RE_vertren_get_winspeed(), RE_vlakren_get_mcol(), RE_vlakren_get_nmap_tangent(), RE_vlakren_get_radface(), RE_vlakren_get_surfnor(), RE_vlakren_get_tface(), realloc_particles(), rearrange_animchannel_add_to_islands(), recalc_emitter_field(), recent_files_menu_register(), region_azone_initialize(), region_scale_invoke(), register_node_type_frame(), rekey_particle(), remove_tagged_keys(), remove_tagged_particles(), render_layer_add_pass(), render_new_particle_system(), render_result_new(), render_result_new_from_exr(), render_result_rect_fill_zero(), resize_object_material(), resizelattice(), retargetArctoArc(), retargetArctoArcAggresive(), RIG_addEdgeToArc(), RIG_graphFromArmature(), ringsel_init(), rna_alloc_function_name(), RNA_create(), rna_def_function(), RNA_def_property(), RNA_def_struct(), RNA_enum_item_add(), rna_function_parameter_parse(), rna_iterator_array_begin(), rna_iterator_listbase_begin(), RNA_parameter_list_create(), rna_path_token(), RNA_property_boolean_get_default_index(), RNA_property_boolean_get_index(), RNA_property_boolean_set_index(), RNA_property_copy(), RNA_property_enum_items_gettexted(), RNA_property_float_get_default_index(), RNA_property_float_get_index(), RNA_property_float_set_index(), RNA_property_int_get_default_index(), RNA_property_int_get_index(), RNA_property_int_set_index(), RNA_property_reset(), RNA_property_string_get_default_alloc(), RNA_property_update_cache_add(), rna_raw_access(), rna_search_cb(), AnimationExporter::sample_and_write_bone_animation(), sample_fcurve(), sample_invoke(), save_hair(), sb_cf_threads_run(), SB_estimate_transform(), sb_new_scratch(), sb_sfesf_threads_run(), sbNew(), scanfill(), scatter_settings_new(), scatter_tree_build(), scatter_tree_new(), scene_add_base(), scene_add_render_layer(), scopes_update(), screen_addarea(), screen_addedge(), screen_addvert(), screen_opengl_render_init(), screen_render_invoke(), screencast_exec(), screenshot_data_create(), script_new(), scrollbar_new(), scroller_activate_init(), sculpt_flush_stroke_deform(), sculpt_get_first_deform_matrices(), sculpt_init_session(), sculpt_toggle_mode(), sculpt_undo_alloc_node(), sculpt_update_cache_invariants(), select_less_exec(), select_linked(), select_linked_tfaces_with_seams(), select_more_exec(), select_moreless_action_keys(), select_moreless_graph_keys(), seq_give_editing(), seq_proxy_build_job(), seq_proxy_rebuild_context(), sequence_effect_speed_rebuild_map(), sequencer_add_effect_strip_exec(), sequencer_add_image_strip(), sequencer_add_movie_strip(), sequencer_add_movieclip_strip_exec(), sequencer_add_scene_strip_exec(), sequencer_change_path_exec(), sequencer_has_buttons_region(), sequencer_meta_make_exec(), sequencer_new(), set_keyed_keys(), setCustomPoints(), shade_tface(), shadowbuf_autoclip(), shapekey_layers_to_keyblocks(), shrink_picture_byte(), shrink_picture_float(), sk_allocStrokeBuffer(), sk_createStroke(), sk_filterStroke(), sk_getIntersections(), sk_getSelfIntersections(), sk_pointToNode(), sk_strokeToArc(), sketch_draw_gesture(), sketch_draw_stroke(), slot_menu(), smokeModifier_createType(), smooth_fcurve(), smoothModifier_do(), snode_autoconnect(), snode_bg_viewmove_invoke(), snode_composite_job(), solidify_add_thickness(), solve_camera_exec(), solve_camera_initjob(), solve_camera_invoke(), sort_halos(), sound_open_init(), sph_spring_add(), splineik_init_tree_from_pchan(), sss_add_points(), sss_create_tree_mat(), startavi(), stats_update(), stitch_init(), stitch_process_data(), strand_shade_cache_create(), strand_shade_get(), subdivide_particle(), subdividenurb(), surfaceGenerateGrid(), tex_space_curve(), tex_space_mball(), text_convert_whitespace_exec(), text_drawcache_init(), text_has_properties_region(), text_new(), text_open_init(), text_scroll_bar_invoke(), text_scroll_invoke(), text_set_selection_invoke(), text_update_drawcache(), texture_paint_init(), thumbnails_start(), time_draw_cache(), time_new(), track_markers_invoke(), tracks_map_new(), transformops_data(), tree_element_to_path(), tri_3edge_subdivide(), txt_add_object(), txt_copy_selected(), ui_add_link(), ui_add_link_line(), ui_add_smart_controller(), ui_add_temporary_region(), ui_apply_autokey_undo(), ui_apply_but_func(), ui_block_position(), ui_but_copy_paste(), ui_but_search_test(), ui_convert_to_unit_alt_name(), ui_def_but(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_item_array(), ui_layout_add_but(), ui_layout_box(), ui_popup_block_create(), ui_popup_menu_create(), ui_searchbox_create(), ui_style_new(), ui_template_id(), ui_textedit_begin(), ui_textedit_set_cursor_pos(), ui_theme_init_default(), ui_tooltip_create(), UI_view2d_grid_calc(), UI_view2d_scrollers_calc(), UI_view2d_tab_set(), UI_view2d_text_cache_add(), UI_view2d_text_cache_rectf(), uiAlignPanelStep(), uiBeginBlock(), uiBeginPanel(), uiBlockLayout(), uiButGetOperatorPtrRNA(), uiItemMenuEnumO(), uiItemMenuEnumR(), uiLayoutAbsolute(), uiLayoutColumn(), uiLayoutColumnFlow(), uiLayoutOverlap(), uiLayoutRow(), uiLayoutSplit(), uiPupMenuBegin(), uiSetButLink(), uiStyleInit(), uiTemplateColorRamp(), uiTemplateCurveMapping(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateMarker(), uiTemplateNodeLink(), uiTemplateVectorscope(), uiTemplateWaveform(), undo_editmode_push(), undo_stack_push_begin(), unit_boundbox(), update_string(), userpref_new(), uv_sculpt_stroke_init(), uvprojectModifier_do(), v3d_editvertex_buts(), verify_driver_fcurve(), verify_fcurve(), verify_pose_channel(), vertcos_to_key(), vfont_get_data(), vgroup_blend(), vgroup_fix(), view3d_boxview_clip(), view3d_buttons_register(), view3d_cached_text_draw_add(), view3d_clipping_exec(), view3d_has_buttons_region(), view3d_has_tools_region(), view3d_new(), view3d_split_250(), view3d_tool_props_register(), view3d_toolshelf_register(), view_pan_init(), view_zoom_init(), view_zoomdrag_init(), viewops_data_create(), vol_precache_objectinstance_threads(), vpaint_stroke_test_start(), vtx_slide_init(), weight_paint_sample_enum_itemf(), weightvg_do_mask(), WM_clipboard_text_get(), WM_clipboard_text_set(), WM_dropbox_add(), WM_dropboxmap_find(), wm_event_add(), WM_event_add_dropbox_handler(), WM_event_add_fileselect(), WM_event_add_keymap_handler(), WM_event_add_keymap_handler_priority(), WM_event_add_modal_handler(), WM_event_add_notifier(), WM_event_add_timer(), WM_event_add_ui_handler(), WM_event_start_drag(), WM_gesture_lasso_modal(), WM_gesture_new(), WM_init_game(), WM_jobs_get(), WM_keyconfig_new(), WM_keymap_add_item(), wm_keymap_diff(), wm_keymap_item_copy(), wm_keymap_new(), WM_keymap_verify_item(), wm_macro_start(), WM_main_add_notifier(), wm_method_draw_triple(), WM_modalkeymap_add_item(), WM_modalkeymap_add_item_str(), wm_operator_create(), WM_operator_properties_alloc(), WM_operator_props_dialog_popup(), wm_operator_reports(), WM_operator_ui_popup(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_operatortype_append_ptr(), WM_operatortype_macro_define(), WM_paint_cursor_activate(), wm_subwindow_open(), wm_window_add_ghostwindow(), wm_window_add_ghostwindows(), wm_window_new(), wpaint_stroke_test_start(), writedata_new(), xsortvert_flag(), zbuffer_strands_abuf(), zbuffer_transp_shade(), zbufshade_sss_tile(), zbufshade_tile(), and zbufshadeDA_tile().
int MEM_check_memory_integrity (void)
Are the start/end block markers still correct ?
Return values:
0 for correct memory, 1 for corrupted memory.
Definition at line 196 of file mallocn.c.
References check_memlist(), localListBase::last, and NULL.
Referenced by main().
void* MEM_dupallocN (void * vmemh)
Duplicates a block of memory, and returns a pointer to the newly allocated block.
Definition at line 238 of file mallocn.c.
References MemHead::len, MEM_mallocN(), MEM_mapallocN(), MemHead::mmap, and NULL.
Referenced by action_duplicate(), adduplicateflagNurb(), ANIM_paste_driver(), apply_mp_locks_normalize(), BKE_area_region_copy(), BKE_copy_animdata(), BKE_copy_envmap(), BKE_copy_oceantex(), BKE_copy_pointdensity(), BKE_copy_voxeldata(), BKE_keyingsets_copy(), BKE_previewimg_copy(), BLI_duplicatelist(), BLI_pbvh_apply_vertCos(), BM_data_layer_add(), BM_data_layer_add_named(), BM_data_layer_free(), BM_data_layer_free_n(), bm_mdisps_space_set(), boid_copy_settings(), boid_duplicate_state(), buttons_duplicate(), ccd_mesh_make(), ccd_mesh_update(), clip_duplicate(), colorband_buttons_large(), colorband_buttons_small(), console_duplicate(), convert_exec(), copy_actuator(), copy_animedit_keys(), copy_bulletsoftbody(), copy_constraints(), copy_controller(), copy_curve(), copy_displist(), copy_fcurve(), copy_fmodifier(), copy_fmodifiers(), copy_glow_effect(), copy_group(), copy_key(), copy_key_nolib(), copy_lattice(), copy_matcopybuf(), copy_material(), copy_mball(), copy_mesh(), copy_nlastrip(), copy_nlatrack(), copy_object(), copy_output_file(), copy_particle_dupliob_exec(), copy_particlesystem(), copy_plugin(), copy_pose(), copy_property(), copy_scene(), copy_sensor(), copy_softbody(), copy_solid_color(), copy_speed_effect(), copy_texture(), copy_transform_effect(), copy_wipe_effect(), copyData(), crazyspace_build_sculpt(), CTX_copy(), CTX_store_add(), CTX_store_add_all(), CTX_store_copy(), curve_calc_modifiers_pre(), curvemap_buttons_layout(), curvemap_reset(), curvemapping_copy(), CustomData_bmesh_merge(), CustomData_copy(), CustomData_duplicate_referenced_layer(), CustomData_duplicate_referenced_layer_named(), deformVerts(), defvert_copy(), direct_link_mesh(), do_versions(), do_weight_paint_vertex(), draw_setting_widget(), duplicate_metaelems_exec(), duplicate_track(), ed_marker_make_links_scene_exec(), ED_mesh_mirrtopo_init(), ED_vgroup_copy_array(), editbmesh_calc_modifiers(), editBones_to_undoBones(), editLatt_to_undoLatt(), editMball_to_undoMball(), fcm_envelope_copy(), fcm_generator_copy(), fcurve_copy_driver(), file_duplicate(), flyEvent(), folderlist_duplicate(), game_copy_pose(), get_alpha_clone_image(), get_PTCacheUndo(), gp_stroke_eraser_splitdel(), gpencil_data_duplicate(), gpencil_frame_duplicate(), gpencil_layer_duplicate(), gpu_node_input_link(), gpu_queue_image_for_free(), graph_duplicate(), graph_panel_drivers(), IDP_CopyArray(), IDP_CopyIDPArray(), IDP_CopyString(), image_duplicate(), image_load_sequence_multilayer(), IMB_filter_extend(), IMB_mask_filter_extend(), info_duplicate(), init_render_mesh(), insert_curvekey(), insert_lattkey(), join_mesh_exec(), layerCopy_mdisps(), load_editLatt(), localize_material(), localize_texture(), logic_duplicate(), make_editLatt(), make_object_duplilist_real(), make_PTCacheUndo(), makebevelcurve(), makeOrcoDispList(), modifier_vgroup_cache(), multires_mdisps_upsample_hidden(), nla_duplicate(), node_composit_exec_image(), node_composit_get_movieclip(), node_copy_standard_storage(), node_duplicate(), ntreeCopyTree(), ntreeGetThreadStack(), object_make_proxy(), occ_compute_bounces(), outliner_duplicate(), p_chart_abf_solve(), paste_matcopybuf(), PE_mirror_particle(), PE_mirror_x(), project_paint_begin(), psys_copy_settings(), ptcache_copy(), ptcache_particle_extra_read(), rekey_particle_to_time(), rna_search_cb(), rotate_direction_nurb(), script_duplicate(), sculpt_undo_alloc_and_store_hidden(), seq_dupli(), sequencer_duplicate(), smokeModifier_copy(), smooth_exec(), splineik_copy(), splineik_init_tree_from_pchan(), template_ID(), template_texture_user_menu(), text_duplicate(), time_duplicate(), tracks_map_insert(), ui_apply_but_func(), ui_def_but(), ui_node_menu_column(), ui_template_node_link_menu(), uiAlignPanelStep(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateVectorscope(), undoBones_to_editBones(), undoMball_to_editMball(), userpref_duplicate(), view3d_boxview_clip(), view3d_duplicate(), view3d_main_area_duplicate(), wm_keymap_copy(), wm_keymap_diff_item_copy(), wm_keymap_item_copy(), and zmask_rect().
short MEM_freeN (void * vmemh)
Release memory previously allocatred by this module.
Definition at line 581 of file mallocn.c.
References check_memlist(), error(), MemHead::len, mem_lock_thread(), mem_unlock_thread(), MEMFREE, MemorY_ErroR(), MEMTAG1, MEMTAG2, MEMTAG3, MemHead::name, NULL, rem_memblock(), MemHead::tag1, MemHead::tag2, MemTail::tag3, and totblock.
Referenced by accum_mballfaces(), achannel_setting_slider_shapekey_cb(), action_get_item_transforms(), actionzone_exit(), add_2nd_order_springs(), add_bp_springlist(), add_driver_button_exec(), add_in_range(), add_keyingset_button_exec(), add_lightgroup(), add_mesh_quad_diag_springs(), add_mtex_id(), add_named_exec(), add_orco_dm(), add_plugin_seq(), add_plugin_tex(), add_text(), add_verts_to_dgroups(), addNurbPoints(), addNurbPointsBezier(), addtovertices(), adduplicateflagNurb(), alloc_child_particles(), alloc_proxy_output_avi(), ANIM_channel_draw_widgets(), ANIM_keyingset_info_unregister(), animchan_sync_fcurve(), animchannels_delete_exec(), animsys_execute_fcurve(), animviz_free_motionpath(), animviz_free_motionpath_cache(), apply_mp_locks_normalize(), applyModifier(), area_join_exit(), area_move_exit(), area_split_exit(), area_swap_exit(), armature_deform_verts(), arrayModifier_doArray(), assign_material(), assign_material_id(), autocomplete_end(), autokeyframe_pose_cb_func(), autosmooth(), AVI_close(), AVI_close_compress(), avi_converter_from_avi_rgb(), avi_converter_from_mjpeg(), avi_converter_from_rgb32(), avi_converter_to_avi_rgb(), avi_converter_to_mjpeg(), avi_converter_to_rgb32(), avi_fetchibuf(), AVI_is_avi(), AVI_read_frame(), AVI_write_frame(), awrite(), bake_freejob(), beztmap_to_data(), BIF_freeTemplates(), BIF_listTemplates(), BIF_ReebGraphMultiFromEditMesh(), BIF_selectOrientation(), BKE_animdata_fix_paths_rename(), BKE_area_region_free(), BKE_free_animdata(), BKE_free_editfont(), BKE_free_envmap(), BKE_free_ocean(), BKE_free_ocean_cache(), BKE_free_oceantex(), BKE_free_pointdensity(), BKE_free_pointdensitydata(), BKE_free_voxeldata(), BKE_free_voxeldatadata(), BKE_freecubetable(), BKE_image_free_anim_ibufs(), BKE_keyingset_free_path(), BKE_mesh_validate_arrays(), BKE_previewimg_freefunc(), BKE_ptcache_free(), BKE_ptcache_id_time(), BKE_ptcache_toggle_disk_cache(), BKE_read_file(), BKE_reports_clear(), BKE_reports_prepend(), BKE_reports_prependf(), BKE_reports_print(), BKE_spacetype_register(), BKE_text_to_curve(), BKE_tracking_clear_path(), BKE_tracking_context_free(), BKE_tracking_delete_marker(), BKE_tracking_detect_fast(), BKE_tracking_distortion_destroy(), BKE_tracking_free_clipboard(), BKE_tracking_free_track(), BKE_tracking_join_tracks(), BKE_tracking_next(), BKE_tracking_reconstruction_context_free(), BKE_undo_get_main(), BKE_userdef_free(), BKE_write_undo(), BL_ConvertActuators(), BL_ConvertControllers(), BL_MakeScreenShot(), BLF_dir_free(), blf_dir_metrics_search(), BLF_dir_rem(), blf_font_free(), blf_font_new(), blf_font_new_from_mem(), blf_glyph_cache_free(), blf_glyph_free(), BLF_load(), BLF_load_unique(), BLI_argsFree(), BLI_buildAdjacencyList(), BLI_bvhtree_free(), BLI_bvhtree_new(), BLI_bvhtree_overlap(), BLI_cb_finalize(), BLI_copy(), BLI_destroy_worker(), BLI_dir_create_recursive(), BLI_dynlib_close(), BLI_dynstr_appendf(), BLI_dynstr_free(), BLI_dynstr_vappendf(), BLI_edgefill_ex(), BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehashIterator_free(), BLI_file_free_lines(), BLI_file_read_as_lines(), BLI_file_ungzip_to_mem(), BLI_freeAdjacencyList(), BLI_freelinkN(), BLI_freelistN(), BLI_freeNode(), BLI_ghash_free(), BLI_ghash_insert(), BLI_ghashIterator_free(), BLI_ghashutil_pairfree(), BLI_gsqueue_free(), BLI_gsqueue_pop(), BLI_heap_free(), BLI_heap_insert(), BLI_initjit(), BLI_kdtree_find_n_nearest(), BLI_kdtree_find_nearest(), BLI_kdtree_free(), BLI_kdtree_range_search(), BLI_linklist_free(), BLI_memarena_free(), BLI_mempool_destroy(), BLI_mempool_free(), BLI_pbvh_build_grids(), BLI_pbvh_build_mesh(), BLI_pbvh_draw(), BLI_pbvh_free(), BLI_pbvh_gather_proxies(), BLI_pbvh_node_free_proxies(), BLI_pbvh_search_gather(), BLI_pbvh_update(), BLI_rebuildAdjacencyListForNode(), BLI_setenv(), BLI_smallhash_insert(), BLI_smallhash_release(), BLI_thread_queue_free(), bli_where_am_i(), BLO_blendfiledata_free(), BLO_blendhandle_get_previews(), BLO_free_memfile(), blo_freefiledata(), blo_join_main(), bloom_with_reference(), blur_single_image(), blur_with_reference(), bm_corners_to_loops(), BM_data_layer_add(), BM_data_layer_add_named(), BM_data_layer_free(), BM_data_layer_free_n(), bm_edgesplit_validate_seams(), BM_face_create_ngon_vcloud(), bm_mdisps_space_set(), BM_mesh_bm_from_me(), BM_mesh_bm_to_me(), BM_mesh_copy(), BM_mesh_free(), BM_mesh_normals_update(), BM_mesh_remap(), BMBVH_FreeBVH(), BME_free_transdata(), BMEdit_Free(), BMEdit_RecalcTessellation_intern(), bmesh_urmv_loop(), bmesh_vert_separate(), bmo_contextual_create_exec(), bmo_create_monkey_exec(), bmo_dissolve_faces_exec(), bmo_dissolve_limit_exec(), bmo_edgenet_fill_exec(), BMO_error_pop(), bmo_inset_exec(), BMO_op_vinitf(), bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), bmo_vertexshortestpath_exec(), boid_free_settings(), bokeh_single_image(), bone_free(), boxPack2D(), boxPack_FromPyObject(), boxPack_ToPyObject(), bpy_bm_utils_vert_separate(), BPy_EnumProperty(), BPy_IDArray_ass_slice(), BPy_IDProperty_Map_ValidateAndCreate(), BPy_reports_to_error(), bpy_text_import(), bpy_text_reimport(), BPy_Wrap_SetMapItem(), brush_add(), brush_edit_exit(), brush_gen_radial_control_imbuf(), brush_painter_free(), bsbFree(), Buffer_dealloc(), build_bps_springlist(), build_underline(), buildchar(), buildNavMesh(), KX_NavMeshObject::BuildNavMesh(), buildNavMeshData(), buildNavMeshDataByDerivedMesh(), buildPolygonsByDetailedMeshes(), KX_NavMeshObject::BuildVertIndArrays(), button_activate_exit(), buttons_context_draw(), buttons_free(), buttons_texture_context_compute(), bvh_free(), bvhcacheitem_free(), cache_voxeldata(), calc_curvepath(), calc_edge_stress(), calc_shapeKeys(), calc_solidify_normals(), calc_vertexnormals(), calc_weightpaint_vert_array(), calculate_speedvectors(), calculateTransformCenter(), ccd_mesh_free(), ccd_mesh_update(), ccgdm_getVertCos(), ccgdm_pbvh_update(), ccgDM_release(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__sync(), ccgSubSurf_free(), ccgSubSurf_processSync(), ccgSubSurf_stitchFaces(), ccgSubSurf_updateFromFaces(), ccgSubSurf_updateLevels(), ccgSubSurf_updateNormals(), ccgSubSurf_updateToFaces(), cdDM_drawFacesTex_common(), cdDM_free_internal(), CDDM_from_curve_customDB(), cdDM_getPBVH(), CDDM_merge_verts(), cdDM_release(), cdf_free(), check_and_compress_jpeg(), check_and_decode_jpeg(), check_destination(), check_persistent(), RAS_MeshObject::CheckWeightCache(), clean_fcurve(), clear_dither_context(), clear_fcurve_keys(), clear_mesh_caches(), clear_solution_exec(), cloth_build_springs(), cloth_bvh_objcollision(), cloth_calc_helper_forces(), cloth_free_errorsprings(), cloth_free_modifier(), cloth_free_modifier_extern(), cloth_from_mesh(), compo_freejob(), compress_deepshadowbuf(), compress_shadowbuf(), console_copy_exec(), console_cursor_set_exit(), console_history_append_exec(), console_history_free(), console_insert_exec(), console_line_verify_length(), console_paste_exec(), console_scrollback_free(), console_scrollback_prompt_end(), constraint_add_exec(), constraints_clear_evalob(), construct_param_handle_subsurfed(), convert_include(), convertspline(), convolve(), copy_animedit_keys(), copy_data_path_button_exec(), copy_driver_button_exec(), copy_scene(), copy_single_file(), copy_to_selected_button_exec(), copy_to_selected_button_poll(), copy_vpaint_prev(), copyData(), copymenu_properties(), cp_key(), crazyspace_build_sculpt(), crazyspace_get_mapped_editverts(), crazyspace_set_quats_editmesh(), create_orco_dm(), create_scene(), createFacepa(), createSlideVerts(), createTransEditVerts(), CTX_free(), CTX_store_free(), curve_calc_modifiers_post(), curve_calc_modifiers_pre(), curve_to_key(), curvemap_insert(), curvemap_make_table(), curvemap_remove(), curvemap_reset(), curvemapping_free(), curvemapping_premultiply(), customData_add_layer__internal(), CustomData_bmesh_interp(), CustomData_bmesh_merge(), CustomData_external_free(), CustomData_free(), customData_free_layer__internal(), CustomData_interp(), customData_resize(), customdata_version_242(), cutEdges(), AnimationExporter::dae_animation(), dag_check_cycle(), dag_get_sub_node(), DAG_pose_sort(), MEM_Allocator< _Tp >::deallocate(), deformVerts(), deformVertsEM(), defvert_add_index_notest(), defvert_clear(), defvert_copy(), defvert_remove_group(), defvert_verify_index(), del_bfmatrix(), del_lfvector(), delete_exec(), delete_fcurve_key(), delete_key_button_exec(), delete_metaelems_exec(), deleteflagNurb(), dialog_exec_cb(), direct_link_curve(), direct_link_dverts(), direct_link_library(), direct_link_mesh(), direct_link_object(), direct_link_screen(), displaceModifier_do(), distribute_threads_init_data(), DM_add_tangent_layer(), dm_calc_normal(), DM_debug_print(), DM_to_bmesh_ex(), DM_to_meshkey(), DM_update_weight_mcol(), DNA_sdna_free(), do_actuator_menu(), do_brush_action(), do_controller_menu(), do_hair_dynamics(), do_idmask(), do_key(), do_latt_key(), do_merge_fullsample(), do_mesh_key(), do_multires_smooth_brush(), do_ob_key(), do_object_pose_box_select(), do_outliner_drivers_editop(), do_outliner_keyingset_editop(), do_paintface_box_select(), do_paintvert_box_select(), do_rel_key(), do_sensor_menu(), do_shared_vertex_tesscol(), do_shared_vertexcol(), do_version_free_effect_245(), do_version_ntree_242_2(), do_versions(), do_versions_nodetree_multi_file_output_format_2_62_1(), do_weight_paint_vertex(), do_write_image_or_movie(), doEdgeSplit(), doMirrorOnAxis(), draw_actuatorbuttons(), draw_depth(), draw_image_buffer_tiled(), draw_image_paint_helpers(), draw_new_particle_system(), draw_ptcache_edit(), draw_tracking_tracks(), draw_volume(), driver_free_variable(), drop_named_image_invoke(), duplicate_fcurve_keys(), duplicate_pose_channel_data(), dynamicPaint_createUVSurface(), dynamicPaint_doStep(), dynamicPaint_doWaveStep(), dynamicPaint_freeAdjData(), dynamicPaint_freeBrush(), dynamicPaint_freeBrushMaterials(), dynamicPaint_freeCanvas(), dynamicPaint_freeSurface(), dynamicPaint_freeSurfaceData(), dynamicPaint_generateBakeData(), dynamicPaint_initAdjacencyData(), dynamicPaint_Modifier_apply(), dynamicPaint_paintMesh(), dynamicPaint_paintParticles(), dynamicPaint_prepareAdjacencyData(), ED_area_headerprint(), ED_area_swapspace(), ED_armature_edit_free(), ED_base_object_free_and_unlink(), ED_editors_exit(), ED_fileselect_exit(), ED_info_stats_clear(), ed_marker_move_exit(), ED_mesh_mirrtopo_free(), ED_mesh_mirrtopo_init(), ED_object_exit_editmode(), ED_object_shape_key_remove(), ed_preview_draw_rect(), ED_preview_init_dbase(), ED_refresh_viewport_fps(), ED_region_draw_cb_exit(), ED_region_exit(), ED_vgroup_copy_array(), ED_vgroup_mirror(), ED_view3D_background_image_remove(), ED_view3d_depth_update(), ED_view3d_draw_offscreen(), EDBM_backbuf_free(), edbm_bevel_exec(), EDBM_index_arrays_free(), edbm_knife_cut_exec(), edbm_loop_multiselect_exec(), EDBM_mesh_clear(), EDBM_mesh_make(), EDBM_op_finish(), edbm_rip_invoke__edge(), edbm_rip_invoke__vert(), edbm_sort_faces_exec(), EDBM_uv_element_map_create(), EDBM_uv_element_map_free(), EDBM_uv_vert_map_free(), EDBM_verts_mirror_cache_end(), edge_pathbase_free(), edgering_sel(), edgetag_shortest_path(), editbmesh_calc_modifiers(), editmesh_set_connectivity_distance(), editvert_mirror_update(), emDM_release(), end_avi(), end_latt_deform(), enforce_locks(), enum_items_from_py(), exec_retargetArctoArc(), exec_work_fnct(), execute_posetree(), expand_doit(), extrawindow_free(), extrudeflagNurb(), eyedropper_exit(), face_duplilist(), FaceIt_Destruct(), fcm_cycles_evaluate(), fcm_envelope_free(), fcm_generator_evaluate(), fcm_generator_free(), fcm_generator_verify(), fcm_python_free(), fcurve_free_driver(), fcurve_path_rename(), fcurve_store_samples(), fcurve_to_keylist(), file_browse_cancel(), file_browse_exec(), file_browse_invoke(), file_free(), filelist_filter(), filelist_free(), find_missing_files_exec(), findFreeNavPolyIndex(), DocumentImporter::finish(), finish_bake_internal(), finish_images(), flatten_string_append(), flatten_string_free(), fluid_free_settings(), fluidsim_free(), fly_invoke(), flyEnd(), flyEvent(), fmod_envelope_addpoint_cb(), fmod_envelope_deletepoint_cb(), folderlist_free(), folderlist_popdir(), font_duplilist(), font_open_cancel(), font_open_exec(), free_actuator(), free_anim_avi(), free_anim_copybuf(), free_armature(), free_avicodecdata(), free_bakeData(), free_bonelist(), free_buffers(), free_collider_cache(), free_compbuf(), free_constraint_data(), free_controller(), free_controllers(), free_curve(), free_curve_editNurb(), free_curve_editNurb_keyIndex(), free_dbase_object_vectors(), free_disp_elem(), free_dverts(), free_dynamic_typeinfo(), free_editLatt(), free_fcurve(), free_forest(), free_glow_effect(), free_gpencil_strokes(), free_group_object(), free_hair(), free_heights_data(), free_ipo(), free_key(), free_key_nolib(), free_keyed_keys(), free_lamp(), free_lattice(), free_libblock(), free_main(), free_matcopybuf(), free_material(), free_mball(), free_mesh(), free_mesh_orco_hash(), free_metaball_octal_node(), free_nlastrip(), free_nlatrack(), free_normal_data(), free_object(), free_object_duplilist(), free_occ_samples(), free_openrecent(), free_output_file(), free_partdeflect(), free_path(), free_plugin_seq(), free_plugin_tex(), free_pointdensity(), free_pose(), free_pose_channel(), free_posebuf(), free_posetree(), free_property(), free_PTCacheUndo(), free_qtcodecdata(), free_render_qmcsampler(), free_renderdata_strandnodes(), free_renderdata_tables(), free_renderdata_vertnodes(), free_renderdata_vlaknodes(), free_sample_tables(), free_scene(), free_scratch(), free_sculptsession(), free_sculptsession_deformMats(), free_sensor(), free_slide_data(), free_softbody_baked(), free_softbody_intern(), free_solid_color(), free_speed_effect(), free_ss_weights(), free_strand_surface(), free_text(), free_texture(), free_transform_effect(), free_typeinfos(), free_undo(), free_undoBones(), free_undoCurve(), free_undoFont(), free_undoLatt(), free_undoMball(), free_uv_vert_map(), free_vfont(), free_volume_precache(), free_wipe_effect(), free_world(), freeData(), freeencodedbufferImBuf(), freeGrid(), freeItem(), freeMetaElemlist(), freeN(), freeNurb(), freePackedFile(), freeparts(), freepolygonize(), freeps(), freepsA(), freeraytree(), freeSeqData(), freeshadowbuf(), freeSketch(), freeSlideVerts(), freeT(), freetypechar_to_vchar(), fsmenu_free(), fsmenu_free_category(), fsmenu_remove_entry(), fwritecolrs(), game_free_pose(), gen_lock_flags(), generate_preview(), get_bhead(), get_cached_work_texture(), get_constraint_target_matrix(), get_driver_path_hack(), AnimationExporter::get_eul_source_for_quat(), get_PTCacheUndo(), get_ss_weights(), get_texture_coords(), getname_anim_fcurve(), gp_session_cleanup(), gp_stroke_eraser_dostroke(), gp_stroke_eraser_splitdel(), gp_stroke_newfrombuffer(), gp_stroke_simplify(), gp_stroke_smooth(), gpencil_draw_exec(), gpencil_draw_exit(), gpencil_draw_invoke(), gpencil_frame_addnew(), gpencil_frame_delete_laststroke(), gpencil_undo_finish(), gpencil_undo_push(), gpu_buffer_pool_delete_last(), gpu_buffer_pool_free(), gpu_buffer_setup(), GPU_codegen_exit(), GPU_drawobject_free(), GPU_end_object_materials(), GPU_framebuffer_free(), GPU_free_buffers(), GPU_free_image(), GPU_free_shader_export(), GPU_glTexSubImageEmpty(), GPU_lamp_free(), gpu_make_repbind(), GPU_material_free(), GPU_node_free(), gpu_node_input_link(), GPU_node_link_free(), GPU_offscreen_free(), GPU_paint_update_image(), gpu_parse_functions_string(), GPU_pass_free(), GPU_shader_export(), GPU_shader_free(), GPU_texture_create_3D(), GPU_texture_create_nD(), GPU_texture_free(), GPU_verify_image(), grab_clone_cancel(), grab_clone_modal(), graph_fmodifier_copy_exec(), graph_free(), graph_panel_context(), graph_panel_drivers(), graph_panel_key_properties(), graph_panel_modifiers(), graph_panel_properties(), graphkeys_click_insert_exec(), graphkeys_mselect_column(), graphop_active_fcurve_poll(), group_sort_exec(), grow_nodes(), handleRadialSymmetry(), harmonic_coordinates_bind(), hashvert_flag(), HC_relaxation_iteration_uv(), heat_bone_weighting(), heat_system_free(), hide_show_exec(), ibJpegImageFromCinfo(), ibuftoimage(), icon_free(), icon_preview_free(), id_data_find_fcurve(), IDP_CopyIDPArray(), IDP_FreeArray(), IDP_FreeIDPArray(), IDP_FreeIterBeforeEnd(), IDP_FreeString(), IDP_GroupIterNext(), IDP_ReplaceGroupInGroup(), IDP_ReplaceInGroup(), idp_resize_group_array(), IDP_ResizeArray(), IDP_ResizeIDPArray(), IDP_SyncGroupValues(), IIR_gauss(), IIR_gauss_single(), image_free_buffers(), image_open_cancel(), image_open_exec(), image_record_composite_exit(), image_sample_exit(), image_save_as_free(), image_undo_free(), image_view_pan_exit(), image_view_zoom_exit(), imb_addrectImBuf(), IMB_exr_close(), IMB_filter_extend(), IMB_flipy(), IMB_free_anim(), IMB_freeImBuf(), imb_freerectfloatImBuf(), imb_freerectImBuf(), imb_freetilesImBuf(), IMB_freezbuffloatImBuf(), IMB_freezbufImBuf(), imb_global_cache_tile_unload(), IMB_index_builder_create(), IMB_index_builder_finish(), IMB_indexer_close(), imb_load_dpx_cineon(), imb_loadhdr(), imb_loadiris(), imb_loadpng(), imb_loadtarga(), IMB_mask_filter_extend(), IMB_metadata_change_field(), IMB_metadata_del_field(), IMB_metadata_free(), IMB_moviecache_free(), IMB_moviecache_get_cache_segments(), IMB_moviecache_put(), imb_save_dpx_cineon(), imb_savepng(), IMB_scalefastImBuf(), implicit_free(), implicit_solver(), index_rebuild_fallback_finish(), indexer_dv_delete(), init_actuator(), init_controller(), init_glow_effect(), init_iconfile_list(), init_mv_jit(), init_property(), init_render_curve(), init_render_mesh(), init_render_surf(), init_sensor(), init_solid_color(), init_speed_effect(), init_transform_effect(), init_wipe_effect(), initialize_all_particles(), initialize_chain(), initialize_posetree(), initMouseInputMode(), insert_bezt_fcurve(), insert_key_button_exec(), insert_text_exec(), interp_sparse_array(), ipo_to_animato(), is_track_clean(), isb_add_samples(), isb_add_samples_transp(), ISB_free(), isb_make_buffer(), isb_make_buffer_transp(), itasc_clear_data(), join_mesh_exec(), jpegmemdestmgr_term_destination(), jpegmemsrcmgr_term_source(), keyIndex_delCV(), keyIndex_delNurb(), keymap_item_free(), knife_add_cut(), knife_cut_through(), knife_edge_tri_isect(), knife_find_line_hits(), knifetool_exit(), KX_Dome::KX_Dome(), laplacian_relaxation_iteration_uv(), laplacian_system_construct_end(), laplacian_system_delete(), latt_to_key(), layerFree_mdeformvert(), layerFree_mdisps(), layerInterp_mdeformvert(), layerSwap_mdisps(), lib_link_particlesystems(), lib_link_scene(), link_logicbricks(), linklist_free_simple(), list_find_data_fcurves(), list_item_row(), load_editLatt(), load_editText(), load_frame_raw8(), load_tex(), loggerwindow_free(), logic_buttons(), logic_buttons_new(), loop_find_regions(), M_Geometry_interpolate_bezier(), main(), mainwindow_free(), make_edges_mdata(), make_new_animlistelem(), make_new_line(), make_occ_tree(), make_orco_surf(), make_proxy_exec(), make_sample_tables(), make_segment_exec(), make_structDNA(), make_trans_verts(), make_unique_prop_names(), makeBevelList(), makedeepshadowbuf(), makeDispListCurveTypes(), makeflatshadowbuf(), makeknots(), makeNurbcurve(), makeNurbfaces(), material_append_id(), material_pop_id(), max_undo_test(), mem_element_reset(), MEM_reallocN(), memdbl(), menudata_add_item(), menudata_free(), merge_2_nurb(), mesh_calc_modifiers(), mesh_calc_normals(), mesh_calc_normals_mapping_ex(), mesh_calc_normals_tessface(), mesh_create_derived_for_modifier(), mesh_deform_bind(), mesh_get_x_mirror_faces(), mesh_octree_free_node(), mesh_octree_table(), mesh_strip_loose_edges(), mesh_strip_loose_polysloops(), mesh_to_curve(), mesh_to_key(), meshdeform_bind_exec(), meshdeform_bind_floodfill(), meshdeform_matrix_solve(), meshdeformModifier_do(), metaball_polygonize(), minimize_stretch_exit(), minmax_verts(), modifier_apply_obdata(), modifier_free(), modifier_freeTemporaryData(), modifier_mdef_compact_influences(), modifier_setError(), modifiers_clearErrors(), mouse_action_keys(), mouse_graph_keys(), mouse_nla_strips(), moveCloserToDistanceFromPlane(), multiple_scattering_diffusion(), multires_apply_smat(), multires_del_higher(), multires_dm_create_from_derived(), multires_free(), multires_free_level(), multires_load_old_dm(), multires_mdisps_subdivide_hidden(), multires_modifier_update_hidden(), multires_modifier_update_mdisps(), multires_reallocate_mdisps(), multires_stitch_grids(), multires_subdivide(), multiresbake_freejob(), multiresModifier_base_apply(), multiresModifier_reshapeFromDeformMod(), multitestapp_free(), navmesh_create_exec(), new_particle_duplilist(), new_pgn_element(), NewBooleanMesh(), nla_free(), nlastrip_evaluate_meta(), node_composit_exec_composite(), node_composit_exec_doubleedgemask(), node_composit_exec_zcombine(), node_composit_get_image(), node_composit_get_movieclip(), node_free_standard_storage(), node_group_make_from_selected(), node_group_remove_socket(), node_group_ungroup(), node_init_preview(), node_link_cancel(), node_link_invoke(), node_link_modal(), node_resize_cancel(), node_resize_modal(), node_shader_buts_dynamic(), node_socket_free_default_value(), nodeFreeNode(), nodeFreePreview(), nodeRemLink(), nodeRemoveSocket(), ntree_exec_begin(), ntree_exec_end(), ntreeCompositOutputFileRemoveActiveSocket(), ntreeLocalMerge(), ntreeShaderEndExecTree(), ntreeTexEndExecTree(), object_hook_assign_exec(), object_make_proxy(), object_remove_material_slot(), object_sculpt_modifiers_changed(), object_shape_key_mirror(), occ_compute_bounces(), occ_compute_passes(), occ_free_tree(), occ_tree_build(), oceanbake_free(), old_mdisps_convert(), oldnewmap_free(), oldnewmap_free_unused(), oldnewmap_insert(), open_cancel(), open_exec(), open_plugin_seq(), open_plugin_tex(), operator delete(), operator_enum_search_cb(), operatortype_ghash_free_cb(), outliner_filter_tree(), outliner_free(), outliner_free_tree(), outliner_sort(), outliner_storage_cleanup(), output_iris(), p_abf_free_system(), p_chart_convex_hull(), p_chart_delete(), p_chart_lscm_end(), p_chart_minimum_area_angle(), p_connect_pairs(), p_node_delete(), p_node_new(), p_smooth(), p_smooth_median_edge_length(), paint_exec(), paint_exit(), paint_invoke(), paint_stroke_cancel(), paint_stroke_exec(), paint_stroke_free(), paint_stroke_modal(), panel_activate_state(), param_delete(), param_pack(), partialvis_update_grids(), particles_fluid_step(), paste_driver_button_exec(), paste_file(), paste_file_exec(), paste_matcopybuf(), pbvh_build(), pbvh_iter_end(), pbvh_stack_push(), pbvh_update_normals(), pdEndEffectors(), PE_free_ptcache_edit(), PE_mirror_particle(), PE_mirror_x(), PE_undo_push(), permutate(), phash_delete(), phash_insert(), pose_clear_user_transforms_exec(), pose_grab_with_ik_clear(), pose_proxy_synchronize(), pose_select_same_group(), pose_select_same_keyingset(), pose_slide_apply_quat(), pose_slide_apply_vec3(), pose_slide_exit(), poseAnim_mapping_free(), poselib_backup_free_data(), poselib_preview_cleanup(), postTrans(), posttrans_fcurve_clean(), preprocess_include(), project_paint_end(), proxy_freejob(), psys_calc_dmcache(), psys_check_boid_data(), psys_check_enabled(), psys_free(), psys_free_children(), psys_free_particles(), psys_free_path_cache_buffers(), psys_free_pdd(), psys_free_settings(), psys_render_restore(), psys_render_simplify_distribution(), psys_reset(), psys_threads_free(), ptcache_data_free(), ptcache_disk_frame_to_mem(), ptcache_dynamicpaint_write(), ptcache_extra_free(), ptcache_file_close(), ptcache_file_compressed_read(), ptcache_file_compressed_write(), ptcache_interpolate(), ptcache_mem_frame_to_disk(), ptcache_particle_extra_read(), ptcache_read(), ptcache_write(), PyC_FlagSet_ValueFromID(), pycon_free(), pyop_as_string(), pyop_call(), pyop_poll(), pyrna_dir_members_rna(), pyrna_enum_as_string(), pyrna_enum_to_py(), pyrna_enum_value_from_id(), pyrna_func_call(), pyrna_func_doc_get(), pyrna_prop_collection_find(), pyrna_prop_collection_items(), pyrna_prop_collection_keys(), pyrna_prop_path_from_id(), pyrna_prop_repr(), pyrna_prop_str(), pyrna_prop_to_enum_bitfield(), pyrna_prop_to_py(), pyrna_string_to_enum(), pyrna_struct_dealloc(), pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_keyframe_delete(), pyrna_struct_keyframe_insert(), pyrna_struct_path_from_id(), pyrna_struct_repr(), pyrna_struct_str(), python_script_exec(), QMC_freeSampler(), quad_4edge_subdivide(), queue_delete(), radial_control_cancel(), radial_control_get_path(), radial_control_invoke(), radial_control_set_tex(), RE_bake_shade_all_selected(), RE_Database_Free(), RE_Database_FromScene_Vectors(), RE_engine_free(), RE_engine_update_stats(), RE_engines_exit(), RE_findOrAddHalo(), RE_findOrAddStrand(), RE_findOrAddVert(), RE_findOrAddVlak(), RE_free_sample_material(), RE_FreeRender(), RE_rayobject_blibvh_free(), RE_rayobject_instance_free(), RE_rayobject_octree_done(), RE_rayobject_octree_free(), RE_strandren_get_mcol(), RE_strandren_get_uv(), RE_vlakren_get_mcol(), RE_vlakren_get_tface(), RE_zbuf_accumulate_vecblur(), read_file_data(), read_file_version(), read_global(), read_libraries(), read_voxeldata_header(), readBitmapFontVersion0(), realloc_particles(), recalc_emitter_field(), recursive_operation(), recursive_tree_free_nodes(), REEB_freeArc(), REEB_freeGraph(), region_quadview_exec(), region_scale_cancel(), region_scale_modal(), BOP_Mesh::rehashVertex(), rekey_particle(), rekey_particle_to_time(), remake_graph_transdata(), remove_driver_button_exec(), remove_fmodifier(), remove_keyingset_button_exec(), remove_particle_dupliob_exec(), remove_particle_target_exec(), remove_tagged_keys(), remove_tagged_particles(), removedouble_scredges(), removedouble_scrverts(), removeDoublesPeel(), removenotused_scredges(), removenotused_scrverts(), render_freejob(), render_new_particle_system(), render_result_free(), render_result_rect_from_ibuf(), reopen_text(), replace_if_different(), report_copy_exec(), report_delete_exec(), reports_to_text_exec(), KX_BlenderSceneConverter::ResetPhysicsObjectsAnimationIpo(), resize_object_material(), resizelattice(), restore_localviewdata(), retargetArctoArcAggresive(), rewrite_path_alloc(), RIG_freeRigGraph(), RIG_removeUneededOffsets(), ringsel_exit(), ringsel_find_edge(), rna_def_property_get_func(), rna_def_property_set_func(), RNA_define_free(), RNA_enum_is_equal(), RNA_enum_item_add(), RNA_free(), rna_freelinkN(), rna_freelistN(), rna_generate_property(), rna_get_fcurve(), rna_idp_path_create(), rna_idproperty_check(), rna_iterator_array_end(), rna_iterator_listbase_end(), RNA_parameter_list_free(), RNA_path_back(), RNA_path_from_ID_to_property(), rna_path_rename_fix(), RNA_path_resolve_full(), RNA_pointer_as_string(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), RNA_property_boolean_get_default_index(), RNA_property_boolean_get_index(), RNA_property_boolean_set_index(), RNA_property_collection_add(), RNA_property_collection_lookup_string(), RNA_property_copy(), RNA_property_enum_bitflag_identifiers(), RNA_property_enum_identifier(), RNA_property_enum_name(), RNA_property_enum_value(), RNA_property_float_get_array_range(), RNA_property_float_get_default_index(), RNA_property_float_get_index(), RNA_property_float_set_index(), RNA_property_int_get_array_range(), RNA_property_int_get_default_index(), RNA_property_int_get_index(), RNA_property_int_set_index(), RNA_property_path_from_ID_check(), RNA_property_pointer_remove(), RNA_property_reset(), rna_raw_access(), rna_search_cb(), rna_sortlist(), RNA_struct_idprops_unset(), rng_free(), rotate_direction_nurb(), rtbuild_free(), rtbuild_heuristic_object_split(), rule_avoid_collision(), rule_del_exec(), rule_fight(), rule_separate(), RVBlurBitmap2_byte(), RVBlurBitmap2_float(), AnimationExporter::sample_and_write_bone_animation(), sample_exit(), sample_fcurve(), sb_cf_threads_run(), SB_estimate_transform(), sb_sfesf_threads_run(), sbFree(), scaledownx(), scaledowny(), scaleupx(), scaleupy(), scanfill(), scatter_settings_free(), scatter_tree_build(), scatter_tree_free(), scene_remove_render_layer(), scopes_free(), scopes_update(), screen_delarea(), screen_opengl_render_apply(), screen_opengl_render_end(), screenshot_data_free(), screenshot_freejob(), screenshot_startjob(), scroll_exit(), scrollbar_free(), scroller_activate_exit(), sculpt_cache_free(), sculpt_combine_proxies(), sculpt_flush_stroke_deform(), sculpt_restore_mesh(), sculpt_set_persistent_base(), sculpt_undo_free(), sculpt_undo_push_end(), sculpt_undo_restore_coords(), sculpt_update_keyblock(), sculpt_update_mesh_elements(), sculpt_update_tex(), sculpt_vertcos_to_key(), select_invoke(), select_less_exec(), select_linked(), select_linked_tfaces_with_seams(), select_more_exec(), select_moreless_action_keys(), select_moreless_graph_keys(), seq_end(), seq_free_editing(), seq_free_sequence(), seq_free_strip(), seq_load_operator_info(), seq_proxy_rebuild_finish(), sequence_effect_speed_rebuild_map(), sequencer_add_image_strip_exec(), sequencer_change_path_exec(), sequencer_meta_toggle_exec(), set_brush_rc_path(), set_brush_rc_props(), set_current_lamp_texture(), set_current_material_texture(), set_current_particle_texture(), set_current_world_texture(), set_subsurf_uv(), setup_app_data(), shader_preview_free(), shadowbuf_autoclip(), shapekey_layers_to_keyblocks(), shrink_picture_byte(), shrink_picture_float(), sima_draw_alpha_pixelsf(), sima_draw_zbuffloat_pixels(), sk_filterStroke(), sk_freeStroke(), sk_growStrokeBuffer(), sk_growStrokeBufferN(), sk_retargetStroke(), sk_reverseStroke(), sk_shrinkStrokeBuffer(), sketch_draw_gesture_cancel(), sketch_draw_modal(), sketch_draw_stroke_cancel(), skip_fcurve_selected_data(), smokeModifier_copy(), smokeModifier_freeCollision(), smokeModifier_freeDomain(), smokeModifier_freeFlow(), smokeModifier_reset(), smooth_exec(), smooth_fcurve(), smoothModifier_do(), snap_curs_to_sel(), snap_sel_to_curs(), snap_sel_to_grid(), snode_autoconnect(), snode_bg_viewmove_cancel(), snode_bg_viewmove_modal(), solidify_add_thickness(), solve_camera_freejob(), sound_open_cancel(), splineik_execute_tree(), splineik_free(), splineik_init_tree_from_pchan(), sss_create_tree_mat(), sss_free_tree(), start_avi(), state_del_exec(), stitch_init(), stitch_preview_delete(), stitch_process_data(), stitch_state_delete(), strand_shade_cache_free(), strand_shade_get(), strand_shade_unref(), subdivide_particle(), subdividenurb(), surfaceGenerateGrid(), swapdata(), switchdirection_knots(), switchdirectionNurb(), system_step(), test_constraints(), test_pointer_array(), tex_free_delegates(), text_check_format_len(), text_convert_whitespace_exec(), text_cursor_set_exit(), text_find_and_replace(), text_find_set_selected_exec(), text_free_caches(), text_insert_exec(), text_make_internal_exec(), text_open_cancel(), text_open_exec(), text_paste_exec(), text_replace_set_selected_exec(), text_save_as_exec(), text_update_drawcache(), text_update_line_edited(), texttool_docs_show(), thumbnails_free(), time_cache_free(), time_draw_cache(), track_context_free(), track_markers_freejob(), tracking_reconstruction_free(), tracks_map_free(), transDataTrackingFree(), transformops_data(), transformops_exit(), tree_element_to_path(), tri_3edge_subdivide(), txt_add_object(), txt_copy_clipboard(), txt_delete_line(), txt_delete_sel(), txt_do_redo(), txt_do_undo(), txt_extended_ascii_as_utf8(), txt_insert_buf(), txt_replace_char(), txt_split_curline(), txttl_free_docs(), txttl_free_suggest(), ui_add_link(), ui_add_smart_controller(), ui_apply_but_funcs_after(), ui_apply_button(), ui_but_add_shortcut(), ui_but_anim_expression_create(), ui_but_copy_paste(), ui_but_search_test(), ui_convert_to_unit_alt_name(), ui_def_but_rna(), ui_delete_active_linkline(), ui_delete_linkline(), ui_do_but_HSVCIRCLE(), ui_do_but_HSVCUBE(), ui_free_but(), ui_free_link(), ui_get_but_string(), UI_icons_free_drawinfo(), ui_intro_button(), ui_item_array(), ui_item_enum_expand(), ui_layout_free(), ui_menu_block_set_keymaps(), ui_menu_enumpropname(), ui_popup_block_create(), ui_popup_block_free(), ui_popup_menu_create(), ui_searchbox_region_free_cb(), ui_template_id(), ui_textedit_begin(), ui_textedit_copypaste(), ui_textedit_set_cursor_pos(), ui_tooltip_create(), ui_tooltip_region_free_cb(), UI_view2d_grid_free(), UI_view2d_scrollers_free(), UI_view2d_tab_set(), uiAlignPanelStep(), uiblock_layer_pass_buttons(), uiBlockSetNFunc(), uiButSetNFunc(), uiDefBlockButN(), uiFreeBlock(), uiItemEnumO_string(), uiItemEnumR_string(), uiItemsEnumR(), uiItemsFullEnumO(), uiLayoutIntrospect(), uiPupMenuEnd(), uiPupMenuReports(), uiTemplateColorRamp(), uiTemplateCurveMapping(), uiTemplateHeader3D(), uiTemplateHistogram(), uiTemplateImage(), uiTemplateList(), uiTemplateVectorscope(), uiTemplateWaveform(), undo_history_invoke(), undoCurve_to_editCurve(), undoMesh_to_editbtMesh(), unique_name(), unlink_logicbricks(), unpackImage(), unpackSound(), unpackVFont(), update_string(), uv_from_view_exec(), uv_sculpt_stroke_exit(), uv_sculpt_stroke_init(), uvprojectModifier_do(), vcol_to_fcol(), vertcos_to_key(), vertex_duplilist(), vertex_group_sort_exec(), VertexIt_Destruct(), vgroup_blend(), vgroup_clean(), vgroup_clean_all(), vgroup_delete_all(), vgroup_delete_edit_mode(), vgroup_delete_update_users(), vgroup_do_remap(), vgroup_duplicate(), vgroup_fix(), vgroup_invert(), vgroup_levels(), vgroup_move_exec(), vgroup_normalize(), vgroup_normalize_all(), view3d_boxview_clip(), view3d_clipping_invoke(), view3d_draw_transp(), view3d_draw_xray(), view3d_draw_xraytransp(), view3d_free(), view3d_main_area_free(), view3d_smoothview_invoke(), view3d_update_depths_rect(), view3d_zoom_border_exec(), view_autodist_depth_margin(), view_pan_exit(), view_zoom_exit(), view_zoomdrag_exit(), view_zoomstep_exit(), viewops_data_free(), vol_precache_objectinstance_threads(), vpaint_stroke_done(), vtx_slide_exit(), vtx_slide_set_frame(), warpModifier_do(), waveModifier_do(), weight_paint_sample_enum_itemf(), weightvg_do_mask(), weld_align_uv(), windowdata_free(), WM_clipboard_text_set(), wm_close_and_free_all(), wm_draw_triple_free(), WM_dropbox_add(), wm_dropbox_free(), wm_event_do_notifiers(), wm_event_drag_test(), wm_event_free(), wm_event_free_handler(), WM_event_remove_timer(), WM_gesture_end(), WM_gesture_lasso_modal(), wm_handler_fileselect_call(), wm_jobs_kill_job(), wm_jobs_timer(), WM_keyconfig_free(), wm_keymap_diff_item_free(), wm_keymap_diff_update(), wm_keymap_item_free(), WM_keymap_properties_reset(), WM_keymap_remove_item(), WM_keymap_restore_item_to_default(), wm_macro_end(), WM_menutype_free(), WM_menutype_freelink(), wm_operator_finished(), WM_operator_free(), wm_operator_print(), WM_operator_properties_free(), WM_operator_pystring(), wm_operator_reports(), wm_operator_ui_popup_cancel(), wm_operatortype_free_macro(), WM_operatortype_remove(), WM_paint_cursor_end(), wm_subwindow_close(), wm_window_free(), WM_write_file(), wpaint_stroke_done(), wpaint_stroke_update_step(), write_history(), write_jpeg(), writedata_free(), xsortvert_flag(), zbuf_free_span(), zbuffer_abuf(), zbuffer_shadow(), zbuffer_solid(), zbuffer_strands_abuf(), zbuffer_transp_shade(), zbufshade_sss_free(), zbufshade_sss_tile(), zbufshade_tile(), zbufshadeDA_tile(), zmask_rect(), BL_ShapeDeformer::~BL_ShapeDeformer(), BL_Uniform::~BL_Uniform(), BOP_Mesh::~BOP_Mesh(), and RAS_MeshObject::~RAS_MeshObject().
uintptr_t MEM_get_mapped_memory_in_use (void)
Get mapped memory usage.
Definition at line 832 of file mallocn.c.
References mem_lock_thread(), mem_unlock_thread(), and mmap_in_use.
Referenced by free_imbuf_seq(), make_renderinfo_string(), stats_background(), and stats_string().
int MEM_get_memory_blocks_in_use (void)
Get amount of memory blocks in use.
Definition at line 843 of file mallocn.c.
References mem_lock_thread(), mem_unlock_thread(), and totblock.
Referenced by main(), and WM_exit_ext().
uintptr_t MEM_get_memory_in_use (void)
Memory usage stats
MEM_get_memory_in_use is all memory
MEM_get_mapped_memory_in_use is a subset of all memory
Definition at line 821 of file mallocn.c.
References mem_in_use, mem_lock_thread(), and mem_unlock_thread().
Referenced by BKE_write_undo(), MEM_CacheLimiter< MEM_CacheLimiterHandleCClass >::enforce_limits(), free_imbuf_seq(), make_renderinfo_string(), stats_background(), stats_string(), and undo_editmode_push().
uintptr_t MEM_get_peak_memory (void)
Get the peak memory usage in bytes, including mmap allocations.
Definition at line 803 of file mallocn.c.
References mem_lock_thread(), mem_unlock_thread(), and peak_mem.
Referenced by make_renderinfo_string(), and stats_background().
void* MEM_mallocN (size_t len, const char * str)
Allocate a block of memory of size len, with tag name str. The name must be a static, because only a pointer to it is stored !
Definition at line 304 of file mallocn.c.
References make_memhead_header(), malloc_debug_memset, mem_in_use, mem_lock_thread(), mem_unlock_thread(), NULL, print_error(), SIZET_ARG, and SIZET_FORMAT.
Referenced by accum_mballfaces(), add_curve(), add_empty_text(), add_memfilechunk(), add_render_lamp(), add_shapekey_layers(), add_text(), add_tface_color_layer(), add_volume(), AddNewBlenderMesh(), addNurbPoints(), addNurbPointsBezier(), addpsmain(), addpsmainA(), addpsmainAstrand(), adduplicateflagNurb(), alloc_point_data(), alloc_proxy_output_avi(), MEM_Allocator< _Tp >::allocate(), append_avi(), applyModifier(), armature_subdivide_exec(), arrayModifier_doArray(), attach_ndof_data(), avi_converter_from_avi_rgb(), avi_converter_from_mjpeg(), avi_converter_from_rgb32(), avi_converter_to_avi_rgb(), avi_converter_to_mjpeg(), avi_converter_to_rgb32(), AVI_open_compress(), AVI_open_movie(), AVI_read_frame(), AVI_write_frame(), awrite(), bevels_to_filledpoly(), BGL_MakeBuffer(), BKE_mesh_validate_arrays(), BKE_text_to_curve(), BL_Uniform::BL_Uniform(), blend_file_thumb(), blf_glyph_add(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), BLI_edgehash_insert(), BLI_edgehashIterator_new(), BLI_file_read_as_lines(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashIterator_new(), BLI_ghashutil_pairalloc(), BLI_gsqueue_new(), BLI_gsqueue_push(), BLI_gsqueue_pushback(), BLI_heap_insert(), BLI_heap_new(), BLI_initjit(), BLI_linklist_append(), BLI_linklist_insert_after(), BLI_linklist_prepend(), BLI_memarena_alloc(), BLI_mempool_alloc(), BLI_mempool_create(), BLI_pbvh_build_grids(), BLI_pbvh_build_mesh(), BLI_pbvh_node_add_proxy(), BLI_setenv(), BLI_strdupcat(), BLI_strdupn(), bli_where_am_i(), bloom_with_reference(), blur_with_reference(), BM_face_create_ngon_vcloud(), BM_mesh_bm_from_me(), BM_mesh_copy(), BM_mesh_remap(), bmo_contextual_create_exec(), bmo_create_monkey_exec(), bmo_dissolve_limit_exec(), bmo_inset_exec(), bmo_similarverts_exec(), bmo_vertexshortestpath_exec(), bokeh_single_image(), boxPack2D(), boxPack_FromPyObject(), BPy_IDArray_ass_slice(), Buffer_item(), build_Rd_table(), build_seqar_cb(), buildchar(), bvhcache_insert(), calc_colors_from_weights_array(), calc_curvepath(), calc_weightpaint_vert_array(), ccd_mesh_make(), ccgdm_create_grids(), ccgdm_getVertCos(), ccgSubSurf__allFaces(), ccgSubSurf__calcSubdivLevel(), ccgSubSurf__effectedFaceNeighbours(), ccgSubSurf__sync(), ccgSubSurf_initFullSync(), CDDM_calc_normals_mapping_ex(), cdDM_drawFacesTex_common(), check_and_compress_jpeg(), check_and_decode_jpeg(), check_persistent(), RAS_MeshObject::CheckWeightCache(), cloth_bvh_objcollisions_nearcheck(), compress_deepshadowbuf(), compress_shadowbuf(), console_insert_exec(), console_scrollback_prompt_begin(), construct_param_handle_subsurfed(), copy_dbase_object_vectors(), copy_lamp(), copy_lattice(), copy_material(), copy_text(), copy_vpaint_prev(), copy_world(), copy_wpaint_prev(), crazyspace_build_sculpt(), create_vert_poly_map(), createTransEditVerts(), createVertsTrisData(), curve_calc_modifiers_post(), curve_getKeyVertexCos(), curve_getVertexCos(), curvemap_remove(), curvemapping_premultiply(), CustomData_duplicate_referenced_layer(), CustomData_duplicate_referenced_layer_named(), dag_add_parent_relation(), dag_add_relation(), def_internal_icon(), defgroup_flip_map(), defgroup_flip_map_single(), defvert_remove_group(), delete_exec(), deleteflagNurb(), direct_link_dverts(), direct_link_text(), displist_get_allverts(), displist_surf_indices(), DNA_sdna_from_data(), do_multires_smooth_brush(), do_object_pose_box_select(), doMirrorOnAxis(), duplibase_for_convert(), duplicateEditBoneObjects(), duplicateNurb(), dynamicPaint_brushMeshCalculateVelocity(), dynamicPaint_createUVSurface(), dynamicPaint_doStep(), dynamicPaint_doWaveStep(), dynamicPaint_generateBakeData(), dynamicPaint_prepareAdjacencyData(), dynamicPaint_prepareEffectStep(), ED_area_headerprint(), ED_mesh_mirrtopo_init(), ed_preview_draw_rect(), ED_vgroup_copy_array(), ED_vgroup_give_parray(), ED_view3d_depth_update(), edbm_bevel_exec(), EDBM_index_arrays_init(), edbm_knife_cut_exec(), edbm_loop_multiselect_exec(), edbm_sort_faces_exec(), EDBM_uv_element_map_create(), edgetag_shortest_path(), editbmesh_calc_modifiers(), editbmesh_get_vertex_cos(), enum_items_from_py(), execute_posetree(), extrudeflagNurb(), FaceIt_Construct(), filelist_from_main(), fill_metaball_octal_node(), filldisplist(), folderlist_pushdir(), fsmenu_insert_entry(), fwritecolrs(), gen_lock_flags(), get_bhead(), get_builtin_packedfile(), get_editbmesh_orco_verts(), get_indexarray(), get_part_from_ibuf(), getCCGDerivedMesh(), getEditDerivedBMesh(), gp_stroke_newfrombuffer(), GPU_buffer_alloc(), gpu_buffer_setup(), GPU_drawobject_new(), GPU_paint_update_image(), GPU_shader_export(), GPU_verify_image(), group_sort_exec(), hashvert_flag(), ibuftoimage(), IDP_CopyIDPArray(), IDP_New(), image_save_as_invoke(), imb_addencodedbufferImBuf(), imb_enlargeencodedbufferImBuf(), IMB_flipy(), IMB_float_profile_ensure(), imb_load_dpx_cineon(), imb_loadhdr(), imb_loadiris(), imb_loadpng(), imb_save_dpx_cineon(), imb_savepng(), IMB_scalefastImBuf(), init_ao_sphere(), init_camera_inside_volumes(), init_latt_deform(), init_metaball_octal_tree(), init_mv_jit(), init_undo_text(), initlocalview(), initTransDataCurveHandles(), isb_add_samples(), isb_add_samples_transp(), jpegmemdestmgr_build(), jpegmemsrcmgr_build(), lattice_getVertexCos(), load_editLatt(), load_frame_raw8(), load_tex(), localize_lamp(), localize_material(), localize_world(), loggerwindow_new(), main(), make_bloomtab(), make_edges_mdata(), make_editLatt(), make_gausstab(), make_jitter_weight_tab(), make_links_scene_exec(), make_orco_curve(), make_orco_mball(), make_sample_tables(), make_segment_exec(), make_solid_mask(), makebevelcurve(), makeBevelList(), makeNurbcurve(), makeNurbfaces(), mallocN(), mallocT(), MEM_dupallocN(), MEM_reallocN(), memdbl(), menudata_add_item(), menudata_new(), merge_2_nurb(), mesh_calc_modifiers(), mesh_faces_to_scratch(), mesh_getVertexCos(), mesh_strip_loose_edges(), mesh_strip_loose_polysloops(), metaball_polygonize(), moveCloserToDistanceFromPlane(), multires_apply_smat(), multiresModifier_base_apply(), multitestapp_new(), NewBooleanMesh(), newPackedFile(), node_composit_exec_doubleedgemask(), node_composit_exec_zcombine(), object_add_duplicate_internal(), object_duplilist(), object_tfm_backup(), ocean_bake_exec(), oldnewmap_insert(), oldnewmap_new(), open_plugin_seq(), open_plugin_tex(), operator new(), outliner_sort(), outliner_storage_cleanup(), output_iris(), p_abf_setup_system(), p_chart_convex_hull(), p_chart_minimum_area_angle(), p_connect_pairs(), p_node_new(), p_smooth(), p_smooth_median_edge_length(), p_split_charts(), param_pack(), paste_mtex_copybuf(), pchan_b_bone_defmats(), permutate(), preprocess_include(), project_camera_info(), project_paint_begin(), psys_copy_settings(), ptcache_file_open(), push_queue(), push_stack(), pyop_call(), python_script_exec(), q_scale_linear_interpolation(), queue_create(), RE_findOrAddStrand(), RE_findOrAddVert(), RE_findOrAddVlak(), RE_vertren_get_sticky(), RE_vertren_get_strand(), RE_vertren_get_stress(), read_file_data(), read_struct(), read_voxeldata_header(), readBitmapFontVersion0(), reference_to_scratch(), BOP_Mesh::rehashVertex(), render_new_particle_system(), render_result_rect_from_ibuf(), renew_softbody(), reopen_text(), replace_if_different(), resizelattice(), return_editcurve_indexar(), return_editlattice_indexar(), return_editmesh_indexar(), rna_generate_property(), RNA_property_as_string(), RNA_property_float_get_array_range(), RNA_property_int_get_array_range(), RNA_property_string_get_alloc(), rna_sortlist(), rng_new(), rtbuild_create(), rtbuild_heuristic_object_split(), RVBlurBitmap2_byte(), RVBlurBitmap2_float(), scaledownx(), scaledowny(), scalefast_Z_ImBuf(), scaleupx(), scaleupy(), screen_opengl_render_apply(), screenshot(), screenshot_updatejob(), sculpt_update_cache_invariants(), select_linked(), seq_array(), sequencer_meta_toggle_exec(), set_subsurf_uv(), shapekey_layers_to_keyblocks(), sima_draw_alpha_pixelsf(), sima_draw_zbuffloat_pixels(), smooth_view(), snode_autoconnect(), sort_bhead_old_map(), sss_create_tree_mat(), start_avi(), stitch_init(), stitch_preview_init(), stitch_process_data(), string_dup(), subdivide_metaball_octal_node(), subdividenurb(), swapdata(), switchdirection_knots(), switchdirectionNurb(), test_pointer_array(), tex_output(), text_check_format_len(), texttool_docs_show(), texttool_suggest_add(), txt_add_char_intern(), txt_add_marker(), txt_combine_lines(), txt_comment(), txt_delete_sel(), txt_do_redo(), txt_do_undo(), txt_extended_ascii_as_utf8(), txt_indent(), txt_new_line(), txt_new_linen(), txt_replace_char(), txt_sel_to_buf(), txt_split_curline(), txt_to_buf(), ui_def_but(), uiBeginBlock(), unique_name(), update_tablet_data(), uv_sculpt_stroke_init(), vcol_to_fcol(), VertexIt_Construct(), vfont_get_data(), vgroup_delete_update_users(), vgroup_do_remap(), vgroup_init_remap(), view3d_update_depths_rect(), warpModifier_do(), waveModifier_do(), weightvg_do_mask(), windowdata_new(), wm_operator_create(), WM_read_history(), wpaint_make_validmap(), wpaint_stroke_update_step(), write_history(), write_jpeg(), writedata_new(), xsortvert_flag(), zbuf_alloc_span(), zbuffer_abuf(), zbuffer_shadow(), zbuffer_solid(), zbuffer_strands_abuf(), zbufshade_sss_tile(), zbufshade_tile(), and zbufshadeDA_tile().
void* MEM_mapallocN (size_t len, const char * str)
Same as callocN, clears memory and uses mmap (disk cached) if supported. Can be free'd with MEM_freeN as usual.
Definition at line 358 of file mallocn.c.
References len(), make_memhead_header(), MAP_ANON, MAP_SHARED, MEM_callocN(), mem_lock_thread(), mem_unlock_thread(), MemHead::mmap, mmap(), mmap_in_use, NULL, peak_mem, print_error(), PROT_READ, PROT_WRITE, SIZET_ARG, and SIZET_FORMAT.
Referenced by addzbuffloatImBuf(), addzbufImBuf(), alloc_compbuf(), do_idmask(), do_merge_fullsample(), do_write_image_or_movie(), image_undo_push_tile(), imb_addrectfloatImBuf(), imb_addrectImBuf(), imb_exr_begin_read_mem(), IMB_tiles_to_rect(), init_frame_smoke(), load_frame_blendervoxel(), load_frame_image_sequence(), load_frame_raw8(), makeflatshadowbuf(), MEM_dupallocN(), node_composit_get_float_buffer(), RE_zbuf_accumulate_vecblur(), render_layer_add_pass(), render_result_new(), sculpt_undo_alloc_and_store_hidden(), and sculpt_undo_alloc_node().
const char* MEM_name_ptr (void * vmemh)
Definition at line 855 of file mallocn.c.
References MemHead::name.
void MEM_printmemlist (void)
Print a list of the names and sizes of all allocated memory blocks.
Definition at line 574 of file mallocn.c.
References MEM_printmemlist_internal().
Referenced by main(), and WM_exit_ext().
void MEM_printmemlist_pydict (void)
Print a list of the names and sizes of all allocated memory blocks. as a python dict for easy investigation
Definition at line 577 of file mallocn.c.
References MEM_printmemlist_internal().
Referenced by KX_BlenderSceneConverter::PrintStats().
void MEM_printmemlist_stats (void)
Print statistics about memory usage
Definition at line 417 of file mallocn.c.
References compare_len(), compare_name(), localListBase::first, MemPrintBlock::items, MemHead::len, MemPrintBlock::len, mem_in_use, mem_lock_thread(), mem_unlock_thread(), MEMNEXT, MemHead::name, MemPrintBlock::name, MemHead::next, and totblock.
Referenced by memory_statistics_exec(), and RE_Database_Free().
void* MEM_reallocN (void * vmemh, size_t len)
Reallocates a block of memory, and returns pointer to the newly allocated block, the old one is freed. this is not as optimized as a system realloc but just makes a new allocation and copies over from existing memory.
Definition at line 259 of file mallocn.c.
References MemHead::len, MEM_freeN(), MEM_mallocN(), MemHead::name, and NULL.
Referenced by add_collision_object(), BKE_tracking_clear_path(), BKE_tracking_delete_marker(), BKE_tracking_insert_marker(), BLI_file_ungzip_to_mem(), BLI_pbvh_node_add_proxy(), ccgSubSurf_syncFace(), file_browse_exec(), gp_stroke_addpoint(), GPU_buffer_free(), join_dirfile_alloc(), knife_find_line_hits(), mesh_recalcTessellation(), sph_spring_add(), sph_spring_delete(), surfaceGenerateGrid(), and text_update_drawcache().
void MEM_reset_peak_memory (void)
Reset the peak memory statistic to zero.
Definition at line 814 of file mallocn.c.
References mem_lock_thread(), mem_unlock_thread(), and peak_mem.
Referenced by RE_BlenderFrame().
void MEM_set_error_callback (void(*)(const char *) func)
Set the callback function for error output.
Definition at line 211 of file mallocn.c.
References error_callback.
Referenced by main(), and setCallbacks().
void MEM_set_lock_callback (void(*)(void) lock, void(*)(void) unlock)
Set thread locking functions for safe memory allocation from multiple threads, pass NULL pointers to disable thread locking again.
Definition at line 216 of file mallocn.c.
References thread_lock_callback, and thread_unlock_callback.
Referenced by BLI_begin_threaded_malloc(), BLI_end_threaded_malloc(), BLI_end_threads(), and BLI_init_threads().
void MEM_set_memory_debug (void)
Attempt to enforce OSX (or other OS's) to have malloc and stack nonzero
Definition at line 222 of file mallocn.c.
References malloc_debug_memset.
Referenced by debug_mode(), and main().
short MEM_testN (void * vmemh)
Return zero if memory is not in allocated list
Definition at line 549 of file mallocn.c.
References localListBase::first, mem_lock_thread(), mem_unlock_thread(), MEMNEXT, MemHead::next, and print_error().