Blender: CacheData Class Reference
CacheData Class Reference
#include <util_cache.h>
Public Member Functions
CacheData (const string &name="")
~CacheData ()
const string & get_filename ()
template<typename T >
void add (const vector< T > &data)
template<typename T >
void add (const array< T > &data)
void add (void *data, size_t size)
void add (int &data)
void add (float &data)
void add (size_t &data)
template<typename T >
void read (array< T > &data)
void read (int &data)
void read (float &data)
void read (size_t &data)
Public Attributes
vector< CacheBuffer > buffers
string name
string filename
bool have_filename
FILE * f
Detailed Description
Definition at line 50 of file util_cache.h.
Constructor & Destructor Documentation
CCL_NAMESPACE_BEGIN CacheData::CacheData (const string & name = "")
Definition at line 38 of file util_cache.cpp.
References f, have_filename, name, and NULL.
CacheData::~CacheData ()
Definition at line 45 of file util_cache.cpp.
References f.
Member Function Documentation
template<typename T > void CacheData::add (const vector< T > & data) [inline]
Definition at line 63 of file util_cache.h.
References buffers, NULL, and T.
Referenced by BVH::cache_read(), and BVH::cache_write().
void CacheData::add (void * data, size_t size) [inline]
Definition at line 75 of file util_cache.h.
References buffers.
void CacheData::add (int & data) [inline]
Definition at line 83 of file util_cache.h.
References buffers.
template<typename T > void CacheData::add (const array< T > & data) [inline]
Definition at line 69 of file util_cache.h.
References buffers, NULL, array< T >::size(), and T.
void CacheData::add (float & data) [inline]
Definition at line 89 of file util_cache.h.
References buffers.
void CacheData::add (size_t & data) [inline]
Definition at line 95 of file util_cache.h.
References buffers.
const string & CacheData::get_filename ()
Definition at line 51 of file util_cache.cpp.
References MD5Hash::append(), buffers, CacheBuffer::data, filename, MD5Hash::get_hex(), hash, have_filename, name, and CacheBuffer::size.
Referenced by BVH::cache_read(), BVH::cache_write(), and Cache::data_filename().
void CacheData::read (size_t & data) [inline]
Definition at line 141 of file util_cache.h.
References f, and size().
void CacheData::read (float & data) [inline]
Definition at line 131 of file util_cache.h.
References f, and size().
template<typename T > void CacheData::read (array< T > & data) [inline]
Definition at line 101 of file util_cache.h.
References f, array< T >::resize(), size(), and T.
Referenced by BVH::cache_read().
void CacheData::read (int & data) [inline]
Definition at line 121 of file util_cache.h.
References f, and size().
Member Data Documentation
vector<CacheBuffer> CacheData::buffers
Definition at line 52 of file util_cache.h.
Referenced by add(), get_filename(), and Cache::insert().
FILE* CacheData::f
Definition at line 56 of file util_cache.h.
Referenced by CacheData(), Cache::lookup(), read(), and ~CacheData().
string CacheData::filename
Definition at line 54 of file util_cache.h.
Referenced by get_filename().
bool CacheData::have_filename
Definition at line 55 of file util_cache.h.
Referenced by CacheData(), and get_filename().
string CacheData::name
Definition at line 53 of file util_cache.h.
Referenced by CacheData(), get_filename(), and Cache::lookup().
The documentation for this class was generated from the following files:
util_cache.h
util_cache.cpp