Blender: svm_mix.h File Reference
svm_mix.h File Reference
#include "svm_hsv.h"
Functions
CCL_NAMESPACE_BEGIN __device float3 svm_lerp (const float3 a, const float3 b, float t)
__device float3 svm_mix_blend (float t, float3 col1, float3 col2)
__device float3 svm_mix_add (float t, float3 col1, float3 col2)
__device float3 svm_mix_mul (float t, float3 col1, float3 col2)
__device float3 svm_mix_screen (float t, float3 col1, float3 col2)
__device float3 svm_mix_overlay (float t, float3 col1, float3 col2)
__device float3 svm_mix_sub (float t, float3 col1, float3 col2)
__device float3 svm_mix_div (float t, float3 col1, float3 col2)
__device float3 svm_mix_diff (float t, float3 col1, float3 col2)
__device float3 svm_mix_dark (float t, float3 col1, float3 col2)
__device float3 svm_mix_light (float t, float3 col1, float3 col2)
__device float3 svm_mix_dodge (float t, float3 col1, float3 col2)
__device float3 svm_mix_burn (float t, float3 col1, float3 col2)
__device float3 svm_mix_hue (float t, float3 col1, float3 col2)
__device float3 svm_mix_sat (float t, float3 col1, float3 col2)
__device float3 svm_mix_val (float t, float3 col1, float3 col2)
__device float3 svm_mix_color (float t, float3 col1, float3 col2)
__device float3 svm_mix_soft (float t, float3 col1, float3 col2)
__device float3 svm_mix_linear (float t, float3 col1, float3 col2)
__device float3 svm_mix (NodeMix type, float fac, float3 c1, float3 c2)
__device void svm_node_mix (KernelGlobals *kg, ShaderData *sd, float *stack, uint fac_offset, uint c1_offset, uint c2_offset, int *offset)
Function Documentation
CCL_NAMESPACE_BEGIN __device float3 svm_lerp (const float3 a, const float3 b, float t)
Definition at line 23 of file svm_mix.h.
Referenced by svm_mix_add(), svm_mix_blend(), svm_mix_color(), svm_mix_diff(), svm_mix_hue(), svm_mix_mul(), and svm_mix_sub().
__device float3 svm_mix (NodeMix type, float fac, float3 c1, float3 c2)
Definition at line 279 of file svm_mix.h.
References clamp, make_float3(), NODE_MIX_ADD, NODE_MIX_BLEND, NODE_MIX_BURN, NODE_MIX_COLOR, NODE_MIX_DARK, NODE_MIX_DIFF, NODE_MIX_DIV, NODE_MIX_DODGE, NODE_MIX_HUE, NODE_MIX_LIGHT, NODE_MIX_LINEAR, NODE_MIX_MUL, NODE_MIX_OVERLAY, NODE_MIX_SAT, NODE_MIX_SCREEN, NODE_MIX_SOFT, NODE_MIX_SUB, NODE_MIX_VAL, svm_mix_add(), svm_mix_blend(), svm_mix_burn(), svm_mix_color(), svm_mix_dark(), svm_mix_diff(), svm_mix_div(), svm_mix_dodge(), svm_mix_hue(), svm_mix_light(), svm_mix_linear(), svm_mix_mul(), svm_mix_overlay(), svm_mix_sat(), svm_mix_screen(), svm_mix_soft(), svm_mix_sub(), and svm_mix_val().
Referenced by svm_node_mix().
__device float3 svm_mix_add (float t, float3 col1, float3 col2)
Definition at line 33 of file svm_mix.h.
References svm_lerp().
Referenced by svm_mix().
__device float3 svm_mix_blend (float t, float3 col1, float3 col2)
Definition at line 28 of file svm_mix.h.
References svm_lerp().
Referenced by svm_mix().
__device float3 svm_mix_burn (float t, float3 col1, float3 col2)
Definition at line 144 of file svm_mix.h.
References float3::x, float3::y, and float3::z.
Referenced by svm_mix().
__device float3 svm_mix_color (float t, float3 col1, float3 col2)
Definition at line 230 of file svm_mix.h.
References hsv_to_rgb(), rgb_to_hsv(), svm_lerp(), float3::x, and float3::y.
Referenced by svm_mix().
__device float3 svm_mix_dark (float t, float3 col1, float3 col2)
Definition at line 99 of file svm_mix.h.
References min.
Referenced by svm_mix().
__device float3 svm_mix_diff (float t, float3 col1, float3 col2)
Definition at line 94 of file svm_mix.h.
References fabs(), and svm_lerp().
Referenced by svm_mix().
__device float3 svm_mix_div (float t, float3 col1, float3 col2)
Definition at line 81 of file svm_mix.h.
References float3::x, float3::y, and float3::z.
Referenced by svm_mix().
__device float3 svm_mix_dodge (float t, float3 col1, float3 col2)
Definition at line 109 of file svm_mix.h.
References float3::x, float3::y, and float3::z.
Referenced by svm_mix().
__device float3 svm_mix_hue (float t, float3 col1, float3 col2)
Definition at line 183 of file svm_mix.h.
References hsv_to_rgb(), rgb_to_hsv(), svm_lerp(), float3::x, and float3::y.
Referenced by svm_mix().
__device float3 svm_mix_light (float t, float3 col1, float3 col2)
Definition at line 104 of file svm_mix.h.
References max.
Referenced by svm_mix().
__device float3 svm_mix_linear (float t, float3 col1, float3 col2)
Definition at line 257 of file svm_mix.h.
References float3::x, float3::y, and float3::z.
Referenced by svm_mix().
__device float3 svm_mix_mul (float t, float3 col1, float3 col2)
Definition at line 38 of file svm_mix.h.
References svm_lerp().
Referenced by svm_mix().
__device float3 svm_mix_overlay (float t, float3 col1, float3 col2)
Definition at line 52 of file svm_mix.h.
References float3::x, float3::y, and float3::z.
Referenced by svm_mix().
__device float3 svm_mix_sat (float t, float3 col1, float3 col2)
Definition at line 200 of file svm_mix.h.
References hsv_to_rgb(), rgb_to_hsv(), and float3::y.
Referenced by svm_mix().
__device float3 svm_mix_screen (float t, float3 col1, float3 col2)
Definition at line 43 of file svm_mix.h.
References make_float3().
Referenced by svm_mix().
__device float3 svm_mix_soft (float t, float3 col1, float3 col2)
Definition at line 247 of file svm_mix.h.
References make_float3().
Referenced by svm_mix().
__device float3 svm_mix_sub (float t, float3 col1, float3 col2)
Definition at line 76 of file svm_mix.h.
References svm_lerp().
Referenced by svm_mix().
__device float3 svm_mix_val (float t, float3 col1, float3 col2)
Definition at line 218 of file svm_mix.h.
References hsv_to_rgb(), rgb_to_hsv(), and float3::z.
Referenced by svm_mix().
__device void svm_node_mix (KernelGlobals * kg, ShaderData * sd, float * stack, uint fac_offset, uint c1_offset, uint c2_offset, int * offset)
Definition at line 309 of file svm_mix.h.
References read_node(), stack_load_float(), stack_load_float3(), stack_store_float3(), svm_mix(), uint4::y, and uint4::z.
Referenced by svm_eval_nodes().