Blender: GHOST_DropTargetWin32 Class Reference
GHOST_DropTargetWin32 Class Reference
#include <GHOST_DropTargetWin32.h>
Public Member Functions
HRESULT __stdcall QueryInterface (REFIID riid, void **ppvObj)
ULONG __stdcall AddRef (void)
ULONG __stdcall Release (void)
HRESULT __stdcall DragEnter (IDataObject *pDataObject, DWORD grfKeyState, POINTL pt, DWORD *pdwEffect)
HRESULT __stdcall DragOver (DWORD grfKeyState, POINTL pt, DWORD *pdwEffect)
HRESULT __stdcall DragLeave (void)
HRESULT __stdcall Drop (IDataObject *pDataObject, DWORD grfKeyState, POINTL pt, DWORD *pdwEffect)
GHOST_DropTargetWin32 (GHOST_WindowWin32 *window, GHOST_SystemWin32 *system)
~GHOST_DropTargetWin32 ()
Detailed Description
Definition at line 40 of file GHOST_DropTargetWin32.h.
Constructor & Destructor Documentation
GHOST_DropTargetWin32::GHOST_DropTargetWin32 (GHOST_WindowWin32 * window, GHOST_SystemWin32 * system)
Constructor With the modifier keys, we want to distinguish left and right keys. Sometimes this is not possible (Windows ME for instance). Then, we want events generated for both keys.
Parameters:
window The window to register as drop target.
system The associated system.
Definition at line 46 of file GHOST_DropTargetWin32.cpp.
References GHOST_WindowWin32::getHWND(), and GHOST_kDragnDropTypeUnknown.
GHOST_DropTargetWin32::~GHOST_DropTargetWin32 ()
Destructor Do NOT destroy directly. Use Release() instead to make COM happy.
Definition at line 59 of file GHOST_DropTargetWin32.cpp.
Member Function Documentation
ULONG __stdcall GHOST_DropTargetWin32::AddRef (void)
Definition at line 93 of file GHOST_DropTargetWin32.cpp.
Referenced by QueryInterface().
HRESULT __stdcall GHOST_DropTargetWin32::DragEnter (IDataObject * pDataObject, DWORD grfKeyState, POINTL pt, DWORD * pdwEffect)
Definition at line 119 of file GHOST_DropTargetWin32.cpp.
References GHOST_kEventDraggingEntered, NULL, GHOST_SystemWin32::pushDragDropEvent(), S_OK, and GHOST_Window::setAcceptDragOperation().
HRESULT __stdcall GHOST_DropTargetWin32::DragLeave (void)
Definition at line 151 of file GHOST_DropTargetWin32.cpp.
References GHOST_kDragnDropTypeUnknown, GHOST_kEventDraggingExited, NULL, GHOST_SystemWin32::pushDragDropEvent(), and S_OK.
HRESULT __stdcall GHOST_DropTargetWin32::DragOver (DWORD grfKeyState, POINTL pt, DWORD * pdwEffect)
Definition at line 133 of file GHOST_DropTargetWin32.cpp.
References GHOST_Window::canAcceptDragOperation(), GHOST_kEventDraggingUpdated, NULL, GHOST_SystemWin32::pushDragDropEvent(), and S_OK.
HRESULT __stdcall GHOST_DropTargetWin32::Drop (IDataObject * pDataObject, DWORD grfKeyState, POINTL pt, DWORD * pdwEffect)
Definition at line 162 of file GHOST_DropTargetWin32.cpp.
References GHOST_Window::canAcceptDragOperation(), data, GHOST_kDragnDropTypeUnknown, GHOST_kEventDraggingDropDone, GHOST_SystemWin32::pushDragDropEvent(), and S_OK.
HRESULT __stdcall GHOST_DropTargetWin32::QueryInterface (REFIID riid, void ** ppvObj)
Definition at line 68 of file GHOST_DropTargetWin32.cpp.
References AddRef(), NULL, and S_OK.
ULONG __stdcall GHOST_DropTargetWin32::Release (void)
Definition at line 101 of file GHOST_DropTargetWin32.cpp.
Referenced by GHOST_WindowWin32::~GHOST_WindowWin32().
The documentation for this class was generated from the following files:
GHOST_DropTargetWin32.h
GHOST_DropTargetWin32.cpp