Blender: util_string.h File Reference
util_string.h File Reference
#include <string.h>
#include <string>
#include <sstream>
#include "util_vector.h"
Defines
#define PRINTF_ATTRIBUTE
Functions
string string_printf (const char *format,...) PRINTF_ATTRIBUTE
bool string_iequals (const string &a, const string &b)
void string_split (vector< string > &tokens, const string &str, const string &separators="\t ")
Define Documentation
#define PRINTF_ATTRIBUTE
Definition at line 38 of file util_string.h.
Function Documentation
bool string_iequals (const string & a, const string & b)
Definition at line 67 of file util_string.cpp.
References i.
Referenced by xml_equal_string(), xml_read_bool(), xml_read_scene(), and xml_read_shader_graph().
string string_printf (const char * format, ...)
Definition at line 35 of file util_string.cpp.
References assert, and str.
Referenced by CUDADevice::compile_kernel(), CUDADevice::cuda_error(), device_cuda_info(), device_multi_add(), MeshManager::device_update(), display_info(), CUDADevice::load_kernels(), node_socket_map_pair(), BVHBuild::progress_update(), session_print_status(), CUDADevice::support_device(), and Session::update_status_time().
void string_split (vector< string > & tokens, const string & str, const string & separators = "\t ")
Definition at line 80 of file util_string.cpp.
References split().
Referenced by device_multi_add(), xml_read_float_array(), xml_read_int_array(), and xml_read_shader_graph().