Blender: uvedit_unwrap_ops.c File Reference
uvedit_unwrap_ops.c File Reference
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "DNA_camera_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_modifier_types.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BLI_edgehash.h"
#include "BLI_uvproject.h"
#include "BLI_rand.h"
#include "BLI_string.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_subsurf.h"
#include "BKE_context.h"
#include "BKE_customdata.h"
#include "BKE_depsgraph.h"
#include "BKE_image.h"
#include "BKE_main.h"
#include "BKE_mesh.h"
#include "BKE_report.h"
#include "BKE_tessmesh.h"
#include "BLI_scanfill.h"
#include "BLI_array.h"
#include "PIL_time.h"
#include "ED_image.h"
#include "ED_mesh.h"
#include "ED_screen.h"
#include "ED_uvedit.h"
#include "ED_view3d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "uvedit_intern.h"
#include "uvedit_parametrizer.h"
Classes
struct MinStretch
Defines
#define VIEW_ON_EQUATOR 0
#define VIEW_ON_POLES 1
#define ALIGN_TO_OBJECT 2
#define POLAR_ZX 0
#define POLAR_ZY 1
Typedefs
typedef struct MinStretch MinStretch
Functions
static int ED_uvedit_ensure_uvs (bContext *C, Scene *scene, Object *obedit)
static int uvedit_have_selection (Scene *scene, BMEditMesh *em, short implicit)
static ParamHandle * construct_param_handle (Scene *scene, BMEditMesh *em, short implicit, short fill, short sel, short correct_aspect)
static void texface_from_original_index (BMFace *efa, int index, float **uv, ParamBool *pin, ParamBool *select, Scene *scene, BMEditMesh *em)
static ParamHandle * construct_param_handle_subsurfed (Scene *scene, BMEditMesh *em, short fill, short sel, short correct_aspect)
static int minimize_stretch_init (bContext *C, wmOperator *op)
static void minimize_stretch_iteration (bContext *C, wmOperator *op, int interactive)
static void minimize_stretch_exit (bContext *C, wmOperator *op, int cancel)
static int minimize_stretch_exec (bContext *C, wmOperator *op)
static int minimize_stretch_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
static int minimize_stretch_modal (bContext *C, wmOperator *op, wmEvent *event)
static int minimize_stretch_cancel (bContext *C, wmOperator *op)
void UV_OT_minimize_stretch (wmOperatorType *ot)
static int pack_islands_exec (bContext *C, wmOperator *op)
void UV_OT_pack_islands (wmOperatorType *ot)
static int average_islands_scale_exec (bContext *C, wmOperator *UNUSED(op))
void UV_OT_average_islands_scale (wmOperatorType *ot)
void ED_uvedit_live_unwrap_begin (Scene *scene, Object *obedit)
void ED_uvedit_live_unwrap_re_solve (void)
void ED_uvedit_live_unwrap_end (short cancel)
void ED_uvedit_live_unwrap (Scene *scene, Object *obedit)
static void uv_map_transform_center (Scene *scene, View3D *v3d, float *result, Object *ob, BMEditMesh *em)
static void uv_map_rotation_matrix (float result[][4], RegionView3D *rv3d, Object *ob, float upangledeg, float sideangledeg, float radius)
static void uv_map_transform (bContext *C, wmOperator *op, float center[3], float rotmat[4][4])
static void uv_transform_properties (wmOperatorType *ot, int radius)
static void correct_uv_aspect (BMEditMesh *em)
static void uv_map_clip_correct_properties (wmOperatorType *ot)
static void uv_map_clip_correct (BMEditMesh *em, wmOperator *op)
void ED_unwrap_lscm (Scene *scene, Object *obedit, const short sel)
static int unwrap_exec (bContext *C, wmOperator *op)
void UV_OT_unwrap (wmOperatorType *ot)
static int uv_from_view_exec (bContext *C, wmOperator *op)
static int uv_from_view_poll (bContext *C)
void UV_OT_from_view (wmOperatorType *ot)
static int reset_exec (bContext *C, wmOperator *UNUSED(op))
void UV_OT_reset (wmOperatorType *ot)
static void uv_sphere_project (float target[2], float source[3], float center[3], float rotmat[4][4])
static void uv_map_mirror (BMEditMesh *em, BMFace *efa, MTexPoly *UNUSED(tf))
static int sphere_project_exec (bContext *C, wmOperator *op)
void UV_OT_sphere_project (wmOperatorType *ot)
static void uv_cylinder_project (float target[2], float source[3], float center[3], float rotmat[4][4])
static int cylinder_project_exec (bContext *C, wmOperator *op)
void UV_OT_cylinder_project (wmOperatorType *ot)
static int cube_project_exec (bContext *C, wmOperator *op)
void UV_OT_cube_project (wmOperatorType *ot)
Variables
static ParamHandle * liveHandle = NULL
Detailed Description
Definition in file uvedit_unwrap_ops.c.
Define Documentation
#define ALIGN_TO_OBJECT 2
Definition at line 850 of file uvedit_unwrap_ops.c.
Referenced by uv_map_transform(), and uv_transform_properties().
#define POLAR_ZX 0
Definition at line 852 of file uvedit_unwrap_ops.c.
Referenced by uv_transform_properties().
#define POLAR_ZY 1
Definition at line 853 of file uvedit_unwrap_ops.c.
Referenced by uv_map_transform(), and uv_transform_properties().
#define VIEW_ON_EQUATOR 0
Definition at line 848 of file uvedit_unwrap_ops.c.
Referenced by uv_map_transform(), and uv_transform_properties().
#define VIEW_ON_POLES 1
Definition at line 849 of file uvedit_unwrap_ops.c.
Referenced by uv_transform_properties().
Typedef Documentation
typedef struct MinStretch MinStretch
Function Documentation
static int average_islands_scale_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 759 of file uvedit_unwrap_ops.c.
References BMEdit_FromObject(), construct_param_handle(), CTX_data_edit_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, param_average(), param_delete(), param_flush(), uvedit_have_selection(), and WM_event_add_notifier().
Referenced by UV_OT_average_islands_scale().
static ParamHandle* construct_param_handle (Scene * scene, BMEditMesh * em, short implicit, short fill, short sel, short correct_aspect) [static]
Definition at line 185 of file uvedit_unwrap_ops.c.
References BLI_addfilledge(), BLI_addfillvert(), BLI_begin_edgefill(), BLI_edgefill_ex(), BLI_end_edgefill(), BLI_frand(), BLI_srand(), BMEditMesh::bm, BM_active_face_get(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_ELEM_SEAM, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_mesh_elem_index_ensure(), BM_VERT, CD_MLOOPUV, CD_MTEXPOLY, ScanFillVert::co, BMVert::co, co, CustomData_bmesh_get(), BMHeader::data, ED_image_uv_aspect(), ScanFillContext::fillfacebase, ListBase::first, MLoopUV::flag, BMLoop::head, BMFace::head, i, BMesh::ldata, BMFace::len, MLOOPUV_PINNED, ScanFillFace::next, BMFace::no, NULL, ScanFillVert::p, param_aspect_ratio(), param_construct_begin(), param_construct_end(), param_edge_set_seam(), param_face_add(), BMesh::pdata, ScanFillVert::tmp, MTexPoly::tpage, TRUE, MLoopUV::uv, uvedit_uv_select_test(), BMLoop::v, BMEdge::v1, ScanFillFace::v1, BMEdge::v2, ScanFillFace::v2, and ScanFillFace::v3.
Referenced by average_islands_scale_exec(), ED_unwrap_lscm(), ED_uvedit_live_unwrap_begin(), minimize_stretch_init(), and pack_islands_exec().
static ParamHandle* construct_param_handle_subsurfed (Scene * scene, BMEditMesh * em, short fill, short sel, short correct_aspect) [static]
Definition at line 355 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_active_face_get(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SEAM, BM_ELEM_SELECT, BM_mesh_elem_index_ensure(), BM_VERT, CD_MTEXPOLY, CD_ORIGINDEX, CDDM_from_BMEditMesh(), MVert::co, co, CustomData_bmesh_get(), BMHeader::data, ED_image_uv_aspect(), EDBM_edge_at_index(), EDBM_face_at_index(), EDBM_index_arrays_free(), EDBM_index_arrays_init(), faceMap, DerivedMesh::getEdgeArray, DerivedMesh::getEdgeDataArray, DerivedMesh::getNumEdges, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceArray, DerivedMesh::getTessFaceDataArray, DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, BMFace::head, i, SubsurfModifierData::levels, ME_CC_SUBSURF, MEM_freeN(), MEM_mallocN(), NULL, param_aspect_ratio(), param_construct_begin(), param_construct_end(), param_edge_set_seam(), param_face_add(), BMesh::pdata, DerivedMesh::release, SubsurfModifierData::subdivType, subsurf_make_derived_from_derived(), texface_from_original_index(), Scene::toolsettings, MTexPoly::tpage, TRUE, ToolSettings::uv_flag, ToolSettings::uv_subsurf_level, UV_SYNC_SELECTION, MEdge::v1, MFace::v1, MEdge::v2, MFace::v2, MFace::v3, and MFace::v4.
Referenced by ED_unwrap_lscm(), and ED_uvedit_live_unwrap_begin().
static void correct_uv_aspect (BMEditMesh * em) [static]
Definition at line 1002 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_active_face_get(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CD_MTEXPOLY, CustomData_bmesh_get(), BMHeader::data, ED_image_uv_aspect(), BMLoop::head, BMFace::head, BMesh::ldata, BMesh::pdata, MTexPoly::tpage, TRUE, and MLoopUV::uv.
Referenced by uv_map_clip_correct().
static int cube_project_exec (bContext * C, wmOperator * op) [static]
Definition at line 1550 of file uvedit_unwrap_ops.c.
References axis_dominant_v3(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, BMVert::co, CTX_data_edit_object(), CTX_data_scene(), CustomData_bmesh_get(), DAG_id_tag_update(), Object::data, BMHeader::data, ED_uvedit_ensure_uvs(), BMLoop::head, BMesh::ldata, NC_GEOM, ND_DATA, BMFace::no, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), MLoopUV::uv, uv_map_clip_correct(), BMLoop::v, and WM_event_add_notifier().
Referenced by UV_OT_cube_project().
static int cylinder_project_exec (bContext * C, wmOperator * op) [static]
Definition at line 1491 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, BMVert::co, CTX_data_edit_object(), CTX_data_scene(), CustomData_bmesh_get(), DAG_id_tag_update(), Object::data, BMHeader::data, ED_uvedit_ensure_uvs(), BMLoop::head, BMFace::head, BMesh::ldata, NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, BMesh::pdata, UvCameraInfo::rotmat, MLoopUV::uv, uv_cylinder_project(), uv_map_clip_correct(), uv_map_mirror(), uv_map_transform(), BMLoop::v, and WM_event_add_notifier().
Referenced by UV_OT_cylinder_project().
void ED_unwrap_lscm (Scene * scene, Object * obedit, const short sel)
Definition at line 1127 of file uvedit_unwrap_ops.c.
References BMEdit_FromObject(), construct_param_handle(), construct_param_handle_subsurfed(), param_delete(), PARAM_FALSE, param_flush(), param_lscm_begin(), param_lscm_end(), param_lscm_solve(), param_pack(), Scene::toolsettings, ToolSettings::unwrapper, UVCALC_FILLHOLES, ToolSettings::uvcalc_flag, ToolSettings::uvcalc_margin, UVCALC_NO_ASPECT_CORRECT, and UVCALC_USESUBSURF.
Referenced by ED_uvedit_live_unwrap(), mark_seam_exec(), and unwrap_exec().
static int ED_uvedit_ensure_uvs (bContext * C, Scene * scene, Object * obedit) [static]
Definition at line 89 of file uvedit_unwrap_ops.c.
References bScreen::areabase, BMEditMesh::bm, BM_data_layer_add(), BM_FACES_OF_MESH, BM_ITER_MESH, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, CTX_data_edit_image(), CTX_data_main(), CTX_wm_screen(), CustomData_has_layer(), Object::data, ED_mesh_uv_loop_reset_ex(), ED_uvedit_assign_image(), ED_uvedit_test(), FALSE, ListBase::first, IMA_TYPE_COMPOSITE, IMA_TYPE_R_RESULT, SpaceImage::image, BMesh::ldata, ScrArea::next, NULL, BMesh::pdata, SPACE_IMAGE, ScrArea::spacedata, SpaceLink::spacetype, BMesh::totface, Image::type, and uvedit_face_select_enable().
Referenced by cube_project_exec(), cylinder_project_exec(), reset_exec(), sphere_project_exec(), unwrap_exec(), and uv_from_view_exec().
void ED_uvedit_live_unwrap (Scene * scene, Object * obedit)
Definition at line 836 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BMEdit_FromObject(), CD_MLOOPUV, CustomData_has_layer(), ED_unwrap_lscm(), ToolSettings::edge_mode_live_unwrap, FALSE, BMesh::ldata, and Scene::toolsettings.
Referenced by edbm_mark_seam(), and mouse_mesh_shortest_path().
void ED_uvedit_live_unwrap_begin (Scene * scene, Object * obedit)
Definition at line 798 of file uvedit_unwrap_ops.c.
References BMEdit_FromObject(), construct_param_handle(), construct_param_handle_subsurfed(), ED_uvedit_test(), param_lscm_begin(), PARAM_TRUE, Scene::toolsettings, ToolSettings::unwrapper, UVCALC_FILLHOLES, ToolSettings::uvcalc_flag, and UVCALC_USESUBSURF.
Referenced by createTransUVs(), and uvedit_live_unwrap_update().
void ED_uvedit_live_unwrap_end (short cancel)
Definition at line 825 of file uvedit_unwrap_ops.c.
References NULL, param_delete(), param_flush_restore(), and param_lscm_end().
Referenced by postTrans(), and uvedit_live_unwrap_update().
void ED_uvedit_live_unwrap_re_solve (void)
Definition at line 817 of file uvedit_unwrap_ops.c.
References param_flush(), and param_lscm_solve().
Referenced by recalcData_image(), and uvedit_live_unwrap_update().
static int minimize_stretch_cancel (bContext * C, wmOperator * op) [static]
Definition at line 682 of file uvedit_unwrap_ops.c.
References minimize_stretch_exit(), and OPERATOR_CANCELLED.
Referenced by UV_OT_minimize_stretch().
static int minimize_stretch_exec (bContext * C, wmOperator * op) [static]
Definition at line 600 of file uvedit_unwrap_ops.c.
References i, minimize_stretch_exit(), minimize_stretch_init(), minimize_stretch_iteration(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, and RNA_int_get().
Referenced by UV_OT_minimize_stretch().
static void minimize_stretch_exit (bContext * C, wmOperator * op, int cancel) [static]
Definition at line 575 of file uvedit_unwrap_ops.c.
References CTX_wm_area(), CTX_wm_manager(), CTX_wm_window(), wmOperator::customdata, DAG_id_tag_update(), Object::data, ED_area_headerprint(), MinStretch::handle, MEM_freeN(), NC_GEOM, ND_DATA, NULL, MinStretch::obedit, param_delete(), param_flush(), param_flush_restore(), param_stretch_end(), MinStretch::timer, WM_event_add_notifier(), and WM_event_remove_timer().
Referenced by minimize_stretch_cancel(), minimize_stretch_exec(), and minimize_stretch_modal().
static int minimize_stretch_init (bContext * C, wmOperator * op) [static]
Definition at line 515 of file uvedit_unwrap_ops.c.
References MinStretch::blend, BMEdit_FromObject(), construct_param_handle(), CTX_data_edit_object(), CTX_data_scene(), wmOperator::customdata, MinStretch::em, MinStretch::handle, MinStretch::i, MinStretch::iterations, MinStretch::lasttime, MEM_callocN(), MinStretch::obedit, param_stretch_begin(), param_stretch_blend(), PIL_check_seconds_timer(), wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), RNA_int_get(), MinStretch::scene, and uvedit_have_selection().
Referenced by minimize_stretch_exec(), and minimize_stretch_invoke().
static int minimize_stretch_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 615 of file uvedit_unwrap_ops.c.
References CTX_wm_manager(), CTX_wm_window(), wmOperator::customdata, minimize_stretch_init(), minimize_stretch_iteration(), OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, TIMER, MinStretch::timer, WM_event_add_modal_handler(), and WM_event_add_timer().
Referenced by UV_OT_minimize_stretch().
static void minimize_stretch_iteration (bContext * C, wmOperator * op, int interactive) [static]
Definition at line 547 of file uvedit_unwrap_ops.c.
References MinStretch::blend, BLI_snprintf(), CTX_wm_area(), wmOperator::customdata, DAG_id_tag_update(), Object::data, ED_area_headerprint(), MinStretch::handle, MinStretch::i, MinStretch::lasttime, NC_GEOM, ND_DATA, MinStretch::obedit, param_flush(), param_stretch_blend(), param_stretch_iter(), PIL_check_seconds_timer(), wmOperator::ptr, RNA_int_set(), str, and WM_event_add_notifier().
Referenced by minimize_stretch_exec(), minimize_stretch_invoke(), and minimize_stretch_modal().
static int minimize_stretch_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 631 of file uvedit_unwrap_ops.c.
References MinStretch::blend, wmEvent::customdata, wmOperator::customdata, ESCKEY, MinStretch::i, MinStretch::iterations, MinStretch::lasttime, LEFTMOUSE, minimize_stretch_exit(), minimize_stretch_iteration(), OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, PADENTER, PADMINUS, PADPLUSKEY, PIL_check_seconds_timer(), wmOperator::ptr, RETKEY, RIGHTMOUSE, RNA_float_set(), MinStretch::timer, TIMER, wmEvent::type, WHEELDOWNMOUSE, and WHEELUPMOUSE.
Referenced by UV_OT_minimize_stretch().
static int pack_islands_exec (bContext * C, wmOperator * op) [static]
Definition at line 712 of file uvedit_unwrap_ops.c.
References BMEdit_FromObject(), construct_param_handle(), CTX_data_edit_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, param_delete(), param_flush(), param_pack(), wmOperator::ptr, RNA_float_get(), RNA_float_set(), RNA_struct_property_is_set(), Scene::toolsettings, ToolSettings::uvcalc_margin, uvedit_have_selection(), and WM_event_add_notifier().
Referenced by UV_OT_pack_islands().
static int reset_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1337 of file uvedit_unwrap_ops.c.
References CTX_data_edit_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, ED_mesh_uv_loop_reset(), ED_uvedit_ensure_uvs(), if(), NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by UV_OT_reset().
static int sphere_project_exec (bContext * C, wmOperator * op) [static]
Definition at line 1418 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), CD_MLOOPUV, CD_MTEXPOLY, BMVert::co, CTX_data_edit_object(), CTX_data_scene(), CustomData_bmesh_get(), DAG_id_tag_update(), Object::data, BMHeader::data, ED_uvedit_ensure_uvs(), BMFace::head, BMLoop::head, BMesh::ldata, NC_GEOM, ND_DATA, OPERATOR_CANCELLED, OPERATOR_FINISHED, BMesh::pdata, UvCameraInfo::rotmat, MLoopUV::uv, uv_map_clip_correct(), uv_map_mirror(), uv_map_transform(), uv_sphere_project(), BMLoop::v, and WM_event_add_notifier().
Referenced by UV_OT_sphere_project().
static void texface_from_original_index (BMFace * efa, int index, float ** uv, ParamBool * pin, ParamBool * select, Scene * scene, BMEditMesh * em) [static]
Definition at line 330 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_elem_index_get, BM_ITER_ELEM, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, MLoopUV::flag, BMLoop::head, BMesh::ldata, MLOOPUV_PINNED, NULL, ORIGINDEX_NONE, MLoopUV::uv, uvedit_uv_select_test(), and BMLoop::v.
Referenced by construct_param_handle_subsurfed().
static int unwrap_exec (bContext * C, wmOperator * op) [static]
Definition at line 1152 of file uvedit_unwrap_ops.c.
References BKE_report(), BMEdit_FromObject(), compare_v3v3(), CTX_data_edit_object(), CTX_data_scene(), DAG_id_tag_update(), Object::data, ED_unwrap_lscm(), ED_uvedit_ensure_uvs(), mat4_to_size(), NC_GEOM, ND_DATA, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_boolean_get(), RNA_enum_get(), RNA_int_get(), RPT_INFO, Scene::toolsettings, TRUE, ToolSettings::unwrapper, ToolSettings::uv_subsurf_level, UVCALC_FILLHOLES, ToolSettings::uvcalc_flag, UVCALC_NO_ASPECT_CORRECT, UVCALC_USESUBSURF, uvedit_have_selection(), and WM_event_add_notifier().
Referenced by UV_OT_unwrap().
static void uv_cylinder_project (float target[2], float source[3], float center[3], float rotmat[4][4]) [static]
Definition at line 1477 of file uvedit_unwrap_ops.c.
References map_to_tube(), mul_m4_v3(), and sub_v3_v3v3().
Referenced by cylinder_project_exec().
static int uv_from_view_exec (bContext * C, wmOperator * op) [static]
Definition at line 1232 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_FromObject(), View3D::camera, CD_MLOOPUV, BMVert::co, copy_m4_m4(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region(), CTX_wm_region_view3d(), CTX_wm_view3d(), CustomData_bmesh_get(), DAG_id_tag_update(), BMHeader::data, Object::data, ED_uvedit_ensure_uvs(), BMLoop::head, BMesh::ldata, MEM_freeN(), NC_GEOM, ND_DATA, NULL, OB_CAMERA, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, RegionView3D::persmat, RegionView3D::persp, project_camera_info(), project_from_camera(), project_from_view(), project_from_view_ortho(), wmOperator::ptr, Scene::r, RNA_boolean_get(), RV3D_CAMOB, Object::type, MLoopUV::uv, uv_map_clip_correct(), uv_map_rotation_matrix(), BMLoop::v, ARegion::winx, ARegion::winy, WM_event_add_notifier(), RenderData::xsch, and RenderData::ysch.
Referenced by UV_OT_from_view().
static int uv_from_view_poll (bContext * C) [static]
Definition at line 1309 of file uvedit_unwrap_ops.c.
References CTX_wm_region_view3d(), ED_operator_uvmap(), and NULL.
Referenced by UV_OT_from_view().
static void uv_map_clip_correct (BMEditMesh * em, wmOperator * op) [static]
Definition at line 1060 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CLAMP(), correct_uv_aspect(), CustomData_bmesh_get(), BMHeader::data, DO_MINMAX2, BMLoop::head, INIT_MINMAX2, BMesh::ldata, max, min, wmOperator::ptr, RNA_boolean_get(), and MLoopUV::uv.
Referenced by cube_project_exec(), cylinder_project_exec(), sphere_project_exec(), and uv_from_view_exec().
static void uv_map_clip_correct_properties (wmOperatorType * ot) [static]
Definition at line 1050 of file uvedit_unwrap_ops.c.
References RNA_def_boolean(), and wmOperatorType::srna.
Referenced by UV_OT_cube_project(), UV_OT_cylinder_project(), UV_OT_from_view(), and UV_OT_sphere_project().
static void uv_map_mirror (BMEditMesh * em, BMFace * efa, MTexPoly * UNUSEDtf) [static]
Definition at line 1386 of file uvedit_unwrap_ops.c.
References BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BMEditMesh::bm, BM_ITER_ELEM, BM_LOOPS_OF_FACE, BM_NGON_STACK_SIZE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, i, BMesh::ldata, BMFace::len, NULL, and MLoopUV::uv.
Referenced by cylinder_project_exec(), and sphere_project_exec().
static void uv_map_rotation_matrix (float result[][4], RegionView3D * rv3d, Object * ob, float upangledeg, float sideangledeg, float radius) [static]
Definition at line 897 of file uvedit_unwrap_ops.c.
References copy_m4_m4(), cos(), M_PI, mul_serie_m4(), NULL, Object::obmat, sin(), unit_m4(), RegionView3D::viewmat, and zero_m4().
Referenced by uv_from_view_exec(), and uv_map_transform().
static void uv_map_transform (bContext * C, wmOperator * op, float center[3], float rotmat[4][4]) [static]
Definition at line 945 of file uvedit_unwrap_ops.c.
References ALIGN_TO_OBJECT, BMEdit_FromObject(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_region_view3d(), CTX_wm_view3d(), POLAR_ZY, wmOperator::ptr, RNA_enum_get(), RNA_float_get(), RNA_struct_find_property(), unit_m4(), uv_map_rotation_matrix(), uv_map_transform_center(), and VIEW_ON_EQUATOR.
Referenced by cylinder_project_exec(), and sphere_project_exec().
static void uv_map_transform_center (Scene * scene, View3D * v3d, float * result, Object * ob, BMEditMesh * em) [static]
Definition at line 855 of file uvedit_unwrap_ops.c.
References View3D::around, BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMVert::co, DO_MINMAX, give_cursor(), max, mid_v3_v3v3(), min, Object::obmat, BMLoop::v, V3D_CENTER, V3D_CENTROID, V3D_CURSOR, and V3D_LOCAL.
Referenced by uv_map_transform().
void UV_OT_average_islands_scale (wmOperatorType * ot)
Definition at line 782 of file uvedit_unwrap_ops.c.
References average_islands_scale_exec(), ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_uvedit().
void UV_OT_cube_project (wmOperatorType * ot)
Definition at line 1610 of file uvedit_unwrap_ops.c.
References cube_project_exec(), ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), wmOperatorType::srna, and uv_map_clip_correct_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_cylinder_project (wmOperatorType * ot)
Definition at line 1532 of file uvedit_unwrap_ops.c.
References cylinder_project_exec(), ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, uv_map_clip_correct_properties(), and uv_transform_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_from_view (wmOperatorType * ot)
Definition at line 1319 of file uvedit_unwrap_ops.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), wmOperatorType::srna, uv_from_view_exec(), uv_from_view_poll(), and uv_map_clip_correct_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_minimize_stretch (wmOperatorType * ot)
Definition at line 689 of file uvedit_unwrap_ops.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, minimize_stretch_cancel(), minimize_stretch_exec(), minimize_stretch_invoke(), minimize_stretch_modal(), wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_GRAB_POINTER, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_factor(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
void UV_OT_pack_islands (wmOperatorType * ot)
Definition at line 742 of file uvedit_unwrap_ops.c.
References ED_operator_uvedit(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, pack_islands_exec(), wmOperatorType::poll, RNA_def_float_factor(), and wmOperatorType::srna.
Referenced by ED_operatortypes_uvedit().
void UV_OT_reset (wmOperatorType * ot)
Definition at line 1358 of file uvedit_unwrap_ops.c.
References ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and reset_exec().
Referenced by ED_operatortypes_uvedit().
void UV_OT_sphere_project (wmOperatorType * ot)
Definition at line 1459 of file uvedit_unwrap_ops.c.
References ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, sphere_project_exec(), uv_map_clip_correct_properties(), and uv_transform_properties().
Referenced by ED_operatortypes_uvedit().
void UV_OT_unwrap (wmOperatorType * ot)
Definition at line 1201 of file uvedit_unwrap_ops.c.
References wmOperatorType::description, ED_operator_uvmap(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), RNA_def_int(), wmOperatorType::srna, and unwrap_exec().
Referenced by ED_operatortypes_uvedit().
static void uv_sphere_project (float target[2], float source[3], float center[3], float rotmat[4][4]) [static]
Definition at line 1372 of file uvedit_unwrap_ops.c.
References map_to_sphere(), mul_m4_v3(), and sub_v3_v3v3().
Referenced by sphere_project_exec().
static void uv_transform_properties (wmOperatorType * ot, int radius) [static]
Definition at line 979 of file uvedit_unwrap_ops.c.
References ALIGN_TO_OBJECT, direction_items, FLT_MAX, NULL, POLAR_ZX, POLAR_ZY, RNA_def_enum(), RNA_def_float(), wmOperatorType::srna, VIEW_ON_EQUATOR, and VIEW_ON_POLES.
Referenced by UV_OT_cylinder_project(), and UV_OT_sphere_project().
static int uvedit_have_selection (Scene * scene, BMEditMesh * em, short implicit) [static]
Definition at line 150 of file uvedit_unwrap_ops.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, CD_MLOOPUV, CustomData_bmesh_get(), BMHeader::data, BMLoop::head, BMesh::ldata, Scene::toolsettings, ToolSettings::uv_flag, UV_SYNC_SELECTION, and uvedit_uv_select_test().
Referenced by average_islands_scale_exec(), minimize_stretch_init(), pack_islands_exec(), and unwrap_exec().
Variable Documentation
ParamHandle* liveHandle = NULL [static]
Definition at line 796 of file uvedit_unwrap_ops.c.