Blender: ControlParticles Class Reference
ControlParticles Class Reference
#include <controlparticles.h>
Public Member Functions
ControlParticles ()
~ControlParticles ()
void prepareControl (LbmFloat simtime, LbmFloat dt, ControlParticles *motion)
void finishControl (std::vector< ControlForces > &forces, LbmFloat iatt, LbmFloat ivel, LbmFloat imaxd)
void calculateKernelWeight ()
void calculateCpInfluenceOpt (ControlParticle *cp, LbmVec fluidpos, LbmVec fluidvel, ControlForces *force, LbmFloat fillFactor)
void calculateMaxdForce (ControlParticle *cp, LbmVec fluidpos, ControlForces *force)
int getSize ()
int getTotalSize ()
ControlParticle * getParticle (int i)
void setInfluenceTangential (LbmFloat set)
void setInfluenceAttraction (LbmFloat set)
void setInfluenceMaxdist (LbmFloat set)
void setInfluenceVelocity (LbmFloat set, LbmFloat dt)
LbmFloat getInfluenceAttraction ()
LbmFloat getInfluenceTangential ()
LbmFloat getInfluenceVelocity ()
LbmFloat getInfluenceMaxdist ()
LbmFloat getCurrTimestep ()
void setRadiusAtt (LbmFloat set)
LbmFloat getRadiusAtt ()
void setRadiusVel (LbmFloat set)
LbmFloat getRadiusVel ()
void setRadiusMaxd (LbmFloat set)
LbmFloat getRadiusMaxd ()
void setRadiusMinMaxd (LbmFloat set)
LbmFloat getRadiusMinMaxd ()
LbmFloat getControlTimStart ()
LbmFloat getControlTimEnd ()
void setCharLength (LbmFloat set)
LbmFloat getCharLength ()
LbmFloat getCharLengthInv ()
void setInitTimeScale (LbmFloat set)
void setInitMirror (string set)
string getInitMirror ()
void setLastOffset (LbmVec set)
void setLastScale (LbmVec set)
void setOffset (LbmVec set)
void setScale (LbmVec set)
void setCPSWith (LbmFloat set)
void setCPSTimestep (LbmFloat set)
void setCPSTimeStart (LbmFloat set)
void setCPSTimeEnd (LbmFloat set)
void setCPSMvmWeightFac (LbmFloat set)
LbmFloat getCPSWith ()
LbmFloat getCPSTimestep ()
LbmFloat getCPSTimeStart ()
LbmFloat getCPSTimeEnd ()
LbmFloat getCPSMvmWeightFac ()
void setDebugInit (int set)
void setFluidSpacing (LbmFloat set)
int initFromTextFile (string filename)
int initFromTextFileOld (string filename)
int initFromBinaryFile (string filename)
int initFromMVCMesh (string filename)
int initExampleSet ()
void initTime (LbmFloat t, LbmFloat dt)
void initBlenderTest ()
int initFromObject (ntlGeometryObjModel *model)
Protected Member Functions
void calculateCPS (string filename)
void applyTrafos ()
void swapCoords (int a, int b)
void mirrorTime ()
void initTimeArray (LbmFloat t, std::vector< ControlParticle > &parts)
bool checkPointInside (ntlTree *tree, ntlVec3Gfx org, gfxReal &distance)
Protected Attributes
LbmFloat _influenceTangential
LbmFloat _influenceAttraction
LbmFloat _influenceVelocity
LbmFloat _influenceMaxdist
LbmFloat _radiusAtt
LbmFloat _radiusVel
LbmFloat _radiusMinMaxd
LbmFloat _radiusMaxd
LbmFloat _currTime
LbmFloat _currTimestep
std::vector< ControlParticle > _particles
std::vector< ControlParticleSet > mPartSets
LbmFloat _initTimeScale
LbmVec _initPartOffset
LbmVec _initPartScale
LbmVec _initLastPartOffset
LbmVec _initLastPartScale
string _initMirror
LbmFloat _fluidSpacing
LbmFloat _kernelWeight
LbmFloat _charLength
LbmFloat _charLengthInv
ntlVec3Gfx mvCPSStart
ani mesh cps params
ntlVec3Gfx mvCPSEnd
gfxReal mCPSWidth
gfxReal mCPSTimestep
gfxReal mCPSTimeStart
gfxReal mCPSTimeEnd
gfxReal mCPSWeightFac
int mDebugInit
Friends
class MultisphGUI
Detailed Description
Definition at line 135 of file controlparticles.h.
Constructor & Destructor Documentation
ControlParticles::ControlParticles ()
Definition at line 225 of file controlparticles.cpp.
References _influenceAttraction, _influenceTangential, _influenceVelocity, _radiusAtt, _radiusMaxd, _radiusMinMaxd, and _radiusVel.
ControlParticles::~ControlParticles ()
Definition at line 259 of file controlparticles.cpp.
Member Function Documentation
void ControlParticles::applyTrafos () [protected]
Definition at line 943 of file controlparticles.cpp.
References _initMirror, _initTimeScale, i, initTime(), mirrorTime(), mPartSets, and swapCoords().
Referenced by initFromBinaryFile(), and initFromMVCMesh().
void ControlParticles::calculateCpInfluenceOpt (ControlParticle * cp, LbmVec fluidpos, LbmVec fluidvel, ControlForces * force, LbmFloat fillFactor)
Definition at line 1344 of file controlparticles.cpp.
References _radiusAtt, _radiusVel, ABS, ControlParticle::avgVel, ControlParticle::avgVelWeight, DEBUG_MODVEL, ControlParticle::density, ControlParticle::densityWeight, ControlForces::forceAtt, ControlForces::forceVel, getInfluenceAttraction(), ControlParticle::influence, MAGNITUDE, ControlForces::maxDistance, ControlParticle::pos, ControlParticle::size, ControlParticle::vel, ControlForces::weightAtt, and ControlForces::weightVel.
Referenced by LbmFsgrSolver::handleCpdata().
void ControlParticles::calculateCPS (string filename) [protected]
do ani mesh CPS
void ControlParticles::calculateKernelWeight ()
Definition at line 1181 of file controlparticles.cpp.
References _fluidSpacing, _influenceAttraction, _influenceTangential, _influenceVelocity, _kernelWeight, _radiusAtt, CP_PI, debMsgStd, DM_MSG, and errMsg.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmFsgrSolver::initCpdata().
void ControlParticles::calculateMaxdForce (ControlParticle * cp, LbmVec fluidpos, ControlForces * force)
Definition at line 1430 of file controlparticles.cpp.
References _radiusMaxd, _radiusMinMaxd, DEBUG_MODVEL, ControlForces::forceMaxd, ControlParticle::influence, ControlForces::maxDistance, ControlParticle::pos, ControlParticle::size, sqrtf, and ControlForces::weightAtt.
Referenced by LbmFsgrSolver::handleCpdata().
bool ControlParticles::checkPointInside (ntlTree * tree, ntlVec3Gfx org, gfxReal & distance) [protected]
Definition at line 690 of file controlparticles.cpp.
References distance(), dot(), errMsg, FGI_FLUID, ntlRay::getDirection(), ntlTriangle::getObjectId(), ntlRay::getOrigin(), getVecEpsilon(), globCPIProblems, globGeoInitDebug, ntlTree::intersectX(), and NULL.
Referenced by initFromMVCMesh(), and initFromObject().
void ControlParticles::finishControl (std::vector< ControlForces > & forces, LbmFloat iatt, LbmFloat ivel, LbmFloat imaxd)
Definition at line 1278 of file controlparticles.cpp.
References _radiusAtt, _radiusMaxd, _radiusVel, ABS, DEBUG_MODVEL, getCurrTimestep(), and i.
LbmFloat ControlParticles::getCharLength () [inline]
Definition at line 188 of file controlparticles.h.
References _charLength.
Referenced by LbmFsgrSolver::initCpdata().
LbmFloat ControlParticles::getCharLengthInv () [inline]
Definition at line 189 of file controlparticles.h.
References _charLengthInv.
LbmFloat ControlParticles::getControlTimEnd ()
Definition at line 267 of file controlparticles.cpp.
References mPartSets.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmFsgrSolver::initCpdata().
LbmFloat ControlParticles::getControlTimStart ()
Definition at line 263 of file controlparticles.cpp.
References mPartSets.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmFsgrSolver::initCpdata().
LbmFloat ControlParticles::getCPSMvmWeightFac () [inline]
Definition at line 212 of file controlparticles.h.
References mCPSWeightFac.
Referenced by LbmControlData::parseControldataAttrList().
LbmFloat ControlParticles::getCPSTimeEnd () [inline]
Definition at line 211 of file controlparticles.h.
References mCPSTimeEnd.
Referenced by LbmControlData::parseControldataAttrList().
LbmFloat ControlParticles::getCPSTimeStart () [inline]
Definition at line 210 of file controlparticles.h.
References mCPSTimeStart.
Referenced by LbmControlData::parseControldataAttrList().
LbmFloat ControlParticles::getCPSTimestep () [inline]
Definition at line 209 of file controlparticles.h.
References mCPSTimestep.
Referenced by LbmControlData::parseControldataAttrList().
LbmFloat ControlParticles::getCPSWith () [inline]
Definition at line 208 of file controlparticles.h.
References mCPSWidth.
Referenced by LbmControlData::parseControldataAttrList().
LbmFloat ControlParticles::getCurrTimestep () [inline]
Definition at line 172 of file controlparticles.h.
References _currTimestep.
Referenced by finishControl().
LbmFloat ControlParticles::getInfluenceAttraction () [inline]
Definition at line 168 of file controlparticles.h.
References _influenceAttraction.
Referenced by calculateCpInfluenceOpt(), and prepareControl().
LbmFloat ControlParticles::getInfluenceMaxdist () [inline]
Definition at line 171 of file controlparticles.h.
References _influenceMaxdist.
Referenced by LbmFsgrSolver::handleCpdata().
LbmFloat ControlParticles::getInfluenceTangential () [inline]
Definition at line 169 of file controlparticles.h.
References _influenceTangential.
LbmFloat ControlParticles::getInfluenceVelocity () [inline]
Definition at line 170 of file controlparticles.h.
References _influenceVelocity.
string ControlParticles::getInitMirror () [inline]
Definition at line 194 of file controlparticles.h.
References _initMirror.
Referenced by LbmControlData::parseControldataAttrList().
ControlParticle* ControlParticles::getParticle (int i) [inline]
Definition at line 159 of file controlparticles.h.
References _particles, and i.
Referenced by LbmFsgrSolver::cpDebugDisplay(), LbmFsgrSolver::handleCpdata(), and prepareControl().
LbmFloat ControlParticles::getRadiusAtt () [inline]
Definition at line 175 of file controlparticles.h.
References _radiusAtt.
Referenced by LbmFsgrSolver::cpDebugDisplay(), and LbmFsgrSolver::handleCpdata().
LbmFloat ControlParticles::getRadiusMaxd () [inline]
Definition at line 179 of file controlparticles.h.
References _radiusMaxd.
Referenced by LbmFsgrSolver::handleCpdata().
LbmFloat ControlParticles::getRadiusMinMaxd () [inline]
Definition at line 181 of file controlparticles.h.
References _radiusMinMaxd.
Referenced by LbmFsgrSolver::handleCpdata().
LbmFloat ControlParticles::getRadiusVel () [inline]
Definition at line 177 of file controlparticles.h.
References _radiusVel.
Referenced by LbmFsgrSolver::handleCpdata().
int ControlParticles::getSize (void) [inline]
Definition at line 156 of file controlparticles.h.
References _particles.
Referenced by LbmFsgrSolver::cpDebugDisplay(), LbmFsgrSolver::handleCpdata(), LbmFsgrSolver::initCpdata(), and prepareControl().
int ControlParticles::getTotalSize ()
Definition at line 288 of file controlparticles.cpp.
References i, and mPartSets.
Referenced by LbmFsgrSolver::initCpdata().
void ControlParticles::initBlenderTest ()
Definition at line 33 of file controlparticles.cpp.
References initTime(), mPartSets, p, ControlParticle::pos, and ControlParticle::reset().
int ControlParticles::initExampleSet ()
Definition at line 282 of file controlparticles.cpp.
int ControlParticles::initFromBinaryFile (string filename)
Definition at line 634 of file controlparticles.cpp.
References applyTrafos(), mPartSets, p, ControlParticle::pos, ControlParticle::reset(), snprintf, and vec2L().
int ControlParticles::initFromMVCMesh (string filename)
Definition at line 781 of file controlparticles.cpp.
References ntlScene::addGeoClass(), ntlScene::addGeoObject(), applyTrafos(), ntlScene::buildScene(), MeanValueMeshCoords::calculateMVMCs(), checkPointInside(), debMsgStd, distance(), DM_MSG, errMsg, FGI_FLUID, ntlGeometryObjModel::getExtends(), getTime(), getTimeString(), ntlGeometryObjModel::getTriangles(), globCPIProblems, i, LBM_EPSILON, ntlGeometryObjModel::loadBobjModel(), mCPSTimeEnd, mCPSTimeStart, mCPSTimestep, mCPSWeightFac, mCPSWidth, mPartSets, norm(), p, ControlParticle::pos, ControlParticle::reset(), ntlGeometryClass::setGeoInitId(), ntlGeometryObject::setGeoInitType(), ntlGeometryObjModel::setLoaded(), snprintf, and vec2L().
int ControlParticles::initFromObject (ntlGeometryObjModel * model)
Definition at line 64 of file controlparticles.cpp.
References ntlScene::addGeoClass(), ntlScene::addGeoObject(), ntlScene::buildScene(), MeanValueMeshCoords::calculateMVMCs(), checkPointInside(), distance(), errMsg, FGI_CONTROL, FGI_FLUID, ntlGeometryObjModel::getExtends(), ntlGeometryClass::getGeoInitId(), ntlGeometryObject::getGeoPartSlipValue(), ntlGeometryObjModel::getTriangles(), i, LBM_EPSILON, mCPSTimeEnd, mCPSTimeStart, mCPSTimestep, mCPSWeightFac, mCPSWidth, mirrorTime(), mPartSets, p, ControlParticle::pos, ControlParticle::reset(), ntlGeometryObject::setGeoInitType(), MeanValueMeshCoords::transfer(), and vec2L().
int ControlParticles::initFromTextFile (string filename)
Definition at line 301 of file controlparticles.cpp.
Referenced by LbmFsgrSolver::initCpdata().
int ControlParticles::initFromTextFileOld (string filename)
Definition at line 513 of file controlparticles.cpp.
void ControlParticles::initTime (LbmFloat t, LbmFloat dt)
Definition at line 1012 of file controlparticles.cpp.
References _currTime, _currTimestep, _initLastPartOffset, _initLastPartScale, _initPartOffset, _initPartScale, _particles, initTimeArray(), mPartSets, p, ControlParticle::pos, and ControlParticle::vel.
Referenced by applyTrafos(), initBlenderTest(), and prepareControl().
void ControlParticles::initTimeArray (LbmFloat t, std::vector< ControlParticle > & parts) [protected]
Definition at line 1051 of file controlparticles.cpp.
References ControlParticle::avgVel, ControlParticle::avgVelAcc, ControlParticle::avgVelWeight, cos(), ControlParticle::density, ControlParticle::densityWeight, i, ControlParticle::influence, M_PI, mDebugInit, mPartSets, p, ControlParticle::pos, ControlParticle::rotaxis, sin(), ControlParticle::size, and ControlParticle::vel.
Referenced by initTime().
void ControlParticles::mirrorTime () [protected]
Definition at line 922 of file controlparticles.cpp.
References errMsg, i, and mPartSets.
Referenced by applyTrafos(), and initFromObject().
void ControlParticles::prepareControl (LbmFloat simtime, LbmFloat dt, ControlParticles * motion)
Definition at line 1210 of file controlparticles.cpp.
References _kernelWeight, _particles, _radiusAtt, _radiusMaxd, _radiusMinMaxd, _radiusVel, ControlParticle::avgVel, ControlParticle::avgVelAcc, ControlParticle::avgVelWeight, debMsgStd, ControlParticle::density, ControlParticle::densityWeight, DM_MSG, getInfluenceAttraction(), getParticle(), getSize(), i, ControlParticle::influence, initTime(), ControlParticle::pos, ControlParticle::size, and ControlParticle::vel.
Referenced by LbmFsgrSolver::handleCpdata().
void ControlParticles::setCharLength (LbmFloat set) [inline]
Definition at line 187 of file controlparticles.h.
References _charLength, and _charLengthInv.
Referenced by LbmFsgrSolver::initCpdata().
void ControlParticles::setCPSMvmWeightFac (LbmFloat set) [inline]
Definition at line 206 of file controlparticles.h.
References mCPSWeightFac.
Referenced by LbmFsgrSolver::initCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setCPSTimeEnd (LbmFloat set) [inline]
Definition at line 205 of file controlparticles.h.
References mCPSTimeEnd.
Referenced by LbmFsgrSolver::initCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setCPSTimeStart (LbmFloat set) [inline]
Definition at line 204 of file controlparticles.h.
References mCPSTimeStart.
Referenced by LbmFsgrSolver::initCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setCPSTimestep (LbmFloat set) [inline]
Definition at line 203 of file controlparticles.h.
References mCPSTimestep.
Referenced by LbmControlData::parseControldataAttrList().
void ControlParticles::setCPSWith (LbmFloat set) [inline]
Definition at line 202 of file controlparticles.h.
References mCPSWidth.
Referenced by LbmFsgrSolver::initCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setDebugInit (int set) [inline]
Definition at line 214 of file controlparticles.h.
References mDebugInit.
Referenced by LbmControlData::parseControldataAttrList().
void ControlParticles::setFluidSpacing (LbmFloat set) [inline]
Definition at line 217 of file controlparticles.h.
References _fluidSpacing.
Referenced by LbmFsgrSolver::initCpdata().
void ControlParticles::setInfluenceAttraction (LbmFloat set) [inline]
Definition at line 163 of file controlparticles.h.
References _influenceAttraction.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setInfluenceMaxdist (LbmFloat set) [inline]
Definition at line 164 of file controlparticles.h.
References _influenceMaxdist.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setInfluenceTangential (LbmFloat set) [inline]
Definition at line 162 of file controlparticles.h.
References _influenceTangential.
Referenced by LbmControlData::parseControldataAttrList().
void ControlParticles::setInfluenceVelocity (LbmFloat set, LbmFloat dt)
Definition at line 273 of file controlparticles.cpp.
References _influenceVelocity, and pow().
Referenced by LbmFsgrSolver::handleCpdata(), LbmFsgrSolver::initCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setInitMirror (string set) [inline]
Definition at line 193 of file controlparticles.h.
References _initMirror.
Referenced by LbmControlData::parseControldataAttrList().
void ControlParticles::setInitTimeScale (LbmFloat set) [inline]
Definition at line 192 of file controlparticles.h.
References _initTimeScale.
Referenced by LbmControlData::parseControldataAttrList().
void ControlParticles::setLastOffset (LbmVec set) [inline]
Definition at line 196 of file controlparticles.h.
References _initLastPartOffset.
Referenced by LbmFsgrSolver::handleCpdata().
void ControlParticles::setLastScale (LbmVec set) [inline]
Definition at line 197 of file controlparticles.h.
References _initLastPartScale.
Referenced by LbmFsgrSolver::handleCpdata().
void ControlParticles::setOffset (LbmVec set) [inline]
Definition at line 198 of file controlparticles.h.
References _initPartOffset.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setRadiusAtt (LbmFloat set) [inline]
Definition at line 174 of file controlparticles.h.
References _radiusAtt.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setRadiusMaxd (LbmFloat set) [inline]
Definition at line 178 of file controlparticles.h.
References _radiusMaxd.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setRadiusMinMaxd (LbmFloat set) [inline]
Definition at line 180 of file controlparticles.h.
References _radiusMinMaxd.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setRadiusVel (LbmFloat set) [inline]
Definition at line 176 of file controlparticles.h.
References _radiusVel.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::setScale (LbmVec set) [inline]
Definition at line 199 of file controlparticles.h.
References _initPartScale.
Referenced by LbmFsgrSolver::handleCpdata(), and LbmControlData::parseControldataAttrList().
void ControlParticles::swapCoords (int a, int b) [protected]
Definition at line 912 of file controlparticles.cpp.
References i, mPartSets, and TRISWAPALL.
Referenced by applyTrafos().
Friends And Related Function Documentation
friend class MultisphGUI [friend]
Definition at line 238 of file controlparticles.h.
Member Data Documentation
LbmFloat ControlParticles::_charLength [protected]
Definition at line 272 of file controlparticles.h.
Referenced by getCharLength(), and setCharLength().
LbmFloat ControlParticles::_charLengthInv [protected]
Definition at line 272 of file controlparticles.h.
Referenced by getCharLengthInv(), and setCharLength().
LbmFloat ControlParticles::_currTime [protected]
Definition at line 251 of file controlparticles.h.
Referenced by initTime().
LbmFloat ControlParticles::_currTimestep [protected]
Definition at line 251 of file controlparticles.h.
Referenced by getCurrTimestep(), and initTime().
LbmFloat ControlParticles::_fluidSpacing [protected]
Definition at line 268 of file controlparticles.h.
Referenced by calculateKernelWeight(), and setFluidSpacing().
LbmFloat ControlParticles::_influenceAttraction [protected]
Definition at line 241 of file controlparticles.h.
Referenced by calculateKernelWeight(), ControlParticles(), getInfluenceAttraction(), and setInfluenceAttraction().
LbmFloat ControlParticles::_influenceMaxdist [protected]
Definition at line 245 of file controlparticles.h.
Referenced by getInfluenceMaxdist(), and setInfluenceMaxdist().
LbmFloat ControlParticles::_influenceTangential [protected]
Definition at line 241 of file controlparticles.h.
Referenced by calculateKernelWeight(), ControlParticles(), getInfluenceTangential(), and setInfluenceTangential().
LbmFloat ControlParticles::_influenceVelocity [protected]
Definition at line 243 of file controlparticles.h.
Referenced by calculateKernelWeight(), ControlParticles(), getInfluenceVelocity(), and setInfluenceVelocity().
LbmVec ControlParticles::_initLastPartOffset [protected]
Definition at line 262 of file controlparticles.h.
Referenced by initTime(), and setLastOffset().
LbmVec ControlParticles::_initLastPartScale [protected]
Definition at line 263 of file controlparticles.h.
Referenced by initTime(), and setLastScale().
string ControlParticles::_initMirror [protected]
Definition at line 265 of file controlparticles.h.
Referenced by applyTrafos(), getInitMirror(), and setInitMirror().
LbmVec ControlParticles::_initPartOffset [protected]
Definition at line 260 of file controlparticles.h.
Referenced by initTime(), and setOffset().
LbmVec ControlParticles::_initPartScale [protected]
Definition at line 261 of file controlparticles.h.
Referenced by initTime(), and setScale().
LbmFloat ControlParticles::_initTimeScale [protected]
Definition at line 259 of file controlparticles.h.
Referenced by applyTrafos(), and setInitTimeScale().
LbmFloat ControlParticles::_kernelWeight [protected]
Definition at line 270 of file controlparticles.h.
Referenced by calculateKernelWeight(), and prepareControl().
std::vector<ControlParticle> ControlParticles::_particles [protected]
Definition at line 253 of file controlparticles.h.
Referenced by getParticle(), getSize(), initTime(), and prepareControl().
LbmFloat ControlParticles::_radiusAtt [protected]
Definition at line 248 of file controlparticles.h.
Referenced by calculateCpInfluenceOpt(), calculateKernelWeight(), ControlParticles(), finishControl(), getRadiusAtt(), prepareControl(), and setRadiusAtt().
LbmFloat ControlParticles::_radiusMaxd [protected]
Definition at line 248 of file controlparticles.h.
Referenced by calculateMaxdForce(), ControlParticles(), finishControl(), getRadiusMaxd(), prepareControl(), and setRadiusMaxd().
LbmFloat ControlParticles::_radiusMinMaxd [protected]
Definition at line 248 of file controlparticles.h.
Referenced by calculateMaxdForce(), ControlParticles(), getRadiusMinMaxd(), prepareControl(), and setRadiusMinMaxd().
LbmFloat ControlParticles::_radiusVel [protected]
Definition at line 248 of file controlparticles.h.
Referenced by calculateCpInfluenceOpt(), ControlParticles(), finishControl(), getRadiusVel(), prepareControl(), and setRadiusVel().
gfxReal ControlParticles::mCPSTimeEnd [protected]
Definition at line 280 of file controlparticles.h.
Referenced by getCPSTimeEnd(), initFromMVCMesh(), initFromObject(), and setCPSTimeEnd().
gfxReal ControlParticles::mCPSTimeStart [protected]
Definition at line 280 of file controlparticles.h.
Referenced by getCPSTimeStart(), initFromMVCMesh(), initFromObject(), and setCPSTimeStart().
gfxReal ControlParticles::mCPSTimestep [protected]
Definition at line 279 of file controlparticles.h.
Referenced by getCPSTimestep(), initFromMVCMesh(), initFromObject(), and setCPSTimestep().
gfxReal ControlParticles::mCPSWeightFac [protected]
Definition at line 281 of file controlparticles.h.
Referenced by getCPSMvmWeightFac(), initFromMVCMesh(), initFromObject(), and setCPSMvmWeightFac().
gfxReal ControlParticles::mCPSWidth [protected]
Definition at line 279 of file controlparticles.h.
Referenced by getCPSWith(), initFromMVCMesh(), initFromObject(), and setCPSWith().
int ControlParticles::mDebugInit [protected]
Definition at line 283 of file controlparticles.h.
Referenced by initTimeArray(), and setDebugInit().
std::vector<ControlParticleSet> ControlParticles::mPartSets [protected]
Definition at line 256 of file controlparticles.h.
Referenced by applyTrafos(), getControlTimEnd(), getControlTimStart(), getTotalSize(), initBlenderTest(), initFromBinaryFile(), initFromMVCMesh(), initFromObject(), initTime(), initTimeArray(), mirrorTime(), and swapCoords().
ntlVec3Gfx ControlParticles::mvCPSEnd [protected]
Definition at line 278 of file controlparticles.h.
ntlVec3Gfx ControlParticles::mvCPSStart [protected]
ani mesh cps params
Definition at line 278 of file controlparticles.h.
The documentation for this class was generated from the following files:
controlparticles.h
controlparticles.cpp