Blender: svm_convert.h File Reference
svm_convert.h File Reference
Functions
CCL_NAMESPACE_BEGIN __device void svm_node_convert (ShaderData *sd, float *stack, uint type, uint from, uint to)
Function Documentation
CCL_NAMESPACE_BEGIN __device void svm_node_convert (ShaderData * sd, float * stack, uint type, uint from, uint to)
Definition at line 23 of file svm_convert.h.
References g, linear_rgb_to_gray(), make_float3(), NODE_CONVERT_CF, NODE_CONVERT_FV, NODE_CONVERT_VF, stack_load_float(), stack_load_float3(), stack_store_float(), stack_store_float3(), float3::x, float3::y, and float3::z.
Referenced by svm_eval_nodes().