Blender: wm_cursors.h File Reference
wm_cursors.h File Reference
windowmanager
Classes
struct BCursor
Defines
#define BC_GHOST_CURSORS 1000
#define SYSCURSOR 1
#define SMALL_CURSOR 0
#define BIG_CURSOR 1
Typedefs
typedef struct BCursor BCursor
Enumerations
enum {
CURSOR_FACESEL = BC_GHOST_CURSORS, CURSOR_WAIT, CURSOR_EDIT, CURSOR_X_MOVE,
CURSOR_Y_MOVE, CURSOR_HELP, CURSOR_STD, CURSOR_NONE,
CURSOR_PENCIL, CURSOR_COPY
}
enum {
BC_NW_ARROWCURSOR = 2, BC_NS_ARROWCURSOR, BC_EW_ARROWCURSOR, BC_WAITCURSOR,
BC_CROSSCURSOR, BC_EDITCROSSCURSOR, BC_BOXSELCURSOR, BC_KNIFECURSOR,
BC_VLOOPCURSOR, BC_TEXTEDITCURSOR, BC_PAINTBRUSHCURSOR, BC_HANDCURSOR,
BC_NSEW_SCROLLCURSOR, BC_NS_SCROLLCURSOR, BC_EW_SCROLLCURSOR, BC_EYEDROPPER_CURSOR,
BC_SWAPAREA_CURSOR, BC_NUMCURSORS
}
enum {
BC_BLACK = 0, BC_WHITE, BC_RED, BC_BLUE,
BC_GREEN, BC_YELLOW
}
Functions
void wm_init_cursor_data (void)
int wm_cursor_arrow_move (struct wmWindow *win, struct wmEvent *event)
Detailed Description
Definition in file wm_cursors.h.
Define Documentation
#define BC_GHOST_CURSORS 1000
Definition at line 40 of file wm_cursors.h.
Referenced by WM_cursor_set().
#define BIG_CURSOR 1
Definition at line 115 of file wm_cursors.h.
#define SMALL_CURSOR 0
Definition at line 114 of file wm_cursors.h.
#define SYSCURSOR 1
Definition at line 81 of file wm_cursors.h.
Referenced by WM_cursor_set().
Typedef Documentation
typedef struct BCursor BCursor
Enumeration Type Documentation
anonymous enum
Enumerator:
CURSOR_FACESEL
CURSOR_WAIT
CURSOR_EDIT
CURSOR_X_MOVE
CURSOR_Y_MOVE
CURSOR_HELP
CURSOR_STD
CURSOR_NONE
CURSOR_PENCIL
CURSOR_COPY
Definition at line 43 of file wm_cursors.h.
anonymous enum
Enumerator:
BC_NW_ARROWCURSOR
BC_NS_ARROWCURSOR
BC_EW_ARROWCURSOR
BC_WAITCURSOR
BC_CROSSCURSOR
BC_EDITCROSSCURSOR
BC_BOXSELCURSOR
BC_KNIFECURSOR
BC_VLOOPCURSOR
BC_TEXTEDITCURSOR
BC_PAINTBRUSHCURSOR
BC_HANDCURSOR
BC_NSEW_SCROLLCURSOR
BC_NS_SCROLLCURSOR
BC_EW_SCROLLCURSOR
BC_EYEDROPPER_CURSOR
BC_SWAPAREA_CURSOR
BC_NUMCURSORS
Definition at line 82 of file wm_cursors.h.
anonymous enum
Enumerator:
BC_BLACK
BC_WHITE
BC_RED
BC_BLUE
BC_GREEN
BC_YELLOW
Definition at line 105 of file wm_cursors.h.
Function Documentation
int wm_cursor_arrow_move (struct wmWindow * win, struct wmEvent * event)
Definition at line 216 of file wm_cursors.c.
References DOWNARROWKEY, KM_PRESS, LEFTARROWKEY, RIGHTARROWKEY, wmEvent::type, UPARROWKEY, wmEvent::val, WM_cursor_warp(), wmEvent::x, and wmEvent::y.
Referenced by wm_handlers_do().
void wm_init_cursor_data (void)
********************** NS_ARROW Cursor *************************/
Definition at line 323 of file wm_cursors.c.
References BC_BLACK, BC_BLUE, BC_BOXSELCURSOR, BC_CROSSCURSOR, BC_EDITCROSSCURSOR, BC_EW_ARROWCURSOR, BC_EW_SCROLLCURSOR, BC_EYEDROPPER_CURSOR, BC_HANDCURSOR, BC_KNIFECURSOR, BC_NS_ARROWCURSOR, BC_NS_SCROLLCURSOR, BC_NSEW_SCROLLCURSOR, BC_NW_ARROWCURSOR, BC_PAINTBRUSHCURSOR, BC_SWAPAREA_CURSOR, BC_TEXTEDITCURSOR, BC_VLOOPCURSOR, BC_WAITCURSOR, BC_WHITE, BC_YELLOW, BEGIN_CURSOR_BLOCK, END_CURSOR_BLOCK, and NULL.
Referenced by WM_init().