Blender: blf_translation.c File Reference
blf_translation.c File Reference
blenfont
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_path_util.h"
#include "BLI_string.h"
#include "BLI_fileops.h"
#include "BLF_translation.h"
#include "DNA_userdef_types.h"
Functions
const char * BLF_gettext (const char *msgid)
const char * BLF_pgettext (const char *context, const char *message)
int BLF_translate_iface (void)
int BLF_translate_tooltips (void)
const char * BLF_translate_do_iface (const char *context, const char *msgid)
const char * BLF_translate_do_tooltip (const char *context, const char *msgid)
Detailed Description
Definition in file blf_translation.c.
Function Documentation
const char* BLF_gettext (const char * msgid)
Definition at line 93 of file blf_translation.c.
Referenced by BLF_translate_do_iface(), BLF_translate_do_tooltip(), and RNA_property_enum_items_gettexted().
const char* BLF_pgettext (const char * context, const char * message)
Definition at line 104 of file blf_translation.c.
References NULL, strlen(), and TEXT_DOMAIN_NAME.
Referenced by BLF_translate_do_iface(), BLF_translate_do_tooltip(), and RNA_property_enum_items_gettexted().
const char* BLF_translate_do_iface (const char * context, const char * msgid)
Definition at line 160 of file blf_translation.c.
References BLF_gettext(), BLF_pgettext(), and BLF_translate_iface().
const char* BLF_translate_do_tooltip (const char * context, const char * msgid)
Definition at line 177 of file blf_translation.c.
References BLF_gettext(), BLF_pgettext(), and BLF_translate_tooltips().
int BLF_translate_iface (void)
Definition at line 142 of file blf_translation.c.
References USER_DOTRANSLATE, and USER_TR_IFACE.
Referenced by BLF_translate_do_iface(), and RNA_property_enum_items_gettexted().
int BLF_translate_tooltips (void)
Definition at line 151 of file blf_translation.c.
References USER_DOTRANSLATE, and USER_TR_TOOLTIPS.
Referenced by BLF_translate_do_tooltip().