Blender: btPrimitiveTriangle Class Reference
btPrimitiveTriangle Class Reference
#include <btTriangleShapeEx.h>
Public Member Functions
btPrimitiveTriangle ()
SIMD_FORCE_INLINE void buildTriPlane ()
bool overlap_test_conservative (const btPrimitiveTriangle &other)
Test if triangles could collide.
SIMD_FORCE_INLINE void get_edge_plane (int edge_index, btVector4 &plane) const
Calcs the plane which is paralele to the edge and perpendicular to the triangle plane.
void applyTransform (const btTransform &t)
int clip_triangle (btPrimitiveTriangle &other, btVector3 *clipped_points)
Clips the triangle against this.
bool find_triangle_collision_clip_method (btPrimitiveTriangle &other, GIM_TRIANGLE_CONTACT &contacts)
Find collision using the clipping method.
Public Attributes
btVector3 m_vertices [3]
btVector4 m_plane
btScalar m_margin
btScalar m_dummy
Detailed Description
Definition at line 74 of file btTriangleShapeEx.h.
Constructor & Destructor Documentation
btPrimitiveTriangle::btPrimitiveTriangle () [inline]
Definition at line 81 of file btTriangleShapeEx.h.
Member Function Documentation
void btPrimitiveTriangle::applyTransform (const btTransform & t) [inline]
Definition at line 108 of file btTriangleShapeEx.h.
References m_vertices.
Referenced by btGImpactCollisionAlgorithm::collide_sat_triangles().
SIMD_FORCE_INLINE void btPrimitiveTriangle::buildTriPlane () [inline]
Definition at line 87 of file btTriangleShapeEx.h.
References cross(), dot(), m_plane, m_vertices, and btVector4::setValue().
Referenced by btGImpactCollisionAlgorithm::collide_sat_triangles().
int btPrimitiveTriangle::clip_triangle (btPrimitiveTriangle & other, btVector3 * clipped_points)
Clips the triangle against this.
Precondition:
clipped_points must have MAX_TRI_CLIPPING size, and this triangle must have its plane calculated.
Returns:
the number of clipped points
Definition at line 89 of file btTriangleShapeEx.cpp.
References bt_plane_clip_polygon(), bt_plane_clip_triangle(), get_edge_plane(), m_vertices, and MAX_TRI_CLIPPING.
Referenced by find_triangle_collision_clip_method().
bool btPrimitiveTriangle::find_triangle_collision_clip_method (btPrimitiveTriangle & other, GIM_TRIANGLE_CONTACT & contacts)
Find collision using the clipping method.
Precondition:
this triangle and other must have their triangles calculated
Definition at line 126 of file btTriangleShapeEx.cpp.
References clip_triangle(), GIM_TRIANGLE_CONTACT::copy_from(), m_margin, GIM_TRIANGLE_CONTACT::m_penetration_depth, m_plane, GIM_TRIANGLE_CONTACT::m_point_count, GIM_TRIANGLE_CONTACT::m_separating_normal, MAX_TRI_CLIPPING, and GIM_TRIANGLE_CONTACT::merge_points().
Referenced by btGImpactCollisionAlgorithm::collide_sat_triangles().
SIMD_FORCE_INLINE void btPrimitiveTriangle::get_edge_plane (int edge_index, btVector4 & plane) const [inline]
Calcs the plane which is paralele to the edge and perpendicular to the triangle plane.
Precondition:
this triangle must have its plane calculated.
Definition at line 101 of file btTriangleShapeEx.h.
References bt_edge_plane(), m_plane, and m_vertices.
Referenced by clip_triangle().
bool btPrimitiveTriangle::overlap_test_conservative (const btPrimitiveTriangle & other)
Test if triangles could collide.
class btPrimitiveTriangle
Definition at line 65 of file btTriangleShapeEx.cpp.
References bt_distance_point_plane(), m_margin, m_plane, and m_vertices.
Referenced by btGImpactCollisionAlgorithm::collide_sat_triangles().
Member Data Documentation
btScalar btPrimitiveTriangle::m_dummy
Definition at line 80 of file btTriangleShapeEx.h.
btScalar btPrimitiveTriangle::m_margin
Definition at line 79 of file btTriangleShapeEx.h.
Referenced by find_triangle_collision_clip_method(), btGImpactMeshShapePart::TrimeshPrimitiveManager::get_primitive_box(), btGImpactMeshShapePart::TrimeshPrimitiveManager::get_primitive_triangle(), and overlap_test_conservative().
btVector4 btPrimitiveTriangle::m_plane
Definition at line 78 of file btTriangleShapeEx.h.
Referenced by buildTriPlane(), find_triangle_collision_clip_method(), get_edge_plane(), and overlap_test_conservative().
btVector3 btPrimitiveTriangle::m_vertices[3]
Definition at line 77 of file btTriangleShapeEx.h.
Referenced by applyTransform(), buildTriPlane(), clip_triangle(), get_edge_plane(), btGImpactMeshShapePart::TrimeshPrimitiveManager::get_primitive_box(), btGImpactMeshShapePart::TrimeshPrimitiveManager::get_primitive_triangle(), overlap_test_conservative(), and btGImpactMeshShapePart::processAllTriangles().
The documentation for this class was generated from the following files:
btTriangleShapeEx.h
btTriangleShapeEx.cpp