Blender: MOD_shrinkwrap.c File Reference
MOD_shrinkwrap.c File Reference
modifiers
#include <string.h>
#include "DNA_object_types.h"
#include "BLI_string.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_modifier.h"
#include "BKE_shrinkwrap.h"
#include "depsgraph_private.h"
#include "MOD_util.h"
Functions
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static CustomDataMask requiredDataMask (Object *UNUSED(ob), ModifierData *md)
static int isDisabled (ModifierData *md, int UNUSED(useRenderParams))
static void foreachObjectLink (ModifierData *md, Object *ob, ObjectWalkFunc walk, void *userData)
static void deformVerts (ModifierData *md, Object *ob, DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static void deformVertsEM (ModifierData *md, Object *ob, struct BMEditMesh *editData, DerivedMesh *derivedData, float(*vertexCos)[3], int numVerts)
static void updateDepgraph (ModifierData *md, DagForest *forest, struct Scene *UNUSED(scene), Object *UNUSED(ob), DagNode *obNode)
Variables
ModifierTypeInfo modifierType_Shrinkwrap
Detailed Description
Definition in file MOD_shrinkwrap.c.
Function Documentation
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 63 of file MOD_shrinkwrap.c.
References ShrinkwrapModifierData::auxTarget, BLI_strncpy(), ShrinkwrapModifierData::keepDist, ShrinkwrapModifierData::projAxis, ShrinkwrapModifierData::shrinkOpts, ShrinkwrapModifierData::shrinkType, ShrinkwrapModifierData::subsurfLevels, ShrinkwrapModifierData::target, and ShrinkwrapModifierData::vgroup_name.
static void deformVerts (ModifierData * md, Object * ob, DerivedMesh * derivedData, float(*) vertexCos[3], int numVerts, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 113 of file MOD_shrinkwrap.c.
References get_cddm(), NULL, DerivedMesh::release, requiredDataMask(), and shrinkwrapModifier_deform().
static void deformVertsEM (ModifierData * md, Object * ob, struct BMEditMesh * editData, DerivedMesh * derivedData, float(*) vertexCos[3], int numVerts) [static]
Definition at line 133 of file MOD_shrinkwrap.c.
References get_cddm(), DerivedMesh::release, requiredDataMask(), and shrinkwrapModifier_deform().
static void foreachObjectLink (ModifierData * md, Object * ob, ObjectWalkFunc walk, void * userData) [static]
Definition at line 105 of file MOD_shrinkwrap.c.
References ShrinkwrapModifierData::auxTarget, and ShrinkwrapModifierData::target.
static void initData (ModifierData * md) [static]
Definition at line 52 of file MOD_shrinkwrap.c.
References ShrinkwrapModifierData::auxTarget, ShrinkwrapModifierData::keepDist, MOD_SHRINKWRAP_NEAREST_SURFACE, MOD_SHRINKWRAP_PROJECT_ALLOW_POS_DIR, NULL, ShrinkwrapModifierData::shrinkOpts, ShrinkwrapModifierData::shrinkType, and ShrinkwrapModifierData::target.
static int isDisabled (ModifierData * md, int UNUSEDuseRenderParams) [static]
Definition at line 98 of file MOD_shrinkwrap.c.
References ShrinkwrapModifierData::target.
static CustomDataMask requiredDataMask (Object * UNUSEDob, ModifierData * md) [static]
Definition at line 80 of file MOD_shrinkwrap.c.
References CD_MASK_MDEFORMVERT, CD_MASK_MVERT, MOD_SHRINKWRAP_PROJECT, MOD_SHRINKWRAP_PROJECT_OVER_NORMAL, ShrinkwrapModifierData::projAxis, ShrinkwrapModifierData::shrinkType, and ShrinkwrapModifierData::vgroup_name.
Referenced by deformVerts(), and deformVertsEM().
static void updateDepgraph (ModifierData * md, DagForest * forest, struct Scene * UNUSEDscene, Object * UNUSEDob, DagNode * obNode) [static]
Definition at line 148 of file MOD_shrinkwrap.c.
References ShrinkwrapModifierData::auxTarget, dag_add_relation(), dag_get_node(), DAG_RL_DATA_DATA, DAG_RL_OB_DATA, and ShrinkwrapModifierData::target.
Variable Documentation
ModifierTypeInfo modifierType_Shrinkwrap
Initial value:
 {
                  "Shrinkwrap",
            "ShrinkwrapModifierData",
            sizeof(ShrinkwrapModifierData),
                  eModifierTypeType_OnlyDeform,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_AcceptsCVs
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode,
              copyData,
           deformVerts,
        NULL,
         deformVertsEM,
      NULL,
         NULL,
       NULL,
              initData,
      requiredDataMask,
              NULL,
            isDisabled,
        updateDepgraph,
         NULL,
        NULL,
     foreachObjectLink,
         NULL,
        NULL,
}
Definition at line 163 of file MOD_shrinkwrap.c.