Blender: gim_contact_array Class Reference
gim_contact_array Class Reference
#include <gim_contact.h>
Public Member Functions
gim_contact_array ()
SIMD_FORCE_INLINE void push_contact (const btVector3 &point, const btVector3 &normal, GREAL depth, GUINT feature1, GUINT feature2)
SIMD_FORCE_INLINE void push_triangle_contacts (const GIM_TRIANGLE_CONTACT_DATA &tricontact, GUINT feature1, GUINT feature2)
void merge_contacts (const gim_contact_array &contacts, bool normal_contact_average=true)
void merge_contacts_unique (const gim_contact_array &contacts)
Detailed Description
Definition at line 125 of file gim_contact.h.
Constructor & Destructor Documentation
gim_contact_array::gim_contact_array () [inline]
Definition at line 128 of file gim_contact.h.
Member Function Documentation
void gim_contact_array::merge_contacts (const gim_contact_array & contacts, bool normal_contact_average = true)
Definition at line 35 of file gim_contact.cpp.
References gim_array< GIM_CONTACT >::back(), gim_array< T >::back(), btFabs(), gim_array< GIM_CONTACT >::clear(), CONTACT_DIFF_EPSILON, gim_heap_sort(), GUINT, i, GIM_CONTACT::interpolate_normals(), GIM_CONTACT::m_depth, GIM_CONTACT::m_normal, MAX_COINCIDENT, gim_array< GIM_CONTACT >::push_back(), gim_array< T >::resize(), and gim_array< T >::size().
void gim_contact_array::merge_contacts_unique (const gim_contact_array & contacts)
Definition at line 116 of file gim_contact.cpp.
References gim_array< T >::back(), gim_array< GIM_CONTACT >::clear(), GREAL, GUINT, i, GIM_CONTACT::m_depth, GIM_CONTACT::m_normal, GIM_CONTACT::m_point, gim_array< GIM_CONTACT >::push_back(), and gim_array< T >::size().
SIMD_FORCE_INLINE void gim_contact_array::push_contact (const btVector3 & point, const btVector3 & normal, GREAL depth, GUINT feature1, GUINT feature2) [inline]
Definition at line 132 of file gim_contact.h.
References gim_array< GIM_CONTACT >::back(), GIM_CONTACT::m_depth, GIM_CONTACT::m_feature1, GIM_CONTACT::m_feature2, GIM_CONTACT::m_normal, GIM_CONTACT::m_point, and gim_array< GIM_CONTACT >::push_back_mem().
SIMD_FORCE_INLINE void gim_contact_array::push_triangle_contacts (const GIM_TRIANGLE_CONTACT_DATA & tricontact, GUINT feature1, GUINT feature2) [inline]
Definition at line 144 of file gim_contact.h.
References gim_array< GIM_CONTACT >::back(), GUINT, i, GIM_CONTACT::m_depth, GIM_CONTACT::m_feature1, GIM_CONTACT::m_feature2, GIM_CONTACT::m_normal, GIM_TRIANGLE_CONTACT_DATA::m_penetration_depth, GIM_CONTACT::m_point, GIM_TRIANGLE_CONTACT_DATA::m_point_count, GIM_TRIANGLE_CONTACT_DATA::m_points, GIM_TRIANGLE_CONTACT_DATA::m_separating_normal, and gim_array< GIM_CONTACT >::push_back_mem().
The documentation for this class was generated from the following files:
gim_contact.h
gim_contact.cpp