Blender: volumetric.h File Reference
volumetric.h File Reference
Rendering
Defines
#define STEPSIZE_VIEW 0
#define STEPSIZE_SHADE 1
#define VOL_IS_BACKFACE 1
#define VOL_IS_SAMEMATERIAL 2
#define VOL_BOUNDS_DEPTH 0
#define VOL_BOUNDS_SS 1
#define VOL_SHADE_OUTSIDE 0
#define VOL_SHADE_INSIDE 1
Functions
float vol_get_density (struct ShadeInput *shi, const float co[3])
void vol_get_scattering (ShadeInput *shi, float scatter_col[3], const float co[3], const float view[3])
void shade_volume_outside (ShadeInput *shi, ShadeResult *shr)
void shade_volume_inside (ShadeInput *shi, ShadeResult *shr)
void shade_volume_shadow (struct ShadeInput *shi, struct ShadeResult *shr, struct Isect *last_is)
Detailed Description
Definition in file volumetric.h.
Define Documentation
#define STEPSIZE_SHADE 1
Definition at line 45 of file volumetric.h.
#define STEPSIZE_VIEW 0
Definition at line 44 of file volumetric.h.
#define VOL_BOUNDS_DEPTH 0
Definition at line 50 of file volumetric.h.
Referenced by shade_volume_shadow(), vol_get_bounds(), and volume_trace().
#define VOL_BOUNDS_SS 1
Definition at line 51 of file volumetric.h.
Referenced by vol_shade_one_lamp().
#define VOL_IS_BACKFACE 1
Definition at line 47 of file volumetric.h.
#define VOL_IS_SAMEMATERIAL 2
Definition at line 48 of file volumetric.h.
#define VOL_SHADE_INSIDE 1
Definition at line 54 of file volumetric.h.
Referenced by shade_volume_inside(), and volume_trace().
#define VOL_SHADE_OUTSIDE 0
Definition at line 53 of file volumetric.h.
Referenced by shade_volume_outside(), and volume_trace().
Function Documentation
void shade_volume_inside (ShadeInput * shi, ShadeResult * shr)
Definition at line 804 of file volumetric.c.
References ShadeResult::alpha, CLAMP(), MatInside::ma, ShadeInput::mat, ShadeInput::obi, MatInside::obi, ObjectInstanceRen::obr, ShadeInput::obr, R, VOL_SHADE_INSIDE, and volume_trace().
Referenced by shade_material_loop().
void shade_volume_outside (ShadeInput * shi, ShadeResult * shr)
Definition at line 797 of file volumetric.c.
References VOL_SHADE_OUTSIDE, and volume_trace().
Referenced by shade_input_do_shade(), and shade_ray().
void shade_volume_shadow (struct ShadeInput * shi, struct ShadeResult * shr, struct Isect * last_is)
Definition at line 749 of file volumetric.c.
References ShadeResult::alpha, ShadeInput::co, ShadeResult::combined, copy_v3_v3(), Isect::dist, Isect::face, ShadeInput::flippednor, Isect::hit, luminance(), Isect::ob, ShadeInput::obi, Isect::start, ShadeInput::view, ShadeInput::vlr, VOL_BOUNDS_DEPTH, vol_get_bounds(), and vol_get_transmittance().
Referenced by shade_ray().
float vol_get_density (struct ShadeInput * shi, const float co[3])
Definition at line 290 of file volumetric.c.
References VolumeSettings::density, VolumeSettings::density_scale, do_volume_tex(), MAP_DENSITY, Material::mapto_textured, ShadeInput::mat, metadensity(), NULL, ObjectRen::ob, OB_MBALL, ShadeInput::obi, ObjectInstanceRen::obr, R, Object::type, and Material::vol.
Referenced by vol_get_transmittance(), and volumeintegrate().
void vol_get_scattering (ShadeInput * shi, float scatter_col[3], const float co[3], const float view[3])
Definition at line 553 of file volumetric.c.
References add_v3_v3(), ListBase::first, get_lights(), GroupObject::lampren, Render::lights, GroupObject::next, vol_shade_one_lamp(), and zero_v3().
Referenced by vol_precache_part(), and volumeintegrate().