Blender: bNodeTreeType Struct Reference
bNodeTreeType Struct Reference
#include <BKE_node.h>
Public Attributes
int type
char idname [64]
ListBase node_types
void(* free_cache)(struct bNodeTree *ntree)
void(* free_node_cache)(struct bNodeTree *ntree, struct bNode *node)
void(* foreach_nodetree)(struct Main *main, void *calldata, bNodeTreeCallback func)
void(* foreach_nodeclass)(struct Scene *scene, void *calldata, bNodeClassCallback func)
void(* localize)(struct bNodeTree *localtree, struct bNodeTree *ntree)
void(* local_sync)(struct bNodeTree *localtree, struct bNodeTree *ntree)
void(* local_merge)(struct bNodeTree *localtree, struct bNodeTree *ntree)
void(* update)(struct bNodeTree *ntree)
void(* update_node)(struct bNodeTree *ntree, struct bNode *node)
int(* validate_link)(struct bNodeTree *ntree, struct bNodeLink *link)
ListBase(* internal_connect)(struct bNodeTree *, struct bNode *node)
Detailed Description
Definition at line 252 of file BKE_node.h.
Member Data Documentation
void(* bNodeTreeType::foreach_nodeclass)(struct Scene *scene, void *calldata, bNodeClassCallback func)
Definition at line 263 of file BKE_node.h.
Referenced by node_menu_add().
void(* bNodeTreeType::foreach_nodetree)(struct Main *main, void *calldata, bNodeTreeCallback func)
Definition at line 262 of file BKE_node.h.
Referenced by do_versions(), ED_node_generic_update(), lib_verify_nodetree(), ntreeMakeLocal(), and ntreeVerifyNodes().
void(* bNodeTreeType::free_cache)(struct bNodeTree *ntree)
Definition at line 260 of file BKE_node.h.
Referenced by ntreeFreeCache().
void(* bNodeTreeType::free_node_cache)(struct bNodeTree *ntree, struct bNode *node)
Definition at line 261 of file BKE_node.h.
Referenced by nodeFreeNode().
char bNodeTreeType::idname[64]
Definition at line 255 of file BKE_node.h.
ListBase(* bNodeTreeType::internal_connect)(struct bNodeTree *, struct bNode *node)
Definition at line 278 of file BKE_node.h.
Referenced by node_type_base().
void(* bNodeTreeType::local_merge)(struct bNodeTree *localtree, struct bNodeTree *ntree)
Definition at line 268 of file BKE_node.h.
Referenced by ntreeLocalMerge().
void(* bNodeTreeType::local_sync)(struct bNodeTree *localtree, struct bNodeTree *ntree)
Definition at line 267 of file BKE_node.h.
Referenced by ntreeLocalSync().
void(* bNodeTreeType::localize)(struct bNodeTree *localtree, struct bNodeTree *ntree)
Definition at line 266 of file BKE_node.h.
Referenced by ntreeLocalize().
ListBase bNodeTreeType::node_types
Definition at line 257 of file BKE_node.h.
Referenced by ED_init_node_butfuncs(), node_add_menu(), node_get_type(), node_tree_has_type(), nodeMakeDynamicType(), nodeRegisterType(), and ui_node_menu_column().
int bNodeTreeType::type
Definition at line 254 of file BKE_node.h.
void(* bNodeTreeType::update)(struct bNodeTree *ntree)
Definition at line 271 of file BKE_node.h.
Referenced by ntreeUpdateTree().
void(* bNodeTreeType::update_node)(struct bNodeTree *ntree, struct bNode *node)
Definition at line 273 of file BKE_node.h.
Referenced by nodeUpdate(), nodeUpdateID(), and ntreeUpdateTree().
int(* bNodeTreeType::validate_link)(struct bNodeTree *ntree, struct bNodeLink *link)
Definition at line 275 of file BKE_node.h.
Referenced by ntree_validate_links().
The documentation for this struct was generated from the following file:
BKE_node.h