Blender: rna_ID.c File Reference
rna_ID.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "RNA_access.h"
#include "RNA_define.h"
#include "DNA_ID.h"
#include "DNA_vfont_types.h"
#include "DNA_material_types.h"
#include "DNA_object_types.h"
#include "WM_types.h"
#include "rna_internal.h"
Functions
static void rna_def_ID_properties (BlenderRNA *brna)
static void rna_def_ID_materials (BlenderRNA *brna)
static void rna_def_ID (BlenderRNA *brna)
static void rna_def_library (BlenderRNA *brna)
void RNA_def_ID (BlenderRNA *brna)
Variables
EnumPropertyItem id_type_items []
Detailed Description
Definition in file rna_ID.c.
Function Documentation
static void rna_def_ID (BlenderRNA * brna) [static]
Definition at line 458 of file rna_ID.c.
References FUNC_USE_REPORTS, LIB_DOIT, LIB_FAKEUSER, LIB_ID_RECALC, LIB_ID_RECALC_DATA, MAX_ID_NAME, NA_RENAME, NC_ID, NULL, OB_RECALC_DATA, OB_RECALC_OB, OB_RECALC_TIME, PROP_BOOLEAN, PROP_EDITABLE, PROP_INT, PROP_LIB_EXCEPTION, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, RNA_def_enum_flag(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_editable_func(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_flag(), RNA_def_struct_idprops_func(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_ui_text(), PropertyRNA::srna, STRUCT_ID, and STRUCT_ID_REFCOUNT.
Referenced by RNA_def_ID().
void RNA_def_ID (BlenderRNA * brna)
Definition at line 558 of file rna_ID.c.
References NULL, rna_def_ID(), rna_def_ID_materials(), rna_def_ID_properties(), rna_def_library(), RNA_def_struct(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
static void rna_def_ID_materials (BlenderRNA * brna) [static]
Definition at line 433 of file rna_ID.c.
References MAXMAT, NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_ID().
static void rna_def_ID_properties (BlenderRNA * brna) [static]
Definition at line 346 of file rna_ID.c.
References NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_EXPORT, PROP_FLOAT, PROP_IDPROPERTY, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_flag(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_idprops_func(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_register_funcs(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_ID().
static void rna_def_library (BlenderRNA * brna) [static]
Definition at line 540 of file rna_ID.c.
References NULL, PROP_FILEPATH, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
Referenced by RNA_def_ID().
Variable Documentation
EnumPropertyItem id_type_items[]
Initial value:
 {
    {ID_AC, "ACTION", ICON_ACTION, "Action", ""},
    {ID_AR, "ARMATURE", ICON_ARMATURE_DATA, "Armature", ""},
    {ID_BR, "BRUSH", ICON_BRUSH_DATA, "Brush", ""},
    {ID_CA, "CAMERA", ICON_CAMERA_DATA, "Camera", ""},
    {ID_CU, "CURVE", ICON_CURVE_DATA, "Curve", ""},
    {ID_VF, "FONT", ICON_FONT_DATA, "Font", ""},
    {ID_GD, "GREASEPENCIL", ICON_GREASEPENCIL, "Grease Pencil", ""},
    {ID_GR, "GROUP", ICON_GROUP, "Group", ""},
    {ID_IM, "IMAGE", ICON_IMAGE_DATA, "Image", ""},
    {ID_KE, "KEY", ICON_SHAPEKEY_DATA, "Key", ""},
    {ID_LA, "LAMP", ICON_LAMP_DATA, "Lamp", ""},
    {ID_LI, "LIBRARY", ICON_LIBRARY_DATA_DIRECT, "Library", ""},
    {ID_LT, "LATTICE", ICON_LATTICE_DATA, "Lattice", ""},
    {ID_MA, "MATERIAL", ICON_MATERIAL_DATA, "Material", ""},
    {ID_MB, "META", ICON_META_DATA, "MetaBall", ""},
    {ID_ME, "MESH", ICON_MESH_DATA, "Mesh", ""},
    {ID_NT, "NODETREE", ICON_NODETREE, "NodeTree", ""},
    {ID_OB, "OBJECT", ICON_OBJECT_DATA, "Object", ""},
    {ID_PA, "PARTICLE", ICON_PARTICLE_DATA, "Particle", ""},
    {ID_SCE, "SCENE", ICON_SCENE_DATA, "Scene", ""},
    {ID_SCR, "SCREEN", ICON_SPLITSCREEN, "Screen", ""},
    {ID_SPK, "SPEAKER", ICON_SPEAKER, "Speaker", ""},
    {ID_SO, "SOUND", ICON_PLAY_AUDIO, "Sound", ""},
    {ID_TXT, "TEXT", ICON_TEXT, "Text", ""},
    {ID_TE, "TEXTURE", ICON_TEXTURE_DATA, "Texture", ""},
    {ID_WO, "WORLD", ICON_WORLD_DATA, "World", ""},
    {ID_WM, "WINDOWMANAGER", ICON_FULLSCREEN, "Window Manager", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 46 of file rna_ID.c.
Referenced by list_item_row(), rna_def_action(), rna_def_drivertarget(), and rna_def_keyingset_path().