Blender: FilterColor.cpp File Reference
FilterColor.cpp File Reference
BGE Video Texture
#include <PyObjectPlus.h>
#include <structmember.h>
#include "FilterColor.h"
#include "FilterBase.h"
#include "PyTypeList.h"
Functions
FilterColor * getFilterColor (PyFilter *self)
static PyObject * getMatrix (PyFilter *self, void *closure)
static int setMatrix (PyFilter *self, PyObject *value, void *closure)
FilterLevel * getFilterLevel (PyFilter *self)
static PyObject * getLevels (PyFilter *self, void *closure)
static int setLevels (PyFilter *self, PyObject *value, void *closure)
Variables
static PyGetSetDef filterGrayGetSets []
PyTypeObject FilterGrayType
static PyGetSetDef filterColorGetSets []
PyTypeObject FilterColorType
static PyGetSetDef filterLevelGetSets []
PyTypeObject FilterLevelType
Detailed Description
Definition in file FilterColor.cpp.
Function Documentation
FilterColor* getFilterColor (PyFilter * self) [inline]
Definition at line 111 of file FilterColor.cpp.
Referenced by getMatrix(), and setMatrix().
FilterLevel* getFilterLevel (PyFilter * self) [inline]
Definition at line 246 of file FilterColor.cpp.
Referenced by getLevels(), and setLevels().
static PyObject* getLevels (PyFilter * self, void * closure) [static]
Definition at line 253 of file FilterColor.cpp.
References getFilterLevel(), and FilterLevel::getLevels().
static PyObject* getMatrix (PyFilter * self, void * closure) [static]
Definition at line 118 of file FilterColor.cpp.
References getFilterColor(), and FilterColor::getMatrix().
Referenced by TransformReader::dae_matrix_to_mat4().
static int setLevels (PyFilter * self, PyObject * value, void * closure) [static]
Definition at line 262 of file FilterColor.cpp.
References getFilterLevel(), and FilterLevel::setLevels().
static int setMatrix (PyFilter * self, PyObject * value, void * closure) [static]
Definition at line 129 of file FilterColor.cpp.
References getFilterColor(), and FilterColor::setMatrix().
Variable Documentation
PyGetSetDef filterColorGetSets[] [static]
Initial value:
{
    {(char*)"matrix", (getter)getMatrix, (setter)setMatrix, (char*)"matrix [4][5] for color calculation", NULL},
    {(char*)"previous", (getter)Filter_getPrevious, (setter)Filter_setPrevious, (char*)"previous pixel filter", NULL},
    {NULL}
}
Definition at line 167 of file FilterColor.cpp.
PyTypeObject FilterColorType
Definition at line 176 of file FilterColor.cpp.
Referenced by registerAllTypes().
PyGetSetDef filterGrayGetSets[] [static]
Initial value:
{
    {(char*)"previous", (getter)Filter_getPrevious, (setter)Filter_setPrevious, (char*)"previous pixel filter", NULL},
    {NULL}
}
Definition at line 38 of file FilterColor.cpp.
PyTypeObject FilterGrayType
Definition at line 45 of file FilterColor.cpp.
Referenced by registerAllTypes().
PyGetSetDef filterLevelGetSets[] [static]
Initial value:
{
    {(char*)"levels", (getter)getLevels, (setter)setLevels, (char*)"levels matrix [4] (min, max)", NULL},
    {(char*)"previous", (getter)Filter_getPrevious, (setter)Filter_setPrevious, (char*)"previous pixel filter", NULL},
    {NULL}
}
Definition at line 300 of file FilterColor.cpp.
PyTypeObject FilterLevelType
Definition at line 309 of file FilterColor.cpp.
Referenced by registerAllTypes().