Blender: codecs.c File Reference
codecs.c File Reference
AVI
#include "AVI_avi.h"
#include "avi_intern.h"
#include "avirgb.h"
#include "mjpeg.h"
#include "rgb32.h"
Functions
void * avi_format_convert (AviMovie *movie, int stream, void *buffer, AviFormat from, AviFormat to, int *size)
int avi_get_data_id (AviFormat format, int stream)
int avi_get_format_type (AviFormat format)
int avi_get_format_fcc (AviFormat format)
int avi_get_format_compression (AviFormat format)
Detailed Description
Definition in file codecs.c.
Function Documentation
void* avi_format_convert (AviMovie * movie, int stream, void * buffer, AviFormat from, AviFormat to, int * size)
Definition at line 43 of file codecs.c.
References avi_converter_from_avi_rgb(), avi_converter_from_mjpeg(), avi_converter_from_rgb32(), avi_converter_to_avi_rgb(), avi_converter_to_mjpeg(), avi_converter_to_rgb32(), AVI_FORMAT_AVI_RGB, avi_format_convert(), AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, and AVI_FORMAT_RGB32.
Referenced by avi_format_convert(), AVI_read_frame(), and AVI_write_frame().
int avi_get_data_id (AviFormat format, int stream)
Definition at line 86 of file codecs.c.
References avi_get_format_type(), and FCC.
Referenced by AVI_write_frame().
int avi_get_format_compression (AviFormat format)
Definition at line 132 of file codecs.c.
References AVI_FORMAT_AVI_RGB, AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, AVI_FORMAT_RGB32, and FCC.
Referenced by AVI_open_compress().
int avi_get_format_fcc (AviFormat format)
Definition at line 115 of file codecs.c.
References AVI_FORMAT_AVI_RGB, AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, AVI_FORMAT_RGB32, and FCC.
Referenced by AVI_open_compress().
int avi_get_format_type (AviFormat format)
Definition at line 100 of file codecs.c.
References AVI_FORMAT_AVI_RGB, AVI_FORMAT_MJPEG, AVI_FORMAT_RGB24, AVI_FORMAT_RGB32, and FCC.
Referenced by avi_get_data_id(), AVI_open_compress(), and AVI_set_compress_option().