Blender: btSimpleBroadphaseProxy Struct Reference
btSimpleBroadphaseProxy Struct Reference
#include <btSimpleBroadphase.h>
Public Member Functions
btSimpleBroadphaseProxy ()
btSimpleBroadphaseProxy (const btVector3 &minpt, const btVector3 &maxpt, int shapeType, void *userPtr, short int collisionFilterGroup, short int collisionFilterMask, void *multiSapProxy)
SIMD_FORCE_INLINE void SetNextFree (int next)
SIMD_FORCE_INLINE int GetNextFree () const
Public Attributes
int m_nextFree
Detailed Description
Definition at line 23 of file btSimpleBroadphase.h.
Constructor & Destructor Documentation
btSimpleBroadphaseProxy::btSimpleBroadphaseProxy () [inline]
Definition at line 30 of file btSimpleBroadphase.h.
btSimpleBroadphaseProxy::btSimpleBroadphaseProxy (const btVector3 & minpt, const btVector3 & maxpt, int shapeType, void * userPtr, short int collisionFilterGroup, short int collisionFilterMask, void * multiSapProxy) [inline]
Definition at line 32 of file btSimpleBroadphase.h.
Member Function Documentation
SIMD_FORCE_INLINE int btSimpleBroadphaseProxy::GetNextFree () const [inline]
Definition at line 40 of file btSimpleBroadphase.h.
References m_nextFree.
Referenced by btSimpleBroadphase::allocHandle().
SIMD_FORCE_INLINE void btSimpleBroadphaseProxy::SetNextFree (int next) [inline]
Definition at line 39 of file btSimpleBroadphase.h.
References m_nextFree, and next.
Referenced by btSimpleBroadphase::btSimpleBroadphase(), and btSimpleBroadphase::freeHandle().
Member Data Documentation
int btSimpleBroadphaseProxy::m_nextFree
Definition at line 25 of file btSimpleBroadphase.h.
Referenced by GetNextFree(), and SetNextFree().
The documentation for this struct was generated from the following file:
btSimpleBroadphase.h