Blender: IK_QJacobian Class Reference
IK_QJacobian Class Reference
#include <IK_QJacobian.h>
Public Types
typedef TNT::Matrix< MT_Scalar > TMatrix
typedef TNT::Vector< MT_Scalar > TVector
Public Member Functions
IK_QJacobian ()
~IK_QJacobian ()
void ArmMatrices (int dof, int task_size)
void SetDoFWeight (int dof, MT_Scalar weight)
void SetBetas (int id, int size, const MT_Vector3 &v)
void SetDerivatives (int id, int dof_id, const MT_Vector3 &v, MT_Scalar norm_weight)
void Invert ()
MT_Scalar AngleUpdate (int dof_id) const
MT_Scalar AngleUpdateNorm () const
void Lock (int dof_id, MT_Scalar delta)
bool ComputeNullProjection ()
void Restrict (TVector &d_theta, TMatrix &null)
void SubTask (IK_QJacobian &jacobian)
Detailed Description
Definition at line 43 of file IK_QJacobian.h.
Member Typedef Documentation
typedef TNT::Matrix<MT_Scalar> IK_QJacobian::TMatrix
Definition at line 46 of file IK_QJacobian.h.
typedef TNT::Vector<MT_Scalar> IK_QJacobian::TVector
Definition at line 47 of file IK_QJacobian.h.
Constructor & Destructor Documentation
IK_QJacobian::IK_QJacobian ()
Definition at line 37 of file IK_QJacobian.cpp.
IK_QJacobian::~IK_QJacobian ()
Definition at line 42 of file IK_QJacobian.cpp.
Member Function Documentation
MT_Scalar IK_QJacobian::AngleUpdate (int dof_id) const
Definition at line 423 of file IK_QJacobian.cpp.
Referenced by SubTask(), IK_QSwingSegment::UpdateAngle(), IK_QTranslateSegment::UpdateAngle(), IK_QSphericalSegment::UpdateAngle(), IK_QRevoluteSegment::UpdateAngle(), and IK_QElbowSegment::UpdateAngle().
MT_Scalar IK_QJacobian::AngleUpdateNorm () const
Definition at line 428 of file IK_QJacobian.cpp.
References i, MT_abs(), and TNT::Vector< T >::size().
Referenced by IK_QJacobianSolver::Solve().
void IK_QJacobian::ArmMatrices (int dof, int task_size)
Definition at line 46 of file IK_QJacobian.cpp.
References TNT::Matrix< T >::newsize(), and TNT::Vector< T >::newsize().
Referenced by IK_QJacobianSolver::Setup().
bool IK_QJacobian::ComputeNullProjection ()
Definition at line 144 of file IK_QJacobian.cpp.
References KDL::epsilon, i, TNT::matmult(), TNT::Matrix< T >::num_cols(), TNT::Matrix< T >::num_rows(), TNT::Vector< T >::size(), and transpose().
Referenced by SubTask().
void IK_QJacobian::Invert ()
Definition at line 123 of file IK_QJacobian.cpp.
References TNT::SVD(), and transpose().
Referenced by IK_QJacobianSolver::Solve(), and SubTask().
void IK_QJacobian::Lock (int dof_id, MT_Scalar delta)
Definition at line 410 of file IK_QJacobian.cpp.
References i.
Referenced by IK_QRevoluteSegment::Lock(), IK_QTranslateSegment::Lock(), IK_QElbowSegment::Lock(), IK_QSphericalSegment::Lock(), and IK_QSwingSegment::Lock().
void IK_QJacobian::Restrict (TVector & d_theta, TMatrix & null)
Definition at line 200 of file IK_QJacobian.cpp.
References TNT::matmult(), and TNT::Vector< T >::size().
Referenced by SubTask().
void IK_QJacobian::SetBetas (int id, int size, const MT_Vector3 & v)
Definition at line 107 of file IK_QJacobian.cpp.
References MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
Referenced by IK_QCenterOfMassTask::ComputeJacobian(), IK_QOrientationTask::ComputeJacobian(), and IK_QPositionTask::ComputeJacobian().
void IK_QJacobian::SetDerivatives (int id, int dof_id, const MT_Vector3 & v, MT_Scalar norm_weight)
Definition at line 114 of file IK_QJacobian.cpp.
References MT_Tuple3::x(), MT_Tuple3::y(), and MT_Tuple3::z().
Referenced by IK_QOrientationTask::ComputeJacobian(), and IK_QPositionTask::ComputeJacobian().
void IK_QJacobian::SetDoFWeight (int dof, MT_Scalar weight)
Definition at line 442 of file IK_QJacobian.cpp.
References sqrt().
Referenced by IK_QJacobianSolver::Setup().
void IK_QJacobian::SubTask (IK_QJacobian & jacobian)
Definition at line 181 of file IK_QJacobian.cpp.
References AngleUpdate(), ComputeNullProjection(), i, Invert(), Restrict(), and TNT::Vector< T >::size().
Referenced by IK_QJacobianSolver::Solve().
The documentation for this class was generated from the following files:
IK_QJacobian.h
IK_QJacobian.cpp