Blender: rna_mesh_api.c File Reference
rna_mesh_api.c File Reference
RNA
#include <stdlib.h>
#include <stdio.h>
#include "RNA_define.h"
#include "BLO_sys_types.h"
#include "BKE_mesh.h"
#include "ED_mesh.h"
Functions
void RNA_api_mesh (StructRNA *srna)
Detailed Description
Definition in file rna_mesh_api.c.
Function Documentation
void RNA_api_mesh (StructRNA * srna)
Definition at line 55 of file rna_mesh_api.c.
References FUNC_USE_CONTEXT, NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_float_matrix(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string().
Referenced by rna_def_mesh().