Blender: BKE_key.h File Reference
BKE_key.h File Reference
blenkernel
Functions
void free_key (struct Key *sc)
void free_key_nolib (struct Key *key)
struct Key * add_key (struct ID *id)
struct Key * copy_key (struct Key *key)
struct Key * copy_key_nolib (struct Key *key)
void make_local_key (struct Key *key)
void sort_keys (struct Key *key)
void key_curve_position_weights (float t, float *data, int type)
void key_curve_tangent_weights (float t, float *data, int type)
void key_curve_normal_weights (float t, float *data, int type)
float * do_ob_key (struct Scene *scene, struct Object *ob)
struct Key * ob_get_key (struct Object *ob)
struct KeyBlock * add_keyblock (struct Key *key, const char *name)
struct KeyBlock * add_keyblock_ctime (struct Key *key, const char *name, const short do_force)
struct KeyBlock * ob_get_keyblock (struct Object *ob)
struct KeyBlock * ob_get_reference_keyblock (struct Object *ob)
struct KeyBlock * key_get_keyblock (struct Key *key, int index)
struct KeyBlock * key_get_named_keyblock (struct Key *key, const char name[])
char * key_get_curValue_rnaPath (struct Key *key, struct KeyBlock *kb)
void do_rel_key (const int start, int end, const int tot, char *basispoin, struct Key *key, struct KeyBlock *actkb, const int mode)
void key_to_mesh (struct KeyBlock *kb, struct Mesh *me)
void mesh_to_key (struct Mesh *me, struct KeyBlock *kb)
void key_to_latt (struct KeyBlock *kb, struct Lattice *lt)
void latt_to_key (struct Lattice *lt, struct KeyBlock *kb)
void key_to_curve (struct KeyBlock *kb, struct Curve *cu, struct ListBase *nurb)
void curve_to_key (struct Curve *cu, struct KeyBlock *kb, struct ListBase *nurb)
float(* key_to_vertcos (struct Object *ob, struct KeyBlock *kb))[3]
void vertcos_to_key (struct Object *ob, struct KeyBlock *kb, float(*vertCos)[3])
void offset_to_key (struct Object *ob, struct KeyBlock *kb, float(*ofs)[3])
Variables
int slurph_opt
Detailed Description
Since:
March 2001
Author:
nzc
Definition in file BKE_key.h.
Function Documentation
struct Key* add_key (struct ID * id) [read]
Definition at line 124 of file key.c.
References alloc_libblock(), Key::elemsize, Key::elemstr, Key::from, G, GS, ID_CU, ID_KE, ID_LT, ID_ME, IPO_BPOINT, IPO_FLOAT, KEY_NORMAL, ID::name, Key::type, and Key::uidgen.
Referenced by insert_curvekey(), insert_lattkey(), insert_meshkey(), join_mesh_exec(), join_mesh_shapes_exec(), and modifier_apply_shape().
struct KeyBlock* add_keyblock (struct Key * key, const char * name) [read]
Note:
caller may want to set this to current time, but don't do it here since we need to sort which could cause problems in some cases, see add_keyblock_ctime
Definition at line 1414 of file key.c.
References BLI_addtail(), BLI_countlist(), BLI_snprintf(), BLI_strncpy(), BLI_uniquename(), Key::block, KEY_CARDINAL, ListBase::last, MEM_callocN(), KeyBlock::name, KeyBlock::pos, Key::refkey, KeyBlock::slidermax, KeyBlock::slidermin, Key::totkey, KeyBlock::type, KeyBlock::uid, and Key::uidgen.
Referenced by add_keyblock_ctime(), BM_mesh_bm_to_me(), join_mesh_shapes_exec(), modifier_apply_shape(), and shapekey_layers_to_keyblocks().
struct KeyBlock* add_keyblock_ctime (Key * key, const char * name, const short do_force) [read]
Note:
sorting is a problematic side effect in some cases, better only do this explicitly by having its own function,
Parameters:
do_force always use ctime even for relative keys.
Definition at line 1460 of file key.c.
References add_keyblock(), Key::ctime, KEY_RELATIVE, KeyBlock::pos, sort_keys(), and Key::type.
Referenced by insert_curvekey(), insert_lattkey(), and insert_meshkey().
struct Key* copy_key (struct Key * key) [read]
Definition at line 173 of file key.c.
References BLI_duplicatelist(), Key::block, copy_libblock(), KeyBlock::data, ListBase::first, Key::id, MEM_dupallocN(), KeyBlock::next, NULL, and Key::refkey.
Referenced by BL_ShapeDeformer::BL_ShapeDeformer(), copy_curve(), copy_lattice(), copy_mesh(), id_copy(), and join_mesh_exec().
struct Key* copy_key_nolib (struct Key * key) [read]
Definition at line 199 of file key.c.
References Key::adt, BLI_duplicatelist(), Key::block, KeyBlock::data, ListBase::first, MEM_dupallocN(), KeyBlock::next, NULL, and Key::refkey.
Referenced by editbtMesh_to_undoMesh().
void curve_to_key (struct Curve * cu, struct KeyBlock * kb, struct ListBase * nurb)
Definition at line 1588 of file key.c.
References BPoint::alfa, BezTriple::alfa, Nurb::bezt, Nurb::bp, copy_v3_v3(), count_curveverts(), KeyBlock::data, Key::elemsize, ListBase::first, Curve::key, MEM_callocN(), MEM_freeN(), Nurb::next, Nurb::pntsu, Nurb::pntsv, KeyBlock::totelem, BPoint::vec, and BezTriple::vec.
Referenced by insert_curvekey().
float* do_ob_key (struct Scene * scene, struct Object * ob)
Definition at line 1309 of file key.c.
References Key::adt, ADT_RECALC_DRIVERS, Nurb::bezt, BKE_animsys_evaluate_animdata(), BLI_findlink(), Key::block, Nurb::bp, RenderData::cfra, cp_cu_key(), cp_key(), Object::data, do_curve_key(), do_latt_key(), do_mesh_key(), ELEM, ListBase::first, KeyBlock::flag, Key::from, get_weights_array(), Key::id, if(), KEYBLOCK_MUTE, MEM_callocN(), MEM_freeN(), Nurb::next, NULL, Curve::nurb, OB_CURVE, ob_get_key(), ob_get_keyblock(), OB_LATTICE, OB_MESH, OB_SHAPE_LOCK, OB_SURF, OB_TYPE_SUPPORT_VGROUP, Nurb::pntsu, Lattice::pntsu, Nurb::pntsv, Lattice::pntsv, Lattice::pntsw, Scene::r, Key::refkey, Object::shapeflag, Object::shapenr, size(), Mesh::totvert, Object::type, and KeyBlock::vgroup.
Referenced by curve_calc_modifiers_pre(), deformVerts(), insert_curvekey(), insert_lattkey(), and insert_meshkey().
void do_rel_key (const int start, int end, const int tot, char * basispoin, struct Key * key, struct KeyBlock * actkb, const int mode)
Definition at line 719 of file key.c.
References BLI_assert, BLI_findlink(), Key::block, cp_key(), KeyBlock::curval, Key::elemsize, Key::elemstr, ListBase::first, KeyBlock::flag, IPO_BEZTRIPLE, IPO_BPOINT, IPO_FLOAT, key_block_get_data(), KEY_MODE_BEZTRIPLE, key_pointer_size(), KEYBLOCK_MUTE, MEM_freeN(), KeyBlock::next, NULL, Key::refkey, rel_flerp(), KeyBlock::relative, KeyBlock::totelem, and KeyBlock::weights.
Referenced by do_latt_key(), do_mesh_key(), do_rel_cu_key(), and BL_ShapeDeformer::Update().
void free_key (struct Key * sc)
Definition at line 81 of file key.c.
References BKE_free_animdata(), BLI_remlink(), KeyBlock::data, and MEM_freeN().
Referenced by free_libblock(), free_undo(), join_mesh_exec(), and BL_ShapeDeformer::~BL_ShapeDeformer().
void free_key_nolib (struct Key * key)
Definition at line 97 of file key.c.
References BLI_remlink(), Key::block, KeyBlock::data, ListBase::first, and MEM_freeN().
void key_curve_normal_weights (float t, float * data, int type)
Definition at line 336 of file key.c.
References KEY_BSPLINE, KEY_CARDINAL, and KEY_LINEAR.
void key_curve_position_weights (float t, float * data, int type)
Definition at line 274 of file key.c.
References KEY_BSPLINE, KEY_CARDINAL, and KEY_LINEAR.
Referenced by alfa_bezpart(), calc_latt_deform(), do_colorband(), psys_interpolate_particle(), setkeys(), strand_eval_point(), and where_on_path().
void key_curve_tangent_weights (float t, float * data, int type)
Definition at line 306 of file key.c.
References KEY_BSPLINE, KEY_CARDINAL, and KEY_LINEAR.
Referenced by strand_eval_point(), and where_on_path().
char* key_get_curValue_rnaPath (struct Key * key, struct KeyBlock * kb)
Definition at line 1527 of file key.c.
References ELEM, Key::id, NULL, RNA_path_from_ID_to_property(), RNA_pointer_create(), RNA_ShapeKey, and RNA_struct_find_property().
Referenced by achannel_setting_slider_shapekey_cb(), ANIM_channel_draw_widgets(), and make_new_animlistelem().
struct KeyBlock* key_get_keyblock (struct Key * key, int index) [read]
Definition at line 1496 of file key.c.
References Key::block, ListBase::first, i, KeyBlock::next, NULL, and Key::totkey.
Referenced by get_orco_coords_dm().
struct KeyBlock* key_get_named_keyblock (struct Key * key, const char name[]) [read]
Definition at line 1516 of file key.c.
References BLI_findstring(), Key::block, and NULL.
Referenced by join_mesh_exec(), and sculpt_undo_restore_coords().
void key_to_curve (struct KeyBlock * kb, struct Curve * cu, struct ListBase * nurb)
Referenced by ED_object_shape_key_remove(), and make_editNurb().
void key_to_latt (struct KeyBlock * kb, struct Lattice * lt)
Definition at line 1570 of file key.c.
References copy_v3_v3(), KeyBlock::data, Lattice::def, MIN2, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, KeyBlock::totelem, and BPoint::vec.
Referenced by ED_object_shape_key_remove(), and make_editLatt().
void key_to_mesh (struct KeyBlock * kb, struct Mesh * me)
Definition at line 1711 of file key.c.
References MVert::co, copy_v3_v3(), KeyBlock::data, MIN2, Mesh::mvert, KeyBlock::totelem, and Mesh::totvert.
Referenced by ED_object_shape_key_remove(), and mesh_create_derived_for_modifier().
float(* key_to_vertcos (struct Object * ob, struct KeyBlock * kb))[3]
Definition at line 1728 of file key.c.
References co, copy_v3_v3(), count_curveverts(), KeyBlock::data, ELEM, ListBase::first, i, MEM_callocN(), NULL, Curve::nurb, OB_CURVE, OB_LATTICE, OB_MESH, OB_SURF, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, and Mesh::totvert.
Referenced by sculpt_undo_restore_coords(), sculpt_update_mesh_elements(), and sculpt_vertcos_to_key().
void latt_to_key (struct Lattice * lt, struct KeyBlock * kb)
Definition at line 1549 of file key.c.
References copy_v3_v3(), KeyBlock::data, Lattice::def, Key::elemsize, Lattice::key, MEM_callocN(), MEM_freeN(), Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, KeyBlock::totelem, and BPoint::vec.
Referenced by insert_lattkey().
void make_local_key (struct Key * key)
Definition at line 226 of file key.c.
References Key::id, ID::lib, new_id(), and NULL.
Referenced by id_make_local().
void mesh_to_key (struct Mesh * me, struct KeyBlock * kb)
Definition at line 1690 of file key.c.
References MVert::co, copy_v3_v3(), KeyBlock::data, Key::elemsize, Mesh::key, MEM_callocN(), MEM_freeN(), Mesh::mvert, KeyBlock::totelem, and Mesh::totvert.
Referenced by insert_meshkey(), join_mesh_shapes_exec(), and modifier_apply_shape().
struct Key* ob_get_key (struct Object * ob) [read]
Definition at line 1395 of file key.c.
References Object::data, ELEM, Lattice::key, Curve::key, Mesh::key, NULL, OB_CURVE, OB_LATTICE, OB_MESH, OB_SURF, and Object::type.
Referenced by actedit_get_shapekeys(), animdata_filter_dopesheet_ob(), build_dag_object(), dag_id_flush_update(), deformMatrices(), deformMatricesEM(), deformVertsEM(), do_ob_key(), draw_mesh_object(), draw_selected_name(), ED_object_shape_key_add(), ED_object_shape_key_remove(), get_orco_coords_dm(), modifiers_getVirtualModifierList(), ob_get_keyblock(), ob_get_reference_keyblock(), object_add_duplicate_internal(), object_frame_has_keyframe(), object_is_modified(), object_shape_key_mirror(), sculpt_undo_restore_coords(), shape_key_clear_exec(), shape_key_move_exec(), shape_key_retime_exec(), and special_aftertrans_update().
struct KeyBlock* ob_get_keyblock (struct Object * ob) [read]
Definition at line 1473 of file key.c.
References BLI_findlink(), Key::block, NULL, ob_get_key(), and Object::shapenr.
Referenced by deformMatrices(), deformMatricesEM(), deformVerts(), do_curve_key(), do_latt_key(), do_mesh_key(), do_ob_key(), make_editLatt(), make_editNurb(), sculpt_update_mesh_elements(), shape_key_clear_exec(), shape_key_retime_exec(), and stats_string().
struct KeyBlock* ob_get_reference_keyblock (struct Object * ob) [read]
Definition at line 1485 of file key.c.
References NULL, ob_get_key(), and Key::refkey.
void offset_to_key (struct Object * ob, struct KeyBlock * kb, float(*) ofs[3])
Definition at line 1884 of file key.c.
References add_v3_v3(), co, Object::data, KeyBlock::data, ELEM, ListBase::first, i, if(), Curve::nurb, OB_CURVE, OB_LATTICE, OB_MESH, OB_SURF, KeyBlock::totelem, and Object::type.
Referenced by sculpt_vertcos_to_key().
void sort_keys (struct Key * key)
Definition at line 244 of file key.c.
References BLI_insertlink(), BLI_remlink(), Key::block, ListBase::first, KeyBlock::next, KeyBlock::pos, KeyBlock::prev, and Key::refkey.
Referenced by add_keyblock_ctime().
void vertcos_to_key (struct Object * ob, struct KeyBlock * kb, float(*) vertCos[3])
Definition at line 1804 of file key.c.
References co, copy_v3_v3(), count_curveverts(), Object::data, KeyBlock::data, ELEM, Key::elemsize, ListBase::first, i, Curve::key, Lattice::key, Mesh::key, MEM_callocN(), MEM_freeN(), NULL, Curve::nurb, OB_CURVE, OB_LATTICE, OB_MESH, OB_SURF, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, Mesh::totvert, and Object::type.
Referenced by sculpt_vertcos_to_key().
Variable Documentation
int slurph_opt
Definition at line 78 of file key.c.
Referenced by database_fromscene_vectors(), do_curve_key(), do_mesh_key(), and RE_Database_FromScene().