Blender: btSparseSdf< CELLSIZE > Struct Template Reference
btSparseSdf< CELLSIZE > Struct Template Reference
#include <btSparseSDF.h>
Classes
struct Cell
struct IntFrac
Public Member Functions
void Initialize (int hashsize=2383)
void Reset ()
void GarbageCollect (int lifetime=256)
int RemoveReferences (btCollisionShape *pcs)
btScalar Evaluate (const btVector3 &x, btCollisionShape *shape, btVector3 &normal, btScalar margin)
void BuildCell (Cell &c)
Static Public Member Functions
static btScalar DistanceToShape (const btVector3 &x, btCollisionShape *shape)
static IntFrac Decompose (btScalar x)
static btScalar Lerp (btScalar a, btScalar b, btScalar t)
static unsigned int Hash (int x, int y, int z, btCollisionShape *shape)
Public Attributes
btAlignedObjectArray< Cell * > cells
btScalar voxelsz
int puid
int ncells
int nprobes
int nqueries
Detailed Description
template<const int CELLSIZE>
struct btSparseSdf< CELLSIZE >
Definition at line 44 of file btSparseSDF.h.
Member Function Documentation
template<const int CELLSIZE> void btSparseSdf< CELLSIZE >::BuildCell (Cell & c) [inline]
Definition at line 228 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate().
template<const int CELLSIZE> static IntFrac btSparseSdf< CELLSIZE >::Decompose (btScalar x) [inline, static]
Definition at line 264 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate().
template<const int CELLSIZE> static btScalar btSparseSdf< CELLSIZE >::DistanceToShape (const btVector3 & x, btCollisionShape * shape) [inline, static]
Definition at line 250 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::BuildCell().
template<const int CELLSIZE> btScalar btSparseSdf< CELLSIZE >::Evaluate (const btVector3 & x, btCollisionShape * shape, btVector3 & normal, btScalar margin) [inline]
Definition at line 154 of file btSparseSDF.h.
Referenced by btSoftBody::checkContact().
template<const int CELLSIZE> void btSparseSdf< CELLSIZE >::GarbageCollect (int lifetime = 256) [inline]
Todo:
: Reset puid's when int range limit is reached */
Definition at line 106 of file btSparseSDF.h.
template<const int CELLSIZE> static unsigned int btSparseSdf< CELLSIZE >::Hash (int x, int y, int z, btCollisionShape * shape) [inline, static]
Definition at line 285 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate().
template<const int CELLSIZE> void btSparseSdf< CELLSIZE >::Initialize (int hashsize = 2383) [inline]
Definition at line 80 of file btSparseSDF.h.
Referenced by btSoftRigidDynamicsWorld::btSoftRigidDynamicsWorld().
template<const int CELLSIZE> static btScalar btSparseSdf< CELLSIZE >::Lerp (btScalar a, btScalar b, btScalar t) [inline, static]
Definition at line 277 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate().
template<const int CELLSIZE> int btSparseSdf< CELLSIZE >::RemoveReferences (btCollisionShape * pcs) [inline]
Definition at line 132 of file btSparseSDF.h.
Referenced by btSoftBodyTriangleCallback::clearCache().
template<const int CELLSIZE> void btSparseSdf< CELLSIZE >::Reset () [inline]
Definition at line 86 of file btSparseSDF.h.
Referenced by btSoftRigidDynamicsWorld::btSoftRigidDynamicsWorld(), and btSparseSdf< 3 >::Initialize().
Member Data Documentation
template<const int CELLSIZE> btAlignedObjectArray<Cell*> btSparseSdf< CELLSIZE >::cells
Definition at line 68 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate(), btSparseSdf< 3 >::GarbageCollect(), btSparseSdf< 3 >::Initialize(), btSparseSdf< 3 >::RemoveReferences(), and btSparseSdf< 3 >::Reset().
template<const int CELLSIZE> int btSparseSdf< CELLSIZE >::ncells
Definition at line 71 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate(), btSparseSdf< 3 >::GarbageCollect(), and btSparseSdf< 3 >::Reset().
template<const int CELLSIZE> int btSparseSdf< CELLSIZE >::nprobes
Definition at line 72 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate(), btSparseSdf< 3 >::GarbageCollect(), and btSparseSdf< 3 >::Reset().
template<const int CELLSIZE> int btSparseSdf< CELLSIZE >::nqueries
Definition at line 73 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate(), btSparseSdf< 3 >::GarbageCollect(), and btSparseSdf< 3 >::Reset().
template<const int CELLSIZE> int btSparseSdf< CELLSIZE >::puid
Definition at line 70 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::Evaluate(), btSparseSdf< 3 >::GarbageCollect(), and btSparseSdf< 3 >::Reset().
template<const int CELLSIZE> btScalar btSparseSdf< CELLSIZE >::voxelsz
Definition at line 69 of file btSparseSDF.h.
Referenced by btSparseSdf< 3 >::BuildCell(), btSparseSdf< 3 >::Evaluate(), and btSparseSdf< 3 >::Reset().
The documentation for this struct was generated from the following file:
btSparseSDF.h