Blender: svm_voronoi.h File Reference
svm_voronoi.h File Reference
Functions
CCL_NAMESPACE_BEGIN
__device_noinline float4 svm_voronoi (NodeVoronoiColoring coloring, float scale, float3 p)
__device void svm_node_tex_voronoi (KernelGlobals *kg, ShaderData *sd, float *stack, uint4 node, int *offset)
Function Documentation
__device void svm_node_tex_voronoi (KernelGlobals * kg, ShaderData * sd, float * stack, uint4 node, int * offset)
Definition at line 47 of file svm_voronoi.h.
References co, decode_node_uchar4(), make_float3(), stack_load_float3(), stack_load_float_default(), stack_store_float(), stack_store_float3(), stack_valid(), svm_voronoi(), float4::w, uint4::w, float4::x, float4::y, uint4::y, float4::z, and uint4::z.
Referenced by svm_eval_nodes().
CCL_NAMESPACE_BEGIN __device_noinline float4 svm_voronoi (NodeVoronoiColoring coloring, float scale, float3 p)
Definition at line 23 of file svm_voronoi.h.
References average(), cellnoise_color(), fabsf, make_float3(), make_float4(), NODE_VORONOI_DISTANCE_SQUARED, NODE_VORONOI_INTENSITY, voronoi(), float3::x, float3::y, and float3::z.
Referenced by svm_node_tex_voronoi().