Blender: SG_DListHead< T > Class Template Reference
SG_DListHead< T > Class Template Reference
#include <SG_DList.h>
Public Types
typedef SG_DListHead< T > _myT
Public Member Functions
SG_DListHead ()
SG_DListHead (const _myT &other)
virtual ~SG_DListHead ()
T * Remove ()
Detailed Description
template<typename T>
class SG_DListHead< T >
SG_DListHead : Template class that implements copy constructor to duplicate list automatically The elements of the list must have themselves a copy constructor.
Definition at line 230 of file SG_DList.h.
Member Typedef Documentation
template<typename T> typedef SG_DListHead<T> SG_DListHead< T >::_myT
Definition at line 233 of file SG_DList.h.
Constructor & Destructor Documentation
template<typename T> SG_DListHead< T >::SG_DListHead () [inline]
Definition at line 234 of file SG_DList.h.
template<typename T> SG_DListHead< T >::SG_DListHead (const _myT & other) [inline]
Definition at line 235 of file SG_DList.h.
template<typename T> virtual SG_DListHead< T >::~SG_DListHead () [inline, virtual]
Definition at line 245 of file SG_DList.h.
Member Function Documentation
template<typename T> T* SG_DListHead< T >::Remove () [inline]
Reimplemented from SG_DList.
Definition at line 246 of file SG_DList.h.
Referenced by BL_ArmatureObject::LoadConstraints(), SG_DListHead< BL_ArmatureConstraint >::Remove(), and BL_ArmatureObject::~BL_ArmatureObject().
The documentation for this class was generated from the following file:
SG_DList.h