Blender: btConvexConcaveCollisionAlgorithm Class Reference
btConvexConcaveCollisionAlgorithm Class Reference
btConvexConcaveCollisionAlgorithm supports collision between convex shapes and (concave) trianges meshes.
#include <btConvexConcaveCollisionAlgorithm.h>
Classes
struct CreateFunc
struct SwappedCreateFunc
Public Member Functions
btConvexConcaveCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *body0, btCollisionObject *body1, bool isSwapped)
virtual ~btConvexConcaveCollisionAlgorithm ()
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
void clearCache ()
Detailed Description
btConvexConcaveCollisionAlgorithm supports collision between convex shapes and (concave) trianges meshes.
Definition at line 73 of file btConvexConcaveCollisionAlgorithm.h.
Constructor & Destructor Documentation
btConvexConcaveCollisionAlgorithm::btConvexConcaveCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * body0, btCollisionObject * body1, bool isSwapped)
Definition at line 29 of file btConvexConcaveCollisionAlgorithm.cpp.
Referenced by btConvexConcaveCollisionAlgorithm::SwappedCreateFunc::CreateCollisionAlgorithm(), and btConvexConcaveCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btConvexConcaveCollisionAlgorithm::~btConvexConcaveCollisionAlgorithm () [virtual]
Definition at line 36 of file btConvexConcaveCollisionAlgorithm.cpp.
Member Function Documentation
btScalar btConvexConcaveCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 208 of file btConvexConcaveCollisionAlgorithm.cpp.
References btSubsimplexConvexCast::calcTimeOfImpact(), btTransform::getOrigin(), btTransform::inverse(), btConvexCast::CastResult::m_fraction, btConcaveShape::processAllTriangles(), and btTransform::setIdentity().
void btConvexConcaveCollisionAlgorithm::clearCache ()
Definition at line 165 of file btConvexConcaveCollisionAlgorithm.cpp.
References btConvexTriangleCallback::clearCache().
void btConvexConcaveCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [virtual]
Implements btCollisionAlgorithm.
Definition at line 40 of file btConvexConcaveCollisionAlgorithm.cpp.
References btConvexTriangleCallback::m_manifoldPtr, and btAlignedObjectArray< T >::push_back().
void btConvexConcaveCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Implements btCollisionAlgorithm.
Definition at line 171 of file btConvexConcaveCollisionAlgorithm.cpp.
References btConvexTriangleCallback::getAabbMax(), btConvexTriangleCallback::getAabbMin(), btConcaveShape::getMargin(), btConvexTriangleCallback::m_manifoldPtr, btConcaveShape::processAllTriangles(), btManifoldResult::refreshContactPoints(), btManifoldResult::setPersistentManifold(), and btConvexTriangleCallback::setTimeStepAndCounters().
The documentation for this class was generated from the following files:
btConvexConcaveCollisionAlgorithm.h
btConvexConcaveCollisionAlgorithm.cpp