Blender: SubdFace::EdgeIterator Class Reference
SubdFace::EdgeIterator Class Reference
#include <subd_face.h>
Public Member Functions
EdgeIterator (SubdEdge *e)
virtual void advance ()
virtual bool isDone ()
virtual SubdEdge * current ()
Detailed Description
Definition at line 83 of file subd_face.h.
Constructor & Destructor Documentation
SubdFace::EdgeIterator::EdgeIterator (SubdEdge * e) [inline]
Definition at line 86 of file subd_face.h.
Member Function Documentation
virtual void SubdFace::EdgeIterator::advance () [inline, virtual]
Definition at line 88 of file subd_face.h.
References SubdEdge::next, and NULL.
virtual SubdEdge* SubdFace::EdgeIterator::current () [inline, virtual]
Definition at line 95 of file subd_face.h.
virtual bool SubdFace::EdgeIterator::isDone () [inline, virtual]
Definition at line 94 of file subd_face.h.
Referenced by SubdAccBuilder::computeCornerStencil(), SubdAccBuilder::computeEdgeStencil(), SubdAccBuilder::computeInteriorStencil(), SubdFace::contains(), SubdFaceRing::initVerts(), SubdFaceRing::is_boundary(), SubdFace::is_boundary(), SubdFaceRing::is_regular(), SubdFace::num_edges(), and SubdLinearBuilder::run().
The documentation for this class was generated from the following file:
subd_face.h