Blender: CExpression Class Reference
CExpression Class Reference
#include <Expression.h>
Public Types
enum {
COPERATOR1EXPRESSIONID = 1, COPERATOR2EXPRESSIONID = 2, CCONSTEXPRESSIONID = 3, CIFEXPRESSIONID = 4,
COPERATORVAREXPRESSIONID = 5, CIDENTIFIEREXPRESSIONID = 6
}
Public Member Functions
virtual bool MergeExpression (CExpression *otherexpr)=0
CExpression ()
virtual CValue * Calculate ()=0
virtual unsigned char GetExpressionID ()=0
virtual bool NeedsRecalculated ()=0
virtual CExpression * CheckLink (std::vector< CBrokenLinkInfo * > &brokenlinks)=0
virtual void ClearModified ()=0
virtual void BroadcastOperators (VALUE_OPERATOR op)=0
virtual CExpression * AddRef ()
virtual CExpression * Release (CExpression *complicatedtrick=NULL)
Protected Member Functions
virtual ~CExpression ()=0
Protected Attributes
int m_refcount
Detailed Description
Definition at line 90 of file Expression.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
COPERATOR1EXPRESSIONID
COPERATOR2EXPRESSIONID
CCONSTEXPRESSIONID
CIFEXPRESSIONID
COPERATORVAREXPRESSIONID
CIDENTIFIEREXPRESSIONID
Definition at line 93 of file Expression.h.
Constructor & Destructor Documentation
CExpression::~CExpression () [protected, pure virtual]
Definition at line 35 of file Expression.cpp.
References assert, and m_refcount.
CExpression::CExpression ()
Definition at line 27 of file Expression.cpp.
References m_refcount.
Member Function Documentation
virtual CExpression* CExpression::AddRef () [inline, virtual]
Definition at line 119 of file Expression.h.
References assertd, and m_refcount.
Referenced by CBrokenLinkInfo::BreakLink(), COperator1Expr::CheckLink(), CConstExpr::CheckLink(), COperator2Expr::MergeExpression(), and SCA_PropertyActuator::Update().
virtual void CExpression::BroadcastOperators (VALUE_OPERATOR op) [pure virtual]
Implemented in CConstExpr, CIdentifierExpr, CIfExpr, COperator1Expr, and COperator2Expr.
Referenced by COperator1Expr::BroadcastOperators(), and COperator2Expr::BroadcastOperators().
virtual CValue* CExpression::Calculate () [pure virtual]
Implemented in CConstExpr, CIdentifierExpr, CIfExpr, COperator1Expr, and COperator2Expr.
Referenced by CIfExpr::Calculate(), COperator1Expr::Calculate(), COperator2Expr::Calculate(), SCA_PropertySensor::CheckPropertyCondition(), EXP_ParseInput(), CParser::GetFloat(), CParser::GetValue(), SCA_ExpressionController::Trigger(), and SCA_PropertyActuator::Update().
virtual CExpression* CExpression::CheckLink (std::vector< CBrokenLinkInfo * > & brokenlinks) [pure virtual]
Implemented in CConstExpr, CIdentifierExpr, CIfExpr, COperator1Expr, and COperator2Expr.
Referenced by COperator1Expr::CheckLink().
virtual void CExpression::ClearModified () [pure virtual]
Implemented in CConstExpr, CIdentifierExpr, CIfExpr, COperator1Expr, and COperator2Expr.
Referenced by COperator1Expr::ClearModified(), and COperator2Expr::ClearModified().
virtual unsigned char CExpression::GetExpressionID () [pure virtual]
Implemented in CConstExpr, CIdentifierExpr, CIfExpr, COperator1Expr, and COperator2Expr.
Referenced by COperator2Expr::MergeExpression().
virtual bool CExpression::MergeExpression (CExpression * otherexpr) [pure virtual]
Implemented in CConstExpr, CIdentifierExpr, CIfExpr, COperator1Expr, and COperator2Expr.
Referenced by COperator1Expr::MergeExpression().
virtual bool CExpression::NeedsRecalculated () [pure virtual]
Implemented in CConstExpr, CIdentifierExpr, CIfExpr, COperator1Expr, and COperator2Expr.
Referenced by COperator2Expr::Calculate(), COperator2Expr::NeedsRecalculated(), CIfExpr::NeedsRecalculated(), and COperator1Expr::NeedsRecalculated().
virtual CExpression* CExpression::Release (CExpression * complicatedtrick = NULL) [inline, virtual]
Definition at line 128 of file Expression.h.
References m_refcount.
Referenced by COperator1Expr::CheckLink(), COperator2Expr::CheckLink(), CConstExpr::CheckLink(), SCA_ExpressionController::Delete(), SCA_PropertySensor::Delete(), EXP_ParseInput(), CParser::GetFloat(), CParser::GetValue(), COperator2Expr::MergeExpression(), SCA_PropertyActuator::Update(), CBrokenLinkInfo::~CBrokenLinkInfo(), CIfExpr::~CIfExpr(), COperator1Expr::~COperator1Expr(), COperator2Expr::~COperator2Expr(), SCA_ExpressionController::~SCA_ExpressionController(), and SCA_PropertySensor::~SCA_PropertySensor().
Member Data Documentation
int CExpression::m_refcount [protected]
Definition at line 138 of file Expression.h.
Referenced by AddRef(), CExpression(), Release(), and ~CExpression().
The documentation for this class was generated from the following files:
Expression.h
Expression.cpp