Blender: readimage.c File Reference
readimage.c File Reference
IMage Buffer
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "imbuf.h"
#include "IMB_imbuf_types.h"
#include "IMB_imbuf.h"
#include "IMB_filetype.h"
Functions
ImBuf * IMB_ibImageFromMemory (unsigned char *mem, size_t size, int flags, const char *descr)
ImBuf * IMB_loadifffile (int file, int flags, const char *descr)
static void imb_cache_filename (char *filename, const char *name, int flags)
ImBuf * IMB_loadiffname (const char *filepath, int flags)
ImBuf * IMB_testiffname (const char *filepath, int flags)
static void imb_loadtilefile (ImBuf *ibuf, int file, int tx, int ty, unsigned int *rect)
void imb_loadtile (ImBuf *ibuf, int tx, int ty, unsigned int *rect)
Detailed Description
Definition in file readimage.c.
Function Documentation
static void imb_cache_filename (char * filename, const char * name, int flags) [static]
Definition at line 106 of file readimage.c.
References BLI_file_older(), BLI_replace_extension(), BLI_strncpy(), IB_FILENAME_SIZE, and IB_tilecache.
Referenced by IMB_loadiffname(), and IMB_testiffname().
ImBuf* IMB_ibImageFromMemory (unsigned char * mem, size_t size, int flags, const char * descr) [read]
Attention:
Defined in readimage.c
Definition at line 53 of file readimage.c.
References ImBuf::flags, IB_premul, IMB_FILE_TYPES, IMB_premultiply_alpha(), ImFileType::is_a, ImFileType::load, and NULL.
Referenced by avi_fetchibuf(), filelist_init_icons(), image_load_image_file(), IMB_loadifffile(), init_internal_icons(), and wm_block_create_splash().
ImBuf* IMB_loadifffile (int file, int flags, const char * descr) [read]
Attention:
defined in readimage.c
Deprecated:
Only here for backwards compatibility of the
plugin system.
Definition at line 82 of file readimage.c.
References BLI_file_descriptor_size(), IMB_ibImageFromMemory(), MAP_SHARED, mmap(), munmap(), NULL, PROT_READ, and size().
Referenced by IMB_loadiffname(), IMB_testiffname(), and loadifffile().
ImBuf* IMB_loadiffname (const char * filepath, int flags) [read]
Attention:
Defined in readimage.c
Definition at line 121 of file readimage.c.
References BLI_open(), BLI_strncpy(), ImBuf::cachename, IB_fields, IB_FILENAME_SIZE, imb_cache_filename(), IMB_de_interlace(), IMB_loadifffile(), ImBuf::mipmap, ImBuf::miptot, ImBuf::name, NULL, and O_BINARY.
Referenced by anim_getnew(), get_brush_icon(), image_load_image_file(), image_load_sequence_file(), IMB_anim_absolute(), IMB_thumb_create(), IMB_thumb_manage(), IMB_thumb_read(), init_iconfile_list(), init_internal_icons(), loadiffname(), movieclip_load_sequence_file(), RE_layer_load_from_file(), seq_proxy_fetch(), and seq_render_strip().
void imb_loadtile (ImBuf * ibuf, int tx, int ty, unsigned int * rect)
Definition at line 194 of file readimage.c.
References BLI_open(), ImBuf::cachename, imb_loadtilefile(), and O_BINARY.
Referenced by imb_global_cache_tile_load().
static void imb_loadtilefile (ImBuf * ibuf, int file, int tx, int ty, unsigned int * rect) [static]
Definition at line 170 of file readimage.c.
References BLI_file_descriptor_size(), ImBuf::cachename, ImFileType::ftype, IMB_FILE_TYPES, ImFileType::is_a, ImFileType::load_tile, MAP_SHARED, mmap(), munmap(), NULL, PROT_READ, and size().
Referenced by imb_loadtile().
ImBuf* IMB_testiffname (const char * filepath, int flags) [read]
Attention:
Defined in readimage.c
Definition at line 147 of file readimage.c.
References BLI_open(), BLI_strncpy(), ImBuf::cachename, IB_FILENAME_SIZE, IB_multilayer, IB_test, imb_cache_filename(), IMB_loadifffile(), ImBuf::name, NULL, and O_BINARY.
Referenced by testiffname().