Blender: kernel_object.h File Reference
kernel_object.h File Reference
Enumerations
enum ObjectTransform { OBJECT_TRANSFORM = 0, OBJECT_INVERSE_TRANSFORM = 4, OBJECT_NORMAL_TRANSFORM = 8, OBJECT_PROPERTIES = 12 }
Functions
__device_inline Transform object_fetch_transform (KernelGlobals *kg, int object, enum ObjectTransform type)
__device_inline void object_position_transform (KernelGlobals *kg, int object, float3 *P)
__device_inline void object_normal_transform (KernelGlobals *kg, int object, float3 *N)
__device_inline void object_dir_transform (KernelGlobals *kg, int object, float3 *D)
__device_inline float object_surface_area (KernelGlobals *kg, int object)
__device_inline float object_pass_id (KernelGlobals *kg, int object)
Enumeration Type Documentation
enum ObjectTransform
Enumerator:
OBJECT_TRANSFORM
OBJECT_INVERSE_TRANSFORM
OBJECT_NORMAL_TRANSFORM
OBJECT_PROPERTIES
Definition at line 21 of file kernel_object.h.
Function Documentation
__device_inline void object_dir_transform (KernelGlobals * kg, int object, float3 * D)
Definition at line 54 of file kernel_object.h.
References object_fetch_transform(), OBJECT_TRANSFORM, and transform_direction().
Referenced by shader_setup_from_ray(), and shader_setup_from_sample().
__device_inline Transform object_fetch_transform (KernelGlobals * kg, int object, enum ObjectTransform type)
Definition at line 28 of file kernel_object.h.
References kernel_tex_fetch, OBJECT_SIZE, Transform::w, Transform::x, Transform::y, and Transform::z.
Referenced by bvh_instance_pop(), bvh_instance_push(), bvh_triangle_refine(), OSLRenderServices::get_inverse_matrix(), OSLRenderServices::get_matrix(), mbvh_instance_pop(), mbvh_instance_push(), object_dir_transform(), object_normal_transform(), object_position_transform(), qbvh_instance_pop(), qbvh_instance_push(), svm_node_tex_coord(), svm_node_tex_coord_bump_dx(), and svm_node_tex_coord_bump_dy().
__device_inline void object_normal_transform (KernelGlobals * kg, int object, float3 * N)
Definition at line 48 of file kernel_object.h.
References normalize(), object_fetch_transform(), OBJECT_NORMAL_TRANSFORM, and transform_direction().
Referenced by shader_setup_from_ray(), shader_setup_from_sample(), and triangle_light_sample().
__device_inline float object_pass_id (KernelGlobals * kg, int object)
Definition at line 67 of file kernel_object.h.
References kernel_tex_fetch, OBJECT_PROPERTIES, OBJECT_SIZE, and float4::y.
Referenced by kernel_write_data_passes().
__device_inline void object_position_transform (KernelGlobals * kg, int object, float3 * P)
Definition at line 42 of file kernel_object.h.
References object_fetch_transform(), OBJECT_TRANSFORM, and transform_point().
Referenced by triangle_light_sample().
__device_inline float object_surface_area (KernelGlobals * kg, int object)
Definition at line 60 of file kernel_object.h.
References kernel_tex_fetch, OBJECT_PROPERTIES, OBJECT_SIZE, and float4::x.
Referenced by shaderdata_to_shaderglobals(), svm_node_emission_set_weight_total(), and svm_node_emission_weight().