Blender: Bullet-C-API.cpp File Reference
Bullet-C-API.cpp File Reference
#include "Bullet-C-Api.h"
#include "btBulletDynamicsCommon.h"
#include "LinearMath/btAlignedAllocator.h"
#include "LinearMath/btVector3.h"
#include "LinearMath/btScalar.h"
#include "LinearMath/btMatrix3x3.h"
#include "LinearMath/btTransform.h"
#include "BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h"
#include "BulletCollision/CollisionShapes/btTriangleShape.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h"
#include "BulletCollision/NarrowPhaseCollision/btPointCollector.h"
#include "BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpa2.h"
#include "BulletCollision/CollisionShapes/btMinkowskiSumShape.h"
#include "BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h"
#include "BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h"
#include "BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h"
Classes
struct btPhysicsSdk
Functions
plPhysicsSdkHandle plNewBulletSdk ()
void plDeletePhysicsSdk (plPhysicsSdkHandle physicsSdk)
plDynamicsWorldHandle plCreateDynamicsWorld (plPhysicsSdkHandle physicsSdkHandle)
void plDeleteDynamicsWorld (plDynamicsWorldHandle world)
void plStepSimulation (plDynamicsWorldHandle world, plReal timeStep)
void plAddRigidBody (plDynamicsWorldHandle world, plRigidBodyHandle object)
void plRemoveRigidBody (plDynamicsWorldHandle world, plRigidBodyHandle object)
plRigidBodyHandle plCreateRigidBody (void *user_data, float mass, plCollisionShapeHandle cshape)
void plDeleteRigidBody (plRigidBodyHandle cbody)
plCollisionShapeHandle plNewSphereShape (plReal radius)
plCollisionShapeHandle plNewBoxShape (plReal x, plReal y, plReal z)
plCollisionShapeHandle plNewCapsuleShape (plReal radius, plReal height)
plCollisionShapeHandle plNewConeShape (plReal radius, plReal height)
plCollisionShapeHandle plNewCylinderShape (plReal radius, plReal height)
plCollisionShapeHandle plNewConvexHullShape ()
plMeshInterfaceHandle plNewMeshInterface ()
plCollisionShapeHandle plNewCompoundShape ()
void plAddChildShape (plCollisionShapeHandle compoundShapeHandle, plCollisionShapeHandle childShapeHandle, plVector3 childPos, plQuaternion childOrn)
void plSetEuler (plReal yaw, plReal pitch, plReal roll, plQuaternion orient)
void plAddVertex (plCollisionShapeHandle cshape, plReal x, plReal y, plReal z)
void plDeleteShape (plCollisionShapeHandle cshape)
void plSetScaling (plCollisionShapeHandle cshape, plVector3 cscaling)
void plSetPosition (plRigidBodyHandle object, const plVector3 position)
void plSetOrientation (plRigidBodyHandle object, const plQuaternion orientation)
void plSetOpenGLMatrix (plRigidBodyHandle object, plReal *matrix)
void plGetOpenGLMatrix (plRigidBodyHandle object, plReal *matrix)
void plGetPosition (plRigidBodyHandle object, plVector3 position)
void plGetOrientation (plRigidBodyHandle object, plQuaternion orientation)
double plNearestPoints (float p1[3], float p2[3], float p3[3], float q1[3], float q2[3], float q3[3], float *pa, float *pb, float normal[3])
Function Documentation
void plAddChildShape (plCollisionShapeHandle compoundShapeHandle, plCollisionShapeHandle childShapeHandle, plVector3 childPos, plQuaternion childOrn)
Definition at line 223 of file Bullet-C-API.cpp.
References btAssert, COMPOUND_SHAPE_PROXYTYPE, btCollisionShape::getShapeType(), btTransform::setIdentity(), btTransform::setOrigin(), and btTransform::setRotation().
void plAddRigidBody (plDynamicsWorldHandle world, plRigidBodyHandle object)
Definition at line 117 of file Bullet-C-API.cpp.
References btDynamicsWorld::addRigidBody(), and btAssert.
void plAddVertex (plCollisionShapeHandle cshape, plReal x, plReal y, plReal z)
Definition at line 252 of file Bullet-C-API.cpp.
References btAssert, CONVEX_HULL_SHAPE_PROXYTYPE, and btCollisionShape::getShapeType().
plDynamicsWorldHandle plCreateDynamicsWorld (plPhysicsSdkHandle physicsSdkHandle)
Definition at line 88 of file Bullet-C-API.cpp.
References btAlignedAlloc, btPhysicsSdk::m_worldAabbMax, and btPhysicsSdk::m_worldAabbMin.
plRigidBodyHandle plCreateRigidBody (void * user_data, float mass, plCollisionShapeHandle cshape)
Definition at line 139 of file Bullet-C-API.cpp.
References btAlignedAlloc, btAssert, btCollisionShape::calculateLocalInertia(), and btTransform::setIdentity().
void plDeleteDynamicsWorld (plDynamicsWorldHandle world)
Definition at line 103 of file Bullet-C-API.cpp.
References btAlignedFree.
void plDeletePhysicsSdk (plPhysicsSdkHandle physicsSdk)
Definition at line 80 of file Bullet-C-API.cpp.
References btAlignedFree.
void plDeleteRigidBody (plRigidBodyHandle cbody)
Definition at line 158 of file Bullet-C-API.cpp.
References btAlignedFree, and btAssert.
void plDeleteShape (plCollisionShapeHandle cshape)
Definition at line 262 of file Bullet-C-API.cpp.
References btAlignedFree, and btAssert.
void plGetOpenGLMatrix (plRigidBodyHandle object, plReal * matrix)
Definition at line 306 of file Bullet-C-API.cpp.
References btAssert.
void plGetOrientation (plRigidBodyHandle object, plQuaternion orientation)
Definition at line 324 of file Bullet-C-API.cpp.
References btAssert, and btQuaternion::getW().
void plGetPosition (plRigidBodyHandle object, plVector3 position)
Definition at line 314 of file Bullet-C-API.cpp.
References btAssert.
double plNearestPoints (float p1[3], float p2[3], float p3[3], float q1[3], float q2[3], float q3[3], float * pa, float * pb, float normal[3])
Definition at line 341 of file Bullet-C-API.cpp.
References btSimplexSolverInterface, btGjkPairDetector::getClosestPoints(), btGjkPairDetector::m_catchDegeneracies, btPointCollector::m_distance, btPointCollector::m_hasResult, btPointCollector::m_normalOnBInWorld, btPointCollector::m_pointInWorld, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformA, btDiscreteCollisionDetectorInterface::ClosestPointInput::m_transformB, NULL, and btTransform::setIdentity().
Referenced by cloth_collision().
plCollisionShapeHandle plNewBoxShape (plReal x, plReal y, plReal z)
Definition at line 175 of file Bullet-C-API.cpp.
References btAlignedAlloc.
plPhysicsSdkHandle plNewBulletSdk (void)
Create and Delete a Physics SDK
Definition at line 74 of file Bullet-C-API.cpp.
References btAlignedAlloc.
plCollisionShapeHandle plNewCapsuleShape (plReal radius, plReal height)
Definition at line 181 of file Bullet-C-API.cpp.
References btAlignedAlloc.
plCollisionShapeHandle plNewCompoundShape (void)
Definition at line 217 of file Bullet-C-API.cpp.
References btAlignedAlloc.
plCollisionShapeHandle plNewConeShape (plReal radius, plReal height)
Definition at line 191 of file Bullet-C-API.cpp.
References btAlignedAlloc.
plCollisionShapeHandle plNewConvexHullShape (void)
Definition at line 204 of file Bullet-C-API.cpp.
References btAlignedAlloc.
plCollisionShapeHandle plNewCylinderShape (plReal radius, plReal height)
Definition at line 197 of file Bullet-C-API.cpp.
References btAlignedAlloc.
plMeshInterfaceHandle plNewMeshInterface (void)
Definition at line 212 of file Bullet-C-API.cpp.
plCollisionShapeHandle plNewSphereShape (plReal radius)
Definition at line 168 of file Bullet-C-API.cpp.
References btAlignedAlloc.
void plRemoveRigidBody (plDynamicsWorldHandle world, plRigidBodyHandle object)
Definition at line 127 of file Bullet-C-API.cpp.
References btAssert, and btDynamicsWorld::removeRigidBody().
void plSetEuler (plReal yaw, plReal pitch, plReal roll, plQuaternion orient)
Definition at line 236 of file Bullet-C-API.cpp.
References btQuaternion::getW(), and btQuaternion::setEuler().
void plSetOpenGLMatrix (plRigidBodyHandle object, plReal * matrix)
Definition at line 298 of file Bullet-C-API.cpp.
References btAssert, and btTransform::setFromOpenGLMatrix().
void plSetOrientation (plRigidBodyHandle object, const plQuaternion orientation)
Definition at line 288 of file Bullet-C-API.cpp.
References btAssert, and btTransform::setRotation().
void plSetPosition (plRigidBodyHandle object, const plVector3 position)
Definition at line 278 of file Bullet-C-API.cpp.
References btAssert, and btTransform::setOrigin().
void plSetScaling (plCollisionShapeHandle cshape, plVector3 cscaling)
Definition at line 268 of file Bullet-C-API.cpp.
References btAssert, and btCollisionShape::setLocalScaling().
void plStepSimulation (plDynamicsWorldHandle world, plReal timeStep)
Definition at line 110 of file Bullet-C-API.cpp.
References btAssert, and btDynamicsWorld::stepSimulation().