Blender: ssp_blas2.c File Reference
ssp_blas2.c File Reference
opennl
#include "ssp_defs.h"
Functions
void susolve (int, int, float *, float *)
void slsolve (int, int, float *, float *)
void smatvec (int, int, int, float *, float *, float *)
int strsv_ (char *, char *, char *, int *, float *, int *, float *, int *)
int sp_strsv (char *uplo, char *trans, char *diag, SuperMatrix *L, SuperMatrix *U, float *x, SuperLUStat_t *stat, int *info)
int sp_sgemv (char *trans, float alpha, SuperMatrix *A, float *x, int incx, float beta, float *y, int incy)
Detailed Description
Definition in file ssp_blas2.c.
Function Documentation
void slsolve (int , int , float * , float *)
Definition at line 33 of file smyblas2.c.
void smatvec (int , int , int , float * , float * , float *)
Definition at line 160 of file smyblas2.c.
int sp_sgemv (char * trans, float alpha, SuperMatrix * A, float * x, int incx, float beta, float * y, int incy)
Definition at line 309 of file ssp_blas2.c.
References ABORT, NCformat::colptr, i, lsame_(), SuperMatrix::ncol, SuperMatrix::nrow, NCformat::nzval, NCformat::rowind, SuperMatrix::Store, and xerbla_().
Referenced by sp_sgemm().
int sp_strsv (char * uplo, char * trans, char * diag, SuperMatrix * L, SuperMatrix * U, float * x, SuperLUStat_t * stat, int * info)
Definition at line 28 of file ssp_blas2.c.
References ABORT, floatCalloc(), i, L_FST_SUPC, L_NZ_START, L_SUB, L_SUB_START, lsame_(), SuperMatrix::ncol, SuperMatrix::nrow, SCformat::nsuper, NCformat::nzval, SCformat::nzval, SuperLUStat_t::ops, slsolve(), smatvec(), SOLVE, SuperMatrix::Store, strlen(), strsv_(), SUPERLU_FREE, susolve(), U_NZ_START, U_SUB, and xerbla_().
Referenced by sgstrs().
int strsv_ (char * uplo, char * trans, char * diag, int * n, float * a, int * lda, float * x, int * incx)
Definition at line 7 of file strsv.c.
References A, i, lsame_(), X, and xerbla_().
Referenced by scolumn_bmod(), sp_strsv(), spanel_bmod(), and ssnode_bmod().
void susolve (int , int , float * , float *)
Definition at line 131 of file smyblas2.c.