Blender: KX_SCA_ReplaceMeshActuator Class Reference
KX_SCA_ReplaceMeshActuator Class Reference
#include <KX_SCA_ReplaceMeshActuator.h>
Public Member Functions
KX_SCA_ReplaceMeshActuator (SCA_IObject *gameobj, RAS_MeshObject *mesh, SCA_IScene *scene, bool use_gfx, bool use_phys)
~KX_SCA_ReplaceMeshActuator ()
CValue * GetReplica ()
virtual bool Update ()
void InstantReplaceMesh ()
Detailed Description
Definition at line 45 of file KX_SCA_ReplaceMeshActuator.h.
Constructor & Destructor Documentation
KX_SCA_ReplaceMeshActuator::KX_SCA_ReplaceMeshActuator (SCA_IObject * gameobj, RAS_MeshObject * mesh, SCA_IScene * scene, bool use_gfx, bool use_phys)
Definition at line 123 of file KX_SCA_ReplaceMeshActuator.cpp.
Referenced by GetReplica().
KX_SCA_ReplaceMeshActuator::~KX_SCA_ReplaceMeshActuator ()
Definition at line 139 of file KX_SCA_ReplaceMeshActuator.cpp.
Member Function Documentation
CValue * KX_SCA_ReplaceMeshActuator::GetReplica (void) [virtual]
Implements CValue.
Definition at line 163 of file KX_SCA_ReplaceMeshActuator.cpp.
References KX_SCA_ReplaceMeshActuator(), NULL, and SCA_IActuator::ProcessReplica().
void KX_SCA_ReplaceMeshActuator::InstantReplaceMesh ()
Definition at line 176 of file KX_SCA_ReplaceMeshActuator.cpp.
References SCA_ILogicBrick::GetParent(), and SCA_IScene::ReplaceMesh().
bool KX_SCA_ReplaceMeshActuator::Update (void) [virtual]
Reimplemented from SCA_IActuator.
Definition at line 146 of file KX_SCA_ReplaceMeshActuator.cpp.
References SCA_ILogicBrick::GetParent(), SCA_IActuator::IsNegativeEvent(), SCA_IActuator::RemoveAllEvents(), and SCA_IScene::ReplaceMesh().
The documentation for this class was generated from the following files:
KX_SCA_ReplaceMeshActuator.h
KX_SCA_ReplaceMeshActuator.cpp