Blender: console_intern.h File Reference
console_intern.h File Reference
console space
Enumerations
enum {
LINE_BEGIN, LINE_END, PREV_CHAR, NEXT_CHAR,
PREV_WORD, NEXT_WORD
}
enum {
DEL_ALL, DEL_NEXT_CHAR, DEL_PREV_CHAR, DEL_NEXT_WORD,
DEL_PREV_WORD, DEL_SELECTION, DEL_NEXT_SEL, DEL_PREV_SEL
}
Functions
void console_textview_main (struct SpaceConsole *sc, struct ARegion *ar)
int console_textview_height (struct SpaceConsole *sc, struct ARegion *ar)
int console_char_pick (struct SpaceConsole *sc, struct ARegion *ar, int mval[2])
void console_scrollback_prompt_begin (struct SpaceConsole *sc, ConsoleLine *cl_dummy)
void console_scrollback_prompt_end (struct SpaceConsole *sc, ConsoleLine *cl_dummy)
void console_history_free (SpaceConsole *sc, ConsoleLine *cl)
void console_scrollback_free (SpaceConsole *sc, ConsoleLine *cl)
ConsoleLine * console_history_add_str (struct SpaceConsole *sc, char *str, int own)
ConsoleLine * console_scrollback_add_str (struct SpaceConsole *sc, char *str, int own)
ConsoleLine * console_history_verify (const struct bContext *C)
void CONSOLE_OT_move (struct wmOperatorType *ot)
void CONSOLE_OT_delete (struct wmOperatorType *ot)
void CONSOLE_OT_insert (struct wmOperatorType *ot)
void CONSOLE_OT_history_append (struct wmOperatorType *ot)
void CONSOLE_OT_scrollback_append (struct wmOperatorType *ot)
void CONSOLE_OT_clear (struct wmOperatorType *ot)
void CONSOLE_OT_history_cycle (struct wmOperatorType *ot)
void CONSOLE_OT_copy (struct wmOperatorType *ot)
void CONSOLE_OT_paste (struct wmOperatorType *ot)
void CONSOLE_OT_select_set (struct wmOperatorType *ot)
Detailed Description
Definition in file console_intern.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
LINE_BEGIN
LINE_END
PREV_CHAR
NEXT_CHAR
PREV_WORD
NEXT_WORD
Definition at line 66 of file console_intern.h.
anonymous enum
Enumerator:
DEL_ALL
DEL_NEXT_CHAR
DEL_PREV_CHAR
DEL_NEXT_WORD
DEL_PREV_WORD
DEL_SELECTION
DEL_NEXT_SEL
DEL_PREV_SEL
Definition at line 67 of file console_intern.h.
Function Documentation
int console_char_pick (struct SpaceConsole * sc, struct ARegion * ar, int mval[2])
Definition at line 241 of file console_draw.c.
References CLAMPIS, CONSOLE_DRAW_MARGIN, CONSOLE_DRAW_SCROLL, console_textview_main__internal(), NULL, ARegion::winx, and ARegion::winy.
Referenced by console_cursor_set_to_pos().
ConsoleLine* console_history_add_str (struct SpaceConsole * sc, char * str, int own)
Definition at line 203 of file console_ops.c.
References console_lb_add_str__internal(), and SpaceConsole::history.
Referenced by console_history_append_exec(), and report_replay_exec().
void console_history_free (SpaceConsole * sc, ConsoleLine * cl)
Definition at line 78 of file console_ops.c.
References BLI_remlink(), SpaceConsole::history, ConsoleLine::line, and MEM_freeN().
Referenced by console_clear_exec(), console_free(), console_history_append_exec(), and console_history_cycle_exec().
ConsoleLine* console_history_verify (const struct bContext * C)
Referenced by console_clear_exec(), console_delete_exec(), console_history_append_exec(), console_history_cycle_exec(), console_insert_exec(), console_main_area_draw(), console_move_exec(), console_paste_exec(), and console_scrollback_append_exec().
void CONSOLE_OT_clear (struct wmOperatorType * ot)
Definition at line 550 of file console_ops.c.
References console_clear_exec(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by console_operatortypes().
void CONSOLE_OT_copy (struct wmOperatorType * ot)
Definition at line 810 of file console_ops.c.
References console_copy_exec(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by console_operatortypes().
void CONSOLE_OT_delete (struct wmOperatorType * ot)
Definition at line 507 of file console_ops.c.
References console_delete_exec(), DEL_NEXT_CHAR, wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by console_operatortypes().
void CONSOLE_OT_history_append (struct wmOperatorType * ot)
Definition at line 673 of file console_ops.c.
References console_history_append_exec(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), RNA_def_int(), RNA_def_string(), and wmOperatorType::srna.
Referenced by console_operatortypes().
void CONSOLE_OT_history_cycle (struct wmOperatorType * ot)
Definition at line 618 of file console_ops.c.
References console_history_cycle_exec(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by console_operatortypes().
void CONSOLE_OT_insert (struct wmOperatorType * ot)
Definition at line 414 of file console_ops.c.
References console_insert_exec(), console_insert_invoke(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_property_flag(), RNA_def_string(), and wmOperatorType::srna.
Referenced by console_operatortypes().
void CONSOLE_OT_move (struct wmOperatorType * ot)
Definition at line 343 of file console_ops.c.
References console_move_exec(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, LINE_BEGIN, wmOperatorType::name, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by console_operatortypes().
void CONSOLE_OT_paste (struct wmOperatorType * ot)
Definition at line 863 of file console_ops.c.
References console_paste_exec(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and wmOperatorType::poll.
Referenced by console_operatortypes().
void CONSOLE_OT_scrollback_append (struct wmOperatorType * ot)
Definition at line 719 of file console_ops.c.
References CONSOLE_LINE_ERROR, CONSOLE_LINE_INFO, CONSOLE_LINE_INPUT, CONSOLE_LINE_OUTPUT, console_scrollback_append_exec(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, NULL, wmOperatorType::poll, RNA_def_enum(), RNA_def_string(), and wmOperatorType::srna.
Referenced by console_operatortypes().
void CONSOLE_OT_select_set (struct wmOperatorType * ot)
Definition at line 988 of file console_ops.c.
References wmOperatorType::cancel, console_modal_select(), console_modal_select_cancel(), console_modal_select_invoke(), wmOperatorType::description, ED_operator_console_active(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, and wmOperatorType::poll.
Referenced by console_operatortypes().
ConsoleLine* console_scrollback_add_str (struct SpaceConsole * sc, char * str, int own)
Definition at line 207 of file console_ops.c.
References console_lb_add_str__internal(), console_select_offset(), ConsoleLine::len, and SpaceConsole::scrollback.
Referenced by console_scrollback_append_exec().
void console_scrollback_free (SpaceConsole * sc, ConsoleLine * cl)
Definition at line 84 of file console_ops.c.
References BLI_remlink(), ConsoleLine::line, MEM_freeN(), and SpaceConsole::scrollback.
Referenced by console_clear_exec(), console_free(), and console_scrollback_limit().
void console_scrollback_prompt_begin (struct SpaceConsole * sc, ConsoleLine * cl_dummy)
Definition at line 93 of file console_draw.c.
References BLI_addtail(), CONSOLE_LINE_INPUT, SpaceConsole::history, ListBase::last, ConsoleLine::len, ConsoleLine::len_alloc, ConsoleLine::line, MEM_mallocN(), SpaceConsole::prompt, SpaceConsole::scrollback, strlen(), and ConsoleLine::type.
Referenced by console_copy_exec(), and console_textview_main__internal().
void console_scrollback_prompt_end (struct SpaceConsole * sc, ConsoleLine * cl_dummy)
Definition at line 105 of file console_draw.c.
References BLI_remlink(), ConsoleLine::line, MEM_freeN(), and SpaceConsole::scrollback.
Referenced by console_copy_exec(), and console_textview_main__internal().
int console_textview_height (struct SpaceConsole * sc, struct ARegion * ar)
Definition at line 235 of file console_draw.c.
References console_textview_main__internal(), and NULL.
Referenced by console_textview_update_rect().
void console_textview_main (struct SpaceConsole * sc, struct ARegion * ar)
Definition at line 229 of file console_draw.c.
References console_textview_main__internal(), and NULL.
Referenced by console_main_area_draw().