Blender: subd_build.cpp File Reference
subd_build.cpp File Reference
#include "subd_build.h"
#include "subd_edge.h"
#include "subd_face.h"
#include "subd_ring.h"
#include "subd_mesh.h"
#include "subd_patch.h"
#include "subd_stencil.h"
#include "subd_vert.h"
#include "util_algorithm.h"
#include "util_debug.h"
#include "util_math.h"
#include "util_string.h"
Classes
class GregoryAccStencil
Functions
static float pseudoValence (SubdVert *vert)
Function Documentation
static float pseudoValence (SubdVert * vert) [static]
Definition at line 79 of file subd_build.cpp.
References SubdVert::is_boundary(), and SubdVert::valence().
Referenced by SubdAccBuilder::computeInteriorStencil().