Blender: plyfile.c File Reference
plyfile.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ply.h"
Defines
#define NO_OTHER_PROPS -1
#define DONT_STORE_PROP 0
#define STORE_PROP 1
#define OTHER_PROP 0
#define NAMED_PROP 1
#define BIG_STRING 4096
Functions
int equal_strings (char *, char *)
PlyElement * find_element (PlyFile *, char *)
PlyProperty * find_property (PlyElement *, char *, int *)
void write_scalar_type (FILE *, int)
char ** get_words (FILE *, int *, char **)
char ** old_get_words (FILE *, int *)
void write_binary_item (FILE *, int, unsigned int, double, int)
void write_ascii_item (FILE *, int, unsigned int, double, int)
double old_write_ascii_item (FILE *, char *, int)
void add_element (PlyFile *, char **)
void add_property (PlyFile *, char **)
void add_comment (PlyFile *, char *)
void add_obj_info (PlyFile *, char *)
void copy_property (PlyProperty *, PlyProperty *)
void store_item (char *, int, int, unsigned int, double)
void get_stored_item (void *, int, int *, unsigned int *, double *)
double get_item_value (char *, int)
void get_ascii_item (char *, int, int *, unsigned int *, double *)
void get_binary_item (FILE *, int, int *, unsigned int *, double *)
void ascii_get_element (PlyFile *, char *)
void binary_get_element (PlyFile *, char *)
char * my_alloc (int, int, char *)
PlyFile * ply_write (FILE *fp, int nelems, char **elem_names, int file_type)
PlyFile * ply_open_for_writing (char *filename, int nelems, char **elem_names, int file_type, float *version)
void ply_describe_element (PlyFile *plyfile, char *elem_name, int nelems, int nprops, PlyProperty *prop_list)
void ply_describe_property (PlyFile *plyfile, char *elem_name, PlyProperty *prop)
void ply_describe_other_properties (PlyFile *plyfile, PlyOtherProp *other, int offset)
void ply_element_count (PlyFile *plyfile, char *elem_name, int nelems)
void ply_header_complete (PlyFile *plyfile)
void ply_put_element_setup (PlyFile *plyfile, char *elem_name)
void ply_put_element (PlyFile *plyfile, void *elem_ptr)
void ply_put_comment (PlyFile *plyfile, char *comment)
void ply_put_obj_info (PlyFile *plyfile, char *obj_info)
PlyFile * ply_read (FILE *fp, int *nelems, char ***elem_names)
PlyFile * ply_open_for_reading (char *filename, int *nelems, char ***elem_names, int *file_type, float *version)
PlyProperty ** ply_get_element_description (PlyFile *plyfile, char *elem_name, int *nelems, int *nprops)
void ply_get_element_setup (PlyFile *plyfile, char *elem_name, int nprops, PlyProperty *prop_list)
void ply_get_property (PlyFile *plyfile, char *elem_name, PlyProperty *prop)
void ply_get_element (PlyFile *plyfile, void *elem_ptr)
char ** ply_get_comments (PlyFile *plyfile, int *num_comments)
char ** ply_get_obj_info (PlyFile *plyfile, int *num_obj_info)
void setup_other_props (PlyElement *elem)
PlyOtherProp * ply_get_other_properties (PlyFile *plyfile, char *elem_name, int offset)
PlyOtherElems * ply_get_other_element (PlyFile *plyfile, char *elem_name, int elem_count)
void ply_describe_other_elements (PlyFile *plyfile, PlyOtherElems *other_elems)
void ply_put_other_elements (PlyFile *plyfile)
void ply_close (PlyFile *plyfile)
void ply_get_info (PlyFile *ply, float *version, int *file_type)
int get_prop_type (char *type_name)
Variables
char * type_names []
int ply_type_size []
Define Documentation
#define BIG_STRING 4096
#define DONT_STORE_PROP 0
Definition at line 82 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
Referenced by ply_read().
#define NAMED_PROP 1
Definition at line 86 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
Referenced by ply_describe_element(), and ply_describe_property().
#define NO_OTHER_PROPS -1
Definition at line 80 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
Referenced by ply_get_other_properties(), and ply_read().
#define OTHER_PROP 0
Definition at line 85 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
Referenced by ply_describe_other_properties(), and ply_put_element().
#define STORE_PROP 1
Definition at line 83 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
Referenced by ply_get_element_setup(), and ply_get_property().
Function Documentation
void add_comment (PlyFile * plyfile, char * line)
void add_element (PlyFile * plyfile, char ** words)
void add_obj_info (PlyFile * plyfile, char * line)
void add_property (PlyFile * plyfile, char ** words)
void ascii_get_element (PlyFile * plyfile, char * elem_ptr)
void binary_get_element (PlyFile * plyfile, char * elem_ptr)
void copy_property (PlyProperty * dest, PlyProperty * src)
int equal_strings (char * s1, char * s2)
Definition at line 1417 of file bsp/test/BSP_GhostTest/plyfile.c.
Referenced by add_property(), find_element(), find_property(), get_prop_type(), BSP_PlyLoader::NewMeshFromFile(), NewVertsFromFile(), and ply_read().
PlyElement* find_element (PlyFile * plyfile, char * element)
PlyProperty* find_property (PlyElement * elem, char * prop_name, int * index)
void get_ascii_item (char * word, int type, int * int_val, unsigned int * uint_val, double * double_val)
void get_binary_item (FILE * fp, int type, int * int_val, unsigned int * uint_val, double * double_val)
double get_item_value (char * item, int type)
int get_prop_type (char * type_name)
Definition at line 2405 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References equal_strings(), i, PLY_END_TYPE, PLY_START_TYPE, and type_names.
void get_stored_item (void * ptr, int type, int * int_val, unsigned int * uint_val, double * double_val)
char** get_words (FILE * fp, int * nwords, char ** orig_line)
char* my_alloc (int size, int lnum, char * fname)
char** old_get_words (FILE * , int *)
double old_write_ascii_item (FILE * fp, char * item, int type)
void ply_close (PlyFile * plyfile)
Definition at line 1383 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::fp.
Referenced by BSP_PlyLoader::NewMeshFromFile(), and NewVertsFromFile().
void ply_describe_element (PlyFile * plyfile, char * elem_name, int nelems, int nprops, PlyProperty * prop_list)
Definition at line 267 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References copy_property(), find_element(), i, myalloc, NAMED_PROP, PlyElement::nprops, NULL, PlyElement::num, PlyElement::props, and PlyElement::store_prop.
void ply_describe_other_elements (PlyFile * plyfile, PlyOtherElems * other_elems)
Definition at line 1304 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References OtherElem::elem_count, OtherElem::elem_name, i, NULL, PlyOtherElems::num_elems, PlyFile::other_elems, PlyOtherElems::other_list, OtherElem::other_props, ply_describe_other_properties(), and ply_element_count().
void ply_describe_other_properties (PlyFile * plyfile, PlyOtherProp * other, int offset)
Definition at line 358 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References copy_property(), find_element(), i, myalloc, PlyOtherProp::name, PlyOtherProp::nprops, PlyElement::nprops, NULL, PlyElement::other_offset, OTHER_PROP, PlyElement::other_size, PlyElement::props, PlyOtherProp::props, PlyOtherProp::size, and PlyElement::store_prop.
void ply_describe_property (PlyFile * plyfile, char * elem_name, PlyProperty * prop)
Definition at line 312 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References copy_property(), find_element(), myalloc, NAMED_PROP, PlyElement::nprops, NULL, PlyElement::props, and PlyElement::store_prop.
void ply_element_count (PlyFile * plyfile, char * elem_name, int nelems)
Definition at line 418 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References find_element(), NULL, and PlyElement::num.
Referenced by ply_describe_other_elements().
char** ply_get_comments (PlyFile * plyfile, int * num_comments)
Definition at line 1035 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::comments, and PlyFile::num_comments.
void ply_get_element (PlyFile * plyfile, void * elem_ptr)
Definition at line 1015 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References ascii_get_element(), binary_get_element(), PlyFile::file_type, and PLY_ASCII.
Referenced by BSP_PlyLoader::NewMeshFromFile(), NewVertsFromFile(), and ply_get_other_element().
PlyProperty** ply_get_element_description (PlyFile * plyfile, char * elem_name, int * nelems, int * nprops)
Definition at line 878 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References copy_property(), find_element(), i, myalloc, PlyElement::nprops, NULL, PlyElement::num, and PlyElement::props.
Referenced by BSP_PlyLoader::NewMeshFromFile(), and NewVertsFromFile().
void ply_get_element_setup (PlyFile * plyfile, char * elem_name, int nprops, PlyProperty * prop_list)
Definition at line 922 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyProperty::count_internal, PlyProperty::count_offset, find_element(), find_property(), i, PlyProperty::internal_type, NULL, PlyProperty::offset, STORE_PROP, PlyElement::store_prop, and PlyFile::which_elem.
void ply_get_info (PlyFile * ply, float * version, int * file_type)
Definition at line 1403 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::file_type, NULL, and PlyFile::version.
char** ply_get_obj_info (PlyFile * plyfile, int * num_obj_info)
Definition at line 1054 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::num_obj_info, and PlyFile::obj_info.
PlyOtherElems* ply_get_other_element (PlyFile * plyfile, char * elem_name, int elem_count)
Definition at line 1232 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References OtherElem::elem_count, OtherElem::elem_name, find_element(), i, myalloc, NULL, PlyOtherElems::num_elems, OtherElem::other_data, PlyFile::other_elems, PlyOtherElems::other_list, OtherElem::other_props, ply_get_element(), and ply_get_other_properties().
PlyOtherProp* ply_get_other_properties (PlyFile * plyfile, char * elem_name, int offset)
Definition at line 1143 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References copy_property(), find_element(), i, myalloc, PlyOtherProp::name, NO_OTHER_PROPS, PlyOtherProp::nprops, PlyElement::nprops, NULL, PlyElement::other_offset, PlyElement::other_size, PlyElement::props, PlyOtherProp::props, setup_other_props(), PlyOtherProp::size, PlyElement::store_prop, and PlyFile::which_elem.
Referenced by ply_get_other_element().
void ply_get_property (PlyFile * plyfile, char * elem_name, PlyProperty * prop)
Definition at line 973 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyProperty::count_internal, PlyProperty::count_offset, find_element(), find_property(), PlyProperty::internal_type, PlyProperty::name, NULL, PlyProperty::offset, STORE_PROP, PlyElement::store_prop, and PlyFile::which_elem.
Referenced by BSP_PlyLoader::NewMeshFromFile(), and NewVertsFromFile().
void ply_header_complete (PlyFile * plyfile)
Definition at line 445 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::comments, PlyProperty::count_external, PlyFile::elems, PlyProperty::external_type, PlyFile::file_type, PlyFile::fp, i, PlyProperty::is_list, PlyProperty::name, PlyElement::name, PlyFile::nelems, PlyElement::nprops, PlyElement::num, PlyFile::num_comments, PlyFile::num_obj_info, PlyFile::obj_info, PLY_ASCII, PLY_BINARY_BE, PLY_BINARY_LE, PlyElement::props, and write_scalar_type().
PlyFile* ply_open_for_reading (char * filename, int * nelems, char *** elem_names, int * file_type, float * version)
Definition at line 824 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::file_type, myalloc, NULL, ply_read(), strlen(), and PlyFile::version.
Referenced by BSP_PlyLoader::NewMeshFromFile(), and NewVertsFromFile().
PlyFile* ply_open_for_writing (char * filename, int nelems, char ** elem_names, int file_type, float * version)
Definition at line 214 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References myalloc, NULL, ply_write(), strlen(), and PlyFile::version.
void ply_put_comment (PlyFile * plyfile, char * comment)
Definition at line 655 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::comments, myalloc, and PlyFile::num_comments.
Referenced by add_comment().
void ply_put_element (PlyFile * plyfile, void * elem_ptr)
Definition at line 542 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyProperty::count_external, PlyProperty::count_internal, PlyProperty::count_offset, PlyProperty::external_type, PlyFile::file_type, PlyFile::fp, get_stored_item(), PlyProperty::internal_type, PlyProperty::is_list, PlyElement::nprops, PlyProperty::offset, PlyElement::other_offset, OTHER_PROP, PLY_ASCII, ply_type_size, PlyElement::props, PlyElement::store_prop, PlyFile::which_elem, write_ascii_item(), and write_binary_item().
Referenced by ply_put_other_elements().
void ply_put_element_setup (PlyFile * plyfile, char * elem_name)
Definition at line 518 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References find_element(), NULL, and PlyFile::which_elem.
Referenced by ply_put_other_elements().
void ply_put_obj_info (PlyFile * plyfile, char * obj_info)
Definition at line 679 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References myalloc, PlyFile::num_obj_info, and PlyFile::obj_info.
Referenced by add_obj_info().
void ply_put_other_elements (PlyFile * plyfile)
Definition at line 1337 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References OtherElem::elem_count, OtherElem::elem_name, i, NULL, PlyOtherElems::num_elems, OtherElem::other_data, PlyFile::other_elems, PlyOtherElems::other_list, ply_put_element(), and ply_put_element_setup().
PlyFile* ply_read (FILE * fp, int * nelems, char *** elem_names)
Definition at line 717 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References add_comment(), add_element(), add_obj_info(), add_property(), PlyFile::comments, DONT_STORE_PROP, PlyFile::elems, equal_strings(), PlyFile::file_type, PlyFile::fp, get_words(), i, myalloc, PlyElement::name, PlyFile::nelems, NO_OTHER_PROPS, PlyElement::nprops, NULL, PlyFile::num_comments, PlyFile::num_obj_info, PlyFile::obj_info, PlyFile::other_elems, PlyElement::other_offset, PLY_ASCII, PLY_BINARY_BE, PLY_BINARY_LE, PlyElement::store_prop, and PlyFile::version.
Referenced by ply_open_for_reading().
PlyFile* ply_write (FILE * fp, int nelems, char ** elem_names, int file_type)
Definition at line 158 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyFile::elems, PlyFile::file_type, PlyFile::fp, i, myalloc, PlyElement::name, PlyFile::nelems, PlyElement::nprops, NULL, PlyElement::num, PlyFile::num_comments, PlyFile::num_obj_info, PlyFile::other_elems, and PlyFile::version.
Referenced by ply_open_for_writing().
void setup_other_props (PlyElement * elem)
Definition at line 1072 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
References PlyProperty::count_external, PlyProperty::count_internal, PlyProperty::count_offset, PlyProperty::external_type, i, PlyProperty::internal_type, PlyProperty::is_list, PlyElement::nprops, PlyProperty::offset, PlyElement::other_size, ply_type_size, PlyElement::props, size(), and PlyElement::store_prop.
void store_item (char * item, int type, int int_val, unsigned int uint_val, double double_val)
void write_ascii_item (FILE * fp, int int_val, unsigned int uint_val, double double_val, int type)
void write_binary_item (FILE * fp, int int_val, unsigned int uint_val, double double_val, int type)
void write_scalar_type (FILE * fp, int code)
Variable Documentation
int ply_type_size[]
Initial value:
 {
  0, 1, 2, 4, 1, 2, 4, 4, 8
}
Definition at line 76 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.
char* type_names[]
Initial value:
 {
"invalid",
"char", "short", "int",
"uchar", "ushort", "uint",
"float", "double",
}
***** BEGIN GPL LICENSE BLOCK *****
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The Original Code is Copyright (C) 2001-2002 by NaN Holding BV. All rights reserved.
The Original Code is: all of this file.
Contributor(s): none yet.
***** END GPL LICENSE BLOCK *****
Definition at line 69 of file decimation/test/decimate_glut_test/intern/ply/plyfile.c.