Blender: editmesh_tools.c File Reference
editmesh_tools.c File Reference
mesh
#include "MEM_guardedalloc.h"
#include "DNA_material_types.h"
#include "DNA_mesh_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "RNA_define.h"
#include "RNA_access.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BKE_material.h"
#include "BKE_context.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_depsgraph.h"
#include "BKE_object.h"
#include "BKE_report.h"
#include "BKE_texture.h"
#include "BKE_main.h"
#include "BKE_tessmesh.h"
#include "WM_api.h"
#include "WM_types.h"
#include "ED_mesh.h"
#include "ED_object.h"
#include "ED_screen.h"
#include "ED_transform.h"
#include "ED_uvedit.h"
#include "ED_view3d.h"
#include "RE_render_ext.h"
#include "mesh_intern.h"
Classes
struct PathNode
struct PathEdge
struct CutCurve
struct xvertsort
Defines
#define TRAIL_POLYLINE 1
#define TRAIL_FREEHAND 2
#define TRAIL_MIXED 3
#define TRAIL_AUTO 4
#define TRAIL_MIDPOINTS 8
#define KNIFE_EXACT 1
#define KNIFE_MIDPOINT 2
#define KNIFE_MULTICUT 3
#define MAXSLOPE 100000
#define MAX_CUTS 2048
Typedefs
typedef struct PathNode PathNode
typedef struct PathEdge PathEdge
typedef struct CutCurve CutCurve
typedef struct xvertsort xvertsort
Functions
static void add_normal_aligned (float nor[3], const float add[3])
static int edbm_subdivide_exec (bContext *C, wmOperator *op)
void MESH_OT_subdivide (wmOperatorType *ot)
void EMBM_project_snap_verts (bContext *C, ARegion *ar, Object *obedit, BMEditMesh *em)
static short edbm_extrude_face_indiv (BMEditMesh *em, wmOperator *op, const char hflag, float *UNUSED(nor))
static short edbm_extrude_edges_indiv (BMEditMesh *em, wmOperator *op, const char hflag, float *UNUSED(nor))
static short edbm_extrude_verts_indiv (BMEditMesh *em, wmOperator *op, const char hflag, float *UNUSED(nor))
static short edbm_extrude_edge (Object *obedit, BMEditMesh *em, const char hflag, float nor[3])
static short edbm_extrude_vert (Object *obedit, BMEditMesh *em, const char hflag, float nor[3])
static int edbm_extrude_repeat_exec (bContext *C, wmOperator *op)
void MESH_OT_extrude_repeat (wmOperatorType *ot)
static int edbm_extrude_mesh (Scene *scene, Object *obedit, BMEditMesh *em, wmOperator *op, float *norin)
static int edbm_extrude_region_exec (bContext *C, wmOperator *op)
void MESH_OT_extrude_region (wmOperatorType *ot)
static int edbm_extrude_verts_exec (bContext *C, wmOperator *op)
void MESH_OT_extrude_verts_indiv (wmOperatorType *ot)
static int edbm_extrude_edges_exec (bContext *C, wmOperator *op)
void MESH_OT_extrude_edges_indiv (wmOperatorType *ot)
static int edbm_extrude_faces_exec (bContext *C, wmOperator *op)
void MESH_OT_extrude_faces_indiv (wmOperatorType *ot)
static int edbm_select_all_exec (bContext *C, wmOperator *op)
void MESH_OT_select_all (wmOperatorType *ot)
static int edbm_faces_select_interior_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_select_interior_faces (wmOperatorType *ot)
static int edbm_dupli_extrude_cursor_invoke (bContext *C, wmOperator *op, wmEvent *event)
void MESH_OT_dupli_extrude_cursor (wmOperatorType *ot)
static int edbm_delete_exec (bContext *C, wmOperator *op)
void MESH_OT_delete (wmOperatorType *ot)
static int edbm_collapse_edge_exec (bContext *C, wmOperator *op)
void MESH_OT_edge_collapse (wmOperatorType *ot)
static int edbm_collapse_edge_loop_exec (bContext *C, wmOperator *op)
void MESH_OT_edge_collapse_loop (wmOperatorType *ot)
static int edbm_add_edge_face__smooth_get (BMesh *bm)
static int edbm_add_edge_face_exec (bContext *C, wmOperator *op)
void MESH_OT_edge_face_add (wmOperatorType *ot)
static int edbm_mark_seam (bContext *C, wmOperator *op)
void MESH_OT_mark_seam (wmOperatorType *ot)
static int edbm_mark_sharp (bContext *C, wmOperator *op)
void MESH_OT_mark_sharp (wmOperatorType *ot)
static int edbm_vert_connect (bContext *C, wmOperator *op)
void MESH_OT_vert_connect (wmOperatorType *ot)
static int edbm_edge_split_exec (bContext *C, wmOperator *op)
void MESH_OT_edge_split (wmOperatorType *ot)
static int edbm_duplicate_exec (bContext *C, wmOperator *op)
static int edbm_duplicate_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void MESH_OT_duplicate (wmOperatorType *ot)
static int edbm_flip_normals_exec (bContext *C, wmOperator *op)
void MESH_OT_flip_normals (wmOperatorType *ot)
static int edbm_edge_rotate_selected_exec (bContext *C, wmOperator *op)
void MESH_OT_edge_rotate (wmOperatorType *ot)
static int edbm_hide_exec (bContext *C, wmOperator *op)
void MESH_OT_hide (wmOperatorType *ot)
static int edbm_reveal_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_reveal (wmOperatorType *ot)
static int edbm_normals_make_consistent_exec (bContext *C, wmOperator *op)
void MESH_OT_normals_make_consistent (wmOperatorType *ot)
static int edbm_do_smooth_vertex_exec (bContext *C, wmOperator *op)
void MESH_OT_vertices_smooth (wmOperatorType *ot)
static void mesh_set_smooth_faces (BMEditMesh *em, short smooth)
static int edbm_faces_shade_smooth_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_faces_shade_smooth (wmOperatorType *ot)
static int edbm_faces_shade_flat_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_faces_shade_flat (wmOperatorType *ot)
static int edbm_rotate_uvs_exec (bContext *C, wmOperator *op)
static int edbm_reverse_uvs_exec (bContext *C, wmOperator *op)
static int edbm_rotate_colors_exec (bContext *C, wmOperator *op)
static int edbm_reverse_colors_exec (bContext *C, wmOperator *op)
void MESH_OT_uvs_rotate (wmOperatorType *ot)
void MESH_OT_uvs_reverse (wmOperatorType *ot)
void MESH_OT_colors_rotate (wmOperatorType *ot)
void MESH_OT_colors_reverse (wmOperatorType *ot)
static int merge_firstlast (BMEditMesh *em, int first, int uvmerge, wmOperator *wmop)
static int merge_target (BMEditMesh *em, Scene *scene, View3D *v3d, Object *ob, int target, int uvmerge, wmOperator *wmop)
static int edbm_merge_exec (bContext *C, wmOperator *op)
static EnumPropertyItem * merge_type_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
void MESH_OT_merge (wmOperatorType *ot)
static int edbm_remove_doubles_exec (bContext *C, wmOperator *op)
void MESH_OT_remove_doubles (wmOperatorType *ot)
static int edbm_select_vertex_path_exec (bContext *C, wmOperator *op)
void MESH_OT_select_vertex_path (wmOperatorType *ot)
static void shape_propagate (BMEditMesh *em, wmOperator *op)
static int edbm_shape_propagate_to_all_exec (bContext *C, wmOperator *op)
void MESH_OT_shape_propagate_to_all (wmOperatorType *ot)
static int edbm_blend_from_shape_exec (bContext *C, wmOperator *op)
static EnumPropertyItem * shape_itemf (bContext *C, PointerRNA *UNUSED(ptr), PropertyRNA *UNUSED(prop), int *free)
void MESH_OT_blend_from_shape (wmOperatorType *ot)
static int edbm_select_axis_exec (bContext *C, wmOperator *op)
void MESH_OT_select_axis (wmOperatorType *ot)
static int edbm_solidify_exec (bContext *C, wmOperator *op)
void MESH_OT_solidify (wmOperatorType *ot)
static float bm_edge_seg_isect (BMEdge *e, CutCurve *c, int len, char mode, struct GHash *gh, int *isected)
static int edbm_knife_cut_exec (bContext *C, wmOperator *op)
void MESH_OT_knife_cut (wmOperatorType *ot)
static int mesh_separate_selected (Main *bmain, Scene *scene, Base *editbase, wmOperator *wmop)
static int mesh_separate_material (Main *bmain, Scene *scene, Base *editbase, wmOperator *wmop)
static int mesh_separate_loose (Main *bmain, Scene *scene, Base *editbase, wmOperator *wmop)
static int edbm_separate_exec (bContext *C, wmOperator *op)
void MESH_OT_separate (wmOperatorType *ot)
static int edbm_fill_exec (bContext *C, wmOperator *op)
void MESH_OT_fill (wmOperatorType *ot)
static int edbm_beautify_fill_exec (bContext *C, wmOperator *op)
void MESH_OT_beautify_fill (wmOperatorType *ot)
static int edbm_quads_convert_to_tris_exec (bContext *C, wmOperator *op)
void MESH_OT_quads_convert_to_tris (wmOperatorType *ot)
static int edbm_tris_convert_to_quads_exec (bContext *C, wmOperator *op)
void MESH_OT_tris_convert_to_quads (wmOperatorType *ot)
static int edbm_dissolve_exec (bContext *C, wmOperator *op)
void MESH_OT_dissolve (wmOperatorType *ot)
static int edbm_dissolve_limited_exec (bContext *C, wmOperator *op)
void MESH_OT_dissolve_limited (wmOperatorType *ot)
static int edbm_split_exec (bContext *C, wmOperator *op)
void MESH_OT_split (wmOperatorType *ot)
static int edbm_spin_exec (bContext *C, wmOperator *op)
static int edbm_spin_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void MESH_OT_spin (wmOperatorType *ot)
static int edbm_screw_exec (bContext *C, wmOperator *op)
static int edbm_screw_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void MESH_OT_screw (wmOperatorType *ot)
static int edbm_select_by_number_vertices_exec (bContext *C, wmOperator *op)
void MESH_OT_select_by_number_vertices (wmOperatorType *ot)
static int edbm_select_loose_verts_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_select_loose_verts (wmOperatorType *ot)
static int edbm_select_mirror_exec (bContext *C, wmOperator *op)
void MESH_OT_select_mirror (wmOperatorType *ot)
static int vergxco (const void *v1, const void *v2)
static void xsortvert_flag__doSetX (void *userData, BMVert *UNUSED(eve), int x, int UNUSED(y), int index)
static void xsortvert_flag (bContext *C, int flag)
static int edbm_vertices_sort_exec (bContext *C, wmOperator *UNUSED(op))
void MESH_OT_vertices_sort (wmOperatorType *ot)
static void permutate (void *list, int num, int size, int *index)
static int float_sort (const void *v1, const void *v2)
static int edbm_sort_faces_exec (bContext *C, wmOperator *op)
void MESH_OT_sort_faces (wmOperatorType *ot)
static void hashvert_flag (BMEditMesh *em, int flag, unsigned int seed)
static int edbm_vertices_randomize_exec (bContext *C, wmOperator *op)
void MESH_OT_vertices_randomize (wmOperatorType *ot)
static int edbm_noise_exec (bContext *C, wmOperator *op)
void MESH_OT_noise (wmOperatorType *ot)
static int edbm_bevel_exec (bContext *C, wmOperator *op)
void MESH_OT_bevel (wmOperatorType *ot)
static int edbm_bridge_edge_loops_exec (bContext *C, wmOperator *op)
void MESH_OT_bridge_edge_loops (wmOperatorType *ot)
static int edbm_inset_exec (bContext *C, wmOperator *op)
void MESH_OT_inset (wmOperatorType *ot)
Variables
static EnumPropertyItem prop_mesh_cornervert_types []
static EnumPropertyItem prop_mesh_delete_types []
static const EnumPropertyItem direction_items []
static EnumPropertyItem merge_type_items []
static EnumPropertyItem knife_items []
static EnumPropertyItem prop_separate_types []
static float * face_sort_floats
Detailed Description
Definition in file editmesh_tools.c.
Define Documentation
#define KNIFE_EXACT 1
Definition at line 2484 of file editmesh_tools.c.
Referenced by MESH_OT_knife_cut().
#define KNIFE_MIDPOINT 2
Definition at line 2485 of file editmesh_tools.c.
Referenced by edbm_knife_cut_exec().
#define KNIFE_MULTICUT 3
Definition at line 2486 of file editmesh_tools.c.
Referenced by bm_edge_seg_isect(), and edbm_knife_cut_exec().
#define MAX_CUTS 2048
Definition at line 2653 of file editmesh_tools.c.
Referenced by edbm_knife_cut_exec().
#define MAXSLOPE 100000
Referenced by bm_edge_seg_isect().
#define TRAIL_AUTO 4
Definition at line 2456 of file editmesh_tools.c.
#define TRAIL_FREEHAND 2
Definition at line 2454 of file editmesh_tools.c.
#define TRAIL_MIDPOINTS 8
Definition at line 2457 of file editmesh_tools.c.
#define TRAIL_MIXED 3
Definition at line 2455 of file editmesh_tools.c.
#define TRAIL_POLYLINE 1
Definition at line 2453 of file editmesh_tools.c.
Typedef Documentation
typedef struct CutCurve CutCurve
typedef struct PathEdge PathEdge
typedef struct PathNode PathNode
typedef struct xvertsort xvertsort
Function Documentation
static void add_normal_aligned (float nor[3], const float add[3]) [static]
Definition at line 73 of file editmesh_tools.c.
References add_v3_v3(), dot_v3v3(), and sub_v3_v3().
Referenced by edbm_extrude_edge().
static float bm_edge_seg_isect (BMEdge * e, CutCurve * c, int len, char mode, struct GHash * gh, int * isected) [static]
Definition at line 2497 of file editmesh_tools.c.
References BLI_ghash_lookup(), i, KNIFE_MULTICUT, len(), MAX2, MAXSLOPE, MIN2, BMEdge::v1, BMEdge::v2, CutCurve::x, and CutCurve::y.
Referenced by edbm_knife_cut_exec().
static int edbm_add_edge_face__smooth_get (BMesh * bm) [static]
Definition at line 1016 of file editmesh_tools.c.
References BM_EDGES_OF_MESH, BM_elem_flag_test, BM_elem_flag_test_bool, BM_ELEM_SELECT, BM_ELEM_SMOOTH, BM_ITER_MESH, BMLoop::f, and BMEdge::l.
Referenced by edbm_add_edge_face_exec().
static int edbm_add_edge_face_exec (bContext * C, wmOperator * op) [static]
Definition at line 1033 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_FACE, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), edbm_add_edge_face__smooth_get(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), BMEditMesh::mat_nr, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_edge_face_add().
static int edbm_beautify_fill_exec (bContext * C, wmOperator * op) [static]
Definition at line 3041 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_beautify_fill().
static int edbm_bevel_exec (bContext * C, wmOperator * op) [static]
Definition at line 4086 of file editmesh_tools.c.
References BMEditMesh::bm, BM_data_layer_add(), BM_data_layer_free_n(), BM_EDGES_OF_MESH, BM_ELEM_SELECT, BM_ITER_MESH, BMEdit_FromObject(), BMO_op_exec(), CD_PROP_FLT, BMVert::co, CTX_data_edit_object(), CustomData_bmesh_get_n(), CustomData_number_of_layers(), BMHeader::data, BMesh::edata, EDBM_mesh_normals_update(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), BMEdge::head, i, len_v3v3(), MEM_freeN(), MEM_mallocN(), mul_vn_fl(), NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, powf, wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by MESH_OT_bevel().
static int edbm_blend_from_shape_exec (bContext * C, wmOperator * op) [static]
Definition at line 2219 of file editmesh_tools.c.
References add(), add_v3_v3v3(), blend(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_SHAPEKEY, co, BMVert::co, copy_v3_v3(), CTX_data_edit_object(), CustomData_bmesh_get_n(), CustomData_number_of_layers(), Object::data, BMHeader::data, EDBM_update_generic(), Mesh::edit_btmesh, BMVert::head, interp_v3_v3v3(), mul_v3_fl(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), RNA_float_get(), TRUE, and BMesh::vdata.
Referenced by MESH_OT_blend_from_shape().
static int edbm_bridge_edge_loops_exec (bContext * C, wmOperator * op) [static]
Definition at line 4179 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_bridge_edge_loops().
static int edbm_collapse_edge_exec (bContext * C, wmOperator * op) [static]
Definition at line 960 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_edge_collapse().
static int edbm_collapse_edge_loop_exec (bContext * C, wmOperator * op) [static]
Definition at line 988 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_edge_collapse_loop().
static int edbm_delete_exec (bContext * C, wmOperator * op) [static]
Definition at line 904 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), DEL_EDGES, DEL_EDGESFACES, DEL_FACES, DEL_ONLYFACES, DEL_VERTS, EDBM_flag_disable_all(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and TRUE.
Referenced by MESH_OT_delete().
static int edbm_dissolve_exec (bContext * C, wmOperator * op) [static]
Definition at line 3151 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), SCE_SELECT_EDGE, SCE_SELECT_FACE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, and TRUE.
Referenced by MESH_OT_dissolve().
static int edbm_dissolve_limited_exec (bContext * C, wmOperator * op) [static]
Definition at line 3195 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), and TRUE.
Referenced by MESH_OT_dissolve_limited().
static int edbm_do_smooth_vertex_exec (bContext * C, wmOperator * op) [static]
Definition at line 1516 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), Object::data, EDBM_op_callf(), EDBM_update_generic(), EDBM_verts_mirror_apply(), EDBM_verts_mirror_cache_begin(), EDBM_verts_mirror_cache_end(), eModifierMode_Realtime, eModifierType_Mirror, FALSE, ListBase::first, MirrorModifierData::flag, i, ME_EDIT_MIRROR_X, MOD_MIR_AXIS_X, MOD_MIR_AXIS_Y, MOD_MIR_AXIS_Z, MOD_MIR_CLIPPING, ModifierData::mode, Object::modifiers, ModifierData::next, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_int_get(), MirrorModifierData::tolerance, TRUE, and ModifierData::type.
Referenced by MESH_OT_vertices_smooth().
static int edbm_dupli_extrude_cursor_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 715 of file editmesh_tools.c.
References angle(), angle_normalized_v3v3(), ViewContext::ar, axis_angle_to_mat3(), BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERT, BM_vert_select_set(), BM_VERTS_OF_MESH, BMO_ITER, BMO_op_exec(), BMVert::co, copy_v3_v3(), cross(), cross_v3_v3v3(), DO_MINMAX, edbm_extrude_edge(), EDBM_mesh_normals_update(), EDBM_op_callf(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), ViewContext::em, em_setup_viewcontext(), EMBM_project_snap_verts(), give_cursor(), Object::imat, INIT_MINMAX, invert_m4_m4(), line_point_side_v2(), max, mid_v3_v3v3(), min, mul_m4_v3(), mul_mat3_m4_v3(), mul_v3_m4v3(), wmEvent::mval, normalize_v3(), normalize_v3_v3(), ViewContext::obedit, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, project_float_noclip(), wmOperator::ptr, RNA_boolean_get(), ViewContext::rv3d, SCE_SNAP, SCE_SNAP_MODE_FACE, ViewContext::scene, ToolSettings::snap_flag, ToolSettings::snap_mode, sub_v3_v3(), Scene::toolsettings, TRUE, unit_m3(), BMEdge::v1, BMEdge::v2, ViewContext::v3d, view3d_get_view_aligned_coordinate(), and RegionView3D::viewinv.
Referenced by MESH_OT_dupli_extrude_cursor().
static int edbm_duplicate_exec (bContext * C, wmOperator * op) [static]
Definition at line 1262 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by edbm_duplicate_invoke(), and MESH_OT_duplicate().
static int edbm_duplicate_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 1284 of file editmesh_tools.c.
References edbm_duplicate_exec(), OPERATOR_FINISHED, and WM_cursor_wait().
Referenced by MESH_OT_duplicate().
static int edbm_edge_rotate_selected_exec (bContext * C, wmOperator * op) [static]
Definition at line 1344 of file editmesh_tools.c.
References BKE_report(), BMEditMesh::bm, BM_EDGE, BM_edge_face_pair(), BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_TAG, BM_ITER_MESH, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_selectmode_flush(), EDBM_update_generic(), fb(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_ERROR, BMesh::totedgesel, and TRUE.
Referenced by MESH_OT_edge_rotate().
static int edbm_edge_split_exec (bContext * C, wmOperator * op) [static]
Definition at line 1224 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_get(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), len(), BMOpSlot::len, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_edge_split().
static short edbm_extrude_edge (Object * obedit, BMEditMesh * em, const char hflag, float nor[3]) [static]
Definition at line 242 of file editmesh_tools.c.
References add_normal_aligned(), BMEditMesh::bm, BM_ALL, BM_EDGE, BM_edge_is_boundary(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_elem_select_set(), BM_FACE, BM_iter_new(), BM_iter_step(), BM_VERT, BMO_ITER, BMO_op_exec(), BMO_op_finish(), BMO_op_init(), BMO_slot_buffer_from_enabled_hflag(), BMO_slot_map_ptr_insert(), BMVert::co, copy_v3_v3(), EDBM_flag_disable_all(), eModifierMode_Realtime, eModifierType_Mirror, BMLoop::f, fabsf, ListBase::first, MirrorModifierData::flag, BMElem::head, BMHeader::htype, invert_m4_m4(), is_zero_v3(), BMEdge::l, MirrorModifierData::mirror_ob, MOD_MIR_AXIS_X, MOD_MIR_AXIS_Y, MOD_MIR_AXIS_Z, MOD_MIR_CLIPPING, ModifierData::mode, Object::modifiers, mul_v3_m4v3(), mult_m4_m4m4(), ModifierData::next, BMFace::no, normalize_v3(), NULL, Object::obmat, MirrorModifierData::tolerance, TRUE, ModifierData::type, BMEdge::v1, BMEdge::v2, and zero_v3().
Referenced by edbm_dupli_extrude_cursor_invoke(), edbm_extrude_mesh(), edbm_extrude_repeat_exec(), and edbm_extrude_vert().
static int edbm_extrude_edges_exec (bContext * C, wmOperator * op) [static]
Definition at line 576 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), edbm_extrude_edges_indiv(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by MESH_OT_extrude_edges_indiv().
static short edbm_extrude_edges_indiv (BMEditMesh * em, wmOperator * op, const char hflag, float * UNUSEDnor) [static]
Definition at line 203 of file editmesh_tools.c.
References BMEditMesh::bm, BM_EDGE, BM_ELEM_SELECT, BM_VERT, BMO_op_exec(), BMO_slot_buffer_hflag_enable(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), and TRUE.
Referenced by edbm_extrude_edges_exec(), and edbm_extrude_mesh().
static short edbm_extrude_face_indiv (BMEditMesh * em, wmOperator * op, const char hflag, float * UNUSEDnor) [static]
Definition at line 171 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_FACE, BM_face_select_set(), BM_ITER_ELEM, BM_LOOPS_OF_FACE, BMO_ITER, BMO_op_exec(), copy_v3_v3(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), BMFace::no, BMVert::no, TRUE, and BMLoop::v.
Referenced by edbm_extrude_faces_exec(), and edbm_extrude_mesh().
static int edbm_extrude_faces_exec (bContext * C, wmOperator * op) [static]
Definition at line 607 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), edbm_extrude_face_indiv(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by MESH_OT_extrude_faces_indiv().
static int edbm_extrude_mesh (Scene * scene, Object * obedit, BMEditMesh * em, wmOperator * op, float * norin) [static]
Definition at line 426 of file editmesh_tools.c.
References BKE_report(), BMEditMesh::bm, BM_ELEM_SELECT, edbm_extrude_edge(), edbm_extrude_edges_indiv(), edbm_extrude_face_indiv(), edbm_extrude_vert(), edbm_extrude_verts_indiv(), mul_m4_v3(), object_handle_update(), Object::obmat, wmOperator::reports, RPT_ERROR, SCE_SELECT_EDGE, SCE_SELECT_VERTEX, BMEditMesh::selectmode, sub_v3_v3v3(), BMesh::totedgesel, BMesh::totfacesel, BMesh::totvertsel, and zero_v3().
Referenced by edbm_extrude_region_exec().
static int edbm_extrude_region_exec (bContext * C, wmOperator * op) [static]
Definition at line 509 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_edit_object(), CTX_data_scene(), edbm_extrude_mesh(), EDBM_mesh_normals_update(), EDBM_update_generic(), NULL, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_extrude_region().
static int edbm_extrude_repeat_exec (bContext * C, wmOperator * op) [static]
Definition at line 370 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_callf(), copy_m3_m4(), CTX_data_edit_object(), CTX_wm_region_view3d(), edbm_extrude_edge(), EDBM_mesh_normals_update(), EDBM_update_generic(), invert_m3_m3(), mul_m3_v3(), mul_v3_fl(), normalize_v3_v3(), Object::obmat, offs, OPERATOR_FINISHED, RegionView3D::persinv, wmOperator::ptr, RNA_float_get(), RNA_int_get(), and TRUE.
Referenced by MESH_OT_extrude_repeat().
static short edbm_extrude_vert (Object * obedit, BMEditMesh * em, const char hflag, float nor[3]) [static]
Definition at line 340 of file editmesh_tools.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_vert_select_set(), edbm_extrude_edge(), TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by edbm_extrude_mesh().
static int edbm_extrude_verts_exec (bContext * C, wmOperator * op) [static]
Definition at line 545 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), edbm_extrude_verts_indiv(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by MESH_OT_extrude_verts_indiv().
static short edbm_extrude_verts_indiv (BMEditMesh * em, wmOperator * op, const char hflag, float * UNUSEDnor) [static]
Definition at line 223 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_VERT, BMO_op_exec(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), EDBM_op_finish(), EDBM_op_init(), and TRUE.
Referenced by edbm_extrude_mesh(), and edbm_extrude_verts_exec().
static int edbm_faces_select_interior_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 683 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_edit_object(), EDBM_select_interior_faces(), NC_GEOM, ND_SELECT, OPERATOR_CANCELLED, OPERATOR_FINISHED, and WM_event_add_notifier().
Referenced by MESH_OT_select_interior_faces().
static int edbm_faces_shade_flat_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1634 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_edit_object(), EDBM_update_generic(), FALSE, mesh_set_smooth_faces(), and OPERATOR_FINISHED.
Referenced by MESH_OT_faces_shade_flat().
static int edbm_faces_shade_smooth_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1607 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_edit_object(), EDBM_update_generic(), FALSE, mesh_set_smooth_faces(), and OPERATOR_FINISHED.
Referenced by MESH_OT_faces_shade_smooth().
static int edbm_fill_exec (bContext * C, wmOperator * op) [static]
Definition at line 3001 of file editmesh_tools.c.
References BMEditMesh::bm, BM_EDGE, BM_ELEM_SELECT, BM_FACE, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_fill().
static int edbm_flip_normals_exec (bContext * C, wmOperator * op) [static]
Definition at line 1310 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_flip_normals().
static int edbm_hide_exec (bContext * C, wmOperator * op) [static]
Definition at line 1422 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_edit_object(), EDBM_mesh_hide(), EDBM_update_generic(), OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and TRUE.
Referenced by MESH_OT_hide().
static int edbm_inset_exec (bContext * C, wmOperator * op) [static]
Definition at line 4211 of file editmesh_tools.c.
References BMEditMesh::bm, BM_EDGE, BM_ELEM_SELECT, BM_FACE, BM_mesh_elem_hflag_disable_all(), BM_mesh_elem_hflag_enable_test(), BM_VERT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), and TRUE.
Referenced by MESH_OT_inset().
static int edbm_knife_cut_exec (bContext * C, wmOperator * op) [static]
Definition at line 2655 of file editmesh_tools.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BMEditMesh::bm, BM_EDGE, bm_edge_seg_isect(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SELECT, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMEdit_FromObject(), BMO_elem_flag_disable, BMO_elem_flag_enable, BMO_op_exec(), BMO_slot_bool_set(), BMO_slot_buffer_from_enabled_flag(), BMO_slot_float_set(), BMO_slot_int_set(), BMO_slot_map_float_insert(), co, BMVert::co, copy_v3_v3(), CTX_data_edit_object(), CTX_wm_region(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), ELEM3, FALSE, KNIFE_MIDPOINT, KNIFE_MULTICUT, len(), MAX_CUTS, MEM_freeN(), MEM_mallocN(), mul_m4_v4(), NULL, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, project_float(), wmOperator::ptr, ARegion::regiondata, RNA_BEGIN, RNA_END, RNA_float_get_array(), RNA_int_get(), SUBD_STRAIGHT_CUT, BMesh::totvertsel, and TRUE.
Referenced by MESH_OT_knife_cut().
static int edbm_mark_seam (bContext * C, wmOperator * op) [static]
Definition at line 1077 of file editmesh_tools.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SEAM, BM_ELEM_SELECT, BM_ITER_MESH, BMEdit_FromObject(), clear(), CTX_data_edit_object(), CTX_data_scene(), Object::data, Mesh::drawflag, ED_uvedit_live_unwrap(), EDBM_update_generic(), ME_DRAWSEAMS, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and TRUE.
Referenced by MESH_OT_mark_seam().
static int edbm_mark_sharp (bContext * C, wmOperator * op) [static]
Definition at line 1132 of file editmesh_tools.c.
References BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_disable, BM_elem_flag_enable, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ELEM_SMOOTH, BM_ITER_MESH, BMEdit_FromObject(), clear(), CTX_data_edit_object(), Object::data, Mesh::drawflag, EDBM_update_generic(), ME_DRAWSHARP, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and TRUE.
Referenced by MESH_OT_mark_sharp().
static int edbm_merge_exec (bContext * C, wmOperator * op) [static]
Definition at line 1912 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_view3d(), EDBM_op_callf(), EDBM_update_generic(), merge_firstlast(), merge_target(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), and TRUE.
Referenced by MESH_OT_merge().
static int edbm_noise_exec (bContext * C, wmOperator * op) [static]
Definition at line 4015 of file editmesh_tools.c.
References Object::actcol, add_v3_v3(), BKE_report(), BLI_hnoise(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, BMEdit_FromObject(), BMVert::co, CTX_data_edit_object(), EDBM_mesh_normals_update(), EDBM_update_generic(), externtex(), give_current_material(), give_current_material_texture(), Material::mtex, Tex::noisesize, NULL, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_float_get(), RPT_WARNING, Tex::stype, TEX_STUCCI, TRUE, Tex::turbul, and Tex::type.
Referenced by MESH_OT_noise().
static int edbm_normals_make_consistent_exec (bContext * C, wmOperator * op) [static]
Definition at line 1479 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and TRUE.
Referenced by MESH_OT_normals_make_consistent().
static int edbm_quads_convert_to_tris_exec (bContext * C, wmOperator * op) [static]
Definition at line 3070 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and TRUE.
Referenced by MESH_OT_quads_convert_to_tris().
static int edbm_remove_doubles_exec (bContext * C, wmOperator * op) [static]
Definition at line 2020 of file editmesh_tools.c.
References BKE_reportf(), BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_op_finish(), BMO_slot_map_count(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_float_get(), RPT_INFO, and TRUE.
Referenced by MESH_OT_remove_doubles().
static int edbm_reveal_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 1452 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_edit_object(), EDBM_mesh_reveal(), EDBM_update_generic(), OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_reveal().
static int edbm_reverse_colors_exec (bContext * C, wmOperator * op) [static]
Definition at line 1741 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_colors_reverse().
static int edbm_reverse_uvs_exec (bContext * C, wmOperator * op) [static]
Definition at line 1690 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_uvs_reverse().
static int edbm_rotate_colors_exec (bContext * C, wmOperator * op) [static]
Definition at line 1713 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and TRUE.
Referenced by MESH_OT_colors_rotate().
static int edbm_rotate_uvs_exec (bContext * C, wmOperator * op) [static]
Definition at line 1664 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and TRUE.
Referenced by MESH_OT_uvs_rotate().
static int edbm_screw_exec (bContext * C, wmOperator * op) [static]
Definition at line 3353 of file editmesh_tools.c.
References BKE_report(), BMEditMesh::bm, BM_ALL, BM_EDGES_OF_VERT, BM_elem_flag_test, BM_ELEM_SELECT, BM_iter_new(), BM_iter_step(), BM_VERTS_OF_MESH, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), BMVert::co, copy_m3_m4(), CTX_data_edit_object(), dot_v3v3(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, Object::imat, mul_m3_v3(), mul_v3_fl(), negate_v3(), NULL, Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_float_get_array(), RNA_int_get(), RPT_ERROR, sub_v3_v3(), sub_v3_v3v3(), and TRUE.
Referenced by edbm_screw_invoke(), and MESH_OT_screw().
static int edbm_screw_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 3440 of file editmesh_tools.c.
References CTX_data_scene(), CTX_wm_view3d(), ED_view3d_context_rv3d(), edbm_screw_exec(), give_cursor(), wmOperator::ptr, RNA_float_set_array(), and RegionView3D::viewinv.
Referenced by MESH_OT_screw().
static int edbm_select_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 639 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_flag_disable_all(), EDBM_flag_enable_all(), EDBM_select_swap(), EDBM_select_toggle_all(), EDBM_selectmode_flush(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), SEL_DESELECT, SEL_INVERT, SEL_SELECT, SEL_TOGGLE, and WM_event_add_notifier().
Referenced by MESH_OT_select_all().
static int edbm_select_axis_exec (bContext * C, wmOperator * op) [static]
Definition at line 2319 of file editmesh_tools.c.
References BKE_report(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ITER_MESH, BM_VERT, BM_vert_select_set(), BM_VERTS_OF_MESH, BMEdit_FromObject(), BMVert::co, CTX_data_edit_object(), CTX_data_tool_settings(), Object::data, ToolSettings::doublimit, EDBM_selectmode_flush(), BMEditSelection::ele, fabs(), BMEditSelection::htype, ListBase::last, NC_GEOM, ND_DATA, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_enum_get(), RPT_WARNING, BMesh::selected, TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_select_axis().
static int edbm_select_by_number_vertices_exec (bContext * C, wmOperator * op) [static]
Definition at line 3477 of file editmesh_tools.c.
References BMEditMesh::bm, BM_face_select_set(), BM_FACES_OF_MESH, BM_iter_new(), BM_iter_step(), BMEdit_FromObject(), CTX_data_edit_object(), Object::data, EDBM_selectmode_flush(), BMFace::len, NC_GEOM, ND_SELECT, NULL, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), RNA_int_get(), TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_select_by_number_vertices().
static int edbm_select_loose_verts_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3541 of file editmesh_tools.c.
References BMEditMesh::bm, BM_edge_select_set(), BM_EDGES_OF_MESH, BM_iter_new(), BM_iter_step(), BM_vert_select_set(), BM_VERTS_OF_MESH, BMEdit_FromObject(), CTX_data_edit_object(), Object::data, BMVert::e, EDBM_selectmode_flush(), BMEdge::l, NC_GEOM, ND_SELECT, NULL, OPERATOR_FINISHED, TRUE, and WM_event_add_notifier().
Referenced by MESH_OT_select_loose_verts().
static int edbm_select_mirror_exec (bContext * C, wmOperator * op) [static]
Definition at line 3586 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_edit_object(), Object::data, EDBM_select_mirrored(), EDBM_selectmode_flush(), NC_GEOM, ND_SELECT, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), and WM_event_add_notifier().
Referenced by MESH_OT_select_mirror().
static int edbm_select_vertex_path_exec (bContext * C, wmOperator * op) [static]
Definition at line 2083 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BM_VERT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_selectmode_flush(), EDBM_update_generic(), BMEditSelection::ele, FALSE, BMEditSelection::htype, ListBase::last, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, BMEditSelection::prev, wmOperator::ptr, RNA_enum_get(), BMesh::selected, and TRUE.
Referenced by MESH_OT_select_vertex_path().
static int edbm_separate_exec (bContext * C, wmOperator * op) [static]
Definition at line 2949 of file editmesh_tools.c.
References BMEdit_FromObject(), CTX_data_active_base(), CTX_data_main(), CTX_data_scene(), EDBM_update_generic(), mesh_separate_loose(), mesh_separate_material(), mesh_separate_selected(), Base::object, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_enum_get(), and TRUE.
Referenced by MESH_OT_separate().
static int edbm_shape_propagate_to_all_exec (bContext * C, wmOperator * op) [static]
Definition at line 2189 of file editmesh_tools.c.
References CTX_data_edit_object(), Object::data, EDBM_update_generic(), Mesh::edit_btmesh, FALSE, OPERATOR_FINISHED, and shape_propagate().
Referenced by MESH_OT_shape_propagate_to_all().
static int edbm_solidify_exec (bContext * C, wmOperator * op) [static]
Definition at line 2399 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_FACE, BMO_op_exec(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), Object::data, EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), Mesh::edit_btmesh, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_float_get(), and TRUE.
Referenced by MESH_OT_solidify().
static int edbm_sort_faces_exec (bContext * C, wmOperator * op) [static]
Definition at line 3781 of file editmesh_tools.c.
References add_v3_v3(), BLI_frand(), MVert::co, copy_v3_v3(), CTX_data_edit_object(), CTX_data_scene(), CTX_wm_view3d(), Scene::cursor, View3D::cursor, CustomData_sizeof(), DAG_id_tag_update(), Object::data, CustomDataLayer::data, ED_object_enter_editmode(), ED_object_exit_editmode(), ED_view3d_context_rv3d(), EM_FREEDATA, MPoly::flag, float_sort(), i, invert_m4_m4(), len_v3v3(), View3D::localvd, MPoly::loopstart, MPoly::mat_nr, ME_FACE_SEL, MEM_freeN(), MEM_mallocN(), Mesh::mloop, Mesh::mpoly, mul_m4_v3(), mul_v3_fl(), mult_m4_m4m4(), Mesh::mvert, OBACT, OPERATOR_CANCELLED, OPERATOR_FINISHED, permutate(), wmOperator::ptr, RNA_enum_get(), MPoly::totloop, Mesh::totpoly, CustomDataLayer::type, MLoop::v, RegionView3D::viewmat, and zero_v3().
Referenced by MESH_OT_sort_faces().
static int edbm_spin_exec (bContext * C, wmOperator * op) [static]
Definition at line 3272 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ALL, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), copy_m3_m4(), CTX_data_edit_object(), EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), Object::imat, mul_m3_v3(), Object::obmat, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), RNA_float_get_array(), RNA_int_get(), sub_v3_v3(), and TRUE.
Referenced by edbm_spin_invoke(), and MESH_OT_spin().
static int edbm_spin_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 3316 of file editmesh_tools.c.
References CTX_data_scene(), CTX_wm_view3d(), ED_view3d_context_rv3d(), edbm_spin_exec(), give_cursor(), wmOperator::ptr, RNA_float_set_array(), and RegionView3D::viewinv.
Referenced by MESH_OT_spin().
static int edbm_split_exec (bContext * C, wmOperator * op) [static]
Definition at line 3234 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ALL, BM_EDGE, BM_ELEM_SELECT, BM_FACE, BM_mesh_elem_hflag_disable_all(), BM_VERT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), EDBM_mesh_normals_update(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), FALSE, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_split().
static int edbm_subdivide_exec (bContext * C, wmOperator * op) [static]
Definition at line 83 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_mesh_esubdivide(), BMEdit_FromObject(), CTX_data_edit_object(), EDBM_update_generic(), OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_enum_get(), RNA_enum_set(), RNA_float_get(), RNA_int_get(), smooth(), SUBD_INNERVERT, SUBD_STRAIGHT_CUT, SUBDIV_SELECT_ORIG, and TRUE.
Referenced by MESH_OT_subdivide().
static int edbm_tris_convert_to_quads_exec (bContext * C, wmOperator * op) [static]
Definition at line 3101 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), EDBM_op_callf(), EDBM_update_generic(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, RNA_boolean_get(), RNA_float_get(), and TRUE.
Referenced by MESH_OT_tris_convert_to_quads().
static int edbm_vert_connect (bContext * C, wmOperator * op) [static]
Definition at line 1187 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BMEdit_FromObject(), BMO_op_exec(), BMO_slot_get(), CTX_data_edit_object(), EDBM_op_finish(), EDBM_op_init(), EDBM_update_generic(), len(), BMOpSlot::len, OPERATOR_CANCELLED, OPERATOR_FINISHED, and TRUE.
Referenced by MESH_OT_vert_connect().
static int edbm_vertices_randomize_exec (bContext * C, wmOperator * op) [static]
Definition at line 3982 of file editmesh_tools.c.
References BM_ELEM_SELECT, BMEdit_FromObject(), CTX_data_edit_object(), hashvert_flag(), OPERATOR_FINISHED, wmOperator::ptr, and RNA_int_get().
Referenced by MESH_OT_vertices_randomize().
static int edbm_vertices_sort_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 3726 of file editmesh_tools.c.
References BM_ELEM_SELECT, OPERATOR_FINISHED, and xsortvert_flag().
Referenced by MESH_OT_vertices_sort().
void EMBM_project_snap_verts (bContext * C, ARegion * ar, Object * obedit, BMEditMesh * em)
Definition at line 150 of file editmesh_tools.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, BMVert::co, Object::imat, mul_v3_m4v3(), Object::obmat, project_float_noclip(), SNAP_NOT_OBEDIT, and snapObjectsContext().
Referenced by edbm_dupli_extrude_cursor_invoke().
static int float_sort (const void * v1, const void * v2) [static]
Definition at line 3769 of file editmesh_tools.c.
Referenced by edbm_sort_faces_exec().
static void hashvert_flag (BMEditMesh * em, int flag, unsigned int seed) [static]
Definition at line 3931 of file editmesh_tools.c.
References BLI_array_randomize(), BMEditMesh::bm, BM_elem_flag_test, BM_ITER_MESH_INDEX, BM_mesh_remap(), BM_VERTS_OF_MESH, FALSE, i, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, BMesh::totvert, and TRUE.
Referenced by edbm_vertices_randomize_exec().
static int merge_firstlast (BMEditMesh * em, int first, int uvmerge, wmOperator * wmop) [static]
Definition at line 1838 of file editmesh_tools.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BMVert::co, EDBM_op_callf(), BMEditSelection::ele, ListBase::first, ListBase::last, OPERATOR_CANCELLED, OPERATOR_FINISHED, and BMesh::selected.
Referenced by edbm_merge_exec().
static int merge_target (BMEditMesh * em, Scene * scene, View3D * v3d, Object * ob, int target, int uvmerge, wmOperator * wmop) [static]
Definition at line 1867 of file editmesh_tools.c.
References add_v3_v3(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, co, BMVert::co, copy_v3_v3(), EDBM_op_callf(), give_cursor(), i, Object::imat, mul_m4_v3(), mul_v3_fl(), NULL, OPERATOR_CANCELLED, and OPERATOR_FINISHED.
Referenced by edbm_merge_exec().
static EnumPropertyItem* merge_type_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 1956 of file editmesh_tools.c.
References BMEditMesh::bm, BM_VERT, BMEdit_FromObject(), CTX_data_edit_object(), ListBase::first, ListBase::last, merge_type_items, NULL, OB_MESH, RNA_enum_item_end(), RNA_enum_items_add_value(), SCE_SELECT_VERTEX, BMesh::selected, BMEditMesh::selectmode, and Object::type.
Referenced by MESH_OT_merge().
void MESH_OT_beautify_fill (wmOperatorType * ot)
Definition at line 3054 of file editmesh_tools.c.
References ED_operator_editmesh(), edbm_beautify_fill_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_bevel (wmOperatorType * ot)
Definition at line 4156 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_bevel_exec(), wmOperatorType::exec, FALSE, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_blend_from_shape (wmOperatorType * ot)
Definition at line 2293 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_blend_from_shape_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_float(), shape_itemf(), wmOperatorType::srna, and WM_operator_props_popup().
Referenced by ED_operatortypes_mesh().
void MESH_OT_bridge_edge_loops (wmOperatorType * ot)
Definition at line 4192 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_bridge_edge_loops_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_colors_reverse (wmOperatorType * ot)
Definition at line 1819 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_reverse_colors_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_colors_rotate (wmOperatorType * ot)
Definition at line 1801 of file editmesh_tools.c.
References wmOperatorType::description, DIRECTION_CCW, ED_operator_editmesh(), edbm_rotate_colors_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_delete (wmOperatorType * ot)
Definition at line 940 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_delete_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_dissolve (wmOperatorType * ot)
Definition at line 3176 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_dissolve_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_dissolve_limited (wmOperatorType * ot)
Definition at line 3213 of file editmesh_tools.c.
References DEG2RADF, wmOperatorType::description, ED_operator_editmesh(), edbm_dissolve_limited_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_rotation(), RNA_def_property_float_default(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_dupli_extrude_cursor (wmOperatorType * ot)
Definition at line 877 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_dupli_extrude_cursor_invoke(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_duplicate (wmOperatorType * ot)
Definition at line 1293 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_duplicate_exec(), edbm_duplicate_invoke(), wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_int(), wmOperatorType::srna, and TFM_TRANSLATION.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_collapse (wmOperatorType * ot)
Definition at line 973 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_collapse_edge_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_collapse_loop (wmOperatorType * ot)
Definition at line 1001 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_collapse_edge_loop_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_face_add (wmOperatorType * ot)
Definition at line 1060 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_add_edge_face_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_rotate (wmOperatorType * ot)
Definition at line 1403 of file editmesh_tools.c.
References wmOperatorType::description, DIRECTION_CW, ED_operator_editmesh(), edbm_edge_rotate_selected_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_edge_split (wmOperatorType * ot)
Definition at line 1246 of file editmesh_tools.c.
References ED_operator_editmesh(), edbm_edge_split_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_edges_indiv (wmOperatorType * ot)
Definition at line 589 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_edges_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_faces_indiv (wmOperatorType * ot)
Definition at line 620 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_faces_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_region (wmOperatorType * ot)
Definition at line 527 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_region_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_repeat (wmOperatorType * ot)
Definition at line 406 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh_view3d(), edbm_extrude_repeat_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_extrude_verts_indiv (wmOperatorType * ot)
Definition at line 558 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_extrude_verts_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_faces_shade_flat (wmOperatorType * ot)
Definition at line 1646 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_faces_shade_flat_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_faces_shade_smooth (wmOperatorType * ot)
Definition at line 1619 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_faces_shade_smooth_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_fill (wmOperatorType * ot)
Definition at line 3026 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_fill_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_flip_normals (wmOperatorType * ot)
Definition at line 1323 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_flip_normals_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_hide (wmOperatorType * ot)
Definition at line 1434 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_hide_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_inset (wmOperatorType * ot)
Definition at line 4253 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_inset_exec(), wmOperatorType::exec, FALSE, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), RNA_def_property_ui_range(), wmOperatorType::srna, and TRUE.
Referenced by ED_operatortypes_mesh().
void MESH_OT_knife_cut (wmOperatorType * ot)
Definition at line 2756 of file editmesh_tools.c.
References BC_KNIFECURSOR, wmOperatorType::description, edbm_knife_cut_exec(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, KNIFE_EXACT, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_COLLECTION, PROP_NONE, RNA_def_enum(), RNA_def_int(), RNA_def_property(), RNA_def_property_struct_runtime(), RNA_OperatorMousePath, wmOperatorType::srna, WM_gesture_lines_invoke(), and WM_gesture_lines_modal().
void MESH_OT_mark_seam (wmOperatorType * ot)
Definition at line 1115 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_mark_seam(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_mark_sharp (wmOperatorType * ot)
Definition at line 1169 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_mark_sharp(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_merge (wmOperatorType * ot)
Definition at line 1998 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_merge_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, merge_type_itemf(), wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_noise (wmOperatorType * ot)
Definition at line 4068 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_noise_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_normals_make_consistent (wmOperatorType * ot)
Definition at line 1497 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_normals_make_consistent_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_quads_convert_to_tris (wmOperatorType * ot)
Definition at line 3084 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_quads_convert_to_tris_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_remove_doubles (wmOperatorType * ot)
Definition at line 2048 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_remove_doubles_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_reveal (wmOperatorType * ot)
Definition at line 1464 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_reveal_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_screw (wmOperatorType * ot)
Definition at line 3452 of file editmesh_tools.c.
References wmOperatorType::description, edbm_screw_exec(), edbm_screw_invoke(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float_vector(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_all (wmOperatorType * ot)
Definition at line 666 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_all_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_axis (wmOperatorType * ot)
Definition at line 2368 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_axis_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_by_number_vertices (wmOperatorType * ot)
Definition at line 3515 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_by_number_vertices_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_interior_faces (wmOperatorType * ot)
Definition at line 699 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_faces_select_interior_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_loose_verts (wmOperatorType * ot)
Definition at line 3571 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_loose_verts_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_mirror (wmOperatorType * ot)
Definition at line 3599 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_mirror_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_select_vertex_path (wmOperatorType * ot)
Definition at line 2128 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_select_vertex_path_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), wmOperatorType::srna, VPATH_SELECT_EDGE_LENGTH, and VPATH_SELECT_TOPOLOGICAL.
Referenced by ED_operatortypes_mesh().
void MESH_OT_separate (wmOperatorType * ot)
Definition at line 2982 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_separate_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_shape_propagate_to_all (wmOperatorType * ot)
Definition at line 2203 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_shape_propagate_to_all_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_solidify (wmOperatorType * ot)
Definition at line 2434 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_solidify_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_float(), RNA_def_property_ui_range(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_sort_faces (wmOperatorType * ot)
Definition at line 3903 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_sort_faces_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_mesh().
void MESH_OT_spin (wmOperatorType * ot)
Definition at line 3328 of file editmesh_tools.c.
References wmOperatorType::description, edbm_spin_exec(), edbm_spin_invoke(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float(), RNA_def_float_vector(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_split (wmOperatorType * ot)
Definition at line 3256 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_split_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_subdivide (wmOperatorType * ot)
Definition at line 118 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_subdivide_exec(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_enum(), RNA_def_float(), RNA_def_int(), RNA_def_property_flag(), wmOperatorType::srna, and SUBD_STRAIGHT_CUT.
Referenced by ED_operatortypes_mesh().
void MESH_OT_tris_convert_to_quads (wmOperatorType * ot)
Definition at line 3125 of file editmesh_tools.c.
References DEG2RADF, wmOperatorType::description, ED_operator_editmesh(), edbm_tris_convert_to_quads_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_float_rotation(), RNA_def_property_float_default(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uvs_reverse (wmOperatorType * ot)
Definition at line 1783 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_reverse_uvs_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_uvs_rotate (wmOperatorType * ot)
Definition at line 1764 of file editmesh_tools.c.
References wmOperatorType::description, DIRECTION_CW, ED_operator_editmesh(), edbm_rotate_uvs_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vert_connect (wmOperatorType * ot)
Definition at line 1209 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_vert_connect(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertices_randomize (wmOperatorType * ot)
Definition at line 3993 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_vertices_randomize_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertices_smooth (wmOperatorType * ot)
Definition at line 1574 of file editmesh_tools.c.
References wmOperatorType::description, ED_operator_editmesh(), edbm_do_smooth_vertex_exec(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
void MESH_OT_vertices_sort (wmOperatorType * ot)
Definition at line 3732 of file editmesh_tools.c.
References wmOperatorType::description, edbm_vertices_sort_exec(), EM_view3d_poll(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_mesh().
static int mesh_separate_loose (Main * bmain, Scene * scene, Base * editbase, wmOperator * wmop) [static]
Definition at line 2881 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_ITER_MESH, BM_vert_select_set(), BM_VERTS_OF_MESH, BMEdit_FromObject(), BMW_begin(), BMW_end(), BMW_FLAG_NOP, BMW_init(), BMW_MASK_NOP, BMW_NIL_LAY, BMW_SHELL, BMW_step(), EDBM_flag_disable_all(), EDBM_selectmode_flush_ex(), FALSE, i, mesh_separate_selected(), NULL, Base::object, SCE_SELECT_VERTEX, BMesh::totvert, BMesh::totvertsel, TRUE, BMEdge::v1, and BMEdge::v2.
Referenced by edbm_separate_exec().
static int mesh_separate_material (Main * bmain, Scene * scene, Base * editbase, wmOperator * wmop) [static]
Definition at line 2847 of file editmesh_tools.c.
References BMEditMesh::bm, BM_ELEM_SELECT, BM_face_select_set(), BM_FACES_OF_MESH, BM_iter_at_index(), BM_ITER_MESH, BMEdit_FromObject(), EDBM_flag_disable_all(), FALSE, BMFace::mat_nr, mesh_separate_selected(), NULL, Base::object, BMesh::totface, and TRUE.
Referenced by edbm_separate_exec().
static int mesh_separate_selected (Main * bmain, Scene * scene, Base * editbase, wmOperator * wmop) [static]
Definition at line 2781 of file editmesh_tools.c.
References assign_matarar(), BA_DESELECT, BMEditMesh::bm, BM_EDGE, BM_edge_is_wire(), BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_FACE, BM_ITER_MESH, BM_LOOP, bm_mesh_allocsize_default, BM_mesh_bm_to_me(), BM_mesh_create(), BM_mesh_free(), BM_mesh_normals_update(), BM_VERT, BM_vert_edge_count(), BM_vert_select_set(), BM_VERTS_OF_MESH, CD_CALLOC, CD_MASK_BMESH, CustomData_bmesh_init_pool(), CustomData_copy(), Object::data, DEL_EDGES, DEL_FACES, DEL_VERTS, ED_base_object_select(), ED_object_add_duplicate(), BMesh::edata, EDBM_op_callf(), Mesh::edit_btmesh, FALSE, give_matarar(), give_totcolp(), BMesh::ldata, NULL, Base::object, BMesh::pdata, BMAllocTemplate::totedge, BMAllocTemplate::totface, BMAllocTemplate::totloop, BMAllocTemplate::totvert, TRUE, USER_DUP_MESH, and BMesh::vdata.
Referenced by edbm_separate_exec(), mesh_separate_loose(), and mesh_separate_material().
static void mesh_set_smooth_faces (BMEditMesh * em, short smooth) [static]
Definition at line 1593 of file editmesh_tools.c.
References BMEditMesh::bm, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_SELECT, BM_ELEM_SMOOTH, BM_FACES_OF_MESH, BM_ITER_MESH, and NULL.
Referenced by edbm_faces_shade_flat_exec(), and edbm_faces_shade_smooth_exec().
static void permutate (void * list, int num, int size, int * index) [static]
Definition at line 3750 of file editmesh_tools.c.
References i, len(), MEM_freeN(), MEM_mallocN(), and size().
Referenced by edbm_sort_faces_exec().
static EnumPropertyItem* shape_itemf (bContext * C, PointerRNA * UNUSEDptr, PropertyRNA * UNUSEDprop, int * free) [static]
Definition at line 2261 of file editmesh_tools.c.
References BMEditMesh::bm, BMEdit_FromObject(), CD_SHAPEKEY, CTX_data_edit_object(), CustomData_has_layer(), EnumPropertyItem::identifier, CustomData::layers, EnumPropertyItem::name, CustomDataLayer::name, NULL, OB_MESH, RNA_enum_item_add(), RNA_enum_item_end(), CustomData::totlayer, Object::type, CustomDataLayer::type, EnumPropertyItem::value, and BMesh::vdata.
Referenced by MESH_OT_blend_from_shape().
static void shape_propagate (BMEditMesh * em, wmOperator * op) [static]
Definition at line 2156 of file editmesh_tools.c.
References BKE_report(), BMEditMesh::bm, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_ELEM_SELECT, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_SHAPEKEY, co, BMVert::co, copy_v3_v3(), CustomData_bmesh_get_n(), CustomData_has_layer(), CustomData_number_of_layers(), BMHeader::data, BMVert::head, i, NULL, OB_RECALC_DATA, wmOperator::reports, RPT_ERROR, and BMesh::vdata.
Referenced by edbm_shape_propagate_to_all_exec().
static int vergxco (const void * v1, const void * v2) [static]
Definition at line 3632 of file editmesh_tools.c.
References xvertsort::org_idx, and xvertsort::x.
Referenced by xsortvert_flag().
static void xsortvert_flag (bContext * C, int flag) [static]
Definition at line 3666 of file editmesh_tools.c.
References BMEditMesh::bm, BM_elem_flag_test, BM_ITER_MESH_INDEX, BM_mesh_remap(), BM_VERTS_OF_MESH, ED_view3d_init_mats_rv3d(), ViewContext::em, em_setup_viewcontext(), i, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mesh_foreachScreenVert(), NULL, ViewContext::obedit, xvertsort::org_idx, ViewContext::rv3d, BMesh::totvert, V3D_CLIP_TEST_OFF, vergxco(), and xsortvert_flag__doSetX().
Referenced by edbm_vertices_sort_exec().
static void xsortvert_flag__doSetX (void * userData, BMVert * UNUSEDeve, int x, int UNUSEDy, int index) [static]
Definition at line 3658 of file editmesh_tools.c.
References xvertsort::x.
Referenced by xsortvert_flag().
Variable Documentation
const EnumPropertyItem direction_items[] [static]
Initial value:
 {
    {DIRECTION_CW, "CW", 0, "Clockwise", ""},
    {DIRECTION_CCW, "CCW", 0, "Counter Clockwise", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 1338 of file editmesh_tools.c.
Referenced by ARMATURE_OT_select_hierarchy(), CURVE_OT_cyclic_toggle(), POSE_OT_select_hierarchy(), and uv_transform_properties().
float* face_sort_floats [static]
Definition at line 3768 of file editmesh_tools.c.
EnumPropertyItem knife_items[] [static]
Initial value:
 {
    {KNIFE_EXACT, "EXACT", 0, "Exact", ""},
    {KNIFE_MIDPOINT, "MIDPOINTS", 0, "Midpoints", ""},
    {KNIFE_MULTICUT, "MULTICUT", 0, "Multicut", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 2488 of file editmesh_tools.c.
EnumPropertyItem merge_type_items[] [static]
Initial value:
 {
    {6, "FIRST", 0, "At First", ""},
    {1, "LAST", 0, "At Last", ""},
    {3, "CENTER", 0, "At Center", ""},
    {4, "CURSOR", 0, "At Cursor", ""},
    {5, "COLLAPSE", 0, "Collapse", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 1948 of file editmesh_tools.c.
Referenced by merge_type_itemf().
EnumPropertyItem prop_mesh_cornervert_types[] [static]
Initial value:
 {
    {SUBD_INNERVERT,     "INNERVERT", 0,      "Inner Vert", ""},
    {SUBD_PATH,          "PATH", 0,           "Path", ""},
    {SUBD_STRAIGHT_CUT,  "STRAIGHT_CUT", 0,   "Straight Cut", ""},
    {SUBD_FAN,           "FAN", 0,            "Fan", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 110 of file editmesh_tools.c.
EnumPropertyItem prop_mesh_delete_types[] [static]
Initial value:
 {
    {0, "VERT",      0, "Vertices", ""},
    {1,  "EDGE",      0, "Edges", ""},
    {2,  "FACE",      0, "Faces", ""},
    {3,  "EDGE_FACE", 0, "Edges & Faces", ""},
    {4,  "ONLY_FACE", 0, "Only Faces", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 895 of file editmesh_tools.c.
EnumPropertyItem prop_separate_types[] [static]
Initial value:
 {
    {0, "SELECTED", 0, "Selection", ""},
    {1, "MATERIAL", 0, "By Material", ""},
    {2, "LOOSE", 0, "By loose parts", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 2975 of file editmesh_tools.c.