Blender: smoke_API.h File Reference
smoke_API.h File Reference
smoke
Functions
void smoke_export (struct FLUID_3D *fluid, float *dt, float *dx, float **dens, float **densold, float **heat, float **heatold, float **vx, float **vy, float **vz, float **vxold, float **vyold, float **vzold, unsigned char **obstacles)
struct FLUID_3D * smoke_init (int *res, float *p0)
void smoke_free (struct FLUID_3D *fluid)
void smoke_initBlenderRNA (struct FLUID_3D *fluid, float *alpha, float *beta, float *dt_factor, float *vorticity, int *border_colli)
void smoke_step (struct FLUID_3D *fluid, size_t framenr, float fps)
float * smoke_get_density (struct FLUID_3D *fluid)
float * smoke_get_heat (struct FLUID_3D *fluid)
float * smoke_get_velocity_x (struct FLUID_3D *fluid)
float * smoke_get_velocity_y (struct FLUID_3D *fluid)
float * smoke_get_velocity_z (struct FLUID_3D *fluid)
float * smoke_get_force_x (struct FLUID_3D *fluid)
float * smoke_get_force_y (struct FLUID_3D *fluid)
float * smoke_get_force_z (struct FLUID_3D *fluid)
unsigned char * smoke_get_obstacle (struct FLUID_3D *fluid)
size_t smoke_get_index (int x, int max_x, int y, int max_y, int z)
size_t smoke_get_index2d (int x, int max_x, int y)
void smoke_dissolve (struct FLUID_3D *fluid, int speed, int log)
struct WTURBULENCE * smoke_turbulence_init (int *res, int amplify, int noisetype)
void smoke_turbulence_free (struct WTURBULENCE *wt)
void smoke_turbulence_step (struct WTURBULENCE *wt, struct FLUID_3D *fluid)
float * smoke_turbulence_get_density (struct WTURBULENCE *wt)
void smoke_turbulence_get_res (struct WTURBULENCE *wt, int *res)
void smoke_turbulence_set_noise (struct WTURBULENCE *wt, int type)
void smoke_initWaveletBlenderRNA (struct WTURBULENCE *wt, float *strength)
void smoke_dissolve_wavelet (struct WTURBULENCE *wt, int speed, int log)
void smoke_turbulence_export (struct WTURBULENCE *wt, float **dens, float **densold, float **tcu, float **tcv, float **tcw)
Detailed Description
Definition in file smoke_API.h.
Function Documentation
void smoke_dissolve (struct FLUID_3D * fluid, int speed, int log)
Definition at line 128 of file smoke_API.cpp.
References FLUID_3D::_density, FLUID_3D::_heat, FLUID_3D::_xRes, FLUID_3D::_yRes, FLUID_3D::_zRes, abs(), i, and size().
void smoke_dissolve_wavelet (struct WTURBULENCE * wt, int speed, int log)
Definition at line 174 of file smoke_API.cpp.
References WTURBULENCE::getDensityBig(), WTURBULENCE::getResBig(), i, and size().
void smoke_export (struct FLUID_3D * fluid, float * dt, float * dx, float ** dens, float ** densold, float ** heat, float ** heatold, float ** vx, float ** vy, float ** vz, float ** vxold, float ** vyold, float ** vzold, unsigned char ** obstacles)
Definition at line 219 of file smoke_API.cpp.
References FLUID_3D::_density, FLUID_3D::_densityOld, FLUID_3D::_dt, FLUID_3D::_dx, FLUID_3D::_heat, FLUID_3D::_heatOld, FLUID_3D::_obstacles, FLUID_3D::_xVelocity, FLUID_3D::_xVelocityOld, FLUID_3D::_yVelocity, FLUID_3D::_yVelocityOld, FLUID_3D::_zVelocity, and FLUID_3D::_zVelocityOld.
void smoke_free (struct FLUID_3D * fluid)
Definition at line 58 of file smoke_API.cpp.
References NULL.
float* smoke_get_density (struct FLUID_3D * fluid)
Definition at line 249 of file smoke_API.cpp.
References FLUID_3D::_density.
Referenced by draw_object(), GPU_create_smoke(), and init_frame_smoke().
float* smoke_get_force_x (struct FLUID_3D * fluid)
Definition at line 274 of file smoke_API.cpp.
References FLUID_3D::_xForce.
float* smoke_get_force_y (struct FLUID_3D * fluid)
Definition at line 279 of file smoke_API.cpp.
References FLUID_3D::_yForce.
float* smoke_get_force_z (struct FLUID_3D * fluid)
Definition at line 284 of file smoke_API.cpp.
References FLUID_3D::_zForce.
float* smoke_get_heat (struct FLUID_3D * fluid)
Definition at line 254 of file smoke_API.cpp.
References FLUID_3D::_heat.
Referenced by init_frame_smoke().
size_t smoke_get_index (int x, int max_x, int y, int max_y, int z)
Definition at line 70 of file smoke_API.cpp.
Referenced by draw_object().
size_t smoke_get_index2d (int x, int max_x, int y)
Definition at line 76 of file smoke_API.cpp.
unsigned char* smoke_get_obstacle (struct FLUID_3D * fluid)
Definition at line 305 of file smoke_API.cpp.
References FLUID_3D::_obstacles.
float* smoke_get_velocity_x (struct FLUID_3D * fluid)
Definition at line 259 of file smoke_API.cpp.
References FLUID_3D::_xVelocity.
Referenced by init_frame_smoke().
float* smoke_get_velocity_y (struct FLUID_3D * fluid)
Definition at line 264 of file smoke_API.cpp.
References FLUID_3D::_yVelocity.
Referenced by init_frame_smoke().
float* smoke_get_velocity_z (struct FLUID_3D * fluid)
Definition at line 269 of file smoke_API.cpp.
References FLUID_3D::_zVelocity.
Referenced by init_frame_smoke().
struct FLUID_3D* smoke_init (int * res, float * p0) [read]
Definition at line 39 of file smoke_API.cpp.
References FLUID_3D::FLUID_3D().
void smoke_initBlenderRNA (struct FLUID_3D * fluid, float * alpha, float * beta, float * dt_factor, float * vorticity, int * border_colli)
Definition at line 123 of file smoke_API.cpp.
References FLUID_3D::initBlenderRNA().
void smoke_initWaveletBlenderRNA (struct WTURBULENCE * wt, float * strength)
Definition at line 209 of file smoke_API.cpp.
References WTURBULENCE::initBlenderRNA().
void smoke_step (struct FLUID_3D * fluid, size_t framenr, float fps)
Definition at line 81 of file smoke_API.cpp.
References FLUID_3D::_dtFactor, FLUID_3D::_xRes, FLUID_3D::_xVelocity, FLUID_3D::_yRes, FLUID_3D::_yVelocity, FLUID_3D::_zRes, FLUID_3D::_zVelocity, DT_DEFAULT, i, size(), sqrt(), and FLUID_3D::step().
void smoke_turbulence_export (struct WTURBULENCE * wt, float ** dens, float ** densold, float ** tcu, float ** tcv, float ** tcw)
Definition at line 237 of file smoke_API.cpp.
References WTURBULENCE::_densityBig, WTURBULENCE::_densityBigOld, WTURBULENCE::_tcU, WTURBULENCE::_tcV, and WTURBULENCE::_tcW.
void smoke_turbulence_free (struct WTURBULENCE * wt)
Definition at line 64 of file smoke_API.cpp.
References NULL.
float* smoke_turbulence_get_density (struct WTURBULENCE * wt)
Definition at line 289 of file smoke_API.cpp.
References WTURBULENCE::getDensityBig(), and NULL.
Referenced by GPU_create_smoke(), and init_frame_smoke().
void smoke_turbulence_get_res (struct WTURBULENCE * wt, int * res)
Definition at line 294 of file smoke_API.cpp.
References WTURBULENCE::getResBig().
Referenced by init_frame_smoke().
struct WTURBULENCE* smoke_turbulence_init (int * res, int amplify, int noisetype) [read]
Definition at line 49 of file smoke_API.cpp.
References NULL.
void smoke_turbulence_set_noise (struct WTURBULENCE * wt, int type)
Definition at line 310 of file smoke_API.cpp.
References WTURBULENCE::setNoise().
void smoke_turbulence_step (struct WTURBULENCE * wt, struct FLUID_3D * fluid)
Definition at line 118 of file smoke_API.cpp.
References FLUID_3D::_dt, FLUID_3D::_dx, FLUID_3D::_obstacles, FLUID_3D::_xVelocity, FLUID_3D::_yVelocity, FLUID_3D::_zVelocity, and WTURBULENCE::stepTurbulenceFull().