Blender: openexr_api.h File Reference
openexr_api.h File Reference
OpenEXR
#include <stdio.h>
Functions
void imb_initopenexr (void)
int imb_is_a_openexr (unsigned char *mem)
int imb_save_openexr (struct ImBuf *ibuf, const char *name, int flags)
struct ImBuf * imb_load_openexr (unsigned char *mem, size_t size, int flags)
Detailed Description
Definition in file openexr_api.h.
Function Documentation
void imb_initopenexr (void)
Test presence of OpenEXR file.
Parameters:
mem pointer to loaded OpenEXR bitstream
Definition at line 1076 of file openexr_api.cpp.
References BLI_system_thread_count().
int imb_is_a_openexr (unsigned char * mem)
Definition at line 158 of file openexr_api.cpp.
Referenced by imb_load_openexr().
struct ImBuf* imb_load_openexr (unsigned char * mem, size_t size, int flags) [read]
Definition at line 963 of file openexr_api.cpp.
References addzbuffloatImBuf(), exr_has_zbuffer(), exr_is_multilayer(), exr_print_filecontents(), exr_rgba_channelname(), ImBuf::ftype, IB_multilayer, IB_PROFILE_LINEAR_RGB, IB_test, imb_addrectfloatImBuf(), IMB_allocImBuf(), imb_exr_begin_read_mem(), IMB_exr_read_channels(), IMB_freeImBuf(), imb_is_a_openexr(), NULL, OPENEXR, ImBuf::profile, ImBuf::rect_float, ImBuf::userdata, and ImBuf::zbuf_float.
int imb_save_openexr (struct ImBuf * ibuf, const char * name, int flags)
Definition at line 365 of file openexr_api.cpp.
References ImBuf::encodedsize, ImBuf::ftype, IB_mem, imb_addencodedbufferImBuf(), imb_save_openexr_float(), imb_save_openexr_half(), NULL, OPENEXR_HALF, and ImBuf::rect_float.