Blender: crazyspace.c File Reference
crazyspace.c File Reference
editor utilities
#include "MEM_guardedalloc.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "DNA_modifier_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "BKE_DerivedMesh.h"
#include "BKE_modifier.h"
#include "BKE_multires.h"
#include "BKE_mesh.h"
#include "BKE_tessmesh.h"
#include "ED_util.h"
Classes
struct MappedUserData
Defines
#define TAN_MAKE_VEC(a, b, c) a[0] = b[0] + 0.2f * (b[0] - c[0]); a[1] = b[1] + 0.2f * (b[1] - c[1]); a[2] = b[2] + 0.2f * (b[2] - c[2])
Functions
static void set_crazy_vertex_quat (float *quat, float *v1, float *v2, float *v3, float *def1, float *def2, float *def3)
static void make_vertexcos__mapFunc (void *userData, int index, const float co[3], const float UNUSED(no_f[3]), const short UNUSED(no_s[3]))
static int modifiers_disable_subsurf_temporary (Object *ob)
float * crazyspace_get_mapped_editverts (Scene *scene, Object *obedit)
void crazyspace_set_quats_editmesh (BMEditMesh *em, float *origcos, float *mappedcos, float *quats)
void crazyspace_set_quats_mesh (Mesh *me, float *origcos, float *mappedcos, float *quats)
int editbmesh_get_first_deform_matrices (Scene *scene, Object *ob, BMEditMesh *em, float(**deformmats)[3][3], float(**deformcos)[3])
int sculpt_get_first_deform_matrices (Scene *scene, Object *ob, float(**deformmats)[3][3], float(**deformcos)[3])
void crazyspace_build_sculpt (Scene *scene, Object *ob, float(**deformmats)[3][3], float(**deformcos)[3])
Detailed Description
Definition in file crazyspace.c.
Define Documentation
#define TAN_MAKE_VEC (a, b, c) a[0] = b[0] + 0.2f * (b[0] - c[0]); a[1] = b[1] + 0.2f * (b[1] - c[1]); a[2] = b[2] + 0.2f * (b[2] - c[2])
Definition at line 57 of file crazyspace.c.
Referenced by set_crazy_vertex_quat().
Function Documentation
void crazyspace_build_sculpt (Scene * scene, Object * ob, float(**) deformmats[3][3], float(**) deformcos[3])
Definition at line 434 of file crazyspace.c.
References copy_m3_m3(), crazyspace_set_quats_mesh(), Object::data, ModifierTypeInfo::deformMatrices, ModifierTypeInfo::deformVerts, eModifierMode_Realtime, eModifierTypeType_OnlyDeform, i, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), MEM_mallocN(), mesh_getVertexCos(), modifier_isEnabled(), modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, mul_m3_m3m3(), ModifierData::next, NULL, quat_to_mat3(), sculpt_get_first_deform_matrices(), Mesh::totvert, ModifierData::type, ModifierTypeInfo::type, and unit_m3().
Referenced by sculpt_update_mesh_elements().
float* crazyspace_get_mapped_editverts (Scene * scene, Object * obedit)
Definition at line 106 of file crazyspace.c.
References BMEditMesh::bm, CD_MASK_BAREMESH, Object::data, Mesh::edit_btmesh, editbmesh_get_derived_cage(), MappedUserData::flags, DerivedMesh::foreachMappedVert, make_vertexcos__mapFunc(), makeDerivedMesh(), MEM_callocN(), MEM_freeN(), modifiers_disable_subsurf_temporary(), DerivedMesh::release, BMesh::totvert, and MappedUserData::vertexcos.
Referenced by createTransEditVerts().
void crazyspace_set_quats_editmesh (BMEditMesh * em, float * origcos, float * mappedcos, float * quats)
Definition at line 141 of file crazyspace.c.
References BMEditMesh::bm, BM_edge_other_vert(), BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_elem_index_set, BM_ELEM_SELECT, BM_face_other_edge_loop(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_VERT, BM_mesh_elem_index_ensure(), BM_VERT, BM_VERTS_OF_MESH, BMVert::co, BMLoop::e, BMesh::elem_index_dirty, BMLoop::f, if(), MEM_callocN(), MEM_freeN(), NULL, BMIter::p, set_crazy_vertex_quat(), BMesh::totvert, and BMLoop::v.
Referenced by createTransEditVerts().
void crazyspace_set_quats_mesh (Mesh * me, float * origcos, float * mappedcos, float * quats)
Definition at line 263 of file crazyspace.c.
References MVert::co, MVert::flag, i, if(), ME_VERT_TMP_TAG, Mesh::mface, Mesh::mvert, set_crazy_vertex_quat(), Mesh::totface, Mesh::totvert, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by crazyspace_build_sculpt().
int editbmesh_get_first_deform_matrices (Scene * scene, Object * ob, BMEditMesh * em, float(**) deformmats[3][3], float(**) deformcos[3])
Definition at line 323 of file crazyspace.c.
References ModifierTypeInfo::deformMatricesEM, editbmesh_get_vertex_cos(), editbmesh_modifier_is_enabled(), eModifierTypeType_OnlyDeform, getEditDerivedBMesh(), i, MEM_callocN(), modifier_isCorrectableDeformed(), modifiers_clearErrors(), modifiers_getCageIndex(), modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, ModifierData::next, NULL, DerivedMesh::release, ModifierTypeInfo::type, and unit_m3().
Referenced by createTransEditVerts().
static void make_vertexcos__mapFunc (void * userData, int index, const float co[3], const float UNUSEDno_f[3], const short UNUSEDno_s[3]) [static]
Definition at line 75 of file crazyspace.c.
References copy_v3_v3(), MappedUserData::flags, and MappedUserData::vertexcos.
Referenced by crazyspace_get_mapped_editverts().
static int modifiers_disable_subsurf_temporary (Object * ob) [static]
Definition at line 90 of file crazyspace.c.
References eModifierMode_DisableTemporary, eModifierMode_OnCage, eModifierType_Subsurf, ListBase::first, ModifierData::mode, Object::modifiers, ModifierData::next, and ModifierData::type.
Referenced by crazyspace_get_mapped_editverts().
int sculpt_get_first_deform_matrices (Scene * scene, Object * ob, float(**) deformmats[3][3], float(**) deformcos[3])
Definition at line 376 of file crazyspace.c.
References Object::data, ModifierTypeInfo::deformMatrices, eModifierMode_Realtime, eModifierTypeType_OnlyDeform, get_multires_modifier(), MEM_callocN(), mesh_create_derived(), mesh_getVertexCos(), modifier_isEnabled(), modifiers_getVirtualModifierList(), modifierType_getInfo(), mti, ModifierData::next, NULL, DerivedMesh::release, MultiresModifierData::sculptlvl, ModifierData::type, ModifierTypeInfo::type, and unit_m3().
Referenced by crazyspace_build_sculpt().
static void set_crazy_vertex_quat (float * quat, float * v1, float * v2, float * v3, float * def1, float * def2, float * def3) [static]
Definition at line 58 of file crazyspace.c.
References sub_qt_qtqt(), TAN_MAKE_VEC, and tri_to_quat().
Referenced by crazyspace_set_quats_editmesh(), and crazyspace_set_quats_mesh().