Blender: btOverlappingPairCallback Class Reference
btOverlappingPairCallback Class Reference
The btOverlappingPairCallback class is an additional optional broadphase user callback for adding/removing overlapping pairs, similar interface to btOverlappingPairCache.
#include <btOverlappingPairCallback.h>
Public Member Functions
virtual ~btOverlappingPairCallback ()
virtual btBroadphasePair * addOverlappingPair (btBroadphaseProxy *proxy0, btBroadphaseProxy *proxy1)=0
virtual void * removeOverlappingPair (btBroadphaseProxy *proxy0, btBroadphaseProxy *proxy1, btDispatcher *dispatcher)=0
virtual void removeOverlappingPairsContainingProxy (btBroadphaseProxy *proxy0, btDispatcher *dispatcher)=0
Detailed Description
The btOverlappingPairCallback class is an additional optional broadphase user callback for adding/removing overlapping pairs, similar interface to btOverlappingPairCache.
Definition at line 24 of file btOverlappingPairCallback.h.
Constructor & Destructor Documentation
virtual btOverlappingPairCallback::~btOverlappingPairCallback () [inline, virtual]
Definition at line 27 of file btOverlappingPairCallback.h.
Member Function Documentation
virtual btBroadphasePair* btOverlappingPairCallback::addOverlappingPair (btBroadphaseProxy * proxy0, btBroadphaseProxy * proxy1) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, btNullPairCache, and btGhostPairCallback.
Referenced by btSortedOverlappingPairCache::addOverlappingPair(), btSimpleBroadphase::calculateOverlappingPairs(), and btDbvtTreeCollider::Process().
virtual void* btOverlappingPairCallback::removeOverlappingPair (btBroadphaseProxy * proxy0, btBroadphaseProxy * proxy1, btDispatcher * dispatcher) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, btNullPairCache, and btGhostPairCallback.
Referenced by btSimpleBroadphase::calculateOverlappingPairs(), btDbvtBroadphase::collide(), btSortedOverlappingPairCache::removeOverlappingPair(), and btHashedOverlappingPairCache::removeOverlappingPair().
virtual void btOverlappingPairCallback::removeOverlappingPairsContainingProxy (btBroadphaseProxy * proxy0, btDispatcher * dispatcher) [pure virtual]
Implemented in btHashedOverlappingPairCache, btSortedOverlappingPairCache, btNullPairCache, and btGhostPairCallback.
Referenced by btDbvtBroadphase::collide(), btDbvtBroadphase::destroyProxy(), and btSimpleBroadphase::destroyProxy().
The documentation for this class was generated from the following file:
btOverlappingPairCallback.h