Blender: SCA_IScene Class Reference
SCA_IScene Class Reference
#include <SCA_IScene.h>
Public Member Functions
SCA_IScene ()
virtual ~SCA_IScene ()
virtual class SCA_IObject * AddReplicaObject (class CValue *gameobj, class CValue *locationobj, int lifespan=0)=0
virtual void RemoveObject (class CValue *gameobj)=0
virtual void DelayedRemoveObject (class CValue *gameobj)=0
virtual void ReplaceMesh (class CValue *gameobj, void *meshobj, bool use_gfx, bool use_phys)=0
std::vector< SCA_DebugProp * > & GetDebugProperties ()
void AddDebugProperty (class CValue *debugprop, const STR_String &name)
void RemoveAllDebugProperties ()
virtual void Update2DFilter (std::vector< STR_String > &propNames, void *gameObj, RAS_2DFilterManager::RAS_2DFILTER_MODE filtermode, int pass, STR_String &text)
Detailed Description
Definition at line 52 of file SCA_IScene.h.
Constructor & Destructor Documentation
SCA_IScene::SCA_IScene ()
Definition at line 46 of file SCA_IScene.cpp.
SCA_IScene::~SCA_IScene () [virtual]
Definition at line 61 of file SCA_IScene.cpp.
References RemoveAllDebugProperties().
Member Function Documentation
void SCA_IScene::AddDebugProperty (class CValue * debugprop, const STR_String & name)
Definition at line 74 of file SCA_IScene.cpp.
References CValue::AddRef(), SCA_DebugProp::m_name, and SCA_DebugProp::m_obj.
Referenced by BL_ConvertProperties(), and KX_GameActuator::Update().
virtual class SCA_IObject* SCA_IScene::AddReplicaObject (class CValue * gameobj, class CValue * locationobj, int lifespan = 0) [pure virtual]
Implemented in KX_Scene.
Referenced by KX_SCA_AddObjectActuator::InstantAddObject().
virtual void SCA_IScene::DelayedRemoveObject (class CValue * gameobj) [pure virtual]
Implemented in KX_Scene.
Referenced by KX_SCA_EndObjectActuator::Update().
std::vector< SCA_DebugProp * > & SCA_IScene::GetDebugProperties ()
Definition at line 67 of file SCA_IScene.cpp.
Referenced by KX_KetsjiEngine::SceneListsChanged().
void SCA_IScene::RemoveAllDebugProperties ()
Definition at line 50 of file SCA_IScene.cpp.
Referenced by KX_Scene::~KX_Scene(), and ~SCA_IScene().
virtual void SCA_IScene::RemoveObject (class CValue * gameobj) [pure virtual]
Implemented in KX_Scene.
virtual void SCA_IScene::ReplaceMesh (class CValue * gameobj, void * meshobj, bool use_gfx, bool use_phys) [pure virtual]
Implemented in KX_Scene.
Referenced by KX_SCA_ReplaceMeshActuator::InstantReplaceMesh(), and KX_SCA_ReplaceMeshActuator::Update().
virtual void SCA_IScene::Update2DFilter (std::vector< STR_String > & propNames, void * gameObj, RAS_2DFilterManager::RAS_2DFILTER_MODE filtermode, int pass, STR_String & text) [inline, virtual]
Reimplemented in KX_Scene.
Definition at line 71 of file SCA_IScene.h.
Referenced by SCA_2DFilterActuator::Update().
The documentation for this class was generated from the following files:
SCA_IScene.h
SCA_IScene.cpp