Blender: clip_toolbar.c File Reference
clip_toolbar.c File Reference
#include <string.h>
#include "DNA_windowmanager_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_screen.h"
#include "ED_util.h"
#include "WM_types.h"
#include "WM_api.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "clip_intern.h"
Functions
static ARegion * clip_has_properties_region (ScrArea *sa)
static int properties_poll (bContext *C)
static int properties_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_properties (wmOperatorType *ot)
static ARegion * clip_has_tools_region (ScrArea *sa)
static int tools_poll (bContext *C)
static int tools_exec (bContext *C, wmOperator *UNUSED(op))
void CLIP_OT_tools (wmOperatorType *ot)
static void clip_panel_operator_redo_buts (const bContext *C, Panel *pa, wmOperator *op)
static void clip_panel_operator_redo_header (const bContext *C, Panel *pa)
static void clip_panel_operator_redo_operator (const bContext *C, Panel *pa, wmOperator *op)
static void clip_panel_operator_redo (const bContext *C, Panel *pa)
void ED_clip_tool_props_register (ARegionType *art)
Detailed Description
Definition in file clip_toolbar.c.
Function Documentation
static ARegion* clip_has_properties_region (ScrArea * sa) [static]
Definition at line 59 of file clip_toolbar.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ARegion::flag, MEM_callocN(), NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_RIGHT, RGN_FLAG_HIDDEN, RGN_TYPE_HEADER, and RGN_TYPE_UI.
Referenced by properties_exec().
static ARegion* clip_has_tools_region (ScrArea * sa) [static]
Definition at line 115 of file clip_toolbar.c.
References ARegion::alignment, BKE_area_find_region_type(), BLI_insertlinkafter(), ListBase::first, ARegion::flag, MEM_callocN(), ARegion::next, NULL, ScrArea::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_FLAG_HIDDEN, RGN_SPLIT_PREV, RGN_TYPE_HEADER, RGN_TYPE_TOOL_PROPS, and RGN_TYPE_TOOLS.
Referenced by tools_exec().
void CLIP_OT_properties (wmOperatorType * ot)
Definition at line 101 of file clip_toolbar.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, properties_exec(), and properties_poll().
Referenced by clip_operatortypes().
void CLIP_OT_tools (wmOperatorType * ot)
Definition at line 176 of file clip_toolbar.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, wmOperatorType::poll, tools_exec(), and tools_poll().
Referenced by clip_operatortypes().
static void clip_panel_operator_redo (const bContext * C, Panel * pa) [static]
Definition at line 219 of file clip_toolbar.c.
References clip_panel_operator_redo_operator(), ED_undo_operator_repeat_cb_evt(), Panel::layout, wmOperatorType::name, NULL, wmOperator::type, uiBlockSetHandleFunc(), uiLayoutGetBlock(), uiLayoutSetEnabled(), WM_operator_check_ui_enabled(), WM_operator_last_redo(), and WM_operator_poll().
Referenced by ED_clip_tool_props_register().
static void clip_panel_operator_redo_buts (const bContext * C, Panel * pa, wmOperator * op) [static]
Definition at line 190 of file clip_toolbar.c.
References Panel::layout, NULL, and uiLayoutOperatorButs().
Referenced by clip_panel_operator_redo_operator().
static void clip_panel_operator_redo_header (const bContext * C, Panel * pa) [static]
Definition at line 195 of file clip_toolbar.c.
References BLI_strncpy(), Panel::drawname, wmOperatorType::name, wmOperator::type, and WM_operator_last_redo().
Referenced by ED_clip_tool_props_register().
static void clip_panel_operator_redo_operator (const bContext * C, Panel * pa, wmOperator * op) [static]
Definition at line 205 of file clip_toolbar.c.
References clip_panel_operator_redo_buts(), ListBase::first, wmOperatorType::flag, Panel::layout, wmOperator::macro, wmOperatorType::name, wmOperator::next, OPTYPE_MACRO, wmOperator::type, and uiItemL().
Referenced by clip_panel_operator_redo().
void ED_clip_tool_props_register (ARegionType * art)
Definition at line 241 of file clip_toolbar.c.
References BLI_addtail(), clip_panel_operator_redo(), clip_panel_operator_redo_header(), PanelType::draw, PanelType::draw_header, PanelType::idname, PanelType::label, MEM_callocN(), and ARegionType::paneltypes.
Referenced by ED_spacetype_clip().
static int properties_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 90 of file clip_toolbar.c.
References clip_has_properties_region(), CTX_wm_area(), ED_region_toggle_hidden(), and OPERATOR_FINISHED.
Referenced by CLIP_OT_properties().
static int properties_poll (bContext * C) [static]
Definition at line 85 of file clip_toolbar.c.
References CTX_wm_space_clip(), and NULL.
Referenced by CLIP_OT_properties().
static int tools_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 165 of file clip_toolbar.c.
References clip_has_tools_region(), CTX_wm_area(), ED_region_toggle_hidden(), and OPERATOR_FINISHED.
Referenced by CLIP_OT_tools().
static int tools_poll (bContext * C) [static]
Definition at line 160 of file clip_toolbar.c.
References CTX_wm_space_clip(), and NULL.
Referenced by CLIP_OT_tools().