Blender: text.c File Reference
text.c File Reference
blenkernel
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <wchar.h>
#include <wctype.h>
#include "MEM_guardedalloc.h"
#include "BLI_path_util.h"
#include "BLI_string.h"
#include "BLI_string_cursor_utf8.h"
#include "BLI_string_utf8.h"
#include "BLI_listbase.h"
#include "BLI_utildefines.h"
#include "BLI_fileops.h"
#include "DNA_constraint_types.h"
#include "DNA_controller_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_space_types.h"
#include "DNA_text_types.h"
#include "DNA_userdef_types.h"
#include "DNA_object_types.h"
#include "BKE_depsgraph.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_text.h"
Functions
static void txt_pop_first (Text *text)
static void txt_pop_last (Text *text)
static void txt_undo_add_op (Text *text, int op)
static void txt_undo_add_block (Text *text, int op, const char *buf)
static void txt_delete_line (Text *text, TextLine *line)
static void txt_delete_sel (Text *text)
static void txt_make_dirty (Text *text)
void txt_set_undostate (int u)
int txt_get_undostate (void)
static void init_undo_text (Text *text)
void free_text (Text *text)
Text * add_empty_text (const char *name)
int txt_extended_ascii_as_utf8 (char **str)
static void cleanup_textline (TextLine *tl)
int reopen_text (Text *text)
Text * add_text (const char *file, const char *relpath)
Text * copy_text (Text *ta)
void unlink_text (Main *bmain, Text *text)
void clear_text (Text *text)
void write_text (Text *text, const char *str)
static void make_new_line (TextLine *line, char *newline)
static TextLine * txt_new_line (const char *str)
static TextLine * txt_new_linen (const char *str, int n)
void txt_clean_text (Text *text)
int txt_get_span (TextLine *from, TextLine *to)
static void txt_curs_cur (Text *text, TextLine ***linep, int **charp)
static void txt_curs_sel (Text *text, TextLine ***linep, int **charp)
static void txt_curs_first (Text *text, TextLine **linep, int *charp)
int txt_utf8_offset_to_index (const char *str, int offset)
int txt_utf8_index_to_offset (const char *str, int index)
static int txt_utf8_len (const char *src)
void txt_move_up (Text *text, short sel)
void txt_move_down (Text *text, short sel)
void txt_move_left (Text *text, short sel)
void txt_move_right (Text *text, short sel)
void txt_jump_left (Text *text, short sel)
void txt_jump_right (Text *text, short sel)
void txt_move_bol (Text *text, short sel)
void txt_move_eol (Text *text, short sel)
void txt_move_bof (Text *text, short sel)
void txt_move_eof (Text *text, short sel)
void txt_move_toline (Text *text, unsigned int line, short sel)
void txt_move_to (Text *text, unsigned int line, unsigned int ch, short sel)
static void txt_curs_swap (Text *text)
void txt_pop_sel (Text *text)
void txt_order_cursors (Text *text)
int txt_has_sel (Text *text)
void txt_sel_all (Text *text)
void txt_sel_line (Text *text)
char * txt_to_buf (Text *text)
int txt_find_string (Text *text, const char *findstr, int wrap, int match_case)
char * txt_sel_to_buf (Text *text)
static void txt_shift_markers (Text *text, int lineno, int count)
void txt_insert_buf (Text *text, const char *in_buffer)
static int max_undo_test (Text *text, int x)
static void dump_buffer (Text *text)
void txt_print_undo (Text *text)
static void txt_undo_store_uint16 (char *undo_buf, int *undo_pos, unsigned short value)
static void txt_undo_store_uint32 (char *undo_buf, int *undo_pos, unsigned int value)
void txt_undo_add_toop (Text *text, int op, unsigned int froml, unsigned short fromc, unsigned int tol, unsigned short toc)
static void txt_undo_add_charop (Text *text, int op_start, unsigned int c)
static unsigned short txt_undo_read_uint16 (const char *undo_buf, int *undo_pos)
static unsigned int txt_undo_read_uint32 (const char *undo_buf, int *undo_pos)
static unsigned int txt_undo_read_unicode (const char *undo_buf, int *undo_pos, short bytes)
static unsigned short txt_redo_read_uint16 (const char *undo_buf, int *undo_pos)
static unsigned int txt_redo_read_uint32 (const char *undo_buf, int *undo_pos)
static unsigned int txt_redo_read_unicode (const char *undo_buf, int *undo_pos, short bytes)
void txt_do_undo (Text *text)
void txt_do_redo (Text *text)
void txt_split_curline (Text *text)
static void txt_combine_lines (Text *text, TextLine *linea, TextLine *lineb)
void txt_delete_char (Text *text)
void txt_delete_word (Text *text)
void txt_backspace_char (Text *text)
void txt_backspace_word (Text *text)
static void txt_convert_tab_to_spaces (Text *text)
static int txt_add_char_intern (Text *text, unsigned int add, int replace_tabs)
int txt_add_char (Text *text, unsigned int add)
int txt_add_raw_char (Text *text, unsigned int add)
void txt_delete_selected (Text *text)
int txt_replace_char (Text *text, unsigned int add)
void txt_indent (Text *text)
void txt_unindent (Text *text)
void txt_comment (Text *text)
void txt_uncomment (Text *text)
int setcurr_tab_spaces (Text *text, int space)
void txt_add_marker (Text *text, TextLine *line, int start, int end, const unsigned char color[4], int group, int flags)
TextMarker * txt_find_marker_region (Text *text, TextLine *line, int start, int end, int group, int flags)
short txt_clear_marker_region (Text *text, TextLine *line, int start, int end, int group, int flags)
short txt_clear_markers (Text *text, int group, int flags)
TextMarker * txt_find_marker (Text *text, TextLine *line, int curs, int group, int flags)
TextMarker * txt_prev_marker (Text *text, TextMarker *marker)
TextMarker * txt_next_marker (Text *text, TextMarker *marker)
int text_check_bracket (const char ch)
int text_check_delim (const char ch)
int text_check_digit (const char ch)
int text_check_identifier (const char ch)
int text_check_whitespace (const char ch)
Variables
static unsigned char undoing
static char tab_to_spaces [] = " "
Detailed Description
Definition in file text.c.
Function Documentation
Text* add_empty_text (const char * name) [read]
Definition at line 183 of file text.c.
References alloc_libblock(), BLI_addhead(), Text::curc, Text::curl, ListBase::first, Text::flags, TextLine::format, G, Text::id, ID_TXT, init_undo_text(), ListBase::last, TextLine::len, TextLine::line, Text::lines, Text::markers, MEM_mallocN(), Text::name, TextLine::next, Text::nlines, NULL, TextLine::prev, Text::selc, Text::sell, Main::text, TXT_ISDIRTY, TXT_ISMEM, TXT_TABSTOSPACES, ID::us, and USER_TXT_TABSTOSPACES_DISABLE.
Referenced by reports_to_text_exec(), and text_new_exec().
Text* add_text (const char * file, const char * relpath) [read]
Definition at line 376 of file text.c.
References alloc_libblock(), BLI_addtail(), BLI_fopen(), BLI_path_abs(), BLI_path_basename(), BLI_strncpy(), cleanup_textline(), Text::curc, Text::curl, FILE_MAX, ListBase::first, Text::flags, TextLine::format, fseek, ftell, G, i, Text::id, ID_TXT, init_undo_text(), L, ListBase::last, TextLine::len, len(), TextLine::line, Text::lines, Text::markers, MEM_freeN(), MEM_mallocN(), Text::mtime, Text::name, Text::nlines, NULL, Text::selc, Text::sell, str, strlen(), Main::text, TXT_TABSTOSPACES, ID::us, and USER_TXT_TABSTOSPACES_DISABLE.
Referenced by main(), and text_open_exec().
static void cleanup_textline (TextLine * tl) [static]
Definition at line 267 of file text.c.
References i, TextLine::len, TextLine::line, and txt_extended_ascii_as_utf8().
Referenced by add_text(), and reopen_text().
void clear_text (Text * text)
Definition at line 596 of file text.c.
References txt_delete_sel(), txt_get_undostate(), txt_make_dirty(), txt_sel_all(), and txt_set_undostate().
Text* copy_text (Text * ta) [read]
Definition at line 476 of file text.c.
References BLI_addtail(), copy_libblock(), Text::curc, Text::curl, ListBase::first, Text::flags, TextLine::format, Text::id, init_undo_text(), ListBase::last, TextLine::len, TextLine::line, Text::lines, Text::markers, MEM_mallocN(), Text::name, TextLine::next, Text::nlines, NULL, Text::selc, Text::sell, strlen(), KDL::tan(), and TXT_ISDIRTY.
Referenced by id_copy().
static void dump_buffer (Text * text) [static]
Definition at line 1579 of file text.c.
References i, Text::undo_buf, and Text::undo_pos.
Referenced by txt_print_undo().
void free_text (Text * text)
Definition at line 163 of file text.c.
References BLI_freelistN(), BPY_text_free_code(), Text::compiled, ListBase::first, TextLine::format, TextLine::line, Text::lines, Text::markers, MEM_freeN(), Text::name, TextLine::next, and Text::undo_buf.
Referenced by free_libblock().
static void init_undo_text (Text * text) [static]
Definition at line 156 of file text.c.
References MEM_mallocN(), TXT_INIT_UNDO, Text::undo_buf, Text::undo_len, and Text::undo_pos.
Referenced by add_empty_text(), add_text(), copy_text(), max_undo_test(), and reopen_text().
static void make_new_line (TextLine * line, char * newline) [static]
Definition at line 625 of file text.c.
References TextLine::format, TextLine::len, TextLine::line, MEM_freeN(), NULL, and strlen().
Referenced by txt_add_char_intern(), txt_combine_lines(), txt_comment(), txt_delete_sel(), and txt_indent().
static int max_undo_test (Text * text, int x) [static]
Definition at line 1558 of file text.c.
References init_undo_text(), MEM_callocN(), MEM_freeN(), TXT_MAX_UNDO, Text::undo_buf, Text::undo_len, and Text::undo_pos.
Referenced by txt_undo_add_block(), txt_undo_add_charop(), txt_undo_add_op(), and txt_undo_add_toop().
int reopen_text (Text * text)
Definition at line 281 of file text.c.
References BLI_addtail(), BLI_fopen(), BLI_freelistN(), BLI_path_abs(), BLI_strncpy(), cleanup_textline(), Text::curc, Text::curl, FILE_MAX, ListBase::first, TextLine::format, fseek, ftell, G, i, init_undo_text(), L, ListBase::last, TextLine::len, len(), TextLine::line, Text::lines, MEM_freeN(), MEM_mallocN(), Text::mtime, Text::name, TextLine::next, Text::nlines, NULL, Text::selc, Text::sell, str, Text::undo_buf, and Text::undo_pos.
Referenced by direct_link_text(), and text_reload_exec().
int setcurr_tab_spaces (Text * text, int space)
Definition at line 3039 of file text.c.
References Text::curc, Text::curl, Text::flags, i, TextLine::line, NULL, and TXT_TABSTOSPACES.
Referenced by text_line_break_exec().
int text_check_bracket (const char ch)
Definition at line 3252 of file text.c.
Referenced by draw_brackets().
int text_check_delim (const char ch)
Definition at line 3268 of file text.c.
Referenced by txt_format_line().
int text_check_digit (const char ch)
Definition at line 3280 of file text.c.
Referenced by txt_format_line().
int text_check_identifier (const char ch)
Definition at line 3287 of file text.c.
Referenced by confirm_suggestion(), find_bool(), find_builtinfunc(), find_decorator(), find_specialvar(), and get_suggest_prefix().
int text_check_whitespace (const char ch)
Definition at line 3298 of file text.c.
Referenced by do_texttools().
int txt_add_char (Text * text, unsigned int add)
Definition at line 2746 of file text.c.
References Text::flags, txt_add_char_intern(), and TXT_TABSTOSPACES.
Referenced by do_textmarkers(), do_texttools(), text_indent_exec(), text_insert_exec(), text_line_break_exec(), txt_do_redo(), txt_do_undo(), and txt_replace_char().
static int txt_add_char_intern (Text * text, unsigned int add, int replace_tabs) [static]
Definition at line 2693 of file text.c.
References BLI_str_utf8_from_unicode(), BLI_UTF8_MAX, Text::curc, Text::curl, TextMarker::end, TextLine::len, TextLine::line, TextMarker::lineno, make_new_line(), MEM_mallocN(), TextMarker::next, TextMarker::start, txt_clean_text(), txt_convert_tab_to_spaces(), txt_delete_sel(), txt_find_marker_region(), txt_make_dirty(), txt_pop_sel(), txt_split_curline(), txt_undo_add_charop(), UNDO_INSERT_1, and undoing.
Referenced by txt_add_char(), and txt_add_raw_char().
void txt_add_marker (Text * text, TextLine * line, int start, int end, const unsigned char color[4], int group, int flags)
Definition at line 3106 of file text.c.
References BLI_addhead(), BLI_insertlinkafter(), TextMarker::color, TextMarker::end, ListBase::first, TextMarker::flags, TextMarker::group, ListBase::last, TextMarker::lineno, Text::lines, Text::markers, MAX2, MEM_mallocN(), MIN2, TextMarker::prev, TextMarker::start, and txt_get_span().
Referenced by text_find_and_replace().
int txt_add_raw_char (Text * text, unsigned int add)
Definition at line 2751 of file text.c.
References txt_add_char_intern().
Referenced by txt_insert_buf().
void txt_backspace_char (Text * text)
Definition at line 2609 of file text.c.
References BLI_freelinkN(), BLI_str_prev_char_utf8(), BLI_str_utf8_as_unicode_and_size(), Text::curc, Text::curl, TextMarker::end, TextMarker::flags, TextMarker::group, TextLine::len, TextLine::line, TextMarker::lineno, Text::markers, TextMarker::next, TextLine::next, TextLine::prev, TextMarker::start, TMARK_EDITALL, TMARK_TEMP, txt_clean_text(), txt_clear_markers(), txt_combine_lines(), txt_delete_sel(), txt_find_marker_region(), txt_has_sel(), txt_make_dirty(), txt_pop_sel(), txt_undo_add_charop(), UNDO_BS_1, and undoing.
Referenced by do_textmarkers(), text_delete_exec(), txt_do_redo(), and txt_do_undo().
void txt_backspace_word (Text * text)
Definition at line 2672 of file text.c.
References txt_delete_sel(), and txt_jump_left().
Referenced by text_delete_exec().
void txt_clean_text (Text * text)
Definition at line 669 of file text.c.
References Text::curc, Text::curl, ListBase::first, ListBase::last, Text::lines, TextLine::next, NULL, TextLine::prev, Text::selc, Text::sell, and txt_new_line().
Referenced by draw_text_main(), txt_add_char_intern(), txt_backspace_char(), txt_combine_lines(), txt_comment(), txt_delete_char(), txt_delete_line(), txt_indent(), txt_replace_char(), txt_split_curline(), txt_uncomment(), and txt_unindent().
short txt_clear_marker_region (Text * text, TextLine * line, int start, int end, int group, int flags)
Definition at line 3157 of file text.c.
References BLI_freelinkN(), TextMarker::end, ListBase::first, TextMarker::flags, TextMarker::group, TextMarker::lineno, Text::lines, Text::markers, TextMarker::next, next, TextMarker::start, and txt_get_span().
Referenced by txt_delete_sel().
short txt_clear_markers (Text * text, int group, int flags)
Definition at line 3183 of file text.c.
References BLI_freelinkN(), ListBase::first, TextMarker::flags, TextMarker::group, Text::markers, TextMarker::next, and next.
Referenced by do_textmarkers(), text_clear_all_markers_exec(), text_find_and_replace(), txt_backspace_char(), and txt_delete_char().
static void txt_combine_lines (Text * text, TextLine * linea, TextLine * lineb) [static]
Definition at line 2511 of file text.c.
References TextMarker::end, ListBase::first, TextLine::len, TextLine::line, TextMarker::lineno, Text::lines, make_new_line(), MEM_mallocN(), TextMarker::next, NULL, TextMarker::start, txt_clean_text(), txt_delete_line(), txt_find_marker_region(), txt_get_span(), and txt_make_dirty().
Referenced by txt_backspace_char(), and txt_delete_char().
void txt_comment (Text * text)
Definition at line 2936 of file text.c.
References add(), Text::curc, Text::curl, ListBase::first, TextLine::len, len(), TextLine::line, Text::lines, make_new_line(), MEM_mallocN(), TextLine::next, TextLine::prev, Text::selc, Text::sell, TRUE, txt_clean_text(), txt_get_span(), txt_make_dirty(), txt_undo_add_toop(), UNDO_COMMENT, and undoing.
Referenced by text_comment_exec(), txt_do_redo(), and txt_do_undo().
static void txt_convert_tab_to_spaces (Text * text) [static]
Definition at line 2683 of file text.c.
References Text::curc, tab_to_spaces, txt_insert_buf(), and TXT_TABSIZE.
Referenced by txt_add_char_intern().
static void txt_curs_cur (Text * text, TextLine *** linep, int ** charp) [static]
Definition at line 742 of file text.c.
References Text::curc, and Text::curl.
Referenced by txt_jump_left(), txt_jump_right(), txt_move_bof(), txt_move_bol(), txt_move_down(), txt_move_eof(), txt_move_eol(), txt_move_left(), txt_move_right(), txt_move_to(), and txt_move_up().
static void txt_curs_first (Text * text, TextLine ** linep, int * charp) [static]
Definition at line 752 of file text.c.
References Text::curc, Text::curl, ListBase::first, Text::lines, Text::selc, Text::sell, and txt_get_span().
Referenced by txt_do_undo().
static void txt_curs_sel (Text * text, TextLine *** linep, int ** charp) [static]
Definition at line 747 of file text.c.
References Text::selc, and Text::sell.
Referenced by txt_jump_left(), txt_jump_right(), txt_move_bof(), txt_move_bol(), txt_move_down(), txt_move_eof(), txt_move_eol(), txt_move_left(), txt_move_right(), txt_move_to(), and txt_move_up().
static void txt_curs_swap (Text * text) [static]
Definition at line 1131 of file text.c.
References Text::curc, Text::curl, Text::selc, Text::sell, txt_undo_add_op(), UNDO_SWAP, and undoing.
Referenced by txt_do_redo(), txt_do_undo(), txt_order_cursors(), txt_pop_first(), and txt_pop_last().
void txt_delete_char (Text * text)
Definition at line 2546 of file text.c.
References BLI_freelinkN(), BLI_str_utf8_as_unicode_and_size(), Text::curc, Text::curl, TextMarker::end, TextMarker::flags, TextMarker::group, TextLine::len, TextLine::line, TextMarker::lineno, Text::markers, TextMarker::next, TextLine::next, TextMarker::start, TMARK_EDITALL, TMARK_TEMP, txt_clean_text(), txt_clear_markers(), txt_combine_lines(), txt_delete_sel(), txt_find_marker_region(), txt_has_sel(), txt_make_dirty(), txt_pop_sel(), txt_undo_add_charop(), UNDO_DEL_1, and undoing.
Referenced by do_textmarkers(), text_delete_exec(), and txt_do_redo().
static void txt_delete_line (Text * text, TextLine * line) [static]
Definition at line 2481 of file text.c.
References BLI_freelinkN(), BLI_remlink(), Text::curl, ListBase::first, TextLine::format, TextLine::line, TextMarker::lineno, Text::lines, Text::markers, MEM_freeN(), TextMarker::next, NULL, txt_clean_text(), txt_get_span(), and txt_make_dirty().
Referenced by txt_combine_lines(), and txt_delete_sel().
static void txt_delete_sel (Text * text) [static]
Definition at line 1206 of file text.c.
References Text::curc, Text::curl, TextMarker::end, TextLine::len, TextLine::line, TextMarker::lineno, make_new_line(), MEM_freeN(), MEM_mallocN(), TextLine::next, TextMarker::next, TextLine::prev, Text::selc, Text::sell, TextMarker::start, txt_clear_marker_region(), txt_delete_line(), txt_find_marker_region(), txt_get_span(), txt_has_sel(), txt_order_cursors(), txt_sel_to_buf(), txt_undo_add_block(), UNDO_DBLOCK, and undoing.
Referenced by clear_text(), txt_add_char_intern(), txt_backspace_char(), txt_backspace_word(), txt_delete_char(), txt_delete_selected(), txt_delete_word(), txt_do_redo(), txt_do_undo(), txt_insert_buf(), and txt_split_curline().
void txt_delete_selected (Text * text)
Definition at line 2756 of file text.c.
References txt_delete_sel(), and txt_make_dirty().
Referenced by text_cut_exec().
void txt_delete_word (Text * text)
Definition at line 2603 of file text.c.
References txt_delete_sel(), and txt_jump_right().
Referenced by text_delete_exec().
void txt_do_redo (Text * text)
Definition at line 2231 of file text.c.
References Text::curc, Text::curl, ListBase::first, i, Text::lines, MEM_freeN(), MEM_mallocN(), TextLine::next, Text::selc, Text::sell, txt_add_char(), txt_backspace_char(), txt_comment(), txt_curs_swap(), txt_delete_char(), txt_delete_sel(), txt_do_redo(), txt_indent(), txt_insert_buf(), txt_move_down(), txt_move_left(), txt_move_right(), txt_move_toline(), txt_move_up(), txt_pop_sel(), txt_redo_read_uint16(), txt_redo_read_uint32(), txt_redo_read_unicode(), txt_uncomment(), txt_unindent(), UNDO_BS_1, UNDO_BS_2, UNDO_BS_3, UNDO_BS_4, Text::undo_buf, UNDO_CDOWN, UNDO_CLEFT, UNDO_COMMENT, UNDO_CRIGHT, UNDO_CTO, UNDO_CUP, UNDO_DBLOCK, UNDO_DEL_1, UNDO_DEL_2, UNDO_DEL_3, UNDO_DEL_4, UNDO_IBLOCK, UNDO_INDENT, UNDO_INSERT_1, UNDO_INSERT_2, UNDO_INSERT_3, UNDO_INSERT_4, Text::undo_pos, UNDO_SDOWN, UNDO_SLEFT, UNDO_SRIGHT, UNDO_STO, UNDO_SUP, UNDO_SWAP, UNDO_UNCOMMENT, UNDO_UNINDENT, and undoing.
Referenced by ED_text_undo_step(), txt_do_redo(), and txt_do_undo().
void txt_do_undo (Text * text)
Definition at line 2004 of file text.c.
References Text::curc, Text::curl, ListBase::first, i, Text::lines, MEM_freeN(), MEM_mallocN(), TextLine::next, Text::selc, Text::sell, txt_add_char(), txt_backspace_char(), txt_comment(), txt_curs_first(), txt_curs_swap(), txt_delete_sel(), txt_do_redo(), txt_do_undo(), txt_get_span(), txt_indent(), txt_insert_buf(), txt_move_down(), txt_move_left(), txt_move_right(), txt_move_toline(), txt_move_up(), txt_pop_sel(), txt_uncomment(), txt_undo_read_uint16(), txt_undo_read_uint32(), txt_undo_read_unicode(), txt_unindent(), txt_utf8_len(), UNDO_BS_1, UNDO_BS_2, UNDO_BS_3, UNDO_BS_4, Text::undo_buf, UNDO_CDOWN, UNDO_CLEFT, UNDO_COMMENT, UNDO_CRIGHT, UNDO_CTO, UNDO_CUP, UNDO_DBLOCK, UNDO_DEL_1, UNDO_DEL_2, UNDO_DEL_3, UNDO_DEL_4, UNDO_IBLOCK, UNDO_INDENT, UNDO_INSERT_1, UNDO_INSERT_2, UNDO_INSERT_3, UNDO_INSERT_4, Text::undo_pos, UNDO_SDOWN, UNDO_SLEFT, UNDO_SRIGHT, UNDO_STO, UNDO_SUP, UNDO_SWAP, UNDO_UNCOMMENT, UNDO_UNINDENT, and undoing.
Referenced by ED_text_undo_step(), and txt_do_undo().
int txt_extended_ascii_as_utf8 (char ** str)
Definition at line 226 of file text.c.
References BLI_str_utf8_from_unicode(), BLI_utf8_invalid_byte(), i, length(), MEM_freeN(), MEM_mallocN(), and strlen().
Referenced by cleanup_textline(), do_versions(), and txt_insert_buf().
TextMarker* txt_find_marker (Text * text, TextLine * line, int curs, int group, int flags) [read]
Definition at line 3202 of file text.c.
References ListBase::first, TextMarker::flags, TextMarker::group, TextMarker::lineno, Text::lines, Text::markers, TextMarker::next, NULL, TextMarker::start, and txt_get_span().
Referenced by do_textmarkers(), text_find_and_replace(), and txt_replace_char().
TextMarker* txt_find_marker_region (Text * text, TextLine * line, int start, int end, int group, int flags) [read]
Definition at line 3134 of file text.c.
References TextMarker::end, ListBase::first, TextMarker::flags, TextMarker::group, TextMarker::lineno, Text::lines, Text::markers, TextMarker::next, next, NULL, TextMarker::start, and txt_get_span().
Referenced by txt_add_char_intern(), txt_backspace_char(), txt_combine_lines(), txt_delete_char(), and txt_delete_sel().
int txt_find_string (Text * text, const char * findstr, int wrap, int match_case)
Definition at line 1358 of file text.c.
References BLI_strcasestr(), Text::curl, ListBase::first, TextLine::line, Text::lines, TextLine::next, NULL, Text::selc, Text::sell, strlen(), txt_get_span(), txt_move_to(), and txt_order_cursors().
Referenced by text_find_and_replace().
int txt_get_span (TextLine * from, TextLine * to)
Definition at line 700 of file text.c.
References TextLine::next, and TextLine::prev.
Referenced by cursor_skip(), do_textmarkers(), draw_brackets(), draw_cursor(), draw_markers(), text_cursor_set_exec(), text_cursor_set_exit(), text_cursor_set_to_pos(), text_get_span_wrap(), text_jump_exec(), text_next_marker_exec(), text_previous_marker_exec(), text_scroll_to_cursor(), text_set_selection_invoke(), txt_add_marker(), txt_clear_marker_region(), txt_combine_lines(), txt_comment(), txt_copy_selected(), txt_curs_first(), txt_delete_line(), txt_delete_sel(), txt_do_undo(), txt_find_marker(), txt_find_marker_region(), txt_find_string(), txt_indent(), txt_insert_buf(), txt_jump_left(), txt_jump_right(), txt_move_bof(), txt_move_bol(), txt_move_eof(), txt_move_eol(), txt_move_to(), txt_order_cursors(), txt_pop_first(), txt_pop_last(), txt_sel_to_buf(), txt_split_curline(), txt_uncomment(), txt_unindent(), txt_wrap_move_bol(), txt_wrap_move_down(), txt_wrap_move_eol(), and txt_wrap_move_up().
int txt_get_undostate (void)
Definition at line 151 of file text.c.
References undoing.
Referenced by clear_text(), and write_text().
int txt_has_sel (Text * text)
Definition at line 1201 of file text.c.
References Text::curc, Text::curl, Text::selc, and Text::sell.
Referenced by console_cursor_set_exit(), text_comment_exec(), text_cursor_set_exit(), text_find_and_replace(), text_indent_exec(), text_uncomment_exec(), text_unindent_exec(), txt_backspace_char(), txt_copy_selected(), txt_delete_char(), txt_delete_sel(), and txt_replace_char().
void txt_indent (Text * text)
Definition at line 2809 of file text.c.
References add(), Text::curc, Text::curl, ELEM3, ListBase::first, Text::flags, TextLine::len, len(), TextLine::line, Text::lines, make_new_line(), MEM_mallocN(), TextLine::next, NULL, TextLine::prev, Text::selc, Text::sell, tab_to_spaces, TRUE, txt_clean_text(), txt_get_span(), txt_make_dirty(), TXT_TABSIZE, TXT_TABSTOSPACES, txt_undo_add_toop(), UNDO_INDENT, and undoing.
Referenced by text_indent_exec(), txt_do_redo(), and txt_do_undo().
void txt_insert_buf (Text * text, const char * in_buffer)
Definition at line 1488 of file text.c.
References add(), BLI_insertlinkbefore(), BLI_str_utf8_as_unicode_step(), BLI_strdupn(), Text::curl, ListBase::first, i, len(), Text::lines, MEM_freeN(), strlen(), txt_add_raw_char(), txt_delete_sel(), txt_extended_ascii_as_utf8(), txt_get_span(), txt_new_linen(), txt_shift_markers(), txt_split_curline(), txt_undo_add_block(), UNDO_IBLOCK, and undoing.
Referenced by confirm_suggestion(), text_find_and_replace(), text_paste_exec(), txt_convert_tab_to_spaces(), txt_do_redo(), txt_do_undo(), and write_text().
void txt_jump_left (Text * text, short sel)
Definition at line 957 of file text.c.
References BLI_str_cursor_step_utf8(), ListBase::first, Text::flags, i, Text::lines, STRCUR_DIR_PREV, STRCUR_JUMP_DELIM, txt_curs_cur(), txt_curs_sel(), txt_get_span(), txt_move_left(), txt_pop_first(), TXT_TABSTOSPACES, txt_undo_add_toop(), UNDO_CTO, UNDO_STO, and undoing.
Referenced by text_move_cursor(), text_select_word_exec(), and txt_backspace_word().
void txt_jump_right (Text * text, short sel)
Definition at line 991 of file text.c.
References BLI_str_cursor_step_utf8(), ListBase::first, Text::flags, i, Text::lines, STRCUR_DIR_NEXT, STRCUR_JUMP_DELIM, txt_curs_cur(), txt_curs_sel(), txt_get_span(), txt_move_right(), txt_pop_last(), TXT_TABSTOSPACES, txt_undo_add_toop(), UNDO_CTO, UNDO_STO, and undoing.
Referenced by text_move_cursor(), text_select_word_exec(), and txt_delete_word().
static void txt_make_dirty (Text * text) [static]
Definition at line 730 of file text.c.
References BPY_text_free_code(), Text::compiled, Text::flags, and TXT_ISDIRTY.
Referenced by clear_text(), txt_add_char_intern(), txt_backspace_char(), txt_combine_lines(), txt_comment(), txt_delete_char(), txt_delete_line(), txt_delete_selected(), txt_indent(), txt_replace_char(), txt_split_curline(), txt_uncomment(), txt_unindent(), and write_text().
void txt_move_bof (Text * text, short sel)
Definition at line 1059 of file text.c.
References ListBase::first, Text::lines, txt_curs_cur(), txt_curs_sel(), txt_get_span(), txt_pop_sel(), txt_undo_add_toop(), UNDO_CTO, UNDO_STO, and undoing.
Referenced by text_move_cursor().
void txt_move_bol (Text * text, short sel)
Definition at line 1025 of file text.c.
References ListBase::first, Text::lines, txt_curs_cur(), txt_curs_sel(), txt_get_span(), txt_pop_sel(), txt_undo_add_toop(), UNDO_CTO, UNDO_STO, and undoing.
Referenced by text_move_cursor(), and txt_move_up().
void txt_move_down (Text * text, short sel)
Definition at line 834 of file text.c.
References TextLine::len, TextLine::next, txt_curs_cur(), txt_curs_sel(), txt_move_eol(), txt_pop_last(), txt_pop_sel(), txt_undo_add_op(), txt_utf8_index_to_offset(), txt_utf8_len(), txt_utf8_offset_to_index(), UNDO_CDOWN, UNDO_SDOWN, and undoing.
Referenced by text_move_cursor(), txt_do_redo(), txt_do_undo(), and txt_move_right().
void txt_move_eof (Text * text, short sel)
Definition at line 1077 of file text.c.
References ListBase::first, ListBase::last, Text::lines, txt_curs_cur(), txt_curs_sel(), txt_get_span(), txt_pop_sel(), txt_undo_add_toop(), UNDO_CTO, UNDO_STO, and undoing.
Referenced by text_move_cursor(), and write_text().
void txt_move_eol (Text * text, short sel)
Definition at line 1042 of file text.c.
References ListBase::first, Text::lines, txt_curs_cur(), txt_curs_sel(), txt_get_span(), txt_pop_sel(), txt_undo_add_toop(), UNDO_CTO, UNDO_STO, and undoing.
Referenced by text_move_cursor(), and txt_move_down().
void txt_move_left (Text * text, short sel)
Definition at line 862 of file text.c.
References BLI_str_prev_char_utf8(), Text::flags, i, txt_curs_cur(), txt_curs_sel(), txt_move_up(), txt_pop_first(), txt_pop_sel(), TXT_TABSIZE, TXT_TABSTOSPACES, txt_undo_add_op(), UNDO_CLEFT, UNDO_SLEFT, and undoing.
Referenced by confirm_suggestion(), text_move_cursor(), txt_do_redo(), txt_do_undo(), and txt_jump_left().
void txt_move_right (Text * text, short sel)
Definition at line 912 of file text.c.
References BLI_str_utf8_size(), Text::flags, i, txt_curs_cur(), txt_curs_sel(), txt_move_down(), txt_pop_last(), txt_pop_sel(), TXT_TABSIZE, TXT_TABSTOSPACES, txt_undo_add_op(), UNDO_CRIGHT, UNDO_SRIGHT, and undoing.
Referenced by confirm_suggestion(), text_move_cursor(), txt_do_redo(), txt_do_undo(), and txt_jump_right().
void txt_move_to (Text * text, unsigned int line, unsigned int ch, short sel)
Definition at line 1101 of file text.c.
References ListBase::first, i, Text::lines, TextLine::next, txt_curs_cur(), txt_curs_sel(), txt_get_span(), txt_pop_sel(), txt_undo_add_toop(), UNDO_CTO, UNDO_STO, and undoing.
Referenced by do_textmarkers(), python_script_error_jump_text(), text_next_marker_exec(), text_previous_marker_exec(), txt_find_string(), and txt_move_toline().
void txt_move_toline (Text * text, unsigned int line, short sel)
Definition at line 1095 of file text.c.
References txt_move_to().
Referenced by text_find_and_replace(), text_jump_exec(), text_line_number_invoke(), txt_do_redo(), and txt_do_undo().
void txt_move_up (Text * text, short sel)
Definition at line 806 of file text.c.
References TextLine::len, TextLine::prev, txt_curs_cur(), txt_curs_sel(), txt_move_bol(), txt_pop_first(), txt_pop_sel(), txt_undo_add_op(), txt_utf8_index_to_offset(), txt_utf8_len(), txt_utf8_offset_to_index(), UNDO_CUP, UNDO_SUP, and undoing.
Referenced by text_move_cursor(), txt_do_redo(), txt_do_undo(), and txt_move_left().
static TextLine* txt_new_line (const char * str) [static]
Definition at line 635 of file text.c.
References TextLine::format, TextLine::len, TextLine::line, MEM_mallocN(), TextLine::next, NULL, TextLine::prev, and strlen().
Referenced by txt_clean_text().
static TextLine* txt_new_linen (const char * str, int n) [static]
Definition at line 653 of file text.c.
References BLI_strncpy(), TextLine::format, TextLine::len, TextLine::line, MEM_mallocN(), TextLine::next, NULL, TextLine::prev, and strlen().
Referenced by txt_insert_buf().
TextMarker* txt_next_marker (Text * text, TextMarker * marker) [read]
Definition at line 3235 of file text.c.
References ListBase::first, TextMarker::group, Text::markers, TextMarker::next, and NULL.
Referenced by do_textmarkers().
void txt_order_cursors (Text * text)
Definition at line 1189 of file text.c.
References Text::curc, Text::curl, Text::selc, Text::sell, txt_curs_swap(), and txt_get_span().
Referenced by text_comment_exec(), text_indent_exec(), text_uncomment_exec(), text_unindent_exec(), txt_delete_sel(), and txt_find_string().
static void txt_pop_first (Text * text) [static]
Definition at line 1147 of file text.c.
References Text::curc, Text::curl, ListBase::first, Text::lines, Text::selc, Text::sell, txt_curs_swap(), txt_get_span(), txt_pop_sel(), txt_undo_add_toop(), UNDO_STO, and undoing.
Referenced by txt_jump_left(), txt_move_left(), and txt_move_up().
static void txt_pop_last (Text * text) [static]
Definition at line 1164 of file text.c.
References Text::curc, Text::curl, ListBase::first, Text::lines, Text::selc, Text::sell, txt_curs_swap(), txt_get_span(), txt_pop_sel(), txt_undo_add_toop(), UNDO_STO, and undoing.
Referenced by txt_jump_right(), txt_move_down(), and txt_move_right().
void txt_pop_sel (Text * text)
Definition at line 1183 of file text.c.
References Text::curc, Text::curl, Text::selc, and Text::sell.
Referenced by cursor_skip(), text_cursor_set_to_pos(), txt_add_char_intern(), txt_backspace_char(), txt_delete_char(), txt_do_redo(), txt_do_undo(), txt_move_bof(), txt_move_bol(), txt_move_down(), txt_move_eof(), txt_move_eol(), txt_move_left(), txt_move_right(), txt_move_to(), txt_move_up(), txt_pop_first(), txt_pop_last(), txt_replace_char(), txt_split_curline(), txt_wrap_move_bol(), txt_wrap_move_down(), txt_wrap_move_eol(), and txt_wrap_move_up().
TextMarker* txt_prev_marker (Text * text, TextMarker * marker) [read]
Definition at line 3221 of file text.c.
References TextMarker::group, ListBase::last, Text::markers, NULL, and TextMarker::prev.
void txt_print_undo (Text * text)
Definition at line 1586 of file text.c.
References BLI_str_utf8_from_unicode(), BLI_UTF8_MAX, dump_buffer(), i, UNDO_BS_1, UNDO_BS_2, UNDO_BS_3, UNDO_BS_4, Text::undo_buf, UNDO_CDOWN, UNDO_CLEFT, UNDO_COMMENT, UNDO_CRIGHT, UNDO_CTO, UNDO_CUP, UNDO_DBLOCK, UNDO_DEL_1, UNDO_DEL_2, UNDO_DEL_3, UNDO_DEL_4, UNDO_IBLOCK, UNDO_INDENT, UNDO_INSERT_1, UNDO_INSERT_2, UNDO_INSERT_3, UNDO_INSERT_4, Text::undo_pos, UNDO_SDOWN, UNDO_SLEFT, UNDO_SRIGHT, UNDO_STO, UNDO_SUP, UNDO_SWAP, UNDO_UNCOMMENT, and UNDO_UNINDENT.
static unsigned short txt_redo_read_uint16 (const char * undo_buf, int * undo_pos) [static]
Definition at line 1953 of file text.c.
Referenced by txt_do_redo().
static unsigned int txt_redo_read_uint32 (const char * undo_buf, int * undo_pos) [static]
Definition at line 1961 of file text.c.
Referenced by txt_do_redo().
static unsigned int txt_redo_read_unicode (const char * undo_buf, int * undo_pos, short bytes) [static]
Definition at line 1971 of file text.c.
References BLI_assert, BLI_str_utf8_as_unicode(), BLI_UTF8_MAX, and txt_undo_read_uint32().
Referenced by txt_do_redo().
int txt_replace_char (Text * text, unsigned int add)
Definition at line 2762 of file text.c.
References BLI_freelinkN(), BLI_str_utf8_as_unicode_and_size(), BLI_str_utf8_from_unicode(), BLI_UTF8_MAX, Text::curc, Text::curl, i, TextLine::len, TextLine::line, Text::markers, MEM_freeN(), MEM_mallocN(), txt_add_char(), txt_clean_text(), txt_find_marker(), txt_has_sel(), txt_make_dirty(), txt_pop_sel(), txt_undo_add_charop(), UNDO_DEL_1, UNDO_INSERT_1, and undoing.
Referenced by do_textmarkers(), do_texttools(), and text_insert_exec().
void txt_sel_all (Text * text)
Definition at line 1269 of file text.c.
References Text::curc, Text::curl, ListBase::first, ListBase::last, TextLine::len, Text::lines, Text::selc, and Text::sell.
Referenced by clear_text(), and text_select_all_exec().
void txt_sel_line (Text * text)
Definition at line 1280 of file text.c.
References Text::curc, Text::curl, TextLine::len, Text::selc, and Text::sell.
Referenced by text_select_line_exec().
char* txt_sel_to_buf (Text * text)
Definition at line 1397 of file text.c.
References BLI_strncpy(), Text::curc, Text::curl, TextLine::len, length(), TextLine::line, MEM_mallocN(), TextLine::next, NULL, Text::selc, Text::sell, and txt_get_span().
Referenced by console_cursor_set_exit(), text_cursor_set_exit(), text_find_and_replace(), text_find_set_selected_exec(), text_replace_set_selected_exec(), and txt_delete_sel().
void txt_set_undostate (int u)
Definition at line 146 of file text.c.
References undoing.
Referenced by clear_text(), and write_text().
static void txt_shift_markers (Text * text, int lineno, int count) [static]
Definition at line 1478 of file text.c.
References ListBase::first, TextMarker::lineno, Text::markers, and TextMarker::next.
Referenced by txt_insert_buf().
void txt_split_curline (Text * text)
Definition at line 2419 of file text.c.
References BLI_insertlinkbefore(), Text::curc, Text::curl, TextMarker::end, ListBase::first, TextLine::format, left(), TextLine::len, TextLine::line, TextMarker::lineno, Text::lines, Text::markers, MEM_freeN(), MEM_mallocN(), TextMarker::next, NULL, TextMarker::start, txt_clean_text(), txt_delete_sel(), txt_get_span(), txt_make_dirty(), txt_pop_sel(), txt_undo_add_charop(), UNDO_INSERT_1, and undoing.
Referenced by text_line_break_exec(), txt_add_char_intern(), and txt_insert_buf().
char* txt_to_buf (Text * text)
Definition at line 1294 of file text.c.
References BLI_strncpy(), Text::curl, ListBase::first, ListBase::last, TextLine::len, length(), TextLine::line, Text::lines, MEM_mallocN(), TextLine::next, NULL, and Text::sell.
Referenced by BL_ConvertActuators(), BL_ConvertControllers(), bpy_text_import(), bpy_text_reimport(), KX_Dome::KX_Dome(), and python_script_exec().
void txt_uncomment (Text * text)
Definition at line 2989 of file text.c.
References Text::curc, Text::curl, ListBase::first, i, TextLine::len, TextLine::line, Text::lines, TextLine::next, TextLine::prev, Text::selc, Text::sell, TRUE, txt_clean_text(), txt_get_span(), txt_make_dirty(), txt_undo_add_toop(), UNDO_UNCOMMENT, and undoing.
Referenced by text_uncomment_exec(), txt_do_redo(), and txt_do_undo().
static void txt_undo_add_block (Text * text, int op, const char * buf) [static]
Definition at line 1827 of file text.c.
References length(), max_undo_test(), strlen(), txt_undo_store_uint32(), Text::undo_buf, and Text::undo_pos.
Referenced by txt_delete_sel(), and txt_insert_buf().
static void txt_undo_add_charop (Text * text, int op_start, unsigned int c) [static]
Definition at line 1871 of file text.c.
References BLI_str_utf8_from_unicode(), BLI_UTF8_MAX, i, max_undo_test(), txt_undo_store_uint32(), Text::undo_buf, and Text::undo_pos.
Referenced by txt_add_char_intern(), txt_backspace_char(), txt_delete_char(), txt_replace_char(), and txt_split_curline().
static void txt_undo_add_op (Text * text, int op) [static]
Definition at line 1797 of file text.c.
References max_undo_test(), Text::undo_buf, and Text::undo_pos.
Referenced by txt_curs_swap(), txt_move_down(), txt_move_left(), txt_move_right(), and txt_move_up().
void txt_undo_add_toop (Text * text, int op, unsigned int froml, unsigned short fromc, unsigned int tol, unsigned short toc)
Definition at line 1849 of file text.c.
References max_undo_test(), txt_undo_store_uint16(), txt_undo_store_uint32(), Text::undo_buf, and Text::undo_pos.
Referenced by cursor_skip(), text_cursor_set_exec(), text_cursor_set_exit(), txt_comment(), txt_indent(), txt_jump_left(), txt_jump_right(), txt_move_bof(), txt_move_bol(), txt_move_eof(), txt_move_eol(), txt_move_to(), txt_pop_first(), txt_pop_last(), txt_uncomment(), txt_unindent(), txt_wrap_move_bol(), txt_wrap_move_down(), txt_wrap_move_eol(), and txt_wrap_move_up().
static unsigned short txt_undo_read_uint16 (const char * undo_buf, int * undo_pos) [static]
Definition at line 1902 of file text.c.
Referenced by txt_do_undo().
static unsigned int txt_undo_read_uint32 (const char * undo_buf, int * undo_pos) [static]
Definition at line 1910 of file text.c.
Referenced by txt_do_undo(), txt_redo_read_unicode(), and txt_undo_read_unicode().
static unsigned int txt_undo_read_unicode (const char * undo_buf, int * undo_pos, short bytes) [static]
Definition at line 1920 of file text.c.
References BLI_assert, BLI_str_utf8_as_unicode(), BLI_UTF8_MAX, and txt_undo_read_uint32().
Referenced by txt_do_undo().
static void txt_undo_store_uint16 (char * undo_buf, int * undo_pos, unsigned short value) [static]
Definition at line 1807 of file text.c.
Referenced by txt_undo_add_toop().
static void txt_undo_store_uint32 (char * undo_buf, int * undo_pos, unsigned int value) [static]
Definition at line 1815 of file text.c.
Referenced by txt_undo_add_block(), txt_undo_add_charop(), and txt_undo_add_toop().
void txt_unindent (Text * text)
Definition at line 2877 of file text.c.
References BLI_strncasecmp(), Text::curc, Text::curl, ListBase::first, Text::flags, i, TextLine::len, TextLine::line, Text::lines, TextLine::next, TextLine::prev, Text::selc, Text::sell, tab_to_spaces, TRUE, txt_clean_text(), txt_get_span(), txt_make_dirty(), TXT_TABSIZE, TXT_TABSTOSPACES, txt_undo_add_toop(), UNDO_UNINDENT, and undoing.
Referenced by text_unindent_exec(), txt_do_redo(), and txt_do_undo().
int txt_utf8_index_to_offset (const char * str, int index)
Definition at line 783 of file text.c.
References BLI_str_utf8_size().
Referenced by txt_move_down(), txt_move_up(), and txt_wrap_move_bol().
static int txt_utf8_len (const char * src) [static]
Definition at line 795 of file text.c.
References BLI_str_utf8_size(), and len().
Referenced by txt_do_undo(), txt_move_down(), and txt_move_up().
int txt_utf8_offset_to_index (const char * str, int offset)
Definition at line 773 of file text.c.
References BLI_str_utf8_size().
Referenced by draw_brackets(), txt_move_down(), txt_move_up(), wrap_offset(), and wrap_offset_in_line().
void unlink_text (Main * bmain, Text * text)
Definition at line 524 of file text.c.
References bScreen::areabase, bPose::chanbase, CONSTRAINT_TYPE_PYTHON, Object::constraints, bPoseChannel::constraints, CONT_PYTHON, Object::controllers, DAG_id_tag_update(), bConstraint::data, data, bController::data, ListBase::first, Text::id, bScreen::id, Object::id, SpaceLink::next, ScrArea::next, bConstraint::next, bPoseChannel::next, bController::next, ID::next, NULL, OB_ARMATURE, OB_RECALC_DATA, Main::object, Object::pose, Main::screen, SPACE_TEXT, ScrArea::spacedata, SpaceLink::spacetype, SpaceText::text, bPythonConstraint::text, bPythonCont::text, SpaceText::top, bConstraint::type, Object::type, bController::type, update(), and ID::us.
Referenced by id_unlink(), and text_unlink_exec().
void write_text (Text * text, const char * str)
Definition at line 609 of file text.c.
References txt_get_undostate(), txt_insert_buf(), txt_make_dirty(), txt_move_eof(), and txt_set_undostate().
Referenced by reports_to_text_exec().
Variable Documentation
char tab_to_spaces[] = " " [static]
Definition at line 2681 of file text.c.
Referenced by txt_convert_tab_to_spaces(), txt_indent(), and txt_unindent().
unsigned char undoing [static]
Definition at line 143 of file text.c.
Referenced by txt_add_char_intern(), txt_backspace_char(), txt_comment(), txt_curs_swap(), txt_delete_char(), txt_delete_sel(), txt_do_redo(), txt_do_undo(), txt_get_undostate(), txt_indent(), txt_insert_buf(), txt_jump_left(), txt_jump_right(), txt_move_bof(), txt_move_bol(), txt_move_down(), txt_move_eof(), txt_move_eol(), txt_move_left(), txt_move_right(), txt_move_to(), txt_move_up(), txt_pop_first(), txt_pop_last(), txt_replace_char(), txt_set_undostate(), txt_split_curline(), txt_uncomment(), and txt_unindent().