Blender: solver_interface.cpp File Reference
solver_interface.cpp File Reference
elbeem
#include "ntl_matrices.h"
#include "solver_interface.h"
#include "ntl_ray.h"
#include "ntl_world.h"
#include "elbeem.h"
Functions
void initGridSizes (int &sizex, int &sizey, int &sizez, ntlVec3Gfx &geoStart, ntlVec3Gfx &geoEnd, int mMaxRefine, bool parallel)
void calculateMemreqEstimate (int resx, int resy, int resz, int refine, float farfield, double *reqret, double *reqretFine, string *reqstr)
string convertSingleFlag2String (CellFlagType cflag)
string convertCellFlagType2String (CellFlagType cflag)
helper function to convert flag to string (for debuggin)
Variables
int globGeoInitDebug = 0
int globGICPIProblems = 0
Detailed Description
Definition in file solver_interface.cpp.
Function Documentation
void calculateMemreqEstimate (int resx, int resy, int resz, int refine, float farfield, double * reqret, double * reqretFine, string * reqstr)
Definition at line 145 of file solver_interface.cpp.
References CellFlagType, debMsgStd, DM_MSG, dTotalNum, i, and PRINT_VEC.
Referenced by elbeemEstimateMemreq(), and LbmFsgrSolver::initializeSolverMemory().
string convertCellFlagType2String (CellFlagType cflag)
helper function to convert flag to string (for debuggin)
Definition at line 722 of file solver_interface.cpp.
References CellFlagType, and convertSingleFlag2String().
Referenced by LbmFsgrSolver::debugPrintNodeInfo(), SimulationObject::initializeLbmSimulation(), and LbmFsgrSolver::reinitFlags().
string convertSingleFlag2String (CellFlagType cflag)
string helper functions
Definition at line 680 of file solver_interface.cpp.
References CellFlagType, CFBnd, CFBndFreeslip, CFBndNoslip, CFBndPartslip, CFEmpty, CFFluid, CFGrCoarseInited, CFGrFromCoarse, CFGrFromFine, CFGrNorm, CFInter, CFInvalid, CFMbndInflow, CFMbndOutflow, CFNoBndFluid, CFNoDelete, CFNoInterpolSrc, CFNoNbEmpty, CFNoNbFluid, and CFUnused.
Referenced by convertCellFlagType2String().
void initGridSizes (int & sizex, int & sizey, int & sizez, ntlVec3Gfx & geoStart, ntlVec3Gfx & geoEnd, int mMaxRefine, bool parallel)
Definition at line 97 of file solver_interface.cpp.
References convertFlags2String(), debMsgStd, DM_MSG, i, and PRINT_VEC.
Referenced by elbeemEstimateMemreq(), and LbmFsgrSolver::initializeSolverMemory().
Variable Documentation
int globGeoInitDebug = 0
perform geometry init (if switched on)
Definition at line 344 of file solver_interface.cpp.
Referenced by ControlParticles::checkPointInside(), and LbmSolverInterface::geoInitCheckPointInside().
int globGICPIProblems = 0
Definition at line 345 of file solver_interface.cpp.
Referenced by LbmSolverInterface::geoInitCheckPointInside().