Blender: wm_draw.h File Reference
wm_draw.h File Reference
windowmanager
Functions
void wm_draw_update (struct bContext *C)
void wm_draw_window_clear (struct wmWindow *win)
void wm_draw_region_clear (struct wmWindow *win, struct ARegion *ar)
void wm_tag_redraw_overlay (struct wmWindow *win, struct ARegion *ar)
Detailed Description
Definition in file wm_draw.h.
Function Documentation
void wm_draw_region_clear (struct wmWindow * win, struct ARegion * ar)
Definition at line 812 of file wm_draw.c.
References bScreen::do_draw, ELEM, wmWindow::screen, USER_DRAW_OVERLAP, USER_DRAW_OVERLAP_FLIP, ARegion::winrct, wm_automatic_draw_method(), and wm_flush_regions_down().
Referenced by ui_remove_temporary_region().
void wm_draw_update (struct bContext * C)
Definition at line 744 of file wm_draw.c.
References CTX_wm_manager(), CTX_wm_window_set(), bScreen::do_draw_drag, bScreen::do_draw_gesture, bScreen::do_draw_paintcursor, bScreen::do_refresh, wmWindow::drawfail, wmWindow::drawmethod, ED_screen_refresh(), ListBase::first, GPU_free_unused_buffers(), wmWindow::next, NULL, wmWindow::screen, USER_DRAW_FULL, USER_DRAW_OVERLAP, USER_DRAW_OVERLAP_FLIP, wmWindowManager::windows, wm_automatic_draw_method(), wm_draw_update_test_window(), wm_draw_window_clear(), wm_method_draw_full(), wm_method_draw_overlap_all(), wm_method_draw_triple(), wm_window_make_drawable(), and wm_window_swap_buffers().
Referenced by redraw_timer_exec(), redraw_timer_window_swap(), WM_main(), and WM_redraw_windows().
void wm_draw_window_clear (struct wmWindow * win)
Definition at line 792 of file wm_draw.c.
References bScreen::areabase, ListBase::first, ScrArea::next, ARegion::next, ScrArea::regionbase, wmWindow::screen, ARegion::swap, bScreen::swap, USER_DRAW_TRIPLE, WIN_NONE_OK, wm_automatic_draw_method(), and wm_draw_triple_free().
Referenced by ghost_event_proc(), wm_close_and_free(), wm_draw_triple_fail(), wm_draw_update(), and wm_window_close().
void wm_tag_redraw_overlay (struct wmWindow * win, struct ARegion * ar)
Definition at line 734 of file wm_draw.c.
References bScreen::do_draw_paintcursor, ED_region_tag_redraw(), wmWindow::screen, USER_DRAW_TRIPLE, and wm_automatic_draw_method().
Referenced by wm_draw_update_test_window(), wm_gesture_tag_redraw(), and wm_paintcursor_tag().