Blender: bpy_operator_wrap.h File Reference
bpy_operator_wrap.h File Reference
Python RNA and Operators
Functions
PyObject * PYOP_wrap_macro_define (PyObject *self, PyObject *args)
void operator_wrapper (struct wmOperatorType *ot, void *userdata)
void macro_wrapper (struct wmOperatorType *ot, void *userdata)
Detailed Description
Definition in file bpy_operator_wrap.h.
Function Documentation
void macro_wrapper (struct wmOperatorType * ot, void * userdata)
Definition at line 85 of file bpy_operator_wrap.c.
References data, wmOperatorType::description, wmOperatorType::ext, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, operator_properties_init(), wmOperatorType::pyop_poll, and wmOperatorType::ui.
void operator_wrapper (struct wmOperatorType * ot, void * userdata)
Definition at line 62 of file bpy_operator_wrap.c.
References NULL, operator_properties_init(), wmOperatorType::prop, RNA_pointer_create(), RNA_struct_find_property(), and wmOperatorType::srna.
PyObject* PYOP_wrap_macro_define (PyObject * self, PyObject * args)