Blender: BLI_dynstr.c File Reference
BLI_dynstr.c File Reference
blenlib
#include <stdarg.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_dynstr.h"
Classes
struct DynStrElem
struct DynStr
Defines
#define va_copy(a, b) ((a)=(b))
Typedefs
typedef struct DynStrElem DynStrElem
Functions
DynStr * BLI_dynstr_new (void)
void BLI_dynstr_append (DynStr *ds, const char *cstr)
void BLI_dynstr_nappend (DynStr *ds, const char *cstr, int len)
void BLI_dynstr_vappendf (DynStr *ds, const char *format, va_list args)
void BLI_dynstr_appendf (DynStr *ds, const char *format,...)
int BLI_dynstr_get_len (DynStr *ds)
void BLI_dynstr_get_cstring_ex (DynStr *ds, char *rets)
char * BLI_dynstr_get_cstring (DynStr *ds)
void BLI_dynstr_free (DynStr *ds)
Detailed Description
Definition in file BLI_dynstr.c.
Define Documentation
#define va_copy (a, b) ((a)=(b))
Definition at line 51 of file BLI_dynstr.c.
Referenced by BLI_dynstr_vappendf().
Typedef Documentation
typedef struct DynStrElem DynStrElem
Definition at line 57 of file BLI_dynstr.c.
Function Documentation
void BLI_dynstr_append (DynStr * ds, const char * cstr)
Append a c-string to a DynStr.
Parameters:
ds The DynStr to append to.
cstr The c-string to append.
Definition at line 80 of file BLI_dynstr.c.
References DynStr::curlen, DynStr::elems, DynStr::last, DynStrElem::next, NULL, DynStrElem::str, and strlen().
Referenced by BKE_reports_prepend(), BKE_reports_prependf(), BKE_undo_menu_string(), BLI_dynstr_appendf(), BLI_dynstr_vappendf(), BLI_replacestr(), code_generate_fragment(), code_generate_vertex(), codegen_call_functions(), codegen_convert_datatype(), codegen_declare_tmps(), codegen_print_datatype(), codegen_print_uniforms_functions(), console_copy_exec(), get_rna_access(), GPU_code_generate_glsl_lib(), IDnames_to_dyn_pupstring(), IDnames_to_pupstring(), Matrix_str(), report_copy_exec(), RNA_path_append(), rna_path_rename_fix(), RNA_pointer_as_string(), RNA_property_as_string(), ui_def_but_rna(), ui_intro_items(), Vector_str(), and WM_operator_pystring().
void BLI_dynstr_appendf (DynStr * ds, const char * format, ...)
Append a c-string to a DynStr, but with formatting like printf.
Parameters:
ds The DynStr to append to.
format The printf format string to use.
Definition at line 168 of file BLI_dynstr.c.
References BLI_dynstr_append(), len(), MEM_callocN(), MEM_freeN(), and NULL.
Referenced by BKE_reports_string(), BPy_enum_as_string(), code_generate_vertex(), codegen_call_functions(), codegen_convert_datatype(), codegen_declare_tmps(), codegen_print_datatype(), codegen_print_uniforms_functions(), Color_str(), DM_debug_info(), dm_debug_info_layers(), Euler_str(), Matrix_str(), PyC_FlagSet_AsString(), pyrna_func_call(), Quaternion_str(), rna_idp_path_create(), RNA_pointer_as_string(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), ui_def_but_rna(), ui_intro_button(), uiPupMenuReports(), Vector_str(), and WM_operator_pystring().
void BLI_dynstr_free (DynStr * ds)
Free the DynStr
Parameters:
ds The DynStr to free.
Definition at line 251 of file BLI_dynstr.c.
References DynStr::elems, MEM_freeN(), DynStrElem::next, and DynStrElem::str.
Referenced by BKE_reportf(), BKE_reports_prepend(), BKE_reports_prependf(), BKE_reports_string(), BKE_undo_menu_string(), BLI_replacestr(), BLI_sprintfN(), BPy_enum_as_string(), code_generate_fragment(), code_generate_vertex(), console_copy_exec(), DM_debug_info(), get_rna_access(), GPU_code_generate_glsl_lib(), IDnames_to_pupstring(), mathutils_dynstr_to_py(), PyC_FlagSet_AsString(), pyrna_func_call(), report_copy_exec(), rna_idp_path_create(), RNA_path_append(), rna_path_rename_fix(), RNA_pointer_as_string(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), ui_def_but_rna(), uiLayoutIntrospect(), uiPupMenuReports(), and WM_operator_pystring().
char* BLI_dynstr_get_cstring (DynStr * ds)
Get a DynStr's contents as a c-string. The returned c-string should be freed using MEM_freeN.
Parameters:
ds The DynStr of interest.
Returns:
The contents of ds as a c-string.
Definition at line 244 of file BLI_dynstr.c.
References BLI_dynstr_get_cstring_ex(), DynStr::curlen, and MEM_mallocN().
Referenced by BKE_reportf(), BKE_reports_prepend(), BKE_reports_prependf(), BKE_reports_string(), BKE_undo_menu_string(), BLI_replacestr(), BLI_sprintfN(), BPy_enum_as_string(), code_generate_fragment(), code_generate_vertex(), console_copy_exec(), DM_debug_info(), get_rna_access(), GPU_code_generate_glsl_lib(), IDnames_to_pupstring(), PyC_FlagSet_AsString(), pyrna_func_call(), report_copy_exec(), rna_idp_path_create(), RNA_path_append(), rna_path_rename_fix(), RNA_pointer_as_string(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), ui_def_but_rna(), uiLayoutIntrospect(), uiPupMenuReports(), and WM_operator_pystring().
void BLI_dynstr_get_cstring_ex (DynStr * ds, char * str)
Get a DynStr's contents as a c-string. The str argument must be allocated to be at least the size of BLI_dynstr_get_len(ds) + 1.
Parameters:
ds The DynStr of interest.
str The string to fill.
Returns:
The contents of ds as a c-string.
Definition at line 229 of file BLI_dynstr.c.
References DynStr::curlen, DynStr::elems, DynStrElem::next, DynStrElem::str, and strlen().
Referenced by BLI_dynstr_get_cstring(), and mathutils_dynstr_to_py().
int BLI_dynstr_get_len (DynStr * ds)
Find the length of a DynStr.
Parameters:
ds The DynStr of interest.
Returns:
The length of ds.
Definition at line 224 of file BLI_dynstr.c.
References DynStr::curlen.
Referenced by BKE_reportf(), BKE_reports_prepend(), BKE_reports_prependf(), BKE_reports_string(), console_copy_exec(), IDnames_to_pupstring(), and mathutils_dynstr_to_py().
void BLI_dynstr_nappend (DynStr * ds, const char * cstr, int len)
Append a length clamped c-string to a DynStr.
Parameters:
ds The DynStr to append to.
cstr The c-string to append.
len The maximum length of the c-string to copy.
Definition at line 97 of file BLI_dynstr.c.
References BLI_strnlen(), DynStr::curlen, DynStr::elems, DynStr::last, DynStrElem::next, NULL, and DynStrElem::str.
Referenced by console_copy_exec().
DynStr* BLI_dynstr_new (void)
Create a new DynStr.
Returns:
Pointer to a new DynStr.
Definition at line 71 of file BLI_dynstr.c.
References DynStr::curlen, DynStr::elems, DynStr::last, MEM_mallocN(), and NULL.
Referenced by BKE_reportf(), BKE_reports_prepend(), BKE_reports_prependf(), BKE_reports_string(), BKE_undo_menu_string(), BLI_replacestr(), BLI_sprintfN(), BPy_enum_as_string(), code_generate_fragment(), code_generate_vertex(), Color_str(), console_copy_exec(), DM_debug_info(), Euler_str(), get_rna_access(), GPU_code_generate_glsl_lib(), IDnames_to_pupstring(), Matrix_str(), PyC_FlagSet_AsString(), pyrna_func_call(), Quaternion_str(), report_copy_exec(), rna_idp_path_create(), RNA_path_append(), rna_path_rename_fix(), RNA_pointer_as_string(), RNA_pointer_as_string_keywords_ex(), RNA_property_as_string(), ui_def_but_rna(), uiLayoutIntrospect(), uiPupMenuReports(), Vector_str(), and WM_operator_pystring().
void BLI_dynstr_vappendf (DynStr * ds, const char * format, va_list args)
Definition at line 115 of file BLI_dynstr.c.
References BLI_dynstr_append(), len(), MEM_callocN(), MEM_freeN(), NULL, and va_copy.
Referenced by BKE_reportf(), BKE_reports_prependf(), and BLI_sprintfN().