Blender: blender.c File Reference
blender.c File Reference
blenkernel
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <fcntl.h>
#include "MEM_guardedalloc.h"
#include "DNA_userdef_types.h"
#include "DNA_scene_types.h"
#include "DNA_screen_types.h"
#include "DNA_sequence_types.h"
#include "DNA_sound_types.h"
#include "BLI_blenlib.h"
#include "BLI_bpath.h"
#include "BLI_dynstr.h"
#include "BLI_utildefines.h"
#include "BLI_callbacks.h"
#include "IMB_imbuf.h"
#include "IMB_moviecache.h"
#include "BKE_blender.h"
#include "BKE_context.h"
#include "BKE_depsgraph.h"
#include "BKE_displist.h"
#include "BKE_global.h"
#include "BKE_idprop.h"
#include "BKE_ipo.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_report.h"
#include "BKE_scene.h"
#include "BKE_screen.h"
#include "BKE_sequencer.h"
#include "BKE_sound.h"
#include "RE_pipeline.h"
#include "BLO_undofile.h"
#include "BLO_readfile.h"
#include "BLO_writefile.h"
#include "BKE_utildefines.h"
#include "RNA_access.h"
#include "WM_api.h"
Classes
struct UndoElem
Defines
#define UNDO_DISK 0
#define MAXUNDONAME 64
Typedefs
typedef struct UndoElem UndoElem
Functions
void free_blender (void)
void initglobals (void)
static void clear_global (void)
static int clean_paths_visit_cb (void *UNUSED(userdata), char *path_dst, const char *path_src)
static void clean_paths (Main *main)
static void setup_app_data (bContext *C, BlendFileData *bfd, const char *filepath)
static int handle_subversion_warning (Main *main, ReportList *reports)
static void keymap_item_free (wmKeyMapItem *kmi)
void BKE_userdef_free (void)
int BKE_read_file (bContext *C, const char *filepath, ReportList *reports)
int BKE_read_file_from_memory (bContext *C, char *filebuf, int filelength, ReportList *reports)
int BKE_read_file_from_memfile (bContext *C, MemFile *memfile, ReportList *reports)
void set_blender_test_break_cb (void(*func)(void))
int blender_test_break (void)
static int read_undosave (bContext *C, UndoElem *uel)
void BKE_write_undo (bContext *C, const char *name)
void BKE_undo_step (bContext *C, int step)
void BKE_reset_undo (void)
void BKE_undo_number (bContext *C, int nr)
void BKE_undo_name (bContext *C, const char *name)
int BKE_undo_valid (const char *name)
const char * BKE_undo_get_name (int nr, int *active)
char * BKE_undo_menu_string (void)
void BKE_undo_save_quit (void)
Main * BKE_undo_get_main (Scene **scene)
Variables
Global G
UserDef U
char versionstr [48] = ""
static void(* blender_test_break_cb)(void) = NULL
static ListBase undobase = {NULL, NULL}
static UndoElem * curundo = NULL
Detailed Description
Definition in file blender.c.
Define Documentation
#define MAXUNDONAME 64
Definition at line 457 of file blender.c.
#define UNDO_DISK 0
Definition at line 455 of file blender.c.
Referenced by BKE_write_undo(), and read_undosave().
Typedef Documentation
typedef struct UndoElem UndoElem
Function Documentation
int BKE_read_file (bContext * C, const char * filepath, ReportList * reports)
Definition at line 377 of file blender.c.
References BKE_READ_FILE_FAIL, BKE_READ_FILE_OK, BKE_READ_FILE_OK_USERPREFS, BKE_reports_prependf(), BLENDER_STARTUP_FILE, BLO_read_from_file(), free_main(), handle_subversion_warning(), BlendFileData::main, MEM_freeN(), NULL, setup_app_data(), and BlendFileData::user.
Referenced by load_file(), read_undosave(), WM_read_file(), and WM_read_homefile().
int BKE_read_file_from_memfile (bContext * C, MemFile * memfile, ReportList * reports)
Definition at line 418 of file blender.c.
References BKE_reports_prepend(), BLO_read_from_memfile(), CTX_data_main(), Global::main, Main::name, and setup_app_data().
Referenced by read_undosave().
int BKE_read_file_from_memory (bContext * C, char * filebuf, int filelength, ReportList * reports)
Definition at line 404 of file blender.c.
References BKE_reports_prepend(), BLO_read_from_memory(), and setup_app_data().
Referenced by WM_read_homefile().
void BKE_reset_undo (void)
Definition at line 626 of file blender.c.
References BLI_freelistN(), BLO_free_memfile(), ListBase::first, UndoElem::memfile, UndoElem::next, and NULL.
Referenced by WM_exit_ext(), WM_read_file(), and WM_read_homefile().
Main* BKE_undo_get_main (Scene ** scene) [read]
Definition at line 744 of file blender.c.
References BLO_read_from_memfile(), BlendFileData::curscene, Global::main, BlendFileData::main, MEM_freeN(), UndoElem::memfile, Main::name, and NULL.
Referenced by screen_render_invoke().
const char* BKE_undo_get_name (int nr, int * active)
Definition at line 671 of file blender.c.
References BLI_findlink(), UndoElem::name, and NULL.
Referenced by rna_undo_itemf().
char* BKE_undo_menu_string (void)
Definition at line 685 of file blender.c.
References BLI_dynstr_append(), BLI_dynstr_free(), BLI_dynstr_get_cstring(), BLI_dynstr_new(), ListBase::first, UndoElem::name, and UndoElem::next.
void BKE_undo_name (bContext * C, const char * name)
Definition at line 648 of file blender.c.
References BKE_undo_step(), BLI_rfindstring(), and UndoElem::prev.
Referenced by ed_undo_step().
void BKE_undo_number (bContext * C, int nr)
Definition at line 641 of file blender.c.
References BKE_undo_step(), and BLI_findlink().
Referenced by undo_history_exec().
void BKE_undo_save_quit (void)
Definition at line 705 of file blender.c.
References BLI_make_file_string(), BLI_open(), BLI_temporary_dir(), MemFileChunk::buf, MemFile::chunks, curundo, FILE_MAX, ListBase::first, ListBase::last, UndoElem::memfile, MemFileChunk::next, NULL, O_BINARY, MemFileChunk::size, str, UserDef::uiflag, and USER_GLOBALUNDO.
Referenced by WM_exit_ext().
void BKE_undo_step (bContext * C, int step)
Definition at line 599 of file blender.c.
References Global::debug, G_DEBUG, UndoElem::name, UndoElem::next, NULL, UndoElem::prev, and read_undosave().
Referenced by BKE_undo_name(), BKE_undo_number(), and ed_undo_step().
int BKE_undo_valid (const char * name)
Definition at line 659 of file blender.c.
References BLI_rfindstring(), ListBase::first, ListBase::last, and UndoElem::prev.
Referenced by ED_undo_valid().
void BKE_userdef_free (void)
Definition at line 345 of file blender.c.
References wmKeyMapDiffItem::add_item, UserDef::addons, BLI_freelistN(), wmKeyMap::diff_items, ListBase::first, wmKeyMap::items, keymap_item_free(), MEM_freeN(), wmKeyMap::next, wmKeyMapDiffItem::next, wmKeyMapItem::next, wmKeyMapDiffItem::remove_item, UserDef::themes, UserDef::uifonts, UserDef::uistyles, and UserDef::user_keymaps.
Referenced by setup_app_data(), and WM_exit_ext().
void BKE_write_undo (bContext * C, const char * name)
Definition at line 501 of file blender.c.
References BLI_addtail(), BLI_make_file_string(), BLI_remlink(), BLI_snprintf(), BLI_strncpy(), BLI_temporary_dir(), BLO_free_memfile(), BLO_merge_memfile(), BLO_write_file(), BLO_write_file_mem(), CTX_data_main(), FILE_MAX, Global::fileflags, ListBase::first, G_FILE_HISTORY, ListBase::last, MEM_callocN(), MEM_freeN(), MEM_get_memory_in_use(), UndoElem::memfile, UndoElem::name, UndoElem::next, NULL, UndoElem::prev, UndoElem::str, UserDef::uiflag, UNDO_DISK, UserDef::undomemory, UndoElem::undosize, UserDef::undosteps, and USER_GLOBALUNDO.
Referenced by ED_undo_push(), WM_read_file(), and WM_read_homefile().
int blender_test_break (void)
Definition at line 442 of file blender.c.
References Global::afbreek, Global::background, and blender_test_break_cb.
Referenced by bake_image_exec(), BKE_ptcache_bake(), dynamicPaint_bakeImageSequence(), and screen_render_exec().
static void clean_paths (Main * main) [static]
Definition at line 172 of file blender.c.
References BLI_clean(), bpath_traverse_main(), BPATH_TRAVERSE_SKIP_MULTIFILE, clean_paths_visit_cb(), ListBase::first, Scene::id, ID::next, NULL, RenderData::pic, Scene::r, and Main::scene.
Referenced by setup_app_data().
static int clean_paths_visit_cb (void * UNUSEDuserdata, char * path_dst, const char * path_src) [static]
Definition at line 164 of file blender.c.
References BLI_clean(), FALSE, and TRUE.
Referenced by clean_paths().
static void clear_global (void) [static]
Definition at line 153 of file blender.c.
References free_main(), Global::main, and NULL.
Referenced by setup_app_data().
void free_blender (void)
Definition at line 103 of file blender.c.
References BKE_spacetypes_free(), BLI_cb_finalize(), free_main(), free_nodesystem(), IMB_exit(), IMB_moviecache_destruct(), Global::main, NULL, and seq_stripelem_cache_destruct().
Referenced by WM_exit_ext().
static int handle_subversion_warning (Main * main, ReportList * reports) [static]
Definition at line 324 of file blender.c.
References BKE_reportf(), BLENDER_SUBVERSION, BLENDER_VERSION, Main::minsubversionfile, Main::minversionfile, and RPT_ERROR.
Referenced by BKE_read_file().
void initglobals (void)
Definition at line 121 of file blender.c.
References BLENDER_SUBVERSION, BLENDER_VERSION, BLI_snprintf(), Global::charmax, Global::charmin, Global::charstart, Global::f, G_SCRIPT_AUTOEXEC, G_WINDOWSTATE_USERDEF, Global::ima, Global::main, MEM_callocN(), UserDef::savetime, versionstr, and Global::windowstate.
Referenced by main().
static void keymap_item_free (wmKeyMapItem * kmi) [static]
Definition at line 335 of file blender.c.
References IDP_FreeProperty(), MEM_freeN(), wmKeyMapItem::properties, and wmKeyMapItem::ptr.
Referenced by BKE_userdef_free().
static int read_undosave (bContext * C, UndoElem * uel) [static]
Definition at line 470 of file blender.c.
References BKE_read_file(), BKE_READ_FILE_FAIL, BKE_read_file_from_memfile(), BLI_strncpy(), CTX_wm_manager(), DAG_on_visible_update(), FALSE, Global::fileflags, G_FILE_NO_UI, Global::main, UndoElem::memfile, Main::name, NULL, UndoElem::str, UNDO_DISK, and WM_jobs_stop_all().
Referenced by BKE_undo_step().
void set_blender_test_break_cb (void(*)(void) func)
Definition at line 436 of file blender.c.
References blender_test_break_cb.
Referenced by WM_init().
static void setup_app_data (bContext * C, BlendFileData * bfd, const char * filepath) [static]
Definition at line 189 of file blender.c.
References Global::background, BKE_userdef_free(), BLI_strncpy(), clean_paths(), clear_global(), CTX_data_main_set(), CTX_data_scene(), CTX_data_scene_set(), CTX_wm_area_set(), CTX_wm_manager_set(), CTX_wm_menu_set(), CTX_wm_region_set(), CTX_wm_screen(), CTX_wm_screen_set(), BlendFileData::curscene, BlendFileData::curscreen, BlendFileData::displaymode, Global::displaymode, do_versions_ipos_to_animato(), Global::f, FILE_MAX, BlendFileData::fileflags, Global::fileflags, BlendFileData::filename, ListBase::first, G_FILE_NO_UI, G_FILE_RECOVER, G_SCRIPT_AUTOEXEC, G_SCRIPT_OVERRIDE_PREF, G_SWAP_EXCHANGE, BlendFileData::globalf, lib_link_screen_restore(), Global::main, BlendFileData::main, MEM_freeN(), Main::name, NULL, RE_FreeAllRenderResults(), Global::relbase_valid, RNA_property_update_cache_free(), Main::scene, bScreen::scene, Main::screen, Main::script, set_scene_bg(), sound_init_main(), SWAP, BlendFileData::user, Main::versionfile, Global::winpos, BlendFileData::winpos, and Main::wm.
Referenced by BKE_read_file(), BKE_read_file_from_memfile(), and BKE_read_file_from_memory().
Variable Documentation
void(* blender_test_break_cb)(void) = NULL [static]
Definition at line 434 of file blender.c.
Referenced by blender_test_break(), and set_blender_test_break_cb().
UndoElem* curundo = NULL [static]
Definition at line 467 of file blender.c.
Referenced by BKE_undo_save_quit().
Global G
Definition at line 94 of file blender.c.
UserDef U
Definition at line 95 of file blender.c.
ListBase undobase = {NULL, NULL} [static]
Definition at line 466 of file blender.c.
Referenced by undoCurve_to_editCurve().
char versionstr[48] = ""
Definition at line 98 of file blender.c.
Referenced by initglobals(), and stats_string().