Blender: nla_buttons.c File Reference
nla_buttons.c File Reference
NLA editor
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include "DNA_anim_types.h"
#include "BLI_utildefines.h"
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLI_blenlib.h"
#include "BLI_rand.h"
#include "BLF_translation.h"
#include "BKE_nla.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "ED_anim_api.h"
#include "ED_screen.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "nla_intern.h"
Defines
#define B_NOP 1
#define B_REDR 2
Functions
static void do_nla_region_buttons (bContext *C, void *UNUSED(arg), int event)
static int nla_panel_context (const bContext *C, PointerRNA *adt_ptr, PointerRNA *nlt_ptr, PointerRNA *strip_ptr)
static int nla_animdata_panel_poll (const bContext *C, PanelType *UNUSED(pt))
static int nla_track_panel_poll (const bContext *C, PanelType *UNUSED(pt))
static int nla_strip_panel_poll (const bContext *C, PanelType *UNUSED(pt))
static int nla_strip_actclip_panel_poll (const bContext *C, PanelType *UNUSED(pt))
static int nla_strip_eval_panel_poll (const bContext *C, PanelType *UNUSED(pt))
static void nla_panel_animdata (const bContext *C, Panel *pa)
static void nla_panel_track (const bContext *C, Panel *pa)
static void nla_panel_properties (const bContext *C, Panel *pa)
static void nla_panel_actclip (const bContext *C, Panel *pa)
static void nla_panel_evaluation (const bContext *C, Panel *pa)
static void nla_panel_modifiers (const bContext *C, Panel *pa)
void nla_buttons_register (ARegionType *art)
static int nla_properties (bContext *C, wmOperator *UNUSED(op))
void NLA_OT_properties (wmOperatorType *ot)
Detailed Description
Definition in file nla_buttons.c.
Define Documentation
#define B_NOP 1
Definition at line 70 of file nla_buttons.c.
#define B_REDR 2
Definition at line 71 of file nla_buttons.c.
Function Documentation
static void do_nla_region_buttons (bContext * C, void * UNUSEDarg, int event) [static]
Definition at line 75 of file nla_buttons.c.
References NC_OBJECT, NC_SCENE, ND_TRANSFORM, NULL, and WM_event_add_notifier().
Referenced by nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), and nla_panel_track().
static int nla_animdata_panel_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 183 of file nla_buttons.c.
References PointerRNA::data, nla_panel_context(), and NULL.
Referenced by nla_buttons_register().
void nla_buttons_register (ARegionType * art)
Definition at line 468 of file nla_buttons.c.
References BLI_addtail(), PanelType::draw, PanelType::flag, PanelType::idname, PanelType::label, MEM_callocN(), nla_animdata_panel_poll(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), nla_strip_actclip_panel_poll(), nla_strip_eval_panel_poll(), nla_strip_panel_poll(), nla_track_panel_poll(), ARegionType::paneltypes, PNL_DEFAULT_CLOSED, and PanelType::poll.
Referenced by ED_spacetype_nla().
void NLA_OT_properties (wmOperatorType * ot)
Definition at line 527 of file nla_buttons.c.
References wmOperatorType::description, ED_operator_nla_active(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, nla_properties(), and wmOperatorType::poll.
Referenced by nla_operatortypes().
static void nla_panel_actclip (const bContext * C, Panel * pa) [static]
Definition at line 357 of file nla_buttons.c.
References do_nla_region_buttons(), Panel::layout, nla_panel_context(), NULL, RNA_boolean_get(), uiBlockSetHandleFunc(), uiItemL(), uiItemO(), uiItemR(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and uiLayoutSetActive().
Referenced by nla_buttons_register().
static void nla_panel_animdata (const bContext * C, Panel * pa) [static]
Definition at line 236 of file nla_buttons.c.
References do_nla_region_buttons(), Panel::layout, nla_panel_context(), NULL, uiBlockSetHandleFunc(), uiItemR(), uiLayoutGetBlock(), uiLayoutRow(), and uiTemplateID().
Referenced by nla_buttons_register().
static int nla_panel_context (const bContext * C, PointerRNA * adt_ptr, PointerRNA * nlt_ptr, PointerRNA * strip_ptr) [static]
Definition at line 88 of file nla_buttons.c.
References bAnimListElem::adt, ANIM_animdata_filter(), ANIM_animdata_get_context(), ANIMFILTER_ACTIVE, ANIMFILTER_DATA_VISIBLE, ANIMFILTER_LIST_CHANNELS, ANIMFILTER_LIST_VISIBLE, ANIMTYPE_DSARM, ANIMTYPE_DSCAM, ANIMTYPE_DSCUR, ANIMTYPE_DSLAM, ANIMTYPE_DSMAT, ANIMTYPE_DSMBALL, ANIMTYPE_DSNTREE, ANIMTYPE_DSPART, ANIMTYPE_DSSKEY, ANIMTYPE_DSSPK, ANIMTYPE_DSWOR, ANIMTYPE_FILLACTD, ANIMTYPE_NLATRACK, ANIMTYPE_OBJECT, ANIMTYPE_SCENE, BKE_nlastrip_find_active(), BLI_freelistN(), bAnimListElem::data, bAnimContext::data, bAnimContext::datatype, filter(), ListBase::first, bAnimListElem::id, if(), bAnimListElem::next, NULL, RNA_AnimData, RNA_NlaStrip, RNA_NlaTrack, RNA_pointer_create(), and bAnimListElem::type.
Referenced by nla_animdata_panel_poll(), nla_panel_actclip(), nla_panel_animdata(), nla_panel_evaluation(), nla_panel_modifiers(), nla_panel_properties(), nla_panel_track(), nla_strip_actclip_panel_poll(), nla_strip_eval_panel_poll(), nla_strip_panel_poll(), and nla_track_panel_poll().
static void nla_panel_evaluation (const bContext * C, Panel * pa) [static]
Definition at line 393 of file nla_buttons.c.
References do_nla_region_buttons(), Panel::layout, nla_panel_context(), NULL, RNA_boolean_get(), uiBlockSetHandleFunc(), uiItemR(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and uiLayoutSetEnabled().
Referenced by nla_buttons_register().
static void nla_panel_modifiers (const bContext * C, Panel * pa) [static]
Definition at line 425 of file nla_buttons.c.
References ANIM_uiTemplate_fmodifier_draw(), BUT, PointerRNA::data, do_nla_region_buttons(), ListBase::first, PointerRNA::id, IFACE_, Panel::layout, NlaStrip::modifiers, FModifier::next, nla_panel_context(), NULL, TIP_, uiBlockSetHandleFunc(), uiDefButO(), uiItemO(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and WM_OP_INVOKE_REGION_WIN.
Referenced by nla_buttons_register().
static void nla_panel_properties (const bContext * C, Panel * pa) [static]
Definition at line 292 of file nla_buttons.c.
References do_nla_region_buttons(), Panel::layout, nla_panel_context(), NLASTRIP_TYPE_SOUND, NULL, RNA_boolean_get(), RNA_enum_get(), uiBlockSetHandleFunc(), uiItemL(), uiItemR(), uiLayoutColumn(), uiLayoutGetBlock(), uiLayoutRow(), and uiLayoutSetActive().
Referenced by nla_buttons_register().
static void nla_panel_track (const bContext * C, Panel * pa) [static]
Definition at line 272 of file nla_buttons.c.
References do_nla_region_buttons(), Panel::layout, nla_panel_context(), NULL, uiBlockSetHandleFunc(), uiItemR(), uiLayoutGetBlock(), and uiLayoutRow().
Referenced by nla_buttons_register().
static int nla_properties (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 516 of file nla_buttons.c.
References CTX_wm_area(), ED_region_toggle_hidden(), nla_has_buttons_region(), and OPERATOR_FINISHED.
Referenced by NLA_OT_properties().
static int nla_strip_actclip_panel_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 201 of file nla_buttons.c.
References PointerRNA::data, nla_panel_context(), NLASTRIP_TYPE_CLIP, NULL, and NlaStrip::type.
Referenced by nla_buttons_register().
static int nla_strip_eval_panel_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 215 of file nla_buttons.c.
References PointerRNA::data, nla_panel_context(), NLASTRIP_TYPE_SOUND, NULL, and NlaStrip::type.
Referenced by nla_buttons_register().
static int nla_strip_panel_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 195 of file nla_buttons.c.
References PointerRNA::data, nla_panel_context(), and NULL.
Referenced by nla_buttons_register().
static int nla_track_panel_poll (const bContext * C, PanelType * UNUSEDpt) [static]
Definition at line 189 of file nla_buttons.c.
References PointerRNA::data, nla_panel_context(), and NULL.
Referenced by nla_buttons_register().