Blender: btMinMax.h File Reference
btMinMax.h File Reference
#include "LinearMath/btScalar.h"
Functions
template<class T >
SIMD_FORCE_INLINE const T & btMin (const T &a, const T &b)
template<class T >
SIMD_FORCE_INLINE const T & btMax (const T &a, const T &b)
template<class T >
SIMD_FORCE_INLINE const T & btClamped (const T &a, const T &lb, const T &ub)
template<class T >
SIMD_FORCE_INLINE void btSetMin (T &a, const T &b)
template<class T >
SIMD_FORCE_INLINE void btSetMax (T &a, const T &b)
template<class T >
SIMD_FORCE_INLINE void btClamp (T &a, const T &lb, const T &ub)
Function Documentation
template<class T > SIMD_FORCE_INLINE void btClamp (T & a, const T & lb, const T & ub)
Definition at line 59 of file btMinMax.h.
template<class T > SIMD_FORCE_INLINE const T& btClamped (const T & a, const T & lb, const T & ub)
Definition at line 35 of file btMinMax.h.
Referenced by btRigidBody::setDamping().
template<class T > SIMD_FORCE_INLINE const T& btMax (const T & a, const T & b)
Definition at line 29 of file btMinMax.h.
Referenced by btDefaultCollisionConfiguration::btDefaultCollisionConfiguration(), btSoftBodyRigidBodyCollisionConfiguration::btSoftBodyRigidBodyCollisionConfiguration(), btSoftBodyHelpers::CreateFromTriMesh(), OcclusionBuffer::draw(), gjkepa2_impl::GJK::Evaluate(), getmaxdepth(), btSoftColliders::CollideCL_SS::Process(), btSoftColliders::CollideVF_SS::Process(), CcdPhysicsEnvironment::processFhSprings(), btSoftBody::solveClusters(), btConeTwistConstraint::solveConstraintObsolete(), and TestTriangleAgainstAabb2().
template<class T > SIMD_FORCE_INLINE const T& btMin (const T & a, const T & b)
Definition at line 23 of file btMinMax.h.
Referenced by btDbvtBroadphase::collide(), OcclusionBuffer::draw(), btSoftBody::generateClusters(), btCollisionDispatcher::getNewManifold(), gjkepa2_impl::EPA::newface(), btSoftBody::AJoint::Prepare(), btSoftColliders::CollideCL_SS::Process(), btSoftColliders::CollideCL_RS::Process(), btSoftBody::PSolve_RContacts(), and TestTriangleAgainstAabb2().
template<class T > SIMD_FORCE_INLINE void btSetMax (T & a, const T & b)
Definition at line 50 of file btMinMax.h.
Referenced by ATTRIBUTE_ALIGNED16(), and calcRollingFriction().
template<class T > SIMD_FORCE_INLINE void btSetMin (T & a, const T & b)
Definition at line 41 of file btMinMax.h.
Referenced by ATTRIBUTE_ALIGNED16(), btRayAabb(), and calcRollingFriction().