Blender: BKE_image.h File Reference
BKE_image.h File Reference
blenkernel
Defines
#define IMA_SRC_CHECK 0
#define IMA_SRC_FILE 1
#define IMA_SRC_SEQUENCE 2
#define IMA_SRC_MOVIE 3
#define IMA_SRC_GENERATED 4
#define IMA_SRC_VIEWER 5
#define IMA_TYPE_IMAGE 0
#define IMA_TYPE_MULTILAYER 1
#define IMA_TYPE_UV_TEST 2
#define IMA_TYPE_R_RESULT 4
#define IMA_TYPE_COMPOSITE 5
#define IMA_OK 1
#define IMA_OK_LOADED 2
#define IMA_SIGNAL_RELOAD 0
#define IMA_SIGNAL_FREE 1
#define IMA_SIGNAL_SRC_CHANGE 5
#define IMA_SIGNAL_USER_NEW_IMAGE 6
#define IMA_CHAN_FLAG_BW 1
#define IMA_CHAN_FLAG_RGB 2
#define IMA_CHAN_FLAG_ALPHA 4
Functions
void free_image (struct Image *me)
void BKE_stamp_info (struct Scene *scene, struct Object *camera, struct ImBuf *ibuf)
void BKE_stamp_buf (struct Scene *scene, struct Object *camera, unsigned char *rect, float *rectf, int width, int height, int channels)
int BKE_alphatest_ibuf (struct ImBuf *ibuf)
int BKE_write_ibuf_stamp (struct Scene *scene, struct Object *camera, struct ImBuf *ibuf, const char *name, struct ImageFormatData *imf)
int BKE_write_ibuf (struct ImBuf *ibuf, const char *name, struct ImageFormatData *imf)
int BKE_write_ibuf_as (struct ImBuf *ibuf, const char *name, struct ImageFormatData *imf, const short is_copy)
void BKE_makepicstring (char *string, const char *base, const char *relbase, int frame, const char imtype, const short use_ext, const short use_frames)
int BKE_add_image_extension (char *string, const char imtype)
char BKE_ftype_to_imtype (const int ftype)
int BKE_imtype_to_ftype (const char imtype)
int BKE_imtype_is_movie (const char imtype)
int BKE_imtype_supports_zbuf (const char imtype)
int BKE_imtype_supports_compress (const char imtype)
int BKE_imtype_supports_quality (const char imtype)
char BKE_imtype_valid_channels (const char imtype)
char BKE_imtype_valid_depths (const char imtype)
char BKE_imtype_from_arg (const char *arg)
void BKE_imformat_defaults (struct ImageFormatData *im_format)
struct anim * openanim (const char *name, int flags, int streamindex)
void image_de_interlace (struct Image *ima, int odd)
void make_local_image (struct Image *ima)
void tag_image_time (struct Image *ima)
void free_old_images (void)
struct ImBuf * BKE_image_get_ibuf (struct Image *ima, struct ImageUser *iuser)
struct ImBuf * BKE_image_acquire_ibuf (struct Image *ima, struct ImageUser *iuser, void **lock_r)
void BKE_image_release_ibuf (struct Image *ima, void *lock)
struct Image * BKE_add_image_file (const char *name)
struct Image * BKE_add_image_size (unsigned int width, unsigned int height, const char *name, int depth, int floatbuf, short uvtestgrid, float color[4])
struct Image * BKE_add_image_imbuf (struct ImBuf *ibuf)
void BKE_image_signal (struct Image *ima, struct ImageUser *iuser, int signal)
struct Image * BKE_image_verify_viewer (int type, const char *name)
void BKE_image_assign_ibuf (struct Image *ima, struct ImBuf *ibuf)
void BKE_image_user_calc_frame (struct ImageUser *iuser, int cfra, int fieldnr)
int BKE_image_user_get_frame (const struct ImageUser *iuser, int cfra, int fieldnr)
struct RenderPass * BKE_image_multilayer_index (struct RenderResult *rr, struct ImageUser *iuser)
struct RenderResult * BKE_image_acquire_renderresult (struct Scene *scene, struct Image *ima)
void BKE_image_release_renderresult (struct Scene *scene, struct Image *ima)
void BKE_image_backup_render (struct Scene *scene, struct Image *ima)
void BKE_image_free_all_textures (void)
void BKE_image_free_anim_ibufs (struct Image *ima, int except_frame)
void BKE_image_all_free_anim_ibufs (int except_frame)
void BKE_image_memorypack (struct Image *ima)
void BKE_image_print_memlist (void)
struct Image * copy_image (struct Image *ima)
void BKE_image_merge (struct Image *dest, struct Image *source)
int BKE_image_has_alpha (struct Image *image)
void BKE_image_buf_fill_color (unsigned char *rect, float *rect_float, int width, int height, const float color[4])
void BKE_image_buf_fill_checker (unsigned char *rect, float *rect_float, int height, int width)
void BKE_image_buf_fill_checker_color (unsigned char *rect, float *rect_float, int height, int width)
Detailed Description
Since:
March 2001
Author:
nzc
Definition in file BKE_image.h.
Define Documentation
#define IMA_CHAN_FLAG_ALPHA 4
Definition at line 122 of file BKE_image.h.
Referenced by BKE_imtype_valid_channels().
#define IMA_CHAN_FLAG_BW 1
Definition at line 120 of file BKE_image.h.
Referenced by BKE_imtype_valid_channels().
#define IMA_CHAN_FLAG_RGB 2
Definition at line 121 of file BKE_image.h.
Referenced by BKE_imtype_valid_channels().
#define IMA_OK 1
Definition at line 108 of file BKE_image.h.
Referenced by BKE_add_image_file(), image_alloc(), and image_free_buffers().
#define IMA_OK_LOADED 2
Definition at line 109 of file BKE_image.h.
Referenced by BKE_add_image_imbuf(), BKE_add_image_size(), BKE_image_acquire_ibuf(), finish_bake_internal(), image_get_render_result(), image_initialize_after_load(), node_composit_exec_splitviewer(), and node_composit_exec_viewer().
#define IMA_SIGNAL_FREE 1
Definition at line 114 of file BKE_image.h.
Referenced by BKE_image_signal(), node_composit_exec_composite(), screen_opengl_render_init(), screen_render_exec(), and screen_render_invoke().
#define IMA_SIGNAL_RELOAD 0
Definition at line 113 of file BKE_image.h.
Referenced by BKE_image_signal(), image_open_exec(), image_reload_exec(), image_replace_exec(), and unpackImage().
#define IMA_SIGNAL_SRC_CHANGE 5
Definition at line 116 of file BKE_image.h.
Referenced by BKE_image_signal().
#define IMA_SIGNAL_USER_NEW_IMAGE 6
Definition at line 118 of file BKE_image.h.
Referenced by BKE_image_signal(), ED_space_image_set(), and image_new_exec().
#define IMA_SRC_CHECK 0
Definition at line 91 of file BKE_image.h.
#define IMA_SRC_FILE 1
Definition at line 92 of file BKE_image.h.
Referenced by BKE_add_image_file(), BKE_add_image_imbuf(), BKE_image_acquire_ibuf(), BKE_image_memorypack(), BKE_image_signal(), bpath_traverse_id(), def_cmp_image(), do_versions(), image_get_ibuf_threadsafe(), image_replace_exec(), packAll(), and save_image_doit().
#define IMA_SRC_GENERATED 4
Definition at line 95 of file BKE_image.h.
Referenced by BKE_add_image_file(), BKE_add_image_size(), BKE_image_acquire_ibuf(), BKE_image_memorypack(), BKE_image_signal(), def_cmp_image(), image_get_ibuf_threadsafe(), save_image_doit(), save_image_options_init(), and uiTemplateImage().
#define IMA_SRC_MOVIE 3
Definition at line 94 of file BKE_image.h.
Referenced by BKE_add_image_file(), BKE_image_acquire_ibuf(), BKE_image_all_free_anim_ibufs(), BKE_texture_dependsOnTime(), bpath_traverse_id(), def_cmp_image(), do_versions(), ED_image_update_frame(), GPU_free_images_anim(), image_get_ibuf_threadsafe(), image_info(), image_pack_test(), image_replace_exec(), image_unpack_exec(), image_unpack_invoke(), init_render_texture(), modifier_init_texture(), node_composit_buts_image(), ntreeCompositTagAnimated(), packAll(), RE_init_sample_material(), and uiTemplateImage().
#define IMA_SRC_SEQUENCE 2
Definition at line 93 of file BKE_image.h.
Referenced by BKE_image_acquire_ibuf(), BKE_image_all_free_anim_ibufs(), BKE_image_signal(), BKE_texture_dependsOnTime(), bpath_traverse_id(), def_cmp_image(), ED_image_update_frame(), GPU_free_images_anim(), image_get_ibuf_threadsafe(), image_info(), image_pack_test(), image_save_sequence_exec(), image_unpack_exec(), image_unpack_invoke(), init_render_texture(), load_frame_image_sequence(), modifier_init_texture(), node_composit_buts_image(), ntreeCompositTagAnimated(), packAll(), RE_init_sample_material(), and uiTemplateImage().
#define IMA_SRC_VIEWER 5
Definition at line 96 of file BKE_image.h.
Referenced by BKE_add_image_file(), BKE_image_acquire_ibuf(), BKE_image_verify_viewer(), do_versions(), draw_image_main(), IDnames_to_dyn_pupstring(), image_get_ibuf_threadsafe(), image_mem_size(), image_refresh(), image_verify_buffer_float(), save_image_doit(), and uiTemplateImage().
#define IMA_TYPE_COMPOSITE 5
Definition at line 105 of file BKE_image.h.
Referenced by BKE_image_acquire_ibuf(), do_versions(), draw_image_main(), draw_nodespace_back_pix(), ED_image_aspect(), ED_node_set_active(), ED_space_image_set(), ED_space_image_show_render(), ED_uvedit_assign_image(), ED_uvedit_ensure_uvs(), image_save_as_invoke(), rna_def_image(), sample_apply(), save_image_options_init(), snode_bg_viewmove_invoke(), uiTemplateImage(), and uvedit_set_tile().
#define IMA_TYPE_IMAGE 0
Definition at line 99 of file BKE_image.h.
Referenced by BKE_add_image_file(), BKE_add_image_imbuf(), BKE_image_acquire_ibuf(), BKE_image_memorypack(), BKE_image_signal(), do_versions(), image_get_ibuf_multilayer(), image_get_ibuf_threadsafe(), image_load_sequence_multilayer(), rna_def_image(), and save_image_doit().
#define IMA_TYPE_MULTILAYER 1
Definition at line 100 of file BKE_image.h.
Referenced by BKE_image_acquire_ibuf(), BKE_image_signal(), cmp_node_image_create_outputs(), image_get_ibuf_threadsafe(), image_load_image_file(), image_load_sequence_file(), image_save_sequence_exec(), node_composit_buts_image(), node_composit_exec_image(), rna_def_image(), and uiTemplateImage().
#define IMA_TYPE_R_RESULT 4
Definition at line 104 of file BKE_image.h.
Referenced by BKE_image_acquire_ibuf(), BKE_image_acquire_renderresult(), BKE_image_release_renderresult(), do_versions(), draw_image_main(), ED_image_aspect(), ED_space_image_acquire_buffer(), ED_space_image_set(), ED_space_image_show_render(), ED_space_image_size(), ED_uvedit_assign_image(), ED_uvedit_ensure_uvs(), find_area_showing_r_result(), image_cycle_render_slot_poll(), image_save_as_invoke(), node_composit_exec_composite(), render_view_open(), rna_def_image(), save_image_doit(), save_image_options_init(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), uiTemplateImage(), uiTemplateImageLayers(), and uvedit_set_tile().
#define IMA_TYPE_UV_TEST 2
Definition at line 102 of file BKE_image.h.
Referenced by BKE_add_image_size(), BKE_image_signal(), and rna_def_image().
Function Documentation
int BKE_add_image_extension (char * string, const char imtype)
Definition at line 1075 of file image.c.
References BLI_ensure_extension(), BLI_replace_extension(), BLI_testextensie(), BLI_testextensie_array(), ELEM, ELEM5, FALSE, FILE_MAX, G, imb_ext_image, imb_ext_image_qt, NULL, R_IMF_IMTYPE_BMP, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_DDS, R_IMF_IMTYPE_DPX, R_IMF_IMTYPE_FFMPEG, R_IMF_IMTYPE_H264, R_IMF_IMTYPE_IRIS, R_IMF_IMTYPE_IRIZ, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_PNG, R_IMF_IMTYPE_RADHDR, R_IMF_IMTYPE_RAWTGA, R_IMF_IMTYPE_TARGA, R_IMF_IMTYPE_THEORA, R_IMF_IMTYPE_TIFF, and R_IMF_IMTYPE_XVID.
Referenced by BKE_makepicstring(), BL_MakeScreenShot(), do_write_image_or_movie(), dynamicPaint_outputSurfaceImage(), envmap_save_exec(), and WM_operator_filesel_ensure_ext_imtype().
struct Image* BKE_add_image_file (const char * name) [read]
Definition at line 513 of file image.c.
References Image::anim, BLI_open(), BLI_path_abs(), BLI_path_cmp, BLI_strncpy(), BLI_testextensie_array(), FILE_MAX, G, Image::id, IMA_OK, IMA_SRC_FILE, IMA_SRC_GENERATED, IMA_SRC_MOVIE, IMA_SRC_VIEWER, IMA_TYPE_IMAGE, image_alloc(), imb_ext_movie, len(), Image::name, ID::next, NULL, O_BINARY, Image::ok, Image::source, str, strlen(), and ID::us.
Referenced by background_image_add_invoke(), drop_named_image_invoke(), image_open_exec(), node_add_file_exec(), and DocumentImporter::writeImage().
struct Image* BKE_add_image_imbuf (struct ImBuf * ibuf) [read]
Definition at line 620 of file image.c.
References BLI_path_basename(), BLI_strncpy(), FILE_MAX, IMA_NO_INDEX, IMA_OK_LOADED, IMA_SRC_FILE, IMA_TYPE_IMAGE, image_alloc(), image_assign_ibuf(), Image::name, ImBuf::name, and Image::ok.
Referenced by texture_paint_image_from_view_exec().
struct Image* BKE_add_image_size (unsigned int width, unsigned int height, const char * name, int depth, int floatbuf, short uvtestgrid, float color[4]) [read]
Definition at line 596 of file image.c.
References add_ibuf_size(), Image::gen_flag, Image::gen_type, Image::gen_x, Image::gen_y, IMA_GEN_FLOAT, IMA_NO_INDEX, IMA_OK_LOADED, IMA_SRC_GENERATED, IMA_TYPE_UV_TEST, image_alloc(), image_assign_ibuf(), Image::name, and Image::ok.
Referenced by image_new_exec().
int BKE_alphatest_ibuf (struct ImBuf * ibuf)
Definition at line 1544 of file image.c.
References FALSE, ImBuf::rect, ImBuf::rect_float, TRUE, ImBuf::x, and ImBuf::y.
Referenced by RE_bake_ibuf_filter(), and save_image_doit().
char BKE_ftype_to_imtype (const int ftype)
Definition at line 887 of file image.c.
References BMP, IMAGIC, OPENEXR, PNG, R_IMF_IMTYPE_BMP, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_DDS, R_IMF_IMTYPE_DPX, R_IMF_IMTYPE_IRIS, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_JPEG90, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_PNG, R_IMF_IMTYPE_RADHDR, R_IMF_IMTYPE_RAWTGA, R_IMF_IMTYPE_TARGA, R_IMF_IMTYPE_TIFF, RAWTGA, and TGA.
Referenced by save_image_options_init().
struct ImBuf* BKE_image_acquire_ibuf (struct Image * ima, struct ImageUser * iuser, void ** lock_r) [read]
Definition at line 2446 of file image.c.
References add_ibuf_size(), BLI_lock_thread(), BLI_unlock_thread(), Image::gen_flag, Image::gen_type, Image::gen_x, Image::gen_y, IB_rect, IMA_GEN_FLOAT, IMA_NO_INDEX, IMA_OK_LOADED, IMA_SRC_FILE, IMA_SRC_GENERATED, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, IMA_SRC_VIEWER, IMA_TYPE_COMPOSITE, IMA_TYPE_IMAGE, IMA_TYPE_MULTILAYER, IMA_TYPE_R_RESULT, image_assign_ibuf(), image_get_ibuf(), image_get_ibuf_multilayer(), image_get_ibuf_threadsafe(), image_get_render_result(), image_load_image_file(), image_load_movie_file(), image_load_sequence_file(), image_load_sequence_multilayer(), IMB_allocImBuf(), ImBuf::index, LOCK_IMAGE, LOCK_VIEWER, Image::name, NULL, Image::ok, ImageUser::ok, Image::source, tag_image_time(), and Image::type.
Referenced by BKE_image_get_ibuf(), BKE_image_has_alpha(), draw_nodespace_back_pix(), ED_image_size(), ED_space_image_acquire_buffer(), image_rect_update(), node_composit_exec_splitviewer(), node_composit_exec_viewer(), sample_apply(), screen_opengl_render_anim_step(), screen_opengl_render_apply(), snode_bg_viewmove_invoke(), and uiTemplateImage().
struct RenderResult* BKE_image_acquire_renderresult (struct Scene * scene, struct Image * ima) [read]
Definition at line 1907 of file image.c.
References Scene::id, IMA_TYPE_R_RESULT, Image::last_render_slot, ID::name, NULL, RE_AcquireResultRead(), RE_GetRender(), Image::render_slot, Image::renders, Image::rr, and Image::type.
Referenced by draw_render_info(), and save_image_doit().
void BKE_image_all_free_anim_ibufs (int except_frame)
Definition at line 835 of file image.c.
References BKE_image_free_anim_ibufs(), ELEM, G, Image::id, IMA_SRC_MOVIE, IMA_SRC_SEQUENCE, ID::next, and Image::source.
Referenced by do_render_all_options(), and image_record_composite_apply().
void BKE_image_assign_ibuf (struct Image * ima, struct ImBuf * ibuf)
Definition at line 1784 of file image.c.
References IMA_NO_INDEX, and image_assign_ibuf().
void BKE_image_backup_render (struct Scene * scene, struct Image * ima)
Definition at line 1931 of file image.c.
References Scene::id, Image::last_render_slot, ID::name, NULL, RE_FreeRenderResult(), RE_GetRender(), RE_SwapResult(), Image::render_slot, and Image::renders.
Referenced by screen_opengl_render_init(), screen_render_exec(), and screen_render_invoke().
void BKE_image_buf_fill_checker (unsigned char * rect, float * rect_float, int height, int width)
Definition at line 69 of file image_gen.c.
References fabs(), floorf, fmodf, g, hsv_to_rgb(), and powf.
Referenced by add_ibuf_size().
void BKE_image_buf_fill_checker_color (unsigned char * rect, float * rect_float, int height, int width)
Definition at line 338 of file image_gen.c.
References checker_board_color_fill(), checker_board_color_tint(), checker_board_grid_fill(), and checker_board_text().
Referenced by add_ibuf_size().
void BKE_image_buf_fill_color (unsigned char * rect, float * rect_float, int width, int height, const float color[4])
Definition at line 36 of file image_gen.c.
References copy_v4_v4(), and rgba_float_to_uchar().
Referenced by add_ibuf_size().
void BKE_image_free_all_textures (void)
Definition at line 776 of file image.c.
References ListBase::first, ID::flag, G, IB_BITMAPDIRTY, Image::ibufs, Tex::id, Image::id, Tex::ima, image_free_buffers(), LIB_DOIT, ImBuf::mipmap, ImBuf::next, ID::next, NULL, ImBuf::userflags, ImBuf::x, and ImBuf::y.
Referenced by RE_Database_Free().
void BKE_image_free_anim_ibufs (struct Image * ima, int except_frame)
Definition at line 813 of file image.c.
References BLI_remlink(), ListBase::first, IB_BITMAPDIRTY, Image::ibufs, IMA_INDEX_FRAME, IMA_NO_INDEX, IMB_freeImBuf(), ImBuf::index, MEM_freeN(), ImBuf::next, NULL, ImBuf::userdata, and ImBuf::userflags.
Referenced by BKE_image_all_free_anim_ibufs(), and load_frame_image_sequence().
struct ImBuf* BKE_image_get_ibuf (struct Image * ima, struct ImageUser * iuser) [read]
Definition at line 2584 of file image.c.
References BKE_image_acquire_ibuf(), and NULL.
Referenced by apply_heights_callback(), apply_heights_data(), apply_tangmat_callback(), bake_images(), brush_gen_texture_cache(), clear_images(), cmp_node_image_create_outputs(), colorfn(), compatible_bump_compute(), do_halo_tex(), do_lamp_tex(), do_material_tex(), do_multires_bake(), do_sky_tex(), draw_bgpic(), draw_empty_image(), draw_mesh_text(), envmaptex(), finish_bake_internal(), finish_images(), get_alpha_clone_image(), get_next_bake_face(), gpu_make_repbind(), GPU_paint_update_image(), GPU_verify_image(), icon_preview_startjob(), image_aspect(), image_de_interlace(), image_invert_exec(), image_invert_poll(), image_pack_exec(), image_pack_invoke(), image_record_composite_apply(), image_sample(), image_undo_restore(), imagewrap(), imagewraposa(), imagewraposa_aniso(), imapaint_canvas_set(), imapaint_paint_stroke(), imapaint_paint_sub_stroke(), init_heights_data(), BL_Texture::InitCubeMap(), BL_Texture::InitFromImage(), load_frame_image_sequence(), multiresbake_check(), multitex_nodes(), node_composit_exec_image(), node_composit_get_image(), node_composit_get_zimage(), ntap_bump_compute(), pack_all_invoke(), project_paint_begin(), project_paint_uvpixel_init(), project_paint_uvpixel_mask(), RE_bake_shade_all_selected(), shade_tface(), BL_Texture::SplitEnvMap(), and texture_paint_camera_project_exec().
int BKE_image_has_alpha (struct Image * image)
Definition at line 2643 of file image.c.
References BKE_image_acquire_ibuf(), BKE_image_release_ibuf(), NULL, and ImBuf::planes.
Referenced by BL_ConvertMesh(), ConvertMaterial(), set_draw_settings_cached(), and set_facetexture_flags().
void BKE_image_memorypack (struct Image * ima)
Definition at line 637 of file image.c.
References PackedFile::data, ImBuf::encodedbuffer, ImBuf::encodedsize, freePackedFile(), ImBuf::ftype, IB_BITMAPDIRTY, IB_mem, IB_rect, IMA_NO_INDEX, IMA_SRC_FILE, IMA_SRC_GENERATED, IMA_TYPE_IMAGE, image_get_ibuf(), IMB_saveiff(), MEM_callocN(), ImBuf::name, NULL, Image::packedfile, pf, ImBuf::planes, PNG, R_IMF_PLANES_RGBA, PackedFile::size, Image::source, Image::type, and ImBuf::userflags.
Referenced by image_pack_exec().
void BKE_image_merge (struct Image * dest, struct Image * source)
Definition at line 492 of file image.c.
References BLI_remlink(), ListBase::first, free_libblock(), G, Image::ibufs, IMA_INDEX_FRAME, IMA_INDEX_PASS, image_assign_ibuf(), and ImBuf::index.
Referenced by local_merge().
struct RenderPass* BKE_image_multilayer_index (struct RenderResult * rr, struct ImageUser * iuser) [read]
Definition at line 1873 of file image.c.
References ListBase::first, ImBuf::index, ImageUser::layer, RenderResult::layers, ImageUser::multi_index, RenderPass::next, RenderLayer::next, NULL, ImageUser::pass, and RenderLayer::passes.
Referenced by compbuf_multilayer_get(), image_get_ibuf_multilayer(), image_load_sequence_multilayer(), image_multi_cb(), image_multi_declay_cb(), image_multi_decpass_cb(), image_multi_inclay_cb(), and image_multi_incpass_cb().
void BKE_image_print_memlist (void)
Definition at line 758 of file image.c.
References G, Image::id, image_mem_size(), ID::name, ID::next, and size().
Referenced by RE_Database_Free().
void BKE_image_release_ibuf (struct Image * ima, void * lock)
Definition at line 2571 of file image.c.
References BLI_unlock_thread(), LOCK_VIEWER, and RE_ReleaseResultImage().
Referenced by BKE_image_has_alpha(), draw_nodespace_back_pix(), ED_image_size(), ED_space_image_release_buffer(), image_rect_update(), node_composit_exec_splitviewer(), node_composit_exec_viewer(), sample_apply(), screen_opengl_render_anim_step(), screen_opengl_render_apply(), snode_bg_viewmove_invoke(), and uiTemplateImage().
void BKE_image_release_renderresult (struct Scene * scene, struct Image * ima)
Definition at line 1922 of file image.c.
References Scene::id, IMA_TYPE_R_RESULT, Image::last_render_slot, ID::name, RE_GetRender(), RE_ReleaseResult(), Image::render_slot, Image::rr, and Image::type.
Referenced by draw_render_info(), and save_image_doit().
void BKE_image_signal (struct Image * ima, struct ImageUser * iuser, int signal)
Definition at line 1789 of file image.c.
References freePackedFile(), G, Image::gen_x, Image::gen_y, Scene::id, Image::id, ID_BLEND_PATH, IMA_NO_INDEX, IMA_SIGNAL_FREE, IMA_SIGNAL_RELOAD, IMA_SIGNAL_SRC_CHANGE, IMA_SIGNAL_USER_NEW_IMAGE, IMA_SRC_FILE, IMA_SRC_GENERATED, IMA_SRC_SEQUENCE, IMA_TYPE_IMAGE, IMA_TYPE_MULTILAYER, IMA_TYPE_UV_TEST, image_free_buffers(), image_get_ibuf(), ImageUser::layer, ImageUser::multi_index, Image::name, newPackedFile(), ID::next, Scene::nodetree, nodeUpdateID(), NULL, Image::ok, ImageUser::ok, Image::packedfile, ImageUser::pass, pf, Image::source, Image::type, ImBuf::x, and ImBuf::y.
Referenced by ED_space_image_set(), image_new_exec(), image_open_exec(), image_reload_exec(), image_replace_exec(), node_composit_exec_composite(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), and unpackImage().
void BKE_image_user_calc_frame (struct ImageUser * iuser, int cfra, int fieldnr)
Definition at line 2630 of file image.c.
References BKE_image_user_get_frame(), ImageUser::flag, ImageUser::framenr, IMA_ANIM_ALWAYS, IMA_ANIM_REFRESHED, and ImageUser::ok.
Referenced by draw_bgpic(), ED_image_update_frame(), image_refresh(), init_render_texture(), modifier_init_texture(), node_composit_exec_image(), node_composit_exec_splitviewer(), node_composit_exec_viewer(), RE_init_sample_material(), set_frames_cb(), and space_view3d_listener().
int BKE_image_user_get_frame (const struct ImageUser * iuser, int cfra, int fieldnr)
Referenced by BKE_image_user_calc_frame(), image_info(), and node_composit_buts_image().
struct Image* BKE_image_verify_viewer (int type, const char * name) [read]
Definition at line 1765 of file image.c.
References G, Image::id, id_us_plus(), IMA_SRC_VIEWER, image_alloc(), ID::next, NULL, Image::source, Image::type, and ID::us.
Referenced by draw_nodespace_back_pix(), ED_node_set_active(), node_composit_exec_composite(), render_view_open(), sample_apply(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), and snode_bg_viewmove_invoke().
void BKE_imformat_defaults (struct ImageFormatData * im_format)
Definition at line 1166 of file image.c.
References ImageFormatData::compress, ImageFormatData::imtype, ImageFormatData::planes, ImageFormatData::quality, R_IMF_IMTYPE_PNG, and R_IMF_PLANES_RGB.
Referenced by save_image_options_defaults(), and screenshot_data_create().
char BKE_imtype_from_arg (const char * arg)
Definition at line 1037 of file image.c.
References R_IMF_IMTYPE_AVICODEC, R_IMF_IMTYPE_AVIJPEG, R_IMF_IMTYPE_AVIRAW, R_IMF_IMTYPE_BMP, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_DDS, R_IMF_IMTYPE_DPX, R_IMF_IMTYPE_FFMPEG, R_IMF_IMTYPE_FRAMESERVER, R_IMF_IMTYPE_INVALID, R_IMF_IMTYPE_IRIS, R_IMF_IMTYPE_IRIZ, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_JPEG90, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_PNG, R_IMF_IMTYPE_QUICKTIME, R_IMF_IMTYPE_RADHDR, R_IMF_IMTYPE_RAWTGA, R_IMF_IMTYPE_TARGA, and R_IMF_IMTYPE_TIFF.
Referenced by set_image_type().
int BKE_imtype_is_movie (const char imtype)
Definition at line 930 of file image.c.
References R_IMF_IMTYPE_AVICODEC, R_IMF_IMTYPE_AVIJPEG, R_IMF_IMTYPE_AVIRAW, R_IMF_IMTYPE_FFMPEG, R_IMF_IMTYPE_FRAMESERVER, R_IMF_IMTYPE_H264, R_IMF_IMTYPE_QUICKTIME, R_IMF_IMTYPE_THEORA, and R_IMF_IMTYPE_XVID.
Referenced by do_write_image_or_movie(), ntreeCompositOutputFileAddSocket(), RE_BlenderAnim(), RE_BlenderFrame(), RE_InitState(), screen_opengl_render_anim_initialize(), screen_opengl_render_anim_step(), screen_opengl_render_end(), screen_opengl_render_init(), screen_render_exec(), screen_render_invoke(), and screenshot_startjob().
int BKE_imtype_supports_compress (const char imtype)
Definition at line 957 of file image.c.
References R_IMF_IMTYPE_PNG.
Referenced by uiTemplateImageSettings().
int BKE_imtype_supports_quality (const char imtype)
Definition at line 966 of file image.c.
References R_IMF_IMTYPE_AVIJPEG, R_IMF_IMTYPE_JP2, and R_IMF_IMTYPE_JPEG90.
Referenced by uiTemplateImageSettings().
int BKE_imtype_supports_zbuf (const char imtype)
Definition at line 947 of file image.c.
References R_IMF_IMTYPE_IRIZ, and R_IMF_IMTYPE_OPENEXR.
Referenced by uiTemplateImageSettings().
int BKE_imtype_to_ftype (const char imtype)
Definition at line 847 of file image.c.
References BMP, IMAGIC, JPG, OPENEXR, PNG, R_IMF_IMTYPE_BMP, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_DDS, R_IMF_IMTYPE_DPX, R_IMF_IMTYPE_IRIS, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_PNG, R_IMF_IMTYPE_RADHDR, R_IMF_IMTYPE_RAWTGA, R_IMF_IMTYPE_TARGA, R_IMF_IMTYPE_TIFF, RAWTGA, and TGA.
char BKE_imtype_valid_channels (const char imtype)
Definition at line 977 of file image.c.
References IMA_CHAN_FLAG_ALPHA, IMA_CHAN_FLAG_BW, IMA_CHAN_FLAG_RGB, R_IMF_IMTYPE_DDS, R_IMF_IMTYPE_IRIS, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_JPEG90, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_PNG, R_IMF_IMTYPE_QUICKTIME, R_IMF_IMTYPE_RADHDR, R_IMF_IMTYPE_RAWTGA, R_IMF_IMTYPE_TARGA, and R_IMF_IMTYPE_TIFF.
char BKE_imtype_valid_depths (const char imtype)
Definition at line 1011 of file image.c.
References R_IMF_CHAN_DEPTH_12, R_IMF_CHAN_DEPTH_16, R_IMF_CHAN_DEPTH_32, R_IMF_CHAN_DEPTH_8, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_DPX, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_RADHDR, and R_IMF_IMTYPE_TIFF.
Referenced by imtype_best_depth(), render_result_rect_to_ibuf(), and uiTemplateImageSettings().
void BKE_makepicstring (char * string, const char * base, const char * relbase, int frame, const char imtype, const short use_ext, const short use_frames)
Definition at line 1705 of file image.c.
References BKE_add_image_extension(), BLI_path_abs(), BLI_path_frame(), BLI_strncpy(), FILE_MAX, and NULL.
Referenced by do_write_image_or_movie(), exec_output_file_multilayer(), exec_output_file_singlelayer(), RE_BlenderAnim(), RE_BlenderFrame(), screen_opengl_render_anim_step(), screen_opengl_render_apply(), and screenshot_startjob().
void BKE_stamp_buf (struct Scene * scene, struct Object * camera, unsigned char * rect, float * rectf, int width, int height, int channels)
Definition at line 1327 of file image.c.
References RenderData::bg_stamp, BLF_buffer(), BLF_buffer_col(), BLF_descender(), BLF_draw_buffer(), BLF_height_max(), blf_mono_font_render, BLF_position(), BLF_size(), BLF_width_and_height(), BLF_width_max(), buf_rectfill_area(), BUFF_MARGIN_X, BUFF_MARGIN_Y, StampData::camera, StampData::cameralens, StampData::date, RenderData::fg_stamp, StampData::file, StampData::frame, StampData::marker, mono, StampData::note, NULL, Scene::r, StampData::rendertime, StampData::scene, RenderData::stamp_font_id, stampdata(), StampData::strip, and StampData::time.
Referenced by renderresult_stampinfo(), and screen_opengl_render_apply().
void BKE_stamp_info (struct Scene * scene, struct Object * camera, struct ImBuf * ibuf)
Definition at line 1522 of file image.c.
References StampData::camera, StampData::cameralens, StampData::date, StampData::file, StampData::frame, IMB_metadata_change_field(), StampData::marker, StampData::note, StampData::rendertime, StampData::scene, stampdata(), StampData::strip, and StampData::time.
Referenced by BKE_write_ibuf_stamp().
int BKE_write_ibuf (struct ImBuf * ibuf, const char * name, struct ImageFormatData * imf)
Definition at line 1569 of file image.c.
References BLI_make_existing_file(), BMP, ImageFormatData::compress, ImageFormatData::depth, ELEM5, ImageFormatData::exr_codec, ImageFormatData::flag, ImBuf::ftype, IB_rect, IB_zbuf, IB_zbuffloat, IMAGIC, IMB_saveiff(), ImageFormatData::imtype, ImageFormatData::jp2_flag, JPG, NULL, OPENEXR, OPENEXR_COMPRESS, OPENEXR_HALF, PNG, ImageFormatData::quality, R_IMF_CHAN_DEPTH_12, R_IMF_CHAN_DEPTH_16, R_IMF_FLAG_ZBUF, R_IMF_IMTYPE_BMP, R_IMF_IMTYPE_CINEON, R_IMF_IMTYPE_DDS, R_IMF_IMTYPE_DPX, R_IMF_IMTYPE_FFMPEG, R_IMF_IMTYPE_H264, R_IMF_IMTYPE_IRIS, R_IMF_IMTYPE_JP2, R_IMF_IMTYPE_MULTILAYER, R_IMF_IMTYPE_OPENEXR, R_IMF_IMTYPE_PNG, R_IMF_IMTYPE_RADHDR, R_IMF_IMTYPE_RAWTGA, R_IMF_IMTYPE_TARGA, R_IMF_IMTYPE_THEORA, R_IMF_IMTYPE_TIFF, R_IMF_IMTYPE_XVID, R_IMF_JP2_FLAG_CINE_48, R_IMF_JP2_FLAG_CINE_PRESET, R_IMF_JP2_FLAG_YCC, RAWTGA, TGA, and ImBuf::zbuf_float.
Referenced by BKE_write_ibuf_as(), BKE_write_ibuf_stamp(), exec_output_file_singlelayer(), RE_WriteEnvmapResult(), screenshot_exec(), and screenshot_startjob().
int BKE_write_ibuf_as (struct ImBuf * ibuf, const char * name, struct ImageFormatData * imf, const short is_copy)
Definition at line 1675 of file image.c.
References BKE_write_ibuf(), ImBuf::ftype, ImageFormatData::planes, and ImBuf::planes.
Referenced by save_image_doit(), and screen_opengl_render_apply().
int BKE_write_ibuf_stamp (struct Scene * scene, struct Object * camera, struct ImBuf * ibuf, const char * name, struct ImageFormatData * imf)
Definition at line 1696 of file image.c.
References BKE_stamp_info(), BKE_write_ibuf(), Scene::r, R_STAMP_ALL, and RenderData::stamp.
Referenced by do_write_image_or_movie(), and screen_opengl_render_anim_step().
struct Image* copy_image (struct Image * ima) [read]
Definition at line 303 of file image.c.
References Image::animspeed, Image::aspx, Image::aspy, BLI_strncpy(), Image::flag, Image::gen_type, Image::gen_x, Image::gen_y, Image::id, image_alloc(), ID::name, Image::name, Image::source, Image::tpageflag, and Image::type.
Referenced by id_copy(), localize(), and make_local_image().
void free_image (struct Image * me)
Definition at line 201 of file image.c.
References BKE_icon_delete(), BKE_previewimg_free(), freePackedFile(), ID::icon_id, Image::id, IMA_MAX_RENDER_SLOT, image_free_buffers(), NULL, Image::packedfile, Image::preview, RE_FreeRenderResult(), and Image::renders.
Referenced by free_libblock().
void free_old_images (void)
Definition at line 693 of file image.c.
References Image::bindcode, ListBase::first, Image::flag, G, GPU_free_image(), Image::ibufs, Image::id, IMA_NOCOLLECT, image_free_buffers(), Image::lastused, ID::next, PIL_check_seconds_timer(), and Image::repbind.
Referenced by draw_object().
void image_de_interlace (struct Image * ima, int odd)
Definition at line 160 of file image.c.
References BKE_image_get_ibuf(), de_interlace_ng(), de_interlace_st(), and NULL.
void make_local_image (struct Image * ima)
Definition at line 330 of file image.c.
References BKE_id_lib_local_paths(), Main::brush, CD_MTEXPOLY, CD_MTFACE, Brush::clone, copy_image(), CustomDataLayer::data, extern_local_image(), FALSE, Mesh::fdata, ListBase::first, G, i, Mesh::id, Brush::id, Tex::id, Image::id, id_clear_lib_data(), id_lib_extern(), Tex::ima, BrushClone::image, CustomData::layers, ID::lib, Main::mesh, Mesh::mtface, Mesh::mtpoly, ID::next, NULL, Main::tex, Mesh::totface, CustomData::totlayer, Mesh::totpoly, MTFace::tpage, MTexPoly::tpage, TRUE, CustomDataLayer::type, and ID::us.
Referenced by id_make_local().
struct anim* openanim (const char * name, int flags, int streamindex) [read]
Definition at line 1720 of file image.c.
References BLI_exists(), IMB_anim_absolute(), IMB_free_anim(), IMB_freeImBuf(), IMB_open_anim(), IMB_PROXY_NONE, IMB_TC_NONE, and NULL.
Referenced by image_load_movie_file(), movieclip_open_anim_file(), reload_sequence_new_file(), seq_open_anim_file(), seq_proxy_fetch(), and sequencer_add_movie_strip().
void tag_image_time (struct Image * ima)
Definition at line 672 of file image.c.
References Image::lastused, and PIL_check_seconds_timer().
Referenced by BKE_image_acquire_ibuf(), and multitex().