Blender: MT_Point2.inl File Reference
MT_Point2.inl File Reference
#include "MT_Optimize.h"
Functions
GEN_INLINE MT_Point2 operator+ (const MT_Point2 &p, const MT_Vector2 &v)
GEN_INLINE MT_Point2 operator- (const MT_Point2 &p, const MT_Vector2 &v)
GEN_INLINE MT_Vector2 operator- (const MT_Point2 &p1, const MT_Point2 &p2)
GEN_INLINE MT_Scalar MT_distance (const MT_Point2 &p1, const MT_Point2 &p2)
GEN_INLINE MT_Scalar MT_distance2 (const MT_Point2 &p1, const MT_Point2 &p2)
GEN_INLINE MT_Point2 MT_lerp (const MT_Point2 &p1, const MT_Point2 &p2, MT_Scalar t)
Function Documentation
GEN_INLINE MT_Scalar MT_distance (const MT_Point2 & p1, const MT_Point2 & p2)
Definition at line 43 of file MT_Point2.inl.
References MT_Point2::distance().
GEN_INLINE MT_Scalar MT_distance2 (const MT_Point2 & p1, const MT_Point2 & p2)
Definition at line 47 of file MT_Point2.inl.
References MT_Point2::distance2().
GEN_INLINE MT_Point2 MT_lerp (const MT_Point2 & p1, const MT_Point2 & p2, MT_Scalar t)
Definition at line 51 of file MT_Point2.inl.
References MT_Point2::lerp().
GEN_INLINE MT_Point2 operator+ (const MT_Point2 & p, const MT_Vector2 & v)
Definition at line 31 of file MT_Point2.inl.
GEN_INLINE MT_Vector2 operator- (const MT_Point2 & p1, const MT_Point2 & p2)
Definition at line 39 of file MT_Point2.inl.
GEN_INLINE MT_Point2 operator- (const MT_Point2 & p, const MT_Vector2 & v)
Definition at line 35 of file MT_Point2.inl.