Blender: rna_brush.c File Reference
rna_brush.c File Reference
RNA
#include <stdlib.h>
#include <assert.h>
#include "RNA_define.h"
#include "rna_internal.h"
#include "DNA_brush_types.h"
#include "DNA_texture_types.h"
#include "DNA_scene_types.h"
#include "DNA_object_types.h"
#include "BLI_math.h"
#include "IMB_imbuf.h"
#include "WM_types.h"
Defines
#define BRUSH_CAPABILITY(prop_name_, ui_name_)
Functions
static void rna_def_brush_texture_slot (BlenderRNA *brna)
static void rna_def_sculpt_capabilities (BlenderRNA *brna)
static void rna_def_brush (BlenderRNA *brna)
static void rna_def_operator_stroke_element (BlenderRNA *brna)
void RNA_def_brush (BlenderRNA *brna)
Variables
static EnumPropertyItem prop_direction_items []
EnumPropertyItem brush_sculpt_tool_items []
EnumPropertyItem brush_vertex_tool_items []
EnumPropertyItem brush_image_tool_items []
Detailed Description
Definition in file rna_brush.c.
Define Documentation
#define BRUSH_CAPABILITY (prop_name_, ui_name_)
Value:
prop = RNA_def_property(srna, #prop_name_,                          \
                            PROP_BOOLEAN, PROP_NONE);                   \
    RNA_def_property_clear_flag(prop, PROP_EDITABLE);                   \
    RNA_def_property_boolean_funcs(prop, "rna_SculptCapabilities_"      \
                                   #prop_name_ "_get", NULL);           \
    RNA_def_property_ui_text(prop, ui_name_, NULL)
Referenced by rna_def_sculpt_capabilities().
Function Documentation
static void rna_def_brush (BlenderRNA * brna) [static]
Definition at line 435 of file rna_brush.c.
References BRUSH_ACCUMULATE, BRUSH_ADAPTIVE_SPACE, BRUSH_AIRBRUSH, BRUSH_ALPHA_PRESSURE, BRUSH_ANCHORED, BRUSH_CUSTOM_ICON, BRUSH_EDGE_TO_EDGE, BRUSH_FIXED_TEX, BRUSH_FRONTFACE, BRUSH_INVERSE_SMOOTH_PRESSURE, BRUSH_JITTER_PRESSURE, BRUSH_LOCK_ALPHA, BRUSH_LOCK_SIZE, BRUSH_OFFSET_PRESSURE, BRUSH_ORIGINAL_NORMAL, BRUSH_PERSISTENT, BRUSH_PLANE_TRIM, BRUSH_RAKE, BRUSH_RANDOM_ROTATION, BRUSH_RESTORE_MESH, BRUSH_SIZE_PRESSURE, BRUSH_SMOOTH_STROKE, BRUSH_SPACE, BRUSH_SPACE_ATTEN, BRUSH_SPACING_PRESSURE, BRUSH_TEXTURE_OVERLAY, BRUSH_TORUS, FLT_MAX, IMB_BLEND_ADD, IMB_BLEND_ADD_ALPHA, IMB_BLEND_DARKEN, IMB_BLEND_ERASE_ALPHA, IMB_BLEND_LIGHTEN, IMB_BLEND_MIX, IMB_BLEND_MUL, IMB_BLEND_SUB, MAX_BRUSH_PIXEL_RADIUS, NC_SPACE, NC_TEXTURE, ND_SPACE_IMAGE, NULL, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, PROP_BOOLEAN, PROP_COLOR, PROP_COLOR_GAMMA, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FILEPATH, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_PERCENTAGE, PROP_POINTER, PROP_STRING, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_default(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), SCULPT_DISP_DIR_AREA, SCULPT_DISP_DIR_VIEW, SCULPT_DISP_DIR_X, SCULPT_DISP_DIR_Y, and SCULPT_DISP_DIR_Z.
Referenced by RNA_def_brush().
void RNA_def_brush (BlenderRNA * brna)
Definition at line 936 of file rna_brush.c.
References rna_def_brush(), rna_def_brush_texture_slot(), rna_def_operator_stroke_element(), and rna_def_sculpt_capabilities().
static void rna_def_brush_texture_slot (BlenderRNA * brna) [static]
Definition at line 368 of file rna_brush.c.
References M_PI, MTEX_MAP_MODE_3D, MTEX_MAP_MODE_FIXED, MTEX_MAP_MODE_TILED, NULL, PROP_ANGLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_brush().
static void rna_def_operator_stroke_element (BlenderRNA * brna) [static]
Definition at line 892 of file rna_brush.c.
References PROP_BOOLEAN, PROP_FLOAT, PROP_IDPROPERTY, PROP_NONE, PROP_UNSIGNED, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_flag(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
Referenced by RNA_def_brush().
static void rna_def_sculpt_capabilities (BlenderRNA * brna) [static]
Definition at line 396 of file rna_brush.c.
References BRUSH_CAPABILITY, NULL, RNA_def_struct(), RNA_def_struct_nested(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_brush().
Variable Documentation
EnumPropertyItem brush_image_tool_items[]
Initial value:
 {
    {PAINT_TOOL_DRAW, "DRAW", ICON_BRUSH_TEXDRAW, "Draw", ""},
    {PAINT_TOOL_SOFTEN, "SOFTEN", ICON_BRUSH_SOFTEN, "Soften", ""},
    {PAINT_TOOL_SMEAR, "SMEAR", ICON_BRUSH_SMEAR, "Smear", ""},
    {PAINT_TOOL_CLONE, "CLONE", ICON_BRUSH_CLONE, "Clone", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 82 of file rna_brush.c.
Referenced by PAINT_OT_brush_select(), and ui_id_brush_get_icon().
EnumPropertyItem brush_sculpt_tool_items[]
Initial value:
 {
    {SCULPT_TOOL_BLOB, "BLOB", ICON_BRUSH_BLOB, "Blob", ""},
    {SCULPT_TOOL_CLAY, "CLAY", ICON_BRUSH_CLAY, "Clay", ""},
    {SCULPT_TOOL_CLAY_STRIPS, "CLAY_STRIPS", ICON_BRUSH_CLAY_STRIPS, "Clay Strips", ""},
    {SCULPT_TOOL_CREASE, "CREASE",ICON_BRUSH_CREASE, "Crease", ""},
    {SCULPT_TOOL_DRAW, "DRAW", ICON_BRUSH_SCULPT_DRAW, "Draw", ""},
    {SCULPT_TOOL_FILL, "FILL", ICON_BRUSH_FILL, "Fill", ""},
    {SCULPT_TOOL_FLATTEN, "FLATTEN", ICON_BRUSH_FLATTEN, "Flatten", ""},
    {SCULPT_TOOL_GRAB, "GRAB", ICON_BRUSH_GRAB, "Grab", ""},
    {SCULPT_TOOL_INFLATE, "INFLATE", ICON_BRUSH_INFLATE, "Inflate", ""},
    {SCULPT_TOOL_LAYER, "LAYER", ICON_BRUSH_LAYER, "Layer", ""},
    {SCULPT_TOOL_NUDGE, "NUDGE", ICON_BRUSH_NUDGE, "Nudge", ""},
    {SCULPT_TOOL_PINCH, "PINCH", ICON_BRUSH_PINCH, "Pinch", ""},
    {SCULPT_TOOL_ROTATE, "ROTATE", ICON_BRUSH_ROTATE, "Rotate", ""},
    {SCULPT_TOOL_SCRAPE, "SCRAPE", ICON_BRUSH_SCRAPE, "Scrape", ""},
    {SCULPT_TOOL_SMOOTH, "SMOOTH", ICON_BRUSH_SMOOTH, "Smooth", ""},
    {SCULPT_TOOL_SNAKE_HOOK, "SNAKE_HOOK", ICON_BRUSH_SNAKE_HOOK, "Snake Hook", ""},
    {SCULPT_TOOL_THUMB, "THUMB", ICON_BRUSH_THUMB, "Thumb", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 51 of file rna_brush.c.
Referenced by PAINT_OT_brush_select(), and ui_id_brush_get_icon().
EnumPropertyItem brush_vertex_tool_items[]
Initial value:
 {
    {PAINT_BLEND_MIX, "MIX", ICON_BRUSH_MIX, "Mix", "Use mix blending mode while painting"},
    {PAINT_BLEND_ADD, "ADD", ICON_BRUSH_ADD, "Add", "Use add blending mode while painting"},
    {PAINT_BLEND_SUB, "SUB", ICON_BRUSH_SUBTRACT, "Subtract", "Use subtract blending mode while painting"},
    {PAINT_BLEND_MUL, "MUL", ICON_BRUSH_MULTIPLY, "Multiply", "Use multiply blending mode while painting"},
    {PAINT_BLEND_BLUR, "BLUR", ICON_BRUSH_BLUR, "Blur", "Blur the color with surrounding values"},
    {PAINT_BLEND_LIGHTEN, "LIGHTEN", ICON_BRUSH_LIGHTEN, "Lighten", "Use lighten blending mode while painting"},
    {PAINT_BLEND_DARKEN, "DARKEN", ICON_BRUSH_DARKEN, "Darken", "Use darken blending mode while painting"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 72 of file rna_brush.c.
Referenced by PAINT_OT_brush_select(), and ui_id_brush_get_icon().
EnumPropertyItem prop_direction_items[] [static]
Initial value:
 {
    {0, "ADD", 0, "Add", "Add effect of brush"},
    {BRUSH_DIR_IN, "SUBTRACT", 0, "Subtract", "Subtract effect of brush"},
    {0, NULL, 0, NULL, NULL}}
Definition at line 46 of file rna_brush.c.