Blender: TNT::Array2D< T > Class Template Reference
TNT::Array2D< T > Class Template Reference
#include <tnt_array2d.h>
Public Types
typedef T value_type
Public Member Functions
Array2D ()
Array2D (int m, int n)
Array2D (int m, int n, T *a)
Array2D (int m, int n, const T &a)
Array2D (const Array2D &A)
operator T ** ()
operator const T ** ()
Array2D & operator= (const T &a)
Array2D & operator= (const Array2D &A)
Array2D & ref (const Array2D &A)
Array2D copy () const
Array2D & inject (const Array2D &A)
T * operator[] (int i)
const T * operator[] (int i) const
int dim1 () const
int dim2 () const
~Array2D ()
int ref_count ()
int ref_count_data ()
int ref_count_dim1 ()
Array2D subarray (int i0, int i1, int j0, int j1)
Detailed Description
template<class T>
class TNT::Array2D< T >
Definition at line 40 of file tnt_array2d.h.
Member Typedef Documentation
template<class T> typedef T TNT::Array2D< T >::value_type
Definition at line 55 of file tnt_array2d.h.
Constructor & Destructor Documentation
template<class T > TNT::Array2D< T >::Array2D ()
Definition at line 86 of file tnt_array2d.h.
template<class T > TNT::Array2D< T >::Array2D (int m, int n)
Definition at line 96 of file tnt_array2d.h.
References i, p, and T.
template<class T> TNT::Array2D< T >::Array2D (int m, int n, T * a)
Definition at line 128 of file tnt_array2d.h.
References i, p, and T.
template<class T> TNT::Array2D< T >::Array2D (int m, int n, const T & a)
Definition at line 112 of file tnt_array2d.h.
References i, p, and T.
template<class T> TNT::Array2D< T >::Array2D (const Array2D< T > & A) [inline]
Definition at line 89 of file tnt_array2d.h.
template<class T > TNT::Array2D< T >::~Array2D ()
Definition at line 241 of file tnt_array2d.h.
Member Function Documentation
template<class T > Array2D< T > TNT::Array2D< T >::copy () const
Definition at line 183 of file tnt_array2d.h.
References A, and i.
template<class T > int TNT::Array2D< T >::dim1 () const [inline]
Definition at line 234 of file tnt_array2d.h.
Referenced by TNT::matmult(), TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), TNT::operator/=(), and JAMA::LU< Real >::solve().
template<class T > int TNT::Array2D< T >::dim2 () const [inline]
Definition at line 237 of file tnt_array2d.h.
Referenced by JAMA::Eigenvalue< Real >::Eigenvalue(), TNT::matmult(), TNT::operator*(), TNT::operator*=(), TNT::operator+(), TNT::operator+=(), TNT::operator-(), TNT::operator-=(), TNT::operator/(), TNT::operator/=(), and JAMA::LU< Real >::solve().
template<class T > Array2D< T > & TNT::Array2D< T >::inject (const Array2D< T > & A)
Definition at line 197 of file tnt_array2d.h.
References i.
template<class T > TNT::Array2D< T >::operator const T ** () [inline]
Definition at line 252 of file tnt_array2d.h.
template<class T > TNT::Array2D< T >::operator T ** () [inline]
Definition at line 247 of file tnt_array2d.h.
template<class T> Array2D< T > & TNT::Array2D< T >::operator= (const Array2D< T > & A) [inline]
Definition at line 228 of file tnt_array2d.h.
template<class T> Array2D< T > & TNT::Array2D< T >::operator= (const T & a) [inline]
Definition at line 169 of file tnt_array2d.h.
References i.
template<class T > T * TNT::Array2D< T >::operator[] (int i) [inline]
Definition at line 144 of file tnt_array2d.h.
References assert, and i.
template<class T > const T * TNT::Array2D< T >::operator[] (int i) const [inline]
Definition at line 157 of file tnt_array2d.h.
References assert, and i.
template<class T > Array2D< T > & TNT::Array2D< T >::ref (const Array2D< T > & A) [inline]
Definition at line 212 of file tnt_array2d.h.
template<class T > int TNT::Array2D< T >::ref_count () [inline]
Definition at line 292 of file tnt_array2d.h.
template<class T > int TNT::Array2D< T >::ref_count_data () [inline]
Definition at line 300 of file tnt_array2d.h.
template<class T > int TNT::Array2D< T >::ref_count_dim1 () [inline]
Definition at line 306 of file tnt_array2d.h.
template<class T > Array2D< T > TNT::Array2D< T >::subarray (int i0, int i1, int j0, int j1)
Create a new view to a subarray defined by the boundaries [i0][i0] and [i1][j1]. The size of the subarray is (i1-i0) by (j1-j0). If either of these lengths are zero or negative, the subarray view is null.
Definition at line 266 of file tnt_array2d.h.
References A, i, p, and T.
The documentation for this class was generated from the following file:
tnt_array2d.h