Blender: rna_modifier.c File Reference
rna_modifier.c File Reference
RNA
#include <float.h>
#include <limits.h>
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_enum_types.h"
#include "rna_internal.h"
#include "DNA_armature_types.h"
#include "DNA_mesh_types.h"
#include "DNA_modifier_types.h"
#include "DNA_object_types.h"
#include "DNA_object_force.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_math.h"
#include "BLF_translation.h"
#include "BKE_animsys.h"
#include "BKE_bmesh.h"
#include "BKE_dynamicpaint.h"
#include "BKE_multires.h"
#include "BKE_smoke.h"
#include "WM_api.h"
#include "WM_types.h"
Functions
static void rna_def_property_subdivision_common (StructRNA *srna, const char type[])
static void rna_def_modifier_subsurf (BlenderRNA *brna)
static void rna_def_modifier_generic_map_info (StructRNA *srna)
static void rna_def_modifier_warp (BlenderRNA *brna)
static void rna_def_modifier_multires (BlenderRNA *brna)
static void rna_def_modifier_lattice (BlenderRNA *brna)
static void rna_def_modifier_curve (BlenderRNA *brna)
static void rna_def_modifier_build (BlenderRNA *brna)
static void rna_def_modifier_mirror (BlenderRNA *brna)
static void rna_def_modifier_decimate (BlenderRNA *brna)
static void rna_def_modifier_wave (BlenderRNA *brna)
static void rna_def_modifier_armature (BlenderRNA *brna)
static void rna_def_modifier_hook (BlenderRNA *brna)
static void rna_def_modifier_softbody (BlenderRNA *brna)
static void rna_def_modifier_boolean (BlenderRNA *brna)
static void rna_def_modifier_array (BlenderRNA *brna)
static void rna_def_modifier_edgesplit (BlenderRNA *brna)
static void rna_def_modifier_displace (BlenderRNA *brna)
static void rna_def_modifier_uvproject (BlenderRNA *brna)
static void rna_def_modifier_smooth (BlenderRNA *brna)
static void rna_def_modifier_cast (BlenderRNA *brna)
static void rna_def_modifier_meshdeform (BlenderRNA *brna)
static void rna_def_modifier_particlesystem (BlenderRNA *brna)
static void rna_def_modifier_particleinstance (BlenderRNA *brna)
static void rna_def_modifier_explode (BlenderRNA *brna)
static void rna_def_modifier_cloth (BlenderRNA *brna)
static void rna_def_modifier_smoke (BlenderRNA *brna)
static void rna_def_modifier_dynamic_paint (BlenderRNA *brna)
static void rna_def_modifier_collision (BlenderRNA *brna)
static void rna_def_modifier_bevel (BlenderRNA *brna)
static void rna_def_modifier_shrinkwrap (BlenderRNA *brna)
static void rna_def_modifier_fluidsim (BlenderRNA *brna)
static void rna_def_modifier_mask (BlenderRNA *brna)
static void rna_def_modifier_simpledeform (BlenderRNA *brna)
static void rna_def_modifier_surface (BlenderRNA *brna)
static void rna_def_modifier_solidify (BlenderRNA *brna)
static void rna_def_modifier_screw (BlenderRNA *brna)
static void rna_def_modifier_weightvg_mask (BlenderRNA *brna, StructRNA *srna)
static void rna_def_modifier_weightvgedit (BlenderRNA *brna)
static void rna_def_modifier_weightvgmix (BlenderRNA *brna)
static void rna_def_modifier_weightvgproximity (BlenderRNA *brna)
static void rna_def_modifier_remesh (BlenderRNA *brna)
static void rna_def_modifier_ocean (BlenderRNA *brna)
void RNA_def_modifier (BlenderRNA *brna)
Variables
EnumPropertyItem modifier_type_items []
Detailed Description
Definition in file rna_modifier.c.
Function Documentation
void RNA_def_modifier (BlenderRNA * brna)
Definition at line 3158 of file rna_modifier.c.
References eModifierMode_ApplyOnSpline, eModifierMode_Editmode, eModifierMode_Expanded, eModifierMode_OnCage, eModifierMode_Realtime, eModifierMode_Render, NA_RENAME, NC_OBJECT, ND_MODIFIER, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_LIB_EXCEPTION, PROP_NONE, PROP_STRING, rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_surface(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_string_funcs(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
static void rna_def_modifier_armature (BlenderRNA * brna) [static]
Definition at line 1259 of file rna_modifier.c.
References ARM_DEF_ENVELOPE, ARM_DEF_INVERT_VGROUP, ARM_DEF_QUATERNION, ARM_DEF_VGROUP, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_array (BlenderRNA * brna) [static]
Definition at line 1401 of file rna_modifier.c.
References FLT_MAX, MOD_ARR_FITCURVE, MOD_ARR_FITLENGTH, MOD_ARR_FIXEDCOUNT, MOD_ARR_MERGE, MOD_ARR_MERGEFINAL, MOD_ARR_OFF_CONST, MOD_ARR_OFF_OBJ, MOD_ARR_OFF_RELATIVE, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, PROP_TRANSLATION, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_TRANSLATION_PREC_DEFAULT.
Referenced by RNA_def_modifier().
static void rna_def_modifier_bevel (BlenderRNA * brna) [static]
Definition at line 2122 of file rna_modifier.c.
References BME_BEVEL_ANGLE, BME_BEVEL_DIST, BME_BEVEL_EMAX, BME_BEVEL_EMIN, BME_BEVEL_EVEN, BME_BEVEL_VERT, BME_BEVEL_WEIGHT, DEG2RAD, FLT_MAX, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_boolean (BlenderRNA * brna) [static]
Definition at line 1372 of file rna_modifier.c.
References eBooleanModifierOp_Difference, eBooleanModifierOp_Intersect, eBooleanModifierOp_Union, NULL, PROP_EDITABLE, PROP_ENUM, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_build (BlenderRNA * brna) [static]
Definition at line 1012 of file rna_modifier.c.
References MAXFRAMEF, MINAFRAMEF, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_TIME, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_cast (BlenderRNA * brna) [static]
Definition at line 1721 of file rna_modifier.c.
References FLT_MAX, MOD_CAST_SIZE_FROM_RADIUS, MOD_CAST_TYPE_CUBOID, MOD_CAST_TYPE_CYLINDER, MOD_CAST_TYPE_SPHERE, MOD_CAST_USE_OB_TRANSFORM, MOD_CAST_X, MOD_CAST_Y, MOD_CAST_Z, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_cloth (BlenderRNA * brna) [static]
Definition at line 2018 of file rna_modifier.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_collision (BlenderRNA * brna) [static]
Definition at line 2104 of file rna_modifier.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_curve (BlenderRNA * brna) [static]
Definition at line 973 of file rna_modifier.c.
References MOD_CURVE_NEGX, MOD_CURVE_NEGY, MOD_CURVE_NEGZ, MOD_CURVE_POSX, MOD_CURVE_POSY, MOD_CURVE_POSZ, NULL, PROP_EDITABLE, PROP_ENUM, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_decimate (BlenderRNA * brna) [static]
Definition at line 1109 of file rna_modifier.c.
References NULL, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_displace (BlenderRNA * brna) [static]
Definition at line 1549 of file rna_modifier.c.
References FLT_MAX, MOD_DISP_DIR_NOR, MOD_DISP_DIR_RGB_XYZ, MOD_DISP_DIR_X, MOD_DISP_DIR_Y, MOD_DISP_DIR_Z, NULL, prop_direction_items, PROP_DISTANCE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_STRING, rna_def_modifier_generic_map_info(), RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_dynamic_paint (BlenderRNA * brna) [static]
Definition at line 2079 of file rna_modifier.c.
References NULL, PROP_ANIMATABLE, prop_dynamicpaint_type_items, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_edgesplit (BlenderRNA * brna) [static]
Definition at line 1514 of file rna_modifier.c.
References DEG2RAD, MOD_EDGESPLIT_FROMANGLE, MOD_EDGESPLIT_FROMFLAG, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_funcs(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_explode (BlenderRNA * brna) [static]
Definition at line 1966 of file rna_modifier.c.
References eExplodeFlag_Alive, eExplodeFlag_Dead, eExplodeFlag_EdgeCut, eExplodeFlag_PaSize, eExplodeFlag_Unborn, MAX_CUSTOMDATA_LAYER_NAME, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_fluidsim (BlenderRNA * brna) [static]
Definition at line 2308 of file rna_modifier.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_generic_map_info (StructRNA * srna) [static]
Definition at line 785 of file rna_modifier.c.
References MOD_DISP_MAP_GLOBAL, MOD_DISP_MAP_LOCAL, MOD_DISP_MAP_OBJECT, MOD_DISP_MAP_UV, NULL, PROP_EDITABLE, PROP_ENUM, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, prop_texture_coordinates_items, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_modifier_displace(), rna_def_modifier_warp(), and rna_def_modifier_wave().
static void rna_def_modifier_hook (BlenderRNA * brna) [static]
Definition at line 1309 of file rna_modifier.c.
References FLT_MAX, NULL, PROP_DISTANCE, PROP_EDITABLE, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_lattice (BlenderRNA * brna) [static]
Definition at line 943 of file rna_modifier.c.
References FLT_MAX, NULL, PROP_EDITABLE, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_mask (BlenderRNA * brna) [static]
Definition at line 2324 of file rna_modifier.c.
References MOD_MASK_INV, MOD_MASK_MODE_ARM, MOD_MASK_MODE_VGROUP, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_meshdeform (BlenderRNA * brna) [static]
Definition at line 1803 of file rna_modifier.c.
References MOD_MDEF_DYNAMIC_BIND, MOD_MDEF_INVERT_VGROUP, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_mirror (BlenderRNA * brna) [static]
Definition at line 1045 of file rna_modifier.c.
References FLT_MAX, MOD_MIR_AXIS_X, MOD_MIR_AXIS_Y, MOD_MIR_AXIS_Z, MOD_MIR_CLIPPING, MOD_MIR_MIRROR_U, MOD_MIR_MIRROR_V, MOD_MIR_NO_MERGE, MOD_MIR_VGROUP, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_multires (BlenderRNA * brna) [static]
Definition at line 886 of file rna_modifier.c.
References eMultiresModifierFlag_ControlEdges, eMultiresModifierFlag_PlainUv, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_FILEPATH, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_string_funcs(), rna_def_property_subdivision_common(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_ocean (BlenderRNA * brna) [static]
Definition at line 2975 of file rna_modifier.c.
References FLT_MAX, MOD_OCEAN_GENERATE_FOAM, MOD_OCEAN_GENERATE_NORMALS, MOD_OCEAN_GEOM_DISPLACE, MOD_OCEAN_GEOM_GENERATE, MOD_OCEAN_GEOM_SIM_ONLY, NULL, PROP_ANGLE, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_DIRPATH, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, PROP_UNSIGNED, PROP_VELOCITY, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_particleinstance (BlenderRNA * brna) [static]
Definition at line 1878 of file rna_modifier.c.
References eParticleInstanceFlag_Alive, eParticleInstanceFlag_Children, eParticleInstanceFlag_Dead, eParticleInstanceFlag_KeepShape, eParticleInstanceFlag_Parents, eParticleInstanceFlag_Path, eParticleInstanceFlag_Unborn, eParticleInstanceFlag_UseSize, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_particlesystem (BlenderRNA * brna) [static]
Definition at line 1862 of file rna_modifier.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_remesh (BlenderRNA * brna) [static]
Definition at line 2917 of file rna_modifier.c.
References MOD_REMESH_CENTROID, MOD_REMESH_FLOOD_FILL, MOD_REMESH_MASS_POINT, MOD_REMESH_SHARP_FEATURES, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_screw (BlenderRNA * brna) [static]
Definition at line 2539 of file rna_modifier.c.
References FLT_MAX, M_PI, MOD_SCREW_NORMAL_CALC, MOD_SCREW_NORMAL_FLIP, MOD_SCREW_OBJECT_OFFSET, NULL, PROP_ANGLE, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_shrinkwrap (BlenderRNA * brna) [static]
Definition at line 2200 of file rna_modifier.c.
References FLT_MAX, MOD_SHRINKWRAP_CULL_TARGET_BACKFACE, MOD_SHRINKWRAP_CULL_TARGET_FRONTFACE, MOD_SHRINKWRAP_KEEP_ABOVE_SURFACE, MOD_SHRINKWRAP_NEAREST_SURFACE, MOD_SHRINKWRAP_NEAREST_VERTEX, MOD_SHRINKWRAP_PROJECT, MOD_SHRINKWRAP_PROJECT_ALLOW_NEG_DIR, MOD_SHRINKWRAP_PROJECT_ALLOW_POS_DIR, MOD_SHRINKWRAP_PROJECT_OVER_X_AXIS, MOD_SHRINKWRAP_PROJECT_OVER_Y_AXIS, MOD_SHRINKWRAP_PROJECT_OVER_Z_AXIS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_simpledeform (BlenderRNA * brna) [static]
Definition at line 2363 of file rna_modifier.c.
References FLT_MAX, MOD_SIMPLEDEFORM_LOCK_AXIS_X, MOD_SIMPLEDEFORM_LOCK_AXIS_Y, MOD_SIMPLEDEFORM_MODE_BEND, MOD_SIMPLEDEFORM_MODE_STRETCH, MOD_SIMPLEDEFORM_MODE_TAPER, MOD_SIMPLEDEFORM_MODE_TWIST, MOD_SIMPLEDEFORM_ORIGIN_LOCAL, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_smoke (BlenderRNA * brna) [static]
Definition at line 2043 of file rna_modifier.c.
References MOD_SMOKE_TYPE_COLL, MOD_SMOKE_TYPE_DOMAIN, MOD_SMOKE_TYPE_FLOW, NULL, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_smooth (BlenderRNA * brna) [static]
Definition at line 1675 of file rna_modifier.c.
References FLT_MAX, MOD_SMOOTH_X, MOD_SMOOTH_Y, MOD_SMOOTH_Z, NULL, PROP_BOOLEAN, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_softbody (BlenderRNA * brna) [static]
Definition at line 1349 of file rna_modifier.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_solidify (BlenderRNA * brna) [static]
Definition at line 2440 of file rna_modifier.c.
References FLT_MAX, MOD_SOLIDIFY_EVEN, MOD_SOLIDIFY_NORMAL_CALC, MOD_SOLIDIFY_RIM, MOD_SOLIDIFY_VGROUP_INV, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_subsurf (BlenderRNA * brna) [static]
Definition at line 751 of file rna_modifier.c.
References eSubsurfModifierFlag_ControlEdges, eSubsurfModifierFlag_SubsurfUv, NULL, PROP_BOOLEAN, PROP_INT, PROP_NONE, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_int_sdna(), rna_def_property_subdivision_common(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_surface (BlenderRNA * brna) [static]
Definition at line 2429 of file rna_modifier.c.
References RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_uvproject (BlenderRNA * brna) [static]
Definition at line 1597 of file rna_modifier.c.
References FLT_MAX, MOD_UVPROJECT_MAX, MOD_UVPROJECT_OVERRIDEIMAGE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_warp (BlenderRNA * brna) [static]
Definition at line 821 of file rna_modifier.c.
References eWarp_Falloff_Const, eWarp_Falloff_Curve, eWarp_Falloff_Linear, eWarp_Falloff_None, eWarp_Falloff_Root, eWarp_Falloff_Sharp, eWarp_Falloff_Smooth, eWarp_Falloff_Sphere, FLT_MAX, MOD_WARP_VOLUME_PRESERVE, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, rna_def_modifier_generic_map_info(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_wave (BlenderRNA * brna) [static]
Definition at line 1132 of file rna_modifier.c.
References FLT_MAX, MAXFRAMEF, MINAFRAMEF, MOD_WAVE_CYCL, MOD_WAVE_NORM, MOD_WAVE_NORM_X, MOD_WAVE_NORM_Y, MOD_WAVE_NORM_Z, MOD_WAVE_X, MOD_WAVE_Y, NULL, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, rna_def_modifier_generic_map_info(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_weightvg_mask (BlenderRNA * brna, StructRNA * srna) [static]
Definition at line 2617 of file rna_modifier.c.
References FLT_MAX, MOD_DISP_MAP_GLOBAL, MOD_DISP_MAP_LOCAL, MOD_DISP_MAP_OBJECT, MOD_DISP_MAP_UV, MOD_WVG_MASK_TEX_USE_ALPHA, MOD_WVG_MASK_TEX_USE_BLUE, MOD_WVG_MASK_TEX_USE_GREEN, MOD_WVG_MASK_TEX_USE_HUE, MOD_WVG_MASK_TEX_USE_INT, MOD_WVG_MASK_TEX_USE_RED, MOD_WVG_MASK_TEX_USE_SAT, MOD_WVG_MASK_TEX_USE_VAL, NULL, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), and rna_def_modifier_weightvgproximity().
static void rna_def_modifier_weightvgedit (BlenderRNA * brna) [static]
Definition at line 2681 of file rna_modifier.c.
References MOD_WVG_EDIT_ADD2VG, MOD_WVG_EDIT_REMFVG, MOD_WVG_MAPPING_CURVE, MOD_WVG_MAPPING_NONE, MOD_WVG_MAPPING_RANDOM, MOD_WVG_MAPPING_ROOT, MOD_WVG_MAPPING_SHARP, MOD_WVG_MAPPING_SMOOTH, MOD_WVG_MAPPING_SPHERE, MOD_WVG_MAPPING_STEP, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, rna_def_modifier_weightvg_mask(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_weightvgmix (BlenderRNA * brna) [static]
Definition at line 2759 of file rna_modifier.c.
References MOD_WVG_MIX_ADD, MOD_WVG_MIX_AVG, MOD_WVG_MIX_DIF, MOD_WVG_MIX_DIV, MOD_WVG_MIX_MUL, MOD_WVG_MIX_SET, MOD_WVG_MIX_SUB, MOD_WVG_SET_A, MOD_WVG_SET_ALL, MOD_WVG_SET_AND, MOD_WVG_SET_B, MOD_WVG_SET_OR, NULL, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_STRING, rna_def_modifier_weightvg_mask(), RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_modifier_weightvgproximity (BlenderRNA * brna) [static]
Definition at line 2830 of file rna_modifier.c.
References FLT_MAX, MOD_WVG_MAPPING_NONE, MOD_WVG_MAPPING_RANDOM, MOD_WVG_MAPPING_ROOT, MOD_WVG_MAPPING_SHARP, MOD_WVG_MAPPING_SMOOTH, MOD_WVG_MAPPING_SPHERE, MOD_WVG_MAPPING_STEP, MOD_WVG_PROXIMITY_GEOM_EDGES, MOD_WVG_PROXIMITY_GEOM_FACES, MOD_WVG_PROXIMITY_GEOM_VERTS, MOD_WVG_PROXIMITY_GEOMETRY, MOD_WVG_PROXIMITY_OBJECT, NULL, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_ENUM_FLAG, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_NONE, PROP_POINTER, PROP_STRING, rna_def_modifier_weightvg_mask(), RNA_def_property(), RNA_def_property_enum_default(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
Referenced by RNA_def_modifier().
static void rna_def_property_subdivision_common (StructRNA * srna, const char type[]) [static]
Definition at line 737 of file rna_modifier.c.
References NULL, PROP_ENUM, PROP_NONE, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_modifier_multires(), and rna_def_modifier_subsurf().
Variable Documentation
EnumPropertyItem modifier_type_items[]
Definition at line 59 of file rna_modifier.c.
Referenced by modifier_add_itemf(), OBJECT_OT_modifier_add(), and rna_def_object_modifiers().