Blender: info_draw.c File Reference
info_draw.c File Reference
info space
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <limits.h>
#include "BLF_api.h"
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "DNA_space_types.h"
#include "DNA_screen_types.h"
#include "BKE_report.h"
#include "MEM_guardedalloc.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "ED_datafiles.h"
#include "ED_types.h"
#include "UI_resources.h"
#include "info_intern.h"
#include "../space_info/textview.h"
Defines
#define USE_INFO_NEWLINE
Functions
static void info_report_color (unsigned char *fg, unsigned char *bg, Report *report, int bool)
static void report_textview_init__internal (TextViewContext *tvc)
static int report_textview_skip__internal (TextViewContext *tvc)
static int report_textview_begin (TextViewContext *tvc)
static void report_textview_end (TextViewContext *UNUSED(tvc))
static int report_textview_step (TextViewContext *tvc)
static int report_textview_line_get (struct TextViewContext *tvc, const char **line, int *len)
static int report_textview_line_color (struct TextViewContext *tvc, unsigned char fg[3], unsigned char bg[3])
static int info_textview_main__internal (struct SpaceInfo *sinfo, struct ARegion *ar, ReportList *reports, int draw, int mval[2], void **mouse_pick, int *pos_pick)
void * info_text_pick (struct SpaceInfo *sinfo, struct ARegion *ar, ReportList *reports, int mouse_y)
int info_textview_height (struct SpaceInfo *sinfo, struct ARegion *ar, ReportList *reports)
void info_textview_main (struct SpaceInfo *sinfo, struct ARegion *ar, ReportList *reports)
Detailed Description
Definition in file info_draw.c.
Define Documentation
#define USE_INFO_NEWLINE
Definition at line 64 of file info_draw.c.
Function Documentation
static void info_report_color (unsigned char * fg, unsigned char * bg, Report * report, int bool) [static]
Definition at line 66 of file info_draw.c.
References Report::flag, RPT_DEBUG_ALL, RPT_ERROR_ALL, RPT_INFO_ALL, RPT_OPERATOR_ALL, RPT_WARNING_ALL, SELECT, and Report::type.
Referenced by report_textview_line_color().
void* info_text_pick (struct SpaceInfo * sinfo, struct ARegion * ar, ReportList * reports, int mouse_y)
Definition at line 282 of file info_draw.c.
References info_textview_main__internal(), and NULL.
Referenced by borderselect_exec(), and select_report_pick_invoke().
int info_textview_height (struct SpaceInfo * sinfo, struct ARegion * ar, ReportList * reports)
Definition at line 295 of file info_draw.c.
References info_textview_main__internal(), and NULL.
Referenced by info_textview_update_rect().
void info_textview_main (struct SpaceInfo * sinfo, struct ARegion * ar, ReportList * reports)
Definition at line 301 of file info_draw.c.
References info_textview_main__internal(), and NULL.
Referenced by info_main_area_draw().
static int info_textview_main__internal (struct SpaceInfo * sinfo, struct ARegion * ar, ReportList * reports, int draw, int mval[2], void ** mouse_pick, int * pos_pick) [static]
Definition at line 252 of file info_draw.c.
References TextViewContext::arg1, TextViewContext::arg2, TextViewContext::begin, View2D::cur, TextViewContext::end, TextViewContext::lheight, TextViewContext::line_color, TextViewContext::line_get, report_textview_begin(), report_textview_end(), report_textview_line_color(), report_textview_line_get(), report_textview_step(), TextViewContext::sel_end, TextViewContext::sel_start, TextViewContext::step, textview_draw(), ARegion::v2d, TextViewContext::winx, ARegion::winx, TextViewContext::ymax, rctf::ymax, rctf::ymin, and TextViewContext::ymin.
Referenced by info_text_pick(), info_textview_height(), and info_textview_main().
static int report_textview_begin (TextViewContext * tvc) [static]
Definition at line 137 of file info_draw.c.
References TextViewContext::arg2, FALSE, TextViewContext::iter, TextViewContext::iter_char, TextViewContext::iter_tmp, ListBase::last, TextViewContext::lheight, ReportList::list, NULL, report_textview_init__internal(), report_textview_skip__internal(), TextViewContext::sel_end, TextViewContext::sel_start, and TRUE.
Referenced by info_textview_main__internal().
static void report_textview_end (TextViewContext * UNUSEDtvc) [static]
Definition at line 169 of file info_draw.c.
Referenced by info_textview_main__internal().
static void report_textview_init__internal (TextViewContext * tvc) [static]
Definition at line 111 of file info_draw.c.
References TextViewContext::iter, TextViewContext::iter_char, TextViewContext::iter_char_next, Report::len, Report::message, and str.
Referenced by report_textview_begin(), and report_textview_step().
static int report_textview_line_color (struct TextViewContext * tvc, unsigned char fg[3], unsigned char bg[3]) [static]
Definition at line 211 of file info_draw.c.
References info_report_color(), TextViewContext::iter, TextViewContext::iter_tmp, TVC_LINE_BG, and TVC_LINE_FG.
Referenced by info_textview_main__internal().
static int report_textview_line_get (struct TextViewContext * tvc, const char ** line, int * len) [static]
Definition at line 203 of file info_draw.c.
References TextViewContext::iter, TextViewContext::iter_char, TextViewContext::iter_char_next, and Report::message.
Referenced by info_textview_main__internal().
static int report_textview_skip__internal (TextViewContext * tvc) [static]
Definition at line 125 of file info_draw.c.
References TextViewContext::arg1, info_report_mask(), TextViewContext::iter, and NULL.
Referenced by report_textview_begin(), and report_textview_step().
static int report_textview_step (TextViewContext * tvc) [static]
Definition at line 175 of file info_draw.c.
References FALSE, if(), TextViewContext::iter, TextViewContext::iter_char, TextViewContext::iter_char_next, TextViewContext::iter_tmp, Report::len, report_textview_init__internal(), report_textview_skip__internal(), and TRUE.
Referenced by info_textview_main__internal().