Blender: gpencil_paint.c File Reference
gpencil_paint.c File Reference
gpencil
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_gpencil.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_report.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_windowmanager_types.h"
#include "UI_view2d.h"
#include "ED_gpencil.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "gpencil_intern.h"
Classes
struct tGPsdata
struct tGpSmoothCo
Defines
#define GP_STROKE_BUFFER_MAX 5000
#define MIN_MANHATTEN_PX (U.gp_manhattendist)
#define MIN_EUCLIDEAN_PX (U.gp_euclideandist)
#define GP_SIMPLIFY_AVPOINT(offs, sfac)
Typedefs
typedef struct tGPsdata tGPsdata
typedef struct tGpSmoothCo tGpSmoothCo
Enumerations
enum { GP_STATUS_IDLING = 0, GP_STATUS_PAINTING, GP_STATUS_ERROR, GP_STATUS_DONE }
enum { GP_STROKEADD_INVALID = -2, GP_STROKEADD_OVERFLOW = -1, GP_STROKEADD_NORMAL, GP_STROKEADD_FULL }
enum { GP_PAINTFLAG_FIRSTRUN = (1<<0), GP_PAINTFLAG_STROKEADDED = (1<<1) }
Functions
static void gp_session_validatebuffer (tGPsdata *p)
static int gpencil_draw_poll (bContext *C)
static int gpencil_project_check (tGPsdata *p)
static void gp_get_3d_reference (tGPsdata *p, float vec[3])
static short gp_stroke_filtermval (tGPsdata *p, const int mval[2], int pmval[2])
static void gp_stroke_convertcoords (tGPsdata *p, const int mval[2], float out[3], float *depth)
static short gp_stroke_addpoint (tGPsdata *p, const int mval[2], float pressure)
static void gp_stroke_smooth (tGPsdata *p)
static void gp_stroke_simplify (tGPsdata *p)
static void gp_stroke_newfrombuffer (tGPsdata *p)
static short gp_stroke_eraser_splitdel (bGPDframe *gpf, bGPDstroke *gps, int i)
static short gp_stroke_eraser_strokeinside (int mval[], int UNUSED(mvalo[]), short rad, short x0, short y0, short x1, short y1)
static void gp_stroke_eraser_dostroke (tGPsdata *p, int mval[], int mvalo[], short rad, rcti *rect, bGPDframe *gpf, bGPDstroke *gps)
static void gp_stroke_doeraser (tGPsdata *p)
static int gp_session_initdata (bContext *C, tGPsdata *p)
static tGPsdata * gp_session_initpaint (bContext *C)
static void gp_session_cleanup (tGPsdata *p)
static void gp_paint_initstroke (tGPsdata *p, short paintmode)
static void gp_paint_strokeend (tGPsdata *p)
static void gp_paint_cleanup (tGPsdata *p)
static void gpencil_draw_exit (bContext *C, wmOperator *op)
static int gpencil_draw_cancel (bContext *C, wmOperator *op)
static int gpencil_draw_init (bContext *C, wmOperator *op)
static void gpencil_draw_status_indicators (tGPsdata *p)
static void gpencil_draw_apply (wmOperator *op, tGPsdata *p)
static void gpencil_draw_apply_event (wmOperator *op, wmEvent *event)
static int gpencil_draw_exec (bContext *C, wmOperator *op)
static int gpencil_draw_invoke (bContext *C, wmOperator *op, wmEvent *event)
static int gpencil_area_exists (bContext *C, ScrArea *satest)
static tGPsdata * gpencil_stroke_begin (bContext *C, wmOperator *op)
static void gpencil_stroke_end (wmOperator *op)
static int gpencil_draw_modal (bContext *C, wmOperator *op, wmEvent *event)
void GPENCIL_OT_draw (wmOperatorType *ot)
Variables
static EnumPropertyItem prop_gpencil_drawmodes []
Detailed Description
Definition in file gpencil_paint.c.
Define Documentation
#define GP_SIMPLIFY_AVPOINT (offs, sfac)
Value:
{ \
        co[0] += (float)(old_points[offs].x * sfac); \
        co[1] += (float)(old_points[offs].y * sfac); \
        pressure += old_points[offs].pressure * sfac; \
    }
Referenced by gp_stroke_simplify().
#define GP_STROKE_BUFFER_MAX 5000
Definition at line 138 of file gpencil_paint.c.
Referenced by gp_session_validatebuffer(), and gp_stroke_addpoint().
#define MIN_EUCLIDEAN_PX (U.gp_euclideandist)
Definition at line 144 of file gpencil_paint.c.
Referenced by gp_stroke_filtermval().
#define MIN_MANHATTEN_PX (U.gp_manhattendist)
Definition at line 142 of file gpencil_paint.c.
Referenced by gp_stroke_filtermval().
Typedef Documentation
typedef struct tGPsdata tGPsdata
typedef struct tGpSmoothCo tGpSmoothCo
Enumeration Type Documentation
anonymous enum
Enumerator:
GP_STATUS_IDLING
GP_STATUS_PAINTING
GP_STATUS_ERROR
GP_STATUS_DONE
Definition at line 114 of file gpencil_paint.c.
anonymous enum
Enumerator:
GP_STROKEADD_INVALID
GP_STROKEADD_OVERFLOW
GP_STROKEADD_NORMAL
GP_STROKEADD_FULL
Definition at line 122 of file gpencil_paint.c.
anonymous enum
Enumerator:
GP_PAINTFLAG_FIRSTRUN
GP_PAINTFLAG_STROKEADDED
Definition at line 130 of file gpencil_paint.c.
Function Documentation
static void gp_get_3d_reference (tGPsdata * p, float vec[3]) [static]
Definition at line 190 of file gpencil_paint.c.
References copy_v3_v3(), PointerRNA::data, ListBase::first, give_cursor(), Object::loc, tGPsdata::ownerPtr, RNA_Object, tGPsdata::sa, tGPsdata::scene, ScrArea::spacedata, sub_v3_v3v3(), and PointerRNA::type.
Referenced by gp_paint_initstroke(), and gp_stroke_convertcoords().
static void gp_paint_cleanup (tGPsdata * p) [static]
Definition at line 1366 of file gpencil_paint.c.
References bGPDframe::flag, GP_FRAME_PAINT, gp_paint_strokeend(), tGPsdata::gpd, and tGPsdata::gpf.
Referenced by gpencil_draw_exit(), and gpencil_stroke_end().
static void gp_paint_initstroke (tGPsdata * p, short paintmode) [static]
Definition at line 1200 of file gpencil_paint.c.
References tGPsdata::ar, RenderData::cfra, bGPDlayer::color, copy_v3_v3(), tGPsdata::custom_color, ED_view3d_calc_camera_border(), ELEM, ListBase::first, bGPDframe::flag, bGPdata::flag, bGPDlayer::flag, tGPsdata::flags, G, G_DEBUG, GP_DATA_VIEWALIGN, GP_FRAME_PAINT, gp_get_3d_reference(), GP_LAYER_LOCKED, GP_PAINTFLAG_FIRSTRUN, GP_PAINTMODE_ERASER, GP_STATUS_ERROR, GP_STROKE_2DIMAGE, GP_STROKE_2DSPACE, GP_STROKE_3DSPACE, GP_STROKE_ERASER, tGPsdata::gpd, gpencil_layer_addnew(), gpencil_layer_getactive(), gpencil_layer_getframe(), tGPsdata::gpf, tGPsdata::gpl, if(), SpaceImage::image, initgrabz(), SpaceSeq::mainb, NULL, tGPsdata::paintmode, RegionView3D::persp, Scene::r, ARegion::regiondata, RV3D_CAMOB, tGPsdata::sa, bGPdata::sbuffer_sflag, tGPsdata::scene, SEQ_DRAW_IMG_IMBUF, SEQ_ZOOM_FAC, RenderData::size, SPACE_CLIP, SPACE_IMAGE, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, ScrArea::spacetype, tGPsdata::status, tGPsdata::subrect, tGPsdata::subrect_data, TRUE, ScrArea::winx, ScrArea::winy, RenderData::xasp, RenderData::xsch, RenderData::yasp, and RenderData::ysch.
Referenced by gpencil_draw_exec(), gpencil_draw_init(), and gpencil_stroke_begin().
static void gp_paint_strokeend (tGPsdata * p) [static]
Definition at line 1336 of file gpencil_paint.c.
References tGPsdata::ar, ED_view3d_autodist_init(), ListBase::first, bGPdata::flag, GP_DATA_DEPTH_STROKE, gp_session_validatebuffer(), GP_STROKE_ERASER, gp_stroke_newfrombuffer(), gp_stroke_simplify(), gp_stroke_smooth(), tGPsdata::gpd, gpencil_project_check(), tGPsdata::sa, bGPdata::sbuffer_sflag, tGPsdata::scene, ScrArea::spacedata, view3d_region_operator_needs_opengl(), and tGPsdata::win.
Referenced by gp_paint_cleanup(), gpencil_draw_apply(), and gpencil_draw_exec().
static void gp_session_cleanup (tGPsdata * p) [static]
Definition at line 1179 of file gpencil_paint.c.
References tGPsdata::gpd, if(), MEM_freeN(), NULL, p, bGPdata::sbuffer, bGPdata::sbuffer_sflag, and bGPdata::sbuffer_size.
Referenced by gpencil_draw_exit(), and gpencil_stroke_end().
static int gp_session_initdata (bContext * C, tGPsdata * p) [static]
Definition at line 981 of file gpencil_paint.c.
References tGPsdata::ar, CTX_data_scene(), CTX_wm_area(), CTX_wm_region(), CTX_wm_window(), tGPsdata::custom_color, ED_gpencil_session_active(), ListBase::first, SpaceSeq::flag, G, G_DEBUG, gp_session_validatebuffer(), GP_STATUS_ERROR, tGPsdata::gpd, gpencil_data_addnew(), gpencil_data_get_pointers(), gpencil_undo_init(), tGPsdata::imat, invert_m4_m4(), SpaceSeq::mainb, NULL, tGPsdata::ownerPtr, ARegion::regiondata, tGPsdata::sa, tGPsdata::scene, SEQ_DRAW_GPENCIL, SEQ_DRAW_SEQUENCE, SI_DISPGP, SNODE_DISPGP, SPACE_CLIP, SPACE_IMAGE, SPACE_NODE, SPACE_SEQ, SPACE_VIEW3D, ScrArea::spacedata, ScrArea::spacetype, tGPsdata::status, SpaceClip::unistabmat, unit_m4(), tGPsdata::v2d, ARegion::v2d, V3D_DISPGP, and tGPsdata::win.
Referenced by gp_session_initpaint(), and gpencil_stroke_begin().
static tGPsdata* gp_session_initpaint (bContext * C) [static]
Definition at line 1165 of file gpencil_paint.c.
References gp_session_initdata(), MEM_callocN(), NULL, and p.
Referenced by gpencil_draw_init().
static void gp_session_validatebuffer (tGPsdata * p) [static]
Definition at line 959 of file gpencil_paint.c.
References GP_STROKE_BUFFER_MAX, tGPsdata::gpd, MEM_callocN(), bGPdata::sbuffer, bGPdata::sbuffer_sflag, and bGPdata::sbuffer_size.
Referenced by gp_paint_strokeend(), gp_session_initdata(), and gp_stroke_simplify().
static short gp_stroke_addpoint (tGPsdata * p, const int mval[2], float pressure) [static]
Definition at line 320 of file gpencil_paint.c.
References tGPsdata::ar, copy_v2_v2_int(), ED_view3d_autodist_init(), ListBase::first, bGPdata::flag, tGPsdata::flags, GP_DATA_DEPTH_STROKE, GP_PAINTFLAG_STROKEADDED, GP_PAINTMODE_DRAW, GP_PAINTMODE_DRAW_POLY, GP_PAINTMODE_DRAW_STRAIGHT, GP_STROKE_BUFFER_MAX, gp_stroke_convertcoords(), GP_STROKEADD_FULL, GP_STROKEADD_INVALID, GP_STROKEADD_NORMAL, GP_STROKEADD_OVERFLOW, tGPsdata::gpd, gpencil_project_check(), tGPsdata::gpf, ListBase::last, MEM_reallocN(), NULL, tGPsdata::paintmode, bGPDstroke::points, bGPDspoint::pressure, tGPspoint::pressure, tGPsdata::sa, bGPdata::sbuffer, bGPdata::sbuffer_size, tGPsdata::scene, ScrArea::spacedata, bGPDframe::strokes, bGPDstroke::totpoints, view3d_region_operator_needs_opengl(), tGPsdata::win, tGPspoint::x, and bGPDspoint::x.
Referenced by gp_stroke_simplify(), and gpencil_draw_apply().
static void gp_stroke_convertcoords (tGPsdata * p, const int mval[2], float out[3], float * depth) [static]
Definition at line 245 of file gpencil_paint.c.
References tGPsdata::ar, ED_view3d_autodist_simple(), ED_view3d_win_to_delta(), gp_get_3d_reference(), GP_STROKE_2DIMAGE, GP_STROKE_2DSPACE, GP_STROKE_3DSPACE, tGPsdata::gpd, gpencil_project_check(), tGPsdata::imat, mul_v3_m4v3(), NULL, project_int_noclip(), bGPdata::sbuffer_sflag, sub_v3_v3v3(), tGPsdata::subrect, UI_view2d_region_to_view(), tGPsdata::v2d, VECSUB2D, ARegion::winx, ARegion::winy, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by gp_stroke_addpoint(), and gp_stroke_newfrombuffer().
static void gp_stroke_doeraser (tGPsdata * p) [static]
Definition at line 936 of file gpencil_paint.c.
References ListBase::first, gp_stroke_eraser_dostroke(), tGPsdata::gpf, tGPsdata::mval, tGPsdata::mvalo, bGPDstroke::next, tGPsdata::radius, bGPDframe::strokes, rcti::xmax, rcti::xmin, rcti::ymax, and rcti::ymin.
Referenced by gpencil_draw_apply().
static void gp_stroke_eraser_dostroke (tGPsdata * p, int mval[], int mvalo[], short rad, rcti * rect, bGPDframe * gpf, bGPDstroke * gps) [static]
Definition at line 803 of file gpencil_paint.c.
References tGPsdata::ar, BLI_freelinkN(), BLI_in_rcti(), bGPDstroke::flag, GP_STROKE_2DIMAGE, GP_STROKE_2DSPACE, GP_STROKE_3DSPACE, gp_stroke_eraser_splitdel(), gp_stroke_eraser_strokeinside(), i, MEM_freeN(), NULL, bGPDstroke::points, project_int(), bGPDframe::strokes, tGPsdata::subrect, bGPDstroke::totpoints, UI_view2d_view_to_region(), tGPsdata::v2d, ARegion::winx, ARegion::winy, bGPDspoint::x, rctf::xmax, rctf::xmin, bGPDspoint::y, rctf::ymax, and rctf::ymin.
Referenced by gp_stroke_doeraser().
static short gp_stroke_eraser_splitdel (bGPDframe * gpf, bGPDstroke * gps, int i) [static]
Definition at line 723 of file gpencil_paint.c.
References BLI_freelinkN(), BLI_insertlinkafter(), i, MEM_callocN(), MEM_dupallocN(), MEM_freeN(), bGPDstroke::next, NULL, bGPDstroke::points, bGPDstroke::prev, bGPDframe::strokes, and bGPDstroke::totpoints.
Referenced by gp_stroke_eraser_dostroke().
static short gp_stroke_eraser_strokeinside (int mval[], int UNUSEDmvalo[], short rad, short x0, short y0, short x1, short y1) [static]
Definition at line 791 of file gpencil_paint.c.
References edge_inside_circle().
Referenced by gp_stroke_eraser_dostroke().
static short gp_stroke_filtermval (tGPsdata * p, const int mval[2], int pmval[2]) [static]
Definition at line 216 of file gpencil_paint.c.
References abs(), tGPsdata::gpd, MIN_EUCLIDEAN_PX, MIN_MANHATTEN_PX, and bGPdata::sbuffer_size.
Referenced by gpencil_draw_apply().
static void gp_stroke_newfrombuffer (tGPsdata * p) [static]
Definition at line 552 of file gpencil_paint.c.
References tGPsdata::ar, BLI_addtail(), copy_v2_v2_int(), ED_view3d_autodist_depth(), ED_view3d_autodist_depth_seg(), FALSE, bGPdata::flag, bGPDstroke::flag, tGPsdata::flags, FLT_MAX, G, G_DEBUG, GP_DATA_DEPTH_STROKE, GP_DATA_DEPTH_STROKE_ENDPOINTS, GP_PAINTFLAG_STROKEADDED, GP_PAINTMODE_DRAW_POLY, GP_PAINTMODE_DRAW_STRAIGHT, gp_stroke_convertcoords(), tGPsdata::gpd, gpencil_project_check(), tGPsdata::gpf, tGPsdata::gpl, i, if(), interp_sparse_array(), MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, tGPsdata::paintmode, bGPDstroke::points, bGPDspoint::pressure, tGPspoint::pressure, bGPdata::sbuffer, bGPdata::sbuffer_sflag, bGPdata::sbuffer_size, bGPDframe::strokes, bGPDstroke::thickness, bGPDlayer::thickness, totelem, bGPDstroke::totpoints, TRUE, tGPspoint::x, and bGPDspoint::x.
Referenced by gp_paint_strokeend().
static void gp_stroke_simplify (tGPsdata * p) [static]
Definition at line 485 of file gpencil_paint.c.
References co, GP_PAINT_DOSIMPLIFY, GP_PAINTMODE_DRAW_STRAIGHT, gp_session_validatebuffer(), GP_SIMPLIFY_AVPOINT, gp_stroke_addpoint(), tGPsdata::gpd, i, if(), MEM_freeN(), NULL, tGPsdata::paintmode, bGPdata::sbuffer, bGPdata::sbuffer_sflag, and bGPdata::sbuffer_size.
Referenced by gp_paint_strokeend().
static void gp_stroke_smooth (tGPsdata * p) [static]
Definition at line 441 of file gpencil_paint.c.
References copy_v2_v2_int(), ELEM, GP_PAINT_DOSMOOTH, GP_PAINTMODE_DRAW_POLY, GP_PAINTMODE_DRAW_STRAIGHT, tGPsdata::gpd, i, MEM_callocN(), MEM_freeN(), NULL, tGPsdata::paintmode, bGPdata::sbuffer, bGPdata::sbuffer_size, tGPspoint::x, tGpSmoothCo::x, tGPspoint::y, and tGpSmoothCo::y.
Referenced by gp_paint_strokeend().
static int gpencil_area_exists (bContext * C, ScrArea * satest) [static]
Definition at line 1724 of file gpencil_paint.c.
References bScreen::areabase, CTX_wm_screen(), ListBase::first, and ScrArea::next.
Referenced by gpencil_draw_modal().
static void gpencil_draw_apply (wmOperator * op, tGPsdata * p) [static]
Definition at line 1491 of file gpencil_paint.c.
References BKE_report(), G, G_DEBUG, gp_paint_strokeend(), GP_PAINTMODE_ERASER, GP_STATUS_ERROR, gp_stroke_addpoint(), gp_stroke_doeraser(), gp_stroke_filtermval(), GP_STROKEADD_FULL, GP_STROKEADD_INVALID, GP_STROKEADD_OVERFLOW, tGPsdata::mval, tGPsdata::mvalo, tGPsdata::opressure, tGPsdata::paintmode, tGPsdata::pressure, wmOperator::reports, RPT_ERROR, and tGPsdata::status.
Referenced by gpencil_draw_apply_event(), and gpencil_draw_exec().
static void gpencil_draw_apply_event (wmOperator * op, wmEvent * event) [static]
Definition at line 1535 of file gpencil_paint.c.
References wmTabletData::Active, tGPsdata::ar, wmEvent::custom, wmOperator::customdata, ED_region_tag_redraw(), EVT_DATA_TABLET, EVT_TABLET_NONE, tGPsdata::flags, GP_PAINTFLAG_FIRSTRUN, gpencil_draw_apply(), tGPsdata::mval, tGPsdata::mvalo, tGPsdata::opressure, p, tGPsdata::pressure, wmTabletData::Pressure, wmOperator::ptr, RNA_boolean_set(), RNA_collection_add(), RNA_float_set(), and RNA_float_set_array().
Referenced by gpencil_draw_invoke(), and gpencil_draw_modal().
static int gpencil_draw_cancel (bContext * C, wmOperator * op) [static]
Definition at line 1411 of file gpencil_paint.c.
References gpencil_draw_exit(), and OPERATOR_CANCELLED.
Referenced by GPENCIL_OT_draw().
static int gpencil_draw_exec (bContext * C, wmOperator * op) [static]
Definition at line 1594 of file gpencil_paint.c.
References wmOperator::customdata, tGPsdata::flags, gp_paint_initstroke(), gp_paint_strokeend(), GP_PAINTFLAG_FIRSTRUN, gpencil_draw_apply(), gpencil_draw_exit(), gpencil_draw_init(), MEM_freeN(), tGPsdata::mval, tGPsdata::mvalo, NA_EDITED, NC_SCREEN, ND_GPENCIL, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, tGPsdata::opressure, p, tGPsdata::paintmode, tGPsdata::pressure, wmOperator::ptr, RNA_BEGIN, RNA_boolean_get(), RNA_END, RNA_float_get(), RNA_float_get_array(), and WM_event_add_notifier().
Referenced by GPENCIL_OT_draw().
static void gpencil_draw_exit (bContext * C, wmOperator * op) [static]
Definition at line 1382 of file gpencil_paint.c.
References CTX_wm_window(), wmOperator::customdata, gp_paint_cleanup(), GP_PAINTMODE_ERASER, gp_session_cleanup(), gpencil_undo_finish(), MEM_freeN(), NULL, p, tGPsdata::paintmode, and WM_cursor_restore().
Referenced by gpencil_draw_cancel(), gpencil_draw_exec(), gpencil_draw_init(), and gpencil_draw_modal().
static int gpencil_draw_init (bContext * C, wmOperator * op) [static]
Definition at line 1421 of file gpencil_paint.c.
References wmOperator::customdata, gp_paint_initstroke(), gp_session_initpaint(), GP_STATUS_ERROR, gpencil_draw_exit(), NULL, p, wmOperator::ptr, tGPsdata::radius, RNA_enum_get(), and tGPsdata::status.
Referenced by gpencil_draw_exec(), and gpencil_draw_invoke().
static int gpencil_draw_invoke (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1665 of file gpencil_paint.c.
References BC_CROSSCURSOR, BC_PAINTBRUSHCURSOR, CTX_wm_window(), wmOperator::customdata, G, G_DEBUG, GP_PAINTMODE_ERASER, GP_STATUS_PAINTING, gpencil_draw_apply_event(), gpencil_draw_init(), MEM_freeN(), NC_SCREEN, ND_GPENCIL, NULL, OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, p, tGPsdata::paintmode, tGPsdata::status, wmEvent::type, WM_cursor_modal(), WM_event_add_modal_handler(), and WM_event_add_notifier().
Referenced by GPENCIL_OT_draw().
static int gpencil_draw_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 1782 of file gpencil_paint.c.
References wmOperator::customdata, ELEM, ELEM4, ESCKEY, tGPsdata::flags, GP_PAINTFLAG_FIRSTRUN, GP_PAINTMODE_DRAW_POLY, GP_STATUS_DONE, GP_STATUS_ERROR, GP_STATUS_IDLING, GP_STATUS_PAINTING, gpencil_area_exists(), gpencil_draw_apply_event(), gpencil_draw_exit(), gpencil_draw_status_indicators(), GPENCIL_SKETCH_SESSIONS_ON, gpencil_stroke_begin(), gpencil_stroke_end(), INBETWEEN_MOUSEMOVE, KM_PRESS, LEFTMOUSE, MOUSEMOVE, NA_EDITED, NC_SCREEN, ND_GPENCIL, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_PASS_THROUGH, OPERATOR_RUNNING_MODAL, p, PADENTER, tGPsdata::paintmode, RETKEY, RIGHTMOUSE, tGPsdata::sa, tGPsdata::scene, SPACEKEY, tGPsdata::status, wmEvent::type, wmEvent::val, and WM_event_add_notifier().
Referenced by GPENCIL_OT_draw().
static int gpencil_draw_poll (bContext * C) [static]
Definition at line 155 of file gpencil_paint.c.
References CTX_wm_operator_poll_msg_set(), ED_gpencil_session_active(), ED_operator_regionactive(), gpencil_data_get_pointers(), and NULL.
Referenced by GPENCIL_OT_draw().
static void gpencil_draw_status_indicators (tGPsdata * p) [static]
Definition at line 1451 of file gpencil_paint.c.
References ED_area_headerprint(), GP_PAINTMODE_DRAW, GP_PAINTMODE_DRAW_STRAIGHT, GP_PAINTMODE_ERASER, GP_STATUS_DONE, GP_STATUS_ERROR, GP_STATUS_IDLING, GP_STATUS_PAINTING, GPENCIL_SKETCH_SESSIONS_ON, NULL, tGPsdata::paintmode, tGPsdata::sa, tGPsdata::scene, and tGPsdata::status.
Referenced by gpencil_draw_modal().
void GPENCIL_OT_draw (wmOperatorType * ot)
Definition at line 1918 of file gpencil_paint.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, gpencil_draw_cancel(), gpencil_draw_exec(), gpencil_draw_invoke(), gpencil_draw_modal(), gpencil_draw_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_collection_runtime(), RNA_def_enum(), RNA_OperatorStrokeElement, and wmOperatorType::srna.
Referenced by ED_operatortypes_gpencil().
static int gpencil_project_check (tGPsdata * p) [static]
Definition at line 178 of file gpencil_paint.c.
References bGPdata::flag, GP_DATA_DEPTH_STROKE, GP_DATA_DEPTH_VIEW, GP_STROKE_3DSPACE, tGPsdata::gpd, and bGPdata::sbuffer_sflag.
Referenced by gp_paint_strokeend(), gp_stroke_addpoint(), gp_stroke_convertcoords(), and gp_stroke_newfrombuffer().
static tGPsdata* gpencil_stroke_begin (bContext * C, wmOperator * op) [static]
Definition at line 1737 of file gpencil_paint.c.
References CTX_wm_area(), wmOperator::customdata, gp_paint_initstroke(), gp_session_initdata(), GP_STATUS_ERROR, GP_STATUS_PAINTING, p, tGPsdata::paintmode, tGPsdata::sa, and tGPsdata::status.
Referenced by gpencil_draw_modal().
static void gpencil_stroke_end (wmOperator * op) [static]
Definition at line 1764 of file gpencil_paint.c.
References wmOperator::customdata, gp_paint_cleanup(), gp_session_cleanup(), GP_STATUS_IDLING, tGPsdata::gpd, gpencil_undo_push(), tGPsdata::gpf, tGPsdata::gpl, NULL, p, and tGPsdata::status.
Referenced by gpencil_draw_modal().
Variable Documentation
EnumPropertyItem prop_gpencil_drawmodes[] [static]
Initial value:
 {
    {GP_PAINTMODE_DRAW, "DRAW", 0, "Draw Freehand", ""},
    {GP_PAINTMODE_DRAW_STRAIGHT, "DRAW_STRAIGHT", 0, "Draw Straight Lines", ""},
    {GP_PAINTMODE_DRAW_POLY, "DRAW_POLY", 0, "Draw Poly Line", ""},
    {GP_PAINTMODE_ERASER, "ERASER", 0, "Eraser", ""},
    {0, NULL, 0, NULL, NULL}
}
Definition at line 1910 of file gpencil_paint.c.