Blender: bMovieHandle Struct Reference
bMovieHandle Struct Reference
#include <BKE_writeavi.h>
Public Attributes
int(* start_movie)(struct Scene *scene, struct RenderData *rd, int rectx, int recty, struct ReportList *reports)
int(* append_movie)(struct RenderData *rd, int start_frame, int frame, int *pixels, int rectx, int recty, struct ReportList *reports)
void(* end_movie)(void)
int(* get_next_frame)(struct RenderData *rd, struct ReportList *reports)
void(* get_movie_path)(char *string, struct RenderData *rd)
Detailed Description
Definition at line 45 of file BKE_writeavi.h.
Member Data Documentation
int(* bMovieHandle::append_movie)(struct RenderData *rd, int start_frame, int frame, int *pixels, int rectx, int recty, struct ReportList *reports)
Definition at line 47 of file BKE_writeavi.h.
Referenced by BKE_get_movie_handle(), do_write_image_or_movie(), screen_opengl_render_anim_step(), and screenshot_startjob().
void(* bMovieHandle::end_movie)(void)
Definition at line 49 of file BKE_writeavi.h.
Referenced by BKE_get_movie_handle(), RE_BlenderAnim(), screen_opengl_render_end(), and screenshot_startjob().
void(* bMovieHandle::get_movie_path)(char *string, struct RenderData *rd)
Definition at line 51 of file BKE_writeavi.h.
Referenced by BKE_get_movie_handle(), and BKE_makeanimstring().
int(* bMovieHandle::get_next_frame)(struct RenderData *rd, struct ReportList *reports)
Definition at line 50 of file BKE_writeavi.h.
Referenced by BKE_get_movie_handle(), and RE_BlenderAnim().
int(* bMovieHandle::start_movie)(struct Scene *scene, struct RenderData *rd, int rectx, int recty, struct ReportList *reports)
Definition at line 46 of file BKE_writeavi.h.
Referenced by BKE_get_movie_handle(), RE_BlenderAnim(), screen_opengl_render_anim_initialize(), and screenshot_startjob().
The documentation for this struct was generated from the following file:
BKE_writeavi.h