Blender: scolumn_dfs.c File Reference
scolumn_dfs.c File Reference
opennl
#include "ssp_defs.h"
Defines
#define T2_SUPER
Functions
int scolumn_dfs (const int m, const int jcol, int *perm_r, int *nseg, int *lsub_col, int *segrep, int *repfnz, int *xprune, int *marker, int *parent, int *xplore, GlobalLU_t *Glu)
Detailed Description
Definition in file scolumn_dfs.c.
Define Documentation
#define T2_SUPER
Definition at line 29 of file scolumn_dfs.c.
Function Documentation
int scolumn_dfs (const int m, const int jcol, int * perm_r, int * nseg, int * lsub_col, int * segrep, int * repfnz, int * xprune, int * marker, int * parent, int * xplore, GlobalLU_t * Glu)
Definition at line 32 of file scolumn_dfs.c.
References EMPTY, GlobalLU_t::lsub, LSUB, GlobalLU_t::nzlmax, sLUMemXpand(), sp_ienv(), GlobalLU_t::supno, GlobalLU_t::xlsub, and GlobalLU_t::xsup.
Referenced by sgstrf().