Blender: node_composite_filter.c File Reference
node_composite_filter.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void do_filter_edge (CompBuf *out, CompBuf *in, float *filter, float fac)
static void do_filter3 (CompBuf *out, CompBuf *in, float *filter, float fac)
static void node_composit_exec_filter (void *data, bNode *node, bNodeStack **in, bNodeStack **out)
void register_node_type_cmp_filter (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_filter_in []
static bNodeSocketTemplate cmp_node_filter_out []
Detailed Description
Definition in file node_composite_filter.c.
Function Documentation
static void do_filter3 (CompBuf * out, CompBuf * in, float * filter, float fac) [static]
Definition at line 95 of file node_composite_filter.c.
References copy_v3_v3(), copy_v4_v4(), CompBuf::rect, CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_filter().
static void do_filter_edge (CompBuf * out, CompBuf * in, float * filter, float fac) [static]
Definition at line 46 of file node_composite_filter.c.
References CB_RGBA, CB_VAL, copy_v4_v4(), CompBuf::rect, sqrt(), CompBuf::type, CompBuf::x, and CompBuf::y.
Referenced by node_composit_exec_filter().
static void node_composit_exec_filter (void * data, bNode * node, bNodeStack ** in, bNodeStack ** out) [static]
Definition at line 168 of file node_composite_filter.c.
References alloc_compbuf(), CMP_FILT_KIRSCH, CMP_FILT_LAPLACE, CMP_FILT_PREWITT, CMP_FILT_SHADOW, CMP_FILT_SHARP, CMP_FILT_SOBEL, CMP_FILT_SOFT, bNode::custom1, bNodeStack::data, do_filter3(), do_filter_edge(), generate_preview(), CompBuf::type, CompBuf::x, CompBuf::xof, CompBuf::y, and CompBuf::yof.
Referenced by register_node_type_cmp_filter().
void register_node_type_cmp_filter (bNodeTreeType * ttype)
Definition at line 223 of file node_composite_filter.c.
References CMP_NODE_FILTER, NODE_CLASS_OP_FILTER, node_composit_exec_filter(), node_filter_label(), NODE_OPTIONS, NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_label(), node_type_size(), node_type_socket_templates(), and nodeRegisterType().
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_filter_in[] [static]
Initial value:
 {
    {   SOCK_FLOAT, 1, "Fac",           1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   SOCK_RGBA, 1, "Image",          1.0f, 1.0f, 1.0f, 1.0f},
    {   -1, 0, ""   }
}
Definition at line 36 of file node_composite_filter.c.
bNodeSocketTemplate cmp_node_filter_out[] [static]
Initial value:
 {
    {   SOCK_RGBA, 0, "Image"},
    {   -1, 0, ""   }
}
Definition at line 41 of file node_composite_filter.c.