Blender: CTR_Map< Key, Value > Class Template Reference
CTR_Map< Key, Value > Class Template Reference
#include <CTR_Map.h>
Classes
struct Entry
Public Member Functions
CTR_Map (int num_buckets=100)
CTR_Map (const CTR_Map &map)
int size ()
Value * at (int index)
Key * getKey (int index)
void clear ()
~CTR_Map ()
void insert (const Key &key, const Value &value)
void remove (const Key &key)
Value * operator[] (Key key)
Detailed Description
template<class Key, class Value>
class CTR_Map< Key, Value >
Definition at line 37 of file CTR_Map.h.
Constructor & Destructor Documentation
template<class Key, class Value> CTR_Map< Key, Value >::CTR_Map (int num_buckets = 100) [inline]
Definition at line 51 of file CTR_Map.h.
template<class Key, class Value> CTR_Map< Key, Value >::CTR_Map (const CTR_Map< Key, Value > & map) [inline]
Definition at line 58 of file CTR_Map.h.
template<class Key, class Value> CTR_Map< Key, Value >::~CTR_Map () [inline]
Definition at line 134 of file CTR_Map.h.
Member Function Documentation
template<class Key, class Value> Value* CTR_Map< Key, Value >::at (int index) [inline]
Definition at line 85 of file CTR_Map.h.
Referenced by NG_NetworkScene::ClearMessageMap(), KX_BlenderSceneConverter::FreeBlendFile(), and KX_BlenderSceneConverter::~KX_BlenderSceneConverter().
template<class Key, class Value> void CTR_Map< Key, Value >::clear () [inline]
Definition at line 121 of file CTR_Map.h.
Referenced by KX_Scene::AddReplicaObject(), NG_NetworkScene::ClearMessageMap(), KX_BlenderSceneConverter::ConvertMeshSpecial(), KX_BlenderSceneConverter::ConvertScene(), KX_Scene::DupliGroupRecurse(), NG_NetworkScene::RemoveAllObjects(), and CTR_Map< STR_HashedString, std::vector< class NG_NetworkMessage * > * >::~CTR_Map().
template<class Key, class Value> Key* CTR_Map< Key, Value >::getKey (int index) [inline]
Definition at line 103 of file CTR_Map.h.
template<class Key, class Value> void CTR_Map< Key, Value >::insert (const Key & key, const Value & value) [inline]
Definition at line 139 of file CTR_Map.h.
Referenced by KX_Scene::AddNodeReplicaObject(), NG_NetworkScene::AddObject(), CTR_Map< STR_HashedString, std::vector< class NG_NetworkMessage * > * >::CTR_Map(), NG_NetworkScene::proceed(), SCA_LogicManager::RegisterActionName(), KX_BlenderSceneConverter::RegisterGameActuator(), KX_BlenderSceneConverter::RegisterGameController(), KX_BlenderSceneConverter::RegisterGameMesh(), SCA_LogicManager::RegisterGameMeshName(), SCA_LogicManager::RegisterGameObj(), KX_BlenderSceneConverter::RegisterGameObject(), SCA_LogicManager::RegisterGameObjectName(), KX_BlenderSceneConverter::RegisterInterpolatorList(), and SCA_LogicManager::RegisterMeshName().
template<class Key, class Value> Value* CTR_Map< Key, Value >::operator[] (Key key) [inline]
Definition at line 167 of file CTR_Map.h.
template<class Key, class Value> void CTR_Map< Key, Value >::remove (const Key & key) [inline]
Definition at line 154 of file CTR_Map.h.
Referenced by KX_BlenderSceneConverter::FreeBlendFile(), NG_NetworkScene::RemoveObject(), SCA_LogicManager::UnregisterGameObj(), KX_BlenderSceneConverter::UnregisterGameObject(), and SCA_LogicManager::UnregisterMeshName().
template<class Key, class Value> int CTR_Map< Key, Value >::size () [inline]
Definition at line 71 of file CTR_Map.h.
Referenced by NG_NetworkScene::ClearMessageMap(), KX_BlenderSceneConverter::FreeBlendFile(), and KX_BlenderSceneConverter::~KX_BlenderSceneConverter().
The documentation for this class was generated from the following file:
CTR_Map.h