Blender: BKE_lamp.h File Reference
BKE_lamp.h File Reference
blenkernel
General operations, lookup, etc. for blender lamps.
Functions
void * add_lamp (const char *name)
struct Lamp * copy_lamp (struct Lamp *la)
struct Lamp * localize_lamp (struct Lamp *la)
void make_local_lamp (struct Lamp *la)
void free_lamp (struct Lamp *la)
Detailed Description
General operations, lookup, etc. for blender lamps.
Definition in file BKE_lamp.h.
Function Documentation
void* add_lamp (const char * name)
Definition at line 54 of file lamp.c.
References Lamp::adapt_thresh, alloc_libblock(), Lamp::area_size, Lamp::area_sizey, Lamp::area_sizez, Lamp::atm_distance_factor, Lamp::atm_extinction_factor, Lamp::atm_inscattering_factor, Lamp::atm_turbidity, Lamp::att2, Lamp::b, Lamp::backscattered_light, Lamp::bias, BLI_XYZ_CIE, Lamp::buffers, Lamp::bufsize, Lamp::buftype, Lamp::clipend, Lamp::clipsta, Lamp::compressthresh, Lamp::curfalloff, curvemapping_add(), curvemapping_initialize(), Lamp::dist, Lamp::energy, Lamp::falloff_type, Lamp::g, G, Lamp::haint, Lamp::horizon_brightness, ID_LA, Lamp::k, LA_FALLOFF_INVSQUARE, LA_SAMP_HALTON, LA_SHAD_BUF, LA_SHADBUF_HALFWAY, MA_RAMP_ADD, Lamp::mode, NULL, Lamp::preview, Lamp::r, Lamp::ray_samp, Lamp::ray_samp_method, Lamp::ray_sampy, Lamp::ray_sampz, Lamp::samp, Lamp::shadspotsize, Lamp::sky_colorspace, Lamp::sky_exposure, Lamp::skyblendfac, Lamp::skyblendtype, Lamp::soft, Lamp::spotblend, Lamp::spotsize, Lamp::spread, Lamp::sun_brightness, Lamp::sun_effect_type, Lamp::sun_intensity, and Lamp::sun_size.
Referenced by add_obdata_from_type(), and DocumentImporter::writeLight().
struct Lamp* copy_lamp (struct Lamp * la) [read]
Definition at line 104 of file lamp.c.
References BKE_previewimg_copy(), copy_libblock(), Lamp::curfalloff, curvemapping_copy(), Lamp::id, id_us_plus(), MAX_MTEX, MEM_mallocN(), Lamp::mtex, Lamp::nodetree, ntreeCopyTree(), Lamp::preview, and MTex::tex.
Referenced by id_copy(), make_local_lamp(), object_add_duplicate_internal(), and single_obdata_users().
void free_lamp (struct Lamp * la)
Definition at line 208 of file lamp.c.
References BKE_free_animdata(), BKE_icon_delete(), BKE_previewimg_free(), curvemapping_free(), ID::icon_id, Tex::id, MAX_MTEX, MEM_freeN(), Lamp::mtex, ntreeFreeTree(), MTex::tex, and ID::us.
Referenced by free_libblock(), and shader_preview_free().
struct Lamp* localize_lamp (struct Lamp * la) [read]
Definition at line 130 of file lamp.c.
References BLI_remlink(), copy_libblock(), Lamp::curfalloff, curvemapping_copy(), G, Lamp::id, id_us_plus(), MAX_MTEX, MEM_mallocN(), Lamp::mtex, Lamp::nodetree, ntreeLocalize(), NULL, Lamp::preview, and MTex::tex.
Referenced by preview_prepare_scene().
void make_local_lamp (struct Lamp * la)
Definition at line 157 of file lamp.c.
References BKE_id_lib_local_paths(), copy_lamp(), Object::data, FALSE, ListBase::first, G, Object::id, Lamp::id, id_clear_lib_data(), ID::lib, ID::next, NULL, Main::object, TRUE, and ID::us.
Referenced by id_make_local().