Blender: util_system.h File Reference
util_system.h File Reference
#include "util_string.h"
Functions
CCL_NAMESPACE_BEGIN int system_cpu_thread_count ()
string system_cpu_brand_string ()
int system_cpu_bits ()
bool system_cpu_support_optimized ()
Function Documentation
int system_cpu_bits ()
Definition at line 116 of file util_system.cpp.
Referenced by CUDADevice::compile_kernel().
string system_cpu_brand_string ()
Definition at line 88 of file util_system.cpp.
References __cpuid(), i, and replace_string().
Referenced by device_cpu_info().
bool system_cpu_support_optimized ()
Definition at line 187 of file util_system.cpp.
Referenced by CPUDevice::CPUDevice(), CPUDevice::thread_path_trace(), CPUDevice::thread_shader(), and CPUDevice::thread_tonemap().
CCL_NAMESPACE_BEGIN int system_cpu_thread_count ()
Definition at line 36 of file util_system.cpp.
References len(), NULL, and uint.
Referenced by CPUDevice::CPUDevice().