Blender: ntlGeometryShader Class Reference
ntlGeometryShader Class Reference
#include <ntl_geometryshader.h>
Public Member Functions
ntlGeometryShader ()
Default constructor.
virtual ~ntlGeometryShader ()
Default destructor.
virtual int getTypeId ()
Return type id.
virtual int initializeShader ()=0
virtual int postGeoConstrInit (ntlRenderGlobals *glob)
virtual vector
< ntlGeometryObject * >
::iterator getObjectsBegin ()
virtual vector
< ntlGeometryObject * >
::iterator getObjectsEnd ()
virtual void notifyShaderOfDump (int dumptype, int frameNr, char *frameNrStr, string outfilename)=0
string getOutFilename (void)
Protected Attributes
vector< ntlGeometryObject * > mObjects
vector for the objects
string mOutFilename
Detailed Description
Definition at line 19 of file ntl_geometryshader.h.
Constructor & Destructor Documentation
ntlGeometryShader::ntlGeometryShader () [inline]
Default constructor.
Definition at line 26 of file ntl_geometryshader.h.
virtual ntlGeometryShader::~ntlGeometryShader () [inline, virtual]
Default destructor.
Definition at line 30 of file ntl_geometryshader.h.
Member Function Documentation
virtual vector<ntlGeometryObject *>::iterator ntlGeometryShader::getObjectsBegin () [inline, virtual]
Get start iterator for all objects
Reimplemented in SimulationObject.
Definition at line 42 of file ntl_geometryshader.h.
References mObjects.
Referenced by ntlScene::buildScene(), and ntlBlenderDumper::renderScene().
virtual vector<ntlGeometryObject *>::iterator ntlGeometryShader::getObjectsEnd () [inline, virtual]
Get end iterator for all objects
Reimplemented in SimulationObject.
Definition at line 44 of file ntl_geometryshader.h.
References mObjects.
Referenced by ntlScene::buildScene(), and ntlBlenderDumper::renderScene().
string ntlGeometryShader::getOutFilename (void) [inline]
get ouput filename, returns global render outfile if empty
Definition at line 50 of file ntl_geometryshader.h.
References mOutFilename.
Referenced by ntlBlenderDumper::renderScene().
virtual int ntlGeometryShader::getTypeId () [inline, virtual]
Return type id.
Implements ntlGeometryClass.
Definition at line 33 of file ntl_geometryshader.h.
References GEOCLASSTID_SHADER.
virtual int ntlGeometryShader::initializeShader () [pure virtual]
Initialize object, should return !=0 upon error
Implemented in SimulationObject.
Referenced by ntlScene::buildScene().
virtual void ntlGeometryShader::notifyShaderOfDump (int dumptype, int frameNr, char * frameNrStr, string outfilename) [pure virtual]
notify object that dump is in progress (e.g. for field dump)
Implemented in SimulationObject.
Referenced by ntlBlenderDumper::renderScene().
virtual int ntlGeometryShader::postGeoConstrInit (ntlRenderGlobals * glob) [inline, virtual]
Do further object initialization after all geometry has been constructed, should return !=0 upon error
Reimplemented in SimulationObject.
Definition at line 39 of file ntl_geometryshader.h.
References NULL.
Referenced by ntlScene::buildScene().
Member Data Documentation
vector<ntlGeometryObject *> ntlGeometryShader::mObjects [protected]
vector for the objects
Definition at line 55 of file ntl_geometryshader.h.
Referenced by getObjectsBegin(), SimulationObject::getObjectsBegin(), SimulationObject::getObjectsEnd(), getObjectsEnd(), and SimulationObject::initializeLbmSimulation().
string ntlGeometryShader::mOutFilename [protected]
surface output name for this simulation
Definition at line 59 of file ntl_geometryshader.h.
Referenced by getOutFilename(), and SimulationObject::initializeLbmSimulation().
The documentation for this class was generated from the following file:
ntl_geometryshader.h