Blender: rna_internal.h File Reference
rna_internal.h File Reference
RNA
#include "UI_resources.h"
#include "rna_internal_types.h"
Classes
struct ContainerDefRNA
struct FunctionDefRNA
struct PropertyDefRNA
struct StructDefRNA
struct AllocDefRNA
struct BlenderDefRNA
struct ListBaseIterator
struct ArrayIterator
Defines
#define RNA_MAGIC ((int)~0)
Typedefs
typedef struct ContainerDefRNA ContainerDefRNA
typedef struct FunctionDefRNA FunctionDefRNA
typedef struct PropertyDefRNA PropertyDefRNA
typedef struct StructDefRNA StructDefRNA
typedef struct AllocDefRNA AllocDefRNA
typedef struct BlenderDefRNA BlenderDefRNA
typedef int(* IteratorSkipFunc)(struct CollectionPropertyIterator *iter, void *data)
typedef struct ListBaseIterator ListBaseIterator
typedef struct ArrayIterator ArrayIterator
Functions
void RNA_def_ID (struct BlenderRNA *brna)
void RNA_def_action (struct BlenderRNA *brna)
void RNA_def_animation (struct BlenderRNA *brna)
void RNA_def_animviz (struct BlenderRNA *brna)
void RNA_def_armature (struct BlenderRNA *brna)
void RNA_def_actuator (struct BlenderRNA *brna)
void RNA_def_boid (struct BlenderRNA *brna)
void RNA_def_brush (struct BlenderRNA *brna)
void RNA_def_camera (struct BlenderRNA *brna)
void RNA_def_cloth (struct BlenderRNA *brna)
void RNA_def_color (struct BlenderRNA *brna)
void RNA_def_constraint (struct BlenderRNA *brna)
void RNA_def_context (struct BlenderRNA *brna)
void RNA_def_controller (struct BlenderRNA *brna)
void RNA_def_curve (struct BlenderRNA *brna)
void RNA_def_dynamic_paint (struct BlenderRNA *brna)
void RNA_def_fluidsim (struct BlenderRNA *brna)
void RNA_def_fcurve (struct BlenderRNA *brna)
void RNA_def_gameproperty (struct BlenderRNA *brna)
void RNA_def_gpencil (struct BlenderRNA *brna)
void RNA_def_group (struct BlenderRNA *brna)
void RNA_def_image (struct BlenderRNA *brna)
void RNA_def_key (struct BlenderRNA *brna)
void RNA_def_lamp (struct BlenderRNA *brna)
void RNA_def_lattice (struct BlenderRNA *brna)
void RNA_def_main (struct BlenderRNA *brna)
void RNA_def_material (struct BlenderRNA *brna)
void RNA_def_mesh (struct BlenderRNA *brna)
void RNA_def_meta (struct BlenderRNA *brna)
void RNA_def_modifier (struct BlenderRNA *brna)
void RNA_def_nla (struct BlenderRNA *brna)
void RNA_def_nodetree (struct BlenderRNA *brna)
void RNA_def_object (struct BlenderRNA *brna)
void RNA_def_object_force (struct BlenderRNA *brna)
void RNA_def_packedfile (struct BlenderRNA *brna)
void RNA_def_particle (struct BlenderRNA *brna)
void RNA_def_pose (struct BlenderRNA *brna)
void RNA_def_render (struct BlenderRNA *brna)
void RNA_def_rna (struct BlenderRNA *brna)
void RNA_def_scene (struct BlenderRNA *brna)
void RNA_def_screen (struct BlenderRNA *brna)
void RNA_def_sculpt_paint (struct BlenderRNA *brna)
void RNA_def_sensor (struct BlenderRNA *brna)
void RNA_def_sequencer (struct BlenderRNA *brna)
void RNA_def_smoke (struct BlenderRNA *brna)
void RNA_def_space (struct BlenderRNA *brna)
void RNA_def_speaker (struct BlenderRNA *brna)
void RNA_def_test (struct BlenderRNA *brna)
void RNA_def_text (struct BlenderRNA *brna)
void RNA_def_texture (struct BlenderRNA *brna)
void RNA_def_timeline_marker (struct BlenderRNA *brna)
void RNA_def_sound (struct BlenderRNA *brna)
void RNA_def_ui (struct BlenderRNA *brna)
void RNA_def_userdef (struct BlenderRNA *brna)
void RNA_def_vfont (struct BlenderRNA *brna)
void RNA_def_wm (struct BlenderRNA *brna)
void RNA_def_world (struct BlenderRNA *brna)
void RNA_def_movieclip (struct BlenderRNA *brna)
void RNA_def_tracking (struct BlenderRNA *brna)
void rna_def_animdata_common (struct StructRNA *srna)
void rna_def_animviz_common (struct StructRNA *srna)
void rna_def_motionpath_common (struct StructRNA *srna)
void rna_def_texmat_common (struct StructRNA *srna, const char *texspace_editable)
void rna_def_mtex_common (struct BlenderRNA *brna, struct StructRNA *srna, const char *begin, const char *activeget, const char *activeset, const char *activeeditable, const char *structname, const char *structname_slots, const char *update)
void rna_def_render_layer_common (struct StructRNA *srna, int scene)
void rna_ID_name_get (struct PointerRNA *ptr, char *value)
int rna_ID_name_length (struct PointerRNA *ptr)
void rna_ID_name_set (struct PointerRNA *ptr, const char *value)
struct StructRNA * rna_ID_refine (struct PointerRNA *ptr)
struct IDProperty * rna_ID_idprops (struct PointerRNA *ptr, int create)
void rna_ID_fake_user_set (struct PointerRNA *ptr, int value)
struct IDProperty * rna_PropertyGroup_idprops (struct PointerRNA *ptr, int create)
void rna_PropertyGroup_unregister (struct Main *bmain, struct StructRNA *type)
struct StructRNA * rna_PropertyGroup_register (struct Main *bmain, struct ReportList *reports, void *data, const char *identifier, StructValidateFunc validate, StructCallbackFunc call, StructFreeFunc free)
struct StructRNA * rna_PropertyGroup_refine (struct PointerRNA *ptr)
void rna_object_vgroup_name_index_get (struct PointerRNA *ptr, char *value, int index)
int rna_object_vgroup_name_index_length (struct PointerRNA *ptr, int index)
void rna_object_vgroup_name_index_set (struct PointerRNA *ptr, const char *value, short *index)
void rna_object_vgroup_name_set (struct PointerRNA *ptr, const char *value, char *result, int maxlen)
void rna_object_uvlayer_name_set (struct PointerRNA *ptr, const char *value, char *result, int maxlen)
void rna_object_vcollayer_name_set (struct PointerRNA *ptr, const char *value, char *result, int maxlen)
PointerRNA rna_object_shapekey_index_get (struct ID *id, int value)
int rna_object_shapekey_index_set (struct ID *id, PointerRNA value, int current)
void rna_Object_internal_update_data (struct Main *bmain, struct Scene *scene, struct PointerRNA *ptr)
void rna_Mesh_update_draw (struct Main *bmain, struct Scene *scene, struct PointerRNA *ptr)
void rna_TextureSlot_update (struct Main *bmain, struct Scene *scene, struct PointerRNA *ptr)
int rna_Armature_object_poll (struct PointerRNA *ptr, struct PointerRNA value)
int rna_Camera_object_poll (struct PointerRNA *ptr, struct PointerRNA value)
int rna_Curve_object_poll (struct PointerRNA *ptr, struct PointerRNA value)
int rna_Lattice_object_poll (struct PointerRNA *ptr, struct PointerRNA value)
int rna_Mesh_object_poll (struct PointerRNA *ptr, struct PointerRNA value)
int rna_Action_id_poll (struct PointerRNA *ptr, struct PointerRNA value)
int rna_Action_actedit_assign_poll (struct PointerRNA *ptr, struct PointerRNA value)
char * rna_TextureSlot_path (struct PointerRNA *ptr)
void RNA_api_action (StructRNA *srna)
void RNA_api_armature_edit_bone (StructRNA *srna)
void RNA_api_bone (StructRNA *srna)
void RNA_api_camera (StructRNA *srna)
void RNA_api_drivers (StructRNA *srna)
void RNA_api_image (struct StructRNA *srna)
void RNA_api_operator (struct StructRNA *srna)
void RNA_api_macro (struct StructRNA *srna)
void RNA_api_keyconfig (struct StructRNA *srna)
void RNA_api_keyconfigs (struct StructRNA *srna)
void RNA_api_keyingset (struct StructRNA *srna)
void RNA_api_keymap (struct StructRNA *srna)
void RNA_api_keymaps (struct StructRNA *srna)
void RNA_api_keymapitem (struct StructRNA *srna)
void RNA_api_keymapitems (struct StructRNA *srna)
void RNA_api_main (struct StructRNA *srna)
void RNA_api_material (StructRNA *srna)
void RNA_api_mesh (struct StructRNA *srna)
void RNA_api_object (struct StructRNA *srna)
void RNA_api_object_base (struct StructRNA *srna)
void RNA_api_pose_channel (struct StructRNA *srna)
void RNA_api_scene (struct StructRNA *srna)
void RNA_api_scene_render (struct StructRNA *srna)
void RNA_api_sequence_strip (StructRNA *srna)
void RNA_api_text (struct StructRNA *srna)
void RNA_api_ui_layout (struct StructRNA *srna)
void RNA_api_wm (struct StructRNA *srna)
void RNA_api_sensor (struct StructRNA *srna)
void RNA_api_controller (struct StructRNA *srna)
void RNA_api_actuator (struct StructRNA *srna)
void RNA_api_texture (struct StructRNA *srna)
void RNA_api_environment_map (struct StructRNA *srna)
void RNA_def_main_cameras (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_scenes (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_objects (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_materials (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_node_groups (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_meshes (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_lamps (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_libraries (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_screens (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_window_managers (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_images (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_lattices (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_curves (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_metaballs (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_fonts (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_textures (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_brushes (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_worlds (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_groups (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_texts (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_speakers (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_sounds (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_armatures (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_actions (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_particles (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_gpencil (BlenderRNA *brna, PropertyRNA *cprop)
void RNA_def_main_movieclips (BlenderRNA *brna, PropertyRNA *cprop)
struct IDProperty * rna_idproperty_check (struct PropertyRNA **prop, struct PointerRNA *ptr)
void rna_builtin_properties_begin (struct CollectionPropertyIterator *iter, struct PointerRNA *ptr)
void rna_builtin_properties_next (struct CollectionPropertyIterator *iter)
PointerRNA rna_builtin_properties_get (struct CollectionPropertyIterator *iter)
PointerRNA rna_builtin_type_get (struct PointerRNA *ptr)
int rna_builtin_properties_lookup_string (PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
void rna_iterator_listbase_begin (struct CollectionPropertyIterator *iter, struct ListBase *lb, IteratorSkipFunc skip)
void rna_iterator_listbase_next (struct CollectionPropertyIterator *iter)
void * rna_iterator_listbase_get (struct CollectionPropertyIterator *iter)
void rna_iterator_listbase_end (struct CollectionPropertyIterator *iter)
PointerRNA rna_listbase_lookup_int (PointerRNA *ptr, StructRNA *type, struct ListBase *lb, int index)
void rna_iterator_array_begin (struct CollectionPropertyIterator *iter, void *ptr, int itemsize, int length, int free_ptr, IteratorSkipFunc skip)
void rna_iterator_array_next (struct CollectionPropertyIterator *iter)
void * rna_iterator_array_get (struct CollectionPropertyIterator *iter)
void * rna_iterator_array_dereference_get (struct CollectionPropertyIterator *iter)
void rna_iterator_array_end (struct CollectionPropertyIterator *iter)
PointerRNA rna_array_lookup_int (PointerRNA *ptr, StructRNA *type, void *data, int itemsize, int length, int index)
void rna_addtail (struct ListBase *listbase, void *vlink)
void rna_freelinkN (struct ListBase *listbase, void *vlink)
void rna_freelistN (struct ListBase *listbase)
PropertyDefRNA * rna_findlink (ListBase *listbase, const char *identifier)
StructDefRNA * rna_find_struct_def (StructRNA *srna)
FunctionDefRNA * rna_find_function_def (FunctionRNA *func)
PropertyDefRNA * rna_find_parameter_def (PropertyRNA *parm)
PropertyDefRNA * rna_find_struct_property_def (StructRNA *srna, PropertyRNA *prop)
PointerRNA rna_pointer_inherit_refine (struct PointerRNA *ptr, struct StructRNA *type, void *data)
int rna_parameter_size (struct PropertyRNA *parm)
int rna_parameter_size_alloc (struct PropertyRNA *parm)
struct MTex * rna_mtex_texture_slots_add (struct ID *self, struct bContext *C, struct ReportList *reports)
struct MTex * rna_mtex_texture_slots_create (struct ID *self, struct bContext *C, struct ReportList *reports, int index)
void rna_mtex_texture_slots_clear (struct ID *self, struct bContext *C, struct ReportList *reports, int index)
int rna_IDMaterials_assign_int (struct PointerRNA *ptr, int key, const struct PointerRNA *assign_ptr)
Variables
BlenderDefRNA DefRNA
BlenderRNA BLENDER_RNA
StringPropertyRNA rna_PropertyGroupItem_string
IntPropertyRNA rna_PropertyGroupItem_int
IntPropertyRNA rna_PropertyGroupItem_int_array
FloatPropertyRNA rna_PropertyGroupItem_float
FloatPropertyRNA rna_PropertyGroupItem_float_array
PointerPropertyRNA rna_PropertyGroupItem_group
CollectionPropertyRNA rna_PropertyGroupItem_collection
CollectionPropertyRNA rna_PropertyGroupItem_idp_array
FloatPropertyRNA rna_PropertyGroupItem_double
FloatPropertyRNA rna_PropertyGroupItem_double_array
StructRNA RNA_PropertyGroupItem
StructRNA RNA_PropertyGroup
Detailed Description
Definition in file rna_internal.h.
Define Documentation
#define RNA_MAGIC ((int)~0)
Definition at line 35 of file rna_internal.h.
Referenced by RNA_def_property(), rna_ensure_property(), rna_ensure_property_array_check(), rna_ensure_property_array_length(), rna_ensure_property_description(), rna_ensure_property_identifier(), rna_ensure_property_multi_array_length(), rna_ensure_property_name(), rna_idproperty_check(), RNA_path_from_ID_to_property(), RNA_property_float_range(), RNA_property_float_ui_range(), RNA_property_int_range(), RNA_property_int_ui_range(), RNA_property_is_idprop(), rna_property_update(), RNA_property_update_cache_add(), and RNA_property_update_check().
Typedef Documentation
typedef struct AllocDefRNA AllocDefRNA
typedef struct ArrayIterator ArrayIterator
typedef struct BlenderDefRNA BlenderDefRNA
typedef struct ContainerDefRNA ContainerDefRNA
typedef struct FunctionDefRNA FunctionDefRNA
typedef int(* IteratorSkipFunc)(struct CollectionPropertyIterator *iter, void *data)
Definition at line 328 of file rna_internal.h.
typedef struct ListBaseIterator ListBaseIterator
typedef struct PropertyDefRNA PropertyDefRNA
typedef struct StructDefRNA StructDefRNA
Function Documentation
int rna_Action_actedit_assign_poll (struct PointerRNA * ptr, struct PointerRNA value)
int rna_Action_id_poll (struct PointerRNA * ptr, struct PointerRNA value)
void rna_addtail (struct ListBase * listbase, void * vlink)
Definition at line 73 of file rna_define.c.
References ListBase::first, ListBase::last, link(), Link::next, NULL, and Link::prev.
Referenced by rna_alloc_function_name(), rna_def_function(), RNA_def_property(), RNA_def_struct(), and rna_sortlist().
void RNA_api_action (StructRNA * srna)
Definition at line 50 of file rna_action_api.c.
Referenced by rna_def_action().
void RNA_api_actuator (struct StructRNA * srna)
Definition at line 56 of file rna_actuator_api.c.
References NC_LOGIC, NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_property_update().
Referenced by rna_def_actuator().
void RNA_api_armature_edit_bone (StructRNA * srna)
Definition at line 59 of file rna_armature_api.c.
References FLT_MAX, NULL, PROP_REQUIRED, RNA_def_float_vector(), RNA_def_function(), RNA_def_function_ui_description(), and RNA_def_property_flag().
Referenced by rna_def_edit_bone().
void RNA_api_bone (StructRNA * srna)
Definition at line 71 of file rna_armature_api.c.
References FLT_MAX, NULL, PROP_REQUIRED, RNA_def_float(), RNA_def_float_vector_xyz(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), and RNA_def_property_flag().
Referenced by rna_def_bone().
void RNA_api_camera (StructRNA * srna)
Definition at line 59 of file rna_camera_api.c.
References FLT_MAX, NULL, PROP_THICK_WRAP, RNA_def_float_vector(), RNA_def_function(), RNA_def_function_output(), RNA_def_function_ui_description(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by RNA_def_camera().
void RNA_api_controller (struct StructRNA * srna)
Definition at line 63 of file rna_controller_api.c.
References NC_LOGIC, NULL, RNA_def_function(), RNA_def_function_ui_description(), RNA_def_pointer(), and RNA_def_property_update().
Referenced by RNA_def_controller().
void RNA_api_drivers (StructRNA * srna)
Definition at line 50 of file rna_fcurve_api.c.
Referenced by rna_def_channeldriver().
void RNA_api_environment_map (struct StructRNA * srna)
Definition at line 101 of file rna_texture_api.c.
References FILE_MAX, FUNC_USE_CONTEXT, FUNC_USE_REPORTS, PROP_REQUIRED, RNA_def_float_array(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string_file_name().
Referenced by rna_def_environment_map().
void RNA_api_image (struct StructRNA * srna)
Definition at line 233 of file rna_image_api.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, PF_USE_LOCAL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string_file_path(), and unpack_method_items.
Referenced by rna_def_image().
void RNA_api_keyconfig (struct StructRNA * srna)
Definition at line 372 of file rna_wm_api.c.
Referenced by rna_def_keyconfig().
void RNA_api_keyconfigs (struct StructRNA * srna)
Definition at line 489 of file rna_wm_api.c.
References PROP_REQUIRED, RNA_def_function(), RNA_def_function_return(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string().
Referenced by rna_def_wm_keyconfigs().
void RNA_api_keyingset (struct StructRNA * srna)
Definition at line 70 of file rna_animation_api.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, RNA_def_function(), RNA_def_function_flag(), and RNA_def_function_ui_description().
Referenced by rna_def_keyingset().
void RNA_api_keymap (struct StructRNA * srna)
Definition at line 378 of file rna_wm_api.c.
References FUNC_USE_CONTEXT, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by rna_def_keyconfig().
void RNA_api_keymapitem (struct StructRNA * srna)
Definition at line 397 of file rna_wm_api.c.
References PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_return(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by rna_def_keyconfig().
void RNA_api_keymapitems (struct StructRNA * srna)
Definition at line 409 of file rna_wm_api.c.
References event_type_items, event_value_items, FUNC_USE_REPORTS, PROP_INT, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_ui_text(), and RNA_def_string().
Referenced by rna_def_keymap_items().
void RNA_api_keymaps (struct StructRNA * srna)
Definition at line 460 of file rna_wm_api.c.
References PROP_REQUIRED, region_type_items, RGN_TYPE_WINDOW, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_return(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), SPACE_EMPTY, and space_type_items.
Referenced by rna_def_wm_keymaps().
void RNA_api_macro (struct StructRNA * srna)
Definition at line 341 of file rna_wm_api.c.
References FUNC_NO_SELF, FUNC_REGISTER_OPTIONAL, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum_flag(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), and wm_report_items.
Referenced by rna_def_macro_operator().
void RNA_api_main (struct StructRNA * srna)
Definition at line 602 of file rna_main_api.c.
References PROP_REQUIRED, RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string_file_path().
Referenced by RNA_def_main().
void RNA_api_material (StructRNA * srna)
Definition at line 45 of file rna_material_api.c.
Referenced by RNA_def_material().
void RNA_api_mesh (struct StructRNA * srna)
Definition at line 55 of file rna_mesh_api.c.
References FUNC_USE_CONTEXT, NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_float_matrix(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string().
Referenced by rna_def_mesh().
void RNA_api_object (struct StructRNA * srna)
Definition at line 519 of file rna_object_api.c.
References eModifierMode_Realtime, eModifierMode_Render, FLT_MAX, FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, PROP_RNAPTR, PROP_THICK_WRAP, RNA_def_boolean(), RNA_def_enum(), RNA_def_float(), RNA_def_float_vector(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_output(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_string().
Referenced by rna_def_object().
void RNA_api_object_base (struct StructRNA * srna)
Definition at line 663 of file rna_object_api.c.
References PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_ui_description(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by rna_def_object_base().
void RNA_api_operator (struct StructRNA * srna)
Definition at line 253 of file rna_wm_api.c.
References FUNC_NO_SELF, FUNC_REGISTER_OPTIONAL, NULL, OPERATOR_CANCELLED, operator_return_items, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum_flag(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), and wm_report_items.
Referenced by rna_def_operator().
void RNA_api_pose_channel (struct StructRNA * srna)
Definition at line 67 of file rna_pose_api.c.
References FLT_MAX, NULL, PROP_REQUIRED, RNA_def_float(), RNA_def_float_vector_xyz(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), and RNA_def_property_flag().
Referenced by rna_def_pose_channel().
void RNA_api_scene (struct StructRNA * srna)
Definition at line 97 of file rna_scene_api.c.
References FILE_MAX, MAXFRAME, MINAFRAME, PROP_FILEPATH, PROP_REQUIRED, RNA_def_boolean(), RNA_def_float(), RNA_def_function(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property_flag(), RNA_def_property_subtype(), and RNA_def_string().
Referenced by RNA_def_scene().
void RNA_api_scene_render (struct StructRNA * srna)
Definition at line 125 of file rna_scene_api.c.
References FILE_MAX, MAXFRAME, MINAFRAME, PROP_THICK_WRAP, RNA_def_function(), RNA_def_function_output(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_property_flag(), and RNA_def_string_file_path().
Referenced by rna_def_scene_render_data().
void RNA_api_sensor (struct StructRNA * srna)
Definition at line 56 of file rna_sensor_api.c.
References NC_LOGIC, NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), and RNA_def_property_update().
Referenced by rna_def_sensor().
void RNA_api_sequence_strip (StructRNA * srna)
Definition at line 57 of file rna_sequencer_api.c.
References FUNC_USE_REPORTS, MAXFRAME, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), and RNA_def_property_flag().
Referenced by rna_def_sequence().
void RNA_api_text (struct StructRNA * srna)
Definition at line 52 of file rna_text_api.c.
References PROP_REQUIRED, RNA_def_function(), RNA_def_function_ui_description(), RNA_def_property_flag(), and RNA_def_string().
Referenced by rna_def_text().
void RNA_api_texture (struct StructRNA * srna)
Definition at line 83 of file rna_texture_api.c.
References FLT_MAX, NULL, PROP_REQUIRED, PROP_THICK_WRAP, RNA_def_float_vector(), RNA_def_function(), RNA_def_function_output(), RNA_def_function_ui_description(), and RNA_def_property_flag().
Referenced by rna_def_texture().
void RNA_api_ui_layout (struct StructRNA * srna)
Definition at line 118 of file rna_ui_api.c.
References api_ui_item_common(), api_ui_item_op(), api_ui_item_op_common(), api_ui_item_rna_common(), curve_type_items, FUNC_USE_CONTEXT, NULL, PROP_NEVER_NULL, PROP_REQUIRED, PROP_RNAPTR, RNA_def_boolean(), RNA_def_enum(), RNA_def_float(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_string(), and RNA_def_string_translate().
Referenced by rna_def_ui_layout().
void RNA_api_wm (struct StructRNA * srna)
Definition at line 195 of file rna_wm_api.c.
References FLT_MAX, FUNC_NO_SELF, FUNC_USE_CONTEXT, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_flag(), RNA_def_property_range(), RNA_def_property_ui_text(), rna_generic_op_invoke(), WM_GEN_INVOKE_EVENT, WM_GEN_INVOKE_RETURN, and WM_GEN_INVOKE_SIZE.
Referenced by rna_def_windowmanager().
int rna_Armature_object_poll (struct PointerRNA * ptr, struct PointerRNA value)
PointerRNA rna_array_lookup_int (PointerRNA * ptr, StructRNA * type, void * data, int itemsize, int length, int index)
Definition at line 3485 of file rna_access.c.
References PointerRNA_NULL, and rna_pointer_inherit_refine().
void rna_builtin_properties_begin (struct CollectionPropertyIterator * iter, struct PointerRNA * ptr)
Referenced by RNA_def_struct().
PointerRNA rna_builtin_properties_get (struct CollectionPropertyIterator * iter)
Referenced by RNA_def_struct().
int rna_builtin_properties_lookup_string (PointerRNA * ptr, const char * key, PointerRNA * r_ptr)
void rna_builtin_properties_next (struct CollectionPropertyIterator * iter)
Referenced by RNA_def_struct().
PointerRNA rna_builtin_type_get (struct PointerRNA * ptr)
Referenced by RNA_def_struct().
int rna_Camera_object_poll (struct PointerRNA * ptr, struct PointerRNA value)
int rna_Curve_object_poll (struct PointerRNA * ptr, struct PointerRNA value)
void RNA_def_action (struct BlenderRNA * brna)
Definition at line 640 of file rna_action.c.
References rna_def_action(), rna_def_action_group(), and rna_def_dopesheet().
void RNA_def_actuator (struct BlenderRNA * brna)
Definition at line 2088 of file rna_actuator.c.
References rna_def_action_actuator(), rna_def_actuator(), rna_def_armature_actuator(), rna_def_camera_actuator(), rna_def_constraint_actuator(), rna_def_edit_object_actuator(), rna_def_game_actuator(), rna_def_message_actuator(), rna_def_object_actuator(), rna_def_parent_actuator(), rna_def_property_actuator(), rna_def_random_actuator(), rna_def_scene_actuator(), rna_def_shape_action_actuator(), rna_def_sound_actuator(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_twodfilter_actuator(), and rna_def_visibility_actuator().
void RNA_def_animation (struct BlenderRNA * brna)
Definition at line 886 of file rna_animation.c.
References rna_def_animdata(), rna_def_keyingset(), rna_def_keyingset_info(), and rna_def_keyingset_path().
void rna_def_animdata_common (struct StructRNA * srna)
Definition at line 811 of file rna_animation.c.
References NULL, PROP_EDITABLE, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_pointer_sdna(), and RNA_def_property_ui_text().
Referenced by rna_def_armature(), RNA_def_camera(), rna_def_curve(), rna_def_key(), rna_def_lamp(), rna_def_lattice(), RNA_def_material(), rna_def_mesh(), rna_def_metaball(), rna_def_nodetree(), rna_def_object(), rna_def_particle_settings(), RNA_def_scene(), rna_def_speaker(), rna_def_texture(), and RNA_def_world().
void RNA_def_animviz (struct BlenderRNA * brna)
Definition at line 371 of file rna_animviz.c.
References rna_def_animviz(), rna_def_animviz_ghosts(), rna_def_animviz_motion_path(), rna_def_animviz_motionpath_vert(), and rna_def_animviz_paths().
void rna_def_animviz_common (struct StructRNA * srna)
Definition at line 335 of file rna_animviz.c.
References NULL, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), and RNA_def_property_ui_text().
Referenced by rna_def_object(), and rna_def_pose().
void RNA_def_armature (struct BlenderRNA * brna)
Definition at line 1041 of file rna_armature.c.
References rna_def_armature(), rna_def_bone(), and rna_def_edit_bone().
void RNA_def_boid (struct BlenderRNA * brna)
Definition at line 655 of file rna_boid.c.
References rna_def_boid_settings(), rna_def_boidrule(), and rna_def_boidstate().
void RNA_def_brush (struct BlenderRNA * brna)
Definition at line 936 of file rna_brush.c.
References rna_def_brush(), rna_def_brush_texture_slot(), rna_def_operator_stroke_element(), and rna_def_sculpt_capabilities().
void RNA_def_camera (struct BlenderRNA * brna)
Definition at line 93 of file rna_camera.c.
References CAM_ANGLETOGGLE, CAM_DTX_CENTER, CAM_DTX_CENTER_DIAG, CAM_DTX_GOLDEN, CAM_DTX_GOLDEN_TRI_A, CAM_DTX_GOLDEN_TRI_B, CAM_DTX_HARMONY_TRI_A, CAM_DTX_HARMONY_TRI_B, CAM_DTX_THIRDS, CAM_ORTHO, CAM_PANORAMA, CAM_PERSP, CAM_SHOWLIMITS, CAM_SHOWMIST, CAM_SHOWNAME, CAM_SHOWPASSEPARTOUT, CAM_SHOWSENSOR, CAM_SHOWTITLESAFE, CAMERA_SENSOR_FIT_AUTO, CAMERA_SENSOR_FIT_HOR, CAMERA_SENSOR_FIT_VERT, FLT_MAX, M_PI, NC_OBJECT, ND_DRAW, NULL, PROP_ANGLE, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_DISTANCE, PROP_EDITABLE, PROP_ENUM, PROP_ENUM_FLAG, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_api_camera(), rna_def_animdata_common(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
void RNA_def_cloth (struct BlenderRNA * brna)
Definition at line 521 of file rna_cloth.c.
References rna_def_cloth_collision_settings(), and rna_def_cloth_sim_settings().
void RNA_def_color (struct BlenderRNA * brna)
Definition at line 607 of file rna_color.c.
References rna_def_color_ramp(), rna_def_color_ramp_element(), rna_def_curvemap(), rna_def_curvemapping(), rna_def_curvemappoint(), rna_def_histogram(), and rna_def_scopes().
void RNA_def_constraint (struct BlenderRNA * brna)
Definition at line 2297 of file rna_constraint.c.
References CONSTRAINT_ACTIVE, CONSTRAINT_DISABLE, CONSTRAINT_EXPAND, CONSTRAINT_OFF, CONSTRAINT_PROXY_LOCAL, NA_RENAME, NC_OBJECT, ND_CONSTRAINT, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_NONE, PROP_STRING, rna_def_constraint_action(), rna_def_constraint_camera_solver(), rna_def_constraint_childof(), rna_def_constraint_clamp_to(), rna_def_constraint_damped_track(), rna_def_constraint_distance_limit(), rna_def_constraint_follow_path(), rna_def_constraint_follow_track(), rna_def_constraint_kinematic(), rna_def_constraint_locate_like(), rna_def_constraint_location_limit(), rna_def_constraint_locked_track(), rna_def_constraint_minmax(), rna_def_constraint_object_solver(), rna_def_constraint_pivot(), rna_def_constraint_python(), rna_def_constraint_rigid_body_joint(), rna_def_constraint_rotate_like(), rna_def_constraint_rotation_limit(), rna_def_constraint_same_volume(), rna_def_constraint_shrinkwrap(), rna_def_constraint_size_like(), rna_def_constraint_size_limit(), rna_def_constraint_spline_ik(), rna_def_constraint_stretch_to(), rna_def_constraint_track_to(), rna_def_constraint_transform(), rna_def_constraint_transform_like(), rna_def_constrainttarget(), RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
void RNA_def_context (struct BlenderRNA * brna)
Definition at line 132 of file rna_context.c.
References CTX_MODE_EDIT_ARMATURE, CTX_MODE_EDIT_CURVE, CTX_MODE_EDIT_LATTICE, CTX_MODE_EDIT_MESH, CTX_MODE_EDIT_METABALL, CTX_MODE_EDIT_SURFACE, CTX_MODE_EDIT_TEXT, CTX_MODE_OBJECT, CTX_MODE_PAINT_TEXTURE, CTX_MODE_PAINT_VERTEX, CTX_MODE_PAINT_WEIGHT, CTX_MODE_PARTICLE, CTX_MODE_POSE, CTX_MODE_SCULPT, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
void RNA_def_controller (struct BlenderRNA * brna)
Definition at line 184 of file rna_controller.c.
References CONT_PRIO, CONT_PY_DEBUG, CONT_PY_MODULE, CONT_PY_SCRIPT, CONT_SHOW, NC_LOGIC, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_UNSIGNED, RNA_api_controller(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
void RNA_def_curve (struct BlenderRNA * brna)
Definition at line 1637 of file rna_curve.c.
References rna_def_beztriple(), rna_def_bpoint(), rna_def_charinfo(), rna_def_curve(), rna_def_curve_nurb(), rna_def_surface(), rna_def_text(), and rna_def_textbox().
void RNA_def_dynamic_paint (struct BlenderRNA * brna)
Definition at line 957 of file rna_dynamicpaint.c.
References rna_def_canvas_surface(), rna_def_dynamic_paint_brush_settings(), and rna_def_dynamic_paint_canvas_settings().
void RNA_def_fcurve (struct BlenderRNA * brna)
Definition at line 1637 of file rna_fcurve.c.
References rna_def_channeldriver(), rna_def_drivertarget(), rna_def_drivervar(), rna_def_fcurve(), rna_def_fkeyframe(), rna_def_fmodifier(), rna_def_fmodifier_cycles(), rna_def_fmodifier_envelope(), rna_def_fmodifier_envelope_ctrl(), rna_def_fmodifier_function_generator(), rna_def_fmodifier_generator(), rna_def_fmodifier_limits(), rna_def_fmodifier_noise(), rna_def_fmodifier_python(), rna_def_fmodifier_stepped(), and rna_def_fpoint().
void RNA_def_fluidsim (struct BlenderRNA * brna)
Definition at line 660 of file rna_fluidsim.c.
References NULL, OB_FLUIDSIM_CONTROL, OB_FLUIDSIM_DOMAIN, OB_FLUIDSIM_ENABLE, OB_FLUIDSIM_FLUID, OB_FLUIDSIM_INFLOW, OB_FLUIDSIM_OBSTACLE, OB_FLUIDSIM_OUTFLOW, OB_FLUIDSIM_PARTICLE, PROP_ANIMATABLE, PROP_ENUM, PROP_NONE, rna_def_fluidsim_control(), rna_def_fluidsim_domain(), rna_def_fluidsim_fluid(), rna_def_fluidsim_inflow(), rna_def_fluidsim_obstacle(), rna_def_fluidsim_outflow(), rna_def_fluidsim_particle(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_items(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
void RNA_def_gameproperty (struct BlenderRNA * brna)
Definition at line 105 of file rna_property.c.
References MAX_PROPSTRING, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_DEBUG, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_float_funcs(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
void RNA_def_gpencil (struct BlenderRNA * brna)
Definition at line 356 of file rna_gpencil.c.
References rna_def_gpencil_data(), rna_def_gpencil_frame(), rna_def_gpencil_layer(), rna_def_gpencil_stroke(), and rna_def_gpencil_stroke_point().
void RNA_def_group (struct BlenderRNA * brna)
Definition at line 108 of file rna_group.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_FLOAT, PROP_LAYER, PROP_NONE, PROP_TRANSLATION, rna_def_group_objects(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_float_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), RNA_TRANSLATION_PREC_DEFAULT, PropertyRNA::srna, and STRUCT_ID_REFCOUNT.
void RNA_def_ID (struct BlenderRNA * brna)
Definition at line 558 of file rna_ID.c.
References NULL, rna_def_ID(), rna_def_ID_materials(), rna_def_ID_properties(), rna_def_library(), RNA_def_struct(), RNA_def_struct_ui_text(), and PropertyRNA::srna.
void RNA_def_image (struct BlenderRNA * brna)
Definition at line 637 of file rna_image.c.
References rna_def_image(), and rna_def_imageuser().
void RNA_def_key (struct BlenderRNA * brna)
Definition at line 645 of file rna_key.c.
References rna_def_key(), rna_def_keyblock(), and rna_def_keydata().
void RNA_def_lamp (struct BlenderRNA * brna)
Definition at line 786 of file rna_lamp.c.
References rna_def_area_lamp(), rna_def_hemi_lamp(), rna_def_lamp(), rna_def_lamp_mtex(), rna_def_point_lamp(), rna_def_spot_lamp(), and rna_def_sun_lamp().
void RNA_def_lattice (struct BlenderRNA * brna)
Definition at line 329 of file rna_lattice.c.
References rna_def_lattice(), and rna_def_latticepoint().
void RNA_def_main (struct BlenderRNA * brna)
Definition at line 282 of file rna_main.c.
References FILE_MAX, MainCollectionDef::func, i, MainCollectionDef::name, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FILEPATH, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_api_main(), RNA_def_main_actions(), RNA_def_main_armatures(), RNA_def_main_brushes(), RNA_def_main_cameras(), RNA_def_main_curves(), RNA_def_main_fonts(), RNA_def_main_gpencil(), RNA_def_main_groups(), RNA_def_main_images(), RNA_def_main_lamps(), RNA_def_main_lattices(), RNA_def_main_libraries(), RNA_def_main_materials(), RNA_def_main_meshes(), RNA_def_main_metaballs(), RNA_def_main_movieclips(), RNA_def_main_node_groups(), RNA_def_main_objects(), RNA_def_main_particles(), RNA_def_main_scenes(), RNA_def_main_screens(), RNA_def_main_sounds(), RNA_def_main_speakers(), RNA_def_main_texts(), RNA_def_main_textures(), RNA_def_main_window_managers(), RNA_def_main_worlds(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_pointer_funcs(), RNA_def_property_string_funcs(), RNA_def_property_string_maxlength(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), and RNA_define_verify_sdna().
void RNA_def_main_actions (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1401 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_armatures (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1367 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_brushes (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1161 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_cameras (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 618 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_curves (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1020 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, object_type_curve_items, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_fonts (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1090 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_gpencil (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1470 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_groups (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1231 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_images (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 936 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_int(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_lamps (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 837 of file rna_main_api.c.
References FUNC_USE_REPORTS, lamp_type_items, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_lattices (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 986 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_libraries (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 874 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_materials (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 727 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_meshes (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 803 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_metaballs (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1056 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_movieclips (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1491 of file rna_main_api.c.
References FILE_MAX, FUNC_USE_REPORTS, NULL, PROP_NEVER_NULL, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_node_groups (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 761 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_objects (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 688 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_particles (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1435 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_scenes (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 653 of file rna_main_api.c.
References FUNC_USE_CONTEXT, FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_screens (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 895 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_sounds (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1344 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_speakers (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1265 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_texts (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1300 of file rna_main_api.c.
References FILE_MAX, FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_string_file_path(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_textures (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1125 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_enum(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), and texture_type_items.
Referenced by RNA_def_main().
void RNA_def_main_window_managers (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 916 of file rna_main_api.c.
References NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_main_worlds (BlenderRNA * brna, PropertyRNA * cprop)
Definition at line 1196 of file rna_main_api.c.
References FUNC_USE_REPORTS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_NEVER_NULL, PROP_NONE, PROP_REQUIRED, RNA_def_boolean(), RNA_def_function(), RNA_def_function_flag(), RNA_def_function_return(), RNA_def_function_ui_description(), RNA_def_pointer(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_srna(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_main().
void RNA_def_material (struct BlenderRNA * brna)
Definition at line 1671 of file rna_material.c.
References FLT_MAX, MA_APPROX_OCCLUSION, MA_CUBE, MA_CUBIC, MA_ENV, MA_FACETEXTURE, MA_FACETEXTURE_ALPHA, MA_FLAT, MA_FULL_OSA, MA_GROUP_NOLAY, MA_HAIR, MA_MONKEY, MA_NOMIST, MA_OBCOLOR, MA_ONLYCAST, MA_ONLYSHADOW, MA_RAYBIAS, MA_RAYTRANSP, MA_SHADBUF, MA_SHADOW, MA_SHADOW_TRA, MA_SHLESS, MA_SO_OLD, MA_SO_SHADED, MA_SO_SHADOW, MA_SPHERE, MA_SPHERE_A, MA_TANGENT_V, MA_TRACEBLE, MA_TRANSP, MA_TYPE_HALO, MA_TYPE_SURFACE, MA_TYPE_VOLUME, MA_TYPE_WIRE, MA_VERTEXCOL, MA_VERTEXCOLP, MA_ZINV, MA_ZTRANSP, NC_MATERIAL, NC_OBJECT, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FACTOR, PROP_FLOAT, PROP_INT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_api_material(), rna_def_animdata_common(), rna_def_material_colors(), rna_def_material_diffuse(), rna_def_material_gamesettings(), rna_def_material_halo(), rna_def_material_mtex(), rna_def_material_physics(), rna_def_material_raymirror(), rna_def_material_raytra(), rna_def_material_specularity(), rna_def_material_sss(), rna_def_material_strand(), rna_def_material_volume(), rna_def_mtex_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
void RNA_def_mesh (struct BlenderRNA * brna)
Definition at line 2827 of file rna_mesh.c.
References rna_def_mcol(), rna_def_medge(), rna_def_mesh(), rna_def_mface(), rna_def_mloop(), rna_def_mloopcol(), rna_def_mloopuv(), rna_def_mpolygon(), rna_def_mproperties(), rna_def_msticky(), rna_def_mtexpoly(), rna_def_mtface(), rna_def_mvert(), and rna_def_mvert_group().
void RNA_def_meta (struct BlenderRNA * brna)
Definition at line 355 of file rna_meta.c.
References rna_def_metaball(), and rna_def_metaelement().
void RNA_def_modifier (struct BlenderRNA * brna)
Definition at line 3158 of file rna_modifier.c.
References eModifierMode_ApplyOnSpline, eModifierMode_Editmode, eModifierMode_Expanded, eModifierMode_OnCage, eModifierMode_Realtime, eModifierMode_Render, NA_RENAME, NC_OBJECT, ND_MODIFIER, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_LIB_EXCEPTION, PROP_NONE, PROP_STRING, rna_def_modifier_armature(), rna_def_modifier_array(), rna_def_modifier_bevel(), rna_def_modifier_boolean(), rna_def_modifier_build(), rna_def_modifier_cast(), rna_def_modifier_cloth(), rna_def_modifier_collision(), rna_def_modifier_curve(), rna_def_modifier_decimate(), rna_def_modifier_displace(), rna_def_modifier_dynamic_paint(), rna_def_modifier_edgesplit(), rna_def_modifier_explode(), rna_def_modifier_fluidsim(), rna_def_modifier_hook(), rna_def_modifier_lattice(), rna_def_modifier_mask(), rna_def_modifier_meshdeform(), rna_def_modifier_mirror(), rna_def_modifier_multires(), rna_def_modifier_ocean(), rna_def_modifier_particleinstance(), rna_def_modifier_particlesystem(), rna_def_modifier_remesh(), rna_def_modifier_screw(), rna_def_modifier_shrinkwrap(), rna_def_modifier_simpledeform(), rna_def_modifier_smoke(), rna_def_modifier_smooth(), rna_def_modifier_softbody(), rna_def_modifier_solidify(), rna_def_modifier_subsurf(), rna_def_modifier_surface(), rna_def_modifier_uvproject(), rna_def_modifier_warp(), rna_def_modifier_wave(), rna_def_modifier_weightvgedit(), rna_def_modifier_weightvgmix(), rna_def_modifier_weightvgproximity(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_string_funcs(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_path_func(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
void rna_def_motionpath_common (struct StructRNA * srna)
Definition at line 89 of file rna_animviz.c.
References NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_pointer_sdna(), and RNA_def_property_ui_text().
Referenced by rna_def_object(), and rna_def_pose_channel().
void RNA_def_movieclip (struct BlenderRNA * brna)
Definition at line 286 of file rna_movieclip.c.
References rna_def_movieclip(), rna_def_movieclip_proxy(), rna_def_movieClipScopes(), and rna_def_moviecliUser().
void rna_def_mtex_common (struct BlenderRNA * brna, struct StructRNA * srna, const char * begin, const char * activeget, const char * activeset, const char * activeeditable, const char * structname, const char * structname_slots, const char * update)
Definition at line 2054 of file rna_material.c.
References NULL, PROP_COLLECTION, PROP_EDITABLE, PROP_INT, PROP_NONE, PROP_POINTER, PROP_UNSIGNED, RNA_def_property(), RNA_def_property_collection_funcs(), RNA_def_property_editable_func(), RNA_def_property_flag(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), and rna_def_texture_slots().
Referenced by rna_def_lamp(), RNA_def_material(), rna_def_particle_settings(), and RNA_def_world().
void RNA_def_nla (struct BlenderRNA * brna)
Definition at line 663 of file rna_nla.c.
References rna_def_nlastrip(), and rna_def_nlatrack().
void RNA_def_nodetree (struct BlenderRNA * brna)
void RNA_def_object (struct BlenderRNA * brna)
Definition at line 2535 of file rna_object.c.
References rna_def_dupli_object(), rna_def_material_slot(), rna_def_object(), rna_def_object_base(), rna_def_object_game_settings(), and rna_def_vertex_group().
void RNA_def_object_force (struct BlenderRNA * brna)
Definition at line 1794 of file rna_object_force.c.
References rna_def_collision(), rna_def_effector_weight(), rna_def_field(), rna_def_game_softbody(), rna_def_pointcache(), and rna_def_softbody().
void RNA_def_packedfile (struct BlenderRNA * brna)
Definition at line 46 of file rna_packedfile.c.
References NULL, PROP_EDITABLE, PROP_INT, PROP_NONE, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_ui_text(), RNA_def_struct(), and RNA_def_struct_ui_text().
void RNA_def_particle (struct BlenderRNA * brna)
Definition at line 2980 of file rna_particle.c.
References rna_def_child_particle(), rna_def_fluid_settings(), rna_def_particle(), rna_def_particle_dupliweight(), rna_def_particle_hair_key(), rna_def_particle_key(), rna_def_particle_settings(), rna_def_particle_settings_mtex(), rna_def_particle_system(), and rna_def_particle_target().
void RNA_def_pose (struct BlenderRNA * brna)
Definition at line 1317 of file rna_pose.c.
References rna_def_bone_group(), rna_def_pose(), rna_def_pose_channel(), rna_def_pose_ikparam(), and rna_def_pose_itasc().
void RNA_def_render (struct BlenderRNA * brna)
Definition at line 529 of file rna_render.c.
References rna_def_render_engine(), rna_def_render_layer(), rna_def_render_pass(), and rna_def_render_result().
void rna_def_render_layer_common (struct StructRNA * srna, int scene)
Definition at line 1862 of file rna_scene.c.
References NC_SCENE, ND_RENDER_OPTIONS, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_LAYER, PROP_LAYER_MEMBER, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_funcs(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct_name_property(), SCE_LAY_ALL_Z, SCE_LAY_DISABLE, SCE_LAY_EDGE, SCE_LAY_HALO, SCE_LAY_NEG_ZMASK, SCE_LAY_SKY, SCE_LAY_SOLID, SCE_LAY_STRAND, SCE_LAY_ZMASK, SCE_LAY_ZTRA, SCE_PASS_AO, SCE_PASS_COMBINED, SCE_PASS_DIFFUSE, SCE_PASS_DIFFUSE_COLOR, SCE_PASS_DIFFUSE_DIRECT, SCE_PASS_DIFFUSE_INDIRECT, SCE_PASS_EMIT, SCE_PASS_ENVIRONMENT, SCE_PASS_GLOSSY_COLOR, SCE_PASS_GLOSSY_DIRECT, SCE_PASS_GLOSSY_INDIRECT, SCE_PASS_INDEXMA, SCE_PASS_INDEXOB, SCE_PASS_INDIRECT, SCE_PASS_MIST, SCE_PASS_NORMAL, SCE_PASS_REFLECT, SCE_PASS_REFRACT, SCE_PASS_RGBA, SCE_PASS_SHADOW, SCE_PASS_SPEC, SCE_PASS_TRANSM_COLOR, SCE_PASS_TRANSM_DIRECT, SCE_PASS_TRANSM_INDIRECT, SCE_PASS_UV, SCE_PASS_VECTOR, and SCE_PASS_Z.
Referenced by rna_def_render_layer(), and rna_def_scene_render_layer().
void RNA_def_rna (struct BlenderRNA * brna)
Definition at line 1399 of file rna_rna.c.
References NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, rna_def_enum_property(), rna_def_function(), rna_def_number_property(), rna_def_pointer_property(), rna_def_property(), RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), rna_def_string_property(), RNA_def_struct(), rna_def_struct(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
void RNA_def_scene (struct BlenderRNA * brna)
Definition at line 4086 of file rna_scene.c.
References AUDIO_SCRUB, AUDIO_SYNC, FLT_MAX, MAXFRAME, MINAFRAME, MINFRAME, NA_EDITED, NC_SCENE, NC_SPACE, NC_WINDOW, ND_FRAME, ND_FRAME_RANGE, ND_KEYINGSET, ND_LAYER, ND_RENDER_OPTIONS, ND_SPACE_GRAPH, ND_SPACE_VIEW3D, ND_WORLD, NULL, PHYS_GLOBAL_GRAVITY, PROP_ACCELERATION, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLLECTION, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_ID_SELF_CHECK, PROP_INT, PROP_LAYER_MEMBER, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, PROP_STRING, PROP_TIME, PROP_XYZ_LENGTH, RNA_api_scene(), rna_def_animdata_common(), RNA_def_function(), RNA_def_function_return(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_enum_bitflag_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_funcs(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_icon(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), rna_def_scene_bases(), rna_def_scene_game_data(), rna_def_scene_image_format_data(), rna_def_scene_keying_sets(), rna_def_scene_keying_sets_all(), rna_def_scene_objects(), rna_def_scene_render_data(), rna_def_scene_render_layer(), rna_def_selected_uv_element(), RNA_def_string(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), rna_def_timeline_markers(), rna_def_tool_settings(), rna_def_transform_orientation(), rna_def_unified_paint_settings(), rna_def_unit_settings(), SCE_FRAME_DROP, SCE_NLA_EDIT_ON, SCER_PRV_RANGE, and STRUCT_ID_REFCOUNT.
void RNA_def_screen (struct BlenderRNA * brna)
Definition at line 302 of file rna_screen.c.
References rna_def_area(), rna_def_region(), and rna_def_screen().
void RNA_def_sculpt_paint (struct BlenderRNA * brna)
Definition at line 560 of file rna_sculpt_paint.c.
References rna_def_image_paint(), rna_def_paint(), rna_def_particle_edit(), rna_def_sculpt(), rna_def_uv_sculpt(), and rna_def_vertex_paint().
void RNA_def_sensor (struct BlenderRNA * brna)
Definition at line 894 of file rna_sensor.c.
References rna_def_actuator_sensor(), rna_def_always_sensor(), rna_def_armature_sensor(), rna_def_collision_sensor(), rna_def_delay_sensor(), rna_def_joystick_sensor(), rna_def_keyboard_sensor(), rna_def_message_sensor(), rna_def_mouse_sensor(), rna_def_near_sensor(), rna_def_property_sensor(), rna_def_radar_sensor(), rna_def_random_sensor(), rna_def_ray_sensor(), rna_def_sensor(), and rna_def_touch_sensor().
void RNA_def_sequencer (struct BlenderRNA * brna)
Definition at line 1831 of file rna_sequencer.c.
References rna_def_adjustment(), rna_def_editor(), rna_def_effect(), rna_def_glow(), rna_def_image(), rna_def_meta(), rna_def_movie(), rna_def_movieclip(), rna_def_multicam(), rna_def_plugin(), rna_def_scene(), rna_def_sequence(), rna_def_solid_color(), rna_def_sound(), rna_def_speed_control(), rna_def_strip_color_balance(), rna_def_strip_crop(), rna_def_strip_element(), rna_def_strip_proxy(), rna_def_strip_transform(), rna_def_transform(), and rna_def_wipe().
void RNA_def_smoke (struct BlenderRNA * brna)
Definition at line 347 of file rna_smoke.c.
References rna_def_smoke_coll_settings(), rna_def_smoke_domain_settings(), and rna_def_smoke_flow_settings().
void RNA_def_sound (struct BlenderRNA * brna)
Definition at line 102 of file rna_sound.c.
References rna_def_sound().
void RNA_def_space (struct BlenderRNA * brna)
Definition at line 3110 of file rna_space.c.
References rna_def_background_image(), rna_def_console_line(), rna_def_fileselect_params(), rna_def_space(), rna_def_space_buttons(), rna_def_space_clip(), rna_def_space_console(), rna_def_space_dopesheet(), rna_def_space_filebrowser(), rna_def_space_graph(), rna_def_space_image(), rna_def_space_info(), rna_def_space_logic(), rna_def_space_nla(), rna_def_space_node(), rna_def_space_outliner(), rna_def_space_sequencer(), rna_def_space_text(), rna_def_space_time(), rna_def_space_userpref(), and rna_def_space_view3d().
void RNA_def_speaker (struct BlenderRNA * brna)
Definition at line 169 of file rna_speaker.c.
References rna_def_speaker().
void RNA_def_test (struct BlenderRNA * brna)
Definition at line 118 of file rna_test.c.
References ARRAY_SIZE, DYNAMIC_ARRAY_SIZE, DYNAMIC_MARRAY_SIZE, MARRAY_DIMSIZE, MARRAY_SIZE, MARRAY_TOTDIM, NULL, PROP_BOOLEAN, PROP_DYNAMIC, PROP_FLOAT, PROP_INT, PROP_NONE, RNA_def_boolean_array(), RNA_def_float_array(), RNA_def_int_array(), RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_dynamic_array_funcs(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_int_funcs(), RNA_def_struct(), and RNA_def_struct_sdna().
void rna_def_texmat_common (struct StructRNA * srna, const char * texspace_editable)
Definition at line 2056 of file rna_mesh.c.
References ME_AUTOSPACE, NULL, PROP_BOOLEAN, PROP_COLLECTION, PROP_FLOAT, PROP_NONE, PROP_TRANSLATION, PROP_XYZ, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_collection_funcs(), RNA_def_property_collection_sdna(), RNA_def_property_editable_func(), RNA_def_property_float_sdna(), RNA_def_property_srna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), and RNA_def_property_update().
Referenced by rna_def_mesh().
void RNA_def_text (struct BlenderRNA * brna)
Definition at line 251 of file rna_text.c.
References rna_def_text(), rna_def_text_line(), and rna_def_text_marker().
void RNA_def_texture (struct BlenderRNA * brna)
Definition at line 2029 of file rna_texture.c.
References rna_def_colormapping(), rna_def_environment_map(), rna_def_mtex(), rna_def_texmapping(), and rna_def_texture().
void RNA_def_timeline_marker (struct BlenderRNA * brna)
Definition at line 82 of file rna_timeline.c.
References rna_def_timeline_marker().
void RNA_def_tracking (struct BlenderRNA * brna)
Definition at line 1434 of file rna_tracking.c.
References rna_def_tracking().
void RNA_def_ui (struct BlenderRNA * brna)
Definition at line 848 of file rna_ui.c.
References rna_def_header(), rna_def_menu(), rna_def_panel(), and rna_def_ui_layout().
void RNA_def_userdef (struct BlenderRNA * brna)
Definition at line 3476 of file rna_userdef.c.
References NULL, PROP_COLLECTION, PROP_ENUM, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_collection_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_funcs(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_clear_flag(), RNA_def_struct_sdna(), RNA_def_struct_ui_text(), rna_def_userdef_addon(), rna_def_userdef_addon_collection(), rna_def_userdef_dothemes(), rna_def_userdef_edit(), rna_def_userdef_filepaths(), rna_def_userdef_input(), rna_def_userdef_solidlight(), rna_def_userdef_system(), rna_def_userdef_view(), STRUCT_UNDO, USER_SECTION_ADDONS, USER_SECTION_EDIT, USER_SECTION_FILE, USER_SECTION_INPUT, USER_SECTION_INTERFACE, USER_SECTION_SYSTEM, and USER_SECTION_THEME.
void RNA_def_vfont (struct BlenderRNA * brna)
Definition at line 40 of file rna_vfont.c.
References NULL, PROP_EDITABLE, PROP_FILEPATH, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_clear_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_struct(), RNA_def_struct_sdna(), RNA_def_struct_ui_icon(), and RNA_def_struct_ui_text().
void RNA_def_wm (struct BlenderRNA * brna)
Definition at line 1882 of file rna_wm.c.
References rna_def_event(), rna_def_keyconfig(), rna_def_macro_operator(), rna_def_operator(), rna_def_operator_filelist_element(), rna_def_operator_type_macro(), rna_def_operator_utils(), rna_def_timer(), rna_def_window(), and rna_def_windowmanager().
void RNA_def_world (struct BlenderRNA * brna)
Definition at line 486 of file rna_world.c.
References NC_WORLD, ND_WORLD_DRAW, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_COLOR, PROP_FLOAT, PROP_NEVER_NULL, PROP_NONE, PROP_POINTER, rna_def_animdata_common(), rna_def_lighting(), rna_def_mtex_common(), RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_ui_icon(), RNA_def_struct_ui_text(), rna_def_world_mist(), rna_def_world_mtex(), rna_def_world_stars(), WO_SKYBLEND, WO_SKYPAPER, WO_SKYREAL, WOPHY_BULLET, and WOPHY_NONE.
FunctionDefRNA* rna_find_function_def (FunctionRNA * func)
Definition at line 197 of file rna_define.c.
References FunctionDefRNA::cont, StructDefRNA::cont, FunctionDefRNA::func, StructDefRNA::functions, ListBase::last, BlenderDefRNA::laststruct, NULL, BlenderDefRNA::preprocess, ContainerDefRNA::prev, rna_find_struct_def(), and BlenderDefRNA::structs.
Referenced by RNA_def_function(), rna_find_container_def(), rna_generate_static_function_prototypes(), and rna_generate_struct().
PropertyDefRNA* rna_find_parameter_def (PropertyRNA * parm)
Definition at line 225 of file rna_define.c.
References FunctionDefRNA::cont, StructDefRNA::cont, StructDefRNA::functions, ListBase::last, BlenderDefRNA::laststruct, NULL, BlenderDefRNA::preprocess, ContainerDefRNA::prev, PropertyDefRNA::prev, PropertyDefRNA::prop, ContainerDefRNA::properties, rna_find_struct_def(), and BlenderDefRNA::structs.
Referenced by rna_def_function_funcs().
StructDefRNA* rna_find_struct_def (StructRNA * srna)
Definition at line 128 of file rna_define.c.
References StructDefRNA::cont, ListBase::last, NULL, BlenderDefRNA::preprocess, ContainerDefRNA::prev, StructDefRNA::srna, and BlenderDefRNA::structs.
Referenced by rna_def_function(), RNA_def_property_collection_sdna(), rna_def_property_sdna(), rna_find_container_def(), rna_find_function_def(), rna_find_parameter_def(), rna_find_struct_property_def(), and rna_generate_static_parameter_prototypes().
PropertyDefRNA* rna_find_struct_property_def (StructRNA * srna, PropertyRNA * prop)
Definition at line 146 of file rna_define.c.
References StructDefRNA::cont, ListBase::last, NULL, BlenderDefRNA::preprocess, ContainerDefRNA::prev, PropertyDefRNA::prev, PropertyDefRNA::prop, ContainerDefRNA::properties, rna_find_struct_def(), and BlenderDefRNA::structs.
Referenced by RNA_def_property_boolean_negative_sdna(), RNA_def_property_enum_bitflag_sdna(), rna_def_property_sdna(), and rna_set_raw_offset().
PropertyDefRNA* rna_findlink (ListBase * listbase, const char * identifier)
Definition at line 96 of file rna_define.c.
References ListBase::first, PropertyRNA::identifier, link(), Link::next, and NULL.
Referenced by RNA_def_property().
void rna_freelinkN (struct ListBase * listbase, void * vlink)
Definition at line 110 of file rna_define.c.
References MEM_freeN(), and rna_remlink().
Referenced by RNA_struct_free().
void rna_freelistN (struct ListBase * listbase)
Definition at line 116 of file rna_define.c.
References ListBase::first, ListBase::last, link(), MEM_freeN(), next, Link::next, and NULL.
Referenced by RNA_define_free(), and RNA_free().
void rna_ID_fake_user_set (struct PointerRNA * ptr, int value)
struct IDProperty* rna_ID_idprops (struct PointerRNA * ptr, int create) [read]
void rna_ID_name_get (struct PointerRNA * ptr, char * value)
int rna_ID_name_length (struct PointerRNA * ptr)
void rna_ID_name_set (struct PointerRNA * ptr, const char * value)
struct StructRNA* rna_ID_refine (struct PointerRNA * ptr) [read]
Referenced by RNA_id_pointer_create(), and RNA_pointer_create().
int rna_IDMaterials_assign_int (struct PointerRNA * ptr, int key, const struct PointerRNA * assign_ptr)
struct IDProperty* rna_idproperty_check (struct PropertyRNA ** prop, struct PointerRNA * ptr) [read]
Definition at line 392 of file rna_access.c.
References IDP_ARRAY, IDP_FreeProperty(), IDP_RemFromGroup(), MEM_freeN(), NULL, PROP_IDPROPERTY, rna_idproperty_find(), rna_idproperty_verify_valid(), RNA_MAGIC, RNA_struct_idprops(), IDProperty::subtype, and IDProperty::type.
Referenced by RNA_property_boolean_get(), RNA_property_boolean_get_array(), RNA_property_boolean_set(), RNA_property_boolean_set_array(), RNA_property_collection_add(), RNA_property_collection_begin(), RNA_property_collection_clear(), RNA_property_collection_length(), RNA_property_collection_move(), RNA_property_collection_remove(), RNA_property_enum_get(), RNA_property_enum_set(), RNA_property_float_get(), RNA_property_float_get_array(), RNA_property_float_set(), RNA_property_float_set_array(), RNA_property_int_get(), RNA_property_int_get_array(), RNA_property_int_set(), RNA_property_int_set_array(), RNA_property_pointer_add(), RNA_property_pointer_get(), RNA_property_pointer_remove(), RNA_property_pointer_set(), RNA_property_string_get(), RNA_property_string_length(), and RNA_property_string_set().
void rna_iterator_array_begin (struct CollectionPropertyIterator * iter, void * ptr, int itemsize, int length, int free_ptr, IteratorSkipFunc skip)
Definition at line 3415 of file rna_access.c.
References CollectionPropertyIterator::internal, length(), MEM_callocN(), NULL, tRnaUpdateCacheElem::ptr, CollectionPropertyIterator::ptr, rna_iterator_array_next(), and CollectionPropertyIterator::valid.
Referenced by RNA_property_collection_begin().
void* rna_iterator_array_dereference_get (struct CollectionPropertyIterator * iter)
Definition at line 3465 of file rna_access.c.
References CollectionPropertyIterator::internal.
void rna_iterator_array_end (struct CollectionPropertyIterator * iter)
Definition at line 3473 of file rna_access.c.
References CollectionPropertyIterator::internal, MEM_freeN(), and NULL.
Referenced by RNA_property_collection_end().
void* rna_iterator_array_get (struct CollectionPropertyIterator * iter)
Definition at line 3458 of file rna_access.c.
References CollectionPropertyIterator::internal.
Referenced by rna_property_collection_get_idp().
void rna_iterator_array_next (struct CollectionPropertyIterator * iter)
Definition at line 3442 of file rna_access.c.
References CollectionPropertyIterator::internal, CollectionPropertyIterator::ptr, and CollectionPropertyIterator::valid.
Referenced by rna_iterator_array_begin(), and RNA_property_collection_next().
void rna_iterator_listbase_begin (struct CollectionPropertyIterator * iter, struct ListBase * lb, IteratorSkipFunc skip)
Definition at line 3365 of file rna_access.c.
References ListBase::first, CollectionPropertyIterator::internal, MEM_callocN(), NULL, rna_iterator_listbase_next(), and CollectionPropertyIterator::valid.
void rna_iterator_listbase_end (struct CollectionPropertyIterator * iter)
Definition at line 3403 of file rna_access.c.
References CollectionPropertyIterator::internal, MEM_freeN(), and NULL.
void* rna_iterator_listbase_get (struct CollectionPropertyIterator * iter)
Definition at line 3396 of file rna_access.c.
References CollectionPropertyIterator::internal.
void rna_iterator_listbase_next (struct CollectionPropertyIterator * iter)
Definition at line 3380 of file rna_access.c.
References CollectionPropertyIterator::internal, NULL, and CollectionPropertyIterator::valid.
Referenced by rna_iterator_listbase_begin().
int rna_Lattice_object_poll (struct PointerRNA * ptr, struct PointerRNA value)
PointerRNA rna_listbase_lookup_int (PointerRNA * ptr, StructRNA * type, struct ListBase * lb, int index)
Definition at line 3409 of file rna_access.c.
References BLI_findlink(), data, and rna_pointer_inherit_refine().
int rna_Mesh_object_poll (struct PointerRNA * ptr, struct PointerRNA value)
void rna_Mesh_update_draw (struct Main * bmain, struct Scene * scene, struct PointerRNA * ptr)
struct MTex* rna_mtex_texture_slots_add (struct ID * self, struct bContext * C, struct ReportList * reports) [read]
void rna_mtex_texture_slots_clear (struct ID * self, struct bContext * C, struct ReportList * reports, int index)
struct MTex* rna_mtex_texture_slots_create (struct ID * self, struct bContext * C, struct ReportList * reports, int index) [read]
void rna_Object_internal_update_data (struct Main * bmain, struct Scene * scene, struct PointerRNA * ptr)
PointerRNA rna_object_shapekey_index_get (struct ID * id, int value)
int rna_object_shapekey_index_set (struct ID * id, PointerRNA value, int current)
void rna_object_uvlayer_name_set (struct PointerRNA * ptr, const char * value, char * result, int maxlen)
void rna_object_vcollayer_name_set (struct PointerRNA * ptr, const char * value, char * result, int maxlen)
void rna_object_vgroup_name_index_get (struct PointerRNA * ptr, char * value, int index)
int rna_object_vgroup_name_index_length (struct PointerRNA * ptr, int index)
void rna_object_vgroup_name_index_set (struct PointerRNA * ptr, const char * value, short * index)
void rna_object_vgroup_name_set (struct PointerRNA * ptr, const char * value, char * result, int maxlen)
int rna_parameter_size (struct PropertyRNA * parm)
Definition at line 2697 of file rna_define.c.
References PropertyRNA::flag, len(), StringPropertyRNA::maxlength, PROP_BOOLEAN, PROP_COLLECTION, PROP_DYNAMIC, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_POINTER, PROP_RNAPTR, PROP_STRING, PROP_THICK_WRAP, PropertyRNA::totarraylength, and PropertyRNA::type.
Referenced by RNA_parameter_list_create(), and rna_parameter_size_alloc().
int rna_parameter_size_alloc (struct PropertyRNA * parm)
Definition at line 2756 of file rna_define.c.
References PropertyRNA::flag, NULL, PROP_DYNAMIC, rna_parameter_size(), and size().
Referenced by rna_def_function_funcs(), RNA_parameter_list_begin(), RNA_parameter_list_create(), RNA_parameter_list_free(), and RNA_parameter_list_next().
PointerRNA rna_pointer_inherit_refine (struct PointerRNA * ptr, struct StructRNA * type, void * data)
Definition at line 180 of file rna_access.c.
References data, PointerRNA::data, PointerRNA_NULL, StructRNA::refine, rna_pointer_inherit_id(), and PointerRNA::type.
Referenced by rna_array_lookup_int(), rna_listbase_lookup_int(), RNA_pointer_recast(), and RNA_property_pointer_get().
struct IDProperty* rna_PropertyGroup_idprops (struct PointerRNA * ptr, int create) [read]
struct StructRNA* rna_PropertyGroup_refine (struct PointerRNA * ptr) [read]
struct StructRNA* rna_PropertyGroup_register (struct Main * bmain, struct ReportList * reports, void * data, const char * identifier, StructValidateFunc validate, StructCallbackFunc call, StructFreeFunc free) [read]
void rna_PropertyGroup_unregister (struct Main * bmain, struct StructRNA * type)
char* rna_TextureSlot_path (struct PointerRNA * ptr)
void rna_TextureSlot_update (struct Main * bmain, struct Scene * scene, struct PointerRNA * ptr)
Variable Documentation
BlenderRNA BLENDER_RNA
Referenced by RNA_blender_rna_pointer_create(), RNA_exit(), RNA_init(), RNA_struct_find(), WM_operatortype_append(), WM_operatortype_append_macro(), WM_operatortype_append_macro_ptr(), WM_operatortype_append_ptr(), and WM_operatortype_remove().
BlenderDefRNA DefRNA
Definition at line 49 of file rna_define.c.
Referenced by rna_alloc_function_name(), rna_auto_types(), rna_def_property_begin_func(), rna_def_property_funcs(), rna_def_property_get_func(), rna_def_property_length_func(), rna_def_property_set_func(), rna_find_dna_type(), rna_find_struct(), rna_find_type(), rna_generate(), rna_generate_header(), rna_generate_header_cpp(), rna_generate_property(), rna_generate_struct(), rna_preprocess(), and rna_sort().
StructRNA RNA_PropertyGroup
Referenced by pointer_type_from_py(), and RNA_path_from_ID_to_struct().
StructRNA RNA_PropertyGroupItem
CollectionPropertyRNA rna_PropertyGroupItem_collection
FloatPropertyRNA rna_PropertyGroupItem_double
FloatPropertyRNA rna_PropertyGroupItem_double_array
FloatPropertyRNA rna_PropertyGroupItem_float
FloatPropertyRNA rna_PropertyGroupItem_float_array
PointerPropertyRNA rna_PropertyGroupItem_group
CollectionPropertyRNA rna_PropertyGroupItem_idp_array
IntPropertyRNA rna_PropertyGroupItem_int
IntPropertyRNA rna_PropertyGroupItem_int_array
StringPropertyRNA rna_PropertyGroupItem_string