Blender: node_composite_composite.c File Reference
node_composite_composite.c File Reference
cmpnodes
#include "node_composite_util.h"
Functions
static void node_composit_exec_composite (void *data, bNode *node, bNodeStack **in, bNodeStack **UNUSED(out))
void register_node_type_cmp_composite (bNodeTreeType *ttype)
Variables
static bNodeSocketTemplate cmp_node_composite_in []
Detailed Description
Definition in file node_composite_composite.c.
Function Documentation
static void node_composit_exec_composite (void * data, bNode * node, bNodeStack ** in, bNodeStack ** UNUSEDout) [static]
Definition at line 46 of file node_composite_composite.c.
References alloc_compbuf(), BKE_image_signal(), BKE_image_verify_viewer(), CB_RGBA, CB_VAL, composit1_pixel_processor(), composit2_pixel_processor(), do_copy_a_rgba(), do_copy_rgba(), do_copy_value(), bNode::flag, free_compbuf(), generate_preview(), Scene::id, bNode::id, if(), IMA_SIGNAL_FREE, IMA_TYPE_R_RESULT, CompBuf::malloc, MEM_freeN(), ID::name, NODE_DO_OUTPUT, NULL, R_DOCOMP, RE_AcquireResultWrite(), RE_GetRender(), RE_ReleaseResult(), CompBuf::rect, RenderResult::rectf, RenderResult::rectx, RenderResult::recty, and RenderResult::rectz.
Referenced by register_node_type_cmp_composite().
void register_node_type_cmp_composite (bNodeTreeType * ttype)
Definition at line 100 of file node_composite_composite.c.
References CMP_NODE_COMPOSITE, NODE_CLASS_OUTPUT, node_composit_exec_composite(), NODE_PREVIEW, node_type_base(), node_type_exec(), node_type_internal_connect(), node_type_size(), node_type_socket_templates(), nodeRegisterType(), and NULL.
Referenced by registerCompositNodes().
Variable Documentation
bNodeSocketTemplate cmp_node_composite_in[] [static]
Initial value:
 {
    {   SOCK_RGBA, 1, "Image",      0.0f, 0.0f, 0.0f, 1.0f},
    {   SOCK_FLOAT, 1, "Alpha",     1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   SOCK_FLOAT, 1, "Z",         1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, PROP_FACTOR},
    {   -1, 0, ""   }
}
Definition at line 38 of file node_composite_composite.c.