Blender: btQuaternion.h File Reference
btQuaternion.h File Reference
#include "btVector3.h"
#include "btQuadWord.h"
Classes
class btQuaternion
The btQuaternion implements quaternion to perform linear algebra rotations in combination with btMatrix3x3, btVector3 and btTransform.
Functions
SIMD_FORCE_INLINE btQuaternion operator- (const btQuaternion &q)
Return the negative of a quaternion.
SIMD_FORCE_INLINE btQuaternion operator* (const btQuaternion &q1, const btQuaternion &q2)
Return the product of two quaternions.
SIMD_FORCE_INLINE btQuaternion operator* (const btQuaternion &q, const btVector3 &w)
SIMD_FORCE_INLINE btQuaternion operator* (const btVector3 &w, const btQuaternion &q)
SIMD_FORCE_INLINE btScalar dot (const btQuaternion &q1, const btQuaternion &q2)
Calculate the dot product between two quaternions.
SIMD_FORCE_INLINE btScalar length (const btQuaternion &q)
Return the length of a quaternion.
SIMD_FORCE_INLINE btScalar angle (const btQuaternion &q1, const btQuaternion &q2)
Return the angle between two quaternions.
SIMD_FORCE_INLINE btQuaternion inverse (const btQuaternion &q)
Return the inverse of a quaternion.
SIMD_FORCE_INLINE btQuaternion slerp (const btQuaternion &q1, const btQuaternion &q2, const btScalar &t)
Return the result of spherical linear interpolation betwen two quaternions.
SIMD_FORCE_INLINE btVector3 quatRotate (const btQuaternion &rotation, const btVector3 &v)
SIMD_FORCE_INLINE btQuaternion shortestArcQuat (const btVector3 &v0, const btVector3 &v1)
SIMD_FORCE_INLINE btQuaternion shortestArcQuatNormalize2 (btVector3 &v0, btVector3 &v1)
Function Documentation
SIMD_FORCE_INLINE btScalar angle (const btQuaternion & q1, const btQuaternion & q2)
Return the angle between two quaternions.
Definition at line 371 of file btQuaternion.h.
References btQuaternion::angle().
Referenced by add_render_lamp(), applyModifier(), applyTranslation(), ATTRIBUTE_ALIGNED16(), axisProjection(), basic_rotate(), BLF_rotation(), BLF_rotation_default(), BM_face_create_ngon_vcloud(), bm_vert_edge_face_angle(), BME_bevel_get_angle_vert(), bmo_dissolve_limit_exec(), bmo_esubd_exec(), bmo_similaredges_exec(), bmo_similarfaces_exec(), boid_body(), btAtan2Fast(), btGetAngle(), C_Matrix_Rotation(), cache_key_incremental_rotation(), calc_corner_co(), calc_radial_symmetry_feather(), calc_solidify_normals(), btTransformUtil::calculateVelocity(), btTransformUtil::calculateVelocityQuaternion(), check_zone(), TransformReader::dae_rotate_to_mat4(), dblur(), do_chroma_key(), do_guides(), do_rotate_brush(), draw_rotation_guide(), draw_spot_cone(), drawArc(), btIDebugDraw::drawArc(), drawHelpline(), dvar_eval_rotDiff(), edbm_dupli_extrude_cursor_invoke(), edbm_select_linked_flat_faces_exec(), edbm_select_sharp_edges_exec(), Euler_rotate_axis(), AnimationImporter::evaluate_animation(), extrawindow_spin_cursor(), find_ear(), flyApply_ndof(), gearGL(), KDL::Rotation::GetRotAngle(), glutil_draw_filled_arc(), glutil_draw_lined_arc(), gpu_lamp_from_blender(), Handle_set_cone_angle_inner(), Handle_set_cone_angle_outer(), InputAngle(), load_tex(), make_bevel_list_3D_minimum_twist(), makebevelcurve(), makeshadowbuf(), mat3_to_quat_is_ok(), mul_fac_qt_fl(), ndof_orbit_invoke(), ndof_to_quat(), node_composit_exec_movieclip(), node_composit_exec_stabilize2d(), KDL::operator>>(), p_chart_fill_boundary(), p_edge_boundary_angle(), pivotcon_evaluate(), poly_rotate_plane(), project_from_camera(), project_paint_uvpixel_mask(), py_blf_rotation(), Quaternion_angle_get(), Quaternion_angle_set(), Quaternion_axis_vector_set(), Quaternion_new(), Quaternion_to_axis_angle(), regular_polygon_sample(), Rot(), rotation_between_vecs_to_quat(), RotationBetween(), AUD_SequencerEntry::setConeAngleInner(), AUD_SequencerEntry::setConeAngleOuter(), AUD_ChannelMapperReader::setMonoAngle(), shadeHaloFloat(), sk_detectDeleteGesture(), sk_detectReverseGesture(), sk_detectTrimGesture(), sk_drawEdge(), sk_drawNormal(), spotvolume(), stabilization_auto_scale_factor(), test_manipulator_axis(), btGeneric6DofConstraint::testAngularLimitMotor(), testRadialSymmetry(), tex_strength(), tri_to_quat(), uiStyleFontDrawRotated(), vec_to_quat(), view3d_align_axis_to_vector(), viewrotate_apply(), visualkey_get_value(), and WardIso_Spec().
SIMD_FORCE_INLINE btScalar dot (const btQuaternion & q1, const btQuaternion & q2)
Calculate the dot product between two quaternions.
Definition at line 356 of file btQuaternion.h.
References btQuaternion::dot().
SIMD_FORCE_INLINE btQuaternion inverse (const btQuaternion & q)
Return the inverse of a quaternion.
Definition at line 378 of file btQuaternion.h.
References btQuaternion::inverse().
Referenced by AngularImpulseMatrix(), BKE_tracking_join_tracks(), drawspiral(), ImpulseMatrix(), KX_GameObject::NodeSetGlobalOrientation(), and btConeTwistConstraint::setMotorTarget().
SIMD_FORCE_INLINE btScalar length (const btQuaternion & q)
Return the length of a quaternion.
Definition at line 364 of file btQuaternion.h.
References btQuaternion::length().
SIMD_FORCE_INLINE btQuaternion operator* (const btQuaternion & q1, const btQuaternion & q2)
Return the product of two quaternions.
Definition at line 329 of file btQuaternion.h.
SIMD_FORCE_INLINE btQuaternion operator* (const btVector3 & w, const btQuaternion & q)
Definition at line 346 of file btQuaternion.h.
SIMD_FORCE_INLINE btQuaternion operator* (const btQuaternion & q, const btVector3 & w)
Definition at line 337 of file btQuaternion.h.
SIMD_FORCE_INLINE btQuaternion operator- (const btQuaternion & q)
Return the negative of a quaternion.
Definition at line 320 of file btQuaternion.h.
SIMD_FORCE_INLINE btVector3 quatRotate (const btQuaternion & rotation, const btVector3 & v)
Definition at line 395 of file btQuaternion.h.
References btQuaternion::inverse().
Referenced by ATTRIBUTE_ALIGNED16(), btAdjustInternalEdgeContacts(), btConeTwistConstraint::calcAngleInfo(), btConeTwistConstraint::calcAngleInfo2(), btConeTwistConstraint::GetPointForAngle(), btConnectivityProcessor::processTriangle(), and btConeTwistConstraint::setMotorTargetInConstraintSpace().
SIMD_FORCE_INLINE btQuaternion shortestArcQuat (const btVector3 & v0, const btVector3 & v1)
Definition at line 403 of file btQuaternion.h.
References btPlaneSpace1(), btSqrt(), btQuaternion::dot(), and SIMD_EPSILON.
Referenced by ATTRIBUTE_ALIGNED16(), btConeTwistConstraint::calcAngleInfo(), btConeTwistConstraint::calcAngleInfo2(), btConeTwistConstraint::setMotorTargetInConstraintSpace(), and shortestArcQuatNormalize2().
SIMD_FORCE_INLINE btQuaternion shortestArcQuatNormalize2 (btVector3 & v0, btVector3 & v1)
Definition at line 422 of file btQuaternion.h.
References btQuaternion::normalize(), and shortestArcQuat().
SIMD_FORCE_INLINE btQuaternion slerp (const btQuaternion & q1, const btQuaternion & q2, const btScalar & t)
Return the result of spherical linear interpolation betwen two quaternions.
Parameters:
q1 The first quaternion
q2 The second quaternion
t The ration between q1 and q2. t = 0 return q1, t=1 returns q2 Slerp assumes constant velocity between positions.
Definition at line 389 of file btQuaternion.h.
References btQuaternion::slerp().