Blender: MOD_weightvg_util.h File Reference
MOD_weightvg_util.h File Reference
modifiers
#include "MOD_modifiertypes.h"
Defines
#define MOD_WVG_ZEROFLOOR 1.0e-32f
Functions
void weightvg_do_map (int num, float *new_w, short mode, struct CurveMapping *cmap)
void weightvg_do_mask (int num, const int *indices, float *org_w, const float *new_w, Object *ob, DerivedMesh *dm, float fact, const char defgrp_name[MAX_VGROUP_NAME], struct Scene *scene, Tex *texture, int tex_use_channel, int tex_mapping, Object *tex_map_object, const char *tex_uvlayer_name)
void weightvg_update_vg (MDeformVert *dvert, int defgrp_idx, MDeformWeight **dws, int num, const int *indices, const float *weights, int do_add, float add_thresh, int do_rem, float rem_thresh)
Detailed Description
Definition in file MOD_weightvg_util.h.
Define Documentation
#define MOD_WVG_ZEROFLOOR 1.0e-32f
Definition at line 60 of file MOD_weightvg_util.h.
Referenced by mix_weight().
Function Documentation
void weightvg_do_map (int num, float * new_w, short mode, struct CurveMapping * cmap)
Definition at line 62 of file MOD_weightvg_util.c.
References BLI_frand(), BLI_rand(), BLI_srand(), curvemapping_evaluateF(), ELEM7, i, MOD_WVG_MAPPING_CURVE, MOD_WVG_MAPPING_RANDOM, MOD_WVG_MAPPING_ROOT, MOD_WVG_MAPPING_SHARP, MOD_WVG_MAPPING_SMOOTH, MOD_WVG_MAPPING_SPHERE, MOD_WVG_MAPPING_STEP, NULL, and sqrt().
Referenced by applyModifier(), and do_map().
void weightvg_do_mask (int num, const int * indices, float * org_w, const float * new_w, Object * ob, DerivedMesh * dm, float fact, const char defgrp_name[MAX_VGROUP_NAME], struct Scene * scene, Tex * texture, int tex_use_channel, int tex_mapping, Object * tex_map_object, const char * tex_uvlayer_name)
Definition at line 115 of file MOD_weightvg_util.c.
References BLI_strncpy(), CD_MDEFORMVERT, defgroup_name_index(), defvert_find_weight(), get_texture_coords(), get_texture_value(), DerivedMesh::getVertCos, DerivedMesh::getVertDataArray, i, MappingInfoModifierData::map_object, MEM_callocN(), MEM_freeN(), MEM_mallocN(), MOD_WVG_MASK_TEX_USE_ALPHA, MOD_WVG_MASK_TEX_USE_BLUE, MOD_WVG_MASK_TEX_USE_GREEN, MOD_WVG_MASK_TEX_USE_HUE, MOD_WVG_MASK_TEX_USE_INT, MOD_WVG_MASK_TEX_USE_RED, MOD_WVG_MASK_TEX_USE_SAT, MOD_WVG_MASK_TEX_USE_VAL, modifier_init_texture(), TexResult::nor, NULL, rgb_to_hsv(), TexResult::ta, TexResult::tb, MappingInfoModifierData::texmapping, MappingInfoModifierData::texture, TexResult::tg, TexResult::tin, TexResult::tr, and MappingInfoModifierData::uvlayer_name.
Referenced by applyModifier().
void weightvg_update_vg (MDeformVert * dvert, int defgrp_idx, MDeformWeight ** dws, int num, const int * indices, const float * weights, int do_add, float add_thresh, int do_rem, float rem_thresh)
Definition at line 237 of file MOD_weightvg_util.c.
References CLAMP(), defvert_add_index_notest(), defvert_find_index(), defvert_remove_group(), i, NULL, and MDeformWeight::weight.
Referenced by applyModifier().