Blender: kernel_accumulate.h File Reference
kernel_accumulate.h File Reference
Functions
CCL_NAMESPACE_BEGIN
__device_inline void bsdf_eval_init (BsdfEval *eval, ClosureType type, float3 value, int use_light_pass)
__device_inline void bsdf_eval_accum (BsdfEval *eval, ClosureType type, float3 value)
__device_inline bool bsdf_eval_is_zero (BsdfEval *eval)
__device_inline void bsdf_eval_mul (BsdfEval *eval, float3 value)
__device_inline void path_radiance_init (PathRadiance *L, int use_light_pass)
__device_inline void path_radiance_bsdf_bounce (PathRadiance *L, float3 *throughput, BsdfEval *bsdf_eval, float bsdf_pdf, int bounce, int bsdf_label)
__device_inline void path_radiance_accum_emission (PathRadiance *L, float3 throughput, float3 value, int bounce)
__device_inline void path_radiance_accum_ao (PathRadiance *L, float3 throughput, float3 bsdf, float3 ao, int bounce)
__device_inline void path_radiance_accum_light (PathRadiance *L, float3 throughput, BsdfEval *bsdf_eval, float3 shadow, int bounce, bool is_lamp)
__device_inline void path_radiance_accum_background (PathRadiance *L, float3 throughput, float3 value, int bounce)
__device_inline float3 path_radiance_sum (PathRadiance *L)
__device_inline void path_radiance_clamp (PathRadiance *L, float3 *L_sum, float clamp)
Function Documentation
__device_inline void bsdf_eval_accum (BsdfEval * eval, ClosureType type, float3 value)
Definition at line 53 of file kernel_accumulate.h.
References CLOSURE_IS_BSDF_DIFFUSE, CLOSURE_IS_BSDF_GLOSSY, BsdfEval::diffuse, BsdfEval::glossy, BsdfEval::transmission, and BsdfEval::use_light_pass.
CCL_NAMESPACE_BEGIN __device_inline void bsdf_eval_init (BsdfEval * eval, ClosureType type, float3 value, int use_light_pass)
Definition at line 26 of file kernel_accumulate.h.
References CLOSURE_BSDF_TRANSPARENT_ID, CLOSURE_IS_BSDF_DIFFUSE, CLOSURE_IS_BSDF_GLOSSY, BsdfEval::diffuse, BsdfEval::glossy, make_float3(), BsdfEval::transmission, BsdfEval::transparent, and BsdfEval::use_light_pass.
Referenced by shader_bsdf_eval(), and shader_bsdf_sample().
__device_inline bool bsdf_eval_is_zero (BsdfEval * eval)
Definition at line 73 of file kernel_accumulate.h.
References BsdfEval::diffuse, BsdfEval::glossy, is_zero(), BsdfEval::transmission, BsdfEval::transparent, and BsdfEval::use_light_pass.
Referenced by direct_emission(), and kernel_path_integrate().
__device_inline void bsdf_eval_mul (BsdfEval * eval, float3 value)
Definition at line 89 of file kernel_accumulate.h.
References BsdfEval::diffuse, BsdfEval::glossy, BsdfEval::transmission, and BsdfEval::use_light_pass.
Referenced by direct_emission().
__device_inline void path_radiance_accum_ao (PathRadiance * L, float3 throughput, float3 bsdf, float3 ao, int bounce)
Definition at line 198 of file kernel_accumulate.h.
References PathRadiance::ao, PathRadiance::direct_diffuse, PathRadiance::emission, PathRadiance::indirect, and PathRadiance::use_light_pass.
Referenced by kernel_path_integrate().
__device_inline void path_radiance_accum_background (PathRadiance * L, float3 throughput, float3 value, int bounce)
Definition at line 251 of file kernel_accumulate.h.
References PathRadiance::background, PathRadiance::direct_emission, PathRadiance::emission, PathRadiance::indirect, and PathRadiance::use_light_pass.
Referenced by kernel_path_integrate().
__device_inline void path_radiance_accum_emission (PathRadiance * L, float3 throughput, float3 value, int bounce)
Definition at line 180 of file kernel_accumulate.h.
References PathRadiance::direct_emission, PathRadiance::emission, PathRadiance::indirect, and PathRadiance::use_light_pass.
Referenced by kernel_path_integrate().
__device_inline void path_radiance_accum_light (PathRadiance * L, float3 throughput, BsdfEval * bsdf_eval, float3 shadow, int bounce, bool is_lamp)
Definition at line 219 of file kernel_accumulate.h.
References average(), BsdfEval::diffuse, PathRadiance::direct_diffuse, PathRadiance::direct_glossy, PathRadiance::direct_transmission, PathRadiance::emission, BsdfEval::glossy, PathRadiance::indirect, PathRadiance::shadow, sum(), BsdfEval::transmission, PathRadiance::use_light_pass, float4::w, float3::x, float4::x, float3::y, float4::y, float3::z, and float4::z.
Referenced by kernel_path_integrate().
__device_inline void path_radiance_bsdf_bounce (PathRadiance * L, float3 * throughput, BsdfEval * bsdf_eval, float bsdf_pdf, int bounce, int bsdf_label)
Definition at line 148 of file kernel_accumulate.h.
References BsdfEval::diffuse, PathRadiance::direct_throughput, BsdfEval::glossy, PathRadiance::indirect_diffuse, PathRadiance::indirect_glossy, PathRadiance::indirect_transmission, LABEL_TRANSPARENT, sum(), BsdfEval::transmission, BsdfEval::transparent, and PathRadiance::use_light_pass.
Referenced by kernel_path_integrate().
__device_inline void path_radiance_clamp (PathRadiance * L, float3 * L_sum, float clamp)
Definition at line 297 of file kernel_accumulate.h.
References PathRadiance::direct_diffuse, PathRadiance::direct_glossy, PathRadiance::direct_transmission, PathRadiance::emission, fabsf, PathRadiance::indirect_diffuse, PathRadiance::indirect_glossy, PathRadiance::indirect_transmission, isfinite(), make_float3(), sum(), and PathRadiance::use_light_pass.
Referenced by kernel_path_integrate().
__device_inline void path_radiance_init (PathRadiance * L, int use_light_pass)
Definition at line 113 of file kernel_accumulate.h.
References PathRadiance::ao, PathRadiance::background, PathRadiance::color_diffuse, PathRadiance::color_glossy, PathRadiance::color_transmission, PathRadiance::direct_diffuse, PathRadiance::direct_emission, PathRadiance::direct_glossy, PathRadiance::direct_throughput, PathRadiance::direct_transmission, PathRadiance::emission, PathRadiance::indirect, PathRadiance::indirect_diffuse, PathRadiance::indirect_glossy, PathRadiance::indirect_transmission, make_float3(), make_float4(), PathRadiance::shadow, and PathRadiance::use_light_pass.
Referenced by kernel_path_integrate().
__device_inline float3 path_radiance_sum (PathRadiance * L)
Definition at line 269 of file kernel_accumulate.h.
References PathRadiance::background, PathRadiance::direct_diffuse, PathRadiance::direct_emission, PathRadiance::direct_glossy, PathRadiance::direct_throughput, PathRadiance::direct_transmission, PathRadiance::emission, PathRadiance::indirect, PathRadiance::indirect_diffuse, PathRadiance::indirect_glossy, PathRadiance::indirect_transmission, L, safe_divide_color(), and PathRadiance::use_light_pass.
Referenced by kernel_path_integrate().