Blender: nla_private.h File Reference
nla_private.h File Reference
blenkernel
Classes
struct NlaEvalStrip
struct NlaEvalChannel
Typedefs
typedef struct NlaEvalStrip NlaEvalStrip
typedef struct NlaEvalChannel NlaEvalChannel
Enumerations
enum {
NES_TIME_BEFORE = -1, NES_TIME_WITHIN, NES_TIME_AFTER, NES_TIME_TRANSITION_START,
NES_TIME_TRANSITION_END
}
Functions
float nlastrip_get_frame (NlaStrip *strip, float cframe, short mode)
NlaEvalStrip * nlastrips_ctime_get_strip (ListBase *list, ListBase *strips, short index, float ctime)
void nlastrip_evaluate (PointerRNA *ptr, ListBase *channels, ListBase *modifiers, NlaEvalStrip *nes)
void nladata_flush_channels (ListBase *channels)
Variables
enum { ... } eNlaEvalStrip_StripMode
Detailed Description
Definition in file nla_private.h.
Typedef Documentation
typedef struct NlaEvalChannel NlaEvalChannel
typedef struct NlaEvalStrip NlaEvalStrip
Enumeration Type Documentation
anonymous enum
Enumerator:
NES_TIME_BEFORE
NES_TIME_WITHIN
NES_TIME_AFTER
NES_TIME_TRANSITION_START
NES_TIME_TRANSITION_END
Definition at line 52 of file nla_private.h.
Function Documentation
void nladata_flush_channels (ListBase * channels)
Definition at line 1955 of file anim_sys.c.
References ANIMSYS_FLOAT_AS_BOOL, ListBase::first, NlaEvalChannel::index, NlaEvalChannel::next, NULL, NlaEvalChannel::prop, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, NlaEvalChannel::ptr, RNA_property_array_length(), RNA_property_boolean_set(), RNA_property_boolean_set_index(), RNA_property_enum_set(), RNA_property_float_set(), RNA_property_float_set_index(), RNA_property_int_set(), RNA_property_int_set_index(), RNA_property_type(), and NlaEvalChannel::value.
Referenced by animsys_calculate_nla().
void nlastrip_evaluate (PointerRNA * ptr, ListBase * channels, ListBase * modifiers, NlaEvalStrip * nes)
Definition at line 1922 of file anim_sys.c.
References NlaStrip::flag, nlastrip_evaluate_actionclip(), nlastrip_evaluate_meta(), nlastrip_evaluate_transition(), NLASTRIP_FLAG_EDIT_TOUCHED, NLASTRIP_TYPE_CLIP, NLASTRIP_TYPE_META, NLASTRIP_TYPE_TRANSITION, NlaEvalStrip::strip, and NlaStrip::type.
Referenced by animsys_evaluate_nla(), nlastrip_evaluate_meta(), and nlastrip_evaluate_transition().
float nlastrip_get_frame (NlaStrip * strip, float cframe, short mode)
Definition at line 489 of file nla.c.
References nlastrip_get_frame_actionclip(), nlastrip_get_frame_transition(), NLASTRIP_TYPE_CLIP, NLASTRIP_TYPE_META, NLASTRIP_TYPE_TRANSITION, and NlaStrip::type.
Referenced by bezt_apply_nlamapping(), BKE_nla_tweakedit_remap(), nlaedit_split_strip_actclip(), and nlastrip_evaluate_controls().
NlaEvalStrip* nlastrips_ctime_get_strip (ListBase * list, ListBase * strips, short index, float ctime)
Definition at line 1432 of file anim_sys.c.
References NlaStrip::act, BLI_addtail(), ELEM, NlaStrip::end, NlaStrip::extendmode, ListBase::first, NlaStrip::flag, IN_RANGE_INCL, NlaStrip::influence, ListBase::last, MEM_callocN(), NES_TIME_AFTER, NES_TIME_BEFORE, NES_TIME_WITHIN, NlaStrip::next, nlastrip_evaluate_controls(), NLASTRIP_EXTEND_HOLD, NLASTRIP_EXTEND_NOTHING, NLASTRIP_FLAG_MUTED, NLASTRIP_TYPE_CLIP, NLASTRIP_TYPE_TRANSITION, NULL, NlaStrip::prev, NlaStrip::start, NlaEvalStrip::strip, NlaEvalStrip::strip_mode, NlaStrip::strip_time, NlaEvalStrip::strip_time, NlaEvalStrip::track_index, and NlaStrip::type.
Referenced by animsys_evaluate_nla(), and nlastrip_evaluate_meta().
Variable Documentation
enum { ... } eNlaEvalStrip_StripMode