Blender: ImageBuff Class Reference
ImageBuff Class Reference
class for image buffer
#include <ImageBuff.h>
Public Member Functions
ImageBuff (void)
constructor
virtual ~ImageBuff (void)
destructor
void load (unsigned char *img, short width, short height)
load image from buffer
void clear (short width, short height, unsigned char color)
clear image with color set on RGB channels and 0xFF on alpha channel
void plot (unsigned char *img, short width, short height, short x, short y, short mode)
plot image from extern RGBA buffer to image at position x,y using one of IMB_BlendMode
void plot (ImageBuff *img, short x, short y, short mode)
plot image from other ImageBuf to image at position x,y using one of IMB_BlendMode
virtual void refresh (void)
refresh image - do nothing
Detailed Description
class for image buffer
Definition at line 38 of file ImageBuff.h.
Constructor & Destructor Documentation
ImageBuff::ImageBuff (void) [inline]
constructor
Definition at line 44 of file ImageBuff.h.
ImageBuff::~ImageBuff (void) [virtual]
destructor
Definition at line 85 of file ImageBuff.cpp.
References IMB_freeImBuf().
Member Function Documentation
void ImageBuff::clear (short width, short height, unsigned char color)
clear image with color set on RGB channels and 0xFF on alpha channel
Definition at line 116 of file ImageBuff.cpp.
References IMB_freeImBuf(), ImageBase::init(), ImageBase::m_avail, ImageBase::m_image, ImageBase::m_size, NULL, p, and size().
Referenced by ImageBuff_init().
void ImageBuff::load (unsigned char * img, short width, short height)
load image from buffer
Definition at line 93 of file ImageBuff.cpp.
References ImageBase::convImage(), IMB_freeImBuf(), ImageBase::init(), ImageBase::m_avail, PyFilter::m_filter, ImageBase::m_pyfilter, and NULL.
Referenced by load().
void ImageBuff::plot (ImageBuff * img, short x, short y, short mode)
plot image from other ImageBuf to image at position x,y using one of IMB_BlendMode
Definition at line 169 of file ImageBuff.cpp.
References IMB_allocImBuf(), IMB_rectblend(), ImageBase::m_image, ImageBase::m_size, NULL, ImBuf::rect, ImBuf::x, and ImBuf::y.
void ImageBuff::plot (unsigned char * img, short width, short height, short x, short y, short mode)
plot image from extern RGBA buffer to image at position x,y using one of IMB_BlendMode
Definition at line 145 of file ImageBuff.cpp.
References IMB_allocImBuf(), IMB_freeImBuf(), IMB_rectblend(), ImageBase::m_image, ImageBase::m_size, NULL, and ImBuf::rect.
Referenced by plot().
virtual void ImageBuff::refresh (void) [inline, virtual]
refresh image - do nothing
Reimplemented from ImageBase.
Definition at line 60 of file ImageBuff.h.
The documentation for this class was generated from the following files:
ImageBuff.h
ImageBuff.cpp