Blender: MOD_edgesplit.c File Reference
MOD_edgesplit.c File Reference
modifiers
#include "BLI_utildefines.h"
#include "BLI_math.h"
#include "MEM_guardedalloc.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_modifier.h"
#include "BKE_tessmesh.h"
#include "BKE_mesh.h"
#include "DNA_object_types.h"
Defines
#define EDGE_MARK 1
Functions
static DerivedMesh * doEdgeSplit (DerivedMesh *dm, EdgeSplitModifierData *emd, Object *UNUSED(ob))
static void initData (ModifierData *md)
static void copyData (ModifierData *md, ModifierData *target)
static DerivedMesh * edgesplitModifier_do (EdgeSplitModifierData *emd, Object *ob, DerivedMesh *dm)
static DerivedMesh * applyModifier (ModifierData *md, Object *ob, DerivedMesh *derivedData, int UNUSED(useRenderParams), int UNUSED(isFinalCalc))
static DerivedMesh * applyModifierEM (ModifierData *md, Object *ob, struct BMEditMesh *UNUSED(editData), DerivedMesh *derivedData)
Variables
ModifierTypeInfo modifierType_EdgeSplit
Detailed Description
Definition in file MOD_edgesplit.c.
Define Documentation
#define EDGE_MARK 1
Definition at line 58 of file MOD_edgesplit.c.
Referenced by doEdgeSplit().
Function Documentation
static DerivedMesh* applyModifier (ModifierData * md, Object * ob, DerivedMesh * derivedData, int UNUSEDuseRenderParams, int UNUSEDisFinalCalc) [static]
Definition at line 143 of file MOD_edgesplit.c.
References CDDM_calc_normals(), and edgesplitModifier_do().
Referenced by applyModifierEM().
static DerivedMesh* applyModifierEM (ModifierData * md, Object * ob, struct BMEditMesh * UNUSEDeditData, DerivedMesh * derivedData) [static]
Definition at line 158 of file MOD_edgesplit.c.
References applyModifier().
static void copyData (ModifierData * md, ModifierData * target) [static]
Definition at line 125 of file MOD_edgesplit.c.
References EdgeSplitModifierData::flags, and EdgeSplitModifierData::split_angle.
static DerivedMesh* doEdgeSplit (DerivedMesh * dm, EdgeSplitModifierData * emd, Object * UNUSEDob) [static]
Definition at line 60 of file MOD_edgesplit.c.
References BLI_assert, BMEditMesh::bm, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_SMOOTH, BM_ITER_MESH, BM_mesh_normals_update(), BMEdit_Free(), BMO_elem_flag_enable, BMO_op_callf(), BMO_pop(), BMO_push(), CDDM_from_BMEditMesh(), cos(), DM_to_editbmesh(), dot_v3v3(), EDGE_MARK, BMLoop::f, FALSE, EdgeSplitModifierData::flags, BMEdge::l, BMEditMesh::looptris, M_PI, MEM_freeN(), MOD_EDGESPLIT_FROMANGLE, MOD_EDGESPLIT_FROMFLAG, BMLoop::next, BMFace::no, NULL, BMLoop::radial_next, EdgeSplitModifierData::split_angle, and TRUE.
Referenced by edgesplitModifier_do().
static DerivedMesh* edgesplitModifier_do (EdgeSplitModifierData * emd, Object * ob, DerivedMesh * dm) [static]
Definition at line 134 of file MOD_edgesplit.c.
References doEdgeSplit(), EdgeSplitModifierData::flags, MOD_EDGESPLIT_FROMANGLE, and MOD_EDGESPLIT_FROMFLAG.
Referenced by applyModifier().
static void initData (ModifierData * md) [static]
Definition at line 116 of file MOD_edgesplit.c.
References EdgeSplitModifierData::flags, MOD_EDGESPLIT_FROMANGLE, MOD_EDGESPLIT_FROMFLAG, and EdgeSplitModifierData::split_angle.
Variable Documentation
ModifierTypeInfo modifierType_EdgeSplit
Initial value:
 {
                  "EdgeSplit",
            "EdgeSplitModifierData",
            sizeof(EdgeSplitModifierData),
                  eModifierTypeType_Constructive,
                 eModifierTypeFlag_AcceptsMesh
                            | eModifierTypeFlag_AcceptsCVs
                            | eModifierTypeFlag_SupportsMapping
                            | eModifierTypeFlag_SupportsEditmode
                            | eModifierTypeFlag_EnableInEditmode,
              copyData,
           NULL,
        NULL,
         NULL,
      NULL,
         applyModifier,
       applyModifierEM,
              initData,
      NULL,
              NULL,
            NULL,
        NULL,
         NULL,
        NULL,
     NULL,
         NULL,
        NULL,
}
Definition at line 166 of file MOD_edgesplit.c.