Blender: SCA_ILogicBrick Class Reference
SCA_ILogicBrick Class Reference
#include <SCA_ILogicBrick.h>
Public Member Functions
SCA_ILogicBrick (SCA_IObject *gameobj)
virtual ~SCA_ILogicBrick ()
void SetExecutePriority (int execute_Priority)
void SetUeberExecutePriority (int execute_Priority)
SCA_IObject * GetParent ()
virtual void ReParent (SCA_IObject *parent)
virtual void Relink (CTR_Map< CTR_HashedPtr, void * > *obj_map)
virtual void Delete ()
virtual CValue * Calc (VALUE_OPERATOR op, CValue *val)
virtual CValue * CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue *val)
virtual const STR_String & GetText ()
virtual double GetNumber ()
virtual STR_String & GetName ()
virtual void SetName (const char *)
bool IsActive ()
void SetActive (bool active)
void InsertActiveQList (SG_QList &head)
void InsertSelfActiveQList (SG_QList &head, SG_QList **current)
virtual bool LessComparedTo (SCA_ILogicBrick *other)
virtual void Replace_IScene (SCA_IScene *val)
virtual void Replace_NetworkScene (NG_NetworkScene *val)
Static Public Attributes
static class SCA_LogicManager * m_sCurrentLogicManager = NULL
Protected Member Functions
void RegisterEvent (CValue *eventval)
void RemoveEvent ()
CValue * GetEvent ()
Protected Attributes
SCA_IObject * m_gameobj
int m_Execute_Priority
int m_Execute_Ueber_Priority
bool m_bActive
CValue * m_eventval
STR_String m_text
STR_String m_name
Detailed Description
Definition at line 44 of file SCA_ILogicBrick.h.
Constructor & Destructor Documentation
SCA_ILogicBrick::SCA_ILogicBrick (SCA_IObject * gameobj)
Definition at line 40 of file SCA_ILogicBrick.cpp.
References m_text.
SCA_ILogicBrick::~SCA_ILogicBrick () [virtual]
Definition at line 54 of file SCA_ILogicBrick.cpp.
References RemoveEvent().
Member Function Documentation
CValue * SCA_ILogicBrick::Calc (VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 85 of file SCA_ILogicBrick.cpp.
References CValue::Calc(), and CValue::Release().
CValue * SCA_ILogicBrick::CalcFinal (VALUE_DATA_TYPE dtype, VALUE_OPERATOR op, CValue * val) [virtual]
Implements CValue.
Definition at line 96 of file SCA_ILogicBrick.cpp.
References CValue::CalcFinal(), and CValue::Release().
virtual void SCA_ILogicBrick::Delete () [inline, virtual]
Reimplemented in SCA_ExpressionController, and SCA_PropertySensor.
Definition at line 72 of file SCA_ILogicBrick.h.
References CValue::Release().
CValue * SCA_ILogicBrick::GetEvent () [protected]
Definition at line 166 of file SCA_ILogicBrick.cpp.
References CValue::AddRef(), m_eventval, and NULL.
STR_String & SCA_ILogicBrick::GetName () [virtual]
Implements CValue.
Definition at line 127 of file SCA_ILogicBrick.cpp.
References m_name.
Referenced by KX_RaySensor::Evaluate(), SCA_ExpressionController::FindIdentifier(), KX_ConstraintActuator::KX_ConstraintActuator(), SCA_IController::UnlinkActuator(), SCA_ISensor::UnlinkController(), SCA_IActuator::UnlinkController(), SCA_IController::UnlinkSensor(), KX_ConstraintActuator::Update(), KX_NetworkMessageActuator::Update(), and SCA_RandomActuator::Update().
double SCA_ILogicBrick::GetNumber () [virtual]
Implements CValue.
Reimplemented in SCA_ISensor.
Definition at line 120 of file SCA_ILogicBrick.cpp.
SCA_IObject* SCA_ILogicBrick::GetParent () [inline]
Definition at line 68 of file SCA_ILogicBrick.h.
References m_gameobj.
Referenced by BL_ShapeActionActuator::BL_ShapeActionActuator(), KX_NearSensor::BroadPhaseFilterCollision(), KX_TouchSensor::BroadPhaseSensorFilterCollision(), SCA_PropertySensor::CheckPropertyCondition(), KX_NetworkMessageSensor::Evaluate(), SCA_KeyboardSensor::Evaluate(), KX_RaySensor::Evaluate(), SCA_ExpressionController::FindIdentifier(), SCA_PropertySensor::FindIdentifier(), KX_SCA_AddObjectActuator::InstantAddObject(), KX_SCA_ReplaceMeshActuator::InstantReplaceMesh(), KX_TouchSensor::NewHandleCollision(), KX_MouseFocusSensor::RayHit(), KX_Scene::ReplicateLogic(), SCA_ActuatorSensor::SCA_ActuatorSensor(), SCA_PropertySensor::SCA_PropertySensor(), BL_ActionActuator::SetLocalTime(), KX_RadarSensor::SynchronizeTransform(), KX_NearSensor::SynchronizeTransform(), SCA_IController::UnlinkActuator(), SCA_ISensor::UnlinkController(), SCA_IActuator::UnlinkController(), SCA_IController::UnlinkSensor(), BL_ArmatureActuator::Update(), KX_SCA_DynamicActuator::Update(), BL_ActionActuator::Update(), KX_GameActuator::Update(), KX_SoundActuator::Update(), KX_ConstraintActuator::Update(), KX_ObjectActuator::Update(), BL_ShapeActionActuator::Update(), KX_SteeringActuator::Update(), KX_CameraActuator::Update(), KX_IpoActuator::Update(), KX_NetworkMessageActuator::Update(), KX_SCA_EndObjectActuator::Update(), SCA_PropertyActuator::Update(), SCA_RandomActuator::Update(), KX_VisibilityActuator::Update(), KX_TrackToActuator::Update(), KX_SCA_ReplaceMeshActuator::Update(), KX_SceneActuator::Update(), KX_ParentActuator::Update(), and KX_StateActuator::Update().
const STR_String & SCA_ILogicBrick::GetText () [virtual]
Implements CValue.
Definition at line 110 of file SCA_ILogicBrick.cpp.
References STR_String::Length(), m_name, and m_text.
void SCA_ILogicBrick::InsertActiveQList (SG_QList & head) [inline]
Definition at line 94 of file SCA_ILogicBrick.h.
References SG_QList::iterator< T >::add_back(), SG_QList::iterator< T >::begin(), SG_QList::iterator< T >::end(), and m_Execute_Priority.
Referenced by SCA_IActuator::Activate(), and SCA_IController::Activate().
void SCA_ILogicBrick::InsertSelfActiveQList (SG_QList & head, SG_QList ** current) [inline]
Definition at line 106 of file SCA_ILogicBrick.h.
References SG_QList::iterator< T >::add_back(), SG_QList::iterator< T >::end(), m_Execute_Priority, m_gameobj, and SG_QList::QAddBack().
Referenced by KX_StateActuator::Activate().
bool SCA_ILogicBrick::IsActive () [inline]
Definition at line 83 of file SCA_ILogicBrick.h.
References m_bActive.
Referenced by SCA_ISensor::ActivateControllers(), SCA_IController::ApplyState(), SCA_ActuatorSensor::Evaluate(), SCA_IController::LinkToActuator(), SCA_IController::LinkToSensor(), SCA_IController::UnlinkActuator(), SCA_IController::UnlinkAllActuators(), SCA_IController::UnlinkAllSensors(), SCA_IController::UnlinkSensor(), and SCA_ActuatorSensor::Update().
bool SCA_ILogicBrick::LessComparedTo (SCA_ILogicBrick * other) [virtual]
Definition at line 139 of file SCA_ILogicBrick.cpp.
References m_Execute_Priority, and m_Execute_Ueber_Priority.
void SCA_ILogicBrick::RegisterEvent (CValue * eventval) [protected]
Definition at line 146 of file SCA_ILogicBrick.cpp.
References CValue::AddRef(), m_eventval, and CValue::Release().
void SCA_ILogicBrick::Relink (CTR_Map< CTR_HashedPtr, void * > * obj_map) [virtual]
Reimplemented in BL_ArmatureActuator, SCA_PropertyActuator, KX_CameraActuator, KX_ObjectActuator, KX_ParentActuator, KX_SCA_AddObjectActuator, KX_SceneActuator, KX_SteeringActuator, and KX_TrackToActuator.
Definition at line 80 of file SCA_ILogicBrick.cpp.
void SCA_ILogicBrick::RemoveEvent () [protected]
Definition at line 155 of file SCA_ILogicBrick.cpp.
References m_eventval, NULL, and CValue::Release().
Referenced by ~SCA_ILogicBrick().
void SCA_ILogicBrick::ReParent (SCA_IObject * parent) [virtual]
Reimplemented in BL_ArmatureActuator, SCA_ActuatorSensor, SCA_ISensor, KX_ArmatureSensor, KX_NearSensor, KX_SteeringActuator, and KX_TouchSensor.
Definition at line 75 of file SCA_ILogicBrick.cpp.
References m_gameobj.
Referenced by SCA_IObject::ReParentLogic().
virtual void SCA_ILogicBrick::Replace_IScene (SCA_IScene * val) [inline, virtual]
Reimplemented in KX_GameActuator, KX_MouseFocusSensor, KX_RaySensor, KX_SCA_AddObjectActuator, and KX_SCA_EndObjectActuator.
Definition at line 136 of file SCA_ILogicBrick.h.
Referenced by MergeScene_LogicBrick().
virtual void SCA_ILogicBrick::Replace_NetworkScene (NG_NetworkScene * val) [inline, virtual]
Reimplemented in KX_NetworkMessageActuator, and KX_NetworkMessageSensor.
Definition at line 137 of file SCA_ILogicBrick.h.
Referenced by MergeScene_LogicBrick().
void SCA_ILogicBrick::SetActive (bool active) [inline]
Definition at line 88 of file SCA_ILogicBrick.h.
References m_bActive.
Referenced by SCA_LogicManager::AddActiveActuator(), SCA_IController::ApplyState(), SCA_LogicManager::RemoveActuator(), SCA_IObject::ReParentLogic(), and SCA_LogicManager::UpdateFrame().
void SCA_ILogicBrick::SetExecutePriority (int execute_Priority)
Definition at line 61 of file SCA_ILogicBrick.cpp.
References m_Execute_Priority.
Referenced by BL_ConvertActuators(), BL_ConvertControllers(), and BL_ConvertSensors().
void SCA_ILogicBrick::SetName (const char * name) [virtual]
Implements CValue.
Definition at line 134 of file SCA_ILogicBrick.cpp.
References m_name.
Referenced by BL_ConvertActuators(), BL_ConvertControllers(), and BL_ConvertSensors().
void SCA_ILogicBrick::SetUeberExecutePriority (int execute_Priority)
Definition at line 68 of file SCA_ILogicBrick.cpp.
References m_Execute_Ueber_Priority.
Referenced by KX_Scene::ReplicateLogic().
Member Data Documentation
bool SCA_ILogicBrick::m_bActive [protected]
Definition at line 52 of file SCA_ILogicBrick.h.
Referenced by IsActive(), and SetActive().
CValue* SCA_ILogicBrick::m_eventval [protected]
Definition at line 53 of file SCA_ILogicBrick.h.
Referenced by GetEvent(), SCA_ISensor::IsPositiveTrigger(), RegisterEvent(), and RemoveEvent().
int SCA_ILogicBrick::m_Execute_Priority [protected]
Definition at line 49 of file SCA_ILogicBrick.h.
Referenced by InsertActiveQList(), InsertSelfActiveQList(), LessComparedTo(), and SetExecutePriority().
int SCA_ILogicBrick::m_Execute_Ueber_Priority [protected]
Definition at line 50 of file SCA_ILogicBrick.h.
Referenced by LessComparedTo(), and SetUeberExecutePriority().
SCA_IObject* SCA_ILogicBrick::m_gameobj [protected]
Definition at line 48 of file SCA_ILogicBrick.h.
Referenced by SCA_IActuator::Activate(), SCA_IController::Activate(), KX_StateActuator::Activate(), SCA_IActuator::Deactivate(), KX_ArmatureSensor::FindConstraint(), GetParent(), InsertSelfActiveQList(), KX_SteeringActuator::ReParent(), ReParent(), SCA_2DFilterActuator::SCA_2DFilterActuator(), SCA_IController::UnlinkActuator(), SCA_ISensor::UnlinkController(), SCA_IActuator::UnlinkController(), SCA_IController::UnlinkSensor(), SCA_2DFilterActuator::Update(), and KX_StateActuator::Update().
STR_String SCA_ILogicBrick::m_name [protected]
Definition at line 55 of file SCA_ILogicBrick.h.
Referenced by SCA_IActuator::DecLink(), SCA_ISensor::DecLink(), GetName(), GetText(), SCA_ISensor::Init(), SetName(), and KX_SoundActuator::Update().
SCA_LogicManager * SCA_ILogicBrick::m_sCurrentLogicManager = NULL [static]
Definition at line 132 of file SCA_ILogicBrick.h.
STR_String SCA_ILogicBrick::m_text [protected]
Definition at line 54 of file SCA_ILogicBrick.h.
Referenced by GetText(), and SCA_ILogicBrick().
The documentation for this class was generated from the following files:
SCA_ILogicBrick.h
SCA_ILogicBrick.cpp