Blender: SCA_ActuatorSensor Class Reference
SCA_ActuatorSensor Class Reference
#include <SCA_ActuatorSensor.h>
Public Member Functions
SCA_ActuatorSensor (class SCA_EventManager *eventmgr, SCA_IObject *gameobj, const STR_String &actname)
virtual ~SCA_ActuatorSensor ()
virtual CValue * GetReplica ()
virtual void Init ()
virtual bool Evaluate ()
virtual bool IsPositiveTrigger ()
virtual void ReParent (SCA_IObject *parent)
void Update ()
Protected Attributes
SCA_IActuator * m_actuator
Detailed Description
Definition at line 41 of file SCA_ActuatorSensor.h.
Constructor & Destructor Documentation
SCA_ActuatorSensor::SCA_ActuatorSensor (class SCA_EventManager * eventmgr, SCA_IObject * gameobj, const STR_String & actname)
Definition at line 43 of file SCA_ActuatorSensor.cpp.
References SCA_IObject::FindActuator(), SCA_ILogicBrick::GetParent(), Init(), and m_actuator.
Referenced by GetReplica().
SCA_ActuatorSensor::~SCA_ActuatorSensor () [virtual]
Definition at line 87 of file SCA_ActuatorSensor.cpp.
Member Function Documentation
bool SCA_ActuatorSensor::Evaluate () [virtual]
Implements SCA_ISensor.
Definition at line 93 of file SCA_ActuatorSensor.cpp.
References SCA_ILogicBrick::IsActive(), m_actuator, SCA_ISensor::m_level, and SCA_ISensor::m_reset.
CValue * SCA_ActuatorSensor::GetReplica (void) [virtual]
Implements SCA_ISensor.
Definition at line 60 of file SCA_ActuatorSensor.cpp.
References Init(), SCA_ISensor::ProcessReplica(), and SCA_ActuatorSensor().
void SCA_ActuatorSensor::Init (void) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 53 of file SCA_ActuatorSensor.cpp.
References SCA_ISensor::m_invert, and SCA_ISensor::m_reset.
Referenced by GetReplica(), and SCA_ActuatorSensor().
bool SCA_ActuatorSensor::IsPositiveTrigger () [virtual]
Reimplemented from SCA_ISensor.
Definition at line 76 of file SCA_ActuatorSensor.cpp.
References SCA_ISensor::m_invert.
void SCA_ActuatorSensor::ReParent (SCA_IObject * parent) [virtual]
Reimplemented from SCA_ISensor.
Definition at line 70 of file SCA_ActuatorSensor.cpp.
References SCA_IObject::FindActuator(), and m_actuator.
void SCA_ActuatorSensor::Update (void)
Definition at line 111 of file SCA_ActuatorSensor.cpp.
References SCA_ILogicBrick::IsActive(), SCA_IActuator::IsNegativeEvent(), and m_actuator.
Member Data Documentation
SCA_IActuator* SCA_ActuatorSensor::m_actuator [protected]
Definition at line 48 of file SCA_ActuatorSensor.h.
Referenced by Evaluate(), ReParent(), SCA_ActuatorSensor(), and Update().
The documentation for this class was generated from the following files:
SCA_ActuatorSensor.h
SCA_ActuatorSensor.cpp