Blender: FilterGray Class Reference
FilterGray Class Reference
pixel filter for gray scale
#include <FilterColor.h>
Public Member Functions
FilterGray (void)
constructor
virtual ~FilterGray (void)
destructor
Protected Member Functions
template<class SRC >
unsigned int tFilter (SRC src, short x, short y, short *size, unsigned int pixSize, unsigned int val)
filter pixel template, source int buffer
virtual unsigned int filter (unsigned char *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for byte source
virtual unsigned int filter (unsigned int *src, short x, short y, short *size, unsigned int pixSize, unsigned int val=0)
virtual filtering function for unsigned int source
Detailed Description
pixel filter for gray scale
Definition at line 36 of file FilterColor.h.
Constructor & Destructor Documentation
FilterGray::FilterGray (void) [inline]
constructor
Definition at line 40 of file FilterColor.h.
virtual FilterGray::~FilterGray (void) [inline, virtual]
destructor
Definition at line 42 of file FilterColor.h.
Member Function Documentation
virtual unsigned int FilterGray::filter (unsigned char * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for byte source
Reimplemented from FilterBase.
Definition at line 60 of file FilterColor.h.
References tFilter().
virtual unsigned int FilterGray::filter (unsigned int * src, short x, short y, short * size, unsigned int pixSize, unsigned int val = 0) [inline, protected, virtual]
virtual filtering function for unsigned int source
Reimplemented from FilterBase.
Definition at line 64 of file FilterColor.h.
References tFilter().
template<class SRC > unsigned int FilterGray::tFilter (SRC src, short x, short y, short * size, unsigned int pixSize, unsigned int val) [inline, protected]
filter pixel template, source int buffer
Definition at line 46 of file FilterColor.h.
References VT_B, VT_G, and VT_R.
Referenced by filter().
The documentation for this class was generated from the following file:
FilterColor.h