Blender: BKE_group.h File Reference
BKE_group.h File Reference
blenkernel
Functions
void free_group_objects (struct Group *group)
void unlink_group (struct Group *group)
struct Group * add_group (const char *name)
struct Group * copy_group (struct Group *group)
int add_to_group (struct Group *group, struct Object *ob, struct Scene *scene, struct Base *base)
int rem_from_group (struct Group *group, struct Object *ob, struct Scene *scene, struct Base *base)
struct Group * find_group (struct Object *ob, struct Group *group)
int object_in_group (struct Object *ob, struct Group *group)
int group_is_animated (struct Object *parent, struct Group *group)
void group_tag_recalc (struct Group *group)
void group_handle_recalc_and_update (struct Scene *scene, struct Object *parent, struct Group *group)
Detailed Description
Since:
March 2001
Author:
nzc
Definition in file BKE_group.h.
Function Documentation
struct Group* add_group (const char * name) [read]
Definition at line 141 of file group.c.
References alloc_libblock(), G, ID_GR, and Group::layer.
Referenced by group_add_exec(), and group_create_exec().
int add_to_group (struct Group * group, struct Object * ob, struct Scene * scene, struct Base * base)
Definition at line 180 of file group.c.
References add_to_group_internal(), Base::flag, Object::flag, NULL, OB_FROMGROUP, and object_in_scene().
Referenced by group_add_exec(), group_create_exec(), group_link_exec(), object_add_duplicate_internal(), and objects_add_active_exec().
struct Group* copy_group (struct Group * group) [read]
Definition at line 150 of file group.c.
References BLI_duplicatelist(), Group::gobject, and MEM_dupallocN().
Referenced by id_copy().
struct Group* find_group (struct Object * ob, struct Group * group) [read]
Definition at line 254 of file group.c.
References G, Group::id, ID::next, NULL, and object_in_group().
Referenced by group_objects_remove_exec(), rem_from_group(), and unlink_group().
void free_group_objects (struct Group * group)
Definition at line 64 of file group.c.
References BLI_remlink(), ListBase::first, free_group_object(), and Group::gobject.
Referenced by free_libblock(), and unlink_group().
void group_handle_recalc_and_update (struct Scene * scene, struct Object * parent, struct Group * group)
Referenced by group_duplilist(), new_particle_duplilist(), and scene_update_tagged_recursive().
int group_is_animated (struct Object * parent, struct Group * group)
Referenced by group_duplilist().
void group_tag_recalc (struct Group * group)
Definition at line 269 of file group.c.
References ListBase::first, Group::gobject, GroupObject::next, NULL, GroupObject::ob, Object::recalc, and GroupObject::recalc.
int object_in_group (struct Object * ob, struct Group * group)
Definition at line 241 of file group.c.
References ListBase::first, Group::gobject, GroupObject::next, NULL, and GroupObject::ob.
Referenced by animdata_filter_dopesheet(), find_group(), object_add_duplicate_internal(), object_select_same_group_exec(), objects_add_active_exec(), objects_remove_active_exec(), psys_check_group_weights(), and select_grouped_group().
int rem_from_group (struct Group * group, struct Object * ob, struct Scene * scene, struct Base * base)
Definition at line 221 of file group.c.
References find_group(), Base::flag, NULL, OB_FROMGROUP, object_in_scene(), and rem_from_group_internal().
Referenced by group_objects_remove_exec(), group_remove_exec(), lib_link_group(), objects_remove_active_exec(), unlink_group(), and unlink_object().
void unlink_group (struct Group * group)
Definition at line 76 of file group.c.
References Scene::base, ParticleSettings::dup_group, Object::dup_group, find_group(), ListBase::first, Base::flag, Object::flag, free_group_objects(), G, Material::group, Group::id, Object::id, Scene::id, Material::id, RenderData::layers, SceneRenderLayer::light_override, Main::mat, ParticleSystem::next, bActionStrip::next, SceneRenderLayer::next, Base::next, ID::next, NULL, OB_FROMGROUP, bActionStrip::object, Main::object, Base::object, ParticleSystem::part, Object::particlesystem, Scene::r, rem_from_group(), Main::scene, and ID::us.
Referenced by id_unlink(), and unlink_group_cb().