Blender: voxel.c File Reference
voxel.c File Reference
blenlib
#include "BLI_voxel.h"
#include "BLI_utildefines.h"
Functions
BLI_INLINE float D (float *data, const int res[3], int x, int y, int z)
float voxel_sample_nearest (float *data, const int res[3], const float co[3])
BLI_INLINE int FLOORI (float x)
BLI_INLINE int _clamp (int a, int b, int c)
float voxel_sample_trilinear (float *data, const int res[3], const float co[3])
float voxel_sample_triquadratic (float *data, const int res[3], const float co[3])
float voxel_sample_tricubic (float *data, const int res[3], const float co[3], int bspline)
Detailed Description
Definition in file voxel.c.
Function Documentation
BLI_INLINE int _clamp (int a, int b, int c)
Definition at line 68 of file voxel.c.
Referenced by voxel_sample_tricubic(), voxel_sample_trilinear(), and voxel_sample_triquadratic().
BLI_INLINE float D (float * data, const int res[3], int x, int y, int z)
Definition at line 38 of file voxel.c.
References CLAMP(), and V_I.
Referenced by bsdf_ashikhmin_velvet_eval_reflect(), bsdf_ashikhmin_velvet_sample(), bsdf_microfacet_beckmann_eval_reflect(), bsdf_microfacet_beckmann_eval_transmit(), bsdf_microfacet_beckmann_sample(), bsdf_microfacet_ggx_eval_reflect(), bsdf_microfacet_ggx_eval_transmit(), bsdf_microfacet_ggx_sample(), bvh_triangle_refine(), dblur(), MicrofacetBeckmannClosure< Refractive >::eval_reflect(), MicrofacetGGXClosure< Refractive >::eval_reflect(), AshikhminVelvetClosure::eval_reflect(), MicrofacetBeckmannClosure< Refractive >::eval_transmit(), MicrofacetGGXClosure< Refractive >::eval_transmit(), feline_eval(), FHT2D(), md5_process_block(), TNT::QR_factor(), TNT::R_solve(), regular_light_sample(), MicrofacetBeckmannClosure< Refractive >::sample(), MicrofacetGGXClosure< Refractive >::sample(), AshikhminVelvetClosure::sample(), QuadDice::scale_factor(), and voxel_sample_nearest().
BLI_INLINE int FLOORI (float x)
Definition at line 60 of file voxel.c.
Referenced by voxel_sample_tricubic(), voxel_sample_trilinear(), and voxel_sample_triquadratic().
float voxel_sample_nearest (float * data, const int res[3], const float co[3])
Definition at line 48 of file voxel.c.
References D().
Referenced by voxeldatatex().
float voxel_sample_tricubic (float * data, const int res[3], const float co[3], int bspline)
Definition at line 135 of file voxel.c.
References _clamp(), FLOORI(), and ShadeResult::z.
Referenced by voxeldatatex().
float voxel_sample_trilinear (float * data, const int res[3], const float co[3])
Definition at line 73 of file voxel.c.
References _clamp(), FLOORI(), and ShadeResult::z.
Referenced by voxeldatatex().
float voxel_sample_triquadratic (float * data, const int res[3], const float co[3])
Definition at line 105 of file voxel.c.
References _clamp(), FLOORI(), and ShadeResult::z.
Referenced by vol_get_precached_scattering(), and voxeldatatex().