Blender: bmesh_mesh.c File Reference
bmesh_mesh.c File Reference
BMesh
#include "MEM_guardedalloc.h"
#include "DNA_listBase.h"
#include "DNA_object_types.h"
#include "BLI_listbase.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_cdderivedmesh.h"
#include "BKE_tessmesh.h"
#include "BKE_multires.h"
#include "intern/bmesh_private.h"
Defines
#define FACE_FLIP 8
Functions
static void bm_mempool_init (BMesh *bm, const BMAllocTemplate *allocsize)
BMesh * BM_mesh_create (BMAllocTemplate *allocsize)
BMesh Make Mesh.
void BM_mesh_data_free (BMesh *bm)
BMesh Free Mesh Data.
void BM_mesh_clear (BMesh *bm)
BMesh Clear Mesh.
void BM_mesh_free (BMesh *bm)
BMesh Free Mesh.
void BM_mesh_normals_update (BMesh *bm, const short skip_hidden)
BMesh Compute Normals.
static void bm_rationalize_normals (BMesh *bm, int undo)
static void UNUSED_FUNCTION() bm_mdisps_space_set (Object *ob, BMesh *bm, int from, int to)
void bmesh_edit_begin (BMesh *bm, int flag)
BMesh Begin Edit.
void bmesh_edit_end (BMesh *bm, int flag)
BMesh End Edit.
void BM_mesh_elem_index_ensure (BMesh *bm, const char hflag)
void BM_mesh_elem_index_validate (BMesh *bm, const char *location, const char *func, const char *msg_a, const char *msg_b)
int BM_mesh_elem_count (BMesh *bm, const char htype)
void BM_mesh_remap (BMesh *bm, int *vert_idx, int *edge_idx, int *face_idx)
BMVert * BM_vert_at_index (BMesh *bm, const int index)
BMEdge * BM_edge_at_index (BMesh *bm, const int index)
BMFace * BM_face_at_index (BMesh *bm, const int index)
Variables
BMAllocTemplate bm_mesh_allocsize_default = {512, 1024, 2048, 512}
BMAllocTemplate bm_mesh_chunksize_default = {512, 1024, 2048, 512}
Detailed Description
BM mesh level functions.
Definition in file bmesh_mesh.c.
Define Documentation
#define FACE_FLIP 8
Definition at line 299 of file bmesh_mesh.c.
Referenced by bm_rationalize_normals().
Function Documentation
BMEdge* BM_edge_at_index (BMesh * bm, const int index)
Definition at line 766 of file bmesh_mesh.c.
References BLI_mempool_findelem(), and BMesh::epool.
Referenced by EDBM_edge_find_nearest(), and emDM_getEdge().
BMFace* BM_face_at_index (BMesh * bm, const int index)
Definition at line 771 of file bmesh_mesh.c.
References BLI_mempool_findelem(), and BMesh::fpool.
Referenced by EDBM_face_find_nearest().
static void UNUSED_FUNCTION() bm_mdisps_space_set (Object * ob, BMesh * bm, int from, int to) [static]
Definition at line 330 of file bmesh_mesh.c.
References BMEditMesh::bm, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BMEdit_Create(), BMEdit_Free(), CD_MDISPS, CDDM_from_BMEditMesh(), CustomData_bmesh_get(), CustomData_get_layer(), CustomData_has_layer(), BMHeader::data, MDisps::disps, FALSE, BMLoop::head, MDisps::level, DerivedMesh::loopData, MEM_dupallocN(), MEM_freeN(), multires_set_space(), DerivedMesh::needsFree, NULL, DerivedMesh::release, MDisps::totdisp, and TRUE.
static void bm_mempool_init (BMesh * bm, const BMAllocTemplate * allocsize) [static]
Definition at line 48 of file bmesh_mesh.c.
References BLI_MEMPOOL_ALLOW_ITER, BLI_mempool_create(), BMesh::epool, FALSE, BMesh::fpool, BMesh::lpool, BMesh::toolflagpool, BMAllocTemplate::totedge, BMAllocTemplate::totface, BMAllocTemplate::totloop, BMAllocTemplate::totvert, and BMesh::vpool.
Referenced by BM_mesh_clear(), and BM_mesh_create().
void BM_mesh_clear (BMesh * bm)
BMesh Clear Mesh.
Clear all data in bm
Definition at line 153 of file bmesh_mesh.c.
References bm_mempool_init(), BM_mesh_data_free(), BMesh::stackdepth, and BMesh::totflags.
Referenced by bpy_bmesh_clear(), and EDBM_mesh_clear().
BMesh* BM_mesh_create (BMAllocTemplate * allocsize)
BMesh Make Mesh.
Allocates a new BMesh structure.
Returns:
The New bmesh
Note:
ob is needed by multires
Definition at line 72 of file bmesh_mesh.c.
References bm_mempool_init(), MEM_callocN(), BMesh::stackdepth, and BMesh::totflags.
Referenced by BKE_mesh_to_bmesh(), BM_mesh_copy(), bpy_bm_new(), DM_to_bmesh(), DM_to_editbmesh(), mesh_separate_selected(), and undoMesh_to_editbtMesh().
void BM_mesh_data_free (BMesh * bm)
BMesh Free Mesh Data.
Frees a BMesh structure.
Note:
frees mesh, but not actual BMesh struct
Definition at line 94 of file bmesh_mesh.c.
References BLI_freelistN(), BLI_mempool_destroy(), BM_EDGES_OF_MESH, BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_VERTS_OF_MESH, BMO_error_clear(), CustomData_bmesh_free_block(), CustomData_free(), BMHeader::data, BMesh::edata, BMesh::epool, BMesh::fpool, BMEdge::head, BMVert::head, BMFace::head, BMLoop::head, BMesh::ldata, BMesh::lpool, BMesh::pdata, CustomData::pool, BMesh::selected, BMesh::toolflagpool, CustomData::totlayer, BMesh::vdata, and BMesh::vpool.
Referenced by BM_mesh_clear(), and BM_mesh_free().
int BM_mesh_elem_count (BMesh * bm, const char htype)
Return the amount of element of type 'type' in a given bmesh.
Definition at line 582 of file bmesh_mesh.c.
References BM_EDGE, BM_FACE, BM_VERT, BMesh::totedge, BMesh::totface, and BMesh::totvert.
Referenced by bmo_similaredges_exec(), bmo_similarfaces_exec(), bmo_similarverts_exec(), and bmo_vertexshortestpath_exec().
void BM_mesh_elem_index_ensure (BMesh * bm, const char hflag)
Definition at line 446 of file bmesh_mesh.c.
References BLI_assert, BM_EDGE, BM_EDGES_OF_MESH, BM_elem_index_set, BM_ELEM_INDEX_VALIDATE, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMEditSelection::ele, BMesh::elem_index_dirty, BMesh::totedge, BMesh::totface, and BMesh::totvert.
Referenced by bm_edgesplit_validate_seams(), bmo_edgenet_fill_exec(), bpy_bmelemseq_index_update(), calc_solidify_normals(), CDDM_from_BMEditMesh(), construct_param_handle(), construct_param_handle_subsurfed(), crazyspace_set_quats_editmesh(), ED_mesh_mirrtopo_init(), EDBM_uv_element_map_create(), EDBM_uv_vert_map_create(), EDBM_verts_mirror_cache_begin(), edgetag_shortest_path(), editmesh_set_connectivity_distance(), emDM_copyEdgeArray(), emDM_copyLoopArray(), emDM_copyTessFaceArray(), emDM_drawFacesTex_common(), emDM_drawMappedEdges(), emDM_drawMappedEdgesInterp(), emDM_drawMappedFaces(), emDM_drawMappedFacesGLSL(), emDM_drawMappedFacesMat(), emDM_foreachMappedEdge(), emDM_foreachMappedFaceCenter(), getEditDerivedBMesh(), knifetool_init(), mouse_select(), select_edgeloop(), solidify_add_thickness(), stitch_process_data(), uv_find_nearest_edge(), uv_find_nearest_vert(), and vgroup_blend().
void BM_mesh_elem_index_validate (BMesh * bm, const char * location, const char * func, const char * msg_a, const char * msg_b)
Array checking/setting macros
Currently vert/edge/loop/face index data is being abused, in a few areas of the code.
To avoid correcting them afterwards, set 'bm->elem_index_dirty' however its possible this flag is set incorrectly which could crash blender.
These functions ensure its correct and are called more often in debug mode.
Definition at line 513 of file bmesh_mesh.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_FACES_OF_MESH, BM_ITER_MESH, BM_VERT, BM_VERTS_OF_MESH, BMEditSelection::ele, BMesh::elem_index_dirty, FALSE, i, TRUE, and type_names.
void BM_mesh_free (BMesh * bm)
BMesh Free Mesh.
Frees a BMesh data and its structure.
Definition at line 171 of file bmesh_mesh.c.
References BM_mesh_data_free(), bpy_bm_generic_invalidate(), MEM_freeN(), NULL, and BMesh::py_handle.
Referenced by BMEdit_Free(), bpy_bmesh_dealloc(), bpy_bmesh_free(), and mesh_separate_selected().
void BM_mesh_normals_update (BMesh * bm, const short skip_hidden)
BMesh Compute Normals.
Updates the normals of a mesh.
Definition at line 192 of file bmesh_mesh.c.
References BM_EDGE, BM_EDGES_OF_MESH, BM_elem_flag_test, BM_ELEM_HIDDEN, BM_elem_index_get, BM_elem_index_set, BM_face_normal_update(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_VERTS_OF_MESH, BMVert::co, dot_v3v3(), BMLoop::e, BMesh::elem_index_dirty, BMFace::head, BMEdge::l, madd_v3_v3fl(), MEM_callocN(), MEM_freeN(), BMFace::no, BMVert::no, normalize_v3(), normalize_v3_v3(), BMLoop::prev, saacos(), sub_v3_v3v3(), BMesh::totedge, BMLoop::v, BMEdge::v1, BMEdge::v2, and zero_v3().
Referenced by bmesh_edit_begin(), bmesh_edit_end(), bpy_bmesh_normal_update(), doEdgeSplit(), EDBM_mesh_normals_update(), mesh_separate_selected(), special_transvert_update(), and undoMesh_to_editbtMesh().
void BM_mesh_remap (BMesh * bm, int * vert_idx, int * edge_idx, int * face_idx)
Remaps the vertices, edges and/or faces of the bmesh as indicated by vert/edge/face_idx arrays (xxx_idx[org_index] = new_index).
A NULL array means no changes.
Note: - Does not mess with indices, just sets elem_index_dirty flag.
For verts/edges/faces only (as loops must remain "ordered" and "aligned" on a per-face basis...).
WARNING: Be careful if you keep pointers to affected BM elements, or arrays, when using this func!
Definition at line 603 of file bmesh_mesh.c.
References BLI_ghash_free(), BLI_ghash_insert(), BLI_ghash_lookup(), BLI_ghash_new(), BLI_ghashutil_ptrcmp(), BLI_ghashutil_ptrhash(), BM_EDGE, BM_EDGES_OF_MESH, BM_FACE, BM_FACES_OF_MESH, BM_iter_as_array(), BM_ITER_ELEM, BM_ITER_MESH, BM_LOOPS_OF_FACE, BM_VERT, BM_VERTS_OF_MESH, BMLoop::e, BMVert::e, BMesh::elem_index_dirty, BMLoop::f, i, MEM_callocN(), MEM_freeN(), MEM_mallocN(), NULL, BMesh::totedge, BMesh::totface, BMesh::totvert, BMLoop::v, BMEdge::v1, and BMEdge::v2.
Referenced by hashvert_flag(), and xsortvert_flag().
static void bm_rationalize_normals (BMesh * bm, int undo) [static]
Definition at line 300 of file bmesh_mesh.c.
References BM_elem_flag_disable, BM_elem_flag_set, BM_elem_flag_test, BM_ELEM_TAG, BM_face_normal_flip(), BM_FACES_OF_MESH, BM_ITER_MESH, BMO_elem_flag_test, BMO_op_finish(), BMO_op_initf(), BMO_pop(), BMO_push(), bmo_righthandfaces_exec(), FACE_FLIP, and FALSE.
Referenced by bmesh_edit_begin(), and bmesh_edit_end().
BMVert* BM_vert_at_index (BMesh * bm, const int index)
Definition at line 761 of file bmesh_mesh.c.
References BLI_mempool_findelem(), and BMesh::vpool.
Referenced by EDBM_vert_find_nearest(), emDM_getVert(), findnearestvert__backbufIndextest(), get_vert_def_nr(), and knife_start_cut().
void bmesh_edit_begin (BMesh * bm, int flag)
BMesh Begin Edit.
Functions for setting up a mesh for editing and cleaning up after the editing operations are done. These are called by the tools/operator API for each time a tool is executed.
Definition at line 389 of file bmesh_mesh.c.
References BM_mesh_normals_update(), bm_rationalize_normals(), BMO_OP_FLAG_RATIONALIZE_NORMALS, BMO_OP_FLAG_UNTAN_MULTIRES, CD_MDISPS, CustomData_has_layer(), BMesh::ldata, MULTIRES_SPACE_ABSOLUTE, MULTIRES_SPACE_TANGENT, and BMesh::opflag.
Referenced by arrayModifier_doArray(), BME_bevel(), BMO_op_exec(), and createSlideVerts().
void bmesh_edit_end (BMesh * bm, int flag)
BMesh End Edit.
Definition at line 420 of file bmesh_mesh.c.
References BM_mesh_normals_update(), BM_mesh_select_mode_flush(), bm_rationalize_normals(), BMO_OP_FLAG_RATIONALIZE_NORMALS, BMO_OP_FLAG_UNTAN_MULTIRES, CD_MDISPS, CustomData_has_layer(), BMesh::ldata, MULTIRES_SPACE_ABSOLUTE, MULTIRES_SPACE_TANGENT, BMesh::opflag, and TRUE.
Referenced by BME_bevel(), BMO_op_exec(), and freeSlideVerts().
Variable Documentation
BMAllocTemplate bm_mesh_allocsize_default = {512, 1024, 2048, 512}
Definition at line 45 of file bmesh_mesh.c.
Referenced by BKE_mesh_to_bmesh(), bpy_bm_new(), DM_to_bmesh(), DM_to_editbmesh(), mesh_separate_selected(), and undoMesh_to_editbtMesh().
BMAllocTemplate bm_mesh_chunksize_default = {512, 1024, 2048, 512}
Definition at line 46 of file bmesh_mesh.c.
Referenced by CustomData_bmesh_init_pool().