Blender: quicktime_import.h File Reference
quicktime_import.h File Reference
quicktime
#include "../imbuf/IMB_imbuf.h"
#include "../imbuf/IMB_imbuf_types.h"
Defines
#define __AIFF__
Functions
char * get_valid_qtname (char *name)
int anim_is_quicktime (const char *name)
int startquicktime (struct anim *anim)
void free_anim_quicktime (struct anim *anim)
ImBuf * qtime_fetchibuf (struct anim *anim, int position)
int imb_is_a_quicktime (char *name)
ImBuf * imb_quicktime_decode (unsigned char *mem, int size, int flags)
Detailed Description
Definition in file quicktime_import.h.
Define Documentation
#define __AIFF__
Definition at line 40 of file quicktime_import.h.
Function Documentation
int anim_is_quicktime (const char * name)
void free_anim_quicktime (struct anim * anim)
Referenced by anim_getnew(), and IMB_free_anim().
char* get_valid_qtname (char * name)
int imb_is_a_quicktime (char * name)
ImBuf* imb_quicktime_decode (unsigned char * mem, int size, int flags)
ImBuf* qtime_fetchibuf (struct anim * anim, int position)
Referenced by IMB_anim_absolute().
int startquicktime (struct anim * anim)
Referenced by anim_getnew().