Blender: BlockDXT5 Struct Reference
BlockDXT5 Struct Reference
DXT5 block.
#include <BlockDXT.h>
Public Member Functions
void decodeBlock (ColorBlock *block) const
void decodeBlockNV5x (ColorBlock *block) const
void flip4 ()
Flip DXT5 block vertically.
void flip2 ()
Flip half DXT5 block vertically.
Public Attributes
AlphaBlockDXT5 alpha
BlockDXT1 color
Detailed Description
DXT5 block.
Definition at line 211 of file BlockDXT.h.
Member Function Documentation
void BlockDXT5::decodeBlock (ColorBlock * block) const
Definition at line 457 of file BlockDXT.cpp.
References alpha, color, BlockDXT1::decodeBlock(), and AlphaBlockDXT5::decodeBlock().
void BlockDXT5::decodeBlockNV5x (ColorBlock * block) const
Definition at line 466 of file BlockDXT.cpp.
References alpha, color, AlphaBlockDXT5::decodeBlock(), and BlockDXT1::decodeBlockNV5x().
void BlockDXT5::flip2 ()
Flip half DXT5 block vertically.
Definition at line 483 of file BlockDXT.cpp.
References alpha, color, BlockDXT1::flip2(), and AlphaBlockDXT5::flip2().
void BlockDXT5::flip4 ()
Flip DXT5 block vertically.
Definition at line 476 of file BlockDXT.cpp.
References alpha, color, BlockDXT1::flip4(), and AlphaBlockDXT5::flip4().
Member Data Documentation
AlphaBlockDXT5 BlockDXT5::alpha
Definition at line 213 of file BlockDXT.h.
Referenced by decodeBlock(), decodeBlockNV5x(), flip2(), flip4(), and mem_read().
BlockDXT1 BlockDXT5::color
Definition at line 214 of file BlockDXT.h.
Referenced by decodeBlock(), decodeBlockNV5x(), flip2(), flip4(), and mem_read().
The documentation for this struct was generated from the following files:
BlockDXT.h
BlockDXT.cpp