Blender: util_transform.h File Reference
util_transform.h File Reference
#include <string.h>
#include "util_math.h"
#include "util_types.h"
Classes
struct Transform
Typedefs
typedef CCL_NAMESPACE_BEGIN
struct Transform Transform
Functions
__device_inline float3 transform_perspective (const Transform *t, const float3 a)
__device_inline float3 transform_point (const Transform *t, const float3 a)
__device_inline float3 transform_direction (const Transform *t, const float3 a)
__device_inline void print_transform (const char *label, const Transform &t)
__device_inline Transform transform_transpose (const Transform a)
__device_inline Transform operator* (const Transform a, const Transform b)
__device_inline Transform make_transform (float a, float b, float c, float d, float e, float f, float g, float h, float i, float j, float k, float l, float m, float n, float o, float p)
__device_inline Transform transform_translate (float3 t)
__device_inline Transform transform_translate (float x, float y, float z)
__device_inline Transform transform_scale (float3 s)
__device_inline Transform transform_scale (float x, float y, float z)
__device_inline Transform transform_perspective (float fov, float n, float f)
__device_inline Transform transform_rotate (float angle, float3 axis)
__device_inline Transform transform_euler (float3 euler)
__device_inline Transform transform_orthographic (float znear, float zfar)
__device_inline Transform transform_identity ()
__device_inline bool operator== (const Transform &A, const Transform &B)
__device_inline bool operator!= (const Transform &A, const Transform &B)
__device_inline float3 transform_get_column (const Transform *t, int column)
__device_inline void transform_set_column (Transform *t, int column, float3 value)
Transform transform_inverse (const Transform &a)
__device_inline bool transform_uniform_scale (const Transform &tfm, float &scale)
__device_inline bool transform_negative_scale (const Transform &tfm)
__device_inline Transform transform_clear_scale (const Transform &tfm)
Typedef Documentation
Vector Camera Vector Extended Separate Hue Lamp Mix Glossy Translucent Velvet Isotropic Image Sky Noise Wave Voronoi Texture Mix RGB to Vector Alpha Separate Set Z Dilate Combine Combine Color Channel Split ID Combine Luma Directional Premul Distance Hue Transform
Definition at line 158 of file rna_nodetree_types.h.
Function Documentation
__device_inline Transform make_transform (float a, float b, float c, float d, float e, float f, float g, float h, float i, float j, float k, float l, float m, float n, float o, float p)
Definition at line 101 of file util_transform.h.
References g, i, p, Transform::w, float4::w, float4::x, Transform::x, Transform::y, float4::y, Transform::z, and float4::z.
Referenced by blender_camera_sync(), BVH::pack_triangle(), transform_perspective(), transform_rotate(), transform_scale(), and transform_translate().
__device_inline bool operator!= (const Transform & A, const Transform & B)
Definition at line 210 of file util_transform.h.
References B.
__device_inline Transform operator* (const Transform a, const Transform b)
Definition at line 88 of file util_transform.h.
References dot(), make_float4(), transform_transpose(), Transform::w, Transform::x, Transform::y, and Transform::z.
__device_inline bool operator== (const Transform & A, const Transform & B)
Definition at line 205 of file util_transform.h.
__device_inline void print_transform (const char * label, const Transform & t)
Definition at line 67 of file util_transform.h.
References print_float4(), Transform::w, Transform::x, Transform::y, and Transform::z.
__device_inline Transform transform_clear_scale (const Transform & tfm)
Definition at line 262 of file util_transform.h.
References normalize(), transform_get_column(), and transform_set_column().
Referenced by blender_camera_focal_distance(), and blender_camera_sync().
__device_inline float3 transform_direction (const Transform * t, const float3 a)
Definition at line 57 of file util_transform.h.
References dot(), make_float3(), make_float4(), Transform::x, float3::x, float3::y, Transform::y, float3::z, and Transform::z.
Referenced by Object::apply_transform(), bvh_instance_pop(), bvh_instance_push(), bvh_triangle_refine(), camera_sample_environment(), camera_sample_orthographic(), camera_sample_perspective(), mbvh_instance_pop(), mbvh_instance_push(), object_dir_transform(), object_normal_transform(), qbvh_instance_pop(), qbvh_instance_push(), and Camera::update().
__device_inline Transform transform_euler (float3 euler)
Definition at line 186 of file util_transform.h.
References make_float3(), transform_rotate(), float3::x, float3::y, and float3::z.
Referenced by TextureMapping::compute_transform().
__device_inline float3 transform_get_column (const Transform * t, int column)
Definition at line 215 of file util_transform.h.
References make_float3(), Transform::x, Transform::y, and Transform::z.
Referenced by blender_camera_focal_distance(), transform_clear_scale(), and transform_negative_scale().
__device_inline Transform transform_identity ()
Definition at line 200 of file util_transform.h.
References transform_scale().
Referenced by Object::apply_transform(), Camera::Camera(), Object::Object(), transform_inverse(), Camera::update(), xml_read_file(), and xml_read_patch().
Transform transform_inverse (const Transform & a)
Definition at line 130 of file util_transform.cpp.
References M, R, T, transform_identity(), and transform_matrix4_gj_inverse().
Referenced by Object::apply_transform(), blender_camera_focal_distance(), Camera::device_update(), ObjectManager::device_update_transforms(), BVH::pack_triangle(), BlenderSync::sync_view(), and Camera::update().
__device_inline bool transform_negative_scale (const Transform & tfm)
Definition at line 253 of file util_transform.h.
References cross(), dot(), and transform_get_column().
Referenced by Object::apply_transform().
__device_inline Transform transform_orthographic (float znear, float zfar)
Definition at line 194 of file util_transform.h.
References transform_scale(), and transform_translate().
Referenced by Camera::update().
__device_inline Transform transform_perspective (float fov, float n, float f)
Definition at line 144 of file util_transform.h.
References make_transform(), tanf, and transform_scale().
__device_inline float3 transform_perspective (const Transform * t, const float3 a)
Definition at line 40 of file util_transform.h.
References dot(), make_float3(), make_float4(), Transform::w, Transform::x, float3::x, float3::y, Transform::y, float3::z, and Transform::z.
Referenced by camera_sample_environment(), camera_sample_orthographic(), camera_sample_perspective(), QuadDice::eval_projected(), DiagSplit::project(), svm_node_tex_coord(), svm_node_tex_coord_bump_dx(), svm_node_tex_coord_bump_dy(), and Camera::update().
__device_inline float3 transform_point (const Transform * t, const float3 a)
Definition at line 49 of file util_transform.h.
References dot(), make_float3(), make_float4(), Transform::x, float3::x, Transform::y, float3::y, Transform::z, and float3::z.
Referenced by Object::apply_transform(), bvh_instance_push(), bvh_triangle_refine(), camera_sample_environment(), camera_sample_orthographic(), camera_sample_perspective(), LightManager::device_update_distribution(), ObjectManager::device_update_transforms(), kernel_write_data_passes(), mbvh_instance_push(), object_position_transform(), qbvh_instance_push(), svm_node_camera(), svm_node_mapping(), svm_node_tex_coord(), svm_node_tex_coord_bump_dx(), svm_node_tex_coord_bump_dy(), BoundBox::transformed(), xml_read_light(), and xml_read_patch().
__device_inline Transform transform_rotate (float angle, float3 axis)
Definition at line 159 of file util_transform.h.
References cosf, make_transform(), normalize(), sinf, float3::x, float3::y, and float3::z.
Referenced by transform_euler(), and xml_read_transform().
__device_inline Transform transform_scale (float3 s)
Definition at line 130 of file util_transform.h.
References make_transform(), float3::x, float3::y, and float3::z.
Referenced by blender_camera_sync(), TextureMapping::compute_transform(), transform_identity(), transform_orthographic(), transform_perspective(), transform_scale(), Camera::update(), and xml_read_transform().
__device_inline Transform transform_scale (float x, float y, float z)
Definition at line 139 of file util_transform.h.
References make_float3(), and transform_scale().
__device_inline void transform_set_column (Transform * t, int column, float3 value)
Definition at line 220 of file util_transform.h.
References Transform::x, float3::x, float3::y, Transform::y, float3::z, and Transform::z.
Referenced by transform_clear_scale().
__device_inline Transform transform_translate (float x, float y, float z)
Definition at line 125 of file util_transform.h.
References make_float3(), and transform_translate().
__device_inline Transform transform_translate (float3 t)
Definition at line 116 of file util_transform.h.
References make_transform(), float3::x, float3::y, and float3::z.
Referenced by TextureMapping::compute_transform(), transform_orthographic(), transform_translate(), Camera::update(), and xml_read_transform().
__device_inline Transform transform_transpose (const Transform a)
Definition at line 76 of file util_transform.h.
References Transform::w, float4::w, Transform::x, float4::x, float4::y, Transform::y, float4::z, and Transform::z.
Referenced by Object::apply_transform(), ObjectManager::device_update_transforms(), OSLRenderServices::get_inverse_matrix(), OSLRenderServices::get_matrix(), get_transform(), operator*(), transform_uniform_scale(), and xml_read_transform().
__device_inline bool transform_uniform_scale (const Transform & tfm, float & scale)
Definition at line 229 of file util_transform.h.
References fabsf, float4_to_float3(), len(), transform_transpose(), Transform::x, Transform::y, and Transform::z.
Referenced by ObjectManager::device_update_transforms().