Blender: screen_intern.h File Reference
screen_intern.h File Reference
screen
Defines
#define AZONESPOT 12
Functions
void area_copy_data (ScrArea *sa1, ScrArea *sa2, int swap_space)
ScrEdge * screen_findedge (bScreen *sc, ScrVert *v1, ScrVert *v2)
ScrArea * area_split (bScreen *sc, ScrArea *sa, char dir, float fac, int merge)
int screen_area_join (bContext *C, bScreen *scr, ScrArea *sa1, ScrArea *sa2)
int area_getorientation (ScrArea *sa, ScrArea *sb)
void select_connected_scredge (bScreen *sc, ScrEdge *edge)
void removenotused_scrverts (bScreen *sc)
void removedouble_scrverts (bScreen *sc)
void removedouble_scredges (bScreen *sc)
void removenotused_scredges (bScreen *sc)
int scredge_is_horizontal (ScrEdge *se)
ScrEdge * screen_find_active_scredge (bScreen *sc, int mx, int my)
struct AZone * is_in_area_actionzone (ScrArea *sa, int x, int y)
int ed_screen_context (const bContext *C, const char *member, bContextDataResult *result)
void SCREEN_OT_screenshot (struct wmOperatorType *ot)
void SCREEN_OT_screencast (struct wmOperatorType *ot)
Variables
const char * screen_context_dir []
Detailed Description
Definition in file screen_intern.h.
Define Documentation
#define AZONESPOT 12
Definition at line 38 of file screen_intern.h.
Referenced by area_azone_initialize(), is_in_area_actionzone(), and region_azone_icon().
Function Documentation
void area_copy_data (ScrArea * sa1, ScrArea * sa2, int swap_space)
Definition at line 1287 of file area.c.
References BKE_area_region_copy(), BKE_area_region_free(), BKE_spacedata_copylist(), BKE_spacedata_freelist(), BKE_spacetype_from_id(), BLI_addtail(), BLI_freelistN(), ScrArea::butspacetype, ListBase::first, ScrArea::headertype, ARegion::next, ScrArea::regionbase, ScrArea::spacedata, ScrArea::spacetype, and SWAP.
Referenced by area_dupli_invoke(), area_split(), ED_area_swapspace(), ED_screen_full_toggle(), and screen_copy().
int area_getorientation (ScrArea * sa, ScrArea * sb)
Definition at line 494 of file screen_edit.c.
References NULL, ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_join_modal(), ED_screen_draw(), and screen_area_join().
ScrArea* area_split (bScreen * sc, ScrArea * sa, char dir, float fac, int merge)
Definition at line 353 of file screen_edit.c.
References area_copy_data(), ScrArea::headertype, NULL, removedouble_scredges(), removedouble_scrverts(), removenotused_scredges(), screen_addarea(), screen_addedge(), screen_addvert(), ScrArea::spacetype, split(), testsplitpoint(), ScrArea::v1, ScrArea::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by area_split_apply(), and ED_screen_full_toggle().
int ed_screen_context (const bContext * C, const char * member, bContextDataResult * result)
Definition at line 73 of file screen_context.c.
References bArmature::act_bone, bArmature::act_edbone, ARM_MIRROR_EDIT, BASACT, Scene::base, BONE_SELECTED, bPose::chanbase, CTX_data_active_base(), CTX_data_active_object(), CTX_data_dir(), CTX_data_dir_set(), CTX_data_edit_object(), CTX_data_equals(), CTX_data_id_list_add(), CTX_data_id_pointer_set(), CTX_data_list_add(), CTX_data_pointer_set(), CTX_DATA_TYPE_COLLECTION, CTX_data_type_set(), CTX_wm_screen(), CTX_wm_space_file(), Object::data, EBONE_EDITABLE, EBONE_VISIBLE, ED_armature_bone_get_mirrored(), bArmature::edbo, FALSE, ListBase::first, Sequence::flag, bArmature::flag, Base::flag, get_active_posechannel(), bArmature::id, Object::id, Scene::id, if(), Base::lay, Scene::lay, Object::mode, Sequence::next, Base::next, NULL, OB_ARMATURE, OB_MODE_PARTICLE_EDIT, OB_MODE_SCULPT, OB_MODE_TEXTURE_PAINT, OB_MODE_VERTEX_PAINT, OB_MODE_WEIGHT_PAINT, OB_RESTRICT_SELECT, OB_RESTRICT_VIEW, OBACT, Scene::obedit, Base::object, object_is_libdata(), object_pose_armature_get(), SpaceFile::op, PBONE_VISIBLE, Object::pose, wmOperator::ptr, Object::restrictflag, RNA_Bone, RNA_EditBone, RNA_ObjectBase, RNA_Operator, RNA_PoseBone, RNA_Sequence, bScreen::scene, screen_context_dir, SELECT, seq_give_editing(), SEQ_LOCK, Editing::seqbasep, Object::type, uiContextActiveOperator(), and WM_operator_last_redo().
Referenced by ED_screen_refresh().
struct AZone* is_in_area_actionzone (ScrArea * sa, int x, int y) [read]
Definition at line 513 of file screen_ops.c.
References ScrArea::actionzones, AZONE_AREA, AZONE_REGION, AZONESPOT, BLI_in_rcti(), ListBase::first, AZone::next, NULL, AZone::rect, AZone::type, AZone::x1, and AZone::y1.
Referenced by actionzone_invoke(), ED_screen_area_active(), ED_screen_set_subwinactive(), and screen_cursor_set().
void removedouble_scredges (bScreen * sc)
Definition at line 200 of file screen_edit.c.
References BLI_remlink(), bScreen::edgebase, ListBase::first, MEM_freeN(), ScrEdge::next, ScrEdge::v1, and ScrEdge::v2.
Referenced by area_join_exit(), area_move_exit(), area_split(), and area_split_exit().
void removedouble_scrverts (bScreen * sc)
Definition at line 120 of file screen_edit.c.
References bScreen::areabase, BLI_remlink(), bScreen::edgebase, ListBase::first, MEM_freeN(), ScrVert::newv, ScrArea::next, ScrEdge::next, ScrVert::next, NULL, sortscrvert(), ScrEdge::v1, ScrArea::v1, ScrArea::v2, ScrEdge::v2, ScrArea::v3, ScrArea::v4, ScrVert::vec, bScreen::vertbase, vec2s::x, and vec2s::y.
Referenced by area_move_exit(), area_split(), area_split_exit(), and screen_area_join().
void removenotused_scredges (bScreen * sc)
Definition at line 220 of file screen_edit.c.
References bScreen::areabase, BLI_remlink(), bScreen::edgebase, ListBase::first, ScrEdge::flag, MEM_freeN(), ScrEdge::next, ScrArea::next, NULL, screen_findedge(), ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_join_exit(), and area_split().
void removenotused_scrverts (bScreen * sc)
Definition at line 174 of file screen_edit.c.
References BLI_remlink(), bScreen::edgebase, ListBase::first, ScrVert::flag, MEM_freeN(), ScrVert::next, ScrEdge::next, ScrEdge::v1, ScrEdge::v2, and bScreen::vertbase.
Referenced by area_join_exit().
int scredge_is_horizontal (ScrEdge * se)
Definition at line 256 of file screen_edit.c.
References ScrEdge::v1, ScrEdge::v2, ScrVert::vec, and vec2s::y.
Referenced by area_move_init(), area_split_invoke(), screen_cursor_set(), and screen_find_active_scredge().
int screen_area_join (bContext * C, bScreen * scr, ScrArea * sa1, ScrArea * sa2)
Definition at line 529 of file screen_edit.c.
References AREA_FLAG_DRAWJOINFROM, AREA_FLAG_DRAWJOINTO, area_getorientation(), ScrArea::flag, removedouble_scrverts(), screen_addedge(), screen_delarea(), ScrArea::v1, ScrArea::v2, ScrArea::v3, and ScrArea::v4.
Referenced by area_join_apply(), and area_split_cancel().
ScrEdge* screen_find_active_scredge (bScreen * sc, int mx, int my)
Definition at line 261 of file screen_edit.c.
References abs(), bScreen::edgebase, ListBase::first, max, MAX2, min, MIN2, ScrEdge::next, NULL, scredge_is_horizontal(), ScrEdge::v1, ScrEdge::v2, ScrVert::vec, vec2s::x, and vec2s::y.
Referenced by area_move_init(), area_split_invoke(), screen_area_options_invoke(), and screen_cursor_set().
ScrEdge* screen_findedge (bScreen * sc, ScrVert * v1, ScrVert * v2)
Definition at line 108 of file screen_edit.c.
References bScreen::edgebase, ListBase::first, ScrEdge::next, NULL, sortscrvert(), ScrEdge::v1, and ScrEdge::v2.
Referenced by area_findsharededge(), removenotused_scredges(), and screen_test_scale().
void SCREEN_OT_screencast (struct wmOperatorType * ot)
Definition at line 432 of file screendump.c.
References wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, PROP_FILEPATH, PROP_STRING, RNA_def_boolean(), RNA_def_property(), screencast_exec(), wmOperatorType::srna, WM_operator_confirm(), and WM_operator_winactive().
Referenced by ED_operatortypes_screen().
void SCREEN_OT_screenshot (struct wmOperatorType * ot)
Definition at line 254 of file screendump.c.
References wmOperatorType::cancel, wmOperatorType::check, wmOperatorType::exec, FILE_DEFAULTDISPLAY, FILE_SAVE, FILE_SPECIAL, wmOperatorType::flag, FOLDERFILE, wmOperatorType::idname, IMAGEFILE, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), screenshot_cancel(), screenshot_check(), screenshot_draw(), screenshot_exec(), screenshot_invoke(), wmOperatorType::srna, wmOperatorType::ui, WM_FILESEL_FILEPATH, WM_operator_properties_filesel(), and WM_operator_winactive().
Referenced by ED_operatortypes_screen().
void select_connected_scredge (bScreen * sc, ScrEdge * edge)
Definition at line 574 of file screen_edit.c.
References bScreen::edgebase, ListBase::first, ScrVert::flag, ScrVert::next, ScrEdge::next, ScrEdge::v1, ScrEdge::v2, ScrVert::vec, bScreen::vertbase, vec2s::x, and vec2s::y.
Referenced by area_move_init(), and screen_test_scale().
Variable Documentation
const char* screen_context_dir[]
Definition at line 60 of file screen_context.c.
Referenced by ed_screen_context().