Blender: bpy_rna_anim.c File Reference
bpy_rna_anim.c File Reference
Python RNA and Operators
#include <Python.h>
#include <float.h>
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_string.h"
#include "DNA_scene_types.h"
#include "DNA_anim_types.h"
#include "ED_keyframing.h"
#include "BKE_report.h"
#include "BKE_context.h"
#include "BKE_animsys.h"
#include "BKE_fcurve.h"
#include "RNA_access.h"
#include "WM_api.h"
#include "WM_types.h"
#include "bpy_rna.h"
#include "bpy_util.h"
#include "bpy_rna_anim.h"
Defines
#define TRUE 1
#define FALSE 0
Functions
static int pyrna_struct_anim_args_parse (PointerRNA *ptr, const char *error_prefix, const char *path, const char **path_full, int *index)
static int pyrna_struct_keyframe_parse (PointerRNA *ptr, PyObject *args, PyObject *kw, const char *parse_str, const char *error_prefix, const char **path_full, int *index, float *cfra, const char **group_name)
PyObject * pyrna_struct_keyframe_insert (BPy_StructRNA *self, PyObject *args, PyObject *kw)
PyObject * pyrna_struct_keyframe_delete (BPy_StructRNA *self, PyObject *args, PyObject *kw)
PyObject * pyrna_struct_driver_add (BPy_StructRNA *self, PyObject *args)
PyObject * pyrna_struct_driver_remove (BPy_StructRNA *self, PyObject *args)
Variables
char pyrna_struct_keyframe_insert_doc [] = " :rtype: boolean\n"
char pyrna_struct_keyframe_delete_doc [] = " :rtype: boolean\n"
char pyrna_struct_driver_add_doc [] = " :rtype: :class:`bpy.types.FCurve` or list if index is -1 with an array property.\n"
char pyrna_struct_driver_remove_doc [] = " :rtype: boolean\n"
Detailed Description
This file defines the animation related methods used in bpy_rna.c
Definition in file bpy_rna_anim.c.
Define Documentation
#define FALSE 0
Definition at line 56 of file bpy_rna_anim.c.
#define TRUE 1
Definition at line 55 of file bpy_rna_anim.c.
Referenced by pyrna_struct_driver_add(), pyrna_struct_driver_remove(), pyrna_struct_keyframe_delete(), and pyrna_struct_keyframe_insert().
Function Documentation
static int pyrna_struct_anim_args_parse (PointerRNA * ptr, const char * error_prefix, const char * path, const char ** path_full, int * index) [static]
Definition at line 59 of file bpy_rna_anim.c.
References BLI_strdup(), PointerRNA::data, PointerRNA::id, NULL, RNA_path_from_ID_to_property(), RNA_path_resolve_full(), RNA_property_animateable(), RNA_property_array_check(), RNA_property_array_length(), RNA_struct_find_property(), RNA_struct_is_ID(), and PointerRNA::type.
Referenced by pyrna_struct_driver_add(), pyrna_struct_driver_remove(), and pyrna_struct_keyframe_parse().
PyObject* pyrna_struct_driver_add (BPy_StructRNA * self, PyObject * args)
Definition at line 281 of file bpy_rna_anim.c.
References ANIM_add_driver(), BKE_animdata_from_id(), BKE_reports_init(), BPy_GetContext(), BPy_reports_to_error(), DRIVER_TYPE_PYTHON, AnimData::drivers, i, list_find_fcurve(), MEM_freeN(), NC_ANIMATION, ND_FCURVES_ORDER, NULL, pyrna_struct_anim_args_parse(), PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_CreatePyObject(), RNA_FCurve, RNA_pointer_create(), RPT_STORE, TRUE, and WM_event_add_notifier().
PyObject* pyrna_struct_driver_remove (BPy_StructRNA * self, PyObject * args)
Definition at line 357 of file bpy_rna_anim.c.
References ANIM_remove_driver(), BKE_reports_init(), BPy_GetContext(), BPy_reports_to_error(), MEM_freeN(), NC_ANIMATION, ND_FCURVES_ORDER, NULL, pyrna_struct_anim_args_parse(), PYRNA_STRUCT_CHECK_OBJ, RPT_STORE, TRUE, and WM_event_add_notifier().
PyObject* pyrna_struct_keyframe_delete (BPy_StructRNA * self, PyObject * args, PyObject * kw)
Definition at line 235 of file bpy_rna_anim.c.
References BKE_reports_init(), BPy_reports_to_error(), delete_keyframe(), FLT_MAX, MEM_freeN(), NULL, PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_keyframe_parse(), RPT_STORE, and TRUE.
PyObject* pyrna_struct_keyframe_insert (BPy_StructRNA * self, PyObject * args, PyObject * kw)
Definition at line 187 of file bpy_rna_anim.c.
References BKE_reports_init(), BPy_reports_to_error(), FLT_MAX, insert_keyframe(), MEM_freeN(), NULL, PYRNA_STRUCT_CHECK_OBJ, pyrna_struct_keyframe_parse(), RPT_STORE, and TRUE.
static int pyrna_struct_keyframe_parse (PointerRNA * ptr, PyObject * args, PyObject * kw, const char * parse_str, const char * error_prefix, const char ** path_full, int * index, float * cfra, const char ** group_name) [static]
Definition at line 151 of file bpy_rna_anim.c.
References BPy_GetContext(), RenderData::cfra, CTX_data_scene(), FLT_MAX, NULL, pyrna_struct_anim_args_parse(), and Scene::r.
Referenced by pyrna_struct_keyframe_delete(), and pyrna_struct_keyframe_insert().
Variable Documentation
char pyrna_struct_driver_add_doc[] = " :rtype: :class:`bpy.types.FCurve` or list if index is -1 with an array property.\n"
Definition at line 269 of file bpy_rna_anim.c.
char pyrna_struct_driver_remove_doc[] = " :rtype: boolean\n"
Definition at line 345 of file bpy_rna_anim.c.
char pyrna_struct_keyframe_delete_doc[] = " :rtype: boolean\n"
Definition at line 219 of file bpy_rna_anim.c.
char pyrna_struct_keyframe_insert_doc[] = " :rtype: boolean\n"
Definition at line 171 of file bpy_rna_anim.c.