Blender: BKE_mesh.h File Reference
BKE_mesh.h File Reference
blenkernel
Classes
struct UvVertMap
struct UvMapVert
struct UvElement
struct UvElementMap
struct MeshElemMap
struct IndexNode
Defines
#define STD_UV_CONNECT_LIMIT 0.0001f
#define INVALID_ISLAND 0xFFFF
#define INVALID_LOOP_EDGE_MARKER 4294967295u
Typedefs
typedef struct UvVertMap UvVertMap
typedef struct UvMapVert UvMapVert
typedef struct UvElement UvElement
typedef struct UvElementMap UvElementMap
typedef struct MeshElemMap MeshElemMap
typedef struct IndexNode IndexNode
Functions
struct BMesh * BKE_mesh_to_bmesh (struct Mesh *me, struct Object *ob)
int mesh_recalcTessellation (struct CustomData *fdata, struct CustomData *ldata, struct CustomData *pdata, struct MVert *mvert, int totface, int totloop, int totpoly, const int do_face_normals)
int mesh_mpoly_to_mface (struct CustomData *fdata, struct CustomData *ldata, struct CustomData *pdata, int totface, int totloop, int totpoly)
void mesh_calc_poly_normal (struct MPoly *mpoly, struct MLoop *loopstart, struct MVert *mvarray, float no[3])
void mesh_calc_poly_normal_coords (struct MPoly *mpoly, struct MLoop *loopstart, const float(*vertex_coords)[3], float no[3])
void mesh_calc_poly_center (struct MPoly *mpoly, struct MLoop *loopstart, struct MVert *mvarray, float cent[3])
float mesh_calc_poly_area (struct MPoly *mpoly, struct MLoop *loopstart, struct MVert *mvarray, float polynormal[3])
int poly_find_loop_from_vert (const struct MPoly *poly, const struct MLoop *loopstart, unsigned vert)
int poly_get_adj_loops_from_vert (unsigned adj_r[3], const struct MPoly *poly, const struct MLoop *mloop, unsigned vert)
void mesh_flush_hidden_from_verts (const struct MVert *mvert, const struct MLoop *mloop, struct MEdge *medge, int totedge, struct MPoly *mpoly, int totpoly)
void unlink_mesh (struct Mesh *me)
void free_mesh (struct Mesh *me, int unlink)
struct Mesh * add_mesh (const char *name)
struct Mesh * copy_mesh (struct Mesh *me)
void mesh_update_customdata_pointers (struct Mesh *me, const short do_ensure_tess_cd)
void make_local_mesh (struct Mesh *me)
void boundbox_mesh (struct Mesh *me, float *loc, float *size)
void tex_space_mesh (struct Mesh *me)
float * get_mesh_orco_verts (struct Object *ob)
void transform_mesh_orco_verts (struct Mesh *me, float(*orco)[3], int totvert, int invert)
int test_index_face (struct MFace *mface, struct CustomData *mfdata, int mfindex, int nr)
struct Mesh * get_mesh (struct Object *ob)
void set_mesh (struct Object *ob, struct Mesh *me)
void mball_to_mesh (struct ListBase *lb, struct Mesh *me)
int nurbs_to_mdata (struct Object *ob, struct MVert **allvert, int *totvert, struct MEdge **alledge, int *totedge, struct MLoop **allloop, struct MPoly **allpoly, int *totloop, int *totpoly)
int nurbs_to_mdata_customdb (struct Object *ob, struct ListBase *dispbase, struct MVert **allvert, int *_totvert, struct MEdge **alledge, int *_totedge, struct MLoop **allloop, struct MPoly **allpoly, int *_totloop, int *_totpoly)
void nurbs_to_mesh (struct Object *ob)
void mesh_to_curve (struct Scene *scene, struct Object *ob)
void free_dverts (struct MDeformVert *dvert, int totvert)
void copy_dverts (struct MDeformVert *dst, struct MDeformVert *src, int totvert)
void mesh_delete_material_index (struct Mesh *me, short index)
void mesh_set_smooth_flag (struct Object *meshOb, int enableSmooth)
void BKE_mesh_convert_mfaces_to_mpolys (struct Mesh *mesh)
void mesh_calc_normals_tessface (struct MVert *mverts, int numVerts, struct MFace *mfaces, int numFaces, float(*faceNors_r)[3])
const char * mesh_cmp (struct Mesh *me1, struct Mesh *me2, float thresh)
struct BoundBox * mesh_get_bb (struct Object *ob)
void mesh_get_texspace (struct Mesh *me, float r_loc[3], float r_rot[3], float r_size[3])
void make_edges (struct Mesh *me, int old)
void mesh_strip_loose_faces (struct Mesh *me)
void mesh_strip_loose_polysloops (struct Mesh *me)
void mesh_strip_loose_edges (struct Mesh *me)
void mesh_calc_normals_mapping (struct MVert *mverts, int numVerts, struct MLoop *mloop, struct MPoly *mpolys, int numLoops, int numPolys, float(*polyNors_r)[3], struct MFace *mfaces, int numFaces, int *origIndexFace, float(*faceNors_r)[3])
void mesh_calc_normals_mapping_ex (struct MVert *mverts, int numVerts, struct MLoop *mloop, struct MPoly *mpolys, int numLoops, int numPolys, float(*polyNors_r)[3], struct MFace *mfaces, int numFaces, int *origIndexFace, float(*faceNors_r)[3], const short only_face_normals)
void mesh_calc_normals (struct MVert *mverts, int numVerts, struct MLoop *mloop, struct MPoly *mpolys, int numLoops, int numPolys, float(*polyNors_r)[3])
float(* mesh_getVertexCos (struct Mesh *me, int *numVerts_r))[3]
UvVertMap * make_uv_vert_map (struct MPoly *mpoly, struct MLoop *mloop, struct MLoopUV *mloopuv, unsigned int totpoly, unsigned int totvert, int selected, float *limit)
UvMapVert * get_uv_map_vert (UvVertMap *vmap, unsigned int v)
void free_uv_vert_map (UvVertMap *vmap)
void create_vert_poly_map (MeshElemMap **map, int **mem, const struct MPoly *mface, const struct MLoop *mloop, int totvert, int totface, int totloop)
void create_vert_edge_map (struct ListBase **map, IndexNode **mem, const struct MEdge *medge, const int totvert, const int totedge)
int minmax_mesh (struct Mesh *me, float min[3], float max[3])
int mesh_center_median (struct Mesh *me, float cent[3])
int mesh_center_bounds (struct Mesh *me, float cent[3])
void mesh_translate (struct Mesh *me, float offset[3], int do_keys)
int BKE_mesh_validate_arrays (struct Mesh *me, struct MVert *mverts, unsigned int totvert, struct MEdge *medges, unsigned int totedge, struct MLoop *mloops, unsigned int totloop, struct MPoly *mpolys, unsigned int totpoly, struct MDeformVert *dverts, const short do_verbose, const short do_fixes)
int BKE_mesh_validate (struct Mesh *me, int do_verbose)
int BKE_mesh_validate_dm (struct DerivedMesh *dm)
void BKE_mesh_calc_edges (struct Mesh *mesh, int update)
void BKE_mesh_ensure_navmesh (struct Mesh *me)
void BKE_mesh_tessface_calc (struct Mesh *mesh)
void BKE_mesh_tessface_ensure (struct Mesh *mesh)
void BKE_mesh_tessface_clear (struct Mesh *mesh)
void mesh_loops_to_mface_corners (struct CustomData *fdata, struct CustomData *ldata, struct CustomData *pdata, int lindex[4], int findex, const int polyindex, const int mf_len, const int numTex, const int numCol, const int hasPCol, const int hasOrigSpace)
Detailed Description
Definition in file BKE_mesh.h.
Define Documentation
#define INVALID_ISLAND 0xFFFF
Definition at line 247 of file BKE_mesh.h.
Referenced by EDBM_uv_element_map_create().
#define INVALID_LOOP_EDGE_MARKER 4294967295u
Definition at line 280 of file BKE_mesh.h.
Referenced by mesh_strip_loose_edges(), and mesh_strip_loose_polysloops().
#define STD_UV_CONNECT_LIMIT 0.0001f
Definition at line 194 of file BKE_mesh.h.
Referenced by EDBM_uv_element_map_create(), seams_from_islands_exec(), and ss_sync_from_uv().
Typedef Documentation
typedef struct IndexNode IndexNode
typedef struct MeshElemMap MeshElemMap
typedef struct UvElement UvElement
typedef struct UvElementMap UvElementMap
typedef struct UvMapVert UvMapVert
typedef struct UvVertMap UvVertMap
Function Documentation
struct Mesh* add_mesh (const char * name) [read]
Definition at line 479 of file mesh.c.
References alloc_libblock(), Mesh::bb, Mesh::drawflag, Mesh::flag, G, ID_ME, ME_AUTOSPACE, ME_DRAWCREASES, ME_DRAWEDGES, ME_DRAWFACES, ME_TWOSIDED, Mesh::size, Mesh::smoothresh, Mesh::texflag, and unit_boundbox().
Referenced by add_obdata_from_type(), AddNewBlenderMesh(), convert_exec(), nurbs_to_mesh(), and MeshImporter::write_geometry().
void BKE_mesh_calc_edges (struct Mesh * mesh, int update)
Definition at line 631 of file mesh_validate.c.
References BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), BLI_edgehash_size(), BLI_edgehashIterator_free(), BLI_edgehashIterator_getKey(), BLI_edgehashIterator_getValue(), BLI_edgehashIterator_isDone(), BLI_edgehashIterator_new(), BLI_edgehashIterator_setValue(), BLI_edgehashIterator_step(), CD_CALLOC, CD_MEDGE, CustomData_add_layer(), CustomData_free(), CustomData_get_layer(), MLoop::e, FALSE, MEdge::flag, GET_INT_FROM_POINTER, i, MPoly::loopstart, ME_EDGEDRAW, ME_EDGERENDER, Mesh::medge, Mesh::mloop, Mesh::mpoly, NULL, SELECT, SET_INT_IN_POINTER, Mesh::totedge, MPoly::totloop, Mesh::totpoly, MLoop::v, MEdge::v1, and MEdge::v2.
Referenced by BKE_mesh_validate_arrays(), ED_mesh_update(), mball_to_mesh(), and nurbs_to_mesh().
void BKE_mesh_convert_mfaces_to_mpolys (struct Mesh * mesh)
Definition at line 2023 of file mesh.c.
References BLI_edgehash_free(), BLI_edgehash_insert(), BLI_edgehash_new(), bm_corners_to_loops(), CD_ASSIGN, CD_MASK_MDISPS, CD_MCOL, CD_MLOOP, CD_MPOLY, CD_MTFACE, CustomData_add_layer(), CustomData_external_read(), CustomData_free(), CustomData_number_of_layers(), CustomData_to_bmeshpoly(), Mesh::fdata, MPoly::flag, MEdge::flag, i, Mesh::id, Mesh::ldata, MPoly::loopstart, MPoly::mat_nr, ME_FGON, Mesh::medge, MEM_callocN(), mesh_update_customdata_pointers(), Mesh::mface, ML, Mesh::mloop, Mesh::mpoly, NULL, SET_INT_IN_POINTER, Mesh::totedge, Mesh::totface, MPoly::totloop, Mesh::totloop, Mesh::totpoly, TRUE, MEdge::v1, MEdge::v2, and MFace::v4.
Referenced by ED_mesh_update(), EDBM_mesh_make(), lib_link_mesh(), and MeshImporter::write_geometry().
void BKE_mesh_ensure_navmesh (struct Mesh * me)
Definition at line 3132 of file mesh.c.
References CD_CALLOC, CD_RECAST, CD_REFERENCE, CustomData_add_layer_named(), CustomData_get_layer(), CustomData_has_layer(), i, NULL, and Mesh::totpoly.
Referenced by createRepresentation(), and navmesh_reset_exec().
void BKE_mesh_tessface_calc (struct Mesh * mesh)
Definition at line 3147 of file mesh.c.
References FALSE, Mesh::fdata, Mesh::ldata, mesh_recalcTessellation(), mesh_update_customdata_pointers(), Mesh::mvert, Mesh::totface, Mesh::totloop, Mesh::totpoly, and TRUE.
Referenced by BKE_mesh_tessface_ensure(), BM_mesh_bm_to_me(), DM_to_mesh(), ED_mesh_calc_tessface(), ED_mesh_update(), EDBM_mesh_load(), lib_link_mesh(), and make_vertexcol().
void BKE_mesh_tessface_clear (struct Mesh * mesh)
Definition at line 3165 of file mesh.c.
References mesh_tessface_clear_intern(), and TRUE.
Referenced by ED_mesh_update(), lib_link_mesh(), make_vertexcol(), mesh_ensure_tessellation_customdata(), and vpaint_fill().
void BKE_mesh_tessface_ensure (struct Mesh * mesh)
Definition at line 3158 of file mesh.c.
References BKE_mesh_tessface_calc(), Mesh::totface, and Mesh::totpoly.
Referenced by cdDM_getPBVH(), heat_bone_weighting(), GeometryExporter::operator()(), PE_mirror_x(), and sculpt_update_mesh_elements().
struct BMesh* BKE_mesh_to_bmesh (struct Mesh * me, struct Object * ob) [read]
Definition at line 556 of file mesh.c.
References bm_mesh_allocsize_default, BM_mesh_bm_from_me(), BM_mesh_create(), Object::shapenr, and TRUE.
Referenced by EDBM_mesh_make().
int BKE_mesh_validate (struct Mesh * me, int do_verbose)
Definition at line 596 of file mesh_validate.c.
References BKE_mesh_validate_all_customdata(), BKE_mesh_validate_arrays(), DAG_id_tag_update(), Mesh::dvert, FALSE, Mesh::id, Mesh::ldata, Mesh::medge, Mesh::mloop, Mesh::mpoly, Mesh::mvert, ID::name, OB_RECALC_DATA, Mesh::totedge, Mesh::totloop, Mesh::totpoly, Mesh::totvert, and TRUE.
int BKE_mesh_validate_arrays (struct Mesh * me, struct MVert * mverts, unsigned int totvert, struct MEdge * medges, unsigned int totedge, struct MLoop * mloops, unsigned int totloop, struct MPoly * mpolys, unsigned int totpoly, struct MDeformVert * dverts, const short do_verbose, const short do_fixes)
Definition at line 98 of file mesh_validate.c.
References BKE_mesh_calc_edges(), BLI_assert, BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_lookup(), BLI_edgehash_new(), CLAMP(), MVert::co, MDeformWeight::def_nr, defvert_remove_group(), MDeformVert::dw, MLoop::e, FALSE, MVert::flag, GET_INT_FROM_POINTER, i, if(), SortPoly::index, int_cmp(), SortPoly::invalid, IS_REMOVED_EDGE, SortPoly::loopstart, ME_VERT_TMP_TAG, MEM_callocN(), MEM_freeN(), MEM_mallocN(), mesh_strip_loose_edges(), mesh_strip_loose_polysloops(), MVert::no, NULL, SortPoly::numverts, PRINT, REMOVE_EDGE_TAG, REMOVE_LOOP_TAG, REMOVE_POLY_TAG, search_poly_cmp(), search_polyloop_cmp(), SET_INT_IN_POINTER, TRUE, MLoop::v, MEdge::v1, MEdge::v2, SortPoly::verts, MDeformWeight::weight, and zero_v3().
Referenced by BKE_mesh_validate(), and BKE_mesh_validate_dm().
int BKE_mesh_validate_dm (struct DerivedMesh * dm)
Definition at line 620 of file mesh_validate.c.
References BKE_mesh_validate_arrays(), CD_MDEFORMVERT, FALSE, DerivedMesh::getEdgeArray, DerivedMesh::getLoopArray, DerivedMesh::getNumEdges, DerivedMesh::getNumLoops, DerivedMesh::getNumPolys, DerivedMesh::getNumVerts, DerivedMesh::getPolyArray, DerivedMesh::getVertArray, DerivedMesh::getVertDataArray, NULL, and TRUE.
void boundbox_mesh (struct Mesh * me, float * loc, float * size)
Definition at line 653 of file mesh.c.
References Mesh::bb, boundbox_set_from_min_max(), INIT_MINMAX, max, MEM_callocN(), mid_v3_v3v3(), min, minmax_mesh(), and NULL.
Referenced by tex_space_mesh().
void copy_dverts (struct MDeformVert * dst, struct MDeformVert * src, int totvert)
Definition at line 430 of file mesh.c.
References MDeformVert::dw, i, and MEM_callocN().
Referenced by copy_lattice(), copy_wpaint_prev(), load_editLatt(), and make_editLatt().
struct Mesh* copy_mesh (struct Mesh * me) [read]
Definition at line 495 of file mesh.c.
References Mesh::bb, CD_DUPLICATE, CD_MASK_MESH, CD_MTEXPOLY, CD_MTFACE, copy_key(), copy_libblock(), CustomData_copy(), CustomDataLayer::data, Mesh::edit_btmesh, FALSE, Mesh::fdata, Key::from, i, Mesh::id, id_lib_extern(), id_us_plus(), Mesh::key, CustomData::layers, Mesh::ldata, Mesh::mat, MEM_dupallocN(), mesh_tessface_clear_intern(), mesh_update_customdata_pointers(), Mesh::mselect, NULL, Mesh::texcomesh, Mesh::totcol, Mesh::totedge, Mesh::totface, CustomData::totlayer, Mesh::totloop, Mesh::totpoly, Mesh::totvert, MTexPoly::tpage, MTFace::tpage, and CustomDataLayer::type.
Referenced by bmo_dupe_exec(), convert_exec(), KX_BlenderSceneConverter::ConvertMeshSpecial(), id_copy(), make_local_mesh(), object_add_duplicate_internal(), and single_obdata_users().
void create_vert_edge_map (struct ListBase ** map, IndexNode ** mem, const struct MEdge * medge, const int totvert, const int totedge)
void create_vert_poly_map (MeshElemMap ** map, int ** mem, const struct MPoly * mface, const struct MLoop * mloop, int totvert, int totface, int totloop)
Referenced by ccgDM_getPolyMap(), and cdDM_getPolyMap().
void free_dverts (struct MDeformVert * dvert, int totvert)
Definition at line 449 of file mesh.c.
References i, and MEM_freeN().
Referenced by copy_wpaint_prev(), free_editLatt(), free_lattice(), load_editLatt(), and resizelattice().
void free_mesh (struct Mesh * me, int unlink)
Definition at line 407 of file mesh.c.
References Mesh::adt, Mesh::bb, BKE_free_animdata(), CustomData_free(), Mesh::edit_btmesh, Mesh::fdata, Mesh::id, Mesh::ldata, Mesh::mat, MEM_freeN(), Mesh::mselect, NULL, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totvert, and unlink_mesh().
Referenced by free_libblock(), and free_undo().
void free_uv_vert_map (UvVertMap * vmap)
Definition at line 2223 of file mesh.c.
References UvVertMap::buf, MEM_freeN(), and UvVertMap::vert.
Referenced by EDBM_uv_vert_map_create(), make_uv_vert_map(), and ss_sync_from_uv().
struct Mesh* get_mesh (struct Object * ob) [read]
Definition at line 841 of file mesh.c.
References Object::data, NULL, OB_MESH, and Object::type.
Referenced by do_paintface_box_select(), image_paint_sample_color_poll(), make_vertexcol(), minmax_object(), multires_force_external_reload(), multiresModifier_base_apply(), multiresModifier_del_levels(), paintface_deselect_all_visible(), paintface_flush_flags(), paintface_hide(), paintface_minmax(), paintface_mouse_select(), paintface_reveal(), paintface_select_linked(), paintvert_deselect_all_visible(), paintvert_flush_flags(), sculpt_update_mesh_elements(), set_vpaint(), set_wpaint(), texture_paint_init(), texture_paint_toggle_exec(), vertex_paint_use_fast_update_check(), vertex_paint_use_tessface_check(), vpaint_fill(), vpaint_paint_poly(), vpaint_stroke_test_start(), weight_paint_sample_enum_itemf(), weight_sample_invoke(), and wpaint_stroke_test_start().
float* get_mesh_orco_verts (struct Object * ob)
Definition at line 724 of file mesh.c.
References MVert::co, copy_v3_v3(), Object::data, MEM_callocN(), MIN2, Mesh::mvert, NULL, Mesh::texcomesh, and Mesh::totvert.
Referenced by distribute_threads_init_data(), face_duplilist(), get_dm(), get_orco_coords_dm(), and vertex_duplilist().
UvMapVert* get_uv_map_vert (UvVertMap * vmap, unsigned int v)
Definition at line 2218 of file mesh.c.
References UvVertMap::vert.
Referenced by get_face_uv_map_vert(), and ss_sync_from_uv().
void make_edges (struct Mesh * me, int old)
Definition at line 1010 of file mesh.c.
References CD_ASSIGN, CD_MEDGE, CustomData_add_layer(), make_edges_mdata(), Mesh::medge, mesh_strip_loose_faces(), Mesh::mface, Mesh::mloop, Mesh::mpoly, Mesh::mvert, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, and Mesh::totvert.
Referenced by do_versions(), and MeshImporter::write_geometry().
void make_local_mesh (struct Mesh * me)
Definition at line 606 of file mesh.c.
References BKE_id_lib_local_paths(), copy_mesh(), Object::data, ELEM, expand_local_mesh(), FALSE, ListBase::first, G, Mesh::id, Object::id, id_clear_lib_data(), ID::lib, ID::next, NULL, Main::object, set_mesh(), TRUE, and ID::us.
Referenced by id_make_local().
UvVertMap* make_uv_vert_map (struct MPoly * mpoly, struct MLoop * mloop, struct MLoopUV * mloopuv, unsigned int totpoly, unsigned int totvert, int selected, float * limit)
Definition at line 2127 of file mesh.c.
References UvVertMap::buf, UvMapVert::f, fabsf, MPoly::flag, free_uv_vert_map(), i, MPoly::loopstart, ME_FACE_SEL, ME_HIDE, MEM_callocN(), next, UvMapVert::next, NULL, UvMapVert::separate, sub_v2_v2v2(), UvMapVert::tfindex, MPoly::totloop, MLoopUV::uv, MLoop::v, and UvVertMap::vert.
Referenced by ss_sync_from_uv().
void mball_to_mesh (struct ListBase * lb, struct Mesh * me)
Definition at line 1161 of file mesh.c.
References BKE_mesh_calc_edges(), CD_CALLOC, CD_MLOOP, CD_MPOLY, CD_MVERT, MVert::co, copy_v3_v3(), CustomData_add_layer(), DL_INDEX4, ListBase::first, MPoly::flag, DispList::index, Mesh::ldata, MPoly::loopstart, ME_SMOOTH, mesh_calc_normals(), mesh_update_customdata_pointers(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, MVert::no, normal_float_to_short_v3(), DispList::nors, DispList::nr, NULL, DispList::parts, Mesh::totloop, MPoly::totloop, Mesh::totpoly, Mesh::totvert, TRUE, DispList::type, MLoop::v, and DispList::verts.
Referenced by convert_exec().
void mesh_calc_normals (struct MVert * mverts, int numVerts, struct MLoop * mloop, struct MPoly * mpolys, int numLoops, int numPolys, float(*) polyNors_r[3])
Referenced by CDDM_calc_normals(), ED_mesh_calc_normals(), ED_mesh_update(), mball_to_mesh(), mesh_calc_normals_mapping_ex(), nurbs_to_mesh(), and sculpt_flush_stroke_deform().
void mesh_calc_normals_mapping (struct MVert * mverts, int numVerts, struct MLoop * mloop, struct MPoly * mpolys, int numLoops, int numPolys, float(*) polyNors_r[3], struct MFace * mfaces, int numFaces, int * origIndexFace, float(*) faceNors_r[3])
Definition at line 1772 of file mesh.c.
References mesh_calc_normals_mapping_ex(), and TRUE.
Referenced by apply_objects_internal(), sculpt_vertcos_to_key(), and MeshImporter::write_geometry().
void mesh_calc_normals_mapping_ex (struct MVert * mverts, int numVerts, struct MLoop * mloop, struct MPoly * mpolys, int numLoops, int numPolys, float(*) polyNors_r[3], struct MFace * mfaces, int numFaces, int * origIndexFace, float(*) faceNors_r[3], const short only_face_normals)
Definition at line 1781 of file mesh.c.
References copy_v3_v3(), FALSE, i, MPoly::loopstart, MEM_callocN(), MEM_freeN(), mesh_calc_normals(), mesh_calc_poly_normal(), NULL, and TRUE.
Referenced by CDDM_calc_normals_mapping_ex(), ED_mesh_calc_normals(), ED_mesh_update(), and mesh_calc_normals_mapping().
void mesh_calc_normals_tessface (struct MVert * mverts, int numVerts, struct MFace * mfaces, int numFaces, float(*) faceNors_r[3])
Definition at line 1905 of file mesh.c.
References accumulate_vertex_normals(), MVert::co, i, MEM_callocN(), MEM_freeN(), MVert::no, normal_float_to_short_v3(), normal_quad_v3(), normal_tri_v3(), normalize_v3(), normalize_v3_v3(), NULL, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by BLI_pbvh_apply_vertCos(), CDDM_calc_normals_tessface(), do_versions(), and sculpt_undo_restore().
float mesh_calc_poly_area (struct MPoly * mpoly, struct MLoop * loopstart, struct MVert * mvarray, float polynormal[3])
Definition at line 2967 of file mesh.c.
References area_poly_v3(), area_quad_v3(), area_tri_v3(), BLI_array_fixedstack_declare, BLI_array_fixedstack_free, BM_NGON_STACK_SIZE, MVert::co, co, copy_v3_v3(), i, mesh_calc_poly_normal(), NULL, MPoly::totloop, and MLoop::v.
Referenced by face_duplilist().
void mesh_calc_poly_center (struct MPoly * mpoly, struct MLoop * loopstart, struct MVert * mvarray, float cent[3])
Definition at line 2943 of file mesh.c.
References cent_quad_v3(), cent_tri_v3(), co, mesh_calc_ngon_center(), and MPoly::totloop.
Referenced by face_duplilist().
void mesh_calc_poly_normal (struct MPoly * mpoly, struct MLoop * loopstart, struct MVert * mvarray, float no[3])
Definition at line 2821 of file mesh.c.
References co, mesh_calc_ngon_normal(), normal_quad_v3(), normal_tri_v3(), and MPoly::totloop.
Referenced by applyModifier(), dm_calc_normal(), mesh_calc_normals(), mesh_calc_normals_mapping_ex(), and mesh_calc_poly_area().
void mesh_calc_poly_normal_coords (struct MPoly * mpoly, struct MLoop * loopstart, const float(*) vertex_coords[3], float no[3])
Definition at line 2902 of file mesh.c.
References mesh_calc_ngon_normal_coords(), normal_quad_v3(), normal_tri_v3(), and MPoly::totloop.
Referenced by multiresModifier_base_apply(), and uvprojectModifier_do().
int mesh_center_bounds (struct Mesh * me, float cent[3])
Definition at line 3100 of file mesh.c.
References INIT_MINMAX, max, mid_v3_v3v3(), min, and minmax_mesh().
Referenced by object_origin_set_exec().
int mesh_center_median (struct Mesh * me, float cent[3])
Definition at line 3084 of file mesh.c.
References add_v3_v3(), MVert::co, mul_v3_fl(), Mesh::mvert, Mesh::totvert, and zero_v3().
Referenced by object_origin_set_exec().
const char* mesh_cmp (struct Mesh * me1, struct Mesh * me2, float thresh)
Definition at line 272 of file mesh.c.
References cmpcode_to_str(), customdata_compare(), Mesh::ldata, NULL, Mesh::totedge, Mesh::totloop, Mesh::totpoly, and Mesh::totvert.
void mesh_delete_material_index (struct Mesh * me, short index)
Definition at line 1727 of file mesh.c.
References i, MFace::mat_nr, MPoly::mat_nr, Mesh::mface, Mesh::mpoly, Mesh::totface, and Mesh::totpoly.
Referenced by data_delete_material_index_id().
void mesh_flush_hidden_from_verts (const struct MVert * mvert, const struct MLoop * mloop, struct MEdge * medge, int totedge, struct MPoly * mpoly, int totpoly)
Referenced by applyModifier(), and hide_show_exec().
struct BoundBox* mesh_get_bb (struct Object * ob) [read]
Definition at line 700 of file mesh.c.
References Mesh::bb, Object::bb, Object::data, and tex_space_mesh().
Referenced by draw_bounding_volume(), minmax_object(), and object_get_boundbox().
void mesh_get_texspace (struct Mesh * me, float r_loc[3], float r_rot[3], float r_size[3])
Definition at line 713 of file mesh.c.
References Mesh::bb, copy_v3_v3(), Mesh::loc, Mesh::rot, Mesh::size, and tex_space_mesh().
Referenced by calc_edge_stress(), drawtexspace(), image_aspect(), psys_render_simplify_distribution(), and transform_mesh_orco_verts().
float(* mesh_getVertexCos (struct Mesh * me, int * numVerts_r))[3]
Definition at line 2110 of file mesh.c.
References MVert::co, copy_v3_v3(), cos(), i, MEM_mallocN(), Mesh::mvert, and Mesh::totvert.
Referenced by crazyspace_build_sculpt(), mesh_calc_modifiers(), mesh_create_derived_for_modifier(), sculpt_get_first_deform_matrices(), and sculpt_update_mesh_elements().
void mesh_loops_to_mface_corners (struct CustomData * fdata, struct CustomData * ldata, struct CustomData * pdata, int lindex[4], int findex, const int polyindex, const int mf_len, const int numTex, const int numCol, const int hasPCol, const int hasOrigSpace)
Definition at line 2297 of file mesh.c.
References CD_MCOL, CD_MLOOPCOL, CD_MLOOPUV, CD_MTEXPOLY, CD_MTFACE, CD_ORIGSPACE, CD_ORIGSPACE_MLOOP, CD_PREVIEW_MCOL, CD_PREVIEW_MLOOPCOL, copy_v2_v2(), CustomData_get(), CustomData_get_n(), i, ME_MTEXFACE_CPY, MESH_MLOOPCOL_TO_MCOL, MTFace::uv, MLoopUV::uv, OrigSpaceLoop::uv, and OrigSpaceFace::uv.
Referenced by DM_update_tessface_data(), and mesh_recalcTessellation().
int mesh_mpoly_to_mface (struct CustomData * fdata, struct CustomData * ldata, struct CustomData * pdata, int totface, int totloop, int totpoly)
Referenced by direct_link_mesh(), and write_meshs().
int mesh_recalcTessellation (struct CustomData * fdata, struct CustomData * ldata, struct CustomData * pdata, struct MVert * mvert, int totface, int totloop, int totpoly, const int do_face_normals)
Referenced by BKE_mesh_tessface_calc(), and CDDM_recalc_tessellation_ex().
void mesh_set_smooth_flag (struct Object * meshOb, int enableSmooth)
Definition at line 1744 of file mesh.c.
References Object::data, MFace::flag, MPoly::flag, i, ME_SMOOTH, Mesh::mface, Mesh::mpoly, Mesh::totface, and Mesh::totpoly.
Referenced by shade_smooth_exec().
void mesh_strip_loose_edges (struct Mesh * me)
Definition at line 1126 of file mesh.c.
References CustomData_copy_data(), CustomData_free_elem(), MLoop::e, INVALID_LOOP_EDGE_MARKER, Mesh::medge, MEM_freeN(), MEM_mallocN(), Mesh::mloop, Mesh::totedge, MEdge::v1, and MEdge::v2.
Referenced by BKE_mesh_validate_arrays().
void mesh_strip_loose_faces (struct Mesh * me)
Definition at line 1031 of file mesh.c.
References CustomData_copy_data(), CustomData_free_elem(), edgesort::f, Mesh::fdata, Mesh::mface, Mesh::totface, and MFace::v3.
Referenced by do_versions(), and make_edges().
void mesh_strip_loose_polysloops (struct Mesh * me)
Definition at line 1055 of file mesh.c.
References CustomData_copy_data(), CustomData_free_elem(), MLoop::e, FALSE, i, INVALID_LOOP_EDGE_MARKER, Mesh::ldata, MPoly::loopstart, MEM_freeN(), MEM_mallocN(), Mesh::mloop, Mesh::mpoly, p, Mesh::totloop, MPoly::totloop, Mesh::totpoly, and TRUE.
Referenced by BKE_mesh_validate_arrays().
void mesh_to_curve (struct Scene * scene, struct Object * ob)
Definition at line 1555 of file mesh.c.
References add_curve(), appendPolyLineVert(), Object::bb, BLI_addtail(), BLI_edgehash_free(), BLI_edgehash_haskey(), BLI_edgehash_insert(), BLI_edgehash_new(), BLI_findlink(), BLI_freelinkN(), BLI_freelistN(), Nurb::bp, CD_MASK_MESH, MVert::co, copy_v3_v3(), CU_3D, CU_NURB_CYCLIC, CU_NURB_ENDPOINT, Object::data, Object::derivedFinal, EdgeLink::edge, BPoint::f1, FALSE, ListBase::first, Curve::flag, Nurb::flagu, DerivedMesh::getEdgeArray, DerivedMesh::getNumEdges, DerivedMesh::getNumTessFaces, DerivedMesh::getTessFaceArray, DerivedMesh::getVertArray, i, Object::id, VertLink::index, ListBase::last, MEM_callocN(), MEM_freeN(), mesh_get_derived_final(), ID::name, DerivedMesh::needsFree, VertLink::next, NULL, Curve::nurb, OB_CURVE, Nurb::orderu, Nurb::pntsu, Nurb::pntsv, prependPolyLineVert(), BPoint::radius, DerivedMesh::release, Nurb::resolu, SELECT, TRUE, Object::type, MEdge::v1, MFace::v1, MEdge::v2, MFace::v2, MFace::v3, MFace::v4, BPoint::vec, and BPoint::weight.
Referenced by convert_exec().
void mesh_translate (struct Mesh * me, float offset[3], int do_keys)
Definition at line 3112 of file mesh.c.
References add_v3_v3(), Key::block, MVert::co, KeyBlock::data, ListBase::first, Mesh::key, Mesh::mvert, KeyBlock::next, KeyBlock::totelem, and Mesh::totvert.
Referenced by object_origin_set_exec().
void mesh_update_customdata_pointers (struct Mesh * me, const short do_ensure_tess_cd)
Definition at line 360 of file mesh.c.
References CD_MCOL, CD_MDEFORMVERT, CD_MEDGE, CD_MFACE, CD_MLOOP, CD_MLOOPCOL, CD_MLOOPUV, CD_MPOLY, CD_MSTICKY, CD_MTEXPOLY, CD_MTFACE, CD_MVERT, CustomData_get_layer(), Mesh::dvert, Mesh::fdata, Mesh::ldata, Mesh::mcol, Mesh::medge, mesh_update_linked_customdata(), Mesh::mface, Mesh::mloop, Mesh::mloopcol, Mesh::mloopuv, Mesh::mpoly, Mesh::msticky, Mesh::mtface, Mesh::mtpoly, and Mesh::mvert.
Referenced by BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_tessface_calc(), BM_mesh_bm_to_me(), copy_mesh(), customdata_version_242(), delete_customdata_layer(), direct_link_mesh(), DM_to_mesh(), ED_mesh_color_add(), ED_mesh_uv_texture_add(), join_mesh_exec(), make_vertexcol(), mball_to_mesh(), mesh_add_edges(), mesh_add_loops(), mesh_add_polys(), mesh_add_tessfaces(), mesh_add_verts(), and write_meshs().
int minmax_mesh (struct Mesh * me, float min[3], float max[3])
Definition at line 3073 of file mesh.c.
References MVert::co, DO_MINMAX, Mesh::mvert, and Mesh::totvert.
Referenced by boundbox_mesh(), and mesh_center_bounds().
int nurbs_to_mdata (struct Object * ob, struct MVert ** allvert, int * totvert, struct MEdge ** alledge, int * totedge, struct MLoop ** allloop, struct MPoly ** allpoly, int * totloop, int * totpoly)
Definition at line 1226 of file mesh.c.
References Object::disp, and nurbs_to_mdata_customdb().
Referenced by nurbs_to_mesh().
int nurbs_to_mdata_customdb (struct Object * ob, struct ListBase * dispbase, struct MVert ** allvert, int * _totvert, struct MEdge ** alledge, int * _totedge, struct MLoop ** allloop, struct MPoly ** allpoly, int * _totloop, int * _totpoly)
Definition at line 1242 of file mesh.c.
References MVert::co, DispList::col, copy_v3_v3(), CU_3D, CU_SMOOTH, Object::data, data, DL_CYCL_U, DL_CYCL_V, DL_INDEX3, DL_POLY, DL_SEGM, DL_SURF, ListBase::first, Curve::flag, MEdge::flag, DispList::flag, MPoly::flag, DispList::index, MPoly::loopstart, make_edges_mdata(), MPoly::mat_nr, ME_EDGEDRAW, ME_EDGERENDER, ME_LOOSEEDGE, ME_SMOOTH, MEM_callocN(), DispList::next, DispList::nr, OB_SURF, DispList::parts, DispList::rt, smooth(), MPoly::totloop, DispList::type, Object::type, MLoop::v, MEdge::v1, MEdge::v2, and DispList::verts.
Referenced by CDDM_from_curve_customDB(), and nurbs_to_mdata().
void nurbs_to_mesh (struct Object * ob)
Definition at line 1462 of file mesh.c.
References add_mesh(), BKE_mesh_calc_edges(), CD_ASSIGN, CD_MEDGE, CD_MLOOP, CD_MPOLY, CD_MVERT, Main::curve, CustomData_add_layer(), Object::data, Object::derivedFinal, DM_to_mesh(), ListBase::first, free_libblock(), G, Object::id, id_us_plus(), Mesh::ldata, Curve::mat, Mesh::mat, Mesh::medge, mesh_calc_normals(), Mesh::mloop, Mesh::mpoly, Mesh::mvert, ID::next, NULL, nurbs_to_mdata(), OB_MESH, Main::object, tex_space_mesh(), Curve::totcol, Mesh::totcol, Mesh::totedge, Mesh::totloop, Mesh::totpoly, Mesh::totvert, TRUE, and Object::type.
Referenced by curvetomesh().
int poly_find_loop_from_vert (const struct MPoly * poly, const struct MLoop * loopstart, unsigned vert)
Referenced by poly_get_adj_loops_from_vert().
int poly_get_adj_loops_from_vert (unsigned adj_r[3], const struct MPoly * poly, const struct MLoop * mloop, unsigned vert)
Referenced by neighbor_average().
void set_mesh (struct Object * ob, struct Mesh * me)
Definition at line 849 of file mesh.c.
References Object::data, Mesh::id, id_us_plus(), multires_force_update(), NULL, OB_MESH, test_object_materials(), test_object_modifiers(), Object::type, and ID::us.
Referenced by MeshImporter::create_mesh_object(), and make_local_mesh().
int test_index_face (struct MFace * mface, struct CustomData * mfdata, int mfindex, int nr)
Definition at line 769 of file mesh.c.
References CustomData_swap(), SWAP, MFace::v1, MFace::v2, MFace::v3, and MFace::v4.
Referenced by CDDM_from_BMEditMesh(), ConvertCSGDescriptorsToDerivedMesh(), cutEdges(), emDM_copyTessFaceArray(), emDM_getTessFace(), explodeMesh(), and mesh_recalcTessellation().
void tex_space_mesh (struct Mesh * me)
Definition at line 680 of file mesh.c.
References boundbox_mesh(), copy_v3_v3(), Mesh::loc, ME_AUTOSPACE, Mesh::rot, Mesh::size, size(), Mesh::texflag, and zero_v3().
Referenced by mesh_get_bb(), mesh_get_texspace(), and nurbs_to_mesh().
void transform_mesh_orco_verts (struct Mesh * me, float(*) orco[3], int totvert, int invert)
Definition at line 744 of file mesh.c.
References co, madd_v3_v3v3v3(), mesh_get_texspace(), NULL, size(), and Mesh::texcomesh.
Referenced by add_orco_dm(), distribute_threads_exec(), distribute_threads_init_data(), face_duplilist(), psys_face_mat(), psys_mat_hair_to_orco(), and vertex_duplilist().
void unlink_mesh (struct Mesh * me)
Definition at line 387 of file mesh.c.
References Key::id, Material::id, Mesh::key, Mesh::mat, NULL, Mesh::texcomesh, Mesh::totcol, and ID::us.
Referenced by free_mesh(), and free_object().