Blender: armature_intern.h File Reference
armature_intern.h File Reference
armature
Classes
struct tPChanFCurveLink
Typedefs
typedef struct tPChanFCurveLink tPChanFCurveLink
Functions
void ARMATURE_OT_bone_primitive_add (struct wmOperatorType *ot)
void ARMATURE_OT_align (struct wmOperatorType *ot)
void ARMATURE_OT_calculate_roll (struct wmOperatorType *ot)
void ARMATURE_OT_switch_direction (struct wmOperatorType *ot)
void ARMATURE_OT_subdivide (struct wmOperatorType *ot)
void ARMATURE_OT_parent_set (struct wmOperatorType *ot)
void ARMATURE_OT_parent_clear (struct wmOperatorType *ot)
void ARMATURE_OT_select_all (struct wmOperatorType *ot)
void ARMATURE_OT_select_inverse (struct wmOperatorType *ot)
void ARMATURE_OT_select_hierarchy (struct wmOperatorType *ot)
void ARMATURE_OT_select_linked (struct wmOperatorType *ot)
void ARMATURE_OT_delete (struct wmOperatorType *ot)
void ARMATURE_OT_duplicate (struct wmOperatorType *ot)
void ARMATURE_OT_extrude (struct wmOperatorType *ot)
void ARMATURE_OT_hide (struct wmOperatorType *ot)
void ARMATURE_OT_reveal (struct wmOperatorType *ot)
void ARMATURE_OT_click_extrude (struct wmOperatorType *ot)
void ARMATURE_OT_fill (struct wmOperatorType *ot)
void ARMATURE_OT_merge (struct wmOperatorType *ot)
void ARMATURE_OT_separate (struct wmOperatorType *ot)
void ARMATURE_OT_autoside_names (struct wmOperatorType *ot)
void ARMATURE_OT_flip_names (struct wmOperatorType *ot)
void ARMATURE_OT_layers_show_all (struct wmOperatorType *ot)
void ARMATURE_OT_armature_layers (struct wmOperatorType *ot)
void ARMATURE_OT_bone_layers (struct wmOperatorType *ot)
void POSE_OT_hide (struct wmOperatorType *ot)
void POSE_OT_reveal (struct wmOperatorType *ot)
void POSE_OT_armature_apply (struct wmOperatorType *ot)
void POSE_OT_visual_transform_apply (struct wmOperatorType *ot)
void POSE_OT_rot_clear (struct wmOperatorType *ot)
void POSE_OT_loc_clear (struct wmOperatorType *ot)
void POSE_OT_scale_clear (struct wmOperatorType *ot)
void POSE_OT_transforms_clear (struct wmOperatorType *ot)
void POSE_OT_user_transforms_clear (struct wmOperatorType *ot)
void POSE_OT_copy (struct wmOperatorType *ot)
void POSE_OT_paste (struct wmOperatorType *ot)
void POSE_OT_select_all (struct wmOperatorType *ot)
void POSE_OT_select_parent (struct wmOperatorType *ot)
void POSE_OT_select_hierarchy (struct wmOperatorType *ot)
void POSE_OT_select_linked (struct wmOperatorType *ot)
void POSE_OT_select_constraint_target (struct wmOperatorType *ot)
void POSE_OT_select_grouped (struct wmOperatorType *ot)
void POSE_OT_select_flip_active (struct wmOperatorType *ot)
void POSE_OT_group_add (struct wmOperatorType *ot)
void POSE_OT_group_remove (struct wmOperatorType *ot)
void POSE_OT_group_move (struct wmOperatorType *ot)
void POSE_OT_group_sort (struct wmOperatorType *ot)
void POSE_OT_group_assign (struct wmOperatorType *ot)
void POSE_OT_group_unassign (struct wmOperatorType *ot)
void POSE_OT_group_select (struct wmOperatorType *ot)
void POSE_OT_group_deselect (struct wmOperatorType *ot)
void POSE_OT_paths_calculate (struct wmOperatorType *ot)
void POSE_OT_paths_clear (struct wmOperatorType *ot)
void POSE_OT_autoside_names (struct wmOperatorType *ot)
void POSE_OT_flip_names (struct wmOperatorType *ot)
void POSE_OT_rotation_mode_set (struct wmOperatorType *ot)
void POSE_OT_quaternions_flip (struct wmOperatorType *ot)
void POSE_OT_armature_layers (struct wmOperatorType *ot)
void POSE_OT_bone_layers (struct wmOperatorType *ot)
void SKETCH_OT_gesture (struct wmOperatorType *ot)
void SKETCH_OT_delete (struct wmOperatorType *ot)
void SKETCH_OT_draw_stroke (struct wmOperatorType *ot)
void SKETCH_OT_draw_preview (struct wmOperatorType *ot)
void SKETCH_OT_finish_stroke (struct wmOperatorType *ot)
void SKETCH_OT_cancel_stroke (struct wmOperatorType *ot)
void SKETCH_OT_convert (struct wmOperatorType *ot)
void SKETCH_OT_select (struct wmOperatorType *ot)
void poseAnim_mapping_get (struct bContext *C, ListBase *pfLinks, struct Object *ob, struct bAction *act)
void poseAnim_mapping_free (ListBase *pfLinks)
void poseAnim_mapping_refresh (struct bContext *C, struct Scene *scene, struct Object *ob)
void poseAnim_mapping_reset (ListBase *pfLinks)
void poseAnim_mapping_autoKeyframe (struct bContext *C, struct Scene *scene, struct Object *ob, ListBase *pfLinks, float cframe)
LinkData * poseAnim_mapping_getNextFCurve (ListBase *fcuLinks, LinkData *prev, const char *path)
void POSELIB_OT_new (struct wmOperatorType *ot)
void POSELIB_OT_unlink (struct wmOperatorType *ot)
void POSELIB_OT_action_sanitise (struct wmOperatorType *ot)
void POSELIB_OT_pose_add (struct wmOperatorType *ot)
void POSELIB_OT_pose_remove (struct wmOperatorType *ot)
void POSELIB_OT_pose_rename (struct wmOperatorType *ot)
void POSELIB_OT_browse_interactive (struct wmOperatorType *ot)
void POSELIB_OT_apply_pose (struct wmOperatorType *ot)
void POSE_OT_push (struct wmOperatorType *ot)
void POSE_OT_relax (struct wmOperatorType *ot)
void POSE_OT_breakdown (struct wmOperatorType *ot)
void POSE_OT_propagate (struct wmOperatorType *ot)
EditBone * make_boneList (struct ListBase *edbo, struct ListBase *bones, struct EditBone *parent, struct Bone *actBone)
void BIF_sk_selectStroke (struct bContext *C, const int mval[2], short extend)
void preEditBoneDuplicate (struct ListBase *editbones)
struct EditBone * duplicateEditBone (struct EditBone *curBone, const char *name, struct ListBase *editbones, struct Object *ob)
void updateDuplicateSubtarget (struct EditBone *dupBone, struct ListBase *editbones, struct Object *ob)
struct EditBone * duplicateEditBoneObjects (struct EditBone *curBone, const char *name, struct ListBase *editbones, struct Object *src_ob, struct Object *dst_ob)
void updateDuplicateSubtargetObjects (struct EditBone *dupBone, struct ListBase *editbones, struct Object *src_ob, struct Object *dst_ob)
Detailed Description
Definition in file armature_intern.h.
Typedef Documentation
typedef struct tPChanFCurveLink tPChanFCurveLink
Function Documentation
void ARMATURE_OT_align (struct wmOperatorType * ot)
Definition at line 4237 of file editarmature.c.
References armature_align_bones_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_armature_layers (struct wmOperatorType * ot)
Definition at line 2022 of file poseobject.c.
References wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_armature_layers_exec(), pose_armature_layers_invoke(), RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_autoside_names (struct wmOperatorType * ot)
Definition at line 5501 of file editarmature.c.
References armature_autoside_names_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_bone_layers (struct wmOperatorType * ot)
Definition at line 2169 of file poseobject.c.
References armature_bone_layers_exec(), armature_bone_layers_invoke(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_bone_primitive_add (struct wmOperatorType * ot)
Definition at line 3495 of file editarmature.c.
References armature_bone_primitive_add_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, MAXBONENAME, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_calculate_roll (struct wmOperatorType * ot)
Definition at line 2101 of file editarmature.c.
References armature_calc_roll_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_click_extrude (struct wmOperatorType * ot)
Definition at line 2408 of file editarmature.c.
References armature_click_extrude_exec(), armature_click_extrude_invoke(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_delete (struct wmOperatorType * ot)
Definition at line 1746 of file editarmature.c.
References armature_delete_selected_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_confirm().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_duplicate (struct wmOperatorType * ot)
Definition at line 2676 of file editarmature.c.
References armature_duplicate_selected_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_extrude (struct wmOperatorType * ot)
Definition at line 3432 of file editarmature.c.
References armature_extrude_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_fill (struct wmOperatorType * ot)
Definition at line 2950 of file editarmature.c.
References armature_fill_bones_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_flip_names (struct wmOperatorType * ot)
Definition at line 5455 of file editarmature.c.
References armature_flip_names_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_hide (struct wmOperatorType * ot)
Definition at line 3183 of file editarmature.c.
References armature_hide_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_layers_show_all (struct wmOperatorType * ot)
Definition at line 1937 of file poseobject.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_armature_layers_showall_exec(), pose_armature_layers_showall_poll(), wmOperatorType::prop, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_merge (struct wmOperatorType * ot)
Definition at line 3129 of file editarmature.c.
References armature_merge_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_parent_clear (struct wmOperatorType * ot)
Definition at line 3920 of file editarmature.c.
References armature_parent_clear_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_parent_set (struct wmOperatorType * ot)
Definition at line 3866 of file editarmature.c.
References armature_parent_set_exec(), armature_parent_set_invoke(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_reveal (struct wmOperatorType * ot)
Definition at line 3223 of file editarmature.c.
References armature_reveal_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_all (struct wmOperatorType * ot)
Definition at line 4017 of file editarmature.c.
References armature_de_select_all_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and WM_operator_properties_select_all().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_hierarchy (struct wmOperatorType * ot)
Definition at line 4092 of file editarmature.c.
References armature_select_hierarchy_exec(), BONE_SELECT_CHILD, BONE_SELECT_PARENT, wmOperatorType::description, direction_items, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_inverse (struct wmOperatorType * ot)
Definition at line 3957 of file editarmature.c.
References armature_select_inverse_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_select_linked (struct wmOperatorType * ot)
Definition at line 1561 of file editarmature.c.
References armature_select_linked_invoke(), armature_select_linked_poll(), wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_separate (struct wmOperatorType * ot)
Definition at line 1243 of file editarmature.c.
References wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, separate_armature_exec(), and WM_operator_confirm().
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_subdivide (struct wmOperatorType * ot)
Definition at line 3585 of file editarmature.c.
References armature_subdivide_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_int(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void ARMATURE_OT_switch_direction (struct wmOperatorType * ot)
Definition at line 3691 of file editarmature.c.
References armature_switch_direction_exec(), wmOperatorType::description, ED_operator_editarmature(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void BIF_sk_selectStroke (struct bContext * C, const int mval[2], short extend)
Definition at line 2476 of file editarmature_sketch.c.
References ToolSettings::bone_sketching, BONE_SKETCHING, contextSketch(), CTX_data_tool_settings(), CTX_wm_area(), ED_area_tag_redraw(), NULL, and sk_selectStroke().
Referenced by mouse_armature().
struct EditBone* duplicateEditBone (struct EditBone * curBone, const char * name, struct ListBase * editbones, struct Object * ob) [read]
Definition at line 2569 of file editarmature.c.
References duplicateEditBoneObjects().
Referenced by armature_duplicate_selected_exec().
struct EditBone* duplicateEditBoneObjects (struct EditBone * curBone, const char * name, struct ListBase * editbones, struct Object * src_ob, struct Object * dst_ob) [read]
Definition at line 2526 of file editarmature.c.
References BLI_addtail(), BLI_strncpy(), duplicate_pose_channel_data(), IDP_CopyProperty(), MEM_mallocN(), EditBone::name, NULL, Object::pose, EditBone::prop, EditBone::temp, unique_editbone_name(), and verify_pose_channel().
Referenced by cloneArc(), cloneControl(), and duplicateEditBone().
EditBone* make_boneList (struct ListBase * edbo, struct ListBase * bones, struct EditBone * parent, struct Bone * actBone)
Definition at line 247 of file editarmature.c.
References Bone::arm_head, Bone::arm_roll, Bone::arm_tail, BLI_addtail(), BLI_strncpy(), BONE_CONNECTED, BONE_ROOTSEL, BONE_SELECTED, BONE_TIPSEL, Bone::childbase, copy_v3_v3(), EditBone::dist, Bone::dist, Bone::ease1, EditBone::ease1, Bone::ease2, EditBone::ease2, ListBase::first, EditBone::flag, Bone::flag, EditBone::head, IDP_CopyProperty(), Bone::layer, EditBone::layer, EditBone::length, Bone::length, make_boneList(), MEM_callocN(), Bone::name, EditBone::name, Bone::next, NULL, EditBone::parent, Bone::prop, EditBone::prop, Bone::rad_head, EditBone::rad_head, Bone::rad_tail, EditBone::rad_tail, EditBone::roll, EditBone::segments, Bone::segments, EditBone::tail, EditBone::weight, Bone::weight, EditBone::xwidth, Bone::xwidth, EditBone::zwidth, and Bone::zwidth.
Referenced by armatureSelectedToGraph(), ED_armature_to_edit(), make_boneList(), and RIG_graphFromArmature().
void POSE_OT_armature_apply (struct wmOperatorType * ot)
Definition at line 729 of file editarmature.c.
References apply_armature_pose2bones_exec(), wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void POSE_OT_armature_layers (struct wmOperatorType * ot)
Definition at line 2003 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_armature_layers_exec(), pose_armature_layers_invoke(), RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_autoside_names (struct wmOperatorType * ot)
Definition at line 1832 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_autoside_names_exec(), wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_bone_layers (struct wmOperatorType * ot)
Definition at line 2097 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_bone_layers_exec(), pose_bone_layers_invoke(), RNA_def_boolean_layer_member(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_breakdown (struct wmOperatorType * ot)
Definition at line 876 of file poseSlide.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_slide_breakdown_exec(), pose_slide_breakdown_invoke(), pose_slide_cancel(), pose_slide_modal(), and pose_slide_opdef_properties().
Referenced by ED_operatortypes_armature().
void POSE_OT_copy (struct wmOperatorType * ot)
Definition at line 1151 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, wmOperatorType::poll, and pose_copy_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_flip_names (struct wmOperatorType * ot)
Definition at line 1785 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_flip_names_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_add (struct wmOperatorType * ot)
Definition at line 1268 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_add_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_assign (struct wmOperatorType * ot)
Definition at line 1423 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_group_assign_exec(), pose_groups_menu_invoke(), RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_group_deselect (struct wmOperatorType * ot)
Definition at line 1740 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_deselect_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_move (struct wmOperatorType * ot)
Definition at line 1554 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, group_move_exec(), wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_group_remove (struct wmOperatorType * ot)
Definition at line 1308 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_remove_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_select (struct wmOperatorType * ot)
Definition at line 1702 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_select_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_group_sort (struct wmOperatorType * ot)
Definition at line 1644 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, group_sort_exec(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, and wmOperatorType::poll.
Referenced by ED_operatortypes_armature().
void POSE_OT_group_unassign (struct wmOperatorType * ot)
Definition at line 1479 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_group_unassign_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_hide (struct wmOperatorType * ot)
Definition at line 5191 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_hide_exec(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_loc_clear (struct wmOperatorType * ot)
Definition at line 5000 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_loc_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_paste (struct wmOperatorType * ot)
Definition at line 1218 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_paste_exec(), PROP_SKIP_SAVE, RNA_def_boolean(), RNA_def_property_flag(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_paths_calculate (struct wmOperatorType * ot)
Definition at line 236 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_calculate_paths_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_paths_clear (struct wmOperatorType * ot)
Definition at line 304 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_paths_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_propagate (struct wmOperatorType * ot)
Definition at line 1231 of file poseSlide.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, POSE_PROPAGATE_BEFORE_END, POSE_PROPAGATE_BEFORE_FRAME, pose_propagate_exec(), POSE_PROPAGATE_LAST_KEY, POSE_PROPAGATE_NEXT_KEY, POSE_PROPAGATE_SELECTED_MARKERS, POSE_PROPAGATE_SMART_HOLDS, wmOperatorType::prop, RNA_def_enum(), RNA_def_float(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_push (struct wmOperatorType * ot)
Definition at line 762 of file poseSlide.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_slide_cancel(), pose_slide_modal(), pose_slide_opdef_properties(), pose_slide_push_exec(), and pose_slide_push_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_quaternions_flip (struct wmOperatorType * ot)
Definition at line 2217 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_flip_quats_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_relax (struct wmOperatorType * ot)
Definition at line 819 of file poseSlide.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_slide_cancel(), pose_slide_modal(), pose_slide_opdef_properties(), pose_slide_relax_exec(), and pose_slide_relax_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_reveal (struct wmOperatorType * ot)
Definition at line 5237 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_reveal_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_rot_clear (struct wmOperatorType * ot)
Definition at line 4979 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_rot_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_rotation_mode_set (struct wmOperatorType * ot)
Definition at line 1878 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_bone_rotmode_exec(), posebone_rotmode_items, wmOperatorType::prop, RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_scale_clear (struct wmOperatorType * ot)
Definition at line 4958 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_scale_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_all (struct wmOperatorType * ot)
Definition at line 5082 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_de_select_all_exec(), and WM_operator_properties_select_all().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_constraint_target (struct wmOperatorType * ot)
Definition at line 364 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_select_constraint_target_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_flip_active (struct wmOperatorType * ot)
Definition at line 743 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_bone_flip_active_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_grouped (struct wmOperatorType * ot)
Definition at line 676 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_select_grouped_exec(), wmOperatorType::prop, prop_select_grouped_types, RNA_def_boolean(), RNA_def_enum(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSE_OT_select_hierarchy (struct wmOperatorType * ot)
Definition at line 457 of file poseobject.c.
References BONE_SELECT_CHILD, BONE_SELECT_PARENT, wmOperatorType::description, direction_items, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_select_hierarchy_exec(), wmOperatorType::prop, RNA_def_boolean(), RNA_def_enum(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_select_linked (struct wmOperatorType * ot)
Definition at line 1467 of file editarmature.c.
References wmOperatorType::description, wmOperatorType::exec, FALSE, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, pose_select_connected_invoke(), pose_select_linked_poll(), RNA_def_boolean(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSE_OT_select_parent (struct wmOperatorType * ot)
Definition at line 5126 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_select_parent_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_transforms_clear (struct wmOperatorType * ot)
Definition at line 5021 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_transforms_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_user_transforms_clear (struct wmOperatorType * ot)
Definition at line 2293 of file poseobject.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_clear_user_transforms_exec().
Referenced by ED_operatortypes_armature().
void POSE_OT_visual_transform_apply (struct wmOperatorType * ot)
Definition at line 780 of file editarmature.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and pose_visual_transform_apply_exec().
Referenced by ED_operatortypes_armature().
void poseAnim_mapping_autoKeyframe (struct bContext * C, struct Scene * scene, struct Object * ob, ListBase * pfLinks, float cframe)
Definition at line 222 of file poseUtils.c.
References ANIM_apply_keyingset(), ANIM_get_keyingset_for_autokeying(), ANIM_KS_WHOLE_CHARACTER_ID, ANIM_relative_keyingset_add_source(), autokeyframe_cfra_can_key(), bPose::avs, BLI_freelistN(), bPoseChannel::bone, BONE_UNKEYED, ED_pose_recalculate_paths(), ListBase::first, Bone::flag, Object::id, MODIFYKEY_MODE_INSERT, MOTIONPATH_BAKE_HAS_PATHS, tPChanFCurveLink::next, NULL, bAnimVizSettings::path_bakeflag, tPChanFCurveLink::pchan, Object::pose, and RNA_PoseBone.
Referenced by pose_slide_autoKeyframe().
void poseAnim_mapping_free (ListBase * pfLinks)
Definition at line 153 of file poseUtils.c.
References BLI_freelinkN(), BLI_freelistN(), tPChanFCurveLink::fcurves, ListBase::first, IDP_FreeProperty(), MEM_freeN(), tPChanFCurveLink::next, NULL, tPChanFCurveLink::oldprops, and tPChanFCurveLink::pchan_path.
Referenced by pose_slide_exit().
void poseAnim_mapping_get (struct bContext * C, ListBase * pfLinks, struct Object * ob, struct bAction * act)
Definition at line 129 of file poseUtils.c.
References CTX_DATA_BEGIN, CTX_DATA_END, fcurves_to_pchan_links_get(), ListBase::first, and NULL.
Referenced by pose_slide_init().
LinkData* poseAnim_mapping_getNextFCurve (ListBase * fcuLinks, LinkData * prev, const char * path)
Definition at line 265 of file poseUtils.c.
References LinkData::data, ListBase::first, if(), LinkData::next, NULL, and FCurve::rna_path.
Referenced by pose_slide_apply_quat(), and pose_slide_apply_vec3().
void poseAnim_mapping_refresh (struct bContext * C, struct Scene * scene, struct Object * ob)
Definition at line 181 of file poseUtils.c.
References ARM_DELAYDEFORM, DAG_id_tag_update(), Object::data, bArmature::flag, Object::id, if(), NC_OBJECT, ND_POSE, OB_RECALC_DATA, where_is_pose(), and WM_event_add_notifier().
Referenced by pose_slide_refresh().
void poseAnim_mapping_reset (ListBase * pfLinks)
Definition at line 199 of file poseUtils.c.
References copy_qt_qt(), copy_v3_v3(), bPoseChannel::eul, ListBase::first, IDP_SyncGroupValues(), bPoseChannel::loc, tPChanFCurveLink::next, tPChanFCurveLink::oldangle, tPChanFCurveLink::oldaxis, tPChanFCurveLink::oldloc, tPChanFCurveLink::oldprops, tPChanFCurveLink::oldquat, tPChanFCurveLink::oldrot, tPChanFCurveLink::oldscale, tPChanFCurveLink::pchan, bPoseChannel::prop, bPoseChannel::quat, bPoseChannel::rotAngle, bPoseChannel::rotAxis, and bPoseChannel::size.
Referenced by pose_slide_reset().
void POSELIB_OT_action_sanitise (struct wmOperatorType * ot)
Definition at line 356 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and poselib_sanitise_exec().
Referenced by ED_operatortypes_armature().
void POSELIB_OT_apply_pose (struct wmOperatorType * ot)
Definition at line 1649 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_preview_exec(), wmOperatorType::prop, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_browse_interactive (struct wmOperatorType * ot)
Definition at line 1623 of file poselib.c.
References wmOperatorType::cancel, wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_preview_cancel(), poselib_preview_exec(), poselib_preview_invoke(), poselib_preview_modal(), wmOperatorType::prop, RNA_def_int(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_new (struct wmOperatorType * ot)
Definition at line 235 of file poselib.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and poselib_new_exec().
Referenced by ED_operatortypes_armature().
void POSELIB_OT_pose_add (struct wmOperatorType * ot)
Definition at line 486 of file poselib.c.
References wmOperatorType::description, ED_operator_posemode(), wmOperatorType::exec, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_add_exec(), poselib_add_menu_invoke(), RNA_def_int(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_pose_remove (struct wmOperatorType * ot)
Definition at line 600 of file poselib.c.
References wmOperatorType::description, DummyRNA_NULL_items, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_remove_exec(), poselib_stored_pose_itemf(), wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), wmOperatorType::srna, and WM_menu_invoke().
Referenced by ED_operatortypes_armature().
void POSELIB_OT_pose_rename (struct wmOperatorType * ot)
Definition at line 687 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, NULL, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, poselib_rename_exec(), poselib_rename_invoke(), poselib_stored_pose_itemf(), wmOperatorType::prop, RNA_def_enum(), RNA_def_enum_funcs(), RNA_def_string(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void POSELIB_OT_unlink (struct wmOperatorType * ot)
Definition at line 270 of file poselib.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::flag, has_poselib_pose_data_poll(), wmOperatorType::idname, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, and poselib_unlink_exec().
Referenced by ED_operatortypes_armature().
void preEditBoneDuplicate (struct ListBase * editbones)
Definition at line 2456 of file editarmature.c.
References ListBase::first, EditBone::next, NULL, and EditBone::temp.
Referenced by armature_duplicate_selected_exec(), and cloneRigGraph().
void SKETCH_OT_cancel_stroke (struct wmOperatorType * ot)
Definition at line 2869 of file editarmature_sketch.c.
References ED_operator_sketch_mode_active_stroke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_cancel().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_convert (struct wmOperatorType * ot)
Definition at line 2884 of file editarmature_sketch.c.
References ED_operator_sketch_full_mode(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, and sketch_convert().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_delete (struct wmOperatorType * ot)
Definition at line 2839 of file editarmature_sketch.c.
References ED_operator_sketch_full_mode(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_delete().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_draw_preview (struct wmOperatorType * ot)
Definition at line 2914 of file editarmature_sketch.c.
References ED_operator_sketch_mode_active_stroke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, RNA_def_boolean(), sketch_draw_preview(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void SKETCH_OT_draw_stroke (struct wmOperatorType * ot)
Definition at line 2931 of file editarmature_sketch.c.
References wmOperatorType::cancel, ED_operator_sketch_mode(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_boolean(), sketch_draw_stroke(), sketch_draw_stroke_cancel(), sketch_draw_stroke_modal(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void SKETCH_OT_finish_stroke (struct wmOperatorType * ot)
Definition at line 2899 of file editarmature_sketch.c.
References ED_operator_sketch_mode_active_stroke(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_finish().
Referenced by ED_operatortypes_armature().
void SKETCH_OT_gesture (struct wmOperatorType * ot)
Definition at line 2950 of file editarmature_sketch.c.
References wmOperatorType::cancel, ED_operator_sketch_mode_gesture(), wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_BLOCKING, wmOperatorType::poll, RNA_def_boolean(), sketch_draw_gesture(), sketch_draw_gesture_cancel(), sketch_draw_gesture_modal(), and wmOperatorType::srna.
Referenced by ED_operatortypes_armature().
void SKETCH_OT_select (struct wmOperatorType * ot)
Definition at line 2854 of file editarmature_sketch.c.
References ED_operator_sketch_full_mode(), wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::name, wmOperatorType::poll, and sketch_select().
Referenced by ED_operatortypes_armature().
void updateDuplicateSubtarget (struct EditBone * dupBone, struct ListBase * editbones, struct Object * ob)
Definition at line 2520 of file editarmature.c.
References updateDuplicateSubtargetObjects().
Referenced by armature_duplicate_selected_exec().
void updateDuplicateSubtargetObjects (struct EditBone * dupBone, struct ListBase * editbones, struct Object * src_ob, struct Object * dst_ob)
Definition at line 2471 of file editarmature.c.
References BLI_strncpy(), constraint_get_typeinfo(), bPoseChannel::constraints, ListBase::first, bConstraintTypeInfo::flush_constraint_targets, bConstraintTypeInfo::get_constraint_targets, get_named_editbone(), EditBone::name, bConstraint::next, bConstraintTarget::next, NULL, Object::pose, bConstraintTarget::subtarget, bConstraintTarget::tar, EditBone::temp, and verify_pose_channel().
Referenced by cloneRigGraph(), and updateDuplicateSubtarget().