Blender: rna_actuator.c File Reference
rna_actuator.c File Reference
RNA
#include <stdlib.h>
#include "RNA_define.h"
#include "RNA_access.h"
#include "rna_internal.h"
#include "DNA_constraint_types.h"
#include "DNA_object_types.h"
#include "DNA_actuator_types.h"
#include "DNA_scene_types.h"
#include "WM_types.h"
#include "BLI_utildefines.h"
Functions
void rna_def_actuator (BlenderRNA *brna)
static void rna_def_action_actuator (BlenderRNA *brna)
static void rna_def_object_actuator (BlenderRNA *brna)
static void rna_def_camera_actuator (BlenderRNA *brna)
static void rna_def_sound_actuator (BlenderRNA *brna)
static void rna_def_property_actuator (BlenderRNA *brna)
static void rna_def_constraint_actuator (BlenderRNA *brna)
static void rna_def_edit_object_actuator (BlenderRNA *brna)
static void rna_def_scene_actuator (BlenderRNA *brna)
static void rna_def_random_actuator (BlenderRNA *brna)
static void rna_def_message_actuator (BlenderRNA *brna)
static void rna_def_game_actuator (BlenderRNA *brna)
static void rna_def_visibility_actuator (BlenderRNA *brna)
static void rna_def_twodfilter_actuator (BlenderRNA *brna)
static void rna_def_parent_actuator (BlenderRNA *brna)
static void rna_def_shape_action_actuator (BlenderRNA *brna)
static void rna_def_state_actuator (BlenderRNA *brna)
static void rna_def_armature_actuator (BlenderRNA *brna)
static void rna_def_steering_actuator (BlenderRNA *brna)
void RNA_def_actuator (BlenderRNA *brna)
Variables
EnumPropertyItem actuator_type_items []
Detailed Description
Definition in file rna_actuator.c.
Function Documentation
static void rna_def_action_actuator (BlenderRNA * brna) [static]
Definition at line 567 of file rna_actuator.c.
References ACT_ACTION_FLIPPER, ACT_ACTION_FROM_PROP, ACT_ACTION_LOOP_END, ACT_ACTION_LOOP_STOP, ACT_ACTION_MOTION, ACT_ACTION_PINGPONG, ACT_ACTION_PLAY, ACT_IPOADD, ACT_IPOCHILD, ACT_IPOFORCE, ACT_IPOLOCAL, MAXFRAME, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
void rna_def_actuator (BlenderRNA * brna)
Definition at line 532 of file rna_actuator.c.
References ACT_PIN, ACT_SHOW, NC_LOGIC, NULL, PROP_ANIMATABLE, PROP_BOOLEAN, PROP_ENUM, PROP_NONE, PROP_STRING, RNA_api_actuator(), RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_clear_flag(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_string_funcs(), RNA_def_property_ui_icon(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_name_property(), RNA_def_struct_refine_func(), RNA_def_struct_sdna(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
void RNA_def_actuator (BlenderRNA * brna)
Definition at line 2088 of file rna_actuator.c.
References rna_def_action_actuator(), rna_def_actuator(), rna_def_armature_actuator(), rna_def_camera_actuator(), rna_def_constraint_actuator(), rna_def_edit_object_actuator(), rna_def_game_actuator(), rna_def_message_actuator(), rna_def_object_actuator(), rna_def_parent_actuator(), rna_def_property_actuator(), rna_def_random_actuator(), rna_def_scene_actuator(), rna_def_shape_action_actuator(), rna_def_sound_actuator(), rna_def_state_actuator(), rna_def_steering_actuator(), rna_def_twodfilter_actuator(), and rna_def_visibility_actuator().
static void rna_def_armature_actuator (BlenderRNA * brna) [static]
Definition at line 1924 of file rna_actuator.c.
References ACT_ARM_DISABLE, ACT_ARM_ENABLE, ACT_ARM_RUN, ACT_ARM_SETINFLUENCE, ACT_ARM_SETTARGET, ACT_ARM_SETWEIGHT, NC_LOGIC, NULL, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_camera_actuator (BlenderRNA * brna) [static]
Definition at line 880 of file rna_actuator.c.
References NC_LOGIC, NULL, OB_NEGX, OB_NEGY, OB_POSX, OB_POSY, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_constraint_actuator (BlenderRNA * brna) [static]
Definition at line 1081 of file rna_actuator.c.
References ACT_CONST_DIRNX, ACT_CONST_DIRNY, ACT_CONST_DIRNZ, ACT_CONST_DIRPX, ACT_CONST_DIRPY, ACT_CONST_DIRPZ, ACT_CONST_DISTANCE, ACT_CONST_DOROTFH, ACT_CONST_LOCAL, ACT_CONST_LOCX, ACT_CONST_LOCY, ACT_CONST_LOCZ, ACT_CONST_MATERIAL, ACT_CONST_NONE, ACT_CONST_NORMAL, ACT_CONST_PERMANENT, ACT_CONST_TYPE_DIST, ACT_CONST_TYPE_FH, ACT_CONST_TYPE_LOC, ACT_CONST_TYPE_ORI, NC_LOGIC, NULL, PROP_BOOLEAN, prop_direction_items, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_STRING, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_edit_object_actuator (BlenderRNA * brna) [static]
Definition at line 1302 of file rna_actuator.c.
References ACT_EDOB_ADD_OBJECT, ACT_EDOB_DISABLE_RB, ACT_EDOB_DYNAMICS, ACT_EDOB_ENABLE_RB, ACT_EDOB_END_OBJECT, ACT_EDOB_LOCAL_ANGV, ACT_EDOB_LOCAL_LINV, ACT_EDOB_REPLACE_MESH, ACT_EDOB_REPLACE_MESH_NOGFX, ACT_EDOB_REPLACE_MESH_PHYS, ACT_EDOB_RESTORE_DYN, ACT_EDOB_SET_MASS, ACT_EDOB_SUSPEND_DYN, ACT_EDOB_TRACK_TO, ACT_TRACK_3D, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_game_actuator (BlenderRNA * brna) [static]
Definition at line 1641 of file rna_actuator.c.
References ACT_GAME_LOAD, ACT_GAME_LOADCFG, ACT_GAME_QUIT, ACT_GAME_RESTART, ACT_GAME_SAVECFG, NC_LOGIC, NULL, PROP_ENUM, PROP_FILEPATH, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_message_actuator (BlenderRNA * brna) [static]
Definition at line 1599 of file rna_actuator.c.
References ACT_MESG_MESG, ACT_MESG_PROP, NC_LOGIC, NULL, PROP_ENUM, PROP_NONE, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_string_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_object_actuator (BlenderRNA * brna) [static]
Definition at line 691 of file rna_actuator.c.
References ACT_ADD_LIN_VEL, ACT_ANG_VEL_LOCAL, ACT_DLOC_LOCAL, ACT_DROT_LOCAL, ACT_FORCE_LOCAL, ACT_LIN_VEL_LOCAL, ACT_OBJECT_NORMAL, ACT_OBJECT_SERVO, ACT_SERVO_LIMIT_X, ACT_SERVO_LIMIT_Y, ACT_SERVO_LIMIT_Z, ACT_TORQUE_LOCAL, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_EULER, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_XYZ, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_funcs(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_funcs(), RNA_def_property_float_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_parent_actuator (BlenderRNA * brna) [static]
Definition at line 1768 of file rna_actuator.c.
References ACT_PARENT_COMPOUND, ACT_PARENT_GHOST, ACT_PARENT_REMOVE, ACT_PARENT_SET, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_property_actuator (BlenderRNA * brna) [static]
Definition at line 1034 of file rna_actuator.c.
References ACT_PROP_ADD, ACT_PROP_ASSIGN, ACT_PROP_COPY, ACT_PROP_TOGGLE, NC_LOGIC, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_pointer_sdna(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_random_actuator (BlenderRNA * brna) [static]
Definition at line 1472 of file rna_actuator.c.
References ACT_RANDOM_BOOL_BERNOUILLI, ACT_RANDOM_BOOL_CONST, ACT_RANDOM_BOOL_UNIFORM, ACT_RANDOM_FLOAT_CONST, ACT_RANDOM_FLOAT_NEGATIVE_EXPONENTIAL, ACT_RANDOM_FLOAT_NORMAL, ACT_RANDOM_FLOAT_UNIFORM, ACT_RANDOM_INT_CONST, ACT_RANDOM_INT_POISSON, ACT_RANDOM_INT_UNIFORM, MAXFRAME, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_PERCENTAGE, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_scene_actuator (BlenderRNA * brna) [static]
Definition at line 1416 of file rna_actuator.c.
References ACT_SCENE_ADD_BACK, ACT_SCENE_ADD_FRONT, ACT_SCENE_CAMERA, ACT_SCENE_REMOVE, ACT_SCENE_RESTART, ACT_SCENE_RESUME, ACT_SCENE_SET, ACT_SCENE_SUSPEND, NC_LOGIC, NULL, PROP_EDITABLE, PROP_ENUM, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_shape_action_actuator (BlenderRNA * brna) [static]
Definition at line 1809 of file rna_actuator.c.
References ACT_ACTION_FLIPPER, ACT_ACTION_FROM_PROP, ACT_ACTION_LOOP_END, ACT_ACTION_LOOP_STOP, ACT_ACTION_MOTION, ACT_ACTION_PINGPONG, ACT_ACTION_PLAY, MAXFRAME, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, PROP_STRING, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_string_sdna(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_sound_actuator (BlenderRNA * brna) [static]
Definition at line 934 of file rna_actuator.c.
References ACT_SND_3D_SOUND, ACT_SND_LOOP_BIDIRECTIONAL_SOUND, ACT_SND_LOOP_BIDIRECTIONAL_STOP_SOUND, ACT_SND_LOOP_END_SOUND, ACT_SND_LOOP_STOP_SOUND, ACT_SND_PLAY_END_SOUND, ACT_SND_PLAY_STOP_SOUND, FLT_MAX, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_state_actuator (BlenderRNA * brna) [static]
Definition at line 1895 of file rna_actuator.c.
References ACT_STATE_ADD, ACT_STATE_CHANGE, ACT_STATE_REMOVE, ACT_STATE_SET, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_ENUM, PROP_LAYER_MEMBER, PROP_NONE, RNA_def_property(), RNA_def_property_array(), RNA_def_property_boolean_funcs(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_steering_actuator (BlenderRNA * brna) [static]
Definition at line 1986 of file rna_actuator.c.
References ACT_STEERING_AUTOMATICFACING, ACT_STEERING_ENABLEVISUALIZATION, ACT_STEERING_FLEE, ACT_STEERING_NORMALUP, ACT_STEERING_PATHFOLLOWING, ACT_STEERING_SEEK, ACT_STEERING_SELFTERMINATED, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_funcs(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_range(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_twodfilter_actuator (BlenderRNA * brna) [static]
Definition at line 1708 of file rna_actuator.c.
References ACT_2DFILTER_BLUR, ACT_2DFILTER_CUSTOMFILTER, ACT_2DFILTER_DILATION, ACT_2DFILTER_DISABLED, ACT_2DFILTER_ENABLED, ACT_2DFILTER_EROSION, ACT_2DFILTER_GRAYSCALE, ACT_2DFILTER_INVERT, ACT_2DFILTER_LAPLACIAN, ACT_2DFILTER_MOTIONBLUR, ACT_2DFILTER_NOFILTER, ACT_2DFILTER_PREWITT, ACT_2DFILTER_SEPIA, ACT_2DFILTER_SHARPEN, ACT_2DFILTER_SOBEL, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_EDITABLE, PROP_ENUM, PROP_FLOAT, PROP_INT, PROP_NONE, PROP_POINTER, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_enum_items(), RNA_def_property_enum_sdna(), RNA_def_property_flag(), RNA_def_property_float_sdna(), RNA_def_property_int_sdna(), RNA_def_property_pointer_sdna(), RNA_def_property_range(), RNA_def_property_struct_type(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
static void rna_def_visibility_actuator (BlenderRNA * brna) [static]
Definition at line 1678 of file rna_actuator.c.
References ACT_VISIBILITY_INVISIBLE, ACT_VISIBILITY_OCCLUSION, ACT_VISIBILITY_RECURSIVE, NC_LOGIC, NULL, PROP_BOOLEAN, PROP_NONE, RNA_def_property(), RNA_def_property_boolean_negative_sdna(), RNA_def_property_boolean_sdna(), RNA_def_property_ui_text(), RNA_def_property_update(), RNA_def_struct(), RNA_def_struct_sdna_from(), and RNA_def_struct_ui_text().
Referenced by RNA_def_actuator().
Variable Documentation
EnumPropertyItem actuator_type_items[]
Initial value:
 {
    {ACT_ACTION, "ACTION", 0, "Action", ""},
    {ACT_ARMATURE, "ARMATURE", 0, "Armature", ""},
    {ACT_CAMERA, "CAMERA", 0, "Camera", ""},
    {ACT_CONSTRAINT, "CONSTRAINT", 0, "Constraint", ""},
    {ACT_EDIT_OBJECT, "EDIT_OBJECT", 0, "Edit Object", ""},
    {ACT_2DFILTER, "FILTER_2D", 0, "Filter 2D", ""},
    {ACT_GAME, "GAME", 0, "Game", ""},
    {ACT_MESSAGE, "MESSAGE", 0, "Message", ""},
    {ACT_OBJECT, "MOTION", 0, "Motion", ""},
    {ACT_PARENT, "PARENT", 0, "Parent", ""},
    {ACT_PROPERTY, "PROPERTY", 0, "Property", ""},
    {ACT_RANDOM, "RANDOM", 0, "Random", ""},
    {ACT_SCENE, "SCENE", 0, "Scene", ""},
    {ACT_SOUND, "SOUND", 0, "Sound", ""},
    {ACT_STATE, "STATE", 0, "State", ""},
    {ACT_VISIBILITY, "VISIBILITY", 0, "Visibility", ""},
    {ACT_STEERING, "STEERING", 0, "Steering", ""},
    {0, NULL, 0, NULL, NULL}}
Definition at line 44 of file rna_actuator.c.