Blender: space_action.c File Reference
space_action.c File Reference
action space
#include <string.h>
#include <stdio.h>
#include "DNA_action_types.h"
#include "DNA_scene_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_blenlib.h"
#include "BLI_math.h"
#include "BLI_rand.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "BKE_screen.h"
#include "ED_screen.h"
#include "BIF_gl.h"
#include "WM_api.h"
#include "WM_types.h"
#include "UI_resources.h"
#include "UI_view2d.h"
#include "ED_space_api.h"
#include "ED_anim_api.h"
#include "ED_markers.h"
#include "action_intern.h"
Functions
static SpaceLink * action_new (const bContext *C)
static void action_free (SpaceLink *UNUSED(sl))
static void action_init (struct wmWindowManager *UNUSED(wm), ScrArea *sa)
static SpaceLink * action_duplicate (SpaceLink *sl)
static void action_main_area_init (wmWindowManager *wm, ARegion *ar)
static void action_main_area_draw (const bContext *C, ARegion *ar)
static void action_channel_area_init (wmWindowManager *wm, ARegion *ar)
static void action_channel_area_draw (const bContext *C, ARegion *ar)
static void action_header_area_init (wmWindowManager *UNUSED(wm), ARegion *ar)
static void action_header_area_draw (const bContext *C, ARegion *ar)
static void action_channel_area_listener (ARegion *ar, wmNotifier *wmn)
static void action_main_area_listener (ARegion *ar, wmNotifier *wmn)
static void action_listener (ScrArea *sa, wmNotifier *wmn)
static void action_header_area_listener (ARegion *ar, wmNotifier *wmn)
static void action_refresh (const bContext *C, ScrArea *sa)
void ED_spacetype_action (void)
Detailed Description
Definition in file space_action.c.
Function Documentation
static void action_channel_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 230 of file space_action.c.
References ANIM_animdata_get_context(), draw_channel_names(), TH_BACK, UI_ThemeClearColor(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_restore(), ARegion::v2d, and V2D_ARG_DUMMY.
Referenced by ED_spacetype_action().
static void action_channel_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 219 of file space_action.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_LIST, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_action().
static void action_channel_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 269 of file space_action.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_RENAME, NC_ANIMATION, NC_ID, NC_OBJECT, NC_SCENE, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_FRAME, ND_KEYS, ND_MODIFIER, and ND_OB_ACTIVE.
Referenced by ED_spacetype_action().
static SpaceLink* action_duplicate (SpaceLink * sl) [static]
Definition at line 144 of file space_action.c.
References MEM_dupallocN().
Referenced by ED_spacetype_action().
static void action_free (SpaceLink * UNUSEDsl) [static]
Definition at line 130 of file space_action.c.
Referenced by ED_spacetype_action().
static void action_header_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 264 of file space_action.c.
References ED_region_header().
Referenced by ED_spacetype_action().
static void action_header_area_init (wmWindowManager * UNUSEDwm, ARegion * ar) [static]
Definition at line 259 of file space_action.c.
References ED_region_header_init().
Referenced by ED_spacetype_action().
static void action_header_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 429 of file space_action.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_RENAME, NC_ID, NC_SCENE, and ND_OB_ACTIVE.
Referenced by ED_spacetype_action().
static void action_init (struct wmWindowManager * UNUSEDwm, ScrArea * sa) [static]
Definition at line 138 of file space_action.c.
References ListBase::first, SpaceAction::flag, SACTION_TEMP_NEEDCHANSYNC, and ScrArea::spacedata.
Referenced by ED_spacetype_action().
static void action_listener (ScrArea * sa, wmNotifier * wmn) [static]
Definition at line 355 of file space_action.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_area_tag_redraw(), ED_area_tag_refresh(), ELEM, ListBase::first, SpaceAction::flag, SpaceAction::mode, NA_SELECTED, NC_ANIMATION, NC_NODE, NC_OBJECT, NC_SCENE, NC_SCREEN, NC_SPACE, ND_ANIMCHAN, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_GPENCIL, ND_KEYFRAME, ND_NLA_ACTCHANGE, ND_OB_ACTIVE, ND_OB_SELECT, ND_SPACE_CHANGED, ND_SPACE_DOPESHEET, ND_TRANSFORM, SACTCONT_GPENCIL, SACTION_TEMP_NEEDCHANSYNC, and ScrArea::spacedata.
Referenced by ED_spacetype_action().
static void action_main_area_draw (const bContext * C, ARegion * ar) [static]
Definition at line 167 of file space_action.c.
References ANIM_animdata_get_context(), ANIM_draw_cfra(), ANIM_draw_previewrange(), CTX_data_scene(), CTX_wm_space_action(), draw_channel_strips(), DRAW_MARKERS_LOCAL, draw_markers_time(), DRAWCFRA_SHOW_NUMBOX, DRAWCFRA_UNIT_SECONDS, SpaceAction::flag, FCurve::flag, Scene::markers, bAnimContext::markers, SACTION_DRAWTIME, SACTION_NODRAWCFRANUM, bAnimContext::scene, TH_BACK, UI_ThemeClearColor(), UI_view2d_grid_calc(), UI_view2d_grid_draw(), UI_view2d_grid_free(), UI_view2d_scrollers_calc(), UI_view2d_scrollers_draw(), UI_view2d_scrollers_free(), UI_view2d_view_ortho(), UI_view2d_view_orthoSpecial(), UI_view2d_view_restore(), ARegion::v2d, V2D_ARG_DUMMY, V2D_GRID_CLAMP, V2D_GRIDLINES_ALL, V2D_UNIT_FRAMES, V2D_UNIT_SECONDS, ARegion::winx, and ARegion::winy.
Referenced by ED_spacetype_action().
static void action_main_area_init (wmWindowManager * wm, ARegion * ar) [static]
Definition at line 156 of file space_action.c.
References wmWindowManager::defaultconf, ARegion::handlers, View2D::mask, SPACE_ACTION, UI_view2d_region_reinit(), ARegion::v2d, V2D_COMMONVIEW_CUSTOM, ARegion::winrct, ARegion::winx, ARegion::winy, WM_event_add_keymap_handler_bb(), and WM_keymap_find().
Referenced by ED_spacetype_action().
static void action_main_area_listener (ARegion * ar, wmNotifier * wmn) [static]
Definition at line 307 of file space_action.c.
References wmNotifier::action, wmNotifier::category, wmNotifier::data, ED_region_tag_redraw(), NA_EDITED, NA_RENAME, NC_ANIMATION, NC_ID, NC_NODE, NC_OBJECT, NC_SCENE, ND_BONE_ACTIVE, ND_BONE_SELECT, ND_FRAME, ND_KEYS, ND_MARKERS, ND_OB_ACTIVE, ND_RENDER_OPTIONS, and ND_TRANSFORM.
Referenced by ED_spacetype_action().
static SpaceLink* action_new (const bContext * C) [static]
Definition at line 67 of file space_action.c.
References SpaceAction::ads, ADS_FILTER_SUMMARY, View2D::align, ARegion::alignment, SpaceAction::autosnap, BLI_addtail(), CTX_wm_area(), View2D::cur, bDopeSheet::filterflag, View2D::flag, FLT_MAX, View2D::keepofs, View2D::keepzoom, View2D::max, MAXFRAMEF, View2D::maxzoom, MEM_callocN(), View2D::min, View2D::minzoom, SpaceAction::mode, SpaceAction::regionbase, ARegion::regiontype, RGN_ALIGN_BOTTOM, RGN_ALIGN_LEFT, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SACTCONT_DOPESHEET, SACTSNAP_FRAME, View2D::scroll, SPACE_ACTION, SpaceAction::spacetype, View2D::tot, ARegion::v2d, V2D_ALIGN_NO_POS_Y, V2D_KEEPOFS_Y, V2D_LOCKZOOM_Y, V2D_SCROLL_BOTTOM, V2D_SCROLL_RIGHT, V2D_SCROLL_SCALE_HORIZONTAL, V2D_VIEWSYNC_AREA_VERTICAL, ScrArea::winx, ScrArea::winy, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by ED_spacetype_action().
static void action_refresh (const bContext * C, ScrArea * sa) [static]
Definition at line 447 of file space_action.c.
References ANIM_sync_animchannels_to_data(), ED_area_tag_redraw(), ListBase::first, SpaceAction::flag, if(), SACTION_TEMP_NEEDCHANSYNC, and ScrArea::spacedata.
Referenced by ED_spacetype_action().
void ED_spacetype_action (void)
Definition at line 465 of file space_action.c.
References action_channel_area_draw(), action_channel_area_init(), action_channel_area_listener(), action_duplicate(), action_free(), action_header_area_draw(), action_header_area_init(), action_header_area_listener(), action_init(), action_keymap(), action_listener(), action_main_area_draw(), action_main_area_init(), action_main_area_listener(), action_new(), action_operatortypes(), action_refresh(), BKE_spacetype_register(), BKE_ST_MAXNAME, BLI_addhead(), ARegionType::draw, SpaceType::duplicate, ED_KEYMAP_ANIMATION, ED_KEYMAP_FRAMES, ED_KEYMAP_HEADER, ED_KEYMAP_MARKERS, ED_KEYMAP_UI, ED_KEYMAP_VIEW2D, SpaceType::free, HEADERY, ARegionType::init, SpaceType::init, SpaceType::keymap, ARegionType::keymapflag, ARegionType::listener, SpaceType::listener, MEM_callocN(), SpaceType::name, SpaceType::new, SpaceType::operatortypes, ARegionType::prefsizex, ARegionType::prefsizey, SpaceType::refresh, ARegionType::regionid, SpaceType::regiontypes, RGN_TYPE_CHANNELS, RGN_TYPE_HEADER, RGN_TYPE_WINDOW, SPACE_ACTION, and SpaceType::spaceid.
Referenced by ED_spacetypes_init().