Blender: edgehash.c File Reference
edgehash.c File Reference
blenlib
#include <stdlib.h>
#include <string.h>
#include "MEM_guardedalloc.h"
#include "BLI_utildefines.h"
#include "BLI_edgehash.h"
#include "BLI_mempool.h"
Classes
struct EdgeEntry
struct EdgeHash
struct EdgeHashIterator
Defines
#define EDGE_HASH(v0, v1) ((v0 * 39)^(v1 * 31))
#define EDGE_ORD(v0, v1)
Typedefs
typedef struct EdgeEntry EdgeEntry
Functions
EdgeHash * BLI_edgehash_new (void)
void BLI_edgehash_insert (EdgeHash *eh, unsigned int v0, unsigned int v1, void *val)
void ** BLI_edgehash_lookup_p (EdgeHash *eh, unsigned int v0, unsigned int v1)
void * BLI_edgehash_lookup (EdgeHash *eh, unsigned int v0, unsigned int v1)
int BLI_edgehash_haskey (EdgeHash *eh, unsigned int v0, unsigned int v1)
int BLI_edgehash_size (EdgeHash *eh)
void BLI_edgehash_clear (EdgeHash *eh, EdgeHashFreeFP valfreefp)
void BLI_edgehash_free (EdgeHash *eh, EdgeHashFreeFP valfreefp)
EdgeHashIterator * BLI_edgehashIterator_new (EdgeHash *eh)
void BLI_edgehashIterator_free (EdgeHashIterator *ehi)
void BLI_edgehashIterator_getKey (EdgeHashIterator *ehi, unsigned int *v0_r, unsigned int *v1_r)
void * BLI_edgehashIterator_getValue (EdgeHashIterator *ehi)
void BLI_edgehashIterator_setValue (EdgeHashIterator *ehi, void *val)
void BLI_edgehashIterator_step (EdgeHashIterator *ehi)
int BLI_edgehashIterator_isDone (EdgeHashIterator *ehi)
Variables
static unsigned int _ehash_hashsizes []
Detailed Description
Definition in file edgehash.c.
Define Documentation
#define EDGE_HASH (v0, v1) ((v0 * 39)^(v1 * 31))
Definition at line 51 of file edgehash.c.
Referenced by BLI_edgehash_insert(), and BLI_edgehash_lookup_p().
#define EDGE_ORD (v0, v1)
Value:
if (v0 > v1) {       \
        v0 ^= v1;        \
        v1 ^= v0;        \
        v0 ^= v1;        \
    }
Definition at line 54 of file edgehash.c.
Referenced by BLI_edgehash_insert(), and BLI_edgehash_lookup_p().
Typedef Documentation
typedef struct EdgeEntry EdgeEntry
Definition at line 63 of file edgehash.c.
Function Documentation
void BLI_edgehash_clear (EdgeHash * eh, EdgeHashFreeFP valfreefp)
Definition at line 166 of file edgehash.c.
References BLI_mempool_free(), EdgeHash::buckets, EdgeHash::epool, i, EdgeHash::nbuckets, EdgeHash::nentries, EdgeEntry::next, and NULL.
Referenced by BLI_edgehash_free().
void BLI_edgehash_free (EdgeHash * eh, EdgeHashFreeFP valfreefp)
Definition at line 187 of file edgehash.c.
References BLI_edgehash_clear(), BLI_mempool_destroy(), EdgeHash::buckets, EdgeHash::epool, and MEM_freeN().
Referenced by applyModifier(), BKE_mesh_calc_edges(), BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_validate_arrays(), ccgDM_release(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), CDDM_merge_verts(), CDDM_tessfaces_to_faces(), cloth_free_errorsprings(), cloth_free_modifier(), cloth_free_modifier_extern(), customdata_compare(), cutEdges(), dm_calc_normal(), draw_mesh_face_select(), explodeMesh(), laplacian_system_construct_end(), make_edges_mdata(), mesh_to_curve(), REEB_freeGraph(), select_linked_tfaces_with_seams(), sph_solver_finalise(), and ss_sync_from_uv().
int BLI_edgehash_haskey (EdgeHash * eh, unsigned int v0, unsigned int v1)
Definition at line 156 of file edgehash.c.
References BLI_edgehash_lookup_p(), and NULL.
Referenced by BKE_mesh_calc_edges(), BKE_mesh_validate_arrays(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cloth_build_springs(), cloth_bvh_objcollision(), get_marked_edge_info__orFlags(), mesh_to_curve(), select_linked_tfaces_with_seams(), and ss_sync_from_uv().
void BLI_edgehash_insert (EdgeHash * eh, unsigned int v0, unsigned int v1, void * val)
Definition at line 92 of file edgehash.c.
References _ehash_hashsizes, BLI_assert, BLI_mempool_alloc(), EdgeHash::buckets, EdgeHash::cursize, EDGE_HASH, EDGE_ORD, EdgeHash::epool, hash, i, MEM_freeN(), MEM_mallocN(), EdgeHash::nbuckets, EdgeHash::nentries, EdgeEntry::next, EdgeEntry::v0, EdgeEntry::v1, and EdgeEntry::val.
Referenced by applyModifier(), BKE_mesh_calc_edges(), BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_validate_arrays(), ccgDM_copyFinalLoopArray(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), CDDM_merge_verts(), CDDM_tessfaces_to_faces(), cloth_build_springs(), customdata_compare(), cutEdges(), explodeMesh(), get_marked_edge_info__orFlags(), hash_add_face(), laplacian_increase_edge_count(), make_edges_mdata(), mesh_to_curve(), select_linked_tfaces_with_seams(), sph_springhash_build(), and ss_sync_from_uv().
void* BLI_edgehash_lookup (EdgeHash * eh, unsigned int v0, unsigned int v1)
Definition at line 149 of file edgehash.c.
References BLI_edgehash_lookup_p(), and NULL.
Referenced by BKE_mesh_calc_edges(), BKE_mesh_validate_arrays(), ccgDM_copyFinalLoopArray(), CDDM_calc_edges(), CDDM_tessfaces_to_faces(), customdata_compare(), draw_mesh_face_select__setHiddenOpts(), draw_mesh_face_select__setSelectOpts(), edgecut_get(), laplacian_edge_count(), make_edges_mdata(), and sph_force_cb().
void** BLI_edgehash_lookup_p (EdgeHash * eh, unsigned int v0, unsigned int v1)
Definition at line 134 of file edgehash.c.
References EdgeHash::buckets, EDGE_HASH, EDGE_ORD, hash, EdgeHash::nbuckets, EdgeEntry::next, NULL, EdgeEntry::v0, EdgeEntry::v1, and EdgeEntry::val.
Referenced by BLI_edgehash_haskey(), BLI_edgehash_lookup(), CDDM_merge_verts(), get_marked_edge_info__orFlags(), and laplacian_increase_edge_count().
EdgeHash* BLI_edgehash_new (void)
Definition at line 78 of file edgehash.c.
References _ehash_hashsizes, BLI_mempool_create(), BLI_MEMPOOL_SYSMALLOC, EdgeHash::buckets, EdgeHash::cursize, EdgeHash::epool, MEM_callocN(), EdgeHash::nbuckets, and EdgeHash::nentries.
Referenced by applyModifier(), BKE_mesh_calc_edges(), BKE_mesh_convert_mfaces_to_mpolys(), BKE_mesh_validate_arrays(), ccgDM_copyFinalLoopArray(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), CDDM_merge_verts(), CDDM_tessfaces_to_faces(), cloth_build_springs(), customdata_compare(), cutEdges(), dm_calc_normal(), explodeMesh(), get_tface_mesh_marked_edge_info(), laplacian_system_construct_end(), make_edges_mdata(), mesh_to_curve(), newReebGraph(), select_linked_tfaces_with_seams(), sph_springhash_build(), and ss_sync_from_uv().
int BLI_edgehash_size (EdgeHash * eh)
Definition at line 161 of file edgehash.c.
References EdgeHash::nentries.
Referenced by BKE_mesh_calc_edges(), CDDM_calc_edges(), and CDDM_calc_edges_tessface().
void BLI_edgehashIterator_free (EdgeHashIterator * ehi)
Definition at line 220 of file edgehash.c.
References MEM_freeN().
Referenced by applyModifier(), BKE_mesh_calc_edges(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cutEdges(), dm_calc_normal(), and explodeMesh().
void BLI_edgehashIterator_getKey (EdgeHashIterator * ehi, unsigned int * v0_r, unsigned int * v1_r)
Definition at line 225 of file edgehash.c.
References EdgeHashIterator::curEntry, EdgeEntry::v0, and EdgeEntry::v1.
Referenced by applyModifier(), BKE_mesh_calc_edges(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cutEdges(), dm_calc_normal(), and explodeMesh().
void* BLI_edgehashIterator_getValue (EdgeHashIterator * ehi)
Definition at line 232 of file edgehash.c.
References EdgeHashIterator::curEntry, NULL, and EdgeEntry::val.
Referenced by applyModifier(), BKE_mesh_calc_edges(), CDDM_calc_edges(), cutEdges(), dm_calc_normal(), and explodeMesh().
int BLI_edgehashIterator_isDone (EdgeHashIterator * ehi)
Definition at line 258 of file edgehash.c.
References EdgeHashIterator::curEntry.
Referenced by applyModifier(), BKE_mesh_calc_edges(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cutEdges(), dm_calc_normal(), and explodeMesh().
EdgeHashIterator* BLI_edgehashIterator_new (EdgeHash * eh)
Create a new EdgeHashIterator. The hash table must not be mutated while the iterator is in use, and the iterator will step exactly BLI_edgehash_size(gh) times before becoming done.
Definition at line 206 of file edgehash.c.
References EdgeHash::buckets, EdgeHashIterator::curBucket, EdgeHashIterator::curEntry, EdgeHashIterator::eh, MEM_mallocN(), EdgeHash::nbuckets, and NULL.
Referenced by applyModifier(), BKE_mesh_calc_edges(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cutEdges(), dm_calc_normal(), and explodeMesh().
void BLI_edgehashIterator_setValue (EdgeHashIterator * ehi, void * val)
Definition at line 237 of file edgehash.c.
References EdgeHashIterator::curEntry, and EdgeEntry::val.
Referenced by BKE_mesh_calc_edges(), CDDM_calc_edges(), cutEdges(), and explodeMesh().
void BLI_edgehashIterator_step (EdgeHashIterator * ehi)
Definition at line 244 of file edgehash.c.
References EdgeHash::buckets, EdgeHashIterator::curBucket, EdgeHashIterator::curEntry, EdgeHashIterator::eh, EdgeHash::nbuckets, and EdgeEntry::next.
Referenced by applyModifier(), BKE_mesh_calc_edges(), CDDM_calc_edges(), CDDM_calc_edges_tessface(), cutEdges(), dm_calc_normal(), and explodeMesh().
Variable Documentation
unsigned int _ehash_hashsizes[] [static]
Initial value:
 {
    1, 3, 5, 11, 17, 37, 67, 131, 257, 521, 1031, 2053, 4099, 8209,
    16411, 32771, 65537, 131101, 262147, 524309, 1048583, 2097169,
    4194319, 8388617, 16777259, 33554467, 67108879, 134217757,
    268435459
}
Definition at line 44 of file edgehash.c.
Referenced by BLI_edgehash_insert(), and BLI_edgehash_new().