Blender: LOD_ManMesh2 Class Reference
LOD_ManMesh2 Class Reference
#include <LOD_ManMesh2.h>
Public Member Functions
bool SetVertices (MEM_SmartPtr< std::vector< LOD_Vertex > > verts)
void AddTriangle (int verts[3])
void ConnectTriangle (LOD_FaceInd fi, std::vector< LOD_EdgeInd > &new_edges)
std::vector< LOD_Vertex > & VertexSet () const
std::vector< LOD_TriFace > & FaceSet () const
std::vector< LOD_Edge > & EdgeSet () const
~LOD_ManMesh2 ()
void FaceVertices (LOD_FaceInd f, std::vector< LOD_VertexInd > &output)
void FaceEdges (LOD_FaceInd f, std::vector< LOD_EdgeInd > &output)
void EdgeVertices (LOD_EdgeInd e, std::vector< LOD_VertexInd > &output)
void EdgeFaces (LOD_EdgeInd e, std::vector< LOD_FaceInd > &output)
void VertexEdges (LOD_VertexInd v, std::vector< LOD_EdgeInd > &output)
void VertexFaces (LOD_VertexInd v, std::vector< LOD_FaceInd > &output)
void SetBBox (MT_Vector3 bbox_min, MT_Vector3 bbox_max)
MT_Vector3 BBoxMin () const
MT_Vector3 BBoxMax () const
void DeleteVertex (LOD_ExternBufferEditor &extern_editor, LOD_VertexInd v)
void DeleteEdge (LOD_EdgeInd e, CTR_UHeap< LOD_Edge > *heap)
void DeleteFace (LOD_ExternBufferEditor &extern_editor, LOD_FaceInd f)
void SC_TriFace (LOD_FaceInd f)
void SC_EdgeList (LOD_EdgeInd e)
bool SC_UniqueEdge (LOD_EdgeInd e)
Static Public Member Functions
static LOD_ManMesh2 * New ()
Detailed Description
Definition at line 44 of file LOD_ManMesh2.h.
Constructor & Destructor Documentation
LOD_ManMesh2::~LOD_ManMesh2 ()
Definition at line 249 of file LOD_ManMesh2.cpp.
Member Function Documentation
void LOD_ManMesh2::AddTriangle (int verts[3])
Definition at line 109 of file LOD_ManMesh2.cpp.
References LOD_TriFace::m_verts, and MT_assert.
Referenced by LOD_LoadMesh().
MT_Vector3 LOD_ManMesh2::BBoxMax () const [inline]
Definition at line 153 of file LOD_ManMesh2.h.
MT_Vector3 LOD_ManMesh2::BBoxMin () const [inline]
Definition at line 147 of file LOD_ManMesh2.h.
void LOD_ManMesh2::ConnectTriangle (LOD_FaceInd fi, std::vector< LOD_EdgeInd > & new_edges)
Definition at line 205 of file LOD_ManMesh2.cpp.
References FaceSet(), LOD_TriFace::m_verts, and MT_assert.
void LOD_ManMesh2::DeleteEdge (LOD_EdgeInd e, CTR_UHeap< LOD_Edge > * heap)
Definition at line 524 of file LOD_ManMesh2.cpp.
References EdgeSet(), EdgeVertices(), CTR_UHeap< HeapType >::HeapVector(), MT_assert, and VertexSet().
void LOD_ManMesh2::DeleteFace (LOD_ExternBufferEditor & extern_editor, LOD_FaceInd f)
Definition at line 563 of file LOD_ManMesh2.cpp.
References LOD_ExternBufferEditor::CopyBackFace(), EdgeSet(), FaceEdges(), and FaceSet().
void LOD_ManMesh2::DeleteVertex (LOD_ExternBufferEditor & extern_editor, LOD_VertexInd v)
Definition at line 463 of file LOD_ManMesh2.cpp.
References LOD_ExternBufferEditor::CopyBackVertex(), LOD_ExternBufferEditor::CopyModifiedFaces(), EdgeSet(), FaceSet(), VertexEdges(), VertexFaces(), and VertexSet().
void LOD_ManMesh2::EdgeFaces (LOD_EdgeInd e, std::vector< LOD_FaceInd > & output)
Definition at line 438 of file BSP_CSGMesh.cpp.
References BSP_CSGMesh::EdgeSet().
vector< LOD_Edge > & LOD_ManMesh2::EdgeSet () const
Definition at line 243 of file LOD_ManMesh2.cpp.
References MEM_SmartPtr< T >::Ref().
Referenced by LOD_QuadricEditor::BuildQuadrics(), LOD_NdQuadricEditor::BuildQuadrics(), LOD_QuadricEditor::ComputeEdgeCosts(), DeleteEdge(), DeleteFace(), DeleteVertex(), LOD_NdQuadricEditor::InitializeHeapKeys(), and SC_EdgeList().
void LOD_ManMesh2::EdgeVertices (LOD_EdgeInd e, std::vector< LOD_VertexInd > & output)
Definition at line 427 of file BSP_CSGMesh.cpp.
References BSP_CSGMesh::EdgeSet().
Referenced by DeleteEdge().
void LOD_ManMesh2::FaceEdges (LOD_FaceInd f, std::vector< LOD_EdgeInd > & output)
Definition at line 379 of file BSP_CSGMesh.cpp.
References e_mesh_error, BSP_CSGMesh::EdgeSet(), BSP_CSGMesh::FaceSet(), i, BSP_MFace::m_verts, MT_assert, and BSP_CSGMesh::VertexEdges().
Referenced by DeleteFace().
vector< LOD_TriFace > & LOD_ManMesh2::FaceSet () const
Definition at line 236 of file LOD_ManMesh2.cpp.
References MEM_SmartPtr< T >::Ref().
Referenced by LOD_FaceNormalEditor::BuildNormals(), LOD_ExternNormalEditor::BuildNormals(), LOD_QuadricEditor::BuildQuadrics(), LOD_NdQuadricEditor::BuildQuadrics(), ConnectTriangle(), LOD_ExternBufferEditor::CopyModifiedFaces(), DeleteFace(), DeleteVertex(), LOD_ExternNormalEditor::New(), LOD_FaceNormalEditor::New(), LOD_ExternNormalEditor::Update(), and LOD_FaceNormalEditor::Update().
void LOD_ManMesh2::FaceVertices (LOD_FaceInd f, std::vector< LOD_VertexInd > & output)
Definition at line 364 of file BSP_CSGMesh.cpp.
References BSP_CSGMesh::FaceSet().
LOD_ManMesh2 * LOD_ManMesh2::New () [static]
Definition at line 56 of file LOD_ManMesh2.cpp.
References NULL, and MEM_SmartPtr< T >::Release().
Referenced by LOD_DecimationClass::New().
void LOD_ManMesh2::SC_EdgeList (LOD_EdgeInd e)
Definition at line 447 of file LOD_ManMesh2.cpp.
References EdgeSet(), MT_assert, and VertexSet().
void LOD_ManMesh2::SC_TriFace (LOD_FaceInd f)
Definition at line 427 of file LOD_ManMesh2.cpp.
References LOD_TriFace::m_verts, and MT_assert.
bool LOD_ManMesh2::SC_UniqueEdge (LOD_EdgeInd e)
void LOD_ManMesh2::SetBBox (MT_Vector3 bbox_min, MT_Vector3 bbox_max)
Definition at line 417 of file LOD_ManMesh2.cpp.
bool LOD_ManMesh2::SetVertices (MEM_SmartPtr< std::vector< LOD_Vertex > > verts)
Definition at line 119 of file BSP_CSGMesh.cpp.
References NULL.
Referenced by LOD_LoadMesh().
void LOD_ManMesh2::VertexEdges (LOD_VertexInd v, std::vector< LOD_EdgeInd > & output)
Definition at line 457 of file BSP_CSGMesh.cpp.
References BSP_CSGMesh::VertexSet().
Referenced by DeleteVertex().
void LOD_ManMesh2::VertexFaces (LOD_VertexInd v, std::vector< LOD_FaceInd > & output)
Definition at line 472 of file BSP_CSGMesh.cpp.
References BSP_CSGMesh::EdgeSet(), BSP_CSGMesh::FaceSet(), BSP_MEdge::m_faces, and BSP_CSGMesh::VertexSet().
Referenced by DeleteVertex().
vector< LOD_Vertex > & LOD_ManMesh2::VertexSet () const
Definition at line 229 of file LOD_ManMesh2.cpp.
References MEM_SmartPtr< T >::Ref().
Referenced by LOD_FaceNormalEditor::BuildNormals(), LOD_QuadricEditor::BuildQuadrics(), LOD_NdQuadricEditor::BuildQuadrics(), LOD_MeshBounds::ComputeBounds(), LOD_ExternBufferEditor::CopyModifiedVerts(), DeleteEdge(), DeleteVertex(), LOD_FaceNormalEditor::New(), SC_EdgeList(), LOD_QuadricEditor::TargetVertex(), and LOD_NdQuadricEditor::TargetVertex().
The documentation for this class was generated from the following files:
LOD_ManMesh2.h
BSP_CSGMesh.cpp
LOD_ManMesh2.cpp