Blender: AUD_RectifyFactory Class Reference
AUD_RectifyFactory Class Reference
#include <AUD_RectifyFactory.h>
Public Member Functions
AUD_RectifyFactory (AUD_Reference< AUD_IFactory > factory)
virtual AUD_Reference
< AUD_IReader > createReader ()
Static Public Member Functions
static sample_t rectifyFilter (AUD_CallbackIIRFilterReader *reader, void *useless)
Detailed Description
This factory rectifies another factory.
Definition at line 39 of file AUD_RectifyFactory.h.
Constructor & Destructor Documentation
AUD_RectifyFactory::AUD_RectifyFactory (AUD_Reference< AUD_IFactory > factory)
Creates a new rectify factory.
Parameters:
factory The input factory.
Definition at line 40 of file AUD_RectifyFactory.cpp.
Member Function Documentation
AUD_Reference< AUD_IReader > AUD_RectifyFactory::createReader () [virtual]
Creates a reader for playback of the sound source.
Returns:
A pointer to an AUD_IReader object or NULL if there has been an error.
Exceptions:
AUD_Exception An exception may be thrown if there has been a more unexpected error during reader creation.
Implements AUD_IFactory.
Definition at line 45 of file AUD_RectifyFactory.cpp.
References AUD_EffectFactory::getReader(), and rectifyFilter().
sample_t AUD_RectifyFactory::rectifyFilter (AUD_CallbackIIRFilterReader * reader, void * useless) [static]
Definition at line 35 of file AUD_RectifyFactory.cpp.
References fabs(), and AUD_BaseIIRFilterReader::x().
Referenced by createReader().
The documentation for this class was generated from the following files:
AUD_RectifyFactory.h
AUD_RectifyFactory.cpp