Blender: KX_ISceneConverter Class Reference
KX_ISceneConverter Class Reference
#include <KX_ISceneConverter.h>
Public Member Functions
KX_ISceneConverter ()
virtual ~KX_ISceneConverter ()
virtual void ConvertScene (class KX_Scene *destinationscene, class RAS_IRenderTools *rendertools, class RAS_ICanvas *canvas)=0
virtual void RemoveScene (class KX_Scene *scene)=0
virtual void SetAlwaysUseExpandFraming (bool to_what)=0
virtual void SetNewFileName (const STR_String &filename)=0
virtual bool TryAndLoadNewFile ()=0
virtual void ResetPhysicsObjectsAnimationIpo (bool clearIpo)=0
virtual void WritePhysicsObjectToAnimationIpo (int frameNumber)=0
this generates ipo curves for position, rotation, allowing to use game physics in animation
virtual void TestHandlesPhysicsObjectToAnimationIpo ()=0
virtual void resetNoneDynamicObjectToIpo ()=0
this is for reseting the position,rotation and scale of the gameobjet that is not dynamic
virtual void SetMaterials (bool val)=0
virtual bool GetMaterials ()=0
virtual void SetGLSLMaterials (bool val)=0
virtual bool GetGLSLMaterials ()=0
virtual struct Scene * GetBlenderSceneForName (const STR_String &name)=0
Public Attributes
bool addInitFromFrame
Detailed Description
Definition at line 44 of file KX_ISceneConverter.h.
Constructor & Destructor Documentation
KX_ISceneConverter::KX_ISceneConverter () [inline]
Definition at line 48 of file KX_ISceneConverter.h.
virtual KX_ISceneConverter::~KX_ISceneConverter () [inline, virtual]
Definition at line 49 of file KX_ISceneConverter.h.
Member Function Documentation
virtual void KX_ISceneConverter::ConvertScene (class KX_Scene * destinationscene, class RAS_IRenderTools * rendertools, class RAS_ICanvas * canvas) [pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by KX_KetsjiEngine::CreateScene(), GPG_Application::startEngine(), and StartKetsjiShell().
virtual struct Scene* KX_ISceneConverter::GetBlenderSceneForName (const STR_String & name) [read, pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by KX_KetsjiEngine::CreateScene().
virtual bool KX_ISceneConverter::GetGLSLMaterials () [pure virtual]
Implemented in KX_BlenderSceneConverter.
virtual bool KX_ISceneConverter::GetMaterials () [pure virtual]
Implemented in KX_BlenderSceneConverter.
virtual void KX_ISceneConverter::RemoveScene (class KX_Scene * scene) [pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by KX_KetsjiEngine::RemoveScheduledScenes(), KX_KetsjiEngine::ReplaceScheduledScenes(), and KX_KetsjiEngine::StopEngine().
virtual void KX_ISceneConverter::resetNoneDynamicObjectToIpo () [pure virtual]
this is for reseting the position,rotation and scale of the gameobjet that is not dynamic
Implemented in KX_BlenderSceneConverter.
Referenced by KX_KetsjiEngine::NextFrame().
virtual void KX_ISceneConverter::ResetPhysicsObjectsAnimationIpo (bool clearIpo) [pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by KX_KetsjiEngine::StartEngine().
virtual void KX_ISceneConverter::SetAlwaysUseExpandFraming (bool to_what) [pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by StartKetsjiShell().
virtual void KX_ISceneConverter::SetGLSLMaterials (bool val) [pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by GPG_Application::startEngine(), and StartKetsjiShell().
virtual void KX_ISceneConverter::SetMaterials (bool val) [pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by GPG_Application::startEngine(), and StartKetsjiShell().
virtual void KX_ISceneConverter::SetNewFileName (const STR_String & filename) [pure virtual]
Implemented in KX_BlenderSceneConverter.
virtual void KX_ISceneConverter::TestHandlesPhysicsObjectToAnimationIpo () [pure virtual]
Implemented in KX_BlenderSceneConverter.
Referenced by KX_KetsjiEngine::StopEngine().
virtual bool KX_ISceneConverter::TryAndLoadNewFile () [pure virtual]
Implemented in KX_BlenderSceneConverter.
virtual void KX_ISceneConverter::WritePhysicsObjectToAnimationIpo (int frameNumber) [pure virtual]
this generates ipo curves for position, rotation, allowing to use game physics in animation
Implemented in KX_BlenderSceneConverter.
Referenced by KX_KetsjiEngine::NextFrame(), and KX_KetsjiEngine::StartEngine().
Member Data Documentation
bool KX_ISceneConverter::addInitFromFrame
Definition at line 68 of file KX_ISceneConverter.h.
Referenced by bl_ConvertBlenderObject_Single(), BL_ConvertBlenderObjects(), KX_BlenderSceneConverter::resetNoneDynamicObjectToIpo(), and StartKetsjiShell().
The documentation for this class was generated from the following file:
KX_ISceneConverter.h