Blender: script_edit.c File Reference
script_edit.c File Reference
script space
#include <string.h>
#include <stdio.h>
#include "BLI_blenlib.h"
#include "BLI_utildefines.h"
#include "BKE_context.h"
#include "WM_api.h"
#include "WM_types.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "ED_screen.h"
#include "script_intern.h"
Functions
static int run_pyfile_exec (bContext *C, wmOperator *op)
void SCRIPT_OT_python_file_run (wmOperatorType *ot)
static int script_reload_exec (bContext *C, wmOperator *UNUSED(op))
void SCRIPT_OT_reload (wmOperatorType *ot)
Detailed Description
Definition in file script_edit.c.
Function Documentation
static int run_pyfile_exec (bContext * C, wmOperator * op) [static]
Definition at line 55 of file script_edit.c.
References BPY_filepath_exec(), CTX_wm_region(), ED_region_tag_redraw(), OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, and RNA_string_get().
Referenced by SCRIPT_OT_python_file_run().
void SCRIPT_OT_python_file_run (wmOperatorType * ot)
Definition at line 71 of file script_edit.c.
References wmOperatorType::description, ED_operator_areaactive(), wmOperatorType::exec, FILE_MAX, wmOperatorType::flag, wmOperatorType::idname, wmOperatorType::name, OPTYPE_UNDO, wmOperatorType::poll, RNA_def_string_file_path(), run_pyfile_exec(), and wmOperatorType::srna.
Referenced by script_operatortypes().
void SCRIPT_OT_reload (wmOperatorType * ot)
Definition at line 103 of file script_edit.c.
References wmOperatorType::description, wmOperatorType::exec, wmOperatorType::idname, wmOperatorType::name, and script_reload_exec().
Referenced by script_operatortypes().
static int script_reload_exec (bContext * C, wmOperator * UNUSEDop) [static]
Definition at line 87 of file script_edit.c.
References BPY_string_exec(), NC_WINDOW, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, WM_cursor_wait(), and WM_event_add_notifier().
Referenced by SCRIPT_OT_reload().