Blender: editmesh_slide.c File Reference
editmesh_slide.c File Reference
mesh
#include "DNA_object_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_array.h"
#include "BLI_math.h"
#include "BKE_context.h"
#include "BKE_report.h"
#include "BKE_tessmesh.h"
#include "BIF_gl.h"
#include "BIF_glutil.h"
#include "ED_screen.h"
#include "ED_view3d.h"
#include "ED_mesh.h"
#include "ED_space_api.h"
#include "UI_resources.h"
#include "RNA_access.h"
#include "RNA_define.h"
#include "WM_api.h"
#include "WM_types.h"
#include "mesh_intern.h"
Classes
struct VertexSlideOp
Defines
#define VTX_SLIDE_SNAP_THRSH 15
Typedefs
typedef struct VertexSlideOp VertexSlideOp
Functions
static void vtx_slide_draw (const bContext *C, ARegion *ar, void *arg)
static int edbm_vertex_slide_exec (bContext *C, wmOperator *op)
static void vtx_slide_exit (const bContext *C, wmOperator *op)
static int vtx_slide_set_frame (VertexSlideOp *vso)
static int vtx_slide_init (bContext *C, wmOperator *op)
static void vtx_slide_confirm (bContext *C, wmOperator *op)
static void vtx_slide_draw (const bContext *C, ARegion *UNUSED(ar), void *arg)
static BMEdge * vtx_slide_nrst_in_frame (VertexSlideOp *vso, const float mval[2])
static void vtx_slide_find_edge (VertexSlideOp *vso, wmEvent *event)
static void vtx_slide_update (VertexSlideOp *vso, wmEvent *event)
static int edbm_vertex_slide_modal (bContext *C, wmOperator *op, wmEvent *event)
static int edbm_vertex_slide_cancel (bContext *C, wmOperator *op)
static int edbm_vertex_slide_invoke (bContext *C, wmOperator *op, wmEvent *UNUSED(event))
void MESH_OT_vert_slide (wmOperatorType *ot)
Detailed Description
Definition in file editmesh_slide.c.
Define Documentation
#define VTX_SLIDE_SNAP_THRSH 15
Definition at line 58 of file editmesh_slide.c.
Referenced by vtx_slide_update().
Typedef Documentation
typedef struct VertexSlideOp VertexSlideOp
Function Documentation
static int edbm_vertex_slide_cancel (bContext * C, wmOperator * op) [static]
Definition at line 628 of file editmesh_slide.c.
References OPERATOR_CANCELLED, and vtx_slide_exit().
Referenced by MESH_OT_vert_slide().
static int edbm_vertex_slide_exec (bContext * C, wmOperator * op) [static]
Definition at line 646 of file editmesh_slide.c.
References BKE_report(), BMEditMesh::bm, BM_ALL, BM_EDGE, BM_edge_select_set(), BM_ELEM_SELECT, BM_select_history_store, BM_VERT, BM_vert_select_set(), BMEdit_FromObject(), BMO_op_exec(), BMO_slot_buffer_hflag_disable(), BMO_slot_buffer_hflag_enable(), CTX_data_edit_object(), wmOperator::customdata, VertexSlideOp::distance, EDBM_flag_disable_all(), EDBM_op_finish(), EDBM_op_init(), EDBM_selectmode_flush(), EDBM_update_generic(), edbm_vertex_slide_modal(), BMEditSelection::ele, BMEditSelection::htype, if(), ListBase::last, wmOperatorType::modal, NULL, OPERATOR_CANCELLED, OPERATOR_FINISHED, wmOperator::ptr, wmOperator::reports, RNA_float_get(), RNA_float_set(), RPT_ERROR_INVALID_INPUT, VertexSlideOp::sel_edge, BMesh::selected, VertexSlideOp::start_vtx, BMesh::totedgesel, TRUE, and wmOperator::type.
Referenced by vtx_slide_confirm().
static int edbm_vertex_slide_invoke (bContext * C, wmOperator * op, wmEvent * UNUSEDevent) [static]
Definition at line 636 of file editmesh_slide.c.
References OPERATOR_CANCELLED, OPERATOR_RUNNING_MODAL, and vtx_slide_init().
Referenced by MESH_OT_vert_slide().
static int edbm_vertex_slide_modal (bContext * C, wmOperator * op, wmEvent * event) [static]
Definition at line 526 of file editmesh_slide.c.
References VertexSlideOp::active_region, copy_v2_v2_int(), CTX_wm_area(), wmOperator::customdata, VertexSlideOp::distance, ED_area_headerprint(), ED_region_tag_redraw(), FALSE, KM_PRESS, KM_RELEASE, LEFTALTKEY, LEFTCTRLKEY, LEFTMOUSE, LEFTSHIFTKEY, VertexSlideOp::m_co, MOUSEMOVE, wmEvent::mval, OPERATOR_CANCELLED, OPERATOR_FINISHED, OPERATOR_RUNNING_MODAL, RIGHTMOUSE, VertexSlideOp::sel_edge, VertexSlideOp::slide_mode, VertexSlideOp::snap_n_merge, VertexSlideOp::snap_to_end_vtx, VertexSlideOp::snap_to_mid, TRUE, wmEvent::type, wmEvent::val, view3d_operator_needs_opengl(), vtx_slide_confirm(), vtx_slide_exit(), vtx_slide_find_edge(), and vtx_slide_update().
Referenced by edbm_vertex_slide_exec(), and MESH_OT_vert_slide().
void MESH_OT_vert_slide (wmOperatorType * ot)
Definition at line 716 of file editmesh_slide.c.
References wmOperatorType::cancel, wmOperatorType::description, ED_operator_editmesh_region_view3d(), edbm_vertex_slide_cancel(), edbm_vertex_slide_invoke(), edbm_vertex_slide_modal(), wmOperatorType::flag, FLT_MAX, wmOperatorType::idname, wmOperatorType::invoke, wmOperatorType::modal, wmOperatorType::name, OPTYPE_REGISTER, OPTYPE_UNDO, wmOperatorType::poll, PROP_SKIP_SAVE, RNA_def_float(), RNA_def_property_flag(), RNA_def_property_ui_range(), and wmOperatorType::srna.
Referenced by ED_operatortypes_mesh().
static void vtx_slide_confirm (bContext * C, wmOperator * op) [static]
Definition at line 193 of file editmesh_slide.c.
References VertexSlideOp::active_region, BMEditMesh::bm, BM_edge_other_vert(), BM_edge_select_set(), BM_ELEM_SELECT, BM_select_history_store, BM_vert_select_set(), BMEdit_FromObject(), BMVert::co, wmOperator::customdata, ED_region_tag_redraw(), EDBM_flag_disable_all(), EDBM_op_callf(), EDBM_selectmode_flush(), EDBM_update_generic(), edbm_vertex_slide_exec(), VertexSlideOp::interp, len_v3v3(), VertexSlideOp::obj, VertexSlideOp::sel_edge, VertexSlideOp::snap_n_merge, VertexSlideOp::start_vtx, and TRUE.
Referenced by edbm_vertex_slide_modal().
static void vtx_slide_draw (const bContext * C, ARegion * ar, void * arg) [static]
Referenced by vtx_slide_init().
static void vtx_slide_draw (const bContext * C, ARegion * UNUSEDar, void * arg) [static]
Definition at line 273 of file editmesh_slide.c.
References bglBegin(), bglEnd(), bglVertex3fv(), BMVert::co, CTX_wm_view3d(), VertexSlideOp::disk_edges, glMultMatrixf, i, VertexSlideOp::interp, VertexSlideOp::obj, Object::obmat, VertexSlideOp::sel_edge, VertexSlideOp::slide_mode, TH_EDGE_SELECT, TH_FACE_DOT, TH_FACEDOT_SIZE, TH_OUTLINE_WIDTH, UI_GetThemeValuef(), UI_ThemeColorShadeAlpha(), BMEdge::v1, BMEdge::v2, VertexSlideOp::vtx_frame, and View3D::zbuf.
static void vtx_slide_exit (const bContext * C, wmOperator * op) [static]
Definition at line 236 of file editmesh_slide.c.
References VertexSlideOp::active_region, CTX_wm_area(), wmOperator::customdata, VertexSlideOp::draw_handle, ED_area_headerprint(), ED_region_draw_cb_exit(), VertexSlideOp::edge_frame, FALSE, MEM_freeN(), NULL, VertexSlideOp::slide_mode, ARegion::type, VertexSlideOp::view_context, and VertexSlideOp::vtx_frame.
Referenced by edbm_vertex_slide_cancel(), edbm_vertex_slide_modal(), and vtx_slide_init().
static void vtx_slide_find_edge (VertexSlideOp * vso, wmEvent * event) [static]
Definition at line 372 of file editmesh_slide.c.
References BM_vert_in_edge(), copy_v2_v2_int(), VertexSlideOp::m_co, ViewContext::mval, wmEvent::mval, NULL, VertexSlideOp::sel_edge, VertexSlideOp::start_vtx, VertexSlideOp::view_context, and vtx_slide_nrst_in_frame().
Referenced by edbm_vertex_slide_modal().
static int vtx_slide_init (bContext * C, wmOperator * op) [static]
Definition at line 106 of file editmesh_slide.c.
References VertexSlideOp::active_region, BKE_report(), BMEditMesh::bm, BM_EDGE, BM_VERT, BMEdit_FromObject(), CTX_data_edit_object(), CTX_wm_area(), CTX_wm_region(), wmOperator::customdata, VertexSlideOp::disk_edges, VertexSlideOp::distance, VertexSlideOp::draw_handle, ED_area_headerprint(), ED_region_draw_cb_activate(), ED_region_tag_redraw(), EDBM_selectmode_flush(), VertexSlideOp::edge_frame, BMEditSelection::ele, em_setup_viewcontext(), FALSE, BMEditSelection::htype, ListBase::last, MEM_callocN(), NULL, VertexSlideOp::obj, REGION_DRAW_POST_VIEW, wmOperator::reports, RPT_ERROR, RPT_ERROR_INVALID_INPUT, VertexSlideOp::sel_edge, BMesh::selected, VertexSlideOp::slide_mode, VertexSlideOp::snap_n_merge, VertexSlideOp::snap_threshold, VertexSlideOp::snap_to_end_vtx, VertexSlideOp::snap_to_mid, VertexSlideOp::start_vtx, TRUE, ARegion::type, view3d_operator_needs_opengl(), VertexSlideOp::view_context, VertexSlideOp::vtx_frame, vtx_slide_draw(), vtx_slide_exit(), vtx_slide_set_frame(), and WM_event_add_modal_handler().
Referenced by edbm_vertex_slide_invoke().
static BMEdge* vtx_slide_nrst_in_frame (VertexSlideOp * vso, const float mval[2]) [static]
Definition at line 342 of file editmesh_slide.c.
References VertexSlideOp::active_region, BMVert::co, VertexSlideOp::disk_edges, dist_to_line_segment_v2(), VertexSlideOp::edge_frame, FLT_MAX, i, mul_v3_m4v3(), NULL, VertexSlideOp::obj, Object::obmat, project_float_noclip(), BMEdge::v1, and BMEdge::v2.
Referenced by vtx_slide_find_edge().
static int vtx_slide_set_frame (VertexSlideOp * vso) [static]
Definition at line 480 of file editmesh_slide.c.
References BLI_array_append, BLI_array_declare, BLI_array_growone, BM_edge_other_vert(), BM_EDGES_OF_VERT, BM_ITER_ELEM_INDEX, BMVert::co, copy_v3_v3(), VertexSlideOp::disk_edges, VertexSlideOp::edge_frame, VertexSlideOp::interp, MEM_freeN(), NULL, VertexSlideOp::start_vtx, and VertexSlideOp::vtx_frame.
Referenced by vtx_slide_init().
static void vtx_slide_update (VertexSlideOp * vso, wmEvent * event) [static]
Definition at line 399 of file editmesh_slide.c.
References VertexSlideOp::active_region, BM_edge_other_vert(), closest_to_line_v2(), BMVert::co, copy_v3_v3(), VertexSlideOp::distance, interp(), VertexSlideOp::interp, interp_v3_v3v3(), len_v3v3(), line_point_factor_v2(), mul_v3_m4v3(), wmEvent::mval, VertexSlideOp::obj, Object::obmat, project_float_noclip(), VertexSlideOp::sel_edge, VertexSlideOp::snap_threshold, VertexSlideOp::snap_to_end_vtx, VertexSlideOp::snap_to_mid, VertexSlideOp::start_vtx, BMEdge::v1, BMEdge::v2, and VTX_SLIDE_SNAP_THRSH.
Referenced by edbm_vertex_slide_modal().