Blender: btGImpactCollisionAlgorithm Class Reference
btGImpactCollisionAlgorithm Class Reference
Collision Algorithm for GImpact Shapes.
#include <btGImpactCollisionAlgorithm.h>
Classes
struct CreateFunc
Protected Member Functions
SIMD_FORCE_INLINE
btPersistentManifold * newContactManifold (btCollisionObject *body0, btCollisionObject *body1)
Creates a new contact point.
SIMD_FORCE_INLINE void destroyConvexAlgorithm ()
SIMD_FORCE_INLINE void destroyContactManifolds ()
SIMD_FORCE_INLINE void clearCache ()
SIMD_FORCE_INLINE
btPersistentManifold * getLastManifold ()
SIMD_FORCE_INLINE void checkManifold (btCollisionObject *body0, btCollisionObject *body1)
SIMD_FORCE_INLINE
btCollisionAlgorithm * newAlgorithm (btCollisionObject *body0, btCollisionObject *body1)
SIMD_FORCE_INLINE void checkConvexAlgorithm (btCollisionObject *body0, btCollisionObject *body1)
void addContactPoint (btCollisionObject *body0, btCollisionObject *body1, const btVector3 &point, const btVector3 &normal, btScalar distance)
Protected Attributes
btCollisionAlgorithm * m_convex_algorithm
btPersistentManifold * m_manifoldPtr
btManifoldResult * m_resultOut
const btDispatcherInfo * m_dispatchInfo
int m_triface0
int m_part0
int m_triface1
int m_part1
void collide_gjk_triangles (btCollisionObject *body0, btCollisionObject *body1, btGImpactMeshShapePart *shape0, btGImpactMeshShapePart *shape1, const int *pairs, int pair_count)
void collide_sat_triangles (btCollisionObject *body0, btCollisionObject *body1, btGImpactMeshShapePart *shape0, btGImpactMeshShapePart *shape1, const int *pairs, int pair_count)
void shape_vs_shape_collision (btCollisionObject *body0, btCollisionObject *body1, btCollisionShape *shape0, btCollisionShape *shape1)
void convex_vs_convex_collision (btCollisionObject *body0, btCollisionObject *body1, btCollisionShape *shape0, btCollisionShape *shape1)
void gimpact_vs_gimpact_find_pairs (const btTransform &trans0, const btTransform &trans1, btGImpactShapeInterface *shape0, btGImpactShapeInterface *shape1, btPairSet &pairset)
void gimpact_vs_shape_find_pairs (const btTransform &trans0, const btTransform &trans1, btGImpactShapeInterface *shape0, btCollisionShape *shape1, btAlignedObjectArray< int > &collided_primitives)
void gimpacttrimeshpart_vs_plane_collision (btCollisionObject *body0, btCollisionObject *body1, btGImpactMeshShapePart *shape0, btStaticPlaneShape *shape1, bool swapped)
btGImpactCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo &ci, btCollisionObject *body0, btCollisionObject *body1)
virtual ~btGImpactCollisionAlgorithm ()
virtual void processCollision (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
btScalar calculateTimeOfImpact (btCollisionObject *body0, btCollisionObject *body1, const btDispatcherInfo &dispatchInfo, btManifoldResult *resultOut)
virtual void getAllContactManifolds (btManifoldArray &manifoldArray)
void gimpact_vs_gimpact (btCollisionObject *body0, btCollisionObject *body1, btGImpactShapeInterface *shape0, btGImpactShapeInterface *shape1)
Collides two gimpact shapes.
void gimpact_vs_shape (btCollisionObject *body0, btCollisionObject *body1, btGImpactShapeInterface *shape0, btCollisionShape *shape1, bool swapped)
void gimpact_vs_compoundshape (btCollisionObject *body0, btCollisionObject *body1, btGImpactShapeInterface *shape0, btCompoundShape *shape1, bool swapped)
void gimpact_vs_concave (btCollisionObject *body0, btCollisionObject *body1, btGImpactShapeInterface *shape0, btConcaveShape *shape1, bool swapped)
void setFace0 (int value)
Accessor/Mutator pairs for Part and triangleID.
int getFace0 ()
void setFace1 (int value)
int getFace1 ()
void setPart0 (int value)
int getPart0 ()
void setPart1 (int value)
int getPart1 ()
static void registerAlgorithm (btCollisionDispatcher *dispatcher)
Use this function for register the algorithm externally.
Detailed Description
Collision Algorithm for GImpact Shapes.
For register this algorithm in Bullet, proceed as following:
btCollisionDispatcher * dispatcher = static_cast<btCollisionDispatcher *>(m_dynamicsWorld ->getDispatcher());
btGImpactCollisionAlgorithm::registerAlgorithm(dispatcher);
Definition at line 54 of file btGImpactCollisionAlgorithm.h.
Constructor & Destructor Documentation
btGImpactCollisionAlgorithm::btGImpactCollisionAlgorithm (const btCollisionAlgorithmConstructionInfo & ci, btCollisionObject * body0, btCollisionObject * body1)
Collision routines
Definition at line 196 of file btGImpactCollisionAlgorithm.cpp.
References m_convex_algorithm, m_manifoldPtr, and NULL.
Referenced by btGImpactCollisionAlgorithm::CreateFunc::CreateCollisionAlgorithm().
btGImpactCollisionAlgorithm::~btGImpactCollisionAlgorithm () [virtual]
Collision routines
Definition at line 203 of file btGImpactCollisionAlgorithm.cpp.
References clearCache().
Member Function Documentation
void btGImpactCollisionAlgorithm::addContactPoint (btCollisionObject * body0, btCollisionObject * body1, const btVector3 & point, const btVector3 & normal, btScalar distance) [protected]
Definition at line 212 of file btGImpactCollisionAlgorithm.cpp.
References btManifoldResult::addContactPoint(), checkManifold(), m_part0, m_part1, m_resultOut, m_triface0, m_triface1, btManifoldResult::setShapeIdentifiersA(), and btManifoldResult::setShapeIdentifiersB().
Referenced by collide_sat_triangles(), and gimpacttrimeshpart_vs_plane_collision().
btScalar btGImpactCollisionAlgorithm::calculateTimeOfImpact (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Collision routines
Implements btCollisionAlgorithm.
Definition at line 876 of file btGImpactCollisionAlgorithm.cpp.
SIMD_FORCE_INLINE void btGImpactCollisionAlgorithm::checkConvexAlgorithm (btCollisionObject * body0, btCollisionObject * body1) [inline, protected]
Definition at line 130 of file btGImpactCollisionAlgorithm.h.
References m_convex_algorithm, and newAlgorithm().
Referenced by convex_vs_convex_collision().
SIMD_FORCE_INLINE void btGImpactCollisionAlgorithm::checkManifold (btCollisionObject * body0, btCollisionObject * body1) [inline, protected]
Definition at line 109 of file btGImpactCollisionAlgorithm.h.
References getLastManifold(), m_resultOut, newContactManifold(), and btManifoldResult::setPersistentManifold().
Referenced by addContactPoint(), and newAlgorithm().
SIMD_FORCE_INLINE void btGImpactCollisionAlgorithm::clearCache () [inline, protected]
Definition at line 91 of file btGImpactCollisionAlgorithm.h.
References destroyContactManifolds(), destroyConvexAlgorithm(), m_part0, m_part1, m_triface0, and m_triface1.
Referenced by processCollision(), and ~btGImpactCollisionAlgorithm().
void btGImpactCollisionAlgorithm::collide_gjk_triangles (btCollisionObject * body0, btCollisionObject * body1, btGImpactMeshShapePart * shape0, btGImpactMeshShapePart * shape1, const int * pairs, int pair_count) [protected]
Collision routines
Definition at line 362 of file btGImpactCollisionAlgorithm.cpp.
References convex_vs_convex_collision(), btGImpactMeshShapePart::getBulletTriangle(), btGImpactMeshShapePart::lockChildShapes(), m_triface0, m_triface1, btTriangleShapeEx::overlap_test_conservative(), and btGImpactMeshShapePart::unlockChildShapes().
Referenced by gimpact_vs_gimpact().
void btGImpactCollisionAlgorithm::collide_sat_triangles (btCollisionObject * body0, btCollisionObject * body1, btGImpactMeshShapePart * shape0, btGImpactMeshShapePart * shape1, const int * pairs, int pair_count) [protected]
Collision routines
Definition at line 401 of file btGImpactCollisionAlgorithm.cpp.
References addContactPoint(), btPrimitiveTriangle::applyTransform(), btPrimitiveTriangle::buildTriPlane(), btPrimitiveTriangle::find_triangle_collision_clip_method(), btGImpactShapeInterface::getPrimitiveTriangle(), btGImpactMeshShapePart::lockChildShapes(), GIM_TRIANGLE_CONTACT::m_penetration_depth, GIM_TRIANGLE_CONTACT::m_point_count, GIM_TRIANGLE_CONTACT::m_points, GIM_TRIANGLE_CONTACT::m_separating_normal, m_triface0, m_triface1, btPrimitiveTriangle::overlap_test_conservative(), and btGImpactMeshShapePart::unlockChildShapes().
Referenced by gimpact_vs_gimpact().
void btGImpactCollisionAlgorithm::convex_vs_convex_collision (btCollisionObject * body0, btCollisionObject * body1, btCollisionShape * shape0, btCollisionShape * shape1) [protected]
Collision routines
Definition at line 255 of file btGImpactCollisionAlgorithm.cpp.
References checkConvexAlgorithm(), m_convex_algorithm, m_dispatchInfo, m_part0, m_part1, m_resultOut, m_triface0, m_triface1, btCollisionAlgorithm::processCollision(), btManifoldResult::setShapeIdentifiersA(), and btManifoldResult::setShapeIdentifiersB().
Referenced by collide_gjk_triangles(), and gimpact_vs_gimpact().
SIMD_FORCE_INLINE void btGImpactCollisionAlgorithm::destroyContactManifolds () [inline, protected]
Definition at line 84 of file btGImpactCollisionAlgorithm.h.
References btCollisionAlgorithm::m_dispatcher, m_manifoldPtr, NULL, and btDispatcher::releaseManifold().
Referenced by clearCache().
SIMD_FORCE_INLINE void btGImpactCollisionAlgorithm::destroyConvexAlgorithm () [inline, protected]
Definition at line 74 of file btGImpactCollisionAlgorithm.h.
References btDispatcher::freeCollisionAlgorithm(), m_convex_algorithm, btCollisionAlgorithm::m_dispatcher, NULL, and btCollisionAlgorithm::~btCollisionAlgorithm().
Referenced by clearCache().
virtual void btGImpactCollisionAlgorithm::getAllContactManifolds (btManifoldArray & manifoldArray) [inline, virtual]
Collision routines
Implements btCollisionAlgorithm.
Definition at line 207 of file btGImpactCollisionAlgorithm.h.
References m_manifoldPtr, and btAlignedObjectArray< T >::push_back().
int btGImpactCollisionAlgorithm::getFace0 () [inline]
Collision routines
Definition at line 268 of file btGImpactCollisionAlgorithm.h.
References m_triface0.
int btGImpactCollisionAlgorithm::getFace1 () [inline]
Collision routines
Definition at line 276 of file btGImpactCollisionAlgorithm.h.
References m_triface1.
SIMD_FORCE_INLINE btPersistentManifold* btGImpactCollisionAlgorithm::getLastManifold () [inline, protected]
Definition at line 102 of file btGImpactCollisionAlgorithm.h.
References m_manifoldPtr.
Referenced by checkManifold(), and newAlgorithm().
int btGImpactCollisionAlgorithm::getPart0 () [inline]
Collision routines
Definition at line 284 of file btGImpactCollisionAlgorithm.h.
References m_part0.
int btGImpactCollisionAlgorithm::getPart1 () [inline]
Collision routines
Definition at line 292 of file btGImpactCollisionAlgorithm.h.
References m_part1.
void btGImpactCollisionAlgorithm::gimpact_vs_compoundshape (btCollisionObject * body0, btCollisionObject * body1, btGImpactShapeInterface * shape0, btCompoundShape * shape1, bool swapped)
Collision routines
Definition at line 694 of file btGImpactCollisionAlgorithm.cpp.
References gimpact_vs_shape(), and i.
Referenced by gimpact_vs_shape().
void btGImpactCollisionAlgorithm::gimpact_vs_concave (btCollisionObject * body0, btCollisionObject * body1, btGImpactShapeInterface * shape0, btConcaveShape * shape1, bool swapped)
Collision routines
Definition at line 813 of file btGImpactCollisionAlgorithm.cpp.
References btGImpactTriangleCallback::algorithm, btGImpactTriangleCallback::body0, btGImpactTriangleCallback::body1, btGImpactShapeInterface::getAabb(), btConcaveShape::getMargin(), btGImpactTriangleCallback::gimpactshape0, btTransform::inverse(), btGImpactTriangleCallback::margin, btConcaveShape::processAllTriangles(), and btGImpactTriangleCallback::swapped.
Referenced by gimpact_vs_shape().
void btGImpactCollisionAlgorithm::gimpact_vs_gimpact (btCollisionObject * body0, btCollisionObject * body1, btGImpactShapeInterface * shape0, btGImpactShapeInterface * shape1)
Collides two gimpact shapes.
Precondition:
shape0 and shape1 couldn't be btGImpactMeshShape objects
Definition at line 474 of file btGImpactCollisionAlgorithm.cpp.
References btGImpactShapeInterface::childrenHasTransform(), collide_gjk_triangles(), collide_sat_triangles(), CONST_GIMPACT_TRIMESH_SHAPE, CONST_GIMPACT_TRIMESH_SHAPE_PART, convex_vs_convex_collision(), GIM_ShapeRetriever::getChildShape(), btGImpactShapeInterface::getChildTransform(), btGImpactShapeInterface::getGImpactShapeType(), btGImpactMeshShape::getMeshPart(), btGImpactMeshShape::getMeshPartCount(), gimpact_vs_gimpact_find_pairs(), i, btGImpactShapeInterface::lockChildShapes(), GIM_PAIR::m_index1, GIM_PAIR::m_index2, m_part0, m_part1, m_triface0, m_triface1, btAlignedObjectArray< T >::size(), and btGImpactShapeInterface::unlockChildShapes().
Referenced by processCollision().
void btGImpactCollisionAlgorithm::gimpact_vs_gimpact_find_pairs (const btTransform & trans0, const btTransform & trans1, btGImpactShapeInterface * shape0, btGImpactShapeInterface * shape1, btPairSet & pairset) [protected]
Collision routines
Definition at line 283 of file btGImpactCollisionAlgorithm.cpp.
References btGImpactQuantizedBvh::find_collision(), btGImpactShapeInterface::getBoxSet(), btGImpactShapeInterface::getChildAabb(), btGImpactShapeInterface::getNumChildShapes(), btGImpactShapeInterface::hasBoxSet(), i, and btPairSet::push_pair().
Referenced by gimpact_vs_gimpact().
void btGImpactCollisionAlgorithm::gimpact_vs_shape (btCollisionObject * body0, btCollisionObject * body1, btGImpactShapeInterface * shape0, btCollisionShape * shape1, bool swapped)
Collision routines
Definition at line 584 of file btGImpactCollisionAlgorithm.cpp.
References btGImpactShapeInterface::childrenHasTransform(), CONST_GIMPACT_TRIMESH_SHAPE, CONST_GIMPACT_TRIMESH_SHAPE_PART, GIM_ShapeRetriever::getChildShape(), btGImpactShapeInterface::getChildTransform(), btGImpactShapeInterface::getGImpactShapeType(), btGImpactMeshShape::getMeshPart(), btGImpactMeshShape::getMeshPartCount(), btCollisionShape::getShapeType(), gimpact_vs_compoundshape(), gimpact_vs_concave(), gimpact_vs_shape_find_pairs(), gimpacttrimeshpart_vs_plane_collision(), i, btCollisionShape::isCompound(), btCollisionShape::isConcave(), btGImpactShapeInterface::lockChildShapes(), m_part0, m_part1, m_triface0, m_triface1, shape_vs_shape_collision(), btAlignedObjectArray< T >::size(), STATIC_PLANE_PROXYTYPE, and btGImpactShapeInterface::unlockChildShapes().
Referenced by gimpact_vs_compoundshape(), processCollision(), and btGImpactTriangleCallback::processTriangle().
void btGImpactCollisionAlgorithm::gimpact_vs_shape_find_pairs (const btTransform & trans0, const btTransform & trans1, btGImpactShapeInterface * shape0, btCollisionShape * shape1, btAlignedObjectArray< int > & collided_primitives) [protected]
Collision routines
Definition at line 320 of file btGImpactCollisionAlgorithm.cpp.
References btGImpactQuantizedBvh::boxQuery(), btCollisionShape::getAabb(), btGImpactShapeInterface::getBoxSet(), btGImpactShapeInterface::getChildAabb(), btGImpactShapeInterface::getNumChildShapes(), btGImpactShapeInterface::hasBoxSet(), i, btTransform::inverse(), and btAlignedObjectArray< T >::push_back().
Referenced by gimpact_vs_shape().
void btGImpactCollisionAlgorithm::gimpacttrimeshpart_vs_plane_collision (btCollisionObject * body0, btCollisionObject * body1, btGImpactMeshShapePart * shape0, btStaticPlaneShape * shape1, bool swapped) [protected]
Collision routines
Definition at line 720 of file btGImpactCollisionAlgorithm.cpp.
References addContactPoint(), BT_CONST_COLLIDE_PLANE, distance(), btPlaneShape::get_plane_equation_transformed(), btGImpactShapeInterface::getAabb(), btGImpactMeshShapePart::getMargin(), btGImpactMeshShapePart::getVertex(), btGImpactMeshShapePart::getVertexCount(), btGImpactMeshShapePart::lockChildShapes(), and btGImpactMeshShapePart::unlockChildShapes().
Referenced by gimpact_vs_shape().
SIMD_FORCE_INLINE btCollisionAlgorithm* btGImpactCollisionAlgorithm::newAlgorithm (btCollisionObject * body0, btCollisionObject * body1) [inline, protected]
Definition at line 120 of file btGImpactCollisionAlgorithm.h.
References checkManifold(), btDispatcher::findAlgorithm(), getLastManifold(), and btCollisionAlgorithm::m_dispatcher.
Referenced by checkConvexAlgorithm(), and shape_vs_shape_collision().
SIMD_FORCE_INLINE btPersistentManifold* btGImpactCollisionAlgorithm::newContactManifold (btCollisionObject * body0, btCollisionObject * body1) [inline, protected]
Creates a new contact point.
Definition at line 68 of file btGImpactCollisionAlgorithm.h.
References btDispatcher::getNewManifold(), btCollisionAlgorithm::m_dispatcher, and m_manifoldPtr.
Referenced by checkManifold().
void btGImpactCollisionAlgorithm::processCollision (btCollisionObject * body0, btCollisionObject * body1, const btDispatcherInfo & dispatchInfo, btManifoldResult * resultOut) [virtual]
Collision routines
Implements btCollisionAlgorithm.
Definition at line 842 of file btGImpactCollisionAlgorithm.cpp.
References clearCache(), GIMPACT_SHAPE_PROXYTYPE, gimpact_vs_gimpact(), gimpact_vs_shape(), m_dispatchInfo, and m_resultOut.
void btGImpactCollisionAlgorithm::registerAlgorithm (btCollisionDispatcher * dispatcher) [static]
Use this function for register the algorithm externally.
Definition at line 887 of file btGImpactCollisionAlgorithm.cpp.
References GIMPACT_SHAPE_PROXYTYPE, i, MAX_BROADPHASE_COLLISION_TYPES, and btCollisionDispatcher::registerCollisionCreateFunc().
Referenced by CcdPhysicsEnvironment::CcdPhysicsEnvironment().
void btGImpactCollisionAlgorithm::setFace0 (int value) [inline]
Accessor/Mutator pairs for Part and triangleID.
Definition at line 264 of file btGImpactCollisionAlgorithm.h.
References m_triface0.
Referenced by btGImpactTriangleCallback::processTriangle().
void btGImpactCollisionAlgorithm::setFace1 (int value) [inline]
Collision routines
Definition at line 272 of file btGImpactCollisionAlgorithm.h.
References m_triface1.
Referenced by btGImpactTriangleCallback::processTriangle().
void btGImpactCollisionAlgorithm::setPart0 (int value) [inline]
Collision routines
Definition at line 280 of file btGImpactCollisionAlgorithm.h.
References m_part0.
Referenced by btGImpactTriangleCallback::processTriangle().
void btGImpactCollisionAlgorithm::setPart1 (int value) [inline]
Collision routines
Definition at line 288 of file btGImpactCollisionAlgorithm.h.
References m_part1.
Referenced by btGImpactTriangleCallback::processTriangle().
void btGImpactCollisionAlgorithm::shape_vs_shape_collision (btCollisionObject * body0, btCollisionObject * body1, btCollisionShape * shape0, btCollisionShape * shape1) [protected]
Collision routines
Definition at line 225 of file btGImpactCollisionAlgorithm.cpp.
References btDispatcher::freeCollisionAlgorithm(), btCollisionAlgorithm::m_dispatcher, m_dispatchInfo, m_part0, m_part1, m_resultOut, m_triface0, m_triface1, newAlgorithm(), btCollisionAlgorithm::processCollision(), btManifoldResult::setShapeIdentifiersA(), btManifoldResult::setShapeIdentifiersB(), and btCollisionAlgorithm::~btCollisionAlgorithm().
Referenced by gimpact_vs_shape().
Member Data Documentation
btCollisionAlgorithm* btGImpactCollisionAlgorithm::m_convex_algorithm [protected]
Definition at line 57 of file btGImpactCollisionAlgorithm.h.
Referenced by btGImpactCollisionAlgorithm(), checkConvexAlgorithm(), convex_vs_convex_collision(), and destroyConvexAlgorithm().
const btDispatcherInfo* btGImpactCollisionAlgorithm::m_dispatchInfo [protected]
Definition at line 60 of file btGImpactCollisionAlgorithm.h.
Referenced by convex_vs_convex_collision(), processCollision(), and shape_vs_shape_collision().
btPersistentManifold* btGImpactCollisionAlgorithm::m_manifoldPtr [protected]
Definition at line 58 of file btGImpactCollisionAlgorithm.h.
Referenced by btGImpactCollisionAlgorithm(), destroyContactManifolds(), getAllContactManifolds(), getLastManifold(), and newContactManifold().
int btGImpactCollisionAlgorithm::m_part0 [protected]
Definition at line 62 of file btGImpactCollisionAlgorithm.h.
Referenced by addContactPoint(), clearCache(), convex_vs_convex_collision(), getPart0(), gimpact_vs_gimpact(), gimpact_vs_shape(), setPart0(), and shape_vs_shape_collision().
int btGImpactCollisionAlgorithm::m_part1 [protected]
Definition at line 64 of file btGImpactCollisionAlgorithm.h.
Referenced by addContactPoint(), clearCache(), convex_vs_convex_collision(), getPart1(), gimpact_vs_gimpact(), gimpact_vs_shape(), setPart1(), and shape_vs_shape_collision().
btManifoldResult* btGImpactCollisionAlgorithm::m_resultOut [protected]
Definition at line 59 of file btGImpactCollisionAlgorithm.h.
Referenced by addContactPoint(), checkManifold(), convex_vs_convex_collision(), processCollision(), and shape_vs_shape_collision().
int btGImpactCollisionAlgorithm::m_triface0 [protected]
Definition at line 61 of file btGImpactCollisionAlgorithm.h.
Referenced by addContactPoint(), clearCache(), collide_gjk_triangles(), collide_sat_triangles(), convex_vs_convex_collision(), getFace0(), gimpact_vs_gimpact(), gimpact_vs_shape(), setFace0(), and shape_vs_shape_collision().
int btGImpactCollisionAlgorithm::m_triface1 [protected]
Definition at line 63 of file btGImpactCollisionAlgorithm.h.
Referenced by addContactPoint(), clearCache(), collide_gjk_triangles(), collide_sat_triangles(), convex_vs_convex_collision(), getFace1(), gimpact_vs_gimpact(), gimpact_vs_shape(), setFace1(), and shape_vs_shape_collision().
The documentation for this class was generated from the following files:
btGImpactCollisionAlgorithm.h
btGImpactCollisionAlgorithm.cpp