Blender: ntlVector3Dim< Scalar > Class Template Reference
ntlVector3Dim< Scalar > Class Template Reference
#include <ntl_vector3dim.h>
Public Member Functions
ntlVector3Dim (void)
ntlVector3Dim (const ntlVector3Dim< Scalar > &v)
ntlVector3Dim (const float *)
ntlVector3Dim (const double *)
ntlVector3Dim (Scalar)
ntlVector3Dim (Scalar, Scalar, Scalar)
Scalar * getAddress ()
const ntlVector3Dim< Scalar > & operator= (const ntlVector3Dim< Scalar > &v)
const ntlVector3Dim< Scalar > & operator= (Scalar s)
const ntlVector3Dim< Scalar > & operator+= (const ntlVector3Dim< Scalar > &v)
const ntlVector3Dim< Scalar > & operator+= (Scalar s)
const ntlVector3Dim< Scalar > & operator-= (const ntlVector3Dim< Scalar > &v)
const ntlVector3Dim< Scalar > & operator-= (Scalar s)
const ntlVector3Dim< Scalar > & operator*= (const ntlVector3Dim< Scalar > &v)
const ntlVector3Dim< Scalar > & operator*= (Scalar s)
const ntlVector3Dim< Scalar > & operator/= (const ntlVector3Dim< Scalar > &v)
const ntlVector3Dim< Scalar > & operator/= (Scalar s)
ntlVector3Dim< Scalar > operator- () const
ntlVector3Dim< Scalar > operator+ (const ntlVector3Dim< Scalar > &) const
ntlVector3Dim< Scalar > operator+ (Scalar) const
ntlVector3Dim< Scalar > operator- (const ntlVector3Dim< Scalar > &) const
ntlVector3Dim< Scalar > operator- (Scalar) const
ntlVector3Dim< Scalar > operator* (const ntlVector3Dim< Scalar > &) const
ntlVector3Dim< Scalar > operator* (Scalar) const
ntlVector3Dim< Scalar > operator/ (const ntlVector3Dim< Scalar > &) const
ntlVector3Dim< Scalar > operator/ (Scalar) const
ntlVector3Dim< Scalar > getOrthogonalntlVector3Dim () const
const ntlVector3Dim< Scalar > & projectNormalTo (const ntlVector3Dim< Scalar > &v)
const ntlVector3Dim< Scalar > & minimize (const ntlVector3Dim< Scalar > &)
const ntlVector3Dim< Scalar > & maximize (const ntlVector3Dim< Scalar > &)
Scalar & operator[] (unsigned int i)
const Scalar & operator[] (unsigned int i) const
Detailed Description
template<class Scalar>
class ntlVector3Dim< Scalar >
Definition at line 125 of file ntl_vector3dim.h.
Constructor & Destructor Documentation
template<class Scalar > ntlVector3Dim< Scalar >::ntlVector3Dim (void) [inline]
Definition at line 259 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar >::ntlVector3Dim (const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 270 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar >::ntlVector3Dim (const float * fvalue) [inline]
Definition at line 277 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar >::ntlVector3Dim (const double * fvalue) [inline]
Definition at line 284 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar >::ntlVector3Dim (Scalar s) [inline]
Definition at line 300 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar >::ntlVector3Dim (Scalar s1, Scalar s2, Scalar s3) [inline]
Definition at line 316 of file ntl_vector3dim.h.
Member Function Documentation
template<class Scalar> Scalar* ntlVector3Dim< Scalar >::getAddress () [inline]
Definition at line 140 of file ntl_vector3dim.h.
template<class Scalar > ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::getOrthogonalntlVector3Dim () const [inline]
Definition at line 714 of file ntl_vector3dim.h.
References fabs(), getNormalized(), max, and ntlVector3Dim< Scalar >::projectNormalTo().
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::maximize (const ntlVector3Dim< Scalar > & pnt) [inline]
Definition at line 782 of file ntl_vector3dim.h.
References i, and MAX.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::minimize (const ntlVector3Dim< Scalar > & pnt) [inline]
Definition at line 765 of file ntl_vector3dim.h.
References i, and MIN.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator* (Scalar s) const [inline]
Definition at line 605 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator* (const ntlVector3Dim< Scalar > & v) const [inline]
Definition at line 590 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator*= (Scalar s) [inline]
Definition at line 458 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator*= (const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 442 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator+ (const ntlVector3Dim< Scalar > & v) const [inline]
Definition at line 529 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator+ (Scalar s) const [inline]
Definition at line 544 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator+= (const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 378 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator+= (Scalar s) [inline]
Definition at line 394 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator- (Scalar s) const [inline]
Definition at line 574 of file ntl_vector3dim.h.
template<class Scalar > ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator- () const [inline]
Definition at line 510 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator- (const ntlVector3Dim< Scalar > & v) const [inline]
Definition at line 559 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator-= (const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 410 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator-= (Scalar s) [inline]
Definition at line 426 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator/ (const ntlVector3Dim< Scalar > & v) const [inline]
Definition at line 618 of file ntl_vector3dim.h.
template<class Scalar> ntlVector3Dim< Scalar > ntlVector3Dim< Scalar >::operator/ (Scalar s) const [inline]
Definition at line 634 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator/= (const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 474 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator/= (Scalar s) [inline]
Definition at line 490 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator= (const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 346 of file ntl_vector3dim.h.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::operator= (Scalar s) [inline]
Definition at line 362 of file ntl_vector3dim.h.
template<class Scalar > const Scalar & ntlVector3Dim< Scalar >::operator[] (unsigned int i) const [inline]
Definition at line 665 of file ntl_vector3dim.h.
References i.
template<class Scalar > Scalar & ntlVector3Dim< Scalar >::operator[] (unsigned int i) [inline]
Definition at line 652 of file ntl_vector3dim.h.
References i.
template<class Scalar> const ntlVector3Dim< Scalar > & ntlVector3Dim< Scalar >::projectNormalTo (const ntlVector3Dim< Scalar > & v) [inline]
Definition at line 740 of file ntl_vector3dim.h.
References dot().
Referenced by ntlVector3Dim< Scalar >::getOrthogonalntlVector3Dim().
The documentation for this class was generated from the following file:
ntl_vector3dim.h