Blender: anim_draw.c File Reference
anim_draw.c File Reference
animation
#include "BLO_sys_types.h"
#include "DNA_anim_types.h"
#include "DNA_object_types.h"
#include "DNA_scene_types.h"
#include "BLI_math.h"
#include "BKE_context.h"
#include "BKE_global.h"
#include "BKE_nla.h"
#include "BKE_object.h"
#include "ED_anim_api.h"
#include "ED_keyframes_edit.h"
#include "RNA_access.h"
#include "BIF_gl.h"
#include "UI_interface.h"
#include "UI_resources.h"
#include "UI_view2d.h"
Functions
void ANIM_timecode_string_from_frame (char *str, Scene *scene, int power, short timecodes, float cfra)
static void draw_cfra_number (Scene *scene, View2D *v2d, float cfra, short time)
void ANIM_draw_cfra (const bContext *C, View2D *v2d, short flag)
void ANIM_draw_previewrange (const bContext *C, View2D *v2d)
AnimData * ANIM_nla_mapping_get (bAnimContext *ac, bAnimListElem *ale)
static short bezt_nlamapping_restore (KeyframeEditData *ked, BezTriple *bezt)
static short bezt_nlamapping_apply (KeyframeEditData *ked, BezTriple *bezt)
void ANIM_nla_mapping_apply_fcurve (AnimData *adt, FCurve *fcu, short restore, short only_keys)
float ANIM_unit_mapping_get_factor (Scene *scene, ID *id, FCurve *fcu, short restore)
static short bezt_unit_mapping_apply (KeyframeEditData *ked, BezTriple *bezt)
void ANIM_unit_mapping_apply_fcurve (Scene *scene, ID *id, FCurve *fcu, short flag)
Detailed Description
Definition in file anim_draw.c.
Function Documentation
void ANIM_draw_cfra (const bContext * C, View2D * v2d, short flag)
Definition at line 215 of file anim_draw.c.
References RenderData::cfra, CTX_data_scene(), CTX_wm_region(), View2D::cur, draw_cfra_number(), DRAWCFRA_SHOW_NUMBOX, DRAWCFRA_UNIT_SECONDS, DRAWCFRA_WIDE, RenderData::framelen, Scene::r, TH_CFRAME, UI_ThemeColor(), UI_view2d_view_orthoSpecial(), rctf::ymax, and rctf::ymin.
Referenced by action_main_area_draw(), draw_timeline_seq(), graph_main_area_draw(), nla_main_area_draw(), and time_main_area_draw().
void ANIM_draw_previewrange (const bContext * C, View2D * v2d)
Definition at line 251 of file anim_draw.c.
References CTX_data_scene(), View2D::cur, PEFRA, PRVRANGEON, PSFRA, rctf::xmax, rctf::xmin, rctf::ymax, and rctf::ymin.
Referenced by action_main_area_draw(), draw_timeline_seq(), graph_main_area_draw(), and nla_main_area_draw().
void ANIM_nla_mapping_apply_fcurve (AnimData * adt, FCurve * fcu, short restore, short only_keys)
Definition at line 338 of file anim_draw.c.
References ANIM_fcurve_keyframes_loop(), bezt_nlamapping_apply(), bezt_nlamapping_restore(), KeyframeEditData::data, KeyframeEditData::i1, and NULL.
Referenced by actkeys_framejump_exec(), actkeys_select_leftright(), borderselect_graphkeys(), fcurve_to_keylist(), get_nearest_fcurve_verts_list(), graph_draw_curves(), graphkeys_framejump_exec(), graphkeys_select_leftright(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), posttrans_action_clean(), snap_action_keys(), snap_graph_keys(), and special_aftertrans_update().
AnimData* ANIM_nla_mapping_get (bAnimContext * ac, bAnimListElem * ale) [read]
Definition at line 279 of file anim_draw.c.
References bAnimListElem::adt, G, and NULL.
Referenced by actkeys_framejump_exec(), actkeys_mselect_column(), actkeys_select_leftright(), borderselect_action(), borderselect_graphkeys(), columnselect_action_keys(), columnselect_graph_keys(), createTransActionData(), draw_channel_strips(), get_graph_keyframe_extents(), get_keyframe_extents(), get_nearest_fcurve_verts_list(), graph_draw_curves(), graphkeys_click_insert_exec(), graphkeys_framejump_exec(), graphkeys_mselect_column(), graphkeys_select_leftright(), insert_action_keys(), insert_graph_keys(), markers_selectkeys_between(), mirror_action_keys(), mirror_graph_keys(), mouse_action_keys(), posttrans_action_clean(), snap_action_keys(), snap_graph_keys(), and special_aftertrans_update().
void ANIM_timecode_string_from_frame (char * str, Scene * scene, int power, short timecodes, float cfra)
Definition at line 66 of file anim_draw.c.
References FPS, TNT::seconds(), USER_TIMECODE_MILLISECONDS, USER_TIMECODE_MINIMAL, USER_TIMECODE_SECONDS_ONLY, USER_TIMECODE_SMPTE_FULL, and USER_TIMECODE_SMPTE_MSF.
Referenced by draw_cfra_number(), and scroll_printstr().
void ANIM_unit_mapping_apply_fcurve (Scene * scene, ID * id, FCurve * fcu, short flag)
Definition at line 418 of file anim_draw.c.
References ANIM_editkeyframes_ok(), ANIM_fcurve_keyframes_loop(), ANIM_unit_mapping_get_factor(), ANIM_UNITCONV_ONLYSEL, ANIM_UNITCONV_RESTORE, BEZT_OK_SELECTED, bezt_unit_mapping_apply(), KeyframeEditData::f1, FCurve::fpt, G, i, KeyframeEditData::i1, NULL, and FPoint::vec.
Referenced by borderselect_graphkeys(), draw_fcurve_curve_bezts(), draw_fcurve_curve_samples(), get_nearest_fcurve_verts_list(), graph_draw_curves(), graphkeys_framejump_exec(), mirror_graph_keys(), and snap_graph_keys().
float ANIM_unit_mapping_get_factor (Scene * scene, ID * id, FCurve * fcu, short restore)
Definition at line 364 of file anim_draw.c.
References DEG2RADF, PROP_UNIT_ROTATION, RAD2DEGF, RNA_id_pointer_create(), FCurve::rna_path, RNA_path_resolve(), RNA_property_subtype(), RNA_SUBTYPE_UNIT, UnitSettings::system_rotation, Scene::unit, and USER_UNIT_ROT_RADIANS.
Referenced by ANIM_unit_mapping_apply_fcurve(), draw_fcurve_curve(), get_graph_keyframe_extents(), and graphkeys_click_insert_exec().
static short bezt_nlamapping_apply (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 316 of file anim_draw.c.
References BKE_nla_tweakedit_remap(), KeyframeEditData::data, KeyframeEditData::i1, NLATIME_CONVERT_MAP, and BezTriple::vec.
Referenced by ANIM_nla_mapping_apply_fcurve().
static short bezt_nlamapping_restore (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 298 of file anim_draw.c.
References BKE_nla_tweakedit_remap(), KeyframeEditData::data, KeyframeEditData::i1, NLATIME_CONVERT_UNMAP, and BezTriple::vec.
Referenced by ANIM_nla_mapping_apply_fcurve().
static short bezt_unit_mapping_apply (KeyframeEditData * ked, BezTriple * bezt) [static]
Definition at line 396 of file anim_draw.c.
References ANIM_UNITCONV_ONLYKEYS, ANIM_UNITCONV_SELVERTS, KeyframeEditData::f1, BezTriple::f1, BezTriple::f2, BezTriple::f3, KeyframeEditData::i1, SELECT, and BezTriple::vec.
Referenced by ANIM_unit_mapping_apply_fcurve().
static void draw_cfra_number (Scene * scene, View2D * v2d, float cfra, short time) [static]
Definition at line 177 of file anim_draw.c.
References ANIM_timecode_string_from_frame(), FRA2TIME, TH_CFRAME, TH_TEXT, UI_DrawString(), UI_GetStringWidth(), UI_ThemeColor(), UI_ThemeColorShade(), and UI_view2d_getscale().
Referenced by ANIM_draw_cfra().