Blender: writefile.c File Reference
writefile.c File Reference
.blend read and write functions
#include <math.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "zlib.h"
#include <unistd.h>
#include "DNA_anim_types.h"
#include "DNA_armature_types.h"
#include "DNA_actuator_types.h"
#include "DNA_brush_types.h"
#include "DNA_camera_types.h"
#include "DNA_cloth_types.h"
#include "DNA_constraint_types.h"
#include "DNA_controller_types.h"
#include "DNA_dynamicpaint_types.h"
#include "DNA_genfile.h"
#include "DNA_group_types.h"
#include "DNA_gpencil_types.h"
#include "DNA_fileglobal_types.h"
#include "DNA_key_types.h"
#include "DNA_lattice_types.h"
#include "DNA_lamp_types.h"
#include "DNA_meta_types.h"
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_material_types.h"
#include "DNA_node_types.h"
#include "DNA_object_types.h"
#include "DNA_object_force.h"
#include "DNA_packedFile_types.h"
#include "DNA_particle_types.h"
#include "DNA_property_types.h"
#include "DNA_scene_types.h"
#include "DNA_sdna_types.h"
#include "DNA_sequence_types.h"
#include "DNA_sensor_types.h"
#include "DNA_smoke_types.h"
#include "DNA_space_types.h"
#include "DNA_screen_types.h"
#include "DNA_speaker_types.h"
#include "DNA_sound_types.h"
#include "DNA_text_types.h"
#include "DNA_view3d_types.h"
#include "DNA_vfont_types.h"
#include "DNA_world_types.h"
#include "DNA_windowmanager_types.h"
#include "DNA_movieclip_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_bitmap.h"
#include "BLI_blenlib.h"
#include "BLI_linklist.h"
#include "BLI_bpath.h"
#include "BLI_math.h"
#include "BLI_utildefines.h"
#include "BKE_action.h"
#include "BKE_blender.h"
#include "BKE_curve.h"
#include "BKE_constraint.h"
#include "BKE_global.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_node.h"
#include "BKE_report.h"
#include "BKE_sequencer.h"
#include "BKE_utildefines.h"
#include "BKE_modifier.h"
#include "BKE_fcurve.h"
#include "BKE_pointcache.h"
#include "BKE_mesh.h"
#include "BLO_writefile.h"
#include "BLO_readfile.h"
#include "BLO_undofile.h"
#include "readfile.h"
#include <errno.h>
Classes
struct WriteData
struct RenderInfo
Defines
#define DNA_DEPRECATED_ALLOW
#define MYWRITE_BUFFER_SIZE 100000
#define MYWRITE_MAX_CHUNK 32768
#define MYWRITE_FLUSH NULL
Typedefs
typedef struct RenderInfo RenderInfo
Functions
static WriteData * writedata_new (int file)
static void writedata_do_write (WriteData *wd, const void *mem, int memlen)
static void writedata_free (WriteData *wd)
static void mywrite (WriteData *wd, const void *adr, int len)
static WriteData * bgnwrite (int file, MemFile *compare, MemFile *current)
static int endwrite (WriteData *wd)
static void writestruct (WriteData *wd, int filecode, const char *structname, int nr, void *adr)
static void writedata (WriteData *wd, int filecode, int len, const void *adr)
void IDP_WriteProperty_OnlyData (IDProperty *prop, void *wd)
void IDP_WriteProperty (IDProperty *prop, void *wd)
static void IDP_WriteArray (IDProperty *prop, void *wd)
static void IDP_WriteIDPArray (IDProperty *prop, void *wd)
static void IDP_WriteString (IDProperty *prop, void *wd)
static void IDP_WriteGroup (IDProperty *prop, void *wd)
static void write_fmodifiers (WriteData *wd, ListBase *fmodifiers)
static void write_fcurves (WriteData *wd, ListBase *fcurves)
static void write_actions (WriteData *wd, ListBase *idbase)
static void write_keyingsets (WriteData *wd, ListBase *list)
static void write_nlastrips (WriteData *wd, ListBase *strips)
static void write_nladata (WriteData *wd, ListBase *nlabase)
static void write_animdata (WriteData *wd, AnimData *adt)
static void write_curvemapping (WriteData *wd, CurveMapping *cumap)
static void write_node_socket (WriteData *wd, bNodeSocket *sock)
static void write_nodetree (WriteData *wd, bNodeTree *ntree)
static void current_screen_compat (Main *mainvar, bScreen **screen)
static void write_renderinfo (WriteData *wd, Main *mainvar)
static void write_keymapitem (WriteData *wd, wmKeyMapItem *kmi)
static void write_userdef (WriteData *wd)
static void write_boid_state (WriteData *wd, BoidState *state)
static void write_pointcaches (WriteData *wd, ListBase *ptcaches)
static void write_particlesettings (WriteData *wd, ListBase *idbase)
static void write_particlesystems (WriteData *wd, ListBase *particles)
static void write_properties (WriteData *wd, ListBase *lb)
static void write_sensors (WriteData *wd, ListBase *lb)
static void write_controllers (WriteData *wd, ListBase *lb)
static void write_actuators (WriteData *wd, ListBase *lb)
static void write_motionpath (WriteData *wd, bMotionPath *mpath)
static void write_constraints (WriteData *wd, ListBase *conlist)
static void write_pose (WriteData *wd, bPose *pose)
static void write_defgroups (WriteData *wd, ListBase *defbase)
static void write_modifiers (WriteData *wd, ListBase *modbase)
static void write_objects (WriteData *wd, ListBase *idbase)
static void write_vfonts (WriteData *wd, ListBase *idbase)
static void write_keys (WriteData *wd, ListBase *idbase)
static void write_cameras (WriteData *wd, ListBase *idbase)
static void write_mballs (WriteData *wd, ListBase *idbase)
static int amount_of_chars (char *str)
static void write_curves (WriteData *wd, ListBase *idbase)
static void write_dverts (WriteData *wd, int count, MDeformVert *dvlist)
static void write_mdisps (WriteData *wd, int count, MDisps *mdlist, int external)
static void write_customdata (WriteData *wd, ID *id, int count, CustomData *data, int partial_type, int partial_count)
static void write_meshs (WriteData *wd, ListBase *idbase)
static void write_lattices (WriteData *wd, ListBase *idbase)
static void write_previews (WriteData *wd, PreviewImage *prv)
static void write_images (WriteData *wd, ListBase *idbase)
static void write_textures (WriteData *wd, ListBase *idbase)
static void write_materials (WriteData *wd, ListBase *idbase)
static void write_worlds (WriteData *wd, ListBase *idbase)
static void write_lamps (WriteData *wd, ListBase *idbase)
static void write_scenes (WriteData *wd, ListBase *scebase)
static void write_gpencils (WriteData *wd, ListBase *lb)
static void write_windowmanagers (WriteData *wd, ListBase *lb)
static void write_region (WriteData *wd, ARegion *ar, int spacetype)
static void write_screens (WriteData *wd, ListBase *scrbase)
static void write_libraries (WriteData *wd, Main *main)
static void write_bone (WriteData *wd, Bone *bone)
static void write_armatures (WriteData *wd, ListBase *idbase)
static void write_texts (WriteData *wd, ListBase *idbase)
static void write_speakers (WriteData *wd, ListBase *idbase)
static void write_sounds (WriteData *wd, ListBase *idbase)
static void write_groups (WriteData *wd, ListBase *idbase)
static void write_nodetrees (WriteData *wd, ListBase *idbase)
static void write_brushes (WriteData *wd, ListBase *idbase)
static void write_scripts (WriteData *wd, ListBase *idbase)
static void write_movieTracks (WriteData *wd, ListBase *tracks)
static void write_movieReconstruction (WriteData *wd, MovieTrackingReconstruction *reconstruction)
static void write_movieclips (WriteData *wd, ListBase *idbase)
static void write_global (WriteData *wd, int fileflags, Main *mainvar)
static void write_thumb (WriteData *wd, const int *img)
static int write_file_handle (Main *mainvar, int handle, MemFile *compare, MemFile *current, int write_user_block, int write_flags, const int *thumb)
static int do_history (const char *name, ReportList *reports)
int BLO_write_file (Main *mainvar, const char *filepath, int write_flags, ReportList *reports, const int *thumb)
int BLO_write_file_mem (Main *mainvar, MemFile *compare, MemFile *current, int write_flags)
Variables
static const char * ptcache_data_struct []
static const char * ptcache_extra_struct []
Detailed Description
Definition in file writefile.c.
Define Documentation
#define DNA_DEPRECATED_ALLOW
Definition at line 93 of file writefile.c.
#define MYWRITE_BUFFER_SIZE 100000
Definition at line 171 of file writefile.c.
Referenced by mywrite(), and writedata_new().
#define MYWRITE_FLUSH NULL
Low level WRITE(2) wrapper that buffers data
Parameters:
adr Pointer to new chunk of data
len Length of new chunk of data
Warning:
Talks to other functions with global parameters
Definition at line 240 of file writefile.c.
Referenced by mywrite(), write_actions(), write_armatures(), write_curves(), write_images(), write_keys(), write_movieclips(), write_objects(), write_scenes(), write_sounds(), write_texts(), and write_textures().
#define MYWRITE_MAX_CHUNK 32768
Definition at line 172 of file writefile.c.
Referenced by mywrite().
Typedef Documentation
typedef struct RenderInfo RenderInfo
Function Documentation
static int amount_of_chars (char * str) [static]
Definition at line 1571 of file writefile.c.
References strlen().
Referenced by write_curves().
static WriteData* bgnwrite (int file, MemFile * compare, MemFile * current) [static]
BeGiN initializer for mywrite
Parameters:
file File descriptor
compare Previous memory file (can be NULL).
current The current memory file (can be NULL).
Warning:
Talks to other functions with global parameters
Definition at line 293 of file writefile.c.
References add_memfilechunk(), compare(), WriteData::compare, WriteData::current, NULL, and writedata_new().
Referenced by write_file_handle().
int BLO_write_file (Main * mainvar, const char * filepath, int write_flags, ReportList * reports, const int * thumb)
Definition at line 2889 of file writefile.c.
References BKE_report(), BKE_reportf(), BLENDER_STARTUP_FILE, BLENDER_USER_CONFIG, BLI_cleanup_dir(), BLI_delete(), BLI_file_gzip(), BLI_get_folder_create(), BLI_make_file_string(), BLI_open(), BLI_path_cmp, BLI_rename(), BLI_snprintf(), BLI_split_dir_part(), do_history(), err, FILE_MAX, G, G_FILE_COMPRESS, G_FILE_HISTORY, G_FILE_RELATIVE_REMAP, makeFilesAbsolute(), makeFilesRelative(), Main::name, NULL, O_BINARY, RPT_ERROR, and write_file_handle().
Referenced by BKE_write_undo(), wm_autosave_timer(), WM_write_file(), WM_write_homefile(), and write_crash_blend().
int BLO_write_file_mem (Main * mainvar, MemFile * compare, MemFile * current, int write_flags)
Definition at line 2992 of file writefile.c.
References err, NULL, and write_file_handle().
Referenced by BKE_write_undo().
static void current_screen_compat (Main * mainvar, bScreen ** screen) [static]
Definition at line 748 of file writefile.c.
References ListBase::first, NULL, wmWindow::screen, wmWindowManager::windows, and Main::wm.
Referenced by write_global(), and write_renderinfo().
static int do_history (const char * name, ReportList * reports) [static]
Definition at line 2855 of file writefile.c.
References BKE_report(), BLI_rename(), BLI_snprintf(), FILE_MAX, RPT_ERROR, and strlen().
Referenced by BLO_write_file().
static int endwrite (WriteData * wd) [static]
END the mywrite wrapper
Returns:
1 if write failed
unknown global variable otherwise
Warning:
Talks to other functions with global parameters
Definition at line 313 of file writefile.c.
References WriteData::buf, WriteData::count, err, WriteData::error, writedata_do_write(), and writedata_free().
Referenced by write_file_handle().
static void IDP_WriteArray (IDProperty * prop, void * wd) [static]
Definition at line 383 of file writefile.c.
References DATA, IDProperty::data, IDP_GROUP, IDP_WriteProperty(), IDProperty::len, MEM_allocN_len(), IDPropertyData::pointer, IDProperty::subtype, and writedata().
Referenced by IDP_WriteProperty_OnlyData().
static void IDP_WriteGroup (IDProperty * prop, void * wd) [static]
Definition at line 419 of file writefile.c.
References IDProperty::data, ListBase::first, IDPropertyData::group, IDP_WriteProperty(), and IDProperty::next.
Referenced by IDP_WriteProperty_OnlyData().
static void IDP_WriteIDPArray (IDProperty * prop, void * wd) [static]
Definition at line 399 of file writefile.c.
References DATA, IDProperty::data, IDP_WriteProperty_OnlyData(), IDProperty::len, IDPropertyData::pointer, and writestruct().
Referenced by IDP_WriteProperty_OnlyData().
void IDP_WriteProperty (IDProperty * prop, void * wd)
Definition at line 447 of file writefile.c.
References DATA, IDP_WriteProperty_OnlyData(), and writestruct().
Referenced by IDP_WriteArray(), IDP_WriteGroup(), write_actions(), write_armatures(), write_bone(), write_brushes(), write_cameras(), write_constraints(), write_curves(), write_fmodifiers(), write_groups(), write_images(), write_keymapitem(), write_keys(), write_lamps(), write_lattices(), write_materials(), write_mballs(), write_meshs(), write_nodetrees(), write_objects(), write_particlesettings(), write_pose(), write_scenes(), write_screens(), write_scripts(), write_sounds(), write_speakers(), write_texts(), write_textures(), write_vfonts(), and write_worlds().
void IDP_WriteProperty_OnlyData (IDProperty * prop, void * wd)
Definition at line 429 of file writefile.c.
References IDP_ARRAY, IDP_GROUP, IDP_IDPARRAY, IDP_STRING, IDP_WriteArray(), IDP_WriteGroup(), IDP_WriteIDPArray(), IDP_WriteString(), and IDProperty::type.
Referenced by IDP_WriteIDPArray(), and IDP_WriteProperty().
static void IDP_WriteString (IDProperty * prop, void * wd) [static]
Definition at line 413 of file writefile.c.
References DATA, IDProperty::data, IDProperty::len, IDPropertyData::pointer, and writedata().
Referenced by IDP_WriteProperty_OnlyData().
static void mywrite (WriteData * wd, const void * adr, int len) [static]
Definition at line 242 of file writefile.c.
References WriteData::buf, WriteData::count, WriteData::error, len(), MIN2, MYWRITE_BUFFER_SIZE, MYWRITE_FLUSH, MYWRITE_MAX_CHUNK, WriteData::tot, and writedata_do_write().
Referenced by write_actions(), write_armatures(), write_curves(), write_file_handle(), write_images(), write_keys(), write_movieclips(), write_objects(), write_scenes(), write_sounds(), write_texts(), write_textures(), writedata(), and writestruct().
static void write_actions (WriteData * wd, ListBase * idbase) [static]
Definition at line 545 of file writefile.c.
References WriteData::current, bAction::curves, DATA, ListBase::first, bAction::groups, bAction::id, ID_AC, IDP_WriteProperty(), bAction::markers, mywrite(), MYWRITE_FLUSH, TimeMarker::next, bActionGroup::next, ID::next, ID::properties, ID::us, write_fcurves(), and writestruct().
Referenced by write_file_handle().
static void write_actuators (WriteData * wd, ListBase * lb) [static]
Definition at line 1109 of file writefile.c.
References ACT_2DFILTER, ACT_ACTION, ACT_ARMATURE, ACT_CAMERA, ACT_CONSTRAINT, ACT_EDIT_OBJECT, ACT_GAME, ACT_GROUP, ACT_IPO, ACT_MESSAGE, ACT_OBJECT, ACT_PARENT, ACT_PROPERTY, ACT_RANDOM, ACT_SCENE, ACT_SHAPEACTION, ACT_SOUND, ACT_STATE, ACT_STEERING, ACT_VISIBILITY, DATA, bActuator::data, ListBase::first, bActuator::next, bActuator::type, and writestruct().
Referenced by write_objects().
static void write_animdata (WriteData * wd, AnimData * adt) [static]
Definition at line 623 of file writefile.c.
References DATA, AnimData::drivers, ListBase::first, AnimOverride::next, AnimData::nla_tracks, AnimData::overrides, AnimOverride::rna_path, strlen(), write_fcurves(), write_nladata(), writedata(), and writestruct().
Referenced by write_armatures(), write_cameras(), write_curves(), write_keys(), write_lamps(), write_lattices(), write_materials(), write_mballs(), write_meshs(), write_movieclips(), write_nodetree(), write_nodetrees(), write_objects(), write_particlesettings(), write_scenes(), write_speakers(), write_textures(), and write_worlds().
static void write_armatures (WriteData * wd, ListBase * idbase) [static]
Definition at line 2489 of file writefile.c.
References bArmature::adt, bArmature::bonebase, WriteData::current, ListBase::first, bArmature::id, ID_AR, IDP_WriteProperty(), mywrite(), MYWRITE_FLUSH, Bone::next, ID::next, ID::properties, ID::us, write_animdata(), write_bone(), and writestruct().
Referenced by write_file_handle().
static void write_boid_state (WriteData * wd, BoidState * state) [static]
Definition at line 832 of file writefile.c.
References DATA, eBoidRuleType_AverageSpeed, eBoidRuleType_Avoid, eBoidRuleType_AvoidCollision, eBoidRuleType_Fight, eBoidRuleType_FollowLeader, eBoidRuleType_Goal, ListBase::first, BoidRule::next, BoidState::rules, BoidRule::type, and writestruct().
Referenced by write_particlesettings().
static void write_bone (WriteData * wd, Bone * bone) [static]
Definition at line 2466 of file writefile.c.
References Bone::childbase, DATA, ListBase::first, IDP_WriteProperty(), Bone::next, Bone::prop, Bone::size, and writestruct().
Referenced by write_armatures().
static void write_brushes (WriteData * wd, ListBase * idbase) [static]
Definition at line 2640 of file writefile.c.
References WriteData::current, Brush::curve, DATA, ListBase::first, Brush::id, ID_BR, IDP_WriteProperty(), Brush::mtex, ID::next, ID::properties, ID::us, write_curvemapping(), and writestruct().
Referenced by write_file_handle().
static void write_cameras (WriteData * wd, ListBase * idbase) [static]
Definition at line 1527 of file writefile.c.
References Camera::adt, WriteData::current, ListBase::first, Camera::id, ID_CA, IDP_WriteProperty(), ID::next, ID::properties, ID::us, write_animdata(), and writestruct().
Referenced by write_file_handle().
static void write_constraints (WriteData * wd, ListBase * conlist) [static]
Definition at line 1197 of file writefile.c.
References constraint_get_typeinfo(), CONSTRAINT_TYPE_PYTHON, CONSTRAINT_TYPE_SPLINEIK, bConstraint::data, DATA, data, ListBase::first, IDP_WriteProperty(), bConstraint::next, bSplineIKConstraint::numpoints, bSplineIKConstraint::points, bPythonConstraint::prop, bConstraintTypeInfo::structName, bPythonConstraint::targets, bConstraint::type, writedata(), and writestruct().
Referenced by write_objects(), and write_pose().
static void write_controllers (WriteData * wd, ListBase * lb) [static]
Definition at line 1084 of file writefile.c.
References CONT_EXPRESSION, CONT_PYTHON, DATA, bController::data, ListBase::first, bController::links, bController::next, bController::totlinks, bController::type, writedata(), and writestruct().
Referenced by write_objects().
static void write_curvemapping (WriteData * wd, CurveMapping * cumap) [static]
Definition at line 647 of file writefile.c.
References CurveMapping::cm, CM_TOT, CurveMap::curve, DATA, CurveMap::totpoint, and writestruct().
Referenced by write_brushes(), write_lamps(), write_modifiers(), write_nodetree(), write_screens(), and write_textures().
static void write_curves (WriteData * wd, ListBase * idbase) [static]
Definition at line 1578 of file writefile.c.
References Curve::adt, amount_of_chars(), Nurb::bezt, Nurb::bp, CU_BEZIER, WriteData::current, DATA, ListBase::first, Curve::id, ID_CU, IDP_WriteProperty(), Nurb::knotsu, KNOTSU, Nurb::knotsv, KNOTSV, Curve::len, Curve::mat, mywrite(), MYWRITE_FLUSH, Nurb::next, ID::next, Curve::nurb, Nurb::pntsu, Nurb::pntsv, ID::properties, Curve::str, Curve::strinfo, Curve::tb, Curve::totbox, Curve::totcol, Nurb::type, ID::us, Curve::vfont, write_animdata(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_customdata (WriteData * wd, ID * id, int count, CustomData * data, int partial_type, int partial_count) [static]
Definition at line 1661 of file writefile.c.
References CD_FLAG_EXTERNAL, CD_MASK_MESH, CD_MDEFORMVERT, CD_MDISPS, WriteData::current, CustomData_external_write(), CustomData_file_write_info(), CustomDataLayer::data, DATA, CustomData::external, CustomDataLayer::flag, i, CustomData::layers, CustomData::maxlayer, CustomData::totlayer, CustomDataLayer::type, write_dverts(), write_mdisps(), and writestruct().
Referenced by write_meshs().
static void write_defgroups (WriteData * wd, ListBase * defbase) [static]
Definition at line 1284 of file writefile.c.
References DATA, ListBase::first, bDeformGroup::next, and writestruct().
Referenced by write_objects().
static void write_dverts (WriteData * wd, int count, MDeformVert * dvlist) [static]
Definition at line 1626 of file writefile.c.
References DATA, i, and writestruct().
Referenced by write_customdata(), and write_lattices().
static void write_fcurves (WriteData * wd, ListBase * fcurves) [static]
Definition at line 503 of file writefile.c.
References FCurve::bezt, DATA, FCurve::driver, DRIVER_TARGETS_LOOPER_END, DRIVER_TARGETS_USED_LOOPER, ListBase::first, FCurve::fpt, FCurve::modifiers, FCurve::next, DriverVar::next, FCurve::rna_path, strlen(), FCurve::totvert, ChannelDriver::variables, write_fmodifiers(), writedata(), and writestruct().
Referenced by write_actions(), write_animdata(), and write_nlastrips().
static int write_file_handle (Main * mainvar, int handle, MemFile * compare, MemFile * current, int write_user_block, int write_flags, const int * thumb) [static]
Definition at line 2780 of file writefile.c.
References Main::action, Main::armature, B_ENDIAN, bgnwrite(), BLENDER_VERSION, blo_join_main(), blo_split_main(), Main::brush, Main::camera, BHead::code, Main::curve, SDNA::data, SDNA::datalen, DNA1, ENDB, ENDIAN_ORDER, endwrite(), G_FILE_MESH_COMPAT, Main::gpencil, Main::group, Main::image, Main::key, Main::lamp, Main::latt, Main::mat, Main::mball, Main::mesh, Main::movieclip, mywrite(), Main::next, Main::nodetree, NULL, Main::object, Main::particle, Main::scene, Main::screen, Main::script, WriteData::sdna, Main::sound, Main::speaker, Main::tex, Main::text, Main::vfont, Main::wm, Main::world, write_actions(), write_armatures(), write_brushes(), write_cameras(), write_curves(), write_global(), write_gpencils(), write_groups(), write_images(), write_keys(), write_lamps(), write_lattices(), write_libraries(), write_materials(), write_mballs(), write_meshs(), write_movieclips(), write_nodetrees(), write_objects(), write_particlesettings(), write_renderinfo(), write_scenes(), write_screens(), write_scripts(), write_sounds(), write_speakers(), write_texts(), write_textures(), write_thumb(), write_userdef(), write_vfonts(), write_windowmanagers(), write_worlds(), and writedata().
Referenced by BLO_write_file(), and BLO_write_file_mem().
static void write_fmodifiers (WriteData * wd, ListBase * fmodifiers) [static]
Definition at line 453 of file writefile.c.
References FMod_Generator::arraysize, FMod_Generator::coefficients, FMod_Envelope::data, data, DATA, FModifier::data, ListBase::first, fmodifier_get_typeinfo(), FMODIFIER_TYPE_ENVELOPE, FMODIFIER_TYPE_GENERATOR, FMODIFIER_TYPE_PYTHON, IDP_WriteProperty(), if(), FModifier::next, FMod_Python::prop, FModifierTypeInfo::structName, FMod_Envelope::totvert, FModifier::type, writedata(), and writestruct().
Referenced by write_fcurves(), and write_nlastrips().
static void write_global (WriteData * wd, int fileflags, Main * mainvar) [static]
Definition at line 2728 of file writefile.c.
References BLENDER_MINSUBVERSION, BLENDER_MINVERSION, BLENDER_SUBVERSION, BLI_strncpy(), build_rev, current_screen_compat(), FileGlobal::curscene, FileGlobal::curscreen, FileGlobal::displaymode, FileGlobal::fileflags, FileGlobal::filename, G, G_FILE_MESH_COMPAT, G_FILE_NO_UI, G_FILE_RELATIVE_REMAP, GLOB, FileGlobal::globalf, FileGlobal::minsubversion, FileGlobal::minversion, Main::name, FileGlobal::pad, FileGlobal::pads, FileGlobal::revision, bScreen::scene, FileGlobal::subversion, FileGlobal::subvstr, FileGlobal::winpos, and writestruct().
Referenced by write_file_handle().
static void write_gpencils (WriteData * wd, ListBase * lb) [static]
Definition at line 2212 of file writefile.c.
References WriteData::current, DATA, ListBase::first, bGPDlayer::frames, bGPdata::id, ID_GD, bGPdata::layers, bGPDlayer::next, bGPDstroke::next, bGPDframe::next, ID::next, bGPDstroke::points, bGPDframe::strokes, bGPDstroke::totpoints, ID::us, and writestruct().
Referenced by write_file_handle().
static void write_groups (WriteData * wd, ListBase * idbase) [static]
Definition at line 2604 of file writefile.c.
References WriteData::current, DATA, ListBase::first, Group::gobject, Group::id, ID_GR, IDP_WriteProperty(), GroupObject::next, ID::next, ID::properties, ID::us, and writestruct().
Referenced by write_file_handle().
static void write_images (WriteData * wd, ListBase * idbase) [static]
Definition at line 1892 of file writefile.c.
References WriteData::current, PackedFile::data, DATA, ListBase::first, Image::id, ID_IM, IDP_WriteProperty(), mywrite(), MYWRITE_FLUSH, ID::next, Image::packedfile, pf, Image::preview, ID::properties, PackedFile::size, ID::us, write_previews(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_keyingsets (WriteData * wd, ListBase * list) [static]
Definition at line 572 of file writefile.c.
References DATA, ListBase::first, KeyingSet::next, KS_Path::next, KeyingSet::paths, KS_Path::rna_path, strlen(), writedata(), and writestruct().
Referenced by write_scenes().
static void write_keymapitem (WriteData * wd, wmKeyMapItem * kmi) [static]
Definition at line 788 of file writefile.c.
References DATA, IDP_WriteProperty(), wmKeyMapItem::properties, and writestruct().
Referenced by write_userdef().
static void write_keys (WriteData * wd, ListBase * idbase) [static]
Definition at line 1498 of file writefile.c.
References Key::adt, Key::block, WriteData::current, DATA, KeyBlock::data, Key::elemsize, ListBase::first, Key::id, ID_KE, IDP_WriteProperty(), mywrite(), MYWRITE_FLUSH, KeyBlock::next, ID::next, ID::properties, KeyBlock::totelem, ID::us, write_animdata(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_lamps (WriteData * wd, ListBase * idbase) [static]
Definition at line 2027 of file writefile.c.
References Lamp::adt, Lamp::curfalloff, WriteData::current, DATA, ListBase::first, Lamp::id, ID_LA, IDP_WriteProperty(), MAX_MTEX, Lamp::mtex, ID::next, Lamp::nodetree, Lamp::preview, ID::properties, ID::us, write_animdata(), write_curvemapping(), write_nodetree(), write_previews(), and writestruct().
Referenced by write_file_handle().
static void write_lattices (WriteData * wd, ListBase * idbase) [static]
Definition at line 1843 of file writefile.c.
References Lattice::adt, WriteData::current, DATA, Lattice::def, Lattice::dvert, ListBase::first, Lattice::id, ID_LT, IDP_WriteProperty(), ID::next, Lattice::pntsu, Lattice::pntsv, Lattice::pntsw, ID::properties, ID::us, write_animdata(), write_dverts(), and writestruct().
Referenced by write_file_handle().
static void write_libraries (WriteData * wd, Main * main) [static]
Definition at line 2430 of file writefile.c.
References Main::curlib, ID::flag, ID_ID, ID_LI, LIB_EXTERN, main(), MAX_LIBARRAY, ID::next, Main::next, set_listbasepointers(), ID::us, and writestruct().
Referenced by write_file_handle().
static void write_materials (WriteData * wd, ListBase * idbase) [static]
Definition at line 1959 of file writefile.c.
References Material::adt, WriteData::current, DATA, ListBase::first, Material::id, ID_MA, IDP_WriteProperty(), MAX_MTEX, Material::mtex, ID::next, Material::nodetree, Material::preview, ID::properties, Material::ramp_col, Material::ramp_spec, ID::us, write_animdata(), write_nodetree(), write_previews(), and writestruct().
Referenced by write_file_handle().
static void write_mballs (WriteData * wd, ListBase * idbase) [static]
Definition at line 1545 of file writefile.c.
References MetaBall::adt, WriteData::current, DATA, MetaBall::elems, ListBase::first, MetaBall::id, ID_MB, IDP_WriteProperty(), MetaBall::mat, MetaElem::next, ID::next, ID::properties, MetaBall::totcol, ID::us, write_animdata(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_mdisps (WriteData * wd, int count, MDisps * mdlist, int external) [static]
Definition at line 1642 of file writefile.c.
References BLI_BITMAP_SIZE, DATA, MDisps::disps, MDisps::hidden, i, MDisps::totdisp, writedata(), and writestruct().
Referenced by write_customdata().
static void write_meshs (WriteData * wd, ListBase * idbase) [static]
Definition at line 1704 of file writefile.c.
References Mesh::adt, WriteData::current, CustomData_free(), DATA, Mesh::edit_btmesh, FALSE, Mesh::fdata, ListBase::first, Mesh::id, ID_ME, IDP_WriteProperty(), Mesh::ldata, Mesh::mat, mesh_mpoly_to_mface(), mesh_update_customdata_pointers(), Mesh::mface, Mesh::mpoly, Mesh::mselect, ID::next, NULL, ID::properties, Mesh::totcol, Mesh::totedge, Mesh::totface, Mesh::totloop, Mesh::totpoly, Mesh::totselect, Mesh::totvert, ID::us, write_animdata(), write_customdata(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_modifiers (WriteData * wd, ListBase * modbase) [static]
Definition at line 1292 of file writefile.c.
References MeshDeformModifierData::bindcagecos, MeshDeformModifierData::bindinfluences, MeshDeformModifierData::bindoffsets, BKE_ptcache_add(), BKE_ptcache_free_list(), DynamicPaintModifierData::brush, DynamicPaintModifierData::canvas, WeightVGEditModifierData::cmap_curve, SmokeModifierData::coll, ClothModifierData::coll_parms, WarpModifierData::curfalloff, DATA, SmokeModifierData::domain, MeshDeformModifierData::dyngrid, MeshDeformModifierData::dyngridsize, MeshDeformModifierData::dyninfluences, MeshDeformModifierData::dynverts, DynamicPaintSurface::effector_weights, SmokeDomainSettings::effector_weights, ClothSimSettings::effector_weights, eModifierType_Cloth, eModifierType_Collision, eModifierType_DynamicPaint, eModifierType_Fluidsim, eModifierType_Hook, eModifierType_MeshDeform, eModifierType_Smoke, eModifierType_Warp, eModifierType_WeightVGEdit, ListBase::first, PointCache::flag, SmokeModifierData::flow, FluidsimModifierData::fss, HookModifierData::indexar, MOD_SMOKE_TYPE_COLL, MOD_SMOKE_TYPE_DOMAIN, MOD_SMOKE_TYPE_FLOW, modifierType_getInfo(), mti, DynamicPaintSurface::next, ModifierData::next, NULL, DynamicPaintBrushSettings::paint_ramp, SmokeDomainSettings::point_cache, PTCACHE_DISK_CACHE, PTCACHE_FAKE_SMOKE, DynamicPaintSurface::ptcaches, SmokeDomainSettings::ptcaches, ClothModifierData::ptcaches, ClothModifierData::sim_parms, size(), PointCache::step, ModifierTypeInfo::structName, DynamicPaintCanvasSettings::surfaces, MeshDeformModifierData::totcagevert, HookModifierData::totindex, MeshDeformModifierData::totinfluence, MeshDeformModifierData::totvert, SmokeModifierData::type, ModifierData::type, DynamicPaintBrushSettings::vel_ramp, write_curvemapping(), write_pointcaches(), writedata(), and writestruct().
Referenced by write_objects().
static void write_motionpath (WriteData * wd, bMotionPath * mpath) [static]
Definition at line 1184 of file writefile.c.
References DATA, bMotionPath::length, NULL, bMotionPath::points, and writestruct().
Referenced by write_objects(), and write_pose().
static void write_movieclips (WriteData * wd, ListBase * idbase) [static]
Definition at line 2690 of file writefile.c.
References MovieClip::adt, WriteData::current, DATA, ListBase::first, MovieClip::id, ID_MC, mywrite(), MYWRITE_FLUSH, ID::next, MovieTracking::objects, MovieTrackingObject::reconstruction, MovieTracking::reconstruction, MovieClip::tracking, MovieTrackingObject::tracks, MovieTracking::tracks, ID::us, write_animdata(), write_movieReconstruction(), write_movieTracks(), and writestruct().
Referenced by write_file_handle().
static void write_movieReconstruction (WriteData * wd, MovieTrackingReconstruction * reconstruction) [static]
Definition at line 2684 of file writefile.c.
References MovieTrackingReconstruction::cameras, MovieTrackingReconstruction::camnr, DATA, and writestruct().
Referenced by write_movieclips().
static void write_movieTracks (WriteData * wd, ListBase * tracks) [static]
Definition at line 2669 of file writefile.c.
References DATA, ListBase::first, MovieTrackingTrack::markers, MovieTrackingTrack::markersnr, MovieTrackingTrack::next, and writestruct().
Referenced by write_movieclips().
static void write_nladata (WriteData * wd, ListBase * nlabase) [static]
Definition at line 609 of file writefile.c.
References DATA, ListBase::first, NlaTrack::next, NlaTrack::strips, write_nlastrips(), and writestruct().
Referenced by write_animdata().
static void write_nlastrips (WriteData * wd, ListBase * strips) [static]
Definition at line 592 of file writefile.c.
References DATA, NlaStrip::fcurves, ListBase::first, NlaStrip::modifiers, NlaStrip::next, NlaStrip::strips, write_fcurves(), write_fmodifiers(), and writestruct().
Referenced by write_nladata().
static void write_node_socket (WriteData * wd, bNodeSocket * sock) [static]
Definition at line 656 of file writefile.c.
References copy_v3_v3(), copy_v4_v4(), DATA, bNodeSocket::default_value, bNodeSocketValueVector::max, bNodeSocketValueFloat::max, bNodeSocketValueVector::min, bNodeSocketValueFloat::min, ntreeGetSocketType(), SOCK_FLOAT, SOCK_RGBA, SOCK_VECTOR, bNodeSocket::type, bNodeSocketValueRGBA::value, bNodeSocketValueVector::value, bNodeSocketValueFloat::value, bNodeSocketType::value_structname, and writestruct().
Referenced by write_nodetree().
static void write_nodetree (WriteData * wd, bNodeTree * ntree) [static]
Definition at line 697 of file writefile.c.
References bNodeTree::adt, CMP_NODE_CURVE_RGB, CMP_NODE_CURVE_VEC, CMP_NODE_HUECORRECT, CMP_NODE_MOVIEDISTORTION, CMP_NODE_OUTPUT_FILE, CMP_NODE_TIME, DATA, ELEM4, ListBase::first, bNodeTree::inputs, bNode::inputs, link(), bNodeTree::links, bNodeLink::next, bNodeSocket::next, bNode::next, NODE_DYNAMIC, bNodeTree::nodes, NTREE_COMPOSIT, NTREE_SHADER, NTREE_TEXTURE, bNodeTree::outputs, bNode::outputs, SH_NODE_CURVE_RGB, SH_NODE_CURVE_VEC, bNodeSocket::storage, bNode::storage, bNodeType::storagename, TEX_NODE_CURVE_RGB, TEX_NODE_CURVE_TIME, bNodeTree::type, bNode::type, bNode::typeinfo, write_animdata(), write_curvemapping(), write_node_socket(), and writestruct().
Referenced by write_lamps(), write_materials(), write_nodetrees(), write_scenes(), write_textures(), and write_worlds().
static void write_nodetrees (WriteData * wd, ListBase * idbase) [static]
Definition at line 2624 of file writefile.c.
References bNodeTree::adt, WriteData::current, ListBase::first, bNodeTree::id, ID_NT, IDP_WriteProperty(), ID::next, ID::properties, ID::us, write_animdata(), write_nodetree(), and writestruct().
Referenced by write_file_handle().
static void write_objects (WriteData * wd, ListBase * idbase) [static]
Definition at line 1416 of file writefile.c.
References bArmature::act_bone, Object::actuators, Object::adt, BLI_strncpy(), Object::bsoft, Object::constraints, Object::controllers, WriteData::current, Object::data, DATA, Object::defbase, SoftBody::effector_weights, ListBase::first, Object::id, ID_OB, IDP_WriteProperty(), Object::mat, Object::matbits, Object::modifiers, Object::mpath, mywrite(), MYWRITE_FLUSH, Bone::name, ID::next, OB_ARMATURE, Object::particlesystem, Object::pd, Object::pose, Object::prop, ID::properties, bPose::proxy_act_bone, SoftBody::ptcaches, Object::sensors, Object::soft, Object::totcol, Object::type, ID::us, write_actuators(), write_animdata(), write_constraints(), write_controllers(), write_defgroups(), write_modifiers(), write_motionpath(), write_particlesystems(), write_pointcaches(), write_pose(), write_properties(), write_sensors(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_particlesettings (WriteData * wd, ListBase * idbase) [static]
Definition at line 916 of file writefile.c.
References ParticleSettings::adt, ParticleSettings::boids, WriteData::current, DATA, ParticleSettings::dup_group, ParticleSettings::dupliweights, ParticleSettings::effector_weights, ListBase::first, ParticleSettings::fluid, Group::gobject, ParticleSettings::id, ID_PA, IDP_WriteProperty(), ParticleDupliWeight::index, MAX_MTEX, ParticleSettings::mtex, ID::next, BoidState::next, GroupObject::next, ParticleDupliWeight::next, ParticleDupliWeight::ob, GroupObject::ob, PART_PHYS_BOIDS, PART_PHYS_FLUID, ParticleSettings::pd, ParticleSettings::pd2, ParticleSettings::phystype, ID::properties, state, BoidSettings::states, ID::us, write_animdata(), write_boid_state(), and writestruct().
Referenced by write_file_handle().
static void write_particlesystems (WriteData * wd, ListBase * particles) [static]
Definition at line 967 of file writefile.c.
References ParticleData::boid, ParticleSystem::child, ParticleSystem::clmd, ClothModifierData::coll_parms, DATA, ListBase::first, SPHFluidSettings::flag, ParticleSettings::fluid, ParticleSystem::fluid_springs, ParticleData::hair, ParticleTarget::next, ParticleSystem::next, ParticleSystem::part, PART_PHYS_BOIDS, PART_PHYS_FLUID, ParticleSystem::particles, ParticleSettings::phystype, ParticleSystem::ptcaches, ClothModifierData::sim_parms, SPH_VISCOELASTIC_SPRINGS, ParticleSystem::targets, ParticleSystem::tot_fluidsprings, ParticleSystem::totchild, ParticleData::totkey, ParticleSystem::totpart, write_pointcaches(), and writestruct().
Referenced by write_objects().
static void write_pointcaches (WriteData * wd, ListBase * ptcaches) [static]
Definition at line 881 of file writefile.c.
References BPHYS_TOT_DATA, PTCacheExtra::data, PTCacheMem::data, DATA, PTCacheMem::data_types, PTCacheMem::extradata, ListBase::first, PointCache::flag, i, MEM_allocN_len(), PointCache::mem_cache, PTCacheExtra::next, PTCacheMem::next, PointCache::next, ptcache_data_struct, PTCACHE_DISK_CACHE, ptcache_extra_struct, PTCacheExtra::totdata, PTCacheMem::totpoint, PTCacheExtra::type, writedata(), and writestruct().
Referenced by write_modifiers(), write_objects(), and write_particlesystems().
static void write_pose (WriteData * wd, bPose * pose) [static]
Definition at line 1241 of file writefile.c.
References bPose::agroups, bPoseChannel::bone, BONE_SELECTED, bPose::chanbase, bPoseChannel::constraints, DATA, ListBase::first, Bone::flag, get_ikparam_name(), IDP_WriteProperty(), bPose::ikparam, bPoseChannel::mpath, bPoseChannel::next, bActionGroup::next, bPoseChannel::prop, bPoseChannel::selectflag, write_constraints(), write_motionpath(), and writestruct().
Referenced by write_objects().
static void write_previews (WriteData * wd, PreviewImage * prv) [static]
Definition at line 1867 of file writefile.c.
References DATA, PreviewImage::h, NULL, PreviewImage::rect, USER_SAVE_PREVIEWS, PreviewImage::w, writedata(), and writestruct().
Referenced by write_images(), write_lamps(), write_materials(), write_textures(), and write_worlds().
static void write_properties (WriteData * wd, ListBase * lb) [static]
Definition at line 1008 of file writefile.c.
References bProperty::data, DATA, ListBase::first, MEM_allocN_len(), bProperty::next, bProperty::poin, writedata(), and writestruct().
Referenced by write_objects().
static void write_region (WriteData * wd, ARegion * ar, int spacetype) [static]
Definition at line 2256 of file writefile.c.
References RegionView3D::clipbb, DATA, RegionView3D::localvd, ARegion::regiondata, ARegion::regiontype, RGN_TYPE_WINDOW, SPACE_VIEW3D, and writestruct().
Referenced by write_screens().
static void write_renderinfo (WriteData * wd, Main * mainvar) [static]
Definition at line 766 of file writefile.c.
References BLI_strncpy(), current_screen_compat(), data, RenderData::efra, RenderInfo::efra, ListBase::first, Scene::id, ID::lib, ID::name, ID::next, NULL, Scene::r, R_BG_RENDER, REND, RenderData::scemode, bScreen::scene, Main::scene, RenderInfo::scene_name, RenderData::sfra, RenderInfo::sfra, and writedata().
Referenced by write_file_handle().
static void write_scenes (WriteData * wd, ListBase * scebase) [static]
Definition at line 2063 of file writefile.c.
References Scene::adt, RenderData::avicodecdata, Scene::base, AviCodecData::cbFormat, AviCodecData::cbParms, QuicktimeCodecData::cdParms, QuicktimeCodecData::cdSize, Strip::color_balance, Strip::crop, DATA, Strip::done, Scene::ed, Sequence::effectdata, RenderData::ffcodecdata, ListBase::first, Sequence::flag, Scene::id, ID_SCE, IDP_WriteProperty(), Scene::keyingsets, RenderData::layers, AviCodecData::lpFormat, AviCodecData::lpParms, Scene::markers, MEM_allocN_len(), Editing::metastack, mywrite(), MYWRITE_FLUSH, ID::next, SceneRenderLayer::next, TransformOrientation::next, TimeMarker::next, MetaStack::next, Base::next, Scene::nodetree, Sequence::plugin, FFMpegCodecData::properties, ID::properties, Strip::proxy, RenderData::qtcodecdata, Scene::r, ToolSettings::sculpt, SEQ_BEGIN, SEQ_COLOR, SEQ_END, SEQ_GLOW, SEQ_HD_SOUND, SEQ_IMAGE, SEQ_MOVIE, SEQ_RAM_SOUND, SEQ_SPEED, SEQ_TRANSFORM, SEQ_USE_COLOR_BALANCE, SEQ_USE_CROP, SEQ_USE_PROXY, SEQ_USE_TRANSFORM, SEQ_WIPE, Sequence::strip, Strip::stripdata, Scene::toolsettings, Strip::transform, Scene::transform_spaces, Sequence::type, ToolSettings::uvsculpt, ToolSettings::vpaint, ToolSettings::wpaint, write_animdata(), write_keyingsets(), write_nodetree(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_screens (WriteData * wd, ListBase * scrbase) [static]
Definition at line 2282 of file writefile.c.
References SpaceNla::ads, SpaceIpo::ads, bScreen::areabase, View3D::bgpicbase, SpaceScript::but_refs, SpaceImage::cumap, TreeStore::data, DATA, bScreen::edgebase, ListBase::first, SpaceIpo::ghostCurves, SpaceConsole::history, bScreen::id, ID_SCRN, IDP_WriteProperty(), ListBase::last, ConsoleLine::len, ConsoleLine::line, View3D::localvd, ID::next, SpaceLink::next, ConsoleLine::next, BGpic::next, Panel::next, ARegion::next, ScrArea::next, ScrEdge::next, ScrVert::next, NULL, ARegion::panels, SpaceFile::params, ID::properties, SpaceLink::regionbase, ScrArea::regionbase, SPACE_ACTION, SPACE_BUTS, SPACE_CLIP, SPACE_CONSOLE, SPACE_FILE, SPACE_IMAGE, SPACE_IPO, SPACE_LOGIC, SPACE_NLA, SPACE_NODE, SPACE_OUTLINER, SPACE_SCRIPT, SPACE_SEQ, SPACE_TEXT, SPACE_TIME, SPACE_USERPREF, SPACE_VIEW3D, ScrArea::spacedata, SpaceLink::spacetype, ScrArea::spacetype, SpaceOops::treestore, TreeStore::usedelem, bScreen::vertbase, write_curvemapping(), write_region(), writedata(), and writestruct().
Referenced by write_file_handle().
static void write_scripts (WriteData * wd, ListBase * idbase) [static]
Definition at line 2657 of file writefile.c.
References WriteData::current, ListBase::first, Script::id, ID_SCRIPT, IDP_WriteProperty(), ID::next, ID::properties, ID::us, and writestruct().
Referenced by write_file_handle().
static void write_sensors (WriteData * wd, ListBase * lb) [static]
Definition at line 1023 of file writefile.c.
References DATA, bSensor::data, ListBase::first, bSensor::links, bSensor::next, SENS_ACTUATOR, SENS_ARMATURE, SENS_COLLISION, SENS_DELAY, SENS_JOYSTICK, SENS_KEYBOARD, SENS_MESSAGE, SENS_MOUSE, SENS_NEAR, SENS_PROPERTY, SENS_RADAR, SENS_RANDOM, SENS_RAY, SENS_TOUCH, bSensor::totlinks, bSensor::type, writedata(), and writestruct().
Referenced by write_objects().
static void write_sounds (WriteData * wd, ListBase * idbase) [static]
Definition at line 2578 of file writefile.c.
References WriteData::current, PackedFile::data, DATA, ListBase::first, bSound::id, ID_SO, IDP_WriteProperty(), mywrite(), MYWRITE_FLUSH, ID::next, bSound::packedfile, pf, ID::properties, PackedFile::size, ID::us, writedata(), and writestruct().
Referenced by write_file_handle().
static void write_speakers (WriteData * wd, ListBase * idbase) [static]
Definition at line 2561 of file writefile.c.
References Speaker::adt, WriteData::current, ListBase::first, Speaker::id, ID_SPK, IDP_WriteProperty(), ID::next, ID::properties, ID::us, write_animdata(), and writestruct().
Referenced by write_file_handle().
static void write_texts (WriteData * wd, ListBase * idbase) [static]
Definition at line 2516 of file writefile.c.
References DATA, ListBase::first, Text::flags, Text::id, ID_TXT, IDP_WriteProperty(), TextLine::len, TextLine::line, Text::lines, Text::markers, mywrite(), MYWRITE_FLUSH, Text::name, ID::next, TextMarker::next, TextLine::next, ID::properties, strlen(), TXT_ISEXT, TXT_ISMEM, writedata(), and writestruct().
Referenced by write_file_handle().
static void write_textures (WriteData * wd, ListBase * idbase) [static]
Definition at line 1919 of file writefile.c.
References Tex::adt, Tex::coba, PointDensity::coba, WriteData::current, DATA, Tex::env, PointDensity::falloff_curve, ListBase::first, Tex::id, ID_TE, IDP_WriteProperty(), mywrite(), MYWRITE_FLUSH, ID::next, Tex::nodetree, Tex::ot, Tex::pd, Tex::plugin, Tex::preview, ID::properties, TEX_ENVMAP, TEX_OCEAN, TEX_PLUGIN, TEX_POINTDENSITY, TEX_VOXELDATA, Tex::type, ID::us, Tex::vd, write_animdata(), write_curvemapping(), write_nodetree(), write_previews(), and writestruct().
Referenced by write_file_handle().
static void write_thumb (WriteData * wd, const int * img) [static]
Definition at line 2773 of file writefile.c.
References TEST, and writedata().
Referenced by write_file_handle().
static void write_userdef (WriteData * wd) [static]
Definition at line 795 of file writefile.c.
References wmKeyMapDiffItem::add_item, DATA, wmKeyMap::diff_items, ListBase::first, wmKeyMap::items, bTheme::next, wmKeyMap::next, wmKeyMapDiffItem::next, bAddon::next, uiStyle::next, wmKeyMapItem::next, wmKeyMapDiffItem::remove_item, USER, write_keymapitem(), and writestruct().
Referenced by write_file_handle().
static void write_vfonts (WriteData * wd, ListBase * idbase) [static]
Definition at line 1472 of file writefile.c.
References WriteData::current, PackedFile::data, DATA, ListBase::first, VFont::id, ID_VF, IDP_WriteProperty(), ID::next, VFont::packedfile, pf, ID::properties, PackedFile::size, ID::us, writedata(), and writestruct().
Referenced by write_file_handle().
static void write_windowmanagers (WriteData * wd, ListBase * lb) [static]
Definition at line 2243 of file writefile.c.
References DATA, ListBase::first, wmWindowManager::id, ID_WM, wmWindow::next, ID::next, wmWindowManager::windows, and writestruct().
Referenced by write_file_handle().
static void write_worlds (WriteData * wd, ListBase * idbase) [static]
Definition at line 1997 of file writefile.c.
References World::adt, WriteData::current, DATA, ListBase::first, World::id, ID_WO, IDP_WriteProperty(), MAX_MTEX, World::mtex, ID::next, World::nodetree, World::preview, ID::properties, ID::us, write_animdata(), write_nodetree(), write_previews(), and writestruct().
Referenced by write_file_handle().
static void writedata (WriteData * wd, int filecode, int len, const void * adr) [static]
Definition at line 357 of file writefile.c.
References BHead::code, len(), BHead::len, mywrite(), BHead::nr, NULL, BHead::old, and BHead::SDNAnr.
Referenced by IDP_WriteArray(), IDP_WriteString(), write_animdata(), write_constraints(), write_controllers(), write_curves(), write_fcurves(), write_file_handle(), write_fmodifiers(), write_images(), write_keyingsets(), write_keys(), write_mballs(), write_mdisps(), write_meshs(), write_modifiers(), write_objects(), write_pointcaches(), write_previews(), write_properties(), write_renderinfo(), write_scenes(), write_screens(), write_sensors(), write_sounds(), write_texts(), write_thumb(), and write_vfonts().
static void writedata_do_write (WriteData * wd, const void * mem, int memlen) [static]
Definition at line 207 of file writefile.c.
References add_memfilechunk(), WriteData::current, WriteData::error, WriteData::file, and NULL.
Referenced by endwrite(), and mywrite().
static void writedata_free (WriteData * wd) [static]
Definition at line 223 of file writefile.c.
References WriteData::buf, DNA_sdna_free(), MEM_freeN(), and WriteData::sdna.
Referenced by endwrite().
static WriteData* writedata_new (int file) [static]
Definition at line 188 of file writefile.c.
References WriteData::buf, DNA_sdna_from_data(), DNAlen, DNAstr, WriteData::file, MEM_callocN(), MEM_mallocN(), MYWRITE_BUFFER_SIZE, NULL, and WriteData::sdna.
Referenced by bgnwrite().
static void writestruct (WriteData * wd, int filecode, const char * structname, int nr, void * adr) [static]
Definition at line 330 of file writefile.c.
References BHead::code, DNA_struct_find_nr(), BHead::len, mywrite(), BHead::nr, NULL, BHead::old, WriteData::sdna, BHead::SDNAnr, SDNA::structs, and SDNA::typelens.
Referenced by IDP_WriteIDPArray(), IDP_WriteProperty(), write_actions(), write_actuators(), write_animdata(), write_armatures(), write_boid_state(), write_bone(), write_brushes(), write_cameras(), write_constraints(), write_controllers(), write_curvemapping(), write_curves(), write_customdata(), write_defgroups(), write_dverts(), write_fcurves(), write_fmodifiers(), write_global(), write_gpencils(), write_groups(), write_images(), write_keyingsets(), write_keymapitem(), write_keys(), write_lamps(), write_lattices(), write_libraries(), write_materials(), write_mballs(), write_mdisps(), write_meshs(), write_modifiers(), write_motionpath(), write_movieclips(), write_movieReconstruction(), write_movieTracks(), write_nladata(), write_nlastrips(), write_node_socket(), write_nodetree(), write_nodetrees(), write_objects(), write_particlesettings(), write_particlesystems(), write_pointcaches(), write_pose(), write_previews(), write_properties(), write_region(), write_scenes(), write_screens(), write_scripts(), write_sensors(), write_sounds(), write_speakers(), write_texts(), write_textures(), write_userdef(), write_vfonts(), write_windowmanagers(), and write_worlds().
Variable Documentation
const char* ptcache_data_struct[] [static]
Initial value:
 {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "BoidData"
}
Definition at line 867 of file writefile.c.
Referenced by write_pointcaches().
const char* ptcache_extra_struct[] [static]
Initial value:
 {
    "",
    "ParticleSpring"
}
Definition at line 877 of file writefile.c.
Referenced by write_pointcaches().