Blender: KX_FontObject.cpp File Reference
KX_FontObject.cpp File Reference
Ketsji
#include "KX_FontObject.h"
#include "DNA_curve_types.h"
#include "KX_Scene.h"
#include "KX_PythonInit.h"
#include "BLI_math.h"
#include "StringValue.h"
#include "BLI_blenlib.h"
#include "BKE_global.h"
#include "BKE_font.h"
#include "BKE_main.h"
#include "DNA_packedFile_types.h"
#include "BLF_api.h"
Defines
#define BGE_FONT_RES 100
Functions
int GetFontId (VFont *font)
std::vector< STR_String > split_string (STR_String str)
Detailed Description
Definition in file KX_FontObject.cpp.
Define Documentation
#define BGE_FONT_RES 100
Definition at line 50 of file KX_FontObject.cpp.
Referenced by KX_FontObject::DrawText().
Function Documentation
int GetFontId (VFont * font)
Definition at line 120 of file KX_FontObject.cpp.
References BLF_load(), BLF_load_mem(), BLI_path_abs(), BLI_strncpy(), PackedFile::data, FO_BUILTIN_NAME, G, VFont::name, NULL, VFont::packedfile, and PackedFile::size.
Referenced by KX_FontObject::KX_FontObject().
std::vector<STR_String> split_string (STR_String str)
Definition at line 55 of file KX_FontObject.cpp.
References STR_String::GetAt(), STR_String::Length(), and STR_String::Mid().
Referenced by KX_FontObject::DrawText(), and KX_FontObject::KX_FontObject().