Blender: GHOST_DisplayManager Class Reference
GHOST_DisplayManager Class Reference
#include <GHOST_DisplayManager.h>
Public Types
enum { kMainDisplay = 0 }
Public Member Functions
GHOST_DisplayManager (void)
virtual ~GHOST_DisplayManager (void)
virtual GHOST_TSuccess initialize (void)
virtual GHOST_TSuccess getNumDisplays (GHOST_TUns8 &numDisplays) const
virtual GHOST_TSuccess getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 &numSettings) const
virtual GHOST_TSuccess getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting &setting) const
virtual GHOST_TSuccess getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting &setting) const
virtual GHOST_TSuccess setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting &setting)
Protected Types
typedef std::vector
< GHOST_DisplaySetting > GHOST_DisplaySettings
Protected Member Functions
GHOST_TSuccess findMatch (GHOST_TUns8 display, const GHOST_DisplaySetting &setting, GHOST_DisplaySetting &match) const
GHOST_TSuccess initializeSettings (void)
Protected Attributes
bool m_settingsInitialized
std::vector
< GHOST_DisplaySettings > m_settings
Detailed Description
Manages system displays (platform independent implementation).
Author:
Maarten Gribnau
Date:
September 21, 2001
Definition at line 45 of file GHOST_DisplayManager.h.
Member Typedef Documentation
typedef std::vector<GHOST_DisplaySetting> GHOST_DisplayManager::GHOST_DisplaySettings [protected]
Definition at line 113 of file GHOST_DisplayManager.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
kMainDisplay
Definition at line 48 of file GHOST_DisplayManager.h.
Constructor & Destructor Documentation
GHOST_DisplayManager::GHOST_DisplayManager (void)
Constructor.
Copyright (C) 2001 NaN Technologies B.V.
Author:
Maarten Gribnau
Date:
September 21, 2001
Definition at line 43 of file GHOST_DisplayManager.cpp.
GHOST_DisplayManager::~GHOST_DisplayManager (void) [virtual]
Destructor.
Definition at line 50 of file GHOST_DisplayManager.cpp.
Member Function Documentation
GHOST_TSuccess GHOST_DisplayManager::findMatch (GHOST_TUns8 display, const GHOST_DisplaySetting & setting, GHOST_DisplaySetting & match) const [protected]
Finds the best display settings match.
Parameters:
display The index of the display device.
setting The setting to match.
match The optimal display setting.
Returns:
Indication of success.
Definition at line 144 of file GHOST_DisplayManager.cpp.
References GHOST_DisplaySetting::bpp, display(), GHOST_DisplaySetting::frequency, GHOST_ASSERT, GHOST_kSuccess, GHOST_PRINT, i, m_settings, m_settingsInitialized, size(), GHOST_DisplaySetting::xPixels, and GHOST_DisplaySetting::yPixels.
Referenced by GHOST_DisplayManagerWin32::setCurrentDisplaySetting().
GHOST_TSuccess GHOST_DisplayManager::getCurrentDisplaySetting (GHOST_TUns8 display, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The current setting of the display device with this index.
Returns:
Indication of success.
Reimplemented in GHOST_DisplayManagerCarbon, GHOST_DisplayManagerCocoa, GHOST_DisplayManagerNULL, GHOST_DisplayManagerSDL, GHOST_DisplayManagerWin32, and GHOST_DisplayManagerX11.
Definition at line 126 of file GHOST_DisplayManager.cpp.
References GHOST_kFailure.
Referenced by GHOST_System::beginFullScreen(), and GHOST_System::createFullScreenWindow().
GHOST_TSuccess GHOST_DisplayManager::getDisplaySetting (GHOST_TUns8 display, GHOST_TInt32 index, GHOST_DisplaySetting & setting) const [virtual]
Returns the current setting for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
index The setting index to be returned.
setting The setting of the display device with this index.
Returns:
Indication of success.
Reimplemented in GHOST_DisplayManagerCarbon, GHOST_DisplayManagerCocoa, GHOST_DisplayManagerNULL, GHOST_DisplayManagerSDL, GHOST_DisplayManagerWin32, and GHOST_DisplayManagerX11.
Definition at line 103 of file GHOST_DisplayManager.cpp.
References display(), getNumDisplays(), GHOST_ASSERT, GHOST_kFailure, GHOST_kSuccess, m_settings, m_settingsInitialized, and size().
Referenced by initializeSettings().
GHOST_TSuccess GHOST_DisplayManager::getNumDisplays (GHOST_TUns8 & numDisplays) const [virtual]
Returns the number of display devices on this system.
Parameters:
numDisplays The number of displays on this system.
Returns:
Indication of success.
Reimplemented in GHOST_DisplayManagerCarbon, GHOST_DisplayManagerCocoa, GHOST_DisplayManagerNULL, GHOST_DisplayManagerSDL, GHOST_DisplayManagerWin32, and GHOST_DisplayManagerX11.
Definition at line 72 of file GHOST_DisplayManager.cpp.
References GHOST_kFailure.
Referenced by getDisplaySetting(), GHOST_SystemWin32::getNumDisplays(), getNumDisplaySettings(), and initializeSettings().
GHOST_TSuccess GHOST_DisplayManager::getNumDisplaySettings (GHOST_TUns8 display, GHOST_TInt32 & numSettings) const [virtual]
Returns the number of display settings for this display device.
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
numSettings The number of settings of the display device with this index.
Returns:
Indication of success.
Reimplemented in GHOST_DisplayManagerCarbon, GHOST_DisplayManagerCocoa, GHOST_DisplayManagerNULL, GHOST_DisplayManagerSDL, GHOST_DisplayManagerWin32, and GHOST_DisplayManagerX11.
Definition at line 81 of file GHOST_DisplayManager.cpp.
References display(), getNumDisplays(), GHOST_ASSERT, GHOST_kFailure, GHOST_kSuccess, m_settings, and m_settingsInitialized.
Referenced by initializeSettings().
GHOST_TSuccess GHOST_DisplayManager::initialize (void) [virtual]
Initializes the list with devices and settings.
Returns:
Indication of success.
Definition at line 56 of file GHOST_DisplayManager.cpp.
References GHOST_kSuccess, initializeSettings(), and m_settingsInitialized.
Referenced by GHOST_SystemCarbon::GHOST_SystemCarbon(), GHOST_SystemCocoa::GHOST_SystemCocoa(), and GHOST_SystemWin32::GHOST_SystemWin32().
GHOST_TSuccess GHOST_DisplayManager::initializeSettings (void) [protected]
Retrieves settings for each display device and stores them.
Returns:
Indication of success.
Definition at line 197 of file GHOST_DisplayManager.cpp.
References display(), getDisplaySetting(), getNumDisplays(), getNumDisplaySettings(), GHOST_kSuccess, and m_settings.
Referenced by initialize().
GHOST_TSuccess GHOST_DisplayManager::setCurrentDisplaySetting (GHOST_TUns8 display, const GHOST_DisplaySetting & setting) [virtual]
Changes the current setting for this display device. The setting given to this method is matched againts the available diplay settings. The best match is activated (
See also:
findMatch()).
Parameters:
display The index of the display to query with 0 <= display < getNumDisplays().
setting The setting of the display device to be matched and activated.
Returns:
Indication of success.
Reimplemented in GHOST_DisplayManagerCarbon, GHOST_DisplayManagerCocoa, GHOST_DisplayManagerNULL, GHOST_DisplayManagerSDL, GHOST_DisplayManagerWin32, and GHOST_DisplayManagerX11.
Definition at line 135 of file GHOST_DisplayManager.cpp.
References GHOST_kFailure.
Referenced by GHOST_System::beginFullScreen(), GHOST_System::endFullScreen(), and GHOST_System::updateFullScreen().
Member Data Documentation
std::vector<GHOST_DisplaySettings> GHOST_DisplayManager::m_settings [protected]
The list with display settings for the main display.
Definition at line 135 of file GHOST_DisplayManager.h.
Referenced by findMatch(), getDisplaySetting(), getNumDisplaySettings(), and initializeSettings().
bool GHOST_DisplayManager::m_settingsInitialized [protected]
Tells whether the list of display modes has been stored already.
Definition at line 133 of file GHOST_DisplayManager.h.
Referenced by findMatch(), getDisplaySetting(), getNumDisplaySettings(), and initialize().
The documentation for this class was generated from the following files:
GHOST_DisplayManager.h
GHOST_DisplayManager.cpp