Blender: Projections Class Reference
Projections Class Reference
#include <Projections.h>
Public Member Functions
Projections ()
Projections (LONG cube[2][3], LONG trig[3][3], LONG error, int triind)
Projections (Projections *parent)
Projections (Projections *parent, int box[3], int depth)
int getIntersectionMasks (UCHAR cedgemask, UCHAR &edgemask)
UCHAR getChildrenMasks (UCHAR cvertmask, UCHAR vertmask[8])
UCHAR getBoxMask ()
void getSubProjectionsSimple (Projections *p[8])
void shift (int off[3])
void shiftNoPrimary (int off[3])
int isIntersecting ()
int isIntersectingNoPrimary ()
int isIntersecting (int edgeInd)
int isIntersecting (int edgeInd, int faceInd)
int isIntersectingPrimary (int edgeInd)
double getIntersection (int edgeInd)
float getIntersectionPrimary (int edgeInd)
void crossProduct (LONG a[3], LONG b[3], LONG res[3])
void crossProduct (double a[3], double b[3], double res[3])
LONG dotProduct (LONG a[3], LONG b[3])
void normalize (double a[3])
Public Attributes
InheritableProjections * inherit
Inheritable portion.
LONG cubeProj [13][6]
Projections of the cube vertices.
Detailed Description
Class for projections of cube / triangle vertices on the separating axes
Definition at line 88 of file Projections.h.
Constructor & Destructor Documentation
Projections::Projections () [inline]
Definition at line 99 of file Projections.h.
Referenced by getSubProjectionsSimple().
Projections::Projections (LONG cube[2][3], LONG trig[3][3], LONG error, int triind) [inline]
Construction from a cube (axes aligned) and triangle
Create axes
Normalize face normal and store
Generate projections
Definition at line 107 of file Projections.h.
References crossProduct(), cubeProj, dotProduct(), i, InheritableProjections::index, inherit, LONG, max, min, InheritableProjections::norm, normalize(), InheritableProjections::trigEdgeProj, InheritableProjections::trigProj, InheritableProjections::trigVertProj, and vertmap.
Projections::Projections (Projections * parent) [inline]
Construction from a parent Projections object and the index of the children
Definition at line 252 of file Projections.h.
References cubeProj, i, and inherit.
Projections::Projections (Projections * parent, int box[3], int depth) [inline]
Definition at line 268 of file Projections.h.
References cubeProj, i, and inherit.
Member Function Documentation
void Projections::crossProduct (LONG a[3], LONG b[3], LONG res[3]) [inline]
Method to perform cross-product
Definition at line 811 of file Projections.h.
Referenced by Projections().
void Projections::crossProduct (double a[3], double b[3], double res[3]) [inline]
Definition at line 817 of file Projections.h.
LONG Projections::dotProduct (LONG a[3], LONG b[3]) [inline]
Method to perform dot product
Definition at line 827 of file Projections.h.
Referenced by Projections().
UCHAR Projections::getBoxMask () [inline]
Definition at line 455 of file Projections.h.
References cubeProj, i, inherit, len(), LONG, InheritableProjections::trigProj, and UCHAR.
UCHAR Projections::getChildrenMasks (UCHAR cvertmask, UCHAR vertmask[8]) [inline]
Retrieving children masks using PRIMARY AXES
Definition at line 366 of file Projections.h.
References cubeProj, i, inherit, len(), LONG, InheritableProjections::trigProj, InheritableProjections::trigVertProj, and UCHAR.
double Projections::getIntersection (int edgeInd) [inline]
Definition at line 737 of file Projections.h.
References cubeProj, edgemap, i, inherit, LONG, InheritableProjections::trigProj, and vertmap.
int Projections::getIntersectionMasks (UCHAR cedgemask, UCHAR & edgemask) [inline]
Testing intersection based on vertex/edge masks
Definition at line 291 of file Projections.h.
References cubeProj, i, inherit, LONG, InheritableProjections::trigEdgeProj, InheritableProjections::trigProj, and UCHAR.
float Projections::getIntersectionPrimary (int edgeInd) [inline]
Definition at line 783 of file Projections.h.
References cubeProj, i, inherit, LONG, and InheritableProjections::trigProj.
void Projections::getSubProjectionsSimple (Projections * p[8]) [inline]
Get projections for sub-cubes (simple axes)
Definition at line 496 of file Projections.h.
References cubeProj, i, inherit, len(), LONG, and Projections().
int Projections::isIntersecting (int edgeInd) [inline]
Method to test intersection of the triangle and one edge
Definition at line 607 of file Projections.h.
References cubeProj, edgemap, i, inherit, LONG, InheritableProjections::trigProj, and vertmap.
int Projections::isIntersecting (int edgeInd, int faceInd) [inline]
Method to test intersection of one triangle edge and one cube face
Definition at line 647 of file Projections.h.
References cubeProj, facemap, i, inherit, LONG, InheritableProjections::trigVertProj, and vertmap.
int Projections::isIntersecting () [inline]
Method to test intersection of the triangle and the cube
Definition at line 548 of file Projections.h.
References cubeProj, i, inherit, LONG, and InheritableProjections::trigProj.
int Projections::isIntersectingNoPrimary () [inline]
Definition at line 576 of file Projections.h.
References cubeProj, i, inherit, LONG, and InheritableProjections::trigProj.
int Projections::isIntersectingPrimary (int edgeInd) [inline]
Definition at line 706 of file Projections.h.
References cubeProj, i, inherit, LONG, and InheritableProjections::trigProj.
void Projections::normalize (double a[3]) [inline]
Definition at line 832 of file Projections.h.
References sqrt().
Referenced by Projections().
void Projections::shift (int off[3]) [inline]
Shifting a cube to a new origin
Definition at line 529 of file Projections.h.
References cubeProj, and i.
void Projections::shiftNoPrimary (int off[3]) [inline]
Definition at line 537 of file Projections.h.
References cubeProj, and i.
Member Data Documentation
LONG Projections::cubeProj[13][6]
Projections of the cube vertices.
Definition at line 95 of file Projections.h.
Referenced by getBoxMask(), getChildrenMasks(), getIntersection(), getIntersectionMasks(), getIntersectionPrimary(), getSubProjectionsSimple(), isIntersecting(), isIntersectingNoPrimary(), isIntersectingPrimary(), Projections(), shift(), and shiftNoPrimary().
InheritableProjections* Projections::inherit
Inheritable portion.
Definition at line 92 of file Projections.h.
Referenced by getBoxMask(), getChildrenMasks(), getIntersection(), getIntersectionMasks(), getIntersectionPrimary(), getSubProjectionsSimple(), isIntersecting(), isIntersectingNoPrimary(), isIntersectingPrimary(), and Projections().
The documentation for this class was generated from the following file:
Projections.h