Blender: bmesh_mesh_conv.c File Reference
bmesh_mesh_conv.c File Reference
BMesh
#include "DNA_mesh_types.h"
#include "DNA_meshdata_types.h"
#include "DNA_object_types.h"
#include "DNA_modifier_types.h"
#include "DNA_key_types.h"
#include "MEM_guardedalloc.h"
#include "BLI_listbase.h"
#include "BLI_array.h"
#include "BLI_math_vector.h"
#include "BKE_mesh.h"
#include "BKE_customdata.h"
#include "BKE_multires.h"
#include "BKE_global.h"
#include "BKE_main.h"
#include "BKE_key.h"
#include "bmesh.h"
#include "intern/bmesh_private.h"
Functions
void BM_mesh_bm_from_me (BMesh *bm, Mesh *me, int set_key, int act_key_nr)
static BMVert ** bm_to_mesh_vertex_map (BMesh *bm, int ototvert)
static int bm_to_mesh_shape_layer_index_from_kb (BMesh *bm, KeyBlock *currkey)
BLI_INLINE void bmesh_quick_edgedraw_flag (MEdge *med, BMEdge *e)
void BM_mesh_bm_to_me (BMesh *bm, Mesh *me, int dotess)
Detailed Description
BM mesh conversion functions.
Converting Shape Keys
When converting to/from a Mesh/BMesh you can optionally pass a shape key to edit. This has the effect of editing the shape key-block rather then the original mesh vertex coords (although additional geometry is still allowed and uses fallback locations on converting).
While this works for any mesh/bmesh this is made use of by entering and exiting edit-mode.
There are comments in code but this should help explain the general intention as to how this works converting from/to bmesh.
User Perspective
Editmode operations when a shape key-block is active edits only that key-block.
The first Basis key-block always matches the Mesh verts.
Changing vertex locations of _any_ Basis will apply offsets to those shape keys using this as their Basis.
Entering EditMode - #BM_mesh_bm_from_me
the active key-block is used for BMesh vertex locations on entering edit-mode. So obviously the meshes vertex locations remain unchanged and the shape key its self is not being edited directly. Simply the BMVert.co is a initialized from active shape key (when its set).
all key-blocks are added as CustomData layers (read code for details).
Exiting EditMode - #BM_mesh_bm_to_me
This is where the most confusing code is! Won't attempt to document the details here, for that read the code. But basics are as follows.
Vertex locations (possibly modified from initial active key-block) are copied directly into MVert.co (special confusing note that these may be restored later, when editing the 'Basis', read on).
if the 'Key' is relative, and the active key-block is the basis for ANY other key-blocks - get an array of offsets between the new vertex locations and the original shape key (before entering edit-mode), these offsets get applied later on to inactive key-blocks using the active one (which we are editing) as their Basis.
Copying the locations back to the shape keys is quite confusing... One main area of confusion is that when editing a 'Basis' key-block 'me->key->refkey' The coords are written into the mesh, from the users perspective the Basis coords are written into the mesh when exiting edit-mode.
When _not_ editing the 'Basis', the original vertex locations (stored in the mesh and unchanged during edit-mode), are copied back into the mesh.
This has the effect from the users POV of leaving the mesh un-touched, and only editing the active shape key-block.
Definition in file bmesh_mesh_conv.c.
Function Documentation
void BM_mesh_bm_from_me (BMesh * bm, Mesh * me, int set_key, int act_key_nr)
Definition at line 102 of file bmesh_mesh_conv.c.
References Mesh::act_face, BMesh::act_face, BLI_array_declare, BLI_array_empty, BLI_array_free, BLI_array_growitems, BLI_findlink(), Key::block, BM_EDGE, BM_edge_create(), BM_edge_flag_from_mflag(), BM_edge_select_set(), BM_EDGES_OF_MESH, BM_elem_float_data_set(), BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_create(), BM_face_flag_from_mflag(), BM_face_select_set(), BM_FACES_OF_MESH, BM_ITER_ELEM, BM_ITER_ELEM_INDEX, BM_ITER_MESH, BM_ITER_MESH_INDEX, BM_LOOP, BM_LOOPS_OF_FACE, BM_select_history_store, BM_VERT, BM_vert_create(), BM_vert_flag_from_mflag(), BM_vert_select_set(), BM_VERTS_OF_MESH, MVert::bweight, MEdge::bweight, CD_ASSIGN, CD_BWEIGHT, CD_CALLOC, CD_CREASE, CD_MASK_BMESH, CD_MLOOPUV, CD_MTEXPOLY, CD_SHAPE_KEYINDEX, CD_SHAPEKEY, MVert::co, co, copy_v3_v3(), MEdge::crease, CustomData_add_layer(), CustomData_add_layer_named(), CustomData_bmesh_get(), CustomData_bmesh_get_n(), CustomData_bmesh_init_pool(), CustomData_copy(), CustomData_free(), CustomData_get_layer_index_n(), CustomData_has_layer(), CustomData_number_of_layers(), CustomData_set_layer_name(), CustomData_to_bmesh_block(), KeyBlock::data, BMHeader::data, MLoop::e, BMesh::edata, BMesh::elem_index_dirty, FALSE, ListBase::first, MEdge::flag, MVert::flag, MPoly::flag, BMEdge::head, BMVert::head, BMFace::head, BMLoop::head, BMHeader::hflag, i, Mesh::id, MSelect::index, Mesh::key, CustomData::layers, BMesh::ldata, Mesh::ldata, MPoly::loopstart, BMFace::mat_nr, MPoly::mat_nr, ME_ESEL, ME_FACE_SEL, ME_FSEL, ME_VSEL, Mesh::medge, MEM_callocN(), MEM_freeN(), MEM_mallocN(), Mesh::mloop, Mesh::mpoly, Mesh::mselect, Mesh::mvert, KeyBlock::name, ID::name, CustomDataLayer::name, KeyBlock::next, MVert::no, BMVert::no, normal_short_to_float_v3(), NULL, BMesh::pdata, SELECT, BMesh::shapenr, BMesh::totedge, Mesh::totedge, KeyBlock::totelem, BMesh::totface, BMesh::totloop, Mesh::totloop, MPoly::totloop, Mesh::totpoly, Mesh::totselect, BMesh::totvert, Mesh::totvert, TRUE, MSelect::type, KeyBlock::uid, CustomDataLayer::uid, Key::uidgen, MLoop::v, BMEdge::v1, MEdge::v1, BMEdge::v2, MEdge::v2, and BMesh::vdata.
Referenced by BKE_mesh_to_bmesh(), bmo_mesh_to_bmesh_exec(), bpy_bmesh_from_mesh(), and undoMesh_to_editbtMesh().
void BM_mesh_bm_to_me (BMesh * bm, Mesh * me, int dotess)
Definition at line 500 of file bmesh_mesh_conv.c.
References Mesh::act_face, BMesh::act_face, add_keyblock(), add_v3_v3(), BKE_mesh_tessface_calc(), BLI_countlist(), BLI_findlink(), Key::block, BM_CHECK_ELEMENT, BM_EDGE, BM_edge_flag_to_mflag(), BM_EDGES_OF_MESH, BM_elem_index_get, BM_elem_index_set, BM_FACE, BM_face_flag_to_mflag(), BM_FACES_OF_MESH, BM_ITER_MESH, BM_ITER_MESH_INDEX, BM_iter_new(), BM_iter_step(), BM_LOOPS_OF_FACE, bm_to_mesh_shape_layer_index_from_kb(), bm_to_mesh_vertex_map(), BM_VERT, BM_vert_flag_to_mflag(), BM_VERTS_OF_MESH, bmesh_quick_edgedraw_flag(), MVert::bweight, MEdge::bweight, CD_ASSIGN, CD_BWEIGHT, CD_CALLOC, CD_CREASE, CD_MASK_MESH, CD_MEDGE, CD_MLOOP, CD_MPOLY, CD_MVERT, CD_SHAPE_KEYINDEX, CD_SHAPEKEY, MVert::co, BMVert::co, copy_v3_v3(), MEdge::crease, CustomData_add_layer(), CustomData_bmesh_get(), CustomData_bmesh_get_n(), CustomData_copy(), CustomData_free(), CustomData_from_bmesh_block(), CustomData_set_layer(), Object::data, KeyBlock::data, BMHeader::data, MLoop::e, BMLoop::e, BMesh::edata, BMEditSelection::ele, ELEM, BMesh::elem_index_dirty, Key::elemsize, eModifierType_Hook, FALSE, Mesh::fdata, ListBase::first, MEdge::flag, MVert::flag, MPoly::flag, G, BMEdge::head, BMVert::head, BMFace::head, BMLoop::head, BMEditSelection::htype, i, Object::id, MSelect::index, HookModifierData::indexar, Mesh::key, KEY_RELATIVE, CustomData::layers, BMesh::ldata, Mesh::ldata, BMFace::len, MPoly::loopstart, BMFace::mat_nr, MPoly::mat_nr, ME_ESEL, ME_FSEL, ME_VSEL, MEM_callocN(), MEM_freeN(), mesh_update_customdata_pointers(), Object::modifiers, Mesh::mselect, multires_topology_changed(), Mesh::mvert, CustomDataLayer::name, ModifierData::next, KeyBlock::next, BMEditSelection::next, ID::next, MVert::no, BMVert::no, normal_float_to_short_v3(), NULL, ORIGINDEX_NONE, Object::par1, Object::par2, Object::par3, Object::parent, Object::partype, PARVERT1, PARVERT3, BMesh::pdata, Key::refkey, KeyBlock::relative, BMesh::selected, BMesh::shapenr, sub_v3_v3v3(), BMesh::totedge, Mesh::totedge, KeyBlock::totelem, totelem, BMesh::totface, Mesh::totface, HookModifierData::totindex, CustomData::totlayer, BMesh::totloop, Mesh::totloop, MPoly::totloop, Mesh::totpoly, Mesh::totselect, BMesh::totvert, Mesh::totvert, TRUE, Key::type, ModifierData::type, MSelect::type, CustomDataLayer::type, KeyBlock::uid, CustomDataLayer::uid, MLoop::v, BMLoop::v, BMEdge::v1, MEdge::v1, BMEdge::v2, MEdge::v2, and BMesh::vdata.
Referenced by bmo_bmesh_to_mesh_exec(), bpy_bmesh_to_mesh(), EDBM_mesh_load(), editbtMesh_to_undoMesh(), and mesh_separate_selected().
static int bm_to_mesh_shape_layer_index_from_kb (BMesh * bm, KeyBlock * currkey) [static]
returns customdata shapekey index from a keyblock or -1
Note:
could split this out into a more generic function
Definition at line 468 of file bmesh_mesh_conv.c.
References CD_SHAPEKEY, i, CustomData::layers, CustomData::totlayer, CustomDataLayer::type, KeyBlock::uid, CustomDataLayer::uid, and BMesh::vdata.
Referenced by BM_mesh_bm_to_me().
static BMVert** bm_to_mesh_vertex_map (BMesh * bm, int ototvert) [static]
Definition at line 421 of file bmesh_mesh_conv.c.
References BLI_assert, BM_ITER_MESH, BM_VERTS_OF_MESH, CD_SHAPE_KEYINDEX, CustomData_bmesh_get(), CustomData_has_layer(), BMHeader::data, BMVert::head, i, MEM_callocN(), NULL, ORIGINDEX_NONE, and BMesh::vdata.
Referenced by BM_mesh_bm_to_me().
BLI_INLINE void bmesh_quick_edgedraw_flag (MEdge * med, BMEdge * e)
Definition at line 484 of file bmesh_mesh_conv.c.
References dot_v3v3(), BMLoop::f, MEdge::flag, BMEdge::l, ME_EDGEDRAW, BMFace::no, and BMLoop::radial_next.
Referenced by BM_mesh_bm_to_me().